[ace] Update to 6.5.8
microsoft/vcpkg pull request #10003
Opened 2020-02-10 09:15 UTC by jwillemsen

Update ACE to 6.5.8

- What does your PR fix? Fixes issue #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-02-11 02:51 UTC, NancyLi1013 requested changes

2020-02-11 02:51 UTC, NancyLi1013 commented on ports/ace/portfile.cmake
>  if(VCPKG_TARGET_IS_WINDOWS)
```
if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
    message(FATAL_ERROR "${PORT} does not currently support UWP")
endif()
```
```
if (TRIPLET_SYSTEM_ARCH MATCHES "arm")
    message(FATAL_ERROR "ARM is currently not supported.")
```
These two parts should be placed at the top of this file. They also need to be replaced by `vcpkg_fail_port_install(ON_ARCH "arm" ON_TARGET "uwp")`.

2020-02-11 02:51 UTC, NancyLi1013 commented on ports/ace/portfile.cmake
>    file(RENAME ${CURRENT_PACKAGES_DIR}/share/ace/COPYING ${CURRENT_PACKAGES_DIR}/share/ace/copyright)
Could you update 
`file(RENAME ${CURRENT_PACKAGES_DIR}/share/ace/COPYING ${CURRENT_PACKAGES_DIR}/share/ace/copyright)`
as
`file(RENAME ${CURRENT_PACKAGES_DIR}/share/ace/COPYING ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)`?

2020-02-11 07:12 UTC, jwillemsen commented on ports/ace/portfile.cmake
>    file(RENAME ${CURRENT_PACKAGES_DIR}/share/ace/COPYING ${CURRENT_PACKAGES_DIR}/share/ace/copyright)
Done

2020-02-11 17:32 UTC, jwillemsen commented
Comments fixed

2020-02-12 14:46 UTC, NancyLi1013 commented
Hi @jwillemsen thanks for this PR.

LGTM now.

Note: All features have passed with the following triplets:
- x86-windows
- x64-windows-static

2020-02-14 01:38 UTC, merged

2020-02-14 01:38 UTC, ras0219-msft commented
LGTM, thanks for the update!