add mirror for mpfr at gnu.org
microsoft/vcpkg pull request #10035
Opened 2020-02-12 11:57 UTC by michaelkonecny

adding a download mirror after having experienced and extended downtime of mpfr.org

2020-02-12 12:50 UTC, LilyWangL commented
@michaelkonecny Can you please correct the Version field in the CONTROL file?

2020-02-12 12:50 UTC, LilyWangL requested changes

2020-02-12 12:50 UTC, LilyWangL commented on ports/mpfr/portfile.cmake
>  include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-02-12 12:50 UTC, LilyWangL commented on ports/mpfr/portfile.cmake
>  )
Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-02-12 13:19 UTC, michaelkonecny commented
> @michaelkonecny Can you please correct the Version field in the CONTROL file?

This is my first time working with vcpkg. My though is maybe the "-1" in the version number is there for a reason. I don't want to break anything.

Are you sure it's ok to change it?

2020-02-13 02:29 UTC, LilyWangL commented
You can update `Version: 4.0.2-1` to `Version: 4.0.2-2`. This is [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md) documention. You can get more information from it.

2020-03-27 03:05 UTC, LilyWangL commented
Pinging @michaelkonecny for response. Is work still being done for this PR?

2020-03-27 09:51 UTC, michaelkonecny commented
Hi, sorry, got distracted. I will do this tonight.

2020-03-27 20:14 UTC, michaelkonecny commented on ports/mpfr/portfile.cmake
>  )
1) are you sure it is ok to have COPY and RENAME on the same line?
2) there is no LICENSE.md file in ${SOURCE_PATH}
3) I haven't found what ${PORT} is

Do you just want me to change COPY to INSTALL?
Please be more clear next time.

2020-03-30 08:17 UTC, LilyWangL commented on ports/mpfr/portfile.cmake
>  )
Sorry, it is my fault. The command should be `file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`. For this port, `${PORT}` is mpfr.

2020-03-30 19:34 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10035) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10035) before we can accept your contribution.<br/><br/>:x: michaelkonecny [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10035)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10035) it.</sub>

2020-03-30 19:46 UTC, michaelkonecny commented on ports/mpfr/portfile.cmake
>  )
OK, thanks.

Done.

2020-04-02 02:54 UTC, LilyWangL commented
/azp run

2020-04-02 03:48 UTC, LilyWangL approved these changes

2020-04-06 22:21 UTC, merged

2020-04-06 22:21 UTC, dan-shaw commented
thanks for the PR!