[replxx] Add new port
microsoft/vcpkg pull request #10052
Opened 2020-02-13 12:39 UTC by kreuzerkrieg

- What does your PR fix?
replxx new port
- Which triplets are supported/not supported?
All except UWP
- Have you updated the CI baseline?
Yes
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-02-14 06:12 UTC, NancyLi1013 requested changes

2020-02-14 06:12 UTC, NancyLi1013 commented on ports/replxx/CONTROL
> +Description: A small, portable GNU readline replacement for Linux, Windows and MacOS which is capable of handling UTF-8 characters.
Since this port doesn't support uwp, we can add this here.
`Supports: !uwp`

2020-02-14 06:12 UTC, NancyLi1013 commented
/azp run

2020-02-20 01:59 UTC, NancyLi1013 commented
/azp run

2020-02-20 20:25 UTC, kreuzerkrieg commented
/azp run

2020-02-20 20:26 UTC, kreuzerkrieg commented
> Commenter does not have sufficient privileges for PR 10052 in repo microsoft/vcpkg

:(
bad azure

2020-03-03 12:01 UTC, NancyLi1013 approved these changes

2020-03-04 03:06 UTC, JackBoosY commented
@kreuzerkrieg Just because the member has permission to rerun the test : )

2020-03-04 13:24 UTC, JackBoosY requested changes

2020-03-04 13:24 UTC, JackBoosY commented on ports/replxx/usage
> +    TARGET_LINK_LIBRARIES(main PRIVATE REPLXX::replxx) for linkage
Could you remove `for linkage`?
Usually, the user copy these 2 lines to CMakeLists.txt.

2020-03-04 13:24 UTC, JackBoosY commented on ports/replxx/replxxConfig.cmake
> +set_library_target("REPLXX" "replxx" "${ROOT}/debug/lib/libreplxx-d.a" "${ROOT}/lib/libreplxx.a" "${ROOT}/include/")
If this port support Windows or OSX, I think `.a` is not suitable here.

2020-03-04 14:50 UTC, kreuzerkrieg commented on ports/replxx/usage
> +    TARGET_LINK_LIBRARIES(main PRIVATE REPLXX::replxx) for linkage
Done

2020-03-04 14:51 UTC, kreuzerkrieg commented on ports/replxx/replxxConfig.cmake
> +set_library_target("REPLXX" "replxx" "${ROOT}/debug/lib/libreplxx-d.a" "${ROOT}/lib/libreplxx.a" "${ROOT}/include/")
Changed for Win
As of OSX, shouldnt it be `.a`? afterall it is BSD based OS

2020-03-05 03:23 UTC, NancyLi1013 commented
Hi @kreuzerkrieg 

The errors like this:
```
Performing C++ SOURCE FILE Test COMPILER_HAS_DEPRECATED_ATTR failed with the following output:
Change Dir: E:/10052/vcpkg/buildtrees/replxx/src/7827007a8c-9c9af6846f/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_df6f8 
[1/2] Building CXX object CMakeFiles\cmTC_df6f8.dir\src.cxx.obj

FAILED: CMakeFiles/cmTC_df6f8.dir/src.cxx.obj 

C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  -DCOMPILER_HAS_DEPRECATED_ATTR /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_df6f8.dir\src.cxx.obj /FdCMakeFiles\cmTC_df6f8.dir\ /FS -c src.cxx

src.cxx(1): error C2065: '__deprecated__': undeclared identifier
src.cxx(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
src.cxx(1): error C2448: '__attribute__': function-style initializer appears to be a function definition
ninja: build stopped: subcommand failed.

Source file was:
__attribute__((__deprecated__)) int somefunc() { return 0; }
    int main() { return somefunc();}
Performing C++ SOURCE FILE Test COMPILER_HAS_DEPRECATED_ATTR failed with the following output:
Change Dir: E:/10052/vcpkg/buildtrees/replxx/src/7827007a8c-9c9af6846f/build/CMakeFiles/CMakeTmp
```
This info is from my local.
 This port can build successfully on `x86-windows` triplet, but we still can get this error in
`E:/10052/vcpkg/buildtrees/replxx/src/7827007a8c-9c9af6846f/build/CMakeFiles/CMakeError.log` file.

Personally, it might be the root cause of CI regression.
Could you please help chect this on your local?

2020-03-05 05:48 UTC, kreuzerkrieg commented
Checked and it worked. I have another Win machine, will check it later, AFAIR it has older VS, like 2017, maybe it will repro there

2020-03-05 16:59 UTC, kreuzerkrieg commented
> c:\vcpkg\vcpkg>vcpkg.exe install replxx
> Computing installation plan...
> The following packages will be built and installed:
>     replxx[core]:x86-windows
> Starting package 1/1: replxx:x86-windows
> Building package replxx[core]:x86-windows...
> -- Downloading https://github.com/AmokHuginnsson/replxx/archive/45696c250ce39ab21dedeea962b94d7827007a8c.tar.gz...
> -- Extracting source C:/vcpkg/vcpkg/downloads/AmokHuginnsson-replxx-45696c250ce39ab21dedeea962b94d7827007a8c.tar.gz
> -- Using source at C:/vcpkg/vcpkg/buildtrees/replxx/src/7827007a8c-9c9af6846f
> -- Configuring x86-windows
> -- Building x86-windows-dbg
> -- Building x86-windows-rel
> -- Installing: C:/vcpkg/vcpkg/packages/replxx_x86-windows/share/replxx/copyright
> -- Installing: C:/vcpkg/vcpkg/packages/replxx_x86-windows/share/replxx/replxxConfig.cmake
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package replxx[core]:x86-windows... done
> Installing package replxx[core]:x86-windows...
> Installing package replxx[core]:x86-windows... done
> Elapsed time for package replxx:x86-windows: 43.71 s
> 
> Total elapsed time: 43.71 s
> 
> 
> c:\vcpkg\vcpkg>vcpkg.exe install replxx:x64-windows
> Computing installation plan...
> The following packages will be built and installed:
>     replxx[core]:x64-windows
> Starting package 1/1: replxx:x64-windows
> Building package replxx[core]:x64-windows...
> -- Using cached C:/vcpkg/vcpkg/downloads/AmokHuginnsson-replxx-45696c250ce39ab21dedeea962b94d7827007a8c.tar.gz
> -- Using source at C:/vcpkg/vcpkg/buildtrees/replxx/src/7827007a8c-9c9af6846f
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Installing: C:/vcpkg/vcpkg/packages/replxx_x64-windows/share/replxx/copyright
> -- Installing: C:/vcpkg/vcpkg/packages/replxx_x64-windows/share/replxx/replxxConfig.cmake
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package replxx[core]:x64-windows... done
> Installing package replxx[core]:x64-windows...
> Installing package replxx[core]:x64-windows... done
> Elapsed time for package replxx:x64-windows: 34.84 s
> 
> Total elapsed time: 34.84 s


Not sure what else I can do on my side. I dont even fully understand what fails in your CI, looks like it is a CMake internal compilation of their internal cpp to check for compiler features. Looks like the MSVC miserably fails to detect a CXX feature, sounds like mismatch between MSVC and CMAKE versions. [This ](https://stackoverflow.com/questions/47135488/performing-test-compiler-has-deprecated-attr-failed)may be related.
Sounds like Gor Nishanov needed here :)

2020-03-10 07:00 UTC, JackBoosY commented
@strega-nil Could you please have a look?

2020-03-16 11:37 UTC, kreuzerkrieg commented
bump

2020-03-17 01:20 UTC, JackBoosY approved these changes

2020-03-17 20:29 UTC, strega-nil commented
cc @dan-shaw

2020-03-19 22:58 UTC, dan-shaw commented
/azp run

2020-03-20 02:57 UTC, JackBoosY commented
Please resolve windows regression, get failure log [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=31536&view=artifacts&type=publishedArtifacts).

2020-03-20 06:06 UTC, dan-shaw commented
@kreuzerkrieg We are still getting the same error as before and I'm not sure what is causing the problem. Could we set this library as failing on the baseline? If someone else has the same issue, we can fix it in another PR.

2020-03-20 09:28 UTC, kreuzerkrieg commented
done

2020-03-22 07:48 UTC, JackBoosY approved these changes

2020-03-28 03:43 UTC, merged

2020-03-28 03:43 UTC, dan-shaw commented
@kreuzerkrieg thanks for the PR!