add feature build vtk[qtopengl]
microsoft/vcpkg pull request #10060
Opened 2020-02-13 22:35 UTC by jafrado

**Describe the pull request**

- What does your PR fix? Fixes issue #10027
https://github.com/microsoft/vcpkg/issues/10027

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-02-13 22:35 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10060) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10060) before we can accept your contribution.<br/><br/>:x: jafrado [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10060)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10060) it.</sub>

2020-02-13 22:36 UTC, jafrado commented
@NancyLi1013 - fix for this issue.

2020-02-14 09:33 UTC, LilyWangL commented
/azp run

2020-02-14 11:48 UTC, Neumann-A commented on ports/vtk/CONTROL
> +Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c, qt5
don't add qt5 here

2020-02-14 11:48 UTC, Neumann-A commented on ports/vtk/CONTROL
> +Build-Depends: qt5
don't add all of qt5. You probably only need qt5-base

2020-02-14 11:49 UTC, Neumann-A commented on ports/vtk/CONTROL
> +Build-Depends: qt5
also you can depend on vtk[core,qt5]

2020-02-14 11:49 UTC, Neumann-A commented on ports/vtk/portfile.cmake
> +    )
only add the new switches. Don't overlap with vtk[qt5]. Depend on vtk[core,qt5]

2020-02-14 23:21 UTC, jafrado reviewed
Will resubmit new change set.

2020-02-14 23:21 UTC, jafrado commented on ports/vtk/CONTROL
> +Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c, qt5
thanks, good catch.

2020-02-14 23:21 UTC, jafrado commented on ports/vtk/CONTROL
> +Build-Depends: qt5
Good call, this will reduce the build time substantially, however, it also needs qt5-tools,  
(if you only include qt5-base, it fails as below):
```
CMake Error at C:/src/vcpkg/work/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  Could not find a package configuration file provided by "Qt5UiPlugin" with
  any of the following names:

    Qt5UiPluginConfig.cmake
    qt5uiplugin-config.cmake

  Add the installation prefix of "Qt5UiPlugin" to CMAKE_PREFIX_PATH or set
  "Qt5UiPlugin_DIR" to a directory containing one of the above files.  If
  "Qt5UiPlugin" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  C:/src/vcpkg/work/vcpkg/installed/x86-windows/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  C:/src/vcpkg/work/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package)
  GUISupport/Qt/CMakeLists.txt:128 (find_package)
```
Note that this has the effect of also bringing in:
```
  * qt5-activeqt[core]:x64-windows
  * qt5-base[core]:x64-windows
  * qt5-declarative[core]:x64-windows
  * qt5-imageformats[core]:x64-windows
  * qt5-svg[core]:x64-windows
```
Which is still better than the whole Qt5 package!

2020-02-14 23:21 UTC, jafrado commented on ports/vtk/portfile.cmake
> +    )
Yes - sorry that's a typo! Fixed.

2020-02-17 19:06 UTC, jafrado commented
I'm not sure why this is failing... I get this on the Linux build ... which works for me (same as Windows)
![image](https://user-images.githubusercontent.com/11479564/74680475-8e618280-5175-11ea-9194-20add2d340c0.png)

2020-02-17 19:26 UTC, jafrado commented
![image](https://user-images.githubusercontent.com/11479564/74681454-4ee86580-5178-11ea-8dad-db2940106dd8.png)

Not sure how to fix the above pipeline checks ... or even if they are related.

2020-03-04 10:51 UTC, LilyWangL commented
/azp run

2020-03-04 12:34 UTC, LilyWangL commented
@jafrado Thanks for your PR. Current this port build failed with the following error, could you please continue to fix it?
```
CMake Error at C:/vsts/_work/3/s/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  GUISupport/Qt/CMakeLists.txt:71 (find_package)
```

2020-03-04 20:09 UTC, jafrado commented
@LilyWangL - thanks, did you run this patch-set: https://github.com/microsoft/vcpkg/pull/10060/commits/993267bc3e78bd0c4a3adbe474b2a1a8401b171c

The error you see should not be present, since the lines:
```
Build-Depends: qt5-base, qt5-tools, vtk[core]
```

include qt5-tools which has the qt5-config.cmake

Let me know and I can repost the original patch.

2020-03-05 07:27 UTC, LilyWangL commented
I cloned your latest commit and reproduced the CI test error. Due to `-DModule_vtkGUISupportQt=ON`, vtk build failed with this error:
```
CMake Error at C:/vsts/_work/3/s/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  GUISupport/Qt/CMakeLists.txt:71 (find_package)
```
This error appear when cmake _vtk/src/v8.2.0-d1dd9405dd/GUISupport/Qt/CMakeLists.txt Line71_.

2020-03-05 19:36 UTC, jafrado commented
@LilyWangL - thanks, I will check it out.

2020-03-21 05:49 UTC, princetonpku commented
I try the new port.cmake and isntall use following:
`vcpkg install vtk[qt,qtopengl]:x64-windows`

Howerver, the "vtkQtLabelRenderStrategy.h" is not installed. Is any solution for this?

2020-03-26 05:37 UTC, JackBoosY commented
/azp run

2020-03-27 04:28 UTC, jafrado commented
This is really weird. This works for me and I have it checked in to my repo for some time now.
Can you send me the build error?

2020-03-27 05:49 UTC, JackBoosY commented
Rerun test maually, I will give you failure log later.

2020-03-27 06:55 UTC, JackBoosY commented
```
...
-- Found Eigen3: G:/10060/vcpkg/installed/x86-windows/include/eigen3 (Required is at least version "2.91.0") 
-- Found ZLIB: optimized;G:/10060/vcpkg/installed/x86-windows/lib/zlib.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/zlibd.lib (found version "1.2.11") 
-- Found Freetype: optimized;G:/10060/vcpkg/installed/x86-windows/lib/freetype.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/freetyped.lib (found version "2.10.1") 
-- Found double-conversion: G:/10060/vcpkg/installed/x86-windows/include/double-conversion  
-- Found LZ4: optimized;G:/10060/vcpkg/installed/x86-windows/lib/lz4.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/lz4d.lib  
-- Found LZMA: optimized;G:/10060/vcpkg/installed/x86-windows/lib/lzma.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/lzmad.lib  
-- Found EXPAT: G:/10060/vcpkg/installed/x86-windows/lib/expat.lib (found version "2.2.7") 
-- Found OpenGL: opengl32   
CMake Error at G:/10060/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  GUISupport/Qt/CMakeLists.txt:71 (find_package)


-- Configuring incomplete, errors occurred!
```

2020-03-27 07:14 UTC, jafrado commented
Thanks, will check it out tomorrow.

2020-03-27 19:51 UTC, jafrado commented
Yep, broken. Hang on, lets go back to basics ...

On Thu, Mar 26, 2020 at 11:55 PM Jack·Boos·Yu <notifications@github.com>
wrote:

> ...
> -- Found Eigen3: G:/10060/vcpkg/installed/x86-windows/include/eigen3 (Required is at least version "2.91.0")
> -- Found ZLIB: optimized;G:/10060/vcpkg/installed/x86-windows/lib/zlib.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/zlibd.lib (found version "1.2.11")
> -- Found Freetype: optimized;G:/10060/vcpkg/installed/x86-windows/lib/freetype.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/freetyped.lib (found version "2.10.1")
> -- Found double-conversion: G:/10060/vcpkg/installed/x86-windows/include/double-conversion
> -- Found LZ4: optimized;G:/10060/vcpkg/installed/x86-windows/lib/lz4.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/lz4d.lib
> -- Found LZMA: optimized;G:/10060/vcpkg/installed/x86-windows/lib/lzma.lib;debug;G:/10060/vcpkg/installed/x86-windows/debug/lib/lzmad.lib
> -- Found EXPAT: G:/10060/vcpkg/installed/x86-windows/lib/expat.lib (found version "2.2.7")
> -- Found OpenGL: opengl32
> CMake Error at G:/10060/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
>   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5", but
>   CMake did not find one.
>
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
>
>     Qt5Config.cmake
>     qt5-config.cmake
>
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   GUISupport/Qt/CMakeLists.txt:71 (find_package)
>
>
> -- Configuring incomplete, errors occurred!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/10060#issuecomment-604844968>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXSUDFENXJLTZP4KXMU4OTRJREXNANCNFSM4KU4LT7A>
> .
>

2020-03-27 20:37 UTC, jafrado commented
Ok, lets try listing qt5-tools first to pickup Qt5Config.cmake, qt5-config.cmake before qtbase, otherwise we can just list the whole qt5 package as a dependency (which is what we have checked in to make a working software where I am working right now). 

See if this change works:
https://github.com/microsoft/vcpkg/pull/10060/commits/3f9925316c8dc8ab75d964031b85294e5bf9b526

2020-03-27 22:09 UTC, Neumann-A commented
order does not matter in vcpkg

2020-03-27 22:11 UTC, Neumann-A commented
From my paraview PR
```
Feature: qt
Description: Qt functionality for VTK
Build-Depends: qt5-xmlpatterns, qt5-tools, qt5-imageformats, qt5-x11extras (linux)
```

2020-03-30 07:13 UTC, JackBoosY commented
Same error as above.

2020-03-30 18:13 UTC, jafrado commented
Thank you @JackBoosY  - @Neumann-A  - so what do you think is the issue? I went back and if I add qt5, it does work. Maybe it is better to put this all under Qt build (I always wondered why it didn't build this widget)? Your feedback would be greatly appreciated - thank you!

2020-03-30 18:22 UTC, jafrado commented
Mmmmmm... maybe I am making stuff up, but this failure does not seem to be related to me on OS-X/Linux, those fail with missing packages:
``
You will need to install Xorg dependencies to build vtk:
apt-get install libxt-dev
``

On Windows, the error below:

Using source at C:/vsts/_work/3/s/buildtrees/vtk/src/v8.2.0-d1dd9405dd
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vsts/_work/3/s/buildtrees/vtk/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vsts\_work\3\s\buildtrees\vtk\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:105 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Where do I get this file?      C:\vsts\_work\3\s\buildtrees\vtk\config-x86-windows-out.log

2020-03-31 05:46 UTC, JackBoosY commented
Please get log [here](https://github.com/microsoft/vcpkg/files/4406988/config-x86-windows-out.log).

2020-04-01 05:59 UTC, jafrado commented
Thanks, I will upload a new patch tomorrow.

On Mon, Mar 30, 2020 at 10:46 PM Jack·Boos·Yu <notifications@github.com>
wrote:

> Please get log here
> <https://github.com/microsoft/vcpkg/files/4406988/config-x86-windows-out.log>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/10060#issuecomment-606413451>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXSUDE56BFPH37TPDUPEPTRKF7SNANCNFSM4KU4LT7A>
> .
>

2020-04-09 03:19 UTC, JackBoosY commented
@jafrado Any progress?

2020-04-09 17:06 UTC, jafrado commented
Lets try this one ... I added back all Qt dependencies... the more I work on this, the more it becomes like the original patch I had, which works now and is in production.

2020-04-16 17:05 UTC, jafrado commented
Let me know how to check/resolve this one. The patches I provided work here locally for me. I guess I need to know how to run your pre-commit

2020-05-08 04:54 UTC, JackBoosY commented
Any progress?

2020-05-09 17:32 UTC, jafrado commented
Thanks, will take a look this week. Can you send a link to your CI
setup/test docs?

On Thu, May 7, 2020 at 9:54 PM Jack·Boos·Yu <notifications@github.com>
wrote:

> Any progress?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/10060#issuecomment-625629635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXSUDBEN3UGCDAFCLVMCOTRQOGAVANCNFSM4KU4LT7A>
> .
>

2020-05-09 18:15 UTC, Neumann-A commented
@jafrado he is probably asking because #11148 is updating VTK to 9.0

2020-05-11 02:37 UTC, JackBoosY commented
/azp run

2020-05-11 09:26 UTC, JackBoosY commented
`x64-linux` regression(vtk):
```
CMake Error at /mnt/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
  Could not find a package configuration file provided by "Qt5X11Extras" with
  any of the following names:

    Qt5X11ExtrasConfig.cmake
    qt5x11extras-config.cmake

  Add the installation prefix of "Qt5X11Extras" to CMAKE_PREFIX_PATH or set
  "Qt5X11Extras_DIR" to a directory containing one of the above files.  If
  "Qt5X11Extras" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /mnt/1/s/installed/x64-linux/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /mnt/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  GUISupport/Qt/CMakeLists.txt:71 (find_package)
```

`x64-osx` regression(pcl):
```
CMake Error at /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Core/Qt5CoreConfig.cmake:113 (message):
  Library not found: m
Call Stack (most recent call first):
  /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Core/Qt5CoreConfig.cmake:195 (_qt5_Core_parse_prl)
  /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Core/Qt5CoreConfig.cmake:317 (_populate_Core_target_properties)
  /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:255 (find_package)
  /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:255 (find_package)
  /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  /Volumes/data/work/1/s/installed/x64-osx/share/vtk/Modules/vtkGUISupportQt.cmake:19 (find_package)
  /Volumes/data/work/1/s/installed/x64-osx/share/vtk/vtkModuleAPI.cmake:45 (include)
  /Volumes/data/work/1/s/installed/x64-osx/share/vtk/vtkModuleAPI.cmake:15 (vtk_module_load)
  /Volumes/data/work/1/s/installed/x64-osx/share/vtk/vtkModuleAPI.cmake:152 (_vtk_module_config_recurse)
  /Volumes/data/work/1/s/installed/x64-osx/share/vtk/VTKConfig.cmake:137 (vtk_module_config)
  /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:364 (find_package)
```

2020-05-11 19:59 UTC, jafrado commented
My core development platform is Linux and I don't have that error. If there
is something I can read to try to debug your Azure pipeline let me know.
Otherwise, I will wait for you to update to VTK 9 and then retest and see
if it works.



On Mon, May 11, 2020 at 2:26 AM Jack·Boos·Yu <notifications@github.com>
wrote:

> x64-linux regression(vtk):
>
> CMake Error at /mnt/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
>   Could not find a package configuration file provided by "Qt5X11Extras" with
>   any of the following names:
>
>     Qt5X11ExtrasConfig.cmake
>     qt5x11extras-config.cmake
>
>   Add the installation prefix of "Qt5X11Extras" to CMAKE_PREFIX_PATH or set
>   "Qt5X11Extras_DIR" to a directory containing one of the above files.  If
>   "Qt5X11Extras" provides a separate development package or SDK, be sure it
>   has been installed.
> Call Stack (most recent call first):
>   /mnt/1/s/installed/x64-linux/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
>   /mnt/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
>   GUISupport/Qt/CMakeLists.txt:71 (find_package)
>
> x64-osx regression(pcl):
>
> CMake Error at /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Core/Qt5CoreConfig.cmake:113 (message):
>   Library not found: m
> Call Stack (most recent call first):
>   /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Core/Qt5CoreConfig.cmake:195 (_qt5_Core_parse_prl)
>   /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Core/Qt5CoreConfig.cmake:317 (_populate_Core_target_properties)
>   /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
>   /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:255 (find_package)
>   /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
>   /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:255 (find_package)
>   /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
>   /Volumes/data/work/1/s/installed/x64-osx/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
>   /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
>   /Volumes/data/work/1/s/installed/x64-osx/share/vtk/Modules/vtkGUISupportQt.cmake:19 (find_package)
>   /Volumes/data/work/1/s/installed/x64-osx/share/vtk/vtkModuleAPI.cmake:45 (include)
>   /Volumes/data/work/1/s/installed/x64-osx/share/vtk/vtkModuleAPI.cmake:15 (vtk_module_load)
>   /Volumes/data/work/1/s/installed/x64-osx/share/vtk/vtkModuleAPI.cmake:152 (_vtk_module_config_recurse)
>   /Volumes/data/work/1/s/installed/x64-osx/share/vtk/VTKConfig.cmake:137 (vtk_module_config)
>   /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
>   CMakeLists.txt:364 (find_package)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/10060#issuecomment-626585366>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXSUDBLFI6MQXBY655F2N3RQ7AFTANCNFSM4KU4LT7A>
> .
>

2020-05-12 03:17 UTC, JackBoosY commented
@jafrado Please get full logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=36597&view=artifacts&type=publishedArtifacts).

2020-05-12 03:19 UTC, jafrado commented
Thanks, I saw that, I'm trying to recreate the issue. Not just spam the
problem with run after run of commits. Is there a way to recreate or test
changes in the CI environment?

On Mon, May 11, 2020 at 8:17 PM Jack·Boos·Yu <notifications@github.com>
wrote:

> @jafrado <https://github.com/jafrado> Please get full logs here
> <https://dev.azure.com/vcpkg/public/_build/results?buildId=36597&view=artifacts&type=publishedArtifacts>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/10060#issuecomment-627083333>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXSUDD7BBTWD3GHMGJT67TRRC5WFANCNFSM4KU4LT7A>
> .
>

2020-05-12 03:21 UTC, jafrado commented
Can you try to install this in your CI environment?
CMake Warning at ports/vtk/portfile.cmake:2 (message):
  You will need to install Xorg dependencies to build vtk:

  apt-get install libxt-dev

Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)


On Mon, May 11, 2020 at 8:19 PM James Dougherty <jafrado@gmail.com> wrote:

> Thanks, I saw that, I'm trying to recreate the issue. Not just spam the
> problem with run after run of commits. Is there a way to recreate or test
> changes in the CI environment?
>
> On Mon, May 11, 2020 at 8:17 PM Jack·Boos·Yu <notifications@github.com>
> wrote:
>
>> @jafrado <https://github.com/jafrado> Please get full logs here
>> <https://dev.azure.com/vcpkg/public/_build/results?buildId=36597&view=artifacts&type=publishedArtifacts>
>> .
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/microsoft/vcpkg/pull/10060#issuecomment-627083333>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ACXSUDD7BBTWD3GHMGJT67TRRC5WFANCNFSM4KU4LT7A>
>> .
>>
>

2020-05-12 06:03 UTC, JackBoosY requested changes

2020-05-12 06:03 UTC, JackBoosY commented on ports/vtk/CONTROL
> +Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c, qt5
```suggestion
Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c
```

2020-05-12 06:03 UTC, JackBoosY commented on ports/vtk/CONTROL
>  Version: 8.2.0-12
```suggestion
Version: 8.2.0-13
```

2020-05-12 16:09 UTC, jafrado commented
I just pulled the latest master, it looks like it includes QtOpenGL support
and VTK 9.0
Let me test it out this week - more later.


On Mon, May 11, 2020 at 11:04 PM Jack·Boos·Yu <notifications@github.com>
wrote:

> *@JackBoosY* requested changes on this pull request.
> ------------------------------
>
> In ports/vtk/CONTROL
> <https://github.com/microsoft/vcpkg/pull/10060#discussion_r423480822>:
>
> > @@ -2,7 +2,7 @@ Source: vtk
>
>  Version: 8.2.0-12
>
>  Description: Software system for 3D computer graphics, image processing, and visualization
>
>  Homepage: https://github.com/Kitware/VTK
>
> -Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c
>
> +Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c, qt5
>
>
> ⬇️ Suggested change
>
> -Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c, qt5
>
> +Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c
>
>
> ------------------------------
>
> In ports/vtk/CONTROL
> <https://github.com/microsoft/vcpkg/pull/10060#discussion_r423480886>:
>
> > @@ -2,7 +2,7 @@ Source: vtk
>
>  Version: 8.2.0-12
>
>
> ⬇️ Suggested change
>
> -Version: 8.2.0-12
>
> +Version: 8.2.0-13
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/10060#pullrequestreview-409721041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXSUDHW47XJNMCQHLELO63RRDRFRANCNFSM4KU4LT7A>
> .
>

2020-05-13 02:10 UTC, JackBoosY commented
```
CMake Error at /home/vzay/work/10060/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package):
  Could not find a package configuration file provided by "Qt5X11Extras" with
  any of the following names:

    Qt5X11ExtrasConfig.cmake
    qt5x11extras-config.cmake

  Add the installation prefix of "Qt5X11Extras" to CMAKE_PREFIX_PATH or set
  "Qt5X11Extras_DIR" to a directory containing one of the above files.  If
  "Qt5X11Extras" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /home/vzay/work/10060/vcpkg/installed/x64-linux/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /home/vzay/work/10060/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  GUISupport/Qt/CMakeLists.txt:71 (find_package)
```

2020-05-13 02:13 UTC, JackBoosY commented on ports/vtk/CONTROL
> +Description: Mfc functionality for VTK on Windows
Did you revert your changes?

2020-05-13 04:22 UTC, jafrado commented on ports/vtk/CONTROL
> +Description: Mfc functionality for VTK on Windows
I merged to master.

2020-05-13 04:22 UTC, jafrado commented on ports/vtk/CONTROL
> +Description: Mfc functionality for VTK on Windows
yes

2020-06-16 09:00 UTC, JackBoosY requested changes

2020-06-16 09:00 UTC, JackBoosY commented on ports/vtk/portfile.cmake
> +if(VTK_WITH_QT_OPENGL)
Where this value is not set, I think it is always 0.

2020-07-09 22:00 UTC, BillyONeal commented
If this was waiting for a VM change that might have been done now in support of the Qt update change merged recently.

2020-07-09 22:00 UTC, ras0219-msft commented
Hey @jafrado, is there work still to be done here? Are the linked issues still applicable after #11596?

2020-07-10 12:01 UTC, Neumann-A commented
@JackBoosY @BillyONeal: This PR can probably be closed due to the update to VTK 9 which includes opengl feature. 
```
if("opengl" IN_LIST FEATURES)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_MODULE_ENABLE_VTK_DomainsChemestryOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_ImagingOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingContextOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingGL2PSOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingLICOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingVolumeOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_opengl=YES
        )
endif()
```

```
if("qt" IN_LIST FEATURES)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_GROUP_ENABLE_Qt=YES
        -DVTK_MODULE_ENABLE_VTK_GUISupportQt=YES
        -DVTK_MODULE_ENABLE_VTK_GUISupportQtSQL=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingQt=YES
        -DVTK_MODULE_ENABLE_VTK_ViewsQt=YES
    )
endif()
```

2020-07-10 15:06 UTC, jafrado commented
Yes. Please close. Thank you all very much for your support!

2020-07-10 15:32 UTC, jafrado commented
Please disregard last commit. Thanks again!

2020-07-13 02:12 UTC, JackBoosY commented
Thanks for this PR!

2020-07-13 02:12 UTC, closed without merging