[freetype] Disabled Harfbuzz check for non-Windows platforms
microsoft/vcpkg pull request #10073
Opened 2020-02-14 12:14 UTC by capnkenny

- What does your PR fix? 
Fixes issue #10041 
Resolves linking errors when building on Linux-based platforms

- Which triplets are supported/not supported? Have you updated the CI baseline?
 No change.
 
- Does your PR follow the maintainer guide?
 I think so.

2020-02-14 12:14 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10073) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10073) before we can accept your contribution.<br/><br/>:x: capnkenny [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10073)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10073) it.</sub>

2020-02-14 12:48 UTC, PhoebeHui requested changes
@capnkenny, thanks for the PR!

Could you also update the version to '2.10.1-5' in [CONTROL](https://github.com/microsoft/vcpkg/blob/5f12ffae8d6444383ed6d88da08ee32876726ebc/ports/freetype/CONTROL) file?

2020-02-14 12:48 UTC, PhoebeHui commented on ports/freetype/portfile.cmake
> +endif()
Could you please update this to

```
set(OPTIONS)
if (NOT VCPKG_TARGET_IS_WINDOWS)
  list(APPEND OPTIONS -DFT_DISABLE_FIND_PACKAGE_Harfbuzz=TRUE)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DCONFIG_INSTALL_PATH=share/freetype
        -DFT_WITH_ZLIB=ON # Force system zlib.
        ${FEATURE_OPTIONS}
        -DENABLE_DLL_EXPORT=${ENABLE_DLL_EXPORT}
        ${OPTIONS}
)
```

2020-02-14 13:08 UTC, capnkenny commented on ports/freetype/portfile.cmake
> +endif()
Made both changes as requested 👍

2020-02-15 11:28 UTC, PhoebeHui commented
The failures doesn't related to this changes, I will help  rerun after the baseline issue fixed.

2020-02-15 11:28 UTC, PhoebeHui approved these changes

2020-02-20 00:55 UTC, PhoebeHui commented
/azp run

2020-03-11 00:28 UTC, strega-nil commented
Cool, thanks @capnkenny :)

2020-03-11 00:28 UTC, merged