[fmt] Update to 6.1.2
microsoft/vcpkg pull request #10080
Opened 2020-02-15 04:15 UTC by curoky

This PR changes:
1. Update to latest revision 6.1.2
2. Update patch fix-warning4189

2020-02-15 11:22 UTC, PhoebeHui requested changes
@curoky, thanks for the PR!

Could you also bump the version in CONTROL file?

2020-02-15 12:22 UTC, curoky commented
Done.

2020-02-18 10:09 UTC, PhoebeHui commented
@curoky, the patch applied failed in CI testing, could you update the patch?

Checking patch include/fmt/format.h...
error: while searching for:

#ifndef FMT_FORMAT_H_
#define FMT_FORMAT_H_

#include <algorithm>
#include <cerrno>
#include <cmath>

error: patch failed: include/fmt/format.h:32
error: include/fmt/format.h: patch does not apply

2020-02-19 08:26 UTC, curoky commented
Done.
spdlog also needs to be upgraded or patched. Because the dependent header files are not in this version of fmt.
```bash
[1/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/fmt.cpp.o -MF CMakeFiles/spdlog.dir/src/fmt.cpp.o.d -o CMakeFiles/spdlog.dir/src/fmt.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/fmt.cpp
[2/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/spdlog.cpp.o -MF CMakeFiles/spdlog.dir/src/spdlog.cpp.o.d -o CMakeFiles/spdlog.dir/src/spdlog.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/spdlog.cpp
FAILED: CMakeFiles/spdlog.dir/src/spdlog.cpp.o 
/usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/spdlog.cpp.o -MF CMakeFiles/spdlog.dir/src/spdlog.cpp.o.d -o CMakeFiles/spdlog.dir/src/spdlog.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/spdlog.cpp
In file included from /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/spdlog.cpp:13:
/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/pattern_formatter-inl.h: In member function ‘void spdlog::details::scoped_padder::pad_it(size_t)’:
/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/pattern_formatter-inl.h:76:9: error: ‘assert’ was not declared in this scope
   76 |         assert(count <= spaces_.size());
      |         ^~~~~~
compilation terminated due to -Wfatal-errors.
[3/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/async.cpp.o -MF CMakeFiles/spdlog.dir/src/async.cpp.o.d -o CMakeFiles/spdlog.dir/src/async.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/async.cpp
[4/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o -MF CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o.d -o CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/stdout_sinks.cpp
[5/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/file_sinks.cpp.o -MF CMakeFiles/spdlog.dir/src/file_sinks.cpp.o.d -o CMakeFiles/spdlog.dir/src/file_sinks.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/file_sinks.cpp
[6/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /home/curoky/repos/fork/vcpkg/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/color_sinks.cpp.o -MF CMakeFiles/spdlog.dir/src/color_sinks.cpp.o.d -o CMakeFiles/spdlog.dir/src/color_sinks.cpp.o -c /home/curoky/repos/fork/vcpkg/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/color_sinks.cpp
ninja: build stopped: subcommand failed.
```
Should fix it in this PR?

2020-02-19 11:04 UTC, PhoebeHui commented
@curoky, please also fix spdlog  in this PR.

2020-02-20 10:10 UTC, PhoebeHui requested changes
@curoky, thanks for updates!

Could you also bump version in spdlog CONTROL file?

2020-02-20 10:14 UTC, curoky commented
Done.

2020-02-20 10:23 UTC, curoky commented
/azp run

2020-02-20 10:28 UTC, PhoebeHui commented
@curoky, I have rerun CI testing on windows, let's wait for the results.

2020-02-21 00:53 UTC, PhoebeHui commented
@curoky, azure-kinect-sensor-sdk:x64-windows failed on CI testing, could you take a look?

Failures:
- Clang-format not found
CMake Error at CMakeLists.txt:303 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!

2020-02-21 06:46 UTC, curoky commented
The error message is not enough to conclude, try to run again? @PhoebeHui

2020-02-21 08:40 UTC, PhoebeHui commented
I have rerun the CI again, does the issue repro locally?

2020-02-21 08:41 UTC, PhoebeHui commented
The CI test pass.

2020-02-21 08:41 UTC, PhoebeHui approved these changes

2020-02-27 10:00 UTC, kenr commented
Is there anything stopping this to get merged? May I assist if so?

2020-02-27 10:18 UTC, PhoebeHui commented
@strega-nil, could you priority to review and merge this PR?

2020-02-28 03:20 UTC, strega-nil requested changes
This is awesome! thanks for the PR, just some minor changes needed and then I'll merge :)

2020-02-28 03:20 UTC, strega-nil commented on ports/fmt/CONTROL
> +Version: 6.1.2-1
This should be `6.1.2`, instead of `6.1.2-1`

2020-02-28 03:20 UTC, strega-nil commented on ports/fmt/portfile.cmake
> +            if(EXISTS "${CURRENT_PACKAGES_DIR}/debug/lib/fmtd.dll")
Is there a reason that this check is now needed?

2020-02-28 03:20 UTC, strega-nil commented on ports/spdlog/CONTROL
> +Version: 1.4.2-2
I think this should be `1.4.2-1`?

2020-02-28 14:49 UTC, curoky commented on ports/fmt/portfile.cmake
> +            if(EXISTS "${CURRENT_PACKAGES_DIR}/debug/lib/fmtd.dll")
yeah, it will fail to compile in x86-window environment without this check.
> @curoky, please also fix spdlog in this PR.
> 
> fmt also failed on CI testing, could you take a look? does it repro in your local machine?
> -- Installing: C:/vsts/_work/3/s/packages/fmt_x86-windows/share/fmt/copyright
> CMake Error at ports/fmt/portfile.cmake:24 (file):
> file RENAME failed to rename
> C:/vsts/_work/3/s/packages/fmt_x86-windows/debug/lib/fmtd.dll
> to
> C:/vsts/_work/3/s/packages/fmt_x86-windows/debug/bin/fmtd.dll
> 
> because: File exists

I guess the file `fmtd.dll` may not exists, although the error message is `File exists`.

I'm not sure because I don't have window environment.

2020-02-29 03:37 UTC, strega-nil commented
/azp run

2020-03-02 13:51 UTC, PhoebeHui commented
The azure-kinect-sensor-sdk failures is fake, after remove the tombstone, this issue solved.
Now the CI test pass.

2020-03-02 17:35 UTC, merged