[vcpkg] Better vcpkg_apply_patches error message
microsoft/vcpkg pull request #10127
Opened 2020-02-19 03:38 UTC by Pospelove

This PR makes vcpkg_apply_patches to show git error instead of writing it into logs.
I think it would be more reasonable because it's actually one line. It makes easier to understand what's wrong with patches.

Before:
```
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:50 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
  ```

After:
```
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:50 (message):
  Applying patch failed. error: corrupt patch at line 8
  ```

2020-02-20 21:10 UTC, vicroms commented
/azp run

2020-02-21 22:24 UTC, vicroms requested changes

2020-02-21 22:24 UTC, vicroms commented on scripts/cmake/vcpkg_apply_patches.cmake
> +            ERROR_VARIABLE error
We really need to have a patch failure log file for our CI. If we want to have both, then we could do something like the following upon failure:

```cmake
file(WRITE "${CURRENT_BUILDTREES_DIR}/${LOGNAME}-err.log" "${error}")
```

2020-02-22 03:24 UTC, Pospelove commented on scripts/cmake/vcpkg_apply_patches.cmake
> +            ERROR_VARIABLE error
Added this line.

2020-02-25 09:44 UTC, Pospelove commented
So, is that fine for the merge?

2020-02-27 22:22 UTC, merged

2020-02-27 22:22 UTC, ras0219-msft commented
LGTM, thanks for the PR!