add a port for chimera
microsoft/vcpkg pull request #10132
Opened 2020-02-19 07:46 UTC by ZMZ91

Chimera is a software regular expression matching engine that is a hybrid of Hyperscan and PCRE. 
https://github.com/intel/hyperscan/tree/master/chimera

2020-02-19 07:46 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10132) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10132) before we can accept your contribution.<br/><br/>:x: ZMZ91 [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10132)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10132) it.</sub>

2020-02-20 10:04 UTC, ZMZ91 commented
hi there, one question that how to handle the conflicts if hyperscan installed as well?

2020-02-20 12:22 UTC, NancyLi1013 requested changes

2020-02-20 12:22 UTC, NancyLi1013 commented on ports/chimera/portfile.cmake
> +message(STATUS "Cmake install done.")
`message() `seems to be not needed  here.

2020-02-21 04:50 UTC, ZMZ91 commented on ports/chimera/portfile.cmake
> +
Thanks for your review. I see your point that pcre is supplied by vcpkg. But here for chimera it requires pcre's source code at the location during building. If I don't download and copy pcre-8.41 there, the building will fail.

2020-02-21 04:52 UTC, ZMZ91 commented on ports/chimera/portfile.cmake
> +message(STATUS "Cmake install done.")
Thank you. Just resolved it.

2020-02-21 05:24 UTC, NancyLi1013 commented on ports/chimera/portfile.cmake
> +
Thanks for your info.

2020-02-21 05:32 UTC, NancyLi1013 commented
I noticed it failed on Windows platform.
Could you please help confirm if it supports Windows?

If not, please add `vcpkg_fail_port_install(ON_TARGET "Windows")` and also update the related triplets to ci.baseline.txt.
If yes, please look into the regressions and try to fix them.

Thanks.

2020-02-22 12:43 UTC, ZMZ91 commented on ports/chimera/portfile.cmake
> +
But find_package() or find_library() won't download the pcre code there, right? It's required by chimera that pcre source code there during building and build pcre stuff into chimera lib. Please checkout chimera's cmake as below
```cmake
# first look in pcre-$version or pcre subdirs
if (PCRE_SOURCE)
    # either provided on cmdline or we've seen it already
    set (PCRE_BUILD_SOURCE TRUE)
elseif (EXISTS ${PROJECT_SOURCE_DIR}/pcre-${PCRE_REQUIRED_VERSION})
    set (PCRE_SOURCE ${PROJECT_SOURCE_DIR}/pcre-${PCRE_REQUIRED_VERSION})
    set (PCRE_BUILD_SOURCE TRUE)
elseif (EXISTS ${PROJECT_SOURCE_DIR}/pcre)
    set (PCRE_SOURCE ${PROJECT_SOURCE_DIR}/pcre)
    set (PCRE_BUILD_SOURCE TRUE)
endif()

if (PCRE_BUILD_SOURCE)
    message(STATUS "SHOULD build pcre with source")
    if (NOT IS_ABSOLUTE ${PCRE_SOURCE})
        set(PCRE_SOURCE "${CMAKE_BINARY_DIR}/${PCRE_SOURCE}")
    endif ()
    set (saved_INCLUDES "${CMAKE_REQUIRED_INCLUDES}")
    set (CMAKE_REQUIRED_INCLUDES "${CMAKE_REQUIRED_INCLUDES} ${PCRE_SOURCE}")

    if (PCRE_CHECKED)
        set(PCRE_INCLUDE_DIRS ${PCRE_SOURCE} ${PROJECT_BINARY_DIR}/pcre)
        set(PCRE_LDFLAGS -L"${LIBDIR}" -lpcre)

        # already processed this file and set up pcre building
        return()
    endif ()

    # first, check version number
    CHECK_C_SOURCE_COMPILES("#include <pcre.h.generic>
    #if PCRE_MAJOR != ${PCRE_REQUIRED_MAJOR_VERSION} || PCRE_MINOR < ${PCRE_REQUIRED_MINOR_VERSION}
    #error Incorrect pcre version
    #endif
    main() {}" CORRECT_PCRE_VERSION)
    set (CMAKE_REQUIRED_INCLUDES "${saved_INCLUDES}")

    if (NOT CORRECT_PCRE_VERSION)
        unset(CORRECT_PCRE_VERSION CACHE)
        message(STATUS "Incorrect version of pcre - version ${PCRE_REQUIRED_VERSION} or above is required")
        return ()
    else()
        message(STATUS "PCRE version ${PCRE_REQUIRED_VERSION} or above - building from source.")
    endif()

    # PCRE compile options
    option(PCRE_BUILD_PCRECPP OFF)
    option(PCRE_BUILD_PCREGREP OFF)
    option(PCRE_SHOW_REPORT OFF)
    set(PCRE_SUPPORT_UNICODE_PROPERTIES ON CACHE BOOL "Build pcre with unicode")
    message(STATUS "PCRE_SUPPORT_UNICODE_PROPERTIES : ${PCRE_SUPPORT_UNICODE_PROPERTIES}")
    add_subdirectory(${PCRE_SOURCE} ${PROJECT_BINARY_DIR}/pcre EXCLUDE_FROM_ALL)
    set(PCRE_INCLUDE_DIRS ${PCRE_SOURCE} ${PROJECT_BINARY_DIR}/pcre)
    set(PCRE_LDFLAGS -L"${LIBDIR}" -lpcre)
else ()
    # pkgconf should save us
    find_package(PkgConfig)
    pkg_check_modules(PCRE libpcre>=${PCRE_REQUIRED_VERSION})
    if (PCRE_FOUND)
        set(CORRECT_PCRE_VERSION TRUE)
        message(STATUS "PCRE version ${PCRE_REQUIRED_VERSION} or above")
    else ()
        message(STATUS "PCRE version ${PCRE_REQUIRED_VERSION} or above not found")
        return ()
    endif ()
endif (PCRE_BUILD_SOURCE)
```

2020-02-25 02:33 UTC, JackBoosY commented on ports/chimera/portfile.cmake
> +
1. set `PCRE_BUILD_SOURCE` to `false`.
2. modify `find_package(PkgConfig)` to `find_package(PCRE REQUIRED)`.
3. modify `pkg_check_modules(PCRE libpcre>=${PCRE_REQUIRED_VERSION})` to `link_libraries(${PCRE_LIBRARIES})`.
4. add [FindPCRE.cmake](https://github.com/LuaDist/pcre/blob/master/FindPCRE.cmake) to source.

2020-02-25 03:30 UTC, ZMZ91 commented on ports/chimera/portfile.cmake
> +
Thanks @JackBoosY. So you suggest modifying chimera's cmake file from its repo? I'm not sure whether that's a good practice.

2020-02-25 07:15 UTC, JackBoosY commented on ports/chimera/portfile.cmake
> +
That's reasonable,  I will give you suggestion.

2020-02-28 13:25 UTC, ZMZ91 commented on ports/chimera/portfile.cmake
> +
Thank you @JackBoosY . I've created a pr for hyperscan/chimera for supporting building chimera without pcre source code. Will update this pr later.

2020-03-03 11:56 UTC, NancyLi1013 requested changes

2020-03-03 11:56 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> +chimera:x86-windows=fail
I noticed that you have added `vcpkg_fail_port_install(ON_TARGET "Windows")`.
But you only updated the above triplets here.
```
chimera:arm64-windows=fail
chimera:x64-uwp=fail
chimera:arm-uwp=fail
```
These triplets are also needed to add.

2020-03-03 11:56 UTC, NancyLi1013 commented on ports/chimera/CONTROL
> +Build-Depends: boost-array, boost-chrono, boost-config, boost-core, boost-crc, boost-detail, boost-functional, boost-regex, boost-system, boost-thread, boost-type-traits, boost-unordered, boost-utili
Could you please add `Supports: linux|osx` here?

2020-03-03 13:17 UTC, ZMZ91 commented on scripts/ci.baseline.txt
> +chimera:x86-windows=fail
Thank you. Please check in the latest commit.

2020-03-04 02:24 UTC, NancyLi1013 approved these changes

2020-03-04 02:46 UTC, NancyLi1013 commented
Hi @ZMZ91 

Let's wait for the PR https://github.com/intel/hyperscan/pull/223 merged.
Note: If `chimera `requires `pcre `to build, please use `pcre `that vcpkg provided.

Thanks.

2020-04-16 12:13 UTC, ZMZ91 commented
Hi @NancyLi1013, 
Got echo from https://github.com/intel/hyperscan/pull/223 which said `Chimera needs to use an internal UTF8 function _pcre_valid_utf from PCRE, which requires PCRE source to been compiled with --enable-unicode-properties option, so PCRE source is required.`
Referring the reply above, I'm afraid we can't cut pcre source from the installation.

2020-04-17 07:31 UTC, NancyLi1013 commented
Hi @ZMZ91 
Thanks for your above info.
We will have a internal discussion about this case.

2020-05-11 07:54 UTC, NancyLi1013 commented
/azp run

2020-05-13 02:58 UTC, NancyLi1013 commented
@ZMZ91 
Sorry for the delay.

If we add `--enable-unicode-properties` option for `pcre `provided by vcpkg, can this port work?

2020-06-17 07:29 UTC, NancyLi1013 commented
@ZMZ91 
Is work still being done for this PR?

2020-06-22 03:00 UTC, ZMZ91 commented
Thanks @NancyLi1013 , sorry for delayed reply. But the option `--enable-unicode-properties` is not fixing it.

2020-06-22 03:18 UTC, JackBoosY commented
I will handle this issue later.

2020-06-22 05:18 UTC, JackBoosY commented
Do we need to add Hyperscan instead of chimera?

2020-06-22 05:34 UTC, JackBoosY commented on ports/chimera/CONTROL
> +Build-Depends: boost-array, boost-chrono, boost-config, boost-core, boost-crc, boost-detail, boost-functional, boost-regex, boost-system, boost-thread, boost-type-traits, boost-unordered, boost-utili
According to [boost.cmake](https://github.com/intel/hyperscan/blob/master/cmake/boost.cmake#L33), this port should only depends on `boost-graph` and `boost-concept-check`.

2020-07-03 00:43 UTC, ZMZ91 commented
Actually this package is a super set of `hyperscan` which's already in vcpkg. `chimera` requires `hyperscan` and `pcre`.

2020-07-09 06:07 UTC, JackBoosY commented
@ZMZ91 Can you resolve the file conflict first?

2020-07-10 02:41 UTC, JackBoosY requested changes

2020-07-10 02:41 UTC, JackBoosY commented on ports/chimera/portfile.cmake
> +    URLS "https://github.com/intel/hyperscan/archive/d79973efb1fcf5ed338122882c1f896829767fb6.zip"
Since this repo is in github, can you replace it with `vcpkg_from_github`?

2020-07-10 02:48 UTC, JackBoosY approved these changes

2020-07-10 05:38 UTC, JackBoosY commented
@ZMZ91 Since you already added `Supports` to _CONTROL_, we don't need to modify _ci.baseline.txt_.

2020-07-10 05:39 UTC, JackBoosY commented
```
-- Downloading https://github.com/intel/hyperscan/archive/d79973efb1fcf5ed338122882c1f896829767fb6.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):
  

  File does not have expected hash:

          File path: [ /Users/vagrant/Data/downloads/temp/intel-hyperscan-d79973efb1fcf5ed338122882c1f896829767fb6.tar.gz ]
      Expected hash: [ 8bf6e8c323ab3c4b3f26d871a9f89e666edba598925c99ad2f14b3e849792c51cb87bc30ad54008ec813603a9a7c94d689ad4344e1a45c10b2a891e434a678f3 ]
        Actual hash: [ 00fe31805efddf25daceaecb94de44dae7cda8e5fb9593bb69ce2d3e3675b5c820cc6bac8d75f88f4ffe7dc9f3c4603b75816479eb36dba5bfb272dc6998003a ]
```

2020-07-10 06:09 UTC, JackBoosY approved these changes

2020-07-16 04:37 UTC, ZMZ91 commented
Hi there, anything needed from me before merging?

2020-07-16 05:34 UTC, JackBoosY commented
Ping @ras0219 @ras0219-msft for merge this PR.

2020-07-16 05:46 UTC, NancyLi1013 commented
@ZMZ91 
We need to add `_pcre_valid_utf ` for `pcre `provided in vcpkg first in order to make it available in this PR.

2020-07-17 09:20 UTC, JackBoosY commented
@ZMZ91 
Here is my changes based on this PR:
[chimera.zip](https://github.com/microsoft/vcpkg/files/4936831/chimera.zip)

It can completely avoid building pcre and hyperscan, but due to the direct use of `CMakeLists.txt` in hyperscan, some macros may not be defined.

2020-07-18 07:54 UTC, ZMZ91 commented
@JackBoosY, just tried the package you uploaded and got following error during installation
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/4941306/install-x64-osx-dbg-out.log)

2020-07-20 02:18 UTC, JackBoosY commented
```
In file included from /usr/local/include/boost/smart_ptr/detail/local_sp_deleter.hpp:20:
/usr/local/include/boost/smart_ptr/detail/local_counted_base.hpp:30:28: error: 'local_counted_base' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Werror,-Wweak-vtables]
class BOOST_SYMBOL_VISIBLE local_counted_base
                           ^
/usr/local/include/boost/smart_ptr/detail/local_counted_base.hpp:92:28: error: 'local_counted_impl' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Werror,-Wweak-vtables]
class BOOST_SYMBOL_VISIBLE local_counted_impl: public local_counted_base
```
Seems doesn't link with boost libraries?

2020-07-20 05:43 UTC, JackBoosY commented
@ZMZ91 if you agree with my changes, please commit them to this PR and we can solve the failures.

2020-07-22 09:46 UTC, ZMZ91 commented
@JackBoosY, just checked in following your changes.

2020-07-23 06:41 UTC, JackBoosY commented
Missing `intrin.h`, does this port support unix?

2020-07-23 09:27 UTC, ZMZ91 commented
I haven't tried on unix. Unix is optional and linux and macos are the first priority.

2020-07-23 09:37 UTC, JackBoosY commented
@ZMZ91 Okay, let's support windows first.

2020-07-23 09:38 UTC, JackBoosY requested changes

2020-07-23 09:38 UTC, JackBoosY commented on ports/chimera/CONTROL
> +Build-Depends: boost-array, boost-chrono, boost-config, boost-core, boost-crc, boost-detail, boost-functional, boost-regex, boost-system, boost-thread, boost-type-traits, boost-unordered, boost-utili
```suggestion
Build-Depends: boost-array, boost-chrono, boost-config, boost-core, boost-crc, boost-detail, boost-functional, boost-regex, boost-system, boost-thread, boost-type-traits, boost-unordered, boost-utility, boost-dynamic-bitset, boost-random, boost-graph, boost-multi-array, boost-icl, boost-ptr-container, python3, ragel, hyperscan
Supports: windows
```

2020-07-28 05:06 UTC, JackBoosY approved these changes

2020-07-28 05:47 UTC, JackBoosY requested changes

2020-07-28 05:47 UTC, JackBoosY commented on ports/chimera/CONTROL
> +Build-Depends: boost-array, boost-chrono, boost-config, boost-core, boost-crc, boost-detail, boost-functional, boost-regex, boost-system, boost-thread, boost-type-traits, boost-unordered, boost-utili
```suggestion
Build-Depends: python3, ragel, hyperscan
```

2020-07-28 05:50 UTC, NancyLi1013 requested changes

2020-07-28 05:50 UTC, NancyLi1013 commented on ports/chimera/portfile.cmake
> +set(ENV{PATH} "$ENV{PATH};${PYTHON3_DIR}")
```suggestion
vcpkg_add_to_path(${PYTHON3_DIR})
```

2020-07-28 05:57 UTC, JackBoosY commented
@ZMZ91 It should be noted that `intrin.h` cannot be found in linux and osx, so these two triplets are not currently supported.

2020-07-29 01:59 UTC, NancyLi1013 commented
/azp run

2020-07-31 06:39 UTC, ZMZ91 commented
Hi, just tried on my mac, still got the error 
```
In file included from /usr/local/include/boost/smart_ptr/detail/local_sp_deleter.hpp:20:
/usr/local/include/boost/smart_ptr/detail/local_counted_base.hpp:30:28: error: 'local_counted_base' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Werror,-Wweak-vtables]
class BOOST_SYMBOL_VISIBLE local_counted_base
                           ^
/usr/local/include/boost/smart_ptr/detail/local_counted_base.hpp:92:28: error: 'local_counted_impl' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Werror,-Wweak-vtables]
class BOOST_SYMBOL_VISIBLE local_counted_impl: public local_counted_base
                           ^
In file included from /Users/zmz/github/vcpkg/buildtrees/hyperscan/src/v5.2.1-c4e657f760.clean/tools/hscollider/NfaGeneratedCorpora.cpp:40:
In file included from /Users/zmz/github/vcpkg/buildtrees/hyperscan/src/v5.2.1-c4e657f760.clean/src/nfagraph/ng.h:44:
In file included from /Users/zmz/github/vcpkg/buildtrees/hyperscan/src/v5.2.1-c4e657f760.clean/src/util/graph.h:42:
In file included from /usr/local/include/boost/graph/depth_first_search.hpp:25:
In file included from /usr/local/include/boost/optional.hpp:15:
In file included from /usr/local/include/boost/optional/optional.hpp:32:
/usr/local/include/boost/optional/bad_optional_access.hpp:22:7: error: 'bad_optional_access' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Werror,-Wweak-vtables]
class bad_optional_access : public std::logic_error
      ^
3 errors generated.
```

2020-07-31 06:42 UTC, JackBoosY commented
@ZMZ91 We can set it to support Windows first.

2020-07-31 06:44 UTC, ZMZ91 commented
> @ZMZ91 We can set it to support Windows first.

Sure, but I don't have a windows env but only macos.

2020-08-03 13:01 UTC, ZMZ91 commented
Thanks for your rapid response @JackBoosY. But I still got same errors using latest code.

2020-08-05 02:52 UTC, JackBoosY commented
Fixing x64-osx...

2020-08-05 05:12 UTC, JackBoosY commented
@ZMZ91 It seems that chimera is not compatible with macosx at all. I have encountered many syntaxes that clang does not support. So I am going to disable macosx build.

2020-08-05 05:13 UTC, JackBoosY requested changes

2020-08-05 05:13 UTC, JackBoosY commented on ports/chimera/CONTROL
> +Build-Depends: python3, ragel, hyperscan
```suggestion
Build-Depends: python3, ragel, hyperscan
Supports: !osx
```

2020-08-05 05:25 UTC, JackBoosY approved these changes

2020-08-06 02:20 UTC, ZMZ91 commented
> @ZMZ91 It seems that chimera is not compatible with macosx at all. I have encountered many syntaxes that clang does not support. So I am going to disable macosx build.

emmm, I don't know why, but my application runs well with chimera on my macbook.

2020-08-06 02:29 UTC, JackBoosY commented
For example:
```
/Users/vagrant/Data/buildtrees/chimera/src/b5c379159c-88a7a080a9.clean/chimera/../src/util/hash.h:60:12: error: 'auto' not allowed in function return type
    static auto has_begin_function(const C &obj) -> decltype(std::begin(obj)) {
           ^~~~
```

2020-08-06 04:54 UTC, ZMZ91 commented
> For example:
> 
> ```
> /Users/vagrant/Data/buildtrees/chimera/src/b5c379159c-88a7a080a9.clean/chimera/../src/util/hash.h:60:12: error: 'auto' not allowed in function return type
>     static auto has_begin_function(const C &obj) -> decltype(std::begin(obj)) {
>            ^~~~
> ```

Is that something about the compiler version? I never got such issue on my macbook. I'm using CMAKE_CXX_STANDARD 17.

2020-08-06 05:51 UTC, JackBoosY commented
@ZMZ91 Not working, see https://stackoverflow.com/questions/30665506/auto-not-allowed-in-function-prototype-with-clang

2020-08-06 07:22 UTC, ZMZ91 commented
> @ZMZ91 Not working, see https://stackoverflow.com/questions/30665506/auto-not-allowed-in-function-prototype-with-clang

Checked on my env, the clang version is
```
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Could you get such an env and try?

2020-08-06 07:38 UTC, JackBoosY commented
@ZMZ91 
```
vcpkg@vcpkg % clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
vcpkg@vcpkg %
```

2020-08-06 07:49 UTC, ZMZ91 commented
ha, that's weird. With my previous package, I can install chimera successfully on both mac and linux and my app runs without problem as well.

2020-08-06 07:58 UTC, JackBoosY commented
@ZMZ91 Therefore, I think this issue can be left to other contributors.

2020-08-10 21:37 UTC, strega-nil commented
I've fixed the problem, hopefully.

2020-08-13 21:18 UTC, strega-nil commented
Is there a reason that this isn't just a feature of hyperscan? @ZMZ91

2020-08-17 07:32 UTC, ZMZ91 commented
> Is there a reason that this isn't just a feature of hyperscan? @ZMZ91

Chimera is indeed a feature from hyperscan. But it requires pcre which makes it quite heavier. Ideally I think it could be built in hyperscan package and add a switch to control chimera feature on/off.

2020-08-17 15:38 UTC, strega-nil commented
@ZMZ91 yeah, that's possible; you'd have, in the hyperscan `CONTROL` file:

```
Feature: chimera
Description: Add the chimera regular expression engine
```

and then you can check for the feature in `hyperscan`'s `portfile.cmake` with `"chimera" IN_LIST FEATURES`.

2020-08-17 15:38 UTC, strega-nil requested changes
Please make this port a feature of the hyperscan port.

2020-08-31 07:39 UTC, NancyLi1013 commented
@ZMZ91 
Could you please add `chimera ` as a feature for `hyperscan`?

2020-10-29 09:16 UTC, NancyLi1013 commented
@ZMZ91 
Could you please handle the conflicts and address the review suggestions?

2020-11-13 07:28 UTC, NancyLi1013 commented
Pinging @ZMZ91 for response. Is work still being done for this PR?

2020-12-04 08:57 UTC, NancyLi1013 commented
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

2020-12-04 08:57 UTC, closed without merging