[libgit2] Update to 0.99.0
microsoft/vcpkg pull request #10140
Opened 2020-02-19 18:16 UTC by kevinlul

**Describe the pull request**

- What does your PR fix? https://github.com/libgit2/libgit2/releases/tag/v0.99.0

- Which triplets are supported/not supported? Have you updated the CI baseline? N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

Changes might be breaking but maintainers say it is expected to be API-compatible with the previous version.

2020-02-20 06:10 UTC, LilyWangL commented
/azp run

2020-02-21 01:53 UTC, LilyWangL requested changes

2020-02-21 01:53 UTC, LilyWangL commented on ports/libgit2/portfile.cmake
>  vcpkg_from_github(
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-02-21 01:53 UTC, LilyWangL commented on ports/libgit2/portfile.cmake
Can you please use command `file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-02-24 03:02 UTC, LilyWangL requested changes

2020-02-24 03:02 UTC, LilyWangL commented on ports/libgit2/portfile.cmake
>      message(FATAL_ERROR "Error: UWP builds are not supported.")
Could you please use command `vcpkg_fail_port_install(ON_TARGET "uwp")` to handle `UWP builds are not supported`?

2020-02-29 06:25 UTC, strega-nil commented
Thanks @kevinlul :)

2020-02-29 06:25 UTC, merged