[magnum/magnum-plugins] Fix patches for --head builds
microsoft/vcpkg pull request #10158
Opened 2020-02-21 13:07 UTC by Squareys

Hi all!

I updated the magnum and magnum-plugins portfiles to work with current HEAD.
As per usual the maintainer of Magnum, @mosra, will quickly review and approve the PR.

Best,
Jonathan

2020-02-21 19:04 UTC, mosra approved these changes

2020-02-24 02:48 UTC, JackBoosY requested changes
Please update version info of these ports, see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-02-24 02:48 UTC, JackBoosY commented on ports/magnum/portfile.cmake
>  include(vcpkg_common_functions)
Can you remove this line? We don't need to include this now.

2020-02-24 02:48 UTC, JackBoosY commented on ports/magnum/portfile.cmake
> +set(_PATCHES 002-tools-path.patch)
Shouldn't this patch be after 001?

2020-02-24 07:28 UTC, Squareys commented on ports/magnum/portfile.cmake
> +set(_PATCHES 002-tools-path.patch)
In this particular case the order doesn't matter, but I'll rename the files to have them reflect the current order

2020-02-24 07:31 UTC, Squareys commented
@JackBoosY Thank you for the review!

I made changes accordingly. Please have another look.

2020-02-24 07:42 UTC, JackBoosY commented
@Squareys Don't forget to update version info : )
[Documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-02-24 08:03 UTC, Squareys commented
@JackBoosY Ah, right, thanks! 🙏 

Done with latest commit.

2020-02-24 09:25 UTC, JackBoosY commented
And `magnum-plugins` version update?

2020-02-24 09:33 UTC, Squareys commented
Yes, sorry, @mosra just pinged me on that, too. Totally forgot I had changed that aswell 🙄

2020-02-25 01:51 UTC, JackBoosY approved these changes

2020-02-25 01:51 UTC, JackBoosY commented
LGTM, we need to test all features.

2020-02-25 13:31 UTC, JackBoosY commented
Build failure with `magnum[al-info,anyimageimporter,anyaudioimporter,anyimageconverter,anysceneimporter,audio,debugtools,distancefieldconverter,fontconverter,gl,gl-info,glfwapplication,imageconverter,magnumfont,magnumfontconverter,meshtools,objimporter,tgaimageconverter,opengltester,primitives,sdl2application,scenegraph,shaders,text,texturetools,tgaimporter,trade,wavaudioimporter,windowlesswglapplication,eglcontext,cglcontext,glxcontext,wglcontext,windowlesseglapplication,eglcontext,windowlessglxapplication]:x86-windows`:

```
CMake Error at src/Magnum/Platform/CMakeLists.txt:515 (message):
  X11 library, required by some applications, was not found.  Set
  WITH_*X*APPLICATION to OFF to skip building them.
```

Looks like you forgot to pass in the following parameters:
```
CORRADE_TARGET_UNIX          - Defined if compiled for some Unix flavor
CORRADE_TARGET_APPLE         - Defined if compiled for Apple platforms
CORRADE_TARGET_IOS           - Defined if compiled for iOS (device or
CORRADE_TARGET_IOS_SIMULATOR - Defined if compiled for iOS Simulator
CORRADE_TARGET_WINDOWS       - Defined if compiled for Windows
CORRADE_TARGET_WINDOWS_RT    - Defined if compiled for Windows RT
CORRADE_TARGET_EMSCRIPTEN    - Defined if compiled for Emscripten
CORRADE_TARGET_ANDROID       - Defined if compiled for Android
```

2020-02-25 13:50 UTC, Squareys commented
@JackBoosY The magnum port has platform dependent features, e.g. `windowlessglxapplication`. If you build `[*]`, then all are included. We have an open PR on that https://github.com/mosra/magnum/pull/368, but didn't come to a consensus on how this should behave.

Do you have a suggestion?

CC @mosra

2020-02-25 15:15 UTC, mosra commented
The inability to use `[*]` is a separate problem that needs a dedicated solution from our side and due to time constraints we weren't able to resolve that yet. @JackBoosY Would it be possible to merge this as-is? 

The build should work on Windows if you install `magnum[al-info,anyimageimporter,anyaudioimporter,anyimageconverter,anysceneimporter,audio,debugtools,distancefieldconverter,fontconverter,gl,gl-info,glfwapplication,imageconverter,magnumfont,magnumfontconverter,meshtools,objimporter,tgaimageconverter,opengltester,primitives,sdl2application,scenegraph,shaders,text,texturetools,tgaimporter,trade,wavaudioimporter,windowlesswglapplication,wglcontext]` (i.e., with `eglcontext`, `cglcontext`, `glxcontext`, `windowlesscglapplication`, `windowlesseglapplication`, `windowlessglxapplication`, which are Linux- and macOS-specific, omitted).

2020-02-26 02:38 UTC, JackBoosY commented
@Squareys If some features are not supported by some triplets, you should add error message in _portfile.cmake_ before `vcpkg_configure_cmake`.
Such as:
```
if ("eglcontext" IN_LIST FEATURES AND NOT VCPKG_TARGET_IS_WINDOWS)
    message(FATAL_ERROR "Feature eglcontext only support windows")
endif()
```

2020-02-26 10:42 UTC, mosra commented
Okay, we'll need to roll out our own `FindOpenAL` that correctly links to `winmm` on Windows (or uses the exported OpenAL Soft CMake config), the builtin CMake module doesn't. Is that a blocker for this PR? This issue was there probably since ever.

Good idea with the `FATAL_ERROR`.

2020-02-27 02:39 UTC, JackBoosY commented
@mosra Yes, we need all features to be successfully tested.

2020-03-20 09:34 UTC, dan-shaw commented
@mosra @Squareys @JackBoosY It is okay if not all features are passing. We just don't want to introduce any additional failures (which is why we test all the features). Since this feature combination seems to have been failing since the beginning, I would be OK with merging this PR.

2020-03-20 09:34 UTC, dan-shaw approved these changes

2020-03-22 07:48 UTC, JackBoosY commented
@dan-shaw Okay.

2020-03-28 03:37 UTC, merged