[libmysql] Fix for missing "ADD_COMPILE_FLAGS" command
microsoft/vcpkg pull request #10162
Opened 2020-02-21 15:00 UTC by Toxe

**Describe the pull request**

- What does your PR fix? Fixes issue #5204

- Which triplets are supported/not supported? Have you updated the CI baseline? Tested `x64-osx` and `x64-windows`.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

When installing `libmysql` on Mac + Clang, CMake will generate a configuration error because a necessary file (`cmake/compile_flags.cmake` from the `libmysql` sources) did not get included:

```
CMake Error at extra/re2/CMakeLists.txt:74 (ADD_COMPILE_FLAGS):
  Unknown CMake command "ADD_COMPILE_FLAGS".
```

This PR...

- Adds a patch for `extra/re2/CMakeLists.txt` that fixes the "unknown command ADD_COMPILE_FLAGS" error.
- Removes an empty directory after the installation of `libmysql` that the post-installation checks would complain about.

2020-02-21 15:00 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10162) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10162) before we can accept your contribution.<br/><br/>:x: Toxe [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10162)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10162) it.</sub>

2020-02-22 16:13 UTC, Toxe commented
Is there a way to restart `vcpkg-osx-PR-test`? It seems to hang and there should not be any problems.

2020-02-25 06:53 UTC, LilyWangL requested changes

2020-02-25 06:53 UTC, LilyWangL commented on ports/libmysql/portfile.cmake
>          ignore-boost-version.patch
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-02-25 07:05 UTC, LilyWangL commented
Thanks for your PR. Please fix these changes as below:

1. Could you please use command [vcpkg_fail_port_install](https://github.com/microsoft/vcpkg/blob/5deea3b975fe62990973d73a102de818d83ba20c/docs/maintainers/vcpkg_fail_port_install.md) to handle `Some triplets builds are not supported` in **portfile.cmake**?

2. Could you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright in **portfile.cmake**? 

3. Please remove `libmysql:x64-osx=fail` in **scripts/ci.baseline.txt**, it makes osx build failed.

2020-02-26 20:34 UTC, Toxe commented on ports/libmysql/portfile.cmake
>          ignore-boost-version.patch
Done. I have removed it.

2020-02-26 20:35 UTC, Toxe commented
I have added 4 more commits that should fix all the issues.

2020-02-27 03:51 UTC, LilyWangL approved these changes

2020-02-29 05:56 UTC, strega-nil commented
Thank you so much for this @Toxe :)

2020-02-29 05:56 UTC, merged