[restinio] update to v.0.6.5
microsoft/vcpkg pull request #10208
Opened 2020-02-25 10:00 UTC by eao197

RESTinio updated to the latest version.

2020-02-26 02:08 UTC, JackBoosY approved these changes

2020-02-26 02:09 UTC, JackBoosY commented
LGTM, thanks for this PR!

2020-02-26 22:09 UTC, strega-nil requested changes
Thanks so much @eao197! This is really great, just needs some minor changes :)

2020-02-26 22:09 UTC, strega-nil commented on ports/restinio/portfile.cmake
> +    REF 6934bd5a8ad707eb6a04894ec3bb198a39f447d9 # v.0.6.5
Could you use the `v.0.6.5` ref instead of the actual git commit?

2020-02-26 22:09 UTC, strega-nil commented on ports/restinio/portfile.cmake
> +    SHA512 5a0228a7a0940f38429cd63368ee3dee72ff2bc9a019bb7b3c9e59314a8fd7afee555f10f9ec375dc7dda412bc6922f7f561fc54b6cf2b783b7db3dda0c2ae6b
(You'll also need to modify the sha here)

2020-02-27 02:53 UTC, JackBoosY commented on ports/restinio/portfile.cmake
> +    REF 6934bd5a8ad707eb6a04894ec3bb198a39f447d9 # v.0.6.5
@strega-nil I prefer to use the commit ID, because the commit ID always corresponds to a constant version, and the version using the tag may change.
Please ask @ras0219-msft.

2020-02-27 08:00 UTC, eao197 commented on ports/restinio/portfile.cmake
> +    REF 6934bd5a8ad707eb6a04894ec3bb198a39f447d9 # v.0.6.5
I think that @JackBoosY 's argument has more sense: commit ID is more stable than the version tag.

2020-02-29 05:09 UTC, strega-nil commented on ports/restinio/portfile.cmake
> +    REF 6934bd5a8ad707eb6a04894ec3bb198a39f447d9 # v.0.6.5
hm, fair enough. I asked robert and he said that you're correct; thanks for informing me!

2020-02-29 05:10 UTC, strega-nil approved these changes

2020-02-29 05:10 UTC, merged