Updating for HPX V1.4.1
microsoft/vcpkg pull request #10214
Opened 2020-02-25 17:33 UTC by hkaiser

2020-02-26 02:07 UTC, NancyLi1013 requested changes

2020-02-26 02:07 UTC, NancyLi1013 commented on ports/hpx/portfile.cmake
Could you please use `vcpkg_replace_string() `to replace a string in a file?

2020-02-26 02:07 UTC, NancyLi1013 commented on ports/hpx/portfile.cmake
Could you please update
```
file(INSTALL
    ${SOURCE_PATH}/LICENSE_1_0.txt
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/hpx RENAME copyright)
```
as
```
file(INSTALL
    ${SOURCE_PATH}/LICENSE_1_0.txt
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```
?

2020-02-26 02:07 UTC, NancyLi1013 commented on ports/hpx/CONTROL
> +Version: 1.4.1-1
The `Version `should be `1.4.1` here.

2020-02-27 02:12 UTC, NancyLi1013 approved these changes

2020-02-29 05:37 UTC, strega-nil commented
Thanks @hkaiser !

2020-02-29 05:38 UTC, merged