[openmvs] use project install folder (#10265)
microsoft/vcpkg pull request #10291
Opened 2020-03-03 10:59 UTC by cdcseacave

**Describe the pull request**

- What does your PR fix? Fixes issue #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-03-03 11:24 UTC, NancyLi1013 requested changes

2020-03-03 11:24 UTC, NancyLi1013 commented on ports/openmvs/CONTROL
>  Description: OpenMVS: open Multi-View Stereo reconstruction library
Could you please add `homepage `here?
`Homepage: https://github.com/cdcseacave/openMVS`

2020-03-03 11:24 UTC, NancyLi1013 commented on ports/openmvs/portfile.cmake
> -        -DINSTALL_INCLUDE_DIR:STRING=include
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

2020-03-03 11:24 UTC, NancyLi1013 commented on ports/openmvs/portfile.cmake
> -        -DINSTALL_INCLUDE_DIR:STRING=include
Could you please update
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/openmvs RENAME copyright)`
as
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-03-03 12:08 UTC, cdcseacave commented
@NancyLi1013 done, thank you

2020-03-04 01:52 UTC, JackBoosY approved these changes

2020-03-04 01:52 UTC, NancyLi1013 approved these changes

2020-03-04 02:08 UTC, NancyLi1013 commented
Hi @cdcseacave 
Thanks for this PR.
LGTM now.

@strega-nil 
Could you please help priority to review and merge this PR?

Thanks.

2020-03-04 18:15 UTC, strega-nil commented
Thanks so much @cdcseacave :D

2020-03-04 18:15 UTC, merged