[geos] Upgrade to GEOS 3.6.4
microsoft/vcpkg pull request #10377
Opened 2020-03-11 04:42 UTC by mwtoews

Update port/geos to version 3.6.4, released 2019-10-04

See details [in this release announcement](http://osgeo-org.1560.x6.nabble.com/GEOS-3-7-3-3-6-4-3-5-2-Released-tt5418254.html)

Note that this is not the current version, as I'd like to re-create each major version, so you can expect me to also create pull requests for GEOS versions 3.7.3 and 3.8.1 (current).

---

- What does your PR fix? None.
- Which triplets are supported/not supported? Have you updated the CI baseline? Not sure, and nope.
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

2020-03-11 04:42 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10377) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10377) before we can accept your contribution.<br/><br/>:x: mwtoews [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10377)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10377) it.</sub>

2020-03-11 10:41 UTC, LilyWangL requested changes

2020-03-11 10:41 UTC, LilyWangL commented on ports/geos/portfile.cmake
>  include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-03-11 11:37 UTC, mwtoews commented on ports/geos/portfile.cmake
>  include(vcpkg_common_functions)
done

2020-03-12 21:32 UTC, strega-nil requested changes
This looks great! Just needs a slight change. Thanks so much :)

2020-03-12 21:32 UTC, strega-nil commented on ports/geos/CONTROL
> +Version: 3.6.4-1
This should just be `Version: 3.6.4` :)

2020-03-12 22:16 UTC, mwtoews commented on ports/geos/CONTROL
> +Version: 3.6.4-1
Ah, I see the `-N` gets appended if there are further patches that get applied to this version. This patch version has been removed for this PR.

2020-03-12 22:26 UTC, strega-nil commented on ports/geos/CONTROL
> +Version: 3.6.4-1
Awesome :)

2020-03-12 22:26 UTC, strega-nil approved these changes

2020-03-13 06:53 UTC, LilyWangL approved these changes

2020-03-19 06:15 UTC, dan-shaw commented
/azp run

2020-03-19 21:42 UTC, dan-shaw commented
/azp run

2020-03-20 05:38 UTC, dan-shaw commented
@mwtoews @LilyWangL This is failing the CI for osg-qt. Do you know if this is a related error or an error with our CI?

2020-03-20 08:08 UTC, LilyWangL commented
> @mwtoews @LilyWangL This is failing the CI for osg-qt. Do you know if this is a related error or an error with our CI?

Port osg-qt build failed is not a related error with this PR.

2020-03-27 03:07 UTC, LilyWangL commented
/azp run

2020-04-22 00:33 UTC, mwtoews commented
is this ready to merge yet?

2020-04-22 02:18 UTC, LilyWangL commented
@ras0219-msft This PR is ready to merge.

2020-04-27 14:47 UTC, merged

2020-04-27 14:47 UTC, ras0219-msft commented
LGTM, thanks for this PR!

2020-05-20 11:15 UTC, jjpepper commented
Is GOES meant to be working?  How is it meant to be used from CMake?