[libffi] Check return value of execute_process()
microsoft/vcpkg pull request #10469
Opened 2020-03-19 14:06 UTC by derselbst

I'm currently unable to cross-compile libffi for arm64. The "compile assembly" `execute_process()` step silently fails and CMake later complains that the .obj file is not available. To avoid hiding errors, the return values of the `execute_process()` commands should be checked and a fatal error should be issued.

(Here's the build log, in case smb. is interested: https://ci.appveyor.com/project/derselbst/fluidsynth-g2ouw/builds/31479626/job/hm9u92nejl7083dx#L596)

2020-03-20 07:44 UTC, PhoebeHui commented
@derselbst, thanks for bringing this up!

We considered a fix for libffi:arm64-wiindows port or upstream needed instead.

2020-04-07 03:09 UTC, JackBoosY commented
Hi @derselbst, I've fixed this issue in #10485, please update vcpkg and rebuild libffi.

Thanks.

2020-04-07 07:19 UTC, derselbst commented
It works now, thanks.

But why closing this? This PR only adds additional error checking and should still be merged. Calling `execute_process()` and blindly hoping that it succeeds is really bad practice.

2020-04-08 06:05 UTC, JackBoosY commented
/azp run

2020-04-08 06:06 UTC, JackBoosY commented
@derselbst Sorry, I closed this PR by mistake.

2020-04-08 06:07 UTC, JackBoosY requested changes
Please update libffi version info in _VCPKG_PATH/ports/libffi/CONTROL_.
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-04-08 06:12 UTC, JackBoosY commented
/azp run

2020-04-08 08:21 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10469) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10469) before we can accept your contribution.<br/><br/>:x: derselbst [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10469)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10469) it.</sub>

2020-04-09 02:26 UTC, JackBoosY approved these changes

2020-04-09 02:26 UTC, JackBoosY commented
LGTM, thanks for this PR!

2020-04-16 20:43 UTC, merged