[qscintilla] Update to 2.11.4
microsoft/vcpkg pull request #10511
Opened 2020-03-23 09:32 UTC by longhuan2018

update qscintilla version from 2.10 to 2.11.4
change Homepage from "https://sourceforge.net/projects/pyqt" to "https://www.riverbankcomputing.com/software/qscintilla"

2020-03-23 10:34 UTC, longhuan2018 commented
I don't know why it went wrong, I checked the log of CL and found that compiling qscintilla was successful

2020-03-23 10:54 UTC, NancyLi1013 requested changes

2020-03-23 10:54 UTC, NancyLi1013 commented on ports/qscintilla/CONTROL
>  Build-Depends: qt5-base, qt5-macextras (osx), qt5-winextras (windows)
It seems that this port currently doesn't support `linux` and `osx`.
Could you please add `Supports `filed here?
`Supports: windows`

2020-03-23 10:54 UTC, NancyLi1013 commented on ports/qscintilla/portfile.cmake
> -include(vcpkg_common_functions)
Could you please also add` vcpkg_fail_port_install(ON_TARGET "linux" "osx")` here?

2020-03-23 10:54 UTC, NancyLi1013 commented
Hi @longhuan2018 
Thanks for this PR.
There is something wrong with CI test and we have been trying to fix the regressions in this PR #10508.
Once fixed, we will re run this PR.

2020-03-23 10:59 UTC, longhuan2018 commented on ports/qscintilla/portfile.cmake
> -include(vcpkg_common_functions)
Ok,  i will try.

2020-03-23 10:59 UTC, longhuan2018 commented on ports/qscintilla/CONTROL
>  Build-Depends: qt5-base, qt5-macextras (osx), qt5-winextras (windows)
Ok,  i will try.

2020-03-23 11:06 UTC, longhuan2018 commented
> Hi @longhuan2018
> Thanks for this PR.
> There is something wrong with CI test and we have been trying to fix the regressions in this PR #10508.
> Once fixed, we will re run this PR.

OK, I just modified it according to your prompt, but CI still fails. I'm sure QScintilla supports linux and osx, so I will revert these changes and wait for the CI problem to be solved.

2020-03-24 00:40 UTC, NancyLi1013 commented
Thanks for your update.

I noticed it was set as fail on linux and osx in ci.baseline.txt.
If you can confirm this port supports linux and osx, there is no need to add the prompt I suggested.
And we should remove the following codes from c.baseline.txt.
```
qscintilla:x64-linux=fail
qscintilla:x64-osx=fail
```
But I saw the CI test results, only linux is passing. So please help confirm if it supports on osx.
Of course,you don't need to update this now until the CI problem is fixed.

2020-03-24 05:21 UTC, NancyLi1013 commented
You don't need to care about other regressions that are not related with this PR.
Let's just wait for the CI problem is fixed.
Once fixed, I will re run this PR.

2020-03-26 04:04 UTC, NancyLi1013 commented
/azp run

2020-03-26 06:31 UTC, NancyLi1013 commented
It seems that it has passed on Linux platform.
`##[error] PASSING, REMOVE FROM FAIL LIST: qscintilla:x64-linux (/ci/myagent/_work/3/s/scripts/ci.baseline.txt)`
Please update ci.baseline.txt.

Also, please add `vcpkg_fail_port_install(ON_TARGET "osx")` to top of `portfile.cmake`
add `Supports: !osx` to `CONTROL `file.

2020-03-26 09:46 UTC, longhuan2018 commented
> It seems that it has passed on Linux platform.
> `##[error] PASSING, REMOVE FROM FAIL LIST: qscintilla:x64-linux (/ci/myagent/_work/3/s/scripts/ci.baseline.txt)`
> Please update ci.baseline.txt.
> 
> Also, please add `vcpkg_fail_port_install(ON_TARGET "osx")` to top of `portfile.cmake`
> add `Supports: !osx` to `CONTROL `file.

OK, I will modify it according to your opinion. In addition, I think qscintilla supports osx. How can I make CI compile it?

2020-03-26 11:08 UTC, NancyLi1013 commented
If it supports osx, you can remove `qscintilla:x64-osx` from ci.baseline.txt.
Then try to fix the regressions.
It might be better to make sure that this port can work well on you local Mac machine first.

2020-04-01 04:37 UTC, longhuan2018 commented
> If it supports osx, you can remove `qscintilla:x64-osx` from ci.baseline.txt.
> Then try to fix the regressions.
> It might be better to make sure that this port can work well on you local Mac machine first.

I compiled qscintilla under osx successfully. But CI failed to compile under osx, but I found that it has not been compiled to qscintilla port. The failure was caused by the glib port. Is there a problem with CI's osx environment?

2020-04-16 03:26 UTC, NancyLi1013 commented
Hi @longhuan2018 
Could you please resolve the conflicts first?

2020-04-16 05:59 UTC, longhuan2018 commented
> Hi @longhuan2018
> Could you please resolve the conflicts first?

I have resolved the conflict, and now it can be compiled under osx and linux.

2020-04-16 07:28 UTC, NancyLi1013 commented
LGTM. Thanks for your update.

2020-04-16 07:28 UTC, NancyLi1013 approved these changes

2020-04-17 22:11 UTC, merged

2020-04-17 22:11 UTC, ras0219-msft commented
Thanks for the PR!