opus: Make AVX an optional feature
microsoft/vcpkg pull request #10634
Opened 2020-03-31 22:31 UTC by Ghabry

This makes AVX for opus an optional feature as in some other ports (fftw3)

Emtting AVX by default is still problematic, see: https://github.com/EasyRPG/Player/issues/2059

The CPU mentioned in that issue is from 2013. Unfortunately, Intel disabled AVX on there cheaper CPUs :(
I even found a Pentium CPU from 2017 without AVX support: https://ark.intel.com/content/www/de/de/ark/products/97453/intel-pentium-processor-g4600-3m-cache-3-60-ghz.html

(but my workstation with an i5 from 2012 supports it...)

For opus[core]
```
objdump -d installed/x86-windows-static/lib/opus.lib | grep "vpxor" | wc -l
0
```

For opus[avx]
```
objdump -d installed/x86-windows-static/lib/opus.lib | grep "vpxor" | wc -l
41
```

2020-04-02 02:48 UTC, LilyWangL requested changes

2020-04-02 02:48 UTC, LilyWangL commented on ports/opus/portfile.cmake
> +if ("avx" IN_LIST FEATURES)
Could you please use [vcpkg_check_features()](https://github.com/microsoft/vcpkg/blob/a3a6530631df905eb5c0e26d0b20d7d548e0c465/docs/maintainers/vcpkg_check_features.md) to handle this feature?

2020-04-02 02:48 UTC, LilyWangL commented on ports/opus/portfile.cmake
>    HEAD_REF
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-04-02 02:49 UTC, LilyWangL commented
> The linux build failed in an unrelated package?

The error on Linux is not related with this PR.

2020-04-02 12:50 UTC, Ghabry commented
Thanks for the quick feedback, didn't knew about the new feature check func :). 
Addressed your coments.

2020-04-03 01:45 UTC, LilyWangL approved these changes

2020-04-03 17:17 UTC, merged

2020-04-03 17:17 UTC, dan-shaw commented
Thanks for the PR!