[coroutine] update to 1.5.0
microsoft/vcpkg pull request #10692
Opened 2020-04-04 12:12 UTC by luncliff

### Changes

New release which allows x86 with better documentation

### Related Issues

* #9624 (`ms-gsl` related work)
* #6245 (Previous release)

2020-04-04 12:12 UTC, luncliff commented
Triplet `WindowsStore` build will be updated within this weekend

2020-04-07 03:07 UTC, NancyLi1013 requested changes

2020-04-07 03:07 UTC, NancyLi1013 commented on ports/coroutine/portfile.cmake
>  include(vcpkg_common_functions)
This line is no longer needed.
Could you please remove it?

2020-04-07 03:07 UTC, NancyLi1013 commented on ports/coroutine/portfile.cmake
> +    message(WARNING "This library may not work correctly in x86 arch. Please consider using x64 instead")
Could you please help confirm if this version has supported x86 arch?

2020-04-07 03:08 UTC, NancyLi1013 commented
/azp run

2020-04-07 03:11 UTC, NancyLi1013 commented
Hi @luncliff 
Thanks for this PR.
It seems that `coroutine` currently doesn't support uwp and linux.
If so, could you please add `Supports: !(uwp|linux)` to CONTROL file and add `vcpkg_fail_port_install(ON_TARGET "uwp" "linux")` to portfile.cmake?

2020-04-07 14:10 UTC, luncliff commented on ports/coroutine/portfile.cmake
> +    message(WARNING "This library may not work correctly in x86 arch. Please consider using x64 instead")
The warning is because of code generation with older VS2017 x86/Release build. I will remove that :)

2020-04-07 14:11 UTC, luncliff commented
> Hi @luncliff
> Thanks for this PR.
> It seems that coroutine currently doesn't support uwp and linux.
> If so, could you please add Supports: !(uwp|linux) to CONTROL file and add vcpkg_fail_port_install(ON_TARGET "uwp" "linux") to portfile.cmake?

UWP install was fine with my laptop, but seems like I missed something. 
I will take a look at it.

2020-04-08 02:54 UTC, NancyLi1013 commented
Ok. Thanks for your update.

2020-04-16 03:24 UTC, NancyLi1013 commented
/azp run

2020-04-16 05:39 UTC, NancyLi1013 commented
Could you please also try to fix the regressions on Windows and OSX?

2020-04-16 05:52 UTC, luncliff commented
> Could you please also try to fix the regressions on Windows and OSX?

Sorry @NancyLi1013 . I was quite busy. Will update ASAP.

2020-04-16 05:57 UTC, NancyLi1013 commented
Okay, thanks for your update.

2020-04-17 02:32 UTC, NancyLi1013 commented
I noticed that it has passed on x86-windows.
Could you please remove `coroutine:x86-windows=fail` from baseline?

2020-04-17 03:15 UTC, luncliff commented
@NancyLi1013 Sure. I will update the part after Linux/OSX build reports their ends.

2020-04-22 07:47 UTC, NancyLi1013 approved these changes

2020-04-24 10:18 UTC, ras0219-msft commented
Thanks for making a neat library and submitting this update PR!

I relaxed some of the restrictions around Linux; here's a brief idea of how they should be used:
- The `Supports:` field should be optimistic -- if there is a way to use it on Linux (via clang, libc++, etc), it shouldn't be listed as unsupported
- `vcpkg_fail_port_install()` should similarly be optimistic
- `scripts/ci.baseline.txt` must exactly match our specific CI setup; if we aren't using the right GCC version in CI, then it gets marked as failing here

This ensures that users who opt in to jumping through the appropriate hoops (having GCC 10, etc) can access those niche scenarios with vcpkg.

2020-04-24 21:02 UTC, merged

2020-04-25 02:46 UTC, luncliff reviewed
learned a lot from this. Thanks :D

2020-04-26 02:02 UTC, NancyLi1013 commented
@luncliff 
Thanks for your kindly reminder.
I closed it just now.