[libmupdf] fix (draft)
microsoft/vcpkg pull request #10708
Opened 2020-04-05 21:04 UTC by simon987

Related to #10556. These changes makes `libmupdf` compile on linux

To do:

- [ ] Execute `generate.bat` or `make generate` depending on the platform 
- [ ] Don't add the `-DHAVE_PTHREAD` parameter on Windows
- [ ] This is not as important and might introduce a breaking change trying to fix, but currently the library is built as `liblibmupdf.a` instead of `libmupdf.a`

2020-04-07 05:46 UTC, PhoebeHui commented
@simon987, could you also update the Version to 1.16.1-1 in CONTROL file?

2020-04-07 12:40 UTC, simon987 commented
Sorry @PhoebeHui I'm really not that experienced with how the different vcpkg files work, as I said in the related issue I need some help to complete the rest of the work

2020-04-08 03:15 UTC, PhoebeHui commented
@simon987, I didn't noticed that, thanks for summiting this PR, we're happy to provide any help if you need, asigined to Nancy help follow up.

2020-04-08 09:20 UTC, NancyLi1013 requested changes

2020-04-08 09:20 UTC, NancyLi1013 commented on ports/libmupdf/CMakeLists.txt
> +find_package(OpenJPEG REQUIRED)
This might be `find_package(OpenJPEG CONFIG REQUIRED)`.

2020-04-08 09:20 UTC, NancyLi1013 commented on ports/libmupdf/CMakeLists.txt
> +target_compile_definitions(libmupdf PRIVATE -DSHARE_JPEG -DFZ_ENABLE_JS=0 -DFZ_ENABLE_ICC=0 -DHAVE_PTHREAD=1)
If `-DHAVE_PTHREAD=1` is only required on Unix platform, we might need to add `if(unix) `to judge this.

2020-04-08 09:20 UTC, NancyLi1013 commented on ports/libmupdf/CMakeLists.txt
> +list(FILTER SOURCES EXCLUDE REGEX "source/tests/.*.c$")
Could you please help clarify why we need to add this?

2020-04-08 09:37 UTC, NancyLi1013 commented
@simon987 
Sorry for the late reply.
For the first item you listed above, since I'm not familiar with this. I might not give you any good suggestions about this.
For the third and forth items, please update as @PhoebeHui commented above.
For the library name, it doesn't matter whether it is `libmupdf.a` or `liblibmupdf.a`.

BTW, could you please also remove `include(vcpkg_common_functions)` from portfile.cmake?

Since this port currently doesn't support osx, please add `Supports: !osx` to CONTROL file and add `vcpkg_fail_port_intall(ON_ATRGET "osx")` to portfile.cmake.

2020-04-09 01:48 UTC, NancyLi1013 commented
/azp run

2020-04-14 08:27 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10708) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10708) before we can accept your contribution.<br/><br/>:x: simon987 [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10708)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10708) it.</sub>

2020-04-14 08:53 UTC, NancyLi1013 commented
@simon987 
Could you please sign [CLA ](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10708)first? 
I submitted the commit to update the review suggestions just now.
Please let me know if you have anything else needs us to do.

2020-04-14 11:32 UTC, simon987 commented
@NancyLi1013 Hi, sorry I've been unavailable for the last few days.

I'm worried that the `cmd.exe generate.bat` command is not executed on Windows. The library would compile fine without it, but some objects would be missing from the binary.

2020-04-15 06:01 UTC, NancyLi1013 commented
@simon987 
Thanks for your update.
It seems to be good now. 
Could you please help confirm if this PR is ready to be merged?

2020-04-17 09:48 UTC, NancyLi1013 approved these changes

2020-04-20 02:35 UTC, JackBoosY requested changes

2020-04-20 02:35 UTC, JackBoosY commented on ports/libmupdf/CMakeLists.txt
> +  find_program(MAKE_EXE NAMES gmake nmake make)
We should put this to line 14 and add keyword `REQUIRED` here.

2020-04-21 02:26 UTC, NancyLi1013 commented
/azp run

2020-04-21 22:13 UTC, simon987 commented
Regarding c04f39b: The `make generate` command wasn't executed

2020-04-22 02:39 UTC, JackBoosY requested changes

2020-04-22 02:39 UTC, JackBoosY commented on ports/libmupdf/CMakeLists.txt
> +    COMMAND ${MAKE_EXE} "generate"
I don’t know what you want to do here. I can't find any generate file in the source.
Can you explain this?

2020-04-22 12:15 UTC, simon987 commented on ports/libmupdf/CMakeLists.txt
> +    COMMAND ${MAKE_EXE} "generate"
Hi, it runs the command `make generate` which creates object files for the embedded fonts.

2020-04-23 02:26 UTC, JackBoosY commented on ports/libmupdf/CMakeLists.txt
> +    COMMAND ${MAKE_EXE} "generate"
```
root@usr:/home/work/vcpkg/buildtrees/libmupdf/src/ef6acfe21c-44efd46359# make generate
    LINK build/release/scripts/hexdump.exe
    GEN generated/resources/fonts/urw/Dingbats.cff.c
    GEN generated/resources/fonts/urw/NimbusMonoPS-Bold.cff.c
    GEN generated/resources/fonts/urw/NimbusMonoPS-BoldItalic.cff.c
    GEN generated/resources/fonts/urw/NimbusMonoPS-Italic.cff.c
    GEN generated/resources/fonts/urw/NimbusMonoPS-Regular.cff.c
    GEN generated/resources/fonts/urw/NimbusRoman-Bold.cff.c
    GEN generated/resources/fonts/urw/NimbusRoman-BoldItalic.cff.c
    GEN generated/resources/fonts/urw/NimbusRoman-Italic.cff.c
    GEN generated/resources/fonts/urw/NimbusRoman-Regular.cff.c
    GEN generated/resources/fonts/urw/NimbusSans-Bold.cff.c
    GEN generated/resources/fonts/urw/NimbusSans-BoldItalic.cff.c
    GEN generated/resources/fonts/urw/NimbusSans-Italic.cff.c
    GEN generated/resources/fonts/urw/NimbusSans-Regular.cff.c
    GEN generated/resources/fonts/urw/StandardSymbolsPS.cff.c
    GEN generated/resources/fonts/han/SourceHanSerif-Regular.ttc.c
    GEN generated/resources/fonts/droid/DroidSansFallback.ttf.c
    GEN generated/resources/fonts/droid/DroidSansFallbackFull.ttf.c
    GEN generated/resources/fonts/noto/NotoMusic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoNastaliqUrdu-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSans-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansAdlam-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansAnatolianHieroglyphs-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansArabic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansAvestan-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBamum-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBassaVah-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBatak-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBhaiksuki-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBrahmi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBuginese-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansBuhid-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCanadianAboriginal-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCarian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCaucasianAlbanian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansChakma-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCham-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCherokee-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCoptic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCuneiform-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansCypriot-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansDeseret-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansDuployan-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansEgyptianHieroglyphs-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansElbasan-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansGlagolitic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansGothic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansGrantha-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansHanunoo-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansHatran-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansImperialAramaic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansInscriptionalPahlavi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansInscriptionalParthian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansJavanese-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansKaithi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansKayahLi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansKharoshthi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansKhojki-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansKhudawadi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLepcha-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLimbu-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLinearA-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLinearB-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLisu-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLycian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansLydian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMahajani-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMandaic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansManichaean-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMarchen-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMath-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMeeteiMayek-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMendeKikakui-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMeroitic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMiao-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansModi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMongolian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMro-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansMultani-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansNKo-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansNabataean-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansNewTaiLue-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansNewa-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOgham-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOlChiki-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldHungarian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldItalic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldNorthArabian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldPermic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldPersian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldSouthArabian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOldTurkic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOsage-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansOsmanya-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansPahawhHmong-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansPalmyrene-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansPauCinHau-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansPhagsPa-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansPhoenician-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansPsalterPahlavi-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansRejang-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansRunic-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSamaritan-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSaurashtra-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSharada-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansShavian-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSiddham-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSoraSompeng-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSundanese-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSylotiNagri-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSymbols-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSymbols2-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansSyriac-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansTagalog-Regular.otf.c
    GEN generated/resources/fonts/noto/NotoSansTa [...]

2020-04-23 02:28 UTC, JackBoosY requested changes

2020-04-23 02:28 UTC, JackBoosY commented on ports/libmupdf/CMakeLists.txt
> +  find_program(MAKE_EXE NAMES gmake nmake make REQUIRED)
Since this is only triggered when it is non-windows, please replace this line to `find_program(MAKE_EXE NAMES make REQUIRED)`

2020-04-24 02:24 UTC, JackBoosY approved these changes

2020-04-24 02:24 UTC, JackBoosY commented
LGTM.

2020-04-24 09:58 UTC, merged

2020-04-24 09:58 UTC, ras0219-msft commented
LGTM, thanks for the PR!