[openslide] Port openslide.
microsoft/vcpkg pull request #10720
Opened 2020-04-07 06:50 UTC by onurtemizkan

Fixes: #3660

2020-04-07 06:50 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10720) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10720) before we can accept your contribution.<br/><br/>:x: onurtemizkan [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10720)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10720) it.</sub>

2020-04-16 08:50 UTC, NancyLi1013 requested changes

2020-04-16 08:50 UTC, NancyLi1013 commented on ports/openslide/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/openslide RENAME copyright)
Could you please update this as
`file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-04-16 08:51 UTC, NancyLi1013 commented
Hi @onurtemizkan 
It seems that this port cannot work in current statue.

2020-04-17 19:35 UTC, onurtemizkan commented
Hi @NancyLi1013, I have been distracted by other work after my first attempt on this port. But I'm planning to do some more work on this PR when I am able to. So, please keep it open until then.

2020-04-20 01:49 UTC, NancyLi1013 commented
@onurtemizkan 
Thanks for your update.

2020-05-21 07:58 UTC, NancyLi1013 commented
/azp run

2020-06-09 07:29 UTC, NancyLi1013 commented
Hi @onurtemizkan 
Is work still being done for this PR?

2020-07-16 02:51 UTC, NancyLi1013 commented
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

2020-07-16 02:51 UTC, closed without merging