[]Fix libarchive libuv static linkage
microsoft/vcpkg pull request #10769
Opened 2020-04-10 10:28 UTC by Neumann-A

**Describe the pull request**

- What does your PR fix? Fixes issue #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-04-13 03:15 UTC, LilyWangL commented
`include(vcpkg_common_functions)` is deprecated in _libuv/portfile.cmake_. Please remove it.

2020-04-13 03:15 UTC, LilyWangL requested changes

2020-04-13 03:15 UTC, LilyWangL commented on ports/libarchive/portfile.cmake
>      file(READ ${HEADER} CONTENTS)
Can you please use command `file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-04-13 03:15 UTC, LilyWangL commented on ports/libuv/portfile.cmake
> +
Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-04-16 20:23 UTC, ras0219-msft requested changes

2020-04-16 20:23 UTC, ras0219-msft commented on ports/libarchive/portfile.cmake
>          -DPOSIX_REGEX_LIB=NONE
Should this option be removed since it is specified above?

2020-04-16 20:23 UTC, ras0219-msft commented on ports/libarchive/portfile.cmake
> +    message(STATUS ${_feature_name} status ${_feature_status})
Please remove this debugging message

2020-04-17 21:13 UTC, merged

2020-04-17 21:13 UTC, ras0219-msft commented
LGTM, thanks!