[physfs] mirror url
microsoft/vcpkg pull request #10781
Opened 2020-04-11 12:50 UTC by Voskrese

download error

2020-04-13 02:47 UTC, NancyLi1013 requested changes

2020-04-13 02:47 UTC, NancyLi1013 commented on ports/physfs/CONTROL
>  Build-Depends: zlib
I noticed that `physfs `was set as `fail `on `arm64-windows`.
So it might be needed to add `Supports: !arm64` here.

2020-04-13 02:47 UTC, NancyLi1013 commented on ports/physfs/portfile.cmake
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?
Also `vcpkg_fail_port_install(ON_ARCH "arm64")` might be added here.

2020-04-13 06:53 UTC, NancyLi1013 approved these changes

2020-04-16 19:39 UTC, merged

2020-04-16 19:39 UTC, ras0219-msft commented
LGTM, thanks for the PR1