Add microsoft-signalr package
microsoft/vcpkg pull request #10833
Opened 2020-04-14 23:27 UTC by BrennanConroy

**Describe the pull request**

Adding the microsoft-signalr package to vcpkg.

@anurse @ras0219-msft

2020-04-16 06:30 UTC, LilyWangL requested changes

2020-04-16 06:30 UTC, LilyWangL commented on ports/microsoft-signalr/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-04-16 06:30 UTC, LilyWangL commented on ports/microsoft-signalr/portfile.cmake
> +file(COPY ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/microsoft-signalr)
Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-04-16 06:30 UTC, LilyWangL commented on ports/microsoft-signalr/CONTROL
> +Version: 0.1.0-alpha1
Can you please add the Homepage for this port in the CONTROL file?
```
Homepage: https://github.com/aspnet/SignalR-Client-Cpp
```

2020-04-16 06:37 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Version: 0.1.0-alpha1
Yeah, I tried that and it failed. Maybe it's a newer feature than the version of vcpkg I have locally...

2020-04-23 21:32 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Default-Features: cpprestsdk
cpprestsdk by default no longer includes websockets, need to change this to: `cpprestsdk[default-features,websockets]`

2020-04-23 21:32 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Build-Depends: cpprestsdk, openssl
cpprestsdk by default no longer includes websockets, need to change this to: `cpprestsdk[default-features,websockets]`

2020-04-24 19:08 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Supports: !uwp
@LilyWangL Is `Supports` not supported on features?

2020-04-26 06:24 UTC, LilyWangL commented on ports/microsoft-signalr/CONTROL
> +Supports: !uwp
Yes, `Supports` only support on port now.

2020-04-26 06:28 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Supports: !uwp
That's unfortunate, how do I add an exception for testing on uwp for the PR?

2020-04-26 07:55 UTC, LilyWangL commented on ports/microsoft-signalr/CONTROL
> +Supports: !uwp
The features of port do not need to indicate that which triplet is not supported temporarily.

2020-04-26 08:36 UTC, LilyWangL commented on ports/microsoft-signalr/CONTROL
> +Supports: !uwp
Due to feature `cpprestsdk` build failed on triplet uwp, you should not set `cpprestsdk` to default features. And add message to portfile.cmake to description feature `cpprestsdk` doesn't support triplet uwp.

2020-05-05 01:04 UTC, BrennanConroy commented
@LilyWangL This should be good now? The Linux failure looks like an infrastructure issue.

2020-05-06 09:35 UTC, LilyWangL commented
> @LilyWangL This should be good now? The Linux failure looks like an infrastructure issue.

Waiting for PR #11189 merge, this fix the CI baseline error.

2020-05-12 09:26 UTC, LilyWangL approved these changes

2020-05-12 23:18 UTC, strega-nil requested changes
Just a minor change here to avoid silent failures; thanks so much!

2020-05-12 23:18 UTC, strega-nil commented on ports/microsoft-signalr/CONTROL
> +Build-Depends: cpprestsdk[default-features,websockets] (!uwp)
This should not be `(!uwp)`; we shouldn't silently failing to depend on cpprestsdk in uwp.

```suggestion
Build-Depends: cpprestsdk[default-features,websockets]

```

2020-05-12 23:18 UTC, strega-nil commented on ports/microsoft-signalr/portfile.cmake
> +if("cpprestsdk" IN_LIST FEATURES AND NOT VCPKG_TARGET_IS_UWP)
This should use `vcpkg_check_features`:

```cmake
vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        cpprestsdk USE_CPPRESTSDK
)
```

2020-05-12 23:18 UTC, strega-nil commented on ports/microsoft-signalr/portfile.cmake
> +    set(USE_CPPRESTSDK false)
And then instead of this, doing:

```cmake
if("cpprestsdk" IN_LIST FEATURES AND VCPKG_TARGET_IS_UWP)
    message(FATAL_ERROR "microsoft-signalr[cpprestsdk] is not supported on UWP")
endif()
```

or something like that.

2020-05-12 23:18 UTC, strega-nil commented on ports/microsoft-signalr/portfile.cmake
> +        -DBUILD_TESTING=OFF
Then here you'd put `${FEATURE_OPTIONS}`

2020-05-12 23:21 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Build-Depends: cpprestsdk[default-features,websockets] (!uwp)
cpprestsdk+websockets doesn't work on uwp, but we want the default to be to install cpprestsdk. So it seems better to silently not install cpprestsdk on uwp than to force everyone else to have to specify cpprestsdk as a feature. (This is because there isn't support for `Supports` on features)

2020-05-12 23:24 UTC, BrennanConroy commented on ports/microsoft-signalr/CONTROL
> +Build-Depends: cpprestsdk[default-features,websockets] (!uwp)
Just read your other comment with the fatal_error. That would be ok, especially if I include the correct command to install the package on uwp.

2020-05-12 23:35 UTC, strega-nil commented on ports/microsoft-signalr/CONTROL
> +Build-Depends: cpprestsdk[default-features,websockets] (!uwp)
Ah, this is how you should do this then:

```
Source: microsoft-signalr
Version: 0.1.0-alpha1
Description: C++ Client for ASP.NET Core SignalR.
Default-Features: default-features
Homepage: https://github.com/aspnet/SignalR-Client-Cpp

Feature: default-features
Build-Depends: microsoft-signalr[cpprestsdk] (!uwp)
Description: Features installed by default

Feature: cpprestsdk
Description: Add default Http and WebSocket implementations using CppRestSDK
Build-Depends: cpprestsdk[default-features,websockets]
```

2020-05-13 23:57 UTC, strega-nil commented
Awesome, thanks so much! Are you comfortable with me merging now?

2020-05-13 23:59 UTC, BrennanConroy commented
Yes please :)

Thanks for helping clean this up!

2020-05-15 19:05 UTC, strega-nil commented
Alright, awesome! Thanks @BrennanConroy :)

2020-05-15 19:05 UTC, merged