[skyr-url] Bump version to 1.7.0
microsoft/vcpkg pull request #10868
Opened 2020-04-16 20:52 UTC by glynos

**Describe the pull request**

- What does your PR fix? Fixes issue #

Updates version of skyr-url, including additional features

- Which triplets are supported/not supported? Have you updated the CI baseline?
x64-osx, x64-linux, x64-windows

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-04-17 06:09 UTC, NancyLi1013 commented
Hi @glynos 
Thanks for this PR.
Could you please look into the regressions on x64-windows-static triplet?
```
-- Found nlohmann_json: C:/vsts/_work/3/s/installed/x64-windows-static/share/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.7.3") 
CMake Error at src/CMakeLists.txt:6 (configure_file):
  configure_file Problem configuring file
```

2020-04-17 06:09 UTC, NancyLi1013 requested changes

2020-04-17 06:09 UTC, NancyLi1013 commented on ports/skyr-url/portfile.cmake
Could you please update this 
`file(INSTALL ${SOURCE_PATH}/LICENSE_1_0.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/skyr-url RENAME copyright)`
as
`file(INSTALL ${SOURCE_PATH}/LICENSE_1_0.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-04-20 02:38 UTC, NancyLi1013 approved these changes

2020-04-21 20:26 UTC, merged

2020-04-21 20:26 UTC, ras0219-msft commented
Thanks for this PR!