[Quill] Add new port
microsoft/vcpkg pull request #10902
Opened 2020-04-19 01:13 UTC by odygrd

**Describe the pull request**
`Quill` is a C++14 logging library 
https://github.com/odygrd/quill

- What does your PR fix? Fixes issue #
N/A

- Which triplets are supported/not supported? Have you updated the CI baseline?
Tested `x86-windows`/`x64-windows`. I have not updated the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-04-19 01:13 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10902) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10902) before we can accept your contribution.<br/><br/>:x: odygrd [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10902)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10902) it.</sub>

2020-04-19 03:09 UTC, odygrd commented
It looks like the CI tests for `arm64-windows` and `arm-uwp` still run and being reported as failed in the CI after updating the `supports` expression and the ci baseline.
Is there any way to ignore them ?

2020-04-20 03:04 UTC, NancyLi1013 requested changes

2020-04-20 03:04 UTC, NancyLi1013 commented on ports/quill/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME quill)
`vcpkg_test_cmake()` is deprecated. Could you please remove this line?

2020-04-20 03:04 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> +quill:x64-uwp=skip
If these triplets currently are not supported, they should be set as `fail `instead of `skip`. 
I also want to confirm with you if it supports `x86-windows`, `x64-windows` and `x64-windows-static` triplets?

2020-04-20 03:08 UTC, NancyLi1013 commented
Hi @odygrd 
Thanks for your PR.
For the regressions on `arm-uwp` and `arm64-windows` about `otl` are not related with this PR, which has been fixed in PR #10922. Please ignore this.

2020-04-20 12:53 UTC, odygrd commented on scripts/ci.baseline.txt
> +quill:x64-uwp=skip
Hello, `x86-windows`, `x64-windows` and `x64-windows-static` are all supported.
I was reading the documentation here 
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md
and I thought `windows` is an alias for windows store, but reading it again it looks like it is an alias for everything related to windows.

Only 3 triplets not supported `arm64`, `arm, `uwp`

2020-04-20 13:12 UTC, odygrd commented on ports/quill/CONTROL
> +Supports: !(arm|arm64|uwp|windows|android)
I have removed `windows`

2020-04-20 13:13 UTC, odygrd commented on ports/quill/CONTROL
> +Supports: !(arm|arm64|uwp|windows|android)
It also supports windows, i only meant to disable uwp

2020-04-20 13:13 UTC, odygrd commented
Thanks a lot for reviewing @NancyLi1013 , I have made all the requested changes

2020-04-21 00:47 UTC, NancyLi1013 commented
/azp run

2020-04-21 02:06 UTC, NancyLi1013 approved these changes

2020-04-21 02:58 UTC, NancyLi1013 requested changes

2020-04-21 02:58 UTC, NancyLi1013 commented on ports/quill/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
Since this port currently doesn't support arm and uwp. We also need to add `vcpkg_fail_port_install(ON_ARCH "arm" ON_TARGET "uwp")` here.

2020-04-21 03:08 UTC, odygrd commented
Thanks @NancyLi1013 . 
I have already tested `x86 windows` and `x64 windows` . Could you please explain what the `Needs Testing` label means. Do I have to do any additional testing on my behalf or does it mean that you would like to test it yourself ?

2020-04-21 03:28 UTC, NancyLi1013 commented
@odygrd 
Since CI currently doesn't support the test for features. We need to test them manually.
Once passed, I will remove the label `Needs Testing`.

2020-04-21 03:30 UTC, NancyLi1013 approved these changes

2020-04-21 05:53 UTC, NancyLi1013 requested changes

2020-04-21 05:53 UTC, NancyLi1013 commented on ports/quill/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
The version of archive seems to be 1.2.0. But the version in CONTROL file is 1.2.1.
Could you please also update this as the latest version?
Since the URL is from GitHub. It might be better to use `vcpkg_from_github()` to get the source code.
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO odygrd/quill
    REF 18271f251ccd5244c0052ed0565a1ada517f5c25 #v1.2.1
    SHA512 
    HEAD_REF master
)
```
If we use this function, `vcpkg_extract_source_archive_ex()` is not needed.
I'm sorry, I didn't noticed this for the last review.

2020-04-21 05:53 UTC, NancyLi1013 commented on ports/quill/CONTROL
> +Feature: external_lib_fmt
The feature might be renamed as `fmt`, which makes it simple.

2020-04-21 05:53 UTC, NancyLi1013 commented on ports/quill/portfile.cmake
> +if("external_lib_fmt" IN_LIST FEATURES)
The same comment as described in CONTROL file.

2020-04-21 05:53 UTC, NancyLi1013 commented on ports/quill/portfile.cmake
> +    external_lib_fmt QUILL_FMT_EXTERNAL
The same comment as described in CONTROL file.

2020-04-21 05:53 UTC, NancyLi1013 commented on ports/quill/portfile.cmake
> +	file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/quill/quill/src/bundled/fmt)
Please update the format for this line. It should be left-aligned with the above file.

2020-04-21 11:55 UTC, odygrd commented
Sorry about this, I have made the changes are re-tested on windows

2020-04-22 03:13 UTC, NancyLi1013 approved these changes

2020-04-22 07:29 UTC, NancyLi1013 commented
The feature `fmt `have passed with the following triplets:
- x86-windows
- x64-windows
- x64-windows-static

2020-04-23 20:26 UTC, ras0219-msft requested changes

2020-04-23 20:26 UTC, ras0219-msft commented on ports/quill/portfile.cmake
> +    fmt QUILL_FMT_EXTERNAL
We always want to use the vcpkg versions of dependencies; there's no need for a feature for this. This port should always depend on fmt and always specify `QUILL_FMT_EXTERNAL`

2020-04-23 21:34 UTC, odygrd commented on ports/quill/portfile.cmake
> +    fmt QUILL_FMT_EXTERNAL
removed option and retested

2020-04-24 04:40 UTC, ras0219-msft commented
Great work!

2020-04-24 04:40 UTC, merged