[alembic] linux fixes
microsoft/vcpkg pull request #10912
Opened 2020-04-19 19:36 UTC by fabiencastan

**Describe the pull request**

- What does your PR fix? Fixes issue #

Fix the portfile to avoid windows-specific commands.
Fix a linux build error due to `-Werror` in the library in debug mode. The build issue has been also reported to the main repository https://github.com/alembic/alembic/issues/263.

- Which triplets are supported/not supported? Have you updated the CI baseline?

The alembic port file was valid only for windows. This PR adds the support for linux.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-04-19 19:37 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10912) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10912) before we can accept your contribution.<br/><br/>:x: fabiencastan [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10912)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10912) it.</sub>

2020-04-20 06:23 UTC, LilyWangL requested changes

2020-04-20 06:23 UTC, LilyWangL commented on ports/alembic/portfile.cmake
> +if(NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
We prefer to use `VCPKG_TARGET_IS_WINDOWS` instead of `VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" OR NOT VCPKG_CMAKE_SYSTEM_NAME`.
Could you please update it?

2020-04-20 06:23 UTC, LilyWangL commented on ports/alembic/portfile.cmake
> +if(NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
We prefer to use `VCPKG_TARGET_IS_WINDOWS` instead of `VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" OR NOT VCPKG_CMAKE_SYSTEM_NAME`.
Could you please update it?

2020-04-20 06:24 UTC, LilyWangL commented
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

2020-04-20 11:19 UTC, fabiencastan commented on ports/alembic/portfile.cmake
> +if(NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
Yes, I will do the update.
As this test adds specific flags to the compiler, it would be even better to test directly which compiler is being used. But I don't know id there is a way to do that.

2020-04-20 11:41 UTC, fabiencastan commented
I'm not sure if I should update the version number, as it doesn't change anything on windows. And on linux it has never been possible to build before, so there is no need for invalidation either.

2020-04-21 02:04 UTC, LilyWangL commented
> I'm not sure if I should update the version number, as it doesn't change anything on windows. And on linux it has never been possible to build before, so there is no need for invalidation either.

You need update the version in CONTROL.

2020-04-21 07:24 UTC, fabiencastan commented
Ok, updated.

2020-04-22 02:30 UTC, LilyWangL commented
Could you please remove `alembic:x64-linux=fail` in _scripts/ci.baseline.txt_, it makes Linux build failed.

2020-04-22 10:44 UTC, fabiencastan commented
Changed. I was not aware of this mechanism.
Thanks.

2020-04-23 02:23 UTC, LilyWangL approved these changes

2020-04-23 20:51 UTC, ras0219-msft commented
Thanks for the PR @fabiencastan!

Could you please revert the line ending change from LF to CRLF in `ports/alembic/portfile.cmake`? I tried pushing the change to your branch, however you did not select the "accept changes from maintainers" box.

2020-04-23 23:08 UTC, fabiencastan commented
Hi @ras0219-msft,
I updated the history to fix the mistake on the line ending.
(I do not find the option to allow the editing of the PR, maybe because it's a fork from an organization and not from my personal account)
Best,

2020-05-01 00:45 UTC, strega-nil commented
LGTM! Thanks @fabiencastan

2020-05-01 00:45 UTC, merged