Fix boost-locale failing to build with ICU
microsoft/vcpkg pull request #10943
Opened 2020-04-21 00:33 UTC by Victor-Bergman

**Get boost-locale to link with ICU library**

- fixes #3537 by modifying and apply a patch that already existed (and mentioned in #3537): 0001-Fix-boost-ICU-support.patch

2020-04-21 00:33 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10943) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10943) before we can accept your contribution.<br/><br/>:x: Victor-Bergman [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10943)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10943) it.</sub>

2020-04-21 03:18 UTC, NancyLi1013 requested changes

2020-04-21 03:18 UTC, NancyLi1013 commented on ports/boost-locale/portfile.cmake
> +
This function is deprecated. We can place the patch here.
```
vcpkg_from_github(
...
PATCHES
    0001-Fix-boost-ICU-support.patch
)
```

2020-04-21 03:18 UTC, NancyLi1013 commented on ports/boost-locale/portfile.cmake
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

2020-04-21 03:20 UTC, NancyLi1013 commented
Hi @Victor-Bergman 
Thanks for this PR.
Could you please also bump the `version ` as  `1.72.0-1` in `CONTROL `file?

2020-04-21 14:39 UTC, Victor-Bergman commented on ports/boost-locale/portfile.cmake
Both requested changes are committed

2020-04-21 19:03 UTC, Victor-Bergman commented
After making the 2 changes from the review (remove include and move PATCHES), the tests on linux and OSX fail (above).  These were passing last night and it makes no sense that these 2 changes should cause them to fail.

2020-04-21 20:10 UTC, ras0219-msft commented
/azp run

2020-04-23 06:05 UTC, NancyLi1013 commented
/azp run

2020-04-27 07:02 UTC, NancyLi1013 commented
/azp run

2020-04-27 07:06 UTC, NancyLi1013 approved these changes

2020-04-30 02:13 UTC, NancyLi1013 commented
/azp run

2020-04-30 06:27 UTC, NancyLi1013 commented
Need to test feature.

2020-05-06 03:09 UTC, JackBoosY commented
/azp run

2020-05-07 06:05 UTC, NancyLi1013 commented
Feature has passed on the following triplets:
- x86-windows
- x64-windows
- x64-windows-static
- x64-linux

2020-05-08 01:44 UTC, NancyLi1013 commented
@Victor-Bergman 
Could you please help confirm if this can work on static build? Or is there something that needs to be configured separately?

2020-05-14 02:58 UTC, NancyLi1013 commented
@Victor-Bergman 
Could you please resolve the conflicts?

2020-06-10 02:21 UTC, NancyLi1013 commented
@Victor-Bergman 
Is work still being done for this PR?

2020-06-23 10:59 UTC, pr8x commented
Can confirm that the PR is working and fixing the icu build for boost-locale. Thanks!

2020-06-23 11:11 UTC, PhoebeHui commented
The baseline failures should be addressed by https://github.com/microsoft/vcpkg/pull/12067

2020-06-29 06:09 UTC, PhoebeHui commented
/azp run

2020-06-29 08:49 UTC, PhoebeHui approved these changes

2020-06-30 00:44 UTC, BillyONeal commented on ports/boost-locale/0001-Fix-boost-ICU-support.patch
> +-#if defined(_MSC_VER) && !defined(_DLL)
I'm not sure we should be removing this error test; if we were triggering this #error it suggests we have broken the build script somewhere.

2020-06-30 01:01 UTC, PhoebeHui commented on ports/boost-locale/0001-Fix-boost-ICU-support.patch
> +-#if defined(_MSC_VER) && !defined(_DLL)
Background:
The patch from https://github.com/microsoft/vcpkg/pull/1453, from the author 'I had to rip out the ICU library detection from the build scripts because they always forced dynamic linking. The ICU libraries are now defined in the user-config, which is configured by the portfile to set the correct CRT linkage.'

We need revaluate this changes.

2020-06-30 01:39 UTC, BillyONeal commented on ports/boost-locale/0001-Fix-boost-ICU-support.patch
> +-#if defined(_MSC_VER) && !defined(_DLL)
I see, so it's removing the enforcement because it's attempting to make it actually work. @ras0219 @ras0219-msft can you take a look?

2020-06-30 01:46 UTC, ras0219 commented on ports/boost-locale/0001-Fix-boost-ICU-support.patch
> +-#if defined(_MSC_VER) && !defined(_DLL)
This seems like an acceptable change, because we are enabling users to link against static ICU.

The previous build scripts only supported a DLL ICU, which made it more reasonable to include this particular enforcement. Removing this enforcement just returns things to "normal behavior" -- mixing DLLs and static runtimes is always a problem (and we already have checks for that in vcpkg).

2020-06-30 01:47 UTC, ras0219 approved these changes
The version in the CONTROL file needs to be bumped -- otherwise LGTM

2020-06-30 01:48 UTC, BillyONeal commented on ports/boost-locale/0001-Fix-boost-ICU-support.patch
> +-#if defined(_MSC_VER) && !defined(_DLL)
Sounds good, I'm happy then :)

2020-06-30 03:18 UTC, PhoebeHui commented on ports/boost-locale/0001-Fix-boost-ICU-support.patch
> +-#if defined(_MSC_VER) && !defined(_DLL)
I remove this change, and test boost-locale[icu]:x64-window-static: and it failed with following failures, it looks default to dynamic link since we didn't specific the link and runtime link in user-config.jam.

has_icu_test.cpp
msvc.link F:\VCPKG\10943\vcpkg\buildtrees\boost-locale\x64-windows-static-dbg\boost\build\3b5884c1d1f69371a4c182d85379c63c\has_icu.exe
icuucd.lib(locid.ao) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in has_icu_obj.obj
icuucd.lib(unames.ao) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in has_icu_obj.obj
....

I add the link and runtime-link with vaule 'static' in user-config.jam, above failures have gone, and it start to failed with follwing failures with icu feature.

has_icu_obj.obj : error LNK2019: unresolved external symbol "public: __cdecl icu_67::Locale::Locale(void)" (??0Locale@icu_67@@QEAA@XZ) referenced in function main
has_icu_obj.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl icu_67::Locale::~Locale(void)" (??1Locale@icu_67@@UEAA@XZ) referenced in function main
has_icu_obj.obj : error LNK2019: unresolved external symbol u_charFromName_67 referenced in function main
F:\VCPKG\10943\vcpkg\buildtrees\boost-locale\x64-windows-static-dbg\boost\build\3b5884c1d1f69371a4c182d85379c63c\has_icu.exe : fatal error LNK1120: 3 unresolved externals

2020-06-30 10:43 UTC, PhoebeHui commented
Done, @BillyONeal  @vicroms, could you please help merge this PR?

2020-06-30 22:00 UTC, merged