[ports] add popsift
microsoft/vcpkg pull request #10979
Opened 2020-04-23 09:38 UTC by simogasp

**Describe the pull request**
It add a new port for popsift library for sift feature detection in images.
It depends on Cuda and optionally on boost if the tools are built.

- Which triplets are supported/not supported? Have you updated the CI baseline?
It builds on win, osx, and Linux, shared or static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

2020-04-23 09:38 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10979) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10979) before we can accept your contribution.<br/><br/>:x: simogasp [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=10979)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=10979) it.</sub>

2020-04-24 02:48 UTC, JackBoosY requested changes
When building `x86-windows`:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "popsift" in directory C:/agent/_work/1/s/buildtrees/popsift/src/v1.0.0-rc1-ce675fc178/src

-- Configuring incomplete, errors occurred!
```

When building `x64-windows-static`:
```
Expected Debug,Static crt linkage, but the following libs had invalid crt linkage:

    C:/agent/_work/1/s/packages/popsift_x64-windows-static/debug/lib/popsiftd.lib: Release,Static
```

2020-04-24 02:48 UTC, JackBoosY commented on ports/popsift/CONTROL
> +Build-Depends: cuda
Please add `Homepage` here.

2020-04-24 08:44 UTC, simogasp commented on ports/popsift/CONTROL
> +Build-Depends: cuda
thanks for the feedback, I'll update.

Concerning the building errors, we'll further check the `x64-windows-static` to fix it.

On the other hand, since we depend on cuda, I don't think cuda supports x86, at least on windows https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#x86-32-bit-support. And our code won't work on arm architectures.

So I'd be leaning to add this line
```
Supports: !(uwp|arm|arm64|android|x86)
```
Does it make sense to you?
Thank you!

2020-04-24 22:03 UTC, fabiencastan commented
I can reproduce the build error on "x64-windows-static" but I do not understand the problem. Does it mean that the library is built in Release instead of Debug?

2020-04-26 02:51 UTC, JackBoosY commented
@fabiencastan Yes, that's right.

2020-05-06 04:36 UTC, JackBoosY requested changes

2020-05-06 04:36 UTC, JackBoosY commented on ports/popsift/CONTROL
> +Supports: !(uwp|arm|arm64|android|x86)
Since this port doesn't support uwp, arm, arm64 and x86, please add the following codes to _VCPKG_PATH/scripts/ci.baseline.txt_:
```
popsift:x86-windows=fail
popsift:arm64-uwp=fail
popsift:x64-uwp=fail
popsift:arm64-windows=fail
```

2020-05-09 18:12 UTC, simogasp commented on ports/popsift/CONTROL
> +Supports: !(uwp|arm|arm64|android|x86)
done

2020-05-11 08:42 UTC, JackBoosY commented
/azp run

2020-05-11 08:46 UTC, JackBoosY commented
When building `popsiftx64-linux`:
```
CMake Error at /mnt/1/s/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindCUDA.cmake:700 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  /mnt/1/s/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:89 (find_package)
```

2020-05-11 09:56 UTC, simogasp commented
@JackBoosY thanks for the log
I don't understand though. Normally if we declare the dependency on cuda it would be up to the cuda port to declare this variable, as it already checks for the cuda install.
And I don't see why it works on windows and not on Linux: is cuda installed in some non-standard location on the azure machine?
In a recent change of the cuda port it only searches for system directories such as `/usr/local/cuda-*`
https://github.com/microsoft/vcpkg/pull/10979#L20
Could be that the issue?

2020-05-11 09:58 UTC, simogasp commented
BTW, it works ok on my local machine and I don't have any special env variable set for cuda

2020-05-14 05:42 UTC, JackBoosY requested changes

2020-05-14 05:42 UTC, JackBoosY commented on ports/popsift/portfile.cmake
> +#    HEAD_REF develop
Please remove these comments.

2020-05-14 05:42 UTC, JackBoosY commented on ports/popsift/portfile.cmake
> +#   - REF and SHA512 to the release version (remember to push to master the develop with release)
Please remove these comments.

2020-05-14 16:29 UTC, simogasp commented on ports/popsift/portfile.cmake
> +#    HEAD_REF develop
yes sure.
We are about to make the official release 1.0.0, so as soon as we have the tag to refer to I will clean up and set it up properly.

2020-05-14 16:31 UTC, simogasp commented on ports/popsift/portfile.cmake
> +#   - REF and SHA512 to the release version (remember to push to master the develop with release)
same as above :-)

2020-05-14 17:06 UTC, simogasp commented
@JackBoosY I'm sorry but I'm still struggling trying to figure out this Linux problem.
We have a simple line in our code to find cuda
`find_package(CUDA 7.0 REQUIRED)`
and indeed it is the findCUDA.cmake module that fails:
```
/mnt/1/s/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindCUDA.cmake:700 (message):
```
which can be found here https://github.com/Kitware/CMake/blob/v3.14.0/Modules/FindCUDA.cmake#L700

FindCUDA is normally able to find cuda in the most common installation places, if it is installed in some weird places, you can pass CUDA_TOOLKIT_ROOT_DIR to tell him where to look.

Even if I wanted to add this to our portfile I still have no clue on what to set it to:
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS} -DCUDA_TOOLKIT_ROOT_DIR:PATH="???????"
)
```
Is there any variable that has this information? Whenever the cuda portfile is called, are the variables set there visible by other packages? (I hope not as this can lead to a clusterf**k of name conflicts...)

2020-05-15 02:25 UTC, JackBoosY commented
@simogasp Yes, I‘m investigating this issue in depth.
The port cuda can already find the libraries and tools correctly, but cmake cannot.

2020-05-19 07:18 UTC, JackBoosY commented
Hmm... I have no permission to push to your branch.
Here is my changes: [popsift.zip](https://github.com/microsoft/vcpkg/files/4648802/popsift.zip)

2020-05-20 13:13 UTC, simogasp commented
thanks @JackBoosY for the patch, I'm pretty sure that with this it is gonna works.

On the other hand, I'm not sure that is the correct solution to put in place because we are just replicating the code of cuda portfile, which means we have to maintain it twice or more if the same patch it is applied to all the other packages depending on Cuda.

It seems that our package is the only one, so far, that has a mandatory dependency on Cuda, for all the others (darkned, opencv etc) it is only optional: I imagine that the CI does not build the optional features otherwise they would have the same issue as well.

I think that at this point we should figure out a way to export this `CUDA_TOOLKIT_ROOT_DIR` variable.
I'll try to spitball some ideas:

1. Obviously we can rely on the user to set it up as env variable because it is often what developers do and for sure if it exists we can rely on that to find Cuda (I'm talking about the Cuda portfile). On the other hand, we cannot make this mandatory because not everybody is familiar with low-level developing stuff such as setting env variables.

2. At the moment the Cuda portfile does nothing other than checking Cuda is there and it is the right version. The only thing that it installs is the abi txt with the various info. What could be done is for the portfile to export a simple CMake file, say `cuda.cmake`  (that will be installed in `share/cuda`) where the `CUDA_TOOLKIT_ROOT_DIR` is set to the proper value.
The port that depends on Cuda then will include `cuda.cmake` to get the value of `CUDA_TOOLKIT_ROOT_DIR` and pass it at CMake config.
This requires to access directly to the install folder of vcpkg and I don't know if it goes against the principles and the philosophy of the package manager.
But I think it is more maintainable solution than having each package personally looking for Cuda.
Each package will have to do something like:

```cmake
if(NOT DEFINED CUDA_TOOLKIT_ROOT_DIR)
  include(${VCPKG_INSTALL}share/cuda/cuda) # this is wrong but I don't know if there is a variable that we can use that tells the install path
endif()
...
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS}
    -DCUDA_TOOLKIT_ROOT_DIR:PATH=${CUDA_TOOLKIT_ROOT_DIR}
...
)
```

I think that something like that will benefit all the other packages that depend on Cuda.
Of course, it may not be the right or best solution, I don't know all the details of vcpkg to a have a better insight.
Since the problem is related to Cuda rather than our package we can also open a dedicate issue to discuss about that and have feedbacks from other maintainers.

thanks again for your help!

2020-05-21 07:24 UTC, JackBoosY commented
Yes, that's only a workaround.

According to [FindCUDA.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake#L696), has the cuda default path been changed?

@strega-nil What do you think about?

2020-06-02 01:06 UTC, BillyONeal commented
I observe that the port is trying to do `find_package(CUDA`. `FindCuda.cmake` says:

```
  Superseded by first-class support for the CUDA language in CMake.

Replacement
^^^^^^^^^^^

It is no longer necessary to use this module or call ``find_package(CUDA)``.
Instead, list ``CUDA`` among the languages named in the top-level
call to the :command:`project` command, or call the
:command:`enable_language` command with ``CUDA``.
Then one can add CUDA (``.cu``) sources to programs directly
in calls to :command:`add_library` and :command:`add_executable`.
```

The port is looking for CUDA 7 but our CI machines have CUDA 10.1 (soon to be 10.2). Perhaps the deprecated script hasn't been updated for the current versions?

We install CUDA here: https://github.com/microsoft/vcpkg/blob/5a80a8e9dd4d18e1491f57cf0d1f03ee8016acfd/scripts/azure-pipelines/linux/provision-image.sh#L38

2020-06-02 01:25 UTC, BillyONeal commented
I see that other ports that want CUDA have `set(ENV{CUDACXX} "$ENV{CUDA_PATH}/bin/nvcc")` in their portfile.cmake, that might be necessary.

2020-06-02 03:20 UTC, JackBoosY commented
According to the official [documentation](https://cmake.org/cmake/help/latest/module/FindCUDA.html#findcuda):
> Deprecated since version 3.10: Superseded by first-class support for the CUDA language in CMake. Superseded by the FindCUDAToolkit for CUDA toolkit libraries.

So, can you report this to upstream?

Thanks.

2020-06-02 03:38 UTC, BillyONeal commented
It looks like we need to come up with some way of exporting the path to CUDA determined by our `cuda\portfile.cmake` and feeding that in to other ports that want to use this deprecated findcuda.cmake script.

2020-06-02 08:24 UTC, simogasp commented
Thanks for your replies.
Concerning the installation script, I don't know if the Cuda installation creates a `/usr/local/cuda/` symlink, that's where FindCuda looks for the nvcc. 
It seems to me that there is only a `/usr/local/cuda10.1` which cannot be found by FindCuda as noted by @JackBoosY .
So adding a line like 
```
sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda
```
should make things better.
Also be careful as there is a 10.1 where I believe it should be a 10.2?
https://github.com/microsoft/vcpkg/blob/5a80a8e9dd4d18e1491f57cf0d1f03ee8016acfd/scripts/azure-pipelines/linux/provision-image.sh#L40

But I agree that having a mechanism to export the cuda path would be great!

2020-06-02 08:25 UTC, simogasp commented
> I observe that the port is trying to do find_package(CUDA. FindCuda.cmake says:
> ...

I agree that switching to first-class support for the CUDA  would be nice, but, unfortunately, it is still under development, not all the features are ported from `findCuda` like the choice of the CC etc. 
`FindCUDAToolkit` has been added only in the latest CMake version 3.17 and still lacks some features.

> The port is looking for CUDA 7 but our CI machines have CUDA 10.1 (soon to be 10.2). Perhaps the deprecated script hasn't been updated for the current versions?

We look for cuda 7 because it's the minimal version we are compatible with, normally this has no effect if a more recent version is installed.
In our travis CI we test with Cuda 8, 9 and 10.2 and we never had problems in that regards:
for example see [here for cuda 10.2](https://travis-ci.org/github/alicevision/popsift/jobs/693179482#L545)

2020-06-02 20:28 UTC, BillyONeal commented
> In our travis CI we test with Cuda 8, 9 and 10.2 and we never had problems in that regards

That's because you did the following, at least that's what it looks like from the build output:
```
 sudo ln -s /usr/local/cuda-${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR} /usr/local/cuda
```
the default CUDA installers don't do that and it isn't reasonable for vcpkg customers to be required to do that in order to use the package if CUDA's installers do not create that link.

vcpkg already contains code that finds a version of CUDA in the port, "cuda". We should feed that into the build system of the target library somehow rather than papering over this with a special machine configuration in CI.

2020-06-02 21:57 UTC, simogasp commented
I was talking about the fact of looking for lower versions of cuda, normally it's not a problem if u ask for a lower version and a greater is found.

Anyway, you are absolutely right about not asking any particular procedure to be made like creating the symlink.
I have not a deep knowledge of internal vcpkg structure/functioning to suggest any solution but I'm available for discussions and testing  :-)

2020-07-09 21:49 UTC, BillyONeal commented
Dropping requires-discussion: We don't want to make this special VM change and would prefer to see the port take steps to inject the version of CUDA detected by the 'coda' package; @ras0219 / @ras0219-msft indicates that we have some infrastructure to help with that somewhere, he should respond here soon-ish.

2020-09-08 12:46 UTC, fabiencastan commented
@BillyONeal @ras0219 @ras0219-msft Any news?

2020-09-10 00:27 UTC, ras0219 commented
I've opened #13440 to expose the CUDA settings we detect as part of the `cuda` helper port; once that's confirmed good and merged, we can use it in the `popsift` port to correctly consume CUDA.

2020-10-12 16:56 UTC, fabiencastan commented
@simogasp https://github.com/microsoft/vcpkg/pull/13440 is now merged.

2020-10-13 10:21 UTC, simogasp commented
@JackBoosY 
I updated the port file to use the newly introduced `vcpkg_find_cuda`.
It still fails on linux CI, this time cuda seems to be found but there are some error at cmake config
```
Starting package 2/2: popsift:x64-linux
Building package popsift[core]:x64-linux...
Could not locate cached archive: /archives/2e/2e8e3af591a9d98509c915475c6b70cedfb8520b.zip
-- Downloading https://github.com/alicevision/popsift/archive/v1.0.0-rc2.tar.gz...
-- Extracting source /mnt/vcpkg-ci/downloads/alicevision-popsift-v1.0.0-rc2.tar.gz
-- Using source at /mnt/vcpkg-ci/buildtrees/popsift/src/v1.0.0-rc2-4cf67195e1.clean
-- Found CUDA V10.2.89
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: /mnt/vcpkg-ci/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake /mnt/vcpkg-ci/buildtrees/popsift/src/v1.0.0-rc2-4cf67195e1.clean -DPopSift_BUILD_EXAMPLES=OFF -DCUDA_TOOLKIT_ROOT=/usr/local/cuda-10.2 -DCMAKE_MAKE_PROGRAM=/mnt/vcpkg-ci/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/agent/_work/1/s/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/agent/_work/1/s/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/agent/_work/1/s -D_VCPKG_INSTALLED_DIR=/mnt/vcpkg-ci/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/mnt/vcpkg-ci/packages/popsift_x64-linux/debug
    Working Directory: /mnt/vcpkg-ci/buildtrees/popsift/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /mnt/vcpkg-ci/buildtrees/popsift/config-x64-linux-dbg-out.log
      /mnt/vcpkg-ci/buildtrees/popsift/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  ports/popsift/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

```
Is it possible to see the content of those log files? `config-x64-linux-dbg-out.log` `config-x64-linux-dbg-err.log`?

2020-10-14 02:25 UTC, JackBoosY commented
```
CMake Error at /mnt/vcpkg-ci/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/share/cmake-3.17/Modules/FindCUDA.cmake:715 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:510 (_find_package)
  CMakeLists.txt:76 (find_package)
```
[failure logs for x64-linux.zip](https://github.com/microsoft/vcpkg/files/5375203/failure.logs.for.x64-linux.26.zip)

2020-10-27 09:03 UTC, JackBoosY commented
Any progress?

2020-10-27 09:07 UTC, simogasp commented
yes it works now!
We are just in the process of finalizing the v1.0.0 version of the library and then we are good to go.

2020-12-24 07:23 UTC, BillyONeal commented
@simogasp  Are you still working on this?

2020-12-24 13:10 UTC, simogasp commented
yes we have been finalising the 1.0 release but it is taking a bit more than expected. Maybe we can do an intermediate release 0.9 for the moment and finalize this PR and we'll do a new PR to update the version. What do you think?

2020-12-25 02:11 UTC, JackBoosY commented
@simogasp That's good!

2021-02-04 06:00 UTC, JackBoosY commented
This PR lasts over 2 months, any progress here?

2021-02-13 18:03 UTC, simogasp commented on ports/popsift/portfile.cmake
> +#   - REF and SHA512 to the release version (remember to push to master the develop with release)
done ee6e1133d

2021-02-13 18:03 UTC, simogasp commented on ports/popsift/portfile.cmake
> +#    HEAD_REF develop
done ee6e1133d

2021-02-13 19:34 UTC, simogasp commented
@JackBoosY any idea why we are getting this error, the baseline fine is correctly set
https://dev.azure.com/vcpkg/public/_build/results?buildId=49417&view=logs&j=0a61404f-5c45-5632-e83c-408b7fcca1d6&t=591b82ac-d7a4-522e-cf3c-66395e94b618&l=1619

2021-02-13 22:21 UTC, simogasp commented
@JackBoosY sorry, scratch my previous question, I didn't see we need another json to be added. Now it seems to be working.
You can merge if you don't have any further comments (at long last!! :-)

2021-02-18 07:17 UTC, JackBoosY requested changes

2021-02-18 07:17 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +popsift:arm64-windows=fail
```suggestion
```

2021-02-18 07:18 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +popsift:arm64-windows=fail
Since we've change the keyword `Supports` method, these codes is not needed.

2021-02-18 09:01 UTC, JackBoosY commented
Wait for #16270 merge.

2021-02-18 09:01 UTC, JackBoosY approved these changes

2021-02-19 02:41 UTC, JackBoosY commented
/azp run

2021-02-19 02:50 UTC, JackBoosY commented
LGTM in my side.

2021-03-10 17:49 UTC, simogasp commented
Any news? Is the PR ok to be merged or are there any more comments? I know we kept it WIP for a very long time, it would be nice to merge it soon if no other changes are required. Thx!

2021-03-11 20:21 UTC, merged

2021-03-11 20:22 UTC, ras0219-msft commented
Thanks for the ping to bring this back up to the top of the stack!