[openssl] Update openssl to 1.1.1g
microsoft/vcpkg pull request #11003
Opened 2020-04-24 07:57 UTC by crackedmind

Update openssl version from 1.1.1d to latest 1.1.1g. Also disable tests building to improve build time.

2020-04-26 08:48 UTC, NancyLi1013 commented
Hi @crackedmind 
Could you please resolve the conflicts first?

2020-04-27 03:07 UTC, fcharlie commented
@NancyLi1013 openssl 1.1.1g is a security update with the vulnerability number CVE-2020-1967 so it should be updated as soon as possible. I suggest that you should not wait for the PR author to respond, but take the initiative to resolve the conflict. There is a branch here that has resolved the conflict. https://github.com/fcharlie/vcpkg/tree/openssl_cve

2020-04-27 05:53 UTC, NancyLi1013 commented
@fcharlie thanks for your kindly reminder.
I resolved the conflicts just now.

2020-04-28 03:06 UTC, NancyLi1013 commented
The regressions caused by `gsoap `is fixed in #11048.

2020-05-07 06:34 UTC, NancyLi1013 requested changes

2020-05-07 06:34 UTC, NancyLi1013 commented on ports/openssl-unix/portfile.cmake
Could you please update the way to handle copyright as
`file(INSTALL ${MASTER_COPY_SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-05-07 06:34 UTC, NancyLi1013 commented on ports/openssl-unix/portfile.cmake
`vcpkg_test_cmake(PACKAGE_NAME OpenSSL MODULE)` is deprecated.
Could you please remove this?

2020-05-07 06:34 UTC, NancyLi1013 commented on ports/openssl-uwp/portfile.cmake
>  set(ENV{PATH} "$ENV{PATH};${PERL_EXE_PATH};${JOM_EXE_PATH}")
We prefer to use `vcpkg_add_to_path() ` instead of `set(ENV{PATH})`.
Could you please update this?

2020-05-07 06:34 UTC, NancyLi1013 commented on ports/openssl-windows/portfile.cmake
>  set(ENV{PATH} "$ENV{PATH};${PERL_EXE_PATH}")
We prefer to use `vcpkg_add_to_path()` instead of `set(ENV{PATH})`.
Could you please update this?

2020-05-07 06:34 UTC, NancyLi1013 commented on ports/openssl-windows/portfile.cmake
>  )
`vcpkg_test_cmake(PACKAGE_NAME OpenSSL MODULE)` is deprecated.
Could you please remove this?

2020-05-07 06:35 UTC, NancyLi1013 commented
/azp run

2020-05-09 09:38 UTC, NancyLi1013 commented
@crackedmind 
Could you please address the review suggestions?
Since this is a security update, it needs to be done as soon as possible. 

Please let me know if you have enough time to continue to make the progress for this PR.

Thanks.

2020-05-11 09:36 UTC, NancyLi1013 commented
/azp run

2020-05-13 01:24 UTC, NancyLi1013 commented
/azp run

2020-05-29 09:46 UTC, NancyLi1013 commented
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

2020-05-29 09:46 UTC, closed without merging