[cpprestsdk] Update to v2.10.16
microsoft/vcpkg pull request #11018
Opened 2020-04-25 00:51 UTC by BillyONeal

2020-04-26 09:02 UTC, LilyWangL requested changes

2020-04-26 09:02 UTC, LilyWangL commented on ports/cpprestsdk/portfile.cmake
>  vcpkg_from_github(
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-04-26 09:03 UTC, LilyWangL commented
The way to handle feature can be replaced by [vcpkg_check_features()](https://github.com/microsoft/vcpkg/blob/a3a6530631df905eb5c0e26d0b20d7d548e0c465/docs/maintainers/vcpkg_check_features.md).
```
set(CPPREST_EXCLUDE_BROTLI ON)
if ("brotli" IN_LIST FEATURES)
    set(CPPREST_EXCLUDE_BROTLI OFF)
endif()
set(CPPREST_EXCLUDE_COMPRESSION ON)
if ("compression" IN_LIST FEATURES)
    set(CPPREST_EXCLUDE_COMPRESSION OFF)
endif()
set(CPPREST_EXCLUDE_WEBSOCKETS ON)
if("websockets" IN_LIST FEATURES)
    set(CPPREST_EXCLUDE_WEBSOCKETS OFF)
endif()
```

2020-04-27 14:07 UTC, ras0219-msft commented
/azp run

2020-04-27 19:01 UTC, BillyONeal commented
@ras0219-msft Thanks for resolving the CR feedback!

2020-04-28 06:13 UTC, LilyWangL approved these changes

2020-04-28 16:10 UTC, cbezault commented on ports/cpprestsdk/CONTROL
>    boost-filesystem (!uwp&!windows), boost-random (!uwp&!windows), boost-chrono (!uwp&!windows),
As an aside, I _think_ default features can take qualifiers now.

2020-04-30 07:46 UTC, merged