[mstch] Add new port
microsoft/vcpkg pull request #11020
Opened 2020-04-25 07:46 UTC by curoky

Describe the pull request
Mstch is a complete implementation of {{mustache}} templates using modern C++
https://github.com/no1msd/mstch

What does your PR fix? Fixes issue #
N/A

Which triplets are supported/not supported? Have you updated the CI baseline?
Not sure.

Does your PR follow the maintainer guide?
Yes

2020-04-26 03:09 UTC, NancyLi1013 requested changes

2020-04-26 03:09 UTC, NancyLi1013 commented on ports/mstch/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

2020-04-26 03:09 UTC, NancyLi1013 commented on ports/mstch/portfile.cmake
> +    -DCMAKE_DEBUG_POSTFIX=d
if the upstream library has the same name in release and debug, we should not introduce a new name.
Please refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-rename-binaries-outside-the-names-given-by-upstream).

2020-04-26 08:45 UTC, curoky commented on ports/mstch/portfile.cmake
> +include(vcpkg_common_functions)
done

2020-04-26 08:45 UTC, curoky commented on ports/mstch/portfile.cmake
> +    -DCMAKE_DEBUG_POSTFIX=d
done

2020-04-26 09:13 UTC, NancyLi1013 approved these changes

2020-04-30 02:08 UTC, NancyLi1013 commented
/azp run

2020-05-01 00:47 UTC, strega-nil commented
LGTM, thanks @curoky :)

2020-05-01 00:47 UTC, merged