[gsoap] Add supports for gsoap
microsoft/vcpkg pull request #11048
Opened 2020-04-27 10:25 UTC by LilyWangL

**Describe the pull request**

- What does your PR fix? 
  Gsoap only supports `Win32`. Add `Supports` and `vcpkg_fail_port_install` for gsoap.
- No features need to test.

2020-04-28 02:21 UTC, JackBoosY requested changes

2020-04-28 02:21 UTC, JackBoosY commented on ports/gsoap/CONTROL
>  Version: 2.8.93-2
Update version.

2020-04-30 06:09 UTC, LilyWangL commented
/azp run

2020-05-01 00:17 UTC, strega-nil commented on ports/gsoap/portfile.cmake
>      set(BUILD_ARCH "Win32")
Given that we should never get to this point, this should probably just not `set`.

2020-05-01 00:18 UTC, strega-nil commented on ports/gsoap/CONTROL
> +Supports: x86
this should probably be `Supports: x86 & windows`

2020-05-01 00:18 UTC, strega-nil commented on ports/gsoap/portfile.cmake
>  if (VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
I don't understand why we don't remove this `if-else` now, since we don't support non-x86 non-windows.

2020-05-01 05:57 UTC, BillyONeal commented
/azp run

2020-05-06 17:40 UTC, strega-nil commented
Could you rerun after running the correct tombstone scripts?

2020-05-06 17:42 UTC, BillyONeal commented
/azp run

2020-05-08 06:24 UTC, strega-nil commented
LGTM! Thanks @LilyWangL :D

2020-05-08 06:24 UTC, merged