[boost-nowide-standalone] Add new port
microsoft/vcpkg pull request #11066
Opened 2020-04-28 06:19 UTC by tats-u

**Describe the pull request**

- What does your PR fix? --- N/A but  #11035

- Which triplets are supported/not supported? Have you updated the CI baseline? --- I don't know, but I'd like to make x{64,86}-windows supported

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  --- No as for now but I will make it do later (removing boiler plates)

2020-04-28 06:44 UTC, tats-u commented
I don't know how to `find_package` from CMake.
Both `boost-nowide-standalone` and `nowide` fails.

2020-04-28 07:06 UTC, tats-u commented
I don't know why CI for UWP and ARM failed.

2020-04-29 01:40 UTC, NancyLi1013 commented
x64-uwp and arm-uwp failed due to this:
```
10>C:\agent\_work\1\s\buildtrees\boost-nowide-standalone\src\dalone_v10-98a85ebde3\test\test_system.cpp(85,38): error C2039: 'getenv': is not a member of 'std' [C:\agent\_work\1\s\buildtrees\boost-nowide-standalone\arm-uwp-dbg\test\nowide-test_system_n.vcxproj]
    16>C:\agent\_work\1\s\buildtrees\boost-nowide-standalone\src\dalone_v10-98a85ebde3\test\test_system.cpp(85,38): error C2039: 'getenv': is not a member of 'std' [C:\agent\_work\1\s\buildtrees\boost-nowide-standalone\arm-uwp-dbg\test\nowide-test_system_w.vcxproj]
```
arm64-windows failed due to this:
```
test_system.cpp.obj : error LNK2019: unresolved external symbol __imp_CommandLineToArgvW referenced in function "public: __cdecl nowide::args::wargv_ptr::wargv_ptr(void)" (??0wargv_ptr@args@nowide@@QEAA@XZ)
nowide-test_system_w.exe : fatal error LNK1120: 1 unresolved externals
```

2020-04-29 01:54 UTC, NancyLi1013 requested changes

2020-04-29 01:54 UTC, NancyLi1013 commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
This port seems to be related with `boost `but it can also be independent from `boost`.
If we name this port like this, it will be easy to mistake it as a module of `boost`. 
What do you think about this?

2020-04-29 01:54 UTC, NancyLi1013 commented on ports/boost-nowide-standalone/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME boost-nowide-standalone)
`vcpkg_test_cmake()` is deprecated.
Could you please remove this function?

2020-04-29 02:07 UTC, tats-u commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
It can be built as a part of Boost.
It depends on Boost by default (git repository).
Is just `nowide` or `nowide-standalone` enough?

2020-04-29 02:08 UTC, tats-u commented on ports/boost-nowide-standalone/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME boost-nowide-standalone)
I got it.
Please wait revised commit(s).

2020-04-29 02:18 UTC, tats-u commented
ARM and UWP seems

2020-04-29 02:19 UTC, tats-u commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
There is `nowideConf.cmake`, so can I try `nowide`?

2020-04-29 02:52 UTC, tats-u commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
By changing to `nowide`, I was able to link this in my program.

2020-04-29 03:28 UTC, NancyLi1013 commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
In my opinion, `nowide `might be better.

2020-04-29 03:29 UTC, NancyLi1013 commented
You can ignore the failure for `mlcpk `on macOS, which is not related with this PR.
We are trying to fix this.

2020-04-29 04:39 UTC, tats-u commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
Is the trailing space necessary?

2020-04-29 05:48 UTC, NancyLi1013 commented
/azp run

2020-04-29 06:30 UTC, NancyLi1013 commented
Hi @tats-u 
For the usage of `nowide`, we should use the following code:

```
The package nowide:x86-windows provides CMake targets:

    find_package(nowide CONFIG REQUIRED)
    target_link_libraries(main PRIVATE nowide::nowide)

```
Also please use this CMake option `"-DVCPKG_TARGET_TRIPLET=x64-windows"`. Please make sure that you have installed `nowide:x64-windows`.

I also noticed that there was no build result on osx pipeline.

2020-04-29 06:36 UTC, NancyLi1013 commented on ports/boost-nowide-standalone/CONTROL
> +Source: boost-nowide-standalone
If we use `nowide` as the port name, it's not necessary to add the space.  This is just my own opinion.
The port name may be needed our colleague to further review.

2020-04-29 06:43 UTC, tats-u commented
I forgot to tell you that I  have already replaced `find_package(boost-nowide-standalone  CONFIG REQUIRED)` in my `CMakeLists.txt` with `find_package(nowide  CONFIG REQUIRED)`.

2020-04-29 07:25 UTC, tats-u commented
CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.13)
add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/Zc:__cplusplus>")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
project(foobar CXX)

find_package(nowide CONFIG REQUIRED)

add_executable(foobar foobar.cpp)
target_link_libraries(foobar PRIVATE nowide::nowide)
```

foobar.cpp

```cpp
#include <iostream>
#include <nowide/args.hpp>
#include <nowide/iostream.hpp>
#ifdef _WIN32
#include <windows.h>
#endif

int main(int argc, char** argv) {
  using namespace nowide;
  args _(argc, argv);
  cout << "ハローワールド (Hello world)\n";
  for(int i = 0; i < argc; ++i) {
    cout << "引数 (Argument) " << i << ": " << argv[i] << '\n';
  }
#ifdef _WIN32
  const auto acp = GetACP();
  cout << "ACP: " << acp << '\n';
#endif
  return 0;
}
```

Build (`-DVCPKG_TARGET_TRIPLET=x64-windows` is not concerned with the result; I tried both added and not)

```pwsh
cmake ..  -DCMAKE_TOOLCHAIN_FILE=C:/Users/tatsu/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja
cmake --build .
```

Run

```pwsh
PS> .\foobar.exe あいうえお abcdefg ☢⚠➗™©℃ pokémon
ハローワールド (Hello world)
引数 (Argument) 0: C:\Users\tatsu\source\repos\cppu8test\build\foobar.exe
引数 (Argument) 1: あいうえお
引数 (Argument) 2: abcdefg
引数 (Argument) 3: ☢⚠➗™©℃
引数 (Argument) 4: pokémon
ACP: 932
```

2020-04-29 08:02 UTC, NancyLi1013 commented
Yes, if you build static, it 's necessary to add the option.

2020-04-29 08:03 UTC, NancyLi1013 approved these changes

2020-04-29 10:41 UTC, tats-u commented
Should I add the following lines to `scripts/ci.baseline.txt`?

```
nowide:arm64-windows=fail
nowide:arm-uwp=fail
nowide:x64-uwp=fail
```

2020-04-30 01:50 UTC, NancyLi1013 commented
If it's not easy to solve the regressions on arm and uwp, you can disable `test`.
I noticed that they failed in building `test`.
Add  `-DBUILD_TESTING=OFF` option.

2020-04-30 02:06 UTC, NancyLi1013 commented
/azp run

2020-04-30 02:23 UTC, tats-u commented
I tried adding this in `vcpkg_configure_cmake`:

```
    OPTIONS_RELEASE -DBUILD_TESTING=OFF
    OPTIONS_DEBUG -DBUILD_TESTING=OFF
```

2020-04-30 02:57 UTC, NancyLi1013 commented
You can only add `OPTIONS `  `-DBUILD_TESTING=OFF` . And there is no need to distinguish debug or release.

2020-04-30 03:44 UTC, tats-u commented
I changed.
I wonder if the line break code is wrong.

2020-04-30 04:26 UTC, tats-u commented
All CIs passed.
It is time to merge.

2020-04-30 05:40 UTC, NancyLi1013 commented
@strega-nil 
Could you help review this PR and check if the port name is appropriate?

2020-05-01 22:10 UTC, strega-nil commented
Alright, this looks great! Thanks @tats-u :)

2020-05-01 22:10 UTC, merged

2020-05-02 03:32 UTC, tats-u commented
Thank you for cooperating and allowing merge, @NancyLi1013 and @NancyLi1013 .