On Linux, stormlib and casclib both implemented GetLastError(), there…
microsoft/vcpkg pull request #11114
Opened 2020-05-01 14:24 UTC by Sweepi

…fore any project using both libs cannot link. Fixed.

Both stormlib and casclib implement 
GetLastError()
SetLastError()

on Linux. Therefore projects using both libraries cannot link on Linux.
The change neither effect users on Windows nor users who are using only one of the libs on Linux.

2020-05-01 14:25 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11114) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11114) before we can accept your contribution.<br/><br/>:x: Sweepi [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11114)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=11114) it.</sub>

2020-05-06 06:09 UTC, NancyLi1013 requested changes

2020-05-06 06:09 UTC, NancyLi1013 commented on ports/casclib/CONTROL
>  Description: An open-source implementation of library for reading CASC storage from Blizzard games since 2014
Could you please add homepage here?
`Homepage: https://github.com/ladislav-zezula/CascLib`

2020-05-06 06:09 UTC, NancyLi1013 commented on ports/casclib/portfile.cmake
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this?

2020-05-06 06:09 UTC, NancyLi1013 commented on ports/casclib/portfile.cmake
Could you please update the way to handle copyright as

```
file(INSTALL ${SOURCE_PATH}/LICENSE 
     DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}
     RENAME copyright)
```
?

2020-05-06 06:11 UTC, NancyLi1013 requested changes

2020-05-06 06:11 UTC, NancyLi1013 commented on ports/casclib/CONTROL
> +Build-Depends: zlib, stormlib
Why is `stormlib` required here?

2020-05-06 06:17 UTC, NancyLi1013 commented
Hi @Sweepi 
Thanks for this PR.
If both `stormlib `and `casclib `implement `GetLastError()`, why did you only fix `casclib ` in this PR instead of both of them?

2020-05-06 11:21 UTC, Sweepi commented
Hi @NancyLi1013 ,

The PR includes a patch file which removes both functions from CascLib, which therefore now depends on StormLibs implementation of GetLastError(). This fixes the double definition error when linking both libs in the same project.

This is not pretty at all, but preserves backwards compatibility.

Only other option I see would be to move both functions to a separate library, and then add a dependency to that lib to both CascLib and StormLib.

2020-05-08 07:27 UTC, NancyLi1013 commented
/azp run

2020-05-08 08:22 UTC, NancyLi1013 commented
@Sweepi 
Could you please address the review suggestions?

2020-06-17 07:53 UTC, NancyLi1013 commented
@Sweepi 
Is work still being done for this PR?

2020-07-09 10:26 UTC, NancyLi1013 commented
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

2020-07-09 10:26 UTC, closed without merging