[premake5] Add new port
microsoft/vcpkg pull request #11292
Opened 2020-05-10 18:38 UTC by thomaskrause

**Describe the pull request**
This adds the new package premake5, which is a build file generator similiar to cmake but based on simple Lua scripts

- What does your PR fix? 
 No packaging request was added as an issue as far as I know.

- Which triplets are supported/not supported? Have you updated the CI baseline?
CI was not changed. I tested this with x64-linux and x86-windows.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I choose to use GNU Make on Linux/Mac and msbuild on Windows because that is the native build system used by premake5 and it would have been difficult to map this to CMake. Also, I'm not using the Git repository directly, but the released tar-balls because only these include the pre-generated project files (additional bootstrapping would be needed when using the Git checkout directly).

I'm not sure if I handled the version number correctly. The original authors are using the "alpha 15" suffix (where the number will increment) and I used the same version including the spaces.

2020-05-10 19:16 UTC, Voskrese commented
now this is unnecessary

` include(vcpkg_common_functions)`

2020-05-11 07:46 UTC, thomaskrause commented
> now this is unnecessary
> 
> ` include(vcpkg_common_functions)`

Thanks for the hint, I don't know if i introduced this line during debugging to fix another error (that was probably unrelated) but its removed now. x64_osx pipeline is failing because the Git checkout failed. I hope this is a temporary failure, compiling premake5 should also work on OSX (and did work in earlier commits when the git checkout succeeded)

2020-05-11 08:18 UTC, Voskrese commented
this is a Ci error, wait for it to be fixed

2020-05-11 09:21 UTC, JackBoosY requested changes

2020-05-11 09:21 UTC, JackBoosY commented on ports/premake5/portfile.cmake
> +set(BUILD_CONFIG "release")
This line should be added to `else()`

2020-05-11 09:21 UTC, JackBoosY commented on ports/premake5/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
Is there no header file available for this port?

2020-05-11 09:21 UTC, JackBoosY commented on ports/premake5/portfile.cmake
> +    find_program(MAKE make REQUIRED)
We already have functions `vcpkg_*_make`.
Please see documentation:
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_make.md
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_build_make.md
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_make.md

Example: [tcl](https://github.com/Microsoft/vcpkg/blob/master/ports/tcl/portfile.cmake)

2020-05-11 10:33 UTC, DailyShana commented
premake5 is not a library.
Is it acceptable to add non-libraries to vcpkg?

2020-05-12 03:07 UTC, JackBoosY commented
@DailyShana If premake5 is a build tool, I prefer to add it to the tool list rather than a port.

2020-05-14 17:43 UTC, thomaskrause commented on ports/premake5/portfile.cmake
> +set(BUILD_CONFIG "release")
Fixed in 0f0cc20b1dde6dd5e9820a099315466accdce16b

2020-05-14 17:47 UTC, thomaskrause commented on ports/premake5/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
Yes, this port produces an executable ("premake5") as main result. I can add a comment to the portfile with an explanation if you want.

2020-05-14 18:00 UTC, thomaskrause commented
> @DailyShana If premake5 is a build tool, I prefer to add it to the tool list rather than a port.

Yes, premake5 is indeed a build tool

2020-05-14 18:19 UTC, thomaskrause commented on ports/premake5/portfile.cmake
> +    find_program(MAKE make REQUIRED)
I could not get `vcpkg_build_make` to work because it needs the `vcpkg_configure_make` script to run first. These makefiles are not generated with autoconf and there are nor configure scripts. I tried to use it with `SKIP_CONFIGURE` like in this example:
```cmake
    vcpkg_configure_make(
        SKIP_CONFIGURE
        PROJECT_SUBPATH ${SOURCE_PATH}/build/gmake2.unix/
    )
    vcpkg_build_make(TARGET "Premake5")
```
Unfortunately i consistently get an error when trying this:
```
-- Using generator make
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:246 (file):
  file COPY cannot find "/dev/disk/by-partlabel/EFI/x20System/x20Partition".
Call Stack (most recent call first):
  ports/premake5/portfile.cmake:34 (vcpkg_configure_make)
  scripts/ports.cmake:90 (include)
```

2020-05-14 19:10 UTC, thomaskrause commented on ports/premake5/portfile.cmake
> +    find_program(MAKE make REQUIRED)
I could resolve the issue with `vcpkg_build_make` and I am using it now on Linux and OSX builds (fd4a673476c32734b42b31e5dc120fd1249457ad)

2020-05-15 04:48 UTC, JackBoosY commented on ports/premake5/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
@thomaskrause See #10505.

2020-05-19 08:44 UTC, thomaskrause commented on ports/premake5/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
Ok, I will look into that example and see if I can adapt this PR.

2020-05-20 07:24 UTC, JackBoosY commented
@thomaskrause Please ping me if this PR is ready for review.

Thanks.

2020-09-18 07:05 UTC, closed without merging