[OpenGL] Fix lib files copy when VCPKG_BUILD_TYPE is set
microsoft/vcpkg pull request #11294
Opened 2020-05-10 21:52 UTC by AenBleidd

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

2020-05-10 22:18 UTC, BillyONeal commented
/azp run

2020-05-11 02:49 UTC, PhoebeHui requested changes
@AenBleidd, thanks for the PR!

Could you also update Version to  0.0-6 in CONTROL file?

2020-05-11 03:05 UTC, AenBleidd commented
@PhoebeHui, done. Thanks for the fast review!

2020-05-11 21:34 UTC, Neumann-A commented on ports/opengl/portfile.cmake
> +        )
```
${CURRENT_PACKAGES_DIR}/include/gl
and
${CURRENT_PACKAGES_DIR}/share/opengl
```
are required in a debug only build

2020-05-11 21:42 UTC, AenBleidd commented on ports/opengl/portfile.cmake
> +        )
Fixed

2020-05-12 07:16 UTC, PhoebeHui approved these changes

2020-05-12 23:30 UTC, strega-nil approved these changes
Some minor changes, but this looks great! Thanks @AenBleidd :)

2020-05-12 23:30 UTC, strega-nil commented on ports/opengl/portfile.cmake
> +    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL release)
```suggestion
    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
```

gotta make sure not to dereference the `release` variable :)

2020-05-12 23:30 UTC, strega-nil commented on ports/opengl/portfile.cmake
> +    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL debug)
```suggestion
    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
```

2020-05-12 23:30 UTC, strega-nil commented on ports/opengl/portfile.cmake
> +    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL release)
Same as above :)

```suggestion
    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
```

2020-05-12 23:30 UTC, strega-nil commented on ports/opengl/portfile.cmake
> +    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL debug)
```suggestion
    if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
```

2020-05-15 23:35 UTC, strega-nil commented
Oops, forgot to merge after I pushed changes; thanks @AenBleidd :D

2020-05-15 23:35 UTC, merged

2020-05-16 20:53 UTC, AenBleidd commented
@strega-nil, thank you too :)