[Quill] update to v1.3.1
microsoft/vcpkg pull request #11326
Opened 2020-05-13 02:55 UTC by odygrd

**Describe the pull request**

- What does your PR fix? Fixes 
Version update

- Which triplets are supported/not supported? Have you updated the CI baseline?
I have updated the CI baseline

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-05-13 03:06 UTC, LilyWangL requested changes

2020-05-13 03:06 UTC, LilyWangL commented on scripts/ci.baseline.txt
> -quill:arm64-windows=fail
This command shouldn't be removed, because this port doesn't support `arm`.

2020-05-13 03:28 UTC, odygrd commented on scripts/ci.baseline.txt
> -quill:arm64-windows=fail
Hey Lily, the 1.3.1 version now supports arm64, should I still add this line back ?

2020-05-13 05:57 UTC, LilyWangL commented
If the new version supports arm64, you need remove `arm` from  `Supports` in CONTROL and remove `ON_ARCH "arm"` from `vcpkg_fail_port_install` in portfile.cmake. Because `arm - VCPKG_TARGET_ARCHITECTURE == "arm" or VCPKG_TARGET_ARCHITECTURE == "arm64"`.
And I test this PR on my locally, I build `quill:arm64-windows` failed with this error:
```
vcpkg\buildtrees\quill\src\76aaafff6d-cac280987f\quill\include\quill/detail/misc/Rdtsc.h(62): error C3861: '__rdtsc': identifier not found
vcpkg\buildtrees\quill\src\76aaafff6d-cac280987f\quill\include\quill/detail/misc/Rdtsc.h(62): error C3861: '__rdtsc': identifier not found
vcpkg\buildtrees\quill\src\76aaafff6d-cac280987f\quill\include\quill/detail/misc/Rdtsc.h(62): error C3861: '__rdtsc': identifier not found
vcpkg\buildtrees\quill\src\76aaafff6d-cac280987f\quill\include\quill/detail/misc/Rdtsc.h(62): error C3861: '__rdtsc': identifier not found
vcpkg\buildtrees\quill\src\76aaafff6d-cac280987f\quill\include\quill/detail/misc/Rdtsc.h(62): error C3861: '__rdtsc': identifier not found
```

2020-05-13 08:26 UTC, odygrd commented
thanks Lilly, I am reverting the changes for now

2020-05-13 09:17 UTC, LilyWangL approved these changes

2020-05-15 23:55 UTC, strega-nil commented
Alright cool, thanks y'all!

2020-05-15 23:55 UTC, merged