Fix openssl-unix android build
microsoft/vcpkg pull request #11344
Opened 2020-05-13 23:37 UTC by majaeger

Updates the openssl-unix port to properly build for Android

- What does your PR fix? Fixes #9874, #11282, #8174

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. Tested w/ [arch]-android and [arch]-android-static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-05-14 06:05 UTC, LilyWangL commented
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

2020-05-14 06:08 UTC, LilyWangL requested changes

2020-05-14 06:08 UTC, LilyWangL commented on ports/openssl-unix/portfile.cmake
>  )
`include(vcpkg_common_functions)` is deprecated. Please remove it. And we prefer to use `VCPKG_TARGET_IS_WINDOWS` instead of `VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" OR NOT VCPKG_CMAKE_SYSTEM_NAME`. Could you please update it?

2020-05-14 06:08 UTC, LilyWangL commented on ports/openssl-unix/portfile.cmake
>      if(NOT MAKE)
`vcpkg_test_cmake` is deprecated. Please remove it.

2020-05-14 19:50 UTC, BillyONeal commented
/azp run

2020-05-19 18:03 UTC, majaeger commented
I ended up hitting the same issue as this PR : https://github.com/microsoft/vcpkg/pull/11344

Will wait and merge changes to msys code after that is merged

2020-05-21 02:14 UTC, LilyWangL commented
/azp run

2020-05-21 06:37 UTC, LilyWangL commented
@majaeger Now port `signalrclient` and `osg` build failed on Linux, they all depend on opnssl-unix.

2020-05-26 02:37 UTC, LilyWangL commented
@majaeger Can you resolve the conflict _scripts/cmake/vcpkg_acquire_msys.cmake_?

2020-06-02 05:24 UTC, majaeger commented
@LilyWangL sorry for the delay. I've undone my changes to vcpkg_acquire_msys.cmake

2020-06-03 07:43 UTC, LilyWangL approved these changes

2020-06-05 19:38 UTC, dan-shaw commented on ports/openssl-unix/CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "Android" OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
I'm not sure why we are removing this check. What does it fix?

2020-06-06 22:57 UTC, majaeger commented on ports/openssl-unix/CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "Android" OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
@dan-shaw , the build for android used to require workarounds / custom rules because of the older clang version used by the Android NDK. In more recent versions ( including r21, which is the first LTS release of the NDK), this is not needed, and actually breaks the build (See the various issues linked to the PR)

2020-06-06 22:58 UTC, majaeger commented on ports/openssl-unix/CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "Android" OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
This fix is to simply treat the Android build as any other linux build

2020-06-11 08:13 UTC, dan-shaw commented on ports/openssl-unix/CMakeLists.txt
> +if(CMAKE_SYSTEM_NAME STREQUAL "Android" OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
Ok. That makes sense

2020-06-11 08:13 UTC, merged

2020-06-11 08:14 UTC, dan-shaw commented
Thanks for the PR!