[fcl] Explicity handle FCL_USE_X64_SSE CMake option
microsoft/vcpkg pull request #11406
Opened 2020-05-17 13:55 UTC by traversaro

The FCL_USE_X64_SSE option is enabled by default in fcl, but it only make sense to enable SSE flags when targeting either x86 or x64.

Related upstream PR: https://github.com/flexible-collision-library/fcl/pull/470 .

- What does your PR fix? There is no relative issue. 

- Which triplets are supported/not supported? Have you updated the CI baseline? The CI baseline should not change.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2020-05-18 07:23 UTC, PhoebeHui requested changes
@traversaro, thanks for the PR!

Could you also update the Version to '0.6.0-1' in CONTROL file?

2020-05-18 07:26 UTC, traversaro commented
> 
> 
> @traversaro, thanks for the PR!
> 
> Could you also update the Version to '0.6.0-1' in CONTROL file?

Done in https://github.com/traversaro/vcpkg/commit/a02bab87e1f18c384d6ec341441f742fa9cdac9e .

2020-05-19 03:21 UTC, PhoebeHui approved these changes
Thanks for the udpates!

2020-05-19 05:38 UTC, PhoebeHui commented
The CI failed on 'git checkout' step, it doesn't related to this change, @strega-nil, could  you help have a look?

2020-05-19 22:09 UTC, strega-nil commented
/azp run

2020-05-19 22:11 UTC, strega-nil commented
Cools, LGTM! Thanks @traversaro :)

I'll wait for the CI to finish and then merge.

2020-05-20 05:50 UTC, PhoebeHui commented
The CI failures doesn't relate to this changes.
Protobuf with arm/uwp failed due to it requires x86-windows protoc to be available, this is expected, PR https://github.com/microsoft/vcpkg/pull/11459 would fix it.

Failures:
CMake Error at ports/protobuf/portfile.cmake:21 (message):
  Cross-targetting protobuf requires the x86-windows protoc to be available.
  Please install protobuf:x86-windows first.

2020-05-20 17:11 UTC, strega-nil commented
/azp run

2020-05-20 21:24 UTC, merged

2020-05-20 21:24 UTC, strega-nil commented
Alright, it passed! Thanks @traversaro :)