[VMSS] add cmake
microsoft/vcpkg pull request #11414
Opened 2020-05-17 19:05 UTC by Voskrese

2020-05-18 06:21 UTC, NancyLi1013 requested changes

2020-05-18 06:21 UTC, NancyLi1013 commented on ports/mpir/portfile.cmake
Could you please update this
`configure_file(${SOURCE_PATH}/COPYING.lib ${CURRENT_PACKAGES_DIR}/share/mpir/copyright COPYONLY)`
as
`configure_file(${SOURCE_PATH}/COPYING.lib ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)`?

2020-05-18 06:25 UTC, NancyLi1013 approved these changes

2020-05-19 21:51 UTC, Voskrese commented
fix 
https://github.com/microsoft/STL/blob/master/azure-devops/provision-image.ps1

2020-05-20 04:22 UTC, Voskrese commented
close it?

2020-05-20 18:13 UTC, BillyONeal commented
@Voskrese Indeed, does https://github.com/microsoft/vcpkg/pull/10767 resolve this to your satisfaction?

2020-05-20 18:34 UTC, Voskrese commented
@BillyONeal 
I have nothing to do with this, the main thing is that the service works and test the libraries

2020-05-20 18:34 UTC, closed without merging