[ace] Simplified port file
microsoft/vcpkg pull request #11464
Opened 2020-05-20 14:16 UTC by jwillemsen

**Describe the pull request**

- What does your PR fix?

Reworked portfile to use an array to simplify the port file and more easily add more directories later

2020-05-20 14:19 UTC, jwillemsen commented
See #8468, there it was added for adding tao

2020-05-20 20:26 UTC, jwillemsen commented
Looks failure is not caused by my changes

2020-05-21 03:02 UTC, JackBoosY requested changes

2020-05-21 03:02 UTC, JackBoosY commented on ports/ace/process_manager.patch
> +-#if defined ACE_HAS_SIG_C_FUNC
Can you change this line to `#if 0` instead of deleting these lines?

2020-05-21 03:02 UTC, JackBoosY commented on ports/ace/process_manager.patch
> +-#if defined ACE_HAS_SIG_C_FUNC
Same above.

2020-05-21 03:02 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +    PATCHES "${CMAKE_CURRENT_LIST_DIR}/process_manager.patch"
```suggestion
    PATCHES process_manager.patch
```

2020-05-21 05:08 UTC, jwillemsen commented on ports/ace/process_manager.patch
> +-#if defined ACE_HAS_SIG_C_FUNC
This exact patch has been committee to ACE, would like to not make a different patch just for vcpkg

2020-05-21 05:49 UTC, JackBoosY approved these changes

2020-05-21 18:35 UTC, strega-nil commented
@jwillemsen should this be the second or third PR merged?

2020-05-21 18:42 UTC, jwillemsen commented
3rd

2020-05-27 05:30 UTC, dan-shaw approved these changes

2020-05-27 06:18 UTC, LilyWangL commented
@jwillemsen Can you resolve the conflict files?

2020-05-27 14:30 UTC, jwillemsen commented
Conflicts have been resolved

2020-05-28 20:09 UTC, merged

2020-05-28 20:09 UTC, dan-shaw commented
Thanks!