[vcpkg] Allow CI to pass in all relevant directories and remove use of symbolic links
microsoft/vcpkg pull request #11483
Opened 2020-05-21 02:52 UTC by BillyONeal

Adds `--x-foo-root=` parameters for the directories to which we have applied symlinks in the past, such as installed, buildtrees, packages, etc.

This is intended to unblock https://github.com/microsoft/vcpkg/pull/11365 which broke due the symlink workaround we previously used to get the work tree onto the VM temp disk not working with the current Scale Set Agents installation script.

Drive-by fixes:
* Fixed help text having differing output and alignment caused by duplicating these declarations in the tool
![image](https://user-images.githubusercontent.com/1544943/82517869-ef7d5700-9ad2-11ea-87f2-7990ad4a88ab.png)
* Always use HelpTableFormatter to emit help tables.
* Fixed parameter validation, filesystem validation, and path conversion being spewed out in between VcpkgCmdArguments, VcpkgPaths, and main(). Now VcpkgCmdArguments owns command line argument parsing and reading defaults from the environment, VcpkgPaths owns only path resolution bits. Theoretically this reduces the fidelity of the error messages we emit here, but I don't think in practice customized error messages for each type of missing input or output directory add much user value. We emit messages containing the bad path whenever something explodes anyway.

2020-05-22 08:19 UTC, Neumann-A commented on scripts/buildsystems/vcpkg.cmake
> +endif()
Hmm is there a reason to not directly pass `installed/triplet` instead?

2020-05-22 08:23 UTC, Neumann-A commented on scripts/buildsystems/vcpkg.cmake
> +endif()
Probably should replace all usage of `${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}` to `${VCPKG_INSTALLED_TRIPLET_DIR}` in the toolchain `vcpkg.cmake` and the wrappers `vcpkg_cmake_wrappers.cmake`

2020-05-22 08:24 UTC, BillyONeal commented on scripts/buildsystems/vcpkg.cmake
> +endif()
This is the file users who use vcpkg include, so we don't know what the triplet is yet. We could pass that in rather than detecting it too; I was trying to make minimal changes to the cmake infrastructure as I understand cmake less than c++ :)

2020-05-22 08:25 UTC, BillyONeal commented on scripts/buildsystems/vcpkg.cmake
> +endif()
Can do that

2020-05-22 08:27 UTC, BillyONeal commented on scripts/buildsystems/vcpkg.cmake
> +endif()
On second thought, this change is already huge enough, can that be done in a followup PR?

2020-05-22 08:33 UTC, Neumann-A commented on scripts/buildsystems/vcpkg.cmake
> +endif()
Do as you like.

2020-05-22 17:53 UTC, Voskrese commented
merge?

2020-05-25 04:59 UTC, BillyONeal commented
Depends on https://github.com/microsoft/vcpkg/pull/11483 and https://github.com/microsoft/vcpkg/pull/11545

2020-05-25 19:45 UTC, Neumann-A commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
That is wrong.
You probably want
```
"/p:VcpkgTriplet=${TARGET_TRIPLET}"
"/p:VcpkgRoot=${VCPKG_ROOT_DIR}"
```

2020-05-25 19:50 UTC, Neumann-A commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
`VcpkgRoot` should be renamed to `VcpkgInstalledTriplet` instead....

2020-05-25 23:12 UTC, BillyONeal commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
I agree :)

2020-05-28 02:37 UTC, strega-nil requested changes
There's some weird stuff, but it's mostly minor. Thanks @BillyONeal :)

2020-05-28 02:37 UTC, strega-nil commented on scripts/azure-pipelines/linux/azure-pipelines.yml
> +      sudo mkdir /mnt/vcpkg-ci/downloads -m=777
(Given this without an intervening `mount`, this seems like it's just on the local hard drive? which is fine, but why's it in `/mnt`)

2020-05-28 02:37 UTC, strega-nil commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
Is `${CURRENT_INSTALLED_DIR}` `installed/triplet` or just `installed`?

2020-05-28 02:37 UTC, strega-nil commented on ports/spirv-tools/portfile.cmake
> +        -DSPIRV-Headers_SOURCE_DIR=${CURRENT_INSTALLED_DIR}
Because here, you've got `${CURRENT_INSTALLED_DIR}` being used to mean `installed/triplet`, afaict.

2020-05-28 03:22 UTC, BillyONeal commented on scripts/azure-pipelines/linux/azure-pipelines.yml
> +      sudo mkdir /mnt/vcpkg-ci -m=777
Azure mounts the temporary disk to `/mnt`; see the last line of df -h in one of our build logs:

```
/bin/bash --noprofile --norc /agent/_work/_temp/6c461458-6559-418b-a4db-89d8303fb4fc.sh
Filesystem                                      Size  Used Avail Use% Mounted on
udev                                             32G     0   32G   0% /dev
tmpfs                                           6.3G  700K  6.3G   1% /run
/dev/sdb1                                        29G  5.6G   24G  20% /
tmpfs                                            32G  8.0K   32G   1% /dev/shm
tmpfs                                           5.0M     0  5.0M   0% /run/lock
tmpfs                                            32G     0   32G   0% /sys/fs/cgroup
/dev/sdb15                                      105M  3.6M  101M   4% /boot/efi
//prlin20200507.file.core.windows.net/archives  2.0T  1.1T  953G  54% /archives
/dev/sda1                                       393G   26G  347G   7% /mnt
```

2020-05-28 03:34 UTC, BillyONeal commented on toolsrc/src/vcpkg/build.cpp
> +                    VCPKG_LINE_INFO, fs, paths.scripts / fs::u8path("toolchains") / fs::u8path("freebsd.cmake"), algo);
The multiple operator/s ensure that the preferred separator is used there... I was being paranoid :)

2020-05-28 03:35 UTC, BillyONeal commented on scripts/azure-pipelines/windows/azure-pipelines.yml
> +  - task: CmdLine@2
That has different effects. As written this causes ADO to run that script directly, with the short form you show it creates a script file with the content `.\boostrap-vcpkg.bat`, and then invokes that temporary.

I guess it's not a huge deal either way.

2020-05-28 15:44 UTC, strega-nil commented on scripts/azure-pipelines/linux/azure-pipelines.yml
> +      sudo mkdir /mnt/vcpkg-ci -m=777
... I hate it.

2020-05-28 15:45 UTC, strega-nil commented on scripts/azure-pipelines/windows/azure-pipelines.yml
> +  - task: CmdLine@2
oh, then don't worry about it.

2020-05-28 15:45 UTC, strega-nil commented on toolsrc/src/vcpkg/build.cpp
> +                    VCPKG_LINE_INFO, fs, paths.scripts / fs::u8path("toolchains") / fs::u8path("freebsd.cmake"), algo);
Given how quickly Windows converts `/` to `\`, I'm not worried about it. If you are, then you can change it.

2020-05-29 04:52 UTC, BillyONeal commented on ports/spirv-tools/portfile.cmake
> +        -DSPIRV-Headers_SOURCE_DIR=${CURRENT_INSTALLED_DIR}
`set(CURRENT_INSTALLED_DIR ${_VCPKG_INSTALLED_DIR}/${TARGET_TRIPLET} CACHE PATH "Location to install final packages")`

No I don't know why the spirv build succeeds ¯\_(ツ)_/¯

2020-05-29 04:53 UTC, BillyONeal commented on scripts/azure-pipelines/linux/azure-pipelines.yml
> +      sudo mkdir /mnt/vcpkg-ci -m=777
I don't think there's anything we can change it to that would make it obvious but I can add a comment.

2020-05-29 05:01 UTC, BillyONeal commented on toolsrc/src/vcpkg/build.cpp
> +                    VCPKG_LINE_INFO, fs, paths.scripts / fs::u8path("toolchains") / fs::u8path("freebsd.cmake"), algo);
Changed.

2020-05-29 05:04 UTC, BillyONeal commented
> There's some weird stuff, but it's mostly minor. Thanks @BillyONeal :)

idk I think you found a serious bug!

2020-05-29 11:39 UTC, BillyONeal commented
/azp run

2020-05-29 16:37 UTC, strega-nil commented on ports/spirv-tools/portfile.cmake
> +        -DSPIRV-Headers_SOURCE_DIR=${CURRENT_INSTALLED_DIR}
So then this use is correct, and it should succeed.

2020-05-29 16:37 UTC, strega-nil commented on scripts/azure-pipelines/linux/azure-pipelines.yml
> +      sudo mkdir /mnt/vcpkg-ci -m=777
that sounds good to me :)

2020-05-29 17:08 UTC, strega-nil commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
is `VcpkgRoot` the equivalent of `CURRENT_INSTALLED_DIR`? I would expect this variable to be something like where the `vcpkg` executable lives.

2020-05-29 17:08 UTC, strega-nil commented on scripts/cmake/vcpkg_install_msbuild.cmake
> +        "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
Same questions as with `build_msbuild`.

2020-05-29 17:45 UTC, BillyONeal commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
Yes, it is like `CURRENT_INSTALLED_DIR` -- the name is bad because I didn't write the script consuming the variable (it's `$/scripts/buildsystems/msbuild/vcpkg.targets`). I don't want to edit that here because I don't know exactly how it interacts with `vcpkg integrate install`. Would filing an issue about it and addressing in a subsequent PR be OK? (I don't want to grow this PR even bigger :) )

2020-05-29 17:48 UTC, BillyONeal commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
Hmmm I guess I could make a dependent change which changes that name, stand by...

2020-05-29 18:02 UTC, BillyONeal commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
https://github.com/microsoft/vcpkg/pull/11653

2020-05-29 20:49 UTC, strega-nil commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
so should we merge 11653 first?

2020-05-29 23:39 UTC, BillyONeal commented on scripts/cmake/vcpkg_build_msbuild.cmake
> +            "/p:VcpkgRoot=${CURRENT_INSTALLED_DIR}"
Yes, done.

2020-05-30 00:04 UTC, strega-nil commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            const auto VCPKG_DISABLE_METRICS_ENV = System::get_environment_variable("VCPKG_DISABLE_METRICS");
Why are these all SCREAMING_SNAKES?

2020-05-30 00:06 UTC, BillyONeal commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            const auto VCPKG_DISABLE_METRICS_ENV = System::get_environment_variable("VCPKG_DISABLE_METRICS");
I wanted to indicate that the variable is in exactly the same as the environment variable of the same name (that's also the pattern below). I had to add an ENV suffix here though because `VCPKG_DISABLE_METRICS` is also already a macro :/

2020-05-30 00:06 UTC, BillyONeal commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            const auto VCPKG_DISABLE_METRICS_ENV = System::get_environment_variable("VCPKG_DISABLE_METRICS");
I am not wed to this convention, SUPER open to other suggestions :)

2020-05-30 00:09 UTC, strega-nil commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            const auto VCPKG_DISABLE_METRICS_ENV = System::get_environment_variable("VCPKG_DISABLE_METRICS");
I'd prefer `vcpkg_disable_metrics_env` style, personally.

2020-05-30 00:15 UTC, BillyONeal commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            const auto VCPKG_DISABLE_METRICS_ENV = System::get_environment_variable("VCPKG_DISABLE_METRICS");
Done.

2020-05-30 00:17 UTC, strega-nil approved these changes

2020-06-01 03:00 UTC, JackBoosY requested changes
Please update `qt5-base`, `shiva-sfml`, `spirv-tools` version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-06-03 00:33 UTC, BillyONeal commented
> Please update `qt5-base`, `shiva-sfml`, `spirv-tools` version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

Done, thanks!

2020-06-03 03:00 UTC, JackBoosY approved these changes

2020-06-04 02:31 UTC, merged

2020-06-04 10:44 UTC, Maximus5 commented on scripts/buildsystems/msbuild/vcpkg.targets
> +    <VcpkgCurrentInstalledDirSanitized>$(VcpkgCurrentInstalledDir)</VcpkgCurrentInstalledDirSanitized>
Looks like there is a problem here.
The `VcpkgCurrentInstalledDir` initialization was removed few lines above and it's empty now.