[libvpx] Change default target on Unix
microsoft/vcpkg pull request #11500
Opened 2020-05-21 14:30 UTC by kafeg

Set default libvpx target to the 'x86_64-darwin17-gcc'. It's macOS 10.13 (High Sierra)

It's required to support the latest CPU features like hardware acceleration.

2020-05-22 02:25 UTC, JackBoosY requested changes
Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-05-22 02:26 UTC, JackBoosY commented
Waiting for merge #11496.

2020-05-22 08:00 UTC, kafeg commented
Done

2020-05-22 08:09 UTC, JackBoosY approved these changes

2020-05-22 08:09 UTC, JackBoosY commented
LGTM, thanks for this PR!

2020-05-23 05:03 UTC, strega-nil commented on ports/libvpx/portfile.cmake
> +        set(LIBVPX_TARGET "x86_64-linux-gcc")
This seems to break non-x64 -- does this not compile on x86?

2020-05-23 08:02 UTC, kafeg commented on ports/libvpx/portfile.cmake
> +        set(LIBVPX_TARGET "x86_64-linux-gcc")
Hello! I thought as vcpkg has only **x64-linux** official triplet, then we could build only for it =)

But you're right, I will fix this part! Thank you!

2020-05-23 21:51 UTC, strega-nil commented on ports/libvpx/portfile.cmake
> +        set(LIBVPX_TARGET_ARCH "x86_64")
Could you add an:

```
else()
    message(FATAL_ERROR "libvpx does not support architecture ${VCPKG_TARGET_ARCHITECTURE}")
endif()
```
?

2020-05-23 21:55 UTC, strega-nil commented on ports/libvpx/portfile.cmake
> +    else()
Here should be `elseif(VCPKG_TARGET_IS_OSX)`, in case someone is building on freeBSD

2020-05-23 21:55 UTC, strega-nil commented on ports/libvpx/portfile.cmake
> +    if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
```suggestion
    if(VCPKG_TARGET_IS_LINUX)
```

2020-05-23 21:58 UTC, strega-nil requested changes
You should probably also do:

```cmake
    set(LIBVPX_TARGET "--target=...")
```

and then instead of passing `--target=${LIBVPX_TARGET}`, pass `${LIBVPX_TARGET}` so that on, say, FreeBSD, it still builds.

2020-05-24 09:34 UTC, kafeg commented on ports/libvpx/portfile.cmake
> +    if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
I followed up exists style of this part above:

> VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore"

2020-05-24 09:34 UTC, kafeg commented on ports/libvpx/portfile.cmake
> +    else()
ok!

2020-05-24 09:35 UTC, kafeg commented on ports/libvpx/portfile.cmake
> +        set(LIBVPX_TARGET_ARCH "x86_64")
Done, thanks!

2020-05-26 05:41 UTC, JackBoosY approved these changes

2020-05-26 11:00 UTC, kafeg commented
> You should probably also do:
> 
> ```cmake
>     set(LIBVPX_TARGET "--target=...")
> ```
> 
> and then instead of passing `--target=${LIBVPX_TARGET}`, pass `${LIBVPX_TARGET}` so that on, say, FreeBSD, it still builds.

Hey! I did it by another way, by set `set(LIBVPX_TARGET "generic-gnu") # use default target`

2020-05-26 21:05 UTC, strega-nil commented
Alright, cool, I'm happy with that. Thanks @kafeg :)

2020-05-26 21:05 UTC, merged

2020-05-28 07:39 UTC, Baselfawwaz commented
<html><body>bupgmobaile.com</html>