[mpg123] Allow cross-compiling, fix previous builds tainting rebuilds
microsoft/vcpkg pull request #11535
Opened 2020-05-23 06:25 UTC by kevinlul

Closes #11164 

This would support cross-compiling to triplets like `arm64-linux` from x64 if an appropriate cross-compiling configuration or toolchain file is specified in the triplet.

I fixed a bug where previous builds were not cleaned up when building again. This came up when testing and I commented it; this could be separated into a different pull request.

I refactored the port a little bit to have common configure flags shared between debug and release builds; again, this could be in a different pull request.

Now for the meat of the problem I'm trying to solve: in the linked issue, JackBoosY suggests using the new `vcpkg_configure_make`. However, I found that this actually sets a bad combination of default flags for mpg123, resulting in attempting to macOS-specific CoreAudio code on Linux. I also noticed that it only attempts to detect autoconf `--host` if on Windows/MSYS, so I went with my own approach here of retrieving the prefix with `-dumpmachine` and passing it to configure and make.

2020-05-25 05:26 UTC, JackBoosY commented
@Neumann-A Could you review this PR?

Thanks.

2020-05-25 12:07 UTC, Neumann-A commented
The port needs a complete rewrite to use `vcpkg_configure_make()` and `vcpkg_install_make()`
a) use `SET(ENV{CC} <somecompiler>)` in the triplet or have it already be set in the environment which vcpkg uses. `vcpkg_configure_make` should automatically pick it up. (or more precisely configure should pick it up under linux)
b) (unreleated to the pr) the prefix passed to configure is completely wrong. Using vcpkg_configure_make() would solve part of that.
c) about the `--host` option VCPKG is currently missing a proper way to pass `--build=something --target=something --host=something` to configure. Even though it is currently not handled for linux in `vcpkg_configure_make` you can always use `OPTIONS` to pass these. I am thinking of adding something like `VCPKG_(AUTOTOOLS_)CONFIGURE_(MAKE_)TRIPLET` which is intended to be set be the users to specify `--build=something --target=something --host=something` in a custom triplet. I am still missing a proper name for that variable. 

Conclusion:
a) Rewrite port to use `vcpkg_configure_make()` and `vcpkg_install_make()`
b) add a global variable to `vcpkg_configure_make` to specify `--build=something --target=something --host=something` which can be used for cross-compiling cases in custom triplets. (Because it should affect all autotools based ports. )

2020-05-25 14:28 UTC, kevinlul commented
The default set of flags used by `vcpkg_configure_make` cause the build to fail. I tried to use it but as I noted, `I found that this actually sets a bad combination of default flags for mpg123, resulting in attempting to macOS-specific CoreAudio code on Linux.`

2020-05-25 15:09 UTC, Neumann-A commented
>I found that this actually sets a bad combination of default flags for mpg123, resulting in attempting to macOS-specific CoreAudio code on Linux.

Be more specific. If this is only due to `--host` this can be changed in `vcpkg_configure_make` as mentioned in my comment before

2020-05-25 15:13 UTC, kevinlul commented
When I had tested, it seemed to be the result of the combination of `--disable-silent-rules` with `--disable-shared` added [here](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_make.cmake#L260)

2020-05-25 15:47 UTC, Neumann-A commented
> When I had tested, it seemed to be the result of the combination of --disable-silent-rules with --disable-shared added here

Test again. The configure script has both rules baked into it so it should work.... (Otherwise check your autoconf version 2.69 is required)

2020-06-13 05:31 UTC, kevinlul commented
By removing a bunch of flags, I got it to compile properly. Tomorrow I will verify that this is still working on macOS. This has a behaviour change: `libmpg123.la` and `libout123.la` are now installed to lib directories. Should these be removed?

Some thoughts:
- the `make distclean` could be moved to `vcpkg_configure_make` because it seems like it could affect other ports that have in-source builds too
- setting the `--host` triplet via `-dumpmachine` could also be moved to `vcpkg_configure_make` so more autoconf ports can be easily cross-compiled with vcpkg

2020-06-13 14:45 UTC, kevinlul commented
I've verified that it compiles successfully on macOS, including the CoreAudio module.

2020-06-15 02:44 UTC, JackBoosY requested changes

2020-06-15 02:44 UTC, JackBoosY commented on ports/mpg123/portfile.cmake
>  elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
```suggestion
elseif(VCPKG_TARGET_IS_OSX OR VCPKG_TARGET_IS_LINUX)
```

2020-06-15 02:44 UTC, JackBoosY commented on ports/mpg123/portfile.cmake
> +        execute_process(
Please use `vcpkg_execute_required_process` instead.

2020-06-15 15:06 UTC, kevinlul commented on ports/mpg123/portfile.cmake
> +        execute_process(
I'm depending on reading the output directly via `OUTPUT_VARIABLE`. If I use `vcpkg_execute_required_process`, I will have to output to file and then read that file. Is this correct?

2020-06-16 02:03 UTC, JackBoosY commented on ports/mpg123/portfile.cmake
> +        execute_process(
@kevinlul Yes, you can have a try.

2020-06-17 02:50 UTC, JackBoosY requested changes
Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-06-17 02:50 UTC, JackBoosY requested changes

2020-06-17 02:50 UTC, JackBoosY commented on ports/mpg123/portfile.cmake
> +        message(STATUS "Cross-compiling with ${CMAKE_C_COMPILER}")
Should we remove these debug info?

2020-06-17 03:30 UTC, kevinlul commented on ports/mpg123/portfile.cmake
> +        message(STATUS "Cross-compiling with ${CMAKE_C_COMPILER}")
I feel it's important and useful to know that it is actually cross-compiling, but that might stem from my several fails while developing this that invoked the default compiler instead of the specified compiler. Here is what the vcpkg output looks like. If this doesn't conform to vcpkg standards then I will remove the messages.

```
$ ./vcpkg install mpg123 mpg123:arm64-linux
Computing installation plan...
The following packages will be built and installed:
    mpg123[core]:arm64-linux
    mpg123[core]:x64-linux
Starting package 1/2: mpg123:arm64-linux
Building package mpg123[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/debian/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached /home/debian/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Using source at /home/debian/vcpkg/buildtrees/mpg123/src/mpg123-1-0aae5f9fd8
-- Cross-compiling with /usr/bin/aarch64-linux-gnu-gcc
-- Detected autoconf triplet --host=aarch64-linux-gnu

-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-rel
-- Building arm64-linux-dbg
-- Building arm64-linux-rel
-- Installing arm64-linux-dbg
-- Installing arm64-linux-rel
-- Installing: /home/debian/vcpkg/packages/mpg123_arm64-linux/share/mpg123/copyright
-- Installing done
-- Performing post-build validation
-- Performing post-build validation done
Building package mpg123[core]:arm64-linux... done
Installing package mpg123[core]:arm64-linux...
Installing package mpg123[core]:arm64-linux... done
Elapsed time for package mpg123:arm64-linux: 1.863 min
Starting package 2/2: mpg123:x64-linux
Building package mpg123[core]:x64-linux...
-- Using cached /home/debian/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Using source at /home/debian/vcpkg/buildtrees/mpg123/src/mpg123-1-0aae5f9fd8
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-dbg
-- Installing x64-linux-rel
-- Installing: /home/debian/vcpkg/packages/mpg123_x64-linux/share/mpg123/copyright
-- Installing done
-- Performing post-build validation
-- Performing post-build validation done
Building package mpg123[core]:x64-linux... done
Installing package mpg123[core]:x64-linux...
Installing package mpg123[core]:x64-linux... done
Elapsed time for package mpg123:x64-linux: 1.706 min

Total elapsed time: 3.571 min

``

2020-06-17 05:40 UTC, JackBoosY approved these changes

2020-07-13 20:53 UTC, ras0219-msft approved these changes
LGTM if the merge from master doesn't break anything.

2020-07-13 20:53 UTC, ras0219-msft commented on ports/mpg123/portfile.cmake
> +        vcpkg_execute_required_process(
We typically don't trust the build script to be clean and prefer just nuking and re-extracting the entire source tree if the buildsystem requires in-source builds.

2020-07-13 21:58 UTC, kevinlul commented on ports/mpg123/portfile.cmake
> +        vcpkg_execute_required_process(
So some form of `file(REMOVE_RECURSE ${SOURCE_PATH})`. Do you know of another port that does in-source builds?

2020-07-17 05:43 UTC, kevinlul commented
Turns out all those lines were unnecessary holdovers from the old version of this port and it's all taken care of by `vcpkg_configure_make` and `vcpkg_install_make`. Nifty!

2020-07-28 21:00 UTC, strega-nil commented
/azp run

2020-07-28 21:01 UTC, strega-nil commented
I like this PR quite a lot! let's just run the PR tests and see if we can merge :)

2020-07-30 01:59 UTC, JackBoosY commented
```
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:377 (message):
  Could not find yasm.  Please install it via your package manager:

      brew install yasm
Call Stack (most recent call first):
  ports/mpg123/portfile.cmake:39 (vcpkg_find_acquire_program)
  scripts/ports.cmake:79 (include)


Error: Building package mpg123:x64-osx failed with: BUILD_FAILED
Elapsed time for package mpg123:x64-osx: 1.314 s
```

2020-07-30 02:01 UTC, strega-nil commented
Looks like this needs to update the scripts.

2020-07-30 02:39 UTC, JackBoosY approved these changes

2020-07-30 02:43 UTC, JackBoosY commented
I don't think mpg123 should use yasm in *nix, please change
```
vcpkg_find_acquire_program(YASM)
get_filename_component(YASM_EXE_PATH ${YASM} DIRECTORY)
set(ENV{PATH} "$ENV{PATH};${YASM_EXE_PATH}")
```
to 
```
if (VCPKG_TARGET_IS_WINDOWS)
    vcpkg_find_acquire_program(YASM)
    get_filename_component(YASM_EXE_PATH ${YASM} DIRECTORY)
    set(ENV{PATH} "$ENV{PATH};${YASM_EXE_PATH}")
endif()

2020-07-31 03:32 UTC, kevinlul commented
The assembler is used on all platforms if it is available. On my macOS CI I have to `brew install yasm` before installing mpg123. Turning that off would mean that we are not using the hand-optimized assembly on those platforms.

2020-08-01 20:56 UTC, merged