ignition-msgs5: Add support for cross-compilation
microsoft/vcpkg pull request #11538
Opened 2020-05-23 10:42 UTC by traversaro

- What does your PR fix? 
  This PR enables compilation of the `ignition-msgs5` port on triplet that require compilation, i.e. among official supported triplets `arm64-windows` and `arm-uwp` . 

- Which triplets are supported/not supported? Have you updated the CI baseline?
This PR add support for compiling `ignition-msgs5` for `arm64-windows` and `arm-uwp`, but I did not updated the CI baseline as the port will fail if  `ignition-msgs5:x86-windows` is not installed, and I do not know how this is supposed to be handled at the CI baseline level.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

This PR also required some changes in the `protobuf` ( https://github.com/microsoft/vcpkg/commit/fd8143bb1753b7c14473618f2f084dbdd151d450 ) and `ignition-modularscripts` (https://github.com/microsoft/vcpkg/commit/1e6f115faec2fef68192c761ce26db48dba83e7d) ports, feel free to check the commit messages for more details on those changes.

2020-05-25 08:55 UTC, NancyLi1013 requested changes

2020-05-25 08:55 UTC, NancyLi1013 commented on ports/ignition-modularscripts/CONTROL
> +Version: 2020-05-23
Is this a new version update for the port?

2020-05-25 08:55 UTC, NancyLi1013 commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
If the port has supported `arm `and `uwp`, we might also need to update ci.baseline.txt.

2020-05-25 12:57 UTC, traversaro commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
As mentioned in the PR body: 
> This PR add support for compiling `ignition-msgs5` for `arm64-windows` and `arm-uwp`, but I did not updated the CI baseline as the port will fail if  `ignition-msgs5:x86-windows` is not installed, and I do not know how this is supposed to be handled at the CI baseline level.

2020-05-25 12:58 UTC, traversaro commented on ports/ignition-modularscripts/CONTROL
> +Version: 2020-05-23
This port is only composed by code stored inside vcpkg, so it simply update this version number every time we edit it.

2020-05-26 01:54 UTC, NancyLi1013 commented on ports/ignition-modularscripts/CONTROL
> +Version: 2020-05-23
If the source is not updated, why don't use `2020-05- 09-1` instead of `2020-05- 23 `?

2020-05-26 06:30 UTC, NancyLi1013 commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
If `arm `or `uwp `depends on x86-windows to build, we might add some messages like this https://github.com/microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L21

As for baseline, we will try to solve it. We have opened a PR #11545 to solve this similar issues.

2020-05-26 06:45 UTC, traversaro commented on ports/ignition-modularscripts/CONTROL
> +Version: 2020-05-23
The `ignition-modularscripts` port there is no external "source", as for other similar ports in vcpkg, such [`boost-modular-build-helper`](https://github.com/microsoft/vcpkg/tree/master/ports/boost-modular-build-helper) and before it was removed `qt5-modularscripts`). For this reason, it would not make a lot of sense to bump the revision rather then the actual version number, and for this reason what we do in every PR that touch this port we just bump the version number, see https://github.com/microsoft/vcpkg/commits/master/ports/ignition-modularscripts/CONTROL .

2020-05-26 06:46 UTC, traversaro commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
> If `arm `or `uwp `depends on x86-windows to build, we might add some messages like this https://github.com/microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L21

The messages are already in the port, see https://github.com/microsoft/vcpkg/pull/11538/files#diff-42114ca08bb5dfacf810e3180a6fb3cbR29 .

2020-05-26 07:08 UTC, NancyLi1013 commented on ports/ignition-modularscripts/CONTROL
> +Version: 2020-05-23
Thanks for your so detailed description about this.

2020-05-26 07:10 UTC, NancyLi1013 commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
In this case, we can update the baseline now. Sorry, I didn't notice this info before.

2020-05-26 07:13 UTC, traversaro commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
Just to understand, how does the CI knows that `ignition-msgs5:x86-windows`  is a dependency for  `ignition-msgs5:arm64-windows` or  `ignition-msgs5:arm-uwp` ?

2020-05-26 07:23 UTC, NancyLi1013 commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
We will preinstall x86-windows on CI machine. So don't need to know the specific dependency.
You can refer to #11545 to learn more about this.

2020-05-26 07:24 UTC, traversaro commented on ports/ignition-msgs5/CONTROL
> +Supports: !(linux)
Great, thanks!

2020-05-26 10:12 UTC, NancyLi1013 approved these changes

2020-05-26 10:25 UTC, NancyLi1013 commented
I will test the features later. Once finished, I will update the results.

2020-05-27 06:11 UTC, NancyLi1013 commented
The feature has passed with the following triplets:

- x86-windows
- x64-windows
- x64-windows-static

2020-06-05 19:25 UTC, dan-shaw approved these changes

2020-06-05 19:25 UTC, dan-shaw commented
@traversaro I just merged a protobuf PR, could you resolve the conflicts?

2020-06-06 07:01 UTC, traversaro commented
> 
> 
> @traversaro I just merged a protobuf PR, could you resolve the conflicts?

Done.

2020-06-06 07:57 UTC, traversaro commented
`x86_windows` and `x64_osx` faiures seems to be unrelated, while the `arm64-windows` fails with the following message: 
~~~
CMake Error at ports/ignition-msgs5/portfile.cmake:29 (message):
  Cross-targetting ignition-msgs5 requires the x86-windows ignition-msgs5 to
  be available.  Please install ignition-msgs5:x86-windows first.
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)
~~~
That from https://github.com/microsoft/vcpkg/pull/11538#discussion_r430206281 it should be something that instead should be installed in the CI machines.

2020-06-11 09:01 UTC, NancyLi1013 commented
@traversaro 
Could you please resolve the conflicts?

2020-06-11 14:23 UTC, traversaro commented
> 
> 
> @traversaro
> Could you please resolve the conflicts?

Done.

2020-06-11 15:13 UTC, traversaro commented
The `arm64-windows` failure is due to: 
> CMake Error at ports/ignition-msgs5/portfile.cmake:29 (message):
  Cross-targetting ignition-msgs5 requires the x86-windows ignition-msgs5 to
  be available.  Please install ignition-msgs5:x86-windows first.
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)

Based on https://github.com/microsoft/vcpkg/pull/11538#discussion_r430206281 , this should be something installed in the CI machines.

2020-06-15 09:20 UTC, NancyLi1013 commented
@traversaro 
The regression on x64-osx should be fixed in this PR #11616.
```
CMake Error in src/CMakeLists.txt:
  Imported target "TINYXML2::TINYXML2" includes non-existent path

    "/Volumes/data/work/1/s/packages/tinyxml2_x64-osx/debug/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
Could you please merge the latest commit on master to this PR?

2020-06-15 21:33 UTC, traversaro commented
> Could you please merge the latest commit on master to this PR?

Done.

2020-06-16 03:02 UTC, NancyLi1013 commented
Seems it doesn't work. I noticed that this was the same reason with #11616. Could you look into this again?

2020-06-16 06:21 UTC, traversaro commented
> 
> 
> Seems it doesn't work. I noticed that this was the same reason with #11616. Could you look into this again?

I remember that at some point https://github.com/microsoft/vcpkg/pull/11616 contained the fixes for https://github.com/microsoft/vcpkg/issues/10039, but I can't find any reference to those in the final merged version (for example there  is no `vcpkg_fixup_pkgconfig` call). I am not sure what happened, possibly @orudge has some insights.

2020-06-16 08:14 UTC, orudge commented
> I remember that at some point #11616 contained the fixes for #10039, but I can't find any reference to those in the final merged version (for example there is no `vcpkg_fixup_pkgconfig` call). I am not sure what happened, possibly @orudge has some insights.

Good question, I'm not too sure. My local branch shows the commit pushed to orudge/vcpkg but somehow it's gone missing!

I've made a new PR (https://github.com/microsoft/vcpkg/pull/11966) with the fix.

2020-07-04 12:55 UTC, traversaro commented
The PR has been rebased on the top of the latest master, in particular fixing the conflicts with https://github.com/microsoft/vcpkg/pull/11275 .

2020-07-04 13:15 UTC, traversaro commented
The `arm64-windows` job is failing with error:
~~~
CMake Error at ports/ignition-msgs5/portfile.cmake:29 (message):
  Cross-targetting ignition-msgs5 requires the x86-windows ignition-msgs5 to
  be available.  Please install ignition-msgs5:x86-windows first.
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)
~~~
So it seems that `ignition-msgs5` is not installed for x86-windows as it was discussed in https://github.com/microsoft/vcpkg/pull/11538#discussion_r430206281 .

2020-07-06 06:57 UTC, NancyLi1013 commented
/azp run

2020-07-07 02:36 UTC, NancyLi1013 commented
@traversaro 
Could you please resolve the conflicts?

2020-07-10 18:40 UTC, traversaro commented
> 
> 
> @traversaro
> Could you please resolve the conflicts?

Hi @NancyLi1013,  I should have fixed all conflicts.

2020-07-12 13:39 UTC, traversaro commented
CI is failing with messages like: 
~~~
Convert-Path : Cannot find path 'C:\agent\_work\1\a\xml-results\x64-uwp.xml' because it does not exist.
At C:\agent\_work\1\s\scripts\azure-pipelines\analyze-test-results.ps1:424 char:42
~~~
at the first glance they do not seems to be related to the PR.

2020-07-16 02:45 UTC, NancyLi1013 commented
/azp run

2020-07-16 07:47 UTC, NancyLi1013 commented
It seems the command `/azp run` doesn't work.

@traversaro 
Could you please merge master to retrigger this PR?

2020-07-18 13:57 UTC, traversaro commented
> 
> 
> It seems the command `/azp run` doesn't work.
> 
> @traversaro
> Could you please merge master to retrigger this PR?

I rebased the PR on the top of latest master.

2020-07-20 02:50 UTC, JackBoosY requested changes

2020-07-20 02:50 UTC, JackBoosY commented on ports/protobuf/CONTROL
>  Description: Protocol Buffers - Google's data interchange format
```suggestion
Description: Protocol Buffers - Google's data interchange format

```

2020-08-01 09:57 UTC, traversaro commented
Sorry @JackBoosY, I had missed you request change. However, I solved the conflicts w.r.t. to the latest master.

2020-08-03 02:42 UTC, JackBoosY commented
Sorry for late, I lost track with this PR.
These changes caused protobuf build failure on uwp triplet, could you fix it?
```
     6>D:\buildtrees\protobuf\src\dfb7589f92-61fbc4fa5f.clean\src\google\protobuf\compiler\subprocess.cc(104,46): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier [D:\buildtrees\protobuf\arm-uwp-dbg\libprotoc.vcxproj]
     6>D:\buildtrees\protobuf\src\dfb7589f92-61fbc4fa5f.clean\src\google\protobuf\compiler\subprocess.cc(105,29): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier [D:\buildtrees\protobuf\arm-uwp-dbg\libprotoc.vcxproj]
     6>D:\buildtrees\protobuf\src\dfb7589f92-61fbc4fa5f.clean\src\google\protobuf\compiler\subprocess.cc(109,48): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier [D:\buildtrees\protobuf\arm-uwp-dbg\libprotoc.vcxproj]
     6>D:\buildtrees\protobuf\src\dfb7589f92-61fbc4fa5f.clean\src\google\protobuf\compiler\subprocess.cc(110,29): error C2065: 'HANDLE_FLAG_INHERIT': undeclared identifier [D:\buildtrees\protobuf\arm-uwp-dbg\libprotoc.vcxproj]
     6>D:\buildtrees\protobuf\src\dfb7589f92-61fbc4fa5f.clean\src\google\protobuf\compiler\subprocess.cc(119,26): error C2065: 'STARTF_USESTDHANDLES': undeclared identifier [D:\buildtrees\protobuf\arm-uwp-dbg\libprotoc.vcxproj]
```

2020-08-14 08:26 UTC, NancyLi1013 commented
@traversaro 
Could you please also resolve the conflicts?

2020-09-05 09:18 UTC, traversaro commented
> 
> 
> @traversaro
> Could you please also resolve the conflicts?

Hi @NancyLi1013 , the conflicts have been solved. @JackBoosY let's see if the uwp failure are still there, probably there is some upstream protobuf regression regarding compilation of the libprotoc library on uwp.

2020-09-05 10:33 UTC, traversaro commented
There are several failures, but they do not seems to be related to this PR.

2020-09-07 02:25 UTC, NancyLi1013 commented
/azp run

2020-09-07 03:49 UTC, BillyONeal commented
The failures in CI are consistent with a malformed CONTROL file somewhere and they aren't happening outside of this PR. Just in case I pushed a merge with master, we'll see what comes back.

2020-10-09 08:10 UTC, JackBoosY commented
/azp run

2020-10-26 06:29 UTC, JackBoosY commented
@BillyONeal Any progress?

2020-10-31 10:55 UTC, traversaro commented
> 
> 
> @BillyONeal Any progress?

The failure on this are due to a regression in protobuf, that does not support anymore in the latest version compilation in uwp . 
As they are already some active PR in the direction of getting protobuf to correctly cross compile (see https://github.com/microsoft/vcpkg/pull/14165), let's try to see if those PR before starting to work again on this one.

2020-10-31 10:55 UTC, closed without merging

2021-01-02 23:16 UTC, traversaro commented
Related PR: https://github.com/microsoft/vcpkg/pull/15424 .