[vcpkg/scripts/pkgconfig] rewrite pkg-config check for libraries.
microsoft/vcpkg pull request #11550
Opened 2020-05-24 17:01 UTC by Neumann-A

closes #11103

- [ ] Testing with X windows PR

2020-05-25 05:30 UTC, JackBoosY commented
Maybe we should choose one port to test this PR?

2020-05-26 05:33 UTC, JackBoosY requested changes

2020-05-26 05:33 UTC, JackBoosY commented on ports/x264/portfile.cmake
> +vcpkg_fail_port_install(ON_TARGET "OSX")
Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-05-27 20:57 UTC, Neumann-A commented
@JackBoosY: osx has no pkg-config installed?

2020-05-28 02:22 UTC, JackBoosY commented
Yes, please install `brew install pkgconfig` here:
https://github.com/microsoft/vcpkg/blob/d9b4acf02d8c784927f89d23edb677408ec428af/scripts/azure-pipelines/osx/azure-pipelines.yml#L25

2020-05-28 11:38 UTC, Neumann-A commented
@JackBoosY: Done

2020-05-29 02:34 UTC, JackBoosY approved these changes

2020-05-29 02:36 UTC, JackBoosY commented
Looks good in my side.

2020-05-29 20:47 UTC, Neumann-A commented
@JackBoosY: Sorry for adding more but I found a few flaws by running the x window pr a bit further. I also added a few *.pc files to basic ports for simple testing.

2020-05-30 01:55 UTC, BillyONeal commented
No changes to vm provisioning scripts here, dropping vm-update-request.

2020-05-30 05:32 UTC, Neumann-A commented
Hmm osx ci is not finding pkg-config again although the brew script claims it has been installed. Don't know what to do about that. Except for th fltk regression which seems to be an error in the baseline the rest are download errors.

2020-06-03 05:28 UTC, JackBoosY commented
Looks good now.

2020-06-09 06:00 UTC, JackBoosY commented
/azp run

2020-06-12 05:39 UTC, JackBoosY commented
Can you merge the latest changes into this branch?

2020-06-28 07:11 UTC, JackBoosY commented
Coud you resolve these file conflicts?

2020-06-28 09:37 UTC, JackBoosY commented
@BillyONeal This PR is important, we need to merge this first.

2020-06-29 20:23 UTC, BillyONeal approved these changes

2020-06-30 08:39 UTC, JackBoosY commented
```
Building package libpng[core]:x64-osx...
...
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: /Users/vagrant/Data/packages/libpng_x64-osx/lib/pkgconfig/libpng.pc
-- Checking file: /Users/vagrant/Data/packages/libpng_x64-osx/lib/pkgconfig/libpng16.pc
-- CHECK_LIB_m:CHECK_LIB_m-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:217 (message):
  Library "m" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:285 (vcpkg_fixup_pkgconfig_check_files)
  ports/libpng/portfile.cmake:117 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:73 (include)


Error: Building package libpng:x64-osx failed with: BUILD_FAILED
Elapsed time for package libpng:x64-osx: 8.888 s
```

Could you fix it?

Thanks.

2020-06-30 09:50 UTC, Neumann-A commented
> Could you fix it?

Done. CI is testing the rest currently. Hopefully there is not more work to be done ;)

2020-07-01 15:04 UTC, Neumann-A commented
@JackBoosY: Please rerun CI for libpq:x86 and libnice. The libnice failure is probably unrelated the libpq:x86 error is just a download failure for winflexbison

2020-07-06 16:07 UTC, Neumann-A commented
@JackBoosY: needs a CI retrigger. Download errors in CI. Can this get merged any time soon?

2020-07-07 01:50 UTC, JackBoosY commented
@ras0219  @ras0219-msft Could you merge this PR first?

2020-07-07 22:50 UTC, ras0219-msft commented
I'm going to try to merge https://github.com/microsoft/vcpkg/pull/12254 before this PR, which will ensure all consumers are re-tested.

2020-07-13 20:44 UTC, ras0219-msft commented
/azp run

since #12254 is merged

2020-07-13 20:44 UTC, ras0219-msft commented
/azp run

2020-07-14 05:47 UTC, Neumann-A commented
currently checking why there is no regression in zstd. according to #12407 there should be a regression

2020-07-16 12:20 UTC, Neumann-A commented
@ras0219-msft: Should have 561287c trigger a full rebuild after 5ccacd4?

Please rerun failing CIs. This PR should be green now.

2020-07-16 22:48 UTC, BillyONeal commented
@Neumann-A Easiest way to force that is to push a merge with master; in this case there are merge conflicts

2020-07-17 07:11 UTC, Neumann-A commented
The ompl:x86-windows regressions seems unrelated. Worked locally and error in CI is:
```
CMake Error at tests/CMakeLists.txt:16 (configure_file):
  configure_file Problem configuring file
```

2020-07-21 06:19 UTC, JackBoosY commented
@ras0219-msft @ras0219 ping for merge this PR.

2020-07-24 18:39 UTC, merged

2020-07-24 18:41 UTC, ras0219-msft commented
LGTM, thanks @Neumann-A for the continued awesome work on this!

I think that it will eventually make sense to move the "checking" parts of this into the vcpkg tool itself, to ensure it is always run on any `.pc` files left in the tree, but this is great for now.