Bump luafilesytem to 1.8.0 and lpeg to 1.0.2
microsoft/vcpkg pull request #11554
Opened 2020-05-25 02:22 UTC by TheCycoONE

**Describe the pull request**
Bump versions of luafilesystem and lpeg to the latest available

2020-05-25 05:42 UTC, LilyWangL requested changes

2020-05-25 05:42 UTC, LilyWangL commented on ports/lpeg/portfile.cmake
>  include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-05-25 05:42 UTC, LilyWangL commented on ports/luafilesystem/portfile.cmake
>  include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-05-25 05:42 UTC, LilyWangL commented on ports/luafilesystem/portfile.cmake
>  file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-05-25 12:20 UTC, TheCycoONE commented
Pushed the requested changes. Thanks @LilyWangL

2020-05-26 01:08 UTC, TheCycoONE commented
I've removed the windows only gates. That was left over from when vcpkg only supported windows, nothing about these packages should be Windows only.

2020-05-26 02:00 UTC, LilyWangL approved these changes

2020-05-27 04:32 UTC, merged