[sockpp] Add new port
microsoft/vcpkg pull request #11562
Opened 2020-05-25 11:15 UTC by thewisebro

**Describe the pull request**

- What does your PR fix? Fixes #10971

- Which triplets are supported/not supported? Have you updated the CI baseline? All triplets are supported. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2020-05-25 11:15 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11562) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11562) before we can accept your contribution.<br/><br/>:x: thewisebro [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11562)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=11562) it.</sub>

2020-05-25 18:53 UTC, BillyONeal commented
/azp run

2020-05-26 02:14 UTC, LilyWangL commented
Can you please add the following command in _scripts/ci.baseline.txt_?
```
sockpp:arm-uwp=fail
sockpp:x64-uwp=fail
```

2020-05-26 02:14 UTC, LilyWangL requested changes

2020-05-26 02:14 UTC, LilyWangL commented on ports/sockpp/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-05-26 02:14 UTC, LilyWangL commented on ports/sockpp/CONTROL
> +Description: Simple, modern, C++ socket library. This is a fairly low-level C++ wrapper around the Berkeley sockets library using socket, acceptor, and connector classes that are familiar concepts fr
Can you please add [Supports](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/docs/maintainers/control-files.md#supports) for this port in the CONTROL file?

2020-05-26 02:14 UTC, LilyWangL commented on ports/sockpp/portfile.cmake
> +file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-05-26 04:45 UTC, thewisebro commented on ports/sockpp/CONTROL
> +Description: Simple, modern, C++ socket library. This is a fairly low-level C++ wrapper around the Berkeley sockets library using socket, acceptor, and connector classes that are familiar concepts fr
Ack.

2020-05-26 04:47 UTC, thewisebro commented on ports/sockpp/portfile.cmake
> +include(vcpkg_common_functions)
Ack.

2020-05-26 04:48 UTC, thewisebro commented on ports/sockpp/portfile.cmake
> +file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
Ack.

2020-05-26 05:14 UTC, thewisebro commented
> Can you please add the following command in _scripts/ci.baseline.txt_?
> 
> ```
> sockpp:arm-uwp=fail
> sockpp:x64-uwp=fail
> ```

Updated _scripts/ci.baseline.txt_

2020-05-27 04:57 UTC, dan-shaw commented on ports/sockpp/sockppConfig.cmake
> +    list(APPEND SOCKPP_LIBRARIES ${_DIR}/lib/libsockpp.so)
It looks like this config doesn't support Windows, can you add that in `Supports` in the Control file.

2020-05-27 04:58 UTC, dan-shaw commented on ports/sockpp/usage
> +    target_link_libraries(main PRIVATE ${SOCKPP_LIBRARIES})
Usage instructions should be automatically generated.

2020-05-27 04:59 UTC, dan-shaw approved these changes

2020-05-27 05:50 UTC, thewisebro commented on ports/sockpp/sockppConfig.cmake
> +    list(APPEND SOCKPP_LIBRARIES ${_DIR}/lib/libsockpp.so)
This was an oversight. I've added support for Windows as well.

2020-05-27 05:50 UTC, thewisebro commented on ports/sockpp/usage
> +    target_link_libraries(main PRIVATE ${SOCKPP_LIBRARIES})
Sorry, but how to enable that? Its not being generated by default.

2020-06-02 02:10 UTC, merged