[telnetpp] Add missing <ostream> for Visual Studio 2019 16.6
microsoft/vcpkg pull request #11573
Opened 2020-05-25 22:29 UTC by BillyONeal

Previously submitted as https://patch-diff.githubusercontent.com/raw/KazDragon/telnetpp/pull/215

2020-05-26 10:23 UTC, PhoebeHui requested changes
Remove the comments for making the patch file smaller.

2020-05-26 10:23 UTC, PhoebeHui commented on ports/telnetpp/github-215.patch
> +Subject: [PATCH 1/2] Include <ostream> in variable.hpp
```suggestion
```

2020-05-26 10:23 UTC, PhoebeHui commented on ports/telnetpp/github-215.patch
> +Subject: [PATCH 2/2] Include <ostream> in variable.cpp
```suggestion
```

2020-05-27 01:51 UTC, BillyONeal commented
> Remove the comments for making the patch file smaller.

I put the comments there to make it identical to the GitHub PR commit so that it's clear once we take a version with that commit integrated that the patch can be removed.

2020-05-27 05:03 UTC, BillyONeal commented
/azp run

2020-05-27 05:05 UTC, BillyONeal commented
@PhoebeHui Looks like you removed the bits you didn't like yourself but you're still marked as requesting changes. Is there anything else you're looking for?

Thanks!

2020-05-27 05:39 UTC, PhoebeHui approved these changes
LGTM, thanks Billy!

2020-05-27 05:50 UTC, merged