fix to build nghttp2 statically.
microsoft/vcpkg pull request #11638
Opened 2020-05-28 17:13 UTC by thothothotho

**Describe the pull request**

- What does your PR fix? Fixes #

nghttp2 is always build dynamic.  nghttp2 uses non standard option to build the static library. see #11492. 
This PR honors whether the triplet is static or dynamic.

- Which triplets are supported/not supported? Have you updated the CI baseline?

I've only tested x64-linux

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I think so.

2020-05-28 17:13 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11638) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11638) before we can accept your contribution.<br/><br/>:x: thothothotho [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11638)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=11638) it.</sub>

2020-05-29 03:19 UTC, NancyLi1013 requested changes
Could you please also bump the version as `1.39.2-2` in `CONTROL `file?

2020-05-29 03:19 UTC, NancyLi1013 commented on ports/nghttp2/portfile.cmake
`include(vcpkg_common_functions)` is deprecated. Could you please remove this line?

2020-05-29 03:19 UTC, NancyLi1013 commented on ports/nghttp2/portfile.cmake
```suggestion

if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
    set(ENABLE_STATIC_LIB ON)
    set(ENABLE_SHARED_LIB OFF)
else()
    set(ENABLE_STATIC_LIB OFF)
    set(ENABLE_SHARED_LIB ON)
endif()
```
We just need to add these codes here.

Then add the following codes to OPTIONS in `vcpkg_configure_cmake()`.
```
-DENABLE_STATIC_LIB=${ENABLE_STATIC_LIB}
-DENABLE_SHARED_LIB=${ENABLE_SHARED_LIB}
```

2020-05-29 03:19 UTC, NancyLi1013 commented on ports/nghttp2/portfile.cmake
Could you please update this

`file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${LIB_NAME} RENAME copyright)`

as

`file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` ?

2020-05-29 08:13 UTC, thothothotho commented on ports/nghttp2/portfile.cmake
done

2020-05-29 09:45 UTC, NancyLi1013 approved these changes

2020-06-01 02:11 UTC, JackBoosY approved these changes

2020-06-01 22:59 UTC, merged