[ocilib] Fix build failure
microsoft/vcpkg pull request #11646
Opened 2020-05-29 09:16 UTC by JackBoosY

The target architecture in different sln is different.

Related: #11637.

2020-05-29 10:01 UTC, LilyWangL requested changes

2020-05-29 10:01 UTC, LilyWangL commented on ports/ocilib/portfile.cmake
>  		set(SOLUTION_TYPE vs2019)
```suggestion
set(SOLUTION_TYPE vs2019)
```

2020-05-29 10:03 UTC, LilyWangL requested changes

2020-05-29 10:03 UTC, LilyWangL commented on ports/ocilib/portfile.cmake
>  		set(SOLUTION_TYPE vs2017)
```suggestion
  set(SOLUTION_TYPE vs2017)
```

2020-05-29 10:03 UTC, LilyWangL requested changes

2020-05-29 10:03 UTC, LilyWangL commented on ports/ocilib/portfile.cmake
> +  set(SOLUTION_TYPE vs2017)
```suggestion
        set(SOLUTION_TYPE vs2017)
```

2020-05-29 10:04 UTC, LilyWangL requested changes

2020-05-29 10:04 UTC, LilyWangL commented on ports/ocilib/portfile.cmake
>  		set(SOLUTION_TYPE vs2015)
```suggestion
        set(SOLUTION_TYPE vs2015)
```

2020-05-29 10:05 UTC, LilyWangL approved these changes

2020-05-29 20:02 UTC, BillyONeal commented
This passes locally for me, what drove this change?

2020-06-01 02:50 UTC, JackBoosY commented
@BillyONeal This is indeed a port bug, it seems that the pipeline did not catch this error correctly.

2020-06-02 00:52 UTC, merged

2020-06-02 05:54 UTC, BillyONeal commented
@JackBoosY I believe that it is a port bug, but it passes in CI and it passed for me locally, so I was hoping to have a more concrete analysis on why. Oh well, no problem, merged now :)