[threadpool] Add new port
microsoft/vcpkg pull request #11650
Opened 2020-05-29 13:20 UTC by jesseschalken

Adds a port for the [threadpool](http://threadpool.sourceforge.net/) library.

Fixes #9735

2020-05-29 13:21 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11650) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11650) before we can accept your contribution.<br/><br/>:x: jesseschalken [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11650)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=11650) it.</sub>

2020-05-29 13:45 UTC, jesseschalken commented
What is the actual failure from CI? The only information it says is:

```
|x86-windows|result|features|notes
|-----------|----|--------|-----
|threadpool |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'threadpool:x86-windows=fail'

The following build failures were ignored: openmama x264 3fd

Uncompressing archives\fail\3d\3d131b502c7b4949811c898bbc27864ce567f359.zip to C:\agent\_work\1\a\failureLogs\x86-windows\
##[error]REGRESSION: threadpool:x86-windows. If expected, add threadpool:x86-windows=fail to C:\agent\_work\1\s\scripts\ci.baseline.txt.
##[section]Finishing: Analyze results and prepare test logs
```

But what is the actual failure? It doesn't say.

I've tried using this library on the `x86-windows` triplet and it works fine.

2020-05-29 17:47 UTC, Neumann-A commented
```
-- Downloading https://downloads.sourceforge.net/project/threadpool/threadpool/0.2.5%20%28Stable%29/threadpool-0_2_5-src.zip...
-- Downloading https://downloads.sourceforge.net/project/threadpool/threadpool/0.2.5%20%28Stable%29/threadpool-0_2_5-src.zip... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/threadpool/portfile.cmake:2 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)
```

2020-05-29 17:58 UTC, Neumann-A commented
Probably should print a warning that the this implementation is not NUMA aware ;) and will only support <64 physical cores on windows

2020-05-29 18:07 UTC, jesseschalken commented
@Neumann-A Thanks. I force pushed an identical commit to retrigger the CI because I thought it might be an intermittent network failure.

And still, the file downloads fine for all the triplets except `x86-windows`. It's literally the same URL. I don't understand how that's possible.

The file downloads fine here via the browser and via `vcpkg install threadpool --triplet x86-windows`.

How do I even debug this?

2020-06-01 02:13 UTC, NancyLi1013 requested changes
Is this a header-only library? It seems just some headers are added.

2020-06-01 02:13 UTC, NancyLi1013 commented on ports/threadpool/portfile.cmake
> +    DESTINATION ${CURRENT_PACKAGES_DIR}/share/threadpool
```suggestion
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}
```
Could you please update as the review suggestion?

2020-06-01 11:11 UTC, jesseschalken commented
@NancyLi1013  Yep, this library is header-only.

2020-06-03 17:51 UTC, jesseschalken commented
So how do I mark the requested review changes as accepted and remove the `requires:author-response` label?

2020-06-04 01:51 UTC, NancyLi1013 requested changes

2020-06-04 01:51 UTC, NancyLi1013 commented on ports/threadpool/portfile.cmake
> +
```suggestion
# header-only library
```
Could you please add the comment here?

2020-06-04 01:54 UTC, NancyLi1013 commented
@jesseschalken 

Sorry for the late response.

The labels can only be removed by our team members. We will remove it if there are no any changes needed to be done.

2020-06-04 07:39 UTC, NancyLi1013 approved these changes

2020-06-04 14:21 UTC, jesseschalken commented
@NancyLi1013 Okay, thanks.

2020-06-09 05:54 UTC, NancyLi1013 commented
/azp run

2020-07-07 22:55 UTC, ras0219-msft approved these changes

2020-07-08 22:26 UTC, merged

2020-07-08 22:26 UTC, ras0219-msft commented
Thanks!

2020-07-10 11:06 UTC, jesseschalken commented
I don't need this anymore personally because the code that used this library turned out to be unreachable. 😣 Maybe someone else will find it useful though.