[MAPNIK] new port added
microsoft/vcpkg pull request #11656
Opened 2020-05-29 19:16 UTC by am2222

**Describe the pull request**

- What does your PR fix? Fixes #
Adds new port for mapnik https://github.com/microsoft/vcpkg/issues/7526
- Which triplets are supported/not supported? Have you updated the CI baseline?
```
mapnik:arm-uwp=fail
mapnik:x64-uwp=fail
 ```
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-06-02 10:00 UTC, NancyLi1013 requested changes

2020-06-02 10:00 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> +mapnik:x64-uwp=fail
Please put these two lines at the place that starts with `m` and keep the codes alphabetically.

2020-06-02 15:39 UTC, am2222 commented on ports/mapnik/portfile.cmake
> +set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/${PORT})
I had to pull the repository with `--recurse-submodules` which I think `vcpkg+from_github()` does not support it.

2020-06-02 15:39 UTC, am2222 commented on ports/mapnik/portfile.cmake
> +include(vcpkg_common_functions)
Done!

2020-06-02 15:58 UTC, am2222 commented on ports/mapnik/portfile.cmake
> +set(ENV{PATH} "$ENV{PATH};${PYTHON2_DIR}")
Done!

2020-06-02 15:59 UTC, am2222 commented on ports/mapnik/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/fonts/unifont_license.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/mapnik RENAME fonts_copyright)
Done!

2020-06-02 16:00 UTC, am2222 commented on scripts/ci.baseline.txt
> +mapnik:x64-uwp=fail
Done!

2020-06-05 02:10 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/${PORT})
Why do you need do this?

2020-06-05 02:11 UTC, NancyLi1013 commented
It seems the review suggestions are not been resolved yet.
Could you please check them again?

2020-06-05 06:10 UTC, am2222 commented
> It seems the review suggestions are not been resolved yet.
> Could you please check them again?

Hi, I had addressed them but I was trying to figure out the reason why it fails on `x64-windows` and `Linux` but I found out this error for Linux build.
https://github.com/microsoft/vcpkg/issues/11780
and on my machine `x64-windows` builds with no issues but I think here it fails.

2020-06-05 06:58 UTC, NancyLi1013 commented on ports/mapnik/CONTROL
> +Feature: WITH_CAIRO
The feature name is not updated.

2020-06-05 07:02 UTC, NancyLi1013 commented
OK. You can push them after you solved the failures. I will try to review this PR again when you have done all work for this PR.

2020-06-05 16:22 UTC, am2222 commented
Thanks. I pushed almost all of the changes. however still waiting for the results of the checks for x64-windows and linux.

2020-06-09 05:56 UTC, NancyLi1013 commented
@am2222 
Could you please resolve the conflicts?

2020-06-09 21:00 UTC, am2222 commented
@NancyLi1013 Thanks. I did not notice that conflict. I resolved it.

2020-06-09 22:54 UTC, am2222 commented on ports/mapnik/portfile.cmake
> +set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/${PORT})
I think now that I am fetching data from mapnik's repo this issue is also resolved.

2020-06-10 08:17 UTC, NancyLi1013 requested changes

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/CONTROL
> +Feature: CAIRO
```suggestion
Feature: cairo
```
Could you please update the feature name? We prefer to use lowercase here.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/CONTROL
> +Feature: PROJ4
The same as above.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +# endif()
Please remove these comments codes here if they are no longer needed.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +    PATCHES 0001-CMakeFiles.patch 0002-sqlitepixelwidth.patch
```suggestion
    PATCHES
        0001-CMakeFiles.patch 
        0002-sqlitepixelwidth.patch
```
Could you please update this?

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +message(STATUS "Adding worktree done")
```suggestion
```
This line seems to be unnecessary.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
```suggestion
```
Please remove this blank line.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +  # Keyword FEATURES is optional if INVERTED_FEATURES are not used
```suggestion
```
This comment should be removed here.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +    UTILS WITH_UTILS
Could you please update the feature names as lowercase and also in CONTROL file?

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
```suggestion
```
Please remove this blank line.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> + #    PREFER_NINJA # Disable this option if project cannot be built with Ninja
```suggestion
       PREFER_NINJA # Disable this option if project cannot be built with Ninja
```
Why do you comment this line out? Can this port not be built with Ninja? If so, please remove this line.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +#    NO_CHARSET_FLAG # automatic templates
```suggestion
```
This line seems to be not needed. Please remove it here.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
Please remove the extra blank lines.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
Please remove the extra blank lines.

2020-06-10 08:17 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
Please remove the extra blank lines.

2020-06-10 15:23 UTC, am2222 reviewed
comments are applied.

2020-06-11 05:50 UTC, NancyLi1013 commented
Could you please resolve the conflicts again?

2020-06-11 13:58 UTC, am2222 commented
> Could you please resolve the conflicts again?

Sure, thanks. I am trying to make a set of patches. I will push it soon. I found the reason why it is breaking on windows tests

2020-07-16 02:47 UTC, NancyLi1013 commented
Hi @am2222 
Could you please resolve the conflicts?

2020-07-16 02:58 UTC, NancyLi1013 requested changes

2020-07-16 02:58 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +      0002-sqlitepixelwidth.patch
```suggestion
    PATCHES
        0001-CMakeFiles.patch 
        0002-sqlitepixelwidth.patch
```

2020-07-16 02:58 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +set(BOOST_ROOT ${CURRENT_INSTALLED_DIR})
Why do we need to add `set(BOOST_ROOT ${CURRENT_INSTALLED_DIR})` here?

2020-07-16 02:58 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
```suggestion
```

2020-07-16 02:58 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +    	-DFREE_TYPE_INCLUDE=${CURRENT_INSTALLED_DIR}/include/freetype2
```suggestion
    PREFER_NINJA # Disable this option if project cannot be built with Ninja
    OPTIONS   
        ${FEATURE_OPTIONS}
        -DMAPNIK_STATIC_LIB=${MAPNIK_STATIC_LIB}
        -DBOOST_PREFIX=${CURRENT_INSTALLED_DIR}/include
        -DFREE_TYPE_INCLUDE=${CURRENT_INSTALLED_DIR}/include/freetype2
```

2020-07-16 03:04 UTC, am2222 commented
> Hi @am2222
> Could you please resolve the conflicts?

Hi @NancyLi1013 ,
Thanks for the comments, I will fix them ASAP, I have a deadline by the end of this month and after it I will finish this port, I had some difficulties with making patches and I had to learn how to make them for a package.
Thanks,
Majid

2020-08-04 08:29 UTC, NancyLi1013 commented
@am2222 
Sorry for the late response.
Please let me know if you need any any from us.

2020-08-05 00:34 UTC, am2222 commented
> @am2222
> Sorry for the late response.
> Please let me know if you need any any from us.

@NancyLi1013  Hi Nancy,
Thanks so much, Actually I had a question, I wanted to know if there is any tuturials for making patches for vcpkg packages? I am facing errors in making patches and they are mainly because of vcpkg is failing in applying patches.

2020-08-05 02:37 UTC, NancyLi1013 commented
You can refer to this [doc ](https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md).

Hope it can help you some.

Please don't hesitate to ask for help from us if we do can help you.

2020-08-14 08:25 UTC, NancyLi1013 commented
@am2222 
Could you please resolve the conflicts?

2020-08-14 16:56 UTC, am2222 commented
> @am2222
> Could you please resolve the conflicts?

Hello @NancyLi1013 
Yes I am working on it. will update it today

2020-08-16 02:52 UTC, am2222 commented on ports/mapnik/portfile.cmake
> +set(BOOST_ROOT ${CURRENT_INSTALLED_DIR})
It is extra. I am deleting it.

2020-08-17 02:20 UTC, NancyLi1013 commented
/azp run

2020-08-17 06:11 UTC, NancyLi1013 commented
The regressions on x64-windows and x64-windows-static are like this:

```
D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(115): error C2061: syntax error: identifier 'string'
D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(132): note: see reference to class template instantiation 'mapnik::box2d<T>' being compiled
D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(118): error C3646: 'to_string': unknown override specifier
D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(118): error C2059: syntax error: '('
D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(118): error C2238: unexpected token(s) preceding ';'
```
Could you please look into this?

2020-08-17 14:18 UTC, am2222 commented
> The regressions on x64-windows and x64-windows-static are like this:
> 
> ```
> D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(115): error C2061: syntax error: identifier 'string'
> D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(132): note: see reference to class template instantiation 'mapnik::box2d<T>' being compiled
> D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(118): error C3646: 'to_string': unknown override specifier
> D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(118): error C2059: syntax error: '('
> D:\buildtrees\mapnik\src\mapnik\include\mapnik/geometry/box2d.hpp(118): error C2238: unexpected token(s) preceding ';'
> ```
> 
> Could you please look into this?

@NancyLi1013  Hi,
Yeah sure I will fix it. I was looking for the link of log files to see the errors, but I have lost that link. Thanks

2020-08-27 23:34 UTC, am2222 commented
@NancyLi1013 Hi,
Sorry for my late reply. Is it possible to share me the full log files? Since I am still trying to find a solution for the errors and could not find any. The even don't happen on my machine with the vcpkg that I have.
Thanks

2020-08-28 01:48 UTC, NancyLi1013 commented
/azp run

2020-08-28 08:37 UTC, NancyLi1013 commented
It seems there are some problems on CI now. I will provide the latest log once it is normal.

2020-09-02 12:58 UTC, treigilbert commented
For x64-windows, vcpkg was giving a command parse error for install mapnik[proj4,input_shape]. I had to change all the input_* features to input-* in the CONTROL and portfile.cmake to allow install mapnik[proj4,input-shape].

For x64-windows using Visual Studio 16.7.5 for vcpkg to compile I had to:
Add #include <algorithm> in src\mapnik\include\mapnik\util\char_array_buffer.hpp
Add #include <string> in src\mapnik\include\mapnik\box2d.hpp

For linking errors from including mapnik headers in my code:
In src\mapnik\include\mapnik\enumeration.hpp disable the #ifdef _MCS_VER at line 278. This might be because I was using /Zc:preprocessor when compiling my code.

2020-09-02 19:07 UTC, am2222 commented
> For x64-windows, vcpkg was giving a command parse error for install mapnik[proj4,input_shape]. I had to change all the input_* features to input-* in the CONTROL and portfile.cmake to allow install mapnik[proj4,input-shape].
> 
> For x64-windows using Visual Studio 16.7.5 for vcpkg to compile I had to:
> Add `#include <algorithm>` in src\mapnik\include\mapnik\util\char_array_buffer.hpp
> Add `#include <string>` in src\mapnik\include\mapnik\box2d.hpp
> 
> For linking errors from including mapnik headers in my code:
> In src\mapnik\include\mapnik\enumeration.hpp disable the #ifdef _MCS_VER at line 278. This might be because I was using /Zc:preprocessor when compiling my code.

Thanks I will apply the changes you mentioned and will push request again. Thanks

2020-09-09 07:30 UTC, NancyLi1013 commented
@am2222 
Could you please resolve the conflicts?

2020-09-10 14:43 UTC, am2222 commented
@NancyLi1013 I think so far it does not work on the x64_linux,x64_osx,x86_windows,arm_uwp. I think there is an issue with one of the dependencies. Can I have the logs?

2020-09-11 03:14 UTC, NancyLi1013 requested changes

2020-09-11 03:14 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> -protozero:arm-uwp=fail
Why do you remove this line here? Seems this port is not related with this PR.

2020-09-11 08:41 UTC, NancyLi1013 commented
You can get the log here:
https://dev.azure.com/vcpkg/public/_build/results?buildId=42695&view=artifacts&type=publishedArtifacts

2020-09-13 22:21 UTC, am2222 commented on scripts/ci.baseline.txt
> -protozero:arm-uwp=fail
I did it by mistake.

2020-10-21 11:50 UTC, SNiLD commented
> For x64-windows, vcpkg was giving a command parse error for install mapnik[proj4,input_shape]. I had to change all the input_* features to input-* in the CONTROL and portfile.cmake to allow install mapnik[proj4,input-shape].

These changes are (still) needed. I also needed to add `boost-msm` to the dependencies.

I was building x64-windows with dependencies as static (however gdal, icu, boost-regex, libpq and openssl need to be dynamic).

2020-10-21 15:33 UTC, am2222 commented
> > For x64-windows, vcpkg was giving a command parse error for install mapnik[proj4,input_shape]. I had to change all the input_* features to input-* in the CONTROL and portfile.cmake to allow install mapnik[proj4,input-shape].
> 
> These changes are (still) needed. I also needed to add `boost-msm` to the dependencies.
> 
> I was building x64-windows with dependencies as static (however gdal, icu, boost-regex, libpq and openssl need to be dynamic).
> 
> After those changes the build was successfull though (haven't linked against it yet).

Are you working with latest version of mapnik? Since I could not make it work with the latest version

2020-10-22 12:40 UTC, SNiLD commented
> Are you working with latest version of mapnik? Since I could not make it work with the latest version

I'm using the version you have used in this pull request i.e.:
```
set(GIT_URL "https://github.com/am2222/mapnik-windows.git")
set(GIT_REV "cfa268fa6ab438568b9b5320f6fce4317f0e3d8e")
```

2020-10-22 20:38 UTC, am2222 commented
@SNiLD  Can you please let me know what other changes did you made that it worked? It works on my local machine but breaks here

2020-10-23 08:10 UTC, SNiLD commented
Well first of all I compiled with Visual Studio 2017 Express Edition in x64 mode (from command prompt started with `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Auxiliary\Build\vcvarsall.bat x86_x64`).

I used following triplet (named `x64-windows-mapnik`):
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
if(PORT MATCHES "mapnik|gdal|icu|boost-regex|libpq|openssl")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```

The build command I used was: `vcpkg install mapnik[input-csv,input-gdal,input-geobuf,input-geojson,input-ogr,input-pgraster,input-postgis,input-raster,input-shape,input-sqlite,input-topojson,proj4] --triplet=x64-windows-mapnik`

I didn't need to do other changes than mentioned in my other post.

2020-10-30 10:55 UTC, SNiLD commented
Now that I tried to use mapnik I faced couple of problems with this build. First you need to apply https://github.com/mapbox/variant/pull/182 and https://github.com/mapnik/mapnik/pull/4184 to fix MIN/MAX macro incompatibility with Visual Studio.

Also the dependency headers are not installed by your `CMakeLists.txt`. I can't provide you a pull request because Github [doesn't support](https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github) me to have fork of fork when I already have fork of the main project. 💯 
So here is a diff what I needed to add to your CMakeLists.txt:
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3e6f4049c..8ae6a09a1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -163,7 +163,9 @@ set(mapnik_include_paths
     deps/mapbox/polylabel/include
     deps/mapbox/variant/include)
     
-
+install(DIRECTORY deps/agg/include/ DESTINATION include CONFIGURATIONS Release)
+install(DIRECTORY deps/mapbox/geometry/include/ DESTINATION include CONFIGURATIONS Release)
+install(DIRECTORY deps/mapbox/protozero/include/ DESTINATION include CONFIGURATIONS Release)
     
 include_directories(${mapnik_include_paths}  ${thirdparty_include_paths})
 
```

Btw. I have made CMake support for mapnik long time ago based on their SCons scripts (version 3.0.11). Maybe those could help you as well: https://github.com/SNiLD/mapnik/tree/cmake

2020-10-30 14:19 UTC, am2222 commented
@SNiLD Thanks for the information, I am currently doing my comp exam until mid Dec, I will try to fix them then, 
thanks so much,

2020-12-04 09:02 UTC, NancyLi1013 commented
@am2222 

Is work still being done for the PR? I noticed that `mapnik ` was also added in another PR #14628.

2020-12-04 22:24 UTC, am2222 commented
Hi @NancyLi1013 , I could not manage to fix the issues with it yet. I had to take my comp exam and could not spend much time on it. I am not sure if the other PR has solved it or not. If yes we can use it, However I will update the forked mapnik repo with the latest mapnik version

2020-12-08 09:49 UTC, mathisloge commented
@am2222 yes, I have resolved the issues. 
There is now a PR @ mapnik for the cmake build https://github.com/mapnik/mapnik/pull/4191

Additionally mapbox/geometry and mapbox/polylabel were added to vcpkg to not to fetch the contents in the port

2020-12-10 01:17 UTC, am2222 commented
@mathisloge Hi, That is great, so it seems we will finally have it on windows and its nodejs package will also work. that is perfect, probably we need also port its python package as well

2020-12-10 06:50 UTC, mathisloge commented
@am2222 that's right. But unfortunately I don't have any spare time to do the node build. 

But it might be easy with https://github.com/cmake-js/cmake-js

2021-02-08 06:39 UTC, NancyLi1013 commented
@am2222 
Thanks for the PR. I'm closing this for now since there's been no progress for a long time. If you'd like to continue working on it, please reopen and ping us!

2021-02-08 06:39 UTC, closed without merging

2021-07-02 15:37 UTC, mathisloge commented
@am2222 if you still using node-mapnik I've added a proof of work https://github.com/mapnik/node-mapnik/pull/976

2021-07-02 21:20 UTC, am2222 commented
@mathisloge Thanks, are you using the github repo of mapnik for building it? if we can fix this port it will be perfect.

2021-07-02 21:31 UTC, mathisloge commented
@am2222 
https://github.com/microsoft/vcpkg/pull/14628 in conjunction with https://github.com/mapnik/mapnik/pull/4191 are working pretty well.

2021-08-30 19:11 UTC, mathisloge commented
@am2222 the cmake support is now merged into mapnik@master.

2021-08-31 14:29 UTC, am2222 commented
@mathisloge thanks man, That is a great new. We finally are able to have windows version alive