[geographiclib] Update to 1.50.1
microsoft/vcpkg pull request #11687
Opened 2020-06-01 07:09 UTC by NancyLi1013

Update `geographiclib `to the latest version 1.50.1.

Other changes:

- Update the patches
- Update the usage file

Also fix the usage error like this:

```
CMake Error at F:/test/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
1> [CMake]   Could not find a configuration file for package "geographiclib" that is
1> [CMake]   compatible with requested version "".
1> [CMake] 
1> [CMake]   The following configuration files were considered but not accepted:
1> [CMake] 
1> [CMake]     F:/test/vcpkg/installed/x64-windows/share/geographiclib/geographiclib-config.cmake, version: 1.47 (package = GeographicLib, NOT geographiclib)
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeProject8/CMakeLists.txt:5 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
```
Resolve #10293

Note: No feature need to test.

2020-06-09 07:25 UTC, NancyLi1013 commented
/azp run

2020-06-11 07:40 UTC, JackBoosY requested changes

2020-06-11 07:40 UTC, JackBoosY commented on ports/geographiclib/usage
> +    target_link_libraries(main PRIVATE GeographicLib GeographicLib_SHARED GeographicLib::GeographicLib GeographicLib::GeographicLib_SHARED)
Could you please add vcpkg-cmake-wrapper to solve this?

2020-06-16 17:56 UTC, Mistrical commented
I tried applying this patch to vcpkg:master at commit 7192d3affa4b1d8f88e3e730eb561612c24f7d78, but it failed to apply. See below:
```
$ git apply 11687.patch
11687.patch:46: trailing whitespace.
diff --git a/CMakeLists.txt b/CMakeLists.txt
11687.patch:47: trailing whitespace.
index 4a9ec4e..57bf448 100644
11687.patch:48: trailing whitespace.
--- a/CMakeLists.txt
11687.patch:49: trailing whitespace.
+++ b/CMakeLists.txt
11687.patch:50: trailing whitespace.
@@ -46,6 +46,7 @@ set (LIBVERSION_API 19)
error: patch failed: ports/geographiclib/CONTROL:1
error: ports/geographiclib/CONTROL: patch does not apply
error: patch failed: ports/geographiclib/portfile.cmake:45
error: ports/geographiclib/portfile.cmake: patch does not apply
```

Is the patch invalid or am I doing something wrong?

2020-06-17 02:31 UTC, NancyLi1013 commented
@Mistrical 
The error is like here:
`11687.patch:46: trailing whitespace.`
You might need to handle `trailing whitespace` issue.

2020-06-25 15:24 UTC, Mistrical commented
@NancyLi1013 Is this PR likely to be finished/merged soon?

I'm happy to help with testing it, but I still can't seem to apply the patch to master at commit 70ab27f

2020-06-26 05:28 UTC, Septarius commented
@Mistrical Try `git pull upstream pull/11687/head` on the local branch you want to patch. It should work if you have your upstream remote set on your fork. There are conflicts that you can accept incoming on in: `ports/geographiclib/CONTROL` and `ports/geographiclib/portfile.cmake`

2020-06-28 05:27 UTC, JackBoosY commented
Please resolve the file conflicts.

2020-07-09 11:29 UTC, cffk commented
@NancyLi1013 Hi, I'm the author of geographiclib.  I would be interested in hearing from you how I can simplify the deployment of a vcpkg for geographiclib.  Perhaps a single flag in CMakeLists.txt?  I also have some questions/comments about the patches:

* I see that the tools are not being built.  Perhaps they *should* be, but not installed?  That way the tests could be enabled.

* I've tried to make the version checking in project-config-cmake.cmake.in as robust as possible.  Do you have any suggestions here?

2020-07-10 06:51 UTC, NancyLi1013 commented
Hi @cffk 
Thanks a lot for coming here. It will be so great with your support and help.

It would be better to add the OPTIONS for these parts:

```
add_subdirectory (tools)
add_subdirectory (man)
add_subdirectory (doc)
add_subdirectory (js)
add_subdirectory (matlab)
add_subdirectory (python/geographiclib)
add_subdirectory (examples)
```
If so, we can disable the codes that we don't need to build via setting the value of options as off instead of making patches.  Or we can add them as features for `geographiclib`. 

I need to investigate why tools are disabled in  current version since it was introduced by some older changes. 

As for the usage, I just added this line:
`set(PROJECT_NAME_LOWER ${PROJECT_NAME})`.

Since the package name seems to be updated `GeographicLib `as `geographiclib`.

We should use `find_package(GeographicLib CONFIG REQUIRED)
` instead of `find_package(geographiclib CONFIG REQUIRED)`.

I will try to rebuild `geographiclib ` and confirm if it can work well after removing patches.

Thanks again for your support.

2020-07-10 08:32 UTC, NancyLi1013 commented
When I try to use `geographiclib` in release type, it references to a debug file. Since I only copy tools from _bin/_  directory to _tools/geographiclib_ directory. 

```
CMake Error at F:/11687/vcpkg/installed/x64-windows/share/geographiclib/geographiclib-targets.cmake:118 (message):
1> [CMake]   The imported target "CartConvert" references the file
1> [CMake] 
1> [CMake]      "F:/11687/vcpkg/installed/x64-windows/tools/geographiclib/CartConvert_d.exe"
1> [CMake] 
1> [CMake]   but this file does not exist.  Possible reasons include:
1> [CMake] 
1> [CMake]   * The file was deleted, renamed, or moved to another location.
1> [CMake] 
1> [CMake]   * An install or uninstall procedure did not complete successfully.
1> [CMake] 
1> [CMake]   * The installation package was faulty and contained
1> [CMake] 
1> [CMake]      "F:/11687/vcpkg/installed/x64-windows/share/geographiclib/geographiclib-targets.cmake"
1> [CMake] 
1> [CMake]   but not all the files it references.
```

2020-07-10 11:29 UTC, cffk commented
Let me try to get my arms around vcpkg and the changes that are being made to the build of GeographicLib.  Then I will be able to offer some intelligent feedback.  (A colleague at work was telling me about vcpkg since a year ago, but I haven't looked at it until now.)  I hope to get back to you within a couple of weeks.

2020-07-10 15:05 UTC, strega-nil commented
@cffk if you have any questions about how this stuff works, we're available on discord, slack, and github issues 😄😄😄

2020-07-11 17:59 UTC, cffk commented
OK, I've submitted an independent PR #12379.  I've configured this from scratch and expect that the next release of GeographicLib will need a minimal patch to work with vcpkg.  By the way, what's the recommended CMake variable, e.g., `_VCPKG_ROOT` to test for to see if a vcpkg port is being built.

2020-07-14 02:19 UTC, NancyLi1013 commented
Closed this PR since @cffk has submitted another PR #12379 to update `geographiclib `.

2020-07-14 02:19 UTC, closed without merging