[iwyu] Added new port: IWYU (include-what-you-use tool)
microsoft/vcpkg pull request #11688
Opened 2020-06-01 08:17 UTC by kafeg

Add support for build IWYU tool https://github.com/include-what-you-use/include-what-you-use

2020-06-01 09:36 UTC, NancyLi1013 requested changes

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/CONTROL
> +Description: include-what-you-use: A tool for use with clang to analyze #includes in C and C++ source files
```suggestion
Description: include-what-you-use: A tool for use with clang to analyze #includes in C and C++ source files
Homepage: https://github.com/include-what-you-use/include-what-you-use
```
Could you please add homepage here?

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
Why is this required here? Could you please make a simple description?

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +include(vcpkg_common_functions)
```suggestion
```
This function is deprecated. Could you please remove this line?

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +	)
```suggestion
)
```

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +    )
```suggestion
)
```

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +vcpkg_build_cmake()
```suggestion
```
This function should be not used here. Since it has been included in` vcpkg_install_cmake()`.

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/include)
Why do you remove include files? Are these headers not needed?

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +file(COPY ${SOURCE_PATH}/LICENSE.TXT DESTINATION ${CURRENT_PACKAGES_DIR}/share/iwyu)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE.TXT DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright )
```
Could you please update this as the review suggestion?

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +file(RENAME ${CURRENT_PACKAGES_DIR}/share/iwyu/LICENSE.TXT ${CURRENT_PACKAGES_DIR}/share/iwyu/copyright)
```suggestion
```
This line is not needed any more.

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +
```suggestion
```

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +file(INSTALL ${BINARY_TOOLS} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/iwyu)
```suggestion
file(INSTALL ${BINARY_TOOLS} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT})
```

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/iwyu)
`vcpkg_copy_tool_dependencies()` is deprecated. Please use `vcpkg_copy_tools()`.

2020-06-01 09:36 UTC, NancyLi1013 commented on ports/iwyu/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/iwyu)
Please remove the following blank lines.

2020-06-01 09:39 UTC, kafeg commented on ports/iwyu/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
Because it's just a binary tool without any libraries or headers. But it's helpful in C++ development sometimes.

2020-06-01 09:40 UTC, NancyLi1013 requested changes

2020-06-01 09:40 UTC, NancyLi1013 commented on ports/iwyu/CONTROL
> +Supports: !uwp
If this port doesn't support uwp, we should also add `vcpkg_fail_port_install(ON_TARGET "uwp") `to the top of portfile.cmake. And also add
```
iwyu: x64-uwp=fail
iwyu: arm-uwp=fail
```
to ci.baseline.txt.

2020-06-01 09:42 UTC, kafeg commented on ports/iwyu/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/include)
Yep, this is one binary tool to analyze C++ source files, it's not a library, but this tool is helpful for development.

2020-06-01 09:56 UTC, kafeg commented
Excuse me for the current state of the PR, i built it before only with CLang 8.0. CLang 10 unsupported for now =(

2020-06-02 09:24 UTC, NancyLi1013 commented
@dan-shaw 

Could you please help take a look and give some suggestion?

2020-06-12 22:11 UTC, dan-shaw commented
@kafeg In general, we need to get a green checkmark before merging any PR. Currently, we merge only C++ libraries (we haven't figured out what the plan for tools is), so I'm closing this PR. The supported way to acquire tools is `vcpkg_find_acquire_program`. Please reopen if I'm missing anything.

2020-06-12 22:11 UTC, closed without merging