[xbyak] Add new port
microsoft/vcpkg pull request #11689
Opened 2020-06-01 08:18 UTC by Ryan-rsm-McKenzie

**Describe the pull request**

Adds [xbyak](https://github.com/herumi/xbyak) to vcpkg

- What does your PR fix? Fixes #11673

- Which triplets are supported/not supported? Have you updated the CI baseline?
Header only, however only supports x86/x64 Windows/Linux/OSX

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-06-01 08:18 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11689) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11689) before we can accept your contribution.<br/><br/>:x: Ryan-rsm-McKenzie [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=11689)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=11689) it.</sub>

2020-06-02 02:36 UTC, LilyWangL requested changes

2020-06-02 02:36 UTC, LilyWangL commented on ports/xbyak/CONTROL
> +Version: 5.911
Can you please add the Homepage for this port in the CONTROL file?

2020-06-02 02:36 UTC, LilyWangL commented on ports/xbyak/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-06-02 02:36 UTC, LilyWangL commented on ports/xbyak/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/COPYRIGHT DESTINATION ${CURRENT_PACKAGES_DIR}/share/xbyak RENAME copyright)
Can you please use command `file(INSTALL ${SOURCE_PATH}/COPYRIGHT DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-06-09 06:04 UTC, LilyWangL commented
/azp run

2020-06-11 07:57 UTC, merged

2020-06-11 07:57 UTC, dan-shaw commented
Thanks for the PR!