docs: fix CMakeLists example for SQLite3
microsoft/vcpkg pull request #11763
Opened 2020-06-04 01:20 UTC by disposedtrolley

This PR modifies the `CMakeLIsts.txt` listing in the **Installing and Using Packages Example: SQLite** example doc to fix some build issues I was experiencing.

Without `target_include_directories` and linking to the `${SQLite3_LIBRARIES}` variable instead of `sqlite3` directly, `cmake --build .` errors with:

    fatal error C1083: Cannot open include file: 'sqlite3.h': No such file or directory

2020-06-04 03:49 UTC, JackBoosY requested changes

2020-06-04 03:49 UTC, JackBoosY commented on docs/examples/installing-and-using-packages.md
> +find_package(SQLite3 REQUIRED)
```suggestion
find_package(sqlite3 CONFIG REQUIRED)
```

2020-06-04 03:49 UTC, JackBoosY commented on docs/examples/installing-and-using-packages.md
> +target_include_directories(main PRIVATE ${SQLite3_INCLUDE_DIRS})
```suggestion
```

2020-06-04 03:49 UTC, JackBoosY commented on docs/examples/installing-and-using-packages.md
> +target_link_libraries(main ${SQLite3_LIBRARIES})
```suggestion
target_link_libraries(main PRIVATE sqlite3)
```

2020-06-04 05:39 UTC, JackBoosY approved these changes

2020-06-04 09:34 UTC, JackBoosY commented
Will rerun test after #11742 merged.

2020-06-04 10:18 UTC, SuperWig commented on docs/examples/installing-and-using-packages.md
> +target_link_libraries(main PRIVATE sqlite3))
```suggestion
target_link_libraries(main PRIVATE sqlite3)
```

2020-06-04 19:54 UTC, dan-shaw commented
/azp run

2020-06-05 17:58 UTC, merged

2020-06-05 17:58 UTC, ras0219-msft commented
Thanks for the PR!