[sqlpp11] update to v0.59
microsoft/vcpkg pull request #11771
Opened 2020-06-04 10:53 UTC by yurybura

This PR updates sqlpp11 library to v0.59 and adds features to sqlpp11-connector-mysql to support MySQL connector.

2020-06-05 02:53 UTC, JackBoosY commented
Thanks for this PR! But I've fixed cpp-taskflow and fastrtps regressions, so please revert them.

2020-06-05 09:58 UTC, JackBoosY approved these changes

2020-06-08 02:30 UTC, LilyWangL requested changes

2020-06-08 02:30 UTC, LilyWangL commented on ports/sqlpp11/portfile.cmake
>  file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug ${CURRENT_PACKAGES_DIR}/lib)
Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

2020-06-08 02:30 UTC, LilyWangL commented on ports/sqlpp11/CONTROL
> +Version: 0.59
Can you please add the Homepage for this port in the CONTROL file?

2020-06-08 08:33 UTC, yurybura commented on ports/sqlpp11/CONTROL
> +Version: 0.59
Added.

2020-06-08 09:38 UTC, LilyWangL commented
Waiting for PR #11824 merged, this PR will fix `qscintilla` build failed on CI.

2020-06-09 06:04 UTC, JackBoosY commented
/azp run

2020-06-10 05:56 UTC, LilyWangL approved these changes

2020-06-11 00:52 UTC, merged