[luajit] Add unsupported message
microsoft/vcpkg pull request #11831
Opened 2020-06-08 07:53 UTC by NancyLi1013

https://github.com/microsoft/vcpkg/blob/cb8a9fe7157f8ad2423742f893955ed9ced05910/ports/luajit/portfile.cmake#L27

Since `lujit `needs to build with the script` msvcbuild.bat` that requires Visual stuido.
So it only supports Windows platform.

2020-06-09 07:26 UTC, NancyLi1013 commented
/azp run

2020-06-11 08:00 UTC, JackBoosY requested changes

2020-06-11 08:00 UTC, JackBoosY commented on ports/luajit/CONTROL
> +Supports: x86|x64|windows
```suggestion
Supports: windows&(!uwp)
```

2020-06-12 03:14 UTC, JackBoosY approved these changes

2020-06-19 10:05 UTC, NancyLi1013 commented
When building on Linux via `Makefile`, post the error:
```
CMake Error at scripts/cmake/vcpkg_build_make.cmake:250 (file):
  file RENAME failed to rename

    /home/vruil/vcpkg/packages/luajit_x64-linux_tmp/home/vruil/vcpkg/installed/x64-linux/

  to

    /home/vruil/vcpkg/packages/luajit_x64-linux

  because: No such file or directory
```
So I changed `file(RENAME "${CURRENT_PACKAGES_DIR}_tmp${_VCPKG_INSTALL_PREFIX}/" "${CURRENT_PACKAGES_DIR}")` as 
`file(RENAME "${CURRENT_PACKAGES_DIR}" "${CURRENT_PACKAGES_DIR}")` in `vcpkg_build_make.cmake`. In this case, I can build luajit without any errors on Linux.

@Neumann-A 
Could you please help take a look about this rename failure?

2020-08-14 08:31 UTC, NancyLi1013 commented
/azp run

2020-10-29 08:56 UTC, JackBoosY commented
Temporary close this PR, Please reopen it when continue this work.

2020-10-29 08:56 UTC, closed without merging