[libuuid] Install uuid.pc file
microsoft/vcpkg pull request #11849
Opened 2020-06-09 07:05 UTC by LilyWangL

**Describe the pull request**

- What does your PR fix? Fixes #11817
Install uuid.pc file for libuuid, and fix deprecated functions.
- Which triplets are supported/not supported? Have you updated the CI baseline?
No
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-06-09 07:46 UTC, Neumann-A commented on ports/libuuid/portfile.cmake
missing call to `vcpkg_fixup_pkgconfig()`. Also you need to install it into `lib/pkgconfig` and `debug/lib/pkgconfig`

2020-06-09 12:52 UTC, c72578 commented on ports/libuuid/portfile.cmake
>      URLS "http://sourceforge.net/projects/libuuid/files/libuuid-1.0.3.tar.gz"
${LIBUUID_VERSION} can be used in the filename now:
`URLS "http://sourceforge.net/projects/libuuid/files/libuuid-${LIBUUID_VERSION}.tar.gz"`

2020-06-09 12:52 UTC, c72578 commented on ports/libuuid/portfile.cmake
>      FILENAME libuuid-1.0.3.tar.gz
Also here:
`FILENAME libuuid-${LIBUUID_VERSION}.tar.gz`

2020-06-10 05:51 UTC, JackBoosY requested changes

2020-06-10 05:51 UTC, JackBoosY commented on ports/libuuid/portfile.cmake
> +vcpkg_fail_port_install(MESSAGE "${PORT} currently only supports unix platform" ON_TARGET "Windows" "UWP")
```suggestion
vcpkg_fail_port_install(MESSAGE "${PORT} currently only supports unix platform" ON_TARGET "Windows")
```

2020-06-12 03:11 UTC, JackBoosY approved these changes

2020-06-12 04:39 UTC, merged