Bitmagic
microsoft/vcpkg pull request #11890
Opened 2020-06-11 20:16 UTC by JangBoo

**Describe the pull request**

- What does your PR fix? Fixes # [#11889](https://github.com/microsoft/vcpkg/issues/11889)

- Which triplets are supported/not supported? Have you updated the CI baseline?
  Only enabled x86-windows and x64-windows
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Let me know if there is errors, I'll edit it.

2020-06-12 07:46 UTC, NancyLi1013 reviewed
Is this a head-only library?

2020-06-12 11:39 UTC, Pospelove commented
@NancyLi1013 
Yes.
> BitMagic C++ is a header only library (easy to build and use in your project) and it comes with a set of examples.

2020-06-12 12:10 UTC, JangBoo commented
> @NancyLi1013

Yes

2020-06-15 02:47 UTC, JangBoo commented
> Is this a head-only library?

2020-06-15 03:10 UTC, NancyLi1013 requested changes

2020-06-15 03:10 UTC, NancyLi1013 commented on ports/bitmagic/portfile.cmake
> +
```suggestion
# Header-only library
```
It might be better to add this comment here.

2020-06-15 03:10 UTC, NancyLi1013 commented on ports/bitmagic/portfile.cmake
> +vcpkg_configure_cmake(
Since this is a header-only library. Is it necessary to use `vcpkg_configure_cmake()` here? Or we also need something else to build and use this port?

2020-06-15 21:48 UTC, JangBoo commented on ports/bitmagic/portfile.cmake
> +
Hi Nancy. I edited it as you suggested.

2020-06-16 02:58 UTC, NancyLi1013 approved these changes

2020-06-23 21:18 UTC, merged