Delete the bin directory if the platform is Linux
microsoft/vcpkg pull request #11903
Opened 2020-06-12 17:50 UTC by hellozee

- What does your PR fix?
Deletes the `bin/` directory in Linux for any type of builds. 

- Which triplets are supported/not supported? Have you updated the CI baseline?
Tested on x64-linux with the following triplet,
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
No, didn't update CI Baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-06-15 09:43 UTC, PhoebeHui requested changes
@hellozee, thanks for the PR!

2020-06-15 09:43 UTC, PhoebeHui commented on ports/x265/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
@hellozee, could you use VCPKG_TARGET_IS_LINUX instead?

Could you also update Version to 3.2-4 in CONTROL file?

2020-06-15 09:46 UTC, hellozee commented on ports/x265/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
Sure

2020-06-17 02:10 UTC, PhoebeHui approved these changes

2020-06-23 20:57 UTC, merged

2020-06-23 20:57 UTC, vicroms commented
Thanks for the PR!