[efsw] Add new port
microsoft/vcpkg pull request #11901
Opened 2020-06-12 12:49 UTC by Pospelove

closes #11894

2020-06-15 03:09 UTC, LilyWangL requested changes

2020-06-15 03:09 UTC, LilyWangL commented on ports/efsw/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
This is already the default behavior, `vcpkg_configure_cmake` already has:

```
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
        list(APPEND _csc_OPTIONS -DBUILD_SHARED_LIBS=ON)
    elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        list(APPEND _csc_OPTIONS -DBUILD_SHARED_LIBS=OFF)
    else()
        message(FATAL_ERROR
            "Invalid setting for VCPKG_LIBRARY_LINKAGE: \"${VCPKG_LIBRARY_LINKAGE}\". "
            "It must be \"static\" or \"dynamic\"")
    endif()
```

2020-06-15 10:31 UTC, Pospelove commented on ports/efsw/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
Fixed

2020-06-16 02:46 UTC, LilyWangL commented
Now this port build failed on triplet UWP and MACOS, you can download the error log from the following URL:

- x64-uwp: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/38877/artifacts?artifactName=x64-uwp%20port%20build%20failure%20logs&api-version=5.1&%24format=zip
- arm-uwp: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/38877/artifacts?artifactName=x64-uwp%20port%20build%20failure%20logs&api-version=5.1&%24format=zip
- x64-osx: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/38877/artifacts?artifactName=x64-uwp%20port%20build%20failure%20logs&api-version=5.1&%24format=zip

2020-06-16 17:28 UTC, Pospelove commented
I have opened an issue about UWP in source repo (https://github.com/SpartanJ/efsw/issues/108). For now, assume that UWP is not supported.

2020-06-16 17:30 UTC, Pospelove commented
It seems there is a typo in the library that causes build failure on MacOS (https://github.com/SpartanJ/efsw/pull/107). Let's wait for the author.

2020-06-16 20:45 UTC, Pospelove commented
Ready

2020-06-17 02:06 UTC, LilyWangL approved these changes

2020-06-23 20:58 UTC, vicroms commented
Thanks for the PR!

2020-06-23 20:58 UTC, merged