[networkdirect] Add new port (only test, no merge)
microsoft/vcpkg pull request #11935
Opened 2020-06-14 14:24 UTC by Voskrese

2020-06-14 16:58 UTC, Voskrese commented
пффф....

Cannot find path 'C:\Program Files (x86)\Windows Kits\10\Vsix\VS2019\WDK.vsix' because it does not exist.

2020-06-17 23:49 UTC, Voskrese commented
домучил) like broke a)))

2020-06-18 00:09 UTC, Voskrese commented
@BillyONeal 

`WDK repair + WDK.vsix + /p:SpectreMitigation=false` build ok

2020-06-18 00:11 UTC, BillyONeal requested changes
This needs to not install persistent things on the VM that affect other PRs.

2020-06-18 00:12 UTC, BillyONeal commented on scripts/azure-pipelines/windows/initialize-component.ps1
> +#Start-Process "$vsPath\Common7\IDE\VSIXInstaller.exe" "/q /a `"${env:ProgramFiles(x86)}\Windows Kits\10\Vsix\VS2019\WDK.vsix`"" -Wait
Clearly the vsix is not important because you commented that out

2020-06-18 00:14 UTC, BillyONeal commented
Right, the spectre thing is why I didn't want to add the WDK to the test fleet last time this came up.

(I know you were mostly attempting a test here; I marked 'waiting' just so that someone doesn't come by, not read the discussion, and merge without looking too hard)

2020-06-18 00:14 UTC, Voskrese commented on scripts/azure-pipelines/windows/initialize-component.ps1
> +#Start-Process "$vsPath\Common7\IDE\VSIXInstaller.exe" "/q /a `"${env:ProgramFiles(x86)}\Windows Kits\10\Vsix\VS2019\WDK.vsix`"" -Wait
@BillyONeal 
no, was an error that the library was needed

this parameter helped `/p:SpectreMitigation=false`

2020-06-18 03:44 UTC, Voskrese commented
@BillyONeal 
here I also need to explain? why do I want to add WDK and why am I testing for SpectreMitigation workarounds
what is the reason for suspending code testing?

2020-06-18 07:06 UTC, BillyONeal commented
No, it's clear here that you're just adding a port. :)

2020-06-18 13:36 UTC, Voskrese commented
OK, if you block someone else's attempts to succeed in overcoming port import problems.
wait until the fear disappears and make the MS-MPI port itself

> ок, раз блокируешь чужие попытки добиться успеха в преодолении проблем импорта портов.
> подождем когда исчезнет страх и сделаешь сам порт MS-MPI

looking forward to

2020-06-18 19:19 UTC, BillyONeal commented
You don't need to explain anything here. I marked this as 'request changes' so that someone else doesn't accidentally merge this PR while the deploy scripts don't match the actual VMs.

Even though I have 'request changes' set you can still test all you want :)

2020-06-18 23:23 UTC, BillyONeal commented
I'm not sure why it doesn't seem to be picking up your test run....

2020-06-18 23:23 UTC, BillyONeal commented
/azp run

2020-06-18 23:24 UTC, BillyONeal commented
Ah, that's why, sorry :)

2020-06-19 01:51 UTC, closed without merging