WIP: [libtins] Fix static build
microsoft/vcpkg pull request #11954
Opened 2020-06-15 14:47 UTC by Pospelove

- [x] Link `Packet.lib`
- [x] Add `TINS_STATIC` definition
- [ ] Link `Version.lib`
- [ ] `Packet.lib(Packet32.obj) : error LNK2005: LoadLibrarySafe already defined in wpcap.lib(pcap-tc.obj)`
- [ ] `Packet.lib(Packet32.obj) : error LNK2005: DllMain already defined in wpcap.lib(pcap-win32.obj)`

For now, I have no idea how to fix LNK2005. `winpcap` seems to be designed to use as DLL.

2020-06-16 02:27 UTC, LilyWangL requested changes

2020-06-16 02:27 UTC, LilyWangL commented on ports/libtins/portfile.cmake
>      REF v4.2
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-06-16 02:27 UTC, LilyWangL commented on ports/libtins/portfile.cmake
>    set(ENABLE_PCAP TRUE)
We prefer to use `VCPKG_TARGET_IS_WINDOWS` instead of `NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore"`.
Could you please update it?

2020-06-16 02:27 UTC, LilyWangL commented on ports/libtins/portfile.cmake
>      PREFER_NINJA
We prefer to use `if (VCPKG_TARGET_IS_WINDOWS)` instead of `if (NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "windows" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")`, please update it.

2020-06-16 02:27 UTC, LilyWangL commented
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

2020-06-18 06:34 UTC, LilyWangL approved these changes

2020-07-07 21:05 UTC, ras0219-msft commented
It might help to add
```
vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
```
to `winpcap`. This will prevent it from being used with the static CRT, but if a user defined a static lib + dynamic CRT triplet, it should work.

2020-07-22 06:33 UTC, LilyWangL commented
Pinging @Pospelove for response, can you address the review suggestions? Thanks!

2020-07-25 21:33 UTC, closed without merging

2020-07-25 21:34 UTC, Pospelove commented
I am not involved currently, so closing this for now.