[XLSX I/O] Add new port
microsoft/vcpkg pull request #11994
Opened 2020-06-17 20:48 UTC by Pospelove

closes #11556

2020-06-17 21:15 UTC, Pospelove commented
Trying to fix `x64-windows` and `x86-windows`. For some reason, these triplets work on my machine.

2020-06-18 06:31 UTC, NancyLi1013 commented on ports/xlsxio/portfile.cmake
> +    REF 7224eecf08b4b0584ec7601d3cc34c56dc83eb96
Is it because there are some bugs in the latest released version and you use a commit id here?

2020-06-18 06:39 UTC, NancyLi1013 requested changes

2020-06-18 06:39 UTC, NancyLi1013 commented on ports/xlsxio/portfile.cmake
> +if ("${VCPKG_LIBRARY_LINKAGE}" STREQUAL "dynamic")
```suggestion
if (VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
```

2020-06-18 11:37 UTC, Pospelove commented
Patches were merged into the library's master branch. Thanks to @brechtsanders!

2020-06-18 13:32 UTC, brechtsanders commented
@Pospelove May I ask why you're not building both static and shared library?
That's what I ususally do with the MinGW-w64 build (as shipped as win32 and win64 XLSX I/O binaries).

2020-06-18 15:13 UTC, Pospelove commented
@brechtsanders vcpkg doesn't build static and shared libraries at the same invocation. For example , `vcpkg install xlsxio:x86-windows` is used to install `xlsxio` port as a shared library. `vcpkg install xlsxio:x86-windows-static` - to install as a static library.

2020-06-19 01:30 UTC, NancyLi1013 approved these changes

2020-06-23 20:32 UTC, vicroms requested changes

2020-06-23 20:32 UTC, vicroms commented on ports/xlsxio/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
This is not necessary, I had success building the shared libraries, see changes to `vcpkg_configure_cmake()` below.

2020-06-23 20:32 UTC, vicroms commented on ports/xlsxio/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```suggestion
```

2020-06-23 20:32 UTC, vicroms commented on ports/xlsxio/portfile.cmake
> +)
```suggestion
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_EXAMPLES=OFF
        -DBUILD_TOOLS=OFF
)
```

2020-06-23 20:32 UTC, vicroms commented on ports/xlsxio/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
```suggestion
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)

if (VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()
```

2020-06-23 20:33 UTC, vicroms commented on ports/xlsxio/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
It is possible to build the shared libraries, the changes below are required.

2020-06-24 07:17 UTC, brechtsanders approved these changes

2020-06-24 07:53 UTC, NancyLi1013 commented
Hi @Pospelove 
Could you please look into the failures on osx?
```
FAILED: libxlsxio_read.dylib 
: && /Library/Developer/CommandLineTools/usr/bin/cc -fPIC -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names  -o libxlsxio_read.dylib -install_name @rpath/libxlsxio_read.dylib CMakeFiles/xlsxio_read_SHARED.dir/lib/xlsxio_read.c.o CMakeFiles/xlsxio_read_SHARED.dir/lib/xlsxio_read_sharedstrings.c.o  /Users/vagrant/Data/installed/x64-osx/debug/lib/libminizip.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libz.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libexpat.a && :
Undefined symbols for architecture x86_64:
  "_BZ2_bzDecompress", referenced from:
      _unzReadCurrentFile in libminizip.a(unzip.c.o)
  "_BZ2_bzDecompressEnd", referenced from:
      _unzCloseCurrentFile in libminizip.a(unzip.c.o)
  "_BZ2_bzDecompressInit", referenced from:
      _unzOpenCurrentFile3 in libminizip.a(unzip.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

2020-06-26 15:46 UTC, brechtsanders approved these changes
Why are you building with `-DBUILD_TOOLS=OFF` ?

2020-06-26 16:01 UTC, Pospelove commented
It fails to build and I don't know why. I'm unable to reproduce locally. Sometimes it's better to leave it as it is. Closing for now.

2020-06-26 16:01 UTC, closed without merging

2020-06-26 19:29 UTC, vicroms commented
@brechtsanders 

We prefer to disable building tools by default. A `tools` feature can be addded to the package to enable building them.

@Pospelove 

This is only a guess, but I think that `BUILD_STATIC_LIBS` stills need to be set to ON/OFF manually, as `vcpkg_configure_cmake` only sets `BUILD_SHARED_LIBS`.

2020-06-27 10:12 UTC, brechtsanders commented
@vicroms FYI: BUILD_STATIC and BUILD_SHARED both default to ON as the default build both static and shared libraries. If you want only one, you have to explicitly set the other to OFF.