[LIBXDIFF] Add port
microsoft/vcpkg pull request #12017
Opened 2020-06-19 02:13 UTC by comedinha

**Describe the pull request**

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?
Not support UWP.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-06-19 05:52 UTC, JackBoosY requested changes

2020-06-19 05:52 UTC, JackBoosY commented on ports/libxdiff/CONTROL
> +Description: The LibXDiff library implements basic and yet complete functionalities to create file differences/patches to both binary and text files. The library uses memory files as file abstraction
```suggestion
Description: The LibXDiff library implements basic and yet complete functionalities to create file differences/patches to both binary and text files. The library uses memory files as file abstraction to achieve both performance and portability.
Supports: !uwp
```

2020-06-19 05:52 UTC, JackBoosY commented on ports/libxdiff/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" KEYSTONE_BUILD_STATIC)
```suggestion
```

2020-06-19 05:52 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +libxdiff:arm-uwp=fail
```suggestion
```

2020-06-19 05:52 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +libxdiff:x64-uwp=fail
```suggestion
```

2020-06-19 05:52 UTC, JackBoosY commented on ports/libxdiff/portfile.cmake
> +        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/xdiff.dll")
Is this dynamic library installed in _${CURRENT_PACKAGES_DIR}/bin_?

2020-06-19 05:52 UTC, JackBoosY commented on ports/libxdiff/portfile.cmake
> +        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib/xdiff.dll")
Same as above.

2020-06-19 22:29 UTC, comedinha commented on ports/libxdiff/portfile.cmake
> +        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/xdiff.dll")
Added again.

2020-06-22 02:55 UTC, JackBoosY requested changes

2020-06-22 02:55 UTC, JackBoosY commented on ports/libxdiff/portfile.cmake
> +    SHA512 ${LIBXDIFF_SHA512}
```suggestion
    SHA512 ${LIBXDIFF_SHA512}
    HEAD_REF master
```

2020-06-22 02:56 UTC, JackBoosY approved these changes

2020-06-23 20:09 UTC, vicroms commented
Thanks for the PR!

2020-06-23 20:09 UTC, merged