[getdns] Add new port.
microsoft/vcpkg pull request #12090
Opened 2020-06-24 17:13 UTC by banburybill

Add new port for getdns (https://getdnsapi.net).

- What does your PR fix? Fixes #12075 

- Which triplets are supported/not supported? Have you updated the CI baseline?
 `x64-windows` and `x86-windows` definitely work. Expecting CI to provide feedback on other triplets.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

2020-06-28 02:16 UTC, NancyLi1013 commented
/azp run

2020-06-28 03:05 UTC, NancyLi1013 requested changes

2020-06-28 03:05 UTC, NancyLi1013 commented on ports/getdns/portfile.cmake
> +
Could you please use `vcpkg_from_github()` to download and extract the source here?

2020-06-28 03:05 UTC, NancyLi1013 commented on ports/getdns/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/getdns RENAME copyright)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```
Could you please update this?

2020-06-29 11:30 UTC, banburybill commented on ports/getdns/CONTROL
> +Build-Depends: libidn2, libevent, libuv, openssl
I have reworked the getdns libevent and libuv libraries as features.

2020-06-29 11:30 UTC, banburybill commented on ports/getdns/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/getdns RENAME copyright)
Done.

2020-06-30 01:58 UTC, NancyLi1013 commented on ports/getdns/portfile.cmake
> +
Thanks for your clarification.

2020-06-30 09:23 UTC, NancyLi1013 commented
/azp run

2020-06-30 10:24 UTC, NancyLi1013 commented
The failures on x64-uwp and arm-uwp triplets:
```
4>D:\buildtrees\getdns\src\1.6.0-ba09677cce\src\platform.c(56,17): error C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\getdns\x64-uwp-dbg\getdns_objects.vcxproj]
         ub_loop.c
     4>D:\buildtrees\getdns\src\1.6.0-ba09677cce\src\anchor.c(108,6): error C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\getdns\x64-uwp-dbg\getdns_objects.vcxproj]
     4>D:\buildtrees\getdns\src\1.6.0-ba09677cce\src\anchor.c(122,6): error C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\getdns\x64-uwp-dbg\getdns_objects.vcxproj]
     4>D:\buildtrees\getdns\src\1.6.0-ba09677cce\src\anchor.c(972,3): error C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\getdns\x64-uwp-dbg\getdns_objects.vcxproj]
     4>D:\buildtrees\getdns\src\1.6.0-ba09677cce\src\anchor.c(977,3): error C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\getdns\x64-uwp-dbg\getdns_objects.vcxproj]
     4>D:\buildtrees\getdns\src\1.6.0-ba09677cce\src\convert.c(1649,10): error C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\getdns\x64-uwp-dbg\getdns_objects.vcxproj]
```
Could you please look into this and try to fix it?

2020-06-30 12:48 UTC, banburybill commented
There's at least one Win32 API being used in GetDNS which is not supported in UWP. I don't have time to properly investigate and correct this myself right now, so for the moment I've marked it as not supported under UWP and filed a bug with upstream.

2020-07-01 01:51 UTC, NancyLi1013 commented
Have you tested these features? Can these work well?

2020-07-01 01:52 UTC, NancyLi1013 commented on ports/getdns/portfile.cmake
> +set(GETDNS_VERSION 1.6.0)
```suggestion
vcpkg_fail_port_install(ON_TARGET "uwp")

set(GETDNS_VERSION 1.6.0)
```
Since it currently doesn't support uwp, it would be better to add the messages here.

2020-07-02 11:48 UTC, banburybill commented on ports/getdns/portfile.cmake
> +set(GETDNS_VERSION 1.6.0)
Argh! Sorry. I'd thought that a CONTROL entry was sufficient.

2020-07-03 01:50 UTC, NancyLi1013 requested changes

2020-07-03 01:50 UTC, NancyLi1013 commented on ports/getdns/portfile.cmake
> +        libuv BUILD_LIBUV
```suggestion
    libevent BUILD_LIBEVENT2
    libuv BUILD_LIBUV
```
The key word `FEATURES `is not needed here in this case. Only when there are `INVERTED_FEATURES`, we should add it.

BTW, have you tested these two features?

2020-07-03 08:09 UTC, banburybill commented on ports/getdns/portfile.cmake
> +        libuv BUILD_LIBUV
If you say so. The documentation says it can be omitted, not that it must or even that omission is preferred. As it happens, I was following a port with INVERTED_FEATURES.

And yes, I have tested building both features. Each generates the appropriate additional library, and those libraries are not present unless you build with the feature, which is the expected behaviour.

2020-07-06 02:07 UTC, NancyLi1013 commented on ports/getdns/portfile.cmake
> +        libuv BUILD_LIBUV
You're right. It can be omitted, but not must. Thanks for your update.

2020-07-06 02:09 UTC, NancyLi1013 approved these changes

2020-07-06 21:26 UTC, ras0219-msft commented on ports/getdns/portfile.cmake
> +    libuv BUILD_LIBUV
Needs testing to confirm that this isn't building a vendored copy over using the vcpkg copy.

2020-07-06 22:26 UTC, banburybill commented on ports/getdns/portfile.cmake
> +    libuv BUILD_LIBUV
To be clear, these features are not building `libevent` or `libuv`. They are building `getdns` extension libraries that allow `getdns` to use the `libevent` and `libuv` event loops, and require the vcpkg packages `libevent` and `libuv` to build and run. See https://getdnsapi.net/documentation/manpages/#ASYNCHRONOUS%20USE.

https://github.com/getdnsapi/getdns/blob/develop/CMakeLists.txt#L863 is the build section dealing with the `libuv` extension library `getdns_ex_uv`.

2020-07-07 00:22 UTC, ras0219-msft commented on ports/getdns/portfile.cmake
> +    libuv BUILD_LIBUV
Thanks for the clarification; it's just very confusing that they chose to name the user-visible option `BUILD_LIBUV` instead of `USE_LIBUV`

2020-07-07 00:22 UTC, merged

2020-07-07 00:22 UTC, ras0219-msft commented
LGTM, thanks for the PR!