[angle] Add egl renderer to list of files compiled for linux
microsoft/vcpkg pull request #12111
Opened 2020-06-25 14:52 UTC by ankurverma85

For linux builds add egl to the list of files compiled.
Not including them causes linking issues on linux with the following undefined reference 
rx::DisplayEGL::DisplayEGL 
as per the following code snippet from
rc/libANGLE/Display.cpp:287
```
#    elif defined(ANGLE_PLATFORM_LINUX)
#        if defined(ANGLE_USE_OZONE)
            impl = new rx::DisplayOzone(state);
#        else
            if (deviceType == EGL_PLATFORM_ANGLE_DEVICE_TYPE_EGL_ANGLE)
            {
                impl = new rx::DisplayEGL(state);
            }
#            if defined(ANGLE_USE_X11)
            else
            {
                impl = new rx::DisplayGLX(state);
            }
#            endif
```
Fixes # 12110

2020-06-28 02:18 UTC, PhoebeHui commented
/azp run

2020-06-28 07:38 UTC, PhoebeHui requested changes
Could you also update the version to '2020-05-15-1' in CONTROL file?

2020-06-30 07:05 UTC, ankurverma85 commented
> Could you also update the version to '2020-05-15-1' in CONTROL file?

2020-06-30 07:19 UTC, PhoebeHui commented
@ankurverma85, why do you close this PR?

2020-06-30 07:45 UTC, ankurverma85 commented
Sorry that was accidental.
New to github ux.

2020-06-30 09:02 UTC, ankurverma85 commented
Is there something blocking this pr?

2020-06-30 09:13 UTC, PhoebeHui reviewed
No changes required now. Thanks for the updates!

2020-06-30 09:13 UTC, PhoebeHui approved these changes

2020-06-30 14:53 UTC, ankurverma85 commented
Can you merge this pull requeat. I can't see any options to complete the pull request.
Maybe I'm not allowed to?

2020-07-01 01:12 UTC, PhoebeHui commented
@BillyONeal, could you please help review and merge this PR?

2020-07-06 21:06 UTC, merged

2020-07-06 21:06 UTC, ras0219-msft commented
LGTM, thanks for the improvement!