[vcpkg] Implement --x-write-nuget-packages-config= setting for `install` and `x-set-installed`
microsoft/vcpkg pull request #12138
Opened 2020-06-27 20:18 UTC by ras0219

This PR enables the four-phase-flow for binary caching via the `--x-write-nuget-packages-config=...` setting. See the specification in #11204 for more details.

This PR also adds an end-to-end test suite to the x86-windows CI to cover basic command operation.

2020-06-30 21:40 UTC, BillyONeal approved these changes

2020-06-30 21:40 UTC, BillyONeal commented on toolsrc/src/vcpkg/base/files.cpp
> +    fs::path concat(const fs::path& lhs, const fs::path& rhs)
This is confusing because in std::filesystem concat is the 'dangerous touch the underlying native string' function but you're giving it append (or /) behavior. Should we call this combine or append instead?

2020-06-30 21:40 UTC, BillyONeal commented on toolsrc/src/vcpkg/base/files.cpp
> +        }
```suggestion
#if VCPKG_USE_STD_FILESYSTEM
        return lhs / rhs;
#else // ^^^ VCPKG_USE_STD_FILESYSTEM // !VCPKG_USE_STD_FILESYSTEM vvv
        if (rhs.is_absolute())
        {
            return rhs;
        }
        else
        {
            return lhs / rhs;
        }
#endif // VCPKG_USE_STD_FILESYSTEM
```

2020-06-30 21:40 UTC, BillyONeal commented on toolsrc/src/vcpkg/binarycaching.cpp
> +std::string vcpkg::generate_packagesconfig(const Dependencies::ActionPlan& action)
Is this the same thing as "pkgconfig"? If so it might make sense to leave it with that spelling given that we use the word "package" to mean something else elsewhere in this codebase.

2020-06-30 21:40 UTC, BillyONeal commented on toolsrc/src/vcpkg/binarycaching.cpp
> +std::string vcpkg::generate_packagesconfig(const Dependencies::ActionPlan& action)
(If it is not the same as "pkgconfig" or .pc files please ignore this comment)

2020-07-01 15:50 UTC, strega-nil requested changes

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$ErrorActionPreference = "Stop"
I think Billy and I have agreed on the "don't `$ErrorActionPreference = 'Stop'`, throw on fatal error" convention (specifically, if you have an error that's Definitely Fatal, `throw` with no arguments after you write it)

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +function Require-Not-File {
```suggestion
function Require-FileNotExists {
```

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +function Require-File {
```suggestion
function Require-FileExists {
```

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +./vcpkg @commonArgs install rapidjson --binarycaching "--x-binarysource=clear;files,$ArchiveRoot,write;nuget,$NuGetRoot,upload"
Might be best to write a little helper function:

```pwsh
function Invoke-CommandAndEcho {
  [CmdletBinding()]
  Param(
    [Parameter(Mandatory=$True)]
    [string]$Command,
    [Parameter(ValueFromRemainingArguments)]
    [string]$Arguments
  )

  Write-Host "$Command $($Arguments -join ' ')"
  & $Command @Arguments
}
```

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +    $WorkingRoot
```suggestion
    [string]$WorkingRoot
```

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +        $file
Generally, I recommend static typing and pascal case for parameters:

```suggestion
        [string]$File
```

(and then change the other references to be pascal case as well)

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +        $file
Same as above - pascal case + static type.

2020-07-01 15:50 UTC, strega-nil commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +if ($(Get-ChildItem $NuGetRoot/*.nupkg | Measure-Object).count -ne 1) {
```suggestion
if ((Get-ChildItem $NuGetRoot -Filter '*.nupkg' | Measure-Object).Count -ne 1)
```

2020-07-01 15:50 UTC, strega-nil commented on toolsrc/src/vcpkg/commands.setinstalled.cpp
> +         "binarycaching` for more information."},
```suggestion
         "Writes out a NuGet packages.config-formatted file for use with external binary caching.\n"
         "See `vcpkg help binarycaching` for more information."},
```

2020-07-01 15:50 UTC, strega-nil commented on toolsrc/src/vcpkg/install.cpp
> +         "binarycaching` for more information."},
Seems like this option exists in multiple commands -- we might want to have a single place where this help exists.

2020-07-01 15:50 UTC, strega-nil commented on toolsrc/src/vcpkg/binarycaching.cpp
> +std::string vcpkg::generate_packagesconfig(const Dependencies::ActionPlan& action)
```suggestion
std::string vcpkg::generate_nuget_packages_config(const Dependencies::ActionPlan& action)
```

2020-07-01 16:50 UTC, ras0219 commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$ErrorActionPreference = "Stop"
The problem is that nearly every action statement in this file is a fatal error; adding `if(){throw}` checks after everything would double/quadruple the length of the file.

@BillyONeal?

2020-07-01 16:51 UTC, ras0219 commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +./vcpkg @commonArgs install rapidjson --binarycaching "--x-binarysource=clear;files,$ArchiveRoot,write;nuget,$NuGetRoot,upload"
I need `$CommonTest` to be set for the `Require-File` and `Require-Not-File` macros to print helpful messages. I may be able to factor things slightly better however...

2020-07-01 16:54 UTC, ras0219 commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$TestingRoot = Join-Path $WorkingRoot 'testing'
To be completely honest, I've never totally understood the difference between `Join-Path` and just using `/`; I assume it will perform lexical normalization, but I don't know.

2020-07-01 17:02 UTC, ras0219 commented on toolsrc/src/vcpkg/install.cpp
> +         "binarycaching` for more information."},
Yes, there is room for a followup refactor PR that centralizes this as well as dry-run and other common options

2020-07-01 17:06 UTC, ras0219 commented on toolsrc/src/vcpkg/binarycaching.cpp
> +std::string vcpkg::generate_packagesconfig(const Dependencies::ActionPlan& action)
They are different, however I will name it as @strega-nil has suggested.

2020-07-01 17:55 UTC, BillyONeal commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$ErrorActionPreference = "Stop"
I didn't have a strong opinion on Write-Error followed or not followed by throw, as long as we were consistent in all the places about it. @strega-nil you wanted the extra throw, so I added that in https://github.com/microsoft/vcpkg/pull/12176 . I still think `$ErrorActionPreference = "Stop"` is a good idea regardless of what we do to Write-Error

I don't see any Write-Errors in this file so I understand neither your objection @strega-nil , nor your assertion that the file would become longer @ras0219 .

2020-07-01 17:58 UTC, BillyONeal commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$TestingRoot = Join-Path $WorkingRoot 'testing'
`Join-Path` tolerates a trailing slash on the first argument while an explicit / might result in a double slash. See https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,1287

2020-07-01 17:59 UTC, BillyONeal approved these changes

2020-07-01 18:34 UTC, ras0219 commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$ErrorActionPreference = "Stop"
E.g. I want `Remove-Item` failing to be a fatal error, so I'd have to add either `-ErrorAction Stop` to all of them or add a check after

2020-07-01 18:35 UTC, BillyONeal commented on scripts/azure-pipelines/end-to-end-tests.ps1
> +$ErrorActionPreference = "Stop"
I see, then for that I agree with `$ErrorActionPreference = "Stop"`.

2020-07-01 18:36 UTC, merged