[simdjson] Update to 0.4.1
microsoft/vcpkg pull request #12140
Opened 2020-06-28 01:05 UTC by myd7349

**Describe the pull request**

- What does your PR fix? Fixes https://github.com/simdjson/simdjson/issues/981

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

2020-06-28 06:23 UTC, JackBoosY requested changes

2020-06-28 06:23 UTC, JackBoosY commented on ports/simdjson/portfile.cmake
> -    HEAD_REF master
Should this line be deleted?

2020-06-29 00:48 UTC, myd7349 commented on ports/simdjson/portfile.cmake
> -    HEAD_REF master
Nice catch! Thanks.

2020-06-29 03:10 UTC, JackBoosY requested changes

2020-06-29 03:10 UTC, JackBoosY commented on scripts/ci.baseline.txt
>  simdjson:x86-windows=fail
```suggestion
```

2020-06-29 03:11 UTC, JackBoosY approved these changes

2020-06-29 06:40 UTC, JackBoosY approved these changes

2020-07-01 02:25 UTC, JackBoosY commented
Ready for review now?

2020-07-01 05:33 UTC, myd7349 commented
> 
> 
> Ready for review now?

Yes.

2020-07-01 05:37 UTC, JackBoosY approved these changes

2020-07-04 04:07 UTC, myd7349 commented
Hi! @JackBoosY Please review again. The upstream has issue several patch releases recently since `v0.4.1`, so I need to update this PR to catch up the upstream.

2020-07-06 03:14 UTC, JackBoosY requested changes

2020-07-06 03:14 UTC, JackBoosY commented on ports/simdjson/portfile.cmake
> +    REF 74870a81898ba44407f5dce1f0f50d4ea53fca04 # v0.4.6
```suggestion
    REF 74870a81898ba44407f5dce1f0f50d4ea53fca04 # v0.4.6
    HEAD_REF master
```

2020-07-06 03:14 UTC, JackBoosY approved these changes

2020-07-07 20:54 UTC, merged

2020-07-07 20:54 UTC, ras0219-msft commented
LGTM, thanks for the PR!