[geos] Update to 3.8.1
microsoft/vcpkg pull request #12163
Opened 2020-06-30 11:52 UTC by oswjk

**Describe the pull request**

- What does your PR fix?

Update geos to 3.8.1

- Which triplets are supported/not supported? Have you updated the CI baseline?

No changes to triplet support I think.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

It should.

2020-07-01 02:14 UTC, PhoebeHui approved these changes
Thanks for the PR! I guess this PR ready for review.

2020-07-06 20:34 UTC, ras0219-msft requested changes

2020-07-06 20:34 UTC, ras0219-msft commented on ports/geos/static-lib-prefix.patch
> ++    set_target_properties(geos PROPERTIES PREFIX lib)
Why is this needed? Ideally, the static libraries and the import libraries will have the same name (see the maintainer guide[1]). If there are downstream ports that break when only the dynamic names are provided, they should be patched instead to use the CMake targets.

[1] https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-rename-binaries-outside-the-names-given-by-upstream

2020-07-06 21:16 UTC, oswjk commented
Hi, I cant take a look at this for a couple of weeks as I'm on vacation.

BR,
Oskari
________________________________
From: Robert Schumacher <notifications@github.com>
Sent: maanantai 6. heinäkuuta 2020 23.34
To: microsoft/vcpkg
Cc: Oskari Timperi; Author
Subject: Re: [microsoft/vcpkg] [geos] Update to 3.8.1 (#12163)

@ras0219-msft requested changes on this pull request.
________________________________
In ports/geos/static-lib-prefix.patch:

> @@ -0,0 +1,26 @@
+diff --git a/CMakeLists.txt b/CMakeLists.txt
+index b78ca54b..26778c83 100644
+--- a/CMakeLists.txt
++++ b/CMakeLists.txt
+@@ -228,6 +228,10 @@ if(BUILD_SHARED_LIBS)
+ 
+   set_target_properties(geos PROPERTIES VERSION ${GEOS_VERSION})
+   set_target_properties(geos PROPERTIES SOVERSION ${GEOS_VERSION})
++else()
++  if(WIN32)
++    set_target_properties(geos PROPERTIES PREFIX lib)

Why is this needed? Ideally, the static libraries and the import libraries will have the same name (see the maintainer guide[1]). If there are downstream ports that break when only the dynamic names are provided, they should be patched instead to use the CMake targets.
[1] https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-rename-binaries-outside-the-names-given-by-upstream
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-04 06:49 UTC, oswjk commented on ports/geos/static-lib-prefix.patch
> ++    set_target_properties(geos PROPERTIES PREFIX lib)
I probably just thought to make the port work like it did before. I've added a commit to fix libspatialite and gdal builds.

2020-08-04 09:25 UTC, oswjk commented
@PhoebeHui Can I somehow run the CI again as the build errors seems to be something that I cannot control? For example [The windows build](https://dev.azure.com/vcpkg/public/_build/results?buildId=41045&view=logs&j=384c4415-93cb-5962-b64b-d976ffb39bd5&t=10350a3b-04e8-59df-137f-98051148e2b1&l=42):

```
Downloading powershell-core...
 https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> D:\downloads\PowerShell-6.2.1-win-x86.zip
WinHttpReceiveResponse() failed: 12152
##[error]Convert-Path : Cannot find path 'C:\agent\_work\1\a\xml-results\x64-windows.xml' because it does not exist.
```

2020-08-10 11:21 UTC, oswjk commented
/azp run

2020-08-10 23:55 UTC, PhoebeHui commented
/azp run

2020-08-10 23:57 UTC, PhoebeHui commented
@oswjk, the failures doesn't relate to your changes, please ignore it, I have rerun the CI testing.

2020-08-18 22:36 UTC, ras0219 requested changes
Because this modifies gdal, libspatialite, and spatialite-tools, those ports all need to have their `Port-Version:` incremented (or introduced and set to `1` if they don't have one).

Otherwise, LGTM

2020-08-18 22:36 UTC, ras0219 commented on ports/spatialite-tools/portfile.cmake
> +    set(GEOS_LIBS_DBG "${LDIR}/debug/lib/geos_c.lib ${LDIR}/debug/lib/geos.lib")
```suggestion
    set(GEOS_LIBS_DBG "${LDIR}/debug/lib/geos_cd.lib ${LDIR}/debug/lib/geosd.lib")
```

2020-08-20 12:59 UTC, oswjk commented
Merged master as `soil` was failing.

2020-09-01 00:45 UTC, ras0219 approved these changes

2020-09-01 00:45 UTC, merged