[openvr] Update to 1.12.5
microsoft/vcpkg pull request #12219
Opened 2020-07-02 15:06 UTC by RT222

https://github.com/ValveSoftware/openvr/releases/tag/v1.12.5

2020-07-02 18:49 UTC, ras0219 requested changes

2020-07-02 18:49 UTC, ras0219 commented on ports/openvr/portfile.cmake
> +set(VCPKG_LIBRARY_LINKAGE dynamic)
Ports should never directly set library linkage; they can instead use `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)`. (The existing port is also incorrect).

2020-07-02 21:22 UTC, RT222 commented on ports/openvr/portfile.cmake
> +set(VCPKG_LIBRARY_LINKAGE dynamic)
That's what I did initially, but it failed to build with the x64-windows-static triplet, because of the static CRT : 
```
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
```
Is it better to let the build fail in this case?

2020-07-03 06:05 UTC, LilyWangL commented
Thanks for your PR. Now `openvr:x64-windows-static` build failed. If expected, add `openvr:x64-windows-static=fail` to _.\scripts\ci.baseline.txt_.

2020-07-03 06:07 UTC, ras0219 commented on ports/openvr/portfile.cmake
> +set(VCPKG_LIBRARY_LINKAGE dynamic)
Yep, this case (mixing dynamic libraries with static CRT) can cause tons of problems for downstream consumers if they aren't expecting it. This is why the helper is good -- it does the right thing :)

2020-07-03 09:08 UTC, LilyWangL approved these changes

2020-07-06 19:51 UTC, merged

2020-07-06 19:52 UTC, ras0219-msft commented
Thanks for the update!

2021-01-06 16:09 UTC, tiaoyuedexin commented
@LilyWangL  Hello ,when I install openvr use vcpgk ，I got a error—— Building package openvr:x64-windows-static failed with: BUILD_FAILED，can you tell me  how do I deal with this? thanks