[ogre] Update to version 1.12.7 and fix link error
microsoft/vcpkg pull request #12210
Opened 2020-07-02 08:44 UTC by LilyWangL

**Describe the pull request**

- What does your PR fix? Fixes #12054
Update ogre to version 1.12.7 and fix link error
- Which triplets are supported/not supported? Have you updated the CI baseline?
No
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-07-03 02:46 UTC, NancyLi1013 approved these changes

2020-07-03 05:39 UTC, JackBoosY approved these changes

2020-07-06 20:14 UTC, ras0219-msft requested changes

2020-07-06 20:14 UTC, ras0219-msft commented on ports/ogre/fix-dependency.patch
> ++    ${IMGUI_INCLUDE_DIR}/imgui/imgui_freetype.cpp)
This should link the built imgui static library, not add its sources.

2020-07-06 20:14 UTC, ras0219-msft commented on ports/ogre/CONTROL
> +Build-Depends: freeimage, freetype, zlib, zziplib, imgui, sdl2, pugixml
This should require the freetype feature `imgui[feature]`

2020-07-06 20:14 UTC, ras0219-msft commented on ports/imgui/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}/misc/freetype/imgui_freetype.cpp
Consumers should use the built static library, not include these sources. These should not be published.

2020-07-06 20:14 UTC, ras0219-msft commented on ports/imgui/CMakeLists.txt
> +        ${CMAKE_CURRENT_SOURCE_DIR}/misc/freetype/imgui_freetype.h
This is already handled if users require the `freetype` feature.

2020-07-09 20:12 UTC, ras0219-msft requested changes

2020-07-09 20:12 UTC, ras0219-msft commented on ports/ogre/fix-findimgui.patch
> ++    ${IMGUI_INCLUDE_DIR}/src/imgui/imgui.h
Based on my reading, this will still install `imgui.h` to `include/OGRE/Overlay/include.h`.

I believe the entire block at https://github.com/OGRECave/ogre/blob/36090b062c5741740a1dc274c33b7abb141d6e8d/Components/Overlay/CMakeLists.txt#L41 should be disabled.

2020-07-31 05:39 UTC, merged