oat++ suite bump to version 1.1
microsoft/vcpkg pull request #12249
Opened 2020-07-03 10:01 UTC by mheyman

**Oat++ suite bump to version 1.1**

Oat++ bumped to version 1.1 in mid May. We've been using the core, websockets, and swagger for a month on both Windows and Linux with no issues.

2020-07-06 07:05 UTC, NancyLi1013 requested changes

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp-consul/CONTROL
>  Description: OAT++ Modern web framework consul module
Could you please add homepage here?

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp-curl/CONTROL
>  Description: Oat++ Modern web framework curl module to use libcurl as a RequestExecutor on the oatpp's ApiClient
Could you please add homepage here?

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp-libressl/CONTROL
>  Description: Oat++ libressl module providing secure server and client connection providers
The same as above.

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp-mbedtls/CONTROL
>  Description: Oat++ Mbed TLS submodule providing secure server and client connection providers
The same as above.

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp-swagger/CONTROL
>  Description: Oat++ OpenApi (Swagger) UI submodule
The same as above.

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp-websocket/CONTROL
>  Description: Oat++ websocket module
The same as above.

2020-07-06 07:05 UTC, NancyLi1013 commented on ports/oatpp/CONTROL
>  Description: Modern web framework
The same as above.

2020-07-06 07:10 UTC, NancyLi1013 commented
The failures on x86-windows, x64-windows, x64-windows-static are like this:
```
-- Configuring done
CMake Error at C:/agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:326 (_add_library):
  Target "oatpp-mbedtls" links to target "mbedtls::TLS" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:2 (add_library)


CMake Error at C:/agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:326 (_add_library):
  Target "oatpp-mbedtls" links to target "mbedtls::X509" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:2 (add_library)


CMake Error at C:/agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:326 (_add_library):
  Target "oatpp-mbedtls" links to target "mbedtls::Crypto" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:2 (add_library)
```

2020-07-06 16:25 UTC, mheyman commented on ports/oatpp-consul/CONTROL
>  Description: OAT++ Modern web framework consul module
Done (didn't know about "Homepage:")

2020-07-06 16:25 UTC, mheyman commented on ports/oatpp-curl/CONTROL
>  Description: Oat++ Modern web framework curl module to use libcurl as a RequestExecutor on the oatpp's ApiClient
Done (didn't know about "Homepage:")

2020-07-06 16:25 UTC, mheyman commented on ports/oatpp-libressl/CONTROL
>  Description: Oat++ libressl module providing secure server and client connection providers
Done (didn't know about "Homepage:")

2020-07-06 16:25 UTC, mheyman commented on ports/oatpp-mbedtls/CONTROL
>  Description: Oat++ Mbed TLS submodule providing secure server and client connection providers
Done (didn't know about "Homepage:")

2020-07-06 16:25 UTC, mheyman commented on ports/oatpp-swagger/CONTROL
>  Description: Oat++ OpenApi (Swagger) UI submodule
Done (didn't know about "Homepage:")

2020-07-06 16:25 UTC, mheyman commented on ports/oatpp-websocket/CONTROL
>  Description: Oat++ websocket module
Done (didn't know about "Homepage:")

2020-07-06 16:26 UTC, mheyman commented on ports/oatpp/CONTROL
>  Description: Modern web framework
Done (didn't know about "Homepage:")

2020-07-07 07:04 UTC, NancyLi1013 commented
Please also look into the regressions and try to fix them.

2020-07-12 20:20 UTC, mheyman commented
The latest code has a change in case for a find_package() that was not failing on my build but seemed to be the issue on yours. We'll see ;-)

2020-07-15 09:08 UTC, NancyLi1013 commented
I will try to reproduce this on my local.

2020-07-16 07:25 UTC, NancyLi1013 commented
It seems to be related with case sensitive.

I noticed that it used `if(MBEDTLS_FOUND)` in 
`cmake/module/Findmbedtls.cmake
`.

But from the configure log, I found the info is:
`-- Found mbedTLS: D:/installed/x64-windows/include (found version "2.16.3")`

So could you please try to update `MBEDTLS_FOUND` as `mbedTLS_FOUND` and rebuild this on CI?

2020-07-27 02:02 UTC, NancyLi1013 commented
/azp run

2020-08-18 22:27 UTC, BillyONeal commented
PR validation still looks like legit failures

2020-08-27 02:37 UTC, NancyLi1013 commented
@mheyman 
Is work still being done for this PR?

2020-09-07 10:26 UTC, mheyman commented
I still want to be able to use oatpp from github vcpkg. Been too busy to do
more. I have to tell you that we've been using it from our own fork of
vcpkg for a while on both windows and linux and haven't been able to
reproduce the issues it has been having building on your servers and it is
hard to debug (or at least requires arcane knowledge I don't posses). Is
there a faq or other document somewhere listing common steps to take when
your code builds without a problem locally but fails in the azure system
you are using?

Thanks

On Wed, Aug 26, 2020 at 10:37 PM NancyLi1013 <notifications@github.com>
wrote:

> @mheyman <https://github.com/mheyman>
> Is work still being done for this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/12249#issuecomment-681308440>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJT7J4G5CH3OYZHVKE2EWDSCXBHFANCNFSM4OPVKTVQ>
> .
>

2020-09-07 13:23 UTC, mheyman commented
I think I finally figured out what was going on - there is a version of FindMbedtls.cmake somewhere on the Azure build servers that doesn't exist in our systems. Cmake calls that find code instead of the one that comes with Oat++. And, that find code doesn't set up the mbedtls targets expected by Oat++, just some variables (which I used instead). FYI: there are also log lines showing that pthreads4w is getting pulled in on the Azure build servers and that doesn't get pulled in on our servers either but that may be part of the FindMbedtls.cmake hijacking going on.

2020-09-08 18:58 UTC, BillyONeal commented
> there is a version of FindMbedtls.cmake somewhere on the Azure build servers

https://github.com/microsoft/vcpkg/blob/master/ports/mbedtls/vcpkg-cmake-wrapper.cmake is that override.

2020-09-08 21:45 UTC, mheyman commented
> > there is a version of FindMbedtls.cmake somewhere on the Azure build servers
> 
> https://github.com/microsoft/vcpkg/blob/master/ports/mbedtls/vcpkg-cmake-wrapper.cmake is that override.

:-) Got it to work using that one or the one that comes with Oat++ for the rest of us

2020-10-06 14:06 UTC, KaungZawHtet commented
1.2.0 is coming

2020-10-06 14:54 UTC, BillyONeal commented
@NancyLi1013 is on vacation and I think she was waiting for a clean CI run anyway; it's passing now so I merged it.

Thanks for your contribution!

2020-10-06 14:54 UTC, merged

2020-10-09 03:11 UTC, NancyLi1013 commented
Thanks for your help and follow up @BillyONeal .

2020-10-09 20:08 UTC, KaungZawHtet commented
it is still 1.0.0 when I do `vcpkg search oatpp`

<img width="853" alt="95308636-2d2b2280-08b0-11eb-81a3-ba82b82e34b4" src="https://user-images.githubusercontent.com/15225530/95627153-adfd4080-0aa1-11eb-929d-33a1018bf880.png">

2020-10-09 22:02 UTC, BillyONeal commented
> it is still 1.0.0 when I do `vcpkg search oatpp`
> 
> <img alt="95308636-2d2b2280-08b0-11eb-81a3-ba82b82e34b4" width="853" src="https://user-images.githubusercontent.com/15225530/95627153-adfd4080-0aa1-11eb-929d-33a1018bf880.png">

Did you do a `git pull` to update your vcpkg repo?

2020-10-10 08:30 UTC, KaungZawHtet commented
opps! I notice what I missed. Thx