[libcoppp] Update version to 1.3.0
microsoft/vcpkg pull request #12264
Opened 2020-07-04 08:52 UTC by owt5008137

**Describe the pull request**

- What does your PR fix? 

Nothing

- Which triplets are supported/not supported? Have you updated the CI baseline?

All x86 and x64 triplets. Yes

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-07-06 02:54 UTC, JackBoosY requested changes

2020-07-06 02:54 UTC, JackBoosY commented on ports/libcopp/portfile.cmake
> +# vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```suggestion
```

2020-07-06 03:02 UTC, JackBoosY requested changes

2020-07-06 03:02 UTC, JackBoosY commented on ports/libcopp/portfile.cmake
> +if (VCPKG_LIBRARY_LINKAGE EQUAL "static")
We don't need to pass `BUILD_SHARED_LIBS` into cmake, vcpkg will perform this operation automatically.

2020-07-06 03:20 UTC, NancyLi1013 requested changes

2020-07-06 03:20 UTC, NancyLi1013 commented on ports/libcopp/portfile.cmake
> +        OPTIONS "-DBUILD_SHARED_LIBS=OFF"
```suggestion
```

This OPTION is not need here. By default, `vcpkg_configure_cmake() `will pass in the appropriate setting for `BUILD_SHARED_LIBS`. Please see this [doc ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#choose-either-static-or-shared-binaries)to learn more about this.

2020-07-06 03:20 UTC, NancyLi1013 commented on ports/libcopp/portfile.cmake
> +        OPTIONS "-DBUILD_SHARED_LIBS=ON"
```suggestion
```
The same as above.

2020-07-06 03:20 UTC, NancyLi1013 commented on ports/libcopp/portfile.cmake
Could you please update `libcopp` as` ${PORT} ` in these codes?
```
file(COPY ${CMAKE_CURRENT_LIST_DIR}/usage DESTINATION ${CURRENT_PACKAGES_DIR}/share/libcopp)
file(COPY ${SOURCE_PATH}/BOOST_LICENSE_1_0.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/libcopp)
```
This line should be removed here.
`file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/libcopp)
`

This might be updated
`file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/libcopp/copyright)`
as
`file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-07-06 03:20 UTC, NancyLi1013 commented on ports/libcopp/usage
Could you please add `vcpkg_cmake_wrapper.cmake` for this port?

2020-07-06 03:32 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
> +if (VCPKG_LIBRARY_LINKAGE EQUAL "static")
Libcoppuse ```BUILD_SHARED_LIBS``` to determine whether to export symbols.

2020-07-06 03:39 UTC, owt5008137 commented on ports/libcopp/usage
Is there any document about ```vcpkg_cmake_wrapper.cmake``` ?

2020-07-06 03:42 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
> +        OPTIONS "-DBUILD_SHARED_LIBS=OFF"
Libcopp use ```BUILD_SHARED_LIBS``` to determine whether to export symbols.

2020-07-06 06:16 UTC, NancyLi1013 commented on ports/libcopp/portfile.cmake
> +        OPTIONS "-DBUILD_SHARED_LIBS=OFF"
Could you please help make it clarify to describe the detail about this? In this case, what do symbols need to be exported?

2020-07-06 06:55 UTC, NancyLi1013 commented on ports/libcopp/usage
Currently, there are no document for this. You can refer to other ports via searching `vcpkg_cmake_wrapper.cmake`. These files are listed in _ports/portName/_ directory.

2020-07-06 07:40 UTC, owt5008137 commented on ports/libcopp/usage
@NancyLi1013 Thanks, I update the release of libcopp, and all the suggestions are updated. Except the ```file(COPY)``` command has no ```RENAME``` parameter and I just replace libcopp with ```${PORT}```

2020-07-06 07:43 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
> +if (VCPKG_LIBRARY_LINKAGE EQUAL "static")
```BUILD_SHARED_LIBS ``` is removed now. Thanks.

2020-07-06 07:44 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
>  include(vcpkg_common_functions)
```include(vcpkg_common_functions)``` is removed, thanks.

2020-07-06 07:44 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
> +        OPTIONS "-DBUILD_SHARED_LIBS=ON"
```OPTIONS "-DBUILD_SHARED_LIBS=ON"``` is removed, thanks.

2020-07-06 09:48 UTC, NancyLi1013 requested changes

2020-07-06 09:48 UTC, NancyLi1013 commented on ports/libcopp/portfile.cmake
> +endif ()
```suggestion
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    DISABLE_PARALLEL_CONFIGURE
    # PREFER_NINJA # Disabled because Ninja does not invoke masm correctly for this project
)
```
The condition `if()` is not not needed. We should just keep it as before.

2020-07-06 09:48 UTC, NancyLi1013 commented on ports/libcopp/portfile.cmake
> +file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
```suggestion
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

2020-07-06 10:26 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
> +endif ()
Sorr, my mistake. Fixed now.

2020-07-06 10:34 UTC, owt5008137 commented on ports/libcopp/portfile.cmake
> +file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
@NancyLi1013 
Using ```file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)```  will lead to this error when running ```vcpkg install libcopp --triplet x64-windows```:

```powershell
PS D:\prebuilt\vcpkg> ./vcpkg install libcopp --triplet x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    libcopp[core]:x64-windows
Starting package 1/1: libcopp:x64-windows
Building package libcopp[core]:x64-windows...
-- Using cached D:/prebuilt/vcpkg/downloads/owt5008137-libcopp-1.3.1.tar.gz
-- Using source at D:/prebuilt/vcpkg/buildtrees/libcopp/src/1.3.1-70ca94026a
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at ports/libcopp/portfile.cmake:21 (file):
  file called with unknown argument "RENAME".
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)


Error: Building package libcopp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libcopp:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
```

And I have checked the [document of cmake](https://cmake.org/cmake/help/v3.18/command/file.html#copy), there is no ```RENAME``` parameter for ```file(COPY)``` . Is there anything I missed?

2020-07-06 19:26 UTC, ras0219-msft commented
Hi @owt5008137, this looks 95% ready to merge!

However, we do not intend `usage` to be the channel for information about how to use static linking, nor for the library's changelog; the purpose of this file is only to handle cases where our built-in heuristics fail.

For information about static linking, we prefer users access our docs[1]. For library changes, we encourage users to visit the homepage.

Here is the diff that brings this PR to 100% -- I was unable to push it to this PR because you've unchecked the "allow edits" box:
```diff
diff --git a/ports/libcopp/CONTROL b/ports/libcopp/CONTROL
index 415c2a90c..8c9162540 100644
--- a/ports/libcopp/CONTROL
+++ b/ports/libcopp/CONTROL
@@ -1,5 +1,6 @@
 Source: libcopp
 Version: 1.3.1
+Port-Version: 1
 Description: A cross-platfrom coroutine library for C++
 Maintainer: owent <admin@owent.net>
 Homepage: https://libcopp.atframe.work/
diff --git a/ports/libcopp/portfile.cmake b/ports/libcopp/portfile.cmake
index e0e59c5d8..5b6be64bb 100644
--- a/ports/libcopp/portfile.cmake
+++ b/ports/libcopp/portfile.cmake
@@ -6,17 +6,14 @@ vcpkg_from_github(
     HEAD_REF v2
 )
 
-# Use libcopp's own build process, skipping examples and tests
 vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     DISABLE_PARALLEL_CONFIGURE
-    # PREFER_NINJA # Disabled because Ninja does not invoke masm correctly for this project
 )
 
 vcpkg_install_cmake()
 
 file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/share/${PORT})
-file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/usage DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
 file(INSTALL ${SOURCE_PATH}/BOOST_LICENSE_1_0.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
 file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
 
diff --git a/ports/libcopp/usage b/ports/libcopp/usage
deleted file mode 100644
index 6e992196c..000000000
--- a/ports/libcopp/usage
+++ /dev/null
@@ -1,31 +0,0 @@
-The package libcopp provides CMake integration:
-
-    find_package(Libcopp CONFIG REQUIRED)
-    target_link_libraries(main PRIVATE libcopp::cotask)
-    # Or just using copp by target_link_libraries(main PRIVATE libcopp::copp)
-
-If using MSVC, CRT must match the triplet of vcpkg, these codes below may be helpful:
-
-    if (MSVC AND VCPKG_TOOLCHAIN)
-        string(REGEX MATCH "^.*windows-static$" CHECK_VCPKG_TARGET_TRIPLET_RUNTIME ${VCPKG_TARGET_TRIPLET})
-        message(STATUS "CHECK_VCPKG_TARGET_TRIPLET_RUNTIME=${CHECK_VCPKG_TARGET_TRIPLET_RUNTIME}")
-        if(DEFINED ENV{VCPKG_DEFAULT_TRIPLET} AND NOT DEFINED VCPKG_TARGET_TRIPLET)
-            set(VCPKG_TARGET_TRIPLET "$ENV{VCPKG_DEFAULT_TRIPLET}" CACHE STRING "")
-        endif()
-        if (CHECK_VCPKG_TARGET_TRIPLET_RUNTIME)
-            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "")
-            set(CMAKE_MSVC_RUNTIME "/MT$<$<CONFIG:Debug>:d>")
-        else ()
-            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL" CACHE STRING "")
-            set(CMAKE_MSVC_RUNTIME "/MD$<$<CONFIG:Debug>:d>")
-        endif ()
-        target_compile_options(main PRIVATE ${CMAKE_MSVC_RUNTIME})
-    endif ()
-
-BREAK CHANGES & UPGRADE GUIDE FROM 1.2.X
-
-+ Rename ```cotask::task::await``` into ```cotask::task::await_task```
-+ Replace ```cotask::task<TCO_MACRO, TTASK_MACRO>``` with ```cotask::task<TCO_MACRO>``` , we don't allow to custom id allocator now.
-+ Replace ```cotask::core::standard_int_id_allocator<uint64_t>``` with ```copp::util::uint64_id_allocator``` , we don't allow to custom id allocator now.
-+ Require gcc 4.7+, MSVC 14+(Visual Studio 2015)>)
-+ Require cmake 3.12.0 or upper
diff --git a/ports/libcopp/vcpkg-cmake-wrapper.cmake b/ports/libcopp/vcpkg-cmake-wrapper.cmake
deleted file mode 100644
index 175ff8d25..000000000
--- a/ports/libcopp/vcpkg-cmake-wrapper.cmake
+++ /dev/null
@@ -1 +0,0 @@
-_find_package(${ARGS} CONFIG)
\ No newline at end of file
```

2020-07-07 05:01 UTC, owt5008137 commented
> 
> 
> Hi @owt5008137, this looks 95% ready to merge!
> 
> However, we do not intend `usage` to be the channel for information about how to use static linking, nor for the library's changelog; the purpose of this file is only to handle cases where our built-in heuristics fail.
> 
> For information about static linking, we prefer users access our docs[1]. For library changes, we encourage users to visit the homepage.
> 
> Here is the diff that brings this PR to 100% -- I was unable to push it to this PR because you've unchecked the "allow edits" box:
> 
> ```diff
> diff --git a/ports/libcopp/CONTROL b/ports/libcopp/CONTROL
> index 415c2a90c..8c9162540 100644
> --- a/ports/libcopp/CONTROL
> +++ b/ports/libcopp/CONTROL
> @@ -1,5 +1,6 @@
>  Source: libcopp
>  Version: 1.3.1
> +Port-Version: 1
>  Description: A cross-platfrom coroutine library for C++
>  Maintainer: owent <admin@owent.net>
>  Homepage: https://libcopp.atframe.work/
> diff --git a/ports/libcopp/portfile.cmake b/ports/libcopp/portfile.cmake
> index e0e59c5d8..5b6be64bb 100644
> --- a/ports/libcopp/portfile.cmake
> +++ b/ports/libcopp/portfile.cmake
> @@ -6,17 +6,14 @@ vcpkg_from_github(
>      HEAD_REF v2
>  )
>  
> -# Use libcopp's own build process, skipping examples and tests
>  vcpkg_configure_cmake(
>      SOURCE_PATH ${SOURCE_PATH}
>      DISABLE_PARALLEL_CONFIGURE
> -    # PREFER_NINJA # Disabled because Ninja does not invoke masm correctly for this project
>  )
>  
>  vcpkg_install_cmake()
>  
>  file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/share/${PORT})
> -file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/usage DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
>  file(INSTALL ${SOURCE_PATH}/BOOST_LICENSE_1_0.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
>  file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
>  
> diff --git a/ports/libcopp/usage b/ports/libcopp/usage
> deleted file mode 100644
> index 6e992196c..000000000
> --- a/ports/libcopp/usage
> +++ /dev/null
> @@ -1,31 +0,0 @@
> -The package libcopp provides CMake integration:
> -
> -    find_package(Libcopp CONFIG REQUIRED)
> -    target_link_libraries(main PRIVATE libcopp::cotask)
> -    # Or just using copp by target_link_libraries(main PRIVATE libcopp::copp)
> -
> -If using MSVC, CRT must match the triplet of vcpkg, these codes below may be helpful:
> -
> -    if (MSVC AND VCPKG_TOOLCHAIN)
> -        string(REGEX MATCH "^.*windows-static$" CHECK_VCPKG_TARGET_TRIPLET_RUNTIME ${VCPKG_TARGET_TRIPLET})
> -        message(STATUS "CHECK_VCPKG_TARGET_TRIPLET_RUNTIME=${CHECK_VCPKG_TARGET_TRIPLET_RUNTIME}")
> -        if(DEFINED ENV{VCPKG_DEFAULT_TRIPLET} AND NOT DEFINED VCPKG_TARGET_TRIPLET)
> -            set(VCPKG_TARGET_TRIPLET "$ENV{VCPKG_DEFAULT_TRIPLET}" CACHE STRING "")
> -        endif()
> -        if (CHECK_VCPKG_TARGET_TRIPLET_RUNTIME)
> -            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "")
> -            set(CMAKE_MSVC_RUNTIME "/MT$<$<CONFIG:Debug>:d>")
> -        else ()
> -            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL" CACHE STRING "")
> -            set(CMAKE_MSVC_RUNTIME "/MD$<$<CONFIG:Debug>:d>")
> -        endif ()
> -        target_compile_options(main PRIVATE ${CMAKE_MSVC_RUNTIME})
> -    endif ()
> -
> -BREAK CHANGES & UPGRADE GUIDE FROM 1.2.X
> -
> -+ Rename ```cotask::task::await``` into ```cotask::task::await_task```
> -+ Replace ```cotask::task<TCO_MACRO, TTASK_MACRO>``` with ```cotask::task<TCO_MACRO>``` , we don't allow to custom id allocator now.
> -+ Replace ```cotask::core::standard_int_id_allocator<uint64_t>``` with ```copp::util::uint64_id_allocator``` , we don't allow to custom id allocator now.
> -+ Require gcc 4.7+, MSVC 14+(Visual Studio 2015)>)
> -+ Require cmake 3.12.0 or upper
> diff --git a/ports/libcopp/vcpkg-cmake-wrapper.cmake b/ports/libcopp/vcpkg-cmake-wrapper.cmake
> deleted file mode 100644
> index 175ff8d25..000000000
> --- a/ports/libcopp/vcpkg-cmake-wrapper.cmake
> +++ /dev/null
> @@ -1 +0,0 @@
> -_find_package(${ARGS} CONFIG)
> \ No newline at end of file
> ```

Merged. I can not see the "allow edits" box on this PR page. 
![图片](https://user-images.githubusercontent.com/1209475/86714372-addc4780-c051-11ea-8512-8e19e480e9b3.png)
There is nothing here, while the [document](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) shows it should be.

2020-07-07 09:07 UTC, NancyLi1013 approved these changes

2020-07-07 20:47 UTC, merged

2020-07-07 20:47 UTC, ras0219-msft commented
Thanks for the update!