[fltk] Force static library due to global variables. Fix CMake Targets.
microsoft/vcpkg pull request #12273
Opened 2020-07-06 01:55 UTC by ras0219

See title.

2020-07-10 19:37 UTC, strega-nil requested changes
That's the only thing I see :)

2020-07-10 19:37 UTC, strega-nil commented on ports/fltk/CONTROL
> +Version: 1.3.5-3
```suggestion
Version: 1.3.5
Port-Version: 3
```

2020-07-16 07:25 UTC, PhoebeHui commented
The bin folder need to remove.

Failures on OSX:

-- Performing post-build validation
There should be no bin\ directory in a static build, but /Users/vagrant/Data/packages/fltk_x64-osx/bin is present.
There should be no debug\bin\ directory in a static build, but /Users/vagrant/Data/packages/fltk_x64-osx/debug/bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

Found 1 error(s). Please correct the portfile:
    /Volumes/data/work/1/s/ports/fltk/portfile.cmake
-- Performing post-build validation done
Error: Building package fltk:x64-osx failed with: POST_BUILD_CHECKS_FAILED
Elapsed time for package fltk:x64-osx: 1.072 min

2020-07-16 07:32 UTC, PhoebeHui commented on ports/fltk/portfile.cmake
> +
```suggestion

if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    file(REMOVE_RECURSE
        ${CURRENT_PACKAGES_DIR}/debug/bin
        ${CURRENT_PACKAGES_DIR}/bin
    )
endif()
```

2020-07-16 09:49 UTC, PhoebeHui approved these changes

2020-07-17 06:04 UTC, LilyWangL approved these changes

2020-07-17 18:33 UTC, strega-nil approved these changes

2020-07-28 21:12 UTC, strega-nil commented
/azp run

2020-07-31 05:41 UTC, merged