[imgui] Split bindings to multiple features
microsoft/vcpkg pull request #12329
Opened 2020-07-08 17:51 UTC by RT222

See #12250.

I tested all the features on x86-windows, x64-windows, x64-windows-static and x64-linux triplets. Everything build fine except:
- dx12-binding on x86-windows. There's an issue opened about it here : https://github.com/ocornut/imgui/pull/2406
- allegro5-binding on x64-linux, because the current allegro5 port fails to build on this platform.

Contrary to the previous port which simply copied the sources to a specific folder, bindings are now compiled with their dependencies. The only exception is Marmelade, because there's no port available for it yet.

Unfortunately, I can't test the OSX and metal bindings. If someone using this platform could test it, it would be very much appreciated. :)

2020-07-09 03:20 UTC, JackBoosY commented
Imgui officials tend to set this port as header only and export it as an interface port.
Therefore:
1. many ports that depend on it use its `.h` and `.cpp` directly to use its functions.
2. imgui did not declare any symbols to be exported in the header file.

So we have to be more careful about imgui changes.

2020-07-09 22:15 UTC, ras0219-msft requested changes

2020-07-09 22:15 UTC, ras0219-msft commented on ports/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
I think these are in the wrong directories :)

2020-07-10 21:06 UTC, RT222 commented on ports/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Whoops, I was probably more tired than I thought when I made this PR. Fixed.

2020-07-13 02:21 UTC, JackBoosY requested changes

2020-07-13 02:21 UTC, JackBoosY commented on ports/imgui/CONTROL
> +Version: 1.77-1
```suggestion
Version: 1.77
Port-Version: 1
```

2020-07-13 02:23 UTC, JackBoosY requested changes

2020-07-13 02:23 UTC, JackBoosY commented on ports/imgui/CMakeLists.txt
> +	target_sources(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/examples/imgui_impl_allegro5.cpp)
I'm not sure if these sample source files should be added to the imgui target.

2020-07-15 23:07 UTC, ras0219-msft commented
>I'm not sure if these sample source files should be added to the imgui target.

Due to the somewhat unique structure of `imgui`, I think this is the best approach we have. The other reasonable alternative would be to turn every backend into a separate port + separate static lib, which would nicely enable adding and removing backends without recompiling everyone using imgui, but that is a lot of boilerplate for something mostly equivalent.

2020-07-15 23:07 UTC, merged

2020-07-15 23:07 UTC, ras0219-msft commented
LGTM, thanks for the awesome improvement!