[libyuv] Fix static build issue
microsoft/vcpkg pull request #12338
Opened 2020-07-09 08:36 UTC by PhoebeHui

Fixes https://github.com/microsoft/vcpkg/issues/12335

Changes:
1. The logic 'if (JPEG_FOUND AND BUILD_SHARED_LIBS)' change skips an entire block which defines loading dependent jpeg libraries In PR https://github.com/microsoft/vcpkg/pull/8769.  update it in the patch.
2. Export 'HAVE_JPEG' definition by target_compile_definitions(xxx PUBLIC HAVE_JPEG)
3. Remove 'REQUIRED' in find_dependency in config files.

Test pass with x64-windows-static:

CMakeLists.txt file:
cmake_minimum_required(VERSION 3.0)
project(example)
find_package(libyuv CONFIG REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example PRIVATE yuv)

example.cpp file:
#include <iostream>
#include <libyuv/convert.h>

int main(int argc, char *argv[])
{
    int foo = libyuv::MJPGSize(nullptr, 42, nullptr, nullptr);
      return 0;
}

2020-07-09 09:32 UTC, JackBoosY approved these changes

2020-07-09 19:32 UTC, ras0219-msft requested changes

2020-07-09 19:32 UTC, ras0219-msft commented on ports/libyuv/fix-build-type.patch
> ++    target_compile_definitions(${ly_lib_shared} PUBLIC HAVE_JPEG)
This definition should be `PRIVATE`

2020-07-10 00:04 UTC, strega-nil commented on ports/libyuv/fix-build-type.patch
> ++    target_compile_definitions(${ly_lib_shared} PUBLIC HAVE_JPEG)
I don't think so; see `libyuv/util/psnr.h`:

```cxx
#if !defined(HAVE_JPEG)
// Computer Sum of Squared Error (SSE).
// Pass this to ComputePSNR for final result.
double ComputeSumSquareError(const uint8_t* src_a,
                             const uint8_t* src_b,
                             int count);
#endif
```

so I'm pretty sure that it needs to be public.

2020-07-10 02:38 UTC, JackBoosY commented on ports/libyuv/fix-build-type.patch
> ++    target_compile_definitions(${ly_lib_shared} PUBLIC HAVE_JPEG)
We must change `#ifdef HAVE_JPEG` to `#if 1`, because if this port is used in msvc project, the macro `HAVE_JPEG` will not be set.

2020-07-10 03:15 UTC, PhoebeHui commented on ports/libyuv/fix-build-type.patch
> ++    target_compile_definitions(${ly_lib_shared} PUBLIC HAVE_JPEG)
Updated.

2020-07-10 03:21 UTC, PhoebeHui commented on ports/libyuv/fix-build-type.patch
> ++    target_compile_definitions(${ly_lib_shared} PUBLIC HAVE_JPEG)
Thanks for your review! I remember there are two reasons that we don't export the definition as public:
1. If we export the definition as public, then when some ports depends on it, the definition would cause the it defined in the dependency port when build it.
2. As Jack said, when using it with msbuild, the macro would not defined.

2020-07-10 19:31 UTC, strega-nil approved these changes

2020-07-15 23:09 UTC, merged

2020-07-15 23:09 UTC, ras0219-msft commented
Thanks!