Adding DataFrame library
microsoft/vcpkg pull request #12364
Opened 2020-07-10 18:40 UTC by remz1337

This is a PR to add the [DataFrame](https://github.com/hosseinmoein/DataFrame) library.

I have followed the examples to create this port, but I still can't get it build successfully with vcpkg, so I would appreciate some support. The library compiles fine on both Linux and Windows when done manually.

Thank you

2020-07-13 09:14 UTC, LilyWangL requested changes

2020-07-13 09:14 UTC, LilyWangL commented on ports/dataframe/CONTROL
> +Version:  1.10.0
Can you please add the Homepage for this port in the CONTROL file?
```
Homepage: https://github.com/hosseinmoein/DataFrame
```

2020-07-13 13:13 UTC, remz1337 commented on ports/dataframe/CONTROL
> +Version:  1.10.0
Done! Thank you

2020-07-14 02:59 UTC, LilyWangL commented
@remz1337 Thanks for your PR. Now `dataframe` build failed on CI, you can click this URL and download the error log: https://dev.azure.com/vcpkg/public/_build/results?buildId=40160&view=artifacts&type=publishedArtifacts

2020-07-14 16:58 UTC, remz1337 commented
@LilyWangL I get the same logs when I try to build locally with vcpkg. As I described earlier, I don't understand why it's failling with vcpkg since I can build the library with standard cmake commands. I'm seeing some compiler warnings, but I don't understand why the standard cmake build still gets through while building with vcpkg fails.

I created this draft PR to get some help to resolve this.

Thanks

2020-10-29 09:04 UTC, LilyWangL commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2020-10-29 09:04 UTC, closed without merging