Update wpilib port to 2020.3.2
microsoft/vcpkg pull request #12373
Opened 2020-07-11 04:38 UTC by ThadHouse

Latest 2020 release. No updates to baseline or supported triplets since last commits

2020-07-13 10:29 UTC, NancyLi1013 requested changes

2020-07-13 10:29 UTC, NancyLi1013 commented on ports/wpilib/CONTROL
>  Description: WPILib is the software library package for the FIRST Robotics Competition. The core install includes wpiutil, a common utilies library, and ntcore, the base NetworkTables library.
We need to add `Supports `field here if this port doesn't support `uwp`.

2020-07-13 10:29 UTC, NancyLi1013 commented on ports/wpilib/portfile.cmake
>  set(WITHOUT_JAVA ON)
Could you please use `vcpkg_check_features()` to handle these features for `wpilib`?

2020-07-13 10:29 UTC, NancyLi1013 commented on ports/wpilib/portfile.cmake
>  endif()
Could you please update this
`file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/wpilib RENAME copyright)`
as
`file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-07-13 10:31 UTC, NancyLi1013 commented
Hi @ThadHouse 
Thanks for this PR.
Have you tested these features? Please make sure that they can work on x64-windows, x86-windows, x64-windows-static and x64-linux triplets.

2020-08-04 07:35 UTC, NancyLi1013 commented
@ThadHouse 
Is work still being done for this PR?

2020-08-04 13:47 UTC, ThadHouse commented
Yes, I'll fix up the comments this week

2020-08-09 15:33 UTC, ThadHouse commented
Fixed all the review comments.

2020-08-10 02:02 UTC, NancyLi1013 commented
@ThadHouse 
Thanks for your update.

Have you tested these features?

2020-08-10 03:02 UTC, ThadHouse commented
Yes I have. Everything can install independently properly.

2020-08-13 03:14 UTC, NancyLi1013 approved these changes

2020-08-13 20:34 UTC, merged