[semver] Add new port
microsoft/vcpkg pull request #12406
Opened 2020-07-13 19:34 UTC by Vennor

Adding new single file header-only library.

2020-07-13 20:08 UTC, ras0219-msft requested changes
Thanks for the PR!

Because this name is quite generic and the library doesn't seem broadly established, a more specialized name would be preferable (perhaps `Neargye-semver`).

Additionally, `semver.hpp` is somewhat likely to conflict with existing source code that might have a private `"semver.hpp"`; please consider moving the header to `include/neargye/semver.hpp`

Another library with an extremely similar name: https://github.com/h2non/semver.c

2020-07-14 13:23 UTC, Vennor commented
Thanks for the comment. I updated the pull request.

2020-07-14 15:42 UTC, ras0219-msft approved these changes

2020-07-16 06:05 UTC, PhoebeHui approved these changes

2020-07-28 21:18 UTC, merged