Improve format check failure message
microsoft/vcpkg pull request #12460
Opened 2020-07-17 06:31 UTC by JackBoosY

Related: #12423.

2020-07-17 18:36 UTC, strega-nil commented
I really want to print the diff in a readable way; I think `Write-Host` the diff, then throw might work?

2020-07-18 02:14 UTC, JackBoosY commented
@strega-nil In fact,  the difference is printed in the error message now,  but it hard to see. 
The best way is commit the correct file to archive automatically,  then contributor can download it and commit to branch,  but it out of my scope.

2020-07-20 21:05 UTC, strega-nil approved these changes

2020-07-21 22:36 UTC, ras0219-msft requested changes

2020-07-21 22:36 UTC, ras0219-msft commented on scripts/azure-pipelines/windows/Check-CxxFormatting.ps1
> -        $msg += "    $changedFiles"
Displaying the list of files that need to be formatted is still very useful so you know which files to open in the IDE / run the CLI on.

2020-07-30 04:12 UTC, merged