Dev/jack/10099
microsoft/vcpkg pull request #12515
Opened 2020-07-21 07:17 UTC by JackBoosY

Finding ffmpeg components in Pangolin's built-in `FindFFmpeg.cmake` is not complete, which causes the build failure in UNIX.

Thanks @Wkkkkk!

2020-07-23 03:14 UTC, PhoebeHui requested changes

2020-07-23 03:14 UTC, PhoebeHui commented on scripts/ci.baseline.txt
>  pangolin:x64-windows-static=fail
Could you also add the this to supports and remove it in ci.baseline.txt?

2020-08-05 03:04 UTC, PhoebeHui approved these changes

2020-08-05 22:38 UTC, strega-nil requested changes
That's the only thing I see.

2020-08-05 22:38 UTC, strega-nil commented on ports/pangolin/CONTROL
> +Supports: !(uwp|osx)&!(windows&static)
This is a very confusing supports paragraph. Could we rewrite this as:

```suggestion
Supports: !uwp & !osx & !(windows&static)
```

2020-08-07 00:11 UTC, strega-nil commented
/azp run

2020-08-07 05:14 UTC, merged