[VCPKG] Add feature mirror
microsoft/vcpkg pull request #12532
Opened 2020-07-22 07:38 UTC by JackBoosY

This PR will add the use of mirror download address function, allow users to set the mirror address of the port and tool through parameters when building vcpkg to reduce download time.

- [x] Modify build scripts
- [ ] Add vcpkg code
- [ ] Test
- [ ] Document

2020-07-23 21:39 UTC, BillyONeal commented
Thanks, this is great 👍 

I would like to see the control being done with an environment variable and/or command line option rather than compiling it into the tool with bootstrap, because once we start doing binary releases that won't work anymore.

2020-07-24 07:44 UTC, JackBoosY commented on toolsrc/src/vcpkg/base/downloads.cpp
> -    static void winhttp_download_file(Files::Filesystem& fs,
Since `winhttp.h` has conflict with `wininet.h`, I split this function into two files.

2020-07-27 02:55 UTC, JackBoosY commented
```
One or more errors occurred. (One or more errors occurred. (Access to the path 'C:\agent\_work\1\s\downloads\tools\msys2\msys64\usr\bin\msys-gcrypt-20.dll' is denied.)) (One or more errors occurred. (Access to the path 'C:\agent\_work\1\s\downloads\tools\msys2\msys64\usr\bin\msys-hogweed-4.dll' is denied.)) (One or more errors occurred. (Access to the path 'C:\agent\_work\1\s\downloads\tools\msys2\msys64\usr\bin\dirmngr.exe' is denied.)) (Access to the path 'C:\agent\_work\1\s\downloads\tools\msys2\msys64\usr\bin\msys-gcrypt-20.dll' is denied.) (Access to the path 'C:\agent\_work\1\s\downloads\tools\msys2\msys64\usr\bin\msys-hogweed-4.dll' is denied.) (Access to the path 'C:\agent\_work\1\s\downloads\tools\msys2\msys64\usr\bin\dirmngr.exe' is denied.)
```

2020-08-19 07:20 UTC, JackBoosY commented
Disaster merger. OMG.

2020-08-25 08:36 UTC, JackBoosY commented
qt5-tools:
```
Qt5Guid.lib(qrhid3d11.obj) : error LNK2001: unresolved external symbol IID_IDXGIFactory2
Qt5Guid.lib(qrhid3d11.obj) : error LNK2001: unresolved external symbol IID_ID3D11DeviceContext1
Qt5Guid.lib(qrhid3d11.obj) : error LNK2001: unresolved external symbol IID_ID3DUserDefinedAnnotation
```

2020-08-25 09:04 UTC, JackBoosY commented
```
Building package clapack[core]:x64-osx... done
Installing package clapack[core]:x64-osx...
The following files are already installed in /Users/vagrant/Data/installed/x64-osx and are in conflict with clapack:x64-osx

Installed by lapack-reference:x64-osx
    lib/liblapack.a
```

2020-08-26 03:09 UTC, JackBoosY commented
> qt5-tools:
> 
> ```
> Qt5Guid.lib(qrhid3d11.obj) : error LNK2001: unresolved external symbol IID_IDXGIFactory2
> Qt5Guid.lib(qrhid3d11.obj) : error LNK2001: unresolved external symbol IID_ID3D11DeviceContext1
> Qt5Guid.lib(qrhid3d11.obj) : error LNK2001: unresolved external symbol IID_ID3DUserDefinedAnnotation
> ```

@Neumann-A It seems that qt5-tools forgot to link to dxguid.lib?

2020-09-01 04:42 UTC, ras0219 commented on scripts/cmake/vcpkg_download_distfile.cmake
> +        set(vcpkg_download_distfile_URLS "ftp://$ENV{VCPKG_EXPERIMENTAL_MIRROR_URL}/${vcpkg_download_distfile_SHA512}")
This should do something reasonable in the `vcpkg_download_distfile_SKIP_SHA512` case

2020-09-01 04:52 UTC, BillyONeal requested changes
I will merge this for you after https://github.com/microsoft/vcpkg/pull/13038 lands; they both touch a lot of the same stuff but this one is a bit smaller so merging will be less painful.

Do we have a spec for this feature? As I originally understood it this was the ability to redirect our download attempts somewhere else; this "crawl" attempt thing is something very different. I don't know if that changed from when I looked last or if I was just blind due to being delirious trying to ship jthread in STL land.

2020-09-01 04:52 UTC, BillyONeal commented on toolsrc/include/vcpkg/vcpkgcmdarguments.h
> +        constexpr static StringLiteral VCPKG_EXPERIMENTAL_MIRROR_URL = "VCPKG_EXPERIMENTAL_MIRROR_URL";
I don't think we should name the variable EXPERIMENTAL because someday it won't be and there's no reason to force everyone to edit their scripts then?

2020-09-01 04:52 UTC, BillyONeal commented on toolsrc/src/vcpkg/vcpkgpaths.cpp
> +        vcpkg_use_mirror = args.use_mirror.value_or(args.download_mirror_url != nullptr);
It seems like we don't need to store a separate bool for this because we're already smashing it down to vcpkg_mirror_url.

2020-09-01 04:52 UTC, BillyONeal commented on toolsrc/src/vcpkg/commands.mirror.cpp
> +            // The VS2015 standard library requires comparison operators of T and U
No reason to not just always provide then though, they don't hurt anything.

2020-09-01 04:52 UTC, BillyONeal commented on toolsrc/src/vcpkg/commands.mirror.cpp
> +        std::sort(intersection.begin(), intersection.end(), [](const file_pack& lhs, const file_pack& rhs) {
This sort does nothing; `set_intersection`'s output is sorted.

2020-09-01 04:52 UTC, BillyONeal commented on toolsrc/src/vcpkg/commands.mirror.cpp
> +#include <vcpkg/base/files.h>
Is this file install.cpp with a few things changed? That seems like a recipe for us not making the right changes in both places over time. I think if you want this feature it needs to be plumbed through the existing infrastructure, not a copy paste of it.

2020-09-01 04:55 UTC, ras0219 requested changes

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/commands.cpp
> +                                                                               {"mirror", &mirror}};
This should be an `x-` command.

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/include/vcpkg/vcpkgcmdarguments.h
> +        constexpr static StringLiteral VCPKG_EXPERIMENTAL_MIRROR_URL = "VCPKG_EXPERIMENTAL_MIRROR_URL";
We conventionally use lowercase here
```suggestion
        constexpr static StringLiteral VCPKG_EXPERIMENTAL_MIRROR_URL = "x-mirror-url";
```

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/commands.mirror.cpp
> +    CMakeUsageInfo get_cmake_usage(const BinaryParagraph& bpgh, const VcpkgPaths& paths)
This code should not be duplicated; use the existing copies in `vcpkg/install.h`

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/commands.mirror.cpp
> +    static constexpr StringLiteral OPTION_XUNIT = "x-xunit";
This is unlikely to be relevant for this command; it should be removed.

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/commands.mirror.cpp
> +#include <vcpkg/base/files.h>
This file has a _lot_ of copy/paste from `install.cpp` and should be reworked to focus on what this specific command requires.

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/commands.cpp
> +                                                                               {"mirror", &mirror}};
```suggestion
                                                                               {"x-mirror", &mirror}};
```

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/base/downloads.cpp
> +                       const bool use_mirror,
This parameter should not be needed -- instead, `url` should be examined via something like `Strings::starts_with()` to detect ftp vs https and dispatch using that.

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/tools.cpp
> +            url += paths.vcpkg_mirror_url;
If `vcpkg_mirror_url` is changed to include the protocol, this would enable https mirrors as well and generally be more robust

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/src/vcpkg/tools.cpp
> +            url += paths.vcpkg_mirror_url;
Additionally, this should arguably be moved into download_file() so that every case across vcpkg uses it.

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/include/vcpkg/commands.mirror.h
> +#pragma once
This file needs to be reworked to only focus on the mirror command instead of being a copy of `install.h`.

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/include/vcpkg/base/downloads.h
> +    extern void ftp_download_file(Files::Filesystem& fs,
```suggestion
    void ftp_download_file(Files::Filesystem& fs,
```

2020-09-01 04:55 UTC, ras0219 commented on toolsrc/include/vcpkg/base/downloads.h
> +    extern void winhttp_download_file(Files::Filesystem& fs,
```suggestion
    void winhttp_download_file(Files::Filesystem& fs,
```

2020-09-01 04:57 UTC, ras0219 commented on toolsrc/include/vcpkg/vcpkgcmdarguments.h
> +        constexpr static StringLiteral VCPKG_EXPERIMENTAL_MIRROR_URL = "VCPKG_EXPERIMENTAL_MIRROR_URL";
OTOH we can continue respecting the experimental form for backwards compatibility and this makes it clear for users that they are using an unsupported feature. Alternatively, the tool could emit a big yelllow warning at the top every time it's run with this env var set.

2020-09-01 06:30 UTC, JackBoosY commented on toolsrc/include/vcpkg/vcpkgcmdarguments.h
> +        constexpr static StringLiteral VCPKG_EXPERIMENTAL_MIRROR_URL = "VCPKG_EXPERIMENTAL_MIRROR_URL";
The environment variable name is set here. Is this correct?

2020-09-01 06:36 UTC, JackBoosY commented on scripts/cmake/vcpkg_download_distfile.cmake
> +        set(vcpkg_download_distfile_URLS "ftp://$ENV{VCPKG_EXPERIMENTAL_MIRROR_URL}/${vcpkg_download_distfile_SHA512}")
Without SHA512, `vcpkg_download_distfile` cannot splice the download URL.

2020-09-01 07:23 UTC, JackBoosY commented on toolsrc/src/vcpkg/tools.cpp
> +            url += paths.vcpkg_mirror_url;
I am currently unable to change it to https, can we make these changes later?

2020-09-01 08:21 UTC, JackBoosY commented
Since the source package downloaded using x-mirror will be automatically renamed to sha512 value, do we need to provide the list of downloaded source packages to the mirror maintainer?

2020-09-11 02:12 UTC, JackBoosY commented
@ras0219 @ras0219-msft Please review again.

2020-10-09 07:00 UTC, closed without merging

2021-05-07 16:50 UTC, soroshsabz commented
@JackBoosY  why this PR closed? Where this functionality exist?

Thanks

2021-05-07 17:06 UTC, BillyONeal commented
> @JackBoosY why this PR closed? Where this functionality exist?
> 
> Thanks

It needs to be replayed over in vcpkg-tool instead at a minimum

2021-05-08 02:52 UTC, JackBoosY commented
This PR was replaced by https://github.com/microsoft/vcpkg/pull/13639.