[winpcap] Remove the keyword 'inline' macro
microsoft/vcpkg pull request #12542
Opened 2020-07-23 07:33 UTC by PhoebeHui

Closes https://github.com/microsoft/vcpkg/issues/10730

winpcap's header file pcap-stdinc.h contains '#define inline _inline', which cause the following failures when use the headers on vs2019. Remove the macro for unblocking the usage.

 fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "inline". Enable warning C4005 to find the forbidden define.

2020-07-28 00:45 UTC, ras0219-msft requested changes

2020-07-28 00:45 UTC, ras0219-msft commented on ports/winpcap/portfile.cmake
> +vcpkg_replace_string(${CURRENT_PACKAGES_DIR}/include/pcap-stdinc.h "#define inline __inline" "/* #define inline __inline */")
This macro may still be required in C, in which case it should be
```suggestion
vcpkg_replace_string(${CURRENT_PACKAGES_DIR}/include/pcap-stdinc.h "#define inline __inline" "#ifndef __cplusplus\n#define inline __inline\n#endif")
```

2020-07-28 01:23 UTC, PhoebeHui commented on ports/winpcap/portfile.cmake
> +vcpkg_replace_string(${CURRENT_PACKAGES_DIR}/include/pcap-stdinc.h "#define inline __inline" "/* #define inline __inline */")
Updated, thanks!

2020-07-28 01:24 UTC, PhoebeHui commented on ports/winpcap/portfile.cmake
> +vcpkg_replace_string(${CURRENT_PACKAGES_DIR}/include/pcap-stdinc.h "#define inline __inline" "/* #define inline __inline */")
Updated, thanks!

2020-07-31 05:34 UTC, JackBoosY approved these changes

2020-07-31 05:45 UTC, merged