[geogram] update to 1.7.5
microsoft/vcpkg pull request #12562
Opened 2020-07-24 14:21 UTC by dsmtE

Update geogram from 16.9 to 1.7.5

2020-07-27 03:20 UTC, NancyLi1013 requested changes

2020-07-27 03:20 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
>  include(vcpkg_common_functions)
```suggestion
```
This function is no longer needed. Could you please remove it?

2020-07-27 03:20 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
```
set(GEOGRAM_WITH_GRAPHICS OFF)
if("graphics" IN_LIST FEATURES)
    set(GEOGRAM_WITH_GRAPHICS ON)
endif()
```
Could you please use `vcpkg_check_features() `to handle feature?

2020-07-27 03:20 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
Could you please use `VCPKG_TARGET_IS_WINDOWS`, `VCPKG_TARGET_IS_LINUX`, `VCPKG_TARGET_IS_OSX`, `VCPKG_TARGET_IS_UWP `to judge platforms instead of via `VCPKG_CMAKE_SYSTEM_NAME`?

2020-07-27 03:20 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
```
file(READ ${CURRENT_PACKAGES_DIR}/share/geogram/GeogramTargets.cmake TARGET_CONFIG)
string(REPLACE [[INTERFACE_INCLUDE_DIRECTORIES "/src/lib;${_IMPORT_PREFIX}/include"]]
               [[INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"]] TARGET_CONFIG "${TARGET_CONFIG}")
file(WRITE ${CURRENT_PACKAGES_DIR}/share/geogram/GeogramTargets.cmake "${TARGET_CONFIG}")
```
Could you please use `vcpkg_replace_string() `to replace strings in a file?

2020-07-27 03:20 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
Could you please update 

```
file(COPY ${SOURCE_PATH}/doc/devkit/license.dox DESTINATION ${CURRENT_PACKAGES_DIR}/share/geogram)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/geogram/license.dox ${CURRENT_PACKAGES_DIR}/share/geogram/copyright)
```
as

`file(INSTALL ${SOURCE_PATH}/doc/devkit/license.dox DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`
?

2020-07-29 01:54 UTC, NancyLi1013 commented
/azp run

2020-07-29 06:27 UTC, NancyLi1013 requested changes

2020-07-29 06:27 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
> +        "graphics" GEOGRAM_WITH_GRAPHICS
```suggestion
    FEATURES
    "graphics" GEOGRAM_WITH_GRAPHICS
```

2020-07-29 06:27 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
>  include(vcpkg_common_functions)
This line is still not removed now.

2020-07-31 06:55 UTC, NancyLi1013 commented on ports/geogram/portfile.cmake
>      URLS "https://gforge.inria.fr/frs/download.php/file/37779/geogram_${GEOGRAM_VERSION}.tar.gz"
Does the `SHA512 `for this version not need to updated here?

2020-08-04 09:17 UTC, dsmtE commented on ports/geogram/portfile.cmake
>      URLS "https://gforge.inria.fr/frs/download.php/file/37779/geogram_${GEOGRAM_VERSION}.tar.gz"
Indeed, it's a big mistake, after verification there was an error in the link and in the SHA512 signature.
Updated, in https://github.com/microsoft/vcpkg/pull/12562/commits/54529959e4750228d56f7d4644fcd81596f2eb35.

2020-08-05 01:55 UTC, NancyLi1013 approved these changes

2020-08-05 01:56 UTC, NancyLi1013 commented
Hi @dsmtE 
Thanks for this PR.

Have you tested the feature? Does it work well?

2020-08-05 09:06 UTC, dsmtE commented
HI @NancyLi1013,
I installed geogram in 1.7.5, it works well for what I need. However, I didn't test all the features and new features added by the update.

2020-08-07 08:41 UTC, NancyLi1013 commented
Hi @dsmtE 

Could you please resolve the conflicts and also test the feature?
 
I can help test it if you don't have enough time to do this.

2020-08-11 08:34 UTC, NancyLi1013 commented
Feature has passed with the following triplets:

- x86-windows
- x64-windows-static

@dsmtE 
Please resolve the conflicts since I have no permission to handle this.

2020-08-12 01:36 UTC, NancyLi1013 requested changes

2020-08-12 01:36 UTC, NancyLi1013 commented on ports/geogram/CONTROL
> +Port-Version: 1
```suggestion
```
Since this is a new update, there is no need to add this.

2020-08-13 01:48 UTC, NancyLi1013 approved these changes

2020-08-14 17:25 UTC, merged