[libmariadb] Include bundled zlib and openssl
microsoft/vcpkg pull request #12669
Opened 2020-07-31 14:01 UTC by arves100

This pull request adds using vcpkg's openssl and zlib with libmariadb.

The first one fixes autolink issues when linking agains python27 or libpng (due to the fact that both inflate functions are autolinked with zlib and libmariadb)
The second change enables libmariadb to use SSL functions.

2020-08-03 03:16 UTC, JackBoosY commented
Please sign CLA first.

2020-08-03 11:44 UTC, arves100 commented
Signed

2020-08-04 09:13 UTC, JackBoosY commented
pbc regression will be fixed in #12732

2020-08-04 09:14 UTC, JackBoosY requested changes

2020-08-04 09:14 UTC, JackBoosY commented on ports/libmariadb/portfile.cmake
> +		-DWITH_EXTERNAL_ZLIB=${WITH_ZLIB}
```suggestion
        -DWITH_EXTERNAL_ZLIB=${WITH_ZLIB}
```

2020-08-04 09:14 UTC, JackBoosY requested changes

2020-08-04 09:14 UTC, JackBoosY commented on ports/libmariadb/CONTROL
>  Version: 3.1.7-1
```suggestion
Version: 3.1.7
Port-Version: 2
```

2020-08-04 09:17 UTC, JackBoosY requested changes

2020-08-04 09:17 UTC, JackBoosY commented on ports/libmariadb/portfile.cmake
> +endif()
```suggestion
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    zlib WITH_EXTERNAL_ZLIB
    openssl WITH_SSL
)
```

2020-08-04 09:17 UTC, JackBoosY commented on ports/libmariadb/portfile.cmake
>      OPTIONS
```suggestion
    OPTIONS
        ${FEATURE_OPTIONS}
```

2020-08-04 09:17 UTC, JackBoosY commented on ports/libmariadb/portfile.cmake
> +        -DWITH_EXTERNAL_ZLIB=${WITH_ZLIB}
```suggestion
        -DWITH_CURL=OFF
```

2020-08-04 09:18 UTC, JackBoosY approved these changes

2020-08-05 21:03 UTC, merged