[libigl] fix imgui feature
microsoft/vcpkg pull request #12691
Opened 2020-08-02 04:59 UTC by strega-nil

Fixes #12442

2020-08-02 05:00 UTC, strega-nil commented
cc @StarGate-One, could you try this out?

2020-08-02 06:44 UTC, c72578 commented on ports/libigl/portfile.cmake
>      message(FATAL_ERROR "Feature imgui does not support static build currentlly")
Typo in "currently":
`Feature imgui does not support static build currentlly`
->
`Feature imgui does not currently support static build`

2020-08-02 06:44 UTC, c72578 commented on ports/libigl/portfile.cmake
> +if ("imgui" IN_LIST FEATURES AND NOT VCPKG_LIBRARY_LINKAGE STREQUAL static)
Why `NOT` ... `static` here?

2020-08-02 14:04 UTC, strega-nil commented on ports/libigl/portfile.cmake
> +if ("imgui" IN_LIST FEATURES AND NOT VCPKG_LIBRARY_LINKAGE STREQUAL static)
Because thats the intended check from the original PR, afaict it was a typo.

2020-08-02 14:05 UTC, strega-nil commented on ports/libigl/portfile.cmake
>      message(FATAL_ERROR "Feature imgui does not support static build currentlly")
oh yeah, I should probably fix this message as well.

2020-08-02 14:22 UTC, StarGate-One commented
@strega-nil fyi I will check when I can, weather issues here in S Florida ;)



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: nicole mazzuca <notifications@github.com>
Date: 8/2/20 10:05 (GMT-05:00)
To: microsoft/vcpkg <vcpkg@noreply.github.com>
Cc: StarGate-One <StarGate_One@outlook.com>, Mention <mention@noreply.github.com>
Subject: Re: [microsoft/vcpkg] [libigl] fix imgui feature (#12691)


@strega-nil commented on this pull request.

________________________________

In ports/libigl/portfile.cmake<https://github.com/microsoft/vcpkg/pull/12691#discussion_r464082140>:

> @@ -16,7 +16,7 @@ if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
     set(LIBIGL_BUILD_STATIC ON)
 endif()

-if ("imgui" IN_LIST FEATURES AND VCPKG_LIBRARY_LINKAGE STREQUAL static)
+if ("imgui" IN_LIST FEATURES AND NOT VCPKG_LIBRARY_LINKAGE STREQUAL static)
     # Remove this after add port libigl-imgui
     message(FATAL_ERROR "Feature imgui does not support static build currentlly")


oh yeah, I should probably fix this message as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/microsoft/vcpkg/pull/12691#discussion_r464082140>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQJBJQLX6UNCQCUJXJXPUG3R6VXB5ANCNFSM4PSK3CEQ>.

2020-08-02 18:58 UTC, c72578 commented on ports/libigl/portfile.cmake
> +if ("imgui" IN_LIST FEATURES AND NOT VCPKG_LIBRARY_LINKAGE STREQUAL static)
OK, the message needed an update too. Now it is clear.

2020-08-03 02:26 UTC, JackBoosY requested changes
Please bump the `Port-Version` to 1.

2020-08-03 17:33 UTC, StarGate-One commented
@strega-nil cc: @JackBoosY 
I tried the changes made in the `CONTROL` and `portfile.cmake` for libigl, making sure to include feature imgui and making sure the [vcpkg-root]\buildtrees\libigl directory/folder was deleted before starting.
It failed as follows:

**CONSOLE output**
`.\vcpkg.exe install libigl[core,glfw,imgui,opengl,xml]:x64-windows --editable`
`Starting package 5/6: libigl:x64-windows`
`Building package libigl[core,glfw,imgui,opengl,xml]:x64-windows...`
`-- Note: libigl only supports static library linkage. Building static library.`
`-- Using cached D:/Git/vcpkg.downloads/libigl-libigl-3cb4894eaf8ea4610467189ca292be349425d44b.tar.gz`
`-- Extracting source D:/Git/vcpkg.downloads/libigl-libigl-3cb4894eaf8ea4610467189ca292be349425d44b.tar.gz`
`-- Applying patch fix-dependency.patch`
`-- Using source at D:/Git/vs2019.prod/buildtrees/libigl/src/349425d44b-75d0882505`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v`
`    Working Directory: D:/Git/vs2019.prod/buildtrees/libigl/x64-windows-dbg`
`    See logs for more information:`
**`      D:\Git\vs2019.prod\buildtrees\libigl\install-x64-windows-dbg-out.log`**

`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/libigl/portfile.cmake:63 (vcpkg_install_cmake)`
`  scripts/ports.cmake:79 (include)`

`Error: Building package libigl:x64-windows failed with: BUILD_FAILED`
`Elapsed time for package libigl:x64-windows: 1.066 min`

**Attached Logs**
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5017392/install-x64-windows-dbg-out.log)

2020-08-03 17:54 UTC, StarGate-One commented
@strega-nil Now this is odd, I built libigl with feature imgui included and as x64-windows (set VCPKG_DEFAULT_TRIPLET=x64-windows; having VCPKG_CRT_LINKAGE=dynamic and VCPKG_LIBRARY_LINKAGE=dynamic) and I did not get the message I should have from link 19-22:
` if ("imgui" IN_LIST FEATURES AND NOT VCPKG_LIBRARY_LINKAGE STREQUAL static)`
`    # Remove this after add port libigl-imgui`
`    message(FATAL_ERROR "Feature imgui does not support non-static build currently")`
`endif()` 
... I have no clue why this message and error did not happen - I double checked the .\ports\libigl\portfile.cmake and it is correct with the one in this PR.. .. :(

2020-08-03 19:02 UTC, strega-nil commented
@StarGate-One that's correct; libigl doesn't support dynamic libraries so it gets built as a static library.

2020-08-03 19:50 UTC, StarGate-One commented
> @StarGate-One that's correct; libigl doesn't support dynamic libraries so it gets built as a static library.

Yes I see now the `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` set the linkage to static, so basically the message paragraph is do nothing code as this test will always be false and never happen ;)

Thanks and have a wonderful week!!!

2020-08-03 20:04 UTC, strega-nil commented
@StarGate-One yeah :) This is just future proofing, afaict.

2020-08-04 00:22 UTC, strega-nil commented
@StarGate-One alright, I've figured it out. Unfortunately, this is an issue with using the `imgui` bundled with vcpkg -- we need to start depending on `libigl-imgui` in this port if we want the imgui feature to work. Afaict, libigl 2.2.0 broke compatibility with imgui proper.

2020-08-04 02:06 UTC, StarGate-One commented
Ah... Ok... I appreciate the time/effort to figure it out.

2020-08-10 22:33 UTC, StarGate-One commented
@JackBoosY - Why information response is required? I tested the changes, these changes also fail and posted the new log files.

2020-08-10 22:35 UTC, strega-nil commented
@StarGate-One I need to fix this, that's why author response is required.

2020-08-10 22:38 UTC, StarGate-One commented
> @StarGate-One I need to fix this by downloading the right headers, that's why author response is required.

Ok thanks. I just thought there may have been something I needed to do.

2020-08-17 02:22 UTC, JackBoosY approved these changes

2020-08-18 09:37 UTC, NancyLi1013 commented
All features for `imgui `have passed with the following triplets:

- x86-windows (Except for `dx12-binding` that doesn't support x86)
`  F:\12691\vcpkg\buildtrees\imgui\src\v1.77-a2cb3da790.clean\examples\imgui_impl_dx12.cpp(390): error C2338: Can't pack descriptor handle into TexID, 32-bit not supported yet.`
- x64-windows
- x64-windows-static

All features for `libigl` have passed with the following triplets:
- x86-windows
- x64-windows-static

Note: For feature `embree`, it failed on x64-windows-static with the error like this:

```
CMake Error at F:/12691/vcpkg/scripts/buildsystems/vcpkg.cmake:455 (_find_package):
  Found package configuration file:

    F:/12691/vcpkg/installed/x64-windows-static/share/embree/embree-config.cmake
 
  but it set embree_FOUND to FALSE so package "embree" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  embree_sse42 embree_avx embree_avx2

Call Stack (most recent call first):
  cmake/libigl.cmake:300 (find_package)
  CMakeLists.txt:59 (include)
```
I checked `embree-config.cmake` and there seems to be less embree_sse42 embree_avx embree_avx2 targets.

I tried to add the following codes to _share/embree/embree-config.cmake_ and it can rebuild successfully.
```
IF(EMBREE_ISA_SSE42)
    INCLUDE("${EMBREE_ROOT_DIR}/share/embree3/embree_sse42-targets.cmake")
endif()

IF(EMBREE_ISA_AVX)
    INCLUDE("${EMBREE_ROOT_DIR}/share/embree3/embree_avx-targets.cmake")
endif()

IF(EMBREE_ISA_AVX2)
    INCLUDE("${EMBREE_ROOT_DIR}/share/embree3/embree_avx2-targets.cmake")
endif()
```

So we might need to change `embree3 `to solve this issue.

2020-08-22 09:34 UTC, BillyONeal approved these changes

2020-08-24 03:02 UTC, JackBoosY commented
LGTM

2020-08-24 19:49 UTC, merged

2020-08-24 19:49 UTC, BillyONeal commented
Thanks for your contribution!