[lapack-reference|fortran] Add new port
microsoft/vcpkg pull request #12805
Opened 2020-08-07 12:32 UTC by Neumann-A

Again. New approach without touching any main files. Other PR seemed broken not running in CI.

2020-08-07 14:00 UTC, Neumann-A commented on ports/clapack/portfile.cmake
> -file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/FindLAPACK.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/lapack)
moved to the lapack metaport

2020-08-07 14:32 UTC, Neumann-A commented on ports/lapack-reference/CONTROL
> +Build-Depends: lapack-reference[core, noblas](!windows|(windows&!static))
windows&!static

should be !staticcrt but I don't know how to express that.

2020-08-07 14:41 UTC, Neumann-A commented
@cenit: Feel free to review and test this one.

2020-08-07 18:38 UTC, Neumann-A commented
@centi any opinion on using `openblas` on OSX? The current osx failure is due to `blas.pc` missing and i would need to create one for the accelerate framework.

2020-08-07 19:22 UTC, centi commented
@Neumann-A To be honest, I have no idea what this is about. Could you please clarify how am I connected to this? Did I report some issue (I've searched the issues but did not find any reported by me)?

I'm not sure if I ever used this tool, but maybe I did (or some other tool which uses this as a dependency) a long time ago and forgotten about it since. Anyway, I no longer use OSX, so I cannot help with the last question either.

2020-08-07 19:23 UTC, Neumann-A commented
@centi typo i meant cenit ;)

2020-08-07 19:34 UTC, cenit commented
> @centi typo i meant cenit ;)

Go for OpenBLAS also on osx. The current situation is very comparable with the accelerate framework, or even better. This is not true for clapack, but that's the whole scope of this PR

2020-08-07 20:26 UTC, centi commented
> @centi typo i meant cenit ;)

Phew. I was starting to doubt my memory :)

2020-08-07 22:04 UTC, Neumann-A commented
Hmm should I put clapack on the skip list for the failing triplets?

2020-08-08 06:21 UTC, Neumann-A commented
@cbezault @vicroms: opinions?

2020-08-10 08:46 UTC, NancyLi1013 requested changes

2020-08-10 08:46 UTC, NancyLi1013 commented on ports/clapack/portfile.cmake
> -file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/FindLAPACK.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/lapack)
The version in CONTROL file for `clapack` should also be updated.

2020-08-10 08:46 UTC, NancyLi1013 commented on ports/lapack/portfile.cmake
> +    file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/clapack/FindLAPACK.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/lapack)
```suggestion
    file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/clapack/vcpkg-cmake-wrapper.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
    file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/clapack/FindLAPACK.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})

```

2020-08-10 08:46 UTC, NancyLi1013 commented on ports/openblas/portfile.cmake
`if(VCPKG_CMAKE_SYSTEM_NAME  STREQUAL "WindowsStore")`

should be updated as

`if(VCPKG_TARGET_IS_UWP)`



Please also update `elseif(NOT VCPKG_CMAKE_SYSTEM_NAME)`.

2020-08-10 08:46 UTC, NancyLi1013 commented on ports/openblas/portfile.cmake
>  # openblas do not make the config file , so I manually made this
Update
```
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/openblas)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/openblas/LICENSE ${CURRENT_PACKAGES_DIR}/share/openblas/copyright)
```

as

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME  copyright)`?

2020-08-10 08:46 UTC, NancyLi1013 commented on ports/vcpkg-gfortran/portfile.cmake
> +include(vcpkg_find_fortran)
```suggestion
`vcpkg_fail_port_install(ON_ARCH "arm" ON_TARGET "linux" "osx")`

include(vcpkg_find_fortran)
```

2020-08-10 08:59 UTC, JackBoosY commented on ports/lapack-reference/CONTROL
> +Build-Depends: lapack-reference[core, noblas](!windows|(windows&!static))
@Neumann-A CRT linkage is always the same in the same triplet, so we don't need to pay attention to this.

2020-08-10 09:04 UTC, JackBoosY requested changes

2020-08-10 09:04 UTC, JackBoosY commented on ports/mlpack/cmakelists.patch
> ++  #set(LAPACK_LIBRARIES lapack)
Just remove them could reduce this patch size.

2020-08-10 09:04 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +clapack:x64-linux = skip
We don't need to add these code here now, we can add `Supports` field to `CONTROL` instead of this.

2020-08-10 09:20 UTC, cenit commented on scripts/ci.baseline.txt
> +clapack:x64-linux = skip
skip is not fail, it's necessary because otherwise installation would fail due to files already installed by other ports ;)

2020-08-10 12:27 UTC, Neumann-A commented on ports/lapack-reference/CONTROL
> +Build-Depends: lapack-reference[core, noblas](!windows|(windows&!static))
@JackBoosY: You are forgetting custom triplets like `x64-windows-static-md`

2020-08-10 12:37 UTC, Neumann-A commented on scripts/ci.baseline.txt
> +clapack:x64-linux = skip
clapack install lapack.lib which directly conflicts with lapack-reference also installing lapack.lib. So skipping clapack in ci is the only option here. building clapack is still supported on these platforms.

2020-08-11 01:57 UTC, JackBoosY approved these changes

2020-08-12 17:28 UTC, strega-nil commented
This is amazing! Thanks @Neumann-A :)

2020-08-12 17:28 UTC, merged

2021-08-17 02:44 UTC, JackBoosY commented on scripts/cmake/vcpkg_find_fortran.cmake
> +            endif()
This may breaks the unity of CRT linkage. Should we use `vcpkg_check_linkage` instead?

2021-08-17 03:23 UTC, cenit commented on scripts/cmake/vcpkg_find_fortran.cmake
> +            endif()
dynamic only linkage in a static triplet cause an error. This would trigger a lot of cascade ports to fail without any notice. it’s very different from a static linkage in a dynamic triplet

while the original line is very problematic, as you say, also the fix would trigger many problems

2021-08-17 06:59 UTC, Neumann-A commented on scripts/cmake/vcpkg_find_fortran.cmake
> +            endif()
#19413 solves all the problems with gfortran by switching to the ifort instead. CRT linkage is also not that important if memory is not passed between the different CRTs.

2023-01-02 07:44 UTC, dg0yt commented on ports/lapack-reference/portfile.cmake
> +endif()
@Neumann-A Is this the desired outcome of feature configuration, in particular with regard to enabling `OPTIMZED_BLAS`?

| Requested features | Static CRT & internal Fortran | Otherwise | Dependencies |
|----------|----------|--------|--------|
| core  | - | `OPTIMIZED_BLAS` | none |
| cblas | `CBLAS`  | `CBLAS`,  `OPTIMIZED_BLAS` | none |
| noblas | -  | `OPTIMIZED_BLAS` | `blas` (->`openblas`) |
| cblas,noblas | error  | error | `blas` (->`openblas`) |

I'm concerned about `OPTIMIZED_BLAS` being enabled for the "Otherwise" "core"/"cblas" cases. The build result will depend on the result of `find_package(BLAS)`. I would assume `OPTIMIZED_BLAS` should be restricted to the `noblas` case so that the actual dependency can be switched in a controlled way by overriding port `blas`.

2023-01-02 09:52 UTC, Neumann-A commented on ports/lapack-reference/portfile.cmake
> +endif()
see #24327. But what vcpkg really needs is a) options RFC and b) a proper Windows Fortran compiler. (#24622)

2023-01-02 20:02 UTC, dg0yt commented on ports/lapack-reference/portfile.cmake
> +endif()
That PR doesn't clearly adress the particular aspect I'm looking at: `set(USE_OPTIMIZED_BLAS ON)` at Line 54 regardless of features. In turn this will enable `find_package(BLAS)` in the project regardless of controlled dependencies. I'm proposing to turn this off. The effective result would be:

| Requested features | Static CRT & internal Fortran | Otherwise | Dependencies |
|----------|----------|--------|--------|
| core  | - | - | none |
| cblas | `CBLAS`  | `CBLAS` | none |
| noblas | -  | `OPTIMIZED_BLAS` | `blas` (->`openblas`) |
| cblas,noblas | error  | error | `blas` (->`openblas`) |

2023-01-02 21:11 UTC, Neumann-A commented on ports/lapack-reference/portfile.cmake
> +endif()
ah i see simply removing line 53-54 should be enough.