Fix/clang10 linux
microsoft/vcpkg pull request #12837
Opened 2020-08-10 05:24 UTC by ignacionr

**Describe the pull request**

- What does your PR fix?
Fixes warnings treated as errors on Clang 10.0.0 Linux. Also one unused fn.

- Which triplets are supported/not supported? Have you updated the CI baseline?
Does not apply (this is a fix for the tool).

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

**Additional notice** (so to understand some of these changes)

- I like the idea of Span<> being a view into contiguous memory (it basically avoids going through abstracted iterators).

- When initializing them with vectors, we are making a claim that will not necessarily last: std::vector may need to re-allocate at some point, so it will all move elsewhere. But while within a fn called with a temporary object, it's fairly safe. 

- Clang is wiser than other compilers and won't let us just go ahead and use vectors for that reason. So I changed it to the address of the first element, and the count (totally equivalent, and the potential risks made explicit).

Of course, I may have completely misunderstood something here, so comments and clarifications are very welcome.

2020-08-10 17:13 UTC, strega-nil commented
@ignacionr this... seems like an unfortunate change. What warnings does clang throw after passing the vector as a span?

Fwiw, this path has been tread before, by the standards committee, so they agree we're doing the right thing here.

2020-08-10 19:18 UTC, ras0219 requested changes
I used docker[1] to get a copy of clang 10 and didn't see a motivation (i.e. compiles without warnings) for two of the changes; otherwise, looks great!

[1] https://solarianprogrammer.com/2017/12/14/clang-in-docker-container-cpp-17-development/

2020-08-10 19:18 UTC, ras0219 commented on toolsrc/src/vcpkg/build.cpp
> +                                  .value_or_exit(VCPKG_LINE_INFO);
This change seems unneeded for clang-10.

2020-08-10 19:18 UTC, ras0219 commented on toolsrc/src/vcpkg/build.cpp
> +            auto maybe_abi_tag_and_file = compute_abi_tag(paths, action, {&dependency_abis[0], dependency_abis.size()});
This change seems unneeded for clang-10.

2020-08-11 01:53 UTC, ignacionr commented
> @ignacionr this... seems like an unfortunate change. What warnings does clang throw after passing the vector as a span?
> 
> Fwiw, this path has been tread before, by the standards committee, so they agree we're doing the right thing here.

I was able to reproduce this only for a minute on the Visual Studio Code messages. At some point, the messages just disappeared. It may have been related to whatever version of compiler/standard library the IDE was using before re-configuring. I will remove the changes (since they proved unnecessary), as I agree they don't look appealing to read.

2020-08-11 01:55 UTC, ignacionr commented on toolsrc/src/vcpkg/build.cpp
> +                                  .value_or_exit(VCPKG_LINE_INFO);
Re-checked and you are totally correct. Also as pointed out previously, they make it less readable. I will go on and remove these two.

2020-08-11 01:56 UTC, ignacionr commented on toolsrc/src/vcpkg/build.cpp
> +            auto maybe_abi_tag_and_file = compute_abi_tag(paths, action, {&dependency_abis[0], dependency_abis.size()});
Will remove.

2020-08-13 10:28 UTC, ignacionr commented
@strega-nil @ras0219 this seems ready now. Care to merge?

2020-08-13 16:49 UTC, strega-nil commented
/azp run

2020-08-17 02:37 UTC, JackBoosY approved these changes

2020-08-17 15:31 UTC, merged