[grpc] grpc v1.30.2
microsoft/vcpkg pull request #12920
Opened 2020-08-15 15:25 UTC by jozefizso

**Describe the pull request**
- What does your PR fix? Fixes #12122
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

https://github.com/grpc/grpc/releases/tag/v1.30.2

2020-08-17 02:49 UTC, NancyLi1013 commented on ports/grpc/CONTROL
>  Port-Version: 1
```suggestion
Version: 1.30.2
```
Since this is a new update, there is no need to use `Port-Version` here.

2020-08-17 02:53 UTC, NancyLi1013 commented
Hi @jozefizso 
Thanks for this PR.

Have you test the feature `absl-sync`? Does it work fine?

2020-08-17 11:04 UTC, jozefizso commented
> Have you test the feature `absl-sync`? Does it work fine?

Nope, I did not try it. Should I just recompile grpc with that feature enabled?

2020-08-18 01:15 UTC, NancyLi1013 commented
Yes, you can just rebuild `grpc` with the feature.

2020-08-18 07:17 UTC, jozefizso commented
I used `.\vcpkg install grpc[absl-sync]` for `x86-windows`, `x64-windows` and `x64-windows-static` builds and it worked.

2020-08-19 06:34 UTC, NancyLi1013 commented
/azp run

2020-08-19 06:41 UTC, NancyLi1013 reviewed
Could you please update 

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/grpc RENAME copyright)`

as

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

Could you please also use `vcpkg_copy_tools()` to take place the following codes?
```
vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/grpc)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/tools")
```
Sorry, I didn't notice this part before.

2020-08-19 20:16 UTC, jozefizso commented
I'm not sure if I used the `vcpkg_copy_tools()` correctly, but it produced the same output structure as before.

2020-08-19 21:21 UTC, jozefizso commented
I fixed it for `uwp` and `arm` builds as they don't produce tool binaries.

2020-08-20 01:57 UTC, NancyLi1013 commented
/azp run

2020-08-20 02:28 UTC, NancyLi1013 approved these changes

2020-08-20 02:29 UTC, JackBoosY requested changes

2020-08-20 02:29 UTC, JackBoosY commented on ports/grpc/portfile.cmake
> +        -DgRPC_INSTALL_BINDIR:STRING=bin
Why change this to `bin`?

2020-08-20 06:52 UTC, jozefizso commented on ports/grpc/portfile.cmake
> +        -DgRPC_INSTALL_BINDIR:STRING=bin
Otherwise the `vcpkg_copy_tools()` does not work:

```
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:47 (message):
  Couldn't find this tool:
  C:/dev/github/vcpkg/packages/grpc_x64-windows/bin/grpc_php_plugin.exe.
Call Stack (most recent call first):
  ports/grpc/portfile.cmake:74 (vcpkg_copy_tools)
  scripts/ports.cmake:79 (include)
```

2020-08-20 06:58 UTC, JackBoosY approved these changes

2020-08-22 08:16 UTC, merged