[libmediainfo] Update to 20.08
microsoft/vcpkg pull request #12944
Opened 2020-08-16 19:35 UTC by g-maxime

2020-08-17 02:37 UTC, NancyLi1013 requested changes

2020-08-17 02:37 UTC, NancyLi1013 commented on ports/libmediainfo/portfile.cmake
>  )
Could you please update

`OPTIONS -DBUILD_ZENLIB=0 -DBUILD_ZLIB=0`

as

```
OPTIONS 
    -DBUILD_ZENLIB=0 
    -DBUILD_ZLIB=0
```
?

2020-08-17 02:38 UTC, NancyLi1013 reviewed
Could you please also bump the `version `in CONTROL file?

2020-08-17 08:01 UTC, g-maxime commented on ports/libmediainfo/portfile.cmake
>  )
Done. Thanks.

2020-08-19 03:13 UTC, NancyLi1013 approved these changes

2020-08-20 04:24 UTC, merged

2020-08-20 04:24 UTC, BillyONeal commented
Thanks for your contribution!