[drogon] Fix building errors on Windows and Linux
microsoft/vcpkg pull request #13007
Opened 2020-08-19 16:45 UTC by an-tao

**Describe the pull request**

- What does your PR fix? Fixes #

1. After the PR #12669, the zlib library is separated from libmariadb, so we should link against it explicitly.(fixed in https://github.com/an-tao/drogon/pull/545)

1. Fix the following error on Linux.
<img width="586" alt="截屏2020-08-20 上午12 40 11" src="https://user-images.githubusercontent.com/21002501/90664828-c5783400-e27d-11ea-8fc3-de0d7b75d0a0.png">

2020-08-20 00:35 UTC, BillyONeal commented
/azp run

2020-08-20 02:40 UTC, NancyLi1013 requested changes

2020-08-20 02:40 UTC, NancyLi1013 commented on ports/drogon/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/Drogon)
Could you please use `vcpkg_copy_tools()` to handle tools instead of `vcpkg_copy_tool_dependencies()`?

Since this function will copy tools and all their DLL dependencies into the tools folder automatically.

2020-08-20 06:57 UTC, NancyLi1013 approved these changes

2020-08-20 08:11 UTC, an-tao commented
Hi, @NancyLi1013, this PR works on Windows and MacOS, but there is  a little problem on Linux, after installing drogon, the drogon_ctl command in tools folder doesn't work (the libpq.so.5 can't be found), but it works in the buildtrees folder.
<img width="834" alt="截屏2020-08-20 下午3 39 41" src="https://user-images.githubusercontent.com/21002501/90733064-9a81f480-e2fe-11ea-8788-99f72e95e423.png">
Although I have a workaround for this by `export LD_LIBRARY_PATH=/../vcpkg/installed/x64-linux/lib`, is there a better way to resolve this?

2020-08-21 05:55 UTC, BillyONeal commented
Would you like this to be merged as is even if the problem above isn't solved yet (since this is a version update)

2020-08-21 06:04 UTC, an-tao commented
That's ok, please merge it. thanks.

2020-08-21 07:11 UTC, JackBoosY approved these changes

2020-08-21 07:21 UTC, NancyLi1013 commented
@an-tao 

This problem also exists on my local. We might fix it in another PR later. 

I also noticed that this port requires `libuuid `to build. But there is no `libuuid `in the dependency lists. 
Could you please help confirm this?

2020-08-21 07:33 UTC, an-tao commented
> @an-tao
> 
> This problem also exists on my local. We might fix it in another PR later.
> 
> I also noticed that this port requires `libuuid `to build. But there is no `libuuid `in the dependency lists.
> Could you please help confirm this?

Yes, libuuid is required on Linux and MacOS but isn't on Windows. How do I add this ?

2020-08-21 08:04 UTC, an-tao commented
After added libuuid, I got following errors on Windows:
![批注 2020-08-21 160253](https://user-images.githubusercontent.com/21002501/90867416-ecdb1800-e3c7-11ea-8f6e-b51c7972e7b4.png)
@NancyLi1013 How should I handle this? Thanks.

2020-08-21 08:11 UTC, JackBoosY requested changes

2020-08-21 08:11 UTC, JackBoosY commented on ports/drogon/CONTROL
> +Build-Depends: trantor, zlib, jsoncpp, libmariadb, libpq, sqlite3, brotli, libuuid
```suggestion
Build-Depends: trantor, zlib, jsoncpp, libmariadb, libpq, sqlite3, brotli, libuuid (!windows)
```

2020-08-21 08:12 UTC, JackBoosY commented
@an-tao Please try again locally.

2020-08-21 08:27 UTC, an-tao commented
> @an-tao Please try again locally.

It works, Thanks so much. Does vcpkg support FreeBSD? the libuuid is also not required on FreeBSD. 
And should we use (!window&!uwp) ?

2020-08-21 08:32 UTC, JackBoosY commented
vcpkg support freebsd, but not totally. And freebsd is not one of our official triplets.
Windows includes uwp, so there is no need to add it.

2020-08-21 08:33 UTC, JackBoosY approved these changes

2020-08-21 16:31 UTC, merged