[fbthrift] Add new port
microsoft/vcpkg pull request #13072
Opened 2020-08-22 03:58 UTC by curoky

Describe the pull request

What does your PR fix?
Add new port: [facebook/fbthrift](https://github.com/facebook/fbthrift)

Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

Does your PR follow the maintainer guide?
Yes.

2020-08-24 08:06 UTC, NancyLi1013 requested changes

2020-08-24 08:06 UTC, NancyLi1013 commented on ports/fbthrift/portfile.cmake
> +)
```suggestion
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO facebook/fbthrift
    REF 3b56786f0822f78a408addffaf3a54b1b8c86dcd # v2019.11.11.00
    SHA512 d892c6825345d2dc68abbe7a0eacb5ee0444fdea328d8d6bbcd512752058a2de715c03567120090a355115bb9d5d41f3f9c8dc2f82b8054d0b5a2fd1621bf473
    HEAD_REF master
)
```
For `REF`, I have the same doubt with the version in CONTROL file.

2020-08-24 08:06 UTC, NancyLi1013 commented on ports/fbthrift/portfile.cmake
> +endif()
`vcpkg_copy_tools()` might take place of these parts. Could you please try to update it?

2020-08-24 08:06 UTC, NancyLi1013 commented on ports/fbthrift/portfile.cmake
> +)
```suggestion
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
)
```

2020-08-24 08:13 UTC, NancyLi1013 commented
Hi @curoky 
Thanks for this PR.
This port cannot build `osx`. Is it due to `bsion`?

2020-08-24 12:34 UTC, curoky commented on ports/fbthrift/CONTROL
> +Version: 2019.11.11.00
Yeah, I also hope to use the latest version, but it will be a long process.

The reason is that fbthrift deeply couples folly/wangle/fizz and so on. If fbthrift uses the latest version, folly/wangle/fizz must also be the latest version. 

It is not difficult to upgrade folly just for fbthrift, but it will be very difficult for all dependent folly packages.

My [vcpkg fork](https://github.com/microsoft/vcpkg/compare/master...curoky:master) use the latest fbthrift, because i upgrade folly/wangle/fizz. 

Downgrade the fbthrift version, just for merging it into the master.

2020-08-24 12:40 UTC, curoky commented
> Hi @curoky
> Thanks for this PR.
> This port cannot build `osx`. Is it due to `bsion`?

I don't know, that's just the first problem I encountered on osx.

2020-08-26 06:35 UTC, NancyLi1013 commented on ports/fbthrift/CONTROL
> +Version: 2019.11.11.00
Thanks for your so detailed information.

2020-08-26 08:46 UTC, NancyLi1013 approved these changes

2020-08-26 09:50 UTC, JackBoosY commented
If this port need bison 3.0.4, please modify the following codes:
https://github.com/microsoft/vcpkg/blob/4a9b658141308ac0c7a26cd98c463466217ff162/scripts/cmake/vcpkg_find_acquire_program.cmake#L257-L286

2020-08-28 03:14 UTC, JackBoosY requested changes

2020-08-28 03:14 UTC, JackBoosY commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
Please don't do that.
Different bison versions will cause this port to fail to build. Therefore, we need to use the built-in bison in vcpkg instead of the system.

2020-08-31 09:41 UTC, curoky commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
It seems that bison does not have a pre-compiled version, we need to compile bison from source during vcpkg installation.

2020-08-31 09:47 UTC, JackBoosY commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
@curoky We don't need to build bison now, as I said, we need to update vcpkg build-in tools bison instead.

2020-08-31 14:06 UTC, curoky commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
I add these lines only for OSX, and only `CMAKE_HOST_WIN32` have pre-compiled bison.

So how to use the built-in bison on OSX without compiling from source?

If there is no official pre-compiled version, or we don't want to compile from the source, then the version installed by brew is also a good choice.

```bash
$ brew info bison          
bison: stable 3.7.1 (bottled) [keg-only]
Parser generator
https://www.gnu.org/software/bison/
/usr/local/Cellar/bison/3.7.1 (94 files, 3.2MB)
  Poured from bottle on 2020-08-23 at 01:23:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bison.rb
License: GPL-3.0
==> Caveats
bison is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have bison first in your PATH run:
  echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.zshrc

For compilers to find bison you may need to set:
  export LDFLAGS="-L/usr/local/opt/bison/lib"
```

https://github.com/microsoft/vcpkg/blob/4a9b658141308ac0c7a26cd98c463466217ff162/scripts/cmake/vcpkg_find_acquire_program.cmake#L258-L275

2020-09-03 08:26 UTC, JackBoosY requested changes

2020-09-03 08:26 UTC, JackBoosY commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
The bison path should be automatically added to the environment or general `vcpkg_find_acquire_program` is automatically exported, so there is no need to set its path here.
See https://github.com/microsoft/vcpkg/blob/310f4df34f154e1e2cd0502a717baf6ccbe29549/ports/libpcap/portfile.cmake#L40-L42

2020-09-03 08:51 UTC, ras0219 commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
I think the best way to handle this is to add this bison path (`/usr/local/opt/bison/bin/bison`) to be searched for in `vcpkg_find_acquire_program(BISON)` preferentially over the system bison on OSX. We can then pass this in directly to the build using `OPTIONS -DBISON_EXECUTABLE=${BISON}`.

2020-09-12 12:13 UTC, curoky commented on ports/fbthrift/0001-fix-bison-path-osx.patch
> ++    set(BISON_EXECUTABLE "/usr/local/opt/bison/bin/bison" CACHE PATH "Bison executable")
@ras0219 👍🏻️ Thanks for your suggestion, it's elegant and simple.

2020-09-12 12:23 UTC, curoky commented
@JackBoosY Also thanks for your suggestion. I just updated this pr. Hope this one can go through soon.

2020-09-13 20:35 UTC, ras0219 approved these changes

2020-09-14 02:46 UTC, JackBoosY approved these changes

2020-09-28 01:55 UTC, merged

2020-09-28 01:55 UTC, ras0219-msft commented
Thanks for the PR!