[mpc/mpfr] Add new port / update mpfr
microsoft/vcpkg pull request #13081
Opened 2020-08-22 12:44 UTC by Neumann-A

~~might depend on #12936 if windows CI fails~~

2020-08-24 07:42 UTC, NancyLi1013 requested changes

2020-08-24 07:42 UTC, NancyLi1013 commented on ports/mpfr/portfile.cmake
> +            dll.patch
```suggestion
    PATCHES 
        gmpd.patch
        dll.patch
```

2020-08-24 07:47 UTC, JackBoosY approved these changes

2020-08-25 09:55 UTC, NancyLi1013 approved these changes

2020-08-26 02:23 UTC, JackBoosY commented
mipr:x64-linux:
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
autoreconf: running: /usr/bin/autoconf --force
configure:14306: error: possibly undefined macro: AX_PTHREAD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

2020-08-27 10:10 UTC, Neumann-A commented
@NancyLi1013: Why requires author-response? libtool is missing which is why the error is there.

2020-08-27 10:16 UTC, NancyLi1013 commented
Thanks for your reply. @Neumann-A 
In fact, I mean this PR still needs to be fixed. It seems that this label is not suitable. I will remove it now.

2020-09-28 01:56 UTC, ras0219-msft commented
/azp run

2020-09-28 03:15 UTC, NancyLi1013 commented
The failure on x86-windows:
```
Starting package 239/289: mpfr:x86-windows
Building package mpfr[core]:x86-windows...
Could not locate cached archive: W:\c4\c415306f605f21769b06fd86ed279f2c0a39342e.zip
-- Downloading http://www.mpfr.org/mpfr-4.1.0/mpfr-4.1.0.tar.xz...
-- Extracting source D:/downloads/mpfr-4.1.0.tar.xz
-- Applying patch gmpd.patch
-- Applying patch dll.patch
-- Using source at D:/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean
CMake Error at scripts/cmake/vcpkg_acquire_msys.cmake:293 (message):
  Unknown packages were required for vcpkg_acquire_msys(texinfo): texinfo

  This can be resolved by explicitly passing URL/SHA pairs to
  DIRECT_PACKAGES.
Call Stack (most recent call first):
  ports/mpfr/portfile.cmake:16 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)
```

2020-09-28 21:04 UTC, Neumann-A commented
@NancyLi1013: Probably due to the changes to msys. Will only touch it if linux vm has the required deps installed otherwise CI will just be red any way.

2020-10-09 06:20 UTC, JackBoosY commented
/azp run

2020-10-09 08:06 UTC, JackBoosY commented
See results https://dev.azure.com/vcpkg/public/_build/results?buildId=43769&view=results

2020-10-09 08:42 UTC, Neumann-A commented
@JackBoosY: I know I currently just don't have time to fix any of my PRs. In this PR texinfo needs to be added to MSYS or it needs to be added manually into the portfile.

2020-10-09 08:51 UTC, JackBoosY commented
@Neumann-A Okay, I'll take a look,

2021-01-11 07:34 UTC, Neumann-A commented
hmm unable to reproduce the x86-windows error locally

2021-01-11 10:06 UTC, NancyLi1013 commented
The error like this:

`configure: error: There is wchar.h but the size of wchar_t is 0`

It's so weird. I noticed that `U_SIZEOF_WCHAR_T` as been defined to the specific value in `platform.h`.

2021-01-11 10:24 UTC, Neumann-A commented
as I said I am unable to reproduce it locally.

2021-01-11 17:29 UTC, BillyONeal commented
I checked the files database from the most recent nightly build and observe that `${VCPKG_INSTALLED_DIR}/include/platform.h` is owned by `scintilla`. Is it possible that ports are stomping on each other here?

2021-01-11 17:49 UTC, Neumann-A commented
@BillyONeal: Seems not to be the issue here. I was able to build icu with scintilla installed. Maybe it just needs a CI rerun? Sometimes the config.log in `<triplet>-<config>/config.log` gives more details

2021-01-12 07:36 UTC, JackBoosY commented
@Neumann-A I will try to repro it manually.

2021-01-13 07:23 UTC, JackBoosY commented
Although I installed these all 248 ports before install icu, I still can't repro this regression.

2021-01-14 02:12 UTC, JackBoosY commented
Install scintilla before install icu, this regression can't repro too.

2021-01-18 09:34 UTC, JackBoosY commented
log about icu regression: 
[failure logs for x86-windows (17).zip](https://github.com/microsoft/vcpkg/files/5829211/failure.logs.for.x86-windows.17.zip)

2021-01-19 07:55 UTC, Neumann-A commented
Yeah green ... but i am curious what happened to the regression

2021-01-19 08:09 UTC, JackBoosY approved these changes

2021-01-19 08:10 UTC, JackBoosY commented
@Neumann-A Anyway, I recorded that in this PR.

2021-01-19 19:20 UTC, vicroms commented on ports/gmp/vcpkg.json
> +  "version-string": "6.2.1",
Since this already uses a manifest file, why not use `version-semver` or `version` [versioning schemes](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#schemes)?

2021-01-19 23:19 UTC, vicroms approved these changes

2021-01-20 10:45 UTC, Neumann-A commented on ports/gmp/vcpkg.json
> +  "version-string": "6.2.1",
Why should it? This is a vcpkg internal update. 
As such port-version is the correct thing and should have been from the beginning.

2021-01-21 03:27 UTC, vicroms commented on ports/gmp/vcpkg.json
> +  "version-string": "6.2.1",
In my opinion we should start switching packages to their correct versioning schemes. 

Since "version-string" are non-orderable (except by their port version number) by design, continuing to use them will seriously limit the usefulness of "version>=" constraints.

2021-01-21 07:22 UTC, Neumann-A commented on ports/gmp/vcpkg.json
> +  "version-string": "6.2.1",
I am just doing what `vcpkg x-add-version` does. If you want `"version": "6.2.1",` here please tell/teach the command to do that.

2021-01-22 02:54 UTC, JackBoosY approved these changes

2021-01-22 02:55 UTC, JackBoosY commented
```
[388/459] cmd.exe /C "cd . && D:\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=src\osgEarth\CMakeFiles\osgEarth.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe"  @CMakeFiles\osgEarth.rsp  /out:lib\osgEarthd.dll /implib:lib\osgEarthd.lib /pdb:lib\osgEarthd.pdb /dll /version:3.1 /machine:x64 /nologo    /debug /INCREMENTAL /NODEFAULTLIB:MSVCRT  && cd ."
FAILED: lib/osgEarthd.dll lib/osgEarthd.lib 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=src\osgEarth\CMakeFiles\osgEarth.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe"  @CMakeFiles\osgEarth.rsp  /out:lib\osgEarthd.dll /implib:lib\osgEarthd.lib /pdb:lib\osgEarthd.pdb /dll /version:3.1 /machine:x64 /nologo    /debug /INCREMENTAL /NODEFAULTLIB:MSVCRT  && cd ."
LINK Pass 1: command "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe @CMakeFiles\osgEarth.rsp /out:lib\osgEarthd.dll /implib:lib\osgEarthd.lib /pdb:lib\osgEarthd.pdb /dll /version:3.1 /machine:x64 /nologo /debug /INCREMENTAL /NODEFAULTLIB:MSVCRT /MANIFEST /MANIFESTFILE:src\osgEarth\CMakeFiles\osgEarth.dir/intermediate.manifest src\osgEarth\CMakeFiles\osgEarth.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library lib\osgEarthd.lib and object lib\osgEarthd.exp
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: static void __cdecl osgEarth::TiXmlBase::EncodeString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?EncodeString@TiXmlBase@osgEarth@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV34@@Z) referenced in function "void __cdecl `anonymous namespace'::storeNode(class osgEarth::Util::XmlNode const *,class osgEarth::TiXmlNode *)" (?storeNode@?A0x092e8abd@@YAXPEBVXmlNode@Util@osgEarth@@PEAVTiXmlNode@4@@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "protected: static char const * __cdecl osgEarth::TiXmlBase::GetEntity(char const *,char *,int *,enum TiXmlEncoding)" (?GetEntity@TiXmlBase@osgEarth@@KAPEBDPEBDPEADPEAHW4TiXmlEncoding@@@Z) referenced in function "protected: static char const * __cdecl osgEarth::TiXmlBase::GetChar(char const *,char *,int *,enum TiXmlEncoding)" (?GetChar@TiXmlBase@osgEarth@@KAPEBDPEBDPEADPEAHW4TiXmlEncoding@@@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl osgEarth::TiXmlNode::~TiXmlNode(void)" (??1TiXmlNode@osgEarth@@UEAA@XZ) referenced in function "int `public: __cdecl osgEarth::TiXmlComment::TiXmlComment(char const *)'::`1'::dtor$0" (?dtor$0@?0???0TiXmlComment@osgEarth@@QEAA@PEBD@Z@4HA)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode const * __cdecl osgEarth::TiXmlNode::FirstChild(char const *)const " (?FirstChild@TiXmlNode@osgEarth@@QEBAPEBV12@PEBD@Z) referenced in function "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::FirstChild(char const *)" (?FirstChild@TiXmlNode@osgEarth@@QEAAPEAV12@PEBD@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode const * __cdecl osgEarth::TiXmlNode::LastChild(char const *)const " (?LastChild@TiXmlNode@osgEarth@@QEBAPEBV12@PEBD@Z) referenced in function "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::LastChild(char const *)" (?LastChild@TiXmlNode@osgEarth@@QEAAPEAV12@PEBD@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode const * __cdecl osgEarth::TiXmlNode::IterateChildren(class osgEarth::TiXmlNode const *)const " (?IterateChildren@TiXmlNode@osgEarth@@QEBAPEBV12@PEBV12@@Z) referenced in function "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::IterateChildren(class osgEarth::TiXmlNode const *)" (?IterateChildren@TiXmlNode@osgEarth@@QEAAPEAV12@PEBV12@@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode const * __cdecl osgEarth::TiXmlNode::IterateChildren(char const *,class osgEarth::TiXmlNode const *)const " (?IterateChildren@TiXmlNode@osgEarth@@QEBAPEBV12@PEBDPEBV12@@Z) referenced in function "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::IterateChildren(char const *,class osgEarth::TiXmlNode const *)" (?IterateChildren@TiXmlNode@osgEarth@@QEAAPEAV12@PEBDPEBV12@@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::LinkEndChild(class osgEarth::TiXmlNode *)" (?LinkEndChild@TiXmlNode@osgEarth@@QEAAPEAV12@PEAV12@@Z) referenced in function "public: void __cdecl osgEarth::Util::XmlDocument::store(class std::basic_ostream<char,struct std::char_traits<char> > &)const " (?store@XmlDocument@Util@osgEarth@@QEBAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode const * __cdecl osgEarth::TiXmlNode::PreviousSibling(char const *)const " (?PreviousSibling@TiXmlNode@osgEarth@@QEBAPEBV12@PEBD@Z) referenced in function "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::PreviousSibling(char const *)" (?PreviousSibling@TiXmlNode@osgEarth@@QEAAPEAV12@PEBD@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlNode const * __cdecl osgEarth::TiXmlNode::NextSibling(char const *)const " (?NextSibling@TiXmlNode@osgEarth@@QEBAPEBV12@PEBD@Z) referenced in function "public: class osgEarth::TiXmlNode * __cdecl osgEarth::TiXmlNode::NextSibling(char const *)" (?NextSibling@TiXmlNode@osgEarth@@QEAAPEAV12@PEBD@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlElement const * __cdecl osgEarth::TiXmlNode::NextSiblingElement(void)const " (?NextSiblingElement@TiXmlNode@osgEarth@@QEBAPEBVTiXmlElement@2@XZ) referenced in function "public: class osgEarth::TiXmlElement * __cdecl osgEarth::TiXmlNode::NextSiblingElement(void)" (?NextSiblingElement@TiXmlNode@osgEarth@@QEAAPEAVTiXmlElement@2@XZ)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlElement const * __cdecl osgEarth::TiXmlNode::NextSiblingElement(char const *)const " (?NextSiblingElement@TiXmlNode@osgEarth@@QEBAPEBVTiXmlElement@2@PEBD@Z) referenced in function "public: class osgEarth::TiXmlElement * __cdecl osgEarth::TiXmlNode::NextSiblingElement(char const *)" (?NextSiblingElement@TiXmlNode@osgEarth@@QEAAPEAVTiXmlElement@2@PEBD@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlElement const * __cdecl osgEarth::TiXmlNode::FirstChildElement(void)const " (?FirstChildElement@TiXmlNode@osgEarth@@QEBAPEBVTiXmlElement@2@XZ) referenced in function "public: class osgEarth::TiXmlElement * __cdecl osgEarth::TiXmlNode::FirstChildElement(void)" (?FirstChildElement@TiXmlNode@osgEarth@@QEAAPEAVTiXmlElement@2@XZ)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class osgEarth::TiXmlElement const * __cdecl osgEarth::TiXmlNode::FirstChildElement(char const *)const " (?FirstChildElement@TiXmlNode@osgEarth@@QEBAPEBVTiXmlElement@2@PEBD@Z) referenced in function "public: class osgEarth::TiXmlElement * __cdecl osgEarth::TiXmlNode::FirstChildElement(char const *)" (?FirstChildElement@TiXmlNode@osgEarth@@QEAAPEAVTiXmlElement@2@PEBD@Z)
XmlUtils.cpp.obj : error LNK2019: unresolved external symbol "public: class o [...]

2021-01-22 03:15 UTC, JackBoosY commented
It seems a baseline regression.

2021-01-22 03:16 UTC, JackBoosY commented
Already merged from master.

2021-01-25 06:51 UTC, dan-shaw approved these changes

2021-01-25 07:01 UTC, merged

2021-01-25 09:26 UTC, cenit commented
@BillyONeal this is an example of what I was trying to discuss with you earlier: this PR changed a dependency, from mpir to gmp, without any additional note, and broke downstream check in CI for other ports without anyone noticing.

The problem is that now, due to already accepted failures in baseline, all ports that were depending on mpir and mpfr are now broken by default, since gmp cannot be installed if mpir is installed.
Also, gmp port is broken on linux at least for me (I don't know why/how/if it passes on ci), and so any additional fix based on it will be even more difficult.

TL;DR : try to install openmvs now. It depends on both gmp and mpir and so it's bound to fail. It was not before. It is completely untested by ci now, and it was not before. This is only an example.

2021-01-25 09:31 UTC, cenit commented
That's similar to what I experience *always* with the opencv port. Somehow, externally it gets broken and no-one gets notified about that. That just means more work to fix parallel unrelated ports every time I want to update it (and make it really work of course, not just pretending it)

2021-01-25 10:24 UTC, Neumann-A commented
> Also, gmp port is broken on linux at least for me (I don't know why/how/if it passes on ci)

probably due to https://github.com/microsoft/vcpkg/pull/13081#issuecomment-678739081. Need to install `autconf-archive`

Trying to fix it in #15860 but I really need an inverse dependency lookup for those issues (e.g. `vcpkg depend-info gmp --invers` or something like that). Furthermore CI should tell us difference between the ports tested current master CI and vs the ones in the PR and warn if there is a negative difference.

2021-01-25 19:08 UTC, cenit commented
Yes, you should put a note in the port file for linux and osx to install autoconf-archive (both on apt and in brew).
I don't understand why you need reverse dependency lookup, but anything that might help you or any other port maintainer to do a better job is important