[sentry-native] Add new port
microsoft/vcpkg pull request #13118
Opened 2020-08-25 00:38 UTC by AenBleidd

This fixes #12159

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

2020-08-25 02:26 UTC, NancyLi1013 requested changes

2020-08-25 03:51 UTC, AenBleidd commented on ports/sentry-native/CONTROL
> +Port-Version: 1
Hm, I thought to put it for future changes. Ok, I remove it.

2020-08-25 03:52 UTC, AenBleidd commented on ports/sentry-native/portfile.cmake
> +include(vcpkg_common_functions)
Sure

2020-08-25 03:53 UTC, AenBleidd commented on ports/sentry-native/portfile.cmake
> +)
This repo has submodules. So Source code archive has some folders (of submodules) empty. sentry-native.zip has these folders filled with necessary files.

2020-08-25 03:53 UTC, AenBleidd commented on ports/sentry-native/portfile.cmake
> +file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/bin/crashpad_handler.exe)
Will do this

2020-08-25 03:54 UTC, AenBleidd commented on ports/sentry-native/portfile.cmake
> +    DESTINATION ${CURRENT_PACKAGES_DIR}/share/sentry-native
Will do

2020-08-25 05:36 UTC, NancyLi1013 commented on ports/sentry-native/portfile.cmake
> +)
Thanks for your clarification.

2020-08-25 05:50 UTC, NancyLi1013 commented
Hi @AenBleidd 
Thanks for this PR.

Could you please look into the failures and try to fix them?

If this port doesn't support arm and uwp, please add `Supports: !(arm|uwp) ` to CONTROL file and also add `vcpkg_fail_port_install_port(ON_ARCH "arm" ON_TARGET "uwp")` to the top of `portfile.cmake`.

2020-08-25 05:51 UTC, NancyLi1013 requested changes

2020-08-25 05:51 UTC, NancyLi1013 commented on ports/sentry-native/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/sentry TARGET_PATH share/${PORT}/cmake)
```suggestion
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/sentry TARGET_PATH share/sentry-native/cmake)
```
It should not be updated as `${PORT} `here. Generally, we suggest to use ${PORT} instead of port name in these cases:
license, usage or other files that need to be placed in `share `directory. For CMake files, since the folder name might not be the same as port name.

2020-08-27 01:07 UTC, AenBleidd commented on ports/sentry-native/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/sentry TARGET_PATH share/${PORT}/cmake)
Fixed

2020-08-27 02:26 UTC, AenBleidd commented
@NancyLi1013, PR is ready for your review

2020-08-27 02:28 UTC, NancyLi1013 approved these changes

2020-08-27 02:32 UTC, AenBleidd commented
CI fail is not related to this PR: previous build was successful: https://dev.azure.com/vcpkg/public/_build/results?buildId=42093&view=results
tiny-xml is failed but definitely not because of this PR

2020-08-27 06:27 UTC, NancyLi1013 commented
@AenBleidd 
Thanks for your kindly reminder.
The failures are not related with this PR. There are some problems on Sourceforge website. We have submitted a PR #13176 to detect Sourceforge website status.

2020-08-28 17:07 UTC, AenBleidd commented
@NancyLi1013, after rebuild it's officially green :)

2020-08-31 02:13 UTC, NancyLi1013 commented
@AenBleidd 
Thanks for this PR. LGTM now.

2020-09-01 00:57 UTC, merged

2020-09-01 00:57 UTC, BillyONeal commented
Thanks for your contribution!