pbjson-lib
microsoft/vcpkg pull request #13160
Opened 2020-08-26 08:39 UTC by tejas15802

- Fixes PR #13131 
- src file added

2020-08-26 10:03 UTC, NancyLi1013 commented
Hi @tejas15802 
Thanks for adding this port.

It seems that you just add the source code to this PR.

Please refer to this doc https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md to learn about how to add a new port. 

You can also search other ports in vcpkg to learn more about this.

BTW, please sign CLA first.

2020-08-26 11:28 UTC, tejas15802 commented
@NancyLi1013 Than code doesn't owned by me. So I'm little confused on what option I should be choosing for signing

2020-08-26 12:11 UTC, tejas15802 commented
can you please guide me choose the appropriate option @NancyLi1013

2020-08-27 02:21 UTC, NancyLi1013 commented
@tejas15802 

You can click here https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=13160 to sign CLA.

2020-08-27 04:11 UTC, tejas15802 commented
> @tejas15802
> 
> You can click here https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=13160 to sign CLA.

I'm not the author of that code, so I'm not sure If I can sign it

2020-08-27 06:06 UTC, NancyLi1013 commented
This is not related to the author. So it doesn't matter to sign this. Everyone needs to sign this if he wants to contribute to Microsoft open source projects. Since the source codes have included LICENSE file, you don't need to worry about this.

2020-08-27 11:01 UTC, tejas15802 commented
I don't what is causing the issue, can someone help me out?

2020-08-28 01:45 UTC, NancyLi1013 commented
@tejas15802 
You just need to keep CONTROL, portfile.cmake files in this PR. Other files are not needed here. You should remove these files.

BTW, I noticed that this is a header-only library, in this case, you just need to install its headers to vcpkg.
Please refer to this port https://github.com/microsoft/vcpkg/tree/master/ports/libmorton.

2020-08-28 07:46 UTC, tejas15802 commented
Have I done it right this time, coz it's taking long to verify

2020-08-28 08:06 UTC, NancyLi1013 requested changes

2020-08-28 08:06 UTC, NancyLi1013 commented on ports/pbjson/portfile.cmake
> +file(GLOB HEADER_FILES ${SOURCE_PATH}/src/*.h)
It seems that there are also *.hpp files included in the source. So these kinds of headers are also needed to install.

BTW, I also noticed that there are `rapidjson` source codes in _${SOURCE_PATH}/src_ directory. Do you know what the relationships between `pbjson `and `rapidjson`?

2020-08-28 08:49 UTC, tejas15802 commented on ports/pbjson/portfile.cmake
> +file(GLOB HEADER_FILES ${SOURCE_PATH}/src/*.h)
no I don't know : [

2020-08-28 09:31 UTC, NancyLi1013 requested changes

2020-08-28 09:31 UTC, NancyLi1013 commented on ports/pbjson/portfile.cmake
> +file(GLOB HEADER_FILES ${SOURCE_PATH}/src/*.h)
```suggestion
file(GLOB HEADER_FILES ${SOURCE_PATH}/src/*.h  ${SOURCE_PATH}/src/*.hpp)
```
Please also add .hpp file.

2020-08-28 12:51 UTC, tejas15802 reviewed
Updated the same

2020-08-31 02:14 UTC, NancyLi1013 commented
/azp run

2020-09-01 13:01 UTC, tejas15802 commented
should I look @ the code once again?

2020-09-02 09:06 UTC, NancyLi1013 commented
> should I look @ the code once again?

Sorry, I don't make sense. What do you mean?

If you mean whether you need to update changes or not in this PR, I think it's unnecessary now.
Since the current status seems to be not related with this PR. I will try to rerun it.

2020-09-03 02:31 UTC, tejas15802 commented
> > should I look @ the code once again?
> 
> Sorry, I don't make sense. What do you mean?
> 
> If you mean whether you need to update changes or not in this PR, I think it's unnecessary now.
> Since the current status seems to be not related with this PR. I will try to rerun it.

Yes that's what I meant. Mm Okay!

2020-10-26 10:11 UTC, NancyLi1013 commented
Hi @tejas15802 
Sorry for the long delay.

It seems that the repository doesn't exist now.

Could you please help take a look and merge master changes to this PR?

2020-10-27 09:30 UTC, tejas15802 commented
I actually deleted the repo, cuz I thought I made some kind of mistake and what I did isn't going to work

2020-10-27 09:31 UTC, tejas15802 commented
I actually deleted the repo, cuz I thought I made some kind of mistake and what I did isn't going to work 

@NancyLi1013 


> Hi @tejas15802
> Sorry for the long delay.
> 
> It seems that the repository doesn't exist now.
> 
> Could you please help take a look and merge master changes to this PR?

2020-10-28 02:08 UTC, NancyLi1013 commented
Are you willing to create a new repo to make a new PR for the new port?

Without the original repo, this PR cannot continue working.

2020-10-28 02:19 UTC, tejas15802 commented
> Are you willing to create a new repo to make a new PR for the new port?
> 
> Without the original repo, this PR cannot continue working.

sorry I'm not.

2020-10-28 05:42 UTC, NancyLi1013 commented
/azp run

2020-10-29 09:26 UTC, NancyLi1013 commented
Thanks for the PR; we're closing this for now since the repo has been deleted. If you'd like to continue working for the port, please open a new PR.

2020-10-29 09:26 UTC, closed without merging