add new port that rest-rpc
microsoft/vcpkg pull request #13190
Opened 2020-08-28 00:11 UTC by zhangdexin

rest-roc is c++11, high performance, cross platform, easy to use rpc framework.

It's so easy to love RPC.

2020-08-28 03:21 UTC, NancyLi1013 requested changes

2020-08-28 03:21 UTC, NancyLi1013 commented on ports/rest-rpc/portfile.cmake
> +include(vcpkg_common_functions)
```suggestion
```
This function is not needed here. Could you please remove it?

2020-08-28 03:21 UTC, NancyLi1013 commented on ports/rest-rpc/portfile.cmake
> +
Could you please use` vcpkg_from_github()` to get the source and extract the archive?

2020-08-28 03:21 UTC, NancyLi1013 commented on ports/rest-rpc/portfile.cmake
> +file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/share/rest-rpc)
```suggestion
```
It is unnecessary to add these two lines. Since vcpkg will create automatically.

2020-08-28 03:21 UTC, NancyLi1013 commented on ports/rest-rpc/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
Why do you remove this folder?

2020-08-28 03:21 UTC, NancyLi1013 commented on ports/rest-rpc/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/third/msgpack/include/ DESTINATION ${CURRENT_PACKAGES_DIR}/include)
Is this a header only library?

2020-08-28 03:21 UTC, NancyLi1013 commented on ports/rest-rpc/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/rest-rpc RENAME copyright)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

2020-08-28 03:31 UTC, zhangdexin commented on ports/rest-rpc/portfile.cmake
> +include(vcpkg_common_functions)
yes

2020-08-28 03:32 UTC, zhangdexin commented on ports/rest-rpc/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
When I install for test, some error

2020-08-28 03:33 UTC, zhangdexin commented on ports/rest-rpc/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/third/msgpack/include/ DESTINATION ${CURRENT_PACKAGES_DIR}/include)
Yes

2020-08-28 03:33 UTC, zhangdexin commented on ports/rest-rpc/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/rest-rpc RENAME copyright)
okey

2020-08-28 03:34 UTC, zhangdexin commented
So Need I request another pr?

2020-08-28 03:35 UTC, zhangdexin commented on ports/rest-rpc/portfile.cmake
> +file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/share/rest-rpc)
Okey

2020-08-28 03:38 UTC, zhangdexin commented on ports/rest-rpc/portfile.cmake
> +
Okey

2020-08-28 06:04 UTC, NancyLi1013 commented
> So Need I request another pr?

Not need. You can update changes in this PR.

2020-08-29 08:12 UTC, closed without merging

2020-08-30 09:16 UTC, zhangdexin commented
Maybe I clicked in a wrong place