[ceres][lapack][clapack][lapack-reference][opencv4][selene] Fix deps issues
microsoft/vcpkg pull request #13229
Opened 2020-08-30 03:29 UTC by ras0219

As part of a full rebuild in #13019, several transitive rebuild issues were found.

1) selene was dynamically detecting the presence of OpenCV, which was not on its dependency list.
2) The dynamic OpenCV was using `find_package()` instead of `find_dependency()`
3) The dynamic OpenCV was always finding all dependencies instead of just those that were used during build.
4) CMake's FindHDF5 module requires C language support
5) ceres was passing `REQUIRED` into find_dependency (not needed -- find_dependency implies REQUIRED)
6) FindLAPACK.cmake was sometimes provided by the meta-port lapack, sometimes by the dependency lapack-reference/clapack
7) The lapack-reference vcpkg-cmake-wrapper was directly including the FindLAPACK, which doesn't respect variables such as QUIET and REQUIRED

Interestingly, the particular issue required a cascade of failures to occur to actually cause a build failure; almost any of these fixes would independently fix the build.

2020-08-30 05:29 UTC, cenit commented
The same cleaner solution for find_dependencies can be applied to opencv2/3. I used find_package and QUIET to “hack” the system, but it is not as robust as this.
I am jut unsure about the `BUILD_opencv_quality` switch. Wasn’t `contrib` feature better? Is opencv quality defined here in the parent script?

2020-08-30 07:35 UTC, ras0219 commented
On uwp, the dependencies are disabled:
https://github.com/microsoft/vcpkg/pull/13229/files#diff-cc80ebd35d7c59af4199c1196aac6692L15-L17

This per-platform logic is already implemented above in the `BUILD_opencv_quality` switch, so that's why I'm using it: https://github.com/microsoft/vcpkg/pull/13229/files#diff-b2c0c4ecb1a6e09f5fc9b8f84fcdc62bL112-L119

2020-08-31 17:33 UTC, BillyONeal commented
Hi there @ras0219 :)

zxing-cpp failed on x64-windows-static due to the default build-depends not having protobuf: https://github.com/BillyONeal/vcpkg/commit/f9cc36251e98e61606660f86fb802274ce1a9e27
It also failed because the bigint dependency failed to be found. A change like the following fixes it: https://github.com/BillyONeal/vcpkg/commit/e80c069b4948135d0cff44664ba68aecfb0a2157 ... but it seems like that shouldn't have been necessary?

2020-08-31 17:33 UTC, BillyONeal commented
(I have those changes prepared in https://github.com/BillyONeal/vcpkg/commits/robert_review_fix if you want to use it as a base)

2020-08-31 20:46 UTC, BillyONeal commented
@ras0219 and I talked about this stuff out of band.

2020-08-31 22:24 UTC, ras0219 commented
I'm looking into the dbow2 failure (looks like the transitive dependency through opencv isn't being handled appropriately)

From dbow2:
>[7/8] : && /Library/Developer/CommandLineTools/usr/bin/c++ -fPIC -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names  -o libDBoW2.dylib -install_name @rpath/libDBoW2.dylib CMakeFiles/DBoW2.dir/src/BowVector.cpp.o CMakeFiles/DBoW2.dir/src/FBrief.cpp.o CMakeFiles/DBoW2.dir/src/FORB.cpp.o CMakeFiles/DBoW2.dir/src/FeatureVector.cpp.o CMakeFiles/DBoW2.dir/src/QueryResults.cpp.o CMakeFiles/DBoW2.dir/src/ScoringObject.cpp.o  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_calib3dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_cored.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_dnnd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_features2dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_flannd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_highguid.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgcodecsd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgprocd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_mld.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_objdetectd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_photod.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_stitchingd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_videod.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_videoiod.a  -llibprotobuf  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgcodecsd.a  /Users/vagrant/Data/installed/x64-osx/lib/libjpeg.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdecoderd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdemuxd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libpng16d.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libtiffd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/liblzmad.a  /Users/vagrant/Data/installed/x64-osx/lib/libjpeg.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdecoderd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdemuxd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libpng16d.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libtiffd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/liblzmad.a  -lm  -framework Accelerate  -framework AVFoundation  -framework CoreGraphics  -framework CoreMedia  -framework CoreVideo  -framework QuartzCore  -framework Cocoa  /Users/vagrant/Data/installed/x64-osx/debug/lib/libquircd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_calib3dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_features2dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_flannd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgprocd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_cored.a  /Users/vagrant/Data/installed/x64-osx/lib/libz.a  -framework OpenCL && :
FAILED: libDBoW2.dylib 
: && /Library/Developer/CommandLineTools/usr/bin/c++ -fPIC -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names  -o libDBoW2.dylib -install_name @rpath/libDBoW2.dylib CMakeFiles/DBoW2.dir/src/BowVector.cpp.o CMakeFiles/DBoW2.dir/src/FBrief.cpp.o CMakeFiles/DBoW2.dir/src/FORB.cpp.o CMakeFiles/DBoW2.dir/src/FeatureVector.cpp.o CMakeFiles/DBoW2.dir/src/QueryResults.cpp.o CMakeFiles/DBoW2.dir/src/ScoringObject.cpp.o  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_calib3dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_cored.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_dnnd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_features2dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_flannd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_highguid.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgcodecsd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgprocd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_mld.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_objdetectd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_photod.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_stitchingd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_videod.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_videoiod.a  -llibprotobuf  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgcodecsd.a  /Users/vagrant/Data/installed/x64-osx/lib/libjpeg.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdecoderd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdemuxd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libpng16d.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libtiffd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/liblzmad.a  /Users/vagrant/Data/installed/x64-osx/lib/libjpeg.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdecoderd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libwebpdemuxd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libpng16d.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libtiffd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/liblzmad.a  -lm  -framework Accelerate  -framework AVFoundation  -framework CoreGraphics  -framework CoreMedia  -framework CoreVideo  -framework QuartzCore  -framework Cocoa  /Users/vagrant/Data/installed/x64-osx/debug/lib/libquircd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_calib3dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_features2dd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_flannd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_imgprocd.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libopencv_cored.a  /Users/vagrant/Data/installed/x64-osx/lib/libz.a  -framework OpenCL && :
ld: library not found for -llibprotobuf
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

2020-09-01 05:37 UTC, ras0219-msft commented
/azp run

2020-09-01 10:05 UTC, NancyLi1013 requested changes

2020-09-01 10:05 UTC, NancyLi1013 commented on ports/opencv4/CONTROL
> +Port-Version: 2
```suggestion
Port-Version: 1
```
This might be `1`.

2020-09-04 02:38 UTC, NancyLi1013 approved these changes

2020-09-04 22:32 UTC, BillyONeal commented
Submitted the Blaze patch upstream: https://bitbucket.org/blaze-lib/blaze/pull-requests/44/fix-inability-to-build-blaze-on-some

2020-09-04 23:02 UTC, dan-shaw approved these changes
It seems that the library `zxing-cpp` doesn't have `protobuf` as a dependency, and `opencv` installs `protobuf`. Not sure why it was failing the CI.

2020-09-05 00:45 UTC, BillyONeal commented
@dan-shaw Good point.

2020-09-05 01:59 UTC, merged

2020-09-05 01:59 UTC, BillyONeal commented
Thanks for your contribution!