[vcpkg_acquire_msys.cmake] Add gettext tool
microsoft/vcpkg pull request #13297
Opened 2020-09-02 03:58 UTC by StarGate-One

**Describe the pull request**
[vcpkg_acquire_msys.cmake] Add gettext tool needed by libpq

- What does your PR fix? Fixes #13291 [vcpkg_acquire_msys.cmake] missing download of gettext

- Which triplets are supported/not supported? Not Applicable

- Have you updated the CI baseline? Not Applicable

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2020-09-02 19:46 UTC, ras0219 requested changes

2020-09-02 19:46 UTC, ras0219 commented on scripts/cmake/vcpkg_acquire_msys.cmake
> +    URL "https://repo.msys2.org/msys/x86_64/gettext-0.19.8.1-1-x86_64.pkg.tar.xz"
This needs to list dependencies from https://packages.msys2.org/package/gettext?repo=msys&variant=x86_64 and be sorted into the list above in topological order; it looks like it needs `DEPS libasprintf libgettextpo libintl`.

2020-09-02 20:17 UTC, StarGate-One commented on scripts/cmake/vcpkg_acquire_msys.cmake
> +    URL "https://repo.msys2.org/msys/x86_64/gettext-0.19.8.1-1-x86_64.pkg.tar.xz"
@ras0219  This all beyond my technical abilities - I not msys expert - I see no topological order or any order alphabetical or otherwise or not instructions anywhere on how to modify the file. 
I went to page listed and see it list things that are in the download package already. 
I do not know why there was a change in direction from plain msys to downloading individual msys parts and pieces - msys with development packages would have everything needed. 
Since I not a technical as you all I withdraw and maybe the next person needing libpq and gettext is missing they can do better job or they smarter than me.

2020-09-03 02:01 UTC, ras0219 approved these changes
Thanks for making the fixes and sorry for the confusing term! This is exactly what I meant :)

The reason we want to split up the msys2 directories is to avoid one port having a "hidden" dependency on another -- for example, when `A` installs gettext we don't want it to silently also be provided to `B`.

2020-09-04 14:11 UTC, merged

2020-09-04 14:11 UTC, BillyONeal commented
Thanks for your contribution!

2020-09-04 18:00 UTC, StarGate-One commented
> Thanks for your contribution!

You are most welcome @BillyONeal. Have a wonderful weekend... Thank you for all the hard work. 👍🏻