[lerc] Add New Port
microsoft/vcpkg pull request #13358
Opened 2020-09-04 19:16 UTC by nazame

Add lerc port according to issue #12031

2020-09-07 02:39 UTC, JackBoosY requested changes

2020-09-07 02:39 UTC, JackBoosY commented on ports/lerc/enable_static_build.patch
> ++add_library(LercLib ${SOURCES})
Since the official setting here is to build dynamic library, can you confirm whether the symbols of the static library are successfully exported?

2020-09-07 23:02 UTC, nazame commented on ports/lerc/enable_static_build.patch
> ++add_library(LercLib ${SOURCES})
I have built a simple tool that makes use of the static library and can confirm that it works as expected.

2020-09-08 01:58 UTC, JackBoosY approved these changes

2020-09-09 19:47 UTC, merged

2020-09-09 19:47 UTC, ras0219-msft commented
LGTM, thanks for the contribution!