[d3dx12] Add new port
microsoft/vcpkg pull request #13360
Opened 2020-09-04 21:26 UTC by mteterel

New port: **d3dx12** (https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3DX12)

For convenience purposes.

2020-09-07 06:54 UTC, NancyLi1013 requested changes

2020-09-07 06:54 UTC, NancyLi1013 commented on ports/d3dx12/portfile.cmake
> +# vcpkg_fail_port_install(MESSAGE "@PORT@ currently only supports Linux and Mac platforms" ON_TARGET "Windows")
```suggestion
```
These comments should be removed.

2020-09-07 06:54 UTC, NancyLi1013 commented on ports/d3dx12/vcpkg.json
> +  "version-string": "12aug2020",
```suggestion
  "version-string": "2020-09-05",
```
It seems that there is no version for this port. So we can use a date here. Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#version.

2020-09-07 06:54 UTC, NancyLi1013 commented on ports/d3dx12/portfile.cmake
> +
```suggestion
# Header-only library
```

2020-09-08 01:41 UTC, NancyLi1013 commented on ports/d3dx12/portfile.cmake
> +    URLS "https://raw.githubusercontent.com/walbourn/directx-vs-templates/master/d3d12game_win32_dr/d3dx12.h"
Why do you use the URL https://raw.githubusercontent.com/walbourn/directx-vs-templates/master/d3d12game_win32_dr/d3dx12.h  instead of https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Libraries/D3DX12/d3dx12.h?

2020-09-08 05:53 UTC, mteterel commented on ports/d3dx12/portfile.cmake
> +    URLS "https://raw.githubusercontent.com/walbourn/directx-vs-templates/master/d3d12game_win32_dr/d3dx12.h"
The previous link is dependent on the latest Windows 10 SDK, where as the second ones has the appropriate preprocessor conditions for newer features.

2020-09-08 08:19 UTC, NancyLi1013 approved these changes

2020-09-09 19:41 UTC, ras0219-msft requested changes
Thanks for the PR!

LGTM once my comments are addressed.

2020-09-09 19:41 UTC, ras0219-msft commented on ports/d3dx12/portfile.cmake
> +    URLS "https://raw.githubusercontent.com/walbourn/directx-vs-templates/master/d3d12game_win32_dr/d3dx12.h"
```suggestion
    URLS "https://raw.githubusercontent.com/walbourn/directx-vs-templates/may2020/d3d12game_win32_dr/d3dx12.h"
```
This needs to use a stable, versioned URL instead of `master`

2020-09-09 19:41 UTC, ras0219-msft commented on ports/d3dx12/vcpkg.json
> +  "version-string": "2020-09-05",
```suggestion
  "version-string": "may2020",
```

2020-09-11 03:02 UTC, NancyLi1013 commented
Also needs to update hash value.

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:102 (message):
  

  File does not have expected hash:

          File path: [ D:/downloads/temp/d3dx12.h ]
      Expected hash: [ 58a1f5060c82c2769987592d6f20d8c8d86032505740492b24f69c88b75f0814d3f18d5c3ae7c71c54bfe5eeb7f844ee623ce73376a676986db0643589aab62b ]
        Actual hash: [ 829b72ddf861652bd96518b7d54f7a103c95b4434ec022e1551fb085e4dfc8f804e01ccdb4677e3f64367553c56d35291b305e10c2ea6186ddadaaa071c6d7a2 ]

2020-09-11 03:03 UTC, NancyLi1013 requested changes

2020-09-11 03:03 UTC, NancyLi1013 commented on ports/d3dx12/portfile.cmake
> +    SHA512 "58a1f5060c82c2769987592d6f20d8c8d86032505740492b24f69c88b75f0814d3f18d5c3ae7c71c54bfe5eeb7f844ee623ce73376a676986db0643589aab62b"
```suggestion
    SHA512 "829b72ddf861652bd96518b7d54f7a103c95b4434ec022e1551fb085e4dfc8f804e01ccdb4677e3f64367553c56d35291b305e10c2ea6186ddadaaa071c6d7a2"
```

2020-09-11 03:16 UTC, NancyLi1013 approved these changes

2020-09-11 19:37 UTC, ras0219-msft approved these changes

2020-09-11 20:18 UTC, merged

2020-09-11 20:18 UTC, ras0219-msft commented
Thanks for the PR!