[vcpkg] update fetch command
microsoft/vcpkg pull request #13430
Opened 2020-09-09 11:22 UTC by dan-shaw

2020-09-09 17:19 UTC, BillyONeal requested changes
* If this is in support of the VS Code extension, why doesn't the VS Code extension do this rather than the vcpkg tool? VS Code should already know how to do git clones etc. which might save a download here.
* What frequency do we expect the VS Code extension to use when invoking this?
* I'm concerned that once a user touches this their update experience, which we've previously documented as `git pull`, becomes broken.
* This is really a totally different 'animal' to the other `vcpkg fetch` invocations, it seems like it should be a top level command and accept the path as a parameter rather than just trying to use the root?

2020-09-09 17:19 UTC, BillyONeal commented on toolsrc/src/vcpkg/commands.fetch.cpp
> +                R"(%s clone %s %s)", fs::u8string(git_exe), fs::u8string(repo), fs::u8string(fetch_dir));
```suggestion
                R"("%s" clone "%s" "%s")", fs::u8string(git_exe), fs::u8string(repo), fs::u8string(fetch_dir));
```

This needs to be made resistant to spaces in the path

2020-09-09 17:19 UTC, BillyONeal commented on toolsrc/src/vcpkg/commands.fetch.cpp
> +            fs.remove_all(paths.ports, ignore_errors);
I don't think ignore errors is the right behavior here. We want failures to be loud so we don't get "impossible" bugs where only some part of the tree got updated or similar.

It's also very strange to totally ignore these errors but then explicitly check for the git exit code on 48.

2020-09-09 17:25 UTC, strega-nil commented on toolsrc/src/vcpkg/commands.fetch.cpp
> +                R"(%s clone %s %s)", fs::u8string(git_exe), fs::u8string(repo), fs::u8string(fetch_dir));
I believe we have an "escape for command line" function.

2021-01-15 16:15 UTC, BillyONeal commented
@dan-shaw Should we close this now that registries have landed?

2021-02-03 19:19 UTC, BillyONeal commented
I believe this PR can be closed following https://github.com/microsoft/vcpkg/pull/15474/

2021-02-07 06:29 UTC, JackBoosY commented
According to @BillyONeal said, close this PR.
If you have any concern, please reopen this.

2021-02-07 06:29 UTC, closed without merging