[hffix] New port hffix library 1.0.0
microsoft/vcpkg pull request #13433
Opened 2020-09-09 13:31 UTC by gnaggnoyil

**Describe the pull request**

- What does your PR fix? Fixes #13432

- Which triplets are supported/not supported? Have you updated the CI baseline?

	* All triplets should be supported. No, CI baseline isn't updated.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

	* Yes

2020-09-10 06:40 UTC, NancyLi1013 requested changes

2020-09-10 06:40 UTC, NancyLi1013 commented on ports/hffix/portfile.cmake
> +	SHA512 0043b789e6ffdc32eaf2736a8621dd7fd54e1a16aae33bb1d5f642da1b04d150ed42d8f9ddd046013242164854d9091540452153f09459d05f9bf4a186c7b860
```suggestion
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO jamesdbrock/hffix
    REF v1.0.0
    SHA512 0043b789e6ffdc32eaf2736a8621dd7fd54e1a16aae33bb1d5f642da1b04d150ed42d8f9ddd046013242164854d9091540452153f09459d05f9bf4a186c7b860
    HEAD_REF master
```

2020-09-10 06:40 UTC, NancyLi1013 commented on ports/hffix/portfile.cmake
> +	PREFER_NINJA
```suggestion
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA	
```

2020-09-10 06:40 UTC, NancyLi1013 commented on ports/hffix/CMakeLists.txt
> +add_library(hffix-header INTERFACE)
```suggestion
add_library(hffix INTERFACE)
```
In my opinion, it might be better to rename it as `hffix`.

2020-09-10 06:40 UTC, NancyLi1013 commented on ports/hffix/CMakeLists.txt
> +target_include_directories(hffix-header INTERFACE
```suggestion
target_include_directories(hffix INTERFACE
```

2020-09-10 06:40 UTC, NancyLi1013 commented on ports/hffix/CMakeLists.txt
> +	TARGETS hffix-header
```suggestion
	TARGETS hffix
```

2020-09-11 02:14 UTC, NancyLi1013 approved these changes

2020-09-11 19:48 UTC, merged

2020-09-11 19:48 UTC, ras0219-msft commented
Thanks for the PR!