[BLAS] add metaport
microsoft/vcpkg pull request #13448
Opened 2020-09-10 08:07 UTC by cenit

Almost identical to LAPACK approach, I am suggesting this metaport to ease BLAS+LAPACK port override (macOS Accelerate framework is almost the only one working properly on the upcoming Apple Silicon)

2020-09-10 09:44 UTC, cenit commented
Note: I added f90ffde commit to keep current BLAS setup also on macOS. It's an open question if we should use Apple Accelerate framework there by default (and in this case just reverting the commit and make blas depend on openblas(!osx)

2020-09-10 10:11 UTC, ras0219 commented on ports/clapack/CONTROL
>  Port-Version: 15
This port has a different behavior with the new `blas` dependency (it now depends on `openblas` on osx) and thus needs to have the `Port-Version` incremented.

2020-09-10 15:56 UTC, cenit commented on ports/clapack/CONTROL
>  Port-Version: 15
Ok right.

2020-09-11 02:57 UTC, NancyLi1013 reviewed
Is it necessary to update Port-Version for other ports?

2020-09-24 19:25 UTC, cenit commented
Any feedback here to consider for merging?

2020-09-25 01:50 UTC, NancyLi1013 commented
I noticed that `Port-Version` is not updated for some ports. I'm not sure if it is necessary to update it.

Note: Seems need to resolve the conflicts caused by `shogun`.

2020-09-25 04:44 UTC, cenit commented
> I noticed that `Port-Version` is not updated for some ports. I'm not sure if it is necessary to update it.
> 
> 
> 
> Note: Seems need to resolve the conflicts caused by `shogun`.

Ok but @ras0219 requested port version bump only for clapack, I assume the others are ok in this way

2020-10-05 07:13 UTC, cenit commented
@NancyLi1013 may I ask why "requires:author-response"?

2020-10-09 03:07 UTC, NancyLi1013 commented
@cenit 
Sorry for the late delay. We're on holiday in these days.
There were some conflicts caused by `shogun` before this. So I added the label. Seems you have solved them now. I will try to rerun and check the new results. I will remove this label if all CI checks have passed.

2020-10-09 09:39 UTC, NancyLi1013 commented
/azp run

2020-10-29 09:33 UTC, NancyLi1013 commented
@cenit 

Could you please resolve the conflicts and also merge master?

2020-10-30 01:46 UTC, NancyLi1013 approved these changes

2020-10-30 01:46 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @cenit.

2020-10-30 19:13 UTC, BillyONeal requested changes

2020-10-30 19:13 UTC, BillyONeal commented on ports/blas/CONTROL
> +Build-Depends: openblas
This will now cause openblas to be dragged in for ports which previously were saying `openblas (!osx)`. How does that interaction work?

2020-10-30 19:13 UTC, BillyONeal commented on ports/blas/portfile.cmake
> +vcpkg_configure_cmake(SOURCE_PATH ${CURRENT_PORT_DIR}
If you're depending on system stuff you should emit a message here or similar when the system thing isn't installed explaining how to get it, at least for osx and Ubuntu

2020-10-30 19:13 UTC, BillyONeal commented on ports/blas/CMakeLists.txt
> +#TODO make sure that the found BLAS is outside VCPKG
This comment seems wrong since on some platforms this port expects `openblas` to provide them.

2020-10-31 21:17 UTC, cenit commented
@BillyONeal i copy-pasted same exact messages and behavior from the lapack port! But I will modify pr according to your review.

About the openblas(!osx), it’s a residual from the past. In the beginning I did a pr to exclude OpenBLAS and clapack from Ports using them on osx, because the accelerate framework was better. Then lapack-reference came and it superseded the behavior, to uniform platform better. This made OpenBLAS the default everywhere, too.
Now with the advent of arm64 arch for macOS the accelerate framework is very relevant again, so also an easy way to override vcpkg default to its own blas/lapack libs

2020-11-02 04:35 UTC, BillyONeal commented
@Neumann-A  Can you explain what those comments are saying that were added in https://github.com/microsoft/vcpkg/pull/12464 ? It seems like the `lapack` port is trying to be both an indicator of use of a system outside-of-vcpkg provided lapack but it simultaneously wants clapack or lapack-reference to provide an implementation.

/cc @strega-nil

2020-11-02 09:19 UTC, Neumann-A commented
@BillyONeal: there was a external/extern feature once but somebody did not like it. The idea was if you install `lapack[core, extern]` the `lapack` port simply checked if `find_package(LAPACK)` finds something. anyway the ports needs updating for the intel-mkl port which should also be able to supply blas/lapack functionality

2020-11-03 03:13 UTC, BillyONeal commented
@Neumann-A I see, so the comment is just wrong and should be removed from both places?

2020-11-03 10:43 UTC, Neumann-A commented
@BillyONeal: I still think the port should be used to test if `find_package(BLAS/LAPACK)` works. Maybe rename the project and remove the comment.

2020-11-03 23:18 UTC, BillyONeal commented
@Neumann-A That's fine, I'm objecting to the comment, not the behavior

2020-11-04 06:39 UTC, BillyONeal approved these changes

2020-11-18 21:55 UTC, merged

2020-11-18 21:55 UTC, strega-nil commented
Thanks @cenit, this is great :)