update Yara from v3.10.0 to v4.0.2
microsoft/vcpkg pull request #13478
Opened 2020-09-11 11:36 UTC by N3mes1s

This will update the current port for Yara (v3.10.0) to support v4.0.2

2020-09-11 19:23 UTC, ras0219-msft requested changes
LGTM once the Version field is changed.

It would be nice to use GLOBs in the buildsystem replacement to avoid needing these changes on future updates, but this is fine for now.

2020-09-11 19:23 UTC, ras0219-msft commented on ports/yara/CONTROL
> +Version: 4.0.2-0
```suggestion
Version: 4.0.2
```

2020-09-14 03:10 UTC, NancyLi1013 commented
Hi @N3mes1s 

Would you like to update CMakeLists.txt as the suggestion from @ras0219-msft ?

2020-09-14 06:59 UTC, N3mes1s commented
Sorry i m missing something here! what do you need me to do?

2020-09-15 01:41 UTC, NancyLi1013 commented
> Sorry i m missing something here! what do you need me to do?

Use GLOBs to set the source files that are needed to be compiled.

`file(GLOB/GLOB_RECURSE ...)`

> LGTM once the Version field is changed.
> 
> It would be nice to use GLOBs in the buildsystem replacement to avoid needing these changes on future updates, but this is fine for now.

Of course, if you don't, this is still ok.

2020-10-22 16:39 UTC, MFMokbel commented
This issue is pending an author response as per the label "requires:author-response". @N3mes1s is this is something you can do? Perhaps the author of Yara has to do that change at the repo level. @NancyLi1013 can you carry on without that change request?

2020-10-23 06:03 UTC, NancyLi1013 approved these changes

2020-10-23 06:05 UTC, NancyLi1013 commented
@MFMokbel 
Thanks for your kindly reminder.

I merge master to retrigger CI. It seems good now. 
Let's wait for the CI test results.

2020-10-23 11:59 UTC, N3mes1s commented
Yes, sorry about that. I will open a PR with the requested changes later on.

2020-10-23 18:53 UTC, merged

2020-10-23 18:53 UTC, BillyONeal commented
Thanks for your contribution!

2020-10-23 19:25 UTC, MFMokbel commented
Thanks all!