[vcpkg_find_acquire_program] add gettext's msgmerge program
microsoft/vcpkg pull request #13532
Opened 2020-09-15 01:38 UTC by wrobelda

**Describe the pull request**

Adds support for gettext's msgmerge program

- What does your PR fix? Fixes #8692

- Which triplets are supported/not supported? Have you updated the CI baseline?
Downloads tool for Windows, adds hints for macOS and Linux.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes. Note that I intentionally did not replace the program name and version in the URL with variables because the upstream zip also includes the iconv binaries, so to not mislead a future updater that updating a version variable is enough.

2020-09-15 02:18 UTC, JackBoosY requested changes

2020-09-15 02:18 UTC, JackBoosY commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +    set(URL "https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.21-v1.16/gettext0.21-iconv1.16-static-32.zip")
gettext can be built on Windows, so do we need this?

2020-09-15 03:33 UTC, wrobelda commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +    set(URL "https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.21-v1.16/gettext0.21-iconv1.16-static-32.zip")
I would suggest that we need consistency: either gettext should to deliver \bin tools for _each_ platform, or vcpkg_find_acquire_program should do so instead. I could not get your gettext build running on macOS nor Windows, and one of the key KDE Frameworks depends on it, so I proposed this for the time being – until the actual gettext gets fixed.

2020-09-15 07:14 UTC, Neumann-A commented
theoretically #11776 can built all of gettext but that is currently blocked by #12936

2020-09-15 09:14 UTC, JackBoosY approved these changes

2020-09-16 00:12 UTC, wrobelda commented
/azp run

2020-09-16 00:13 UTC, wrobelda commented
@JackBoosY looks like osx build has stalled and was killed, hence the failure. Mind triggering the build again?

2020-09-17 01:09 UTC, wrobelda commented
On a second thought, while this allows ports to use the msmerge, it requires modification of the personal project's CMakeList as well, should it also require `msgmerge`.

Moreover, `brew install gettext` or `apt install gettext` would be required for macOS\Linux hosts as well as for your CI runs, which can potentially cause conflicts with the gettext library installed using a portfile.

2020-09-17 01:18 UTC, wrobelda commented
> theoretically #11776 can built all of gettext but that is currently blocked by #12936

When you say "theoretically", does it mean it does that already but e.g. it hasn't been tested, or does it require additional work?

2020-09-17 02:25 UTC, JackBoosY commented
Fine, please ping me if this issue needs to be considered.

2020-09-17 02:25 UTC, closed without merging

2021-03-06 00:19 UTC, wrobelda commented
@JackBoosY unfortunately, the vcpkg's native gettext implementation did not eventually arrive with the generator tools included. I can't find it now, but I saw @Neumann-A confirming it somewhere in https://github.com/microsoft/vcpkg/pull/11776 or related PRs. 
 
From the conversation [I had with @ras0219 on Slack](https://cpplang.slack.com/archives/C7BFF7RCJ/p1614637296024600),  it seems that the current approach remains the same as before, i.e. to use the msys2 gettext package on Windows in case tools are needed: 

> I believe right now what generally happens is that on Linux/OSX we expect the generator tools from your system and on Windows we get the generator tools from msys2.

Therefore I believe that this PR adding `msgmerge` to `vcpkg_find_acquire_program` takes things a step forward.  Ideally, all generator tools should be added, too.

I would appreciate your input and hopefully the correct approach to gettext usage can find its way into official Maintainer Guidelines.

2021-03-06 21:56 UTC, Neumann-A commented
https://github.com/microsoft/vcpkg/pull/14333/commits/cd0c4444a845a84e1ddae98a5bbfdbc82ad15782 adds feature tools to gettext. I don't know when I have time to move it out into a separate PR. 
Building all the tools requires some time and also another patch to make autopoint und gettextsize relocatable. (Both are shellscripts hardcoding an absolute prefix.)

2021-03-09 06:21 UTC, JackBoosY commented
See https://github.com/microsoft/vcpkg/pull/16612