[pcre] Export cmake targets
microsoft/vcpkg pull request #13539
Opened 2020-09-15 08:23 UTC by PhoebeHui

Export cmake targets for pcre

Related to https://github.com/microsoft/vcpkg/pull/10326#discussion_r483215122

2020-09-17 09:35 UTC, JackBoosY approved these changes

2020-09-28 01:32 UTC, ras0219-msft requested changes

2020-09-28 01:32 UTC, ras0219-msft commented on ports/pcre/export-cmake-targets.patch
> ++        EXPORT ${target}-targets
```suggestion
+        EXPORT pcre-targets
```

2020-09-28 01:32 UTC, ras0219-msft commented on ports/pcre/export-cmake-targets.patch
> ++    INSTALL(EXPORT ${target}-targets
Move this export out of the `foreach()` loop and install `pcre-targets` once.

2020-09-28 01:32 UTC, ras0219-msft commented on ports/pcre/unofficial-pcre-config.cmake
> +include("${CMAKE_CURRENT_LIST_DIR}/unofficial-pcre-targets.cmake")
With the changes above, this only needs to include `unofficial-pcre-targets.cmake`

2020-09-28 01:32 UTC, ras0219-msft commented on ports/pcre/unofficial-pcre-config.cmake
> +set(PCRE_INCLUDE_DIR ${CMAKE_CURRENT_LIST_FILE}/../../include)
We do not need to provide these variables; instead we should encourage users to use the targets directly

2020-09-28 01:32 UTC, ras0219-msft commented on ports/pcre/usage
> +The package pcre provides CMake targets:
This file should be removed and we should ensure the automatic cmake guidance is sufficient

2020-09-28 01:32 UTC, ras0219-msft commented on ports/pcre/export-cmake-targets.patch
> ++foreach(target ${targets})
These targets may need to have
```cmake
target_include_directories(${target} PUBLIC $<INSTALL_INTERFACE:include>)
```

2020-10-21 07:51 UTC, PhoebeHui commented on ports/pcre/export-cmake-targets.patch
> ++        EXPORT ${target}-targets
Updated, thanks for your guidlines!

2020-10-21 07:51 UTC, PhoebeHui commented on ports/pcre/export-cmake-targets.patch
> ++    INSTALL(EXPORT ${target}-targets
Updated, thanks!

2020-10-21 07:51 UTC, PhoebeHui commented on ports/pcre/unofficial-pcre-config.cmake
> +include("${CMAKE_CURRENT_LIST_DIR}/unofficial-pcre-targets.cmake")
Fixed, thanks!

2020-10-21 07:52 UTC, PhoebeHui commented on ports/pcre/unofficial-pcre-config.cmake
> +set(PCRE_INCLUDE_DIR ${CMAKE_CURRENT_LIST_FILE}/../../include)
Updated, thanks for your review!

2020-10-21 07:52 UTC, PhoebeHui commented on ports/pcre/usage
> +The package pcre provides CMake targets:
Removed, thanks for pointing out this!

2020-10-21 07:53 UTC, PhoebeHui commented on ports/pcre/export-cmake-targets.patch
> ++foreach(target ${targets})
Updated, thanks!

2020-10-27 00:44 UTC, ras0219 approved these changes

2020-10-27 00:44 UTC, merged

2020-10-27 00:45 UTC, BillyONeal commented
Thanks for your contribution!