[many ports] 2019.09.14 Updates
microsoft/vcpkg pull request #13536
Opened 2020-09-15 06:45 UTC by ras0219-msft

Rollup of automatable updates using the ports-update script at https://github.com/ras0219-msft/vcpkg/tree/dev/roschuma/port-upgrades/scripts/port-upgrades (328269a)

2020-09-15 09:39 UTC, JackBoosY commented
The failed ports will be fixed in other PRs.

2020-09-16 02:56 UTC, JackBoosY commented
Addtional 13 ports will be updated and fixed in other PRs.

2020-09-16 06:18 UTC, JackBoosY commented
asio will cancel the update due to upstream issue https://github.com/Corvusoft/restbed/issues/370.

2020-09-16 06:37 UTC, ras0219 commented on ports/fmt/portfile.cmake
> +    REF cd4af11efc9c622896a3e4cb599fa28668ca3d05 # 7.0.3
This should be reverted

2020-09-16 06:46 UTC, JackBoosY commented on ports/fmt/portfile.cmake
> +    REF cd4af11efc9c622896a3e4cb599fa28668ca3d05 # 7.0.3
@ras0219 This can be done without revert, because the next update using the script will still affect the line, and there is no specific modification here.

2020-09-16 07:25 UTC, PhoebeHui requested changes
The 'Port-Version' should be removed.

2020-09-16 07:25 UTC, PhoebeHui commented on ports/alembic/CONTROL
>  Port-Version: 1
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui requested changes

2020-09-17 06:58 UTC, PhoebeHui commented on ports/freetype-gl/CONTROL
>  Port-Version: 4
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/gdcm/CONTROL
>  Port-Version: 2
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/harfbuzz/CONTROL
>  Port-Version: 1
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/io2d/CONTROL
>  Port-Version: 3
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/lcms/CONTROL
>  Build-Depends:
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/libcopp/CONTROL
>  Port-Version: 1
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/libmariadb/CONTROL
>  Port-Version: 2
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/nanodbc/CONTROL
>  Port-Version: 9
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/openmvg/CONTROL
>  Port-Version: 1
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/pcl/CONTROL
>  Port-Version: 2
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/urdfdom-headers/CONTROL
> +Port-Version: 1
```suggestion
```

2020-09-17 06:58 UTC, PhoebeHui commented on ports/wavpack/CONTROL
>  Port-Version: 3
```suggestion
```

2020-09-17 07:50 UTC, JackBoosY commented
Should be okay now.

2020-09-17 14:24 UTC, JackBoosY approved these changes

2020-09-17 19:51 UTC, ras0219-msft commented on ports/devil/portfile.cmake
>          -DIL_NO_PNG=${IL_NO_PNG}
The settings present through `FEATURE_OPTIONS` need to be removed from this list.

2020-09-17 19:52 UTC, ras0219-msft commented on ports/devil/portfile.cmake
> -set(IL_USE_DXTC_NVIDIA 0)
This is not handled via `vcpkg_check_features()` and still needs to be set separately.

2020-09-17 19:53 UTC, ras0219-msft commented on ports/fmt/portfile.cmake
> +    REF cd4af11efc9c622896a3e4cb599fa28668ca3d05 # 7.0.3
Changing the bytes of the file results in a cache invalidation, that's why it's important to avoid trivial nonfunctional changes.

2020-09-17 19:58 UTC, ras0219-msft commented on ports/qt5-base/cmake/qt_download_submodule.cmake
> +    cmake_parse_arguments(_csc "" "OUT_SOURCE_PATH" "PATCHES;BUILD_OPTIONS;BUILD_OPTIONS_RELEASE;BUILD_OPTIONS_DEBUG" ${ARGN})
Why was this change made?

2020-09-18 02:04 UTC, JackBoosY commented on ports/devil/portfile.cmake
>          -DIL_NO_PNG=${IL_NO_PNG}
Oh I missed that.

2020-09-18 02:10 UTC, JackBoosY commented on ports/qt5-base/cmake/qt_download_submodule.cmake
> +    cmake_parse_arguments(_csc "" "OUT_SOURCE_PATH" "PATCHES;BUILD_OPTIONS;BUILD_OPTIONS_RELEASE;BUILD_OPTIONS_DEBUG" ${ARGN})
@ras0219 @ras0219-msft 
When `PATCHES` and `BUILD_OPTIONS` and other parameters are passed into `qt_submodule_installation` at the same time, `qt_submodule_installation` will pass all the parameters into `qt_download_submodule` as a whole(`${ARGN}`), causing `qt_download_submodule` to think that keywords such as `BUILD_OPTIONS` are the values of the parameters.

2020-09-19 00:22 UTC, ras0219-msft commented on ports/devil/0004_compatible-jasper-2-0-20.patch
> ++#ifdef __APPLE__
This is extremely strange; what specific error required this change?

2020-09-19 02:43 UTC, JackBoosY commented on ports/devil/0004_compatible-jasper-2-0-20.patch
> ++#ifdef __APPLE__
Jasper provides a different list of parameters of the same function in different platforms.

2020-09-21 08:09 UTC, PhoebeHui approved these changes

2020-09-28 01:24 UTC, ras0219-msft commented
@PhoebeHui @JackBoosY This LGTM as is; please merge it with master.

2020-09-29 09:39 UTC, PhoebeHui commented
Revert libideviceactivation, and would update in https://github.com/microsoft/vcpkg/pull/1381.

2020-10-08 19:41 UTC, BillyONeal commented
osg failures look legit

2020-10-09 09:13 UTC, JackBoosY commented
osg regression will be fixed in #13942.

2020-10-13 20:17 UTC, merged

2020-10-13 20:17 UTC, dan-shaw commented
Thanks everyone!