[nng] Update to 1.3.2
microsoft/vcpkg pull request #13545
Opened 2020-09-15 15:08 UTC by myd7349

**Describe the pull request**

- What does your PR fix?
Update `nng` to 1.3.2 (bug fixes).

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-09-16 02:56 UTC, NancyLi1013 commented on ports/nng/portfile.cmake
> +    #PREFER_NINJA
Why do you disable `PREFER_NINJA` here?

2020-09-17 00:29 UTC, myd7349 commented on ports/nng/portfile.cmake
> +    #PREFER_NINJA
> 
> 
> Why do you disable `PREFER_NINJA` here?

It failed to install `nng` on my PC before when `ninja` is enabled. I will test it again.

2020-09-17 01:37 UTC, NancyLi1013 approved these changes

2020-09-17 01:39 UTC, NancyLi1013 commented
Looks work fine now. 
Have you tested these features in this PR?

2020-09-17 04:01 UTC, myd7349 commented
> 
> 
> Looks work fine now.
> Have you tested these features in this PR?

Yes.

2020-09-21 03:34 UTC, ras0219-msft requested changes
LGTM once my comment is addressed. Thanks for the PR!

2020-09-21 03:34 UTC, ras0219-msft commented on ports/nng/portfile.cmake
>          -DNNG_ENABLE_NNGCAT=OFF
```suggestion
```
This is provided by the `vcpkg_check_features()` above

2020-09-24 19:25 UTC, merged

2020-09-24 19:25 UTC, ras0219-msft commented
Thanks for the PR!