[v-hacd] Fix cmake patch for include files
microsoft/vcpkg pull request #13549
Opened 2020-09-15 20:32 UTC by FabienPean

This PR is an attempt at fixing the v-hacd port. It fixes the target include directory so that the public include file `VHACD.h` can be found in the include path. It also stops installing the private header files in order to reduce clutter.

I think the patch+portfile from the port (and also the CMakeLists from the project repository) could benefit from some rework (cleanup, simplification, fix of shared library), unfortunately I am unable to do it at the moment. The changes are the minimum I had to do to make it work on my machine.

- Which triplets are supported/not supported? Have you updated the CI baseline?
Tested with x64-windows and VS2019. What is the CI baseline ?

Let me know if anything is missing or feel free to take over from here.

2020-09-16 01:24 UTC, ras0219-msft requested changes
Thanks for the PR! Please also modify the `CONTROL` file to introduce a `Port-Version: 1` below the current `Version:` field.

2020-09-16 01:24 UTC, ras0219-msft commented on ports/v-hacd/fix-cmake.patch
> ++        $<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include/>)
```suggestion
+        $<INSTALL_INTERFACE:include>)
```
The `INSTALL_INTERFACE` is automatically relative to `CMAKE_INSTALL_PREFIX`

2020-09-16 01:24 UTC, ras0219-msft commented on ports/v-hacd/fix-cmake.patch
> ++  $<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include/>  # <prefix>/include/mylib
This change shouldn't be needed; INSTALL_INTERFACE in PRIVATE does nothing.

2020-09-16 09:25 UTC, FabienPean commented
Thanks for the review, I amended the commit with the requested changes.

2020-09-17 10:16 UTC, PhoebeHui approved these changes
LGTM, thanks for the PR!

2020-09-28 05:57 UTC, PhoebeHui commented
/azp run

2020-10-09 05:15 UTC, merged

2020-10-09 05:15 UTC, BillyONeal commented
Thanks for your contribution!