[libconfig] init #1343
microsoft/vcpkg pull request #1366
Opened 2017-06-28 21:07 UTC by atkawa7

2017-06-28 21:07 UTC, msftclas commented
@atkawa7,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by Microsoft. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-06-29 09:14 UTC, jtravs commented on ports/libconfig/CONTROL
> +Description: Library for collision detection between two convex shapes
I guess this is copied from somewhere. Perhaps
```C/C++ library for processing configuration files```

2017-06-29 12:29 UTC, atkawa7 commented on ports/libconfig/CONTROL
> +Description: Library for collision detection between two convex shapes
@jtravs Yep the trouble of copy and paste programming

2017-06-29 19:34 UTC, ras0219-msft requested changes

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/portfile.cmake
> +set(MIINTTYPES_HOME ${VCPKG_ROOT_DIR}/packages/msinttypes_${TARGET_TRIPLET})
You shouldn't rely on the structure of the packages directory.

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +if(BUILD_SHARED)
Use the standard CMake variable `BUILD_SHARED_LIBS` to determine if you need to build shared or static

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +  add_library(libconfig SHARED ${C_SOURCES})
These add_library calls can be lifted out of the `if()/else()` by just removing the `STATIC` and `SHARED`. If the library type isn't listed, CMake will choose `STATIC` or `SHARED` based on the `BUILD_SHARED_LIBS` setting (which we set automatically based on `VCPKG_LIBRARY_LINKAGE`).

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +file(COPY ${C_HEADERS} DESTINATION ${COMMON_INCLUDES})
Generally, you shouldn't need to copy files into the output directory if they're just being read from (like most header files).

The only files that need to get copied would be those that change based on the build configuration, such as generated headers.

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +  ${SOURCE_PATH}/grammar.h
Most CMake commands (including `add_library()`) interpret paths relative to the location of the CMakeLists.txt -- in this case, that would be the same as `${PROJECT_SOURCE_DIR}`.

Lists of headers and sources can be made simpler by just writing `lib/grammar.h` instead of having a longer variable above.

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +  ${SOURCE_PATH}/libconfigcpp.c++
This looks like it should be a source file -- is it really a header?

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/portfile.cmake
> +endif()
If the CMakeLists.txt relies on `BUILD_SHARED_LIBS`, this is not needed.

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/scandir.c
> +// "$Id: scandir.c 1339 2006-04-03 22:47:29Z spitzak $"
Could you write a few sentences about why this file is here and where it came from?

2017-06-29 19:34 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +  install(DIRECTORY "${COMMON_INCLUDES}/" DESTINATION include)
Often libraries really only want to install a subset of their headers -- just the "public" ones, not the "private" ones.

2017-06-29 19:43 UTC, atkawa7 commented on ports/libconfig/scandir.c
> +// "$Id: scandir.c 1339 2006-04-03 22:47:29Z spitzak $"
@ras0219-msft The reason was windows does not have scandir. However it is required by the library to build it. This code aims to emulate that and is taken from [`http://www.fltk.org/strfiles/1779/scandir.c`](http://www.fltk.org/strfiles/1779/scandir.c)

2017-06-29 19:44 UTC, atkawa7 commented on ports/libconfig/portfile.cmake
> +set(MIINTTYPES_HOME ${VCPKG_ROOT_DIR}/packages/msinttypes_${TARGET_TRIPLET})
@ras0219-msft What are you suggestions on this one ?

2017-06-29 19:45 UTC, atkawa7 commented on ports/libconfig/portfile.cmake
> +endif()
@ras0219-msft  Thanks I am learning

2017-06-29 19:47 UTC, atkawa7 commented on ports/libconfig/portfile.cmake
> +endif()
@ras0219-msft Thanks. So if you add it to source. Does it affect this [part ](https://github.com/hyperrealm/libconfig/blob/5a06a161afacce6e32491db33781dab2f216df71/lib/libconfigcpp.cc#L23)?

2017-06-29 19:49 UTC, atkawa7 commented on ports/libconfig/CMakeLists.txt
> +  install(DIRECTORY "${COMMON_INCLUDES}/" DESTINATION include)
@ras0219-msft Just wondering, how do you tell which ones are public and which ones are not?

2017-06-29 19:56 UTC, atkawa7 commented on ports/libconfig/CMakeLists.txt
> +  ${SOURCE_PATH}/libconfigcpp.c++
@ras0219-msft Thanks. So if you add it to source. Does it affect this [part ](https://github.com/hyperrealm/libconfig/blob/5a06a161afacce6e32491db33781dab2f216df71/lib/libconfigcpp.cc#L23)?

2017-06-29 20:50 UTC, atkawa7 commented
@ras0219-msft Changes requested added

2017-06-29 21:53 UTC, ras0219-msft commented on ports/libconfig/CMakeLists.txt
> +  install(DIRECTORY "${COMMON_INCLUDES}/" DESTINATION include)
I'd look at the existing buildsystem's install script. If that fails, I'd look at their examples. Typically the headers will be organized such that all the headers in some subfolder are "public" headers, with all the other headers (perhaps intermixed with the sources) are private.

2017-06-29 21:55 UTC, ras0219-msft commented on ports/libconfig/portfile.cmake
> +set(MIINTTYPES_HOME ${VCPKG_ROOT_DIR}/packages/msinttypes_${TARGET_TRIPLET})
In this case, the CMakeLists.txt should probably simply use `find_path(DIRENT_H dirent.h)` and then `include_directories(${DIRENT_H})`. This will find the header inside the current installed directory and as a bonus is totally portable to other systems.

2017-06-29 22:22 UTC, atkawa7 commented on ports/libconfig/portfile.cmake
> +set(MIINTTYPES_HOME ${VCPKG_ROOT_DIR}/packages/msinttypes_${TARGET_TRIPLET})
@ras0219-msft Thanks. I have added it. Looks more nicer than using directories

2017-06-29 22:41 UTC, atkawa7 commented
@ras0219-msft. I think msinttypes is polluting the environment. It has a header stdint.h which is required libconfig. How do you deal with that?

```
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe
          /c /I..\include /I"C:\src\vcpkg\installed\x86-windows\include" /Zi /nologo /W3 /WX- /diagnostics:classic /sdl
          /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-6acb7526f8deefdd61b2b1dadd7ca1fea157a50b" /D _MB
         CS /D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"Re
         lease\vcpkglib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++late
         st ..\src\pch.cpp
         pch.cpp
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\ratio(112): erro
       r C2065: 'INTMAX_MAX': undeclared identifier [C:\src\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\ratio(124): no
         te: see reference to class template instantiation 'std::ratio<_Nx,_Dx>' being compiled
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\ratio(114): erro
       r C2065: 'INTMAX_MAX': undeclared identifier [C:\src\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\ratio(28): error
        C2065: 'INTMAX_MAX': undeclared identifier [C:\src\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\ratio(166): no
         te: see reference to class template instantiation 'std::_Ratio_add<_R1,_R2>' being compiled
     3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\ratio(217): erro
       r C2338: integer arithmetic overflow [C:\src\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\chrono(970): n
         ote: see reference to class template instantiation 'std::_Ratio_mu
```

This is after I installed it. When I build everything it fails

2017-06-30 08:37 UTC, muemart commented
msinttypes isn't necessary, I think. Those headers were missing in ancient MSVC versions, but are there now.

2017-06-30 19:18 UTC, atkawa7 commented
@codicodi @ras0219-msft  Do you mind reviewing this?

2017-07-01 22:55 UTC, codicodi commented
@muemart is right, `stdint.h` is part of the standard library, so we really don't need to package it

2017-07-01 22:57 UTC, codicodi commented on ports/libconfig/CMakeLists.txt
> +add_library(libconfig++ ${C_SOURCES} ${CPP_SOURCES})
Isn't there way to make the C++ library link to the C one, so that symbola wouldn't be duplicated?

2017-07-01 23:03 UTC, codicodi commented on ports/libconfig/scandir.c
> +int scandir(const char *dirname, struct dirent ***namelist,
Defininfg `scandir` like this is IMHO pretty dangerous as it may easily collide with user code. Could you rename it to `libconfig_scandir` and then add `-Dscandir=libconfig_scandir` to compilation flags?

2017-07-01 23:15 UTC, atkawa7 commented on ports/libconfig/scandir.c
> +int scandir(const char *dirname, struct dirent ***namelist,
@codicodi I am not sure  I understand what you mean by collision as currently there isn't any `scandir.c` file  in the project.

2017-07-01 23:19 UTC, atkawa7 commented on ports/libconfig/CMakeLists.txt
> +add_library(libconfig++ ${C_SOURCES} ${CPP_SOURCES})
Thanks @codicodi . Will change that part

2017-07-01 23:28 UTC, codicodi commented on ports/libconfig/scandir.c
> +int scandir(const char *dirname, struct dirent ***namelist,
Vcpkg user may define his/her own `scandir`, which may conflict with the one defined here

2017-07-01 23:33 UTC, atkawa7 commented on ports/libconfig/scandir.c
> +int scandir(const char *dirname, struct dirent ***namelist,
@codicodi I see. Thanks for clarifying

2017-07-04 04:32 UTC, atkawa7 commented
@codicodi @ras0219-msft updated the PR

2017-07-06 12:41 UTC, atkawa7 commented
@ras0219-msft Could you review new changes on this one?

2017-07-10 22:11 UTC, merged

2017-07-10 22:11 UTC, ras0219-msft commented
Thanks!