[manyports] Update version 3
microsoft/vcpkg pull request #13677
Opened 2020-09-23 08:02 UTC by JackBoosY

Continue PR #13558

2020-09-24 02:46 UTC, LilyWangL approved these changes

2020-09-24 20:36 UTC, ras0219-msft requested changes

2020-09-24 20:36 UTC, ras0219-msft commented on ports/capnproto/portfile.cmake
> -	PATCHES "${CMAKE_CURRENT_LIST_DIR}/0001-fix-capnpc-extension-handling-on-Windows.patch"
This PR should also remove the patch file.

2020-09-25 02:11 UTC, JackBoosY commented on ports/capnproto/portfile.cmake
> -	PATCHES "${CMAKE_CURRENT_LIST_DIR}/0001-fix-capnpc-extension-handling-on-Windows.patch"
@ras0219-msft Thanks for notice.

2020-09-25 02:42 UTC, JackBoosY commented
Blocked by #13722.

2020-09-27 06:57 UTC, JackBoosY commented
blocked by #13765.

2020-09-28 00:54 UTC, merged