[libtins] Update to version 4.3
microsoft/vcpkg pull request #13681
Opened 2020-09-23 08:14 UTC by cnbatch

Update `libtins` to version 4.3 and enables C++11 support.

2020-09-23 08:35 UTC, JackBoosY requested changes

2020-09-23 08:35 UTC, JackBoosY commented on ports/libtins/portfile.cmake
> +        -DLIBTINS_ENABLE_CXX11=1
This requires a judgment, if the current compiler does not support c11, we should not add this parameter.
See https://github.com/microsoft/vcpkg/pull/12612/commits/a11b055c3a1989ee87b1f4a4ee5046d37d1fc105

2020-09-23 09:16 UTC, cnbatch commented on ports/libtins/portfile.cmake
> +        -DLIBTINS_ENABLE_CXX11=1
It's not C11.

2020-09-24 13:12 UTC, cnbatch reviewed
C++11 is not C11. They're not the same.

2020-09-24 13:12 UTC, cnbatch commented on ports/libtins/portfile.cmake
> +        -DLIBTINS_ENABLE_CXX11=1
As I mentioned in comment, this option is for C++11 (ISO/IEC 14882:2011) only. If a compiler supports vcpkg (Visual Studio 2015 Update 3 or greater / g++ >= 6), it's also supports this option too.
C11 (ISO/IEC 9899:2011) is irrelevant to this option here.

2020-09-24 20:43 UTC, merged

2020-09-24 20:43 UTC, ras0219-msft commented
LGTM, thanks for the PR!