[atk][exiv2][gdk-pixbuf][gettext][glib][libcroco][tesseract] Replace uses of unofficial-gettext with FindIntl
microsoft/vcpkg pull request #13762
Opened 2020-09-27 00:34 UTC by ras0219

See title.

We prefer supporting built-in cmake modules whenever possible instead of providing our own replacements.

2020-11-18 22:01 UTC, strega-nil commented
I think this might've been fixed already by @Neumann-A in #11776, no?

2020-12-11 07:02 UTC, PhoebeHui commented
After compared with PR https://github.com/microsoft/vcpkg/pull/11776, the changes for atk and gettext still needed, I will help to undo changes for other ports and resolve the conflicts.

2020-12-11 09:52 UTC, PhoebeHui requested changes
@ras0219, I think we need check if unofficial-gettext exist.

2020-12-11 09:52 UTC, PhoebeHui commented on ports/gettext/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH share/unofficial-gettext TARGET_PATH share/unofficial-gettext)
The CI failed with following errors:

```
Make Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:126 (message):
  'D:/packages/gettext_x64-windows-static/debug/share/unofficial-gettext'
  does not exist.
Call Stack (most recent call first):
  ports/gettext/portfile.cmake:63 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:136 (include)
```

2020-12-11 10:04 UTC, Neumann-A commented on ports/gettext/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH share/unofficial-gettext TARGET_PATH share/unofficial-gettext)
it does not exists anymore since gettext was changed to native build which is make based

2021-01-06 15:11 UTC, closed without merging