[vcpkg] Add script to generate version database files
microsoft/vcpkg pull request #13777
Opened 2020-09-28 04:14 UTC by vicroms

This PR includes the following changes:

* Modifies `x-history` to produce JSON output when using the `--json` switch. The command makes an attempt to separate the package version from the port version in CONTROL files using legacy version strings.

* Adds a Python script that uses `x-history` to generate version database files for all ports. For each port a `<port_name>.db.json` file is created and placed into a  folder specified as a parameter in the script.

2020-09-28 04:27 UTC, vicroms commented
I'm not sure whether to check in the db files, there are too many of them. 
Right now the DB files are one per port (located inside `scripts/port_versions_db` and use JSON format. Generating them took about 1 hour on my computer.

Also, it seems like I forgot to clean up some unrelated code.

2020-09-28 20:03 UTC, ras0219-msft requested changes
Thanks for opening this PR!

I haven't finished reading more deeply into the algorithm, but here are some more trivial comments.

2020-09-28 20:03 UTC, ras0219-msft commented on toolsrc/src/vcpkg/versions.cpp
> +    const auto working_dir = paths.root / "vcpkg-temp";
```suggestion
    const auto working_dir = paths.buildtrees / "versioning_tmp";
```
because underscores are not valid port names, this will avoid creating a new root folder and won't collide with ports.

2020-09-28 20:03 UTC, ras0219-msft commented on toolsrc/src/vcpkg/versions.cpp
> +
```suggestion
```

2020-09-28 21:03 UTC, vicroms commented on toolsrc/src/vcpkg/versions.cpp
> +    auto output = run_git_command(paths, working_dir, "clone https://github.com/microsoft/vcpkg vcpkg-temp");
Implemented `--no-checkout` but I'm not sure what you mean about how to use the local `.git` dir.

2020-09-28 21:04 UTC, vicroms commented on toolsrc/src/vcpkg/commands.porthistory.cpp
> +                Strings::format(R"("%s" --git-dir="%s" %s)", fs::u8string(git_exe), fs::u8string(dot_git_dir), cmd);
I'll look into this next

2020-09-28 22:10 UTC, ras0219-msft commented on toolsrc/src/vcpkg/versions.cpp
> +    auto output = run_git_command(paths, working_dir, "clone https://github.com/microsoft/vcpkg vcpkg-temp");
We could clone from `paths.root` instead of github, possibly running a `fetch` from github afterwards if a commit is missing.

2020-09-28 22:29 UTC, vicroms commented on toolsrc/src/vcpkg/versions.cpp
> +    auto output = run_git_command(paths, working_dir, "clone https://github.com/microsoft/vcpkg vcpkg-temp");
Got it, I'll take a look at the `git clone` docs.

2020-09-28 23:07 UTC, vicroms commented on toolsrc/src/vcpkg/versions.cpp
> +    auto output = run_git_command(paths, working_dir, "clone https://github.com/microsoft/vcpkg vcpkg-temp");
Done

2020-10-21 21:26 UTC, ras0219 requested changes

2020-10-21 21:26 UTC, ras0219 commented on toolsrc/src/vcpkg/sourceparagraph.cpp
> +        if (maybe_dependencies.has_value())
This change causes failures to result in a "successful" return with no dependencies.

Instead, this needs to return the failure.

2020-10-21 21:41 UTC, ras0219 requested changes
I've lightly reviewed the changes to port history since that's an `x-` command.

2020-10-21 21:41 UTC, ras0219 commented on toolsrc/src/vcpkg/paragraphs.cpp
> +        const ExpectedT<std::pair<vcpkg::Json::Value, vcpkg::Json::JsonStyle>, std::unique_ptr<Parse::IParseError>>&
It's very strange to pass an `ExpectedT` as an argument; it would be better for the caller to have handled any errors first and just pass extracted `Json::Value`.

2020-10-21 21:41 UTC, ras0219 commented on toolsrc/src/vcpkg/sourceparagraph.cpp
> +            spgh->default_features = maybe_default_features.value_or_exit(VCPKG_LINE_INFO);
This shouldn't drop the error information (see above).

2020-10-21 22:09 UTC, vicroms commented on toolsrc/src/vcpkg/paragraphs.cpp
> +        const ExpectedT<std::pair<vcpkg::Json::Value, vcpkg::Json::JsonStyle>, std::unique_ptr<Parse::IParseError>>&
It is strange, but this function is made to avoid repeating the error handling code 😅

2020-10-21 22:14 UTC, vicroms commented on toolsrc/src/vcpkg/paragraphs.cpp
> +        // TODO: Handle Json::parse(text) errors
Forgot to remove my comment but `try_load_manifest_object(origin, res)` does exactly that.
However, the `error_info` declaration and `if (ec) return error_info;` lines are useless and should be removed.

2020-10-21 22:15 UTC, vicroms commented on toolsrc/src/vcpkg/paragraphs.cpp
> +        const ExpectedT<std::pair<vcpkg::Json::Value, vcpkg::Json::JsonStyle>, std::unique_ptr<Parse::IParseError>>&
If you feel strongly about it, I can refactor it.

2020-10-22 18:50 UTC, strega-nil requested changes
I haven't looked at the rest of the code, but here are the things I see that should be corrected with the python.

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +            os.makedirs(dir_path)
Could be replaced with `os.makedirs(dir_path, exist_ok=True)`

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        print('Couldn\'t fetch current Git revision')
```suggestion
        print('Couldn\'t fetch current Git revision.', file=sys.stderr)
```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        print('Database files already exist for commit {}'.format(revision))
```suggestion
        print(f'Database files already exist for commit {revision}')
```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        quit()
```suggestion
        sys.exit(0)
```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +    main('../ports', '../port_versions')
```suggestion
    main(ports_path=path.join(SCRIPT_DIRECTORY, '../ports'), db_path=path.join(SCRIPT_DIRECTORY, '../port_versions'))

```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +    generate_port_versions_db(ports_path, db_path, revision)
```suggestion
    generate_port_versions_db(ports_path=ports_path, db_path=db_path, revision=revision)

```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        quit()
```suggestion
        sys.exit(1)
```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        print("Failed to get git ref")
```suggestion
    output = subprocess.run(['git', '-C', SCRIPT_DIRECTORY, 'rev-parse', '--verify', 'HEAD'], capture_output=True, encoding='utf-8')
    if output.returncode == 0:
        return output.stdout.strip()
    print('Failed to get current git ref:', output.stderr.strip(), file=sys.stderr)
    return None
```

Few things:

* `subprocess.run` doesn't raise a `CalledProcessError` unless you pass `check=True`
* Correctly outputting to stderr, and outputting the actual error message
* Use `git -C <path>` to make sure that we're using the right git repository
* (minor) returning None if there's an error is better than empty string
* (minor) adding the encoding in `run` is easier.

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +                print("Failed to run {}".format(err.cmd))
```suggestion
            output = subprocess.run([path.join(SCRIPT_DIRECTORY, '../vcpkg'), 'x-history', port_name, '--x-json'], capture_output=True)
            if output.returncode == 0:
                try:
                    versions_object = json.loads(output.stdout)
                    with open(output_filepath, 'w') as output_file:
                        json.dump(versions_object, output_file)
                except JSONDecodeError as json_err:
                    print(f'Malformed JSON from vcpkg x-history {port_name}:', output.stdout, file=sys.stderr))
            else:
                print(f'x-history {port_name} failed:', output.stdout, file=sys.stderr)
```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +
```suggestion

SCRIPT_DIRECTORY = path.dirname(path.abspath(__file__))

```

allows us to use file-relative paths later, rather than CWD-relative.

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        containing_dir = os.path.join(db_path, port_name[0])
```suggestion
        containing_dir = os.path.join(db_path, f'{port_name[0]}-')
```

don't forget the `-` :)

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +        output_filepath = os.path.join(containing_dir, '{}.json'.format(port_name))
```suggestion
        output_filepath = os.path.join(containing_dir, f'{port_name}.json')

```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +            print('Processed {} out of {}. Elapsed time: {:.2f} seconds'.format(counter, total_count, elapsed_time))
```suggestion
            print(f'Processed {counter} out of {total_count}. Elapsed time: {elapsed_time:.2f} seconds'.)
```

2020-10-22 18:50 UTC, strega-nil commented on scripts/generatePortVersionsDb.py
> +    print('Processed {} total ports. Elapsed time: {:.2f} seconds'.format(total_count, elapsed_time))
```suggestion
    print(f'Processed {total_count} total ports. Elapsed time: {elapsed_time:.2f} seconds')
```

2020-10-22 20:54 UTC, ras0219 approved these changes

2020-10-22 23:20 UTC, strega-nil reviewed
Thanks for the changes victor!

2020-10-26 17:24 UTC, merged