Always accept = or space as delimiters when parsing command line parameters.
microsoft/vcpkg pull request #13857
Opened 2020-10-02 23:18 UTC by BillyONeal

Resolves #11456.

2020-10-03 00:06 UTC, BillyONeal commented
CI failed because repo.msys.org is down.

2020-10-05 16:36 UTC, strega-nil requested changes
Those are a few of the things I've noticed, but the big thing I'd like to see is this working for options to commands. This isn't necessary for this first pass, however. The `enum class` thing is a necessity before I approve.

2020-10-05 16:36 UTC, strega-nil commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +                    case 2: ++it; // fallthrough
Should use the `[[fallthrough]]` attribute.

2020-10-05 16:36 UTC, strega-nil commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +    static size_t try_parse_argument_as_option(
This should use an enum return value:

```cxx
enum class ArgumentParseResult {
  Unsuccessful,
  Successful,
  SuccessfulConsumedLookahead
}
```
or something.

2020-10-05 16:36 UTC, strega-nil commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            }
This is a pointer, and therefore this can be much simpler:

```suggestion
            Optional<StringView> lookahead = (it + 1 != arg_last) ? *(it + 1) : Optional<StringView>(nullopt);
```

2020-10-05 18:01 UTC, BillyONeal commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +                    case 2: ++it; // fallthrough
We can't since we want to target older C++ than that attribute.

2020-10-06 17:29 UTC, strega-nil commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +                    case 2: ++it; // fallthrough
We turn off unknown attribute warnings.

2020-10-06 21:56 UTC, ras0219-msft approved these changes
I'd like to see an `enum class` over `size_t` as the return of `try_parse_argument_as_option()`; otherwise LGTM.

2020-10-07 08:20 UTC, BillyONeal commented on toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
> +            }
I hate ternaries so I didn't do exactly that but I did avoid the `next` variable.

2020-10-07 08:27 UTC, BillyONeal commented
@strega-nil Do you have an example command like you want to work for your more complete desired overhaul that doesn't work with the current state of this PR? Out of band you said `--x-feature` but that option doesn't seem to exist...

2020-10-07 16:31 UTC, strega-nil commented
@BillyONeal `--x-feature` is an option for the `install` command, not a global option: https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/install.cpp#L549

2020-10-07 16:32 UTC, strega-nil approved these changes

2020-10-07 16:34 UTC, BillyONeal commented
> @BillyONeal `--x-feature` is an option for the `install` command, not a global option: https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/install.cpp#L549

I tried it with the install command and that didn't work. But I didn't try with a manifest so that likely explains it ¯\_(ツ)_/¯

2020-10-07 16:35 UTC, strega-nil commented
Ah, yeah, it's a manifest-only option.

2020-10-07 17:31 UTC, merged