[tensorflow-c-gpu] Add new port
microsoft/vcpkg pull request #13867
Opened 2020-10-03 14:54 UTC by ianormy

**TensorFlow C API (GPU)**

- This PR adds a new port for the TensorFlow C API (GPU) for Windows. It downloads and builds a package using the prebuilt files provided by the TensorFlow team. [https://www.tensorflow.org/install/lang_c](https://www.tensorflow.org/install/lang_c). This works for the latest version, 2.3.0.

- The only triplets supported are x64-windows

2020-10-03 15:53 UTC, ianormy commented
My support string in the vcpkg.json file clearly tells the CI not to build x86 for Windows, but your CI seems to ignore it. Here's my string:

`"supports": "windows & !x86 & !uwp & !static & !arm"`


Is there something I am missing? Any help would be gratefully appreciated. It should only build **x64-windows**.

Thanks

Ian

2020-10-05 17:35 UTC, ianormy commented
I have checked the logs for the x86_windows build and its failing when trying to build zlib:x86-windows-static. It doesn't appear to be related to my code at all.

2020-10-06 11:53 UTC, RDCH106 commented
Try to exclude from the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) `tensorflow-c-gpu:x64-uwp`

2020-10-09 03:12 UTC, JackBoosY requested changes
What's the different between this port with `tensorflow-cc`?

2020-10-09 03:12 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +tensorflow-c-gpu:x86-windows=fail
Since we have `supports` on manifest, we don't need add this.

2020-10-09 07:57 UTC, NancyLi1013 requested changes

2020-10-09 07:57 UTC, NancyLi1013 commented on ports/tensorflow-c-gpu/portfile.cmake
> +vcpkg_fail_port_install(MESSAGE "tensorflow-c-gpu currently does not support static libraries" ON_LIBRARY_LINKAGE "static")
```suggestion
vcpkg_fail_port_install(ON_ARCH "x86" "arm" ON_TARGET "UWP" "LINUX" "ANDROID" "FREEBSD" "OSX")

vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
```
We use `vcpkg_check_linkage()` to judge if the port supports static or dynamic build.

2020-10-09 08:37 UTC, ianormy commented on ports/tensorflow-c-gpu/portfile.cmake
> +vcpkg_fail_port_install(MESSAGE "tensorflow-c-gpu currently does not support static libraries" ON_LIBRARY_LINKAGE "static")
@NancyLi1013 thanks for the suggested change. I will commit as you have suggested.

2020-10-09 08:40 UTC, ianormy commented on scripts/ci.baseline.txt
> +tensorflow-c-gpu:x86-windows=fail
@JackBoosY I only added this because the *supports* wasn't apparently being parsed correctly. This was suggested previously on this PR as a fix for that.

2020-10-09 08:44 UTC, ianormy commented on scripts/ci.baseline.txt
> +tensorflow-c-gpu:x86-windows=fail
@JackBoosY I started with **tensorflow-cc** but this doesn't build on Windows. That's why I went for using the TensorFlow C API. It's more hard-core, and there's no documentation for it, but it's very fast. I can now load and run inference on my model even quicker than the equivalent Python code!

2020-10-09 08:56 UTC, NancyLi1013 commented
Hi @ianormy 

> I have checked the logs for the x86_windows build and its failing when trying to build zlib:x86-windows-static. It doesn't appear to be related to my code at all.

This failure is not related to your PR. You can ignore it. So this port might support x86, you should remove it from `Supports` field and portfile,cmake. Then let's see the new CI tests. Sorry, I didn't notice your comment before.

Also you can remove the codes added in ci.baseline.txt, since you have added `Supports `field.

2020-10-09 08:58 UTC, NancyLi1013 requested changes

2020-10-09 08:58 UTC, NancyLi1013 commented on ports/tensorflow-c-gpu/vcpkg.json
> +  "supports": "windows & !x86 & !uwp & !static & !arm"
```suggestion
  "supports": "windows & !uwp & !static & !arm"
```

2020-10-10 15:56 UTC, ianormy commented
I've applied the recommended changes by @NancyLi1013  and answered @JackBoosY question. Both of these comments have been resolved but the status still says that both of you require changes that I need to respond to. Is there something else I need to do to resolve this? I can't see any other buttons to press - unless I'm missing something. Please could you let me know if there is something else I should do. Thanks.

2020-10-11 03:55 UTC, JackBoosY requested changes

2020-10-11 03:55 UTC, JackBoosY commented on ports/tensorflow-c-gpu/portfile.cmake
> +file(COPY ${SOURCE_PATH}/lib/tensorflow.lib
Can we build it instead of using the binaries?

2020-10-11 08:11 UTC, ianormy commented on ports/tensorflow-c-gpu/portfile.cmake
> +file(COPY ${SOURCE_PATH}/lib/tensorflow.lib
@JackBoosY Building it would have the same issues as the tensorflow-cc port under Windows. 

I can see this port isn't going to get through this process. It's a great solution for me locally (I've used the same approach for using the onnxruntime on my machine) so I'll leave it at that and abandon this PR. I appreciate your time.

2020-10-11 08:11 UTC, closed without merging