[rbdl] Add new port
microsoft/vcpkg pull request #13884
Opened 2020-10-05 14:50 UTC by RDCH106

**RBDL - Rigid Body Dynamics Library** 

- What does your PR fix? 
  * This PR adds a new port for the RDBL for Windows and Linux. It builds the library downloading it from [official repository](https://github.com/rbdl/rbdl) and making compilation through CMake according to [Packaging Zipfiles guide](https://vcpkg.readthedocs.io/en/latest/examples/packaging-zipfiles).

  * The port only builds the core library and not the optional addons (future work for features).

  * Port was tested in [vcpkg 2020.07](https://github.com/microsoft/vcpkg/releases/tag/2020.07) with [RBDL 2.6.0](https://github.com/rbdl/rbdl/releases/tag/v2.6.0)

- Which triplets are supported/not supported?
  * Expected supported triplets: `(x86|x64) & (windows|linux)`

- Have you updated the CI baseline?
  * Not updated the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  * All the implementation has been done taking into account the [Maintainer Guidelines and Policies](https://vcpkg.readthedocs.io/en/latest/maintainers/maintainer-guide).

2020-10-09 07:43 UTC, NancyLi1013 requested changes

2020-10-09 07:43 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +
```suggestion
```
Please remove these comments here.

2020-10-09 07:43 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +)
```suggestion
vcpkg_from_github(ARCHIVE
    OUT_SOURCE_PATH SOURCE_PATH
    REPO rbdl/rbdl
    REF v2.6.0
    SHA512 7b5fd03c0090277f295a28a1ff0542cd8cff76dda4379b3edc61ca3d868bf77d8b4882f81865fdffd0cf756c613fe55238b29a83bc163fc32aa94aa9d5781480
    HEAD_REF master
    PATCHES 001_x64_number_of_sections_exceeded_in_object_file_patch.diff
)
```
Since the source codes can be downloaded from GitHub, we prefer to use `vcpkg_from_github()` to get the source.

2020-10-09 07:43 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +# )
```suggestion
```
If these features can not work now, it would be better to remove these codes until they can work fine.

2020-10-09 07:43 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/rbdl RENAME copyright)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

2020-10-09 07:43 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME rbdl MODULE)
```suggestion
```
This function doesn't wok now. So please remove it.

2020-10-09 07:43 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> +rbdl:x64-uwp=fail
If it cannot support uwp, we can add it in `Supports `filed. Please also remove this line here.

2020-10-09 08:08 UTC, RDCH106 commented on ports/rbdl/CONTROL
> +Port-Version: 0
According to the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#versioning) Port-Version is correct and no explicit "port-version" is equivalent to a "port-version" of 0. In the future, the change only will update the number of "port-version" avoiding to forget the "port-version" addition.

If there is no problem, I would prefer to keep Port-Version explicitly in the Control file

2020-10-09 08:18 UTC, RDCH106 commented on ports/rbdl/CONTROL
> +Supports: (x86|x64) & (windows|linux)
I suppose yes... I added only triplets that I have tested, but I can add more triplets and test them with the CI.

Currently, I am using also:
- x86-windows-static-md
- x64-windows-static-md

But I think that `x86-windows-static-md` and `x64-windows-static-md` are included in `x86-windows` and `x64-windows`, Right?

2020-10-09 08:26 UTC, RDCH106 commented on ports/rbdl/portfile.cmake
> +)
I didn't know `vcpkg_from_github()`. Thank you for the information! 😉

I followed [Packaging Zipfiles guide](https://vcpkg.readthedocs.io/en/latest/examples/packaging-zipfiles) and I filled the template generated by `vcpkg create` command.

2020-10-09 08:33 UTC, RDCH106 commented on ports/rbdl/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/rbdl RENAME copyright)
More elegant. Thanks!

2020-10-09 08:38 UTC, RDCH106 commented on ports/rbdl/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME rbdl MODULE)
Really??

It was automatically generated by `vcpkg create` command. Maybe comment out the function instead of deleting it?

2020-10-09 08:47 UTC, RDCH106 commented on scripts/ci.baseline.txt
> +rbdl:x64-uwp=fail
I will review the `Supports` field again.

I added it because of CI throwed errors. I don't understand the reason... I needed to include it to exclude it from CI baseline, when the `Supports` field exclude it:

 `(x86|x64) & (windows|linux)`

2020-10-09 08:47 UTC, NancyLi1013 commented on ports/rbdl/CONTROL
> +Supports: (x86|x64) & (windows|linux)
In fact, these triplets are different. But currently, CI will only test `x86-windows`  `x64-windows` and `x64-windows-static`.

Since these two triplets are listed in community folder, which are unofficial triplets.

- x86-windows-static-md
- x64-windows-static-md

In order to make sure if the port can work fine on all triplets, it might be better to remove the Supports field. Let's see the CI check results. What do you think?

2020-10-09 08:49 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME rbdl MODULE)
Yes, we suggest to remove it now. We can add it back until it can work normally.

2020-10-09 08:57 UTC, RDCH106 commented on ports/rbdl/CONTROL
> +Supports: (x86|x64) & (windows|linux)
Good point 👍
Thanks for your time and your help

2020-10-09 09:05 UTC, NancyLi1013 requested changes

2020-10-09 09:05 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +
```suggestion
```
This line seems to be not needed here now.

2020-10-09 09:05 UTC, RDCH106 commented on ports/rbdl/CONTROL
> +Supports: (x86|x64) & (windows|linux)
Supports field removed in the last commit

2020-10-09 09:08 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> +rbdl:x64-uwp=fail
You can also remove this line and then we check the new CI checks. If we can make that it doesn't support uwp, we add it in `Supports` field.

2020-10-09 09:12 UTC, RDCH106 commented on scripts/ci.baseline.txt
> +rbdl:x64-uwp=fail
Done

2020-10-09 14:12 UTC, RDCH106 commented
I am going to update `Supports`  field. It works perfectly for Windows and I am using on Windows.
Linux and OSX remains as future work. ok?

2020-10-09 14:53 UTC, RDCH106 commented
I don't understand... 🤔

The previous build was: https://dev.azure.com/vcpkg/public/_build/results?buildId=43808&view=logs&j=d3670d0c-cc82-50c9-762c-eccde036829f

And the new one: https://dev.azure.com/vcpkg/public/_build/results?buildId=43818&view=logs&j=a83b7983-e539-5449-9e09-337ff5f52283

- Between 2 builds starts failing x86-windows when in the previous one was marked as success
- I exclude `linux` and `osx` in `Supports` field and using `vcpkg_fail_port_install` and they continue failing in CI

@NancyLi1013 any idea or recommendation about that?

Thanks in advance.

2020-10-10 02:12 UTC, NancyLi1013 commented
Hi @RDCH106 
I checked the build results here https://dev.azure.com/vcpkg/public/_build/results?buildId=43808&view=logs&j=d3670d0c-cc82-50c9-762c-eccde036829f and found that:

The failures on Linux and osx are due to this:

`c++: error: /bigobj: No such file or directory`

Since `/bigobj` is only used in MSVC.

The failures on uwp are due to this:

```
CMake Error at ports/rbdl/portfile.cmake:29 (file):
  file COPY cannot find "D:/buildtrees/rbdl/x64-uwp-dbg/rbdl.dll": No error.
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)
```
Generally, CMake will install the targets to the related directory automatically and we don't need to handle it manually.
So this part might not be needed.

```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    if(VCPKG_TARGET_IS_WINDOWS)
        if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
            file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/rbdl.dll DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin)
        endif()
        if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
            file(COPY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/rbdl.dll DESTINATION ${CURRENT_PACKAGES_DIR}/bin)
        endif()
    endif()
endif()
```
You can make a patch to add 
` RUNTIME DESTINATION ${CMAKE_INSTALL_LIBDIR}` to install targets in dynamic build.

Based on the above situation, I think this port supports all platform. So we can remove `Supports `field now and try to fix the failures and rebuild this.

Note: You can merge the master branch to this PR when you do the changes.

2020-10-10 02:17 UTC, NancyLi1013 requested changes

2020-10-10 02:17 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/debug/share/rbdl)
```suggestion
```
This line seems to be not needed. Can you remove it?

2020-10-10 02:17 UTC, NancyLi1013 commented on ports/rbdl/portfile.cmake
> +# # See /docs/maintainers/vcpkg_fixup_cmake_targets.md for more details
```suggestion
```
These comments can be removed here.

2020-10-10 02:17 UTC, NancyLi1013 commented on ports/rbdl/001_x64_number_of_sections_exceeded_in_object_file_patch.diff
> ++set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
```suggestion
+if(MSVC)
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
+endif()
```
We might need to add this condition here.

2020-10-10 07:48 UTC, RDCH106 commented
Just one more question to be more self-reliant next time. The error due `/bigobj` only supported by MSVC is not showed here: https://dev.azure.com/vcpkg/public/_build/results?buildId=43808&view=logs&j=d3670d0c-cc82-50c9-762c-eccde036829f

![imagen](https://user-images.githubusercontent.com/1483414/95649225-c50d5400-0adc-11eb-88e7-054d208ae671.png)

But how can I inspect `/mnt/vcpkg-ci/buildtrees/rbdl/install-x64-linux-dbg-out.log`? Is it any way to access the log produced by the CI to see that file?

Thanks in advance and sorry for my many questions

2020-10-10 07:49 UTC, RDCH106 commented on ports/rbdl/001_x64_number_of_sections_exceeded_in_object_file_patch.diff
> ++set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
Totally agree

2020-10-10 08:30 UTC, RDCH106 commented
@NancyLi1013 removing Supports field and vcpkg_fail_port_install function produces global failure. It have no sense for me...

2020-10-10 08:54 UTC, RDCH106 commented
I begin to understand... The successfully builds are because they are skipping CMake building 😅, but I don't know how to resolve it because have no idea how to see CMake logs in Azure DevOps.

2020-10-10 09:22 UTC, NancyLi1013 commented
Hi @RDCH106 

The failures are caused by the patch. It seems you didn't update the patch. So It failed to apply.
```
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:54 (message):
  Applying patch failed.  error: corrupt patch at line 16

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:141 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/rbdl/portfile.cmake:7 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)
```
You need to make a new patch.

2020-10-10 09:24 UTC, NancyLi1013 commented
You can check the results here https://dev.azure.com/vcpkg/public/_build/results?buildId=43865&view=logs&j=5dffab7c-3299-5a76-7b02-e037cd868fad&t=1294d155-2ef8-5412-c4b1-d5b95781dd72&l=1574.

Other triplets are the same as this.

2020-10-10 11:38 UTC, RDCH106 commented
I think it's ready 😁

@NancyLi1013, thank you again for your huge job and patient with me.

2020-10-12 01:31 UTC, NancyLi1013 approved these changes

2020-10-12 01:32 UTC, NancyLi1013 commented
Thanks for your efforts to this PR. @RDCH106 
LGTM now.

2020-10-12 22:51 UTC, merged