add docking support for imgui
microsoft/vcpkg pull request #13899
Opened 2020-10-06 10:38 UTC by brukted

One thing worth noting  is that the docking branch is still in beta but as expressed in the readme of the  repo it is pretty much stable.

2020-10-09 07:14 UTC, JackBoosY commented on ports/imgui/portfile.cmake
> +if("docking" IN_LIST FEATURES)
I prefer to set this feature as a new port `imgui-docking` instead of this.

2020-10-09 10:36 UTC, brukted commented on ports/imgui/portfile.cmake
> +if("docking" IN_LIST FEATURES)
I agree it is better to port it separately since It is a beta feature. Users will be able to switch between simply by changing from
imgui to imgui-docking rather than uninstalling and reinstalling. We can remove imgui-docking once it is merged into the master branch.

2020-10-09 18:00 UTC, RT222 commented
`DESTINATION include/${PROJECT_NAME}`

Is moving the headers to the imgui directory really necessary? This would break every port depending of it.

2020-10-09 20:41 UTC, brukted commented
@RT222 It's necessary since both the master and docking branch files have same names and installing imgui-docking  would overwrite the existing files. But It shouldn't break other ports for new imgui installs because the include directories will be changed accordingly. But for those with imgui already installed it would break, To solve that we can make imgui-docking dependent on imgui  so imgui will be reinstalled.

2020-10-10 07:12 UTC, LilyWangL approved these changes

2020-10-22 22:06 UTC, BillyONeal commented
@dan-shaw  Why did you tag this requires:discussion?

2020-10-29 09:06 UTC, LilyWangL commented
Pinging @dan-shaw for response.

2020-11-02 21:07 UTC, BillyONeal commented
@dan-shaw confirmed with me out of band that we are unsure whether we want to catalog what are effectively different versions of the same library under different names. He says that he, @strega-nil, and @ras0219 / @ras0219-msft discussed it a few weeks ago but didn't end up at a consensus. I'll keep you posted.

2020-11-05 22:54 UTC, BillyONeal reviewed
@ocornut @rokups @ShironekoBen This is really about how you would like imgui's "docking" feature branch exposed in vcpkg. Does it make sense to have it available as an incompatible alternative like the `boringssl` vs. `openssl` split, as proposed here? Are you OK with marking whichever merge commit merges master at a given imgui version into the docking branch as "imgui %VERSION%"? Should we use some external configuration (via a user-customized triplet) that indicates desire to use the docking branch?

2020-11-05 22:54 UTC, BillyONeal commented on ports/imgui-docking/CONTROL
> +Version: 1.78
This is grabbing a random commit off the `docking` branch, so if we accept this I think it should get a date version rather than tracking any imgui version, since what we install here is certainly not "imgui 1.78".

2020-11-06 07:12 UTC, rokups commented
I may not have all clear answers, but here are some details.

Docking branch is WIP and does not track releases and should be considered unstable. Given that, i think package installing such version should somehow hint this instability. Archlinux aur packages use `-git` suffix for packages that install latest git version. Short commit hash could also be used. I do not know what would be best in this particular situation. I am not sure if merges to docking are done during releases, so there might not be a precise v1.78 docking version for example.

User code utilizing docking features is not compatible with master branch. Docking/viewport-specific code has to be disabled using `#ifdef IMGUI_HAS_DOCK`/`#ifdef IMGUI_HAS_VIEWPORT`.

> @RT222 It's necessary since both the master and docking branch files have same names and installing imgui-docking would overwrite the existing files. But It shouldn't break other ports because the include directories will be changed accordingly.

I am unsure what this is about, but it does not make sense to have two versions of the library (release + docking) installed at the same time. If anything, `imgui` and `imgui-docking` packages should be conflicting. Does vcpkg have such mechanism?

2020-11-06 19:08 UTC, strega-nil commented
Then what I think is probably that this is a use for versioning (and specifically, beta versions).

2020-11-08 05:43 UTC, BillyONeal commented
@rokups Thanks so much for your feedback.

@brukted Given the wishes / indications of the upstream library maintainers I think we want to wait to accept this until the versioning story @vicroms is working on lands and hook it up to that.

2020-11-08 14:52 UTC, ocornut commented
> I am not sure if merges to docking are done during releases, so there might not be a precise v1.78 docking version for example.

Just to clarify, merges into docking are done very regularly (1-2 months a month at least) and definitively right after every time a release is tagged for master.

Difficult for me to say how it should be catalogued in vcpkg, out of context I would say a YYYYMMDD versioning scheme + short git hash would neatly convey the kinda wip-experimental aspect of this branch, but "1.79+docking" would also work. I understand there's lot of demand for this branch and many users have switched to it a long time ago, and therefore it makes sense to feature it in vcpkg.

2020-12-10 22:35 UTC, BillyONeal commented
@ocornut Can we expect APIs that are in master to work more or less identically in the "docking" branch which are not specifically related to the docking feature?

We are considering recommending using "features" to model this: a "docking" feature which would select the corresponding merge commit from `master` to `docking` for a given release in master.

The north star for "features" is that turning on a feature should not break people who don't care about the presence of the feature. Do you believe that there is a high probability that people who get docking when they didn't explicitly ask for it would be OK, or are they likely to be broken? Examples that would make them likely to be broken would be API removals. For example, we couldn't model boringssl vs openssl with features but we might be able to model this.

Thanks for your help!

2020-12-10 22:46 UTC, BillyONeal commented
To clarify: if the probability of breakage is high, we must do what this PR does and add a skip in `ci.baseline.txt`; otherwise, we need to change this to have a `docking` feature.

2020-12-10 22:47 UTC, ocornut commented
There’s a very low probability for that.the api are expected to function the same (i imagine probably some subtle/contrived examples may differ a little, but its unlikely as we run tests on both and any changes to docking branch which is not strictly related to docking tends to get backported and merged in master in order to keep their difference minimal).

Moreover most of Docking and Multi-viewports are opt-in at runtime level, using Config flags. So using the Docking branch so can you still have Docking disabled which would reduce the likehood of undesirable issue minimal.

There is one important exception: if multi-viewports are enabled, which is an opt-in runtime config flags, the coordinate system changes in a way where the user cannot assume that (0,0) is the top-left origin of their main window. Its a probable source of easy-to-correct-once-you-understand-whats-going-on issues but it’ll only happen when the feature is enabled at runtime and it isn’t by default.

So, yes to your question.

If vcpkg has such a mechanism, I would suggest to label the docking features as “unstable” or “exprimental”. its very functional and widely adopted but I think it is reasonable to keep people on their toes a little bit as to what this branch is.

2020-12-10 22:49 UTC, BillyONeal commented
@brukted Can you change this such that the docking branch commit corresponding to the current master version commit is selected if and only if a feature `docking-experimental` is enabled in the plain `imgui` port?

Thanks!

2020-12-13 21:20 UTC, brukted commented
@billyoneal Ok.

2020-12-14 02:40 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-12-15 08:05 UTC, JackBoosY commented
Should be good, @BillyONeal do you have any other questions?

2020-12-15 22:46 UTC, BillyONeal commented
I verified that 682249396f02b8c21e5ff333ab4a1969c89387ad is the right merge commit and @JackBoosY's request for a bumped port version is satisfied.

Thanks for your contribution and sorry for the deliberations!

2020-12-15 22:46 UTC, merged