ask for amalgamation build on windows
microsoft/vcpkg pull request #13936
Opened 2020-10-08 17:22 UTC by jgilje

**Describe the pull request**

- What does your PR fix?

On Windows, I get the following error building botan:
`Can't start command: C:\WINDOWS\system32\cmd.exe /C link /DLL    build\obj\lib\buildtrees_botan_src_89b3286ac4-fdb28db12d.clean_src_lib_asn1_alg_id.obj (...) build\obj\lib\buildtrees_botan_src_89b3286ac4-fdb28db12d.clean_src_lib_x509_x509self.obj crypt32.lib user32.lib ws2_32.lib /OUT:.\botan.dll`
The entire LIBOBJS variable in the generated Makefile is over 36000 characters long.

I looked into patching botan at first, but I didn't immediately get their custom configure script, and I found this to be the easiest solution. I scoped it under Windows to avoid longer build times on other systems.

I'm of course open for other suggestions for fixing the build error.

- Which triplets are supported/not supported? Have you updated the CI baseline?

NA

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-10-09 06:51 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-10-09 07:11 UTC, jgilje commented
Thanks, Port-Version has been bumped

2020-10-09 07:17 UTC, JackBoosY approved these changes

2020-10-12 19:26 UTC, dan-shaw commented
Can we add this flag as a feature in the `CONTROL` file?

2020-10-12 19:49 UTC, jgilje commented
Sure, amalgamation build is now a feature flag

2020-10-12 22:19 UTC, dan-shaw commented
Thanks!

2020-10-12 22:20 UTC, merged