Fix forward declarations & replace fwd header files
microsoft/vcpkg pull request #13972
Opened 2020-10-10 23:07 UTC by cngzhnp

I had done before in #13623 and these are new fixes for other files as well. I try to use forward declaration files as much as possible. Please give feedback about if new files need to be created.

2020-10-12 17:11 UTC, strega-nil requested changes
Just the one thing, otherwise this is so great 😄

2020-10-12 17:11 UTC, strega-nil commented on toolsrc/include/vcpkg/binarycaching.h
> +#include <vcpkg/fwd/dependencies.h>
👍

2020-10-12 17:11 UTC, strega-nil commented on toolsrc/include/vcpkg/paragraphs.h
> +}
why is this not in `vcpkg/fwd/paragraphparser.h`?

2020-10-12 19:11 UTC, cngzhnp commented on toolsrc/include/vcpkg/paragraphs.h
> +}
Escaped my notice, I will add a forward declaration file for this :)

2020-10-12 19:14 UTC, BillyONeal approved these changes

2020-10-12 19:14 UTC, BillyONeal commented
(Approval obviously conditioned on a successful build :) )

2020-10-12 19:19 UTC, cngzhnp commented
/azp run

2020-10-12 19:22 UTC, BillyONeal commented
@cngzhnp It got your changes with out azp run : https://dev.azure.com/vcpkg/public/_build/results?buildId=43989&view=results

2020-10-12 19:28 UTC, cngzhnp commented
@BillyONeal thanks, maybe not a good place to mention or ask but if the azure-pipelines bot can do format with commands here, it would be easier for us. I always forget to run the format tool before committing the changes :)

2020-10-12 19:34 UTC, BillyONeal commented
Yeah, it's something we've wanted to do; unfortunately we're stuck between a rock and a hard place here. Azure Pipelines can't write any changes back to GitHub (like the formatting changes we want), and GitHub Actions can't control Azure to create and destroy the test machines (we need bigger than the dual core boxes Actions come with).

2020-10-13 10:17 UTC, cngzhnp commented
> Yeah, it's something we've wanted to do; unfortunately we're stuck between a rock and a hard place here. Azure Pipelines can't write any changes back to GitHub (like the formatting changes we want), and GitHub Actions can't control Azure to create and destroy the test machines (we need bigger than the dual core boxes Actions come with).

Thanks for the reply @BillyONeal. Now, it is ready to merge I guess. (condition is checked) :)

2020-10-25 04:59 UTC, merged

2020-10-25 04:59 UTC, BillyONeal commented
Thanks for your contribution!