[libctl/meep] add new port
microsoft/vcpkg pull request #13994
Opened 2020-10-12 09:21 UTC by cenit

follow-up of #4997

2020-10-13 10:41 UTC, cenit commented
@Neumann-A whenever you might have time, can you please help me with the win32 build here?

2020-10-13 11:20 UTC, Neumann-A commented
@cenit: If you want to create import libraries for the make based ports you need to look at what CMake does with GNUtoMS and do the same manually. Furthermore you need to completely switch the compiler to mingw-gcc by setting `ENV{CC/CPP}` etc. (basically all values which are set within `vcpkg_configure_make`). Otherwise wait for #12936 and modify it to not manually have to set all those `ENV` variables. 
I am currently tied down by project proposals so I won't have time to explicitly help you. Main focus is to somehow get #12936 merged/split and then move to other PRs depending on it first.

2020-10-13 12:56 UTC, cenit commented
thank you in any case for the good hints! And good luck for your project proposals!

2020-10-16 08:30 UTC, cenit commented
@JackBoosY since you have also worked on make/autotools projects on windows, may I ask you help here?
I am stuck with a strange problem on windows: the configure step for libctl fails not finding a tool, which is there and on path (/usr/bin/guile).
Do you know what might be the problem here? 
On linux and osx the port seems to work here on my machines. Not in CI because CI does not have guile tool installed (this PR adds it)

2020-10-16 08:38 UTC, JackBoosY commented
> @JackBoosY since you have also worked on make/autotools projects on windows, may I ask you help here?
> I am stuck with a strange problem on windows: the configure step for libctl fails not finding a tool, which is there and on path (/usr/bin/guile).
> Do you know what might be the problem here?
> On linux and osx the port seems to work here on my machines. Not in CI because CI does not have guile tool installed (this PR adds it)

This may be caused by its path not being added to the environment variable `PATH`. For make in windows, @Neumann-A goes further than me.

2020-10-16 08:56 UTC, cenit commented
it's on PATH, that's the strange thing... thanks anyway. I will open up the PR when I will be sure that the Linux/osx versions are OK, for the win32 port it will be left non-working...

2020-10-16 09:00 UTC, Neumann-A commented
@cenit MSYS was change to be separate instances for every vcpkg_acquire_msys call. So you want to make sure you only have one.

2020-10-16 09:13 UTC, Neumann-A commented
@cenit:
conftest.obj : error LNK2019: unresolved external symbol gh_enter referenced in function main
conftest.obj : error LNK2019: unresolved external symbol scm_boot_guile referenced in function main

it is also using cl:
configure:13408: compile cl.exe -nologo -o conftest.exe -g  -IE:/vcpkg_folders/get_comp/installed/x64-windows-static/include -D_WIN32_WINNT=0x0601 -DWIN32_LEAN_AND_MEAN -DWIN32 -D_WINDOWS  -LE:/vcpkg_folders/get_comp/installed/x64-windows-static/debug/lib    conftest.c   >&5

it finds guile:
configure:13042: checking for guile
configure:13058: found /cygdrive/e/vcpkg_cache/downloads/tools/msys2/886986c7a0e6650e/usr/bin/guile
configure:13070: result: guile

it is also doing strange things in guile-config so you probably do not want to use guile-config

2020-10-16 09:14 UTC, Neumann-A commented
also you need to use mingw gcc and not msys gcc. The same probably applys to guile?

2020-10-16 09:15 UTC, cenit commented
guile-config is exactly the script that should launch guile and fails finding it. It might be very difficult to avoid guile-config to properly build libctl...

2020-10-16 09:15 UTC, cenit commented
> also you need to use mingw gcc and not msys gcc. The same probably applys to guile?

2020-10-16 09:17 UTC, cenit commented
yes I just left the win32 part untouched from random tests I did trying to make it work

2020-10-16 10:05 UTC, cenit commented
Unfortunately also guile is not available as a mingw package
https://github.com/msys2/MINGW-packages/issues/3298

2020-10-16 10:08 UTC, Neumann-A commented
according to the guile-config script: 
`;;; This script has been deprecated. Just use pkg-config.`

so patching the script out is the way to go.

> Unfortunately also guile is not available as a mingw package

since I don't know what guile does I cannot tell you if it is necessary to switch to mingw or if msys would be ok.

2020-10-16 10:17 UTC, Neumann-A commented
you probably need to have a mingw guile package first or a vcpkg guile port. Otherwise linking against it is not possible. You can pass `ac_cv_prog_GUILE_CONFIG=unknown` as a configure option to disable guile-config and get configure to the fortran check but the guile check will fail and set `with_guile=no`.

2020-10-17 21:10 UTC, cenit commented
Which might even be acceptable to have a very basic libctl/meep... thinking about it to have a win32 port of it :)
Thank you very much for your investigation.
I am also too busy in this period, so I really appreciate your time here!

2020-10-29 09:11 UTC, NancyLi1013 commented
@cenit 
Could you please resolve the conflicts?

2021-01-14 02:32 UTC, JackBoosY commented
3 regressions left.

2021-04-23 03:17 UTC, NancyLi1013 commented
Needs to merge master to rebuild.

2021-05-25 08:11 UTC, JackBoosY commented
Pinging @cenit  for response. Is work still being done for this PR?

2021-05-25 08:23 UTC, cenit commented
> Pinging @cenit for response. Is work still being done for this PR?

yes, albeit extremely slowly.
I merged master in the meantime to see current PR status

2021-06-11 14:29 UTC, cenit commented
@JackBoosY ok libctl/meep work on linux/osx
For Windows the road will be long, so there is no reason to block the PR anymore waiting for that

2021-06-15 02:24 UTC, JackBoosY commented
When building `libctl:x64-linux:
err:
```
make[2]: *** No rule to make target 'geom-ctl-io.c', needed by 'all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
out:
```
/usr/bin/make  all-recursive
make[1]: Entering directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg'
Making all in src
make[2]: Entering directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg/src'
/usr/bin/make  all-am
make[3]: Entering directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg/src'
make[2]: Leaving directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg/src'
Making all in utils
make[2]: Entering directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg/utils'
make[2]: Leaving directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg/utils'
Makefile:474: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/mnt/vcpkg-ci/buildtrees/libctl/x64-linux-dbg'
Makefile:382: recipe for target 'all' failed
```

2021-06-15 06:24 UTC, cenit commented
I think that the image has to be provisioned with some system dependencies. They are present in PR but not applied until merged I think. 
Can you please try to install them manually on your system and try again?

2021-06-15 08:01 UTC, JackBoosY commented
Sorry, I tested it on my machine successfully.

2021-06-15 08:06 UTC, JackBoosY commented on ports/libctl/CONTROL
> +Description: libctl is a Guile-based library for supporting flexible control files in scientific simulations.
Please add `homepage`.

2021-06-15 08:06 UTC, JackBoosY commented on ports/libctl/portfile.cmake
> +if(CMAKE_HOST_WIN32)
```suggestion
if(VCPKG_HOST_IS_WINDOWS)
```

2021-06-15 08:06 UTC, JackBoosY commented on ports/libctl/portfile.cmake
> +    #set(ENV{CXX} "g++")
```suggestion
```

2021-06-15 08:06 UTC, JackBoosY commented on ports/libctl/portfile.cmake
> +    #set(ENV{CXXFLAGS} "-mabi=ms ${MACHINE_FLAG} ${VCPKG_CXX_FLAGS}")
```suggestion
```

2021-06-15 08:06 UTC, JackBoosY commented on ports/libctl/portfile.cmake
> +    include("${SCRIPTS}/toolchains/mingw.cmake")
So can we only use mingW to build it on Windows?
If yes, I think we should remove `Supports: !windows` on CONTROL.

2021-06-15 08:06 UTC, JackBoosY commented on ports/meep/portfile.cmake
> +    #set(ENV{CXX} "g++")
```suggestion
```

2021-06-15 08:06 UTC, JackBoosY commented on ports/meep/portfile.cmake
> +    #set(ENV{CXXFLAGS} "-mabi=ms ${MACHINE_FLAG} ${VCPKG_CXX_FLAGS}")
```suggestion
```

2021-06-18 01:30 UTC, NancyLi1013 requested changes

2021-06-18 01:30 UTC, NancyLi1013 commented on ports/libctl/CONTROL
> +Supports: linux
Can we change `CONTROL `file as manifest?

2021-07-10 01:39 UTC, ras0219-msft commented
I think that it is inappropriate to attempt to switch the user's toolchain out with MinGW; a key principle of vcpkg is that (at least for C & C++) we use your tools and toolchain.

Instead, I think this library needs to be marked as not supporting windows unless targeting MinGW. If a user really wants a Frankenstein triplet of MSVC for half of their libraries and MinGW for the other half, they can use custom triplets to ask for it.

2021-07-10 07:43 UTC, cenit commented
you are perfectly right. in fact the manifest support field lists only linux.

the mingw experiment is interesting but not so effective too, so maybe the best thing would be to remove everything about it

2021-07-22 03:06 UTC, JackBoosY commented
Ping @cenit for response. Is work still being done for this PR?
If you don't have much time, you can switch this PR to draft.

2021-08-11 23:06 UTC, BillyONeal commented
Dropping depends:vm-update because I see no VM changes in this PR.

2021-08-15 21:51 UTC, cenit commented on scripts/azure-pipelines/linux/provision-image.sh
> +APT_PACKAGES="$APT_PACKAGES guile-2.2-dev"
@BillyONeal this line ;)

2021-08-15 21:51 UTC, cenit commented
@BillyONeal see the line highlighted in the comment above

2021-08-16 02:54 UTC, JackBoosY commented on scripts/azure-pipelines/linux/provision-image.sh
> +APT_PACKAGES="$APT_PACKAGES guile-2.2-dev"
Ping @BillyONeal

2021-08-16 19:44 UTC, BillyONeal commented on scripts/azure-pipelines/linux/provision-image.sh
> +APT_PACKAGES="$APT_PACKAGES guile-2.2-dev"
It didn't make this train, we were under the gun to get patch tuesday last week applied and I was a dum dum and missed this when minting VMs.

That said shouldn't vcpkg providing this library rather than grabbing it off the system?

2021-08-17 03:18 UTC, cenit commented on scripts/azure-pipelines/linux/provision-image.sh
> +APT_PACKAGES="$APT_PACKAGES guile-2.2-dev"
yes. Also, i am not sure that i’d really ask for a vm update from an old draft pr from a very difficult port… i was just highlighting you why the label vm update was there

2021-09-29 09:54 UTC, JackBoosY commented on scripts/azure-pipelines/linux/provision-image.sh
> +APT_PACKAGES="$APT_PACKAGES guile-2.2-dev"
@BillyONeal Should we consider add this in the next update?

2021-11-10 22:09 UTC, BillyONeal commented
/azp run

2021-11-11 09:29 UTC, cenit commented on ports/libctl/CONTROL
> +Supports: linux
done :)

2021-11-15 17:14 UTC, ras0219-msft commented
It looks like guile may be optional (https://github.com/NanoComp/libctl/blob/76deb2af3db3b07b91b89254b739dd8793fb921e/configure.ac#L57-L59); could we sidestep this entirely by just passing `--without-guile`?

2021-12-30 18:34 UTC, JackBoosY commented
Ping for response.

2022-03-18 06:09 UTC, JackBoosY commented
Any progress?

2022-05-07 05:55 UTC, JackBoosY commented
Convert this PR to draft since there is no progress.

2022-06-24 07:54 UTC, JackBoosY commented
Please temporary close this PR if you don't have spare time to finish it.

2022-06-24 08:25 UTC, closed without merging