[jansson] Update to 2.13.1
microsoft/vcpkg pull request #14007
Opened 2020-10-13 03:25 UTC by Jimmy-Hu

**Describe the pull request**

- What does your PR fix? Update jansson package to 2.13.1

  https://github.com/akheron/jansson/releases/tag/v2.13.1

2020-10-14 07:24 UTC, NancyLi1013 requested changes

2020-10-14 07:24 UTC, NancyLi1013 commented on ports/jansson/portfile.cmake
Could you please also update 

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/jansson RENAME copyright)`

as

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2020-10-14 07:25 UTC, NancyLi1013 commented
Hi @Jimmy-Hu 
Thanks for this PR.
Could you please resolve the conflicts and also address the review suggestions?

2020-10-14 07:31 UTC, Jimmy-Hu commented
> 
> 
> Hi @Jimmy-Hu
> Thanks for this PR.
> Could you please resolve the conflicts and also address the review suggestions?

@NancyLi1013 Thank you for your reply. Let me check and update that.

2020-10-15 01:50 UTC, NancyLi1013 approved these changes

2020-10-15 01:51 UTC, NancyLi1013 commented
LGTM now. Thanks for your efforts.

2020-10-15 22:37 UTC, merged