[ezc3d] Add new port
microsoft/vcpkg pull request #14016
Opened 2020-10-13 16:24 UTC by RDCH106

**ezc3d - C3D reader/writer**

- What does your PR fix?
  * This PR adds a new port for ezc3d. It builds the library downloading it from [official repository](https://github.com/rbdl/rbdl) and making compilation through CMake according to [Packaging Zipfiles guide](https://vcpkg.readthedocs.io/en/latest/examples/packaging-zipfiles).

  * The port only builds the core library and not the optional addons (future work for features).

  * Port was tested in [vcpkg 2020.07](https://github.com/microsoft/vcpkg/releases/tag/2020.07) with [ezc3d 1.3.7](https://github.com/pyomeca/ezc3d/releases/tag/Release_1.3.7)

- Which triplets are supported/not supported?
  * Expected supported triplets: Triplets tested by CI baseline

- Have you updated the CI baseline?
  * Not updated the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  * All the implementation has been done taking into account the [Maintainer Guidelines and Policies](https://vcpkg.readthedocs.io/en/latest/maintainers/maintainer-guide).

2020-10-14 08:45 UTC, NancyLi1013 requested changes

2020-10-14 08:45 UTC, NancyLi1013 commented on ports/ezc3d/CONTROL
> +Build-Depends:
```suggestion
```
If there is no port to depend on, we should remove this field.

2020-10-14 08:45 UTC, NancyLi1013 commented on ports/ezc3d/portfile.cmake
> +
```suggestion
```

2020-10-14 08:45 UTC, NancyLi1013 commented on ports/ezc3d/portfile.cmake
> +    PATCHES
```suggestion
```
Since there is no any additional patch, please remove it.

2020-10-14 08:45 UTC, NancyLi1013 commented on ports/ezc3d/portfile.cmake
> +endif()
```suggestion
```
Since by default, vcpkg_configure_cmake() will pass in the appropriate setting for `BUILD_SHARED_LIBS`. There is no need to do this operation.
Please see this doc
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#choose-either-static-or-shared-binaries

2020-10-14 08:45 UTC, NancyLi1013 commented on ports/ezc3d/portfile.cmake
> +        -DBUILD_SHARED_LIBS=${EZC3D_SHARED}
```suggestion
```

2020-10-14 09:03 UTC, RDCH106 commented on ports/ezc3d/portfile.cmake
> +endif()
Agree
Thank you for the given reference 👍

2020-10-14 09:04 UTC, RDCH106 commented on ports/ezc3d/portfile.cmake
> +        -DBUILD_SHARED_LIBS=${EZC3D_SHARED}
Agree

2020-10-14 11:17 UTC, RDCH106 commented
Neverending story version x64-osx 😅
@NancyLi1013 , maybe starting again the job...

2020-10-15 01:14 UTC, Hoikas commented on ports/ezc3d/CONTROL
> +Description: C3D reader/writer
Per the [maintainer's guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#manifests-and-control-files):
> When adding a new port, use the new manifest syntax for defining a port

2020-10-15 02:12 UTC, NancyLi1013 commented on ports/ezc3d/CONTROL
> +Description: C3D reader/writer
@Hoikas 
Thanks for your review and also pointing this reference doc to us. It's really so nice.
But currently, we have no requirement to use vcpkg.json instead of CONTROL file. We might replace it in the near furture.

Thanks again for your help.

2020-10-15 02:13 UTC, NancyLi1013 requested changes

2020-10-15 02:13 UTC, NancyLi1013 commented on ports/ezc3d/portfile.cmake
> +
```suggestion
```

2020-10-15 02:14 UTC, NancyLi1013 commented
> Neverending story version x64-osx 😅
> @NancyLi1013 , maybe starting again the job...

@RDCH106 
All work seems good now. So what do you mean about this comment?

2020-10-15 07:46 UTC, RDCH106 commented on ports/ezc3d/CONTROL
> +Description: C3D reader/writer
I am aware of this, but I use the CONTROL file because vcpkg.json gives me problems. In the future, I will replace them.

2020-10-15 08:05 UTC, RDCH106 commented
> 
> 
> > Neverending story version x64-osx 😅
> > @NancyLi1013 , maybe starting again the job...
> 
> @RDCH106
> All work seems good now. So what do you mean about this comment?

It was just a joke due to the x64_osx job duration. In the end, the job finalized.

![imagen](https://user-images.githubusercontent.com/1483414/96094258-72151180-0ecd-11eb-9458-869c3acba16f.png)

2020-10-15 08:09 UTC, RDCH106 commented on ports/ezc3d/CONTROL
> +Description: C3D reader/writer
@Hoikas @NancyLi1013 updated CONTROL file to vcpkg.json manifest

2020-10-15 08:25 UTC, RDCH106 commented on ports/ezc3d/CONTROL
> +Description: C3D reader/writer
@Hoikas `vcpkg format-manifest` not found command  in [vcpkg 2020.07](https://github.com/microsoft/vcpkg/releases/tag/2020.07)

@NancyLi1013 what is the expected format for the manifest: https://dev.azure.com/vcpkg/public/_build/results?buildId=44147&view=logs&j=ce047939-a825-53e5-6448-6f7a4cb38089&t=a8b60181-d0d7-59bf-902d-f19e55a12f6e&l=116

The manifest works in my computer.

2020-10-15 09:33 UTC, NancyLi1013 commented
The format for `vcpkg.json` is not right. The end of line should be `LF `instead of `CRLF`.

2020-10-15 10:13 UTC, RDCH106 commented
@NancyLi1013 done, but same error...

Currently, the command `vcpkg create` on Windows is generating vcpkg.json with `CRLF` line ending instead of `LF`.

2020-10-15 10:18 UTC, RDCH106 commented
@NancyLi1013 , we can consider to revert conversion from CONTROL file to vcpkg.json manifest... Before it, the CI was passed successfully.

2020-10-16 11:16 UTC, RDCH106 commented
Reverted conversion from CONTROL file to vcpkg.json manifest

I think it's ready 😁

2020-10-19 02:26 UTC, NancyLi1013 approved these changes

2020-10-20 02:23 UTC, BillyONeal approved these changes

2020-10-20 19:22 UTC, merged

2020-10-20 19:22 UTC, BillyONeal commented
Thanks for your contribution!