[PDAL] Update to v2.2.0
microsoft/vcpkg pull request #14055
Opened 2020-10-14 23:57 UTC by GeorgeR

Update PDAL to v2.2.0 (from v1.7.2)

2020-10-15 03:17 UTC, LilyWangL commented
@GeorgeR Thanks for your PR. Could you resolve conflicts?

2020-10-16 08:21 UTC, LilyWangL requested changes

2020-10-16 08:21 UTC, LilyWangL commented on ports/pdal/portfile.cmake
>  vcpkg_download_distfile(ARCHIVE
Could you use `vcpkg_from_github` instead of `vcpkg_download_distfile` and `vcpkg_extract_source_archive_ex`?

2020-10-22 02:59 UTC, LilyWangL commented
Pinging @GeorgeR for response.

2020-10-27 02:05 UTC, LilyWangL commented
@GeorgeR Now `pdal` build failed on `x64-windows-static` with the following error:
```
-- Configuring done
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_arbiter" that is not in any export set.
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_kazhdan" that is not in any export set.
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_INSTALL_BINDIR
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
Could you continue to fix this?

2020-11-03 06:46 UTC, LilyWangL commented
Pinging @GeorgeR for response.

2020-11-03 06:56 UTC, GeorgeR commented
@LilyWangL no problem, will continue to work on this shortly (had to work over weekend so didn't get much time)

2020-11-08 07:06 UTC, GeorgeR commented
> 
> 
> @GeorgeR Now `pdal` build failed on `x64-windows-static` with the following error:
> 
> ```
> -- Configuring done
> CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_arbiter" that is not in any export set.
> CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_kazhdan" that is not in any export set.
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
>     CMAKE_INSTALL_BINDIR
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> ```
> 
> Could you continue to fix this?

I'm really at a loss as to how to fix this. 

I almost got PDAL to build on it's own as static (but got some CURL errors) and noticed that the output PDALTargets.cmake file didn't reference the two offending libraries (arbiter or kazhdan) in INTERFACE_LINK_LIBRARIES for pdalcpp, but when built from vcpkg it did. 

I reverted some of the changes in the vcpkg patch, for example the export of arbiter and kazdhan, but this didn't change the fact that both are expected in INTERFACE_LINK_LIBRARIES in the form of: 
```
$<LINK_ONLY:pdal_kazhdan>
```

I also enabled the PDAL_USE_STATIC_RUNTIME flag in the port file:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
  set(VCPKG_BUILD_SHARED_LIBS ON)
  set(VCPKG_BUILD_STATIC_LIBS OFF)
else()
  set(VCPKG_BUILD_SHARED_LIBS OFF)
  set(VCPKG_BUILD_STATIC_LIBS ON)
  set(PDAL_USE_STATIC_RUNTIME TRUE)
endif()
```

So i'm still getting the same errors as you've posted, but i'm unsure why vcpkg is creating a different PDALTargets.cmake than the what i've got via regular cmake.

2020-11-18 22:22 UTC, strega-nil commented
@NancyLi1013 are you looking into this? could you make sure that this gets worked through?

2020-11-19 02:06 UTC, NancyLi1013 commented
Yes, I arm looking into this. Thanks for your kindly reminder @strega-nil .

@GeorgeR 

Sorry for the delay. Could you please resolve the conflicts?

2020-12-02 14:14 UTC, ThGravo commented
I tried your changes, but get the following error:
Building package pdal[core]:x64-linux...
Could not locate cached archive: /home/fgawrilo/.cache/vcpkg/archives/da/da6419805d08e65d688e0e4cba52c509042f6d69.zip
-- Using cached /media/data/Code/repos/3rd/vcpkg/downloads/PDAL-PDAL-2.2.0.tar.gz
-- Cleaning sources at /media/data/Code/repos/3rd/vcpkg/buildtrees/pdal/src/2.2.0-1c3e5bb51e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /media/data/Code/repos/3rd/vcpkg/downloads/PDAL-PDAL-2.2.0.tar.gz
-- Applying patch reimplement-patch-172-in-220.patch
-- Using source at /media/data/Code/repos/3rd/vcpkg/buildtrees/pdal/src/2.2.0-1c3e5bb51e.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /media/data/Code/repos/3rd/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake /media/data/Code/repos/3rd/vcpkg/buildtrees/pdal/src/2.2.0-1c3e5bb51e.clean -DPDAL_BUILD_STATIC:BOOL=ON -DWITH_TESTS:BOOL=OFF -DWITH_COMPLETION:BOOL=OFF -DCMAKE_MAKE_PROGRAM=/home/fgawrilo/repos/3rd/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/fgawrilo/repos/3rd/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/fgawrilo/repos/3rd/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/media/data/Code/repos/3rd/vcpkg -D_VCPKG_INSTALLED_DIR=/media/data/Code/repos/3rd/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/media/data/Code/repos/3rd/vcpkg/packages/pdal_x64-linux/debug
    Working Directory: /media/data/Code/repos/3rd/vcpkg/buildtrees/pdal/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /media/data/Code/repos/3rd/vcpkg/buildtrees/pdal/config-x64-linux-dbg-out.log
      /media/data/Code/repos/3rd/vcpkg/buildtrees/pdal/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:328 (vcpkg_execute_required_process)
  ports/pdal/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package pdal:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pdal:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.


[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5629779/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5629780/config-x64-linux-dbg-out.log)

2020-12-04 09:12 UTC, NancyLi1013 commented
@GeorgeR 

The current changes in this PR cannot work fine. Please update vcpkg to the latest version to rebuild this port on vcpkg master branch.

2020-12-25 07:41 UTC, NancyLi1013 commented
PDAL failed on the x64-windows-static with the following errors:

```
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_arbiter" that is not in any export set.
CMake Error: install(EXPORT "PDALTargets" ...) includes target "pdalcpp" which requires target "pdal_kazhdan" that is not in any export set.
```

2020-12-25 07:51 UTC, NancyLi1013 requested changes

2020-12-25 07:51 UTC, NancyLi1013 commented on ports/pdal/portfile.cmake
> +set(PDAL_VERSION_STR "2.2.0")
```suggestion
```
This is not used any more.

2020-12-25 07:51 UTC, NancyLi1013 commented on ports/pdal/portfile.cmake
>  # Install PDAL executable
Could you please use `vcpkg_copy_tools()` to handle these executables?

2020-12-25 07:51 UTC, NancyLi1013 commented on ports/pdal/portfile.cmake
> +
```suggestion
```

2020-12-25 07:51 UTC, NancyLi1013 commented on ports/pdal/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")
```suggestion
```
This is invalided.

2020-12-25 07:51 UTC, NancyLi1013 commented on ports/pdal/portfile.cmake
> +        reimplement-patch-172-in-220.patch
There are a lot of changes in this patch. Could you please submit these changes to upstream?

2021-01-07 22:09 UTC, Neumann-A commented on ports/pdal/reimplement-patch-172-in-220.patch
> ++    return boost::filesystem::exists(toNative(dirname));
wouldn't it be easier to alias `pdalboost::filesystem` as `boost::filesystem` via `using` instead of patching it everywhere?

2021-01-07 22:11 UTC, Neumann-A commented on ports/pdal/reimplement-patch-172-in-220.patch
> ++    return boost::filesystem::exists(toNative(dirname));
something like `namespace pdalboost { using filesystem =::boost::filesystem;}` (is filesystem a namespace or a type?)

2021-01-07 22:24 UTC, GeorgeR commented
I started on this fresh yesterday, using a commit which fixes VS2019 build errors:
https://github.com/PDAL/PDAL/commit/0f319a51cb3cb67b10328176ebbefcbe6ca4fc9b

I will get it building outside of vcpkg (but using the vcpkg toolchain) first, then patch in the relevant changes. The issue I'm facing at the moment are differences between how vcpkg is configuring the project vs what I'm doing via cmake-ui.

2021-01-07 22:26 UTC, GeorgeR commented on ports/pdal/reimplement-patch-172-in-220.patch
> ++    return boost::filesystem::exists(toNative(dirname));
I'll give this a go when the build errors are sorted. For now I'm using a patch that only changes what's absolutely necessary to get it building.

2021-02-08 07:04 UTC, NancyLi1013 commented
Hi @GeorgeR 

What's progress on this PR?

2021-04-02 06:51 UTC, NancyLi1013 commented
Converting to draft for now until this PR can work fine. Please ping me if it is ready for review.

2021-08-30 03:12 UTC, PhoebeHui commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2021-08-30 03:12 UTC, closed without merging