Fix #14049
microsoft/vcpkg pull request #14051
Opened 2020-10-14 21:41 UTC by klalumiere

- What does your PR fix? Fixes #14049

- Which triplets are supported/not supported? Adds support for the non-official `x64-linux-dynamic` which is described in the official doc.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2020-10-15 06:41 UTC, PhoebeHui requested changes

2020-10-15 06:41 UTC, PhoebeHui commented on ports/curl/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR ${VCPKG_CMAKE_SYSTEM_NAME} STREQUAL "Linux")
```suggestion
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR VCPKG_TARGET_IS_LINUX)
```

2020-10-16 02:10 UTC, PhoebeHui approved these changes

2020-10-16 02:12 UTC, PhoebeHui requested changes
Could you also update the Port-Verison in CONTROL file?

From
Version: 7.73.0

To 
Version: 7.73.0
Port-Version: 1

2020-10-16 03:06 UTC, klalumiere commented
@PhoebeHui Sorry for the `requested review`, I did not notice you already approved 😳.

2020-10-16 05:36 UTC, PhoebeHui approved these changes

2020-10-16 05:38 UTC, PhoebeHui commented
@klalumiere, never mind, appreciate your effort very much.

2020-10-20 18:29 UTC, merged

2020-10-20 18:30 UTC, BillyONeal commented
Thanks for your contribution!