[oatpp-sqlite] port added
microsoft/vcpkg pull request #14107
Opened 2020-10-19 03:48 UTC by KaungZawHtet

Other oatpp modules hav already been included and this sqlite one left and now here it is

2020-10-19 12:13 UTC, KaungZawHtet commented
After seeing the build failure on UWP , I reported to the main author and he replied. Here is the link:
https://github.com/oatpp/oatpp-sqlite/issues/3#issuecomment-712106236
As you see, build fail at him too. Please investigate the problem at vcpkg.

2020-10-20 07:20 UTC, NancyLi1013 commented
The failures on x64-uwp and arm-uwp:

```
5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42196,56): error C2065: 'AreFileApisANSI': undeclared identifier [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42196,56): warning C4312: 'type cast': conversion from 'int' to 'sqlite3_syscall_ptr' of greater size [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42226,52): error C2065: 'CreateFileA': undeclared identifier [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42226,52): warning C4312: 'type cast': conversion from 'int' to 'sqlite3_syscall_ptr' of greater size [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42235,52): error C2065: 'CreateFileW': undeclared identifier [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42235,52): warning C4312: 'type cast': conversion from 'int' to 'sqlite3_syscall_ptr' of greater size [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42385,52): error C2065: 'GetFileSize': undeclared identifier [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42385,52): warning C4312: 'type cast': conversion from 'int' to 'sqlite3_syscall_ptr' of greater size [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42531,53): error C2065: 'HeapValidate': undeclared identifier [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42531,53): warning C4312: 'type cast': conversion from 'int' to 'sqlite3_syscall_ptr' of greater size [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42548,53): error C2065: 'LoadLibraryA': undeclared identifier [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42548,53): warning C4312: 'type cast': conversion from 'int' to 'sqlite3_syscall_ptr' of greater size [D:\buildtrees\oatpp-sqlite\x64-uwp-dbg\src\sqlite.vcxproj]
     5>D:\buildtrees\oatpp-sqlite\src\d2e5962be1-146fcc8dbb.clean\src\sqlite\sqlite3.c(42557,53): error C2065: 'LoadLibraryW': undeclared identifier 
```
The error occurred when building `sqlite3.c` file.

Since [sqlite3 ](https://github.com/microsoft/vcpkg/tree/master/ports/sqlite3)has been provided in vcpkg now. 
We should depend on `sqlite3 `in vcpkg to build `oatpp-sqlite` instead of building the source codes embedded in `oatpp-sqlite` here https://github.com/oatpp/oatpp-sqlite/tree/master/src/sqlite.

So could you please update this to rebuild this again?

2020-10-20 07:26 UTC, NancyLi1013 requested changes

2020-10-20 07:26 UTC, NancyLi1013 commented on ports/oatpp-sqlite/portfile.cmake
> +endif()
```suggestion
```
These lines are not needed. Since by default, `vcpkg_configure_cmake()` will pass in the appropriate setting for `BUILD_SHARED_LIBS`.

Please see this doc
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#choose-either-static-or-shared-binaries

2020-10-20 07:26 UTC, NancyLi1013 commented on ports/oatpp-sqlite/portfile.cmake
> +        "-DBUILD_SHARED_LIBS:BOOL=${OATPP_BUILD_SHARED_LIBRARIES_OPTION}"
```suggestion
```
The same reason as above.

2020-10-21 01:41 UTC, KaungZawHtet commented on ports/oatpp-sqlite/portfile.cmake
> +endif()
How about oatpp-consul ? It passed with the same script by someone else. If including the code or not is the same result, keeping the code, for uniformity , look better I think.

2020-10-21 07:21 UTC, NancyLi1013 commented on ports/oatpp-sqlite/portfile.cmake
> +endif()
In fact, other ports also don't need to add these codes.  You can remove them in this PR too.

2020-10-21 09:40 UTC, KaungZawHtet commented on ports/oatpp-sqlite/portfile.cmake
> +endif()
Ok, I am going to take a look after uwp build fail, the main issue, has been solved by the lib author.

2020-10-25 13:14 UTC, KaungZawHtet commented
fixed but failed. For the failure, is there any informative log that need to shared here ?

2020-10-26 02:35 UTC, NancyLi1013 commented
```
CMake Error at D:/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  D:/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/share/cmake-3.18/Modules/FindSQLite3.cmake:52 (find_package_handle_standard_args)
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:536 (_find_package)
  CMakeLists.txt:108 (find_package)
```
Please check the log here 
https://dev.azure.com/vcpkg/public/_build/results?buildId=44522&view=artifacts&type=publishedArtifacts

2020-10-27 20:03 UTC, KaungZawHtet commented
Fixed and builds are in success now

2020-10-27 20:04 UTC, KaungZawHtet commented on ports/oatpp-sqlite/portfile.cmake
> +endif()
Done!

2020-10-28 01:55 UTC, NancyLi1013 reviewed
Could you please also bump CONTROL file?

Add `Port-Version` for all ports except for new port `oatpp-sqlite.`

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-consul/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-consul/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-libressl/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-libressl/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-mbedtls/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-mbedtls/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-swagger/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-swagger/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-websocket/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp-websocket/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp/portfile.cmake
> +
```suggestion
```

2020-10-28 01:55 UTC, NancyLi1013 commented on ports/oatpp/portfile.cmake
> +    REF 8f1c11ae534e1f03646de8efcc9b2505fb1881cc  # 1.2.0
I noticed that the version is also 1.2.0 in vcpkg master branch. Why is the commit id different? Is this a unstable release?

2020-10-28 08:42 UTC, KaungZawHtet commented on ports/oatpp/portfile.cmake
> +    REF 8f1c11ae534e1f03646de8efcc9b2505fb1881cc  # 1.2.0
1.2.0 tag is released with that 8f1c11ae commit, not with 2d87110.

2020-10-28 08:45 UTC, KaungZawHtet commented
1.2.0 is only version number main author gives us. No bump version we get to display

2020-10-28 08:50 UTC, KaungZawHtet commented on ports/oatpp/portfile.cmake
> +    REF 8f1c11ae534e1f03646de8efcc9b2505fb1881cc  # 1.2.0
https://github.com/oatpp/oatpp/releases/tag/1.2.0

2020-10-28 09:06 UTC, NancyLi1013 commented on ports/oatpp/portfile.cmake
> +    REF 8f1c11ae534e1f03646de8efcc9b2505fb1881cc  # 1.2.0
It seems that 1.2.0 was tagged twice.

First commit is 2d8711307e23e9f022cbe2758c07ce4e44e8d31f
Please see https://github.com/oatpp/oatpp/commit/2d8711307e23e9f022cbe2758c07ce4e44e8d31f

Second commit is 8f1c11ae534e1f03646de8efcc9b2505fb1881cc
Please see https://github.com/oatpp/oatpp/commit/8f1c11ae534e1f03646de8efcc9b2505fb1881cc

2020-10-28 09:10 UTC, NancyLi1013 commented
> 1.2.0 is only version number main author gives us. No bump version we get to display

You're right, the version number is from upstream. But we also need to bump CONTROL file. In this case, we can add `Port-Version: 1`. Since there are changes in these ports.

Please see this doc https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#port-version

2020-10-28 09:28 UTC, KaungZawHtet commented
`Port-Version: 2` to oatpp and other oatpp modules except oatpp-sqlite , right ?

2020-10-29 07:41 UTC, NancyLi1013 requested changes

2020-10-29 07:41 UTC, NancyLi1013 commented on ports/oatpp/CONTROL
>  Version: 1.2.0
```suggestion
Version: 1.2.0
Port-Version: 1
```

2020-10-29 07:44 UTC, NancyLi1013 commented
> `Port-Version: 2` to oatpp and other oatpp modules except oatpp-sqlite , right ?

All `Port-Version:` should be 1, except `oatpp-sqlite`.

2020-10-29 07:59 UTC, NancyLi1013 commented on ports/oatpp-sqlite/portfile.cmake
> +
```suggestion
```

2020-10-29 08:00 UTC, NancyLi1013 commented on ports/oatpp-sqlite/portfile.cmake
> +
```suggestion
```

2020-10-29 08:02 UTC, NancyLi1013 approved these changes

2020-10-30 20:44 UTC, merged

2020-10-30 20:44 UTC, BillyONeal commented
Thanks again!