[drogon] Fix build errors on linux/osx
microsoft/vcpkg pull request #14148
Opened 2020-10-21 10:58 UTC by an-tao

To resolve #13848

2020-10-21 16:10 UTC, BillyONeal commented on ports/drogon/pg.patch
> ++  find_package(PostgreSQL)
```suggestion
+  find_package(PostgreSQL REQUIRED)
```

2020-10-22 02:01 UTC, NancyLi1013 requested changes

2020-10-22 03:52 UTC, an-tao commented on ports/drogon/CONTROL
> +Build-Depends: trantor, zlib, jsoncpp, libmariadb[iconv], libpq, sqlite3, brotli, libuuid (!windows)
I agree with you, thanks.

2020-10-22 05:38 UTC, NancyLi1013 approved these changes

2020-10-23 06:18 UTC, NancyLi1013 commented
@BillyONeal 
This PR is ready for merged now. But the CI seems to be stuck by something. It has been running more than one day. Please help take a look.

Thanks.

2020-10-23 19:05 UTC, merged