[asio] update to version 1.18.0 (#14095)
microsoft/vcpkg pull request #14167
Opened 2020-10-22 17:32 UTC by mathisloge

This PR is related to #14095

- What does your PR fix? 
Upates asio to version 1.18.0

- Which triplets are supported/not supported? Have you updated the CI baseline? 

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

2020-10-22 18:39 UTC, mathisloge commented
Hi @NancyLi1013 

So I have tried to update restbed to the newest version prior to appliying the patch you mentioned at #14095 .

Unfortunately I getting now the ninja error 

   `ninja: error: build.ninja:469: multiple rules generate restbed.lib [-w dupbuild=err]`

2020-10-22 19:01 UTC, mathisloge commented
Okay, the removal of `PREFER_NINJA` fixed the `ninja: error: build.ninja:469: multiple rules generate restbed.lib [-w dupbuild=err]`

2020-10-23 06:40 UTC, NancyLi1013 requested changes

2020-10-23 06:40 UTC, NancyLi1013 commented on ports/asio/portfile.cmake
> +    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/
```suggestion
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}
```

2020-10-23 06:40 UTC, NancyLi1013 commented on ports/asio/portfile.cmake
> -#header-only library
This comment should not be removed.

2020-10-23 06:40 UTC, NancyLi1013 commented on ports/opendnp3/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake TARGET_PATH share/${PORT})
```suggestion
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake TARGET_PATH share/asio)
```
It would be better to use the name here.

2020-10-23 06:40 UTC, NancyLi1013 commented on ports/restbed/portfile.cmake
>  vcpkg_install_cmake()
Could you please update this

`configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/restbed/copyright COPYONLY)
`

as

`configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)`?

2020-10-23 06:40 UTC, NancyLi1013 commented on ports/restbed/use-FindOpenSSL-cmake.patch
> +--- a/cmake/Findopenssl.cmake
If this file is not needed, we can remove it in portfile.cmake instead of patch.

2020-10-23 06:40 UTC, NancyLi1013 commented on ports/restbed/portfile.cmake
> -    PREFER_NINJA
We should try to fix the problem instead of just removing this.

2020-10-23 11:42 UTC, mathisloge commented on ports/opendnp3/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake TARGET_PATH share/${PORT})
should have been opendnp3 instead of asio

2020-10-23 11:46 UTC, mathisloge commented
when adding  64cfeef28b1b0cd2b10499592ce3c81d22c741c3 it results in the config error. 

@NancyLi1013 do you have any tips on how to solve this? I don't have any experience with that one.

2020-10-26 08:37 UTC, NancyLi1013 commented
```
CMake Error:
  Running

   'D:/downloads/tools/ninja/1.10.1-windows/ninja.exe' '-C' 'D:/buildtrees/restbed/x86-windows-dbg' '-t' 'cleandead'

  failed with:

   ninja: error: build.ninja:469: multiple rules generate restbed.lib [-w dupbuild=err]
```
Since there are more that one targets generated at the same time.

You can add the options `BUILD_SHARED_LIBS ` in CMakeLists.txt to judge if you build static library or dynamic library.
```
if(NOT BUILD_SHARED_LIBS)
      
else()

endif()
```

2020-10-28 18:10 UTC, mathisloge commented
@NancyLi1013 now it will build with PREFER_NINJA

2020-10-29 01:32 UTC, NancyLi1013 commented
Could you please resolve the conflicts?

2020-10-29 06:31 UTC, mathisloge commented
@NancyLi1013 resolved conflicts

2020-10-29 07:30 UTC, NancyLi1013 approved these changes

2020-10-29 07:33 UTC, NancyLi1013 commented
LGTM now. Have you tested the feature `restbed[openssl]`? Does it work fine?

2020-10-29 07:38 UTC, NancyLi1013 commented on ports/restbed/portfile.cmake
> +        asio-1-18-0-deprecations.patch
```suggestion
        asio-1-18-0-deprecations.patch #https://github.com/Corvusoft/restbed/pull/444/files
```
It would be better to add this comment here, so we can remove this patch in next release easily.

2020-10-29 07:49 UTC, mathisloge commented
> LGTM now. Have you tested the feature `restbed[openssl]`? Does it work fine?

I've only build with the openssl feature but didn't compile a test program. I can do that in the evening today.

2020-10-29 08:35 UTC, mathisloge commented
@NancyLi1013 I've build restbed[*] with tests. All tests are successfully.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5457022/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5457023/install-x64-windows-rel-out.log)

2020-10-29 09:02 UTC, NancyLi1013 commented
Awesome! Thanks for your test and feedback.

2020-10-30 19:47 UTC, merged

2020-10-30 19:47 UTC, BillyONeal commented
Thanks for your contribution!