[krabsetw] Add new port
microsoft/vcpkg pull request #14192
Opened 2020-10-24 06:05 UTC by jrave

**Describe the pull request**

- What does your PR fix? Fixes #
Adding new port for krabsetw

- Which triplets are supported/not supported? Have you updated the CI baseline?
Windows (non UWP) triplets are supported. Other platforms not. CI baseline not updated.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-10-25 10:50 UTC, jrave commented
/azp run

2020-10-26 08:26 UTC, NancyLi1013 commented
/azp run

2020-10-26 09:13 UTC, NancyLi1013 reviewed
Is this a header-only library?

2020-10-26 09:13 UTC, NancyLi1013 commented on ports/krabsetw/portfile.cmake
> +    REF 66294b50b75a38545eb93175baa84300a0190b59
Why do you not use the latest commit id `84b77ed85093cdffc8cc074c0b70ab90cfc1552e`?

2020-10-26 09:13 UTC, NancyLi1013 commented on ports/krabsetw/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/krabsetw RENAME copyright)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

2020-10-26 09:13 UTC, NancyLi1013 commented on ports/krabsetw/portfile.cmake
> +vcpkg_fail_port_install(MESSAGE "krabsetw currently only supports Windows" ON_TARGET "UWP" "LINUX" "OSX" "FREEBSD" "ANDROID" "MINGW" "IOS")
```suggestion
vcpkg_fail_port_install(ON_TARGET "UWP" "LINUX" "OSX" "FREEBSD" "ANDROID" "MINGW")
```
`osx` is duplicated with `ios`.

2020-10-26 15:47 UTC, jrave commented
> Is this a header-only library?

Yes it is header-only

2020-10-26 15:47 UTC, jrave commented on ports/krabsetw/portfile.cmake
> +vcpkg_fail_port_install(MESSAGE "krabsetw currently only supports Windows" ON_TARGET "UWP" "LINUX" "OSX" "FREEBSD" "ANDROID" "MINGW" "IOS")
Changed that

2020-10-26 15:47 UTC, jrave commented on ports/krabsetw/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/krabsetw RENAME copyright)
Changed that

2020-10-26 15:50 UTC, jrave commented on ports/krabsetw/portfile.cmake
> +    REF 66294b50b75a38545eb93175baa84300a0190b59
This commits refers to the latest version published to https://www.nuget.org/packages/Microsoft.O365.Security.Krabsetw/ which appears to be the official release mechanism for this library.

2020-10-28 06:02 UTC, NancyLi1013 requested changes

2020-10-28 06:02 UTC, NancyLi1013 commented on ports/krabsetw/vcpkg.json
> +  "description": "krabsetw is a C++ library that simplifies interacting with ETW.",
```suggestion
  "description": "krabsetw is a header-only C++ library that simplifies interacting with ETW.",
```
It would be nice to add header-only here.

2020-10-28 06:02 UTC, NancyLi1013 commented on ports/krabsetw/portfile.cmake
> +vcpkg_fail_port_install(ON_TARGET "UWP" "LINUX" "OSX" "FREEBSD" "ANDROID" "MINGW")
```suggestion
# Header-only library

vcpkg_fail_port_install(ON_TARGET "UWP" "LINUX" "OSX" "FREEBSD" "ANDROID" "MINGW")
```

2020-10-29 01:33 UTC, NancyLi1013 approved these changes

2020-10-29 01:34 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @jrave.

2020-10-29 07:09 UTC, merged

2020-10-29 07:09 UTC, BillyONeal commented
Thanks for your contribution!