[arrayfire] New Port
microsoft/vcpkg pull request #14240
Opened 2020-10-26 19:40 UTC by jacobkahn

Adds a new port for [ArrayFire](https://github.com/arrayfire/arrayfire). Ports all backends -- CUDA, OpenCL, and CPU.

cc @9prady9 @umar456 to join the discussion here.

Some things to note:
1. Depends on CUDA and MKL -- uses the corresponding vcpkg ports. Not sure how this affects CI here.
2. ArrayFire relies on [several submodules](https://github.com/arrayfire/arrayfire/blob/master/.gitmodules).
  a) Some of these (e.g. those for testing) aren't required and aren't present in this port.
  b) Most of the submodules that are required don't have ports and probably won't (these are ArrayFire specific projects).
  c) Some things do have ports, e.g. NVIDIA Cub. The solution here is probably to ultimately change the ArrayFire build to look for Cub on the existing system rather than downloading it.
  d) As a stopgap measure to solve these issues, the `vcpkg` config uses `vcpkg_from_github` to clone submodules as needed them moves them into their expected directories via CMake so that they can be built from source normally with calls to `add_subdirectory` from ArrayFire CMake things.
3. This is a port of 3.7.1, a recent stable release. We can update the port to 3.7.3/3.8 once those releases are out.
4. Backends are features, as in `./vcpkg install arrayfire[cuda]`. Multiple backends/features can be installed at once.
5. Only installs `libafcuda`, `libafcpu`, or `libafopencl`, as specified. Doesn't install examples, tests, or other things, although this might be useful down the road.
6. Doesn't build with forge/AF graphics features. This is probably something that can be added or changed later given that most of the needed ports are here and the forge submodule is manually cloned and moved to the right place.

> Which triplets are supported/not supported? Have you updated the CI baseline?

Have tested `x64-linux`. Might want some help testing the others.

> Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-10-27 09:54 UTC, PhoebeHui commented
@jacobkahn, could you format vcpkg.json file firstly?

See github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#manifest for solution.

2020-10-27 10:04 UTC, PhoebeHui requested changes

2020-10-27 10:04 UTC, PhoebeHui commented on ports/arrayfire/portfile.cmake
> +
I think you can rely on the ports that installed by vcpkg, and add them to Build-Depends in CONTROL file.

2020-10-27 17:33 UTC, jacobkahn commented on ports/arrayfire/portfile.cmake
> +
@PhoebeHui — the issue here is that the ArrayFire CMake build builds these projects from source using `add_subdirectory`. Is there some way to still use the vcpkg dependencies but move the project source to this directory so that it can be built by ArrayFire? What's the recommended solution her?

2020-10-28 00:40 UTC, jacobkahn commented on ports/arrayfire/portfile.cmake
> +
If the above can't be done, using clones like this is the only alternative to a recursive original clone. Of the projects that are grabbed from Github, the only ones that are definitely compatible out of the box with what ArrayFire expects are `spdlog` and `Cub`.

Thoughts?

2020-10-28 08:16 UTC, PhoebeHui commented on ports/arrayfire/portfile.cmake
> +
You can disable them to build from the external source by patching CMakeLists.txt file https://github.com/arrayfire/arrayfire/blob/master/CMakeLists.txt#L163, also for other related external libs, and add find_package or find_library, like https://github.com/arrayfire/arrayfire/blob/master/CMakeLists.txt#L45 

I think vcpkg already provides the headers that the port requires.

NVlabs/cub
find_path(CUB_INCLUDE_DIRS "cub/agent/agent_histogram.cuh")
target_include_directories(main PRIVATE ${CUB_INCLUDE_DIRS})

gabime/spdlog:
find_package(spdlog CONFIG REQUIRED)
target_link_libraries(main PRIVATE spdlog::spdlog spdlog::spdlog_header_only)

arrayfire/forge:
find_package(Forge CONFIG REQUIRED)
target_link_libraries(main PRIVATE Forge::forge)

Could you try if Dav1dde/glad meet the requirement?
find_package(glad CONFIG REQUIRED)
target_link_libraries(main PRIVATE glad::glad)

I haven't find the arrayfire/threads ports in vcpkg.

2020-10-28 22:55 UTC, jacobkahn commented
@JackBoosY @PhoebeHui — I've removed all of the submodule dependencies as mentioned (besides of [`arrayfire/threads`](https://github.com/arrayfire/threads), which is a standalone library with dependencies and has no vcpkg port).

A patch is needed for now to update the build config to search for these libraries rather than relying on their existing as submodules. Hopefully there can be more flexibility with the build in future ArrayFire releases such that we don't need the patch, cc @umar456 @9prady9.

2020-10-28 22:56 UTC, jacobkahn commented on ports/arrayfire/portfile.cmake
> +
@PhoebeHui this ended up working great - thanks for finding those ports and CMake exported targets for me! I've added a patch that contains these needed changes.

2020-10-29 06:01 UTC, PhoebeHui commented
@jacobkahn, here is CI test failure:

x64-windows and x64-windows-static:
```
-- Performing post-build validation
The following cmake files were found outside /share/arrayfire. Please place cmake files in /share/arrayfire.

    D:/packages/arrayfire_x64-windows/cmake/ArrayFireConfig.cmake
    D:/packages/arrayfire_x64-windows/cmake/ArrayFireConfigVersion.cmake
    D:/packages/arrayfire_x64-windows/cmake/ArrayFireUnifiedTargets-release.cmake
    D:/packages/arrayfire_x64-windows/cmake/ArrayFireUnifiedTargets.cmake
    D:/packages/arrayfire_x64-windows/debug/cmake/ArrayFireConfig.cmake
    D:/packages/arrayfire_x64-windows/debug/cmake/ArrayFireConfigVersion.cmake
    D:/packages/arrayfire_x64-windows/debug/cmake/ArrayFireUnifiedTargets-debug.cmake
    D:/packages/arrayfire_x64-windows/debug/cmake/ArrayFireUnifiedTargets.cmake

The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.
    D:/packages/arrayfire_x64-windows/lib/af.dll
The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.
    D:/packages/arrayfire_x64-windows/debug/lib/af.dll
Found 3 error(s). Please correct the portfile:
    C:\a\1\s\ports\arrayfire\portfile.cmake
```

x64-osx:
```
In file included from /Users/vagrant/Data/installed/x64-osx/include/boost/stacktrace/safe_dump_to.hpp:217:
/Users/vagrant/Data/installed/x64-osx/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error: "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if _Unwind_Backtrace is available without `_GNU_SOURCE`."
#error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if _Unwind_Backtrace is available without `_GNU_SOURCE`."
 ^
1 error generated.
```
[failure logs for x64-osx (13).zip](https://github.com/microsoft/vcpkg/files/5456412/failure.logs.for.x64-osx.13.zip)

2020-10-29 06:09 UTC, PhoebeHui commented
For the post build check failrues, you can use the vcpkg_fixup_cmake_targets(CONFIG_PATH cmake) to fix the cmake targets issue.
For the af.dll issue, you need to patch the CMakeLists file to install the

2020-10-29 06:15 UTC, PhoebeHui requested changes

2020-10-29 06:15 UTC, PhoebeHui commented on ports/arrayfire/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

# Copyright and license
file(INSTALL ${SOURCE_PATH}/COPYRIGHT.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME license)

```

2020-10-29 06:15 UTC, PhoebeHui commented on ports/arrayfire/portfile.cmake
> +    opencl AF_BUILD_OPENCL
Have you test these features locally?

2020-10-29 06:25 UTC, jacobkahn commented on ports/arrayfire/portfile.cmake
> +    opencl AF_BUILD_OPENCL
Yes, everything works well.

2020-10-29 07:36 UTC, PhoebeHui commented
The latest CI test failures:
x64-windows: you need to check why it doesn't generate for debug configuration.
```
-- Performing post-build validation
Mismatching number of debug and release binaries. Found 0 for debug but 1 for release.
Debug binaries
Release binaries
    D:/packages/arrayfire_x64-windows/bin/af.dll
Debug binaries were not found
Found 1 error(s). Please correct the portfile
```

x64-windows-static: you need to check why it generated in a static build, and patch the CMakeLists.txt file to fix this issue, rather that removing the bin folder.
```
DLLs should not be present in a static build, but the following DLLs were found:
    D:/packages/arrayfire_x64-windows-static/bin/af.dll

There should be no bin\ directory in a static build, but D:\packages\arrayfire_x64-windows-static\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()
Found 2 error(s). Please correct the portfile
```

2020-10-30 05:32 UTC, 9prady9 commented on ports/arrayfire/vcpkg.json
> +        "intel-mkl"
@jacobkahn ArrayFire doesn't need fftw3 if it uses Intel MKL. This dependency can be removed.

2020-10-30 05:47 UTC, 9prady9 commented on ports/arrayfire/vcpkg.json
> +  "description": "ArrayFire is a general-purpose library that simplifies the process of developing software that targets parallel and massively-parallel architectures including CPUs, GPUs, and other
I think `"supports": "x64"` should be added instead of all architectures. x64/x86_64/amd64 is what ArrayFire officially supports.

2020-10-30 06:03 UTC, 9prady9 commented on ports/arrayfire/portfile.cmake
> +  set(AF_BIN_DIR ${CURRENT_PACKAGES_DIR}/debug/bin)
@jacobkahn I believe these two conditions are what causing the behavior w.r.t dlls being misplaced across configurations.
release
```
-- Installing: D:/packages/arrayfire_x64-windows/debug/lib/af.lib
-- Installing: D:/packages/arrayfire_x64-windows/debug/bin/af.dll
-- Installing: D:/packages/arrayfire_x64-windows/debug/lib/af.pdb
```
release
```
-- Installing: D:/packages/arrayfire_x64-windows/lib/af.lib
-- Installing: D:/packages/arrayfire_x64-windows/debug/bin/af.dll
```

It willd be worth looking at these. If `VCPKG_BUILD_TYPE` is not defined, there is always an extra `debug` infix in the path, is that the expected behavior in such scenario ?

2020-10-30 19:31 UTC, jacobkahn commented
@PhoebeHui @JackBoosY — tests are passing - I think this is ready for a final review.

2020-11-02 16:25 UTC, jacobkahn commented
@PhoebeHui @JackBoosY bump

2020-11-03 05:12 UTC, 9prady9 commented
> @PhoebeHui @JackBoosY bump

Please let us know if there is anything else that needs to be addressed here. Thank you.

2020-11-03 05:56 UTC, JackBoosY approved these changes

2020-11-03 05:57 UTC, JackBoosY commented
Since your changes is huge, does the official accept them?

2020-11-03 06:27 UTC, PhoebeHui requested changes

2020-11-03 06:27 UTC, PhoebeHui commented on ports/arrayfire/vcpkg.json
> +  "port-version": 1,
```suggestion
  "port-version": 0,
```

2020-11-03 07:03 UTC, 9prady9 commented
> Since your changes is huge, does the official accept them?

Do you mean does arrayfire approve of the patch that is submitted in this port ?

2020-11-03 07:04 UTC, PhoebeHui commented
@BillyONeal, the arrayfire port haven't been test in CI system from build https://dev.azure.com/vcpkg/public/_build/results?buildId=44791&view=results, could you help have a look?

arrayfire:x64-windows:    cascade: 5cb12df794ddbae1efd99ab6fb0b459048019f8d

I checked the arrayfire dependency port, all are passed. I'm not sure why it cascade.

2020-11-03 07:07 UTC, JackBoosY commented
> > Since your changes is huge, does the official accept them?
> 
> Do you mean does arrayfire approve of the patch that is submitted in this port ?

I saw these changes have nothing to do with implementation, so ignore my comment. That's okay.

2020-11-04 08:55 UTC, JonLiu1993 commented
@jacobkahn, hello, 
I tested the features of jacobkahn [cpu], jacobkahn [cuda] and jacobkahn [opencl], and jacobkahn [unified], none of which can be built on Linux. Can you solve them? Below is their failure log：

````
-- Found Boost: F:/test7/vcpkg/installed/x64-windows/include (found version "1.73.0")  
CMake Error at CMakeModules/InternalUtils.cmake:10 (message):
  FFTW not found
Call Stack (most recent call first):
  src/backend/cpu/CMakeLists.txt:312 (dependency_check)


CMake Error at CMakeModules/InternalUtils.cmake:10 (message):
  CBLAS not found
Call Stack (most recent call first):
  src/backend/cpu/CMakeLists.txt:313 (dependency_check)


-- No git. Setting hash to default
-- Configuring incomplete, errors occurred!
See also "F:/test7/vcpkg/buildtrees/arrayfire/x64-windows-rel/CMakeFiles/CMakeError.log".
````
F:/test7/vcpkg/buildtrees/arrayfire/x64-windows-rel/CMakeFiles/CMakeError.log:
````
Determining if the include file pthread.h exists failed with the following output:
Change Dir: F:/test7/vcpkg/buildtrees/arrayfire/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command(s):F:/test7/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe cmTC_d3a8a && [1/2] Building C object CMakeFiles\cmTC_d3a8a.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_d3a8a.dir/CheckIncludeFile.c.obj 

C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe  /nologo   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_d3a8a.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_d3a8a.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.
````

2020-11-04 09:07 UTC, 9prady9 commented
> Hi @jacobkahn, I tested the features of jacobkahn [cpu], jacobkahn [cuda] and jacobkahn [opencl], and jacobkahn [unified], none of which can be built on Windows. They all failed with same issue, could you please take a look? Below is their failure log：
> 
> ```
> -- Found Boost: F:/test7/vcpkg/installed/x64-windows/include (found version "1.73.0")  
> CMake Error at CMakeModules/InternalUtils.cmake:10 (message):
>   FFTW not found
> Call Stack (most recent call first):
>   src/backend/cpu/CMakeLists.txt:312 (dependency_check)
> 
> CMake Error at CMakeModules/InternalUtils.cmake:10 (message):
>   CBLAS not found
> Call Stack (most recent call first):
>   src/backend/cpu/CMakeLists.txt:313 (dependency_check)
> 
> -- No git. Setting hash to default
> -- Configuring incomplete, errors occurred!
> See also "F:/test7/vcpkg/buildtrees/arrayfire/x64-windows-rel/CMakeFiles/CMakeError.log".
> ```
> 
> [config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5486652/config-x64-windows-out.log)

hi @JonLiu1993  Is this with Intel-MKL installed on Windows ?

2020-11-04 09:14 UTC, JonLiu1993 commented
Hi @9prady9 ,Yes, I have installed Intel-MKL on windows

2020-11-04 09:22 UTC, 9prady9 commented
> Hi @9prady9 ,Yes, I have installed Intel-MKL on windows

Ok, @jacobkahn Looks like the setting `USE_CPU_MKL` and `USE_OPENCL_MKL` to `ON` on relevant features on vcpkg port is missing. Can you please add those.

@JonLiu1993 I don't quite yet understand why CUDA would fail. The dependency FFTW is looked for but only used/checked for in CPU backend builds. Does trying to install `arrayfire[cuda]` install default features `cpu | unified` too ?

2020-11-04 09:28 UTC, PhoebeHui commented
@9prady9, yes, it would install the default feature 'cpu' and 'unified'.

2020-11-04 09:29 UTC, 9prady9 commented
> @9prady9, yes, it would install the default feature 'cpu' and 'unified'.

Ok that makes sense. Once @jacobkahn adds the missing `USE*` flags in, this error should go away.

2020-11-04 17:05 UTC, jacobkahn commented
@JonLiu1993 — I've added those flags, cc @9prady9. Thanks both of you for catching that. Can you try things again @JonLiu1993 so we can see if we still have an FFTW issue?

2020-11-05 04:25 UTC, JonLiu1993 commented
@jacobkahn , I tested the default and other functions of arrayfire again, but it still failed. Below is the failure log. could you please take a look? 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5491978/install-x64-windows-dbg-out.log)

2020-11-05 08:09 UTC, jacobkahn commented
@JonLiu1993 this looks like `events.hpp` in [`arrayfire/threads`](https://github.com/arrayfire/threads/) was missing a `#pragma once` in the submodule commit for which 3.7.1 is compiled which caused those definitions to be duplicated.

I added a patch to fix it. I unfortunately don't have an x64 Windows env with which to test the fix - please let me know if there are any errors! Thanks again for helping test.

2020-11-05 10:19 UTC, JonLiu1993 commented
@jacobkahn ,I tested it again and it still seems that there are some problems, can you take a look?
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5493570/install-x64-windows-dbg-out.log)

2020-11-05 22:09 UTC, jacobkahn commented
@JonLiu1993 — just added a fix for that issue — a header in the threads library was conflicting with a Windows std C++ header. Reverted part of the patch (which removes a necessary infix) to resolve it. Thanks to @9prady9 for helping me debug.

Can you try once more? Thanks!

2020-11-06 06:49 UTC, JonLiu1993 commented
@jacobkahn ,I tested it again, and now the DEBUG version can be compiled, but an error occurred when compiling the RELEASE version. I checked the log and found that some problems occurred during the installation of RELEASE. Some dlls of RELEASE were installed. In the debug directory, this problem exists in every feature of arrayfire. Hope this discovery can help you solve the problem
````
Mismatching number of debug and release binaries. Found 3 for debug but 0 for release.
Debug binaries

    F:/test7/vcpkg/packages/arrayfire_x64-windows/debug/bin/af.dll
    F:/test7/vcpkg/packages/arrayfire_x64-windows/debug/bin/afcpu.dll
    F:/test7/vcpkg/packages/arrayfire_x64-windows/debug/bin/afopencl.dll

Release binaries


Release binaries were not found

Found 1 error(s). Please correct the portfile:
    F:\test7\vcpkg\ports\arrayfire\portfile.cmake
-- Performing post-build validation done
Error: Building package arrayfire:x64-windows failed with: POST_BUILD_CHECKS_FAILED
````
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5499619/install-x64-windows-rel-out.log)

2020-11-07 14:46 UTC, 9prady9 commented
@JonLiu1993 Any idea why would `VCPKG_BUILD_TYPE` be empty when vcpkg configures the project ? At which point is this variable set in the workflow so that I can use it appropriately ?

The reason I ask this is, although @jacobkahn is checking this (as shown below) in the portfile
```cmake
# bin/dll directory for Windows non-static builds for the unified backend dll
if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_LIBRARY_LINKAGE STREQUAL "static")
  if (NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
    set(AF_BIN_DIR ${CURRENT_PACKAGES_DIR}/bin)
  endif()
  if (NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
    set(AF_BIN_DIR ${CURRENT_PACKAGES_DIR}/debug/bin)
  endif()
  file(MAKE_DIRECTORY ${AF_BIN_DIR})
  set(AF_DEFAULT_VCPKG_CMAKE_FLAGS ${AF_DEFAULT_VCPKG_CMAKE_FLAGS} -DAF_INSTALL_BIN_DIR:PATH=${AF_BIN_DIR})
endif()
```
when I print the value of `VCPKG_BUILD_TYPE`, it is coming out as empty on command line output when the install command runs. Hence, the error of both debug and release dlls being copied over into same folder. I confirmed this from the value of `AF_INSTALL_BIN_DIR` in the `CMakeCache.txt` from debug and release config folders.

2020-11-08 05:29 UTC, BillyONeal commented
> @JonLiu1993 Any idea why would `VCPKG_BUILD_TYPE` be empty when vcpkg configures the project ? At which point is this variable set in the workflow so that I can use it appropriately ?

That is set by a triplet, if it wants to. Most of the time it will be empty, which means a port needs to mint both release and debug bits. Note examples which all do:

```
if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
# release bits
endif()
if (NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
#debug bits
endif()
```

2020-11-08 05:52 UTC, 9prady9 commented
@BillyONeal I have seen the other port files that are using similar pattern. Hence, my confusion on what is @jacobkahn missing in the code that isn't setting the build configuration. I don't quite understand how triplet will indicate build configuration/type ? `vcpkg install arrayfire:x64-windows` command doesn't have a build configuration, but both debug and release are built by that command. So, I would expect the build type to be set appropriately when that particular configuration is built. Is there something in the port file code that one needs to add to ensure that ?

2020-11-08 05:53 UTC, BillyONeal commented
>Hence, my confusion on what is @jacobkahn missing in the code that isn't setting the build configuration.

The default is "not set", meaning a port must produce both release and debug bits. The option can only be set by a triplet author. None of our in-box triplets set it.

2020-11-08 05:56 UTC, 9prady9 commented
> > Hence, my confusion on what is @jacobkahn missing in the code that isn't setting the build configuration.
> 
> The default is "not set", meaning a port must produce both release and debug bits. The option can only be set by a triplet author. None of our in-box triplets set it.

what is the suggested work around for the problem we are having here where the `INSTALL` cmake variable is being set to same path in both debug and release configurations because build type is not set ?

2020-11-09 20:38 UTC, jacobkahn commented
@JonLiu1993 — I've just sent what I think should be a catch-all fix for all of the DLLs generated by the build. Sorry this took so long - it's extremely slow to experiment and iterate in my environment. Things work with `x64-windows` for me — hopefully they do for you too now and we can get this merged!

@BillyONeal I think we were getting hung up on a weird Ninja multiconfig scenario where cache variables weren't being changed across configs - either way, a patch was required to get the behavior we need. Thanks for those pointers.

That said, the idea that a DLL path would have to be determined via a `CMAKE_BUILD_TYPE` check inside a project's CMake seems odd to me, so I'd be more interested in seeing what other projects do to resolve this. It seems like most projects have a bunch of other cruft that move DLLs around (or remove them entirely) because of how `VCPKG_BUILD_TYPE` might not be defined and a path can't be reliably passed. If you have examples of projects that do that in the recommended way, that would be helpful to understand for future iterations of this port.

2020-11-09 22:58 UTC, BillyONeal commented
>if NOT defined VCPKG_BUILD_TYPE is causing the second if to become true always irrespective of what config is being built.

`portfile.cmake` does not have a config; it is only built once. `portfile.cmake` is obligated to invoke the library in question's build system such that it produces both release and debug bits. For example, `vcpkg_configure_cmake` invokes a port's cmake-based build system twice; once for release, and once for debug: https://github.com/microsoft/vcpkg/blob/10c38371cb264932530b7e175b34712f48c15264/scripts/cmake/vcpkg_configure_cmake.cmake#L299-L307

>@BillyONeal I think we were getting hung up on a weird Ninja multiconfig scenario where cache variables weren't being changed across configs - either way, a patch was required to get the behavior we need.

vcpkg doesn't inject any ninja multiconfig stuff.

>the idea that a DLL path would have to be determined via a CMAKE_BUILD_TYPE check inside a project's CMake seems odd to me, so I'd be more interested in seeing what other projects do to resolve this.

The port builds as normal and uses `install(` to install the resulting binaries where that's been configured. vcpkg passes `CMAKE_INSTALL_PREFIX` to make sure `install(` drops the bits in the right place:

https://github.com/microsoft/vcpkg/blob/6ba00186b11754db7a9a83a0e53cd921dfbd5ca8/scripts/cmake/vcpkg_configure_cmake.cmake#L268-L277

2020-11-09 23:55 UTC, jacobkahn commented
@BillyONeal thanks for taking the time to write all that up. That's really helpful.

> The port builds as normal and uses `install(` to install the resulting binaries where that's been configured. vcpkg passes `CMAKE_INSTALL_PREFIX` to make sure `install(` drops the bits in the right place:

I see that the prefix has the `debug` infix... so it should have been prepended to `RUNTIME DESTINATION` for the DLLs dropped into place by `install(`. I suppose I still have absolutely no idea why that didn't work - using `CMAKE_BUILD_TYPE` as a proxy for whether or not to add `debug` to the path appears necessary on `x64-windows` with my particular config. Probably something wrong with my environment or the project's config, but I have no clue. Seems like that repro for @JonLiu1993 as well. In any event, this works for now...

2020-11-10 06:20 UTC, JonLiu1993 commented
@jacobkahn ,I just tested the default arrayfire and its features. Except for the cuda features, everything else is successful. The version of cuda installed in my test environment is v11，The attachment is its complete log，could you please take a look?
````
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at cuda_compile_4_generated_thrust_sort_by_key_impl_double_1.cu.obj.Debug.cmake:220 (message):
  Error generating
````
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5515223/install-x64-windows-dbg-out.log)

2020-11-10 07:20 UTC, jacobkahn commented
@JonLiu1993 — good catch and thanks for testing - just patched the build to work for CUDA 11. A future version of this port with a newer ArrayFire version will have this updated code and won't require a patch for those nvcc flags, but this should work fine for now.

One more try would be great (I don't have a GPU accessible from my Windows VM). Thanks again!

2020-11-10 08:27 UTC, JonLiu1993 commented
@jacobkahn ,I just re-tested the cuda feature and it failed. The problem seems to have not been resolved through the log. The following is the complete log. Please take a look 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5515846/install-x64-windows-dbg-out.log)

2020-11-10 23:36 UTC, jacobkahn commented
@JonLiu1993 fixed. Also reprod the issue - pushed a fix I've confirmed works on Linux. Can you give it one last try?

2020-11-11 00:04 UTC, jacobkahn commented
@JonLiu1993 — turns out the ArrayFire commit the port is checked out too doesn't work too well with CUDA 11. I'm going to try a different commit and re-work the patch. I'll push that up and let you know when it's done.

2020-11-11 19:12 UTC, jacobkahn commented
@JonLiu1993 — just updated the port's commit. Tested with CUDA 11 on Linux and everything builds. Let's test on Windows once more.

2020-11-12 01:58 UTC, JonLiu1993 commented
@jacobkahn ,I just updated and tested the latest submission. It seems that there are still some problems. Can you take a look?
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5527778/install-x64-windows-dbg-out.log)

2020-11-12 17:41 UTC, jacobkahn commented
@JonLiu1993 turns out there are difficulties compiling with MSVC 2019, but not with 2017, cc @9prady9 @umar456. I think a fix for these is in the works, but may not be ready for some time, and we'd like to land the port as is. Is it possible to detect the MSVC compiler version in the port file with some vcpkg variable? cc @PhoebeHui @JackBoosY

2020-11-14 03:26 UTC, BillyONeal commented
> Waiting is fine, but is it possible to detect the MSVC compiler version in the port file with some vcpkg variable?

Not with a vcpkg variable but the library's build system has that ability.

2020-11-16 16:33 UTC, jacobkahn commented
@JonLiu1993 — everything should work with MSVC 2019 now as per those fixes from @9prady9 @umar456. Can you test one more time on your machine? I've re-tested on Linux, and things look good.

2020-11-17 02:32 UTC, PhoebeHui commented
@jacobkahn, the libarchive issue has been fixed, it doesn't relate to this change, please ignore it, I have rerun the CI testing.

2020-11-17 07:11 UTC, jacobkahn commented
@PhoebeHui Thanks. We'll wait for one more test from @JonLiu1993.

2020-11-17 08:39 UTC, JonLiu1993 commented
@jacobkahn ,I tested the default triplet of arraryfire and x64-windows of all features, they all built successfully. Good job！

2020-11-17 16:55 UTC, jacobkahn commented
Looks like the `x64_osx` is stuck @PhoebeHui — once that's fixed, I think we're ready to merge?

2020-11-18 02:26 UTC, PhoebeHui commented
@jacobkahn, I checked, the CI testing with x64-osx is in progress. Let's wait for the results.

2020-11-18 07:17 UTC, jacobkahn commented
@PhoebeHui it looks like the macOS CI is stuck again...

2020-11-18 07:26 UTC, PhoebeHui commented
/azp run

2020-11-18 08:11 UTC, PhoebeHui approved these changes

2020-11-18 08:15 UTC, PhoebeHui commented
Thanks all for making this possible!

@strega-nil, could you please help review and merge this PR?

All features test passed with x64-windows, tested by @JonLiu1993 
All features test passed with x64-linux, tested by @jacobkahn

2020-11-18 19:29 UTC, strega-nil requested changes

2020-11-18 19:29 UTC, strega-nil commented on ports/arrayfire/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME license)
```suggestion
file(INSTALL ${SOURCE_PATH}/COPYRIGHT.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

This is the standard naming convention in vcpkg.

2020-11-18 19:29 UTC, strega-nil commented on ports/arrayfire/portfile.cmake
> +if(EXISTS ${CURRENT_PACKAGES_DIR}/share/ArrayFire/cmake)
Should this be an `elseif()`?

2020-11-18 19:29 UTC, strega-nil commented on ports/arrayfire/portfile.cmake
> +)
```suggestion
vcpkg_configure_cmake(
  SOURCE_PATH ${SOURCE_PATH}
  PREFER_NINJA
  OPTIONS
    ${AF_DEFAULT_VCPKG_CMAKE_FLAGS}
    ${AF_BACKEND_FEATURE_OPTIONS}
  )
```

keepin the indentation the same.

2020-11-18 19:29 UTC, strega-nil commented on ports/arrayfire/portfile.cmake
> +  set(AF_DEFAULT_VCPKG_CMAKE_FLAGS ${AF_DEFAULT_VCPKG_CMAKE_FLAGS} -DAF_BIN_DIR=${AF_BIN_DIR})
```suggestion
  list(APPEND AF_DEFAULT_VCPKG_CMAKE_FLAGS "-DAF_BIN_DIR=${AF_BIN_DIR}")
```

2020-11-18 19:29 UTC, strega-nil commented on ports/arrayfire/portfile.cmake
> +)
```suggestion
vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO arrayfire/arrayfire
  REF 646bdeed1557abfdfe6735b9d20377c5b08a12da # v3.7.3
  SHA512 8af15c25bc46235c0554dad963d94c36ae078e2ad7e65ccbbe101e9f06c33618b52207c0a26b8dd56b3d7c9e0032ea75d08f18a5644eadbf56fefe5952aff699
  HEAD_REF master
  PATCHES build.patch
  )
```
keepin that indentation

2020-11-18 19:30 UTC, strega-nil approved these changes

2020-11-18 19:31 UTC, strega-nil commented
@jacobkahn could you respond to whether the `endif();if()` pair should be an elseif()? then I'll merge :)

2020-11-18 19:42 UTC, jacobkahn commented on ports/arrayfire/portfile.cmake
> +if(EXISTS ${CURRENT_PACKAGES_DIR}/share/ArrayFire/cmake)
Hi @strega-nil — this can be `elseif()`, sure, since this condition won't be met on Windows.

2020-11-18 19:42 UTC, jacobkahn commented
@strega-nil — just responded. Thanks for the review and those fixes!

2020-11-18 21:05 UTC, strega-nil commented on ports/arrayfire/portfile.cmake
> +if(EXISTS ${CURRENT_PACKAGES_DIR}/share/ArrayFire/cmake)
```suggestion
elseif(EXISTS ${CURRENT_PACKAGES_DIR}/share/ArrayFire/cmake)
```

2020-11-18 21:53 UTC, jacobkahn commented
@strega-nil — it looks like the `elseif` change means one other tweak is necessary (need to update the patch) — sending a fix in a moment.

2020-11-19 00:01 UTC, strega-nil commented
@jacobkahn alright, cool, thanks!

2020-11-19 03:21 UTC, jacobkahn commented
/azp run

2020-11-19 18:50 UTC, strega-nil commented
Alright, this looks great :) Thanks @jacobkahn :)

2020-11-19 18:50 UTC, merged

2020-12-24 05:55 UTC, jinggaizi commented
when i install arrayfire with vcpkg ; 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j41
    Working Directory:cpkg/buildtrees/arrayfire/x64-linux-dbg
    See logs for more information:
     vcpkg/buildtrees/arrayfire/install-x64-linux-dbg-out.log

i check the install-x64-linux-dbg-out.log ，it appear "ninja: build stopped: subcommand failed" end of this file

2020-12-24 09:10 UTC, JackBoosY commented
@jinggaizi Can you open a new issue to report that?
Note you also should provide the full error logs.

Thanks.

2020-12-25 07:52 UTC, jinggaizi commented
> @jinggaizi Can you open a new issue to report that?
> Note you also should provide the full error logs.
> 
> Thanks.

thanks for your reply , i use gcc version 6.3.1 and fix the problem