[libnice] Fix build error on Linux
microsoft/vcpkg pull request #14248
Opened 2020-10-27 06:39 UTC by LilyWangL

**Describe the pull request**

- What does your PR fix? Fixes #13483
Fix `libnice` build failed on Linux.

2020-11-04 08:01 UTC, JackBoosY requested changes

2020-11-04 08:01 UTC, JackBoosY commented on ports/libnice/CMakeLists.txt
>  set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "/wd4244 /wd4005 /wd4391 /wd4142 /wd4267")
```suggestion
    set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "/wd4244 /wd4005 /wd4391 /wd4142 /wd4267")
```

2020-11-04 08:01 UTC, JackBoosY commented on ports/libnice/CMakeLists.txt
>  target_link_libraries(libnice ${IPHLPAPI_LIBRARY} ${WS2_32_LIB} ${ADVAPI32_LIB} ${GLIB_LIBRARY} ${GOBJECT_LIBRARY} ${GIO_LIBRARY} OpenSSL::SSL)
```suggestion
    target_link_libraries(libnice ${IPHLPAPI_LIBRARY} ${WS2_32_LIB} ${ADVAPI32_LIB} ${GLIB_LIBRARY} ${GOBJECT_LIBRARY} ${GIO_LIBRARY} OpenSSL::SSL)
```

2020-11-04 08:01 UTC, JackBoosY commented on ports/libnice/CMakeLists.txt
> +target_link_libraries(libnice ${GLIB_LIBRARY} ${GOBJECT_LIBRARY} ${GIO_LIBRARY} OpenSSL::SSL)
```suggestion
    target_link_libraries(libnice ${GLIB_LIBRARY} ${GOBJECT_LIBRARY} ${GIO_LIBRARY} OpenSSL::SSL)
```

2020-11-04 08:02 UTC, JackBoosY commented on ports/libnice/CMakeLists.txt
> +        -D_SCL_SECURE_NO_WARNINGS
```suggestion
```

2020-11-04 08:02 UTC, JackBoosY approved these changes

2020-11-05 09:28 UTC, LilyWangL commented
Baseline error will be fixed in PR #14400

2020-11-06 21:31 UTC, merged