[many ports] Add GnuTLS and its dependencies
microsoft/vcpkg pull request #14242
Opened 2020-10-26 20:29 UTC by wrobelda

This PR provides a port for GnuTLS library and its dependencies. 

- Which triplets are supported/not supported? Have you updated the CI baseline?
Currently testing under macOS only, will update list of triplets supported once tested on all platforms.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Still a work in progress.

2020-11-29 05:14 UTC, odskinz488 commented
can you please hurry up to port this library faster?!

2020-11-30 03:01 UTC, JackBoosY commented
@odskinz488 You can open a new PR, inherit these changes and continue.

2021-02-07 06:31 UTC, JackBoosY commented
Pinging @wrobelda for response. Is work still being done for this PR?

2021-02-07 06:59 UTC, wrobelda commented
@JackBoosY I intend to finish this work, got held back by migrating to Apple Silicon last month.

2021-02-28 19:53 UTC, wrobelda commented
@JackBoosY ready for review. Linux only, for now.

2021-03-01 02:57 UTC, wrobelda commented
@JackBoosY I just got it to work on macOS, about to commit those changes

2021-03-01 03:02 UTC, JackBoosY commented on ports/libgnutls/CONTROL
> +Supports: linux, osx
```suggestion
Supports: linux | osx

```

2021-03-01 03:02 UTC, JackBoosY requested changes

2021-03-01 03:02 UTC, JackBoosY commented on ports/libgnutls/CONTROL
> +Supports: linux, osx
```suggestion
Supports: !windows
```

2021-03-01 03:02 UTC, JackBoosY commented on ports/libtasn1/CONTROL
> +Supports: linux, osx
```suggestion
Supports: !windows
```

2021-03-01 03:11 UTC, wrobelda commented
@JackBoosY the CI build is being skipped for `libgnutls`: "libgnutls:x64-osx:    cascade"

2021-03-01 05:39 UTC, JackBoosY commented
@wrobelda  Because libgnutls dependency can't be built on OSX now.

2021-03-01 05:40 UTC, JackBoosY requested changes

2021-03-01 05:40 UTC, JackBoosY commented on versions/l-/libgnutls.json
> +      "git-tree": "514174165bb692927e6af1b8d0ba877977760235",
```suggestion
      "git-tree": "0475cd142427a78431e3cc124b5ec14b189854b7",
```

2021-03-01 05:40 UTC, JackBoosY commented on versions/l-/libtasn1.json
> +      "git-tree": "40e3f04762264c9abfbd1046a58e0e08768c45dd",
```suggestion
      "git-tree": "74b4837de3f9ea6b15db7cfcba384a75c91a20d4",
```

2021-03-01 05:40 UTC, JackBoosY approved these changes

2021-03-09 02:41 UTC, JackBoosY approved these changes

2021-03-11 20:42 UTC, merged

2021-03-11 20:42 UTC, ras0219-msft commented
This LGTM, thanks for the PR!