[libxml2] Add link libraries for target LibXml2::LibXml2
microsoft/vcpkg pull request #14478
Opened 2020-11-09 08:39 UTC by LilyWangL

**Describe the pull request**

- What does your PR fix? Fixes #14468
Target `LibXml2::LibXml2` is not linked against all necessary libraries in **vcpkg-cmake-wrapper.cmake**. Target `LibXml2::LibXml2` should link with `Iconv`, `Charset`, `lzma`, `zlib`, `ws2_32` (windows only) libraries.

2020-11-09 08:52 UTC, JackBoosY approved these changes

2020-11-10 09:02 UTC, jmelas requested changes
I think still LIBXML2_LIBRARIES is not populated correctly
The missing libraries should first added to LIBXML2_LIBRARIES 
and then target LibXml2::LibXml2 should link with these libraries.

2020-11-10 09:50 UTC, LilyWangL commented
> I think still LIBXML2_LIBRARIES is not populated correctly.
> The missing libraries should first be added to LIBXML2_LIBRARIES variable
> and then target LibXml2::LibXml2 should link with this variable.

Due to `libiconv` and `libcharset` don't create lib on Linux, so it need not link to them when `CMAKE_SYSTEM_NAME STREQUAL "Linux"`. I think this handle is correct.

2020-11-10 10:31 UTC, jmelas requested changes
Now it's broken on macOS.
This is my proposition:

`if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        list(APPEND LIBXML2_LIBRARIES m)
    else()
        list(APPEND LIBXML2_LIBRARIES ${ICONV_LIBRARIES} ${CHARSET_LIBRARIES} ${LIBLZMA_LIBRARIES} ${ZLIB_LIBRARIES})
        if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
            list(APPEND LIBXML2_LIBRARIES ws2_32)
        endif()
    endif()
    if(TARGET LibXml2::LibXml2)
        target_link_libraries(LibXml2::LibXml2 INTERFACE ${LIBXML2_LIBRARIES})
    endif()
`

2020-11-11 03:05 UTC, LilyWangL commented
Due to `libiconv` and `libcharset` don't create lib on MACOS, I think this shoule be changed to:
```
    list(APPEND LIBXML2_LIBRARIES ${LIBLZMA_LIBRARIES} ${ZLIB_LIBRARIES})
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        list(APPEND LIBXML2_LIBRARIES m)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        list(APPEND LIBXML2_LIBRARIES ${ICONV_LIBRARIES} ${CHARSET_LIBRARIES} ws2_32)
	endif()
	if(TARGET LibXml2::LibXml2)
        target_link_libraries(LibXml2::LibXml2 INTERFACE ${LIBXML2_LIBRARIES})
    endif()
```

2020-11-11 08:58 UTC, jmelas approved these changes

2020-11-11 08:59 UTC, jmelas approved these changes

2020-11-12 20:08 UTC, Neumann-A commented on ports/libxml2/vcpkg-cmake-wrapper.cmake
> +        target_link_libraries(LibXml2::LibXml2 INTERFACE ${LIBXML2_LIBRARIES})
Simply no. This is linking itself. LIBXML2_LIBRARIES is not empty after the `find_package` call but contains the libxml2 library.

2020-11-12 23:38 UTC, strega-nil commented on ports/libxml2/vcpkg-cmake-wrapper.cmake
> +        target_link_libraries(LibXml2::LibXml2 INTERFACE ${LIBXML2_LIBRARIES})
Yeah, I think I agree with this; could we switch to the old code, but add `target_link_libraries` below the second `list(APPEND`?

2020-11-16 08:31 UTC, JackBoosY commented
Replaced by #14588.

2020-11-16 08:31 UTC, closed without merging