[nuspell] Update version to 4.0.1
microsoft/vcpkg pull request #14505
Opened 2020-11-10 19:19 UTC by dimztimz

**Describe the pull request**

- What does your PR fix?

Updates port.

- Which triplets are supported/not supported? Have you updated the CI baseline?

All. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes.

2020-11-11 02:23 UTC, NancyLi1013 requested changes

2020-11-11 02:23 UTC, NancyLi1013 commented on ports/nuspell/portfile.cmake
```suggestion
```

2020-11-11 02:23 UTC, NancyLi1013 commented on ports/nuspell/portfile.cmake
> +    PATCHES 0001-Disable-CLI-tool-and-docs.patch
```suggestion
    PATCHES cmake-disable-cli-and-docs.patch
```
Since the patch modifies the same problem as before. It would be better to use the original patch name.

2020-11-11 09:07 UTC, dimztimz commented on ports/nuspell/portfile.cmake
Fixed.

2020-11-11 09:08 UTC, dimztimz commented on ports/nuspell/portfile.cmake
> +    PATCHES 0001-Disable-CLI-tool-and-docs.patch
Fixed.

2020-11-12 01:58 UTC, NancyLi1013 approved these changes

2020-11-12 02:01 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @dimztimz.

2020-11-12 20:42 UTC, merged