[Catch2] Update to v3.0.0
microsoft/vcpkg pull request #14503
Opened 2020-11-10 16:20 UTC by Link1J

**Describe the pull request**
Update Catch2 to v3.0.0. As v3.0.0 is a breaking change, this update attempts to help informing users about the change.
1) Informs the user about the update, and where or how to find fixes. 
2) Add a feature to use v2 (updated to 2.13.3) over v3
3) Removes v2's forwarder. I don't think it is needed anymore.

*This pull request is here, waiting for v3.0.0 to come out. It currently is available for testing and review.*

- What does your PR fix? Fixes #14391 

- Which triplets are supported/not supported? Have you updated the CI baseline?
No changes

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes, I think so.

2020-11-11 07:28 UTC, NancyLi1013 commented
The failures for `coolprop`:

```
CMake Error at ports/coolprop/portfile.cmake:22 (file):
  file COPY cannot find "D:/installed/x64-windows/include/catch.hpp": No such
  file or directory.
Call Stack (most recent call first):
  scripts/ports.cmake:135 (include)
```

The failures for `msix`:

```
D:\buildtrees\msix\src\8872d686f2-b64fdbf79e.clean\src\test\msixtest\unpack.cpp(5): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory

D:\buildtrees\msix\src\8872d686f2-b64fdbf79e.clean\src\test\msixtest\msixtest.cpp(6): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory

D:\buildtrees\msix\src\8872d686f2-b64fdbf79e.clean\src\test\msixtest\api_manifestreader.cpp(6): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
```

2020-11-11 07:29 UTC, NancyLi1013 commented
Have you tested the feature v2? Does this feature work fine?

2020-11-11 14:37 UTC, Link1J commented
Corrected build errors.
Do I need to update the `port-version` for `msix` and `coolprop`?

2020-11-12 02:09 UTC, NancyLi1013 requested changes

2020-11-12 02:09 UTC, NancyLi1013 commented on ports/coolprop/CONTROL
>  Version: 6.4.1
```suggestion
Version: 6.4.1
Port-Version: 1
```

2020-11-12 02:09 UTC, NancyLi1013 commented on ports/msix/CONTROL
>  Version: 1.7-2
```suggestion
Version: 1.7
Port-Version: 3
```

2020-11-12 02:17 UTC, NancyLi1013 commented
> Do I need to update the `port-version` for `msix` and `coolprop`?

Yes,` Port-Version` is needed here.

Now is this PR waiting for v3.0.0 release?

2020-11-12 12:57 UTC, Link1J commented
Yes. That is all that is being waited for.

2021-02-08 07:24 UTC, NancyLi1013 commented
Hi @Link1J 

Since this PR requires a new release from upstream. We're also not sure when the release will be ready.

I think we can close this PR for now. You can reopen this if there is a new release on upstream.

What do you think?

2021-02-08 12:01 UTC, Link1J commented
That sounds fine to me.

2021-02-09 02:10 UTC, closed without merging