Make aws-sdk-cpp rpath relocatable (fix #14544)
microsoft/vcpkg pull request #14546
Opened 2020-11-12 15:29 UTC by klalumiere

This is important since vcpkg offers binary caching which could be
shared between different machines (as long as both machines use the same
"toolchains" [more technically, as long as the vcpkg hash is the same])

**Describe the pull request**

- What does your PR fix? Fixes #14544

- Which triplets are supported/not supported? Have you updated the CI baseline? No changes related to triplets support or to CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

2020-11-13 02:29 UTC, PhoebeHui requested changes
@klalumiere, thanks for the PR!

Could you also update the Port-Version from 0 to 1 in CONTROL file?

2020-11-13 02:34 UTC, klalumiere commented
> @klalumiere, thanks for the PR!
> 
> Could you also update the Port-Version from 0 to 1 in CONTROL file?

I always forget about this :flushed: :laughing:. Done :heavy_check_mark:.

2020-11-13 05:57 UTC, PhoebeHui commented
All features test passed with x64-windows.

2020-11-13 05:57 UTC, PhoebeHui approved these changes

2020-11-16 18:26 UTC, merged

2020-11-16 18:26 UTC, strega-nil commented
Thanks @klalumiere 👍