[x265] Add HDR and high bit depth option for x265
microsoft/vcpkg pull request #14572
Opened 2020-11-15 00:48 UTC by ThisIsAreku

**Describe the pull request**

- What does your PR fix?

Fixes #13875

- Which triplets are supported/not supported? Have you updated the CI baseline?

No changes in support.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-11-16 06:25 UTC, JackBoosY requested changes

2020-11-16 06:25 UTC, JackBoosY commented on ports/x265/portfile.cmake
> +endif()
We need to consider the coexistence of these two features.

2020-11-16 06:25 UTC, JackBoosY commented on ports/x265/CONTROL
>  Version: 3.4
```suggestion
Version: 3.4
Port-Version: 1
```

2020-12-16 03:17 UTC, JackBoosY commented
Pinging @ThisIsAreku  for response. Is work still being done for this PR?

2020-12-22 13:53 UTC, ThisIsAreku commented on ports/x265/portfile.cmake
> +endif()
Actually `main10` and `main12` cannot coexist. When building for high bit depth the default is `main10`. I've removed the `main10` feature.

2020-12-22 13:56 UTC, ThisIsAreku commented
@JackBoosY a new commit has been pushed. I'm waiting for the tests to complete

2020-12-23 02:31 UTC, JackBoosY requested changes

2020-12-23 02:31 UTC, JackBoosY commented on ports/x265/CONTROL
> +
```suggestion
```

2020-12-23 02:31 UTC, JackBoosY approved these changes

2020-12-30 06:59 UTC, JackBoosY commented
Needs test features.

2020-12-30 07:06 UTC, JackBoosY commented
When building `x265[hbd,main12,hdr10plus]`:
```
G:\14572\vcpkg\buildtrees\x265\src\f1b45711b7-44018d5a0c.clean\source\common\x86\ssd-a.asm:827: error: invalid combination of opcode and operands
```

2021-02-04 06:04 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2021-02-04 06:04 UTC, closed without merging