[Mapnik]
microsoft/vcpkg pull request #14628
Opened 2020-11-18 10:49 UTC by mathisloge

**Describe the pull request**
adds mapnik without forking the mapnik repository. However, this PR needs the current master.

Adds the mapbox-geometry and mapbox-polyline ports. Mapnik is dependend on specific commits, therefore the REF *commit*. 
I'll test with current releases after I've validated mapnik.

- What does your PR fix? 
Fixes #7526
Forked from #11656 

- Which triplets are supported/not supported? Have you updated the CI baseline?
needs CI test

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes

2020-11-18 11:28 UTC, mathisloge commented
osx fails due to boost-regex build...

2020-11-18 12:23 UTC, mathisloge commented
added issue https://github.com/mapnik/mapnik/issues/4187 to fix the applied patches csv and geojson

2020-11-18 14:11 UTC, mathisloge commented
Have tested with the viewer example. Ready for review

2020-11-18 18:10 UTC, mathisloge commented
so, now it is ready to review. I've compiled a test program to validate that everything compiles 

but i still need to fix the static version. somehow the defines got messed up and still i prefixes classes with dllimport.. 
Can someone help me with that?

2020-11-18 19:10 UTC, mathisloge commented
Might be good to switch to scons with vcpkg_find_acquire_program/vcpkg_execute_required_process

2020-11-19 10:16 UTC, NancyLi1013 requested changes

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/vcpkg.json
> +    "mapbox-variant",
```suggestion
```
Seems duplicated.

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapbox-geometry/portfile.cmake
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapbox-geometry/portfile.cmake
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapbox-polylabel/portfile.cmake
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapbox-polylabel/portfile.cmake
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +#set(MAPNIK_SOURCES ${MAPNIK_SOURCES} src/rapidxml_loader.cpp)
```suggestion
```
If this line is not needed, please remove it here.

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/demo/viewer/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/demo/viewer/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/plugins/input/geobuf/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/cmake/utils/mapnik-render/CMakeLists.txt
> +
```suggestion
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +vcpkg_fail_port_install(ON_TARGET Windows ON_LIBRARY_LINKAGE "static")
```suggestion
vcpkg_fail_port_install(ON_TARGET "Windows")

vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +      fix-constructor-inheritance.patch
```suggestion
    PATCHES
        fix-box2d.patch
        fix-constructor-inheritance.patch
```

2020-11-19 10:16 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
```suggestion
```

2020-11-19 10:52 UTC, mathisloge commented
mhm linux fails due to qt5-location error. but mapnik was build successfully.

2020-11-20 07:40 UTC, NancyLi1013 commented
/azp run

2020-11-20 07:46 UTC, NancyLi1013 commented
@mathisloge 

Would you like to add these CMakeLists.txt for `mapnik `to upstream? I noticed that there are several files in this PR.

2020-11-20 09:25 UTC, mathisloge commented
@NancyLi1013 to upstream vcpkg master yes.
Normally mapnik uses scons as a build system but I don't get it to work with vcpkg since all the dependencies would not be correctly noticed by the build system.
I've set the include dirs manually .

Because of that I would like to use cmake as the build system. (URL of scons port https://github.com/mathisloge/vcpkg/tree/mapnik_scons)note: it is quite messed up because I've tried a few different things

2020-11-20 10:04 UTC, NancyLi1013 commented
> @NancyLi1013 to upstream vcpkg master yes.

I mean upstream is https://github.com/mapnik/mapnik.

2020-11-20 10:40 UTC, mathisloge commented
@NancyLi1013 i don't think that they want to change their build system. But I will ask them.

2020-11-20 17:05 UTC, mathisloge commented
@NancyLi1013 Well, I guess I was wrong. :D 
I will create a PR in mapnik to add CMake support. I will convert this PR into a draft.

2020-11-20 20:18 UTC, mathisloge commented
PR located at https://github.com/mapnik/mapnik/pull/4191

2020-12-04 09:00 UTC, NancyLi1013 commented
/azp run

2020-12-16 09:26 UTC, mathisloge commented
@NancyLi1013 could you restart the azp? windows static has shutdown before the build has started.

2020-12-16 10:28 UTC, NancyLi1013 commented
/azp run

2020-12-16 23:09 UTC, mathisloge commented
super - success.  :)

2020-12-17 01:53 UTC, NancyLi1013 requested changes

2020-12-17 01:53 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +    REF 410393fefabf2c9d25f6ed3f823868139cbd7467
It seems that you use the commit of your PR https://github.com/mapnik/mapnik/pull/4191 as `REF `here. Since this PR hasn't been accepted by the upstream. The current REF is not suitable.

2020-12-17 01:53 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +
Have you tested these features?

2020-12-17 01:53 UTC, NancyLi1013 commented on ports/mapnik/portfile.cmake
> +  #file(COPY ${SOURCE_PATH}/fonts DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT})
```suggestion
```

2020-12-17 02:06 UTC, NancyLi1013 commented
@mathisloge 

Thanks for all your efforts to this PR. 
In my opinion, it would be better to wait for the PR https://github.com/mapnik/mapnik/pull/4191 merged to upstream. Then we can update the changes to this PR. We can ask for help form upstream and let them merge the cmake support as soon as possible if they agree to the changes.

For the features, I noticed that you added many features for `mapnik` (29 features) in this PR. Are all these features required? If  adding these features, we must make sure all features work fine. And every update to a new version, we also need to test them.

2020-12-17 08:44 UTC, mathisloge commented
@NancyLi1013 

thanks for your feedback. I agree that waiting for the merge is the best option. 

With the features you can enable the required core features of Mapnik and some tools. I don't know if some people have requirements not to activate certain features. I would like to leave them. But we could make a default configuration that enables the most common features. 
Can we test the features in the ci? I tested the whole build locally, but couldn't test it on macOS. 
(Tested with a separate project and the build in the demo viewer. The demo viewer can use most of the features).

2020-12-17 08:46 UTC, mathisloge commented on ports/mapnik/portfile.cmake
> +
had make a whole build locally and build a seperate project

2020-12-17 08:47 UTC, mathisloge commented on ports/mapnik/portfile.cmake
> +    REF 410393fefabf2c9d25f6ed3f823868139cbd7467
Yep, thats right. as discussed we need to wait for merge. I will then change the REF and REPO

2020-12-17 08:50 UTC, mathisloge commented on ports/mapnik/portfile.cmake
> +
for the upstream changes, I need to get the tests running. At the moment they are only running with some manual modifications. But after I make those modifications, the build-in tests will run. (some need changes due to windows, but that's a story for mapnik itself. mostly file paths created with only linux in mind).

2020-12-23 09:17 UTC, NancyLi1013 commented
@mathisloge 

Sorry for the delay.

For the features, it's unnecessary to test them on osx. Since currently features are not supported on osx.

2021-01-27 08:19 UTC, mathisloge commented
ci has failed due to osgearth. mapnik itself succeeded

2021-01-27 08:36 UTC, NancyLi1013 commented
The regression caused by `osgearth ` will be fixed by this PR #15900.

The failures on x64-osx caused by `mapnik`:

```
Undefined symbols for architecture x86_64:
  "_icudt67_dat", referenced from:
      openCommonData(char const*, int, UErrorCode*) in libicuuc.a(udata.ao)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

2021-01-27 10:09 UTC, mathisloge commented
@NancyLi1013 osx error looks like some missing linkage in icu itself. 
https://github.com/denoland/deno/issues/1968#issuecomment-633363257

The previous builds were successful and the new commits doesnt changed the code of mapnik and the logic of the build. 
So i guess this error had come into icu with the rebase 0e20d61

2021-01-28 03:00 UTC, NancyLi1013 commented
Thanks for looking into this error @mathisloge

I will rerun to check the new result.

2021-02-03 18:47 UTC, mathisloge commented
@NancyLi1013 sorry for the inconvenience. That was a mistake on my part. I forgot to add the component icu::data. Strange that it didn't was detected before.

2021-02-08 07:26 UTC, NancyLi1013 commented
Hi @mathisloge 

Is this PR ready for review now?

2021-02-08 08:57 UTC, mathisloge commented
Hi @NancyLi1013 

don't think so. The PR at upstream mapnik is still pending while we squeeze out the last remaining build details

2021-03-19 20:16 UTC, ras0219-msft commented
/azp run

2021-04-02 01:54 UTC, NancyLi1013 commented
@mathisloge 

Could you please resolve the conflicts?

2021-04-23 05:46 UTC, NancyLi1013 commented
Please ping me if this PR is ready for review @mathisloge.

2021-04-24 08:03 UTC, mathisloge commented
Hi @NancyLi1013 

so it isn't merged into upstream yet. 
However I'm also waiting for some responses to https://github.com/microsoft/vcpkg/issues/16906 since `find_package(PROJ ...)` is not working with vcpkg. I think i will need to add a patch to this port to fix the vcpkg related issue.

2021-07-06 21:38 UTC, mathisloge commented
@NancyLi1013 i think i have screwed this PR up. Don't know what has happend here to the git history. :D 

Should i open a new fresh PR?

2021-07-07 08:57 UTC, closed without merging

2021-07-07 08:57 UTC, mathisloge commented
closed in favor of https://github.com/microsoft/vcpkg/pull/18849

2021-07-08 06:45 UTC, NancyLi1013 commented
Thanks for your information. Seems your branch is based on upstream master. These changes should be in vcpkg master branch.