[mesa] new port
microsoft/vcpkg pull request #14640
Opened 2020-11-18 23:06 UTC by Neumann-A

closes #6705 

should currently only work for windows.

2020-11-20 06:22 UTC, PhoebeHui commented
CI test failures:

..\src\189b5861b5-bd40f385ca.clean\meson.build:1492:2: ERROR: Neither a subproject directory nor a llvm.wrap file was found.

Full logs:
[failure logs for x86-windows.zip](https://github.com/microsoft/vcpkg/files/5571617/failure.logs.for.x86-windows.zip)

2020-11-23 09:35 UTC, PhoebeHui commented
/azp run

2020-11-27 05:44 UTC, PhoebeHui commented
@Neumann-A, here is failure for libass:x64-linux in CI testing:
```
/mnt/vcpkg-ci/buildtrees/libass/src/ebd911d5ca-39016ec3fc.clean/libass/ass_fontconfig.c:26:10: fatal error: fontconfig/fontconfig.h: No such file or directory
 #include <fontconfig/fontconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
```
[failure logs for x64-linux (9).zip](https://github.com/microsoft/vcpkg/files/5606138/failure.logs.for.x64-linux.9.zip)

2020-11-27 08:41 UTC, Neumann-A commented
@PhoebeHui that seems to be unrelated to this PR since the depend-info for libass does not list fontconfig!

```
$ ./vcpkg.exe depend-info libass
zlib:
brotli:
bzip2:
libpng: zlib
freetype[bzip2, png]: brotli, bzip2, libpng, zlib
ragel:
tool-meson:
dirent:
fribidi: tool-meson
harfbuzz: freetype, ragel
libass: dirent, freetype, fribidi, harfbuzz
```

looking at the `CMakeLists.txt` it vendored by vcpkg it is definitely missing a `find_package(Fontconfig)` and a `Build-Depends` on it.

Since it is completly unrelated I am not going to fix it in this PR.

2020-11-27 09:37 UTC, PhoebeHui commented
@Neumann-A, please ignore it, it's not related to this changes, it also failed in master, I will take a look the baseline issue.

2020-11-27 09:38 UTC, PhoebeHui commented
I will test all features with x64-window if you haven't test yet.

2020-11-27 10:18 UTC, Neumann-A commented
@PhoebeHui. I did not test everything. One interesting point will be if `llvm[core]` is really enough or if `llvm[core,target-x64]` is required. I couldn't really deduce that from mesa's find_dep call.

2020-12-01 02:23 UTC, PhoebeHui commented
Feature 'egl' test failed with x64-windows, others passed.

```
..\src\189b5861b5-bd40f385ca.clean\meson.build:412:4: ERROR: Problem encountered: EGL requires dri
```
[meson-log.txt](https://github.com/microsoft/vcpkg/files/5619885/meson-log.txt)

2020-12-01 09:02 UTC, Neumann-A commented
That feature probably only works for unix due to:
```
  elif ['darwin', 'windows'].contains(host_machine.system())
    error('EGL is not available on Windows or MacOS')
```

2020-12-01 10:34 UTC, PhoebeHui commented
Could you add comments to portfile.cmake or description in CONTROL file about the failed feature 'egl'?

2020-12-02 09:00 UTC, PhoebeHui approved these changes

2020-12-02 21:20 UTC, strega-nil requested changes
This is what I see, anyways.

2020-12-02 21:20 UTC, strega-nil commented on ports/mesa/CONTROL
> +
Seems like this feature should be programmatically decided upon, rather than being a feature...

2020-12-02 21:20 UTC, strega-nil commented on ports/mesa/portfile.cmake
> +endif()
```suggestion
foreach(feature IN LISTS FEATURES)
    if(feature IN_LIST "opengl;gles1;gles2")
        list(APPEND GL_FEATURES "${feature}")
    endif()
    list(LENGTH GL_FEATURES NUMBER_GL_FEATURES)
endforeach()

if(NUMBER_GL_FEATURES GREATER 1)
    list(APPEND MESA_OPTIONS -Dshared-glapi=enabled)
else()
    list(APPEND MESA_OPTIONS -Dshared-glapi=disabled)
endif()
```

something like this?

2020-12-17 18:11 UTC, Neumann-A commented on ports/mesa/CONTROL
> +
I would say if users would like to use only one API they are free to decide if they want to be shared or not and in this case it is a feature. The port currently always builds atleast the basic opengl api and the other apis are built on top of it.

2020-12-17 18:16 UTC, strega-nil commented on ports/mesa/CONTROL
> +
Hmm, so basically, `shared-glapi` introduces new APIs, and it's required to have it when more than one GL API is selected, but it's also allowed when only one is selected?

Why not just make it always on?

2020-12-17 20:16 UTC, Neumann-A commented on ports/mesa/CONTROL
> +
> Why not just make it always on?

because the build offers that option? On windows it probably makes sense to build it always as a shared library. On linux? don't ask me. Ask upstream when/why to use a static gl library.

2021-01-07 11:53 UTC, Neumann-A commented on ports/mesa/portfile.cmake
> +endif()
I kept sharedgl-api as a feature but made it fatally error if more than one api is selected and it is disabled.

2021-01-07 18:03 UTC, strega-nil commented
Adding `requires:discussion` to talk about at the mtg today.

2021-01-07 18:03 UTC, strega-nil approved these changes

2021-01-07 22:10 UTC, BillyONeal commented on ports/mesa/CONTROL
> +Description: Build support for OpenGL (all versions)
```suggestion
Description: Build support for OpenGL (all non-ES versions)

```

2021-01-07 22:11 UTC, strega-nil commented
@Neumann-A is there a reason that we don't just always build `shared-glapi`?

2021-01-07 22:16 UTC, Neumann-A commented on ports/mesa/CONTROL
> +Description: Build support for OpenGL (all versions)
The description is from meson_options.txt stating:
```
option(
  'opengl',
  type : 'boolean',
  value : true,
  description : 'Build support for OpenGL (all versions)'
)
```
I think features in vcpkg should copy upstream descriptions 1:1 even if it seems to be a wrong.

2021-01-07 22:29 UTC, Neumann-A commented
> is there a reason that we don't just always build shared-glapi?

The only discussion I found is in https://www.mail-archive.com/mesa-dev@lists.freedesktop.org/msg17040.html and there seem to be at least one use case which does not use a `shared-glapi`

2021-01-07 22:33 UTC, strega-nil commented
@Neumann-A hmm, it looks to me like unshared-glapi is pretty not-useful, except for _maybe_ some minor cases to do with system package managers. I think the best thing to do is just make shared-glapi always-on, and if a person really needs unshared-glapi, they can work on it themselves.

2021-01-07 22:43 UTC, strega-nil approved these changes

2021-01-08 01:11 UTC, ras0219-msft requested changes

2021-01-08 01:11 UTC, ras0219-msft commented on ports/mesa/portfile.cmake
> +        file(CREATE_LINK "${FLEX}" "${FLEX_DIR}/flex${VCPKG_HOST_EXECUTABLE_SUFFIX}")
This link should be created in a port-local location instead of mutating the tool's install. E.g:
```suggestion
        file(CREATE_LINK "${FLEX}" "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}/flex${VCPKG_HOST_EXECUTABLE_SUFFIX}")
```

2021-01-08 01:11 UTC, ras0219-msft commented on ports/mesa/portfile.cmake
> +vcpkg_fixup_pkgconfig(SYSTEM_LIBRARIES pthread)
```suggestion
vcpkg_fixup_pkgconfig()

```

2021-01-08 01:11 UTC, ras0219-msft commented on ports/mesa/portfile.cmake
> +#installed by opengl-registry
Should this port depend on opengl-registry then?

2021-01-08 01:11 UTC, ras0219-msft commented on ports/mesa/portfile.cmake
> +endforeach()
```suggestion
list(TRANSFORM _double_files PREPEND "${CURRENT_PACKAGES_DIR}/")
file(REMOVE ${_double_files})
```

2021-01-08 01:11 UTC, ras0219-msft commented on ports/mesa/portfile.cmake
> +    include/GLES3/gl3.h  include/GLES3/gl31.h include/GLES3/gl32.h include/GLES3/gl3platform.h)
```suggestion
set(_double_files include/GL/glcorearb.h include/GL/glext.h include/GL/glxext.h
    include/GLES3/gl3.h  include/GLES3/gl31.h include/GLES3/gl32.h include/GLES3/gl3platform.h)
```
Below is already removing the `GLES` and `GLES2` dirs.

2021-01-08 10:21 UTC, Neumann-A commented on ports/mesa/portfile.cmake
> +        file(CREATE_LINK "${FLEX}" "${FLEX_DIR}/flex${VCPKG_HOST_EXECUTABLE_SUFFIX}")
On Windows there is a very high probability that flex/bison are owned by vcpkg anyway.  I'll add a check if it is seated in `DOWNLOADS`

2021-01-11 03:05 UTC, PhoebeHui commented
The x64-windows-static failed with 'only supports dynamic crt linkage", @Neumann-A, could you add mesa:x64-windows-static to ci.baseline file for unblocking CI testing?

```
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:51 (message):
  mesa only supports dynamic crt linkage
Call Stack (most recent call first):
  ports/mesa/portfile.cmake:10 (vcpkg_check_linkage)
  scripts/ports.cmake:136 (include)
```

2021-01-11 08:09 UTC, Neumann-A commented on ports/mesa/portfile.cmake
> +#installed by opengl-registry
this would only generate an hard error on the installation of mesa if it tries to install headers which are already present, The build itself will not use either egl-registry nor opengl-registry.

2021-01-11 08:12 UTC, Neumann-A commented on ports/mesa/portfile.cmake
> +function(vcpkg_get_python_package PYTHON_DIR )
@ras0219-msft As requested I factored out a function called `vcpkg_get_python_package` here but I did not put it into `scripts/cmake` yet since I did not want to rebuild all ports within this PR.

2021-01-11 09:50 UTC, Neumann-A commented on ports/mesa/portfile.cmake
> +endif()
it is the default now.

2021-01-12 00:11 UTC, vicroms approved these changes

2021-01-12 00:12 UTC, merged