[clamav] Add new port
microsoft/vcpkg pull request #14658
Opened 2020-11-19 20:27 UTC by zaddach

Adds port for ClamAV

- Tested on x64_windows

2020-11-20 06:42 UTC, NancyLi1013 requested changes

2020-11-20 06:42 UTC, NancyLi1013 commented on ports/clamav/portfile.cmake
> +endif()
Can these parts be handled by CMake in CMakeLists.txt or cmake files? Seems to be related with the path.

2020-11-20 08:18 UTC, zaddach commented on ports/clamav/CONTROL
> +Port-Version: 1
I've removed that.

2020-11-20 08:18 UTC, zaddach commented on ports/clamav/portfile.cmake
> +vcpkg_from_github(
Added the message.

2020-11-20 08:19 UTC, zaddach commented on ports/clamav/portfile.cmake
> +
Removed the newline.

2020-11-20 08:22 UTC, zaddach commented on ports/clamav/portfile.cmake
> +endif()
The CMakeLists.txt that build the package is from the package itself, so I can't modify it easily (And I'm not sure if ClamAV wants to change the install paths to what vcpkg expects). I had taken inspiration from the [antlr4 portfile](https://github.com/microsoft/vcpkg/blob/e803bf11296d8e7900dafb41e7b1224778d33dc6/ports/antlr4/portfile.cmake#L42) which handles things the same way.

2020-11-20 08:23 UTC, zaddach commented
Thanks for the review! I've pushed an update.

2020-11-20 20:42 UTC, micahsnyder commented on ports/clamav/portfile.cmake
> +endif()
I did see that CMake on Windows installs executables and libraries to the bin sub-directory, which explains why so many Windows ports of linux applications have a bin directory (i.e. `Program Files\<application>\bin`).  I'm really not a fan of this, as it's not idiomatic for Windows applications.
 
ClamAV's CMakeLists.txts intentionally installs everything to the prefix directory for Windows (no bin or lib).  Eg: https://github.com/Cisco-Talos/clamav-devel/blob/dev/0.104/libclamav/CMakeLists.txt#L612

For vcpkg if you need everything under `bin` you'll need the `RENAME`'s.

2020-11-20 20:47 UTC, micahsnyder commented on ports/clamav/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc.exe")
If you only want the libs, the ClamAV CMake build tooling provides an `ENABLE_APP` option that you can set to `OFF`.  See: https://github.com/Cisco-Talos/clamav-devel/blob/dev/0.104/CMakeOptions.cmake#L68 and https://github.com/Cisco-Talos/clamav-devel/blob/dev/0.104/INSTALL.cmake.md#custom-cmake-options for additional details.

2020-11-20 20:52 UTC, micahsnyder commented on ports/clamav/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc.exe")
I'm not entirely familiar with how vcpkg ports work -- if you want to provide static libs as well as the DLLs, there is also an `ENABLE_STATIC_LIB` option you can enable.  It should work in 0.103, though we are making some improvements to the no-shared+yes-static combination in the next release.

2020-11-23 09:09 UTC, NancyLi1013 commented on ports/clamav/portfile.cmake
> +endif()
I know the current status is from `clamav` itself.  But you can make a patch to update the directory. Seems most libraries will install the targets to `bin `or `lib `directoty, which is also we expected.

2020-11-23 17:37 UTC, zaddach commented on ports/clamav/portfile.cmake
> +endif()
Added a patch which makes ClamAV install the files into the correct directories.

2020-11-23 17:39 UTC, zaddach commented on ports/clamav/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc.exe")
I've added `ENABLE_APP=OFF` to the build, which disables all the binaries. Additionally, I'm now setting the `ENABLE_STATIC_LIB` and `ENABLE_SHARED_LIB` correctly (though there's little use of building ClamAV with anything but dlls, as pdcurses doesn't support static building)

2020-11-23 19:46 UTC, micahsnyder commented on ports/clamav/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc.exe")
pdcurses is only required for the `clamdtop` app dependency, so if you've disabled apps -- you need not worry about pdcurses.

2020-11-27 13:42 UTC, zaddach commented on ports/clamav/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc.exe")
Ok, I've stripped everything down to really only build `libclamav` (`ENABLE_LIBCLAMAV_ONLY`), and only require the dependencies for that.

2020-11-27 18:26 UTC, zaddach commented
I've fixed the windows static build as well as the Linux/OsX build.

2020-12-01 06:29 UTC, JackBoosY requested changes

2020-12-01 06:29 UTC, JackBoosY commented on ports/clamav/curl.patch
> ++endif()
I found `CURL::libcurl` has been linked above, can you confirm this?

2020-12-01 06:29 UTC, JackBoosY commented on ports/clamav/static_iconv.patch
> ++        target_link_libraries( clamav_static PUBLIC Iconv::Iconv )
Is the source broken here?

2020-12-01 06:29 UTC, JackBoosY commented on ports/clamav/cmakefiles.patch
> ++    install(TARGETS clamunrar_iface)
Should give it a destination.

2020-12-01 06:30 UTC, JackBoosY requested changes

2020-12-01 06:30 UTC, JackBoosY commented on ports/clamav/cmakefiles.patch
> ++install(TARGETS clamunrar)
Same as below.

2020-12-01 06:30 UTC, JackBoosY commented on ports/clamav/cmakefiles.patch
> ++install(TARGETS mspack)
Same as below.

2020-12-01 06:30 UTC, JackBoosY commented on ports/clamav/cmakefiles.patch
> ++    install(TARGETS clamav_static)
Same as below.

2020-12-01 06:30 UTC, JackBoosY commented on ports/clamav/cmakefiles.patch
> ++    install(TARGETS clamav)
Same as below.

2020-12-01 11:58 UTC, zaddach commented on ports/clamav/cmakefiles.patch
> ++    install(TARGETS clamunrar_iface)
Why is the default destination not good? By default cmake will install into `${CMAKE_INSTALL_PREFIX}/{bin,lib}`, which is exactly the behavior vcpkg expects. If I specify a relative path, I need to split this for dlls into the `bin` (for the dll) and the `lib` (for the lib) directories. If I specify an absolute path, I need to make sure this path respects `CMAKE_INSTALL_PREFIX`. Thus everything expect the default destination seems a lot of work for no visible gain to me.

2020-12-01 12:01 UTC, zaddach commented on ports/clamav/static_iconv.patch
> ++        target_link_libraries( clamav_static PUBLIC Iconv::Iconv )
Yes. It will be fixed in 0.104.

2020-12-01 18:45 UTC, zaddach commented on ports/clamav/curl.patch
> ++endif()
Yes, this actually slipped my attention. I had fixed it in the ClamAV repo, but didn't update the patch. Fixed.

2020-12-02 03:07 UTC, NancyLi1013 requested changes

2020-12-02 03:14 UTC, NancyLi1013 requested changes

2020-12-02 03:14 UTC, NancyLi1013 commented on ports/clamav/cmakefiles.patch
> ++    install(TARGETS clamunrar_iface)
Thanks for your clarification about this point. It looks good currently. So you don't need to update it again.

2020-12-03 16:38 UTC, zaddach commented on ports/clamav/cmakefiles.patch
> ++install(TARGETS clamav RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
That was a copy-paste mistake. Fixed it, and aligned installation for `freshclam` and `freshclam_static` targets with the other install directives.

2020-12-04 02:22 UTC, NancyLi1013 approved these changes

2020-12-04 02:38 UTC, JackBoosY approved these changes

2020-12-04 23:32 UTC, BillyONeal commented on ports/clamav/static_unrar.patch
> ++if(NOT ENABLE_SHARED_LIB AND ENABLE_UNRAR)
It seems like this should be in the triplet and result in a hard error rather than being patched in, what do you think? (That way features don't silently have no effect)

2020-12-04 23:32 UTC, BillyONeal commented on ports/clamav/static_libclammspack.patch
> ++endif()
```suggestion
+add_library( mspack )

```

I think the default `BUILD_SHARED_LIBS` setting does the right thing here? (Is `ENABLE_SHARED_LIB` duplicating what [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) does or something else? If something else feel free to reply to and ignore this comment)

2020-12-04 23:32 UTC, BillyONeal commented on ports/clamav/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ENABLE_STATIC)
Should we error here if neither of these match?

2020-12-14 16:01 UTC, zaddach commented on ports/clamav/static_unrar.patch
> ++if(NOT ENABLE_SHARED_LIB AND ENABLE_UNRAR)
In general, a static build a ClamAV doesn't make much sense. Unrar only works in a dynamic build, and mspack (without patching) only builds for a dynamic build. mspack is a hard dependency. Probably I should make my life easier and just accept dynamic builds.

2020-12-14 16:10 UTC, zaddach commented on ports/clamav/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ENABLE_STATIC)
Same as above. Probably would be a good idea to only allow dynamic builds and error in all other cases:
```
+ vcpkg_fail_port_install(MESSAGE "A static build for ${PORT} doesn't make much sense, as the mspack and unrar dependencies don't support a static build" ON_LIBRARY_LINKAGE "static")
+ set(ENABLE_SHARED )
```
What do you think?

2020-12-14 17:05 UTC, BillyONeal commented on ports/clamav/static_unrar.patch
> ++if(NOT ENABLE_SHARED_LIB AND ENABLE_UNRAR)
If only dynamic makes sense, you can set `Supports: !static` and use `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` in `portfile.cmake`. For example: https://github.com/microsoft/vcpkg/blob/81b67c387848731aefacc19aea7f41364e5d5ba2/ports/atkmm/portfile.cmake#L3

2020-12-14 17:06 UTC, BillyONeal commented on ports/clamav/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ENABLE_STATIC)
See `vcpkg_check_linkage` comment above.

2021-02-08 07:29 UTC, NancyLi1013 commented
@zaddach 

Could you please address the review suggestion? Thanks.

2021-02-09 17:48 UTC, zaddach commented on ports/clamav/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ENABLE_STATIC)
Sorry, I missed that comment. I've used `vcpkg_check_linkage` as you recommended and removed everything related to the static build.

2021-02-19 16:05 UTC, zaddach commented
Hey, I can't reproduce the build failure in the `x86_windows` pipeline. Is this just a pipeline hiccup, or a real problem?

2021-02-20 03:04 UTC, JackBoosY commented
@zaddach Note for changes, we should use `./vcpkg x-add-version --all` to generate port version info and commit the changes.

2021-02-20 07:24 UTC, zaddach commented
Thank you for your help!

2021-03-29 17:14 UTC, merged