[qt5] Update to 5.15.2
microsoft/vcpkg pull request #14678
Opened 2020-11-20 20:18 UTC by Neumann-A

TODO: qt5-mqtt, test qt5-webengine
(mqtt currently missing git tag)
closes #14675

2020-11-20 20:26 UTC, Neumann-A commented on ports/qt5-imageformats/CONTROL
> +Port-Version: 1
```suggestion
Port-Version: 0
```

2020-11-20 22:16 UTC, bl-ue commented on ports/qt5-base/cmake/qt_port_hashes.cmake
>  #set(QT_HASH_qt5-canvas3d            0) deprectaed
```suggestion
#set(QT_HASH_qt5-canvas3d            0) deprecated

```

2020-11-20 22:17 UTC, bl-ue commented on ports/qt5-base/cmake/qt_port_hashes_latest.cmake
>  #set(QT_HASH_qt5-canvas3d            0) deprectaed
```suggestion
#set(QT_HASH_qt5-canvas3d            0) deprecated

```

2020-11-23 08:05 UTC, Neumann-A commented
@JackBoosY @strega-nil could somebody investigate the problems `vcpkg_from_git` has with the official git of qt https://code.qt.io/cgit/qt/qtmqtt.git. qt5-mqtt is currently using a github mirror which hasn't yet updated to 5.15.2 so this PR will be blocked until then or the problem with `vcpkg_from_git` and the official git are resolved

2020-11-24 01:38 UTC, JackBoosY commented
@Neumann-A Seems 5.15.2 doesn't published on the github.
See https://github.com/qt/qtmqtt/tags

2020-11-24 09:07 UTC, Neumann-A commented
@JackBoosY:

> So as you said, we need to wait for the upstream publish that version.

we only need to wait if we use the github mirror. If we could use the official git at https://code.qt.io/cgit/qt/qtmqtt.git we wouldn't need to wait since it has the tag. The problem is that I wasn't able to get `vcpkg_from_git` to work with the official git repro. (Should probably be considered a vcpkg bug. I already ran into a few issues with `vcpkg_from_git` where it wasn't able to download from a git repro)

2020-11-24 09:09 UTC, JackBoosY commented
@Neumann-A  Maybe some parameters caused that. You can print the clone command and try it manually on you machine.

2020-11-24 09:15 UTC, Neumann-A commented
@JackBoosY. I already tried to make it work (e.g. by making --depth 1 and everything optional) but without success (I didn't try very long). `vcpkg_from_git` is doing a bit more than a simple `git clone`

2020-11-24 10:26 UTC, Neumann-A commented
@JackBoosY Also needs to have tag `depends_vm_update`

2020-12-01 09:27 UTC, dweckmann requested changes

2020-12-01 09:27 UTC, dweckmann commented on ports/qt5-base/cmake/qt_port_hashes_latest.cmake
> -set(QT_HASH_qt5-base                40b687c046b25a6717834ffe2616ee4f373d75214ec1c7e3a26502cd0cde9f0a872eaee99f06c54c7a3625ae85df5cdd3a3b54a160e8e37c7cfeb5800d026fe4)
Suggested change :): 

4: set(QT_PATCH_VER 1) -> set(QT_PATCH_VER 2)

2021-01-07 12:43 UTC, Neumann-A commented
@JackBoosY: remove depends-upstream changes. Changed it to depend on the other PR #15049

2021-01-07 12:44 UTC, Neumann-A commented on ports/qt5-webengine/portfile.cmake
> +            build_3.patch)
Could be replaced with the upstream patches if somebody cares and give me a link to the correct patchset.

2021-01-07 21:31 UTC, BillyONeal commented on ports/qt5-webengine/portfile.cmake
> +            build_3.patch)
Speaking as the person who usually beats the "should be upstream thing" drum very hard given that future Qt will be qt6 and thus there are relatively little worries about these being "brittle" for the purposes of this port, I think these are OK as is.

2021-01-11 14:45 UTC, vicroms commented
/azp run

2021-01-11 18:37 UTC, ras0219 approved these changes

2021-01-11 18:37 UTC, ras0219 commented on ports/qt5-location/CONTROL
> +Port-Version: 0
```suggestion
```

2021-01-11 18:37 UTC, ras0219 commented on ports/qt5-location/rename_third_party_libs_conflicts.patch
> -diff --git a/src/3rdparty/clip2tri/clip2tri.pro b/src/3rdparty/clip2tri/clip2tri.pro
Just checking -- this was incorporated upstream?

2021-01-11 18:42 UTC, Neumann-A commented on ports/qt5-location/rename_third_party_libs_conflicts.patch
> -diff --git a/src/3rdparty/clip2tri/clip2tri.pro b/src/3rdparty/clip2tri/clip2tri.pro
yes. You already used the upstream patch here. 
alternativly you can check:
https://github.com/qt/qtlocation/blob/5.15.2/src/3rdparty/clip2tri/clip2tri.pro
https://github.com/qt/qtlocation/blob/5.15.2/src/3rdparty/clipper/clipper.pro
https://github.com/qt/qtlocation/blob/5.15.2/src/3rdparty/poly2tri/poly2tri.pro

2021-01-11 21:23 UTC, BillyONeal commented
The mac build failed due to a transient infrastructure issue ( https://github.com/microsoft/vcpkg/pull/15584 ). `/azp run` after the other entries come back green should fix it.

2021-01-12 01:26 UTC, BillyONeal commented
/azp run

2021-01-18 02:20 UTC, JackBoosY commented
Can you please resolve the conflicts?

2021-01-19 11:59 UTC, Neumann-A commented
@JackBoosY You probably want to remove `depends:different-pr`

2021-01-20 02:54 UTC, JackBoosY approved these changes

2021-01-20 02:55 UTC, JackBoosY commented
Let's merge this PR.

2021-01-20 20:55 UTC, merged

2021-01-20 20:56 UTC, dan-shaw commented
Thanks everyone!