[nccl] New Port
microsoft/vcpkg pull request #14683
Opened 2020-11-20 22:19 UTC by jacobkahn

Adds a port for NCCL, NVIDIA's collective multi-GPU communication library.

This port almost exactly mirrors the [cuDNN port](https://github.com/microsoft/vcpkg/tree/master/ports/cudnn):
- Checks if NCCL is available on the system. This is because the installation is somewhat specialized and new versions have improved performance but can still be compiled with CUDA 10.1 (what the [CUDA port](https://github.com/microsoft/vcpkg/tree/master/ports/cuda) is frozen at). The NCCL version minimum is `2.4.6`, so if a later version is found, that satisfies the install requirement.
- Downloads `cuDNN` from Anaconda if not. Downloads a version consistent with CUDA 10.1.
- If there's a better way to call `find_package` inside the portfile to simulate finding the package, let me know/feel free to commit.

- Which triplets are supported/not supported? Have you updated the CI baseline?

`linux` only, which is what NCCL supports. I've tested in `x64` linux linking and building with other packages.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-11-23 05:48 UTC, JackBoosY requested changes

2020-11-23 05:48 UTC, JackBoosY commented on ports/nccl/portfile.cmake
> +endif()
```suggestion
vcpkg_fail_port_install(ON_TARGET "Windows" "OSX" ON_ARCH "x86" "arm")
```

2020-11-23 05:48 UTC, JackBoosY commented
Will test the usage locally.

2020-11-23 06:21 UTC, JackBoosY requested changes
Since you provided the cmake wrapper, you should also provide a usage.

2020-11-23 16:35 UTC, jacobkahn commented
@JackBoosY added some usage in the wrapper. Is that what you meant?

2020-11-23 23:45 UTC, jacobkahn commented
I can also create an imported target (i.e. `add_library(NCCL::NCCL UNKNOWN IMPORTED)` in `FindNCCL.cmake` -- the only issue there is that `add_library` can't be called in script mode which is what will happen if `find_package(NCCL)` is called in the portfile. In that case, I can copy code from FindNCCL directly into the portfile...

Any thoughts on this/is there a best practice? Can also gate the creation of the imported target by `(NOT DEFINED ${CMAKE_SCRIPT_MODE_FILE})` which should only call `add_library` if in script mode, which means things won't break.

2020-11-24 02:03 UTC, JackBoosY requested changes

2020-11-24 02:03 UTC, JackBoosY commented on ports/nccl/portfile.cmake
> +endif()
```suggestion
endif()

file(INSTALL "${CURRENT_PORT_DIR}/usage" DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
```

2020-11-24 02:09 UTC, JackBoosY commented
The `NCCL_LIBRARIES` always only contain the debug library, can you confirm this?

2020-11-24 02:10 UTC, jacobkahn commented
@JackBoosY — only one library ships with NCCL when it's downloaded, and it's a release library. There isn't a debug library as far as I know.

2020-11-24 02:25 UTC, JackBoosY commented
```
NCCL_INCLUDE_DIRS: /home/work/14683/vcpkg/installed/x64-linux/include
NCCL_LIBRARIES: /home/work/14683/vcpkg/installed/x64-linux/debug/lib/libnccl.so

```

2020-11-24 02:26 UTC, jacobkahn commented
@JackBoosY — nope, that's a mistake. Fixing.

2020-11-24 02:37 UTC, jacobkahn commented
@JackBoosY is it viable to not copy the library to `${CURRENT_PACKAGES_DIR}/debug`, or does it need to be there? If it has to be copied, I'll have to change `FindNCCL.cmake` to not find it there.

2020-11-24 02:39 UTC, JackBoosY commented
@jacobkahn Different types of libraries should be copied to the corresponding path, if it does not provide a debug version, you do not need to copy.

2020-11-24 02:40 UTC, jacobkahn commented
@JackBoosY sounds good. I won't copy. I will also send a PR fixing the cuDNN port.

2020-11-24 02:45 UTC, JackBoosY approved these changes

2020-11-24 15:33 UTC, jacobkahn commented
@JackBoosY  this don't actually have a dependency on a different PR. It can be merged as is.

2020-11-25 15:49 UTC, jacobkahn commented
@JackBoosY @strega-nil - looks like three remaining CI jobs have all OOMed and have been stuck for several hours - can we restart them?

2020-11-25 19:33 UTC, jacobkahn commented
👍  — is this ready to merge @JackBoosY @strega-nil?

2020-11-25 19:35 UTC, merged

2020-11-25 19:35 UTC, strega-nil commented
Thanks @jacobkahn :)