[azure-kinect-sensor-sdk] not working on Linux
microsoft/vcpkg pull request #14750
Opened 2020-11-24 12:52 UTC by fran6co

Depends on https://github.com/microsoft/vcpkg/pull/14749

2020-11-25 06:47 UTC, JackBoosY requested changes

2020-11-25 06:47 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/disable-c4275.patch
> + if ("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
```suggestion
 if (MSVC)
```

2020-11-25 09:07 UTC, JackBoosY requested changes

2020-11-25 09:07 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/portfile.cmake
> +if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
```suggestion
if (VCPKG_TARGET_IS_LINUX)
```

2021-02-09 02:21 UTC, JackBoosY commented
Sorry but uou may need to revert libuvc changes.

2021-02-09 02:52 UTC, JackBoosY commented
As I said, please revert changes about libuvc.

Thanks.

2021-02-09 09:06 UTC, fran6co commented
@JackBoosY done

2021-02-09 09:59 UTC, JackBoosY commented
Waiting for merge #16138.

2021-02-11 08:36 UTC, fran6co commented
/azp run

2021-02-11 10:27 UTC, JackBoosY commented
/azp run

2021-02-18 06:05 UTC, JackBoosY commented
```
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\font.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\attributes.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\coverage.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\attriter.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\context.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\fontdescription.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\cairofontmap.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\fontmetrics.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\fontfamily.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\fontset.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\color.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\glyph.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\attrlist.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\fontface.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\glyphstring.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
     2>D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\pango\pangomm\fontmap.cc(4,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory [D:\buildtrees\pangomm\src\pangomm-2-bb0817eca2.clean\MSVC_Net2013\pangomm.vcxproj]
```
Please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=49325&view=artifacts&pathAsName=false&type=publishedArtifacts).

2021-02-18 06:17 UTC, fran6co commented
@JackBoosY those errors are not related to this PR

2021-02-18 08:54 UTC, JackBoosY commented
Wait for https://github.com/microsoft/vcpkg/pull/16270 merge.

2021-02-19 02:44 UTC, JackBoosY commented
/azp run

2021-02-19 06:58 UTC, JackBoosY requested changes

2021-02-19 06:58 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/fix-uvc.patch
> ++   set_property(TARGET libjpeg-turbo::libjpeg-turbo PROPERTY IMPORTED_LOCATION ${JPEG_LIBRARIES})
Where use this targets?

2021-02-19 06:58 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/portfile.cmake
> +        fix-uvc.patch
Should we only apply these 2 patches on Linux?

2021-02-19 06:58 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/fix-linux.patch
> +diff --git a/cmake/k4aCompilerFlags.cmake b/cmake/k4aCompilerFlags.cmake
Does the official accept this changes? Can you please report it to the upstream?

Thanks.

2021-02-19 10:50 UTC, fran6co commented on ports/azure-kinect-sensor-sdk/portfile.cmake
> +        fix-uvc.patch
The patches work on windows too

2021-02-19 10:52 UTC, fran6co commented on ports/azure-kinect-sensor-sdk/fix-uvc.patch
> ++   set_property(TARGET libjpeg-turbo::libjpeg-turbo PROPERTY IMPORTED_LOCATION ${JPEG_LIBRARIES})
It was complaining in the build with alpha 1.4.0, maybe it's not longer needed after upgrading to 1.4.1. I would need to retest the patches. But it's currently working on all platforms

2021-02-19 10:53 UTC, fran6co commented on ports/azure-kinect-sensor-sdk/fix-linux.patch
> +diff --git a/cmake/k4aCompilerFlags.cmake b/cmake/k4aCompilerFlags.cmake
I haven't pushed the changes upstream because most of them are just changing the find_packages to the vcpkg ones

2021-02-20 02:40 UTC, JackBoosY approved these changes

2021-02-20 02:41 UTC, JackBoosY requested changes

2021-02-20 02:41 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/CONTROL
>  Supports: windows
```suggestion
```

2021-02-20 09:11 UTC, JackBoosY requested changes

2021-02-20 09:11 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/portfile.cmake
> +    SHA512 17630a00f4e9ff3ef68945b62021f6d0390030b43c120c207afe934075a7a87c5848be1f46f4c35c7ecd5698012452ffcbb67f739e9048857410ec7077e5e8c6
```suggestion
    SHA512 6c15975e7c834672de723b0c474fa4cd58f41c5bee6511dcbdbc22f1a58daa906c4f01a7e941af0e7d09f763ff886015c1f6b1e29b6bdfb333f10857edfec2ca
```

2021-02-22 05:40 UTC, JackBoosY commented
When building x64-osx:
```
CMake Error at /Volumes/data/work/1/s/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
  Could not find a package configuration file provided by "libuvc" with any
  of the following names:

    libuvcConfig.cmake
    libuvc-config.cmake

  Add the installation prefix of "libuvc" to CMAKE_PREFIX_PATH or set
  "libuvc_DIR" to a directory containing one of the above files.  If "libuvc"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:114 (find_package)
```
Does that expected?

2021-02-22 06:41 UTC, fran6co commented
@JackBoosY yes, I didn't get libuvc to build on macOS so it's only available for Linux right now. Probably it's easy to fix it, but I think it would be better to make this port only support windows and Linux for now.

2021-02-22 08:16 UTC, JackBoosY requested changes

2021-02-22 08:16 UTC, JackBoosY commented on ports/azure-kinect-sensor-sdk/CONTROL
> +Build-Depends: azure-c-shared-utility, glfw3, gtest, imgui, libusb, spdlog, cjson, ebml, libjpeg-turbo, matroska, libsoundio, libyuv, libuvc (linux)
```suggestion
Build-Depends: azure-c-shared-utility, glfw3, gtest, imgui, libusb, spdlog, cjson, ebml, libjpeg-turbo, matroska, libsoundio, libyuv, libuvc (linux)
Supports: !osx
```

2021-02-22 08:31 UTC, JackBoosY requested changes

2021-02-22 08:31 UTC, JackBoosY commented on versions/a-/azure-kinect-sensor-sdk.json
> +      "git-tree": "59a3a985dcf5ee9769224dc02feb53e092f85dba",
```suggestion
      "git-tree": "d60602da16f9c39b78d2f33f00d48e385c7c7c67",
```

2021-02-22 08:32 UTC, JackBoosY approved these changes

2021-03-09 22:45 UTC, adammpolak commented
@fran6co is this PR ready to rock?

2021-03-09 23:12 UTC, fran6co commented
Not sure about rocking but maybe you can get some jazz out of it

2021-03-10 01:53 UTC, JackBoosY commented
Waiting for merge.

2021-03-15 16:48 UTC, adammpolak commented
( @JackBoosY how do we merge 😬)

2021-03-15 22:25 UTC, ras0219-msft commented
I've pushed the merge to https://github.com/ras0219-msft/vcpkg/tree/azure_linux, however I'm unable to push directly to your branch. Could you please run:
```
git pull https://github.com/ras0219-msft/vcpkg azure_linux
git push
```
while on your azure_linux branch?

2021-03-16 08:46 UTC, fran6co commented
@ras0219-msft  done

2021-03-29 17:17 UTC, merged