[speexdsp] Update CMake script for macOS/Linux
microsoft/vcpkg pull request #14758
Opened 2020-11-25 00:53 UTC by LRFLEW

The CMake build for SpeexDSP in vcpkg was designed very narrowly for building on Windows. This is pretty clear with the presence of the lines like `add_definitions(-D_WINDOWS -D_USRDLL)` in the CMake file. This caused the build to fail for macOS and Linux. I went through, analyzing and understanding the project's autoconf setup, and writing a new CMake file that's more platform agnostic.

To make it simpler, I have the script make certain assumptions about the build setup. The CMake file generally assumes that the compiler is either MSVC, GCC, or Clang. This is mostly present in conditions for the different definitions of `EXPORT` and `VAR_ARRAYS`.

The original script used `file(GLOB_RECURSE ...)` to list the source and header files for the project. I switched this to explicitly listing the files instead. Looking through the autoconf files of the project, there were some minor differences from what the original was doing. Some source files were only compiled for specific FFT's (smallft.c, kiss_fft.c, and kiss_fftr.c), and one of the header files in the include directory is not actually set to install (speex_buffer.h).

The public header file speexdsp_types.h includes the integer type definitions for Windows and macOS, but Linux is expected to have speexdsp_config_types.h present. This file is generated by the autoconf configuration based on the headers and integer types available. If <stdint.h> is available (and has the fixed-size integer types), the configuration generated header will use it. For the CMake config file, I assume that it is available and configure the file directly to make it work correctly on Linux.

The download source for the project was change from the official source to the Github mirror with #11218. This appears to have been a workaround for an issue with CMake at the time which has since been resolved. Using a Git source does have the advantage of making `--head` builds possible, but the Github mirror is not kept up-to-date very well. (It was significantly behind until I made a PR that brought attention to the mirror). The official Git for the project is xiph's Gitlab. I asked on xiph's IRC about using it as the source in vcpkg, and they said that the original download url used is the preferred download source, and didn't want the Gitlab instance to be the *main* source, as the hosting for it is "donated" and they didn't want to send too much load onto it. As a compromise, I updated the portfile to use the official download link for release builds and the Gitlab instance for `--head` builds.

2020-11-25 06:04 UTC, JackBoosY requested changes

2020-11-25 06:04 UTC, JackBoosY commented on ports/speexdsp/portfile.cmake
> +        SHA512 e357cd5377415ea66c862302c7cf8bf6a10063cacd903f0846478975b87974cf5bdf00e2c6759d8f4f453c4c869cf284e9dc948a84a83d7b2ab96bd5405c05ec
I think we'd better to add a comment here that why we choose this path.

2020-11-25 22:55 UTC, LRFLEW commented on ports/speexdsp/portfile.cmake
> +        SHA512 e357cd5377415ea66c862302c7cf8bf6a10063cacd903f0846478975b87974cf5bdf00e2c6759d8f4f453c4c869cf284e9dc948a84a83d7b2ab96bd5405c05ec
I added a comment about why there's a split between the `--head` and release sources. I assume that's what you're referring to by "why we choose this url." If you were looking for something else to be commented, then please clarify what you're asking for.

2020-11-25 23:01 UTC, LRFLEW commented on ports/speexdsp/portfile.cmake
> +set(USE_NEON OFF)
Unset variables don't default to `OFF`, but instead to `""`. This is a subtle distinction, as both are treated as false values in comparisons, but allowing the value passed into the CMake to be anything other than `ON` or `OFF` could lead to confusion later when an issue needs to be debugged. Also, I'm not sure how stable passing in an empty option value is in CMake (since `option()` expects boolean values). I think leaving this how it is makes sense.

2020-11-25 23:01 UTC, LRFLEW commented on ports/speexdsp/portfile.cmake
>  set(USE_SSE OFF)
See [my other comment](https://github.com/microsoft/vcpkg/pull/14758#discussion_r530684926)

2020-11-25 23:07 UTC, LRFLEW commented
The CI ran into an error for the Windows builds. I don't get what's going on or what the appropriate fix *should* be. The error is as follows:

```
CMake Error: Could not open file for write in copy operation D:/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include/speex/speexdsp_config_types.h.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:92 (configure_file):
  configure_file Problem configuring file
```

I'm not sure why it would have permission errors, but I'm looking into changing the output location for the `configure_file` call.

2020-11-26 19:42 UTC, LRFLEW commented
The CI had build errors for the Windows ARM targets. Apparently the Neon support in SpeexDSP is written for GCC's inline ASM syntax and is not compatible with MSVC. I updated the portfile to not enable the explicit Neon optimizations when using MSVC.

2020-11-27 06:22 UTC, JackBoosY requested changes

2020-11-27 06:22 UTC, JackBoosY commented on ports/speexdsp/portfile.cmake
> +    # Use official download URL for release builds to reduce traffic to the Gitlab host
```suggestion
    # Since the github repo is out-dated, use official download URL for release builds to reduce traffic to the Gitlab host
```

2020-11-27 08:45 UTC, JackBoosY requested changes

2020-11-27 08:45 UTC, JackBoosY commented on ports/speexdsp/CMakeLists.txt
> +elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
```suggestion
elseif(WIN32)
```

2020-11-27 08:45 UTC, JackBoosY commented on ports/speexdsp/CMakeLists.txt
> +    add_definitions("-DEXPORT=")
When we build dynamic, the export should be `__declspec(dllexport)`.
Is it?

2020-11-27 08:45 UTC, JackBoosY commented on ports/speexdsp/CMakeLists.txt
> +if (NOT CMAKE_C_COMPILER_ID MATCHES "MSVC")
```suggestion
if (NOT MSVC)
```

2020-11-27 08:45 UTC, JackBoosY commented on ports/speexdsp/CMakeLists.txt
> +               "${CMAKE_CURRENT_BINARY_DIR}/speexdsp_config_types.h")
Missing `@ONLY` or `COPYONLY`?

2020-11-28 02:38 UTC, LRFLEW commented on ports/speexdsp/CMakeLists.txt
> +    add_definitions("-DEXPORT=")
SpeexDSP actually doesn't support `__declspec(dllexport)`. The simple explanation is that the public header files would need to also use the `EXPORT` macro. If you try to use `__declspec(dllexport)`, the build will fail with Error C2375. The line following this one adds a .def file to the build, which is how the project handles DLL exports on Windows.

2020-11-28 02:55 UTC, LRFLEW commented on ports/speexdsp/CMakeLists.txt
> +elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
I was under the impression that this was the "*wrong*" way of doing this. Looking through a few of the ports, it seems that using `WIN32` is at least more common, so I'll switch it for project consistency.

2020-11-30 02:52 UTC, JackBoosY approved these changes

2020-11-30 19:57 UTC, merged

2020-11-30 19:57 UTC, strega-nil commented
Cool, thanks @LRFLEW !

2020-12-07 17:39 UTC, BillyONeal commented
The linux build of speexdsp still fails for me; it was missed here because `speexdsp` is in `ci.baseline.txt` as failed.

2020-12-08 05:43 UTC, LRFLEW commented
@BillyONeal I was working on a macOS machine, so I hadn't tested it on Linux myself. I had assumed that it would work based on my analysis of the automake script. If you can provide logs of the errors you're getting, I can take a look. Otherwise, I'll see if I get issues in a Docker instance, but it might take me some time to get around to it.

2020-12-08 17:48 UTC, BillyONeal commented
@LRFLEW Here you go:

```
billy@bion-ubuntu-18-04:~/vcpkg$ ./vcpkg install speexdsp
Computing installation plan...
The following packages will be built and installed:
    speexdsp[core]:x64-linux -> 1.2.0#3
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/billy/.cache/vcpkg/archives/2d/2d63e6218aad1e3394293db35189b4f67c35fd1e.zip
Starting package 1/1: speexdsp:x64-linux
Building package speexdsp[core]:x64-linux...
-- Using cached /home/billy/vcpkg/downloads/speexdsp-1.2.0.tar.gz
-- Cleaning sources at /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/billy/vcpkg/downloads/speexdsp-1.2.0.tar.gz
-- Using source at /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: /home/billy/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j65
    Working Directory: /home/billy/vcpkg/buildtrees/speexdsp/x64-linux-dbg
    See logs for more information:
      /home/billy/vcpkg/buildtrees/speexdsp/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/speexdsp/portfile.cmake:41 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package speexdsp:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: speexdsp:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.
billy@bion-ubuntu-18-04:~/vcpkg$ cat /home/billy/vcpkg/buildtrees/speexdsp/install-x64-linux-dbg-out.log
[1/11] /usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/mdf.c
FAILED: CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o
/usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/mdf.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/mdf.c
In file included from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/arch.h:70:0,
                 from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/mdf.c:72:
/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include/speex/speexdsp_types.h:122:10: fatal error: speexdsp_config_types.h: No such file or directory
 #include "speexdsp_config_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/11] /usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/scal.c
FAILED: CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o
/usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/scal.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/scal.c
In file included from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include/speex/speex_echo.h:40:0,
                 from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/scal.c:47:
/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include/speex/speexdsp_types.h:122:10: fatal error: speexdsp_config_types.h: No such file or directory
 #include "speexdsp_config_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[3/11] /usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/fftwrap.c
FAILED: CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o
/usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/fftwrap.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/fftwrap.c
In file included from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/arch.h:70:0,
                 from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/fftwrap.c:39:
/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include/speex/speexdsp_types.h:122:10: fatal error: speexdsp_config_types.h: No such file or directory
 #include "speexdsp_config_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[4/11] /usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/filterbank.c
FAILED: CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o
/usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o -MF CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o.d -o CMakeFiles/speexdsp.dir/libspeexdsp/filterbank.c.o -c /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/filterbank.c
In file included from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/arch.h:70:0,
                 from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/filterbank.h:37,
                 from /home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/libspeexdsp/filterbank.c:38:
/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include/speex/speexdsp_types.h:122:10: fatal error: speexdsp_config_types.h: No such file or directory
 #include "speexdsp_config_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[5/11] /usr/bin/cc -DEXPORT="" -DFLOATING_POINT -DUSE_SMALLFT -DUSE_SSE -DUSE_SSE2 -DVAR_ARRAYS -I/home/billy/vcpkg/buildtrees/speexdsp/src/1.2.0-b3a579389f.clean/include -fPIC -g -MD -MT CMakeFiles/speexdsp.dir/libspeexdsp/jitter.c.o -MF CMakeFi [...]

2020-12-09 04:24 UTC, LRFLEW commented
>```
>  include/speex/speexdsp_types.h:122:10: fatal error: speexdsp_config_types.h: No such file or directory
>  #include "speexdsp_config_types.h"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~
>```

I had added handling for `speexdsp_config_types.h`, so it *is* a bug if that's the issue. My guess is that the quick fix I made for [this issue](https://github.com/microsoft/vcpkg/pull/14758#issuecomment-733984344) isn't working correctly. I'll issue a PR for it.

> To be clear, I don't think we're clamoring to do anything specifically here; this port has always been in ci.baseline.txt. Just letting you know in case you were depending on that to work.

I'm not depending on Linux support for what I'm doing, but I was intending on making Linux support work, and I don't mind taking time to see that through.