Build using c++17 standard
microsoft/vcpkg pull request #14762
Opened 2020-11-25 08:11 UTC by JonLiu1993

**Describe the pull request**

- What does your PR fix? Fixes #14654 
Redis-plus-plus is by default built using c++11 standard. When trying to use it in a Linux application built using C++17 I get link errors.

Build redis-plus-plus using define flag REDIS_PLUS_PLUS_CXX_STANDARD=17 can be solved

Note: No feature need to test

2020-11-25 09:30 UTC, JackBoosY requested changes

2020-11-25 09:30 UTC, JackBoosY commented on ports/redis-plus-plus/portfile.cmake
> +        -DREDIS_PLUS_PLUS_CXX_STANDARD=17
Add a feature `cxx17` instead.

2020-11-26 02:30 UTC, JackBoosY requested changes

2020-11-26 02:30 UTC, JackBoosY commented on ports/redis-plus-plus/portfile.cmake
> +
```suggestion
```

2020-11-26 02:31 UTC, JackBoosY requested changes

2020-11-26 02:31 UTC, JackBoosY commented on ports/redis-plus-plus/CONTROL
> +Description: Build redis-plus-plus using define flag REDIS_PLUS_PLUS_CXX_STANDARD=17
```suggestion
Description: Build redis-plus-plus with cxx 17 standard
```

2020-12-01 01:51 UTC, JackBoosY requested changes

2020-12-01 01:51 UTC, JackBoosY commented on ports/redis-plus-plus/portfile.cmake
> +
```suggestion
```

2020-12-01 01:51 UTC, JackBoosY commented on ports/redis-plus-plus/portfile.cmake
> +    OPTIONS ${FEATURE_OPTIONS}
```suggestion
    OPTIONS
```

2020-12-01 01:51 UTC, JackBoosY commented on ports/redis-plus-plus/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright )
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright )
```

2020-12-01 01:52 UTC, JackBoosY approved these changes

2020-12-01 06:24 UTC, NancyLi1013 approved these changes

2020-12-01 22:16 UTC, merged

2020-12-01 22:16 UTC, strega-nil commented
Thanks @JonLiu1993 :)