[ace] copy generated headers files for tao
microsoft/vcpkg pull request #14768
Opened 2020-11-25 17:00 UTC by victorburckel

**Describe the pull request**
For tao feature, some header files are generated by the tao_idl compiler. Also install those generated headers in the package. As vcpkg_install_msbuild generate a temporary build folder, skip clean at first to keep generated files, copy the files from the copy source folder instead of the source folder at the end of the process, and finally execture the clean up proces

- What does your PR fix? 
Add missing headers for TAO

- Which triplets are supported/not supported? Have you updated the CI baseline?
This fixes the windows x86 and x64 packages

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

2020-11-26 02:54 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-11-26 15:30 UTC, victorburckel commented
Sorry forgot about the Port-Version, I updated the control file.

2020-11-27 06:07 UTC, JackBoosY commented
Will check the output manually later.

2020-11-30 02:35 UTC, JackBoosY commented
LGTM.

2020-11-30 02:35 UTC, JackBoosY approved these changes

2020-11-30 18:37 UTC, merged

2020-11-30 18:37 UTC, strega-nil commented
Thanks @victorburckel !