[nvml] Initial commit for Non-Volatile Memory Library
microsoft/vcpkg pull request #1477
Opened 2017-07-18 12:54 UTC by krzycz

2017-07-18 12:54 UTC, msftclas commented
@__krzycz__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-07-19 00:12 UTC, ras0219-msft requested changes
Overall looks great!

I had a few comments about tools and I'll be happy to merge once those are addressed.

2017-07-19 00:12 UTC, ras0219-msft commented on ports/nvml/portfile.cmake
> +file(INSTALL ${DEBUG_ARTIFACTS_PATH}/pmempool.exe DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
We typically don't install debug versions of tools.

2017-07-19 00:12 UTC, ras0219-msft commented on ports/nvml/portfile.cmake
> +file(INSTALL ${RELEASE_ARTIFACTS_PATH}/pmempool.exe DESTINATION ${CURRENT_PACKAGES_DIR}/tools)
This should go into a `nvml` subdirectory of tools and then you should also call `vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/nvml)` to ensure any runtime DLLs are deployed applocally to it.

2017-07-19 09:45 UTC, krzycz commented on ports/nvml/portfile.cmake
> +file(INSTALL ${RELEASE_ARTIFACTS_PATH}/pmempool.exe DESTINATION ${CURRENT_PACKAGES_DIR}/tools)
Fixed.

2017-07-19 09:45 UTC, krzycz commented on ports/nvml/portfile.cmake
> +file(INSTALL ${DEBUG_ARTIFACTS_PATH}/pmempool.exe DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
Fixed.

2017-09-06 21:08 UTC, ras0219-msft commented
Hi @krzycz, did you sign the CLA? I need that to merge this PR.

2017-10-03 21:58 UTC, ras0219-msft approved these changes

2017-10-03 21:58 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Microsoft/vcpkg?pullRequest=1477) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Microsoft/vcpkg?pullRequest=1477) before we can accept your contribution.<br/><br/>:x: krzycz [sign now](https://cla.opensource.microsoft.com/Microsoft/vcpkg?pullRequest=1477)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Microsoft/vcpkg?pullRequest=1477) it.</sub>

2018-03-22 07:42 UTC, krzycz commented
@ras0219-msft - CLA signed

2018-03-22 08:35 UTC, merged

2018-03-22 08:35 UTC, ras0219-msft commented
Thanks!