[moltenvk] New Port
microsoft/vcpkg pull request #14819
Opened 2020-11-28 03:34 UTC by Haeri

This is a first attempt to port MoltenVK. This port is not 100% perfect and has TODOs but this is a first base-implementation. The port is based on the unfortunately closed #9575 PR.

- What does your PR fix? Fixes #
This is a new port #14698

- Which triplets are supported/not supported? Have you updated the CI baseline?
Only osx is supported. CI is updated.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
As much as possible. Unfortunately the dependencies of MoltenVK are handled with script files. It would require a big patch to  adjust the dependencies to vcpkg.

2020-11-30 06:02 UTC, JackBoosY requested changes

2020-11-30 06:02 UTC, JackBoosY commented on ports/moltenvk/portfile.cmake
> +vcpkg_build_make(BUILD_TARGET macos)
Does it have install command?

2020-11-30 06:02 UTC, JackBoosY commented on ports/moltenvk/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
```suggestion
if(VCPKG_TARGET_IS_OSX AND VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
```

2020-11-30 06:02 UTC, JackBoosY commented on ports/moltenvk/portfile.cmake
> +file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/Package/Latest/MoltenVKShaderConverter/MoltenVKShaderConverter.xcframework/macos-x86_64/libMoltenVKShaderConverter.a DESTINATION ${CURRENT
```suggestion
if (NOT VCPKG_TARGET_IS_WINDOWS)
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/Package/Latest/MoltenVK/MoltenVK.xcframework/macos-x86_64/libMoltenVK.a DESTINATION ${CURRENT_PACKAGES_DIR}/lib)
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/Package/Latest/MoltenVKShaderConverter/MoltenVKShaderConverter.xcframework/macos-x86_64/libMoltenVKShaderConverter.a DESTINATION ${CURRENT_PACKAGES_DIR}/lib)
    # copy debug static
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/Package/Latest/MoltenVK/MoltenVK.xcframework/macos-x86_64/libMoltenVK.a DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib)
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/Package/Latest/MoltenVKShaderConverter/MoltenVKShaderConverter.xcframework/macos-x86_64/libMoltenVKShaderConverter.a DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib)
endif()
```

2020-11-30 17:22 UTC, Haeri commented on ports/moltenvk/portfile.cmake
> +)
The fetchDependencies script downloads the following dependencies:

- cereal
- Vulkan-Headers
- SPIRV-Cross
- glslang
- Vulkan-Tools
- VulkanSamples

Except for Vulkan-Tools and VulkanSamples all the other dependencies have vcpkg ports but as already explained in the initial PR, this is an xcode exclusive project and would require a lot of plumbing to swap out the dependencies. At least that would exceed my knowledge.

2020-11-30 17:29 UTC, Haeri commented on ports/moltenvk/portfile.cmake
> +vcpkg_build_make(BUILD_TARGET macos)
I'm intentionally using `vcpkg_build_make` instead `vcpkg_install_make` cause the install step seems to have some bug:
```
 Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing x64-osx-dbg
-- Installing x64-osx-rel
CMake Error at scripts/cmake/vcpkg_build_make.cmake:191 (file):
  file RENAME failed to rename

    /Users/runner/work/ElementalDraw/ElementalDraw/external/vcpkg/packages/moltenvk_x64-osx_tmp/Users/runner/work/ElementalDraw/ElementalDraw/build/vcpkg_installed/x64-osx/

  to

    /Users/runner/work/ElementalDraw/ElementalDraw/external/vcpkg/packages/moltenvk_x64-osx

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_make.cmake:24 (vcpkg_build_make)
  /Users/runner/work/ElementalDraw/ElementalDraw/external/custom-ports/moltenvk/portfile.cmake:25 (vcpkg_install_make)
  scripts/ports.cmake:79 (include)
```

Someone from the vcpkg Discord suggested to just use `vcpkg_build_make`.

2020-11-30 17:30 UTC, Haeri commented on ports/moltenvk/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
Since I am using `vcpkg_fail_port_install(ON_TARGET "WINDOWS" "LINUX" "UWP")` I thought this was not necessary.

2020-12-01 02:10 UTC, JackBoosY commented on ports/moltenvk/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
For future expansion, I think we’d better do this.

2020-12-01 02:10 UTC, JackBoosY commented
I'll help you to improve this PR later.

2020-12-02 09:36 UTC, JackBoosY commented
Ops, the official build type is to use xcodebuild which we don’t support it now.
Let me find other solution.

2020-12-02 09:40 UTC, JackBoosY commented
@Haeri I don't know xcode because I have never used it for development. Can you help me if I have any questions?

2020-12-02 09:57 UTC, JackBoosY requested changes

2020-12-02 09:57 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +moltenvk:x64-linux=fail
```suggestion
```

2020-12-03 12:47 UTC, Haeri commented
> @Haeri I don't know xcode because I have never used it for development. Can you help me if I have any questions?

Unfortunately me neither 😅 and I don't have access to a mac either at the moment. I am also not associated with the MoltenVK project in any way. I'm just trying to get it to work with my project. It is a bit unfortunate that they insist on using xcode instead of cmake or actual make (as you saw, their make file just calls xcode) but they argue, that this is justified, since this is a apple only project. 

Also it is a bit surprising that the initial PR azure build failed as I have tested that version in my project with Github actions:
https://github.com/Haeri/ElementalDraw/runs/1468647387?check_suite_focus=true#step:3:7

PS: Any particular reason you removed the adjustments to ci.baseline.txt?

2020-12-04 02:14 UTC, JackBoosY commented
@Haeri If we added `Support` keyword on manifest or CONTROL file, we don't need to add the same content on baseline.

2020-12-11 05:42 UTC, JackBoosY commented
@Haeri Can you try this PR locally?

2020-12-11 19:41 UTC, Haeri commented
@JackBoosY The main issue is that the vulkan dependency is only a check if the Vulkan SDK is installed and does not actually contain anything in it. That's why it fails when I run it on the GitHub runner:
https://github.com/Haeri/ElementalDraw/runs/1501915931?check_suite_focus=true#step:4:238

I assume that the Vulkan SDK is installed on the Azure pipeline, seeing that it didn't fail there.

2020-12-14 02:29 UTC, JackBoosY commented
@Haeri No, Vulkan is skipped on our pipeline test.

2020-12-29 07:36 UTC, JackBoosY commented
As @strega-nil said:
> macOS _does not_ support vulkan, at least natively; Khronos seems to have created a compatibility layer, maybe, but I'm not sure on that.
I'm not clear if this PR works.

2020-12-29 16:58 UTC, Haeri commented
> As @strega-nil said:
> 
> > macOS _does not_ support vulkan, at least natively; Khronos seems to have created a compatibility layer, maybe, but I'm not sure on that.
> > I'm not clear if this PR works.

@JackBoosY Not sure if this comment was directed towards me, but moltenvk ***is*** the compatibility layer @strega-nil is referring to.

2020-12-30 02:21 UTC, JackBoosY commented
So if this PR works locally, then we can accept this without test on the pipeline.
However, I can't test it on my machine because I can't install vulkan.

2020-12-30 16:59 UTC, strega-nil commented
@JackBoosY @Haeri isn't it the case that `moltenvk` provides vulkan given metal (installed by default on macOS)? You should be able to install it without any prerequisites.

2020-12-30 22:55 UTC, Haeri commented
@strega-nil Yes MoltenVk is a portability implementation that allows Vulkan to run on Metal. It does have some prerequisites or dependencies on:
- Cereal
- Vulkan-Headers
- SPIRV-Cross
- glslang 
- Vulkan-Tools
- VulkanSamples

All of them already have vcpkg ports except for `Vulkan-Tools`. I'm not sure if that is the cause, but I am unfortunately not able to successfully compile this current port @JackBoosY. I do a step, where I install the Vulkan SDK so the `vulkan` port does not abort for not being able to find VULKAN_SDK but still no luck:
https://github.com/Haeri/Mac-Runner/runs/1628063004#step:4:109

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: "xcodebuild build -quiet -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (macOS only)" -configuration "Debug""
    Working Directory: /Users/runner/work/Mac-Runner/Mac-Runner/extern/vcpkg/buildtrees/moltenvk/x64-osx-dbg
    See logs for more information:
```
Unfortunately I am not able to find more log files to see what the problem is.

2020-12-31 02:19 UTC, JackBoosY commented
@Haeri Can you manually run the command `xcodebuild build -quiet -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (macOS only)" -configuration "Debug"` in directory _/Users/runner/work/Mac-Runner/Mac-Runner/extern/vcpkg/buildtrees/moltenvk/x64-osx-dbg_ ?

2020-12-31 03:50 UTC, Haeri commented
@JackBoosY https://github.com/Haeri/Mac-Runner/runs/1628845754?check_suite_focus=true#step:5:56
Looks like it is having trouble finding the dependencies. I guess we will have to manually reimplement the stuff their `fetchDependencies.sh` is doing...

2020-12-31 07:17 UTC, JackBoosY commented
@Haeri Yeah...

2021-05-21 08:49 UTC, PhoebeHui commented
@Haeri, we prefer using CMake buildsystems, the OSX CI test machines doesn't support to executing the commands, and may not support in future,  may be you can add a custom CMakeLists.txt instead?

2021-05-21 11:31 UTC, Haeri commented
@PhoebeHui I completely understand and I also would have preferred for them to provide a proper cmake build system instead, but unfortunately, that's what they chose. 
As I already mentioned, I have no affiliation at all with MoltenVK and to be honest, after spending one month trying to get their stuff to compile, I just can't be bothered to deal with it anymore. So instead I am using OpenGL as a stand-in backend for Vulkan on Apple platforms. 
Feel free to close this PR at any time and maybe if someday they decide to switch to cmake, we can finalize this RP.

2021-05-24 02:16 UTC, PhoebeHui commented
@Haeri, thanks for your response!

2021-05-24 02:16 UTC, closed without merging