Fix Git too long path error
microsoft/vcpkg pull request #14825
Opened 2020-11-28 19:59 UTC by Pospelove

Fixes #14824 

[This](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows) answer helped me.

2020-11-30 06:41 UTC, JackBoosY commented
/azp run

2020-11-30 07:40 UTC, JackBoosY commented
@strega-nil Could you please check the linux and osx regressions? They are related to the permission.

Thanks.

2020-11-30 17:51 UTC, strega-nil commented
Rerunning after merging #14848 

/azp run

2020-11-30 17:51 UTC, strega-nil commented
/azp run

2020-11-30 18:24 UTC, ras0219 requested changes

2020-11-30 18:24 UTC, ras0219 commented on scripts/cmake/vcpkg_apply_patches.cmake
> +            COMMAND ${GIT} config --system core.longpaths true
This modifies the global system state, which is against vcpkg policy. Instead, we should pass `-c core.longpaths=true` to the actual git command.

2020-12-06 00:32 UTC, Pospelove commented
kek

2020-12-07 02:41 UTC, JackBoosY commented
```
-- Applying patch cmake_dont_build_more_than_needed.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:63 (message):
  Applying patch failed.  error: unknown switch `c'
```

2020-12-07 08:09 UTC, JackBoosY commented
Needs merge to master.

2020-12-09 19:54 UTC, BillyONeal commented
Just pinged @ras0219 / @ras0219-msft again

2020-12-09 20:06 UTC, BillyONeal commented
I spoke with Robert and he's not a fan of `--config local` either, I'm investigating a fix that still uses `-c`.

2020-12-09 20:18 UTC, BillyONeal commented
Test result:

```
PS C:\Dev\Users\Denis\AppData\Local\pmm\1.4.2\vcpkg-790910f79f653978f90aadd958abf3c407215552\vcpkg> .\vcpkg.exe install mongo-c-driver
Computing installation plan...
The following packages will be built and installed:
  * libbson[core]:x86-windows -> 1.16.1#2
    mongo-c-driver[core]:x86-windows -> 1.16.1#3
  * zlib[core]:x86-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\billy\AppData\Local\vcpkg\archives\fb\fb2f04ad0e948f17f46081da042a3c132e598721.zip
Could not locate cached archive: C:\Users\billy\AppData\Local\vcpkg\archives\80\809e8129cb834f39817b645c4f7f20a3bfcd54cc.zip
Could not locate cached archive: C:\Users\billy\AppData\Local\vcpkg\archives\86\86d8ce5e3652d58bcb6075cb1f82df5f84ae6976.zip
Starting package 1/3: libbson:x86-windows
Building package libbson[core]:x86-windows...
-- Downloading https://github.com/mongodb/mongo-c-driver/archive/99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz...
-- Extracting source C:/Dev/vcpkg-downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-static-cmake.patch
-- Using source at C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/buildtrees/libbson/src/97251b2b2d-a3810c39b5.clean
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/packages/libbson_x86-windows/share/libbson/copyright
-- Installing: C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/packages/libbson_x86-windows/share/libbson/usage
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\billy\AppData\Local\vcpkg\archives\fb\fb2f04ad0e948f17f46081da042a3c132e598721.zip
Building package libbson[core]:x86-windows... done
Installing package libbson[core]:x86-windows...
Installing package libbson[core]:x86-windows... done
Elapsed time for package libbson:x86-windows: 17.47 s
Starting package 2/3: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached C:/Dev/vcpkg-downloads/zlib1211.tar.gz
-- Extracting source C:/Dev/vcpkg-downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at C:/Dev/vcpkg-downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/packages/zlib_x86-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig file: C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/packages/zlib_x86-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\billy\AppData\Local\vcpkg\archives\80\809e8129cb834f39817b645c4f7f20a3bfcd54cc.zip
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 4.138 s
Starting package 3/3: mongo-c-driver:x86-windows
Building package mongo-c-driver[core]:x86-windows...
-- Using cached C:/Dev/vcpkg-downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Extracting source C:/Dev/vcpkg-downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Applying patch fix-dependency-libbson.patch
-- Applying patch disable-static-when-dynamic-build.patch
-- Applying patch fix-arm-build.patch
-- Using source at C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/buildtrees/mongo-c-driver/src/97251b2b2d-64741a92bf.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Dev/Users/Denis/AppData/Local/pmm/1.4.2/vcpkg-790910f79f653978f90aadd958abf3c407215552/vcpkg/packages/mongo-c-driver_x86-windows/share/mongo-c-driver/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\billy\AppData\Local\vcpkg\archives\86\86d8ce5e3652d58bcb6075cb1f82df5f84ae6976.zip
Building package mongo-c-driver[core]:x86-windows... done
Installing package mongo-c-driver[core]:x86-windows...
Installing package mongo-c-driver[core]:x86-windows... done
Elapsed time for package mongo-c-driver:x86-windows: 14.57 s

Total elapsed time: 38.98 s

The package mongo-c-driver is compatible with built-in CMake targets:

        find_package(libmongoc-1.0 CONFIG REQUIRED)

        target_include_directories(main PRIVATE ${MONGOC_INCLUDE_DIRS})
        target_link_libraries(main PRIVATE ${MONGOC_LIBRARIES})
        target_compile_definitions(main PRIVATE ${MONGOC_DEFINITIONS})

PS C:\Dev\Users\Denis\AppData\Local\pmm\1.4.2\vcpkg-790910f79f653978f90aadd958abf3c407215552\vcpkg>
```

2020-12-15 04:53 UTC, Pospelove commented
🆘

2020-12-15 05:47 UTC, JackBoosY commented
```
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
jmemansi.c(234): fatal error C1051: program database file, 'D:\buildtrees\gdal\x64-windows-dbg\gdal301_d.pdb', has an obsolete format, delete it and recompile
```

2020-12-15 08:05 UTC, JackBoosY commented
LGTM.

2020-12-15 22:35 UTC, ras0219-msft approved these changes

2020-12-15 22:37 UTC, merged

2020-12-15 22:37 UTC, BillyONeal commented
thanks for your help!