[kuku] Add new port
microsoft/vcpkg pull request #14898
Opened 2020-12-02 06:08 UTC by kiromaru

Add new port for kuku library:
https://github.com/microsoft/Kuku

- What does your PR fix?
This is a new port

- Which triplets are supported/not supported? Have you updated the CI baseline?
Tested x86-windows, x86-windows-static, x64-windows, x64-windows-static, x64-linux, x64-osx. Other triplets should be supported as well.
I have not updated the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-12-02 08:31 UTC, PhoebeHui requested changes
Thanks for the PR! Please ignore the CI failures, it doesn't relate to this changes.

2020-12-02 08:31 UTC, PhoebeHui commented on ports/kuku/CONTROL
> +Default-Features:
```suggestion
```

2020-12-02 21:04 UTC, kiromaru commented
I've removed the empty Default-Features entry.

2020-12-03 03:13 UTC, PhoebeHui approved these changes

2020-12-05 00:40 UTC, merged

2020-12-05 00:40 UTC, BillyONeal commented
Thanks!