[flashlight-cuda] Add stb as dependency, bump port commit
microsoft/vcpkg pull request #14912
Opened 2020-12-02 17:27 UTC by jacobkahn

`stb` should be a dependency but isn't. If the flashlight build doesn't find stb, it downloads it from source, which is bad because there might be multiple headers for the same project if a downstream project uses the stb vcpkg port. This also caused a problem because flashlight tried to install the downloaded stb headers which resulted in some empty directories/could break the port.

Also updates the port commit to have some fixes to the nvcc `-std`/C++ compiler version.

- Which triplets are supported/not supported? Have you updated the CI baseline?

Same triplets as before. No changes.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-12-03 02:20 UTC, PhoebeHui requested changes
Thanks for the PR!

2020-12-03 02:20 UTC, PhoebeHui commented on ports/flashlight-cuda/vcpkg.json
> +  "port-version": 2,
```suggestion
  "port-version": 0,
```

2020-12-03 08:15 UTC, PhoebeHui approved these changes

2020-12-05 00:41 UTC, merged

2020-12-05 00:41 UTC, BillyONeal commented
Thanks for your contribution!