[sail] Add port, do not merge
microsoft/vcpkg pull request #14925
Opened 2020-12-03 13:24 UTC by smoked-herring

**Describe the pull request**

Draft PR to test a new port: SAIL.

- What does your PR fix? Fixes #
Adds a new port.

- Which triplets are supported/not supported? Have you updated the CI baseline?
Not sure.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

2020-12-04 02:01 UTC, NancyLi1013 requested changes

2020-12-04 02:01 UTC, NancyLi1013 commented on ports/sail/vcpkg.json
> +}
`libjpeg-turbo` is one of dependencies for `tiff`. So `tiff `might be enough here. Could you please help confirm this?

2020-12-04 06:56 UTC, smoked-herring commented on ports/sail/portfile.cmake
> +    HEAD_REF feature/vcpkg
`feature/vcpkg` is an experiment to add vcpkg support. When `feature/vcpkg` is ready, I'll merge it into the master, and update the port file as well as the PR.

2020-12-04 06:59 UTC, smoked-herring commented on ports/sail/vcpkg.json
> +}
I directly depend on `libjpeg-turbo` as well. That's why it's here.

2020-12-04 07:29 UTC, smoked-herring commented on ports/sail/portfile.cmake
> +vcpkg_fail_port_install(ON_TARGET "UWP" "OSX" "Linux")
You're absolutely right, SAIL supports OSX and Linux, but natively. I.e. w/o using vcpkg. I plan to extend vcpkg support for Linux/OSX later. For now, there are some compilation issues and vpkg peculiarities (due to static linking on Linux) that stop me from doing that.

2020-12-04 08:00 UTC, NancyLi1013 requested changes

2020-12-04 08:00 UTC, NancyLi1013 commented on scripts/ci.baseline.txt
> +sail:x64-windows-static=skip
Does the port not support static build? If so, you can add this in `Supports: !static`. For uwp, you can handle it in the same way.

2020-12-04 08:03 UTC, smoked-herring commented on ports/sail/portfile.cmake
> +vcpkg_fail_port_install(ON_TARGET "UWP" "OSX" "Linux")
I think not in this PR. In this PR I target Windows only.

2020-12-04 08:11 UTC, smoked-herring commented on ports/sail/portfile.cmake
> +file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/lib)
Oops, it looks like a mistake!

2020-12-04 08:20 UTC, smoked-herring commented on scripts/ci.baseline.txt
> +sail:x64-windows-static=skip
Thanks! I'll commit a fix.

2020-12-04 14:46 UTC, smoked-herring commented
Updated REF to master. I think it's ready for a review.

2020-12-08 06:42 UTC, smoked-herring commented
@NancyLi1013 Could you please review once more?

2020-12-10 08:25 UTC, NancyLi1013 commented
@smoked-herring 

Sorry for the delay.

I noticed that there are also some *.pc files in` lib/pkgconfig`. So it would be better to add` vcpkg_fixup_pkgconfig()`.

2020-12-10 09:49 UTC, smoked-herring commented
@NancyLi1013 

Thanks for the review!

>I noticed that there were also some *.pc files in lib/pkgconfig. So it would be better to add vcpkg_fixup_pkgconfig().

Added `vcpkg_fixup_pkgconfig()`.

>I also found that there were some *.info and *.dll files listed in bin/sail/codes. Do you know what these files are used for?

These are dynamically loaded codecs (plugins). They provide actual image decoding capabilities. Static build is not supported for now, so codecs are distributed as standalone DLL plugins.

>For the usage of sail, have you tested it?

Yes, there are demo apps. I tested all of them against the port, everything works fine. The only caveat is that a user needs to copy codecs (`bin/sail/codecs`) and their dependencies by hand into the application directory. I also added a `usage` file to inform the user about this peculiarity.

2020-12-11 01:30 UTC, NancyLi1013 approved these changes

2020-12-11 22:17 UTC, merged

2020-12-11 22:17 UTC, BillyONeal commented
Thanks for your contribution!