[vcpkg] Disable survey message
microsoft/vcpkg pull request #14954
Opened 2020-12-05 03:26 UTC by ras0219

We're retiring the in-tool survey for now. Thank you to everyone who responded!

2020-12-05 03:30 UTC, vicroms approved these changes

2020-12-06 23:26 UTC, BillyONeal requested changes
I don't think we should have checked in commented out code.

2020-12-08 19:13 UTC, BillyONeal approved these changes

2020-12-14 20:02 UTC, merged

2020-12-14 20:02 UTC, BillyONeal commented
Thanks! :D