[pcl] Fix build when librealsense2 is present
microsoft/vcpkg pull request #14960
Opened 2020-12-05 20:12 UTC by dweckmann

**Describe the pull request**

- What does your PR fix? 

When librealsens2 is installed, PCL want to build realsense2 grabber. The file `io/src/real_sense_2_grabber.cpp` miscompile and this patch fix it. (Upstream's master have the same modification)

- Which triplets are supported/not supported? Have you updated the CI baseline?

Should support everything, since the problem is present in `real_sense_2_grabber.cpp` and it is used in all triplets. However, the autodetection of librealsense is curious and this should be a feature that set a dependency to the librealsense2 package. Anyway, this patch will be still required, so it can be already applied. 

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Not sure, but it should.

2020-12-07 08:12 UTC, NancyLi1013 reviewed
Could you please update version in CONTROL file?

2020-12-07 08:27 UTC, dweckmann commented
@NancyLi1013 : You mean setting `Port-Version: 2` ? It should be good. Sorry for dumb question, I'm a newbie :-)

2020-12-09 06:01 UTC, NancyLi1013 requested changes

2020-12-09 06:01 UTC, NancyLi1013 commented on ports/pcl/CONTROL
> +Port-Version: 2
```suggestion
Port-Version: 1
```
This should be 1, since this is the first change for the version 1.11.1.

Please refer to this doc https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#port-version

2020-12-09 06:08 UTC, dweckmann commented on ports/pcl/CONTROL
> +Port-Version: 2
oh sorry, will do the change ASAP

2020-12-09 06:50 UTC, NancyLi1013 approved these changes

2020-12-09 06:51 UTC, NancyLi1013 commented
Have you tested these features included in this PR?

2020-12-09 07:44 UTC, dweckmann commented
> Have you tested these features included in this PR?

Well, I've tested that it builds and that I can integrate it into our project. We do not rely directly on librealsense2 inside PCL, but use both of them separately.

2020-12-09 07:47 UTC, NancyLi1013 commented
Thanks for your feedback. LGTM now.

2020-12-09 19:56 UTC, BillyONeal commented
Thanks for submitting upstream and your contribution here!

2020-12-09 19:56 UTC, merged