[ms-gltf] Add new port
microsoft/vcpkg pull request #14971
Opened 2020-12-06 17:01 UTC by luncliff

### Changes

New port for https://github.com/microsoft/glTF-SDK in Windows / MacOS platforms.

* https://github.com/microsoft/glTF-SDK/pull/66 updated required RapidJSON's version. So the code can be built with VcPkg now.  
* The `port-version` will be updated **when the new version is released**. (== Next of [`r1.9.5.0`](https://github.com/microsoft/glTF-SDK/releases))

#### What does your PR fix?

There was no port request for this.

#### Which triplets are supported/not supported? Have you updated the CI baseline?

Linux is not supported.  
ci.baseline.txt will be updated soon. 

#### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes!

2020-12-07 03:01 UTC, PhoebeHui commented
@luncliff, could you format the vcpkg.json file? See github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#manifest for solution.

2021-01-17 18:32 UTC, luncliff commented
@PhoebeHui, I was waiting for the next release of the library since last December but seems like it can take more than months... :(  
**The port's version is `r1.9.5.0` but the ref commit is not**. Can this be allowed? I'd like to hear opinions about it.  

In https://github.com/microsoft/glTF-SDK/pull/66, I update some build configurations and source code. Fortunately the project's TC passed, so I'd like to use the changes if possible.

2021-01-18 02:33 UTC, PhoebeHui requested changes
@luncliff, I think it's fine, we already have the comments about the ref commit,  we can update that with new release in future.

2021-01-18 02:33 UTC, PhoebeHui commented on scripts/ci.baseline.txt
> +ms-gltf:x64-linux=fail
Could you remove this in ci.baseline.txt, and add "supports":  "!linux" to vcpkg.json file?

2021-01-18 02:38 UTC, PhoebeHui commented on ports/ms-gltf/vcpkg.json
> +    },
Have you test this feature locally?

2021-01-18 02:45 UTC, luncliff commented on ports/ms-gltf/vcpkg.json
> +    },
I tested for `x64-windows` and `x86-windows`, but not for `x64-osx`. I will check the part again.

2021-01-18 02:46 UTC, luncliff commented on scripts/ci.baseline.txt
> +ms-gltf:x64-linux=fail
got it!

2021-01-22 05:38 UTC, PhoebeHui commented
All features test passed with x64-windows.

2021-01-22 05:39 UTC, PhoebeHui approved these changes

2021-01-23 10:54 UTC, luncliff commented
@PhoebeHui Appreciate the changes and testing. (Sadly, things didn't go well last week)

I added a small patch because of `<filesystem>` support in Mac OS (`x64-osx` triplets).
It basically adds 2 more changes.

* source: `_LIBCPP_NO_EXPERIMENTAL_DEPRECATION_WARNING_FILESYSTEM` when `__APPLE__`
  Like warning for `std::experimental::filesystem` in MS STL, headers in MacOS SDK reports the deprecation and it is considered error. The library is used only in samples so I placed a macro definition.
* cmake: `CMAKE_OSX_DEPLOYMENT_TARGET` to `10.15`.   
  This version allows use of `std::filesystem::path`.
  Normally it is fine with CMake configuration, but I found that ninja places the minimum osx version to `10.11`.

2021-01-25 02:44 UTC, PhoebeHui approved these changes

2021-01-25 09:53 UTC, dan-shaw approved these changes

2021-01-25 09:54 UTC, merged