[spatialite-tools]update to 5.0.0
microsoft/vcpkg pull request #15039
Opened 2020-12-10 07:55 UTC by longhuan2018

spatialite-tools update to 5.0.0
support linux and osx build

2020-12-10 08:58 UTC, longhuan2018 commented
Both libspatialite and spatialite-tools depend on librttopo，After librttopo PR#15037 is merged, I will merge the code again.

2020-12-22 02:38 UTC, JackBoosY requested changes

2020-12-22 02:38 UTC, JackBoosY commented on ports/spatialite-tools/portfile.cmake
> +  string(REPLACE "/" "\\\\" INST_DIR ${CURRENT_PACKAGES_DIR})
```suggestion
  file(TO_CMAKE_PATH "${CURRENT_PACKAGES_DIR}" INST_DIR)
```

2020-12-22 02:38 UTC, JackBoosY commented on ports/spatialite-tools/portfile.cmake
> +  file(REMOVE ${EXES})
Can you use `vcpkg_copy_tools` instead?

2020-12-22 02:38 UTC, JackBoosY commented on ports/spatialite-tools/portfile.cmake
> +  file(REMOVE ${DEBUG_EXES})
Same as above.

2020-12-22 02:38 UTC, JackBoosY commented on ports/spatialite-tools/portfile.cmake
> +  vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug)
By using `vcpkg_copy_tools`, we don't need this.

2020-12-22 02:52 UTC, longhuan2018 commented on ports/spatialite-tools/portfile.cmake
> +  string(REPLACE "/" "\\\\" INST_DIR ${CURRENT_PACKAGES_DIR})
The mkdir and copy commands are used in makefile.vc, but if the path contains'/' instead of'\\', it will report an error "The syntax of the command is incorrect.". How can I solve this problem?
```
install: all
	-mkdir $(INSTDIR)
	-mkdir $(INSTDIR)\bin
	copy *.exe $(INSTDIR)\bin
```

2020-12-22 03:00 UTC, longhuan2018 commented on ports/spatialite-tools/portfile.cmake
> +  string(REPLACE "/" "\\\\" INST_DIR ${CURRENT_PACKAGES_DIR})
file(TO_NATIVE_PATH "${CURRENT_PACKAGES_DIR}" INST_DIR)   Can meet my needs

2020-12-22 03:06 UTC, JackBoosY commented on ports/spatialite-tools/portfile.cmake
> +  string(REPLACE "/" "\\\\" INST_DIR ${CURRENT_PACKAGES_DIR})
Oh sorry, should be `TO_NATIVE_PATH`.

2020-12-22 03:08 UTC, JackBoosY approved these changes

2020-12-22 03:09 UTC, JackBoosY commented
LGTM.

2020-12-23 07:21 UTC, merged

2020-12-23 07:21 UTC, BillyONeal commented
Thank you for the help!