[readosm]update to 1.1.0a
microsoft/vcpkg pull request #15038
Opened 2020-12-10 07:44 UTC by longhuan2018

update to 1.1.0a
support linux and osx build

2020-12-10 08:55 UTC, longhuan2018 commented
The detection failure is caused by spatialite-tools. I fixed this port in PR #15039. I don’t know if I need to block the linux and osx compilation of spatialite-tools in this PR.

2020-12-10 10:38 UTC, PhoebeHui commented
@longhuan2018, after PR #15039 merged, I will rerun the CI testing, so you don't need to block them in this PR.

2020-12-10 10:45 UTC, PhoebeHui requested changes
Thanks for your contribution!

Could you please exported the cmake config and targets file instead?

2020-12-10 10:45 UTC, PhoebeHui commented on ports/readosm/vcpkg-cmake-wrapper.cmake
> +set(READOSM_LIBRARIES ${READOSM_LIBRARY})
Quoth @ras0219 "vcpkg_cmake_wrapper" should only be used when we are overriding the behavior of a shipped-with-CMake find_library module, but "FindReadosm" is not a built in cmake module. We should patch the build system in question to install(EXPORT the bits someone wants instead.

2020-12-11 01:24 UTC, longhuan2018 commented on ports/readosm/vcpkg-cmake-wrapper.cmake
> +set(READOSM_LIBRARIES ${READOSM_LIBRARY})
The library is not built using cmake, so. . .
The practice of usage and vcpkg-cmake-wrapper.cmake, I refer to the GDAL port, no one needs to use readosm through cmake yet, I think I should delete these two files?

2020-12-11 02:31 UTC, PhoebeHui commented on ports/readosm/vcpkg-cmake-wrapper.cmake
> +set(READOSM_LIBRARIES ${READOSM_LIBRARY})
Yes, please remove them.

2020-12-11 02:59 UTC, longhuan2018 commented
Do I need to add spatialite-tools to ci.baseline.txt first to exclude its compilation in linux and osx? Because the current version of the spatialite-tools port only supports windows. @PhoebeHui

2020-12-11 03:03 UTC, PhoebeHui commented
@longhuan2018, since you have fixed it by PR #15039, so this is not required, I will rerun the CI testing after the PR merged.

2020-12-11 03:07 UTC, longhuan2018 commented
But spatialite-tools is dependent on readosm. If this PR fails, then it cannot be compiled.

2020-12-11 03:17 UTC, PhoebeHui commented
@longhuan2018, I think you should update the 2 ports togather, then the CI would test the changes and catch the regressions.

2020-12-11 03:35 UTC, longhuan2018 commented
This is what I split from PR #14951, CI has been verified

2020-12-11 05:58 UTC, PhoebeHui commented
@longhuan2018, that's fine, you can enable the spatialite-tools in PR https://github.com/microsoft/vcpkg/pull/15039 after this PR merged.

2020-12-11 06:05 UTC, PhoebeHui approved these changes
Thanks for your contribution!

2020-12-12 00:58 UTC, BillyONeal commented on ports/readosm/portfile.cmake
> +    "${CURRENT_INSTALLED_DIR}/debug/lib/zlibd.lib kernel32.lib windowsapp.lib \
kernel32.lib windowsapp.lib doesn't make sense: the former is for desktop targeting, the latter is for OneCore or App targeting, and they provide the same APIs from different export surfaces. What made this change necessary?

2020-12-12 00:58 UTC, BillyONeal commented on ports/readosm/portfile.cmake
> +    "LINK_FLAGS=/APPCONTAINER" "INST_DIR=${INST_DIR}" "CL_FLAGS=${CL_FLAGS_REL}" "LIBS_ALL=${LIBS_ALL_REL}"
Appcontainer should probably only be set for _uwp triplets?

2020-12-12 00:58 UTC, BillyONeal commented on scripts/ci.baseline.txt
> +spatialite-tools:x64-osx=skip
```suggestion
spatialite-tools:x64-linux=fail
spatialite-tools:x64-osx=fail
```

2020-12-14 03:00 UTC, longhuan2018 commented on ports/readosm/portfile.cmake
> +    "LINK_FLAGS=/APPCONTAINER" "INST_DIR=${INST_DIR}" "CL_FLAGS=${CL_FLAGS_REL}" "LIBS_ALL=${LIBS_ALL_REL}"
I added VCPKG_TARGET_IS_UWP to check whether it is a uwp environment

2020-12-14 03:01 UTC, longhuan2018 commented on ports/readosm/portfile.cmake
> +    "${CURRENT_INSTALLED_DIR}/debug/lib/zlibd.lib kernel32.lib windowsapp.lib \
Windowsapp.lib must be added under UWP, otherwise it will fail to compile, I deleted kernel32.lib, it is not necessary

2020-12-17 08:14 UTC, merged

2020-12-17 08:14 UTC, BillyONeal commented
Thanks!