[libspatialite ]Update 5.0.0
microsoft/vcpkg pull request #15040
Opened 2020-12-10 08:51 UTC by longhuan2018

update libspatialite to 5.0.0

2020-12-10 08:59 UTC, longhuan2018 commented
Both libspatialite and spatialite-tools depend on librttopo，After librttopo PR#15037 is merged, I will merge the code again.

2020-12-19 05:46 UTC, longhuan2018 commented
The modification of spatialite-tools is to make this PR static library compile without error, it will be updated in another PR #15039

2020-12-19 05:50 UTC, longhuan2018 commented
@JackBoosY Can anyone review this PR？

2020-12-21 02:27 UTC, JackBoosY requested changes

2020-12-21 02:27 UTC, JackBoosY commented on ports/libspatialite/fix-latin-literals.patch
> ++    p = add_epsg_def(filter,first,last,187918,"mj10777.de",187918,u8"DHDN / Soldner 18 M\u00fcggelberg 600");
Should this report to the upstream?

2020-12-21 02:27 UTC, JackBoosY commented on ports/libspatialite/fix-makefiles.patch
> ++OPTFLAGS=	/nologo /fp:precise /W4 $(CL_FLAGS) /D_CRT_SECURE_NO_WARNINGS \
I think we should use `W3` instead.

2020-12-21 07:29 UTC, longhuan2018 commented on ports/libspatialite/fix-latin-literals.patch
> ++    p = add_epsg_def(filter,first,last,187918,"mj10777.de",187918,u8"DHDN / Soldner 18 M\u00fcggelberg 600");
I kept the file fix-latin-literals.patch from the previous version. I tried to delete it and found that the compilation was normal. Maybe it is not a necessary option now. So I deleted it.

2020-12-21 07:30 UTC, longhuan2018 commented on ports/libspatialite/fix-makefiles.patch
> ++OPTFLAGS=	/nologo /fp:precise /W4 $(CL_FLAGS) /D_CRT_SECURE_NO_WARNINGS \
W3 is changed to W4 in upstream, so I keep it consistent

2020-12-21 07:37 UTC, JackBoosY approved these changes

2020-12-21 07:40 UTC, JackBoosY requested changes
This port installed the pkgconfig file on non-Windows, so I think we should add `vcpkg_fixup_pkgconfig()` after `vcpkg_install_make` when building non-Windows.

2020-12-21 08:20 UTC, JackBoosY approved these changes

2020-12-21 16:56 UTC, vicroms approved these changes

2020-12-21 16:56 UTC, merged

2020-12-21 16:56 UTC, vicroms commented
Thanks for the PR!

2021-01-19 08:37 UTC, JackBoosY commented
@longhuan2018  Hi, yesterday I got a regression about `spatialite-tools`:
```
/home/usr/work/vcpkg/installed/x64-linux/debug/lib/libspatialite.a(lwn_network.o): In function `geo_link_split':
lwn_network.c:(.text+0x26e7): undefined reference to `ptarray_construct'
lwn_network.c:(.text+0x2791): undefined reference to `ptarray_set_point4d'
lwn_network.c:(.text+0x27d2): undefined reference to `rtline_construct'
lwn_network.c:(.text+0x27fc): undefined reference to `ptarray_construct'
lwn_network.c:(.text+0x2860): undefined reference to `ptarray_set_point4d'
lwn_network.c:(.text+0x2884): undefined reference to `rtpoint_construct'
...
```
This seems to be caused by libspatialite using **postgis** when building, but not adding the postgis library to the link list when building spatialite-tools.
But I did not find the postgis library in the build logs of libspatialite.
Do you have any ideas?

2021-01-19 08:47 UTC, longhuan2018 commented
> @longhuan2018 Hi, yesterday I got a regression about :`spatialite-tools`
> 
> ```
> /home/usr/work/vcpkg/installed/x64-linux/debug/lib/libspatialite.a(lwn_network.o): In function `geo_link_split':
> lwn_network.c:(.text+0x26e7): undefined reference to `ptarray_construct'
> lwn_network.c:(.text+0x2791): undefined reference to `ptarray_set_point4d'
> lwn_network.c:(.text+0x27d2): undefined reference to `rtline_construct'
> lwn_network.c:(.text+0x27fc): undefined reference to `ptarray_construct'
> lwn_network.c:(.text+0x2860): undefined reference to `ptarray_set_point4d'
> lwn_network.c:(.text+0x2884): undefined reference to `rtpoint_construct'
> ...
> ```
> 
> This seems to be caused by libspatialite using **postgis** when building, but not adding the postgis library to the link list when building spatialite-tools.
> But I did not find the postgis library in the build logs of libspatialite.
> Do you have any ideas?
> 
> Note the symbols are belong to postgis instead of geos. See [documentation](https://www.postgis.net/docs/doxygen/2.4/da/de7/liblwgeom_8h_a6967ac4744c94dc2cbbf9e43d0ae9d66.html).

Now libspatialite depends on librttopo, so if libspatialite is statically linked, librttopo also needs to be linked

2021-01-19 08:55 UTC, longhuan2018 commented
How can I reproduce this compilation error? Do need to download the latest vcpkg?

2021-01-19 09:09 UTC, JackBoosY commented
@longhuan2018  Yes, do you have linux machine? Just install `spatialite-tools:x64-linux` can repro this issue.

2021-01-19 09:11 UTC, longhuan2018 commented
> @longhuan2018 Yes, do you have linux machine? Just install `spatialite-tools:x64-linux` can repro this issue.
OK, I'll try first

2021-01-19 09:18 UTC, JackBoosY commented
@longhuan2018 Note #15746 trying to disable `spatialite-tools` results in pipeline test, so if your PR can successfully fix this regression, please leave a message in #15746 to close that PR.

2021-01-19 09:19 UTC, longhuan2018 commented
ok