[breakpad] Support breakpad_client on Linux & macOS
microsoft/vcpkg pull request #15092
Opened 2020-12-13 15:30 UTC by Perlmint

Support breakpad_client on Linux & macOS

Tested on macOS Big Sur and Ubuntu 20.04 docker on macOS.

2020-12-14 03:03 UTC, JackBoosY requested changes

2020-12-14 03:03 UTC, JackBoosY commented on ports/breakpad/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL Linux)
Is this for Linux and OSX?

2020-12-14 03:07 UTC, Perlmint commented on ports/breakpad/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL Linux)
This part is required for only Linux, not OSX.

2020-12-14 03:10 UTC, JackBoosY requested changes

2020-12-14 03:10 UTC, JackBoosY commented on ports/breakpad/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL Linux)
```suggestion
if(VCPKG_HOST_IS_LINUX)
```

2020-12-14 05:58 UTC, JackBoosY approved these changes

2020-12-14 05:59 UTC, JackBoosY commented
/azp run

2020-12-14 06:30 UTC, JackBoosY commented
What's going on with the license check?

2020-12-14 06:31 UTC, JackBoosY commented
@Perlmint Can you re-sign the CLA please?

2020-12-14 06:35 UTC, Perlmint commented
> @Perlmint Can you re-sign the CLA please?

I just opened the https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=15092. But, there is no submit/sign button. How can I re-sign the CLA?

2020-12-14 06:48 UTC, JackBoosY commented
Hmm... @BillyONeal can you please take a look?

2020-12-15 00:26 UTC, BillyONeal commented on ports/breakpad/CMakeLists.txt
> +            DIRECTORY src/third_party/lss
This is a bit... suspect. Is lss an embedded/vendored third party library? Why are customers expected to `#include <third_party/anything>` ?

2020-12-15 02:30 UTC, Perlmint commented on ports/breakpad/CMakeLists.txt
> +            DIRECTORY src/third_party/lss
They are not included manually. But, Headers - should be included to use breakpad_client - include they as `third_party/*`.

Below is an error message from my test project without installing headers in `third_party/lss`.

```
In file included from /ws/installed/x64-linux/include/client/linux/dump_writer_common/thread_info.h:37,
                from /ws/installed/x64-linux/include/client/linux/minidump_writer/linux_dumper.h:54,
                from /ws/installed/x64-linux/include/client/linux/minidump_writer/minidump_writer.h:42,
                from /ws/installed/x64-linux/include/client/linux/handler/exception_handler.h:42,
                from /ws/test_proj/MinidumpHandler.cpp:12:
/ws/installed/x64-linux/include/common/memory_allocator.h:50:10: fatal error: third_party/lss/linux_syscall_support.h: No such file or directory
   50 | #include "third_party/lss/linux_syscall_support.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2020-12-15 23:57 UTC, BillyONeal commented on ports/breakpad/CMakeLists.txt
> +            DIRECTORY src/third_party/lss
Hmmm sounds OK.

2020-12-17 08:16 UTC, merged

2020-12-17 08:16 UTC, BillyONeal commented
Thanks for your contribution!