[coin] x64-windows-statid-md fixes
microsoft/vcpkg pull request #15125
Opened 2020-12-15 07:40 UTC by ankurverma85

Fix the coin port to build with x64-windows-static-md

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-12-15 09:24 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-12-16 01:09 UTC, ankurverma85 commented
> Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

Done. Please review and merge

2020-12-16 02:39 UTC, JackBoosY requested changes

2020-12-16 02:39 UTC, JackBoosY commented on ports/coin/portfile.cmake
> +endif()
You can see above that `COIN_BUILD_MSVC_STATIC_RUNTIME` has been changed, maybe you need to delete them from the judgment of `VCPKG_LIBRARY_LINKAGE`?

2020-12-16 06:44 UTC, ankurverma85 commented on ports/coin/portfile.cmake
> +endif()
Yes. Thanks for highlighting

2020-12-16 07:57 UTC, JackBoosY approved these changes

2020-12-17 08:15 UTC, merged

2020-12-17 08:15 UTC, BillyONeal commented
Thanks for your contribution!