iphlpapi.lib is required when building static lib on windows
microsoft/vcpkg pull request #15121
Opened 2020-12-15 07:20 UTC by gennesseaux

iphlpapi.lib is required when building static lib on windows

2020-12-15 10:02 UTC, NancyLi1013 requested changes

2020-12-15 10:02 UTC, NancyLi1013 commented on ports/poco/fix_foundation_link.patch
> +
Could you please also check the format for this patch? Is it LF?

2020-12-15 10:02 UTC, NancyLi1013 commented on ports/poco/portfile.cmake
> +        #
```suggestion
```
Please remove this commnet.

2020-12-15 10:02 UTC, NancyLi1013 commented
Have you tested these features in this PR?

2020-12-15 16:39 UTC, gennesseaux commented on ports/poco/arm64_pcre.patch
> + #include "Poco/Exception.h"
This one is `LF` not `CRLF`

2020-12-15 16:39 UTC, gennesseaux commented on ports/poco/fix_foundation_link.patch
> +
done

2020-12-15 16:40 UTC, gennesseaux commented on ports/poco/portfile.cmake
> +        #
Added comment

2020-12-15 16:43 UTC, gennesseaux commented
Previous versions of Poco used to work on windows when building static lib.
I've updated this PR because I couldn't compile anymore and this solved my issue.

2020-12-21 09:34 UTC, NancyLi1013 approved these changes

2020-12-21 09:40 UTC, NancyLi1013 commented
> Have you tested these features in this PR?

I mean if you have tested these features included this PR.  Please check if `vcpkg install poco[mysql, mariadb, postgresql, sqlite3, nettle, pdf]` can work on `x86-windows` and `x64-windows-static`.

2021-01-19 12:17 UTC, gennesseaux commented
> > Have you tested these features in this PR?
> 
> I mean if you have tested these features included this PR. Please check if `vcpkg install poco[mysql, mariadb, postgresql, sqlite3, nettle, pdf]` can work on `x86-windows` and `x64-windows-static`.

Done. everything works fine for me

2021-03-04 06:47 UTC, NancyLi1013 commented
/azp run

2021-03-04 08:36 UTC, NancyLi1013 commented
```
Error: While reading versions for port poco from file: C:\a\1\s\versions\p-\poco.json
       Version `1.10.1#4` was not found in versions file.
       Run:

           vcpkg x-add-version poco

       to add the new port version.
```

@gennesseaux 

Sorry for the long delay.
Could you please run  `vcpkg x-add-version poco` and then submit the changes for versions to solve the failure on x86-windows?

2021-03-04 08:39 UTC, NancyLi1013 requested changes

2021-03-04 08:39 UTC, NancyLi1013 commented on ports/poco/arm64_pcre.patch
> + #include "Poco/Exception.h"
Sorry for the wrong comment. In order to make it more clear to review the changes, we suggest to use the original format of the patch. So would you like to update this patch?

2021-03-30 01:12 UTC, NancyLi1013 commented
Hi @gennesseaux 

Could you please resolve the conflicts?

2021-04-23 06:03 UTC, NancyLi1013 commented
Is work still being done for this PR @gennesseaux?

2021-05-25 10:07 UTC, NancyLi1013 commented
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

2021-05-25 10:07 UTC, closed without merging