[magnum,magnum-plugins] Add vulkan and shaderconverter features
microsoft/vcpkg pull request #15163
Opened 2020-12-16 14:04 UTC by Squareys

Hi all!

This PR adds a few new features available in magnum HEAD.

Best,
Jonathan

(As per usual, @mosra will quickly review and approve from his side.)

2020-12-16 14:49 UTC, mosra approved these changes

2020-12-17 02:49 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-12-18 10:22 UTC, Squareys commented
@JackBoosY Sorry about that! Fixed.

2020-12-19 08:08 UTC, Squareys commented
@JackBoosY Ready to be merged! :)

2020-12-20 04:46 UTC, JackBoosY commented
Did you test all features?

2020-12-20 04:47 UTC, JackBoosY requested changes

2020-12-20 04:47 UTC, JackBoosY commented on ports/magnum-plugins/portfile.cmake
> +    list(REMOVE_ITEM ALL_SUPPORTED_FEATURES glslangshaderconverter spirvtoolsshaderconverter)
Should add a warning message here.

2020-12-20 04:47 UTC, JackBoosY commented on ports/magnum/portfile.cmake
> +    list(REMOVE_ITEM ALL_SUPPORTED_FEATURES anyshaderconverter shadertools shaderconverter
See below.

2020-12-21 11:59 UTC, Squareys commented on ports/magnum-plugins/portfile.cmake
> +    list(REMOVE_ITEM ALL_SUPPORTED_FEATURES glslangshaderconverter spirvtoolsshaderconverter)
But I assume only in case the user selected these features, right?

2020-12-22 01:46 UTC, JackBoosY commented on ports/magnum-plugins/portfile.cmake
> +    list(REMOVE_ITEM ALL_SUPPORTED_FEATURES glslangshaderconverter spirvtoolsshaderconverter)
Yes, but this does not mean that the user has indeed selected all features.
So my suggestion is add a warning message like `message(WARNING "Feature glslangshaderconverter spirvtoolsshaderconverter are not avaliable when building non-head version.")`.

2021-01-25 16:00 UTC, Squareys commented on ports/magnum-plugins/portfile.cmake
> +    list(REMOVE_ITEM ALL_SUPPORTED_FEATURES glslangshaderconverter spirvtoolsshaderconverter)
Sorry for the long delay! I implemented this warning. It will be emitted regardless whether the user selected the features.

2021-01-26 03:06 UTC, JackBoosY approved these changes

2021-01-26 03:06 UTC, JackBoosY commented
Need test all features.

2021-01-26 07:07 UTC, JackBoosY commented
Test all features succesfully on `x86-windows` and `x64-windows-static`.

2021-01-26 23:03 UTC, merged