[gloo] New Port
microsoft/vcpkg pull request #15219
Opened 2020-12-19 23:33 UTC by jacobkahn

Add a port for [gloo](https://github.com/facebookincubator/gloo).

cc @xw285cornell, @mrshenli, @pbelevich, @osalpekar

cc @syhw, @padentomasello, @tlikhomanenko, @vineelpratap, @xuqiantong, @avidov

- Which triplets are supported/not supported? Have you updated the CI baseline?

`x64-linux`, which I've tested. I'm can't tell if there's windows support at this time -- the docs suggest no, but a project maintainer might be able to help me out here. I don't have the means to test it.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-12-23 09:13 UTC, PhoebeHui requested changes
thanks for your contribution! 

Could you add the homepage in vcpkg.json file?

2020-12-23 09:15 UTC, PhoebeHui requested changes

2020-12-23 09:15 UTC, PhoebeHui commented on ports/gloo/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/gloo RENAME copyright)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

2020-12-23 10:26 UTC, PhoebeHui commented on ports/gloo/vcpkg.json
> +  "features": {
Have you test the 3 features with x64-linux?

2020-12-23 22:10 UTC, jacobkahn commented on ports/gloo/vcpkg.json
> +  "features": {
Yes, I've tested all of the features individually on `x64-linux`.

2020-12-23 22:11 UTC, jacobkahn commented
One odd thing I can't make work for this port - the contents of `usage` don't print when installing. I always see
```
Elapsed time for package gloo:x64-linux: 6.536 s

Total elapsed time: 6.828 s

The package gloo:x64-linux provides CMake targets:

    find_package(Gloo CONFIG REQUIRED)
    target_link_libraries(main PRIVATE gloo)
```
which seems to be some sort of default. Since the library doesn't provide any imported targets or a config module, I wrote a CMake wrapper which is also in this commit, but I wanted to make the proper usage show up accordingly. @PhoebeHui any idea what I'm doing wrong?

2020-12-24 06:47 UTC, PhoebeHui requested changes
@jacobkahn, I noticed gloo provided cmake config and targets file, so you don't need to add the FindGloo.cmake, wrapper and usage file, could you remove them?

 BTW, You may need use vcpkg_fixup_cmake_targets to fix up the targets file.

See https://github.com/facebookincubator/gloo/tree/master/cmake 
https://github.com/facebookincubator/gloo/blob/master/CMakeLists.txt#L129

2020-12-24 15:15 UTC, jacobkahn commented
@PhoebeHui — I didn't even notice that, good catch 👍 

Removed the usage, updated, the port, and added `vcpkg_fixup_cmake_targets` - things seem to be correct now

2020-12-25 07:02 UTC, PhoebeHui approved these changes
LGTM, thanks for your updates!

2020-12-27 06:38 UTC, BillyONeal commented on ports/gloo/portfile.cmake
> +  list(APPEND GLOO_FEATURE_OPTIONS "-DUSE_CUDA=1 -DUSE_NCCL=1")
```suggestion
  list(APPEND GLOO_FEATURE_OPTIONS "-DUSE_CUDA=1" "-DUSE_NCCL=1")
```

I'm pretty sure you want these to be separate list entries?

2020-12-27 14:48 UTC, jacobkahn commented on ports/gloo/portfile.cmake
> +  list(APPEND GLOO_FEATURE_OPTIONS "-DUSE_CUDA=1 -DUSE_NCCL=1")
Thanks

2020-12-28 20:25 UTC, merged

2020-12-28 20:25 UTC, BillyONeal commented
Thanks for your help!