Updated directxtk et al for cmake package support
microsoft/vcpkg pull request #15210
Opened 2020-12-19 05:17 UTC by walbourn

The CMake support for directxtk, directxtk12, directxmesh, directxtex, and uvatlas has been updated to include cmake package 'installation'. This PR updates the vcpkg references to those versions for a much improved cmake vcpkg experience.

* ``BUILD_TOOLS`` build option added to control the building of Win32 command-line tools. This makes the UWP/ARM64 scenarios much easier and properly supports installation.

* In most cases, the vcpkg port now fetches the digitally signed version of my command-line tools for all configs from GitHub.

* I preserved the support for the 'openexr' feature in DirectXTex, with the required CMakeLists.txt support in the mainline.

* uvatlas was updated to use cmake build instead of msbuild

2020-12-19 05:19 UTC, walbourn commented on ports/directxmesh/CONTROL
> +Version: nov2020b
No source changes for directxtk, directxtk12, directxtex, or directxmesh. Just updates to cmake linked to this tag.

uvatlas was updated to the [latest release](https://github.com/microsoft/UVAtlas/releases/tag/dec2020)

2020-12-19 05:21 UTC, walbourn commented on ports/directxtex/enable_openexr_support.patch
> -diff --git a/CMakeLists.txt b/CMakeLists.txt
These changes are now in the [mainline](https://github.com/microsoft/DirectXTex/commit/6163ec1dccf95a6c33c48191b7b3395c9e790332) to make this more maintainable.

2020-12-19 05:21 UTC, walbourn commented on ports/directxtex/portfile.cmake
> +if("openexr" IN_LIST FEATURES)
I only build the texassemble.exe, texconv.exe, and texdiag.exe tools locally if using the "openexr" feature. Otherwise, better to use the digitally signed copies I posted to GitHub.

2020-12-19 05:53 UTC, walbourn commented on ports/uvatlas/portfile.cmake
> -vcpkg_fail_port_install(ON_TARGET "OSX" "Linux")
I was debating keeping this and on add this to the other four packages... Most of DirectXTex, DIrectXMesh, and UVAtlas could be built on non-MSFT platforms, but would require some surgery to do that. DirectXTK/DirectXTK12 require DirectX.

2020-12-19 07:13 UTC, walbourn commented
Test built all five libraries with the following triplets (which are all fully supported scenarios for these libraries):

* x86-windows
* x64-windows
* arm64-windows

* x86-uwp
* x64-uwp
* arm-uwp
* arm64-uwp

2020-12-19 07:26 UTC, walbourn commented on ports/uvatlas/portfile.cmake
> -vcpkg_fail_port_install(ON_TARGET "OSX" "Linux")
I'm going to add ``vcpkg_fail_port_install(ON_TARGET "OSX" "Linux")`` to directxtk, directxtk12 for sure as they require DirectX to be any use at all.

2020-12-19 22:05 UTC, walbourn commented on ports/directxmath/portfile.cmake
> +vcpkg_install_cmake()
No call to ``vcpkg_build_cmake`` because it's an all inline C++ header only library. There's nothing to build.

2020-12-20 01:25 UTC, walbourn commented on scripts/ci.baseline.txt
> +directxmath:x64-linux=fail
In theory DirectXMath should build for these scenarios with clang/LLVM, but it depends on which version of the toolset and what intrinsics are enabled.

2020-12-21 02:54 UTC, JackBoosY requested changes

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxmesh/portfile.cmake
> +
```suggestion
```

Since you have already called `vcpkg_install_cmake`, we should not call `vcpkg_build_cmake` again.

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
Is this binary 32-bit or 64-bit?

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtex/portfile.cmake
```suggestion
```
See above.

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtex/portfile.cmake
> +    FILENAME "texdiag.exe"
See above.

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtk/portfile.cmake
> +
```suggestion
```

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtk/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXTK/releases/download/nov2020/MakeSpriteFont.exe"
See above.

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtk/portfile.cmake
> +    FILENAME "xwbtool.exe"
Same as above.

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtk12/portfile.cmake
```suggestion
```

2020-12-21 02:54 UTC, JackBoosY commented on ports/directxtk12/portfile.cmake
> +    FILENAME "xwbtool.exe"
Same as above.

2020-12-21 02:54 UTC, JackBoosY commented on ports/uvatlas/portfile.cmake
> +
```suggestion
```

2020-12-21 02:54 UTC, JackBoosY commented on ports/uvatlas/portfile.cmake
> +    URLS "https://github.com/Microsoft/UVAtlas/releases/download/dec2020/uvatlastool.exe"
Same as above.

2020-12-21 02:54 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +directxmath:x64-linux=fail
Can you please add a comment here?

2020-12-21 03:21 UTC, walbourn commented on scripts/ci.baseline.txt
> +directxmath:x64-linux=fail
Added

2020-12-21 20:53 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
I just build 64-bit native binaries since these are development only tools.

2020-12-21 20:57 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
Ideally I'd be able to guard this based on the HOST architecture rather than the target. Is there a test for that?

2020-12-21 21:03 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
I could use ``VCPKG_TARGET_IS_WINDOW`` for now...

2020-12-21 21:05 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
Ah, now we are getting somewhere. ``VCPKG_HOST_IS_WINDOWS``!

2020-12-21 21:07 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +
Thanks for the feedback. Fixed.

2020-12-21 21:07 UTC, walbourn commented on ports/directxtex/portfile.cmake
Thanks for the feedback. Fixed.

2020-12-21 21:15 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
There doesn't seem to be a "VCPKG_HOST_IS_WINDOWS_X64" or "VCPKG_HOST_ARCHITECTURE" variable I can use, so I went with ``VCPKG_HOST_IS_WINDOWS`` for the downloads of all my tool EXEs. These are development-time tools, and basically all developers are using x64 native as their dev machine anyhow. This test does avoid downloading the EXEs for non-Win32 platforms since they won't work there.

2020-12-22 02:11 UTC, JackBoosY commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
> and basically all developers are using x64 native as their dev machine anyhow

That's not correct, we need to ensure the availability of tools on x86-windows.

2020-12-22 02:23 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
It depends on how you define developers. In games everyone uses x64 native toolsets due to code size.

I'm all for supporting x86 as target. The old port failed to install any tools for UWP.

I need a way to see if the host supports x64. Do you have one?

2020-12-22 02:26 UTC, JackBoosY commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
@walbourn Currently no... Instead of that, we can always download the x86 executables to solve this.

2020-12-22 02:28 UTC, JackBoosY commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
On the other hand, if users want to build x64-windows, their system will always be 64-bit.

2020-12-22 02:54 UTC, walbourn commented on ports/directxmesh/portfile.cmake
> +    URLS "https://github.com/Microsoft/DirectXMesh/releases/download/nov2020/meshconvert.exe"
By design I don't have 32-bit versions of executables to download. I'm not sure where the data is coming from that indicates to you that native developers use 32-bit (x86) versions of Windows for their development machines, but it's the exactly opposite for native game development.

In any case, I'll see what I can do to satisfy this ask to unblock this PR.

2020-12-22 05:04 UTC, walbourn commented on ports/uvatlas/portfile.cmake
> -vcpkg_fail_port_install(ON_TARGET "OSX" "Linux")
For now I'm adding ``vcpkg_fail_port_install(ON_TARGET "OSX" "Linux")`` to directxtk, directxtk12, directxmesh, directxtex, and uvatlas. directxmath installs fine for linux.

In future, with directxmath and directx-headers in vcpkg, I should be able to make at least directxmesh, uvatlas build for linux. directxtex will require some work to remove WIC. Not a requirement now.

2020-12-22 05:35 UTC, JackBoosY approved these changes

2020-12-22 05:39 UTC, JackBoosY commented
directxmesh:
```
     5>D:\buildtrees\directxmesh\src\nov2020b-509e5fd905.clean\Meshconvert\Mesh.cpp(1067,36): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxmesh\arm-uwp-dbg\meshconvert.vcxproj]
     5>D:\buildtrees\directxmesh\src\nov2020b-509e5fd905.clean\Meshconvert\Mesh.cpp(1111,36): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxmesh\arm-uwp-dbg\meshconvert.vcxproj]
     5>D:\buildtrees\directxmesh\src\nov2020b-509e5fd905.clean\Meshconvert\Mesh.cpp(1472,36): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxmesh\arm-uwp-dbg\meshconvert.vcxproj]
     5>D:\buildtrees\directxmesh\src\nov2020b-509e5fd905.clean\Meshconvert\Mesh.cpp(2254,36): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxmesh\arm-uwp-dbg\meshconvert.vcxproj]
```

directxtex:
```
     6>D:\buildtrees\directxtex\src\nov2020b-5aa3ddc968.clean\Texconv\ExtendedBMP.cpp(49,40): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxtex\arm-uwp-dbg\texconv.vcxproj]
     6>D:\buildtrees\directxtex\src\nov2020b-5aa3ddc968.clean\Texconv\PortablePixMap.cpp(85,40): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxtex\arm-uwp-dbg\texconv.vcxproj]
     6>D:\buildtrees\directxtex\src\nov2020b-5aa3ddc968.clean\Texconv\ExtendedBMP.cpp(108,28): error C2065: 'BITMAPFILEHEADER': undeclared identifier [D:\buildtrees\directxtex\arm-uwp-dbg\texconv.vcxproj]
...
```

directxtk:
```
     5>D:\buildtrees\directxtk\src\nov2020b-09af77c7d2.clean\XWBTool\xwbtool.cpp(1423,68): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\buildtrees\directxtk\arm-uwp-dbg\xwbtool.vcxproj]
     5>D:\buildtrees\directxtk\src\nov2020b-09af77c7d2.clean\XWBTool\xwbtool.cpp(1423,52): error C2146: syntax error: missing '>' before identifier 'ADPCMEWAVEFORMAT' [D:\buildtrees\directxtk\arm-uwp-dbg\xwbtool.vcxproj]
     5>D:\buildtrees\directxtk\src\nov2020b-09af77c7d2.clean\XWBTool\xwbtool.cpp(1424,33): error C3536: 'adpcmFmt': cannot be used before it is initialized [D:\buildtrees\directxtk\arm-uwp-dbg\xwbtool.vcxproj]
     5>D:\buildtrees\directxtk\src\nov2020b-09af77c7d2.clean\XWBTool\xwbtool.cpp(1507,29): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\directxtk\arm-uwp-dbg\xwbtool.vcxproj]
```

I think that's by design, please add `Supports: !uwp` to these port's _CONTROL_ file.

2020-12-22 05:45 UTC, walbourn commented
Am I using the wrong test here?

```
if(NOT VCPKG_TARGET_IS_UWP)
  set(FEATURE_OPTIONS ${FEATURE_OPTIONS} -DBUILD_TOOLS=ON)
elseif()
  set(FEATURE_OPTIONS ${FEATURE_OPTIONS} -DBUILD_TOOLS=OFF)
endif()
```

2020-12-22 05:52 UTC, JackBoosY commented
@walbourn The regressions are on arm / uwp triplets.

2020-12-22 05:53 UTC, JackBoosY commented
You can get the failure log [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=46854&view=artifacts&pathAsName=false&type=publishedArtifacts).

2020-12-22 06:03 UTC, walbourn commented
For some reason, I have to use:

```
if(VCPKG_TARGET_IS_UWP)
  set(EXTRA_OPTIONS -DBUILD_TOOLS=OFF)
else()
  set(EXTRA_OPTIONS -DBUILD_TOOLS=ON)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS} ${EXTRA_OPTIONS}
)
```

instead of adding to ``FEATURE_OPTIONS`` directly...

2020-12-22 06:20 UTC, JackBoosY commented
I will help you to look at this later.

2020-12-22 07:03 UTC, JackBoosY commented
LGTM.

2020-12-22 09:59 UTC, JackBoosY commented
Waiting for #15251 merge.

2020-12-23 22:31 UTC, walbourn commented
OK, at this point I believe everything here is done and all code-review feedback addressed.  Checks all passed, and a local build for all supported triplets passes including ``x64-linux`` for directxmath.

Linux is blocked for directxtk, directxtk12, directxmesh, and directxtex for now--plan to address this in future upstream.

OSX is blocked for directxtk, directxtk12, directxmesh, and directxtex--support for this is blocked unless **directx-headers** supports OSX.

2020-12-24 01:30 UTC, BillyONeal commented on scripts/ci.baseline.txt
>  directxmesh:x64-windows-static=fail
Do you expect x64-windows-static to fail for these? If so maybe !static should be in the Supports field.

2020-12-24 01:30 UTC, BillyONeal commented on ports/uvatlas/CONTROL
> +Build-Depends: uvatlas[core](arm64|uwp), directxmesh(!uwp), directxtex(!uwp)
Why does the port `Build-Depends:` on itself?

2020-12-24 01:31 UTC, BillyONeal approved these changes

2020-12-24 02:44 UTC, walbourn commented on ports/uvatlas/CONTROL
> +Build-Depends: uvatlas[core](arm64|uwp), directxmesh(!uwp), directxtex(!uwp)
I think it was in another of the ports and I copied it. I can clean it up if that's proper...

2020-12-24 02:48 UTC, walbourn commented on ports/uvatlas/CONTROL
> +Build-Depends: uvatlas[core](arm64|uwp), directxmesh(!uwp), directxtex(!uwp)
The directxmesh ``CONTROL`` in [master](https://github.com/microsoft/vcpkg/blob/master/ports/directxmesh/CONTROL) has it there, so that's probably where I thought it was needed.

2020-12-24 02:55 UTC, walbourn commented on scripts/ci.baseline.txt
>  directxmesh:x64-windows-static=fail
I don't know why it fails... It *always* uses static linking per ``vcpkg_check_linkage(ONLY_STATIC_LIBRARY ONLY_DYNAMIC_CRT)``

2020-12-24 02:56 UTC, JackBoosY commented on ports/uvatlas/CONTROL
> +Build-Depends: uvatlas[core](arm64|uwp), directxmesh(!uwp), directxtex(!uwp)
@walbourn  Please clean that.

2020-12-24 20:47 UTC, walbourn commented
Previous submitters had marked things as fail in ci scripts, so I didn't notice this bug before upstream. No idea why it didn't show up locally but probably some subtle order difference in cmake revisions.

Fixing.

2020-12-25 02:18 UTC, JackBoosY commented on scripts/ci.baseline.txt
>  directxmesh:x64-windows-static=fail
@walbourn We should dig into the cause of this.
If this is a bug, we need to fix it; if this is by design, it can be written in the `Supports` field.

2020-12-25 22:02 UTC, walbourn commented on scripts/ci.baseline.txt
>  directxmesh:x64-windows-static=fail
@JackBoosY  My libraries should support static, and static only. I don't know why the triplet x64-windows works but x64-window-static fails, but that seems to be a vcpkg thing.

2020-12-25 22:04 UTC, walbourn commented on scripts/ci.baseline.txt
>  directxmesh:x64-windows-static=fail
@JackBoosY Is it because ``x64-windows-static`` also mandates static CRT, maybe?

2020-12-25 22:32 UTC, walbourn commented on scripts/ci.baseline.txt
>  directxmesh:x64-windows-static=fail
This looks like it dates back to this commit https://github.com/microsoft/vcpkg/commit/9a642ade4e7a605e7d11b693e471990d5c6468ed which just set a bunch of ports as 'requires dynamic CRT'.

I don't know why it was done that way, but there's no reason I know of that it should just work for both... Updating the port to remove the ``ONLY_DYNAMIC_CRT`` part of ``vcpkg_check_linkage``

2020-12-28 05:55 UTC, JackBoosY commented
@BillyONeal do you have any other questions?

2020-12-29 01:28 UTC, merged

2020-12-29 01:29 UTC, BillyONeal commented
Thanks for your help!