[openblas] dynamic arch feature
microsoft/vcpkg pull request #15238
Opened 2020-12-21 16:34 UTC by xandox

Add [dynamic arch](https://github.com/xianyi/OpenBLAS/#support-for-multiple-targets-in-a-single-library) feature to OpenBLAS ports

- What does your PR fix? Fixes # Add new feature

- Which triplets are supported/not supported? Have you updated the CI baseline? Same

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes

2020-12-22 02:19 UTC, NancyLi1013 requested changes

2020-12-22 02:20 UTC, NancyLi1013 commented
@xandox 

Have you tested the feature `dynamic-arch`?

2020-12-22 11:13 UTC, xandox commented
@NancyLi1013 before PR I build with dynamic-arch feature for x64-linux, today I try to build for arm64-android and version 0.3.10 would not build. I also update version.

2020-12-22 12:16 UTC, xandox commented
Oh, how to debug failed tests?

2020-12-23 06:10 UTC, NancyLi1013 commented
For the failure on osx, there is no error log generated. I have rerun it and let's see the new test result.

For the feature test, you can test x86-windows and x64-windows.

2020-12-23 06:12 UTC, NancyLi1013 requested changes

2020-12-23 06:12 UTC, NancyLi1013 commented on ports/openblas/CONTROL
> +Port-Version: 1
```suggestion
Version: 0.3.13
```

2020-12-23 06:45 UTC, NancyLi1013 commented
The failures are like this:

```
/Users/vagrant/Data/buildtrees/openblas/src/7079f26fa1-32aa3694bc.clean/kernel/x86_64/srot_microk_haswell-2.c:41:14: error: always_inline function '_mm256_fmadd_ps' requires target feature 'fma', but would be inlined into function 'srot_kernel' that is compiled without support for 'fma'
        t0 = _mm256_fmadd_ps(c_256, x0, t0);
             ^
/Users/vagrant/Data/buildtrees/openblas/src/7079f26fa1-32aa3694bc.clean/kernel/x86_64/srot_microk_haswell-2.c:42:14: error: always_inline function '_mm256_fmadd_ps' requires target feature 'fma', but would be inlined into function 'srot_kernel' that is compiled without support for 'fma'
        t1 = _mm256_fmadd_ps(c_256, x1, t1);
             ^
/Users/vagrant/Data/buildtrees/openblas/src/7079f26fa1-32aa3694bc.clean/kernel/x86_64/srot_microk_haswell-2.c:43:14: error: always_inline function '_mm256_fmadd_ps' requires target feature 'fma', but would be inlined into function 'srot_kernel' that is compiled without support for 'fma'
        t2 = _mm256_fmadd_ps(c_256, x2, t2);
```

2021-03-04 06:46 UTC, NancyLi1013 commented
/azp run

2021-03-04 08:45 UTC, NancyLi1013 commented
The same error on x64-osx

2021-03-04 08:46 UTC, NancyLi1013 commented
Related PR #14760

2021-03-04 15:29 UTC, xandox commented
Problem here is: `openblas` detects that processor (on check host) does not have `FMA` instructions set. And as it does not have this instructions `-mfma` flag does not append to compilator arguments. But `openblas` still use intrinsics from `FMA` set if processor is `HASWELL` and that is why error is produced.  
I created issue https://github.com/xianyi/OpenBLAS/issues/3128 for `openblas`.

2021-03-04 15:32 UTC, xandox commented
Accidentally closed it. Missed the buttons

2021-03-05 14:37 UTC, xandox commented
There a comment from @martin-frbg from openblas issue: 
> I do find it a bit strange that the cpu would report AVX/AVX2 capability but not FMA3 though - is this a VM config problem ?

Is it any chance that it can be fixed by configuring VM?

2021-03-08 08:43 UTC, NancyLi1013 commented
> There a comment from @martin-frbg from openblas issue:
> 
> > I do find it a bit strange that the cpu would report AVX/AVX2 capability but not FMA3 though - is this a VM config problem ?
> 
> Is it any chance that it can be fixed by configuring VM?

For fma problem, you can try to add an option for osx platform, it's unnecessary to configure VM.

` add_compile_options(-mfma)`

2021-03-08 10:29 UTC, xandox commented
This is issue not about missed compiler flag or mac os itself. `openblas` perfectly compiles on my local mac. openblas crew already fix this problem but it will be in new release only. However, comment from @martin-frbg still applyable to VM.

2021-03-09 09:41 UTC, NancyLi1013 commented
@xandox 

Thanks for your above information. Is it possible to update `openblas ` to the latest commit or make a patch to fix the problem?

For the configuration on our CI machine, we will also check and confirm this later.

2021-03-09 15:17 UTC, xandox commented
> Is it possible to update openblas to the latest commit or make a patch to fix the problem?

Yes. It looks like 0.3.14 is about to be released soon. I update this PR after this will happen.

2021-04-23 06:06 UTC, NancyLi1013 commented
Hi @xandox 

v0.3.14 has been released now. https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.14

Could you please update to 0.3.14 in this PR?

2021-04-23 16:38 UTC, xandox commented
(╯°□°)╯︵ ┻━┻

2021-04-25 06:31 UTC, NancyLi1013 commented
Seems the new release doesn't fix the problem. 

The same error as before:
```
/Users/vagrant/Data/buildtrees/openblas/src/2e36dd2a71-ba2c41d242.clean/kernel/x86_64/drot_microk_haswell-2.c:41:14: error: always_inline function '_mm256_fmadd_pd' requires target feature 'fma', but would be inlined into function 'drot_kernel' that is compiled without support for 'fma'
        t0 = _mm256_fmadd_pd(c_256, x0, t0);
```

2021-04-25 06:34 UTC, NancyLi1013 requested changes

2021-04-25 06:34 UTC, NancyLi1013 commented on versions/o-/openblas.json
> +    },
```suggestion
```
There should be only one change for every PR.

2021-04-25 14:30 UTC, martin-frbg commented
> Seems the new release doesn't fix the problem.
> 
> The same error as before:
> 
> ```
> /Users/vagrant/Data/buildtrees/openblas/src/2e36dd2a71-ba2c41d242.clean/kernel/x86_64/drot_microk_haswell-2.c:41:14: error: always_inline function '_mm256_fmadd_pd' requires target feature 'fma', but would be inlined into function 'drot_kernel' that is compiled without support for 'fma'
>         t0 = _mm256_fmadd_pd(c_256, x0, t0);


> Seems the new release doesn't fix the problem.
> 
> The same error as before:
> 
> ```
> /Users/vagrant/Data/buildtrees/openblas/src/2e36dd2a71-ba2c41d242.clean/kernel/x86_64/drot_microk_haswell-2.c:41:14: error: always_inline function '_mm256_fmadd_pd' requires target feature 'fma', but would be inlined into function 'drot_kernel' that is compiled without support for 'fma'
>         t0 = _mm256_fmadd_pd(c_256, x0, t0);
> ```

can you post the config.h generated during the failed build please ?

2021-04-26 09:17 UTC, xandox commented
unfortunately `config.h` not in artifacts. @NancyLi1013 can you help with this?

2021-04-26 20:00 UTC, martin-frbg commented
nevermind - I realized that I had only fixed the srot microkernel while the same mistake exists in drot as well.

2021-04-29 10:04 UTC, gnaggnoyil commented
It seems that version bump and dynamic arch are two separate features that shouldn't impact on each other. As a user, we are waiting to use v0.3.14 in vcpkg thus we think it would be great if there's a separate PR that bumps version and make this PR rebase on the version-bumped one so that this PR would focus on dynamic arch issues.

2021-04-29 10:08 UTC, xandox commented
Unfortunately `dynamic-arch` feature is not issue here. It can't be compiled in core mode

2021-04-29 10:20 UTC, gnaggnoyil commented
@xandox So can we ignore this and bump version first?

2021-04-29 10:24 UTC, martin-frbg commented
can you wait a bit (until the weekend I hope) and go straight to 0.3.15 then ?

2021-04-29 10:24 UTC, xandox commented
>So can we ignore this and bump version first?
No, problem in new versions. Probably if set dynamic-arch as default feature - it can helps, but I do not know is it good idea?

2021-04-29 10:26 UTC, xandox commented
@martin-frbg it will be grate!

2021-04-30 04:32 UTC, gnaggnoyil commented
@xandox @martin-frbg Sure. I'll wait for the 0.3.15 version in vcpkg.

2021-05-02 22:06 UTC, martin-frbg commented
0.3.15 released now

2021-05-03 09:35 UTC, xandox commented
@martin-frbg thank you!

2021-05-05 09:06 UTC, xandox commented
up

2021-05-07 07:40 UTC, NancyLi1013 approved these changes

2021-05-07 07:44 UTC, NancyLi1013 commented
LGTM now, thanks for your patience and contribution @xandox. Also thanks everyone here.

2021-05-18 05:55 UTC, dan-shaw commented on ports/openblas/portfile.cmake
> +        set(VCPKG_LIBRARY_LINKAGE dynamic)
We generally should not change library linkage if a feature is enabled. If a feature does not support a linkage type, we should output `message(FATAL_ERROR)`. Does the `dynamic-arch` feature work for other platforms? We should also output an error if this feature is enabled on platforms that are not supported.

2021-05-18 12:49 UTC, xandox commented on ports/openblas/portfile.cmake
> +        set(VCPKG_LIBRARY_LINKAGE dynamic)
There actually a issue not with `openblas` directly but in ninja.
https://gitlab.kitware.com/cmake/cmake/-/issues/16731
rsp-file contains 7001 lines of other libraries. 

Can you suggest some other ways to resolve it without `message(FATAL_ERROR)`?

2021-05-20 21:57 UTC, ras0219 commented on ports/openblas/portfile.cmake
> +        set(VCPKG_LIBRARY_LINKAGE dynamic)
```
vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
```

plus a message about why this is happening.

2021-05-27 05:39 UTC, NancyLi1013 commented
/azp run

2021-07-20 09:14 UTC, NancyLi1013 commented
@xandox 
Could you please resolve the conflicts in this PR?

2021-07-20 12:31 UTC, xandox commented
> @xandox
> Could you please resolve the conflicts in this PR?

done, once again

2021-07-21 01:44 UTC, NancyLi1013 commented
LGTM now, thanks for your PR. @xandox

2021-07-23 05:52 UTC, vicroms approved these changes
This LGTM once merge conflicts have been solved

2021-07-25 19:47 UTC, vicroms commented
/azp run

2021-07-26 00:26 UTC, merged