[openssl] Update to 1.1.1i
microsoft/vcpkg pull request #15298
Opened 2020-12-25 15:48 UTC by lebdron

- Update openssl to 1.1.1i.
- Add support for arm64-osx triplet.

2020-12-28 07:18 UTC, NancyLi1013 commented on ports/openssl/unix/CMakeLists.txt
> +    set(PLATFORM darwin64-${CMAKE_OSX_ARCHITECTURES}-cc)
@Neumann-A Could you please help review?

2020-12-28 07:24 UTC, NancyLi1013 commented
Hi @lebdron 

Thanks for this PR.

Could you please look into the failures?

`cppcms `failed on x86-windows and x64-windows

```
[302/431] cmd.exe /C "cd /D D:\buildtrees\cppcms\x86-windows-dbg && D:\installed\x86-windows\tools\python3\python.exe D:/buildtrees/cppcms/src/20a4ad93d4-26c9d29282.clean/bin/cppcms_tmpl_cc -o D:/buildtrees/cppcms/x86-windows-dbg/tc_skin.cpp D:/buildtrees/cppcms/src/20a4ad93d4-26c9d29282.clean/tests/tc_skin.tmpl"
FAILED: tc_skin.cpp 
cmd.exe /C "cd /D D:\buildtrees\cppcms\x86-windows-dbg && D:\installed\x86-windows\tools\python3\python.exe D:/buildtrees/cppcms/src/20a4ad93d4-26c9d29282.clean/bin/cppcms_tmpl_cc -o D:/buildtrees/cppcms/x86-windows-dbg/tc_skin.cpp D:/buildtrees/cppcms/src/20a4ad93d4-26c9d29282.clean/tests/tc_skin.tmpl"
Traceback (most recent call last):
  File "D:\buildtrees\cppcms\src\20a4ad93d4-26c9d29282.clean\bin\cppcms_tmpl_cc", line 14, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

`open62541` failed on x64-windows-static:
```
FAILED: src_generated/open62541/transport_generated.c src_generated/open62541/transport_generated.h src_generated/open62541/transport_generated_handling.h src_generated/open62541/transport_generated_encoding_binary.h 
cmd.exe /C "cd /D D:\buildtrees\open62541\x64-windows-static-dbg && D:\installed\x64-windows-static\tools\python3\python.exe D:/buildtrees/open62541/src/26be47a0cb-7b2df1ce14.clean/tools/generate_datatypes.py --namespace=1 --selected-types=D:/buildtrees/open62541/src/26be47a0cb-7b2df1ce14.clean/tools/schema/datatypes_transport.txt --type-bsd=D:/buildtrees/open62541/src/26be47a0cb-7b2df1ce14.clean/tools/schema/Opc.Ua.Types.bsd --type-bsd=D:/buildtrees/open62541/src/26be47a0cb-7b2df1ce14.clean/tools/schema/Custom.Opc.Ua.Transport.bsd --type-csv=D:/buildtrees/open62541/src/26be47a0cb-7b2df1ce14.clean/tools/schema/NodeIds.csv --no-builtin --internal D:/buildtrees/open62541/x64-windows-static-dbg/src_generated/open62541/transport"
Traceback (most recent call last):
  File "D:\installed\x64-windows-static\tools\python3\lib\xml\etree\ElementTree.py", line 1527, in __init__
    from xml.parsers import expat
  File "D:\installed\x64-windows-static\tools\python3\lib\xml\parsers\expat.py", line 4, in <module>
    from pyexpat import *
ModuleNotFoundError: No module named 'pyexpat'
```

2020-12-28 07:27 UTC, lebdron commented
Hello @NancyLi1013 

Could you rerun the pipelines please? Those issues do not really look related to OpenSSL. Thanks!

2020-12-28 09:04 UTC, NancyLi1013 commented
@lebdron 

I noticed you have submit a new commit to retrigger CI.

Since `cppcms `and `open62541` have the dependency of `openssl`. It might be something related with the changes in this PR.

Let's see the latest build results.

2020-12-31 22:45 UTC, Hoikas commented
The CI failures seem to be related to the wrong Python executable being used - I've submitted a fix in #15404.

2021-01-06 11:10 UTC, lebdron commented
Requires https://github.com/microsoft/vcpkg/pull/15473 now. With poppler, the problem appears when `curl` is installed with vcpkg.

2021-01-06 11:30 UTC, lebdron commented
@Neumann-A could you check the change mentioned please? and also poppler build fails because of this policy issue https://github.com/microsoft/vcpkg/pull/10715/files#r404183663 . Could you tell what is the suggested fix?

2021-01-06 11:38 UTC, Neumann-A commented on ports/openssl/unix/CMakeLists.txt
> +    set(PLATFORM darwin64-${CMAKE_OSX_ARCHITECTURES}-cc)
https://cmake.org/cmake/help/v3.19/variable/CMAKE_OSX_ARCHITECTURES.html

seems ok from the description but I am not an osx guy so I don't know which values CMAKE_OSX_ARCHITECTURES actually has

2021-01-07 07:44 UTC, NancyLi1013 commented
@lebdron 

Could you please merge master to this branch to retrigger CI? Since some problems caused by python3 has been solved now.

2021-01-07 07:46 UTC, NancyLi1013 commented on ports/openssl/unix/CMakeLists.txt
> +    set(PLATFORM darwin64-${CMAKE_OSX_ARCHITECTURES}-cc)
Thanks for your help @Neumann-A.

2021-01-07 09:57 UTC, lebdron commented
@NancyLi1013 Done! CI passed :relieved:

2021-01-08 01:55 UTC, NancyLi1013 approved these changes

2021-01-08 02:01 UTC, NancyLi1013 commented
LGTM now except for `CMAKE_OSX_ARCHITECTURES`. Since I'm not familiar with this.

Thanks for your PR @lebdron.

@vicroms 

Could you please help review this point? Please help confirm if `CMAKE_OSX_ARCHITECTURES `is proper here.

Thanks.

2021-01-08 19:26 UTC, vicroms commented on ports/openssl/unix/CMakeLists.txt
> +    set(PLATFORM darwin64-${CMAKE_OSX_ARCHITECTURES}-cc)
If I recall correctly `CMAKE_OSX_ARCHITECTURES` can contain multiple values, e.g: `x86_64;arm64` when building universal (a.k.a. fat) binaries. But to be fair, we don't handle those properly in vcpkg (see [lines 166-196 in our toolchain](https://github.com/microsoft/vcpkg/blob/c898283a41af23135c048c50836f2bc2eccea819/scripts/buildsystems/vcpkg.cmake#L166-L196)). 

I'd prefer if we used old-and-trusty `if-else` instead of trying to do something clever.

2021-01-08 19:56 UTC, vicroms requested changes

2021-01-08 19:56 UTC, vicroms commented on ports/openssl/unix/CMakeLists.txt
> +    set(PLATFORM darwin64-${CMAKE_OSX_ARCHITECTURES}-cc)
If I recall correctly CMAKE_OSX_ARCHITECTURES can contain multiple values, e.g: x86_64;arm64 when building universal (a.k.a. fat) binaries. But to be fair, we don't handle those properly in vcpkg (see lines 166-196 in our toolchain).

I'd prefer if we used old-and-trusty if-else instead of trying to do something clever.

2021-01-08 20:09 UTC, vicroms approved these changes

2021-01-08 20:10 UTC, vicroms commented
Thanks for the PR! 
Waiting for CI results to merge.

2021-01-11 07:47 UTC, vicroms commented
/azp run

2021-01-11 08:08 UTC, merged

2021-01-11 08:08 UTC, vicroms commented
Thanks for the PR!