fix licensingfile of kf5archive
microsoft/vcpkg pull request #15314
Opened 2020-12-26 11:44 UTC by Hendiadyoin1

**Describe the pull request**

Fix issue related to the missing/renaming of a file in newer versions of kf5archive as described in #15304 

- ports: all

2020-12-27 06:21 UTC, BillyONeal commented
I'm not sure I understand; if the ref didn't change, and therefore the content we are starting with didn't change, how did the file disappear in the original issue report? Was that build actually using `--head` or something like that instead?

2020-12-27 09:24 UTC, Hendiadyoin1 commented
Before it was using a file/directory named COPYING.LIB and now it's using a directory called LICENSING.

I build the library without the --head flag.

2020-12-27 20:05 UTC, Hoikas commented
It looks like `COPYING.LIB` does not exist in the v5.74.0 tag at all. Is it legal for `copyright` to be a [directory](https://github.com/KDE/karchive/tree/v5.74.0/LICENSES) in vcpkg?

2020-12-28 02:46 UTC, JackBoosY commented
@BillyONeal  The issue DOES exist, don't know why.

2020-12-28 02:49 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-12-28 02:49 UTC, JackBoosY commented on ports/kf5archive/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSES DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
Since LICENSES is a folder, we should select one of the license files to install instead of installing the entire folder.

2021-01-02 11:49 UTC, Hendiadyoin1 commented
> 
> 
> Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

If you mean just the port version, there was none before,  
if you meen the library version on the otherhand, i'd have to do the same thing for ecm and the other kf5 libraries as well

2021-01-02 11:57 UTC, Hendiadyoin1 commented
Another pull request propabbly fixing these issues is #13467, where as the version they are updtaing to is already not uptodate, though better than the current one (0.10 versions)

2021-01-02 12:31 UTC, Hoikas commented
> If you mean just the port version, there was none before,

Because you have updated the port, you need to add `Port-Version: 1` to the CONTROL file.

2021-01-02 17:45 UTC, Hendiadyoin1 commented
Port-version got bumped to 1, although an update to newer version may be recommended

2021-01-04 02:57 UTC, JackBoosY approved these changes

2021-01-05 20:11 UTC, merged