[KTX] Add port
microsoft/vcpkg pull request #15336
Opened 2020-12-28 05:59 UTC by stephenjust

Adds a port for libktx

- What does your PR fix? Fixes #15113

- Which triplets are supported/not supported? UWP not supported.

2020-12-28 09:41 UTC, PhoebeHui commented
@stephenjust, thanks for your contribution!

Here is CI test failures with x64-windows/x86-windows/x64-windows-static/arrm64-windows.

```
CMake Error at D:/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Bash (missing: BASH_EXECUTABLE)
Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindBash.cmake:95 (find_package_handle_standard_args)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
```

2020-12-28 17:58 UTC, stephenjust commented
> @stephenjust, thanks for your contribution!
> 
> Here is CI test failures with x64-windows/x86-windows/x64-windows-static/arrm64-windows.
> ...

This project has a custom module to resolve Bash, I have some ideas for how I might override the behavior - still investigating.

2020-12-31 06:16 UTC, PhoebeHui commented on ports/ktx/vcpkg.json
> +      "description": "Build Vulkan support"
Have you test the 2 features locally?

2020-12-31 06:39 UTC, PhoebeHui requested changes

2020-12-31 06:39 UTC, PhoebeHui commented on ports/ktx/0001-Use-vcpkg-zstd.patch
> ++            PRIVATE ${ZSTD_H_PATH}
When build the feature 'tools',  it failed with 
```
vcpkg\buildtrees\ktx\src\.0.0-beta5-c23f0e515e.clean\utils\scapp.h(7): fatal error C1083: Cannot open include file: 'zstd.h': No such file or directory
```
You may need to update the PRIVATE to PUBLIC.

BTW, you can also update the patch as following instead.
```
  find_package(zstd CONFIG REQUIRED)
  target_link_libraries(
            ${lib}
            $<IF:$<TARGET_EXISTS:zstd::libzstd_shared>,zstd::libzstd_shared,zstd::libzstd_static>
        )
```

2021-01-09 23:01 UTC, stephenjust commented on ports/ktx/0001-Use-vcpkg-zstd.patch
> ++            PRIVATE ${ZSTD_H_PATH}
Great suggestion here - seems to work and eliminates the need to manually include zstd.h.

2021-01-09 23:12 UTC, stephenjust commented on ports/ktx/vcpkg.json
> +      "description": "Build Vulkan support"
I've built the project with the different feature combinations, and I've run each of the tools on some sample files from the source repository. I unfortunately don't fully understand what the vulkan support is doing for any meaningful validation other than that the build output looks correct according to my interpretation of the cmake scripts.

2021-01-11 05:55 UTC, PhoebeHui approved these changes
LGTM, thanks for your updates!

2021-01-11 07:59 UTC, merged

2021-01-11 07:59 UTC, vicroms commented
Thanks for the PR!