[freetype] Update to 2.10.4
microsoft/vcpkg pull request #15334
Opened 2020-12-28 02:25 UTC by kevinlul

**Describe the pull request**

- What does your PR fix?

Regular port update https://sourceforge.net/projects/freetype/files/freetype2/2.10.4/ with major security vulnerability fix, plus the upstream vtk patch for compatibility with this revision from https://discourse.vtk.org/t/building-opencascade-7-5-0-with-vtk-9-0-1

Closes #14008. I made a new PR due to the changes on `master` and branched off the last commit that affected freetype and vtk since I could not build anything on HEAD #15332 but I could on 191e01f 

- Which triplets are supported/not supported? Have you updated the CI baseline?
It should work everywhere but since vtk takes really long to build, I've only tested against x86-windows.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2020-12-28 03:06 UTC, JackBoosY requested changes

2020-12-28 03:06 UTC, JackBoosY commented on ports/vtk/fix-freetype.patch
> ++static FT_Error
What is wrong here? Does the upstream accept this changes and know this bug?

2020-12-28 17:27 UTC, kevinlul commented on ports/vtk/fix-freetype.patch
> ++static FT_Error
See the linked thread for the details. The short version that I understand is that `FT_CALLBACK_DEF` is actually an internal freetype macro that got removed in 2.10.4, and the patches I incorporate and reference replace the usage of this macro with what it actually expands to.

2020-12-29 02:55 UTC, JackBoosY approved these changes
Did you test the usage?

2020-12-29 04:37 UTC, kevinlul commented
Behaviour of freetype is fine for me since that was working in the old PR but I cannot really say anything meaningful about vtk since I didn't expect this problem with a seemingly unrelated port.

2020-12-30 00:05 UTC, vicroms commented
Thanks for the PR!

2020-12-30 00:05 UTC, merged