[osgearth] Fix x64-windows-static-md
microsoft/vcpkg pull request #15375
Opened 2020-12-29 17:59 UTC by ankurverma85

**Describe the pull request**
* Fix osgearth for x64-windows-static-md

- What does your PR fix? Fixes #15301

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-12-30 06:49 UTC, JackBoosY requested changes

2020-12-30 06:49 UTC, JackBoosY commented on ports/osgearth/StaticOSG.patch
> ++  )
The vcpkg internal geos should be used instead of the system.

2020-12-30 06:49 UTC, JackBoosY commented on ports/osgearth/portfile.cmake
> +#vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY ONLY_DYNAMIC_CRT)
```suggestion
```

2021-01-01 12:06 UTC, ankurverma85 commented on ports/osgearth/StaticOSG.patch
> ++  )
This (find_library) would use the vcpkg geos wont it ?
Not sure what is the change that is requested here

2021-01-04 08:27 UTC, JackBoosY commented on ports/osgearth/StaticOSG.patch
> ++  )
Since you manually set the search path of geos, and the path does NOT contain the installation path of the library in vcpkg (_VCPKG_ROOT/installed/TRIPLET/lib_ AND _VCPKG_ROOT/installed/TRIPLET/debug/lib_), geos will always be found from these system paths.

So you should use `find_package(geos CONFIG REQUIRED)` and `target_link_libraries(${TARGET} PRIVATE GEOS::geos)` instead.

2021-01-04 17:06 UTC, ankurverma85 commented on ports/osgearth/StaticOSG.patch
> ++  )
That indeed looks cleaner
Will try it out. 

However, to further explain why this is only uglier and not wrong

There are multiple find_library calls for the same name. The first one does not specify PATHS and will pick up the vcpkg one.
The second one only applies in case the first does not get found. The second one is a no-op is first picked up library from vcpkg installed paths. 
This is also copy pasted to conform to other instances of find_library for other libs. 

However given the patch only applies to osgearth for vcpkg. I'll try out the suggestions

2021-01-04 19:50 UTC, ankurverma85 commented on ports/osgearth/StaticOSG.patch
> ++  )
Due to the organization of osgearth cmake functions this file here is only allowed to set the global variables GEOS_LIBRARY and GEOS_LIBRARY_DEBUG

The target_link_libraries happens elsewhere. 

Its going to be a huge refactor if we want it done that way.

I'm cleaning up the unnecessary second call since it does not apply to vcpkg.

2021-01-05 02:26 UTC, JackBoosY commented on ports/osgearth/StaticOSG.patch
> ++  )
I'll help you to fix that.

2021-01-06 07:12 UTC, JackBoosY requested changes

2021-01-06 07:12 UTC, JackBoosY commented on ports/osgearth/portfile.cmake
> +      deprecated_cpp_fix.patch # Fix port headers to not use classes deprecated in c++17. Gives errors when using the installed port headers
This change includes a modification in the source code. Does the upstream approve it?

2021-01-06 09:50 UTC, JackBoosY requested changes

2021-01-06 21:52 UTC, ankurverma85 commented on ports/osgearth/portfile.cmake
> +        -DOSG_IS_STATIC=ON
dc51519e3c-a190354632.clean/CMakeModules/OsgEarthMacroUtils.cmake:206:    IF   (OSGEARTH_BUILD_SHARED_LIBS)
dc51519e3c-a190354632.clean/CMakeModules/OsgEarthMacroUtils.cmake:208:    ELSE (OSGEARTH_BUILD_SHARED_LIBS)

dc51519e3c-a190354632.clean/src/osgEarth/CMakeLists.txt:872:if(NOT NRL_STATIC_LIBRARIES)
dc51519e3c-a190354632.clean/src/osgEarth/CMakeLists.txt:874:else(NOT NRL_STATIC_LIBRARIES)
dc51519e3c-a190354632.clean/src/osgEarth/CMakeLists.txt:876:endif(NOT NRL_STATIC_LIBRARIES)

The last (OSG_IS_STATIC) is added via a patch to the osgearth. This tells the osgearth cmake to expect static libraries for OSG

2021-01-07 02:36 UTC, JackBoosY commented on ports/osgearth/portfile.cmake
> +        -DOSG_IS_STATIC=ON
I couldn't find `OSG_IS_STATIC` in patches or osgearth sources. Can you double confirm that?

2021-01-09 11:18 UTC, ankurverma85 commented on ports/osgearth/portfile.cmake
> +      deprecated_cpp_fix.patch # Fix port headers to not use classes deprecated in c++17. Gives errors when using the installed port headers
https://github.com/gwaldron/osgearth/issues/1623

2021-01-09 18:41 UTC, ankurverma85 commented on ports/osgearth/portfile.cmake
> +        -DOSG_IS_STATIC=ON
Got accidentally deleted in the last commit. Restored it back. its in the patch file.
Thanks for catching that

2021-01-14 02:17 UTC, JackBoosY commented on ports/osgearth/portfile.cmake
> +      deprecated_cpp_fix.patch # Fix port headers to not use classes deprecated in c++17. Gives errors when using the installed port headers
@ankurverma85 According to the official reply, I think you need to improvde these changes.

2021-01-14 20:05 UTC, ankurverma85 commented on ports/osgearth/portfile.cmake
> +      deprecated_cpp_fix.patch # Fix port headers to not use classes deprecated in c++17. Gives errors when using the installed port headers
Yes. I'll see if i can find a better fix

2021-01-16 05:45 UTC, ankurverma85 commented on ports/osgearth/portfile.cmake
> +      deprecated_cpp_fix.patch # Fix port headers to not use classes deprecated in c++17. Gives errors when using the installed port headers
Using feature_test recommendation from 
https://en.cppreference.com/w/cpp/feature_test

2021-01-18 02:27 UTC, JackBoosY commented
Please run command `vcpkg x-add-version osgearth` then commit the changes.

Thanks.

2021-01-20 06:26 UTC, JackBoosY commented
Waiting for upstream approval.

2021-01-20 19:38 UTC, plevy commented
@ankurverma85 Does this build successfully with -DOSGEARTH_BUILD_TOOLS=OFF?  For me, I get an error on Release build:
CMake Error at ports/osgearth/portfile.cmake:60 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)
Error: Building package osgearth:x64-windows failed with: BUILD_FAILED

The debug build is successful, but for release, I needed to set -DOSGEARTH_BUILD_TOOLS=ON

2021-01-27 03:10 UTC, ankurverma85 commented
> @ankurverma85 Does this build successfully with -DOSGEARTH_BUILD_TOOLS=OFF? For me, I get an error on Release build:
> CMake Error at ports/osgearth/portfile.cmake:60 (file):
> file must be called with at least two arguments.
> Call Stack (most recent call first):
> scripts/ports.cmake:136 (include)
> Error: Building package osgearth:x64-windows failed with: BUILD_FAILED
> 
> The debug build is successful, but for release, I needed to set -DOSGEARTH_BUILD_TOOLS=ON
> Perhaps just set -DOSGEARTH_BUILD_TOOLS=ON as the default as that is a more useful case for most people.
>
I suspect its your cmake that might be old that could be causing the issue. . Could you try with a fresh clone of vcpkg ?

Some build tools dont quite built properly in x64-windows-static-md and will require patches into the osgearth itself.
Given its not really in the scope of vcpkg libs to use those anyways. I'm disabling building those here.

> Are you able to successfully build osgearth:x64-windows-static or osgearth:x64-windows-static-md? Are you using Windows and if so, what version of Visual Studio?

Yes. VS 2019 16.8.4
I'll be turning on the CI-Pipeline build for osgearth in the vcpkg PR pipeline so hopefully any issues should show up

2021-01-27 07:12 UTC, JackBoosY commented
@gwaldron  Can you please review this PR?

Thanks.

2021-01-27 07:14 UTC, JackBoosY commented
```
CMake Error at ports/osgearth/portfile.cmake:62 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:128 (include)


Error: Building package osgearth:x64-windows failed with: BUILD_FAILED
```

2021-01-27 18:00 UTC, ankurverma85 commented
@plevy , Your issue should be fixed now.
All triplets building successfully with the latest changes

2021-01-27 20:52 UTC, plevy commented
> ```
> CMake Error at ports/osgearth/portfile.cmake:62 (file):
>   file must be called with at least two arguments.
> Call Stack (most recent call first):
>   scripts/ports.cmake:128 (include)
> 
> 
> Error: Building package osgearth:x64-windows failed with: BUILD_FAILED
> ```

> @plevy , Your issue should be fixed now.
> All triplets building successfully with the latest changes

Thank you for fixing that, looks like it passes the checks now.

2021-01-27 22:18 UTC, gwaldron commented
@JackBoosY approved by upstream

2021-01-28 07:35 UTC, JackBoosY requested changes

2021-01-28 07:35 UTC, JackBoosY commented on ports/osgearth/portfile.cmake
> +if((NOT OSG_PLUGINS_SUBDIR_LENGTH EQUAL 1) AND (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic))
Why add this condition? We always need to check the osg version.

2021-01-28 07:48 UTC, ankurverma85 commented on ports/osgearth/portfile.cmake
> +if((NOT OSG_PLUGINS_SUBDIR_LENGTH EQUAL 1) AND (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic))
Plugins (dlls) only apply for dynamic mode.
static/static-md mode require all plugins to be statically linked as well.

2021-01-28 09:17 UTC, JackBoosY approved these changes

2021-01-28 10:02 UTC, JackBoosY commented
Will handle the regression later.

2021-01-29 06:15 UTC, JackBoosY commented
Can't repro this regression locally, will digger into it.

2021-01-29 07:32 UTC, ankurverma85 commented
@JackBoosY , One possible explanation for you not being able to reproduce locally could possibly be because you might using older osg libraries that you might have built from a few days back.
Took a quick look at the failure and i have a hunch we might need to add the following 
snippet to osg portfile to really prevent it (osg) from using fontconfig on windows 

```
if (VCPKG_TARGET_IS_WINDOWS)
    list(APPEND OPTIONS -DOSG_TEXT_USE_FONTCONFIG=OFF)
endif()
```

Can you please maybe try that out ?

2021-01-29 07:36 UTC, JackBoosY commented
@ankurverma85 Thanks for pointing this! I will test it immediately.

2021-01-29 09:31 UTC, JackBoosY commented
@ankurverma85 I still can't repro it, even I added option `OSG_TEXT_USE_FONTCONFIG`.

2021-01-29 09:45 UTC, JackBoosY commented
From install log:
missing link to `libssl.lib` and `libcrypto.lib`

From configure log:
Additional `Found OpenSSL`

2021-01-29 19:09 UTC, ankurverma85 commented
@JackBoosY , 
Would you be ok reverting the last 2 commits (changes beyond the last successful build) and perhaps re-enabling the osgearth-tools as a different PR 
I personally find them only a build overhead and I'm not entirely sure why osgearth-tools are particularly important to publish but my vision is highly myopic so I wont argue more.

IMO this PR (without the last 2 commits) enables static linking for osgearth libraries which is still a huge step forward

2021-01-30 11:11 UTC, ankurverma85 commented
/azp run

2021-01-30 13:40 UTC, JackBoosY commented
/azp run

2021-01-30 16:53 UTC, ankurverma85 commented
@JackBoosY , 
FWIW. I cannot repro the x64-windows-static failure either
Builds fine for me

2021-01-30 21:02 UTC, ankurverma85 commented
@JackBoosY 

Looks like the OSG_TEXT_USE_FONTCONFIG  fix works and windows-static port is fine now.

Looking at the x64-linux port. Its technically not a regression because its already broken in master. The port doesnt build on x64-linux.
I'm not sure whats the best way to disable tools for x64-linux but can we please keep enabling x64-linux osgearth(tools) out of scope for the PR ?
And if so do you mind making the right fixes to correctly disable that.

2021-02-01 15:49 UTC, plevy commented
> @JackBoosY
> 
> Looks like the OSG_TEXT_USE_FONTCONFIG fix works and windows-static port is fine now.
> 
> Looking at the x64-linux port. Its technically not a regression because its already broken in master. The port doesnt build on x64-linux.
> I'm not sure whats the best way to disable tools for x64-linux but can we please keep enabling x64-linux osgearth(tools) out of scope for the PR ?
> And if so do you mind making the right fixes to correctly disable that.

Is that the same build tools problem on x64-linux? I see the build failure below which is slightly different.  I can't figure out how to open that log on the Azure system to look at the log.

2021-01-30T17:20:59.6119158Z CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
2021-01-30T17:20:59.6121893Z     Command failed: /mnt/vcpkg-ci/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j17
2021-01-30T17:20:59.6122945Z     Working Directory: /mnt/vcpkg-ci/buildtrees/osgearth/x64-linux-dbg
2021-01-30T17:20:59.6123520Z     See logs for more information:
2021-01-30T17:20:59.6124441Z       /mnt/vcpkg-ci/buildtrees/osgearth/install-x64-linux-dbg-out.log

2021-02-02 02:52 UTC, JackBoosY commented
The link list should be:
<details>
libosgEarthd.a
libosgDBd.a
libosgUtild.a
libosgViewerd.a
dl
libgeos_cd.a
libgeosd.a
libprotobufd.a
m
libosgSimd.a
libosgTextd.a
libosgGAd.a
libosgShadowd.a
libosgd.a
libfontconfig.a
libuuid.a
libfreetyped.a
libbrotlidec-static.a
libbrotlicommon-static.a
libbz2d.a
libcurl-d.a
ldap
lber
libgdal.a
libjpeg.a
libgif.a
libgeotiff.a
libopenjp2.a
libwebpd.a
libzstdd.a
libcfitsio.a
libjson-c.a
libproj.a
libsqlite3.a
libexpat.a
libtinyxml.a
libosgManipulatord.a
libpng16d.a
libssl.a
libcrypto.a
pthread
libz.a
gl
glu
libOpenThreadsd.a
</details>

2021-02-03 09:57 UTC, JackBoosY commented
We need to fix the way to find dependencies in osgearth first.

2021-02-04 02:57 UTC, JackBoosY commented
When I fixed the way to find dependencies, I found that the way osgearth links these dependencies is not suitable for directly using the target name. Will look into it later.

2021-02-08 09:44 UTC, JackBoosY commented
Windows regression will be fixed in #16109.

2021-02-09 02:18 UTC, JackBoosY commented
Since osgearth has a sequence error when calling the components of the dependency osg, and only 10 applications can be activated under linux, only modify them in this PR:
- osgearth_3pv
- osgearth_atlas
- osgearth_boundarygen
- osgearth_clamp
- osgearth_conv
- osgearth_overlayviewer
- osgearth_tfs
- osgearth_toc
- osgearth_version
- osgearth_viewer

2021-02-09 04:08 UTC, JackBoosY commented
LGTM, will rerun the pipeline test after #16088 merged.

2021-02-09 17:20 UTC, ankurverma85 commented
LGTM,
@JackBoosY,
Thanks for driving the right set of fixes across different ports

2021-02-10 03:03 UTC, JackBoosY commented
```
CMake Error at CMakeModules/FindOSG.cmake:134 (FIND_LIBRARY):
  Could not find UUID_LIBRARY_DEBUG using the following names: uuid, libuuid
Call Stack (most recent call first):
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:653 (_find_package)
  CMakeLists.txt:130 (find_package)
```
Needs re-patch FindOSG.cmake.

2021-02-16 02:31 UTC, ankurverma85 commented
@JackBoosY , 
Havent seen an update on this for a while and neither on the dependent PR (#16088)
Can you maybe summarize whats the chain of dependencies here ? 
Seems like this could be stuck for a while

Thanks again for driving the right set of fixes

2021-02-18 06:08 UTC, JackBoosY commented
@ankurverma85 I was on holiday before, waiting for re-fix PR #16088.

2021-02-24 08:06 UTC, ankurverma85 commented
@JackBoosY , Not sure how we're tracking on this .
But given this has been hanging around for about a month now.

Would you be open to revert this to last successful state but with the osgearth_tools being included. ?


This will atleast unblock the triplet builds for osgearth: x64-windows-static-md and the triplet will be built.

It can also  be successfully consumed in an external project (with a few hacks, that i believe wont be required after your fixes)

you can then drive the right set of changes as a follow up with the triplet being unblocked

2021-02-24 08:55 UTC, JackBoosY commented
@ankurverma85 I understand your thoughts very well, but before this PR, the feature tools can be built successfully. 
If the feature tools is removed, some users will lose this feature.
Please wait a while.

2021-02-25 15:38 UTC, ankurverma85 commented
I totally support and agree what you are saying. 
In addition to it being a regression, that fact that we cannot link the static-md libs into an exe and get undefined-ref errors is proof of the different bugs plaguing this port, and so I'm happy to wait

But just for the sake of argument (feel free to ignore if you'd still like me to wait and am happy to, because again, i am convinced you're right):

1. VCPKG is for libs and headers. Tools are primarily codegen tools like protobuf but the output most is libs and headers. So in some sense while its a regression, perhaps, not that serious in light of what it enables. The tools with osgearth are mostly display tools not really programming tools. 
2. I've tested the libs to link with an exe when used. So in some sense the link errors are not because the libs are wrongly generated, its because the cmake scripting that links the libs into the exe is wrong. So they're good to be used in a developer script with a few additonal lines of hackiness
3. It enables osgearth:x64-windows-static-md builds and thereby testing *all* its other dependent ports for the triplet.

2021-02-26 02:38 UTC, JackBoosY commented
cc @ras0219 @ras0219-msft

2021-03-11 20:19 UTC, ankurverma85 commented
@JackBoosY , I see there's been some progress on this in the last week but I'm still not fully sure what are the series of dependencies that need to come together to get this working.
So I'd like to compile a list of open Pull-Requests and issues blocking this.

Pull-Requests
#16088 (GDAL)
      --  #16500 (GDAL)

Open Issues ?

Is GDAL #16088 the only blocking dependency for this ?
Are there other pull requests?
And do we know what are the cascading dependencies for 16088 (gdal)  (open issues/pullrequests)?

Are there any open issues that are not under review/pull requests ?

I'm currently using vcpkg from waaay back with my last successful build for the time being.
But if there's some fixes available (in WIP Pull-Requests) that get this working I'd like to start using atleast locally 

If not, i'd atleast like to track the list of work items to see when that might be possible

2021-03-12 16:12 UTC, JackBoosY commented
This PR doesn't depend on #16500, we need to patch `vcpkg-cmake-wrapper` to add the correct dependencies to the port using ffmpeg.
Sorry to stop this PR for so long, I will solve this problem as soon as possible.

2021-03-21 05:15 UTC, ankurverma85 commented
@JackBoosY I made some scoped changes on top of what you were working on to get things into a clean "all-checks-passing" state
Given this has been hanging around for quite some time.
Can we perhaps get this in as-is and follow this up with any clean-ups you might want. ?

2021-03-21 10:20 UTC, JackBoosY approved these changes

2021-03-21 10:21 UTC, JackBoosY commented
@ankurverma85 Thanks for your hard work! I think this PR will not depend on other PR now.

2021-03-24 03:10 UTC, ankurverma85 commented
@JackBoosY , Can we get this merged ?

2021-03-24 03:23 UTC, JackBoosY commented
ping @vicroms

2021-03-25 20:28 UTC, vicroms approved these changes

2021-03-25 20:28 UTC, merged

2021-03-27 10:08 UTC, autoantwort commented
Now the pipeline fails for osgearth for x64_linux, x64_windows, x64_windows_static and x64_windows_static_md as you can see in #16914, #16879, #16913, #16910, ...