[freeimage] Fix for FreeImage incorrect image format enum after disabling vendor plugins
microsoft/vcpkg pull request #15393
Opened 2020-12-30 12:05 UTC by giladbau

**Describe the pull request**

This PR fixes an issue that arise from a separate patch being applied as part of the port: disable-plugins-depending-on-internal-third-party-libraries.patch. 

When ascertaining the format of an image, FreeImage returns and enum value, `FREE_IMAGE_FORMAT`. The above patch commented out one of the enum values, `FIF_FAXG3`, while leaving the enum values following it unchanged: `FIF_SGI, FIF_EXR, FIF_J2K, FIF_JP2, FIF_PFM, FIF_PICT, FIF_RAW, FIF_WEBP, FIF_JXR`. It also commented out adding the plugin to the list via AddNode().

FreeImage has a one-to-one relationship between this enum and its list of available plugins. Therefore, since one plugin is missing from the list, there is an offset of -1 for the above formats when trying to ascertain an image's format. For example, when trying to find the format of a WEBP image, we receive `FIF_RAW`. 

The PR fixes the issue by applying a new patch, subtracting 1 from each of the enum values after `FIF_FAXG3`. We tested it using WEBP images, and quite certain it will work for the rest.

2021-01-04 02:26 UTC, JackBoosY requested changes

2021-01-04 02:26 UTC, JackBoosY commented on ports/freeimage/update_format_enum_values.patch
> ++	FIF_JXR		= 35
Are these enumerated values only used inside the program? Will import them according to the configuration file and cause the corresponding values to be confused?

2021-01-04 07:44 UTC, giladbau commented on ports/freeimage/update_format_enum_values.patch
> ++	FIF_JXR		= 35
I am not sure I understand the full question. As long as you are using the version from vcpkg, these values correspond to the formats directly. The only way to confuse the values is if someone accounted for the offset in their code, which is a workaround for the incorrect values.

However, please explain your question if possible.

2021-01-04 08:21 UTC, JackBoosY commented on ports/freeimage/update_format_enum_values.patch
> ++	FIF_JXR		= 35
Suppose we use a configuration file `.conf` to store these enumeration values (29, 33, etc.), import and identify the corresponding enumeration values through the library, then if we translate their values, the judgment in the program will be problematic:
`28 -> FIF_EXR` wrong
`28 -> FIF_SGI` right

2021-01-04 11:04 UTC, giladbau commented on ports/freeimage/update_format_enum_values.patch
> ++	FIF_JXR		= 35
From what I know, this is not a usage scenario of this library. It seems that the implementation does not care about the enumeration, only the list of plugins. When requested to return an enum value, it just grabs the index of the list.

2021-01-05 02:19 UTC, JackBoosY approved these changes

2021-01-05 02:19 UTC, JackBoosY commented
Fine, LGTM.

2021-01-05 20:12 UTC, merged

2021-01-05 20:12 UTC, vicroms commented
Thanks for the PR!