Fix paraview mpi
microsoft/vcpkg pull request #15484
Opened 2021-01-06 18:39 UTC by albertziegenhagel

This PR fixes building `paraview` with the `mpi` feature enabled. To my knowledge that feature has never been tested and thus was actually never working before.

The following changes where made:
  - Apply a fix to `vtk` so that some headers get installed that are required by ParaView.
  - Enable the `FiltersParallelFlowPaths` module in `vtk` when both `paraview` and `mpi` features are enabled.
  - Download the source for `IceT` before building ParaView.

Additionally I have added the `mpi` feature to the `vcpkg-ci-paraview` test port. This should make sure that the combination will be tested in the future. I am not sure what the policy about such testing ports is, so let me know if you would prefer that I revert that change.

2021-01-07 02:50 UTC, JackBoosY requested changes

2021-01-07 02:50 UTC, JackBoosY commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
Is this a upstream bug?

2021-01-07 02:50 UTC, JackBoosY commented
I will test it locally.

2021-01-07 10:48 UTC, Neumann-A commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
The question is more if all headers are required or only a few. Upstream paraview is tightly entangled with VTK although they try to minimize those deps they still happen. There are also some private headers which paraviews needs of vtk which get manually copied in the vtk portfile.

2021-01-07 10:58 UTC, albertziegenhagel commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
Oh it is just a single header `vtkCompositeZPassFS.h` which is used by ParaView here:
https://gitlab.kitware.com/paraview/paraview/-/blob/510ee33bbc32de0882dd753fd8ceb61eb2a309ed/Remoting/Views/vtkIceTCompositePass.cxx#L50

I did totally overlook the part in the VTK portfile that explicitly copied some headers for ParaView...

I was thinking whether to open a MR in upstream VTK about that issue, but was not feeling to good about it, since building ParaView against an external VTK installation is not officially supported and I wasn't sure whether they will like those changes.

I will change this PR to copy the header similar to the other ones and remove applying the patch. Thanks for the hint!

2021-01-07 11:12 UTC, Neumann-A commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
Open up a issue in ParaView about the private VTK header. I know that at least Ben Boeckel wants to have the two things cleanly separated. See https://gitlab.kitware.com/paraview/paraview/-/issues/19515

2021-01-07 11:56 UTC, albertziegenhagel commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
I have force-pushed the mentioned changes here and have opened an issue over at ParaView: https://gitlab.kitware.com/paraview/paraview/-/issues/20425

2021-01-12 08:51 UTC, JackBoosY commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
@albertziegenhagel The official replied to you.

2021-01-13 11:50 UTC, albertziegenhagel commented on ports/vtk/fix-install-rendering-parallel-header.patch
> ++  HEADERS ${private_headers})
@JackBoosY They did reply, but did not not yet answer the question where they would like the issues to be solved (either VTK can install the required headers or ParaView should stop using them). While making VTK install the headers is probably easy to be implemented, making ParaView not using them will most likely need a deeper insight into ParaView itself than what I currently have.

As for this MR I do think the current approach to copy the additional header is the best we can do at the moment.

2021-01-20 07:10 UTC, JackBoosY commented
Testing...

2021-01-21 02:47 UTC, JackBoosY commented
When building `vtk[openvr,qt,python,atlmfc,paraview,opengl]`:
```
CMake Error at ThirdParty/hdf5/CMakeLists.txt:26 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.
```

Does that related to your changes?

2021-01-25 11:34 UTC, albertziegenhagel commented
@JackBoosY: Sorry for the late reply. The error is not related to this PR. This happens when `hdf5[parallel]` is already installed and you are trying to install `vtk` without the `mpi` feature.

See [this comment in another PR](https://github.com/microsoft/vcpkg/pull/12971#issuecomment-679002803) and the following discussion.

2021-01-27 08:26 UTC, JackBoosY commented
Can you please solve the file conflicts by revert vtk.json, merge this branch from master and regenerate the version record?

Thanks.

2021-01-28 12:32 UTC, albertziegenhagel commented
> Can you please solve the file conflicts by revert vtk.json, merge this branch from master and regenerate the version record?

Done!

2021-01-29 02:28 UTC, JackBoosY commented
```
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
```
Seems your changes is incorrect. An extra slash.

2021-05-25 08:19 UTC, JackBoosY commented
Pinging @albertziegenhagel for response. Is work still being done for this PR?

2021-07-21 10:05 UTC, PhoebeHui commented
Closing this PR since it seems that no progress is being made, Please reopen if work is still being done.

2021-07-21 10:05 UTC, closed without merging