[openigtlink] Fix cmake config location
microsoft/vcpkg pull request #15500
Opened 2021-01-07 12:38 UTC by dweckmann

**Describe the pull request**

- What does your PR fix? 

Currently the openigtlink config file are generated in a igtl-3.0 subdirectory making the standard cmake `find_package(OpenIGTLink CONFIG REQUIRED)` fail. Even worse, the `OpenIGTLinkConfig.cmake` contained wrong hard coded path, set during build time. The package was just unusable.

This PR address this issues.

2021-01-08 09:23 UTC, NancyLi1013 requested changes

2021-01-11 10:15 UTC, NancyLi1013 requested changes

2021-01-11 10:15 UTC, NancyLi1013 commented on ports/openigtlink/portfile.cmake
> -vcpkg_fixup_cmake_targets(CONFIG_PATH lib/igtl/cmake)
Why do you remove this?

2021-01-11 11:05 UTC, dweckmann commented on ports/openigtlink/portfile.cmake
> -vcpkg_fixup_cmake_targets(CONFIG_PATH lib/igtl/cmake)
> Why do you remove this?

Because it seems unneeded now as the cmake configs are generated at the right place, with the right content. Should I still call it ?

2021-01-12 03:14 UTC, NancyLi1013 commented on ports/openigtlink/portfile.cmake
> -vcpkg_fixup_cmake_targets(CONFIG_PATH lib/igtl/cmake)
If there is absolute path in cmake configs or targets, we should still call it. If not, it's unnecessary.
Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_fixup_cmake_targets.md

2021-01-12 03:18 UTC, NancyLi1013 commented
Have you tested the usage? Does it work fine? It seems that there is something wrong with include path. 

I tried to use it, the header` igtl/igtlSocket.h` cannot be found.

Could you please help check?

2021-01-12 05:40 UTC, dweckmann commented
> Have you tested the usage? Does it work fine? It seems that there is something wrong with include path.
> 
> I tried to use it, the header` igtl/igtlSocket.h` cannot be found.
> 
> Could you please help check?

We use #include <igtlSocket.h>. Upstreams install it on /usr/include/openigtl/. So I'm not sure what is the right prefix. Anyway, before my patch doesn't change the location of the header (same as before). Not sure what to do...

2021-01-12 05:42 UTC, dweckmann commented on ports/openigtlink/portfile.cmake
> -vcpkg_fixup_cmake_targets(CONFIG_PATH lib/igtl/cmake)
There is paths which were definitively wrong before my patch. Now, it should point to relative directory.

2021-01-15 10:36 UTC, dweckmann commented
> Have you tested the usage? Does it work fine? It seems that there is something wrong with include path.
> 
> I tried to use it, the header` igtl/igtlSocket.h` cannot be found.
> 
> Could you please help check?

I've just double checked. In fact, openigtlink cmake config reports `D:/Work/vcpkg/installed/x64-windows/include/igtl` as `OpenIGTLink_INCLUDE_DIRS` variable. Therefore, I cannot see how `#include <igtl/igtlSocket.h>` could work. As I didn't touch upstream cmake, I assume using the provided cmake config from upstream would force you to write `#include <igtlSocket.h>`, if you don't add by yourself  `..vcpkg/installed/x64-windows/include` to the target include directories. We could do that by patching upstream openigtl cmake files, but I'm not sure it is the right thing to do.

2021-01-19 07:54 UTC, NancyLi1013 commented
Generally, we use the header like this if it is installed in _D:/Work/vcpkg/installed/x64-windows/include/igtl_.

`#include <igtl/igtlSocket.h>`

If there is no `igtl `subdirectory, we can use `#include <igtlSocket.h>`.

2021-01-19 18:51 UTC, dweckmann commented
> Generally, we use the header like this if it is installed in _D:/Work/vcpkg/installed/x64-windows/include/igtl_.
> 
> `#include <igtl/igtlSocket.h>`
> 
> If there is no `igtl `subdirectory, we can use `#include <igtlSocket.h>`.

Well, then we must patch upstream, as I didn't touch upstream cmake. On a linux system, the headers are in _/usr/include/igtl_, so it works as is if you use the provided cmake config or not.

I'm a bit confused about how this could have worked before ? The config file were clearly wrong, and still `OpenIGTLink_INCLUDE_DIRS` pointed to  something like _.../include/igtl_ .  It seems wrong to make `OpenIGTLink_INCLUDE_DIRS` point to _D:/Work/vcpkg/installed/x64-windows/include_

2021-01-19 20:06 UTC, dweckmann commented
According to official samples and tutorials directly from http://openigtlink.org/tutorials/ and specifically from https://www.na-mic.org/wiki/OpenIGTLink/Library/Tutorial, all use includes without "igtl" prefix :

Source code from http://svn.na-mic.org/NAMICSandBox/trunk/OpenIGTLink/Examples:

```c++
#include "igtlOSUtil.h"
#include "igtlMessageHeader.h"
#include "igtlTransformMessage.h"
#include "igtlImageMessage.h"
#include "igtlServerSocket.h"
#include "igtlStatusMessage.h"
#include "igtlPositionMessage.h"
...
```

So, I really guess `<igtl/igtlSocket.h>` works by side effect on unix system, but the samples says `<igtlSocket.h>`. 

@NancyLi1013, what do you think ?

2021-01-20 09:00 UTC, NancyLi1013 approved these changes

2021-01-20 09:06 UTC, NancyLi1013 commented
@dweckmann 
Thanks for your further investigation about this issue.

I also checked that `igtl `has been added to `OpenIGTLink_INCLUDE_DIRS`, so we can use `#include <igtlSocket.h>` directly.

LGTM now, thanks for your efforts.

2021-01-21 19:14 UTC, strega-nil commented
Same thing here @dweckmann

2021-01-22 06:21 UTC, NancyLi1013 commented
@dweckmann 

Could you please merge master to this PR?

2021-01-25 07:06 UTC, merged