[flashlight-cpu] New port
microsoft/vcpkg pull request #15514
Opened 2021-01-08 02:18 UTC by jacobkahn

Adds a port for the [flashlight](https://github.com/facebookresearch/flashlight) CPU backend.

Note that only one of the flashlight backends (`flashlight-cpu` or `flashlight-cuda`) can be installed since the two share library bits and headers. Checks have been added to `flashlight-cuda`. This might be relaxed down the line/we may reorganize the structure of the flashlight backends.

cc @padentomasello, @xuqiantong, @vineelpratap, @tlikhomanenko, @avidov, @syhw, @andresy

- Which triplets are supported/not supported? Have you updated the CI baseline?

`x64-linux` -- same as `flashlight-cuda`

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2021-01-08 07:57 UTC, NancyLi1013 reviewed
Could you please also bump version for `flashlight-cuda` in vcpkg.json?

Add port-version: 1

2021-01-08 07:57 UTC, NancyLi1013 commented on ports/flashlight-cpu/portfile.cmake
> +    REF 0948e97dbff23d474500a5f55bcf59d3b3589cf4
I noticed that there is a released version v0.2. Why do you not use the commit `e62eb7ea4c9381411508c08226598ba11cbf9511`?

2021-01-08 07:57 UTC, NancyLi1013 commented on ports/flashlight-cpu/portfile.cmake
> +################################### Build ###################################
```suggestion
```
This comment is not necessary.

2021-01-08 07:57 UTC, NancyLi1013 commented on ports/flashlight-cpu/portfile.cmake
> +  OUT_FEATURE_OPTIONS FL_FEATURE_OPTIONS
```suggestion
  OUT_FEATURE_OPTIONS FEATURE_OPTIONS
```
Please use the default name.

2021-01-08 07:57 UTC, NancyLi1013 commented on ports/flashlight-cpu/portfile.cmake
> +    OPTIONS ${FL_DEFAULT_VCPKG_CMAKE_FLAGS} ${FL_FEATURE_OPTIONS}
```suggestion
    OPTIONS 
        ${FL_DEFAULT_VCPKG_CMAKE_FLAGS} 
        ${FEATURE_OPTIONS}
```

2021-01-08 07:57 UTC, NancyLi1013 commented on ports/flashlight-cpu/vcpkg.json
> +  "version-string": "20201229",
Why do you use this date as version-string?

2021-01-09 17:45 UTC, jacobkahn commented on ports/flashlight-cpu/portfile.cmake
> +    REF 0948e97dbff23d474500a5f55bcf59d3b3589cf4
The `v0.2` release is an old release. We're going to start using tags starting with the 1.0. Release in a few weeks. I will update the port again to point to the tag after that happens.

2021-01-09 17:46 UTC, jacobkahn commented on ports/flashlight-cpu/vcpkg.json
> +  "version-string": "20201229",
This was suggested before - we don't yet have formal releases, but we will starting soon. This will be the last port update before we start using versions.

2021-01-13 16:04 UTC, jacobkahn commented
Bump @JackBoosY @NancyLi1013 :)

2021-01-14 01:51 UTC, NancyLi1013 requested changes

2021-01-14 01:51 UTC, NancyLi1013 commented on ports/flashlight-cpu/portfile.cmake
> +  FEATURES
```suggestion
vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
```

2021-01-14 01:53 UTC, NancyLi1013 requested changes

2021-01-14 01:53 UTC, NancyLi1013 commented on ports/flashlight-cuda/portfile.cmake
```
vcpkg_check_features(
  OUT_FEATURE_OPTIONS FL_FEATURE_OPTIONS
  FEATURES
```
These should also be updated as the follows:

```
vcpkg_check_features(
    OUT_FEATURE_OPTIONS FL_FEATURE_OPTIONS
    FEATURES
```

2021-01-14 03:17 UTC, NancyLi1013 requested changes

2021-01-14 03:17 UTC, NancyLi1013 commented on ports/flashlight-cuda/portfile.cmake
> +    OPTIONS ${FL_DEFAULT_VCPKG_CMAKE_FLAGS} ${FEATURE_OPTIONS}
```suggestion
    OPTIONS 
        ${FL_DEFAULT_VCPKG_CMAKE_FLAGS} 
        ${FEATURE_OPTIONS}
```

2021-01-14 03:17 UTC, NancyLi1013 commented on ports/flashlight-cuda/vcpkg.json
> +  "port-version": 1,
```suggestion
```
Since this is a new version update, port-version is not needed here.

2021-01-14 03:18 UTC, NancyLi1013 approved these changes

2021-01-14 03:19 UTC, NancyLi1013 commented
Have you tested these features? Can they work fine?

2021-01-14 20:48 UTC, jacobkahn commented
@NancyLi1013 — I've tested the ports on `x64-linux`, and everything works.

2021-01-15 01:49 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @jacobkahn.

2021-01-15 07:33 UTC, NancyLi1013 commented
/azp run

2021-01-17 03:42 UTC, merged