[paho-mqttpp3] update to 1.2.0
microsoft/vcpkg pull request #15573
Opened 2021-01-11 10:19 UTC by JonLiu1993

Fix #15547 

Update paho-mqttpp3 to the latest version 1.2.0

Note: All features are tested sucessfully in the following triplets:
1. x86-windows
2. x64-windows
3. x64-windows-static

2021-01-13 08:12 UTC, JonLiu1993 commented
/azp run

2021-01-15 05:36 UTC, vicroms commented
/azp run

2021-02-03 06:35 UTC, NancyLi1013 approved these changes

2021-02-09 02:25 UTC, ras0219-msft requested changes

2021-02-09 02:25 UTC, ras0219-msft commented on ports/paho-mqttpp3/fix-include-path.patch
> -diff --git a/src/mqtt/async_client.h b/src/mqtt/async_client.h
Please revert the line ending changes to this file.

2021-04-09 03:14 UTC, JonLiu1993 commented
/azp run

2021-04-09 06:44 UTC, NancyLi1013 approved these changes

2021-04-09 16:14 UTC, merged