[android] vcpkg_configure_make correct set flags for android build
microsoft/vcpkg pull request #15605
Opened 2021-01-12 15:20 UTC by xandox

vcpkg_configure_make properly set CFLAGS, CXXFLAGS, LDFLAG, CC and CXX env variables now for android cross compilation. 

- Which triplets are supported/not supported?  Mostly android triplets, 
- Have you updated the CI baseline? - no

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

2021-01-12 20:29 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +                set(TARGET_TRIPLET_ARG "--target=${TARGET_TRIPLET_ARG}")
That is wrong. We are not doing a canadian cross build in vcpkg.

2021-01-12 20:31 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +            set(LDFLAGS_EXTRA "${LDFLAGS_EXTRA} --sysroot=${VCPKG_DETECTED_CMAKE_SYSROOT}")
THose flags should already be in LDFLAGS otherwise the toolchain is wrong

2021-01-12 20:45 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +                set(TARGET_TRIPLET_ARG "--target=${TARGET_TRIPLET_ARG}")
Canadian?

2021-01-12 20:57 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +                set(TARGET_TRIPLET_ARG "--target=${TARGET_TRIPLET_ARG}")
canadian cross build means: --build != --host != --target. In vcpkg --host and --target are always the same. 
`VCPKG_TARGET_TRIPLET/CMAKE_SYSTEM_NAME` translates to --host not to --target.

2021-01-12 20:58 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +            set(LDFLAGS_EXTRA "${LDFLAGS_EXTRA} --sysroot=${VCPKG_DETECTED_CMAKE_SYSROOT}")
Not sure. Toolchain configured by cmake. And cmake does not have direct analog of LDFLAGS and handles them by bunch of variables.

2021-01-12 21:01 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +                set(TARGET_TRIPLET_ARG "--target=${TARGET_TRIPLET_ARG}")
Hm, thank you, did not know about Canadian build. But this argument not for configure script, it is for clang and will passed to CXXFLAGS and CFLAGS.

2021-01-12 21:05 UTC, Neumann-A commented on scripts/get_cmake_vars/CMakeLists.txt
> +list(APPEND VCPKG_DEFAULT_VARS_TO_CHECK ANDROID_TOOLCHAIN)
This should only be added if it is necessary.

2021-01-12 21:07 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +                set(TARGET_TRIPLET_ARG "--target=${TARGET_TRIPLET_ARG}")
So this also does not belong here but in the CMakeLists.txt extracting the flags.

2021-01-18 02:14 UTC, JackBoosY commented
Regression when building `mlpack:x86-windows`:
```
armadillo.lib(wrapper2.cpp.obj) : error LNK2019: unresolved external symbol _sgetrf_ referenced in function _wrapper2_sgetrf_
armadillo.lib(wrapper2.cpp.obj) : error LNK2019: unresolved external symbol _dgetrf_ referenced in function _wrapper2_dgetrf_
armadillo.lib(wrapper2.cpp.obj) : error LNK2019: unresolved external symbol _cgetrf_ referenced in function _wrapper2_cgetrf_
armadillo.lib(wrapper2.cpp.obj) : error LNK2019: unresolved external symbol _zgetrf_ referenced in function _wrapper2_zgetrf_
```

2021-01-18 06:06 UTC, JackBoosY commented
Regression is gone.

2021-01-18 06:06 UTC, JackBoosY commented
@Neumann-A Can you please review again?

Thanks.

2021-01-18 06:29 UTC, JackBoosY approved these changes

2021-01-18 09:45 UTC, JackBoosY commented
Fixes #15255.

2021-01-20 06:10 UTC, ras0219-msft requested changes

2021-01-20 06:10 UTC, ras0219-msft commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endif()
This may also want to check `CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES`: https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/CMakeLists.txt#L111-L113

2021-01-20 15:35 UTC, xandox commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endif()
fixed

2021-01-20 15:35 UTC, xandox commented on scripts/get_cmake_vars/CMakeLists.txt
> +    if(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN)
fixed

2021-01-20 15:36 UTC, xandox commented on scripts/get_cmake_vars/CMakeLists.txt
> +if (CMAKE_CROSSCOMPILING)
fixed

2021-01-20 15:36 UTC, xandox commented on scripts/get_cmake_vars/CMakeLists.txt
> +    macro(_append_to target value)
fixed. thank you. did not know about string(APPEND)

2021-01-20 15:37 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +            _vcpkg_determine_autotools_target_cpu(TARGET_ARCH)
add more systems. not sure cover all, but tried

2021-01-20 15:39 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if (NOT CMAKE_HOST_WIN32 AND VCPKG_DETECTED_CMAKE_CROSSCOMPILING)
set always apply. but afraid something is going to broke. will see after autotests.

2021-01-20 16:36 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if (NOT CMAKE_HOST_WIN32 AND VCPKG_DETECTED_CMAKE_CROSSCOMPILING)
Yeh, I have recalled what  a problem with settings CC and CXX always.
On macos cmake set CMAKE_C_COMPILER to something like `/Library/Developer/CommandLineTools/usr/bin/cc` and similar for CXX. And this compilers really can't compile anything. I know very few about macos and do not have full access to any mac machine, and can't determinate what the reason of this problem.

2021-01-21 03:00 UTC, JackBoosY commented
Seems have many regressions when building `x64-osx`, please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=48193&view=artifacts&pathAsName=false&type=publishedArtifacts).

2021-01-25 21:07 UTC, venabled commented
@xandox Thanks for the contribution. I've been playing around with this PR to try and build 'libiconv' the past two days, and I've found a few things that have prevented that port from building.

I think most of it was that `--gcc-toolchain' and '--sysroot' are getting pulled into the `VCPKG_DETECTED_CMAKE_C*_FLAGS_*` variables.

And according to @DanAlbert [post in the NDK repo](https://github.com/android/ndk/issues/951) and the NDK integration with other build systems documentation those really shouldn't be in there.

I guess this isn't really a problem with `vcpkg_configure_make` as it's an issue in Meson ports too. These aren't set as C/CPP flags in the Android toolchain CMake file, so Ill have to keep digging.

2021-01-25 21:47 UTC, xandox commented
@venabled hi. I am not sure what you mean. I am able to build libiconv with 21d and 22 ndk. What is you problem? 

According to the article you provided - yes, looks like `--sysroot` and `--gcc-toolchain` not necessary here, but they are not a problem. They came from `android.toolchain.cmake` and have correct paths.

2021-01-25 21:51 UTC, venabled commented
I guess I should have been more specific, I had to modify 'libiconv' port as the current port only builds from source if you're on Windows.

2021-01-25 22:04 UTC, xandox commented
Yes, sure. See #15606.

2021-01-26 01:24 UTC, DanAlbert commented
> @venabled hi. I am not sure what you mean. I am able to build libiconv with 21d and 22 ndk. What is you problem?
> 
> According to the article you provided - yes, looks like `--sysroot` and `--gcc-toolchain` not necessary here, but they are not a problem. They came from `android.toolchain.cmake` and have correct paths.

Possibly superfluous context here, but in case it's helpful:

While they're not necessary to build correctly, as long as they are set to the appropriate values they shouldn't harm anything. The toolchain file still configures them because (iirc), CMake's `find_*` behaviors depend on `CMAKE_SYSROOT`. There were also old versions of our gradle plugin that depended on that value being present.

 `-gcc-toolchain` I think has done nothing useful since r19 :)

The problem in the NDK bug linked was that folks had set `--sysroot`'s value to the _wrong_ path, and that can definitely break things.

2021-01-26 14:16 UTC, venabled commented
Thanks for the discussion @xandox and @DanAlbert. For whatever reason I couldn't get the mods from this PR to build `libiconv` for `arm-android`.

Modified portfile.cmake:

```
# if(NOT VCPKG_TARGET_IS_WINDOWS)
#     # set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
#     file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/share/Iconv)
#     file(COPY ${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/iconv)
#     return()
# endif()

set(LIBICONV_VERSION 1.16)

vcpkg_download_distfile(ARCHIVE
    URLS "https://ftp.gnu.org/gnu/libiconv/libiconv-${LIBICONV_VERSION}.tar.gz" "https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/libiconv/libiconv-${LIBICONV_VERSION}.tar.gz"
    FILENAME "libiconv-${LIBICONV_VERSION}.tar.gz"
    SHA512 365dac0b34b4255a0066e8033a8b3db4bdb94b9b57a9dca17ebf2d779139fe935caf51a465d17fd8ae229ec4b926f3f7025264f37243432075e5583925bb77b7
)

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE}
)

vcpkg_configure_make(SOURCE_PATH ${SOURCE_PATH}
                     DETERMINE_BUILD_TRIPLET
                     USE_WRAPPERS
                    ${OPTIONS}
                    )

vcpkg_build_make()

vcpkg_install_make()

vcpkg_copy_pdbs()
vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin)
vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug/bin)

file(COPY ${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/iconv)

file(INSTALL ${SOURCE_PATH}/COPYING.LIB DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
set(VCPKG_POLICY_ALLOW_RESTRICTED_HEADERS enabled)
```

Using this script I get linking errors for `crti.o, crtbeginS.o, crtendS.o, crtn.o` and some other libs:

```
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crti.o: No such file or directory
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtbeginS.o: No such file or directory
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtendS.o: No such file or directory
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtn.o: No such file or directory
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lcompiler_rt-extras
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lgcc_s
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lc
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lcompiler_rt-extras
/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lgcc_s
```

Configure command:

```
  $ ./../src/libiconv-1-b9f06978f2.clean/configure --host=arm-linux-android --build=x86_64-linux-gnu --enable-relocatable --enable-extra-encodings --without-libiconv-prefix --without-libintl-prefix --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/data/vcpkg/installed/arm-android --bindir=${prefix}/tools/libiconv/bin --sbindir=${prefix}/tools/libiconv/sbin --mandir=${prefix}/share/libiconv --docdir=${prefix}/share/libiconv --datarootdir=${prefix}/share/libiconv
```

And then CMake detected vars:

```
set(VCPKG_DETECTED_CMAKE_CROSSCOMPILING "TRUE")
set(VCPKG_DETECTED_CMAKE_SYSTEM_NAME "Android")
set(VCPKG_DETECTED_CMAKE_HOST_SYSTEM_NAME "Linux")
set(VCPKG_DETECTED_CMAKE_SYSTEM_PROCESSOR "armv7-a")
set(VCPKG_DETECTED_CMAKE_HOST_SYSTEM_PROCESSOR "x86_64")
set(VCPKG_DETECTED_CMAKE_AR "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar")
set(VCPKG_DETECTED_CMAKE_RANLIB "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib")
set(VCPKG_DETECTED_CMAKE_STRIP "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip")
set(VCPKG_DETECTED_CMAKE_NM "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm")
set(VCPKG_DETECTED_CMAKE_OBJDUMP "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-objdump")
set(VCPKG_DETECTED_CMAKE_DLLTOOL "CMAKE_DLLTOOL-NOTFOUND")
set(VCPKG_DETECTED_CMAKE_MT "")
set(VCPKG_DETECTED_CMAKE_LINKER "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld")
set(VCPKG_DETECTED_CMAKE_AS "")
set(VCPKG_DETECTED_CMAKE_C_COMPILER "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
set(VCPKG_DETECTED_CMAKE_CXX_COMPILER "/home/venabled/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++")
set(VCPKG_DETECTED_CMAKE_RC_COMPILER "")
set(VCPKG_DETECTED_CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "")
set(VCPKG_DETECTED_CMAKE_C_STANDARD_LIBRARIES "-latomic -lm")
set(VCPKG_DETECTED_CMAKE_C_STANDARD "")
set(VCPKG_DETECTED_CMAKE_C_COMPILE_FEATURES "c_std_90;c_function_prototypes;c_std_99;c_restrict;c_variadic_macros;c_std_11;c_static_assert")
set(VCPKG_DETECTED_CMAKE_C_EXTENSION "")
set(VCPKG_DETECTED_CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "")
set(VCPKG_DETECTED_CMAKE_CXX_STANDARD_LIBRARIES "-latomic -lm")
set(VCPKG_DETECTED_CMAKE_CXX_STANDARD "")
set(VCPKG_DETECTED_CMAKE_CXX_COMPILE_FEATURES "cxx_std_98;cxx_template_template_parameters;cxx_std_11;cxx_alias_templates;cxx_alignas;cxx_alignof;cxx_attributes;cxx_auto_type;cxx_constexpr;cxx_decltype;cxx_decltype_incomplete_return_types;cxx_default_function_template_args;cxx_defaulted_functions;cxx_defaulted_move_initializers;cxx_delegating_constructors;cxx_deleted_functions;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_extended_friend_declarations;cxx_extern_templates;cxx_final;cxx_func_identifier;cxx_generalized_initializers;cxx_inheriting_constructors;cxx_inline_namespaces;cxx_lambdas;cxx_local_type_template_args;cxx_long_long_type;cxx_noexcept;cxx_nonstatic_member_init;cxx_nullptr;cxx_override;cxx_range_for;cxx_raw_string_literals;cxx_reference_qualified_functions;cxx_right_angle_brackets;cxx_rvalue_references;cxx_sizeof_member;cxx_static_assert;cxx_strong_enums;cxx_thread_local;cxx_trailing_return_types;cxx_unicode_literals;cxx_uniform_initialization;cxx_unrestricted_unions;cxx_user_literals;cxx_variadic_macros;cxx_variadic_templates;cxx_std_14;cxx_aggregate_default_initializers;cxx_attribute_deprecated;cxx_binary_literals;cxx_contextual_conversions;cxx_decltype_auto;cxx_digit_separators;cxx_generic_lambdas;cxx_lambda_init_captures;cxx_relaxed_constexpr;cxx_return_type_deduction;cxx_variable_templates;cxx_std_17;cxx_std_20")
set(VCPKG_DETECTED_CMAKE_CXX_EXTENSION "")
set(VCPKG_DETECTED_ENV_PATH "/home/venabled/install/bin:/home/venabled/.local/bin:/home/venabled/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/data/vcpkg/downloads/tools/ninja-1.10.1-linux")
set(VCPKG_DETECTED_ENV_INCLUDE "")
set(VCPKG_DETECTED_ENV_C_INCLUDE_PATH "")
set(VCPKG_DETECTED_ENV_CPLUS_INCLUDE_PATH "")
set(VCPKG_DETECTED_ENV_LIB "")
set(VCPKG_DETECTED_ENV_LIBPATH "")
set(VCPKG_DETECTED_ENV_LIBR [...]

2021-01-26 14:39 UTC, Neumann-A commented
> CPPFLAGS

CXXFLAGS is the right variable. CPPFLAGS is the preprocessor flags. 

so doing set(ENV{CPPFLAGS} "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}") is wrong.

2021-01-26 15:02 UTC, venabled commented
> > CPPFLAGS
> 
> CXXFLAGS is the right variable. CPPFLAGS is the preprocessor flags.
> 
> so doing set(ENV{CPPFLAGS} "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}") is wrong.

Nice catch, thanks. Ill fix that going forward. Granted in NDKPorts / my custom scripts I dont even set C*Flags unless the configure script is relatively botched.

2021-02-16 17:52 UTC, jwtowner commented
Hey thanks for your effort. I can confirm that `vcpkg_configure_meson` also suffers from the same problem when cross-compiling for Android NDK. Unable to build harfbuzz which uses it. Dropping in the changes to `scripts/get_cmake_vars/CMakeLists.txt` appears to be a big step in the right direction.

However, an immediate problem occurs when the Android NDK is installed under a directory containing a space character, which is often the case with Xamarin included with MSVS. 

```
..\src\f4d3aa1127-a820a32874.clean\meson.build:1:0: ERROR: Unable to detect linker for compiler "C:/Program Files (x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -Wl,--version -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -fPIC -fasynchronous-unwind-tables -ffunction-sections -fdata-sections -fstack-protector-strong -fstrict-aliasing -fthreadsafe-statics -fvisibility=hidden -fvisibility-inlines-hidden -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_REENTERANT --target=armv7-none-linux-androideabi19 --gcc-toolchain=C:/Program Files (x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Program Files (x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Oz -DNDEBUG -Os -g2 -gdwarf-2 -fomit-frame-pointer -DNDEBUG -flto=thin -I"D:/Devel/Monster/Dev/External/vcpkg/vcpkg/installed/arm-android-sgi-shipping/include""
stdout:
stderr: clang: error: no such file or directory: 'Files'
clang: error: no such file or directory: '(x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64'
clang: error: no such file or directory: 'Files'
clang: error: no such file or directory: '(x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/sysroot'
```

Wrapping the gcc-toolchain and sysroot paths in double-quotations by changing the relevant portions of `scripts/get_cmake_vars/CMakeLists.txt` appears tp fix the problem. Note the escaped back-slash and double-quote.

```
if(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN AND CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        string(APPEND CMAKE_CXX_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN}\\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
        string(APPEND CMAKE_C_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN}\\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
        string(APPEND CMAKE_STATIC_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN}\\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
        string(APPEND CMAKE_SHARED_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN}\\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
    else()
        string(APPEND CMAKE_CXX_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN} \\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
        string(APPEND CMAKE_C_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN} \\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
        string(APPEND CMAKE_STATIC_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN} \\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
        string(APPEND CMAKE_SHARED_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_EXTERNAL_TOOLCHAIN} \\\"${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}\\\"")
    endif()
endif()

if(CMAKE_SYSROOT AND CMAKE_CXX_COMPILE_OPTIONS_SYSROOT)
    string(APPEND CMAKE_CXX_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}\\\"${CMAKE_SYSROOT}\\\"")
    string(APPEND CMAKE_C_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}\\\"${CMAKE_SYSROOT}\\\"")
    string(APPEND CMAKE_STATIC_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}\\\"${CMAKE_SYSROOT}\\\"")
    string(APPEND CMAKE_SHARED_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}\\\"${CMAKE_SYSROOT}\\\"")
endif()
```

However, I'm getting a different issue now and I believe that is we're still missing some paths needed for C++ due to how libc++ overlays on top of Bionic libc, as it's unable to find some of the header files:

```
"C:/Program Files (x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe" "-Isrc\libharfbuzz.a.p" "-Isrc" "-I..\src\f4d3aa1127-a820a32874.clean\src" "-I." "-I..\src\f4d3aa1127-a820a32874.clean" "-ID:/Devel/Monster/Dev/External/vcpkg/vcpkg/installed/arm-android-sgi-shipping/include" "-ID:/Devel/Monster/Dev/External/vcpkg/vcpkg/installed/arm-android-sgi-shipping/include/libpng16" "-ID:/Devel/Monster/Dev/External/Android/support_libcxx/include" "-I\"D:/Devel/Monster/Dev/External/vcpkg/vcpkg/installed/arm-android-sgi-shipping/include\"" "-Xclang" "-fcolor-diagnostics" "-pipe" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=c++11" "-fno-exceptions" "-fno-rtti" "-fno-exceptions" "-fno-rtti" "-fno-threadsafe-statics" "-fvisibility-inlines-hidden" "-DHAVE_CONFIG_H" "-g" "-DANDROID" "-fdata-sections" "-ffunction-sections" "-funwind-tables" "-fstack-protector-strong" "-no-canonical-prefixes" "-march=armv7-a" "-mthumb" "-Wformat" "-Werror=format-security" "-frtti" "-fexceptions" "-fPIC" "-fasynchronous-unwind-tables" "-fno-exceptions" "-fno-rtti" "-ffunction-sections" "-fdata-sections" "-fstack-protector-strong" "-fstrict-aliasing" "-fthreadsafe-statics" "-fvisibility=hidden" "-fvisibility-inlines-hidden" "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=2" "-D_REENTERANT" "--target=armv7-none-linux-androideabi19" "--gcc-toolchain=\"C:/Program Files (x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64\"" "--sysroot=\"C:/Program Files (x86)/Android/android-sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/windows-x86_64/sysroot\"" "-Oz" "-Os" "-g2" "-gdwarf-2" "-fomit-frame-pointer" "-DNDEBUG" "-flto=thin" "-fPIC" "-pthread" "-Wno-non-virtual-dtor" -MD -MQ src/libharfbuzz.a.p/hb-ot-face.cc.o -MF "src\libharfbuzz.a.p\hb-ot-face.cc.o.d" -o src/libharfbuzz.a.p/hb-ot-face.cc.o "-c" ../src/f4d3aa1127-a820a32874.clean/src/hb-ot-face.cc
In file included from ../src/f4d3aa1127-a820a32874.clean/src/hb-ot-face.cc:27:
In file included from ..\src\f4d3aa1127-a820a32874.clean\src/hb-ot-face.hh:32:
..\src\f4d3aa1127-a820a32874.clean\src/hb.hh:179:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
```

I will investigate and report back.

2021-02-16 21:06 UTC, jwtowner commented
Okay, so I modified `scripts/get_cmake_vars/CMakeLists.txt` to add the system include paths needed for C++ compilation and I added them inside of the existing block that deals with CMAKE_SYSROOT like so:

```
if(CMAKE_SYSROOT AND CMAKE_CXX_COMPILE_OPTIONS_SYSROOT)
    string(APPEND CMAKE_CXX_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}${CMAKE_SYSROOT}")
    string(APPEND CMAKE_C_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}${CMAKE_SYSROOT}")
    string(APPEND CMAKE_STATIC_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}${CMAKE_SYSROOT}")
    string(APPEND CMAKE_SHARED_LINKER_FLAGS " ${CMAKE_CXX_COMPILE_OPTIONS_SYSROOT}${CMAKE_SYSROOT}")
    if (CMAKE_SYSTEM_NAME MATCHES "Android")
        if(CMAKE_LIBRARY_ARCHITECTURE AND EXISTS "${CMAKE_SYSROOT}/usr/include/${CMAKE_LIBRARY_ARCHITECTURE}")
            string(APPEND CMAKE_CXX_FLAGS " -isystem ${CMAKE_SYSROOT}/usr/include/${CMAKE_LIBRARY_ARCHITECTURE}")
        endif()
        string(APPEND CMAKE_CXX_FLAGS " -isystem ${CMAKE_SYSROOT}/usr/include")
    endif()
endif()
```

I'm not sure if there's a CMAKE variable we can use for `-isystem` or if there's a better way to structure the above that you may want to use, but with that, everything compiles.

Unfortunately, I could not get it to work when the Android NDK's filesystem path contained a space, even with double-quotation escapes. I think it has something to do with how the various CXXFLAGS options are themselves again double-quoted before being passed to Ninja, and because isystem in particular doesn't support a form that doesn't already use a space. This results in `"-isystem" "\"C:/Program Files (x86)/.../sysroot\""` instead of `"-isystem \"C:/Program Files (x86)/.../sysroot\""` being passed on the command line to Ninja. Not sure if there's an easy fix for this we can use in `scripts/get_cmake_vars/CMakeLists.txt`. My current workaround is just to setup a directory symlink for the Android NDK in my wrapper scripts before invoking vcpkg, so regardless it's not a blocker anymore.

2021-02-16 23:21 UTC, jwtowner commented
I may have spoke too soon. Everything builds fine for Android arm and arm64, but the x86 and x64 target architectures fail. Seems like the --target and --sysroot parameters are already added, but contain a space between the double hypens, resulting in unknown argument errors.

For example, building `harfbuzz:x64-android` gives me this:

```
Build started at 2021-02-16T15:08:56.556844
Main binary: D:\Devel\vcpkg\downloads\tools\python\python-3.9.0-x64\python.exe
Build Options: -Dicu=disabled -Dgraphite=disabled -Dglib=disabled -Dfreetype=enabled -Dgobject=disabled -Dcairo=disabled -Dfontconfig=disabled -Dintrospection=disabled -Ddocs=disabled -Dtests=disabled -Dbenchmark=disabled -Ddebug=false '-Dcmake_prefix_path=['"'"'D:/Devel/Monster/Dev/External/vcpkg/vcpkg/installed/x64-android-sgi-shipping'"'"','"'"'D:/Devel/Monster/Dev/External/vcpkg/vcpkg/installed/x64-android-sgi-shipping/debug'"'"']' -Dprefix=D:/Devel/Monster/Dev/External/vcpkg/vcpkg/packages/harfbuzz_x64-android-sgi-shipping -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Ddefault_library=static -Dwrap_mode=nodownload '--native-file D:/Devel/Monster/Dev/External/vcpkg/vcpkg/buildtrees/harfbuzz/meson-nativ-x64-android-sgi-shipping.log' '--native-file D:/Devel/Monster/Dev/External/vcpkg/vcpkg/buildtrees/harfbuzz/meson-nativ-x64-android-release.log'
Python system: Windows
The Meson build system
Version: 0.56.99
Source dir: D:\Devel\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean
Build dir: D:\Devel\vcpkg\buildtrees\harfbuzz\x64-android-rel
Build type: native build
Project name: harfbuzz
Project version: 2.7.4
None of 'CFLAGS' are defined in the environment, not changing global flags.
None of 'LDFLAGS' are defined in the environment, not changing global flags.
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity testing C compiler: C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
Is cross compiler: False.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity check compiler command line: C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe D:\Devel\vcpkg\buildtrees\harfbuzz\x64-android-rel\meson-private\sanitycheckc.c -o D:\Devel\vcpkg\buildtrees\harfbuzz\x64-android-rel\meson-private\sanitycheckc.exe -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fPIC -fasynchronous-unwind-tables -ffunction-sections -fdata-sections -fstack-protector-strong -fstrict-aliasing -fthreadsafe-statics -fvisibility=hidden -fvisibility-inlines-hidden -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_REENTERANT --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/sysroot -isystem C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/x86_64-linux-android -isystem C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -O2 -DNDEBUG -Os -g2 -gdwarf-2 -fomit-frame-pointer -DNDEBUG -flto=thin -ID:/Devel/vcpkg/vcpkg/installed/x64-android-sgi-shipping/include -pipe -D_FILE_OFFSET_BITS=64 - -target=x86_64-none-linux-android21 - -gcc-toolchain=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64 - -sysroot=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/sysroot -LD:/Devel/vcpkg/installed/x64-android-sgi-shipping/lib
Sanity check compile stdout:

-----
Sanity check compile stderr:
clang: error: unknown argument '-target=x86_64-none-linux-android21'; did you mean '--target=x86_64-none-linux-android21'?
clang: error: unknown argument '-gcc-toolchain=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64'; did you mean '--gcc-toolchain=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64'?
clang: error: unknown argument '-sysroot=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/sysroot'; did you mean '--sysroot=C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/sysroot'?
clang: error: -E or -x required when input is from standard input
clang: error: -E or -x required when input is from standard input
clang: error: -E or -x required when input is from standard input

-----

..\src\f4d3aa1127-a820a32874.clean\meson.build:1:0: ERROR: Compiler C:/Windows/Temp/2CB702BC-7649-4C41-B9AE-C2F75D8AC52A/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe can not compile programs.
```

2021-02-16 23:23 UTC, Neumann-A commented
@jwtowner merge with master. The regex for meson should be fixed.

2021-02-16 23:38 UTC, jwtowner commented
@Neumann-A 
> @jwtowner merge with master. The regex for meson should be fixed.
Hi, I've been working out of master and testing this on our build machines which simply clone from microsoft:master. Is there a specific PR or commit where some of this was fixed?

2021-02-16 23:54 UTC, Neumann-A commented
should be #15867

2021-02-17 02:35 UTC, jwtowner commented
@Neumann-A 
Sadly, every combination of quotes and escapes that I've tried does not appear to work. Looking in the generated `cmake-vars-***.cmake.log` file shows that none of them result in the desired value.

What I've tried so far:

```
string(APPEND CMAKE_CXX_FLAGS " -isystem \"${CMAKE_SYSROOT}/usr/include\"")
string(APPEND CMAKE_CXX_FLAGS " -isystem \\\"${CMAKE_SYSROOT}/usr/include\\\"")
string(APPEND CMAKE_CXX_FLAGS " -isystem\\ \"${CMAKE_SYSROOT}/usr/include\"")
string(APPEND CMAKE_CXX_FLAGS " \"-isystem \\\"${CMAKE_SYSROOT}/usr/include\\\"\"")
string(APPEND CMAKE_CXX_FLAGS " \\\"-isystem \\\"${CMAKE_SYSROOT}/usr/include\\\"\\\"")
string(APPEND CMAKE_CXX_FLAGS " '-isystem \"${CMAKE_SYSROOT}/usr/include\"'")
string(APPEND CMAKE_CXX_FLAGS " '-isystem \\\"${CMAKE_SYSROOT}/usr/include\\\"'")
string(APPEND CMAKE_CXX_FLAGS " \"-isystem '${CMAKE_SYSROOT}/usr/include'\"")
string(APPEND CMAKE_CXX_FLAGS " -isystem\\ \\\"${CMAKE_SYSROOT}/usr/include\\\"")
string(APPEND CMAKE_CXX_FLAGS " -isystem\\ '${CMAKE_SYSROOT}/usr/include'")
```

2021-02-17 06:03 UTC, jwtowner commented
I've created PR #16260 that fixes two independent issues in `scripts/cmake/vcpkg_configure_meson.cmake` I ran into above when trying to build harfbuzz for android, working off of the changes in this PR and the changes in my post [here](https://github.com/microsoft/vcpkg/pull/15605#issuecomment-780117968).

2021-02-17 11:29 UTC, xandox commented
@jwtowner Thank you very match, I will apply your changes to `scripts/get_cmake_vars/CMakeLists.txt` quite letter.

2021-02-17 11:35 UTC, Neumann-A commented
@jwtowner do you know the result you want to have in `cmake-vars-***.cmake.log`. But it is very likely that `libtool` will fail anyway however you quote the paths.

2021-02-17 17:49 UTC, jwtowner commented
> @jwtowner do you know the result you want to have in `cmake-vars-***.cmake.log`. But it is very likely that `libtool` will fail anyway however you quote the paths.

Yeah, I think the issue is in libtool and possibly in Meson or elsewhere now as well. As a test, I manually modified vcpkg_configure_meson.cmake to format the CFLAGS/CXXFLAGS as desired, and despite showing up correctly in the cmake-vars logs, they still were being passed incorrectly to Meson. And for what it's worth, I just ran into the same issue with libvpx on Android, which uses a custom configure/make based build process. So even if we somehow fix it for Meson, I'd still going to need to rely on the directory symlink to remove spaces from the directory path, and therefore fixing it probably isn't a high priority issue.

2021-02-17 23:09 UTC, jwtowner commented
@xandox 
So, great news. I've managed to get this working on iOS as well and have found CMake variables for the `-isystem` flags for general use. For iOS and macOS, there are completely different variables we have to look at for SYSROOT and such. CMAKE_OSX_SYSROOT  instead of CMAKE_SYSROOT, and so on.

It also turns out that all of the extra system include directories are already added to `CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES` and `CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES` by the underlying toolchain configurations, so I've changed the code to enumerate those lists and add each of them to the CFLAGS and CXXFLAGS.

Here's the full updated `[scripts/get_cmake_vars/CMakeLists.txt](https://gist.github.com/jwtowner/da8df13eb5c1a225f323cb753465b591)` that I'm using.

2021-03-19 20:51 UTC, ras0219-msft requested changes
Thanks for the continued great work!

I'd strongly prefer the port changes be pulled out before the final merge and made into separate PRs. Changes to the core scripts helpers must maintain backwards compatibility with older versions, so it should never be necessary to simultaneously change ports with the script changes. It's totally fine to include the port changes while doing development though; it's great to ensure that the final change actually fixes the problems you're looking to solve :)

2021-03-19 20:51 UTC, ras0219-msft commented on ports/libidn2/portfile.cmake
> +	COPY_SOURCE
```suggestion
	  COPY_SOURCE
```

2021-03-19 20:51 UTC, ras0219-msft commented on ports/openmpi/keep_isystem.patch
> ++                ;;
Could this be submitted upstream?

2021-03-19 20:51 UTC, ras0219-msft commented on scripts/cmake/vcpkg_build_make.cmake
> +                        COMMAND ${MAKE_BASH} ${NO_PARALLEL_MAKE_CMD_LINE}
Can we split this off into a separate PR?

2021-03-19 20:51 UTC, ras0219-msft commented on scripts/cmake/vcpkg_configure_make.cmake
> +    if(in_system MATCHES "Linux")
```suggestion
    unset(${out_var} PARENT_SCOPE)
    if(in_system MATCHES "Linux")
```

2021-03-19 20:51 UTC, ras0219-msft commented on scripts/cmake/vcpkg_configure_make.cmake
> +    string(APPEND CFLAGS_${_SUFFIX} " ${VCPKG_DETECTED_CMAKE_INCLUDE_FLAG_C}${VCPKG_DETECTED_CMAKE_INCLUDE_FLAG_C_SEP}${CURRENT_INSTALLED_DIR}/include")
This probably needs (at a minimum) to surround the added path with quotes.

2021-03-19 20:51 UTC, ras0219-msft commented on scripts/cmake/vcpkg_configure_make.cmake
> +macro(_vcpkg_determine_autotools_host_os out_var)
The cross-compilation model that vcpkg is pursuing is that each "build" should target a single platform; this enables each triplet to be completely independent and fully "normalized" (we don't need a `x64-windows-cross-to-x64-linux` triplet, et al).

However, this means that any ports that need to perform "native" builds must be taught to have an option to provide prebuilt executables instead. Then, we can use host dependencies [1] to cause the cross build to depend on the native build of the package, reusing the native build's generators.

For example, something like
```cmake
# portfile.cmake
if(HOST_TRIPLET STREQUAL TARGET_TRIPLET)
  set(OPTIONS -DBUILD_GENERATORS=ON)
else()
  set(OPTIONS -DBUILD_GENERATORS=OFF -DMY_GENERATOR1=${CURRENT_HOST_INSTALLED_DIR}/tools/${port}/mygenerator${VCPKG_HOST_EXECUTABLE_SUFFIX})
endif()
```

This means that we should be doing as little as possible to detect the host system in a cross scenario; all needed bits should be precomputed during the separate native package build and put in files for the cross build to consume after.

[1] https://github.com/microsoft/vcpkg/blob/master/docs/users/host-dependencies.md

2021-03-19 20:51 UTC, ras0219-msft commented on scripts/get_cmake_vars/CMakeLists.txt
> +    foreach(_arch ${CMAKE_OSX_ARCHITECTURES})
-arch and sysroot are added below in `_vcpkg_adjust_flags` (this probably changed since your initial PR)

2021-03-19 20:51 UTC, ras0219-msft commented on versions/l-/libidn2.json
> +      "git-tree": "8affd85878049fa1b8af42706c2c2dd4a7bf137f",
We must not replace existing library versions.

2021-04-01 09:45 UTC, xandox commented on ports/openmpi/keep_isystem.patch
> ++                ;;
I created issue for upstream https://github.com/open-mpi/ompi/issues/8573

2021-04-01 09:45 UTC, xandox commented on scripts/cmake/vcpkg_build_make.cmake
> +                        COMMAND ${MAKE_BASH} ${NO_PARALLEL_MAKE_CMD_LINE}
Yep. will do

2021-04-01 09:46 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +    string(APPEND CFLAGS_${_SUFFIX} " ${VCPKG_DETECTED_CMAKE_INCLUDE_FLAG_C}${VCPKG_DETECTED_CMAKE_INCLUDE_FLAG_C_SEP}${CURRENT_INSTALLED_DIR}/include")
ok

2021-04-01 14:16 UTC, xandox commented on scripts/cmake/vcpkg_build_make.cmake
> +                        COMMAND ${MAKE_BASH} ${NO_PARALLEL_MAKE_CMD_LINE}
done

2021-04-01 15:20 UTC, xandox commented on scripts/cmake/vcpkg_configure_make.cmake
> +macro(_vcpkg_determine_autotools_host_os out_var)
But how said relates to `_vcpkg_determine_autotools_host_os`? 
This macro need only for set correct triplets for `--build` and `--host` flags.

2021-04-01 15:31 UTC, xandox commented
>I'd strongly prefer the port changes be pulled out before the final merge and made into separate PRs. Changes to the core scripts helpers must maintain backwards compatibility with older versions, so it should never be necessary to simultaneously change ports with the script changes. 

I am not sure I know how to organize this.
If port fails to build during checks, I should fix it, check again, and then make separated PR for it?
But what if fixes will be incompatible with old scripts versions? I even do not say it gone take forever.

2021-04-01 16:43 UTC, xandox commented
I made PRs for current ports.

2021-04-13 14:13 UTC, xandox commented
Hello, Can someone fix `osx` builder. It seems that it out of disk space.

2021-04-13 14:38 UTC, JackBoosY commented
@xandox We'll fix this tomorrow.

2021-04-15 02:55 UTC, JackBoosY requested changes
Please run command `vcpkg x-add-version --all` then commit the changes.

2021-04-21 03:49 UTC, JackBoosY commented
Should wait for https://github.com/microsoft/vcpkg/pull/17227 or #17376 merge.

2021-04-21 04:01 UTC, dg0yt commented
Instead of proliferating `_vcpkg_determine_autotools_target_arch_...`, wouldn't it make sense to move the responsibility to provide matching variables from the triplet files? The triplet files can be customized by the user, in particular when new targets appear. And the values would become available to ports which don't use `vcpkg_configure_make`.
(This is a general question, not a direct request to change this PR.)

2021-04-21 15:01 UTC, xandox commented
@dg0yt 
`_vcpkg_determine_autotools_target_cpu` creates output based on `VCPKG_TARGET_ARCHITECTURE` which comes directly from triplet file. 
`_vcpkg_determine_autotools_target_os` creates output based on `VCPKG_DETECTED_CMAKE_SYSTEM_NAME` which comes from android toolchain file or directly from current host os. Why do not use value from triplet file see comment https://github.com/microsoft/vcpkg/pull/15605#discussion_r597963125

2021-04-21 16:51 UTC, dg0yt commented
> `_vcpkg_determine_autotools_target_cpu` creates output based on `VCPKG_TARGET_ARCHITECTURE` which comes directly from triplet file.
> `_vcpkg_determine_autotools_target_os` creates output based on `VCPKG_DETECTED_CMAKE_SYSTEM_NAME` which comes from android toolchain file or directly from current host os. Why do not use value from triplet file see comment [#15605 (comment)](https://github.com/microsoft/vcpkg/pull/15605#discussion_r597963125)

Maybe I failed to make my point. I want to try in another way: 
When users want to target autotools' `x86_64-w64-mingw32` [!] or `arm2025-linux-androidNT`, it would be easy if they could put this literally in a variable in the triplet file. (You might still use these functions when the variable is not set.)
On the other hand I have the impression that there is no function to get variables from the triplet file matching the *host*, at the moment.

2021-04-21 21:23 UTC, xandox commented
> When users want to target autotools' x86_64-w64-mingw32 [!] or arm2025-linux-androidNT, it would be easy if they could put this literally in a variable in the triplet file.

Not sure this is a good idea at all. However it could be done letter when somebody really will need it.

2021-04-21 21:24 UTC, xandox commented
> On the other hand I have the impression that there is no function to get variables from the triplet file matching the host, at the moment.

Not sure I got what you mean.

2021-04-22 07:16 UTC, dg0yt commented
> > On the other hand I have the impression that there is no function to get variables from the triplet file matching the host, at the moment.
> 
> Not sure I got what you mean.

I suggested to get the autoconf triplet from a variable in vcpkg's triplet files. For cross compiling, autoconf triplets are needed for the target and for the host. However, `scripts/port.cmake` only loads vcpkg's triplet file for the target, so there is no way get the proposed variable for the host.

2021-04-23 19:45 UTC, ras0219-msft commented
In order to work broadly across all C++ buildsystems, we don't want to specialize vcpkg heavily for those which build simultaneously for host and target (or in autotools parlance: build and host). This also has additional advantages as it means we can separately package and reuse tool builds from different targets as long as the host is the same.

Our current desired behavior is to:
1. Run a native build (possibly full, possibly reduced to just built-time tools) which is packaged in a reusable way
2. Run a target build, without rebuilding the build-time tools -- use them from the previous native build.

This also ensures that our triplets stay completely orthogonalized and users don't need to produce the cross-product of all possible native+targets. It is possible in the future that we can add specializations for autotools/meson/etc that start leaking information between these boundaries (such as perhaps a 'port' that actually just generates a 'host compiler info' file), but this is our current approach.

2021-04-24 05:26 UTC, dg0yt commented
@ras0219-msft I'm not sure if the last post in response to my question. If yes, I'm still misunderstood. We agree on the orthogonality of native and target builds.

What I proposed is that the autoconf triplets shall be *declared* in vcpkg triplet files, instead of being constructed in a *procedural* way. I admit that declaring the autoconfig triplet in the vcpkg triplet file can be seen as leaking buildsystem details into more general vcpkg files. But it is a single variable, and it is a welcome hook for users with different CPUs or OS, Probably it is is also useful for some portfiles (cf. `git grep '[-]-host`).

Examples:
- CPUs: ARMv5, S390x (community triplet)
- OS: FreeBSD (community triplet)
- mingw:
  - x86_64-w64-mingw32 instead of x86_64-pc-mingw32 (cf. icu portfile)
  - i686-w64-mingw32.static (MXE.cc)

At least for mingw, the triplet would also guide compiler lookup in `scripts/toolchains/mingw.cmake`.

2021-04-24 08:11 UTC, Neumann-A commented
you know there is `VCPKG_MAKE_BUILD_TRIPLET` which is totally undocumented but exists ;)

2021-04-24 08:26 UTC, dg0yt commented
> you know there is `VCPKG_MAKE_BUILD_TRIPLET` which is totally undocumented but exists ;)

I see, it is somewhat hidden, documented with `BUILD_TRIPLET` parameter for `vcpkg_configure_cmake`, but not in the general triplet files documentation. In this state, it is clear why it is not used in other scripts.

Good to learn about it now: If it is really meant to stay, we may have to watch out for it in #17438....

2021-05-19 05:51 UTC, JackBoosY commented
Depends on https://github.com/microsoft/vcpkg/pull/17983.

2021-05-21 02:19 UTC, JackBoosY commented
Ping @ras0219 @ras0219-msft for reply.

2021-05-26 13:51 UTC, xandox commented
up

2021-05-26 15:45 UTC, m-kuhn commented
Thanks for this, it fixes building libpq :+1: 

It still fails with fontconfig

```
$ cat buildtrees/fontconfig/build-arm64-android-dbg-err.log

gcc: error: unrecognized command line option '--target=aarch64-none-linux-android21'
gcc: error: unrecognized command line option '--gcc-toolchain=/opt/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64'
gcc: error: unrecognized command line option '-fno-limit-debug-info'
make[4]: *** [Makefile:667: fc-case] Error 1
make[3]: *** [Makefile:670: fccase.h] Error 1
make[2]: *** [Makefile:415: all] Error 2
make[1]: *** [Makefile:602: all-recursive] Error 1
make: *** [Makefile:486: all] Error 2
```

2021-05-26 17:30 UTC, m-kuhn commented
@xandox here is the complete list of logs

https://gist.github.com/m-kuhn/0fec06b59597d3a20581bdb0f20f13a8

2021-05-28 14:43 UTC, xandox commented
@m-kuhn thank you.
It's looks like there are problem with tool which must be build for host machine and not for target. This package needs be pached. There a lot of packages with same problem and it's out of scope current pr.

2021-05-28 15:41 UTC, dg0yt commented
@mkuhn @xandox Looks like a draft PR for cross-builds was closed (not merged) just a few days ago, #15869.

2021-05-28 15:58 UTC, m-kuhn commented
Thank you for looking into it and sharing the findings @xandox and thanks for the additional pointer @dg0yt 

Would be great to see vcpkg_configure_make fixed soon so the path to follow up issues is cleared

2021-05-28 17:01 UTC, dg0yt commented
@mkuhn From config.log
~~~
Found candidate GCC installation: /opt/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x
Found candidate GCC installation: /opt/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
~~~
and this gcc doesn't understand the Anroid parameters.

2021-05-28 20:38 UTC, m-kuhn commented
I guess we should convince it to use clang rather than trying to adjust the params?!

2021-05-29 06:13 UTC, m-kuhn commented
@dg0yt isn't that just some noise from calling `clang -v` without `--gcc-toolchain`? Subsequent calls specifiy the `--gcc-toolchain` explicitly. I also checked libpq logs, the same output is in there and doesn't prevent it from building.

2021-05-29 06:39 UTC, m-kuhn commented
fc-case is compiled for the build system, using `CC_FOR_BUILD` it's using the correct compiler (build system `gcc`) but it also uses `CFLAGS` for cross compiling, which is incorrect here.

2021-05-29 06:48 UTC, dg0yt commented
@m-kuhn Please open an issue for port font-config. The bug is build2.patch. Upstream compiles with CPPFLAGS (preprocessor flags) but vcpkg adds CFLAGS (C compiler flags)

2021-05-29 06:56 UTC, m-kuhn commented
Good catch, https://github.com/microsoft/vcpkg/issues/18181

2021-05-29 07:49 UTC, dg0yt commented
Maybe this PR indeed needs an update to care for #18181: Ports which also compile binaries for the the host seem to need variables for the host triplet
- `CC_FOR_BUILD`
- `CFLAGS_FOR_BUILD`
- ...

Providing these variables might controlled by an option to `vcpkg_configure_make`, but it must be possible for native builds: It allows to remove patches which might be regarded as early attempts to handle the absence of these variables.

2021-06-01 14:52 UTC, xandox commented
@dg0yt, @m-kuhn I added CFLAGS_FOR_BUILD and CC_FOR_BUILD, and etc. But it does not help for fontconfig, fc-cache is not a build tool as appeared. I known too little about fontconfig for fix that.

2021-06-01 16:18 UTC, m-kuhn commented
@xandox the affected part here is `fc-case`

Both, this fix and removing `fc-cache` from the portfile are required to make the build happy.
`fc-cache` seems to be a common source of pborlems https://github.com/microsoft/vcpkg/issues/17557 https://github.com/microsoft/vcpkg/issues/18170

2021-06-01 16:26 UTC, xandox commented
Part with `fc-case` easy to fix, but only with this pull request. 
But about part with `fc-cache` I am not sure, 
https://github.com/microsoft/vcpkg/issues/18170#issuecomment-850599430
I am agree with @Neumann-A that `fc-cache` must be a host tool. But right now it is not. Port have to be patched.

2021-06-01 16:33 UTC, dg0yt commented
> I added CFLAGS_FOR_BUILD and CC_FOR_BUILD, and etc. But it does not help for fontconfig, fc-cache is not a build tool as appeared. I known too little about fontconfig for fix that.

Always providing the variables is sufficient for this PR.

2021-06-01 16:36 UTC, dg0yt commented
(continuing) 
Making use of the new variables, hopefully rolling back some now-obsolete patches, fixing fontconfig, is left to coming PRs.
Thank you very much.

2021-06-01 17:31 UTC, m-kuhn commented
+1 to isolate this patch as it is and leave the `fc-cache` issue for a separate PR

2021-07-19 03:27 UTC, strega-nil-ms commented
What's going on with this PR? Should we get this up to date and merge?

2021-07-19 07:58 UTC, JackBoosY commented
> What's going on with this PR? Should we get this up to date and merge?

+1, does the PR ready for review now?

2021-07-19 09:44 UTC, xandox commented
I will update it today. 
Main functional already ready.

2021-07-19 19:06 UTC, strega-nil-ms commented
Cool, @JackBoosY could you review today?

2021-07-20 06:11 UTC, dg0yt commented on ports/libiconv/portfile.cmake
> +if(NOT VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_CROSSCOMPILING)
What is the point of this change? Port libiconv could be empty when the target has iconv, but it must be built
- when the target is Windows.
- when the target is ...

But it doesn't matter if we are cross compiling.

2021-07-20 12:22 UTC, xandox commented on ports/libiconv/portfile.cmake
> +if(NOT VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_CROSSCOMPILING)
If I am building libiconv on linux-x64 for linux-arm64 without VCPKG_CROSSCOMPILING it will let empty, for example.

2021-07-20 13:42 UTC, dg0yt commented on ports/libiconv/portfile.cmake
> +if(NOT VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_CROSSCOMPILING)
> If I am building libiconv on linux-x64 for linux-arm64 without VCPKG_CROSSCOMPILING it will let empty, for example.

IIUC that's just the intention of that code block: "iconv is empty unless built for Windows or Android." Probably this assumes iconv system libraries on linux, osx or bsd, and maybe this is not 100% right. But it doesn't matter if you compile from a different platform or natively.

Can you just remove the iconv changes from this PR? IMO they seem to be unrelated to "vcpkg_configure_make flags for android".

2021-07-21 02:31 UTC, JackBoosY commented
Can you please resolve the file conflicts?

2021-07-21 08:18 UTC, xandox commented on ports/libiconv/portfile.cmake
> +if(NOT VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_CROSSCOMPILING)
ok, done

2021-07-21 08:19 UTC, xandox commented
> Can you please resolve the file conflicts?

done

2021-07-21 10:16 UTC, dg0yt reviewed
I would like to note that the `get_cmake_vars` project is transforming into a unit which no longer reports the *actual* cmake variables. This is probably beneficial for some use cases, but it can fail miserably for other uses. 
My preference would be a clearer separation of concerns, e.g. by using different variables for computed *effective* properties, and/or by offering a separate entry point for getting these properties.

2021-07-21 10:16 UTC, dg0yt commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endforeach()
I don't see the benefit here. Implicit directories are needed to be known in order to find a file in build system configuration steps, but they do not need to be given explicitly to the compiler.

2021-07-21 10:27 UTC, xandox commented
> I would like to note that the `get_cmake_vars` project is transforming into a unit which no longer reports the _actual_ cmake variables. 

Not sure what you mean. Which variable it reports now?

> My preference would be a clearer separation of concerns, e.g. by using different variables for computed _effective_ properties, and/or by offering a separate entry point for getting these properties.

It reports all properties, consumer could use only what they need.

2021-07-21 10:28 UTC, xandox commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endforeach()
Unfortunately for some cases it needed to be explicitly provided. Especially for macos native compiler.

2021-07-21 10:29 UTC, Neumann-A commented
Why do we need host cmake vars? VCPKG should not build for the host but only the target! host binaries are provided by host dependencies! Otherwise patch the buildsystem

2021-07-21 10:34 UTC, xandox commented
> 
> 
> Why do we need host cmake vars? VCPKG should not build for the host but only the target! 

Host cmake vars needed for host tools used during compilation (file generators and so on). 

>host binaries are provided by host dependencies! Otherwise patch the buildsystem

It's good idea but not for all ports in single pull request. Let's merge this one which works, and then everyone who would like to patch every single autotools port to separate host-build-tools from main package could do it in their own rithm.

2021-07-21 10:57 UTC, dg0yt commented
> > I would like to note that the `get_cmake_vars` project is transforming into a unit which no longer reports the _actual_ cmake variables.
> 
> Not sure what you mean. Which variable it reports now?

All the added lines which look like `string(APPEND CMAKE_...)` transform the original value of `CMAKE_...`.

2021-07-21 11:02 UTC, dg0yt commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endforeach()
> Unfortunately for some cases it needed to be explicitly provided. Especially for macos native compiler.

Now I wonder how I can build autotools projects without vcpkg/cmake. 

(All really meant constructive. I just want to avoid pitfalls from my personal cross-platform cmake experience.)

2021-07-21 11:04 UTC, xandox commented
> 
> 
> > > I would like to note that the `get_cmake_vars` project is transforming into a unit which no longer reports the _actual_ cmake variables.
> > 
> > 
> > Not sure what you mean. Which variable it reports now?
> 
> All the added lines which look like `string(APPEND CMAKE_...)` transform the original value of `CMAKE_...`.

So, you suggest to make another one project like `get_cmake_vars_ex`? Is `get_cmake_vars` project needed only for other buildsystems to provide correct options?

2021-07-21 11:21 UTC, xandox commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endforeach()
Yep. good catch. 
I am not good in autotools or macos, so some explanation could be not accurate. But what I saw is. There are two different compile system in macos (how I understand this). First one which `cmake` uses usually placed in `/Library/....`. The compiler in this system unusable without all this flags and include directories. And cmake provide them to it. The second one placed in `/usr/bin` and if you just run `configure.sh` for some autotools package very probably that it will select second one system. And it is what happen right now in `master` when you install some `autotools` package by `vcpkg`.  So there is some inconsistent. 

When I just start this PR I tried to leave this behaviour unchanged. But guys decided it's not good idea. And now I force `autotools` use the same compiler as `cmake`

2021-07-21 16:43 UTC, dg0yt commented on scripts/get_cmake_vars/CMakeLists.txt
> +    endforeach()
> When I just start this PR I tried to leave this behaviour unchanged. But guys decided it's not good idea. And now I force `autotools` use the same compiler as `cmake`

Yes, this is a good thing.

> I am not good in autotools or macos

I wouldn't claim to be an expert. This discussion is also an invitation for others to help with feedback.

2021-07-21 16:56 UTC, dg0yt commented
> > > > I would like to note that the `get_cmake_vars` project is transforming into a unit which no longer reports the _actual_ cmake variables.
> > > 
> > > 
> > > Not sure what you mean. Which variable it reports now?
> > 
> > 
> > All the added lines which look like `string(APPEND CMAKE_...)` transform the original value of `CMAKE_...`.
> 
> So, you suggest to make another one project like `get_cmake_vars_ex`? Is `get_cmake_vars` project needed only for other buildsystems to provide correct options?

I didn't want to jump into proposing a particular implementation.  

Following the *single responsibility principle* and the *principle of least surprise*, `get_cmake_vars` should do just that: report cmake variables. Still, output may vary by platform, to cover special properties.
And then another script/function can compose the variables to form new variables.  It doesn't even need another CMake project, it will simply use the output of `get_cmake_vars`. If the purpose is providing configuration information for build system, I would probably choose a name like `get_build_configuration`.

Disclaimer: This is just personal opinion of an external contributor.

2021-09-08 00:13 UTC, strega-nil-ms commented
This does look good, but it needs to be updated for the new style of `z_vcpkg_get_cmake_vars`; @xandox are you interested in updating the PR for the new world order; otherwise, @m-kuhn do you want to take over this PR?

2021-09-08 09:06 UTC, xandox commented
@strega-nil-ms @m-kuhn Sorry, but right now I have no time to work on this PR. If someone would take over this I will be appreciated.

2021-09-10 14:36 UTC, m-kuhn commented
I am afraid this pull request is outside my comfort zone and I don't have the time available to expand this zone at the moment.

Even if it was within the zone, what I think this needs currently is:
1. a core maintainer to comment on https://github.com/microsoft/vcpkg/pull/15605#issuecomment-884341618 - which as far as I can see is the only open question at the moment
2. a rebase / merge of master

and since number 2 depends on number 1 it will be hard to take over for anyone at the moment

2022-01-06 16:44 UTC, JackBoosY commented
If you want to continue this PR, please reopen it.

2022-01-06 16:44 UTC, closed without merging