[yaml-cpp] Support dynamic library on linux
microsoft/vcpkg pull request #15626
Opened 2021-01-13 18:45 UTC by vmiheer

**This prevents unixy compilers erroring out after seeing __declspec(dllimport|export)**
This is temporary change, ideally it should go upstream.

- Which triplets are supported/not supported? Have you updated the CI baseline?
linux-x64-dynamic, I don't think linux-x64-dynamic is official triplet so likely no CI impact.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

2021-01-14 02:07 UTC, NancyLi1013 reviewed
Could you please also bump CONTROL file?

`Add Port-Version: 1`

2021-01-14 02:07 UTC, NancyLi1013 commented on ports/yaml-cpp/portfile.cmake
> +endif()
Can you make a patch directly based on the current source instead of downloading from upstream?

2021-01-14 02:36 UTC, vmiheer commented on ports/yaml-cpp/portfile.cmake
> +endif()
Like putting patch in vcpkg repository?

2021-01-14 23:36 UTC, vmiheer commented on ports/yaml-cpp/portfile.cmake
> +endif()
@NancyLi1013, updated port version in CONTROL. I am not sure about https://github.com/microsoft/vcpkg/pull/15626#discussion_r556996841

2021-01-15 01:41 UTC, NancyLi1013 commented on ports/yaml-cpp/portfile.cmake
> +endif()
Yes, putting patch in vcpkg repository.

2021-01-15 02:13 UTC, vmiheer commented on ports/yaml-cpp/portfile.cmake
> +endif()
I think the patch is not related to the library support being compatible with vcpkg the patch deserves to be in upstream repository.

2021-01-15 07:07 UTC, NancyLi1013 requested changes

2021-01-15 07:07 UTC, NancyLi1013 commented on ports/yaml-cpp/CONTROL
>  Version: 0.6.3
```suggestion
Version: 0.6.3
Port-Version: 1
```

2021-01-15 07:07 UTC, NancyLi1013 commented on ports/yaml-cpp/CONTROL
> +Port-Version: 1
```suggestion
```

2021-01-15 07:13 UTC, NancyLi1013 commented on ports/yaml-cpp/portfile.cmake
> +endif()
Your consideration is reasonable. But we recommend to use the patch provided by vcpkg to avoid the patch being applied failed due to some external reasons.

2021-01-15 09:25 UTC, NancyLi1013 commented
Hi @vmiheer 

Could you please merge master to this PR?

Please also run the command `vcpkg x-add-version yaml-cpp`.

2021-01-16 05:10 UTC, vmiheer commented
All done

2021-01-27 07:12 UTC, NancyLi1013 commented
@vmiheer 

Could you please merge master to this PR?

2021-01-28 05:58 UTC, vmiheer commented
Done

2021-03-04 06:44 UTC, NancyLi1013 commented
/azp run

2021-03-05 05:53 UTC, NancyLi1013 requested changes

2021-03-05 05:53 UTC, NancyLi1013 commented on ports/yaml-cpp/portfile.cmake
>  endif()
Could you please update these codes as follows?

`string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" YAML_BUILD_SHARED_LIBS)`

Please see the doc https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md

2021-03-05 05:53 UTC, NancyLi1013 commented on ports/yaml-cpp/portfile.cmake
> +endif()
```suggestion
if (NOT WIN32 AND YAML_BUILD_SHARED_LIBS)
    vcpkg_apply_patches(
       SOURCE_PATH ${SOURCE_PATH}
       PATCHES jbeder_yaml-cpp_958.patch)
endif()
```
Seems that `jbeder_yaml-cpp_958.patch` is missing in this PR. So I wonder where do you get it now?

2021-04-02 07:14 UTC, NancyLi1013 commented
@vmiheer 

Could you please address the review suggestions?

2021-04-23 06:10 UTC, NancyLi1013 commented
Is work still being done for this PR? @vmiheer

2021-04-24 20:36 UTC, vmiheer commented
Sorry for late reply, I was busy with other things. I have rebased the branch on master and added the patch file in the folder. I tested locally and seem to be fine.

2021-04-25 01:44 UTC, NancyLi1013 commented
You also need to address the review suggestions @vmiheer.

2021-04-25 18:11 UTC, vmiheer commented
I have added: https://github.com/vmiheer/vcpkg/commit/85bf14c032a3a53e4f144ba4a16c9d85c7d80445

2021-05-25 10:14 UTC, NancyLi1013 commented
If you don't have enough time to continue working on this PR now, you can convert this PR to draft until all work have been done  on your sides. @vmiheer

2021-05-26 20:45 UTC, closed without merging