[vtk] use patch for QT_NO_KEYWORDS support from upstream
microsoft/vcpkg pull request #15667
Opened 2021-01-15 10:42 UTC by dweckmann

**Describe the pull request**

- What does your PR fix? It apply upstream patches (already merged), to support QT_NO_KEYWORDS. This is absolutely mandatory if you use VTK with other frameworks that define `slots, signals, ...` keywords. This doesn't change anything in VTK itself

2021-01-18 02:42 UTC, JackBoosY commented
Can you simply update vtk to apply these changes?

2021-01-18 05:26 UTC, dweckmann commented
> Can you simply update vtk to apply these changes?

This patch is applied on master branch. There is no released version that includes them.

2021-01-18 05:54 UTC, JackBoosY approved these changes

2021-01-18 05:55 UTC, JackBoosY commented
cc @Neumann-A @cenit for review this PR deeper.

2021-01-18 06:02 UTC, JackBoosY requested changes

2021-01-18 06:02 UTC, JackBoosY commented on ports/vtk/portfile.cmake
> +        0002-Qt-enforce-QT_NO_KEYWORDS-builds-by-VTK-itself.patch
```suggestion
        # Remove these 2 official patches in the next update
        0001-Qt-support-QT_NO_KEYWORDS-builds.patch
        0002-Qt-enforce-QT_NO_KEYWORDS-builds-by-VTK-itself.patch
```

2021-01-18 06:03 UTC, JackBoosY commented
Since you closed the modify for other mantainer. Please do the following step:
1. update this branch from vcpkg master.
2. rebuild vcpkg
3. use command `./vcpkg x-add-version --all`
4. commit the changes.

2021-01-18 07:14 UTC, Neumann-A commented
This is just applying upstream patches. There is nothing to review here.

2021-01-19 05:34 UTC, dweckmann commented
> Since you've closed the modify permission for other mantainer. Please do the following step:
> 
> 1. update this branch from vcpkg master.
> 2. rebuild vcpkg
> 3. use command `./vcpkg x-add-version --all`
> 4. commit the changes.

Should be good

2021-01-19 07:36 UTC, cenit commented
integration failure looks like it is not

2021-01-19 07:49 UTC, dweckmann commented
> integration failure looks like it is not

Well, I did launch `./vcpkg x-add-version --all`, I swear :)

Ok. I will check and try again.

2021-01-19 09:01 UTC, JackBoosY approved these changes

2021-01-20 00:27 UTC, ras0219-msft requested changes
Thanks for the PR!

2021-01-20 00:27 UTC, ras0219-msft commented on ports/vtk/portfile.cmake
> +        0001-Qt-support-QT_NO_KEYWORDS-builds.patch
This file is huge -- we'd really rather not check it in to the vcpkg tree.

Instead, it can be downloaded on demand before the sources:
```
vcpkg_download_distfile(QT_NO_KEYWORDS_PATCH
  URLS "https://github.com/Kitware/VTK/commit/64265c5fd1a8e26a6a81241284dea6b3272f6db6.diff"
  FILENAME 64265c5fd1a8e26a6a81241284dea6b3272f6db6.diff
  SHA512 08991f07b30b893b14e906017b77fb700a8298a3a8906086a0c4b67688c1c0431b3d6bf890df70bd3ebf963cbb9c035b5dbcb9d7593e8c716c3a594ccb9a0fc7
)
vcpkg_from_github(
 ...
 PATCHES
   ...
   ${QT_NO_KEYWORDS_PATCH}
)
```

2021-01-20 07:21 UTC, dweckmann commented on ports/vtk/portfile.cmake
> +        0001-Qt-support-QT_NO_KEYWORDS-builds.patch
I've saw bigger path than 600 lines patch, but ok, I've done as you told. It should be good now.

2021-01-21 02:25 UTC, JackBoosY requested changes

2021-01-21 02:25 UTC, JackBoosY commented on port_versions/v-/vtk.json
> +      "git-tree": "bd26a920998f31cd8f459493069f16cd506b143f",
```suggestion
      "git-tree": "94667926df104c70c0229cc96b36ec41f3911853",
```

2021-01-21 08:35 UTC, JackBoosY approved these changes

2021-01-21 08:36 UTC, JackBoosY commented
Need test all features.

2021-01-21 19:03 UTC, strega-nil commented
@dweckmann Please rebase this onto master; I don't have access so I can't do it for you.

2021-01-22 06:19 UTC, JackBoosY commented
You still need to refresh the version record, see [my comments](https://github.com/microsoft/vcpkg/pull/15667#issuecomment-762004086).

2021-01-22 09:23 UTC, JackBoosY commented
Already merged from master.

2021-01-22 09:25 UTC, dweckmann commented
> Already merged from master.

Sorry ;)

2021-01-25 07:35 UTC, merged