Fix Mbed TLS build for Android
microsoft/vcpkg pull request #15680
Opened 2021-01-15 23:49 UTC by ahmedyarub

**Describe the pull request**
Allows using VCPKG toolchain + Android toolchain. Otherwise, we would not be able to use Android toolchain together with VCPKG building Mbed TLS. After this, SDK building should work on VCPKG.
This change can be easily extended to enable building with VCPKG + iOS/Wasm or any other cross-platform build.

*Check all that applies:*
- [x] Did a review by yourself.
- [ ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [x] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [x] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [ ] Linux
- [ ] Windows
- [x] Android
- [ ] MacOS
- [ ] IOS
- [ ] Other Platforms

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-18 02:45 UTC, JackBoosY commented
Please run command `vcpkg x-add-version --all` then commit the changes.

Thanks.

2021-01-18 03:17 UTC, ahmedalnuaimi commented
> Please run command `vcpkg x-add-version --all` then commit the changes.
> 
> Thanks.

Done

2021-01-18 03:21 UTC, ahmedyarub commented
> 
> 
> Please run command `vcpkg x-add-version --all` then commit the changes.
> 
> Thanks.

Done

2021-01-18 05:47 UTC, JackBoosY approved these changes

2021-01-18 06:05 UTC, JackBoosY commented
@ahmedyarub I found that some of the items in your comment have not yet been implemented. Is this PR ready?

2021-01-18 06:12 UTC, ahmedyarub commented
> 
> 
> @ahmedyarub I found that some of the items in your comment have not yet been implemented. Is this PR ready?

I`m sorry which comments exactly? If you are talking about Wasm and iOS support then that would be done in a separate PR during the next week.

2021-01-18 06:28 UTC, JackBoosY commented
Test all features successfully on `x86-windows` and `x64-windows-static`.

2021-01-20 02:19 UTC, ahmedyarub commented
Fixed according to https://vcpkg.readthedocs.io/en/latest/users/android/

2021-01-20 05:25 UTC, JackBoosY commented
@ahmedyarub Ready for review now?

2021-01-20 19:22 UTC, ahmedyarub commented
> 
> 
> @ahmedyarub Ready for review now?

Yes it is

2021-01-21 02:59 UTC, ras0219 requested changes
LGTM once my two comments are addressed!

2021-01-21 02:59 UTC, ras0219 commented on ports/mbedtls/portfile.cmake
> +    set(EXTRA_ARGS "-DMBEDTLS_FATAL_WARNINGS=FALSE")
Can this be applied always? Our policy is to not enable warnings as errors in package builds.

2021-01-21 02:59 UTC, ras0219 commented on ports/mbedtls/portfile.cmake
> +        OUT_SOURCE_PATH SOURCE_PATH
Could you please restore the formatting of this file to the original 4 spaces?

2021-01-21 03:12 UTC, ahmedyarub commented on ports/mbedtls/portfile.cmake
> +        OUT_SOURCE_PATH SOURCE_PATH
Done

2021-01-21 05:44 UTC, JackBoosY approved these changes

2021-01-22 02:50 UTC, JackBoosY approved these changes

2021-01-22 02:50 UTC, JackBoosY commented
Already merged from master.

2021-01-22 05:46 UTC, ahmedyarub commented
This should be ready for last review and merge.

2021-01-25 07:37 UTC, merged