[glslang] Update to 11.1.0
microsoft/vcpkg pull request #15719
Opened 2021-01-17 19:01 UTC by Luke-Filewalker

**Describe the pull request**
Update of glslang to version 11.1.0. Previous one was over a year old and had no support for KHR Ray Tracing. I also had to remove Shaderc from the ports since it is broken for some time now. Even with the update of glslang it does not build and only prevents the tests for glslang from succeeding. 

- Which triplets are supported/not supported? Have you updated the CI baseline?
Works with `glslang:x64-windows` `glslang:x64-linux` `glslang:x64-osx`

2021-01-18 06:48 UTC, JonLiu1993 approved these changes

2021-01-18 09:24 UTC, JonLiu1993 approved these changes

2021-01-19 23:58 UTC, ras0219-msft requested changes
Since it upstream has introduced official target/package names, we must begin providing those; after the `vcpkg_fixup_cmake_targets()` call, the `OGLCompiler*` files and `SPVRemapper*` files can be moved to `share/oglcompiler/` and `share/spvremapper/` respectively.

For compatibility, we can ensure the previous names still work by appending text to the end of the `share/glslang/glslang-config.cmake` of the form:
```
include(CMakeDependencyMacro)
find_dependency(OGLCompiler CONFIG)
find_dependency(SPVRemapper CONFIG)

add_library(glslang::glslang INTERFACE IMPORTED)
set_target_properties(glslang::glslang PROPERTIES INTERFACE_LINK_LIBRARIES "glslang")
# repeat for all previous names (SPVRemapper, etc)
```
This ensures that the previously supported pattern of:
```
find_package(glslang CONFIG REQUIRED)
target_link_libraries(main PRIVATE glslang::glslang)
```
continues to work.

2021-01-19 23:58 UTC, ras0219-msft commented on ports/glslang/CMakeLists-targets.patch
> +-	install(EXPORT OGLCompilerTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake)
This appears to be removing a blessed upstream name for the package: `OGLCompiler`.

2021-01-19 23:58 UTC, ras0219-msft commented on ports/glslang/CMakeLists-targets.patch
> +-            install(TARGETS SPVRemapper EXPORT SPVRemapperTargets
This appears to be removing a blessed upstream name for the package: `SPVRemapper`

2021-01-19 23:58 UTC, ras0219-msft commented on ports/glslang/CMakeLists-targets.patch
> +-        install(TARGETS HLSL EXPORT HLSLTargets
This appears to be removing a blessed upstream package name: `HLSL`

2021-01-20 08:47 UTC, Luke-Filewalker commented on ports/glslang/CMakeLists-targets.patch
> +-	install(EXPORT OGLCompilerTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake)
I think the commit diff is a bit difficult to read in this case. The TARGETS OGLCompiler is preserved in my commit. As it is with HLSL and SPVRemapper 

https://github.com/Luke-Filewalker/vcpkg/blob/952a2a3cca7570b1da7fd07d42b487fb9124fe47/ports/glslang/CMakeLists-targets.patch#L10-L23
```patch
diff --git a/OGLCompilersDLL/CMakeLists.txt b/OGLCompilersDLL/CMakeLists.txt
index 0b007d45..5bba8245 100644
--- a/OGLCompilersDLL/CMakeLists.txt
+++ b/OGLCompilersDLL/CMakeLists.txt
@@ -42,7 +42,7 @@ if(WIN32)
 endif(WIN32)
 
 if(ENABLE_GLSLANG_INSTALL)
-    install(TARGETS OGLCompiler EXPORT OGLCompilerTargets
+    install(TARGETS OGLCompiler EXPORT glslangConfig
             ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
-	install(EXPORT OGLCompilerTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake)
+	install(EXPORT glslangConfig DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake)
 endif(ENABLE_GLSLANG_INSTALL)
```

Also the previous build produced 
```
find_package(glslang CONFIG REQUIRED)
target_link_libraries(main PRIVATE glslang::HLSL glslang::SPIRV glslang::glslang glslang::OGLCompiler)
```
as an output, exactly like the new one.
Or do you mean 
```
find_package(glslang CONFIG REQUIRED)
target_link_libraries(main PRIVATE glslang::glslang)
```
should link all the targets at once?

2021-01-22 21:04 UTC, Luke-Filewalker commented
Pls someone respond: https://github.com/microsoft/vcpkg/pull/15719#discussion_r560776238

2021-02-25 09:29 UTC, NancyLi1013 commented
@Luke-Filewalker 

The latest version has been updated to 11.2.0. So could you please update the changes to this PR?

https://github.com/KhronosGroup/glslang/releases/tag/11.2.0

Also since there is LICENSE.txt file in source codes. I think it's unnecessary to add copyright.
https://github.com/KhronosGroup/glslang/blob/11.2.0/LICENSE.txt

2021-02-27 14:43 UTC, axsaucedo commented
Is this something planned for the next release of vcpkg? We'll be using this branch for the time being as we need glslang to be in pair with our submodule-in-repo build

2021-02-27 14:55 UTC, axsaucedo commented
Just testing the branch against our project but it seems I'm getting an error when binding the libraries:
```
"C:\...\build\test\test_kompute.vcxproj" (default target) (1) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'glslang.lib' [C:\...\build\test\test_kompute.vcxproj]
```

2021-02-27 15:57 UTC, Luke-Filewalker commented
You can always use the relatively old version that is currently included in the original vcpkg repo. I will update this one once I find the time. But after that, I don't know how long it takes to get this merged.

2021-02-28 16:15 UTC, MrROBUST commented
Hello. Can someone check why the 'vcpkg\packages\glslang_x64-windows\include\glslang' folder does not contain 'OSDependent' subfolder after port installation? Neither with this PR nor with the current port.

2021-04-01 06:02 UTC, JonLiu1993 commented
@Luke-Filewalker ,Can you deal with the conflicting files?

2021-05-27 06:37 UTC, JonLiu1993 commented
@Luke-Filewalker ,Can you please resolve the conflicts against master?

2021-05-28 15:58 UTC, Luke-Filewalker commented
Updated it to 11.4.0 and passes all checks except windows x86. During test "Validate version file" the following happens:

```
Error: While reading versions for port glslang from file: C:\a\1\s\versions\g-\glslang.json
       File declares version `11.4.0` with SHA: fa1249fa3b58d1e38362f3b27f020d6a5295fcd2
       But local port with the same verion has a different SHA: 1991049d53f75d60a03bf5f8d58f26a8f4c85cbf
```
No idea why the SHA is wrong just for x86

2021-05-31 07:42 UTC, Luke-Filewalker commented
passes all checks now

2021-05-31 07:54 UTC, JonLiu1993 requested changes

2021-05-31 07:54 UTC, JonLiu1993 commented on ports/glslang/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/copyright DESTINATION ${CURRENT_PACKAGES_DIR}/share/glslang)
@Luke-Filewalker ,We should replace "share/glslang" to "share/${PORT}"

2021-05-31 07:54 UTC, JonLiu1993 commented on ports/glslang/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Please revert the portfile.cmake format

2021-05-31 08:16 UTC, JonLiu1993 approved these changes

2021-05-31 08:55 UTC, JonLiu1993 commented
@Luke-Filewalker ,Please revert the portfile.cmake format,Keep it consistent with the previous file

2021-06-08 10:46 UTC, Luke-Filewalker commented
> 
> 
> @Luke-Filewalker ,Please revert the portfile.cmake format,Keep it consistent with the previous file
> 
> ports/glslang/portfile.cmake

Not exactly sure what you mean

2021-06-09 05:46 UTC, JonLiu1993 commented
> > @Luke-Filewalker ,Please revert the portfile.cmake format,Keep it consistent with the previous file
> > ports/glslang/portfile.cmake
> 
> Not exactly sure what you mean

Please keep the original format of EOL.

2021-06-17 02:24 UTC, JonLiu1993 commented
@ras0219-msft @ras0219 ,Could you help review this pr？Thanks

2021-06-24 20:51 UTC, ras0219-msft commented on ports/glslang/CMakeLists-targets.patch
> +-	install(EXPORT OGLCompilerTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake)
I was concerned about a possible `find_package(OGLCompiler)`, but I realize now that this is a `Targets.cmake`, not a `-config.cmake`.

Thanks for the explanation!

2021-06-25 08:16 UTC, Luke-Filewalker commented
Update to newest 1.5.0

2021-06-25 08:27 UTC, JonLiu1993 requested changes

2021-06-25 08:27 UTC, JonLiu1993 commented on versions/g-/glslang.json
> +      "port-version": 0
We should delete this

2021-06-25 08:27 UTC, JonLiu1993 commented on ports/glslang/vcpkg.json
> +  "version-string": "11.5.0",
We should use "version" instaead of "version-string"

2021-07-01 14:19 UTC, ras0219-msft approved these changes
We can't simply delete the entire history of a package; that would break all current users.

Instead, I looked into updating shaderc to fix the conflicts. While updating it, I noticed that our patches are actually modifying upstream's install to add a `glslang::` namespace. This violates our policy of adhering to upstream as much as possible.

While unravelling that difference, I also found a much simpler way to fix the `find_package(glslang)` without needing to maintain dozens of lines of patchfiles moving forward. I've pushed this improvement to your branch.

Assuming CI passes, LGTM. Thanks for the PR and sorry for the very long wait on this!

2021-07-15 14:00 UTC, merged