[vcpkg edit] Simplify execution of VS Code
microsoft/vcpkg pull request #15778
Opened 2021-01-20 18:03 UTC by strega-nil

**Describe the pull request**

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2021-01-20 18:04 UTC, ras0219 approved these changes

2021-01-20 18:04 UTC, ras0219 commented on toolsrc/src/vcpkg/commands.edit.cpp
>              // note that we are invoking cmd silently but Code.exe is relaunched from there
This comment seems outdated :)

2021-01-20 18:08 UTC, BillyONeal commented
This relaunching with cmd was to protect VS Code from `cmd_execute_background`s `CREATE_NO_WINDOW` I thought?

2021-01-21 00:08 UTC, strega-nil commented
@BillyONeal Not really. If you want more information you can ask on Teams.

2021-01-21 05:36 UTC, BillyONeal commented
>> This relaunching with cmd was to protect VS Code from `cmd_execute_background`s `CREATE_NO_WINDOW` I thought?
> @BillyONeal Not really. If you want more information you can ask on Teams.

I just tested this and I'm seeing no window. And a ton of spew in the console.

![image](https://user-images.githubusercontent.com/1544943/105284547-8cfbbf80-5b67-11eb-898d-45ece102b35b.png)

2021-01-21 05:36 UTC, BillyONeal requested changes
This breaks launching code in my testing.

2021-01-21 05:42 UTC, BillyONeal commented
Note that to demonstrate the problem you need to not have an already running copy of VS Code somewhere.

2021-01-21 17:54 UTC, strega-nil commented
@BillyONeal ah, that's why we were having issues.

2021-02-02 23:03 UTC, ras0219-msft commented
@strega-nil Ping on this

2021-02-03 01:53 UTC, strega-nil commented
Closing since clearly this breaks something.

2021-02-03 01:53 UTC, closed without merging