Fix #15395: libarchive build fails for x86_windows_v120
microsoft/vcpkg pull request #15799
Opened 2021-01-21 17:43 UTC by Olernov

Build fails on compiling xxhash.c having a fuction with "inline" specifier.
"inline" is a c99 keyword and c99 is not yet (fully) supported with MSVC toolset v120:
"The inline keyword is available only in C++. The __inline and __forceinline
keywords are available in both C and C++. For compatibility with previous versions,
_inline is a synonym for __inline."
(Source: http://msdn.microsoft.com/en-us/library/z8y1yy88.aspx)

This fix adds a patch that replaces "inline" with "__inline" in xxhash.c

**Describe the pull request**

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2021-01-22 06:14 UTC, JackBoosY commented
Hi @Olernov, thanks for this PR!
Can you report this issue to the upstream and wait for official approval?

Thanks.

2021-01-22 11:22 UTC, Olernov commented
Ok, submitted:
https://github.com/libarchive/libarchive/issues/1486
https://github.com/libarchive/libarchive/pull/1487

2021-01-25 02:43 UTC, JackBoosY commented
Waiting for official reply.

2021-02-17 08:22 UTC, Olernov commented
Libarchive has accepted the pull request https://github.com/libarchive/libarchive/pull/1487. Probably the fix will be included into the next release.

2021-02-18 07:38 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

2021-02-19 09:06 UTC, Olernov commented
I think we should better wait for the next release of libarchive and then bump the port version, what do you think?

2021-02-19 09:15 UTC, JackBoosY commented
@Olernov  Fine.

2021-09-10 06:57 UTC, JackBoosY commented
So, the upstream merged your changes, can you please merge your branch to master and run `x-add-version`?

2021-09-13 11:54 UTC, Olernov commented
Opened a new PR for this: https://github.com/microsoft/vcpkg/pull/20133

2021-09-13 11:54 UTC, closed without merging