[vcpkg_configure_cmake] Introduce REQUIRE_ALL_PACKAGES
microsoft/vcpkg pull request #15808
Opened 2021-01-22 01:58 UTC by ras0219

A recurring problem with many builds are uses of autodetected dependencies; depending on the specific install order, different CI runs results in different results for detection which results in flaky, unrobust behavior.

This PR introduces new flags to `vcpkg_configure_cmake()` to control this: `REQUIRE_ALL_PACKAGES`, `DISABLE_PACKAGES`, and `OPTIONAL_PACKAGES`.

2021-01-22 06:26 UTC, cenit commented
Very nice and very useful. Might help also reducing patchsets in some ports (and improve their maintainability too)

2021-01-22 06:28 UTC, cenit commented
Is it necessary to remove the QUEIT keyword from ${ARGS}? Or putting REQUIRED at the end always wins?

2021-01-22 07:56 UTC, Neumann-A commented on scripts/buildsystems/vcpkg.cmake
>      elseif("${name}" STREQUAL "ICU" AND EXISTS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/unicode/utf.h")
everything below should probably be installed within a port via a vcpkg-cmake-wrapper.cmake instead of being in the toolchain.

2021-01-22 08:56 UTC, cenit commented on scripts/buildsystems/vcpkg.cmake
>      elseif("${name}" STREQUAL "ICU" AND EXISTS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/unicode/utf.h")
i agree. They belong to a time in which vcpkg-cmake-wrapper.cmake was not existing...

2021-01-22 19:05 UTC, ras0219 commented on scripts/buildsystems/vcpkg.cmake
>      elseif("${name}" STREQUAL "ICU" AND EXISTS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/unicode/utf.h")
Yep, but I didn't want to make that change in this PR.

2021-01-22 19:13 UTC, cenit commented
Just few years ago @Neumann-A (or me) would have triggered a full rebuild just after this PR was merged, enabling the REQUIRE_ALL_PACKAGES by default. And I would have really enjoyed the result of that hard work!
It would be a very reasonable default, to have more reproducible builds. But I understand that it would be very very difficult, with many broken ports at first. The outcome would be a better vcpkg too

2021-01-22 19:15 UTC, ras0219 commented
We unfortunately can no longer do such "break the world" operations with the new versioning and registries features -- we've lost "total" atomicity in exchange for stability.

However, we do intend to make this a requirement for all new ports and to eventually apply this policy to every current port.

2021-02-13 07:42 UTC, ras0219-msft commented
/azp run

2021-02-14 23:29 UTC, Neumann-A commented on ports/gdal/vcpkg-cmake-wrapper.cmake
> +_find_package(${ARGS} CONFIG)
This is indirectly providing a `FindGDAL.cmake` via a vcpkg created `-config.cmake`. Maybe finally decide to support a CMake module directory?

2021-02-14 23:31 UTC, Neumann-A commented on ports/gdal/portfile.cmake
> +            "LIBS=${release_libs} -lm -lpthread -l${cppstdlib}"
Does this generate a correct `*.pc` file with the dependencies in `requries` or will it just add all libraries to the link flags?

2021-02-15 00:04 UTC, ras0219 commented on ports/gdal/portfile.cmake
> +            "LIBS=${release_libs} -lm -lpthread -l${cppstdlib}"
This is just modifying the LIBS variable to get things linking.

2021-02-15 00:19 UTC, Neumann-A commented on ports/gdal/portfile.cmake
> +            "LIBS=${release_libs} -lm -lpthread -l${cppstdlib}"
Yeah I know. But sometimes those get added to the generated pc file in `Libs:`.

2021-02-16 00:54 UTC, ras0219 commented on ports/gdal/vcpkg-cmake-wrapper.cmake
> +_find_package(${ARGS} CONFIG)
The reason why we don't use the module directory approach is twofold:

1. _Many_ projects do something like:
```
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
```
which would break the "obvious" way to provide a module path.
2. Because vcpkg packages are the "producers", they should provide `-config.cmake` files, which are essentially strictly superior to Find modules (notably they support `find_dependency()`).

I took this approach for GDAL to replace the official target with a config file, since I felt that we could provide the full official interface easily enough.

2021-02-16 07:28 UTC, Neumann-A commented on ports/gdal/vcpkg-cmake-wrapper.cmake
> +_find_package(${ARGS} CONFIG)
Concerning 1:
The reason projects does this is because the cmake docs tell them to set it. In my opinion, this is a case of outdated/Wrong docs since `CMAKE_MODULE_PATH` can be provided either by a toolchain or by a superproject/superbuild so only setting the value is conceptually wrong and needs correction. (i.e. `list(PREPEND)` or similar is the correct way to go. See e.g. VTK). Modifying&backuping the `CMAKE_MODULE_PATH` is for example also done by `VTK-Config.cmake`

Concerning 2:
If the information is provided by vcpkg it does not matter here if it is `<package>-config.cmake` or `Find<package>.cmake` because you can encode the same information in both. The config way would only be superior if you also supply a `<configfile>Version.cmake`. Although the `find_dependency` part is correct you just can wrap it into a minimal function in a `Find<package>.cmake`  to workaround that. 

My main nitpick here ist that with a `CMAKE_MODULE_PATH` you wouldn't need to use the indirection with the `vcpkg-cmake-wrapper.cmake` here. Furthermore redirection of **all** calls to `FindGDAL.cmake` is possibly breaking downstream users with a custom `FindGDAL.cmake` which does not define the same targets and/or variables as the vcpkg one without a way to bail out. So chose your poison very carefully.

2021-02-16 22:05 UTC, ras0219-msft commented on ports/gdal/vcpkg-cmake-wrapper.cmake
> +_find_package(${ARGS} CONFIG)
Agreed that the current practice of many projects is "wrong"/"bad", but patching the world is never a good solution.

It is true that we are possibly overriding a package's custom FindGDAL.cmake, however these custom find scripts are (in general) fundamentally broken in the face of static libraries, because there's no way for them to know the precise dependencies that were consumed. Additionally, as long as we adhere to "only use vcpkg-cmake-wrapper to wrap built-in CMake modules", the probability of custom FindXYZ.cmake scripts is much lower (but non-zero -- we've both seen it happen).

2021-02-16 23:22 UTC, Neumann-A commented on ports/gdal/vcpkg-cmake-wrapper.cmake
> +_find_package(${ARGS} CONFIG)
> because there's no way for them to know the precise dependencies that were used during the build

Unless they are using the `FindPkgConfig` module + `pkg_check_modules` in the `Find<Package>.cmake`.  If they also use the `IMPORTED_TARGET` option and link against the created target it should be always correct (unless there is something wrong with the pc files generated by vcpkg). Unfortunately, I have also seen that the results of `pkg_check_modules` is sometimes only used as hinting for `find_library` calls etc.  (Source: Qt6)

Since I saw a mention of changes to FindGDAL in the CMake 3.20 release notes you might want to have look at in the CMake RC to make sure everything is ok with the config here.

2021-02-18 06:55 UTC, JackBoosY requested changes

2021-02-18 06:55 UTC, JackBoosY commented on ports/gdal/portfile.cmake
> +    set(ENV{PKG_CONFIG_PATH} "${backup_PKG_CONFIG_PATH}")
Should be separarte this to a new vcpkg function?

2021-02-18 18:46 UTC, ras0219 commented on ports/gdal/portfile.cmake
> +    set(ENV{PKG_CONFIG_PATH} "${backup_PKG_CONFIG_PATH}")
That may be reasonable, but I want to scope this PR to just the primary feature (`REQUIRE_ALL_PACKAGES`). We can consider extracting this procedure out in the future.

2021-02-19 21:55 UTC, ras0219-msft commented
/azp run

2021-03-15 21:10 UTC, wrobelda commented
Don't want to sound need or anything, but it is a blocker for a number of PRs right now, which is a bummer. Has this stalled?

2021-06-16 20:48 UTC, ras0219-msft commented
Note https://github.com/microsoft/vcpkg/pull/18393 and https://github.com/microsoft/vcpkg/pull/18473 for examples of transitive dependency issues.

2021-06-19 05:06 UTC, dg0yt commented
> Note #18393 and #18473 for examples of transitive dependency issues.

Or now simage on Windows: https://github.com/microsoft/vcpkg/pull/17519, https://github.com/microsoft/vcpkg/pull/17519

2021-09-10 06:58 UTC, JackBoosY commented
This PR has been inactive for a long time, please reopen it if there is any progress.

2021-09-10 06:58 UTC, closed without merging

2021-09-10 09:33 UTC, cenit commented
😞 😢 😭

2021-09-10 09:48 UTC, JackBoosY commented
@cenit Don't worry, I believe this PR will continue.