[libkeyfinder] add new port with libkeyfinder 2.2.4
microsoft/vcpkg pull request #15878
Opened 2021-01-25 23:29 UTC by Be-ing

**Describe the pull request**

- Which triplets are supported/not supported? Have you updated the CI baseline?
Windows, macOS, and Linux have been tested. Not sure about UWP, but it's a simple C++ library that only depends on FFTW.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
AFAIK yes

2021-01-26 00:03 UTC, Be-ing commented on ports/libkeyfinder/vcpkg.json
> +    "catch2",
This dependency could be removed if BUILD_TESTING=OFF is passed to cmake. Is there a policy on this?

2021-01-26 00:06 UTC, Be-ing commented on ports/libkeyfinder/vcpkg.json
> +    "catch2",
oh yeah, I'll change this https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-build-testsdocsexamples-by-default

2021-01-26 06:07 UTC, NancyLi1013 requested changes

2021-01-26 06:07 UTC, NancyLi1013 commented on ports/libkeyfinder/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/libkeyfinder RENAME copyright)
```suggestion
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

2021-01-26 06:08 UTC, NancyLi1013 commented
Hi @Be-ing 

Thanks for your PR.

Have you tested the feature?

2021-01-26 06:34 UTC, Be-ing commented
Yes I have tested it here: https://github.com/mixxxdj/mixxx/pull/3594

2021-01-26 08:10 UTC, NancyLi1013 approved these changes

2021-01-26 10:00 UTC, Be-ing commented
![mixxx-windows](https://user-images.githubusercontent.com/9455094/105829733-5cae8980-5f8a-11eb-8aee-a0f7652db10c.png)
Thanks to vcpkg we've been able to add several libraries to our Windows builds (libkeyfinder, lilv, libmodplug) that were too much of hassle to add with our old system of custom batch scripts. :grinning: Just in time for [PawPaw](https://kx.studio/News/?action=view&url=announcing-pawpaw-cross-platform-lv2-ports-for-macos-and-windows) to make LV2 audio plugins available on Windows!

2021-01-27 16:02 UTC, Be-ing commented
What is left before this can be merged?

2021-01-28 03:06 UTC, NancyLi1013 commented
For me, nothing needs to be done here.

2021-01-29 03:21 UTC, merged

2021-02-24 18:59 UTC, Be-ing commented
> Thanks to vcpkg we've been able to add several libraries to our Windows builds (libkeyfinder, lilv, libmodplug) that were too much of hassle to add with our old system of custom batch scripts. grinning Just in time for PawPaw to make LV2 audio plugins available on Windows!

I wrote a [blog post](https://mixxx.org/news/2021-02-23-build-infrastructure-updates/) detailing this if you're curious.