[matio] Update to v1.5.19
microsoft/vcpkg pull request #15971
Opened 2021-02-01 08:25 UTC by traversaro

- What does your PR fix? This PR updates matio to v1.5.19

- Which triplets are supported/not supported? Have you updated the CI baseline? The change should not affect the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2021-02-01 08:55 UTC, JackBoosY requested changes

2021-02-01 08:55 UTC, JackBoosY commented on ports/matio/portfile.cmake
>      SHA512 bbb1c5f1f2609d329b69963f16ff8b60052922f83513d20f3ef687c04c4278536b88116c4727855de06f12ddf34103fe4be250012ae24706868490583ee90fde
```suggestion
    SHA512 67c239d8aabafaa935775f3b260ba0756c196b0d845ef5116365c9aa6a0b24dae70d92c4e74d5d43ae073ae0744f084f0f58ead864eb77c813d43dbbb3e4ec5e
```

2021-02-01 09:08 UTC, traversaro commented on ports/matio/portfile.cmake
>      SHA512 bbb1c5f1f2609d329b69963f16ff8b60052922f83513d20f3ef687c04c4278536b88116c4727855de06f12ddf34103fe4be250012ae24706868490583ee90fde
Sorry for the noise, I was still in the process of updating the PR.

2021-02-04 07:03 UTC, JackBoosY commented
/azp run

2021-02-04 07:42 UTC, JackBoosY approved these changes

2021-02-09 01:56 UTC, merged

2021-02-09 01:56 UTC, ras0219-msft commented
Thanks for the update!