[aubio] allow to build without dependencies
microsoft/vcpkg pull request #16051
Opened 2021-02-05 00:02 UTC by autoantwort

Fixes #15966

Can now be used on mac and linux

2021-02-05 06:00 UTC, NancyLi1013 commented on ports/aubio/vcpkg.json
> +  ],
Since you set it as default features, it should be built on all platforms.

2021-02-05 06:10 UTC, NancyLi1013 requested changes
Also needs to use `vcpkg_check_features() `to handle the feature `tools `in port.cmake.

2021-02-05 06:10 UTC, NancyLi1013 commented on ports/aubio/CMakeLists.txt
> +if(tools IN_LIST FEATURES)
```suggestion
if(BUILD_TOOLS)
```
I think there should be `BUILD_TOOLS`.

2021-02-05 06:10 UTC, NancyLi1013 commented on ports/aubio/CMakeLists.txt
> -option(BUILD_TOOLS "Build and install tools" ON)
This option should not be removed.

2021-02-05 06:10 UTC, NancyLi1013 commented on ports/aubio/CMakeLists.txt
> +if(tools IN_LIST FEATURES)
```suggestion
if(BUILD_TOOLS)
```

2021-02-05 06:10 UTC, NancyLi1013 commented on ports/aubio/CMakeLists.txt
> +if(tools IN_LIST FEATURES)
```suggestion
if(BUILD_TOOLS)
```

2021-02-05 06:10 UTC, NancyLi1013 commented on ports/aubio/CMakeLists.txt
> +if(tools IN_LIST FEATURES)
```suggestion
if(BUILD_TOOLS)
```

2021-02-05 06:10 UTC, NancyLi1013 commented on ports/aubio/CMakeLists.txt
> +if(VCPKG_TARGET_IS_WINDOWS)
```suggestion
if(WIN32)
```

2021-02-05 17:50 UTC, autoantwort commented on ports/aubio/vcpkg.json
> +  ],
It builds on my macOS 11 with Apple M1 and the pipeline suggests that is also builds on linux.

2021-02-07 03:15 UTC, NancyLi1013 requested changes

2021-02-07 03:15 UTC, NancyLi1013 commented on ports/aubio/portfile.cmake
>    OPTIONS_RELEASE
```suggestion
  OPTIONS ${FEATURE_OPTIONS}
  OPTIONS_RELEASE
```

2021-02-07 03:15 UTC, NancyLi1013 commented on ports/aubio/vcpkg.json
> +  ],
The pipeline didn't test the feature `tools `before. Since you didn't handle it correctly. Let's see the new test result.

2021-02-07 03:41 UTC, autoantwort commented on ports/aubio/vcpkg.json
> +  ],
Ohh ok 😅

2021-02-07 04:33 UTC, autoantwort commented on ports/aubio/vcpkg.json
> +  ],
Now it only fails on linux, is there a way to get the error log from the pipeline? :)

2021-02-07 05:42 UTC, NancyLi1013 commented
The failures on x64-linux:

```
CMake Error at /mnt/vcpkg-ci/installed/x64-linux/share/ffmpeg/vcpkg-cmake-wrapper.cmake:4 (_find_package):
  By not providing "FindFFmpeg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FFmpeg", but
  CMake did not find one.

  Could not find a package configuration file provided by "FFmpeg" with any
  of the following names:

    FFmpegConfig.cmake
    ffmpeg-config.cmake

  Add the installation prefix of "FFmpeg" to CMAKE_PREFIX_PATH or set
  "FFmpeg_DIR" to a directory containing one of the above files.  If "FFmpeg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:604 (include)
  CMakeLists.txt:36 (find_package)
```
You can get the log [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=49055&view=artifacts&pathAsName=false&type=publishedArtifacts).

2021-02-11 18:39 UTC, autoantwort commented
> You can get the log [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=49055&view=artifacts&pathAsName=false&type=publishedArtifacts).

Thanks! Works now everywhere.

2021-02-14 17:32 UTC, autoantwort commented
Now also on mingw. I don't now why it shows that there are *Changes requested*, there are no.

2021-02-19 07:03 UTC, JackBoosY requested changes

2021-02-19 07:03 UTC, JackBoosY commented on ports/aubio/CMakeLists.txt
> +    -DHAVE_ERRNO_H=1
Only for UNIX?

2021-02-19 07:05 UTC, JackBoosY approved these changes

2021-02-19 07:05 UTC, JackBoosY commented
Needs to test build core only.

2021-02-19 07:42 UTC, NancyLi1013 commented
`aubio[core]` has been passed with the following triplets:

- x86-windows
- x64-windows-static
- x64-osx

2021-02-19 07:42 UTC, NancyLi1013 approved these changes

2021-02-19 14:53 UTC, autoantwort commented
I have tested `aubio[core]` on `x64-linux` also. Is there anything that prevents merging?

2021-02-20 02:49 UTC, JackBoosY commented
@autoantwort Nope, waiting for merge.

2021-03-15 17:53 UTC, autoantwort commented
> @autoantwort Nope, waiting for merge.

@ras0219-msft

2021-03-16 01:25 UTC, NancyLi1013 commented
@ras0219-msft Could you please help review and merge this PR?

2021-03-23 00:23 UTC, vicroms commented on ports/aubio/CMakeLists.txt
> +endif()
Why `vcpkg_check_features()` add these definitions instead of patching? 

```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    tools HAVE_SNDFILE
    tools HAVE_WAVWRITE
    tools HAVE_WAVREAD
    tools LIBAV
    tools SWRESAMPLE
)
```

2021-03-23 09:26 UTC, autoantwort commented on ports/aubio/CMakeLists.txt
> +endif()
I didn't know that is is possible. Now I have removed the commented section and added 
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    tools WITH_DEPENDENCIES
    tools HAVE_SNDFILE
    tools HAVE_WAVWRITE
    tools HAVE_WAVREAD
    tools LIBAV
    tools SWRESAMPLE
)
```

2021-03-23 10:40 UTC, JackBoosY requested changes

2021-03-23 10:40 UTC, JackBoosY commented on ports/aubio/portfile.cmake
> +vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
```suggestion
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
```

2021-03-24 01:54 UTC, JackBoosY requested changes

2021-03-24 01:54 UTC, JackBoosY commented on ports/aubio/portfile.cmake
> +    tools LIBAV
```suggestion
    tools HAVE_LIBAV
```

2021-03-25 00:49 UTC, JackBoosY approved these changes

2021-03-25 19:36 UTC, merged