[libarchive] Fix static linking dependencies
microsoft/vcpkg pull request #16082
Opened 2021-02-07 02:50 UTC by DDoSolitary

Fix configuration of libarchive's dependencies zstd and zlib, which would otherwise cause undefined symbols error when linking statically.

2021-02-07 06:36 UTC, NancyLi1013 requested changes
Please also bump `Port-Version` in CONTROL file.

Also use the command `vcpkg x-add-version libarchive` to update the files in `versions `folder.
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-files-in-versions-of-any-modified-ports

2021-02-07 06:36 UTC, NancyLi1013 commented on ports/libarchive/portfile.cmake
> +set(ENABLE_ZLIB ON)
`ENABLE_ZLIB` has been set as ON by default. Why do you still set it again?
https://github.com/libarchive/libarchive/blob/v3.4.3/CMakeLists.txt#L205

2021-02-07 07:26 UTC, DDoSolitary commented on ports/libarchive/portfile.cmake
> +set(ENABLE_ZLIB ON)
Yes it has been set for building libarchive itself. However, it is also used in `vcpkg-cmake-wrapper.cmake.in`, so we need to set it for the current file so that the [`configure_file` call below](https://github.com/microsoft/vcpkg/blob/9199e697a1c775bba06474e95b42347d54f3d62d/ports/libarchive/portfile.cmake#L72) works properly.

2021-02-07 07:43 UTC, DDoSolitary commented
Versions bumped as requested.

2021-02-07 07:51 UTC, NancyLi1013 commented on ports/libarchive/portfile.cmake
> +set(ENABLE_ZLIB ON)
Since `zlib` is the required dependency, I think we should always require `find_dependency(ZLIB)` in vcpkg-cmake-wrapper.cmake.in.

It might be needed to update these codes
```
if(@ENABLE_ZLIB@)
    find_dependency(ZLIB)
endif()
```
as

` find_dependency(ZLIB)`.

But I also wonder why the option `ENABLE_ZLIB` is not set as ON in this file.

Perhaps it is related with `cmake_policy(SET CMP0012 NEW)`?
https://cmake.org/cmake/help/latest/policy/CMP0012.html

2021-02-07 08:16 UTC, DDoSolitary commented on ports/libarchive/portfile.cmake
> +set(ENABLE_ZLIB ON)
> Since zlib is the required dependency, I think we should always require find_dependency(ZLIB) in vcpkg-cmake-wrapper.cmake.in.

I'm not sure but probably because it's configurable for libarchive itself. The "required" property seems to be enforced by the port's author.

> But I also wonder why the option ENABLE_ZLIB is not set as ON in this file.

The `configure_file` function is called in `portfile,cmake` so neither `${FEATURE_OPTIONS}` nor libarchive's CMakeLists.txt will take effect. Other options work because although undocumented, `vcpkg_check_features` also [sets the options for its parent scope](https://github.com/microsoft/vcpkg/blob/5eea585548058540c3b73d087eb101c033b5fa85/scripts/cmake/vcpkg_check_features.cmake#L175), but it is not the case for `ENABLE_ZLIB`, which is manually appended to `FEATURE_OPTIONS`.

2021-02-07 13:32 UTC, DDoSolitary commented
I have to idea why the x64_linux CI tests failed.

2021-02-08 08:31 UTC, JackBoosY commented
```
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
```

2021-02-08 08:31 UTC, NancyLi1013 commented
/azp run

2021-02-08 08:33 UTC, NancyLi1013 commented
@DDoSolitary 

The failures on x64-linux are not related with this PR. I have rerun to rebuild.

2021-02-08 08:34 UTC, NancyLi1013 approved these changes

2021-02-18 06:07 UTC, JackBoosY commented
/azp run

2021-02-18 12:49 UTC, DDoSolitary commented
I'm unable to reproduce the x64-linux error locally. Running `./vcpkg install --overlay-ports=scripts/test_ports cmake:x64-linux` on my Arch Linux installation on WSL works without issues.

The errors in windows triplets seems irrelevant. They failed due to some network errors.

2021-02-18 15:10 UTC, ras0219-msft commented
/azp run

2021-02-18 15:45 UTC, DDoSolitary commented
@JackBoosY

> c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory

It's quite surprising that it's trying to link against glib. The cmake port doesn't depend on the glib port at all (not even intermediately, glib is not installed when I built cmake in a clean vcpkg installation).

2021-02-19 03:00 UTC, JackBoosY commented
cc @ras0219 @ras0219-msft
Can you please take a look?

Thanks.

2021-02-19 04:56 UTC, DDoSolitary commented
Strangely, after removing libglib-2.0.so from /usr/lib, build fails with another error

```
CMake Error at /root/vcpkg/installed/x64-linux/share/cmake/Qt5Core/Qt5CoreConfig.cmake:95 (message):                              
  Library not found: glib-2.0
```

So I still have no idea why it's unable to find the glib library in the CI build.

2021-02-23 07:02 UTC, NancyLi1013 commented
Depends on PR #15808.

2021-04-07 09:58 UTC, NancyLi1013 commented
@DDoSolitary 

Could you please resolve the conflicts?

2021-04-07 10:50 UTC, DDoSolitary commented
@NancyLi1013 Rebased.

2021-04-09 07:02 UTC, NancyLi1013 approved these changes

2021-04-09 07:03 UTC, NancyLi1013 commented
LGTM now, thanks for your patience @DDoSolitary.

2021-04-09 07:03 UTC, NancyLi1013 commented
LGTM now, thanks for your patience @DDoSolitary.

2021-04-09 13:37 UTC, ytbigvinny27 approved these changes

2021-04-20 00:14 UTC, merged