Update portaudio port to latest on github
microsoft/vcpkg pull request #16197
Opened 2021-02-13 00:53 UTC by fluffy

**Describe the pull request**

Update portaudio port to latest on github

- What does your PR fix? Fixes #16196

- Which triplets are supported/not supported? Have you updated the CI baseline?

uwp is not supported 

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

yes (I hope so)

2021-02-13 22:48 UTC, viromer requested changes

2021-02-13 22:48 UTC, viromer commented on ports/portaudio/vcpkg.json
> +  "port-version": 3,
```suggestion
  "port-version": 0,
```

Port version should reset to 0 when the main version changes.

2021-02-14 01:49 UTC, vicroms requested changes

2021-02-14 01:49 UTC, vicroms commented on ports/portaudio/vcpkg.json
> +  "version-string": "2020-02-20",
```suggestion
  "version-date": "2020-02-20",
```
It's better to use the appropriate [version scheme](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.reference.md#version-schemes).

2021-02-14 17:35 UTC, fluffy commented on ports/portaudio/vcpkg.json
> +  "version-string": "2020-02-20",
Thanks - this is my first time updating a port and appreciate the guidance.

2021-02-14 17:55 UTC, fluffy commented on ports/portaudio/vcpkg.json
> +  "port-version": 3,
After I moved this to zero, I needed to remove the line all together to make it pass the "./vcpkg format-manifest --all"

2021-02-14 23:29 UTC, merged

2021-02-14 23:29 UTC, vicroms commented
Thanks for the PR!

2021-02-15 02:47 UTC, fluffy commented
Thank you and thanks for the work on vcpkg