[ryu] activated libraries generic_128 and ryu_printf
microsoft/vcpkg pull request #16238
Opened 2021-02-15 19:12 UTC by georg-emg

This patch updates the port files to build and install the libraries `generic_128` and `ryu_printf`. Previously, only the base `ryu` library was built. The new libraries are completely independent builds, so that the existing library is not affected in any way.

2021-02-16 19:14 UTC, ras0219-msft requested changes
Thanks for the PR!

LGTM after the version change.

2021-02-16 19:14 UTC, ras0219-msft commented on ports/ryu/CONTROL
> +Port-Version: 1
```suggestion
Version: 2.0
Port-Version: 3
```

2021-02-16 19:14 UTC, ras0219-msft commented on versions/r-/ryu.json
> +    },
When changing the port-version to 3, this entry needs to be removed.

2021-02-17 08:41 UTC, georg-emg commented on versions/r-/ryu.json
> +    },
Just trying to understand your request.

If I understand correctly, your concern is that the version number in the CONTROL file (2.0-2) is incorrect and does not correspond to the git tag listed in the portfile (v2.0). You suspect, and I agree with you, that whoever updated the CONTROL file before me mistakenly added "-1" and "-2" to the version, instead of adding a Port-Version entry. So in reality, my change would be port version 3 of ryu version 2.0, and not port version 1 of ryu version 2.0-2.

So basically, I see three ways to fix this:

1. use `Port-Version: 3` and `Version: 2.0`, as you suggested,
2. use `Port-Version: 1` and `Version: 2.0`, because that would be the next port version in line for v2.0, or
3. use `Port-Version: 3` and `Version: 2.0`, but also correct the whole version file, replacing `Version: 2.0-1` with `Port-Version: 1`/`Version: 2.0`, and replacing `Version: 2.0-2` with `Port-Version: 2`/`Version: 2.0` for the earlier commits.

I'll go with whatever you think is best, I just wanted to make sure.

Also, while I'm at it, should I replace the CONTROL file with a proper manifest file?

2021-02-18 08:49 UTC, JackBoosY commented on versions/r-/ryu.json
> +    },
Since you doesn't update ryu version, we should keep `Version` as `2.0`, and update the `Port-Version`.
And since the `Port-Version` is incorrect in the previous PR, it should be `3`.
So please use the first way.

We prefer to use manifest file.

2021-02-18 15:12 UTC, georg-emg commented on versions/r-/ryu.json
> +    },
Ok, I replaced the CONTROL file with a manifest with port-version 3 and version 2.0, as you requested.

2021-02-18 20:58 UTC, merged

2021-02-18 20:58 UTC, ras0219-msft commented
Looks great, thanks for the PR!