qt5-base: misleading list of system packages reqd
microsoft/vcpkg pull request #16280
Opened 2021-02-18 15:53 UTC by wrobelda

qt5-base requires many more packages present than just a mere libxkbcommon-x11-dev currently suggested. Let's instead point users to thezure provision script, which a complete and an up-to-date list of them.

Alternatively, a complete list of those packages could be added to the port file itself, but I find this approach cleaner. 

This also signals that some more robust way of declaring a list of system-level dependencies for each port would be nice. 

**Describe the pull request**

- What does your PR fix? 

A misleadingly short list of system-level dependencies required.

2021-02-19 06:32 UTC, JackBoosY requested changes

2021-02-19 06:32 UTC, JackBoosY commented on ports/qt5-base/portfile.cmake
> +  https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh
I think we need to link to the official documentation instead of this.
@Neumann-A what do you think about?

2021-02-19 06:57 UTC, Neumann-A commented on ports/qt5-base/portfile.cmake
> +  https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh
As I already told you in another PR: I think we could do both. qt in vcpkg is built with a lot of features enabled by default which is why it requires so many deps.

2021-02-19 07:19 UTC, JackBoosY requested changes

2021-02-19 07:19 UTC, JackBoosY commented on ports/qt5-base/portfile.cmake
> +  https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh
```suggestion
  https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh#L18-L19
```

2021-02-20 20:34 UTC, wrobelda commented on ports/qt5-base/portfile.cmake
> +  https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh
I don't think this is a sensible improvement: it's only a matter of time until some more lines are added/removed from the script and that anchoring URL becomes misleading. There are clear comments in each section and can't imagine it would be a problem for any dev to understand which of those lists are for qt5.

2021-03-02 06:41 UTC, JackBoosY approved these changes

2021-04-20 00:11 UTC, strega-nil commented
@wrobelda or @JackBoosY, could you merge with master?

2021-04-20 01:38 UTC, JackBoosY approved these changes

2021-04-21 03:53 UTC, JackBoosY commented on versions/q-/qt5-base.json
> +      "git-tree": "e81e2a72343cf756e3baa492422056e2e8e6101b",
```suggestion
      "git-tree": "0a2e6f5403e24e41109d28db0c2330f8254774f2",
```

2021-04-29 00:53 UTC, merged

2021-04-29 00:53 UTC, BillyONeal commented
Thanks for your contribution!