[docs/users/manifests.md] add a link to the specification
microsoft/vcpkg pull request #16336
Opened 2021-02-21 01:27 UTC by coryan

Add a link to the specification

- What does your PR fix? Fixes #

A link to the specification would have saved me a few minutes trying to figure out what identifiers were reserved.

- Which triplets are supported/not supported? Have you updated the CI baseline?

N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

N/A

2021-02-22 07:51 UTC, NancyLi1013 requested changes

2021-02-22 07:51 UTC, NancyLi1013 commented on docs/users/manifests.md
> +See [the specification](/docs/specifications/manifests.md) for all the details about what can go into a manifest,
```suggestion
See [the specification](../specifications/manifests.md) for all the details about what can go into a manifest,
```

2021-02-22 11:41 UTC, coryan commented
PTAL

2021-02-23 01:44 UTC, NancyLi1013 approved these changes

2021-02-24 21:55 UTC, merged

2021-02-24 21:55 UTC, ras0219-msft commented
Thanks!