[podofo] update to 0.9.7
microsoft/vcpkg pull request #16373
Opened 2021-02-23 10:06 UTC by JonLiu1993

Fix #16358 

Update podofo to the latest version 0.9.7

All feature are tested successfully in the following triplets:
- x86-windows
- x64-windows
- x64-windows-static

2021-02-24 07:51 UTC, JonLiu1993 commented on ports/podofo/fix-x64-osx.patch
> ++    struct tm _tm;
install-x64-osx reported a compilation error of "error: expected';' at end of declaration". This patch solves this problem

2021-02-24 08:33 UTC, NancyLi1013 approved these changes

2021-02-24 21:41 UTC, ras0219-msft requested changes

2021-02-24 21:41 UTC, ras0219-msft commented on ports/podofo/fix-x64-osx.patch
> ++    struct tm _tm;
This is a potential change in behavior, because `_tm` is no longer initialized to 0. 
```suggestion
+    struct tm _tm{0};
```

2021-02-26 05:55 UTC, JonLiu1993 commented on ports/podofo/fix-x64-osx.patch
> ++    struct tm _tm;
I changed struct tm _tm; to struct tm _tm{0}; but it seems that the previous problem appeared again: error: expected';' at end of declaration
     struct tm _tm{0};

2021-02-27 10:55 UTC, alwendya commented
Excuse my mistake if I'm wrong,  you add the label 'requires:author-response'. Do you request the post author or you're asking the Podofo author ?
As I'm running on windows, is it possible for me to already use vcpkg with the working windows builds?
Like I said in my first post, thanks to all the team with your great work. You help lot of dev with your vcpkg tool!

2021-03-01 02:59 UTC, JonLiu1993 commented
> Excuse my mistake if I'm wrong, you add the label 'requires:author-response'. Do you request the post author or you're asking the Podofo author ?
> As I'm running on windows, is it possible for me to already use vcpkg with the working windows builds?
> Like I said in my first post, thanks to all the team with your great work. You help lot of dev with your vcpkg tool!

The label'requires:author-response' means the author of the pr submission, this pr is a discussion about podofo, if you have a new issue, please submit a new issue, thank you

2021-03-25 18:33 UTC, alwendya approved these changes

2021-03-25 18:50 UTC, alwendya reviewed
Works for myself in Windows x64 vs2019 static

2021-03-26 19:06 UTC, ras0219-msft requested changes

2021-03-26 19:06 UTC, ras0219-msft commented on ports/podofo/freetype.patch
> -diff --git a/cmake/modules/FindFREETYPE.cmake b/cmake/modules/FindFREETYPE.cmake
Please revert the changes to this file.

2021-03-26 19:06 UTC, ras0219-msft commented on ports/podofo/0005-fix-crypto.patch
>  diff --git a/CMakeLists.txt b/CMakeLists.txt
Please revert the changes to this file.

2021-03-26 19:06 UTC, ras0219-msft commented on ports/podofo/0002-HAVE_UNISTD_H.patch
> -index fea9ada..a813c7b 100644
Please revert the changes to this file.

2021-03-30 09:58 UTC, NancyLi1013 approved these changes

2021-04-01 17:29 UTC, merged