[erfa] Essential Routines for Fundamental Astronomy (ERFA) new port.
microsoft/vcpkg pull request #16372
Opened 2021-02-23 09:54 UTC by mgrutten

**Describe the pull request**

A new port for the [Essential Routines for Fundamental Astronomy (ERFA)](https://github.com/liberfa/erfa).

- What does your PR fix? Fixes #

This PR adds a port for ERFA.  I am new to vcpkg and relatively new to CMake, but copied the structure from a similar package (farmhash)

- Which triplets are supported/not supported? Have you updated the CI baseline?

This package uses autoconf and libtool, so I suspect it is limited to linux-based triplets.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I believe so.

2021-05-12 06:00 UTC, NancyLi1013 requested changes

2021-05-12 06:00 UTC, NancyLi1013 commented on ports/erfa/vcpkg.json
> +  "description": "Essential Routines for Fundamental Astronomy."
```suggestion
  "description": "Essential Routines for Fundamental Astronomy.",
  "homepage": "https://github.com/liberfa/erfa"
```

2021-05-13 02:25 UTC, NancyLi1013 commented
The failures are like this:
`configure: error: cannot find math functions`

2021-05-13 07:39 UTC, mgrutten commented
> The failures are like this:
> `configure: error: cannot find math functions`

I'm out of my depth here.

It looks like MSVC is failing in a way that "configure" doesn't expect.  If I take out the test for the math library (modify configure.ac, run autoconf and then run vcpkg), then "configure" succeeds, but the build stage errors with
`libtool:   error: can't build i686-pc-mingw32 shared library unless -no-undefined is specified`

2021-05-13 07:51 UTC, dg0yt commented on ports/erfa/portfile.cmake
> +    AUTOCONFIG
Try to add
~~~
    OPTIONS
        "LIBS=-lm"
~~~

2021-05-13 10:53 UTC, mgrutten commented on ports/erfa/portfile.cmake
> +    AUTOCONFIG
Thanks for the suggestion @dg0yt, but MSVC doesn't like -lm.  I get
`LINK : fatal error LNK1104: cannot open file 'm.lib'`

The error Nancy identified (cannot find math functions) occurs during the configure step of the release version (not debug) and the full error looks like this:
```
configure:11910: checking for library containing sin
configure:11941: compile cl.exe -o conftest.exe -nologo -W3 -utf-8 -MP -MD -O2 -Oi -Gy -Z7 -DWIN32 -D_WINDOWS -DNDEBUG -LC:/Users/markg/Documents/dev/vcpkg/installed/x86-windows/lib -LC:/Users/markg/Documents/dev/vcpkg/installed/x86-windows/lib/manual-link conftest.c -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32 >&5
conftest.c
conftest.c(31): warning C4391: 'char sin()': incorrect return type for intrinsic function, expected 'double'
conftest.c(35): error C2168: 'sin': too few actual parameters for intrinsic function
configure:11941: $? = 2
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "erfa"
| #define PACKAGE_TARNAME "erfa"
| #define PACKAGE_VERSION "1.7.2"
| #define PACKAGE_STRING "erfa 1.7.2"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "erfa"
| #define VERSION "1.7.2"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define LT_OBJDIR ".libs/"
| #define PACKAGE_VERSION_MAJOR 1
| #define PACKAGE_VERSION_MINOR 7
| #define PACKAGE_VERSION_MICRO 2
| #define SOFA_VERSION "20210125"
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char sin ();
| int
| main ()
| {
| return sin ();
|   ;
|   return 0;
| }
```

2021-05-13 11:42 UTC, dg0yt commented on ports/erfa/portfile.cmake
> +    AUTOCONFIG
Actually this test is from the buildsystem looking for libm itself. It looks like upstream isn't yet supporting MSVC (CI is linux, macos), but a CMake build system is offered in https://github.com/liberfa/erfa/pull/75/files. Perhaps you can wait for the merge? (And maybe indicate your interest over there.)

2021-05-13 11:54 UTC, mgrutten commented on ports/erfa/portfile.cmake
> +    AUTOCONFIG
Yes! Well spotted @dg0yt! Waiting for upstream ERFA to support CMake is a really sensible thing to do.

@NancyLi1013: should we keep this request open, or close it and open a new one when upstream includes a CMake build system?

2021-05-14 02:20 UTC, NancyLi1013 commented on ports/erfa/portfile.cmake
> +    AUTOCONFIG
I suggest to close this PR now since CMake support will not be merged to upstream recently. Seems there is no any update  since Jan 15. You can reopen this PR or open a new one when CMake is supported by upstream.

2021-05-16 23:55 UTC, closed without merging