[woff2] fix for static linking and alternative compiler toolchains
microsoft/vcpkg pull request #16392
Opened 2021-02-24 17:59 UTC by jwtowner

This PR fixes static linking with the brotli port and fixes building woff2 with alternate compiler toolchains

Firstly, this change teaches the woff2 CMake configuration to understand the vcpkg's custom unofficial-brotli pkg-config configuration in order to support static linking. This fixes a build failure on x64-osx, x64-linux triplet or other triplets when VCPKG_LIBRARY_LINKAGE is set to static.

Secondly, the CANONICAL_PREFIXES option for the woff2 CMake configuration has been changed to be on by default, otherwise
custom triplets or toolchains using alternate compilers such as Clang/LLVM or other versions of GCC will fail. Leaving CANONICAL_PREFIXES set to OFF causes -no-canonical-prefixes to be passed to the compiler, which prevents symlinked compiler toolchains from working correctly. If a user does actually need non-canonical prefixes, chances are they will have a custom triplet or toolchain file that passes in -no-canonical-prefixes as a CFLAG for every port, and so setting it to ON here is a better default for vcpkg.

Triplets fixed by this PR:

arm-ios
arm-linux
arm64-ios
arm64-linux
arm64-mingw-static
arm64-osx
arm64-windows-static
ppc64le-linux
s390x-linux
wasm32-emscripten
x64-ios
x64-openbsd
x64-osx
x64-linux
x64-mingw-static
x64-windows-static
x86-mingw-static
x86-windows-static
x86-windows-static-md

2021-02-24 18:18 UTC, jwtowner commented
Sorry, I'm not sure what to do to get x86_windows Validate version files build step to pass in this case. Running the recommended command `vcpkg x-add-version --all` doesn't change any of the version files. Looking at `versions/w-/woff2.json`, I don't see anything off, but I must be missing something. Any ideas? Thanks!

2021-02-24 20:10 UTC, cenit commented
strange that you have fixed many triplets but no changes are required in ci.baseline.txt
is woff2 not tested in CI?

2021-02-24 20:32 UTC, jwtowner commented
> strange that you have fixed many triplets but no changes are required in ci.baseline.txt
> is woff2 not tested in CI?

Good question. Looking at ci.baseline.txt, I see:

```
woff2:x64-linux=fail
woff2:x64-osx=fail
woff2:x64-windows-static=fail
woff2:x64-windows-static-md=fail
```

Should I remove them from that file and submit it?

2021-02-25 05:41 UTC, cenit commented
the system should have already told you...
please check in ci logs that the checks are performed. i will also check it later

2021-02-25 06:28 UTC, jwtowner commented
@cenit @JonLiu1993 
> the system should have already told you...
> please check in ci logs that the checks are performed. i will also check it later

Done! Should just b e the stalled x64_osx CI build holding things up now.

2021-02-25 06:41 UTC, JackBoosY requested changes

2021-02-25 06:41 UTC, JackBoosY commented on ports/woff2/0001-unofficial-brotli.patch
> ++  set(WOFF2_BORTLIENC_LIBRARIES unofficial::brotli::brotlienc${BROTLI_LINKAGE} unofficial::brotli::brotlicommon${BROTLI_LINKAGE})
```suggestion
+  find_package(unofficial-brotli REQUIRED)
+  if (TARGET unofficial::brotli::brotlidec-static)
+      set(BROTLI_LINKAGE -static)
+  endif()
+  set(WOFF2_BROTLIDEC unofficial::brotli::brotlidec${BROTLI_LINKAGE})
+  set(WOFF2_BROTLIENC unofficial::brotli::brotlienc${BROTLI_LINKAGE})
+  set(WOFF2_BORTLIDEC_LIBRARIES unofficial::brotli::brotlidec${BROTLI_LINKAGE} unofficial::brotli::brotlicommon${BROTLI_LINKAGE})
+  set(WOFF2_BORTLIENC_LIBRARIES unofficial::brotli::brotlienc${BROTLI_LINKAGE} unofficial::brotli::brotlicommon${BROTLI_LINKAGE})
```

2021-02-25 06:42 UTC, JackBoosY commented on ports/woff2/0001-unofficial-brotli.patch
> ++  set(WOFF2_BORTLIENC_LIBRARIES unofficial::brotli::brotlienc${BROTLI_LINKAGE} unofficial::brotli::brotlicommon${BROTLI_LINKAGE})
We should always use `TARGET` to determine the target names instead of `VCPKG_LIBRARY_LINKAGE`, because some ports are always built as static/dynamic libraries.

2021-02-25 06:48 UTC, jwtowner commented on ports/woff2/0001-unofficial-brotli.patch
> ++  set(WOFF2_BORTLIENC_LIBRARIES unofficial::brotli::brotlienc${BROTLI_LINKAGE} unofficial::brotli::brotlicommon${BROTLI_LINKAGE})
Got it, thanks!

2021-02-25 07:21 UTC, JackBoosY commented
Please remake the patch file.

2021-02-25 07:39 UTC, JackBoosY commented
@jwtowner Seems you revert my suggestion?

2021-02-25 07:44 UTC, jwtowner commented
> @jwtowner Seems you revert my suggestion?

Sorry, botched patch regenertion somehow, trying again.

2021-02-25 08:49 UTC, JackBoosY approved these changes

2021-02-25 13:50 UTC, cenit commented
@BillyONeal is CI system not triggering "FIXED, REMOVE FROM FAILING" in the PR pipeline anymore?

2021-02-25 17:20 UTC, BillyONeal commented
> @BillyONeal is CI system not triggering "FIXED, REMOVE FROM FAILING" in the PR pipeline anymore?

Correct; we did this to remove the need to have tombstones be a concept when binary caching was productized; instead we build everything every night now and someone is supposed to look at those and fix them regularly.

2021-02-26 07:19 UTC, cenit commented
> Correct; we did this to remove the need to have tombstones be a concept when binary caching was productized; instead we build everything every night now and someone is supposed to look at those and fix them regularly.

ok looks reasonable. But why is not the Support manifest tag treated the same way? If a port is ever going to be fixed, CI will never notice it automatically, always skipping it and leaving the burden on the author (which I am sure will forget it)

2021-04-07 21:22 UTC, merged