[iir1] Add new port
microsoft/vcpkg pull request #16436
Opened 2021-02-26 14:40 UTC by andywang0607

**Describe the pull request**

- What does your PR fix?
  - Fixes #16367
- Which triplets are supported/not supported? Have you updated the CI baseline?
  - I've tested x64-windows, x86-windows and x64-linux locally. I'm assuming that this will support most triplets, but I really don't know.
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  - Yes (as far as I am aware)

2021-03-01 08:44 UTC, Cheney-W commented on ports/iir1/portfile.cmake
> +set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/iir1-1.8.0)
Please remove this sentence.

2021-03-01 08:46 UTC, Cheney-W commented on ports/iir1/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
Since this port saved on github, please use vcpkg_from_github() function instead of vcpkg_download_distfile().
`vcpkg_from_github(`
`    OUT_SOURCE_PATH SOURCE_PATH`
`    REPO berndporr/iir1`
`    REF 67591c8eac591c576b9aabe9a2f288296bb263f0 #1.8.0`
`    SHA512 7bea56bd3a5251656834f43ea55e1a8bff48ed2b5576ea9d7bc058e371457b7a3e8fe26111ec9457d4aa9e397f3267d330c5353aea00810a5cc4d9bec2bdcc72`
`    HEAD_REF master`
`)`

2021-03-01 08:47 UTC, Cheney-W commented on ports/iir1/portfile.cmake
> +vcpkg_extract_source_archive(${ARCHIVE})
Please remove this sentence.

2021-03-01 08:55 UTC, Cheney-W commented on ports/iir1/vcpkg.json
> +  "version-string": "1.8.0",
```suggestion
  "version": "1.8.0",
```
Please see the doc https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#22-package-versions to learn more about package versions.

2021-03-02 02:30 UTC, Cheney-W requested changes

2021-03-02 02:30 UTC, Cheney-W commented on ports/iir1/portfile.cmake
> +OUT_SOURCE_PATH SOURCE_PATH
```suggestion
    OUT_SOURCE_PATH SOURCE_PATH
```
Each parameter in the vcpkg_from_github() function is preceded by four spaces. Could you please add them? 
BTW, after modifying this file and executed the git commit command, please continue to run **vcpkg x-add-version iir1 --overwrite-version** to update the josn file, so the CI system will work again.

2021-03-03 01:50 UTC, Cheney-W approved these changes

2021-03-03 01:53 UTC, andywang0607 commented
@Cheney-W Thanks for review and instruction

2021-03-10 20:13 UTC, ras0219-msft requested changes
This LGTM once the excess lines have been removed.

2021-03-10 20:13 UTC, ras0219-msft commented on ports/iir1/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" KEYSTONE_BUILD_STATIC)
This looks like it was copied from `keystone` -- is this needed?

2021-03-10 20:13 UTC, ras0219-msft commented on ports/iir1/portfile.cmake
> +        -DKEYSTONE_BUILD_SHARED=${KEYSTONE_BUILD_SHARED}
```suggestion
```

2021-03-29 17:08 UTC, merged