[protobuf] Update to 3.15.3
microsoft/vcpkg pull request #16449
Opened 2021-02-27 19:14 UTC by yonik

Library name: protobuf

New version number: 3.15.3

See https://github.com/protocolbuffers/protobuf/releases for release notes.
3.15 makes "optional" available and contains a number of enhancements, bugfixes and security fixes for  c++

2021-03-01 08:18 UTC, NancyLi1013 requested changes

2021-03-01 08:18 UTC, NancyLi1013 commented on ports/protobuf/vcpkg.json
> +  "version-string": "3.15.3",
```suggestion
  "version-semver": "3.15.3",
```
For the package version, please this doc https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md

2021-03-01 08:18 UTC, NancyLi1013 commented on versions/p-/protobuf.json
> +      "version-string": "3.15.3",
```suggestion
      "version-semver": "3.15.3",
```
The same as above.

2021-03-01 08:18 UTC, NancyLi1013 commented
Hi @yonik 

Thanks for your PR.

Have you tested the feature `zlib`?

2021-03-11 15:54 UTC, yonik commented
> Have you tested the feature zlib?

No, but I can do so.

2021-03-11 21:09 UTC, yonik commented
protobuf[zlib] also seems fine

2021-03-12 01:42 UTC, NancyLi1013 approved these changes

2021-03-12 01:43 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @yonik.

2021-04-09 17:38 UTC, vicroms commented
Hi @yonik 

Can you please fix the conflicts?

2021-04-09 17:48 UTC, ytbigvinny27 reviewed
🔝

2021-04-12 17:51 UTC, Farhangv commented
Thanks, @yonik for the PR!
Is it now ready to be merged?

2021-04-12 18:16 UTC, merged