[vcpkg_*_cmake] remove deprecation message
microsoft/vcpkg pull request #16480
Opened 2021-03-01 18:54 UTC by strega-nil

to be replaced by a note in the maintainer-guide
this allows existing ports to build without warnings, so as to avoid warning people unnecessarily,
while still making sure people update when they update ports.

2021-03-01 19:41 UTC, strega-nil commented
/azp run

2021-03-02 17:34 UTC, strega-nil commented
/azp run

2021-03-02 20:37 UTC, ras0219 requested changes
LGTM once rescoped to just removing the deprecation message

2021-03-02 20:37 UTC, ras0219 commented on docs/maintainers/maintainer-guide.md
> +5. `vcpkg_configure_cmake()`, `vcpkg_build_cmake()`, and `vcpkg_install_cmake()` should be replaced by the helper functions in [`vcpkg-cmake`](ports/vcpkg-cmake.md).
We should wait to add this to the maintainer guide until we've successfully deployed these across several ports

2021-03-02 20:41 UTC, ras0219 commented
Additionally, if just the maintainer guide changes are reverted, this LGTM as a hotfix that should be applied bypassing CI.

2021-03-03 01:02 UTC, strega-nil commented on docs/maintainers/maintainer-guide.md
> +5. `vcpkg_configure_cmake()`, `vcpkg_build_cmake()`, and `vcpkg_install_cmake()` should be replaced by the helper functions in [`vcpkg-cmake`](ports/vcpkg-cmake.md).
```suggestion
```

2021-03-03 01:03 UTC, merged