Don't copy svm-toy if not on Windows
microsoft/vcpkg pull request #16501
Opened 2021-03-02 17:58 UTC by SoftwareApe

svm-toy is only compiled on Windows, so should only be copied on Windows.

**Describe the pull request**

- What does your PR fix? Fixes platform dependence on libsvm with tool feature enabled.

- Which triplets are supported/not supported? Have you updated the CI baseline? x64-linux

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2021-03-03 02:58 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

2021-03-03 09:03 UTC, SoftwareApe commented
@JackBoosY I updated to the new vcpkg.json manifest format along the way. I bumped to port-version 1, since I assumed default is 0 if no port-version field exists.

2021-03-04 06:20 UTC, JackBoosY approved these changes

2021-03-10 20:02 UTC, ras0219-msft commented
Awesome work, thanks for the PR!

2021-03-10 20:02 UTC, merged