[icu] add host depedency
microsoft/vcpkg pull request #16577
Opened 2021-03-06 19:48 UTC by autoantwort

**Describe the pull request**

- What does your PR fix? Fixes #16424

Same as #16433, but now with host support in vcpkg as base

2021-03-06 20:38 UTC, Neumann-A commented on ports/icu/portfile.cmake
> +        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --build=arm-darwin --host=x86_64-apple-darwin --with-cross-build=${CURRENT_BUILDTREES_DIR}/${_HOST_TRIPLET}-rel/")
thats not going to work. You cannot reference the buildtree of the host.

2021-03-06 21:08 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --build=arm-darwin --host=x86_64-apple-darwin --with-cross-build=${CURRENT_BUILDTREES_DIR}/${_HOST_TRIPLET}-rel/")
Hm ok, than there is afaik no way to build icu cross platform and you have to install the triplet for the host manually, which is impossible for manifest installs. 

Why can I not access the buildtree of the host?  
This is the current portfile script:
```cmake
    if(CMAKE_HOST_WIN32 AND (VCPKG_TARGET_ARCHITECTURE STREQUAL "arm" OR VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64") AND NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" AND NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "MinGW")
        set(ICU_MSVC_CROSS_COMPILE_TO_ARM ON)
        # Need the buildtrees dir, as the required files (e.g. icucross.mk) are not part of the installed package
        get_filename_component(ICU_HOST_PATH "${BUILDTREES_DIR}/icu/x86-windows-rel" ABSOLUTE)
        if(NOT EXISTS "${ICU_HOST_PATH}")
            message(FATAL_ERROR "The x86 icu must be be built locally to build for non-x86/x64 platforms. Please run `vcpkg install icu:x86-windows`.")
        endif()

        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --with-cross-build=${ICU_HOST_PATH}")
        set(ENV{PATH} "$ENV{PATH}${VCPKG_HOST_PATH_SEPARATOR}${ICU_HOST_PATH}/lib")
    endif()
```

2021-03-06 21:45 UTC, Neumann-A commented on ports/icu/portfile.cmake
> +        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --build=arm-darwin --host=x86_64-apple-darwin --with-cross-build=${CURRENT_BUILDTREES_DIR}/${_HOST_TRIPLET}-rel/")
>Why can I not access the buildtree of the host?

There is the possibility that it does not exist (e.g. due to binary caching or cleaning after a separate build. )

2021-03-06 22:20 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --build=arm-darwin --host=x86_64-apple-darwin --with-cross-build=${CURRENT_BUILDTREES_DIR}/${_HOST_TRIPLET}-rel/")
> There is the possibility that it does not exist (e.g. due to binary caching or cleaning after a separate build)

Ok, then we have to emit an error and say that you have to build with `--binarysource=clear` (actually the current behavior)

2021-03-06 23:27 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --build=arm-darwin --host=x86_64-apple-darwin --with-cross-build=${CURRENT_BUILDTREES_DIR}/${_HOST_TRIPLET}-rel/")
Hm ok, the pipeline clears the buildtree folder after each package installation. Do you have an idea how to solve this?

2021-03-07 01:01 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --build=arm-darwin --host=x86_64-apple-darwin --with-cross-build=${CURRENT_BUILDTREES_DIR}/${_HOST_TRIPLET}-rel/")
Ok, I now install the required files that are needed to cross compile to`tools/icu/for-cross-compile`

2021-03-07 23:38 UTC, Neumann-A commented on ports/icu/portfile.cmake
>  file(COPY ${CROSS_COMPILE_TOOLS} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/for-cross-compile/bin)
```suggestion
file(COPY ${CROSS_COMPILE_TOOLS} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin)
```
i think the additional subfolder is not needed. Or is there a reason to have it?

2021-03-07 23:56 UTC, autoantwort commented on ports/icu/portfile.cmake
>  file(COPY ${CROSS_COMPILE_TOOLS} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/for-cross-compile/bin)
The only requirement is, that there is a folder `bin` with the executables and next to `bin` folder a `config`folder with the icucross.* files. I have chosen an extra `for-cross-compile` folder to make the intention of the folder content clear, otherwise it might be a little bit strange why the executables are duplicated in a bin folder next to the executables.

2021-03-09 02:50 UTC, JackBoosY commented
@Neumann-A Do you have any other questions?

2021-03-09 20:44 UTC, Neumann-A commented
@JackBoosY: all tools should be moved into `${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin` if the bin folder is required instead of having an extra for-cross-compile subfolder.

2021-03-09 20:46 UTC, Neumann-A commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
the port needs to be switched either to `vcpkg_configure_make` if possible or use the function to detect the cmake compiler options/flags.

2021-03-10 00:55 UTC, autoantwort commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
> use the function to detect the cmake compiler options/flags.

What do you mean? Can you give an hint/example/documentation link?

2021-03-10 01:11 UTC, autoantwort commented
> @JackBoosY: all tools should be moved into ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin if the bin folder is required instead of having an extra for-cross-compile subfolder.

Ok, it now don't use the `for-cross-compile` subfolder anymore.

2021-03-10 01:39 UTC, JackBoosY commented
Shoud we wait for PR https://github.com/microsoft/vcpkg/pull/16627?

2021-03-10 10:22 UTC, autoantwort commented
> Shoud we wait for PR #16627?

Then we can use `${HOST_TRIPLET}` instead of `${_HOST_TRIPLET}`

2021-03-11 23:13 UTC, autoantwort commented
I don't think that the `x86_windows` pipeline failure is caused by the latest commit.

2021-03-13 02:59 UTC, JackBoosY commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
@Neumann-A  Can you explain more?

2021-03-16 19:03 UTC, ras0219-msft commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
CMake knows what compiler flags are required to cross compile -- we should use that instead of reimplementing it.

We can get the flags that CMake would use via https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/internal/vcpkg_internal_get_cmake_vars.md, however that's internal only since we may wish to change it in the future. Instead, it would be best to find a way to use https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_make.cmake which will correctly set CXXFLAGS & friends.

2021-03-16 19:11 UTC, ras0219-msft requested changes
This looks really great and I'm excited to merge!

I agree with @Neumann-A that it's probably better to use `vcpkg_internal_get_cmake_vars()` instead of hardcoding `-arch x86_64`.

2021-03-16 19:11 UTC, ras0219-msft commented on ports/icu/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/lib/icu*${ICU_VERSION_MAJOR}.dll
It would probably be better to use `vcpkg_copy_tool_dependencies()` instead of manually globbing the DLLs. This function may be updated to support `.so` and `.dylib` in the future.

2021-03-16 19:11 UTC, ras0219-msft commented on ports/icu/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/lib/icu*${ICU_VERSION_MAJOR}.dll
Additionally, we could probably replace the original purge of the bin directory above (line ~340ish) with `vcpkg_copy_tools()`. Even if `vcpkg_copy_tools()` isn't applicable, it would be better to move those files to the tools directory instead of deleting and re-copying from the buildtrees.

2021-03-16 19:11 UTC, ras0219-msft commented on ports/icu/vcpkg.json
> +  "version-string": "67.1",
```suggestion
  "version": "67.1",
```

2021-03-17 12:43 UTC, autoantwort commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
> Instead, it would be best to find a way to use https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_make.cmake which will correctly set CXXFLAGS & friends.

Afaik vcpkg_configure_make only runs configure, but icu needs `"${SOURCE_PATH}/source/runConfigureICU ${PLATFORM} ${CONFIGURE_OPTIONS} ${CONFIGURE_OPTIONS_RELEASE}"`

2021-03-17 12:54 UTC, Neumann-A commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
the last time I checked `runConfigureICU` it was just a fancy way to run configure if I remember correctly.

2021-03-17 12:58 UTC, autoantwort commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
Yes it sets flags for every Platform: https://github.com/unicode-org/icu/blob/master/icu4c/source/runConfigureICU

2021-03-17 13:11 UTC, Neumann-A commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
The point here is that `vcpkg_configure_make` will do what `runConfigureICU` does with the flags from the `CMAKE_TOOLCHAIN_FILE`. Unless there is something ontop of that you can simply pass it as an option to  `vcpkg_configure_make`

2021-03-17 15:31 UTC, autoantwort commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
Ok cool. I have started changing it and one thing I noticed is that the current configure use `${CURRENT_PACKAGES_DIR}` as prefix and `vcpkg_configure_make` uses `${CURRENT_INSTALLED_DIR}`. What is the difference or idea behind this folders, which one is right? Is there documentation for that?

2021-03-17 18:39 UTC, autoantwort commented
@Neumann-A @ras0219-msft  If you have any idea what the problem with the windows build could be let me know.

2021-03-17 19:35 UTC, autoantwort commented on ports/icu/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/lib/icu*${ICU_VERSION_MAJOR}.dll
> Additionally, we could probably replace the original purge of the bin directory above (line ~340ish) with vcpkg_copy_tools()

The problem with `vcpkg_copy_tools()` is, that it copies to `${CURRENT_PACKAGES_DIR}/tools/${PORT}`, but the files must be copied to `${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin`

2021-03-17 20:58 UTC, Neumann-A commented on ports/icu/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/lib/icu*${ICU_VERSION_MAJOR}.dll
you could use `set(PORT "${PORT}/bin")` but you could also add an option like `SUBDIR` or `DESTINATION` to `vcpkg_copy_tools`

2021-03-18 12:28 UTC, Neumann-A commented
@autoantwort You probably want to cleanup the portfile a bit more so it only uses `vcpkg_configure_make()` and `vcpkg_install_make()`. The whole debug/release thing in the portfile looks fishy. I don't know about the rpath issues on OSX though but it looks like it should be at least refactored into a `foreach` loop.

2021-03-18 12:39 UTC, autoantwort commented
> @autoantwort You probably want to cleanup the portfile a bit more so it only uses `vcpkg_configure_make()` and `vcpkg_install_make()`. 

I am already working on it :)

> The whole debug/release thing in the portfile looks fishy. I don't know about the rpath issues on OSX though but it looks like it should be at least refactored into a `foreach` loop.

The macOS issues are still there, but they are fixed in the next release that is not released yet. Yes to some extend `foreach` loops should be possible.

2021-03-18 13:27 UTC, autoantwort commented on ports/icu/portfile.cmake
> +                set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -arch x86_64")
> I now get tons of warnings like

They are gone now. Idk why, but they are gone :D

It now uses `vcpkg_configure_make`

2021-03-18 13:28 UTC, autoantwort commented on ports/icu/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/lib/icu*${ICU_VERSION_MAJOR}.dll
I have added a `DESTINATION` parameter to `vcpkg_copy_tools`

2021-03-18 13:43 UTC, autoantwort commented on ports/icu/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/lib/icu*${ICU_VERSION_MAJOR}.dll
The problem with `vcpkg_copy_tool_dependencies` is, that it does not copy the tool dependencies ...  
On my mashine it copies nothing and cmake can't start the applications because of missing dlls

2021-03-19 02:14 UTC, JackBoosY commented
Please run `vcpkg x-add-version icu --overwrite-version` then commit changes.

2021-03-19 02:27 UTC, autoantwort commented
> Please run `vcpkg x-add-version icu --overwrite-version` then commit changes.

I know :) But the idea was to first fix the mingw build and maybe the copying of the *.pdb files on windows.

2021-03-19 11:43 UTC, autoantwort commented
The problem with the mingw build is that the icu build system does not detect that it will be compiled with mingw. So it build with `\` as path separator, `.lib` as static library ending, places `.dll` files in `/lib` ([should be fixed](https://github.com/unicode-org/icu/pull/945)) and several other things. Did someone have an idea @Neumann-A @ras0219-msft? Or should I create an issue at icu?

2021-03-22 13:44 UTC, autoantwort commented
The Problem with the pdb files is, that `vcpkg_configure_make` automatically adds `-Z7` to the flags even if `-Zi` is already there so that no pdb files gets generated. I don't know how to fix that.  

It seems that you also have no idea how to fix the mingw build. So I would not support mingw in this PR. 

I now remove `vcpkg_copy_pdbs`, add the version files and than this PR is finished from my side.

2021-03-22 13:55 UTC, Neumann-A commented
> The Problem with the pdb files is, that vcpkg_configure_make automatically adds -Z7 to the flags even if -Zi is already there so that no pdb files gets generated. I don't know how to fix that.

`vcpkg_configure_make` does not delete flags. It uses the `CMAKE_TOOLCHAIN_FILE` or `VCPKG_CHAINLOOAD_TOOLCHAIN_FILE`. The default windows toolchain for vcpkg uses `/Z7`
https://github.com/microsoft/vcpkg/blob/9986c28da97f316fe3c79be0538af8f46a200796/scripts/toolchains/windows.cmake#L28-L31
as such no pdb files are generated. The main issue is when somebody uses a custom toolchain with `/Zi` instead

2021-03-22 14:20 UTC, autoantwort commented
> The main issue is when somebody uses a custom toolchain with `/Zi` instead

Ok, so you propose to add `vcpkg_copy_pdbs` back again for the case that somebody is using a custom toolchain file with `/Zi`?

2021-03-22 19:33 UTC, autoantwort commented
again some random errors in the pipeline

2021-03-23 00:41 UTC, JackBoosY commented
Already reran the pipeline test.

2021-03-23 10:33 UTC, JackBoosY commented
Need wait for #16837 merge first.

2021-03-25 16:51 UTC, autoantwort commented
@JackBoosY #16837 is merged, can you rerun the pipeline ? :)

2021-03-26 17:29 UTC, JackBoosY commented
/azp run

2021-03-29 17:08 UTC, JackBoosY commented
/azp run

2021-03-30 05:55 UTC, JackBoosY commented
@autoantwort  Is this PR ready for review?

2021-03-30 11:33 UTC, autoantwort commented
> @autoantwort Is this PR ready for review?

Yes

2021-03-31 01:57 UTC, JackBoosY requested changes

2021-03-31 01:57 UTC, JackBoosY commented on ports/icu/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin
I think the tools should be moved to _${CURRENT_PACKAGES_DIR}/tools/${PORT}_.

2021-03-31 10:14 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin
No, see [here](https://github.com/microsoft/vcpkg/pull/16577#issuecomment-794430062)

2021-04-01 01:39 UTC, JackBoosY commented on ports/icu/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin
Can you please add a comment here?

2021-04-01 23:36 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin
Done

2021-04-02 12:45 UTC, autoantwort commented
Again a lot of random ci errors. I mean I changed a comment and the last ci was successful ...

2021-04-07 14:08 UTC, autoantwort commented
All random ci errors are gone. Ready for review.

2021-04-08 02:33 UTC, JackBoosY approved these changes

2021-04-14 23:47 UTC, ras0219 requested changes

2021-04-14 23:47 UTC, ras0219 commented on ports/icu/portfile.cmake
> +        set(VCPKG_MAKE_BUILD_TRIPLET --host=x86_64-w64-mingw32)
This should pass `BUILD_TRIPLET` to `vcpkg_configure_make()` instead -- this variable is intended for the triplet to potentially overwrite the setting.

https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/docs/maintainers/vcpkg_configure_make.md#build_triplet

2021-04-14 23:47 UTC, ras0219 commented on ports/icu/portfile.cmake
> +        vcpkg_build_make()
I'm very confused why `vcpkg_build_make` and `vcpkg_install_make` are guarded inside `VCPKG_BUILD_TYPE` -- the previous code was explicitly building each flavor separately, but the helpers already build both/either as needed.

2021-04-15 00:03 UTC, autoantwort commented on ports/icu/portfile.cmake
> +        vcpkg_build_make()
The problem is that: `add ID_PREFIX to libicudata libicui18n libicuio ...` should only be done on dynamic mac release builds (the same as before).  
But you are right, the new line 138/140 should be an `else()`, so that the lib is not build twice.

2021-04-20 00:18 UTC, strega-nil commented
@autoantwort could you merge with latest master?

2021-04-21 03:55 UTC, JackBoosY commented
Will rerun the osx pipeline test later.

2021-04-30 17:00 UTC, JackBoosY commented
When building `libheif:x64-linux`:
```
CMake Error at gdk-pixbuf/CMakeLists.txt:18 (install):
  install TARGETS given no LIBRARY DESTINATION for module target
  "pixbufloader-heif".
```

2021-04-30 17:03 UTC, JackBoosY commented
@autoantwort  I've got the failure log, will restart pipeline test now.

2021-04-30 17:11 UTC, autoantwort commented
> When building `libheif:x64-linux`

Maybe #17593 fixes that

2021-04-30 18:36 UTC, autoantwort commented
> > When building `libheif:x64-linux`
> 
> Maybe #17593 fixes that

Ok seems that a simple rerun solved the problem :)

2021-04-30 19:18 UTC, Neumann-A commented
> Ok seems that a simple rerun solved the problem :)

that is because gdk-pixbuf will not be restored in the rerun and so libheif does not pick it up and installs successfully.

2021-05-01 01:07 UTC, strega-nil-ms approved these changes
double documentation! o noes

2021-05-01 01:07 UTC, strega-nil-ms commented on docs/maintainers/vcpkg_copy_tools.md
> +    [DESTINATION <${CURRENT_PACKAGES_DIR}/tools/${PORT}>]
```suggestion
```

2021-05-01 01:07 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_copy_tools.cmake
> +    [DESTINATION <${CURRENT_PACKAGES_DIR}/tools/${PORT}>]
```suggestion
```

double documented option

2021-05-01 01:12 UTC, autoantwort reviewed
Seems that the DESTINATION option was also added in another PR

2021-05-01 01:12 UTC, autoantwort commented on docs/maintainers/vcpkg_copy_tools.md
> +
```suggestion
```

2021-05-01 01:12 UTC, autoantwort commented on scripts/cmake/vcpkg_copy_tools.cmake
> +
```suggestion
```

2021-05-01 11:46 UTC, autoantwort commented
Most random ci errors were resolved by a rerun, now this PR only depends on #17610

2021-05-01 16:53 UTC, strega-nil-ms commented
/azp run

2021-05-01 18:16 UTC, merged

2021-05-01 18:17 UTC, strega-nil-ms commented
Thanks @autoantwort :)