CGAL: Restore boost dependencies
microsoft/vcpkg pull request #16592
Opened 2021-03-08 08:52 UTC by maxGimeno

The boost packages listed in the dependencies are unsufficient. We need the whole boost as a dependency, not just a few modules.

2021-03-08 10:58 UTC, PhoebeHui requested changes
@maxGimeno, thanks for the PR!

Could you update the port version?

2021-03-08 10:58 UTC, PhoebeHui commented on ports/cgal/CONTROL
>  Port-Version: 1
```suggestion
Port-Version: 2
```

2021-03-09 01:36 UTC, PhoebeHui approved these changes

2021-03-10 18:09 UTC, ras0219-msft commented
The problem with listing all of boost is that it includes additional heavy modules, like:
- `boost-python` and therefore a transitive dependency on `python3` and `libffi`
- `boost-asio` and therefore a transitive dependency on `openssl`

plus others.

Diff:
```diff
diff --git "a/.\\cgaldeps.cur.txt" "b/.\\cgaldeps.txt"
index 6b0087f9e..5fcda1959 100644
--- "a/.\\cgaldeps.cur.txt"
+++ "b/.\\cgaldeps.txt"
@@ -1,93 +1,164 @@
 Computing installation plan...
 The following packages will be built and installed:
+    boost[core]:x86-windows -> 1.75.0
+  * boost-accumulators[core]:x86-windows -> 1.75.0
   * boost-algorithm[core]:x86-windows -> 1.75.0
   * boost-align[core]:x86-windows -> 1.75.0
   * boost-any[core]:x86-windows -> 1.75.0
   * boost-array[core]:x86-windows -> 1.75.0
+  * boost-asio[core]:x86-windows -> 1.75.0#1
   * boost-assert[core]:x86-windows -> 1.75.0
+  * boost-assign[core]:x86-windows -> 1.75.0
   * boost-atomic[core]:x86-windows -> 1.75.0
+  * boost-beast[core]:x86-windows -> 1.75.0
   * boost-bimap[core]:x86-windows -> 1.75.0
   * boost-bind[core]:x86-windows -> 1.75.0
   * boost-build[core]:x86-windows -> 1.75.0.beta1#1
+  * boost-callable-traits[core]:x86-windows -> 1.75.0
   * boost-chrono[core]:x86-windows -> 1.75.0
   * boost-circular-buffer[core]:x86-windows -> 1.75.0
   * boost-compatibility[core]:x86-windows -> 1.75.0
+  * boost-compute[core]:x86-windows -> 1.75.0
   * boost-concept-check[core]:x86-windows -> 1.75.0#1
   * boost-config[core]:x86-windows -> 1.75.0
   * boost-container[core]:x86-windows -> 1.75.0
   * boost-container-hash[core]:x86-windows -> 1.75.0
+  * boost-context[core]:x86-windows -> 1.75.0
+  * boost-contract[core]:x86-windows -> 1.75.0
   * boost-conversion[core]:x86-windows -> 1.75.0
+  * boost-convert[core]:x86-windows -> 1.75.0
   * boost-core[core]:x86-windows -> 1.75.0
+  * boost-coroutine[core]:x86-windows -> 1.75.0
+  * boost-coroutine2[core]:x86-windows -> 1.75.0
+  * boost-crc[core]:x86-windows -> 1.75.0
   * boost-date-time[core]:x86-windows -> 1.75.0
   * boost-detail[core]:x86-windows -> 1.75.0
+  * boost-dll[core]:x86-windows -> 1.75.0
   * boost-dynamic-bitset[core]:x86-windows -> 1.75.0
   * boost-endian[core]:x86-windows -> 1.75.0
   * boost-exception[core]:x86-windows -> 1.75.0
+  * boost-fiber[core]:x86-windows -> 1.75.0
+  * boost-filesystem[core]:x86-windows -> 1.75.0
+  * boost-flyweight[core]:x86-windows -> 1.75.0
   * boost-foreach[core]:x86-windows -> 1.75.0
   * boost-format[core]:x86-windows -> 1.75.0
   * boost-function[core]:x86-windows -> 1.75.0
   * boost-function-types[core]:x86-windows -> 1.75.0
   * boost-functional[core]:x86-windows -> 1.75.0
   * boost-fusion[core]:x86-windows -> 1.75.0
+  * boost-geometry[core]:x86-windows -> 1.75.0
+  * boost-gil[core]:x86-windows -> 1.75.0
   * boost-graph[core]:x86-windows -> 1.75.0
+  * boost-graph-parallel[core]:x86-windows -> 1.75.0
+  * boost-hana[core]:x86-windows -> 1.75.0
   * boost-heap[core]:x86-windows -> 1.75.0
+  * boost-histogram[core]:x86-windows -> 1.75.0
+  * boost-hof[core]:x86-windows -> 1.75.0
+  * boost-icl[core]:x86-windows -> 1.75.0
   * boost-integer[core]:x86-windows -> 1.75.0
+  * boost-interprocess[core]:x86-windows -> 1.75.0
   * boost-interval[core]:x86-windows -> 1.75.0
   * boost-intrusive[core]:x86-windows -> 1.75.0
   * boost-io[core]:x86-windows -> 1.75.0
+  * boost-iostreams[core]:x86-windows -> 1.75.0
   * boost-iterator[core]:x86-windows -> 1.75.0
+  * boost-json[core]:x86-windows -> 1.75.0
   * boost-lambda[core]:x86-windows -> 1.75.0
+  * boost-leaf[core]:x86-windows -> 1.75.0
   * boost-lexical-cast[core]:x86-windows -> 1.75.0
+  * boost-local-function[core]:x86-windows -> 1.75.0
+  * boost-locale[core]:x86-windows -> 1.75.0
+  * boost-lockfree[core]:x86-windows -> 1.75.0
+  * boost-log[core]:x86-windows -> 1.75.0
   * boost-logic[core]:x86-windows -> 1.75.0
   * boost-math[core]:x86-windows -> 1.75.0
+  * boost-metaparse[core]:x86-windows -> 1.75.0
   * boost-modular-build-helper[core]:x86-windows -> 1.75.0#6
   * boost-move[core]:x86-windows -> 1.75.0
   * boost-mp11[core]:x86-windows -> 1.75.0
   * boost-mpl[core]:x86-windows -> 1.75.0
+  * boost-msm[core]:x86-windows -> 1.75.0
+  * boost-multi-array[core]:x86-windows -> 1.75.0
   * boost-multi-index[core]:x86-windows -> 1.75.0
   * boost-multiprecision[core]:x86-windows -> 1.75.0
+  * boost-nowide[core]:x86-windows -> 1.75.0
   * boost-numeric-conversion[core]:x86-windows -> 1.75.0
+  * boost-odeint[core]:x86-windows -> 1.75.0
   * boost-optional[core]:x86-windows -> 1.75.0
+  * boost-outcome[core]:x86-windows -> 1.75.0
   * boost-parameter[core]:x86-windows -> 1.75.0
+  * boost-parameter-python[core]:x86-windows -> 1.75.0
+  * boost-pfr[core]:x86-windows -> 1.75.0
   * boost-phoenix[core]:x86-windows -> 1.75.0
+  * boost-poly-collection[core]:x86-windows -> 1.75.0
+  * boost-polygon[core]:x86-windows -> 1.75.0
   * boost-pool[core]:x86-windows -> 1.75.0
   * boost-predef[core]:x86-windows -> 1.75.0
   * boost-preprocessor[core]:x86-windows -> 1.75.0
+  * boost-process[core]:x86-windows -> 1.75.0
+  * boost-program-options[core]:x86-windows -> 1.75.0
   * boost-property-map[core]:x86-windows -> 1.75.0
   * boost-property-tree[core]:x86-windows -> 1.75.0
   * boost-proto[core]:x86-windows -> 1.75.0
   * boost-ptr-container[core]:x86-windows -> 1.75.0
+  * boost-python[core]:x86-windows -> 1.75.0#1
+  * boost-qvm[core]:x86-windows -> 1.75.0
   * boost-random[core]:x86-windows -> 1.75.0
   * boost-range[core]:x86-windows -> 1.75.0
   * boost-ratio[core]:x86-windows -> 1.75.0
   * boost-rational[core]:x86-windows -> 1.75.0
   * boost-regex[core]:x86-windows -> 1.75.0
+  * boost-safe-numerics[core]:x86-windows -> 1.75.0
+  * boost-scope-exit[core]:x86-windows -> 1.75.0
   * boost-serialization[core]:x86-windows -> 1.75.0
+  * boost-signals2[core]:x86-windows -> 1.75.0
   * boost-smart-ptr[core]:x86-windows -> 1.75.0
+  * boost-sort[core]:x86-windows -> 1.75.0
   * boost-spirit[core]:x86-windows -> 1.75.0
+  * boost-stacktrace[core]:x86-windows -> 1.75.0
+  * boost-statechart[core]:x86-windows -> 1.75.0
   * boost-static-assert[core]:x86-windows -> 1.75.0
+  * boost-static-string[core]:x86-windows -> 1.75.0
+  * boost-stl-interfaces[core]:x86-windows -> 1.75.0
   * boost-system[core]:x86-windows -> 1.75.0
   * boost-test[core]:x86-windows -> 1.75.0
   * boost-thread[core]:x86-windows -> 1.75.0
   * boost-throw-exception[core]:x86-windows -> 1.75.0
+  * boost-timer[core]:x86-windows -> 1.75.0
   * boost-tokenizer[core]:x86-windows -> 1.75.0
   * boost-tti[core]:x86-windows -> 1.75.0
   * boost-tuple[core]:x86-windows -> 1.75.0
+  * boost-type-erasure[core]:x86-windows -> 1.75.0
   * boost-type-index[core]:x86-windows -> 1.75.0
   * boost-type-traits[core]:x86-windows -> 1.75.0
   * boost-typeof[core]:x86-windows -> 1.75.0
+  * boost-ublas[core]:x86-windows -> 1.75.0
   * boost-uninstall[core]:x86-windows -> 1.75.0
+  * boost-units[core]:x86-windows -> 1.75.0
   * boost-unordered[core]:x86-windows -> 1.75.0
   * boost-utility[core]:x86-windows -> 1.75.0
+  * boost-uuid[core]:x86-windows -> 1.75.0
   * boost-variant[core]:x86-windows -> 1.75.0
+  * boost-variant2[core]:x86-windows -> 1.75.0
   * boost-vcpkg-helpers[core]:x86-windows -> 7#2
+  * boost-vmd[core]:x86-windows -> 1.75.0
+  * boost-wave[core]:x86-windows -> 1.75.0
   * boost-winapi[core]:x86-windows -> 1.75.0
   * boost-xpressive[core]:x86-windows -> 1.75.0
+  * boost-yap[core]:x86-windows -> 1.75.0
+  * bzip2[core]:x86-windows -> 1.0.8#1
     cgal[core]:x86-windows -> 5.2#1
+  * expat[core]:x86-windows -> 2020-08-18
   * gmp[core]:x86-windows -> 6.2.1#3
+  * libffi[core]:x86-windows -> 3.3#7
+  * liblzma[core]:x86-windows -> 5.2.5#2
   * mpfr[core]:x86-windows -> 4.1.0
+  * openssl[core]:x86-windows -> 1.1.1i
+  * python3[core]:x86-windows -> 3.9.2#1
+  * sqlite3[core]:x86-windows -> 3.34.1
   * vs-yasm[core]:x86-windows -> 0.5.0#1
   * yasm-tool[core]:x86-windows -> 2020-10-12
   * yas [...]

2021-03-11 07:57 UTC, maxGimeno commented
Ok, I see. I admit "all boost modules" is a lot more than I thought it was. I'll try to list those used in CGAL more precisely, and hope I won't miss some.

2021-03-11 08:47 UTC, maxGimeno commented
done

2021-03-11 09:12 UTC, PhoebeHui commented
@maxGimeno, we don't have port boost-pending and boost-archive, so I remove it from the dependency, and fix some port name, could you double check the dependency?

2021-03-11 09:19 UTC, maxGimeno commented
`boost-pending` is OK to skip, but I think `boost-archive` may be more problematic, though it is not essential.

2021-03-11 09:27 UTC, maxGimeno commented
Actually I think I found the hpp that we use in `boost-serialization` : 
`./buildtrees/boost-serialization/src/ost-1.69.0-c06aec2726/include/boost/archive/text_oarchive.hpp`

Maybe `boost-serialization` is enough.

2021-03-12 08:55 UTC, PhoebeHui commented
/azp run

2021-03-16 12:11 UTC, PhoebeHui approved these changes

2021-03-16 18:42 UTC, merged

2021-03-16 18:42 UTC, ras0219-msft commented
Thanks!