[vcpkg_execute_build_process] Add warning message when memory or hard disk space is insufficient
microsoft/vcpkg pull request #16633
Opened 2021-03-10 02:40 UTC by JackBoosY

When building a port in linux, occasionally there will be insufficient memory or disk, we should extract this information and display it in the console.

Related #16586.

2021-03-10 18:13 UTC, ras0219-msft requested changes

2021-03-10 18:13 UTC, ras0219-msft commented on scripts/cmake/vcpkg_execute_build_process.cmake
> +            message(WARNING "Insufficient memory or hard disk space is detected, please make sure there is enough space and try again.")
Signal 9 is a _very_ generic kill signal on linux, and cannot be assumed to mean "out of memory or hard disk". We can only suggest to the user that "ld was terminated with signal 9 [killed] -- ensure the system has sufficient hard disk space and memory".


https://stackoverflow.com/questions/16338884/what-does-exited-abnormally-with-signal-9-killed-9-mean#:~:text=Signal%209%20means%20that%20the%20application%20needs%20to,it%20property,%20then%20the%20process%20continues%20to%20live.

2021-03-13 03:29 UTC, JackBoosY commented on scripts/cmake/vcpkg_execute_build_process.cmake
> +            message(WARNING "Insufficient memory or hard disk space is detected, please make sure there is enough space and try again.")
```suggestion
            message(WARNING "ld was terminated with signal 9 [killed], please ensure your system has sufficient hard disk space and memory.")
```

2021-03-15 00:56 UTC, PhoebeHui approved these changes

2021-03-16 18:52 UTC, merged