New port for mailio.
microsoft/vcpkg pull request #16696
Opened 2021-03-14 13:51 UTC by karastojko

**Describe the pull request**

- What does your PR fix?
  Fixes #16695

- Which triplets are supported/not supported? Have you updated the CI baseline?
  MSVC, Gcc, Clang are supported on Linux, MacOS, Windows.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

2021-03-14 14:05 UTC, autoantwort commented
You have to format your `vcpkg.json` file with `./vcpkg format-manifest ports/mailio/vcpkg.json`. If you have committed this, you have to run `./vcpkg x-add-version mailio`

2021-03-15 02:37 UTC, JackBoosY requested changes
1. Please run `./vcpkg format-manifest --all` first,
2. then run `./vcpkg x-add-version --all` and commit changes.

2021-03-15 02:38 UTC, JackBoosY requested changes

2021-03-15 02:38 UTC, JackBoosY commented on ports/mailio/vcpkg.json
> +  "dependencies": ["boost",	"openssl"]
Please add `maintainers`, see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md#specification).

2021-03-16 03:21 UTC, JackBoosY commented
```
Starting package 263/274: mailio:x64-windows-static
Building package mailio[core]:x64-windows-static...
-- Downloading https://github.com/karastojko/mailio/archive/1872f29d88a52f06cd96b611673b2e46c6b9832b.tar.gz -> karastojko-mailio-1872f29d88a52f06cd96b611673b2e46c6b9832b.tar.gz...
-- Extracting source D:/downloads/karastojko-mailio-1872f29d88a52f06cd96b611673b2e46c6b9832b.tar.gz
-- Using source at D:/buildtrees/mailio/src/46c6b9832b-9aa8aa669f.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: D:/packages/mailio_x64-windows-static/share/mailio/copyright
-- Performing post-build validation
DLLs should not be present in a static build, but the following DLLs were found:

    D:/packages/mailio_x64-windows-static/bin/mailio.dll
    D:/packages/mailio_x64-windows-static/debug/bin/mailio.dll
```
It seems that `BUILD_SHARED_LIBS` is not used in the internal cmake code.

2021-03-17 09:27 UTC, JackBoosY requested changes

2021-03-17 09:27 UTC, JackBoosY commented on ports/mailio/portfile.cmake
> +
```suggestion
```

2021-03-17 09:29 UTC, JackBoosY approved these changes

2021-03-17 09:36 UTC, JackBoosY commented on versions/m-/mailio.json
> +      "git-tree": "52e9f6449fd3bc017e7ca9a41afb9cf07a44b911",
```suggestion
      "git-tree": "125456f1ee58cb9a193ab5dfe95644150a437f0c",
```

2021-03-17 22:10 UTC, ras0219-msft requested changes
LGTM once the version is changed to `0.20.0`. Note that you will need to undo the changes to `versions/` (`git checkout upstream/master -- versions`) and re-run `vcpkg x-add-version mailio`.

2021-03-17 22:10 UTC, ras0219-msft commented on ports/mailio/vcpkg.json
> +  "version-string": "version_0-20-0",
```suggestion
  "version": "0.20.0",
```

2021-03-18 20:46 UTC, karastojko commented
Tag renamed to 0.20.0 to follow the convention.

2021-03-19 16:55 UTC, merged

2021-03-19 16:55 UTC, ras0219-msft commented
Awesome, thanks for the great library and PR :)

2021-03-19 19:40 UTC, autoantwort commented
This port fails in the pipeline for windows uwp, as you can see [here](https://github.com/microsoft/vcpkg/pull/16788)

2022-01-06 15:03 UTC, kotori2 commented
Any idea on how to link this library? Simply use `target_link_libraries(${PROJECT_NAME} mailio)` won't work and `find_package` won't work as well...

2022-01-06 16:20 UTC, karastojko commented
> Any idea on how to link this library? Simply use `target_link_libraries(${PROJECT_NAME} mailio)` won't work and `find_package` won't work as well...

This works for me:
`include_directories(${CMAKE_SOURCE_DIR}/libs/mailio/include)
find_library(MAILIO_LIB mailio HINTS ${CMAKE_SOURCE_DIR}/libs/mailio/build)
add_executable(${PROJ} ${PROJSRC} ${PROJINC})
target_link_libraries(${PROJ} ${Boost_LIBRARIES} Threads::Threads ${OPENSSL_LIBRARIES} ${MAILIO_LIB})
`