[FLANN] Allow to be build as shared lib
microsoft/vcpkg pull request #16724
Opened 2021-03-16 09:56 UTC by larshg

**Describe the pull request**

- What does your PR fix? Allow FLANN to build as shared library.

- Which triplets are supported/not supported? Have you updated the CI baseline? All triplets. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

2021-03-17 03:24 UTC, JackBoosY commented
Please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=50560&view=artifacts&pathAsName=false&type=publishedArtifacts).

2021-03-17 13:16 UTC, larshg commented
@JackBoosY Should I include corrections to pcl, openmvg and others in this PR as well?

2021-03-17 14:26 UTC, JackBoosY commented
@larshg Please fix them in another PR.

2021-03-19 22:43 UTC, larshg commented
#16792  and #16791 are to resolve the PCL and OpenMVG build failures.

2021-03-23 09:25 UTC, larshg commented
The build error on Ubuntu is:

`c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory`

Doesn't seem to have anything with FLANN to do?

2021-03-24 09:50 UTC, JackBoosY commented
I can't repro this issue on my machine, here is my log:
```
[171/249] : && /usr/bin/c++ -fPIC -march=znver1 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -mavx -mfma -mbmi2 -mavx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -g -rdynamic software/SfM/export/CMakeFiles/openMVG_main_openMVG2CMPMVS.dir/main_openMVG2CMPMVS.cpp.o -o Linux-x86_64-Debug/openMVG_main_openMVG2CMPMVS  Linux-x86_64-Debug/libopenMVG_system.a  Linux-x86_64-Debug/libopenMVG_image.a  Linux-x86_64-Debug/libopenMVG_features.a  Linux-x86_64-Debug/libopenMVG_sfm.a  Linux-x86_64-Debug/libopenMVG_stlplus.a  Linux-x86_64-Debug/libopenMVG_system.a  Linux-x86_64-Debug/libopenMVG_image.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libpng16d.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libtiffd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libpng16d.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libtiffd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  Linux-x86_64-Debug/libopenMVG_geometry.a  Linux-x86_64-Debug/libopenMVG_matching.a  Linux-x86_64-Debug/libopenMVG_features.a  Linux-x86_64-Debug/libopenMVG_fast.a  Linux-x86_64-Debug/libopenMVG_stlplus.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libflann_sd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblz4d.a  Linux-x86_64-Debug/libopenMVG_lInftyComputerVision.a  Linux-x86_64-Debug/libopenMVG_multiview.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/lemon/../../debug/lib/libemon.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libceres-debug.a  -pthread  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libglog.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libgflags_debug.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcxsparsed.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libklud.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libbtfd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libldld.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libumfpackd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libspqrd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcholmodd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libccolamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcolamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libsuitesparseconfigd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblapack.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libopenblas.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libmetis.a  -lm  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcxsparsed.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/lib/liblapack.a  -lm  /usr/lib/x86_64-linux-gnu/libgfortran.so.4  /home/vzay/work/16724/vcpkg/installed/x64-linux/lib/libopenblas.a  -lpthread  Linux-x86_64-Debug/libopenMVG_linearProgramming.a  Linux-x86_64-Debug/libopenMVG_numeric.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/clp/../../debug/lib/libClp.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/osi/../../debug/lib/libOsi.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/coinutils/../../debug/lib/libCoinUtils.a && :
```

Yours:
```
[171/249] : && /usr/bin/c++ -fPIC -march=znver1 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -mavx -mfma -mbmi2 -mavx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -g -rdynamic  /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a -pthread -pthread /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a -pthread /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a -pthread -pthread software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/openMVG_main_AlternativeVO_autogen/mocs_compilation.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/main.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/ControlButtonsPanel.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/MainWindow.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/VOFolderProcessor.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/VOViewerPanel.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/VOViewerDrawableElements.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSEmulatorIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSKmsEglDeviceIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSX11IntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QXcbEglIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QXcbGlxIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QXcbIntegrationPlugin_Import.cpp.o -o Linux-x86_64-Debug/openMVG_main_AlternativeVO  -Wl,-rpath,/mnt/vcpkg-ci/installed/x64-linux/debug/lib:  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5Widgets.a  Linux-x86_64-Debug/libopenMVG_image.a  Linux-x86_64-Debug/libopenMVG_features.a  Linux-x86_64-Debug/libopenMVG_stlplus.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5Gui.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/egldeviceintegrations/libqeglfs-emu-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/egldeviceintegrations/libqeglfs-x11-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/imageformats/libqgif.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/imageformats/libqico.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/imageformats/libqjpeg.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/xcbglintegrations/libqxcb-egl-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/xcbglintegrations/libqxcb-glx-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/platforms/libqxcb.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5EglFSDeviceIntegration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5KmsSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5EglFsKmsSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5XcbQpa.a  /mnt/vcpkg-ci/installed/x64-linux/ [...]

2021-03-24 10:16 UTC, larshg commented
> I can't repro this issue on my machine, here is my log:
> 
> ```
> [171/249] : && /usr/bin/c++ -fPIC -march=znver1 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -mavx -mfma -mbmi2 -mavx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -g -rdynamic software/SfM/export/CMakeFiles/openMVG_main_openMVG2CMPMVS.dir/main_openMVG2CMPMVS.cpp.o -o Linux-x86_64-Debug/openMVG_main_openMVG2CMPMVS  Linux-x86_64-Debug/libopenMVG_system.a  Linux-x86_64-Debug/libopenMVG_image.a  Linux-x86_64-Debug/libopenMVG_features.a  Linux-x86_64-Debug/libopenMVG_sfm.a  Linux-x86_64-Debug/libopenMVG_stlplus.a  Linux-x86_64-Debug/libopenMVG_system.a  Linux-x86_64-Debug/libopenMVG_image.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libpng16d.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libtiffd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libpng16d.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libtiffd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  Linux-x86_64-Debug/libopenMVG_geometry.a  Linux-x86_64-Debug/libopenMVG_matching.a  Linux-x86_64-Debug/libopenMVG_features.a  Linux-x86_64-Debug/libopenMVG_fast.a  Linux-x86_64-Debug/libopenMVG_stlplus.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libflann_sd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblz4d.a  Linux-x86_64-Debug/libopenMVG_lInftyComputerVision.a  Linux-x86_64-Debug/libopenMVG_multiview.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/lemon/../../debug/lib/libemon.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libceres-debug.a  -pthread  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libglog.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libgflags_debug.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcxsparsed.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libklud.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libbtfd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libldld.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libumfpackd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libspqrd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcholmodd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libccolamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcolamdd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libsuitesparseconfigd.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/liblapack.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libopenblas.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libmetis.a  -lm  /home/vzay/work/16724/vcpkg/installed/x64-linux/debug/lib/libcxsparsed.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/lib/liblapack.a  -lm  /usr/lib/x86_64-linux-gnu/libgfortran.so.4  /home/vzay/work/16724/vcpkg/installed/x64-linux/lib/libopenblas.a  -lpthread  Linux-x86_64-Debug/libopenMVG_linearProgramming.a  Linux-x86_64-Debug/libopenMVG_numeric.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/clp/../../debug/lib/libClp.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/osi/../../debug/lib/libOsi.a  /home/vzay/work/16724/vcpkg/installed/x64-linux/share/coinutils/../../debug/lib/libCoinUtils.a && :
> ```
> 
> Yours:
> 
> ```
> [171/249] : && /usr/bin/c++ -fPIC -march=znver1 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -mavx -mfma -mbmi2 -mavx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -g -rdynamic  /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a -pthread -pthread /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a -pthread /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a -pthread -pthread software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/openMVG_main_AlternativeVO_autogen/mocs_compilation.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/main.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/ControlButtonsPanel.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/MainWindow.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/VOFolderProcessor.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/VOViewerPanel.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/VOViewerDrawableElements.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSEmulatorIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSKmsEglDeviceIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSX11IntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QGifPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QICOPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QJpegPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QXcbEglIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QXcbGlxIntegrationPlugin_Import.cpp.o software/VO/AlternativeVO/CMakeFiles/openMVG_main_AlternativeVO.dir/mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QXcbIntegrationPlugin_Import.cpp.o -o Linux-x86_64-Debug/openMVG_main_AlternativeVO  -Wl,-rpath,/mnt/vcpkg-ci/installed/x64-linux/debug/lib:  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5Widgets.a  Linux-x86_64-Debug/libopenMVG_image.a  Linux-x86_64-Debug/libopenMVG_features.a  Linux-x86_64-Debug/libopenMVG_stlplus.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5Gui.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/egldeviceintegrations/libqeglfs-emu-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/egldeviceintegrations/libqeglfs-x11-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/imageformats/libqgif.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/imageformats/libqico.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/imageformats/libqjpeg.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/xcbglintegrations/libqxcb-egl-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/xcbglintegrations/libqxcb-glx-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/plugins/platforms/libqxcb.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5EglFSDeviceIntegration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5KmsSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5EglFsKmsSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt5XcbQpa.a  /mnt/vcpkg-c [...]

2021-03-25 02:50 UTC, JackBoosY commented
Glib is not a dependency of openmvg or one of its dependency chains, I am curious why it is linked to glib.

2021-03-29 17:19 UTC, JackBoosY commented
/azp run

2021-04-02 03:14 UTC, PhoebeHui commented
The openmvg:x64-linux failed with following failure in CI testing and will be fixed by https://github.com/microsoft/vcpkg/pull/16954

```
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
```

2021-04-07 08:52 UTC, JackBoosY requested changes

2021-04-07 08:52 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++      # 	target_link_libraries(flann_cuda cudpp_x86_64)
```suggestion
```

2021-04-07 08:52 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++  set_property(TARGET flann_cpp_s PROPERTY COMPILE_DEFINITIONS FLANN_STATIC FLANN_USE_CUDA)
I think we shouldn't change the library name, please add `OUTPUT_NAME flann_cpp`.

2021-04-07 08:52 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++      set_target_properties(flann_cpp PROPERTIES LINKER_LANGUAGE CXX)
See comment above.

2021-04-09 07:40 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++  set_property(TARGET flann_cpp_s PROPERTY COMPILE_DEFINITIONS FLANN_STATIC FLANN_USE_CUDA)
Aren't it supposed to follow the original naming of the project? I think many find_scripts search for flann static libs with _s?

2021-04-09 07:46 UTC, ytbigvinny27 approved these changes

2021-04-12 12:40 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++  set_property(TARGET flann_cpp_s PROPERTY COMPILE_DEFINITIONS FLANN_STATIC FLANN_USE_CUDA)
No, since it's not official, we should do that.
See many examples:
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/libmariadb/export-cmake-targets.patch
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/parson/CMakeLists.txt
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/pcre/export-cmake-targets.patch
etc.

2021-04-30 21:04 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++      set_target_properties(flann_cpp PROPERTIES LINKER_LANGUAGE CXX)
This already has the right name? Not sure I follow you.

Should all be named the same?
Flann
Flann_s
Flann_cpp
Flann_cpp_s
Flann_cuda
Flann_cuda_s

I thought they were dependent, ie. flann_cpp wraps flann?

2021-05-05 14:25 UTC, JackBoosY commented
Sorry for late, I will handle it this week.

2021-05-05 15:16 UTC, larshg commented
I have rebased it and hopefully updated accordingly with control files to json conversion.

2021-05-06 08:51 UTC, JackBoosY requested changes

2021-05-06 08:51 UTC, JackBoosY commented on ports/flann/portfile.cmake
>  vcpkg_from_github(
Since the repo has been changed to `flann-lib/flann`, please modify the line 5 to:
`REPO flann-lib/flann`

2021-05-06 08:51 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++      set_target_properties(flann_cpp PROPERTIES LINKER_LANGUAGE CXX)
See official `Findflann.lib`: https://github.com/flann-lib/flann/blob/master/cmake/FindFlann.cmake.

2021-05-06 10:23 UTC, larshg commented on ports/flann/portfile.cmake
>  vcpkg_from_github(
Changed it.

2021-05-06 10:33 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++      set_target_properties(flann_cpp PROPERTIES LINKER_LANGUAGE CXX)
That one only finds the C version of the library and is obsolete if you ask me.
The correct way is to use the Config files generated, which depending on what you enable will output the correct libraries imports:

This is from my local build for the release verisons:

```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "flann::flann_cpp" for configuration "Release"
set_property(TARGET flann::flann_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(flann::flann_cpp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/flann_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "-Wl,--push-state,--no-as-needed;lz4::lz4;-Wl,--pop-state"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/flann_cpp.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS flann::flann_cpp )
list(APPEND _IMPORT_CHECK_FILES_FOR_flann::flann_cpp "${_IMPORT_PREFIX}/lib/flann_cpp.lib" "${_IMPORT_PREFIX}/bin/flann_cpp.dll" )

# Import target "flann::flann_cpp_s" for configuration "Release"
set_property(TARGET flann::flann_cpp_s APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(flann::flann_cpp_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "lz4::lz4"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/flann_cpp_s.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS flann::flann_cpp_s )
list(APPEND _IMPORT_CHECK_FILES_FOR_flann::flann_cpp_s "${_IMPORT_PREFIX}/lib/flann_cpp_s.lib" )

# Import target "flann::flann" for configuration "Release"
set_property(TARGET flann::flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(flann::flann PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/flann.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "-Wl,--push-state,--no-as-needed;lz4::lz4;-Wl,--pop-state"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/flann.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS flann::flann )
list(APPEND _IMPORT_CHECK_FILES_FOR_flann::flann "${_IMPORT_PREFIX}/lib/flann.lib" "${_IMPORT_PREFIX}/bin/flann.dll" )

# Import target "flann::flann_s" for configuration "Release"
set_property(TARGET flann::flann_s APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(flann::flann_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "-Wl,--push-state,--no-as-needed;lz4::lz4;-Wl,--pop-state"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/flann_s.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS flann::flann_s )
list(APPEND _IMPORT_CHECK_FILES_FOR_flann::flann_s "${_IMPORT_PREFIX}/lib/flann_s.lib" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)

```

2021-05-06 11:23 UTC, larshg commented
I have updated the flann cuda project settings, as it missed a define.

2021-05-06 11:29 UTC, larshg commented
I have added the possibility to enable the cuda build.

2021-05-06 12:12 UTC, larshg commented
When installing now it correctly tells:
In dynamic:
```
The package flann:x64-windows provides CMake targets:

    find_package(flann CONFIG REQUIRED)
    target_link_libraries(main PRIVATE flann::flann flann::flann_cpp flann::flann_cuda)
```
In static:
```
The package flann:x64-windows-static provides CMake targets:

    find_package(flann CONFIG REQUIRED)
    target_link_libraries(main PRIVATE flann::flann_s flann::flann_cpp_s flann::flann_cuda_s)
```

2021-05-07 02:14 UTC, JackBoosY requested changes

2021-05-07 02:14 UTC, JackBoosY commented on ports/flann/vcpkg.json
> +  "version-string": "2019-04-07",
```suggestion
  "version-date": "2019-04-07",
```

2021-05-07 02:14 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> +
Can you revert this change because it only changes the indent?

2021-05-07 02:14 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++  endif()
Why the tools wouldn't be built in static?

2021-05-07 02:14 UTC, JackBoosY commented on versions/f-/flann.json
> +      "version-string": "2019-04-07",
```suggestion
      "version-date": "2019-04-07",
```

2021-05-07 02:14 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++  endif()
As I said, I think the static library output name also should be `flann`.

2021-05-07 09:30 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++  endif()
They depend on the shared version of flann_cpp? there are no original option that depend on flann_cpp_s.

2021-05-07 09:32 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++  endif()
So flann_s -> flann
     flann_cpp_s -> flann_cpp
     flann_cuda_s -> flann_cuda

What if I build both shared and static? One or the other will be overwritten?

2021-05-07 09:33 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++  endif()
I guess its not possible with vcpkg to build both and they are copied to their respective folders ie. static / non-static.

2021-05-07 09:37 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++  endif()
In vcpkg, we should at least NOT let dynamic and static installation at the same time.

2021-05-07 10:08 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++  endif()
It should be changed accordingly now.

However, the config targets is still called flann::flann_s - but it points to flann.lib.

2021-05-08 02:51 UTC, JackBoosY requested changes

2021-05-08 02:51 UTC, JackBoosY commented on ports/flann/fix-build-error.patch
> ++      set_target_properties(flann_cpp PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS YES)
Does the upstream also have `WINDOWS_EXPORT_ALL_SYMBOLS`? According to our policy, we shouldn't use this.

2021-05-10 06:38 UTC, larshg commented on ports/flann/fix-build-error.patch
> ++      set_target_properties(flann_cpp PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS YES)
Yes it does.
If I remove it, it doesn't create any flann_cpp.lib file.

2021-05-10 08:53 UTC, JackBoosY approved these changes

2021-05-26 21:48 UTC, strega-nil-ms commented
This LGTM! Thanks @larshg :)

2021-05-26 21:48 UTC, merged