[openmama] Modify the output path of the common header file
microsoft/vcpkg pull request #16725
Opened 2021-03-16 11:25 UTC by Cheney-W

**Describe the pull request**
In CI Test, workflow installation failed with following errors:
```
error C2079: 'list' uses undefined struct 'list_head'
error C2198: 'list_for_each': too few arguments for call 
error C2143: syntax error: missing ';' before '{'
```
This issue occurs because there is a list.h file generated by openmama and saved in the vcpkg\installed{triplets}\include folder, it conflict with the list.h file of workflow. As a result, the structure and macro defined in the header file list.h(workflow) become undefined during compilation.
After communicatied with upstream, I moved these common header file into the wombat folder and modified the header files those include the common header files.

BTW, update the REPO and homapage from OpenMAMA/OpenMAMA to finos/OpenMAMA, because OpenMAMA/OpenMAMA is no longer found.

2021-03-16 18:49 UTC, ras0219-msft requested changes
Please also validate that you can `#include` every installed file in the `include/` folder and successfully compile (no need to link).

2021-03-16 18:49 UTC, ras0219-msft commented on ports/openmama/portfile.cmake
> +if(EXISTS "${CURRENT_PACKAGES_DIR}/include/mama/integration/transport.h")
These files should always exist iiuc; we shouldn't need `if(EXISTS)`.

2021-03-17 02:59 UTC, Cheney-W commented on ports/openmama/portfile.cmake
> +if(EXISTS "${CURRENT_PACKAGES_DIR}/include/mama/integration/transport.h")
Thanks for your review.

2021-03-17 03:16 UTC, Cheney-W commented
@ras0219-msft 
There are more than 300 header files generated by openmama, most of which have nothing to do with this modification. I have verified the header file that was modified and other header files affected by this modification, and they can be compiled normally. So I want to confirm with you that other header files still need to be verified?

2021-03-17 06:02 UTC, NancyLi1013 approved these changes

2021-03-19 19:54 UTC, ras0219-msft commented
Please create one .cpp file that includes every header and try to compile that file.

```powershell
ls -recurse .\packages\openmama_x64-windows\include\* | % { "#include <$_>" -replace "\\","/" } | out-file -enc ascii test.cpp
```

2021-03-22 08:57 UTC, Cheney-W commented
I have tested all of the generated header files of openmama, and them built failed with following errors:
![error](https://user-images.githubusercontent.com/38240633/111963767-d7c99180-8b2e-11eb-97dd-086b4e8fbfd3.PNG)

I also tested the files of previous versions of openmama and the files manually downloaded from https://github.com/finos/OpenMAMA, and above errors still exist. 
So these errors have nothing to do with this PR.

2021-04-07 05:50 UTC, fquinner commented
Hi it's the OpenMAMA maintainer here and yes this looks good to me. The fact is most users won't actually be using those headers anyway and in future I'll try and get these moved into a subdirectory by default. When that time comes I'll update this workaround in VCPKG but for now yes this looks perfectly fine to me.

2021-04-12 09:07 UTC, NancyLi1013 approved these changes

2021-04-12 16:59 UTC, merged