[qt5-webengine] Fix issues
microsoft/vcpkg pull request #16770
Opened 2021-03-18 12:23 UTC by Neumann-A

changes from #16583

2021-03-18 12:23 UTC, Neumann-A commented on ports/qt5-webengine/portfile.cmake
> +set(VCPKG_BUILD_TYPE release) #You probably want to set this to reduce build type and space requirements
```suggestion
#set(VCPKG_BUILD_TYPE release) #You probably want to set this to reduce build type and space requirements
```

2021-03-18 12:23 UTC, Neumann-A commented on scripts/ci.baseline.txt
> +# qt5-webengine:x64-windows=skip
```suggestion
qt5-webengine:x64-windows=skip
```

2021-03-18 13:05 UTC, JackBoosY commented
Seems CI passed.

2021-03-18 21:37 UTC, strega-nil commented
/azp run

2021-03-18 22:54 UTC, ras0219-msft requested changes
Thanks for the PR! LGTM once we use the official helper.

If you would like it to be a fatal error, we should rely on the official helper to provide the message and then emit the fatal error afterwards.

2021-03-18 22:54 UTC, ras0219-msft commented on ports/qt5-webengine/portfile.cmake
> +endif()
```suggestion
vcpkg_buildpath_length_warning(35)
```

2021-03-18 23:02 UTC, Neumann-A commented on ports/qt5-webengine/portfile.cmake
> +endif()
The helper is used inside of `qt_submodule_installation`

2021-03-25 15:54 UTC, Neumann-A commented on ports/qt5-webengine/portfile.cmake
> +endif()
What I need here is a `vcpkg_buildpath_length_error(35)` and not a warning. Building 2h and getting a long filepath error (file not found although it is there) is not really a good user experience. 
That is why I added it here explicitly.

2021-03-25 16:38 UTC, ras0219-msft commented on ports/qt5-webengine/portfile.cmake
> +endif()
Should qt_submodule_installation be modified to terminate then?

2021-03-26 09:15 UTC, Neumann-A commented on ports/qt5-webengine/portfile.cmake
> +endif()
> Should qt_submodule_installation be modified to terminate then?

Most qt modules are fine on longer paths and I think nobody actually knows the correct number to put into the warning. 
In Qt6 for example I only know of qtquick3d having this issue and it builds rather fast compared to qt5-webengine.

2021-03-26 17:27 UTC, JackBoosY commented
Depends on #16904

2021-03-29 17:12 UTC, JackBoosY approved these changes

2021-03-30 17:56 UTC, merged