[shaderc] Re-fix installation
microsoft/vcpkg pull request #16781
Opened 2021-03-19 05:46 UTC by JackBoosY

Since the tool needs to use static library, enable dynamic and static builds and install the corresponding libraries according to the build type.

Related: #16137.

2021-03-19 05:46 UTC, JackBoosY commented
@jmoguillansky-gpsw  Can you please test this PR?

Thanks.

2021-03-19 06:34 UTC, NancyLi1013 commented
Related issue #16658

2021-03-19 06:34 UTC, NancyLi1013 approved these changes

2021-03-19 16:21 UTC, ras0219-msft requested changes
Please see https://github.com/microsoft/vcpkg/pull/16137#issuecomment-802952196

2021-03-19 19:12 UTC, jmoguillansky-gpsw commented
> @jmoguillansky-gpsw Can you please test this PR?
> 
> Thanks.

Hi @JackBoosY I tested your branch, I was able to build shaderc shared lib successfully.
Thanks, much appreciated!

2021-03-25 08:34 UTC, JackBoosY commented
@ras0219-msft glslang and spir-tools use some symbols that are not exported in shaderc, so if we need to build them, we must first build static shaderc.

2021-03-26 18:11 UTC, ras0219-msft commented
>glslang and spir-tools use some symbols that are not exported in shaderc

shaderc _depends_ on glslang and spirv-tools; therefore they cannot be depending on symbols exported by shaderc:

```
# ports/control/shaderc

Build-Depends: glslang, spirv-tools
```

Therefore, if glslang and spirv-tools can only be built statically, shaderc should also be built statically. Dynamic libraries should (generally) not depend on static libraries.

2021-03-29 17:08 UTC, jmoguillansky-gpsw commented
> The reason I need to use shaderc shared library is because visual studio toolchain doesn't let you mix /MT (multithreaded) and /MD (multithreaded DLL) so if I have a shared library that links against shaderc, it needs to link against the shared lib of shaderc if I understand correctly?

I see there's an option: "DSHADERC_ENABLE_SHARED_CRT", maybe it's possible to use the shaderc static lib if I set this option?
But I don't think vcpkg exposes this option, maybe I need to build shaderc manually from source?

2021-06-11 09:04 UTC, CaptainHorse commented
Any updates on this? Would love to use shaderc thru vcpkg as it has issues with path size limits in my project.

2021-06-17 09:52 UTC, JackBoosY commented
@CaptainHorse  Will continue to handle this PR later.

2021-07-28 09:56 UTC, JackBoosY commented on versions/s-/shaderc.json
> +      "git-tree": "acddbab84ab19cc4d1e04ecb5277d3969cf9b093",
```suggestion
      "git-tree": "f6a82ca83afbf20c08d6d001f133cd5fd2672108",
```

2021-07-29 06:49 UTC, JackBoosY commented
Requires https://github.com/microsoft/vcpkg/pull/19219.

2021-07-30 02:56 UTC, JackBoosY commented
Linux regression related to https://github.com/KhronosGroup/SPIRV-Tools/issues/1569.

2022-02-09 01:06 UTC, PhoebeHui commented
The related upstream issue on linux has been fixed, please reopen and continue this PR if you have time.

2022-02-09 01:06 UTC, closed without merging