Update portfile.cmake
microsoft/vcpkg pull request #16815
Opened 2021-03-21 17:39 UTC by electron271

Updating gtkmm to 4.0.0

**Describe the pull request**

Updates gtkmm to 4.0.0

- What does your PR fix? Fixes #16803 

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

2021-03-21 18:03 UTC, electron271 commented
/azp run

2021-03-21 22:01 UTC, electron271 commented
tried running, and so far its working well installing gtkmm 4

2021-03-21 22:33 UTC, electron271 commented
nope didnt work
```
Error: Building package pcre:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcre:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```

2021-03-22 02:50 UTC, NancyLi1013 requested changes

2021-03-22 02:50 UTC, NancyLi1013 commented on ports/gtkmm/CONTROL
>  Port-Version: 5
```suggestion
```
Since this is a new version update, it's unnecessary to add this field here now. Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#port-version

2021-03-22 02:50 UTC, NancyLi1013 commented on ports/gtkmm/portfile.cmake
>  vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Could you please update 
```
if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL WindowsStore)
    message(FATAL_ERROR "Error: UWP builds are currently not supported.")
endif()
```
as

`vcpkg_fail_port_install(ON_TARGET "uwp")` ?

2021-03-22 02:50 UTC, NancyLi1013 commented on ports/gtkmm/portfile.cmake
>  vcpkg_extract_source_archive_ex(
Could you please update 

`file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/gtkmm RENAME copyright)`

as


`file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2021-03-22 02:52 UTC, NancyLi1013 commented
Hi @electron271 

Thanks for this PR.

It seems that you didn't update the patch.
```
-- Applying patch fix_properties.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:57 (message):
  Applying patch failed: Checking patch MSVC_Net2013/gdkmm.vcxproj...

  error: MSVC_Net2013/gdkmm.vcxproj: No such file or directory

  Checking patch MSVC_Net2013/gdkmm.vcxproj.filters...

  error: MSVC_Net2013/gdkmm.vcxproj.filters: No such file or directory

  Checking patch MSVC_Net2013/gtkmm-build-defines.props...

  error: MSVC_Net2013/gtkmm-build-defines.props: No such file or directory

  Checking patch MSVC_Net2013/gtkmm-version-paths.props...

  error: MSVC_Net2013/gtkmm-version-paths.props: No such file or directory

  Checking patch MSVC_Net2013/gtkmm.vcxproj...

  error: MSVC_Net2013/gtkmm.vcxproj: No such file or directory

  Checking patch MSVC_Net2013/gtkmm.vcxproj.filters...

  error: MSVC_Net2013/gtkmm.vcxproj.filters: No such file or directory
```

2021-03-22 14:43 UTC, electron271 commented
Got all of this, going to change. This is my first pull request and couldn't find much docs of how to update a lib.

2021-03-22 14:45 UTC, electron271 commented on ports/gtkmm/portfile.cmake
>  vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
So replace this:
```
if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL WindowsStore)
    message(FATAL_ERROR "Error: UWP builds are currently not supported.")
endif()
```
with
```
vcpkg_fail_port_install(ON_TARGET "uwp")
```

2021-03-22 14:51 UTC, electron271 commented on ports/gtkmm/portfile.cmake
>  vcpkg_extract_source_archive_ex(
I think I did it

2021-03-22 14:51 UTC, electron271 commented on ports/gtkmm/portfile.cmake
>  vcpkg_extract_source_archive_ex(
Ok, changed.

2021-03-22 14:54 UTC, electron271 commented
How do I update the patch?

2021-03-23 15:26 UTC, electron271 commented
@NancyLi1013 How do I update the patch?

2021-03-24 03:06 UTC, NancyLi1013 commented
@electron271 

Please refer to this doc https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md

2021-03-24 15:34 UTC, electron271 commented
Ok, attempting patch right now.

2021-03-24 15:42 UTC, electron271 commented
So, one of the git commit commands in the patching.md didn't work, does this command also work?
![Uploading image.png…]()

2021-03-24 16:16 UTC, electron271 commented
Nope, having issues understanding how to update the patch.

2021-03-24 16:31 UTC, electron271 commented
Still having issues figuring out how to add the patch

2021-03-25 00:47 UTC, eszlari commented
Shouldn't this be a new port (gtkmm4)?

2021-03-25 01:43 UTC, electron271 commented
thats what the title was changed to so don't ask

2021-03-25 01:45 UTC, electron271 commented
as far as i know if that was true it would be named gtkmm3

2021-03-25 01:45 UTC, electron271 commented
not just gtkmm

2021-03-25 15:27 UTC, electron271 commented
going to reserve entire day to attempt to fix this so hopefully gtkmm 4.0.0 will be on vcpkg soon

2021-03-27 19:06 UTC, electron271 commented
🤔maybe?

2021-04-09 13:42 UTC, electron271 commented
This pr is a little outdated, so I'm closing it.

2021-04-09 13:42 UTC, closed without merging