[ryu] ryuConfig.cmake now adds the correct libraries when cross compiling
microsoft/vcpkg pull request #16858
Opened 2021-03-24 09:46 UTC by georg-emg

When using ryu in a cmake project, the correct library names are now used when cross compiling. Previously, ryuConfig.cmake checked the host system rather than the target system to decide whether to attempt to link with ryu.lib or libryu.a, which caused the wrong library names to be used when the host and target were different.

2021-03-24 20:18 UTC, ras0219-msft requested changes

2021-03-24 20:18 UTC, ras0219-msft commented on ports/ryu/ryuConfig.cmake
>  set_library_target("RYU" "ryu_printf" "${ROOT}/debug/lib/ryu_printf.lib" "${ROOT}/lib/ryu_printf.lib" "${ROOT}/include/")
```suggestion
if (TRUE)
find_library(RYU_RELEASE_LIB ryu PATHS "${ROOT}/lib" NO_DEFAULT_PATH)
find_library(RYU_DEBUG_LIB ryu PATHS "${ROOT}/debug/lib" NO_DEFAULT_PATH)
find_library(RYUPF_RELEASE_LIB ryu_printf PATHS "${ROOT}/lib" NO_DEFAULT_PATH)
find_library(RYUPF_DEBUG_LIB ryu_printf PATHS "${ROOT}/debug/lib" NO_DEFAULT_PATH)
set_library_target("RYU" "ryu" "${RYU_DEBUG_LIB} "${RYU_RELEASE_LIB}" "${ROOT}/include/")
set_library_target("RYU" "ryu_printf" "${RYUPF_DEBUG_LIB} "${RYUPF_RELEASE_LIB}" "${ROOT}/include/")
```

2021-03-24 20:18 UTC, ras0219-msft commented on ports/ryu/ryuConfig.cmake
>  set_library_target("RYU" "ryu_printf" "${ROOT}/debug/lib/ryu_printf.lib" "${ROOT}/lib/ryu_printf.lib" "${ROOT}/include/")
This should work across all platforms, including cross compilation.

2021-03-24 20:18 UTC, ras0219-msft commented
Thanks for the PR! This LGTM once my suggestion is applied

2021-03-25 08:19 UTC, georg-emg commented on ports/ryu/ryuConfig.cmake
>  set_library_target("RYU" "ryu_printf" "${ROOT}/debug/lib/ryu_printf.lib" "${ROOT}/lib/ryu_printf.lib" "${ROOT}/include/")
Just a quick question, out of curiosity: why `if(TRUE)`?

2021-03-25 08:32 UTC, JackBoosY approved these changes

2021-03-26 18:39 UTC, ras0219-msft commented on ports/ryu/ryuConfig.cmake
>  set_library_target("RYU" "ryu_printf" "${ROOT}/debug/lib/ryu_printf.lib" "${ROOT}/lib/ryu_printf.lib" "${ROOT}/include/")
I was just trying indicate that it should always be applied; it's not needed to have `if(TRUE)`.

2021-03-26 18:39 UTC, merged

2021-03-26 18:39 UTC, ras0219-msft commented
Thanks for the PR!