[llvm] add more features
microsoft/vcpkg pull request #16877
Opened 2021-03-25 10:36 UTC by abique

Adds missing features to LLVM

2021-03-25 14:55 UTC, yurybura commented
Related to #16232

2021-03-25 15:27 UTC, abique commented
They do not overlap through.

2021-03-25 16:51 UTC, abique commented
Yay, all the tests passed, this looks good to me.

2021-03-26 05:32 UTC, yurybura requested changes
Please check my comments below.

2021-03-26 05:36 UTC, yurybura commented on ports/llvm/portfile.cmake
> +if(LLVM_TOOLS)
LLVM_TOOLS will be removed in #16232.

2021-03-26 07:34 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-bindings
I think it does because if it is not mentioned it will be set to off.

2021-03-26 07:37 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
again same as above.
Did you miss that?
```cmake
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    tools LLVM_BUILD_TOOLS
    tools LLVM_INCLUDE_TOOLS
    utils LLVM_BUILD_UTILS
    utils LLVM_INCLUDE_UTILS
    enable-rtti LLVM_ENABLE_RTTI
    enable-ffi LLVM_ENABLE_FFI
    enable-terminfo LLVM_ENABLE_TERMINFO
    enable-threads LLVM_ENABLE_THREADS
    enable-eh LLVM_ENABLE_EH
    enable-bindings LLVM_ENABLE_BINDINGS
)
```

2021-03-26 07:38 UTC, abique commented on ports/llvm/portfile.cmake
> +if(LLVM_TOOLS)
Until that happens we need to check that the list is not empty before calling vcpkg_copy_tools.

2021-03-26 07:39 UTC, yurybura commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
Yes, feature enable-terminfo sets LLVM_ENABLE_TERMINFO=ON

2021-03-26 07:40 UTC, abique commented on ports/llvm/CONTROL
> +Description: Build LLVM with FFI.
Done.

2021-03-26 07:43 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-eh
Done, thank you.

2021-03-26 07:46 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
Just to make it clear it will set `LLVM_ENABLE_TERMINFO` to `OFF` if the feature `enable-terminfo` is not present. Which gives us direct control of `LLVM_ENABLE_TERMINFO` by using the feature.

2021-03-26 07:46 UTC, yurybura commented on ports/llvm/portfile.cmake
> +if(LLVM_TOOLS)
Yes, this is just for your information about overlap)

2021-03-26 07:53 UTC, abique commented
@yurybura Thank you very much for the review :+1:

2021-03-26 07:59 UTC, yurybura commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
You are right. This make sense if you want to disable it. In this case please add it to Default-Features.
Maybe you know, LLVM supports 3 states for this option: ON, OFF, FORCE_ON.

2021-03-26 08:03 UTC, yurybura commented on ports/llvm/CONTROL
> +Feature: enable-bindings
Ok, it makes sense. Please add it to Default-Features.

2021-03-26 08:08 UTC, yurybura commented on ports/llvm/CONTROL
> +Feature: enable-threads
I think this is wrong request from my side) Option is useful for disable threads. Please resolve. Thank you.

2021-03-26 08:27 UTC, abique commented on ports/llvm/portfile.cmake
> +if(LLVM_TOOLS)
OK

2021-03-26 08:29 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
According to https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_check_features.md if the feature is not set it sets it to false, at least this is my understanding of:
```
vcpkg_check_features() will:

    for each <feature-name> passed in FEATURES:
        if the feature is set, add -D<feature-var>=ON to <out-var>, and set <prefix>_<feature-var> to ON.
        if the feature is not set, add -D<feature-var>=OFF to <out-var>, and set <prefix>_<feature-var> to OFF.
    for each <feature-name> passed in INVERTED_FEATURES:
        if the feature is set, add -D<feature-var>=OFF to <out-var>, and set <prefix>_<feature-var> to OFF.
        if the feature is not set, add -D<feature-var>=ON to <out-var>, and set <prefix>_<feature-var> to ON.

```

2021-03-26 09:32 UTC, abique commented
It seems that the osgearth failure is unrelated right?

2021-03-26 09:42 UTC, Cheney-W commented
Yes, this is a CI issue, we are working on it.

2021-03-26 10:15 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
OK, I'll do that shortly.

2021-03-26 10:53 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-terminfo
Done

2021-03-26 10:56 UTC, abique commented on ports/llvm/CONTROL
> +Feature: enable-bindings
Done

2021-03-29 16:39 UTC, merged