[libsoundio] Add support for linux backends
microsoft/vcpkg pull request #16891
Opened 2021-03-25 22:10 UTC by joefocusrite

Adds features to build against optional backends (ALSA, JACK or PulseAudio).

2021-03-25 22:12 UTC, joefocusrite commented
Issue #16864

2021-03-26 13:54 UTC, PhoebeHui requested changes
Thanks for the PR!

2021-03-26 13:54 UTC, PhoebeHui commented on ports/libsoundio/portfile.cmake
> +endif()
Could you use [vcpkg_check_features](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_check_features.md) instead?

2021-03-26 13:54 UTC, PhoebeHui commented on ports/libsoundio/vcpkg.json
> +  "port-version": 1,
```suggestion
  "version": "2.0.0",
  "port-version": 4,
```

2021-03-26 17:37 UTC, JackBoosY commented
Waiting for #16904 merged.

2021-03-29 17:14 UTC, JackBoosY approved these changes

2021-03-29 17:14 UTC, JackBoosY commented
Need test all features.

2021-03-30 05:53 UTC, JackBoosY commented
Test passed on `x86-windows` / `x64-windows-static` / `x64-linux`.

2021-03-31 21:20 UTC, vicroms requested changes

2021-03-31 21:20 UTC, vicroms commented on versions/l-/libsoundio.json
> +    },
```suggestion
```
Please remove this entry to avoid duplicates with old version.

2021-04-02 20:25 UTC, merged

2021-04-02 20:25 UTC, ras0219-msft commented
Thanks for the improvements!