[libgpgp-error arm fixes
microsoft/vcpkg pull request #16932
Opened 2021-03-28 19:46 UTC by wrobelda

**Describe the pull request**

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2021-03-31 07:53 UTC, JonLiu1993 approved these changes

2021-04-02 21:16 UTC, ras0219-msft requested changes
Overall this looks really great, thanks for the PR!

LGTM once my suggestions are applied

2021-04-02 21:16 UTC, ras0219-msft commented on ports/libgpg-error/portfile.cmake
> +        REF 8dbb46c75850c6a2a215b1964dcca59ff6e34af6 #v1.41
```suggestion
        REF libgpg-error-${PACKAGE_VERSION}
```

2021-04-02 21:16 UTC, ras0219-msft commented on ports/libgpg-error/portfile.cmake
> +    vcpkg_from_github(
```suggestion
    message(WARNING "libgpg-error on Windows uses a fork managed by the ShiftMediaProject: https://shiftmediaproject.github.io/")
    vcpkg_from_github(
```

2021-04-02 21:16 UTC, ras0219-msft commented on ports/libgpg-error/portfile.cmake
> +
```suggestion
```

I don't see how this will do anything -- the project files don't have `${VCPKG_ROOT_DIR}` in them as far as I can see

2021-04-02 21:16 UTC, ras0219-msft commented on ports/libgpg-error/portfile.cmake
> +        TARGET Rebuild
```suggestion
```
This is the default

2021-04-02 21:54 UTC, wrobelda commented on ports/libgpg-error/portfile.cmake
> +        REF 8dbb46c75850c6a2a215b1964dcca59ff6e34af6 #v1.41
[libgpg-error] use git tag instead of sha

2021-04-04 22:45 UTC, wrobelda commented
@ras0219-msft I fixed the compilation issues I talked about on Slack. The libs build fine now, however, CI/CD _static_ build [fails](https://dev.azure.com/vcpkg/public/_build/results?buildId=51549&view=logs&jobId=837527cd-1f23-573f-4465-1412393a9ad5&j=837527cd-1f23-573f-4465-1412393a9ad5&t=5ebe51be-b0b9-5501-ce62-e5d2bdd3ba19), while not making much sense:

```
-- [COMMUNITY] Loading triplet configuration from: C:\a\1\s\triplets\community\x64-windows-static-md.cmake

(...)
-- Performing post-build validation
Expected Debug,**Dynamic** crt linkage, but the following libs had invalid crt linkage:
    D:/packages/libgpg-error_x64-windows-static-md/debug/lib/gpg-errord.lib: Debug,Static
Expected Release,**Dynamic** crt linkage, but the following libs had invalid crt linkage:
    D:/packages/libgpg-error_x64-windows-static-md/lib/gpg-error.lib: Release,Static
```

Surely something is off here with post-build validation?

2021-05-19 04:55 UTC, wrobelda commented
@JonLiu1993 all fixed now

2021-05-27 07:28 UTC, JonLiu1993 approved these changes

2021-05-27 07:29 UTC, JonLiu1993 commented
LGTM! Thanks for your contribution

2021-06-03 00:53 UTC, strega-nil-ms commented
Thanks @wrobelda :)

2021-06-03 00:53 UTC, merged