[ghc-filesystem] create a new port
microsoft/vcpkg pull request #16936
Opened 2021-03-29 07:55 UTC by luncliff

### What does your PR fix?

This is a rework of #15031.  
Targeting the latest release of https://github.com/gulrak/filesystem/releases/tag/v1.5.4

### Which triplets are supported/not supported? Have you updated the CI baseline?

The project is a header-only library, so every triplet must be available.

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes.

2021-03-30 02:15 UTC, NancyLi1013 requested changes

2021-03-30 02:15 UTC, NancyLi1013 commented on ports/ghc-filesystem/portfile.cmake
> +    REF v1.5.4
```suggestion
    REF v1.5.4
    HEAD_REF master
```

2021-03-30 02:15 UTC, NancyLi1013 commented on ports/ghc-filesystem/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/ghc_filesystem TARGET_PATH share/${PORT})
```suggestion
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/ghc_filesystem)
```
Since TARGET_PATH will default to `share/${PORT}`, it's unnecessary to add it here. Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_fixup_cmake_targets.md.

2021-03-30 02:51 UTC, luncliff commented
Thanks for suggestions, @NancyLi1013. 👍   
I'd like to check if the library works for old NDK versions, which doesn't support C++ `<filesystem>` . I will mark "Ready for review" after then.

2021-04-06 05:00 UTC, luncliff commented
I checked the library and works quite well. I'm gonna like this one :D

2021-04-16 07:41 UTC, NancyLi1013 requested changes

2021-04-16 07:41 UTC, NancyLi1013 commented on ports/ghc-filesystem/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/ghc_filesystem)
These function have deprecated. Could you please update these to the new ones?
```
vcpkg_cmake_configure()
vcpkg_cmake_install()
vcpkg_cmake_config_fixup()
```
We prefer to use suggested functions for new ports. Please also pay attention to the differences between deprecated functions and the new ones.

Note: if we use new functions, vcpkg-cmake and vcpkg-cmake-config are also required to be added in dependency lists like this:
```
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
```

2021-04-16 07:43 UTC, luncliff commented on ports/ghc-filesystem/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/ghc_filesystem)
Oh. The time came! Thanks for the check. I will update in this weekend.

2021-04-17 09:01 UTC, luncliff commented
Applied the feedback in 852d0bb. Wish it looks good to you, @NancyLi1013.

2021-04-19 09:21 UTC, NancyLi1013 approved these changes

2021-04-19 09:22 UTC, NancyLi1013 commented
LGTM now, thanks for your work @luncliff.

2021-04-20 00:21 UTC, merged

2021-04-20 00:22 UTC, strega-nil commented
great, thanks @luncliff :)