[libfido2] New port
microsoft/vcpkg pull request #16965
Opened 2021-03-30 12:45 UTC by xgcssch

This PR introduces libfido2 as a new port

- What does your PR fix?
-/-

- Which triplets are supported/not supported?
*-windows

- Have you updated the CI baseline?
no

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

2021-03-31 02:36 UTC, NancyLi1013 requested changes

2021-03-31 02:36 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +      "find_packages.patch"
```suggestion
    PATCHES
        "find_packages.patch"
```

2021-03-31 02:36 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +    )
```suggestion
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_EXAMPLES=OFF
        -DBUILD_MANPAGES=OFF
        -DBUILD_STATIC_LIBS=${LIBFIDO2_BUILD_STATIC}
        -DBUILD_SHARED_LIBS=${LIBFIDO2_BUILD_SHARED}
        -DBUILD_TOOLS=OFF
 )
```

2021-03-31 02:36 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +vcpkg_build_cmake()
```suggestion
```
This function is not needed here since it has been included in `vcpkg_install_cmake()`
.

2021-03-31 02:36 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +endif()
```suggestion
```
We can solve this problem via changing the destination path here.

https://github.com/Yubico/libfido2/blob/a36538af8ae99809acaf7d525833dbb431a0640c/src/CMakeLists.txt#L123
`RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})`

2021-03-31 02:36 UTC, NancyLi1013 commented on ports/libfido2/vcpkg.json
> +  "version-string": "1.6.0",
```suggestion
  "version": "1.6.0",
```
We prefer to use a proper package version to describe it. Please see https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#22-package-versions

2021-03-31 02:36 UTC, NancyLi1013 commented on ports/libfido2/find_packages.patch
> ++	include(FindPkgConfig)
Why do you add this line here?

2021-03-31 02:38 UTC, NancyLi1013 commented
Hi @xgcssch 

Thanks for your PR.

I also noticed that there was a new released version 1.7.0. So would you like to update it to the latest release in this PR?

2021-03-31 08:24 UTC, NancyLi1013 requested changes

2021-03-31 08:24 UTC, NancyLi1013 commented on ports/libfido2/vcpkg.json
> +  "version-string": "1.7.0",
```suggestion
  "version": "1.7.0",
```
It might be better to use `version `here. Please see https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#22-package-versions

2021-03-31 08:24 UTC, NancyLi1013 commented on versions/l-/libfido2.json
> +      "version-string": "1.7.0",
```suggestion
      "version": "1.7.0",
```
The same as above.

2021-03-31 08:24 UTC, NancyLi1013 commented on versions/l-/libfido2.json
> +    }
```suggestion
```
This part should not exist here.

2021-03-31 08:24 UTC, NancyLi1013 commented
Could you please also address the review suggestions?

2021-03-31 08:30 UTC, xgcssch commented
Hello Nancy!
Sorry for the checkin with only the 1.7 update. 
I haven't recognized the suggestions you made.
I am currently working on them.
Thanks

2021-04-01 07:50 UTC, NancyLi1013 requested changes

2021-04-01 07:50 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
```suggestion
```
This line seems to be unnecessary.

2021-04-01 10:47 UTC, xgcssch commented on ports/libfido2/portfile.cmake
> +    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
Sorry, some remains of testing ...
Removed!

2021-04-13 09:13 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +vcpkg_configure_cmake(
This function has deprecated in favor of `vcpkg_cmake_configure`. Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md

So would you like you update it as the new function here? We prefer to use the new one for a new port.

Note: `PREFER_NINJA` is no longer needed to pass in new function.

2021-04-13 09:14 UTC, NancyLi1013 commented on ports/libfido2/portfile.cmake
> +vcpkg_install_cmake()
```suggestion
vcpkg_cmake_install()
```
The same as above.

2021-04-13 09:15 UTC, NancyLi1013 requested changes

2021-04-13 09:15 UTC, NancyLi1013 commented on ports/libfido2/vcpkg.json
> +    "zlib"
`vcpkg-cmake` is also needed here if we use new functions.

2021-04-13 16:12 UTC, xgcssch commented
Hi Nancy!
I applied the suggested changes.
I've no idea, why the osx check is failing.
Best regards 
Sönke

2021-04-14 02:04 UTC, NancyLi1013 requested changes

2021-04-14 02:04 UTC, NancyLi1013 commented on ports/libfido2/vcpkg.json
> +    "vcpkg-cmake",
```suggestion
   {
     "name": "vcpkg-cmake",
     "host": true
   }
```
We should add the dependency like this. Please use `./vcpkg format-manifest ./ports/libfido2/vcpkg.json` to format this file.

2021-04-14 02:06 UTC, NancyLi1013 commented
> Hi Nancy!
> I applied the suggested changes.
> I've no idea, why the osx check is failing.
> Best regards
> Sönke

The failures on osx pipeline are not related with this PR, it due to disk space ran out. I will rerun this PR once solved.

2021-04-14 08:57 UTC, xgcssch commented
Done!
The failing Tests are from a different package. Interesting.

2021-04-14 10:11 UTC, NancyLi1013 approved these changes

2021-04-14 10:13 UTC, NancyLi1013 commented
The failures cause by `popsift ` will be fixed by #17277.

2021-04-15 01:50 UTC, NancyLi1013 commented
/azp run

2021-04-15 01:56 UTC, NancyLi1013 commented
LGTM now, thanks for adding this port @xgcssch.

2021-04-30 18:34 UTC, strega-nil-ms commented
@xgcssch could you rebase on latest? thanks!

2021-05-01 12:19 UTC, xgcssch commented
Done!

2021-05-07 00:41 UTC, merged

2021-05-07 00:41 UTC, BillyONeal commented
Thanks for your contribution!