add clags in tools build command
microsoft/vcpkg pull request #17019
Opened 2021-04-01 15:40 UTC by xandox

add clags in tools build command

- What does your PR fix? Fixes # fixes needs for PR #15605 

- Which triplets are supported/not supported? same
- Have you updated the CI baseline? no

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes

2021-04-02 02:37 UTC, NancyLi1013 approved these changes

2021-04-09 17:04 UTC, vicroms commented
@xandox please pull the latest commit and run `vcpkg x-add-version` again

2021-04-14 02:17 UTC, NancyLi1013 commented
Seems you missed the changes in `ports/fontconfig/CONTROL ` file.

Could you please add it back? @xandox

2021-04-21 01:34 UTC, NancyLi1013 approved these changes

2021-04-22 02:20 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @xandox.

2021-04-23 18:41 UTC, ras0219-msft requested changes

2021-04-23 18:41 UTC, ras0219-msft commented on versions/f-/fontconfig.json
> +      "git-tree": "d9774e3ba72153356e6ba148678304283053feda",
```suggestion
      "git-tree": "de83a21d912d9b87d8ad069d94dffcca201830a3",
```
Previous versions must not be modified.

2021-04-30 18:32 UTC, strega-nil-ms commented
@xandox could you rebase on head? thanks!

2021-05-05 09:06 UTC, xandox commented
up

2021-05-05 20:31 UTC, merged

2021-05-05 20:31 UTC, strega-nil-ms commented
Thanks @xandox!