Libspatialite remove cflags from vcpkg_configure_make options
microsoft/vcpkg pull request #17024
Opened 2021-04-01 16:30 UTC by xandox

Libspatialite remove cflags from vcpkg_configure_make options
This flag do not mentioned in sources 

- What does your PR fix? Fixes for PR #15605

- Which triplets are supported/not supported? same
- Have you updated the CI baseline? no

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes

2021-04-02 04:13 UTC, JackBoosY requested changes

2021-04-02 04:13 UTC, JackBoosY commented on ports/libspatialite/portfile.cmake
> -          "CFLAGS=-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H"
Any reason to remove this here?

2021-04-02 05:00 UTC, xandox commented on ports/libspatialite/portfile.cmake
> -          "CFLAGS=-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H"
This cflag option completely overwrite any cflag set by vcpkg_configure_make. Probably there should be some merge algorithm for system cflags and cflags from options, but it does not exists yet. This line does not affect at anything with current scripts but breakes new ones.

2021-04-02 08:00 UTC, JackBoosY commented on ports/libspatialite/portfile.cmake
> -          "CFLAGS=-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H"
I think we should add `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H` to compile options, can you patch it?

2021-04-03 16:57 UTC, rhuijben commented
The flag is no longer needed with current libspatialite versions that support newer proj versions. And once proj is bumped to 8.0 this will even cause an error, so +1 on removing the define.

2021-04-03 16:58 UTC, rhuijben commented
The flag used to enable the legacy api in the proj headers

2021-04-05 04:37 UTC, JackBoosY approved these changes

2021-04-07 20:03 UTC, merged