[cpuinfo] update port to latest
microsoft/vcpkg pull request #17063
Opened 2021-04-03 16:06 UTC by luncliff

### What does your PR fix?

* Update `cpuinfo` to use the latest source code.
    * Use different log level for debug build.
    * Embed a patch that works like `cpuinfo-pull-22-868bd11.patch`
* Change `CONTROL` to `vcpkg.json`.

The previous patch `cpuinfo-pull-22-868bd11.patch`, which is from https://github.com/pytorch/cpuinfo/pull/22 failed to apply.

```
Starting package 1/1: cpuinfo:x64-osx
Building package cpuinfo[core]:x64-osx...
-- Using cached /Users/user/vcpkg/downloads/cpuinfo-pull-22-868bd11.patch
-- Using cached /Users/user/vcpkg/downloads/pytorch-cpuinfo-5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz
-- Extracting source /Users/user/vcpkg/downloads/pytorch-cpuinfo-5916273f79a21551890fd3d56fc5375a78d1598d.tar.gz
-- Applying patch /Users/user/vcpkg/downloads/cpuinfo-pull-22-868bd11.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:57 (message):
  Applying patch failed: Checking patch CMakeLists.txt...

  error: while searching for:

  OPTION(CPUINFO_BUILD_MOCK_TESTS "Build cpuinfo mock tests" ON)

  OPTION(CPUINFO_BUILD_BENCHMARKS "Build cpuinfo micro-benchmarks" ON)

  

  # ---[ CMake options

  IF(CPUINFO_BUILD_UNIT_TESTS OR CPUINFO_BUILD_MOCK_TESTS)

    ENABLE_TESTING()

  

  error: patch failed: CMakeLists.txt:17

  error: CMakeLists.txt: patch does not apply

  Checking patch cmake/Config.cmake.in...

  Checking patch deps/clog/CMakeLists.txt...

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:144 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:154 (vcpkg_extract_source_archive_ex)
  ports/cpuinfo/portfile.cmake:11 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)

```

Picked those differences and created a new patch file.
What a sad that PR is not merged yet ... 

### Which triplets are supported/not supported? Have you updated the CI baseline?

No change in triplet support. The current build check must be passed. 

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I think so.

2021-04-07 08:08 UTC, JackBoosY requested changes
Since this is no the upstream changes, we should add prefix `unofficial-`.

2021-04-07 08:08 UTC, JackBoosY commented on ports/cpuinfo/fix-install.patch
> ++set(targets_export_name "${PROJECT_NAME}Targets")
```suggestion
+set(targets_export_name "unofficial-${PROJECT_NAME}Targets")
```

2021-04-07 08:08 UTC, JackBoosY commented on ports/cpuinfo/fix-install.patch
> ++set(project_config "${generated_dir}/${PROJECT_NAME}Config.cmake")
```suggestion
+set(project_config "${generated_dir}/unofficial-${PROJECT_NAME}Config.cmake")
```

2021-04-07 08:08 UTC, JackBoosY commented on ports/cpuinfo/portfile.cmake
>  vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/${PORT})
```suggestion
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/unofficial-${PORT} TARGET_PATH unofficial-${PORT})
```

2021-04-07 08:08 UTC, JackBoosY commented on ports/cpuinfo/fix-install.patch
> ++set(config_install_dir "lib/cmake/${PROJECT_NAME}")
```suggestion
+set(config_install_dir "lib/cmake/unofficial-${PROJECT_NAME}")
```

2021-04-07 11:17 UTC, luncliff commented
Cool. There are some ports I worked to use this, but let me fix them after this

2021-04-07 12:09 UTC, JackBoosY commented
I think you should remake the patch file.

2021-04-10 09:51 UTC, luncliff commented
Merged `master` to resolve failures of #16346 #16344

2021-04-11 09:33 UTC, JackBoosY approved these changes

2021-04-30 18:29 UTC, strega-nil-ms commented
I think that that's incorrect; they're just corrections of upstream targets, so they should be under the upstream name, not `unofficial-`; @JackBoosY do you disagree?

2021-05-02 12:41 UTC, JackBoosY commented
@strega-nil-ms The upstream doesn't export any targets in the master branch, did I miss something?

2021-05-05 20:37 UTC, strega-nil-ms commented
@JackBoosY oh... yeah you're right, I totally misread that, you're right.

2021-05-05 20:37 UTC, merged

2021-05-05 20:38 UTC, strega-nil-ms commented
Thanks @luncliff :)