[qnnpack] create a new port
microsoft/vcpkg pull request #17065
Opened 2021-04-03 16:24 UTC by luncliff

### What does your PR fix?

There was no port request for this project.

This is one of the 3rd party libraries for [the PyTorch project](https://github.com/pytorch/pytorch/blob/master/.gitmodules). The PR will be used for future support of the `libtorch` port.

#### Related Works

* `nnpack` #16344: has same dependencies
* `xnnpack` #17064: has same dependencies

### Which triplets are supported/not supported? Have you updated the CI baseline?

Need more check. Targets general desktop triplets. 

* [x] `x64-osx`
* [ ] `x64-windows`
* [ ] `x64-linux`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes.

2021-04-06 10:00 UTC, PhoebeHui requested changes
@luncliff, thanks for the PR!

2021-04-06 10:13 UTC, luncliff commented on ports/qnnpack/portfile.cmake
> +vcpkg_install_cmake()
Thanks @PhoebeHui . Do I have to apply `vcpkg_cmake_configure` either?

2021-04-06 10:20 UTC, luncliff commented on ports/qnnpack/portfile.cmake
> +vcpkg_install_cmake()
I just tried the change and got the command is unknown. Let me check with `vcpkg-cmake`... hmm...

2021-04-07 02:44 UTC, PhoebeHui requested changes
@luncliff, you need add vcpkg-cmake to dependency.

You can reference similar PR https://github.com/microsoft/vcpkg/pull/17101

2021-04-07 02:44 UTC, PhoebeHui commented on ports/qnnpack/portfile.cmake
> +vcpkg_configure_cmake(
```suggestion
vcpkg_cmake_configure(
```

2021-04-07 02:44 UTC, PhoebeHui commented on ports/qnnpack/portfile.cmake
> +vcpkg_install_cmake()
```suggestion
vcpkg_cmake_install()
```

2021-04-10 08:47 UTC, luncliff commented on ports/qnnpack/portfile.cmake
> +vcpkg_install_cmake()
OK. applied in 75e1f36

2021-04-10 08:49 UTC, luncliff commented
Applied `vcpkg-cmake` in 75e1f3608181c388900420dba6187202dc64eef6. But #17063 may break this port.  
I will take care of it if this PR is merged first.

2021-04-12 01:20 UTC, PhoebeHui commented
We should rerun this PR after PR https://github.com/microsoft/vcpkg/pull/17063 merged.

2021-04-12 01:21 UTC, PhoebeHui approved these changes

2021-05-06 07:14 UTC, PhoebeHui approved these changes
LGTM, thanks for your contribution!

2021-05-07 00:44 UTC, merged

2021-05-07 00:44 UTC, BillyONeal commented
Thanks for your contribution!