[xnnpack] create a new port
microsoft/vcpkg pull request #17064
Opened 2021-04-03 16:17 UTC by luncliff

### What does your PR fix?

There was no port request for this project. The PR requires #17063.

This is one of the 3rd party libraries for [the PyTorch project](https://github.com/pytorch/pytorch/blob/master/.gitmodules). The PR will be used for future support of the `libtorch` port.

#### Related Works

* `nnpack` #16344: has same dependencies

### Which triplets are supported/not supported? Have you updated the CI baseline?

Need more check. Targets general desktop triplets. 

* [x] `x64-osx`
* [ ] `x64-windows`
* [ ] `x64-linux`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

* The library doesn't have a tag/release. Used `version-date`.
* Will be rebased after merge of #17063

2021-04-03 17:16 UTC, luncliff commented
#### Note for the failure in Windows 
Requires `pthreadpool.lib`. It would be better if the port `pthreadpool` can support `find_package`.

2021-04-10 15:33 UTC, luncliff commented
### Linux 
* https://github.com/google/XNNPACK/pull/1391 fixed the SIMD errors. changing code snapshot to `2021-04-10`

2021-04-10 16:27 UTC, luncliff commented
This PR will be rebased after #17063 and  #17196 are merged.

2021-05-07 00:45 UTC, BillyONeal approved these changes

2021-05-07 06:10 UTC, NancyLi1013 requested changes

2021-05-07 06:10 UTC, NancyLi1013 commented on ports/xnnpack/portfile.cmake
> +    PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
```
We prefer to use `vcpkg_cmake_configure` for new ports instead of the deprecated one. Could you please update this?

2021-05-07 06:10 UTC, NancyLi1013 commented on ports/xnnpack/portfile.cmake
> +vcpkg_install_cmake()
```suggestion
vcpkg_cmake_install()
```
The same as above.

2021-05-07 06:10 UTC, NancyLi1013 commented on ports/xnnpack/portfile.cmake
> +vcpkg_fixup_cmake_targets()
```suggestion
vcpkg_cmake_config_fixup()
```
The same as above.

2021-05-07 06:10 UTC, NancyLi1013 commented on ports/xnnpack/vcpkg.json
> +}
If using the new functions, these ports should be added to the dependency lists.
```
   {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
```

2021-05-18 02:08 UTC, NancyLi1013 approved these changes

2021-05-18 06:22 UTC, merged