[mpg123] Upgrade to 1.26.4
microsoft/vcpkg pull request #17074
Opened 2021-04-04 04:22 UTC by evpobr

Add next version In continuation of the pull request #16910.

2021-04-06 06:26 UTC, JonLiu1993 commented on versions/m-/mpg123.json
> +    },
@evpobr ，Please delete this duplicate "version", each version corresponds to only one git-tree.

2021-04-06 06:42 UTC, JonLiu1993 requested changes
Please add the .PC file processing function vcpkg_fixup_pkgconfig() under vcpkg_install_make() in portifle.cmake

2021-04-06 07:37 UTC, JonLiu1993 commented
@evpobr ,After you have modified everything, you should run the ./vcpkg x-add-version forge --overwrite-version command and then submit it again

2021-04-06 08:21 UTC, evpobr commented
@JonLiu1993 , thanks, i know. I did everything I could without installing Vcpkg, which is impossible on this computer. I'll finish this pull request later tonight.

2021-04-07 01:21 UTC, JonLiu1993 approved these changes

2021-04-07 19:47 UTC, vicroms requested changes

2021-04-07 19:47 UTC, vicroms commented on ports/mpg123/vcpkg.json
> +  "version-string": "1.26.4",
Maybe change this to [`version` or `version-semver`](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md).

2021-04-08 14:54 UTC, evpobr commented on ports/mpg123/vcpkg.json
> +  "version-string": "1.26.4",
I guess it could be "version".

2021-04-08 18:57 UTC, merged