[PCL] add a way to disable SSE
microsoft/vcpkg pull request #17156
Opened 2021-04-08 15:32 UTC by fran6co

PCL adds `-march=native` and other flags to the whole project making it harder to make binaries that work across different instruction sets. This PR add a feature flag to be able to disable SSE optimizations

2021-04-09 05:58 UTC, NancyLi1013 requested changes
Could you please also update Port-Version in CONTROL file?

2021-04-09 05:58 UTC, NancyLi1013 commented on ports/pcl/portfile.cmake
> +endif()
You can add this feature in `vcpkg_check_features()` feature lists. This feature should be added to `INVERTED_FEATURES`.

Please also add keyword `FEATURES` to these current features to solve deprecated warnings. See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_check_features.md

2021-04-09 06:01 UTC, NancyLi1013 commented
Hi @fran6co 

Thanks for your PR.

Please run `vcpkg x-add-version pcl` to solve the failures on x86-windows.
```
Error: While reading versions for port pcl from file: C:\a\1\s\versions\p-\pcl.json
       File declares version `1.11.1#2` with SHA: 965ac7e810b04459a8060a73273f924cf8d7f317
       But local port with the same verion has a different SHA: 7efe6bc9f411b5669ec8ae76407a1250318f3772
       Please update the port's version fields and then run:

           vcpkg x-add-version pcl

       to add a new version.
```

Note: Please run the command after you submitted the changes.

2021-04-09 08:10 UTC, ytbigvinny27 approved these changes

2021-04-09 09:28 UTC, NancyLi1013 requested changes

2021-04-09 09:28 UTC, NancyLi1013 commented on ports/pcl/CONTROL
> +
Please update `Port-Version: 2` as `Port-Version: 3`.

2021-04-09 10:32 UTC, NancyLi1013 commented
```
Error: While reading versions for port pcl from file: C:\a\1\s\versions\p-\pcl.json
       File declares version `1.11.1#3` with SHA: 0e13d4046052222f0135999a05aa72875d2647a4
       But local port with the same verion has a different SHA: b4a8098db5f2ca93a22cc1bfd94d2fe32ca9f539
       Please update the port's version fields and then run:

           vcpkg x-add-version pcl

       to add a new version.
```
Please run `vcpkg x-add-version --overwrite-version pcl` to solve the failures on x86-windows.

2021-04-09 17:31 UTC, ytbigvinny27 approved these changes

2021-04-12 02:05 UTC, NancyLi1013 approved these changes

2021-04-12 02:06 UTC, NancyLi1013 commented
Hi @fran6co 

Have you tested this new feature `disable-sse`?

2021-04-12 06:02 UTC, fran6co commented
Yes, I need it for the project i’m working on right now.

On Mon, 12 Apr 2021 at 04:06, NancyLi1013 ***@***.***> wrote:

> Hi @fran6co <https://github.com/fran6co>
>
> Have you tested this new feature disable-sse?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/17156#issuecomment-817430428>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFRISH6GLJZMMA57DH2PJLTIJIS7ANCNFSM42TEIKMQ>
> .
>

2021-04-13 05:53 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @fran6co.

2021-04-30 18:23 UTC, strega-nil-ms commented
I am concerned about this PR. I don't think this is the right way forward; features should be additive, and should not be used to disable features. This should likely be done with triplets instead... cc @ras0219, could you comment?

2021-05-07 00:48 UTC, BillyONeal commented
Dropping "status:reviewed" as there are outstanding comments.

2021-07-20 08:43 UTC, NancyLi1013 commented
@fran6co Is work still being done for this Pr?

2021-07-20 09:14 UTC, fran6co commented
@NancyLi1013 there is no more work needed on this PR save for fixing the conflicts

2021-07-20 09:37 UTC, NancyLi1013 commented
Thanks for your response. Please resolve the conflicts later.

2021-07-20 18:55 UTC, BillyONeal commented
I believe the problem is that we are still uncomfortable with this being controlled with the feature mechanism and would want to see this driven through triplets. It is a setting that needs to be consistent for the universe, not only for pcl.

2021-07-31 09:26 UTC, fran6co commented
Not sure how to do this with triplets, I'll close the PR for now then

2021-07-31 09:26 UTC, closed without merging