Add subversion and serf ports
microsoft/vcpkg pull request #17186
Opened 2021-04-09 16:09 UTC by rhuijben

Adds support for building the subversion client libraries.

Do this by adding Apache Serf and Apache Subversion ports.

The ports should work on:
* x86-windows
* x64-windows
* x86-windows-static-md
* x64-windows-static-md

The patches applied for Subversion are already in the base Subversion repository, but will most likely only be included in the next feature release (=1.x release).

2021-04-09 17:11 UTC, Neumann-A commented on ports/serf/portfile.cmake
> +)
`vcpkg_find_acquire_program(SCONS)` ?

2021-04-09 17:12 UTC, Neumann-A commented on ports/serf/portfile.cmake
> +)
this needs to setup build flags from the cmake toolchain

2021-04-09 17:14 UTC, Neumann-A commented on ports/subversion/portfile.cmake
> +endif()
this is wrong for custom triplets. probably requires #17029 @ras0219-msft

2021-04-09 18:17 UTC, rhuijben commented on ports/subversion/portfile.cmake
> +endif()
Subversion has its own buildfile generator. This produces proper msbuild files, and the settings are then overloaded bij the vcproj msbuild runner.

2021-04-09 18:19 UTC, rhuijben commented on ports/serf/portfile.cmake
> +)
Don't think that will work yet. Couldn't find a single reference to scons in the build tree.

This works for the current serf version, and the next one (if ever released as stable) switches to cmake.

2021-04-09 18:45 UTC, Neumann-A commented on ports/subversion/portfile.cmake
> +endif()
You are assuming here that `VCPKG_LIBRARY_LINKAGE` is constant for all ports and thus setting 
 `--with-shared-serf`
or
`--with-static-apr --with-static-openssl`
without knowing if serf, apr or openssl have really been built with the same `VCPKG_LIBRARY_LINKAGE`. Please read the vcpkg docs about per port customization (https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization).

2021-04-09 21:16 UTC, Neumann-A commented on ports/serf/portfile.cmake
> +)
https://github.com/microsoft/vcpkg/blob/fe112d8301e13fde9a25dc92d94a0c4a6dc3cf19/scripts/cmake/vcpkg_find_acquire_program.cmake#L355-L363

https://github.com/microsoft/vcpkg/blob/fe112d8301e13fde9a25dc92d94a0c4a6dc3cf19/scripts/cmake/vcpkg_find_acquire_program.cmake#L15-L39

2021-04-09 21:45 UTC, rhuijben commented on ports/subversion/portfile.cmake
> +endif()
This does only change the name of the .lib linked against, as generated in the .vcxproj files later build with msbuild... It doesn't build apr itself, not any of these other dependencies.

But I do want apr-1.lib (static);vs libapr-1.lib (shared) to be correct.

Note I maintained quite a bit of the Windows specific scripting on the Subversion side over the last decade and a half. You should really check the code there before blocking a patch for the wrong reasons.

The resulting binaries through these patches have been tested by the Subversion project.

But Subversion and most of its ASF dependencies don't have a native static+static crt build, so this specific scenario needs separate patches.

2021-04-09 22:10 UTC, Neumann-A commented on ports/subversion/portfile.cmake
> +endif()
> But I do want apr-1.lib (static);vs libapr-1.lib (shared) to be correct.

Consider the triplet:
```
set(VCPKG_LIBRARY_LINKAGE dynamic)
if(PORT MATCHES "apr")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```

how does it affect the build? Is the portfile correct in this case? Can it still find the library?

> Note I maintained quite a bit of the Windows specific scripting on the Subversion side over the last decade and a half. You should really check the code there before blocking a patch for the wrong reasons.

Don't care about that. I just care about correctness and none of your "reasons". `VCPKG_LIBRARY_LINKAGE` is a per port value and can be different on a per port basis. So consider answering my concerns instead of trying to use your "position" to convince me. 

Furthermore I am not blocking, I am just trying to get something like #17029 into vcpkg because it is sometimes needed/required by ports how dependent ports are build.

2021-04-10 13:18 UTC, rhuijben commented on ports/serf/portfile.cmake
> +)
Thanks... I found it and tried it... and determined that it doesn't work. 

This version of scons is incompatible with Visual Studio 2019 without further patches.

I think this should be updated as a separate patch. (Might need more work as just bumping versions and download references didn't work either).

For now I'm trying to get my existing legacy NAnt scripting converted to VCPkg to enable the use of github workflows for a few depending projects.

2021-04-10 13:19 UTC, rhuijben commented on ports/serf/portfile.cmake
> +)
Would be nice, yes... But I don't think APR and anything below it really supports anything but 100% Shared libraries, or 100% static. APR is like the CRT for the projects depending on it. You can't mix memory management.

2021-04-16 19:16 UTC, rhuijben commented
@JackBoosY Why did you add the requires author response? I don't see new open questions. What am I missing?

2021-04-18 03:03 UTC, JackBoosY commented
@rhuijben Neumann have some unsolved questions.

2021-04-18 07:39 UTC, rhuijben commented
> @rhuijben Neumann have some unsolved questions.

Most of these would require new vcpkg features to fix.. other packages to forward info that they currently don't do... While these ports would already help users in this form.

I don't think we would like completely custom cmake scripts for every project in vcpkg that just ignore the intended builds from the projects providing the source code.

2021-04-20 09:22 UTC, JackBoosY commented on ports/subversion/portfile.cmake
> +endif()
I think what Neumann said is reasonable, this will pass our official triad, but not unofficially.

2021-04-30 12:59 UTC, rhuijben commented on ports/subversion/portfile.cmake
> +endif()
@JackBoosY This will ask changes to at least quite a few dependencies before leaf ports can use this. Libraries like apr don't support al these scenarios as they provide memory management to their dependencies and you can't just mix CRT versions like that or things will break in the most unexpected locations.

Serf and Subversion depend on the apr memory management for their internals, so I have no idea how vcpkg will just fix this for everyone to mix everywhere, without patching out all of these products and many similar. You can't allocate ram using the malloc of one static CRT and then release it with a shared CRT or a different static CRT.

Not sure why we should delay adding new ports for this.

2021-05-03 06:18 UTC, JackBoosY commented
/azp run

2021-05-07 08:55 UTC, JackBoosY requested changes

2021-05-07 08:55 UTC, JackBoosY commented on ports/serf/portfile.cmake
> +endif()
```suggestion
vcpkg_fail_port_install(ON_TARGET "UWP")
```

2021-05-07 08:55 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +serf:x64-osx=fail
Is this unsupport by the upstream or temporary unsupport in vcpkg?

2021-05-07 08:55 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +subversion:x64-linux=fail
Same as above.

2021-05-07 08:55 UTC, JackBoosY commented on ports/subversion/portfile.cmake
> +endif()
@BillyONeal what do you think about this?

2021-05-10 08:06 UTC, rhuijben commented on scripts/ci.baseline.txt
> +serf:x64-osx=fail
For now unsupported in vcpkg. It is supported but uses a different buildsystem on these platforms. 

These Subversion packages are +- in the base system on these platforms, while they are generally hard to build on Windows. I'm trying to switch my personal build for these package to vcpkg... Maintain the patches there instead of in a separate scripted legacy buildsystem.

Getting serf to build properly most likely just requires passing a few paths in another style.
Subversion requires using a different generator and other ways to find the packages. 
Subversion uses autoconf on linux and os/x, while it mostly assumes passing all paths manually on Windows.

2021-05-10 08:07 UTC, rhuijben commented on scripts/ci.baseline.txt
> +subversion:x64-linux=fail
See answer above. Should work, but much easier to fix on a linux or mac/os system than on my windows box.

2021-05-10 08:09 UTC, rhuijben commented on ports/serf/portfile.cmake
> +endif()
Thanks. Committed this fix. Not sure if this is completely necessary, as APR (required dependency) doesn't work on UWP yet.

2021-05-10 09:51 UTC, rhuijben commented
@JackBoosY Fixed the serf build for x64-linux with the last version of the patch. I assume this fixes os/x as well.

2021-05-11 03:09 UTC, JackBoosY commented
I would like my colleague will review the PR further.

2021-05-15 11:14 UTC, rhuijben commented on ports/subversion/portfile.cmake
> +endif()
As far as I can tell only the Sqlite dependency currently publishes its library name. All the other dependencies don't. 
Are we now asking all libraries to start publishing their dependencies in pkg-config *or* cmake config, or?

I don't think we should delay individual packages included in this repository until everything else is converted...?

perhaps it would be easier to ask dependencies to use constant names (would just require patches to libexpat, apr and apr-util).

I don't think any of these dependencies can just fix the mixing of memory models as noted earlier. So these new configs would be broken at runtime anyway if they started using mixed crt configs.

2021-07-26 23:40 UTC, vicroms commented
We'll review this in our Thursday meeting.

2021-08-23 11:28 UTC, rhuijben commented
@vicroms Any news?

2021-09-10 07:03 UTC, JackBoosY commented
Sorry for late, we will discuss this PR at the meeting next week.

2021-09-14 07:39 UTC, JackBoosY commented
Ping @vicroms @BillyONeal for response.

2021-09-16 17:37 UTC, BillyONeal commented on ports/subversion/portfile.cmake
> +endif()
>Are we now asking all libraries to start publishing their dependencies in pkg-config or cmake config, or?

It isn't "all libraries need to use pkgconfig", it is "if we have a library that needs something normally provided by pkgconfig, we should patch the source to produce pkgconfig rather than patching every consumer".

2021-09-23 18:32 UTC, BillyONeal commented on ports/subversion/portfile.cmake
> +endif()
It looks like most of the dependencies do publish pkgconfig and there is an autoconf build system, have you considered using that @rhuijben ?

2021-09-23 18:33 UTC, BillyONeal commented on ports/subversion/portfile.cmake
> +        --with-apr=${CURRENT_INSTALLED_DIR}
It seems unlikely that these are going to correctly find the debug libraries in debug builds?

2021-11-03 11:22 UTC, rhuijben commented on ports/subversion/portfile.cmake
> +        --with-apr=${CURRENT_INSTALLED_DIR}
There is magic in the python code to find both debug and release libraries. This goes through a lot of steps to generate .vcxproj files with all the right references for both debug and release builds.

The separate patches fix this version of Subversion to find them directly... And the same patches are already in Subversion trunk so should be available with the next minor release of Subversion (if not earlier)

2022-01-06 16:47 UTC, JackBoosY commented
Can you please merge to master?

2022-01-13 18:01 UTC, JackBoosY commented
Can you handle the osx failure? See logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=65506&view=artifacts&pathAsName=false&type=publishedArtifacts).

2022-01-26 03:52 UTC, JackBoosY commented
Oh that's a disaster, you wrongly merged the commits.

2022-03-18 06:12 UTC, JackBoosY commented
Convert this PR to draft since there is no progress in a long time.

2022-05-07 05:56 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2022-05-07 05:56 UTC, closed without merging