[pthreadpool] update sources and support find_package
microsoft/vcpkg pull request #17196
Opened 2021-04-10 11:49 UTC by luncliff

### What does your PR fix?

* update to latest source
   * There was an update for `arm64-osx`. https://github.com/Maratyszcza/pthreadpool/pull/14
* `xnnpack` #17064 needs support to find `pthreads` and `pthreadpool` artifacts easily.

#### Support find_package

Export 2 targets. `pthreadpool_interface`(INTERFACE) and `pthreadpool`(IMPORTED)
```
    find_package(pthreadpool CONFIG REQUIRED)
    target_link_libraries(main PRIVATE pthreadpool pthreadpool_interface)
```

### Which triplets are supported/not supported? Have you updated the CI baseline?

* With #16348, `windows & uwp` triplets should become available
* `arm64-osx`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes. Wish the port works well.

2021-04-12 02:51 UTC, JackBoosY requested changes
Since the changes is unofficial, please set the target name to `unofficial-${TARGET}`.

2021-04-14 10:05 UTC, luncliff commented
OK. with ebf60e3174df240eda7e45f6d0885df662b21e76, the export should be like the following.

```
    find_package(unofficial-pthreadpool CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::pthreadpool unofficial::pthreadpool_interface)
```

2021-04-15 02:26 UTC, JackBoosY approved these changes

2021-04-30 18:14 UTC, merged

2021-04-30 18:14 UTC, strega-nil-ms commented
Awesome, thanks @luncliff :)

2021-05-02 12:03 UTC, luncliff commented on ports/pthreadpool/vcpkg.json
> +      "platform": "windows & uwp"
My god. Seems like this part should be `windows | uwp`, not `windows & uwp`....

2021-05-02 12:09 UTC, luncliff commented on ports/pthreadpool/vcpkg.json
> +      "platform": "windows & uwp"
I checked the source file and the implementation redirects to Win32 API. The dependency should be removed.

2021-05-02 13:11 UTC, JackBoosY commented on ports/pthreadpool/vcpkg.json
> +      "platform": "windows & uwp"
Can you please make a new PR to fix that?

Thanks.

2021-05-02 13:12 UTC, luncliff commented
Yeah. I will make it tomorrow.

On Sun, May 2, 2021, 10:11 PM Jack·Boos·Yu ***@***.***> wrote:

> *@JackBoosY* commented on this pull request.
> ------------------------------
>
> In ports/pthreadpool/vcpkg.json
> <https://github.com/microsoft/vcpkg/pull/17196#discussion_r624692802>:
>
> >    "dependencies": [
>      "fxdiv",
>      {
>        "name": "pthreads",
> -      "platform": "uwp"
> +      "platform": "windows & uwp"
>
> Can you please make a new PR to fix that?
>
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/17196#discussion_r624692802>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLSYEZD7IV6SFW4S2ZCVI3TLVFRTANCNFSM42WNZAWA>
> .
>