[doc] Improve manifest documentation links
microsoft/vcpkg pull request #17214
Opened 2021-04-11 10:34 UTC by dg0yt

This PR fixes a broken documentation link, and it improves the TOC on the front page.

I got lost in the documentation a few times. Maybe this needs even more explicit language, e.g. "user manifest files" and "port manifest files".

2021-04-12 10:18 UTC, NancyLi1013 requested changes

2021-04-12 10:18 UTC, NancyLi1013 commented on docs/maintainers/control-files.md
> +all new features are added only to [vcpkg.json manifest files](manifest-files.md), and we recommend using vcpkg.json for any newly authored port.**
```suggestion
all new features are added only to [vcpkg.json](manifest-files.md), and we recommend using vcpkg.json for any newly authored port.**
```
`manifest files` seems not needed here. Or maybe updated it as  `Manifest files - vcpkg.json`?

2021-04-12 20:14 UTC, dg0yt commented on docs/maintainers/control-files.md
> +all new features are added only to [vcpkg.json manifest files](manifest-files.md), and we recommend using vcpkg.json for any newly authored port.**
IMHO "vcpkg.json manifest files" is what reads most fluently (apart form simply "manifest files"). "Manifest files - vcpkg.json" is fine for headlines and toc, but not in plain text.
Disclaimer: I'm not a native speaker.

But I can role back to plain "vcpkg.json".

2021-04-13 02:41 UTC, NancyLi1013 commented on docs/maintainers/control-files.md
> +all new features are added only to [vcpkg.json manifest files](manifest-files.md), and we recommend using vcpkg.json for any newly authored port.**
Thanks for your description about this point. Sounds good.

2021-04-13 02:41 UTC, NancyLi1013 approved these changes

2021-04-23 17:33 UTC, ras0219-msft approved these changes
Thanks for the PR!

2021-04-23 17:39 UTC, merged

2021-04-27 06:40 UTC, dg0yt commented
This change doesn't seem to arrive at https://vcpkg.readthedocs.io/en/latest/maintainers/control-files/