[Gmp]  add cflags to build commands for compiletime tools
microsoft/vcpkg pull request #17264
Opened 2021-04-13 14:09 UTC by xandox

add `cflags` to build commands for compile time tools. Additional PR for #15605

- #### Which triplets are supported/not supported? same
- #### Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  Yes

2021-04-14 02:16 UTC, JackBoosY commented
```
CMake Error at D:/installed/x64-windows-static/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:19 (yasm_tool_helper)
  scripts/ports.cmake:142 (include)
```
You should add yasm-tool as a host dependency.

2021-04-20 13:31 UTC, JackBoosY requested changes

2021-04-20 13:31 UTC, JackBoosY commented on ports/gmp/vcpkg.json
> +  "port-version": 6,
```suggestion
  "port-version": 5,
```

2021-04-20 13:31 UTC, JackBoosY commented on versions/baseline.json
> +      "port-version": 6
```suggestion
      "port-version": 5
```

2021-04-20 13:31 UTC, JackBoosY commented on versions/g-/gmp.json
> +    },
```suggestion
```

2021-04-20 13:31 UTC, JackBoosY approved these changes

2021-04-20 15:11 UTC, xandox commented
@JackBoosY looks like there are some problems with versions.

2021-04-21 01:25 UTC, JackBoosY commented on versions/g-/gmp.json
> +      "git-tree": "4c7fd1c1653a634159b15a5fba32592f49554a2a",
```suggestion
      "git-tree": "90eb02f55e96530420b8e83209651a9b91b7b002",
```

2021-04-29 23:13 UTC, merged

2021-04-29 23:13 UTC, strega-nil-ms commented
LGTM, thanks @xandox :)

2021-04-30 03:19 UTC, acgetchell commented
I think this broke cgal:x64-windows:

https://github.com/microsoft/vcpkg/issues/17584

2021-04-30 03:55 UTC, acgetchell commented
Confirmed, it does.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/history