Fix libvpx compilation (install process)
microsoft/vcpkg pull request #17287
Opened 2021-04-14 21:58 UTC by talregev

Fix libvpx compilation (install process)
compile on windows (x86, x64)
Fix Cannot find pdb (line 104 in profile).

2021-04-15 02:33 UTC, JackBoosY commented
```
-- Installing: D:/packages/libvpx_x64-windows/lib/vpxmd.lib
CMake Error at ports/libvpx/portfile.cmake:104 (file):
  file INSTALL cannot find
  "D:/buildtrees/libvpx/x64-windows/x64/Release/vpxmd.pdb": File exists.
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)
```
Can you double confirm your changes?

2021-04-15 05:17 UTC, talregev commented
> ```
> -- Installing: D:/packages/libvpx_x64-windows/lib/vpxmd.lib
> CMake Error at ports/libvpx/portfile.cmake:104 (file):
>   file INSTALL cannot find
>   "D:/buildtrees/libvpx/x64-windows/x64/Release/vpxmd.pdb": File exists.
> Call Stack (most recent call first):
>   scripts/ports.cmake:142 (include)
> ```
> 
> Can you double confirm your changes?

Is it from your pc?
On one of the computer libvpx compile without the change. I compile only the libvpx
Other computer I need to do the change. I compile libvpx as part of ffmpeg[all-gpl]
Maybe if I compile libvpx part of other libs, it happen?
Can you investigate it more? 

Both computers running windows 10.

2021-04-15 05:27 UTC, JackBoosY commented
@talregev  From our pipeline test, Windows10 with Visual Studio 2019.

2021-04-15 08:21 UTC, JackBoosY commented
@talregev  What triplet do you use?

2021-04-15 09:22 UTC, talregev commented
both x86-windows x64-windows

2021-04-16 07:10 UTC, mcmtroffaes commented
I haven't seen this happen on my CI (with x64-windows, x64-windows-static, and x64-windows-static-md); installation and compilation works fine. For the record, logs are here (for an ffmpeg master build, but otherwise the portfiles are the same, and in particular its the same for libvpx):

https://ci.appveyor.com/project/mcmtroffaes/ffmpeg-msvc-build/build/job/3yn0l4c3ge9fwkiy (x64-windows)
https://ci.appveyor.com/project/mcmtroffaes/ffmpeg-msvc-build/build/job/stavyb3m9i23my7w (x64-windows-static)
https://ci.appveyor.com/project/mcmtroffaes/ffmpeg-msvc-build/build/job/yr0nuflv8k8e4j0a (x64-windows-static-md)

This seems vaguely related to #12706 where the names were fixed to ensure the pdb files were found when compiling other apps against ffmpeg: the pdb files cannot be renamed after install.

2021-04-16 07:22 UTC, talregev commented
> This seems vaguely related to #12706 where the names were fixed to ensure the pdb files were found when compiling other apps against ffmpeg: the pdb files cannot be renamed after install.

I think it a good lead and I would start from there. Did you try / ci compile `vcpkg ffmpeg[all-gpl]`?
I think when it compile ffmep with all the option, it also compile an apps that using ffmpeg, and maybe that why it rename the pdb. if it that the case, my suggestion is that the pdb always need to be rename

2021-04-16 07:30 UTC, JackBoosY commented
I think CRT linkage affected it.
Can you please provide `vpx.vcxproj` in _VCPKG_ROOT/buildtrees/libvpx/x86-windows_ ?

2021-04-16 07:42 UTC, mcmtroffaes commented
> Did you try / ci compile `vcpkg ffmpeg[all-gpl]`?

That's a good suggestion. I just tested `vcpkg ffmpeg[core,ffmpeg,libvpx]` on x64-windows and I can confirm that this works as expected at least on my local setup, with the ffmpeg binary able to encode with the libvpx-vp9 codec. Note that building ffmpeg (with whichever feature set) will not change the libvpx build on vcpkg: the ffmpeg build process does not influence the build process of its dependencies (such as libvpx).

2021-04-16 16:51 UTC, talregev commented
I preproduce the problem with small example. 
`vcpkg install ffmpeg[core,ffmpeg,vpx]:x64-windows`
[vpx.vcxproj and logs.zip](https://github.com/microsoft/vcpkg/files/6326741/vpx.vcxproj.and.logs.zip)

2021-04-16 17:27 UTC, talregev commented
Maybe the problem is from the things I install on visual studio. like mfc and clang support?

2021-04-18 20:22 UTC, talregev commented
@JackBoosY any news? 
Do you need more information?

2021-04-19 02:55 UTC, JackBoosY commented
@talregev  Nope.

2021-04-19 06:18 UTC, JackBoosY commented
@talregev  Can you test whether my changes is correct?

2021-04-19 07:14 UTC, JackBoosY approved these changes

2021-04-19 07:15 UTC, JackBoosY requested changes

2021-04-19 07:15 UTC, JackBoosY commented on ports/ffmpeg/CONTROL
> +Port-Version: 4
```suggestion
Port-Version: 5
```

2021-04-19 09:14 UTC, mcmtroffaes commented
Thanks @JackBoosY! For the record, I've just tested this pr by compiling an application against ``ffmpeg[core,avcodec,vpx]`` on the x64-windows and x64-windows-static triplets, and I can confirm that it works like charm, besides also cleaning things up for libvpx detection on ffmpeg. Fingers crossed it also fixes @talregev 's issue.

2021-04-19 10:02 UTC, JackBoosY commented on versions/f-/ffmpeg.json
> +      "git-tree": "f4fe9fdcd47745dee73dfecc23d4abd0a5515cb0",
```suggestion
      "git-tree": "68f6d071ba23bf8ad28a12a507c8089a47a76d73",
```

2021-04-19 10:03 UTC, JackBoosY approved these changes

2021-04-19 13:54 UTC, JackBoosY approved these changes

2021-04-19 21:26 UTC, strega-nil commented
LGTM! Thanks @talregev

2021-04-19 21:26 UTC, merged

2021-04-19 22:06 UTC, BillyONeal commented
Unfortunately it doesn't look like this fixed it, in https://github.com/microsoft/vcpkg/pull/17331 with this change applied we still see:

```
CMake Error at ports/libvpx/portfile.cmake:104 (file):
  file INSTALL cannot find
  "D:/buildtrees/libvpx/arm-uwp/ARM/Release/vpx/vpx.pdb": File exists.
```

2021-04-19 22:22 UTC, BillyONeal commented
I think I have a fix, will put into the VM update PR

2021-04-20 20:26 UTC, Hoikas commented
A user of my project is reporting this same failure even after this PR.

2021-04-21 12:25 UTC, mcmtroffaes commented
I've started hitting this now as well on appveyor CI (not locally); https://github.com/microsoft/vcpkg/commit/91542464a564bfad42fcf2fa2fbafa3cab929a54 also fixed it for me. Perhaps something to do with the version of Visual Studio.

2021-04-24 04:30 UTC, Hoikas commented
This issue is now being tripped on GitHub Actions CI. Is there any chance the fix can be fast-tracked @BillyONeal?

2021-04-26 18:32 UTC, BillyONeal commented
> This issue is now being tripped on GitHub Actions CI. Is there any chance the fix can be fast-tracked @BillyONeal?

The VM update just landed, try again?

2021-04-26 23:15 UTC, Hoikas commented
That seems to have fixed it, thanks!

2021-04-27 00:40 UTC, JackBoosY commented
@Hoikas @mcmtroffaes  Fixed.

2021-04-27 06:41 UTC, mcmtroffaes commented
Yup, happy to confirm the fix in master now. Thanks a bunch!