[vcpkg.cmake] PREPEND CMAKE_FIND_ROOT_PATH
microsoft/vcpkg pull request #17336
Opened 2021-04-17 19:27 UTC by autoantwort

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #17163

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  N/A

2021-04-17 19:45 UTC, Neumann-A commented
a) Why?
b) No. Why no? Because users toolchain is loaded before vcpkg and users might want to override there find paths.

2021-04-17 20:00 UTC, autoantwort commented
> a) Why?
 
Because of #17163. Otherwise libs from the toolchain gets selected
> b) No. Why no? Because users toolchain is loaded before vcpkg and users might want to override there find paths.

I don't want that in my project. And afaik there is currently no way to prevent that.

2021-04-17 20:08 UTC, autoantwort commented
Maybe we can add an option `VCPKG_PREFER_VCPKG_LIBS` that toggles the behavior (`PREPEND` vs `APPEND`)

2021-04-17 20:25 UTC, Neumann-A commented
The correct solution is to have vcpkg install working boost cmake configs....

2021-04-18 04:46 UTC, longnguyen2004 commented
> The correct solution is to have vcpkg install working boost cmake configs....

Time to modify `boost-modular-build-helper` then. If that's the case, we would have to move everything into the `CMakeLists.txt`.

2021-04-18 05:55 UTC, huangqinjin commented
> Is there a way for b2 to generate CMake configs?

Actually there is a module https://github.com/boostorg/boost_install. It will generate cmake config files for each module like below

```shell
boost$ ls stage/lib/cmake
Boost-1.75.0                     boost_graph-1.75.0           boost_math_tr1l-1.75.0             boost_stacktrace_noop-1.75.0
boost_atomic-1.75.0              boost_graph_parallel-1.75.0  boost_mpi-1.75.0                   boost_stacktrace_windbg-1.75.0
boost_chrono-1.75.0              boost_headers-1.75.0         boost_nowide-1.75.0                boost_stacktrace_windbg_cached-1.75.0
boost_container-1.75.0           boost_iostreams-1.75.0       boost_numpy-1.75.0                 boost_system-1.75.0
boost_context-1.75.0             boost_json-1.75.0            boost_prg_exec_monitor-1.75.0      boost_test_exec_monitor-1.75.0
boost_contract-1.75.0            boost_locale-1.75.0          boost_program_options-1.75.0       boost_thread-1.75.0
boost_coroutine-1.75.0           boost_log-1.75.0             boost_python-1.75.0                boost_timer-1.75.0
boost_date_time-1.75.0           boost_log_setup-1.75.0       boost_random-1.75.0                boost_type_erasure-1.75.0
BoostDetectToolset-1.75.0.cmake  boost_math_c99-1.75.0        boost_regex-1.75.0                 boost_unit_test_framework-1.75.0
boost_exception-1.75.0           boost_math_c99f-1.75.0       boost_serialization-1.75.0         boost_wave-1.75.0
boost_fiber-1.75.0               boost_math_c99l-1.75.0       boost_stacktrace_addr2line-1.75.0  boost_wserialization-1.75.0
boost_fiber_numa-1.75.0          boost_math_tr1-1.75.0        boost_stacktrace_backtrace-1.75.0
boost_filesystem-1.75.0          boost_math_tr1f-1.75.0       boost_stacktrace_basic-1.75.0
```
Unless you invoke `b2 --no-cmake-config ...`.

2021-04-18 11:42 UTC, autoantwort commented
> Unless you invoke `b2 --no-cmake-config ...`.

But [here](https://github.com/microsoft/vcpkg/blob/414bec05f2a97cfc0ddb8e22fd4635dfe2a20ab8/ports/boost-modular-build-helper/CMakeLists.txt#L156) `--no-cmake-config` is not passed to b2 but no cmake files are generated

2021-04-18 12:15 UTC, huangqinjin commented
Since vcpkg doesn't use `boost_install` currently.

2021-04-18 12:44 UTC, autoantwort commented
> Since vcpkg doesn't use `boost_install` currently.

Ah ok, do you know how to use this library? Iiuc you only have to copy the content of the lib to the `src/tools` folder in the [boost-build portfile](https://github.com/microsoft/vcpkg/blob/master/ports/boost-build/portfile.cmake) and than it simply works?

2021-04-18 15:04 UTC, huangqinjin commented
The rule [`boost-install`](https://github.com/boostorg/boost_install/blob/047edbaab4c3740fce8c0c9104174aa7053606e2/boost-install.jam#L1220) provided by `boost_install` will generate cmake config files, but vcpkg customized [`boost-install`](https://github.com/microsoft/vcpkg/blob/414bec05f2a97cfc0ddb8e22fd4635dfe2a20ab8/ports/boost-modular-build-helper/Jamroot.jam#L17) does not.

2021-04-19 08:18 UTC, JackBoosY commented
I remember @ras0219 @ras0219-msft or @BillyONeal answered this question.
The result: we shouldn't do that.

2021-04-20 00:09 UTC, BillyONeal commented
> I remember @ras0219 @ras0219-msft or @BillyONeal answered this question.
> The result: we shouldn't do that.

I assume you mean https://github.com/microsoft/vcpkg/pull/14552/

2021-04-23 23:02 UTC, ras0219-msft commented
This seems best addressed by installing a `vcpkg-cmake-wrapper.cmake` that does:
```cmake
set(Boost_NO_BOOST_CMAKE ON)
set(BOOST_ROOT ${_VCPKG_INSTALLED_DIR})
# The usual chaining _find_package()
```
(copied from @Neumann-A's comment https://github.com/microsoft/vcpkg/issues/17163#issuecomment-821882962)

2021-04-24 01:45 UTC, autoantwort commented
> This seems best addressed by installing a `vcpkg-cmake-wrapper.cmake` in one of the low level boost ports (vcpkg-modular-boost-helper?) that does:
> 
> ```cmake
> set(Boost_NO_BOOST_CMAKE ON)
> set(BOOST_ROOT ${_VCPKG_INSTALLED_DIR})
> # The usual chaining _find_package()
> ```

The problem is that is does not help, I still get the same error with that as you can see in #17163

2021-05-24 18:29 UTC, ras0219-msft commented
I think that https://github.com/microsoft/vcpkg/issues/18015 is a strong motivator for making this prepend by default. If users want to override vcpkg in their custom toolchain, they can avoid `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` and instead include our toolchain from theirs, then prepend their own changes.

2021-05-24 19:27 UTC, talregev commented
@ras0219-msft Thank you Robert. 
I vote up for `VCPKG_PREFER_VCPKG_LIBS` default on option.

2021-05-28 11:41 UTC, autoantwort commented
> I think that #18015 is a strong motivator for making this prepend by default. If users want to override vcpkg in their custom toolchain, they can avoid `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` and instead include our toolchain from theirs, then prepend their own changes.

So should I remove the `VCPKG_PREFER_VCPKG_LIBS` option and simply change it to `list(PREPEND ...)` ?

2021-05-28 12:39 UTC, talregev commented
> > I think that #18015 is a strong motivator for making this prepend by default. If users want to override vcpkg in their custom toolchain, they can avoid `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` and instead include our toolchain from theirs, then prepend their own changes.
> 
> So should I remove the `VCPKG_PREFER_VCPKG_LIBS` option and simply change it to `list(PREPEND ...)` ?

Maybe just change the default to on?

2021-06-02 05:33 UTC, strega-nil-ms commented
Marking `requires:discussion` since this is interesting and I agree with it, but we clearly need to discuss how to either work around it for cases like @Neumann-A's.

2021-06-02 06:23 UTC, dg0yt commented
> how to either work around it for cases like (AT)Neumann-A's.

@strega-nil-ms Which cases are you refering to?

2021-06-02 07:16 UTC, autoantwort commented
I thing @strega-nil-ms is referring to `Because users toolchain is loaded before vcpkg and users might want to override there find paths.`. Isn't the general solution for that problem to write empty overlay ports? Iiuc is that what you propose on discord all the time when a user has such a problem.

2021-06-03 05:00 UTC, dg0yt commented
> `Because users toolchain is loaded before vcpkg and users might want to override there find paths`

So this is what the user does. I'm curious about the use case. 

IMO it is at least fragile to expect the early part of the toolchain configuration (user toolchain) to *directly override effects* of the later parts (vcpkg toolchain, cmake). This is different from simply setting variables (e.g. CMAKE_C_COMPILER) which *change behaviour* of later parts.

2021-06-03 21:33 UTC, strega-nil requested changes
Rename the variable so as to make "preferring vcpkg libraries" to be the default.

2021-06-03 21:33 UTC, strega-nil commented on scripts/buildsystems/vcpkg.cmake
> +option(VCPKG_PREFER_VCPKG_LIBS "Prepends the vcpkg paths to CMAKE_PREFIX_PATH, CMAKE_LIBRARY_PATH and CMAKE_FIND_ROOT_PATH so that vcpkg libraries/packages are found before toolchain/system libraries
```suggestion
option(VCPKG_PREFER_SYSTEM_LIBS "Prepends the vcpkg paths to CMAKE_PREFIX_PATH, CMAKE_LIBRARY_PATH and CMAKE_FIND_ROOT_PATH so that vcpkg libraries/packages are found before toolchain/system libraries/packages." OFF)
```

2021-06-03 21:33 UTC, strega-nil commented on scripts/buildsystems/vcpkg.cmake
> +endif()
```suggestion
if(VCPKG_PREFER_SYSTEM_LIBS)
    set(Z_VCPKG_PATH_LIST_OP APPEND)
else()
    set(Z_VCPKG_PATH_LIST_OP PREPEND)
endif()
```

2021-06-03 21:51 UTC, strega-nil-ms commented
This needs a world rebuild, so placing into that bucket.

2021-06-04 01:11 UTC, autoantwort commented on scripts/buildsystems/vcpkg.cmake
> +option(VCPKG_PREFER_SYSTEM_LIBS "Prepends the vcpkg paths to CMAKE_PREFIX_PATH, CMAKE_LIBRARY_PATH and CMAKE_FIND_ROOT_PATH so that vcpkg libraries/packages are found before toolchain/system librarie
```suggestion
option(VCPKG_PREFER_SYSTEM_LIBS "Appends the vcpkg paths to CMAKE_PREFIX_PATH, CMAKE_LIBRARY_PATH and CMAKE_FIND_ROOT_PATH so that vcpkg libraries/packages are found after toolchain/system libraries/packages." OFF)
```

2021-06-04 02:03 UTC, JackBoosY commented
LGTM.

2021-06-04 04:12 UTC, talregev commented
Can you make the `VCPKG_PREFER_SYSTEM_LIBS` default `ON`?

2021-06-04 04:14 UTC, talregev commented
Also can some give me an example where I can change `VCPKG_PREFER_SYSTEM_LIBS` value? (on which user file?)

2021-06-04 04:17 UTC, talregev commented
Sorry, I made a mistake. 
`VCPKG_PREFER_SYSTEM_LIBS` should be default `OFF`
Thank you for the PR.

2021-06-04 04:18 UTC, dg0yt commented
> Can you make the `VCPKG_PREFER_SYSTEM_LIBS` default `ON`?

@talregev AFAIU you don't want it to be `ON` because this is what vcpkg does until now, and it didn't work for you (zlib on Android).

> Also can some give me an example where I can change `VCPKG_PREFER_SYSTEM_LIBS` value? (on which user file?)

The new variable needs to be documented in `docs/users/triplets.md`.

2021-06-04 04:20 UTC, talregev commented
@dg0yt Thank you for the info!
I was confuse by the rename. Now I understand I want `VCPKG_PREFER_SYSTEM_LIBS` will be default `OFF`. 
Thank you!

2021-06-04 11:12 UTC, autoantwort commented
> The new variable needs to be documented in `docs/users/triplets.md`.

Is it really a triplet option? Is it not more a configuration option (I think there is no documentation, maybe add this in `docs/users/integration.md`)

2021-06-04 12:45 UTC, dg0yt commented
> Is it really a triplet option? Is it not more a configuration option (I think there is no documentation, maybe add this in `docs/users/integration.md`)

Hm, I see. 
- Is there a single answer for manifest mode and standalone mode?
- Is there (fairly) consistent behaviour for cmake config, pkg-config, and all the options passed by various `cmake_configure_xxx`?
- Isn't there a risk of subtle ABI issues if it is user project configuration?

(From my POV, vcpkg always comes on top of user toolchain, but below user project settings. I don't need the option, but I need the new behaviour.)

2021-06-04 13:06 UTC, autoantwort commented
>     * Is there a single answer for manifest mode and standalone mode?

There is no difference
>     * Is there (fairly) consistent behaviour for cmake config, pkg-config, and all the options passed by various `cmake_configure_xxx`?

? If you use the vcpkg toolchain file is your project and uses find_package, vcpkg packages are now preferred.  
>     * Isn't there a risk of subtle ABI issues if it is user project configuration?

I mean it maybe now selects other(the right) packages
> I don't need the option, but I need the new behaviour.)

Same 

I would add it to `docs/users/integration.md` and restructure the documentation because currently the documentation says for example *There are two main categories of project integration: `import` and `export` command* Huh, no Cmake and MSBuild integration ?

2021-06-07 10:35 UTC, PhoebeHui commented
/azp run

2021-06-07 23:42 UTC, strega-nil-ms commented
You can add docs here https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#cmake-toolchain-file-recommended-for-open-source-cmake-projects

2021-06-08 14:03 UTC, autoantwort commented
> You can add docs in [docs/users/integration.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#cmake-toolchain-file-recommended-for-open-source-cmake-projects)

Yesterday I have found [docs/users/manifests.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#cmake-integration), I thing that fists best because it already explains other cmake options

2021-06-10 07:33 UTC, dg0yt commented
What I'm still concerned about but didn't write down so far:
Is vcpkg touching the right variables, given cmake's lookup algorithms? 
As part of the toolchain definition, shouldn't it prepend to `CMAKE_SYSTEM_<FEATURE>_PATH` instead of `CMAKE_<FEATURE>_PATH`? 

1. CMake documentation calls `CMAKE_<FEATURE>_PATH` "*cmake-specific cache variables. These are intended to be used on the command line with a -DVAR=value.*" ([`find_package` search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure)).
   Touching them in the toolchain, in connection with prepending as introduced as default behaviour in this PR, blocks the effect of user parameters.
   This affects not only user projects but also calls to `vcpkg_cmake_configure` in portfiles.
2. Using `CMAKE_SYSTEM_<FEATURE>_PATH` would enable the following additional lookups *before* vcpkg paths (cf. search procedure):
    - cmake-specific environment variables
    - paths specified by the HINTS option
    - standard system environment variables

2021-06-16 05:40 UTC, talregev commented
@autoantwort Any news

2021-06-16 23:06 UTC, autoantwort commented
> What I'm still concerned about but didn't write down so far:
> Is vcpkg touching the right variables, given cmake's lookup algorithms?
> As part of the toolchain definition, shouldn't it prepend to `CMAKE_SYSTEM_<FEATURE>_PATH` instead of `CMAKE_<FEATURE>_PATH`?

I don't know CMake that much so I don't know. I can only read the documentation and it says about `CMAKE_SYSTEM_LIBRARY_PATH`: ` It is not intended to be modified by the project; use CMAKE_LIBRARY_PATH for this.`.

I have asked about this comment on discord and the only response by someone I didn't know was that it is maybe something for another PR.  

So I am waiting for feedback of @strega-nil-ms, @strega-nil, @ras0219, @ras0219-msft or maybe @Neumann-A (I think you also know CMake very well :) )

2021-06-17 03:55 UTC, dg0yt commented
> `It is not intended to be modified by the project; use CMAKE_LIBRARY_PATH for this.`

Yes, this is the key point: Is vcpkg part of the (user) project? In my eyes, it is part of the system

2021-06-18 00:18 UTC, ras0219 approved these changes

2021-06-23 22:30 UTC, strega-nil commented
So, while I agree that in theory, vcpkg is the system, apparently nobody else uses the `SYSTEM` variables, which means that this won't fix the actual bug. Additionally, it's very likely that overriding vcpkg libraries is a Bad Idea anyways, for ODR purposes. Therefore, I think the current behavior of this PR is correct.

Thanks @autoantwort :)

2021-06-23 22:30 UTC, merged

2021-06-24 04:25 UTC, dg0yt commented
> apparently nobody else uses the `SYSTEM` variables

Hm, did you really look at cmake toolchain files?

> which means that this won't fix the actual bug. Additionally, it's very likely that overriding vcpkg libraries is a Bad Idea anyways, for ODR purposes.

"This" was proposed and should fix the bug as well:

>> shouldn't it prepend to `CMAKE_SYSTEM_<FEATURE>_PATH` instead of `CMAKE_<FEATURE>_PATH`?
>> ...
Using `CMAKE_SYSTEM_<FEATURE>_PATH` would enable the following additional lookups before vcpkg paths (cf. search procedure):
>> -  cmake-specific environment variables
>> -  paths specified by the HINTS option
>> -  standard system environment variables

Overriding will happen with this PR or with prepending to `CMAKE_SYSTEM_<FEATURE>_PATH`. Now is just made harder, even for valid use cases.
Note that my remark did not just apply to libs, but also to includes, executables, etc. I would strongly prefer conistent handing, for user experience, and for getting headers which match the libraries, etc.

I do admit that binary caching becomes fragile as soon as paths outside vcpkg change binary outputs.