Update VMs, CUDA to 11.3, and pwsh to 7.1.3
microsoft/vcpkg pull request #17331
Opened 2021-04-17 06:47 UTC by BillyONeal

I tried updating to Ubuntu 20.04 as well but that's apparently not offered in a reasonable way on Azure right now.

2021-04-19 09:57 UTC, NancyLi1013 commented
The failures caused by `cudnn `depends on PR #17346.

2021-04-19 18:27 UTC, BillyONeal commented
@NancyLi1013 Thanks for pointing those out!

2021-04-19 21:07 UTC, BillyONeal commented
Looks like the many libvpx failures are https://github.com/microsoft/vcpkg/pull/17287/ ?

2021-04-20 00:49 UTC, JackBoosY commented on ports/libvpx/portfile.cmake
> +        endif()
Sorry for that, but I think we still need to know what caused this.

2021-04-20 01:46 UTC, JackBoosY approved these changes

2021-04-20 05:53 UTC, NancyLi1013 requested changes

2021-04-20 05:53 UTC, NancyLi1013 commented on ports/chromaprint/vcpkg.json
>    "version-string": "1.5.0",
```suggestion
  "version": "1.5.0",
```
We might use [version](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.reference.md#version) here.

2021-04-20 05:53 UTC, NancyLi1013 commented on versions/c-/chromaprint.json
> +      "version-string": "1.5.0",
```suggestion
      "version": "1.5.0",
```

2021-04-21 00:09 UTC, BillyONeal commented
/azp run

2021-04-21 12:58 UTC, cenit commented
you removed cudnn auto-download for recognized cuda versions. Wasn't it accepted that it was ok in other PRs?

This is removing a feature otherwise which might be the base on which someone has built something... (me)

2021-04-21 19:27 UTC, BillyONeal commented
> you removed cudnn auto-download for recognized cuda versions. Wasn't it accepted that it was ok in other PRs?

It was accepted in other PRs because from original contribution it looked like downloading any other closed source library, which would normally be OK. Unfortunately, it has been brought to our attention that this behavior is both (1) contrary to cudnn's license terms, and (2) contrary to anaconda.org's terms of service. As a result I feel forced to remove it. I did ask some nvidia folks to give us better options: https://twitter.com/MalwareMinigun/status/1384335333249097732

> This is removing a feature otherwise which might be the base on which someone has built something... (me)

I'm sorry :(

2021-04-22 00:32 UTC, jacobkahn commented
I've removed this functionality from the `nccl` port as well in https://github.com/microsoft/vcpkg/pull/17431. It would be great to get a CUDA 11.3-compatible NCCL version on the CI machines as well.

2021-04-22 04:09 UTC, BillyONeal commented
/azp run

2021-04-22 07:12 UTC, PhoebeHui commented
@BillyONeal, we noticed that many PRs failed with following failures on osx pipeline machine, could you please help take a look? 

```
Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

2021-04-22 18:24 UTC, BillyONeal commented
> @BillyONeal, we noticed that many PRs failed with following failures on osx pipeline machine, could you please help take a look?
> 

Unfortunately I know very little about how the osx stuff works; Nicole was working on that

2021-04-22 18:29 UTC, BillyONeal commented
/azp run

2021-04-24 01:27 UTC, BillyONeal commented
/azp run

2021-04-25 03:12 UTC, NancyLi1013 requested changes

2021-04-25 03:12 UTC, NancyLi1013 commented on ports/dartsim/portfile.cmake
>  vcpkg_configure_cmake(
The format should be like this:

```
 OPTIONS 
    -DDART_VERBOSE=ON
    -DDART_MSVC_DEFAULT_OPTIONS=ON
    -DDART_SKIP_DOXYGEN=ON
    -DDART_SKIP_FLANN=ON
    -DDART_SKIP_IPOPT=ON
    -DDART_SKIP_NLOPT=ON
    -DDART_SKIP_OPENGL=ON
    -DDART_SKIP_pagmo=ON
```

2021-04-25 03:12 UTC, NancyLi1013 commented on ports/dartsim/portfile.cmake
>  vcpkg_configure_cmake(
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/dartsim RENAME copyright)
`

should be updated as

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`

2021-04-25 03:12 UTC, NancyLi1013 commented on ports/libudis86/portfile.cmake
The format of options for debug should be like this:
```
OPTIONS_DEBUG
    -DDISABLE_INSTALL_HEADERS=ON
    -DDISABLE_INSTALL_TOOLS=ON
```

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/libudis86 RENAME copyright)`

 should be updated as

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`

2021-04-25 03:20 UTC, NancyLi1013 commented
On x86-windows:

`libhv `failed with this error:

```
CMake Error at CMakeLists.txt:60 (configure_file):
  Permission denied
```
Maybe this is related with parallel issue?

`kf5windowsystem` failed with this error:

```
FAILED: src/KF5WindowSystem_autogen/timestamp 
cmd.exe /C "cd /D D:\buildtrees\kf5windowsystem\x86-windows-dbg\src && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_autogen D:/buildtrees/kf5windowsystem/x86-windows-dbg/src/CMakeFiles/KF5WindowSystem_autogen.dir/AutogenInfo.json Debug && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E touch D:/buildtrees/kf5windowsystem/x86-windows-dbg/src/KF5WindowSystem_autogen/timestamp && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_transform_depfile Ninja gccdepfile D:/buildtrees/kf5windowsystem/src/v5.75.0-98cbac325e.clean D:/buildtrees/kf5windowsystem/src/v5.75.0-98cbac325e.clean/src D:/buildtrees/kf5windowsystem/x86-windows-dbg D:/buildtrees/kf5windowsystem/x86-windows-dbg/src D:/buildtrees/kf5windowsystem/x86-windows-dbg/src/KF5WindowSystem_autogen/deps D:/buildtrees/kf5windowsystem/x86-windows-dbg/CMakeFiles/d/ac0678512fc3ae64732cd27db69d826af10d6262969c164f975967658f984c1c.d"
ninja: build stopped: subcommand failed.
```

2021-04-25 06:01 UTC, NancyLi1013 commented
`dimcli `failed on x64-windows-static and x64-widnows-static-md with this error:

```
-- Install configuration: "Debug"
         -- Installing: D:/packages/dimcli_x64-windows-static-md/debug/lib/dimcli.lib
         CMake Error at cmake_install.cmake:45 (file):
           file INSTALL cannot find
           "D:/buildtrees/dimcli/x64-windows-static-md-dbg/dimcli.dir/Debug/dimcli.pdb":
           File exists.
```
`wangle` failed on x64-windows and x64-windows-static-md with this error:
```
D:\installed\x64-windows-static-md\include\fizz/protocol/FizzBase.h(139): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1588)
```

`paraview ` failed on x64-windows-static with this error:

```
FAILED: Qt/ApplicationComponents/pqApplicationComponents_autogen/timestamp 
cmd.exe /C "cd /D D:\buildtrees\paraview\x64-windows-static-dbg\Qt\ApplicationComponents && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_autogen D:/buildtrees/paraview/x64-windows-static-dbg/Qt/ApplicationComponents/CMakeFiles/pqApplicationComponents_autogen.dir/AutogenInfo.json Debug && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E touch D:/buildtrees/paraview/x64-windows-static-dbg/Qt/ApplicationComponents/pqApplicationComponents_autogen/timestamp && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_transform_depfile Ninja gccdepfile D:/buildtrees/paraview/src/4fb6e6800f-6b3165e6c7.clean D:/buildtrees/paraview/src/4fb6e6800f-6b3165e6c7.clean/Qt/ApplicationComponents D:/buildtrees/paraview/x64-windows-static-dbg D:/buildtrees/paraview/x64-windows-static-dbg/Qt/ApplicationComponents D:/buildtrees/paraview/x64-windows-static-dbg/Qt/ApplicationComponents/pqApplicationComponents_autogen/deps D:/buildtrees/paraview/x64-windows-static-dbg/CMakeFiles/d/9f52e9f0cf771bc230acb38a0b83aad4a0e8fbcb2a50c4bba7e0ead5db381cdc.d"
```

2021-04-25 06:14 UTC, NancyLi1013 commented
`libidn2 `failed on osx with this error:

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force -I m4 -I unistring/m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
autoreconf: configure.ac: not using Intltool
autoreconf: running: gtkdocize --copy
Can't exec "gtkdocize": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: gtkdocize failed with exit status: 2
```
This should be fixed in PR #17419, please see https://github.com/microsoft/vcpkg/pull/17419#issuecomment-824819810 and https://github.com/microsoft/vcpkg/pull/17419#issuecomment-825719305.

Seems you forgot to add `forest:x64-osx=fail` in ci.baseline.txt.

2021-04-25 06:33 UTC, BillyONeal commented
>For forest, seems you forgot to add forest:x64-osx=fail in ci.baseline.txt.

I didn't see it before because this PR didn't trigger a world-rebuild that attempted to build it on osx until I did the cmake version update.

2021-04-25 08:52 UTC, BillyONeal commented
/azp run

2021-04-26 01:31 UTC, NancyLi1013 approved these changes

2021-04-26 01:34 UTC, NancyLi1013 commented
All checks have passed now.

2021-04-26 17:23 UTC, strega-nil approved these changes

2021-04-26 17:23 UTC, strega-nil commented on scripts/azure-pipelines/windows/utility-prefix.ps1
> +# Copyright (c) Microsoft Corporation.
This should probably be a `utilities.psm1`, like in macOS, but not blocking

2021-04-26 17:25 UTC, BillyONeal commented on scripts/azure-pipelines/windows/utility-prefix.ps1
> +# Copyright (c) Microsoft Corporation.
We can't shove .psm1s through `Invoke-AzVmRunCommand` though; we're taking this script and find and replacing `# REPLACE WITH UTILITY-PREFIX.ps1` with it.

2021-04-26 17:27 UTC, merged

2021-04-27 00:31 UTC, JackBoosY commented
Great! Thanks Billy!