[aws-sdk-cpp] [openssl] Fix iOS build
microsoft/vcpkg pull request #17338
Opened 2021-04-18 01:25 UTC by ahmedyarub

Don't pass the the compiler to OpenSSL when building for iOS. That would end generating a MacOS library which would cause linking errors when the libraries are used. The OpenSSL configuration scripts know how to detect the target OS and compile using the correct command, example: `xcrun -sdk iphonesimulator cc`. Note that this change should fix building for all iOS targets, including both simulators and actual devices.
Add try_compile() parameters required to test the features of curl when cross-compiling AWS SDK for C++.

- #### What does your PR fix?  
  Fixes building OpenSSL and AWS SDK for C++ for iOS.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All iOS triplets

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-04-19 03:04 UTC, JackBoosY requested changes

2021-04-19 03:04 UTC, JackBoosY commented on versions/a-/aws-sdk-cpp.json
> +      "git-tree": "2795f006adfb732d610a140ef9eb036f053a5997",
```suggestion
      "git-tree": "9c60baa2cff0bbfc024a8241b96f6685f4e083d3",
```

2021-04-19 03:04 UTC, JackBoosY commented on versions/o-/openssl.json
> +      "git-tree": "2797d49ed1aa47fd6f37965c3db7dc48ca64d1f5",
```suggestion
      "git-tree": "3388a88872808e9926c9d94a702bca7e9f2736f9",
```

2021-04-19 06:56 UTC, JackBoosY commented
I think you should wait for my PR https://github.com/microsoft/vcpkg/pull/17341 merge.

2021-04-19 06:56 UTC, JackBoosY approved these changes

2021-04-21 07:51 UTC, JackBoosY commented on versions/a-/aws-sdk-cpp.json
> +      "git-tree": "422c3181effad9596e2a70905d357e39ec33d5cc",
```suggestion
      "git-tree": "c23d66191b235f6f388187395b62f38b8e6e35f5",
```

2021-04-21 07:51 UTC, JackBoosY commented on versions/o-/openssl.json
> +      "git-tree": "f64c492c931c3cb248575a39ae92645392564ad3",
```suggestion
      "git-tree": "01fede48f331d05f2feb591061d9e5c1bc076fb0",
```

2021-04-23 23:13 UTC, ras0219-msft requested changes
Thanks for the PR!

Generally, this smells like we simply aren't correctly propagating flags to the build -- we're missing some flags from the big list on lines 50-77 or so.

This file comes from a time before we had https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_internal_get_cmake_vars.cmake, which is the new way of approaching this problem. See https://github.com/microsoft/vcpkg/blob/master/scripts/get_cmake_vars/CMakeLists.txt for the "modern" version.

I'm not opposed to this stop-gap for now as long as it's better integrated with the existing behavior, but the long term goal will be to move to `vcpkg_internal_get_cmake_vars()`.

2021-04-23 23:13 UTC, ras0219-msft commented on ports/openssl/unix/CMakeLists.txt
> +    add_custom_command(
This call should be combined with the main `add_custom_command()` with only the needed parts changed.

For example, `DISABLES` could be set in an if/else chain.

2021-04-24 23:26 UTC, ahmedyarub commented
> Thanks for the PR!
> 
> Generally, this smells like we simply aren't correctly propagating flags to the build -- we're missing some flags from the big list on lines 50-77 or so.
> 
> This file comes from a time before we had https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_internal_get_cmake_vars.cmake, which is the new way of approaching this problem. See https://github.com/microsoft/vcpkg/blob/master/scripts/get_cmake_vars/CMakeLists.txt for the "modern" version.
> 
> I'm not opposed to this stop-gap for now as long as it's better integrated with the existing behavior, but the long term goal will be to move to `vcpkg_internal_get_cmake_vars()`.

Appreciate the feedback @ras0219-msft . Please give me a couple of days to redo this PR and the Emscripten/WASM32. I'll make the suggested modernization and test on Windows, Ubuntu 20.04 (WSL), MacOS Big Sur, latest Android NDK, iOS and Emscripten SDK on WSL.

2021-05-09 20:19 UTC, ahmedyarub commented
> Thanks for the PR!
> 
> Generally, this smells like we simply aren't correctly propagating flags to the build -- we're missing some flags from the big list on lines 50-77 or so.
> 
> This file comes from a time before we had https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_internal_get_cmake_vars.cmake, which is the new way of approaching this problem. See https://github.com/microsoft/vcpkg/blob/master/scripts/get_cmake_vars/CMakeLists.txt for the "modern" version.
> 
> I'm not opposed to this stop-gap for now as long as it's better integrated with the existing behavior, but the long term goal will be to move to `vcpkg_internal_get_cmake_vars()`.

I thought that this method was not supposed to be used by us port devs, right? I tried using vcpkg_configure_make() but it is not compatible at all with OpenSSL and I had to close the PR.

2021-05-18 09:37 UTC, JackBoosY commented
Depends on https://github.com/microsoft/vcpkg/pull/17983.

2021-05-19 06:15 UTC, JackBoosY approved these changes

2021-05-26 21:03 UTC, strega-nil-ms commented
@ahmedyarub could you rebase onto latest?

2021-05-26 21:44 UTC, ahmedalnuaimi commented
> @ahmedyarub could you rebase onto latest?

Done.

2021-05-26 21:51 UTC, ahmedalnuaimi commented
Please hold on merging I need to make more tests since the rebase...

2021-05-26 21:53 UTC, ahmedyarub commented
> @ahmedyarub could you rebase onto latest?

Please hold on merging I need to make more tests since the rebase...

2021-05-26 23:52 UTC, ahmedalnuaimi commented
OK tested both on iOS and Emscripten on Ubuntu. Fixed a couple of bugs and not it should be good to go.

2021-05-26 23:54 UTC, ahmedyarub commented
OK tested both on iOS and Emscripten on Ubuntu. Fixed a couple of bugs and not it should be good to go.

2021-06-07 19:05 UTC, strega-nil-ms approved these changes

2021-06-07 19:05 UTC, merged

2021-06-07 19:05 UTC, strega-nil-ms commented
Thanks @ahmedyarub :)