[Open3d] new port
microsoft/vcpkg pull request #17423
Opened 2021-04-21 15:38 UTC by fran6co

This is part of #12199

Depends on:

- https://github.com/microsoft/vcpkg/pull/17415
- https://github.com/microsoft/vcpkg/pull/17370

I disable GUI for now, I will enable it when I get filament working with it

2021-04-22 07:02 UTC, NancyLi1013 requested changes

2021-04-22 07:02 UTC, NancyLi1013 commented on ports/poissonrecon/CMakeLists.txt
> +endif()
Can you add CMakeLists.txt to upstream?

2021-04-22 08:12 UTC, fran6co commented on ports/poissonrecon/CONTROL
> +Build-Depends: zlib, libpng, libjpeg-turbo
I'll do the change in https://github.com/microsoft/vcpkg/pull/17370

2021-04-22 08:13 UTC, fran6co commented on ports/tinygltf/portfile.cmake
I'll do the change in https://github.com/microsoft/vcpkg/pull/17415

2021-04-22 08:14 UTC, fran6co commented on ports/poissonrecon/intel-isl.patch
> +-
This has been discussed in https://github.com/microsoft/vcpkg/pull/17370 already, this changes come from a fork of the project to fix the compilation. The project itself doesn't seem to that active with releases

2021-04-22 08:15 UTC, fran6co commented on ports/poissonrecon/CMakeLists.txt
> +endif()
There is a PR already but it didn't get merged yet

2021-04-22 08:15 UTC, fran6co commented on ports/poissonrecon/intel-isl.patch
> +-
The fork was made by the open3d guys

2021-04-22 08:22 UTC, fran6co commented on ports/poissonrecon/intel-isl.patch
> +-
Fixed in https://github.com/microsoft/vcpkg/pull/17370

2021-04-22 08:22 UTC, fran6co commented on ports/poissonrecon/CONTROL
> +Build-Depends: zlib, libpng, libjpeg-turbo
Fixed in https://github.com/microsoft/vcpkg/pull/17370

2021-04-22 09:10 UTC, NancyLi1013 commented on ports/poissonrecon/CMakeLists.txt
> +endif()
Thanks for your information. Is it this PR https://github.com/mkazhdan/PoissonRecon/pull/35 in upstream?

2021-04-22 10:47 UTC, fran6co commented on ports/poissonrecon/CMakeLists.txt
> +endif()
yeah, it looks like it. But the PR is a bit all over the place

2021-05-11 05:10 UTC, fran6co commented
> `Open3d `failed with the following errors:
> 
> ```
> 
> -- Found PythonInterp: D:/installed/x86-windows/tools/python3/python.exe (found version "3.9.2") 
> 
> CMake Error at D:/installed/x86-windows/share/pybind11/FindPythonLibsNew.cmake:210 (message):
> 
>   Python libraries not found
> 
> Call Stack (most recent call first):
> 
>   C:/a/1/s/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
> 
>   D:/installed/x86-windows/share/pybind11/pybind11Tools.cmake:38 (find_package)
> 
>   D:/installed/x86-windows/share/pybind11/pybind11Common.cmake:195 (include)
> 
>   D:/installed/x86-windows/share/pybind11/pybind11Config.cmake:249 (include)
> 
>   C:/a/1/s/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
> 
>   3rdparty/find_dependencies.cmake:726 (find_package)
> 
>   CMakeLists.txt:444 (include)
> 
> ```

It looks to be pybind11 not finding python. I couldn't get to build python with the latest vcpkg on windows, could that be related?

2021-05-13 21:01 UTC, ssheorey commented
@fran6co Open3D doesn't support Python 3.9.x as yet.

2021-05-25 09:06 UTC, JackBoosY commented
> @fran6co Open3D doesn't support Python 3.9.x as yet. Only 3.6-3.8.

If it's true, we should wait for the upstream to support newer Python.

2021-05-26 09:55 UTC, fran6co commented
I don't think the problem is python 3.9 given that I'm disabling all python stuff. Right now it's failing on windows inside pybind11 checks that technically are not needed given the current configuration but I haven't seen an easy way to turn it off

2021-05-26 15:06 UTC, ssheorey commented
@fran6co Please see this issue https://github.com/intel-isl/Open3D/issues/3376
Python is still needed for the build process.
It should work if we can specify the [full path to the Python executable as a CMake argument.](https://github.com/intel-isl/Open3D/issues/3376#issuecomment-833577254).

2021-07-20 07:45 UTC, NancyLi1013 commented
Can we convert this PR to draft until you have done all work? @fran6co

2021-07-20 07:49 UTC, fran6co commented
Yes, please do. I'll come back to it when I have some time. 0.13 came out as well

2021-08-18 18:59 UTC, Ulysses1337 commented
I really appreciate your effort to take on this ill-designed behemoth. Presumably I'm not alone in my desire to just process point clouds. I don't want the bloat of an asset importer or renderer, neither do I want to inherit someone else's logger macros. Does it look like it will be feasible to make the major sideshows optional?

2021-08-18 21:46 UTC, fran6co commented
I think it should be, my goal was to just create a baseline, get it
compiling and integrated to vcpkg with some of the features. Probably the
lifecycle it’s going to be: get all the features working first and then
making them optional later

On Wed, 18 Aug 2021 at 20:59, Ulysses1337 ***@***.***> wrote:

> I really appreciate your effort to take on this ill-designed behemoth.
> Presumably I'm not alone in my desire to just process point clouds. I don't
> want the bloat of an asset importer or renderer, neither do I want to
> inherit someone else's logger macros. Does it look like it will be feasible
> to make the major sideshows optional?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/17423#issuecomment-901354449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFRISHFESLURJC2CZFV263T5P7ILANCNFSM43KTRAXA>
> .
>

2021-09-10 07:05 UTC, JackBoosY commented
Any progress here?

2021-09-10 07:29 UTC, fran6co commented
Might resume work on it in the next weeks, but no promises

2021-09-29 07:38 UTC, NancyLi1013 commented
Need to resolve the conflicts. @fran6co

2021-11-02 02:28 UTC, NancyLi1013 commented
Is work still being done for this PR? @fran6co

2021-11-02 07:22 UTC, fran6co commented
> Is work still being done for this PR? @fran6co

No, I don’t have time to work on it

2021-11-02 08:43 UTC, NancyLi1013 commented
Thanks for your contribution and response. @fran6co 

We're closing this for now since there's been no progress for a long time. If you'd like to continue working on it, please reopen and ping us!

2021-11-02 08:43 UTC, closed without merging

2024-05-23 22:57 UTC, hectorpiteau commented
@fran6co It there a way to help you on this? I know it's been a while but it would be cool to reopen the issue

2024-06-06 02:01 UTC, QiuYilin commented
Is there any progress on this?