[physx] Update to 4.1.2
microsoft/vcpkg pull request #17453
Opened 2021-04-23 00:26 UTC by Hoikas

Update the physx port from 4.1.1 to 4.1.2, removing many patches.

- #### What does your PR fix?  
See above

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No change

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Indeed

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Indeed

2021-04-23 07:33 UTC, JonLiu1993 approved these changes

2021-04-23 17:21 UTC, ras0219-msft requested changes
LGTM once my comment is addressed -- thanks for the PR!

2021-04-23 17:21 UTC, ras0219-msft commented on ports/physx/fix-compiler-flag.patch
> +diff --git a/physx/source/compiler/cmake/android/CMakeLists.txt b/physx/source/compiler/cmake/android/CMakeLists.txt
Could we move these new sections into a separate patch (`remove-werror.patch`)?

2021-04-28 21:45 UTC, ras0219-msft approved these changes

2021-04-28 22:52 UTC, merged

2021-04-28 22:52 UTC, BillyONeal commented
Thanks for your contribution!