[vcpkg baseline][gdk-pixbuf] Fix build error on windows
microsoft/vcpkg pull request #17528
Opened 2021-04-27 07:09 UTC by PhoebeHui

Related to https://github.com/microsoft/vcpkg/pull/17431

Change the function name from 'lrint' to 'opj_lrint' to fix the error C2169.
Reference https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2169?view=msvc-160

Fix the failures:
E:\vcpkg\clean\vcpkg\buildtrees\gdk-pixbuf\src\k-pixbuf-2-c86079bed6\gdk-pixbuf\pixops\../fallback-c89.c(38): error C2169: 'lrint': intrinsic function, cannot be defined

2021-04-27 07:17 UTC, Neumann-A commented
wrong fix the correct fix is to have the check call the function with the correct parameters

2021-04-27 08:39 UTC, PhoebeHui commented
```
Code:
 
        #define lrint meson_disable_define_of_lrint
        
        #include <limits.h>
        #undef lrint
        
        #ifdef __cplusplus
        extern "C"
        #endif
        char lrint (void);
        
        #if defined __stub_lrint || defined __stub___lrint
        fail fail fail this function is not going to work
        #endif
        
        int main(void) {
          return lrint ();
        }
Compiler stdout:
 cl : Command line warning D9030 : '/showIncludes' is incompatible with multiprocessing; ignoring /MP switch
testfile.c
Note: including file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\limits.h
Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\vcruntime.h
Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\sal.h
Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\concurrencysal.h
Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\vadefs.h
E:\vcpkg\clean\vcpkg\buildtrees\gdk-pixbuf\x64-windows-rel\meson-private\tmp0ydnp6qn\testfile.c(10): warning C4391: 'char lrint(void)': incorrect return type for intrinsic function, expected 'long'
E:\vcpkg\clean\vcpkg\buildtrees\gdk-pixbuf\x64-windows-rel\meson-private\tmp0ydnp6qn\testfile.c(10): warning C4392: 'char lrint(void)': incorrect number of arguments for intrinsic function, expected '1' arguments
E:\vcpkg\clean\vcpkg\buildtrees\gdk-pixbuf\x64-windows-rel\meson-private\tmp0ydnp6qn\testfile.c(17): error C2168: 'lrint': too few actual parameters for intrinsic function
```

2021-04-27 08:52 UTC, PhoebeHui commented
Related to upstream issue https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/187.

2021-04-27 09:27 UTC, PhoebeHui commented
@Neumann-A, we don't know how to correct the args, we just replace the functions with check code.

2021-04-27 09:55 UTC, JackBoosY approved these changes

2021-04-27 09:57 UTC, JackBoosY commented
Note this just a workaround to avoid this bug, we need to wait for upstream reply to completely solve this issue.

2021-04-27 09:58 UTC, Neumann-A commented
https://github.com/mesonbuild/meson/issues/8703

2021-04-27 10:02 UTC, Neumann-A commented
> Note this just a workaround to avoid this bug, we need to wait for upstream reply to completely solve this issue.

This also happens with autotools and cmake builds. The only difference is that for those we are able to override the result.

2021-04-27 10:09 UTC, Neumann-A commented
I think the trick is to pass `/Oi-` as an extra compiler argument in the check if msvc is used

2021-04-27 10:36 UTC, PhoebeHui commented
> I think the trick is to pass /Oi- as an extra compiler argument in the check if msvc is used

It seems related to the option https://docs.microsoft.com/en-us/cpp/build/reference/oi-generate-intrinsic-functions?view=msvc-160.

2021-04-27 15:28 UTC, Neumann-A commented
with `if cc.has_function('lrint', dependencies: mathlib_dep, args: '-Oi-')`
```
Running compile:
Working directory:  E:\vcpkg_folders\master\buildtrees\gdk-pixbuf\x64-windows-rel\meson-private\tmpbwbo3a9c
Command line:  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe -INCREMENTAL:NO -I"E:/vcpkg_folders/master/installed/x64-windows/include" E:\vcpkg_folders\master\buildtrees\gdk-pixbuf\x64-windows-rel\meson-private\tmpbwbo3a9c\testfile.c /FeE:\vcpkg_folders\master\buildtrees\gdk-pixbuf\x64-windows-rel\meson-private\tmpbwbo3a9c\output.exe /nologo /showIncludes /MD -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP -MD -O2 -Oi -Gy -DNDEBUG -Z7 /nologo /showIncludes /Od kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib -Oi- /link -machine:x64 -DEBUG -OPT:REF -OPT:ICF /LIBPATH:E:/vcpkg_folders/master/installed/x64-windows/lib 

Code:
 
        #define lrint meson_disable_define_of_lrint
        
        #include <limits.h>
        #undef lrint
        
        #ifdef __cplusplus
        extern "C"
        #endif
        char lrint (void);
        
        #if defined __stub_lrint || defined __stub___lrint
        fail fail fail this function is not going to work
        #endif
        
        int main(void) {
          return lrint ();
        }
Compiler stdout:
 cl : Command line warning D9030 : '/showIncludes' is incompatible with multiprocessing; ignoring /MP switch
testfile.c
Note: including file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\limits.h
Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\vcruntime.h
Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\sal.h
Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\concurrencysal.h
Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\vadefs.h

Compiler stderr:
 cl : Command line warning D9025 : overriding '/O2' with '/Od'
cl : Command line warning D9025 : overriding '/Oi' with '/Oi-'

Checking for function "lrint" with dependency -lm: YES 
```

2021-04-27 15:33 UTC, Neumann-A commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> +
```suggestion
```

2021-04-27 15:33 UTC, Neumann-A commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> +    * Code copied from gdk_pixbuf_new() */
```suggestion
```

2021-04-27 15:35 UTC, Neumann-A commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> ++if cc.has_function('opj_lrint', dependencies: mathlib_dep)
```suggestion
+function_check_args =''
+if cc.get_id() == 'msvc'
+  function_check_args ='-Oi-'
+endif
+if cc.has_function('lrint', dependencies: mathlib_dep, args: function_check_args)
+  gdk_pixbuf_conf.set('HAVE_LRINT', 1)
+endif
```

2021-04-27 15:35 UTC, Neumann-A commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> +@@ -89,7 +89,7 @@ if cc.has_function('round', dependencies: mathlib_dep)
```suggestion
@@ -89,7 +89,11 @@ if cc.has_function('round', dependencies: mathlib_dep)
```

2021-04-27 20:22 UTC, Neumann-A commented
this should be the minimal patch. there is no need to patch `round`
[fix_intrinsic.txt](https://github.com/microsoft/vcpkg/files/6387428/fix_intrinsic.txt)

2021-04-27 21:04 UTC, strega-nil-ms approved these changes

2021-04-27 21:04 UTC, strega-nil-ms commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> ++    name : 'round Support')
```suggestion
+    name : 'round Support', dependencies: mathlib_dep)
```

2021-04-27 21:04 UTC, strega-nil-ms commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> ++    name : 'lrint Support')
```suggestion
+    name : 'lrint Support', dependencies: mathlib_dep)
```

2021-04-28 01:03 UTC, PhoebeHui commented
Thanks @Neumann-A for your help! I applied the minimal patch which pass the option '-Oi' to the check function.

2021-04-28 01:11 UTC, PhoebeHui commented
With minimal patch, it failed on linux platform:

```
In file included from ../src/k-pixbuf-2-330a654e51.clean/gdk-pixbuf/pixops/pixops.c:24:0:
../src/k-pixbuf-2-330a654e51.clean/gdk-pixbuf/pixops/../fallback-c89.c:37:1: error: static declaration of ‘lrint’ follows non-static declaration
 lrint (double x)
 ^~~~~
In file included from /usr/include/features.h:424:0,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/math.h:27,
                 from ../src/k-pixbuf-2-330a654e51.clean/gdk-pixbuf/pixops/pixops.c:21:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:314:1: note: previous declaration of ‘lrint’ was here
 __MATHDECL (long int,lrint,, (_Mdouble_ __x));
 ^
```

2021-04-28 02:18 UTC, PhoebeHui commented
@strega-nil-ms, could you help review and merge this PR?

2021-04-28 02:27 UTC, JackBoosY requested changes

2021-04-28 02:27 UTC, JackBoosY commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> +@@ -89,8 +89,14 @@ if cc.has_function('round', dependencies: mathlib_dep)
function `round` also need it.

2021-04-28 02:39 UTC, JackBoosY commented on ports/gdk-pixbuf/fix_build_error_windows.patch
> +@@ -89,8 +89,14 @@ if cc.has_function('round', dependencies: mathlib_dep)
Curious why round uses `/Oi` to compile successfully.

2021-04-28 02:40 UTC, JackBoosY approved these changes

2021-04-28 19:06 UTC, merged