Fixes and customizations to vcpkg_configure_make
microsoft/vcpkg pull request #17574
Opened 2021-04-29 16:47 UTC by ahmedyarub

**Describe the pull request**

- #### What does your PR fix?  
  Fixes variable name
  Adds the capability to choose the configuration script and disable shared/static flags. These changes are required for OpenSSL build.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-04-29 17:01 UTC, Neumann-A commented on docs/maintainers/vcpkg_configure_make.md
> +    [CONFIG_FILE]
it should be `CONFIGURE_FILE` instead. Also please give further information why this is necessary

2021-04-29 17:04 UTC, ahmedalnuaimi commented on docs/maintainers/vcpkg_configure_make.md
> +    [CONFIG_FILE]
It's required for configuring libraries like OpenSSL where the default file name is Configure and not configure. OpenSSL port modernization is WIP currently.

2021-04-29 17:07 UTC, ahmedyarub commented on docs/maintainers/vcpkg_configure_make.md
> +    [CONFIG_FILE]
It's required for configuring libraries like OpenSSL where the default file name is Configure and not configure. OpenSSL port modernization is WIP currently.

2021-04-29 17:21 UTC, Neumann-A commented
It's required for configuring libraries like OpenSSL where the default file name is Configure and not configure. OpenSSL port modernization is WIP currently.

Even if it is WIP open up a Draft PR and link it so that reviewers have context.

2021-04-29 17:26 UTC, Neumann-A commented
Hmm seems a bit invalid for me since openssl `Configure` is using `#! /usr/bin/env perl` and not a bash script which `vcpkg_configure_make` assumes. I don't know how well it follows autotools rules in this case.

2021-04-29 17:29 UTC, ahmedyarub commented
> Hmm seems a bit invalid for me since openssl `Configure` is using `#! /usr/bin/env perl` and not a bash script which `vcpkg_configure_make` assumes. I don't know how well it follows autotools rules in this case.

So do you propose running the configuration command directly without vcpkg_configure_make()?

2021-04-29 18:04 UTC, ahmedyarub commented
> > It's required for configuring libraries like OpenSSL where the default file name is Configure and not configure. OpenSSL port modernization is WIP currently.
> 
> Even if it is WIP open up a Draft PR and link it so that reviewers have context.

Added to the description.

2021-04-30 14:30 UTC, JackBoosY commented
You should modify the comments in `vcpkg_configure_make.cmake` and regenerate the documentation.

2021-05-04 03:38 UTC, ahmedyarub commented
> You should modify the comments in `vcpkg_configure_make.cmake` and regenerate the documentation.

Done

2021-05-05 14:37 UTC, JackBoosY commented
/azp run

2021-05-06 06:31 UTC, JackBoosY requested changes

2021-05-06 06:31 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_make.cmake
> +        endif()
I think we should use `VCPKG_LIBRARY_LINKAGE` to determine which type should be used, that's suitable for all triplets.
Do you use it in any scene?

2021-05-06 06:33 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_make.cmake
> +        endif()
For those ports that need to be forced to use static construction, you should use the following code:
```
if (VCPKG_HOST_IS_WINDOWS/VCPKG_HOST_IS_LINUX/VCPKG_HOST_IS_OSX)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
```

2021-05-06 14:14 UTC, ahmedyarub commented on scripts/cmake/vcpkg_configure_make.cmake
> +        endif()
@JackBoosY as I mentioned in the description, this was made to accommodate https://github.com/microsoft/vcpkg/pull/17577
The configuration script there does not recognize these parameters. It has its own parameters for choosing between static and dynamic library build.

2021-05-06 14:19 UTC, ahmedyarub commented on scripts/cmake/vcpkg_configure_make.cmake
> +        endif()
In OpenSSL I'll be disabling these flags and adding logic specific to its build scripts.

2021-05-07 02:36 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_make.cmake
> +        endif()
As I said above, I think the best way is add the code I provided.
@Neumann-A What do you think about?

2021-05-09 16:18 UTC, ahmedyarub commented
Closed because depending PR is not valid anymore.

2021-05-09 16:18 UTC, closed without merging