[flashlight-cpu] Update port
microsoft/vcpkg pull request #17643
Opened 2021-05-03 21:05 UTC by jacobkahn

- #### What does your PR fix?  

Updates the port to include the fix to https://github.com/flashlight/flashlight/issues/574.

Also adds a `usage` that resolves incorrect package info being printed post-install (which is as a result of how the ports are named).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

No change to supported triplets

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes

2021-05-04 04:25 UTC, JackBoosY commented on ports/flashlight-cpu/usage
> +The package flashlight-cpu provides CMake targets:
If this port exports its target, this usage information should be displayed automatically.
It is not clear why it needs to be added.

2021-05-04 15:23 UTC, jacobkahn commented on ports/flashlight-cpu/usage
> +The package flashlight-cpu provides CMake targets:
The issue is that the name of the port is flashlight-cpu, whereas the CMake config file that's generated is called flashlightConfig.cmake.

The auto-generated usage message from vcpkg says that the user should use `find_package(flashlight-cpu ...)` - which is wrong - instead of `find_package(flashlight ...)`. See the issue in the original PR description for an example of that confusion.

2021-05-05 11:51 UTC, JackBoosY commented on ports/flashlight-cpu/usage
> +The package flashlight-cpu provides CMake targets:
So I think we should add `vcpkg_fixup_cmake_targets(CONFIG_PATH share/flashlight-cpu TARGET_PATH share/flashlight)` and remove the usage.

2021-05-06 18:57 UTC, jacobkahn commented on ports/flashlight-cpu/usage
> +The package flashlight-cpu provides CMake targets:
Good point. Let me fix this up and test it.

2021-05-07 03:00 UTC, jacobkahn commented on ports/flashlight-cpu/usage
> +The package flashlight-cpu provides CMake targets:
@JackBoosY fixed! Ready for review

2021-05-07 05:44 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

2021-05-10 05:36 UTC, JackBoosY requested changes

2021-05-10 05:36 UTC, JackBoosY commented on versions/f-/flashlight-cpu.json
> +      "git-tree": "8a2fdb6cf5423b0dd078ccaebbddace28ac896e8",
```suggestion
      "git-tree": "63e05566899f6a034fb93cf6556cf3d5ca387f61",
```

2021-05-10 05:36 UTC, JackBoosY approved these changes

2021-05-18 07:32 UTC, merged