[Hedley] Update to v15
microsoft/vcpkg pull request #17675
Opened 2021-05-05 05:43 UTC by pratikpc

**Describe the pull request**

- #### What does your PR fix?  
Updates Hedley to 15

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

2021-05-05 11:46 UTC, JackBoosY requested changes

2021-05-05 11:46 UTC, JackBoosY commented on ports/hedley/vcpkg.json
> +  "description": "A C/C++ header to help move #ifdefs out of your code"
```suggestion
  "description": "A C/C++ header to help move #ifdefs out of your code",
  "homepage": "https://nemequ.github.io/hedley/"
```

2021-05-05 14:21 UTC, pratikpc commented on ports/hedley/vcpkg.json
> +  "description": "A C/C++ header to help move #ifdefs out of your code"
@JackBoosY awesome!

2021-05-06 02:47 UTC, JackBoosY approved these changes

2021-05-06 19:24 UTC, strega-nil-ms commented on ports/hedley/vcpkg.json
> +  "version-string": "15",
```suggestion
  "version": "15",
```

2021-05-06 19:27 UTC, pratikpc commented on ports/hedley/vcpkg.json
> +  "version-string": "15",
@strega-nil-ms you might also have to run vcpkg x-add-one or else it will break

2021-05-07 21:10 UTC, merged

2021-05-08 03:04 UTC, JackBoosY commented
Thanks for this PR!