[asiosdk] Update hash
microsoft/vcpkg pull request #17714
Opened 2021-05-07 08:44 UTC by NancyLi1013

**Describe the pull request**

- #### What does your PR fix?  
  In CI unstable test, asiosdk build failed with wrong hash:

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

```
  File does not have expected hash:

          File path: [ D:/downloads/temp/asiosdk_2.3.3_2019-06-14.zip ]
      Expected hash: [ 65d6f2fa4f0e23939fcdf46ff3b04760089c0f14e2ac3e37e63cbf6733f3acc93ab930ea9e3f1eb60483d4654f7ba4699ed506531074c4f55e763ad92736c231 ]
        Actual hash: [ f73973067502a6d1696372eac57707984d6df57fe0cfc47f74ea73e401f0258c63f72ff9b5a161f61df551c0f1cb3f82d1ea4e8e3e301debc9dcab4c069f07f5 
```
Note: No feature needs to test.

2021-05-08 08:37 UTC, JackBoosY requested changes

2021-05-08 08:37 UTC, JackBoosY commented on ports/asiosdk/portfile.cmake
>      FILENAME "asiosdk_2.3.3_2019-06-14.zip"
```suggestion
    FILENAME "asiosdk_2.3.3_2019-06-14-eac6c1a5.zip"

```

2021-05-08 08:37 UTC, JackBoosY requested changes

2021-05-08 08:37 UTC, JackBoosY commented on ports/asiosdk/portfile.cmake
> +
```suggestion
```

2021-05-08 08:37 UTC, JackBoosY approved these changes

2021-05-08 08:42 UTC, JackBoosY requested changes

2021-05-08 08:42 UTC, JackBoosY commented on ports/asiosdk/portfile.cmake
> +	SHA512 eac6c1a57829b7f722a681c54b2f6469d54695523f08f727d0dd6744dcd7fce4f3249c57689bb15ed7a8bcb912833b226439d800913e122e0ef9ab73672f6542
```suggestion
	SHA512 f73973067502a6d1696372eac57707984d6df57fe0cfc47f74ea73e401f0258c63f72ff9b5a161f61df551c0f1cb3f82d1ea4e8e3e301debc9dcab4c069f07f5
```

2021-05-08 09:06 UTC, JackBoosY approved these changes

2021-05-09 16:28 UTC, merged

2021-05-09 16:28 UTC, strega-nil-ms commented
Thanks nancy!