duilib enable unicode define
microsoft/vcpkg pull request #17745
Opened 2021-05-08 15:14 UTC by w703710691d

if use vcpkg to build duilib, can not use unicode define in CMakeLists.txt where in source code root dir, so add it to DuiLib/CMakeLists.txt

2021-05-09 05:02 UTC, w703710691d commented
fix version file

2021-05-10 02:39 UTC, NancyLi1013 requested changes
Please also update the version in CONTROL file.

Note: Add `Port-Version` and `homepage `field. Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md

2021-05-10 02:39 UTC, NancyLi1013 commented on ports/duilib/portfile.cmake
> +        "enable-unicode-for-vcpkg.patch"
Could you please format this part as follows:

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO duilib/duilib
    REF d7f3a331a0fc6ba48429cd9e5c427570cc73bc35
    SHA512 6381cac467d42e4811859411a5fa620e52075622e8fbec38a6ab320c33bc7d6fdddc809c150d6a10cc40c55a651345bda9387432898d24957b6ab0f5c4b5391c
    HEAD_REF master
    PATCHES 
        "fix-post-build-errors.patch"
        "fix-arm-build.patch"
        "fix-encoding.patch"
        "enable-static.patch"
        "enable-unicode-for-vcpkg.patch"
```

2021-05-10 02:39 UTC, NancyLi1013 commented on ports/duilib/portfile.cmake
Could you please update this

`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/duilib RENAME copyright)`
as
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

2021-05-10 14:00 UTC, w703710691d commented on ports/duilib/portfile.cmake
> +        "enable-unicode-for-vcpkg.patch"
Sorry, I do not found any diffrence :(

2021-05-11 00:53 UTC, NancyLi1013 commented on ports/duilib/portfile.cmake
> +        "enable-unicode-for-vcpkg.patch"
If don't format, like this before:
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO duilib/duilib
	REF d7f3a331a0fc6ba48429cd9e5c427570cc73bc35
	SHA512 6381cac467d42e4811859411a5fa620e52075622e8fbec38a6ab320c33bc7d6fdddc809c150d6a10cc40c55a651345bda9387432898d24957b6ab0f5c4b5391c
    HEAD_REF master
    PATCHES 
        "fix-post-build-errors.patch"
        "fix-arm-build.patch"
        "fix-encoding.patch"
        "enable-static.patch"
        "enable-unicode-for-vcpkg.patch"
```
`REF `and  `SHA512` didn't align left with other arguments.

2021-05-11 00:54 UTC, NancyLi1013 requested changes

2021-05-11 00:54 UTC, NancyLi1013 commented on ports/duilib/CONTROL
> +Port-Version: 0
```suggestion
Version: 2019-4-28
Port-Version: 4
Description: Duilib is a free open source DirectUI interface library under Windows. It is widely accepted by major Internet companies due to its simple and easy to expand design and stable and efficient implementation. It is widely used in IM, video client, stock market software, navigation software, and mobile phone assistive software. Duilib is still evolving, and will continue to improve in many aspects such as documentation, examples, animations, and rendering engines.
```

2021-05-11 01:01 UTC, NancyLi1013 commented
Please run `vcpkg x-add-version duilib` after you address all review suggestions.

2021-05-12 02:55 UTC, NancyLi1013 requested changes

2021-05-12 02:55 UTC, NancyLi1013 commented on ports/duilib/portfile.cmake
>      HEAD_REF master
```suggestion
    REF d7f3a331a0fc6ba48429cd9e5c427570cc73bc35
    SHA512 6381cac467d42e4811859411a5fa620e52075622e8fbec38a6ab320c33bc7d6fdddc809c150d6a10cc40c55a651345bda9387432898d24957b6ab0f5c4b5391c
    HEAD_REF master
```

2021-05-14 13:09 UTC, w703710691d commented
should i have to modify other files?

2021-05-15 06:35 UTC, NancyLi1013 requested changes

2021-05-15 06:35 UTC, NancyLi1013 commented on ports/duilib/CONTROL
> +Port-Version: 4
```suggestion
Port-Version: 3
```
This field should be 3 instead of 4. Since last time it is 2.

2021-05-15 06:35 UTC, NancyLi1013 commented on versions/baseline.json
> +      "port-version": 4
```suggestion
      "port-version": 3
```

2021-05-15 06:35 UTC, NancyLi1013 commented on versions/d-/duilib.json
> +      "port-version": 4
```suggestion
      "port-version": 3
```

2021-05-15 06:36 UTC, NancyLi1013 commented
Except for the `port-version`, others are good for me now.

2021-05-17 13:44 UTC, w703710691d reviewed
[duilib] Enable unicode define

2021-05-18 02:16 UTC, NancyLi1013 approved these changes

2021-05-28 17:15 UTC, strega-nil-ms commented
@w703710691d do you have a reasoning for this? I don't understand why duilib needs to be modified for vcpkg. Do the people behind duilib agree with this change? (@wangchyz?)

2021-05-30 01:58 UTC, w703710691d commented
> @w703710691d do you have a reasoning for this? I don't understand why duilib needs to be modified for vcpkg. Do the people behind duilib agree with this change? (@wangchyz?)

In duilib source, the root CMakeLists.txt has lines "add_definitions(-DUNICODE -D_UNICODE)" and "add_subdirectory(duilib)"。so the final library file use unicode function defines。But vcpkg only use "duilib"  subdirectory,  dosen't include unicode define。So the library file is different from the origin library file

2021-05-30 02:00 UTC, w703710691d commented
> @w703710691d do you have a reasoning for this? I don't understand why duilib needs to be modified for vcpkg. Do the people behind duilib agree with this change? (@wangchyz?)

In duilib source, the root CMakeLists.txt has lines "add_definitions(-DUNICODE -D_UNICODE)" and "add_subdirectory(duilib)"。so the final library file use unicode function defines。But vcpkg only use "duilib" subdirectory, dosen't include unicode define。So the library file is different from the origin library file

2021-07-26 23:42 UTC, merged