[tre, libmagic] Windows + mingw support
microsoft/vcpkg pull request #17769
Opened 2021-05-10 10:01 UTC by longnguyen2004

After a year...

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #11832 
  Also fixes a small bug in `vcpkg_configure_make` where `uuid` isn't removed on mingw triplets.
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Windows + mingw triplets, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-05-10 10:15 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> -        list(TRANSFORM ALL_LIBS_LIST REPLACE "^(${_lprefix})" "")
IIRC this is what I initially proposed in #17137, but it didn't seem to find acceptance.

2021-05-10 10:19 UTC, longnguyen2004 commented on scripts/cmake/vcpkg_configure_make.cmake
> -        list(TRANSFORM ALL_LIBS_LIST REPLACE "^(${_lprefix})" "")
So now we have 2 different approaches to the same problem, let's see which one gets accepted first.
Since on MSVC triplets, `uuid.lib` gets stripped entirely, I'm doing the same with mingw.

2021-05-10 10:28 UTC, longnguyen2004 commented
I can't seem to get the diff artifact, can someone help me?
https://dev.azure.com/vcpkg/public/_build/results?buildId=53405&view=artifacts&pathAsName=false&type=publishedArtifacts

2021-05-10 11:07 UTC, longnguyen2004 commented
Also, now that we have host dependencies, theoretically `libmagic` can be cross compiled as well, but that's for another day.

2021-05-10 11:15 UTC, Neumann-A commented on ports/libmagic/0001-Use-libtre.patch
> ++  AC_CHECK_LIB(tre,tre_regexec,,AC_MSG_ERROR([libtre is required to build file(1) with MinGW]))
`AC_SEARCH_LIBS` instead?

2021-05-10 11:16 UTC, Neumann-A commented on ports/libmagic/0001-Use-libtre.patch
> ++#include <tre/regex.h>
pass `-I"<vcpkginclude>/tre"` instead of patching

2021-05-10 11:17 UTC, Neumann-A commented on ports/libmagic/0002-Change-zlib-lib-name-to-match-CMake-output.patch
> ++  AC_CHECK_LIB(zlib, gzopen)
`AC_SEARCH_LIBS` ! due to debug suffix on windows. Search for `z zlib zlibd`

2021-05-10 15:42 UTC, longnguyen2004 commented on ports/libmagic/0002-Change-zlib-lib-name-to-match-CMake-output.patch
> ++  AC_CHECK_LIB(zlib, gzopen)
We don't have to worry about which one gets found first, since only one will be available in each build.

2021-05-10 17:39 UTC, Neumann-A commented on ports/libmagic/0002-Change-zlib-lib-name-to-match-CMake-output.patch
> ++  AC_CHECK_LIB(zlib, gzopen)
as longnguyen2004 said. This is not cmake where we have to deal with both prefixes/libdirs being visible.

2021-05-10 18:55 UTC, dg0yt commented on ports/libmagic/0002-Change-zlib-lib-name-to-match-CMake-output.patch
> ++  AC_CHECK_LIB(zlib, gzopen)
For z, fair enough. But not in general. This is part of the "gdal completely broken on Linux" story. On Linux, there is always a system path, in addition to the debug path. And generally there is no control about the user environment (manifest mode, registries, overlay ports).

2021-05-11 02:10 UTC, longnguyen2004 commented on ports/libmagic/0002-Change-zlib-lib-name-to-match-CMake-output.patch
> ++  AC_CHECK_LIB(zlib, gzopen)
@dg0yt We can probably uses `-nostdinc`/`-nostdlib` and manually add back in the necessary include and library paths, but that gets tedious fast.

2021-05-11 17:33 UTC, dg0yt commented
> `file` requires a native `file` of the same version to compile the magic file, so we have to add `file` itself as a host dependency (is it possible?)

Maybe a host dependency of a non-core default feature on a non-default feature?

No way to pass the tool path explicitly instead of modifying `PATH`?

2021-05-13 08:13 UTC, JackBoosY requested changes

2021-05-13 08:13 UTC, JackBoosY commented on ports/libmagic/portfile.cmake
> +if(NOT HOST_TRIPLET STREQUAL TARGET_TRIPLET)
```suggestion
if(VCPKG_CROSSCOMPILING)
```

2021-05-13 08:57 UTC, longnguyen2004 commented
@Neumann-A Can you check `x86-windows` and see if there's a workaround?
The build system detects the correct `file`, but `file --version` returns `D:\installed\x64-windows\tools\libmagic\bin\file.exe-5.40` for some reason, while the build expect `file-x.xx`, thus it fails to detect the version.

2021-05-13 09:20 UTC, longnguyen2004 commented on ports/libmagic/portfile.cmake
> +if(NOT HOST_TRIPLET STREQUAL TARGET_TRIPLET)
I'll merge this later, for now I need to find out what's going on with the build process.

2021-05-13 13:28 UTC, Neumann-A commented
> This line only checks for '/' in argv[0], which is not the case on Windows (?)

Yeah probably need to fix that + adding ${EXEEXT} in the Makefile doing the check. 
Also install the magic.mgc file into `tools/libmagic/share/misc` so that the tool automatically picks it up

2021-05-14 05:27 UTC, longnguyen2004 commented
Eh...`git rebase -i` messes everything up :)

2021-05-14 19:05 UTC, strega-nil-ms approved these changes
This looks good to me, just needs a minor change

2021-05-14 21:20 UTC, Neumann-A commented on ports/libmagic/portfile.cmake
> +endif()
Why would I want to run against debug tools in a native build? 
Wouldn't `vcpkg_add_to_path(PREPEND ${CURRENT_HOST_INSTALLED_DIR}/tools/libmagic/bin)` be enough?

2021-05-14 21:20 UTC, Neumann-A commented on ports/libmagic/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug/bin)
Is there a reason to keep the debug tools?

2021-05-14 22:51 UTC, strega-nil-ms commented on ports/libmagic/portfile.cmake
> +endif()
no, because the tools don't exist in `${CURRENT_HOST_INSTALLED_DIR}` yet.

2021-05-15 01:20 UTC, longnguyen2004 commented on ports/libmagic/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug/bin)
Debug-only builds, for instance.

2021-05-15 01:59 UTC, longnguyen2004 commented on ports/libmagic/portfile.cmake
> +endif()
In native builds, after building `file.exe`, it'll use that to compile the magic file. So we need `ADD_BIN_TO_PATH` in order to let it find the correct DLL.

2021-05-15 04:52 UTC, dg0yt commented on ports/libmagic/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug/bin)
Debug-only builds are generally broken for many ports. But did you try this with a release-only build?

2021-05-15 06:10 UTC, longnguyen2004 commented on ports/libmagic/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug/bin)
Not yet, can you test for me? My computer is currently busy.

2021-05-16 13:17 UTC, dg0yt commented on ports/libmagic/portfile.cmake
> +vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug/bin)
> Not yet, can you test for me? My computer is currently busy.

I think it is okay, the function uses globs which should produce nothing in that case.

2021-05-16 13:19 UTC, dg0yt commented
On mingw, the build failed:
~~~
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libmagic.a(compress.o):compress.c:(.text+0xae): undefined reference to `ioctl'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libmagic.a(compress.o):compress.c:(.text+0x108): undefined reference to `__imp_select'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libmagic.a(compress.o):compress.c:(.text+0x12e): undefined reference to `ioctl'
collect2.exe: error: ld returned 1 exit status
~~~

2021-05-16 13:43 UTC, longnguyen2004 commented
@dg0yt Try applying this MSYS2 patch https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-file/0001-file-5.38-mingw-build.patch

2021-05-18 02:03 UTC, longnguyen2004 commented
@dg0yt Is the problem solved?

2021-05-18 05:10 UTC, dg0yt commented
> @dg0yt Is the problem solved?

Yes, mingw build succeeds now. :+1:

2021-05-27 06:43 UTC, longnguyen2004 commented
Now that #17137 is merged, I'll take that fix off of my PR.

2021-05-28 02:22 UTC, JackBoosY approved these changes

2021-05-28 17:09 UTC, strega-nil-ms commented
Alright, great, thanks for the awesome work @longnguyen2004 :)

2021-05-28 17:09 UTC, merged