add the port of bsio library
microsoft/vcpkg pull request #17789
Opened 2021-05-11 03:59 UTC by IronsDu

**Describe the pull request**

- #### What does your PR fix?  
  add new port which name is bsio.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all >, <No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-05-11 09:02 UTC, IronsDu commented
@NancyLi1013 Hi, can you review this pr ? thank you.

2021-05-11 09:16 UTC, NancyLi1013 requested changes

2021-05-11 09:16 UTC, NancyLi1013 commented on ports/bsio/portfile.cmake
> +    REPO IronsDu/bsio
Sorry, I only found `ArkNX/bsio` on GitHub instead of `IronsDu/bsio`. Could you please help clarify this?

2021-05-11 09:16 UTC, NancyLi1013 commented on ports/bsio/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/include/bsio DESTINATION ${CURRENT_PACKAGES_DIR}/include)
I noticed that there is CMakeLists.txt in source code. In this case, we prefer to use `vcpkg_cmake_configure()` and `vcpkg_cmake_install()` to build and install the port instead of install the headers directly.

2021-05-11 09:16 UTC, NancyLi1013 commented on ports/bsio/vcpkg.json
> +  "version-string": "1.0.0",
This might be `version `instead of `version-string`. Please see https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-schemes.

2021-05-11 09:16 UTC, NancyLi1013 commented on ports/bsio/vcpkg.json
> +    "asio"
If we use cmake to build the port, vcpkg-cmake is also needed here.
```
   {
      "name": "vcpkg-cmake",
      "host": true
    }
```

2021-05-11 09:53 UTC, IronsDu commented on ports/bsio/vcpkg.json
> +    "asio"
I think this library don't need CMake.

2021-05-11 09:54 UTC, IronsDu commented on ports/bsio/portfile.cmake
> +    REPO IronsDu/bsio
Must use ArnNX/bsio？

2021-05-11 09:54 UTC, IronsDu commented on ports/bsio/vcpkg.json
> +  "version-string": "1.0.0",
fix it.

2021-05-12 02:31 UTC, JackBoosY commented on ports/bsio/vcpkg.json
> +    "asio"
Using cmake can avoid installing the header files in the wrong folder, and can install documentation, usage or other files through it.
If cmake configuration files(bsio-config.cmake/bsio-targets.cmake) can be exported in cmake, we can also have them through CMakeLists.txt.
So I think it is appropriate.

2021-05-12 02:59 UTC, IronsDu commented on ports/bsio/portfile.cmake
> +    REPO IronsDu/bsio
initially, bsio is my repo, the after, i donate it to ArkNX. so it `IronsDu/bsio` moved to `ArkNX/bsio`. but we can visit `IronsDu/bsio` still yet.

Of cause, i can use ArkNX/bsio.  
Now, already fix it. ^_^.

2021-05-12 03:10 UTC, IronsDu commented on ports/bsio/vcpkg.json
> +    "asio"
got it, thank you.

2021-05-12 04:01 UTC, IronsDu commented on ports/bsio/vcpkg.json
> +    "asio"
fix.  how to retry the CI ?

2021-05-12 05:41 UTC, JackBoosY commented
Please run `./vcpkg format-manifest --all` then commit changes.

2021-05-12 05:53 UTC, NancyLi1013 requested changes

2021-05-12 05:53 UTC, NancyLi1013 commented on ports/bsio/portfile.cmake
> +)
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -Dbsio_BUILD_EXAMPLES=OFF
)
```

2021-05-12 05:53 UTC, NancyLi1013 commented on ports/bsio/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/include/bsio DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```suggestion
```
This line is no longer needed here. Since cmake has done this in CMakeLists.txt.
https://github.com/ArkNX/bsio/blob/master/CMakeLists.txt#L15

2021-05-12 05:53 UTC, NancyLi1013 commented on ports/bsio/vcpkg.json
> +  "homepage": "https://github.com/IronsDu/bsio",
```suggestion
  "homepage": "https://github.com/ArkNX/bsio",
```

2021-05-12 06:25 UTC, IronsDu commented on ports/bsio/vcpkg.json
> +  "homepage": "https://github.com/IronsDu/bsio",
already fix.

2021-05-12 06:25 UTC, IronsDu commented on ports/bsio/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/include/bsio DESTINATION ${CURRENT_PACKAGES_DIR}/include)
already fix.

2021-05-12 06:25 UTC, IronsDu commented on ports/bsio/portfile.cmake
> +)
already fix.

2021-05-12 09:14 UTC, NancyLi1013 commented on ports/bsio/portfile.cmake
> +)
Please see the format. it is the same as before.

2021-05-12 10:24 UTC, NancyLi1013 approved these changes

2021-05-13 02:08 UTC, NancyLi1013 commented
LGTM now, thanks for adding this new port @IronsDu.

2021-05-13 02:13 UTC, IronsDu commented
thank you @JackBoosY @NancyLi1013  review my PR.

2021-05-13 18:07 UTC, merged

2021-05-14 00:26 UTC, IronsDu commented
@JackBoosY can you add my weixin: 158..82..12608.9