[yomm2] new port
microsoft/vcpkg pull request #17886
Opened 2021-05-12 15:20 UTC by FabienPean

Add new port for library [yomm2](https://github.com/jll63/yomm2). Note that dependency of Boost libs are not resolved properly (#17882 #17848)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Normally all, waiting for CI

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-05-13 02:57 UTC, JackBoosY commented
Please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=53530&view=artifacts&pathAsName=false&type=publishedArtifacts).

2021-05-13 03:47 UTC, strega-nil-ms commented
/azp run

2021-05-13 08:09 UTC, JackBoosY requested changes

2021-05-13 08:09 UTC, JackBoosY commented on ports/yomm2/vcpkg.json
> +    "boost-type-traits"
```
[1/3] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\cl.exe   /TP  -ID:\buildtrees\yomm2\src\v1.1.2-556c088e4c.clean\include -ID:\installed\x64-windows\include /std:c++17 -D_SCL_SECURE_NO_WARNINGS /EHsc /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\yomm2.dir\yomm2.cpp.obj /Fdsrc\CMakeFiles\yomm2.dir\yomm2.pdb /FS -c D:\buildtrees\yomm2\src\v1.1.2-556c088e4c.clean\src\yomm2.cpp
FAILED: src/CMakeFiles/yomm2.dir/yomm2.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\cl.exe   /TP  -ID:\buildtrees\yomm2\src\v1.1.2-556c088e4c.clean\include -ID:\installed\x64-windows\include /std:c++17 -D_SCL_SECURE_NO_WARNINGS /EHsc /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\yomm2.dir\yomm2.cpp.obj /Fdsrc\CMakeFiles\yomm2.dir\yomm2.pdb /FS -c D:\buildtrees\yomm2\src\v1.1.2-556c088e4c.clean\src\yomm2.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\installed\x64-windows\include\boost/dynamic_bitset/detail/lowest_bit.hpp(17): fatal error C1083: Cannot open include file: 'boost/integer/integer_log2.hpp': No such file or directory
ninja: build stopped: subcommand failed.
```
Also need to depend on `boost-dynamic-bitset`.

2021-05-13 16:02 UTC, FabienPean commented on ports/yomm2/vcpkg.json
> +    "boost-type-traits"
The problem comes from boost ports not resolving their own dependencies properly, see #17882 and #17848. Initially I just added the dependencies required by yomm2 in `vcpkg.json`. Now I added the minimum amount of dependencies needed for the port to compile successfully. Let's see the result of the CI.

2021-05-13 16:10 UTC, FabienPean commented
Note that dependency to `boost-integer` and `boost-move` are only required because of `boost-dynamic-bitset` and should be removed from this port when #17882 is resolved.

2021-05-18 09:42 UTC, FabienPean commented
I added a patch to fix uwp and osx build in vcpkg. This should be removed in the next version of yomm2 thanks to an update of the CMakeLists of the lib. The CI does not crash anymore on this port, so I think it is ready for review.

2021-05-18 09:43 UTC, JackBoosY commented
Depends on https://github.com/microsoft/vcpkg/pull/17983.

2021-05-20 02:29 UTC, JackBoosY commented
/azp run

2021-05-20 02:51 UTC, JackBoosY approved these changes

2021-05-24 23:26 UTC, ras0219-msft approved these changes
Thanks for the PR! This LGTM once my comment has been addressed.

2021-05-24 23:26 UTC, ras0219-msft commented on ports/yomm2/vcpkg.json
> +  "supports": "(x64 | arm64) & (linux | osx | windows)",
```suggestion
  "supports": "x64 | arm64",
```

2021-05-24 23:26 UTC, ras0219-msft commented on ports/yomm2/vcpkg.json
> +  "supports": "(x64 | arm64) & (linux | osx | windows)",
vcpkg tries to be as optimistic as possible, so there's no need to require linux/osx/windows.

2021-05-25 12:53 UTC, FabienPean commented on ports/yomm2/vcpkg.json
> +  "supports": "(x64 | arm64) & (linux | osx | windows)",
Actually the CI passed for everything, so I simply removed the line. I guess this should mean it applies for everything by default if I understood correctly.

2021-05-26 05:50 UTC, JackBoosY approved these changes

2021-05-26 17:33 UTC, merged

2021-05-26 17:33 UTC, ras0219-msft commented
Thanks for the quick response!