[getopt-win32] fix static builds
microsoft/vcpkg pull request #17942
Opened 2021-05-14 19:59 UTC by Neumann-A

2021-05-15 02:33 UTC, JackBoosY commented
```
Building package getopt-win32[core]:x64-windows-static...
-- Note: getopt-win32 only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:47 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/getopt-win32/portfile.cmake:5 (vcpkg_check_linkage)
  scripts/ports.cmake:142 (include)
```

2021-05-18 02:14 UTC, JackBoosY requested changes
I wish `ConfigurationType` and `RuntimeLibrary` can be set as a option for `vcpkg_install_msbuild` or `vcpkg_build_msbuild`.

2021-05-18 02:14 UTC, JackBoosY commented on ports/getopt-win32/portfile.cmake
> +file(WRITE "${_file}" "${_contents}")
```suggestion
if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
    vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/getopt.h"
        "	#define __GETOPT_H_" "	#define __GETOPT_H_\n	#define STATIC_GETOPT"
    )
endif()
```

2021-05-18 09:31 UTC, JackBoosY commented
Depends on https://github.com/microsoft/vcpkg/pull/17983.

2021-05-20 02:33 UTC, JackBoosY approved these changes

2021-05-20 19:56 UTC, Neumann-A commented
@JackBoosY Why did you mark this as requires discussion?

2021-05-21 02:24 UTC, JackBoosY commented
I hope my colleague will do further review.

2021-05-21 07:50 UTC, merged