[gnutls] Add Windows support
microsoft/vcpkg pull request #18029
Opened 2021-05-20 17:54 UTC by wrobelda

**Describe the pull request**

- #### What does your PR fix?  
  Adds support for Windows build for gnutls. Depends on #16953 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>
   I am still working on this PR

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
   I am still working on this PR

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
 I am still working on this PR

2021-05-20 19:03 UTC, dg0yt commented
I would prefer when one port would use only one particular set of sources and patches, so that I can build for different target triplets without worrying about the state of the port's sources in the buildtrees folder.
(I know it is only a draft at this point.)

2021-05-20 19:24 UTC, wrobelda commented
I'm sorry, I am not sure what you expect here. All of the portfiles which use ShiftMediaProject forks to provide Windows support behave like this.

2021-05-20 19:46 UTC, dg0yt commented
I know that a lot of ports do different patching for different triplet, but this is the first time I note different sources.
- What is going to happen when I want to cross-build for Android from the same vcpkg root?
- If I need to collect the sources, am I expected to collect it separately for each triplet (read: `vcpkg --download-only`)?

2021-05-20 19:58 UTC, wrobelda commented
> I know that a lot of ports do different patching for different triplet, but this is the first time I note different sources.

See e.g. gmp, nettle for comparison.

> * What is going to happen when I want to cross-build for Android from the same vcpkg root?

I am not sure I follow, again. Sources are downloaded into separate folders with unique names, usually consisting of a version/revision number and a hash sum. Since sources for Windows and *nix are different in those portfiles, they get be downloaded into separate folders and patches will be applied respectively. This behavior is no different than when building a different port version on demand.

2021-05-20 20:24 UTC, dg0yt commented
> Sources are downloaded into separate folders with unique names, usually consisting of a version/revision number and a hash sum.

I see, and you refering to unpacking indeed. So I only need to worry about some patches which are not applied uniformly.

Anyway, I find it confusing to have different sources. I admit I'm biased, with experience in building RPMS and DEBs.

2021-05-20 20:36 UTC, wrobelda commented
> So I only need to worry about some patches which are not applied uniformly.

I don't think there's anything to worry at all. Those Windows-specific patches will only be applied on top of ShiftMediaProject source code, which, in turn, is only used for Windows build.

> Anyway, I find it confusing to have different sources. I admit I'm biased, with experience in building RPMS and DEBs.

These are definitely exceptions. ShiftMediaProject has whole bunch of MSVC-compatible forks, which are very convenient to use. I even discussed a possibility of pushing those changed upstream, but as you can imagine, it's a voluntary work on all ends:

https://github.com/ShiftMediaProject/gnutls/issues/13#issuecomment-809224478

2021-05-26 05:28 UTC, dg0yt commented on ports/libgnutls/pkgconfig.patch
> ++Libs: -L${libdir} @LIBS@
Did you verify the pc file outside windows? I'm curious what is expected to appear here for LIBS. As an input variable to `configure`, it has a different meaning.
And in a quick local test with just this change, I got an empty substitution on linux.

2021-06-03 20:52 UTC, wrobelda commented on ports/libgnutls/portfile.cmake
> +endif()
This is a WIP, I sometimes make some quick fixes using `nano` (which somehow ignores my EOF newline settings). The final file will be free of such formatting issues.

2021-06-04 05:55 UTC, NancyLi1013 requested changes

2021-06-04 05:55 UTC, NancyLi1013 commented on ports/libgnutls/portfile.cmake
> +        URLS "https://www.gnupg.org/ftp/gcrypt/gnutls/v${PACKAGE_VERSION_MAJOR}.{PACKAGE_VERSION_MINOR}/gnutls-${PACKAGE_VERSION}.tar.xz"
```suggestion
        URLS "https://www.gnupg.org/ftp/gcrypt/gnutls/v${PACKAGE_VERSION_MAJOR}.${PACKAGE_VERSION_MINOR}/gnutls-${PACKAGE_VERSION}.tar.xz"
```

2021-06-04 05:58 UTC, NancyLi1013 commented
```
-- Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.{PACKAGE_VERSION_MINOR}/gnutls-3.6.15.tar.xz -> gnutls-3.6.15.tar.xz...
-- Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.{PACKAGE_VERSION_MINOR}/gnutls-3.6.15.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):
      
      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:
```
`{PACKAGE_VERSION_MINOR} `should be `${{PACKAGE_VERSION_MINOR}}`.

I have a question here, why do you use different repo in different platforms? Also I noticed there was a new version 3.16.6. Why do you not use the latest?

2021-06-04 06:00 UTC, NancyLi1013 commented
Please ping me if this is ready for review. @wrobelda

2021-09-29 07:46 UTC, NancyLi1013 commented
Hi @wrobelda Is work still being done for this PR? Seems there is no any progress for a long time.

2021-09-29 09:13 UTC, wrobelda commented
> Hi @wrobelda Is work still being done for this PR? Seems there is no any progress for a long time.

I am going to return to it as soon as all of my `kf5*` ports are merged.

2021-09-30 21:27 UTC, wrobelda commented on ports/libgnutls/pkgconfig.patch
> ++Libs: -L${libdir} @LIBS@
Good call, replaced it with something less ambiguous.

2021-10-06 22:57 UTC, wrobelda commented
> I have a question here, why do you use different repo in different platforms? Also I noticed there was a new version 3.16.6. 

This was already discussed above. It is a similar approach to `gmp`, `nettle` or `libgcrypt` port. ShiftMediaProject provide forks for each of those which allow for a much easier compilation under Windows. 

> Why do you not use the latest?

See: https://github.com/ShiftMediaProject/gnutls/issues/13#issuecomment-937294630

2021-10-07 08:00 UTC, Neumann-A commented
I would really like to see somebody figure out how to use `vcpkg_configure_make` with asm files on windows. Then we wouldn't need the SMP fork and compiler flags of toolchains would be correctly forwared for these ports.

2021-10-08 07:24 UTC, NancyLi1013 submitted a review, later dismissed

2022-03-08 22:44 UTC, elibroftw commented on ports/libgnutls/portfile.cmake
> +        REPO ShiftMediaProject/gnutls
> To paraphrase @ras0219 / @ras0219-msft (we talked about this in person yesterday), just because we have previously used a fork to provide something, doesn't mean that we want to blindly use that fork for everything in the future. If we can get the upstream build system to work, we want to use that. I am told that the main thing ShiftMediaProject does for us is add Visual Studio projects to things, but VS projects are a relatively poor experience in vcpkg because MSBuild has no handling of transitive dependencies, etc., so we actually would prefer to run the upstream non-forked autoconf wherever possible.

So then how are windows users supposed to use libgcrypt on windows via vcpkg? Vcpkg is supposed to solve headaches, not be the source of truth moderator!

2022-03-08 23:41 UTC, BillyONeal commented on ports/libgnutls/portfile.cmake
> +        REPO ShiftMediaProject/gnutls
> So then how are windows users supposed to use libgcrypt on windows via vcpkg? Vcpkg is supposed to solve headaches, not be the source of truth moderator!

The problem is that for people using vcpkg, it *is* a source of truth. Nobody is going to dig into the portfile and find out that instead of what they think is the real thing is provided by some fork. For example, if there is a vulnerability fixed in the real project's package that isn't picked up by the fork quickly, folks could be left without a path forward. Elevating a fork to the level of trust of the original project must be done extremely sparingly, on a case by case basis, only after a good faith showing that the fork tracks what upstream is doing very closely. *Especially* with crypto stuff where introducing bugs that look benign but break the security of the cryptosystem is relatively easy to do.

If this were trying to add shiftmedia-gnutls or something like that, that could be fine, because it wouldn't be advertising something that it is not.

2022-03-08 23:45 UTC, elibroftw commented on ports/libgnutls/portfile.cmake
> +        REPO ShiftMediaProject/gnutls
I'm fine with not including it under the same name because that's mixing sources but at least add it under a different name. That way users can install the fork via vcpkg but still include it in their source code without requiring copy pasting sources.

2022-03-09 00:10 UTC, wrobelda commented on ports/libgnutls/portfile.cmake
> +        REPO ShiftMediaProject/gnutls
> If this were trying to add shiftmedia-gnutls or something like that, that could be fine, because it wouldn't be advertising something that it is not.

Frankly speaking, I did not think this was even an option, especially that nettle, a cryptographic library on its own, uses the shift media fork as well. It would at the very least be nice to have some consistency in vcpkg's approach here.

2022-03-09 00:33 UTC, BillyONeal commented on ports/libgnutls/portfile.cmake
> +        REPO ShiftMediaProject/gnutls
>Frankly speaking, I did not think this was even an option, especially that a port for nettle, a cryptographic library on its own, uses the shiftmedia fork as well. It would be nice to have some consistency in vcpkg's Microsoft's approach here.

Unfortunate consequence of having way more incoming PRs than a single person can reasonably review is that we don't always have the same read on a situation. I don't think we would accept https://github.com/microsoft/vcpkg/pull/10613 today for the same reasons enumerated above. But that decision was made before I had a true understanding of being a vcpkg maintainer. :/

2022-03-12 20:40 UTC, Neumann-A commented
If you update to 3.7.3 you can simply run `vcpkg_configure_make` with `USE_WRAPPERS` and configure will pass. The next step would be to solve the build issues due to some dirent types. Maybe something from the SMP patches can be reused.

2022-08-15 23:37 UTC, wrobelda commented
@NancyLi1013 I renamed this port to reflect the fact that it uses a SMP fork of gnutls, as [suggested](https://github.com/microsoft/vcpkg/pull/18029#discussion_r822167313) by @BillyONeal. While there is a possibility to build it natively, as in turn [suggested](https://github.com/microsoft/vcpkg/pull/18029#issuecomment-1065959145) by @Neumann-A, this gets GnuTLS across for Windows, and it being an important library, I think it's worth having for the time being, until the native build is sorted out.

2022-08-17 09:21 UTC, JackBoosY requested changes

2022-08-17 09:21 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/portfile.cmake
> +include("${CURRENT_INSTALLED_DIR}/share/yasm-tool-helper/yasm-tool-helper.cmake")
You may not need to include this.

2022-08-17 09:21 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/portfile.cmake
> +    OPTIONS_RELEASE /p:RuntimeLibrary=MultiThreaded${RuntimeLibraryExt}
This only for static CRT linkage, right?

2022-08-17 09:21 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/portfile.cmake
> +file(RENAME "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" "${CURRENT_PACKAGES_DIR}/include")
I think you shouldn't touch the buidtrees here, just glob it and install them.

2022-08-17 09:21 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/runtime.patch
> +diff --git a/SMP/libgnutls.vcxproj b/SMP/libgnutls.vcxproj
You may not need this patch if there is no other `RuntimeLibrary` setting since `vcpkg_install_msbuild` can handle them.

2022-08-17 09:21 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/external-libtasn1.patch
> +-    <ClCompile Include="..\devel\libtasn1\lib\coding.c">
Why deleted these sources?

2022-08-17 09:49 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +file(RENAME "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" "${CURRENT_PACKAGES_DIR}/include")
This is required since the `.vcxproj` use relative path everywhere, assuming the (IIRC) the build to be in some  `build\out` folder, which is not the case. This is also how the original GMP or Nettle ports used to do this, when they used SMP for building on Windows.

2022-08-17 09:51 UTC, wrobelda commented on ports/shiftmedia-libgnutls/external-libtasn1.patch
> +-    <ClCompile Include="..\devel\libtasn1\lib\coding.c">
`libtasn1` is provided externally

2022-08-17 09:51 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +    OPTIONS_RELEASE /p:RuntimeLibrary=MultiThreaded${RuntimeLibraryExt}
Correct

2022-08-17 09:52 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +include("${CURRENT_INSTALLED_DIR}/share/yasm-tool-helper/yasm-tool-helper.cmake")
This was a copy'n'paste from other ports that used yasm for SMP forks, I'll check if it's still needed.

2022-08-17 09:55 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/portfile.cmake
> +file(RENAME "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" "${CURRENT_PACKAGES_DIR}/include")
Please note that this place is after the build. In my opinion, we shouldn't touch the binary path such as _${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel_ here since the install function may delete this path automaticly after build.

2022-08-17 09:55 UTC, wrobelda commented on ports/shiftmedia-libgnutls/runtime.patch
> +diff --git a/SMP/libgnutls.vcxproj b/SMP/libgnutls.vcxproj
if I remember correctly the `/p:RuntimeLibrary` passed to `vcpkg_install_msbuild` didn't work without this, but this port was originally written a year ago, so let me check again.

2022-08-17 09:57 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/portfile.cmake
> +    OPTIONS_RELEASE /p:RuntimeLibrary=MultiThreaded${RuntimeLibraryExt}
So I think you may need to do 2 things:
1. add extra supports field `& staticcrt` on `vcpkg.json`.
2. Remove patch `runtime.patch`.

2022-08-17 10:05 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +include("${CURRENT_INSTALLED_DIR}/share/yasm-tool-helper/yasm-tool-helper.cmake")
```
CMake Error at ports/shiftmedia-libgnutls/portfile.cmake:39 (yasm_tool_helper):
  Unknown CMake command "yasm_tool_helper".
```

2022-08-17 10:13 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +file(RENAME "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" "${CURRENT_PACKAGES_DIR}/include")
Ah, indeed, was speaking from the memory. Let me look into that.

2022-08-17 10:14 UTC, wrobelda commented on ports/shiftmedia-libgnutls/runtime.patch
> +diff --git a/SMP/libgnutls.vcxproj b/SMP/libgnutls.vcxproj
Well, it doesn't work without it:

```
-- Performing post-build validation
Invalid crt linkage. Expected Debug,Static, but the following libs had:

    D:\packages\shiftmedia-libgnutls_x64-windows-static\debug\lib\libgnutlsd.lib: Debug,Dynamic
```

See the CI build results below for details.

2022-08-17 10:32 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +    OPTIONS_RELEASE /p:RuntimeLibrary=MultiThreaded${RuntimeLibraryExt}
Regarding 1., frankly speaking, I don't understand why? CI builds both `static` and `staticcrt` configurations as is, with `(windows | uwp)` only. And since both are supported, why add `& staticrt` explicitly? This would limit CI to `staticcrt` only and exclude `static`. Or am I missing something?

Regarding 2., see your comment below.

2022-08-17 10:41 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +file(RENAME "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" "${CURRENT_PACKAGES_DIR}/include")
Fixed.

2022-08-18 17:47 UTC, wrobelda commented
@JackBoosY for the most recent commits and the `vcpkg_replace_string()` usage, see the discussion here: https://github.com/microsoft/vcpkg/pull/26364#discussion_r948525288

2022-08-19 06:22 UTC, JackBoosY commented
Can you please resolve the file confict?

2022-08-19 06:24 UTC, JackBoosY commented on ports/shiftmedia-libgnutls/portfile.cmake
> +    OPTIONS_RELEASE /p:RuntimeLibrary=MultiThreaded${RuntimeLibraryExt}
Ah I forgot the extenstion `RuntimeLibraryExt`.

2022-08-19 06:39 UTC, wrobelda commented
> Can you please resolve the file confict?

@JackBoosY Done

2022-08-19 07:21 UTC, JackBoosY approved these changes, later dismissed

2022-08-19 22:47 UTC, JavierMatosD commented
@wrobelda would you mind explaining why this is using different repos for different platforms?

2022-08-19 22:51 UTC, wrobelda commented
> @wrobelda would you mind explaining why this is using different repos for different platforms?

This has been discussed extensively with previous uses of SMP forks. See for example the discussion for a previous PR for gnutls, which at the time was meant to do the same, albeit under a single `gnutls` port name: https://github.com/microsoft/vcpkg/pull/18029#discussion_r822167313

The reason is that GnuPG's autotools scripting is complicated, with their custom additional tools and header generation — see e.g. https://github.com/microsoft/vcpkg/discussions/20755

SMP fork dumbs down GnuPG libraries for MSVC/MSBuild usage, and while it's not perfect, it gets the job done for the time being.

2022-08-19 22:55 UTC, wrobelda commented
Also see https://github.com/microsoft/vcpkg/pull/26364, which was merged in yesterday

2022-08-19 23:10 UTC, BillyONeal commented
> Also see #26364, which was merged in yesterday

That doesn't try to fetch from multiple repos though.

2022-08-19 23:12 UTC, BillyONeal commented
To clarify, @JavierMatosD is asking about that we're downloading sources on line 8 and line 21 in portfile.cmake which makes what we are actually packaging here unclear (at least, to the two of us). The comment isn't about the use of the shiftmedia fork(s) in the first place which you have already addressed by changing the port's name.

2022-08-20 07:24 UTC, wrobelda commented
Oh, the other file is gnulib, not gnutls, and is a requirement for compilation of the latter.

2022-08-24 08:25 UTC, wrobelda commented
@JavierMatosD is that response satisfactory?

2022-08-26 20:56 UTC, BillyONeal commented
> Oh, the other file is gnulib, not gnutls, and is a requirement for compilation of the latter.

It seems like that should be a separate port? (It looks like an independent thing...)

2022-08-29 10:58 UTC, wrobelda commented
> It seems like that should be a separate port? (It looks like an independent thing...)

It actually isn't. The SMP fork relies on bunch of code from Gnulib which are directly referenced by their VS project files, see: https://github.com/ShiftMediaProject/gnutls/blob/master/SMP/libgnutls_files.props

They don't ship that code, though — they provide a script that populates the `gnulib/` subfolder using upstream code: 
https://github.com/ShiftMediaProject/gnutls/blob/master/bootstrap
Also see: https://github.com/ShiftMediaProject/gnutls/blob/master/SMP/readme.txt

What I am merely doing here is exactly that: populating that folder with the code it expects. The original `gnulib/` subfolder is a git submodule, which is why I am extracting the gnulib source into it. 

Obviously this still doesn't mean `gnulib` couldn't be built as a library independently, but that's _way_ more complex and I vividly remember the discussion around it from a while back on why it hasn't made it to vcpkg yet...

2022-08-29 16:06 UTC, BillyONeal submitted a review, later dismissed
This approval is contingent on:

* Another vcpkg maintainer signing off on the multiple-upstreams thing
* The 'supports' expression being fixed.
* The additional quotes in `file(RENAME` added.

All other review comments are nitpicks.

Thanks for your contribution!

2022-08-29 16:06 UTC, BillyONeal commented on ports/shiftmedia-libgnutls/vcpkg.json
> +  "supports": "windows | uwp",
```suggestion
  "supports": "windows",
```

uwp implies windows.

2022-08-29 16:06 UTC, BillyONeal commented on ports/shiftmedia-libgnutls/vcpkg.json
> +    "yasm-tool-helper",
These two should probably be host dependencies, although I acknowledge that other callers aren't right now.

2022-08-29 19:24 UTC, wrobelda commented on ports/shiftmedia-libgnutls/portfile.cmake
> +    OPTIONS /p:YasmPath="${YASM}" /p:OutDir=..\\msvc
I agree. Eventually I hope we can get a vanilla version of this to compile with clang-cl, similarly to the ongoing #26424.

2022-08-29 19:53 UTC, wrobelda commented on ports/shiftmedia-libgnutls/vcpkg.json
> +    "yasm-tool-helper",
Indeed, fixed.

2022-08-29 19:55 UTC, wrobelda commented
> This approval is contingent on:
> 
> * Another vcpkg maintainer signing off on the multiple-upstreams thing

To be fair, this is only required because `vcpkg_from_github()` is not currently able to download from git modules.

2022-09-02 21:30 UTC, merged

2022-09-02 21:30 UTC, BillyONeal commented
Thanks!