[hunspell] Fix build error on Windows
microsoft/vcpkg pull request #18037
Opened 2021-05-21 02:46 UTC by NancyLi1013

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #17781

Update to use MSBuild instead of Make to build this port on Windows.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]arm64-windows
arm64-windows and arm-uwp are not supported.

Note: Feature[tools] has passed with the following triplets:

- x86-windows
- x64-windows
- x64-windows-static

2021-05-21 05:52 UTC, NancyLi1013 commented on ports/hunspell/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS OR NOT VCPKG_TARGET_IS_MINGW)
```suggestion
if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
```

2021-05-31 09:51 UTC, JackBoosY requested changes

2021-05-31 09:51 UTC, JackBoosY commented on ports/hunspell/vcpkg.json
>    "port-version": 3,
```suggestion
  "port-version": 4,
```
```suggestion
  "port-version": 3,
```

2021-06-01 02:02 UTC, JackBoosY approved these changes

2021-06-09 22:28 UTC, strega-nil-ms commented
Cool, thanks @NancyLi1013 :)

2021-06-09 22:28 UTC, merged