[vcpkg.cmake] Cleanup every special cases in the find_package override
microsoft/vcpkg pull request #18047
Opened 2021-05-21 10:00 UTC by Neumann-A

and replace it with appropriate `vcpkg-cmake-wrappers.cmake`.

CI will run due to adding the wrappers or changing the portfile of the affected base ports

2021-05-21 13:02 UTC, Osyotr commented on ports/gsl/vcpkg-cmake-wrapper.cmake
> +if(GSL_FOUND AND TARGET GSL::gsl)
Missing endif()?

2021-05-24 07:23 UTC, JackBoosY requested changes

2021-05-24 07:23 UTC, JackBoosY commented on ports/boost-uninstall/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake" "${CURRENT_PACKAGES_DIR}/share/boost/vcpkg-cmake-wrapper.cmake" @ONLY)
This port is only used to recursively uninstall boost, so I think we don't need to add a wrapper here.\
So should we move it to `boost-core` or `boost-build` or `boost-modular-build-helper`?

2021-05-24 08:07 UTC, Neumann-A commented on ports/boost-uninstall/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake" "${CURRENT_PACKAGES_DIR}/share/boost/vcpkg-cmake-wrapper.cmake" @ONLY)
`boost-modular-build-helper` should be a host dependency as it seems so it is out
`boost-build` is also a host dependency and not all of boost depends in it, so it is out 
`boost-vcpkg-helpers` is only for headers boost libs?

`boost-core` hmm could be a possibility but, does it cover everything in boost?

`boost-uninstall` covers the following helper scripts, so for me it looks like the correct port currently unless `boost-core` is just as powerful? 
```
boost-build
boost-modular-build-helper
boost-vcpkg-helpers
```

2021-05-24 09:36 UTC, JackBoosY commented on ports/boost-uninstall/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake" "${CURRENT_PACKAGES_DIR}/share/boost/vcpkg-cmake-wrapper.cmake" @ONLY)
Maybe we should add a new port `boost-wrapper`?

2021-05-24 10:30 UTC, Neumann-A commented on ports/boost-uninstall/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake" "${CURRENT_PACKAGES_DIR}/share/boost/vcpkg-cmake-wrapper.cmake" @ONLY)
another one? I don't think so.... Maybe ask the person responsible for the boost ports where to put the wrapper

2021-05-24 19:10 UTC, ras0219-msft requested changes
Thanks for the PR, this is really great and much appreciated!

I think using `boost-uninstall` is fine for this; the naming isn't perfect but the semantics are correct.

Unfortunately, we can't remove the direct hacks inside `vcpkg.cmake` because existing users of older versions currently rely on them. For example, if someone has a version baseline from the current master and uses boost, removing the lines from `vcpkg.cmake` would suddenly break them when they next `git pull`.

Without removing those lines, this LGTM. I think it's still worth doing to move us to a cleaner world.

2021-05-24 19:10 UTC, ras0219-msft commented on scripts/buildsystems/vcpkg.cmake
> -    elseif("${PACKAGE_NAME}" STREQUAL "Boost" AND EXISTS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/boost")
These need to stick around since removing them would break users continuing to use the old ports.

2021-05-24 19:31 UTC, Neumann-A commented on scripts/buildsystems/vcpkg.cmake
> -    elseif("${PACKAGE_NAME}" STREQUAL "Boost" AND EXISTS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/boost")
done. But i still want them gone because they are visible in --trace everytime the toolchain is loaded. 
maybe have a `vcpkg-(v2|no-old-stuff|clean|minimal).cmake` at some time in the feature. 
Especially in manifest mode all ports get rebuild anyway. Only people using classic mode would be affected.

2021-05-25 01:26 UTC, JackBoosY commented
Can you please resolve the file conflict?

2021-05-26 06:47 UTC, JackBoosY approved these changes

2021-05-28 17:00 UTC, strega-nil-ms commented
This looks great to me! Thanks @Neumann-A :)

2021-05-28 17:00 UTC, merged

2021-12-07 09:45 UTC, JonLiu1993 commented
@Neumann-A 
Today when I do some work with `highfivex:64-windows-static`, I met some errors related to boost-test:
```
FAILED: tests/unit/tests_high_five_base.exe 
cmd.exe /C "cd . && F:\test8\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=tests\unit\CMakeFiles\tests_high_five_base.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  tests\unit\CMakeFiles\tests_high_five_base.dir\tests_high_five_base.cpp.obj  /out:tests\unit\tests_high_five_base.exe /implib:tests\unit\tests_high_five_base.lib /pdb:tests\unit\tests_high_five_base.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  F:\test8\vcpkg\installed\x64-windows-static\debug\lib\boost_unit_test_framework-vc140-mt-gd.lib  F:\test8\vcpkg\installed\x64-windows-static\debug\lib\libhdf5_D.lib  F:\test8\vcpkg\installed\x64-windows-static\debug\lib\zlibd.lib  F:\test8\vcpkg\installed\x64-windows-static\debug\lib\libszip_D.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe tests\unit\CMakeFiles\tests_high_five_base.dir\tests_high_five_base.cpp.obj /out:tests\unit\tests_high_five_base.exe /implib:tests\unit\tests_high_five_base.lib /pdb:tests\unit\tests_high_five_base.pdb /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /subsystem:console F:\test8\vcpkg\installed\x64-windows-static\debug\lib\boost_unit_test_framework-vc140-mt-gd.lib F:\test8\vcpkg\installed\x64-windows-static\debug\lib\libhdf5_D.lib F:\test8\vcpkg\installed\x64-windows-static\debug\lib\zlibd.lib F:\test8\vcpkg\installed\x64-windows-static\debug\lib\libszip_D.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:tests\unit\CMakeFiles\tests_high_five_base.dir/intermediate.manifest tests\unit\CMakeFiles\tests_high_five_base.dir/manifest.res" failed (exit code 1120) with the following output:
LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
tests_high_five_base.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl boost::unit_test::lazy_ostream::~lazy_ostream(void)" (__imp_??1lazy_ostream@unit_test@boost@@UEAA@XZ) referenced in function "public: virtual __cdecl boost::unit_test::lazy_ostream_impl<class boost::unit_test::lazy_ostream,char [1],char const (&)[1]>::~lazy_ostream_impl<class boost::unit_test::lazy_ostream,char [1],char const (&)[1]>(void)" (??1?$lazy_ostream_impl@Vlazy_ostream@unit_test@boost@@$$BY00DAEAY00$$CBD@unit_test@boost@@UEAA@XZ)
tests_high_five_base.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::unit_test::lazy_ostream & __cdecl boost::unit_test::lazy_ostream::instance(void)" (__imp_?instance@lazy_ostream@unit_test@boost@@SAAEAV123@XZ) referenced in function "public: void __cdecl HighFiveBasic::test_method(void)" (?test_method@HighFiveBasic@@QEAAXXZ)
tests_high_five_base.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: __cdecl boost::unit_test::lazy_ostream::lazy_ostream(bool)" (__imp_??0lazy_ostream@unit_test@boost@@IEAA@_N@Z) referenced in function "public: __cdecl boost::unit_test::lazy_ostream_impl<class boost::unit_test::lazy_ostream,char [1],char const (&)[1]>::lazy_ostream_impl<class boost::unit_test::lazy_ostream,char [1],char const (&)[1]>(class boost::unit_test::lazy_ostream const &,char const (&)[1])" (??0?$lazy_ostream_impl@Vlazy_ostream@unit_test@boost@@$$BY00DAEAY00$$CBD@unit_test@boost@@QEAA@AEBVlazy_ostream@12@AEAY00$$CBD@Z)
```
Please note these symbols have prefix `__declspec(dllimport) public:` which is incorrect.
So I checked the declaration:
```cpp
class BOOST_TEST_DECL lazy_ostream {
public:
```
Macro `BOOST_TEST_DECL` is declared in _include/boost/test/detail/config.hpp_ line 107:
```cpp
#  ifdef BOOST_TEST_SOURCE
#    define BOOST_TEST_DECL BOOST_SYMBOL_EXPORT BOOST_SYMBOL_VISIBLE
#  else
#    define BOOST_TEST_DECL BOOST_SYMBOL_IMPORT BOOST_SYMBOL_VISIBLE
#  endif  // BOOST_TEST_SOURCE
#else
#  if defined(BOOST_TEST_INCLUDED)
#     define BOOST_TEST_DECL
#  else
#     define BOOST_TEST_DECL BOOST_SYMBOL_VISIBLE
#  endif
#endif
```
Further more:
```cpp
#if defined(BOOST_ALL_DYN_LINK) && !defined(BOOST_TEST_DYN_LINK)
#  define BOOST_TEST_DYN_LINK
#endif

// in case any of the define from cmake/b2 is set
#if !defined(BOOST_TEST_DYN_LINK) \
    && (defined(BOOST_UNIT_TEST_FRAMEWORK_DYN_LINK) \
        || defined(BOOST_TEST_EXEC_MONITOR_DYN_LINK) \
        || defined(BOOST_PRG_EXEC_MONITOR_DYN_LINK) )
#  define BOOST_TEST_DYN_LINK
#endif

#if defined(BOOST_TEST_INCLUDED)
#  undef BOOST_TEST_DYN_LINK
#endif

#if defined(BOOST_TEST_DYN_LINK)
#  define BOOST_TEST_ALTERNATIVE_INIT_API

#  ifdef BOOST_TEST_SOURCE
#    define BOOST_TEST_DECL BOOST_SYMBOL_EXPORT BOOST_SYMBOL_VISIBLE
#  else
#    define BOOST_TEST_DECL BOOST_SYMBOL_IMPORT BOOST_SYMBOL_VISIBLE
#  endif  // BOOST_TEST_SOURCE
#else
#  if defined(BOOST_TEST_INCLUDED)
#     define BOOST_TEST_DECL
#  else
#     define BOOST_TEST_DECL BOOST_SYMBOL_VISIBLE
#  endif
#endif
```
So `BOOST_TEST_DYN_LINK` must be defined in some where, then I checked highfive's CMakeLists.txt, in _HIGHFIVE_SOURCE/tests/unit/CMakeLists.txt_ line 6:
```cmake
if(NOT Boost_USE_STATIC_LIBS)
  add_definitions(-DBOOST_TEST_DYN_LINK=TRUE)
endif()
```
I think that's reasonable because we should use dynamic declaration when linking to  boost dynamic libraries.
However we built boost as static library before.

Then I found this PR.

I think the reason why force `Boost_USE_STATIC_LIBS` to `OFF` is because you fix the `FindBoost` usage, but it affect some other stuff such like this issue.

Then I changed `Boost_USE_STATIC_LIBS` to `ON` manually, and got the find boost errors.
After some investigations, I think if we not defined `Boost_LIB_PREFIX`, `FindBoost.cmake` will always find boost library with prefix `lib` when `Boost_USE_STATIC_LIBS` is `ON` and `WIN32` is defined. But the fact is we do NOT pick this prefix in boost build process. Even I set it to empty before, it didn't work.

At last, I think if we keep this changes, we also need to modify the related declarations in _include/boost/test/detail/config.hpp_, Or we should completely fix this issues by not remove the official prefix `lib` when building static.

What do you think about?

cc @ras0219-msft @JackBoosY @PhoebeHui 
Related issue: https://github.com/microsoft/vcpkg/issues/1338 https://github.com/microsoft/vcpkg/issues/1745

2021-12-07 10:01 UTC, Neumann-A commented
@JonLiu1993 The code here is just copied over from vcpkg.cmake: https://github.com/microsoft/vcpkg/blob/431d3810aa9241aed49b14367be417f225d2af5e/scripts/buildsystems/vcpkg.cmake#L746
to make vcpkg handling of these settings more consistent. The old code in vcpkg.cmake is kept for backward compatibility

2021-12-07 10:02 UTC, JackBoosY commented
@Neumann-A Alright, I think we may need more discussion with @ras0219-msft here to confirm the fix solution.

2021-12-07 10:56 UTC, JackBoos commented
I suddenly realized that we can do some "hack" in the wrapper as before:
```cmake
unset(BOOST_TEST_DYN_LINK)
unset(BOOST_TEST_DYN_LINK CACHE)
```

2021-12-08 06:42 UTC, JackBoosY commented
> I suddenly realized that we can do some "hack" in the wrapper as before:
> 
> ```cmake
> unset(BOOST_TEST_DYN_LINK)
> unset(BOOST_TEST_DYN_LINK CACHE)
> ```

In https://github.com/BlueBrain/HighFive/blob/master/tests/unit/CMakeLists.txt#L5-L8:
```cmake
# NOTE: These unit tests expect linking with boost test framework lib
if(NOT Boost_USE_STATIC_LIBS)
  add_definitions(-DBOOST_TEST_DYN_LINK=TRUE)
endif()
```
`BOOST_TEST_DYN_LINK` is a c++ macro so we can't do that.