[onnx] create a new port
microsoft/vcpkg pull request #18073
Opened 2021-05-23 11:57 UTC by luncliff

### What does your PR fix?  

Create a new port for https://github.com/onnx/onnx. 

### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

Targets Windows / Linux triplets. I will update "supports" after checking installed files in Windows / Linux

* `x64-windows`
* `x86-windows`
* `x64-osx`
* `x64-linux`: supports feature `pybind11`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

2021-06-29 14:53 UTC, talregev commented
@luncliff Need any help?

2021-07-30 17:02 UTC, talregev commented
Did you fix everything? 
You can run tests by type:
/azp run

2021-07-30 17:06 UTC, luncliff commented
> Did you fix everything?
> You can run tests by type:
> /azp run
> 
> Thank you for the commits!

Thanks for check. I couldn't work on libtorch port dependencies, but starting it again.
Import worked fine. Several build fix commit will be added

2021-07-30 17:07 UTC, talregev commented
> > Did you fix everything?
> > You can run tests by type:
> > /azp run
> > Thank you for the commits!
> 
> Thanks for check. I couldn't work on libtorch port dependencies, but starting it again.
> Import worked fine. Several build fix commit will be added

Thank you!

2021-07-30 17:21 UTC, luncliff commented
Found the error is from `tensorflow-cc`, Bazel version issue.
https://dev.azure.com/vcpkg/public/_build/results?buildId=56904&view=artifacts

2021-07-30 17:21 UTC, luncliff commented
/azp run

2021-07-31 08:48 UTC, talregev commented
@JackBoosY Can you help?

2021-08-02 08:48 UTC, NancyLi1013 commented
@luncliff 
Is this ready for review now?

2021-08-02 08:49 UTC, luncliff commented
I think so.

On Mon, Aug 2, 2021 at 5:48 PM NancyLi1013 ***@***.***> wrote:

> @luncliff <https://github.com/luncliff>
> Is this ready for review now?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/18073#issuecomment-890847082>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLSYE7AMH4WZS5QICI4JQTT2ZLVBANCNFSM45LUOKGA>
> .
>

2021-08-03 06:40 UTC, NancyLi1013 requested changes

2021-08-03 06:40 UTC, NancyLi1013 commented on ports/onnx/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```
The path should be quoted in cmake file. Please see the doc https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/cmake-guidelines.md.

2021-08-03 06:40 UTC, NancyLi1013 commented on ports/onnx/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-03 06:40 UTC, NancyLi1013 commented on ports/onnx/portfile.cmake
> +)
Could you please also add double quotes for these paths?

2021-08-03 06:40 UTC, NancyLi1013 commented on ports/onnx/vcpkg.json
> +  "version": "1.9.0",
```suggestion
  "version-semver": "1.9.0",
```
It might be better served by [version-semver](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-semver).

2021-08-03 07:01 UTC, luncliff commented on ports/onnx/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
Got it. I will check the other works either.

2021-08-03 07:02 UTC, luncliff commented on ports/onnx/portfile.cmake
> +)
Yeah. I will double check the folders and quote them soon

2021-08-06 18:09 UTC, luncliff commented
Added `host` dependencies for `protoc`, `python3` which is required for codegen steps.

My Linux environment kept using `/usr/bin/python3` which has lower version.
To fix this, I replaced `find_package(Python)` to `find_package(Python3)` and provide `Python3_ROOT_DIR=${CURRENT_INSTALLED_DIR}` to work correctly with `python3` port of vcpkg.

Hope this approach is correct.

2021-08-09 06:43 UTC, NancyLi1013 approved these changes

2021-08-09 06:44 UTC, NancyLi1013 commented
Have you tested the feature `pybind11`? @luncliff

2021-08-12 02:53 UTC, NancyLi1013 commented
LGTM now, thanks for adding this new port. @luncliff

2021-08-12 04:34 UTC, BillyONeal commented on ports/onnx/portfile.cmake
> +vcpkg_find_acquire_program(PYTHON3)
```suggestion
# Like protoc, python is required for codegen.
vcpkg_find_acquire_program(PYTHON3)
```

Is this required even when pybind11 is off?

2021-08-12 04:36 UTC, BillyONeal commented on ports/onnx/vcpkg.json
> +    },
Is this being added because of `vcpkg_find_acquire_program(PYTHON3)`, or is there some other use?

2021-08-12 04:52 UTC, luncliff commented on ports/onnx/portfile.cmake
> +vcpkg_find_acquire_program(PYTHON3)
Yes. protobuf and python is required for internal protobuf related code generation steps.

2021-08-12 05:07 UTC, luncliff commented on ports/onnx/vcpkg.json
> +    },
The part is for `find_package(Python3 COMPONENTS Interpreter)`. And for cross compile scenario, it uses `find_package(Python3 COMPONENTS Development)`. The dependency is solved by `pybind11`.

2021-08-27 21:20 UTC, merged