[libpng] fix Android ARM triplet build failure
microsoft/vcpkg pull request #18115
Opened 2021-05-26 02:24 UTC by luncliff

### What does your PR fix?  

Fix build failure of `libpng` targeting Android `arm-android`.

Port version 14 fails with the following error (install-arm-android-dbg-out.log)

```
...
[6/21] D:\shared\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe -target armv7-none-linux-androideabi21 -gcc-toolchain D:/shared/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/shared/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DPNG_ARM_NEON_OPT=2 -I. -ID:/luncliff/sources/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean -isystem D:/luncliff/sources/vcpkg/installed/arm-android/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -mfpu=vfpv3-d16 -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/png_static.dir/arm/filter_neon.S.o -MF CMakeFiles\png_static.dir\arm\filter_neon.S.o.d -o CMakeFiles/png_static.dir/arm/filter_neon.S.o -c D:/luncliff/sources/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean/arm/filter_neon.S
FAILED: CMakeFiles/png_static.dir/arm/filter_neon.S.o 
D:\shared\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe -target armv7-none-linux-androideabi21 -gcc-toolchain D:/shared/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/shared/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DPNG_ARM_NEON_OPT=2 -I. -ID:/luncliff/sources/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean -isystem D:/luncliff/sources/vcpkg/installed/arm-android/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -mfpu=vfpv3-d16 -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/png_static.dir/arm/filter_neon.S.o -MF CMakeFiles\png_static.dir\arm\filter_neon.S.o.d -o CMakeFiles/png_static.dir/arm/filter_neon.S.o -c D:/luncliff/sources/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean/arm/filter_neon.S
<instantiation>:18:9: error: unknown directive
        .func png_read_filter_row_sub4_neon
        ^
...
```

Change option `PNG_ARM_NEON=on` to `PNG_ARM_NEON=check`.

#### Related Issues

* #16847 current mainstream's `arm-android.cmake`
* #11162 `PNG_ARM_NEON=on` specified

### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

* `arm-android`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

2021-05-26 06:51 UTC, JackBoosY approved these changes

2021-05-26 07:37 UTC, JackBoosY commented
Waiting for https://github.com/microsoft/vcpkg/pull/18116 merge.

2021-05-28 02:48 UTC, luncliff commented
I found `arm64-osx` triplet build is failing. Let me handle the issue in this PR.

2021-05-31 02:29 UTC, JackBoosY requested changes

2021-05-31 02:29 UTC, JackBoosY commented on ports/libpng/vcpkg.json
> +  "version-string": "1.6.37",
```suggestion
  "version": "1.6.37",
```

2021-05-31 05:42 UTC, JackBoosY commented
Please ping me if this PR is ready for review.

2021-06-01 14:07 UTC, luncliff commented
I checked triplets and build was successful with local machine. I think it will be fine when CI passes.

2021-06-02 03:13 UTC, JackBoosY approved these changes

2021-06-02 03:13 UTC, JackBoosY commented
LGTM.

2021-06-09 22:47 UTC, strega-nil-ms commented
Thanks @luncliff :)

2021-06-09 22:47 UTC, merged