Add VCPKG_MAKE_CONFIGURE_OPTIONS (that can be set in the triplet)
microsoft/vcpkg pull request #18132
Opened 2021-05-26 22:53 UTC by past-due

Permits appending / forwarding options to the configure command (in `vcpkg_configure_make`) from a triplet.

This should enable resolving a number of outstanding issues with various community (and custom) triplets, and avoid having to hard-code those fixes in `vcpkg_configure_make.cmake` itself.

Adds support for three new triplet variables:
- `VCPKG_MAKE_CONFIGURE_OPTIONS`
- `VCPKG_MAKE_CONFIGURE_OPTIONS_RELEASE`
- `VCPKG_MAKE_CONFIGURE_OPTIONS_DEBUG`

### Example:

Add to a triplet:
```cmake
set(VCPKG_MAKE_CONFIGURE_OPTIONS "lt_cv_deplibs_check_method=pass_all")
```
To skip libtool checks that may errantly fail in a number of configurations / triplets.

@ras0219-msft @Neumann-A

2021-05-26 23:20 UTC, ras0219 commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(APPEND _csc_OPTIONS "${VCPKG_MAKE_CONFIGURE_OPTIONS}")
```suggestion
        list(APPEND _csc_OPTIONS ${VCPKG_MAKE_CONFIGURE_OPTIONS})
```

Since VCPKG_MAKE_CONFIGURE_OPTIONS is a list variable in this context, I believe it should be expanded without quotes @strega-nil @strega-nil-ms

2021-05-27 02:21 UTC, JackBoosY requested changes
I'd like to see the same changes in _ports/vcpkg_cmake/vcpkg_cmake_configure.cmake_

2021-05-27 05:51 UTC, dg0yt commented
This needs to get documentation here and/or in `docs/users/triplets.md`. At least it needs a mention here similar to `VCPKG_MAKE_BUILD_TRIPLET`.

2021-05-27 13:36 UTC, past-due commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(APPEND _csc_OPTIONS "${VCPKG_MAKE_CONFIGURE_OPTIONS}")
Applied 👍

2021-05-28 02:27 UTC, JackBoosY requested changes
Please bump `vcpkg-cmake` version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version vcpkg-cmake` then commit the changes.

2021-05-28 03:23 UTC, past-due commented
> Please bump `vcpkg-cmake` version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
> Also please run command `vcpkg x-add-version vcpkg-cmake` then commit the changes.

@JackBoosY Done. 👍

2021-05-28 05:44 UTC, JackBoosY approved these changes

2021-06-01 18:16 UTC, strega-nil-ms approved these changes
needs fixin'

2021-06-01 18:16 UTC, strega-nil-ms commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +        list(APPEND arg_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS})
```suggestion
        list(APPEND arg_OPTIONS "${VCPKG_CMAKE_CONFIGURE_OPTIONS}")
```

2021-06-01 18:16 UTC, strega-nil-ms commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +        list(APPEND arg_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS_RELEASE})
```suggestion
        list(APPEND arg_OPTIONS_RELEASE "${VCPKG_CMAKE_CONFIGURE_OPTIONS_RELEASE}")
```

2021-06-01 18:16 UTC, strega-nil-ms commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +        list(APPEND arg_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS_DEBUG})
```suggestion
        list(APPEND arg_OPTIONS_DEBUG "${VCPKG_CMAKE_CONFIGURE_OPTIONS_DEBUG}")
```

2021-06-01 18:30 UTC, dg0yt commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +        list(APPEND arg_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS})
No? A few days ago @ras0219 requested to remove the quote.
https://github.com/microsoft/vcpkg/pull/18132#discussion_r640183017

2021-06-01 18:33 UTC, dg0yt commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +        list(APPEND arg_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS})
Okay, it is a different variable name. But isn't `arg_OPTIONS` a list, too? If not, I would prefer `string(APPEND ..)`

2021-06-07 02:45 UTC, past-due commented
The single failure in x86_windows appears to have nothing to do with this PR:

```
> -- Fetching git://code.qt.io/qt/qtnetworkauth.git...
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
>     Command failed: C:/agent/externals/git/cmd/git.exe fetch git://code.qt.io/qt/qtnetworkauth.git v6.1.0 --depth 1 -n
>     Working Directory: D:/downloads/git-tmp
>     Error code: 128
>     See logs for more information:
>       D:\buildtrees\qtnetworkauth\git-fetch-x86-windows-err.log
```

2021-06-08 16:50 UTC, merged

2021-06-08 16:50 UTC, strega-nil-ms commented
Thanks @past-due :)