[ffmpeg] Add support for arm64 on macOS
microsoft/vcpkg pull request #18182
Opened 2021-05-29 09:10 UTC by vejmartin

Adds arm64 support for macOS.

- #### What does your PR fix?  
  arm64-osx, arm64-osx-dynamic

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  arm64-osx, arm64-osx-dynamic; No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-05-31 06:27 UTC, NancyLi1013 requested changes

2021-05-31 06:27 UTC, NancyLi1013 commented on ports/ffmpeg/vcpkg.json
>    "version-string": "4.4",
```suggestion
  "version": "4.4",
```
Should be `version` here. Please see the reference https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version.

2021-05-31 08:41 UTC, NancyLi1013 approved these changes

2021-06-02 20:38 UTC, strega-nil-ms commented
i'm going to try this on my m1 mac later today, then i'll merge :)

2021-06-03 19:58 UTC, ras0219-msft approved these changes

2021-06-03 21:56 UTC, merged

2021-06-03 21:56 UTC, strega-nil-ms commented
Thanks @vejmartin :)