Update xmlsec to 1.2.32
microsoft/vcpkg pull request #18199
Opened 2021-05-31 03:46 UTC by SvenPStarFinanz

- #### What does your PR fix?  
Updates xmlsec to 1.2.32. Among other minor fixes that version removes the need to patch UWP build.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
no change

- #### Does your PR follow the [maintainer guide]
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

2021-05-31 06:30 UTC, JonLiu1993 requested changes

2021-05-31 06:30 UTC, JonLiu1993 commented on ports/xmlsec/vcpkg.json
> +  "version-string": "1.2.32",
@SvenPStarFinanz ,We should use "version" replace "version-string"

2021-05-31 06:30 UTC, JonLiu1993 commented on versions/x-/xmlsec.json
> +      "version-string": "1.2.32",
We should use "version" replace "version-string"

2021-05-31 14:00 UTC, SvenPStarFinanz commented on ports/xmlsec/vcpkg.json
> +  "version-string": "1.2.32",
Ok, did so.

2021-05-31 14:03 UTC, SvenPStarFinanz commented on versions/x-/xmlsec.json
> +      "version-string": "1.2.32",
Did so.

2021-05-31 14:17 UTC, SvenPStarFinanz commented
Apart from the version update I found/fixed a problem resulted by #16908 on Windows build of xmlsec. In src\dl.c of xmlsec there was constructed the name of the crypto library, which always have to begin with "lib", so I turned back to the old file name on Windows.

2021-06-01 02:47 UTC, JonLiu1993 approved these changes

2021-06-03 19:42 UTC, merged

2021-06-03 19:42 UTC, ras0219-msft commented
That makes sense to me, thanks for the update & fix!