[d3d12-memory-allocator] new port
microsoft/vcpkg pull request #18212
Opened 2021-05-31 17:58 UTC by crud89

This PR adds a port for the [D3D12 Memory Allocator](https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator), a DirectX 12 counterpart for the already existing [Vulkan Memory Allocator](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator). The port creates an interface library target from the D3D12MemAlloc header and source files. The port was also requested in issue #17157. Due to the nature of DirectX, it only Windows is supported.

2021-06-01 02:40 UTC, NancyLi1013 requested changes

2021-06-01 02:40 UTC, NancyLi1013 commented on ports/d3d12-memory-allocator/portfile.cmake
> +file(COPY "${SOURCE_PATH}/src/D3D12MemAlloc.cpp" DESTINATION "${CURRENT_PACKAGES_DIR}/src")
Can you write a CMakeLists.txt to use cmake to build this port instead of installing these files directly?

2021-06-01 02:40 UTC, NancyLi1013 commented on ports/d3d12-memory-allocator/portfile.cmake
> +    REF 10f148cef0dfd34ae1a9373b9396beb1581c992a
Seems you used the latest commit instead of the latest release.

2021-06-01 02:40 UTC, NancyLi1013 commented on ports/d3d12-memory-allocator/vcpkg.json
> +  "port-version": 1,
```suggestion
  "port-version": 0,
```
The value should be 0 for new ports.

2021-06-01 10:08 UTC, crud89 commented on ports/d3d12-memory-allocator/portfile.cmake
> +file(COPY "${SOURCE_PATH}/src/D3D12MemAlloc.cpp" DESTINATION "${CURRENT_PACKAGES_DIR}/src")
Done, I've changed it so that it always builds a static library instead. The reason why I used the interface library approach was, that the documentation of the project states, that you should add both source files to your projects' source tree, similar to an interface target. However, the static library approach should do the job as better.

2021-06-01 10:08 UTC, crud89 commented on ports/d3d12-memory-allocator/portfile.cmake
> +    REF 10f148cef0dfd34ae1a9373b9396beb1581c992a
This was a deliberate choice, since there does not seem a fixed release schedule. The last release was the initial release and since then there have been a lot of fixes. The master branch is stable, though.

2021-06-01 10:09 UTC, NancyLi1013 commented on ports/d3d12-memory-allocator/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Can you please help make a simple description why this port only support static build?

2021-06-01 10:10 UTC, NancyLi1013 requested changes

2021-06-01 10:10 UTC, NancyLi1013 commented on ports/d3d12-memory-allocator/portfile.cmake
> +    PREFER_NINJA
```suggestion
```
This is not needed for the function.

2021-06-01 10:11 UTC, NancyLi1013 commented
Have you tested the usage for this port? @crud89

2021-06-01 11:02 UTC, crud89 commented on ports/d3d12-memory-allocator/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Sure! 🙂 The library is intended to be copied into the source tree of you application (that's why I originally used an interface library target). This means, that it does not `dllexport`/`dllimport` any symbols, so building a shared library would not work.

2021-06-01 16:05 UTC, crud89 commented
> Have you tested the usage for this port? @crud89

Yes. First, I have tried to install the port locally, which works when using my fork. Also I have integrated the fork into my project and referenced the port from there and wrote a small sample application that calls into the library. The sample builds and runs successfully.

2021-06-02 01:50 UTC, NancyLi1013 approved these changes

2021-06-02 01:50 UTC, NancyLi1013 commented
LGTM now, thanks for adding this port @crud89.

2021-06-10 23:07 UTC, strega-nil-ms requested changes

2021-06-10 23:07 UTC, strega-nil-ms commented on ports/d3d12-memory-allocator/portfile.cmake
> +    REF 10f148cef0dfd34ae1a9373b9396beb1581c992a
This is definitely not `1.0.0`; if you want the latest on this date, you should probably use `version-date: 2021-06-10`.

2021-06-10 23:07 UTC, strega-nil-ms commented on ports/d3d12-memory-allocator/portfile.cmake
> +    REF 10f148cef0dfd34ae1a9373b9396beb1581c992a
(otherwise, you can use the ref that corresponds to `1.0.0`)

2021-06-15 11:59 UTC, crud89 commented on ports/d3d12-memory-allocator/portfile.cmake
> +    REF 10f148cef0dfd34ae1a9373b9396beb1581c992a
Thanks for the hint. I've changed it to `version-date: 2021-05-05`, which aligns with the commit date. 🙂

2021-06-24 22:16 UTC, ras0219-msft requested changes
Thanks for the PR! This LGTM once my suggestion is applied.

2021-06-24 22:16 UTC, ras0219-msft commented on versions/d-/d3d12-memory-allocator.json
> +      "port-version": 0
```suggestion
```
PRs must add only one version for each library to the database

2021-07-16 07:15 UTC, merged

2021-07-16 07:15 UTC, BillyONeal commented
Thanks for your contribution!