Update presentmon port from 1.6.0 release to 1.7.0
microsoft/vcpkg pull request #18234
Opened 2021-06-02 05:02 UTC by aggieNick02

Update presentmon port from 1.6.0 release to 1.7.0
- #### What does your PR fix?  
Updates port to latest presentmon release

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
- Same as previous port version

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
 Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-06-03 02:23 UTC, NancyLi1013 requested changes

2021-06-03 02:23 UTC, NancyLi1013 commented on ports/presentmon/portfile.cmake
>  vcpkg_from_github(
`set(PRESENTMON_VERSION 1.6.0)` 
This line seems not to be not used. It might be removed. Can you help confirm this?

2021-06-03 02:23 UTC, NancyLi1013 commented on ports/presentmon/CMakeLists.txt
> +set(PRESENTMON_VERSION 1.7.0)
Do you know why `PRESENTMON_VERSION ` is added here? Seems it is not used in other places.

2021-06-03 02:23 UTC, NancyLi1013 commented on ports/presentmon/portfile.cmake
Can you update the following lines
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    tools BUILD_TOOLS
)
```
as 
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        tools BUILD_TOOLS
)

```
?

2021-06-03 02:23 UTC, NancyLi1013 commented on ports/presentmon/vcpkg.json
> +  "version-string": "1.7.0",
```suggestion
  "version": "1.7.0",
```
`version `might be better here. Please see https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version

2021-06-03 18:37 UTC, aggieNick02 commented on ports/presentmon/portfile.cmake
>  vcpkg_from_github(
I don't think it is used. When I did the first Presentmon port I did it as a visual studio-based port and @JackBoosY helped by offering a CMake based port. @JackBoosY do you know if this is needed for any reason?

2021-06-03 18:37 UTC, aggieNick02 commented on ports/presentmon/CMakeLists.txt
> +set(PRESENTMON_VERSION 1.7.0)
I don't think it is used. @JackBoosY do you know if this is needed for any reason?

2021-06-03 18:38 UTC, aggieNick02 commented on ports/presentmon/portfile.cmake
Is that just fixing the indenting? Happy to update that.

2021-06-03 18:43 UTC, aggieNick02 commented on ports/presentmon/vcpkg.json
> +  "version-string": "1.7.0",
I just kept it as version-string since that was what it was the first time. Any reason to not change @JackBoosY ? I thought I ran into some doc that said version-string was the only supported option right now, but I'm guessing that's not true anymore, and I can't find the stale doc at the moment.

2021-06-04 08:08 UTC, NancyLi1013 commented on ports/presentmon/portfile.cmake
>  vcpkg_from_github(
This can be removed. Since it is not used anywhere.

2021-06-04 08:08 UTC, NancyLi1013 commented on ports/presentmon/CMakeLists.txt
> +set(PRESENTMON_VERSION 1.7.0)
The same reason as above.

2021-06-04 08:09 UTC, NancyLi1013 commented on ports/presentmon/portfile.cmake
Yes, just update the indenting as four spaces.

2021-06-04 08:13 UTC, NancyLi1013 commented on ports/presentmon/vcpkg.json
> +  "version-string": "1.7.0",
`version-string` is the general expression. But we prefer to use more proper filed here. You can see the differences between these filed names. https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-schemes

2021-06-14 17:10 UTC, aggieNick02 commented on ports/presentmon/portfile.cmake
>  vcpkg_from_github(
Got it, thanks!

2021-06-14 17:10 UTC, aggieNick02 commented on ports/presentmon/CMakeLists.txt
> +set(PRESENTMON_VERSION 1.7.0)
Got it, thanks!

2021-06-14 17:10 UTC, aggieNick02 commented on ports/presentmon/portfile.cmake
Got it, thanks!

2021-06-14 17:10 UTC, aggieNick02 commented on ports/presentmon/vcpkg.json
> +  "version-string": "1.7.0",
Thanks for explaining. Will fix.

2021-06-14 17:11 UTC, aggieNick02 commented
Sorry for the delay getting back with the fixes. They should be submitted now. Please just let me know if I missed anything or there's anything else. Thank you!

2021-06-16 01:42 UTC, NancyLi1013 approved these changes

2021-06-16 01:43 UTC, NancyLi1013 commented
Have you tested the feature `tools`? @aggieNick02

2021-06-24 03:39 UTC, aggieNick02 commented
Hi @NancyLi1013 - sorry for the delay. In terms of testing, do you mean manually? I've built and used the changes in this PR with the tools feature, and validated that PresentMon.exe works as it should.

2021-06-24 08:04 UTC, NancyLi1013 commented
> Hi @NancyLi1013 - sorry for the delay. In terms of testing, do you mean manually? I've built and used the changes in this PR with the tools feature, and validated that PresentMon.exe works as it should.

Yes, generally, all features need to be tested manually except for default features. Since our CI only test default features.

2021-06-24 08:05 UTC, NancyLi1013 commented
LGTM, thanks for your updates @aggieNick02.

2021-07-15 22:05 UTC, BillyONeal commented
@aggieNick02 Can you push a merge with master? It's not letting me push to your branch and I want to make sure this builds on the now-current Ubuntu before merging it. Thanks!

2021-07-15 22:26 UTC, aggieNick02 commented
Wasn't 100% sure exactly what you needed, i.e. if y'all prefer my changes as rebase on latest or the more traditional merge- I did a github.com fetch and merge that is building now. Let me know if you need it differently. Thanks.
The port is windows only so there should not be any issues on ubuntu.

2021-07-15 22:36 UTC, BillyONeal commented
> Wasn't 100% sure exactly what you needed, i.e. if y'all prefer my changes as rebase on latest or the more traditional merge- I did a github.com fetch and merge that is building now. Let me know if you need it differently. Thanks.
> The port is windows only so there should not be any issues on ubuntu.

Either one works. It gets squashed when it lands and I tend to do merges when pushing to branches I don't own because it's easier people to undo if they want and doesn't break any commits they might not have pushed yet.

Thanks!

2021-07-16 07:14 UTC, merged

2021-07-16 07:14 UTC, BillyONeal commented
Thanks for your contribution!