[FreeRDP] update to 2.3.2
microsoft/vcpkg pull request #18242
Opened 2021-06-02 13:37 UTC by zhongzf

Update FreeRDP to the latest version 2.3.2

Note : no feature need to test

2021-06-03 07:12 UTC, JonLiu1993 requested changes
@zhongzf ,Thanks for your pr.
Please add 'FEATURES' below the function "vcpkg_check_features" in the portifile.cmake like this:
````
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS    
    FEATURES
        urbdrc CHANNEL_URBDRC)


````

2021-06-03 07:19 UTC, JonLiu1993 requested changes
Please add "vcpkg_fixup_pkgconfig()" below 
````
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/WinPR2_temp/WinPR2 TARGET_PATH share/WinPR)
````
in the portfile.cmake

2021-06-03 07:22 UTC, JonLiu1993 commented
After modification,please execute './vcpkg x-add-version --overwrite-version freerdp', and submit the changes again.

2021-06-03 16:13 UTC, zhongzf commented
> After modification,please execute './vcpkg x-add-version --overwrite-version freerdp', and submit the changes again.

Fixed.

2021-06-04 08:25 UTC, JonLiu1993 commented
> > After modification,please execute './vcpkg x-add-version --overwrite-version freerdp', and submit the changes again.
> 
> Fixed.

After modification,please execute './vcpkg x-add-version --overwrite-version freerdp', and submit the changes again.

2021-06-04 11:19 UTC, zhongzf commented
> > > After modification,please execute './vcpkg x-add-version --overwrite-version freerdp', and submit the changes again.
> > 
> > 
> > Fixed.
> 
> After modification,please execute './vcpkg x-add-version --overwrite-version freerdp', and submit the changes again.

It's done.

2021-06-07 06:20 UTC, JackBoosY requested changes

2021-06-07 06:20 UTC, JackBoosY commented on ports/freerdp/portfile.cmake
> +vcpkg_fixup_pkgconfig(SKIP_CHECK)
Why skip this check? Did you test the usage using pkgconfig?

2021-06-07 12:06 UTC, zhongzf commented on ports/freerdp/portfile.cmake
> +vcpkg_fixup_pkgconfig(SKIP_CHECK)
I tested without SKIP,  it throws an error when the build completed, I guess it may caused by the openssl lib, it is not using the config from the original makefile, so added the SKIP_CHECK, all works fine.

2021-06-08 02:48 UTC, JackBoosY commented on ports/freerdp/portfile.cmake
> +vcpkg_fixup_pkgconfig(SKIP_CHECK)
cc @Neumann-A for review this part.

2021-07-06 08:26 UTC, JonLiu1993 commented on ports/freerdp/portfile.cmake
> +vcpkg_fixup_pkgconfig(SKIP_CHECK)
cc @Neumann-A ,Could you please help review this part?

2021-07-12 20:24 UTC, ras0219-msft approved these changes

2021-07-13 02:31 UTC, JackBoosY commented
Please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=55957&view=artifacts&pathAsName=false&type=publishedArtifacts).

2021-07-23 06:36 UTC, JonLiu1993 commented
@zhongzf ,Could you please fix this error?
https://dev.azure.com/vcpkg/public/_build/results?buildId=55957&view=artifacts&pathAsName=false&type=publishedArtifacts

2021-07-26 12:33 UTC, zhongzf commented
It's strange, it compiles before, and I didn't see any meaningful message from the error log.

2021-07-26 13:45 UTC, zhongzf commented
rollback changes, compile passed.

2021-07-27 01:14 UTC, JackBoosY requested changes

2021-07-27 01:14 UTC, JackBoosY commented on ports/freerdp/install-dirs.patch
> ++endfunction()
Why add this? It should already provided by cmake.

2021-07-28 11:52 UTC, zhongzf commented on ports/freerdp/install-dirs.patch
> ++endfunction()
It's migrated from previous version, removed now.

2021-07-29 03:01 UTC, JackBoosY commented on versions/f-/freerdp.json
> +      "git-tree": "7eb5d9de06951055b7b58d99c7fa44b0de087980",
```suggestion
      "git-tree": "50c37de4c7ad0b1cfec9f285c83b231f2225ff7c",
```

2021-07-29 09:19 UTC, JackBoosY approved these changes

2021-07-29 18:10 UTC, merged

2021-10-11 02:12 UTC, JackBoosY commented
@vicroms Can you confirm that?