[SLikeNet] Fix building with x64-mingw-static
microsoft/vcpkg pull request #18358
Opened 2021-06-10 02:48 UTC by Pospelove

This PR makes `slikenet` port buildable with the `x64-mingw-static` triplet. However there are some problems with merging it as I can see:

1. The patch introduces tons of changes. Obviously, this violates [the maintainer guide.](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-implement-features-in-patches)
The reason for patching code this way is pretty simple. As far as I know, MinGW doesn't have some essential functions support like `inet_pton`/`inet_ntop`. Building SLikeNet requires them.
2. `TwoWayAuthentication.cpp` breaks compilation. Investigating. For now, I remove this file via `portfile.cmake`.

I would really appreciate your feedback, especially options on how to workaround missing functions. My current idea is that we should add something like `vcpkg-platform-helper` as a port that would implement functions missing on some platforms.

2021-06-10 07:13 UTC, NancyLi1013 commented
Please ping me if this PR is read for review @Pospelove.

2021-06-12 03:42 UTC, Pospelove commented
> This PR makes `slikenet` port buildable with the `x64-mingw-static` triplet. However there are some problems with merging it as I can see:
> 
> 1. The patch introduces tons of changes. Obviously, this violates [the maintainer guide.](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-implement-features-in-patches)
>    The reason for patching code this way is pretty simple. As far as I know, MinGW doesn't have some essential functions support like `inet_pton`/`inet_ntop`. Building SLikeNet requires them.
> 2. `TwoWayAuthentication.cpp` breaks compilation. Investigating. For now, I remove this file via `portfile.cmake`.
> 
> I would really appreciate your feedback, especially options on how to workaround missing functions. My current idea is that we should add something like `vcpkg-platform-helper` as a port that would implement functions missing on some platforms.

1. I have read the guide again and now I think that there is no violation. I do not implement anything new, just fix compatibility. Patched license file since the third-party implementation is being used.
2. Figured out that it's just an optional plugin. So, disabling it via compile definition when building under MinGW.

2021-06-12 03:42 UTC, Pospelove commented
@NancyLi1013 I think it's ready

2021-06-15 09:59 UTC, NancyLi1013 requested changes
Seems you rewrite portfile.cmake instead of only updating the changes based on the original file. Can you update this?

2021-06-15 09:59 UTC, NancyLi1013 commented on ports/slikenet/portfile.cmake
> +set(SLIKENET_PATCHES fix-install.patch)
Since there are many changes in this patch. Could you please submit these changes to upstream?

2021-06-15 09:59 UTC, NancyLi1013 commented on ports/slikenet/portfile.cmake
> +endif()
```suggestion
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" SLIKENET_ENABLE_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" SLIKENET_ENABLE_DLL)
```
Please see the reference here https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#choose-either-static-or-shared-binaries

2021-06-16 02:41 UTC, NancyLi1013 requested changes

2021-06-16 02:41 UTC, NancyLi1013 commented on ports/slikenet/vcpkg.json
> +  "version-string": "2021-06-07",
```suggestion
  "version-date": "2021-06-07",
```
This should be `version-date` here. Please see the doc here. https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-date

2021-06-16 03:01 UTC, NancyLi1013 commented
Please `vcpkg x-add-version slikenet --overwrite-version` to solve the failures on x86-windows.

2021-06-16 03:05 UTC, NancyLi1013 approved these changes

2021-06-17 06:15 UTC, NancyLi1013 commented
LGTM, thanks for your updates and fixes. @Pospelove

2021-07-12 10:47 UTC, NancyLi1013 commented
/azp run

2021-07-23 05:15 UTC, merged