Upgrade mqtt-cpp to 10.0.0
microsoft/vcpkg pull request #18371
Opened 2021-06-10 13:02 UTC by iainchesworth

Updates the mqtt-cpp port to v10.0.0.  

- #### What does your PR fix?  
Adds missing support for optional TLS, websocket, and logging features.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
No

- #### Does your PR follow the [maintainer guide]
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

2021-06-10 22:10 UTC, ras0219 commented on ports/mqtt-cpp/portfile.cmake
> +if ("log" IN_LIST FEATURES)
This is a great place to use `vcpkg_check_features()`:
```cmake
vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        log MQTT_USE_LOG
        tls MQTT_USE_TLS
        ws MQTT_USE_WS
)

vcpkg_configure_cmake(
  OPTIONS ${FEATURE_OPTIONS}
)
```

2021-06-11 06:24 UTC, JonLiu1993 requested changes

2021-06-11 06:24 UTC, JonLiu1993 commented on ports/mqtt-cpp/portfile.cmake
> +	${OUT_FEATURE_OPTIONS}
There should be ${FEATURE_OPTIONS}

2021-06-11 06:24 UTC, JonLiu1993 commented on ports/mqtt-cpp/portfile.cmake
> +	-DMQTT_USE_STR_CHECK=ON
Please indent two spaces backward to keep the format consistent with the options that follow

2021-06-14 04:24 UTC, iainchesworth commented
Added requested changes (formatting).

2021-06-15 06:33 UTC, JonLiu1993 commented
All features are tested successfully in the folllowing triplet:
- x64-windows
- x64-windows-static
- x64-linux

2021-06-15 18:48 UTC, ras0219-msft requested changes

2021-06-15 18:48 UTC, ras0219-msft commented on ports/mqtt-cpp/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
By replacing the entire CMake build, this also removes any transitive dependencies needed to consume the library (openssl? boost?). It'd be much better if we could patch the original build to fix the problem instead of replacing it entirely.

2021-07-06 08:21 UTC, JonLiu1993 commented
@iainchesworth ,Have you considered @ras0219-msft 's suggestion?

2021-07-20 01:34 UTC, PhoebeHui commented
Ping @iainchesworth for response. Is work still being done for this PR?

2021-07-28 01:19 UTC, closed without merging