[dxut] port updated
microsoft/vcpkg pull request #18431
Opened 2021-06-13 22:07 UTC by walbourn

Minor DXUT servicing release for June 2021. See [GitHub](https://github.com/microsoft/DXUT/releases/tag/jun2021).

2021-06-13 22:08 UTC, walbourn commented
Verified all support triplets build:

```
vcpkg install dxut:x86-windows
vcpkg install dxut:x86-windows-static
vcpkg install dxut:x64-windows
vcpkg install dxut:x64-windows-static
```

2021-06-13 22:28 UTC, walbourn commented
Verified all supported **fx11** triplets:

```
vcpkg install effects11:x86-windows
vcpkg install effects11:x86-windows-static
vcpkg install effects11:x64-windows
vcpkg install effects11:x64-windows-static
vcpkg install effects11:arm64-windows
vcpkg install effects11:arm64-windows-static
vcpkg install effects11:x86-uwp
vcpkg install effects11:x64-uwp
vcpkg install effects11:arm-uwp
vcpkg install effects11:arm64-uwp
```

2021-06-13 22:47 UTC, walbourn commented
Verified all *directxmath* triplets:

```
vcpkg install directxmath:x86-windows
vcpkg install directxmath:x86-windows-static
vcpkg install directxmath:x64-windows
vcpkg install directxmath:x64-windows-static
vcpkg install directxmath:arm64-windows
vcpkg install directxmath:arm64-windows-static
vcpkg install directxmath:x86-uwp
vcpkg install directxmath:x64-uwp
vcpkg install directxmath:arm-uwp
vcpkg install directxmath:arm64-uwp
vcpkg install directmath:x64-linux
vcpkg install directmath:arm64-linux
```

2021-06-14 22:01 UTC, walbourn commented
@NancyLi1013 This PR is ready for review when you have a moment. Thanks.

2021-06-15 02:15 UTC, NancyLi1013 requested changes

2021-06-15 02:15 UTC, NancyLi1013 commented on ports/directxmath/vcpkg.json
> +  "homepage": "http://go.microsoft.com/fwlink/?LinkID=615560",
```suggestion
  "homepage": "https://github.com/Microsoft/DirectXMath",
```
The URL will be redirected to https://github.com/Microsoft/DirectXMath, we can use it directly here.

Note: Seems you just update CONTROL file as manifest for `directxmath`, there is no update for source codes.

2021-06-15 02:15 UTC, NancyLi1013 commented on ports/dxut/vcpkg.json
> +  "homepage": "http://go.microsoft.com/fwlink/?LinkId=320437",
Why do you not use the original URL https://github.com/Microsoft/DXUT for `homepage `field?

2021-06-15 02:15 UTC, NancyLi1013 commented on ports/effects11/vcpkg.json
> +  "homepage": "http://go.microsoft.com/fwlink/?LinkId=271568",
The same as above.

2021-06-15 02:51 UTC, walbourn commented on ports/directxmath/vcpkg.json
> +  "homepage": "http://go.microsoft.com/fwlink/?LinkID=615560",
If you'd rather use direct than fwlinks, that's fine by me...

2021-06-15 02:53 UTC, walbourn commented on ports/directxmath/vcpkg.json
> +  "homepage": "http://go.microsoft.com/fwlink/?LinkID=615560",
DirectXMath was just a port update to vcpkg.json so I could include the extra metadata...

2021-06-15 08:47 UTC, NancyLi1013 approved these changes

2021-06-15 10:28 UTC, NancyLi1013 commented
LGTM, thanks for your updates @walbourn.

2021-06-18 05:20 UTC, walbourn commented
@NancyLi1013 anything blocking this PR or is it just waiting for someone to take a look?

2021-06-18 06:14 UTC, NancyLi1013 commented
> @NancyLi1013 anything blocking this PR or is it just waiting for someone to take a look?

No, just need to merge now.

@ras0219 @ras0219-msft Could you please help merge this PR?

Thanks.

2021-06-21 21:19 UTC, merged

2021-06-21 21:19 UTC, ras0219-msft commented
This all looks awesome, thanks for the continued support @walbourn :)