[new port] libsmb2
microsoft/vcpkg pull request #18471
Opened 2021-06-15 22:04 UTC by timmeh87

**Describe the pull request**
New port 

- #### What does your PR fix?  
  Fixes #18454 
  
- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
I tested windows and linux-x64, Have not updated CI baseline, fingers crossed

- #### Does your PR follow the [maintainer guide]
I have read it but it is my first time doing this and I am a little uncertain, esp on the versions file and CI file

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-06-15 22:11 UTC, timmeh87 commented
I have failed the OSX test, please advise. I do not currently have an OSX machine or any experience at all using one, is it okay to mark as "fail" in the CI file? OSX is not officially supported by libsmb2. I will look into x86_windows.

2021-06-15 22:17 UTC, timmeh87 commented
In addition to my question about OSX, my other question is what should I do about this error from x86-windows? Should I update the SHA like it suggests? I dont understand why it only failed on this one triplet, or what I did wrong.

```
Error: While reading versions for port libsmb2 from file: C:\a\1\s\versions\l-\libsmb2.json
       File declares version `2021-4-29` with SHA: 6c4a62554446fd2e0bb41dfcd28d7da4b956c3fc
       But local port with the same verion has a different SHA: 0ba00729230d8f35629588109af3757277c06aab
       Please update the port's version fields and then run:

           vcpkg x-add-version libsmb2

       to add a new version.

To attempt to resolve all errors at once, run:

    vcpkg x-add-version --all

##[error]PowerShell exited with code '1'.
```

2021-06-16 06:53 UTC, JonLiu1993 requested changes

2021-06-16 06:53 UTC, JonLiu1993 commented on ports/libsmb2/vcpkg.json
> +  "version-string": "2021-4-29",
@timmeh87 ,Thanks for your pr.
We should use "version-date" instead of "version-string", the format of "version-date" is "2021-04-29"

2021-06-16 06:53 UTC, JonLiu1993 commented on ports/libsmb2/portfile.cmake
> +vcpkg_from_github(
We should add vcpkg_fail_port_install(ON_TARGET "osx") above vcpkg_from_github

2021-06-16 06:53 UTC, JonLiu1993 commented on ports/libsmb2/vcpkg.json
> +  "homepage": "https://github.com/sahlberg/libsmb2",
We should add "supports: !osx" in the vcpkg.json

2021-06-17 02:52 UTC, JonLiu1993 approved these changes

2021-06-21 20:55 UTC, ras0219-msft requested changes
Thanks for the PR!

2021-06-21 20:55 UTC, ras0219-msft commented on scripts/ci.baseline.txt
> +libsmb2:x64-osx=fail
```suggestion
```

This is not needed given the `"supports"` field.

2021-06-21 20:55 UTC, ras0219-msft commented on ports/libsmb2/vcpkg.json
> +    "vcpkg-cmake-config"
```suggestion
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
```

`vcpkg-cmake-config` is a helper script and so should only be installed for the host.

2021-06-21 20:55 UTC, ras0219-msft commented on ports/libsmb2/portfile.cmake
> +        -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
```suggestion
```
`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` is a highly problematic behavior for many reasons, therefore our maintainer guide explicitly forbids adding it to libraries: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-add-cmake_windows_export_all_symbols.

Since the library doesn't use `dllexport`, it should instead be marked as static only via `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` at the top of the portfile.

+@JonLiu1993 for visibility

2021-06-22 01:47 UTC, JonLiu1993 commented on ports/libsmb2/portfile.cmake
> +        -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
> `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` is a highly problematic behavior for many reasons, therefore our maintainer guide explicitly forbids adding it to libraries: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-add-cmake_windows_export_all_symbols.
> 
> Since the library doesn't use `dllexport`, it should instead be marked as static only via `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` at the top of the portfile.
> 
> +@JonLiu1993 for visibility

I'm sorry I didn't notice this, I will remember it, thank you for your reminder

2021-06-22 03:10 UTC, timmeh87 commented
Ok thank you for the help, I have made the requested changes via this buttons on this page (nifty)

2021-06-23 02:38 UTC, JonLiu1993 requested changes

2021-06-23 02:38 UTC, JonLiu1993 commented on ports/libsmb2/portfile.cmake
> +
Please add "vcpkg_fixup_pkgconfig()"

2021-06-23 05:46 UTC, JonLiu1993 approved these changes

2021-06-24 20:11 UTC, merged

2021-06-24 20:11 UTC, ras0219-msft commented
Thanks for the PR!