[simdjson] Update to v0.9.6
microsoft/vcpkg pull request #18479
Opened 2021-06-16 11:40 UTC by myd7349

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-06-17 06:56 UTC, JonLiu1993 requested changes

2021-06-17 06:56 UTC, JonLiu1993 commented on ports/simdjson/portfile.cmake
> +        -DSIMDJSON_CXXOPTS=OFF
@myd7349 ,Thanks for posting this pr,These options don't seem to be found in CMakeLists

2021-07-06 06:08 UTC, JonLiu1993 commented
@myd7349 ,Please let me know if this pr is ready for review

2021-07-09 10:07 UTC, myd7349 commented
Hi! @JonLiu1993 Thanks for your helpful review and sorry for the long delay.
This PR is ready now.

2021-07-14 06:23 UTC, JonLiu1993 commented on ports/simdjson/portfile.cmake
> +        exceptions    SIMDJSON_EXCEPTIONS
@myd7349 ,SIMDJSON_EXCEPTIONS is not found in CMakeLists, where is this feature implemented

2021-07-14 06:29 UTC, JonLiu1993 commented
@myd7349, have you tested these functions locally?

2021-07-14 10:55 UTC, myd7349 commented
> 
> 
> @myd7349, have you tested these functions locally?

Hi! @JonLiu1993 I have tested these features on:
- x86-windows
- x64-windows
- x64-windows-static

and it worked as expected on all these platforms.

My linux machine doesn't have a C++17 compiler, so I was not able to test them on `x64-linux`.

2021-07-14 11:27 UTC, JonLiu1993 approved these changes

2021-07-16 07:24 UTC, BillyONeal requested changes

2021-07-16 07:24 UTC, BillyONeal commented on ports/simdjson/portfile.cmake
> +        no-deprecated SIMDJSON_DISABLE_DEPRECATED_API
Features need to be additive, not subtractive; e.g. port a that depends on simdjson[no-deprecated] and port b that depends on simdjson together produce non-functional results.

2021-07-16 07:24 UTC, BillyONeal commented on ports/simdjson/portfile.cmake
> +        no-deprecated SIMDJSON_DISABLE_DEPRECATED_API
(If you invert the feature it's ok)

2021-07-17 03:25 UTC, myd7349 commented on ports/simdjson/portfile.cmake
> +        no-deprecated SIMDJSON_DISABLE_DEPRECATED_API
Hi! @BillyONeal Thanks for your helpful review. That sounds resonable.

2021-07-19 08:28 UTC, JonLiu1993 approved these changes

2021-07-19 19:11 UTC, BillyONeal approved these changes

2021-07-20 00:19 UTC, JonLiu1993 commented
Fix #19009

2021-07-20 00:20 UTC, merged

2021-07-20 00:21 UTC, BillyONeal commented
Thanks for your contribution @myd7349 !