[nuspell] Update to version 5.0.0
microsoft/vcpkg pull request #18590
Opened 2021-06-22 14:06 UTC by dimztimz

- #### What does your PR fix?  
  Port update

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

2021-06-23 06:00 UTC, JonLiu1993 requested changes

2021-06-23 06:00 UTC, JonLiu1993 commented on ports/nuspell/vcpkg.json
> +  "version-string": "5.0.0",
We should use "version-semver" instead of "version-string"

2021-06-23 06:00 UTC, JonLiu1993 commented on versions/n-/nuspell.json
> +      "version-string": "5.0.0",
We should use "version-semver" instead of "version-string"

2021-06-24 01:56 UTC, JonLiu1993 approved these changes

2021-06-24 20:07 UTC, merged

2021-06-24 20:07 UTC, ras0219-msft commented
Thanks for the update!