[cef-build] Create a new port
microsoft/vcpkg pull request #18613
Opened 2021-06-23 22:25 UTC by serg06

**Describe the pull request**

[CEF](https://bitbucket.org/chromiumembedded/cef/src/master/) was requested 5 years ago but nobody has added it yet: #332 

This is the next best thing: [Pre-built CEF binaries](https://cef-builds.spotifycdn.com/index.html).

#### What does your PR fix?  

Fixes #332 (for win64 users.)

#### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

x64-windows, Yes

(There are binaries for other triplets on their website, but I didn't implement that.)

#### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

#### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-06-24 03:43 UTC, serg06 commented
Update: I realize I'm not copying the `dll`, `bin`, `pak` and `dat` files correctly. It only ran for me because they were left over from an old build.

How do I get the `pak` and `dat` files to end up in the .exe directory?

2021-06-24 07:01 UTC, JackBoosY requested changes

2021-06-24 07:01 UTC, JackBoosY commented on ports/cef-build/portfile.cmake
> +)
Why not use `vcpkg_install_cmake` instead? Does the source have `install` code?

2021-06-24 16:04 UTC, serg06 commented on ports/cef-build/portfile.cmake
> +)
@JackBoosY It doesn't have `install` code unfortunately, I tried `vcpkg_install_cmake` but it told me "invalid target install".

2021-06-25 02:22 UTC, JackBoosY commented on ports/cef-build/portfile.cmake
> +)
Yeah, therefore, we need to patch the source to add the install command.

2021-06-27 07:17 UTC, Pospelove commented
Please take a look at https://github.com/microsoft/vcpkg/pull/10102

2021-06-27 18:23 UTC, serg06 commented
@Pospelove But doesn't the recent [chartdir port](https://github.com/microsoft/vcpkg/blob/master/ports/chartdir/portfile.cmake) use prebuilts?

2021-06-28 01:47 UTC, serg06 commented
@JackBoosY I changed it to use `INSTALL()` command for everything, but I still have the same issue, I don't know how to copy `.bin` files to output directory.

For example I added this to CMakeLists.txt:

```
file(GLOB bins_deb Debug/*.dll Debug/*.bin)
file(GLOB bins_rel Release/*.dll Release/*.bin)
INSTALL(
  FILES ${bins_deb}
  CONFIGURATIONS Debug
  TYPE BIN
)
```

And they appear in the bin folder:

![image](https://user-images.githubusercontent.com/1350889/123567843-1192df80-d791-11eb-9cb6-330dbd582dcf.png)

But they don't get copied over to .exe directory. Am I doing something wrong?

2021-06-28 02:32 UTC, JackBoosY commented
@serg06  I will give you some help.

2021-07-08 06:50 UTC, JonLiu1993 commented
@serg06 ,Can you please resolve the conflicts against master?

2021-07-09 07:38 UTC, JackBoosY commented
I noticed that this port only generates the library `libcef_dll_wrapper`, and other libraries copy existing files. Right?
If it's true, we hope that the main library `cef` is generated by the build process and change the port name to cef.

2021-07-19 18:26 UTC, serg06 commented
@JackBoosY Yeah, this library copies a bunch of pre-built binaries and generates `libcef_dll_wrapper`.

Are you suggesting we generate the `cef` binaries ourselves instead of using prebuilts? How could that help with the current issue?

2021-07-20 00:44 UTC, JackBoosY commented
@serg06 According to our policy, we need to generate binaries as much as possible instead of directly installing pre-built binaries.

2021-07-20 01:21 UTC, serg06 commented
@JackBoosY That's fine, but it has been years and nobody has added cef yet. Wouldn't it better to have prebuilt binaries than to have nothing at all?

2021-07-20 09:07 UTC, JackBoosY commented
@serg06 Sorry but according to our policy, only SDK can use pre-built binaries.
We should use vcpkg_configure_gn to build it.
Example: [chromium-base](https://github.com/microsoft/vcpkg/blob/master/ports/chromium-base/portfile.cmake)

2021-07-20 17:35 UTC, serg06 commented
@JackBoosY Ah okay. Thanks for the help. I hope someone will add it in the future.

2021-07-20 17:35 UTC, closed without merging