[glew] Fix the dependency
microsoft/vcpkg pull request #18672
Opened 2021-06-28 08:51 UTC by PhoebeHui

Fixes https://github.com/microsoft/vcpkg/issues/18662

glew depends on port opengl, which only built for windows, so limit to platform for dependencies. 
It requires libraries libxmu-dev libxi-dev libgl-dev which should be installed via system package manager on linux, providing the message with user.

2021-06-29 01:36 UTC, JackBoosY approved these changes

2021-07-01 16:44 UTC, ras0219-msft requested changes

2021-07-01 16:44 UTC, ras0219-msft commented on ports/glew/vcpkg.json
> +    }
```suggestion
    "opengl"
```

The port `opengl` is intended to represent `find_package(OpenGL)`, so that is a true dependency on all platforms.

2021-07-01 16:44 UTC, ras0219-msft commented on ports/glew/portfile.cmake
> +    message(WARNING "${PORT} currently requires the following libraries from the system package manager:\n    libxmu-dev\n    libxi-dev\n    libgl-dev\n\nThese can be installed on Ubuntu systems via
```suggestion
    message(WARNING "${PORT} requires the following libraries from the system package manager:\n    libxmu-dev\n    libxi-dev\n    libgl-dev\n\nThese can be installed on Ubuntu systems via apt-get install libxmu-dev libxi-dev libgl-dev.")
```

2021-07-02 07:49 UTC, PhoebeHui commented on ports/glew/vcpkg.json
> +    }
Updated, thanks for your review!

2021-07-02 07:49 UTC, PhoebeHui commented on ports/glew/portfile.cmake
> +    message(WARNING "${PORT} currently requires the following libraries from the system package manager:\n    libxmu-dev\n    libxi-dev\n    libgl-dev\n\nThese can be installed on Ubuntu systems via
Updated, thanks!

2021-07-07 16:26 UTC, merged