[restc-cpp] make using boost-log an optional feature
microsoft/vcpkg pull request #18683
Opened 2021-06-28 16:07 UTC by sandro97git

This disables logging with boost-log by default and makes it an optional feature. This also solves the problem that this library configures boost-log to link dynamically which leads to problems on linux where vcpkg links statically by default.

2021-06-28 23:44 UTC, NancyLi1013 requested changes

2021-06-28 23:44 UTC, NancyLi1013 commented on ports/restc-cpp/portfile.cmake
>      openssl       RESTC_CPP_WITH_TLS
```suggestion
    FEATURES 
        openssl       RESTC_CPP_WITH_TLS
```

2021-06-28 23:44 UTC, NancyLi1013 commented on ports/restc-cpp/vcpkg.json
>    "features": {
Could you please also update version in this files?

Add `"port-version": 1,` below  `"version-semver": "0.10.0",`. Namely like this:

```
"version-semver": "0.10.0",
"port-version": 1,
```

2021-06-29 06:59 UTC, NancyLi1013 approved these changes

2021-06-29 07:00 UTC, NancyLi1013 commented
Have you tested this feature `boost-log`? Does it work fine?

2021-06-29 08:41 UTC, sandro97git commented
> Have you tested this feature `boost-log`? Does it work fine?
yes it works as intended

2021-06-30 07:36 UTC, sandro97git commented
Any hints on how I can fix the checks?

2021-07-01 06:50 UTC, NancyLi1013 commented
Please run `vcpkg x-add-version --overwrite-version restc-cpp` to solve the failures on x86-windows.

2021-07-20 07:13 UTC, NancyLi1013 commented
LGTM now, thanks for your PR @sandro97git.

2021-07-23 04:55 UTC, vicroms requested changes
Remove `boost-log`  from the main list of dependencies

```
  "dependencies": [
    "boost-chrono",
    "boost-context",
    "boost-coroutine",
    "boost-date-time",
    "boost-filesystem",
    "boost-log",
    "boost-program-options",
    "boost-system",
    "boost-uuid",
    "rapidjson"
  ],
  ```

2021-07-23 06:02 UTC, NancyLi1013 commented
It should be fine now, thanks for your review @vicroms.

2021-07-23 16:59 UTC, vicroms commented
missing a `boost-asio` dependency that was previously transitively supplied by `boost-log`

2021-07-26 00:27 UTC, merged