[geographiclib] Update to version 1.52
microsoft/vcpkg pull request #18694
Opened 2021-06-29 01:29 UTC by cffk

**Describe the pull request**

- #### What does your PR fix?  
  Update to version 1.52

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

2021-06-29 07:04 UTC, JonLiu1993 requested changes

2021-06-29 10:20 UTC, cffk commented on ports/geographiclib/vcpkg.json
> +  "version-string": "1.52",
Thanks, done.

2021-06-30 02:09 UTC, JonLiu1993 approved these changes

2021-06-30 02:18 UTC, JonLiu1993 commented
@cffk ,Have you tested the tool feature?

2021-06-30 03:22 UTC, cffk commented
> @cffk ,Have you tested the tool feature?

Yes, this works.

2021-07-01 14:35 UTC, merged

2021-07-01 14:36 UTC, ras0219-msft commented
Thanks for the update!