[gl3w] Fix download issue: certification failed
microsoft/vcpkg pull request #18846
Opened 2021-07-07 02:52 UTC by JackBoosY

2021-07-07 03:40 UTC, BillyONeal requested changes
I don't think we can just disable TLS; if anything we're soon going to be required to force *enable* TLS for things.

2021-07-07 03:41 UTC, BillyONeal commented
https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.Cryptography.10031

2021-07-07 09:46 UTC, JackBoosY commented
> Now, we have 2 ports depend on gl3w:
> 
> * `imgui` feature `opengl3-gl3w-binding`, but it's not a default feature.
> * `azure-kinect-sensor-sdk[core]` requires it.
> 
> If we skip it on the baseline, only one port is affected.

@BillyONeal

2021-07-08 01:25 UTC, BillyONeal commented
Closing this since it was resolved in a way that doesn't require disabling TLS in https://github.com/microsoft/vcpkg/pull/18858

2021-07-08 01:25 UTC, closed without merging