[PMDK] update to 1.11
microsoft/vcpkg pull request #18848
Opened 2021-07-07 08:31 UTC by JonLiu1993

Fix #18832 

Update PMDK to the latest version 1.11.0

Note : no feature need to tested

2021-07-08 02:30 UTC, NancyLi1013 approved these changes

2021-07-08 17:52 UTC, ras0219-msft requested changes

2021-07-08 17:52 UTC, ras0219-msft commented on ports/pmdk/remove-non-ascii-character.patch
>  diff --git a/src/libpmemobj/critnib.c b/src/libpmemobj/critnib.c
This patch file is no longer needed because upstream has removed the non-ascii characters from their sources

2021-07-09 02:26 UTC, JonLiu1993 commented on ports/pmdk/remove-non-ascii-character.patch
>  diff --git a/src/libpmemobj/critnib.c b/src/libpmemobj/critnib.c
Ok , I will delete it and resubmit

2021-07-13 20:06 UTC, merged

2021-07-13 20:06 UTC, ras0219-msft commented
LGTM, thanks!