[zstd] update to 1.5.0
microsoft/vcpkg pull request #18915
Opened 2021-07-12 07:54 UTC by JonLiu1993

Fix #18912 

Update zstd to the latest version 1.5.0

Note: no feature need to test

2021-08-12 12:55 UTC, xavier2k6 commented
@JonLiu1993 are the regressions genuine?

2021-08-13 02:48 UTC, JonLiu1993 commented
> @JonLiu1993 are the regressions genuine?

Sorry,I do not quite understand you.

2021-08-13 21:00 UTC, xavier2k6 commented
>Sorry, I do not quite understand you.

The test failures.

>##[error]REGRESSION: zstd:x64-uwp. If expected, add zstd:x64-uwp=fail to .\scripts\ci.baseline.txt.

>##[error]REGRESSION: zstd:arm-uwp. If expected, add zstd:arm-uwp=fail to .\scripts\ci.baseline.txt.

2021-08-16 06:39 UTC, JonLiu1993 commented
> > Sorry, I do not quite understand you.
> 
> The test failures.
> 
> > ##[error]REGRESSION: zstd:x64-uwp. If expected, add zstd:x64-uwp=fail to .\scripts\ci.baseline.txt.
> 
> > ##[error]REGRESSION: zstd:arm-uwp. If expected, add zstd:arm-uwp=fail to .\scripts\ci.baseline.txt.

I will fix it soon if I have time

2021-08-17 07:29 UTC, NancyLi1013 commented on ports/zstd/portfile.cmake
>  if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
```
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ZSTD_STATIC )
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" ZSTD_SHARED)
```
Please use the above way to choose static or dynamic build.

2021-08-17 07:29 UTC, NancyLi1013 requested changes

2021-08-17 07:29 UTC, NancyLi1013 commented on ports/zstd/portfile.cmake
>  file(WRITE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright "ZSTD is dual licensed - see LICENSE and COPYING files\n")
```suggestion
file(WRITE "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" "ZSTD is dual licensed - see LICENSE and COPYING files\n")
```

2021-08-24 08:35 UTC, NancyLi1013 approved these changes

2021-08-26 04:08 UTC, merged

2022-08-28 11:32 UTC, Tachi107 commented
@JonLiu1993 I believe that the `install_pkgpc` patch will become obsolete once/if https://github.com/facebook/zstd/pull/3252 gets merged. Notifying you just so you're aware.