[shaderc] Add fix for installing shaderc_util
microsoft/vcpkg pull request #18979
Opened 2021-07-16 20:15 UTC by chrismile

**Describe the pull request**

- #### What does your PR fix?  
  The current version of the port shaderc neither installs shaderc_combined nor shaderc_shared, which both combine the targets shaderc and shaderc_util. Currently, only shaderc is installed by the port. However, if a program uses functionality from shaderc_util, there is currently no way to link to it. Thus, this PR adds shaderc_util as an installation target.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

2021-07-19 08:28 UTC, NancyLi1013 requested changes

2021-07-19 08:28 UTC, NancyLi1013 commented on ports/shaderc/fix-install-shaderc_util.patch
> ++endif(SHADERC_ENABLE_INSTALL)
Seems we should install this target according to build type. Since it only supports static build. Please refer to this patch.
https://github.com/microsoft/vcpkg/blob/master/ports/shaderc/fix-build-type.patch

2021-07-19 09:44 UTC, chrismile commented on ports/shaderc/fix-install-shaderc_util.patch
> ++endif(SHADERC_ENABLE_INSTALL)
Thanks a lot for your change request! I added a check for "NOT BUILD_SHARED_LIBS", so hopefully this should be fixed now.

2021-07-20 06:12 UTC, NancyLi1013 commented on ports/shaderc/fix-install-shaderc_util.patch
> ++endif(SHADERC_ENABLE_INSTALL)
I wonder if we also need to add `if(NOT BUILD_SHARED_LIBS)` for https://github.com/google/shaderc/blob/main/libshaderc_util/CMakeLists.txt#L17. Since it seems like a static library. What do you think?

2021-07-20 09:25 UTC, chrismile commented on ports/shaderc/fix-install-shaderc_util.patch
> ++endif(SHADERC_ENABLE_INSTALL)
I think that `if(NOT BUILD_SHARED_LIBS)` can't be added in this case. Both shaderc (static library) and shaderc_shared (shared library) seem to reference shaderc_util with target_link_libraries. Here's the excerpt from the current (patched) version of libshaderc/CMakeLists.txt:

```CMake
set(SHADERC_LIBS
  glslang OSDependent OGLCompiler glslang ${CMAKE_THREAD_LIBS_INIT}
  shaderc_util
  SPIRV # from glslang
  SPIRV-Tools
)

if(NOT BUILD_SHARED_LIBS)
target_link_libraries(shaderc PRIVATE ${SHADERC_LIBS})
else()
target_link_libraries(shaderc_shared PRIVATE ${SHADERC_LIBS})
endif()
```

2021-07-23 06:35 UTC, NancyLi1013 approved these changes

2021-07-23 16:04 UTC, merged