Add draft port zipper
microsoft/vcpkg pull request #18990
Opened 2021-07-17 11:34 UTC by BullyWiiPlaza

This draft pull request adds the port zipper.

- #### What does your PR fix?  
No fixes.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
All, no.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Not necessary.

- **If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**  

Yes. Currently the port does not successfully install and generates the following error message:
```
D:\Cpp\vcpkg>vcpkg install zipper
Computing installation plan...
The following packages will be built and installed:
    zipper[core]:x64-windows -> 1.0.2
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\BullyWiiPlaza\AppData\Local\vcpkg\archives\aa\aa458309039f2b2786b772ecf06fffdcafa7d200a7f555705d83941626e58444.zip
Starting package 1/1: zipper:x64-windows
Building package zipper[core]:x64-windows...
-- Using D:/Cpp/vcpkg/downloads/sebastiandev-zipper-201627bd3dbfbf1b53f69af29b8b079a9f3ffb1c.tar.gz
-- Cleaning sources at D:/Cpp/vcpkg/buildtrees/zipper/src/9a9f3ffb1c-e3a21c6906.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Cpp/vcpkg/downloads/sebastiandev-zipper-201627bd3dbfbf1b53f69af29b8b079a9f3ffb1c.tar.gz
-- Using source at D:/Cpp/vcpkg/buildtrees/zipper/src/9a9f3ffb1c-e3a21c6906.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/Cpp/vcpkg/buildtrees/zipper/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Cpp\vcpkg\buildtrees\zipper\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/zipper/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package zipper:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zipper:x64-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.
```

Most of the code is taken from [this](https://github.com/microsoft/vcpkg/pull/4581) pull request. I'm unsure how to fix it so any help is welcome.

Related issue: https://github.com/microsoft/vcpkg/issues/2229

2021-07-19 08:09 UTC, NancyLi1013 requested changes

2021-07-19 08:09 UTC, NancyLi1013 commented on ports/zipper/vcpkg.json
> +	"dependencies": [
```suggestion
       "homepage": "https://github.com/sebastiandev/zipper",
	"dependencies": [
	{
	  "name": "vcpkg-cmake",
	  "host": true
	},
```
The dependent ports should be added here if using the new functions.

For vcpkg-cmake-config, please help confirm if we need to add [vcpkg_cmake_config_fixup](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/ports/vcpkg-cmake-config/vcpkg_cmake_config_fixup.md) in portfiel.cmake.

2021-07-19 08:09 UTC, NancyLi1013 commented on ports/zipper/zipper.patch
> ++# source_group(minizip FILES ${MINIZIP_SOURCES})
We prefer to use `if(0)` to disable these codes. Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#minimize-patches

2021-07-19 08:09 UTC, NancyLi1013 commented on ports/zipper/zipper.patch
> ++  add_library (${ZIPPER_LIBRARY} SHARED ${ZIPPER_SOURCES} ) #${MINIZIP_SOURCES} )
`${MINIZIP_SOURCES}` should be delated from this line instead of commenting this out if it is not needed.

2021-07-19 08:09 UTC, NancyLi1013 commented on ports/zipper/zipper.patch
> ++  add_library (${ZIPPER_LIBRARY}-static STATIC ${ZIPPER_SOURCES}) #${MINIZIP_SOURCES})
The same as above.

2021-07-19 20:17 UTC, BullyWiiPlaza commented
Hello @NancyLi1013
Thanks for all the suggestions, I applied them all. However, now the package still does not build with `cmake`. Can you please take a look into what the problem could be?

2021-07-20 03:03 UTC, NancyLi1013 commented
Seems you didn't run `.\vcpkg.exe format-manifest ./ports/zipper/vcpkg.json` to format manifest file.

I have done this now.

2021-07-20 03:08 UTC, NancyLi1013 commented
The new failures are like this:
```
CMake Error at CMakeLists.txt:273 (FILE):
  FILE COPY cannot find
  "D:/buildtrees/zipper/src/9184e4f518-42e9489d1e.clean/minizip/zip.h": No
  such file or directory.
```

2021-07-20 05:45 UTC, NancyLi1013 requested changes

2021-07-20 05:45 UTC, NancyLi1013 commented on ports/zipper/portfile.cmake
> +
```suggestion
```

2021-07-20 12:09 UTC, BullyWiiPlaza commented
@NancyLi1013 Thanks again, I applied all of your improvement suggestions. However, I still get a `cmake` build error but not the one you mentioned:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/Cpp/vcpkg/buildtrees/zipper/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Cpp\vcpkg\buildtrees\zipper\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:364 (vcpkg_execute_required_process)
  ports/zipper/portfile.cmake:9 (vcpkg_cmake_configure)
  scripts/ports.cmake:140 (include)


Error: Building package zipper:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zipper:x64-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.
```
Would you be so kind and help me resolve it so the port can potentially be merged into the master branch soon?

2021-07-23 06:57 UTC, NancyLi1013 commented
@BullyWiiPlaza 

I have fixed the build errors. Can you help test the usage of `zipper`? You can try to fix the problems if there is something wrong.

2021-07-23 11:39 UTC, BullyWiiPlaza commented
@NancyLi1013 Thanks a lot. I tested a clean clone of `vcpkg` and installing `zipper`. I also compiled a test `Visual Studio 2019` solution in `Debug` and `Release` mode as well as statically linked the `Release` mode binary. All worked perfectly. I also used `zipper` with `CMake` on `WSL Ubuntu` and compiling worked fine as well. [I just ran into a runtime bug](https://github.com/sebastiandev/zipper/issues/102) which I believe isn't related to adding this port to `vcpkg`.

2021-07-27 09:17 UTC, NancyLi1013 commented
Thanks for your feedback. The problem you encountered seems to be not related with vcpkg.

For the usage, I test static library on Windows, the headers cannot be found.

```
F:\18990\zipper\main.cpp(2): fatal error C1083: Cannot open include file: 'zipper/zipper.h': No such file or direc
tory [F:\18990\zipper\build\main.vcxproj]
```
Can you compile the project with static library successfully on your machine?

2021-07-27 11:06 UTC, BullyWiiPlaza commented
@NancyLi1013 Yes, I'm using a `Visual Studio` solution (`*.sln`) file for compiling the static binary using the `zipper` library by configuring it to use static libraries from `vcpkg` and to use the static runtime (`/MT`) as well.
![image](https://user-images.githubusercontent.com/7620135/127143534-bc106e32-3b27-46ae-80ac-371a4b8de33b.png)
![image](https://user-images.githubusercontent.com/7620135/127143570-1beeb97c-c949-48e0-a1de-fc61e3236325.png)
I didn't try using `CMake` on `Windows` since it's less convenient.

2021-07-28 07:45 UTC, NancyLi1013 commented
Thanks for your information. I will look into the problem on cmake project.

2022-02-15 09:25 UTC, LilyWangLL approved these changes

2022-02-16 00:29 UTC, BillyONeal commented on ports/zipper/portfile.cmake
> +vcpkg_from_github(
This needs to use the existing `minizip` port rather than trying to vendor it: https://github.com/microsoft/vcpkg/tree/master/ports/minizip

2022-02-16 00:30 UTC, BillyONeal requested changes
minizip needs to be devendored

2022-02-16 02:50 UTC, LilyWangLL commented on ports/zipper/portfile.cmake
> +vcpkg_from_github(
That's my oversight, I will change this soon.

2022-02-16 06:32 UTC, LilyWangLL commented
https://github.com/Lecrapouille/minizip is a new port, this PR need add `minizip` to VCPKG first. @BullyWiiPlaza

2022-02-16 18:11 UTC, BillyONeal commented
> https://github.com/Lecrapouille/minizip is a new port, this PR need add `minizip` to VCPKG first. @BullyWiiPlaza

It should already be there: https://github.com/microsoft/vcpkg/tree/master/ports/minizip

2022-05-06 08:37 UTC, LilyWangLL commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2022-05-06 08:37 UTC, closed without merging