[libidn2] Fixes for mingw and minor issues
microsoft/vcpkg pull request #19002
Opened 2021-07-19 05:41 UTC by dg0yt

- #### What does your PR fix?  
  - [x] Fixes building with mingw (needed for curl). For faster build, it uses the cmake build system which is also used for MSVC.
  - [x] Installs the pc file also for cmake builds.
  - [x] Modernizes the portfile
  - [ ] Use libunistring for non-windows systems [#18997]
 
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes, but I am still working on this PR.

2021-07-22 06:11 UTC, dg0yt commented
I can pick up libunistring in another PR. But this one is needed for updating curl.

2021-07-22 08:36 UTC, NancyLi1013 requested changes

2021-07-22 08:36 UTC, NancyLi1013 commented on ports/libidn2/portfile.cmake
>  else()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

2021-07-23 07:43 UTC, NancyLi1013 requested changes

2021-07-23 07:43 UTC, NancyLi1013 commented on ports/libidn2/portfile.cmake
>  if (VCPKG_TARGET_IS_WINDOWS)
```suggestion
if (VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_MINGW)
```
If using cmake to build on mingw, this condition is also required. I noticed that you add
```
{
      "name": "vcpkg-cmake",
      "host": true,
      "platform": "windows | mingw"
    }
```
in vcpkg.json file.

2021-07-23 08:03 UTC, dg0yt commented on ports/libidn2/portfile.cmake
>  if (VCPKG_TARGET_IS_WINDOWS)
Note that the platform expression in the manifest is not consistent with the script variables:
https://github.com/microsoft/vcpkg/blob/cdd51899f6ae3736bfbe936f9e387f86d4a63a58/scripts/cmake/vcpkg_common_definitions.cmake#L52-L55

2021-07-23 10:46 UTC, dg0yt commented on ports/libidn2/portfile.cmake
>  if (VCPKG_TARGET_IS_WINDOWS)
Verified again: Mingw uses cmake as expected. No change needed.

2021-07-26 08:19 UTC, NancyLi1013 approved these changes

2021-07-26 18:02 UTC, merged