[kf5package] new port
microsoft/vcpkg pull request #19195
Opened 2021-07-28 09:53 UTC by wrobelda

**Describe the pull request**

- #### What does your PR fix?  
  Adds new kf5package port. Depends on:
  - #19194. Will rebase once it gets merged.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All official are supported.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-08-27 03:06 UTC, JackBoosY requested changes

2021-08-30 14:19 UTC, wrobelda commented on ports/kf5archive/portfile.cmake
> +        24.patch # https://invent.kde.org/frameworks/karchive/-/merge_requests/24
@JackBoosY renamed.

2021-08-30 14:28 UTC, wrobelda commented on ports/kf5coreaddons/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/KF5CoreAddons)
As noted in another PR, this is required due to case-sensitivity.

2021-08-31 02:58 UTC, wrobelda commented on ports/kf5archive/23.patch
> +diff --git a/KF5ArchiveConfig.cmake.in b/KF5ArchiveConfig.cmake.in
ping @JackBoosY

2021-08-31 05:54 UTC, JackBoosY requested changes

2021-08-31 05:54 UTC, JackBoosY commented on ports/kf5archive/portfile.cmake
> -        -DBUILD_QTHELP_DOCS=OFF
The last question: why did you remove them? Are they removed in the source?

2021-08-31 05:54 UTC, JackBoosY commented on ports/kf5package/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSES/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright")
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSES/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-31 05:54 UTC, JackBoosY commented on ports/kf5coreaddons/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSES/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright")
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSES/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-31 05:54 UTC, JackBoosY commented on ports/kf5archive/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSES/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright")
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSES/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAMEcopyright)
```

2021-08-31 06:36 UTC, wrobelda commented on ports/kf5archive/portfile.cmake
> -        -DBUILD_QTHELP_DOCS=OFF
They were never in the source. It was a leftover from copy-and-paste.

2021-08-31 06:58 UTC, JackBoosY approved these changes

2021-08-31 06:59 UTC, JackBoosY commented
Huge work, thanks!

2021-09-01 18:47 UTC, ras0219-msft commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
This being needed only in static mode indicates that this is really a bug in a dependency that isn't propagating its needs correctly.

Could you dig a bit to determine where the iconv dependency is coming from?

2021-09-02 02:58 UTC, JackBoosY commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
My mistake, this patch should always be applied since all triplet use cmake to build this port.

2021-09-03 09:12 UTC, wrobelda commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
@JackBoosY sorry, I don't follow. My understanding is that this is only needed on macOS and Windows (static) because they do not pick up libiconv or pick up the wrong one (macOS)?

2021-09-06 23:37 UTC, wrobelda commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
@ras0219 I checked what's happening on macOS (Windows to follow) and see the following:

1. Build fails with:
```
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_iconv_open", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_libiconv_set_relocation_prefix", referenced from:
      _libintl_set_relocation_prefix in libintl.a(relocatable.o)
```
2. CMake used vcpkg's own `libintl.a` in this case – from CMakeCache.txt:
`LibIntl_LIBRARIES:FILEPATH=/Users/cromo/Documents/Sourcecode/vcpkg/installed/arm64-osx/debug/lib/libintl.a`

Frankly speaking, not sure what should be done here. `gettext` depends on `libiconv`, but it doesn't come with CMake config nor `.pc`, so for static builds that dependency is not passed over?

2021-09-07 00:39 UTC, wrobelda commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
@ras0219-msft @JackBoosY I located the common dependency that hasn't propagated Iconv down (#20016) and removed patches from this port. #20016 will have to be merged first, though.

2021-09-07 21:02 UTC, wrobelda commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
@dg0yt I suppose you may have some input here, given your experience with `gettext`/`libintl`?

2021-09-08 04:16 UTC, dg0yt commented on ports/kf5package/portfile.cmake
> +    list(APPEND PATCHES fix_libiconv.patch)
@wrobelda `gettext` / `libintl` is a different story. But from `gdal`, I know that lots of ports do not properly export their transitive dependencies.

> Frankly speaking, not sure what should be done here. gettext depends on libiconv, but it doesn't come with CMake config nor .pc, so for static builds that dependency is not passed over?

We might add dependencies via the cmake wrapper. (For one port I even added a pc file.)

2021-09-10 05:46 UTC, JackBoosY commented
/azp run

2021-09-10 05:53 UTC, JackBoosY commented
All tests passed, ready for review now?

2021-09-10 07:43 UTC, JackBoosY commented
Requies #20090.

2021-09-10 12:14 UTC, wrobelda commented
> Requies #20090.

@JackBoosY not really, the #20016 provided all the fixes for `kf5i18n`. Once #20090 gets merged, I'll update `kf5i18n` and remove its patch. In the meanwhile #20016 was merged to master already, so I rebased this PR and it's good to go.

2021-09-13 02:11 UTC, JackBoosY approved these changes

2021-09-14 02:34 UTC, JackBoosY commented
I need my colleague to review this PR further to prevent anything being missed.

2021-09-14 02:46 UTC, merged

2021-09-14 02:46 UTC, BillyONeal commented
Thank you :D