[kf5solid] new port
microsoft/vcpkg pull request #19201
Opened 2021-07-28 13:06 UTC by wrobelda

**Describe the pull request**

- #### What does your PR fix?  
  Adds new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All official.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

2021-07-29 06:11 UTC, JonLiu1993 requested changes

2021-07-29 06:11 UTC, JonLiu1993 commented on ports/kf5solid/portfile.cmake
> +    PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"

```

2021-07-29 06:11 UTC, JonLiu1993 commented on ports/kf5solid/portfile.cmake
> +vcpkg_install_cmake()
```suggestion
vcpkg_cmake_install()

```

2021-07-29 06:11 UTC, JonLiu1993 commented on ports/kf5solid/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/KF5Solid)
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/KF5Solid)

```

2021-07-29 06:11 UTC, JonLiu1993 commented on ports/kf5solid/vcpkg.json
> +  "version-string": "5.84.0",
```suggestion
  "version-semver": "5.84.0",
```

2021-07-29 06:11 UTC, JonLiu1993 commented on ports/kf5solid/vcpkg.json
> +  ]
```suggestion
    "qt5-base",
    "qt5-tools",
    {
      "name": vcpkg-cmake,
      "host": true
    },
    {
      "name": vcpkg-cmake-config,
      "host": true
    }
  ]
```

2021-07-29 09:54 UTC, wrobelda reviewed
@JonLiu1993  Replaced outdated functions. All fixed now.

2021-07-30 08:35 UTC, JonLiu1993 commented on ports/kf5solid/portfile.cmake
> +        BUILD_QTHELP_DOCS
@wrobelda ,I checked CMakeLists.txt, these options do not exist,

2021-07-30 08:36 UTC, JonLiu1993 commented
Can you please resolve the conflicts against master?

2021-07-30 08:54 UTC, wrobelda commented on ports/kf5solid/portfile.cmake
> +        BUILD_QTHELP_DOCS
@JackBoosY, as mentioned in another PRs, these are standard KDE variables used across KDE/QT software. If at any point a library adds a manual or HTML docs, these will apply. I thought that it makes sense for consistency with other frameworks where such variables are already present in their CMakeLists.txt.

2021-07-30 09:33 UTC, wrobelda commented on ports/kf5solid/portfile.cmake
> +        BUILD_QTHELP_DOCS
I removed them based on the discussion here: https://github.com/microsoft/vcpkg/pull/19245#pullrequestreview-718841990

2021-07-30 10:43 UTC, wrobelda commented
> Can you please resolve the conflicts against master?

Done

2021-08-02 07:02 UTC, JonLiu1993 approved these changes

2021-08-02 23:49 UTC, merged