[kf5jobwidgets] new port
microsoft/vcpkg pull request #19200
Opened 2021-07-28 12:46 UTC by wrobelda

**Describe the pull request**

- #### What does your PR fix?  
  Adds new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All official.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

2021-07-29 06:49 UTC, JonLiu1993 requested changes

2021-07-29 06:49 UTC, JonLiu1993 commented on ports/kf5jobwidgets/portfile.cmake
> +    PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"

```

2021-07-29 06:49 UTC, JonLiu1993 commented on ports/kf5jobwidgets/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/KF5JobWidgets)
```suggestion
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/KF5JobWidgets)

```

2021-07-29 06:49 UTC, JonLiu1993 commented on ports/kf5jobwidgets/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSES/ DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/etc")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

file(INSTALL "${SOURCE_PATH}/LICENSES" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-07-29 06:49 UTC, JonLiu1993 commented on ports/kf5jobwidgets/vcpkg.json
> +  "version-string": "5.84.0",
```suggestion
  "version-semver": "5.84.0",
```

2021-07-29 06:49 UTC, JonLiu1993 commented on ports/kf5jobwidgets/vcpkg.json
> +  ]
```suggestion
      "platform": "linux"
    },
    {
      "name": vcpkg-cmake,
      "host": true
    },
    {
      "name": vcpkg-cmake-config,
      "host": true
    }
  ]
```

2021-07-29 10:59 UTC, wrobelda commented on ports/kf5jobwidgets/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSES/ DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
${SOURCE_PATH}/LICENSES/ is a folder, not a file, and it contains several SPDX license files which all need to be copied to "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" folder. The syntax I used does exactly that.

2021-07-29 11:58 UTC, wrobelda commented
@JonLiu1993 all fixed now

2021-07-30 01:49 UTC, JonLiu1993 commented on ports/kf5jobwidgets/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSES/ DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
Sorry,I made a mistake

2021-07-30 08:25 UTC, JonLiu1993 commented on ports/kf5jobwidgets/portfile.cmake
> +        BUILD_QTHELP_DOCS
@wrobelda ,I checked CMakeLists.txt, these options do not exist,

2021-07-30 08:54 UTC, wrobelda commented on ports/kf5jobwidgets/portfile.cmake
> +        BUILD_QTHELP_DOCS
@JonLiu1993, as mentioned in another PR, these are standard KDE variables used across KDE/QT software. If at any point a library adds a manual or HTML docs, these will apply. I thought that it makes sense for consistency with other frameworks where such variables are already present in their CMakeLists.txt.

2021-07-30 09:35 UTC, wrobelda commented on ports/kf5jobwidgets/portfile.cmake
> +        BUILD_QTHELP_DOCS
I removed them based on the discussion here: #19245

2021-08-02 07:00 UTC, JonLiu1993 approved these changes

2021-08-02 23:50 UTC, merged