[kf5guiaddons] fix Wayland scanner not being found by transitive deps
microsoft/vcpkg pull request #19203
Opened 2021-07-28 14:34 UTC by wrobelda

**Describe the pull request**

- #### What does your PR fix?  
  Transitive dependencies are not able to find the QtWaylandScanner_EXECUTABLE, which was explicitly provided to cmake as a parameter, but not passed down. This adds it to `KF5GuiAddonsConfig.cmake` so that dependencies compile fine.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

2021-07-29 03:14 UTC, NancyLi1013 requested changes

2021-07-29 03:14 UTC, NancyLi1013 commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
Why do you remove this line?

2021-07-29 09:52 UTC, wrobelda commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
This was a leftover from a copy and paste. This specific port does not currently install anything to `/etc`, but it might in the future and there's no reason to assume upfront that whatever would be copied there wouldn't be necessary.

2021-07-29 09:58 UTC, Neumann-A commented on ports/kf5guiaddons/fix_cmake.patch
> ++        set(QtWaylandScanner_EXECUTABLE "${CURRENT_INSTALLED_DIR}/tools/qt5-wayland/bin/qtwaylandscanner")
isn't there a target for this in the Qt configs ?

2021-07-29 09:59 UTC, Neumann-A commented on ports/kf5guiaddons/fix_cmake.patch
> ++        set(QtWaylandScanner_EXECUTABLE "${CURRENT_INSTALLED_DIR}/tools/qt5-wayland/bin/qtwaylandscanner")
Also this is probably a host dependency so this breaks cross builds.

2021-07-29 21:05 UTC, wrobelda commented on ports/kf5guiaddons/fix_cmake.patch
> ++        set(QtWaylandScanner_EXECUTABLE "${CURRENT_INSTALLED_DIR}/tools/qt5-wayland/bin/qtwaylandscanner")
@Neumann-A there is in 6.2: https://github.com/qt/qtwayland/blob/6.2/src/qtwaylandscanner/CMakeLists.txt
Not sure how that works for qmake in qt5

2021-07-30 01:37 UTC, NancyLi1013 commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
If so, we should also keep `debug/etc` folder. Given that there is no anything installed to `/etc`. We can remove in current version until there is no empty folder in the future.

2021-07-30 10:15 UTC, wrobelda commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
@NancyLi1013 fixed

2021-07-30 10:31 UTC, wrobelda commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
Fixed

2021-08-02 07:48 UTC, NancyLi1013 commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
Seems you misunderstand what I mean. We can keep it as before, since these folders are empty. It's unnecessary to keep empty folders.
```
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/etc)
```

Is `data `the same case with `etc`? If so, please use the same way to handle it.

2021-08-03 21:45 UTC, wrobelda commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
>  We can keep it as before, since these folders are empty. It's unnecessary to keep empty folders.

This would also mean that each time I upgraded these ports after new version upstream got released, I'd have to remove those lines again to double check if by any chance some new files were not added to those (previously) empty folders – on each platform. This seems like unnecessary burden for maintainers for a very little (if any at all) gain?

2021-08-04 02:19 UTC, NancyLi1013 commented
Need to resolve the conflicts..

2021-08-04 02:22 UTC, NancyLi1013 commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
Empty folders should be removed.

2021-08-04 22:13 UTC, wrobelda commented on ports/kf5guiaddons/portfile.cmake
> -file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
> If so, we should also keep debug/etc folder. Given that there is no anything installed to /etc. We can remove in current version until there is no empty folder in the future.

I just checked the `installed/vcpkg/info/kf5guiaddons*.list` file and I don't say *any* empty folders there even if I remove the lines. Do you? If not, then we don't have any issue here at all.

2021-08-05 06:10 UTC, NancyLi1013 commented
```
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:421 (message):
  The following variables are not used in CMakeLists.txt:

      QtWaylandScanner_EXECUTABLE

  Please recheck them and remove the unnecessary options from the
  `vcpkg_configure_cmake` call.
```
Seems need to add `QtWaylandScanner_EXECUTABLE` to `MAYBE_UNUSED_VARIABLES`.

2021-08-07 13:28 UTC, wrobelda commented
> Seems need to add `QtWaylandScanner_EXECUTABLE` to `MAYBE_UNUSED_VARIABLES`.

Done.

2021-08-09 02:08 UTC, NancyLi1013 approved these changes

2021-08-09 02:12 UTC, NancyLi1013 commented
So you should have tested the feature `wayland`, right? @wrobelda

2021-08-09 21:37 UTC, wrobelda commented
> So you should have tested the feature `wayland`, right? @wrobelda

This has been tested by #16562, which depends on this fix – the Linux package would not build without it. 
FYI, I updated the port with some additional improvements, so please re-check.

2021-08-30 03:05 UTC, JackBoosY commented on ports/kf5guiaddons/fix_cmake.patch
> ++        set(QtWaylandScanner_EXECUTABLE "${CURRENT_INSTALLED_DIR}/tools/qt5-wayland/bin/qtwaylandscanner")
All tool dependencies should be set to host.

2021-08-30 17:04 UTC, merged

2021-08-30 17:04 UTC, BillyONeal commented
Thanks for your contribution!