[Bullet] fixes config failures.
microsoft/vcpkg pull request #19236
Opened 2021-07-29 21:49 UTC by mathisloge

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19234
 Fixes #19172

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
think so

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes
- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

2021-07-29 21:57 UTC, mathisloge commented
tensorflow fails with 
```
You have bazel 4.1.0 installed.
Please downgrade your bazel installation to version 3.99.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
```

So this should not be a thing on my side.

2021-08-02 10:53 UTC, JonLiu1993 requested changes

2021-08-02 10:53 UTC, JonLiu1993 commented on ports/bullet3/vcpkg.json
> +  "version-string": "3.17",
```suggestion
  "version": "3.17",
```

2021-08-02 23:19 UTC, bttner commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
I am running Ubuntu 20.04, CMake 3.21.1, and this pull request fixed the problem `Unknown CMake command "set_and_check"`  for me (#19234 and #19172). However, as also mentioned in #19172, the proposed item order in target_link_libraries leads to a compiling error (e.g., undefined reference to ...) when running the make command. One can easily reproduce this error by using _HelloWorld.cpp_ in _bullet3/examples/HelloWorld_ and 
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/6920032/CMakeLists.txt). Using `target_link_libraries(main PRIVATE BulletSoftBody BulletDynamics BulletCollision Bullet3Common LinearMath)` instead solves the issue, at least for me.

2021-08-03 06:54 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
Please see the changed usage file. That will resolve this issue too

2021-08-03 07:05 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
```` include(${BULLET_USE_FILE}) ``` after find_package

2021-08-03 08:11 UTC, JackBoosY commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
This file only add the usage cmake code, so we don't need it.

2021-08-03 08:18 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
i don't quite understand your comment @JackBoosY . 
The `include(${BULLET_USE_FILE})` is required after `find_package` because it adds the library paths etc. to the library search dir. `LinearMath` is only a library name. It doesn't have a cmake target from upstream. So this would resolve to something like `LinearMath.a or LinearMath.lib`

2021-08-03 08:19 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
so the usage file should definitly be appended to the port since it highlights the needed `include(${BULLET_USE_FILE})`

2021-08-03 08:24 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
Just for reference, the BULLET_USE_FILE has the following contents: 
```
add_definitions     ( ${BULLET_DEFINITIONS} )
include_directories ( ${BULLET_INCLUDE_DIRS} )
link_directories    ( ${BULLET_LIBRARY_DIRS} )
```

2021-08-03 09:21 UTC, JackBoosY commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
> Just for reference, the BULLET_USE_FILE has the following contents: 
```
add_definitions     ( ${BULLET_DEFINITIONS} )
include_directories ( ${BULLET_INCLUDE_DIRS} )
link_directories    ( ${BULLET_LIBRARY_DIRS} )
```
According to this content, the only purpose of this file is to automatically use this port in private projects. This approach will cause the target in the project to be unable to be exported and overlap with the rest of the usage. 
So I don’t think we need them.

2021-08-03 09:31 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
This is needed. If you don't use BULLET_USE_FILE it will lead to link errors since `LinearMath` might not be found. It isn't in the library search path for the linker. It all is provided from upstream. Again if you don't use `BULLET_USE_FILE` it will lead to link errors. Or you add the `BULLET_LIBRARY_DIRS` to the library search path yourself.

2021-08-03 12:52 UTC, bttner commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
As can be seen in the linked file - CMakeLists.txt - in my comment, I put

> `include(${BULLET_USE_FILE})` after find_package

but still run into compiling errors when running make. Only after I set `target_link_libraries(HelloWorld PRIVATE BulletSoftBody BulletDynamics BulletCollision Bullet3Common LinearMath)` my project compiled. Thus, the order in target_link_libraries seems important and can not be set arbitrary. 

Regarding the use of `include(${BULLET_USE_FILE})`. When I exclude that line, I run into linking errors, e.g., `fatal error: btBulletDynamicsCommon.h: No such file or directory`.

Overall, I suggest to simply change `target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)` to `target_link_libraries(HelloWorld PRIVATE BulletSoftBody BulletDynamics BulletCollision Bullet3Common LinearMath)`. At least in my case, everything works as expected then.

2021-08-03 12:56 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
That doesn't work for me in a completly new project. 
Could you confirm that the error persists if you clean your build dir and reconfigure?

Because the order of the libraries don't have any effect for me.

2021-08-03 13:48 UTC, bttner commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
Ok, probably I am doing something wrong. I just did the following:

1. `$ git clone https://github.com/mathisloge/vcpkg.git`, `$ ./vcpkg/bootstrap-vcpkg.sh` and `$ ./vcpkg/vcpkg install bullet3`
2. `$ mkdir HelloWorld`, copied [HelloWorld.cpp](https://github.com/bulletphysics/bullet3/blob/master/examples/HelloWorld/HelloWorld.cpp) and the mentioned CMakeLists.txt into it.
3. `$ cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/...` works.
4. `$ cmake --build [build directory]` only works when I set `target_link_libraries(main PRIVATE BulletSoftBody BulletDynamics BulletCollision Bullet3Common LinearMath)`. Otherwise, I get a lot of error messages. The first reads `undefined reference to btDefaultCollisionConfiguration::btDefaultCollisionConfiguration(btDefaultCollisionConstructionInfo const&)`

2021-08-03 13:58 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
In step one you are changing to the branch `mathisloge:bullet-fix`? 

Are you cleaning your build dir between step 3 and 4? 
Otherwise it looks all correct. Maybe add `--config Debug --target all` to step 4

2021-08-03 14:06 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
But I just discovered some other problems regarding the vcpkg build structure. If you want to build for debug, you can't find the LinearMath lib since it is called `LinearMath_Debug` and in a different folder. I think i will need to add some patches or a own target for the lib.

2021-08-03 14:32 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
@bttner could you pull the new changes again? I've added the missing export targets. You could also remove the `include(${BULLET_USE_FILE})` and replace it with `target_include_directories(main PRIVATE ${BULLET_INCLUDE_DIRS})` after your `add_executable` call.

2021-08-03 15:18 UTC, bttner commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
Yes, I changed to the branch `mathisloge:bullet-fix` and therefore am using bullet3[core]:x64-linux -> 3.17#1. Furthermore, in the fourth step I do `--config Debug --target all --clean first`. Despite all my efforts, however, I always run into the same issue. Have you tried the provided example project yourself and it compiles without errors?

2021-08-03 15:46 UTC, mathisloge commented on ports/bullet3/usage
>  target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)
have you tried the updates i've pushed? 

The `clean-first` option has some strange side effects. Run `--target clean` run the configure step, and then build without `--clean-first`

2021-08-03 19:41 UTC, mathisloge commented
@JackBoosY PR is ready to review. I've added the last remaining targets and updated the usage file. 
This takes the file structure layout of vcpkg into accout (lib or debug/lib). 
I've tested with ubuntu and windows the HelloWorld program of bullet3 without any linkage errors (debug and release)

2021-08-04 01:59 UTC, JackBoosY commented on ports/bullet3/usage
> +target_include_directories(main PRIVATE ${BULLET_INCLUDE_DIRS})
For those content, I'll help you to fix that.

2021-08-04 09:24 UTC, mathisloge commented on ports/bullet3/usage
> +target_include_directories(main PRIVATE ${BULLET_INCLUDE_DIRS})
I've added the include dirs to each target and checked if they match with what upstream expects.

2021-08-04 09:50 UTC, JackBoosY commented
@mathisloge  In fact, there are still some other issue:
- LinearMath should be dependent on some other components
- The generated cmake file should be in _share/bullet_

And I'm fixing them now.

2021-08-04 10:03 UTC, JackBoosY commented
Since I have no permission to push my changes to this branch, please use my changes:
[bullet3.zip](https://github.com/microsoft/vcpkg/files/6930388/bullet3.zip)

2021-08-04 10:16 UTC, mathisloge commented
@JackBoosY thanks for the fixes. 

Maybe you should get the maintainer role to get access? 
![image](https://user-images.githubusercontent.com/13556116/128164625-ed9ef833-4b2d-4cf5-8963-4f6afa274854.png)

2021-08-05 02:34 UTC, JackBoosY requested changes

2021-08-05 02:34 UTC, JackBoosY commented on ports/bullet3/cmake-fix.patch
> +diff --git a/BulletConfig.cmake.in b/BulletConfig.cmake.in
Can you please change this file's EOL?

2021-08-05 09:43 UTC, mathisloge commented on ports/bullet3/cmake-fix.patch
> +diff --git a/BulletConfig.cmake.in b/BulletConfig.cmake.in
have changed to LF

2021-08-05 09:49 UTC, JackBoosY approved these changes

2021-08-06 02:17 UTC, JonLiu1993 approved these changes

2021-08-06 02:18 UTC, JonLiu1993 commented
Feature multithreading tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2021-08-10 21:54 UTC, mathisloge commented
will someone merge this?

2021-08-11 01:59 UTC, JonLiu1993 commented
@dan-shaw ,Could you please help merge this pr?

2021-08-20 21:46 UTC, mathisloge commented
Will anyone merge this?

2021-08-31 19:55 UTC, merged

2021-08-31 19:56 UTC, BillyONeal commented
Sorry for the delay, thanks for your contribution!