[oatpp-openssl] new port
microsoft/vcpkg pull request #19265
Opened 2021-07-31 12:15 UTC by mheyman

This is a new port for the *oatpp* suite of ports. Oat++ added an openssl module and this port provides access to that module.

This port can be helpful for those that wanted to use the `openssl` port and the `oatpp-libressl` port at the same time which is difficult because of conflicts between the `openssl` and `libressl` ports (`oatpp-libressl`, not surprisingly, depends on `libressl`). With this, `oatpp-openssl` is a drop-in replacement for `oatpp-libressl` without the conflicts.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all (I believe, linux and windows tested, including `x64-windows-static-md`)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-08-02 06:24 UTC, NancyLi1013 requested changes

2021-08-02 06:24 UTC, NancyLi1013 commented on ports/oatpp-openssl/portfile.cmake
> +    PREFER_NINJA
```suggestion
```
This parameter is not needed here, please see the [doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/ports/vcpkg-cmake/vcpkg_cmake_configure.md).

2021-08-02 06:24 UTC, NancyLi1013 commented on ports/oatpp-openssl/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/oatpp-openssl-${OATPP_VERSION})
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/oatpp-openssl-${OATPP_VERSION}")
```
We suggest to add quotes to path. Please see the [doc ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/cmake-guidelines.md).

2021-08-02 06:24 UTC, NancyLi1013 commented on ports/oatpp-openssl/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```
The same as above.

2021-08-02 06:24 UTC, NancyLi1013 commented on ports/oatpp-openssl/vcpkg.json
> +  "version": "1.2.5",
```suggestion
  "version-semver": "1.2.5",
```
It would be better severed by [version-semver](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-semver) here.

2021-08-02 18:28 UTC, mheyman commented on ports/oatpp-openssl/vcpkg.json
> +  "version": "1.2.5",
done ;-)

2021-08-02 18:36 UTC, mheyman commented on ports/oatpp-openssl/portfile.cmake
> +    PREFER_NINJA
done

2021-08-02 18:36 UTC, mheyman commented on ports/oatpp-openssl/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/oatpp-openssl-${OATPP_VERSION})
done

2021-08-02 18:37 UTC, mheyman commented on ports/oatpp-openssl/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
and done.

2021-08-03 17:11 UTC, ras0219 commented on ports/oatpp-openssl/portfile.cmake
> +        "-DCMAKE_CXX_FLAGS=-D_CRT_SECURE_NO_WARNINGS"
```suggestion
```

Portfiles must not add flags via `CMAKE_CXX_FLAGS`; instead it's best to add a small patch injecting an `add_definitions()` into the `CMakeLists.txt`.

2021-08-07 09:41 UTC, mheyman commented on ports/oatpp-openssl/portfile.cmake
> +        "-DCMAKE_CXX_FLAGS=-D_CRT_SECURE_NO_WARNINGS"
Doh! Didn't see that when I copy-pasted from `oatpp-libressl`'s portfile. Fixed now...

2021-08-09 02:00 UTC, NancyLi1013 approved these changes

2021-09-01 18:48 UTC, merged

2021-09-01 18:48 UTC, ras0219-msft commented
LGTM, thanks for the PR and sorry for the long merge delay!