[wxwidgets] make wxUSE_STL an optional feature disabled by default
microsoft/vcpkg pull request #19274
Opened 2021-08-01 02:49 UTC by Be-ing

wxUSE_STL defaults to OFF so that is how it is in Linux
distribution packages. Downstream projects developed with
wxUSE_STL=ON are not necessarily compatible with wxUSE_STL=OFF
without modification. So, by default, go with wxWidgets' default
for compatibility with downstream codebases. vcpkg users who need
wxUSE_STL=ON can still do so by simply opting into the new 'stl'
feature of this port.

https://forums.wxwidgets.org/viewtopic.php?p=165208

**Describe the pull request**

- #### What does your PR fix?  
  Fixes downstream applications not building with wxwidgets port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-08-02 06:03 UTC, PhoebeHui approved these changes
LGTM

2021-08-02 06:23 UTC, JackBoosY approved these changes

2021-08-02 06:40 UTC, dg0yt commented
I would like to ask for clarificiation whether this feature is additive and compatible with binary caching:
- How does it affect ABI?
- How does it affect the library's backward compatibility.
- Basically, it Port B requires wxwidgets[stl], will it break Port A which was built agains wxwidgets?

2021-08-02 12:17 UTC, Be-ing commented
wxUSE_STL=ON and wxUSE_STL=OFF are not source compatible so I can't imagine they would be ABI compatible.

2021-08-02 13:35 UTC, dg0yt commented
> wxUSE_STL=ON and wxUSE_STL=OFF are not source compatible so I don't imagine they would be ABI compatible.
> 
> > Basically, it Port B requires wxwidgets[stl], may it break Port A which was built agains wxwidgets[core]?
> 
> I suppose so.

This is the list of "Do not" for features: 
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#features

I get the impression that the proposed feature is in conflict with at least one item.

2021-08-02 13:38 UTC, Be-ing commented
The only alternatives are:
* Keep this port as-is and make it unusable for lots of wxWidgets applications.
* Provide no option and only use wxUSE_STL=OFF which would make the upstream port unusable if anyone was previously depending on wxUSE_STL=ON.

2021-08-02 13:41 UTC, Be-ing commented
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-control-alternatives-in-published-interfaces lists some exceptions made for backwards compatibility. I think this case should have an exception made for backwards compatibility.

2021-08-02 16:29 UTC, dg0yt commented
> I think this case should have an exception made for backwards compatibility.

Don't misunderstand backwards compatibility and the existing exceptions: These ports already had a broken feature list. The feature were *left* for backwards compatibility.

> The only alternatives are:
> 
> * Keep this port as-is which is unusable for lots of wxWidgets applications.
> * Provide no option and only use wxUSE_STL=OFF which would make the upstream port unusable if anyone was previously depending on wxUSE_STL=ON.

There is more:

 * Let the user use overlay ports to change the default.
 * Use another variable in the portfile, and let users override this variable in *custom triplets* if needed.

2021-08-02 16:32 UTC, Be-ing commented
> Let the user use overlay ports to change the default.

I don't think this is a good idea because the port currently does not work with downstream codebases that were developed with wxWidget's default of wxUSE_STL=OFF.

> Use another variable in the portfile, and let users override this variable in custom triplets if needed.

This would be quite cumbersome. I don't know why that would be better than a port feature.

2021-08-02 16:49 UTC, dg0yt commented
> > Use another variable in the portfile, and let users override this variable in custom triplets if needed.
> 
> This would be quite cumbersome. I don't know why that would be better than a port feature.

It creates an entire consistent universe of compatible binaries bound to that particular triplet. 

With features, this is not possible: The binaries created from `wxwidgets[stl]` are incompatible with ports depending on `wxwidgets[core]`  as far as we are told. This is not additive.

2021-08-02 16:52 UTC, Be-ing commented
I would be annoyed if I had to use a custom triplet just to use wxWidgets with its upstream defaults. But if that's what the vcpkg maintainers decide, it should be documented.

2021-08-05 23:07 UTC, strega-nil-ms commented
Do you have a repro? I'm trying to figure out why this is necessary, except for the `wxUSE_STL_BASED_WXSTRING` stuff (which we could fix by defining that).

2021-08-06 00:10 UTC, Be-ing commented
Unfortunately due to other bugs in the wxwidgets port (#17111) I cannot tell you how to reproduce this with the wxwidgets port in vcpkg. I am working with this branch of Tenacity: https://github.com/tenacityteam/tenacity/pull/228 This branch is still very much a work-in-progress and I am force pushing frequently.

When I tried to build that branch with the wxwidgets port in vcpkg which uses wxUSE_STL=ON, the build failed [with these errors](https://github.com/tenacityteam/tenacity/pull/228#issuecomment-880113285). When I build wxwidgets manually without vcpkg using the default wxUSE_STL=OFF, I am able to build that branch.

2021-08-06 02:25 UTC, JackBoosY commented
> I am working with this branch of Tenacity: [tenacityteam/tenacity#228](https://github.com/tenacityteam/tenacity/pull/228) This branch is still very much a work-in-progress and I am force pushing frequently.
> 
> When I tried to build that branch with the wxwidgets port in [wxWidgets/wxWidgets#2402](https://github.com/wxWidgets/wxWidgets/pull/2402) which uses wxUSE_STL=ON, the build failed [with these errors](https://github.com/tenacityteam/tenacity/pull/228#issuecomment-880113285). When I build wxwidgets manually without vcpkg using the default wxUSE_STL=OFF, I am able to build that branch. When I rebuilt wxwidgets manually with wxUSE_STL=ON, I reproduced the compile errors.

Those failures are due to the upstream doesn't handle the library path. See https://github.com/wxWidgets/wxWidgets/pull/2402.

2021-08-06 04:53 UTC, talregev commented
@JackBoosY Will you help us to continue the PR that solve the problems?

2021-08-06 16:05 UTC, Be-ing commented
> Those failures are due to the upstream doesn't handle the library path. See wxWidgets/wxWidgets#2402.

Yes the first error I posted in https://github.com/tenacityteam/tenacity/pull/228#issuecomment-880113285 was due to that upstream bug. But then I ran into the compile errors because of wxUSE_STL=ON.

2021-08-06 16:07 UTC, Be-ing commented
https://docs.wxwidgets.org/3.0/classwx_string.html has this note:

> If you built wxWidgets with wxUSE_STL set to 1, the implicit conversions to both narrow and wide C strings are disabled and replaced with implicit conversions to std::string and std::wstring.

I think this is the source of the compile error I encountered with wxUSE_STL=ON.

2021-08-06 19:56 UTC, strega-nil-ms commented
@Be-ing could you try instead with `wxUSE_STL=1`, and `wxUSE_STL_BASED_WXSTRING=0`?

2021-08-06 20:01 UTC, Be-ing commented
That's not an available CMake variable:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    wxUSE_STL_BASED_WXSTRING
```

2021-08-06 20:40 UTC, strega-nil-ms commented
urggh... okay, I think the best thing is to default to `-DwxUSE_STL=OFF` then, and allow for turning it back on.

2021-08-06 20:52 UTC, Be-ing commented
So merge this PR?

2021-08-09 16:57 UTC, strega-nil-ms commented
@Be-ing no, it shouldn't be a feature. Could you turn it off by default, and make turning it back on a triplet option?

2021-08-09 21:25 UTC, Be-ing commented
Okay, that sounds like a good solution. Is there documentation or an example how to do that? Just set the `wxUSE_STL` CMake option based on a CMake variable? Then users can choose to set that CMake variable in a custom triplet?

2021-08-09 22:15 UTC, Be-ing commented
Where would I document that the triplet option exists?

2021-08-10 06:38 UTC, dg0yt commented
> Where would I document that the triplet option exists?

Good question. Documentation exists for global triplet variables, but not for per-port variables. How about adding a sentence to the port's description field? In this way, it would be visible in online package search. E.g. 
~~~
To enable 'wxUSE_STL', set 'VCPKG_WXWIDGETS_USE_STL' to 'ON' in a custom triplet file.
~~~

2021-08-11 15:23 UTC, talregev requested changes

2021-08-11 15:23 UTC, talregev commented on ports/wxwidgets/portfile.cmake
> +if(NOT DEFINED WXWIDGETS_USE_STL)
In triplet, you can set only VCPKG_ prefix vars.
I am not sure where neet to add this var. 
https://vcpkg.readthedocs.io/en/latest/users/triplets/

2021-08-11 15:23 UTC, talregev commented on ports/wxwidgets/vcpkg.json
> +  "description": "a widget toolkit and tools library for creating graphical user interfaces (GUIs) for cross-platform applications. Set WXWIDGETS_USE_STL in a custom triplet to build with the wxUSE_S
Can you force it to next line? Because usually you cannot see long lines.
I think we also need to take care of it globally.

2021-08-11 15:56 UTC, Be-ing commented on ports/wxwidgets/portfile.cmake
> +if(NOT DEFINED WXWIDGETS_USE_STL)
Are you sure? All the global variables for vcpkg use the `VCPKG_` prefix but I don't know if this convention should be followed for port-specific variables.

2021-08-11 16:08 UTC, talregev commented on ports/wxwidgets/portfile.cmake
> +if(NOT DEFINED WXWIDGETS_USE_STL)
I know that from android, When I wanted to add some vars. It needed vcpkg_ prefix. also to add in some place.
I will let other here to comment that know this matter to explain it better.

2021-08-11 17:16 UTC, strega-nil-ms commented on ports/wxwidgets/portfile.cmake
> +if(NOT DEFINED WXWIDGETS_USE_STL)
No, `VCPKG_` should be used for vcpkg variables; for this kinda thing, WXWIDGETS is a perfectly fine prefix for the wxwidgets port.

2021-08-11 17:16 UTC, strega-nil-ms commented on ports/wxwidgets/vcpkg.json
> +  "description": "a widget toolkit and tools library for creating graphical user interfaces (GUIs) for cross-platform applications. Set WXWIDGETS_USE_STL in a custom triplet to build with the wxUSE_S
```suggestion
  "description": [
    "a widget toolkit and tools library for creating graphical user interfaces (GUIs) for cross-platform applications.",
    "Set WXWIDGETS_USE_STL in a custom triplet to build with the wxUSE_STL build option."
  ],
```

2021-08-11 17:17 UTC, strega-nil-ms approved these changes

2021-08-11 17:17 UTC, talregev commented on ports/wxwidgets/portfile.cmake
> +if(NOT DEFINED WXWIDGETS_USE_STL)
ok. I didn't know that. thank you for the correction.

2021-08-11 17:20 UTC, talregev approved these changes

2021-08-12 09:36 UTC, JackBoosY approved these changes

2021-08-19 14:34 UTC, Be-ing commented
This has been approved by 3 reviewers. Can it be merged?

2021-08-19 15:59 UTC, merged

2021-08-19 16:12 UTC, Be-ing commented
Thanks for reviewing. I am glad we found a solution that works with vcpkg's policies. Now, onto #17111...

2021-08-19 16:22 UTC, talregev commented
@Be-ing @JackBoosY 
> Now, onto #17111...
I so agree ...