[yaml-cpp] update to 0.7.0
microsoft/vcpkg pull request #19272
Opened 2021-07-31 18:35 UTC by autoantwort

Fixes #19255

2021-08-02 08:39 UTC, JonLiu1993 reviewed
@autoantwort ,Why delete the opencolorio-tools port?

2021-08-02 12:05 UTC, autoantwort commented
> @autoantwort ,Why delete the opencolorio-tools port?

Because it was simply a tools feature if the `opencolorio` port, I assume that was done when features were not supported in vcpkg so that they created a new `...-tools` port for that.

2021-08-02 21:29 UTC, ras0219 requested changes

2021-08-02 21:29 UTC, ras0219 commented on ports/opencolorio/fix-pystring-path.patch
> +-            pystring/pystring.h
This looks like we have a bug in `pystring` and the header should actually be at `pystring/pystring.h`. Considering `pystring` is owned by the same entity as `opencolorio`, I trust that their `Findpystring` module is correct.

Could you change `pystring` to install the header into `pystring/pystring.h` instead of adding this patch?

2021-08-02 21:29 UTC, ras0219 commented on ports/opencolorio/fix-half-version.patch
> ++set(_Half_LIB_VER "${Half_FIND_VERSION_MAJOR}_5")
This looks an awful lot like hardcoding in a specific version of the dependency; can we change this to use `find_package(OpenEXR CONFIG)` instead?

2021-08-02 21:29 UTC, ras0219 commented on ports/opencolorio/vcpkg.json
> +    "expat",
I see a dependency on `openimageio` which should either be explicitly disabled or added as a dep: https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/src/CMakeLists.txt#L11

2021-08-02 21:29 UTC, ras0219 commented on ports/opencolorio/vcpkg.json
> +        "lcms"
It looks like building the apps also depends on `GLEW`: https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/0021372b4dba3444e21a36d846b327efad054f8d/share/cmake/utils/CheckSupportGL.cmake#L10

2021-08-03 01:38 UTC, JonLiu1993 requested changes

2021-08-03 01:38 UTC, JonLiu1993 commented on ports/opencolorio/portfile.cmake
>      PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-08-03 01:38 UTC, JonLiu1993 commented on ports/opencolorio/portfile.cmake
>  file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-03 01:38 UTC, JonLiu1993 commented on ports/yaml-cpp/portfile.cmake
>      PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-08-03 01:38 UTC, JonLiu1993 commented on ports/yaml-cpp/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
```

2021-08-03 01:38 UTC, JonLiu1993 commented on ports/yaml-cpp/vcpkg.json
> +  "version": "0.7.0",
```suggestion
  "version-semver": "0.7.0",
```

2021-08-03 17:06 UTC, ras0219 commented on ports/yaml-cpp/vcpkg.json
> +  "version": "0.7.0",
Semver seems correct here.

2021-08-03 17:08 UTC, ras0219 commented on ports/yaml-cpp/vcpkg.json
> +  "homepage": "https://github.com/jbeder/yaml-cpp",
```suggestion
  "homepage": "https://github.com/jbeder/yaml-cpp",
  "documentation": "https://codedocs.xyz/jbeder/yaml-cpp/index.html",
```

2021-08-05 01:23 UTC, autoantwort commented on ports/opencolorio/fix-pystring-path.patch
> +-            pystring/pystring.h
Hm opencolorio uses a [custom build script](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/share/cmake/projects/Buildpystring.cmake) to build pystring and move it to the pystring folder, but the [original makefile](https://github.com/imageworks/pystring/blob/master/Makefile) does not do that.

2021-08-05 01:49 UTC, autoantwort commented on ports/opencolorio/vcpkg.json
> +    "expat",
Openimageio has an optional dependency on opencolorio, that can cause a circle.

2021-08-05 01:55 UTC, autoantwort commented on ports/yaml-cpp/vcpkg.json
> +  "version": "0.7.0",
Have you checked that the lib follows the strict semver rules?

2021-08-05 02:08 UTC, autoantwort commented
Thank you for your detailed review @ras0219 ❤️

2021-08-05 03:02 UTC, JonLiu1993 commented on ports/yaml-cpp/vcpkg.json
> +  "version": "0.7.0",
Yes, I checked the historical version records, "port-semver" is more suitable

2021-08-05 06:37 UTC, JonLiu1993 requested changes

2021-08-05 06:37 UTC, JonLiu1993 commented on ports/openimageio/portfile.cmake
> +    REF 099c8585e3add6f58fab9aa438a491fa55d3f67e # 2.2.16.0
```suggestion
    REF 099c8585e3add6f58fab9aa438a491fa55d3f67e # 2.2.17.0
```

2021-08-05 06:37 UTC, JonLiu1993 commented on ports/pystring/vcpkg.json
> +  "version-string": "1.1.3",
```suggestion
  "version-semver": "1.1.3",
```

2021-08-06 09:20 UTC, JonLiu1993 approved these changes

2021-08-10 08:11 UTC, merged