[fontconfig] update to 2.13.94
microsoft/vcpkg pull request #19285
Opened 2021-08-02 01:50 UTC by autoantwort

Updates the port and fixes #18172

2021-08-02 06:22 UTC, JackBoosY requested changes

2021-08-02 06:22 UTC, JackBoosY commented on ports/fontconfig/portfile.cmake
> +vcpkg_configure_meson(SOURCE_PATH ${SOURCE_PATH})
Hmm... we prefer to use cmake, and the meson always has some problems.

2021-08-02 11:40 UTC, autoantwort commented on ports/fontconfig/portfile.cmake
> +vcpkg_configure_meson(SOURCE_PATH ${SOURCE_PATH})
But fontconfig has no cmake support?

2021-08-03 01:22 UTC, JackBoosY commented
> 2.13.94 is still only a release candidate for 2.14 and not an official release

Yes, for the tool ports, I suggest to use the official release version.

2021-08-03 16:58 UTC, ras0219 commented
2.13.1: Aug 30 2018
2.13.91: Jun 10 2019
2.13.92: Aug 9 2019
2.13.93: Nov 27 2020
2.13.94: Jun 28 2021

There hasn't been a stable release in almost 3 years but code is still being written that fixes real bugs. There is some point that we must move to consider the RC's stable enough, but I'd love to hear evidence from either side.

https://github.com/microsoft/vcpkg/issues/18172 is certainly evidence in support of moving to the RCs.

2021-08-03 17:20 UTC, dg0yt commented
> There is some point at which we must consider the RCs stable enough, but I'd love to hear evidence from either side.

Some evidence from Repology:

[![Packaging status](https://repology.org/badge/vertical-allrepos/fontconfig.svg)](https://repology.org/project/fontconfig/versions)

2021-08-05 01:03 UTC, autoantwort commented
@Neumann-A It currently fails to cross build from arm64-osx to x64-osx with some strange liker stuff, so it builds everything as x86_64 but then at the end want to link a arm64 binary. Maybe a bug in `vcpkg_install_meson`?
[package-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/6935205/package-x64-osx-dbg-out.log)
[meson-cross-x64-osx-debug.log](https://github.com/microsoft/vcpkg/files/6935207/meson-cross-x64-osx-debug.log)
[meson-cross-x64-osx-release.log](https://github.com/microsoft/vcpkg/files/6935208/meson-cross-x64-osx-release.log)
[meson-cross-x64-osx.log](https://github.com/microsoft/vcpkg/files/6935209/meson-cross-x64-osx.log)
[cmake-vars-x64-osx-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/6935211/cmake-vars-x64-osx-dbg.cmake.log)

2021-08-17 20:15 UTC, autoantwort commented
> @Neumann-A It currently fails to cross build from arm64-osx to x64-osx with some strange liker stuff, so it builds everything as x86_64 but then at the end want to link a arm64 binary. Maybe a bug in `vcpkg_install_meson`?

It seems that this only happens when you build the vcpkg tool as arm64 binary, when you build the tool as x64 binary via `arch -x86_64 ./bootstrap-vcpkg.sh` the build succeeds

2021-09-09 18:28 UTC, ras0219-msft commented
/azp run

2021-09-09 18:29 UTC, ras0219-msft approved these changes

2021-09-09 18:30 UTC, BillyONeal commented
Thanks @dg0yt for pointing to Repology, what's good enough for Fedora and MinGW should be good enough for us. :)

2021-09-10 02:34 UTC, JackBoosY approved these changes

2021-09-10 20:36 UTC, merged

2021-09-10 20:36 UTC, BillyONeal commented
Thanks for the update!