[vcpkg baseline][hunspell] Fix usage when building static
microsoft/vcpkg pull request #19323
Opened 2021-08-03 07:55 UTC by JackBoosY

In _include/hunspell/hunvisapi.h_:
```cpp
#ifndef HUNSPELL_VISIBILITY_H_
#define HUNSPELL_VISIBILITY_H_

#if defined(HUNSPELL_STATIC)
#  define LIBHUNSPELL_DLL_EXPORTED
#elif defined(_WIN32)
#  if defined(BUILDING_LIBHUNSPELL)
#    define LIBHUNSPELL_DLL_EXPORTED __declspec(dllexport)
#  else
#    define LIBHUNSPELL_DLL_EXPORTED __declspec(dllimport)
#  endif
#elif defined(BUILDING_LIBHUNSPELL) && 1
#  define LIBHUNSPELL_DLL_EXPORTED __attribute__((__visibility__("default")))
#else
#  define LIBHUNSPELL_DLL_EXPORTED
#endif

#endif
```
That caused the usage error in baseline.

2021-08-03 08:44 UTC, NancyLi1013 approved these changes

2021-08-04 07:08 UTC, NancyLi1013 requested changes

2021-08-04 07:08 UTC, NancyLi1013 commented on ports/hunspell/portfile.cmake
> +        "${CURRENT_PACKAGES_DIR}/include/hunspell/hunvisapi.h"
```suggestion
        "${CURRENT_PACKAGES_DIR}/include/hunvisapi.h"
```

2021-08-04 07:32 UTC, JackBoosY commented on versions/h-/hunspell.json
> +      "git-tree": "2f2264528232cb7b66605e84634f86bbde7f2be7",
```suggestion
      "git-tree": "2a0514dd8b3893b6d3a502fbf55156e9e971d6f7",
```

2021-08-04 07:35 UTC, NancyLi1013 approved these changes

2021-08-04 07:37 UTC, NancyLi1013 commented
Ping @dan-shaw, please help merge this PR, thanks.

2021-08-05 02:48 UTC, BillyONeal commented on ports/hunspell/portfile.cmake
> +    vcpkg_replace_string(
It seems like it should make this be 0 if we aren't static?

2021-08-05 03:03 UTC, JackBoosY commented on ports/hunspell/portfile.cmake
> +    vcpkg_replace_string(
We don't need it, on dynamic it doesn't define `HUNSPELL_STATIC` and `BUILDING_LIBHUNSPELL` so we can take `__declspec(dllimport)`.

2021-08-05 03:05 UTC, merged

2021-08-05 03:05 UTC, BillyONeal commented
Thanks for the fix!

2021-08-05 04:31 UTC, dg0yt commented on ports/hunspell/portfile.cmake
> +    if (VCPKG_TARGET_IS_WINDOWS)
This needs a `AND NOT VCPKG_TARGET_IS_MINGW`, to match the earlier choice of build system. I just verified that mingw installs to `include/hunspell/hunvisapi.h`.