[soundtouch] enable static build
microsoft/vcpkg pull request #19377
Opened 2021-08-05 09:45 UTC by daschuer

**Describe the pull request**

- #### What does your PR fix?  
 Static build of soundtouch

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all,!uwp, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-08-06 02:04 UTC, NancyLi1013 requested changes

2021-08-06 02:04 UTC, NancyLi1013 commented on ports/soundtouch/CONTROL
> +Version: 2.0.0-7
```suggestion
Version: 2.0.0
Port-Version: 7
```

2021-08-06 02:04 UTC, NancyLi1013 commented on ports/soundtouch/portfile.cmake
>  endif()
```suggestion
vcpkg_fail_port_install(ON_TARGET "uwp")
```

2021-08-06 02:04 UTC, NancyLi1013 commented on ports/soundtouch/portfile.cmake
>  file(INSTALL ${SOURCE_PATH}/source/SoundTouchDLL/SoundTouchDLL.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```suggestion
file(INSTALL "${SOURCE_PATH}/source/SoundTouchDLL/SoundTouchDLL.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
```

2021-08-06 02:04 UTC, NancyLi1013 commented on ports/soundtouch/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/COPYING.TXT DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/COPYING.TXT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-06 04:41 UTC, daschuer commented on ports/soundtouch/CONTROL
> +Version: 2.0.0-7
Is the version still concidered as newer than?

2021-08-07 22:35 UTC, daschuer commented
Done

2021-08-09 03:14 UTC, NancyLi1013 commented
/azp run

2021-08-09 07:25 UTC, NancyLi1013 requested changes

2021-08-09 07:25 UTC, NancyLi1013 commented on ports/soundtouch/vcpkg.json
> +  "version-string": "2.0.0",
```suggestion
  "version-semver": "2.0.0",
```
This might be served by [version-semver](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-semver).

2021-08-09 07:30 UTC, NancyLi1013 commented on ports/soundtouch/CONTROL
> +Version: 2.0.0-7
In CONTROL file, we use `Version ` and `Port-Version` to express the version for the library. Please refer to the details 
 [here ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md).

2021-08-09 16:40 UTC, daschuer commented
Done

2021-09-29 02:46 UTC, NancyLi1013 commented
Needs to solve the conflicts here. @daschuer

2021-09-29 14:19 UTC, Be-ing commented
This PR is obsolete. #20017 implemented support for static builds.

2021-09-29 21:11 UTC, daschuer commented
The only missing bit was the ci.baseline.txt  change. I have rebased this PR accordingly.

2021-09-29 21:21 UTC, BillyONeal commented
This PR is also (accidentally) included in https://github.com/microsoft/vcpkg/pull/20435

2021-09-30 01:04 UTC, BillyONeal commented
Thanks for your contribution! Unfortunately it looks like all the edits here are already applied in master :)

2021-09-30 01:04 UTC, closed without merging