[trantor] Update to 1.5.1
microsoft/vcpkg pull request #19443
Opened 2021-08-08 08:32 UTC by an-tao

2021-08-09 06:29 UTC, JonLiu1993 requested changes

2021-08-09 06:29 UTC, JonLiu1993 commented on ports/trantor/vcpkg.json
> +  "port-version": 1,
```suggestion
```

2021-08-09 06:29 UTC, JonLiu1993 commented on ports/trantor/vcpkg.json
> +  "features": {}
```suggestion
  ]
```

2021-08-09 06:44 UTC, JonLiu1993 requested changes
Replace vcpkg_configure_cmake by vcpkg_cmake_configure,vcpkg_install_cmake by vcpkg_cmake_install,vcpkg_fixup_cmake_targets by vcpkg_cmake_config_fixup

2021-08-09 06:44 UTC, JonLiu1993 commented on ports/trantor/vcpkg.json
> +  "dependencies": [
let it depend on vcpkg-cmake port and vcpkg-cmake-config
vcpkg_cmake_configure and vcpkg_cmake_install provided by vcpkg-cmake port.
vcpkg_cmake_config_fixup provide by vcpkg-cmake-config.
eg:  https://github.com/microsoft/vcpkg/blob/master/ports/recast/vcpkg.json

2021-08-09 06:47 UTC, JonLiu1993 requested changes

2021-08-09 06:47 UTC, JonLiu1993 commented on ports/trantor/vcpkg.json
> +  "features": {}
```suggestion
    "openssl",
    "c-ares",
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ]
```

2021-08-10 08:15 UTC, JonLiu1993 commented
@an-tao ,Could you please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=57527&view=artifacts&pathAsName=false&type=publishedArtifacts

2021-08-11 00:28 UTC, an-tao commented
@JonLiu1993 Thanks so much for your help, but I don't know why it runs the `ninja -v` command. here is the error:

```shell
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
```

2021-08-11 01:38 UTC, JonLiu1993 commented
@an-tao ,You did not find the real error, this is the core error:
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6965313/config-x64-windows-out.log)

2021-08-16 08:53 UTC, JonLiu1993 commented
@an-tao ,Could you please take a look?

2021-08-16 09:25 UTC, an-tao commented
> @an-tao ,Could you please take a look?

@JonLiu1993 Sorry for the late reply, I have no idea about the error, It seems a permission error, do you have any suggestions?

2021-08-16 09:50 UTC, JonLiu1993 commented
> > @an-tao ,Could you please take a look?
> 
> @JonLiu1993 Sorry for the late reply, I have no idea about the error, It seems a permission error, do you have any suggestions?

I will try to reproduce locally, if it can be reproduced, I will solve it

2021-08-16 13:44 UTC, an-tao commented
> > > @an-tao ,Could you please take a look?
> > 
> > 
> > @JonLiu1993 Sorry for the late reply, I have no idea about the error, It seems a permission error, do you have any suggestions?
> 
> I will try to reproduce locally, if it can be reproduced, I will solve it

Thank you so much.

2021-08-18 02:40 UTC, JonLiu1993 commented
The 'paraview' breaks due CI basline error,just wait CI error fixed.

2021-08-23 09:54 UTC, JonLiu1993 commented
/azp run

2021-08-23 09:55 UTC, JonLiu1993 approved these changes

2021-08-24 07:39 UTC, JonLiu1993 approved these changes

2021-08-30 17:42 UTC, BillyONeal approved these changes

2021-08-31 02:27 UTC, merged

2021-08-31 02:27 UTC, BillyONeal commented
Thanks for your contribution!