Libb64
microsoft/vcpkg pull request #19447
Opened 2021-08-08 12:17 UTC by 9cvele3

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19445

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 It should be possible to build for every triplet, the library is lightweight. 
 However, Windows is focus here. For Linux, you can find regular libb64 packages in standard Linux repositories, so this PR should bring libb64 for Windows. I'm not quite sure how to handle other triplets (Linux ones) here (should I disable them, and how?)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  It follows the guide in everything except the `check names against other repositories`, read the note above about that.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-08-08 13:36 UTC, cenit commented
do not add cmakelists.txt as a patch but put it in the port folder and then copy it to the source tree

2021-08-08 15:15 UTC, cenit commented
good. windows-fix.patch still contains cmakelists.txt anyway

2021-08-08 15:16 UTC, cenit commented on ports/libb64/CMakeLists.txt
> +add_library(b64 STATIC ${SOURCE_FILES} ${HEADER_FILES})
why static? please remove it and let the triplet decide if shared or static

2021-08-08 15:17 UTC, cenit commented on ports/libb64/CMakeLists.txt
> +
would you mind adding also cmake targets to export, so that the downstream usage is simplified?
use the unofficial:: prefix if you do not submit the fix upstream and you think it won’t be accepted

2021-08-08 15:19 UTC, cenit commented on ports/libb64/CONTROL
> +Source: libb64
new ports require the vcpkg.json manifest instead of the legacy CONTROL file,

2021-08-08 19:19 UTC, 9cvele3 commented on ports/libb64/CMakeLists.txt
> +add_library(b64 STATIC ${SOURCE_FILES} ${HEADER_FILES})
done

2021-08-08 19:19 UTC, 9cvele3 commented on ports/libb64/CONTROL
> +Source: libb64
done

2021-08-08 19:20 UTC, 9cvele3 commented on ports/libb64/CMakeLists.txt
> +
done

2021-08-10 08:02 UTC, JonLiu1993 requested changes

2021-08-10 08:02 UTC, JonLiu1993 commented on ports/b64/portfile.cmake
> +file(COPY ports/b64/CMakeLists.txt DESTINATION ${SOURCE_PATH}/)
```suggestion
file(COPY "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DESTINATION "${SOURCE_PATH}")
```

2021-08-11 02:22 UTC, JonLiu1993 approved these changes

2021-08-12 02:15 UTC, BillyONeal commented on ports/b64/CMakeLists.txt
> +set(LIBB64_EXPORTS 1)
LIBB64_EXPORTS seems unused?

2021-08-12 02:16 UTC, BillyONeal commented
Have you asked upstream if they would be willing to accept the Windows patch?

2021-08-12 09:31 UTC, 9cvele3 commented on ports/b64/CMakeLists.txt
> +set(LIBB64_EXPORTS 1)
It is used in window-fix.patch, line 18.
I use it to handle dllimport dllexport stuff for dlls on Windows. 
If you have some suggestion how to handle that in an different way, it's welcome.

2021-08-12 09:38 UTC, BillyONeal commented on ports/b64/CMakeLists.txt
> +set(LIBB64_EXPORTS 1)
I see that constant used in the patch but I'm missing how this set is attached to that. Did I miss a configure_file or something?

2021-08-12 09:40 UTC, 9cvele3 commented
> Have you asked upstream if they would be willing to accept the Windows patch?

The upstream seemed like not being actively maintained (no merged PR for almost a year), so I didn't ask. 
But I see your point, I will try to submit the patch there,

2021-08-12 09:47 UTC, 9cvele3 commented on ports/b64/CMakeLists.txt
> +set(LIBB64_EXPORTS 1)
I probably need `add_definitions` here, not `set` :sweat_smile:

2021-08-12 10:02 UTC, 9cvele3 commented on ports/b64/CMakeLists.txt
> +set(LIBB64_EXPORTS 1)
Or even better, `add_compile_definitions`

2021-08-12 22:51 UTC, BillyONeal commented
> > Have you asked upstream if they would be willing to accept the Windows patch?
> 
> The upstream seemed like not being actively maintained (no merged PR for almost a year), so I didn't ask.
> But I see your point, I will try to submit the patch there,

Makes sense. This is certainly in the ballpack of what we would accept as a patch; we usually at least look for an attempt to submit upstream to remove all doubt though. If build gets fixed you have my vote.

2021-08-13 10:26 UTC, 9cvele3 commented
> > > Have you asked upstream if they would be willing to accept the Windows patch?
> > 
> > 
> > The upstream seemed like not being actively maintained (no merged PR for almost a year), so I didn't ask.
> > But I see your point, I will try to submit the patch there,
> 
> Makes sense. This is certainly in the ballpack of what we would accept as a patch; we usually at least look for an attempt to submit upstream to remove all doubt though. If build gets fixed you have my vote.

Build fixed. 
Just in case created a PR for the upstream: https://github.com/libb64/libb64/pull/8 
If / When it gets approved, patch and cmakefile can be removed from vcpkg. But, as I said, I don't expect quick feedback here.

2021-08-13 18:04 UTC, BillyONeal commented on ports/b64/CMakeLists.txt
> +target_compile_definitions(b64 PUBLIC LIBB64_EXPORTS=1)
This seems like it must be wrong, since it would add dllexports to *consumers* of the lib. Perhaps that should be PRIVATE, and only put here when BUILD_SHARED_LIBS is on?

2021-08-13 18:05 UTC, BillyONeal requested changes

2021-08-13 18:05 UTC, BillyONeal commented on ports/b64/windows-fix.patch
> ++#ifdef _WIN32
It seems like this will do the wrong thing for static triplets.

2021-08-14 16:44 UTC, 9cvele3 commented
It seems that build failure is not related to this PR. 

Port `colmap` is failing with x64-windows-static triplet: https://dev.azure.com/vcpkg/public/_build/results?buildId=57780&view=logs&j=821e2c31-c252-5a5c-eeb9-89df78f2f610&t=34ac2787-4652-59a0-fda0-8b82a81de66d&l=2861 

It happens with other PRs also: https://github.com/microsoft/vcpkg/pull/19572

2021-08-16 19:50 UTC, BillyONeal approved these changes

2021-08-17 01:54 UTC, JonLiu1993 commented
@9cvele3 ,Could you please take a look:
````
ninja: error: 'D:/installed/x64-windows-static/debug/lib/openblas.lib', needed by 'src/exe/colmap.exe', missing and no known rule to make it
````

2021-08-17 03:19 UTC, cenit commented
> @9cvele3 ,Could you please take a look:
> 
> ```
> ninja: error: 'D:/installed/x64-windows-static/debug/lib/openblas.lib', needed by 'src/exe/colmap.exe', missing and no known rule to make it
> ```

totally unrelated to this PR, do not worry about it @9cvele3

2021-08-18 02:44 UTC, JonLiu1993 commented
The 'colmap' breaks due CI basline error,just wait CI error fixed.

2021-08-23 09:57 UTC, JonLiu1993 commented
/azp run

2021-08-26 03:33 UTC, merged