[kf5windowsystem] fix cmake.in for static usage; extra fixes
microsoft/vcpkg pull request #19440
Opened 2021-08-07 20:33 UTC by wrobelda

- #### What does your PR fix?  
  Apply https://invent.kde.org/frameworks/kwindowsystem/-/merge_requests/27 patch
    - fix MAYBE_UNUSED_VARIABLES usage
    - use semVer
    - update deprecated functions
    - wrap paths in quotes
    - don't overzealously remove folders

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

2021-08-09 02:25 UTC, JackBoosY requested changes

2021-08-09 02:25 UTC, JackBoosY commented on ports/kf5windowsystem/27.patch
> ++    if(@WIN32@)
```suggestion
+    if(WIN32)
```

2021-08-09 18:39 UTC, wrobelda commented on ports/kf5windowsystem/27.patch
> ++    if(@WIN32@)
Why this suggestion? This was already merged upstream and confirmed working.

2021-08-09 18:54 UTC, Neumann-A commented on ports/kf5windowsystem/27.patch
> ++    find_dependency(Qt5Widgets @REQUIRED_QT_VERSION@)
Tell upstream this is not how one should find Qt. 
The correct syntax is to use
 `find_(packacke|dependency)(Qt[MajorVersion] <Version> COMPONENTS Widgets)`
Never should you directly lookup cmake configs of components.

2021-08-09 22:10 UTC, wrobelda commented on ports/kf5windowsystem/27.patch
> ++    find_dependency(Qt5Widgets @REQUIRED_QT_VERSION@)
Looks like the opinions vary. Mind providing some reference?
<img width="890" alt="Screen Shot 2021-08-09 at 10 09 50 PM" src="https://user-images.githubusercontent.com/1702435/128780818-3edd3272-25ca-40ac-81bf-14358e29b4ae.png">

2021-08-10 04:44 UTC, dg0yt commented on ports/kf5windowsystem/27.patch
> ++    find_dependency(Qt5Widgets @REQUIRED_QT_VERSION@)
Repeated calls to `find_package(<PKG> ...  COMPONENT ...)` don't or didn't work as expected is some cases. For example, `<PKG>_FOUND` is set to true after the first call, so further calls are ignored. This is an issue when components (sub-directories) in a project do their own dependency lookup.

2021-08-10 05:14 UTC, dg0yt commented on ports/kf5windowsystem/27.patch
> ++    find_dependency(Qt5Widgets @REQUIRED_QT_VERSION@)
And for completeness, until Qt 5.11, `find_package(Qt5Widgets)` etc. was the recommended form:
https://doc.qt.io/archives/qt-5.11/cmake-manual.html

2021-08-11 08:15 UTC, wrobelda commented on ports/kf5windowsystem/27.patch
> ++    if(@WIN32@)
@JackBoosY

2021-08-11 09:56 UTC, JackBoosY commented on ports/kf5windowsystem/27.patch
> ++    find_dependency(Qt5Widgets @REQUIRED_QT_VERSION@)
Was this resolved?

2021-08-11 13:43 UTC, wrobelda commented on ports/kf5windowsystem/27.patch
> ++    find_dependency(Qt5Widgets @REQUIRED_QT_VERSION@)
@JackBoosY this is a discussion around the upstream code quality, unrelated to this port.

2021-08-12 02:31 UTC, JackBoosY approved these changes

2021-08-19 22:49 UTC, merged