[nng] Update to v1.5.1
microsoft/vcpkg pull request #19478
Opened 2021-08-10 10:28 UTC by myd7349

**Describe the pull request**

- #### What does your PR fix?  
  Update to v1.5.1.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All. Yes.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-08-23 02:25 UTC, JonLiu1993 requested changes

2021-08-23 02:25 UTC, JonLiu1993 commented on ports/nng/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-08-23 02:27 UTC, JonLiu1993 commented
@myd7349, thanks for your PR, have you tested these features locally?

2021-09-08 13:17 UTC, myd7349 commented
> 
> 
> @myd7349, thanks for your PR, have you tested these features locally?

Hi! @JonLiu1993 Thanks for your help and sorry for the long delay.
I have tested all features with:
- x86-windows
- x86-windows-static
- x64-windows
- x64-windows-static

2021-09-09 03:06 UTC, JonLiu1993 approved these changes

2021-09-10 04:12 UTC, merged

2021-09-10 04:12 UTC, BillyONeal commented
Thanks for the help!