[freexl] Fix mingw, cleanup
microsoft/vcpkg pull request #19504
Opened 2021-08-11 19:32 UTC by dg0yt

- #### What does your PR fix?  
  This PR fixes the mingw, modernizes the portfile, and adds the libiconv dependency to the pc file.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

2021-08-12 05:16 UTC, dg0yt commented
CI is rebuilding a lot of packages now, just after update of `master`. Let's hope we don't get too many unrelated regressions.

2021-08-12 23:16 UTC, dg0yt commented
rtaudio:x64-osx CI failure: unrelated.

2021-08-13 08:53 UTC, JackBoosY requested changes

2021-08-13 08:53 UTC, JackBoosY commented on ports/freexl/portfile.cmake
> +    vcpkg_fixup_pkgconfig()
Does this not need `SYSTEM_LIBRARIES m` now?

2021-08-13 10:20 UTC, dg0yt commented on ports/freexl/portfile.cmake
> +    vcpkg_fixup_pkgconfig()
No port does: 
https://github.com/microsoft/vcpkg/blob/7bdf2f8e853a476f96f3d1ba3be409b65822a29d/scripts/cmake/vcpkg_fixup_pkgconfig.cmake#L34-L35

2021-08-16 02:34 UTC, JackBoosY requested changes

2021-08-16 02:34 UTC, JackBoosY commented on ports/freexl/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/freexl" RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-16 15:38 UTC, dg0yt commented on ports/freexl/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/freexl" RENAME copyright)
Done.

2021-08-17 01:35 UTC, JackBoosY approved these changes

2021-09-01 03:39 UTC, merged

2021-09-01 03:39 UTC, ras0219-msft commented
Yep, this LGTM. Thanks for the awesome cleanup!