[vcpkg_configure_make] Fix passing of space in OPTIONS for Windows
microsoft/vcpkg pull request #19540
Opened 2021-08-12 23:31 UTC by dg0yt

- #### What does your PR fix?  
  This PR fixes passing of space in `OPTIONS` to `vcpkg_configure_make` when `VCPKG_TARGET_IS_WINDOWS`. Options are passed in a single string here.
  A typical use is passing something like `LIBS=-lpthread -lm -lz`. Without this fix, `configure` would see individual parameters like `LIBS=-lpthread`, then `-lm`, then `-lz`.
  (The problem was found in preparing other changes.)
  It also removes an unused `EXTRA_QUOTES` variable.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all (but changing only for VCPKG_TARGET_IS_WINDOWS), no

  This change was tested locally with native and cross mingw.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  not needed

2021-08-13 02:34 UTC, JackBoosY commented
cc @Neumann-A for review this PR.

2021-08-13 02:36 UTC, JackBoosY requested changes

2021-08-13 02:36 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_make.cmake
> -            set(command "${base_cmd}" -c "${CONFIGURE_ENV} $@" -- "./${RELATIVE_BUILD_PATH}/configure" ${_csc_BUILD_TRIPLET} ${_csc_OPTIONS} ${_csc_OPTIONS_${_buildtype}})
Is this suitable for mingW?

2021-08-13 04:17 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> -            set(command "${base_cmd}" -c "${CONFIGURE_ENV} $@" -- "./${RELATIVE_BUILD_PATH}/configure" ${_csc_BUILD_TRIPLET} ${_csc_OPTIONS} ${_csc_OPTIONS_${_buildtype}})
Yes. Mingw is included in `VCPKG_TARGET_IS_WINDOWS`. This part of the change just restores what was there before #18554.

I wonder if this is shouldn't really take the form of `CMAKE_HOST_WIN32 OR VCPKG_TARGET_IS_WINDOWS`, to cover crosscompiling from Windows to non-Windows (Android, emscripten). But I don't have a test case, so I decided to take what was there before.

2021-08-13 05:27 UTC, dg0yt commented
It is still a draft PR. I expected problems, but was too tired to figure out which ports to test. From previous CMake experience I know that dealing with double quotes, single quotes and escaping, cross-platform, can be quite tricky. An alternative could be writing and calling a bash script, and call this script uniformly. One could even look at the script in case of trouble.

2021-08-13 07:01 UTC, Neumann-A commented
there is another way to pass env variables. E.g. `CONFIGURE_ENVIRONMENT_VARIABLES` and `CONFIG_DEPENDENT_ENVIRONMENT`

2021-08-13 07:02 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if(VCPKG_TARGET_IS_WINDOWS)
This is wrong.

2021-08-13 07:13 UTC, dg0yt commented
Thanks for the incoming review comments, despite the draft state. However it means you may raise issues which I planned to study in the course of the CI run, and adress before review. This PR is about lack of portability, and I can't cover this locally, quickly.

libtasn1 turned out to be the only port which already deals with `LIBS` (`git grep 'LIBS=."' ports/*/portfile.cmake`). 
It uses this (but only for windows and mingw): 
https://github.com/microsoft/vcpkg/blob/c801072693edcd0704d187131d9078fcd089dbf2/ports/libtasn1/portfile.cmake#L21-L25
This fails now. (libtasn1 also has another use case: `CFLAGS=...`.)

The problem with the above code is that it works for Windows because here arguments are substituted into a single string which is evaluated as a command line by bash. But for non-Windows targets, `vcpkg_configure_make` will pass the arguments literally to `configure`, i.e. with literal `"` and literal `$`. This means `$LIBS` wouldn't be expanded at all.

For more consistency and portability, we need to get completely rid of the branching around `set(command "${base_cmd}" ...`. 

In the end, the most portable solution might be to generate a parameterless bash script which handles setting up the environment and calling `configure`. This avoids the cross-platform and cmake quirks of argument passing and quoting in connection with variables, and it allows for inspection.

2021-08-13 07:20 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if(VCPKG_TARGET_IS_WINDOWS)
See my comment in https://github.com/microsoft/vcpkg/pull/19540#discussion_r688232122. Key points:
- `VCPKG_TARGET_IS_WINDOWS` is the code that was there before #18554.
- `CMAKE_HOST_WIN32` alone is not enough: mingw cross-builds would take the other branch, lacking `CONFIGURE_ENV`.

Fun fact: `CMAKE_HOST_WIN32` is identical to `WIN32` in script mode. And then there is also `VCPKG_HOST_IS_WINDOWS`.

2021-08-13 07:26 UTC, dg0yt commented
> there is another way to pass env variables. E.g. `CONFIGURE_ENVIRONMENT_VARIABLES` and `CONFIG_DEPENDENT_ENVIRONMENT`

Thanks for this pointer. I will try that for libtasn1 in a separate PR. It is broken for mingw now, so it needs an update anyway.

2021-08-13 07:26 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if(VCPKG_TARGET_IS_WINDOWS)
> CMAKE_HOST_WIN32 alone is not enough: mingw cross-builds would take the other branch,

is this not detected as MSYS?

2021-08-13 07:32 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if(VCPKG_TARGET_IS_WINDOWS)
> > CMAKE_HOST_WIN32 alone is not enough: mingw cross-builds would take the other branch,
> 
> is this not detected as MSYS?

What do you mean by that sentence? Mingw on Linux is neither `CMAKE_HOST_WIN32` nor `MSYS`, and the latter plays no role in vcpkg, apart from providing binaries. `MSYS` denotes a POSIX-style runtime for Windows.

2021-08-13 07:40 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if(VCPKG_TARGET_IS_WINDOWS)
>  Mingw on Linux

i was assuming mingw from msys

2021-08-13 07:56 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +        if(VCPKG_TARGET_IS_WINDOWS)
> i was assuming mingw from msys

You answer on a "mingw cross-builds" comment which was meaning Linux (or similar) hosts. Anyway, from CMake doc:

### `CMAKE_HOST_WIN32` 
`True` if the host system is running Windows, including Windows 64-bit and MSYS.

Set to false on Cygwin.

### `MSYS`

`True` when using the MSYS Makefiles generator.

---

We are in script mode, so there is no generator.

2021-08-13 19:42 UTC, dg0yt commented
> > there is another way to pass env variables. E.g. `CONFIGURE_ENVIRONMENT_VARIABLES` and `CONFIG_DEPENDENT_ENVIRONMENT`
> 
> Thanks for this pointer. I will try that for libtasn1 in a separate PR. It is broken for mingw now, so it needs an update anyway.

Unfortunately this won't work for variables which are already handled by `vcpkg_configure_make`. `CONFIGURE_ENVIRONMENT_VARIABLES` and `CONFIG_DEPENDENT_ENVIRONMENT` provide no means to mix detected cmake configuration with values provided by the portfile.

So in libtasn1, `LIBS` and `CFLAGS` are passed as parameters to `configure`, not as environment variables. AFAIK this takes precedence over environment variables of the same name.
 
For the Windows code path, the parameters are part of a command run in bash, with parameters expanded by bash at runtime. That's how libtasn1 manages to merge the `LIBS` environment variable from `vcpkg_configure_make` with the parameter it wants to add. And that's where the difficulties with spaces and quotes come from.

For the non-Windows code path, the parameters are passed directly to configure, without expansion in bash. This eliminates the need for quoting or escaping. But here, there is no way to combine with the values from `vcpkg_configure_make` with values supplied by the portfile. 

The question remains: How to combine detected values with additional values, in a portable and clean way?

2021-08-13 19:54 UTC, Neumann-A commented
> The question remains: How to combine detected values with additional values, in a portable and clean way?

Add the additional values to the detected values. Or to be more precise make the additional values the detected values + the normally detected values.

2021-08-14 04:28 UTC, dg0yt commented
> Add the additional values to the detected values. Or to be more precise make the additional values the detected values + the normally detected values.

You mean to make `detected values = additional values + normally detected values`?

I considered this, too. But I couldn't see a clean and consistent way to do this. All examples I know use the `OPTIONS` of `vcpkg_configure_make`.
- Setting `ENV{CFLAGS}` might help for such flags, because CMake should pick it up in the detection step (prepending to `CMAKE_C_FLAGS_INIT`).
- For `LIBS`, I don't see that CMake is looking at an environment variable.

This doesn't look clean and consistent to me. Did I miss another approach or working example?

2021-08-14 04:30 UTC, dg0yt commented
For the record, this is the current situation:

`OPTIONS`               | Works on Windows | Works on non-Windows | Example
----------------------------|---------------------------|-------------------------------|---------------
LIBS=$LIBS -la -lb   | no (space)              | no (dollar)                     |
LIBS=-la -lb               | no (space)             | yes                               | libspatite (overwrites detected LIBS)
LIBS="$LIBS -la -lb" | yes                         | no (quotes, dollar)        | libtasn1

2021-09-07 10:55 UTC, dg0yt commented
Ping for feedback. Such long delays make it necessary to consolidate with other PRs. (Looking at #19753.)

2021-09-08 02:38 UTC, JackBoosY commented
That's what I need.
For libraries that are dependent and not declared in configure / configure.ac, we still do not have an appropriate and standard way to add them to the link queue.

2021-09-08 03:13 UTC, JackBoosY commented
How about to use `CONFIGURE_ENVIRONMENT_VARIABLES` and `CONFIG_DEPENDENT_ENVIRONMENT`, I'd like to provide some vcpkg_configure_cmake options instead of adding the extra libs to `LIBS`.

2021-09-08 05:22 UTC, dg0yt commented
This PR is targeting the interface of `vcpkg_configure_make`, not `LIBS` in particular. (However `LIBS` is the most frequent use case.) So I would prefer to leave out discussions about how to better deal with `LIBS`.

2021-09-08 05:57 UTC, JackBoosY commented
Can you please trigger more port tests by adding port-version?

2021-09-08 06:07 UTC, dg0yt commented
> Can you please trigger more port tests by adding port-version?

Why? Ports that use `vcpkg_configure_make` are triggered by the changes to `vcpkg_configure_make.cmake` anyway. 
I merged `master` now. If this doesn't trigger enough rebuilds, let's add another no-op change to the script instead.

2021-09-08 16:05 UTC, dg0yt commented
So after hours of building, there is only the usual unrelated pangolin:x64-linux error.
Do you need more port tests?

2021-09-09 02:44 UTC, JackBoosY commented
@dg0yt  Yes please.

2021-09-09 06:08 UTC, dg0yt commented
> @dg0yt Yes please.

So let's fix the missing `EXISTS` as a drive-by.

2021-09-09 08:23 UTC, dg0yt commented
> So let's fix the missing `EXISTS` as a drive-by.

This opens a can of worms. Reverting to a no-op change.

2021-09-09 08:59 UTC, JackBoosY commented
I will rerun the failed tests after other tests finished.

2021-09-09 18:40 UTC, dg0yt commented
Linux unchanged: unrelated pangolin error.
Windows unchanged AFAICT: x64-windows and x86-windows agents died during the build (unrelated).

2021-09-13 06:18 UTC, JackBoosY approved these changes

2021-09-14 03:13 UTC, BillyONeal commented
> Windows unchanged AFAICT: x64-windows and x86-windows agents died during the build (unrelated).

I just changed the VM SKU to hopefully make that happen less often ( in #20064 )

2021-09-14 03:15 UTC, BillyONeal approved these changes
Thanks for the awesome commit messages!

2021-09-14 05:54 UTC, JackBoosY commented
All these changes will be merged into https://github.com/microsoft/vcpkg/pull/19753.

2021-09-14 06:49 UTC, dg0yt commented
> All these changes will be merged into #19753.

Hm, this will delay the merge, blocking other work. And with the successful CI run, the binary artifacts are in the cache *now*.

2021-09-14 07:44 UTC, JackBoosY commented
@dg0yt  This PR can be merged first, then I will synchronize the changes to my PR.

2021-09-14 18:42 UTC, strega-nil-ms reviewed
These are the things I see right now.

2021-09-14 18:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
Is there a reason that these are set to `\${prefix}` as opposed to just `${prefix}` (i.e., this results in the command line: `--bindir=\${prefix}/tools/<PORT>/bin`, as opposed to `--bindir=${prefix}/tools/<PORT>/bin`; this is a change from the previous behavior, which was the latter).

2021-09-14 18:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(JOIN ${var} " " ${var})
```suggestion
        vcpkg_list(SET tmp)
        foreach(element IN LISTS "${var}")
            string(REPLACE [["]] [[\"]] element "${element}")
            vcpkg_list(APPEND tmp "\"${element}\"")
        endforeach()
        vcpkg_list(JOIN tmp " " "${var}")
```

2021-09-14 18:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(JOIN ${var} " " ${var})
Also, you'll note the change from `\\"` to `\"` - I think `\\"` is just incorrect here.

2021-09-14 21:24 UTC, BillyONeal commented
Marked "requires:author-response" as a result of Nicole's feedback.

2021-09-15 06:16 UTC, dg0yt reviewed
I would prefer to reject the suggestions, and I hope my answers are satisifying.
Please review quickly again. I now repeated part of the testing work I did four weeks ago, and after such a long delay, it really takes more time.

2021-09-15 06:16 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(JOIN ${var} " " ${var})
The suggested change is longer, less readable IMHO and not standard CMake. But I couldn't find a single case where it would make a difference. I would prefer to leave as is.

> Also, you'll note the change from `\\"` to `\"` - I think `\\"` is just incorrect here.

In my original implementation, a single backslash gives the following error:
~~~
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:736 (list):
  list sub-command TRANSFORM, action REPLACE: Unknown escape "\"" in
  replace-expression.
~~~
Note that `list(TRANSFORM ... REPLACE ...)` is based on regex, but `string(REPLACE ...)` isn't.

2021-09-24 21:02 UTC, strega-nil-ms commented on ports/libtasn1/portfile.cmake
> +    list(APPEND EXTRA_OPTS "LIBS=-lgettimeofday -lgetopt $LIBS")
I don't want to have a raw `$` in a string here, even if it is parsed "correctly". `\$` is more clear, imo; or use `[[]]`.

2021-09-24 21:04 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(JOIN ${var} " " ${var})
We do not wish to use `list()` in vcpkg, since it breaks on internal semicolons. This is part of the scripts requirements work from #17691

2021-09-24 21:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
Can we not use `'` in the command line instead of `"` to fix it then?

2021-09-26 09:03 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
> Can we not use `'` in the command line instead of `"` to fix it then?

No. The difference is like this:
~~~sh
$ echo "'${prefix}'"
''
$ echo "\${prefix}"
${prefix}
~~~

We call `execute_process` with this cmake list (simplified):
~~~
${base_cmd}
-c
${CONFIGURE_ENV} ./${RELATIVE_BUILD_PATH}/configure ${_csc_OPTIONS_RELEASE}
~~~
The last item is what I called the "bash command line". `--bindir=\\\${prefix}/tools/${PORT}/bin` will end up in `_csc_OPTIONS_RELEASE`, enclosed in double quotes as a general strategy to deal with spaces in parameters. And within these double quotes, the single quote doesn't mean bash quoting.

That's the key trade-off: We need quotes in order to portably separate the individual arguments. We need *double* quotes instead of single quotes to allow expansion of environment variable `$LIB` at the time bash interpretes the command line, but we cannot use single quotes inside double quotes to protect `$prefix`.

2021-09-26 10:55 UTC, dg0yt commented on ports/libtasn1/portfile.cmake
> +    list(APPEND EXTRA_OPTS "LIBS=-lgettimeofday -lgetopt $LIBS")
Done.

2021-09-26 10:55 UTC, dg0yt commented on ports/libtasn1/portfile.cmake
> +    list(APPEND EXTRA_OPTS "CFLAGS=$CFLAGS -DASN1_STATIC")
Done.

2021-09-26 10:55 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +        list(JOIN ${var} " " ${var})
Done.

2021-09-27 06:00 UTC, JackBoosY commented
When building `python3:x64-osx`:
```
install: mkdir /Users/vagrant/Data/packages/python3_x64-osx/Users/vagrant/Data/installed/x64-osx/debug/lib: File exists
make: *** [altbininstall] Error 71
make: *** Waiting for unfinished jobs....
```

2021-09-27 06:58 UTC, dg0yt commented
No more results from `git grep '=""' | grep portfile` ...

2021-09-27 08:06 UTC, JackBoosY commented
Ping @strega-nil-ms for review again.

2021-09-27 16:45 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
ah, right... god that's terrible. I do not like the double-expansion going on here, but clearly we have people already depending on this behavior. Could you add a comment about this? Something like "These have an extra backslash to avoid double-expansion by bash"?

2021-09-28 04:33 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
Nobody likes the double quoting, but Windows is too relevant to ignore ;-)
I would prefer refering to "early" instead of "double". It is expanded only once.
~~~
    # ${prefix} has an extra backslash to prevent early expansion when calling `bash -c configure "..."`.
~~~

2021-09-28 20:55 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
fair enough

2021-09-29 16:13 UTC, BillyONeal approved these changes

2021-09-29 17:38 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
Could you add that comment at the top?

2021-09-30 09:38 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_make.cmake
> +                            "--bindir=\\\${prefix}/tools/${PORT}/bin"
@strega-nil-ms Done.

2021-09-30 23:40 UTC, BillyONeal commented
Since this rebuilds a lot I just merged with master; will merge once build comes back

2021-10-01 02:43 UTC, BillyONeal commented
/azp run

2021-10-01 02:43 UTC, BillyONeal commented
```
CMake Error at common/fw/CMakeLists.txt:61 (file):
  file DOWNLOAD HASH mismatch

    for file: [/mnt/vcpkg-ci/buildtrees/realsense2/x64-linux-rel/common/fw/L51X_FW_Image-1.5.8.1.bin]
      expected hash: [ab73e5bfc520c0aa0340cada4b3e317b8fd31a4d]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [56;"Failure when receiving data from the peer"]
```

2021-10-01 06:58 UTC, merged

2021-10-01 06:58 UTC, BillyONeal commented
Thanks for your help!

2021-10-01 07:03 UTC, dg0yt commented
Thanks for merging. Already needed for changes to the next port (libspatialite)...