[ngspice] Update to release 35
microsoft/vcpkg pull request #19542
Opened 2021-08-13 02:46 UTC by marekr

**Describe the pull request**

- #### What does your PR fix?  
Updates to latest r35 release

Also fixes the project's vcproj dumping files in C:\ root

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
Windows x64, x86 only

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes its committed.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-08-13 03:04 UTC, JonLiu1993 requested changes

2021-08-13 03:04 UTC, JonLiu1993 commented on ports/ngspice/portfile.cmake
> +		remove-64-in-codemodel-name.patch
```suggestion
        remove-post-build.patch
        remove-64-in-codemodel-name.patch

```

2021-08-13 03:08 UTC, marekr commented
Updated with the suggested change and x-add-version

2021-08-13 06:09 UTC, JonLiu1993 approved these changes

2021-08-13 06:23 UTC, JonLiu1993 commented
Feature codemodels tested successfully in the following triplet:
- x86-windows
- x64-windows

2021-08-31 01:32 UTC, ras0219-msft commented
LGTM, thanks for the update!

2021-08-31 01:33 UTC, merged