[openxr-loader] Update to 1.0.18
microsoft/vcpkg pull request #19574
Opened 2021-08-14 19:16 UTC by jherico

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19573 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
UWP and ARM are not supported.  This is unchanged from the previous version of the port. 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
I believe the portfile may be using a deprecated function but I'm attempting to make this a minimum touch PR.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes.

2021-08-16 09:44 UTC, JackBoosY requested changes

2021-08-16 09:44 UTC, JackBoosY commented on ports/openxr-loader/002-fix-hpp-gen.patch
> ++            "XR_MSFT_scene_understanding_serialization",
Is this the upstream changes?

2021-08-16 21:30 UTC, jherico commented on ports/openxr-loader/002-fix-hpp-gen.patch
> ++            "XR_MSFT_scene_understanding_serialization",
The OpenXR-hpp project generates C++ bindings, but the generation code isn't handling every case properly.  Excluding these extensions was required to get a version of the header that compiles.  This replaces the old patch method in the previous version where I patched the output headers directly.  That approach is significantly more difficult now because the C++ bindings have been broken up into many files.

2021-08-18 08:39 UTC, JackBoosY commented on ports/openxr-loader/002-fix-hpp-gen.patch
> ++            "XR_MSFT_scene_understanding_serialization",
Is this caused by upstream? If so, please report to the upstream first.

2021-08-18 23:08 UTC, jherico commented on ports/openxr-loader/002-fix-hpp-gen.patch
> ++            "XR_MSFT_scene_understanding_serialization",
I've already reported the corresponding issues here:  https://github.com/KhronosGroup/OpenXR-Hpp/issues/24 but they haven't gotten any traction.  I'm one of the two main contributors to the upstream repository and I haven't had time to try to resolve this bug yet, but I still need an updated version of the XR bindings from vcpkg.

2021-08-19 02:57 UTC, JackBoosY approved these changes

2021-08-26 17:54 UTC, merged