[comms,commsdsl,comms-ublox] update ports
microsoft/vcpkg pull request #19581
Opened 2021-08-15 14:16 UTC by mathisloge

**Describe the pull request**

- #### What does your PR fix?  

* updates comms to 3.4
* adds feature tools to comms. 
* update commsdsl to 3.6.4
* update comms-ublox to 0.20.2

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

2021-08-15 14:16 UTC, mathisloge commented
\ping https://github.com/commschamp/comms_champion/issues/13

2021-08-16 09:45 UTC, JackBoosY requested changes

2021-08-16 09:45 UTC, JackBoosY commented on ports/comms/portfile.cmake
> +endif()
Why do that?

2021-08-16 15:38 UTC, mathisloge commented on ports/comms/portfile.cmake
> +endif()
good catch. Forgot to remove that.

2021-08-17 00:47 UTC, JackBoosY requested changes

2021-08-17 00:47 UTC, JackBoosY commented on ports/comms/portfile.cmake
> +    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/LibComms")
Can you confirm which file was installed in those directories?

2021-08-17 00:47 UTC, JackBoosY commented on ports/comms/portfile.cmake
> +    file(COPY "${CURRENT_PACKAGES_DIR}/lib/CommsChampion/plugin" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/${PORT}/lib/CommsChampion/")
Maybe `RENAME` would be better.

2021-08-17 19:38 UTC, mathisloge commented on ports/comms/portfile.cmake
> +    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/LibComms")
with the fix now, all dirs are empty (except plugins which are installed now)

2021-08-17 19:38 UTC, mathisloge commented on ports/comms/portfile.cmake
> +    file(COPY "${CURRENT_PACKAGES_DIR}/lib/CommsChampion/plugin" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/${PORT}/lib/CommsChampion/")
Rename gives some strange errors that the target dir does not exists

2021-08-18 08:33 UTC, JackBoosY commented
Depends on https://github.com/microsoft/vcpkg/pull/19629.

2021-08-23 02:23 UTC, JackBoosY requested changes

2021-08-23 02:23 UTC, JackBoosY commented on ports/comms/portfile.cmake
> +    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
Why did you remove that? Is this port a header only library?

2021-08-23 04:46 UTC, mathisloge commented on ports/comms/portfile.cmake
> +    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
Yes

2021-08-23 06:07 UTC, JackBoosY approved these changes

2021-08-23 10:46 UTC, JackBoosY commented
When building `comms[core,tools]:x64-windows-static`:
```
-- Installing: G:/19581/vcpkg/packages/comms_x64-windows-static/share/comms/copyright
-- Performing post-build validation
DLLs should not be present in a static build, but the following DLLs were found:

    G:/19581/vcpkg/packages/comms_x64-windows-static/bin/comms_champion.dll
    G:/19581/vcpkg/packages/comms_x64-windows-static/debug/bin/comms_champion.dll

There should be no bin\ directory in a static build, but G:\19581\vcpkg\packages\comms_x64-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but G:\19581\vcpkg\packages\comms_x64-windows-static\debug/bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

Found 2 error(s). Please correct the portfile:
    G:\19581\vcpkg\ports\comms\portfile.cmake
-- Performing post-build validation done
Error: Building package comms:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
```

2021-08-23 14:59 UTC, mathisloge commented
@JackBoosY Is there a way to add `supports` fields to a feature property? 
The tool itself builds a shared library (hardcoded) which is needed for the build plugins. 
So the feature tools can only be build if the triplet is dynamic, but the port without the feature tools supports all triplets, since it is header only

2021-08-24 07:24 UTC, JackBoosY requested changes

2021-08-24 07:24 UTC, JackBoosY commented on ports/comms/portfile.cmake
>      OPTIONS
```suggestion
    OPTIONS ${FEATURE_OPTIONS}
```

2021-08-24 07:24 UTC, JackBoosY commented on ports/comms/portfile.cmake
> +endif()
I don't think we can deprive users of the power to build static, even with feature tools.
Please replace `vcpkg_check_linkage` with `message(FATAL_ERROR)` here.

2021-08-24 07:42 UTC, dg0yt commented
Is the DLL only used by the tools (= a private implementation detail)?
If yes, can't the DLL and its import library be removed from everything but `tools/${PORT}`?

2021-08-24 07:54 UTC, mathisloge commented
> Is the DLL only used by the tools (= a private implementation detail)?
> If yes, can't the DLL and its import library be removed from everything but `tools/${PORT}`?

It's not a private implementation detail. It can be used to develop own plugins for the tool application.

2021-08-24 16:11 UTC, mathisloge commented on ports/comms/portfile.cmake
>      OPTIONS
not applicable in this case. There is not a `COMMS_BUILD_TOOLS` in the upstream cmake. 
The tools feature depends on multiple variables. 
```
-DCC_BUILD_TOOLS_LIBRARY=${COMMS_BUILD_TOOLS}
-DCC_INSTALL_TOOLS_LIBRARY=${COMMS_BUILD_TOOLS}
-DCC_BUILD_TOOLS=${COMMS_BUILD_TOOLS}
-DCC_INSTALL_TOOLS=${COMMS_BUILD_TOOLS}
-DCC_BUILD_DEMO_PROTOCOL=OFF
```

2021-08-24 16:33 UTC, dg0yt commented on ports/comms/portfile.cmake
>      OPTIONS
But you can set multiple variables from the same feature, even inverted ones.

2021-08-24 16:48 UTC, mathisloge commented on ports/comms/portfile.cmake
>      OPTIONS
Ah thanks for the hint. wasn't aware of it

2021-08-24 16:49 UTC, mathisloge commented
@JackBoosY please review again. I've also replaced the deprecated cmake functions with the new one

2021-08-24 16:51 UTC, mathisloge commented on ports/comms/portfile.cmake
>      OPTIONS
Ah thanks! wasn't aware of it

2021-08-25 09:50 UTC, JackBoosY requested changes

2021-08-25 09:50 UTC, JackBoosY commented on ports/comms/portfile.cmake
> +if(CC_BUILD_TOOLS)
```suggestion
if("tools" IN_LIST FEATURES)
```

2021-08-26 02:26 UTC, JackBoosY requested changes

2021-08-26 03:02 UTC, JackBoosY approved these changes

2021-08-26 03:14 UTC, NancyLi1013 requested changes

2021-08-27 02:11 UTC, NancyLi1013 approved these changes

2021-08-31 01:25 UTC, ras0219-msft commented
This all looks clean and reasonable. Thanks for the update!

2021-08-31 01:25 UTC, merged