[qt] Add patches to fix missing includes
microsoft/vcpkg pull request #19668
Opened 2021-08-20 12:40 UTC by nicolasfella

This is needed to build with GCC11

Fixes #19226

2021-08-23 03:09 UTC, JackBoosY commented
cc @Neumann-A for review this PR.

2021-08-23 06:19 UTC, JackBoosY requested changes

2021-08-23 06:19 UTC, JackBoosY commented on ports/qt5-declarative/portfile.cmake
> +qt_submodule_installation(PATCHES limits_include.patch)
Please update qt5-declarative's port version.

2021-08-23 08:04 UTC, Neumann-A approved these changes

2021-09-13 06:16 UTC, JackBoosY commented
/azp run

2021-09-16 06:21 UTC, Be-ing commented
Ready for merge?

2021-09-16 08:05 UTC, JackBoosY approved these changes

2021-09-16 17:34 UTC, merged

2021-09-16 17:34 UTC, BillyONeal commented
Thanks for fixing GCC 11 :)