[lager] add port
microsoft/vcpkg pull request #19661
Opened 2021-08-20 00:57 UTC by waybeforenow

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19538 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  I've tested `x86-linux`, will wait for CI for the rest.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-08-20 02:08 UTC, JonLiu1993 requested changes

2021-08-20 02:08 UTC, JonLiu1993 commented on ports/lager/portfile.cmake
> +    PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-08-20 02:08 UTC, JonLiu1993 commented on ports/lager/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/Lager)
```suggestion
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/Lager)
```

2021-08-20 02:08 UTC, JonLiu1993 commented on ports/lager/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-20 02:08 UTC, JonLiu1993 commented on ports/lager/vcpkg.json
> +  "port-version": 1,
```suggestion
  "version-date": "2021-06-17",
```

2021-08-20 02:08 UTC, JonLiu1993 commented on ports/lager/vcpkg.json
> +    "zug"
```suggestion
    "boost-hana",
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
    "zug"
```

2021-08-20 21:48 UTC, strega-nil-ms commented
/azp run

2021-08-21 02:48 UTC, waybeforenow commented
@JonLiu1993, I incorporated your changes and re-made the branch entirely, please check it again. Thanks

2021-08-23 06:34 UTC, JonLiu1993 approved these changes

2021-08-23 06:45 UTC, JonLiu1993 commented
Feature 'docs' tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static
- x64-linux

2021-08-31 01:29 UTC, ras0219-msft approved these changes

2021-09-03 00:57 UTC, merged

2021-09-03 00:57 UTC, BillyONeal commented
Thanks for the new port! 👍