[vcpkg-tool] Auto update sha512
microsoft/vcpkg pull request #19679
Opened 2021-08-21 01:08 UTC by autoantwort

Needed for https://github.com/microsoft/vcpkg-tool/pull/166

2021-09-15 17:34 UTC, strega-nil-ms requested changes

2021-09-15 17:34 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_download_distfile.cmake
> +        if(_VCPKG_SHA512_MISMATCH_NO_ERROR)
This should be `Z_VCPKG_SHA512_MISMATCH_NO_ERROR`.

2021-10-08 07:23 UTC, PhoebeHui commented
@strega-nil-ms, could you please take a look again?

2022-09-14 11:13 UTC, wrobelda commented
Is this still planned for inclusion? It saves tremendous amount of time when mass-updating ports, like I do for KF5 frameworks.

2022-09-16 08:17 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please ping me to reopen if work is still being done.

2022-09-16 08:17 UTC, closed without merging

2022-09-16 08:18 UTC, JackBoosY commented
Needs to wait for https://github.com/microsoft/vcpkg-tool/pull/166 merge first.