[nlohmann-json] update to 3.10.0
microsoft/vcpkg pull request #19690
Opened 2021-08-22 09:21 UTC by mathisloge

**Describe the pull request**

- #### What does your PR fix?  
updates nlohmann-json to 3.10.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

2021-08-23 02:34 UTC, NancyLi1013 requested changes

2021-08-23 02:34 UTC, NancyLi1013 commented on ports/nlohmann-json/vcpkg.json
> +  "version-string": "3.10.0",
```suggestion
  "version-semver": "3.10.0",
```
This should be served by [version-semver](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-semver).

2021-08-23 02:34 UTC, NancyLi1013 commented on ports/nlohmann-json/portfile.cmake
>  vcpkg_configure_cmake(
```suggestion
vcpkg_cmake_configure(
```
Since you have updated `vcpkg_fixup_cmake_targets` to the new function. Could you please also update this one?

2021-08-23 02:34 UTC, NancyLi1013 commented on ports/nlohmann-json/portfile.cmake
>      PREFER_NINJA
```suggestion
```
If using new function, this argument is not needed here.

2021-08-23 02:34 UTC, NancyLi1013 commented on ports/nlohmann-json/portfile.cmake
>  vcpkg_install_cmake()
```suggestion
vcpkg_cmake_install()
```

2021-08-23 02:34 UTC, NancyLi1013 commented on ports/nlohmann-json/portfile.cmake
>  file(INSTALL ${SOURCE_PATH}/LICENSE.MIT DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE.MIT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-23 02:34 UTC, NancyLi1013 commented on ports/nlohmann-json/vcpkg.json
> +    "vcpkg-cmake-config"
```suggestion
{
    "name": "vcpkg-cmake",
    "host": true
},
{
   "name": "vcpkg-cmake-config",
   "host": true
    }
```
We should add the dependencies like this for `vcpkg-cmake `and `vcpkg-cmake-config`.

2021-08-23 14:44 UTC, mathisloge commented on ports/nlohmann-json/vcpkg.json
> +  "version-string": "3.10.0",
yeah, wasn't sure because i haven't found a clear statement at the library. But just searched the issues and the maintainer confirmed semver https://github.com/nlohmann/json/issues/721#issuecomment-326494840.

2021-08-24 00:28 UTC, NancyLi1013 approved these changes

2021-08-24 01:16 UTC, NancyLi1013 commented
Hi @mathisloge 

Thanks for your PR! @mathisloge

LGTM now, but I'm not clear why it get source codes in another way before. So this PR still needs further review.

2021-08-24 04:37 UTC, mathisloge commented
> Hi @mathisloge 
> 
> Thanks for your PR! @mathisloge
> 
> LGTM now, but I'm not clear why it get source codes in another way before. So this PR still needs further review.
> 

Maybe the upstream cmake changed since last release. But that's just a guess

2021-08-24 23:25 UTC, ras0219-msft requested changes
We fetch the source code using these individual fetches because the nlohmann-json repo has _massive_ test files checked in that cause significant slowdowns and bloat.

As painful as it is, please do switch back to the individual file downloads for now. If you're interested in being extra awesome, could you add a comment to this effect to the file as you're doing that?

Thanks so much for the PR and sorry for the mystery!

2021-08-25 05:18 UTC, mathisloge commented
@ras0219-msft could you clarify which _massive_ test files you mean? 
The whole repository unzipped is around 11 MB. It's something but in my opinion it is not _massive_. 
If I compare it to other header only repos like asio, it is half the size of that. 

@NancyLi1013 upstream has released a new minor. updated to it

2021-08-25 05:24 UTC, mathisloge commented
@ras0219-msft I think you are referring to https://github.com/microsoft/vcpkg/pull/5258#issuecomment-459929209

But that has definitely changed since then:
![image](https://user-images.githubusercontent.com/13556116/130731322-366f9cd3-55f4-4fa2-89ef-7c6306253c1a.png)

2021-08-25 05:54 UTC, NancyLi1013 requested changes

2021-08-25 05:54 UTC, NancyLi1013 commented on versions/n-/nlohmann-json.json
> +      "version-semver": "3.10.1",
This is not right, please keep this and the new version should be added.
```
"git-tree": "4318f5430d8885b9dcb9d4c5478e9e1299df33d5",
"version-semver": "3.10.0",
```
Please run `vcpkg x-add-version --overwrite-version nlohmann` to update this.

2021-09-02 23:05 UTC, merged

2021-09-02 23:05 UTC, ras0219-msft commented
Yep, looks like I was working off of outdated info. Thanks for the update!