[icu] Fix tool path
microsoft/vcpkg pull request #19726
Opened 2021-08-24 10:32 UTC by PhoebeHui

Fixes https://github.com/microsoft/vcpkg/issues/18086

The vcpkg tool path passed when cross build, however, the path doesn't convert to unix path. So when the top level contains 'dev' word, it will cause below failures.

Before:
E:/dev/vcpkg/installed/x64-windows/tools/icu

After:
/e/dev/vcpkg/installed/x64-windows/tools/icu

Failures:
```
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
'bash' is not recognized as an internal or external command,
operable program or batch file.
-- return status = 1
Failed to compile oma.c
'LIB.exe' is not recognized as an internal or external command,
operable program or batch file.
-- return status = 1
Error creating Windows DLL library. Failed command: LIB.exe /nologo /out:"../lib/sicudtd.lib" "./out/tmp/icudt69l_dat.obj"
Error generating package data.
make[1]: *** [Makefile:176: packagedata] Error 1
make: *** [Makefile:153: all-recursive] Error 2
```

2021-08-25 03:11 UTC, JackBoosY requested changes

2021-08-25 03:11 UTC, JackBoosY commented on ports/icu/portfile.cmake
> +    string(REGEX REPLACE "([a-zA-Z]):/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
```suggestion
    string(REGEX REPLACE "^([a-zA-Z])+:/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
```

2021-08-25 05:46 UTC, JackBoosY commented
@Neumann-A @past-due @autoantwort @dg0yt Should we check all the paths in `vcpkg_configure_make` when using mingW crossbuild?

2021-08-25 06:09 UTC, JackBoosY commented on ports/icu/portfile.cmake
> +    string(REGEX REPLACE "([a-zA-Z]):/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
I think the best way is to get the drive letter through the cmake function and replace it with unix format (if cmake does not provide a conversion path function).

2021-08-25 06:30 UTC, JackBoosY commented on ports/icu/portfile.cmake
> +    string(REGEX REPLACE "([a-zA-Z]):/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
```cmake

            find_program(cygpath NAMES cygpath PATHS "${MSYS_ROOT}/usr/bin" REQUIRED)
            MESSAGE("cygpath: ${cygpath}")
            vcpkg_execute_required_process(
                COMMAND ${cygpath} ${IN_PATHS}
                WORKING_DIRECTORY ${CURRENT_BUILDTREES_DIR}
                OUTPUT_VARIABLE OUT_VARS
                LOGNAME cypath_options
            )
```

2021-08-25 06:50 UTC, dg0yt commented on ports/icu/portfile.cmake
> +    string(REGEX REPLACE "([a-zA-Z]):/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
Note that accessing `MSYS_ROOT` in the scope of the portfile requires an explicit `vcpkg_acquire_msys`. Wouldn't `find_program` work without `PATHS` option?

2021-08-25 07:20 UTC, PhoebeHui commented on ports/icu/portfile.cmake
> +    string(REGEX REPLACE "([a-zA-Z]):/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
I'd like to use the regex instead personally. @ras0219 @ras0219-msft, any thoughts?

2021-08-25 07:46 UTC, JackBoosY commented
@dg0yt See https://github.com/microsoft/vcpkg/pull/19734.

2021-08-25 10:20 UTC, autoantwort commented
> @Neumann-A @past-due @autoantwort @dg0yt Should we check all the paths in `vcpkg_configure_make` when using mingW crossbuild?

I don't think that this is needed. On linux the /dev folder lists all your devices. You never use this folder to put custom stuff there (I don't know it this is even possible)

2021-08-31 00:52 UTC, ras0219-msft commented on ports/icu/portfile.cmake
> +    set(TOOL_PATH "${_VCPKG_INSTALLED_DIR}/${HOST_TRIPLET}/tools/${PORT}")
```suggestion
    set(TOOL_PATH "${CURRENT_HOST_INSTALLED_DIR}/tools/${PORT}")
```

2021-08-31 01:35 UTC, PhoebeHui commented on ports/icu/portfile.cmake
> +    string(REGEX REPLACE "([a-zA-Z]):/" "/\\1/" _VCPKG_TOOL_PATH "${TOOL_PATH}")
Updated, thanks for your review!

2021-08-31 01:37 UTC, PhoebeHui commented on ports/icu/portfile.cmake
> +    set(TOOL_PATH "${_VCPKG_INSTALLED_DIR}/${HOST_TRIPLET}/tools/${PORT}")
Updated!, thanks for your review!

2021-08-31 06:46 UTC, JackBoosY approved these changes

2021-09-02 04:26 UTC, BillyONeal commented
/azp run

2021-09-03 23:54 UTC, ras0219-msft approved these changes

2021-09-03 23:54 UTC, ras0219-msft commented
LGTM once merged from master

2021-09-07 22:19 UTC, merged

2021-09-07 22:19 UTC, BillyONeal commented
Thanks for the fix!