[libgo] fix baseline issue
microsoft/vcpkg pull request #19773
Opened 2021-08-27 14:38 UTC by cenit

its own cmakelists.txt is a mess, the patch to make it really work is as big as the file itself....
also, now it builds on windows

2021-08-30 06:10 UTC, PhoebeHui requested changes
Thanks for your PR!

2021-08-30 06:10 UTC, PhoebeHui commented on ports/libgo/cmake.patch
> +-message("----------------------------------")
For minimizing the patch, Could you add a AND FALSE or && 0 to the condition than to delete every line of the conditional?

2021-08-30 06:10 UTC, PhoebeHui commented on ports/libgo/cmake.patch
> +-    set(PROFILE_FLAGS "-pg ${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}}")
For minimizing the patch, Could you add a AND FALSE or && 0 to the condition than to delete every line of the conditional?

2021-08-30 06:17 UTC, cenit commented on ports/libgo/cmake.patch
> +-message("----------------------------------")
but there is always the else() case! 
what do you mean? wrapping the whole section in another external if() clause)

2021-08-30 06:18 UTC, cenit commented on ports/libgo/cmake.patch
> +-    set(PROFILE_FLAGS "-pg ${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}}")
here it might work, but waiting for your reply to the other similar question before approaching the problem with the misunderstood solution

2021-08-30 06:28 UTC, PhoebeHui commented on ports/libgo/cmake.patch
> +-message("----------------------------------")
You can add another external if() clause to wrap the whole section.

2021-09-13 06:36 UTC, PhoebeHui approved these changes

2021-09-13 21:56 UTC, merged

2021-09-13 21:57 UTC, BillyONeal commented
Thanks for making this library work on Windows! Have you contracted upstream to see if they would take the parts of the patch that just fix building? (The `install` parts of the patch seem vcpkg specific so one could understand if they don't want to take that part)