[kf5bookmarks] new port (WIP)
microsoft/vcpkg pull request #19780
Opened 2021-08-28 13:06 UTC by wrobelda

**Describe the pull request**
  Adds new kf5bookmarks port. This is a WIP.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All official, plus `arm64-osx`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I am still working on this PR

2021-08-31 00:40 UTC, wrobelda commented
@NancyLi1013 the CI infra seems to have some random problems, look like one of the agents has leftovers in C:\installed

2021-09-24 01:15 UTC, wrobelda commented
@NancyLi1013 this no longer has any dependencies, ready to be merged.

2021-09-24 03:05 UTC, NancyLi1013 requested changes

2021-09-24 03:05 UTC, NancyLi1013 commented on ports/kf5bookmarks/fix_config_cmake.patch
> +
Could you please remove these information?

2021-09-24 03:05 UTC, NancyLi1013 commented on ports/kf5bookmarks/vcpkg.json
> +  "version-semver": "5.84.0",
```suggestion
  "version": "5.84.0",
```
This should be version here.

2021-09-24 08:22 UTC, wrobelda commented on ports/kf5bookmarks/fix_config_cmake.patch
> +
Done.

2021-09-24 08:23 UTC, wrobelda commented on ports/kf5bookmarks/vcpkg.json
> +  "version-semver": "5.84.0",
Done.

2021-09-24 09:00 UTC, NancyLi1013 approved these changes

2021-09-26 02:31 UTC, NancyLi1013 commented
LGTM now. thanks for adding this port. @wrobelda

2021-09-28 00:15 UTC, merged

2021-09-28 00:15 UTC, BillyONeal commented
Thanks for the new port!