[ecal] added a new port
microsoft/vcpkg pull request #19802
Opened 2021-08-30 14:25 UTC by niclar

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19597

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  tested x64-windows-static & x64-linux

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
 yes

2021-08-31 01:18 UTC, ras0219-msft commented
While reviewing, I noticed:
1. The installed `cmake_functions` pieces are completely inaccessible (no `find_package()` to get them)
2. The LICENSE file is present in the sources, so there's no need for it to be checked in to vcpkg

I've simplified the build taking these facts into account. LGTM if the CI succeeds. Thanks for the PR!

2021-08-31 06:15 UTC, JonLiu1993 requested changes

2021-08-31 06:15 UTC, JonLiu1993 commented on ports/ecal/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-08-31 06:15 UTC, JonLiu1993 commented on ports/ecal/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/bin)
@niclar, Could you please clarify why these directory was deleted?

2021-08-31 06:15 UTC, JonLiu1993 commented on ports/ecal/vcpkg.json
> +  "version": "5.9.0",
```suggestion
  "version-semver": "5.9.0",
```

2021-08-31 06:15 UTC, JonLiu1993 commented on scripts/ci.baseline.txt
> +ecal:x86-windows=fail
Does the upstream support x86-windows and x64-windows?

2021-08-31 09:43 UTC, niclar commented
@ras0219-msft (& @JonLiu1993) thanks for reviewing the PR. 

To my understanding, you added dynamic linking as a requirement. This is not really the case and breaks the build;

```
# eCAL always builds both static and shared binaries because it has a plugin model
vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
```

I removed the line for now, to get the CI working.

2021-08-31 09:44 UTC, niclar commented on ports/ecal/portfile.cmake
> +    PREFER_NINJA
vcpkg_cmake_configure is not found

2021-08-31 09:44 UTC, niclar commented on ports/ecal/portfile.cmake
> +vcpkg_install_cmake()
vcpkg_cmake_install is not found

2021-08-31 09:44 UTC, niclar commented on ports/ecal/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
Is quoting really necessary? -I see that it's not done in other ports

2021-08-31 09:45 UTC, niclar commented on ports/ecal/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/bin)
The build as is produces artifacts in these directories that are not needed and breaks the vcpkg install/deployment

2021-08-31 09:45 UTC, niclar commented on ports/ecal/vcpkg.json
> +  "version": "5.9.0",
fixed

2021-08-31 09:55 UTC, JonLiu1993 requested changes

2021-08-31 09:55 UTC, JonLiu1993 commented on ports/ecal/vcpkg.json
> +}
```suggestion
    "simpleini",
    "tclap",
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-camke-config",
      "host": true
    }
  ]
}
```

2021-08-31 09:58 UTC, JonLiu1993 commented on ports/ecal/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
We now need to add "", those that are not added will be added later when we update port or fix bugs

2021-08-31 09:59 UTC, JonLiu1993 commented on ports/ecal/portfile.cmake
> +vcpkg_install_cmake()
Same as above.

2021-08-31 10:06 UTC, niclar commented on scripts/ci.baseline.txt
> +ecal:x86-windows=fail
Yes I think so, and this vcpkg build does not (unresolved symbols in ecal_rec_addon_cored.dll) out of the box. Hence I've not spent any more time on it. This is is probably good enough for a MVP, no ?

2021-08-31 10:15 UTC, niclar commented on ports/ecal/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
FYI when doing quoted paths (/ format) in the vcpkg_configure_cmake call (e.g as a -DPATH="<path>") I experienced that linux paths got garbled (works in windows).

2021-08-31 10:19 UTC, niclar commented on ports/ecal/vcpkg.json
> +}
I get this;
`Error: while loading vcpkg-camke-config:
The port directory (C:\src\thirdparty\vcpkg-clean\ports\vcpkg-camke-config) does not exist
Error: failed to load port from C:\src\thirdparty\vcpkg-clean\ports\vcpkg-camke-config
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.`

2021-08-31 10:27 UTC, niclar commented on ports/ecal/vcpkg.json
> +}
thanks.  fixed

2021-09-01 08:37 UTC, JonLiu1993 commented on ports/ecal/vcpkg.json
> +  "supports": "!emscripten",
```suggestion
  "supports": "!emscripten & !x86 & !x64",
```

2021-09-01 08:39 UTC, JonLiu1993 commented on ports/ecal/portfile.cmake
> +
```suggestion
vcpkg_fail_port_install(ON_ARCH "x86" "x64" ON_TARGET "windows")
```

2021-09-01 08:39 UTC, JonLiu1993 approved these changes

2021-09-01 09:46 UTC, niclar commented on ports/ecal/portfile.cmake
> +
this line will effectively block *windows-static  builds which isn't correct

2021-09-01 09:52 UTC, niclar commented on ports/ecal/vcpkg.json
> +  "supports": "!emscripten",
-Shouldn't it rather read x86-windows and x64-windows, or is this field enforced somewhere ?

2021-09-01 09:57 UTC, JackBoosY commented
I will take over this PR.

2021-09-02 07:08 UTC, JackBoosY commented on ports/ecal/portfile.cmake
> +message(WARNING "ecal in vcpkg does not currently support find_package(eCAL) -- you will need to manually add headers and libraries via `find_library()` and `find_path()`")
That's no needed because large count of ports in vcpkg also do not support `find_package`.

2021-09-02 07:54 UTC, JackBoosY commented
Since some necessary plugins are always built as dynamic libraries and they do not export any symbols on Windows, we have to build this port as static:
In _source/CMakeLists.txt_ line 480:
```
# --------------------------------------------------------
# protobuf utilities
# --------------------------------------------------------
add_subdirectory(contrib/ecalproto)
```
Please note that it has not been included in any judgment.

In _source/contrib/ecalproto/CMakeLists.txt_ line 40:
```
ecal_add_library(${PROJECT_NAME} ${ecal_protobuf_src} ${ecal_protobuf_header})
```
This plugin doesn't export any symbols but be used in other internal libraries:
```
[117/146] cmd.exe /C "cd . && G:\19802\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=ecal\core\CMakeFiles\core.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86\link.exe"  ecal\core\CMakeFiles\core.dir\src\io\rcv_sample.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\snd_raw_buffer.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\snd_sample.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\udp_init.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\udp_receiver.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\udp_sender.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\ecal_memfile.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\ecal_memfile_pool.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\win32\ecal_memfile_win32.cpp.obj ecal\core\CMakeFiles\core.dir\src\mon\ecal_monitoring_def.cpp.obj ecal\core\CMakeFiles\core.dir\src\mon\ecal_monitoring_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\mon\ecal_monitoring_threads.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_proto_dyn_json_sub.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_pubgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_publisher.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_subgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_subscriber.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_inproc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_udp.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_udp_mc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer_inproc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer_udp_mc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_shm.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer_shm.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_client.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_client_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_server.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_server_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_tcpclient.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_tcpserver.cpp.obj ecal\core\CMakeFiles\core.dir\src\convert_utf.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_clang.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_config.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_descgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_event.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_global_accessors.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_globals.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_log.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_log_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_process.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_reggate.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_register.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_servgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_thread.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_time.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_timegate.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_timer.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_util.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecalc.cpp.obj ecal\core\CMakeFiles\core.dir\src\sys_usage.cpp.obj  /out:bin\ecal_cored.dll /implib:ecal\core\ecal_cored.lib /pdb:bin\ecal_cored.pdb /dll /version:2021.5 /machine:X86 /nologo    /debug /INCREMENTAL  contrib\ecalproto\ecal_protod.lib  iphlpapi.lib  psapi.lib  shlwapi.lib  winmm.lib  ws2_32.lib  wsock32.lib  lib\CustomTclap\ecal_CustomTclapd.lib  ecal\pb\ecal_pbd.lib  lib\ecal_utils\ecal_utilsd.lib  G:\19802\vcpkg\installed\x86-windows\debug\lib\libprotobufd.lib  G:\19802\vcpkg\installed\x86-windows\debug\lib\libprotobufd.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: bin/ecal_cored.dll ecal/core/ecal_cored.lib 
cmd.exe /C "cd . && G:\19802\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=ecal\core\CMakeFiles\core.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86\link.exe"  ecal\core\CMakeFiles\core.dir\src\io\rcv_sample.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\snd_raw_buffer.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\snd_sample.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\udp_init.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\udp_receiver.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\udp_sender.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\ecal_memfile.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\ecal_memfile_pool.cpp.obj ecal\core\CMakeFiles\core.dir\src\io\win32\ecal_memfile_win32.cpp.obj ecal\core\CMakeFiles\core.dir\src\mon\ecal_monitoring_def.cpp.obj ecal\core\CMakeFiles\core.dir\src\mon\ecal_monitoring_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\mon\ecal_monitoring_threads.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_proto_dyn_json_sub.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_pubgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_publisher.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_subgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\pubsub\ecal_subscriber.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_inproc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_udp.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_udp_mc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer_inproc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer_udp_mc.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_reader_shm.cpp.obj ecal\core\CMakeFiles\core.dir\src\readwrite\ecal_writer_shm.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_client.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_client_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_server.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_service_server_impl.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_tcpclient.cpp.obj ecal\core\CMakeFiles\core.dir\src\service\ecal_tcpserver.cpp.obj ecal\core\CMakeFiles\core.dir\src\convert_utf.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_clang.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_config.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_descgate.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_event.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_global_accessors.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_globals.cpp.obj ecal\core\CMakeFiles\core.dir\src\ecal_log.cpp.obj ecal\core\CMakeFiles\core.dir\src\ [...]

2021-09-02 08:28 UTC, JackBoosY commented
However, the core library is built as shared library:
In _source/ecal/core/CMakeLists.txt_ line 355:
```cmake
ecal_add_ecal_shared_library(${PROJECT_NAME}_c ${ecal_c_src} ${ecal_c_win_src})
```
So I guess there is some problems with the port being built under Windows.

2021-09-02 09:09 UTC, JackBoosY commented on ports/ecal/disable-app-plugins.patch
> ++if (DBUILD_APPS)
There is a internal issue: the library `rec_addon_core` uses external recorder_impl which defined in `rec_addon_dummy`, but `rec_addon_dummy` depends on `rec_addon_core`.

2021-09-02 09:11 UTC, JackBoosY commented on ports/ecal/fix-build.patch
> ++endif()
This library doesn't export any symbols on Windows, so I forced it as a static library on Windows.

2021-09-02 09:11 UTC, JackBoosY commented on ports/ecal/fix-build.patch
> ++endif()
Same as above.

2021-09-02 09:52 UTC, niclar commented
The prior working static build built ecal_core.dll & ecal_core_c.dll, erroneously, I presume, so I removed them.

```
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")
```


ecal_core.lib  (.a)    is the only library needed to get basic pub/sub working

2021-09-02 09:56 UTC, JackBoosY commented
Now ecal:x86-windows generated the following libraries:
```
ecal:/bin/ecal_core.dll
ecal:/bin/ecal_core.pdb
ecal:/bin/ecal_core_c.dll
ecal:/bin/ecal_core_c.pdb
ecal:/bin/ecaltime_plugins/ecaltime-localtime.dll
ecal:/bin/ecaltime_plugins/ecaltime-localtime.pdb
ecal:/bin/ecaltime_plugins/ecaltime-simtime.dll
ecal:/bin/ecaltime_plugins/ecaltime-simtime.pdb
ecal:/lib/ecal_core.lib
ecal:/lib/ecal_core_c.lib
ecal:/lib/ecal_hdf5.lib
ecal:/lib/ecal_pb.lib
ecal:/lib/ecal_proto.lib
ecal:/lib/ecal_utils.lib
```
Did you mean we only need to generated `ecal_core.dll` now?

2021-09-02 10:03 UTC, niclar commented
No that's the dynamically linked build. I'm talking about the static build   *-windows-static

2021-09-02 14:48 UTC, Kerstin-Keller commented
Hi all,
I am from the eCAL team, and wanted to give :+1: on integrating eCAL with vcpkg.
Maybe I can help clarify some of the issue.

The core library which provides the communication capabilities is 
`ecal_core / ecal_core_c` (C++ and C language binding), the user will also need ecal_proto when using protobuf serializsation.
`ecal_hdf5` is necessary for reading from / writing to eCAL measurements, it needs ecal_utils.

The time plugins are not strictly necessary. You can do without them and disable them with `-DBUILD_TIME=OFF`.

As you have seen, we disable static builds for the core communication library, as linking ecal twice (e.g. static linkage into an application and dll at the same time can lead to serious trouble).
I am pretty certain that the eCAL-config.cmake file will not work properly when building static libs.

Is it possible for vcpkg, to offer eCAL only as shared?

2021-09-02 14:58 UTC, Kerstin-Keller commented
Also a disclaimer:
On windows, we've always build eCAL in a mode such that
- the core communication and plugins (for time) are build as dynamic library
- everything else (e.g. helper libraries, and the measurement library) are build statically.
I am well aware that this might not be the super generic approach. It was the "easiset" way to make things work.
We can definetly work on exporting symbols for the ecal_hdf5 case, so that everything may be build dynamically (or at least user facing libraries).

2021-09-03 02:16 UTC, JackBoosY commented
> Also a disclaimer:
> On windows, we've always build eCAL in a mode such that
> 
> * the core communication and plugins (for time) are build as dynamic library
> * everything else (e.g. helper libraries, and the measurement library) are build statically.

Yeah, so we forced set ecal to build as dynamic.

> I am well aware that this might not be the super generic approach. It was the "easiset" way to make things work.
> We can definetly work on exporting symbols for the ecal_hdf5 case, so that everything may be build dynamically (or at least user facing libraries).

Sounds great.

2021-09-03 07:41 UTC, niclar commented
@JackBoosY  "Yeah, so we forced set ecal to build as dynamic" 

-not really, the originally pushed static build of core is just fine albeit restricted in scope (only the core lib and its static dependencies)

2021-09-03 08:22 UTC, JackBoosY commented
@niclar That's because you removed _bin_ and _debug/bin_ after build, however, the core libraries are always built as dyanmic library. Therefore, that's incorrect because you removed the core libraries.

2021-09-03 08:54 UTC, niclar commented
Semantics. -When building the static build yes it also builds the dynamic ones. Disable the dynamic ones in that build and we're done, no ? ( Don't conflate "core libraries" with the core library (ecal_core.lib) which is strictly speaking the one needed for basic pub/sub. )

2021-09-03 09:39 UTC, JackBoosY commented
@niclar As the member said:
> The core library which provides the communication capabilities is
ecal_core / ecal_core_c (C++ and C language binding), the user will also need ecal_proto when using protobuf serializsation.
ecal_hdf5 is necessary for reading from / writing to eCAL measurements, it needs ecal_utils.

And

> On windows, we've always build eCAL in a mode such that
>
> the core communication and plugins (for time) are build as dynamic library
> everything else (e.g. helper libraries, and the measurement library) are build statically.

If a dynamic library is generated during static build, it will definitely be blocked in the final check `POST_CHECK`.

2021-09-03 10:34 UTC, Kerstin-Keller commented
> The prior working static build built ecal_core.dll & ecal_core_c.dll, erroneously, I presume, so I removed them.
> 
> ```
> file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
> file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")
> ```
> 
> ecal_core.lib (.a) is the only library needed to get basic pub/sub working

eCAL will never build *both* shared and static libs.
So if you remove `ecal_core.dll`, it's very likely that `ecal_core.lib` is only the linker lib, but not the full static library.
Because on windows:
- Dynamic build -> libA.dll & libA.lib (small size)
- Static build -> libA.lib (big size)

For a static build you will need to change this line https://github.com/continental/ecal/blob/49e37df6216b9d07ab8bcdbc643eee8f65ff7e66/ecal/core/CMakeLists.txt#L321
to just `ecal_add_library` but I am not 100% sure what the consequences will be.

I will be out of office for 3 weeks, maybe @FlorianReimold or @hannemn can help out a bit.

2021-09-07 09:21 UTC, JackBoosY commented
Since it is risky to change the build type of the core library, I think the current changes is just fine.

2021-09-08 22:20 UTC, strega-nil-ms commented on ports/ecal/fix-build.patch
> ++endif()
Shouldn't we solve this by using `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` on windows?

2021-09-10 03:50 UTC, BillyONeal commented on ports/ecal/portfile.cmake
> +    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
```suggestion
    # We build core libraries as a static library, but use requires plugins always built
    # as DLLs intended to be found through runtime dynamic linking. As the deployment
    # for the customer involves deploying those plugin DLLs, we call this a "dynamic only"
    # port.
    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)

```

2021-09-10 03:52 UTC, BillyONeal commented on ports/ecal/portfile.cmake
> +    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
@niclar @Kerstin-Keller Can you add a comment like this explaining the situation why you are forcing some libraries to be static despite the port being dynamic-only? (I suggested my understanding of the results of the preceding conversation)

2021-09-10 03:53 UTC, BillyONeal requested changes
See comment

2021-09-13 08:31 UTC, niclar commented on ports/ecal/portfile.cmake
> +    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
@BillyONeal Originally the port was static only , since that was/is our requirement. I made the necessary changes (albeit ad-hoc) to the ecal build to facilitate that and deferred the dynamic port. As a general observation, mixing static and dynamic libraries in the same vcpkg build as proposed/implied seems inconsistent. In this case one would expect a static build to be pure albeit restricted in scope or the dynamic dependencies made optional at the least.

That said we won't proceed with ecal at this time so proceed as you want.

Thanks all for your time and effort

2021-09-13 09:15 UTC, niclar commented
> risky to change the build type of the core library

No really, the pub/sub tests runs fine.

2021-09-14 06:13 UTC, JonLiu1993 approved these changes

2021-09-14 18:49 UTC, BillyONeal commented on ports/ecal/portfile.cmake
> +    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
>As a general observation, mixing static and dynamic libraries in the same vcpkg build as proposed/implied seems inconsistent.

That's correct, it's generally not OK. The problem is that static customers expect to be able to distribute their program as a single binary, and producing DLLs breaks that, and dynamic customers don't expect each consumer of a library to have their own copies of globals. (If a lib is built static, it is *copied* into each DLL, so if for example it declares a lock table or other global or local-static variable, there are multiple copies of that global or local-static in the process)

> I made the necessary changes (albeit ad-hoc) to the ecal build to facilitate that and deferred the dynamic port. 
> That said we won't proceed with ecal at this time so proceed as you want.

That sounds like maybe we shouldn't merge this then?

2021-09-15 08:05 UTC, niclar commented on ports/ecal/portfile.cmake
> +    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Maybe not. I haven't tested this dynamic build.

@Kerstin-Keller et al. at ecal can drive it from here (& maybe improve the situation for us static consumers) if they're interested I reckon.

2021-09-15 18:31 UTC, BillyONeal commented
https://github.com/microsoft/vcpkg/pull/19802#discussion_r708941548

>>That sounds like maybe we shouldn't merge this then?
>Maybe not. I haven't tested this dynamic build.
>
>@Kerstin-Keller et al. at ecal can drive it from here (& maybe improve the situation for us static consumers) if they're interested I reckon.

OK, in that case I'm going to close this PR for now; I don't think it's a good idea to land something in a configuration neither its expected customers nor upstream have tested / expect. @Kerstin-Keller if you are still interested in continuing here, please create a new PR (so that you're the owner). You can start from @niclar 's branch https://github.com/niclar/vcpkg/tree/ecal-5.9.0 . Please link back to this PR so that folks can follow the discussion that has occurred.

@niclar Thanks nonetheless for your contribution; I hope any other contributions go smoothly :)

2021-09-15 18:31 UTC, closed without merging