[sentencepiece] v0.1.95
microsoft/vcpkg pull request #19858
Opened 2021-09-01 15:26 UTC by JackyYin

Update sentencepiece from 0.1.82 to 0.1.95.

2021-09-01 20:25 UTC, xavier2k6 commented
Why not go with latest v0.1.96?
https://github.com/google/sentencepiece/releases/latest

2021-09-02 01:49 UTC, JackyYin commented
Hi @xavier2k6,
because currently I need a `0.1.95` version,
maybe I can open another PR for `0.1.96` after this PR is merged.

2021-09-02 06:17 UTC, JonLiu1993 approved these changes

2021-09-04 00:09 UTC, ras0219-msft requested changes
LGTM after the patch file is removed. Thanks for the PR!

2021-09-04 00:09 UTC, ras0219-msft commented on ports/sentencepiece/portfile.cmake
> -    PATCHES rename-version.patch
Could you also remove the no longer used patchfile?

https://github.com/microsoft/vcpkg/blob/1021933b268afa63a28378dec8ce85bde0b01d30/ports/sentencepiece/rename-version.patch

2021-09-04 00:28 UTC, JackyYin commented on ports/sentencepiece/portfile.cmake
> -    PATCHES rename-version.patch
Hello @ras0219 ,
I just removed the patch file.
please check.

2021-09-04 01:47 UTC, BillyONeal commented
simdutf should be fixed by https://github.com/microsoft/vcpkg/pull/19987

2021-09-05 16:49 UTC, merged

2021-09-05 16:49 UTC, BillyONeal commented
Thanks for your contribution!

2021-09-05 19:52 UTC, cenit commented
https://github.com/JackyYin/vcpkg/blob/e113e89769c8cc6aab6527e9ab86c0ece6019645/ports/sentencepiece/portfile.cmake#L25

@ras0219-msft 
isn’t this even worse than using an imposed CMAKE_DEBUG_SUFFIX, which is clearly stated as unwanted on vcpkg?
or, let me rephrase: isn’t it better to use CMAKE_DEBUG_SUFFIX instead of hard renaming an artifact after the built?

2021-09-06 02:03 UTC, JackyYin commented
Hello @cenit,
Thanks for your feedback.
I think I can fix this in another PR, 
maybe add an OPTIONS `-DCMAKE_DEBUG_POSTFIX=d` and remove line 25 - line 29 as you mentioned.

2021-09-06 03:23 UTC, cenit commented
let's discuss with @ras0219-msft because that option is really not wanted here (even too much avoided imho), but again those lines are much worse and they passed the review

2021-09-07 21:17 UTC, BillyONeal commented
> let's discuss with @ras0219-msft because that option is really not wanted here (even too much avoided imho), but again those lines are much worse and they passed the review

Some inconsistency between reviewers, sorry. :/

In this case the usual problems with renaming .libs aren't problems because this is an `ONLY_STATIC_LIBRARY` port