[protobuf] Set visibility to "hidden" to avoid a linker warning
microsoft/vcpkg pull request #19908
Opened 2021-09-01 22:32 UTC by daschuer

Apple's ld warns when linked as a static library:
"direct access in function ... to global weak symbol. The weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

**Describe the pull request**

- #### What does your PR fix?  
  Fixes a linker warning on OSX

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 all 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-09-02 09:21 UTC, NancyLi1013 commented
Hi @daschuer 

Could you please run `vcpkg x-add-version --overwrite-version protobuf ` to update versions and then commit the changes?

2021-09-05 15:03 UTC, daschuer commented
Done.

2021-09-07 12:30 UTC, Be-ing commented
Thank you for digging into this. Have you asked upstream about this? It seems like something Protobuf's build system should take care of.

2021-09-07 12:45 UTC, daschuer commented
Protobuf currently uses dllexport detectives not the new fvisibility approach Apple's LD is complaining about. So in my view this is a vcpkg issue which should be solved there. I have no interest to invest more time into this.

2021-09-08 02:29 UTC, JackBoosY commented
It seems that your changes can avoid this issue but no the best solution, and vcpkg doesn't do any extra thing with protobuf.
Can you report this to protobuf upstream: https://github.com/protocolbuffers/protobuf/issues ?

2021-11-22 04:31 UTC, JackBoosY commented
Ping for response.

2021-11-22 07:00 UTC, daschuer commented
I the upstream bug is here since 2021-09-08: https://github.com/protocolbuffers/protobuf/issues/8958 
Is there anything else we can do?

2021-11-22 07:19 UTC, JackBoosY commented
Ah, we should wait for the upstream response first.

2022-01-06 16:54 UTC, JackBoosY approved these changes

2022-01-06 16:54 UTC, JackBoosY commented
Can you please merge to master?

2022-01-09 22:06 UTC, daschuer commented
Done.

2022-01-10 03:46 UTC, JackBoosY commented
The upstream approved this changes.

2022-01-10 08:33 UTC, JackBoosY requested changes

2022-01-10 08:33 UTC, JackBoosY commented on ports/protobuf/portfile.cmake
>      PREFER_NINJA
```suggestion
```

2022-01-10 12:17 UTC, JackBoosY requested changes

2022-01-10 12:17 UTC, JackBoosY commented on ports/protobuf/portfile.cmake
```suggestion

set(protobuf_VISIBILITY_FLAGS )
```
We should declare `protobuf_VISIBILITY_FLAGS` first in oder to prevent it's not defined.

2022-01-11 07:04 UTC, JackBoosY approved these changes

2022-01-11 22:40 UTC, strega-nil-ms reviewed
minor change

2022-01-11 22:40 UTC, strega-nil-ms commented on ports/protobuf/portfile.cmake
> +if(${VCPKG_LIBRARY_LINKAGE} STREQUAL "static")
```suggestion
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static") 
```

2022-01-11 22:42 UTC, strega-nil-ms commented on ports/protobuf/portfile.cmake
> +if(${VCPKG_LIBRARY_LINKAGE} STREQUAL "static")
I can't push to your branch; could you make this change yourself?

2022-01-12 22:27 UTC, daschuer commented
Done

2022-01-13 03:53 UTC, JackBoosY commented
Can you please resolve the file conflict?

Thanks.

2022-01-13 17:35 UTC, JackBoosY commented on versions/p-/protobuf.json
> +      "git-tree": "1126e08fd6414862fc2999aa70d2f66ed42e2d06",
```suggestion
      "git-tree": "a5b79f8273999be1d0ad25104167f45f3e7a6d00",
```

2022-01-13 17:35 UTC, JackBoosY approved these changes

2022-01-18 19:46 UTC, strega-nil-ms commented on ports/protobuf/portfile.cmake
> +    set(protobuf_VISIBILITY_FLAGS )
```suggestion
    set(protobuf_VISIBILITY_FLAGS "")
```

we don't want to unset `protobuf_VISIBILITY_FLAGS`

2022-01-18 19:47 UTC, strega-nil-ms commented on ports/protobuf/portfile.cmake
> +    set(protobuf_VISIBILITY_FLAGS )
@JackBoosY you need to `set(blah "")` in order to give it a value; otherwise, it's just equivalent to `unset(blah)`

2022-01-18 19:48 UTC, strega-nil-ms commented
@daschuer in the future, please mark these PRs as "allow maintainers to push changes" so we can make very minor changes like this.

2022-01-19 16:50 UTC, faysal247 reviewed
Committing change in bot

2022-03-18 06:33 UTC, JackBoosY commented
Sorry for late, can you please merge to master and resolve the file conflicts?

Thanks.

2022-03-19 06:45 UTC, daschuer commented
The build failure seems to be unrelated: 
```FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\installed\\vcpkg\\info\\'```

2022-03-21 05:55 UTC, JackBoosY approved these changes

2022-03-21 18:19 UTC, BillyONeal commented
> Protobuf currently uses dllexport detectives not the new fvisibility approach Apple's LD is complaining about. So in my view this is a vcpkg issue which should be solved there. I have no interest to invest more time into this.

I kind of disagree. It being a vcpkg issue would imply that it was an issue of vcpkg's creation, but that's not the case here: the upstream port just doesn't seem to care about creation of the linker warning in question.

Given that upstream seems to feel skittish about merging this kind of configuration change I'm weakly against this change. @strega-nil-ms / @strega-nil you have reviewed this before; is there something I missed in my reading above?

2022-03-23 03:02 UTC, JackBoosY commented
@BillyONeal I think it's https://github.com/protocolbuffers/protobuf/issues/8958#issuecomment-977221720 which the member said?

2022-03-23 22:13 UTC, BillyONeal commented
> @BillyONeal I think it's [protocolbuffers/protobuf#8958 (comment)](https://github.com/protocolbuffers/protobuf/issues/8958#issuecomment-977221720) which the member said?

Hmmm maybe. Let's double check.

2022-04-07 23:50 UTC, BillyONeal commented
I interpret https://github.com/protocolbuffers/protobuf/issues/8958#issuecomment-1091825229 as an explicit request to be fixed upstream rather than here

2022-04-08 06:16 UTC, daschuer commented
https://github.com/protocolbuffers/protobuf/pull/9768

2022-04-27 20:57 UTC, daschuer commented
I have failed to make the upstream PR work, because of issues with templates in the unit-test when forcing shared libraries.

2022-04-28 01:11 UTC, BillyONeal commented
> I have failed to make the upstream PR work, because of issues with templates in the unit-test when forcing shared libraries.

Unfortunately I think that means we shouldn't merge this, because it means upstream has concerns that there will be missing symbols for their customers, right? Or do I misunderstand the situation?

Sorry for the runaround; we're just paranoid about changes that upstream may not like being applied to their ports.

2022-04-28 06:05 UTC, daschuer commented
Ok, than let's close this as well.

2022-04-28 06:05 UTC, closed without merging