[Qt] update to 6.1.3
microsoft/vcpkg pull request #19918
Opened 2021-09-02 08:53 UTC by Neumann-A

Depends: #19657 (CI will fail without it)
Testing: None. Waiting for #19657 and CI to do it (without requiring a world rebuild in this PR.)
Closes: #19860

2021-09-03 02:25 UTC, JackBoosY commented
Please ping me if this PR is ready for review.

2021-09-03 04:32 UTC, Neumann-A commented
> Please ping me if this PR is ready for review.

@JackBoosY it is ready

2021-09-03 06:12 UTC, JackBoosY requested changes

2021-09-03 06:12 UTC, JackBoosY commented on ports/qtbase/cmake/qt_port_details.cmake
> +endif()
Why judge `QT_UPDATE_VERSION`?

2021-09-03 07:46 UTC, Neumann-A commented on ports/qtbase/cmake/qt_port_details.cmake
> +endif()
Because I just want to update the refs if `QT_UPDATE_VERSION` is set. Unfortunately the changes to `vcpkg_from_git` broke my update path and always tries to extract the archive which will most likely fail due to the applied patches not yet being updated. As such I need  stub `vcpkg_extract_source_archive` to do nothing. 

The way to update qt is:
- update `QT_VERSION`
- set(QT_UPDATE_VERSION TRUE)
- (optional) set all _REFS variables to 0
- vcpkg.exe install qt qtwayland
- vcpkg.exe remove qtbase --recurse
- copy new REFS from `qt_new_refs.cmake` to `qt_port_details.cmake`
- remove/comment set(QT_UPDATE_VERSION TRUE)
- vcpkg.exe install qt qtwayland
- fix any broken patches. 
- in qt 6.2 there are extra steps necessary for qttools and qtwebengine due to git submodules being used

2021-09-12 23:43 UTC, Be-ing commented on ports/qtbase/cmake/qt_port_details.cmake
> +endif()
Thank you for all the work you put into packaging Qt in vcpkg. Could you document this procedure in the port somewhere so it is easier for others to help maintain the Qt ports?

2021-09-13 06:10 UTC, JackBoosY approved these changes

2021-09-13 21:46 UTC, BillyONeal commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    if(NOT PORT STREQUAL "qtwebengine") # qtwebengine requires python2
Note that python2 is unavailable on modern *nix (e.g. Ubuntu 20.04). I hope they look at dropping that dependency...

2021-09-13 21:47 UTC, BillyONeal commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +        #TAG ${${PORT}_TAG}
Did you intend to leave this commented out?

2021-09-13 22:02 UTC, Neumann-A commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    if(NOT PORT STREQUAL "qtwebengine") # qtwebengine requires python2
That depends on chromium dropping/migrating it not Qt.

2021-09-13 22:08 UTC, Neumann-A commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +        #TAG ${${PORT}_TAG}
The code is just copied from #18687 to make the upgrade path work again (due to the changes applied to `vcpkg_from_git`). 
I removed it in https://github.com/microsoft/vcpkg/pull/18687/commits/361eaa4454323b85a9cb104296b399cc7a1019b5 but didn't intend to retouch this PR. (I would do it via github if the change wouldn't require to rerun `vcpkg x-add-version`)

2021-09-13 22:12 UTC, Be-ing commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    if(NOT PORT STREQUAL "qtwebengine") # qtwebengine requires python2
python2 is still available on Fedora 34 FWIW. I doubt it is installed by default though.

2021-09-13 22:18 UTC, BillyONeal commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +        #TAG ${${PORT}_TAG}
Okie dokie, thanks for the update!

2021-09-13 22:18 UTC, merged