Fix linking amqpcpp on macOS
microsoft/vcpkg pull request #19967
Opened 2021-09-03 08:12 UTC by kjagosz

**When you try to link your app with amqpcpp lib you'll see errors for unsupported architecture**

- #### What does your PR fix?  
  Fix linking amqpcpp on macOS

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-09-03 09:27 UTC, PhoebeHui requested changes
@kjagosz, thanks for the PR!

Could you submit an issue for the problem? And please update the port-version in vcpkg.json and update the baseline version as well.

2021-09-03 09:59 UTC, kjagosz commented
@PhoebeHui i've changed a PR description and commit changes for baseline version and new issue

2021-09-06 07:29 UTC, PhoebeHui commented
Thanks @kjagosz for your updates! Could you update the version database by following steps?

vcpkg x-add-version amqpcpp
git add versions
git commit -m "Update version database"

2021-09-09 03:12 UTC, PhoebeHui approved these changes

2021-09-10 03:57 UTC, BillyONeal commented
I'm a bit concerned to turn on this switch when the upstream project has clearly indicated that they intend for it only to be used on Linux. Have you submitted an issue or documentation change request over there?

2021-09-17 10:21 UTC, PhoebeHui commented
Ping @kjagosz for your response..

2021-10-08 07:20 UTC, PhoebeHui commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2021-10-08 07:20 UTC, closed without merging