[netcdf-c] Fix build under Linux with dynamic linkage
microsoft/vcpkg pull request #19981
Opened 2021-09-03 14:57 UTC by Osyotr

The fix is basically the same as in #19126. 
`gdal` depends on `netcdf-c` since #17698, so it is also fixed.
x64-linux-dynamic: build OK
x64-windows: build OK

2021-09-06 09:30 UTC, JonLiu1993 requested changes

2021-09-06 09:30 UTC, JonLiu1993 commented on ports/netcdf-c/vcpkg.json
>    "version-string": "4.7.4",
```suggestion
  "version-semver": "4.7.4",
```

2021-09-07 02:21 UTC, JonLiu1993 approved these changes

2021-09-08 14:46 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
It seems like it can't be correct to delete the dynamic libraries when targeting dynamic?

2021-09-08 14:52 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
I see in the linked item there is a comment saying that they're empty on non-windows dynamic, I think it needs such a comment here too at a minimum.

2021-09-08 16:21 UTC, Osyotr commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
@BillyONeal I thought that this is common for non-windows libraries to put their .so files in `lib/`, leaving empty `bin/`.
Something like this would be more appropriate than rather obvious comment about emptiness of this folders:
```
elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
   vcpkg_remove_empty_dirs(
       "${CURRENT_PACKAGES_DIR}/bin"
       "${CURRENT_PACKAGES_DIR}/debug/bin"
   )
endif()
```

2021-09-08 18:57 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
>I thought that this is common for non-windows libraries to put their .so files in lib/, 

Maybe it is, I admit to being very underinformed on how `.so`s typically work. (I know about things that make them explode but that's about it.

Considering the only failure here is a "post build lint" check we may want to consider changing the lint check to account for that pattern rather than playing whack a mole with ports.

2021-09-08 18:58 UTC, BillyONeal commented
I'm marking this with `requires:vcpkg-team-review` because we need to decide whether we want to change the lint check in the tool (which will make this change irrelevant) vs. accept this as is.

2021-09-09 04:33 UTC, dg0yt commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
I can confirm that this is the pattern: executables (binaries and scripts) in `bin`, shared objects (.so) and static libraries in `lib`. Sometimes the packages creates empty `bin` when you don't build/install executables. `vcpkg_copy_tools` has a auto-clean feature but probably auto-clean should be applied to every port's `bin`.

If there were a `vcpkg_remove_empty_dirs`, it wouldn't even need the `elseif` condition.

2021-09-09 18:19 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
After some discussion, it appears that cmake creates `CMAKE_INSTALL_BINDIR` regardless of whether that directory is actually used, which is creating this game of whack-a-mole. We would like to see an edit to `vcpkg_cmake_install` which removes these empty directories rather than fixing this on a port-by-port basis. Would you be willing to make that edit?

2021-09-09 18:26 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
@strega-nil @strega-nil-ms reports that this affects osx-dynamic triplets as well.

2021-09-09 22:36 UTC, Osyotr commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
Is there really a way to check that? In this port, `${CURRENT_PACKAGES_DIR}/bin` is not empty after `vcpkg_cmake_install`. There is a file we delete in [line 57](https://github.com/microsoft/vcpkg/blob/467b24ea7bdb6037ca2b538bb6e153102719bc0e/ports/netcdf-c/portfile.cmake#L57).
I think it's better to remove this folders at post-build validation step.

PS: @BillyONeal I've added a cleanup step in `vcpkg_cmake_install` anyway. It obviously fails for this port, but is this what you meant?
```cmake
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
    foreach(_bindir IN ITEMS "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
        file(GLOB _bindir_files "${_bindir}/*")
        list(LENGTH _bindir_files _bindir_files_count)
        if(_bindir_files_count EQUAL 0)
            file(REMOVE_RECURSE "${_bindir}")
        endif()
    endforeach()
endif()
```

2021-09-09 23:42 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
@Osyotr Ah, that's where it came from. Is your impression that this port is unusual in triggering the problem and thus this "whack a mole" fix is OK or that most ports are going to suffer this problem?

2021-09-10 04:28 UTC, dg0yt commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
`git grep "OR NOT VCPKG_TARGET_IS_WINDOWS"` gives only four ports with that pattern. I touched at least one of them, to fix either non-windows or mingw. There may be more ports which do this incorrectly or in another pattern.
The deleted file `nc-config` is an example of a shell script which provides information like cmake config file or pkgconfig file. It should be moved to `tools/${PORT}/bin`, and perhaps added to the `PATH`. But it needs fixup (as did `geos-config`, `curl-config` etc.).

2021-09-10 04:34 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
@dg0yt 

>git grep "OR NOT VCPKG_TARGET_IS_WINDOWS" gives only four ports with that pattern. 

Right, but since no current triplet experiences the problem, it isn't clear if few occurrences is caused by few people/ports being used with triplets creating the problem, or if few occurrences is caused by it just not being a problem for them.

2021-09-10 05:28 UTC, dg0yt commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
> it isn't clear if few occurrences is caused by few people/ports being used with triplets creating the problem, or if few occurrences is caused by it just not being a problem for them.

Agreed. 
But I'm concerned about the barrier for users and contributors when they have to learn how to deal with directories which are sometimes empty, sometimes not empty, and sometimes absent - depending on platform particularies (DLL vs. shared object), linkage, and vcpkg particularities (executables moved to `tools`). 
That's why I suggested to always remove empty `bin` dirs.
Note that `bin` would probably be auto-cleaned here if `nc-config` would be handled by `vcpkg_copy_tools`. But the script doesn't end with `.exe`. Yet another vcpkg particularity...

2021-09-10 06:04 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
>That's why I suggested to always remove empty bin dirs.

Sure, that's kind of what we suggested here too.

>Note that bin would probably be auto-cleaned here if nc-config would be handled by vcpkg_copy_tools.

That was another suggestion at our in-person meeting -- just removing the check around `vcpkg_copy_tools` and call it unconditionally; removing empty bin dirs is what `AUTO_CLEAN` should do. But again we wanted to understand if this is something that substantially all ports will experience vs. something we should spot fix here.

2021-09-10 07:04 UTC, Osyotr commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
I think there will be more ports with such an error.

Output from: `grep -ir "file(remove_recurse \"\?\${CURRENT_PACKAGES_DIR}/bin/"`:
`freealut`
`ignition-common3`
`kf5auth`
`kf5dbusaddons`
`kf5completion`
`kf5config`
`kf5i18n`
`kf5itemmodels`
`kf5itemviews`
`kf5widgetsaddons`
`laszip`
`qtbase` - they did what I did above [portfile.cmake#L301](https://github.com/microsoft/vcpkg/blob/master/ports/qtbase/portfile.cmake#L301) [qt_install_submodule.cmake#L197](https://github.com/microsoft/vcpkg/blob/master/ports/qtbase/cmake/qt_install_submodule.cmake#L197)
`urho3d`
`embree2` - has the same pattern, but currently this lib is windows only
`cmark`
`ismrmrd`
`openmwg`
`osg`

2021-09-13 19:40 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
>But again we wanted to understand if this is something that substantially all ports will experience vs. something we should spot fix here.

I ran a full run of x64-osx-dynamic over the weekend and got:

Succeeded: 1286
Failed: 142
Post build checks failed: 10   <-- Suggests that whack a mole is OK
File conflicts: 8
Cascade: 220

@Osyotr 

>PS: @BillyONeal I've added a cleanup step in vcpkg_cmake_install anyway. It obviously fails for this port, but is this what you meant?

That is what I meant, but given that only 10 ports failed post-build-lint suggests that this isn't some strange CMake behavior, rather, this is something that individual port did that created the bin directory.

2021-09-13 20:31 UTC, Osyotr commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
All right then! What about encapsulating `file(REMOVE_RECURSE ...)` into `vcpkg_remove_empty_dirs(...)`?
Also, were you doing full run of x64-osx-dynamic on Azure Pipelines or your spare PC? If it's the latter and took only two days, I might do the same with x64-linux-dynamic. Is there a command in vcpkg to build everything?

2021-09-13 20:41 UTC, BillyONeal commented on ports/netcdf-c/portfile.cmake
> +elseif(VCPKG_LIBRARY_LINKAGE STREQUAL "static" OR NOT VCPKG_TARGET_IS_WINDOWS)
> What about encapsulating `file(REMOVE_RECURSE ...)` into `vcpkg_remove_empty_dirs(...)`?

That would be a nice thing but I no longer think we should block this PR over it.

> Also, were you doing full run of x64-osx-dynamic on Azure Pipelines or your spare PC?

My laptop.

>Is there a command in vcpkg to build everything?

You can run `vcpkg ci` just like our CI does. See https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/test-modified-ports.ps1 for an example. (Or just consider using that script directly)

2021-09-13 20:42 UTC, BillyONeal approved these changes

2021-09-13 20:42 UTC, BillyONeal commented on ports/netcdf-c/vcpkg.json
> +  "version-semver": "4.7.4",
Did upstream indicate that this is actually semver or should it just be `version`?

2021-09-13 20:45 UTC, Osyotr commented on ports/netcdf-c/vcpkg.json
> +  "version-semver": "4.7.4",
It was @JonLiu1993 suggestion: https://github.com/microsoft/vcpkg/pull/19981#pullrequestreview-747021936

2021-09-13 20:51 UTC, BillyONeal commented on ports/netcdf-c/vcpkg.json
>    "version-string": "4.7.4",
@JonLiu1993  We shouldn't be asking people to mark `semver` unless the project in question actually says they follow semver.

2021-09-14 03:19 UTC, merged

2021-09-14 03:19 UTC, BillyONeal commented
Thanks for the fix and sorry for the runaround :)