[lcms] Backfill compat for lcms::lcms
microsoft/vcpkg pull request #20034
Opened 2021-09-07 22:35 UTC by ras0219-msft

Backfill a few issues unaddressed in https://github.com/microsoft/vcpkg/pull/19551:

1. Follow upstream naming since we're breaking the binary names -- remove `d` suffix in debug
2. Add back compat support for `lcms::lcms` since there's no need to break existing users
3. Remove deprecated helpers (vcpkg_configure_cmake)
4. Switch to `version` scheme

2021-09-07 22:51 UTC, BillyONeal commented on ports/lcms/usage
> +The package lcms:@TARGET_TRIPLET@ provides CMake targets:
I thought we said we don't want `:@TARGET_TRIPLET@` in this output elsewhere?

2021-09-08 01:31 UTC, BillyONeal commented on ports/lcms/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" @ONLY)
```suggestion
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```

2021-09-08 01:31 UTC, BillyONeal commented on ports/lcms/usage
> +The package lcms:@TARGET_TRIPLET@ provides CMake targets:
```suggestion
The package lcms provides CMake targets:
```

2021-09-08 01:31 UTC, BillyONeal commented on ports/lcms/usage
> +The package lcms:@TARGET_TRIPLET@ provides CMake targets:
I'm not sure exactly which PR where this was litigated but I note that including the target triplet here prevents the usages from being deduplicated ( as in https://github.com/microsoft/vcpkg-tool/pull/175 ) . I filed https://github.com/microsoft/vcpkg-tool/pull/185 to make sure the heuristic ones also don't include that.

2021-09-08 06:43 UTC, NancyLi1013 commented on ports/lcms/portfile.cmake
> +vcpkg_cmake_config_fixup()
Why does it call `vcpkg_cmake_config_fixup` twice here?

2021-09-08 08:08 UTC, c72578 commented
Concerning the removal of the `d` suffix in debug, please consider `ports/libraw/lcms2_debug_fix.patch`:
https://github.com/microsoft/vcpkg/blob/615547c1d5b363d3586d2012c4cd7d075a0516b8/ports/libraw/lcms2_debug_fix.patch#L25

2021-09-08 22:55 UTC, BillyONeal commented on ports/lcms/portfile.cmake
> +vcpkg_cmake_config_fixup()
Because the second one provides the name "lcms" rather than "lcms2". I added a comment to indicate this.

2021-09-08 22:56 UTC, BillyONeal approved these changes
I'm happy as long as @c72578 's comment is addressed.

2021-09-09 02:01 UTC, NancyLi1013 commented on ports/lcms/portfile.cmake
> +vcpkg_cmake_config_fixup()
Thanks for your clarification @BillyONeal.

2021-09-10 08:15 UTC, NancyLi1013 requested changes

2021-09-10 08:15 UTC, NancyLi1013 commented on ports/lcms/portfile.cmake
> +file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```

2021-09-21 01:24 UTC, ras0219-msft commented
Because vcpkg builds each flavor separately, the results will still be correct even given the patch: CMake will only ever find a "release" version (which is actually the debug version when built in debug) and will use that regardless of the consumer's configuration.

2021-09-21 17:46 UTC, BillyONeal commented
/azp run

2021-09-23 02:06 UTC, NancyLi1013 approved these changes

2021-09-23 18:00 UTC, merged