[audiofile/cgltf/libsbml] Update to the latest version
microsoft/vcpkg pull request #20066
Opened 2021-09-09 09:19 UTC by NancyLi1013

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19865 
  Fixes #19867 
  Fixes #19885

Update `audiofile `to 1.0.9, use cmake to build instead of installing the headers directly.

Update `cgltf `to 1.10

Update `libsbml `to 5.19.0, update repo from github.

Note:

All features except for `test `for `libsbml ` have passed with the following triplets:

- x86-windows
- x64-windows-static

`test `only support Unix platform.

2021-09-10 02:31 UTC, JackBoosY requested changes

2021-09-10 02:31 UTC, JackBoosY commented on ports/audiofile/fix-cmakeLists.patch
> ++install(TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}Config)
Can you please test the usage?

2021-09-10 02:31 UTC, JackBoosY commented on ports/libsbml/portfile.cmake
> +    HEAD_REF stable
```suggestion
    HEAD_REF development
```
The stable branch should always lag behind the development branch.

2021-09-10 06:48 UTC, NancyLi1013 commented on ports/audiofile/fix-cmakeLists.patch
> ++install(TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}Config)
Has tested the usage and it can work fine.

2021-09-14 02:48 UTC, JackBoosY approved these changes

2021-09-14 03:20 UTC, merged

2021-09-14 03:20 UTC, BillyONeal commented
Thanks for the updates and """""" quotes