[ibarchive] Fix pc file, modernize portfile
microsoft/vcpkg pull request #20146
Opened 2021-09-14 06:44 UTC by dg0yt

- #### What does your PR fix?  
  Fixes the invalid pkgconfig file by switching to modules. (Cf. https://github.com/microsoft/vcpkg/pull/20062#issuecomment-916377810.)
  Modernizes the portfile.
  Drops the unused openssl dependency for osx. 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

- #### Features
  pc file after `vcpkg install 'libarchive[*]'` on x64-osx:

~~~
prefix=${pcfiledir}/../..

exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/../include

Name: libarchive
Description: library that can create and read several streaming archive formats
Version: 3.5.2
Cflags: -I"${includedir}"
Cflags.private: -DLIBARCHIVE_STATIC
Libs: -L"${libdir}" -larchive 
Requires: zlib bzip2 liblzma lzo2 liblz4 libzstd libxml-2.0
~~~
 (Note that `libssl` and `libcrypto` are missing. That's how I found that libarchive doesn't use OpenSSL on 'Darwin'.)

2021-09-14 08:03 UTC, NancyLi1013 requested changes

2021-09-14 08:03 UTC, NancyLi1013 commented on ports/libarchive/portfile.cmake
>          #libb2   ENABLE_LIBB2
Since these features are commented out. We can remove these comments until we add these as features.

2021-09-16 07:47 UTC, dg0yt commented
Hm, there are no pc files for the MSVC builds of port openssl.

2021-09-16 20:22 UTC, dg0yt commented
This is complete. If possible this should be tested with #20062 on windows, static and dynamic.

2021-09-17 20:54 UTC, Neumann-A commented on ports/libarchive/vcpkg-cmake-wrapper.cmake.in
>          endif()
Why `Z_VCPKG` ? Where is the conflict?

2021-09-17 21:31 UTC, dg0yt commented on ports/libarchive/vcpkg-cmake-wrapper.cmake.in
>          endif()
Well, it is a wrapper. It is run in user project scope, isn't it?. And `select_library_configurations` is know to set `<PREFIX>_FOUND`. So this just tries to go out of the way of user projects.

2021-09-18 06:29 UTC, NancyLi1013 commented
The problem caused by CI pipeline line depends on PR https://github.com/microsoft/vcpkg/pull/20236.

2021-09-18 07:37 UTC, c72578 commented
Remark: This is how **`libarchive.pc`** looks now (at 141ec0d4ccf3a65272c284ef49d573c8e696fc48) in case of `x64-windows`:

```
prefix=${pcfiledir}/../..

exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libarchive
Description: library that can create and read several streaming archive formats
Version: 3.5.2
Cflags: -I"${includedir}"
Cflags.private: -DLIBARCHIVE_STATIC
Libs: -L"${libdir}" -larchive
Libs.private:  -lcrypto -lssl -lssl -lssl -lssl -lssl -lssl
Requires.private:  zlib bzip2 liblzma liblz4 libzstd libxml-2.0
```
It contains `-lssl` 6 times under `Libs.private`

2021-09-18 07:58 UTC, dg0yt commented
Thanks for the feedback @c72578. I assume it works now for #20062?

> It contains `-lssl` 6 times under `Libs.private`

I don't think this is a problem for now. The library is added for each matching algorithm. This could be improved upstream, instead of adding complexity to the patch. Maybe when I upstream the patch...

2021-09-18 20:22 UTC, c72578 commented
@dg0yt the situation concerning #20062 has improved, however it is still failing for **`x64-linux`**:
`/usr/bin/ld: cannot find -llz4`

This is how **`libarchive.pc`** looks under **`x64-linux`** now (tested at commit 74f3712):
```
prefix=${pcfiledir}/../..

exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libarchive
Description: library that can create and read several streaming archive formats
Version: 3.5.2
Cflags: -I"${includedir}"
Cflags.private: -DLIBARCHIVE_STATIC
Libs: -L"${libdir}" -larchive 
Requires: zlib bzip2 liblzma liblz4 libzstd libcrypto libxml-2.0 libssl libssl libssl libssl libssl libssl
```
See: `liblz4` in `Requires`

2021-09-19 07:31 UTC, c72578 commented
@dg0yt The remaining issue is related to the port **`lz4`**.
`lz4_x64-linux/debug/lib/pkgconfig\liblz4.pc` contains `-llz4`, but it should contain `-llz4d`
```
prefix=${pcfiledir}/../..
#   LZ4 - Fast LZ compression algorithm
#   Copyright (C) 2011-2014, Yann Collet.
#   BSD 2-Clause License (http://www.opensource.org/licenses/bsd-license.php)

libdir=${prefix}/lib
includedir=${prefix}/../include

Name: lz4
Description: extremely fast lossless compression algorithm library
URL: http://www.lz4.org/
Version: 1.9.3
Libs: -L"${prefix}/lib" -llz4
Cflags: -I"${prefix}/../include"
```

2021-09-19 08:12 UTC, dg0yt commented
> `lz4_x64-linux/debug/lib/pkgconfig\liblz4.pc` contains `-llz4`, but it should contain `-llz4d`

Thanks for reporting @c72578. I added a fix to this PR now.

2021-09-19 12:41 UTC, c72578 approved these changes
@dg0yt Thanks. I have completed the testing and the PR LGTM now.

2021-09-22 07:07 UTC, c72578 commented
@NancyLi1013 PR #20236 has been merged in the meantime.

2021-09-23 02:36 UTC, NancyLi1013 commented
/azp run

2021-09-23 06:40 UTC, NancyLi1013 approved these changes

2021-09-24 19:05 UTC, BillyONeal commented
Thanks @dg0yt for the fixes, @c72578 @JonLiu1993 for testing, and @Neumann-A for the review!

2021-09-24 19:06 UTC, merged

2024-07-05 01:01 UTC, kientzle commented on ports/libarchive/pkgconfig-modules.patch
> ++Requires.private: @LIBARCHIVE_REQUIRES_PRIVATE@
I would appreciate if someone could help us verify libarchive/libarchive#2253 which claims to be a fix for libarchive/libarchive#1446