[discord-game-sdk] use updated domain name
microsoft/vcpkg pull request #20153
Opened 2021-09-14 10:28 UTC by J-Human

**Describe the pull request**
This updates the external URLs to use the base domain name of `discord` instead of `discordapp` since [the company changed the name last year](https://support.discord.com/hc/en-us/articles/360042987951-Discordapp-com-is-now-Discord-com).
- #### What does your PR fix?  
N/A

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
As per the configuration file, all 3 are supported.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
No, since this only fixes plain-text files.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**
N/A

2021-09-15 06:17 UTC, NancyLi1013 requested changes

2021-09-15 06:17 UTC, NancyLi1013 commented on ports/discord-game-sdk/vcpkg.json
>    "port-version": 2,
```suggestion
  "version": "2.5.6",
  "port-version": 3,
```
This might be `version `here.

2021-09-15 06:19 UTC, NancyLi1013 commented
Please run `vcpkg x-add-version discord-game-sdk` to update version files after you address the review suggestions.

2021-09-15 11:18 UTC, J-Human commented on ports/discord-game-sdk/vcpkg.json
>    "port-version": 2,
Addressed.

2021-09-15 11:19 UTC, J-Human commented
> Please run `vcpkg x-add-version discord-game-sdk` to update version files after you address the review suggestions.

Done, it has been committed.

2021-09-16 06:26 UTC, NancyLi1013 requested changes

2021-09-16 06:26 UTC, NancyLi1013 commented on versions/d-/discord-game-sdk.json
> +      "git-tree": "1e36656365b603448365695d858cf2eaf3aff0bd",
This is not correct. We should not change the content in the last version. Adding a new item for the new version changes is right action.

2021-09-16 11:25 UTC, J-Human commented on versions/d-/discord-game-sdk.json
> +      "git-tree": "1e36656365b603448365695d858cf2eaf3aff0bd",
I think I fixed it, please check. Thanks!

2021-09-17 03:10 UTC, NancyLi1013 commented on versions/d-/discord-game-sdk.json
> +      "git-tree": "1e36656365b603448365695d858cf2eaf3aff0bd",
```suggestion
```
This should be removed. You add this twice. Every PR only has one item for the changes.

2021-09-17 05:43 UTC, NancyLi1013 approved these changes

2021-09-17 15:03 UTC, merged

2021-09-17 15:03 UTC, BillyONeal commented
Looks good, thank you!