[tomlplusplus] Update to 2.5.0
microsoft/vcpkg pull request #20164
Opened 2021-09-15 01:53 UTC by Qudix

**Describe the pull request**

- #### What does your PR fix?  
  Updates tomlplusplus to 2.5.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Just an update

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-09-15 05:42 UTC, PhoebeHui commented on ports/tomlplusplus/vcpkg.json
> +  "version-string": "2.5.0",
```suggestion
  "version": "2.5.0",
```

2021-09-15 05:43 UTC, PhoebeHui requested changes
@Qudix, thanks for the PR!

Could you address the review suggestion?

2021-09-15 06:24 UTC, Qudix commented
I'm not sure what's wrong with CI, seems unrelated?

2021-09-15 06:30 UTC, PhoebeHui commented
The CI failed with the following failure, It looks relate to https://github.com/microsoft/vcpkg/pull/20140

@BillyONeal, do you know how to find the 2 unexpected failures port?

eg: x86-windows:
```
Expected 28 cascaded failures, but there were 31 cascaded failures.
##[error]vcpkg ci failed
At C:\a\1\s\scripts\azure-pipelines\test-modified-ports.ps1:174 char:5
+     throw "vcpkg ci failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (vcpkg ci failed:String) [], RuntimeException
+ FullyQualifiedErrorId : vcpkg ci failed
##[error]PowerShell exited with code '1'.
```

2021-09-15 07:25 UTC, PhoebeHui commented
```
x86-windows:                   Expected 28 cascaded failures, but there were 31 cascaded failures.
x64-windows:                   Expected 21 cascaded failures, but there were 24 cascaded failures.
x64-windows-static:            Expected 59 cascaded failures, but there were 62 cascaded failures.
x64-windows-static-md:         Expected 53 cascaded failures, but there were 56 cascaded failures.
x64-uwp:                       Expected 345 cascaded failures, but there were 342 cascaded failures.
arm64-windows:                 Expected 228 cascaded failures, but there were 226 cascaded failures.
arm-uwp:                       Expected 345 cascaded failures, but there were 343 cascaded failures.
x64-osx:                       Pass
x64-linux:                     Pass
```

2021-09-15 18:54 UTC, BillyONeal commented
>@BillyONeal, do you know how to find the 2 unexpected failures port?

It was just a count lock, not a per-port lock. We backed out the check entirely.

2021-09-16 00:21 UTC, PhoebeHui approved these changes

2021-09-16 00:49 UTC, merged

2021-09-16 00:49 UTC, BillyONeal commented
Thanks for your update!