Update ned14-internal-quickcpplib and LLFIO to latest matching Outcome v2.2.1 (bugfixed) release.
microsoft/vcpkg pull request #20171
Opened 2021-09-15 10:41 UTC by ned14

**Describe the pull request**

- #### What does your PR fix?  

Update ned14-internal-quickcpplib and LLFIO to latest matching Outcome v2.2.1 (bugfixed) release.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]

All the same as before.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes

2021-09-15 11:00 UTC, ned14 commented
Looks like "Test Modified Ports and Prepare Test Logs" is failing for the Windows targets. Obviously this is new since I last submitted a version bump.

Do I need to add something about test status to some file in the commit or something?

2021-09-15 21:22 UTC, BillyONeal commented
> Looks like "Test Modified Ports and Prepare Test Logs" is failing for the Windows targets. Obviously this is new since I last submitted a version bump.

We added an overzealous check, I removed the check and pushed a merge with master for you.

2021-09-15 21:23 UTC, BillyONeal commented
/azp run

2021-09-16 01:11 UTC, PhoebeHui requested changes
@ned14, thanks for the PR! Could you address the review suggestions?

2021-09-16 01:11 UTC, PhoebeHui commented on ports/llfio/vcpkg.json
> +  "port-version": 20210915,
```suggestion
```

2021-09-16 01:11 UTC, PhoebeHui commented on ports/llfio/vcpkg.json
>    "version-string": "2.0",
```suggestion
  "version-string": "2.0-ac83bef",
```

2021-09-22 02:59 UTC, PhoebeHui approved these changes

2021-09-22 08:38 UTC, ned14 commented
Can you not merge this as is please? One of the reasons I'm late getting back to this PR is because a showstopper memory corruption bug was present in this edition of LLFIO. Everything needs bumped to latest versions. I'll try to find time to do it soon.

2021-09-22 11:16 UTC, ned14 commented
Ok moved to latest everything, fixed suggested items from review.

2021-09-24 00:42 UTC, BillyONeal commented
> Can you not merge this as is please? One of the reasons I'm late getting back to this PR is because a showstopper memory corruption bug was present in this edition of LLFIO. Everything needs bumped to latest versions. I'll try to find time to do it soon.

You can also just close the PR whenever that happens and reopen later :)

2021-09-24 08:23 UTC, PhoebeHui approved these changes
Thanks for the updates

2021-09-24 17:53 UTC, BillyONeal commented
> It's kinda hard to know what the expected process semantics are for PRs across different orgs. Some get real arsey if you close and open PRs. Or open PRs at all without a preceding issue. Even here in vcpkg I've noticed quite a lot of change in the past year in terms of vibe and process. Probably your influence Billy :)

I hope you're getting a good experience contributing :)

> Re: this one change requested above, I don't understand it. Didn't I already update the versions last commit I did? If I did it wrong, I'll need instruction on how to do it better, I merged latest master, readded versions, commit. I don't know what else I am supposed to do.

The version database should have only 1 new version entry added per port per PR; this change removes an entry:

![image](https://user-images.githubusercontent.com/1544943/134719215-b12ef2ee-7a19-4311-9f08-301011e64f17.png)

 and adds multiple entries:

![image](https://user-images.githubusercontent.com/1544943/134719260-b4216663-1d96-4557-a827-ba4dbdb73709.png)

A good way to fix this is to (1) merge with origin/master, (2) `git checkout origin/master -- versions`, then rerun any commands to touch the version database. I'm just going to fix this one for you though....

2021-09-24 17:57 UTC, BillyONeal approved these changes
Will land as soon as build comes back.

2021-09-27 13:41 UTC, ned14 commented
> The version database should have only 1 new version entry added per port per PR; this change removes an entry:

That was intentional.

> and adds multiple entries:

That was not. I wanted only the one with port-version: 0, but obviously vcpkg readded in the other one.

2021-09-27 19:42 UTC, BillyONeal commented
> > The version database should have only 1 new version entry added per port per PR; this change removes an entry:
> 
> That was intentional.

Version entries can never be removed.

> > and adds multiple entries:
> 
> That was not. I wanted only the one with port-version: 0, but obviously vcpkg readded in the other one.

Your `vcpkg.json` has `port-version: 1` so it kept trying to add that one.

2021-09-27 19:42 UTC, merged

2021-09-27 19:42 UTC, BillyONeal commented
Thanks for the version updates!