[think-cell-range] Adding think-cell's range library
microsoft/vcpkg pull request #202
Opened 2016-10-22 19:40 UTC by frederich

https://www.think-cell.com/en/career/talks/ranges/#1

Signed-off-by: Jens Frederich <jfrederich@gmail.com>

2016-10-22 19:40 UTC, msftclas commented
Hi __@frederich__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, MSBOT;

2016-10-22 20:16 UTC, frederich commented
Note, there is a boost patch (boost_patches/has_range_iterator.patch) This is equivalent to @treh's https://github.com/boostorg/range/pull/40 (accepted, but not merged into the release yet).

2016-10-24 19:09 UTC, Orvid requested changes

2016-10-24 19:09 UTC, Orvid commented on ports/think-cell-range/portfile.cmake
> +    PATCHES "${SOURCE_PATH}/boost_patches/has_range_iterator.patch"
Ekk.... If we want to apply a patch to boost it probably needs to be done in the Boost portfile, otherwise we risk the binaries being out of date. This will also get obliterated if someone re-installs boost without re-installing this package.

2016-10-24 21:37 UTC, frederich commented on ports/think-cell-range/portfile.cmake
> +    PATCHES "${SOURCE_PATH}/boost_patches/has_range_iterator.patch"
@ras0219-msft, no it's not shipped with 1.62. The patch is still required. Look at the official 1.62 download package.

2016-10-24 21:41 UTC, ras0219-msft commented on ports/think-cell-range/portfile.cmake
> +    PATCHES "${SOURCE_PATH}/boost_patches/has_range_iterator.patch"
I stand corrected. Somehow, even though this was resolved a year ago, it wasn't included in the release a month ago. In this case, Orvid's observation will need to be addressed before I can merge this.

2016-10-24 21:56 UTC, frederich commented on ports/think-cell-range/portfile.cmake
> +    PATCHES "${SOURCE_PATH}/boost_patches/has_range_iterator.patch"
Okay, but the patch resists in the think-cell repo. One solution is to add the patch to the boost ports folder and apply; another is to download the think-cell package while boost installation is in progress and cherry-pick the patch. What's your choice?

2016-10-24 22:39 UTC, Orvid commented on ports/think-cell-range/portfile.cmake
> +    PATCHES "${SOURCE_PATH}/boost_patches/has_range_iterator.patch"
Fetch and apply the commit directly instead:
https://github.com/boostorg/range/commit/e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff

2016-10-25 00:11 UTC, ras0219-msft commented on ports/think-cell-range/portfile.cmake
> +    PATCHES "${SOURCE_PATH}/boost_patches/has_range_iterator.patch"
Make sure to bump the boost version to `1.62-1` to signal that it has been modified.

2016-10-27 06:04 UTC, frederich commented
@ras0219-msft ping

2016-10-27 21:45 UTC, merged

2016-10-27 21:47 UTC, ras0219-msft commented
Thanks for this pull request!

I needed to modify the "fix-the-patch" code to not overwrite in place, because otherwise future installs would fail because the patch did not match the expected SHA. It is now generated into `buildtrees\` near the sources.