Update rbdl-orb port to rbdl-orb version 3.1.2
microsoft/vcpkg pull request #20305
Opened 2021-09-23 12:20 UTC by ju6ge

This PR, updates the rbdl-orb port to version 3.1.2. 

What is new:
- adds FindRBDL.cmake files
- updates to the URDF Parser library

2021-09-24 03:03 UTC, JonLiu1993 requested changes

2021-09-24 03:03 UTC, JonLiu1993 commented on ports/rbdl-orb/vcpkg.json
> +  "port-version": 2,
```suggestion
```

2021-09-24 09:36 UTC, JonLiu1993 approved these changes

2021-09-29 16:03 UTC, BillyONeal requested changes

2021-09-29 16:03 UTC, BillyONeal commented on versions/r-/rbdl-orb.json
> +    },
```suggestion
```

Deleting this nonexistent version from the database will allow us to merge this. I tried to do it for you but the PR was created without permissions for maintainers to fix.

2021-09-29 16:09 UTC, ju6ge commented on versions/r-/rbdl-orb.json
> +    },
sry next time i will allow maintainer edits ;)

2021-09-29 16:34 UTC, BillyONeal commented on versions/r-/rbdl-orb.json
> +    {
I'm not sure what happened here. The way I normally fix this is something like:

```
git fetch origin #assuming that microsoft/vcpkg is called origin
git merge origin/master
git checkout origin/master -- versions # this removes all edits to the version database
vcpkg x-add-version rbdl-orb
git commit -am "Update version database"
git push
```

2021-09-30 00:55 UTC, PhoebeHui commented on versions/r-/rbdl-orb.json
> +    {
There has extra '{' here.☺

2021-09-30 00:58 UTC, PhoebeHui commented on versions/r-/rbdl-orb.json
> +    {
I have no permission to push the changes to this PR, @ju6ge, could you fix this issue?

2021-09-30 00:58 UTC, PhoebeHui commented on versions/r-/rbdl-orb.json
> +    {
```suggestion
```

2021-09-30 00:59 UTC, ju6ge commented on versions/r-/rbdl-orb.json
> +    {
sure ;)

2021-09-30 01:03 UTC, PhoebeHui approved these changes
Thanks for your quick fix!

2021-09-30 01:06 UTC, merged