[scripts-audit] QMake buildsystem
microsoft/vcpkg pull request #20322
Opened 2021-09-24 09:33 UTC by JackBoosY

2021-09-24 10:01 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_qmake.cmake
> +    set(triplet_hostbindir "${CURRENT_INSTALLED_DIR}/tools/qt5/bin")
```suggestion
    set(triplet_hostbindir "${CURRENT_HOST_INSTALLED_DIR}/tools/qt5/bin")
```

2021-09-24 10:02 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_qmake.cmake
>      endif()
Remove `if()` since host tools are a thing now this is no longer necessary.

2021-09-24 10:10 UTC, dg0yt reviewed
Just when I submitted a PR touching one of these files...

2021-09-24 10:10 UTC, dg0yt commented on scripts/cmake/vcpkg_configure_qmake.cmake
> +        "OPTIONS;OPTIONS_RELEASE;OPTIONS_DEBUG;BUILD_OPTIONS;BUILD_OPTIONS_RELEASE;BUILD_OPTIONS_DEBUG"
`BUILD_OPTIONS`, `BUILD_OPTIONS_RELEASE` and `BUILD_OPTIONS_DEBUG` don't have documenation. It is not obvious how they differ from `OPTIONS` etc.

2021-09-26 07:59 UTC, JackBoosY commented on scripts/cmake/vcpkg_build_qmake.cmake
>          if (VCPKG_QMAKE_USE_NMAKE)
I also didn't find this, @Neumann-A should I remove the related code?

2021-09-26 08:25 UTC, Neumann-A commented on scripts/cmake/vcpkg_build_qmake.cmake
>          if (VCPKG_QMAKE_USE_NMAKE)
> Is this variable documented?

No. It is only meant to be set by people for which jom acts up.

> @Neumann-A should I remove the related code?

No. It was introduced for people who have problems with jom. This happens rarely but it happens.

2021-09-26 08:42 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_qmake.cmake
> +    set(triplet_hostbindir "${CURRENT_INSTALLED_DIR}/tools/qt5/bin")
@Neumann-A The pipeline test results shows that this changes will requires all the qt component ports depend on host `qt5-base[core]`, should we do that?

2021-09-26 08:49 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_qmake.cmake
> +    set(triplet_hostbindir "${CURRENT_INSTALLED_DIR}/tools/qt5/bin")
qt5-base needs a host dependency on itself. Just like qtbase

2021-09-27 10:02 UTC, JackBoosY commented on scripts/cmake/vcpkg_install_qmake.cmake
> +        file(COPY ${release_libs} DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
`release_libs` cannot use double quotes because it may be a list.

2021-09-28 23:42 UTC, strega-nil-ms requested changes
started reviewing :)

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
>              set(ENV{PATH} "$ENV{PATH};${NMAKE_EXE_PATH}")
This should be switched to use `vcpkg_host_path_list`.

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +            get_filename_component(NMAKE_EXE_PATH "${nmake_executable}" DIRECTORY)
```suggestion
            get_filename_component(nmake_exe_path "${nmake_executable}" DIRECTORY)
```

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
>      endif()
This if-else block should be moved below the `env_path_backup` and `env_cl_backup`.

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
>      endif()
```suggestion
    set(short_name_debug "dbg")
    set(path_suffix_debug "/debug")
    set(targets_debug "${arg_DEBUG_TARGETS}")
```

We can simplify this quite a bit (and same below)

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +    foreach(build_type IN LISTS buildtypes)
```suggestion
    foreach(build_type IN ITEMS debug release)
        if(DEFINED VCPKG_BUILD_TYPE AND NOT "${VCPKG_BUILD_TYPE}" STREQUAL "${build_type}")
            continue()
        endif()
```

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +        vcpkg_add_to_path(PREPEND "${current_installed_prefix}/lib")
```suggestion
        vcpkg_add_to_path(PREPEND "${current_installed_prefix}/lib" "${current_installed_prefix}/bin")
```

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +                set(ld_library_path_backup $ENV{LD_LIBRARY_PATH})
it's easy to just write something more like:

```cmake
    if(DEFINED ENV{LD_LIBRARY_PATH})
        set(ld_library_path_backup "$ENV{LD_LIBRARY_PATH}")
        ...
    else()
        unset(ld_library_path_backup)
    endif()
```

and then check for `if(DEFINED ld_library_path_backup)`

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +        vcpkg_list(APPEND arg_${build_type}_TARGETS ${arg_TARGETS})
```suggestion
        vcpkg_list(SET targets ${targets_${build_type}} ${arg_TARGETS})
```

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +            z_run_jom_build(qmake_all makefiles ${short_name_${build_type}})
```suggestion
            z_run_jom_build(qmake_all makefiles "${short_name_${build_type}}")
```

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +        z_run_jom_build("${arg_${build_type}_TARGETS}" ${arg_BUILD_LOGNAME} ${short_name_${build_type}})
```suggestion
        z_run_jom_build("${targets}" "${arg_BUILD_LOGNAME}" "${short_name_${build_type}}")
```

2021-09-28 23:42 UTC, strega-nil-ms commented on scripts/cmake/vcpkg_build_qmake.cmake
> +            if(is_ld_library_path_defined)
```suggestion
            if(DEFINED ld_library_path_backup)
```

2021-09-29 06:50 UTC, dg0yt commented on docs/maintainers/vcpkg_configure_qmake.md
> +The options passed to qmake to the build step.
This may have been the intention by name, but does it make sense for qmake? There is no "build step" in `vcpkg_configure_qmake` and also no documented effect of `--` in https://doc.qt.io/qt-5/qmake-manual.html.
CC @Neumann-A

2021-09-29 09:34 UTC, JackBoosY commented on scripts/cmake/vcpkg_build_qmake.cmake
> +                endforeach()
Same with https://github.com/microsoft/vcpkg/pull/20165#discussion_r718325877:
Since `current_installed_libpath` and `ld_library_path_backup` already contain host separator, we can't pass it into environment variables using `vcpkg_host_path_list `directly.

2021-09-29 09:34 UTC, JackBoosY commented on scripts/cmake/vcpkg_build_qmake.cmake
> +                endforeach()
Same as above.

2021-09-29 09:48 UTC, Neumann-A commented on docs/maintainers/vcpkg_configure_qmake.md
> +The options passed to qmake to the build step.
It just means non parametric options after the `--` . `BUILD_OPTIONS` might be the wrong name here and it was a bit influenced by qt5-base bootstrap script where it is needed to pass other variables to the next build/configure step. `BUILD_OPTIONS` is used in in e.g. qt5-webengine.

2021-10-20 21:39 UTC, strega-nil-ms requested changes
some stuff to change :)

2021-10-21 04:49 UTC, Neumann-A commented
@Osyotr neither respect the cmake toolchain. Qt5-base runs a bootstrap script and the flags are not passed and the rest uses the script here

2021-10-26 23:08 UTC, strega-nil-ms reviewed
Continue marking changes to make

2021-11-03 08:00 UTC, JackBoosY commented on scripts/cmake/vcpkg_build_qmake.cmake
> +function(z_run_jom_build targets log_prefix log_suffix)
Since this function has the prefix `z_`, it will only be used in this file, so I think this is also acceptable.
`invoke_command` is not a tool, so I think it should be lowercase.

2021-11-03 08:59 UTC, dg0yt commented on scripts/cmake/vcpkg_build_qmake.cmake
> +function(z_run_jom_build targets log_prefix log_suffix)
`z_run_jom_build` is exposed in the stack trace on port build failures. In this situation, it is inviting to be misunderstood as "Oh no, `jom` is wrong on POSIX, vcpkg [!] broke my port again."

I know `invoke_command` is a variable. I complain that it is passed to `z_run_jom_build` by context, not as a proper formal parameter. Ideally, a function depends only on its input parameters, and has no side effects.

2021-11-05 17:58 UTC, strega-nil-ms approved these changes

2021-11-05 23:55 UTC, merged