[z3] Update to 4.8.12
microsoft/vcpkg pull request #20348
Opened 2021-09-26 00:52 UTC by chausner

**Describe the pull request**

- #### What does your PR fix?  
  Updates z3 to 4.8.12

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-09-26 03:04 UTC, NancyLi1013 requested changes

2021-09-26 03:04 UTC, NancyLi1013 commented on ports/z3/vcpkg.json
> +  "version-semver": "4.8.12",
```suggestion
  "version-string": "4.8.12",
```
This might be `version-string` instead of `version-semver`. Since it also has the prefix 'z3-' for the version.Please refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md).

2021-09-26 12:12 UTC, chausner commented on ports/z3/vcpkg.json
> +  "version-semver": "4.8.12",
Judging by https://github.com/Z3Prover/z3/blob/master/RELEASE_NOTES, I agree that z3 does not seem to follow semver. But shouldn't we switch to `version` instead of `version-string`? After all, the version is still `4.8.12` and not `z3-4.8.12`.

2021-09-27 08:50 UTC, NancyLi1013 commented on ports/z3/vcpkg.json
> +  "version-semver": "4.8.12",
Thanks for your details. Seems `version `is more proper here.

2021-09-27 19:12 UTC, chausner commented on ports/z3/vcpkg.json
> +  "version-semver": "4.8.12",
I switched to `version`.

2021-09-28 00:00 UTC, NancyLi1013 approved these changes

2021-09-28 00:00 UTC, NancyLi1013 commented
LGTM, thanks for your update. @chausner

2021-09-28 03:51 UTC, merged

2021-09-28 03:52 UTC, BillyONeal commented
Thanks for the update!