[glog] Update to 0.5.0
microsoft/vcpkg pull request #20351
Opened 2021-09-26 01:30 UTC by chausner

**Describe the pull request**

- #### What does your PR fix?  
  Updates glog to 0.5.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

2021-09-26 06:19 UTC, JonLiu1993 requested changes

2021-09-26 06:19 UTC, JonLiu1993 commented on ports/glog/vcpkg.json
> +  "version-string": "0.5.0",
```suggestion
  "version": "0.5.0",
```

2021-09-26 06:20 UTC, JonLiu1993 commented
@chausner ,Thanks for your pr,this is error log:
https://dev.azure.com/vcpkg/public/_build/results?buildId=60211&view=artifacts&pathAsName=false&type=publishedArtifacts

2021-09-28 22:29 UTC, chausner commented
This currently breaks several dependent packages. I also think there is a bug in glog 0.5.0 which I reported at https://github.com/google/glog/issues/715 and tried to workaround with `glog_fix_os_defines.patch` but it appears there are more issues..

2021-12-10 07:52 UTC, JonLiu1993 commented
@chausner, any progress?

2021-12-10 18:40 UTC, chausner commented
> @chausner, any progress?

No, I'll close this PR.

2021-12-10 18:40 UTC, closed without merging