[sleepy-discord] fix [core] build
microsoft/vcpkg pull request #20372
Opened 2021-09-26 22:21 UTC by autoantwort

2021-09-27 00:59 UTC, PhoebeHui requested changes
Thanks for the PR!

2021-09-27 00:59 UTC, PhoebeHui commented on ports/sleepy-discord/portfile.cmake
> +        -DUSE_BOOST_ASIO=ON
it looks USE_BOOST_ASIO is OFF by default, and enabled when use USE_UWEBSOCKETS and USE_WEBSOCKETPP, see https://github.com/yourWaifu/sleepy-discord/blob/develop/CMakeLists.txt#L35.

2021-09-27 00:59 UTC, PhoebeHui commented on ports/sleepy-discord/portfile.cmake
> -        "websocketpp"    USE_BOOST_ASIO
The origin change looks correct.

2021-09-27 01:11 UTC, autoantwort commented
> Thanks for the PR! what issue does this PR fix?

As the title states, the `sleepy-discord[core]` build

2021-09-27 01:12 UTC, autoantwort commented on ports/sleepy-discord/portfile.cmake
> +        -DUSE_BOOST_ASIO=ON
Yeah but when you not use `USE_UWEBSOCKETS` or `USE_WEBSOCKETPP`, it falls back to asio. It at least tries to include the asio headers and then fails

2021-09-27 03:15 UTC, PhoebeHui commented on ports/sleepy-discord/portfile.cmake
> +        -DUSE_BOOST_ASIO=ON
How it falls back to asio, USE_ASIO is OFF by default too, and it enabled when use USE_WEBSOCKETPP and USE_UWEBSOCKETS.

2021-09-27 08:52 UTC, autoantwort commented on ports/sleepy-discord/portfile.cmake
> +        -DUSE_BOOST_ASIO=ON
Yeah it falls back to USE_BOOST_ASIO because that is used anyway if you use the feature websocketpp. Alternatively we can remove the feature `websocketpp` and make this feature the default

2021-09-27 23:56 UTC, BillyONeal commented
Indeed, upstream always assumes that it can use asio, https://github.com/yourWaifu/sleepy-discord/blob/0f090ffc883dd7f0212969c5bed9c2b1699b2a38/sleepy_discord/CMakeLists.txt#L2 adds `asio_udp` unconditionally.

2021-09-29 06:31 UTC, PhoebeHui approved these changes

2021-09-29 15:35 UTC, merged

2021-09-29 15:35 UTC, BillyONeal commented
Thanks again!