[pegtl] Update to 3.2.1
microsoft/vcpkg pull request #20400
Opened 2021-09-28 00:00 UTC by chausner

**Describe the pull request**

- #### What does your PR fix?  
  Updates pegtl to 3.2.1

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

2021-09-28 00:00 UTC, chausner commented on ports/pegtl/vcpkg.json
> +  "version-semver": "3.2.1",
Follows semver according to https://github.com/taocpp/PEGTL#status.

2021-09-28 02:44 UTC, JonLiu1993 approved these changes

2021-09-29 02:38 UTC, NancyLi1013 requested changes

2021-09-29 02:38 UTC, NancyLi1013 commented on ports/pegtl/portfile.cmake
> +
```suggestion
```

2021-09-29 02:50 UTC, NancyLi1013 requested changes

2021-09-29 02:50 UTC, NancyLi1013 commented on versions/p-/pegtl.json
> +      "git-tree": "9f1940d2f2fe494042528d38159260879648f16b",
```suggestion
      "git-tree": "4a95202decfce79a39190525dea1c3a135bf393f",
```

2021-09-29 03:07 UTC, NancyLi1013 approved these changes

2021-09-29 15:39 UTC, BillyONeal commented
Thanks for the update and semver research!

2021-09-29 15:39 UTC, merged