[hypodermic] added version 2.5.3, updated baseline
microsoft/vcpkg pull request #20414
Opened 2021-09-28 19:16 UTC by lerppana

**Describe the pull request**

- #### What does your PR fix?  
This PR adds new version 2.5.3, which contains bug fix for nested containers

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
I have tested new version with windows and macOS. 
I updated baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
I believe so. I only added new version.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

2021-09-29 02:21 UTC, NancyLi1013 requested changes

2021-09-29 02:21 UTC, NancyLi1013 commented on ports/hypodermic/portfile.cmake
>          "disable_hypodermic_tests.patch"
Could you please handle license like this?
`file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)`

Please also add quotes for other paths. Please see  https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/cmake-guidelines.md.

2021-09-29 09:24 UTC, lerppana commented on ports/hypodermic/portfile.cmake
>          "disable_hypodermic_tests.patch"
is this better?

2021-09-30 05:48 UTC, NancyLi1013 commented on ports/hypodermic/portfile.cmake
>          "disable_hypodermic_tests.patch"
Yes, it it good now.

2021-09-30 05:50 UTC, NancyLi1013 approved these changes

2021-09-30 21:02 UTC, BillyONeal commented
I couldn't find documentation suggesting that hypodermic follows semver so I changed to "version".

2021-09-30 21:03 UTC, BillyONeal approved these changes
Will merge as soon as build comes back.

2021-09-30 22:45 UTC, merged

2021-09-30 22:45 UTC, BillyONeal commented
Thanks for the update!