[gnupg and deps] Fix arm64-osx compilation, other fixes
microsoft/vcpkg pull request #20433
Opened 2021-09-29 16:28 UTC by wrobelda

**Describe the pull request**  

- #### What does your PR fix?  
  - fixes libgcrypt macOS arm64 compilation

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No change, plus:
  - added libgcrypt `arm64-osx`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
    I am still working on this PR

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
   I am still working on this PR

2021-09-30 06:18 UTC, wrobelda commented
@JackBoosY this is WIP, I already added Windows support to the port since creating this issue, so this isn't a "community-triplet" exclusively.

2021-10-06 17:55 UTC, wrobelda commented
@JackBoosY, @PhoebeHu, FYI,i this is ready for a review since a while.

2021-10-08 02:10 UTC, JackBoosY requested changes

2021-10-08 03:07 UTC, JackBoosY requested changes

2021-10-08 05:56 UTC, JackBoosY requested changes

2021-10-13 09:13 UTC, closed without merging