[gRPC] update to v1.41.0
microsoft/vcpkg pull request #20835
Opened 2021-10-19 03:10 UTC by JonLiu1993

Fix #19511

Update grpc to the latest version 1.41.0

All feature are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2021-10-20 02:19 UTC, NancyLi1013 requested changes

2021-10-20 06:13 UTC, JonLiu1993 commented
/azp run

2021-10-21 07:04 UTC, JonLiu1993 commented
/azp run

2021-10-21 10:21 UTC, JonLiu1993 commented
/azp run

2021-10-22 05:57 UTC, NancyLi1013 approved these changes

2021-11-02 08:27 UTC, NancyLi1013 approved these changes

2021-11-04 04:40 UTC, BillyONeal commented
@jozefizso @youknowone @coryan Can you take a look at this and comment?

2021-11-04 04:40 UTC, BillyONeal commented on ports/grpc/00014-pkgconfig-upbdefs.patch
>  +  "-lgrpc -lgrpc_upbdefs -laddress_sorting -lre2 -lupb_fastdecode -lupb_json -lupb_pb -lupb_handlers -lupb_textformat -lupb_reflection -lupb -lcares -lz -labsl_statusor -labsl_status -labsl_raw_hash
This doesn't seem quite right to me. In the old version, we patched that big list of libraries to link. In the new version, upstream no longer has that big list of libraries to link, instead deferring to dependencies pkgconfig files (if I understand what's going on correctly). But we're still adding in all those extra -l flags that are no longer present in upstream. I think the effects of these "upb" changes need to be redone in light of how upstream works now.

2021-11-04 04:41 UTC, BillyONeal commented
Related: https://github.com/microsoft/vcpkg/pull/17422#issuecomment-824447090

2021-11-04 11:15 UTC, coryan commented on ports/grpc/00014-pkgconfig-upbdefs.patch
>  +  "-lgrpc -lgrpc_upbdefs -laddress_sorting -lre2 -lupb_fastdecode -lupb_json -lupb_pb -lupb_handlers -lupb_textformat -lupb_reflection -lupb -lcares -lz -labsl_statusor -labsl_status -labsl_raw_hash
Assuming the Abseil package in `vcpkg` installs its pkg-config files correctly, then yes, there should be no need for the additional `-labsl_*` options.  The list of `absl_*` pkg-config modules should do the trick, and that is  how the Abseil and gRPC teams want this thing to work (there can be bugs, of course).

2021-11-11 02:30 UTC, NancyLi1013 approved these changes

2021-11-11 19:34 UTC, merged