[qwt-qt6] new port
microsoft/vcpkg pull request #20921
Opened 2021-10-22 05:42 UTC by MehdiChinoune

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #20836 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-10-22 05:47 UTC, JackBoosY requested changes

2021-10-22 05:47 UTC, JackBoosY requested changes

2021-11-23 03:49 UTC, MehdiChinoune commented
Waiting for #20963
I took too long!

2021-11-24 05:07 UTC, JackBoosY commented
Now you can continue your work.

2021-11-24 05:09 UTC, MehdiChinoune commented
@JackBoosY Please take a look, It should be ready now.

2021-11-24 05:11 UTC, JackBoosY requested changes

2021-11-24 05:11 UTC, JackBoosY commented on ports/qwt-qt5/rename-library-to-qwt-qt5.patch
> +diff --git a/qwt.prf b/qwt.prf
Renaming the library is inappropriate in our policy.
For those conflicting ports, we should choose the not commonly used one in ci.baseline.txt to skip it.

2021-11-24 05:42 UTC, MehdiChinoune commented on ports/qwt-qt5/rename-library-to-qwt-qt5.patch
> +diff --git a/qwt.prf b/qwt.prf
> Renaming the library is inappropriate in our policy. For those conflicting ports, we should choose the not commonly used one in ci.baseline.txt to skip it.

I have not understand well, Could explain more. I mean how to mark them conflicting (or avoid them to be installed at the same time)

2021-11-24 05:49 UTC, JackBoosY commented on ports/qwt-qt5/rename-library-to-qwt-qt5.patch
> +diff --git a/qwt.prf b/qwt.prf
For example: opencv2, opencv3 and opencv4.
You can find 2 and 3 in _scripts/ci.baseline.txt_.
As @cenit said, one of them should be marked `skip` in all official triplets to avoid conflicts.

2021-11-24 06:27 UTC, JackBoosY requested changes

2021-11-24 06:27 UTC, JackBoosY commented on ports/qwtw/vcpkg.json
> +    "qwt-qt5"
This will cause qwtw to always use qt5 instead of qt. Can you confirm that?

2021-11-24 06:33 UTC, MehdiChinoune commented on ports/qwtw/vcpkg.json
> +    "qwt-qt5"
I couldn't confirm. I did a look at the project and I didn't find any changes related to qt6.
I will revert the changes. (I think it failed the last time!)

2021-11-24 06:35 UTC, MehdiChinoune commented on ports/qwtw/vcpkg.json
> +    "qwt-qt5"
Well if we want to build it against qwt then we should also move to change other dependencies to qt6-base, qt6-networkauth and qt6-svg.

2021-11-24 08:59 UTC, JackBoosY commented on ports/qwtw/vcpkg.json
> +    "qwt-qt5"
qt6 is named `qt` in vcpkg now.

2021-11-24 09:07 UTC, MehdiChinoune commented on ports/qwtw/vcpkg.json
> +    "qwt-qt5"
I know, qt5-base, qt5-svg and qt5-networkauth should be changed to qt-base, qt-svg and qt-networkauth. Which means another move into qt6 which means I have to add another port qwtw-qt5. but this is about moving qwt to qt6.

2021-11-24 09:11 UTC, JackBoosY commented on ports/qwtw/vcpkg.json
> +    "qwt-qt5"
For this question, you should ask @Neumann-A .

2021-11-24 09:31 UTC, cenit commented
for qtkeychain it was decided that it had to remain with qt5 and a new one has to be created for qt6
see https://github.com/microsoft/vcpkg/pull/20185

2021-11-24 09:48 UTC, MehdiChinoune commented
> for qtkeychain it was decided that it had to remain with qt5 and a new one has to be created for qt6 see #20185

@JackBoosY Do you agree with that?

2021-11-24 09:52 UTC, JackBoosY commented
> for qtkeychain it was decided that it had to remain with qt5 and a new one has to be created for qt6 see #20185

Therefore, should we also create a new port `qwtw-qt5` to move all the files into that and suitable `qwtw` with qt6 in this PR?

2021-11-24 10:15 UTC, cenit commented
> > for qtkeychain it was decided that it had to remain with qt5 and a new one has to be created for qt6 see #20185
> 
> Therefore, should we also create a new port `qwtw-qt5` to move all the files into that and suitable `qwtw` with qt6 in this PR?

on the contrary, qwtw has to remain with qt5 and a new port qwtw-qt6 will point to qt6

2021-11-24 10:16 UTC, cenit commented
ask @ras0219-msft for more info if you have any doubt. I hope consistency will be kept and same rule will be enforced here...

2021-11-25 07:17 UTC, JackBoosY requested changes

2021-11-25 07:17 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +qwt-qt6:x64-osx=fail
Is qwt-qt6 doesn't support osx or there are some issues about configure/build step?

2021-11-25 07:26 UTC, MehdiChinoune commented on scripts/ci.baseline.txt
> +qwt-qt6:x64-osx=fail
qwt supports macos, but unfortunately it fails like qwt (qwt-qt5).
I don't know why as I don't use macos.

2021-11-25 08:38 UTC, JackBoosY approved these changes

2021-11-26 09:45 UTC, BillyONeal commented on scripts/ci.baseline.txt
> +qwt-qt6:x64-osx=fail
I'm testing on a mac now...

2021-11-26 11:26 UTC, BillyONeal commented
The osx failure is:

```
make[1]: *** No rule to make target `/Users/bion/vcpkg/installed/x64-osx/debug/lib/libQt6OpenGLWidgets.a', needed by `../lib/libqwt.6.2.0.dylib'.  Stop.
make: *** [sub-src-all-ordered] Error 2
```

I observe there is no `libQt6OpenGLWidgets.a` but there is `installed/x64-osx/debug/lib/libQt6OpenGLWidgets_debug.a` Is that ringing any bells in terms of obvious mixups?

2021-11-26 11:38 UTC, Neumann-A commented
>  Is that ringing any bells in terms of obvious mixups?

looks like it is setup the wrong way. Maybe the PRL file for libQt6OpenGLWidgets is wrong?

2021-11-26 16:22 UTC, MehdiChinoune commented
I think the macos failure is not from the qwt side. So could you please merge this PR and resolve/resolve the issue in another PR.

2021-11-27 06:09 UTC, BillyONeal commented
The reason I’m trying to run this down is that we generally try to avoid adding new ci.baseline.txt entries unless we are doing a major bulk add (e.g. turning on a new platform or triplet) or have some understanding as to why our infrastructure can’t test a particular port.

That said, that desire isn’t absolute; I want to make sure an attempt has been made to avoid adding that entry, but it isn’t the end of the world if not.

You said you expect the build system here is reading “PRL” files?

2021-11-29 14:10 UTC, MehdiChinoune commented
Another issue!
I should wait for another 2-4 weeks to be fixed by another PR, and then I have to rebase my changes which will maybe lead to the discovery of another issue, and so on...

2021-11-30 02:09 UTC, JackBoosY commented
Please ping me if you continue this PR.

2021-11-30 05:52 UTC, MehdiChinoune commented
depends on #21695

2021-11-30 07:48 UTC, BillyONeal commented
> Another issue! I should wait for another 2-4 weeks to be fixed by another PR, and then I have to rebase my changes which will maybe lead to the discovery of another issue, and so on...

I think the existence of https://github.com/microsoft/vcpkg/pull/21695/ provides the understanding of the issue that I was looking for, thanks!

2021-11-30 07:48 UTC, merged

2021-12-02 03:46 UTC, BillyONeal commented
Unfortunately this has caused breakage in our most recent full catalog build:

```
    Installing package qwt-qt6[core]:x86-windows...
    The following files are already installed in D:/installed/x86-windows and are in conflict with qwt-qt6:x86-windows

    Installed by qwt:x86-windows
        bin/qwt.dll
        debug/bin/qwtd.dll
        debug/lib/qwtd.lib
        lib/qwt.lib

    Elapsed time for package qwt-qt6:x86-windows: 34.6 s
```

Any chance we could convince upstream to make these side-by-side-able or should we disable one or the other in CI?

2021-12-02 04:23 UTC, MehdiChinoune commented
> Unfortunately this has caused breakage in our most recent full catalog build:
> 
> ```
>     Installing package qwt-qt6[core]:x86-windows...
>     The following files are already installed in D:/installed/x86-windows and are in conflict with qwt-qt6:x86-windows
> 
>     Installed by qwt:x86-windows
>         bin/qwt.dll
>         debug/bin/qwtd.dll
>         debug/lib/qwtd.lib
>         lib/qwt.lib
> 
>     Elapsed time for package qwt-qt6:x86-windows: 34.6 s
> ```
> 
> Any chance we could convince upstream to make these side-by-side-able or should we disable one or the other in CI?

Some Linux distributions rename them to qwt-qt5 and qwt-qt6 to remove the conflict. I tried to do the same but @JackBoosY refused.

2021-12-02 06:27 UTC, JackBoosY commented
We should not rename the official library name, we should skip one of them in ci.baseline.txt.

2021-12-02 23:57 UTC, BillyONeal commented
> We should not rename the official library name, we should skip one of them in ci.baseline.txt.

Under normal circumstances we should not do that, but the qt5/qt6 split here is a little different in that there appears to be no canonical names for distinguishing to match from upstream. RedHat, Debian etc. all have different ways of doing that selection.

However, given that this new port is causing failures to show up in other ports, I'm removing it again in https://github.com/microsoft/vcpkg/pull/21825 . I discussed this with other maintainers @ras0219 / @ras0219-msft and @vicroms to figure out what a reasonable answer would be. Together we can up with the following list of things that would have to change if you want this port back @MehdiChinoune :

* This port and the qwt one need to some how feed into the qwt build system which version of qt they are expected to build with; as far as we can tell this construction is path dependent (e.g. vcpkg install qt5-base && vcpkg install qwt-qt6 doesn't necessarily produce the same qwt bits as vcpkg install qwt-qt6 because the selection is done by guessing from previous dependencies)
* The headers should be installed to something like qt6/qwt, so that someone can ensure they get the qt6 versions by adding that earlier on their include path. (We observe that this pattern is what Red Hat does and we like it)
* The build system should be patched to add some kind of qt6 marker to the binary names so that they are side by side able with the qwt port.
* (ideally, but we wouldn't block over) There should be some form of pkgconfig files which make downstream consumption reasonably easy. 

Alternately, you could look at adding a qt6 version of the port to a different registry. See example public ones in https://github.com/microsoft/vcpkg/discussions/17161

We are sorry that the road has been so long on this one but we have to place a premium on not breaking folks over new things being added. It would be nice to have some kind of 'meta' port story in the future to more easily solve conditional alternative dependencies like this in the future, but we don't know exactly what that would look like at this time and don't want to ask you to do that kind of major feature development to get a port you want.

2021-12-03 06:43 UTC, MehdiChinoune commented
I have packaged qwt(-qt6) for both Homebrew and MINGW and both have a way to mark packages conflicting.
https://github.com/Homebrew/homebrew-core/pull/84246
https://github.com/msys2/MINGW-packages/pull/9210

I don't see adding a package to ci-baseline as a mechanism to declare conflict, a user will end up trying to install both.

2021-12-03 07:23 UTC, ras0219-msft commented
Our goals with vcpkg are slightly different from those systems; whereas Homebrew and MINGW both have the ultimate goal of providing applications (and libraries are a means to those ends), vcpkg's ultimate goal is to provide a coherent set of libraries for development (and applications are a means to those ends). At the end of the day, vcpkg is a C/C++ library management tool, not a Linux(-ish) system package manager even though we share a lot of common themes.

Our eventual goal is what @BillyONeal mentioned at the end:
> It would be nice to have some kind of 'meta' port story in the future to more easily solve conditional alternative dependencies like this

Users should be able to easily decide whether they want to use qt5 or qt6, and then just install `qwt` which will use their chosen version of Qt. It would be unfortunate to duplicate every package downstream of qt into `-qt5` and `-qt6` variants, because a user can never use both at the same time (and indeed -- might not even care!). Plus, imagine a world with more than just `qt` handled this way; you'd need 2^N packages to handle the explosion of `boost-w/libressl-w/qt6-w/opencv3-...`.