[EasyHook] Fix the build failure "cannot open include file 'afxres.h'" when MFC SDK is not installed
microsoft/vcpkg pull request #21035
Opened 2021-10-28 09:51 UTC by lanyizi

**Describe the pull request**

- #### What does your PR fix?  
  Fixes the build failure of EasyHook when MFC SDK is not installed 
  See https://github.com/EasyHook/EasyHook/issues/210
  https://github.com/microsoft/vcpkg/issues/21011

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  the supported triplets should have remained unchanged; No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `I guess yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-10-29 01:38 UTC, NancyLi1013 requested changes

2021-11-01 10:09 UTC, NancyLi1013 commented on ports/easyhook/fix-build.patch
> + #undef APSTUDIO_READONLY_SYMBOLS
Yes, another patch is needed.

2021-11-22 04:26 UTC, JackBoosY commented on ports/easyhook/fix-build.patch
> + #undef APSTUDIO_READONLY_SYMBOLS
Ping @lanyizi for response.

2021-11-26 00:57 UTC, lanyizi commented on ports/easyhook/fix-build.patch
> + #undef APSTUDIO_READONLY_SYMBOLS
@JackBoosY Was quite busy these days, I think I'll have more time in the next weeks.
By the way, if a separate patch is needed, how should that be called? Like `fix-build-without-mfc.patch`?

2021-11-26 02:34 UTC, JackBoosY commented on ports/easyhook/fix-build.patch
> + #undef APSTUDIO_READONLY_SYMBOLS
I think that if mfc is included in the build conditions expected by the upstream, we should warn users before building in portfile.cmake, rather than force fixing it against the wishes of the upstream.

2021-11-26 21:00 UTC, lanyizi commented on ports/easyhook/fix-build.patch
> + #undef APSTUDIO_READONLY_SYMBOLS
I'm not sure if upstream had the "wish" of requiring MFC (see https://github.com/EasyHook/EasyHook/commit/b71a8efe41e0bd0eab7a8396855bfe75e958d413)

But if we do warn, how should we do that? I'm not very familiar with vcpkg yet, should I use some specific CMake function (or... something like `#pragma message` in the `.patch` file?) to warn users?

2021-11-29 02:57 UTC, JackBoosY commented on ports/easyhook/fix-build.patch
> + #undef APSTUDIO_READONLY_SYMBOLS
Ah the upstream already approve this.

2021-11-29 02:57 UTC, JackBoosY approved these changes

2021-11-29 20:28 UTC, merged

2021-11-29 20:28 UTC, BillyONeal commented
Thanks for the fix! Please try to notify upstream and/or submit this change to them too.