[sjpeg] Add new port
microsoft/vcpkg pull request #21094
Opened 2021-10-31 19:52 UTC by chausner

**Describe the pull request**

- #### What does your PR fix?  
  This adds a new port for [sjpeg](https://github.com/webmproject/sjpeg).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Not sure yet, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-11-01 05:40 UTC, dg0yt commented
What is the problem with windows dynamic?

ATM it installs man1 manual pages (i.e. for tools) but it doesn't install a tool (feature). (They are the "examples".)

2021-11-01 07:16 UTC, NancyLi1013 requested changes

2021-11-01 07:16 UTC, NancyLi1013 commented on ports/sjpeg/portfile.cmake
> +    vcpkg_fail_port_install(ON_LIBRARY_LINKAGE "dynamic")
```suggestion
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```
We prefer to use this to express a port that only supports static build. https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_check_linkage.md

2021-11-01 07:16 UTC, NancyLi1013 commented on ports/sjpeg/vcpkg.json
> +  "supports": "!(windows & !static)",
```suggestion
```
This will block dynamic build. Since we have defined it as `ONLY_STATIC_LIBRARY`, we should not add this here.

2021-11-01 11:10 UTC, chausner commented on ports/sjpeg/portfile.cmake
> +    vcpkg_fail_port_install(ON_LIBRARY_LINKAGE "dynamic")
Applied your suggestion in 906e4bade39fbcdceb69474e2ad7d67036e6ac01.

2021-11-01 11:10 UTC, chausner commented on ports/sjpeg/vcpkg.json
> +  "supports": "!(windows & !static)",
Applied your suggestion in 906e4bade39fbcdceb69474e2ad7d67036e6ac01.

2021-11-01 11:18 UTC, chausner commented
> What is the problem with windows dynamic?
> 
> ATM it installs man1 manual pages (i.e. for tools) but it doesn't install a tool (feature). (They are the "examples".)

It fails with the following linker error:

```
[12/13] cmd.exe /C "cd . && D:\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\utils.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x86\link.exe  CMakeFiles\utils.dir\examples\utils.cc.obj  /out:utils.dll /implib:utils.lib /pdb:utils.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  D:\vcpkg\installed\x86-windows\debug\lib\libpng16d.lib  D:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib  D:\vcpkg\installed\x86-windows\debug\lib\jpeg.lib  opengl32.lib  D:\vcpkg\installed\x86-windows\debug\lib\freeglutd.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: utils.dll utils.lib 
cmd.exe /C "cd . && D:\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\utils.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x86\link.exe  CMakeFiles\utils.dir\examples\utils.cc.obj  /out:utils.dll /implib:utils.lib /pdb:utils.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  D:\vcpkg\installed\x86-windows\debug\lib\libpng16d.lib  D:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib  D:\vcpkg\installed\x86-windows\debug\lib\jpeg.lib  opengl32.lib  D:\vcpkg\installed\x86-windows\debug\lib\freeglutd.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x86\link.exe CMakeFiles\utils.dir\examples\utils.cc.obj /out:utils.dll /implib:utils.lib /pdb:utils.pdb /dll /version:0.0 /machine:X86 /nologo /debug /INCREMENTAL D:\vcpkg\installed\x86-windows\debug\lib\libpng16d.lib D:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib D:\vcpkg\installed\x86-windows\debug\lib\jpeg.lib opengl32.lib D:\vcpkg\installed\x86-windows\debug\lib\freeglutd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\utils.dir/intermediate.manifest CMakeFiles\utils.dir/manifest.res" failed (exit code 1120) with the following output:
utils.cc.obj : error LNK2019: unresolved external symbol "public: void __thiscall sjpeg::EncoderParam::ResetMetadata(void)" (?ResetMetadata@EncoderParam@sjpeg@@QAEXXZ) referenced in function "class std::vector<unsigned char,class std::allocator<unsigned char> > __cdecl ReadJPEG(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int * const,int * const,struct sjpeg::EncoderParam * const)" (?ReadJPEG@@YA?AV?$vector@EV?$allocator@E@std@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@QAH1QAUEncoderParam@sjpeg@@@Z)
```

I did not further investigate this error since the library is missing dllexport annotations and a DEF file, so it is obviously not intended to be built as a dynamic library on Windows.

2021-11-01 11:20 UTC, chausner commented
> ATM it installs man1 manual pages (i.e. for tools) but it doesn't install a tool (feature). (They are the "examples".)

Good catch. I guess they should only get installed if the tools get installed, as well. Or should man pages never get installed?

2021-11-02 01:27 UTC, NancyLi1013 commented
Generally, man pages are not installed to vcpkg. If installed by upstream, we can remove the folder. You can see that there are many ports removing the man installation.

For the tool (examples in this port ), we can disable it via pass `-DSJPEG_BUILD_EXAMPLES=OFF`.

https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-build-testsdocsexamples-by-default

https://github.com/webmproject/sjpeg/blob/676de227d75877eb5863ec805ba0a4b97fc2fc6c/CMakeLists.txt#L24

2021-11-02 18:56 UTC, chausner commented
I pushed a3e6f4a967f009bcbd2d23105426595c8834c457 which removes the man pages.

2021-11-03 03:00 UTC, NancyLi1013 approved these changes

2021-11-03 03:01 UTC, NancyLi1013 commented
LGTM, thanks for adding this port. @chausner

2021-11-04 19:59 UTC, merged