[ismrmrd] no absolute paths
microsoft/vcpkg pull request #21143
Opened 2021-11-02 23:08 UTC by autoantwort

For #20469

2021-11-03 02:41 UTC, NancyLi1013 requested changes

2021-11-03 02:41 UTC, NancyLi1013 commented on ports/ismrmrd/portfile.cmake
>  endif()
```suggestion
```
This seems to be not used in other places.

2021-11-03 02:41 UTC, NancyLi1013 commented on ports/ismrmrd/portfile.cmake
> +vcpkg_copy_tool_dependencies("${CURRENT_PACKAGES_DIR}/tools/ismrmrd")
Could you please use `vcpkg_copy_tools `to handle tools?

2021-11-03 02:43 UTC, NancyLi1013 requested changes

2021-11-03 02:43 UTC, NancyLi1013 commented on ports/ismrmrd/vcpkg.json
>    "version-string": "1.5.0",
```suggestion
  "version": "1.5.0",
```
This might be served by `version `here.

2021-11-08 07:47 UTC, NancyLi1013 commented on ports/ismrmrd/portfile.cmake
> -vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/ismrmrd)
Why do you remove this executable?

2021-11-08 11:47 UTC, autoantwort commented on ports/ismrmrd/portfile.cmake
> -vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/ismrmrd)
Because there are no tools

2021-11-09 01:54 UTC, NancyLi1013 approved these changes

2021-11-09 05:30 UTC, merged