[mdspan] Add new port for kokkos/mdspan
microsoft/vcpkg pull request #21170
Opened 2021-11-03 19:07 UTC by jdthomas

Adds new port for [mdspan](https://github.com/kokkos/mdspan)

- #### What does your PR fix?  
  Fixes # `TBD`, adds new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-11-04 05:48 UTC, NancyLi1013 requested changes

2021-11-04 05:48 UTC, NancyLi1013 commented on ports/mdspan/portfile.cmake
> +  stable)
```suggestion
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO kokkos/mdspan
    REF aced2cebd362a1e15830da030bd16748131d28bd # stable as of 2021-11-03
    SHA512 a1950430be537497fb84c4a8c5e681cacead93512775098f38ea6c1a20b95d0f7110d9d0802fbdcf8ce3c40ade766cc697773f6ea6fcf8c363b3ebee55620f7c
    HEAD_REF stable
)
```

2021-11-04 05:48 UTC, NancyLi1013 commented on ports/mdspan/portfile.cmake
> +vcpkg_cmake_configure(SOURCE_PATH ${SOURCE_PATH})
```suggestion
vcpkg_cmake_configure(SOURCE_PATH "${SOURCE_PATH}")
```

2021-11-04 05:48 UTC, NancyLi1013 commented on ports/mdspan/portfile.cmake
> +     "${CURRENT_PACKAGES_DIR}/debug")
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib" "${CURRENT_PACKAGES_DIR}/debug")
```

2021-11-04 05:48 UTC, NancyLi1013 commented on ports/mdspan/portfile.cmake
> +  RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-11-04 16:32 UTC, jdthomas commented on ports/mdspan/vcpkg.json
> +  "description": "Provide a production-quality implementation of the P0009 proposal as written in preparation for the addition of mdspan to the c++ standard library.",
```suggestion
  "description": "A non-owning multi-dimensional array reference type.",
```

2021-11-04 16:32 UTC, jdthomas commented on ports/mdspan/vcpkg.json
> +  "description": "Provide a production-quality implementation of the P0009 proposal as written in preparation for the addition of mdspan to the c++ standard library.",
@cjdb 's description is nicer than my copy-pasta from the README :)

2021-11-04 16:37 UTC, cjdb commented on ports/mdspan/vcpkg.json
> +  "description": "Provide a production-quality implementation of the P0009 proposal as written in preparation for the addition of mdspan to the c++ standard library.",
FWIW that was also a copypasta with an "A " prefixed :)

2021-11-05 03:09 UTC, NancyLi1013 approved these changes

2021-11-05 03:10 UTC, NancyLi1013 commented
LGTM, thanks for adding this port. @jdthomas

2021-11-05 20:03 UTC, merged

2021-11-30 17:52 UTC, jdthomas commented
> @jdthomas I haven't ever used vcpkg would it be possible to get some guidance on how we can make sure we don't break this integration?

@crtrott 
heh, I am new to this as well, so maybe there's someone better to answer any specific question :)
In the vcpkg repo there's a hard coded sha (aced2cebd362a1e15830da030bd16748131d28bd) that it pulls from the mdspan repo. I think the only maintenance you might be interested in is potentially updating that if mdspan gets updates. Since mdspan takes no external dependencies, I cannot imagine there being any breakage other than potentially while updating (and even then super unlikely unless someone adds another "port" that depends on mdspan).  ... but again, i am new to this too 🤷🏽‍♀️