[rsm-bsa] Update to 4.0.0
microsoft/vcpkg pull request #21214
Opened 2021-11-05 22:01 UTC by Ryan-rsm-McKenzie

**Describe the pull request**

- #### What does your PR fix?  
  Updates [rsm-bsa](https://github.com/Ryan-rsm-McKenzie/bsa) to 4.0.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Just a port update

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-11-08 02:48 UTC, JonLiu1993 approved these changes

2021-11-08 02:52 UTC, JonLiu1993 commented
Feature 'xmem' is tested successfully in the following triplet:
- x64-windows
- x64-windows-static

2021-11-09 00:11 UTC, ras0219-msft requested changes
This PR looks great to me other than deleting bsa.json. Thanks!

2021-11-09 00:11 UTC, ras0219-msft commented on versions/b-/bsa.json
> -{
We must never delete version databases; this would potentially break existing users.

Can you please revert this file?

2021-11-09 00:19 UTC, Ryan-rsm-McKenzie commented on versions/b-/bsa.json
> -{
This was added by accident in the original pr. It's not tied to any port.
https://github.com/microsoft/vcpkg/pull/19496

2021-11-09 02:55 UTC, JonLiu1993 commented on versions/b-/bsa.json
> -{
@ras0219-msft ,When we added this port, the original name of this port was ‘bsa’. Because it was too short, we re-modified the name to ‘rsm-bsa’. We forgot to delete the _revisions/b-/bsa.json_ that we submitted at the beginning. Now when we update it Deleting will not affect the use of this port

2021-11-09 05:06 UTC, merged