Python 3.10: fix deprecated win7 support patch
microsoft/vcpkg pull request #21236
Opened 2021-11-07 01:43 UTC by lakor64

- #### What does your PR fix?  
Fixes building of python3 with win7 support

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
tested on x86-windows-static

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
I think yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

2021-11-07 06:45 UTC, Hoikas commented
What problem are you trying to fix? The patch works perfectly in my testing.

2021-11-07 13:01 UTC, lakor64 commented
> 
> 
> What problem are you trying to fix? The patch works perfectly in my testing.

When I tried to do vcpkg install python3[deprecated-win7-support] it got me an error saying that the patch was not applicable

2021-11-08 09:12 UTC, JackBoosY requested changes

2021-11-08 09:12 UTC, JackBoosY commented on ports/python3/0006-restore-support-for-windows-7.patch
Does the upstream approve this changes?

2021-11-09 02:11 UTC, Hoikas commented on ports/python3/0006-restore-support-for-windows-7.patch
This change seems to be only updating the context lines of an already approved patch so that it will apply without errors. See #16420 for why this patch is needed.

2021-11-09 03:03 UTC, JackBoosY commented on ports/python3/0006-restore-support-for-windows-7.patch
Ahh that's just update the patch.

2021-11-09 03:03 UTC, JackBoosY commented on versions/p-/python3.json
> +      "git-tree": "1d0520eb68f885be8164fbe6060d1d97973bea28",
```suggestion
      "git-tree": "d82868d73c1fef612f6d510750a33d306b1a04df",
```

2021-11-09 03:04 UTC, JackBoosY approved these changes

2021-11-09 13:45 UTC, lakor64 commented
I'm sorry I caused some confusion by using the word "fix". What my commit does is updating the windows 7 deprecated patch to work on Python 3.10. I avehn't applied any fix to the existing patch just updated it to having it correctly applied.

2021-11-10 02:33 UTC, JackBoosY commented
Can you please resolve the file conflict?

2021-11-11 20:19 UTC, lakor64 commented
> 
> 
> Can you please resolve the file conflict?

Is it ok now?

2021-11-12 02:38 UTC, JackBoosY commented
LGTM.

2021-11-13 00:39 UTC, merged