[ois] Update to 1.5.1
microsoft/vcpkg pull request #21244
Opened 2021-11-07 23:55 UTC by chausner

**Describe the pull request**

- #### What does your PR fix?  
  Updates ois to 1.5.1

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

2021-11-08 03:08 UTC, NancyLi1013 requested changes

2021-11-08 03:08 UTC, NancyLi1013 commented on ports/ois/portfile.cmake
>  vcpkg_from_github(
The above message can be removed now. You can add `supports: ! (arm | uwp)` in the vcpkg.json if the new version still doesn't support arm and uwp.

Besides this, please also remove the failures in ci.baseline.txt.
https://github.com/microsoft/vcpkg/blob/66c39e113a348a6ae80419fae5a629b951b00f1a/scripts/ci.baseline.txt#L1032-L1034

2021-11-08 03:08 UTC, NancyLi1013 commented on ports/ois/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION" ${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-11-08 19:49 UTC, chausner commented on ports/ois/portfile.cmake
>  vcpkg_from_github(
I assume you meant `supports: ! (arm | arm64 | uwp)`? I made the corresponding changes in https://github.com/microsoft/vcpkg/pull/21244/commits/781a71e2db84eecbc8e4d630d7a701e63d860a1a.

2021-11-09 01:03 UTC, NancyLi1013 commented on ports/ois/portfile.cmake
>  vcpkg_from_github(
Actually, only arm is enough. Of course, you can also add arm64.

2021-11-09 01:03 UTC, NancyLi1013 approved these changes

2021-11-09 04:43 UTC, merged