[libgeotiff] Update to 1.7.0, revise features and config
microsoft/vcpkg pull request #21253
Opened 2021-11-08 08:50 UTC by dg0yt

- #### What does your PR fix?  
  Updates and revise libgeotiff.
  Restores canonical `find_package(GeoTiff)` and adds proper `usage`.
  Moves tools to explicit feature.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

2021-11-09 06:56 UTC, JonLiu1993 requested changes

2021-11-09 06:56 UTC, JonLiu1993 commented on ports/pdal/vcpkg.json
>    "version-string": "1.7.1",
```suggestion
  "version": "1.7.1",
```

2021-11-09 06:56 UTC, JonLiu1993 commented on ports/liblas/vcpkg.json
>    "version-string": "1.8.1",
```suggestion
  "version": "1.8.1",
```

2021-11-09 06:56 UTC, JonLiu1993 commented on ports/libgeotiff/vcpkg.json
> +  "version-string": "1.7.0",
```suggestion
  "version": "1.7.0",
```

2021-11-09 07:19 UTC, dg0yt commented
@NancyLi1013 Switched to `version` field.

2021-11-09 07:26 UTC, dg0yt commented
Now really switched all three fields...

2021-11-09 08:00 UTC, JonLiu1993 approved these changes

2021-11-10 02:02 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static
- x64-linux

2021-11-10 22:54 UTC, merged