[dcmtk] no absolute paths
microsoft/vcpkg pull request #21277
Opened 2021-11-09 10:14 UTC by autoantwort

For #20469

2021-11-10 02:48 UTC, JackBoosY requested changes

2021-11-10 02:48 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
Are they correct? You removed those definations, and I think you should use the relative path instead.

2021-11-10 02:50 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
The problem is that there is no way to get a relative path inside of header

2021-11-10 02:52 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
So this is a define. The path must be the same regardless where the define is used, so a completely relative path don't work. It can be relative to the folder of the dir of the header, but there is not way to get the dir of the header

2021-11-10 03:04 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
Maybe we should change `"#define DCMTK_PREFIX \"${CURRENT_PACKAGES_DIR}\""` to some code related to get the current path, such as `getcwd`.
We should see what the upstream says.

2021-11-10 03:14 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
You can't use `getcwd` because it changes

It is better to remove this definitions instead of providing wrong ones.

2021-11-10 06:19 UTC, dg0yt commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
Either use standard prefixes, e.g. `/etc`, `/usr`, maybe guarded with `#ifndef`, and/or list the required definitions in `usage`?

2021-11-10 12:55 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
Then I think the best solution is to provide a usage file with the content
```cmake
  target_compile_definitions(main PRIVATE -DDCMTK_PREFIX=${IS_THERE_A_CMAKE_VARIABLE_FOR_THE_INSTALLED_DIR?})
  ...
```

2021-11-11 02:23 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
@autoantwort That's the best way I think.

2021-11-11 02:33 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
@JackBoosY Is there a variable for the installed dir provided by the cmake integration?

2021-11-11 02:37 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
This path can't be fixed because the user may export this port and use it in other place.
So I think we should notice the user to fill this value manually.

2021-11-11 06:14 UTC, dg0yt commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
> Is there a variable for the installed dir provided by the cmake integration?

`${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}`? (not verified, cf. `vcpkg.cmake`)

2021-11-11 06:21 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
> ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}? (not verified, cf. vcpkg.cmake)

As I said, in manifest mode the path is not that one.

2021-11-11 07:14 UTC, dg0yt commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
> > `${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}`? (not verified, cf. vcpkg.cmake)
> 
> As I said, in manifest mode the path is not that one.

Did you verify the path?

IIUC the problem with manifest mode is that there are two modes of operation:
- When building the user project, ports are properly installed to `${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}` in the project's `${CMAKE_CURRENT_BINARY_DIR}`.
- Documentation indicates that users may run `vpckg install` in the directory of the manifest file. 
  However, this doesn't know neither actual `${CMAKE_CURRENT_BINARY_DIR}` nor actual target. So it is pointless and only generates issues on GH.

Correct me if I'm wrong.

2021-11-11 08:57 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
@dg0yt Yeah that's correct, but we can't guarantee the export scenes.

2021-11-11 12:46 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
@JackBoosY So what should I print as usage in your opinion?

2021-11-12 02:25 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"${CURRENT_PACKAGES_DIR}/share/dcmtk/\"" "")
We should consider all scenes, maybe print a usage like:
```
# Pass the installation path such as ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}
target_compile_definitions(main PRIVATE -DDCMTK_PREFIX=${INSTALLATION_DIR})
```

2021-11-15 06:11 UTC, JackBoosY requested changes

2021-11-15 06:11 UTC, JackBoosY commented on ports/dcmtk/portfile.cmake
> +]])
Can we create file `usage` to print that?

2021-11-17 01:25 UTC, autoantwort commented on ports/dcmtk/portfile.cmake
> +]])
Ok I have added a usage file

2021-11-18 09:33 UTC, JackBoosY approved these changes

2021-11-19 05:02 UTC, merged