[itk] no absolute paths
microsoft/vcpkg pull request #21330
Opened 2021-11-11 13:50 UTC by autoantwort

For #20469

2021-11-12 03:02 UTC, NancyLi1013 requested changes

2021-11-12 03:02 UTC, NancyLi1013 commented on ports/itk/vcpkg.json
>    "version-string": "5.1.0",
```suggestion
  "version-semver": "5.1.0",
```
This might be served by `version-semver` here. Please see https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md

2021-11-13 18:40 UTC, ras0219-msft approved these changes

2021-11-15 08:08 UTC, NancyLi1013 approved these changes

2021-11-15 17:10 UTC, merged

2021-11-15 17:10 UTC, ras0219-msft commented
Pretty odd that there's cmake code in the header, but LGTM. Thanks!