Igraph 0.9.5
microsoft/vcpkg pull request #21346
Opened 2021-11-12 08:38 UTC by szhorvat

**Describe the pull request**

- #### What does your PR fix?  
 Update to 0.9.5

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-11-12 08:53 UTC, JonLiu1993 requested changes

2021-11-12 08:53 UTC, JonLiu1993 commented on ports/igraph/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-11-12 14:33 UTC, szhorvat commented
@JonLiu1993 Thanks for the review! CI checks have passed, this PR is now complete.

2021-11-15 07:32 UTC, JonLiu1993 approved these changes

2021-11-15 08:59 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2021-11-15 09:45 UTC, szhorvat commented
@JonLiu1993 Could you please answer my question from here? https://github.com/microsoft/vcpkg/pull/17683#issuecomment-834119358, https://github.com/microsoft/vcpkg/pull/18213#issuecomment-852020227

> When using `${FEATURE_OPTIONS}`, vcpkg adds `-DSOMEFLAG=ON` when an option is enabled. Does it also add `-DSOMEFLAG=OFF` when the option is not enabled?  Is there an easy way to see the CMake invocation, so I can determine this for myself?

2021-11-15 10:15 UTC, JonLiu1993 commented
@szhorvat ,If the options are set to OFF by default, we can set -DSOMEFLAG=OFF in ${FEATURE_OPTIONS} or not listed here, but if we need to enable this option, we need to modify -DSOMEFLAG=ON or add -DSOMEFLAG= ON, when to set it to ON, we need to analyze and judge according to the specific situation

2021-11-16 00:46 UTC, merged