[mapbox-geojson-vt-cpp] Update to 6.6.5
microsoft/vcpkg pull request #21384
Opened 2021-11-13 19:14 UTC by chausner

**Describe the pull request**

- #### What does your PR fix?  
  Updates mapbox-geojson-vt-cpp to 6.6.5

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

2021-11-15 03:03 UTC, NancyLi1013 requested changes

2021-11-15 03:03 UTC, NancyLi1013 commented on ports/mapbox-geojson-vt-cpp/vcpkg.json
> +  "version-semver": "6.6.5",
```suggestion
  "version": "6.6.5",
```
Seems there is no any evidence that can describe this meets the policy of semver.

2021-11-15 17:45 UTC, chausner commented on ports/mapbox-geojson-vt-cpp/vcpkg.json
> +  "version-semver": "6.6.5",
I did find this mention of semver by what appears to be one of the maintainers: https://github.com/mapbox/geojson-vt-cpp/pull/21#issue-120041154

2021-11-16 07:28 UTC, NancyLi1013 commented on ports/mapbox-geojson-vt-cpp/vcpkg.json
> +  "version-semver": "6.6.5",
Thanks for your information.

2021-11-16 07:28 UTC, NancyLi1013 approved these changes

2021-11-17 00:47 UTC, merged