Enable arm64 build for Arrow
microsoft/vcpkg pull request #21467
Opened 2021-11-16 17:16 UTC by jgiannuzzi

**Describe the pull request**

- #### What does your PR fix?  
  This PR adds support for building Arrow for arm64, and for cross-compilation to work (e.g. building `arm64-osx` from a `x64-osx` host). Building on `arm64-windows` is still not supported and would require a patch to Arrow (maybe for a future PR?).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Adding non-Windows `arm64` triplets to the current list (all `x64` triplets).
  No change to the CI baseline (The non-Windows `arm64` triplets are community supported anyway).

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-11-16 17:34 UTC, jgiannuzzi commented
How can I tell the CI to build the arrow port on `arm64-windows`?

2021-11-16 18:11 UTC, autoantwort commented on ports/arrow/vcpkg.json
>    "supports": "x64",
You have to change this line to `x64 | arm64`

2021-11-16 18:22 UTC, jgiannuzzi commented on ports/arrow/vcpkg.json
>    "supports": "x64",
Thank you @autoantwort!

2021-11-17 09:13 UTC, JackBoosY requested changes

2021-11-17 09:13 UTC, JackBoosY commented on ports/arrow/portfile.cmake
> +vcpkg_fail_port_install(ON_ARCH "x86" "arm")
```suggestion
```
Since keyword `supports` have implement this, we don't need this anymore.

2021-11-17 09:37 UTC, jgiannuzzi commented on ports/arrow/portfile.cmake
> +vcpkg_fail_port_install(ON_ARCH "x86" "arm")
Done. Thanks @JackBoosY!

2021-11-17 09:38 UTC, JackBoosY approved these changes

2021-11-18 02:01 UTC, JackBoosY commented
LGTM.

2021-11-19 04:39 UTC, merged