Update meson to 0.60.1
microsoft/vcpkg pull request #21542
Opened 2021-11-19 14:27 UTC by Neumann-A

- rename tool-meson to vcpkg-tool-meson. (deprecate old port or to be more precise use for testing of `vcpkg_find_acquire_program(MESON)`)
- make ports explicitly depend on vcpkg-tool-meson if they require meson.
- make it so that no future changes to `vcpkg_find_acquire_program` are necessary if meson gets updated. (Will reduce the number of CI rebuilds.)

I expect ports to break with this because meson updates break stuff even more than cmake updates

2021-11-19 15:45 UTC, Neumann-A commented on ports/gstreamer/vcpkg.json
> +    },
```suggestion
```

accidental duplication

2021-11-19 21:17 UTC, c72578 commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +    elseif(${program}) # onyl do a version check if ${program} has a value
onyl->only

2021-11-23 10:33 UTC, Neumann-A commented
@BillyONeal  can you say something about the v8 failure. Is that a baseline failure?

2021-11-23 10:34 UTC, Neumann-A commented
opened https://github.com/mesonbuild/meson/issues/9618 because they regressed my previous glib fix for libintl.

2021-11-23 17:32 UTC, BillyONeal commented
> @BillyONeal can you say something about the v8 failure. Is that a baseline failure?
> 
> probably baseline see #21620

Indeed; I was forced to engage Twitter Driven Development https://twitter.com/sokac/status/1463182302679220230

2021-11-26 07:01 UTC, BillyONeal commented
I believe Google folks fixed v8

2021-11-26 08:09 UTC, Neumann-A commented
@BillyONeal:
hpx on linux:
`-- Could NOT find TCMalloc (missing: TCMALLOC_LIBRARY TCMALLOC_INCLUDE_DIR) `
```
CMake Error at cmake/HPX_Message.cmake:51 (message):
  HPX_WITH_MALLOC was set to tcmalloc, but tcmalloc could not be found.
  Valid options for HPX_WITH_MALLOC are: system, tcmalloc, jemalloc,
  mimalloc, tbbmalloc, and custom
Call Stack (most recent call first):
  cmake/HPX_SetupAllocator.cmake:47 (hpx_error)
  CMakeLists.txt:2166 (include)
```

looks like a baseline regression?

2021-11-26 08:18 UTC, BillyONeal commented
> @BillyONeal: hpx on linux: `-- Could NOT find TCMalloc (missing: TCMALLOC_LIBRARY TCMALLOC_INCLUDE_DIR) `
> 
> ```
> CMake Error at cmake/HPX_Message.cmake:51 (message):
>   HPX_WITH_MALLOC was set to tcmalloc, but tcmalloc could not be found.
>   Valid options for HPX_WITH_MALLOC are: system, tcmalloc, jemalloc,
>   mimalloc, tbbmalloc, and custom
> Call Stack (most recent call first):
>   cmake/HPX_SetupAllocator.cmake:47 (hpx_error)
>   CMakeLists.txt:2166 (include)
> ```
> 
> looks like a baseline regression?

We did just remove hpx from ci.baseline.txt here but that was because it passed in CI (it got PASSING: REMOVE FROM FAIL LIST). Perhaps it's order dependent?

2021-11-26 08:27 UTC, BillyONeal commented
I'm able to repro the hpx failure locally, stand by...

2021-11-26 08:32 UTC, BillyONeal commented
https://github.com/microsoft/vcpkg/pull/21673

2021-11-26 08:36 UTC, Neumann-A commented
the gstreamer regression also seems like baseline:
`LINK : fatal error LNK1181: cannot open input file 'm.lib'`
```
, {"name": "flac"
, "version": "1.3.3"
, "compile_args": ["-ID:/installed/x64-windows/include"]
, "link_args": ["D:/installed/x64-windows/lib/FLAC.lib"
, "D:/installed/x64-windows/lib/ogg.lib"
, "m.lib"]}
```
```
gst-plugins-good| Dependency flac found: NO unknown version, but need: ['>=1.1.4']
gst-plugins-good| Run-time dependency flac found: YES 1.3.3
```
so its an issue in libflac. fixed it manually.

2021-11-29 03:03 UTC, JackBoosY commented
The hpx regression should not related to this PR.

2021-11-29 20:56 UTC, BillyONeal commented
The osx failure ran on the one we suspect is unhealthy from https://github.com/microsoft/vcpkg/pull/21676#issuecomment-982010390 but I'm not resubmitting because it looks like there are version DB updates needed. I've removed -06 from the fleet.

2021-11-29 23:06 UTC, Neumann-A commented
hmm the formater in vcpkg-tool changed?

2021-11-30 00:04 UTC, BillyONeal commented
> hmm the formater in vcpkg-tool changed?

https://github.com/microsoft/vcpkg-tool/pull/282 may have had an effect, yes

2021-12-01 03:08 UTC, JackBoosY requested changes

2021-12-01 03:08 UTC, JackBoosY commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +    elseif(${program}) # only do a version check if ${program} has a value
What if NOT `"${version_command}" STREQUAL ""` and NOT `${program}` ?

2021-12-02 03:02 UTC, JackBoosY approved these changes

2021-12-02 03:19 UTC, BillyONeal approved these changes

2021-12-02 23:48 UTC, BillyONeal commented
I'm merging this despite the qwt-qt6 failure because that port is currently broken and being backed out https://github.com/microsoft/vcpkg/pull/21825

2021-12-02 23:48 UTC, merged

2021-12-02 23:48 UTC, BillyONeal commented
Thanks for the update!