[spirv-cross] Fix iOS triplet build
microsoft/vcpkg pull request #21588
Opened 2021-11-22 02:40 UTC by luncliff

### What does your PR fix?  

Fix port bug. It tries to install CLI tools which are not built with iOS triplets.

### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

Only several community triplets.

* `arm64-ios`
* `x64-ios`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes :D

2021-11-22 06:08 UTC, JonLiu1993 requested changes

2021-11-22 06:08 UTC, JonLiu1993 commented on ports/spirv-cross/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-11-22 06:08 UTC, JonLiu1993 commented on ports/spirv-cross/portfile.cmake
> +    vcpkg_cmake_config_fixup(CONFIG_PATH "share/spirv_cross_${COMPONENT}/cmake" PACKAGE_NAME "spirv_cross_${COMPONENT}")
```suggestion
    vcpkg_cmake_config_fixup(CONFIG_PATH share/spirv_cross_${COMPONENT}/cmake PACKAGE_NAME spirv_cross_${COMPONENT})
```

2021-11-23 06:08 UTC, JonLiu1993 approved these changes

2021-11-23 20:15 UTC, merged

2021-11-23 20:15 UTC, BillyONeal commented
Thanks for the fix!