[boinc] Fix crosscompilation on linux for arm/arm64/armv6
microsoft/vcpkg pull request #21587
Opened 2021-11-22 01:40 UTC by AenBleidd

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

2021-11-22 04:14 UTC, JackBoosY requested changes

2021-11-22 04:14 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
This should be processed by `vcpkg_configure_make`, can you double confirm that?

2021-11-22 05:16 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
Without this parameter 'configure' scripts fails to detect correct environment. So this is an essential change for this function. Tested with custom port here: https://github.com/BOINC/boinc-apps/pull/26

2021-11-22 07:02 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
Here:
https://github.com/microsoft/vcpkg/blob/653912591af709c162fba2d4000a6b3362c8d3c9/scripts/cmake/vcpkg_configure_make.cmake#L108-L143

vcpkg_configure_make will detect the host arch to suitable the configure options by adding option `DETERMINE_BUILD_TRIPLET`. So in the correct triplet it should have no issues. See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_make.md#determine_build_triplet
Can you double confirm that?
If not, you should use option `BUILD_TRIPLET` instead of this. See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_make.md#build_triplet

2021-11-22 07:29 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
I believe here's the some kind of confusion.
Function you mentioned correctly recognise host_cpu, but when I build 'arm' on 'amd64', I need to pass to 'configure' script not the host cpu ('amd64' in this case) but target cpu ('arm-linux').
So this is not an issue with vcpkg, this might be an issue in our scripts (wrong variable naming, probably?). I'll investigate this in BOINC codebase, but since next release is not planned for a few next months, this fix for this port will be fine (since I'm a maintainer for both of these products).

2021-11-22 07:31 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
cc @Neumann-A

2021-11-22 07:32 UTC, JackBoosY requested changes

2021-11-22 07:32 UTC, JackBoosY commented on ports/boinc/vcpkg.json
> +  "port-version": 3,
Also, since you are the maintainer, can you please add `maintainers` here? 
See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#maintainers

2021-11-22 07:34 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
I think you should use `--target` instead of `--host` since you are using cross build here?

2021-11-22 07:39 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
According to this ( https://gcc.gnu.org/onlinedocs/gccint/Configure-Terms.html ) I need to specify only `--host` since I'm using the correct compiler that builds for specific architecture.
Also, we already use exactly the `--host` parameter: https://github.com/BOINC/boinc/blob/06cc5302991217bef89ba60404e584bd94924d2a/android/build_boinc_arm.sh#L76
This is an example of Android script, but the logic is the same.

2021-11-22 07:40 UTC, AenBleidd commented on ports/boinc/vcpkg.json
> +  "port-version": 3,
Fixed

2021-11-22 08:00 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
>  need to specify only --host since I'm using the correct compiler that builds for specific architecture.

Therefore, I think you should create a custom triplet file and use it in the build command.
Modifying here will cause this "special" configuration to be used in all triplets, so I think it is inappropriate.

2021-11-22 08:09 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
I didn't understand which `specific architecture` mean.
`arm64-linux` or `arm-linux` uses gcc to build by default. When building `arm/arm64-linux` in `x86/x64-linux`, `--host` should be `x86/x64`, and `--target` should be `arm/arm64`.
Right?

2021-11-22 08:12 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
This is an error log with debug output `before` this change: https://github.com/BOINC/boinc-apps/runs/4280686170?check_suite_focus=true

Lines of interest:
```
    Command failed: /usr/bin/bash -c "V=1 ./../src/18_-7.18.1-1910b9f200.clean/configure  \"--disable-server\" \"--disable-client\" \"--disable-manager\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/armvfpv3-linux-static/vcpkg_installed/armvfpv3-linux-static\""
```
As you can see above, `--host` parameter was not passed
And the hint from the error log:
```
checking whether we are cross compiling... configure: error: in `/home/runner/work/boinc-apps/boinc-apps/vcpkg/buildtrees/boinc/armvfpv3-linux-static-rel':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

2021-11-22 08:19 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
> I didn't understand what `specific architecture` mean.
> `arm64-linux` or `arm-linux` uses gcc to build by default. When building `arm/arm64-linux` in `x86/x64-linux`, `--host` should be `x86/x64`, and `--target` should be `arm/arm64`.
> Right?

No.
`host` is the target architecture
`target` is used when you build toolchains.
Here's a good answer: https://stackoverflow.com/a/15901574/4210508

2021-11-22 08:22 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
Can you please add `DETERMINE_BUILD_TRIPLET` to `vcpkg_configure_make` and try again?

2021-11-22 08:32 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
It doesn't work: https://github.com/BOINC/boinc-apps/runs/4283961130?check_suite_focus=true

2021-11-22 08:33 UTC, JackBoosY commented on ports/boinc/portfile.cmake
> +    endif()
@Neumann-A What do you think about?

2021-11-23 05:54 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
@JackBoosY, could you please remove 'requires:authors-response' label? Technically I answered your questions, so you are not waiting for me ^^

2021-11-23 07:00 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    endif()
After resolving the initial confusion about autotools `--host`, the question remains where armv6 handling should be done, in port boinc, or here:
https://github.com/microsoft/vcpkg/blob/30465138ef7facf1d4c1aa8a06dd62ceb71cc2eb/scripts/cmake/vcpkg_configure_make.cmake#L131-L143

Note that `vcpkg_configure_make` already has case-insensitive handling for everything but armv6.

2021-11-23 07:01 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    if (${VCPKG_TARGET_ARCHITECTURE} MATCHES "arm")
This line will also match `arm64` and `armv6`, so the remaining branches are unreachable.

2021-11-23 07:15 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
It's handled in BOINC code

2021-11-23 07:18 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    if (${VCPKG_TARGET_ARCHITECTURE} MATCHES "arm")
Fixed. @dg0yt, thanks for this finding!

2021-11-23 07:23 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    endif()
If the special case is only "armv6-linux in BOINC", why not override the autotools host triplet (i.e. pass `BUILD_TRIPLET`) just for armv6-linux?

2021-11-23 07:24 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
Because it's not only for armv6-linux. Other were not working either.
Here's an example: https://github.com/BOINC/boinc-apps/runs/4280686170?check_suite_focus=true

2021-11-23 07:48 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    endif()
I see. Basically, cross-compiling support for linux on linux seems to be fairly unsupported in `vcpkg_configure_make`.
- `z_vcpkg_determine_autotools_target_cpu` is called only for `VCPKG_TARGET_IS_WINDOWS`.
- `arg_DETERMINE_BUILD_TRIPLET` is only checked for `VCPKG_TARGET_IS_WINDOWS` and `VCPKG_TARGET_IS_OSX`.

This is what needs to be fixed.

2021-11-23 07:50 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
This is out-of-scope of this PR, and looks like a bigger ticket that will require extensive testing.

2021-11-23 07:59 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    endif()
> This is out-of-scope of this PR, and looks like a bigger ticket that will require extensive testing.

Fair enough.
But you should still prefer setting `BUILD_TRIPLET` over adding to `OPTIONS` in this case. This avoids eventually having two `--host` arguments to `configure`.
Or simply set `VCPKG_MAKE_BUILD_TRIPLET` in the arm* toolchain files.

2021-11-23 08:05 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
I don't understand what you are talking about. When I build this port for some particular architecture, I'm using a triplet that specifies VCPKG_TARGET_ARCHITECTURE. And this target is not used to pass -host parameter correctly.
Maybe you can give me an example of triplet and how it should be called? Maybe I'm just doing smth wrong while building this port.

2021-11-23 08:16 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    endif()
> prefer setting `BUILD_TRIPLET` over adding to `OPTIONS` in this case. This avoids eventually having two `--host` arguments to `configure`. 

This refers to `ports/boinc/portfile.cmake`.

> Or simply set `VCPKG_MAKE_BUILD_TRIPLET` in the arm* toolchain files.

I meant tor refer vcpkg triplet files, not toolchain files. Basically, next to 
~~~
set(VCPKG_TARGET_ARCHITECTURE armv6)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
~~~
add 
~~~
set(VCPKG_MAKE_BUILD_TRIPLET armv6-linux)
~~~

2021-11-23 08:59 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
I tried this now and it fails:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/18_-7.18.1-1910b9f200.clean/configure aarch64-linux \"--disable-server\" \"--disable-client\" \"--disable-manager\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/arm64-linux-static/vcpkg_installed/arm64-linux-static\""
```
Should I use
```
set(VCPKG_MAKE_BUILD_TRIPLET -host=aarch64-linux)
```
instead of
```
```
set(VCPKG_MAKE_BUILD_TRIPLET aarch64-linux)
```
?
If yes - then it looks weird for me

2021-11-23 10:09 UTC, dg0yt commented on ports/boinc/portfile.cmake
> +    endif()
Ah, indeed it takes the full option -- it goes directly to the `configure` call if set.

2021-11-23 10:11 UTC, AenBleidd commented on ports/boinc/portfile.cmake
> +    endif()
ok. looks like full option is working for me.
Thanks for your help @dg0yt.
@JackBoosY, looks like this PR is not needed anymore

2021-11-23 10:11 UTC, closed without merging