add InitializeVcpkg CMake module
microsoft/vcpkg pull request #21591
Opened 2021-11-22 06:17 UTC by Be-ing

This CMake module can be included to automatically initialize a vcpkg Git submodule, or alternatively allow the user to specify a `VCPKG_ROOT` path manually to use a vcpkg repository outside the repository of the CMake project. This is intended to be copied verbatim into a CMake project because the presence of the vcpkg repository is not yet established when this is used.

I don't know if `docs/examples` is the best place for this, but nowhere else seemed better.

2021-11-22 07:03 UTC, Osyotr commented
I very much like the idea but IMHO users should be able to specify:
1) vcpkg repo URL
2) directory where to clone the repo
The script should probably also read builtin registry baseline from `vcpkg.json`/`vcpkg_configuration.json` and use it as git ref to make sure everyone has the same repo cloned. (I'm not sure if and how this affects binary caching but just in case).

2021-11-22 07:23 UTC, JackBoosY commented
We do like this feature, and I think we should have more discuss here.
cc @ras0219-msft @BillyONeal @vicroms @strega-nil-ms

2021-11-22 07:24 UTC, JackBoosY commented
Of course, I personally think that using vcpkg as a library is better than a toolchain.

2021-11-22 07:44 UTC, Be-ing commented
@Osyotr those are interesting ideas but I'm not sure that's something this simple CMake module should do. What would be the advantage of having CMake do that instead of simply calling Git manually before running CMake then specifying `VCPKG_ROOT`? As for reading the vcpkg.json file, I think that would be overkill. I think it should be up to the developers to ensure the submodule is checked out to a commit at or beyond the baseline specified in the manifest.

To clarify my intention with this, I want to make it trivially easy for new developers (or old developers setting up on a new machine) to get started working on a CMake project that uses vcpkg without needing to know any of the implementation details of vcpkg. At the same time, the `VCPKG_ROOT` variable allows for more knowledgeable developers to use any arbitrary workflow, for example using one central vcpkg repository for multiple CMake projects.

2021-11-22 08:04 UTC, JackBoosY commented
This will fix https://github.com/microsoft/vcpkg/discussions/20994.

2021-11-22 14:31 UTC, autoantwort commented
On discord 
```cmake
include(FetchContent)
FetchContent_Declare(
    vcpkg
    GIT_REPOSITORY https://github.com/microsoft/vcpkg.git
    GIT_TAG b295670e4bab14debe88d92cd5364b21ce26232c # 2021-09-09
)
if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    FetchContent_Populate(vcpkg)
    set(CMAKE_TOOLCHAIN_FILE "${vcpkg_SOURCE_DIR}/scripts/buildsystems/vcpkg.cmake")
endif()
```
 was proposed by @strega-nil-ms

2021-11-22 16:03 UTC, Osyotr commented
Actually, both variants are not perfect. I think we should move from vcpkg as a toolchain because it's impossible to reference `vcpkg.cmake` in `CMakePresets.json` before it is downloaded.

2021-11-22 16:37 UTC, Be-ing commented
I don't understand what you're suggesting as an alternative.

2021-11-22 22:07 UTC, BillyONeal requested changes
I think adding yet another deployment mechanism for vcpkg needs some serious justification as to why the existing ways to do this are bad.

>To clarify my intention with this, I want to make it trivially easy for new developers (or old developers setting up on a new machine) to get started working on a CMake project that uses vcpkg without needing to know any of the implementation details of vcpkg.

I don't think getting this .cmake into a user's project is substantially less complex than the status quo? The complex parts are about creating the submodule and managing the SHA thereof and this is no help for that.

2021-11-23 01:06 UTC, Hoikas commented on docs/examples/InitializeVcpkg.cmake
> +      message(STATUS "Initializing vcpkg Git submodule")
Or [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html).

2021-11-23 01:17 UTC, Be-ing commented on docs/examples/InitializeVcpkg.cmake
> +  set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
I thought about checking if `CMAKE_TOOLCHAIN_FILE` is set and if so, using it to set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`. Would you prefer that?

2021-11-23 01:19 UTC, Be-ing commented on docs/examples/InitializeVcpkg.cmake
> +      message(STATUS "Initializing vcpkg Git submodule")
I disagree that encoding the same information as a submodule in CMakeLists.txt is a good idea.

2021-11-23 01:21 UTC, Be-ing commented
> I don't think getting this .cmake into a user's project is substantially less complex than the status quo?

It is. With this, all a new developer has to do is copy and paste the Git URL for the project into Visual Studio (or an IDE of their choice with similar functionality). Thereafter, CMake and vcpkg take care of setting everything up automatically. It's pretty awesome.

> The complex parts are about creating the submodule and managing the SHA thereof and this is no help for that.

It is not intended to help with that. The purpose of this is to easy the process of setting up a development environment for an existing project.

2021-11-23 04:17 UTC, Be-ing commented on docs/examples/InitializeVcpkg.cmake
> +      message(STATUS "Initializing vcpkg Git submodule")
I think FetchContent would be a significant step back from using a Git submodule. Git can be configured to automatically update submodules when checking out a commit of the parent repository. Even without that, `git status` notifies the developer when their submodule is out of date. FetchContent can't do that. You could hypothetically hack something together with FetchContent and some execute_process calls to Git, but that would be reimplementing Git submodule in a less robust and less well understood way.

2021-11-23 20:29 UTC, Hoikas commented on docs/examples/InitializeVcpkg.cmake
> +      message(STATUS "Initializing vcpkg Git submodule")
If the goal here is to produce something that "just works", then it makes more sense to me to just let FetchContent handle fetching vcpkg's latest master. Then, use the builtin-baseline in the manifest to constrain the revision. That way, there is no need to worry about nonsense like "crap, I need to `git submodule init` because I forgot to recurse the clone", "grrr, the submodule changed, so I have to `git submodule update`, and so forth due to default git configurations. Submodules, IME, offer an inferior UX and should be avoided when possible.

2021-12-17 21:54 UTC, strega-nil-ms commented on docs/examples/InitializeVcpkg.cmake
> +      message(STATUS "Initializing vcpkg Git submodule")
I also really really don't like the use of submodules here, instead of say, `FetchContent`. I think this might be cool for a community repository, but I don't want to officially support it forever.

2021-12-22 05:16 UTC, BillyONeal commented
Given that several maintainers have commented that this isn't a direction in which we want to direct customers, and there is probably nothing that can be done in the direction this PR desires that would change that, I'm closing this.

@Be-ing I'm sorry that we were not able to merge this contribution; we remain interested in your other contributions! Thanks for your interest in contributing to vcpkg!

2021-12-22 05:16 UTC, closed without merging

2021-12-22 09:42 UTC, Be-ing commented
That's okay. I didn't open this expecting that it would definitely be merged.

2021-12-23 03:15 UTC, ilongshan commented
Using "brew install x264" can install x264. I am not sure how they make it work. Hope vcpkg can support x264 soon.