[teemo] Update to v2.3
microsoft/vcpkg pull request #21616
Opened 2021-11-23 04:45 UTC by winsoft666

**Describe the pull request**

- #### What does your PR fix?  
Update to v2.3 version.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <linux, widnows / osx, uwp>, <Yes>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-11-23 07:25 UTC, JonLiu1993 requested changes

2021-11-23 07:25 UTC, JonLiu1993 commented on ports/teemo/vcpkg.json
> +  "port-version": 3,
```suggestion
  "version": "2.3",
```

2021-11-23 07:32 UTC, winsoft666 commented on ports/teemo/vcpkg.json
> +  "port-version": 3,
OK, updated!

2021-11-23 07:38 UTC, JonLiu1993 commented
@winsoft666 ,LGTM, plesase run command "./vcpkg x-add-version teemo --overwrite-version" and commit again

2021-11-23 07:40 UTC, winsoft666 commented on ports/teemo/vcpkg.json
> +  "port-version": 3,
> @winsoft666 ,LGTM, plesase run command "./vcpkg x-add-version teemo --overwrite-version" and commit again

OK, updated!

2021-11-23 07:41 UTC, JonLiu1993 requested changes

2021-11-23 07:41 UTC, JonLiu1993 commented on versions/t-/teemo.json
> +    },
```suggestion
```

2021-11-25 06:51 UTC, JonLiu1993 approved these changes

2021-11-26 08:57 UTC, merged

2021-11-26 08:58 UTC, BillyONeal commented
Thanks for the version update!