[qmake] Check build type for debug/release
microsoft/vcpkg pull request #21650
Opened 2021-11-24 17:12 UTC by itsmattkc

**Describe the pull request**

- #### What does your PR fix?  
  The existing qmake build script assumes that both a debug and release build will be made and would throw errors if only a release build was being made (notably with qt5-*). This PR checks the `VCPKG_BUILD_TYPE` to ensure those errors don't occur.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I have not updated a port.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-11-24 18:11 UTC, Neumann-A commented on scripts/cmake/vcpkg_build_qmake.cmake
>      foreach(build_type IN ITEMS debug release)
```suggestion
    if(NOT DEFINED VCPKG_BUILD_TYPE)
        set(items debug release)
    else()
        set(items release)
    endif()
    foreach(build_type IN ITEMS ${items})
```
Note: release only builds are not really release builds but more like single configurations builds.

2021-11-24 18:12 UTC, Neumann-A commented on scripts/cmake/vcpkg_build_qmake.cmake
>      foreach(build_type IN ITEMS debug release)
also remove all other changes

2021-11-25 05:53 UTC, JackBoosY requested changes

2021-11-25 05:53 UTC, JackBoosY commented on scripts/cmake/vcpkg_build_qmake.cmake
> +    endif()
What about I defined `VCPKG_BUILD_TYPE` with `debug`?

2021-11-25 06:10 UTC, itsmattkc commented on scripts/cmake/vcpkg_build_qmake.cmake
> +    endif()
I've been told in another PR that vcpkg no longer supports `VCPKG_BUILD_TYPE=debug` and that my if statements should not include that: https://github.com/microsoft/vcpkg/pull/21501#issuecomment-972710038

2021-11-25 06:18 UTC, JackBoosY commented on scripts/cmake/vcpkg_build_qmake.cmake
> +    endif()
Yeah, we does say that.
I need other guys to review this again.

2021-11-25 06:18 UTC, JackBoosY approved these changes

2021-11-26 09:16 UTC, merged

2021-11-26 09:16 UTC, BillyONeal commented
Thanks for the fix!