[libpmemobj-cpp] no absolute paths
microsoft/vcpkg pull request #21703
Opened 2021-11-27 19:06 UTC by autoantwort

For #20469

2021-11-29 05:51 UTC, JackBoosY requested changes

2021-11-29 05:51 UTC, JackBoosY commented on ports/libpmemobj-cpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
Should we use `vcpkg_fixup_pkgconfig` instead? This port doesn't have any dependency.

2021-11-29 17:34 UTC, autoantwort commented on ports/libpmemobj-cpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
It will fail with:
```
-- Fixing pkgconfig file: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libpmemobj-cpp_x64-osx/lib/pkgconfig/libpmemobj++.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  /usr/local/bin/pkg-config --exists libpmemobj++ failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libpmemobj-cpp_x64-osx/lib/pkgconfig:/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/libpmemobj-cpp_x64-osx/share/pkgconfig:/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/lib/pkgconfig:/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/share/pkgconfig"
      output: Package libpmemobj was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libpmemobj.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'libpmemobj', required by 'libpmemobj++', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/libpmemobj-cpp/portfile.cmake:33 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)
```

2021-11-30 02:26 UTC, JackBoosY commented on ports/libpmemobj-cpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
Same as [my comment](https://github.com/microsoft/vcpkg/pull/21704#discussion_r758052146).

2021-11-30 21:17 UTC, autoantwort commented on ports/libpmemobj-cpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
See https://github.com/microsoft/vcpkg/pull/21704#pullrequestreview-819436226

2021-12-01 06:44 UTC, JackBoosY commented on ports/libpmemobj-cpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
Yeah, as Robert said, I think we'd better enable `libpmemobj` to generate the pkgconfig.

2021-12-28 12:51 UTC, autoantwort commented on ports/libpmemobj-cpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
I have looked at it, but it seems to be a not so easy task and I am not really motivated to do it. I only created this PR to merge https://github.com/microsoft/vcpkg-tool/pull/172

2021-12-28 13:47 UTC, JackBoosY commented
Can you please merge to master?

2021-12-28 15:03 UTC, JackBoosY approved these changes

2021-12-28 22:13 UTC, merged