[fltk] no absolute paths
microsoft/vcpkg pull request #21714
Opened 2021-11-28 00:26 UTC by autoantwort

For #20469

2021-11-30 03:04 UTC, Cheney-W requested changes

2021-11-30 03:04 UTC, Cheney-W commented on ports/fltk/portfile.cmake
> +file(REMOVE "${CURRENT_PACKAGES_DIR}/share/fltk/UseFLTK.cmake")
The UseFLTK.cmake file is still being used in the FLTKConfig.cmake file when the FLTK_USE_FILE variable is set:
```
set (FLTK_USE_FILE ${CMAKE_CURRENT_LIST_DIR}/UseFLTK.cmake)
```
so I think it is better to replace the absolute path than to delete this file.

2021-12-01 00:12 UTC, autoantwort commented on ports/fltk/portfile.cmake
> +file(REMOVE "${CURRENT_PACKAGES_DIR}/share/fltk/UseFLTK.cmake")
This file is deprecated and will be removed in the next version.

2021-12-01 02:16 UTC, Cheney-W commented on ports/fltk/portfile.cmake
> +file(REMOVE "${CURRENT_PACKAGES_DIR}/share/fltk/UseFLTK.cmake")
Yes, I known this file will be removed in the next version, however, in the current version provided by vcpkg, it still has the probability of being used, so deleting the file directly may lead to a bug in usage.

2021-12-02 01:13 UTC, autoantwort commented on ports/fltk/portfile.cmake
> +file(REMOVE "${CURRENT_PACKAGES_DIR}/share/fltk/UseFLTK.cmake")
The file in the current state is already pointing to two non existing locations and is not functional, so I would wonder if anybody is using this file currently.

2021-12-02 08:18 UTC, JackBoosY commented on ports/fltk/portfile.cmake
> +file(REMOVE "${CURRENT_PACKAGES_DIR}/share/fltk/UseFLTK.cmake")
Please note that this file, like `VTK_USE_FILE`, may be directly called by other users.
Since the upstream has not completely deprecated and deleted this file, removing it here may cause the statement that directly includes it in the custom project to fail.
So I think the best solution is to replace it with a relative path.

2021-12-03 20:35 UTC, autoantwort commented on ports/fltk/portfile.cmake
> +file(REMOVE "${CURRENT_PACKAGES_DIR}/share/fltk/UseFLTK.cmake")
Ok I have now fixed the ´UseFLTK.cmake´ file

2021-12-06 02:39 UTC, Cheney-W approved these changes

2021-12-07 04:18 UTC, merged

2021-12-07 04:18 UTC, BillyONeal commented
Thanks for the fix!