[pdal] no absolute paths
microsoft/vcpkg pull request #21723
Opened 2021-11-28 02:54 UTC by autoantwort

For #20469

2021-11-28 03:37 UTC, autoantwort commented
Also depends on #20439

2021-11-28 06:59 UTC, dg0yt commented
Don't modernize outdated pdal too much. There is #21275.

2021-11-28 12:13 UTC, autoantwort commented
Ah sorry, I only changed vcpkg_configure_cmake to vcpkg_cmake_configure etc. and added some quotes. But I can revert this changes

2021-11-29 12:58 UTC, dg0yt requested changes
How about putting this PR in draft state? I will take it as a check list for the PDAL update.

2021-11-29 12:58 UTC, dg0yt commented on ports/pdal/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/pdal/pdal_features.hpp" "#define PDAL_PLUGIN_INSTALL_PATH \"${CURRENT_PACKAGES_DIR}/bin\"" "")
It is probaly safe to define PDAL_PLUGIN_INSTALL_PATH as `"."`.

2021-11-29 12:58 UTC, dg0yt commented on ports/pdal/usage
> +Add the following cmake code to your CMakeLists.txt to create definitions for DCMTK
It is PDAL, not DCMTK.

2021-11-29 12:58 UTC, dg0yt commented on ports/pdal/usage
> +                "PDAL_PLUGIN_INSTALL_PATH=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin"
I doubt that `bin` is the right path for linux or osx. I would prefer to not add non-portable instructions.

2021-11-29 12:58 UTC, dg0yt commented on ports/pdal/usage
> +Add the following cmake code to your CMakeLists.txt to create definitions for DCMTK
In addition, I think it would be better to handle PDAL_PLUGIN_INSTALL_PATH in the config files.

2021-11-29 17:43 UTC, autoantwort commented
> It is probaly safe to define PDAL_PLUGIN_INSTALL_PATH as ".".

Ok good, then the `usage` file is not needed.

2021-12-13 14:20 UTC, closed without merging