[gamenetworkingsockets] Update with fixes for static library and add webrtc feature
microsoft/vcpkg pull request #21759
Opened 2021-11-29 21:31 UTC by eddiejames

This PR bumps the GameNetworkingSockets revision and adds the webrtc feature for P2P support.

- #### What does your PR fix?  
  Fixes the lack of static linking both in Linux and Windows.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Linux and Windows. No I haven't - GameNetworkingSockets isn't in the CI baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  I believe so

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2021-11-30 03:06 UTC, JackBoosY requested changes

2021-11-30 03:06 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +    REF 5c793b9f1a507aa9670c8634817bde48b744428b # v1.3.0
```suggestion
    REF 5c793b9f1a507aa9670c8634817bde48b744428b
```
We shouldn't mislead the contributors.

2021-11-30 03:06 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +)
```suggestion
if (USE_STEAMWEBRTC)
    vcpkg_from_git(
        OUT_SOURCE_PATH WEBRTC_SOURCE_PATH
        URL https://webrtc.googlesource.com/src
        REF 30a3e787948dd6cdd541773101d664b85eb332a6
        HEAD_REF MAIN
    )
endif()
```
This should only be executed when the user select the webrtc feature.

2021-11-30 03:06 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
Maybe we should use `file(RENAME)` instead?

2021-11-30 14:14 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
Sure!

2021-11-30 20:06 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
Actually rename gives me "access denied" on Windows... I think copy would be safer.

2021-12-01 05:46 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
It should not have permission issue, I will try to repro that later.

2021-12-01 07:17 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
Change it to:
```cmake
file(CHMOD "${WEBRTC_SOURCE_PATH}" PERMISSIONS)
file(RENAME "${WEBRTC_SOURCE_PATH}" "${SOURCE_PATH}/src/external/webrtc")
```
And try again?

2021-12-01 09:17 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
IIUC these files come from a source directory. RENAME from source dir is not an option, it breaks at least `--editable` builds.

2021-12-01 15:04 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
Right. I guess the source is still available for editable builds, just not in the expected place... What do you think @JackBoosY ?

2021-12-01 15:20 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
But the key of JackBoosY's proposal is to handle the whole folder at once, instead of globbing individual files.
The problem with the target is that it may already exists. You may need to remove it first.

2021-12-02 05:53 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
There are many such examples in vcpkg, please refer to https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/soqt/portfile.cmake

2021-12-02 07:00 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
... with the rename wisely guarded by a `if(NOT EXISTS <destination>)`.

2021-12-03 10:00 UTC, JackBoosY commented
Ping for reply.

2021-12-03 19:44 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
Having some trouble with this. The destination always exists, since its a submodule that hasn't been populated. Furthermore, if I remove it first, I still get permission problems trying to rename, even with file(CHMOD <path> PERMISSIONS OWNER_WRITE)

2021-12-03 20:30 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
I see, the submodules aren't in 1.60 version of soqt. So, I don't think this rename method works with submodules.

2021-12-06 07:33 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
So what's the solution here?

2021-12-06 07:49 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
If the directory always exists, you might perhaps check if a particular file from the submodule (e.g. CMakeLists.txt?) exists, and `REMOVE_RECURSE` the destination dir before `RENAME`.

2021-12-06 08:34 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
> If the directory always exists, you might perhaps check if a particular file from the submodule (e.g. CMakeLists.txt?) exists, and REMOVE_RECURSE the destination dir before RENAME.

If the version is mismatched, we should use the correct version.

2021-12-06 08:38 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +endforeach()
How can the version be mismatched here?
- submodule checkout. This isn't done IIUC.
- change of submodule version, in editable mode. Well, if you use editable mode, you must be aware of this IMO.

2021-12-10 02:22 UTC, JackBoosY approved these changes

2021-12-10 03:45 UTC, BillyONeal commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
It seems like this should be its own port rather than effectively vendoring it?

2021-12-10 04:26 UTC, BillyONeal commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
(What if 2 ports do this, will they get ABI mismatched mess of webrtc?)

2021-12-10 14:40 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
GameNetworkingSockets uses only a subset of the webrtc source; basically a custom build of it. It cannot use a shared or static library of webrtc directly.

2021-12-13 23:20 UTC, BillyONeal commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
Does the port take steps to work side by side with webrtc? (If a webrtc port gets added will `vcpkg install gamenetworkingsockets webrtc` explode?)

Sorry for pushing on this but vendored dependencies are one of our most insidious timebombs that break customers when they try to use 2 things and that fails with "impossible" errors at runtime.

2021-12-30 18:37 UTC, JackBoosY commented
Ping for response.

2022-01-03 14:37 UTC, eddiejames commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
Sorry for the delay. Yes, the port should work side by side since the webrtc code since gamenetworkingsockets only builds a subset of the webrtc library called "webrtc-lite" So no other port that wants to use webrtc should even see that library.

2022-01-07 07:22 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
Ping @BillyONeal for reply.

2022-01-14 19:02 UTC, fletcherdvalve commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
What should I do to fix this?  I'm working right now on getting all configured properly with regard to vcpkg and want to fix all the things about the way my project is configured so that it plays nice.

Context: we only need a really small subset of webrtc, the NAT traversal bit.  We don't need SIP, audio drivers, video codes, encryption, DTLS, etc, etc.  The structure of their library is layered very beautifully; if it weren't for one single file, I actually wouldn't need to make any changes at all, and the linker wouldn't pull in all that stuff I don't need.  But the way this one particular file is written, it cannot determine at link time the code isn't needed.  So I needed to a small amount of surgery on that one file, hence the vendoring.

I always statically link the webrtc-lite lib I build, so there shouldn't be any clash of symbol names if my lib is dynamically linked.  But if mine is statically linked, then you could not also statically link webrtc.


So what are my options?

- When building through vcpkg I could just ignore this bloat.  I don't actually need to change any behaviour, my edits were strictly to fix the linker problems.
- I could just remove the webrtc feature from the vcpkg version for now, and if you need that support you can't use the version from vcpkg, you need to build manually.

Side note: I also could use some guidance fulfilling the "don't use features to implement alternatives" rule.  The alternatives I am using features for are to select the crypto backend.  (I notice that the examples of grandfathered projects that violate this rule are also using features for this exact same purpose.)  I guess in the short term I could simply not support any other crypto backend besides openssl, and if you want libsodium or bcrypt, you just have to build manual?

Side note 2: I readily confess to a low skill level when it comes to both cmake and vcpkg, so any advice is appreciated.

2022-01-18 07:29 UTC, JackBoosY commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
Ping @BillyONeal for reply.

2022-01-20 07:25 UTC, BillyONeal commented on ports/gamenetworkingsockets/portfile.cmake
> +if (USE_STEAMWEBRTC)
>Context: we only need a really small subset of webrtc, the NAT traversal bit. We don't need SIP, audio drivers, video codes, encryption, DTLS, etc, etc. The structure of their library is layered very beautifully; if it weren't for one single file, I actually wouldn't need to make any changes at all, and the linker wouldn't pull in all that stuff I don't need. But the way this one particular file is written, it cannot determine at link time the code isn't needed. So I needed to a small amount of surgery on that one file, hence the vendoring.

The issue is that including that file anywhere stomps on those symbols, so if someone wants to build a program that uses real webrtc in addition to gamenetworkingsockets, they get link errors, silent ABI breaks, etc. This is a C++ limitation, not a vcpkg limitation.

Have you tried submitting the changes you need upstream? It could be done as a feature to disable the things you don't need in webrtc.

>I always statically link the webrtc-lite lib I build

That isn't a thing if the customer static links on Windows, or a thing ever on the other platforms. POSIX process-wide symbol table means you don't get to firewall symbols like that.

> I guess in the short term I could simply not support any other crypto backend besides openssl, and if you want libsodium or bcrypt, you just have to build manual?

That's right. You can provide extra code in your portfile.cmake to make it someone to use an overlay port to select something else.

2022-03-18 07:41 UTC, JackBoosY commented
@eddiejames Any progress here?

2022-03-18 13:51 UTC, eddiejames commented
> @eddiejames Any progress here?

I'm not in a position to do the kind of refactoring necessary to fix the webrtc conflict, I think. Was hoping @fletcherdvalve would have some ideas. I guess I could try using upstream webrtc when building with vcpkg

2022-03-21 20:06 UTC, fletcherdvalve commented
An upcoming version will have a custom ICE client.  We might continue to support WebRTC, and do so "properly".  But I don't want to invest any more time in the current situation, so I think for now, WebRTC support when building the library using vcpkg will just not be not supported

Also, see https://github.com/microsoft/vcpkg/pull/23043.

2022-03-25 20:30 UTC, eddiejames commented
@BillyONeal @JackBoosY  I see there is outstanding issues with pulling in webrtc to vcpkg (https://github.com/microsoft/vcpkg/issues/6205). So adding that as a port doesn't seem possible right now. Given that, is this current solution acceptable? (I'll rebase if so)

2022-03-26 00:15 UTC, BillyONeal commented
> @BillyONeal @JackBoosY I see there is outstanding issues with pulling in webrtc to vcpkg (#6205). So adding that as a port doesn't seem possible right now. Given that, is this current solution acceptable? (I'll rebase if so)

Doesn't the current solution still break webrtc customers in vcpkg? I don't think the problem that only one webrtc can exist in the results is fixed.

2022-03-26 00:17 UTC, BillyONeal commented
> Doesn't the current solution still break webrtc customers in vcpkg? I don't think the problem that only one webrtc can exist in the results is fixed.

Sorry, I think I got confused with another PR, looking again.

2022-03-26 00:22 UTC, BillyONeal commented on ports/gamenetworkingsockets/vcpkg.json
>    "version": "1.3.0",
Is this still the right version number now?

2022-03-26 00:36 UTC, BillyONeal commented on ports/gamenetworkingsockets/portfile.cmake
> +        REF 30a3e787948dd6cdd541773101d664b85eb332a6
I assume now that gamenetworkingsockets is 1.4 this ref needs to be changed?

2022-03-26 00:49 UTC, BillyONeal commented
/azp run

2022-03-26 00:56 UTC, BillyONeal commented
OK, to sum up the situation:

* ValveSoftware/GameNetworkingSockets wants to use the NAT traversial component of WebRTC
* WebRTC is a huge library with a bunch of stuff for doing real time conferencing over the internet, including video codecs and similar.
* WebRTC is part of the Chromium project, so creating a port for it is 'annoying', and also likely would have its own conflicts with the port `chromium-base`.

Unfortunately I think vendoring it would still create conflicts with anyone else who were using the WebRTC stuff, at least as far as I can tell. (Again, the symbols owned by WebRTC, when put into the linker, will conflict with any other copies that may be at different versions)

I think that still leaves us with the current solution being a problem. *However*, if the webrtc symbols are 'firewalled' / not exported from GameNetworkingSockets when built as a DLL, that would be OK, since it wouldn't create any intersection between this port and some other use of webrtc. Is that the case, that the webrtc stuff aren't part of GameNetworkingSockets' exported interface? If so, we could allow this vendoring if and only if GameNetworkingSockets is built as a DLL, on Windows. (I think there may be a way to do such firewalling on MacOS as well, but I don't have another example of a port doing that today to look to)

2022-03-28 14:17 UTC, eddiejames commented
> However, if the webrtc symbols are 'firewalled' / not exported from GameNetworkingSockets when built as a DLL, that would be OK, since it wouldn't create any intersection between this port and some other use of webrtc. Is that the case, that the webrtc stuff aren't part of GameNetworkingSockets' exported interface? If so, we could allow this vendoring if and only if GameNetworkingSockets is built as a DLL, on Windows.

OK, fair enough. I don't think this can meet those requirements, so I'll go ahead and close this. Thanks for the feedback everyone. Hopefully we can get the P2P support in vcpkg later.

2022-03-28 14:17 UTC, closed without merging

2022-03-28 17:56 UTC, fletcherdvalve commented
>if the webrtc symbols are 'firewalled' / not exported from GameNetworkingSockets when built as a DLL, that would be OK, since it wouldn't create any intersection between this port and some other use of webrtc. Is that the case, that the webrtc stuff aren't part of GameNetworkingSockets' exported interface?

Yes, WebRTC is just used under the hood and so symbols *could* be made private.  So this could work on Windows as you describe.  (I think it might already...would have to double-check.)

However, I'm really not inclined to pursue this much further.  We are working on our own ICE client, which would make the functionality available without WebRTC, and I don't think people really care about WebRTC, they mainly just want P2P functionality.  When that happens, the value of having a version of the lib that uses a lean version of WebRTC seems low and not worth maintaining.  Making it work through vpc officially, but only on windows, seems low value.  If we cared about continuing to allow people to select WebRTC as their ICE client, instead of ours, and we wanted to allow them to do that through vpc, then I would probably use the lib in the "regular" way, getting rid of the vendoring.  That would take some work to get up-to-date -- the version we are vendoring is a bit old at this point.  But since this would be a runtime switch, we could make it a vpc "feature" without violating vpc best practices, which would be nice.

I like the sound of all that, but I doubt it will rise in value for us enough to warrant doing the work.  I would take a PR if somebody really cared about it, though.

2022-03-28 18:24 UTC, BillyONeal commented
Thanks for understanding and sorry for the runaround!

2022-05-17 17:32 UTC, zpostfacto commented on ports/gamenetworkingsockets/portfile.cmake
> +        REF 30a3e787948dd6cdd541773101d664b85eb332a6
We require a very specific version of webrtc, because we hack their code in very shameful ways.

That's why, I really don't think our webrtc support should be enabled as a vcpkg feature.  We are definitely not following best practices, and we would conflict with any other project that used webrtc.