[xxhash] Update to 0.8.1
microsoft/vcpkg pull request #21761
Opened 2021-11-29 22:34 UTC by RT222

Update the xxhash port from 0.8.0 to 0.8.1.

Changelog : https://github.com/Cyan4973/xxHash/releases/tag/v0.8.1

2021-11-30 02:24 UTC, JonLiu1993 requested changes

2021-11-30 02:24 UTC, JonLiu1993 commented on ports/xxhash/portfile.cmake
>      PREFER_NINJA
```suggestion
    SOURCE_PATH "${SOURCE_PATH}/cmake_unofficial"
```

2021-11-30 02:24 UTC, JonLiu1993 commented on ports/xxhash/vcpkg.json
> +  "version-string": "0.8.1",
```suggestion
  "version": "0.8.1",
```

2021-12-01 10:25 UTC, JonLiu1993 approved these changes

2021-12-01 10:26 UTC, JonLiu1993 approved these changes

2021-12-02 03:22 UTC, merged

2021-12-02 03:22 UTC, BillyONeal commented
Thanks for both the update and the modernization!