UPDATE Qt-Advanced-Docking-System to v3.7.2
microsoft/vcpkg pull request #21801
Opened 2021-12-01 16:50 UTC by vincent-nv

**Describe the pull request**

- #### What does your PR fix?  
UPDATE Qt-Advanced-Docking-System to v3.7.2

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
x64-windows, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  IDN

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
vcpkg x-add-version done

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-02 05:56 UTC, JackBoosY commented
Thanks for your contributor.
Please sign CLA first.

2021-12-02 07:24 UTC, vincent-nv commented
CLA signed

2021-12-02 07:29 UTC, JackBoosY requested changes

2021-12-02 07:29 UTC, JackBoosY commented on ports/qt-advanced-docking-system/vcpkg.json
> +  "version-string": "3.7.2",
```suggestion
  "version": "3.7.2",
```
Same with you previous PR 😄

2021-12-02 08:35 UTC, JackBoosY requested changes

2021-12-02 08:35 UTC, JackBoosY commented on ports/qt-advanced-docking-system/vcpkg.json
>    "dependencies": [
Also, you need add the following code:
```json
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
```

2021-12-06 08:37 UTC, JackBoosY requested changes

2021-12-06 08:37 UTC, JackBoosY commented on ports/qt-advanced-docking-system/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/qtadvanceddocking TARGET_PATH share/qtadvanceddocking)
```suggestion
vcpkg_cmake_config_fixup(PACKAGE_NAME qtadvanceddocking CONFIG_PATH lib/cmake/qtadvanceddocking)
```

2021-12-07 02:46 UTC, JackBoosY approved these changes

2021-12-07 02:46 UTC, JackBoosY commented
LGTM.

2021-12-07 04:18 UTC, merged

2021-12-07 04:18 UTC, BillyONeal commented
Thanks for the update!