[qjsonwebtoken] New port for Qt/JWT support
microsoft/vcpkg pull request #21852
Opened 2021-12-04 14:16 UTC by kafeg

New port for Qt/JWT support

2021-12-04 20:19 UTC, cenit commented
shall you export unofficial targets for downstream library consumption?

2021-12-04 21:06 UTC, kafeg commented
> shall you export unofficial targets for downstream library consumption?

Sorry I'm not sure i understand you question correctly. The lib for now supports only static build without extra exports for dlls and like that, so in this PR i marked it as static only.

2021-12-04 21:59 UTC, cenit commented
i mean in cmakelists, export targets and create a port config… so that downstream projects can do a find_package(qjsonwebtoken) and a target_link_library(…)

2021-12-05 19:18 UTC, kafeg commented
It's a very tiny lib, includes already in vcpkg includes dir and it's enough just to link lib itself to the project.

I notified the lib maintainer and if he will would like to change it to support full cmake build i think he can do that.

2021-12-06 05:56 UTC, JackBoosY requested changes

2021-12-06 05:56 UTC, JackBoosY commented on ports/qjsonwebtoken/vcpkg.json
> +  "supports": "!uwp",
```suggestion
  "supports": "!uwp",
  "license": "MIT",
```

2021-12-06 05:56 UTC, JackBoosY commented on ports/qjsonwebtoken/CMakeLists.txt
> +add_library( qjsonwebtoken STATIC src/QJsonWebToken src/qjsonwebtoken.h src/qjsonwebtoken.cpp )
I think the author wants it to be used as source code, so here we should use `INTERFACE` instead of `STATIC`, and we should export this target for downstream use. See
https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/tinyxml/CMakeLists.txt#L25-L40

2021-12-06 05:56 UTC, JackBoosY commented on ports/qjsonwebtoken/portfile.cmake
> +    #    allow-build-static.patch
```suggestion
```

2021-12-06 05:56 UTC, JackBoosY commented on ports/qjsonwebtoken/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```suggestion
```

2021-12-06 09:11 UTC, kafeg commented
Thank you guys for comments, review and samples. Now I understand what i should to do and made changes.

2021-12-06 09:43 UTC, JackBoosY requested changes

2021-12-06 09:43 UTC, JackBoosY commented on ports/qjsonwebtoken/CMakeLists.txt
> +generate_export_header(unofficial-qjsonwebtoken BASE_NAME qjsonwebtoken)
Maybe we should provide all the headers instead of this.

2021-12-06 09:43 UTC, JackBoosY commented on ports/qjsonwebtoken/CMakeLists.txt
> +        $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
```suggestion
```
Since it's a interface library, we may not need this.

2021-12-06 09:45 UTC, kafeg commented on ports/qjsonwebtoken/CMakeLists.txt
> +generate_export_header(unofficial-qjsonwebtoken BASE_NAME qjsonwebtoken)
I provided other headers just the same way as in tinyxml with HEADERS env var which used below in `install(FILES ${HEADERS} ...`

2021-12-07 02:21 UTC, JackBoosY commented on ports/qjsonwebtoken/CMakeLists.txt
> +generate_export_header(unofficial-qjsonwebtoken BASE_NAME qjsonwebtoken)
I still think it's incorrect.
We should only provide the headers which upstream provided.
Any reason to do that?

2021-12-07 08:30 UTC, kafeg commented on ports/qjsonwebtoken/CMakeLists.txt
> +generate_export_header(unofficial-qjsonwebtoken BASE_NAME qjsonwebtoken)
Please check it now)

2021-12-07 09:57 UTC, JackBoosY requested changes

2021-12-07 09:57 UTC, JackBoosY commented on ports/qjsonwebtoken/CMakeLists.txt
> +add_library(unofficial-qjsonwebtoken ${SOURCES} )
```suggestion
add_library(unofficial-qjsonwebtoken INTERFACE ${SOURCES} )
```

2021-12-07 11:15 UTC, kafeg commented on ports/qjsonwebtoken/CMakeLists.txt
> +add_library(unofficial-qjsonwebtoken ${SOURCES} )
Can we avoid this? This change breaks the lib build.

2021-12-08 10:13 UTC, kafeg commented on ports/qjsonwebtoken/CMakeLists.txt
> +add_library(unofficial-qjsonwebtoken ${SOURCES} )
Sorry i definitely don't understand sense of this. Now lib builds staticaly and has all headers in right places. So, what exatly wrong there?

2021-12-09 02:39 UTC, JackBoosY commented
@kafeg Can you please test the usage?

2021-12-10 09:49 UTC, kafeg commented
> @kafeg Can you please test the usage?

It doesn't work in my case unfortunately in this config.

Anyway, i found a problem in this lib which breaks parsing of JWT tokens generated by another implimentations so it's not so usable for now. I propose to close and hold this until that will be fixed. As a good replacement i found in vcpkg port jwt-cpp.

2021-12-10 09:50 UTC, JackBoosY commented
Okay, feel free to reopen this PR.

2021-12-10 09:50 UTC, closed without merging