[tensorflow-common] remove single quotes from vcpkg flags
microsoft/vcpkg pull request #21869
Opened 2021-12-05 22:52 UTC by daschuer

They are escaped like '\'-mtune=native\''  which leads to a compiler error:
cc: error: unrecognized command line option '-mtune=native'
Set via: set(VCPKG_CXX_FLAGS "-mtune=native")

- #### What does your PR fix?  
 compiling with custom flags set via VCPKG_CXX_FLAGS and friends

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  `Yes`

2021-12-06 02:54 UTC, JackBoosY commented on ports/tensorflow-common/tensorflow-common.cmake
> -			list(APPEND COPTS "--copt='${OPT}'")
Why our pipeline tests didn't figure that out?

2021-12-06 05:05 UTC, dg0yt commented on ports/tensorflow-common/tensorflow-common.cmake
> -			list(APPEND COPTS "--copt='${OPT}'")
Good question. But these single quotes are shell syntax  and not entirely portable. YMMV.

2021-12-06 07:34 UTC, daschuer commented on ports/tensorflow-common/tensorflow-common.cmake
> -			list(APPEND COPTS "--copt='${OPT}'")
> Why our pipeline tests didn't figure that out?

Because there is no triplet in the pipeline which makes use of VCPKG_CXX_FLAGS or friends.

2021-12-06 07:43 UTC, daschuer commented
Unfortunately the pipeline is still failing.
Probably unrelated. I have original discovered it here: https://github.com/microsoft/vcpkg/pull/21790

Where is fails in the same way:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64039&view=logs&j=21e04d2e-bc14-5d6e-7914-b7708563a1ce&t=f24f25f4-e0f7-5ef7-8a8f-8c1f7db3f313

My lokal build is at least starting with this patch, but is killed later due to an out of memory situation > 16 GB. Can this also be an out if memory issue?

2021-12-06 08:33 UTC, JackBoosY commented
> Unfortunately the pipeline is still failing.
Probably unrelated. I have original discovered it here: #21790

Yes, see #21758.

2021-12-06 08:33 UTC, JackBoosY commented on ports/tensorflow-common/tensorflow-common.cmake
> -			list(APPEND COPTS "--copt='${OPT}'")
We should re-test it after fix #21758 first.

2021-12-08 11:08 UTC, jgehw commented
@daschuer Which OS are you working on -- Linux/macOS or Windows? I'm asking this because I assume that on Linux/macOS the single quotes are unnecessary, lead to errors, and should be removed as you did, whereas on Windows the single quotes should be consumed the wrapping `bash -c "..."` call, and removing them should break COPTs containing spaces (on Linux/macOS spaces should be auto-escaped by cmake, which doesn't work on Windows because of the wrapping `bash -c "..."` call). So, we might need an `if(VCPKG_TARGET_IS_WINDOWS) ... else() ... endif()` around your fix.

> My lokal build is at least starting with this patch, but is killed later due to an out of memory situation > 16 GB. Can this also be an out if memory issue?

Yes, tensorflow needs more than 60GB on my systems...

2021-12-09 02:08 UTC, JackBoosY commented
Depends on #21912.

2021-12-09 11:43 UTC, daschuer commented
@jgehw I am working normally on Linux and use GitHub workflows for MacOs and windows. 

I just did a check on Windows 10: 

using x64-windows with 
```
set(VCPKG_CXX_FLAGS "/Zc:__cplusplus /fp:fast")
set(VCPKG_C_FLAGS "/Zc:__cplusplus /fp:fast")
````

This becomes without the patch:

```
211209 09:59:34.340:I 199 [com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start] starting local subprocess #44, argv: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351...p:fast /std:c++14 /Zc:__cplusplus /fp:fast /Fobazel-out/x64_windows-dbg/bin/external/com_google_protobuf/_objs/protoc/main.obj /c external/com_google_protobuf/src/google/protobuf/compiler/main.cc
```

Ans with this Patch: 
```
211209 11:32:29.769:I 191 [com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start] starting local subprocess #327, argv: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351...td:c++14 /Zc:__cplusplus /fp:fast /Fobazel-out/x64_windows-dbg/bin/external/llvm-project/llvm/_objs/tblgen/AsmMatcherEmitter.obj /c external/llvm-project/llvm/utils/TableGen/AsmMatcherEmitter.cpp
```

You see It is working even with spaces. 

Do you have a different use case in mind?

2021-12-09 11:46 UTC, daschuer commented
This requires now also a update of vcpkg_acquire_msys.cmake because a referenceed package was is no longer available.

2021-12-09 13:50 UTC, jgehw commented
> Do you have a different use case in mind?

Spaces between options are no problem, the cmake code
```
		foreach(OPT IN LISTS VCPKG_C_FLAGS VCPKG_C_FLAGS_DEBUG)
			list(APPEND COPTS "--copt='${OPT}'")
		endforeach()
```
should make `--copt='/Zc:__cplusplus' --copt='/fp:fast'` out of it.

I had a use case in mind with a space within an option (not space separating options), some like `/I "C:\Program Files\..."`. If this becomes `--copt=/I --copt=C:\Program Files\...` I would assume that it stops working. Unfortunately I neither have a concrete use case nor sufficient diskspace on Windows to test it. I just remember adding these single quotes long time back because some other user had a use case at that time...

2021-12-09 16:41 UTC, daschuer commented
VCPKG_CXX_FLAGS is a space separated list. So you need to quote the path with spaces initially.
This applies to any target triplet. 
So there is no reason for special case windows here.

2021-12-09 20:24 UTC, jgehw commented
> VCPKG_CXX_FLAGS is a space separated list. So you need to quote the path with spaces initially. This applies to any target triplet. So there is no reason for special case windows here.

Ok, from https://vcpkg.readthedocs.io/en/latest/users/triplets/#vcpkg_cxx_flags it was not clear to me that it must be a space separated string, e.g., `set(VCPKG_CXX_FLAGS "/I \"C:\\Program Files\\...\"")` and **not** a cmake list `set(VCPKG_CXX_FLAGS /I "C:\\Program Files\\...")`. If you use the latter, the quotes get consumed by the `foreach()` loop and are finally missing in the command executed. Without explicit definition as space separated string in the docs, I'd assume the cmake default, i.e., the parameter being a cmake list. Either I missed something or the docs need to be written more clearly...

2021-12-09 22:07 UTC, daschuer commented
x64_osx is failing unrelated with 
```
Failed to build numpy
``

2021-12-14 01:56 UTC, JackBoosY commented
Can you please merge to master?

Thanks.

2021-12-15 07:21 UTC, JackBoosY requested changes
Please run command `vcpkg x-add-version --overwrite-version --all` then commit the changes.

2021-12-17 07:37 UTC, JackBoosY approved these changes
LGTM.

2021-12-17 18:22 UTC, merged

2021-12-17 18:22 UTC, BillyONeal commented
Thanks for the fix!