Fix ompl config
microsoft/vcpkg pull request #21864
Opened 2021-12-05 07:34 UTC by Ace314159

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #21863

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-06 03:00 UTC, JackBoosY approved these changes

2021-12-06 03:07 UTC, JonLiu1993 requested changes

2021-12-06 03:07 UTC, JonLiu1993 commented on ports/ompl/vcpkg.json
>    "version-string": "1.5.1",
```suggestion
  "version": "1.5.1",
```

2021-12-06 05:52 UTC, JonLiu1993 approved these changes

2021-12-07 05:51 UTC, merged

2021-12-07 05:51 UTC, BillyONeal commented
Thanks for the fix :)