add: gmsh
microsoft/vcpkg pull request #21896
Opened 2021-12-07 10:30 UTC by xarthurx

**Describe the pull request**

- #### What does your PR fix?  
  add `Gmsh` lib per request: https://github.com/microsoft/vcpkg/issues/4930

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  I'm really not good at this and don't know how to do it...

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `YES`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  `YES`

2021-12-07 12:04 UTC, xarthurx commented
`vcpkg.exe x-add-version gmsh` keep saying cannot find gmsh port...
Not sure why.

2021-12-08 02:01 UTC, JonLiu1993 requested changes

2021-12-08 02:01 UTC, JonLiu1993 commented on ports/gmsh/portfile.cmake
> +# file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/gmsh RENAME copyright)
Could you please clarify why these contents are commented out

2021-12-08 06:38 UTC, JackBoosY commented
I will take over this PR.

2021-12-08 09:16 UTC, JackBoosY commented
@xarthurx  Does my changes meet you requirement?

2021-12-08 09:44 UTC, JackBoosY commented
The upstream did not add cross-platform code for uwp, so drop it.

2021-12-09 09:19 UTC, xarthurx commented
> @xarthurx Does my changes meet you requirement?

Yes, thank you so much for the quick response!

2021-12-09 09:58 UTC, JackBoosY approved these changes

2021-12-09 09:58 UTC, JackBoosY commented
Already tested all features on x86-windows.

2021-12-10 02:24 UTC, BillyONeal commented on ports/gmsh/portfile.cmake
> +if (ENABLE_BUILD_DYNAMIC)
I think this is always false? Should this be `BUILD_SHARED_LIBS` or `BUILD_SHARED` from 12?

2021-12-10 02:44 UTC, JackBoosY commented on ports/gmsh/portfile.cmake
> +if (ENABLE_BUILD_DYNAMIC)
Ahh I forgot to remove this.
Thanks for noticed me.

2021-12-10 02:44 UTC, JackBoosY requested changes

2021-12-10 02:44 UTC, JackBoosY commented on ports/gmsh/portfile.cmake
> +endif()
```suggestion
```

2021-12-10 02:51 UTC, JackBoosY requested changes

2021-12-10 02:51 UTC, JackBoosY commented on versions/g-/gmsh.json
> +    }
```suggestion
      "git-tree": "992d5523675b2e8483db92e258b17ad357349085",
      "version": "4.9.0",
      "port-version": 0
    }
```

2021-12-10 02:52 UTC, JackBoosY approved these changes

2021-12-10 02:52 UTC, JackBoosY commented
Ping @BillyONeal for review again.

2021-12-10 04:14 UTC, BillyONeal commented on versions/g-/gmsh.json
> +    {
This should only add 1 version

2021-12-10 04:17 UTC, BillyONeal commented on ports/gmsh/portfile.cmake
> +        -DGMSH_RELEASE=ON
Is there some kind of rationale as to which of these are turned on vs. off? I don't really know how to evaluate if this is correct or not but I see yet another scientific compute project that depends on the universe of optional dependencies and am scared 👻

Also, is there a good way to make sure if/when the version is updated that we know what the new optional dependencies are to turn off?

2021-12-10 04:23 UTC, BillyONeal commented on ports/gmsh/portfile.cmake
> +vcpkg_copy_tools(TOOL_NAMES gmsh AUTO_CLEAN)
Hmmm ... is this a library or is just an executable at the end named gmsh? Note that we do not want vcpkg to compete with apt or similar; ports should provide libraries for use or be a build tool in service of one of those libraries, if that makes sense.

2021-12-10 05:51 UTC, JackBoosY commented on versions/g-/gmsh.json
> +    {
Already fixed.

2021-12-10 05:54 UTC, JackBoosY commented on ports/gmsh/portfile.cmake
> +        -DGMSH_RELEASE=ON
According to the [CMakeLists.txt](https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/CMakeLists.txt#L118-143):
```cmake
if(NOT GMSH_RELEASE)
  find_package(Git)
  if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} log -1 --format=%h
                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR} ERROR_QUIET
                    OUTPUT_VARIABLE GIT_COMMIT_HASH
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
  endif()
  if(GIT_COMMIT_HASH)
    set(GMSH_EXTRA_VERSION "${GMSH_EXTRA_VERSION}-git-${GIT_COMMIT_HASH}")
  endif()
  set(GMSH_EXTRA_VERSION_TEXI "${GMSH_EXTRA_VERSION_TEXI} (development version)")
endif()

set(GMSH_SHORT_VERSION
    "${GMSH_MAJOR_VERSION}.${GMSH_MINOR_VERSION}.${GMSH_PATCH_VERSION}")
set(GMSH_VERSION "${GMSH_SHORT_VERSION}${GMSH_EXTRA_VERSION}")
set(GMSH_SHORT_LICENSE "GNU General Public License")

set(GMSH_GITLAB_PREFIX "https://gitlab.onelab.info/gmsh/gmsh")
if(GMSH_RELEASE)
  string(REPLACE "\." "_" GMSH_SHORT_VERSION_ ${GMSH_SHORT_VERSION})
  set(GMSH_GITLAB_PREFIX "${GMSH_GITLAB_PREFIX}/blob/gmsh_${GMSH_SHORT_VERSION_}")
else()
  set(GMSH_GITLAB_PREFIX "${GMSH_GITLAB_PREFIX}/blob/master")
endif()
```
This option is used to get gmsh version.
Since we use the release, so it should be turn on.

2021-12-10 05:55 UTC, JackBoosY commented on ports/gmsh/portfile.cmake
> +vcpkg_copy_tools(TOOL_NAMES gmsh AUTO_CLEAN)
This port provides both library and executable, and they have the same name.

2021-12-10 21:57 UTC, BillyONeal commented on ports/gmsh/portfile.cmake
> +        -DGMSH_RELEASE=ON
@JackBoosY Perhaps I chose a bad example option. There are a ton of options in this list that look like they control optional dependencies, and I don't know how to evaluate how or why various ones of those are turned on. (Of course the first option in the list is the one that just tells it it's a release copy :()

2021-12-10 21:57 UTC, BillyONeal commented on ports/gmsh/portfile.cmake
> +vcpkg_copy_tools(TOOL_NAMES gmsh AUTO_CLEAN)
Sounds good, thanks!

2021-12-10 21:58 UTC, BillyONeal requested changes
Can you group together and/or explain why the optional dependencies that are turned on are selected and how we are supposed to evaluate that they are set correctly in future updates?

2021-12-16 10:32 UTC, JonLiu1993 commented
@xarthurx ,Can you reply to BillyONeal's review suggestion?

2021-12-16 11:17 UTC, xarthurx commented
> Can you group together and/or explain why the optional dependencies that are turned on are selected and how we are supposed to evaluate that they are set correctly in future updates? With that understanding I think we should merge this, thanks for your help!


For those detailed options, could we just use the default options here below?
https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/CMakeLists.txt

There is a `${DEFAULT}` setting and several `${ENABLE_xxx}` settings.

2021-12-17 02:40 UTC, JackBoosY commented
I will continue this PR today.

2021-12-17 07:05 UTC, JackBoosY commented
@BillyONeal Done.

2021-12-17 07:22 UTC, merged

2021-12-17 07:22 UTC, BillyONeal commented
> @BillyONeal Done.

Thanks for digging!