Patch 1
microsoft/vcpkg pull request #21915
Opened 2021-12-08 09:58 UTC by LiarMaiq

Update co to v2.0.3

2021-12-08 10:00 UTC, JonLiu1993 commented
@LiarMaiq ,Thanks for your pr ,please sign in CLA first

2021-12-08 10:02 UTC, JonLiu1993 commented
please run command "./vcpkg x-add-version co --overwrite-version" then commit again

2021-12-09 01:56 UTC, JonLiu1993 requested changes

2021-12-09 01:56 UTC, JonLiu1993 commented on ports/co/portfile.cmake
> +#        fix-event-destruct.patch
```suggestion
```

2021-12-09 01:56 UTC, JonLiu1993 commented on ports/co/portfile.cmake
> +#        fix-event-destruct.patch
@LiarMaiq , These patches have been applied to the current version, so we should delete them instead of blocking them

2021-12-09 01:56 UTC, JonLiu1993 commented on ports/co/vcpkg.json
>    "port-version": 1,
```suggestion
```

2021-12-09 01:56 UTC, JonLiu1993 commented on ports/co/vcpkg.json
>    "port-version": 1,
When we update port version we should remove the "port version" filed

2021-12-09 02:25 UTC, JonLiu1993 commented
@LiarMaiq ,Please run command "./vcpkg x-add-version co --overwrite-version" then command again

2021-12-09 05:56 UTC, JonLiu1993 approved these changes

2021-12-09 06:15 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2021-12-10 01:28 UTC, BillyONeal requested changes

2021-12-10 01:28 UTC, BillyONeal commented on ports/co/portfile.cmake
> -        fix-event-destruct.patch
I double checked that this patch has landed and was https://github.com/idealvin/co/commit/cf1f4b9804d7e02900800aab5b9590daabc5a29d

2021-12-10 01:28 UTC, BillyONeal commented on ports/co/portfile.cmake
> -        install-dll.patch
I don't see a change upstream corresponding to this patch. Can you confirm why it is no longer needed?

2021-12-10 05:37 UTC, LiarMaiq commented on ports/co/portfile.cmake
> -        install-dll.patch
Yes, 2.0.3 No need for these patches, thanks.

2021-12-10 06:30 UTC, JonLiu1993 commented on ports/co/portfile.cmake
> -        install-dll.patch
@BillyONeal ,I checked that this patch has landed and was https://github.com/idealvin/co/commit/1027a1507bffa049b0934e9225c1229f5ddf6ab5#

2021-12-10 22:00 UTC, BillyONeal commented on ports/co/portfile.cmake
> -        install-dll.patch
Ah, thank you, it wasn't mentioned in the release notes.

2021-12-10 22:00 UTC, merged

2021-12-10 22:00 UTC, BillyONeal commented
Thanks for the help with the update!