[colmap] Fix LNK2019 in x64-windows-static triplet
microsoft/vcpkg pull request #21937
Opened 2021-12-09 08:17 UTC by Cheney-W

- #### What does your PR fix?  
  Fixes #21744 

All features passed with following triplets:
x86-windows 
x64-windows 
x64-windows-static

2021-12-10 02:39 UTC, JackBoosY requested changes
According to the link error:
```
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsOpenProfileFromFile referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsOpenProfileFromMem referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsCloseProfile referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsCreate_sRGBProfile referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsCreateTransform referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsDeleteTransform referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
rawd.lib(dcraw_fileio.cpp.obj) : error LNK2019: unresolved external symbol cmsDoTransform referenced in function "protected: void __cdecl LibRaw::apply_profile(char const *,char const *)" (?apply_profile@LibRaw@@IEAAXPEBD0@Z)
```
There are 2 situation:
1. libraw's cmake config file doesn't contains `lcms2`.
2. colmap should uue libraw's cmake config file to find libraw.

2021-12-11 05:23 UTC, Sousuke13 commented
Build successful. Thank you for the quick solution.

2022-01-03 22:41 UTC, BillyONeal approved these changes

2022-01-06 04:56 UTC, JackBoosY approved these changes

2022-01-06 21:46 UTC, strega-nil-ms commented
Thanks!

2022-01-06 21:46 UTC, merged