[xtensor-io ] updates to 0.13.0
microsoft/vcpkg pull request #21946
Opened 2021-12-09 15:11 UTC by tatatupi

Updates xtensor-io to 0.13.0

2021-12-10 02:32 UTC, JonLiu1993 requested changes

2021-12-10 02:32 UTC, JonLiu1993 commented on ports/xtensor-io/vcpkg.json
>    "port-version": 1,
```suggestion
```

2021-12-10 02:34 UTC, JonLiu1993 commented
@tatatupi , Thanks for your pr, please run command "./vcpkg x-add-version xtensor-io --overwrite-version" then commit again.

2021-12-10 12:19 UTC, tatatupi commented
> @tatatupi , Thanks for your pr, please run command "./vcpkg x-add-version xtensor-io --overwrite-version" then commit again.

I just ran it and nothing happened. I guess it is a lib that no other depends on?

2021-12-13 09:18 UTC, JonLiu1993 approved these changes

2021-12-13 19:56 UTC, merged

2021-12-13 19:56 UTC, BillyONeal commented
Thanks for the update!

2021-12-14 07:44 UTC, aizuon commented
The hash has not been updated,  unable to build the package:

[DEBUG] Downloading https://github.com/xtensor-stack/xtensor-io/archive/ffada938383b0f24c9e0b07cea7d5780057e1d96.tar.gz
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/xtensor-stack/xtensor-io/archive/ffada938383b0f24c9e0b07cea7d5780057e1d96.tar.gz ]
       File path : [ D:\vcpkg\downloads\xtensor-stack-xtensor-io-ffada938383b0f24c9e0b07cea7d5780057e1d96.tar.gz.7116.part ]
   Expected hash : [ d7c5c85489aea9b9d8af7ee33a43dd8ab888e7f03da8b533ace39e143f89acbae4fe88bb10253931a3cc44041e1532bd76483686f7f20c00e2850647a574349c ]
     Actual hash : [ ce5d085e500ef7043eb51538cab9a53c857983ac43e392cd65958c76fcde3ddb00161097cb70d334fa7d12af12e8109bb958b51f39afd9eeb60bb3421424058e ]

2021-12-14 07:49 UTC, JonLiu1993 commented
@tatatupi ,Thanks for your reminder, I will submit a new pr to update the hash value