[readline] New readline-osx port for MacOS
microsoft/vcpkg pull request #22000
Opened 2021-12-12 23:03 UTC by zekoz

**Describe the pull request**

- #### What does your PR fix?  
Adding readline package for Mac

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
x64-osx-rel, x64-osx-dbg

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
 Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-13 02:37 UTC, JonLiu1993 requested changes

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/CMakeLists.txt
> +    parens.c
```suggestion
    keymaps.c
    vi_mode.c
    parens.c
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/CMakeLists.txt
> +    terminal.c
```suggestion
    kill.c
    undo.c
    macro.c
    input.c
    callback.c
    terminal.c
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/CMakeLists.txt
> +    nls.c
```suggestion
    xmalloc.c
    history.c
    histsearch.c
    histexpand.c
    histfile.c
    nls.c
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/CMakeLists.txt
> +    xfree.c
```suggestion
    search.c
    shell.c
    savestring.c
    tilde.c
    text.c
    misc.c
    compat.c
    mbutil.c
    xfree.c
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/config.h DESTINATION ${SOURCE_PATH})
```suggestion
file(COPY "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DESTINATION "${SOURCE_PATH}")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/config.h" DESTINATION "${SOURCE_PATH}")
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/portfile.cmake
> +    PREFER_NINJA
```suggestion
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/portfile.cmake
> +file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/include/readline)
```suggestion
file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/include/readline")

```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/portfile.cmake
> +file(COPY ${headers} DESTINATION ${CURRENT_PACKAGES_DIR}/include/readline)
```suggestion
file(COPY "${headers}" DESTINATION "${CURRENT_PACKAGES_DIR}/include/readline")
```

2021-12-13 02:37 UTC, JonLiu1993 commented on ports/readline-osx/vcpkg.json
> +  "version-string": "8.1",
```suggestion
  "version": "8.1",
```

2021-12-13 02:37 UTC, JonLiu1993 commented on scripts/ci.baseline.txt
> +readline-osx:x86-windows=fail
@zekoz, thanks for your PR, if upstream does not support these triplets, we should use the "support" field in vcpkg instead of ci.baseline.txt

2021-12-13 03:10 UTC, zekoz commented on scripts/ci.baseline.txt
> +readline-osx:x86-windows=fail
Ah thanks, that's a better way to do it.

2021-12-13 08:31 UTC, dg0yt commented
Port `readline` is described as `"GNU readline and history libraries"`. So why is this implemented as a separate port, and not using upstream's build system?
win32 is a different case, because it actually uses different sources.

2021-12-13 14:54 UTC, zekoz commented
> Port `readline` is described as `"GNU readline and history libraries"`. So why is this implemented as a separate port, and not using upstream's build system? win32 is a different case, because it actually uses different sources.

Now it is readline. Will keep using cmake because https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#prefer-using-cmake

2021-12-14 02:22 UTC, JackBoosY commented
Readline was moved to `readline-win32` in PR https://github.com/microsoft/vcpkg/pull/3504.
@qmfrederik I wish to listen some suggestions.

2021-12-14 02:23 UTC, JackBoosY requested changes

2021-12-14 02:23 UTC, JackBoosY commented on ports/readline/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
If this part only support OSX, we should create a new port `readline-osx`.

2021-12-14 04:09 UTC, zekoz commented on ports/readline/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
In that case, we have this version https://github.com/microsoft/vcpkg/commit/aadb0856cda2054c6109a493aa0c0714e0092c47 I'll let the maintainers choose which they like best.

2021-12-14 06:02 UTC, JackBoosY commented on ports/readline/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
@zekoz I think that's good.

2021-12-15 16:31 UTC, zekoz commented
@JonLiu1993 could you take another look, and make a decision whether we need a readline-osx dependency port or whether to put the build into the readline port?

2021-12-16 02:55 UTC, JackBoosY commented
@zekoz Please follow my suggestion.

2021-12-16 04:49 UTC, zekoz commented
Ok @JackBoosY , pushed that older commit back to my branch.

2021-12-16 05:15 UTC, dg0yt commented
Back to start. Please update the port descriptions to make clear that "readline" is a "metapackage", and that "readline-osx" is GNU readline for osx. Think of the visibility for users, e.g. on https://vcpkg.io/en/packages.html.

I still think it would be better to not add a custom build system. It is fragmentation. It creates a maintenance burden. It is not necessary.

2021-12-16 05:45 UTC, JonLiu1993 approved these changes

2021-12-16 05:57 UTC, JackBoosY commented
> Back to start. Please update the port descriptions to make clear that "readline" is a "metapackage", and that "readline-osx" is GNU readline for osx. Think of the visibility for users, e.g. on https://vcpkg.io/en/packages.html.
> 
> I still think it would be better to not add a custom build system. It is fragmentation. It creates a maintenance burden. It is not necessary.

If we ensure that the cmake configuration is the same as the make configuration, we can accept the use of cmake.
The source of this port contains configure and makefile.

2021-12-16 05:58 UTC, JonLiu1993 commented
@zekoz ,Readline was moved to 'readline-win32', I think we need a readline-osx dependency port .

2021-12-16 06:29 UTC, dg0yt commented
> Readline was moved to 'readline-win32'

This was a fork of GNU readline 5.0 for windows. Not updated since 2017.

> The source of this port contains configure and makefile.

So GNU readline version 8.1 can be build with `vcpkg_configure_make` and friends. Across platforms, maybe even for windows.

2021-12-16 15:14 UTC, zekoz commented
@JonLiu1993 do you want to me to reset my branch back to f99800c or are there still issues remaining?

2021-12-17 01:46 UTC, JonLiu1993 commented
> @JonLiu1993 do you want to me to reset my branch back to [f99800c](https://github.com/microsoft/vcpkg/commit/f99800c586dc4e55749322ec5b55874aae52982a) or are there still issues remaining?

I think this pr is ready to merge, of course my colleague will review it again before the final merge

2021-12-17 06:41 UTC, BillyONeal approved these changes
I'm not a huge fan of checking in a config file like this but that's what readline-win32 was already doing.

2021-12-17 06:43 UTC, BillyONeal commented
> So GNU readline version 8.1 can be build with `vcpkg_configure_make` and friends. Across platforms, maybe even for windows.

I think we can merge this but would much prefer this solution suggested by @dg0yt . Would you be willing to try that?

2021-12-17 18:16 UTC, BillyONeal commented
(Will merge this Dec 23 if no response)

2021-12-18 11:25 UTC, dg0yt commented
Upstream readline still doesn't support windows. Not even mingw. It lacks at least signal handling and DLL exports. 

It also needs termcap or curses, but isn't prepared to work with pdcurses. Is termcap a system library on macOS?

readline-win32 contains changes for signal handling and exports (https://github.com/lltcggie/readline/blob/vs/src/readline/5.0/readline-5.0/patches/readline-5.0-src.diff). This could probably be adjusted for readline 8.1 but I assume it is not easy to make a derived change part of upstream or of vcpkg, due to contribution policies.

2021-12-20 02:38 UTC, JackBoosY requested changes

2021-12-20 02:38 UTC, JackBoosY commented on ports/readline-osx/CMakeLists.txt
> +add_definitions(-D_CRT_SECURE_NO_WARNINGS)
OSX don't need this.

2021-12-20 02:38 UTC, JackBoosY commented on ports/readline-osx/CMakeLists.txt
> +endif()
I think there are some problems here.

2021-12-20 02:51 UTC, JonLiu1993 commented on versions/r-/readline.json
> +      "version-string": "0",
"version-string": "0" , Doesn't look right here

2021-12-29 00:11 UTC, BillyONeal commented on ports/readline-osx/CMakeLists.txt
> +add_definitions(-D_CRT_SECURE_NO_WARNINGS)
That's true, but as a definition it's unlikely to break anything.

2021-12-29 00:11 UTC, BillyONeal commented on ports/readline-osx/CMakeLists.txt
> +endif()
Can you be more specific?

2021-12-29 00:24 UTC, BillyONeal commented on ports/readline-osx/CMakeLists.txt
> +add_definitions(-D_CRT_SECURE_NO_WARNINGS)
Oh wait I see this port is only osx so yeah this is vestigal.

2021-12-29 00:27 UTC, BillyONeal commented on versions/r-/readline.json
> +      "version-string": "0",
I agree but that's the existing behavior of the `readline` port. It's somewhat OK given that it's a metaport anyway.

2021-12-29 01:44 UTC, merged

2021-12-29 01:44 UTC, BillyONeal commented
Thanks for the improvements!

2021-12-29 04:44 UTC, JackBoosY commented on ports/readline-osx/CMakeLists.txt
> +endif()
I can confirm that those 2 macros are only supported in Windows. I checked the source code.

2021-12-30 05:44 UTC, JackBoosY commented on ports/readline-osx/CMakeLists.txt
> +endif()
In _readline.h_ or _rlstdc.h_:
```cpp
#if (defined __WIN32__) || (defined _WIN32)
# ifdef BUILD_READLINE_DLL
#  define READLINE_DLL_IMPEXP     __DLL_EXPORT__
# elif defined(READLINE_STATIC)
#  define READLINE_DLL_IMPEXP      
# elif defined (USE_READLINE_DLL)
#  define READLINE_DLL_IMPEXP     __DLL_IMPORT__
# elif defined (USE_READLINE_STATIC)
#  define READLINE_DLL_IMPEXP      
# else /* assume USE_READLINE_DLL */
#  define READLINE_DLL_IMPEXP     __DLL_IMPORT__
# endif
#else /* __WIN32__ */
# define READLINE_DLL_IMPEXP  
#endif
```
You can see thoses 2 macros are only avaliable in Windows build.

2022-01-07 02:15 UTC, BillyONeal commented on ports/readline-osx/CMakeLists.txt
> +endif()
I see you already addressed in https://github.com/microsoft/vcpkg/pull/22321