[abseil] Upgrade to 2021.1102
microsoft/vcpkg pull request #22017
Opened 2021-12-14 08:02 UTC by jiayuehua

**Describe the pull request**
upgrade abseil to version 2021.1102
- #### What does your PR fix?  
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all >, <No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes >

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-14 08:23 UTC, JonLiu1993 requested changes

2021-12-14 08:23 UTC, JonLiu1993 commented on ports/abseil/portfile.cmake
> +if (NOT VCPKG_TARGET_IS_WINDOWS)
@jiayuehua ,Thanks for your pr, could you please keep the original format of EOL for this poftfile.cmake, maybe LF?

2021-12-14 08:29 UTC, jiayuehua commented on ports/abseil/portfile.cmake
> +if (NOT VCPKG_TARGET_IS_WINDOWS)
ok, I will fix it.

2021-12-16 01:52 UTC, JonLiu1993 approved these changes

2021-12-16 23:52 UTC, merged

2021-12-16 23:52 UTC, BillyONeal commented
Thanks for the update!