update libdatachannel to 0.16.0
microsoft/vcpkg pull request #22048
Opened 2021-12-16 07:34 UTC by evaldemar

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-16 08:20 UTC, JonLiu1993 commented
@evaldemar ,Thanks for your pr, could you please sign CLA first?

2021-12-16 08:22 UTC, JonLiu1993 requested changes

2021-12-16 08:22 UTC, JonLiu1993 commented on ports/libdatachannel/vcpkg.json
>    "port-version": 1,
```suggestion
```

2021-12-20 06:22 UTC, JonLiu1993 approved these changes

2021-12-22 04:06 UTC, merged

2021-12-22 04:06 UTC, BillyONeal commented
Thanks for the update!