Dev/lily wang/issue22057
microsoft/vcpkg pull request #22062
Opened 2021-12-17 10:18 UTC by LilyWangLL

- #### What does your PR fix?  
  Fixes #22057

Fix ports which depend on libmysql build error:
```
Could not find a package configuration file provided by
  "unofficial-libmysql" with any of the following names:

    unofficial-libmysqlConfig.cmake
    unofficial-libmysql-config.cmake
```

2021-12-17 20:20 UTC, dg0yt reviewed
If possible, please try to make this port work also with single-config build, i.e. with absence of `debug` paths.

2021-12-17 20:20 UTC, dg0yt commented on ports/libmysql/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME unofficial-libmysql CONFIG_PATH share/libmysql/unofficial-libmysql)
Given the previous changes, you also need to replace `share/libmysql` with `share/${PORT}` here.

2021-12-17 20:20 UTC, dg0yt commented on ports/libmysql/portfile.cmake
> +file(RENAME "${CURRENT_PACKAGES_DIR}/debug/${PORT}" "${CURRENT_PACKAGES_DIR}/debug/share/${PORT}")
Does libmysql actually find all the files in `share/${PORT}`, given that the rename is done after build?

2021-12-18 09:43 UTC, cloudsnake commented
thanks!
libmysql is ok!
but 
./vcpkg install poco[mysql]:x64-windows-static 
no error,no PocoDataMysqlmt.lib file!

2021-12-22 07:29 UTC, LilyWangLL commented on ports/libmysql/portfile.cmake
> +file(RENAME "${CURRENT_PACKAGES_DIR}/debug/${PORT}" "${CURRENT_PACKAGES_DIR}/debug/share/${PORT}")
I just move config files and target files to `unofficial-libmysql`, other files in `share/${PORT}` keep the original structure.

2021-12-22 09:01 UTC, JackBoosY requested changes

2021-12-22 09:01 UTC, JackBoosY commented on ports/poco/portfile.cmake
> +    file(COPY "${SOURCE_PATH}/Data/include" DESTINATION ${CURRENT_PACKAGES_DIR})
```suggestion
    file(COPY "${SOURCE_PATH}/Data/include" DESTINATION "${CURRENT_PACKAGES_DIR}")
```
etc.

2021-12-22 09:01 UTC, LilyWangLL commented
> thanks! libmysql is ok! but ./vcpkg install poco[mysql]:x64-windows-static no error,no PocoDataMysqlmt.lib file!

After new change, PocoDataMysqlmt.lib can install correct.

2021-12-22 15:05 UTC, JackBoosY approved these changes

2021-12-23 03:53 UTC, merged

2021-12-23 03:53 UTC, BillyONeal commented
Thanks for the fix!