Upgrade libjpeg-turbo to 2.1.2
microsoft/vcpkg pull request #22156
Opened 2021-12-22 13:30 UTC by ahojnnes

2021-12-23 02:15 UTC, JonLiu1993 requested changes

2021-12-23 02:15 UTC, JonLiu1993 commented on ports/libjpeg-turbo/workaround_cmake_system_processor.patch
> -diff --git a/CMakeLists.txt b/CMakeLists.txt
@ahojnnes, thanks for your PR, I noticed that you deleted this patch, but I can't find the upstream application of this patch, can you find out the commit that applied this patch？

2021-12-23 02:15 UTC, JonLiu1993 commented on ports/libjpeg-turbo/portfile.cmake
>      PREFER_NINJA
```suggestion
    SOURCE_PATH "${SOURC E_PATH}"
```

2021-12-23 02:33 UTC, JonLiu1993 commented
CI failed on x64-uwp triplet and arm-uwp triplet:
````
CMake Error at CMakeLists.txt:57 (string):
  string no output variable specified

````

I think maybe we should revert this patch:
_ports/libjpeg-turbo/workaround_cmake_system_processor.patch_

2021-12-23 15:22 UTC, ahojnnes commented
@JonLiu1993 Addressed your comments. PTAL.

2021-12-24 01:43 UTC, JonLiu1993 approved these changes

2021-12-24 02:30 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2021-12-29 02:38 UTC, merged

2021-12-29 02:38 UTC, BillyONeal commented
Thanks for the update and merging the tricky patches!