Flash runtime extensions
microsoft/vcpkg pull request #22171
Opened 2021-12-23 09:03 UTC by al-sabr

**Describe the pull request**

- #### What does your PR fix?  
Windows port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Windows x86 & x64

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-23 09:42 UTC, JonLiu1993 commented
@al-sabr ,Thanks for your pr, could you please sign CLA first?

2021-12-23 09:50 UTC, al-sabr commented
> @al-sabr ,Thanks for your pr, could you please sign CLA first?

Wher ?

2021-12-23 09:52 UTC, JonLiu1993 commented
> > @al-sabr ,Thanks for your pr, could you please sign CLA first?
> 
> Where ?

There are hints above

2021-12-23 09:56 UTC, al-sabr commented
I've read and accepted! Thank you for feedback.

2021-12-23 10:21 UTC, JonLiu1993 requested changes

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/portfile.cmake
> +    REPO al-sabr/FlashRuntimeExtensions
@al-sabr, Thanks for your pr, why are we using a private repo, I can’t find this repo on github

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/portfile.cmake
> +    PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
```

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/portfile.cmake
> +vcpkg_install_cmake()
```suggestion
vcpkg_cmake_install()
```

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/vcpkg.json
> +  "port-version": 0,
```suggestion
```

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/vcpkg.json
> +  "supports": "!(linux | osx)",
```suggestion
  "supports": "!(linux | osx)",
  "dependencies": [
   {
     "name": "vcpkg-cmake",
     "host": true
   },
   {
     "name": "vcpkg-cmake-config",
     "host": true
   }
  ]

```

2021-12-23 10:21 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/README.md
> +# flash-runtime-extensions
We do not recommend adding README.md to vcpkg，please remove it

2021-12-23 10:45 UTC, JonLiu1993 requested changes

2021-12-23 10:45 UTC, JonLiu1993 commented on versions/f-/flash-runtime-extensions.json
> +      "version-string": "2021-12-23",
Why is version-string here, we should be consistent with the version type in vcpkg.json

2021-12-23 14:19 UTC, maksqwe commented on ports/flash-runtime-extensions/vcpkg.json
> +  "homepage": "https://github.com/facebookresearch/flashlight",
Incorrect homepage

2021-12-23 21:36 UTC, al-sabr commented on ports/flash-runtime-extensions/vcpkg.json
> +  "homepage": "https://github.com/facebookresearch/flashlight",
See https://github.com/al-sabr/vcpkg/commit/84b753917345327829695b91ffd6e348adeef754

2021-12-24 02:20 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/vcpkg.json
> +  "homepage": "https://github.com/facebookresearch/flashlight",
@al-sabr, It looks like this homepage is not correct, it should be this:
https://github.com/al-sabr/FlashRuntimeExtensions

2021-12-24 03:11 UTC, JonLiu1993 commented
@al-sabr ,Cou you confirm the reason why CI failed in arm64-windows and arm64-uwp in upstream?

2021-12-24 10:22 UTC, al-sabr commented
İ really don't know since I have no arm setup and I cannot see the error logs.

2021-12-24 11:02 UTC, maksqwe commented
So do you have source? Or you have headers and .lib file for win32/win64 only?

2021-12-24 12:33 UTC, PhoebeHui commented
@al-sabr, it looks the post build step failed, See the CI failures:
```
Starting package 3/3: flash-runtime-extensions:arm64-windows
Building package flash-runtime-extensions[core]:arm64-windows...
-- Downloading https://github.com/al-sabr/FlashRuntimeExtensions/archive/v2.3.tar.gz -> al-sabr-FlashRuntimeExtensions-v2.3.tar.gz...
-- Extracting source D:/downloads/al-sabr-FlashRuntimeExtensions-v2.3.tar.gz
-- Using source at D:/buildtrees/flash-runtime-extensions/src/v2.3-a47b7db0b9.clean
-- Configuring arm64-windows
-- Building arm64-windows-dbg
-- Building arm64-windows-rel
-- Installing: D:/packages/flash-runtime-extensions_arm64-windows/share/flash-runtime-extensions/copyright
-- Performing post-build validation
The following files were built for an incorrect architecture:

    D:\packages\flash-runtime-extensions_arm64-windows\debug\lib\FlashRuntimeExtensions.lib
Expected arm64, but was: x64

    D:\packages\flash-runtime-extensions_arm64-windows\lib\FlashRuntimeExtensions.lib
Expected arm64, but was: x64

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    C:\a\1\s\ports\flash-runtime-extensions\portfile.cmake
-- Performing post-build validation done
Error: Building package flash-runtime-extensions:arm64-windows failed with: POST_BUILD_CHECKS_FAILED
Elapsed time for package flash-runtime-extensions:arm64-windows: 2.364 s

Triplet: arm64-windows
Total elapsed time: 17.69 s
```

2021-12-24 12:35 UTC, PhoebeHui commented on ports/flash-runtime-extensions/README.md
> +CMake port of FlashRuntimeExtensions for vcpkg
Does this require?

2021-12-24 12:45 UTC, PhoebeHui commented
BTW, you can check the logs from CI pipeline:

Install steps:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64933&view=logs&j=84da4f4a-968a-5b5c-16e9-f444c845396d&t=80e5e0c8-bb3b-5216-9f3f-2618d4e9f3f4
![image](https://user-images.githubusercontent.com/20694052/147353610-306fd440-82d2-46c2-a3bc-496f551ab348.png)


Download build logs from https://dev.azure.com/vcpkg/public/_build/results?buildId=64933&view=artifacts&pathAsName=false&type=publishedArtifacts


![image](https://user-images.githubusercontent.com/20694052/147353455-c4b18c74-bc00-4a82-8a4d-e9dea09915c6.png)

2021-12-24 14:20 UTC, al-sabr commented
> So do you have source? Or you have headers and .lib files for win32/win64 only?

This is the official link https://github.com/al-sabr/FlashRuntimeExtensions

2021-12-24 14:23 UTC, al-sabr commented
At the moment we need to add in this conversation the team behind the development of the SDK. I will create a link to for them to this thread so that they can also share thoughts.

2021-12-24 20:53 UTC, al-sabr commented
Is there a way in the json files to specify that arm32 and arm6 is not supported so that it is bypassed for the moment?

2021-12-24 22:38 UTC, al-sabr commented on ports/flash-runtime-extensions/README.md
> +CMake port of FlashRuntimeExtensions for vcpkg
Yes! I will put more details in the Future to explain but right now it is rudimentary.

2021-12-25 14:29 UTC, al-sabr commented on ports/flash-runtime-extensions/README.md
> +CMake port of FlashRuntimeExtensions for vcpkg
Yes it does ... I will improve it in Future with more details.

2021-12-28 02:29 UTC, JonLiu1993 commented
/azp run

2021-12-28 02:51 UTC, JonLiu1993 commented
@al-sabr , it looks the post build step failed, 
See the CI failures:
x64-linux:
````
-- Installing: /mnt/vcpkg-ci/packages/flash-runtime-extensions_x64-linux/share/flash-runtime-extensions/copyright
-- Performing post-build validation
There should be no empty directories in /mnt/vcpkg-ci/packages/flash-runtime-extensions_x64-linux
The following empty directories were found:

    /mnt/vcpkg-ci/packages/flash-runtime-extensions_x64-linux/debug

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    /agent/_work/1/s/ports/flash-runtime-extensions/portfile.cmake
-- Performing post-build validation done
Error: Building package flash-runtime-extensions:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Elapsed time for package flash-runtime-extensions:x64-linux: 1.27 s
````

x64-osx:
````
-- Installing: /Users/vagrant/Data/packages/flash-runtime-extensions_x64-osx/share/flash-runtime-extensions/copyright
-- Performing post-build validation
There should be no empty directories in /Users/vagrant/Data/packages/flash-runtime-extensions_x64-osx
The following empty directories were found:

    /Users/vagrant/Data/packages/flash-runtime-extensions_x64-osx/debug

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    /Users/vagrant/Data/work/1/s/ports/flash-runtime-extensions/portfile.cmake
-- Performing post-build validation done
Error: Building package flash-runtime-extensions:x64-osx failed with: POST_BUILD_CHECKS_FAILED
Elapsed time for package flash-runtime-extensions:x64-osx: 2.266 s
````

2021-12-28 18:22 UTC, al-sabr commented
Applied the change.

2021-12-29 08:28 UTC, JonLiu1993 commented
@al-sabr ,it looks the post build step failed, you can check the logs from CI pipeline:

Install steps:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64933&view=logs&j=84da4f4a-968a-5b5c-16e9-f444c845396d&t=80e5e0c8-bb3b-5216-9f3f-2618d4e9f3f4

![Capture3](https://user-images.githubusercontent.com/63675417/147642216-6dc7341f-3acc-4491-accb-10c8e43048ee.PNG)

2021-12-30 10:39 UTC, al-sabr commented
> @al-sabr ,it looks the post build step failed, you can check the logs from CI pipeline:
> 
> Install steps:
> https://dev.azure.com/vcpkg/public/_build/results?buildId=64933&view=logs&j=84da4f4a-968a-5b5c-16e9-f444c845396d&t=80e5e0c8-bb3b-5216-9f3f-2618d4e9f3f4
> 
> ![Capture3](https://user-images.githubusercontent.com/63675417/147642216-6dc7341f-3acc-4491-accb-10c8e43048ee.PNG)
> 

Unfortunately Adobe doesn't provide any debug versions of the libraries. See thread:

2022-01-03 23:02 UTC, al-sabr commented
I cannot provide the debug versions of the libraries. They are not available in the SDK.

2022-01-03 23:03 UTC, al-sabr commented
> So do you have source? Or you have headers and .lib files for win32/win64 only?

Yes only for win32/win64 nothing else.

2022-01-05 11:25 UTC, JonLiu1993 commented
> I cannot provide the debug versions of the libraries. They are not available in the SDK.

@al-sabr , Thanks for your diligent investigation, I will discuss this issue with my colleague

2022-01-06 06:06 UTC, JackBoosY requested changes

2022-01-06 06:06 UTC, JackBoosY commented on ports/flash-runtime-extensions/portfile.cmake
> +    REPO al-sabr/FlashRuntimeExtensions
Does this extension only provide binary? Can we use source code to compile? Is it provided by adobe?

2022-01-06 10:34 UTC, al-sabr commented on ports/flash-runtime-extensions/portfile.cmake
> +    REPO al-sabr/FlashRuntimeExtensions
The headers are open but the binaries are closed source. See previous threads for clarifications.

2022-01-06 10:37 UTC, al-sabr commented on ports/flash-runtime-extensions/portfile.cmake
> +    REPO al-sabr/FlashRuntimeExtensions
See https://github.com/airsdk/Adobe-Runtime-Support/issues/1490

2022-01-06 11:15 UTC, JackBoosY commented on ports/flash-runtime-extensions/portfile.cmake
> +#set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
```suggestion
set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
```

2022-01-07 05:48 UTC, JackBoosY commented on ports/flash-runtime-extensions/portfile.cmake
> +set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
```suggestion
set(VCPKG_POLICY_MISMATCHED_NUMBER_OF_BINARIES enabled)
```

2022-01-07 05:50 UTC, JackBoosY requested changes

2022-01-07 05:50 UTC, JackBoosY commented on ports/flash-runtime-extensions/vcpkg.json
> +  "supports": "!(arm64 | (arm & uwp))",
```suggestion
  "supports": "!(arm | uwp)",
```

2022-01-07 05:50 UTC, JackBoosY commented on ports/flash-runtime-extensions/vcpkg.json
> +  "supports": "!(arm64 | (arm & uwp))",
All the arm or uwp triplets are not supported, right?

2022-01-07 19:19 UTC, al-sabr commented on ports/flash-runtime-extensions/vcpkg.json
> +  "supports": "!(arm64 | (arm & uwp))",
Right

2022-01-10 03:00 UTC, JonLiu1993 commented
@al-sabr ，Please run command "./vcpkg x-add-version flash-runtime-extensions --overwrite-version" and commit again

2022-01-10 20:52 UTC, al-sabr commented
> vcpkg x-add-version flash-runtime-extensions --overwrite-version

Done and pushed !

2022-01-11 07:31 UTC, JackBoosY commented on ports/flash-runtime-extensions/vcpkg.json
> +  "supports": "!(arm64 | (arm & uwp))",
@al-sabr So please consider my suggestion.

2022-01-19 21:15 UTC, al-sabr commented
İs this finally going to be accepted?

2022-01-20 05:34 UTC, JackBoosY commented
> İs this finally going to be accepted?

See [my comment](https://github.com/microsoft/vcpkg/pull/22171#discussion_r781817529).

2022-01-20 07:05 UTC, al-sabr commented
> > İs this finally going to be accepted?
> 
> See [my comment](https://github.com/microsoft/vcpkg/pull/22171#discussion_r781817529).

Resolved from my side.

2022-01-20 07:05 UTC, JonLiu1993 commented on ports/flash-runtime-extensions/vcpkg.json
> +  "supports": "!(arm64 | (arm & uwp))",
@al-sabr , Please consider the suggestion

2022-01-20 07:22 UTC, JonLiu1993 approved these changes

2022-01-20 08:38 UTC, JackBoosY approved these changes

2022-01-20 15:55 UTC, al-sabr commented
Is this finished?

2022-01-20 19:01 UTC, merged