[live555] Fix install head failed
microsoft/vcpkg pull request #22190
Opened 2021-12-24 09:10 UTC by JonLiu1993

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #17165

live555 install failed whit --head, Add this condition
````
if (WIN32)
    add_definitions(-DNO_GETIFADDRS)
endif(WIN32)
````
Fix the issue

2021-12-24 14:31 UTC, JackBoosY requested changes
I think we should also update this port, can you?

2021-12-27 07:13 UTC, JackBoosY commented on ports/live555/CMakeLists.txt
> +endif(WIN32)
In _groupsock/GroupsockHelper.cpp_ line 45:
```cpp
#ifndef NO_GETIFADDRS
#include <ifaddrs.h>
#include <net/if.h>
#endif
```

2021-12-27 07:16 UTC, JackBoosY requested changes
```cmake
vcpkg_download_distfile(ARCHIVE
    URLS "http://www.live555.com/liveMedia/public/live.2021.12.18.tar.gz"
    FILENAME "live.2021.12.18.tar.gz"
    SHA512 072ae92a1a63687e33c659627fbf562e6f2cdf73cf1c3199959aa3a713636ccd4113d56270c4793c86b42338000f180e16a7b2cf3d893402226a04360f8b2e97
)
```

2021-12-27 08:43 UTC, JackBoosY approved these changes

2021-12-28 23:04 UTC, BillyONeal commented
Thanks for the update, and investigation of the build failure!

2021-12-28 23:04 UTC, merged