gtk 3.24.30 port
microsoft/vcpkg pull request #22201
Opened 2021-12-25 20:10 UTC by mkhon

New port: gtk 3.24.30 (some software still requires GTK3)

- #### What does your PR fix?  

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-26 04:46 UTC, nlogozzo commented
Could we see a gtkmm3 port as well?

2021-12-26 10:00 UTC, mkhon commented
Sure, I will work on gtk3mm port

2021-12-26 13:56 UTC, nlogozzo commented
Cool, thanks :)

2021-12-27 06:12 UTC, JonLiu1993 commented
@mkhon ,Thanks for your pr, for the x86-windows error, you can run command "./vcpkg x-add-version gtk3 --overwrite-version " and commit again after you finish your pr.
````
Found the following errors:
##[error]versions/g-/gtk3.json(2,): error : While reading versions for port gtk3 from file: version/g-/gtk3.json
File declares version `3.24.30` with SHA: 8fcadeff3c2eba6e6cd20b1158014c8f308dea54
But local port with the same version has a different SHA: 4fb3acb0474e205624b3a2b4c1f02a45468be19c
Please update the port's version fields and then run:

    vcpkg x-add-version gtk3
    git add versions
    git commit -m "Update version database"

to add a new version.

To attempt to resolve all errors at once, run:

    vcpkg x-add-version --all

##[error]PowerShell exited with code '1'.

````
and This is the detail error log please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64967&view=artifacts&pathAsName=false&type=publishedArtifacts 

![Capture](https://user-images.githubusercontent.com/63675417/147440355-2dd68de1-6601-4c94-a618-6c326fe1334a.PNG)

2021-12-29 08:20 UTC, JonLiu1993 commented
@mkhon , it looks the post build step failed.
See the CI failures:
https://dev.azure.com/vcpkg/public/_build/results?buildId=65027&view=artifacts&pathAsName=false&type=publishedArtifacts

2021-12-30 10:30 UTC, JonLiu1993 commented
@mkhon ，It seems that the error has not been solved yet, here is the detailed error log
https://dev.azure.com/vcpkg/public/_build/results?buildId=65097&view=artifacts&pathAsName=false&type=publishedArtifacts

2022-01-04 12:27 UTC, JonLiu1993 approved these changes

2022-01-05 06:51 UTC, JonLiu1993 commented
@mkhon ,I encountered this error when verifying the feature, it seems that port pango does not have an introspection feature
./vcpkg install gtk3[*]:x64-windows
````
Package pango does not have a introspection feature
````

2022-01-05 09:55 UTC, mkhon commented
@JonLiu1993 introspection feature is added in #22200

2022-01-05 11:22 UTC, JonLiu1993 commented
Depends on pr #22200

2022-01-17 19:38 UTC, mkhon commented
@nlogozzo see #22598

2022-02-11 11:07 UTC, nlogozzo commented
What's the status on this?

2022-02-11 11:10 UTC, mkhon commented
I believe introspection feature was not tested because #22200 has not been merged yet

2022-02-21 07:23 UTC, mkhon commented
I updated this PR: introspection bits are removed as it seems that #22200 has stuck
depends:different-pr tag can now be removed and this port can hopefully be merged

2022-02-21 08:40 UTC, JonLiu1993 commented
Please run command "./vcpkg x-add-version gtk3 --overwrite-version" and commit again

2022-02-21 09:13 UTC, JonLiu1993 commented
@mkhon ,When I tested the features locally by the command "./vcpkg install gtk3[*]" but failed :
````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg
    Error code: 1
    See logs for more information:
      F:\test-pr\gtk\vcpkg\buildtrees\gtk3\package-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
  ports/gtk3/portfile.cmake:62 (vcpkg_install_meson)
  scripts/ports.cmake:145 (include)


Error: Building package gtk3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.

````
F:\test-pr\gtk\vcpkg\buildtrees\gtk3\package-x86-windows-dbg-err.log:
````

CreateProcess failed. Command attempted:
""F:\test-pr\gtk\vcpkg\downloads\tools\python\python-3.10.1-x86\python.exe" "F:\test-pr\gtk\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "exe" "--capture" "gtk\gtktypebuiltins.h" "--" "F:\test-pr\gtk\vcpkg\downloads\tools\python\python-3.10.1-x86\python.exe" "F:/test-pr/gtk/vcpkg/installed/x64-windows/tools/glib/glib-mkenums" "--template" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtktypebuiltins.h.template" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk-autocleanups.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkx-autocleanups.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk-a11y.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaboutdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccelgroup.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccellabel.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccelmap.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccessible.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkactionable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkactionbar.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkadjustment.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooser.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserwidget.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkapplication.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkapplicationwindow.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaspectframe.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkassistant.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbbox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbin.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbindings.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkborder.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbuilder.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbuildable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcalendar.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellarea.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellareacontext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellareabox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcelleditable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcelllayout.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderer.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendereraccel.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderercombo.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererpixbuf.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererprogress.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererspin.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererspinner.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderertext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderertoggle.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellview.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcheckbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcheckmenuitem.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkclipboard.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooser.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooserwidget.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooserdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorutils.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcombobox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcomboboxtext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcontainer.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcssprovider.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcsssection.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkdebug.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkdnd.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean [...]

2022-02-22 03:02 UTC, JonLiu1993 commented
@mkhon ,When I tested the features locally by command "./vcpkg install gtk[*] " but failed:
````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg
    Error code: 1
    See logs for more information:
      F:\test-pr\gtk\vcpkg\buildtrees\gtk3\package-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
  ports/gtk3/portfile.cmake:62 (vcpkg_install_meson)
  scripts/ports.cmake:145 (include)


Error: Building package gtk3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gtk3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gtk3]+Build+error
including:
  package: gtk3[core]:x86-windows -> 3.24.30
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 648993fac 2022-02-21 (20 hours ago)

````
F:\test-pr\gtk\vcpkg\buildtrees\gtk3\package-x86-windows-dbg-err.log
````

CreateProcess failed. Command attempted:
""F:\test-pr\gtk\vcpkg\downloads\tools\python\python-3.10.1-x86\python.exe" "F:\test-pr\gtk\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "exe" "--capture" "gtk\gtktypebuiltins.h" "--" "F:\test-pr\gtk\vcpkg\downloads\tools\python\python-3.10.1-x86\python.exe" "F:/test-pr/gtk/vcpkg/installed/x64-windows/tools/glib/glib-mkenums" "--template" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtktypebuiltins.h.template" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk-autocleanups.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkx-autocleanups.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk-a11y.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaboutdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccelgroup.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccellabel.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccelmap.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccessible.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkactionable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkactionbar.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkadjustment.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooser.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserwidget.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkapplication.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkapplicationwindow.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaspectframe.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkassistant.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbbox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbin.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbindings.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkborder.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbuilder.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbuildable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcalendar.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellarea.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellareacontext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellareabox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcelleditable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcelllayout.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderer.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendereraccel.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderercombo.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererpixbuf.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererprogress.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererspin.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererspinner.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderertext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderertoggle.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellview.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcheckbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcheckmenuitem.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkclipboard.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooser.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooserwidget.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooserdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorutils.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcombobox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcomboboxtext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcontainer.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcssprovider.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-w [...]

2022-02-22 06:41 UTC, JonLiu1993 commented
> @mkhon ,When I tested the features locally by command "./vcpkg install gtk[*] " but failed:
> 
> ```
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
>     Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
>     Working Directory: F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg
>     Error code: 1
>     See logs for more information:
>       F:\test-pr\gtk\vcpkg\buildtrees\gtk3\package-x86-windows-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
>   ports/gtk3/portfile.cmake:62 (vcpkg_install_meson)
>   scripts/ports.cmake:145 (include)
> 
> 
> Error: Building package gtk3:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
> Then check for known issues at:
>   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gtk3
> You can submit a new issue at:
>   https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gtk3]+Build+error
> including:
>   package: gtk3[core]:x86-windows -> 3.24.30
>     vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
>     vcpkg-scripts version: 648993fac 2022-02-21 (20 hours ago)
> ```
> 
> F:\test-pr\gtk\vcpkg\buildtrees\gtk3\package-x86-windows-dbg-err.log
> 
> ```
> 
> CreateProcess failed. Command attempted:
> ""F:\test-pr\gtk\vcpkg\downloads\tools\python\python-3.10.1-x86\python.exe" "F:\test-pr\gtk\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "exe" "--capture" "gtk\gtktypebuiltins.h" "--" "F:\test-pr\gtk\vcpkg\downloads\tools\python\python-3.10.1-x86\python.exe" "F:/test-pr/gtk/vcpkg/installed/x64-windows/tools/glib/glib-mkenums" "--template" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtktypebuiltins.h.template" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk-autocleanups.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkx-autocleanups.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtk-a11y.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaboutdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccelgroup.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccellabel.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccelmap.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaccessible.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkactionable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkactionbar.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkadjustment.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooser.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkappchooserwidget.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkapplication.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkapplicationwindow.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkaspectframe.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkassistant.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbbox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbin.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbindings.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkborder.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbuilder.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbuildable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcalendar.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellarea.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellareacontext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellareabox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcelleditable.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcelllayout.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderer.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendereraccel.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderercombo.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererpixbuf.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererprogress.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererspin.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrendererspinner.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderertext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellrenderertoggle.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcellview.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcheckbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcheckmenuitem.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkclipboard.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorbutton.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooser.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooserwidget.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorchooserdialog.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcolorutils.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcombobox.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcomboboxtext.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clean/gtk/gtkcontainer.h" "F:/test-pr/gtk/vcpkg/buildtrees/gtk3/x86-windows-dbg/../src/gtk+-3-4bfa5ce158.clea [...]

2022-03-18 08:35 UTC, JonLiu1993 commented
Ping @mkhon for response, Is work still being done for this PR?

2022-03-25 15:02 UTC, talregev commented
Thank you for this PR.

2022-03-25 19:58 UTC, talregev commented
@JonLiu1993 When I try 
`./vcpkg install gtk3[*]`
it install all without any problem. there is only core feature in the gtk. 
What os are you installing?

2022-03-28 07:52 UTC, JonLiu1993 commented
> @JonLiu1993 When I try `./vcpkg install gtk3[*]` it install all without any problem. there is only core feature in the gtk. What os are you installing?

@talregev ,Thanks for your reply, I tested all features on windows 10

2022-03-28 17:19 UTC, talregev commented
> > @JonLiu1993 When I try `./vcpkg install gtk3[*]` it install all without any problem. there is only core feature in the gtk. What os are you installing?
> 
> @talregev ,Thanks for your reply, I tested all features on windows 10

I tried on linux wsl, and I will try on windows 11.

2022-03-29 00:48 UTC, talregev commented
> > @JonLiu1993 When I try `./vcpkg install gtk3[*]` it install all without any problem. there is only core feature in the gtk. What os are you installing?
> 
> @talregev ,Thanks for your reply, I tested all features on windows 10

I have the same problem. The problem is it using mason with python script on the command line.
and The command line is too long. There is any way to solve it? to short it out?

2022-03-29 00:55 UTC, talregev commented
@JonLiu1993 
Can you take a look on this answer? 
https://stackoverflow.com/questions/43184251/cmake-command-line-too-long-windows?noredirect=1&lq=1

2022-03-29 08:27 UTC, JonLiu1993 commented
> @JonLiu1993 Can you take a look on this answer? https://stackoverflow.com/questions/43184251/cmake-command-line-too-long-windows?noredirect=1&lq=1

@talregev ,I have saw the answer, but I am not familiar makefile, could you please help test the awser if can apply this pr error?

2022-03-29 15:33 UTC, talregev commented
> have saw the answer, but I am not familiar makefile, could

I didn't succeeded to do the solution. it not a make file, it a meson with ninja. I don't know how to pass the meson, the ninja flags, and I am not sure ninja can do it with python call. 

So we need meson expert. 
@JackBoosY  @dg0yt 
Can you help?

2022-03-29 16:18 UTC, dg0yt commented
I'm not a meson expert.
But I can share my research:
- Same issue for port gtk: https://github.com/microsoft/vcpkg/issues/20472
  Linking to:
- Issue in meson: https://github.com/mesonbuild/meson/issues/6710
  And I will try to add another post there.

2022-03-29 16:52 UTC, Neumann-A commented
Maybe using the vcpkg-tool-ninja pr can solve the issue with the long cmd line?

2022-03-29 17:43 UTC, talregev commented
> Maybe using the vcpkg-tool-ninja pr can solve the issue with the long cmd line?

Can you try?

2022-03-29 18:42 UTC, dg0yt commented
> Maybe using the vcpkg-tool-ninja pr can solve the issue with the long cmd line?

More than 35000 characters? I didn't find any hint, that's why I didn't propose it. (I read about long file paths, but that's not the same as long command lines.)

2022-03-29 18:49 UTC, talregev commented
> > Maybe using the vcpkg-tool-ninja pr can solve the issue with the long cmd line?
> 
> More than 35000 characters? I didn't find any hint, that's why I didn't propose it. (I read about long file paths, but that's not the same as long command lines.)

These flags will not help? 
from here:
https://stackoverflow.com/questions/43184251/cmake-command-line-too-long-windows?noredirect=1&lq=1

SET(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS 1)
SET(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 1)

SET(CMAKE_C_RESPONSE_FILE_LINK_FLAG "@")
SET(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG "@")

SET(CMAKE_NINJA_FORCE_RESPONSE_FILE 1 CACHE INTERNAL "")

There is a way to tell ninja to do response file? 
https://ninja-build.org/manual.html

2022-03-29 19:13 UTC, dg0yt commented
It is meson, not cmake.

2022-03-30 03:23 UTC, talregev commented
> It is meson, not cmake.
Can we make vcpkg-tool-ninja to use response file for every command? 
https://ninja-build.org/manual.html

>rspfile, rspfile_content
if present (both), Ninja will use a response file for the given command, i.e. write the selected string (rspfile_content) to the given file (rspfile) before calling the command and delete the file after successful execution of the command.

2022-03-30 04:04 UTC, dg0yt commented
No.

2022-03-30 04:06 UTC, talregev commented
> No.

Do you have other solution? 
Are you waiting for meson to be fixed in their side?

2022-03-30 04:08 UTC, dg0yt commented
> > No.
> 
> Do you have other solution? Are you waiting for meson to be fixed in their side?

Yes, I have to wait for meson. Feel free to help there.

2022-03-30 04:09 UTC, talregev commented
> > > No.
> > 
> > 
> > Do you have other solution? Are you waiting for meson to be fixed in their side?
> 
> Yes, I have to wait for meson. Feel free to help there.

I am feel free to help here.

2022-04-30 07:40 UTC, talregev commented
@dg0yt @JackBoosY 
Can we make this port not for windows and not for mingw until this meson problem is solve?
For wxwidgets the gtk3 is needed only on linux.

2022-04-30 07:43 UTC, mkhon commented
The port is still usable on Windows even before meson issue is resolved: build in C:\vcpkg succeeds

2022-04-30 07:50 UTC, talregev commented
> The port is still usable on Windows even before meson issue is resolved: build in C:\vcpkg succeeds

I didn't succeed to build this port on windows, nor @JonLiu1993

2022-04-30 07:59 UTC, mkhon commented
> > The port is still usable on Windows even before meson issue is resolved: build in C:\vcpkg succeeds
> 
> I didn't succeed to build this port on windows, nor @JonLiu1993 I build it on `d:\src\vcpkg` More important I want to build it on the CI, that it have larger path.

What is your vcpkg root directory?

1) @JonLiu1993 has too long vcpkg root

2) I developed this port on Windows (the final goal was to have pygtk on Windows) and when I noticed this meson problem i just moved my vcpkg root to C:\vcpkg and it was enough

3) CI builds use even shorter paths (vcpkg root is just the root of a drive, like E:\) and they also succeed

2022-04-30 08:02 UTC, mkhon commented
> > The port is still usable on Windows even before meson issue is resolved: build in C:\vcpkg succeeds
> 
> I didn't succeed to build this port on windows, nor @JonLiu1993 I build it on `d:\src\vcpkg` More important I want to build it on the CI, that it have larger path.

Please use d:\vcpkg

2022-04-30 08:05 UTC, talregev commented
my root is `D:\src\vcpkg` 
1. ok.
2. ok.
3. In our CI is github action, the folder is much longer, and we clone it inside the repo automatic, and it not going to change. 
`D:\a\boinc\boinc\3rdParty\Windows\vcpkg\` Also like I say we don't need to compile gtk3 for windows because it not needed for wxwidgets on windows. So for us it ok.

2022-04-30 08:13 UTC, talregev commented
@mkhon @JonLiu1993 I succeeded to compile the gtk3 on `D:\vcpkg`.
I hope it will convince @JonLiu1993 to approve this PR like it is.

2022-04-30 11:59 UTC, talregev commented
@mkhon Can you rebase/merge from the master?

2022-05-01 13:50 UTC, dg0yt commented
If the windows issue is just path length, then
- the windows triplets could be added with `fail` to the CI baseline list.
- there should be an build time warning, as exists for other ports (e.g. qt5-base), using 
  `vcpkg_buildpath_length_warning(<INT>)`
- even on GH actions, the build root (!) could be overriden using variables or parameters.

2022-05-01 15:18 UTC, talregev commented
> * the windows triplets could be added with `fail` to the CI baseline list.

The build is working on the ci because it compile on `E:\vcpkg`?
Also I am request to rebase\merge to master to test this PR properly. Thank you.

2022-05-01 16:38 UTC, dg0yt commented
> The build is working on the ci because it compile on `E:\vcpkg`?

Yes, as @mkhon was pointing out in https://github.com/microsoft/vcpkg/pull/22201#issuecomment-1113944523 item 3.

2022-05-03 05:56 UTC, talregev commented
I rebase the master to this branch in my different branch I created for that. I test it and it working.
Too bad the author @mkhon is not so responsive. 
@JonLiu1993 @dg0yt
Can you review this PR again? For me everything is working. windows and linux. with limitation of short path. 
Thank you all.

2022-05-03 06:22 UTC, dg0yt commented
> Too bad the author @mkhon is not so responsive.

Too bad that the official reviewers didn't properly respond to @mkhon when he was active.

Anyways, it doesn't need to be rebased, and there are no merge conflicts. What should be done, if enabled for the fork, is that one of the official reviewer (e.g. @JonLiu1993) pushes a merge with master to the the fork. If this passes CI, the PR could be accepted.

2022-05-03 08:33 UTC, talregev commented
@JackBoosY can you help us here?

2022-05-04 10:46 UTC, mkhon commented
> > * the windows triplets could be added with `fail` to the CI baseline list.
> 
> The build is working on the ci because it compile on `E:\vcpkg`? Also I am request to rebase\merge to master to test this PR properly. Thank you.

CI uses even a shorter path (like E:\)

2022-05-04 10:47 UTC, mkhon commented
1) rebased to latest master

2) added build path length warning. I can't use vcpkg_buildpath_length_warning() because it recommends using C:\src\vcpkg which is too long for gtk3 build

2022-05-04 10:48 UTC, talregev commented
> 1. rebased to latest master
> 2. added build path length warning. I can't use vcpkg_buildpath_length_warning() because it recommends using C:\src\vcpkg which is too long for gtk3 build

Thank you!

2022-05-04 23:32 UTC, BillyONeal commented
1. Do gtk4 and gtk3 work "side by side" or does installing one exclude install of the other?
2. Can you apply these nitpick level changes or fix the PR to allow me to push such changes?

```
diff --git a/ports/gtk3/portfile.cmake b/ports/gtk3/portfile.cmake
index 2a45a3aef..ca826e634 100644
--- a/ports/gtk3/portfile.cmake
+++ b/ports/gtk3/portfile.cmake
@@ -1,9 +1,9 @@
 set(warning_length 8)
 string(LENGTH "${CURRENT_BUILDTREES_DIR}" buildtrees_path_length)
 if(buildtrees_path_length GREATER warning_length AND CMAKE_HOST_WIN32)
-        message(WARNING "${PORT}'s buildsystem uses very long paths and may fail on your system.\n"
-            "We recommend moving vcpkg to a short path such as 'C:\\vcpkg' or using the subst command."
-        )
+    message(WARNING "${PORT}'s buildsystem uses very long paths and may fail on your system.\n"
+        "We recommend moving vcpkg to a short path such as 'C:\\vcpkg' or using the subst command."
+    )
 endif()
 
 set(GTK_MAJOR_MINOR 3.24)
@@ -17,7 +17,7 @@ vcpkg_download_distfile(ARCHIVE
 
 vcpkg_extract_source_archive_ex(
     OUT_SOURCE_PATH SOURCE_PATH
-    ARCHIVE ${ARCHIVE}
+    ARCHIVE "${ARCHIVE}"
     PATCHES
         0001-build.patch
         0002-windows-sdk11.patch
@@ -33,9 +33,8 @@ vcpkg_add_to_path("${CURRENT_HOST_INSTALLED_DIR}/tools/gdk-pixbuf")
 vcpkg_add_to_path("${CURRENT_HOST_INSTALLED_DIR}/tools/gettext/bin")
 
 vcpkg_configure_meson(
-    SOURCE_PATH ${SOURCE_PATH}
+    SOURCE_PATH "${SOURCE_PATH}"
     OPTIONS
-        ${OPTIONS}
         -Dwayland_backend=false
         -Ddemos=false
         -Dexamples=false
@@ -48,10 +47,6 @@ vcpkg_configure_meson(
         -Dtracker3=false            # Enable Tracker3 filechooser search
         -Dcolord=no                 # Build colord support for the CUPS printing backend
         -Dintrospection=false
-    OPTIONS_DEBUG
-        ${OPTIONS_DEBUG}
-    OPTIONS_RELEASE
-        ${OPTIONS_RELEASE}
     ADDITIONAL_NATIVE_BINARIES
         glib-genmarshal='${CURRENT_HOST_INSTALLED_DIR}/tools/glib/glib-genmarshal'
         glib-mkenums='${CURRENT_HOST_INSTALLED_DIR}/tools/glib/glib-mkenums'
@@ -72,15 +67,15 @@ vcpkg_copy_pdbs()
 
 vcpkg_fixup_pkgconfig()
 
-file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
+file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
 
 set(GTK_TOOLS
-        gtk-builder-tool
-        gtk-encode-symbolic-svg
-        gtk-launch
-        gtk-query-immodules-3.0
-        gtk-query-settings
-        gtk-update-icon-cache
+    gtk-builder-tool
+    gtk-encode-symbolic-svg
+    gtk-launch
+    gtk-query-immodules-3.0
+    gtk-query-settings
+    gtk-update-icon-cache
 )
 vcpkg_copy_tools(TOOL_NAMES ${GTK_TOOLS} AUTO_CLEAN)
 
diff --git a/versions/g-/gtk3.json b/versions/g-/gtk3.json
index 37d6674df..ca886c94d 100644
--- a/versions/g-/gtk3.json
+++ b/versions/g-/gtk3.json
@@ -1,7 +1,7 @@
 {
   "versions": [
     {
-      "git-tree": "d8b0591c0b4235a0b55ff5357855bca882f0e760",
+      "git-tree": "86685f3f55c172707f910886bd111790b41fd497",
       "version": "3.24.30",
       "port-version": 0
     }

```

> > Too bad the author @mkhon is not so responsive.
> 
> Too bad that the official reviewers didn't properly respond to @mkhon when he was active.
> 
> Anyways, it doesn't need to be rebased, and there are no merge conflicts. What should be done, if enabled for the fork, is that one of the official reviewer (e.g. @JonLiu1993) pushes a merge with master to the the fork. If this passes CI, the PR could be accepted.

We can't, the PR was created without such permissions:

![image](https://user-images.githubusercontent.com/1544943/166841705-7537653b-0a53-42f8-93f3-734dc5cefffb.png)
![image](https://user-images.githubusercontent.com/1544943/166841705-7537653b-0a53-42f8-93f3-734dc5cefffb.png)

2022-05-04 23:32 UTC, BillyONeal commented
1. Do gtk4 and gtk3 work "side by side" or does installing one exclude install of the other?
2. Can you apply these nitpick level changes or fix the PR to allow me to push such changes?

```
diff --git a/ports/gtk3/portfile.cmake b/ports/gtk3/portfile.cmake
index 2a45a3aef..ca826e634 100644
--- a/ports/gtk3/portfile.cmake
+++ b/ports/gtk3/portfile.cmake
@@ -1,9 +1,9 @@
 set(warning_length 8)
 string(LENGTH "${CURRENT_BUILDTREES_DIR}" buildtrees_path_length)
 if(buildtrees_path_length GREATER warning_length AND CMAKE_HOST_WIN32)
-        message(WARNING "${PORT}'s buildsystem uses very long paths and may fail on your system.\n"
-            "We recommend moving vcpkg to a short path such as 'C:\\vcpkg' or using the subst command."
-        )
+    message(WARNING "${PORT}'s buildsystem uses very long paths and may fail on your system.\n"
+        "We recommend moving vcpkg to a short path such as 'C:\\vcpkg' or using the subst command."
+    )
 endif()
 
 set(GTK_MAJOR_MINOR 3.24)
@@ -17,7 +17,7 @@ vcpkg_download_distfile(ARCHIVE
 
 vcpkg_extract_source_archive_ex(
     OUT_SOURCE_PATH SOURCE_PATH
-    ARCHIVE ${ARCHIVE}
+    ARCHIVE "${ARCHIVE}"
     PATCHES
         0001-build.patch
         0002-windows-sdk11.patch
@@ -33,9 +33,8 @@ vcpkg_add_to_path("${CURRENT_HOST_INSTALLED_DIR}/tools/gdk-pixbuf")
 vcpkg_add_to_path("${CURRENT_HOST_INSTALLED_DIR}/tools/gettext/bin")
 
 vcpkg_configure_meson(
-    SOURCE_PATH ${SOURCE_PATH}
+    SOURCE_PATH "${SOURCE_PATH}"
     OPTIONS
-        ${OPTIONS}
         -Dwayland_backend=false
         -Ddemos=false
         -Dexamples=false
@@ -48,10 +47,6 @@ vcpkg_configure_meson(
         -Dtracker3=false            # Enable Tracker3 filechooser search
         -Dcolord=no                 # Build colord support for the CUPS printing backend
         -Dintrospection=false
-    OPTIONS_DEBUG
-        ${OPTIONS_DEBUG}
-    OPTIONS_RELEASE
-        ${OPTIONS_RELEASE}
     ADDITIONAL_NATIVE_BINARIES
         glib-genmarshal='${CURRENT_HOST_INSTALLED_DIR}/tools/glib/glib-genmarshal'
         glib-mkenums='${CURRENT_HOST_INSTALLED_DIR}/tools/glib/glib-mkenums'
@@ -72,15 +67,15 @@ vcpkg_copy_pdbs()
 
 vcpkg_fixup_pkgconfig()
 
-file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
+file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
 
 set(GTK_TOOLS
-        gtk-builder-tool
-        gtk-encode-symbolic-svg
-        gtk-launch
-        gtk-query-immodules-3.0
-        gtk-query-settings
-        gtk-update-icon-cache
+    gtk-builder-tool
+    gtk-encode-symbolic-svg
+    gtk-launch
+    gtk-query-immodules-3.0
+    gtk-query-settings
+    gtk-update-icon-cache
 )
 vcpkg_copy_tools(TOOL_NAMES ${GTK_TOOLS} AUTO_CLEAN)
 
diff --git a/versions/g-/gtk3.json b/versions/g-/gtk3.json
index 37d6674df..ca886c94d 100644
--- a/versions/g-/gtk3.json
+++ b/versions/g-/gtk3.json
@@ -1,7 +1,7 @@
 {
   "versions": [
     {
-      "git-tree": "d8b0591c0b4235a0b55ff5357855bca882f0e760",
+      "git-tree": "86685f3f55c172707f910886bd111790b41fd497",
       "version": "3.24.30",
       "port-version": 0
     }

```

> > Too bad the author @mkhon is not so responsive.
> 
> Too bad that the official reviewers didn't properly respond to @mkhon when he was active.
> 
> Anyways, it doesn't need to be rebased, and there are no merge conflicts. What should be done, if enabled for the fork, is that one of the official reviewer (e.g. @JonLiu1993) pushes a merge with master to the the fork. If this passes CI, the PR could be accepted.

We can't, the PR was created without such permissions:

![image](https://user-images.githubusercontent.com/1544943/166841705-7537653b-0a53-42f8-93f3-734dc5cefffb.png)
![image](https://user-images.githubusercontent.com/1544943/166841705-7537653b-0a53-42f8-93f3-734dc5cefffb.png)

2022-05-05 14:02 UTC, mkhon commented
> 1. Do gtk4 and gtk3 work "side by side" or does installing one exclude install of the other?

They can be installed side by side

> 2. Can you apply these nitpick level changes or fix the PR to allow me to push such changes?

Done

2022-05-05 19:27 UTC, talregev commented
vcpkg ci error: 
```
CMake Error at ports/gtk3/portfile.cmake:70 (file):
  file INSTALL given no DESTINATION
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)
```
@mkhon can you fix?

2022-05-05 19:30 UTC, talregev approved these changes
@BillyONeal
I succeeded to build it on windows and linux along side gtk port.

2022-05-05 21:10 UTC, mkhon commented
> vcpkg ci error:
> 
> ```
> CMake Error at ports/gtk3/portfile.cmake:70 (file):
>   file INSTALL given no DESTINATION
> Call Stack (most recent call first):
>   scripts/ports.cmake:145 (include)
> ```
> 
> @mkhon can you fix?

Sorry. Re-tested and fixed properly now.
Also fixed buildtrees path length check.

2022-05-06 06:04 UTC, JonLiu1993 commented
@mkhon ,I tested the feature locally by command ./vcpkg install gtk3[*]:x64-windows but failed:
````
ninja: fatal: CreateProcess: The parameter is incorrect.
````

2022-05-06 06:20 UTC, dg0yt requested changes

2022-05-06 06:20 UTC, dg0yt commented on ports/gtk3/vcpkg.json
> +      "platform": "(windows & static) | uwp"
Why does it depend on gettext for `windows & static` not  `windows & dynamic`? This doesn't make sense.

2022-05-06 06:20 UTC, dg0yt commented on ports/gtk3/vcpkg.json
> +        "tools"
`gettext[tools]` is generally expected to be used as a host dependency.

2022-05-06 06:20 UTC, dg0yt commented on ports/gtk3/vcpkg.json
> +      "host": true
Does `gtk3` build host binaries? If yes, they should be resolved via a host dependency on `gtk3`.
Or does `glib` install host tools?

2022-05-06 07:07 UTC, talregev commented
> 

This is due the error of too long command line. The root path you are using is too long.
Please try it on `C:\vcpkg`

2022-05-06 07:08 UTC, talregev commented
> @mkhon ,I tested the feature locally by command ./vcpkg install gtk3[*]:x64-windows but failed:
> 
> ```
> ninja: fatal: CreateProcess: The parameter is incorrect.
> ```

This is due the error of too long command line. The root path you are using is too long.
Please try it on `C:\vcpkg`

2022-05-07 08:01 UTC, mkhon commented on ports/gtk3/vcpkg.json
> +      "host": true
glib does install host tools which are used during gtk3 build (see also gtk port)

2022-05-07 08:01 UTC, mkhon commented on ports/gtk3/vcpkg.json
> +        "tools"
Fixed

2022-05-07 08:02 UTC, mkhon commented on ports/gtk3/vcpkg.json
> +      "platform": "(windows & static) | uwp"
I fixed this. It was an incorrect attempt to fix the build on windows static or uwp platforms

2022-05-09 05:42 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows

2022-05-09 05:42 UTC, JonLiu1993 approved these changes, later dismissed

2022-05-09 08:19 UTC, Thomas1664 commented on ports/gtk3/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
Wasn't there a PR recently that moved some gnome ports from ftp to GitLab?

2022-05-10 03:13 UTC, talregev commented on ports/gtk3/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
This was my PRs. It not a must. For gtk there only a github and not gitlab. not sure if it consider official:
https://github.com/GNOME/gtk/releases/tag/3.24.30. Also when you using source code from here, you need to remove the last patch.

2022-05-10 03:15 UTC, talregev commented on ports/gtk3/vcpkg.json
> +        "tools"
@dg0yt is it resolve?

2022-05-10 03:15 UTC, talregev commented on ports/gtk3/vcpkg.json
> +      "host": true
@dg0yt is it resolve?

2022-05-10 06:35 UTC, dg0yt commented on ports/gtk3/vcpkg.json
> +        "tools"
@talregev There is `"host": true` now. What else do you need to know?

2022-05-10 06:35 UTC, dg0yt commented on ports/gtk3/vcpkg.json
> +      "host": true
@talregev The answer was clear enough.

2022-05-10 06:40 UTC, talregev commented on ports/gtk3/vcpkg.json
> +      "host": true
ok. Please hit the resolve button.  Thank you.

2022-05-10 06:40 UTC, talregev commented on ports/gtk3/vcpkg.json
> +        "tools"
Just hit the resolve button.

2022-05-10 06:43 UTC, talregev commented on ports/gtk3/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
@JonLiu1993 Also, please don't hold this PR for this. I can change it to github in other PR. Thank you. 
Anything else left to review/respond?

2022-05-10 07:02 UTC, JonLiu1993 commented on ports/gtk3/portfile.cmake
> +vcpkg_download_distfile(ARCHIVE
No, I added the reviewed label.

2022-05-10 07:04 UTC, dg0yt reviewed
I did a successful build of this port. However, I have few more remarks:

- I notice that it installs tools, and I wonder if these tools would belong to the host triplet. (I don't know enough about GTK.)
- The port uses atk, and atk is always built with dynamic linkage in vcpkg. So the tools need to load the atk shared objects to resolve symbols. I wonder if they should be moved behind wrappers to set `LD_LIBRARY_PATH` (if atk cannot be changed to static).
- The port install modules/plugins to `/lib/gtk-3.0/3.0.0`. Vcpkg doesn't have a strict filesystem layout for plugins, so it is probably okay. However there is some convergence to using `/plugins` at least around Qt and KDE ports.

2022-05-10 18:26 UTC, BillyONeal commented
>The port uses atk, and atk is always built with dynamic linkage in vcpkg. So the tools need to load the atk shared objects to resolve symbols. I wonder if they should be moved behind wrappers to set LD_LIBRARY_PATH (if atk cannot be changed to static).

Notably, dynamic linkage on non-Windows is a fairly poor experience at the moment.

2022-05-10 18:28 UTC, BillyONeal commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
I'm nervous about licensing abut copying a file this large with an incompatible-with-vcpkg's license block, even if this is just defining constants. Can we download the real copy of this file from some upstream instead?

2022-05-10 18:44 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
@BillyONeal 
We can do it via github.
https://github.com/GNOME/gtk/releases/tag/3.24.30
Inside this zip file there is a winpointer.h.
Is it consider official repo?

2022-05-10 18:52 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
The official gitlab there isn't an older versions of gtk.
This repo is a read only mirror repo from gitlab, but have all the archive of older version.
If you allow to take the zip file from github, it will solve also the problem of `winpointer.h` (The patch will be removed).

2022-05-10 18:54 UTC, BillyONeal commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
>The official gitlab there isn't an older versions of gtk.

Makes sense! Sounds good to me then.

2022-05-10 18:56 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
@mkhon Can you change the source of file from github? Also you should remove the patch: `winpointer.h.patch`

2022-05-11 05:07 UTC, dg0yt commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
> The official gitlab there isn't an older versions of gtk.
> This repo is a read only mirror repo from gitlab, but have all the archive of older version.

I don't  get it.
- A true mirror cannot contain more files.
- There is tag 3.24.33 at https://gitlab.gnome.org/GNOME/gtk/, with https://github.com/GNOME/gtk/blob/3.24.33/gdk/win32/winpointer.h
  (And there is 3.24.30, too.)

2022-05-11 05:19 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
I don't get it either, but it seems taking from official and it solve the problem. You have objection to use this source?

2022-05-11 05:27 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
Here the explanation 
https://gitlab.gnome.org/GNOME/gtk/-/issues/4128

2022-05-11 05:30 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
We actually can take binaries from gtk gitlab with older tags.
https://gitlab.gnome.org/GNOME/gtk/-/tree/3.24.33/gdk
https://gitlab.gnome.org/GNOME/gtk/-/archive/3.24.33/gtk-3.24.33.tar.gz

2022-05-11 05:32 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
I will try with 3.24.33 and let you know (for Linux at least)

2022-05-11 05:54 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
I didn't succeeded with the versions: 3.24.33, 3.24.32.1, 3.24.32, 3.24.31. On newer versions, there is a new problems we need to solve.  on 3.24.30 the `winpointer.h` is missing because the reason I show above. 
@dg0yt Any objections to use github?

2022-05-11 06:16 UTC, dg0yt commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
Well, I wouldn't really want to see an outdated version which nobody is willing to update.

I have no objections with using the github mirror if it is official enough. Just don't mix arguments. There are official release tarballs (created with autotools) which lack the file in past versions. That's an entirely different thing then a tarball from a github tag. I guess you could get a tarball from a gitlab tag, too.

2022-05-11 18:35 UTC, Neumann-A commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
Have you tried meson?

https://gitlab.gnome.org/GNOME/gtk/-/tree/8ff9b2f83ff491cbfcbf9b30c706bd917679e7cc

Already has a meson build. 

Also:
https://gitlab.gnome.org/GNOME/gtk/-/blob/8ff9b2f83ff491cbfcbf9b30c706bd917679e7cc/gdk/win32/gdkdevice-winpointer.h

2022-05-11 18:57 UTC, dg0yt commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
> Have you tried meson?

We are using meson here.

> Also: ...

This was already said: It is in git, but it is missing from some release tarballs.

Don't ask me why it isn't using `vcpkg_from_gitlab`.
The patch don't need much changes to build with 3.24.33.

2022-05-11 19:32 UTC, dg0yt commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
> The patch don't need much changes to build with 3.24.33.

https://github.com/soylent-io/vcpkg/pull/1

2022-05-11 20:32 UTC, Neumann-A commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
> Don't ask me why it isn't using vcpkg_from_gitlab.
The patch don't need much changes to build with 3.24.33.

I somehow expect that but you beat me to it ;)

2022-05-11 21:07 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
I try to update to version 3.24.33 but the patches need to be updated. (I try myself). Also it fail on custom script and I am not sure why. 
@dg0yt @Neumann-A 
Can you try yourself and suggest fix for update 3.24.33? We don't need the `winpointer.h` patch because from 3.24.31 and above the file is presented.

2022-05-12 06:08 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
@dg0yt I just today notice of your PR update to 3.24.33. I compiled successful on Linux and windows.
Thank you for this update.
I hope @mkhon will take these changes soon.

2022-05-12 18:50 UTC, talregev commented
@mkhon Do you mind if one of us will take over this PR (in a different PR), and finish it instead of you?

2022-05-13 09:27 UTC, talregev commented on ports/gtk3/winpointer.h.patch
> ++/* GDK - The GIMP Drawing Kit
@dg0yt Do you have discord?

2022-05-16 13:24 UTC, mkhon commented
> @mkhon Do you mind if one of us will take over this PR (in a different PR), and finish it instead of you?

I merged the PR to update to 3.24.32 and I think this PR can just now be merged

2022-05-16 13:57 UTC, talregev commented
> I did a successful build of this port. However, I have few more remarks:
> 
> * I notice that it installs tools, and I wonder if these tools would belong to the host triplet. (I don't know enough about GTK.)
> * The port uses atk, and atk is always built with dynamic linkage in vcpkg. So the tools need to load the atk shared objects to resolve symbols. I wonder if they should be moved behind wrappers to set `LD_LIBRARY_PATH` (if atk cannot be changed to static).
> * The port install modules/plugins to `/lib/gtk-3.0/3.0.0`. Vcpkg doesn't have a strict filesystem layout for plugins, so it is probably okay. However there is some convergence to using `/plugins` at least around Qt and KDE ports.

@mkhon Did you answer these points?

2022-05-16 19:21 UTC, talregev commented
> I did a successful build of this port. However, I have few more remarks:
> 
> * I notice that it installs tools, and I wonder if these tools would belong to the host triplet. (I don't know enough about GTK.)
> * The port uses atk, and atk is always built with dynamic linkage in vcpkg. So the tools need to load the atk shared objects to resolve symbols. I wonder if they should be moved behind wrappers to set `LD_LIBRARY_PATH` (if atk cannot be changed to static).
> * The port install modules/plugins to `/lib/gtk-3.0/3.0.0`. Vcpkg doesn't have a strict filesystem layout for plugins, so it is probably okay. However there is some convergence to using `/plugins` at least around Qt and KDE ports.

@dg0yt Can you do this after this PR will merge?

2022-05-17 07:22 UTC, mkhon commented
> I did a successful build of this port. However, I have few more remarks:
> 
> * I notice that it installs tools, and I wonder if these tools would belong to the host triplet. (I don't know enough about GTK.)

I think they belong to the target triplet. ports/gtk/ does not do anything special about them

> * The port uses atk, and atk is always built with dynamic linkage in vcpkg. So the tools need to load the atk shared objects to resolve symbols. I wonder if they should be moved behind wrappers to set `LD_LIBRARY_PATH` (if atk cannot be changed to static).

I think all the dependencies (including atk libraries) are properly copied to tools/gtk3/

> * The port install modules/plugins to `/lib/gtk-3.0/3.0.0`. Vcpkg doesn't have a strict filesystem layout for plugins, so it is probably okay. However there is some convergence to using `/plugins` at least around Qt and KDE ports.

I do not see these to be built on Windows builds so can not comment right now

2022-05-17 07:51 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows

2022-05-17 08:06 UTC, JackBoosY commented
@BillyONeal Do you have any concern?

2022-05-18 22:16 UTC, BillyONeal commented
This looks good to me other than that I need to discuss the atk situation with other maintainers.

2022-05-19 18:46 UTC, BillyONeal commented
@vicroms @ras0219 and I discussed the ATK patch in person today and we are uncomfortable with patching out a major dependency like atk that upstream's build system doesn't already understand; we would want upstream to be involved in particular.

(I personally also am nervous about patching out accessibility stuff given ... some laws in some places)

To that end I don't think we can accept ninja-patching that out like this. If you want to proceed in getting this port into vcpkg and need to fix the dynamic loading bits, you may wish to look at helping the folks trying to figure out how to get `RPATH` set correctly using e.g. `patchelf`:

https://github.com/microsoft/vcpkg/pulls?q=is%3Apr+is%3Aopen+patchelf

* https://github.com/microsoft/vcpkg/pull/23035 (I think main discussion is going on here)
* https://github.com/microsoft/vcpkg/pull/19940 (Only for vcpkg_copy_app_local_dependencies only)
* https://github.com/microsoft/vcpkg/pull/15134 (Only for protocol buffers)

I'm sorry that this late breaking thing wasn't discovered until recently given that you've been working on this for so long :(. Thanks for giving it a shot though!

2022-05-19 19:32 UTC, mkhon commented
@BillyONeal which atk patch and issue do you mean? Can you clarify, please?

2022-05-19 20:58 UTC, BillyONeal commented
> @BillyONeal which atk patch and issue do you mean? Can you clarify, please?

`0003-disable-atk-bridge.patch`

2022-05-20 04:18 UTC, dg0yt commented
Note that `0003-disable-atk-bridge.patch` isn't patching out `atk` but `atk-bridge`. But I don't know how useful the former is without the latter.

2022-05-20 10:28 UTC, mkhon commented
@BillyONeal atk-bridge is not atk - this dependency does not exist in vcpkg (provided by https://gitlab.gnome.org/GNOME/at-spi2-atk)

Also, this dependency is only required on Linux, while main targets for vcpkg are Windows

Can we merge this port with this patch until the dependency is properly ported (again it is needed only on X11 targets, which obviously excludes Windows targets).

2022-05-20 12:10 UTC, dg0yt commented
I don't agree on the Windows focus (some of us need gtk3 for wxwidgets:x64-linux), but I do agree that the current state is good enough - as much it was fine before port gtk was upgrade from 3 to 4. My remarks were meant to reflect what could be regarde as "known issues" for linux.
Improvements can be implemented and tested with the wxidgets integration.

2022-05-21 04:31 UTC, talregev commented
> @BillyONeal atk-bridge is not atk - this dependency does not exist in vcpkg (provided by https://gitlab.gnome.org/GNOME/at-spi2-atk)
> 
> Also, this dependency is only required on Linux, while main targets for vcpkg are Windows
> 
> Can we merge this port with this patch until the dependency is properly ported (again it is needed only on X11 targets, which obviously excludes Windows targets)?

@mkhon You should create the https://gitlab.gnome.org/GNOME/at-spi2-atk port. Then modify this PR.

2022-05-21 04:32 UTC, talregev commented on ports/gtk3/0003-disable-atk-bridge.patch
> +diff --git a/gtk/a11y/gtkaccessibility.c b/gtk/a11y/gtkaccessibility.c
Please create https://gitlab.gnome.org/GNOME/at-spi2-atk port
and remove this patch.

2022-05-21 04:32 UTC, talregev requested changes
Add https://gitlab.gnome.org/GNOME/at-spi2-atk port.

2022-05-23 19:13 UTC, talregev commented
> Add https://gitlab.gnome.org/GNOME/at-spi2-atk port.

@dg0yt Can you help me to create this port?

2022-05-24 06:14 UTC, mkhon commented
@talregev I have a draft of this port, but it currently does not build because of the pkgconfig cflags quoting issue bug in meson. Basically, if pkgconfig cflags has double quotes like -DFOO="bar", meson puts -DFOO=bar (without the quotes) to the generated ninja build files and the build fails

2022-05-24 06:15 UTC, talregev commented
> @talregev I have a draft of this port, but it currently does not build because of the pkgconfig cflags quoting issue bug in meson. Basically, if pkgconfig cflags has double quotes like -DFOO="bar", meson puts -DFOO=bar (without the quotes) to the generated ninja build files and the build fails

Can you put a link to your draft pr?

2022-05-24 06:30 UTC, mkhon commented
No, it does not help because FOO is expected to be a C string. I'll wrap it up and submit a PR for this port today

2022-05-24 06:40 UTC, talregev commented
> No, it does not help because FOO is expected to be a C string. I'll wrap it up and submit a PR for this port today

It will help because we can take a look and fix.
Can you send a link to your draft branch and I will make a PR?

2022-05-24 06:41 UTC, talregev commented
> No, it does not help because FOO is expected to be a C string. I'll wrap it up and submit a PR for this port today

When you make a PR, please make it that other can edit it too (maintainers) That will make a fast development. also please cc me on this PR.

2022-05-26 09:04 UTC, mkhon commented
@talregev I don't see "Allow edits by maintainers" option on my PR by the way

2022-05-26 09:13 UTC, mkhon commented
I created a PR for at-spi2-atk dependency: #24934

2022-05-26 09:45 UTC, talregev commented
> I created a PR for at-spi2-atk dependency: #24934

Thank you for your PR!

2022-05-27 23:03 UTC, mkhon commented
Can we merge this one with Linux build disabled.

We will enable Linux build as soon as at-spi2-atk port is merged.

2022-05-28 03:33 UTC, talregev commented
> Can we merge this one with Linux build disabled?
> 
> We will enable Linux build as soon as at-spi2-atk port is merged.

We actually need the Linux part in the gtk to fix wxwidgets port.

2022-05-29 19:09 UTC, dg0yt commented
> Can we merge this one with Linux build disabled?
> 
> We will enable Linux build as soon as at-spi2-atk port is merged.

We don't even need linux disabled. we need CI being rerun.
~~~
git commit --allow-empty -m CI
gir push

2022-05-29 19:12 UTC, talregev commented
> > Can we merge this one with Linux build disabled?
> > We will enable Linux build as soon as at-spi2-atk port is merged.
> 
> We don't even need linux disabled. we need CI being rerun.
> 
> ```
> git commit --allow-empty -m CI
> gir push
> ```

This PR is missing `at-spi2-atk` port.
He want to disable the linux part because it missing libs and merge it to the master without these libs.
I am against it.
Can you help with  `at-spi2-atk` port?

2022-05-30 04:35 UTC, dg0yt commented
@BillyONeal We had a mergeable state which included linux support with `0003-disable-atk-bridge.patch`. I would prefer to return immediately to this mergeable state, to unblock downstream usage.

2022-05-31 14:10 UTC, japm48 commented
I would suggest also updating to version 3.24.34, as it now correctly includes some required icons (see [gtk!4754](https://gitlab.gnome.org/GNOME/gtk/-/issues/4754)).
Of course, that could be done after merging this PR, if you prefer so.

2022-05-31 18:41 UTC, mkhon commented
> I would suggest also updating to version 3.24.34, as it now correctly includes some required icons (see [gtk!4754](https://gitlab.gnome.org/GNOME/gtk/-/issues/4754) and [gtk!4790](https://gitlab.gnome.org/GNOME/gtk/-/issues/4790)).
> Of course, that could be done after merging this PR, if you prefer so.

Done

2022-06-02 12:44 UTC, mkhon commented
/azp run

2022-06-02 13:21 UTC, talregev commented
> I temporarily removed at-spi2-atk dependency (for Linux) as CI build was failing (even when the port was marked as "skip" on x64-linux)
> 
> Can we finally merge this port?

We need gtk in Linux. even if you disable it on the cli, it mean that it cannot compile under Linux. 
We should wait for `at-spi2-atk` port. 
Another alternative like @dg0yt is suggested that you will restore the patch that disable the need of `at-spi2-atk` in Linux part.
But I doubt that @BillyONeal will approve that.

That why I think the best effort for this PR, that we will focuses on `at-spi2-atk` port.

@dg0yt @BillyONeal 
Correct me if I wrong.

2022-06-02 13:48 UTC, mkhon commented
> We need gtk in Linux. even if you disable it on the cli, it mean that it cannot compile under Linux. We should wait for `at-spi2-atk` port. Another alternative like @dg0yt is suggested that you will restore the patch that disable the need of `at-spi2-atk` in Linux part. But I doubt that @BillyONeal will approve that.

1) I fully support you - that's why I create at-spi2-atk and at-spi2-core ports

2) It is not true you can not compile under Linux - you can build at-spi2-atk port from PR, then build gtk3 port. If gtk3 is merged you will only have to deal with at-spi2 out-of-tree ports, now you also have to deal with out-of-tree gtk3

3) I don't think it is reasonable to block port merge referring it is not buildable on CI for one single platform and thus blocking this port on all other platforms. Especially given that the port is not buildable because it depends on the port (at-spi2-atk) which depends on yet another port (at-spi2-core) which depends on a system-provided package (libdbus-1-dev) which requires either changing the CI build VM (installing this package there) or waiting until yet another PR gets merged (which will theoretically provide dbus-1 dependency)

This may take ages

4) I am curious why you can't use stock -dev/-devel packages on Linux - never had a single issue with them and whenever I needed a version update or some package that does not exist in the distro - I created a native package for it instead of depending on vcpkg build

Stock gtk3 and wxgtk stock packages exist in all Linux distros I know

2022-06-02 13:58 UTC, talregev commented
> Also, I do not quite underdstand what do you mean by "focusing" on at-spi2-atk - I made a PR for it but it can not be built on CI because of infrastructure issues - I am afraid I can not help with this

I agree. I note for maintainers and they should back on us with this. So currently we should wait for their respond.

2022-06-02 14:01 UTC, talregev commented
> I don't think it is reasonable to block port merge referring it is not buildable on CI for one single platform and thus blocking this port on all other platforms. Especially given that the port is not buildable because it depends on the port (at-spi2-atk) which depends on yet another port (at-spi2-core) which depends on a system-provided package (libdbus-1-dev) which requires either changing the CI build VM (installing this package there) or waiting until yet another PR gets merged (which will theoretically provide dbus-1 dependency)

I think they have a rule now that you cannot add a port with ci skipped / fail. And you should to add it for not support. 
But this port it is support Linux, that we will need wait for `at-spi2-atk` port.

2022-06-02 14:04 UTC, mkhon commented
My preference is to make any change (mark it as not supported, have at-spi2-atk dependency patched out, merge it with ci=skip for one platform) - whatever will make it merged is fine for me.

However we should have maintainers consent on this - we're playing ping-pong for some time with this port

2022-06-02 14:07 UTC, talregev commented
> I am curious why you can't use stock -dev/-devel packages on Linux - never had a single issue with them and whenever I needed a version update or some package that does not exist in the distro - I created a native package for it instead of depending on vcpkg build 

I need `gtk` Linux for vcpkg `wxwidgets`. 
Currently the way vcpkg `wxwidgets` is build that you cannot install some library in vcpkg (for example glib and freetype) in vcpkg. You need to delete them first. then install `wxwidegts` and then install them again in vckg. 
We are using vcpkg in the opensource project and it help to compile these ports via across os. (Linux, Windows, Mac). for other libraries we also compile for Android. 
So for now the wxwidgets for linux is somehow broken for us, even we can compile it with vcpkg on Linux.
The way we using now vcpkg is with version control. but for wxwidgwts linux vcpkg we cannot use it in the reason I mention before. 
That why I am waiting for this gtk port that will fix wxwidgets for opensource project I contribute to.

2022-06-02 14:09 UTC, talregev commented
> 

@BillyONeal is one of the maintainers. His respond will be official for vcpkg and for this port.

2022-06-03 09:27 UTC, talregev commented
@mkhon Thank you for update to the next version.
You update the version, but forget to update the hash. 
Can you update also the hash? 
```
File does not have the expected hash:
             url : [ https://gitlab.gnome.org/GNOME/gtk/-/archive/3.24.34/gtk-3.24.34.tar.gz ]
       File path : [ /home/ubuntu/vcpkg/downloads/GNOME-gtk-3.24.34.tar.gz.1072287.part ]
   Expected hash : [ 634c3684e670e662340e780a0f561ddc191790625d6b7f28ec7fbb1fcaec86856091e94124565f138d3adaa08a9e063ead2ff441354763b21b4e887c2a54e8d0 ]
     Actual hash : [ 20a91e30a89070461af06b33829bc723b348806b4a785d0743af8bd4789b55dade24686e08bf1b2f0335240463aacc040134babb0605b809186b15de9cf261e4 ]
```

2022-06-03 10:23 UTC, talregev commented
Also I try gtk3 (with at-spi2-atk port) with wxwidget port. 
here:
https://github.com/talregev/vcpkg/tree/TalR/wxwidgets_with_gtk3_port_test
In this opensource project:
https://github.com/BOINC/boinc/pull/4756
It compile on vcpkg.
But when I use the wxwidegts in our opensource project
I get this error:
```
/usr/bin/ld: /home/runner/work/boinc/boinc/3rdParty/linux/vcpkg/installed/x64-linux/lib/libgtk-3.a(gtkbuilder.c.o): undefined reference to symbol 'g_module_supported'
```

Can you help?

2022-06-03 10:29 UTC, talregev commented
> ```
> undefined reference to symbol 'g_module_supported'
> ```

I am trying to install `libglib2.0-dev` on the opensource ci. I hope it solve it.
From here:
https://unix.stackexchange.com/questions/406659/gmodule-2-0-not-found-while-compiling

2022-06-03 10:39 UTC, Neumann-A commented
vcpkg has glib.

2022-06-03 11:03 UTC, talregev commented
```
/usr/bin/ld: /home/runner/work/boinc/boinc/3rdParty/linux/vcpkg/installed/x64-linux/lib/libgtk-3.a(gtkbuilder.c.o): undefined reference to symbol 'g_module_supported'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line
```
The problem that wxwidgets is take the glib from system instead glib vcpkg.
I will try to fix it myself.

2022-06-03 15:06 UTC, talregev commented
> vcpkg has glib.

Can you suggest how I will fix it?

2022-06-03 15:07 UTC, talregev commented
> @mkhon Thank you for update to the next version. You update the version, but forgot to update the hash. Can you update also the hash?
> 
> ```
> File does not have the expected hash:
>              url : [ https://gitlab.gnome.org/GNOME/gtk/-/archive/3.24.34/gtk-3.24.34.tar.gz ]
>        File path : [ /home/ubuntu/vcpkg/downloads/GNOME-gtk-3.24.34.tar.gz.1072287.part ]
>    Expected hash : [ 634c3684e670e662340e780a0f561ddc191790625d6b7f28ec7fbb1fcaec86856091e94124565f138d3adaa08a9e063ead2ff441354763b21b4e887c2a54e8d0 ]
>      Actual hash : [ 20a91e30a89070461af06b33829bc723b348806b4a785d0743af8bd4789b55dade24686e08bf1b2f0335240463aacc040134babb0605b809186b15de9cf261e4 ]
> ```

@mkhon It it possible that gitlab change the file for 3.24.34? 
Can you check local on your side?

2022-06-03 18:43 UTC, mkhon commented
> > vcpkg has glib.
> 
> Can you suggest how I will fix it? wxwdigets use glib from sys instead of vcpkg?

You should use the same glib in both wxwidgets and vcpkg. Otherwise you may get fancy errors during runtime

2022-06-03 18:53 UTC, talregev commented
> and vcpkg. Otherwise you may

How I can do it? How I tell wxwidgets vcpkg port to use gtk3 that you created?

2022-06-03 19:01 UTC, talregev commented
> wxwidgets and vcpkg

@mkhon Can you check the hash on your local on your side? Thank you.

2022-06-03 19:21 UTC, talregev requested changes
Please change the hash

2022-06-03 19:21 UTC, talregev commented on ports/gtk3/portfile.cmake
> +    SHA512 634c3684e670e662340e780a0f561ddc191790625d6b7f28ec7fbb1fcaec86856091e94124565f138d3adaa08a9e063ead2ff441354763b21b4e887c2a54e8d0
Change the hash to:
```
20a91e30a89070461af06b33829bc723b348806b4a785d0743af8bd4789b55dade24686e08bf1b2f0335240463aacc040134babb0605b809186b15de9cf261e4
```

2022-06-03 19:27 UTC, BillyONeal commented
To clarify: our validation won't catch hash mistakes when the old hash is previously there, because we have asset caching turned on, and asset caching does:

```
if (asset cache has that SHA) {
   download from asset cache
} else {
   download from supplied URL
   check the hash
   store in the asset cache
}
```

2022-06-03 20:57 UTC, talregev commented
I look again on wxwidgets and I faild to change that it take glib from vcpkg.
I think wxwidgets take the correct gtk3 (from vcpkg). and gtk3 doesn't publish the correct glib. (it publish system glib).

```
~/vcpkg/installed/x64-linux/lib/pkgconfig
```

```
> pkg-config gtk+-3.0.pc --libs
-L./../../lib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -latk-1.0 -latk-bridge-2.0 -lepoxy -lfribidi -lpangoft2-1.0 -lpango-1.0 -lharfbuzz -lfontconfig -lfreetype -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

Can you change that it will take from vcpkg and not from system?

2022-06-04 04:14 UTC, talregev commented on versions/g-/gtk3.json
> +      "version": "3.24.33",
Please delete this, because there isn't 3.24.33 version anymore.

2022-06-04 07:26 UTC, talregev commented
Thank you for your changes!

2022-06-04 07:32 UTC, talregev commented
@BillyONeal @dg0yt 
@mkhon There is a PR of dubs waiting, that why they will not rush and install dbus on the ci. That will hold at-spi2-atk port.
So the fastest way this PR can be merge to the master is to go with @dg0yt suggestion. 
Please: 
- [ ] Revert the at-spi2-atk bridge patch. The patch that cancel the use of the bridge in gtk3 and can compile again on linux.
- [ ] Remove the skipped linux in the ci. Let the ci compile linux with success (after the patch). 
- [ ] Update with ` ./vcpkg x-add-version --all --overwrite-version`

Then we can ask to review this PR again. hopefully it can be merge that way. 
In the meanwhile keep the at-spi2-atk PR. When dbus will be ready, we can merge it too, and fix gtk3 PR again, in separate PR.

2022-06-05 08:47 UTC, talregev commented
> I look again on wxwidgets and I faild to change that it take glib from vcpkg. ~I think wxwidgets take the correct gtk3 (from vcpkg). and gtk3 doesn't publish the correct glib. (it publish system glib).~
> 
> ```
> ~/vcpkg/installed/x64-linux/lib/pkgconfig
> ```
> 
> ```
> > pkg-config gtk+-3.0.pc --libs
> -L./../../lib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -latk-1.0 -latk-bridge-2.0 -lepoxy -lfribidi -lpangoft2-1.0 -lpango-1.0 -lharfbuzz -lfontconfig -lfreetype -lgio-2.0 -lgobject-2.0 -lglib-2.0
> ```
> 
> ~Can you change that it will take from vcpkg and not from system?~
> 
> Edit: I think the problem is on wxwidgets that I failed to fix.

I fix the gkt ld error I got. It was bug in our end (boinc opensource project).
I fix it on this PR:
https://github.com/BOINC/boinc/pull/4756

2022-06-06 09:08 UTC, JackBoosY requested changes

2022-06-06 09:08 UTC, JackBoosY commented on ports/gtk3/0001-build.patch
> +-if not meson.is_cross_build()
I'm not sure why this option is disabled?

2022-06-06 09:08 UTC, JackBoosY commented on ports/gtk3/portfile.cmake
> +endif()
```suggestion
vcpkg_buildpath_length_warning(24)
```

2022-06-06 12:35 UTC, mkhon commented on ports/gtk3/portfile.cmake
> +endif()
vcpkg_buildpath_length_warning() can not be used here as it recommends to move to C:\src\vcpkg which gives buildpath length >24

2022-06-07 07:09 UTC, dg0yt commented on ports/gtk3/0001-build.patch
> +-if not meson.is_cross_build()
This is the gtk3 port of `ports/gtk/0001-build.patch`, isn't it?
I don't have the full context now, but obviously this disables a post-install step which isn't executed for cross builds anyways so it cannot be strictly necesary. IIRC the reason is that it doesn't work on mingw in particular or on window in general.

2022-06-07 11:01 UTC, mkhon commented
> @BillyONeal @dg0yt @mkhon There is a PR of dubs waiting, that why they will not rush and install dbus on the ci. That will hold at-spi2-atk port. The PR of dbus is open from January, and likely to be merge to the master in more then a few weeks. So the fastest way this PR can be merge to the master is to go with @dg0yt suggestion. Please:
> 
> * [ ]  Revert the at-spi2-atk bridge patch. The patch that cancel the use of the bridge in gtk3 and can compile again on linux.
> * [ ]  Remove the skipped linux in the ci. Let the ci compile linux with success (after the patch).
> * [ ]  Update with ` ./vcpkg x-add-version --all --overwrite-version`
> 
> Then we can ask to review this PR again. hopefully it can be merge that way. In the meanwhile keep the at-spi2-atk PR. When dbus will be ready, we can merge it too, and fix gtk3 PR again, in separate PR.

I would like to hear from the maintainers, as we had this patch before and PR got rejected because of this.
I haven't heard from maintainers since then

2022-06-08 06:48 UTC, JackBoosY commented on ports/gtk3/portfile.cmake
> +endif()
So can you confirm a longest valid path to replace this code?

2022-06-08 06:49 UTC, JackBoosY commented
I'd like to wait for #24934 to add port at-spi2-atk first.

2022-06-08 10:09 UTC, talregev commented
> I'd like to wait for #24934 to add port at-spi2-atk first.

I would like that too! But vcpkg don't install dubs on the ci for that. 😢

2022-08-22 23:20 UTC, stevapple requested changes

2022-08-22 23:20 UTC, stevapple commented on ports/gtk3/portfile.cmake
> +endif()
I tried `subst` and it seems not solving the problem. Moving to the root of a drive may be the only choice.

I would also suggest we make it clear that the path length cannot exceed 24 (if that’s the exact number). This message may fail to inform the user which paths are acceptable.

2022-09-02 09:57 UTC, JonLiu1993 commented
Ping @mkhon for response.

2022-09-09 07:50 UTC, JonLiu1993 commented
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

2022-09-16 08:21 UTC, JackBoosY commented
Waiting for https://github.com/microsoft/vcpkg/pull/26766 merge first.
Before that, I think we should close this PR temporary. Then please ping me to reopen it.

2022-09-16 08:21 UTC, closed without merging

2022-09-16 09:11 UTC, talregev commented
Better that he will open this PR on his mkhon user.

2022-09-28 19:36 UTC, mkhon commented
I opened a new PR #24136 for this

2022-09-28 19:55 UTC, talregev commented
#24136 this is my PR. I can open it.

2022-09-28 19:56 UTC, talregev commented
I think you meant this PR #27026