[civetweb] add option support USE_ZLIB
microsoft/vcpkg pull request #22223
Opened 2021-12-27 10:28 UTC by JonLiu1993

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #16044
  Add '-DCIVETWEB_ENABLE_ZLIB=ON' and zlib dependency to support compile this package with -DUSE_ZLIB

2021-12-27 10:31 UTC, JonLiu1993 commented on ports/civetweb/portfile.cmake
> +        fix-error-D8021.patch
Add patches for fix error D8021 : invalid numeric argument '/Wextra' '/Wshadow' '/Wconversion' ...

2021-12-27 11:30 UTC, JackBoosY requested changes

2021-12-27 11:30 UTC, JackBoosY commented on ports/civetweb/portfile.cmake
> +        fix-error-D8021.patch
Why remove them?

2021-12-28 02:30 UTC, JonLiu1993 commented
/azp run

2021-12-31 08:52 UTC, JackBoosY commented on ports/civetweb/portfile.cmake
> +        fix-error-D8021.patch
Those compile flags should only be used on Linux.

2022-01-03 22:12 UTC, BillyONeal approved these changes, later dismissed

2022-01-04 03:47 UTC, JackBoosY requested changes

2022-01-04 03:47 UTC, JackBoosY commented on ports/civetweb/fix-error-D8021.patch
> +   endif()
```cmake
if (UNIX)
   ...
endif()
```

2022-01-04 12:20 UTC, JackBoosY requested changes

2022-01-04 12:20 UTC, JackBoosY commented on ports/civetweb/fix-error-D8021.patch
> +-  add_c_compiler_flag(/Wd4820) # padding
Also modify this.

2022-01-04 15:34 UTC, JackBoosY approved these changes

2022-01-04 22:57 UTC, strega-nil-ms requested changes
hey, just wanted a response for the questions

2022-01-04 22:57 UTC, strega-nil-ms commented on ports/civetweb/fix-error-D8021.patch
> ++      add_cxx_compiler_flag(/Wd4820) # padding
putting this in the `if(UNIX)` block doesn't make sense

2022-01-04 22:57 UTC, strega-nil-ms commented on ports/civetweb/fix-error-D8021.patch
> ++      add_c_compiler_flag(/Wd4820) # padding
same here

2022-01-04 22:57 UTC, strega-nil-ms commented on ports/civetweb/fix-error-D8021.patch
> +-  add_c_compiler_flag(-Wall)
it looks very much here like this `add_c_compiler_flag` is supposed to check if the flag goes to gcc-style or msvc-style compilers; can we see what's wrong with this function, rather than just adding `if(UNIX)` around all of the options?

2022-01-06 01:51 UTC, BillyONeal commented on ports/civetweb/fix-error-D8021.patch
> ++      add_cxx_compiler_flag(/Wd4820) # padding
... because these are MSVC switches

2022-01-06 17:18 UTC, JackBoosY commented on ports/civetweb/fix-error-D8021.patch
> ++      add_cxx_compiler_flag(/Wd4820) # padding
Yes, that's only for non-Windows.

2022-01-07 00:16 UTC, BillyONeal commented on ports/civetweb/fix-error-D8021.patch
> ++      add_cxx_compiler_flag(/Wd4820) # padding
@JackBoosY Non-Windows compilers do not understand `/W4` and `/Wd4820`; those are MSVC switches.

2022-01-07 02:35 UTC, JackBoosY commented on ports/civetweb/fix-error-D8021.patch
> ++      add_cxx_compiler_flag(/Wd4820) # padding
Ah sorry, I misunderstood that.

2022-01-28 08:41 UTC, JonLiu1993 commented on ports/civetweb/fix-error-D8021.patch
> +-  add_c_compiler_flag(-Wall)
@strega-nil-ms ,Sorry for replying you so late, I looked into this issue locally, I investigated and found that this error was introduced because:
I modernized the vcpkg_install_cmake() function in the portfile.cmake file to vcpkg_cmake_install()
when I made the keep all The modification is unchanged, and then vcpkg_cmake_install() and vcpkg_cmake_configure() are restored to their original writing, this problem will not occur. 
Restore the vcpkg_cmake_configure() function because it has the same dependencies as vcpkg_cmake_install(): vcpkg-cmake, modify one of them Unable to install port normally

2022-01-29 07:20 UTC, JackBoosY requested changes

2022-01-29 07:20 UTC, JackBoosY commented on ports/civetweb/fix-error-D8021.patch
> ++      add_c_compiler_flag(/Wd4820) # padding
This also should be included in `if (MSVC)`.

2022-01-29 14:50 UTC, JonLiu1993 commented on ports/civetweb/fix-error-D8021.patch
> ++      add_c_compiler_flag(/Wd4820) # padding
@JackBoosY ,When I added "add_c_compiler_flag(/Wd4820) # padding" to the if (MSVC), I still got the same error in my local test:
error D8021 : invalid numeric argument '/Wd4820', but after I did some investigation I found that adding "add_c_compiler_flag(Wd4820) # padding" to if (MSVC) after deleting "/" can successfully install, but apparently this The solution for raising is not correct, so I have submitted an [issue ](https://github.com/civetweb/civetweb/issues/1052)on Upstream, hoping they can give some suggestions

2022-01-31 20:20 UTC, BillyONeal commented on ports/civetweb/fix-error-D8021.patch
> ++      add_c_compiler_flag(/Wd4820) # padding
This option is case sensitive; it needs to be `/wd4820`. `/W` capital tries to set the overall warning level, e.g. `/W3` or `/W4`.

2022-03-18 08:00 UTC, JackBoosY commented
Draft this PR and waiting for the upstream reply.

2022-06-24 08:05 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2022-06-24 08:05 UTC, closed without merging