[teemo] Fix string replace error.
microsoft/vcpkg pull request #22244
Opened 2021-12-29 06:43 UTC by winsoft666

**Describe the pull request**

- #### What does your PR fix?  
  Fixes string replace error.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <linux, windows / macos>, <No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2021-12-29 08:32 UTC, JackBoosY commented
I think we don't need this, do we?

2021-12-29 08:46 UTC, winsoft666 commented
> I think we don't need this, do we?

The old code can not replace string correctly.
If VCPKG_LIBRARY_LINKAGE is `dynamic`, it mistakenly  replaced `#ifdef TEEMO_STATIC` with `#if $<STREQUAL:dynamic, static>`.
What I want is to replace `#ifdef TEEMO_STATIC` with `#if 0`.

2021-12-29 08:47 UTC, winsoft666 commented
> > I think we don't need this, do we?
> 
> The old code can not replace string correctly. If VCPKG_LIBRARY_LINKAGE is `dynamic`, it mistakenly replaced `#ifdef TEEMO_STATIC` with `#if $<STREQUAL:dynamic, static>`. What I want is to replace `#ifdef TEEMO_STATIC` with `#if 0`.

I'm not familiar with cmake grammar.

2021-12-29 08:53 UTC, JackBoosY commented
Ah you are the owner, I have some questions:
1. When building dynamic, should we undefine `TEEMO_STATIC`?
2. When building static, should we define `TEEMO_STATIC`?

2021-12-29 09:33 UTC, winsoft666 commented
> 

Obviously, define/undefined TEEMO_STATIC in projects that  use teemo library is a good method.
However I have not found a way to automatically define/undefined TEEMO_STATIC via VCPKG.

2021-12-29 10:02 UTC, JackBoosY commented
Does there have any other places to use this macro?

2021-12-29 10:05 UTC, winsoft666 commented
> Does there have any other places to use this macro?

No

2021-12-29 10:26 UTC, JackBoosY commented
> > Does there have any other places to use this macro?
> 
> No

Therefore, I think we can keep this code since there is no other place to use that:
1. Replace "#ifdef TEEMO_STATIC" to "#if 1" when building static.
2. Replace "#ifdef TEEMO_STATIC" to "#if 0" when building dynamic.

Do you agree that?

2021-12-29 10:41 UTC, winsoft666 commented
> > > Does there have any other places to use this macro?
> > 
> > 
> > No
> 
> Therefore, I think we can keep this code since there is no other place to use that:
> 
> 1. Replace `#ifdef TEEMO_STATIC` to `#if 1` when building static.
> 2. Replace `#ifdef TEEMO_STATIC` to `#if 0` when building dynamic.
> 
> Do you agree that?

I don't understand what's your meaning, and keep what code?

All of my updated code is designed to do just that:
1. Replace `#ifdef TEEMO_STATIC` to `#if 1` when building static.
2. Replace `#ifdef TEEMO_STATIC` to `#if 0` when building dynamic.

The old code has some bug, can not replace correctly.

2021-12-29 13:27 UTC, JackBoosY commented
> > > > Does there have any other places to use this macro?
> > > 
> > > 
> > > No
> > 
> > 
> > Therefore, I think we can keep this code since there is no other place to use that:
> > 
> > 1. Replace `#ifdef TEEMO_STATIC` to `#if 1` when building static.
> > 2. Replace `#ifdef TEEMO_STATIC` to `#if 0` when building dynamic.
> > 
> > Do you agree that?
> 
> I don't understand what's your meaning, and keep what code?
> 
> All of my updated code is designed to do just that:
> 
> 1. Replace `#ifdef TEEMO_STATIC` to `#if 1` when building static.
> 2. Replace `#ifdef TEEMO_STATIC` to `#if 0` when building dynamic.
> 
> The old code has some bug, can not replace correctly.

The current code already does this. `if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")` means build static, otherwise build dynamic.
Can you describe the bug you encountered?

2021-12-29 14:27 UTC, dg0yt commented
> The current code already does this. `if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")` means build static, otherwise build dynamic.
> Can you describe the bug you encountered?

@JackBoosY The current substitution contains a cmake generator expression, but this expression never goes through a generation step, so it doesn't achieve the desired out come.

2021-12-29 14:28 UTC, dg0yt requested changes

2021-12-29 14:28 UTC, dg0yt commented on ports/teemo/portfile.cmake
> -vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/teemo/teemo.h" "#ifdef TEEMO_STATIC" "#if $<STREQUAL:${VCPKG_LIBRARY_LINKAGE},static>")
Good catch @winsoft666!

2021-12-29 14:28 UTC, dg0yt commented on ports/teemo/vcpkg.json
> +  "version": "2.5#2",
Instead of appending `#2`, we need a `"port-version": 1` line.

2021-12-30 01:50 UTC, winsoft666 commented on ports/teemo/vcpkg.json
> +  "version": "2.5#2",
OK, has updated!

2021-12-30 04:20 UTC, JackBoosY commented
Oh sorry, I reversed the deleted part and the newly added part.

2021-12-30 04:22 UTC, JackBoosY requested changes

2021-12-30 04:22 UTC, JackBoosY commented on ports/teemo/vcpkg.json
> +  "port-version": 1,
Since you are the owner, can you please add `maintainers` here? see [document](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#maintainers).

2021-12-30 04:31 UTC, winsoft666 commented on ports/teemo/vcpkg.json
> +  "port-version": 1,
> Since you are the owner, can you please add `maintainers` here? see [document](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#maintainers).

Updated！

2021-12-30 04:39 UTC, JackBoosY commented on versions/t-/teemo.json
> +      "git-tree": "5d9a099bba6f647165ff3b64e69dcc300bacfca9",
```suggestion
      "git-tree": "4d7bc3440769e15a00e84e168257bda517a9f0b2",
```

2021-12-30 04:39 UTC, JackBoosY approved these changes

2021-12-30 04:39 UTC, JackBoosY commented
LGTM.

2021-12-30 04:42 UTC, JackBoosY commented on versions/t-/teemo.json
> +      "git-tree": "4d7bc3440769e15a00e84e168257bda517a9f0b2",
```suggestion
      "git-tree": "d92f8edfaa4c8a208cfa6253c6d2ebd8beeaf303",
```

2021-12-30 04:43 UTC, JackBoosY commented on ports/teemo/vcpkg.json
> +  "maintainers": "winsoft666 <winsoft666@outlook.com>",
```suggestion
  "maintainers": "winsoft666 <winsoft666@outlook.com>",
  "description": "C++ File Download Library, support Multithreading, Breakpoint Transmission, Speed Limit, Real-time Speed.",
  "homepage": "https://github.com/winsoft666/teemo",
```

2021-12-30 17:52 UTC, merged

2021-12-30 17:52 UTC, BillyONeal commented
Thanks for the fix!