[vcpkg-cmake-validate] New port (WIP)
microsoft/vcpkg pull request #22258
Opened 2021-12-30 07:54 UTC by dg0yt

- #### What does your PR fix?  
  This PR is a variation of #15173 (CC @JackBoosY) which also covers 
  - Find module
  - testing with older cmake binaries
  - testing with policies for a minimum cmake version.
  
  It would eventually replace the `cmake-user` port.

  This PR also adds a `vcpkg-maintainer-options` port which can be used to control expensive tests through `vcpkg install` commands. It intentionally avoids a hard (ABI-affecting) dependency on certain parameters of the testing environment (active tests, minimum cmake versions).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I am still working on this PR.

2021-12-30 14:13 UTC, JackBoosY commented
Can I draft this PR until it's ready for review?

2021-12-31 07:21 UTC, dg0yt commented
> Can I draft this PR until it's ready for review?

It was meant to be a draft.

2022-01-09 11:34 UTC, dg0yt commented
I would really like to use this now for every port I update.

2022-01-10 03:34 UTC, JackBoosY commented
Any PR that contributes to the port's robustness is supported.

2022-01-10 05:16 UTC, dg0yt commented
For illustration, extra output from CI:
~~~
-- Using D:/buildtrees/vcpkg-maintainer-options/cmake-3.4.3-win32-x86
-- (1) Validating `find_package(CURL MODULE)`, libraries: CURL_LIBRARIES, CMake 3.4.3+3.21.1
-- (2) Validating `find_package(CURL CONFIG)`, libraries: CURL::libcurl, CMake 3.4.3+3.21.1
-- (3) Validating `find_package(CURL MODULE COMPONENTS HTTP libz HTTPS SSL)`, libraries: CURL::libcurl, CMake 3.21.1
~~~

2022-01-11 07:48 UTC, dg0yt commented
FTR the test is now always executed (at least with the current version). If desired, control might be established via another `vcpkg-maintainer-options` feature so that the test would be skipped for normal users.

2022-01-12 00:04 UTC, strega-nil-ms requested changes
This is what I see for now; I'll review again once these changes are made.

2022-01-12 00:04 UTC, strega-nil-ms commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
I do not like this argument; it is really difficult to guarantee in C++, and even in C it's suspect. I'd prefer to remove it.

2022-01-12 00:04 UTC, strega-nil-ms commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [CMAKE_PROLOG <cmake statements>...]
```suggestion
    [CMAKE_PROLOGUE <cmake statements>...]
```

you should also `s/PROLOG/PROLOGUE` generally

2022-01-12 00:04 UTC, strega-nil-ms commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [CMAKE_VERSION <version>]
```suggestion
    [CMAKE_MINIMUM_VERSION <version>]
```

2022-01-12 04:45 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
What do you propose to create symbols that actually need to be resolved during linking:
~~~
    CODE [[ ... ]]
~~~
or entire source code files?

2022-01-14 07:53 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [CMAKE_PROLOG <cmake statements>...]
FTR there used to be `PROLOG` in https://cmake.org/cmake/help/v3.21/module/WriteCompilerDetectionHeader.html?highlight=prolog.

2022-01-17 07:11 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [LIBRARIES <targets or variable names>...]
Done, but with `TARGETS` (because it needs targets) and `LIBRARIES_VARIABLES` (because it should normally be used with `<Pkg>_LIBRARIES` output variables, not with `<Pkg>_LIBRARY` cache variables).

2022-01-17 07:37 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [CMAKE_PROLOG <cmake statements>...]
Done.

2022-01-17 07:37 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [CMAKE_VERSION <version>]
Done.

2022-01-19 21:19 UTC, strega-nil-ms commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
I would prefer nothing at all; this isn't a CMake thing, it's a C++ thing, imo.

2022-01-20 04:50 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
It is needed now, not at some point in time. In particular due to the vcpkg's decision to focus on static for linux and osx: It is a minimal introspection into the completeness and order of the static usage requirements. It is something which is regularly found to be broken in vcpkg ports.

2022-01-20 05:37 UTC, JackBoosY commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
@strega-nil-ms The option `FUNCTIONS` is to verify the correctness of the symbols in the generated library，such like `AC_CHECK_LIB` in `configure.ac`.

2022-01-20 06:53 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
See also https://cmake.org/cmake/help/v3.22/module/CheckSymbolExists.html#module:CheckSymbolExists

2022-01-20 07:30 UTC, dg0yt commented on ports/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake
> +    [FUNCTIONS <function1> ...]
Just using my port to develop an unofficial poppler cmake export: Together with `HEADERS`, this part of the test discovered the missing export of include directories:
~~~
-- (1) Validating `find_package(unofficial-poppler)`, targets: unofficial::poppler, CMake 3.21.1+
CMake Error at installed/x64-linux/share/vcpkg-cmake-validate/z_vcpkg_cmake_validate_build.cmake:131 (message):
    CMake 3.21.1: `find_package()` validation failed at build step for 'Release'.
    See logs for more information:
      /home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/poppler/checks/validate-1-find_package_unofficial_poppler_targets_unofficial_poppler-3.21.1-x64-linux-build-out.log
      /home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/poppler/checks/validate-1-find_package_unofficial_poppler_targets_unofficial_poppler-3.21.1-x64-linux-build-err.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake-validate/vcpkg_cmake_validate.cmake:170 (z_vcpkg_cmake_validate_build)
  ports/poppler/portfile.cmake:50 (vcpkg_cmake_validate)
  scripts/ports.cmake:142 (include)


CMake Error at installed/x64-linux/share/vcpkg-cmake-validate/z_vcpkg_cmake_validate_build.cmake:131 (message):
    CMake : `find_package()` validation failed at build step for 'Release'.
    See logs for more information:
      /home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/poppler/checks/validate-1-find_package_unofficial_poppler_targets_unofficial_poppler--x64-linux-build-out.log
      /home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/poppler/checks/validate-1-find_package_unofficial_poppler_targets_unofficial_poppler--x64-linux-build-err.log
~~~

with this ...-build-err.log:
~~~
[1/2] Building CXX object CMakeFiles/main.dir/src.cxx.o
FAILED: CMakeFiles/main.dir/src.cxx.o 
/usr/bin/c++ -DCURL_STATICLIB -isystem /home/dg0yt/Projekte/vcpkg/vcpkg/installed/x64-linux/include -O3 -DNDEBUG -pthread -MD -MT CMakeFiles/main.dir/src.cxx.o -MF CMakeFiles/main.dir/src.cxx.o.d -o CMakeFiles/main.dir/src.cxx.o -c /home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/poppler/checks/validate-1-find_package_unofficial_poppler_targets_unofficial_poppler--x64-linux/src.cxx
/home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/poppler/checks/validate-1-find_package_unofficial_poppler_targets_unofficial_poppler--x64-linux/src.cxx:3:10: fatal error: poppler/cpp/poppler-version.h: No such file or directory
 #include <poppler/cpp/poppler-version.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
~~~

2022-01-20 20:48 UTC, dg0yt commented
Thanks for the pointer. Picking out  the "TODOs".

> `#   1. Use the actual vcpkg toolchain file.`

The one in vcpkg root? Done.

> `# 2. Select a generator in the same method as vcpkg_configure_cmake() as though the PREFER_NINJA flag was always passed.`

I don't understand why it should be the same generator. This might be relevant if the cmake toolchain would only be used in ports. But I was looking on how a user would consume an installed package. You don't ask him to use the same generator. 

> `#   3. Fully emulate the toolchain file for the just-built package (just adding it to CMAKE_PREFIX_PATH is not enough).`

I touch one of the dragons here, loading `vcpkg-cmake-wrapper.cmake` directly from the staging directory (`packages`) instead of calling `find_package` through the vcpkg toolchain.
This implementation won't work if more than one wrapper from the tested port is need to resolve a `find_package` call. A robust implementation needs adjustments in `vcpkg.cmake` to make the staged package testable.
And this topic might touch all variables where `vcpkg.cmake` adds paths.

2022-01-21 08:39 UTC, dg0yt commented
Hm, this is really something which is desperately needed. While trying to deal with poppler, I just stumble over fontconfig wrapper bugs. (Not to mention all the missing policy stuff...)

I will be reverting and adding port updates in this PR, for history, evaluation, and cherry-picking.

---

There is no hurry to resolve every implementation detail now. However it would be good to discuss the interface. 
- Parameter `FIND_PACKAGE` is fine if a single package is enough. Is there a use case for multiple packages (without dependencies)?
- Parameter `SYMBOLS` restricts what can be tested. I tend to a more generic solution like `C_SOURCE` etc. (With `SYMBOLS`, I just hit a wall where the named function had overloads.

2022-02-14 05:03 UTC, dg0yt commented
PING @BillyONeal @ras0219-msft @strega-nil-ms 

I really don't want to submit more PRs without tested usage so help define at least the interface.

2022-02-14 05:12 UTC, BillyONeal commented
> > `#   3. Fully emulate the toolchain file for the just-built package (just adding it to CMAKE_PREFIX_PATH is not enough).`
> 
> I touch one of the dragons here, loading `vcpkg-cmake-wrapper.cmake` directly from the staging directory (`packages`) instead of calling `find_package` through the vcpkg toolchain. This implementation won't work if more than one wrapper from the tested port is need to resolve a `find_package` call. A robust implementation needs adjustments in `vcpkg.cmake` to make the staged package testable. And this topic might touch all variables where `vcpkg.cmake` adds paths.

Last we looked at this I think we were still worried about this issue. Because this has been added and removed before we are nervous about opening this can of worms.

===================

Looking again if the interface is really "if this other port is installed first then additional checks happen" then that makes install path dependent which I don't think is OK. We can hook up an additional tool parameter akin to our prohibit-backcompat-features stuff if necessary, pretty cheaply. I would like people who understand those dragons to be happy before dropping everything to unblock you on that though.

2022-02-16 18:25 UTC, dg0yt commented
> Looking again if the interface is really "if this other port is installed first then additional checks happen" then that makes install path dependent which I don't think is OK.

In general I do agree. However, the *check* is not a *fixup*. It has no side-effect on the package content and dependencies. It just adds extra conditions for the build result to be accepted.

In particular, given expected frequent usage, I would very much like to decouple the testing facility from the package ABI hash, to not trigger mandatory world rebuilds from check improvements. This may need more work, and it could use a different interface, completely avoiding the port dependency.

> Because this has been added and removed before we are nervous about opening this can of worms.

The current can of worms is that package quality is a lottery. No option to force validation of cmake or pkg-config usage. No option to run the tests provided by the packages themselves. There is vcpkg's whole-universe CI, but this isn't a sufficient substitute for valdiating the usage contract of individual packages. The wrappers may break without notice when a CMake update brings an updated Find module.

2022-02-16 18:29 UTC, BillyONeal commented
>In general I do agree. However, the check is not a fixup. It has no side-effect on the package content and dependencies. It just adds extra conditions for the build result to be accepted.

Sure, neither does `--prohibit-backcompat-features`.

>In particular, given expected frequent usage, I would very much like to decouple the testing facility from the package ABI hash, to not trigger mandatory world rebuilds from check improvements. This may need more work, and it could use a different interface, completely avoiding the port dependency.

Right, the interface I'm arguing for is a command line parameter.

>The current can of worms is that package quality is a lottery. No option to force validation of cmake or pkg-config usage. No option to run the tests provided by the packages themselves. There is vcpkg's whole-universe CI, but this isn't a sufficient substitute for valdiating the usage contract of individual packages. The wrappers may break without notice when a CMake update brings an updated Find module.

Yes, I agree that the lack of testing situation is a problem.

2022-02-16 18:40 UTC, dg0yt commented
> Right, the interface I'm arguing for is a command line parameter. 

The downside of a parameter, apart from requiring changes in the tool, is that I would have to add it permanently. Unless I missed a configuration file which is always read.

FTR I could also use `find_package(vcpkg-cmake-validate 1) \n if(vcpkg-cmake-validate_FOUND)` to discover if a particular test is enabled and a compatible version is available.

2022-02-16 18:41 UTC, BillyONeal commented
> > Right, the interface I'm arguing for is a command line parameter.
> 
> The downside of a parameter, apart from requiring changes in the tool, is that I would have to add it permanently. Unless I missed a configuration file which is always read.

We could give it an environment variable?

2022-02-16 18:51 UTC, dg0yt commented
> We could give it an environment variable?

Okay, I could add it to my `.profile`. 
It would probably work well also for CI. (Even with extra parameters added to an existing AZP pipeline.)

2022-02-17 06:31 UTC, JackBoosY commented
We do need to add these test functions to ensure the correctness of the port, but the extra time cost should not be borne by the user.
My suggestion is to only enable it in our pipeline tests with --editable mode.

2022-02-17 06:36 UTC, dg0yt commented
> We do need to add these test functions to ensure the correctness of the port, but the extra time cost should not be borne by the user.

Everybody agrees, and nobody proposes something different.

> My suggestion is to only enable it in our pipeline tests with --editable mode.

`--editable` has a different meaning. It affects only the current package. It doesn't work for `vcpkg ci`.

2022-02-17 07:07 UTC, JackBoosY commented
> --editable has a different meaning. It affects only the current package. It doesn't work for vcpkg ci.

I mean both of them, we may need to add an extra cmake flag in vcpkg-tool to enable those tests, such as `VCPKG_ENABLE_TESTS`.
The reason for needing to support --editable is that we can test the port while doing port development or repair work, so we only need to target the current port.

2022-02-17 19:36 UTC, BillyONeal commented
@ras0219 @ras0219-msft indicates that if we're going to make this optional that it is likely a good idea to separate this from `portfile.cmake` entirely so that we can more easily run this as a post-build check, for example after a binary cache restore. (And also to create space in the future where we would probably want to be in the business of running ports' unit tests themselves where reasonble)

2022-02-19 11:23 UTC, dg0yt commented
> to make sure you have the feedback you need otherwise regarding our hesitancy due to history with `vcpkg_test_cmake`.

I feel like there is still a gap between rejecting this PR and defining the interface of what could be submitted as the next PR with a reasonable chance of acceptance.

So let me give you some options.

The key aspect is the entry point for port usage tests. Some ideas:

- `porttest.cmake` file
  To be run in script mode, similar but independent of `portfile.cmake`. 
  May easily build multiple child projects via "maintainer functions".
  May easily use an alternative version of CMake for some tests.
  May run either on a staged or on an installed port.
- `porttest\CMakelists.txt` file
  To be run in with the vcpkg toolchain on an installed port. (With some extra hooks, it might also work on a staged port.)
  May need to use `ExternalProject` to decouple multiple tests or alternative CMake versions.
  May use support functions via `include` or `find_package`.
  Alternative CMake versions could be deduced from the `cmake_minimum_required` statement.
- `porttest` directory hosting multiple scripts or subdirs.

FTR regular post-build checks run on the staged port (in `packages` but not in `installed`). IIUC The package artifact (for caching) is created after the post-build checks, and the package is installed after that. So it is difficult to use the same check as a post-build gate and after installation from a cached artifact.

Another aspect mentioned in the comments is running ports' unit tests. This must happen while building the package, from `portfile.cmake`. Some ideas:
- A script mode variable, e.g. `VCPKG_ENABLE_TESTING` (similar to CMake's `ENABLE_TESTING`). 
- A special feature, e.g. `tests` (similar to the special feature `core`).

2022-02-19 18:22 UTC, BillyONeal commented
> I feel like there is still a gap between rejecting this PR and defining the interface of what could be submitted as the next PR with a reasonable chance of acceptance.

Right, the bits @vicroms is on the hook to verify is making sure how the actual validation works works; after that's OK we can relatively easily hook it up to any interface.

No desire to "reject" the PR.

2022-04-05 07:58 UTC, dg0yt commented
I will merge master ASAP.

> making sure how the actual validation works

Does the validation work? It verifies some working cases, but we cannot prove that it detects all broken cases.
What I can say is that I permanently detect broken ports which would have been easily detected.

Ideally, the tests would run after installation to `installed`. This would avoid some complications, and it would better reflect the user's scenario. However, all current checks, and the upload of the binary artifact, seem to take place before this step.

2022-06-17 08:31 UTC, JackBoosY commented
Can you please merge to master first?

2022-07-16 04:03 UTC, vicroms commented
> Ideally, the tests would run after installation to `installed`. This would avoid some complications, and it would better reflect the user's scenario. However, all current checks, and the upload of the binary artifact, seem to take place before this step.

This is the same conclusion the team has reached. We would like to change CI to insert the CMake validation step after everything is laid out in `installed/` and before uploading to the binary cache.

2022-12-26 19:04 UTC, Thomas1664 commented
I really like this PR but I think there are a few issues that have not been discussed yet:

**Feel free to correct me if any of my points is wrong.**

- Do we have enough CI budget for these tests, i.e. how long do they take?
- Maintenance overhead: We have to manually keep track of installed headers/ symbols/ targets that might change during port updates
  - We have to proactively touch a port in order to find bugs which is hard given that there are ~ 2K ports. It would be easier if we had a tool that automatically scans all ports for bugs. In contrast, with this approach we only observe a bug after actively searching for them, i. e. using `vcpkg_cmake_validate`.
- It is inefficient to test only one symbol at a time
  - However, this might be required to make sure there is no interference between individual tests
  - It is well known that extensive check symbol executions slow down configure time
  - Ideally, we would test all symbols of a port in one go or even multiple ports in one go
- Do we really need to perform a compilation in order to test `vcpkg_cmake_wrapper` and `find_package()`?
  - Isn't the configure step enough to tell that a package is found? We could observe the variables that `find_package` sets if it finds a package?
  - Is it possible to tell by analysing the installed CMake config/ `vcpkg_cmake_wrapper` that everything is set up correctly?
- Is it possible to detect weither a package comes from somewhere else than vcpkg?

2022-12-26 22:54 UTC, dg0yt commented
@Thomas1664 I can't correct you if you ask questions. Regarding the  magic bug scanning tool: vcpkg even fails to derive quality usage hints.

I'm not worried by CI time. I'm worried about how many ports turn out to be unusable despite hundreds of CI runs, and no way to protect my voluntary work (read: my time!) against regressions.

I would prefer to have half the number of ports but twice the quality. Cross-platform.

2022-12-26 23:42 UTC, Thomas1664 commented
> Regarding the magic bug scanning tool: vcpkg even fails to derive quality usage hints.

> I'm worried about how many ports turn out to be unusable despite hundreds of CI runs, and no way to protect my voluntary work (read: my time!) against regressions.

You could put them on CI baseline if there are too many regressions.

The problem with this approach is that it doesn't scale well because you have to explicitly add tests and I'm afraid only a few people actually would use this. Like there are many ports that use `vcpkg_configure_cmake` although this function is deprecated for more than a year.

I think it would be easier to implement this check inside the vcpkg-tool via C++. The only tricky part would be to find symbols to use for testing. The tool [nm](https://linux.die.net/man/1/nm) (installed by default on Linux) can help with this. With nm we can get the symbol table of a .a/ .lib/.so/.dll/.dylib file: `nm libbz2.a --demangle --defined-only`.

2022-12-28 21:22 UTC, BillyONeal commented
> The problem with this approach is that it doesn't scale well because you have to explicitly add tests

We have code review for this.

2023-01-19 21:22 UTC, BillyONeal commented
Checking up on this again because it was tagged requires vcpkg-team-review:

* We remain interested in some way for ports to test the things tested here.
* The problem that the installation happens after `portfile.cmake` finishes running and therefore `portfile.cmake` can't see the actually installed state and as a result can't truly test this remains.
* We are considering adding features like this to the tool in the future, and when we do so we will come back to this PR to make sure the use cases it intends to test are fixed.

2023-01-21 11:53 UTC, dg0yt commented
FWIW I added CI test ports to cover critical port and feature configurations, after installation. As long as this isn't blocked, I can arrange with that state.

2023-01-21 11:53 UTC, closed without merging