Use boost's correct .jam file.
microsoft/vcpkg pull request #22274
Opened 2021-12-31 09:29 UTC by Nemirtingas

Use boost's clang-win.jam configuration file when using Clang-cl to allow cross-compilation for Windows.

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #22232

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Same as before but allows for cross-compilation on LInux for Windows.
I didn't update ci.baseline.txt.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
I am still working on this PR.

2022-01-03 10:40 UTC, yurybura approved these changes

2022-01-04 03:36 UTC, JackBoosY approved these changes

2022-01-04 06:46 UTC, PhoebeHui approved these changes
LGTM.

2022-01-05 04:06 UTC, strega-nil-ms requested changes

2022-01-05 04:06 UTC, strega-nil-ms commented on ports/boost-modular-build-helper/CMakeLists.txt
> +            endif()
```suggestion
            set(USER_CONFIG_TOOLSET clang-win)
```

this can only be clang-cl in this branch.

2022-01-05 04:06 UTC, strega-nil-ms commented on ports/boost-modular-build-helper/CMakeLists.txt
> +        else(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
```suggestion
        else()
```

2022-01-05 04:06 UTC, strega-nil-ms commented on ports/boost-modular-build-helper/CMakeLists.txt
> +            endif()
```suggestion
        if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            set(USER_CONFIG_TOOLSET clang)
```

same as above

2022-01-05 04:06 UTC, strega-nil-ms commented
just some minor changes!

2022-01-06 03:51 UTC, PhoebeHui approved these changes

2022-01-06 21:54 UTC, strega-nil-ms commented
Thanks!

2022-01-06 21:55 UTC, merged