Spirv reflect port
microsoft/vcpkg pull request #22295
Opened 2022-01-02 16:49 UTC by kleszcz

**Describe the pull request**

- #### What does your PR fix?  
  Adds port for [SPIRV-Reflect](https://github.com/KhronosGroup/SPIRV-Reflect)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  `linux, windows`, `No`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `NO` - working on it

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  `Yes`

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-01-04 06:05 UTC, JonLiu1993 requested changes

2022-01-04 07:28 UTC, JonLiu1993 approved these changes

2022-01-04 07:28 UTC, JonLiu1993 commented
@kleszcz ，Have you tested the usage locally?

2022-01-04 07:32 UTC, kleszcz commented
Hi @JonLiu1993!
Yes, I've it tested locally. Also I use this port in my Vulkan project via vcpkg manifest and it works fine .

2022-01-05 04:02 UTC, strega-nil-ms commented
I need to do deep review on this, so I'm leaving it for tomorrow.

2022-01-06 00:38 UTC, strega-nil-ms requested changes
Otherwise, looks good! I just think we can simplify it by not making our replacement a patch.

2022-01-06 00:38 UTC, strega-nil-ms commented on ports/spirv-reflect/cmake-install.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
This patch seems incredibly complex for what it does; since we're basically completely remaking the CMake build without using almost any of the original stuff, can we just replace CMakeLists.txt wholesale? There's no need for example or test building, as an example.

2022-01-09 10:36 UTC, kleszcz commented on ports/spirv-reflect/cmake-install.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
Hi @strega-nil-ms, sure I can do that. I was considering this option after finding that glm is doing exactly that - I will implement the CMakeLists.txt substitution the same way then.

2022-01-10 12:17 UTC, JonLiu1993 requested changes

2022-01-11 03:07 UTC, JonLiu1993 approved these changes

2022-01-11 03:08 UTC, JonLiu1993 commented
@strega-nil-ms ,Could you please take a look?

2022-01-14 06:09 UTC, JonLiu1993 approved these changes

2022-01-14 23:29 UTC, BillyONeal requested changes
These are mostly just nitpicks, thanks for the port!

2022-01-14 23:29 UTC, BillyONeal commented on ports/spirv-reflect/CMakeLists.txt
> +        $<$<CXX_COMPILER_ID:AppleClang>:-Wall -Werror>)
```suggestion
```

We should not be turning on errors in replaced build systems; vcpkg customers are not generally capable of doing anything about such errors.

2022-01-14 23:29 UTC, BillyONeal commented on ports/spirv-reflect/portfile.cmake
> +endif()
This seems to be duplicating output from the dependency `vulcan` port so I don't know how useful this reporting is; I would remove it. If it stays, I think you need to explain something about how the user can remedy the situation.

2022-01-14 23:29 UTC, BillyONeal commented on ports/spirv-reflect/CMakeLists.txt
> +    EXPORT spirv-reflect-config
When vcpkg makes up these names we usually try to add `unofficial-` as a prefix so that we don't stomp on upstream should they choose to add their own CMake targets. Or is this intended to match upstream exactly? (I see in the history this PR used to not be a complete build replacement)

2022-01-14 23:29 UTC, BillyONeal commented on ports/spirv-reflect/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 14)
This property has no effect because it is overridden on 17.

2022-01-30 03:42 UTC, JonLiu1993 commented
@kleszcz ,Could you please consider @BillyONeal 's suggestion？

2022-02-01 16:22 UTC, kleszcz commented on ports/spirv-reflect/CMakeLists.txt
> +    EXPORT spirv-reflect-config
Should the EXPORT be named `unofficial-spriv-reflect-config` and should I rename the namespace too?

2022-02-07 09:06 UTC, JonLiu1993 commented on ports/spirv-reflect/CMakeLists.txt
> +    EXPORT spirv-reflect-config
```suggestion
    EXPORT unofficial-spirv-reflect-config
```

2022-02-07 09:06 UTC, JonLiu1993 commented on ports/spirv-reflect/CMakeLists.txt
> +    NAMESPACE spirv-reflect::
```suggestion
    NAMESPACE unofficial::spirv-reflect::
```

2022-02-07 09:07 UTC, JonLiu1993 commented on ports/spirv-reflect/CMakeLists.txt
> +    DESTINATION share/spirv-reflect
```suggestion
    DESTINATION share/unofficial-spirv-reflect
```

2022-02-11 00:23 UTC, BillyONeal commented on ports/spirv-reflect/CMakeLists.txt
> +    EXPORT spirv-reflect-config
I believe the "config" name doesn't need the prefix because we can compose that if upstream ever adds official support. (That is, the foo-config can provide both foo and unofficial-foo targets to not break existing customers if we want)

2022-02-11 00:36 UTC, BillyONeal commented
@strega-nil tells me my reply above was incorrect. In order to reduce confusion I've submitted https://github.com/microsoft/vcpkg/pull/23041 to codify what we want. I will push a change consistent with what lands there here if you want me to.

2022-02-11 01:11 UTC, BillyONeal approved these changes

2022-02-11 01:12 UTC, merged