[python2] no absolute paths
microsoft/vcpkg pull request #22329
Opened 2022-01-04 12:33 UTC by autoantwort

For #20469

Like  #21144

2022-01-04 17:09 UTC, JackBoosY approved these changes

2022-01-05 02:55 UTC, strega-nil-ms requested changes
I've made the changes in a local branch, so I'll push.

2022-01-05 03:45 UTC, strega-nil-ms commented
@autoantwort what do you think of my changes?

2022-01-11 02:25 UTC, autoantwort reviewed
Otherwise LGTM!

2022-01-20 17:39 UTC, autoantwort commented on ports/python2/portfile.cmake
> +        string(REPLACE ";" "\\;" old_contents "${contents}")
ping @strega-nil-ms

2022-02-24 06:03 UTC, JackBoosY commented
I will ping Nicole internal.

2022-02-24 17:13 UTC, strega-nil-ms commented on ports/python2/portfile.cmake
> +        string(REPLACE ";" "\\;" old_contents "${contents}")
This line isn't useless, because the line that follows turns newlines into `;`s - if you didn't have this, when you switch back, any semicolons in the original source would be turned into newlines.

2022-02-24 17:14 UTC, strega-nil-ms approved these changes

2022-03-02 21:29 UTC, merged