[kf5windowsystem] no absolute paths
microsoft/vcpkg pull request #22333
Opened 2022-01-04 13:06 UTC by autoantwort

For #20469

2022-01-04 17:06 UTC, JackBoosY requested changes

2022-01-04 17:06 UTC, JackBoosY commented on ports/kf5windowsystem/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/KF5/KWindowSystem/config-kwindowsystem.h" "${CURRENT_PACKAGES_DIR}/" "")
Which code did you replace?

2022-01-04 17:17 UTC, autoantwort commented on ports/kf5windowsystem/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/KF5/KWindowSystem/config-kwindowsystem.h" "${CURRENT_PACKAGES_DIR}/" "")
It changes 
```c++
#define XCB_PLUGIN_PATH "/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/kf5windowsystem_x64-osx/plugins/kf5/kwindowsystem/KF5WindowSystemX11Plugin.so"
```
to 
```c++
#define XCB_PLUGIN_PATH "plugins/kf5/kwindowsystem/KF5WindowSystemX11Plugin.so"
```

2022-01-04 17:21 UTC, JackBoosY approved these changes

2022-01-05 00:54 UTC, strega-nil-ms commented
LGTM! Thanks @autoantwort :)

2022-01-05 00:54 UTC, merged