[openmvg] no absolute paths
microsoft/vcpkg pull request #22342
Opened 2022-01-04 17:45 UTC by autoantwort

For #20469

2022-01-05 08:09 UTC, LilyWangLL approved these changes

2022-01-07 00:46 UTC, strega-nil-ms requested changes
removing `-targets.cmake` looks really wrong...

2022-01-07 00:46 UTC, strega-nil-ms commented on ports/openmvg/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/lib/openMVG-targets.cmake" "${CURRENT_PACKAGES_DIR}/debug/lib/openMVG-targets-debug.cmake")
This looks wrong, but I can't test it because I can't build openMVG on my machine; shouldn't this be fixed up by `vcpkg_cmake_config_fixup`?

2022-01-07 21:37 UTC, strega-nil-ms commented
poke @autoantwort for response

2022-01-08 02:45 UTC, autoantwort commented on ports/openmvg/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/lib/openMVG-targets.cmake" "${CURRENT_PACKAGES_DIR}/debug/lib/openMVG-targets-debug.cmake")
These files are kind of duplicated. `vcpkg_cmake_config_fixup(CONFIG_PATH share/openMVG/cmake)` is called. 
<img width="260" alt="image" src="https://user-images.githubusercontent.com/41973254/148628782-8d17909c-ecee-497b-b586-3b97848ca41c.png">

2022-01-17 08:50 UTC, LilyWangLL commented on ports/openmvg/portfile.cmake
> +    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/lib/openMVG-targets.cmake" "${CURRENT_PACKAGES_DIR}/debug/lib/openMVG-targets-debug.cmake")
Ping @strega-nil-ms

2022-02-14 09:22 UTC, LilyWangLL commented
@autoantwort Could you please resolve the conflicts?

2022-03-02 21:30 UTC, merged