[sqlite3] update to <3.37.1>
microsoft/vcpkg pull request #22365
Opened 2022-01-05 03:13 UTC by FrankXie05

Fix #22353 
[sqlite3] update to 3.37.1
All features have been tested successfullly in the following triplet:

- x64-windows
- x64-windows-static
- x86-windows

2022-01-05 03:15 UTC, FrankXie05 commented on ports/ogre-next/portfile.cmake
> +        csharp  OGRE_BUILD_COMPONENT_CSHARP
Depend on [ogre-next] FEATURES

2022-01-05 03:29 UTC, JonLiu1993 commented on ports/ogre-next/portfile.cmake
>  vcpkg_configure_cmake(
Could you modernize this cmake function？

2022-01-05 03:31 UTC, JonLiu1993 requested changes

2022-01-05 03:31 UTC, JonLiu1993 commented on ports/ogre-next/vcpkg.json
>    "version-string": "2019-10-20",
```suggestion
  "version-date": "2019-10-20",
```

2022-01-05 03:40 UTC, JonLiu1993 commented on ports/ogre-next/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2022-01-05 06:12 UTC, dg0yt commented
IMO the ogre changes should be a separate PR.

2022-01-05 06:40 UTC, FrankXie05 commented
@dg0yt #22058  I have submitted the pr of ogre-next update, and it is waiting for review. And I'll just merge it by then  :)

2022-01-05 07:22 UTC, dg0yt commented
> @dg0yt #22058 I have submitted the pr of ogre-next update, and it is waiting for review. And I'll just merge it by then :)

I still miss the link why there are ogre-next changes in this sqlite3 PR.

2022-01-11 01:46 UTC, FrankXie05 commented
@dg0yt yes it is my problem, it really should be modified in ogre-next instead of sqlite3.  Thanks. :)

2022-01-26 06:23 UTC, FrankXie05 commented
Fix by #22795

2022-01-26 06:23 UTC, closed without merging