[drogon] Fix MySQL finding
microsoft/vcpkg pull request #22378
Opened 2022-01-05 13:04 UTC by kotori2

**Describe the pull request**
#21359 changed paths for libmariadb, which makes drogon fails to find them

- #### What does your PR fix?  
  https://github.com/drogonframework/drogon/issues/1146

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Not touched, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-01-07 01:03 UTC, FrankXie05 approved these changes

2022-01-07 21:52 UTC, strega-nil-ms commented
I really don't like this; I'd much prefer if we fixed libmariadb to support `find_package(MySql)`. Marking requires:discussion so we can talk about it at the thursday meeting.

2022-01-08 10:19 UTC, dg0yt requested changes

2022-01-08 10:19 UTC, dg0yt commented on ports/drogon/libmariadb.patch
> ++    if (unofficial-libmariadb_FOUND)
A minimal patch would just take
~~~patch
     # Find mysql, only mariadb client liberary is supported
-    find_package(MySQL)
+    find_package(unofficial-libmariadb CONFIG REQUIRED)
+    set(MySQL_FOUND TRUE)
+    set(MySQL_lib unofficial::libmariadb)
     if (MySQL_FOUND)
~~~
The `REQUIRED` implies that the build stops if unofficial-libmariadb isn't found.

2022-01-08 10:20 UTC, dg0yt commented
> I really don't like this; I'd much prefer if we fixed libmariadb to support `find_package(MySql)`. Marking requires:discussion so we can talk about it at the thursday meeting.

Note that `FindMySQL.cmake` is part of drogon. It takes a patch anyway.

2022-01-08 10:32 UTC, kotori2 commented on ports/drogon/libmariadb.patch
> ++    if (unofficial-libmariadb_FOUND)
> A minimal patch would just take
> 
> ```diff
>      # Find mysql, only mariadb client liberary is supported
> -    find_package(MySQL)
> +    find_package(unofficial-libmariadb CONFIG REQUIRED)
> +    set(MySQL_FOUND TRUE)
> +    set(MySQL_lib unofficial::libmariadb)
>      if (MySQL_FOUND)
> ```
> 
> The `REQUIRED` implies that the build stops if unofficial-libmariadb isn't found.

I've tried `set(MySQL_FOUND TRUE)` before, but it will throw an error when you are syncing your own project since MySQL can't be found. Does `set(MySQL_lib unofficial::libmariadb)` solve this issue?

2022-01-08 11:09 UTC, dg0yt commented on ports/drogon/libmariadb.patch
> ++    if (unofficial-libmariadb_FOUND)
> I've tried `set(MySQL_FOUND TRUE)` before, but it will throw an error when you are syncing your own project since MySQL can't be found. 

I see.

> Does `set(MySQL_lib unofficial::libmariadb)` solve this issue?

I cannot answer that without know the error message. "syncing your own project " isn't clear. 
But it seems either your project shouldn't directly depend on `MySQL_FOUND` when MySQL actually isn't used, or it is implicitly relying on drogon's `FindMySQL.cmake`, and then you need to patch that script instead.

2022-01-08 11:58 UTC, kotori2 commented on ports/drogon/libmariadb.patch
> ++    if (unofficial-libmariadb_FOUND)
> "syncing your own project " isn't clear.

Actually I mean generating Makefile from CMake after all vcpkg packages installed.

> I cannot answer that without know the error message. 

CMake will generate `DrogonConfig.cmake` in `vcpkg_installed/[triplet]/share/drogon`. It will call `find_dependency(MySQL)`, which will fail since mariadb changed its name. 

Also when trying your patch, I got build error. 
```
FAILED: CMakeFiles/drogon.dir/orm_lib/src/mysql_impl/MysqlConnection.cc.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DUSE_BROTLI -DUSE_OSSP_UUID=0 -I/Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/lib/inc -I/Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/orm_lib/inc -I/Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/nosql_lib/redis/inc -I/Users/kotori0/vcpkg/buildtrees/drogon/x64-osx-dbg -I/Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/trantor -I/Users/kotori0/vcpkg/buildtrees/drogon/x64-osx-dbg/exports -isystem /Users/kotori0/Downloads/test/cmake-build-debug/vcpkg_installed/x64-osx/include -isystem /Users/kotori0/Downloads/test/cmake-build-debug/vcpkg_installed/x64-osx/include/uuid -isystem /Library/Frameworks/Mono.framework/Headers -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -std=c++17 -MD -MT CMakeFiles/drogon.dir/orm_lib/src/mysql_impl/MysqlConnection.cc.o -MF CMakeFiles/drogon.dir/orm_lib/src/mysql_impl/MysqlConnection.cc.o.d -o CMakeFiles/drogon.dir/orm_lib/src/mysql_impl/MysqlConnection.cc.o -c /Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/orm_lib/src/mysql_impl/MysqlConnection.cc
In file included from /Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/orm_lib/src/mysql_impl/MysqlConnection.cc:15:
/Users/kotori0/vcpkg/buildtrees/drogon/src/v1.7.4-3e6a1930a1.clean/orm_lib/src/mysql_impl/MysqlConnection.h:25:10: fatal error: 'mysql.h' file not found
#include <mysql.h>
         ^~~~~~~~~
1 error generated.
```

2022-01-08 14:00 UTC, dg0yt commented on ports/drogon/libmariadb.patch
> ++    if (unofficial-libmariadb_FOUND)
`MySQL_lib` is a target, so my proposed `set(MySQL_lib ...)` can't help - sorry for the confusion. Your change to the `target_link_libraries` is already the right thing at this point.

Variable or not, when linking `unofficial::libmariadb` while building, the exported config will link to `unofficial::libmariadb`, too. So you need to replace the `find_dependency(MySQL)` with `find_dependency(unofficial-libmariadb)`.

(@strega-nil-ms proposed to only patch `FindMySQL.cmake`. It is possible to handle the redirection entirely in that module, but it might be even more confusing when something goes wrong.)

I wanted to attach a test patch now, but I just run into another build issue with drogon. Either you try yourself again, or you wait a moment.

2022-01-11 06:24 UTC, dg0yt commented
This PR is obsolete now with #22426 merged. But many thanks for the initial work and discussion @kotori2.

2022-01-11 07:58 UTC, JackBoosY commented
Can you please resolve the file conflict?

2022-01-11 08:11 UTC, closed without merging