Add CppXaml package
microsoft/vcpkg pull request #22414
Opened 2022-01-08 07:28 UTC by asklar

**Describe the pull request**
Adds the CppXaml library

- #### What does your PR fix?  

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 windows, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
 Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-01-10 09:27 UTC, JonLiu1993 requested changes

2022-01-10 09:27 UTC, JonLiu1993 commented on ports/cppxaml/vcpkg.json
> +  "version-string": "0.0.16",
```suggestion
  "version": "0.0.16",
```

2022-01-13 01:12 UTC, JonLiu1993 approved these changes

2022-01-13 17:17 UTC, strega-nil-ms commented
Thanks!

2022-01-13 17:17 UTC, merged