[FLTK] Update to 1.3.8
microsoft/vcpkg pull request #22487
Opened 2022-01-11 20:57 UTC by gvnnz

Updates FLTK to version 1.3.8. Opened as draft because of point 2 (see below).

- #### What does your PR fix?  
Nothing, just updates the port.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Tested on Linux. Proper testing is needed on other platforms. 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
 Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes.

2022-01-12 03:02 UTC, JonLiu1993 requested changes

2022-01-12 12:59 UTC, gvnnz commented on ports/fltk/vcpkg.json
>    "port-version": 1,
Done.

2022-01-12 13:01 UTC, gvnnz commented on ports/fltk/fltk_version.dat
> -1.3.7
No idea honestly: I thought this was something required by vckpg. I removed it and FLTK installed just fine.

2022-01-12 13:37 UTC, JonLiu1993 commented
@gvnnz ,Please run command "./vcpkg x-add-version fltk --overwrite-version" and commit again

2022-01-12 22:14 UTC, gvnnz commented
> ports/fltk/fltk_version.dat

Done.

2022-01-13 04:48 UTC, JonLiu1993 requested changes

2022-01-13 04:48 UTC, JonLiu1993 commented on versions/f-/fltk.json
> +    },
```suggestion
```

2022-01-13 04:48 UTC, JonLiu1993 commented on versions/f-/fltk.json
> +    },
I don't have permission to modify this for you, please run the command "./vcpkg x-add-version fltk --overwrite-version" and commit again after the modification is complete

2022-01-14 02:41 UTC, JonLiu1993 requested changes

2022-01-14 02:41 UTC, JonLiu1993 commented on versions/f-/fltk.json
> +    },
```suggestion
```

2022-01-14 02:41 UTC, JonLiu1993 commented on versions/f-/fltk.json
> +    },
We only need to add git-tree once per merge, so that we can go back to our historical version later

2022-01-20 09:56 UTC, JonLiu1993 approved these changes

2022-01-20 22:05 UTC, strega-nil-ms commented
Thanks!

2022-01-20 22:05 UTC, merged