[libgpod] only linux
microsoft/vcpkg pull request #22561
Opened 2022-01-16 21:41 UTC by autoantwort

2022-01-17 03:07 UTC, LilyWangLL requested changes

2022-01-17 03:07 UTC, LilyWangLL commented on scripts/ci.baseline.txt
>  libgpod:x64-linux=fail
```suggestion
```
`libgpod` supports Linux, this code needs be removed. But `libgpod` build failed with the following error now, could you please check and fix?
```
Building package libgpod[core]:x64-linux...
-- Downloading https://github.com/fadingred/libgpod/archive/4a8a33ef4bc58eee1baca6793618365f75a5c3fa.tar.gz -> fadingred-libgpod-4a8a33ef4bc58eee1baca6793618365f75a5c3fa.tar.gz...
-- Extracting source /home/vlilywang/Lily/0117/vcpkg/downloads/fadingred-libgpod-4a8a33ef4bc58eee1baca6793618365f75a5c3fa.tar.gz
-- Applying patch configure.ac.patch
-- Using source at /home/vlilywang/Lily/0117/vcpkg/buildtrees/libgpod/src/5f75a5c3fa-9e39aa1f67.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: intltoolize --force --copy --automake
    Working Directory: /home/vlilywang/Lily/0117/vcpkg/buildtrees/libgpod/src/5f75a5c3fa-9e39aa1f67.clean
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  ports/libgpod/portfile.cmake:12 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)
```

2022-01-20 19:39 UTC, autoantwort commented on scripts/ci.baseline.txt
>  libgpod:x64-linux=fail
Hm I have no linux to test this currently

2022-01-20 19:40 UTC, autoantwort commented on scripts/ci.baseline.txt
>  libgpod:x64-linux=fail
I also have not changed anything

2022-01-29 15:55 UTC, autoantwort commented
This change was done by another PR

2022-01-29 15:55 UTC, closed without merging