Update zxing-cpp port
microsoft/vcpkg pull request #22657
Opened 2022-01-20 18:20 UTC by joiskash

**Describe the pull request**

- #### What does your PR fix?  
This  Fixes #10503. It is a closed PR. I cannot reopen it .

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  It supports all but I have tried it only on x64-windows. No I have not updated the baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes, but need to update helpers WIP

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I am still working on this PR

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-01-21 03:31 UTC, JonLiu1993 requested changes

2022-01-21 03:31 UTC, JonLiu1993 commented on ports/zxing-cpp/vcpkg.json
> +  "port-version": 4,
```suggestion
  "version": "1.2.0",
```

2022-01-21 05:24 UTC, dg0yt commented
What is it doing with git and ExternalProject? Please no hidden downloads and vendored dependencies.

2022-01-21 05:29 UTC, joiskash commented
> What is it doing with git and ExternalProject? Please no hidden downloads and vendored dependencies.

https://github.com/nu-book/zxing-cpp/blob/master/test/blackbox/CMakeLists.txt 

```
if (NOT fmt_FOUND)
    include(FetchContent)
    FetchContent_Declare (fmtlib
            GIT_REPOSITORY https://github.com/fmtlib/fmt.git
            GIT_TAG 8.0.1)
    FetchContent_MakeAvailable (fmtlib) # Adds fmt::fmt
endif()
```

This is not part of the core. It is part of test/blackbox we could probably just remove it

2022-01-21 05:31 UTC, joiskash commented
I tried to add fmt as a dependency in the manifest file, that did not help.

2022-01-21 05:59 UTC, dg0yt commented
Thanks for the response. Apart from tests being generally skipped in vcpkg ports, it should really use vcpkg's `fmt` if needed.
It provides cmake config including `fmt::fmt`, so it must work.

Looking around, it seems that `BUILD_SYSTEM_DEPS` should be set to `ALWAYS` (actually meaning to always *use* system dependencies instead of vendored dependencies).
https://github.com/nu-book/zxing-cpp/blob/485a72b73fe549a623bf3cf7220c58bf6c1b1cdb/CMakeLists.txt#L11

2022-01-21 11:06 UTC, joiskash commented
Cant get the uwp builds to succeed . Will try on local system..

2022-01-24 09:04 UTC, JonLiu1993 commented on ports/zxing-cpp/portfile.cmake
> +if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
```suggestion
if(VCPKG_TARGET_IS_UWP)
```

2022-01-24 09:04 UTC, JonLiu1993 commented on ports/zxing-cpp/portfile.cmake
> +        SOURCE_PATH ${SOURCE_PATH}
```suggestion
        SOURCE_PATH "${SOURCE_PATH}"
```

2022-01-24 09:04 UTC, JonLiu1993 commented on ports/zxing-cpp/portfile.cmake
> +        SOURCE_PATH ${SOURCE_PATH}
```suggestion
        SOURCE_PATH "${SOURCE_PATH}"
```

2022-01-24 09:05 UTC, JonLiu1993 commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY ${SOURCE_PATH}/zxing.pc.in DESTINATION ${CURRENT_PACKAGES_DIR}/lib/pkgconfig)
```suggestion
    file(COPY "${SOURCE_PATH}/zxing.pc.in" DESTINATION "${CURRENT_PACKAGES_DIR}/lib/pkgconfig")
```

2022-01-24 09:05 UTC, JonLiu1993 commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY ${SOURCE_PATH}/zxing.pc.in DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig)
```suggestion
    file(COPY "${SOURCE_PATH}/zxing.pc.in" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig")
```

2022-01-24 09:06 UTC, JonLiu1993 commented on versions/z-/zxing-cpp.json
> +    },
```suggestion
```

2022-01-24 09:19 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +        SOURCE_PATH ${SOURCE_PATH}
done

2022-01-24 09:19 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +        SOURCE_PATH ${SOURCE_PATH}
done

2022-01-24 09:19 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY ${SOURCE_PATH}/zxing.pc.in DESTINATION ${CURRENT_PACKAGES_DIR}/lib/pkgconfig)
done

2022-01-24 09:19 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY ${SOURCE_PATH}/zxing.pc.in DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig)
done

2022-01-24 09:19 UTC, joiskash commented on versions/z-/zxing-cpp.json
> +    },
done

2022-01-24 09:20 UTC, JonLiu1993 approved these changes

2022-01-24 09:22 UTC, JonLiu1993 commented
Please run command "./vcpkg x-add-version zxing-cpp --overwrite-version" and commit again

2022-01-24 09:33 UTC, joiskash commented
Thanks for the quick review! @JonLiu1993

2022-01-24 10:11 UTC, dg0yt requested changes

2022-01-24 10:11 UTC, dg0yt commented on ports/zxing-cpp/portfile.cmake
> +            -DCMAKE_CXX_FLAGS=-wd4996
Duplicate option. (Is this the right way to set flags?)

2022-01-24 10:11 UTC, dg0yt commented on ports/zxing-cpp/portfile.cmake
> +endif()
I would prefer a single vcpkg_cmake_configure, with parameters as needed.

2022-01-24 10:11 UTC, dg0yt commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY "${SOURCE_PATH}/zxing.pc.in" DESTINATION "${CURRENT_PACKAGES_DIR}/lib/pkgconfig")
Did you check the content if copying without configuration is really enough? (version, libary names)

2022-01-24 10:42 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +            -DCMAKE_CXX_FLAGS=-wd4996
Oh dont know how that happened. Removing the duplicate.

2022-01-24 10:48 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +endif()
So we do not need to send the -wd4996 flag for windows x64 x86 , osx and linux builds. It is only passed to ask Visual studio 2019 to ignore deprecated function errors. Im not sure how to do this with just one vcpkg_cmake_configre. The flags need to be passed separately. If you look at the Readme, It says that to build for [uwp](https://github.com/nu-book/zxing-cpp#windows-universal-platform), you need to use the [CMakeList in wrapper/winrt/](https://github.com/nu-book/zxing-cpp/blob/master/wrappers/winrt/CMakeLists.txt) . And in that you will see that they add the -wd4996 flag using add_definitions . Let me know what the appropriate way is to handle this.

2022-01-24 11:18 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +            -DCMAKE_CXX_FLAGS=-wd4996
Yes this seems to be the right way.. https://github.com/nu-book/zxing-cpp/blob/master/CMakeLists.txt line number 23

2022-01-24 11:19 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY "${SOURCE_PATH}/zxing.pc.in" DESTINATION "${CURRENT_PACKAGES_DIR}/lib/pkgconfig")
Checking it now on a linux systme, will update it once I move the right file. Ill need to copy the zxing.pc file from CMAKE_CURRENT_BINARY_DIR/ . Also I realized this needs to be copied only for !WIN32

reference: line 106 https://github.com/nu-book/zxing-cpp/blob/master/CMakeLists.txt

2022-01-24 11:35 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +    file(COPY "${SOURCE_PATH}/zxing.pc.in" DESTINATION "${CURRENT_PACKAGES_DIR}/lib/pkgconfig")
Looks like cmake takes care of all of this. And vcpkg_fixup_pkgconfig(). I have removed this file copy.

2022-01-25 07:54 UTC, JackBoosY requested changes

2022-01-25 07:54 UTC, JackBoosY commented on ports/zxing-cpp/portfile.cmake
> +endif()
```cmake
set(EXTRA_CONFIGURE_OPTIONS )
set(EXTRA_OPTIONS )
if (VCPKG_TARGET_IS_UWP)
   set(EXTRA_CONFIGURE_OPTIONS WINDOWS_USE_MSBUILD)
    set(EXTRA_OPTIONS -DCMAKE_CXX_FLAGS=-wd4996)
endif()
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    ${EXTRA_CONFIGURE_OPTIONS}
        OPTIONS
        -DBUILD_BLACKBOX_TESTS=OFF
        -DBUILD_EXAMPLES=OFF
        ${EXTRA_OPTIONS}
)
```

2022-01-25 07:54 UTC, JackBoosY commented on ports/zxing-cpp/portfile.cmake
> +endif()
In fact we should patch the source to add `target_compile_definitions(... _CRT_SECURE_NO_WARNINGS)` instead of this changes.

2022-01-25 08:20 UTC, joiskash commented
@JackBoosY Line 26 of https://github.com/nu-book/zxing-cpp/blob/master/core/CMakeLists.txt already does this.

2022-01-25 10:28 UTC, joiskash commented
> > @JackBoosY Line 26 of https://github.com/nu-book/zxing-cpp/blob/master/core/CMakeLists.txt already does this.
> 
> So I assume we don't need add `/wd4996`.

We still need it. The build fails without it. Below is a snippet of the [error logs](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/66291/artifacts?artifactName=failure%20logs%20for%20x64-uwp&api-version=7.0&%24format=zip)

>    D:\buildtrees\zxing-cpp\src\v1.2.0-e91bbfd983.clean\core\src\Result.cpp(48,33): error C4996: 'ZXing::ResultMetadata::STRUCTURED_APPEND_SEQUENCE': was declared deprecated [D:\buildtrees\zxing-cpp\x64-uwp-dbg\core\ZXing.vcxproj]
         D:\buildtrees\zxing-cpp\src\v1.2.0-e91bbfd983.clean\core\src\Result.cpp(49,33): error C4996: 'ZXing::ResultMetadata::STRUCTURED_APPEND_CODE_COUNT': was declared deprecated [D:\buildtrees\zxing-cpp\x64-uwp-dbg\core\ZXing.vcxproj]
         D:\buildtrees\zxing-cpp\src\v1.2.0-e91bbfd983.clean\core\src\Result.cpp(51,34): error C4996: 'ZXing::ResultMetadata::STRUCTURED_APPEND_PARITY': was declared deprecated [D:\buildtrees\zxing-cpp\x64-uwp-dbg\core\ZXing.vcxproj]

Also this is also what is mentioned in the reply to your comment above about the flag being set in the [CMakeList](https://github.com/nu-book/zxing-cpp/blob/master/wrappers/winrt/CMakeLists.txt) found in /wrappers/winrt.

2022-01-26 03:45 UTC, JackBoosY requested changes

2022-01-26 03:45 UTC, JackBoosY commented on ports/zxing-cpp/portfile.cmake
> +    REPO nu-book/zxing-cpp
I also noticed that you changed the repo, why?

2022-01-26 04:05 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +    REPO nu-book/zxing-cpp
That repo is very old. As mentioned in the closed issue that i have linked to this PR #10503, this new repo is more well maintained, with the latest features.

2022-01-26 08:28 UTC, JackBoosY commented on ports/zxing-cpp/portfile.cmake
> +    REPO nu-book/zxing-cpp
Since the new repo inherits from the official repo, is this behavior officially permitted?

2022-01-26 09:07 UTC, joiskash commented on ports/zxing-cpp/portfile.cmake
> +    REPO nu-book/zxing-cpp
https://github.com/zxing/zxing#zxing-based-third-party-open-source-projects it is linked in the official report as a c++ port. And the both have Apache 2.0 licences.

2022-01-27 05:56 UTC, JackBoosY requested changes

2022-01-27 05:56 UTC, JackBoosY commented on ports/zxing-cpp/vcpkg.json
> -    "iconv": {
Delete features is a bad bahavor becuase it may breaks the users dependency.
Is the abi of this new repo compatible with the old repo? Why were these features removed?

2022-01-27 08:14 UTC, joiskash commented on ports/zxing-cpp/vcpkg.json
> -    "iconv": {
Great question. As per my understanding the abi of the new repo is not compatible with the old one. This is the main reason for updating this port. The old repo does not seem to have a simple api to read barcodes. In the new repo they have explained very clearly as to what the API is https://github.com/nu-book/zxing-cpp#to-read-barcodes . I also do not see any dependencies on opencv in the new repo. This is a breaking change.

2022-01-27 10:12 UTC, joiskash commented on ports/zxing-cpp/vcpkg.json
> -    "iconv": {
Ok should I call it nu-book-zxing-cpp? Also should I create a new PR?

2022-01-28 04:02 UTC, JackBoosY commented on ports/zxing-cpp/vcpkg.json
> -    "iconv": {
> Ok should I call it nu-book-zxing-cpp? Also should I create a new PR? Is there some naming convention for new ports?

Yes, please make changes in this PR, we can accept this name.

2022-01-28 09:02 UTC, joiskash commented on ports/zxing-cpp/vcpkg.json
> -    "iconv": {
I have made the changes as per your request

2022-01-28 13:32 UTC, cenit commented on versions/z-/zxing-cpp.json
> +    },
the above entry in the versions database should be purged?

2022-01-28 13:33 UTC, cenit commented on versions/z-/zxing-cpp.json
> +    },
@autoantwort do you have any idea why your bot didn't catch this error, an entry in the versions that is not matched anymore by any version in the PR (the edit was reverted and a new port was added, instead of an edit of this other one)?

2022-01-28 13:44 UTC, autoantwort commented on versions/z-/zxing-cpp.json
> +    },
Afaik the bot only checks if the new version is in the file and not the reverse. Maybe it should check if the current `git-tree` hash is the first in the file

2022-01-28 14:27 UTC, joiskash commented
Oops last commit is non-existent*  version.  Removed the entry from versions database as per @cenit feedback

2022-01-28 17:33 UTC, JackBoosY commented
Also, this port must have file conflicts with the old zxing-cpp, so please add the following content to _scripts/ci.baseline.txt_ after all test passed:
```
# Conflict with old zxing-cpp
nu-book-zxing-cpp:arm64-windows      = skip
nu-book-zxing-cpp:arm-uwp            = skip
nu-book-zxing-cpp:x64-linux          = skip
nu-book-zxing-cpp:x64-osx            = skip
nu-book-zxing-cpp:x64-uwp            = skip
nu-book-zxing-cpp:x64-windows        = skip
nu-book-zxing-cpp:x64-windows-static = skip
nu-book-zxing-cpp:x64-windows-static-md=skip
nu-book-zxing-cpp:x86-windows        = skip
```

2022-01-29 07:33 UTC, JackBoosY requested changes

2022-01-29 07:33 UTC, JackBoosY commented on ports/nu-book-zxing-cpp/vcpkg.json
> +  "name": "zxing-cpp",
```suggestion
  "name": "nu-book-zxing-cpp",
```

2022-02-02 17:34 UTC, joiskash commented
This is ready for review

2022-02-05 07:58 UTC, JackBoosY approved these changes

2022-02-07 07:14 UTC, JonLiu1993 approved these changes

2022-02-08 03:39 UTC, ras0219-msft requested changes
Thanks for the PR!

Since:
1. This conflicts with the existing `zxing-cpp` port
2. The existing port has no consumers
3. The existing port is abandoned with multiple inquiries on its GitHub with no response from someone with commit access
4. This new port seems to be well maintained and listed on the main `zxing` page

It makes sense to remove the abandoned `zxing-cpp` and instead build this library in CI and promote it for vcpkg users. I've pushed a commit to do that to https://github.com/ras0219-msft/vcpkg/tree/dev/roschuma/nu-book-zxing-cpp, so please run:
```
git pull https://github.com/ras0219-msft/vcpkg dev/roschuma/nu-book-zxing-cpp
```
and push the result to this PR.

We will also discuss this on Thursday PST to confirm that we want to remove the existing `zxing-cpp` port.

2022-02-10 19:13 UTC, ras0219-msft requested changes

2022-02-10 19:13 UTC, ras0219-msft commented on scripts/ci.baseline.txt
>  ocilib:arm-uwp=fail
```suggestion
ocilib:arm-uwp=fail
```
I can't push the change to your branch, so could you please apply this suggestion?

2022-02-11 04:31 UTC, ras0219-msft commented
We have made the decision that we should add this as a new port and remove the old port.

2022-02-11 08:25 UTC, JackBoosY commented
@ras0219-msft Should we rename this port to `zxing-cpp`?

2022-02-12 01:19 UTC, ras0219-msft commented
>@ras0219-msft Should we rename this port to zxing-cpp?

No, while this library does conflict with the original `zxing-cpp`, it makes no attempt to be a drop-in replacement. Therefore it is inappropriate to have the name `zxing-cpp` refer to this library.

>ENV{CL} "$ENV{CL} -wd4996" this did not seem to work. uwp build is failing due to error C4996

Let's mark this as unsupported on UWP for now. Unfortunately, we use MSBuild when targeting UWP which behaves very differently and would require patching to fix.

2022-02-14 02:34 UTC, JackBoosY requested changes

2022-02-14 02:34 UTC, JackBoosY commented on ports/nu-book-zxing-cpp/vcpkg.json
> +  "dependencies": [
```suggestion
  "supports": "!uwp",
  "dependencies": [
```

2022-02-14 08:13 UTC, JackBoosY approved these changes

2022-02-15 00:37 UTC, merged

2022-02-15 00:37 UTC, ras0219-msft commented
Thanks and sorry for the long journey here!

2022-02-15 02:36 UTC, joiskash commented
No problem. Im glad that my contribution got merged into main :)