[cppgraphqlgen] Update to v4.1.1 for latest release (plus v3.7.1 maintenance release)
microsoft/vcpkg pull request #22702
Opened 2022-01-22 18:28 UTC by wravery

**Describe the pull request**

- #### What does your PR fix?  
  Updates the latest version from v4.1.0 to v4.1.1. I also tested and added a v3.7.1 version, which is the latest in the v3.x maintenance branch for consumers who might be stuck on v3.6.0 due to the C++20 dependency in v4.x. It's not the default, but they can use a manifest to pin their version to v3.7.1 and pick up changes since v3.6.0.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All triplets are supported, but ci.baseline.txt still has an exception for x64-linux because the version of GCC is not new enough in the CI workflow.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes, for v3.7.1 and then v4.1.1, so v4.1.1 is the latest.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-01-24 08:02 UTC, JackBoosY requested changes

2022-01-24 08:02 UTC, JackBoosY commented on versions/c-/cppgraphqlgen.json
> +    },
```suggestion
```
Please remove this line, this commit will not merged into master, so the users can't use this commit id to pull the related changes.

2022-01-24 08:10 UTC, JonLiu1993 requested changes

2022-01-24 08:10 UTC, JonLiu1993 commented on versions/c-/cppgraphqlgen.json
> +    },
```suggestion
```

2022-01-24 08:10 UTC, JonLiu1993 commented on versions/c-/cppgraphqlgen.json
> +    },
@wravery ,Thanks for your pr ,the git tree that is not pushed to the master cannot pull the corresponding commit

2022-01-24 16:10 UTC, wravery commented on versions/c-/cppgraphqlgen.json
> +    },
Ah, OK. Sounds like I can't really add the maintenance release version then, at least not without creating a separate port like `cppgraphqlgen3`.

2022-01-25 05:58 UTC, JackBoosY approved these changes

2022-01-25 07:55 UTC, JonLiu1993 approved these changes

2022-01-26 05:24 UTC, merged

2022-01-26 05:24 UTC, ras0219-msft commented
Thanks for the update!