[poppler] Major update
microsoft/vcpkg pull request #22720
Opened 2022-01-23 18:18 UTC by dg0yt

- #### What does your PR fix?  
  Updates poppler to 22.01.0.
  Revises dependencies and feature interface.
  - The Cairo backend can be requested via a feature now. (Used to be hard dependency on osx.)
  - Unstable API/ABI headers (used by packages like GDAL) can be requested via a feature now.
  - The default font configuration backend follows upstream. Windows defaults to win32 instead of fontconfig.
  - gperf is no longer used. (There are ready-to-use files. We can avoid patching and cross platform issues.)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, yes (arm64-windows no longer blocked by gperf) 
  Build tested on Ubuntu 18.04.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR.

Todo:
 - [ ] Fix exported pkgconfig files (static dependencies)
 - [ ] Export unofficial cmake target configuration (to be used with gdal, #22583, CC @m-kuhn)
       (Needs fix to fontconfig wrapper, WIP in #22258)

2022-01-24 08:25 UTC, dg0yt commented
UWP:
~~~
5>D:\buildtrees\poppler\src\er-22.01.0-24b8c57e16.clean\goo\gfile.cc(363,21): error C3861: 'CreateFileA': identifier not found [D:\buildtrees\poppler\x64-uwp-dbg\poppler.vcxproj]
5>D:\buildtrees\poppler\src\er-22.01.0-24b8c57e16.clean\goo\gfile.cc(370,21): error C3861: 'CreateFileW': identifier not found [D:\buildtrees\poppler\x64-uwp-dbg\poppler.vcxproj]
~~~
=> unsupported

2022-01-31 09:15 UTC, dg0yt commented
This version of poppler is currently not usable with gdal. gdal uses the poppler C++ API, and poppler uses C++ 17 in the API (`std::optional`).
The C++17 requirement in poppler came app. three months ago. The newer version include security updates, so I wouldn't really want to go back. Not sure if this can be resolved in another way.

2022-01-31 10:12 UTC, m-kuhn commented
Is there a ticket about this open on gdal side?

2022-02-10 06:15 UTC, LilyWangLL approved these changes

2022-02-10 08:41 UTC, JackBoosY requested changes

2022-02-10 08:41 UTC, JackBoosY commented on ports/poppler/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/unofficial-poppler-config.cmake" "${CURRENT_PACKAGES_DIR}/share/unofficial-poppler/unofficial-poppler-config.cmake" @ONLY)
Since it's part of generating the cmake config file, can you move it into the patch?

2022-02-10 09:01 UTC, dg0yt commented on ports/poppler/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/unofficial-poppler-config.cmake" "${CURRENT_PACKAGES_DIR}/share/unofficial-poppler/unofficial-poppler-config.cmake" @ONLY)
I don't want to put it in the patch. It is easier to maintain separately.

2022-02-11 04:47 UTC, dg0yt commented
I update license field for gdal and unofficial namespace for poppler exports. No other changes planned.

2022-02-11 09:45 UTC, JackBoosY requested changes

2022-02-11 09:45 UTC, JackBoosY commented on ports/gdal/vcpkg.json
> +  "license": null,
```suggestion
  "license": "MIT",
```
`MIT style`: https://gdal.org/license.html.

2022-02-11 10:26 UTC, dg0yt commented on ports/gdal/vcpkg.json
> +  "license": null,
Do read that file: "In general" MIT but ... there is more, in
https://raw.githubusercontent.com/OSGeo/gdal/master/LICENSE.TXT
This is also the file which we install for `copyright`.
That's why I explicitly chose `null` which is for [other licenses for which one should "just read the copyright file" (e.g., Qt)](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#license).
In particular in the light of Poppler: gdal[poppler] results in GPL-2.0-only.

2022-02-14 02:28 UTC, JackBoosY approved these changes

2022-02-14 09:13 UTC, LilyWangLL commented
@dg0yt `poppler[fontconfig]:x64-windows` build failed with the following error:
```
H:\Lily\22720\vcpkg\buildtrees\poppler\src\er-22.02.0-e605c044ce.clean\poppler\GlobalParams.cc(751): error C3861: 'strndup': identifier not found
H:\Lily\22720\vcpkg\buildtrees\poppler\src\er-22.02.0-e605c044ce.clean\poppler\GlobalParams.cc(719): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
```

2022-02-14 12:11 UTC, dg0yt commented
Okay, poppler[fontconfig] is now unsupported on windows (except mingw).

2022-02-15 02:54 UTC, LilyWangLL requested changes

2022-02-15 02:54 UTC, LilyWangLL commented on ports/poppler/vcpkg.json
> +      "supports": "!windows, mingw",
Could you use `|` instead of `,`?

2022-02-15 05:01 UTC, dg0yt commented on ports/poppler/vcpkg.json
> +      "supports": "!windows, mingw",
I could, but why?

2022-02-15 06:30 UTC, JackBoosY commented on ports/poppler/vcpkg.json
> +      "supports": "!windows, mingw",
Using "&" and "|" is more logical than using "," and can express the meaning of expressions more intuitively.

2022-02-15 06:36 UTC, dg0yt commented on ports/poppler/vcpkg.json
> +      "supports": "!windows, mingw",
This entirely subjective, opinion. AFAIU the `,` exists to express top-level alternatives.

If you want opinion: 
- It is more comfortable to read with `,`
- The expression syntax should have used C/C++/preprocessor/shell syntax (`&&`, `||`).
  (In contrast, `|` is popular for shell pipes.)

@strega-nil-ms You added the `,`. What now?

2022-02-15 08:00 UTC, JackBoosY commented on ports/poppler/vcpkg.json
> +      "supports": "!windows, mingw",
This modification is acceptable because we added "," as a supported expression symbol.
This is just my personal suggestion.

2022-02-16 18:01 UTC, dg0yt commented
AFAICS the author gave all required response.

2022-02-17 18:12 UTC, ras0219-msft approved these changes

2022-02-17 18:25 UTC, dg0yt commented on ports/poppler/export-unofficial-poppler.patch
> ++set_target_properties(poppler PROPERTIES EXPORT_NAME poppler-private)
The name "poppler" is fine when used inside the Poppler project. However, upstream is really putting much emphasis on that this shall not be used by other projects and that such usage is entirely unsupported. However, some projects need it (e.g. GDAL). I want to carry upstreams point of view. Even more in the light of tools like `vcpkg?  blindly reporting all targets as if they were public API.

I also want to add proper CMake config export upstream, and I expect better acceptance for this name.

2022-02-17 18:29 UTC, dg0yt commented on ports/poppler/portfile.cmake
> +        "-DCMAKE_PROJECT_INCLUDE=${CMAKE_CURRENT_LIST_DIR}/cmake-project-include.cmake"
I used this also in the GDAL cmake packaging attempt. It helps to avoid fragile patches. 
(Until some package comes with its own hacks (as seen yesterday with the opencv android zlib hack: clearing input variables, overwriting standard lib suffixes).

2022-02-18 01:03 UTC, merged