[flann] Change from find_package(hdf5) to find_dependency(HDF5)
microsoft/vcpkg pull request #22731
Opened 2022-01-24 03:30 UTC by longhuan2018

fix #22153

2022-01-24 03:31 UTC, BillyONeal approved these changes

2022-01-24 04:24 UTC, JackBoosY commented
Will rerun test after x64-windows finished.
Also please report this to the upstream.

Thanks.

2022-01-24 05:38 UTC, dg0yt requested changes
Please either remove the non-standard `CMAKE_DEBUG_POSTFIX`, or move it to `OPTIONS_DEBUG`.

And check if other build warnings that can be resolved.

2022-01-24 05:38 UTC, dg0yt commented on ports/flann/portfile.cmake
> +endif()
Please use a non-conditional patch. Either configure the wrapper, or inspect the required libraries.

2022-01-24 07:23 UTC, JackBoosY commented on ports/flann/portfile.cmake
> +endif()
Yes, it may affect other patches.

2022-01-25 06:26 UTC, JackBoosY approved these changes

2022-01-26 23:27 UTC, merged

2022-01-26 23:27 UTC, BillyONeal commented
Thanks <3