[Qt6] update to 6.2.3
microsoft/vcpkg pull request #22846
Opened 2022-01-28 19:58 UTC by Neumann-A

CI test run more changes incoming

2022-01-28 21:05 UTC, abique commented
Hi @Neumann-A 
Do you think you could add a feature to turn on `-optimize-size`?
It is documented here: https://github.com/qt/qtbase/blob/dev/config_help.txt#L67
I've tried adding it via the triplet: `VCPKG_CXX_FLAGS="-Os"` but Qt did not picked it up, and did build with `-O3`.
Thanks!

2022-01-28 21:15 UTC, Neumann-A commented
> Do you think you could add a feature to turn on -optimize-size?

no the toolchain should control that. If you find the line in qt which messes up the flags you are free to tell me and I patch it out. 
Otherwise if you correctly set `VCPKG_CXX_FLAGS` you also needed to set `VCPKG_C_FLAGS`. If you did not do that there is something wrong with your setting.

2022-01-28 21:37 UTC, Neumann-A commented
@autoantwort @strega-nil: There needs to be some automatic way to update the license stuff ..... i am not going to add those for qt manually considering the amount of license files and ports.

2022-01-29 14:58 UTC, autoantwort commented
> @autoantwort @strega-nil: There needs to be some automatic way to update the license stuff ..... i am not going to add those for qt manually considering the amount of license files and ports.

Is the license for all qt ports the same? If you know the license I can add it (Conan uses `LGPL-3.0`).

2022-01-29 19:20 UTC, Neumann-A commented
> Is the license for all qt ports the same? If you know the license I can add it (Conan uses LGPL-3.0).

According to the licenses in the sources it has a complicated `OR` licenscape and it is not all the same for all ports.

2022-02-01 05:19 UTC, ras0219-msft commented
Sorry for the spam from actions -- the license clause is only a warning and the action will still approve without addressing it. We should definitely put the output into a details when modifying many ports at once.

2022-02-03 19:29 UTC, strega-nil-ms commented
@Neumann-A I think the correct thing here is to put `"null"` as a license, since the licensing story is complex enough that we shouldn't make it simple.

I'll update the tool in the vcpkg repo with the tool that has that ability today.

2022-02-04 00:52 UTC, strega-nil-ms requested changes
Minor changes requested, then I'm happy to merge :)

2022-02-04 00:52 UTC, strega-nil-ms commented on ports/qt/vcpkg.json
> +  "version-semver": "6.2.3",
Can you please change all of these `version-semver`'s to `version`'s?

2022-02-04 00:52 UTC, strega-nil-ms commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    if(NOT ${PORT} MATCHES "qtbase")
```suggestion
    if(NOT PORT MATCHES "^qtbase")
```

2022-02-04 00:52 UTC, strega-nil-ms commented on ports/qtbase/cmake/qt_install_submodule.cmake
>      endif()
This also needs to be swapped:

```suggestion
    set(ninja_option "")
    if(_qarg_DISABLE_NINJA)
        set(ninja_option WINDOWS_USE_MSBUILD)
    endif()
```

2022-02-04 00:52 UTC, strega-nil-ms commented on ports/qtbase/portfile.cmake
> +    elseif(_input MATCHES "(sql-sqlite)") # Not yet used be the cmake build
```suggestion
    elseif(_input MATCHES "(sql-sqlite)") # Not yet used by the cmake build
```

2022-02-04 00:52 UTC, strega-nil-ms commented on ports/qtbase/portfile.cmake
> +    list(APPEND FEATURE_OPTIONS -DQT_NAMESPACE:STRING=${VCPKG_QT_NAMESPACE})
```suggestion
    list(APPEND FEATURE_OPTIONS "-DQT_NAMESPACE:STRING=${VCPKG_QT_NAMESPACE}")
```

2022-02-04 21:38 UTC, Neumann-A commented on ports/qt/vcpkg.json
> +  "version-semver": "6.2.3",
next update. I currently don't want to rerun the update script again locally which performs the change. (since this requires a removal of qtbase)

2022-02-04 21:39 UTC, Neumann-A commented on ports/qtbase/cmake/qt_install_submodule.cmake
>          ${NINJA_OPTION}
```suggestion
        ${ninja_option}
```

2022-02-04 23:31 UTC, strega-nil-ms commented
Merge once green!

2022-02-06 02:46 UTC, JackBoosY commented
Can you please use `vcpkg-cmake` in qtbase?

2022-02-06 06:14 UTC, Neumann-A commented
> Can you please use `vcpkg-cmake` in qtbase?

It is already used? (Otherwise i would get an error) vcpkg-cmake-config isn't used yet -> next update

2022-02-07 13:57 UTC, abique commented
> > Do you think you could add a feature to turn on -optimize-size?
> 
> no the toolchain should control that. If you find the line in qt which messes up the flags you are free to tell me and I patch it out. Otherwise if you correctly set `VCPKG_CXX_FLAGS` you also needed to set `VCPKG_C_FLAGS`. If you did not do that there is something wrong with your setting.

Hi @Neumann-A,

We can try to pass: `-DQT_USE_DEFAULT_CMAKE_OPTIMIZATION_FLAGS=ON`.

See:

https://github.com/qt/qtbase/blob/6.2.3/cmake/QtFlagHandlingHelpers.cmake#L674
https://github.com/qt/qtbase/blob/6.2.3/cmake/QtFlagHandlingHelpers.cmake#L856

Regards,
Alexandre

2022-02-07 23:00 UTC, Neumann-A commented
So I updated the following:
- added `-DQT_USE_DEFAULT_CMAKE_OPTIMIZATION_FLAGS=ON.`
- switched to vcpkg-cmake-config
- fixed an issues with prl files (used by vcpkg-qmake not yet tested in CI)
- added some x related FEATURES_ to fix the regression in the cmake update PR. Also fixed a missing dependency
- moved all hashes to port_details so everything is again in one location. (Needed for future LTS version feature to simply replace the file with the hashes) 
- GH actions still complains for some reason.

2022-02-08 12:14 UTC, Neumann-A commented
so all MAYBE_UNUSED_WARNINGS should be silenced now.

2022-02-09 02:25 UTC, JackBoosY requested changes

2022-02-09 02:25 UTC, JackBoosY commented on ports/qtbase/vcpkg.json
> +  "license": null,
Should be `LGPL`? See https://www.qt.io/licensing/open-source-lgpl-obligations

2022-02-09 05:48 UTC, Neumann-A commented on ports/qtbase/vcpkg.json
> +  "license": null,
I wasnt th one adding the license here

2022-02-10 02:51 UTC, JackBoosY approved these changes
LGTM.

2022-02-16 04:24 UTC, BillyONeal commented
@strega-nil-ms is still marked as "requested changes" but she has a more recent comment than that "merge once green" so I'm assuming she's OK with it.

2022-02-16 04:24 UTC, merged

2022-02-16 04:24 UTC, BillyONeal commented
Thanks for the update!