[jasper]: Move opengl & freeglut dependencies under default-features in order to enable flexibility to not require any of those when importing jasper package (via default-features=false).
microsoft/vcpkg pull request #22895
Opened 2022-02-02 08:18 UTC by sylvain-prevost

**Describe the pull request**
[jasper]: Move opengl & freeglut dependencies under default-features in order to enable flexibility to not require any of those when importing jasper package (via default-features=false).

- #### What does your PR fix?  
  Fixes # Allow developer to not require opengl and/or freeglut package in order to be able to import jasper package. Hopefully this should be fully backward compatible and transparent to current users. Useful for developers that cross-compile on systems that do not have opengl.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
(https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Unchanged from previous port. Not sure about expected syntax below.
  <linux, windows, uwp>, <Yes>
  <osx>, <No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Careful review is advisable since it is my 1st PR (ever).

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**
I believe it is complete as is, but really not certain about CI requirements.

2022-02-02 09:33 UTC, sylvain-prevost commented
Some invalid commit noise re: [x264] cause I improperly reused this branch for a different PR :( 
Reverted undue [x264] related commits.

2022-02-04 03:08 UTC, BillyONeal requested changes

2022-02-04 03:08 UTC, BillyONeal commented on ports/jasper/vcpkg.json
> +    "freeglut": {
I think you forgot to hook up this feature in `portfile.cmake`.

2022-02-04 17:49 UTC, strega-nil-ms requested changes

2022-02-04 17:49 UTC, strega-nil-ms commented on ports/jasper/vcpkg.json
> +  }
This is inaccurate; `opengl` and `freeglut` should be the same feature:

```suggestion
  "default-features": [
    "opengl"
  ],
  "features": {
    "opengl": {
      "description": "Enable the use of the OpenGL/GLUT Library",
      "dependencies": [
        {
          "name": "freeglut",
          "platform": "osx"
        },
        "opengl"
      ]
    }
  }
```

2022-02-08 09:49 UTC, LilyWangLL approved these changes

2022-02-08 18:40 UTC, ras0219-msft commented on ports/jasper/vcpkg.json
> +        "freeglut",
This appears to drop the condition `"!osx"` -- was that intended?

2022-02-08 20:00 UTC, sylvain-prevost commented on ports/jasper/vcpkg.json
> +        "freeglut",
@ras0219-msft,
Yes - it was. 

Review of the freeglut port seemed to indicate that it is compatible with osx since there is no platform constraint in the freeglut vcpkg.json + portfile contains a macOS specific patch + the CI did not complain. 

I do not have a MAC so I have NOT verified functionality. If you have doubdt, I can revert back.. although more-appropriate place would be in the freeglut itself (IMO).

2022-02-09 02:44 UTC, LilyWangLL requested changes

2022-02-09 02:44 UTC, LilyWangLL commented on ports/jasper/vcpkg.json
> +        "freeglut",
`freeglut` and `jasper[opengl]` can install succeed on MACOS.
```
Installing package jasper[core,opengl]:x64-osx...
Elapsed time for package jasper:x64-osx: 6.484 s
```

2022-02-09 02:44 UTC, LilyWangLL commented on ports/jasper/vcpkg.json
> +        "freeglut",
`freeglut` and `jasper[opengl]` can install succeed on MACOS.
```
Installing package jasper[core,opengl]:x64-osx...
Elapsed time for package jasper:x64-osx: 6.484 s
```

2022-02-09 05:32 UTC, merged

2022-02-09 05:32 UTC, ras0219-msft commented
Ok, this LGTM then. Thanks!