Added libe57format port
microsoft/vcpkg pull request #22909
Opened 2022-02-03 09:32 UTC by joseangelmt

**Describe the pull request**

A library to provide read & write support for the E57 file format.

- #### What does your PR fix?  
  Adds a new port ([libe57format](https://github.com/asmaloney/libE57Format))

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
 Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-02-03 09:43 UTC, mathisloge commented on ports/libe57format/portfile.cmake
> +vcpkg_configure_cmake(
`vcpkg_configure_cmake` is deprecated, see https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md 

You should use `vcpkg_cmake_configure` and add 
```cmake
{
      "name": "vcpkg-cmake",
      "host": true
    }
``` to the dependencies.

2022-02-03 09:44 UTC, mathisloge commented on ports/libe57format/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH "lib/cmake/E57Format")
same as above, but use `vcpkg_cmake_config_fixup`

and add 
```json
{
      "name": "vcpkg-cmake-config",
      "host": true
    },
``` 
to the dependencies

2022-02-03 09:45 UTC, mathisloge requested changes
see https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md and https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md for deprecation notice

2022-02-03 10:47 UTC, joseangelmt commented on ports/libe57format/portfile.cmake
> +vcpkg_configure_cmake(
Thank you Mathis,

I already changed both: vcpkg_configure_cmake and cpkg_fixup_cmake_targets.
What confused me was the [Packaging Github Repos Example: libogg](https://vcpkg.io/en/docs/examples/packaging-github-repos.html) documentation.

2022-02-04 03:03 UTC, BillyONeal approved these changes

2022-02-04 09:17 UTC, merged

2022-02-04 09:17 UTC, BillyONeal commented
Thanks for the new port!