[vcpkg.targets] Fix _ZVcpkgInstalledDir in manifest mode
microsoft/vcpkg pull request #23023
Opened 2022-02-10 01:20 UTC by PhoebeHui

The $(VcpkgTriplet) in path duplicated when enable manifest in msbuild project, which cause the installed files can't be found when using these files.

```
 
  <Choose>
    <When Condition="'$(VcpkgEnableManifest)' == 'true'">
      <PropertyGroup>
        <_ZVcpkgInstalledDir Condition="'$(_ZVcpkgInstalledDir)' == ''">$(_ZVcpkgManifestRoot)vcpkg_installed\$(VcpkgTriplet)\</_ZVcpkgInstalledDir>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <_ZVcpkgInstalledDir Condition="'$(_ZVcpkgInstalledDir)' == ''">$(_ZVcpkgRoot)installed\</_ZVcpkgInstalledDir>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <PropertyGroup>
    <_ZVcpkgCurrentInstalledDir>$(_ZVcpkgInstalledDir)$(VcpkgTriplet)\</_ZVcpkgCurrentInstalledDir>
...
 </PropertyGroup>
```

2022-02-10 02:29 UTC, autoantwort commented
This will break multitriplet solutions again

2022-02-10 02:57 UTC, JackBoosY commented
> This will break multitriplet solutions again

One solution uses the same manifest file and vcpkg configuration.
@BillyONeal right?

2022-02-10 03:10 UTC, autoantwort commented
> One solution uses the same manifest file and vcpkg configuration. 

Yes (You also can use separate manifest files for each project). But within one solution you can use multiple triplets with one manifest file.

2022-02-10 03:19 UTC, BillyONeal requested changes
> One solution uses the same manifest file and vcpkg configuration. @BillyONeal right?

Typically, yes. The location for the installed directory is to be chosen relative to the location of `vcpkg.json` though, so that if multiple are used that works.

The things that are important here are:

1. Different `vcpkg.json`s need to be able build their own bits without trying to stomp on the same "installed" tree. (This means it needs to be chosen relative to `vcpkg.json`)
2. Changing "configuration" in Visual Studio needs to not delete / invalidate everything for other configurations. (This means generally that the resulting path must contain the triplet)

I think the previous behavior may be intentional through in support of making different "configuration"s separate, because the "host" triplet is also going to want a place to put its bits. That is, I think the status quo is:

* `(where vcpkg.json is)/vcpkg_installed/target_triplet1/target_triplet1`
* `(where vcpkg.json is)/vcpkg_installed/target_triplet1/host_triplet`
* * `(where vcpkg.json is)/vcpkg_installed/target_triplet2/target_triplet2`
* `(where vcpkg.json is)/vcpkg_installed/target_triplet2/host_triplet`

while this will make:

* `(where vcpkg.json is)/vcpkg_installed/target_triplet1`
* `(where vcpkg.json is)/vcpkg_installed/target_triplet2`
* `(where vcpkg.json is)/vcpkg_installed/host_triplet`

which means different changing "configuration" and thus "target_triplet" is likely to invalidate work and thus need race protection for the "host_triplet" directory.

2022-02-10 06:34 UTC, PhoebeHui commented
@BillyONeal, thanks for confirming this issue, the previous behavior does make sense for supporting the different configuration.

I noticed the intelliSense has false error, it tells the file not found, however the file exist and it builds fine, this issue could be resolved by reopen the solution. I tried this with VS2017 and VS2019, they have same behavior.

![image](https://user-images.githubusercontent.com/20694052/153350191-f5f2e37e-7a7a-45b3-9812-70b20ebcd55a.png)

2022-02-11 22:24 UTC, BillyONeal commented
Given discussion that happened in email and my response above, it appears the code in `master` is correct, so I'm closing this. Thanks for your contribution Phoebe :)

2022-02-11 22:24 UTC, closed without merging