[mapnik] test static build
microsoft/vcpkg pull request #23060
Opened 2022-02-11 22:35 UTC by mathisloge

**Describe the pull request**

- #### What does your PR fix?  
enables mapnik static linkage.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
hopefully all except supported

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
I am still working on this PR

2022-02-14 07:03 UTC, LilyWangLL requested changes

2022-02-14 07:03 UTC, LilyWangLL commented on ports/mapnik/portfile.cmake
> +    REPO mathisloge/mapnik
Why change to a unofficial github url?

2022-02-14 07:07 UTC, mathisloge commented on ports/mapnik/portfile.cmake
> +    REPO mathisloge/mapnik
I'm currently testing static linkage. The static build is in a PR for upstream.

This PR is a draft as long as the upstream PR is not merged. I'll then change back to the official repo

2022-05-06 08:23 UTC, LilyWangLL commented
Ping @mathisloge for response. Does the upstream PR has new updates?

2022-05-06 08:30 UTC, mathisloge commented
@LilyWangLL i will update the PR if I have resolved all bugs at upstream.

2022-06-15 06:35 UTC, LilyWangLL commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2022-06-15 06:35 UTC, closed without merging