[fribidi] Fix cross-compilation in meson. Re-enable arm64-windows.
microsoft/vcpkg pull request #23063
Opened 2022-02-12 00:58 UTC by ras0219-msft

The buildsystem revert back to autoconf in https://github.com/microsoft/vcpkg/pull/21948 did not actually fix cross-compilation; rather it just allowed the build to stumble forward hoping that the cross-built executables would run.

This PR actually fixes cross-compilation by adding a proper host dependency and reusing the tables generated from that host build.

This PR is specifically in pursuit of reenabling ffmpeg:arm64-windows.

2022-02-12 07:25 UTC, Osyotr commented on ports/fribidi/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/include/fribidi
Shouldn't this be quoted? Same below

2022-02-14 06:55 UTC, LilyWangLL requested changes

2022-02-14 06:55 UTC, LilyWangLL commented on ports/fribidi/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/include/fribidi
```suggestion
        DESTINATION "${CURRENT_PACKAGES_DIR}/include/fribidi"

```

2022-02-14 06:55 UTC, LilyWangLL commented on ports/fribidi/portfile.cmake
> +        COPY ${CURRENT_PACKAGES_DIR}/include/fribidi/fribidi-unicode-version.h
```suggestion
        COPY "${CURRENT_PACKAGES_DIR}/include/fribidi/fribidi-unicode-version.h"

```

2022-02-14 06:55 UTC, LilyWangLL commented on ports/fribidi/portfile.cmake
> +        DESTINATION ${CURRENT_PACKAGES_DIR}/share/fribidi/gen.tab
```suggestion
        DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}/gen.tab"

```

2022-02-14 06:55 UTC, LilyWangLL commented on ports/fribidi/portfile.cmake
> +    set(gen_tab "${CURRENT_HOST_INSTALLED_DIR}/share/fribidi/gen.tab")
```suggestion
    set(gen_tab "${CURRENT_HOST_INSTALLED_DIR}/share/${PORT}/gen.tab")

```

2022-02-16 05:58 UTC, LilyWangLL approved these changes

2022-02-16 21:04 UTC, merged