[vcpkg-get-python-packages] add helper to manage python and pip
microsoft/vcpkg pull request #23089
Opened 2022-02-14 15:00 UTC by Neumann-A

ports which could use this:
- duktape
- mesa (changed to use it)
- opencv2 / opencv3 / opencv4
- qtinterfaceframework
- qtwebengine (in 6.3)
- tensorflow (?)

2022-02-15 02:21 UTC, Hoikas commented
This looks way too complicated to me. There is a lot of code for determining the paths of pip executables that could be simplified by simply calling `<path_to_python> -m pip [pip arguments here]`. If you need to install pip itself, use `<path_to_python> -m ensurepip`.

2022-02-15 07:57 UTC, JackBoosY commented
I think we can accept this. Needs more review.

2022-02-15 07:58 UTC, JackBoosY requested changes

2022-02-15 07:58 UTC, JackBoosY commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +                execute_process(COMMAND "${arg_PYTHON_EXECUTABLE}" "${PYFILE_PATH}/get-pip.py" ${PYTHON_OPTION})
`vcpkg_execute_required_process`?

2022-02-15 08:02 UTC, Neumann-A commented
@Hoikas The script is directly out of the mesa portfile which adapted it out of the duktape/opencv ports. If you think this is too complicated provide a working example for mesa. Be aware that `vcpkg_find_acquire_program(PYTHON3)` only downloads and extracts python and does no setup it at all.

2022-02-16 10:32 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +function(x_vcpkg_get_python_packages PYTHON_DIR )
should this be prefixed with `x_` if it is a script from a port?

2022-02-16 21:26 UTC, vicroms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +function(x_vcpkg_get_python_packages PYTHON_DIR )
Since ports can be versioned, I don't think that the experimental prefix is necessary. 
@strega-nil has been driving the scripts-to-ports conversion so I'd like to hear her thougts?

2022-02-16 21:27 UTC, vicroms approved these changes

2022-02-16 21:41 UTC, ras0219-msft commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +if(Z_VCPKG_GET_PYTHON_PACKAGES_GUARD)
https://cmake.org/cmake/help/latest/command/include_guard.html#command:include_guard
?

2022-02-16 21:51 UTC, ras0219-msft reviewed
I'm going to take a look at `virtualenv` and post back

2022-02-16 21:51 UTC, ras0219-msft commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +                    HEAD_REF master
This shouldn't have a HEAD_REF because this is a nested tool; using the head version of some package shouldn't also imply head of pip

2022-02-16 21:51 UTC, ras0219-msft commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +        set(PYTHON_OPTION "--user")
> --user  Install to the Python user install directory for your platform. 
        Typically ~/.local/, or %APPDATA%\Python on Windows. 
        (See the Python documentation for site.USER_BASE for full details.)
        
This still modifies the user's system. I think we should be using a virtual environment instead.

2022-02-16 21:51 UTC, ras0219-msft commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +    if("${arg_PYTHON_DIR}" MATCHES "${DOWNLOADS}") # inside vcpkg
I think by using `virtualenv` https://packaging.python.org/en/latest/tutorials/installing-packages/#id16 we can have the exact same process on all platforms and avoid system modification.

2022-02-16 21:58 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +        set(PYTHON_OPTION "--user")
This script is not installing anything if python3 outside of vcpkg is used. 
venv could only help installing packages if python3 outside of vcpkg is used. So we wouldn't throw an error.

2022-02-16 21:59 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +                    HEAD_REF master
```suggestion
```

2022-02-16 21:59 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +            endif()
Here venv could be used to avoid the error and install python packages for vcpkg.

2022-02-16 22:03 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +if(Z_VCPKG_GET_PYTHON_PACKAGES_GUARD)
that is a question for @strega-nil. I think I suggested the same in one of the script audit PRs. 
Due to that I just copied the guard from the other scripts.

2022-02-16 22:24 UTC, ras0219-msft commented
Ok, on my linux container I get:
```
$ pip
bash: pip: command not found
$ python -m pip
/usr/bin/python3: No module named pip
$ python -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR
$ python -m venv venv-test
```
Then,
```
$ export VIRTUAL_ENV="$(pwd)/venv-test"
$ export PATH="$VIRTUAL_ENV/bin:$PATH"
$ unset PYTHONHOME
$ pip --isolated -v list
Package       Version Location                                                Installer
------------- ------- ------------------------------------------------------- ---------
pip           20.0.2  /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip      
pkg-resources 0.0.0   /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip      
setuptools    44.0.0  /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip
$ pip --isolated -v install mako
// a bunch of output because verbose mode
$ pip --isolated -v list
Package       Version Location                                                Installer
------------- ------- ------------------------------------------------------- ---------
Mako          1.1.6   /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip      
MarkupSafe    2.0.1   /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip      
pip           20.0.2  /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip      
pkg-resources 0.0.0   /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip      
setuptools    44.0.0  /workspaces/vcpkg/venv-test/lib/python3.8/site-packages pip
```

This looks like it can at least isolate the packages. To get even more reproducible results, it looks like we can use `pipenv` to get hashes:
```
$ cat requirements.txt
Mako==1.1.6
MarkupSafe==2.0.1
$ pipenv lock
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
// some messages
$ ls Pip*
Pipfile  Pipfile.lock
```

I'm not sure that `pipenv` is worth the extra hassle though.

2022-02-16 22:37 UTC, Neumann-A commented
Lets just do your iterative improvement strategy:
1) **first get the function definition into a script-port (this PR)**
2) adjust all ports which could use the function to use the script port
3) make improvements to the script port

since 1) is this PR lets focus on porting it to a script-port instead of changing functionality. 

The main reason I made this PR was that I needed the same code as mesa in qtwebengine to get python packages.

2022-02-17 07:30 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +function(x_vcpkg_get_python_packages PYTHON_DIR )
So I'll be waiting for a reply before applying further CR changes

2022-02-17 19:02 UTC, vicroms commented
Closed and re-opened to trigger CLA check again

2022-02-17 20:16 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +if(Z_VCPKG_GET_PYTHON_PACKAGES_GUARD)
I believe I didn't use that because of misguided understandings of our minimum CMake requirements; you can use `include_guard`.

2022-02-17 20:17 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +function(x_vcpkg_get_python_packages PYTHON_DIR )
I'd prefer the experimental prefix personally, but I leave that up to you

2022-02-17 20:27 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +function(x_vcpkg_get_python_packages PYTHON_DIR )
since `x_` was my first gut feeling I will leave it that way. Maybe someone wants to change the function signature or drastically change of it works in the future (pointing at the other discussions about venv and stuff).

2022-03-03 09:45 UTC, JackBoosY commented
Ping @ras0219-msft @vicroms for review this PR again.

2022-03-15 23:39 UTC, strega-nil-ms requested changes
This is what I see on a cursory glance

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/x_vcpkg_get_python_packages.cmake" "${CURRENT_PACKAGES_DIR}/share/${PORT}/x_vcpkg_get_python_packages.cmake" @ONLY)
Why is this a `configure_file`?

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +function(x_vcpkg_get_python_packages PYTHON_DIR )
```suggestion
function(x_vcpkg_get_python_packages python_dir)
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +    cmake_parse_arguments(PARSE_ARGV 0 arg "" "PYTHON_EXECUTABLE" "PACKAGES")
```suggestion
    cmake_parse_arguments(PARSE_ARGV 1 arg "" "PYTHON_EXECUTABLE" "PACKAGES")
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +    endif()
This should be `PYTHON_DIR` (not `arg_PYTHON_DIR`), but also it's always passed so this should be removed.

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +    endif()
```suggestion
    endif()
    if(DEFINED arg_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} was passed extra arguments: ${arg_UNPARSED_ARGUMENTS}")
    endif()
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +    if(NOT arg_PACKAGES)
```suggestion
    if(NOT DEFINED arg_PACKAGES)
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +    if(NOT arg_PYTHON_EXECUTABLE)
```suggestion
    if(NOT DEFINED arg_PYTHON_EXECUTABLE)
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} requires parameter PYTHON_EXECUTABLE!")
```suggestion
        message(FATAL_ERROR "PYTHON_EXECUTABLE must be specified.")
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} requires parameter PACKAGES!")
```suggestion
        message(FATAL_ERROR "PACKAGES must be specified.")
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +        set(PYTHON_OPTION "--user")
also, this should be:
```suggestion
        vcpkg_list(SET python_user_param "--user")
```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +endfunction()
```suggestion
endfunction()

```

2022-03-15 23:39 UTC, strega-nil-ms commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +        foreach(_package IN LISTS arg_PACKAGES)
```suggestion
        foreach(package IN LISTS arg_PACKAGES)
```

2022-03-16 12:20 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/x_vcpkg_get_python_packages.cmake" "${CURRENT_PACKAGES_DIR}/share/${PORT}/x_vcpkg_get_python_packages.cmake" @ONLY)
copy pasta

2022-03-16 12:21 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +            vcpkg_execute_in_download_mode(COMMAND ${arg_PYTHON_EXECUTABLE} -c "import ${_package}" RESULT_VARIABLE HAS_ERROR)
```suggestion
            vcpkg_execute_in_download_mode(COMMAND ${arg_PYTHON_EXECUTABLE} -c "import ${package}" RESULT_VARIABLE HAS_ERROR)

```

2022-03-16 12:21 UTC, Neumann-A commented on ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
> +                message(FATAL_ERROR "Python package '${_package}' needs to be installed for port '${PORT}'.\nComplete list of required python packages: ${arg_PACKAGES}")
```suggestion
                message(FATAL_ERROR "Python package '${package}' needs to be installed for port '${PORT}'.\nComplete list of required python packages: ${arg_PACKAGES}")

```

2022-03-23 22:32 UTC, strega-nil-ms commented
Can we do this instead?

```patch
From 7c3f98be33bf07770636a93bf98ea479975c33a7 Mon Sep 17 00:00:00 2001
From: nicole mazzuca <mazzucan@outlook.com>
Date: Wed, 23 Mar 2022 15:31:26 -0700
Subject: [PATCH] actually install stuff locally

This installs pip packages per-port
---
 ports/mesa/portfile.cmake                     | 12 ++--
 .../x_vcpkg_get_python_packages.cmake         | 61 ++++++-------------
 2 files changed, 23 insertions(+), 50 deletions(-)

diff --git a/ports/mesa/portfile.cmake b/ports/mesa/portfile.cmake
index 5fa919888..2dcc52247 100644
--- a/ports/mesa/portfile.cmake
+++ b/ports/mesa/portfile.cmake
@@ -36,7 +36,7 @@ vcpkg_add_to_path("${PYTHON3_DIR}")
 vcpkg_add_to_path("${PYTHON3_DIR}/Scripts")
 set(ENV{PYTHON} "${PYTHON3}")
 
-x_vcpkg_get_python_packages(PYTHON_EXECUTABLE "${PYTHON3}" PACKAGES setuptools mako)
+x_vcpkg_get_python_packages(PACKAGES setuptools mako)
 
 vcpkg_find_acquire_program(FLEX)
 get_filename_component(FLEX_DIR "${FLEX}" DIRECTORY )
@@ -118,12 +118,12 @@ list(APPEND MESA_OPTIONS -Dshared-glapi=enabled)  #shared GLAPI required when bu
 if(VCPKG_TARGET_IS_WINDOWS)
     list(APPEND MESA_OPTIONS -Dplatforms=['windows'])
     list(APPEND MESA_OPTIONS -Dmicrosoft-clc=disabled)
-    if(NOT VCPKG_TARGET_IS_MINGW)
-        set(VCPKG_CXX_FLAGS "/D_CRT_DECLARE_NONSTDC_NAMES ${VCPKG_CXX_FLAGS}")
-        set(VCPKG_C_FLAGS "/D_CRT_DECLARE_NONSTDC_NAMES ${VCPKG_C_FLAGS}")
-    endif()
+    if(NOT VCPKG_TARGET_IS_MINGW)
+        set(VCPKG_CXX_FLAGS "/D_CRT_DECLARE_NONSTDC_NAMES ${VCPKG_CXX_FLAGS}")
+        set(VCPKG_C_FLAGS "/D_CRT_DECLARE_NONSTDC_NAMES ${VCPKG_C_FLAGS}")
+    endif()
 endif()
-
+
 vcpkg_configure_meson(
     SOURCE_PATH "${SOURCE_PATH}"
     OPTIONS 
diff --git a/ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake b/ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
index 1fee61281..8e5e960dc 100644
--- a/ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
+++ b/ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake
@@ -23,11 +23,14 @@ List of python packages to acquire
 include_guard(GLOBAL)
 
 function(x_vcpkg_get_python_packages)
-    cmake_parse_arguments(PARSE_ARGV 0 arg "" "PYTHON_EXECUTABLE" "PACKAGES")
+    cmake_parse_arguments(PARSE_ARGV 0 arg "" "PYTHON_VERSION" "PACKAGES")
     
-    if(NOT DEFINED arg_PYTHON_EXECUTABLE)
-        message(FATAL_ERROR "PYTHON_EXECUTABLE must be specified.")
+    if(NOT DEFINED arg_PYTHON_VERSION)
+        set(arg_PYTHON_VERSION 3)
+    elseif(NOT (arg_PYTHON_VERSION EQUAL "2" OR arg_PYTHON_VERSION EQUAL "3"))
+        message(FATAL_ERROR "Unsupported python version ${arg_PYTHON_VERSION}")
     endif()
+
     if(NOT DEFINED arg_PACKAGES)
         message(FATAL_ERROR "PACKAGES must be specified.")
     endif()
@@ -35,47 +38,17 @@ function(x_vcpkg_get_python_packages)
         message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} was passed extra arguments: ${arg_UNPARSED_ARGUMENTS}")
     endif()
 
-    get_filename_component(python_dir "${arg_PYTHON_EXECUTABLE}" DIRECTORY)
-
-    if (WIN32)
-        set(PYTHON_OPTION "")
-    else()
-        set(PYTHON_OPTION "--user")
-    endif()
+    set(python_variable "PYTHON${arg_PYTHON_VERSION}")
+    vcpkg_find_acquire_program("${python_variable}")
+    set(python_program "${${python_variable}}")
 
-    if("${python_dir}" MATCHES "(${DOWNLOADS}|${CURRENT_HOST_INSTALLED_DIR})") # inside vcpkg
-        if(NOT EXISTS "${python_dir}/easy_install${VCPKG_HOST_EXECUTABLE_SUFFIX}")
-            if(NOT EXISTS "${python_dir}/Scripts/pip${VCPKG_HOST_EXECUTABLE_SUFFIX}")
-                vcpkg_from_github(
-                    OUT_SOURCE_PATH PYFILE_PATH
-                    REPO pypa/get-pip
-                    REF 309a56c5fd94bd1134053a541cb4657a4e47e09d #2019-08-25
-                    SHA512 bb4b0745998a3205cd0f0963c04fb45f4614ba3b6fcbe97efe8f8614192f244b7ae62705483a5305943d6c8fedeca53b2e9905aed918d2c6106f8a9680184c7a
-                )
-                vcpkg_execute_required_process(COMMAND "${arg_PYTHON_EXECUTABLE}" "${PYFILE_PATH}/get-pip.py" ${PYTHON_OPTION}
-                                               WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}")
-            endif()
-            foreach(_package IN LISTS arg_PACKAGES)
-                vcpkg_execute_required_process(COMMAND "${python_dir}/Scripts/pip${VCPKG_HOST_EXECUTABLE_SUFFIX}" install ${_package} ${PYTHON_OPTION}
-                                               WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}")
-            endforeach()
-        else()
-            foreach(_package IN LISTS arg_PACKAGES)
-                vcpkg_execute_required_process(COMMAND "${python_dir}/easy_install${VCPKG_HOST_EXECUTABLE_SUFFIX}" ${_package}
-                                               WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}")
-            endforeach()
-        endif()
-        if(NOT VCPKG_TARGET_IS_WINDOWS)
-            vcpkg_execute_required_process(COMMAND pip3 install ${arg_PACKAGES})
-        endif()
-    else() # outside vcpkg
-        foreach(package IN LISTS arg_PACKAGES)
-            vcpkg_execute_in_download_mode(COMMAND ${arg_PYTHON_EXECUTABLE} -c "import ${package}" RESULT_VARIABLE HAS_ERROR)
+    set(ENV{PYTHONUSERBASE} "${CURRENT_BUILDTREES_DIR}/vcpkg-python-packages")
 
-            if(HAS_ERROR)
-                message(FATAL_ERROR "Python package '${package}' needs to be installed for port '${PORT}'.\nComplete list of required python packages: ${arg_PACKAGES}")
-
-            endif()
-        endforeach()
-    endif()
+    foreach(package IN LISTS arg_PACKAGES)
+        vcpkg_execute_required_process(
+            COMMAND "${python_program}" -m pip install --user ${package}
+            WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}"
+						LOGNAME "pip-install-${package}"
+        )
+    endforeach()
 endfunction()
-- 
2.32.0 (Apple Git-132)

```

2022-03-23 22:54 UTC, Neumann-A commented
> Can we do this instead?

Can we leave this up to another PR ? 
The original python stuff was added in https://github.com/microsoft/vcpkg/pull/5937 by @vicroms I assume.

2022-03-23 23:14 UTC, strega-nil-ms commented
@Neumann-A I mean we could, but I don't see what the point of this PR is if we don't actually make the helper any different.

2022-03-23 23:20 UTC, Neumann-A commented
> I mean we could, but I don't see what the point of this PR is if we don't actually make the helper any different.

The point of this PR is to provide a port with commonly used code by other ports without the need to duplicate the code itself. I mean I can alternatively keep duplicating that specific code for qtwebengine in the upcoming Qt 6.3 release .....

2022-03-30 10:26 UTC, Neumann-A commented
@strega-nil-ms: Your approach won't work since pip is not available in the embedded version of python3 vcpkg downloads on windows.

2022-04-01 00:17 UTC, strega-nil-ms commented
@Neumann-A hmm, after doing some research, it seems to me that we're making a mistake by using the embedded version of python, given that we do want to have access to pip...

2022-04-01 08:36 UTC, Neumann-A commented
> Edit: after doing more research, it seems to me that we should be using the nuget package, since it is easily downloadable and unpackable, but does not miss out on pip.

I think it doesn't really matter if we download python with pip or without it. 
Considering that the main python usage within vcpkg is limited to invoking meson and meson not requiring any additional packages, it is reasonable to not have pip by default. Only a few ports really want to have additional python packages. 

Instead of doing: https://github.com/microsoft/vcpkg/blob/27fd32e91c172e8b8a2ee338efc088a0c0103348/scripts/cmake/vcpkg_find_acquire_program.cmake#L263
we could string replace within it and changing `python310.zip` to 
```
python310.zip
Lib
Lib/site-packages
```
I wrote a batch file this week which mimics what vcpkg does but replaces the python310._pth with a version which contains the above changes:
```
curl https://www.python.org/ftp/python/3.10.4/python-3.10.4-embed-amd64.zip --output python3.10.4-x64.zip
mkdir python3
cd python3
tar -xf ..\python3.10.4-x64.zip
curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python.exe get-pip.py --no-warn-script-location
rem replace python310._pth with my version
copy python310._pth python310._pth.bak
del python310._pth
copy ..\python310._pth python310._pth
python.exe -m pip install matplotlib numpy opencv-python torch jupyterlab --no-warn-script-location
cd ..
```

> The more important thing is that we shouldn't be installing stuff in user global locations, ever.

we never do. We only download python on windows and only install packages there. 
I removed some stuff in https://github.com/microsoft/vcpkg/pull/23089/commits/03addea5d526591be028ff9072e1d0ad8d625561 which seems to be unnecessary considering the above.

2022-04-01 19:53 UTC, strega-nil-ms commented
Mmh, yeah, I'm much happier with that change.

2022-04-01 19:57 UTC, strega-nil-ms approved these changes

2022-04-05 18:21 UTC, merged

2022-04-05 18:21 UTC, strega-nil-ms commented
Thanks @Neumann-A

2022-04-05 19:21 UTC, Osyotr commented
> meson not requiring any additional packages

I remember getting errors about missing setuptools on a fresh linux VM when building ports with meson.
UPD: https://mesonbuild.com/Quick-guide.html#installation-using-package-manager

2022-04-05 19:24 UTC, Neumann-A commented
then we should add a dependency to `vcpkg-get-python-packages` in `vcpkg-tool-meson` and get the required python packages