Use static runtime if capstone wants to be statically linked
microsoft/vcpkg pull request #23122
Opened 2022-02-16 03:32 UTC by illera88

**Describe the pull request**
This makes more sense than using the shared runtime if building a static version

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

2022-02-16 06:34 UTC, JonLiu1993 commented
@illera88 ,Thanks for your pr, please add "port-version" to 3 in vcpkg.json file, and  run the command "./vcpkg x-add-version capstone --overwrite-version" and commit again

2022-02-16 07:10 UTC, illera88 commented
> @illera88 ,Thanks for your pr, please add "port-version" to 3 in vcpkg.json file, and run the command "./vcpkg x-add-version capstone --overwrite-version" and commit again

done

2022-02-17 02:40 UTC, JonLiu1993 commented on ports/capstone/portfile.cmake
> +        "static-crt"   CAPSTONE_BUILD_STATIC_RUNTIME
```suggestion
        "diet"        CAPSTONE_BUILD_DIET
        "static-crt"  CAPSTONE_BUILD_STATIC_RUNTIME 
```

2022-02-17 08:23 UTC, JonLiu1993 commented
@illera88 , When I test the features by the command "./vcpkg install capstone[*] " failed,
Please take a look:

````
[1/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\MCRegisterInfo.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\MCRegisterInfo.c
[2/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\MCInstrDesc.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\MCInstrDesc.c
[3/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\utils.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\utils.c
FAILED: CMakeFiles/capstone-shared.dir/utils.c.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\utils.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\utils.c
F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\utils.c(5): fatal error C1083: Cannot open include file: 'Availability.h': No such file or directory
[4/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\arch\AArch64\AArch64BaseInfo.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\arch\AArch64\AArch64BaseInfo.c
FAILED: CMakeFiles/capstone-shared.dir/arch/AArch64/AArch64BaseInfo.c.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\arch\AArch64\AArch64BaseInfo.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\arch\AArch64\AArch64BaseInfo.c
F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\arch\AArch64\../../utils.h(8): fatal error C1083: Cannot open include file: 'libkern/libkern.h': No such file or directory
[5/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -D [...]

2022-02-21 02:06 UTC, illera88 commented
Hi,

that's now a problem my PR has brought up. I believe you are compiling on a Linux system but passing CMake the flag `CAPSTONE_HAS_OSXKERNEL` which makes Capstone to include the following:
https://github.com/capstone-engine/capstone/blob/ea6b1a264689311ab11efb60354461e7990a2581/utils.c#L4-L9

Those headers do only exist on OSX.

2022-02-21 02:23 UTC, JonLiu1993 commented
@illera88 ,It may be that my log is not obvious, this is the X86-windows triplet tested under Windows:
````
PS F:\test-pr\capstone\vcpkg> ./vcpkg install capstone[*]
Computing installation plan...
The following packages will be built and installed:
    capstone[arm,arm64,core,diet,evm,m680x,m68k,mips,osxkernel,ppc,sparc,static-crt,sysz,tms320c64x,x86,x86-reduce,xcore]:x86-windows -> 4.0.2#3
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 3.222 ms. Use --debug to see more details.
Starting package 1/1: capstone:x86-windows
Building package capstone[arm,arm64,core,diet,evm,m680x,m68k,mips,osxkernel,ppc,sparc,static-crt,sysz,tms320c64x,x86,x86-reduce,xcore]:x86-windows...
-- Using cached aquynh-capstone-4.0.2.tar.gz.
-- Cleaning sources at F:/test-pr/capstone/vcpkg/buildtrees/capstone/src/4.0.2-30e847ef8c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test-pr/capstone/vcpkg/downloads/aquynh-capstone-4.0.2.tar.gz
-- Using source at F:/test-pr/capstone/vcpkg/buildtrees/capstone/src/4.0.2-30e847ef8c.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
  The following variables are not used in CMakeLists.txt:

      CAPSTONE_X86_ONLY

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/capstone/portfile.cmake:32 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)


-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: F:/test-pr/capstone/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: F:/test-pr/capstone/vcpkg/buildtrees/capstone/x86-windows-dbg
    See logs for more information:
      F:\test-pr\capstone\vcpkg\buildtrees\capstone\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/capstone/portfile.cmake:43 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


Error: Building package capstone:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+capstone
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[capstone]+Build+error
including:
  package: capstone[arm,arm64,core,diet,evm,m680x,m68k,mips,osxkernel,ppc,sparc,static-crt,sysz,tms320c64x,x86,x86-reduce,xcore]:x86-windows -> 4.0.2#3
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: d49e40f16 2022-02-17 (4 days ago)

Additionally, attach any relevant sections from the log files above.
````
F:\test-pr\capstone\vcpkg\buildtrees\capstone\install-x86-windows-dbg-out.log
````
[1/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\MCRegisterInfo.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\MCRegisterInfo.c
[2/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\MCInstrDesc.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\MCInstrDesc.c
[3/57] C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\MCInst.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\MCInst.c
FAILED: CMakeFiles/capstone-shared.dir/MCInst.c.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   -DCAPSTONE_ARM64_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_DIET -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_ARM64 -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_OSXKERNEL -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_SHARED -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_X86_REDUCE -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -Dcapstone_shared_EXPORTS -IF:\test-pr\capstone\vcpkg\buildtrees\capstone\src\4.0.2-30e847ef8c.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -DCAPSTONE_SHARED /showIncludes /FoCMakeFiles\capstone-shared.dir\MCInst.c.obj /FdCMakeFiles\capstone-shared.dir\ /FS -c F:\test-pr\capstone\vcpkg\buil [...]

2022-02-21 02:28 UTC, illera88 commented
Same problem applies. You are passing the `CAPSTONE_HAS_OSXKERNEL` flag and therefore this code is compiled:

```
#if defined(CAPSTONE_HAS_OSXKERNEL)
#include <Availability.h>
#include <libkern/libkern.h>
#else
#include <stdlib.h>
#endif
```

and both:
```
#include <Availability.h>
#include <libkern/libkern.h>
```
are not present under Windows. You can't do `./vcpkg install capstone[*]` in either Windows or Linux or you will run in the same problem.

But I don't think it's an error per se. You are indicating Capstone that you have a OSX Kernel in a Windows system which is not true.

2022-02-21 07:08 UTC, JackBoosY commented
If some features are not applicable to some triplets, please add the following code before `vcpkg_configure_cmake` in `portfile.cmake`:
```cmake
if ("xcore" IN_LIST FEATURES AND VCPKG_TARGET_IS_WINDOWS)
    message(FATAL_ERROR "Feature 'xcore' doesn't support Windows")
endif()
```

2022-02-21 08:03 UTC, illera88 commented
I can do that but in that case doing:
```bash
./vcpkg install capstone[*]
```
will fail

2022-02-21 08:05 UTC, JonLiu1993 commented
> I can do that but in that case doing:
> 
> ```shell
> ./vcpkg install capstone[*]
> ```
> 
> will fail

Could you provide the error log?

2022-02-21 08:13 UTC, illera88 commented
Last commit adds mentioned checks

2022-02-21 08:51 UTC, JonLiu1993 approved these changes

2022-02-21 09:30 UTC, JackBoosY requested changes

2022-02-21 09:30 UTC, JackBoosY commented on ports/capstone/portfile.cmake
> +        "static-crt"  CAPSTONE_BUILD_STATIC_RUNTIME
I noticed this feature isn't used, can you double confirm this?

If this port doesn't support static crt, please add the following lines top of this file:
```cmake
vcpkg_check_linkage(ONLY_DYNAMIC_CRT)
```

2022-02-21 10:22 UTC, illera88 commented on ports/capstone/portfile.cmake
> +        "static-crt"  CAPSTONE_BUILD_STATIC_RUNTIME
What do you mean it isn't used?
AFAIK if you do `vcpkg install capstone[static-crt]`  then `-DCAPSTONE_BUILD_STATIC_RUNTIME=ON` which will be passed to `vcpkg_cmake_configure`.

in `vcpkg.json` you can find:
```cmake
"static-crt": {
      "description": "Use Windows C Runtime Library (CRT)"
    },
```

Am I missing something?

2022-02-21 10:23 UTC, illera88 commented on ports/capstone/portfile.cmake
> +        "static-crt"  CAPSTONE_BUILD_STATIC_RUNTIME
The entire point of this PR is adding support for capstone to be built with static CRT

2022-02-21 11:53 UTC, dg0yt commented on ports/capstone/portfile.cmake
> +        "static-crt"  CAPSTONE_BUILD_STATIC_RUNTIME
Shouldn't this follow triplet settings (`VCPKG_CRT_LINKAGE`) instead of being an independent feature?

2022-02-21 12:24 UTC, illera88 commented on ports/capstone/portfile.cmake
> +        "static-crt"  CAPSTONE_BUILD_STATIC_RUNTIME
I think you are right. I updated the code to use `VCPKG_CRT_LINKAGE`

2022-02-22 01:27 UTC, JackBoosY approved these changes

2022-02-22 22:08 UTC, merged