Fixed inaccurate Chinese words
microsoft/vcpkg pull request #23179
Opened 2022-02-19 07:32 UTC by fawdlstty

**Describe the pull request**

- #### What does your PR fix?  
Fixed inaccurate Chinese words

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  not added/updated port

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-02-21 03:01 UTC, JackBoosY requested changes
能顺便根据英文文档更新一下其他内容吗？

2022-02-21 15:27 UTC, fawdlstty commented
Ok, I will check the other documents later and then report back here.

2022-02-23 02:15 UTC, JackBoosY requested changes

2022-02-23 02:15 UTC, JackBoosY commented on CONTRIBUTING_zh.md
> +Vcpkg 是一个社区驱动的努力，旨在构建一个多产的、健壮的本地库生态系统 - 你的贡献价值不可估量！
"社区驱动的努力"?

2022-02-24 08:30 UTC, Cheney-W requested changes

2022-02-24 08:30 UTC, Cheney-W commented on CONTRIBUTING_zh.md
> +- 你正在构建什么版本例如: “opencv 3.1.0”
```suggestion
- 您正在构建什么包以及它的版本，例如: “opencv 3.1.0”
```

2022-02-24 08:30 UTC, Cheney-W commented on CONTRIBUTING_zh.md
> +我们很乐意接受关于修复、特性、新包和更新现有包的拉取请求。 为了避免浪费您的时间，我们强烈建议您公开讨论您正在考虑的PR是否可以接受。 对于特性和新包来说更是如此。
```suggestion
我们很乐意接受关于修复、特性、新包和更新现有包的拉取请求。 为了避免浪费您的时间，我们强烈建议您提交一个问题来讨论您想要制作的PR是否能被接受。 对于特性和新包来说也是如此。
```

2022-02-24 08:30 UTC, Cheney-W commented on CONTRIBUTING_zh.md
> +我们很高兴您有兴趣提交一个新的包! 这里有一些指导方针来帮助你编写一个优秀的作品集:
```suggestion
我们很高兴您有兴趣来提交一个新的包! 这里有一些指导方针来帮助您编写一个优秀的端口文件:
```

2022-02-24 08:30 UTC, Cheney-W commented on CONTRIBUTING_zh.md
> +在你的pull请求被接受之前，你需要完成一个Contributor许可协议 (CLA)。 本协议证明您允许我们使用您提交的源代码，并且本作品是在合适的许可下提交的，我们可以使用它。
```suggestion
在您的拉取请求被接受之前，您需要完成一个贡献者许可协议 (CLA)。 本协议证明您允许我们使用您提交的源代码，并且本作品是在合适的许可下提交的，我们可以使用它。
```

2022-02-24 08:30 UTC, Cheney-W commented on CONTRIBUTING_zh.md
> +Vcpkg 是一个尝试由社区驱动，旨在构建一个多产的、健壮的本地库生态系统 - 你的贡献价值不可估量！
```suggestion
Vcpkg 是一个尝试由社区驱动，旨在构建一个多产的、健壮的本地库生态系统 - 您的贡献价值不可估量！
```

2022-02-24 08:32 UTC, FrankXie05 approved these changes

2022-02-24 09:30 UTC, Cheney-W approved these changes

2022-02-24 09:30 UTC, JackBoosY approved these changes

2022-02-24 09:31 UTC, FrankXie05 approved these changes

2022-02-24 09:31 UTC, JackBoosY commented
Thanks for your contribution!

2022-02-24 09:59 UTC, LilyWangLL approved these changes

2022-02-24 10:03 UTC, JonLiu1993 approved these changes

2022-02-25 01:52 UTC, Adela0814 approved these changes

2022-02-25 04:54 UTC, merged

2022-02-25 04:54 UTC, BillyONeal commented
Thanks everyone for the reviews :)