[proj, proj-4] Update to PROJ 9.0.0 & make proj the regular port
microsoft/vcpkg pull request #23186
Opened 2022-02-19 17:24 UTC by dg0yt

- #### What does your PR fix?  
  Updates to PROJ 9.0.0 (WIP, only RC at the moment).
  Makes proj the regular port instead of proj4.
  Moves cmake config to lower-case folders, and data into a subfolder.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I am still working on this PR.

2022-03-01 01:58 UTC, JackBoosY commented
Also please resolve this PR's conflicts.

Thanks.

2022-03-01 08:08 UTC, dg0yt commented
I will resolve the conflicts with the official release which we can expect today. 
Independent of that, you may validate the switch of regular and stub port which comes with this PR.

2022-03-02 11:18 UTC, dg0yt commented
> There are some most likely unrelated 7zip errors on x64_uwp and arm64 builds now?

Entirely unrelated: #23284

2022-03-03 06:20 UTC, JackBoosY approved these changes

2022-03-03 20:55 UTC, vicroms requested changes

2022-03-03 21:27 UTC, rhuijben commented on ports/proj4/vcpkg.json
> +  "version-semver": "8.9.9",
Can you explain why?
I would expect server to have stricter rules than plain version, so to be slightly better.

2022-03-03 23:17 UTC, vicroms commented on ports/proj4/vcpkg.json
> +  "version-semver": "8.9.9",
We prefer relaxed version unless upstream explicitly states that they follow semver strictly. 
I admit, it doesn't matter much here since we don't expect to keep updating the `proj4` port.

2022-03-04 00:08 UTC, vicroms approved these changes

2022-03-04 02:23 UTC, JackBoosY commented
Can you please resolve the file conflicts?

Thanks.

2022-03-04 07:10 UTC, dg0yt commented on ports/proj4/vcpkg.json
> +  "version-semver": "8.9.9",
This is intentional.
AFAIU we need to keep the version scheme to have an upgrade path with a version number which compares greater-than to the previous version.

2022-03-07 09:57 UTC, JackBoosY approved these changes

2022-03-09 07:07 UTC, dg0yt commented
Can this be merged soon? New releases for libgeotiff and gdal are coming, and I'm tired of merge conflicts from versioning meta data.

2022-03-09 07:27 UTC, JackBoosY commented
Ping @vicroms @BillyONeal for merge this quickly.

2022-03-09 18:33 UTC, merged