[arrow] add plasma support for non Windows platforms
microsoft/vcpkg pull request #23188
Opened 2022-02-20 13:07 UTC by fran6co

**Describe the pull request**

Add a way to enable plasma

2022-02-21 01:13 UTC, autoantwort requested changes

2022-02-21 01:13 UTC, autoantwort commented on ports/arrow/vcpkg.json
> +      "description": "Plasma support"
```suggestion
      "description": "Plasma support",
      "supports": "!windows"
```

2022-02-21 01:13 UTC, autoantwort commented on ports/arrow/portfile.cmake
> +
```suggestion
```

2022-02-21 06:31 UTC, LilyWangLL commented
Thanks for posting this PR. I test arrow[plasma] on Linux, and it build with the following error:
```
There should be no bin\ directory in a static build, but /home/vlilywang/Lily/vcpkg/packages/arrow_x64-linux/bin is present.
There should be no debug\bin\ directory in a static build, but /home/vlilywang/Lily/vcpkg/packages/arrow_x64-linux/debug/bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()
```
I found this exe file under the directory ${CURRENT_PACKAGES_DIR}/bin, you can use `vcpkg_copy_tools(TOOL_NAMES plasma-store-server AUTO_CLEAN)` to fix it.
![image](https://user-images.githubusercontent.com/94091114/154898023-a4edb253-d0d5-48ed-9e2e-d3070d7e6918.png)

2022-02-21 10:54 UTC, fran6co commented
> Thanks for posting this PR. I test arrow[plasma] on Linux, and it build with the following error:
> 
> ```
> There should be no bin\ directory in a static build, but /home/vlilywang/Lily/vcpkg/packages/arrow_x64-linux/bin is present.
> There should be no debug\bin\ directory in a static build, but /home/vlilywang/Lily/vcpkg/packages/arrow_x64-linux/debug/bin is present.
> If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them
> 
>     if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
>         file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
>     endif()
> ```
> 
> I found this exe file under the directory ${CURRENT_PACKAGES_DIR}/bin, you can use `vcpkg_copy_tools(TOOL_NAMES plasma-store-server AUTO_CLEAN)` to fix it. ![image](https://user-images.githubusercontent.com/94091114/154898023-a4edb253-d0d5-48ed-9e2e-d3070d7e6918.png)

Done

2022-02-22 02:23 UTC, LilyWangLL approved these changes

2022-02-22 20:08 UTC, merged