[libao] Add parameter to control whether to detect dlfcn
microsoft/vcpkg pull request #23235
Opened 2022-02-23 05:51 UTC by Cheney-W

**Describe the pull request**
In an internal CI test, libao installation failed with following errors:
```
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(291): error C2065: 'DIR': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(291): error C2065: 'plugindir': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2037: left of 'd_name' specifies undefined struct/union 'dirent'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2198: 'strlen': too few arguments for call
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2057: expected constant expression
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2466: cannot allocate an array of constant size 0
```
This issue only occurs when dlfcn-win32 installed before libao in Windows. Libao always check dlfcn.h and enable the macro HAVE_DLOPEN if dlfcn.h is exists, then the DIR struct will be compiled, in windows environment this will cause the above errors to appear.

For fixing this issue, I added a condition to the part where libao checks dlfcn, and passed parameters through vcpkg_configure_make to control whether to check or not.

No feature need to be tested.

2022-02-23 06:32 UTC, dg0yt commented
Does it need a patch, or could you just pass a corresponding cache vale (`ac_cv_...=no` or similar) to `configure`? (See `config.log...` for `ac_cv_...` variables resulting from detection.)

2022-02-23 09:08 UTC, Cheney-W commented
@dg0yt Thanks for your guidance!

2022-02-23 09:13 UTC, JackBoosY requested changes

2022-02-23 09:13 UTC, JackBoosY commented on ports/libao/portfile.cmake
>  if(VCPKG_TARGET_IS_WINDOWS)
```suggestion
set(NO_DLFCN )
if(VCPKG_TARGET_IS_WINDOWS)
```

2022-02-23 09:20 UTC, Cheney-W commented on ports/libao/portfile.cmake
>  if(VCPKG_TARGET_IS_WINDOWS)
Thanks for your remider!

2022-02-23 09:38 UTC, JackBoosY approved these changes
LGTM if the tests passed.

2022-02-23 09:39 UTC, JackBoosY commented
@vicroms Please consider to merge this PR first.

2022-02-23 19:58 UTC, merged

2022-02-24 05:27 UTC, dg0yt commented on ports/libao/portfile.cmake
> +set(NO_DLFCN )
This bad CMake style. It unset the variable in the current scope, unhiding a possible value from a parent scope. For a clean variable, always use:
~~~cmake
set(VAR "")
~~~

2022-02-24 05:28 UTC, dg0yt commented on ports/libao/portfile.cmake
> +set(NO_DLFCN )
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/cmake-guidelines.md