[loguru] Add feature to build with fmt
microsoft/vcpkg pull request #23242
Opened 2022-02-23 17:10 UTC by mrlegohead0x45

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #23231 and replaces the deprecated functions with their supported equivalents

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Same as before, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

2022-02-24 05:39 UTC, LilyWangLL commented
Feature `fmt` test pass on x64-windows.

2022-02-24 05:42 UTC, LilyWangLL requested changes

2022-02-24 05:42 UTC, LilyWangLL commented on ports/loguru/CMakeLists.txt
> +    find_package(fmt REQUIRED)
Why not use `find_package(fmt CONFIG REQUIRED)` here?

2022-02-24 16:08 UTC, mrlegohead0x45 commented on ports/loguru/CMakeLists.txt
> +    find_package(fmt REQUIRED)
Because I saw that whoever wrote the rest of the file use `find_package(Threads REQUIRED)` and I thought I should do the same, however what you suggested is what the usage for fmt says, so I will change it to that

2022-02-24 17:31 UTC, mrlegohead0x45 commented
When using this feature without
```cmake
find_package(fmt CONFIG REQUIRED)
target_link_libraries(main PRIVATE fmt::fmt)
```
(which is what the fmt usage says) in the user's `CMakeLists.txt` a `fatal error: fmt/format.h: No such file or directory` is thrown in `loguru.hpp` from the `loguru.hpp` included in the user's sources. Attempts to fix this with `target_include_directories(loguru PUBLIC fmt::fmt)` in the loguru `CMakeLists.txt` fail with
```
CMake Error in CMakeLists.txt:
  Target "loguru" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/mrlegohead/loguru-fmt/vcpkg/buildtrees/loguru/src/01c98b579e-95df5cccc7.clean/fmt::fmt"

  which is prefixed in the source directory.
```
when installing the package.
What shall I do about this?

2022-04-01 06:11 UTC, LilyWangLL requested changes

2022-04-01 06:11 UTC, LilyWangLL commented on ports/loguru/portfile.cmake
> +
```suggestion
```

2022-04-01 06:11 UTC, LilyWangLL commented on ports/loguru/portfile.cmake
>          SOURCE_PATH ${SOURCE_PATH}
```suggestion
        SOURCE_PATH "${SOURCE_PATH}"
```

2022-04-01 06:11 UTC, LilyWangLL commented
Please  run:
```
    vcpkg x-add-version loguru --overwrite-version
    git add versions
    git commit -m "Update version database"
```

2022-04-07 02:12 UTC, LilyWangLL requested changes

2022-04-07 02:12 UTC, LilyWangLL commented on ports/loguru/vcpkg.json
>    "version-string": "2.1.0",
```suggestion
  "version": "2.1.0",
```

2022-04-07 02:12 UTC, LilyWangLL commented on ports/loguru/vcpkg.json
>    "version-string": "2.1.0",
This cause CI pipeline failed.

2022-04-08 01:58 UTC, LilyWangLL commented
Version must be unique even between different schemes.
Please Run:
`
    vcpkg x-add-version loguru --overwrite-version`

2022-04-08 10:16 UTC, LilyWangLL approved these changes

2022-04-08 22:23 UTC, strega-nil-ms commented
Thanks!

2022-04-08 22:23 UTC, merged