[ffmpeg] Update to 5.0
microsoft/vcpkg pull request #23312
Opened 2022-02-28 00:39 UTC by Sibras

2022-02-28 06:29 UTC, JonLiu1993 commented
@Sibras ,Thanks for your pr, looks CI tested failed in many triplet,
Please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=68078&view=artifacts&pathAsName=false&type=publishedArtifacts

2022-02-28 10:01 UTC, Sibras commented
The errors in the CI were unfortunately somewhat expected.
ffmpeg builds fine but several other packages fail due to ffmpeg 5.0 removing older deprecated API. So any project that hasnt updated accordingly now fails to compile.

From the CI the current packages that only work with ffmpeg 4.x and not 5.x are:
aubio
avcpp
ignition
opencv4
pangolin

These projects would need to be fixed or possibly do one of those unwanted but perhaps necessary dual ffmpeg ports.

2022-02-28 11:14 UTC, cenit commented
add also opencv2 and opencv3 that are not tested by CI (which for compatibility reasons tests only opencv4) but are still used anyway

2022-03-11 10:25 UTC, JonLiu1993 commented
@Sibras ,Is this pr temporarily blocked?

2022-03-12 03:22 UTC, Sibras commented
> @Sibras ,Is this pr temporarily blocked?

Yep, I put it up so that people who want ffmpeg 5.0 know how to do it. But until a solution is provided to fix the downstream projects that are not compatible with 5.0 this PR is blocked.

Not sure what the best solution is to proceed. Either create a separate ffmpeg5 port, wait for some of those dependent projects to be fixed (some havnt been maintained for years so this is unlikely, opencv2/3 also unlikely to get fixed). Or have some way for dependency ports to specify what port versions (min/max) they support.

2022-03-18 09:13 UTC, JonLiu1993 commented
Because of blocking, temporarily convert this pr to draft

2022-04-24 14:40 UTC, ghesketh commented
> > @Sibras ,Is this pr temporarily blocked?
> 
> Yep, I put it up so that people who want ffmpeg 5.0 know how to do it. But until a solution is provided to fix the downstream projects that are not compatible with 5.0 this PR is blocked.
> 
> Not sure what the best solution is to proceed. Either create a separate ffmpeg5 port, wait for some of those dependent projects to be fixed (some havnt been maintained for years so this is unlikely, opencv2/3 also unlikely to get fixed). Or have some way for dependency ports to specify what port versions (min/max) they support.

It seems like creating a new package (e.g., ffmpeg5) would be consistent with historical vcpkg practices, such as with opencv, sdl, etc.

2022-04-24 23:00 UTC, traversaro commented
For Gazebo and ignition we have patches upstream: 
* https://github.com/osrf/gazebo/pull/3195 
* https://github.com/ignitionrobotics/ign-common/pull/325

2022-06-14 13:51 UTC, horenmar commented
For the record, newer versions of opencv should also support ffmpeg 5.

2022-06-16 09:57 UTC, cenit commented
i will try to back port support also to older version if reasonable

2022-06-28 20:22 UTC, shahneil commented
Any updates? Will there be a new port for ffmpeg v5?

2022-07-23 06:14 UTC, julianxhokaxhiu commented
5.1 has been released: http://www.ffmpeg.org/download.html#release_5.1

2022-07-23 07:30 UTC, Sibras commented
> 5.1 has been released: http://www.ffmpeg.org/download.html#release_5.1

We still need some resolution on the API breakage of downstream ports. Once that has been resolved ill update this to 5.1.

2022-07-23 17:10 UTC, horenmar commented
@Sibras I am a third party, but personally I would prefer if vcpkg had 5.0 version committed before an update to 5.1 happens. It makes keeping versions in sync between different package management methods easier, and presumably update from 5.0(.1) to 5.1 should be relatively small diff due to being the same major version.

2022-08-08 14:00 UTC, julianxhokaxhiu commented
Has there been any progress on this PR?

2022-09-01 07:44 UTC, JonLiu1993 commented
@Sibras, Can you please resolve the conflicts against master?

2022-09-02 09:30 UTC, Sibras commented
> @Sibras, Can you please resolve the conflicts against master?

Done.

2022-09-02 09:31 UTC, cenit commented on ports/ffmpeg/FindFFMPEG.cmake.in
> -  if(FFMPEG_libswresample_FOUND)
maybe you had to delete libavresample version, not libswresample's one (looking from the other diff parts)

2022-09-02 09:42 UTC, Sibras commented on ports/ffmpeg/FindFFMPEG.cmake.in
> -  if(FFMPEG_libswresample_FOUND)
not sure how that happened, fixed

2022-10-11 06:29 UTC, JonLiu1993 commented
Pinging @Sibras for response. Is work still being done for this PR?

2022-10-15 07:49 UTC, Sibras commented
Ive resolved the current merge conflicts but at present this PR is still waiting for the blocking ports to be updated to support ffmpeg5. So still in the same position as when I first put this up.

2022-12-02 06:50 UTC, JonLiu1993 commented
Duplicate of #27713

2022-12-02 08:26 UTC, julianxhokaxhiu commented
How can this be a duplicate of a PR bumping ffmpeg to 4.4.3 instead of 5.0.0?

2022-12-02 09:35 UTC, JonLiu1993 commented
> How can this be a duplicate of a PR bumping ffmpeg to 4.4.3 instead of 5.0.0?

@julianxhokaxhiu, Sorry for my misoperation, the versions released by ffmpeg are released alternately, the 4.4.3 version was released later than 5.0.0, so I made a mistake, I have reopened the PR

2022-12-02 10:28 UTC, julianxhokaxhiu commented
Thanks, no worries! All it counts is that we get this port working so we can merge ASAP. I'm waiting for it since a while as it's a dependency for one of my own projects. Looking forward!

2022-12-11 21:40 UTC, horenmar commented
Just to make sure: the update is (or at least seems to be) fine, but ffmpeg's dependees cannot use newer version yet?

2022-12-19 02:24 UTC, complexlogic commented
@JonLiu1993 FFmpeg 5 has been the stable release for almost a year now, and not much progress has been made in recent months to upgrade the dependent ports. I propose forking the current ffmpeg port as `ffmpeg4.4` or similar for incompatible ports, and upgrading the base `ffmpeg` port to version 5.

I understand having multiple ports is an increased maintenance burden, but Homebrew and virtually every Linux distro has already done this to deal with the incompatibilities. It's not realistic to expect every single port that depends on FFmpeg to be compatible with version 5.

2022-12-19 08:07 UTC, julianxhokaxhiu commented
I agree, especially I'm not sure where the vcpkg direction is going but to me it feels extremely slow. I wanted to open a discussion on this repo about this topic overall, since I have also a PR opened that is taking months to be merged. If this is a community lead project, probably we need to lower down the requirements barrier and start to accept contributions as they come if there's no one in MS capable or willing to work cooperatively in a manner of getting things done. I see more PRs getting stale than merged, and if we expect vcpkg to become a de-facto tool on the C++ world, we have to do much more than this IMHO.

Regarding this PR, let's find a middle term please because we can't keep it stale forever.

2022-12-19 08:13 UTC, Neumann-A commented
So all downstream projects need to be fixed for ffmpeg 5.0 unless that has been done this PR cannot be merged. This has also been the case for eigen3, openssl, etc. 

Currently there is also a competing PR #28387

> Regarding this PR, let's find a middle term please because we can't keep it stale forever.

If you need ffmpeg 5.0 in the meantime you can just an overlay.

2022-12-19 08:16 UTC, cnSchwarzer commented
Have you encounter the issue that building on triplet `x64-windows` will stuck at linking `libavcodec`? How do you resolve it?

2022-12-19 08:34 UTC, julianxhokaxhiu commented
> If you need ffmpeg 5.0 in the meantime you can just an overlay.

All my projects are having an overlay but is this the way to go? What's the point of using vcpkg then? The idea here is to provide less work on my shoulders and use vcpkg as any other package manager for any other language ecosystem.

2022-12-19 12:59 UTC, Neumann-A commented
> All my projects are having an overlay but is this the way to go? 

Yes if it is not appropriate for the main repo (yet) an overlay is a valid solution. 

> What's the point of using vcpkg then? 

ffmpeg has dependencies doesn't it? Do you have all of them overlayed? Also there is downstream use of ffmpeg which you probably also didn't overlay.

> The idea here is to provide less work on my shoulders and use vcpkg as any other package manager for any other language ecosystem.

By having this PR open you are already reducing the workload of others since they can use this PR as a basis for their own overlays. Also at some point this or another PR updating ffmpeg will probably be merged. 
You are just not happy with the timescale but you could actively fix that by fixing all downstream usages and make CI happy ;).

2022-12-19 14:00 UTC, cnSchwarzer commented
I think there's no point to stick to `ffmpeg`, as 5.x deprecated and removed many things, it is also too complex to update all downstreams that you might don't even know what's the port is about. There're even might be unfixable if you don't change source of such port. I still strongly recomment create `ffmpeg50` and leave all depencency to 4.x. It is easier for all of us.

2022-12-19 14:38 UTC, Sibras commented
Currently the broken projects that dont currently support ffmpeg 5+ are:
aubio
avcpp
pangolin
ignition.

I had a go at updating some of those within this patch to hurry things along:
pangolin [done]: seems to be fixed with latest version
avcpp [help needed]: Fixed but introduced a new issue that seems to be around pkg_config detection (I dont have further time to debug this so help wanted here)
aubio [done]: latest master branch seems to fix issue
ignition [help needed]: Latest version should support ffmpeg 5+ but the version in vcpkg is really old. This would need to be updated by someone more familiar with it (as its rather complicated) pinging @traversaro

2022-12-20 13:45 UTC, traversaro commented
> ~This would need to be updated by someone more familiar with it (as its rather complicated) pinging @traversaro~ Updated just ignition-common3 and its dependencies.

Great! Sorry I just read this comment.

2022-12-20 14:00 UTC, Sibras commented
OK I think I have fixed all the broken downstreams, just waiting for the CI to confirm.
Changed this from draft.

2022-12-20 14:04 UTC, Neumann-A commented on ports/aubio/vcpkg.json
> +  "version-date": "2022-01-26",
I probably would do 
`"version": "0.4.9+20220126",`
but would let that detail open for discussion.  
Don't actually know which one is better from a versioning perspective. 
cc @BillyONeal

2022-12-20 14:06 UTC, Neumann-A commented on ports/ffmpeg/portfile.cmake
> -endif()
probably better to print a message that the feature has been deprecated.

2022-12-20 14:08 UTC, Neumann-A commented on ports/pangolin/vcpkg.json
> -    },
feature removal is not an option since it breaks `vcpkg upgrade` features can only be declared deprecated and made empty.

2022-12-20 14:09 UTC, Neumann-A commented on ports/pangolin/vcpkg.json
> -    "video"
What up with all those removed features? Are they now integrated by default?

2022-12-20 14:11 UTC, Neumann-A commented
@Sibras small tipp: If you fan out the smaller port updates in single PRs it is probable that those gets merged fast making this PR smaller and thus easier to review.

2022-12-21 11:14 UTC, Sibras commented on ports/ffmpeg/portfile.cmake
> -endif()
It was actually deprecated several years ago, with the 5.0 release it has now been completely removed

2022-12-21 11:16 UTC, Sibras commented on ports/ffmpeg/vcpkg.json
> -            "avresample",
swresample has been the replacement for avresample and avresample itself was only an option for compatibility with the now defunct libav port. So no features have been lost just the old compatibility avresample has been removed

2022-12-21 11:18 UTC, Sibras commented on ports/pangolin/vcpkg.json
> -    "video"
Yep, they are now all default and can no longer be enabled/disabled

2022-12-21 11:19 UTC, Sibras commented on ports/pangolin/vcpkg.json
> -    },
eigen3 is now a hard dependency and no longer an optional feature

2022-12-21 11:21 UTC, Sibras commented
> @Sibras small tipp: If you fan out the smaller port updates in single PRs it is probable that those gets merged fast making this PR smaller and thus easier to review.

I needed the CI to test and make sure they worked with ffmepg 5.0 before I split them, once everything is clean ill split them into separate PRs if required.

2022-12-21 11:27 UTC, Sibras commented on ports/aubio/vcpkg.json
> +  "version-date": "2022-01-26",
Well technically its newer than 0.4.9 and is part of the development branch for whatever version comes after 0.4.9 (yet to be defined by the developer) which is why I just left it as the date

2022-12-22 11:45 UTC, Sibras commented
Separated the other effected ports into other PRs:
[aubio] Update to latest master. [#28491](https://github.com/microsoft/vcpkg/pull/28491)
[pangolin] Update to 0.8. [#28492](https://github.com/microsoft/vcpkg/pull/28492)
[avcpp] Update to version 2.1.0. [#28493](https://github.com/microsoft/vcpkg/pull/28493)
[discordcoreapi] Fix compilation with ffmpeg. [#28494](https://github.com/microsoft/vcpkg/pull/28494)
[ignition-common3] Update to 3.14.1. [#28495](https://github.com/microsoft/vcpkg/pull/28495)

2022-12-23 07:06 UTC, JonLiu1993 approved these changes, later dismissed

2022-12-30 09:37 UTC, JonLiu1993 requested changes

2022-12-30 09:37 UTC, JonLiu1993 commented on versions/f-/ffmpeg.json
> -      "port-version": 2
@Sibras, Don't change the history "git-tree", please add new one.

2022-12-30 13:34 UTC, Sibras commented on versions/f-/ffmpeg.json
> -      "port-version": 2
Fixed, got messed up in one of the many upstream merges.

2022-12-31 14:46 UTC, Sibras commented
All dependent ports have now been updated in master, this PR is now good to go.

2023-01-03 10:51 UTC, JonLiu1993 approved these changes

2023-01-03 18:32 UTC, merged

2023-01-03 18:32 UTC, vicroms commented
Thanks for all the hard work!