[libssh2] Fix various issues
microsoft/vcpkg pull request #23327
Opened 2022-02-28 23:37 UTC by Thomas1664

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #12939
  Fix copyright
  Fix deprecated cmake
  Fix issues with DLL not exporting symbols

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I am still working on this PR

TODO:

- [ ] Make `zlib` optional
- [ ] Support for other crypto libraries

Reference: https://github.com/libssh2/libssh2/blob/master/docs/INSTALL_CMAKE.md

2022-03-01 02:08 UTC, JackBoosY requested changes

2022-03-01 02:08 UTC, JackBoosY commented on ports/libssh2/portfile.cmake
> +endif()
`BUILD_SHARED_LIBS` was already set in `vcpkg_cmake_configure` according to `VCPKG_LIBRARY_LINKAGE`.
https://github.com/microsoft/vcpkg/blob/b726998b816c583ff549e29d98fe06dbd6d0f694/ports/vcpkg-cmake/vcpkg_cmake_configure.cmake#L263-L271

2022-03-01 07:29 UTC, Thomas1664 commented on ports/libssh2/portfile.cmake
> +endif()
Didn't know why I needed this in the fist place (maybe `vcpkg_configure_cmake` vs `vcpkg_cmake_configure`). Builds now without it.

2022-03-01 07:42 UTC, Thomas1664 commented
Does implementing alternatives to OpenSSL not violate the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives)?

> Do not use features to implement alternatives
> Features must be treated as additive functionality. If port[featureA] installs and port[featureB] installs, then port[featureA,featureB] must install. Moreover, if a second port depends on [featureA] and a third port depends on [featureB], installing both the second and third ports should have their dependencies satisfied.

2022-03-01 09:02 UTC, Thomas1664 commented
@JackBoosY There is an [upstream issue](https://github.com/libssh2/libssh2/issues/595) about dll bugs causing our post build checks to fail. Is disabling dynamic linking on Windows and UWP ok?

2022-03-01 09:04 UTC, JackBoosY commented
@Thomas1664 Yes we can accept it.

2022-03-01 09:06 UTC, JackBoosY commented
> Does implementing alternatives to OpenSSL not violate the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives)?
> 
> > Do not use features to implement alternatives
> > Features must be treated as additive functionality. If port[featureA] installs and port[featureB] installs, then port[featureA,featureB] must install. Moreover, if a second port depends on [featureA] and a third port depends on [featureB], installing both the second and third ports should have their dependencies satisfied.

Sadly, I think so.

2022-03-01 09:08 UTC, Thomas1664 commented
> Sadly, I think it will.

@JackBoosY Then I'm ready for review

2022-03-01 09:08 UTC, JackBoosY commented
I noticed that you left a TODO item, is this PR really ready for review?

2022-03-01 09:18 UTC, JackBoosY requested changes

2022-03-01 09:18 UTC, JackBoosY commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
So why So why was there no error without these conditions originally? The source code is unchanged.

2022-03-01 09:22 UTC, Thomas1664 commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
The last update of libssh2 was at 11th October last year. Maybe there was a change in CI checks since then?

2022-03-01 09:25 UTC, JackBoosY commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
I will check it locally.

2022-03-01 09:30 UTC, Thomas1664 commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
@JackBoosY I figured it out: The new cmake functions are the problem.
From PR #20364:

> One thing I am not sure about is vcpkg build validation errors related to the DLL not having any exports and no import library getting built when I migrated to the new way of including CMake commands (vcpkg-cmake and vcpkg-cmake-config dependencies). Only after reverting this change (https://github.com/microsoft/vcpkg/commit/0fe70113b3b55579fafb0c0b0da3fcaf95377f91) it works again.

So it seems vcpkg_configure_cmake is not equivalent to vcpkg_cmake_configure? Do you know what needs to be changed to make it work with the new commands?

2022-03-01 09:34 UTC, JackBoosY commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
Let me try to compile the dynamic one first,

2022-03-01 09:41 UTC, Thomas1664 commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
Fixed setting `WINDOWS_USE_MSBUILD` in `vcpkg_cmake_configure`

2022-03-01 09:45 UTC, JackBoosY commented on ports/libssh2/vcpkg.json
> +  "supports": "!(!static & (windows | uwp))",
I believe this changes can not fix this.
In _SOURCE/include/libssh2.h_ line 101:
```cpp
#ifndef LIBSSH2_API
# ifdef LIBSSH2_WIN32
#  ifdef _WINDLL
#   ifdef LIBSSH2_LIBRARY
#    define LIBSSH2_API __declspec(dllexport)
#   else
#    define LIBSSH2_API __declspec(dllimport)
#   endif /* LIBSSH2_LIBRARY */
#  else
#   define LIBSSH2_API
#  endif
# else /* !LIBSSH2_WIN32 */
#  define LIBSSH2_API
# endif /* LIBSSH2_WIN32 */
#endif /* LIBSSH2_API */
```
In dynamic-windows build, `LIBSSH2_WIN32`, `_WINDLL` and `LIBSSH2_LIBRARY` should be defined in the cmake code, but I didn't find the last 2 definitions.

2022-03-01 09:46 UTC, Thomas1664 commented
@JackBoosY Getting following error un OSX:

```
CMake Error at /Users/vagrant/Data/installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:228 (message):
  Unable to determine appropriate generator for: Darwin-x64-external
Call Stack (most recent call first):
  ports/libssh2/portfile.cmake:15 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)
```

2022-03-01 09:58 UTC, JackBoosY approved these changes
LGTM if the tests passed.

2022-03-03 02:41 UTC, JonLiu1993 commented
The function is successfully tested on the local machine

2022-03-03 20:52 UTC, merged

2022-03-11 16:54 UTC, swt2c commented
@Thomas1664, this seems to have caused a regression for curl, see #23505.