[zeromq] Update checksum for patch patch4311
microsoft/vcpkg pull request #23435
Opened 2022-03-08 19:22 UTC by zmughal

GitHub is returning different checksum for the same patch now because
the index objects are abbreviated to 9 characters instead of 10
characters:

```diff
+ index 24cce83d1..c6d625188 100644
- index 24cce83d11..c6d625188d 100644
```
Reported at <https://github.com/microsoft/vcpkg/pull/22681#issuecomment-1061312320>.

A possible long-term fix is reported to GitHub at
<https://github.com/github/feedback/discussions/12531>.

- #### What does your PR fix?

  Fixes checksum for patch.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

  No.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

  I am still working on this PR.

2022-03-08 19:56 UTC, zmughal commented
@JackBoosY, this PR addresses the earlier report I wrote. Not sure why the builds are having problems with retrieving CMake.

2022-03-09 01:50 UTC, zmughal commented
/azp run

2022-03-09 01:50 UTC, FrankXie05 approved these changes

2022-03-09 01:58 UTC, zmughal commented
It appears that the other patch is now also intermittently switching:

```shell
$ curl "https://patch-diff.githubusercontent.com/raw/zeromq/libzmq/pull/4310.diff" |  sha512sum
```
between outputs:
```
64e6d37ab843e5b9aa9e56ba7904423ce0a2c6b4101dbd86b7b8b22c52c384ed7ea9764f9e0a53be04e7ade09923ca95452104e9760b66ebc0ed3ffef08a75c5  4310.diff
42663c9b16a09a5c30d61a027c544ea318a9f745129579dcc0d5dd2d529be42e8dbaee1b9406497c4da7815fa60fc877d2e26f807135b2bbc0ea7ea4214b8af6  4310.diff
```

It might end up changing as well and this build will fail again. Perhaps the patch file should be checked in.

2022-03-09 02:05 UTC, FrankXie05 commented
/azp run

2022-03-09 02:51 UTC, JackBoosY requested changes

2022-03-09 02:51 UTC, JackBoosY commented on ports/zeromq/portfile.cmake
> +    SHA512 08c3f000eb1582c94473d83c05b64f8934a14d18446faa10a396b8425eba108363cbb3382b7c95ffea8589ed5312244cd3cf76c3e49db20071dfae7c5d9e94ed
```suggestion
    SKIP_SHA512
```

2022-03-09 02:51 UTC, JackBoosY commented on ports/zeromq/portfile.cmake
>      FILENAME "zeromq-libzmq-4311.diff"
Or
```suggestion
    FILENAME "zeromq-libzmq-4311-08c3fe94ed.diff"
```

2022-03-09 03:34 UTC, zmughal commented
I decided to skip the SHA512 on both GitHub PR patches. Since both are already merged, they should not change.

2022-03-09 03:38 UTC, zmughal commented
Ah, `SKIP_SHA512` will not work:

```
### SKIP_SHA512
Skip SHA512 hash check for file.

This switch is only valid when building with the `--head` command line flag.
```

I will pull the patch files into the directory.

2022-03-09 06:18 UTC, JackBoosY commented
@ras0219-msft  Since using github to download patches may have commit id inconsistencies, what do you think about it?

2022-03-09 06:27 UTC, JackBoosY approved these changes

2022-03-10 21:10 UTC, zmughal commented
By the way, there are a couple other ports that use GitHub PR URLs:

```sh
$ git -P grep -l URLS.*patch-diff
ports/brpc/portfile.cmake
ports/libsrtp/portfile.cmake
```

2022-03-15 02:03 UTC, zmughal commented
Is this PR ready to go? @ras0219-msft?

2022-03-15 21:07 UTC, merged