[vlpp] update
microsoft/vcpkg pull request #23432
Opened 2022-03-08 18:44 UTC by autoantwort

2022-03-08 19:05 UTC, autoantwort commented
It seems that the linux build is broken

2022-03-09 02:26 UTC, Adela0814 requested changes

2022-03-09 02:26 UTC, Adela0814 commented on ports/vlpp/vcpkg.json
> +  "supports": "!(osx & arm64)",
I wonder why these two triplets no longer supported, I didn't see the related documents.

2022-03-09 02:26 UTC, Adela0814 commented on ports/vlpp/vcpkg.json
> +  "license": null,
The license in the port homepage is `Apache License 2.0 with extra conditions`, I think you can change it to `Apache-2.0`

2022-03-09 05:06 UTC, dg0yt commented on ports/vlpp/vcpkg.json
> +  "license": null,
Please don't! Either I can rely on this field, or it is worthless for all ports. `null` means: Read the license.

2022-03-09 14:54 UTC, autoantwort commented on ports/vlpp/vcpkg.json
> +  "license": null,
> Please don't change it to Apache-2.0! Either I can rely on this field (no extra restrictions), or it is worthless for all ports. null means: Read the license - this is the right thing here.

This!!

2022-03-21 06:52 UTC, Adela0814 commented
@autoantwort  Are you trying to fix the build error of Linux？
I wonder if this port has never been built successfully on `Linux`? If so, you can add it to `supports` as `osx` and `arm64`.

2022-03-21 06:52 UTC, Adela0814 commented
@autoantwort  Are you trying to fix the build error of Linux？
I wonder if this port has never been built successfully on `Linux`? If so, you can add it to `supports` as `osx` and `arm64`.

2022-04-01 09:06 UTC, Adela0814 commented
Convert this PR to draft since there is no progress for a long time.

2022-06-24 06:08 UTC, Adela0814 commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2022-06-24 06:08 UTC, closed without merging