2022 03 19 glib update
microsoft/vcpkg pull request #23652
Opened 2022-03-19 07:34 UTC by SchaichAlonso

**Describe the pull request**
Update glib and it's C++ wrapper (glibmm).

- #### What does your PR fix?  
  Fixes #23647 , #23649 and #23650 .

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
(https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  any linux and non-static windows, CI baseline was not updated

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-03-19 11:28 UTC, Thomas1664 requested changes

2022-03-19 11:28 UTC, Thomas1664 commented on ports/glibmm/vcpkg.json
> +  "port-version": 1,
```suggestion
  "version": "2.70.0",
```

2022-03-19 11:28 UTC, Thomas1664 commented on versions/g-/glibmm.json
> +    },
```suggestion
```
Please remove this and run `vcpkg x-add-version glibmm --overwrite-version` after you committed all changes.

2022-03-19 11:28 UTC, Thomas1664 commented on versions/baseline.json
> +      "port-version": 1
```suggestion
      "port-version": 0
```

2022-03-19 11:40 UTC, SchaichAlonso commented on versions/baseline.json
> +      "port-version": 1
done and re-pushed

2022-03-19 12:09 UTC, Thomas1664 commented
Please run `vcpkg x-add-version glibmm --overwrite-version`. Because you modified `ports/glibmm/vcpkg.json` the old commit hash isn't valid anymore.

2022-03-19 13:07 UTC, Thomas1664 approved these changes

2022-03-21 02:40 UTC, JackBoosY approved these changes

2022-03-21 20:42 UTC, merged