[vcpkg baseline][cairo] Add option atomic-ops and disable it
microsoft/vcpkg pull request #23999
Opened 2022-04-06 08:58 UTC by JackBoosY

cairo will automatically detect `libatomic-ops` and enable this feature when discovered. But using it in cairo has some issues.
I have opened an issue upstream: https://gitlab.freedesktop.org/cairo/cairo/-/issues/554
Since cairo uses auto-detection instead of options, we can't add dependencies explicitly, so I added a feature and disabled it until upstream fixes this.

Replace #23995.

2022-04-06 10:14 UTC, LilyWangLL approved these changes

2022-04-06 18:24 UTC, strega-nil-ms requested changes
I also think we should just remove the check for `atomic_ops.h`, so that it will still check for `atomic-ops-cxx11` and `atomic-ops-gcc-legacy` and `libkern/OSAtomic.h` (OSX built-in atomics)

2022-04-06 18:24 UTC, strega-nil-ms commented on ports/cairo/add-option-atomic-ops.patch
> ++if get_option('atomic-ops').enabled()
```suggestion
+if false
```

2022-04-07 07:01 UTC, JackBoosY commented
@strega-nil-ms Done.

2022-04-07 14:45 UTC, strega-nil-ms commented
Thanks!

2022-04-07 14:45 UTC, merged