[zziplib] Update to v0.13.72
microsoft/vcpkg pull request #24011
Opened 2022-04-07 05:07 UTC by dg0yt

- #### What does your PR fix?
  Updates and modernize zziplib.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR.

2022-04-07 06:00 UTC, dg0yt commented
CC @autoantwort @strega-nil-ms @ras0219-msft I picked this port to address issues with the formatting check:
The action fails when version scheme `version-string` is used. (Cf. first push, [a2885af](https://github.com/microsoft/vcpkg/pull/24011/commits/a2885af063adf2a3658eb3b08a75855bbe24a92a).)
 - vcpkg tool blindly suggest to use scheme `version` even if the value doesn't match the requirements for this scheme, and returns with error. Output (Cf. https://github.com/microsoft/vcpkg/pull/24011#pullrequestreview-934511407):
   ~~~
   Consider using another version scheme instead of "version-string" in port "zziplib".
   Use `--skip-version-format-check` to disable this check.
   ~~~
 - Reviewers blindly suggested the same to other contributors.

This PR now fixes that situation, by re-running `vcpkg x-add-version` with `--skip-version-format-check`, and by modifying the output (cf. https://github.com/microsoft/vcpkg/pull/24011#pullrequestreview-934512941).
~~~
Consider using another version scheme instead of "version-string" in port "zziplib".
~~~

This is offered as an immediate mitigation. It might be necessary to make changes to the tool.

2022-04-07 09:42 UTC, JackBoosY requested changes

2022-04-07 09:42 UTC, JackBoosY commented on ports/zziplib/cmake-project-include.cmake
> +if(WIN32)
If upstream rejects this change, I'd like to approve this.

2022-04-07 09:42 UTC, JackBoosY commented on ports/zziplib/portfile.cmake
> +    "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/zzipmmapped.pc"
Why not fix them?

2022-04-07 09:42 UTC, JackBoosY commented on ports/zziplib/portfile.cmake
> +file(READ "${SOURCE_PATH}/docs/COPYING.LIB" lgpl)
I'm not sure about this part.

2022-04-07 09:52 UTC, dg0yt commented on ports/zziplib/cmake-project-include.cmake
> +if(WIN32)
This was previously in `VCPKG_C_FLAGS` in the portfile. But `VCPKG_C_FLAGS` depends on the chainloaded toolchain, and the portfile lack the windows condition.
So either accept it here, or I will restore the portfile code.

2022-04-07 09:52 UTC, dg0yt commented on ports/zziplib/portfile.cmake
> +    "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/zzipmmapped.pc"
Because the port never always turned off building these libraries, and nobody cared.
(Hello `vpckg_pkgconfig_valdidate`...)

2022-04-07 09:52 UTC, dg0yt commented on ports/zziplib/portfile.cmake
> +file(READ "${SOURCE_PATH}/docs/COPYING.LIB" lgpl)
About the actual licensing, look at the sources.
About implementing dual-license in ports, ask @ras0219-msft. This is based on previous discussions.

2022-04-07 11:15 UTC, autoantwort commented
> vcpkg tool blindly suggest to use scheme version even if the value doesn't match the requirements for this scheme

That is not true. See 
https://github.com/microsoft/vcpkg-tool/blob/0840ffdf10c20c23fc5b9a048e1d7f896e3e76b1/src/vcpkg/commands.add-version.cpp#L70-L93

2022-04-07 16:55 UTC, strega-nil-ms commented on .github/workflows/untrustedPR.yml
> +            ./vcpkg x-add-version --all --skip-formatting-check --skip-version-format-check >> .github-pr.x-add-version.out
what's up with this change?

2022-04-07 16:56 UTC, strega-nil-ms commented
@dg0yt I have no idea what you mean; `0.13.72` is a totally fine `"version"`

2022-04-07 18:27 UTC, dg0yt commented on .github/workflows/untrustedPR.yml
> +            ./vcpkg x-add-version --all --skip-formatting-check --skip-version-format-check >> .github-pr.x-add-version.out
It fixes the broken GH Action when running into `version-string`.

2022-04-07 18:33 UTC, dg0yt commented
> @dg0yt I have no idea what you mean; `0.13.72` is a totally fine `"version"`

@strega-nil-ms I was concerned about `"version-string": "1.1.1-3651f232c27074c4ceead169e223edf5f00247c5"`, as touched in another PR.

With all these literals being acceptable `version`s, the GH Action should really pass the tool's proposal, not exit with error.
Demonstrating and fixing the GH Action was the main motivation of this PR. I will update it again in a way that verifies the desired change.

2022-04-08 05:20 UTC, dg0yt commented
> Use the version scheme "version" instead of "version-string" in port "zziplib".

:tada:

2022-04-08 05:31 UTC, dg0yt commented
Now the GH Action no longer fails, and it captures the messages as needed.
- I decided to not block "approval" in presence of a  `version-string` - I'm not sure if there might be valid cases for staying with that scheme even if the relaxed `version` scheme "matches".
- It would be possible to generate a diff for the proposed version scheme change. However, it would need to handle two scheme already now (`version`, `version-date`), so it is more than one extra line.

2022-04-08 06:53 UTC, dg0yt commented
:tada: llvm:x64-windows restored from cache, finally. (https://github.com/microsoft/vcpkg/pull/23896)

2022-04-08 07:13 UTC, dg0yt commented
> I remembered a different observation.

FTR it was here https://github.com/microsoft/vcpkg/pull/23532#issuecomment-1085511034. But this was also just based on assumptions, and in practice, `164-5db6aa6cab1b146` is accepted as `version`.

2022-04-08 07:58 UTC, JackBoosY approved these changes

2022-04-08 18:56 UTC, strega-nil commented
I disagree strongly with the `"version-string"` change (and at _least_ it should be its own PR) - `"version-string"` is a back-compat hack that should almost never be used.

2022-04-08 19:12 UTC, dg0yt commented
> I disagree strongly with the `"version-string"` change 

Which change?

>(and at _least_ it should be its own PR)

I can split the PR for final history, but I had to verify that it works. Unfortunately, I still didn't get the message through, despite providing the demonstration in the history of this PR.

>  `"version-string"` is a back-compat hack that should almost never be used.

So where is the problem?

- Current CI behaviour: the PR suggestion action fails if there is `version-string`. User confused.
- New CI behaviour: the PR suggestion passes the tool's suggestion to replace `version-string`. User can act.

2022-04-08 19:58 UTC, strega-nil commented
Oh shit! I totally missed what it was actually doing, sorry.

2022-04-08 19:58 UTC, merged