Update skia
microsoft/vcpkg pull request #24066
Opened 2022-04-10 08:42 UTC by bold84

**Describe the pull request**

- #### What does your PR fix?
  Updates Skia to newer version

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-04-11 06:57 UTC, JonLiu1993 commented on ports/skia/portfile.cmake
> +    #PATCHES add-missing-tuple.patch
@bold84 ,Thanks for posting this issue, could you clarify why remove this patch?

2022-04-11 06:57 UTC, JonLiu1993 commented on ports/skia/portfile.cmake
> +
```suggestion
```

2022-04-11 07:00 UTC, bold84 commented on ports/skia/portfile.cmake
> +    #PATCHES add-missing-tuple.patch
Actually.. I just realized that the workspace wasn't clean when I updated the version. The opengl feature was also not intended to be part of this PR. 
I will look into this to find out why I disabled this PR.

2022-04-11 08:21 UTC, JonLiu1993 commented
@bold84 , If this pr is ready for review please let me know, thanks!

2022-04-14 12:28 UTC, bold84 commented
This depends on https://github.com/microsoft/vcpkg/pull/24142

2022-04-15 20:04 UTC, bold84 commented
This is weird... I don't have these errors on two Windows machines with Windows 11 and VS 2022. 

What's even weirder is that even the zeroc-ice port (x64-windows-static) suddenly fails on your windows servers, although nothing was changed. 

<img width="997" alt="Screen Shot 2022-04-16 at 03 02 56" src="https://user-images.githubusercontent.com/21118257/163626746-1d584486-b4c8-4ed7-857f-10b4b66c9ef5.png">

2022-04-16 06:28 UTC, dg0yt commented
> What's even weirder is that even the zeroc-ice port (x64-windows-static) suddenly fails on your windows servers, although nothing was changed.

This is a baseline regression, also failing in the daily full builds: https://dev.azure.com/vcpkg/public/_build/results?buildId=70644&view=results

2022-04-16 06:53 UTC, bold84 commented
That you for letting me know. I figured that out by now 😊.
I was able to reproduce the issues and make everything build successfully, despite the regression.

I think that this was a good opportunity to fix a potential problem with the zeroc-ice port.

I will push the changes soon (still in bed).

2022-04-16 08:00 UTC, dg0yt commented
@bold84 There is already other work on zero-ice: #24169

2022-04-17 10:24 UTC, bold84 commented
1. x86-windows has been disabled for skia. 
<img width="927" alt="Screen Shot 2022-04-17 at 17 18 09" src="https://user-images.githubusercontent.com/21118257/163710308-891f8593-5b26-4186-a3c6-70e1a7f912e9.png">

2. v8 has been disabled or expected to fail on linux
<img width="484" alt="Screen Shot 2022-04-17 at 17 19 16" src="https://user-images.githubusercontent.com/21118257/163710331-5b18ae62-7b86-4a62-ae14-30615ec955f7.png">

3. Skia fails to build on linux. It's looking for fontconfig/fontconfig.h which is present but isn't found. I will solve this problem later. 

4. zeroc-ice port has been changed so that the crt linkage and library linkage are now written directly to the project files before msbuild is called. @strega-nil please confirm that this solves the static crt issue you had.

2022-04-17 11:39 UTC, dg0yt reviewed
Maybe it would be better to add a versioned `vcpkg-tool-gn` port instead of updating the `vcpkg_find_acquire_program`. Similar to `vcpkg-tool-meson` etc.

This would also avoid the world rebuilds which are triggered from touching that script.

2022-04-17 11:39 UTC, dg0yt commented on scripts/ci.baseline.txt
> +v8:x84-linux=fail
IIUC there is no PR CI left for v8.
And I guess from the headline that these four windows entries were intentionally listed separately.
Last not least this heavily overlaps with the `supports` field in v8 manifest.

2022-04-17 11:39 UTC, dg0yt commented on scripts/ci.baseline.txt
> +skia:x86-windows=fail # skia doesn't support x86 builds with local MSVC installations
This is redundant, given the `supports` field in the manifest.
And I really don't understand what "local" is meant to indicate here.

2022-04-17 11:39 UTC, dg0yt commented on ports/skia/portfile.cmake
> +        set(${OUTPUT_} "[\"${TEMP}\"]" PARENT_SCOPE)
Extra whitespace.

2022-04-17 11:39 UTC, dg0yt commented on ports/skia/portfile.cmake
> +    "webp;webpdemux;webpdecoder;libwebpmux,webpmux" "")
Outdated. Update your webp installation.

2022-04-17 11:39 UTC, dg0yt commented on ports/skia/portfile.cmake
> +set(OPTIONS "${OPTIONS} target_cpu=\"${VCPKG_TARGET_ARCHITECTURE}\"")
Embedded quotes invite cross-platform issues.
Apart from that, `string(APPEND )` may make the appending a more explicit string operation.

2022-04-17 11:39 UTC, dg0yt commented on ports/skia/portfile.cmake
> +file(COPY "${SOURCE_PATH}/include"
Extra whitespace here and below.

2022-04-17 12:28 UTC, bold84 commented on ports/skia/portfile.cmake
> +set(OPTIONS "${OPTIONS} target_cpu=\"${VCPKG_TARGET_ARCHITECTURE}\"")
I've tried several other ways... single quotes, no quotes... GN doesn't accept the architecture string without double quotes.

2022-04-17 12:32 UTC, bold84 commented on scripts/ci.baseline.txt
> +skia:x86-windows=fail # skia doesn't support x86 builds with local MSVC installations
It's a text I copied from their BUILD.gn file. 

See the screenshot:
https://github.com/microsoft/vcpkg/pull/24066#issuecomment-1100848079

2022-04-17 12:39 UTC, bold84 commented on scripts/ci.baseline.txt
> +v8:x84-linux=fail
I moved them together, so there aren't many different locations with information for the same port. 

I started updating v8, but soon got into difficulties. The build requires the breakpad python module. Removing that line caused a whole lot of other errors and since I originally just wanted to update gn and skia and because the current v8 version doesn't build with vs2022 anyways, I thought it might not hurt not caring too much about it.

How do you mean overlaps with the supports field?

2022-04-17 12:49 UTC, bold84 commented on scripts/ci.baseline.txt
> +v8:x84-linux=fail
vcpkg-tool-gn, alright... will add in a separate PR (or in this one?)

2022-04-17 14:12 UTC, dg0yt commented on scripts/ci.baseline.txt
> +v8:x84-linux=fail
> I moved them together, so there aren't many different locations with information for the same port.

AFAIU there is alphabetical group of generic issues, and a number of groups with specific, sometimes temporary, issues. So in general, "there aren't many different locations with information for the same port". 

> How do you mean overlaps with the supports field?

If a port (upstream) doesn't support a platform at all, it must be excluded via `supports` and doesn't need an entry in `ci.baseline.txt`.
Only if a platform is supported, but fails in CI, it should have a `fail` entry. Or a `skip` entry if  a port causes conflicts.
`fail` entries are still built in daily CI, to detect what unexpected pass.

2022-04-17 14:17 UTC, bold84 commented on scripts/ci.baseline.txt
> +v8:x84-linux=fail
> AFAIU there is alphabetical group of generic issues, and a number of groups with specific, sometimes temporary, issues. So in general, "there aren't many different locations with information for the same port".
Oh... I didn't know that. I will separate them again. 

> If a port (upstream) doesn't support a platform at all, it must be excluded via `supports` and doesn't need an entry in `ci.baseline.txt`. Only if a platform is supported, but fails in CI, it should have a `fail` entry. Or a `skip` entry if a port causes conflicts. `fail` entries are still built in daily CI, to detect unexpected pass.
Ahh... :-) Thank you for the explanation. I thought they have to be added to both locations (`supports` and `ci.baseline.txt`). I'll fix it. ☺️

2022-04-17 15:01 UTC, bold84 commented on ports/skia/portfile.cmake
> +    #PATCHES add-missing-tuple.patch
The patches have been removed because they fail. And I have seen somewhere that these changes have already been merged to skia. But I can't find anymore where. :-(

2022-04-17 18:47 UTC, bold84 commented
Because I assume that this PR triggers a "world build" with every commit, I will continue working on Skia here:

https://github.com/bold84/vcpkg/tree/update_skia_local

Once this PR is merged, I will open a new PR with the changes therein.

2022-04-18 02:50 UTC, bold84 commented
What distribution are these linux builds running on?

<img width="1028" alt="Screen Shot 2022-04-18 at 09 49 42" src="https://user-images.githubusercontent.com/21118257/163746617-d369cb26-ed71-4413-a4e4-e1524762fffb.png">

2022-04-18 04:33 UTC, dg0yt commented
> What distribution are these linux builds running on?

It shouldn't matter.
~~~
/usr/bin/ld: cannot find -lmcpp
collect2: error: ld returned 1 exit status
make: *** [Makefile:28: bin/slice2cpp] Error 1
~~~
Do you know that you can download the CI failure logs yourself, via the publised artifacts in Azure Pipelines?
And I wouldn't run builds as root user on Linux on my local system.

2022-04-18 04:37 UTC, bold84 commented
> > What distribution are these linux builds running on?
> 
> It shouldn't matter.
> 
> ```
> /usr/bin/ld: cannot find -lmcpp
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:28: bin/slice2cpp] Error 1
> ```
> 
> Do you know that you can download the CI failure logs yourself, via the publised artifacts in Azure Pipelines? And I wouldn't run builds as root user on Linux on my local system.

Thank you. Yep, I know bout the failure logs. Unfortunately they are only available after all builds are done.

Thank you for the hint about running the build as root. It's a Docker container :-P

2022-04-18 04:42 UTC, bold84 commented
Well, the linux build was fine before. But something has changed and caused it to fail. There is another PR, that fixes the mcpp library name issue. I guess I have to wait until it's merged.

2022-04-20 05:41 UTC, bold84 commented
> @bold84 , If this pr is ready for review please let me know, thanks!

It’s ready for review.

2022-04-20 07:48 UTC, JonLiu1993 requested changes

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/chromium-base/vcpkg.json
>    "port-version": 3,
```suggestion
  "port-version": 4,
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/crashpad/portfile.cmake
> +file(WRITE "${SOURCE_PATH}/.gn" ${GN_FILE_CONTENT})
```suggestion
vcpkg_replace_string("${SOURCE_PATH}/.gn" "script_executable = \"python3\"" "script_executable = \"${PYTHON3}\"")
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/crashpad/vcpkg.json
>    "port-version": 2,
```suggestion
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/skia/fontconfig.gn
> + }
```suggestion
 }
 
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/skia/portfile.cmake
> +file(WRITE "${SOURCE_PATH}/.gn" ${GN_FILE_CONTENT})
```suggestion
vcpkg_replace_string("${SOURCE_PATH}/.gn" "script_executable = \"python3\"" "script_executable = \"${PYTHON3}\"")
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/skia/portfile.cmake
> +file(WRITE "${SOURCE_PATH}/gn/toolchain/BUILD.gn" ${GN_FILE_CONTENT})
```suggestion
vcpkg_replace_string("${SOURCE_PATH}/gn/toolchain/BUILD.gn" "command = \"$shell python" "command = \"$shell '${PYTHON3}'")
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/skia/vcpkg.json
> +  "port-version": 10,
```suggestion
```

2022-04-20 07:48 UTC, JonLiu1993 commented on ports/v8/vcpkg.json
>    "port-version": 3,
```suggestion
  "port-version": 4,
```

2022-04-20 07:48 UTC, JonLiu1993 commented on scripts/ci.baseline.txt
> +skia:x86-windows=fail # skia doesn't support x86 builds with local MSVC installations
if this port doesn't support x86-windows triplets, please add supports keyword in vcpkg.json instead of modify baseline.

2022-04-20 07:48 UTC, JonLiu1993 commented on versions/s-/skia.json
> -      "version-date": "2020-05-18",
We should keep the history git-tree not change and add the new  "git-tree", please revert the history "git-tree" and only add a new one

2022-04-20 07:48 UTC, JonLiu1993 commented on versions/s-/skia.json
> +      "version-date": "2022-04-10",
```suggestion

```

2022-04-20 07:48 UTC, JonLiu1993 commented on versions/s-/skia.json
> +      "port-version": 10
please revert the history "git-tree" and only add this

2022-04-20 07:48 UTC, JonLiu1993 commented on versions/z-/zeroc-ice.json
> -      "git-tree": "f32e4c338e25d36018095348e632c794b13fc513",
same as above , We should keep the history git-tree not change and add the new "git-tree", please revert the history "git-tree" and only add a new one

2022-04-20 07:54 UTC, bold84 commented on ports/crashpad/portfile.cmake
> +file(WRITE "${SOURCE_PATH}/.gn" ${GN_FILE_CONTENT})
Oh, I didn't know that function. Cool!

2022-04-20 07:58 UTC, bold84 commented on versions/z-/zeroc-ice.json
> -      "git-tree": "f32e4c338e25d36018095348e632c794b13fc513",
I don't fully understand what exactly should be done and why. Please elaborate, so I can avoid this problem in the future.

2022-04-20 08:18 UTC, bold84 commented on versions/z-/zeroc-ice.json
> -      "git-tree": "f32e4c338e25d36018095348e632c794b13fc513",
Nevermind... I think I got it... port-version should be 9 though, if I understand correctly.

2022-04-20 09:05 UTC, bold84 commented
@JonLiu1993 Okay... I see now how much I f...ed up the versioning / git-tree. 
I think I have corrected everything to the values they should have. Please have a look.

2022-04-20 09:32 UTC, JonLiu1993 submitted a review, later dismissed

2022-04-20 09:32 UTC, JonLiu1993 commented on ports/crashpad/vcpkg.json
> +  "port-version": 3,
```suggestion
```

2022-04-20 09:32 UTC, JonLiu1993 commented on ports/skia/vcpkg.json
>    "port-version": 9,
```suggestion
```

2022-04-20 09:32 UTC, JonLiu1993 commented on versions/s-/skia.json
>      },
```suggestion
    {
      "git-tree": "cdf8cda1612a4770f3a01e35ae5da93654abc17d",
      "version-date": "2020-05-18",
      "port-version": 9
    },
```

2022-04-20 09:40 UTC, bold84 commented on ports/crashpad/vcpkg.json
> +  "port-version": 3,
Why is port-version removed?

2022-04-20 09:43 UTC, bold84 commented on versions/s-/skia.json
>      },
What am I understanding wrong?
The last change to Skia that was merged was two months ago; port-version: 8

From what I can understand, the next version should represent the changes of this PR and therefore be port-version: 9

What am I getting wrong?

2022-04-20 10:09 UTC, JonLiu1993 commented on ports/crashpad/vcpkg.json
> +  "port-version": 3,
Because when we update the port , we should remove the port-version, you can refer to [this ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-port-version-field-in-the-manifest-file-of-any-modified-ports)

2022-04-20 10:11 UTC, JonLiu1993 commented on versions/s-/skia.json
>      },
Currently, the skia in vcpkg port-version is port-version: 9, [this ](https://github.com/microsoft/vcpkg/commit/99346bb6926e85d93e4aad330bf28cce4a18051b)is the last commit

2022-04-20 10:38 UTC, bold84 commented on versions/s-/skia.json
>      },
Ops… I see 👍

2022-04-20 10:42 UTC, bold84 commented on ports/crashpad/vcpkg.json
> +  "port-version": 3,
Thank you!! Now, understand.

2022-04-20 11:15 UTC, bold84 commented
<img width="607" alt="Screen Shot 2022-04-20 at 18 15 17" src="https://user-images.githubusercontent.com/21118257/164218924-76a9d099-4096-4e73-93f7-4ffea97fbd13.png">

https://github.com/microsoft/vcpkg/actions/runs/2195232664

What's wrong?

2022-04-20 11:20 UTC, JackBoosY commented
```
Error: Unhandled error: HttpError: Unknown error: {"count":11,"value":"Uri expired"}
```
@BillyONeal  Do you know why?

2022-04-20 15:32 UTC, bold84 commented
/azp run

2022-04-20 16:03 UTC, JackBoosY commented
Will rerun the test after other tests finished.

2022-04-21 07:53 UTC, JackBoosY commented
Depends on https://github.com/microsoft/vcpkg/pull/24267.

2022-04-21 08:14 UTC, bold84 commented
I have learned a lot from this PR 🤓. Thank you for your review and recommendations.

Besides other things, next time I'll plan changes to core files a bit better.

2022-04-21 16:24 UTC, JackBoosY commented
/azp run

2022-04-22 02:14 UTC, bold84 commented
Hmm… There are several things I could improve. But I’ll create new PRs for them.

2022-04-22 02:20 UTC, JackBoosY requested changes

2022-04-22 02:20 UTC, JackBoosY commented on ports/skia/portfile.cmake
> +function(checkout_in_path_with_patch PATH URL REF PATCH)
Defined this function but not use it?

2022-04-22 02:20 UTC, JackBoosY commented on ports/skia/skiaConfig.cmake.in
>  add_library(skia INTERFACE)
Did you test the usage?

2022-04-22 06:11 UTC, bold84 commented on ports/skia/portfile.cmake
> +function(checkout_in_path_with_patch PATH URL REF PATCH)
It was part of an unfinished PR on here, in which one of the dependencies required a patch. With the newer ref I used, that patch was not required anymore.

I’m aware this function is currently not used, but it might be used in the future. So, I felt it doesn’t hurt to leave it there.

2022-04-22 06:16 UTC, bold84 commented on ports/skia/skiaConfig.cmake.in
>  add_library(skia INTERFACE)
No, I just took the changes from the previously mentioned PR. 
I know that this file of the previous port version did not work (tested), so it couldn’t get worse than that. I will improve this file, but I prefer this to be in a separate PR, as one round trip (build) of this PR takes several hours due to the involvement of core files.

2022-04-22 08:05 UTC, JackBoosY approved these changes

2022-04-22 16:50 UTC, strega-nil-ms commented
rebased and fixed spaces; gonna wait for green one last time :)

2022-04-23 11:26 UTC, Thomas1664 commented on ports/crashpad/vcpkg.json
> +  "version-date": "2022-04-16",
```suggestion
  "version-date": "2022-04-12",
```
Please use the actual commit date

2022-04-23 11:43 UTC, dg0yt commented on ports/crashpad/vcpkg.json
> +  "version-date": "2022-04-16",
> Please use the actual commit date

Wait. I'm not convinced this is the de-facto policy.
(I don't see it written, except for [old hints about `version-string`](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#version-string):
`we use the date that the commit was accessed by you`)

2022-04-23 11:55 UTC, Thomas1664 commented on ports/crashpad/vcpkg.json
> +  "version-date": "2022-04-16",
I saw several reviews where it was asked to use commit date as version-date. However, after some research I saw both policies.

2022-04-23 11:55 UTC, Thomas1664 approved these changes

2022-04-25 22:39 UTC, merged

2022-04-25 22:39 UTC, BillyONeal commented
> rebased and fixed spaces; gonna wait for green one last time :)

I didn't review; I just merged green build based on this :)

2022-06-03 12:08 UTC, njakob commented on ports/crashpad/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/${PORT}/build")
I'm currently running into the following error while using the latest version of crashpad (`2022-04-16`) on Windows. Can this line be responsible for the missing files and is this an intended behavior?

> Error: %REDACTED%\build\windows-release\vcpkg_installed\x64-windows\include\crashpad\base/files/file_path.h(110): fatal error C1083: Cannot open include file: 'build/build_config.h': No such file or directory

I'm not sure if it's related to https://github.com/microsoft/vcpkg/issues/24510 or if it deserves its own issue?

CC @bold84

2022-06-04 10:42 UTC, njakob commented on ports/crashpad/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/${PORT}/build")
I created a new issue regarding this problem https://github.com/microsoft/vcpkg/issues/25066