[dstorage] - Add port for Microsoft.Direct3D.DirectStorage NuGet
microsoft/vcpkg pull request #24063
Opened 2022-04-09 22:43 UTC by walbourn

This adds a new port for the [DirectStorage](https://aka.ms/directstorage/) API using the [NuGet package](https://www.nuget.org/packages/Microsoft.Direct3D.DirectStorage/1.0.0).

2022-04-09 22:49 UTC, walbourn commented
Validated all supported triplets:

```
vcpkg install dstorage:x86-windows
vcpkg install dstorage:x64-windows
vcpkg install dstorage:arm-windows
vcpkg install dstorage:arm64-windows
```

2022-04-10 00:36 UTC, Osyotr commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
I think `!static` here is redundant because of `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)`. IIRC, the former will produce error when trying to build `dstorage` with static triplet while the latter will warn and build dynamic library.

2022-04-11 03:50 UTC, walbourn commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
I believe you have to have it in the vcpkg so it doesn't break the CI build. Last I heard, it was driven by that metadata.

2022-04-11 07:53 UTC, LilyWangLL approved these changes

2022-04-11 10:44 UTC, Osyotr commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
Using similar port `dbghelp` as example:
x86-windows:
no errors or messages
x86-windows-static:
`Refusing to build unexpected dynamic library against the static CRT. If this is desired, please configure your triplet to directly request this configuration.`
x86-windows-static-md:
`-- Note: dbghelp only supports dynamic library linkage. Building dynamic library.`

2022-04-11 15:38 UTC, strega-nil-ms requested changes
Since this is not an official config.cmake, it needs to be in the `unofficial` namespace.

Also, probably should lowercase the `Config.cmake.in` name.

2022-04-11 15:38 UTC, strega-nil-ms commented on ports/dstorage/Config.cmake.in
> +      INTERFACE_INCLUDE_DIRECTORIES        "${_dstorage_root}/include/dstorage"
This should probably be 
```suggestion
      INTERFACE_INCLUDE_DIRECTORIES        "${_dstorage_root}/include"
```

2022-04-11 19:11 UTC, walbourn commented on ports/dstorage/Config.cmake.in
> +      INTERFACE_INCLUDE_DIRECTORIES        "${_dstorage_root}/include/dstorage"
This is the 'official' vcpkg port. I'm working with the owner of the DirectStorage NuGet package, and they are on-board with this vcpkg port. There is no native CMake support otherwise.

I used the same casing as I see in many other ports. Since this is a Windows only technology, it's not going to get used on Linux or other case-sensitive filesystems.

I'll move the includes up a folder level...

2022-04-11 19:14 UTC, walbourn commented on ports/dstorage/Config.cmake.in
> +   add_library(Microsoft::DirectStorage SHARED IMPORTED)
This is the 'official' vcpkg port. I'm working with the owner of the DirectStorage NuGet package, and they are on-board with this vcpkg port. There is no native CMake support otherwise.

2022-04-11 19:32 UTC, walbourn commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
@BillyONeal, @JonLiu1993 - Can any of you comment on if the use of ``!static`` in the vcpkg.json supports expression is best-practice for a port that has `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` or not?

Thanks!

2022-04-11 19:59 UTC, coopp commented
I am the owner of the Microsoft.Direct3D.DirectStorage nuget package and I agree that this is an official port.

2022-04-11 22:31 UTC, strega-nil commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
it is best practice to not have `!static`, imo; however, I'd like opinions from @ras0219

2022-04-11 22:33 UTC, strega-nil commented on ports/dstorage/Config.cmake.in
> +      INTERFACE_INCLUDE_DIRECTORIES        "${_dstorage_root}/include/dstorage"
it's mostly just confusing that you're going from `Config.cmake.in` -> `dstorage-config.cmake`; it should probably be called `dstorage-config.cmake.in`

2022-04-11 22:47 UTC, strega-nil commented
@coopp alright; what is your thought on `Microsoft::DirectStorage`? I would personally expect something like `Direct3D::DirectStorage` (project :: library)

2022-04-11 22:48 UTC, strega-nil commented
I also think the following changes should be made:

```patch
From 6dbded87ea8f0eb38b9bfda2605f26998abd7726 Mon Sep 17 00:00:00 2001
From: nicole mazzuca <mazzucan@outlook.com>
Date: Mon, 11 Apr 2022 15:48:11 -0700
Subject: [PATCH] minor CR changes

---
 .../dstorage/{Config.cmake.in => dstorage-config.cmake.in}  | 0
 ports/dstorage/portfile.cmake                               | 6 +++---
 2 files changed, 3 insertions(+), 3 deletions(-)
 rename ports/dstorage/{Config.cmake.in => dstorage-config.cmake.in} (100%)

diff --git a/ports/dstorage/Config.cmake.in b/ports/dstorage/dstorage-config.cmake.in
similarity index 100%
rename from ports/dstorage/Config.cmake.in
rename to ports/dstorage/dstorage-config.cmake.in
diff --git a/ports/dstorage/portfile.cmake b/ports/dstorage/portfile.cmake
index e74aaaad6..b8e4ff394 100644
--- a/ports/dstorage/portfile.cmake
+++ b/ports/dstorage/portfile.cmake
@@ -12,8 +12,8 @@ vcpkg_extract_source_archive_ex(
     NO_REMOVE_ONE_LEVEL
 )
 
-file(GLOB HEADER_FILES "${PACKAGE_PATH}/include/DirectStorage/*.h")
-file(INSTALL ${HEADER_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/include")
+file(INSTALL "${PACKAGE_PATH}/include/DirectStorage"
+    DESTINATION "${CURRENT_PACKAGES_DIR}/include")
 
 file(INSTALL "${PACKAGE_PATH}/bin/${VCPKG_TARGET_ARCHITECTURE}/dstorage.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
 
@@ -25,4 +25,4 @@ file(COPY "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/lib" DESTINATIO
 
 file(INSTALL "${PACKAGE_PATH}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
 
-configure_file("${CMAKE_CURRENT_LIST_DIR}/Config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/${PORT}/${PORT}-config.cmake" COPYONLY)
+configure_file("${CMAKE_CURRENT_LIST_DIR}/dstorage-config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/${PORT}/${PORT}-config.cmake" COPYONLY)
-- 
2.32.0 (Apple Git-132)
```

2022-04-11 22:51 UTC, walbourn commented
> @coopp alright; what is your thought on `Microsoft::DirectStorage`? I would personally expect something like `Direct3D::DirectStorage` (project :: library)

I believe the reason the NuGet namespace is ``Microsoft.Direct3D.*`` is because how nuget.org manages their namespace ownership within the company. There's not going to be a conflict with ANOTHER Microsoft technology called "DirectStorage", and I believe it's a lot clearer this is a "Microsoft" technology with the current namespace.

2022-04-11 23:08 UTC, walbourn commented
> I also think the following changes should be made:

I didn't use exactly those diffs, but I believe my latest revision should resolve this. Thanks!

2022-04-11 23:28 UTC, strega-nil commented
@walbourn I agree that it's unlikely another MS technology is going to compete with the name `DirectStorage`, in general CMake targets are written `project :: package`, not `company :: package` - for example, `abseil` is not `google::abseil`, it's `absl::blah`.

2022-04-11 23:30 UTC, strega-nil commented on ports/dstorage/portfile.cmake
> +file(INSTALL "${PACKAGE_PATH}/Include/DirectStorage/dstorageerr.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
The issue here is installing `dstorage.h` and `dstorageerr.h` into the top level - I would really prefer if they were installed in `DirectStorage/dstorage.h` and `DirectStorage/dstorageerr.h`, same as in the upstream sources.

2022-04-11 23:30 UTC, walbourn commented
> @walbourn I agree that it's unlikely another MS technology is going to compete with the name `DirectStorage`, in general CMake targets are written `project :: package`, not `company :: package` - for example, `abseil` is not `google::abseil`, it's `absl::blah`.

We already have ``Microsoft::directxtk``, ``Microsoft::directxmath``, etc. Renaming ALL these other ports to ``Direct3D::`` seems far more disruptive than calling this one ``Microsoft::``.

2022-04-11 23:31 UTC, walbourn commented on ports/dstorage/portfile.cmake
> +file(INSTALL "${PACKAGE_PATH}/Include/DirectStorage/dstorageerr.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
This is going to be updated in the next release of the NuGet to move it up one level.

2022-04-11 23:39 UTC, strega-nil commented
alright... I really don't like that that's the way we've done that there, but I'll merge once you've done the `install` into the correct include directory. Thanks for contributing!

2022-04-11 23:40 UTC, walbourn commented
> alright... I really don't like that that's the way we've done that there, but I'll merge once you've done the `install` into the correct include directory. Thanks for contributing!

Won't I also need to change the .in to match the new lower include folder?

2022-04-11 23:45 UTC, ras0219-msft commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
The correct expression is `!(static & staticcrt)` -- if the user requests `static` but with the dynamic crt, this port will successfully build a DLL linked against the dynamic CRT which is valid according to vcpkg policy.

2022-04-11 23:54 UTC, strega-nil commented
@walbourn the idea is that someone links to `Microsoft::DirectStorage`, and then includes one of those headers via `#include <DirectStorage/dstorage.h>` rather than `#include <dstorage.h>`

2022-04-12 00:08 UTC, walbourn commented
> @walbourn the idea is that someone links to `Microsoft::DirectStorage`, and then includes one of those headers via `#include <DirectStorage/dstorage.h>` rather than `#include <dstorage.h>`; if you really want to make it possible to `#include <dstorage.h>`, you can add both as include directories so that both are allowed (at least, that's my opinion)

Clients of the nuget package use ``#include <dstorage.h>``. They can't use anything else.

2022-04-12 00:17 UTC, walbourn commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
> The correct expression is `!(static & staticcrt)` -- if the user requests `static` but with the dynamic crt, this port will successfully build a DLL linked against the dynamic CRT which is valid according to vcpkg policy.

What triplet builds static libraries but uses the dynamic CRT? The ``x64-windows-static`` triplet uses the static CRT.

2022-04-12 00:28 UTC, strega-nil commented
mhh, alright; then, merging as is. Thanks for talking it out with me!

2022-04-12 00:28 UTC, merged

2022-04-12 00:34 UTC, walbourn commented
Thanks!

I'm happy to revisit the taxonomy of namespaces for my Microsoft org hosted projects *directxtk*, *directxtk12*, *directxtex*, *directxmesh*, *uvatlas*, and *directxmath* if ``Microsoft::`` is inappropriate. Maybe I could use ``DirectX::``?

I'm not sure there is any better namespace than ``Microsoft::``, however, for *xaudio2redist*, *dxsdk-d3dx*, and *dstorage* since they are just raw projections of nuget packages for closed-source binaries.

2022-04-12 07:08 UTC, walbourn commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
I'll update the vcpkg.json with this next time I rev this port--should be reasonably soon.

I'd still like to know what triplet I can use to test this senario: static library + dynamiccrt.

2022-04-12 09:26 UTC, Osyotr commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
> What triplet builds static libraries but uses the dynamic CRT

`x86-windows-static-md` :)

2022-04-12 19:05 UTC, walbourn commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
@Osyotr  Thanks!  I'll review all my ports and do a port revision as needed.

2022-04-12 19:48 UTC, walbourn commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !static"
@ras0219-msft, @Osyotr see https://github.com/microsoft/vcpkg/pull/24104

2022-04-13 17:55 UTC, strega-nil-ms commented
@walbourn for that, I'd personally say something like `xaudio::xaudio`. In order to link `fmt`, for example, you'd link `fmt::fmt`.

Using `Microsoft::` as a namespace is _fine_, it's just not standard practice in CMake land.