[dstorage, dxsdk-d3dx, xaudio2redist] ports updated to support static-md triplets
microsoft/vcpkg pull request #24104
Opened 2022-04-12 19:46 UTC by walbourn

Per feedback in [24063](https://github.com/microsoft/vcpkg/pull/24063), I've updated the ``vcpkg.json`` supports statement to change the expression ``!static`` to ``!(static & staticcrt)``.

2022-04-12 19:47 UTC, walbourn commented
Validated the following triplets:

```
vcpkg install dstorage:x64-windows
vcpkg install dstorage:x86-windows
vcpkg install dstorage:x64-windows-static-md
vcpkg install dstorage:x86-windows-static-md

vcpkg install dxsdk-d3dx:x64-windows
vcpkg install dxsdk-d3dx:x86-windows
vcpkg install dxsdk-d3dx:x64-windows-static-md
vcpkg install dxsdk-d3dx:x86-windows-static-md

vcpkg install xaudio2redist:x64-windows
vcpkg install xaudio2redist:x86-windows
vcpkg install xaudio2redist:x64-windows-static-md
vcpkg install xaudio2redist:x86-windows-static-md

vcpkg install directxtk[xaudio2redist]:x64-windows --recurse
vcpkg install directxtk[xaudio2redist]:x86-windows --recurse
vcpkg install directxtk[xaudio2redist]:x64-windows-static-md --recurse
vcpkg install directxtk[xaudio2redist]:x86-windows-static-md --recurse
```

Also confirmed directxmath, directxtk, directxtk12, directxtex, directxmesh, and uvatlas all support these triplets:

```
arm64-windows-static-md
x64-windows-static-md
x86-windows-static-md
```

2022-04-13 03:07 UTC, FrankXie05 approved these changes

2022-04-13 17:53 UTC, strega-nil-ms requested changes
I don't believe these support a static CRT during a dynamic build either; there's no reason to mention `static` here (I believe Robert was incorrect in the original PR comments)

2022-04-13 17:53 UTC, strega-nil-ms commented on ports/dstorage/vcpkg.json
> +  "supports": "windows & !uwp & !(static & staticcrt)"
```suggestion
  "supports": "windows & !uwp & !staticcrt"
```

2022-04-13 18:08 UTC, strega-nil-ms approved these changes

2022-04-13 18:23 UTC, strega-nil-ms commented
Thanks!

2022-04-13 18:23 UTC, merged