Update simage port for version 1.8.2
microsoft/vcpkg pull request #24125
Opened 2022-04-13 15:18 UTC by ChrisSchulte

Updated the port of simage from 1.8.1 to 1.8.2

- #### What does your PR fix?
  Fixes #23915

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <linux, windows>, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes, result is empty.

2022-04-13 16:32 UTC, dg0yt requested changes

2022-04-13 16:32 UTC, dg0yt commented on ports/simage/requies-all-dependencies.patch
> -+  find_package(GdiPlus REQUIRED)
This single line was enough...

2022-04-13 16:32 UTC, dg0yt commented on ports/simage/requies-all-dependencies.patch
> ++  endif()
... instead of these three lines.

2022-04-13 16:32 UTC, dg0yt commented on ports/simage/requies-all-dependencies.patch
> -+  find_package(Vfw REQUIRED)
And same here.

Its common practice in vcpgk,  and it allows error reporting from `find_package`.

2022-04-13 16:58 UTC, ChrisSchulte commented on ports/simage/requies-all-dependencies.patch
> -+  find_package(Vfw REQUIRED)
Sorry but as stated on the PR on VCPKG and simage side, this single line does not work if more than one version of the Windows SDK (typically on Windows 10 the version 8.1 and multiple 10 versions) is installed. Your suggestion was the previous behaviour that has been corrected on simage side. This is the reason a compile test is used instead of the find_package version as done before in version 1.81.

2022-04-14 04:57 UTC, dg0yt commented on ports/simage/requies-all-dependencies.patch
> -+  find_package(Vfw REQUIRED)
Sorry, I misread the GH view. I didn't realize that they moved away from a `find_package` approach. 
(And I don't think it is a good move - in fact it is the reason why we still need patching, instead of just using [`CMAKE_REQUIRE_FIND_PACKAGE_<PackageName>`](https://cmake.org/cmake/help/latest/variable/CMAKE_REQUIRE_FIND_PACKAGE_PackageName.html#variable:CMAKE_REQUIRE_FIND_PACKAGE_%3CPackageName%3E))

2022-04-25 09:31 UTC, ChrisSchulte commented
I've added a null license entry as the port comes with a proper license file.

2022-04-25 13:36 UTC, ChrisSchulte commented
Hello @FrankXie05,
I'm sorry but I'm a little bit lost with the port versioning. If I understand correctly the versioning [doc](https://vcpkg.readthedocs.io/en/latest/specifications/versioning/#2-specifying-package-versions) I should have moved to port version 0 as I moved from simage version 1.8.1 to 1.8.2, am I assuming correctly ? If yes, how should I proceed to correct the behaviour ? Should I remove port version 5 and 6 and push version 0 in simage.json ?
Thank you for your time and best regards.

2022-04-26 02:34 UTC, FrankXie05 commented
@ChrisSchulte 
If you're referring to port-version in manifest files, you increment it if you modified the port but didn't update the version. If you update a port, you remove port-version. This resets it to 0. git-tree in the version database is updated by running vcpkg x-add-version <port name>. If you already ran vcpkg x-add-version <port name> but modified the port again in the same PR, you append --overwrite-version. The easiest way to get SHA512 is to set it to 0 and look at the error message when you try to install that port (vcpkg install <port name>). There you will find something like expected hash.

2022-04-27 10:04 UTC, FrankXie05 approved these changes

2022-04-28 01:55 UTC, BillyONeal commented
Thanks for the update!

2022-04-28 01:55 UTC, merged