[blaze] fix mac arm build
microsoft/vcpkg pull request #24235
Opened 2022-04-18 22:45 UTC by autoantwort

2022-04-19 01:01 UTC, JackBoosY requested changes

2022-04-19 01:01 UTC, JackBoosY commented on ports/blaze/fix-osx-cache-sizes.patch
> ++      if (flag OR NOT "$tmp")
I'm not sure about this part, can you please make a PR to the upstream first?

Thanks.

2022-04-19 09:09 UTC, autoantwort commented on ports/blaze/fix-osx-cache-sizes.patch
> ++      if (flag OR NOT "$tmp")
I have created a issue: https://bitbucket.org/blaze-lib/blaze/issues/431/cmake-configuration-failure

It seems that the problem is that the result is empty on M1 macs, but this is not interpreted as error. So do it and check the next key

2022-06-06 10:36 UTC, autoantwort commented on ports/blaze/fix-osx-cache-sizes.patch
> ++      if (flag OR NOT "$tmp")
I updated the port to the latest release because that also fixed the error.

2022-06-07 00:58 UTC, JackBoosY commented on versions/b-/blaze.json
> +    },
```suggestion
```

2022-06-07 00:59 UTC, JackBoosY approved these changes

2022-06-08 00:28 UTC, ras0219-msft requested changes
LGTM after the small tweak. Thanks as always!

2022-06-08 00:28 UTC, ras0219-msft commented on ports/blaze/portfile.cmake
> +vcpkg_cmake_config_fixup()
I think this still needs to be
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH share/blaze/cmake)
```
otherwise the files are produced into `share/blaze/cmake/blaze-config.cmake`.

2022-06-10 02:25 UTC, JackBoosY approved these changes

2022-06-10 17:25 UTC, merged