[pthreads4w] update for single config builds, improve downstream compatibility
microsoft/vcpkg pull request #24308
Opened 2022-04-21 16:15 UTC by cenit

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-04-21 17:58 UTC, dg0yt commented
:+1: for this PR. I have a similar but incomplete draft somewhere between 100 branches...

What I would like to see changed is: 
- Only one, properly implemented package name. No forwarding wrapper under other names like `pthreads`.
- No extra variables needed by some ports, but patches to these ports, or setting its find module's input variables from a `CMAKE_PROJECT_INCLUDE`. 
  Otherwise the "convenient" use of the alternative names proliferates and increases the number of inverse dependencies.

This seems to be the contrary of what you call "downstream compatibility", but IMO this compatibility mixes too many concerns.

2022-04-21 20:15 UTC, cenit commented
the problem is backwards compatibility

this port was called (upstream) once pthreads (hence the port name here), then became Pthreads_windows, then PThreads4W.

I don't like to break downstream projects if they depended on the original names (not just ports here, world is much bigger than registry here), and also the wrapper was exposing many different names.
I just made all of them working, removed cache variables as you taught me, ensuring consistency between all of them

2022-04-21 21:13 UTC, Neumann-A commented
> Note 1: the incompatibility is really between EH implementations
of the different compilers. It should be possible to use the
standard C version from either compiler with C++ applications
built with a different compiler. If you use an EH version of
the library, then you must use the same compiler for the
application. This is another complication and dependency that
can be avoided by using only the standard C library version.

> The default version uses setjmp/longjmp

> If you use either pthreadVCE[2] or pthreadGCE[2]: 
If your application contains catch(...) blocks in your POSIX
threads then you will need to replace the "catch(...)" with the macro
"__PtW32Catch", eg.

> It is recommended that you let pthread.h use it's default __PTW32_CLEANUP_C
for both library and application builds. That is, don't define any of
the above, and then link with pthreadVC.lib (MSVC or MSVC++)

> The reason is explained below, but
another reason is that the prebuilt pthreadVCE.dll is currently broken.
Versions built with MSVC++ later than version 6 may not be broken, but I
can't verify this yet.

> Now you may be asking: then why have you kept the EH versions of
the library?
There are a couple of reasons:
- there is division amongst the experts and so the code may
  be needed in the future. Yes, it's in the repository and we
  can get it out anytime in the future, but it would be difficult
  to find.
- pthreads-win32 is one of the few implementations, and possibly
  the only freely available one, that has EH versions. It may be
  useful to people who want to play with or study application
  behaviour under these conditions.

as such vcpkg should only provide the default version without exception handling (pthreadVC). All other versions are irrelevant in the context of vcpkg.

2022-04-22 03:15 UTC, dg0yt commented
> the problem is backwards compatibility
> 
> this port was called (upstream) once pthreads (hence the port name here), then became Pthreads_windows, then PThreads4W.
> 
> I don't like to break downstream projects if they depended on the original names (not just ports here, world is much bigger than registry here), and also the wrapper was exposing many different names. I just made all of them working, removed cache variables as you taught me, ensuring consistency between all of them

External usage of the broken interface, okay. I would still prefer to at least incrementally remove inconsistent parts of the interface.

2022-04-22 03:21 UTC, dg0yt requested changes

2022-04-22 03:21 UTC, dg0yt commented on ports/pthreads/portfile.cmake
> -file(COPY ${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/pthread)
Here the PR removes the pthread package name (case-insensitive, wrongly implemented via the wrapper)...

2022-04-22 03:21 UTC, dg0yt commented on ports/pthreads/portfile.cmake
> +file(COPY "${CMAKE_CURRENT_LIST_DIR}/PThreads4WConfig.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/PThreads4W")
... and here it introduces the `PThreads4W` package name (case-sensitive cmake config name). What I ask for is that this *new* config doesn't set any of the legacy variables (because they are not yet technical debt of the new package name). The legacy variable can be derived in the forwarding wrappers, or better: forwarding configs.

2022-04-22 03:21 UTC, dg0yt commented on ports/pthreads/vcpkg-cmake-wrapper.cmake
> +include(FindPackageHandleStandardArgs)
The functions from this module seem unused in this minimal wrapper.

2022-04-22 06:35 UTC, Neumann-A commented on ports/pthreads/portfile.cmake
> +  file(RENAME "${CURRENT_PACKAGES_DIR}/lib/libpthreadVSE3.lib" "${CURRENT_PACKAGES_DIR}/lib/pthreadVSE3.lib")
why the rename?

2022-04-22 06:38 UTC, cenit commented on ports/pthreads/portfile.cmake
> +  file(RENAME "${CURRENT_PACKAGES_DIR}/lib/libpthreadVSE3.lib" "${CURRENT_PACKAGES_DIR}/lib/pthreadVSE3.lib")
the lines are just moved from the original position, renaming was already in place and kept as before

2022-04-22 06:39 UTC, cenit commented on ports/pthreads/portfile.cmake
> +file(COPY "${CMAKE_CURRENT_LIST_DIR}/PThreads4WConfig.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/PThreads4W")
i tried to do your suggestion in recent commits, is it better now?

2022-04-22 06:44 UTC, cenit commented on ports/pthreads/portfile.cmake
> +  file(RENAME "${CURRENT_PACKAGES_DIR}/lib/libpthreadVSE3.lib" "${CURRENT_PACKAGES_DIR}/lib/pthreadVSE3.lib")
maybe for the original vcpkg stance about libraries being identical between shared/static builds?

2022-04-22 07:26 UTC, dg0yt commented on ports/pthreads/portfile.cmake
> +file(COPY "${CMAKE_CURRENT_LIST_DIR}/PThreads4WConfig.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/PThreads4W")
The split looks really good now. Even if it inspires more refactorings, I don't want to add any additional wishes to this PR.
Thanks a lot!

2022-04-26 12:40 UTC, raghavthind2005 submitted a review, later dismissed

2022-04-29 06:39 UTC, JackBoosY commented
Are there any objections in this PR now?

2022-04-29 07:20 UTC, dg0yt submitted a review, later dismissed

2022-04-29 08:08 UTC, JackBoosY requested changes

2022-04-29 14:49 UTC, cenit commented on ports/pthreads/portfile.cmake
> +    vcpkg_execute_required_process(
it looks like a big task. Is it necessary in this PR?

2022-05-05 02:20 UTC, JackBoosY approved these changes, later dismissed

2022-05-05 17:52 UTC, BillyONeal commented on ports/pthreads/vcpkg.json
>    "description": "pthreads for windows",
```suggestion
  "description": "Meta-package that provides PThreads4W on Windows, or assumes presence of system pthreads on POSIX systems.",
```

2022-05-05 17:52 UTC, BillyONeal commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
Something seems messed up with this usage, since it won't be correct on non-Windows? It seems like if downstream customers have to name the "4win" part specifically then the port should have `"supports": "windows"`?

2022-05-05 17:54 UTC, cenit commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
you're right, i will put usage installation behind a vcpkg_target_windows check

2022-06-25 09:51 UTC, cenit commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
sorry, just noticed that  the port begins with

```
if(NOT VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_MINGW)
  set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
  return()
endif()
```

this means that if you are on a *nix platform no usage is involved (it was not even installed before the latest commit) and so no broken instructions have ever been distributed

2022-06-27 07:58 UTC, JackBoosY commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
@BillyONeal See https://github.com/microsoft/vcpkg/pull/24308/files#diff-5965a1d51ff0c8398873c1ec5b51edd25ac4f84b97312f3a8c329ad5cae88a7fR1-R4

2022-06-27 13:30 UTC, dg0yt commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
FTR non-Windows users will normally have an implementation which is found via `find_package(Threads)`.

2022-06-27 17:58 UTC, BillyONeal commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
> sorry, just noticed that the port begins with
> 
> ```
> if(NOT VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_MINGW)
>   set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
>   return()
> endif()
> ```
> 
> this means that if you are on a *nix platform no usage is involved (it was not even installed before the latest commit) and so no broken instructions have ever been distributed

Hmmm should that be `if(NOT (VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_MINGW))` or `if(NOT VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)` ?

2022-06-27 18:00 UTC, BillyONeal approved these changes

2022-06-27 18:32 UTC, dg0yt commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
Empty for non-Windows targets. Empty for MinGW windows targets. The condition is okay.

There are MinGW toolchains with Posix threads and MinGW toolchains with win32 threads. Those with Posix threads don't need this port. And those with win32 threads don't (or didn't) support C++11 multithreading. I guees that most MinGW users want Posix threads and C++11.

2022-06-27 18:39 UTC, BillyONeal commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
> Empty for MinGW windows targets.

Wait, really?! I thought MinGW targeted the native system rather compatibility layers.

2022-06-27 18:51 UTC, dg0yt commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
I guess it is getting more difficult here, and I don't know if I manage to tell entirely correct facts.

Assuming we mean mingw-w64 when we say mingw today, it comes with a "a wrapper implementation of pthreads, winpthreads, which tries to use more native system calls than the Pthreads4w project." 
https://en.wikipedia.org/wiki/Pthreads#POSIX_Threads_for_Windows
http://locklessinc.com/articles/pthreads_on_windows/

2022-06-27 18:53 UTC, BillyONeal commented on ports/pthreads/usage
> +    find_package(PThreads4W REQUIRED)
Huh, Today I Learned :)

2022-06-27 23:45 UTC, merged