[geos] Update, cleanup
microsoft/vcpkg pull request #24382
Opened 2022-04-24 17:27 UTC by dg0yt

- #### What does your PR fix?
  Updates GEOS to 3.10.2. Resolves #24380.
  Cleanup and dropping of the debug postfix for easier mainenance. (AFAICT all downstream ports use pkg-config or cmake config. osgearth has a patch which refers to the geos debug postfix, but the patched file is unused, and osgearth deserves a separate cleanup.)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-04-25 02:35 UTC, JackBoosY requested changes

2022-04-25 02:35 UTC, JackBoosY commented on ports/geos/portfile.cmake
> +set(EXTRA_OPTIONS)
```suggestion
set(EXTRA_OPTIONS "")
```

2022-04-25 02:35 UTC, JackBoosY commented on ports/geos/portfile.cmake
> -endif()
Is this not needed?

2022-04-25 03:56 UTC, dg0yt commented on ports/geos/portfile.cmake
> +set(EXTRA_OPTIONS)
Indeed, it was meant like this.

2022-04-25 03:58 UTC, dg0yt commented on ports/geos/portfile.cmake
> -endif()
The debug postfix is removed in this PR so it is no longer needed.
The `geos-config` fixup for release is still there, but no longer guarded by `VCPKG_BUILD_TYPE`. (Debug-only single-config is unsupported.)

2022-04-25 06:02 UTC, JackBoosY approved these changes

2022-04-26 00:17 UTC, merged

2022-04-26 00:17 UTC, BillyONeal commented
Thanks for the fixes!