[jansson] Update to 2.14
microsoft/vcpkg pull request #24411
Opened 2022-04-25 23:05 UTC by Jimmy-Hu

[jansson] Update to 2.14

**Describe the pull request**

- #### What does your PR fix? Update jansson package to 2.14
  
  https://github.com/akheron/jansson/releases/tag/v2.14

2022-04-25 23:33 UTC, BillyONeal commented
/azp run

2022-04-25 23:44 UTC, Jimmy-Hu commented
Not sure why it failing (`Version `2.14#2` was not found in versions file.`) in x86_windows

on my machine

```
vcpkg.exe install jansson
Computing installation plan...
The following packages will be built and installed:
    jansson[core]:x86-windows -> 2.14#2
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\jimmyhu\AppData\Local\vcpkg\archives in 587.5 us. Use --debug to see more details.
Starting package 1/1: jansson:x86-windows
Building package jansson[core]:x86-windows...
-- Downloading https://github.com/akheron/jansson/archive/684e18c927e89615c2d501737e90018f4930d6c5.tar.gz -> akheron-jansson-684e18c927e89615c2d501737e90018f4930d6c5.tar.gz...
-- Extracting source V:/downloads/akheron-jansson-684e18c927e89615c2d501737e90018f4930d6c5.tar.gz
-- Using source at V:/buildtrees/jansson/src/8f4930d6c5-d0383a6ce3.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: V:/packages/jansson_x86-windows/share/jansson/copyright
-- Fixing pkgconfig file: V:/packages/jansson_x86-windows/lib/pkgconfig/jansson.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at V:/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: V:/packages/jansson_x86-windows/debug/lib/pkgconfig/jansson.pc
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\jimmyhu\AppData\Local\vcpkg\archives\c9\c99fbe967b6b8fc71353603f8ab9a4971e557a8e09a3fb294d32eb96588adbc6.zip
Installing package jansson[core]:x86-windows...
Elapsed time for package jansson:x86-windows: 39.96 s

Total elapsed time: 42.56 s

The package jansson provides CMake targets:

    find_package(jansson CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jansson::jansson)


```

2022-04-26 00:25 UTC, JackBoosY approved these changes

2022-04-26 00:29 UTC, BillyONeal commented on ports/jansson/vcpkg.json
> +  "version-string": "2.14",
```suggestion
  "version": "2.14",
```
?

2022-04-26 00:46 UTC, JackBoosY requested changes

2022-04-26 00:46 UTC, JackBoosY commented on versions/j-/jansson.json
> +      "git-tree": "4f2760bb6ef390f3472b4789914024054fccaeb6",
```suggestion
      "git-tree": "13cb17992f4a9ef3eaba47a1449bb859e9009a03",
```

2022-04-26 00:56 UTC, JackBoosY commented on versions/j-/jansson.json
> +      "version-string": "2.14",
```suggestion
      "version": "2.14",
```

2022-04-26 00:56 UTC, JackBoosY approved these changes

2022-04-26 06:10 UTC, Thomas1664 requested changes
Please remove `port-version`

2022-04-26 06:10 UTC, Thomas1664 commented on ports/jansson/vcpkg.json
>    "description": "Jansson is a C library for encoding, decoding and manipulating JSON data",
```suggestion
  "version": "2.14",
  "description": "Jansson is a C library for encoding, decoding and manipulating JSON data",
```

2022-04-26 07:18 UTC, JackBoosY commented on versions/j-/jansson.json
> +      "port-version": 2
```suggestion
      "port-version": 0
```

2022-04-26 07:19 UTC, JackBoosY commented on versions/j-/jansson.json
> +      "port-version": 2
```suggestion
      "git-tree": "1a5c55feab368e4bfb40be993b9ea5a39fc82f51",
      "version": "2.14",
      "port-version": 0
```

2022-04-26 07:20 UTC, JackBoosY commented on versions/baseline.json
>        "port-version": 2
```suggestion
      "port-version": 0
```

2022-04-26 07:20 UTC, JackBoosY approved these changes

2022-04-26 12:34 UTC, raghavthind2005 approved these changes

2022-04-27 02:23 UTC, merged

2022-04-27 02:23 UTC, BillyONeal commented
Thanks for the update!