[qt5-base]: Fix build with "mysqlplugin" feature by linking to OpenSS…
microsoft/vcpkg pull request #24462
Opened 2022-04-28 04:46 UTC by davidebeatrici

Fixes #20817.

2022-04-28 08:42 UTC, silverqx approved these changes
I can confirm that this PR fixed the build, the build process finished without errors, thank you 🙌 @davidebeatrici.

I don't know if the static build especially QMYSQL plugin works correctly, but I will test it in the future when I will do next release of my personal library project and let know.

2022-04-28 08:50 UTC, davidebeatrici commented
No problem, thanks for testing!

2022-04-28 09:06 UTC, JackBoosY commented
cc @Neumann-A for review this PR.

2022-04-28 11:51 UTC, Neumann-A approved these changes

2022-04-29 02:34 UTC, JackBoosY requested changes

2022-04-29 02:34 UTC, JackBoosY commented on ports/qt5-base/portfile.cmake
> +        list(APPEND DEBUG_OPTIONS "MYSQL_LIBS=${MYSQL_DEBUG} ${SSL_DEBUG} ${EAY_DEBUG} ${ZLIB_DEBUG} ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib")
```suggestion
        list(APPEND RELEASE_OPTIONS "MYSQL_LIBS=${MYSQL_RELEASE} ${SSL_RELEASE} ${EAY_RELEASE} ${ZLIB_RELEASE}")
        list(APPEND DEBUG_OPTIONS "MYSQL_LIBS=${MYSQL_DEBUG} ${SSL_DEBUG} ${EAY_DEBUG} ${ZLIB_DEBUG}")
        if (VCPKG_TARGET_IS_WINDOWS)
            list(APPEND RELEASE_OPTIONS "ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib")
            list(APPEND DEBUG_OPTIONS "ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib")
        endif()
```

2022-04-29 04:22 UTC, dg0yt commented on ports/qt5-base/portfile.cmake
> +        list(APPEND DEBUG_OPTIONS "MYSQL_LIBS=${MYSQL_DEBUG} ${SSL_DEBUG} ${EAY_DEBUG} ${ZLIB_DEBUG} ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib")
We are inside `VCPKG_TARGET_IS_WINDOWS` here.

2022-04-29 06:37 UTC, JackBoosY approved these changes

2022-04-29 07:55 UTC, silverqx commented on ports/qt5-base/portfile.cmake
> +        list(APPEND DEBUG_OPTIONS "MYSQL_LIBS=${MYSQL_DEBUG} ${SSL_DEBUG} ${EAY_DEBUG} ${ZLIB_DEBUG} ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib")
I have taken a closer look at this PR and it is correct, we already are inside `VCPKG_TARGET_IS_WINDOWS`. @JackBoosY your proposed change is not correct.

2022-04-29 07:56 UTC, silverqx approved these changes
LGTM

2022-04-29 20:21 UTC, merged

2022-04-29 20:21 UTC, BillyONeal commented
Thanks for the fix!

2022-04-29 23:19 UTC, davidebeatrici commented
Thanks for merging!

2022-04-30 05:34 UTC, silverqx commented
Thx guys for this PR