[cgns] Update to 4.3.0
microsoft/vcpkg pull request #24531
Opened 2022-05-04 08:22 UTC by panda-z

**Describe the pull request**

- #### What does your PR fix?
  Update cgns to 4.3.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Yes (As before)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-05-05 00:01 UTC, BillyONeal commented on ports/cgns/hdf5.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
It is kind of strange that this file goes from LF to CRLF but I tried to put it back and that makes things fail. O_O

No change requested.

2022-05-05 00:16 UTC, BillyONeal requested changes
I was unable to build `cgns[hdf5,lfs,legacy,cgnstools]:x64-windows`, with the failure:

```
-- Could NOT find Tclsh (missing: TCL_TCLSH) 
-- Could NOT find TCL (missing: TCL_LIBRARY TCL_INCLUDE_PATH) 
-- Could NOT find TCLTK (missing: TCL_LIBRARY TCL_INCLUDE_PATH TK_LIBRARY TK_INCLUDE_PATH) 
-- Could NOT find TK (missing: TK_LIBRARY TK_INCLUDE_PATH) 
CMake Error at src/cgnstools/CMakeLists.txt:80 (message):
  The path and library needs to be defined for:

      TCL;TK
```

It looks like some dependencies are missing from declarations?

I pushed some other minor nitpicks.

2022-05-05 00:16 UTC, BillyONeal commented on ports/cgns/vcpkg.json
> -    "tools": {
Why is this feature renamed?

2022-05-05 00:16 UTC, BillyONeal commented on ports/cgns/vcpkg.json
>      "tests": {
Should this feature exist in the first place?

2022-05-05 00:16 UTC, BillyONeal commented on ports/cgns/vcpkg.json
>        "description": "Enable fortran support (not yet implemented)"
Not yet implemented suggests that the feature should be removed?

2022-05-05 02:40 UTC, panda-z commented on ports/cgns/vcpkg.json
> -    "tools": {
"cgnstools" is different with "tools". The "tools" is built by default. I just add a new feature named "cgnstools".

2022-05-05 02:45 UTC, panda-z commented on ports/cgns/vcpkg.json
>        "description": "Enable fortran support (not yet implemented)"
Ok, I forgot I've installed [ActiveTcl](https://www.activestate.com/activetcl/) manually. It will built without error after installed ActiveTcl. Should I remove this feature?

2022-05-05 02:49 UTC, panda-z commented on ports/cgns/hdf5.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
I think this may related to the trailing spaces in the original source file. If the patch has been modifed and the trailing spaces in patch file is (automatically) removed by editor, then the patch will fail to apply.

2022-05-05 03:47 UTC, panda-z commented on ports/cgns/portfile.cmake
> +        foreach(CGNSTOOL IN LIOSTS CGNSTOOLS)
Is "LIOSTS" a typo?

2022-05-05 04:42 UTC, panda-z commented on ports/cgns/hdf5.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
I've pushed a commit that converts this patch from CRLF to LF.

2022-05-05 04:44 UTC, panda-z commented on ports/cgns/vcpkg.json
>        "description": "Enable fortran support (not yet implemented)"
I removed ActiveTCL and installed tcl from vcpkg, but cmake can't locate the installed tcl package.

2022-05-05 05:45 UTC, panda-z commented on ports/cgns/vcpkg.json
>      "tests": {
I've put this feature at the end. But it seems `.\vcpkg x-add-version` updated the json file.

2022-05-05 11:55 UTC, panda-z commented on ports/cgns/vcpkg.json
>        "description": "Enable fortran support (not yet implemented)"
After some investigation, it seems "cgnstools" feature requires also tk, which is not currently available in vcpkg. Should this feature be removed? Related issue: https://github.com/microsoft/vcpkg/issues/7648

2022-05-06 06:23 UTC, JonLiu1993 commented
@panda-z ,I tested the features locally with the command "./vcpkg install cgns[hdf5,lfs,legacy,cgnstools]:x64-windows" failed:
````
CMake Error at src/cgnstools/CMakeLists.txt:80 (message):
  The path and library needs to be defined for:

      TCL;TK
````

2022-05-06 08:43 UTC, panda-z commented
@JonLiu1993 

Currently, the feature "cgnstools" relies on tcl and tk as dependencies. While tcl is available in vcpkg repo but cannot be located by cmake when building cgns. Tk is not currently available in vcpkg repo (https://github.com/microsoft/vcpkg/issues/7648).

By installing [ActiveTcl](https://www.activestate.com/activetcl/) one can workaround the build failure issue. But that will pull in a third party binary package. I have no idea whether we should keep this feature option or not.

2022-05-06 09:28 UTC, JonLiu1993 commented
> @JonLiu1993
> 
> Currently, the feature "cgnstools" relies on tcl and tk as dependencies. While tcl is available in vcpkg repo but cannot be located by cmake when building cgns. Tk is not currently available in vcpkg repo (#7648).
> 
> By installing [ActiveTcl](https://www.activestate.com/activetcl/) one can workaround the build failure issue. But that will pull in a third party binary package. I have no idea whether we should keep this feature option or not.

Thanks for the clarification, as you said we cannot use the feature "cgnstools" directly at the moment, I suggest to delete this feature for now

2022-05-06 09:33 UTC, Neumann-A commented
You cannot delete existing features... this breaks the upgrade path.

2022-05-06 09:40 UTC, panda-z commented
@Neumann-A 

The "cgnstools" is not an existing feature. It is a new feature which is introduced by this PR.

However, "tools" is an existing feature which will be removed, since it is an "dummy" feature which is unused in portfile.cmake.

If this breaks the upgrade path, I can revert the changes.

2022-05-06 18:46 UTC, BillyONeal commented on ports/cgns/portfile.cmake
> +        foreach(CGNSTOOL IN LIOSTS CGNSTOOLS)
Yes, should be `IN LISTS`.

2022-05-06 18:47 UTC, BillyONeal commented on ports/cgns/portfile.cmake
> +        foreach(CGNSTOOL IN LIOSTS CGNSTOOLS)
(Sorry I just realized I pushed that)

2022-05-06 19:11 UTC, BillyONeal commented on ports/cgns/vcpkg.json
>        "description": "Enable fortran support (not yet implemented)"
Yes, if we're adding a feature it should work out of the box, so please remove this one.

2022-05-06 19:11 UTC, BillyONeal commented on ports/cgns/portfile.cmake
> +        foreach(CGNSTOOL IN LIOSTS CGNSTOOLS)
I fixed it!

2022-05-06 19:13 UTC, BillyONeal commented
> You cannot delete existing features... this breaks the upgrade path.

I think it's borderline because it's a non-default feature with no effects so presumably people wouldn't have installed it. On the other hand there seems to be little strong reason to remove it either.

@panda-z I think we should describe any features with no effects with "No effects, preserved for upgrade compatibility." or similar and not add new features that are broken.

2022-05-07 09:57 UTC, panda-z commented
@BillyONeal Thanks for clarification. That makes sense. I've modified the description to "No effects, preserved for upgrade compatibility".

In addition, "cgnstools" is removed due to the lack of support for tcl/tk in vcpkg.

2022-05-09 03:11 UTC, JonLiu1993 approved these changes

2022-05-09 06:33 UTC, JonLiu1993 commented
@panda-z ,I tested the features locally with the command "./vcpkg install cgns[*]" failed:
````
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at F:/Feature-test/cgns/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FortranCInterface/Detect.cmake:41 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  F:/Feature-test/cgns/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/FortranCInterface.cmake:224 (include)
  CMakeLists.txt:168 (include)

````

2022-05-09 07:38 UTC, panda-z commented
@JonLiu1993 This error may relate to the "not yet implemented" fortran feature.

2022-05-09 07:49 UTC, JonLiu1993 commented
> @JonLiu1993 This error may relate to the "not yet implemented" fortran feature.

OK, I will test the other features again

2022-05-11 06:27 UTC, panda-z commented
Can we remove the `requires:author-response` label? Thanks.

2022-05-11 07:27 UTC, JonLiu1993 commented
Except for the fortran feature, all features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2022-05-11 07:27 UTC, JonLiu1993 approved these changes

2022-05-11 23:26 UTC, BillyONeal commented on ports/cgns/linux_lfs.patch
>  +    add_definitions(-D_FILE_OFFSET_BITS=64 -D__LARGEFILE64_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE)
Do we still need this patch?

```
PS C:\Dev\CGNS> git switch -d ec538ac11dbaff510464a831ef094b0d6bf7216c
HEAD is now at ec538ac add 4.3.0 release to version list
PS C:\Dev\CGNS> findstr /snipl FILE_OFFSET_BITS *
PS C:\Dev\CGNS> findstr /snipl LARGEFILE64 *
PS C:\Dev\CGNS> findstr /snipl LARGEFILE *
PS C:\Dev\CGNS>
```

2022-05-11 23:27 UTC, merged

2022-05-11 23:28 UTC, BillyONeal commented
Thanks for the update! (If you'd be willing to submit a PR removing that patch if unnecessary that would be nice, but didn't seem worth blocking the version update for that)

2022-05-12 01:06 UTC, panda-z commented on ports/cgns/linux_lfs.patch
>  +    add_definitions(-D_FILE_OFFSET_BITS=64 -D__LARGEFILE64_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE)
I don't have a linux box on hand. So I haven't touched this patch.

Macros started with underscore are usually preserved for compiler or standard library internal use. So you cannot grep it from source files.

Refs: http://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html