Update portfile.cmake
microsoft/vcpkg pull request #24578
Opened 2022-05-06 11:06 UTC by anders-wind

**Describe the pull request**

- #### What does your PR fix?
Update the mpmcqueue package to a newer version (commit from 2021-12-01).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
I have not updated anything related to CI

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
I hope so.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

I am still working on this PR

2022-05-06 11:06 UTC, anders-wind commented
Still need to update the sha512

2022-05-06 11:34 UTC, anders-wind commented
And is there any way access the content in "`D:\buildtrees\mpmcqueue\build-x86-windows-dbg-out.log`"

2022-05-07 02:22 UTC, FrankXie05 commented
@anders-wind Thank you for submitting the pull request, the first submission of pull request requires you to sign the [CLA](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=24578)

2022-05-08 19:10 UTC, anders-wind commented
> @anders-wind Thank you for submitting the pull request, the first submission of pull request requires you to sign the [CLA](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=24578) And can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

Hi - I have signed the CLA. What is the CONTROL file? The vcpkg.json?

2022-05-09 01:50 UTC, FrankXie05 commented
@anders-wind Yes, it is vcpkg.json, please refer to [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

2022-05-09 07:38 UTC, FrankXie05 reviewed
````
file(COPY
    ${SOURCE_PATH}/include/rigtorp/MPMCQueue.h
    DESTINATION ${CURRENT_PACKAGES_DIR}/include/rigtorp
)
````
Why delete it？ This file contains a disclaimer.
https://github.com/rigtorp/MPMCQueue/blob/master/include/rigtorp/MPMCQueue.h

2022-05-09 07:46 UTC, anders-wind commented
> ```
> file(COPY
>     ${SOURCE_PATH}/include/rigtorp/MPMCQueue.h
>     DESTINATION ${CURRENT_PACKAGES_DIR}/include/rigtorp
> )
> ```
> 
> Why delete it？ This file contains a disclaimer. https://github.com/rigtorp/MPMCQueue/blob/master/include/rigtorp/MPMCQueue.h

Im just using the cmake setup instead of just copying over the file.

2022-05-09 07:54 UTC, FrankXie05 commented
@anders-wind Sorry, we just need to keep a main copyright and it's fine. :)

2022-05-09 08:02 UTC, FrankXie05 requested changes

2022-05-09 08:02 UTC, FrankXie05 commented on ports/mpmcqueue/vcpkg.json
> +  "port-version": 0,
```suggestion
```
Just delete, then run command `.\vcpkg.exe format-manifest .\ports\mpmcqueue\vcpkg.json `

2022-05-09 11:05 UTC, anders-wind commented on ports/mpmcqueue/vcpkg.json
> +  "port-version": 0,
I deleted it and ran format-manifest. It didnt add it again so I hope thats ok?

2022-05-09 20:16 UTC, anders-wind commented
Oh well - it looks like their cmake setup is not fully functional - or atleast compatible with vcpk. Unless I am missing something

2022-05-10 00:19 UTC, FrankXie05 commented on ports/mpmcqueue/vcpkg.json
> +  "port-version": 0,
Yes, it will be added automatically after formatting.

2022-05-11 09:09 UTC, anders-wind commented
Is there a common solution to this type of cmake config errors?

2022-05-11 10:12 UTC, FrankXie05 requested changes

2022-05-11 10:12 UTC, FrankXie05 commented on ports/mpmcqueue/portfile.cmake
> +vcpkg_cmake_config_fixup()
```suggestion
```
This method is for Merge release and debug CMake targets and configs to support multiconfig generators. This port does not export cmake configuration, so this method is not needed.
Reference: https://github.com/microsoft/vcpkg/blob/master/ports/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake

2022-05-11 10:12 UTC, FrankXie05 commented on ports/mpmcqueue/vcpkg.json
> +    }
```suggestion
```
`vcpkg_cmake_config_fixup` is provided by this, so delete it together。

2022-05-11 10:34 UTC, FrankXie05 requested changes

2022-05-11 10:34 UTC, FrankXie05 commented on ports/mpmcqueue/portfile.cmake
>  configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)
```suggestion
configure_file("${SOURCE_PATH}/LICENSE" "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" COPYONLY)
```

2022-05-11 10:34 UTC, FrankXie05 commented on ports/mpmcqueue/portfile.cmake
> +vcpkg_cmake_config_fixup()
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/MPMCQueue)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib") 
```
The method `vcpkg_cmake_config_fixup` is used to merge release and debug CMake targets and configs to support multiconfig generators.
Referance: https://github.com/microsoft/vcpkg/blob/master/ports/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake

2022-05-13 06:42 UTC, FrankXie05 approved these changes

2022-05-13 23:51 UTC, merged

2022-05-13 23:51 UTC, BillyONeal commented
Thanks for the update!

2022-05-14 09:46 UTC, anders-wind commented
@FrankXie05 Thanks for the feedback and help - hopefully next PR will require less guiding :)