[cppgraphqlgen] Update to v4.3.1
microsoft/vcpkg pull request #24607
Opened 2022-05-08 06:17 UTC by wravery

**Describe the pull request**

- #### What does your PR fix?
  Updates `cppgraphqlgen` to the latest release.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All, No (although it is still marked as failing in Linux because the version of GCC is not new enough)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes.

2022-05-09 06:29 UTC, LilyWangLL requested changes

2022-05-09 06:29 UTC, LilyWangLL commented on ports/cppgraphqlgen/vcpkg.json
> +  "version-semver": "4.3.1",
```suggestion
  "version": "4.3.1",
```

2022-05-10 07:25 UTC, LilyWangLL approved these changes

2022-05-10 18:36 UTC, merged

2022-05-10 18:36 UTC, BillyONeal commented
Thanks for the update!