[mdl] Add port MDL-SDK 2020.0.1
microsoft/vcpkg pull request #24633
Opened 2022-05-09 23:27 UTC by theblackunknown

**Describe the pull request**

- #### What does your PR fix?
Add a new port for MDL-SDK

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
all, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-05-12 02:56 UTC, Cheney-W commented on ports/mdl/003-install-rules.patch
> ++]=])
I think you could save mdl-config.cmake.in into the ports\mdl folder and move it into the source_path with following command in portfile.cmake:
`file(COPY "${CMAKE_CURRENT_LIST_DIR}/mdl-config.cmake.in" DESTINATION "${SOURCE_PATH}")`

This will avoid file access errors at the vcpkg_cmake_configure step.

2022-05-12 03:00 UTC, Cheney-W commented on versions/m-/mdl.json
> +  ]
Please remove this record. There can be only one record about the version in a PR.

2022-05-12 12:58 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++]=])
I am happy to do it, out of curiosity what is the advantage of copying a `mdl-config.cmake.in` from the portfile script rather than bringing it through a patch ?

> This will avoid file access errors at the vcpkg_cmake_configure step.

I am not sure what you are referring to, do you have some logs to share regarding this ?

2022-05-12 13:00 UTC, theblackunknown commented on versions/m-/mdl.json
> +  ]
Thanks for catchign this ! This is a leftover !

2022-05-13 06:16 UTC, JackBoosY commented on ports/mdl/001-freeimage-from-vcpkg.patch
> +diff --git a/cmake/find/find_freeimage_ext.cmake b/cmake/find/find_freeimage_ext.cmake
This patch is too huge, can you please reduce its size?

2022-05-13 06:16 UTC, JackBoosY commented on ports/mdl/002-clang-7.0.x-and-above.patch
> ++    if(${_CLANG_VERSION_STRING} VERSION_LESS "7.0.0")
Why remove condition `VERSION_GREATER_EQUAL "7.1.0"`?

2022-05-13 06:16 UTC, JackBoosY commented on ports/mdl/003-install-rules.patch
> ++]=])
Since it doesn't contain any extra operations, we can simply export the target as `mdl-config` and remove these code,

2022-05-13 06:19 UTC, JackBoosY requested changes

2022-05-13 06:19 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +)
```suggestion
vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
```

2022-05-13 06:19 UTC, JackBoosY commented on ports/mdl/009-build-static-llvm.patch
> ++  llvm_add_library(${name} STATIC ${ARG_UNPARSED_ARGUMENTS})
Why do you make this changes?

2022-05-13 06:19 UTC, JackBoosY commented on ports/mdl/003-install-rules.patch
> ++            LIBRARY  DESTINATION modules # ${CMAKE_INSTALL_LIBDIR}
Why do you choose `modules` as the installation path for `LIBRARY` here?

2022-05-13 07:41 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++]=])
Good point !

2022-05-13 07:42 UTC, theblackunknown commented on ports/mdl/001-freeimage-from-vcpkg.patch
> +diff --git a/cmake/find/find_freeimage_ext.cmake b/cmake/find/find_freeimage_ext.cmake
You are right, I'll revise it

2022-05-13 07:44 UTC, theblackunknown commented on ports/mdl/002-clang-7.0.x-and-above.patch
> ++    if(${_CLANG_VERSION_STRING} VERSION_LESS "7.0.0")
The original repo expect a `clang` version 7 and not above for working correctly, however from small test this does not seems to matter so I decided to lift the restriction.
I can give another round of testing to this

2022-05-13 07:49 UTC, theblackunknown commented on ports/mdl/009-build-static-llvm.patch
> ++  llvm_add_library(${name} STATIC ${ARG_UNPARSED_ARGUMENTS})
Two reasons:
1. To compile MDL libraries with dependencies only to the other ports
2. To workaround LLVM libraries compiled as shared library but without any explicitly exported symbol which fails to produce a `.lib` on Windows.

MDL vendors its own LLVM subset, which specific modifications from the original.
When library linkage is requested on Windows, some LLVM libraries ends up compiling as shared library but as they do not have any exported symbiol no `.lib` is produced and this cascades into further linkage errors.

As this modified LLVM is vendored, I also wanted it to be fully included in MDL binaries and not "spilled" into additional artefacts produced for this package.

2022-05-13 07:50 UTC, theblackunknown commented on ports/mdl/009-build-static-llvm.patch
> ++  llvm_add_library(${name} STATIC ${ARG_UNPARSED_ARGUMENTS})
Note that alternatively I have also considered marking this port ` ON_STATIC_LIBRARY` but the mdl package only produce shared library so I guess this will fails packaging checking as `.dll`/`.so` are always produced

2022-05-13 07:51 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++            LIBRARY  DESTINATION modules # ${CMAKE_INSTALL_LIBDIR}
This is a leftover part, thanks for catchig it 
I'll modify it

2022-05-13 07:52 UTC, JackBoosY commented on ports/mdl/009-build-static-llvm.patch
> ++  llvm_add_library(${name} STATIC ${ARG_UNPARSED_ARGUMENTS})
If we only want to build mdl as static library on Windows, we should add the following codes instead of make this changes:
```cmake
if (VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
```
Please add it in top of `portfile.cmake` instead.

2022-05-13 08:29 UTC, theblackunknown commented on ports/mdl/009-build-static-llvm.patch
> ++  llvm_add_library(${name} STATIC ${ARG_UNPARSED_ARGUMENTS})
This is not about building `mdl` as a whole as static, but just the vendored LLVM subset.
mdl binaries must be shared library so current `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` is what I believe is correct to do.

2022-05-13 08:43 UTC, JackBoosY commented on ports/mdl/009-build-static-llvm.patch
> ++  llvm_add_library(${name} STATIC ${ARG_UNPARSED_ARGUMENTS})
@theblackunknown Okay.

2022-05-16 02:52 UTC, JackBoosY commented on ports/mdl/001-freeimage-from-vcpkg.patch
> ++        find_file(_FREEIMAGE_HEADER_FILE "FreeImage.h"
I would like to use `find_path`, but it's okay.

2022-05-16 02:59 UTC, JackBoosY requested changes

2022-05-16 02:59 UTC, JackBoosY commented on ports/mdl/mdl-config.cmake.in
> +find_dependency(freeimage)
Missing `CONFIG` here?

2022-05-16 02:59 UTC, JackBoosY commented on ports/mdl/003-install-rules.patch
> ++export(
We can combile `install(EXPORT)` and `export()` with the following codes:
```cmake
install(TARGETS ... EXPORT mdl-targets
    ....
)
install(EXPORT unofficial-mdl-targets
    NAMESPACE unofficial::mdl::
    DESTINATION share/unofficial-mdl
)
```
Please note that this is unofficial, so you need to add the prefix namespace `unofficial::`.

2022-05-16 08:24 UTC, theblackunknown commented on ports/mdl/002-clang-7.0.x-and-above.patch
> ++    if(${_CLANG_VERSION_STRING} VERSION_LESS "7.0.0")
After a bit more advanced, it seems to really matter to stick to clang 7.0
Giving it a bit more thought it make sense as this is matching the vendored LLVM version

I will switch back this PR until I find a more satisfying solution.
Ideas I have in mind are:
1. mimick what `vcpkg_find_acquire_program(CLANG)` does but pulling a clang version 7
2. trying to bypass the vendored LLVM and use in `vcpkg` (🤞 probably breaking API changes but let's try)

Beyong that I do not really having any further ideas, I would appreciate if you have some ?
Otherwise i'll move that port in my custom registry if I do not succeed with above ideas

2022-05-16 08:25 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++export(
Indeed, I will try to contact upstream to propose my patches can be then

2022-05-17 07:09 UTC, theblackunknown commented on ports/mdl/002-clang-7.0.x-and-above.patch
> ++    if(${_CLANG_VERSION_STRING} VERSION_LESS "7.0.0")
So in the end I did "3. checkout clang 7 into vendored LLVM, build and use it"
Although we now have increased compilation time, this approach is more robust and scale well.

2022-05-17 07:17 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++export(
Agreed about merging `install` and `export`, epsecially as I do not really need `export`

> Please note that this is unofficial, so you need to add the prefix namespace unofficial::.

I was going to do this, but then looking at upstream code I see that they intend CMake target namespace to be `mdl::` as we can see in the way they alias.
https://github.com/NVIDIA/MDL-SDK/blob/d6c9a6560265025a30d16fcd9d664f830ab63109/src/prod/lib/mdl_core/CMakeLists.txt#L54-L55

Hence I think we should keep the namespace to `mdl::` otherwise this means we would get different target depending if we are using this port or using MDL-SDK as a subdirectory.

That being said, we can still keep the package name as `unofficial-mdl` if you want.
Although unofficial I find it confusing but I understand the rationale.

What do you think ?

2022-05-17 07:42 UTC, JackBoosY commented on ports/mdl/003-install-rules.patch
> ++export(
Since the upstream added a namespace `mdl::`, we can use namespace `unofficial::mdl::` instead.

2022-05-17 22:16 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++export(
Ok, I think my latest changes take care of your request

2022-05-18 06:35 UTC, JackBoosY requested changes

2022-05-18 06:35 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +        WORKING_DIRECTORY "${SOURCE_PATH}/src/mdl/jit/llvm/dist/tools")
```suggestion
    vcpkg_extract_source_archive_ex(
        ARCHIVE ${ARCHIVE}
        OUT_SOURCE_PATH CLANG_SOURCE_PATH
        PATCHES
            001-clang-skip-symlink.patch
            002-clang-build-static-clang.patch
    )
    file(RENAME "${SOURCE_PATH}" "${SOURCE_PATH}/src/mdl/jit/llvm/dist/tools")
```
Why not use `vcpkg_extract_source_archive_ex`?

2022-05-18 06:35 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +    string(SUBSTRING "${patchset_hash}" 0 10 patchset_hash)
So we don't need to get the source path. Use `CLANG_SOURCE_PATH` directly.

2022-05-18 06:35 UTC, JackBoosY commented on ports/mdl/002-use-llvm-clang.patch
> ++return()
I think we don't need this since we should ensure that this dependency is always exist.

2022-05-18 06:35 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +    )
I think we shouldn't download a build tool here.
We may need to ensure this tools exists in user's machine or gauantee by other ports or `vcpkg_find_acquire_program(CLANG)`.

2022-05-18 07:32 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +        WORKING_DIRECTORY "${SOURCE_PATH}/src/mdl/jit/llvm/dist/tools")
The script documentation says to prefer `vcpkg_extract_source_archive` (cf. https://github.com/microsoft/vcpkg/blob/6dbfaba0393e851fcef2a90ed33fcdac8074d241/scripts/cmake/vcpkg_extract_source_archive_ex.cmake#L4-L7)
Shoud I bother ?

2022-05-18 07:33 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    string(SUBSTRING "${patchset_hash}" 0 10 patchset_hash)
No I do not think so, `CLANG_SOURCE_PATH` exists because `vcpkg_extract_source_archive` requires it.

2022-05-18 07:35 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    string(SUBSTRING "${patchset_hash}" 0 10 patchset_hash)
To be honest, I would rather avoid this whole dance, but I cannot fully specify the folder where `vcpkg_extract_source_archive` will extract the archive. (We use to be able to with the old deprecated signature)
This hash generation code has been copied from this script.

2022-05-18 07:42 UTC, theblackunknown commented on ports/mdl/002-use-llvm-clang.patch
> ++return()
It is true that I do not need to verify that the target exists as the dependency should be properly solved, I only need the `return()` to skip below lines.
I still believe this can be useful to troubleshoot the port in case of failure but as it is not strictly needed I'll remove it for now

2022-05-18 07:48 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    )
I am running into the issue that I exactly need `clang` at version `7.0.0`
There is nothing providing me this feature nor guarantee in a cross-platform way in `vcpkg` scripts toolset as far I as know.
Moreover, as MDL-SDK is already shipping a vendored LLVM subset adding clang to it and building it seems the most trivial approach to do so.

2022-05-18 09:07 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +        WORKING_DIRECTORY "${SOURCE_PATH}/src/mdl/jit/llvm/dist/tools")
`vcpkg_extract_source_archive` has been deprecated. If you need to use it just because you need to get the target decompression path, you shouldn't. Please use `vcpkg_extract_source_archive_ex` and `file(RENAME)` instead.

2022-05-18 12:07 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    )
I am not sure to fully understand the change you suggest, can you elaborate more on what would be the alternative to get clang 7 for my port ?

To me current blockers are:
- Relying on `llvm[clang]`:  current HEAD will install `clang 13.0` and it is incompatible to build this port correctly
- Create a new host port dedicated to provide `clang` `7.0.0`: this redundant with `llvm[clang]` and will even conflicts with it if it gets installed into the installation folder
- Using `vcpkg_find_acquire_program(CLANG)`: first there is an hardcoded path to get clang 12 on windows, but also it tries to fetch whatever clang installed on the system whatever the version is, so also compatible. For UNIX platform it requires the user to install `clang` through package manager, but clang 7 may not be available anymore for some distrib

2022-05-18 12:17 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +        WORKING_DIRECTORY "${SOURCE_PATH}/src/mdl/jit/llvm/dist/tools")
I does not look like the second overload is `deprecated`, only the first one isn't it ?

2022-05-18 12:18 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    string(SUBSTRING "${patchset_hash}" 0 10 patchset_hash)
Reading again your review comment, I realise I am so wrong with computing all those things and that indeed I can simply use `CLANG_SOURCe_PATH` like so 

```
    vcpkg_extract_source_archive(CLANG_SOURCE_PATH
        ARCHIVE "${CLANG_ARCHIVE}"
        PATCHES
            001-clang-skip-symlink.patch
            002-clang-build-static-clang.patch
    file(RENAME "${CLANG_SOURCE_PATH}" "${SOURCE_PATH}/src/mdl/jit/llvm/dist/tools/clang")
```

2022-05-19 06:29 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +    )
> Relying on llvm[clang]: current HEAD will install clang 13.0 and it is incompatible to build this port correctly

If we add llvm[clang] as a dependency, the build time will grow significantly.

> Create a new host port dedicated to provide clang 7.0.0: this redundant with llvm[clang] and will even conflicts with it if it gets installed into the installation folder

No, port llvm already has it.

> Using `vcpkg_find_acquire_program(CLANG)`: first there is an hardcoded path to get clang 12 on windows, but also it tries to fetch whatever clang installed on the system whatever the version is, so also compatible. For UNIX platform it requires the user to install clang through package manager, but clang 7 may not be available anymore for some distrib

My suggestion is to use this. Users should ensure that they have the appropriate clang version installed.
If the version of clang in `vcpkg_find_acquire_program` does not match, we need to update its version first.

2022-05-19 06:30 UTC, JackBoosY requested changes

2022-05-19 06:30 UTC, JackBoosY commented on ports/mdl/002-use-llvm-clang.patch
> ++return()
Why add return here?

2022-05-19 12:10 UTC, theblackunknown commented on ports/mdl/002-use-llvm-clang.patch
> ++return()
Because I need to early out of this file without doing any processing at all.
Note that this file get implicitely included for any target declaring to depends on clang.
This was the _less intrusive_ option I find on top of upstream code

2022-05-19 12:11 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    )
Okay, let me make some changes on `vcpkg_find_acquire_program` where I will add a `CLANG7` to achieve this.
Let us continue this discussion on there

2022-05-19 12:13 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    )
> >Create a new host port dedicated to provide clang 7.0.0: this redundant with llvm[clang] and will even conflicts with it if it gets installed into the installation folder
> 
> No, port llvm already has it.

This is the part where I do not follow you, current `llvm` port can build `clang` 13 not 7, have I miss something ?

2022-05-19 19:22 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
@JackBoosY here is what I understood from your review comment, is this what you have in mind ?
From what I have seen implementing and testing it on Windows/macOS:
- Pro: mdl port is less complex, and build faster as `clang` is no more needed
- Cons: there is no prebuilt binaries for all platforms/arhictecure
- Cons: there is not even a ready to use and compatible package from the package manager
- Cons: when no prebuilt exists, it burden the user to provide `clang` 7 itself, but doing so will likely also replace the main compiler used to compile C/C++ sources which I see as a workflow conflict

Let me  know what you think, and if you have further improvements ideas to get clang 7

2022-05-19 19:23 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        "MIN_VERSION;PROGRAM_NAME;VERSION_REGEX"
Small useful feature addition: sometime fetch program version requires a regex to extract it from the output (e.g. `clang`)

2022-05-20 04:13 UTC, dg0yt commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
There are two big CONs to any addition to `vcpkg_find_acquire_program.cmake`:
- It is not versioned.
- Changes for one program invalidate cached artifacts for all consumers of any program.
  (You see this in the increased CI build time.)

That's the reason why there are some `vcpkg-tool-...` ports now.

2022-05-20 07:00 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
Good observation @dg0yt !
I will look into using/creating of those instead if possible.

2022-05-20 07:29 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
One notable cons of going the `vcpkg-tool-... ` path is that it is assume that the tool is assumed to be installed in the `CURRENT_HOST_INSTALLED_DIR` which _may_ conflict with other ports.

For example, in my case creating a new `vcpkg-tool-clang7` will conflict with `llvm[clang]` port, isn't it ?
That said, looking at `vcpkg-tool-python2` it gets installed into `${CURRENT_HOST_INSTALLED_DIR}/manual-tools/${PORT}` and write a `${CURRENT_PACKAGES_DIR}/share/${PORT}/details.cmake` CMake file but I am not sure how it gets retrieved ? I see that some port like `blitz` depends on it but just use `vcpkg_find_acquire_program(PYTHON2)` to retrive it

2022-05-20 12:47 UTC, dg0yt commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
Maybe Python2 is a different story, for historical reasons.

Different ports can install to different directories. If you depend on a particular tool port, you can refer to its relative installation directory (tight coupling), or the tool port can use `vcpkg-port-config.cmake` to offer variables and functions for portfile script mode.

2022-05-20 14:05 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
I am currently going down the `vcpkg-tool-...` route, can you points me to one of those ports which I may use as a reference ?
> you can refer to its relative installation directory (tight coupling), or the tool port can use vcpkg-port-config.cmake to offer variables and functions for portfile script mode.

I am especially interested into this as I have never met those yet.

2022-06-04 14:25 UTC, theblackunknown commented
@JackBoosY @dg0yt I think I implemented the right split between my port `mdl` and its required build tool `vcpkg-tool-clang7`.
I successfully tested it locally however I am struggling to get a meaningful output from the CI, moreover the build time seems to be pretty high those days.
May I ask that you can start reviewing latest changes, and ideally give it a try to build the port ?

In the meantime, I'll wait for the last CI to finish and see if I can troubleshoot any errors there.

2022-06-04 14:28 UTC, Neumann-A commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        endif()
I think the idea is to no longer add extra tools to `vcpkg_find_acquire_program`. You simply directly depend on the tool port.

2022-06-04 14:30 UTC, Neumann-A commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
Why are we building here? what about https://github.com/llvm/llvm-project/releases/tag/llvmorg-7.1.0

2022-06-04 15:25 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        endif()
I recently learnt about `vcpkg-port-config.cmake` behaviour and indeed I could totally bypass this.

2022-06-04 15:30 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
Believe me I would love to simply pull an prebuilt binaries however mdl-sdk strictly requires clang 7.0.0 to match its internal modified vendored LLVM 7.0.0. 
I confirm this from my port testing that using any other version will fail due to bitcode incompatibilities. 
cf. MDL-SDK readme https://github.com/NVIDIA/MDL-SDK/blob/master/README.md#dependencies
Note that there is the old page on LLVM org site where I can find prebuilt package but it was not clear to me whether I will restrict this port or only a subset of triplet because I do not build clang from source.

2022-06-17 06:53 UTC, Cheney-W commented
Could you please handle the conflicts? Thank you!

2022-06-24 07:45 UTC, Cheney-W commented
Pinging @theblackunknown for response. Is work still being done for this PR?

2022-06-25 12:22 UTC, theblackunknown commented
> Pinging @theblackunknown for response. Is work still being done for this PR?

Hi @Cheney-W , sorry for the delay. Yes this PR is still in progress, I have not found enough bandwidth to apply the change you requested but I'll try to do it next week.

2022-06-25 15:59 UTC, theblackunknown commented on ports/mdl/002-clang-7.0.x-and-above.patch
> ++    if(${_CLANG_VERSION_STRING} VERSION_LESS "7.0.0")
@JackBoosY  Can we resolve this conversation thread ?

2022-06-25 16:00 UTC, theblackunknown commented on ports/mdl/003-install-rules.patch
> ++export(
@JackBoosY can we resolve this conversation thread ?

2022-06-25 16:01 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    )
@JackBoosY can we resolve this conversation thread ?
The new `vcpkg-tool-clang7` port solves this issue (thanks @dg0yt for suggesting to use `vcpkg-tool-XXX` port style for this).

2022-06-25 16:02 UTC, theblackunknown commented on ports/mdl/002-use-llvm-clang.patch
> ++return()
Are you satisfied with my answer, or would you like to suggest an alternative ?

2022-06-25 16:03 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        set(paths_to_search "${DOWNLOADS}/tools/${program_name}/${tool_subdirectory}/bin")
No longer relevant as I am relying on `vcpkg-port-config.cmake` from `vcpkg-tool-clang7`.

2022-06-25 16:03 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        "MIN_VERSION;PROGRAM_NAME;VERSION_REGEX"
No longer relevant.

2022-06-25 16:05 UTC, theblackunknown commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +        endif()
I have reverted my changes in this file with latest commit, let me know if you need anything else before resolving this thread.

2022-06-25 16:06 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
Do you agree with can keep building after reading my explanation ? Or do you want to suggest an alternative ?

2022-07-01 07:23 UTC, JackBoosY requested changes

2022-07-01 07:23 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +mdl:x64-windows-static-md=fail
I think we can add `supports` value `!(windows & static)` on _ports/mdl/vcpkg.json_ instead since it's unsupported by the upstream.

2022-07-01 07:23 UTC, JackBoosY commented on ports/mdl/002-use-llvm-clang.patch
> ++option(LLVM_INCLUDE_TOOLS "Generate build targets for the LLVM tools." ON)
This is not needed.

2022-07-01 07:23 UTC, JackBoosY commented on ports/vcpkg-tool-clang7/002-clang-skip-other-tool-configuration.patch
> +diff --git a/tools/CMakeLists.txt b/tools/CMakeLists.txt
Please add judgment `if (0) ... endif()` to reduce the patch size.

2022-07-01 07:23 UTC, JackBoosY commented on ports/mdl/002-use-llvm-clang.patch
> ++option(CLANG_TOOL_DRIVER_BUILD "Whether to build driver as part of CLANG" ON)
Are these 2 options not used?

2022-07-01 07:23 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
We should add `supports` value `!static` in _ports/mdl/vcpkg.json_ instead.

2022-07-01 07:23 UTC, JackBoosY commented on ports/vcpkg-tool-clang7/portfile.cmake
> +cmake_path(GET PYTHON3 PARENT_PATH PYTHON3_DIR)
```suggestion
get_filename_component(PYTHON3_DIR "${PYTHON3}" DIRECTORY)
```

2022-07-02 17:45 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/002-clang-skip-other-tool-configuration.patch
> +diff --git a/tools/CMakeLists.txt b/tools/CMakeLists.txt
Agreed, I have cleanup other clang patches similarly.

2022-07-02 17:45 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +cmake_path(GET PYTHON3 PARENT_PATH PYTHON3_DIR)
Fine for me, out of curiosity any guideline on why `get_filename_component` is preferred now that there is `cmake_path` ?

2022-07-02 17:45 UTC, theblackunknown commented on scripts/ci.baseline.txt
> +mdl:x64-windows-static-md=fail
Sounds reasonable, I lift this requirement as a future improvement.

2022-07-02 20:29 UTC, theblackunknown commented on ports/mdl/009-include-priority-vendored-llvm.patch
> +         ${mdl-jit-llvm_BINARY_DIR}/dist/include
I have run into this - not consistently - that if you have `llvm` from vcpkg port installed prior to installing `mdl` there are conflicts between the vendored and the installed one headers.
This patch fixes this.

2022-07-04 07:04 UTC, JackBoosY requested changes

2022-07-04 07:04 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
Also please add double quotes to the absolute paths.

2022-07-04 07:04 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2022-07-04 07:05 UTC, JackBoosY commented on ports/mdl/portfile.cmake
> +vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Since you've added `!(windows&static)` to `supports`, this will only enabled on non-Windows triplets.
I think it's okay now.

2022-07-04 20:26 UTC, theblackunknown commented on ports/mdl/003-freeimage-disable-faxg3.patch
> ++        // Plugin_description( "fi_faxg3" , FIF_FAXG3 ), # not shipped with vcpkg
Yes, `freeimage` port explicitely disable it so it is not available.
https://github.com/microsoft/vcpkg/blob/4826ede84084395b0f87476e48ff6d4070eba0e4/ports/freeimage/disable-plugins-depending-on-internal-third-party-libraries.patch#L19-L23

2022-07-04 20:37 UTC, theblackunknown commented on ports/mdl/006-guard-nonexisting-targets.patch
> +-    obj.llvm-tblgen
I have left a note about this few lines below in the patch: this is because vendored LLVM does not define this target in some cases (i.e. in this case it is in case the Ninja generator is in use).
cf. https://github.com/NVIDIA/MDL-SDK/blob/aa9642b2546ad7b6236b5627385d882c2ed83c5d/src/mdl/jit/llvm/dist/cmake/modules/TableGen.cmake#L124-L128

2022-07-04 20:37 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
Will do.

2022-07-05 02:40 UTC, JackBoosY approved these changes, later dismissed

2022-07-05 06:14 UTC, FrankXie05 commented
All features are tested successfully in the following triplet:

- x64-windows

2022-07-06 20:35 UTC, vicroms requested changes
I'm tagging this PR for review with the whole team in our next Thursday meeting (7/7/22).

We usually don't accept PRs trying to set the compiler used for the port since compiler is a user setting. But this case is a different since it uses LLVM as a dependency rather than as the compiler; and [upstream has listed Clang 7 as a hard-dependency](https://github.com/NVIDIA/MDL-SDK#dependencies).

2022-07-06 20:43 UTC, vicroms commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
I'd like to see this port use the pre-built binaries and restrict it to the subset of triplets where we have those binaries available.

2022-07-07 08:30 UTC, theblackunknown commented
> I'm tagging this PR for review with the whole team in our next Thursday meeting (7/7/22).
> 
> We usually don't accept PRs trying to set the compiler used for the port since compiler is a user setting. But this case is a different since it uses LLVM as a dependency rather than as the compiler; and [upstream has listed Clang 7 as a hard-dependency](https://github.com/NVIDIA/MDL-SDK#dependencies).

Hi @vicroms and thanks for your interest in this PR !

Let me know after your team review if there is anything more I can do to help. I am also in touch with the upstream repository maintainers if that helps to change things there instead of patching the port.

2022-07-07 08:33 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
I think this is reasonable for the first version of this port yes. 
I think a couple of triplets are non-supported (e.g. arm64-osx) but that should leave the most common ones enabled. 
I also hope that - given how old is LLVM 7 - it does not depends on outdated system libraries.

2022-07-09 19:43 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
For MDL-SDK, `clang` is used as a simple build tool: if I remember correctly it is used to produce LLVM module bitcode which will end up as C array content into some headers compiled into MDL-SDK binaries.
This is emphasized by both:
- `vcpkg-tool-clang7` being a host dependency of `mdl`
- `vcpkg-tool-clang7` to only produce a `clang` executable, no other executable, nor libraries, nor include headers is produced to avoid any possible conflicts with `llvm` port. Moreover, it produces the `clang` executable in a non-default nor search location: it ends up in `$<...>/tools/vcpkg-tool-clang7/clang` and is made available through a `vcpkg-port-config.cmake`.

Let me know if this makes sense and provide enough guarantee to not conflict with `llvm`.

2022-07-09 19:44 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
> I'd like to see this port use the pre-built binaries and restrict it to the subset of triplets where we have those binaries available.

Let me know if this comment still apply after your team meeting, if yes I'll dedicate some time this week to implement it.

2022-07-14 17:58 UTC, vicroms commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
@theblackunknown  sorry for the delayed reply. 

[As a team we are not convinced that `vcpkg-tool-*` is the right path forward](https://github.com/microsoft/vcpkg/pull/23659#issuecomment-1151867976). We are actively working on an [artifacts experience](https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/) that will serve use cases like this one. Note that at this point we are not making any commitments for when the feature will be fully available. 

Having said that, we would feel more comfortable merging this if you changed `mdl`'s portfile to acquire the necessary pre-built binaries it needs during its build and update the `supports` line to reflect platforms where the pre-built is available.

2022-07-19 02:40 UTC, Cheney-W commented
versions/m-/mdl.json(2,): error : While reading versions for port mdl from file: version/m-/mdl.json
File declares version `2021.1.2` with SHA: f63c610c21422d2b345b1cf88f6df7b3e1cd1c20
But local port with the same version has a different SHA: 69e720adce8a980c2b7f6d7608f3d1466cd991b9
Please update the port's version fields and then run:

    vcpkg x-add-version mdl
    git add versions
    git commit -m "Update version database"

to add a new version.

2022-07-19 16:00 UTC, theblackunknown commented
> versions/m-/mdl.json(2,): error : While reading versions for port mdl from file: version/m-/mdl.json File declares version `2021.1.2` with SHA: f63c610c21422d2b345b1cf88f6df7b3e1cd1c20 But local port with the same version has a different SHA: 69e720adce8a980c2b7f6d7608f3d1466cd991b9 Please update the port's version fields and then run:
> 
> ```
> vcpkg x-add-version mdl
> git add versions
> git commit -m "Update version database"
> ```
> 
> to add a new version.

Thanks for the reminder @Cheney-W , I am a bit swamped this week but I'll find time to put the final touch on this PR.

2022-07-19 23:55 UTC, theblackunknown commented on ports/vcpkg-tool-clang7/portfile.cmake
> +vcpkg_cmake_install()
I have revised this PR with your suggested changes, let me know if we are now aligned on how to write this port.

2022-07-20 02:49 UTC, JackBoosY approved these changes, later dismissed

2022-07-20 05:56 UTC, FrankXie05 commented
All features are tested successfully in the following triplet:

- x64-windows

2022-07-20 08:06 UTC, Cheney-W approved these changes, later dismissed

2022-07-26 00:01 UTC, vicroms requested changes, later dismissed
Partial review.

2022-07-26 20:55 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +endif()
Thanks I like your suggestion !
I took the liberty to abuse `vcpkg_extract_source_archive` for UNIX platform where I need to extract a tar: this is useful as it will extract into `buildtrees/` but also remove the top level directory which simplify the rest of the script to resolve `LLVM_CLANG7`

2022-07-26 20:56 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +endif()
> unfortunately we don't have VCPKG_HOST_ARCHITECTURE 

This is what I have noticed when I first code this part, but I notice that you _do_ use `VCPKG_HOST_ARCHITECTURE` in your suggestion. Is it intended ?

2022-07-27 06:28 UTC, JackBoosY commented
Ping @vicroms for review again.

2022-07-28 17:01 UTC, vicroms commented on ports/mdl/portfile.cmake
> +endif()
Not intended, I had a snippet at the top that tried to deduce the host architecture but decided against it, it seems like I forgot an instance.

2022-07-29 02:05 UTC, Cheney-W approved these changes, later dismissed

2022-07-29 20:23 UTC, vicroms commented on ports/mdl/portfile.cmake
> +        -Dclang_PATH:PATH=${LLVM_CLANG7}
Does this not affect users compiling this library on Clang?

2022-07-29 20:25 UTC, vicroms commented on ports/mdl/portfile.cmake
> +    message(FATAL_ERROR "Pre-built binaries for Clang 7 not available, aborting install (platform: ${VCPKG_CMAKE_SYSTEM_NAME}, architecture: ${VCPKG_HOST_ARCHITECTURE}).")
```suggestion
    message(FATAL_ERROR "Pre-built binaries for Clang 7 not available, aborting install (platform: ${VCPKG_CMAKE_SYSTEM_NAME}).")
```

Maybe we can wait for #25529 to define `VCPKG_HOST_TRIPLET`

2022-07-29 22:54 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +        -Dclang_PATH:PATH=${LLVM_CLANG7}
How could it affect them ?
This CMake variable is required and as a build tool set specifically for the MDL port, it doesn't "leak" to the user as far as I know ?
If a user uses clang to compile (e.g. on macOS) CMAKE_LANG_COMPILER would be set and not conflict with it right ?

2022-07-29 22:55 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    message(FATAL_ERROR "Pre-built binaries for Clang 7 not available, aborting install (platform: ${VCPKG_CMAKE_SYSTEM_NAME}, architecture: ${VCPKG_HOST_ARCHITECTURE}).")
I am fine to wait, but given the lengthy PR why not doing it as a follow-up?

2022-08-02 14:59 UTC, Thomas1664 commented on ports/mdl/vcpkg.json
> +  "version-semver": "2021.1.2",
```suggestion
  "version": "2021.1.2",
```

This version scheme does not confirm with semver because it has the year in its version.

2022-08-02 14:59 UTC, Thomas1664 commented on ports/mdl/portfile.cmake
> +    )
```suggestion
)

```

2022-08-05 15:19 UTC, theblackunknown commented on ports/mdl/vcpkg.json
> +  "version-semver": "2021.1.2",
Good catch, I have integrated your suggestion into my last commit.

2022-08-05 15:19 UTC, theblackunknown commented on ports/mdl/portfile.cmake
> +    )
Good catch, I have integrated your suggestion into my last commit.

2022-08-05 15:20 UTC, theblackunknown commented
Thanks for you review @Thomas1664 , I have integrated your suggestions.

2022-08-05 15:20 UTC, theblackunknown commented
Is there anything else preventing this PR to be merged ?

2022-08-08 02:30 UTC, FrankXie05 approved these changes, later dismissed

2022-08-08 20:46 UTC, BillyONeal submitted a review, later dismissed
The 'request changes' is about needing to have an understanding of what happened to boost.uuid , and the optional find_packages addressed in some form.

=================================

I am still extremely concerned about the clang 7 bits. I understand that the claim is that that's expected to produce bitcode or something that gets embedded into a header. However, it gets *very* close to explicitly disregarding something that is intended to be a user setting (via https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_chainload_toolchain_file ) If the user says "I want you to use MinGW", the port must use MinGW, and cannot be that opinionated about specific compilers or toolchains.

For example, we've had customers ask to ensure everything in their tree was built with `/ZH:SHA256`, necessitating forcing using a compiler new enough to understand that switch, to ensure no SHA-1 hashes land in the PDB. Or customers who needed `/guard:cf` or `/Qspectre` or similar funny switches to target other platforms, that sort of thing. (Sorry my windows-native-ness is showing with my examples but I hope you get the point)

However, I understand that this isn't intended to be used for 'front line' compilation of C++ code that may affect scenarios like that, so it may be OK.

I'm going to bring this up in the maintainers' Thursday meeting one last time before taking any action here.

In the meantime, I would like to see that some of these patches are at least submitted to upstream. Things like adding headers and that sort of thing aren't specific-to-vcpkg and we want to minimize the amount of patches, as they both create maintenance burden for us and take away agency of upstream authors. (I won't block merging over that though)

New port checklist:

* Check the name against https://repology.org/  
`mdl` already refers to MarkdownLint, there is an `mdl-sdk` pointing to the same thing, so I would prefer that we rename this port to `mdl-sdk`.
* Check the name against Bing/Google. (If the first results aren't C++ related, try "name C++")  
Bing: First hit is for Windows DDK memory descriptor list, 4th hit is for this.
Google: Second hit is for this, but third hit is for a different mdl: https://www.graphics.cornell.edu/online/formats/mdl/iolib/index.html
* Check the source code for optional `find_package`s  
find_package(${__TARGET_ADD_DEPENDENCY_DEPENDS}) followed by an if that effectively makes it REQUIRED  
find_package(Boost QUIET) followed by an if that effectively makes it REQUIRED  
find_package(Threads REQUIRED QUITE) This is just bogus? https://github.com/NVIDIA/MDL-SDK/pull/8  
find_package(Boost QUIET) ditto turned into fatal error right after  
find_package(OpenGL QUIET) in vcpkg.json
find_package(GLEW QUIET) Missing! I think we should add that as an explicit dependency in vcpkg.json?  
find_package(glfw3 QUIET) Ditto missing!  
find_package (Python COMPONENTS Interpreter Development) Seems to be missing?  
find_package(Qt5 COMPONENTS Core HINTS ${Qt5_DIR}) Missing, can you confirm this is shut off by `-DMDL_ENABLE_QT_EXAMPLES:BOOL=OFF`?  
find_package(LibXml2) Missing!  
find_package(Backtrace) Missing!  
find_package(OCaml) Missing! Can we add `-DLLVM_ENABLE_BINDINGS=OFF` or will that damage the port?  
find_package(Subversion) Missing! But probably unused?  
* Check that the versioning scheme and license match what upstream says
Version: OK https://github.com/NVIDIA/MDL-SDK/releases/tag/2021.1.2
License: OK https://github.com/NVIDIA/MDL-SDK/blob/master/LICENSE.md
* Check that the source code comes from the upstream project's authoritative source.
✅
* Check that the generated usage is accurate.
```
mdl provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(unofficial-mdl CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::mdl::mdl_sdk unofficial::mdl::mdl_core)
```
Can you confirm that this is how one is to use that?

2022-08-11 19:24 UTC, BillyONeal commented on ports/mdl/vcpkg.json
> +  "supports": "!arm & !x86 & !(windows & static)",
```suggestion
  "supports": "!arm & !x86 & !(windows & staticcrt)",
```

Does this need to be static or would staticcrt work?

2022-08-11 20:08 UTC, BillyONeal commented
@ras0219-msft, @vicroms, @dan-shaw, @JavierMatosD, and I talked about this today and have the following additional statements:

1. Can a user meaningfully use this without a copy of LLVM 7 themselves? (e.g. should this LLVM 7.x come from the CUDA toolset itself?) We are assuming for purposes of this reply that the answer is no, if it is yes please come back because we need to rediscuss.
2. We are OK with this, and are explicitly saying it isn't like https://github.com/microsoft/vcpkg/pull/23827 , because the downloaded toolchain is not actually used to produce any of the resulting binaries; the toolchain file, flags, etc. the user supplies in their triplet is respected.
3. This situation needs a big comment in the portfile to explain the situation.
4. We would like the name to be `mdl-sdk` for consistency with upstream and https://repology.org/project/mdl-sdk/

We will not bring up the LLVM concern again (as long as the answer to 1 above remains no) and will be happy to merge this once a comment and the outstanding code review nitpicks are resolved.

2022-08-11 21:26 UTC, theblackunknown commented
Thanks for the detailed review and very good questions @BillyONeal   
I am away this week and probably couple of next ones after so there will be either no or slow progress during this time, I'll be back at the beginning of September to answer and tackle the remaining issues.

2022-08-15 19:19 UTC, BillyONeal commented
> * find_package(Threads REQUIRED QUITE) This is just bogus? [NVIDIA/MDL-SDK#8](https://github.com/NVIDIA/MDL-SDK/pull/8)

Upstream merged my fix :). But not in a release yet...

2022-08-29 08:44 UTC, theblackunknown commented
> > * find_package(Threads REQUIRED QUITE) This is just bogus? [NVIDIA/MDL-SDK#8](https://github.com/NVIDIA/MDL-SDK/pull/8)
> 
> Upstream merged my fix :). But not in a release yet...

I have seen it, well done !
They will probably have it in the next minor release.

2022-08-29 08:45 UTC, theblackunknown commented
> 4. We would like the name to be mdl-sdk for consistency with upstream and https://repology.org/project/mdl-sdk/

Good observation, I'll incorporate this change in my next change set.

2022-08-29 08:54 UTC, theblackunknown commented on ports/mdl/005-missing-link-windows-crypt-libraries.patch
> ++)
I have dig this one a bit more: when using `boost-uuid` on Windows, the random provider is set to use `bcrypt` library [1], however the way boost port is set up there is no auto link of this system library [2]. 
This means we should either inject this system dependency ourselves when using `boost-uuid` on Windows, or rely on `BOOST_UUID_FORCE_AUTO_LINK` which achieve the same in this case [3].

[1] https://github.com/boostorg/uuid/blob/94381580f91db51fe9cf7e38f77b4f17abd0f202/include/boost/uuid/detail/random_provider_detect_platform.hpp#L43-L52
[2] https://github.com/microsoft/vcpkg/blob/e85b5bb95a14ff7e014601e88a8dc2fea6798e33/ports/boost-config/portfile.cmake#L13
[3] https://github.com/boostorg/uuid/blob/94381580f91db51fe9cf7e38f77b4f17abd0f202/include/boost/uuid/detail/random_provider_bcrypt.ipp#L20-L29

2022-08-29 08:58 UTC, theblackunknown commented on ports/mdl/005-missing-link-windows-crypt-libraries.patch
> ++)
Looking at `scripts/cmake/vcpkg_common_definitions.cmake`, I see that `bcrypt` is included in  `VCPKG_SYSTEM_LIBRARIES`. But I do not know whether this should be enough to force linkage of those libraries when compiling `mdl-sdk`, any thoughts ?

https://github.com/microsoft/vcpkg/blob/e85b5bb95a14ff7e014601e88a8dc2fea6798e33/scripts/cmake/vcpkg_common_definitions.cmake#L168

When linking `mdl-sdk` library, here is the line which fails:

```
FAILED: src/prod/lib/mdl_sdk/Debug/libmdl_sdk.dll src/prod/lib/mdl_sdk/Debug/mdl_sdk.lib 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe  @CMakeFiles\prod-lib-mdl_sdk.rsp  /out:src\prod\lib\mdl_sdk\Debug\libmdl_sdk.dll /implib:src\prod\lib\mdl_sdk\Debug\mdl_sdk.lib /pdb:src\prod\lib\mdl_sdk\Debug\libmdl_sdk.pdb /dll /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe @CMakeFiles\prod-lib-mdl_sdk.rsp /out:src\prod\lib\mdl_sdk\Debug\libmdl_sdk.dll /implib:src\prod\lib\mdl_sdk\Debug\mdl_sdk.lib /pdb:src\prod\lib\mdl_sdk\Debug\libmdl_sdk.pdb /dll /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir/intermediate.manifest src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library src\prod\lib\mdl_sdk\Debug\mdl_sdk.lib and object src\prod\lib\mdl_sdk\Debug\mdl_sdk.exp
io-scene.lib(mdl_elements_utilities.cpp.obj) : error LNK2019: unresolved external symbol BCryptCloseAlgorithmProvider referenced in function "private: void __cdecl boost::uuids::detail::random_provider_base::destroy(void)" (?destroy@random_provider_base@detail@uuids@boost@@AEAAXXZ)
io-scene.lib(mdl_elements_utilities.cpp.obj) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function "public: void __cdecl boost::uuids::detail::random_provider_base::get_random_bytes(void *,unsigned __int64)" (?get_random_bytes@random_provider_base@detail@uuids@boost@@QEAAXPEAX_K@Z)
io-scene.lib(mdl_elements_utilities.cpp.obj) : error LNK2019: unresolved external symbol BCryptOpenAlgorithmProvider referenced in function "public: __cdecl boost::uuids::detail::random_provider_base::random_provider_base(void)" (??0random_provider_base@detail@uuids@boost@@QEAA@XZ)
src\prod\lib\mdl_sdk\Debug\libmdl_sdk.dll : fatal error LNK1120: 3 unresolved externals
```

Extracted command line for convenience
```
"C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe
@CMakeFiles\prod-lib-mdl_sdk.rsp
/out:src\prod\lib\mdl_sdk\Debug\libmdl_sdk.dll
/implib:src\prod\lib\mdl_sdk\Debug\mdl_sdk.lib
/pdb:src\prod\lib\mdl_sdk\Debug\libmdl_sdk.pdb
/dll
/version:0.0
/machine:x64
/nologo
/debug
/INCREMENTAL
/MANIFEST
/MANIFESTFILE:src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir/intermediate.manifest
```

And `prod-lib-mdl_sdk.rsp` content for convenience too 
```
src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir\mdl_sdk_factory.cpp.obj
src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir\mdl_sdk_required_modules.cpp.obj
src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir\mdl_sdk_stubs.cpp.obj
src\prod\lib\mdl_sdk\CMakeFiles\prod-lib-mdl_sdk.dir\mdl_sdk.rc.res
dbghelp.lib
include\Debug\include-mi.lib
src\api\api\mdl\Debug\api-api-mdl.lib
src\base\data\attr\Debug\base-data-attr.lib
src\base\data\db\Debug\base-data-db.lib
src\base\data\dblight\Debug\base-data-dblight.lib
src\base\data\serial\Debug\base-data-serial.lib
src\base\hal\disk\Debug\base-hal-disk.lib
src\base\hal\hal\Debug\base-hal-hal.lib
src\base\hal\link\Debug\base-hal-link.lib
src\base\hal\time\Debug\base-hal-time.lib
src\base\lib\config\Debug\base-lib-config.lib
src\base\lib\cont\Debug\base-lib-cont.lib
src\base\lib\mem\Debug\base-lib-mem.lib
src\base\lib\path\Debug\base-lib-path.lib
src\base\lib\plug\Debug\base-lib-plug.lib
src\base\lib\log\Debug\base-lib-log.lib
src\base\lib\libzip\Debug\base-lib-libzip.lib
src\base\lib\tinyxml2\Debug\base-lib-tinyxml2.lib
src\base\lib\zlib\Debug\base-lib-zlib.lib
src\base\util\string_utils\Debug\base-util-string_utils.lib
src\base\util\registry\Debug\base-util-registry.lib
src\base\system\main\Debug\base-system-main.lib
src\base\system\stlext\Debug\base-system-stlext.lib
src\base\system\version\Debug\base-system-version.lib
src\io\image\Debug\io-image.lib
src\io\scene\Debug\io-scene.lib
src\mdl\codegenerators\generator_dag\Debug\mdl-codegenerators-generator_dag.lib
src\mdl\codegenerators\generator_code\Debug\mdl-codegenerators-generator_code.lib
src\mdl\compiler\compilercore\Debug\mdl-compiler-compilercore.lib
src\mdl\compiler\compiler_hlsl\Debug\mdl-compiler-compiler_hlsl.lib
src\mdl\integration\mdlnr\Debug\mdl-integration-mdlnr.lib
src\mdl\integration\i18n\Debug\mdl-integration-i18n.lib
src\mdl\jit\generator_jit\Debug\mdl-jit-generator_jit.lib
src\mdl\no_glsl\generator_stub\Debug\mdl-no_glsl-generator_stub.lib
src\mdl\runtime\Debug\mdl-runtime.lib
src\render\mdl\backends\Debug\render-mdl-backends.lib
src\render\mdl\runtime\Debug\render-mdl-runtime.lib
src\mdl\jit\llvm\dist\lib\LLVMLinker.lib
src\mdl\jit\llvm\dist\lib\LLVMipo.lib
src\mdl\jit\llvm\dist\lib\LLVMVectorize.lib
src\mdl\jit\llvm\dist\lib\LLVMBitWriter.lib
src\mdl\jit\llvm\dist\lib\LLVMNVPTXCodeGen.lib
src\mdl\jit\llvm\dist\lib\LLVMNVPTXDesc.lib
src\mdl\jit\llvm\dist\lib\LLVMNVPTXInfo.lib
src\mdl\jit\llvm\dist\lib\LLVMNVPTXAsmPrinter.lib
src\mdl\jit\llvm\dist\lib\LLVMTableGen.lib
src\mdl\jit\llvm\dist\lib\LLVMDebugInfoDWARF.lib
src\mdl\jit\llvm\dist\lib\LLVMDebugInfoPDB.lib
src\mdl\jit\llvm\dist\lib\LLVMOption.lib
src\mdl\jit\llvm\dist\lib\LLVMX86Disassembler.lib
src\mdl\jit\llvm\dist\lib\LLVMX86AsmParser.lib
src\mdl\jit\llvm\dist\lib\LLVMX86CodeGen.lib
src\mdl\jit\llvm\dist\lib\LLVMGlobalISel.lib
src\mdl\jit\llvm\dist\lib\LLVMSelectionDAG.lib
src\mdl\jit\llvm\dist\lib\LLVMAsmPrinter.lib
src\mdl\jit\llvm\dist\lib\LLVMDebugInfoCodeView.lib
src\mdl\jit\llvm\dist\lib\LLVMX86Desc.lib
src\mdl\jit\llvm\dist\lib\LLVMDemangle.lib
src\mdl\jit\llvm\dist\lib\LLVMX86Info.lib
src\mdl\jit\llvm\dist\lib\LLVMX86AsmPrinter.lib
src\mdl\jit\llvm\dist\lib\LLVMX86Utils.lib
src\mdl\jit\llvm\dist\lib\LLVMIRReader.lib
src\mdl\jit\llvm\dist\lib\LLVMBitReader.lib
src\mdl\jit\llvm\dist\lib\LLVMAsmParser.lib
src\mdl\jit\llvm\dist\lib\LLVMMCDisassembler.lib
src\mdl\jit\llvm\dist\lib\LLVMMCParser.lib
src\mdl\jit\llvm\dist\lib\LLVMInstrumentation.lib
src\mdl\jit\llvm\dist\lib\LLVMMCJIT.lib
src\mdl\jit\llvm\dist\lib\LLVMOrcJIT.lib
src\mdl\jit\llvm\dist\lib\LLVMCodeGen.lib
src\mdl\jit\llvm\dist\lib\LLVMScalarOpts.lib
src\mdl\jit\llvm\dist\lib\LLVMInstCombine.lib
src\mdl\jit\llvm\dist\lib\LLVMAggressiveInstCombine.lib
src\mdl\jit\llvm\dist\lib\LLVMTransformUtils.lib
src\mdl\jit\llvm\dist\lib\LLVMAnalysis.lib
src\mdl\jit\llvm\dist\lib\LLVMProfileData.lib
src\mdl\jit\llvm\dist\lib\LLVMRuntimeDyld.lib
src\mdl\jit\llvm\dist\lib\LLVMExecutionEngine.lib
src\mdl\jit\llvm\dist\lib\LLVMTarget.lib
src\mdl\jit\llvm\dist\lib\LLVMMC.lib
src\mdl\jit\llvm\dist\lib\LLVMObject.lib
src\mdl\jit\llvm\dist\lib\LLVMCore.lib
src\mdl\jit\llvm\dist\lib\LLVMBinaryFormat.lib
src\mdl\jit\llvm\dist\lib\LLVMSupport.lib
src\mdl\jit\libbsdf\Debug\mdl-jit-libbsdf.lib
src\mdl\jit\libmdlrt\Debug\mdl-jit-libmdlrt.lib
src\base\data\serial\Debug\base-data-serial.lib
src\base\system\version\Debug\base-system-version.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
```

2022-08-29 09:12 UTC, theblackunknown commented
> Check that the generated usage is accurate.
mdl provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(unofficial-mdl CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::mdl::mdl_sdk unofficial::mdl::mdl_core)
Can you confirm that this is how one is to use that?

To be fully correct, we should one or the other but noy both, I'll craft a dedicated `usage` file to clarify this.
If you want to see it in action, here is a work in progress repo of mine to test this port (including proper bitcode generation) : https://github.com/theblackunknown-experiments/test-vcpkg-mdl

2022-08-29 12:12 UTC, theblackunknown commented on ports/mdl/vcpkg.json
> +  "supports": "!arm & !x86 & !(windows & static)",
Unfortunately it does not work either: current MDL-SDK upstream expects the `freeimage` dependency provided as a shared library, the issue is not solely about library linkage vs crt linkage.
I plan to address this limitation as a follow-up of this PR as the change set is already quite large.

2022-08-29 13:24 UTC, theblackunknown commented on ports/mdl/006-guard-nonexisting-targets.patch
> +     yaml-bench
Minimized and submitted upstream NVIDIA/MDL-SDK#10

2022-08-29 13:37 UTC, theblackunknown commented on ports/mdl/002-install-rules.patch
> ++    endif()
Done.

2022-08-29 13:39 UTC, theblackunknown commented on ports/mdl/004-missing-std-includes.patch
> +diff --git a/src/api/api/neuray/neuray_class_factory.h b/src/api/api/neuray/neuray_class_factory.h
It seems to be already fixed in the latest MDL-SDK release, I suggest to keep this patch and delete it once I upgrade the port.

2022-08-29 13:50 UTC, theblackunknown commented on ports/mdl/007-plugin-options.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
Done. NVIDIA/MDL-SDK#11

2022-08-29 20:10 UTC, theblackunknown commented
Using `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` to disable all optional packages you listed, the only hit I got is `find_package(Backtrace)`
I do not know a lot but it looks like a system lib and hence we may not want to disable it ? or can it be provided by a port ?
In anycase, this does not look like a requirement to build `mdl-sdk` port.

vcpkg install exceprt
```
CMake Warning at installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:302 (message):
  The following variables are not used in CMakeLists.txt:

      CMAKE_DISABLE_FIND_PACKAGE_GLEW
      CMAKE_DISABLE_FIND_PACKAGE_LibXml2
      CMAKE_DISABLE_FIND_PACKAGE_OCaml
      CMAKE_DISABLE_FIND_PACKAGE_OpenGL
      CMAKE_DISABLE_FIND_PACKAGE_Qt5
      CMAKE_DISABLE_FIND_PACKAGE_Subversion
      CMAKE_DISABLE_FIND_PACKAGE_glfw3
```

Last but not least, is it worth it to update the portfile with all those `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` anyway ?

2022-09-09 08:42 UTC, Cheney-W commented
@BillyONeal 
Could you please take a look this PR again? Thank you!

2022-09-17 19:17 UTC, theblackunknown commented
@BillyONeal can ask you to have another look when you get a chance please?

2022-09-28 21:51 UTC, BillyONeal commented
Sorry it's taken a long time to reply to this; I've been under a whole bunch of guns for the artifacts feature and haven't been able to respond much. 

> Using `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` to disable all optional packages you listed, the only hit I got is `find_package(Backtrace)` I do not know a lot but it looks like a system lib and hence we may not want to disable it ? or can it be provided by a port ? In anycase, this does not look like a requirement to build `mdl-sdk` port.
> 
> vcpkg install excerpt
> 
> ```
> CMake Warning at installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:302 (message):
>   The following variables are not used in CMakeLists.txt:
> 
>       CMAKE_DISABLE_FIND_PACKAGE_GLEW
>       CMAKE_DISABLE_FIND_PACKAGE_LibXml2
>       CMAKE_DISABLE_FIND_PACKAGE_OCaml
>       CMAKE_DISABLE_FIND_PACKAGE_OpenGL
>       CMAKE_DISABLE_FIND_PACKAGE_Qt5
>       CMAKE_DISABLE_FIND_PACKAGE_Subversion
>       CMAKE_DISABLE_FIND_PACKAGE_glfw3
> ```
> 
> Last but not least, is it worth it to update the portfile with all those `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` anyway ?

Perhaps what I noticed with grep isn't active unless some other conditions are met; I still would feel better about including them, even if they need to be tagged with maybe_unused. We have a long history of merging megaprojects like this and then kicking ourselves for several months afterward as optional dependencies cause "random failures" in CI because the install order differs, or that sort of thing.

2022-10-08 14:09 UTC, theblackunknown commented
> Sorry it's taken a long time to reply to this; I've been under a whole bunch of guns for the artifacts feature and haven't been able to respond much.

No worry about this @BillyONeal , I must say that I am very eager to play with vcpkg tool and the artifact feature !

I have added the `CMAKE_DISABLE_FIND_PACKAGE` you requested.

2022-10-10 08:18 UTC, Cheney-W commented on ports/mdl-sdk/portfile.cmake
> +        ${FEATURE_OPTIONS}
```suggestion
        ${FEATURE_OPTIONS}
        
    MAYBE_UNUSED_VARIABLES
        -DCMAKE_DISABLE_FIND_PACKAGE_GLEW=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_glfw3=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_LibXml2=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_OCaml=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_OpenGL=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_Qt5=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_Subversion=ON
```

2022-10-13 18:17 UTC, merged

2022-10-14 08:17 UTC, theblackunknown commented
Thank you very much to all reviewers for your help and patience on this one !

2024-04-17 07:25 UTC, kevle commented on ports/mdl-sdk/portfile.cmake
> +        ${FEATURE_OPTIONS}
This came up after searching for "MAYBE_UNUSED_VARIABLES[\r\n\s]*-D" because of [this](https://github.com/microsoft/vcpkg/pull/36124#discussion_r1567897651). 
Not sure if this needs to be changed.

2024-04-18 06:31 UTC, dg0yt commented on ports/mdl-sdk/portfile.cmake
> +        ${FEATURE_OPTIONS}
> Not sure if this needs to be changed.

Of course it needs a change.
And we must catch the errors proposed by the reviewers: #38249