[magic-enum] Update to v0.8.0
microsoft/vcpkg pull request #24646
Opened 2022-05-10 19:58 UTC by Neargye

**Describe the pull request**

- #### What does your PR fix?

Update magic-enum to v0.8.0

Changelog:
https://github.com/Neargye/magic_enum/releases/tag/v0.8.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
 All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-05-10 20:18 UTC, Thomas1664 requested changes
Additionally, please put paths in cmake inside quotes and remove deprecated cmake as the bot suggested.

2022-05-10 20:18 UTC, Thomas1664 commented on ports/magic-enum/vcpkg.json
>    "port-version": 1,
```suggestion
  "version-string": "0.8.0",
```

2022-05-10 20:18 UTC, Thomas1664 commented on versions/m-/magic-enum.json
> +      "port-version": 1
```suggestion
      "port-version": 0
```

2022-05-10 20:18 UTC, Thomas1664 commented on ports/magic-enum/vcpkg.json
>    "port-version": 1,
```suggestion
  "version": "0.8.0",
```

2022-05-10 20:18 UTC, Thomas1664 commented on ports/magic-enum/portfile.cmake
>      PREFER_NINJA
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}

```

2022-05-10 20:26 UTC, Neargye commented
> Additionally, please put paths in cmake inside quotes.

Which path are you talking about?

2022-05-10 20:28 UTC, Thomas1664 commented on ports/magic-enum/portfile.cmake
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum TARGET_PATH share/magic_enum)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug" "${CURRENT_PACKAGES_DIR}/lib")


```
e.g. this and line 27 as well

2022-05-10 20:29 UTC, Thomas1664 commented on ports/magic-enum/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"

```

2022-05-10 20:37 UTC, Neargye commented
I need run `./vcpkg x-add-version --all --overwrite-version` ?

2022-05-10 20:55 UTC, Thomas1664 commented
> I need run `./vcpkg x-add-version --all --overwrite-version` ?

Yes

2022-05-10 20:57 UTC, Thomas1664 commented
You need to add those dependencies:

> In the ports that use the new function, you have to add the corresponding dependencies:
> 
> ```json
> {
>   "name": "vcpkg-cmake",
>   "host": true
> },
> {
>   "name": "vcpkg-cmake-config",
>   "host": true
> }
> ```

2022-05-10 20:59 UTC, Thomas1664 commented on versions/m-/magic-enum.json
> +      "version-string": "0.8.0",
```suggestion
      "version": "0.8.0",
```

2022-05-10 21:01 UTC, Thomas1664 commented
> e.g. this and line 27 as well

Please add quotes in line 27 as well.

2022-05-10 21:50 UTC, Thomas1664 commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/magic_enum" TARGET_PATH "share/magic_enum")
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum PACKAGE_NAME magic_enum)

```

This should fix CI

2022-05-10 21:51 UTC, Neargye commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/magic_enum" TARGET_PATH "share/magic_enum")
need quotes?

2022-05-10 21:53 UTC, Thomas1664 commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/magic_enum" TARGET_PATH "share/magic_enum")
No because this path doesn't include a variable expansion like `$[VCPKG_CURRENT_PACKAGES_DIR}`

2022-05-11 01:54 UTC, JonLiu1993 requested changes

2022-05-11 01:54 UTC, JonLiu1993 commented on ports/magic-enum/portfile.cmake
>      OPTIONS
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
```

2022-05-11 01:54 UTC, JonLiu1993 commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum PACKAGE_NAME magic_enum)
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum)
```

2022-05-11 01:54 UTC, JonLiu1993 commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum PACKAGE_NAME magic_enum)
@Neargye ,PACKAGE_NAME defaults to ${PORT}, you can refer to [this ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/ports/vcpkg-cmake-config/vcpkg_cmake_config_fixup.md)

2022-05-11 08:38 UTC, Neargye commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum PACKAGE_NAME magic_enum)
`"name": "magic-enum"` as I remember it's problem, name with dash, and the library with underscore `magic_enum`

2022-05-11 08:44 UTC, JonLiu1993 commented on ports/magic-enum/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/magic_enum PACKAGE_NAME magic_enum)
@Neargye ,OK, thanks for your clarify.

2022-05-11 08:46 UTC, JonLiu1993 commented on ports/magic-enum/portfile.cmake
>      OPTIONS
@Neargye ,Please delete this extra blank line

2022-05-11 08:53 UTC, JonLiu1993 approved these changes

2022-05-11 23:46 UTC, merged

2022-05-11 23:47 UTC, BillyONeal commented
Thanks for the update and modernization!