Provide port for Deshaw Research's Random123 implementation
microsoft/vcpkg pull request #24716
Opened 2022-05-14 22:52 UTC by KineticTheory

**Provide port for Deshaw Research's Random123 implementation**

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>
This is a header only package.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-05-15 10:50 UTC, Thomas1664 commented on ports/random123/vcpkg.json
> +  "version-string": "1.14.0",
```suggestion
  "version": "1.14.0",
```

2022-05-15 10:50 UTC, Thomas1664 commented on ports/random123/portfile.cmake
> +)
Please use [vcpkg_from_github](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_from_github.md) instead.

2022-05-15 20:55 UTC, KineticTheory commented on ports/random123/portfile.cmake
> +)
Thanks for the feedback.  Syntax corrected in [4a026fd](https://github.com/microsoft/vcpkg/pull/24716/commits/4a026fdc693bf155dd720816381786d39e2799e2)

2022-05-16 03:08 UTC, LilyWangLL commented
Thanks for adding this port, please run command `vcpkg x-add-version random123 --overwrite-version` on vcpkg window.

2022-05-16 07:23 UTC, LilyWangLL requested changes

2022-05-16 07:23 UTC, LilyWangLL commented on ports/random123/portfile.cmake
> +     DESTINATION ${CURRENT_PACKAGES_DIR}/include/${PORT} )
```suggestion
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}" )
```

2022-05-16 07:23 UTC, LilyWangLL commented on ports/random123/portfile.cmake
> +     DESTINATION ${CURRENT_PACKAGES_DIR}/include/${PORT} )
```suggestion
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}" )
```

2022-05-16 07:23 UTC, LilyWangLL commented on ports/random123/portfile.cmake
> +     DESTINATION ${CURRENT_PACKAGES_DIR}/include/${PORT} )
```suggestion
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}" )
```

2022-05-16 07:23 UTC, LilyWangLL commented on ports/random123/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2022-05-22 18:50 UTC, KineticTheory commented
> Thanks for adding this port, please run command `vcpkg x-add-version random123 --overwrite-version` on vcpkg window.

I applied the fixes you requested.  Thank you for providing feedback.

2022-05-22 19:46 UTC, Thomas1664 commented
> I applied the fixes you requested. Thank you for providing feedback.

This didn't work because you modified the portfile without committing this change **before** running `x-add-version`. You have to run `vcpkg x-add-version random123 --overwrite-version` again.

2022-05-22 19:51 UTC, KineticTheory commented
> vcpkg x-add-version random123 --overwrite-version

I didn't understand that they needed to be in separate commits.  I updated the version again.

2022-05-24 01:00 UTC, KineticTheory commented
> You have modified or added at least one vcpkg.json where you should check the `license` field.

The software uses as custom license, so I added `license: null`.

2022-06-10 06:09 UTC, LilyWangLL commented
Sorry I am late, I did a little change, just formatted the portfile.cmake and merged master, added "" for absolute path.

2022-06-10 06:10 UTC, LilyWangLL approved these changes

2022-06-10 17:19 UTC, ras0219-msft requested changes
Thanks for the PR!

2022-06-10 17:19 UTC, ras0219-msft commented on ports/random123/portfile.cmake
> +     DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
It looks like the header path is intended to be capitalized.

```suggestion
file(GLOB header_files
    "${SOURCE_PATH}/include/Random123/*.h"
    "${SOURCE_PATH}/include/Random123/*.hpp")
file(COPY ${header_files}
    "${SOURCE_PATH}/include/Random123/features"
    "${SOURCE_PATH}/include/Random123/conventional"
    DESTINATION "${CURRENT_PACKAGES_DIR}/include/Random123")
```

2022-06-10 17:19 UTC, ras0219-msft commented on ports/random123/vcpkg.json
> +  "license": null
```suggestion
  "license": "BSD-3-Clause"
```

2022-06-10 17:19 UTC, ras0219-msft commented on ports/random123/portfile.cmake
> +  REF "v${VERSION}"
```suggestion
  REF "v1.14.0"
```

2022-06-10 17:19 UTC, ras0219-msft commented on ports/random123/portfile.cmake
> +
```suggestion
```

2022-06-15 20:40 UTC, merged