[v8] Update to Stable version 10.1.124.12
microsoft/vcpkg pull request #24817
Opened 2022-05-19 22:24 UTC by Kwizatz

Update v8 to Stable version 10.1.124.12

- #### What does your PR fix?
Fixes #24510

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

Windows, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-05-19 22:48 UTC, Kwizatz commented
I tested this on Windows 11, MSVC 2022, WinSDK 10.0.22000.194, seems the CI is still running on 10.0.19041.685.

2022-05-20 02:38 UTC, JackBoosY commented
> I tested this on Windows 11, MSVC 2022, WinSDK 10.0.22000.194, seems the CI is still running on 10.0.19041.685.

Is this update requires WinSDK 10.0.22000.194?

2022-05-20 04:15 UTC, Kwizatz commented
> > I tested this on Windows 11, MSVC 2022, WinSDK 10.0.22000.194, seems the CI is still running on 10.0.19041.685.
> 
> Is this update requires WinSDK 10.0.22000.194?

I think so

2022-05-20 05:54 UTC, JackBoosY commented
cc @BillyONeal

2022-05-20 21:18 UTC, BillyONeal commented
Do you know if that SDK version needs to be installed to the exclusion of others or can we just add it?

2022-05-20 21:43 UTC, Kwizatz commented
> Do you know if that SDK version needs to be installed to the exclusion of others or can we just add it?

You can just add it, I have 10.0.19x, 10.0.20x and 10.0.22x concurrently on my dev machine, the WindowsSDKVersion on the environment should be that of 10.0.22 though.

2022-06-24 08:32 UTC, JackBoosY commented
Ready for review now?

2022-06-25 05:30 UTC, Kwizatz commented
> Ready for review now?

I think so.

2022-06-27 02:58 UTC, JackBoosY requested changes

2022-06-27 02:58 UTC, JackBoosY commented on ports/v8/vcpkg.json
> +  "port-version": 1,
```suggestion
```

2022-06-27 02:58 UTC, JackBoosY commented on ports/v8/v8.patch
> +diff --git a/include/v8-cppgc.h b/include/v8-cppgc.h
Is there any modification for this upstream?

2022-06-27 02:58 UTC, JackBoosY commented on ports/v8/v8.patch
> +     LocalIsolate*, Handle<Object>, Handle<Object>);
Same as above.

2022-06-27 04:28 UTC, Kwizatz commented on ports/v8/v8.patch
> +     LocalIsolate*, Handle<Object>, Handle<Object>);
I remember these being very old changes, I'll revert them and see what happens, the initializers were needed for component (DLL) builds, otherwise the linker would complain, and the other was a similar situation, V8_EXPORT_PRIVATE is dll(import/export) and the linker complained as well.

I'll take a look, a lot has changed.

2022-06-27 18:52 UTC, BillyONeal commented on scripts/ci.baseline.txt
> +# but it must have installed Windows SDK 10.0.22000.194
That SDK is installed on the machines now, so this should be working? Note that =fails aren't tested in PR builds.

2022-06-27 18:55 UTC, mehdialiakbar31 commented
> Update v8 to Stable version 10.1.124.12
> 
> * #### What does your PR fix?
> 
> Fixes #24510
> 
> * #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
> 
> Windows, Yes
> 
> * #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
>   Yes
> * #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
>   Yes
> 
> **If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-06-29 02:53 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +# but it must have installed Windows SDK 10.0.22000.194
Please remove the `v8:TRIPLET=fail` in the following content to test this PR.

2022-07-15 05:55 UTC, JackBoosY commented
Convert this PR to draft since there is no progress.

2022-07-18 01:16 UTC, Kwizatz commented on ports/v8/v8.patch
> +diff --git a/include/v8-cppgc.h b/include/v8-cppgc.h
I am not sure which part are you asking about, IIRC this is a specific issue on MSVC22 being stricter than clang and MSVC19 on deleted constructors in base classes, it may have a similar patch upstream, but not on this version.

2022-07-18 01:18 UTC, Kwizatz commented on scripts/ci.baseline.txt
> +# but it must have installed Windows SDK 10.0.22000.194
Done.

2022-07-18 01:58 UTC, Kwizatz commented
Looks like the SDK installed is 10.0.22621.0, is it installed side by side with 10.0.2000.0? I installed 10.0.22621.0 side by side and I am not seeing these errors:

`[1/1354] CXX obj/cppgc_base/object-size-trait.obj
FAILED: obj/cppgc_base/object-size-trait.obj 
ninja -t msvc -e environment.x64 -- "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64/cl.exe" /c ../src/c77ccc7593-16c1b401a7.clean/src/heap/cppgc/object-size-trait.cc /Foobj/cppgc_base/object-size-trait.obj /nologo /showIncludes -DUSE_AURA=1 -D_CRT_NONSTDC_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DCOMPONENT_BUILD -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_FE -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DCPPGC_VERIFY_HEAP -DENABLE_DISASSEMBLER -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DOBJECT_PRINT -DV8_TRACE_MAPS -DV8_ENABLE_ALLOCATION_TIMEOUT -DV8_ENABLE_FORCE_SLOW_PATH -DV8_ENABLE_DOUBLE_CONST_STORE_CHECK -DV8_INTL_SUPPORT -DENABLE_HANDLE_ZAPPING -DV8_CODE_COMMENTS -DV8_ENABLE_DEBUG_CODE -DV8_ENABLE_HEAP_SNAPSHOT_VERIFY -DV8_SNAPSHOT_NATIVE_CODE_COUNTERS -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_ATOMIC_OBJECT_FIELD_WRITES -DV8_ENABLE_LAZY_SOURCE_POSITIONS -DV8_SHARED_RO_HEAP -DV8_WIN64_UNWINDING_INFO -DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH -DV8_SHORT_BUILTIN_CALLS -DV8_EXTERNAL_CODE_SPACE -DV8_ENABLE_MAGLEV -DV8_ENABLE_SYSTEM_INSTRUMENTATION -DV8_ENABLE_WEBASSEMBLY -DV8_ALLOCATION_FOLDING -DV8_ALLOCATION_SITE_TRACKING -DV8_ADVANCED_BIGINT_ALGORITHMS -DV8_ENABLE_CHECKS -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DV8_IMMINENT_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DV8_TARGET_ARCH_X64 -DV8_HAVE_TARGET_OS -DV8_TARGET_OS_WIN -DDEBUG -DBUILDING_V8_SHARED -DUSING_V8_BASE_SHARED -DUSING_V8_PLATFORM_SHARED -I../src/c77ccc7593-16c1b401a7.clean -Igen -I../src/c77ccc7593-16c1b401a7.clean/include -Igen/include /WX /wd4244 /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /Zi /MDd /wd4245 /wd4267 /wd4324 /wd4701 /wd4702 /wd4703 /wd4709 /wd4714 /wd4715 /wd4718 /wd4723 /wd4724 /wd4800 /wd4506 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /O2 /Ob3 /Oy- /Zc:inline /Gw /std:c++17 /Zc:alignedNew- /TP /GR- /Fd"obj/cppgc_base_cc.pdb"
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt.h(19): fatal error C1083: Cannot open include file: 'winapifamily.h': No such file or directory`

2022-07-18 23:21 UTC, BillyONeal commented
> Looks like the SDK installed is 10.0.22621.0, is it installed side by side with 10.0.2000.0?

I don't think so based on:

https://github.com/microsoft/vcpkg/blob/678c0ea99b778c7871e648182d61e1db7cee8892/scripts/azure-pipelines/windows/deploy-visual-studio.ps1#L21

2022-07-19 05:21 UTC, Kwizatz commented
> > Looks like the SDK installed is 10.0.22621.0, is it installed side by side with 10.0.2000.0?
> 
> I don't think so based on:
> 
> https://github.com/microsoft/vcpkg/blob/678c0ea99b778c7871e648182d61e1db7cee8892/scripts/azure-pipelines/windows/deploy-visual-studio.ps1#L21

Ok, that's one problem, there is also a link issue on the release build.

2022-08-19 07:58 UTC, JackBoosY commented
Any progress here?

2022-09-16 08:31 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please ping me to reopen if work is still being done.

2022-09-16 08:31 UTC, closed without merging

2022-09-19 22:23 UTC, Kwizatz commented
Yeah, this is fine, the PR works but CI does not, may need to just let V8 catch up to the latest SDK.