boringssl: Add a patch to disable another warning breaking build for …
microsoft/vcpkg pull request #24899
Opened 2022-05-24 16:21 UTC by rpavlik

…VS2022.

Filed upstream as https://bugs.chromium.org/p/boringssl/issues/detail?id=495

**Describe the pull request**

- #### What does your PR fix?
Build of boringssl broken as noted in https://github.com/microsoft/vcpkg/pull/24310#issuecomment-1132294821

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
Only affects windows. Did not update the baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Well, it adds a patch for a non-vcpkg-specific problem, but I did file it upstream too.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
yes

2022-05-25 10:57 UTC, LilyWangLL requested changes

2022-05-25 10:57 UTC, LilyWangLL commented on ports/boringssl/portfile.cmake
>  vcpkg_configure_cmake(
```suggestion
vcpkg_cmake_configure(
```
`vcpkg_configure_cmake` has been deprecated, and please also remove `PREFER_NINJA`. Change `vcpkg_install_cmake()` to `vcpkg_cmake_install()`

2022-05-25 10:59 UTC, LilyWangLL commented on ports/boringssl/portfile.cmake
>  vcpkg_configure_cmake(
Also add dependency to vcpkg.json
```
"dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    }
]
```

2022-05-27 06:17 UTC, LilyWangLL commented
Ping @rpavlik

2022-05-28 03:43 UTC, rpavlik commented
Haven't had time to do the requested extra maintenance, and won't for a couple of weeks.

2022-05-30 07:38 UTC, LilyWangLL approved these changes

2022-05-31 22:08 UTC, ras0219-msft requested changes
Thanks for the PR!

2022-05-31 22:08 UTC, ras0219-msft commented on ports/boringssl/0003-Disable-C4191-warning-to-fix-VS2022-build.patch
> ++      "C4191" # Unsafe cast (we use it as a type-erased type) - see https://bugs.chromium.org/p/boringssl/issues/detail?id=495
Could you instead change this patch to just remove `-WX` and `-Werror` from this file? vcpkg policy is to never build with warnings-as-errors -- it just causes build breaks for customers on compiler upgrades.

2022-05-31 22:09 UTC, ras0219-msft commented on ports/boringssl/0003-Disable-C4191-warning-to-fix-VS2022-build.patch
> ++      "C4191" # Unsafe cast (we use it as a type-erased type) - see https://bugs.chromium.org/p/boringssl/issues/detail?id=495
@LilyWangLL

2022-06-01 06:21 UTC, LilyWangLL commented on ports/boringssl/0003-Disable-C4191-warning-to-fix-VS2022-build.patch
> ++      "C4191" # Unsafe cast (we use it as a type-erased type) - see https://bugs.chromium.org/p/boringssl/issues/detail?id=495
Done.

2022-06-02 19:55 UTC, ras0219-msft approved these changes
Thanks for the PR!

2022-06-02 19:55 UTC, merged