[restinio] Update to 0.6.15
microsoft/vcpkg pull request #24936
Opened 2022-05-26 09:34 UTC by eao197

RESTinio updated to the latest version.

2022-05-26 15:10 UTC, Thomas1664 commented on ports/restinio/vcpkg.json
>    "port-version": 1,
```suggestion
  "version": "0.6.15",
```

2022-05-26 22:27 UTC, ras0219-msft requested changes
Thanks for the update!

2022-05-26 22:27 UTC, ras0219-msft commented on versions/r-/restinio.json
> +    {
PRs should only ever add one version to the database. Can you run:

```
git checkout 762992cd6118b44ef6ddfab6d2410026c96b5122~ -- versions
./vcpkg x-add-version restinio
git commit -m "Remove additional version entry" versions
```

2022-05-27 04:51 UTC, eao197 commented on versions/r-/restinio.json
> +    {
Done.

2022-05-27 05:43 UTC, FrankXie05 approved these changes

2022-05-27 23:37 UTC, ras0219-msft approved these changes

2022-05-27 23:37 UTC, merged