[getopt-win32] ARM64 support
microsoft/vcpkg pull request #24963
Opened 2022-05-27 13:17 UTC by ZacWalk

**Describe the pull request**

- #### What does your PR fix?
  This PR adds arm64-windows  support for getopt-win32

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  yes - removed arm64-windows

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-06-01 06:31 UTC, Adela0814 requested changes

2022-06-01 06:31 UTC, Adela0814 commented on ports/libirecovery/vcpkg.json
> +  "supports": "!(windows & arm)",
Should this be `!(windows & arm64)`. Port `ideviceinstaller `and `graphviz `are the same.

In fact, I think we need to confirm whether these ports really do not support arm64. If there is only fail in CI due to an issue, we can add it to `ci.baseline` and fix it later.

2022-06-01 06:31 UTC, Adela0814 commented on ports/libirecovery/vcpkg.json
> +  "supports": "!(windows & arm)",
I don't think the `supports `field needs to be added here

2022-06-01 06:31 UTC, Adela0814 commented on ports/getopt-win32/portfile.cmake
> +		arm64.patch
```suggestion
    PATCHES getopt.h.patch 
		arm64.patch
```suggestion
    PATCHES 
        getopt.h.patch 
        arm64.patch

```
```

2022-06-01 06:31 UTC, Adela0814 commented on ports/getopt-win32/portfile.cmake
> +		arm64.patch
```suggestion
    PATCHES getopt.h.patch 
		arm64.patch
```suggestion
    PATCHES 
        getopt.h.patch 
        arm64.patch

```
```

2022-06-02 20:20 UTC, ras0219-msft requested changes
Thanks for the PR!

I noticed that the patch was much, much longer than a simple CMake build, so I've pushed a change to use a replacement buildsystem.

Could you please address the one outstanding comment I have? LGTM after that.

2022-06-02 20:20 UTC, ras0219-msft commented on versions/g-/graphviz.json
> -      "git-tree": "c1f20d0e1aaccb1035e3fe3eb95d005b4161a56e",
Modifying existing `git-tree` entries in the version database is never correct. Any changes to the ports requires incrementing the `port-version` and publishing a new port.

2022-06-03 08:23 UTC, ZacWalk commented
Thanks @ras0219-msft  and @Adela0814.  Using CMAKE is a better approach. Hopefully everything is OK now.

2022-06-03 22:13 UTC, merged

2022-06-03 22:13 UTC, ras0219-msft commented
Yep, LGTM. Thanks!