[jwt-cpp] Update jwt-cpp to 0.6.0
microsoft/vcpkg pull request #25120
Opened 2022-06-07 20:43 UTC by macedot

**Describe the pull request**

- #### What does your PR fix?
Update do current sable release of jwt-cpp (Support for OpenSSL 3.0.0, Implemented the "alg" ES256K, etc)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
 All / same as before

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
N/A

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-06-08 05:45 UTC, Adela0814 commented
@macedot 

```
versions/j-/jwt-cpp.json(2,): error : While reading versions for port jwt-cpp from file: version/j-/jwt-cpp.json
Version `0.6.0#1` was not found in versions file.
Run:

    vcpkg x-add-version jwt-cpp

to add the new port version
```

2022-06-08 13:07 UTC, macedot commented
New version added to vcpkg metadata

2022-06-09 02:03 UTC, Adela0814 requested changes

2022-06-09 02:03 UTC, Adela0814 commented on ports/jwt-cpp/vcpkg.json
>    "port-version": 1,
`port-version` should be deleted after version upgrade. And please add `licenses` field for `jwt-cpp`.

2022-06-10 02:02 UTC, Adela0814 approved these changes

2022-06-10 16:59 UTC, merged

2022-06-10 17:00 UTC, ras0219-msft commented
Thanks for the update!