[llvm] updated to 14.0.4 + add spirv backend support
microsoft/vcpkg pull request #25142
Opened 2022-06-08 11:26 UTC by pheonixfirewingz

**Describe the pull request**
the pull request updates vcpkg to be able to use the most resent version of llvm 14.0.4
also i added support to build llvm with the new spirv backend

- #### What does your PR fix?
  Fixes:
1. update latest version
2. add spirv backend

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
1. I have not touched the CI
2. I have tested (windows| linux) (64bit) I do not have mac access.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes as far as I have Checked`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result? yes
```PS
PS D:\Desktop\vcpkg> ./vcpkg.exe x-add-version llvm
version 14.0.4 is already in D:\Desktop\vcpkg\versions\l-\llvm.json
version 14.0.4 is already in D:\Desktop\vcpkg\versions\baseline.json
No files were updated for llvm
```
same result for `./vcpkg x-add-version --all --verbose`

2022-06-08 22:08 UTC, Thomas1664 commented on versions/l-/llvm.json
> +}
Please add a final newline here.

2022-06-08 23:15 UTC, pheonixfirewingz commented on versions/l-/llvm.json
> +}
fixed with a quick push

2022-06-09 04:34 UTC, dg0yt requested changes
Please use `vcpkg x-add-version ...` to update the files in `versions`. This ensure consistent formatting in every commit.

2022-06-09 04:34 UTC, dg0yt commented on versions/l-/llvm.json
> +      "git-tree": "fe9a228e3ded582f205104bb804ad065c26c082b",
No, it doesn't change 14.0.3#1.

2022-06-09 04:34 UTC, dg0yt commented on versions/l-/llvm.json
> +}
A  line break after `}`, not before...

2022-06-09 07:02 UTC, BillyONeal approved these changes

2022-06-09 07:04 UTC, pheonixfirewingz commented
> Please use `vcpkg x-add-version ...` to update the files in `versions`. This ensure consistent formatting in every commit.

Forgot to do that last push on it

2022-06-09 07:06 UTC, pheonixfirewingz commented
@BillyONeal thank you 😊 for the assistance

2022-06-09 07:07 UTC, pheonixfirewingz commented
Thank you for the reviews 🙂 everything i'll use to improve future pr's

2022-06-09 07:29 UTC, JonLiu1993 approved these changes

2022-06-09 07:44 UTC, pheonixfirewingz commented
@JonLiu1993 what to you mean by requires all feature testing isn`t that what azure pipelines do? 😕😵‍💫

2022-06-09 07:58 UTC, JonLiu1993 commented
> @JonLiu1993 what to you mean by requires all feature testing isn`t that what azure pipelines do? 😕😵‍💫 I mean it worked on my Linux and windows machine i'm confused? 😵‍💫 (please done take it as rude i really am just confused)

@pheonixfirewingz ,Take it easy, ci just test default-features, can't test other feature, we need test other features with x86-window,x64-windows,x64-windows-static and x64-linux triplet, if all successfully we will merge this pr.

2022-06-09 08:00 UTC, pheonixfirewingz commented
> > @JonLiu1993 what to you mean by requires all feature testing isn`t that what azure pipelines do? 😕😵‍💫 I mean it worked on my Linux and windows machine i'm confused? 😵‍💫 (please done take it as rude i really am just confused)
> 
> @pheonixfirewingz ,Take it easy, ci just test default-features, can't test other feature, we need test other features with x86-window,x64-windows,x64-windows-static and x64-linux triplet, if all successfully we will merge this pr.

ok just with the label idk what i needed to do to fix it so was panicking that i missing something required forgive me  😅

2022-06-09 08:02 UTC, JonLiu1993 commented
> > > @JonLiu1993 what to you mean by requires all feature testing isn`t that what azure pipelines do? 😕😵‍💫 I mean it worked on my Linux and windows machine i'm confused? 😵‍💫 (please done take it as rude i really am just confused)
> > 
> > 
> > @pheonixfirewingz ,Take it easy, ci just test default-features, can't test other feature, we need test other features with x86-window,x64-windows,x64-windows-static and x64-linux triplet, if all successfully we will merge this pr.
> 
> ok just with the label idk what i needed to do to fix it so was panicking that i missing something required forgive me 😅

this label just tell everyone this pr need test feature, that's all

2022-06-09 08:04 UTC, pheonixfirewingz commented
> > > > @JonLiu1993 what to you mean by requires all feature testing isn`t that what azure pipelines do? 😕😵‍💫 I mean it worked on my Linux and windows machine i'm confused? 😵‍💫 (please done take it as rude i really am just confused)
> > > 
> > > 
> > > @pheonixfirewingz ,Take it easy, ci just test default-features, can't test other feature, we need test other features with x86-window,x64-windows,x64-windows-static and x64-linux triplet, if all successfully we will merge this pr.
> > 
> > 
> > ok just with the label idk what i needed to do to fix it so was panicking that i missing something required forgive me 😅
> 
> This label just tell everyone this pr need test feature, that's all

ok 😅 thank you for your patience's with me to explain.🫂

2022-06-09 12:28 UTC, Neumann-A commented on ports/llvm/portfile.cmake
> +set(known_llvm_experamental_targets
```suggestion
set(known_llvm_experimental_targets
```

2022-06-09 12:28 UTC, Neumann-A commented on ports/llvm/portfile.cmake
> +foreach(llvm_target IN LISTS known_llvm_experamental_targets)
```suggestion
foreach(llvm_target IN LISTS known_llvm_experimental_targets)
```

2022-06-09 12:32 UTC, yurybura commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
How did you calculate memory limits 2, 3, ... jobs?

2022-06-09 12:39 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +foreach(llvm_target IN LISTS known_llvm_experamental_targets)
I don't understand the problem?

2022-06-09 12:46 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
based on the amount of ram free(available) 7GB, 15GB, 31GB, 63GB allow clang to parallelize the build linking to speed up build times based on personal tests on windows and linux it seems to speed up build time by 30mins (1H:8-15min from 1H:38 - 45min)

2022-06-09 12:48 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
this also seems to me the same for azure pipelines as far as I can see.

2022-06-09 12:55 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
https://cmake.org/cmake/help/v3.23/command/cmake_host_system_information.html
https://www.gbmb.org/gb-to-mib

2022-06-09 13:07 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +foreach(llvm_target IN LISTS known_llvm_experamental_targets)
i'll fix it anyway

2022-06-09 16:39 UTC, pheonixfirewingz commented
@JonLiu1993 sometime is wrong with azure pipelines it been stuck for 3 hours this is not normal and it’s not just my pr that is doing it

2022-06-09 17:53 UTC, BillyONeal commented
> @JonLiu1993 sometime is wrong with azure pipelines it been stuck for 3 hours this is not normal and it’s not just my pr that is doing it

It's most likely that there just were not more agents available. 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1544943/172912584-f1a831d5-5077-46e0-b68b-a04c05ad600d.png">

2022-06-09 18:21 UTC, ekilmer requested changes

2022-06-09 18:21 UTC, ekilmer commented on ports/llvm/portfile.cmake
> +endif()
These `if` statements are wrong for what you're trying to do. Needs to be `MEMORY GREATER_EQUAL ...`

2022-06-09 18:21 UTC, ekilmer commented on ports/llvm/portfile.cmake
> +cmake_host_system_information(RESULT MEMORY QUERY AVAILABLE_VIRTUAL_MEMORY)
`AVAILABLE_VIRTUAL_MEMORY` was giving me much lower numbers than I expected. I changed it to `AVAILABLE_PHYSICAL_MEMORY` and that gave me what I expected. Are you seeing differently?

2022-06-09 18:28 UTC, ekilmer commented
I noticed an error in the output on this line in the logs (shows in red when running locally) https://dev.azure.com/vcpkg/public/_build/results?buildId=73447&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=da63cf11-1f12-503b-6d64-3b2fb713c172&l=3782

```
Error: Unrecognized identifer name spirv. Add to override list in triplet file.
```

Not sure what is actually causing it though... Maybe the `"platform": "spirv"` line in `ports/llvm/vcpkg.json`? Is this something to worry about?

2022-06-09 19:22 UTC, pheonixfirewingz commented
> I noticed an error in the output on this line in the logs (shows in red when running locally) https://dev.azure.com/vcpkg/public/_build/results?buildId=73447&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=da63cf11-1f12-503b-6d64-3b2fb713c172&l=3782
> 
> 
> 
> ```
> 
> Error: Unrecognized identifer name spirv. Add to override list in triplet file.
> 
> ```
> 
> 
> 
> Not sure what is actually causing it though... Maybe the `"platform": "spirv"` line in `ports/llvm/vcpkg.json`? Is this something to worry about?

What platform is this happening on i checking the azure and can't find what you are talking about

2022-06-09 19:29 UTC, ekilmer commented
> > I noticed an error in the output on this line in the logs (shows in red when running locally) https://dev.azure.com/vcpkg/public/_build/results?buildId=73447&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=da63cf11-1f12-503b-6d64-3b2fb713c172&l=3782
> > ```
> > 
> > Error: Unrecognized identifer name spirv. Add to override list in triplet file.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure what is actually causing it though... Maybe the `"platform": "spirv"` line in `ports/llvm/vcpkg.json`? Is this something to worry about?
> 
> What platform is this happening on i checking the azure and can't find what you are talking about

Seems to be happening on all platforms. The link I posted _should_ take you to the correct spot, but if not. Here's a pic 
![Screen Shot 2022-06-09 at 3 28 52 PM](https://user-images.githubusercontent.com/816362/172928941-56b63d38-83c2-4b9a-a381-d9ac3f8dd2ed.png)

If you search the other OSs, it should also come up in the logs.

2022-06-09 20:18 UTC, pheonixfirewingz commented
Idk where to start to fix is as the is not enough information to be useful

2022-06-09 20:44 UTC, pheonixfirewingz commented
@JonLiu1993 @BillyONeal could you potentially tell me if this is a config error on my end or is it that azure is not set up to support the new backend for llvm?

2022-06-09 22:17 UTC, BillyONeal commented
`"platform":"spirv"` is saying "this feature may only be installed when targeting spirv", and vcpkg has no idea what "spirv" is. The allowable values for `"platform"`/`"supports"` are: https://github.com/microsoft/vcpkg-tool/blob/d2d696a5e87d5ab981b54a95e61bfb5bcf09c805/src/vcpkg/platform-expression.cpp#L44-L62

2022-06-09 22:18 UTC, BillyONeal requested changes
"spirv" needs to be fixed.

2022-06-09 22:48 UTC, pheonixfirewingz commented
Dose that mean i have to submit a pr to the vcpkg tool?

2022-06-10 02:48 UTC, BillyONeal commented
> It's a shader language making it platform agnostic how do i go about telling vcpkg that it is compatible with all platforms?

Don't provide a `"platform"` element at all.

2022-06-10 07:32 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +cmake_host_system_information(RESULT MEMORY QUERY AVAILABLE_VIRTUAL_MEMORY)
yep to be honest I was meant to use AVAILABLE_PHYSICAL_MEMORY  not AVAILABLE_VIRTUAL_MEMORY I don't think 3am brain realized and I had not noticed this bug good spot, furthermore idk my math worked as I wrote it with   AVAILABLE_PHYSICAL_MEMORY in mind 🤦‍♂️pushing fix

2022-06-10 11:21 UTC, ekilmer approved these changes

2022-06-10 20:12 UTC, pheonixfirewingz commented
> > It's a shader language making it platform agnostic how do i go about telling vcpkg that it is compatible with all platforms?
> 
> 
> 
> Don't provide a `"platform"` element at all.

@BillyONeal fixed! 😊

2022-06-13 05:39 UTC, JonLiu1993 commented
@pheonixfirewingz ,Could you test the features locally by command "./vcpkg install llvm[*]:x64-linux"?

2022-06-13 06:21 UTC, pheonixfirewingz commented
> @pheonixfirewingz ,Could you test the features locally by command "./vcpkg install llvm[*]:x64-linux"?

I could run it on my linux laptop if you need me to

2022-06-13 06:22 UTC, JonLiu1993 commented
> > @pheonixfirewingz ,Could you test the features locally by command "./vcpkg install llvm[*]:x64-linux"?
> 
> I could run it on my linux laptop if you need me to

Thanks for your help

2022-06-13 07:26 UTC, pheonixfirewingz commented
I'll sent the log asap

2022-06-13 08:20 UTC, pheonixfirewingz commented
@JonLiu1993 how do i compile with extra features without a vcpkg.json aka via command line? i wanting to add spirv to the log

2022-06-13 15:20 UTC, pheonixfirewingz commented
@JonLiu1993 after me updating to the new Ubuntu 22.04 LTS the system-d memory daemon keeps killing the compile process because of it taking 75% of my ram at the linking stage what should i do? as i can not supply the log when it dose not complete

2022-06-13 15:27 UTC, ekilmer commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
Seems like these numbers need to be bumped up based on your recent comment @pheonixfirewingz https://github.com/microsoft/vcpkg/pull/25142#issuecomment-1154057603

2022-06-13 17:21 UTC, BillyONeal approved these changes

2022-06-13 18:22 UTC, BillyONeal commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
Given that we're already seeing reports of this causing failures for people do you mind if we take the update and new backend but backout this LLVM_LINK_JOBS change for now?

2022-06-14 06:27 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
The new back end is not having problems for me but yea the auto jobs bit needs more work also the new Ubuntu lts is buggy as all hell idk if it will work on linux https://odysee.com/@TheLinuxExperiment:e/ubuntu-problems,-linux-on-ipad,-system76:7

2022-06-14 06:32 UTC, JonLiu1993 commented
> @JonLiu1993 after me updating to the new Ubuntu 22.04 LTS the system-d memory daemon keeps killing the compile process because of it taking 75% of my ram at the linking stage what should i do? as i can not supply the log when it dose not complete

I will find a free linux machine and try again

2022-06-14 06:33 UTC, JonLiu1993 approved these changes

2022-06-14 06:34 UTC, pheonixfirewingz commented on ports/llvm/portfile.cmake
> +#this is calculated in mib to gb
Will submit new patch to remove the jobs bit

2022-06-14 16:07 UTC, BillyONeal commented
Thanks for the update and sorry for the runaround :D

2022-06-14 16:07 UTC, merged