[paho-mqtt] Update to 1.3.10 and fix include path
microsoft/vcpkg pull request #25207
Opened 2022-06-13 07:34 UTC by LilyWangLL

**Describe the pull request**

- #### What does your PR fix?
  Fixes #15349
1. Update `paho-mqtt` to version 1.3.10
2. Remove old patch `remove_compiler_options.patch`.
3. Remove patch `fix-install-path.patch`, due to the official header file path doesn't include port name. This patch be removed, port `paho-mqttpp3` doesn't need patch `fix-include-path.patch`.
4. Add `find_dependency(OpenSSL)` for `paho-mqtt`.

2022-06-13 08:10 UTC, Thomas1664 reviewed
Although this is still a draft, I have a few suggestions:

2022-06-13 08:10 UTC, Thomas1664 commented on ports/paho-mqtt/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/about.html" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

Why are you copying readme?
There is now a `LICENSE` file

2022-06-13 08:10 UTC, Thomas1664 commented on ports/paho-mqtt/portfile.cmake
> +file(COPY "${CURRENT_PACKAGES_DIR}/share/doc" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
Please avoid installing documentation by default.

2022-06-13 08:25 UTC, LilyWangLL commented on ports/paho-mqtt/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/about.html" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
Thanks for your suggestion, I missed this. Done.

2022-06-13 08:34 UTC, LilyWangLL commented on ports/paho-mqtt/portfile.cmake
> +file(COPY "${CURRENT_PACKAGES_DIR}/share/doc" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
I just move this documentation folder to _share/${PORT}_, these files installed by option `PAHO_ENABLE_CPACK`, the related codes as below.
```
IF (PAHO_ENABLE_CPACK)
    ### packaging settings
    FILE(GLOB samples "src/samples/*.c")
    INSTALL(FILES ${samples} DESTINATION ${CMAKE_INSTALL_DOCDIR}/samples)

    SET(CPACK_PACKAGE_VENDOR "Eclipse Paho")
    SET(CPACK_PACKAGE_NAME "Eclipse-Paho-MQTT-C")
    INSTALL(FILES CONTRIBUTING.md epl-v20 edl-v10 README.md notice.html DESTINATION ${CMAKE_INSTALL_DOCDIR})

    IF (WIN32)
        SET(CPACK_GENERATOR "ZIP")
    ELSEIF(PAHO_BUILD_DEB_PACKAGE)
        INSTALL(FILES CONTRIBUTING.md epl-v20 edl-v10 README.md notice.html DESTINATION ${CMAKE_INSTALL_DOCDIR})

        SET(CPACK_GENERATOR "DEB")
        CONFIGURE_FILE(${CMAKE_SCRIPTS}/CPackDebConfig.cmake.in
                ${CMAKE_BINARY_DIR}/CPackDebConfig.cmake @ONLY)
        SET(CPACK_PROJECT_CONFIG_FILE ${CMAKE_BINARY_DIR}/CPackDebConfig.cmake)
    ELSE()
            SET(CPACK_GENERATOR "TGZ")
    ENDIF()
ELSE()
       FILE(GLOB samples "src/samples/*.c")
       INSTALL(FILES ${samples} DESTINATION ${CMAKE_INSTALL_DOCDIR})
ENDIF()
```

2022-06-13 11:22 UTC, dg0yt commented on ports/paho-mqtt/portfile.cmake
> +file(COPY "${CURRENT_PACKAGES_DIR}/share/doc" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
I don't  think `PAHO_ENABLE_CPACK` should be turned on.
But even if turned of, there will be `samples`.
(Which value is given to `CMAKE_INSTALL_DOCDIR` by `vcpkg_cmake_configure`? Doesn't it include `${PORT}`?)

2022-06-14 02:33 UTC, LilyWangLL commented on ports/paho-mqtt/portfile.cmake
> +file(COPY "${CURRENT_PACKAGES_DIR}/share/doc" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
I test set `CMAKE_INSTALL_DOCDIR` to empty by `vcpkg_cmake_configure`, it doesn't useful, it will install these files `src/samples/*.c`. So I remove the doc folder. The following is my test code:
```
vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DPAHO_WITH_SSL=TRUE
    -DPAHO_BUILD_SHARED=${PAHO_BUILD_DYNAMIC}
    -DPAHO_BUILD_STATIC=${PAHO_BUILD_STATIC}
    -DPAHO_ENABLE_TESTING=FALSE
    -DCMAKE_INSTALL_DOCDIR=
    -DPAHO_ENABLE_CPACK=OFF
)
```

2022-06-14 03:04 UTC, JackBoosY requested changes

2022-06-14 03:04 UTC, JackBoosY commented on ports/paho-mqtt/portfile.cmake
> +find_dependency(OpenSSL)"
```suggestion
    [[# Generated by CMake]]
    [[# Generated by CMake
include(CMakeFindDependencyMacro)
find_dependency(OpenSSL)]]
```

2022-06-14 05:24 UTC, dg0yt commented on ports/paho-mqtt/portfile.cmake
> +file(COPY "${CURRENT_PACKAGES_DIR}/share/doc" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
> I test set `CMAKE_INSTALL_DOCDIR` to empty by `vcpkg_cmake_configure`, it doesn't useful

I don't think this is a good idea. Setting it to emtpy doesn't disable installation of files, they will only end up in a different location.
Sometimes I wish I could just set it to a `VCPKG_TRASH` folder which is automatically cleaned, not packaged...

2022-06-15 09:30 UTC, JackBoosY approved these changes

2022-06-15 18:02 UTC, merged