Upgrade tensorflow to 2.9.1 and support osx-arm64.
microsoft/vcpkg pull request #25250
Opened 2022-06-15 15:23 UTC by matt-42

This PR upgrade tensorflow to 2.9.1 and add support of triplet osx-arm64

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
existing triplets plus osx-arm64

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
 Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-06-16 06:59 UTC, JonLiu1993 requested changes

2022-06-16 06:59 UTC, JonLiu1993 commented on ports/tensorflow-cc/vcpkg.json
>    "port-version": 2,
```suggestion
```

2022-06-16 06:59 UTC, JonLiu1993 commented on ports/tensorflow-common/vcpkg.json
>    "port-version": 2,
```suggestion
```

2022-06-16 06:59 UTC, JonLiu1993 commented on ports/tensorflow/vcpkg.json
>    "port-version": 2,
```suggestion
```

2022-06-21 06:21 UTC, JonLiu1993 commented on ports/tensorflow-common/tensorflow-common.cmake
> +	endif()
@matt-42 ,Please keep the code format here the same as above, the spaces here are too large

2022-06-21 06:25 UTC, JonLiu1993 commented on ports/tensorflow-cc/vcpkg.json
> +  "supports": "!(x86 | arm | uwp) | (arm64 & osx)",
```suggestion
  "supports": "!(x86 | arm | uwp) | (arm64 & osx)",
  "license": "MIT",
```

2022-06-22 08:55 UTC, matt-42 commented on ports/tensorflow-cc/vcpkg.json
> +  "supports": "!(x86 | arm | uwp) | (arm64 & osx)",
Shouldn't it be "Apache-2.0" ? Tensorflow is under Apache-2.0.

2022-06-22 09:08 UTC, JonLiu1993 commented on ports/tensorflow-cc/vcpkg.json
> +  "supports": "!(x86 | arm | uwp) | (arm64 & osx)",
@matt-42, I referenced [this](https://github.com/FloopCZ/tensorflow_cc/blob/master/LICENSE)

2022-06-22 09:21 UTC, matt-42 commented on ports/tensorflow-cc/vcpkg.json
> +  "supports": "!(x86 | arm | uwp) | (arm64 & osx)",
Why referencing this ?  I do not see how the tensorflow-cc port is related to FloopCZ/tensorflow_cc

2022-06-22 09:38 UTC, JonLiu1993 commented on ports/tensorflow-cc/vcpkg.json
> +  "supports": "!(x86 | arm | uwp) | (arm64 & osx)",
@matt-42 ,Sorry my mistake, it should be "Apache-2.0"

2022-07-06 06:47 UTC, JonLiu1993 commented
@matt-42, Ci tested failed in the x64-linux and x64-osx triplet,
This is error log, please take a look:
````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: virtualenv --symlinks /mnt/vcpkg-ci/buildtrees/tensorflow/x64-linux-venv
    Working Directory: /mnt/vcpkg-ci/buildtrees/tensorflow
    Error code: No such file or directory
    See logs for more information:
````

2022-07-11 12:56 UTC, matt-42 commented
Hi @JonLiu1993 , I don't have more time to dedicate to this pr. I'm closing it. If anyone wants to take over feel free to start from my branch:  https://github.com/matt-42/vcpkg/tree/tensorflow-update-osx-arm64

2022-07-11 12:56 UTC, closed without merging