[ncnn] Add new port
microsoft/vcpkg pull request #25276
Opened 2022-06-16 12:02 UTC by holylong

[ncnn] Add new port
* Provide ncnn implementation

* Convert CONTROL to vcpkg.json.

* Update versions/baseline.json.

* Address reviewer comments by using vcpkg_from_github.

* Implement recommended changes from MR review.

* Update x-add-version.

* ncnn uses a proprietary license is BSD

* Update versions file.

* format portfile.cmake

* x-add-version

* apply suggestion

* x-add-version

Co-authored-by: holylong<mrhlingchen@163.com>

2022-06-16 16:31 UTC, Thomas1664 requested changes

2022-06-17 02:20 UTC, JonLiu1993 requested changes

2022-06-17 02:20 UTC, JonLiu1993 commented on ports/ncnn/portfile.cmake
> +
```suggestion
```

2022-06-17 02:20 UTC, JonLiu1993 commented on ports/ncnn/vcpkg.json
> +  "homepage": "https://github.com/Tencent/ncnn",
```suggestion
  "homepage": "https://github.com/Tencent/ncnn",
  "license": "BSD-3-Clause",
```

2022-06-17 02:23 UTC, JonLiu1993 commented
@holylong, Thanks for your pr, Looks the ci tested failed, 
this is error log, please taeke a look:
````
/debug/share should not exist. Please reorganize any important files, then use
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    D:/packages/ncnn_x86-windows/bin/darknet2ncnn.exe
    D:/packages/ncnn_x86-windows/bin/mxnet2ncnn.exe
    D:/packages/ncnn_x86-windows/bin/ncnn2int8.exe
    D:/packages/ncnn_x86-windows/bin/ncnn2mem.exe
    D:/packages/ncnn_x86-windows/bin/ncnn2table.exe
    D:/packages/ncnn_x86-windows/bin/ncnnmerge.exe
    D:/packages/ncnn_x86-windows/bin/ncnnoptimize.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    D:/packages/ncnn_x86-windows/debug/bin/darknet2ncnn.exe
    D:/packages/ncnn_x86-windows/debug/bin/mxnet2ncnn.exe
    D:/packages/ncnn_x86-windows/debug/bin/ncnn2int8.exe
    D:/packages/ncnn_x86-windows/debug/bin/ncnn2mem.exe
    D:/packages/ncnn_x86-windows/debug/bin/ncnn2table.exe
    D:/packages/ncnn_x86-windows/debug/bin/ncnnmerge.exe
    D:/packages/ncnn_x86-windows/debug/bin/ncnnoptimize.exe

````

2022-06-17 03:49 UTC, holylong commented
> Please don't git push this branch, I'm fixing bugs

ok, I add some ncnn cmake options to avoid exe generation

2022-06-17 05:43 UTC, JonLiu1993 commented
This is error log, please take a look:
````
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\emmintrin.h(20): fatal error C1189: #error:  This header is specific to X86, X64 and ARM64EC targets
[11/158] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\arm\cl.exe   /TP -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer\x86 -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src -ID:\buildtrees\ncnn\arm-uwp-dbg\src -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /D_DEBUG /Od /RTC1 /MDd  -MDd -DNCNN_STATIC_DEFINE -fno-rtti /arch:SSE2 /D__SSE2__ -openmp /showIncludes /Fosrc\CMakeFiles\ncnn.dir\layer\x86\bias_x86.cpp.obj /Fdsrc\CMakeFiles\ncnn.dir\ncnn.pdb /FS -c D:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer\x86\bias_x86.cpp
FAILED: src/CMakeFiles/ncnn.dir/layer/x86/bias_x86.cpp.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\arm\cl.exe   /TP -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer\x86 -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src -ID:\buildtrees\ncnn\arm-uwp-dbg\src -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /D_DEBUG /Od /RTC1 /MDd  -MDd -DNCNN_STATIC_DEFINE -fno-rtti /arch:SSE2 /D__SSE2__ -openmp /showIncludes /Fosrc\CMakeFiles\ncnn.dir\layer\x86\bias_x86.cpp.obj /Fdsrc\CMakeFiles\ncnn.dir\ncnn.pdb /FS -c D:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer\x86\bias_x86.cpp
cl : Command line warning D9002 : ignoring unknown option '-fno-rtti'
cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\emmintrin.h(20): fatal error C1189: #error:  This header is specific to X86, X64 and ARM64EC targets
[12/158] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\arm\cl.exe   /TP -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer\x86 -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src -ID:\buildtrees\ncnn\arm-uwp-dbg\src -ID:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\layer /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /D_DEBUG /Od /RTC1 /MDd  -MDd -DNCNN_STATIC_DEFINE -fno-rtti /arch:SSE2 /D__SSE2__ -openmp /showIncludes /Fosrc\CMakeFiles\ncnn.dir\mat.cpp.obj /Fdsrc\CMakeFiles\ncnn.dir\ncnn.pdb /FS -c D:\buildtrees\ncnn\src\20220420-dbbb03d16a.clean\src\mat.cpp
FAILED: src/CMakeFiles/ncnn.dir/mat.cpp.obj 
````

2022-06-17 05:44 UTC, JonLiu1993 commented
You can modify it normally

2022-06-17 06:11 UTC, holylong commented
I'm not have toolchain to compile for arm platform

```
error: in triplet arm64-windows: Unable to find a valid toolchain for requested target architecture arm64.
The selected Visual Studio instance is at: D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
The available toolchain combinations are: x86, amd64, x86_amd64, amd64_x86
See https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#VCPKG_VISUAL_STUDIO_PATH for more information.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

2022-06-17 06:13 UTC, holylong commented
I change vcpkg.json like mnn not sopport mobile and arm
```
"supports": "!(arm | uwp | ios | android)",
```

2022-06-17 06:19 UTC, JonLiu1993 commented
> I change vcpkg.json like mnn not sopport mobile and arm
> 
> ```
> "supports": "!(arm | uwp | ios | android)",
> ```

ncnn support these platforms natively?

2022-06-17 07:45 UTC, holylong commented
> > I change vcpkg.json like mnn not sopport mobile and arm
> > ```
> > "supports": "!(arm | uwp | ios | android)",
> > ```
> 
> ncnn support these platforms natively?
ncnn is a inference library like mnn, The method of compiling the arm version with visual studio not supported now.

2022-06-17 08:11 UTC, JonLiu1993 commented on ports/ncnn/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
@holylong ,Please add a new final line

2022-06-17 08:49 UTC, JonLiu1993 submitted a review, later dismissed

2022-06-17 16:39 UTC, Thomas1664 requested changes

2022-06-17 16:39 UTC, Thomas1664 commented on ports/ncnn/portfile.cmake
> +endif()
```suggestion
vcpkg_copy_tools(TOOL_NAMES <tool_names> AUTO_CLEAN)
```

Since you disabled tools and test, are these lines still required? If yes please use [`vcpkg_copy_tools()`](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md) instead.

2022-06-17 22:02 UTC, Thomas1664 commented on ports/ncnn/portfile.cmake
> +endif()
@holylong `<tool_names>` was meant as a placeholder for the names of the executables. Please replace it with their file names (without file extension. Furthermore, I recommend to read the docs about [`vcpkg_copy_tools()`](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md).

2022-06-17 22:17 UTC, holylong commented
But I add cmake options to avoid generate exes,there has no exes to clean or copy.



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/18/2022 06:02 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [microsoft/vcpkg] [ncnn] Add new port (PR #25276) |

@Thomas1664 commented on this pull request.

In ports/ncnn/portfile.cmake:

> +file(GLOB EXES "${CURRENT_PACKAGES_DIR}/bin/*.exe")
+if(EXES)
+    file(COPY ${EXES} DESTINATION "${CURRENT_PACKAGES_DIR}/tools/shapelib")
+    file(COPY ${EXES} DESTINATION "${CURRENT_PACKAGES_DIR}/tools/shapelib")
+    file(REMOVE ${EXES})
+endif()
+
+file(GLOB DEBUG_EXES "${CURRENT_PACKAGES_DIR}/debug/bin/*.exe")
+if(DEBUG_EXES)
+    file(REMOVE ${DEBUG_EXES})
+endif()


@holylong<tool_names> was meant as a placeholder for the names of the executables. Please replace it with their file names (without file extension. Furthermore, I recommend to read the docs about vcpkg_copy_tools().

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-18 01:48 UTC, holylong commented
> But I add cmake options to avoid generate exes,there has no exes to clean or copy.
> ---- Replied Message ---- | From | ***@***.***> | | Date | 06/18/2022 06:02 | | To | ***@***.***> | | Cc | ***@***.******@***.***> | | Subject | Re: [microsoft/vcpkg] [ncnn] Add new port (PR #25276) | @Thomas1664 commented on this pull request. In ports/ncnn/portfile.cmake:
> +file(GLOB EXES "${CURRENT_PACKAGES_DIR}/bin/*.exe")
> +if(EXES) + file(COPY ${EXES} DESTINATION "${CURRENT_PACKAGES_DIR}/tools/shapelib") + file(COPY ${EXES} DESTINATION "${CURRENT_PACKAGES_DIR}/tools/shapelib") + file(REMOVE ${EXES}) +endif() + +file(GLOB DEBUG_EXES "${CURRENT_PACKAGES_DIR}/debug/bin/*.exe") +if(DEBUG_EXES) + file(REMOVE ${DEBUG_EXES}) +endif() @holylong<tool_names> was meant as a placeholder for the names of the executables. Please replace it with their file names (without file extension. Furthermore, I recommend to read the docs about vcpkg_copy_tools(). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>


But I add cmake options to avoid generate exes,there has no exes to clean or copy. so function vcpkg_copy_tools() is it a little superfluous

2022-06-20 07:47 UTC, JonLiu1993 commented on ports/ncnn/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
@holylong, I'm curious does ncnn not compile Debug? Nothing is generated under the Debug path?

2022-06-21 08:20 UTC, holylong commented on ports/ncnn/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
> I'm curious does ncnn not compile Debug? Nothing is generated under the Debug path?

There seems to be a ncnnd.lib library under the debug directory I compiled，Which version did you compile? I'll try it

2022-06-21 09:54 UTC, holylong commented on ports/ncnn/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
> @holylong ,I just checkout your branch and when I install it locally, it shows that the _/bin_ and _/debug/bin_ directories are empty, so I added these two lines, can you still generate .lib files locally?

ok，I‘ll remove all the ncnn libs and try again

2022-08-05 08:28 UTC, JonLiu1993 commented
Ping @holylong for response

2022-09-02 10:21 UTC, JonLiu1993 commented
Duplicate of #26557

2022-09-02 10:21 UTC, closed without merging