[DiscordCoreAPI] Update to version 2022-06-17.
microsoft/vcpkg pull request #25292
Opened 2022-06-17 10:38 UTC by RealTimeChris

**Describe the pull request**

- #### What does your PR fix?
It adds support for Discord's latest API endpoints. I also refactored some of the core architecture - instead of using 1 thread per connection in the instance of sharding, it utilizes a threadpool now. Also refactored some of the exception handling.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <Linux, Windows>, <Yes>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
 Yes I have.

2022-06-21 07:54 UTC, JackBoosY requested changes

2022-06-21 07:54 UTC, JackBoosY commented on ports/discordcoreapi/portfile.cmake
> -vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)
Why remove this? Does the upstream no longer provide to generate the cmake configure files?

2022-06-22 02:34 UTC, JackBoosY commented on ports/discordcoreapi/portfile.cmake
> -vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)
I don't get it. Even if the *config.cmake is generated correctly, we also need to use `vcpkg_cmake_config_fixup()` with no params here.

2022-06-22 02:57 UTC, RealTimeChris commented on ports/discordcoreapi/portfile.cmake
> -vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)
It seems to build fine on the Windows and Linux configurations I've tested it on without it - but if it is the case that it is required then I have no problems putting it back.

2022-06-22 03:02 UTC, JackBoosY commented on ports/discordcoreapi/portfile.cmake
> -vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)
We need to ensure that the absolute path is changed to relative path to support feature export and binarycaching, and the debug configuration should exist in the same directory as the release configuration.

2022-06-22 03:17 UTC, RealTimeChris commented on ports/discordcoreapi/portfile.cmake
> -vcpkg_cmake_config_fixup(NO_PREFIX_CORRECTION)
I'm fairly certain that this is the case, the way I have the cmake script set up.

2022-06-22 05:38 UTC, JackBoosY approved these changes

2022-06-22 05:38 UTC, JackBoosY requested changes

2022-06-22 05:38 UTC, JackBoosY commented on versions/d-/discordcoreapi.json
> +      "git-tree": "ad04fb27ce70ec41f7952a752f74831e20c49bd4",
```suggestion
      "git-tree": "c452db017823a155eec5eba2a0dca0d21f12d541",
```

2022-06-22 05:39 UTC, JackBoosY approved these changes

2022-06-22 05:47 UTC, JackBoosY commented
The upstream cmake seems has some bugs:
In debug:
```
-- Installing: D:/packages/discordcoreapi_x64-uwp/share/discordcoreapi/DiscordCoreAPIConfig.cmake
-- Installing: D:/packages/discordcoreapi_x64-uwp/share/discordcoreapi/DiscordCoreAPIConfigVersion.cmake
...
-- Installing: D:/packages/discordcoreapi_x64-uwp/share/discordcoreapi/DiscordCoreAPITargets.cmake
-- Installing: D:/packages/discordcoreapi_x64-uwp/share/discordcoreapi/DiscordCoreAPITargets-debug.cmake
```
Theses files should be installed into _D:/packages/discordcoreapi_x64-uwp/debug/share/discordcoreapi_.
The installation code should be:
```cmake
install(EXPORT DiscordCoreAPITargets ... DESTINATION share/discordcoreapi)
install(FILES DiscordCoreAPIConfig.cmake DESINTATION share/discordcoreapi)
install(FILES DiscordCoreAPIConfigVersion.cmake DESINTATION share/discordcoreapi)
```

2022-06-23 02:07 UTC, JackBoosY commented on ports/discordcoreapi/portfile.cmake
> +if(VCPKG_TARGET_IS_LINUX)
Did you convert the file's format?

2022-06-23 02:07 UTC, JackBoosY reviewed
Did you test cmake usage?

2022-06-23 02:51 UTC, RealTimeChris commented on ports/discordcoreapi/portfile.cmake
> +if(VCPKG_TARGET_IS_LINUX)
What do you mean?

2022-06-23 03:57 UTC, RealTimeChris commented
> Did you test cmake usage?

Yes I did - it works as intended.

2022-06-23 05:42 UTC, JackBoosY approved these changes

2022-06-23 20:58 UTC, merged