[glog] upgrade to v0.6
microsoft/vcpkg pull request #25312
Opened 2022-06-18 17:52 UTC by jiayuehua

**Describe the pull request**

- #### What does your PR fix?
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-06-21 08:02 UTC, JackBoosY requested changes

2022-06-21 08:02 UTC, JackBoosY commented on ports/fbthrift/fix-glog.patch
> ++  find_package(glog CONFIG REQUIRED)
I prefer to add the following code instead of modify `GLOG_LIBRARIES` to `glog::glog` to reduce the patch size:
```patch
-  find_package(Glog REQUIRED)
+  find_package(glog CONFIG REQUIRED)
+  set(GLOG_LIBRARIES glog::glog)
```

2022-06-21 08:02 UTC, JackBoosY commented on ports/folly/fix-abort.patch
> +diff --git a/folly/init/Init.cpp b/folly/init/Init.cpp
Also please report this to the upstream.

2022-06-21 08:02 UTC, JackBoosY commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
Why we need this?

2022-06-21 08:02 UTC, JackBoosY commented on ports/glog/fix_glog_CMAKE_MODULE_PATH.patch
>  -install (CODE
can you please use `if (0) ... endif()` to these code to reduce the patch size?

2022-06-21 08:02 UTC, JackBoosY commented on ports/glog/glog_disable_debug_postfix.patch
> -diff --git a/CMakeLists.txt b/CMakeLists.txt
You may need to modify the file format to LF.

2022-06-21 08:28 UTC, jiayuehua commented on ports/folly/fix-abort.patch
> +diff --git a/folly/init/Init.cpp b/folly/init/Init.cpp
this is a upstream master change, without this change , build will fail.

2022-06-21 08:31 UTC, jiayuehua commented on ports/caffe2/fix-isgloginitialized.patch
> +diff --git a/caffe2/core/logging.cc b/caffe2/core/logging.cc
[caffe2 ](https://github.com/facebookarchive/caffe2 ) has been archived by the owner in 2018. This change is because glog 0.6 move IsGoogleLoggingInitialized to 'google' namespace.

2022-06-21 08:40 UTC, jiayuehua commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
https://stackoverflow.com/questions/57102212/cannot-set-cplusplus-to-c17-standard-with-visual-studio-and-cmake
to make __cplusplus macro work correctly
[ #if @ac_cv_cxx11_atomic@ && __cplusplus >= 201103L](https://github.com/google/glog/blob/79d692c6459536356bdbbd4b89df2e0aee5b4eaf/src/glog/logging.h.in#L92)

2022-06-21 08:47 UTC, jiayuehua commented on ports/glog/fix_glog_CMAKE_MODULE_PATH.patch
>  -install (CODE
ok.

2022-06-21 09:53 UTC, jiayuehua commented on ports/glog/glog_disable_debug_postfix.patch
> -diff --git a/CMakeLists.txt b/CMakeLists.txt
ok

2022-06-21 10:59 UTC, jiayuehua commented on ports/fbthrift/fix-glog.patch
> ++  find_package(glog CONFIG REQUIRED)
I see. ok

2022-06-22 02:29 UTC, JackBoosY commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
I suspect this, what goes wrong without this setting?
From [official doc](https://docs.microsoft.com/en-us/cpp/build/reference/zc-conformance?view=msvc-170):
```
/Zc:__cplusplus	Enable the __cplusplus macro to report the supported standard (off by default).
```

2022-06-22 02:30 UTC, JackBoosY commented
Can you please merge to master?

2022-06-22 05:22 UTC, jiayuehua commented
you mean merge master to this pr?

2022-06-22 05:36 UTC, JackBoosY commented
> you mean merge master to this pr?

Yes.

2022-06-22 06:19 UTC, jiayuehua commented
ok

2022-06-22 06:35 UTC, jiayuehua commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
without this setting , even if we set c++ standard up than C++11,  __cplusplus >201103L still is not true.

2022-06-22 06:39 UTC, JackBoosY commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
I will test without it locally.

2022-06-22 06:51 UTC, JackBoosY commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
Tested successfully without this patch using Visual Studio 2017 / 2019 / 2022 / gcc 7.5.0.
So I think you don't need this.

2022-06-22 06:57 UTC, JackBoosY commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
I tried to remove this patch and store it locally.
If something goes wrong, I'll revert my commit.

2022-06-22 07:49 UTC, JackBoosY commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
Okay, seems it works. I will revert my changes.

Doc: https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170

2022-06-22 07:52 UTC, JackBoosY approved these changes

2022-06-23 22:29 UTC, merged

2022-09-14 03:17 UTC, craigscott-crascit commented on ports/glog/fix_cpluplus_macro.patch
> ++endif()
Did the correct final version of this change get merged? I see the `/Zc:__cplusplus` flag still being added, but the discussion above seems to conclude that the changes should have been reverted (but I could be misunderstanding @JackBoosY here).

I'm arriving here after this broke projects that use msvc clang (not clang-cl) and pull in glog. That compiler builds for the MSVC ABI, but it doesn't support MSVC command line options. If this flag really does need to be added, the condition around adding it needs to be on the _consumer_, not here on the _producer_. You could wrap it with a generator expression that checks the consumer's compiler ID, but then you'd have to pick a language (C or C++) to base that test on. It is probably simpler just to restore the old patch instead of adding this flag as was done in this PR.