[vcpkg_setup_pkgconfig_path] Fix backup/restore
microsoft/vcpkg pull request #25361
Opened 2022-06-21 08:16 UTC by dg0yt

- #### What does your PR fix?
  Add unit testing for for `vcpkg_backup/restore_env_variables` and `vcpkg_setup/restore_pkgconfig_path`.
  Fixes the broken backup of pkg-config path variables. Cf. https://github.com/microsoft/vcpkg/pull/25118#issuecomment-1155057516, and https://github.com/microsoft/vcpkg/blob/d732e2f628269c15026e1cdda228cc4f527e81e9/ports/dpdk/portfile.cmake#L63-L69

  *Unhanged:*
  Due to CMake's special handling of `<unset>` and scopes, there might still be room for unexpected behaviour.
  And `vcpkg_setup_pkgconfig_path` still adds to `ENV{PATH}` with no backup.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  not needed.

2022-06-21 08:41 UTC, dg0yt commented
NB: CI run only the unit tests.

2022-06-22 05:43 UTC, JackBoosY requested changes

2022-06-22 05:43 UTC, JackBoosY commented on scripts/cmake/vcpkg_backup_restore_env_vars.cmake
> +macro(vcpkg_backup_env_variables)
We should provide a function to other modules instead of a macro.

2022-06-22 06:02 UTC, dg0yt commented on scripts/cmake/vcpkg_backup_restore_env_vars.cmake
> +macro(vcpkg_backup_env_variables)
A function cannot write to the parent scope of the parent scope. That's why I changed the user facing command into a macro.

2022-06-22 06:06 UTC, JackBoosY commented on scripts/cmake/vcpkg_backup_restore_env_vars.cmake
> +macro(vcpkg_backup_env_variables)
Is there any other way we can solve this?
Consider this: it would be a disaster if a C++ module provided a macro containing a function for other modules to call.

2022-06-22 06:12 UTC, dg0yt commented on scripts/cmake/vcpkg_backup_restore_env_vars.cmake
> +macro(vcpkg_backup_env_variables)
> Is there any other way we can solve this?

Not within this command. The only alternative is yet another tighly coupled command. See the individual commits.

> Consider this: it would be a disaster if a C++ module provided a macro containing a function for other modules to call.

The script mode command names `vcpkg_backup_env_variables`/`z_vcpkg_backup_env_variables` are clearly owned by vcpkg, no matter if macro or function. No room for collision.
There is only one variable always overwritten in calling scope: `z_vcpkg_backup_env_variables_arg_vars`. Ownership should be clear here, too. What should be added is unsetting the variable before leaving the macro.

2022-06-22 06:53 UTC, JackBoosY submitted a review, later dismissed

2022-06-22 06:53 UTC, JackBoosY commented
I personally don't agree with this, need other guys to review it further.

2022-06-27 18:23 UTC, dg0yt commented
> just inline the function for its particular use.

Done. Using the same variable names as `vcpkg_backup_env_variables`/`z_vcpkg_restore_env_variables`.

2022-06-28 00:19 UTC, JackBoosY commented on docs/maintainers/internal/z_vcpkg_setup_pkgconfig_path.cmake.md
> -# z_vcpkg_setup_pkgconfig_path
Why remove this document?

2022-06-28 05:14 UTC, dg0yt commented on docs/maintainers/internal/z_vcpkg_setup_pkgconfig_path.cmake.md
> -# z_vcpkg_setup_pkgconfig_path
The commit message says `Remove duplicate doc file`. There is `docs/maintainers/internal/z_vcpkg_setup_pkgconfig_path.md`, and that file is linked in the index. What else do you need to know?

2022-06-28 06:30 UTC, JackBoosY commented on docs/maintainers/internal/z_vcpkg_setup_pkgconfig_path.cmake.md
> -# z_vcpkg_setup_pkgconfig_path
Ah, maybe Robert forgot to remove this doc.

2022-06-28 06:31 UTC, JackBoosY approved these changes

2022-06-29 21:47 UTC, merged