[dpdk] Update to version v22.03
microsoft/vcpkg pull request #25374
Opened 2022-06-21 22:02 UTC by ljishen

**Describe the pull request**

- #### What does your PR fix?
  Update dpdk to version v22.03

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  I've removed the x64-linux=fail from the file to mark that this port is supported by that Linux triplet.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

2022-06-22 04:15 UTC, dg0yt commented
I think both the old and the new attempt to provide a CMake config are full of problems. In addition, it is not from upstream, so it is should be in the `unofficial` namespace.

2022-06-23 05:56 UTC, Cheney-W commented
@ljishen Could you please handle the failure in CI test? [Failure log](https://dev.azure.com/vcpkg/_apis/resources/Containers/17241369/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fdpdk&%24format=zip&saveAbsolutePath=false)

2022-06-23 06:54 UTC, ljishen commented
> @ljishen Could you please handle the failure in CI test? [Failure log](https://dev.azure.com/vcpkg/_apis/resources/Containers/17241369/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fdpdk&%24format=zip&saveAbsolutePath=false)

The error is expected currently without the #25372. I've figured out how to separate static from dynamic build in dpdk according to @dg0yt's requirement. There is one more issue I need to fix before I can update this PR. Sorry about that.

2022-06-23 23:05 UTC, ljishen commented
Is there a way to view the error log?

2022-06-24 02:34 UTC, Cheney-W commented
Could you please open this: https://dev.azure.com/vcpkg/public/_build/results?buildId=74149&view=artifacts&pathAsName=false&type=publishedArtifacts ? 
All failure logs are stored there.

2022-06-24 07:04 UTC, ljishen commented
> Could you please open this: https://dev.azure.com/vcpkg/public/_build/results?buildId=74149&view=artifacts&pathAsName=false&type=publishedArtifacts ? All failure logs are stored there.

Thanks so much, @Cheney-W. This PR is ready to be reviewed.

2022-06-24 07:26 UTC, Cheney-W commented
Please remove the record about dpdk from `ci.baseline.txt`, because you have added `"supports": "linux | freebsd"` into the vcpkg.json file. Thank you!

2022-06-24 07:31 UTC, ljishen commented
@Cheney-W I've removed them. Please take a look. Thanks!

2022-06-25 00:27 UTC, ljishen commented
@Cheney-W Is this PR ready to be merged? Thanks.

2022-06-27 02:21 UTC, Cheney-W commented
Yes

2022-06-27 08:15 UTC, Thomas1664 requested changes

2022-06-27 17:50 UTC, ljishen commented on ports/dpdk/portfile.cmake
> +  RENAME copyright)
What should I do currently with this?

2022-06-27 17:53 UTC, ljishen commented on ports/dpdk/portfile.cmake
> +
OK

2022-06-27 18:10 UTC, Thomas1664 commented on ports/dpdk/portfile.cmake
> +  RENAME copyright)
Wait until #25239 gets merged. The PR is almoast ready so it should't take long

2022-06-27 18:34 UTC, dg0yt commented on ports/dpdk/vcpkg.json
> +  "version-string": "22.03",
Yes. It is not the first port which is hit by this.

2022-06-27 18:59 UTC, ljishen commented on ports/dpdk/portfile.cmake
> +  RENAME copyright)
I've updated the port to use the function to be merged. I will rebase it once the code is actually there.

2022-06-29 03:34 UTC, ljishen commented on ports/dpdk/portfile.cmake
> +  RENAME copyright)
@Thomas1664 Could I know when will #25239 get merged?

2022-06-30 03:50 UTC, dg0yt requested changes

2022-06-30 03:50 UTC, dg0yt commented on ports/dpdk/portfile.cmake
> +vcpkg_restore_env_variables(VARS PKG_CONFIG PKG_CONFIG_PATH)
`z_vcpkg_setup/restore_pkgconfig_path` should now work as expected (#25361). Please merge master and test without the explicit backup/restore.

2022-06-30 03:50 UTC, dg0yt commented on ports/dpdk/portfile.cmake
> +vcpkg_install_copyright(FILE_LIST ${license_files} COMMENT "${comment}")
This function shouldn't be used before https://github.com/microsoft/vcpkg/pull/25239 is merged.

2022-07-01 06:34 UTC, Cheney-W commented
@ljishen Could you please handle the suggestions of dg0yt? 
Also, I don't think you should let a PR that hasn't been merged block your PR.

2022-07-01 06:37 UTC, ljishen commented
> @ljishen Could you please handle the suggestions of dg0yt? Also, I don't think you should let a PR that hasn't been merged block your PR.

Great. Thanks for your support! I'll fix the code.

2022-07-01 07:53 UTC, ljishen commented on ports/dpdk/portfile.cmake
> +vcpkg_install_copyright(FILE_LIST ${license_files} COMMENT "${comment}")
OK

2022-07-01 07:54 UTC, ljishen commented on ports/dpdk/portfile.cmake
> +vcpkg_restore_env_variables(VARS PKG_CONFIG PKG_CONFIG_PATH)
Yes. The variable backup is working. Thanks.

2022-07-01 18:54 UTC, ljishen commented
@dan-shaw Could you help to merge this one, please?

2022-07-01 19:38 UTC, Thomas1664 approved these changes

2022-07-02 05:50 UTC, merged

2022-07-18 11:42 UTC, autoantwort commented
This package contains the following absolute path in `include/rte_build_config.h`:
```c++
#define RTE_EAL_PMD_PATH "/home/leander/vcpkg/packages/dpdk_x64-linux/lib/dpdk/pmds-22.1"
```
and it seems that this path is used in the code. The Problem is not existing when the package is restored from a binary cache. How should we handle this @ljishen?

2022-07-19 04:46 UTC, ljishen commented
@[autoantwort](https://github.com/autoantwort) With the linux triplet (e.g., [x64-linux](https://github.com/microsoft/vcpkg/blob/master/triplets/x64-linux.cmake)), this port will only build static libraries. The absolute path you asked contains dpdk's shared libraries and should be empty based on the triplet's requirement. Can you elaborate on the problem you have with that macro definition in the code? Did you have a customized triplet to use dpdk as a shared library?

2022-07-19 05:46 UTC, dg0yt commented
Since 10 hours, there is now an x64-linux-dynamic.cmake community triplet.
And in general, there must be no absolute paths in vcpkg packages. They must be relocatable.

2022-07-19 06:05 UTC, ljishen commented
OK. I'll update the dpdk port to fix the absolute part problem.

2022-08-14 10:02 UTC, autoantwort commented
@ljishen Is there already a PR to fix the absolute path problem? :)