Fixed typos and updated out-of-date information in the FAQ
microsoft/vcpkg pull request #25400
Opened 2022-06-22 22:56 UTC by AugP

Updated vcpkg FAQ since it's 2022 and a lot has changed with vcpkg and how we recommend people to use it. Also addresses a specific community-reported issue. 

- #### What does your PR fix?
  Fixes #25321 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
N/A
- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
N/A

2022-06-23 02:18 UTC, JackBoosY commented on docs/about/faq.md
> +* Linux (x64)
I think we should note these 2 triplets are static.

2022-06-23 12:59 UTC, Thomas1664 commented on docs/about/faq.md
> +vcpkg uses CMake internally as a build scripting language. This is because CMake is already an extremely common build system for cross-platform open source libraries and is becoming very popular for
```suggestion
Vcpkg uses CMake internally as a build scripting language. This is because CMake is already an extremely common build system for cross-platform open source libraries and is becoming very popular for C++ projects in general. It is easy to acquire on Windows, does not require system-wide installation, and legible for unfamiliar users.
```

Beginning of a sentence

2022-06-23 12:59 UTC, Thomas1664 commented on docs/about/faq.md
> +Chocolatey is an excellent system for managing applications. However, it is not currently designed to acquire redistributable developer assets and help you with debugging. vcpkg, in comparison, is de
Same here

2022-06-23 20:01 UTC, ras0219-msft requested changes

2022-06-23 20:01 UTC, ras0219-msft commented on docs/about/faq.md
> +Yes. See the article on [Creating Registries](../maintainers/registries.md). A registry is a catalog of ports, similar to the one provided with vcpkg that contains open source libraries.
I think this should be in-addition-to the advice on packaging, not instead-of.

I assume users reading this FAQ haven't packaged their library yet, which is step 1. Step 2 is (optionally) distribution via a private registry.

2022-06-24 00:41 UTC, AugP commented
Updated PR based on feedback. Let me know if any further changes are needed.

2022-07-25 20:44 UTC, ras0219-msft approved these changes

2022-07-25 20:45 UTC, merged