[QT] arm64-windows build (WIP)
microsoft/vcpkg pull request #25418
Opened 2022-06-24 08:21 UTC by ZacWalk

**Describe the pull request**

- #### What does your PR fix?
This PR adds arm64-windows support for QT

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
 wip - arm64-windows
(https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-06-24 13:18 UTC, ZacWalk commented on ports/qtapplicationmanager/portfile.cmake
> +        stack-walker-arm64.patch
Yep - [that is here](https://github.com/JochenKalmbach/StackWalker/pull/54). There are some long path issues with this build in CI. Wanted to run checks now to discover any problems.

2022-06-29 02:24 UTC, JackBoosY requested changes

2022-06-29 02:24 UTC, JackBoosY commented on ports/qt5-imageformats/vcpkg.json
> +  "port-version": 2,
```suggestion
  "port-version": 1,
```

2022-06-29 02:24 UTC, JackBoosY commented on ports/qtapplicationmanager/vcpkg.json
> +  "port-version": 2,
```suggestion
  "port-version": 1,
```

2022-06-29 06:36 UTC, JackBoosY approved these changes

2022-06-30 20:01 UTC, merged

2022-07-02 10:56 UTC, cenit reviewed
review might have overlooked some changes?

2022-07-02 10:56 UTC, cenit commented on ports/libraw/vcpkg.json
> +  "supports": "!arm & !uwp",
why this platform removal, if it was not broken before? This also cuts out a lot of machines, arm64-osx at the forefront!

2022-07-02 10:56 UTC, cenit commented on ports/osg/vcpkg.json
> +  "supports": "!arm & !uwp",
why this platform removal, if it was not broken before? This also cuts out a lot of machines, arm64-osx at the forefront!

2022-07-02 11:20 UTC, dg0yt commented on ports/osg/vcpkg.json
> +  "supports": "!arm & !uwp",
.. and why does it touch osg at all?

2022-07-02 22:18 UTC, ZacWalk commented on ports/osg/vcpkg.json
> +  "supports": "!arm & !uwp",
This PR extend platform support for jasper to include arm64. This caused breaks in CI for projects like osg and libraw where platform support had relied on support definitions cascading from jasper.

Might be that  "!arm & !uwp" blocks more than I expected and what I really need is "!(arm & uwp)".  I will test with [this PR](https://github.com/microsoft/vcpkg/pull/25535).

Weirdly I see osg:arm64-osx still does not build because of a dependency on x265:

C:\v>vcpkg install osg:arm64-osx
Computing installation plan...
Error: x265[core] is only supported on '!(uwp | arm)'

2022-07-02 23:08 UTC, dg0yt commented on ports/osg/vcpkg.json
> +  "supports": "!arm & !uwp",
Basically, the top-level `supports` has to reflect the `<port>[core]` capabilities. Features can add add further restrictions.
So you need to look for `osg[core]`.

2022-07-03 20:58 UTC, ZacWalk commented on ports/osg/vcpkg.json
> +  "supports": "!arm & !uwp",
@dg0yt in that case I extended the [second PR](https://github.com/microsoft/vcpkg/pull/25535) to reflect what is supported for the each specific port.

 - libraw does support compiling for arm64 but not uwp because of a dependency on CreateFile
 - openexr does not support arm because of some intel intrinsic used
 - osg does not support compiling for uwp but does support arm on other platforms like osx
 - jasper does not support compiling for uwp
 
I was not able to test OSX as I don't have a Mac. I can always iterate if more feedback is provided by Mac developers.