[proxy] Add new port
microsoft/vcpkg pull request #25445
Opened 2022-06-27 06:02 UTC by tian-lt

**Describe the pull request**

- #### What does your PR fix?
  No, this PR is going to add a new port - proxy referring to a GitHub repo: https://github.com/microsoft/proxy

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No.
 *(This is a header-only library*

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR

2022-06-27 12:09 UTC, mingxwa commented on ports/proxy/vcpkg.json
> +  "description": "Proxy: Easy Polymorphism in C++",
Suggested wording: "A single-header C++20 library that facilitates runtime polymorphism."

2022-06-27 12:50 UTC, mingxwa submitted a review, later dismissed

2022-06-27 12:53 UTC, tian-lt commented on ports/proxy/vcpkg.json
> +  "description": "Proxy: Easy Polymorphism in C++",
done.

2022-06-27 12:59 UTC, mingxwa approved these changes, later dismissed

2022-06-29 10:18 UTC, Adela0814 commented
@tian-lt  Thanks for your PR! feel free to ping us if the PR is ready for review.

2022-06-29 13:19 UTC, tian-lt commented
@Adela0814 thank you for reminding.
Marked this PR as ready for review.

2022-06-30 06:17 UTC, mingxwa commented
@Adela0814 I saw the tag "requires:author-response" was added. Which comment are you referring to? Is there any other information required from our side?

cc @tian-lt @BillyONeal

2022-06-30 08:10 UTC, Adela0814 requested changes

2022-06-30 08:33 UTC, tian-lt commented on ports/proxy/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
Thanks for the suggestion.
Added the quotes.

2022-06-30 09:11 UTC, Adela0814 approved these changes

2022-06-30 20:03 UTC, merged