[bitar] Add new port for biar
microsoft/vcpkg pull request #25533
Opened 2022-07-02 19:01 UTC by ljishen

**Describe the pull request**

Add the support for bitar, a C++ library to simplify accessing hardware compression/decompression accelerators.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Support only on Linux

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

2022-07-03 09:50 UTC, dg0yt requested changes
I would suggest to mark your PR as draft if it is still work in progress.

2022-07-03 09:50 UTC, dg0yt commented on ports/bitar/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME arrow CONFIG_PATH lib/cmake/arrow)
Dependencies like `arrow` should be used as port from vcpkg, not build within the consuming port.

2022-07-03 09:50 UTC, dg0yt commented on ports/bitar/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib/cmake")
With proper use of `vcpkg_cmake_config_fixup`, this shouldn't  be necessary.

2022-07-03 09:50 UTC, dg0yt commented on scripts/ci.baseline.txt
> +bitar:x64-linux=fail
Together with `"supports": "linux"`, this disables all CI.

2022-07-03 17:55 UTC, ljishen commented on ports/bitar/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME arrow CONFIG_PATH lib/cmake/arrow)
My next step is to integrate bitar into Arrow. If I rely on the arrow port from vcpkg, there would be circular dependency involved.

2022-07-03 17:58 UTC, ljishen commented on scripts/ci.baseline.txt
> +bitar:x64-linux=fail
This is intentional, because building bitar requires gcc>=10. However, it seems the CI only has GCC 9.

2022-07-03 18:00 UTC, ljishen commented on ports/bitar/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib/cmake")
I thought this is required because I saw similar code from the arrow port. OK.

2022-07-03 18:05 UTC, ljishen commented
> I would suggest to mark your PR as draft if it is still work in progress.

I had a couple of unexpected errors from the CI that I didn't notice from my local development. Sorry for having multiple force pushes. But I think this PR has gotten to the point for reviewing. I will update the code according to your feedback. Thanks!

2022-07-03 18:51 UTC, dg0yt commented on ports/bitar/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME arrow CONFIG_PATH lib/cmake/arrow)
> My next step is to integrate bitar into Arrow.

Not sure what you mean. So the now-new bitar package would be empty soon? 
Or arrow is to use bitar? (I would be worried about mixing symbols from different builds of arrow. And of course you cannot install arrow files (incl. CMake config) from port bitar when arrow will be installed, too. And this problem already exists now for vcpkg CI now, it is just hidden by the lack of an included build triplet.)

2022-07-03 18:51 UTC, dg0yt commented on scripts/ci.baseline.txt
> +bitar:x64-linux=fail
I noticed that already from the comments. However, it is alerting if there is no CI at all.

2022-07-03 18:51 UTC, dg0yt commented on ports/bitar/vcpkg.json
> +  "supports": "linux",
IIUC bitar supports also `freebsd`.

2022-07-03 21:24 UTC, ljishen commented on ports/bitar/vcpkg.json
> +  "supports": "linux",
- I mean I'm expecting to have "bitar" to be one of dependencies of arrow in `arrow/vcpkg.json`
- All arrow relevant symbols/references in bitar will be weak, and therefore can be replaced/overrided by strong ones later when integrated into arrow. So no worry about existing of multiple arrow symbols.
- I will update the code and remove all arrow installed files from the bitar port.
- What should I suppose to do for the altering about no CI?
- Yes, I will add `freebsd` to "supports".

2022-07-03 23:00 UTC, ljishen commented on ports/bitar/vcpkg.json
> +  "supports": "linux",
@[dg0yt](https://github.com/dg0yt) I've stopped installing arrow files by having changes in the upstream.

2022-07-05 20:12 UTC, vicroms commented
I'll rather wait to merge this PR until it has CI coverage, I'll talk with the team about updating our VMs,

2022-07-05 21:24 UTC, ljishen commented
> I'll rather wait to merge this PR until it has CI coverage, I'll talk with the team about updating our VMs,

Alright. Please let me know how it goes.

2022-07-05 22:23 UTC, BillyONeal commented
We wanted to update the fleet to Ubuntu 22.04 last month but ran into a problem because there is no cudnn available yet for that release. Perhaps we need to turn off anyone who forces a dependency on cudnn instead....

2022-07-06 17:42 UTC, ljishen commented
Do you have a plan for when to update the VM?

2022-07-06 18:47 UTC, ljishen commented
Is it possible to update the GCC in the VM without updating the OS version?

2022-07-06 18:48 UTC, BillyONeal commented
We don't want to do that because, by and large, users don't

2022-07-06 19:04 UTC, BillyONeal commented
> I see. I found that other ports like eve, coroutine, and mfl require GCC>=10 as well. So for this PR to be able to accept, do I have to enable and pass at least one of the CI checks?

Our policy on accepting ports that we can't validate has changed with registries becoming a more or less stable feature that people can use as a workaround. Give us until at least this upcoming Patch Tuesday to see if we end up doing 22.04 anyway.

2022-07-06 19:16 UTC, ljishen commented
OK, thanks. Please let me know what I can do to move this PR forward.

2022-07-07 02:35 UTC, dg0yt commented
> I found that other ports like eve, coroutine, and mfl require GCC>=10 as well

Note that these ports can be tested in CI on at least one other triplet than linux.

2022-07-14 18:35 UTC, vicroms commented
depends on #25785

2022-07-14 18:45 UTC, ljishen commented
> depends on #25785

Cool, thanks!

2022-07-18 02:59 UTC, Cheney-W commented
x64-linux failure: 
```
In file included from /mnt/vcpkg-ci/buildtrees/bitar/src/v0.0.1-fe9e9758bc.clean/src/memory.cc:23:
/mnt/vcpkg-ci/buildtrees/bitar/src/v0.0.1-fe9e9758bc.clean/src/include/memory.h:34:10: fatal error: span: No such file or directory
   34 | #include <span>  // NOLINT
      |          ^~~~~~
compilation terminated.
```

2022-07-18 04:57 UTC, ljishen commented
I'll make an update to fix this. Please allow for a few days.

2022-07-29 07:22 UTC, Cheney-W commented
Are there any new changes?

2022-07-30 06:21 UTC, ljishen commented
This is depending on #25899

2022-08-26 06:50 UTC, Cheney-W commented
/azp run

2022-08-26 06:56 UTC, ljishen commented
I'll make an update for this tomorrow.

2022-08-26 21:54 UTC, ljishen commented
I just rebased the code and it causes the CI to also test other ports. Can I just test the bitar alone?

2022-08-29 08:18 UTC, Cheney-W commented
/azp run

2022-09-02 00:44 UTC, ljishen commented
It looks like the port "libilbc" failed in the building. But I don't think I used it as one of the dependencies.

2022-09-02 06:30 UTC, Cheney-W commented
/azp run

2022-09-02 07:12 UTC, ljishen commented
Do you know why it involves the building of "libilbc"?

2022-09-09 10:37 UTC, Cheney-W commented
Could you please merge master for this PR?

2022-09-16 09:14 UTC, Cheney-W commented
I tried to merge master, but I don't have permission to modify your pr.

2022-09-16 17:24 UTC, ljishen commented
Sorry for the late reply. I'll merge it in these few days.

2022-09-30 06:36 UTC, Cheney-W commented
Is work still being done for this PR?

2022-10-01 04:29 UTC, ljishen commented
I've merged the master, but the CI still builds other irrelevant libraries.

2023-01-09 22:20 UTC, vicroms commented on ports/bitar/portfile.cmake
> +    -DBITAR_FETCHCONTENT_OVERWRITE_CONFIGURATION=OFF)
This should be handled already since `vcpkg_cmake_configure()` passes `"-DFETCHCONTENT_FULLY_DISCONNECTED=ON"`

2023-01-09 22:23 UTC, vicroms commented
/azp run

2023-01-10 07:23 UTC, ljishen commented
I'll close this PR because it is not needed anymore.

2023-01-10 07:23 UTC, closed without merging

2023-01-10 07:27 UTC, dg0yt commented
> I'll close this PR because it is not needed anymore.

Was it replaced by another port or PR?

2023-01-10 07:46 UTC, ljishen commented
> > I'll close this PR because it is not needed anymore.
> 
> Was it replaced by another port or PR?

The same function is now officially supported by an SDK maintained by Nvidia. Unless I add distinct features to bitar, I think people will use their version instead of mine.