[json-c] Updated to the last version
microsoft/vcpkg pull request #25565
Opened 2022-07-05 01:24 UTC by luizfernandonb

**Describe the pull request**

- #### What does your PR fix?
  Nothing.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes.`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes.

2022-07-05 05:40 UTC, JonLiu1993 commented on ports/json-c/vcpkg.json
>    "port-version": 2,
```suggestion
```

2022-07-05 05:42 UTC, JonLiu1993 commented
@luizfernandonb ,Thanks for your pr, If you feel able to do so, please consider migrating them to the new functions:
````
vcpkg_install_cmake -> vcpkg_cmake_install (from port vcpkg-cmake)
vcpkg_build_cmake -> vcpkg_cmake_build (from port vcpkg-cmake)
vcpkg_configure_cmake -> vcpkg_cmake_configure (Please remove the option PREFER_NINJA) (from port vcpkg-cmake)
vcpkg_fixup_cmake_targets -> vcpkg_cmake_config_fixup (from port vcpkg-cmake-config)
````
In the ports that use the new function, you have to add the corresponding dependencies:
````
{
  "name": "vcpkg-cmake",
  "host": true
},
{
  "name": "vcpkg-cmake-config",
  "host": true
}
````
The following files are affected:

ports/json-c/portfile.cmake

2022-07-05 05:47 UTC, JonLiu1993 requested changes

2022-07-05 05:47 UTC, JonLiu1993 commented on ports/json-c/vcpkg.json
>    "port-version": 2,
```suggestion
```

2022-07-05 05:47 UTC, JonLiu1993 commented on ports/json-c/vcpkg.json
>    "port-version": 2,
When update port version, we should remove "port-version"

2022-07-05 05:47 UTC, JonLiu1993 commented on versions/j-/json-c.json
> +      "version-date": "2019-09-10",
@luizfernandonb , Please keep the historical json-c.json don't change

2022-07-05 05:47 UTC, JonLiu1993 commented on versions/j-/json-c.json
> +      "version-date": "2019-09-10",
Same as above

2022-07-05 05:47 UTC, JonLiu1993 commented on versions/j-/json-c.json
> +      "version-date": "2019-09-10",
Same as above

2022-07-05 05:47 UTC, JonLiu1993 commented on versions/j-/json-c.json
> +      "version-date": "2019-05-31",
Same as above

2022-07-05 05:48 UTC, JonLiu1993 requested changes

2022-07-05 05:48 UTC, JonLiu1993 commented on ports/json-c/vcpkg.json
>    "description": "A JSON implementation in C",
Please add license in vcpkg.json

2022-07-05 16:02 UTC, Thomas1664 requested changes

2022-07-05 16:02 UTC, Thomas1664 commented on versions/j-/json-c.json
> +      "version-string": "2019-09-10",
Do not modify existing entries.

2022-07-05 16:05 UTC, luizfernandonb commented on versions/j-/json-c.json
> +      "version-string": "2019-09-10",
I put it as it was before at @JonLiu1993's request, I changed it from string to date.

2022-07-05 16:07 UTC, Thomas1664 commented on versions/j-/json-c.json
> +    },
Please remove the old one:

```suggestion
```

2022-07-05 16:07 UTC, luizfernandonb commented on ports/json-c/vcpkg.json
> +  "dependencies": [
It's already between these two.

![image](https://user-images.githubusercontent.com/42288418/177370641-2fbefaf7-171e-47d4-96d1-07644ea6168d.png)

2022-07-05 16:08 UTC, Thomas1664 commented on versions/j-/json-c.json
> +      "version-string": "2019-09-10",
Yes, but not in this file. This is for the version database. Every version of this port is stored here. You can't modify old entries because the ports' `vcpkg.json` contained `version-string` at that time.

2022-07-05 16:12 UTC, Thomas1664 commented on ports/json-c/vcpkg.json
> +  "dependencies": [
I reviewed before you pushed your commit.

2022-07-05 16:13 UTC, luizfernandonb commented on ports/json-c/vcpkg.json
> +  "dependencies": [
Ok.

2022-07-05 16:15 UTC, Thomas1664 commented on versions/j-/json-c.json
> +      "version-string": "2019-09-10",
I don't understand your question. The only place you change `version-string` to `version-date` is `vcpkg.json`. The command `vcpkg x-add-version json-c` updated the version database accordingly.

2022-07-05 16:20 UTC, luizfernandonb commented on versions/j-/json-c.json
> +      "version-string": "2019-09-10",
I asked if I leave it as a string or leave it as a date because you said not to modify the entries in the file "versions/j-/json-c.json", and the entry you were referring to was "2019-09-10" which was a "version-string" and I changed it to "version-date", but I reversed this change at the request of @JonLiu1993, so I believe there is nothing wrong in this case and we can mark it as resolved.

2022-07-05 16:24 UTC, Thomas1664 commented on versions/j-/json-c.json
> +      "version-string": "2019-09-10",
Yes, but the other comment you marked as resolved isn't resolved. You are only allowed to add 1 entry, so remove your old one. Finally CI complains about wrong commit hashes. You can fix this using `vcpkg x-add-version json-c --overwrite-version`

2022-07-05 17:05 UTC, luizfernandonb commented
@Thomas1664, @JonLiu1993 done.

2022-07-06 02:52 UTC, JonLiu1993 requested changes

2022-07-06 02:52 UTC, JonLiu1993 commented on ports/json-c/vcpkg.json
> +  "license": null,
```suggestion
  "license": "MIT",
```

2022-07-06 02:52 UTC, JonLiu1993 commented on ports/json-c/vcpkg.json
> +  "license": null,
There should be "MIT" license, you can refer to [this ](https://spdx.org/licenses/MIT.html)

2022-07-06 02:52 UTC, JonLiu1993 commented on ports/json-c/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2022-07-06 02:52 UTC, JonLiu1993 commented on ports/json-c/portfile.cmake
Please put double quotes around the absolute path below

2022-07-07 10:37 UTC, JonLiu1993 approved these changes

2022-07-07 21:19 UTC, merged