[Document] Improve documentation with a straight to the point example
microsoft/vcpkg pull request #25655
Opened 2022-07-09 14:05 UTC by ryuukk

Improves documentation

2022-07-11 14:39 UTC, Neumann-A commented on README.md
> +vcpkg install mongoose[ssl]:x64-windows-static
```suggestion
vcpkg install mongoose[ssl]:x64-windows-static --host-triplet=x64-windows
```
+ add description

2022-07-11 20:26 UTC, dg0yt commented on README.md
> +                      feature
~~~
vcpkg install mongoose[core,ssl]:x64-windows-static
                       |
                       feature list

2022-07-11 22:29 UTC, vicroms requested changes

2022-07-11 22:29 UTC, vicroms commented on README.md
> +                      feature
```suggestion
vcpkg install mongoose[ssl]:x64-windows-static
              |       |    | 
              package |    target triplet
                      |
                      feature list
```

fix off-by-one in format

2022-07-29 07:23 UTC, Cheney-W commented
@ryuukk  Can you address the review suggestions? Thanks!

2022-08-05 07:21 UTC, Cheney-W commented
Pinging @ryuukk for response. Is work still being done for this PR?

2022-08-08 17:15 UTC, vicroms commented
The only problem I have with this type of formatting is that it doesn't work well with screen readers. I'd rather we use a proper image with alt-text or do a better job of explaining this topic textually.

2022-08-08 19:16 UTC, BillyONeal commented on README.md
> +vcpkg install mongoose[ssl]:x64-windows-static
I don't expect most people to need to pass `--host-triplet` so I think it's better to not include it in the first front-line example.

2022-08-08 22:46 UTC, ras0219-msft reviewed
A few concerns:
- As @vicroms mentioned above, screen readers interact poorly with ascii art, so at a minimum we should look at leveraging html accessibility practices. https://stackoverflow.com/questions/22676072/how-do-i-hide-ascii-art-from-screen-readers-and-other-at-using-aria-html5 looks like a good start.
- This presents classic mode as the primary and only example, however many users are best served by manifest mode. If we're going to present an inline example like this, I think it should be our "best foot forward" -- manifest mode.

2022-08-11 20:04 UTC, BillyONeal commented
Dropping vcpkg-team-review because all the folks who should review already have.

2022-08-19 06:45 UTC, Cheney-W commented
Pinging @ryuukk for response. Is work still being done for this PR?

2022-08-26 06:48 UTC, Cheney-W commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2022-08-26 06:48 UTC, closed without merging