Add caffe port.
microsoft/vcpkg pull request #2570
Opened 2018-01-14 00:16 UTC by vlj

This port is adding caffe-1.0 to vcpkg.
While caffe2 is newer it's not completly backward compatible which motivates this port. Additionnaly Caffe has an opencl branch (this is so far the only Deep Learning Framework with an opencl backend so far) which I'd like to bring to vcpkg through features.

Initially there is no CUDA/OpenCV/Python/Matlab support.

2018-01-14 21:08 UTC, vlj commented
Added python support

2018-01-15 22:18 UTC, jasjuang commented
Just wondering did you check out @willyd 's port https://github.com/BVLC/caffe/issues/5674? His port works with OpenCV and CUDA but he never submitted a PR to vcpkg (not sure why). Can you look into it and update this PR?

2018-01-16 13:26 UTC, willyd commented
@vjl This port has been on my TODO list for a while now. I have one that works but is different from yours in some ways:

- Mine is based off the caffe/windows branch
- Mine supports CUDA and OpenCV
- Your supports Python. I wonder how this is possible, vcpkg overwrites the PATH variable so CMake can't find my Anaconda Python. 
- Mine supports Dynamic linking (Also supports static linking in theory, but I haven't tried to build it yet)

I haven't submitted a PR since I needed to make some changes to the caffe code base for the port to work and I still need to find some time to merge the changes in the caffe windows branch.

Would you like to collaborate on this?

2018-01-17 20:18 UTC, vlj commented
I added CUDA and OpenCV using @willyd branch. I checked both and OpenCV works, but Cuda fails with the following :
"fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!"

I have vanilla Python 3 installed and I didn't get issue at all. I suspect vcpkg uses it's own python, but relies on Python_packages_path envvar to find Numpy.

For me dynamic linking builds but doesn't work, caffe executable fails because protobuf is misleaded by a static symbol found twice. This is an instance of this bug : https://github.com/BVLC/caffe/issues/1917

The branch is based on the 1.0 release with patch backported from the Windows branch.

2018-01-17 20:26 UTC, jasjuang commented
@vlj I suspect you are using VS2017 15.5, unfortunately you need to downgrade it to VS2017 15.4 for CUDA to work. See https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/

2018-01-17 21:07 UTC, willyd commented
@vlj There is a detail writeup on a to workaround the CUDA issue here: https://github.com/BVLC/caffe/issues/5654#issuecomment-354539618

As @jasjuang mentionned the safest route is probably to downgrade until NVIDIA releases an update.

2018-01-17 21:13 UTC, willyd commented
> I have vanilla Python 3 installed and I didn't get issue at all. I suspect vcpkg uses it's own python, but relies on Python_packages_path envvar to find Numpy.

I guess CMake looks up the Python registry entries. This won't work with conda environments and virtual envs. Sad.

> For me dynamic linking builds but doesn't work, caffe executable fails because protobuf is misleaded by a static symbol found twice. This is an instance of this bug : BVLC/caffe#1917

Yeah, I had to fiddle a lot with the build to get this to work. Changed caffeproto from STATIC to OBJECT and changed the protoc command line call in Protobuf.cmake. See this commit https://github.com/willyd/caffe/commit/8aee77a3b8983310dab023f94d427c18caebfa48

2018-01-20 19:45 UTC, vlj commented
I updated the port so that it uses dynamic instead of static, using @willyd tips (declaring proto as OBJECT instead of STATIC). I also had to use the same tricks for pycaffe.

With these modifications I got Deepdream script working : https://www.alanzucconi.com/2016/05/25/generating-deep-dreams/
natively on Windows with dynamic linked caffe.

Unfortunatly the static version doesn't work, it looks like it strips static symbol when linking proto (hence the layers descriptions are not found when pycaffe is loaded and it's not possible to use any caffeproto file). I will import the export related code in static build in the Windows branch of caffe I guess.

2018-01-20 23:51 UTC, willyd commented
@vjl This is great! Use the /wholearchive linker flag. This way you won't need to use the pragma trick that I implemented in the windows branch. I am going to drop this along VS 2013 support anyway.

2018-01-21 17:38 UTC, vlj commented
Actually I had to revert back to using static linking to enable CUDA support ; OBJECT doesn't accept *.cu file.
I got Deepdream python script working however it gives me some strange result with the sky picture, as if it was random :

![0322](https://user-images.githubusercontent.com/6413475/35197007-2e889aaa-feda-11e7-8cf8-523ee90b61d7.jpg)

2018-01-22 00:52 UTC, willyd commented
@vjl It was only necessary to use `OBJECT` for the caffeproto library. This library does not include any .cu files. You have to use the `WINDOWS_EXPORT_ALL_SYMBOLS` CMake trick though. 

Can't comment on the DeepDream result I always wanted to try it but never got to it. I usually try MNIST or just a simple linear regression to see if everything is working fine.

2018-01-22 20:22 UTC, vlj commented
I opened an issue here : https://github.com/BVLC/caffe/issues/6192

2018-01-23 15:06 UTC, ras0219-msft commented
LMK when this is ready to be merged :)

2018-01-24 20:52 UTC, vlj commented
I'm a bit puzzled since the caffe prebuilt binaries from this link : https://github.com/BVLC/caffe/tree/windows
works properly with the deepdream script. 

Unit tests mostly pass.
There's some patch I didn't import like the one moving Template from headers to cpp files (but I think using /WHOLEARCHIVE flag is equivalent) and some fix to MakeTempDirectory but I'm not sure it's used for anything but tests. There's also leveldb which is missing but it doesn't seem to be used to load caffemodel files.
I'm investigating

2018-01-25 20:56 UTC, vlj commented
It looks like protobuf fails to load the caffemodel file, I don't know why. I modified the proto definition by adding an underscore to STRICT and PERMISSIVE, but removing them and manually changing the var definition in the autogenerated file doesn't seem to have any influence.

2018-01-27 22:26 UTC, vlj commented
I fixed the issue, actually I missed a hunk (open needs the binary flag to read caffeproto files).
The branch should be ready to merge I think.

2018-02-03 18:01 UTC, vlj commented
Feedback ?

2018-02-04 05:43 UTC, jasjuang commented
Looks great to me! can't wait to see it to be merged

2018-02-04 14:40 UTC, willyd commented on ports/caffe/0001-Use-vcpkg-dependencies.patch
> ++list(APPEND Caffe_LINKER_LIBS PUBLIC hdf5-shared hdf5_hl-shared)
x64-windows-static would require to link to hdf5-static here.

2018-02-04 14:42 UTC, willyd commented on ports/caffe/0002-Fix-permissive-strict.patch
> +-    PERMISSIVE = 1;
We should use the NO_STRICT compile definition instead.

2018-02-04 14:43 UTC, willyd commented on ports/caffe/0002-Fix-permissive-strict.patch
> +-    PERMISSIVE = 1;
Ditto.

2018-02-04 17:18 UTC, willyd commented on ports/caffe/0004-Export-fix.patch
> ++set_target_properties(pycaffe PROPERTIES LINK_FLAGS "/WHOLEARCHIVE:caffe.lib")
Would a generator expression work here: `/WHOLEARCHIVE:$<TARGET_FILE_NAME:caffe>`?

2018-02-04 17:21 UTC, willyd commented on ports/caffe/0004-Export-fix.patch
> ++set_target_properties(gtest PROPERTIES LINK_FLAGS_RELEASE "/WHOLEARCHIVE:caffe")
Should probably be in the LINK_INTERFACE_LIBRARIES of the caffe lib instead.

2018-02-04 17:27 UTC, willyd commented on ports/caffe/portfile.cmake
> +#file(COPY ${CURRENT_PACKAGES_DIR}/debug/lib/caffe-d.dll DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin)
You should use vcpkg_fixup_cmake_targets too!

2018-02-04 17:27 UTC, willyd commented
@vlj Please see my comments on your patches.

2019-08-28 22:50 UTC, cbezault commented
/azp run

2020-01-14 05:56 UTC, NancyLi1013 commented
/azp run

2020-01-14 07:07 UTC, NancyLi1013 requested changes

2020-01-14 07:07 UTC, NancyLi1013 commented on ports/caffe/portfile.cmake
> +    ${CMAKE_CURRENT_LIST_DIR}/0009-Fix-Cuda.patch
Can these patches be submitted upstream?

Besides this, `vcpkg_apply_patches()` is deprecated, if there are some patches needed by this port, please use `vcpkg_from_github()` instead.

2020-01-31 01:02 UTC, dan-shaw commented
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

2020-01-31 01:02 UTC, closed without merging