Add Unicode support to Curl
microsoft/vcpkg pull request #25865
Opened 2022-07-19 11:12 UTC by rozdaybeda

**Describe the pull request**

- #### What does your PR fix?
  Fixes unicode support for curl

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  windows, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-07-19 12:58 UTC, autoantwort requested changes

2022-07-19 12:58 UTC, autoantwort commented on ports/curl/portfile.cmake
> +
```suggestion
```

2022-07-20 06:05 UTC, m-kuhn commented
Should this be added to default features?

2022-07-20 15:14 UTC, rozdaybeda commented
> Should this be added to default features?

I think it should be enabled by default for windows

2022-07-21 09:04 UTC, rozdaybeda commented on ports/curl/portfile.cmake
> +
![image](https://user-images.githubusercontent.com/3129784/180174903-66a65566-84ff-4867-94aa-46fdf0696bfd.png)
https://github.com/curl/curl/blob/master/CMakeLists.txt

2022-07-21 10:02 UTC, autoantwort commented on ports/curl/vcpkg.json
> +      "description": "Enables the Unicode version of the Windows API functions"
Because of that, see my next comment

2022-07-21 10:03 UTC, autoantwort commented on ports/curl/portfile.cmake
> +
Because of that, see my next comment

2022-08-05 08:44 UTC, JonLiu1993 commented
@rozdaybeda, Can you please resolve the conflicts against master?

2022-08-08 03:01 UTC, JonLiu1993 commented
@rozdaybeda, I agree with @autoantwort, can you revise it?

2022-08-11 02:36 UTC, JonLiu1993 commented
@rozdaybeda, These two suggestions should be adopted, what do you think?
https://github.com/microsoft/vcpkg/pull/25865#discussion_r924470115
https://github.com/microsoft/vcpkg/pull/25865#discussion_r924470405

2022-08-11 17:41 UTC, rozdaybeda commented
> 

The first one doesn't fit and here's why: [#25865](https://github.com/microsoft/vcpkg/pull/25865#discussion_r926437890)
I think it makes sense to add only the second suggestion.

Thanks

2022-08-12 02:37 UTC, JonLiu1993 commented
All functions were successfully tested except for feature 'sectransp' in the following triples:
- x86-windows
- x64-windows
- x64-windows-static

2022-08-12 09:53 UTC, Thomas1664 commented on ports/curl/portfile.cmake
> +
@rozdaybeda Because you're using `"supports": "windows"` in `vcpkg.json`, this is no longer needed and can be removed as proposed by @autoantwort.

2022-08-12 22:39 UTC, BillyONeal requested changes
I don't believe we can accept this because it's using a feature to control alternatives: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-control-alternatives-in-published-interfaces

It may make sense to do unconditionally on Windows (which is why I'm not outright closing the PR).

2022-08-23 00:36 UTC, BillyONeal commented
> I don't believe we can accept this because it's using a feature to control alternatives: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-control-alternatives-in-published-interfaces
> 
> It may make sense to do unconditionally on Windows (which is why I'm not outright closing the PR).

I don't believe anything about this has been addressed.

To be clear, it can never be a requirement for correctness that a feature is *not* installed.

2022-09-01 07:43 UTC, rozdaybeda commented
@BillyONeal  does it work for you?
```
if(VCPKG_TARGET_IS_WINDOWS)
    list(APPEND OPTIONS -DENABLE_UNICODE=ON)
endif()
```

Or would that be better?
```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS 
        "-DCMAKE_PROJECT_INCLUDE=${CMAKE_CURRENT_LIST_DIR}/cmake-project-include.cmake"
        ${FEATURE_OPTIONS}
        ${OPTIONS}
        ...
	-DENABLE_UNICODE=ON
    OPTIONS_DEBUG
        -DENABLE_DEBUG=ON
)
```

2022-09-01 22:34 UTC, BillyONeal approved these changes

2022-09-01 22:35 UTC, BillyONeal commented
> @BillyONeal does it work for you?
> 
> ```
> if(VCPKG_TARGET_IS_WINDOWS)
>     list(APPEND OPTIONS -DENABLE_UNICODE=ON)
> endif()
> ```

It works for me!

@bagder @MarcelRaad @apique Is there any reason we should not just turn this on unconditionally?

2022-09-02 07:21 UTC, MarcelRaad commented
It doesn't do anything on non-Windows platforms, so turning it on unconditionally shouldn't hurt.

2022-09-02 20:46 UTC, merged

2022-09-02 20:46 UTC, BillyONeal commented
Thanks for your contribution @rozdaybeda !