[inih] Upgrade from r51 to r56
microsoft/vcpkg pull request #25879
Opened 2022-07-20 04:16 UTC by SamuelMarks

**Describe the pull request**
https://github.com/benhoyt/inih/releases

56

> Two updates:
> 
>   https://github.com/benhoyt/inih/pull/137
>   https://github.com/benhoyt/inih/pull/140

55

> Added "version" to meson.build config: https://github.com/benhoyt/inih/pull/135 (but bumped up to 55 in a subsequent commit, for this release).

54

> Mainly https://github.com/benhoyt/inih/pull/134, adding the visibility symbols to the Meson build config, but also [other small tweaks](https://github.com/benhoyt/inih/compare/r53...r54) to tests and so on.

53

> Updates to Meson config:
> 
>   https://github.com/benhoyt/inih/pull/124 meson: optionally depend on C++
>   https://github.com/benhoyt/inih/pull/125 meson: enable distro settings by default
>   https://github.com/benhoyt/inih/pull/126 meson: add static compile args to inih_dep

52
> Add INI_CUSTOM_ALLOCATOR to allow using a custom memory allocator. Per the README:
> 
>     By default when using the heap, the standard library's malloc, free, and realloc functions are used; to use a custom allocator, specify -DINI_CUSTOM_ALLOCATOR=1 (and -DINI_USE_STACK=0). You must define and link functions named ini_malloc, ini_free, and (if INI_ALLOW_REALLOC is set) ini_realloc, which must have the same signatures as the stdlib.h memory allocation functions.
> 
> See [tests/unittest_alloc.c](https://github.com/benhoyt/inih/blob/master/tests/unittest_alloc.c) for an example.
> 
> Fixes https://github.com/benhoyt/inih/issues/118.

- #### What does your PR fix?

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-07-20 10:39 UTC, JonLiu1993 requested changes

2022-07-20 10:39 UTC, JonLiu1993 commented on ports/inih/CMakeLists.txt
>      TARGETS inih
@SamuelMarks ,Thanks for your pr, could you please export the config.cmake file?

2022-07-20 20:55 UTC, SamuelMarks commented on ports/inih/CMakeLists.txt
>      TARGETS inih
Did something along those lines, does it need to be `unofficial`?

2022-07-21 07:19 UTC, JonLiu1993 commented on ports/inih/CMakeLists.txt
>      TARGETS inih
YES

2022-07-21 07:38 UTC, JonLiu1993 submitted a review, later dismissed

2022-07-21 07:39 UTC, JonLiu1993 commented
Tested the usage successfully

2022-07-22 20:53 UTC, BillyONeal commented
This is becoming a relatively large build system replacement. Do you know why we aren't just using upstream's meson one?

2022-07-28 03:50 UTC, SamuelMarks commented
My main goal was debugging why it was getting my `#define`'d or `target_compile_definitions` params so I updated the port you already had in order to fix it. No opinion about build systems (us or theirs).

2022-08-05 15:46 UTC, Thomas1664 reviewed
I would like to see that `vcpkg_cmake_config_fixup` is used + quotes around paths.

2022-08-05 15:46 UTC, Thomas1664 commented on ports/inih/portfile.cmake
>  file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
```suggestion
file(COPY "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DESTINATION "${SOURCE_PATH}")
```

Please put paths in quotes (same below).

2022-08-05 15:46 UTC, Thomas1664 commented on ports/inih/portfile.cmake
> +vcpkg_cmake_install()
```suggestion
vcpkg_cmake_install()
vcpkg_cmake_config_fixup()
```

Ports should use `vcpkg_cmake_config_fixup` when exporting cmake config.

2022-08-05 15:46 UTC, Thomas1664 commented on ports/inih/portfile.cmake
> +                    "${CURRENT_PACKAGES_DIR}/debug/include")
You should replace `inih` with `${PORT}` in the line above to ensure that the location copyright file aligns with the port name.

2022-08-06 06:21 UTC, BillyONeal requested changes
I agree with @Thomas1664 's comments

2022-08-06 06:22 UTC, BillyONeal commented
(I tried to push a fix for you but:
![image](https://user-images.githubusercontent.com/1544943/183237112-9ffb2c0c-5044-4d1d-9208-7ef13bf4880f.png)
)

2022-08-06 22:33 UTC, SamuelMarks commented
I'll manually make these changes and/or apply the given patch first chance I get (probably 24 hours from now)

In the interim I've given [@BillyONeal](https://github.com/BillyONeal) write access to my vcpkg port

2022-08-06 22:33 UTC, SamuelMarks commented
I'll manually make these changes and/or apply the given patch first chance I get (probably 24 hours from now)

In the interim I've given [@BillyONeal](https://github.com/BillyONeal) write access to my vcpkg fork

2022-08-10 20:30 UTC, BillyONeal approved these changes, later dismissed

2022-08-11 00:09 UTC, BillyONeal commented
@SamuelMarks I had to make significant changes in order to get this to pass in CI, because this stealth-merge-conflicted with https://github.com/microsoft/vcpkg/pull/26145 which depends on headers this was no longer installing. Please double check that you are happy with these changes.

2022-08-11 00:12 UTC, BillyONeal approved these changes, later dismissed

2022-08-11 01:59 UTC, JonLiu1993 approved these changes, later dismissed

2022-08-18 08:16 UTC, JonLiu1993 commented
@SamuelMarks, Please double check that you are happy with these changes.

2022-08-18 23:46 UTC, SamuelMarks commented
Yes I'm sure this is fine

2022-08-19 00:13 UTC, BillyONeal commented
Thanks for your contribution and thanks for confirming. I resolved the merge conflict and will merge as soon as PR build is green. Thanks!

2022-08-19 00:15 UTC, merged