[anyrpc] Add MinGW support
microsoft/vcpkg pull request #25901
Opened 2022-07-21 05:44 UTC by m-kuhn

Ports https://github.com/sgieseking/anyrpc/pull/46

- #### What does your PR fix?
  Fixes MinGW support for anyrpc

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-07-21 09:13 UTC, FrankXie05 commented on ports/anyrpc/mingw.patch
> ++            _WIN32_WINNT=0x0A00
```suggestion
+            WINVER=0x0A00
+            _WIN32_WINNT=0x0A00
```
As far as I know, the variable of this macro is for windows10, can you explain it in detail?  :)

2022-07-21 10:21 UTC, m-kuhn commented on ports/anyrpc/mingw.patch
> ++            _WIN32_WINNT=0x0A00
I am not upstream maintainer so I cannot tell.
What I can tell is it fixes mingw.

2022-07-21 12:29 UTC, longnguyen2004 commented
Could probably add a note to remove the patch once https://github.com/sgieseking/anyrpc/pull/46 is merged, otherwise LGTM!

2022-07-21 12:30 UTC, longnguyen2004 approved these changes, later dismissed

2022-07-22 01:59 UTC, FrankXie05 requested changes

2022-07-22 01:59 UTC, FrankXie05 commented on ports/anyrpc/portfile.cmake
> +        mingw.patch
```suggestion
        mingw.patch #Remove this patch in the next version 
```

2022-07-22 02:01 UTC, FrankXie05 commented on ports/anyrpc/mingw.patch
> ++            _WIN32_WINNT=0x0A00
Thanks for your reply, we accept this patch. We should add a note saying: Remove this patch in the next version

2022-07-22 05:59 UTC, FrankXie05 approved these changes

2022-07-25 21:53 UTC, BillyONeal commented
I want to give upstream an opportunity to merge (or not) https://github.com/sgieseking/anyrpc/pull/46 before merging this.

2022-08-26 17:29 UTC, m-kuhn commented
How long do we want to wait for upstream to merge (or not)?

2022-08-29 02:03 UTC, FrankXie05 commented
@m-kuhn At least a month, we may merge this pr if upstream doesn't respond for a long time. :)

2022-08-29 02:46 UTC, FrankXie05 commented
@BillyONeal Can we merge this pr, due to upstream not responding for a long time.

2022-08-29 13:50 UTC, longnguyen2004 commented
Just merge this, since the purpose of a patch is to add something upstream doesn't have anyway

2022-08-29 15:56 UTC, BillyONeal commented
> How long do we want to wait for upstream to merge (or not)?

It's been a month, that's enough for me. :)

Moreover, upstream indicated that they don't have serious problems with the direction in https://github.com/sgieseking/anyrpc/pull/46#issuecomment-1191687257

Thanks for your contribution!

2022-08-29 15:56 UTC, merged