[nrf-ble-dirver] Fix possible conflicting files
microsoft/vcpkg pull request #25900
Opened 2022-07-20 23:27 UTC by Thomas1664

**Describe the pull request**

- #### What does your PR fix?
  This port installed its license file to a possible conflicting location:

```
nrf-ble-driver:x64-linux:/share/LICENSE
nrf-ble-driver:x64-linux:/share/nrf-ble-driver/copyright
```

2022-07-21 02:51 UTC, JonLiu1993 requested changes

2022-07-21 02:51 UTC, JonLiu1993 commented on ports/nrf-ble-driver/vcpkg.json
> +  "license": null,
```suggestion
  "license": "BSD-3-Clause",
```

2022-07-22 02:47 UTC, JonLiu1993 approved these changes

2022-07-22 21:39 UTC, merged

2022-07-22 21:39 UTC, BillyONeal commented
Thank you!