Wxwidgets 3.2
microsoft/vcpkg pull request #25943
Opened 2022-07-23 12:15 UTC by dg0yt

Continues #25717. Alternative to #25931. Thanks to @talregev and @DragonJoker.

- #### What does your PR fix?
  Updates wxWidgets to 3.2.0.
  Updates the CMake wrapper to make CMake's `FindwxWidgets.cmake` work with 3.2.
  Adds a test for the new exported CMake config to `vcpkg-ci-wxwidgets`.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-07-23 13:09 UTC, talregev commented
I will test it with our opensource. Also I will check this issue:
https://github.com/microsoft/vcpkg/issues/25786

Thank you for this PR!

2022-07-23 14:22 UTC, talregev commented
Windows is working:
![image](https://user-images.githubusercontent.com/7043539/180609153-3dbdd02d-ee0c-4ebf-bc24-6ba3d5bfd8a5.png)


Linux we have compilation issue: 
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'XGetWindowAttributes'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
https://github.com/BOINC/boinc/pull/4852

Not sure how to solve it.

2022-07-23 14:50 UTC, dg0yt commented
> Linux we have compilation issue

The Linux build depends on system libs and pc files.
There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.

2022-07-23 14:58 UTC, talregev commented
> > Linux we have compilation issue
> 
> The Linux build depends on system libs and pc files. There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.

I think it missing -lX11 flag. Also when compile with webview it missing the flags for webview that I add manually. We are using `wx-config --libs`

2022-07-23 15:02 UTC, talregev commented
It mean the flags that produce in upstream `wx-config --libs` and vcpkg `wx-config --libs` are different.

2022-07-23 15:49 UTC, talregev commented
> > > Linux we have compilation issue
> > 
> > 
> > The Linux build depends on system libs and pc files. There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.
> 
> I think it missing -lX11 flag. Also when compile with webview it missing the flags for webview that I add manually. We are using `wx-config --libs`

@dg0yt I solve this problem by adding the `-lX11` flag manually. This is not a blocking issue for this PR. (also this PR make it). 
And should fix it in a different PR. I will open an issue about this.

2022-07-23 15:50 UTC, talregev commented
Works on ubuntu 20.04

![image](https://user-images.githubusercontent.com/7043539/180612539-ccf07713-7617-432f-9162-40e53c7840aa.png)

2022-07-23 15:50 UTC, talregev commented
This issue remain: "Cannot run wxwidgets on ubuntu 22.04":
https://github.com/microsoft/vcpkg/issues/25786

2022-07-23 15:56 UTC, dg0yt commented
> It mean the flags that produce in upstream `wx-config --libs` and vcpkg `wx-config --libs` are different.

Sure. Mostly due to the change in FindGTK3. It is turning `-lX11` into `/usr/lib/x86_64-linux-gnu/libX11.so`. 
This change ensures that libs search paths from the pc files are actually used, not lost.

2022-07-23 15:59 UTC, dg0yt commented
> This issue remain: "Cannot run wxwidgets on ubuntu 22.04".

I'm not surprised, as long as the system gtk3 is used.

2022-07-23 16:00 UTC, talregev commented
> > It mean the flags that produce in upstream `wx-config --libs` and vcpkg `wx-config --libs` are different.
> 
> Sure. Mostly due to the change in FindGTK3. It is turning `-lX11` into `/usr/lib/x86_64-linux-gnu/libX11.so`. This change ensures that libs search paths from the pc files are actually used, not lost.

So it should also reflected in wx-config. 
I will print both versions in the issue (upstream and vcpkg).

2022-07-23 16:00 UTC, talregev commented
> > This issue remain: "Cannot run wxwidgets on ubuntu 22.04".
> 
> I'm not surprised, as long as the system gtk3 is used.

Can you elaborate?

2022-07-23 16:00 UTC, talregev commented
Also I want to say thank you for your hard work and continue my PR.

2022-07-23 16:42 UTC, dg0yt commented
> > > This issue remain: "Cannot run wxwidgets on ubuntu 22.04".
> > 
> > I'm not surprised, as long as the system gtk3 is used.
> 
> Can you elaborate?

Take libpng and x64-linux (static):
 - Vcpkg wxwidgets (static lib) itself is built against vcpkg libpng (static lib).
 - System gtk (dynamic lib) was built against system libpng (dynamic lib).
 - When linking a program, it is only vcpkg libpng (static lib) which makes it to the link editor command line, and code from this library will end up in the executable.
 - When running the program, the dynamic linker will still load the system libpng (dynamic lib). Now your running process has code from system libpng and from vcpkg libpng, possibly different versions and configurations. When data is passed around between these world, can you be sure that they share the same interpretation of the data?

After looking at `ldd buildtrees/vcpkg-ci-wxwidgets/x64-linux-dbg/main` output, there are more such libs:
z, expat, lzma
Your app itself may add more.

Disclaimer: I have only very basic knowledge on linking and symbols.

2022-07-23 16:44 UTC, talregev commented
> > > > This issue remain: "Cannot run wxwidgets on ubuntu 22.04".
> > > 
> > > 
> > > I'm not surprised, as long as the system gtk3 is used.
> > 
> > 
> > Can you elaborate?
> 
> Take libpng and x64-linux (static):
> 
> * Vcpkg wxwidgets (static lib) itself is built against vcpkg libpng (static lib).
> * System gtk (dynamic lib) was built against system libpng (dynamic lib).
> * When linking a program, it is only vcpkg libpng (static lib) which makes it to the link editor command line, and code from this library will end up in the executable.
> * When running the program, the dynamic linker will still load the system libpng (dynamic lib). Now your running process has code from system libpng and from vcpkg libpng, possibly different versions and configurations. When data is passed around between these world, can you be sure that they share the same interpretation of the data?
> 
> After looking at `ldd buildtrees/vcpkg-ci-wxwidgets/x64-linux-dbg/main` output, there are more such libs: z, expat, lzma Your app itself may add more.
> 
> Disclaimer: I have only very basic knowledge on linking and symbols.

Thank you for your detail explanations!
You have more knowledge on linking and symbols than I do.

2022-07-24 20:55 UTC, talregev commented
@JackBoosY Can you review?

2022-07-26 02:55 UTC, JackBoosY requested changes

2022-07-26 02:55 UTC, JackBoosY commented on ports/wxwidgets/portfile.cmake
> +vcpkg_find_acquire_program(PKGCONFIG)
```suggestion
else()
    vcpkg_find_acquire_program(PKGCONFIG)
endif()
```

2022-07-26 03:02 UTC, dg0yt commented on ports/wxwidgets/portfile.cmake
> +vcpkg_find_acquire_program(PKGCONFIG)
Pointless. If `PKGCONFIG` is set, `vcpkg_find_acquire_program(PKGCONFIG)` is a no-op.
And wrong. Because it may be needed if there is no system `pkg-config`.

2022-07-27 02:55 UTC, JackBoosY approved these changes

2022-07-27 02:56 UTC, JackBoosY commented
No need to test all the features since we have the test port.

2022-07-27 18:42 UTC, BillyONeal commented
> The Linux build depends on system libs and pc files. There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.

22.04*

2022-07-27 18:51 UTC, BillyONeal commented
Yikes! What a mess, thanks for fighting it!

2022-07-27 18:51 UTC, merged