Cpuinfo updated to last commit from 2022-07-19
microsoft/vcpkg pull request #25974
Opened 2022-07-25 14:15 UTC by vladimir-aubrecht

**Describe the pull request**
Cpuinfo updated to last commit from 2022-07-19

- #### What does your PR fix?
- New version is adding win-arm64 support.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-07-25 15:54 UTC, Neumann-A commented on ports/cpuinfo/vcpkg.json
> +  "port-version": 2,
```suggestion
```

if you update `version: x` you delete `port-version`

2022-07-27 02:48 UTC, JackBoosY commented on ports/cpuinfo/vcpkg.json
> +  "supports": "!(uwp & arm32)",
It seems that this port support uwp before, what's going wrong on this version?

2022-07-27 16:13 UTC, vladimir-aubrecht commented on ports/cpuinfo/vcpkg.json
> +  "supports": "!(uwp & arm32)",
Actually it did support UWP only on non-arm platforms.
This version added arm64 support, which wasn't supported before and which also supports UWP now.
What is not supported (and wasn't supported) is UWP on arm32 only as code of the library has unfortunately written condition which checks if it's arm64 else do x86/x64 branch 😕

2022-07-28 02:30 UTC, JackBoosY submitted a review, later dismissed

2022-07-28 02:34 UTC, JackBoosY commented
Already tested all features successsfully on x86-windows and x64-windows-static.

2022-07-28 07:44 UTC, Thomas1664 requested changes

2022-07-28 07:44 UTC, Thomas1664 commented on versions/c-/cpuinfo.json
> +    },
```suggestion
    {
      "git-tree": "5ee1eff9fe6cfa584b697e71ce7081a69ef2c51d",
      "version-date": "2022-07-19",
      "port-version": 0
    },
```

You may add at most only one version.

2022-07-28 07:45 UTC, JackBoosY approved these changes

2022-07-30 04:30 UTC, merged

2022-07-30 04:30 UTC, ras0219-msft commented
LGTM, thanks!