[dv-processing] Update to latest version
microsoft/vcpkg pull request #25992
Opened 2022-07-26 16:04 UTC by jureviciusr

**Describe the pull request**

- #### What does your PR fix?
Update to newly released version 1.5.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
yes

2022-07-28 06:35 UTC, JonLiu1993 requested changes

2022-07-28 06:35 UTC, JonLiu1993 commented on ports/dv-processing/portfile.cmake
> +        REF 96d082a862bb1e5bfdc79b39aa09e7a50c2dac49
@jureviciusr, Thanks for your pr, currently the latest stable version is 1.5.0 and the commit id is 
9b1d8bb2e2223f76a4b1f12ae3998933947855b3, could you please change the REF?

2022-07-28 06:35 UTC, JonLiu1993 commented on ports/dv-processing/vcpkg.json
> +  "port-version": 2,
```suggestion
```

2022-07-28 06:35 UTC, JonLiu1993 commented on ports/dv-processing/vcpkg.json
> +  "port-version": 2,
When we update port, we should remove the 'port version'

2022-07-28 07:47 UTC, jureviciusr commented on ports/dv-processing/portfile.cmake
> +        REF 96d082a862bb1e5bfdc79b39aa09e7a50c2dac49
The commit 9b1d8bb2e2223f76a4b1f12ae3998933947855b3 points to release version of 1.5.0, but a few days later additional hot-fix was introduced and the head commit is 96d082a862bb1e5bfdc79b39aa09e7a50c2dac49 now, you can see that here: https://gitlab.com/inivation/dv/dv-processing/-/commits/rel_1.5

2022-07-28 07:54 UTC, JonLiu1993 approved these changes

2022-08-01 06:56 UTC, JonLiu1993 approved these changes

2022-08-01 16:58 UTC, merged

2022-08-01 16:58 UTC, JavierMatosD commented
Thanks!