[libsndfile] Remove docs
microsoft/vcpkg pull request #26017
Opened 2022-07-27 21:17 UTC by Thomas1664

2022-07-28 06:13 UTC, JonLiu1993 submitted a review, later dismissed

2022-07-28 21:41 UTC, JavierMatosD requested changes

2022-07-28 21:41 UTC, JavierMatosD commented on ports/libsndfile/vcpkg.json
> +  "license": "LGPL-2.1-only",
```suggestion
  "license": "LGPL-2.1-or-later",
```

2022-07-29 02:38 UTC, JonLiu1993 approved these changes

2022-07-29 19:57 UTC, JavierMatosD approved these changes
Thanks!

2022-07-29 19:57 UTC, merged

2022-07-29 19:57 UTC, JavierMatosD commented
Thanks!