[sdl2-ttf,tgui,sfml] Update sdl2-ttf to 2.20.0, revise dependencies import and export
microsoft/vcpkg pull request #26026
Opened 2022-07-28 08:28 UTC by dg0yt

Reprise of  #25803 (@Thomas1664), #25713 (@FrankXie05). They made the major work.

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/25661.
  Modernizes `tgui`, and updates import and export of dependencies.
  Fixes and updates import and export of dependencies in port `sfml`, in particular OpenGL, needed for building `tgui[tool]:x64-linux`.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-07-29 07:45 UTC, dg0yt commented
- SFML is the default backend in TGUI. Using the SDL backend requires user to explicitly add 
   `#include <TGUI/Backends/SDL.hpp>`.
 - The TGUI pc file isn't installed for all platforms, the given lib name doesn't match the actual file name for most configurations, and dependencies are completely missing.

2022-08-02 07:01 UTC, FrankXie05 requested changes

2022-08-02 13:07 UTC, dg0yt commented on ports/tgui/portfile.cmake
> +if(NOT "sdl2" IN_LIST FEATURES AND NOT "sfml" IN_LIST FEATURES)
Define "necessary", from user POV.

2022-08-03 02:39 UTC, FrankXie05 requested changes

2022-08-03 02:39 UTC, FrankXie05 commented on ports/tgui/usage
> +    target_link_libraries(main PRIVATE tgui)
It's not available.
![image](https://user-images.githubusercontent.com/65999885/182511737-575c2bcb-7152-46cc-be6b-1a55f9a78589.png)
````
CMake Error at E:/feature-test/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
      Could not find a package configuration file provided by "TGUI" with any of
         the following names:    
            
           TGUIConfig.cmake
           tgui-config.cmake
````

2022-08-03 02:39 UTC, FrankXie05 commented on ports/sdl2-ttf/usage
> +    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:SDL2_ttf::SDL2_ttf>,SDL2_ttf::SDL2_ttf,SDL2_ttf::SDL2_ttf-static>)
````
 CMake Error at E:/feature-test/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
   Could not find a package configuration file provided by "SDL2_ttf" with any
   of the following names:
 
     SDL2_ttfConfig.cmake
     sdl2_ttf-config.cmake
 
   Add the installation prefix of "SDL2_ttf" to CMAKE_PREFIX_PATH or set
   "SDL2_ttf_DIR" to a directory containing one of the above files.  If
   "SDL2_ttf" provides a separate development package or SDK, be sure it has
   been installed.
````
![image](https://user-images.githubusercontent.com/65999885/182512092-a821c665-52d3-42d6-b6b4-05ea12d2557a.png)

2022-08-03 07:18 UTC, dg0yt commented
@FrankXie05 Then please run with `CMAKE_FIND_DEBUG_MODE` enabled. I assume it is available, but not accepted due to some missing dependency.

2022-08-04 02:40 UTC, FrankXie05 commented on ports/sdl2-ttf/usage
> +    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:SDL2_ttf::SDL2_ttf>,SDL2_ttf::SDL2_ttf,SDL2_ttf::SDL2_ttf-static>)
Sorry, I got the matching system architecture wrong.

2022-08-04 02:49 UTC, FrankXie05 approved these changes

2022-08-05 02:18 UTC, merged

2022-08-05 02:18 UTC, BillyONeal commented
Thanks for the updates! (And also @Thomas1664 and @FrankXie05 )