[gpgmm] Add gpgmm. Highly experimental.
microsoft/vcpkg pull request #26045
Opened 2022-07-29 04:19 UTC by bbernhar

Reverts https://github.com/microsoft/vcpkg/pull/25849

Just disables the backend causing the vulkan dependencies (will be fixed in next release).

2022-07-29 06:52 UTC, LilyWangLL requested changes

2022-07-29 06:52 UTC, LilyWangLL commented on ports/gpgmm/portfile.cmake
> +  -DGPGMM_ENABLE_VK=OFF
```suggestion
      -DGPGMM_STANDALONE=OFF
      -DGPGMM_ENABLE_TESTS=OFF
      -DGPGMM_ENABLE_VK=OFF

```

2022-07-29 06:52 UTC, LilyWangLL commented on ports/gpgmm/portfile.cmake
> +  SOURCE_PATH ${SOURCE_PATH}
```suggestion
  SOURCE_PATH "${SOURCE_PATH}"

```

2022-07-29 16:40 UTC, bbernhar commented on ports/gpgmm/portfile.cmake
> +  SOURCE_PATH ${SOURCE_PATH}
Done.

2022-07-29 16:40 UTC, bbernhar commented on ports/gpgmm/portfile.cmake
> +  -DGPGMM_ENABLE_VK=OFF
Done.

2022-08-01 05:56 UTC, LilyWangLL approved these changes

2022-08-01 16:10 UTC, bbernhar commented
@LilyWangLL Thank you. Please merge.

2022-08-03 06:01 UTC, ras0219-msft commented
Ok this looks good to me. Looking forward to a de-vendored vulkan backend in the future!

2022-08-03 06:01 UTC, merged