[tree-sitter] add new port
microsoft/vcpkg pull request #26058
Opened 2022-07-29 09:45 UTC by kylo252

**Describe the pull request**

add a new port for [tree-sitter](https://github.com/tree-sitter/tree-sitter)

>  Tree-sitter consists of two components: a C library (`libtree-sitter`), and
>  a command-line tool (the `tree-sitter` CLI). The library, `libtree-sitter`,
>  is used in combination with the parsers generated by the CLI, to produce
>  syntax trees from source code and keep the syntax trees up-to-date as the
>  source code changes. `libtree-sitter` is designed to be embedded in
>  applications. It is written in plain C. Its interface is specified in the
>  header file [`tree_sitter/api.h`](https://github.com/tree-sitter/tree-sitter/blob/master/lib/include/tree_sitter/api.h)

- #### What does your PR fix?
  NA

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all triplets are supported except `uwp`.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-08-01 06:29 UTC, JonLiu1993 requested changes

2022-08-01 08:54 UTC, kylo252 commented on ports/tree-sitter/vcpkg.json
> +  "version-semver": "0.26.0",
I'd say that's their general intention for publishing releases, see https://github.com/tree-sitter/tree-sitter/releases

2022-08-01 08:56 UTC, kylo252 commented on ports/tree-sitter/vcpkg.json
> +  "supports": "!uwp",
I haven't actually tried it, I just saw it always being excluded, so I  figured it has a special use-case 😄 

I'll add a test commit to see if it passes the CI.

2022-08-01 09:18 UTC, kylo252 commented on ports/tree-sitter/vcpkg.json
> +  "supports": "!uwp",
looks like it worked 🚀

2022-08-01 10:43 UTC, JonLiu1993 approved these changes, later dismissed

2022-08-02 01:24 UTC, JonLiu1993 commented
Tested usage successfully on my local machine

2022-08-02 14:21 UTC, Thomas1664 commented on ports/tree-sitter/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/tree-sitter.pc.in DESTINATION ${SOURCE_PATH}/lib)
```suggestion
file(COPY "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DESTINATION "${SOURCE_PATH}/lib")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/tree-sitter.pc.in" DESTINATION "${SOURCE_PATH}/lib")
```

Please add quotes.

2022-08-02 14:21 UTC, Thomas1664 commented on ports/tree-sitter/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
# Handle copyright
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

Quotes + Installing copyright should be done at the very end because it should only be installed after everything else succeeded.

2022-08-02 14:21 UTC, Thomas1664 commented on ports/tree-sitter/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
Why are there no headers although the port installs one?

2022-08-02 15:10 UTC, kylo252 commented on ports/tree-sitter/portfile.cmake
> +set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
fixed!

2022-08-02 23:44 UTC, ras0219-msft requested changes, later dismissed
Thanks for the PR!

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/vcpkg-cmake-wrapper.cmake
> +set(REQUIRES )
`vcpkg-cmake-wrapper` should not be required -- it exists to paper over some complex scenarios with CMake's built-in FindXYZ modules.

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/tree-sitter.pc.in
> +prefix=@CMAKE_INSTALL_PREFIX@
We should just use the .pc.in from the project[1] instead of providing our own.

[1]: https://github.com/tree-sitter/tree-sitter/blob/master/tree-sitter.pc.in

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/CMakeLists.txt
> +  HOMEPAGE_URL "https://tree-sitter.github.io")
```suggestion
project(tree-sitter C)
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
```suggestion
cmake_minimum_required(VERSION 3.20)
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/portfile.cmake
> +file(COPY "${CMAKE_CURRENT_LIST_DIR}/tree-sitter.pc.in" DESTINATION "${SOURCE_PATH}/lib")
```suggestion
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/CMakeLists.txt
> +configure_file("${CMAKE_CURRENT_SOURCE_DIR}/tree-sitter.pc.in"
```suggestion
set(LIBDIR "\${prefix}/lib")
set(INCLUDEDIR "\${prefix}/include")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/tree-sitter.pc.in"
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME "unofficial-${PORT}" CONFIG_PATH "share/unofficial-${PORT}")
```suggestion
vcpkg_cmake_config_fixup(PACKAGE_NAME "unofficial-tree-sitter")
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/portfile.cmake
> +  SOURCE_PATH "${SOURCE_PATH}/lib"
```suggestion
  SOURCE_PATH "${SOURCE_PATH}/lib"
  OPTIONS -DVERSION=${VERSION}
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/portfile.cmake
> +)
```suggestion
)
set(VERSION 0.26.0)
```

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/portfile.cmake
> +
```suggestion
```

Nothing should be being written to bin, so there's no need to delete the folder.

2022-08-02 23:44 UTC, ras0219-msft commented on ports/tree-sitter/portfile.cmake
> +file(INSTALL "${CURRENT_PORT_DIR}/vcpkg-cmake-wrapper.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion
```

2022-08-03 07:51 UTC, kylo252 commented on ports/tree-sitter/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
wouldn't the version requirement for this leak externally? I wanted to use an older cmake version to keep the port accessible for the public, since there's no point of a port that's only consumed by vcpkg's CI

2022-08-03 09:56 UTC, kylo252 commented on ports/tree-sitter/tree-sitter.pc.in
> +prefix=@CMAKE_INSTALL_PREFIX@
I did manage to get around this by patching the upstream `pkgconfig` template instead.

Some background: this `CMakeLists.txt` is for building the core library itself located in [`lib`](https://github.com/tree-sitter/tree-sitter/tree/master/lib). On the other hand, a project-level `CMakeLists.txt` should be able to interact with `cargo`, which is out-of-scope for this PR.

2022-08-04 05:53 UTC, JonLiu1993 commented
@kylo252, I noticed some of the reviews given by @ras0219-msft above and you marked it as resolved, but you don't seem to have modified the code. Can you reply to @ras0219-msft and give your reasons? thanks!

2022-08-04 07:29 UTC, kylo252 commented on ports/tree-sitter/portfile.cmake
> +  SOURCE_PATH "${SOURCE_PATH}/lib"
no longer needed after patching the `pkgconfig` template

2022-08-04 07:29 UTC, kylo252 commented on ports/tree-sitter/portfile.cmake
> +)
no longer needed after patching the `pkgconfig` template

2022-08-04 07:31 UTC, kylo252 commented
> @kylo252, I noticed some of the reviews given by @ras0219-msft above and you marked it as resolved, but you don't seem to have modified the code. Can you reply to @ras0219-msft and give your reasons? thanks!

handling `VERSION` externally is no longer needed after patching the `pkgconfig` template
https://github.com/microsoft/vcpkg/blob/912deeabf4e7652e6d2ae992a07c57d4bcf8f9fc/ports/tree-sitter/pkgconfig.patch#L19-L20

2022-08-06 06:29 UTC, BillyONeal approved these changes, later dismissed

2022-08-06 06:29 UTC, BillyONeal commented on ports/tree-sitter/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.10)
No: this CMakeLists.txt is only ever observed by vcpkg itself.

2022-08-06 06:45 UTC, BillyONeal commented
Thanks!

2022-08-06 06:46 UTC, merged

2022-08-06 10:06 UTC, heirecka commented
There's a typo in the version, there isn't 0.26.0 (yet), only 0.20.6

2023-11-19 11:41 UTC, keynmol commented on ports/tree-sitter/pkgconfig.patch
> ++libdir=${prefix}@/lib
Hello, is there a special meaning behind the trailing @ after prefix here?

It produces a folder name with @ in it: `arm64-osx/lib/pkgconfig/../..@/lib` and as such fails to link: 

```
ld: warning: search path '<snip>/arm64-osx/lib/pkgconfig/../..@/lib' not found
ld: library 'tree-sitter' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

2023-11-19 12:00 UTC, dg0yt commented on ports/tree-sitter/pkgconfig.patch
> ++libdir=${prefix}@/lib
There is no special meaning. Just remove it.
The `@` is probably left over from changing `@prefix@` to `${prefix}`.