[libmariadb] Fix features
microsoft/vcpkg pull request #26077
Opened 2022-07-31 09:00 UTC by Thomas1664

**Describe the pull request**

- #### What does your PR fix?
  Fixes #26059
  Feature `sschannel` doesn't work on mingw.
  Use `openssl` instead.

Note that this PR is not tested in CI because `libmariadb` conflicts with `libmysql`. I tested that the right features for the corrisponding platform are set locally.

2022-08-01 06:03 UTC, JackBoosY commented on ports/libmariadb/portfile.cmake
>  if("openssl" IN_LIST FEATURES AND "schannel" IN_LIST FEATURES)
Can you please also move this to `supports` field?

2022-08-01 07:11 UTC, Thomas1664 commented on ports/libmariadb/portfile.cmake
>  if("openssl" IN_LIST FEATURES AND "schannel" IN_LIST FEATURES)
I think this isn't possible: This check is to ensure that openssl and schannel aren't used at the same time.

2022-08-01 09:02 UTC, JackBoosY approved these changes, later dismissed

2022-08-02 23:51 UTC, ras0219-msft requested changes, later dismissed
I also want to give @dg0yt a chance to comment on this -- my understanding is that mingw intends for all Win32 APIs (including SChannel) to work.

2022-08-02 23:51 UTC, ras0219-msft commented on ports/libmariadb/vcpkg.json
> +  "license": "LGPL-2.1-only",
```suggestion
  "license": "LGPL-2.1-or-later",
```

2022-08-03 07:45 UTC, dg0yt commented
> * Feature `schannel` doesn't work on mingw.

`libmariadb[core,schannel]` builds SCHANNEL support without problems in MSYS2 with a recent mingw-w64. 
https://github.com/microsoft/vcpkg/issues/26059 refers to a Linux host. It may have an older version of mingw-w64. (e.g. Ubuntu 18.04 is too old.)
So the change to `supports` is wrong, and IMO even the default shouldn't be changed for mingw.

2022-08-03 08:36 UTC, dg0yt approved these changes
:+1:

2022-08-03 18:58 UTC, merged

2022-08-03 18:58 UTC, JavierMatosD commented
Thanks!