libusb: Fix compilation on MinGW
microsoft/vcpkg pull request #26152
Opened 2022-08-03 17:37 UTC by GPUCode

**Describe the pull request**

- #### What does your PR fix?
  Fixes the libusb package when building with the MinGW environment

2022-08-04 02:41 UTC, JackBoosY requested changes
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

2022-08-04 08:15 UTC, GPUCode commented
> Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports). Also please run command `vcpkg x-add-version --all` then commit the changes.

Thanks for linking the documentation, I couldn't initially find how to properly do this. I think it's correct now

2022-08-08 09:23 UTC, JackBoosY approved these changes

2022-08-08 19:14 UTC, merged

2022-08-08 19:14 UTC, BillyONeal commented
Thanks!