[bshoshany-thread-pool] Updated to v3.3.0
microsoft/vcpkg pull request #26154
Opened 2022-08-03 19:47 UTC by bshoshany

- #### What does your PR fix?
Updated [bshoshany-thread-pool] to v3.3.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
all, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-08-03 20:10 UTC, bshoshany commented
Question: Starting from v3.3.0, the package now has two (stand-alone) header files, `BS_thread_pool.hpp` and `BS_thread_pool_light.hpp`. However, when I tried the port with `*.hpp` in line 9, it generated some errors and didn't install anything. I didn't write the initial port, so I'm not sure how this is supposed to work; how to install both header files?

2022-08-04 08:14 UTC, LilyWangLL requested changes

2022-08-04 08:14 UTC, LilyWangLL commented on ports/bshoshany-thread-pool/portfile.cmake
>  file(INSTALL "${HEADER_FILES}" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
```suggestion
file(INSTALL ${HEADER_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/include")
```

2022-08-04 08:14 UTC, LilyWangLL commented on ports/bshoshany-thread-pool/portfile.cmake
> +file(GLOB HEADER_FILES LIST_DIRECTORIES false "${SOURCE_PATH}/BS_thread_pool.hpp")
```suggestion
file(GLOB HEADER_FILES LIST_DIRECTORIES false "${SOURCE_PATH}/*.hpp")
```

2022-08-04 08:15 UTC, LilyWangLL commented on ports/bshoshany-thread-pool/portfile.cmake
>  file(INSTALL "${HEADER_FILES}" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
You can try this.

2022-08-04 15:39 UTC, bshoshany commented
Thanks @LilyWangLL! :)

2022-08-05 02:23 UTC, LilyWangLL approved these changes

2022-08-05 02:29 UTC, merged

2022-08-05 02:29 UTC, BillyONeal commented
Thanks!