[tracy] update to 0.8.2
microsoft/vcpkg pull request #26200
Opened 2022-08-05 21:15 UTC by alex-tdrn

**Describe the pull request**

- #### What does your PR fix?
  Updates `tracy` to version 0.8.2. The vcxproj patch has been removed, since [it was merged upstream](https://github.com/wolfpld/tracy/pull/412/files#diff-a77fdc8f9d16eb55e3d0f19c1738839914856387facbeba1fc93bc81cf40f2a0)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-08-08 02:25 UTC, FrankXie05 requested changes

2022-08-08 02:25 UTC, FrankXie05 commented on ports/tracy/portfile.cmake
> +        001-fix-capstone-5.patch
Note: This patch contains nothing.

2022-08-10 13:22 UTC, Thomas1664 commented on versions/baseline.json
> +}
Please keep the final newline here...

2022-08-10 13:22 UTC, Thomas1664 commented on versions/t-/tracy.json
> +}
... and here as well.

2022-08-12 02:41 UTC, FrankXie05 requested changes

2022-08-12 02:41 UTC, FrankXie05 commented on ports/tracy/portfile.cmake
> -        001-fix-vcxproj-vcpkg.patch
Why remove this patch? Upstream did not make changes: 
https://github.com/wolfpld/tracy/blob/a8511d357650282c6915f7aa9775e9c4945e42b5/profiler/build/win32/Tracy.vcxproj#L100

2022-08-12 06:36 UTC, alex-tdrn commented on ports/tracy/portfile.cmake
> -        001-fix-vcxproj-vcpkg.patch
Ah I'm very sorry, I messed up here. The vcxproj patch did not apply cleanly on 0.8.2, so I looked for changes upstream, saw that there was _some_ patch merged on that file related to vcpkg, so I assumed it was doing the same thing, but I see now that it doesn't, I should have been more careful. I'll update our patch when I have access to a windows machine to test things out with visual studio

2022-08-12 14:59 UTC, alex-tdrn commented on ports/tracy/portfile.cmake
> -        001-fix-vcxproj-vcpkg.patch
Alrighty, I've updated the patch, and tested the port with `.\vcpkg.exe install tracy[gui-tools]:x64-windows`
The resulting Tracy.exe starts and seems to work fine 👍 
Sidenote: looking at diffs of patches hurt my brain 🤮

2022-08-18 02:03 UTC, FrankXie05 approved these changes

2022-08-18 17:44 UTC, JavierMatosD commented
Thanks!

2022-08-18 17:44 UTC, merged