Update TBB to 2021.5
microsoft/vcpkg pull request #26284
Opened 2022-08-11 03:25 UTC by BillyONeal

Merges / combines the following:

* https://github.com/microsoft/vcpkg/pull/26106
* https://github.com/microsoft/vcpkg/pull/23058
* https://github.com/microsoft/vcpkg/pull/19909

Credit to @ras0219 / @ras0219-msft , @vladimir-aubrecht , and @mathisloge for the initial work.

2022-08-11 07:24 UTC, LilyWangLL requested changes

2022-08-11 07:24 UTC, LilyWangLL commented on ports/tbb/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/TBB)
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/TBB")
```

2022-08-11 07:24 UTC, LilyWangLL commented on ports/tbb/vcpkg.json
> +  "version": "2021.5",
```suggestion
  "version": "2021.5.0",
```

2022-08-11 07:24 UTC, LilyWangLL commented
Thanks for your update, please consider adding a "license" field to the following files:
```
ports/pagmo2/vcpkg.json
ports/tbb/vcpkg.json
```

2022-08-13 08:05 UTC, Osyotr commented on scripts/ci.baseline.txt
> +# openvdb\openvdb\libopenvdb.lib : fatal error LNK1248: image size (109A36020) exceeds maximum allowable size (FFFFFFFF)
This failure may be due to usage of /Z7

2022-08-17 23:03 UTC, BillyONeal commented
pagmo license written as OR despite two license files in upstream based on:

https://github.com/esa/pagmo2/blob/19d774fbb6128124305225803f8c1ad9e2f95c8c/src/bfe.cpp#L5-L27

2022-08-18 02:57 UTC, LilyWangLL commented on ports/gazebo/portfile.cmake
> +        "-DPKG_CONFIG_EXECUTABLE=${CURRENT_HOST_INSTALLED_DIR}/tools/pkgconf/pkgconf${VCPKG_HOST_EXECUTABLE_SUFFIX}"
Why are double quotes added here? Do other options need double quotes too?

2022-08-18 02:59 UTC, LilyWangLL commented on ports/tbb/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/TBB)
Ping...

2022-08-18 02:59 UTC, LilyWangLL commented on ports/tbb/vcpkg.json
> +  "version": "2021.5",
Ping...

2022-08-18 18:59 UTC, BillyONeal commented
* Add usd explainer patch
* Remove embree2 completely

2022-08-19 00:28 UTC, BillyONeal commented on ports/gazebo/portfile.cmake
> +        "-DPKG_CONFIG_EXECUTABLE=${CURRENT_HOST_INSTALLED_DIR}/tools/pkgconf/pkgconf${VCPKG_HOST_EXECUTABLE_SUFFIX}"
CURRENT_HOST_INSTALLED_DIR could have spaces.

2022-08-19 02:33 UTC, LilyWangLL commented
@BillyONeal You need run the following command to fix pipeline error.
```
    vcpkg x-add-version usd
```

2022-08-22 07:31 UTC, dg0yt commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
No need to change the case of the `tbb` directory. CMake finds the directory case-insensitively.

2022-08-22 07:33 UTC, dg0yt commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
BTW this can be handled by `vcpkg_replace_string`.

2022-08-22 07:45 UTC, BillyONeal commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
I'm not sure I understand, this isn't changing the case? (Or rather, if there is a case change, it was done by TBB itself.

2022-08-22 08:06 UTC, dg0yt commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
You mean upstream changed the installation directory? Even if this is the case, do we want to continue keeping the files together in `share/${PORT}`? If yes, ...

2022-08-22 08:06 UTC, dg0yt commented on ports/tbb/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME TBB CONFIG_PATH "lib/cmake/TBB")
... then we should simply remove `PACKAGE_NAME TBB` here (restoring `${PORT}` as the directory name; `PACKAGE_NAME` is sort-of a misnomer).

2022-08-22 08:18 UTC, BillyONeal commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
I mean, I don't see anywhere where vcpkg asked for TBB in all caps.

2022-08-22 09:03 UTC, dg0yt commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
Definitely in `vcpkg_cmake_config_fixup(PACKAGE_NAME TBB` <-----

2022-08-22 19:50 UTC, BillyONeal commented on ports/tbb/portfile.cmake
> +file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
> Definitely in `vcpkg_cmake_config_fixup(PACKAGE_NAME TBB`

That's an input though, not an output. Example:

```
bion@BION-TR:~/vcpkg$ git diff
diff --git a/ports/tbb/portfile.cmake b/ports/tbb/portfile.cmake
index 6bfa28251..4ab2243b8 100644
--- a/ports/tbb/portfile.cmake
+++ b/ports/tbb/portfile.cmake
@@ -16,7 +16,6 @@ vcpkg_cmake_configure(
 )

 vcpkg_cmake_install()
-vcpkg_cmake_config_fixup(PACKAGE_NAME TBB CONFIG_PATH "lib/cmake/TBB")
 vcpkg_fixup_pkgconfig()
 vcpkg_copy_pdbs()

@@ -29,10 +28,4 @@ file(REMOVE_RECURSE
     "${CURRENT_PACKAGES_DIR}/debug/lib/tbb_debug.lib"
 )

-file(READ "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" _contents)
-file(WRITE "${CURRENT_PACKAGES_DIR}/share/TBB/TBBConfig.cmake" "
-include(CMakeFindDependencyMacro)
-find_dependency(Threads)
-${_contents}")
-
 file(INSTALL "${SOURCE_PATH}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)bion@BION-TR:~/vcpkg$ ./vcpkg install tbb
Computing installation plan...
The following packages will be built and installed:
    tbb[core]:x64-linux -> 2021.5.0
  * vcpkg-cmake[core]:x64-linux -> 2022-07-18
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 2 package(s) from /home/bion/.cache/vcpkg/archives in 37.87 ms. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-linux...
Elapsed time to handle vcpkg-cmake:x64-linux: 499.3 us
Installing 2/3 vcpkg-cmake-config:x64-linux...
Elapsed time to handle vcpkg-cmake-config:x64-linux: 296.4 us
Installing 3/3 tbb:x64-linux...
Building tbb[core]:x64-linux...
-- Using cached oneapi-src-oneTBB-v2021.5.0.tar.gz.
-- Extracting source /mnt/c/Dev/vcpkg-downloads/oneapi-src-oneTBB-v2021.5.0.tar.gz
-- Using source at /home/bion/vcpkg/buildtrees/tbb/src/v2021.5.0-808f1ff7af.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/bion/vcpkg/packages/tbb_x64-linux/lib/pkgconfig/tbb.pc
-- Fixing pkgconfig file: /home/bion/vcpkg/packages/tbb_x64-linux/debug/lib/pkgconfig/tbb.pc
-- Installing: /home/bion/vcpkg/packages/tbb_x64-linux/share/tbb/copyright
-- Performing post-build validation
The /lib/cmake folder should be merged with /debug/lib/cmake and moved to /share/tbb/cmake.
Please use the helper function `vcpkg_cmake_config_fixup()` from the port vcpkg-cmake-config.`
The following cmake files were found outside /share/tbb. Please place cmake files in /share/tbb.

    /home/bion/vcpkg/packages/tbb_x64-linux/lib/cmake/TBB/TBBTargets-release.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/lib/cmake/TBB/TBBConfig.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/lib/cmake/TBB/TBBTargets.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/lib/cmake/TBB/TBBConfigVersion.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/debug/lib/cmake/TBB/TBBConfig.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/debug/lib/cmake/TBB/TBBTargets.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/debug/lib/cmake/TBB/TBBTargets-debug.cmake
    /home/bion/vcpkg/packages/tbb_x64-linux/debug/lib/cmake/TBB/TBBConfigVersion.cmake

The /debug/lib/cmake folder should be merged with /lib/cmake into /share/tbb
Found 3 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    /home/bion/vcpkg/ports/tbb/portfile.cmake
-- Performing post-build validation done
Stored binary cache: "/home/bion/.cache/vcpkg/archives/ac/ac8bd29b609bbc52f74540ceef7da7a4634d8ebfd518a4ead473a6eb8c39261c.zip"
Elapsed time to handle tbb:x64-linux: 6.446 s

Total elapsed time: 12.73 s

bion@BION-TR:~/vcpkg$
```

2022-08-22 20:21 UTC, BillyONeal commented on ports/tbb/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME TBB CONFIG_PATH "lib/cmake/TBB")
If you remove `PACKAGE_NAME TBB` then it fails because it doesn't find `TBBConfig.cmake` created by upstream.

2022-08-22 20:28 UTC, BillyONeal commented on ports/tbb/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME TBB CONFIG_PATH "lib/cmake/TBB")
... Hmmmm or so I thought?

2022-09-05 09:50 UTC, LilyWangLL approved these changes, later dismissed

2022-09-09 20:13 UTC, ras0219-msft approved these changes, later dismissed

2022-09-09 20:13 UTC, ras0219-msft commented on ports/tbb/vcpkg.json
> +  "supports": "!(windows & uwp) | linux | osx",
```suggestion
  "supports": "(windows & !uwp) | linux | osx",
```
`emscripten` passes `!(windows & uwp)`, but this is clearly an allow list that intends to exclude it.

2022-09-09 20:13 UTC, ras0219-msft commented on ports/usd/portfile.cmake
> +and does not expect to be updated to work with current versions soon.
I think we should point users towards the upstream issue: https://github.com/PixarAnimationStudios/USD/issues/1600

2022-09-09 20:15 UTC, ras0219-msft commented
Additionally, the `pagmo2` port patches can be reduced by deleting the lines and not re-adding them as comments:
```diff
diff --git a/ports/pagmo2/disable-werror.patch b/ports/pagmo2/disable-werror.patch
index 92d930a04..fbbad4785 100644
--- a/ports/pagmo2/disable-werror.patch
+++ b/ports/pagmo2/disable-werror.patch
@@ -2,21 +2,19 @@ diff --git a/cmake_modules/yacma/YACMACompilerLinkerSettings.cmake b/cmake_modul
 index 7d7aa1b..21613a2 100644
 --- a/cmake_modules/yacma/YACMACompilerLinkerSettings.cmake
 +++ b/cmake_modules/yacma/YACMACompilerLinkerSettings.cmake
-@@ -95,7 +95,7 @@ if(NOT _YACMACompilerLinkerSettingsRun)
+@@ -95,7 +95,6 @@ if(NOT _YACMACompilerLinkerSettingsRun)
          # NOTE: enable unconditionally, as it seems like the CMake
          # machinery for detecting this fails. Perhaps the source code
          # used for checking the flag emits warnings?
 -        list(APPEND _YACMA_CXX_FLAGS_DEBUG "-Werror")
-+        #list(APPEND _YACMA_CXX_FLAGS_DEBUG "-Werror")
          # New warnings in clang 8.
          # NOTE: a few issues with macros here, let's disable for now.
          # _YACMA_CHECK_ENABLE_DEBUG_CXX_FLAG(-Wextra-semi-stmt)
-@@ -180,7 +180,7 @@ if(NOT _YACMACompilerLinkerSettingsRun)
+@@ -180,7 +179,6 @@ if(NOT _YACMACompilerLinkerSettingsRun)
          # Enable higher warning level than usual.
          _YACMA_CHECK_ENABLE_DEBUG_CXX_FLAG(/W4)
          # Treat warnings as errors.
 -        _YACMA_CHECK_ENABLE_DEBUG_CXX_FLAG(/WX)
-+        #_YACMA_CHECK_ENABLE_DEBUG_CXX_FLAG(/WX)
      endif()

      # Set the cache variables.
diff --git a/ports/pagmo2/doxygen.patch b/ports/pagmo2/doxygen.patch
index 1a59a9110..a95cc47b3 100644
--- a/ports/pagmo2/doxygen.patch
+++ b/ports/pagmo2/doxygen.patch
@@ -2,14 +2,12 @@ diff --git a/CMakeLists.txt b/CMakeLists.txt
 index 34bad69..dfb942d 100644
 --- a/CMakeLists.txt
 +++ b/CMakeLists.txt
-@@ -398,8 +398,8 @@ endif()
+@@ -398,8 +398,6 @@ endif()
  configure_file("${CMAKE_CURRENT_SOURCE_DIR}/config.hpp.in" "${CMAKE_CURRENT_BINARY_DIR}/include/pagmo/config.hpp" @ONLY)

  # Configure the doc files.
 -configure_file("${CMAKE_CURRENT_SOURCE_DIR}/doc/doxygen/Doxyfile.in" "${CMAKE_CURRENT_SOURCE_DIR}/doc/doxygen/Doxyfile" @ONLY)
 -configure_file("${CMAKE_CURRENT_SOURCE_DIR}/doc/sphinx/conf.py.in" "${CMAKE_CURRENT_SOURCE_DIR}/doc/sphinx/conf.py" @ONLY)
-+# configure_file("${CMAKE_CURRENT_SOURCE_DIR}/doc/doxygen/Doxyfile.in" "${CMAKE_CURRENT_SOURCE_DIR}/doc/doxygen/Doxyfile" @ONLY)
-+# configure_file("${CMAKE_CURRENT_SOURCE_DIR}/doc/sphinx/conf.py.in" "${CMAKE_CURRENT_SOURCE_DIR}/doc/sphinx/conf.py" @ONLY)

  # This is just a simple counter variable, internal use only.
  set(_PAGMO_TEST_NUM "0")
```

2022-09-19 21:58 UTC, BillyONeal commented on ports/cctag/0002-find-tbb.patch
> ++find_dependency(TBB)
We were already deleting `FindTBB.cmake` so I just removed this part of the patch.

2022-09-19 22:02 UTC, BillyONeal commented on ports/cctag/0002-find-tbb.patch
> ++#include <mutex>
1. I don't think the change is big enough to trigger licensing concerns, and
2. fetching additional content like that is worse UX, and
3. this change isn't exactly that because that was made against a different branch

I think we should be doing things like that only when the patch wouldn't be de-minimis.

2022-09-23 19:00 UTC, ras0219-msft approved these changes

2022-09-23 19:03 UTC, merged