[azure-iot-sdk-c] LTS Release 07-2022
microsoft/vcpkg pull request #26361
Opened 2022-08-15 21:27 UTC by vaavva

**Describe the pull request**

- #### What does your PR fix?
  LTS release for 2022-07-18

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-08-16 02:28 UTC, LilyWangLL commented
Please update the port's version fields and then run:

```
    vcpkg x-add-version azure-c-shared-utility
    git add versions
    git commit -m "Update version database"
```

to add a new version.

2022-08-16 02:30 UTC, LilyWangLL commented
> _This is a new experimental fast check for PR issues. Please let us know if this bot is helpful!_
> 
> All manifest files must be formatted
> PRs must add only one version and must not modify any published versions
> You have modified or added at least one portfile where deprecated functions are used.
> 
> If you feel able to do so, please consider migrating them to the new functions: `vcpkg_install_cmake` -> `vcpkg_cmake_install` (from port `vcpkg-cmake`) `vcpkg_build_cmake` -> `vcpkg_cmake_build` (from port `vcpkg-cmake`) `vcpkg_configure_cmake` -> `vcpkg_cmake_configure` (Please remove the option `PREFER_NINJA`) (from port `vcpkg-cmake`) `vcpkg_fixup_cmake_targets` -> `vcpkg_cmake_config_fixup` (from port `vcpkg-cmake-config`)
> 
> In the ports that use the new function, you have to add the corresponding dependencies:
> 
> ```json
> {
>   "name": "vcpkg-cmake",
>   "host": true
> },
> {
>   "name": "vcpkg-cmake-config",
>   "host": true
> }
> ```
> 
> The following files are affected:
> 
> * `ports/azure-uamqp-c/portfile.cmake`
> 
Could you apply these suggestions in `ports/azure-uamqp-c/portfile.cmake`?

2022-08-17 02:36 UTC, LilyWangLL commented
Now `azure-c-shared-utility:x64-linux` build failed on CI pipeline, you can download the error log from: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/76628/artifacts?artifactName=file%20lists%20for%20x64-linux&api-version=7.0&%24format=zip

2022-09-05 09:48 UTC, LilyWangLL commented
Ping @vaavva for response. Is work still being done for this PR?

2022-09-08 21:38 UTC, vaavva commented
@LilyWangLL yes, I'm working on fixing the Linux failure!

2022-09-14 10:07 UTC, PhoebeHui commented
@vaavva, please ping us if the PR is ready for review, thanks!

2022-09-20 18:11 UTC, vaavva commented
@PhoebeHui @LilyWangLL This is now ready for review, thanks!

2022-09-20 18:14 UTC, vaavva commented on versions/a-/azure-c-shared-utility.json
> +      "git-tree": "e1e2f89fdb6cd296d8c401eb248956ff86686c80",
@LilyWangLL Should I take out the 2022-07-18 entries on the version files since they were never published with vcpkg?

2022-09-21 01:56 UTC, LilyWangLL commented on versions/a-/azure-c-shared-utility.json
> +      "git-tree": "e1e2f89fdb6cd296d8c401eb248956ff86686c80",
Yes, this should be removed.

2022-09-21 02:01 UTC, vaavva commented on versions/a-/azure-c-shared-utility.json
> +      "git-tree": "e1e2f89fdb6cd296d8c401eb248956ff86686c80",
Done!

2022-09-21 02:12 UTC, LilyWangLL requested changes

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-c-shared-utility/vcpkg.json
>    "port-version": 3,
```suggestion
```
When the version of the underlying library is upgraded, this field should be removed.

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-uamqp-c/portfile.cmake
>      SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-uamqp-c/portfile.cmake
>  file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include ${CURRENT_PACKAGES_DIR}/debug/share)
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include" "${CURRENT_PACKAGES_DIR}/debug/share")
```
The following codes `configure_file("${SOURCE_PATH}/LICENSE" "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" COPYONLY)` should also modified.

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-uamqp-c/vcpkg.json
>    "port-version": 1,
```suggestion
```

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-uhttp-c/vcpkg.json
>    "port-version": 1,
```suggestion
```

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-umqtt-c/vcpkg.json
>    "port-version": 1,
```suggestion
```

2022-09-21 02:12 UTC, LilyWangLL commented on ports/azure-umqtt-c/portfile.cmake
>  endif()
Could you please add "" for the absolute path in this file?

2022-09-21 02:45 UTC, LilyWangLL approved these changes

2022-09-21 06:06 UTC, LilyWangLL commented
@vaavva You could run `./vcpkg x-add-version PORT_NAME --overwrite-version` after change files of on port, this command will update **PORT_NAME.json** correctly. 
And I noticed port `umock-c` and `azure-macro-utils-c` just update the `version-date` in `vcpkg.json`, why not change the commit in `portfile.cmake`? I saw the upstream has new commit.

2022-09-21 06:06 UTC, LilyWangLL requested changes

2022-09-21 06:06 UTC, LilyWangLL commented on versions/a-/azure-c-shared-utility.json
> +      "git-tree": "9ebf38da3870cf1d514ae8cde6b1f1fad69e8770",
`./vcpkg x-add-version PORT_NAME --overwrite-version`

2022-09-21 06:06 UTC, LilyWangLL commented on versions/a-/azure-uamqp-c.json
> +      "git-tree": "42efba430e30e78eaf72b03c94f8c4afe07bcfda",
`./vcpkg x-add-version PORT_NAME --overwrite-version`

2022-09-21 06:06 UTC, LilyWangLL commented on versions/a-/azure-uhttp-c.json
> +      "git-tree": "5c83542c6dc2b853932ac25c4d8314a5556aab40",
`./vcpkg x-add-version PORT_NAME --overwrite-version`

2022-09-21 06:06 UTC, LilyWangLL commented on versions/a-/azure-umqtt-c.json
> +      "git-tree": "28ef0c8d4778d3fd30120290bcb4a121a2efc14f",
`./vcpkg x-add-version PORT_NAME --overwrite-version`

2022-09-22 02:12 UTC, LilyWangLL commented
> For `umock-c` and `azure-macro-utils-c`, we're still pointing to the same commit as before in our repos.

If this, I think we don't need update the `version-date` in `vcpkg.json`, because these two ports have no new change.

2022-09-22 06:26 UTC, Cheney-W approved these changes

2022-09-22 06:28 UTC, LilyWangLL approved these changes

2022-09-22 16:09 UTC, vaavva commented
@LilyWangLL Anything else I need to do for this to be merged?

2022-09-22 21:32 UTC, merged