[luv] add new port
microsoft/vcpkg pull request #26438
Opened 2022-08-20 12:28 UTC by kylo252

**Describe the pull request**

add https://github.com/luvit/luv: libuv bindings for lua

- #### What does your PR fix?
  NA

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All except `uwp`, as it's not supported by `luajit`.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-08-24 08:46 UTC, FrankXie05 requested changes

2022-08-24 08:46 UTC, FrankXie05 commented on ports/luv/portfile.cmake
> +)
```suggestion
```
It should be added as another new port.

2022-09-07 02:34 UTC, FrankXie05 commented
/azp run

2022-09-07 02:38 UTC, FrankXie05 requested changes

2022-09-07 02:38 UTC, FrankXie05 commented on ports/lua-compat53/portfile.cmake
> +vcpkg_from_github(
```suggestion
#header-only library
vcpkg_from_github(
```

2022-09-07 02:38 UTC, FrankXie05 requested changes

2022-09-07 02:38 UTC, FrankXie05 commented on ports/lua-compat53/portfile.cmake
> +vcpkg_from_github(
```suggestion
#header-only library
vcpkg_from_github(
```

2022-09-07 02:39 UTC, FrankXie05 approved these changes

2022-09-07 02:48 UTC, FrankXie05 requested changes

2022-09-07 02:48 UTC, FrankXie05 commented on ports/luv/fix-msvc-build.patch
> +-endif ()
Can I ask why these flags were deleted? 🤔

2022-09-07 06:13 UTC, FrankXie05 commented
All features of the ports `lua-compat53`  are tested successfully in the following triplet:

- x86-windows
- x64-windows
- x64-windows-stataic

2022-09-15 10:05 UTC, kylo252 commented on ports/luv/fix-msvc-build.patch
> +-endif ()
They were causing problems with linking to `MSVCRT`, those flags should be controlled by vcpkg instead, the alternative would've adding [linkage restrictions](https://github.com/microsoft/vcpkg/blob/d9553663ca0c1586043695d92e4d93bdb7440c8b/ports/apsi/portfile.cmake#L1) (as I understand it at least)

2022-09-16 02:38 UTC, FrankXie05 approved these changes

2022-09-16 06:17 UTC, FrankXie05 requested changes

2022-09-16 06:17 UTC, FrankXie05 commented on ports/lua-compat53/portfile.cmake
> +    REPO lunarmodules/lua-compat-5.3
```suggestion
    OUT_SOURCE_PATH SOURCE_PATH
    REPO lunarmodules/lua-compat-5.3
```

2022-09-20 06:23 UTC, FrankXie05 submitted a review, later dismissed

2022-09-21 20:31 UTC, dan-shaw commented on ports/lua-compat53/vcpkg.json
> +    "c-api": {
Do we need this feature? It does not seem this feature is used in `portfile.cmake`.

2022-09-27 11:21 UTC, kylo252 commented on ports/lua-compat53/vcpkg.json
> +    "c-api": {
@dan-shaw, sorry for the late reply, the idea is that I'm only providing the C API part of https://github.com/lunarmodules/lua-compat-5.3

> It includes:
> 
> - For writing Lua: The Lua module compat53, which can be require'd from Lua scripts and run in Lua 5.1, 5.2, and 5.3, including a backport of the utf8 module, the 5.3 table module, and the string packing functions straight from the Lua 5.3 sources.
> - For writing C: A C header and file which can be linked to your Lua module written in C, providing some functions from the C API of Lua 5.3 that do not exist in Lua 5.2 or 5.1, making it easier to write C code that compiles with all three versions of liblua.

my thinking is basically:
1. make it clear that this is only providing the C API
2. make it easy to add lua-modules export part

2022-10-14 23:01 UTC, merged