[libxdamage,libxext,libxfixes] add ports
microsoft/vcpkg pull request #26486
Opened 2022-08-23 18:20 UTC by Neumann-A

2022-08-24 09:08 UTC, JonLiu1993 requested changes

2022-08-24 09:08 UTC, JonLiu1993 commented on ports/libxdamage/vcpkg.json
> +  "license": null,
@Neumann-A, Thanks for your pr, I investigated, shouldn't the license here be MIT? https://gitlab.freedesktop.org/xorg/lib/libxdamage/-/blob/master/COPYING

2022-08-24 09:08 UTC, JonLiu1993 commented on ports/libxext/vcpkg.json
> +  "license": null,
I investigated here the license should also be MIT 
https://gitlab.freedesktop.org/xorg/lib/libxext/-/blob/master/COPYING

2022-08-24 09:12 UTC, Neumann-A commented on ports/libxdamage/vcpkg.json
> +  "license": null,
> This project is licensed under the Other. [Learn more](http://choosealicense.com/licenses/other/)

2022-08-24 09:12 UTC, Neumann-A commented on ports/libxext/vcpkg.json
> +  "license": null,
> This project is licensed under the Other. [Learn more](http://choosealicense.com/licenses/other/)

2022-08-24 09:17 UTC, JonLiu1993 approved these changes

2022-08-24 10:14 UTC, JackBoosY approved these changes

2022-08-26 20:08 UTC, JavierMatosD commented
Thank you!

2022-08-26 20:08 UTC, merged