Avoid conflicts between openexr and imath
microsoft/vcpkg pull request #26513
Opened 2022-08-25 09:08 UTC by fabiencastan

**Describe the pull request**

Imath is included in openexr and the install of imath or openexr will overide the other one.
So, currently the system is broken and we cannot install both openexr and alembic, as it will end up in 2 differents versions mixed up.

- #### What does your PR fix?
Use openexr which contains the latest version of imath.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
Does not change anything.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Not yet, I would like to get feedback.

2022-08-25 10:05 UTC, dg0yt commented
I think this PR is invalid. (The problem is valid, but the solution will be different.)

> Use openexr which contains the latest version of imath.

Actually port `imath` is the latest version.  Port `openexr` in vcpkg is an older version, which includes an older version of imath.

You can install both ports at the same time, but you can't use them at the same time.
For this reason, you currently cannot install `openimageio[opencolorio]` with the latest versions of these ports, because `opencolorio` was updated to use the new `imath` while `openimageio` still uses the outdated `openexr`.
However, in manifest mode, you could request an old, compatible version of `opencolorio`.
There is a version check added as a patch to `openimageio`:
https://github.com/microsoft/vcpkg/blob/55112eb54a1c4cfaec5dd2592a39cea72f78ed56/ports/openimageio/imath-version-guard.patch#L9-L13

The ultimate solution is to update `openexr` to version 3. There have been two attempts already, but they are somewhat stuck due to depending ports not being ready for the update. And vcpgk makes it hard to have an `openexr3` (or `openexr2`) in addition to `openexr`. But you know that, as you commented on these PRs.

2022-09-13 16:11 UTC, xchen31u commented
Hi, please accelerate this if possible; is breaking OpenColorIO

2022-09-19 06:19 UTC, LilyWangLL requested changes

2022-09-19 06:19 UTC, LilyWangLL commented on ports/imath/portfile.cmake
> -file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
Please don't just remove this port, add `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` here, and add `openexr` to `imath`'s dependency in **vcpkg.json**.
You can refer the change of PR #26655.

2022-09-19 06:22 UTC, LilyWangLL commented
> I think this PR is invalid. (The problem is valid, but the solution will be different.)
> 
> > Use openexr which contains the latest version of imath.
> 
> Actually port `imath` is the latest version. Port `openexr` in vcpkg is an older version, which includes an older version of imath.
> 
> You can install both ports at the same time, but you can't use them at the same time. For this reason, you currently cannot install `openimageio[opencolorio]` with the latest versions of these ports, because `opencolorio` was updated to use the new `imath` while `openimageio` still uses the outdated `openexr`. However, in manifest mode, you could request an old, compatible version of `opencolorio`. There is a version check added as a patch to `openimageio`:
> 
> https://github.com/microsoft/vcpkg/blob/55112eb54a1c4cfaec5dd2592a39cea72f78ed56/ports/openimageio/imath-version-guard.patch#L9-L13
> 
> The ultimate solution is to update `openexr` to version 3. There have been two attempts already, but they are somewhat stuck due to depending ports not being ready for the update. And vcpgk makes it hard to have an `openexr3` (or `openexr2`) in addition to `openexr`. But you know that, as you commented on these PRs.

Ping @fabiencastan for response.

2022-09-19 06:51 UTC, dg0yt commented on ports/imath/portfile.cmake
> -file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
This part is invalid anyways. Imath is separate from openexr 3.
This whole PR is obsolete with #26862.

2022-10-08 08:59 UTC, LilyWangLL commented
Ping @fabiencastan for response. Is work still being done for this PR?

2022-10-08 09:26 UTC, dg0yt commented
> Ping @fabiencastan for response. Is work still being done for this PR?

I hope not. Cf. https://github.com/microsoft/vcpkg/pull/26513#discussion_r973912958.

2022-10-08 19:19 UTC, closed without merging

2022-10-08 19:21 UTC, fabiencastan commented
No, everything is working fine with the great work to move to openexr-3!