[scripts] fixes for armv7l host builds
microsoft/vcpkg pull request #26510
Opened 2022-08-25 06:19 UTC by vserdyuk

Fixes some problems when using vcpkg on host armv7l/aarch64. It allows to build qtdeclarative shared libraries on the target machine (unfortunately, cross-compiling Qt on x86_x64 host for armv7l target does not work for me, but that's another issue).

- #### What does your PR fix?
  Fixes #25277

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  I guess yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  n/a

2022-08-25 07:06 UTC, Osyotr commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +            EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE HOST_ARCH)
HOST_ARCH is already set

2022-08-25 07:06 UTC, Osyotr commented on scripts/cmake/vcpkg_configure_meson.cmake
> +            set(build_cpu ${MACHINE})
This code should probably match code for host detection below

2022-08-25 07:08 UTC, Osyotr commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +            EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE HOST_ARCH)
Ah sorry, didn't read the comment

2022-08-25 07:44 UTC, vserdyuk commented on scripts/cmake/vcpkg_configure_meson.cmake
> +            set(build_cpu ${MACHINE})
If you mean `VCPKG_TARGET_ARCHITECTURE` check, I think those variables are different. `VCPKG_TARGET_ARCHITECTURE` is defined by vcpkg and for ARM family it is either `arm` or `arm64` while `MACHINE ` variable is a `uname -m` call result and can be `aarch64`, `armv7l`, `armv7h`, etc.

2022-08-25 07:48 UTC, vserdyuk commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +            EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE HOST_ARCH)
Yes, it's defined in each `program` branch separately (when needed). Should probably be defined once in the beginning of the function, though.

2022-08-25 08:57 UTC, Osyotr commented on scripts/cmake/vcpkg_configure_meson.cmake
> +            set(build_cpu ${MACHINE})
I mean, is it ok to assume that host CPU is always `armv7hl` if build CPU can be either `armv7l` or `armv7hl`

2022-08-25 09:28 UTC, vserdyuk commented on scripts/cmake/vcpkg_configure_meson.cmake
> +            set(build_cpu ${MACHINE})
Unfortunately, the `arm` value of `VCPKG_TARGET_ARCHITECTURE` lost it's precision whether it's `armv7l` or `armv7hl` while `MACHINE` variable has the exact information. Now we do our best effort to provide the most accurate information.
I have 32-bit Ubuntu 20.04 on Raspberry Pi 4B and `uname -m` gives me `armv7l`. So `build_cpu` being `armv7l` works with `host_cpu` being `armv7hl`. Haven't checked whether it will work if I change to `set(build_cpu armv7hl)`. Do you think it's better to hard code it this way?

2022-08-26 08:55 UTC, Cheney-W commented
The failure of `kf5globalaccel` and `libx11` is fixing by PR [26486](https://github.com/microsoft/vcpkg/pull/26486).

2022-08-26 08:58 UTC, Neumann-A commented
`kf5globalaccel` is not fixed by that. Seems like `kf5globalaccel` needs to explicitly disable x11 usage on windows.

2022-08-30 15:46 UTC, vserdyuk commented
Are there any additional steps to be taken to push this forward? Considering failing pipelines (Windows. UWP, etc.) have nothing to do with the change?

2022-09-08 06:29 UTC, Cheney-W commented
/azp run

2022-09-10 06:44 UTC, Neumann-A commented
Can you not simply use `set(NINJA <yourpath>)` in the triplet to achieve the same ?

2022-09-10 07:31 UTC, dg0yt requested changes

2022-09-10 07:31 UTC, dg0yt commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +            EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE HOST_ARCH)
`exec_program` is deprecated already since CMake 3.0.

2022-09-10 07:31 UTC, dg0yt commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +            EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE HOST_ARCH)
`exec_program` is deprecated already since CMake 3.0.

2022-09-10 09:15 UTC, vserdyuk commented
> Can you not simply use `set(NINJA <yourpath>)` in the triplet to achieve the same ?

I reverted my fix and added hard-coded path to ninja this to arm-linux triplet and it worked. But if we take this approach, we will have to patch all non-x64 linux tripet files.

2022-09-10 09:29 UTC, vserdyuk commented on scripts/cmake/vcpkg_find_acquire_program.cmake
> +            EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE HOST_ARCH)
I replaced it with execute_process

2022-09-10 12:17 UTC, dg0yt commented
> But if we take this approach, we will have to patch all non-x64 linux tripet files.

No, it is a host tool, so in general, its path cannot be in the (target) triplet files.

2022-09-16 08:51 UTC, Cheney-W commented
/azp run

2022-10-01 00:22 UTC, merged