Bump spix version to 0.4 and add qt6 variant
microsoft/vcpkg pull request #26555
Opened 2022-08-27 14:40 UTC by m-kuhn

**Describe the pull request**

- #### What does your PR fix?
  Bumps spix version to v0.4
  Add a variant for qt6 (follows the pattern of qtkeychain/qtkeychain-qt6)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-08-28 13:22 UTC, m-kuhn commented
Is it possible to offer two ports with conflicting files?

2022-09-07 06:49 UTC, Adela0814 commented
> Is it possible to offer two ports with conflicting files?

Yes, but it is necessary to judge whether the conflicting port file exists in each port. If it exists, the current port will fail, and a warning message should be printed.
Dependencies of the same port are not allowed to be conflicting ports.

2022-09-07 12:45 UTC, m-kuhn commented
What we have in this PR are two versions of the same library built against qt5 and qt6.

The checks are failing because of conflicting files, how can I teach the ci to ignore these conflicts? Should I simply flag `spix-qt6` as expected failure as proposed by the error?

```
REGRESSION: spix-qt6:x64-linux failed with FILE_CONFLICTS. If expected, add spix-qt6:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
```

2022-09-08 09:35 UTC, JackBoosY commented
So the only choice is disable one of the 2 ports and set the conflict error message in `portfile.cmake`.

Wait, I think we should just modify spix dependency from `qt5*` to `qt*`.

2022-09-08 10:58 UTC, m-kuhn commented
> So the only choice is disable one of the 2 ports and set the conflict error message in `portfile.cmake`.
> 
> Wait, I think we should just modify spix dependency from `qt5*` to `qt*`.

What's the question?

2022-09-09 02:43 UTC, JackBoosY commented
> What's the question?

The question is that it's not different versions of spix, but different versions of dependencies.
Since the dependency corresponds to feature, we should change the feature instead of adding a new port.

2022-09-09 05:19 UTC, m-kuhn commented
@JackBoosY
From [the features documentation](https://vcpkg.readthedocs.io/en/latest/maintainers/maintainer-guide/#features)

> ## Do not use features to implement alternatives
> Features must be treated as additive functionality. If port[featureA] installs and port[featureB] installs, then port[featureA,featureB] must install. Moreover, if a second port depends on [featureA] and a third port depends on [featureB], installing both the second and third ports should have their dependencies satisfied.
> 
> Libraries in this situation must choose one of the available options as expressed in vcpkg, and users who want a different setting must use overlay ports at this time.
> 
> Existing examples we would not accept today retained for backwards compatibility: * libgit2, libzip, open62541 all have features for selecting a TLS or crypto backend. Note that curl has different crypto backend options but allows selecting between them at runtime, meaning the above tenet is maintained. * darknet has opencv2, opencv3, features to control which version of opencv to use for its dependencies.

I do have no issue with going this way if it's preferred. In this case, I'd recommend doing the same for qtkeychain and other qt6 capable ports.

2022-09-09 06:19 UTC, JackBoosY commented
> I do have no issue with going this way if it's preferred. In this case, I'd recommend doing the same for qtkeychain and other qt6 capable ports.

For ports qt*, the reason we choose to do this is that they themselves have been updated and are not compatible with the original version, similar examples are opencv.
The current port is different.

2022-09-09 06:29 UTC, m-kuhn commented
> > I do have no issue with going this way if it's preferred. In this case, I'd recommend doing the same for qtkeychain and other qt6 capable ports.
> 
> For ports qt*, the reason we choose to do this is that they themselves have been updated and are not compatible with the original version, similar examples are opencv. The current port is different.

👍 So for qca, spix, qwt, etc it should be a feature.

Qtkeychain would IMO also belong to this group, since it's not core qt just happens to have a similar name. There's even an info about this shown during installation.

2022-09-13 20:46 UTC, m-kuhn commented
I don't particularly like this implementation with 2 features `qt5` and `qt6` but I didn't find a way to do it with only the `qt6` feature and conditionally add qt5 specific dependencies only if the `qt6` feature is _not_ enabled.

2022-09-14 06:43 UTC, JackBoosY commented
> I don't particularly like this implementation with 2 features `qt5` and `qt6` but I didn't find a way to do it with only the `qt6` feature and conditionally add qt5 specific dependencies only if the `qt6` feature is _not_ enabled.

The only way we should do is update the dependecy from `qt5` to `qt6` since they have conflict.

2022-09-14 07:22 UTC, m-kuhn commented
> > I don't particularly like this implementation with 2 features `qt5` and `qt6` but I didn't find a way to do it with only the `qt6` feature and conditionally add qt5 specific dependencies only if the `qt6` feature is _not_ enabled.
> 
> The only way we should do is update the dependecy from `qt5` to `qt6` since they have conflict. In fact, many ports did that, example: the opencv downstream ports.

I had a look at the `opencv` downstream port `darknet` and took it as an example, there are 2 features `opencv-base` and `opencv2-base`. This corresponds to the approach in here with the features `qt5` and `qt6`. Is that ok?

2022-09-14 07:24 UTC, Neumann-A commented
> Is that ok?

No. See: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives

2022-09-14 08:54 UTC, m-kuhn commented
@Neumann-A I thought the same, see https://github.com/microsoft/vcpkg/pull/26555#issuecomment-1241509736 but the recommendation in the discussion in here was different

2022-09-15 02:44 UTC, JackBoosY commented
> I had a look at the `opencv` downstream port `darknet` and took it as an example, there are several features `opencv-base`, `opencv2-base`, .... This corresponds to the approach in here with the features `qt5` and `qt6`. Is that ok?

See the document link:

Existing examples we would **not accept today** retained for backwards compatibility: * libgit2, libzip, open62541 all have features for selecting a TLS or crypto backend. Note that curl has different crypto backend options but allows selecting between them at runtime, meaning the above tenet is maintained. * darknet has opencv2, opencv3, features to control which version of opencv to use for its dependencies.

2022-09-15 03:54 UTC, m-kuhn commented
@JackBoosY can you tell me how this should be implemented as feature, as I believe you have proposed in https://github.com/microsoft/vcpkg/pull/26555#issuecomment-1241434899 . A reference to an example would be ideal. Thank you.

2022-09-15 06:16 UTC, m-kuhn commented
An alternative interpretation of this discussion would be that the `qt5` version should be completely abandoned and replaced by `qt6`. If this is true, I don't know why "features" where mentioned above :thinking:

2022-09-15 06:42 UTC, JackBoosY requested changes

2022-09-15 06:42 UTC, JackBoosY commented on ports/spix/vcpkg.json
> +  }
Since spix requires one of qt versions, we shouldn't set it as a feature.
So my suggestion is to change the dependencies `qt5-base` and `qt5-declarative` to `qtbase` and `qtdeclarative`.

2022-09-15 07:23 UTC, m-kuhn commented on ports/spix/vcpkg.json
> +  }
So spix will be incompatible with other qt downstream ports like `qca` and also `qt5-*`. Whereas the `qtkeychain` downstream port offers variants.
What is the migration plan/policy for qt downstream ports?

2022-09-15 07:49 UTC, JackBoosY commented on ports/spix/vcpkg.json
> +  }
> So spix will be incompatible with other qt downstream ports like qca and also qt5-*. Whereas the qtkeychain downstream port offers variants.

Yes. Like other ports.

> What is the migration plan/policy for qt downstream ports?

We should keep all ports qt5* and update dependencies qt5* that depend on them to qt.

2022-09-15 07:59 UTC, m-kuhn commented on ports/spix/vcpkg.json
> +  }
> > So spix will be incompatible with other qt downstream ports like qca and also qt5-*. Whereas the qtkeychain downstream port offers variants.
> 
> Yes. Like other ports.

Yes what?

> 
> > What is the migration plan/policy for qt downstream ports?
> 
> We should keep all ports qt5* and update dependencies qt5* that depend on them to qt.

That translates to: qt5 is being phased out, correct?

2022-09-15 09:54 UTC, JackBoosY commented on ports/spix/vcpkg.json
> +  }
> Yes what?

As I said, like other ports which depends on opencv. But we can't accpet some of the method now.

> That translates to: qt5 is being phased out, correct?

Yes, vcpkg should always focus on the latest port version.
However, the API gap between the various versions of Qt is too huge. We can accept that keep each large version of them, but we cannot accept the ports that depend on them to be split or used as features.

2022-09-17 05:54 UTC, m-kuhn commented on ports/spix/vcpkg.json
> +  }
And Qt6 is gone

2022-09-19 02:31 UTC, JackBoosY approved these changes

2022-09-19 19:38 UTC, merged