[boost-modular-build-helper] Add BSD and FreeBSD target-os
microsoft/vcpkg pull request #26562
Opened 2022-08-27 20:33 UTC by noeffn

- #### What does your PR fix?
  Fixes b2 using the wrong operating system on bsd/freebsd resulting in <cstddef> not being found 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-08-27 20:51 UTC, noeffn commented
Okay this will probably not work like this https://github.com/Kitware/CMake/blob/master/Modules/Platform/FreeBSD.cmake
I looked at this and thought it would be included on BSD

2022-08-27 21:04 UTC, noeffn commented
I now use CMAKE_SYSTEM_NAME altough I dont know if it would be better to use VCPKG_CMAKE_SYSTEM_NAME set in the triplet

2022-08-29 07:18 UTC, JonLiu1993 requested changes

2022-08-29 07:18 UTC, JonLiu1993 commented on ports/boost-modular-build-helper/vcpkg.json
> +  "port-version": 2,
```suggestion
  "port-version": 1,
```

2022-08-29 07:18 UTC, JonLiu1993 commented on versions/b-/boost-modular-build-helper.json
> +    },
```suggestion
```

2022-08-29 07:18 UTC, JonLiu1993 commented on versions/b-/boost-modular-build-helper.json
> +    },
@noeffn ,Thanks for your pr, please remove this code and change the `port-version` to 1, then run the command "./vcpkg x-add-version boost-modular-build-helper --overwrite-version" and commit again

2022-08-29 09:13 UTC, noeffn commented
Done

2022-08-30 03:08 UTC, JonLiu1993 submitted a review, later dismissed

2022-08-31 22:27 UTC, JavierMatosD requested changes

2022-08-31 22:27 UTC, JavierMatosD commented on ports/boost-modular-build-helper/CMakeLists.txt
> +elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
```suggestion
elseif(VCPKG_DETECTED_CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")

```

2022-09-01 00:32 UTC, noeffn commented on versions/b-/boost-modular-build-helper.json
> +
bad merge

2022-09-01 00:34 UTC, noeffn commented on ports/boost-modular-build-helper/CMakeLists.txt
> +elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
Done

2022-09-01 02:50 UTC, JonLiu1993 approved these changes

2022-09-02 17:47 UTC, JavierMatosD approved these changes

2022-09-02 17:47 UTC, JavierMatosD commented
Thanks!

2022-09-02 17:47 UTC, merged