[issue template] Emphasise that console output isn't enough
microsoft/vcpkg pull request #26569
Opened 2022-08-28 14:29 UTC by Thomas1664

**Describe the pull request**

- #### What does your PR fix?
  I noticed that most new issues just provide the console output when they report a port build failure. The problems are that this is not helpful at all and increases the time it needs to investigate an issue. It seems like users stop reading after `Failure logs` and remove everything that comes after it.

2022-08-28 14:38 UTC, m-kuhn commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +- Please attach any additional failure logs mentioned in the console output.
```suggestion
- Attach any additional **failure log files** mentioned in the console output.
```

Let's be a bit more explicit here

2022-08-28 14:45 UTC, Thomas1664 commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +- Please attach any additional failure logs mentioned in the console output.
Thanks for your suggestion!

I replaced `additional` with `every` because I think that the term `additional` implies that the log files *just* provide additional information and that it is therefore not mandatory to provide them.

2022-08-28 14:46 UTC, m-kuhn commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +- Attach ***every failure log files*** mentioned in the console output.
```suggestion
- Attach ***every failure log file*** mentioned in the console output.
```

Typo from me already

2022-08-28 16:29 UTC, m-kuhn commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +‼ **Note that you also have to provide the contents of *all* log files mentioned in the console output.** ‼
I'm not convinced a "also" note should come before the note it's meant to supplement.
I'd probably just add the emphasis added in the latest commit.

2022-08-28 16:58 UTC, Thomas1664 commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +‼ **Note that you also have to provide the contents of *all* log files mentioned in the console output.** ‼
I put this note intentionally above the `**Failure logs**` section because my observation is that people often replace the comments underneath `**Failure logs**`. If you browse through issues that have `requires:more-information`, you'll see what I mean.
Although I agree that this comment is somewhat redundant with the other comment below, I'd prefer to keep both because my hope is that people won't delete things that are above `**Failure logs**`.

The comment bellow describes more precisely what the user should do and how to do it whereas this comment is a reminder to do so and tries to explain why the log files are important.

That being said, I don't think it is sufficient to put more emphasis on the comment below because it is likely to get deleted without reading it anyways. In contrast, comments above the `**Failure logs**` section seem to get deleted less likely. If someone removes every comment below `**Failure logs**` and replaces it with their console output, the lines above will still be visible after the issue was created. My hope is that a user will then read them and add the contents of the log files.

2022-08-29 08:18 UTC, Osyotr commented
I wonder if `validation` can be used here 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#validations-2

2022-08-29 09:24 UTC, JackBoosY commented
Needs other maintainers to further review.

2022-08-29 15:52 UTC, autoantwort commented
Theoretically there is also the prefilled autogenerated issue body that could/should be used.

2022-08-29 21:25 UTC, JavierMatosD submitted a review, later dismissed

2022-08-29 21:25 UTC, JavierMatosD commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +‼ **Note that you also have to provide the contents of *all* log files mentioned in the console output.** ‼
I agree with @m-kuhn concern about including supplementary notes before the thing it supplements. I also agree with @autoantwort's suggestion to use the prefilled autogenerated issue body. Additionally, I would like to avoid redundancy whenever possible, and I believe this note and the one below emphasize the same thing.

2022-08-29 22:17 UTC, Thomas1664 commented
> Theoretically there is also the prefilled autogenerated issue body that could/should be used.

I created https://github.com/microsoft/vcpkg-tool/pull/681 . Hopefully, this feature will be used by more users in the future.

2022-09-12 22:49 UTC, Thomas1664 commented
@JavierMatosD @JackBoosY Any progress in reviewing this now that https://github.com/microsoft/vcpkg-tool/pull/681 was merged?

2022-09-13 07:25 UTC, JackBoosY requested changes

2022-09-13 07:25 UTC, JackBoosY commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +labels: ''
```suggestion
labels: category:port-bug
```

2022-09-13 07:25 UTC, JackBoosY commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +<!-- ⁉ You can find its location at the end of the console output. ⁉ -->
```suggestion
<!-- Please use the generated issue template instead to report a port build failure. -->
<!-- You can find its location at the end of the console output. -->
```
Can we remove these graphic characters?

2022-09-13 21:22 UTC, Thomas1664 commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +<!-- ⁉ You can find its location at the end of the console output. ⁉ -->
Why? What's wrong with using emojis?

2022-09-14 02:27 UTC, JackBoosY commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +<!-- ⁉ You can find its location at the end of the console output. ⁉ -->
I'm worried that these emoji won't display properly on some users' pages.

2022-09-14 06:38 UTC, Osyotr commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +<!-- ⁉ You can find its location at the end of the console output. ⁉ -->
Some people just don't read texts... Emojis here are absolutely necessary.

2022-09-14 06:45 UTC, JackBoosY commented on .github/ISSUE_TEMPLATE/report-package-build-failure.md
> +<!-- ⁉ You can find its location at the end of the console output. ⁉ -->
Okay.

2022-09-14 06:45 UTC, JackBoosY approved these changes

2022-09-15 20:15 UTC, BillyONeal approved these changes
I don't think this will do anything but I don't think it will harm anything either.

2022-09-15 21:19 UTC, merged