Mig output
microsoft/vcpkg pull request #26682
Opened 2022-09-05 00:39 UTC by promag

**Describe the pull request**

- #### What does your PR fix?
  Fixes linking on macOS

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-09-05 01:01 UTC, promag commented
Fix discussed here https://groups.google.com/a/chromium.org/g/crashpad-dev/c/XVggc7kvlNs

2022-09-05 03:09 UTC, JonLiu1993 requested changes

2022-09-05 03:09 UTC, JonLiu1993 commented on ports/crashpad/vcpkg.json
> +  "port-version": 4,
```suggestion
```

2022-09-05 03:09 UTC, JonLiu1993 commented on ports/crashpad/vcpkg.json
> +  "port-version": 4,
@promag, Thanks for your pr, if you update a port, you should remove the `port-version`

2022-09-05 03:09 UTC, JonLiu1993 commented on versions/c-/crashpad.json
> +    },
```suggestion
    {
      "git-tree": "955373b979b70472dc4dee66726e2fae83c69e4c",
      "version-date": "2022-04-16",
      "port-version": 4
    },
```

2022-09-05 03:09 UTC, JonLiu1993 commented on versions/c-/crashpad.json
> +    },
Each time we commit pr, we can only add one "versions" record, which is beneficial for us to backtrack later versions

2022-09-05 06:50 UTC, promag commented
@JonLiu1993 apologies, removed `port-version` key from ports/crashpad/vcpkg.json.

2022-09-05 07:15 UTC, JonLiu1993 approved these changes

2022-09-05 09:47 UTC, JonLiu1993 requested changes

2022-09-05 09:47 UTC, JonLiu1993 commented on ports/crashpad/portfile.cmake
> +endif()
```suggestion
if(VCPKG_TARGET_IS_OSX)
    file(COPY "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/obj/util/libmig_output.a" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
    file(COPY "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/obj/util/libmig_output.a" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
endif()
```

2022-09-05 09:47 UTC, JonLiu1993 commented on ports/crashpad/portfile.cmake
> +endif()
The representation and format here need to be modified

2022-09-05 12:50 UTC, promag commented on ports/crashpad/portfile.cmake
> +endif()
Done.

2022-09-06 09:02 UTC, JonLiu1993 approved these changes

2022-09-06 21:54 UTC, merged