[libmariadb] Fix build error on Linux
microsoft/vcpkg pull request #26704
Opened 2022-09-06 09:50 UTC by LilyWangLL

**Describe the pull request**

- #### What does your PR fix?
  Fixes #26697, fixes #26366. Fix build error on Linux:
```
CMake Error:
  Running

   '/home/lily/0729/downloads/tools/ninja/1.10.2-linux/ninja' '-C' '/home/lily/0729/buildtrees/libmariadb/x64-linux-dbg' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:1401: multiple rules generate libmariadb/libmariadb.a [-w dupbuild=err]
```

2022-09-06 09:52 UTC, LilyWangLL commented on scripts/ci.baseline.txt
> +libmysql:arm64-windows      = skip
Since `libmysql` and `libmariadb` are incompatible, so here's changes is opening `libmariadb` test on CI pipeline, once CI test pass I will revert these change.

2022-09-06 11:39 UTC, dg0yt requested changes

2022-09-06 11:39 UTC, dg0yt commented on ports/libmariadb/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
Why is this fixup only for Windows now?

2022-09-06 11:39 UTC, dg0yt commented on ports/libmariadb/no-extra-static-lib.patch
> ++IF(VCPKG_MARIADBCLIENT)
The case changes are not needed, but who cares.

2022-09-06 11:39 UTC, dg0yt commented on ports/libmariadb/no-extra-static-lib.patch
> + create_symlink(libmariadb${CMAKE_STATIC_LIBRARY_SUFFIX} mariadbclient ${INSTALL_LIBDIR})
With this being the only change, I doubt that this solves the problem: The command takes immediate effect. It doesn't affect build rules.

2022-09-07 00:16 UTC, beats-dh commented
![image](https://user-images.githubusercontent.com/61994374/188761651-53125d3d-9c5a-4fdc-b2dd-a7b0876a8823.png)

2022-09-07 07:29 UTC, LilyWangLL commented on ports/libmariadb/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
Fix by `fix-CMakeLists.patch`.

2022-09-07 07:30 UTC, LilyWangLL commented on ports/libmariadb/no-extra-static-lib.patch
> + create_symlink(libmariadb${CMAKE_STATIC_LIBRARY_SUFFIX} mariadbclient ${INSTALL_LIBDIR})
Have disable by `fix-CMakeLists.patch`.

2022-09-08 00:30 UTC, beats-dh commented
> @beats-dh Could you test this PR again?

Now it worked perfectly!!

2022-09-08 00:30 UTC, beats-dh approved these changes, later dismissed

2022-09-08 04:14 UTC, dg0yt requested changes

2022-09-08 04:14 UTC, dg0yt commented on ports/libmariadb/fix-CMakeLists.patch
> +
Is the guarding of `create_symlink` the only actual change? If yes, I would prefer the PR wouldn't completely restructure the patches, for traceability.

2022-09-08 05:40 UTC, LilyWangLL commented on ports/libmariadb/fix-CMakeLists.patch
> +
This patch also fix CMake export, the original file is only exported to CMake under `WIN32`.

2022-09-08 14:08 UTC, dg0yt commented on ports/libmariadb/fix-CMakeLists.patch
> +
Okay.

2022-09-08 14:08 UTC, dg0yt commented on ports/libmariadb/fix-CMakeLists.patch
> +   SET_TARGET_PROPERTIES(libmariadb PROPERTIES COMPILE_FLAGS "${CMAKE_SHARED_LIBRARY_C_FLAGS}")
Aren't we concerned about explicitly setting `CMAKE_SHARED_LIBRARY_C_FLAGS` on a possibly-static library?

2022-09-09 02:57 UTC, LilyWangLL commented on ports/libmariadb/fix-CMakeLists.patch
> +   SET_TARGET_PROPERTIES(libmariadb PROPERTIES COMPILE_FLAGS "${CMAKE_SHARED_LIBRARY_C_FLAGS}")
The value of `CMAKE_SHARED_LIBRARY_C_FLAGS` is `-fPIC`, I removed this.

2022-09-09 08:47 UTC, JackBoosY commented on ports/libmariadb/fix-CMakeLists.patch
> +diff --git a/libmariadb/CMakeLists.txt b/libmariadb/CMakeLists.txt
Note to other reviewer: this changes is come from `fix-installpath.path` and we approved it.

2022-09-09 08:47 UTC, JackBoosY approved these changes

2022-09-12 20:50 UTC, merged