[node-api] Add new port
microsoft/vcpkg pull request #26768
Opened 2022-09-12 22:26 UTC by Pospelove

2022-09-13 03:55 UTC, longnguyen2004 commented on ports/node-api/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
To check for the host, use `CMAKE_HOST_WIN32` or `VCPKG_HOST_IS_WINDOWS`

2022-09-13 12:54 UTC, Pospelove commented on ports/node-api/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
@longnguyen2004 thanks, I'll fix. Btw do you know how to make node tool the same triplet as port? Host: true isn't acceptable. We need x86-windows to have x86-windows node-tool dependency. Please tell me if you know 🙏

2022-09-13 23:19 UTC, Pospelove commented
@JackBoosY @FrankXie05 could you please take a look?

2022-09-14 05:48 UTC, dg0yt requested changes

2022-09-14 05:48 UTC, dg0yt commented on ports/node-api/node-api-config.cmake
> +set(node-api_INCLUDE_DIR "${node-api_INCLUDE_DIR}/node")
This should be collapsed to a single find_path. IMO it should also use `PATHS "${CMAKE_CURRENT_LIST_DIR}/../../include" NO_DEFAULT_PATH`.

2022-09-14 05:48 UTC, dg0yt commented on ports/node-api/node-api-config.cmake
> +find_library(node-api_LIBRARY NAMES node)
This is not enough. You must find debug and release variant separately. Again, I would suggest to add `PATHS` and `NO_DEFAULT_PATH`.

2022-09-14 05:48 UTC, dg0yt commented on ports/node-api/node-api-config.cmake
> +add_library(node_api INTERFACE)
This should be an `unofficial::node-api::node-api UNKNOWN IMPORTED`, and the following properties have to be modified accordingly.

2022-09-14 05:48 UTC, dg0yt commented on ports/node-api/portfile.cmake
> +file(COPY "${CMAKE_CURRENT_LIST_DIR}/node-api-config.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
This is not official, so it must be installed to `share/unofficial-node-api/unofficial-node-api-config.cmake`.

2022-09-14 05:48 UTC, dg0yt commented on scripts/ports.cmake
> +include("${SCRIPTS}/cmake/vcpkg_execute_npm_command.cmake")
No, no more scripts here. You can add a script port (like `vcpkg-cmake`) if you really need more script functions.

2022-09-14 05:48 UTC, dg0yt commented on scripts/cmake/vcpkg_execute_npm_command.cmake
> +endfunction()
I don't see the added value of this command over `execute_command`. And vcpkg already has wrappers, for example to handle logging.

2022-09-14 06:23 UTC, JackBoosY commented
```
CMake Error at ports/node-api/portfile.cmake:5 (message):
  node not found! Please install it via your system package manager!
```
two way to fix this:
- Add new tool `node` to `vcpkg_find_acquire_program`
- Add this tool installation to our pipeline script.

2022-09-14 06:40 UTC, longnguyen2004 commented
> * Add new tool `node` to `vcpkg_find_acquire_program`

Which would be a world rebuild...let's not do that

2022-09-14 06:44 UTC, JackBoosY commented
> > * Add new tool `node` to `vcpkg_find_acquire_program`
> 
> Which would be a world rebuild...let's not do that

Can you please provide the official doc for install node?

2022-09-14 07:37 UTC, dg0yt commented
> * Add new tool `node` to `vcpkg_find_acquire_program`

Again, please no new tools in `vcpkg_find_acquire_program`.

2022-09-14 07:50 UTC, JackBoosY commented
> Again, please no new tools in `vcpkg_find_acquire_program`.

As @BillyONeal said, we plan to migrate all tools to `vcpkg_find_acquire_program` and use vcpkg instead of cmake to download and unpack them in the future.

2022-09-14 08:04 UTC, dg0yt commented
> > Again, please no new tools in `vcpkg_find_acquire_program`.
> 
> As @BillyONeal said, we plan to migrate all tools to `vcpkg_find_acquire_program` and use vcpkg instead of cmake to download and unpack them in the future.

I don't know where this is was said. But I think in order to do so, you must decouple the tool data from the downloads script. We cannot trigger even more world rebuilds from this script. The script simply doesn't scale in its current form (factors: number of tools, number of host platforms, tool versions),

2022-09-14 10:22 UTC, Pospelove commented
I'll take a look at CI failures a little bit later. Looks fixable

2022-09-16 15:12 UTC, Pospelove commented
@JackBoosY @FrankXie05 I think it's ready could you please take a look?

2022-09-24 04:12 UTC, Pospelove commented
@JackBoosY Any progress on this?

2022-09-27 08:42 UTC, JackBoosY commented
Sorry for late, I will review this PR again tomorrow.

2022-09-29 07:06 UTC, JackBoosY requested changes

2022-09-29 07:06 UTC, JackBoosY commented on ports/node-api/portfile.cmake
> +)
I still think it's a bad idea.
Usually we inform the user to use the package manager to install the required package instead of calling the install command directly using the package manager.
Such as:
https://github.com/microsoft/vcpkg/blob/a9613b57751ea9dd7006f251ed1af1ccf3a808f9/ports/angle/portfile.cmake#L3

2022-09-29 09:09 UTC, Pospelove commented on ports/node-api/portfile.cmake
> +)
@JackBoosY Oh. Thanks for your time reviewing this. 
I can try redo this without npm, but that's why I think it's fine to use npm here:

- It's not a global node/npm, it comes from `vcpkg-tool-nodejs` port, so it doesn't touch system package manager.
- Installation dir is also out of the system. It uses `installed/vcpkg-tool-nodejs/node_modules`. So it doesn' pollute the system with packages.
- Everything installed here gets removed at the end of `portfile.cmake` so it doesn't leave garbage in `installed` too.

If it's strictly required I may change this, but I hope it's not. Cause I put everything out of system/user directories. I think I follow guidelines.

2022-09-29 09:09 UTC, Pospelove commented on ports/node-api/cmake-js-fetch/CMakeLists.txt
> +foreach(p ${CMAKE_JS_INC})
@JackBoosY Yeah sounds reasonable. Will do.

2022-09-29 22:07 UTC, Pospelove commented on ports/node-api/cmake-js-fetch/CMakeLists.txt
> +foreach(p ${CMAKE_JS_INC})
@JackBoosY  done

2022-09-29 22:12 UTC, Pospelove commented on ports/node-api/portfile.cmake
> +)
@JackBoosY
Also we should rely on npm version bundled with `vcpkg-tool-nodejs` port, not the system one.

2022-09-30 06:09 UTC, JackBoosY commented on ports/node-api/portfile.cmake
> +)
We want to avoid adding new tool ports and instead use `vcpkg_find_acquire_program` to add tools to download them directly using vcpkg in the future.

2022-09-30 07:38 UTC, dg0yt commented on ports/node-api/portfile.cmake
> +)
@JackBoosY Can you please tell us when this future is scheduled? Until then, we want to avoid adding more tools `vcpkg_find_acquire_program` because changes and additions trigger world rebuilds and must be avoided.

2022-09-30 07:48 UTC, JackBoosY commented on ports/node-api/portfile.cmake
> +)
cc @BillyONeal

2022-09-30 09:27 UTC, Pospelove commented on ports/node-api/portfile.cmake
> +)
@JackBoosY 

> We want to avoid adding new tool ports and instead use `vcpkg_find_acquire_program` to add tools to download them directly using vcpkg in the future.

@JackBoosY I see. This PR doesn't add new tool ports, only uses existing one

2022-10-03 11:13 UTC, Pospelove commented
@BillyONeal Could you please take a look?

2022-10-05 23:52 UTC, Pospelove commented
Hey @BillyONeal Could you please take a quick look?

2022-10-09 23:48 UTC, Pospelove commented
Hey @JackBoosY

2022-10-10 01:56 UTC, JackBoosY commented
We will have some discussion internal this week.

2022-10-10 11:23 UTC, Pospelove commented
Glad to hear. looking forward to it. Just gave this thread multiple pings to make sure that the RP isn't abandoned. Thank you very much!

2022-10-19 02:43 UTC, Pospelove commented
and what about the pr lololol @Cheney-W

2022-10-22 04:45 UTC, BillyONeal commented
Thanks for your contribution, sorry it's been a bit of a runaround :)

> 2\. cmake-js, requires npm on host system, requires writing `cmake-js` command instead of `cmake <source_dir>`

I mean, possibly, but given that this port appears to be a thin wrapper around npm, I'm not sure what the user experience is intended to be of this port? Can you show like a "before and after"? Because this seems just actively worse than invoking npm directly. (To be clear, I'm not saying that it *is* worse than invoking NPM directly, only that it isn't obvious to me reading this right now.) What is a vcpkg customer who got this install expected to do with the results?

Other concerns:
* This isn't going to work with artifact caching because the download is done inside npm's guts, and unlikely to play nicely with binary caching because npm tends to be full of symlink stuff.
* This is "installing" things into the node.js instance vcpkg provides sometimes for other ports to play with, but appears to be attempting to provide services for *users* of vcpkg, who can't depend on that node.js instance being durable.

===============

New port checklist:
* Review the code ❗
* Check the name against https://repology.org/
No match ⚠️
* Check the name against Bing/Google. (If the first results aren't C++ related, try "name C++")
The first hit may be related, but I don't see how what's installed here is connected? ⚠️
* Check the source code for optional `find_package`s ✅
* Check that the versioning scheme matches what upstream says 
This is installing cmake-js@7.0.0-3 but is claiming to be 14.17.4 ⚠️
* Check that the license in vcpkg.json matches what upstream says ✅
MIT == https://github.com/cmake-js/cmake-js/blob/master/LICENSE
* Check that the license installed by the port matches what upstream says
file(INSTALL "${NODEJS_DIR}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
A node.js LICENSE has a lot of stuff that isn't MIT ❗
* Check that the source code comes from the upstream project's authoritative source.
I don't even know how to evaluate this. It certainly isn't pointed at cmake-js's github repo...
* Check that the generated usage is accurate.
(Didn't try yet)
* Check for issues that are resolved.
Fixes https://github.com/microsoft/vcpkg/issues/26769 .

2022-10-22 15:49 UTC, Pospelove commented
Hey @BillyONeal and thank you for your review

> I mean, possibly, but given that this port appears to be a thin wrapper around npm, I'm not sure what the user experience is intended to be of this port? Can you show like a "before and after"? Because this seems just actively worse than invoking npm directly. (To be clear, I'm not saying that it is worse than invoking NPM directly, only that it isn't obvious to me reading this right now.) What is a vcpkg customer who got this install expected to do with the results?

I left a comment at the top of `portfile.cmake`. I think it can be useful in the future.

```yml
# NodeJS has native modules API called node-api.
# This port uses cmake-js to download and build node-api for you.
# NPM is required to run cmake-js.

# Nor NPM output nor cmake-js output is left after portfile.cmake execution like npm packages or any other files.
# ${DOWNLOADS} and ${NODEJS_BIN_DIR} folders are used in process, but they are cleaned at the end.

# As a normal port, this port leaves some includes and libraries in ${CURRENT_PACKAGES_DIR}.
# So it doesn't break binary caching or any other vcpkg features
```

- **review the code**, ok, it's up to you
- **Check the name against https://repology.org/**: Not sure about naming, didn't want to name it `node` or `nodejs` since it's too common. Maybe worth trying `node-n-api`. There is also [C++ Embedder API](https://nodejs.org/api/embedding.html) of NodeJS which is out of scope of this port. So. I'd accept any name you suggest
- **Check the name against Bing/Google.** For both the first result is https://nodejs.org/api/n-api.html which is totally expected.
- **Check the source code for optional find_packages** Yeah it works
- **Check that the versioning scheme matches what upstream says. This is installing cmake-js@7.0.0-3 but is claiming to be 14.17.4.** We're installing node-api, not cmake-js. So it's the version of nodejs. cmake-js is just a helper tool. It gets wiped at the end of portfile.cmake
- **Check that the license in vcpkg.json matches what upstream says.** I see. removing MIT for now, please let me know what do I type in vcpkg.json license field
- **Check that the source code comes from the upstream project's authoritative source.**
  npm would throw "checksum failed while installing cmake-js" in case of checksums mismatch.
  btw cmake-js verifies file checksums too:
  https://github.com/cmake-js/cmake-js/blob/afdaaf203376303abd4dbd78379c0883e6faa6c2/lib/downloader.js#L89
- **Check that the generated usage is accurate.** It is, there is [example project](https://github.com/Pospelove/napi-test/tree/main), but yeah feel free to check

2022-10-26 19:56 UTC, BillyONeal commented
I'm sorry I'm still confused. Can you show what, for example, the shortest possible `vcpkg.json` + `CMakeLists.txt` + .cpp file that would consume this port would look like?

If it's too much for a comment you can put it on gist.github.com.

Here's an example of what I mean for zlib:

```
C:\Dev\test>type CMakeLists.txt
cmake_minimum_required(VERSION 3.24)
project(demo)
find_package(ZLIB REQUIRED)
add_executable(test test.cpp)
target_link_libraries(test PRIVATE ZLIB::ZLIB)

C:\Dev\test>type test.cpp
#include <stdio.h>
#include <zlib.h>

int main() {
    puts(ZLIB_VERSION);
}

C:\Dev\test>type vcpkg.json
{
    "dependencies": ["zlib"]
}

C:\Dev\test>cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=C:\Dev\vcpkg2\scripts\buildsystems\vcpkg.cmake -S . -B out
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
  * vcpkg-cmake[core]:x64-windows -> 2022-09-26
    zlib[core]:x64-windows -> 1.2.12#2
Additional packages (*) will be modified to complete this operation.
Restored 2 package(s) from C:\Users\bion\AppData\Local\vcpkg\archives in 50.87 ms. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 9.379 ms
Installing 2/2 zlib:x64-windows...
Elapsed time to handle zlib:x64-windows: 17.61 ms

Total elapsed time: 2.153 s
The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

-- Running vcpkg install - done
-- The C compiler identification is MSVC 19.34.31931.0
-- The CXX compiler identification is MSVC 19.34.31931.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.34.31931/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/MSVC/14.34.31931/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: optimized;C:/Dev/test/out/vcpkg_installed/x64-windows/lib/zlib.lib;debug;C:/Dev/test/out/vcpkg_installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.12")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Dev/test/out

C:\Dev\test>ninja -C out
ninja: Entering directory `out'
[2/2] Linking CXX executable test.exe

C:\Dev\test>.\out\test.exe
1.2.12

C:\Dev\test>
```

2022-10-26 22:23 UTC, BillyONeal commented on ports/node-api/portfile.cmake
> +set(npm_args --prefix "${NODEJS_BIN_DIR}" install cmake-js@7.0.0-3)
@ras0219-msft @dan-shaw @JavierMatosD @markle11m @AugP @ValeriaConde and I discussed this NPM part today because we are concerned that this does not respect asset caching settings. To that end, to accept this port, we want any downloads of parts to use `vcpkg_download_distfile`. (You can give the resulting tarballs to `npm` for extraction and similar if you want)

2022-12-15 03:10 UTC, Pospelove commented
Hey @BillyONeal
I think it works now, no npm stuff at all

2022-12-15 09:53 UTC, Cheney-W commented on ports/node-api/portfile.cmake
> +set(NODEJS_VERSION 18.12.1)
```suggestion
vcpkg_minimum_required(VERSION 2022-10-12) # for ${VERSION}
```

You could use `${VERSION}` directly in the portfile.cmake instead of set a new version variable.

2022-12-15 11:14 UTC, Pospelove commented on ports/node-api/portfile.cmake
> +set(NODEJS_VERSION 18.12.1)
Added. Thank you

2022-12-23 21:07 UTC, dan-shaw approved these changes

2022-12-23 21:09 UTC, Pospelove commented
@dan-shaw heyy let's go merge

2023-01-04 18:05 UTC, Pospelove commented
@vicroms

2023-01-04 22:26 UTC, merged