[binlog] Add new port
microsoft/vcpkg pull request #26843
Opened 2022-09-16 21:41 UTC by eddiejames

**Describe the pull request**

Add binlog, a high performance C++ log library to produce structured binary logs.

- #### What does your PR fix?
  New port.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Hopefully?

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
 Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-09-19 06:57 UTC, JonLiu1993 commented
@eddiejames, Thanks for your pr, please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/78157/artifacts?artifactName=failure%20logs%20for%20arm-uwp&api-version=7.0&%24format=zip). Please ping me if you need any help.

2022-09-20 02:43 UTC, JonLiu1993 commented
@eddiejames, Thanks for your pr, when I tested the binlog:x64-windows usage, I got a error:
could you please take a look:
````
1> [CMake] CMake Error at F:/Feature-test/binlog/vcpkg/installed/x64-windows/share/binlog/binlogTargets.cmake:96 (message):
1> [CMake]   The imported target "binlog::bread" references the file
1> [CMake] 
1> [CMake]      "F:/Feature-test/binlog/vcpkg/installed/x64-windows/tools/binlog/bread.exe"
1> [CMake] 
1> [CMake]   but this file does not exist.  Possible reasons include:
1> [CMake] 
1> [CMake]   * The file was deleted, renamed, or moved to another location.
1> [CMake] 
1> [CMake]   * An install or uninstall procedure did not complete successfully.
1> [CMake] 
1> [CMake]   * The installation package was faulty and contained
1> [CMake] 
1> [CMake]      "F:/Feature-test/binlog/vcpkg/installed/x64-windows/share/binlog/binlogTargets.cmake"
1> [CMake] 
1> [CMake]   but not all the files it references.
````

CMakelists.txt:
````
cmake_minimum_required (VERSION 3.8)

project(test)

find_package(binlog CONFIG REQUIRED)

add_executable (main "CMakeProject42.cpp" "CMakeProject42.h")

target_link_libraries(main PRIVATE binlog::binlog binlog::headers)
````

CMakeProject42.cpp:
````
#include "CMakeProject42.h"
#include "binlog/binlog.hpp"

using namespace std;

int main()
{
	cout << "Hello CMake." << endl;
	return 0;
}
````

2022-09-21 12:08 UTC, erenon commented
hi (binlog author here), thanks for the new port! What's the root cause of the error? Is the bread.exe install path wrong somehow? I'd rather have a fix here, so the vcpkg install is complete, if possible, otherwise the users will have an incomplete distribution, forced to recompile some parts on demand when eventually needed.

2022-09-21 13:30 UTC, eddiejames commented
> 

Hi, thanks for your quick response. As far as I understand, vcpkg doesn't allow any executables to be packaged, so I had to remove them after the build step in the vcpkg configuration for binlog. @JonLiu1993 is my understanding correct here?

2022-09-22 01:48 UTC, JonLiu1993 commented
> > hi (binlog author here), thanks for the new port! What's the root cause of the error? Is the bread.exe install path wrong somehow? I'd rather have a fix here, so the vcpkg install is complete, if possible, otherwise the users will have an incomplete distribution, forced to recompile some parts on demand when eventually needed.
> 
> Hi, thanks for your quick response. As far as I understand, vcpkg doesn't allow any executables to be packaged, so I had to remove them after the build step in the vcpkg configuration for binlog. @JonLiu1993 is my understanding correct here?

@eddiejames, Yes, we should remove remove `*.exe `after the build step in the vcpkg configuration.

2022-09-22 02:51 UTC, dg0yt commented
> Yes, we should remove remove `*.exe `after the build step in the vcpkg configuration.

No, removal *after* build is just the last resort to get rid of large binaries. It wastes build time, and it creates problems with exported config, as reported above.
The preferred way is to control the build of executables via a CMake option, which can be mapped to an optional features.
And extra care is needed with the CMake config for tools which must run on the *host*, not target.

2022-09-22 07:00 UTC, erenon commented
I agree that building something just to remove it afterwards is incorrect. binlog cmake can be changed to optionally avoid building/install binaries.

However: binlog produces binary logfiles, that can be converted to text using `bread` (bread.exe above). If binaries get removed, what's the proposed use workflow? How is the user going to read the logfiles? Will the user build `bread` separately? Isn't that a bit unconvenient? Doesn't vcpkg support building/installing tools?

2022-09-22 07:09 UTC, dg0yt commented
> However: binlog produces binary logfiles, that can be converted to text using `bread` (bread.exe above). If binaries get removed, what's the proposed use workflow? How is the user going to read the logfiles? Will the user build `bread` separately? Isn't that a bit unconvenient? Doesn't vcpkg support building/installing tools?

The tools can be requested via a port "feature". I hope the log files are portable, so I can use my x64-linux tools to convert arm-android log files, and don't need arm-android `bread`?

2022-09-22 07:46 UTC, erenon commented
Strictly speaking, they are not portable, however, in practice, they are, as long as the different platforms use the same endianness  and floating point representation. (rationale: https://binlog.org/Mserialize.html#overview)

2022-10-28 08:52 UTC, JonLiu1993 commented
Draft this PR since it seems that no progress is being made.

2023-01-06 15:16 UTC, erenon commented
The referenced PR that blocked this was merged, please re-open this. Thanks!

2023-02-06 10:03 UTC, JonLiu1993 commented
Pinging @eddiejames for response. Is work still being done for this PR?

2023-02-08 07:05 UTC, JonLiu1993 commented
@eddiejames, Please let me know if this PR is ready for review, Thanks.

2023-02-08 14:38 UTC, eddiejames commented
> @eddiejames, Please let me know if this PR is ready for review, Thanks.

Yes it is.

2023-02-09 07:58 UTC, JonLiu1993 requested changes

2023-02-09 07:58 UTC, JonLiu1993 commented on ports/binlog/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
```

2023-02-09 07:58 UTC, JonLiu1993 commented on ports/binlog/portfile.cmake
> +
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2023-02-09 08:08 UTC, JonLiu1993 commented
Tetsed usage by binlog:x64-windows triplet successfully:
````
    # this is heuristically generated, and may not be correct
    find_package(binlog CONFIG REQUIRED)
    target_link_libraries(main PRIVATE binlog::binlog binlog::headers)
````

2023-02-10 06:04 UTC, JonLiu1993 approved these changes

2023-02-10 19:37 UTC, merged