[vlpp] Fix configure issues, export unofficial target
microsoft/vcpkg pull request #26887
Opened 2022-09-20 06:59 UTC by JackBoosY

This PR is trying to fix the configure issues in vcpkg.

Related: https://github.com/vczh-libraries/Release/pull/13

2022-09-20 06:59 UTC, JackBoosY commented
cc @vczh

2022-09-20 07:06 UTC, JackBoosY commented
I saw https://github.com/vczh-libraries/Release/tree/master/Import has many source files, but I don't know what files should be corresponding to the features.
I looked up the documentation but couldn't find instructions.

2022-09-20 07:15 UTC, dg0yt reviewed
Is there a public record of the actual problems?

2022-09-20 07:15 UTC, dg0yt commented on ports/vlpp/CMakeLists.txt
> +add_library(Vlpp INTERFACE ${SRCS})
I don't understand what you expect to gain from an `INTERFACE` library.

2022-09-20 07:17 UTC, JackBoosY commented on ports/vlpp/CMakeLists.txt
> +add_library(Vlpp INTERFACE ${SRCS})
https://github.com/vczh-libraries/Release#content-of-this-project
```md
Import Gaclib source code
```

2022-09-20 07:20 UTC, JackBoosY commented
> Is there a public record of the actual problems?

Trying to have communication in Teams internal.

2022-09-20 07:34 UTC, dg0yt commented on ports/vlpp/CMakeLists.txt
> +add_library(Vlpp INTERFACE ${SRCS})
This is from "Content of this project", i.e. explaining what you find in `Import`. It is not a usage instruction.

2022-09-20 07:36 UTC, dg0yt commented on ports/vlpp/CMakeLists.txt
> +add_library(Vlpp INTERFACE ${SRCS})
BTW the content also lists "Tools". Maybe the port needs to install tools for native triplets, in order to be useful?

2022-09-20 07:39 UTC, JackBoosY commented on ports/vlpp/CMakeLists.txt
> +add_library(Vlpp INTERFACE ${SRCS})
> This is from "Content of this project", i.e. explaining what you find in `Import`. It is not a usage instruction.

This need to confirm with the author.


> BTW the content also lists "Tools". Maybe the port needs to install tools for native triplets, in order to be useful?

Also should do that.

2022-09-22 09:30 UTC, JackBoosY commented
arm64: 
```
D:\buildtrees\vlpp\src\89147234d4-66da526de7.clean\Import\VlppOS.Windows.cpp(1782): error C3861: '_mm_pause': identifier not found
```

x64-osx:
```
/Users/vagrant/Data/buildtrees/vlpp/src/89147234d4-66da526de7.clean/Import/VlppOS.Linux.cpp:51:17: error: use of undeclared identifier 'PATH_MAX'
                                char buffer[PATH_MAX] = { 0 };
                                            ^
/Users/vagrant/Data/buildtrees/vlpp/src/89147234d4-66da526de7.clean/Import/VlppOS.Linux.cpp:52:20: error: use of undeclared identifier 'PATH_MAX'
```

x64-linux:
```
/mnt/vcpkg-ci/buildtrees/vlpp/src/89147234d4-66da526de7.clean/Import/VlppOS.Linux.cpp:1539:20: error: ‘_mm_pause’ was not declared in this scope
 1539 |    while(token!=0) _mm_pause();
      |                    ^~~~~~~~~
```

2022-09-22 09:56 UTC, JackBoosY commented
@vczh any ideas on the regressions?

2022-09-22 10:46 UTC, dg0yt commented on ports/vlpp/fix-arm.patch
>   #include <stdint.h>
The removal of this include is probably the reason for loosing `_mm_pause`. As an alternative, you may perhaps use `<immintrin.h>`.

2022-09-22 10:46 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +    vcpkg_copy_tools(TOOL_NAMES GacGen)
No `AUTO_CLEAN`?

2022-09-22 10:46 UTC, dg0yt commented on ports/vlpp/vcpkg.json
> +      "description": "Use DarkSkin"
Is this an *additive* feature?

2022-09-23 02:38 UTC, JackBoosY commented on ports/vlpp/vcpkg.json
> +      "description": "Use DarkSkin"
Yes.

2022-09-23 03:06 UTC, JackBoosY commented on ports/vlpp/fix-arm.patch
>   #include <stdint.h>
According to official doc: https://learn.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=msvc-170
Only include `intrin.h` should be okay.

2022-09-23 05:06 UTC, dg0yt commented on ports/vlpp/fix-arm.patch
>   #include <stdint.h>
MSVC documentation is not relevant here. `<x86intrin.h>` is removed from the `#elif defined VCZH_GCC` section.

2022-09-23 05:42 UTC, vczh commented on ports/vlpp/CMakeLists.txt
> +    Import/VlppGlrParser.h
The dependency is not right. Here is what I suggests:

Core:
- Core: `Vlpp` / `VlppOS` / `VlppRegex`
  - For Windows: `Vlpp.Windows` / `VlppOS.Windows`
  - For others: `Vlpp.Linux` / `VlppOS.Linux`
- Reflection: **Core** & `VlppReflection` (This file is needed even when VCZH_DEBUG_NO_REFLECTION is on)
- GlrParser: **Core** & **Reflection** & / `VlppGlrParser`

Workflow
- WfLibrary depends on `VlppReflection`
- WfRuntime depends on **WfLibrary**
- WfCompiler depends on **WfRuntime**

GacUI:
- GacUICore: **GlrParser** & **WfLibrary** & `GacUI` / `Skins/DarkSkin/DarkSkin`
  - For Windows: `GacUI.Windows`
- GacUIReflection: **GacUICore** & **WfRuntime** & `GacUIReflection` / `Skins/DarkSkin/DarkSkinReflection`
- GacUICompiler: **GacUIReflection** & **WfCompiler** & `GacUICompiler`

2022-09-23 06:52 UTC, vczh commented on ports/vlpp/fix-arm.patch
>   #include <stdint.h>
in `VCZH_GCC`, which means the code is not in Windows (That's not a good name and I am going to rename them but just not now), includes x86intrin.h, which should include xmmintrin.h internally. I did tried it in my local ubuntu computer but I didn't see the error. I guess the error must be from a different reason.

2022-09-23 07:33 UTC, dg0yt commented on ports/vlpp/fix-arm.patch
>   #include <stdint.h>
> x86intrin.h, which should include xmmintrin.h internally

This is the arm patch. I wouldn't expect an `x86` file to include `arm` stuff. And I proposed  `immintrin.h`, not  `xmmintrin.h`.

2022-09-23 21:47 UTC, vczh commented on ports/vlpp/fix-arm.patch
>   #include <stdint.h>
Hi, @dg0yt I think the patch is updated and could be just deleted in this version. By the way,  is `immintrin.h` good for `__atomic_add_fetch`, `__atomic_sub_fetch` and `__yield` (which I believe is going to replace `_mm_pause` in x86)? I don't have any arm device so I cannot do the experiment by myself.

2022-09-28 05:53 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +        SOURCE_PATH "${GACGEN_SOURCE_PATH}"
Please avoid multiple cmake builds in a single portfile. It increases build time (compiler detection is slow), and it will overwrite log files.

2022-09-28 09:17 UTC, JackBoosY commented on ports/vlpp/portfile.cmake
> +        SOURCE_PATH "${GACGEN_SOURCE_PATH}"
> It increases build time (compiler detection is slow)

It's depends on a feature.

> and it will overwrite log files.

Fixed.

2022-10-08 10:00 UTC, vczh approved these changes, later dismissed

2022-10-10 06:25 UTC, JackBoosY commented
Waiting for internal discuss result.

2022-10-11 06:16 UTC, MonicaLiu0311 submitted a review, later dismissed

2022-10-11 06:53 UTC, dg0yt requested changes

2022-10-11 06:53 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +    )
According to the licensing information given in the vczh repositories, we must not use these repositories for building software. Cf. 
https://github.com/vczh-libraries/GacUI#gacui 
https://github.com/vczh-libraries/Workflow#gacui 
https://github.com/vczh-libraries/License#license-for-dev-repos
CC @vczh

2022-10-11 06:53 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
I don't think this file is useful: 
https://github.com/vczh-libraries/Release/blob/master/LICENSE.md

We probably need 
https://github.com/vczh-libraries/License/blob/master/README.md#license-for-release-repos

2022-10-11 06:53 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +    vcpkg_cmake_install()
I keep repeating that we want an single CMake project. I think it can be done from a trivial top-level `CMakeLists.txt`.

2022-10-11 07:22 UTC, JackBoosY commented on ports/vlpp/portfile.cmake
> +    vcpkg_cmake_install()
> I think it can be done from a trivial top-level `CMakeLists.txt`.

Further information?

2022-10-11 07:51 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +    vcpkg_cmake_install()
Sketch:
~~~cmake
project(magic)
add_subdirectory(release-repo)
if(BUILD_TOOLS)
    add_subdirectory(first-tool-repo)
    add_subdirectory(second-tool-repo)
endif()

2022-10-12 06:07 UTC, vczh commented on ports/vlpp/portfile.cmake
> +    )
@dg0yt When I make the license I was intended to let people use only sources and tools in `Release` repo, it integrates sources and executables from other repos, so that different repos are allowed to be in different on-going developing progress, and sources in `Release` are always tested and synchronized.

I think @JackBoosY pull sources from `Workflow` and `GacUI` simply because unsigned executables are not allowed to be downloaded to end-users' computers directly via vcpkg (if I understand the situation correctly), meanwhile sources are not in `Release` since I don't expect people to rely on CLI code.

But since vcpkg pulls the source code only to build these executables in end-users'. I am not an expert to this license, do you think the license allow it or not?

2022-10-12 06:20 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +    )
IANAL, but this is what I read:

https://github.com/vczh-libraries/GacUI#gacui 
> - The release of the GacUI project is put in [vczh-libraries/Release](https://github.com/vczh-libraries/Release).
> -  DO NOT download source code from this repo if you are not intended to create pull request. This is not for end users.

etc.

2022-10-12 07:31 UTC, vczh commented on ports/vlpp/portfile.cmake
> +    )
@dg0yt I changed the wording in project readmes and license.

2022-10-13 04:09 UTC, JackBoosY commented
Will request review again after header path issues are fixed by merge the upstream PR https://github.com/vczh-libraries/GacUI/pull/85 and https://github.com/vczh-libraries/Workflow/pull/4.

2022-10-17 03:00 UTC, MonicaLiu0311 approved these changes

2022-10-17 03:54 UTC, dg0yt commented on ports/vlpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
Is there any reason to build the debug variant if every binary debug artifact is removed in the end?

2022-10-17 03:54 UTC, merged

2022-10-17 07:43 UTC, JackBoosY commented on ports/vlpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
It's converted to header only.