[jsonnet][opentelemetry-cpp] Remove `!(windows & !static)`
microsoft/vcpkg pull request #26953
Opened 2022-09-23 17:36 UTC by Thomas1664

**Describe the pull request**

- #### What does your PR fix?
  Fixes #25149
  See the linked issue for more information

2022-09-23 18:48 UTC, dg0yt requested changes

2022-09-23 18:48 UTC, dg0yt commented on ports/jsonnet/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic" OR NOT VCPKG_TARGET_IS_WINDOWS)
IMO `vcpkg_check_linkage` should be used explicity, so that all maintainer function can also get the information if needed.

2022-09-23 18:48 UTC, dg0yt commented on ports/jsonnet/portfile.cmake
>  else()
In many port updates, this rewritten using `string(COMPARE EQUAL ...)`.

2022-09-23 18:48 UTC, dg0yt commented on ports/opentelemetry-cpp/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT}")
IMO we should use `${PORT}` only for destinations, but not for names chosen by the package.

2022-09-23 18:48 UTC, dg0yt commented on ports/opentelemetry-cpp/vcpkg.json
> +      "supports": "!linux & !osx"
If it supports neither linux nor osx, it probably also doesn't support android, ios, freebsd,... 
Read: it `"supports": "windows"`.
Well, it is "Event Tracing for Windows":
https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/etw

2022-09-23 19:19 UTC, Thomas1664 commented on ports/jsonnet/portfile.cmake
>  else()
Thanks! I didn't see this one!

2022-09-23 19:19 UTC, Thomas1664 commented on ports/opentelemetry-cpp/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT}")
Good point!

2022-09-23 19:30 UTC, Thomas1664 commented on ports/jsonnet/portfile.cmake
> +if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic" OR NOT VCPKG_TARGET_IS_WINDOWS)
Agreed!

2022-09-26 18:35 UTC, merged

2022-09-27 12:57 UTC, Tradias commented on ports/opentelemetry-cpp/vcpkg.json
> +      "supports": "windows"
https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json does not know about the property `"supports"`.

2022-09-27 21:46 UTC, Thomas1664 commented on ports/opentelemetry-cpp/vcpkg.json
> +      "supports": "windows"
I already opened an issue: #26952