[rapidfuzz] new port
microsoft/vcpkg pull request #27133
Opened 2022-10-07 13:40 UTC by quyykk

- #### What does your PR fix?

It adds a new port, rapidfuzz.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

It is a header-only library, so it should support all.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

yeah

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

yes

2022-10-08 06:53 UTC, Adela0814 requested changes

2022-10-08 06:53 UTC, Adela0814 commented on ports/rapidfuzz/vcpkg.json
> +  "version-semver": "1.8.0",
Can you explain why there is 'version-semver' instead of 'version'?

2022-10-08 08:59 UTC, quyykk commented on ports/rapidfuzz/vcpkg.json
> +  "version-semver": "1.8.0",
The port seems to follow semver, so it seemed logical to use `version-semver`.

2022-10-08 10:12 UTC, Adela0814 commented on ports/rapidfuzz/vcpkg.json
> +  "version-semver": "1.8.0",
In fact, I didn't find the relevant instructions in the source, can you point it out? Thanks.

2022-10-08 10:15 UTC, quyykk commented on ports/rapidfuzz/vcpkg.json
> +  "version-semver": "1.8.0",
I'm not quite sure I understand what you mean. Could you clarify? Thanks!

2022-10-08 10:22 UTC, Adela0814 commented on ports/rapidfuzz/vcpkg.json
> +  "version-semver": "1.8.0",
Why do you think this follows semver? Is there any document upstream? I can't find it.

2022-10-08 10:25 UTC, quyykk commented on ports/rapidfuzz/vcpkg.json
> +  "version-semver": "1.8.0",
Oh I'm just assuming this follows semver; I also didn't find anything upstream. Now that you say that, I realize that this is a bit dumb. I'll change it to `version`.

2022-10-09 05:38 UTC, Adela0814 approved these changes

2022-10-09 21:00 UTC, merged