[skia] Fix build for release-only triplets
microsoft/vcpkg pull request #27196
Opened 2022-10-12 09:45 UTC by Chlumsky

- #### What does your PR fix?
  Fixes the Skia package build for release-only triplets such as `x64-linux-release`.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Release-only triplets in addittion to those that were supported previously. No, I did not.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Probably.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Sure, but what is it supposed to do? It doesn't do anything.

2022-10-13 02:10 UTC, FrankXie05 approved these changes

2022-10-13 04:07 UTC, dg0yt requested changes

2022-10-13 04:07 UTC, dg0yt commented on ports/skia/portfile.cmake
> +    if(NOT VCPKG_BUILD_TYPE STREQUAL release)
Please just use `if(NOT VCPKG_BUILD_TYPE)`. It indicates that both release and debug are being built.

2022-10-13 04:07 UTC, dg0yt commented on ports/skia/portfile.cmake
Unneeded. The variant named "release" is always built.

2022-10-13 08:40 UTC, Chlumsky commented
I respectfully disagree with the changes proposed by @dg0yt. My version is both much more clear and more future-proof. Yes, I read in the documentation that `VCPKG_BUILD_TYPE` can be either `release` or empty. But it is *not* called `VCPKG_BUILD_RELEASE_ONLY` (which is a design flaw on your part), so just `if(NOT VCPKG_BUILD_TYPE)` (meaning not release-only) is extremely confusing, and if someone in the future decides that the variable can have other values (nothing is set in stone), my version would still work, but not the proposed one. (Same argument for the claim that release version is always built.)

2022-10-27 10:46 UTC, Chlumsky commented
@dg0yt Could this please be merged? It would reduce the size of our Docker images by like 75%...

2022-11-04 17:46 UTC, Chlumsky commented
Kind of ironic to put "requires author response" on this even though the author is actually the only one responding...

2022-11-07 02:28 UTC, FrankXie05 submitted a review, later dismissed

2022-11-07 23:24 UTC, BillyONeal approved these changes

2022-11-07 23:42 UTC, merged

2022-11-07 23:42 UTC, BillyONeal commented
Thanks!