X Window Part 9/N (some xcb ports)
microsoft/vcpkg pull request #27240
Opened 2022-10-14 20:14 UTC by Neumann-A

2022-10-18 05:50 UTC, Adela0814 submitted a review, later dismissed

2022-10-20 01:46 UTC, BillyONeal requested changes
Just a couple of nitpicks and questions, overall this looks good, thanks!


xcb-errors xcb-image xcb-keysyms xcb-util xcb-wm

New port checklist:
* Review the code  ⚠️⚠️⚠️⚠️⚠️
* Check the name against https://repology.org/  ❗✅✅✅❗
Should xcb-errors be xcb-util-errors ? https://repology.org/project/xcb-util-errors/versions
Should xcb-wm be xcb-util-wm ? https://repology.org/project/xcb-util-wm/versions

* Check the name against Bing/Google. (If the first results aren't C++ related, try "name C++") Skipped.
* Check the source code for optional `find_package`s None are CMake. ✅
* Check that the versioning scheme matches what upstream says ✅✅✅✅✅
* Check that the license in vcpkg.json matches what upstream says ✅✅✅✅✅
* Check that the license installed by the port matches what upstream says ✅⚠️✅✅✅
* Check that the source code comes from the upstream project's authoritative source. ✅✅✅✅✅
* Check that the generated usage is accurate. No usage. ✅
* Check for issues that are resolved. ✅✅✅✅✅ (No hits for "xcb")

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-image/add_return_value.patch
> ++  return -1;
Should this [__fastfail](https://learn.microsoft.com/en-us/cpp/intrinsics/fastfail?view=msvc-170) or _Exit or similar instead?

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-util/ssize.patch
> ++#ifndef ssize_t
Similarly, is it possible to just use ptrdiff_t instead or is this used all over the place?

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-errors/portfile.cmake
> + configure_file("${SOURCE_PATH}/COPYING" "${CURRENT_PACKAGES_DIR}/share/xcb-errors/copyright" COPYONLY)
```suggestion
file(INSTALL "${SOURCE_PATH}/COPYING" "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-image/portfile.cmake
> +file(TOUCH "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright") #already installed by xproto
There is a COPYING file, should we use it? https://gitlab.freedesktop.org/xorg/lib/libxcb-image/-/blob/master/COPYING

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-keysyms/portfile.cmake
> +# Handle copyright
```suggestion
```

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-util/portfile.cmake
> +# Handle copyright
```suggestion
```

2022-10-20 01:46 UTC, BillyONeal commented on ports/xcb-wm/portfile.cmake
> +file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/share/${PORT}/")
```suggestion
```

2022-10-20 06:59 UTC, Neumann-A commented on ports/xcb-image/portfile.cmake
> +file(TOUCH "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright") #already installed by xproto
The problem is that it is not in REF d882052fb2ce439c6483fce944ba8f16f7294639  it was added later. But today 0.4.1 was released so I probably can just bump the port version now.

2022-10-20 07:01 UTC, Neumann-A commented on ports/xcb-errors/portfile.cmake
> +# # Handle copyright
```suggestion
```

2022-10-20 07:04 UTC, Neumann-A commented on ports/xcb-image/add_return_value.patch
> ++  return -1;
```suggestion
+  exit(EXIT_FAILURE);
+  return -1;
```

2022-10-20 07:19 UTC, Neumann-A commented on ports/xcb-util/ssize.patch
> ++#ifndef ssize_t
No its just here.

2022-10-20 08:12 UTC, Neumann-A commented
Should xcb-errors be xcb-util-errors ? https://repology.org/project/xcb-util-errors/versions
Should xcb-wm be xcb-util-wm ? https://repology.org/project/xcb-util-wm/versions

there doesn't seem to be a consistent naming for these. The repos are `libxcb-errors` / `libxcb-wm`. On Cygwin is split up into the two sub libs (iccm,ewmh) in `libxcb-wm`.

The pc file for xcb-errors is https://gitlab.freedesktop.org/xorg/lib/libxcb-errors/-/blob/master/xcb-errors.pc.in

2022-10-20 08:15 UTC, Neumann-A commented on ports/xcb-errors/fix_python.patch
> ++for input_file in glob.glob(sys.argv[2]):
I could make the patch conditional on windows but I didn't see a reason to do so since the patch makes it simply work on all platforms.

2022-10-20 08:19 UTC, Neumann-A commented on ports/xcb-image/add_return_value.patch
> ++  return -1;
https://gitlab.freedesktop.org/xorg/lib/libxcb-image/-/blob/master/image/xcb_bitops.h#L201-L210. I don't think it is logically possible to reach that part of the code but I added a `exit(EXIT_FAILURE);` to the code for you.

2022-10-20 19:27 UTC, BillyONeal commented on ports/xcb-image/portfile.cmake
> +file(TOUCH "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright") #already installed by xproto
![image](https://user-images.githubusercontent.com/1544943/197039831-12dc84d8-52c7-4a3d-9074-720ade511304.png)

I left the comment specifically due to this being from 8 years ago.

It's also present in 0.4.0, which this claims to be: https://gitlab.freedesktop.org/xorg/lib/libxcb-image/-/blob/0.4.0/COPYING

2022-10-20 19:32 UTC, Neumann-A commented on ports/xcb-image/portfile.cmake
> +file(TOUCH "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright") #already installed by xproto
Hmm maybe I mixed it up. One of the x ports had the COPYING added after the release tag I thought it was this one. However updated to 0.4.1 and now installing this file any way ;)

2022-10-21 10:16 UTC, Neumann-A commented on ports/xcb-errors/fix_python.patch
> ++for input_file in glob.glob(sys.argv[2]):
retested and the patch on linux breaks stuff so i made it windows only as suggested.

2022-10-24 13:11 UTC, Neumann-A commented
@Adela0814 Please remove `requires:author-response`.

2022-10-26 04:23 UTC, BillyONeal commented on ports/xcb-image/add_return_value.patch
> ++  return -1;
I agree but when the impossible happens, death is always preferrable to "just keep running I guess :)"

2022-10-26 04:25 UTC, BillyONeal approved these changes
Thanks! <3

2022-10-26 04:25 UTC, merged