[docs] Migrate docs/users/buildsystems/export-command.md to docs/commands/export.md
microsoft/vcpkg pull request #27309
Opened 2022-10-18 20:39 UTC by ras0219-msft

2022-10-18 20:42 UTC, BillyONeal commented on docs/commands/export.md
> +Officially supported SDK formats:
This is missing Chocolatey, Prefab, and "ifw"

2022-10-18 20:44 UTC, BillyONeal commented
(I also don't know what `--dry-run` is supposed to mean, even looking at the code)

2022-10-18 21:03 UTC, BillyONeal commented on docs/commands/export.md
> +Officially supported SDK formats:
I think we can at least have 10'000 foot view "these are the switches" included herein without necessarily documenting the innards of the package format as would be required by such a work item.

2022-10-19 07:05 UTC, LilyWangLL requested changes

2022-11-04 02:19 UTC, LilyWangLL submitted a review, later dismissed

2022-11-08 23:36 UTC, BillyONeal approved these changes
I checked that all of the switches are here now.

2022-11-09 02:08 UTC, LilyWangLL approved these changes

2022-11-09 18:53 UTC, AugP reviewed
Added some comments.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +`export` must be used from Classic Mode. [Manifest Mode](../users/manifests.md) is unsupported.
IMO we should avoid using the terms "Classic Mode" and "Manifest Mode" in our docs. It can easily confuse users. Just say something like "export does not work for projects using vcpkg manifests."

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +See also:
Instead of "See also", I think it is clearer to say "Available options:" or something to that effect.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +See also:
Same as above. Instead of "See also", I think it is clearer to say "Available options:" or something to that effect.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +See also:
Same as above. Instead of "See also", I think it is clearer to say "Available options:" or something to that effect.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +See also:
Same as above. Instead of "See also", I think it is clearer to say "Available options:" or something to that effect.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +Specifies the output description for [NuGet](#nuget) nupkgs.
Suggest rephrasing "for NuGet nupkgs" to "for NuGet .nupkg files."

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +Defaults to "Vcpkg NuGet export".
Is the uppercase "Vcpkg" here important since this is a user-visible setting? We should consider making everything lowercase in the future to match our marketing naming rules. However, the docs need to refer to the current state of the product, so if it does actually make it uppercase, this can be left alone.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +Specifies the output id for [NuGet](#nuget) nupkgs.
Suggest rephrasing "for NuGet nupkgs" to "for NuGet .nupkg files."

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +Specifies the output version for [NuGet](#nuget) nupkgs.
Suggest rephrasing "for NuGet nupkgs" to "for NuGet .nupkg files."

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +GroupId uniquely identifies your project according to maven specifications.
Maven should be uppercase (at least that seems to be the naming convention I am seeing online).

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +Enable maven.
Maven should be uppercase.

2022-11-09 18:53 UTC, AugP commented on docs/commands/export.md
> +Version is the version of the project according to maven specifications.
Maven should be uppercase.

2023-01-31 22:30 UTC, closed without merging

2023-01-31 22:34 UTC, ras0219-msft commented on docs/commands/export.md
> +Defaults to "Vcpkg NuGet export".
Yes, the product currently produces the string as uppercased.