[libcanberra] Control dependencies
microsoft/vcpkg pull request #27314
Opened 2022-10-19 05:59 UTC by dg0yt

Pulled out and extended from #27217.

- #### What does your PR fix?
  Fixes tldl lookup and export.
  Fixes dependency control via features.
  Enables mingw.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all but non-mingw windows, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-10-19 06:46 UTC, LilyWangLL commented
The CI pipeline error on x64-osx:
```
rm: conftest.dSYM: is a directory
configure: error: Unable to find libltdl.
```

2022-10-21 03:20 UTC, LilyWangLL requested changes

2022-10-21 03:20 UTC, LilyWangLL commented on ports/libcanberra/portfile.cmake
> -set(VERSION 0.30)
This can't be removed. `vcpkg_download_distfile` need `VERSION`.

2022-10-21 03:20 UTC, LilyWangLL commented on ports/libcanberra/portfile.cmake
>      OUT_SOURCE_PATH SOURCE_PATH
[`vcpkg_extract_source_archive_ex`](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_extract_source_archive_ex.md) has been deprecated in favor of [vcpkg_extract_source_archive()](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_extract_source_archive.md).

2022-10-21 04:57 UTC, dg0yt commented on ports/libcanberra/portfile.cmake
> -set(VERSION 0.30)
So how does CI work?
It can be removed, vcpkg tool does set it now.
(This PR doesn't include the related bootstrap update, but CI builds merges with master.)

2022-10-21 04:57 UTC, dg0yt commented on ports/libcanberra/portfile.cmake
>      OUT_SOURCE_PATH SOURCE_PATH
So someone should add this to the automated PR checks for deprecated functions...

2022-10-21 09:20 UTC, LilyWangLL commented on ports/libcanberra/portfile.cmake
> -set(VERSION 0.30)
The CI log:
```
Installing 90/94 libcanberra:x64-linux...
Building libcanberra[alsa,core,defaults]:x64-linux...
libcanberra currently requires the following libraries from the system package manager:
    automake
    libtool
    ltdl-dev

They can be installed with apt-get install automake libtool ltdl-dev
-- Using cached libcanberra-0.30.tar.xz.
-- Extracting source /mnt/vcpkg-ci/downloads/libcanberra-0.30.tar.xz
```
It use the cache, I test this issue locally, the `${VERSION}` doesn't work, its value is empty.
cc @autoantwort

2022-10-21 10:26 UTC, dg0yt commented on ports/libcanberra/portfile.cmake
> -set(VERSION 0.30)
Note that I did merge master with the last push. You must re-do bootstrap. It is tested locally and in CI.

2022-10-24 08:25 UTC, LilyWangLL commented on ports/libcanberra/portfile.cmake
> -set(VERSION 0.30)
Yeah, this issue resolved after I re-do bootstrap.

2022-10-24 09:02 UTC, LilyWangLL approved these changes

2022-10-25 00:09 UTC, merged

2022-10-25 00:09 UTC, BillyONeal commented
Thanks for the fixes!