[xalan-c] deprecate port
microsoft/vcpkg pull request #27401
Opened 2022-10-22 14:31 UTC by rleigh-codelibre

**Describe the pull request**

Deprecate the "xalan-c" port.

- #### What does your PR fix?

Xalan-C is in the process of being retired (I'm the primary upstream maintainer at Apache and have previously contributed updates and fixes to the vcpkg support for it).  It will shortly be moved to the Attic.  No future releases, bugfixes or security updates will be provided.

Mark the port as deprecated in line with how other ports have been deprecated.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

2022-10-23 12:14 UTC, Osyotr commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
qt5xmlpatterns is deprecated, saxonc is paid...
Btw why remove port? Just issue a warning in portfile

2022-10-23 13:48 UTC, rleigh-codelibre commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
The retirement of the Xalan-C project is a wholly separate concern from what other projects are or are not doing.  I have put them in the PR as suggestions for users who will be affected to consider.  You're right that the alternatives aren't necessarily good either, but the Xalan-C project is being wound up and end-users will need to consider their options.  It may well be the case that paying for SaxonC is the better choice.

With regard to deprecation, I've followed the pattern used by other projects in vcpkg.  I haven't seen any which are both marked deprecated and which are still buildable.  That doesn't appear to be possible with the current practice of putting "deprecated" into the version string, rather than having some additional metadata for that purpose.

2022-10-23 14:11 UTC, Neumann-A commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
> other projects in vcpkg

please give example projects. I also see no reason to remove the port itself.

2022-10-23 14:35 UTC, rleigh-codelibre commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
Examples: `gdcm2`, `lodepng-c`, `qt5-modularscripts`, `qtquickcontrols2`.  Two of these have a dependency on their replacement.  That's not possible to do in the case of `xalan-c`.

2022-10-23 14:46 UTC, Neumann-A commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
The examples you give have not been removed. They either have been renamed within vcpkg or been integrated into other ports. As such the libraries they represent still exist within vcpkg. (especially `qt5-modularscripts` was just an unnecessary internal vcpkg helper port)

As long as the github repo exists I don't see any real reason to remove it.

2022-10-23 14:55 UTC, rleigh-codelibre commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
If vcpkg provides a mechanism to deprecate a port while retaining the ability to build it, then please point me to an example of this and I'll be happy to update this PR to follow that example.  But if that's something which vcpkg doesn't currently cater for, then that's perhaps something the vcpkg maintainers need to provide some mechanism for.

2022-10-23 16:12 UTC, dg0yt commented on ports/xalan-c/vcpkg.json
> +  "description": "Retired port.  libxslt, qt5xmlpatterns and SaxonC are alternatives to consider.",
The version string is not suitable here: The `version-string` will not take part in version number resolution for manifest requirements. But vcpkg may need to add new patches to the current version.

2022-10-28 08:21 UTC, Cheney-W commented
Adding `reviewed` lable is just for team to further review.

2022-10-29 04:38 UTC, BillyONeal commented
If an upstream wishes to be delisted, particularly when we're talking something that is likely to be security sensitive like this, I'm inclined to do what they asked. However, that action is somewhat unprecedented, so I want other maintainers to confirm before we proceed.

2022-10-29 08:03 UTC, rleigh-codelibre commented
@BillyONeal If vcpkg provides any mechanism for continuing to allow the package to build, but at the same time marking it deprecated then I would be happy with that as an interim step before completely withdrawing it.  It looks like this isn't currently possible, so I would prefer to remove completely and mark deprecated.  If vcpkg needs to develop some support for this I'm happy to revisit if this changes.

Regarding "other maintainers", the short answer to that is that there aren't any.  I'm the only person to have done any maintenance on this project in the last 9 years, which is the primary reason it's being retired--I'm ceasing my involvement and there is not one else left who will be working on it.  However, please see [this thread](https://marc.info/?l=xalan-dev&m=166603389016762&w=2) which is the vote of the Apache PMC to retire the project.  There will be a formal announcement forthcoming as a followup, but the decision itself has been concluded and PRs like this are the followup actions I'm taking as part of winding up my responsibilities.

2022-10-29 08:48 UTC, dg0yt commented
Isn't it enough for now to put "Deprecated." at the begin of the description? (There could also be warning printed from the portfile.)

2022-10-29 08:50 UTC, dg0yt requested changes

2022-10-29 08:50 UTC, dg0yt commented on ports/xalan-c/vcpkg.json
> +  "version-string": "deprecated",
This change makes it impossible to add more patches (port versions) to 1.12.

2022-11-03 20:26 UTC, BillyONeal commented
@ras0219-msft @JavierMatosD @markle11m @vicroms @AugP @valeriaconde, and I discussed this and agree to comply with what the upstream maintainer, @rleigh-codelibre desires. The port should be deleted from ports/ and from the baseline. Customers who want to still use this can pin an older version as older versions will still be present in the versions database.

@JavierMatosD and @markle11m are weakly against this without some sort of mention in November's vcpkg blog post.

2022-11-04 00:44 UTC, ras0219-msft approved these changes

2022-11-04 00:46 UTC, ras0219-msft commented
Optionally we can delay this merge until a tool release with better removal diagnostics.

2022-11-04 21:43 UTC, BillyONeal commented
@ras0219-msft asked until next week to improve the diagnostic in the tool when we do this to merge this. Leaving it tagged reviewed to make sure we don't drop it on the floor.

2022-11-11 22:28 UTC, merged

2022-11-11 22:28 UTC, BillyONeal commented
Thank you!