[docs] document 'version' command 📃⚡🚀
microsoft/vcpkg pull request #27509
Opened 2022-10-27 18:09 UTC by valeriaconde

**Describe the pull request**

- #### What does your PR fix? 
  Documentation 😊❤😍😜

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
✌ n/a

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
obvs ✔

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
not adding a port 😢😢😢

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-10-27 22:05 UTC, vicroms requested changes

2022-10-27 22:05 UTC, vicroms commented on docs/commands/version.md
> +Displays the version of vcpkg installed.
```suggestion
Displays the version of the vcpkg executable.

```

We are not actually "installed" so I would avoid that word.

2022-10-28 16:28 UTC, ras0219-msft commented on docs/commands/version.md
> +**The latest version of this documentation is available on [GitHub](https://github.com/Microsoft/vcpkg/tree/master/docs/commands/integrate.md).**
```suggestion
**The latest version of this documentation is available on [GitHub](https://github.com/Microsoft/vcpkg/tree/master/docs/commands/version.md).**
```

2022-10-28 19:00 UTC, valeriaconde commented on docs/commands/version.md
> +**The latest version of this documentation is available on [GitHub](https://github.com/Microsoft/vcpkg/tree/master/docs/commands/integrate.md).**
Thank you 😦

2022-10-28 19:00 UTC, valeriaconde commented on docs/commands/version.md
> +Displays the version of vcpkg installed.
Thanks! 😄😄

2022-10-31 17:55 UTC, vicroms approved these changes

2022-10-31 18:20 UTC, merged