[thorvg] create a new port
microsoft/vcpkg pull request #27525
Opened 2022-10-28 10:15 UTC by luncliff

### What does your PR fix?

Resolve #23353

### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

* x64-linux
* x64-osx

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I think so.

2022-10-28 10:16 UTC, luncliff commented
CC. @rinechran

2022-10-31 06:56 UTC, JonLiu1993 requested changes, later dismissed

2022-10-31 06:56 UTC, JonLiu1993 commented on ports/thorvg/portfile.cmake
> +    HEAD_REF master
```suggestion
    HEAD_REF master
    PATCHES
        install-tools.patch
```

2022-10-31 06:57 UTC, JonLiu1993 commented on ports/thorvg/portfile.cmake
> +    HEAD_REF master
@luncliff, Thanks for your pr, this suggestion is just to make the code more standardized

2022-10-31 07:01 UTC, JonLiu1993 commented
Feature `tools` tested successfully in the x64-linux triplet

2022-11-01 00:02 UTC, BillyONeal commented
thorvg

New port checklist:
* Review the code ✅
* Check the name against https://repology.org/ ⚠️ No match
* Check the name against Bing/Google. ✅ First hit. https://www.thorvg.org/
* Check the source code for optional `find_package`s ✅ Not a CMake port
* Check that the versioning scheme matches what upstream says ✅ https://github.com/Samsung/thorvg/releases/tag/v0.8.2
* Check that the license in vcpkg.json matches what upstream says ✅ MIT 
* Check that the license installed by the port matches what upstream says ✅ https://github.com/Samsung/thorvg/blob/master/LICENSE
* Check that the source code comes from the upstream project's authoritative source. ✅
* Check that the generated usage is accurate. ✅ No usage.
* Check for issues that are resolved.

Resolves https://github.com/microsoft/vcpkg/issues/23353

Thanks for your contribution!

2022-11-01 00:02 UTC, merged