[lcms] update to version 2.14
microsoft/vcpkg pull request #27602
Opened 2022-11-02 01:41 UTC by 0xC0000054

- #### What does your PR fix?
  Updates lcms to version 2.14

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
   Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-11-02 02:11 UTC, JonLiu1993 requested changes

2022-11-02 02:11 UTC, JonLiu1993 commented on ports/lcms/vcpkg.json
>    "description": "Little CMS.",
```suggestion
  "description": "Little CMS.",
  "license": "MIT",
```

2022-11-02 02:11 UTC, JonLiu1993 commented on ports/lcms/vcpkg.json
>    "description": "Little CMS.",
https://github.com/mm2/Little-CMS/blob/master/COPYING

2022-11-02 02:11 UTC, JonLiu1993 commented on ports/lcms/vcpkg.json
>    "description": "Little CMS.",
@0xC0000054 , Thanks for your pr, please add license here.

2022-11-02 02:38 UTC, 0xC0000054 commented on ports/lcms/vcpkg.json
>    "description": "Little CMS.",
Added in commit https://github.com/microsoft/vcpkg/commit/9ae28988cf5ab4c73d3e155ba35bdf5c63547e58

2022-11-02 02:45 UTC, JonLiu1993 approved these changes, later dismissed

2022-11-02 05:54 UTC, JonLiu1993 commented
Please run command "./vcpkg x-add-version lcms --overwrite-version" and commit again.

2022-11-02 06:12 UTC, JonLiu1993 approved these changes

2022-11-04 02:29 UTC, JonLiu1993 commented
Duplicate of #27593

2022-11-04 02:29 UTC, closed without merging