[WIP] OpenCV patch rework, static triplet fixes
microsoft/vcpkg pull request #2764
Opened 2018-02-09 21:13 UTC by cenit

I open here a PR with a work in progress, hoping for other help.
Need to fix:
- [x] patchset not updated for OpenCV 3.4.0 (everything from 3.3.0 should be correctly ported over, I hope)
- [ ] random failures in opencv_contrib vgg files downloaded on the fly
- [x] static triplets not working (I modified the portfile.cmake for that but still not tested, unable to build OpenCV in any way as of now)

Still investigating on the issues, and any other that may appear as a result.
Any help is really appreciated

2018-02-10 14:11 UTC, cenit commented
I need help for the last point @alexkaratarakis @ras0219-msft

2018-02-13 03:57 UTC, lijgame commented
Thanks.
I tried this patch, it works for OpenCV[core].
OpenCV[cuda] is still broken.

But this works for me, appreciate it!

2018-02-13 20:49 UTC, cenit commented
could you please tell me more? I have a sample build project which worked ok....
I will try to work on this patch more to make it also OpenCV[ffmpeg] work ASAP...

2018-02-14 17:17 UTC, patrikhuber commented
I'm also getting multiple `Applying patch failed.` errors when installing the latest OpenCV (3.4.0) from vcpkg.

2018-02-14 17:27 UTC, patrikhuber commented
Maybe @jasjuang can help as well, he [updated from 3.3 to 3.4](https://github.com/Microsoft/vcpkg/commit/6832578fe3197f4c367f26cb98b22858fd4db6b2#diff-4fa98fbb3179d5f3752868d923d9c9aa).

2018-02-14 17:30 UTC, cenit commented
This PR fixes that problem. I am collecting problems if you have any. I will work on opencv[ffmpeg] also soon, because I need it.

2018-02-14 17:35 UTC, cenit commented
I also discussed about that patch (accepted too quickly imho) here https://github.com/Microsoft/vcpkg/issues/2762
The curated collection should avoid these problems, but it already happened more than once here with opencv, breaking suddenly the port. The idea is to test ports and not point to head of master because of that...

2018-02-14 17:49 UTC, patrikhuber commented
> I will work on opencv[ffmpeg] also soon, because I need it.

What do you mean with that - does it not work for you? I had problems with it (see #2613) but since @ras0219-msft can't reproduce them, I am just trying again now to see whether it's a local problem or one with the vcpkg port.

What do you think about #2794?

Thank you very much for your work @cenit.
OpenCV is a particularly difficult package (almost like boost ;-) ) but used quite widely, and it would be nice to have timely updates, which is one of the main points of a package manager like this. The difficulty of the package probably means it needs someone quite familiar with vcpkg (e.g. from upstream) to help maintaining it, to also make sure it doesn't break again, which I agree with you sucks :\

2018-02-14 17:54 UTC, cenit commented
It just means that I have not tested OpenCV[ffmpeg] for now, so I don't want to say that it's working without having tried it!

2018-02-14 17:59 UTC, cenit commented
I can try to exploit feature packages and extract OpenCV-contrib and protobuf, #2794 is a good idea. Unfortunately my time is really constrained now, but since I need this package working (my time spent fixing it would be much more reasonable than any time spent manually installing on many system the library) I will find some time to fix it. If you want access to my repo to contribute to it (automatically only maintainers, so MSFT's Robert and Alex, have it), please let me know so that I can add you manually

2018-02-14 20:36 UTC, patrikhuber commented
Ok, cool! Looking forward to the changes. :-) In my opinion, OpenCV-contrib should never have been part of the "default" OpenCV package in vcpkg in the first place.

Regarding ffmpeg, we solved #2613, and isolated the problem, for which I've created a new issue: #2799.

2018-02-14 22:54 UTC, jasjuang commented
One thing to point out first, in the usage `include_directories(${OpenCV_INCLUDE_DIRS})` is redundant, as `${OpenCV_LIBS}` are targets not plain library names. 

It seems that you remove the patches I did earlier, which might be the cause of the path issues that @lijgame is seeing. I will test out this PR later.

2018-02-15 01:55 UTC, ras0219-msft commented
> random failures in opencv_contrib vgg files downloaded on the fly (ninja parallel configuring was messing with downloading files on the fly, OpenCV now opts-out of this new mechanism)

If OpenCV needs more files, we should do the download ourselves and place it into the right place. In order to ensure things like proxy support / authentication / determinism, we need to have all the downloads occur as directly in the portfile as possible.

>libjpeg-turbo was found only as a debug library, creating issues when linking with CRT/CRTd (the latter always required by libjpeg, wrongly)

I'll look into this!

>the lzma dependency of libtiff was missed out, making impossible to proper linking to OpenCV.

We should have fixed this in our toolchain file [1]. Could you go into a bit more detail here about what specifically isn't working?

[1] https://github.com/Microsoft/vcpkg/blob/0d29d2fe869863640253c1486e2a83c6941d2b8a/scripts/buildsystems/vcpkg.cmake#L209-L217

2018-02-15 08:17 UTC, jasjuang commented
`vcpkg install opencv` works, but as I suspected it breaks OpenCVConfig for downstream projects because you removed my patch, I am not sure how it works for you. Below is the minimal CMakeLists to demonstrate the problem.

```
cmake_minimum_required(VERSION 3.9)

project(Example LANGUAGES CXX)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/mycpp.cpp) 

find_package(OpenCV REQUIRED)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS})
```

mycpp.cpp can be as simple as

```
int main(){
return 0;
}
```

After running cmake configuration for the downstream, the below error shows up

```
CMake Error at C:/dev/vcpkg/installed/x64-windows/share/opencv/OpenCVModules.cmake:367 (message):
  The imported target "opencv_core" references the file

     "C:/dev/vcpkg/installed/x64-windows/x64/vc15/lib/opencv_core340d.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/dev/vcpkg/installed/x64-windows/share/opencv/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows/share/opencv/OpenCVConfig.cmake:112 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:239 (_find_package)
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/jasju/Desktop/test/build/CMakeFiles/CMakeOutput.log".
```

Additionally when I tested out `vcpkg install opencv[ffmpeg]` here is the build error I am seeing.

```
-- Performing post-build validation
Detected outdated dynamic CRT in the following files:

    C:/dev/vcpkg/packages/opencv_x64-windows/debug/bin/opencv_ffmpeg340_64.dll: msvcrt.dll
    C:/dev/vcpkg/packages/opencv_x64-windows/bin/opencv_ffmpeg340_64.dll: msvcrt.dll

To inspect the dll files, use:
    dumpbin.exe /dependents mydllfile.dll
Found 1 error(s). Please correct the portfile:
    C:\dev\vcpkg\ports\opencv\portfile.cmake
```

2018-02-15 09:15 UTC, cenit commented
which patch are you talking about? I ported patches, not removed any...

2018-02-15 10:07 UTC, cenit commented
> If OpenCV needs more files, we should do the download ourselves and place it into the right place. In order to ensure things like proxy support / authentication / determinism, we need to have all the downloads occur as directly in the portfile as possible.

While I fully understand your point, the fact is that dynamic downloading of files is embedded in OpenCV CMake toolchain through the OpenCVDownload.cmake functions (available in the `cmake/` folder inside the `.tar.gz`). We can maybe prepare all the possible files inside the `opencv-cache` which is used by the script, but the port is much bigger than expected. I would like to see, first of all, a working and proper OpenCV port without dealing with proxy et al, then maybe we can concentrate on that.

> We should have fixed this in our toolchain file [1]. Could you go into a bit more detail here about what specifically isn't working?

There are some unresolved lzma symbols when using static builds of OpenCV. Maybe, since the FindTIFF is not triggered by a FindOpenCV, the toolchain script doesn't magically fix this problem?

2018-02-15 17:36 UTC, jasjuang commented
If you made changes to `OpenCV_INSTALL_BINARIES_PREFIX` then I am not sure why it's not working. I will try to test it again

2018-02-16 18:19 UTC, jasjuang commented
I just tested it again and it works. The catch is I have to delete opencv from the `buildtree` folder and do a clean extraction.

2018-02-16 21:27 UTC, jasjuang commented
I also tested `vcpkg install opencv[ffmpeg]` and can confirm that it didn't work. Below is the error

2018-02-16 23:16 UTC, cenit commented
I suspected there was something on your end that made any problem ;)
This weekend I will try to find time to work on opencv[ffmpeg]

2018-02-16 23:37 UTC, ras0219-msft commented
>Detected outdated dynamic CRT in the following files:
>
>    C:/dev/vcpkg/packages/opencv_x64-windows-dev/debug/bin/opencv_ffmpeg340_64.dll: msvcrt.dll
>    C:/dev/vcpkg/packages/opencv_x64-windows-dev/bin/opencv_ffmpeg340_64.dll: msvcrt.dll

This would be caused by removing `set(VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT enabled)`. Since the ffmpeg plugin is using precompiled binaries against msvcrt, this flag will need to be set when the feature is enabled.

2018-02-17 00:13 UTC, patrikhuber commented
I'm not sure how "severe" this outdated dynamic CRT error/warning is, and what its implications are. But doesn't allow OpenCV to build ffmpeg as part of its standard build? Like with `BUILD_FFMPEG` or some similar CMake flag?
I have no experience whether that would be a good idea or not though.

2018-02-17 17:52 UTC, maxula commented
You should add this line to portfile.cmake 

`set(VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT enabled)`

as it was done in 4d274a7bffa1cf141f3be7d227702cea44df6894

2018-02-17 23:08 UTC, cenit commented
That would rule out static builds. I am trying to use external ffmpeg, I hope to share something soon

2018-02-18 20:57 UTC, cenit commented
I am working on building OpenCV without using pre-built ffmpeg but using vcpkg's installed one.
I have already pushed my work in progress, if anyone wants to help she/he is more than welcome!
The port is becoming really big...

2018-02-18 21:54 UTC, patrikhuber commented
I really wonder what the OpenCV people's decision was to bundle ffmpeg. I guess it's the same reason they bundle libpng/libjpeg/libtiff, they wanted one self-contained package with everything. So if there is no other reason, I guess it's okay to use vcpkg's ffmpeg instead of OpenCV's.

Really appreciate your work! I saw you also added a "todo" to add pcl to featurepackages, that would be great, it's also quite a huge dependency that is not needed by most users. 👍 :-)

2018-02-19 15:34 UTC, cenit commented
@ras0219-msft @alexkaratarakis I am stuck with a problem: when a library has the same name in both debug and release, FindXXX will have a hard time distinguishing them, in particular because the debug path is appended for debug mode, and not prepended.

https://github.com/cenit/vcpkg/blob/c1d74ab97bc4da3560bc5560cfd530e087e02df3/scripts/buildsystems/vcpkg.cmake#L84-L86

2018-02-19 20:55 UTC, cenit commented
by the way, I fear that from the license point of view, a static link of software with both GPL code (ffmpeg) and BSD code (OpenCV) is not redistributable. Am I right?

2018-02-20 16:03 UTC, cenit commented
also OpenEXR is now used from vcpkg (the library did not build, I had to add some patches to it too).
Next step (already found how to fix it, hope to have time soon) is to use external Tiff library.
OpenCV now also does NOT download anything (in the [core] package) on the fly uncontrolled by vcpkg.

2018-02-20 20:05 UTC, ras0219-msft requested changes

2018-02-20 20:05 UTC, ras0219-msft commented on scripts/cmake/vcpkg_configure_cmake.cmake
>          set(NINJA_CAN_BE_USED OFF)
Please make these changes in a separate PR.

2018-02-20 20:05 UTC, ras0219-msft commented on scripts/cmake/vcpkg_configure_cmake.cmake
> +        message(STATUS "Disabling parallel configure - package has opted-out")
I don't believe being noisy here is beneficial

2018-02-20 20:05 UTC, ras0219-msft commented on scripts/cmake/vcpkg_configure_cmake.cmake
> +        if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
Please make this swap (Debug first) in a separate PR!

2018-02-20 20:17 UTC, ras0219-msft commented
I'm going to prepare a rebased branch with some of these changes I've requested

2018-02-20 20:51 UTC, cenit commented on ports/ilmbase/IexMath__CMakeLists.txt.patch
> +-TARGET_LINK_LIBRARIES(IexMath Iex)
If you use the ilmlibrary, usually you have to link to Iex and IexMath and others (as also examples do). If you link Iex library symbols into IexMath you have symbols multiply defined. Also, linking a library to another one is not a best practice.
The library of course builds perfectly also without the patch, but you cannot use it. In the original conditions any symbol of Iex not included into IexMath requires linking also to Iex, but you cannot do it because of the problem just described.

2018-02-20 20:51 UTC, cenit commented on ports/ilmbase/portfile.cmake
> +    "${CMAKE_CURRENT_LIST_DIR}/Imath__CMakeLists.txt.patch"
To remove the interlinking between libraries, which make them not working if you try to use them

2018-02-20 20:52 UTC, cenit commented on ports/ilmbase/portfile.cmake
> +endif()
ok good, I will remove it :)

2018-02-20 20:53 UTC, cenit commented on ports/opencv/FindFFMPEG.cmake
> +# Distributed under the OSI-approved BSD 3-Clause License.
I wrote all of them. I can move them wherever you need them and also relicense as you like

2018-02-20 20:54 UTC, cenit commented on ports/opencv/FindJPEG.cmake
> +# Distributed under the OSI-approved BSD 3-Clause License.
Shall you give me the proper license tag to put on the header? Also, this port is becoming huge. I think I will submit all these FindXXX.cmake modules to official cmake repository, but it will take time (as you can see, the includes are almost ready for official inclusion), so having them here in the meantime can speed up things a lot

2018-02-20 20:55 UTC, cenit commented on ports/opencv/cmake__OpenCVFindLibsGrmft.cmake.patch
> ++    include(FindWebP)
Yes it works, FindWebP.cmake is ready for REQUIRED option. But is it necessary?

2018-02-20 20:55 UTC, cenit commented on ports/opencv/cmake__OpenCVFindLibsGrmft.cmake.patch
> ++    include(FindOpenEXR)
Same as before, why having required?

2018-02-20 20:56 UTC, cenit commented on ports/openexr/IlmImfExamples__CMakeLists.txt.patch
> +diff --git a/IlmImfExamples/CMakeLists.txt b/IlmImfExamples/CMakeLists.txt
No, you are right. I was fixing also Examples and Tests, but then I gave up, it was becoming a HUGE waste of time, totally uninteresting

2018-02-20 20:56 UTC, cenit commented on ports/openexr/IlmImfFuzzTest__CMakeLists.txt.patch
> +diff --git a/IlmImfFuzzTest/CMakeLists.txt b/IlmImfFuzzTest/CMakeLists.txt
Same as before

2018-02-20 20:56 UTC, cenit commented on ports/openexr/IlmImfTest__CMakeLists.txt.patch
> +diff --git a/IlmImfTest/CMakeLists.txt b/IlmImfTest/CMakeLists.txt
Same as before, will remove in the next commit

2018-02-20 20:56 UTC, cenit commented on ports/openexr/portfile.cmake
> +endif()
ok :)

2018-02-20 20:57 UTC, cenit commented on scripts/cmake/vcpkg_configure_cmake.cmake
>          set(NINJA_CAN_BE_USED OFF)
ok

2018-02-20 20:57 UTC, cenit commented on scripts/cmake/vcpkg_configure_cmake.cmake
> +        message(STATUS "Disabling parallel configure - package has opted-out")
Right. It was necessary for me during the debug, to be sure that the correct path was chosen. Will remove!

2018-02-20 20:58 UTC, cenit commented on scripts/cmake/vcpkg_configure_cmake.cmake
> +        if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
sure!

2018-02-21 07:30 UTC, cenit commented
on my train to a conference, I implemented the external TIFF library detection fixing the LZMA dependency (it required the deployment of another couple of FindXXX.cmake modules, both for TIFF and for LibLZMA...), but now it works.
I also did some requested changes, other will come soon, unfortunately my free time is almost finished so any help is really welcome (I would like to enable also python, but I will leave it for later and another PR, this one is already too big).

I will also rewrite git history with a force push before merging, so we can have only the necessary number of commits and any trace of wrong licenses.

2018-02-22 03:11 UTC, ras0219-msft commented
Ok, I've rebased, squashed, cherry-picked, and minimized my way to a (small) victory:
https://github.com/Microsoft/vcpkg/tree/dev/roschuma/opencv-rework
https://github.com/Microsoft/vcpkg/tree/dev/roschuma/opencv-use-external-ffmpeg

I've prepared two branches: one without the ffmpeg change and one with. I think we should deliberate a bit more on what the right answer is w.r.t. the ffmpeg change (licenses as well as the upstream choices make me hesitant), however the branch without external ffmpeg LGTM.

I've also split out the various `-DCMAKE_DEBUG_SUFFIX=d` and removal of namespace changes that you had made -- I think these changes are orthogonal so they should be broken into separate PRs to minimize the number of simultaneous moving parts.

Barring bugs, I plan to merge opencv-rework soon. We can then keep working on the external ffmpeg and switching the dependencies to use debug suffixes.

2018-02-22 08:28 UTC, cenit commented
First of all, thank you for revising the patchset and for all the small enhancements along the road.

>  we should deliberate a bit more on what the right answer is w.r.t. the ffmpeg change (licenses as well as the upstream choices make me hesitant)

>  (licenses)

For the license problem, I would not give it too much weight. `vcpkg` is just a tool to give you working libraries built from sources, we should not discuss how the user wants to play with them. This is also not the only mixture that would be not redistributable. Also, why should we block custom experiments?

>  (upstream choices)

On all the other systems, `OpenCV` links to the already available `ffmpeg` and does not download custom prebuilt binaries, all without complaining. On Windows for now they redistribute `dlls` that are made inside a docker container which runs ubuntu cross-compiling to Windows [1]. May I suppose that they never found a clean way to build ffmpeg as they require it on Windows and this is the reason they download it on the fly (while all the other libraries are built from sources if missing?)
Besides bumps and obstacles along the road, `vcpkg` is really playing a huge role in restoring Windows usability for `C` and `C++` cross-platform developers and the fact that it can build `ffmpeg` with a simple command is a big testament to that. Maybe not the `ffmpeg` collaboration, but the `OpenCV` one could be interested in the toolchain that will come out of this rework :)

> I've also split out the various -DCMAKE_DEBUG_SUFFIX=d and removal of namespace changes that you had made -- I think these changes are orthogonal so they should be broken into separate PRs to minimize the number of simultaneous moving parts.
> Barring bugs, I plan to merge opencv-rework soon. We can then keep working on the external ffmpeg and switching the dependencies to use debug suffixes.

Ok let me know how to proceed in the best coordinated way. I don't want to do anything that you have already done and I am sure also the vice-versa is valid.
Let me know if I should open some small PR with the `-d` options. I will not open any PR with the removal of inter-library linking for now because it should be avoided only for static builds, not shared ones. Better fixes should be written instead of what I did.
In the meantime I will also open some PR in the `CMake` repository to trigger some updates of some FindXXXX.cmake modules. In the long time, it should ease this and other ports.

[1] https://github.com/opencv/opencv_3rdparty/tree/ffmpeg/master/ffmpeg

2018-02-22 08:36 UTC, cenit commented on ports/ilmbase/IexMath__CMakeLists.txt.patch
> +-TARGET_LINK_LIBRARIES(IexMath Iex)
Ok after more investigation, I think I should drop this patch too

2018-02-24 01:25 UTC, ras0219-msft commented
I've merged the OpenCV-rework branch to master!

> Also, why should we block custom experiments?

I am simply concerned about blocking users from using the _dynamic_ ffmpeg (which is currently the out-of-the-box experience with OpenCV on Windows/MSVC, even when building statically). However, this should still be possible with our triplets system, so I think that while changing the default is always something worth contemplating, it doesn't block us here.

>On all the other systems, OpenCV links to the already available ffmpeg and does not download custom prebuilt binaries, all without complaining. [additional solid reasoning]

That's a good argument. I'm mostly convinced, but I'll wait a bit longer for other users to potentially chime in (@jasjuang @lp55 @Mixaill @UnaNancyOwen @amincheloh @zabulus @tobiaskohlbau -- you've all contributed in the past so please chime in if you feel one way or another!).

>Ok let me know how to proceed in the best coordinated way.

I see a few things:
1. Could you test the dev/roschuma/opencv-use-external-ffmpeg and confirm it works for your scenarios? If it doesn't, either let me know or perhaps update this PR to be based off that branch plus some fixes.
2. Could you submit independent PRs for the libraries you'd like to see changed w.r.t. debug suffixes and namespaces? I want to be cautious about changing the names because I want to (as much as reasonable) support _existing_ FindXYZ.cmake scripts in the wild, such as for OpenEXR[1]. Looking at the first result from that query, it[2] actually looks like good evidence that we should remove the namespaces but _not_ add a debug suffix! OTOH, Ogre3d[3] appears to support a debug suffix without namespaces.

> Should I rework this PR in any way for merging or do you prefer to abandon it 😢 ?

Sorry for doing the separate rebase, but I didn't want to force-push-rebase over your master branch 😢. I still really appreciate what you've provided here -- it really makes up the majority of the branch I did merge! Unless you have some changes you'd like to apply on top of dev/roschuma/opencv-use-external-ffmpeg, I think it'd be best to close this PR and open new ones for any future work (also, please use separate branches when possible so I can contribute directly to them if I want simple formatting changes 😄)!

[1] https://github.com/search?utf8=%E2%9C%93&q=filename%3Afindopenexr.cmake&type=Code
[2] https://github.com/ItayGal2/nvidia-texture-tools/blob/32904e479f3d3da4d431b3023d847e0e239c6bf7/cmake/FindOpenEXR.cmake
[3] https://github.com/OGRECave/ogre/blob/06307e1963a97dbfc5871d23e613108ace9d0b93/CMake/Packages/FindOpenEXR.cmake

2018-02-24 07:56 UTC, jasjuang commented
Thanks for the work guys. I tested the builds and it works with my downstream project with both release and debug.

2018-02-24 13:25 UTC, patrikhuber commented
With the latest master branch of vcpkg, `.\vcpkg.exe install opencv[core]:x64-windows` now requires to install `opengl[core]:x64-windows`. This wasn't required before. Any reason for that?

2018-02-24 13:32 UTC, patrikhuber commented
With regards to ffmpeg, I don't have a particular opinion. If OpenCV on all other platforms is using system ffmpeg too and not the OpenCV-bundled one, then that sounds like a good reason to use vcpkg-ffmpeg on Windows too.
If you're using vcpkg libpng, tiff and jpeg also from vcpkg (it looks like that to me) and not the OpenCV-bundled one, then why not do it for ffmpeg too, this would be another argument for it.

2018-02-24 14:41 UTC, cenit commented
> Any reason for that?

`OpenCV` building triggers a `FindOpenGL` along the way, which was correctly solved because the SDK is Always checked by cmake. Having it explicitly as a dependency I think is better, so that we can keep track of what is really necessary. Installing OpenGL also is very quick, since it is just a copy of the binary libraries inside vcpkg folder.

> If you're using vcpkg libpng, tiff and jpeg also from vcpkg (it looks like that to me) and not the OpenCV-bundled one, then why not do it for ffmpeg too, this would be another argument for it.

Exactly. But I can understand that we should just let the dust settle a bit. The rework is just big enough to deserve some days to see if there's a surge of issues related to it (I am almost sure not, on the other hands many problems are now solved)

2018-02-24 15:22 UTC, closed without merging

2018-04-17 12:35 UTC, patrikhuber commented
> OpenCV building triggers a FindOpenGL along the way, which was correctly solved because the SDK path is always checked by cmake. Having it explicitly as a dependency I think is better, so that we can keep track of what is really necessary.

Just came across this again by coincidence. Strictly speaking OpenCV build does not trigger a FindOpenGL. It only triggers it when `WITH_OPENGL` (don't remember the exact option, but something like that) is set to `ON`.

Also another thing, I'm not sure which module it is but some apps that I build with OpenCV, now show some output on the command-line about OpenCL initialisation - without me ever printing something. This must be one of OpenCV's modules - and I am definitely not using OpenCL. So I am not sure but I think this output message is a bit intrusive and it's on with vcpkg's default configuration of OpenCV. I don't really want any spurious output in my apps on the command line, particularly if I'm not even using OpenCL. I'd set building OpenCV with OpenCL off by default - I am surprised that it isn't.

2018-04-18 06:12 UTC, cenit commented
in the latest patchset, I explicitly treated OpenGL as a feature (a default one, by the way), but still you can force to disable it during install.
I will look into this OpenCL issue you are seeing. Can you provide a repro?