[folly] Fix feature's find_dependency
microsoft/vcpkg pull request #27728
Opened 2022-11-09 10:14 UTC by LilyWangLL

**Describe the pull request**

- #### What does your PR fix?
  Fixes #27422, add feature option for some `find_dependency`, this is regression from PR #25335.
  cc @jiayuehua

2022-11-10 06:41 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++    find_package(ZLIB MODULE)
What's the purpose of this construction?

2022-11-10 06:41 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++    find_package(zstd CONFIG)
What's the purpose of this construction?

2022-11-10 06:41 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++    find_package(unofficial-sodium CONFIG)
What's the purpose of this construction?

2022-11-10 06:52 UTC, LilyWangLL commented on ports/folly/fix-deps.patch
> ++    find_package(ZLIB MODULE)
This dependency has been added as a feature of `folly`, so change to use option to control `find_package`. I want use this change fix the error from `fizz`:
```
CMake Error at D:/installed/x64-windows/share/folly/folly-targets.cmake:71 (set_target_properties):
  The link interface of target "Folly::folly_deps" contains:

    zstd::libzstd_shared

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

2022-11-11 06:28 UTC, dg0yt requested changes

2022-11-11 06:28 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++    find_package(ZLIB MODULE)
This either doesn't answer the question, or indicates that it is going into the wrong direction.

Briefly:
- You don't need explicit `if(CMAKE_DISABLE_FIND_PACKAGE_ZLIB)` before `find_package(ZLIB)`.
- There is no changed needed when building folly (`folly-deps-cmake`), but only when using folly (`folly-config.cmake`)

2022-11-11 06:28 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++endif()
So this is the right spot and fix.
However, I would generally recommend quotes around `@VAR@` expressions in `if` clauses, to reduce ambiguity in the generated config.

2022-11-11 07:04 UTC, LilyWangLL commented on ports/folly/fix-deps.patch
> ++    find_package(ZLIB MODULE)
`folly` has change dependencies `zlib` and `zstd` to feature. If user doesn't install `folly[zstd]`, port `zstd` will not be installed, but `folly` use `find_package(zstd CONFIG)` without `REQUIRED`. 
So `folly` can install succeed, but its downstream like `fizz` will install failed with the above error.
`zlib` is a default feature of `folly`, so I am not sure whether to add an option switch to it.

2022-11-11 07:22 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++    find_package(ZLIB MODULE)
> `folly` has change dependencies `zlib` and `zstd` to feature. If user doesn't install `folly[zstd]`, port `zstd` will not be installed, but `folly` use `find_package(zstd CONFIG)` without `REQUIRED`.

But your current patch neither adds `REQUIRED` nor `CMAKE_REQUIRE_FIND_PACKAGE_ZLIB`.

I would propose the following:
- Don't use `CMAKE_DISABLE_FIND_PACKAGE_ZLIB`. It is dangerous: It may break `find_dependency(ZLIB)` for other dependencies. (`ZLIB` is a very common dependency, and folly has many dependencies. Risk is high. IMO `CMAKE_DISABLE_FIND_PACKAGE_<Pkg>` is okay for ports without dependencies, or for unique dependencies.)
- Implement feature control with `CMAKE_REQUIRE_FIND_PACKAGE_ZLIB`.
  - It adds `REQUIRED` to `find_package(ZLIB)` without patching.
  - It doesn't have unexpected side effects on transitive `find_dependency`.
  - You can change your `if` guards to `if(CMAKE_REQUIRE_FIND_PACKAGE_ZLIB)` and  `if("@CMAKE_REQUIRE_FIND_PACKAGE_ZLIB@")`.
- (Or introduce another variable name, and add an explicit `REQUIRED` to `find_package(ZLIB)`.)

2022-11-11 09:44 UTC, LilyWangLL commented on ports/folly/fix-deps.patch
> ++    find_package(ZLIB MODULE)
Thanks for your suggestion. I changed to `CMAKE_REQUIRE_FIND_PACKAGE_ZLIB`, please review again.

2022-11-16 06:57 UTC, Cheney-W submitted a review, later dismissed

2022-11-16 07:13 UTC, dg0yt requested changes
You must actually control `CMAKE_REQUIRE_FIND_PACKAGE_ZLIB` from the portfile.

2022-11-16 07:13 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++if (NOT @CMAKE_REQUIRE_FIND_PACKAGE_ZLIB@)
Must not use `NOT` here.

2022-11-16 21:37 UTC, BillyONeal approved these changes

2022-11-16 22:04 UTC, merged

2022-11-17 08:30 UTC, BillyONeal commented
> > You must actually control `CMAKE_REQUIRE_FIND_PACKAGE_ZLIB` from the portfile.
> 
> I cannot see this was fixed.

Sigh, sorry, I dropped the ball there. I saw the comment in the files view but not the comment back here in 'conversation' view.

I super hate GitHub's code review tools sometimes :(