[botan] Use higher level maintainer functions [skip actions]
microsoft/vcpkg pull request #27750
Opened 2022-11-10 05:15 UTC by dg0yt

- #### What does your PR fix?
  Improves port maintainability.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  WIP

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

2022-11-12 03:59 UTC, dg0yt commented
uwp is now marked unsupported, because it would need patches to at least two components, and I don't want to deal with this in this PR.
- The win32 entropy component uses desktop api. It probably must be disabled, which would be a simple build system patch.
- The system RNG component has another build problem, fixed upstream for 3.0.0

So uwp should be revisited for botan 3.0.0.

2022-11-14 10:10 UTC, LilyWangLL approved these changes, later dismissed

2022-11-15 00:47 UTC, BillyONeal requested changes
This breaks `botan[zlib]` on Windows: https://github.com/randombit/botan/issues/3066

Given that it was always broken, I don't think you need to fix the broken, but it would be nice. I think it should at least replicate the old broken though.

2022-11-15 00:49 UTC, BillyONeal commented on ports/botan/configure
> +#!/bin/bash
(Sorry, to clarify, I wrote this comment when I thought I was going to merge it immediately. I am happy with the change overall except for the zlib feature being broken on Windows. Ideally upstream gives us what they want us to do?)

2022-11-16 08:45 UTC, dg0yt commented on ports/botan/configure
> +#!/bin/bash
This script is just glue between `vcpkg_configure_make`  and `configure.py`. It is a copy from what I have in the openssl non-windows PR. It becomes obsolete when there is another way to run a custom configure command in our `make` command family.

2022-11-17 13:14 UTC, dg0yt commented
The new patch doesn work for in-source builds, but this is not relevant for vcpkg.

2022-11-17 20:53 UTC, BillyONeal commented
> in-source builds

Why do people do that to themselves?! 😅

2022-11-17 22:23 UTC, dg0yt commented
And why yet another proprietary configuration system...

2022-11-18 07:22 UTC, BillyONeal approved these changes
Thanks for also fixing the zlib issue!

2022-11-18 07:22 UTC, merged