[openimageio] Update to v2.4.5.0
microsoft/vcpkg pull request #27766
Opened 2022-11-11 03:03 UTC by MonicaLiu0311

Fixes https://github.com/microsoft/vcpkg/issues/27666. 
Update version to v2.4.5.0.

2022-11-11 05:58 UTC, dg0yt requested changes
Unless there are good reasons, can you please restore the original patch structure, for the benefit of PR review and `git blame`?

2022-11-15 07:43 UTC, dg0yt requested changes
`fix-dependencies.patch`seems to have the line breaks changed.

2022-11-15 07:43 UTC, dg0yt commented on ports/openimageio/fix-dependencies.patch
> +     set (OpenColorIO_FOUND 0)
Is `OPENCOLORIO_FOUND` spelling still used? If not, we don't need to inject it.

2022-11-15 07:43 UTC, dg0yt commented on ports/openimageio/fix-dependencies.patch
> ++set(FFMPEG_INCLUDES "${FFMPEG_INCLUDE_DIRS}")
Which `FFmpeg` package is loaded now? Does it set `FFmpeg_FOUND` or `FFMPEG_FOUND`?

2022-11-15 07:43 UTC, dg0yt commented on ports/openimageio/portfile.cmake
> +		-DENABLE_INSTALL_testtex=OFF
Indent...

2022-11-15 07:43 UTC, dg0yt commented on versions/o-/openimageio.json
> +    },
No.

2022-11-22 10:25 UTC, JonLiu1993 commented on ports/openimageio/fix-dependencies.patch
> +     if (@OpenEXR_VERSION@ VERSION_GREATER_EQUAL 3.0)
fjggj

2022-12-05 02:39 UTC, JonLiu1993 requested changes

2022-12-05 02:39 UTC, JonLiu1993 commented on ports/openimageio/portfile.cmake
> +		fix-openimageio_include_dir.patch
```suggestion
        imath-version-guard.patch
	fix-openimageio_include_dir.patch
```

2022-12-07 06:18 UTC, JonLiu1993 submitted a review, later dismissed

2022-12-07 06:55 UTC, dg0yt requested changes

2022-12-07 06:55 UTC, dg0yt commented on ports/openimageio/portfile.cmake
> +    REF 1e70f7862ceca56c0d30185837ea08e765fa73db    # v2.4.5.0
Don't you want to use `v${VERSION}`?
There was an explict version tag reference before, and this PR replaces it with an commit ID. I already considered this bad practice in the past, and I just fixed another popular port where the ref didn't match the claimed version.

2022-12-07 10:12 UTC, JonLiu1993 requested changes

2022-12-07 10:12 UTC, JonLiu1993 commented on ports/openimageio/portfile.cmake
>  vcpkg_from_github(
```suggestion
vcpkg_minimum_required(VERSION 2022-10-12)
vcpkg_from_github(
```

2022-12-07 12:04 UTC, JonLiu1993 approved these changes

2022-12-14 03:15 UTC, merged