[sentry-native] Support for builds without a backend.
microsoft/vcpkg pull request #27770
Opened 2022-11-11 06:53 UTC by FrankXie05

**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/27696
  Note: Officially supports builds without a backend and adds the warning.

2022-11-11 08:02 UTC, AudriusButkevicius commented
How do you set these defines at vcpkg install time? Or does vcpkg inherit the defines from the parent project at msbuild time?

2022-11-11 09:12 UTC, FrankXie05 commented
@AudriusButkevicius I changed it to a feature. Add parameter command `./vcpkg install sentry-native[none]` to use it. :)

2022-11-11 09:16 UTC, AudriusButkevicius commented on ports/sentry-native/vcpkg.json
> +      "description": "This builds sentry-native without a backend, so it does not handle crashes at all. It is primarily used for tests."
I think the "used for tests" is wrong. Sentry is useful for other things than just tests without a backend, as I explained on my original ticket.

2022-11-11 09:42 UTC, FrankXie05 commented on ports/sentry-native/vcpkg.json
> +      "description": "This builds sentry-native without a backend, so it does not handle crashes at all. It is primarily used for tests."
I just copied the instructions from upstream. 🧐  https://github.com/getsentry/sentry-native#compile-time-options
````
none: This builds sentry-native without a backend, so it does not handle crashes at all. It is primarily used for tests.
````

2022-11-11 09:49 UTC, AudriusButkevicius commented on ports/sentry-native/vcpkg.json
> +      "description": "This builds sentry-native without a backend, so it does not handle crashes at all. It is primarily used for tests."
Sadness :/

I guess I won't argue with the people making the software, even if I disagree.

2022-11-11 10:04 UTC, FrankXie05 commented on ports/sentry-native/vcpkg.json
> +      "description": "This builds sentry-native without a backend, so it does not handle crashes at all. It is primarily used for tests."
Sorry, unless there is a good reason, I will still take the official statement. 😔

2022-11-11 10:04 UTC, AudriusButkevicius submitted a review, later dismissed

2022-11-11 12:23 UTC, dg0yt requested changes
The feature `none` is invalid because it is not additive.

What could be done is implement an opt-out feature `backend` or `default-backend` which enables the default backend for the given platform.
What must not be done is implementing alternatives via features.

2022-11-14 06:54 UTC, FrankXie05 commented
For port `sentry-native`, any platform has a default backend, but it also supports `none` (except IOS).
https://github.com/getsentry/sentry-native#compile-time-options
![image](https://user-images.githubusercontent.com/65999885/201594368-d70ef82b-2535-4393-a899-6e04060537c8.png)

2022-11-18 08:25 UTC, JonLiu1993 submitted a review, later dismissed

2022-11-18 08:27 UTC, FrankXie05 commented
The feature `none` has been tested successfully locally.

2022-11-18 08:44 UTC, dg0yt commented
> The feature `none` is invalid because it is not additive.
> 
> What could be done is implement an opt-out feature `backend` or `default-backend` which enables the default backend for the given platform. What must not be done is implementing alternatives via features.

**Please re-read immediately, remove approval/info:reviewed, and fix. **

2022-11-22 06:47 UTC, FrankXie05 commented
@dg0yt Sorry, I don't understand what you mean. What is `an opt-out feature backend` and what is its implementation logic?

2022-11-22 07:30 UTC, dg0yt commented
Default features are installed unless the user explicitly requests to not install them (aka *opt-out*). Opt-out is by requesting the pseudo-feature `core` in classic mode or specifying `"default-features": false` in manifest mode, for that package. This opt-out is blocked by any other required port which (implicitly) depends on the port's default features.

In particular, default features shall include what users commonly expect from the package when not installed with vcpkg. For example the default backend.

*Features must be additive.* If a user or port doesn't opt out from default features and relies on the resulting (default) binary feature set, it must not break if an additional feature is added. The proposed feature `none` breaks this rule by taking away the default backend.

What can be done is to add a feature `backend`, listed in `default-features`, and add this to `portfile.cmake`:
~~~cmake
vcpkg_list(SET FEATURE_OPTIONS)
if(NOT "backend" IN_LIST FEATURES)
    vcpkg_list(APPEND FEATURE_OPTIONS -DSENTRY_BACKEND=none)
    message(STATUS "This build doesn't include a backend to handle crashes. It is primarily used for tests.")
endif()
~~~

You may even add per-platform dependencies to feature `backend`.

2022-11-23 08:16 UTC, dg0yt requested changes

2022-11-23 08:16 UTC, dg0yt commented on ports/sentry-native/portfile.cmake
>          -DSENTRY_BACKEND=${SENTRY_BACKEND}
Note that my proposal was aiming at removing the explicit selection of the defautl `SENTRY_BACKEND` which is still left in lines 17-28 and used here, overwriting the effect of `FEATURE_OPTIONS`. 
If the package is smart enough to select a default backend, I don't see a need to duplicate this in the portfile.
If it needs this explicit selection, you will have to handle feature `backend` there.

2023-01-17 09:27 UTC, FrankXie05 commented on ports/sentry-native/vcpkg.json
> -  ]
Yes, I missed this.

2023-01-20 07:55 UTC, closed without merging