[trantor] Update to 1.5.8
microsoft/vcpkg pull request #27777
Opened 2022-11-11 15:51 UTC by an-tao

2022-11-14 02:22 UTC, JonLiu1993 requested changes

2022-11-14 02:22 UTC, JonLiu1993 commented on ports/trantor/portfile.cmake
> +  PATCHES)
@an-tao, thanks for your PR, could you keep the format the same as before? let's do our best to keep the code nice and spec.

2022-11-15 02:32 UTC, JonLiu1993 approved these changes

2022-11-15 05:34 UTC, merged

2022-11-15 05:34 UTC, BillyONeal commented
Thanks for the update!