[Sqlitecpp] update to 3.2.0
microsoft/vcpkg pull request #27807
Opened 2022-11-14 14:26 UTC by SvenPStarFinanz

**Describe the pull request**

- #### What does your PR fix?
  Updating Sqlitecpp to the current version.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-11-15 03:12 UTC, JonLiu1993 requested changes

2022-11-15 03:12 UTC, JonLiu1993 commented on ports/sqlitecpp/portfile.cmake
>  file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
```suggestion
file(REMOVE_RECURSE “${CURRENT_PACKAGES_DIR}/debug/include")
```

2022-11-15 03:12 UTC, JonLiu1993 commented on ports/sqlitecpp/portfile.cmake
>  file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.txt")
```

2022-11-15 03:13 UTC, JonLiu1993 commented
@SvenPStarFinanz , Thanks for your pr, could you please consider migrating them to the new functions:
````
vcpkg_install_cmake -> vcpkg_cmake_install (from port vcpkg-cmake)
vcpkg_configure_cmake -> vcpkg_cmake_configure (Please remove the option PREFER_NINJA) (from port vcpkg-cmake)
vcpkg_fixup_cmake_targets -> vcpkg_cmake_config_fixup (from port vcpkg-cmake-config)
````

2022-11-16 08:52 UTC, JonLiu1993 requested changes

2022-11-16 08:52 UTC, JonLiu1993 commented on ports/sqlitecpp/portfile.cmake
> +file(REMOVE_RECURSE “${CURRENT_PACKAGES_DIR}/debug/include")
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
```

2022-11-16 08:52 UTC, JonLiu1993 commented on ports/sqlitecpp/portfile.cmake
> +file(REMOVE_RECURSE “${CURRENT_PACKAGES_DIR}/debug/include")
Note the form of double quotes.

2022-11-16 08:52 UTC, JonLiu1993 commented on ports/sqlitecpp/portfile.cmake
> +		-DSQLITECPP_USE_STATIC_RUNTIME=OFF
```suggestion
        -DSQLITECPP_INTERNAL_SQLITE=OFF
        -DSQLITECPP_USE_STATIC_RUNTIME=OFF
```

2022-11-16 09:05 UTC, JonLiu1993 requested changes

2022-11-16 09:05 UTC, JonLiu1993 commented on ports/sqlitecpp/vcpkg.json
> +      "platform": "windows"
```suggestion
```

2022-11-16 09:17 UTC, JonLiu1993 approved these changes, later dismissed

2022-11-16 09:30 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows

2022-11-16 21:13 UTC, BillyONeal approved these changes

2022-11-16 21:20 UTC, merged

2022-11-16 21:21 UTC, BillyONeal commented
Thank you!