[avro-cpp] Update to 1.11.1
microsoft/vcpkg pull request #27825
Opened 2022-11-15 08:19 UTC by PavelKisliak

**Update 'avro-cpp' port to latest version 1.11.1**

- #### What does your PR fix?
  - Update avro-cpp to new version
  - Remove setting DEBUG option 'AVRO_ADD_PROTECTOR_FLAGS' (leading to binary incompatibility and segfault crashes)
  - Add feature for build tests
  - Remove not used dependencies
  - Update deprecated VCPKG functions
  - Add 'usage' file

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `All (only with shared linkage)`, `Yes`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

2022-11-16 02:54 UTC, MonicaLiu0311 commented on ports/avro-cpp/vcpkg.json
> +    "boost-algorithm",
```suggestion
  "homepage": "https://github.com/apache/avro",
  "license": "Apache-2.0",
  "supports": "!(windows & static)",
  "dependencies": [
    "boost-algorithm",
```

2022-11-16 02:54 UTC, MonicaLiu0311 commented on ports/avro-cpp/vcpkg.json
> +    "boost-algorithm",
A `license` is required.

2022-11-16 02:59 UTC, MonicaLiu0311 commented on ports/avro-cpp/portfile.cmake
> -    HEAD_REF master
After checking, I found that the latest upstream version is `release-1.11.1`, and the `master` is the main branch. Why delete it?

2022-11-16 06:24 UTC, PavelKisliak commented on ports/avro-cpp/portfile.cmake
> -    HEAD_REF master
Agree, it's my mistake, thank you!

2022-11-16 06:52 UTC, MonicaLiu0311 commented on ports/avro-cpp/portfile.cmake
>  )
`vcpkg` does not recommend building `tests`, and an error occurred when testing the feature. For details, see:

`./vcpkg install avro-cpp[test]`

```
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/src/27825/buildtrees/avro-cpp/x86-windows-dbg
    See logs for more information:
      E:\src\27825\buildtrees\avro-cpp\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  ports/avro-cpp/portfile.cmake:27 (vcpkg_install_cmake)
  scripts/ports.cmake:147 (include)

```
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10018850/install-x86-windows-dbg-out.log)

2022-11-16 07:17 UTC, MonicaLiu0311 commented on ports/avro-cpp/vcpkg.json
> +      ]
An error occurred when testing the feature. For details, see:

`./vcpkg install avro-cpp[test]`

```
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/src/27825/buildtrees/avro-cpp/x86-windows-dbg
    See logs for more information:
      E:\src\27825\buildtrees\avro-cpp\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  ports/avro-cpp/portfile.cmake:27 (vcpkg_install_cmake)
  scripts/ports.cmake:147 (include)
```
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10019004/install-x86-windows-dbg-out.log)

2022-11-16 12:29 UTC, PavelKisliak commented on ports/avro-cpp/vcpkg.json
> +      ]
Fixed, thank you!

2022-11-16 12:34 UTC, PavelKisliak commented
Just wondering why, there is still warning 'You have modified or added at least one portfile where deprecated functions are used.', I don't see any more deprecated functions from the list.

2022-11-18 06:23 UTC, MonicaLiu0311 commented
> Just wondering why there is still warning 'You have modified or added at least one portfile where deprecated functions are used.', I don't see any more deprecated functions from the list.

It may be this copyright function, and it will be changed next time.
`file(INSTALL "${SOURCE_PATH}/lang/c++/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)`
New functions:
`vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/lang/c++/LICENSE")`

2022-11-18 06:28 UTC, MonicaLiu0311 commented
All features are tested successfully in the following triplet:
x86-windows
x64-windows

2022-11-18 06:28 UTC, MonicaLiu0311 submitted a review, later dismissed

2022-11-18 06:54 UTC, dg0yt commented
> may be this copyright function, and it will be changed next time.
> `file(INSTALL "${SOURCE_PATH}/lang/c++/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)`
> New functions:
> `vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/lang/c++/LICENSE")`

No, this is not the reason.

2022-11-18 06:59 UTC, dg0yt requested changes

2022-11-18 06:59 UTC, dg0yt commented on ports/avro-cpp/portfile.cmake
>  vcpkg_install_cmake(ADD_BIN_TO_PATH)
With `vcpkg_cmake_configure`, you must use `vcpkg_cmake_install`. This is the trigger for the deprecation notice.

2022-11-18 06:59 UTC, dg0yt commented on ports/avro-cpp/usage
> +    target_link_libraries(main PRIVATE ${AVROCPP_LIBRARIES})
IMO you should use singular variable names with `find_path` and `find_library`, and add quotes when using them in expressions or arguments.

In addition, I'm concerned that a single `find_library` will not work well with multi-config generators (in particular with Visual Studio).

2022-11-18 07:28 UTC, MonicaLiu0311 commented on ports/avro-cpp/portfile.cmake
>  vcpkg_install_cmake(ADD_BIN_TO_PATH)
You are right, it was my carelessness.

2022-11-18 11:15 UTC, PavelKisliak commented on ports/avro-cpp/usage
> +    target_link_libraries(main PRIVATE ${AVROCPP_LIBRARIES})
Thanks, fixed!

2022-11-18 11:16 UTC, PavelKisliak commented on ports/avro-cpp/portfile.cmake
>  vcpkg_install_cmake(ADD_BIN_TO_PATH)
Thanks @dg0yt, fixed!

2022-11-18 21:07 UTC, BillyONeal commented on ports/avro-cpp/vcpkg.json
> +    "test": {
I don't think this feature should exist: vcpkg should not be building tests.

2022-11-20 07:49 UTC, PavelKisliak commented on ports/avro-cpp/vcpkg.json
> +    "test": {
I was just following official [maintainer-guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-build-testsdocsexamples-by-default), this is an optinal feature which is not build by default. I see that there are already existing a lot of ports with such feature.

2022-11-20 11:11 UTC, dg0yt commented on ports/avro-cpp/vcpkg.json
> +    "test": {
@BillyONeal IMO the recommendation needs to be "optional feature", not "this feature shouldn't exist". Given a broad usage of vcpkg ports beyond platforms tested by upstream or vcpkg CI, the lack of an easy way to run tests *on demand* is a disservice for users.

2022-11-21 02:01 UTC, MonicaLiu0311 approved these changes

2022-11-21 07:53 UTC, MonicaLiu0311 approved these changes

2022-11-21 16:51 UTC, JavierMatosD commented
Thank you

2022-11-21 16:51 UTC, merged