[openssh] Add openssh application for vcpkg
microsoft/vcpkg pull request #27843
Opened 2022-11-16 05:58 UTC by melchi45

- Add openssh version 9.1 with github potable application
- This application build on Linux

(cherry picked from commit b9a2f035f519dcc45da8cf6914a1de06f84ac8a6)

**Describe the pull request**

- #### What does your PR fix?
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-11-16 07:30 UTC, MonicaLiu0311 commented on ports/openssh/vcpkg.json
> +  "license": "BSD-3-Clause",
```suggestion
  "license": "BSD-3-Clause",
  "supports": "linux",
```

2022-11-16 07:32 UTC, MonicaLiu0311 commented on ports/openssh/vcpkg.json
> +  "license": "BSD-3-Clause",
```suggestion
  "license": "BSD-3-Clause",
  "supports": "linux",
```

>This application build on Linux

If only linux is supported, please add `supports`.

2022-11-16 07:35 UTC, MonicaLiu0311 commented on ports/openssh/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)

```

Please leave a blank line at the end of portfile.cmake and vcpkg.json.
(format requirement)

2022-11-18 10:12 UTC, MonicaLiu0311 commented on ports/openssh/portfile.cmake
> +
Replace this part with the `support` of `vcpkg.json`

2022-11-18 10:13 UTC, MonicaLiu0311 commented
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version openssh` then commit the changes.

2022-11-22 07:21 UTC, melchi45 reviewed
I was changed your suggestion.

2022-11-22 07:47 UTC, dg0yt commented
Does this port add a library or an application. If the latter, I would assume it won't be accepted.

2022-11-23 00:40 UTC, melchi45 reviewed
please check again.

2022-11-23 09:00 UTC, MonicaLiu0311 requested changes

2022-11-23 09:00 UTC, MonicaLiu0311 commented on ports/openssh/vcpkg.json
> +  "port-version": 1,
```suggestion
```

`port-verison` is what needs to be changed when vcpkg adjusts the port. It needs to be deleted when the port is added for the first time or the `"version"` is updated.

2022-11-23 09:03 UTC, MonicaLiu0311 commented
The `baseline` and `o-/openssh.json` files are missing, please refer to: [versions/](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-files-in-versions-of-any-modified-ports)

2022-11-23 09:53 UTC, melchi45 reviewed
ok, I added the version information for openssh.

2022-11-23 10:16 UTC, MonicaLiu0311 commented
> ok, I added the version information for openssh.

Please push the `baseline.json` file.

2022-11-30 02:38 UTC, melchi45 reviewed
OK. I was changed the baseline.json file for openssh.

2022-11-30 06:00 UTC, MonicaLiu0311 requested changes

2022-11-30 06:00 UTC, MonicaLiu0311 commented on versions/baseline.json
> +	"oatpp-openssh": {
```suggestion
    },
    "oatpp-openssh": {
```

2022-11-30 06:07 UTC, MonicaLiu0311 commented on versions/baseline.json
> +	"oatpp-openssh": {
Please run `./vcpkg x-add-version openssh` to generate `openssh.json` and `baseline.json`, and do not manually modify these two files.
1) The indentation format is incorrect.
2) And because of the generation problem of the `json` file, CI error was also generated：
```
##[error]Found the following errors:
    Error: While reading versions for port openssh from file: C:\a\1\s\versions\o-\openssh.json
       Version `9.1` was not found in versions file.
       Run:

           vcpkg x-add-version openssh

       to add the new port version.
To attempt to resolve all errors at once, run:
vcpkg x-add-version --all
##[error]PowerShell exited with code '1'.
Finishing: Validate version files
```

2022-11-30 06:11 UTC, MonicaLiu0311 commented on versions/baseline.json
> +	"oatpp-openssh": {
After generating the baseline for the first time, if it is any additional modification for the same git branch, please use `./vcpkg x-add-version drogon --overwrite-version`.
(But you have a problem with the first generation, please use `./vcpkg x-add-version` drogon to complete the first generation)

2022-11-30 10:04 UTC, melchi45 reviewed
[openssh] generating the baseline information for openssh

- $ vcpkg format-manifest ports/openssh/vcpkg.json
- $ vcpkg x-add-version openssh

2022-11-30 10:43 UTC, MonicaLiu0311 commented
Please resolve CI conflicts.
```
##[error]Found the following errors:
    Error: While reading versions for port openssh from file: C:\a\1\s\versions\o-\openssh.json
       File declares version `9.1` with SHA: 075b6bedcaebea574d5a57cbe514e3f925fc19c8
       But local port with the same version has a different SHA: a9d1547b2dfb19e05f24ddbeb1faafa4d8309a86
       Please update the port's version fields and then run:

           vcpkg x-add-version openssh
           git add versions
           git commit -m "Update version database"

       to add a new version.
To attempt to resolve all errors at once, run:
vcpkg x-add-version --all
##[error]PowerShell exited with code '1'.
Finishing: Validate version files

```

2022-11-30 11:09 UTC, melchi45 reviewed
Update version database

2022-12-02 07:29 UTC, melchi45 reviewed
[openssh] add -lpthread option for x64-linux build, but this option do not needs arm64-linux.

2022-12-02 07:52 UTC, melchi45 reviewed
change post build check script for openssh

2022-12-02 07:56 UTC, melchi45 reviewed
[openssh] change git-tree version

2022-12-02 08:30 UTC, melchi45 reviewed
[openssh] add VCPKG_POLICY_EMPTY_INCLUDE_FOLDER option for openssh, this project is only executable binary tools to openssh.

2022-12-02 08:37 UTC, dg0yt commented
> Does this port add a library or an application? If the latter, I would assume it won't be accepted.

Now answering my own question from the CI results:
**This port doesn't add a library.** I think it won't be accepted. (Even most build tools are rejected.)

~~~
openssh:x64-linux:/debug/libexec/sftp-server
openssh:x64-linux:/debug/libexec/ssh-keysign
openssh:x64-linux:/debug/libexec/ssh-pkcs11-helper
openssh:x64-linux:/debug/libexec/ssh-sk-helper
openssh:x64-linux:/libexec/sftp-server
openssh:x64-linux:/libexec/ssh-keysign
openssh:x64-linux:/libexec/ssh-pkcs11-helper
openssh:x64-linux:/libexec/ssh-sk-helper
openssh:x64-linux:/share/openssh/copyright
openssh:x64-linux:/share/openssh/man1/scp.1
openssh:x64-linux:/share/openssh/man1/sftp.1
openssh:x64-linux:/share/openssh/man1/ssh-add.1
openssh:x64-linux:/share/openssh/man1/ssh-agent.1
openssh:x64-linux:/share/openssh/man1/ssh-keygen.1
openssh:x64-linux:/share/openssh/man1/ssh-keyscan.1
openssh:x64-linux:/share/openssh/man1/ssh.1
openssh:x64-linux:/share/openssh/man5/moduli.5
openssh:x64-linux:/share/openssh/man5/ssh_config.5
openssh:x64-linux:/share/openssh/man5/sshd_config.5
openssh:x64-linux:/share/openssh/man8/sftp-server.8
openssh:x64-linux:/share/openssh/man8/ssh-keysign.8
openssh:x64-linux:/share/openssh/man8/ssh-pkcs11-helper.8
openssh:x64-linux:/share/openssh/man8/ssh-sk-helper.8
openssh:x64-linux:/share/openssh/man8/sshd.8
openssh:x64-linux:/share/openssh/vcpkg.spdx.json
openssh:x64-linux:/share/openssh/vcpkg_abi_info.txt
openssh:x64-linux:/tools/openssh/bin/scp
openssh:x64-linux:/tools/openssh/bin/sftp
openssh:x64-linux:/tools/openssh/bin/ssh
openssh:x64-linux:/tools/openssh/bin/ssh-add
openssh:x64-linux:/tools/openssh/bin/ssh-agent
openssh:x64-linux:/tools/openssh/bin/ssh-keygen
openssh:x64-linux:/tools/openssh/bin/ssh-keyscan
openssh:x64-linux:/tools/openssh/debug/bin/scp
openssh:x64-linux:/tools/openssh/debug/bin/sftp
openssh:x64-linux:/tools/openssh/debug/bin/ssh
openssh:x64-linux:/tools/openssh/debug/bin/ssh-add
openssh:x64-linux:/tools/openssh/debug/bin/ssh-agent
openssh:x64-linux:/tools/openssh/debug/bin/ssh-keygen
openssh:x64-linux:/tools/openssh/debug/bin/ssh-keyscan
openssh:x64-linux:/tools/openssh/debug/sbin/sshd
openssh:x64-linux:/tools/openssh/sbin/sshd
~~~

2022-12-02 09:36 UTC, MonicaLiu0311 commented
@melchi45 
The `port` you add must generate a `dynamic/static library` (it can also be a `herder-only` library), and vcpkg does not accept ports that **only** have `executable files`.

2022-12-22 06:38 UTC, MonicaLiu0311 commented
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

2023-02-27 09:43 UTC, MonicaLiu0311 commented
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

2023-02-27 09:43 UTC, closed without merging