[libigl] update to v2.4.0
microsoft/vcpkg pull request #27963
Opened 2022-11-22 19:16 UTC by iAnyKey

Udates libigl to v2.4.0
see also https://github.com/microsoft/vcpkg/pull/26029

2022-11-22 19:50 UTC, iAnyKey commented
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

2022-11-22 21:01 UTC, iAnyKey commented
linux build fails for this reason:
MPFR cannot be found:
```
CMake Error at cmake/find/FindMPFR.cmake:17 (find_path):
  Could not find MPFR_INCLUDES using the following files: mpfr.h
Call Stack (most recent call first):
  /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:829 (_find_package)
  CMakeLists.txt:69 (find_package)
```
[gmp_mpfr.cmake](https://github.com/libigl/libigl/blob/87a550af22fc4af210af40f1d61d81594bbaf546/cmake/recipes/external/gmp_mpfr.cmake#L33)

need help

2022-11-24 03:35 UTC, JonLiu1993 commented on ports/libigl/portfile.cmake
> +        png LIBIGL_PNG # Disable this feature due to issue https://github.com/libigl/libigl/issues/1199
@iAnyKey, Thanks for your pr, I saw this issue https://github.com/libigl/libigl/issues/1199 not be solved, why open this option, this option default to "ON"

2022-11-24 03:45 UTC, JonLiu1993 commented
When I tested the features by command "./vcpkg install libigl[*]:x86-windows", I got this error,
Please take a look:
````
Computing installation plan...
error: while looking for embree:x86-windows:
error: while loading embree:
The port directory (F:\Feature-test\libigl\vcpkg\ports\embree) does not exist````

2022-11-24 09:56 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +        png LIBIGL_PNG # Disable this feature due to issue https://github.com/libigl/libigl/issues/1199
@FrankXie05 enabled it, but I agree with him: the mentioned issue is only about someone forgotten to build libigl with the PNG option enabled.

Just tested the build routine on my side.
* Configuration step
```
git clone https://github.com/libigl/libigl -b v2.4.0
cd .\libigl\
mkdir build && cd build
cmake .. -DLIBIGL_PNG=ON
cmake .. -DLIBIGL_PNG=ON
```
results in (s. attached [configuration.log](configuration.log) for more details):
```


-- Configuring done
-- Generating done
-- Build files have been written to: C:/libigl/build
```

* Build step

```
cmake --build . --config Release
```
results in (s. attached [build.log](build.log) for more details):


[configuration.log]:https://github.com/microsoft/vcpkg/files/10082671/configuration.log
[build.log]:https://github.com/microsoft/vcpkg/files/10083214/build.log

2022-11-24 11:09 UTC, FrankXie05 requested changes

2022-11-24 11:09 UTC, FrankXie05 commented on ports/libigl/vcpkg.json
> +          "name": "embree",
```suggestion
          "name": "embree3",
```
Is it repeated with the `embree3` below.

2022-11-24 12:36 UTC, iAnyKey commented on ports/libigl/vcpkg.json
> +          "name": "embree",
fixed with https://github.com/microsoft/vcpkg/pull/27963/commits/76a4b123ca3db34752c2a7a3320e2ce172fc2f1e

2022-11-24 12:36 UTC, iAnyKey commented
> When I tested the features by command "./vcpkg install libigl[*]:x86-windows", I got this error, Please take a look:
> 
> ```
> Computing installation plan...
> error: while looking for embree:x86-windows:
> error: while loading embree:
> The port directory (F:\Feature-test\libigl\vcpkg\ports\embree) does not exist````
> ```

fixed with https://github.com/microsoft/vcpkg/pull/27963/commits/76a4b123ca3db34752c2a7a3320e2ce172fc2f1e

2022-11-24 12:39 UTC, iAnyKey commented
now we've got:
```
CMake Warning in doc/snippets/CMakeLists.txt:
  The object file directory

    C:/.hunter/_Base/ca7838d/7162b26/5ebf7ca/Build/Eigen/Build/Eigen-Debug-prefix/src/Eigen-Debug-build/doc/snippets/CMakeFiles/compile_Tridiagonalization_Tridiagonalization_MatrixType.dir/./

  has 187 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    compile_Tridiagonalization_Tridiagonalization_MatrixType.cpp.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.



[hunter ** INTERNAL **] Unexpected empty string
[hunter ** INTERNAL **] [Directory:C:/vcpkg/buildtrees/libigl/src/706e5ba176-88fa556277.clean/cmake/recipes/hunter]
```
Any ideas, how we could fix it?

[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/10084614/config-x86-windows-dbg-err.log)

2022-11-24 12:52 UTC, iAnyKey commented on ports/libigl/install-extra-headers.patch
> ++    hunter_add_package(Glad)
@FrankXie05 There is no such hunter package. results in
```
[hunter ** INTERNAL **] Unexpected empty string
[hunter ** INTERNAL **] [Directory:C:/vcpkg/buildtrees/libigl/src/706e5ba176-88fa556277.clean/cmake/recipes/hunter]

```
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/10084703/config-x86-windows-dbg-err.log)

2022-11-24 13:36 UTC, iAnyKey commented on ports/libigl/install-extra-headers.patch
> ++    hunter_add_package(Glad)
happens because of glad package does not exist in hunter. fixed with https://github.com/microsoft/vcpkg/pull/27963/commits/c39c13d44b33dc5658163507f9c6d405449bda50

2022-11-24 13:37 UTC, iAnyKey commented
still something wrong with `GMP`: `.\vcpkg.exe install libigl[*]`:

```
CMake Warning at CMakeLists.txt:79 (message):
  Matlab not found, disabling igl_restricted::matlab module.


CMake Warning at CMakeLists.txt:84 (message):
  Mosek not found, disabling igl_restricted::mosek module.


CMake Error at cmake/find/FindGMP.cmake:17 (find_path):
  Could not find GMP_INCLUDES using the following files: gmp.h
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  C:/vcpkg/installed/x86-windows/share/cgal/CGAL_SetupGMP.cmake:24 (find_package)
  C:/vcpkg/installed/x86-windows/share/cgal/CGAL_SetupCGALDependencies.cmake:37 (include)
  C:/vcpkg/installed/x86-windows/share/cgal/CGALConfig.cmake:155 (include)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  cmake/recipes/hunter/cgal.cmake:2 (find_package)
  cmake/igl/modules/copyleft/cgal.cmake:17 (include)
  cmake/igl/igl_include.cmake:32 (include)
  cmake/igl/igl_include.cmake:40 (_igl_include_full)
  cmake/libigl.cmake:26 (igl_include_optional)
  CMakeLists.txt:142 (include)
```

2022-11-24 13:47 UTC, iAnyKey commented
still something wrong with `GMP`: `.\vcpkg.exe install libigl[*]`:

```
CMake Warning at CMakeLists.txt:79 (message):
  Matlab not found, disabling igl_restricted::matlab module.


CMake Warning at CMakeLists.txt:84 (message):
  Mosek not found, disabling igl_restricted::mosek module.


CMake Error at cmake/find/FindGMP.cmake:17 (find_path):
  Could not find GMP_INCLUDES using the following files: gmp.h
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  C:/vcpkg/installed/x86-windows/share/cgal/CGAL_SetupGMP.cmake:24 (find_package)
  C:/vcpkg/installed/x86-windows/share/cgal/CGAL_SetupCGALDependencies.cmake:37 (include)
  C:/vcpkg/installed/x86-windows/share/cgal/CGALConfig.cmake:155 (include)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  cmake/recipes/hunter/cgal.cmake:2 (find_package)
  cmake/igl/modules/copyleft/cgal.cmake:17 (include)
  cmake/igl/igl_include.cmake:32 (include)
  cmake/igl/igl_include.cmake:40 (_igl_include_full)
  cmake/libigl.cmake:26 (igl_include_optional)
  CMakeLists.txt:142 (include)
```
need help

2022-11-24 19:27 UTC, dg0yt commented on ports/libigl/portfile.cmake
> +        -DHUNTER_ENABLED=ON
Don't enable hunter in a vcpkg port. Or don't use vcpgk.

2022-11-25 13:14 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +        -DLIBIGL_COPYLEFT_COMISO=OFF #there is no comiso port available anywhere. solved internally via FetchContent in cmake\recipes\external\comiso.cmake. maybe replace in patch with vcpkg_from_git
These three options are internally downloaded by libigl via CMAKE's FetchContent. Unfortunately I dont know, how to get rid of FetchContent in a vcpkg port. They are also unavailable over vcpkg.

2022-11-28 06:23 UTC, FrankXie05 submitted a review, later dismissed

2022-11-28 12:04 UTC, JonLiu1993 submitted a review, later dismissed

2022-11-29 08:12 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2022-11-29 21:22 UTC, BillyONeal commented on ports/libigl/portfile.cmake
> +# Header-only library
It's asking for an awful lot of non header-only dependencies to be a header only library... ?

2022-11-29 21:36 UTC, JavierMatosD submitted a review, later dismissed

2022-11-29 21:36 UTC, JavierMatosD commented on ports/libigl/dependencies.patch
> ++++ /dev/null
FindXxx.cmake files should be removed by using a file(REMOVE ... ) instead of a patch.

2022-11-29 21:36 UTC, JavierMatosD commented on ports/libigl/dependencies.patch
> ++find_package(eigen3)
find package calls should be CONFIG REQUIRED

2022-11-29 21:36 UTC, JavierMatosD commented on ports/libigl/dependencies.patch
> ++find_package(embree 3.12)
Including the version here is a bit suspect. vcpkg should handle the version resolution. Is there a reason for including the version?

2022-11-30 10:53 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +# Header-only library
sadly yes :D

2022-11-30 11:01 UTC, iAnyKey commented on ports/libigl/dependencies.patch
> ++find_package(embree 3.12)
no but otherwise cmake wont find compatible version responding:
```
CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
  Could not find a configuration file for package "embree" that is compatible
  with requested version "".
```

2022-11-30 13:07 UTC, dg0yt commented on ports/libigl/dependencies.patch
> ++find_package(embree 3.12)
The embree `usage` files suggests
~~~cmake
find_package(embree 3 CONFIG REQUIRED)
~~~
This should be generic enough for vcpkg.

2022-11-30 13:10 UTC, dg0yt commented on ports/libigl/dependencies.patch
> +The file will have its original line endings in your working directory
These lines shouln't be in any patches.

2022-12-20 03:22 UTC, JonLiu1993 commented
Ping @iAnyKey for response.

2023-01-29 11:20 UTC, zone-1614 commented
why i get 
```
Could not find a package configuration file provided by "igl" with any of
  the following names:

    iglConfig.cmake
    igl-config.cmake
```
And vcpkg doesn't download the file `igl/opengl/glfw/Viewer.h`

2023-01-30 06:09 UTC, JonLiu1993 commented
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

2023-01-30 17:49 UTC, iAnyKey commented on ports/libigl/dependencies.patch
> +The file will have its original line endings in your working directory
done

2023-01-30 17:49 UTC, iAnyKey commented on ports/libigl/dependencies.patch
> ++find_package(embree 3.12)
fixed

2023-01-30 17:49 UTC, iAnyKey commented on ports/libigl/dependencies.patch
> ++find_package(eigen3)
fixed

2023-01-30 17:50 UTC, iAnyKey commented on ports/libigl/dependencies.patch
> ++++ /dev/null
fixed

2023-01-30 17:51 UTC, iAnyKey commented
> Pinging @iAnyKey for response. Is work still being done for this PR?

@JonLiu1993 sorry took me long this time. Should work fine now. Also implemented feedback from everyone here.

2023-01-30 18:01 UTC, iAnyKey commented
Need help with x64_linux port. For some reason it wont find `eigen3`:
[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10538538/config-x64-linux-dbg-CMakeCache.txt.log)
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/10538539/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10538540/config-x64-linux-dbg-out.log)

2023-01-30 18:29 UTC, dg0yt commented
The package names is spelled `Eigen3`, not  `eigen3`.

2023-02-01 00:33 UTC, BillyONeal commented on ports/libigl/portfile.cmake
> +# Header-only library
Sorry, I should be less snarky. There is clearly something happening here that is not just copying headers. Things like `LIBIGL_USE_STATIC_LIBRARY` suggest that there is in fact a static library and that this thing is not header only. Can you explain why / how this is header only despite the port clearly doing not header only things?

2023-02-01 00:34 UTC, BillyONeal commented
Readded author-response tag for https://github.com/microsoft/vcpkg/pull/27963#discussion_r1092628298

2023-02-01 06:22 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +# Header-only library
Well I'm not the developer oft this monstrum. You may take a look into previous port versions of libigl for vcpkg - it was never 'header only'.
I only completed work started by @FrankXie05

2023-02-01 06:38 UTC, FrankXie05 commented on ports/libigl/portfile.cmake
> +# Header-only library
I didn't modify anything, just modernized. 
https://github.com/microsoft/vcpkg/blob/17030920aa97f2dc17a0bdc314344b5ca2807fdf/ports/libigl/portfile.cmake#L31

2023-02-28 20:26 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +# Header-only library
so are we concluded in this discussion @BillyONeal, or is there anything to fix? This port would be completed otherwise

2023-02-28 20:29 UTC, iAnyKey commented
From my side I don't see anything to do anymore. Does anybody?

2023-02-28 20:31 UTC, iAnyKey commented on ports/libigl/dependencies.patch
> ++++ /dev/null
done

2023-03-01 03:02 UTC, FrankXie05 commented on ports/libigl/portfile.cmake
> +# Header-only library
We can give users a choice. If the current port construction is static, start and build the static library(LIBIGL_USE_STATIC_LIBRARY= ON). :)

2023-03-02 20:40 UTC, Neumann-A commented on ports/libigl/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake)
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/libigl PACKAGE_NAME libigl)
```
Your config stuff doesn't work

2023-03-02 20:44 UTC, Neumann-A commented on ports/libigl/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake)
the config is also not including the target file.....

2023-03-02 21:01 UTC, Neumann-A commented
@iAnyKey Why is this installing `cpp` files into `include` ?

2023-03-02 21:28 UTC, Neumann-A commented
Ok got it why it installes cpp files but the features are completly broken and don't install the required headers. If you ask for cgal for example no further headers than without that option are getting installed. Something is wrong here.

2023-03-03 10:25 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake)
Considering previous ports (e.g. https://github.com/microsoft/vcpkg/blob/0bf3923f9fab4001c00f0f429682a0853b5749e0/ports/libigl/portfile.cmake#L68) I would leave it unchanged

2023-03-03 10:36 UTC, iAnyKey commented
> Ok got it why it installes cpp files but the features are completly broken and don't install the required headers. If you ask for cgal for example no further headers than without that option are getting installed. Something is wrong here.

You can see in https://github.com/libigl/libigl/blob/66b3ef2253e765d0ce0db74cec91bd706e5ba176/cmake/igl/modules/copyleft/cgal.cmake that the option 'cgal' does not much - it only includes tests, which are disabled. However cgal is included in the pipeline, will be installed separately and can be referenced out of libigl

2023-03-03 10:41 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +        -DLIBIGL_COPYLEFT_COMISO=OFF #there is no comiso port available anywhere. solved internally via FetchContent in cmake\recipes\external\comiso.cmake. maybe replace in patch with vcpkg_from_git
does anybody know how such dependency could be integrated in the port?
https://github.com/libigl/libigl/blob/66b3ef2253e765d0ce0db74cec91bd706e5ba176/cmake/recipes/external/comiso.cmake#L7-L12

2023-03-03 10:44 UTC, iAnyKey commented
does anybody know how such dependency (external git repo with FetchContent) could be integrated in the port?
https://github.com/libigl/libigl/blob/66b3ef2253e765d0ce0db74cec91bd706e5ba176/cmake/recipes/external/comiso.cmake#L7-L12

```cmake
include(FetchContent)
FetchContent_Declare(
    comiso
    GIT_REPOSITORY https://github.com/libigl/CoMISo.git
    GIT_TAG 536440e714f412e7ef6c0b96b90ba37b1531bb39
)
```

2023-03-03 10:58 UTC, Neumann-A commented
the same way https://github.com/microsoft/vcpkg/blob/master/ports/paraview/portfile.cmake does it.

2023-03-03 10:58 UTC, iAnyKey commented
> @iAnyKey If we want to use vcpkg, we need to open Hunter. Like my original patch `ports/libigl/install-extra-headers.patch`. And we should not use `external`.

Why? Right now it works without hunter purely over vcpkg. I'm testing a static build at the moment. The thing is: `comiso` and `tetgen` are only available as preserved repositories by libigl. Respective options cause download using fetchcontent.
I`m thinking on something similar like here https://github.com/blavallee/vcpkg/blob/12d976b0d0c12f32b6a839bf7120101a9984691f/ports/launch-darkly-server/portfile.cmake

2023-03-03 11:01 UTC, Neumann-A commented
> the option 'cgal' does not much - it only includes tests, which are disabled. However cgal is included in the pipeline, will be installed separately and can be referenced out of libigl

The problem is that the headers for libigl with cgal aren't installed. basically the whole folder https://github.com/libigl/libigl/tree/66b3ef2253e765d0ce0db74cec91bd706e5ba176/include/igl/copyleft/cgal needs to installed by libigl for projects to consume (e.g. prusaslicer which currently vendors libigl and uses one of the headers in this folder)

2023-03-03 11:07 UTC, iAnyKey commented
> the headers for libigl with cgal aren't installed. basically the whole folder https://github.com/libigl/libigl/tree/66b3ef2253e765d0ce0db74cec91bd706e5ba176/include/igl/copyleft/cgal needs to installed by libigl

on my installation, if I install with `.\vcpkg.exe install libigl[*]` these headers can be found under `.\vcpkg\installed\x86-windows\include\CGAL`, where they in my opinion also belong to

2023-03-03 11:54 UTC, Neumann-A commented
I just do `vcpkg install libigl[cgal]` and no extra headers get installed.

> these headers can be found under .\vcpkg\installed\x86-windows\include\CGAL

No they are not. Check `packages/libigl_x86-windows/include` to actually see what gets installed. 
`libigl` uses a completely different namespace from cgal so it **HAS TO** install its headers.

2023-03-03 12:43 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +# static or dynamic build
@FrankXie05 like that? 
now one coud issue `.\vcpkg.exe install libigl[*]:x86-windows-static`

2023-03-03 12:45 UTC, iAnyKey commented on ports/libigl/portfile.cmake
> +string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" LIBIGL_BUILD_STATIC)
@FrankXie05 like that? 
now one coud issue `.\vcpkg.exe install libigl[*]:x86-windows-static`

2023-03-03 15:38 UTC, iAnyKey commented
For some reasone the install step fails on x64 and linux, claiming ninja subcommand failure w/o details.  Would somebody take a look into?
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/10883561/install-x64-windows-static-dbg-out.log)
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10883562/install-x64-linux-dbg-out.log)

2023-03-03 15:41 UTC, iAnyKey commented
> 



> I just do `vcpkg install libigl[cgal]` and no extra headers get installed.
> 
> > these headers can be found under .\vcpkg\installed\x86-windows\include\CGAL
> 
> No they are not. Check `packages/libigl_x86-windows/include` to actually see what gets installed. `libigl` uses a completely different namespace from cgal so it **HAS TO** install its headers.

do you get a different result after "standalone" compilation of libigl? Because this port is nonivasive and should provide the same result as the main repository...

2023-03-03 16:46 UTC, iAnyKey commented
> the same way https://github.com/microsoft/vcpkg/blob/master/ports/paraview/portfile.cmake does it.

done with https://github.com/microsoft/vcpkg/pull/27963/commits/03df64861c8374b52d4625625fbb916452b70e87

2023-03-03 17:16 UTC, iAnyKey commented
well it seems like I'm looking for help again. 😒
No idea, why x64_linux, x64osx, and x64_windows_static fail on build stage

2023-03-13 07:37 UTC, JonLiu1993 commented
@iAnyKey, Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/86283/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip).

2023-03-13 14:10 UTC, iAnyKey commented
> @iAnyKey, Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/86283/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip).

Thank you for the link, but thats where these logs are from:
> For some reasone the install step fails on static x64 and linux, claiming ninja subcommand failure w/o details. Would somebody take a look into? [install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/10883561/install-x64-windows-static-dbg-out.log) [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10883562/install-x64-linux-dbg-out.log)

2023-03-14 02:21 UTC, FrankXie05 commented
Error log from `install-x64-linux-dbg-out.log`:
```
/mnt/vcpkg-ci/buildtrees/libigl/src/706e5ba176-2331c97b95.clean/include/igl/average_from_edges_onto_vertices.cpp:65:271: error: wrong number of template arguments (1, should be 2)
   65 | template void igl::average_from_edges_onto_vertices<Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::PartialReduxExpr<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::internal::member_norm<double>, 1>, Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::MatrixBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::MatrixBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::MatrixBase<Eigen::Matrix<int, -1, -1, 0, -1, -1> > const&, Eigen::MatrixBase<Eigen::PartialReduxExpr<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::internal::member_norm<double>, 1> > const&, Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&);
      |    
```
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10963548/install-x64-linux-dbg-out.log)

Is missing template parameters and headers? Need to check it out. 🤔

2023-03-14 03:13 UTC, FrankXie05 commented
> Is missing template parameters and headers? Need to check it out. 🤔

After investigation, it was found that upstream removed this definition `member_norm`.

https://github.com/libigl/libigl/commit/c35f0fee39195e72ea92d28ab7c10dfc0425b5d4

2023-03-17 20:26 UTC, iAnyKey commented
> > Is missing template parameters and headers? Need to check it out. 🤔
> 
> After investigation, it was found that upstream removed this definition `member_norm`.
> 
> [libigl/libigl@c35f0fe](https://github.com/libigl/libigl/commit/c35f0fee39195e72ea92d28ab7c10dfc0425b5d4)

thank you! Fixed it with https://github.com/microsoft/vcpkg/pull/27963/commits/599b52c3dd2355f1141736ac7d1a44aff103b607. looks good now

2023-03-28 01:51 UTC, JonLiu1993 approved these changes

2023-03-28 16:53 UTC, merged

2023-04-02 15:41 UTC, FabienPean commented on ports/libigl/portfile.cmake
> +# Header-only library
> There is clearly something happening here that is not just copying headers. Things like `LIBIGL_USE_STATIC_LIBRARY` suggest that there is in fact a static library and that this thing is not header only. Can you explain why / how this is header only despite the port clearly doing not header only things?

With this option, the library is explicitly instantiating some templates into a static library, _but_, it also removes all definition of the templated functions... Building with `LIBIGL_USE_STATIC_LIBRARY` is fundamentally different from standard expectation when considering static/shared. It was the case then https://github.com/microsoft/vcpkg/pull/14888, it is still applicable now after checking the repo. 

Ultimately this means using libigl after this PR with a static vcpkg triplet would break users relying on types outside the ones allowed by libigl devs.