FreeRDP: verion update to 2.9.0
microsoft/vcpkg pull request #28106
Opened 2022-12-01 08:58 UTC by KangLin

2022-12-01 09:40 UTC, JonLiu1993 requested changes

2022-12-01 09:40 UTC, JonLiu1993 commented on ports/freerdp/portfile.cmake
> +vcpkg_configure_cmake(
@KangLin, Please do not change new functions to deprecated functions

2022-12-01 09:40 UTC, JonLiu1993 commented on ports/freerdp/portfile.cmake
> +vcpkg_install_cmake()
same as above

2022-12-01 09:40 UTC, JonLiu1993 commented on ports/freerdp/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/WinPR2_temp/WinPR2 PACKAGE_NAME WinPR)
same as above

2022-12-01 10:23 UTC, JonLiu1993 commented
@KangLin, please consider migrating it to the new functions:
at poftfile.cmake 57 line:

vcpkg_copy_tool_dependencies -> [[vcpkg_copy_tools](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md)]

2022-12-01 12:53 UTC, KangLin commented
@JonLiu1993 Already modified

2022-12-02 04:25 UTC, JonLiu1993 commented on ports/freerdp/portfile.cmake
> -vcpkg_copy_tool_dependencies("${CURRENT_PACKAGES_DIR}/tools/${PORT}")
@KangLin, can you explain why you removed `vcpkg_copy_tool_dependencies` instead of replacing it with vcpkg_copy_tools?

2022-12-02 07:13 UTC, KangLin commented on ports/freerdp/portfile.cmake
> -vcpkg_copy_tool_dependencies("${CURRENT_PACKAGES_DIR}/tools/${PORT}")
The above liens has done its job. If you use vcpkg_copy_tools, you also need to resolve the tool name.

2022-12-02 07:17 UTC, KangLin commented on ports/freerdp/portfile.cmake
> -vcpkg_copy_tool_dependencies("${CURRENT_PACKAGES_DIR}/tools/${PORT}")
The following code is equivalent to vcpkg_copy_tools:

```c++
file(GLOB_RECURSE TOOLS_RELEASE "${CURRENT_PACKAGES_DIR}/bin/*.exe")

if(TOOLS_RELEASE)
    file(COPY ${TOOLS_RELEASE} DESTINATION "${CURRENT_PACKAGES_DIR}/tools/${PORT}")
    file(GLOB_RECURSE TOOLS_DEBUG "${CURRENT_PACKAGES_DIR}/debug/bin/*.exe")
    file(REMOVE ${TOOLS_RELEASE} ${TOOLS_DEBUG})
endif()
```

2022-12-02 08:39 UTC, JonLiu1993 submitted a review, later dismissed

2022-12-02 09:09 UTC, JonLiu1993 commented
@KangLin, When I tested the features by command "./vcpkg install freerpd[*]: x86-windows", I got this error:
````
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: F:/Feature-test/free/vcpkg/downloads/tools/cmake-3.25.0-windows/cmake-3.25.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: F:/Feature-test/free/vcpkg/buildtrees/freerdp/x86-windows-dbg
    See logs for more information:
      F:\Feature-test\free\vcpkg\buildtrees\freerdp\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
````
F:\Feature-test\free\vcpkg\buildtrees\freerdp\install-x86-windows-dbg-out.log
````
FAILED: channels/urbdrc/client/libusb/CMakeFiles/urbdrc-client-libusb.dir/libusb_udevman.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe   -DFREERDP_EXPORTS -DHAVE_CONFIG_H -DUNICODE -DWIN32_LEAN_AND_MEAN -DWINPR_EXPORTS -DWINVER=0x0601 -DWITH_OPENSSL -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0601 -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_X86_ -IF:\Feature-test\free\vcpkg\installed\x86-windows\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\winpr\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg\winpr\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\rdtk\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg\rdtk\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\common -IF:\Feature-test\free\vcpkg\installed\x86-windows\include\libusb-1.0 -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\.. /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /Gd /W3 /Zi -DWINPR_DLL /D_DEBUG /MDd /Z7 /Ob2 /Od /RTC1 /showIncludes /Fochannels\urbdrc\client\libusb\CMakeFiles\urbdrc-client-libusb.dir\libusb_udevman.c.obj /Fdchannels\urbdrc\client\libusb\CMakeFiles\urbdrc-client-libusb.dir\urbdrc-client-libusb.pdb /FS -c F:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\libusb_udevman.c
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
F:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\libusb_udevman.c(875): error C2440: 'function': cannot convert from 'int (__cdecl *)(libusb_context *,libusb_device *,libusb_hotplug_event,void *)' to 'libusb_hotplug_callback_fn'
F:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\libusb_udevman.c(875): warning C4024: 'libusb_hotplug_register_callback': different types for formal and actual parameter 7
[140/520] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe   -DFREERDP_EXPORTS -DHAVE_CONFIG_H -DUNICODE -DWIN32_LEAN_AND_MEAN -DWINPR_EXPORTS -DWINVER=0x0601 -DWITH_OPENSSL -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0601 -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_X86_ -IF:\Feature-test\free\vcpkg\installed\x86-windows\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\winpr\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg\winpr\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\rdtk\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\x86-windows-dbg\rdtk\include -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\common -IF:\Feature-test\free\vcpkg\installed\x86-windows\include\libusb-1.0 -IF:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\.. /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /Gd /W3 /Zi -DWINPR_DLL /D_DEBUG /MDd /Z7 /Ob2 /Od /RTC1 /showIncludes /Fochannels\urbdrc\client\libusb\CMakeFiles\urbdrc-client-libusb.dir\libusb_udevice.c.obj /Fdchannels\urbdrc\client\libusb\CMakeFiles\urbdrc-client-libusb.dir\urbdrc-client-libusb.pdb /FS -c F:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\libusb_udevice.c
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
F:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\libusb_udevice.c(1009): warning C4101: 'i': unreferenced local variable
F:\Feature-test\free\vcpkg\buildtrees\freerdp\src\2.9.0-c89f44faff.clean\channels\urbdrc\client\libusb\libusb_udevice.c(1011): warning C4101: 'urbdrc': unreferenced local variable
````

please take a look

2022-12-02 17:02 UTC, dg0yt commented
Can you please fix the typo in commit and PR title? I assume it is meant to be "version".

2022-12-06 03:22 UTC, KangLin commented
@akallabeth Please take a look at the error above.

2022-12-07 05:32 UTC, KangLin commented
@akallabeth I only need freerdp-server library. but There are not close client program in CMakeLists.txt.
In addition, please pay attention to the error of libusb above. I temporarily shut down libusb.

2022-12-07 09:19 UTC, akallabeth commented
@KangLin ok, the libusb thing is fixed with https://github.com/FreeRDP/FreeRDP/pull/8498 (backport in https://github.com/FreeRDP/FreeRDP/pull/8499 )

2022-12-08 05:03 UTC, KangLin commented
@akallabeth Thanks! I am closed the server programe.

2022-12-08 06:28 UTC, JonLiu1993 requested changes

2022-12-08 06:28 UTC, JonLiu1993 commented on versions/l-/libssh.json
> +      "git-tree": "68659ea5eb32e7c3f1b594fa7c6179a745efbb5e",
Is this seemingly unrelated modification a misoperation?

2022-12-08 06:28 UTC, JonLiu1993 commented on versions/o-/opencv3.json
> -    },
Is this seemingly unrelated modification a misoperation?

2022-12-08 07:13 UTC, KangLin commented on versions/l-/libssh.json
> +      "git-tree": "68659ea5eb32e7c3f1b594fa7c6179a745efbb5e",
Generated after executing vcpkg x-add-version --all
I am deleted it.

2022-12-08 07:16 UTC, JonLiu1993 approved these changes, later dismissed

2022-12-14 02:48 UTC, dan-shaw submitted a review, later dismissed
Thanks for the PR!

2022-12-14 08:05 UTC, JonLiu1993 approved these changes

2022-12-14 18:55 UTC, merged