Fastdds
microsoft/vcpkg pull request #28181
Opened 2022-12-05 12:13 UTC by ex-purple

**Describe the pull request**

- #### What does your PR fix?
Introduce new port fastdds

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-12-12 07:15 UTC, JonLiu1993 commented
@ex-purple, Thanks for your pr, This is ci error log, please take a look:

````
FAILED: tools/fds/fast-discovery-serverd-1.0.1.exe 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=tools\fds\CMakeFiles\fast-discovery-server.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe  tools\fds\CMakeFiles\fast-discovery-server.dir\server.cpp.obj  /out:tools\fds\fast-discovery-serverd-1.0.1.exe /implib:tools\fds\fast-discovery-serverd-1.0.1.lib /pdb:tools\fds\fast-discovery-serverd-1.0.1.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  src\cpp\libfastrtpsd-2.8.lib  D:\installed\x64-windows-static\debug\lib\libfastcdrd-1.0.lib  D:\installed\x64-windows-static\debug\lib\foonathan_memory-0.6.1-dbg.lib  D:\installed\x64-windows-static\debug\lib\tinyxml2.lib  D:\installed\x64-windows-static\debug\lib\libssl.lib  D:\installed\x64-windows-static\debug\lib\libcrypto.lib  crypt32.lib  ws2_32.lib  crypt32.lib  iphlpapi.lib  Shlwapi.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe tools\fds\CMakeFiles\fast-discovery-server.dir\server.cpp.obj /out:tools\fds\fast-discovery-serverd-1.0.1.exe /implib:tools\fds\fast-discovery-serverd-1.0.1.lib /pdb:tools\fds\fast-discovery-serverd-1.0.1.pdb /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /subsystem:console src\cpp\libfastrtpsd-2.8.lib D:\installed\x64-windows-static\debug\lib\libfastcdrd-1.0.lib D:\installed\x64-windows-static\debug\lib\foonathan_memory-0.6.1-dbg.lib D:\installed\x64-windows-static\debug\lib\tinyxml2.lib D:\installed\x64-windows-static\debug\lib\libssl.lib D:\installed\x64-windows-static\debug\lib\libcrypto.lib crypt32.lib ws2_32.lib crypt32.lib iphlpapi.lib Shlwapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:tools\fds\CMakeFiles\fast-discovery-server.dir/intermediate.manifest tools\fds\CMakeFiles\fast-discovery-server.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'fastcdrd-1.0.lib'
ninja: build stopped: subcommand failed.

````

2022-12-27 15:02 UTC, dg0yt reviewed
I know it is a draft, but I want to save and share my notes.

2022-12-27 15:02 UTC, dg0yt commented on ports/fastdds/portfile.cmake
> +    if(EXISTS "${CURRENT_PACKAGES_DIR}/bin/${TOOL}")
`if(EXISTS ...)` is somewhat prone to hide problems. It is better to use the variables which actually control the existence of these tools.

2022-12-27 21:41 UTC, ex-purple commented on ports/fastdds/fix-debug-postfix.patch
> ++    set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX -${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR})
I was just trying to resolve the build issue. Anyway, this approach is ineffective, so I will remove it

2022-12-27 21:50 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/tools/fastdds/discovery/parser.py" "tool_path / '../../../bin'" "tool_path / '..'")
Done

2022-12-28 10:58 UTC, dg0yt commented on ports/fastdds/portfile.cmake
> +endif()
Which files are left in `bin`, after `vcpkg_copy_tools(... AUTO_CLEAN)`?

2022-12-28 11:09 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
Unfortunately, I do not have a Windows development environment. It is cause why I suffer here

2022-12-28 11:13 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
It is strange, but:
"
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.
D:/packages/fastdds_x64-windows/debug/bin/fast-discovery-serverd-1.0.1.exe
"

What is default VCPKG_BUILD_TYPE for Windows?

2022-12-28 11:32 UTC, dg0yt commented on ports/fastdds/portfile.cmake
> +endif()
> I do not have a Windows development environment.

Neither do I, but vcpkg CI usually gives me what I need.

> It is strange, but:
> 
> ```
> The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.
> D:/packages/fastdds_x64-windows/debug/bin/fast-discovery-serverd-1.0.1.exe
> ```
> 

IIUC it is not so strange: The debug variant of the tool uses the `d` debug postfix indeed (`serverd` instead of `server`). This is not handled by `vcpkg_copy_tools`. Are the debug variants of these tools needed?

> Which is default value of VCPKG_BUILD_TYPE for Windows?

For portfiles, you can assume two accepted cases: 
- unset/emtpy/false (supported triplets, meaning release+debug), 
- `release` (release-only triplets). 
 
That's why we only write `if(NOT VCPKG_BUILD_TYPE)` to guard code paths which handle the debug variant.

2022-12-28 11:33 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
Sorry, but vcpkg_copy_tools is not working for this project, because fast-discovery-server-1.0.1 and fast-discovery-serverd-1.0.1 are present with different conditions. And these conditions are different for different platforms and build types. Moreover, it is quite difficult to understand the logic of these conditions.

2022-12-28 11:35 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +    if(EXISTS "${CURRENT_PACKAGES_DIR}/bin/${TOOL}")
Sorry, but I can't force the project to go through the configuration stage in any other way.

2022-12-28 12:33 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
> That's why we only write if(NOT VCPKG_BUILD_TYPE) to guard code paths which handle the debug variant.

That explains a lot, thanks

2022-12-28 12:33 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +    if(EXISTS "${CURRENT_PACKAGES_DIR}/bin/${TOOL}")
This is issues is solved, thank you

2022-12-28 12:33 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
This is issues is solved, thank you

2022-12-28 14:22 UTC, ex-purple commented
@dg0yt , @JonLiu1993 I need your help.

I solved build issues for this port, but now I have problem with installation.
The FastRTPS project has been renamed to the FastDDS, so I want to add new port version that names fastdds. But here I have conflict with legacy port fastrtps.

What is true way for solve this conflict?

2022-12-29 23:01 UTC, ex-purple commented
fastrtps problem has been solved by deprecating the port

2023-01-13 06:31 UTC, JonLiu1993 commented
@ex-purple, This is error log, please take a look:
````
CMake Error at src/cpp/cmake_install.cmake:80 (file):
  file INSTALL cannot find
  "D:/buildtrees/fastdds/x64-windows-static-dbg/src/cpp/symbols/libfastrtpsd-2.9.pdb":
  File exists.
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)

````

2023-01-13 06:50 UTC, dg0yt requested changes
There is `/share/fastrtps/cmake/fastrtps-config.cmake` (in x64-windows). So the portfile must call 
~~~cmake
vcpkg_cmake_config_fixup(CONFIG_PATH "share/fastrtps/cmake" PACKAGE_NAME fastrtps)
~~~
and the manifest needs another host dependency on `vcpkg-cmake-config`.

2023-01-13 06:50 UTC, dg0yt commented on ports/fastdds/portfile.cmake
> +endif()
We don't need a guard around the release variant.

2023-01-13 06:50 UTC, dg0yt commented on ports/fastdds/portfile.cmake
> +endif()
Move the removal of the debug tool before the calls. `vcpkg_copy_tool`. Then `AUTO_CLEAN` can take care of `bin`, and we won't need `file(REMOVE_RECURSE ...)` which might remove unhandled tools.

2023-01-13 07:30 UTC, ex-purple commented
Depends on PR https://github.com/microsoft/vcpkg/pull/28905

2023-01-17 22:47 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
Done

2023-01-17 22:47 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
Done

2023-01-18 05:07 UTC, dg0yt commented on ports/fastrtps/disable-symlink.patch
> -       COMPONENT discovery)
This patch should be ported to the new port. See comment at top for the reasons.

2023-01-18 08:20 UTC, ex-purple commented on ports/fastrtps/disable-symlink.patch
> -       COMPONENT discovery)
Done

2023-01-18 10:41 UTC, ex-purple commented on ports/fastdds/portfile.cmake
> +endif()
In other case, we have:

```
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "fast-discovery-server":

      "D:/packages/fastdds_x86-windows/bin/fast-discovery-server.exe" does not exist
Call Stack (most recent call first):
  ports/fastdds/portfile.cmake:38 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)

```

2023-01-19 07:17 UTC, JonLiu1993 commented
Please get the ci error log:
````
error: Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: C:\a\1\s\ports\fastdds\portfile.cmake
error: building fastdds:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Elapsed time to handle fastdds:x86-windows: 1.662 min
Installing 10/10 fastrtps:x86-windows...
Building fastrtps[core]:x86-windows...
error: building fastrtps:x86-windows failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
    due to the following missing dependencies:
        fastdds[core]:x86-windows
Elapsed time to handle fastrtps:x86-windows: 21.6 us
Total install time: 1.683 min

````

2023-02-06 08:56 UTC, JonLiu1993 commented
Pinging @ex-purple for response. Is work still being done for this PR?

2023-02-06 09:04 UTC, ex-purple commented
@JonLiu1993
As a result of my lack of appropriate environment, I am unable to fix problems specific to Windows. There seems to be nothing else I can do here

2023-02-06 09:23 UTC, JonLiu1993 commented
Temporarily close this PR, please ping us to reopen if work is still being done.

2023-02-06 09:23 UTC, closed without merging