Fix the vcpkg_install_msbuild docs to reflect handling of x86==Win32.
microsoft/vcpkg pull request #28189
Opened 2022-12-05 20:28 UTC by BillyONeal

Also fixes ports that were doing this in an overcomplicated way.

See:
* https://github.com/microsoft/vcpkg/pull/28119#issuecomment-1336270264
* https://github.com/microsoft/vcpkg/issues/28076

2022-12-06 02:13 UTC, LilyWangLL requested changes

2022-12-06 02:13 UTC, LilyWangLL commented on ports/activemq-cpp/portfile.cmake
> +    if(VCPKG_TARGET_ARCHITECTURE MATCHES "x86")
Should this judgment `x86` also be removed?

2022-12-06 02:13 UTC, LilyWangLL commented on scripts/templates/portfile.in.cmake
>  #   BUILD_ARCH                = "Win32" "x64" "ARM"
Why is `arm64` not added here? Is it included in `ARM`?

2022-12-06 02:14 UTC, LilyWangLL commented on scripts/templates/portfile.in.cmake
>  #   BUILD_ARCH                = "Win32" "x64" "ARM"
Why is `arm64` not added here? Is it included in `ARM`?

2022-12-06 02:16 UTC, LilyWangLL requested changes

2022-12-06 02:23 UTC, LilyWangLL requested changes

2022-12-06 02:23 UTC, LilyWangLL commented on ports/ecsutil/portfile.cmake
> +    PLATFORM "${TRIPLET_SYSTEM_ARCH}"
```suggestion
```
This is a default behavior, why not remove this like ports `3fd` and `ace`?

2022-12-06 04:02 UTC, JonLiu1993 requested changes

2022-12-30 17:32 UTC, ras0219-msft commented
Docs changes have been migrated in https://github.com/microsoft/vcpkg-docs/pull/21

2023-03-13 08:08 UTC, JonLiu1993 commented
@BillyONeal, The modification of the documentation part has been merged in microsoft/vcpkg-docs#21, can we remove the modification related to the documentation in this PR?

2023-05-08 17:55 UTC, BillyONeal commented
Was merged

2023-05-08 17:55 UTC, closed without merging