[ECSUtil] update to version 1.0.7.22
microsoft/vcpkg pull request #28206
Opened 2022-12-06 14:56 UTC by bobk2824

update ECSUtil to version 1.0.7.22

Triplets are supported:
- x64-windows
- x64-windows-static
- x64-windows-static-md
- x86-windows
- x86-windows-static
- x86-windows-static-md

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-12-09 06:59 UTC, Adela0814 requested changes

2022-12-09 06:59 UTC, Adela0814 commented on scripts/ci.baseline.txt
> +ecsutil:x86-windows=skip
This port cannot be tested by CI right now, so we doubt that this port update makes sense.

2022-12-09 13:05 UTC, bobk2824 commented on scripts/ci.baseline.txt
> +ecsutil:x86-windows=skip
You know what? I think you're right. I've been searching on how to remove a port from vcpkg and I can't find anything. How can I remove ECSUtil from vcpkg?
Thanks,
Bob

2022-12-12 21:35 UTC, closed without merging

2022-12-12 21:36 UTC, bobk2824 commented
update not needed anymore. Thanks.