Fix glib on x64-mingw-dynamic
microsoft/vcpkg pull request #28207
Opened 2022-12-06 17:06 UTC by kvnp

Building glib on x64-mingw-dynamic fails with the following error:

```
-- Package x64-mingw-dynamic-dbg
-- Package x64-mingw-dynamic-rel
CMake Error at ports/glib/portfile.cmake:63 (file):
  file RENAME failed to rename

    C:/Users/kevinpfeifer/Projekte/vcpkg/packages/glib_x64-mingw-dynamic/bin/glib-gettextize

  to

    C:/Users/kevinpfeifer/Projekte/vcpkg/packages/glib_x64-mingw-dynamic/tools/glib/glib-gettextize

  because: Das System kann die angegebene Datei nicht finden.

Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building glib:x64-mingw-dynamic failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glib]+Build+error
Include '[glib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: d7c68eea3 2022-12-05 (15 hours ago)
```

gcc -v
```
Using built-in specs.
COLLECT_GCC=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
OFFLOAD_TARGET_NAMES=nvptx-none
Target: x86_64-w64-mingw32
Configured with: ../configure --prefix=/r/winlibs64-11.3.0ucrt/2604.gcc/inst_gcc-12.2.0/share/gcc --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders' --with-tune=generic --enable-checking=release --enable-threads=posix --disable-sjlj-exceptions --disable-libunwind-exceptions --disable-serial-configure --disable-bootstrap --enable-host-shared --enable-plugin --disable-default-ssp --disable-rpath --disable-libstdcxx-debug --disable-version-specific-runtime-libs --with-stabs --disable-symvers --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --disable-gold --disable-nls --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-time --disable-libstdcxx-pch --with-mpc=/e/Prog/winlibs64-11.3.0ucrt/custombuilt --with-mpfr=/e/Prog/winlibs64-11.3.0ucrt/custombuilt --with-gmp=/e/Prog/winlibs64-11.3.0ucrt/custombuilt --with-isl=/e/Prog/winlibs64-11.3.0ucrt/custombuilt --enable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/r/winlibs64-11.3.0ucrt/2604.gcc/gcc-12.2.0/build_mingw/mingw-w64 CFLAGS='-I/e/Prog/winlibs64-11.3.0ucrt/custombuilt/include/libdl-win32 -D__USE_MINGW_ACCESS' CXXFLAGS=-D__USE_MINGW_ACCESS LDFLAGS='-Wl,--disable-nxcompat -Wl,--disable-high-entropy-va -Wl,--disable-dynamicbase'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)
```

The portfile currently assumes that the executable glib-gettextize is built when using mingw which is not the case. Removing it from the loop for all windows builds fixes it.

**Describe the pull request**

- #### What does your PR fix?
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-12-07 06:53 UTC, JonLiu1993 commented
@kvnp, thanks for your PR, please add` "port-version": 1`, into the vcpkg.json file.

2022-12-07 07:04 UTC, dg0yt requested changes

2022-12-07 11:10 UTC, kvnp commented on ports/glib/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
It did not for me as can be seen in my log snippet, hence this PR. Maybe checking if glib-gettextize exists would be a better approach?

2022-12-07 12:00 UTC, dg0yt commented on ports/glib/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
>> I think it should also be installed for mingw triplets on windows hosts.
>
> It did not for me as can be seen in my log snippet, hence this PR. 

What I meant is that we should take control.

> Maybe checking if glib-gettextize exists would be a better approach?

No. It would be a workaround to make the glib build succeed, but random failures might pop up for ports or users which actually depend on `glib-gettextize`.

So we need to see how we can take control. (In the worst case, always remove it for mingw.)

FTR I could reproduce the problem. It will take a moment to find a better solution. From `meson.build` I see that it wants `sh` for this tool:
~~~
# Determine which user environment-dependent files that we want to install
have_bash = find_program('bash', required : false).found() # For completion scripts
bash_comp_dep = dependency('bash-completion', version: '>=2.0', required: false)
have_sh = find_program('sh', required : false).found() # For glib-gettextize
~~~
but config output is:
~~~
Program bash found: YES (C:\WINDOWS\system32\bash.EXE)
Run-time dependency bash-completion found: NO (tried pkgconfig and cmake)
Program sh found: NO
~~~
This is alarming: No sh, and another bash than the MSYS2 one normally used by vcpkg. I didn't know Windows has `C:\WINDOWS\system32\bash.EXE`, but it is connected to WSL.

2022-12-07 13:18 UTC, kvnp commented on ports/glib/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS)
> > It did not for me as can be seen in my log snippet, hence this PR.
> 
> What I meant is that we should take control.
> 
> > Maybe checking if glib-gettextize exists would be a better approach?
> 
> No. It would be a workaround to make the glib build succeed, but random failures might pop up for ports or users which actually depend on `glib-gettextize`.

I see. Thanks for clarifying!


> 
> This is alarming: No sh, and another bash than the MSYS2 one normally used by vcpkg. I didn't know Windows has `C:\WINDOWS\system32\bash.EXE`, but it is connected to WSL.

That's interesting! I think installing an msys2 environment and passing it's /bin directory to PATH would be a possible solution. I remember seeing some ports do something similar.

2022-12-08 07:05 UTC, dg0yt requested changes
Actually we don't need anything from msys for building this port and could just patch the condition in `tools/meson.build` (`if have_sh -> if true`).
OTOH the msys packages are already needed to build dependency gettext, so it is acceptable for me to avoid the patch.

2022-12-08 07:05 UTC, dg0yt commented on ports/glib/portfile.cmake
> -if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
This should be:
~~~
`if(VCPKG_HOST_IS_WINDOWS)`
~~~

2022-12-08 13:34 UTC, kvnp commented on ports/glib/portfile.cmake
> -if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
Replaced VCPKG_TARGET_IS_WINDOWS with VCPKG_HOST_IS_WINDOWS

2022-12-09 05:49 UTC, JonLiu1993 commented
Please run command "./vcpkg x-add-version glib --overwrite-version" and commit again.

2022-12-09 10:47 UTC, dg0yt commented
So now I have the solution I was looking for:
~~~diff
diff --git a/ports/glib/portfile.cmake b/ports/glib/portfile.cmake
index 4c7d6d406..ba4f4c288 100644
--- a/ports/glib/portfile.cmake
+++ b/ports/glib/portfile.cmake
@@ -34,8 +34,17 @@ if(VCPKG_TARGET_IS_WINDOWS)
     list(APPEND OPTIONS -Diconv=external)
 endif()

+vcpkg_list(SET ADDITIONAL_BINARIES)
+if(VCPKG_HOST_IS_WINDOWS)
+    # Presence of bash and sh enables installation of auxiliary components.
+    vcpkg_list(APPEND ADDITIONAL_BINARIES "bash = ['${CMAKE_COMMAND}', '-E', 'false']")
+    vcpkg_list(APPEND ADDITIONAL_BINARIES "sh = ['${CMAKE_COMMAND}', '-E', 'false']")
+endif()
+
 vcpkg_configure_meson(
     SOURCE_PATH "${SOURCE_PATH}"
+    ADDITIONAL_BINARIES
+        ${ADDITIONAL_BINARIES}
     OPTIONS
         ${OPTIONS}
         -Dgtk_doc=false
~~~

2022-12-15 00:04 UTC, kvnp commented
> So now I have the solution I was looking for:

That's an interesting feature of CMake I didn't know existed!

2022-12-15 02:16 UTC, JonLiu1993 commented
@kvnp, please fix the conflict files.

2022-12-15 06:05 UTC, dg0yt commented
@kvnp There was a glib update so you have to merge master, or rebase on top of it.

2022-12-20 08:01 UTC, JonLiu1993 commented
This is error log, please take a look:
````
FAILED: gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o 
/Library/Developer/CommandLineTools/usr/bin/cc -Igio/kqueue/libkqueue.a.p -Igio/kqueue -I../src/glib-2-802473e24b.clean/gio/kqueue -I. -I../src/glib-2-802473e24b.clean -Iglib -I../src/glib-2-802473e24b.clean/glib -Igmodule -I../src/glib-2-802473e24b.clean/gmodule -Igio -Igobject -I/Users/vagrant/Data/installed/x64-osx/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -O0 -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wunused -Wno-unused-parameter -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -O3 -DNDEBUG '-DG_LOG_DOMAIN="GLib-GIO"' '-DGIO_LAUNCH_DESKTOP="/Users/vagrant/Data/packages/glib_x64-osx/libexec/gio-launch-desktop"' '-DGIO_MODULE_DIR="/Users/vagrant/Data/packages/glib_x64-osx/lib/gio/modules"' '-DLOCALSTATEDIR="/Users/vagrant/Data/packages/glib_x64-osx/var"' -DGIO_COMPILATION -MD -MQ gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -MF gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o.d -o gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -c ../src/glib-2-802473e24b.clean/gio/kqueue/gkqueuefilemonitor.c
In file included from ../src/glib-2-802473e24b.clean/gio/kqueue/gkqueuefilemonitor.c:37:
In file included from ../src/glib-2-802473e24b.clean/gio/gfilemonitor.h:30:
In file included from ../src/glib-2-802473e24b.clean/gio/giotypes.h:30:
../src/glib-2-802473e24b.clean/gio/gioenums.h:31:10: fatal error: 'gio/gio-visibility.h' file not found
#include <gio/gio-visibility.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
````

2023-02-08 06:34 UTC, JonLiu1993 commented
Pinging @kvnp for response. Is work still being done for this PR?

2023-03-01 22:38 UTC, kvnp commented
> This is error log, please take a look:
> 
> ```
> FAILED: gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o 
> /Library/Developer/CommandLineTools/usr/bin/cc -Igio/kqueue/libkqueue.a.p -Igio/kqueue -I../src/glib-2-802473e24b.clean/gio/kqueue -I. -I../src/glib-2-802473e24b.clean -Iglib -I../src/glib-2-802473e24b.clean/glib -Igmodule -I../src/glib-2-802473e24b.clean/gmodule -Igio -Igobject -I/Users/vagrant/Data/installed/x64-osx/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -O0 -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wunused -Wno-unused-parameter -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -O3 -DNDEBUG '-DG_LOG_DOMAIN="GLib-GIO"' '-DGIO_LAUNCH_DESKTOP="/Users/vagrant/Data/packages/glib_x64-osx/libexec/gio-launch-desktop"' '-DGIO_MODULE_DIR="/Users/vagrant/Data/packages/glib_x64-osx/lib/gio/modules"' '-DLOCALSTATEDIR="/Users/vagrant/Data/packages/glib_x64-osx/var"' -DGIO_COMPILATION -MD -MQ gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -MF gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o.d -o gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -c ../src/glib-2-802473e24b.clean/gio/kqueue/gkqueuefilemonitor.c
> In file included from ../src/glib-2-802473e24b.clean/gio/kqueue/gkqueuefilemonitor.c:37:
> In file included from ../src/glib-2-802473e24b.clean/gio/gfilemonitor.h:30:
> In file included from ../src/glib-2-802473e24b.clean/gio/giotypes.h:30:
> ../src/glib-2-802473e24b.clean/gio/gioenums.h:31:10: fatal error: 'gio/gio-visibility.h' file not found
> #include <gio/gio-visibility.h>
>          ^~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```

This error shouldn't have occurred since this PR has no effect on Unix based environments. I would suggest to rerun the pipeline. Unfortunately, I don't have an OSX machine for further troubleshooting.

2023-03-02 02:42 UTC, JonLiu1993 commented
> > This is error log, please take a look:
> > ```
> > FAILED: gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o 
> > /Library/Developer/CommandLineTools/usr/bin/cc -Igio/kqueue/libkqueue.a.p -Igio/kqueue -I../src/glib-2-802473e24b.clean/gio/kqueue -I. -I../src/glib-2-802473e24b.clean -Iglib -I../src/glib-2-802473e24b.clean/glib -Igmodule -I../src/glib-2-802473e24b.clean/gmodule -Igio -Igobject -I/Users/vagrant/Data/installed/x64-osx/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -O0 -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wunused -Wno-unused-parameter -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -O3 -DNDEBUG '-DG_LOG_DOMAIN="GLib-GIO"' '-DGIO_LAUNCH_DESKTOP="/Users/vagrant/Data/packages/glib_x64-osx/libexec/gio-launch-desktop"' '-DGIO_MODULE_DIR="/Users/vagrant/Data/packages/glib_x64-osx/lib/gio/modules"' '-DLOCALSTATEDIR="/Users/vagrant/Data/packages/glib_x64-osx/var"' -DGIO_COMPILATION -MD -MQ gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -MF gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o.d -o gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -c ../src/glib-2-802473e24b.clean/gio/kqueue/gkqueuefilemonitor.c
> > In file included from ../src/glib-2-802473e24b.clean/gio/kqueue/gkqueuefilemonitor.c:37:
> > In file included from ../src/glib-2-802473e24b.clean/gio/gfilemonitor.h:30:
> > In file included from ../src/glib-2-802473e24b.clean/gio/giotypes.h:30:
> > ../src/glib-2-802473e24b.clean/gio/gioenums.h:31:10: fatal error: 'gio/gio-visibility.h' file not found
> > #include <gio/gio-visibility.h>
> >          ^~~~~~~~~~~~~~~~~~~~~~
> > 1 error generated.
> > ```
> 
> This error shouldn't have occurred since this PR has no effect on Unix based environments. I would suggest to rerun the pipeline. Unfortunately, I don't have an OSX machine for further troubleshooting.

You can send your modification plan. I will test it locally and provide you with feedback results. I have OSX machines.

2023-03-13 08:09 UTC, JonLiu1993 commented
Pinging @kvnp for response. Is work still being done for this PR?

2023-03-13 21:17 UTC, kvnp commented
> You can send your modification plan. I will test it locally and provide you with feedback results. I have OSX machines.

Does glib still build on OSX without the change in this PR?

2023-03-13 22:01 UTC, kvnp commented
Pushed some experimental commits just to rule out that setting additional binaries is the cause for the build failure on OSX. I hope it works this time.

2023-03-19 05:38 UTC, dg0yt requested changes
x64-windows error:
~~~
.\src\glib-2-8ca74e7d19.clean\meson.build:1:0: ERROR: Unknown options: "iconv"
~~~

2023-03-19 05:38 UTC, dg0yt commented on versions/g-/glib.json
>      },
You can add port-version 1, but you must not remove port-version 0.

2023-03-27 21:58 UTC, kvnp commented on versions/g-/glib.json
>      },
Something went wrong during the merge of master. Couldn't find a port-version 0 for 2.75.3.  It's included now after a rebase

2023-03-28 00:42 UTC, JonLiu1993 commented
@kvnp, Please run command `./vcpkg x-add-version glib --overwrite-version` and commit again.

2023-03-28 01:42 UTC, JonLiu1993 approved these changes

2023-03-28 18:00 UTC, merged