[elements] Add new port
microsoft/vcpkg pull request #28224
Opened 2022-12-07 16:57 UTC by ex-purple

**Describe the pull request**

- #### What does your PR fix?
  Add new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-12-11 19:29 UTC, ex-purple commented
@LilyWangLL , please check this request

2022-12-13 09:18 UTC, LilyWangLL commented
Thanks for your PR. I test install this port locally, but this port doesn't export library, could you also fix it?

2022-12-23 03:22 UTC, LilyWangLL commented
Ping @ex-purple for response.

2022-12-23 17:25 UTC, ex-purple commented
@LilyWangLL 
Sorry, I have not build environment for Windows and I have not experience with it.
What is the file extension and installation prefix for the export library?

2022-12-26 10:56 UTC, ex-purple commented
@LilyWangLL
I tried to fix problem with exports for dll, but I have not experience in Windows specific developments.
Can I disable this port for Windows until someone fixes this issue in future?

2022-12-27 08:38 UTC, JackBoosY commented
According to upstream code:
https://github.com/cycfi/elements/blob/edda9551b642ffa6a30059238a5fd1328b58fb29/lib/external/freetype/include/freetype/config/ftconfig.h#L462-L472

`DLL_EXPORT` may not be defined by the compiler, so I think we should double confirm that this macro was added in the compile commands.

2022-12-27 08:50 UTC, LilyWangLL requested changes

2022-12-27 08:50 UTC, LilyWangLL commented on ports/elements/portfile.cmake
> +vcpkg_from_github(
```suggestion
vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
```

2022-12-27 08:50 UTC, LilyWangLL commented on ports/elements/portfile.cmake
> +vcpkg_from_github(
```suggestion
vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
```

2022-12-27 08:50 UTC, LilyWangLL commented on ports/elements/portfile.cmake
> +endif()
```suggestion
if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
    file(GLOB ELEMENTS_LIBS "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/lib/*elements*")
    file(INSTALL ${ELEMENTS_LIBS} DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
endif()

if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
    file(GLOB ELEMENTS_LIBS "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/lib/*elements*")
    file(INSTALL ${ELEMENTS_LIBS} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
endif()
```

2022-12-27 08:50 UTC, LilyWangLL commented on ports/elements/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/README.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/README.md")
```

2022-12-27 08:50 UTC, LilyWangLL commented on ports/elements/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/lib/infra/include/infra DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```suggestion
file(INSTALL "${SOURCE_PATH}/lib/include/elements.hpp" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(INSTALL "${SOURCE_PATH}/lib/include/elements" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(INSTALL "${SOURCE_PATH}/lib/infra/include/infra" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
```

2022-12-27 09:39 UTC, ex-purple commented on ports/elements/portfile.cmake
> +vcpkg_from_github(
This is duplicate request

2022-12-27 09:48 UTC, dg0yt requested changes

2022-12-27 09:48 UTC, dg0yt commented on ports/elements/portfile.cmake
> +endif()
Attention, portfiles run in script mode. You must use:
~~~cmake
if(VCPKG_TARGET_IS_WINDOWS)
...
elseif(VCPKG_TARGET_IS_OSX)
...
~~~

2022-12-27 09:49 UTC, dg0yt commented on ports/elements/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
If this is just because of DLL export, you might perhaps wrap it into `if(VCPKG_TARGET_IS_WINDOWS)`.

2022-12-27 10:13 UTC, ex-purple commented on ports/elements/portfile.cmake
> +endif()
Thanks for the support

2022-12-27 10:13 UTC, ex-purple commented on ports/elements/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Done

2022-12-27 10:20 UTC, ex-purple commented
@LilyWangLL thanks a lot for your help. All changes except for the duplicate have been committed

2022-12-27 10:42 UTC, LilyWangLL approved these changes

2022-12-28 21:15 UTC, merged