Launchdarklyserver 2.8.6
microsoft/vcpkg pull request #28227
Opened 2022-12-07 20:28 UTC by blavallee

**Describe the pull request**

- #### What does your PR fix?
  Update launch-darkly-server to 2.8.6

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-12-08 03:14 UTC, MonicaLiu0311 commented
```
PS E:\launch> ./vcpkg install launch-darkly-server
...
launch-darkly-server provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(launch-darkly-server CONFIG REQUIRED)
    # note: 2 additional targets are not displayed.
    target_link_libraries(main PRIVATE ldserverapi::sha1 ldserverapi::hexify ldserverapi::semver ldserverapi::uthash)

```
The `usage` seems wrong, it should be as follows, please provide the `usage` file and put it in the `"${CURRENT_PACKAGES_DIR}/share/${PORT}"` directory.
```
find_package(launch-darkly-server CONFIG REQUIRED)
target_link_libraries(main PRIVATE ldserverapi::ldserverapi)
```

2022-12-27 07:53 UTC, MonicaLiu0311 commented
Pinging @blavallee 
 Can you address the review suggestions? Thanks!

2023-01-03 08:45 UTC, MonicaLiu0311 commented on ports/launch-darkly-server/usage
> +
A blank line at the end of the text is a format requirement.

2023-01-03 09:02 UTC, MonicaLiu0311 commented
![image](https://user-images.githubusercontent.com/110024546/210325944-2e0d91f1-4bd1-4afe-a132-d52d3b9cea07.png)

A blank line at the end of the text is a format requirement.
(It should be the impact of Tab spaces as shown in the figure below)

![image](https://user-images.githubusercontent.com/110024546/210326301-7d780c00-8dc6-482a-87d4-358fbbfb9dd6.png)

2023-01-04 02:56 UTC, MonicaLiu0311 approved these changes

2023-01-04 20:20 UTC, vicroms requested changes

2023-01-04 20:20 UTC, vicroms commented on ports/launch-darkly-server/portfile.cmake
> +        -DFETCHCONTENT_SOURCE_DIR_UTHASH=${UTHASH_SOURCE_DIR}
This should be converted into proper port dependencies instead of vendoring the source code. Otherwise, we risk causing link errors if another package also depends on one of these libraries.

2023-01-04 21:42 UTC, klalumiere commented on ports/launch-darkly-server/portfile.cmake
> +        -DFETCHCONTENT_SOURCE_DIR_UTHASH=${UTHASH_SOURCE_DIR}
All these libraries are included as `OBJECT` libraries (`add_library(target OBJECT ...)`) or header only library in the case of `UTHASH`:
-[HEXIFY](https://github.com/launchdarkly/c-server-sdk/blob/2.8.6/cmake/hexify.cmake#L14)
-[SEMVER](https://github.com/launchdarkly/c-server-sdk/blob/2.8.6/cmake/semver.cmake#L14)
-[SHA1](https://github.com/launchdarkly/c-server-sdk/blob/2.8.6/cmake/sha1.cmake#L12)
-[TIMESTAMP](https://github.com/launchdarkly/c-server-sdk/blob/2.8.6/cmake/timestamp.cmake#L14)
-[UTHASH](https://github.com/launchdarkly/c-server-sdk/blob/2.8.6/cmake/uthash.cmake#L12)

Hence, it's reasonably safe since the dependencies are not dynamically linked. Moreover, [hexify, semver and timestamp are patched with a custom launch-darkly-server patch](https://github.com/microsoft/vcpkg/pull/28227/files#diff-9e0dbeb1352392a75c0ddfa37c42fce66d13919f900ae3c5eb32a85f80128879R48). Hence, if we were to create new ports, we would need to also add the (custom launch-darkly-server) patches to the ports (if we want to use it with launch-darkly-server).

Also, the problem is not new. With the version `2.4.3`, launch-darkly-server included the source code of these dependencies directly ([copy-pasted in a `third-party` folder](https://github.com/launchdarkly/c-server-sdk/tree/release-release-2.4.3/third-party/src)). On version `2.8.6`, it uses `FetchContent`. We introduced this code as a workaround to the issue #28386, (`FETCHCONTENT_FULLY_DISCONNECTED`). Hence, as announced above, the issue you highlight is not new with this pull request, it is just more visible with the version `2.8.6` than it was with version `2.4.3` since `FetchContent` is used instead than just a copy of the dependencies source files directly checked-in the launch-darkly-server repository.

2023-01-09 18:35 UTC, blavallee commented on ports/launch-darkly-server/portfile.cmake
> +        -DFETCHCONTENT_SOURCE_DIR_UTHASH=${UTHASH_SOURCE_DIR}
@vicroms you can look at my colleague's answer just above

2023-01-09 18:55 UTC, vicroms approved these changes

2023-01-09 18:55 UTC, merged