Add wayland feature to glfw3 port
microsoft/vcpkg pull request #28232
Opened 2022-12-08 03:58 UTC by marinedalek

This PR adds a `wayland` feature to the glfw3 port to enable compilation targeting the Wayland display server.

- #### What does your PR fix?
  Fixes #28230 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
Unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
 Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-12-08 04:01 UTC, marinedalek commented
@microsoft-github-policy-service agree

2022-12-08 15:07 UTC, Neumann-A commented on ports/glfw3/vcpkg.json
> +    }
Please add the required port dependencies for this.

2022-12-08 15:24 UTC, Neumann-A commented on ports/glfw3/vcpkg.json
> +    }
https://github.com/microsoft/vcpkg/blob/master/ports/wayland/vcpkg.json and there is also `wayland-protocols`.

2022-12-13 01:50 UTC, marinedalek commented on ports/glfw3/vcpkg.json
> +    }
The empty ports `wayland`, `wayland-protocols`, `libxkbcommon`, and `ecm` currently build their dependencies unnecessarily, even when compilation is not forced. In addition, `pthread-stubs`, one of `libxkbcommon`'s transitive dependencies, does not build successfully on a clean install of Fedora. Upon initial failure, a diagnostic message is displayed instructing the user to install `autoconf` from the system package manager. However, a subsequent build attempt also fails with no such helpful message, requiring a dig into the logs and a web search to discover that `automake` is also required. 
Given these issues, I'd rather not add these dependencies at this time. Is that OK? As an alternative, I have modified the build message for linux builds with a link to the GLFW docs that list the required packages for Wayland compilation on a variety of distros. That change is now part of this pull request.

2022-12-29 06:37 UTC, Adela0814 submitted a review, later dismissed

2022-12-29 23:07 UTC, vicroms commented on ports/glfw3/vcpkg.json
> +    }
I have made PR #28628 to disable the extra dependencies when not actually building `wayland`. The same approach should be used for the other `X_VCPKG_[X|WAYLAND]_FORCE_VCPKG_LIBRARIES` and after that is done then we can add the dependencies on this port.

2023-01-10 23:10 UTC, vicroms commented on ports/glfw3/vcpkg.json
> +    }
#28628 has been merged so you should be able to declare the dependency on `wayland` and it won't build unnecessary dependencies anymore.

2023-01-10 23:11 UTC, vicroms requested changes

2023-01-10 23:11 UTC, vicroms commented on ports/glfw3/vcpkg.json
> +      "supports": "linux"
```suggestion
      "supports": "linux",
      "dependencies": [ "wayland" ]
```

2023-01-12 07:29 UTC, vicroms approved these changes

2023-01-12 07:29 UTC, merged