[Libvault] new port
microsoft/vcpkg pull request #28266
Opened 2022-12-09 14:01 UTC by alexander-smyslov

**Describe the pull request**

- #### What does your PR fix?
Libvault - new port 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all , sYes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes >

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-12-12 06:17 UTC, FrankXie05 requested changes

2022-12-12 06:17 UTC, FrankXie05 commented on ports/libvault/portfile.cmake
> +#vcpkg_cmake_config_fixup()
```suggestion
```

2022-12-12 06:53 UTC, FrankXie05 requested changes

2022-12-12 06:53 UTC, FrankXie05 commented on ports/libvault/portfile.cmake
> +        0001-fix-dependencies.patch
Test the usage and error log:
```
CMake Error at vcpkg/installed/x64-windows/share/libvault/libvaultTargets.cmake:60 (set_target_properties): 
  The link interface of target "libvault::vault" contains:

  CURL::libcurl

 but the target was not found.  Possible reasons include: 
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

    Call Stack (most recent call first):
    vcpkg/installed/x64-windows/share/libvault/libvaultConfig.cmake:27 (include)  
    vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
```

2022-12-12 09:35 UTC, alexander-smyslov commented on ports/libvault/portfile.cmake
> +        0001-fix-dependencies.patch
@FrankXie05 not clear for me where you see this error...

2022-12-13 02:17 UTC, FrankXie05 commented on ports/libvault/portfile.cmake
> +        0001-fix-dependencies.patch
I build a simple cmake project to test the provided usage of the port:
```
libvault provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(libvault CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libvault::vault)
```
We need `find_depedency(curl)`.

2023-02-24 07:38 UTC, FrankXie05 requested changes

2023-04-14 05:15 UTC, BillyONeal commented on ports/libvault/usage
> +    find_package(CURL CONFIG REQUIRED)
To clarify: The CMake configs installed by the port need to contain a call to `find_dependency` to make the corresponding curl targets available, rather than requiring users to know the entire universe of transitive dependencies before doing anything. See https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html

2023-04-14 13:11 UTC, dg0yt commented on ports/libvault/usage
> +The package @PORT@:@TARGET_TRIPLET@ provides CMake targets:
Keep this simple. There should be uniform usage across all triplets:
~~~
libvault provides CMake targets:
~~~

2023-04-26 06:36 UTC, BillyONeal commented on ports/libvault/usage
> +    find_package(CURL CONFIG REQUIRED)
This was marked resolved but I still don't see a `find_dependency` call added anywhere here...

2023-04-26 08:38 UTC, FrankXie05 requested changes

2023-04-26 08:38 UTC, FrankXie05 commented on ports/libvault/usage
> +    find_dependency(CURL)
It should be called in `cmake` config file not usage.

2023-05-01 19:29 UTC, BillyONeal commented
I think https://github.com/BillyONeal/vcpkg/commit/bc7b8b2d2833e6165af24498ebc1b4ac2538d40d implements the correct find_dependency call.

2023-05-02 10:13 UTC, alexander-smyslov commented
@BillyONeal Thanks

2023-05-02 17:38 UTC, BillyONeal commented
> @BillyONeal Thanks

Are you OK with those changes? I can push them into your branch for you.

2023-05-02 17:52 UTC, alexander-smyslov commented
@BillyONeal Please push your changes in my branch

2023-05-02 17:58 UTC, BillyONeal approved these changes

2023-05-02 17:59 UTC, BillyONeal commented
Thanks!

2023-05-08 07:06 UTC, FrankXie05 approved these changes

2023-05-08 17:07 UTC, merged