[sail] Update to 0.9.0-rc2
microsoft/vcpkg pull request #28402
Opened 2022-12-17 23:05 UTC by HappySeaFox

**Describe the pull request**

- #### What does your PR fix?
  Fixes compilation issues

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Same

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2022-12-19 09:00 UTC, JonLiu1993 requested changes

2022-12-19 09:00 UTC, JonLiu1993 commented on ports/sail/vcpkg.json
> -            "xbm"
@HappySeaFox, Thanks for your pr, could you explain why these features were removed?

2022-12-19 15:58 UTC, HappySeaFox commented on ports/sail/vcpkg.json
> -            "xbm"
I updated the `all` feature to include other "container" features instead of specific features. This way the `all` feature is more maintainable and requires less updates in the future. Once I add a new codec in the future, it will be automatically included into the `all` feature.

2022-12-20 06:29 UTC, JonLiu1993 approved these changes

2022-12-20 06:56 UTC, JonLiu1993 commented
@HappySeaFox, when I tested the features by command "./vcpkg install sail[all]" I got this error.
Please take a look: 
````
FAILED: CMakeFiles/aom_av1_common_sse4_intrinsics.dir/av1/common/x86/cdef_block_sse4.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse4_intrinsics.dir\av1\common\x86\cdef_block_sse4.c.obj /FdCMakeFiles\aom_av1_common_sse4_intrinsics.dir\ /FS -c F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse4.c
F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(775) : fatal error C1002: compiler is out of heap space in pass 2
[347/402] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /arch:AVX2 /showIncludes /FoCMakeFiles\aom_av1_common_avx2_intrinsics.dir\av1\common\x86\cdef_block_avx2.c.obj /FdCMakeFiles\aom_av1_common_avx2_intrinsics.dir\ /FS -c F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_avx2.c
FAILED: CMakeFiles/aom_av1_common_avx2_intrinsics.dir/av1/common/x86/cdef_block_avx2.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /arch:AVX2 /showIncludes /FoCMakeFiles\aom_av1_common_avx2_intrinsics.dir\av1\common\x86\cdef_block_avx2.c.obj /FdCMakeFiles\aom_av1_common_avx2_intrinsics.dir\ /FS -c F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_avx2.c
F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(292) : fatal error C1002: compiler is out of heap space in pass 2
[348/402] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse2_intrinsics.dir\av1\common\x86\cdef_block_sse2.c.obj /FdCMakeFiles\aom_av1_common_sse2_intrinsics.dir\ /FS -c F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse2.c
FAILED: CMakeFiles/aom_av1_common_sse2_intrinsics.dir/av1/common/x86/cdef_block_sse2.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse2_intrinsics.dir\av1\common\x86\cdef_block_sse2.c.obj /FdCMakeFiles\aom_av1_common_sse2_intrinsics.dir\ /FS -c F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse2.c
F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(775) : fatal error C1002: compiler is out of heap space in pass 2
F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(292) : fatal error C1002: compiler is out of heap space in pass 2
[349/402] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_ssse3_intrinsics.dir\av1\common\x86\cdef_block_ssse3.c.obj /FdCMakeFiles\aom_av1_common_ssse3_intrinsics.dir\ /FS -c F:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_ssse3.c
FAILED: CMakeFiles/aom_av1_common_ssse3_intrinsics.dir/av1/common/x86/cdef_block_ssse3.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\sail\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\sail\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-te [...]

2022-12-20 07:07 UTC, HappySeaFox commented
>compiler is out of heap space in pass 2

AOM port cannot be compiled on your machine. I'm not sure how to reduce the number of compilation jobs in vcpkg, but single-threaded compilation may help. It's a good idea to file a feature request if vcpkg doesn't support that .

2022-12-20 08:56 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x64-windows
- x64-windows-static

2022-12-20 17:23 UTC, merged