Pangolin
microsoft/vcpkg pull request #28492
Opened 2022-12-22 11:31 UTC by Sibras

Multiple features were removed as the newer version has moved them from being selectable to always being built. As such eigen3 is now a hard dependency and no longer selectable as part of feature dependencies.

This is required to support using newer versions of ffmpeg (5.0+)

See PR [#23312](https://github.com/microsoft/vcpkg/pull/23312)

2022-12-23 07:49 UTC, JonLiu1993 requested changes

2022-12-23 07:49 UTC, JonLiu1993 commented on ports/pangolin/portfile.cmake
> -        fix-dependencies.patch
@Sibras, thanks for the pr, we should also delete the patch files in the folder if the patches are no longer needed.

2022-12-23 07:49 UTC, JonLiu1993 commented on ports/pangolin/portfile.cmake
>  file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)

```

2022-12-23 07:49 UTC, JonLiu1993 commented on ports/pangolin/portfile.cmake
>  file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
Add a blank line at the end to ensure that it is consistent with the previous format.

2022-12-23 12:37 UTC, Sibras commented on ports/pangolin/portfile.cmake
>  file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
The previous format didnt have a newline according to git diff

2022-12-23 16:19 UTC, quyykk commented on ports/pangolin/portfile.cmake
>  file(INSTALL "${SOURCE_PATH}/LICENCE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2022-12-26 05:25 UTC, JonLiu1993 submitted a review, later dismissed

2022-12-26 05:34 UTC, JonLiu1993 commented
@Sibras, when I tested the features by command "./vcpkg install pangolin[*]:x86-windows" I got this error, please take a look:
````
Could not find video in pangolin.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
````

2022-12-26 11:40 UTC, Sibras commented
> @Sibras, when I tested the features by command "./vcpkg install pangolin[*]:x86-windows" I got this error, please take a look:
> 
> ```
> Could not find video in pangolin.
> note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
> ```

There was an issue with tools feature that is now fixed.

2022-12-27 08:48 UTC, JonLiu1993 submitted a review, later dismissed

2022-12-27 08:51 UTC, JonLiu1993 commented
Expect feature ''uvc", all features are tested successfully in the following triplet:
- x86-windows
- x64-windows

2022-12-27 08:55 UTC, dg0yt requested changes
This PR removes features. It can break upgrades for users which depend on these features. Alternative:
Keep the features as no-ops.

2022-12-29 05:45 UTC, Sibras commented
> This PR removes features. It can break upgrades for users which depend on these features. Alternative: Keep the features as no-ops.

OK Ive added the removed features back to the vcpkg.json file

2022-12-29 06:55 UTC, JonLiu1993 commented
> pangolin

@Sibras, If you restore that code, we will also encounter the same problem before, the `vedio` feature cannot be tested

2022-12-29 08:59 UTC, Sibras commented
OK so should I keep the features as no-ops as suggested or remove them entirely as initially done?

2022-12-29 11:51 UTC, dg0yt commented
> > > when I tested the features by command "./vcpkg install pangolin[*]:x86-windows" I got this error, please take a look:
> > > 
> > > ```
> > > Could not find video in pangolin.
> > > note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
> > > ```
> >
> > If you restore that code, we will also encounter the same problem before, the `vedio` feature cannot be tested

No.

> should I keep the features as no-ops as suggested or remove them entirely as initially done?

You must keep the no-op features. 

Ironically, this problem was actually caused by the removal of feature `video` while it was still used as a dependency. 
User may have a dependency on `pangolin[video]`, so will get that problem when the feature is not kept.

2022-12-30 07:10 UTC, JonLiu1993 approved these changes

2022-12-30 08:22 UTC, vicroms requested changes

2022-12-30 08:22 UTC, vicroms commented on ports/pangolin/vcpkg.json
> +      "description": "Unused option left for backwards compatibility with older versions"
It should be OK to remove these features entirely.

2022-12-30 08:32 UTC, dg0yt commented on ports/pangolin/vcpkg.json
> +      "description": "Unused option left for backwards compatibility with older versions"
And break `vcpkg upgrade`?

2022-12-30 10:04 UTC, vicroms commented on ports/pangolin/vcpkg.json
> +      "description": "Unused option left for backwards compatibility with older versions"
You're right, I forgot about `vcpkg upgrade`... @ras0219-msft and @BillyONeal what do you think?

2022-12-30 10:32 UTC, dg0yt commented on ports/pangolin/vcpkg.json
> +      "description": "Unused option left for backwards compatibility with older versions"
Note the previous comments in this PR ...

2022-12-31 09:33 UTC, vicroms approved these changes

2022-12-31 09:33 UTC, merged