[aubio] Update to latest master.
microsoft/vcpkg pull request #28491
Opened 2022-12-22 11:25 UTC by Sibras

This is required to support using newer versions of ffmpeg (5.0+)

See PR [#23312](https://github.com/microsoft/vcpkg/pull/23312)

2022-12-23 02:40 UTC, FrankXie05 requested changes

2022-12-23 02:40 UTC, FrankXie05 commented on ports/aubio/portfile.cmake
> +    REF 8a05420e5dd8c7b8b2447f82dc919765876511b3
Do we have to update to the master branch?
Could you please request a new version upstream?

2022-12-23 12:40 UTC, Sibras commented on ports/aubio/portfile.cmake
> +    REF 8a05420e5dd8c7b8b2447f82dc919765876511b3
The last time aubio had a tagged released was nearly 4 years ago, so it doesnt see alot of maintenance, hence just bumping to master here

2022-12-23 12:44 UTC, Sibras commented on ports/aubio/portfile.cmake
> +    REF 8a05420e5dd8c7b8b2447f82dc919765876511b3
Since this is a blocker for ffmpeg getting bumped to 5.0 (which has already been waiting for 10 months) this seemed like the fastest way to get it unblocked

2022-12-26 01:24 UTC, FrankXie05 approved these changes

2022-12-28 20:59 UTC, merged