[entt, libharu, libopensp, minizip, smf, vlpp, vulkan-headers] Fix incorrect versions
microsoft/vcpkg pull request #28571
Opened 2022-12-27 01:19 UTC by njakob

**Describe the pull request**

- #### What does your PR fix?
  While working on [vcpkg.link](https://vcpkg.link/), I realized that some ports' versions point to invalid git trees. Therefore, this PR fixes these different issues.
 
  I'm not sure what practices are in place when it comes to updating the version files when they contain mistakes. Moreover, some of these fixes also include removing a version when it seems they have been introduced by mistake in a single PR.
  
  Semi-related to this PR, https://github.com/microsoft/vcpkg/issues/27451 suggests using `git blame` in order to get the history of a port. While changing the file would alter this history, using `git blame` already doesn't provide any data before the introduction of the versions files. In other words, vcpkg does not and should not rely on `git blame` for simulating this functionality.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Support was not changed, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  N/A

2022-12-27 01:21 UTC, njakob commented
@microsoft-github-policy-service agree

2022-12-27 01:22 UTC, njakob commented on versions/e-/entt.json
> -    {
Version `3.10.0` is duplicated with different git trees. The duplication has been introduced by https://github.com/microsoft/vcpkg/pull/24581 ([1](https://github.com/microsoft/vcpkg/pull/24581/files#diff-6ddc4d1880410064c385d27685c026087f1a2e4a29de0e7bfb9c9274205afe81R9-R12)) and seems to be safe to be removed.

2022-12-27 01:28 UTC, njakob commented on versions/l-/libharu.json
> -      "git-tree": "bfeaf0d13fce9156ac216daa37a2c945290fc0ed",
This has been introduced by https://github.com/microsoft/vcpkg/pull/25613 ([1](https://github.com/microsoft/vcpkg/pull/25613/files#diff-d942ca2b50ce9a300d973cf26402432c1be67f2bf414197676ed86013f14dbdeR3-R7)) as most likely a mistake since the PR is about `boost-build`.

Simply updated the git tree with the previous version since something got changed.

We could also simply remove the version completely.

2022-12-27 01:30 UTC, njakob commented on versions/l-/libopensp.json
> -      "git-tree": "4b7d728266ee8b4e03f27a619cbf9efc9484cbb6",
The git tree got changed by mistake in https://github.com/microsoft/vcpkg/pull/26382 ([1](https://github.com/microsoft/vcpkg/pull/26382/files#diff-00c1774d75badd67a7eb0a385d036117e257cb6612d10f4f3df6babbbfd24cc2R9)).

This reverts the original git tree of `1.5.2#0` while keeping the `1.5.2#1` version.

2022-12-27 01:33 UTC, njakob commented on versions/m-/minizip.json
> -      "git-tree": "65a32bfac58033a215e271db94d5e022fce816e3",
It seems that `1.2.12#0` got introduced by mistake in https://github.com/microsoft/vcpkg/pull/27226 ([1](https://github.com/microsoft/vcpkg/pull/27226/files#diff-4e953389a5a3e2522c76eec6e0b42ba11205c12d7615d347d56261d2ea369651R9-R12)).

The fix simply uses the git tree of `1.2.13#0`.

We could also simply remove the version completely.

2022-12-27 01:34 UTC, njakob commented on versions/s-/smf.json
> -    {
The port has been added with both `0.1.0#0` and `0.1.1#0` through https://github.com/microsoft/vcpkg/pull/28162 ([1](https://github.com/microsoft/vcpkg/pull/28162/files#diff-fe7fd55c2d98f71ca97c37b7f24ce8d8f6b0cecd85474781689eabafd7d0b3f7R9-R12)).

Since the PR specifies adding `0.1.1`, the faulty version simply got removed.

2022-12-27 01:37 UTC, njakob commented on versions/v-/vlpp.json
> -    {
The version `0.11.0.0#4` mostly likely added by mistake by https://github.com/microsoft/vcpkg/pull/26887 ([1](https://github.com/microsoft/vcpkg/pull/26887/files#diff-76de0b07f080da1bb7ee433fb82e923d5912de9071a5df2ffb6b8e69493d65cfR9-R12)) since `1.1.0.0#0` was added on the same PR.

The version pointing to the invalid git tree got removed.

2022-12-27 01:40 UTC, njakob commented on versions/v-/vulkan-headers.json
> -    {
The version `1.3.233#0` was most likely added by mistake in https://github.com/microsoft/vcpkg/pull/27746 ([1](https://github.com/microsoft/vcpkg/pull/27746/files#diff-2d4b263397385974512204ffc3561f83f78b114de42e0609b4cd527117ad2ae8R9-R11)) since the PR clearly references `1.3.234`.

Therefore, the version pointing to an invalid git tree got removed.

2022-12-27 02:29 UTC, FrankXie05 submitted a review, later dismissed

2022-12-27 08:15 UTC, Thomas1664 commented
@njakob out of curiosity, how did you find those incorrect versions? There already is a GitHub bot that makes sure the version database is updated correctly but as you have seen, there are ways to fool the bot.

2022-12-27 09:14 UTC, dg0yt commented
\<off-topic>
@njakob On vcpkg.link:
"No license" is displayed when a port manifest has `"license": null`. IMO this is misleading. These ports do have license terms. They are just too complex to be expressed in the SPDX license field, or strongly depend on selected features. 
Example: [gdal](https://vcpkg.link/ports/gdal)
Suggestion: Display "Complex license" or similar. 
Reference: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#license 
\</off-topic>

2022-12-27 10:47 UTC, njakob commented
> @njakob out of curiosity, how did you find those incorrect versions? There already is a GitHub bot that makes sure the version database is updated correctly but as you have seen, there are ways to fool the bot.

That's a good question! Since this should have been part of the PR description, I added some details on how I did find these broken versions.

First of all, I haven't checked in detail how the [bot is generating suggestions](https://github.com/microsoft/vcpkg/blob/master/.github/workflows/untrustedPR.yml#L51). However, it seems we're not performing an integrity check of the changed versions file.

We could imagine adding a separate GitHub action performing a `git ls-tree` of each entry of the changed files. This way we would catch such cases before they get merged into master and keep the existing suggestion system.

I could take a look at this in the following days if that's something you believe could be valuable!

2022-12-27 11:12 UTC, njakob commented
> <off-topic> @njakob On vcpkg.link: "No license" is displayed when a port manifest has `"license": null`. IMO this is misleading. These ports do have license terms. They are just too complex to be expressed in the SPDX license field, or strongly depend on selected features. Example: [gdal](https://vcpkg.link/ports/gdal) Suggestion: Display "Complex license" or similar. Reference: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#license </off-topic>

That's very valuable feedback @dg0yt, I have not considered this case and missed the meaning of the `null` value. Your idea to use a different terminology makes a lot of sense!

Quickly [searching over the repository](https://github.com/microsoft/vcpkg/search?l=Text&q=copyright), it seems we also have cases with a license file without any indication in the manifest (e.g. [vulkan](https://github.com/microsoft/vcpkg/tree/master/ports/vulkan)). I'm wondering if we should somehow either always add the "complex license" as part of the port or enable contributors to specify an external URL for it. This, however, deserves its own issue to be discussed and tracked.

I'll make sure to address the issue you raised @dg0yt today!

2023-01-02 05:45 UTC, vicroms commented
There is an existing `--verify-git-trees` flag that checks for consistency in the version database. I'm working on some changes to enable it on every PR run, but in its current implementation is too costly to run.

2023-01-02 05:56 UTC, vicroms requested changes
I ran `./vcpkg x-ci-verify-versions --verify-git-trees` on this PR. 

The errors on `abseil`, `blend2d` and `libwebp` are known from #24277 but `libharu` and `minizip` have incorrect fixes on this PR.

2023-01-02 05:56 UTC, vicroms commented on versions/l-/libharu.json
> -      "git-tree": "bfeaf0d13fce9156ac216daa37a2c945290fc0ed",
We should find the proper SHA for version `2017-08-15` if it exsits.

```
Error: While reading versions for port libharu from file: /workspaces/vcpkg/versions/l-/libharu.json
       While validating version: 2017-08-15#11.
       The version declared in file does not match checked-out version: 2017-08-15#10
       Checked out Git SHA: 312f4b697d2f46818c218e270bd447cdeb76322c
```

2023-01-02 14:17 UTC, njakob reviewed
Thank you for having a look @vicroms and pointing out `./vcpkg x-ci-verify-versions --verify-git-trees`, I was not aware of this command!

Looking quickly at the [current implementation](https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/commands.civerifyversions.cpp), we could imagine only validating files that change in PRs instead of every single port.

Regarding the two new errors you raised for `libharu` and `minizip`, I simply removed the version entries since we do not have any git tree with a matching package and port version.

2023-01-02 14:17 UTC, njakob commented on versions/l-/libharu.json
> -      "git-tree": "bfeaf0d13fce9156ac216daa37a2c945290fc0ed",
While checking the [history of this port](https://github.com/microsoft/vcpkg/commits/master/ports/libharu), it seems we do not have a valid git tree for `2017-08-15#11`: We move from `2017-08-15#10` (https://github.com/microsoft/vcpkg/pull/19979) to `2.4.0-rc1#0` (https://github.com/microsoft/vcpkg/pull/25569) directly. Therefore, I simply removed the version entry.

2023-01-02 14:17 UTC, njakob commented on versions/m-/minizip.json
> -      "git-tree": "65a32bfac58033a215e271db94d5e022fce816e3",
Since pointing to different manifest or control files with different package and port versions trigger validation errors when running `./vcpkg x-ci-verify-versions --verify-git-trees`, the version was removed.

2023-01-04 22:39 UTC, vicroms approved these changes

2023-01-04 22:39 UTC, merged

2023-01-04 22:40 UTC, vicroms commented
Thanks for the PR!

2023-01-11 15:28 UTC, gharwo commented
Related to this, in the process of trying to establish a maintenance branch for our code consuming libharu at version 2017-08-15#10, I seem to have come across issue 25518, which was fixed by PR2553. The problem appears to be that the fix is the removal of the TIFF symbols and not fixing the original hash:
 
url : [ https://github.com/libharu/libharu/pull/157.diff ]
1>       File path : [ C:\Users\<user>\AppData\Local\Programs\vcpkg\downloads\libharu-shading-pr-157.patch.28904.part ]
1>   Expected hash : [ f2ddb22b54b4eccc79400b6a4b2d245a221898f75456a5a559523eab7a523a87dfc5dfd0ec5fb17a771697e03c7ea6ed4c6095eff73e0a4302cd6eb24584c957 ]
1>     Actual hash : [ 10562c8c9c6975b74d625912e7d3b850376941d5e46136679371ce1315f416b6b8e91d73fd1257b907327b2d71d50b8c026547203f280e42fb7b1901245de03c ] 

This means building the versions prior to the fix still produce the hash error. I hope I've understood this correctly. This is on a fresh install of vcpkg and after doing a git pull.

2023-01-11 18:34 UTC, vicroms commented
@gharwo 

The SHA `bfeaf0d13fce9156ac216daa37a2c945290fc0ed` is invalid in a local clone of vcpkg, and because of that, removing them from the version database was the right thing to do. 

However, since vcpkg keeps the PR refs around (and thus the git objects), one can obtain the files for that specific SHA from GitHub via `https://github.com/Microsoft/vcpkg/archive/bfeaf0d13fce9156ac216daa37a2c945290fc0ed.zip`.

If you must take that version and cannot upgrade the port, then you should download the port files form the URL provided above and create a port overlay for `libharu`.

2023-01-11 19:26 UTC, dg0yt commented
@vicroms @gharwo The problem in https://github.com/microsoft/vcpkg/pull/28571#issuecomment-1378949538 is the occassional vcpkg habbit of downloading diffs from other repos instead of committing them to vcpkg. You will always get a valid diff from GH, but it is not binary stable over time. So SHA512 checks can fail after some time.

The variable part in the downloaded diffs ist the format of the index lines. Example for the given diff:
original: `index 44b816c..60b1d84 100644`
current: `index 44b816c2..60b1d847 100644`

A regex substitution e.g. in VS Code transforms the download from the actual hash to the expected hash: (Hey, I produced a SHA512 collission ;-)
`(^index .......).(\.\........).` -> `$1$2`

2023-01-12 12:29 UTC, gharwo commented
OK. Thanks for the hint. I'll see how I get on.

On Wed, 11 Jan 2023 at 18:34, Victor Romero ***@***.***>
wrote:

> @gharwo <https://github.com/gharwo>
>
> The SHA bfeaf0d13fce9156ac216daa37a2c945290fc0ed is invalid in a local
> clone of vcpkg, and because of that, removing them from the version
> database was the right thing to do.
>
> However, since vcpkg keeps the PR refs around (and thus the git objects),
> one can obtain the files for that specific SHA from GitHub via
> https://github.com/Microsoft/vcpkg/archive/bfeaf0d13fce9156ac216daa37a2c945290fc0ed.zip
> .
>
> If you must take that version and cannot upgrade the port, then you should
> download the port files form the URL provided above and create a port
> overlay for libharu.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/28571#issuecomment-1379319247>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXENQ5YVA5RLUPUBAGLI4UTWR34LFANCNFSM6AAAAAATKAF2II>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-18 09:05 UTC, gharwo commented
Pulling that specific PR ref worked perfectly and enabling the overlay port in vcpkg-configuration embedded in vcpkg.json of the maintenance branch means less churn for maintenance releases. Thanks.