[staticjson] add new port.
microsoft/vcpkg pull request #28578
Opened 2022-12-27 12:42 UTC by netheril96

**Describe the pull request**

- #### What does your PR fix?
   Add a new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2022-12-28 06:02 UTC, Adela0814 requested changes

2022-12-28 06:02 UTC, Adela0814 commented on ports/staticjson/vcpkg.json
> +  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
This is unnecessary.

2022-12-28 08:23 UTC, netheril96 commented on ports/staticjson/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Done

2022-12-28 08:26 UTC, netheril96 commented on ports/staticjson/vcpkg.json
> +  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
It's helpful for autocompletion when editing this file in an IDE. And it is recommended [here](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#simple-example-manifest).

2022-12-28 08:44 UTC, Adela0814 submitted a review, later dismissed

2022-12-28 10:20 UTC, njakob commented on versions/s-/staticjson.json
> +      "port-version": 0
You might double-check these since we should have only one version entry (see https://github.com/microsoft/vcpkg/pull/28571)

2022-12-28 10:47 UTC, netheril96 commented on versions/s-/staticjson.json
> +      "port-version": 0
Done.

2022-12-28 10:57 UTC, dg0yt requested changes

2022-12-28 10:57 UTC, dg0yt commented on ports/staticjson/portfile.cmake
> +    REF v1.0.0
Suggesting `"v${VERSION}"`.

2022-12-28 10:57 UTC, dg0yt commented on ports/staticjson/portfile.cmake
> +vcpkg_cmake_configure(SOURCE_PATH ${SOURCE_PATH} OPTIONS -DSTATICJSON_ENABLE_TEST=OFF)
For future maintenance, use the following formatting and quoting:
~~~cmake
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DSTATICJSON_ENABLE_TEST=OFF
)
~~~

2022-12-28 11:07 UTC, netheril96 commented on ports/staticjson/portfile.cmake
> +    REF v1.0.0
Done

2022-12-28 11:07 UTC, netheril96 commented on ports/staticjson/portfile.cmake
> +vcpkg_cmake_configure(SOURCE_PATH ${SOURCE_PATH} OPTIONS -DSTATICJSON_ENABLE_TEST=OFF)
Done

2022-12-28 11:10 UTC, njakob approved these changes, later dismissed
Thank you for addressing the issue in the version file @netheril96!

2022-12-28 20:26 UTC, vicroms requested changes
Looks good to me once the review comment has been addressed.

2022-12-28 20:26 UTC, vicroms commented on ports/staticjson/portfile.cmake
> +    REF "v${VERSION}"
Since you're using `${VERSION}` this needs a [`vcpkg_minimum_required(VERSION 2022-12-28)`](https://learn.microsoft.com/vcpkg/maintainers/functions/vcpkg_minimum_required) at the top of the portfile.

2022-12-29 01:34 UTC, netheril96 commented on ports/staticjson/portfile.cmake
> +    REF "v${VERSION}"
Why do we need this? I can install the port with the line `REF "v${VERSION}"` with vcpkg 2022-11-10 just fine.

2022-12-29 06:57 UTC, dg0yt commented on ports/staticjson/portfile.cmake
> +    REF "v${VERSION}"
The variable came with `2022-10-12`.

2022-12-29 08:14 UTC, netheril96 commented on ports/staticjson/portfile.cmake
> +    REF "v${VERSION}"
Added minimum requirement for 2022-10-12 instead.

2022-12-29 19:41 UTC, vicroms approved these changes

2022-12-29 19:41 UTC, merged