[opentracing] Fix library linkage
microsoft/vcpkg pull request #28606
Opened 2022-12-29 00:05 UTC by Thomas1664

**Describe the pull request**

- #### What does your PR fix?
  Port did only support dynamic linkage

2022-12-29 10:19 UTC, dg0yt requested changes

2022-12-29 10:19 UTC, dg0yt commented on ports/jaeger-client-cpp/fix-CMakeLists.patch
> + endif()
This seems to miss changing `OPENTRACING_LIB`.
Wouldn't it be easier to change `if(WIN32)` to `if(TARGET OpenTracing::opentracing)` ?

2022-12-29 10:19 UTC, dg0yt commented on ports/opentracing/fix-cmake.patch
> ++endif()
What is the purpose of this change? The CPack stuff and even the output_directory shouldn't have an effect on a regular build/install.

2022-12-29 13:52 UTC, Thomas1664 commented on ports/jaeger-client-cpp/fix-CMakeLists.patch
> + endif()
> This seems to miss changing OPENTRACING_LIB.

This variable is only used for unit testing which is disabled. Using `if(TARGET OpenTracing::opentracing)` would be a lot easier, thanks for this suggestion!

2022-12-29 14:16 UTC, Thomas1664 commented on ports/opentracing/fix-cmake.patch
> ++endif()
> What is the purpose of this change? The CPack stuff and even the output_directory shouldn't have an effect on a regular build/install.

Improved configure time without this change, installing this port on WSL2 takes 3,05 min vs. 1,75 min with this change. IMO this is significant performance increase justifies keeping this part of the patch. This was also the initial reason why I expanded the `if(0)` to CPack. But you are right in that it has no influence on the resulting build.

2022-12-29 14:35 UTC, dg0yt commented on ports/opentracing/fix-cmake.patch
> ++endif()
The difference in time is significant. But the only non-trivial command in these lines is `include(CPack)`. So it should be enough to remove this line.
And if the difference is confirmed to be with this package, it might make sense to generally provide a custom no-op `CPack.cmake`, because ports shouldn't call the targets it creates. However, some users might disagree with overriding a default CMake behaviour, so it may need to be handled with care.

2023-02-08 06:45 UTC, JonLiu1993 commented
Pinging @Thomas1664 for response. Is work still being done for this PR?

2023-02-11 14:26 UTC, Thomas1664 commented
I think there needs to be a discussion on how to get rid of `CPack` and if we want to get rid of it in the first place.

2023-02-11 14:44 UTC, dg0yt commented
What is the problem with the CPack stuff? Usually it is only creating additional targets which we don't need to use.

2023-03-13 08:12 UTC, JonLiu1993 commented
Pinging @Thomas1664 for response. Is work still being done for this PR?

2023-03-16 10:26 UTC, Thomas1664 commented
@JonLiu1993 Ready for review!

2023-03-16 10:44 UTC, JonLiu1993 approved these changes

2023-03-17 20:02 UTC, merged