[zfp] update to 1.0.0
microsoft/vcpkg pull request #28616
Opened 2022-12-29 10:44 UTC by JonLiu1993

Fix #28574 

Update zfp to the latest version 1.0.0.
Modernize the portfile.cmake file

All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2022-12-29 11:40 UTC, dg0yt requested changes
I know it is a draft PR but I want to record some early comments.

2022-12-29 11:40 UTC, dg0yt commented on ports/zfp/vcpkg.json
> +  "version": "0.5.5",
You missed to update this to 1.0.0...

2022-12-29 11:40 UTC, dg0yt commented on versions/z-/zfp.json
> +    },
... and now we have a strange sequence here.

2022-12-29 11:40 UTC, dg0yt commented on ports/zfp/portfile.cmake
> +endif()
I assume the tool exists also for static builds. But the `bin` dir is already removed at this point.

Doesn't  the utility feature build any tools?

2022-12-29 11:40 UTC, dg0yt commented on ports/zfp/portfile.cmake
>  endif()
This where we loose the tools for static builds. This explicitly removal shouldn't be needed if we use `vcpkg_copy_tools(... AUTO_CLEAN)`  correctly. However, we may need to construct a list of tools depending on actual features.

2022-12-29 11:41 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> ++    RUNTIME DESTINATION tools)
Multiple targets could be installed in a single command.

2022-12-30 04:35 UTC, JonLiu1993 commented on ports/zfp/portfile.cmake
> +endif()
`zfpcmd.exe` is built from utilities

2023-02-06 20:10 UTC, aavbsouza commented
Any news on this issue ?

2023-02-07 02:30 UTC, MonicaLiu0311 commented
Ping @JonLiu1993

2023-02-07 06:28 UTC, dg0yt requested changes
Maybe the 1.0.0. release is an opportunity to trim the port's patching?

2023-02-07 06:28 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> + endif()
Does have `BUILD_ALL` any other effects than these? If not, `BUILD_ALL` shouldn't be used, the patch chunk should be removed, and these options should be controlled directly be feature `all`.

2023-02-07 06:28 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> ++    RUNTIME DESTINATION tools)
So upstream doesn't install examples even if they are build?  Why does vcpkg have to install them?
Why not just drop examples in this case?

2023-02-07 06:28 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> ++    RUNTIME DESTINATION tools)
Upstream doesn't install tests. Does vcpkg really have to add it?

2023-02-07 06:28 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> +     DESTINATION "${CMAKE_INSTALL_BINDIR}")
Isn't this utility installed twice here?

2023-02-07 06:28 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> ++install(DIRECTORY ${ZFP_SOURCE_DIR}/include DESTINATION include)
zfp already has installation of public headers:
https://github.com/LLNL/zfp/blob/f39af72648a2aeb88e9b2cca8c64f51b493ad5f4/CMakeLists.txt#L329-L334

2023-02-07 08:46 UTC, JonLiu1993 commented on ports/zfp/fix-install-tools.patch
> + endif()
`BUILD_ALL `is used as a macro judgment in the upstream Config file.
https://github.com/LLNL/zfp/blob/81dbdd02dc3d326b0565336c378c526263eba6ac/Config#L82-L91

2023-02-07 11:42 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> + endif()
`Config` is part of the `Makefile` build system, not of the CMake build system. So this spot is unrelated.

2023-02-08 03:53 UTC, dg0yt commented on ports/zfp/fix-install-tools.patch
> ++  set(BUILD_EXAMPLES OFF CACHE BOOL "Build Examples" FORCE)
I still think we should get rid this patch and of `BUILD_ALL`. We can control the desired options directly if `BUILD_ALL`  is not used.

2023-02-08 06:15 UTC, JonLiu1993 commented on ports/zfp/fix-install-tools.patch
> ++  set(BUILD_EXAMPLES OFF CACHE BOOL "Build Examples" FORCE)
Thanks for your review, done.

2023-02-08 08:05 UTC, dg0yt commented on ports/zfp/vcpkg.json
> -    },
Removing features is still somewhat tricky in vcpkg, in particular breaking the `upgrade` command.
Simply leave the feature, make it depend on features cfp, utility.
Change the description to `Obsolete. This feature is left for compatibility.`
(Similar to libmariadb[zlib].)

2023-02-09 02:35 UTC, JonLiu1993 commented on ports/zfp/vcpkg.json
> -    },
Thanks for your review, Done.

2023-02-09 06:30 UTC, MonicaLiu0311 approved these changes

2023-02-09 18:55 UTC, merged