[gamenetworkingsockets] Add find_dependency(protobuf CONFIG REQUIRED)
microsoft/vcpkg pull request #28615
Opened 2022-12-29 10:24 UTC by LilyWangLL

**Describe the pull request**

- #### What does your PR fix?
  Fixes #28518

2022-12-29 10:36 UTC, dg0yt requested changes

2022-12-29 10:36 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +find_dependency(protobuf CONFIG REQUIRED)]]
Uff.
- Upstream does a module-mode `find_package(Protobuf)`. So you must use this package name and must not use `CONFIG` here.
- Never use explicit `REQUIRED` with `find_dependency`. The correct use of `REQUIRED` is implicit behaviour of this macro.
- Do such fixup as a patch. And submit it upstream.
  When the patch no longer applies, we will notice it immediately when building this port and never merge a broken revision.
  When `vcpkg_replace_string` no longer matches the pattern, we may not notice the breakage and get bug reports.

2022-12-29 11:28 UTC, LilyWangLL commented on ports/gamenetworkingsockets/portfile.cmake
> +find_dependency(protobuf CONFIG REQUIRED)]]
Done.

2022-12-29 11:29 UTC, dg0yt commented on ports/gamenetworkingsockets/portfile.cmake
> +find_dependency(protobuf CONFIG REQUIRED)]]
Thank you @LilyWangLL :+1:

2022-12-30 02:20 UTC, FrankXie05 approved these changes

2022-12-30 07:54 UTC, merged