[szip] Fix crosscompiling
microsoft/vcpkg pull request #28681
Opened 2023-01-03 00:34 UTC by Pospelove

2023-01-03 03:57 UTC, Cheney-W commented
[CI failure logs](https://dev.azure.com/vcpkg/public/_build/results?buildId=83161&view=artifacts&pathAsName=false&type=publishedArtifacts).

2023-01-03 07:58 UTC, dg0yt requested changes

2023-01-03 07:58 UTC, dg0yt commented on ports/szip/portfile.cmake
> +if (VCPKG_CROSSCOMPILING)
Please fix below:
~~~cmake
    set(extra_opts 
        -DTEST_LFS_WORKS_RUN=TRUE
        -DTEST_LFS_WORKS_RUN__TRYRUN_OUTPUT=
    )
~~~
(Summary: Quote whole options or nothing.)

2023-01-04 11:07 UTC, Neumann-A commented on ports/szip/portfile.cmake
> +if (VCPKG_CROSSCOMPILING)
I don't think this is universally correct or can the below always be assumed?

2023-01-04 18:08 UTC, Pospelove commented on ports/szip/portfile.cmake
> +if (VCPKG_CROSSCOMPILING)
I think it's correct. These vars are needed when try_run can't do its job. And it's because of crosscompiling

2023-01-04 18:10 UTC, Neumann-A commented on ports/szip/portfile.cmake
> +if (VCPKG_CROSSCOMPILING)
> I think it's correct. These vars are needed when try_run can't do its job. And it's because of crosscompiling

that is why you need a special toolchain if you are crosscompiling defining those results of `try_run`. The problem is that `-DTEST_LFS_WORKS_RUN=TRUE` is probably not true for all cross cases

2023-01-04 23:28 UTC, Pospelove commented on ports/szip/portfile.cmake
> +if (VCPKG_CROSSCOMPILING)
I'm not really sure if it is 100% correct or not after you asked. closing for now

2023-01-04 23:29 UTC, closed without merging