[xaudio2redist] allow static CRT
microsoft/vcpkg pull request #28699
Opened 2023-01-03 22:04 UTC by Neumann-A

`vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` was invalid since the DLL this redist bundles is build against dynamic CRT. 
Since it bundles a static library with static CRT linkage static CRT linkage is obviously allowed.

2023-01-04 02:09 UTC, Adela0814 approved these changes

2023-01-04 10:33 UTC, Neumann-A commented
@walbourn you probably also want to unblock other ports. dx can be considered a system library so the library linkage of the triplet shouldn't effect the installation for static library linkage. Otherwise people would need explicit per port specialization for these ports. Would vcpkg follow the current logic of the dx ports opengl wouldn't be available in static triplets.

2023-01-04 19:12 UTC, walbourn requested changes
I will of course defer to the vcpkg owners, but in the case of **xaudio2redist**, **dxsdk-d3dx**, and **dstorage**, they all require you include a specific DLL with your application, and therefore do not actually support "static" binding.

2023-01-04 19:12 UTC, walbourn commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
> Library linkage for this library is irrelevant since it is a prebuild

Logically, if you are using a ``static`` triplet, you expect all dependencies to be bound into your executable binary. The ``static-md`` triplet means all dependencies are in your library except the CRT DLLs which have to be deployed.

In the case of **xaudio2redist**, **dxsdk-d3dx**, **dstorage**, etc. you always have a DLL you must redist and none of them provide a statically linked library.

Your comparison to OpenGL is not the same. OpenGL has a well-known deployment redistributable model which will add all required DLLs to the system. The same is true of the MSVC CRT redist package. For these ports, they all expect the *application* to deploy the DLL.

The extra here is specific to **xaudio2redist** in that it *also* provides a helper static C++ library, but there is no usage case where you only use the static C++ library and do not use the DLL.

2023-01-04 19:12 UTC, walbourn commented on ports/xaudio2redist/vcpkg.json
> +  "supports": "windows & !arm & !uwp"
I believe this should be:

```
"supports": "windows & !arm & !uwp & !static"
```

2023-01-04 19:50 UTC, dg0yt commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
AFAICT vcpkg tries to make every port available in every triplet.

2023-01-04 20:52 UTC, Neumann-A commented
> I will of course defer to the vcpkg owners, but in the case of xaudio2redist, dxsdk-d3dx, and dstorage, they all require you include a specific DLL with your application, and therefore do not actually support "static" binding.

AS @dg0yt said in https://github.com/microsoft/vcpkg/pull/27577#issuecomment-1371346986 and https://github.com/microsoft/vcpkg/pull/28699#discussion_r1061831255 vcpkg is not strict about `VCPKG_LIBRARY_LINKAGE`. If something is only avaibale as a static or dynamic library vcpkg will allow the port to take over `VCPKG_LIBRARY_LINKAGE` typically via `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)`. What `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` however tries to block is implicit shared lib with static crt which isn't the case here. 
The reason vcpkg isn't strict about `VCPKG_LIBRARY_LINKAGE` is due to the fact that if a user needs the library and the library is only available as a static or shared library it shouldn't block the installation since this would just force the user to explicitly request whatever would be available.

2023-01-06 18:57 UTC, walbourn commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
What specifically does ``VCPKG_POLICY_DLLS_IN_STATIC_LIBRARY`` do here?

2023-01-06 19:00 UTC, Neumann-A commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
> What specifically does VCPKG_POLICY_DLLS_IN_STATIC_LIBRARY do here? 

exactly what it says. If `VCPKG_LIBRARY_LINKAGE` is static  a `bin` folder with dlls is normally not allowed and the tool checks that. In this case however the redist dll is required and the policy tells the tool to not throw an error about it.

2023-01-06 20:01 UTC, walbourn commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
With the removal of ``vcpkg_check_linkage`` and the addition of this policy, it builds but it does provide any indication that a DLL is still required for distribution.

Perhaps we need to add a message:

```
if (NOT VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
   message(STATUS "Note: ${PORT} always requires dynamic library linkage at runtime.")
endif()
```

2023-01-06 20:15 UTC, Neumann-A commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
> still required for distribution.

That is what `dumpbin <executable> /DEPENDENTS` or in cmake `GET_RUNTIME_DEPENDENCIES` is for.

2023-01-06 20:20 UTC, walbourn commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Many developers do not do this or realize this. A log entry would at least help the discoverability for these 'prebuilt DLL' port scenarios.

2023-01-06 20:51 UTC, dg0yt commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Many developers do not read the output.

2023-01-06 20:53 UTC, dg0yt commented on ports/xaudio2redist/portfile.cmake
> -vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
But you could put a message in the `usage` document which is printed after install.

2023-01-10 21:53 UTC, Neumann-A commented on ports/xaudio2redist/vcpkg.json
> +  "supports": "windows & !arm & !uwp"
(as discussed this is not the case.)

2023-01-10 21:57 UTC, merged