[libadwaita] Add new port
microsoft/vcpkg pull request #28721
Opened 2023-01-04 14:47 UTC by clemenswasser

**Describe the pull request**

- #### What does your PR fix?
  Fixes #23050

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2023-01-04 14:48 UTC, clemenswasser commented
@microsoft-github-policy-service agree

2023-01-04 17:59 UTC, clemenswasser commented
Somehow, the `libadwaita-1.pc` file doesn't get installed.
Do I have to do something special for that to happen?

2023-01-05 02:57 UTC, FrankXie05 requested changes

2023-01-08 15:27 UTC, clemenswasser commented on ports/libadwaita/portfile.cmake
> +)
I've now reformatted in the style also used by the gstreamer portfile:
https://github.com/microsoft/vcpkg/blob/739824a6d3179d85820eedc0637e81c0c68b874c/ports/gstreamer/portfile.cmake#L602-L607

2023-01-09 09:14 UTC, FrankXie05 approved these changes

2023-01-09 09:22 UTC, merged