[scripts] add vcpkg-msbuild
microsoft/vcpkg pull request #28773
Opened 2023-01-06 14:29 UTC by Neumann-A

split out of #26370 as requested for simpler review.

2023-01-06 14:31 UTC, Neumann-A commented on ports/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake
> +    if(arg_USE_MSVC_SYNTAX_ON_WINDOWS AND VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
@dg0yt: better? (although the option name now kind of ....; so if someone wants to suggest a better one.... )

2023-02-06 08:50 UTC, JonLiu1993 commented
@Neumann-A, `zeroc-ice` baseline error have been faixed by PR https://github.com/microsoft/vcpkg/pull/28522, can this PR be closed?

2023-02-08 06:33 UTC, JonLiu1993 approved these changes, later dismissed

2023-02-10 20:41 UTC, JavierMatosD approved these changes, later dismissed

2023-02-10 23:15 UTC, ras0219-msft commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_INSTALL_DIR "${CURRENT_PACKAGES_DIR}/include/${PORT}")
Looking through the ports that use `vcpkg_install_msbuild()`, I think the `INCLUDE_SUBPATH` / `INCLUDE_INSTALL_DIR` mechanism needs work to actually meet the needs of MSBuild libraries. At the bottom of this comment I've accumulated a semi-random sample of how ports do it today.

The major takeaways for me are that the current mechanism works for vanishingly few ports and that `include/${PORT}` is correct in even fewer cases (often due to casing).

The best complexity-to-value improvement I see which covers every case below would be to mirror `install(DIRECTORY ...)`:
- `INCLUDES_SUBPATHS <path1>...`, a list of directories/paths to install.
- `INCLUDES_DESTINATION <include/>`, where to install them, defaults to `include` 
- `INCLUDES_MATCHING ....`, exactly the same syntax and semantics as `install(DIRECTORY ... FILES_MATCHING ...)`. We do not need to implement all this ourselves -- internally we will call `file(COPY ...)`

I've added the translation proposal as an additional comment.

### `INCLUDES_SUBPATH` ✅
```cmake
#libfabric, libirecovery
vcpkg_install_msbuild(... INCLUDES_SUBPATH include ALLOW_ROOT_INCLUDES ...)
# Proposed: INCLUDES_SUBPATHS include/
```

### Copying a single prefix with a single PATTERN/GLOB
```cmake
#ecsutil
file(COPY ${SOURCE_PATH}/ECSUtil DESTINATION ${CURRENT_PACKAGES_DIR}/include FILES_MATCHING PATTERN *.h)
# Proposed: INCLUDES_SUBPATHS ECSUtil INCLUDES_MATCHING PATTERN *.h
```
```cmake
#libmicrohttpd
    file(GLOB MICROHTTPD_HEADERS "${SOURCE_PATH}/src/include/microhttpd*.h")
    file(COPY ${MICROHTTPD_HEADERS} DESTINATION "${CURRENT_PACKAGES_DIR}/include")
    # Proposed: INCLUDES_SUBPATHS include/ INCLUDES_MATCHING PATTERN microhttpd*.h
```
```cmake
#easyhook
file(INSTALL "${SOURCE_PATH}/Public/easyhook.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include/easyhook")
    # Proposed: INCLUDES_SUBPATHS Public/easyhook.h INCLUDES_DESTINATION include/easyhook
```
```cmake
#marisa-trie
    file(INSTALL "${SOURCE_PATH}/include/marisa.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
    file(GLOB MARISA_DIR_HEADERS "${SOURCE_PATH}/include/marisa/*.h")
    file(INSTALL ${MARISA_DIR_HEADERS} DESTINATION "${CURRENT_PACKAGES_DIR}/include/marisa")
    # Proposed: INCLUDES_SUBPATHS include/marisa.h include/marisa INCLUDES_MATCHING PATTERN *.h
```
### Single prefix with multiple patterns
```cmake
#simd
  file(GLOB SIMD_HEADERS "${SOURCE_PATH}/src/Simd/*.hpp" "${SOURCE_PATH}/src/Simd/*.h")
  file(COPY ${SIMD_HEADERS} DESTINATION "${CURRENT_PACKAGES_DIR}/include/Simd")
  # Proposed: INCLUDES_SUBPATHS src/Simd INCLUDES_MATCHING PATTERN *.h PATTERN *.hpp
```
### Multiple directories with patterns
```cmake
#activemp-cpp
    file(COPY "${SOURCE_PATH}/src/main/activemq" DESTINATION "${CURRENT_PACKAGES_DIR}/include" FILES_MATCHING PATTERN *.h)
    file(COPY "${SOURCE_PATH}/src/main/cms"      DESTINATION "${CURRENT_PACKAGES_DIR}/include" FILES_MATCHING PATTERN *.h)
    file(COPY "${SOURCE_PATH}/src/main/decaf"    DESTINATION "${CURRENT_PACKAGES_DIR}/include" FILES_MATCHING PATTERN *.h)
    # Proposed: INCLUDES_SUBPATHS src/main/activemq src/main/cms src/main/decaf INCLUDES_MATCHING PATTERN *.h
```
### Multiple directories with patterns, exclusions, and rearranging
```cmake
#3fd
file(GLOB HEADER_FILES LIST_DIRECTORIES false "${SOURCE_PATH}/3FD/*.h")
file(INSTALL
    ${HEADER_FILES}
    DESTINATION ${CURRENT_PACKAGES_DIR}/include/3FD
    PATTERN "*_impl*.h" EXCLUDE
    PATTERN "*example*.h" EXCLUDE
    PATTERN "stdafx.h" EXCLUDE
    PATTERN "targetver.h" EXCLUDE
)

file(INSTALL ${SOURCE_PATH}/btree  DESTINATION ${CURRENT_PACKAGES_DIR}/include/3FD)
file(INSTALL ${SOURCE_PATH}/OpenCL/CL DESTINATION ${CURRENT_PACKAGES_DIR}/include/3FD)
# Proposed:
# INCLUDES_SUBPATHS 3FD/ btree OpenCL/CL
# INCLUDES_DESTINATION include/3FD
# INCLUDES_MATCHING
#     PATTERN OpenCL/CL/*
#     PATTERN btree/*
#     PATTERN *.h
#     PATTERN "*_impl*.h" EXCLUDE
#     PATTERN "*example*.h" EXCLUDE
#     PATTERN "stdafx.h" EXCLUDE
#     PATTERN "targetver.h" EXCLUDE
```

2023-02-11 09:19 UTC, dg0yt commented on ports/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake
>              execute_process(
TBH I would prefer if we would trim the sea of log files which also hides error messages from the console. Since CMake 3.19, there is a `COMMAND_ERROR_IS_FATAL` for `execute_process`.

2023-02-25 14:08 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild.targets.in
> +  <PropertyGroup>
because I never know when MSBuild actually sets/accepts this stuff.  
I am a bit reluctant to remove the doubling since it has been tested in CI and without it it might simply break again.

2023-02-25 14:39 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild.targets.in
> +        <RuntimeLibrary Condition="'${VCPKG_CRT_LINKAGE}|$(Configuration)' == 'static|${arg_DEBUG_CONFIGURATION}'">MultiThreadedDebug</RuntimeLibrary>
I don't see how it would be easier to generate those files per configuration but for testing having it this way was easier. I see that some lines could be deduplicated by generating the file per configuration instead but again without CI testing this is going to by a pain to get correct. 
Secondly, I really don't care about "MSBuild runtime evaluation" at this time since the first step needs to be  correctness and not speed. The current msbuild state is simply incorrect by not applying the user provided flags.

However if you want to try, the branch is - as always - open for edits from maintainers.

2023-02-25 15:08 UTC, Neumann-A commented on ports/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake
> +    if(arg_USE_MSVC_SYNTAX_ON_WINDOWS AND VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
If you want to test something here it would be the vcpkg variant of `CMAKE_<LANG>_COMPILER_FRONTEND_VARIANT`. However, for me this seems to have only one use case being pure clang on windows and I doubt anything else in vcpkg is setup to deal with that (except maybe CMake ports). There is also a high possibilty that clang figures it out by itself using filemagic.
I think we first need more data about clang toolchains/triplets to understand if it can or cannot deal with MSVC syntax or if it has to set `VCPKG_TARGET_IS_MINGW` as a workaround anyway to make other stuff in vcpkg work.

Another problem here is that it is not really only compiler dependent but buildsystem dependent. qmake for example can be fed either on windows.  

I like the inversion but will call it `NO_MSVC_SYNTAX` since it is shorter ;)

2023-02-25 15:12 UTC, Neumann-A commented on ports/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake
>              execute_process(
Yeah should probably have `COMMAND_ERROR_IS_FATAL ANY`

2023-02-25 15:33 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_INSTALL_DIR "${CURRENT_PACKAGES_DIR}/include/${PORT}")
- MSBuild implies Windows: So do we really have to care about upper/lower case?
- MSBuild doesn't have install rules so include layout can be mandated by vcpkg. 
- I would drop `PATTERN` and `PATTERN "something" EXCLUDE`  and simply have `INCLUDES_MATCHING` and `INCLUDES_NOT_MATCHING` instead. Makes it way easier to deal with this stuff in the implementation. 

That being said I only covered a few cases since I didn't have the time to deal with all those manual install rules so I only covered those which were already covered by `vcpkg_install_msbuild` without inventing something new. Again the aim of this PR is to get the toolchain flags into msbuild. 

Furthermore these rules feel more like a different PR where the implementation of the propsed change is actually tested with ports using them. 

I'll rename `INCLUDE_INSTALL_DIR` into `INCLUDES_DESTINATION`

2023-02-25 16:08 UTC, Neumann-A commented on ports/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake
> +    if(arg_USE_MSVC_SYNTAX_ON_WINDOWS AND VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
> Should the option be inverted? NEVER_USE_MSVC_SYNTAX

The answer to that is no. It breaks ffmpeg.

2023-05-10 02:40 UTC, JonLiu1993 commented on versions/v-/vcpkg-msbuild.json
> +}
There should be only one record here.

2023-05-10 02:40 UTC, JonLiu1993 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-05-10 08:05 UTC, Neumann-A commented on versions/v-/vcpkg-msbuild.json
> +    }
```suggestion
    }
```

2023-05-11 02:12 UTC, JonLiu1993 approved these changes, later dismissed

2023-05-22 17:20 UTC, JavierMatosD reviewed
Doing the "Draft" dance.

2023-05-22 17:20 UTC, JavierMatosD commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        "SOURCE_PATH;PROJECT_SUBPATH;INCLUDES_SUBPATH;LICENSE_SUBPATH;RELEASE_CONFIGURATION;DEBUG_CONFIGURATION;PLATFORM;TARGET;INCLUDE_DESTINATION"
I think it might be worth adding the `INCLUDES_MATCHING` and `INCLUDE_NOT_MATCHING` functionality you discussed with @ras0219-msft. The concern is having to come back and change the behavior or `vcpkg_msbuild_install`.

2023-05-23 19:20 UTC, JavierMatosD requested changes

2023-05-23 19:20 UTC, JavierMatosD commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +    endif()
```suggestion
```

2023-05-23 19:20 UTC, JavierMatosD commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        "SOURCE_PATH;PROJECT_SUBPATH;INCLUDES_SUBPATH;LICENSE_SUBPATH;RELEASE_CONFIGURATION;DEBUG_CONFIGURATION;PLATFORM;TARGET;INCLUDE_DESTINATION"
```suggestion
        "SOURCE_PATH;PROJECT_SUBPATH;RELEASE_CONFIGURATION;DEBUG_CONFIGURATION;PLATFORM;TARGET;INCLUDE_DESTINATION"
```

2023-06-10 20:58 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
That requires whatever to be installed to use unique named headers which might not be the case. So the better and saver default is to have a subdir in my opinion.

2023-06-10 21:01 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        "SOURCE_PATH;PROJECT_SUBPATH;INCLUDES_SUBPATH;LICENSE_SUBPATH;RELEASE_CONFIGURATION;DEBUG_CONFIGURATION;PLATFORM;TARGET;INCLUDE_DESTINATION"
Those two options are from `vcpkg_install_msbuild`. Without those porting from old to new would be a bit more work. But I don't really care about those. Maybe vcpkg needs a script function `vcpkg_install_headers` which has some filtering etc.

2023-06-10 21:02 UTC, Neumann-A commented
Waiting for response to https://github.com/microsoft/vcpkg/pull/28773#discussion_r1225583644 before apply suggestions.

2023-06-13 21:15 UTC, JavierMatosD commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        "SOURCE_PATH;PROJECT_SUBPATH;INCLUDES_SUBPATH;LICENSE_SUBPATH;RELEASE_CONFIGURATION;DEBUG_CONFIGURATION;PLATFORM;TARGET;INCLUDE_DESTINATION"
I'm not sure about the `vcpkg_install_headers` idea. Porting from old to new should just be a matter of having them call `install(DIRECTORY...)`.

2023-06-16 22:48 UTC, JavierMatosD commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
@Neumann-A, I get where you're coming from, but we're sticking with `${CURRENT_PACKAGES_DIR}/include` mainly for compatibility reasons. A single-level include directory is a common practice in C++. Take `zlib` for example. Regardless of how `zlib` documents their headers, it's usually expected to do `#include <zlib.h>` rather than `#include <zlib/zlib.h>`.

Say openssl needs zlib, and both are sourced from vcpkg. These headers are coded to say #include <zlib.h>. If we start to use subdirectories in the include directory, we'd then be faced with the task of patching everything everywhere to avoid conflicts in the single include directory. It's just more straightforward to stick to the norm.

2023-06-19 06:03 UTC, dg0yt commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
> Take `zlib` for example. Regardless of how `zlib` documents their headers, it's usually expected to do `#include <zlib.h>` rather than `#include <zlib/zlib.h>`.

Nobody asks to use `zlib/zlib.h`. This is unrelated to the installation location: This is managed by adjusting the include path. Easy with CMake config or pkg-config. But "I get where you're coming from" ;-)

2023-06-19 07:14 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
>  A single-level include directory is a common practice in C++

"common practice" seems to have widely varying definitions. Just check the vcpkg header list and look at ports like Qt, VTK, glib, Eigen3 (vcpkg duplicates the headers from `include/eigen3/` to `include` to make it work seamless in MSBuild), boost, abseil, llvm and many more. (You can also just scroll through the list and you will notice the common pattern)
From what I see in the header file list is that `"${CURRENT_PACKAGES_DIR}/include/${PORT}"`  seems to be the more common sane default for bigger projects. So please fact check your argument or give a better argument. 

> It's just more straightforward to stick to the norm.

According to actual facts (i.e. the header database) the norm is `"${CURRENT_PACKAGES_DIR}/include/${PORT}"` and  `"${CURRENT_PACKAGES_DIR}/include/"` is the exception. To make it clear here: We are only speaking about the default if the port has a described different usage somewhere the port is free to override it and move the headers anywhere it wants it to be.

2023-06-20 06:50 UTC, dg0yt commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
As a reminder why polluting the global file name space is bad: https://github.com/microsoft/vcpkg/issues/31887
(If libzip would use a subdir for `zip.h`, it wouldn't break minizip unsage unless you really try to use both at once.)

2023-06-21 21:09 UTC, JavierMatosD commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
Ok, how about removing the `INCLUDE_DESTINATION` default altogether and having the ports do the copying?

2023-06-22 19:23 UTC, Neumann-A commented on ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
> +        set(arg_INCLUDE_DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
for the sake of getting this merged someday ;)

2023-06-23 19:07 UTC, JavierMatosD approved these changes

2023-06-23 19:07 UTC, merged