Updated APSI to 0.9.0
microsoft/vcpkg pull request #28778
Opened 2023-01-06 20:40 UTC by WeiDaiWD

**Describe the pull request**

- #### What does your PR fix?
Updated `ports/apsi` to version 0.9.0.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
x86-windows-static, x64-windows-static, arm64-windows-static, x64-linux, arm64-linux, arm64-osx, x64-osx

No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2023-01-09 07:48 UTC, JonLiu1993 requested changes

2023-01-09 07:48 UTC, JonLiu1993 commented on ports/apsi/vcpkg.json
>    "port-version": 1,
```suggestion
```

2023-01-09 07:48 UTC, JonLiu1993 commented on ports/apsi/vcpkg.json
>    "port-version": 1,
When we update port version, we should remove "port-version".

2023-01-09 07:48 UTC, JonLiu1993 commented on ports/apsi/portfile.cmake
> -        fix-find_package.patch
@WeiDaiWD, thanks for your pr, please delete the patch files under the port folder and submit again.

2023-01-12 23:07 UTC, WeiDaiWD commented on ports/apsi/portfile.cmake
> -        fix-find_package.patch
Done.

2023-01-12 23:16 UTC, WeiDaiWD commented on ports/apsi/vcpkg.json
>    "port-version": 1,
This is removed.

2023-01-13 07:02 UTC, JonLiu1993 approved these changes

2023-01-24 09:00 UTC, merged

2023-01-24 09:00 UTC, BillyONeal commented
Thanks for the update!

2023-01-26 10:23 UTC, autoantwort commented
Hm since this update the build fails with 
```
CMake Error at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package):
  Could not find a configuration file for package "SEAL" that is compatible
  with requested version "4".

  The following configuration files were considered but not accepted:

    /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/arm64-osx/share/seal/SEALConfig.cmake, version: 4.1.1

Call Stack (most recent call first):
  CMakeLists.txt:120 (find_package)


```

2023-01-26 10:27 UTC, autoantwort commented
I wounder how the pipeline succeeded at all. For me the build now fails on all operating systems.

2023-01-26 10:30 UTC, autoantwort commented
Ah the last pipeline probably run before 0a77b03b49a33b46af1bca5c6546b3c6c0625362 was merged. It is also a baseline regression: https://github.com/microsoft/vcpkg/runs/10897043328

2023-01-26 19:50 UTC, BillyONeal commented
https://github.com/microsoft/vcpkg/pull/29204/