[acl] Add new port
microsoft/vcpkg pull request #28819
Opened 2023-01-09 12:06 UTC by ex-purple

- #### What does your PR fix?
  Add new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  linux, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

2023-01-10 06:27 UTC, JonLiu1993 requested changes

2023-01-10 06:27 UTC, JonLiu1993 commented on ports/acl/vcpkg.json
> +  "name": "acl",
@ex-purple, thanks for the pr, can you change this port name `acl`? Because another port https://github.com/acl-dev/acl duplicates this port name, which confuses users

2023-01-10 06:40 UTC, dg0yt commented on ports/acl/vcpkg.json
> +  "name": "acl",
@JonLiu1993 Does this request make sense? It is this PR's source which is commonly packaged as `acl`:
https://repology.org/project/acl/information

2023-01-10 06:49 UTC, JonLiu1993 approved these changes

2023-01-11 21:23 UTC, ex-purple commented
@JonLiu1993 
Looks like info:reviewed label is missing here.

2023-01-12 07:05 UTC, merged