[pcl] update to version 1.13.0
microsoft/vcpkg pull request #28818
Opened 2023-01-09 09:54 UTC by mvieth

**Describe the pull request**

- #### What does your PR fix?
  Updates PCL to version 1.13.0, remove patches that are no longer needed

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No changes, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2023-01-09 09:56 UTC, mvieth commented
@microsoft-github-policy-service agree

2023-01-10 06:34 UTC, JonLiu1993 requested changes

2023-01-10 06:34 UTC, JonLiu1993 commented on ports/pcl/vcpkg.json
> +  "port-version": 0,
```suggestion
```

2023-01-10 06:34 UTC, JonLiu1993 commented on ports/pcl/portfile.cmake
> +        # remove-broken-targets.patch
```suggestion
```

2023-01-10 06:34 UTC, JonLiu1993 commented on ports/pcl/portfile.cmake
> +        # remove-broken-targets.patch
@mvieth, thanks for the PR, please delete this patch here if it is no longer applicable.

2023-01-10 06:37 UTC, JonLiu1993 commented
Please run command  "./vcpkg format-manifest ports/pcl/vcpkg.json" after finished the vcpkg.json file.

2023-01-13 09:10 UTC, mvieth commented
@JonLiu1993 Thank you for your hints and suggestions. This PR is now ready for review. Please also see my explanations in the PR description, and please tell me if you want me to squash all commits. Unfortunately, I don't feel capable of migrating the existing deprecated function(s) in the portfile, so I left those unchanged.

2023-01-18 09:27 UTC, JonLiu1993 approved these changes, later dismissed

2023-01-19 09:28 UTC, JonLiu1993 commented
@mvieth, when I tested the features by command "./vcpkg install pcl[*]:x64-windows" I get this error:
````
CMake Error at cmake/pcl_find_vtk.cmake:96 (message):
  Missing vtk modules: RenderingContextOpenGL2
Call Stack (most recent call first):
  CMakeLists.txt:393 (include)


-- Configuring incomplete, errors occurred!
See also "F:/Feature-test/pcl/vcpkg/buildtrees/pcl/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "F:/Feature-test/pcl/vcpkg/buildtrees/pcl/x64-windows-rel/CMakeFiles/CMakeError.log".
````
Please take a look.

2023-01-19 12:45 UTC, mvieth commented
@JonLiu1993 Please check again

2023-01-25 19:50 UTC, BillyONeal requested changes
```
.\vcpkg.exe install pcl[core,apps,cuda,examples,libusb,opengl,openni2,pcap,qt,simulation,tools,visualization,vtk]:x64-windows
```

fails with:

```
C:\vcpkg\buildtrees\pcl\src\89d532cf08-f1f6fba89c.clean\outofcore\tools\outofcore_viewer.cpp(118): fatal error C1083: Cannot open include file: 'vtkMutexLock.h': No such file or directory
```

[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10503049/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/10503050/config-x64-windows-err.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10503051/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10503052/config-x64-windows-rel-CMakeCache.txt.log)
[error-logs-x64-windows.txt](https://github.com/microsoft/vcpkg/files/10503053/error-logs-x64-windows.txt)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10503054/install-x64-windows-dbg-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/10503055/stdout-x64-windows.log)

Please investigate. Thanks for your contribution to vcpkg!

2023-01-26 08:07 UTC, mvieth commented
@BillyONeal Thanks for your comment. I assume you tested with VTK's master branch? I added a patch to remove the include. The patch is already present on PCL's master branch (https://github.com/PointCloudLibrary/pcl/commit/b957fbee3bd837e8c569e0042691ff5c3baf2df7), but was not included in PCL 1.13.0.

2023-01-27 04:23 UTC, BillyONeal commented
> I assume you tested with VTK's master branch?

I tested with the current copy of vtk vcpkg installs.

2023-01-27 05:44 UTC, BillyONeal commented
No joy, this time:

```
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DH5_BUILT_AS_DYNAMIC_LIB -DKISSFFT_DLL_IMPORT=1 -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x050900 -DQT_GUI_LIB -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -Dkiss_fft_scalar=double -IC:\vcpkg\buildtrees\pcl\x64-windows-dbg\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\common\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\io\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\features\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\search\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\kdtree\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\octree\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\filters\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\keypoints\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\segmentation\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\sample_consensus\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\outofcore\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\stereo\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\geometry\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\surface\include -IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\visualization\include -external:IC:\vcpkg\installed\x64-windows\include\eigen3 -external:IC:\vcpkg\installed\x64-windows\include\openni2 -external:IC:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\recognition\include\pcl\recognition\3rdparty -external:IC:\vcpkg\installed\x64-windows\include -external:IC:\vcpkg\installed\x64-windows\include\vtk-9.2 -external:IC:\vcpkg\installed\x64-windows\include\Qt6\QtOpenGL -external:IC:\vcpkg\installed\x64-windows\include\Qt6 -external:IC:\vcpkg\installed\x64-windows\include\Qt6\QtCore -external:IC:\vcpkg\installed\x64-windows\share\Qt6\mkspecs\win32-msvc -external:IC:\vcpkg\installed\x64-windows\include\Qt6\QtGui -external:IC:\vcpkg\installed\x64-windows\include\Qt6\QtWidgets -external:IC:\vcpkg\installed\x64-windows\include\Qt6\QtOpenGLWidgets -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /bigobj /FS -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -DBOOST_ALL_NO_LIB -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -DNOMINMAX -DPCL_ONLY_CORE_POINT_TYPES  -D__SSE4_2__ -D__SSE4_1__ -D__SSSE3__ -D__SSE3__ -D__SSE2__ -D__SSE__ -Zc:__cplusplus -permissive- -utf-8 -std:c++17 /showIncludes /Foexamples\surface\CMakeFiles\pcl_example_nurbs_fitting_closed_curve.dir\example_nurbs_fitting_closed_curve.cpp.obj /Fdexamples\surface\CMakeFiles\pcl_example_nurbs_fitting_closed_curve.dir\ /FS -c C:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\examples\surface\example_nurbs_fitting_closed_curve.cpp
C:\vcpkg\buildtrees\pcl\src\e50dc19856-e1542a945a.clean\surface\include\pcl\surface\3rdparty\opennurbs\opennurbs_system.h(147): fatal error C1189: #error:  do not define WIN32 for x64 builds
```

Can you please try running

x-set-installed pcl[core,apps,cuda,examples,libusb,opengl,openni2,pcap,qt,simulation,tools,visualization,vtk]:x64-windows

and let me know when you've got that working?

2023-01-29 19:19 UTC, mvieth commented
@BillyONeal Please review again.
Unfortunately I don't have a Windows system to test on, but @larshg was so kind to do the testing. And now all problems should be fixed :smile:

2023-01-30 07:29 UTC, JonLiu1993 commented
`.\vcpkg.exe install pcl[core,apps,cuda,examples,libusb,opengl,openni2,pcap,qt,simulation,tools,visualization,vtk]:x64-windows `tested successfully.

2023-01-31 00:36 UTC, BillyONeal approved these changes

2023-01-31 00:36 UTC, BillyONeal commented
Thanks for your contribution!

2023-01-31 00:41 UTC, merged

2023-01-31 08:58 UTC, mvieth commented
Thanks for the reviews!