[vcpkg] update msys-libiconv version
microsoft/vcpkg pull request #28919
Opened 2023-01-13 07:40 UTC by JonLiu1993

**Describe the pull request**

- #### What does your PR fix?
  Fixes #28896 
  link to previous version 2.6.4-9 does not exist anymore. update version to libtool-2.4.6-14.

2023-01-13 08:31 UTC, pango3001 requested changes

2023-01-13 08:31 UTC, pango3001 commented on scripts/cmake/vcpkg_acquire_msys.cmake
> +        URL "https://repo.msys2.org/msys/x86_64/libtool-2.4.6-14-x86_64.pkg.tar.zst"
If this is being updated, is there any reason why not bump it to `libtool-2.4.7-3-x86_64.pkg.tar.zst`? That seems to be the latest on msys2.

2023-01-13 08:44 UTC, pango3001 commented on scripts/cmake/vcpkg_acquire_msys.cmake
> +        SHA512 ba983ed9c2996d06b0d21b8fab9505267115f2106341f130e92d6b66dad87b0f0e82707daf0b676a28966bfaa24f6c41b6eef9e1f9bf985611471024f2b0ac97
If this is being updated, is there any reason not to bump it to `libtool-2.4.7-3-x86_64.pkg.tar.zst`? That seems to be the latest on msys2.
```suggestion
        URL "https://repo.msys2.org/msys/x86_64/libtool-2.4.7-3-x86_64.pkg.tar.zst"
        SHA512 a202ddaefa93d8a4b15431dc514e3a6200c47275c5a0027c09cc32b28bc079b1b9a93d5ef65adafdc9aba5f76a42f3303b1492106dd
```

2023-01-14 18:00 UTC, stianval commented on scripts/cmake/vcpkg_acquire_msys.cmake
>          DEPS grep sed coreutils file findutils
I'm not sure if the deps needs to be updated, it doesn't align with what I see on https://packages.msys2.org/package/libtool?repo=msys (says [libltdl](https://packages.msys2.org/package/libltdl?repo=msys&variant=x86_64) =2.4.7, [sh](https://packages.msys2.org/package/sh?repo=msys&variant=x86_64), [tar](https://packages.msys2.org/package/tar?repo=msys&variant=x86_64))
tar is already present in this file, and FWIW libltdl would be something like
```
    z_vcpkg_acquire_msys_declare_package(
        URL "https://repo.msys2.org/msys/x86_64/libltdl-2.4.7-3-x86_64.pkg.tar.zst"
        SHA512 eae760b03b3208c3e6121761951fd00d8f3389960193296c1256e25bc540be80510f72410a49b8c897ebff8a6b5107ca3dd0976db5f36791599cb97013a10ac9
     )
```
(I've checked since I also encountered this problem).

I don't know about the `sh` dependency, though maybe we need to add this bash package https://packages.msys2.org/package/bash?repo=msys

I'm not using libtool myself, and I'm not sure if the libraries in https://github.com/microsoft/vcpkg/issues/28896 or https://github.com/microsoft/vcpkg/issues/28945 does either, or if they just need a general MSYS environment. So I don't know how to test if this change will actually make libtool work, or if it just allows it to be downloaded.

In any case, I'm not commenting to hold back anything, I'm just flagging this here

2023-01-15 10:35 UTC, cnSchwarzer commented
Can anyone merge this ASAP?

2023-01-16 02:33 UTC, Cheney-W approved these changes

2023-01-16 03:58 UTC, duanqn approved these changes

2023-01-16 12:23 UTC, dicroce commented
When will this change be available on master?

2023-01-16 13:31 UTC, cnSchwarzer commented
For anyone who is urgent: Create your own registry! 😂

2023-01-16 14:10 UTC, Neumann-A commented
> Create your own registry! 😂

Won't solve the issue. You need to supply your own SCRIPTS folder in that case.

2023-01-16 14:11 UTC, Neumann-A commented
@JonLiu1993 Please check all msys tools if they are latest. If not update them accordingly.

2023-01-16 14:12 UTC, cnSchwarzer commented
Yes, I mean create your own fork, it can be used for a custom vcpkg and registry, and its fast.

2023-01-16 14:27 UTC, Neumann-A commented
Also this stuff can be avoided for existing users via setting up an asset cache https://vcpkg.io/en/docs/users/assetcaching.html

2023-01-16 15:35 UTC, dicroce commented
> Yes, I mean create your own fork, it can be used for a custom vcpkg and registry, and its fast.

Definitely going to do this once we have a working build.

2023-01-16 20:30 UTC, merged