Update blosc
microsoft/vcpkg pull request #28986
Opened 2023-01-16 09:05 UTC by wzj219

**[blosc] Update to 1.21.3**

2023-01-17 02:35 UTC, JonLiu1993 commented
@wzj219, Thanks for your PR, please run command "./vcpkg x-add-version blosc --overwrite-version" and commit again.

2023-01-18 02:31 UTC, JonLiu1993 submitted a review, later dismissed

2023-01-18 08:31 UTC, LilyWangLL requested changes

2023-01-18 08:31 UTC, LilyWangLL commented on ports/blosc/0001-find-deps.patch
>  +find_library(LZ4_LIBRARY_DEBUG NAMES lz4d)
Here should use `find_package(lz4 CONFIG REQUIRED)` instead of `find_library` and `find_path`.

2023-01-29 10:34 UTC, dg0yt commented on ports/blosc/0002-export-blosc-config.patch
> ++++ b/tests/fuzz/CMakeLists.txt
This directory names sounds like it should be removed from the build, not patched.

2023-01-29 10:34 UTC, dg0yt commented on ports/blosc/0002-export-blosc-config.patch
> ++                RUNTIME COMPONENT bin)
I don't think we have to patch the names of the `COMPONENT`. It is not `DESTINATION`.

2023-01-29 10:34 UTC, dg0yt commented on ports/blosc/0001-find-deps.patch
> ++        find_package(lz4 CONFIG REQUIRED)
`find_package(LZ4 NAMES lz4 CONFIG REQUIRED)` for getting `LZ4_FOUND`
plus setup of related variables and targets as used in blosc.

The changes to `FindLZ4.cmake` become obsolete with this change.

2023-01-29 10:34 UTC, dg0yt commented on ports/blosc/0002-export-blosc-config.patch
> -+        install(TARGETS blosc EXPORT blosc-config RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
I can't see that upstream renamed the library target.

2023-01-29 10:34 UTC, dg0yt commented on ports/blosc/0001-find-deps.patch
> ++if(0)
Why do these spots need to be patched?

2023-01-31 10:00 UTC, wzj219 commented on ports/blosc/0001-find-deps.patch
> ++if(0)
The find_package already contains the process of adding header files of lz4, so there is no need to add header files separately. This code is no longer needed.

2023-01-31 10:03 UTC, wzj219 commented on ports/blosc/0002-export-blosc-config.patch
> -+        install(TARGETS blosc EXPORT blosc-config RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
The library file name generated in the blosc package has been modified.

2023-01-31 16:00 UTC, dg0yt commented on ports/blosc/0001-find-deps.patch
> ++if(0)
This doesn't require a patch. The patch is needed only if we can't control `DEACTIVATE_LZ4` via CMake parameters.

2023-01-31 16:02 UTC, dg0yt commented on ports/blosc/0002-export-blosc-config.patch
> ++    "Build test programs from the blosc compression library" OFF)
Really NO to this patch. This is explicitly an option, i.e. you pass the desired value in `OPTIONS` of vcpkg_cmake_configure`.

2023-02-03 01:46 UTC, JonLiu1993 requested changes

2023-02-03 01:46 UTC, JonLiu1993 commented on versions/b-/blosc.json
> +    },
@wzj219, we only allow adding one "git-tree" record, please delete these two records and re-run `./vcpkg x-add-version blosc --overwrite-version` then commit again.

2023-02-03 07:49 UTC, LilyWangLL approved these changes

2023-02-03 08:15 UTC, JonLiu1993 approved these changes

2023-02-03 08:21 UTC, wzj219 commented
@microsoft-github-policy-service agree

2023-02-03 20:38 UTC, merged

2023-02-03 20:38 UTC, BillyONeal commented
Thanks for the update!