[mujoco] Add new port
microsoft/vcpkg pull request #28993
Opened 2023-01-16 21:42 UTC by talregev

**Describe the pull request**
Add new port mujoco
- #### What does your PR fix?
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

There is still problems:
`engine_collision_convex.c.obj : error LNK2001: unresolved external symbol _ccd_vec3_origin`
I found the same issue in other library:
https://github.com/flexible-collision-library/fcl/issues/183

I didn't test it in linux.
Help needed.
@dg0yt @JackBoosY 

Thank you!

2023-01-16 22:35 UTC, talregev commented
Fix for linux. Didn't handle bin folder pretty. (not working for all cases). Help needed. Thank you!

2023-01-16 22:54 UTC, talregev commented
For mac:
`/Users/vagrant/Data/buildtrees/mujoco/src/2.3.1-3e4b35f9cd.clean/src/engine/engine_collision_convex.c:36:13: error: incompatible pointer types passing 'ccd_real_t [3]' to parameter of type 'mjtNum *' (aka 'double *') [-Werror,-Wincompatible-pointer-types]
  mju_copy3(center->v, ccd->data->geom_xpos + 3*ccd->geom);
`

Not sure how to fix ccd library. Also it seems not active. 
Maybe we need to do some patch?

2023-01-17 06:18 UTC, MonicaLiu0311 requested changes

2023-01-17 06:18 UTC, MonicaLiu0311 commented on ports/mujoco/vcpkg.json
> +  "version": "0.16.3",
```suggestion
  "version": "2.3.1",
```

2023-01-17 06:18 UTC, MonicaLiu0311 commented on ports/mujoco/portfile.cmake
> +set(MUJOCO_VERSION 2.3.1)
```suggestion
```

2023-01-17 06:18 UTC, MonicaLiu0311 commented on ports/mujoco/portfile.cmake
> +    REF ${MUJOCO_VERSION}
```suggestion
    REF "${VERSION}"
```

2023-01-17 06:18 UTC, MonicaLiu0311 commented on ports/mujoco/portfile.cmake
> +    REF ${MUJOCO_VERSION}
You can directly get the version data specified in `vcpkg.json` through `${VERSION}`.

2023-01-17 06:18 UTC, MonicaLiu0311 commented on ports/mujoco/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/debug
All absolute paths in `portfile.cmake` must be enclosed in double quotes.

2023-01-17 06:19 UTC, MonicaLiu0311 commented on ports/mujoco/vcpkg.json
> +  "version": "0.16.3",
Found version `2.3.1` upstream.

2023-01-17 06:38 UTC, talregev commented on ports/mujoco/vcpkg.json
> +  "version": "0.16.3",
done.

2023-01-17 06:38 UTC, talregev commented on ports/mujoco/portfile.cmake
> +    REF ${MUJOCO_VERSION}
done.

2023-01-17 06:38 UTC, talregev commented on ports/mujoco/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/debug
done.

2023-01-17 06:39 UTC, talregev commented on ports/mujoco/portfile.cmake
> +set(MUJOCO_VERSION 2.3.1)
done.

2023-01-17 07:00 UTC, MonicaLiu0311 requested changes

2023-01-17 07:00 UTC, MonicaLiu0311 commented on versions/m-/mujoco.json
> +    }
A PR can only have one record at most, please delete the wrong record of `0.16.3`.

PS: If there are multiple revision submissions for the same version, run `./vcpkg x-add-verion mujoco` after the first revision, and run `./vcpkg x-add-verion mujoco --overwrite-version` to update `git-tree` after subsequent revisions ..

2023-01-17 07:05 UTC, talregev commented on versions/m-/mujoco.json
> +    }
Only one version. It my mistake. I will fix it.

2023-01-17 07:09 UTC, talregev commented on ports/mujoco/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
done.

2023-01-17 07:09 UTC, talregev commented on versions/m-/mujoco.json
> +    }
done.

2023-01-17 13:55 UTC, talregev commented
I fix for windows.

I don't know how to handle the exe file. Please help.

```
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/vcpkg/packages/mujoco_x86-windows/bin/simulate.exe

warning: Mismatching number of debug and release binaries.
warning: Found 0 debug binaries:


warning: Found 1 debug binaries:

    C:/src/vcpkg/packages/mujoco_x86-windows/bin/mujoco.dll

warning: Debug binaries were not found.
error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: C:\src\vcpkg\ports\mujoco\portfile.cmake
```

2023-01-17 15:09 UTC, talregev commented
Fix for mac.

2023-01-17 16:45 UTC, talregev commented
It not working for static windows:
```
tinyxml2.lib(tinyxml2.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in engine_plugin.cc.obj
tinyxml2.lib(tinyxml2.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in engine_plugin.cc.obj
```

2023-01-17 21:26 UTC, talregev commented
@vicroms @BillyONeal 
> It not working for static windows:
> 
> ```
> tinyxml2.lib(tinyxml2.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in engine_plugin.cc.obj
> tinyxml2.lib(tinyxml2.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in engine_plugin.cc.obj
> ```

After change to `_ITERATOR_DEBUG_LEVEL=0`
```
lodepng.lib(lodepng.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in engine_plugin.cc.obj

tinyxml2.lib(tinyxml2.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in engine_plugin.cc.obj

   Creating library lib\mujoco.lib and object lib\mujoco.exp
```

What should be the value of `_ITERATOR_DEBUG_LEVEL` when compile on debug?
For `tinyxml2` it '0'
For `lodepng` it '2'

2023-01-18 02:11 UTC, MonicaLiu0311 commented
> I don't know how to handle the exe file. Please help.
```
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/vcpkg/packages/mujoco_x86-windows/bin/simulate.exe

warning: Mismatching number of debug and release binaries.
warning: Found 0 debug binaries:


warning: Found 1 debug binaries:

    C:/src/vcpkg/packages/mujoco_x86-windows/bin/mujoco.dll

warning: Debug binaries were not found.
error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: C:\src\vcpkg\ports\mujoco\portfile.cmake
```


It can be handled with the [vcpkg_copy_tools()](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md).

2023-01-18 05:20 UTC, talregev commented
> > I don't know how to handle the exe file. Please help.
> 
> ```
> warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.
> 
>     C:/src/vcpkg/packages/mujoco_x86-windows/bin/simulate.exe
> 
> warning: Mismatching number of debug and release binaries.
> warning: Found 0 debug binaries:
> 
> 
> warning: Found 1 debug binaries:
> 
>     C:/src/vcpkg/packages/mujoco_x86-windows/bin/mujoco.dll
> 
> warning: Debug binaries were not found.
> error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: C:\src\vcpkg\ports\mujoco\portfile.cmake
> ```
> 
> It can be handled with the [vcpkg_copy_tools()](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md).

Thank you for your help!
For now, I disable the compilation of the exe file.

2023-01-18 09:40 UTC, talregev commented
I disable the support in windows static, because 2 problems: 
- I think tinyxml2 is not compile correctly in static. in the debug compilation, it compile as release.
- It hard for me to convert mujoco itself to compile static. (It force shared inside the cmake).

If anyone want to do it later on different pr, he will welcome.

2023-01-18 11:58 UTC, talregev commented
@MonicaLiu0311 please review.

2023-01-19 07:29 UTC, MonicaLiu0311 commented
Usage test passed.

2023-01-19 07:29 UTC, MonicaLiu0311 submitted a review, later dismissed

2023-01-19 07:54 UTC, dg0yt requested changes
IMO the dependencies needs more work.

2023-01-19 07:54 UTC, dg0yt commented on ports/mujoco/fix_dependencies.patch
> ++)
Why does the patch switch from modern `target_include_directories` to legacy `include_directories`? Did the usage test include the reachability of the qhull headers?

2023-01-19 07:54 UTC, dg0yt commented on ports/mujoco/fix_dependencies.patch
> + )
Why is this needed?

2023-01-19 07:54 UTC, dg0yt commented on ports/mujoco/fix_dependencies.patch
> +-if(NOT TARGET lodepng)
Changing this to `if(0)` would be amore robust patch. And with `findorfetch` before moved that line, you wouldn't have to change/remove it at all. (The target would be defined.)

2023-01-19 08:02 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> ++)
It don't find `include/libqhull_r` by it own. qhull don't export it. Also when it doing find_packege it don't create a target, because the package already there. and the dependency is coming before mujoco directory, so I did it in the legacy way.

2023-01-19 08:12 UTC, dg0yt commented on ports/mujoco/fix_dependencies.patch
> ++)
Maybe you cannot change the imported Qhull targets. But `target_include_directories` should be used with the project's targets, not with imported targets. This project's specific patterns explain why you need to remove so many of these lines... 
Let's accept if for now if it isn't missing from exported CMake config.

2023-01-19 08:24 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> +-if(NOT TARGET lodepng)
done.

2023-01-19 08:25 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> ++
It not needed to remove. I restore it.

2023-01-19 08:28 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
It for other problem:
`LINK : fatal error LNK1181: cannot open input file 'tinyobjloader.lib'`
I will think other way to fix it.

2023-01-19 08:44 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
I added this line for `tinyobjloader`. Not sure why it not find it.

2023-01-19 08:58 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> ++
I fix it for the mac:
```

CMake Error at simulate/cmake/SimulateDependencies.cmake:102 (target_compile_options):
  target_compile_options may only set INTERFACE properties on IMPORTED
  targets
Call Stack (most recent call first):
  simulate/CMakeLists.txt:64 (include)


CMake Error at simulate/cmake/SimulateDependencies.cmake:103 (target_link_options):
  target_link_options may only set INTERFACE properties on IMPORTED targets
Call Stack (most recent call first):
  simulate/CMakeLists.txt:64 (include)
```

I don't want to change the `SIMULATE_STANDALONE` vars. not sure how it affect the compilation. 
I just put if(0) instead of removing.

2023-01-19 09:00 UTC, talregev commented
@dg0yt Please review again. Thanks.

2023-01-19 09:04 UTC, dg0yt commented on ports/mujoco/fix_dependencies.patch
> + )
This is the wrong spot for changes associated with tinyobjloader.

I guess that the original code uses a target `tinyobjloader`. The patching removes the original target. `link_directories` hides the problem but doesn't fix it.
- CMake cannot detect that a target is meant here because the name doesn't use a namespace.
- CMake passes the name to the linker.
- The linker finds a lib which matches the name spec (`tinyobjloader.lib`, `libtinyobjloader.so`).

The problem is not solved because the linker might find the wrong lib: It doesn't look for suffixes (`-static`, `-import`, `d`).

You must make sure that imported target is actually used (so it will tell CMake the actual library location), and that the same target is available when the exported config is used (`find_dependency`). For all relevant targets.

2023-01-19 09:57 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
I am not sure how to do it. Can you help me?

2023-01-19 09:59 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
The a look for the new code I added:
https://github.com/microsoft/vcpkg/pull/28993/files#diff-408648fe36ba0a1489bed804dfa0ac1e236101e4724bf9dbc74212b39b4b449bR113

2023-01-19 13:46 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
@dg0yt 
I didn't delete the targets for `tinyobjloader`. It wasn't there. Also the `findorfetch` are finding the `tinyobjloader`, but not adding it to linker library. not sure why.
Can You take a look on the fix I made? 
Take a look for the new code I added:
https://github.com/microsoft/vcpkg/pull/28993/files#diff-408648fe36ba0a1489bed804dfa0ac1e236101e4724bf9dbc74212b39b4b449bR113

2023-01-19 14:30 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
@dg0yt 
I removed:
```
link_directories(
  ${Qhull_DIR}/../../lib
)
``` 
And I change the target of mujoco to be like this:
```
target_link_libraries(
  mujoco
  PRIVATE ccd
          lodepng
          Qhull::qhull_r
          tinyobjloader::tinyobjloader
          tinyxml2::tinyxml2
)
```

Now I have a new error:
Can you help me with that?
```
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification
   Creating library lib\mujoco.lib and object lib\mujoco.exp
xml_native_writer.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall mj_XMLPrinter::~mj_XMLPrinter(void)" (__imp_??1mj_XMLPrinter@@UAE@XZ) referenced in function "enum tinyxml2::XMLError __cdecl SaveFile(class tinyxml2::XMLDocument &,struct _iobuf *)" (?SaveFile@@YA?AW4XMLError@tinyxml2@@AAVXMLDocument@2@PAU_iobuf@@@Z)
xml_native_writer.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall mj_XMLPrinter::mj_XMLPrinter(struct _iobuf *,bool,int)" (__imp_??0mj_XMLPrinter@@QAE@PAU_iobuf@@_NH@Z) referenced in function "enum tinyxml2::XMLError __cdecl SaveFile(class tinyxml2::XMLDocument &,struct _iobuf *)" (?SaveFile@@YA?AW4XMLError@tinyxml2@@AAVXMLDocument@2@PAU_iobuf@@@Z)

bin\mujoco.dll : fatal error LNK1120: 2 unresolved externals
```

Current PR is done without these errors.

2023-01-19 23:25 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
@dg0yt 
`  Unknown CMake command "find_dependency".`

2023-01-20 02:09 UTC, BillyONeal reviewed
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See docs/examples/adding-an-explicit-usage.md for context.  
  
Can you please confirm that the following looks correct?
```
mujoco provides CMake targets:

    find_package(mujoco CONFIG REQUIRED)
    target_link_libraries(main PRIVATE mujoco::mujoco)
```

- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-01-20 06:34 UTC, talregev commented
> Can you please confirm that the following looks correct?
> 
> ```
> mujoco provides CMake targets:
> 
>     find_package(mujoco CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE mujoco::mujoco)
> ```

This is correct.

2023-01-20 20:54 UTC, BillyONeal commented on ports/mujoco/fix_dependencies.patch
> + )
> @dg0yt ` Unknown CMake command "find_dependency".`

That means you forgot an `include(CMakeFindDependencyMacro)`. See https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html

2023-01-20 21:06 UTC, talregev commented on ports/mujoco/fix_dependencies.patch
> + )
@BillyONeal Thank you!
I read this docs, but I didn't understand I need to include this macro. Now I know.
Now I tested it with `find_dependency` and it still give me the same errors like `find_packages` (with the changes I made):

```
xml_native_writer.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl mj_XMLPrinter::~mj_XMLPrinter(void)" (__imp_??1mj_XMLPrinter@@UEAA@XZ) referenced in function "enum tinyxml2::XMLError __cdecl SaveFile(class tinyxml2::XMLDocument &,struct _iobuf *)" (?SaveFile@@YA?AW4XMLError@tinyxml2@@AEAVXMLDocument@2@PEAU_iobuf@@@Z)
xml_native_writer.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl mj_XMLPrinter::mj_XMLPrinter(struct _iobuf *,bool,int)" (__imp_??0mj_XMLPrinter@@QEAA@PEAU_iobuf@@_NH@Z) referenced in function "enum tinyxml2::XMLError __cdecl SaveFile(class tinyxml2::XMLDocument &,struct _iobuf *)" (?SaveFile@@YA?AW4XMLError@tinyxml2@@AEAVXMLDocument@2@PEAU_iobuf@@@Z)
```

I am not sure how to solve it, that why I am leaving the current state of the PR that it working.

2023-01-20 22:52 UTC, BillyONeal submitted a review, later dismissed
My fix attempt is at https://github.com/BillyONeal/vcpkg/commits/demo_PR_28993 . The include_directories still probably needs to be fixed and the licensing thing (where it looks like TinyXML code was copied into mujoco in contradiction of TinyXML's license) should be looked at by upstream.

2023-01-20 22:52 UTC, BillyONeal commented on ports/mujoco/fix_dependencies.patch
> + )
This is because this project "mujoco" is violating tinyxml2's license by copying code out of it and removing the license text.

![image](https://user-images.githubusercontent.com/1544943/213818443-27d71d8f-e64e-4506-a187-561991aa1129.png)

Here, when the cmake target is correctly used, `TINYXML2_LIB` becomes `__declspec(dllimport)` which causes the linker to be looking for a DLL that lives in rather than using it here.

Unfortunately upon discovery of this licensing problem I am not comfortable submitting a patch to fix it. From TinyXML:
![image](https://user-images.githubusercontent.com/1544943/213818649-b4fc8050-bc2d-4bea-880e-07f53b6c041d.png)

2023-01-21 00:03 UTC, talregev commented
@BillyONeal Thank you for the investigation. Can we fix `mujoco` that they will not violate the tinyxml2's license?
I mean for create a PR on mujoco. Not just a patch.

2023-01-23 21:06 UTC, BillyONeal commented
> @BillyONeal Thank you for the investigation. Can we fix `mujoco` that they will not violate the tinyxml2's license? I mean for create a PR on mujoco. Not just a patch.

We would be more than happy to add the port if this is fixed upstream. Technically the thing is licensed by upstream, not by us, but I don't want to be making major contributions myself while I have doubts and while I haven't brought in actual lawyers to take a look. I showed you where I got to by linking to what was my work in progress but stopped. Feel free to submit the exact change there upstream if you wish.

2023-02-02 17:53 UTC, saran-t commented
@BillyONeal could you please elaborate on your specific concern about tinyxml2?

MuJoCo does not redistribute tinyxml2 source code. The language in the tinyxml2 license relating to attribution specifically refers to source redistribution.

Although specific license attribution isn't required for binary distribution, we do nevertheless include it as part of our [prebuilt binary packages](https://github.com/deepmind/mujoco/releases/tag/2.3.1), as part of the `THIRD_PARTY_NOTICES` file.

2023-02-02 19:35 UTC, BillyONeal commented
> MuJoCo does not redistribute tinyxml2 source code. The language in the tinyxml2 license relating to attribution specifically refers to source redistribution.

The file in MuJoCo that says `TINYXML2_LIB` looks like it was copy pasted out of libxml2 which would require libxml2's license to be in that file. Why else would it have TINYXML2_LIB on the definition of anything? (That macro is the cause of the problem: it says 'TinyXML2 provides this thing', for example by saying `__declspec(dllimport)` on Windows, which fails because no DLL is providing those bits)

This doesn't mean we won't index the thing but it does mean that I stopped attempts at extensive patching to fix the problem. I provided the commit where I stopped that upstream may wish to take or not. I'm just paranoid about touching anything that may have the appearance or reality of copyright infringement.

2023-02-02 19:43 UTC, saran-t commented
> The file in MuJoCo that says `TINYXML2_LIB` looks like it was copy pasted out of libxml2 which would require libxml2's license to be in that file. Why else would it have TINYXML2_LIB on the definition of anything? (That macro is the cause of the problem: it says 'TinyXML2 provides this thing', for example by saying `__declspec(dllimport)` on Windows, which fails because no DLL is providing those bits)

That file isn't copied from anywhere, it's MuJoCo's own code. I'm double checking why we're declaring `TINYXML2_LIB` there but I suspect at some point (potentially still) we needed to do some gymnastics around visibility of the base class symbol on Linux.

By way of context, MuJoCo "official" dynamic library builds are statically linked against all of its dependencies but with symbols hidden to prevent conflict against other copies of those dependent libraries that user code might bring in. The reason that we do this is because we want to control dependency versions to ensure reproducibility of our physics calculations for users who use our official builds.

I hope this clears things up!

2023-02-08 07:12 UTC, talregev commented
@saran-t Thank you for your help!
@BillyONeal I updated to mujoco 2.3.2 and upstream remove the `TINYXML2_LIB`.
I also update the port according your comments. 
Can you review again?

2023-02-16 07:22 UTC, BillyONeal commented on ports/mujoco/vcpkg.json
> +  "supports": "!(windows & static)",
```
warning: DLLs should not be present in a static build, but the following DLLs were found:

    C:/Dev/vcpkg/packages/mujoco_x64-windows-static/bin/mujoco.dll
    C:/Dev/vcpkg/packages/mujoco_x64-windows-static/debug/bin/mujoco.dll

warning: There should be no bin\ directory in a static build, but C:\Dev\vcpkg\packages\mujoco_x64-windows-static\bin is present.
warning: There should be no debug\bin\ directory in a static build, but C:\Dev\vcpkg\packages\mujoco_x64-windows-static\debug\bin is present.
warning: If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them  
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: C:\Dev\vcpkg\ports\mujoco\portfile.cmake
```

This is caused by the SHARED in:
```
add_library(mujoco SHARED ${MUJOCO_RESOURCE_FILES})
```

Since you seem to be on good terms with upstream, can you ask/confirm why this is `SHARED`? (I ask because `x64-linux` and `x64-osx` are both static triplets; we just don't have a post-build check for them :) )

2023-02-16 07:47 UTC, talregev commented on ports/mujoco/vcpkg.json
> +  "supports": "!(windows & static)",
I don't have a relation with mujoco team. I just create my first issue there, and they accept to help. They are nice people.
Can you create another issue and explain that to them?

2023-02-16 07:48 UTC, talregev commented
> By way of context, MuJoCo "official" dynamic library builds

@BillyONeal This is answer your question?

2023-02-16 20:58 UTC, BillyONeal commented on ports/mujoco/vcpkg.json
> +  "supports": "!(windows & static)",
I would let them know that the right way to do that is to set `BUILD_SHARED_LIBS` as appropriate but if they aren't "actively present" that's OK.

2023-02-16 20:58 UTC, BillyONeal approved these changes

2023-02-16 21:32 UTC, merged