[libyuv] Update libyuv
microsoft/vcpkg pull request #29032
Opened 2023-01-18 02:12 UTC by cnSchwarzer

Reopen #28917 because of the accidental deletion of the branch. 😔
Also, update the REF to the latest upstream.

2023-01-18 13:20 UTC, Cheney-W requested changes

2023-01-18 13:27 UTC, Cheney-W requested changes

2023-01-18 13:27 UTC, Cheney-W commented on ports/libyuv/portfile.cmake
> +    # Manually build the port with clang-cl when using MSVC as compiler
As vicroms said before, this is not a change we can take. The compiler is a user setting, all ports must respect the compiler set by the toolchain. If you are worried about end-user performance, you could change this to a warning when building on MSVC.

2023-01-18 14:00 UTC, cnSchwarzer commented on ports/libyuv/portfile.cmake
> +    # Manually build the port with clang-cl when using MSVC as compiler
Forgotten

2023-01-18 14:04 UTC, cnSchwarzer commented on versions/l-/libyuv.json
> +    },
Forgotten

2023-01-18 14:16 UTC, cnSchwarzer commented on ports/libyuv/portfile.cmake
> +    # Manually build the port with clang-cl when using MSVC as compiler
I'm willing to wait for the meeting.

Restate my opinion: 
I think it is a kind of 'dogmatism' (unsure if the word is accurate) to not let a reasonable compiler change differently than the toolchain set. Because `libyuv` is not designed for x64 MSVC at all, many inline assembly accelerations are not enabled. And, I think most users want to keep their build settings simple, in other words, use `x64-windows` by default because it is tested by CI and ensures all ports are buildable. Forcing users to use a community triplet is a downgrade in that aspect.

From this consideration, I think doing jobs for the user to use `clang-cl` to replace `MSVC` ONLY for this port is acceptable for ordinary users, because the performance is what users want, and it requires users to do nothing, which is friendly. It is way better than showing a warning and letting the user switch to another community triplet, handling compiler errors if that triplet introduces other problems.

2023-01-19 21:16 UTC, BillyONeal commented on ports/libyuv/portfile.cmake
> +    # Manually build the port with clang-cl when using MSVC as compiler
The constraint is that if we have a user setting that controls a thing like the C++ compiler, ports need to respect that setting.

Looking at the examples dg0yt cited in the other PR:

> chromium

I don't believe this is the case, and it's one of the reasons the chromium port we have is fairly old.

> gmp

We use clang as an assembler here, not a C++ compiler. The "user compiler setting is respected" constraint isn't violated here.

> libxt

I guess I don't have much to say other that 'oops sorry we should not have merged that' 😳

2023-01-20 01:46 UTC, cnSchwarzer commented
OK, you guys know what you are doing, closing this PR

2023-01-20 01:46 UTC, closed without merging