Update workflow to the latest version 0.10.5
microsoft/vcpkg pull request #29060
Opened 2023-01-19 07:26 UTC by dengjunplusplus

**Describe the pull request**

- #### What does your PR fix?
  Update workflow to the latest version

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Not Changed

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

2023-01-20 02:59 UTC, Adela0814 requested changes

2023-01-20 02:59 UTC, Adela0814 commented on ports/workflow/portfile.cmake
> +endif()
You can set a variable for the value of this option to judge in the condition `if(VCPKG_LIBRARY_LINKAGE STREQUAL static)`.

2023-01-20 05:41 UTC, Adela0814 requested changes

2023-01-20 05:41 UTC, Adela0814 commented on ports/workflow/portfile.cmake
> +if(VCPKG_CRT_LINKAGE STREQUAL "static")
if (VCPKG_LIBRARY_LINKAGE STREQUAL static)

2023-01-20 06:54 UTC, dg0yt commented on ports/workflow/portfile.cmake
> +if(VCPKG_CRT_LINKAGE STREQUAL "static")
NO NO NO.

2023-01-20 06:57 UTC, dg0yt commented on ports/workflow/portfile.cmake
> +if(VCPKG_CRT_LINKAGE STREQUAL "static")
It is about runtime, isn't it?
And we want quotes around `static`.

2023-01-20 07:06 UTC, Adela0814 approved these changes, later dismissed

2023-01-21 06:12 UTC, BillyONeal requested changes

2023-01-21 06:12 UTC, BillyONeal commented on ports/workflow/portfile.cmake
> +    OPTIONS "${CONFIGURE_OPTIONS}"
```suggestion
    OPTIONS ${CONFIGURE_OPTIONS}
```

The name being plural suggests that this is intended to be expanded like a list but you are putting it in quotes here. Is that the intent?

2023-01-23 04:11 UTC, dengjunplusplus commented
@BillyONeal PTAL

2023-01-23 23:38 UTC, BillyONeal approved these changes

2023-01-23 23:38 UTC, merged

2023-01-23 23:38 UTC, BillyONeal commented
Thanks for the update!