[ffmpeg] add android support
microsoft/vcpkg pull request #29092
Opened 2023-01-21 13:07 UTC by lemourin

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-01-21 13:09 UTC, lemourin commented
@microsoft-github-policy-service agree [company="Google"]

2023-01-21 13:09 UTC, lemourin commented
@microsoft-github-policy-service agree company="Google"

2023-01-23 05:08 UTC, cnSchwarzer commented
Please wait for #28955

2023-01-23 18:31 UTC, vicroms requested changes

2023-01-23 18:31 UTC, vicroms commented on ports/ffmpeg/portfile.cmake
> +endif()
Ports are not allowed to change the compiler; this should respect the value set by `VCPKG_DETECTED_CMAKE_C_COMPILER`.

2023-01-23 22:32 UTC, lemourin commented on ports/ffmpeg/portfile.cmake
> +endif()
This is no longer necessary. Removed.

2023-01-23 23:44 UTC, BillyONeal approved these changes

2023-01-24 00:19 UTC, vicroms approved these changes

2023-01-24 00:52 UTC, merged

2023-01-24 00:52 UTC, BillyONeal commented
Thank you!

2023-02-14 11:54 UTC, shithappens2016 commented
@lemourin

#29649

not working on windows