[docs] Add note about when we add community triplets
microsoft/vcpkg pull request #29209
Opened 2023-01-27 01:39 UTC by BillyONeal

2023-01-28 06:13 UTC, Adela0814 requested changes

2023-01-28 06:13 UTC, Adela0814 commented on docs/maintainers/maintainer-guide.md
> +* It is demonstrated that people will actually use that community triplet; and,
Is there an extra 'and,' here?

2023-02-09 21:03 UTC, ras0219-msft commented on docs/maintainers/maintainer-guide.md
> +* It is demonstrated that people will actually use that community triplet; and,
This is intended style, to be read as though the bullets were concatenated:

> It is demonstrated that people will actually use that community triplet; and, we don't know that such a triplet is broken.

2023-02-09 23:07 UTC, ras0219-msft commented
Merged in Microsoft/vcpkg-docs#32

2023-02-09 23:07 UTC, closed without merging