[ffmpeg] enable auto-detect
microsoft/vcpkg pull request #29213
Opened 2023-01-27 10:45 UTC by cnSchwarzer

Fixes #29212

The last change to this port deletes `--disable-autodetect` and the author claims that disabling this meets the vcpkg guideline that this will prevent the port download dependency from other sources.

However, this constantly causes config errors on my side that some libraries cannot be found.

I think we either remove `--disable-autodetect` until all features are tested, or we let the CI to build all features. But even if the port can pass the CI, it is still not a guarantee that all user computer environments can pass the build.

I prefer adding it back.

2023-01-27 10:54 UTC, Neumann-A commented
> On my computer it cannot find schannel and I don't know why or what can explicitly enable to fix the issue. This problem even only popup on debug builds.

Which triplet ?

2023-01-27 11:03 UTC, cnSchwarzer commented
> > On my computer it cannot find schannel and I don't know why or what can explicitly enable to fix the issue. This problem even only popup on debug builds.
> 
> 
> 
> Which triplet ?

x64-windows

2023-01-27 11:18 UTC, cnSchwarzer commented
How did last PR even passed CI, the bin2c seems also a problem

2023-01-27 11:31 UTC, dg0yt commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
Is this not to run on osx or linux?
Also, if `bin2c` must run during the build, it must come from the host triplet. This is vcpkg.

2023-01-27 11:38 UTC, cnSchwarzer commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
I forget to make this patch MSVC only and now I fixed it.

I don't know every detail, but on my observation, if LLVM is found on PATH (like CI), then it will enable `cuda-llvm`, and the `bin2c` is needed for this feature. If there's no LLVM on PATH, then this bin2c is not needed, which is easy to omit this bug because this LLVM detect behaviour is invisible.

2023-01-27 11:45 UTC, cnSchwarzer commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
I don't think it is a vcpkg author's job to move bin2c to a separate host port, it is way too complicated and unnessesary in my opinion. I prefer a registry if it is a must.

2023-01-27 11:51 UTC, Neumann-A commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
>  separate host port, i

Same port just a host dependency. There are different bin2c from my experience so you always need the one the port actually builds.

2023-01-27 11:56 UTC, cnSchwarzer commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
Can I consider it as a "vcpkg-ify"? Because in this manner we should also extract `cuda-llvm` as a feature.

2023-01-27 14:12 UTC, Sibras commented
Quoting from the linked issue ticket:
portfile.cmake line 413: If openssl isnt used as a feature then schannel is enabled. Schannel is part of the windows SDK so if it cant be found then somethings gone wrong with your installation. The only thing that deleting '--disable-autodetect` is doing is allowing it to silently fail should schannel not be found, which is actually a bug in ffmpeg that is likely to be fixed in a future version. So a proper fix would be to correctly find schannel which seems to be a problem limited to your current setup.

2023-01-27 14:23 UTC, Sibras commented
For reference on `--disable-autodetect`:
Disabling autodetect is required as otherwise ffmpeg will automatically pull in dependency packages from the system (or any location found in PATH) instead of using the ones provided by vcpkg. This can be particular problematic on linux/osx as it can autodetect the presence of packages from apt/homebrew etc. that arent actually supported causing compilation/linker errors. By using `--disable-autodetect` then ffmpeg build scripts will only pull in dependency packages that are explicitly enabled in the vcpkg portfile which prevents undefined behavior on different systems.

2023-01-27 21:56 UTC, cnSchwarzer commented
Thank you guys! What about bin2c?

2023-01-28 15:44 UTC, Sibras commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
`cuda-llvm` should be added as a feature if wanting to use cuda files in ffmpeg. This is what bin2c is actually used for as ffmpegs build uses it to embed the compiled ptx into a c file that is then built into the library to be loaded at runtime. ffmpeg supports 2 different ways to use code written in cuda: 1) uses `cuda-nvcc` which requires the cuda sdk to be installed as it uses the nvcc compiler 2) `cuda-llvm` which uses clangs ptx backed to compile cuda. Both options compile cuda code to ptx that is then passed to bin2c. The main difference from an end user is that ffmpeg compiled using `cuda-nvcc` is non-redistributable due to license issues whereas `cuda-llvm` is fine.

However neither options are currently exposed by vcpkg so no cuda code is being used and thus bin2c should never be used. A stock vcpkg shouldnt be using bin2c at all. The issue your referring to about llvm being picked up when its in PATH and then `cuda-llvm` being auto enabled only happens when not using `--disable-autodetect`, which is why by default we use `--disable-autodetect` 😉 

So your PR is fixing an issue that your PR is actually causing in the first place 😜 . Of course if you do have a PR to add a cuda-llvm feature (feel free to submit one as its a useful feature) then that will expose any issues with bin2c which should be fixed as part that PR

2023-01-28 15:58 UTC, cnSchwarzer commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
Previously CI have LLVM on their path, thus cuda-llvm is auto enabled by default and result in bin2c failure. If both nvcc and clang are not found, bin2c is not used just like my computer.

2023-01-28 15:59 UTC, cnSchwarzer commented on ports/ffmpeg/0021-fix-bin2c.patch
> ++	$(CC) $(CFLAGS) -Foffbuild/bin2c.o -Feffbuild/bin2c.exe $(SRC_PATH)/ffbuild/bin2c.c
Oh, does auto-detect finds clang and enables cuda-llvm?

2023-01-29 03:43 UTC, cnSchwarzer commented
Hi guys, I have rewritten this PR, please have a look.

2023-01-29 05:59 UTC, Sibras commented on ports/ffmpeg/portfile.cmake
> +
It might be a good idea to throw in `--disable-cuda-nvcc` on both of these just to make sure

2023-01-29 06:00 UTC, Sibras commented on ports/ffmpeg/vcpkg.json
> +    },
cuda-llvm should be added to the `all` feature so that the CI tests it

2023-01-29 10:26 UTC, cnSchwarzer commented on ports/ffmpeg/portfile.cmake
> +
What about user just want to use nvcc?

2023-01-29 10:30 UTC, Sibras commented on ports/ffmpeg/portfile.cmake
> +
someone would have to add a separate feature for cuda-nvcc that depended upon the cuda sdk port. ffmpeg only supports one or the other, they cant be active at the same time

2023-01-29 13:13 UTC, Sibras commented on ports/ffmpeg/vcpkg.json
> +          "platform": "windows & linux"
This shouldnt be here as ffmpeg[non-free] pulls in everything from ffmpeg[all] so it will try and enable cuda-llvm and cuda-nvcc and then fail due to both being enabled. Since both do the exact same thing then probably just stick with cuda-llvm as the default.

2023-01-29 13:13 UTC, Sibras commented on ports/ffmpeg/vcpkg.json
> +    },
vcpkg has a port for detecting cuda sdk (port: 'cuda') so this should depend on that

2023-01-29 13:18 UTC, Sibras commented on ports/ffmpeg/portfile.cmake
> +    vcpkg_add_to_path(PREPEND "$ENV{CUDA_PATH}/bin")
Theres a vcpkg port for finding cuda sdk that adds a `vcpkg_find_cuda` function that I believe is the recommended way to find the cuda path as it works cross platform (I dont think the above works on linux etc.)

2023-01-29 13:22 UTC, Sibras commented on ports/ffmpeg/vcpkg.json
> +      "description": "Use LLVM clang ptx backend to compile CUDA files"
Should have a dependency on llvm added here. It doesnt need the full llvm maybe just llvm[clang] or llvm[tools], im not sure which one does what from a quick look.

2023-01-29 13:34 UTC, cnSchwarzer commented on ports/ffmpeg/vcpkg.json
> +    },
Thanks for telling that!

2023-01-29 13:38 UTC, cnSchwarzer commented on ports/ffmpeg/vcpkg.json
> +      "description": "Use LLVM clang ptx backend to compile CUDA files"
From my test, the llvm port is 14.0.7 which is old, and it takes years to compile, generating tons of GB data in buildtree, while the prebuilt one from vcpkg_find_acquire_program is faster and supports building ptx backend as well.

2023-01-29 16:56 UTC, Sibras commented on ports/ffmpeg/vcpkg.json
> +      "description": "Use LLVM clang ptx backend to compile CUDA files"
Yep your right, I missed the use of `vcpkg_find_acquire_program` to get clang, which is the correct approach

2023-01-31 13:57 UTC, cnSchwarzer commented
Anyone have a look tonight?

2023-02-01 06:17 UTC, LilyWangLL commented
Feature `cuda-llvm` and `cuda-nvcc` test pass on `x64-windows`.

2023-02-01 06:17 UTC, LilyWangLL submitted a review, later dismissed

2023-02-01 06:53 UTC, cnSchwarzer commented on ports/ffmpeg/portfile.cmake
> +    vcpkg_find_cuda(OUT_CUDA_TOOLKIT_ROOT CUDA_TOOLKIT_ROOT)
I'm also confused about include, but I didn't take time to investigate, I thought it is unnessesary at all?

2023-02-01 06:58 UTC, dg0yt commented on ports/ffmpeg/portfile.cmake
> +    vcpkg_find_cuda(OUT_CUDA_TOOLKIT_ROOT CUDA_TOOLKIT_ROOT)
ATM it is necessary. I'm asking (not you personally) if this needs to be fixed in port cuda.

2023-02-01 07:04 UTC, cnSchwarzer commented on ports/ffmpeg/portfile.cmake
> +    vcpkg_find_cuda(OUT_CUDA_TOOLKIT_ROOT CUDA_TOOLKIT_ROOT)
Yes, I think it should.

2023-02-03 12:02 UTC, cnSchwarzer commented
Can we merge this now? 👀

2023-02-07 02:17 UTC, LilyWangLL commented
> Can we merge this now? 👀

Please resolve the conflicts.

2023-02-07 07:42 UTC, cnSchwarzer commented
Fixes #29489

2023-02-08 03:22 UTC, cnSchwarzer commented
@LilyWangLL 😘

2023-02-08 06:15 UTC, FrankXie05 requested changes

2023-02-08 06:15 UTC, FrankXie05 commented on ports/mfx-dispatch/fix-vcpkg.patch
> +-    src/mfx_critical_section_linux.cpp
```suggestion
-  list(APPEND SOURCES
-    src/mfx_library_iterator_linux.cpp
-    src/mfx_load_dll_linux.cpp
-    src/mfx_critical_section_linux.cpp
```
If `linux` uses make to build, do we still need to delete this files?

2023-02-08 06:15 UTC, FrankXie05 commented on ports/mfx-dispatch/portfile.cmake
> +    vcpkg_configure_make(
```suggestion
    vcpkg_cmake_configure(
```
Please use the new function.

2023-02-08 06:15 UTC, FrankXie05 commented on ports/mfx-dispatch/portfile.cmake
> +    vcpkg_configure_cmake(
```suggestion
    vcpkg_cmake_configure(

```

2023-02-08 06:15 UTC, FrankXie05 commented on ports/mfx-dispatch/portfile.cmake
> +    vcpkg_install_cmake()
```suggestion
    vcpkg_cmake_install()

```

2023-02-08 06:39 UTC, LilyWangLL requested changes

2023-02-08 06:39 UTC, LilyWangLL commented on ports/mfx-dispatch/portfile.cmake
> +    REF 1.35.1
```suggestion
    REF "${VERSION}"
```

2023-02-08 06:44 UTC, cnSchwarzer commented on ports/mfx-dispatch/fix-vcpkg.patch
> +-    src/mfx_critical_section_linux.cpp
It doesn't matter, because use cmake to build linux is completely broken.

2023-02-08 07:01 UTC, cnSchwarzer commented
Resolved

2023-02-08 07:06 UTC, FrankXie05 commented
Feature `qsv` successfully tested in the local `linux` triplet.

2023-02-08 07:52 UTC, LilyWangLL submitted a review, later dismissed

2023-02-08 07:54 UTC, FrankXie05 approved these changes, later dismissed

2023-02-09 04:51 UTC, cnSchwarzer commented
This also ready, don't miss it😘

2023-02-09 22:58 UTC, JavierMatosD commented
I believe this violates our "don't implement features as alternatives" policy https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives.

2023-02-10 02:43 UTC, cnSchwarzer commented
It is a true world situation and I prefer blaming the vcpkg and its policy for not covering such situation.

We really should provide some "switch" for such alternative behaviour. I personally saw many ports have this problem like mimalloc, etc.

In this case, user can have the right to choose whether use cuda or not, whether to use nvcc or llvm to compile cuda codes. None of them can be made default behaviour. Since this will eventually violates vcpkg's policy, what else can port author do? Maybe abandon this PR for good.

This is a vcpkg design flaw that should be improved.

2023-02-14 01:31 UTC, cnSchwarzer commented
Might you guys team-review this PR? @vicroms @BillyONeal 

I remember that we have encountered this many times, it is totally unnecessary to achieve the "alternative" in another much complicated approach.

2023-02-18 06:55 UTC, Sibras commented
> I believe this violates our "don't implement features as alternatives" policy https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives.

If the cuda compilation alternatives are an issue then the cuda-nvcc can be removed as its not really all that useful, as it and cuda-llvm do the exact same thing just the later results in a non-redistributable binary whereas the first one doesn't. Which means theres not really much practical use having it apart from giving downstream users an option, although in this case the option doesnt provide any advantages

2023-02-21 01:26 UTC, cnSchwarzer commented
Any update?

2023-02-21 09:23 UTC, BillyONeal commented
> Any update?

I don't expect there to be a substantial update until we have addressed the alternatives problem which we might start at the earliest at the end of March.

2023-02-21 09:27 UTC, cnSchwarzer commented
OK, I'll wait. Meanwhile, I will remove cuda-nvcc for good for now.

2023-02-22 01:34 UTC, cnSchwarzer commented
Removed cuda-nvcc. Please review again.

2023-02-27 23:04 UTC, JavierMatosD commented
We aren't comfortable changing the default for CUDA compiles from nvcc at this time. As a result, we won't be able to accept a PR with effects like this until we have a better overall answer for alternatives.

2023-02-27 23:04 UTC, JavierMatosD reviewed
We aren't comfortable changing the default for CUDA compiles from nvcc at this time. As a result, we won't be able to accept a PR with effects like this until we have a better overall answer for alternatives.

2023-02-28 01:36 UTC, cnSchwarzer commented
OK, let's wait for that😘

2023-04-01 14:11 UTC, cnSchwarzer commented
Any update on this?

2023-04-13 02:24 UTC, cnSchwarzer commented
@BillyONeal @JavierMatosD @vicroms Hi guys, any discussion on this alternative feature thing? 😘

2023-04-25 09:06 UTC, LilyWangLL commented
> @BillyONeal @JavierMatosD @vicroms Hi guys, any discussion on this alternative feature thing? 😘

Pinging @BillyONeal @JavierMatosD for response.

2023-04-27 00:07 UTC, BillyONeal commented
> > @BillyONeal @JavierMatosD @vicroms Hi guys, any discussion on this alternative feature thing? 😘
> 
> Pinging @BillyONeal @JavierMatosD for response.

Alternatives didn't make the cut line for Gallium so it's unlikely we'll be working on them before September.

2023-04-27 00:43 UTC, cnSchwarzer commented
> > > @BillyONeal @JavierMatosD @vicroms Hi guys, any discussion on this alternative feature thing? 😘
> 
> > 
> 
> > Pinging @BillyONeal @JavierMatosD for response.
> 
> 
> 
> Alternatives didn't make the cut line for Gallium so it's unlikely we'll be working on them before September.

Gallium is some milestone codename?

2023-04-27 00:46 UTC, BillyONeal commented
> Gallium is some milestone codename?

Yeah, all the Azure/DevDiv/etc. projects are on this every-6-months-or-so schedule where each block is the next element. Zinc ended March 31, Gallium ends ~ September, then Germanium will end next March.

2023-04-27 11:19 UTC, cnSchwarzer commented
OK let's wait

2023-04-28 02:01 UTC, LilyWangLL commented
> OK let's wait

I am converting this PR to draft for now.

2023-09-26 07:13 UTC, cnSchwarzer commented
Hi @BillyONeal , Its near October, any uodate on alternative feature?

2024-11-07 23:58 UTC, closed without merging