[zstr] Update to 1.0.7
microsoft/vcpkg pull request #29254
Opened 2023-01-29 19:18 UTC by chausner

Updates zstr to 1.0.7

* [x]  Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
* [x]  SHA512s are updated for each updated download
* [x]  The "supports" clause reflects platforms that may be fixed by this new version
* [x]  Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
* [x]  Any patches that are no longer applied are deleted from the port's directory.
* [x]  The version database is fixed by rerunning ./vcpkg x-add-version --all and committing the result.
* [x]  Only one version is added to each modified port's versions file.

2023-01-30 08:54 UTC, LilyWangLL requested changes

2023-01-30 08:54 UTC, LilyWangLL commented on ports/zstr/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2023-01-30 08:54 UTC, LilyWangLL commented on ports/zstr/portfile.cmake
> +  REF v1.0.7
```suggestion
  REF "v${VERSION}"
```

2023-01-30 08:54 UTC, LilyWangLL commented on ports/zstr/portfile.cmake
>  vcpkg_from_github(
```suggestion
# header-only library
vcpkg_from_github(
```

2023-01-30 08:54 UTC, LilyWangLL commented on ports/zstr/usage
> +    find_package(ZLIB REQUIRED)
This file could be removed, vcpkg will output after install succeed.
```
zstr is header-only and can be used from CMake via:

    find_path(ZSTR_INCLUDE_DIRS "strict_fstream.hpp")
    target_include_directories(main PRIVATE ${ZSTR_INCLUDE_DIRS})
```

2023-01-30 08:54 UTC, LilyWangLL commented on ports/zstr/portfile.cmake
> +file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion
```

2023-01-30 18:24 UTC, chausner commented on ports/zstr/usage
> +    find_package(ZLIB REQUIRED)
Consumers of zstr are required to link to zlib, otherwise the header file cannot be used. That's why I went with the custom usage file.

2023-01-31 02:47 UTC, LilyWangLL approved these changes

2023-01-31 21:27 UTC, merged

2023-01-31 21:27 UTC, BillyONeal commented
Thanks for the update!