[google-cloud-cpp] upgrade to latest version (v2.7.0)
microsoft/vcpkg pull request #29373
Opened 2023-02-01 21:43 UTC by coryan

Updates `google-cloud-cpp` to the latest release (v2.7.0), and add feature `gkemulticloud`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-02-02 00:14 UTC, coryan commented
I tested the new feature locally with `vcpkg install google-cloud-cpp[core,gkemulticloud]`.  I also tested with `vcpkg install google-cloud-cpp[*]`.

2023-02-02 03:01 UTC, MonicaLiu0311 commented
> I tested the new feature locally with vcpkg install google-cloud-cpp[core,gkemulticloud]. I also tested with vcpkg install google-cloud-cpp[*].

Thanks for your contribution, next I will feature test the following triplets:
x86-windows
x64-windows
x64-windows-static

2023-02-03 08:32 UTC, MonicaLiu0311 commented
Because there are too many features, only the new `gkemulticloud` was tested, but not all of them.

Feature `gkemulticloud` is tested successfully in the following triplet:
x86-windows
x64-windows
x64-windows-static

2023-02-03 08:33 UTC, MonicaLiu0311 approved these changes

2023-02-03 20:35 UTC, BillyONeal requested changes

2023-02-03 20:35 UTC, BillyONeal commented on ports/google-cloud-cpp/vcpkg.json
> +    "gkemulticloud": {
It looks like you forgot to hook up this feature in `portfile.cmake`?

2023-02-03 20:43 UTC, coryan commented
There should be no need.  The portfile (and the project for that matter) are designed to add features without requiring a change.

2023-02-03 21:03 UTC, BillyONeal commented
> There should be no need. The portfile (and the project for that matter) are designed to add features without requiring a change.

Oh. Sorry for missing that; just passing the feature list directly into upstream is a pattern I haven't seen before, sorry for the confusion on my part!

2023-02-03 21:03 UTC, BillyONeal approved these changes
Thanks for the update!

2023-02-03 21:04 UTC, merged

2023-02-03 21:08 UTC, coryan commented
> Oh. Sorry for missing that; just passing the feature list directly into upstream is a pattern I haven't seen before, sorry for the confusion on my part!

No problem.  I know it is a bit odd.  It is also odd that we have so many features.