[sonic] Add new port
microsoft/vcpkg pull request #29374
Opened 2023-02-01 23:46 UTC by ex-purple

Fixes https://github.com/microsoft/vcpkg/issues/26423

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See docs/examples/adding-an-explicit-usage.md for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2023-02-02 08:05 UTC, Cheney-W requested changes

2023-02-02 18:46 UTC, ex-purple commented on ports/sonic/vcpkg.json
> +  "name": "sonic",
@Cheney-W should I change folder name too?

2023-02-03 02:47 UTC, Cheney-W commented on ports/sonic/vcpkg.json
> +  "name": "sonic",
Yes

2023-02-03 09:07 UTC, Cheney-W approved these changes, later dismissed

2023-02-03 22:20 UTC, BillyONeal requested changes, later dismissed
Thanks for the new port!

2023-02-03 22:20 UTC, BillyONeal commented on ports/libsonic/makefile.patch
> ++SUFFIX=so
It seems like this is building dynamic libs for a static triplet (of which both `x64-linux` and `x64-osx` are). Can you describe why we don't need to take steps to make those .sos relocatable?

(Note that the community triplets use `patchelf` to resolve this: https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/z_vcpkg_fixup_rpath.cmake )

2023-02-03 22:20 UTC, BillyONeal commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
Is there a good reason this isn't using the `vcpkg_*_make` family? As written this isn't properly passing `VCPKG_C_FLAGS` et al. into the build system.

2023-02-03 23:00 UTC, ex-purple commented on ports/libsonic/makefile.patch
> ++SUFFIX=so
The original sonic project build both static and dynamic libraries. I separate these targets and add a LINKAGE variable to the Makefile that copies VCPKG_LIBRARY_LINKAGE value. So static or dinamic library will be build depens on VCPKG_LIBRARY_LINKAGE value.

2023-02-03 23:08 UTC, ex-purple commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
How to force vcpkg_*_make functions work with the ${SOURCE_PATH} directory instead of ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel and -dbg directories?

Also, I tried to copy the files from ${SOURCE_PATH} to  ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel but vcpkg_*_make is cleaning this folder before start building

2023-02-04 04:36 UTC, dg0yt commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
I you need in-source build, pass `COPY_SOURCE` to `vcpkg_configure_make`.

2023-02-04 19:42 UTC, ex-purple commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
> pass COPY_SOURCE to vcpkg_configure_make

It looks like an [undocumented](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_make.mdl) flag

I tried it and I have:
```CMake
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:157 (message):
Could not determine method to configure make
```

I also tried adding the SKIP_CONFIGURE flag, but it did not help.

2023-02-04 21:31 UTC, dg0yt commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
Maybe not documented, but implemented and used, e.g. by port libidn2.
Are you sure you didn't make typo?

2023-02-05 00:09 UTC, ex-purple commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
> Are you sure you didn't make typo?

These changes have been committed. Now you can check it

2023-02-15 19:27 UTC, ex-purple commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
@dg0yt, @BillyONeal should I revert changes? Looks like  vcpkg_*_make is not working here

2023-04-14 05:04 UTC, BillyONeal commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
Wow, sorry I left you hanging, I was under the gun from some other deadline stuff and this got lost in the shuffle.

I don't care specifically that the `vcpkg_*_make` family is used, only that the various knobs that we give users to set things up, like `VCPKG_CXX_FLAGS`, are appropriately connected. I don't really have a good understanding of the relative cost of wiring all that up in terms of `vcpkg_cmake_get_vars` and plumbing the results all over the place vs. calling the `vcpkg_*_make` family, but it seems very likely that the latter will be easier to do overall.

Alternately, the upstream build system looks very simple; perhaps we could author our own `CMakeLists.txt` and submit one upstream rather than trying to adapt what upstream did in the first place? That seems likely to be simpler than any of the options trying to cobble random makefiles in here.

2023-04-14 05:05 UTC, BillyONeal commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
To that end I note that the makefile patch is probably longer than a `CMakeLists.txt` is going to be.

2023-04-28 03:02 UTC, Cheney-W commented
Pinging @ex-purple Could you please address the review suggestions of Billy? Thanks!

2023-05-05 10:17 UTC, Cheney-W commented
I will be converting your PR to draft status. When you addressed the review suggestions of Billy, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-05-08 00:06 UTC, ex-purple commented on ports/libsonic/portfile.cmake
> +if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
It makes sense
I will add CMakeLists.txt

2023-05-08 03:56 UTC, dg0yt requested changes
Shouldn't  the tool be controlled by feature (and not be built for debug)?

2023-05-08 03:56 UTC, dg0yt commented on ports/libsonic/CMakeLists.txt
> +)
You must set the `OUTPUT_NAME` OR `PREFIX` properties to avoid "liblibsonic" filenames.

2023-05-08 03:56 UTC, dg0yt commented on ports/libsonic/vcpkg.json
> +    }
Cmake config fixup isn't used AFAICS

2023-05-08 03:56 UTC, dg0yt commented on ports/libsonic/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
Missing double quotes.

2023-05-08 06:24 UTC, Cheney-W commented
Converted PR to draft status. When you addressed the review suggestions of Dg0yt, please revert to "ready for review".

2023-05-08 09:14 UTC, ex-purple commented on ports/libsonic/CMakeLists.txt
> +)
Fixed

2023-05-08 09:14 UTC, ex-purple commented on ports/libsonic/vcpkg.json
> +    }
Fixed

2023-05-08 09:14 UTC, ex-purple commented on ports/libsonic/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
Fixed

2023-05-08 10:38 UTC, Cheney-W submitted a review, later dismissed

2023-05-08 10:56 UTC, Cheney-W commented
The [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md) does not mandate that the `tool` must exist as a feature, but having the tool as a feature and building it only in release mode can save library build time.
If you would like to add the `tool` as a feature, you can refer to https://github.com/microsoft/vcpkg/tree/master/ports/cmark for modifications.

2023-05-08 17:26 UTC, vicroms commented
This looks good enough to merge, some things that would improve the port:

* making the tool optional by using a feature
* exporting CMake targets or a usage file

@ex-purple is your call if you want me to merge as-is or want to try implementing the suggestions

2023-05-08 20:52 UTC, ex-purple commented
@vicroms 

Okay, I agree to make the tool optional by using a feature. And I did it now.

But I don't like the idea of adding something extra to the upstream installation. So, I won't add export targets because upstream installation doesn't contains this.

2023-05-08 22:06 UTC, merged