WIP: [intel-mkl] install mkl instead of requesting the user to install it
microsoft/vcpkg pull request #29437
Opened 2023-02-03 23:16 UTC by Neumann-A

2023-02-06 09:08 UTC, JackBoosY commented
So I can close my PR https://github.com/microsoft/vcpkg/pull/15233 now?

2023-02-06 09:20 UTC, Neumann-A commented
@JackBoosY didn't even know that it was brokn on linux.

2023-02-06 09:24 UTC, JackBoosY commented
> @JackBoosY didn't even know that it was brokn on linux.

That's not broken, that's not supported.

2023-02-07 09:18 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +      vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/mkl.pc" "/lib/intel64" "/../lib/intel64")
```suggestion
      vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/mkl.pc" "/lib/intel64" "/../lib/intel64")
      vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/mkl.pc" "openmp" "libiomp5")
```

2023-02-07 09:19 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +    configure_file("${basepath}lib/pkgconfig/mkl-${VCPKG_LIBRARY_LINKAGE}-${interface}-${short_thread}.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/mkl.pc" @ONLY)
```suggestion
    configure_file("${basepath}lib/pkgconfig/mkl-${VCPKG_LIBRARY_LINKAGE}-${interface}-${short_thread}.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/mkl.pc" @ONLY)
    vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/lib/pkgconfig/mkl.pc" "openmp" "libiomp5")
```

2023-02-27 02:05 UTC, JackBoosY commented on ports/intel-mkl/vcpkg.json
> +  "supports": "(windows | linux) & x64",
what about osx?

2023-02-27 02:05 UTC, JackBoosY commented on ports/intel-mkl/portfile.cmake
> +  set(ProgramFilesx86 "ProgramFiles(x86)")
I guess here is never executed?

2023-02-27 08:52 UTC, Neumann-A commented on ports/intel-mkl/vcpkg.json
> +  "supports": "(windows | linux) & x64",
As mentioned in the portfile:

> This is a disk image: If somebody knows how to extract it please do so. 

Since the port was broken on linux before I assumed it also to be broken for osx which is also displayed by the ci baseline. Furhtermore since I don't have access to osx to test stuff out I left the status of osx as is. (But maybe I should remove all intel-mkl entries from the baseline?)

2023-02-27 08:53 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +  set(ProgramFilesx86 "ProgramFiles(x86)")
The question here is if there should be a no-install feature which is why I left the code here so I don't have to recover it if that is requested.

2023-03-03 08:33 UTC, Neumann-A commented
> Could NOT find MKL (missing: mkl_intel_ilp64_file)

OK that error is kind of expected since I only install either `ilp` or `lp` libs so I probably need to adjust the config but the real usage is via FindBLAS and FindLAPACK ;)

2023-03-06 02:28 UTC, MonicaLiu0311 approved these changes, later dismissed

2023-03-08 00:15 UTC, Bzz2745 commented
OS:Linux Ubunru 2022.4
Complier:gcc11
 When I need to build intel-mkl it alway tell me to install intel-mkl even I have installed version 2022.4 of intel-mkl (highter than 202000),I have also add it to .zshrc but still not work.How can I solve this?

2023-03-08 03:10 UTC, JackBoosY requested changes

2023-03-08 04:03 UTC, Bzz2745 commented on ports/arrayfire/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS AND VCPKG_CRT_LINKAGE STREQUAL "static")
I have edited it now but the error still existing. 
![图片](https://user-images.githubusercontent.com/68807654/223616760-db91c79a-c69f-4597-98ff-089943464085.png)
![图片](https://user-images.githubusercontent.com/68807654/223616673-1f2789b1-a0a9-4f58-a04f-979f0e495d01.png)

2023-03-08 04:04 UTC, MonicaLiu0311 commented
Installation fails on linux:
```
monica@monica003:~/mkl$ ./vcpkg install intel-mkl
Computing installation plan...
A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz->/home/monica/mkl/downloads/cmake-3.25.1-linux-x86_64.tar.gz
Extracting cmake...
The following packages will be built and installed:
    intel-mkl[core]:x64-linux -> 2023.0.0
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/monica/.cache/vcpkg/archives in 6.3 us. Use --debug to see more details.
Installing 1/1 intel-mkl:x64-linux...
Building intel-mkl[core]:x64-linux...
-- Downloading https://registrationcenter-download.intel.com/akdlm/IRC_NAS/19138/l_onemkl_p_2023.0.0.25398_offline.sh -> l_onemkl_p_2023.0.0.25398_offline.sh...
CMake Warning at ports/intel-mkl/portfile.cmake:185 (message):
  This port is still a work on progress on linux.  E.g.  it is not correctly
  filtering the libraries in accordance with VCPKG_LIBRARY_LINKAGE.
  Furthermore it is using the default threading which is Intel OpenMP which
  is known to segfault if GNU OpenMP is also used elsewhere!
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


-- /home/monica/mkl/downloads/l_onemkl_p_2023.0.0.25398_offline.sh
CMake Error at ports/intel-mkl/portfile.cmake:227 (file):
  file COPY cannot copy file
  "/home/monica/mkl/packages/intel-mkl_x64-linux/intel-extract/_installdir/mkl/2023.0.0/lib/intel64/libmkl_core.a"
  to
  "/home/monica/mkl/packages/intel-mkl_x64-linux/lib/intel64/libmkl_core.a":
  Success.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

```

2023-03-08 04:57 UTC, Bzz2745 commented
> Installation fails on linux:
> 
> ```
> monica@monica003:~/mkl$ ./vcpkg install intel-mkl
> Computing installation plan...
> A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
> Downloading cmake...
> https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz->/home/monica/mkl/downloads/cmake-3.25.1-linux-x86_64.tar.gz
> Extracting cmake...
> The following packages will be built and installed:
>     intel-mkl[core]:x64-linux -> 2023.0.0
> Detecting compiler hash for triplet x64-linux...
> Restored 0 package(s) from /home/monica/.cache/vcpkg/archives in 6.3 us. Use --debug to see more details.
> Installing 1/1 intel-mkl:x64-linux...
> Building intel-mkl[core]:x64-linux...
> -- Downloading https://registrationcenter-download.intel.com/akdlm/IRC_NAS/19138/l_onemkl_p_2023.0.0.25398_offline.sh -> l_onemkl_p_2023.0.0.25398_offline.sh...
> CMake Warning at ports/intel-mkl/portfile.cmake:185 (message):
>   This port is still a work on progress on linux.  E.g.  it is not correctly
>   filtering the libraries in accordance with VCPKG_LIBRARY_LINKAGE.
>   Furthermore it is using the default threading which is Intel OpenMP which
>   is known to segfault if GNU OpenMP is also used elsewhere!
> Call Stack (most recent call first):
>   scripts/ports.cmake:147 (include)
> 
> 
> -- /home/monica/mkl/downloads/l_onemkl_p_2023.0.0.25398_offline.sh
> CMake Error at ports/intel-mkl/portfile.cmake:227 (file):
>   file COPY cannot copy file
>   "/home/monica/mkl/packages/intel-mkl_x64-linux/intel-extract/_installdir/mkl/2023.0.0/lib/intel64/libmkl_core.a"
>   to
>   "/home/monica/mkl/packages/intel-mkl_x64-linux/lib/intel64/libmkl_core.a":
>   Success.
> Call Stack (most recent call first):
>   scripts/ports.cmake:147 (include)
> ```

I installed it by install Intel OneAPI which include this.

2023-03-08 13:44 UTC, Neumann-A commented on ports/arrayfire/portfile.cmake
> +if(VCPKG_TARGET_IS_WINDOWS AND VCPKG_CRT_LINKAGE STREQUAL "static")
@JackBoosY I assume that should be applied to both statements?

2023-03-08 15:44 UTC, Bzz2745 commented
@MonicaLiu0311  @JackBoosY   I have successfully build it with this:
![图片](https://user-images.githubusercontent.com/68807654/223758709-9f75e8b3-b573-4e1c-a6b2-c49700381828.png)
But I really can't understand why this didn't fixed since THREE YEARS ago when the first one upload this bug ?

2023-03-09 06:51 UTC, MonicaLiu0311 commented
The usage test passed (header files found): 
```
intel-mkl provides CMake targets:

    find_package(MKL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE MKL::MKL)
```

2023-03-09 07:54 UTC, MonicaLiu0311 submitted a review, later dismissed

2023-03-09 08:01 UTC, MonicaLiu0311 commented
> Why merging is blocked? Can we re-trigger the GitHub actions?

Maybe because the above review comments did not detect changes?
https://github.com/microsoft/vcpkg/pull/29437#discussion_r1128930665

2023-03-09 22:04 UTC, talregev commented
> Why merging is blocked? Can we re-trigger the GitHub actions?

Maybe need to push on the bot to review it again? 

Push on the red symbol to review again:
![image](https://user-images.githubusercontent.com/7043539/224170592-0554d7fb-a1d4-467f-8e25-75cb103db796.png)

2023-03-10 02:00 UTC, dan-shaw approved these changes, later dismissed
I noticed `libiomp5md_db.dll` in `lib/` when targeting `x64-windows`. Is that expected?

2023-03-10 20:37 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +                      "${CURRENT_PACKAGES_DIR}/manual-tools"
No I want to completely remove this folder. It was just used as a staging dir for extraction.

2023-03-10 20:42 UTC, Neumann-A commented
> I noticed libiomp5md_db.dll in lib/ when targeting x64-windows. Is that expected?

I don't know what that file is for but it comes from the upstream lib folder which is why I left it in. I think it probably can be removed but didn't want to touch it since there must be some reason why it exists.

2023-03-10 21:04 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +# Due to the complexity involved, this package doesn't install MKL. It instead verifies that MKL is installed.
done

2023-03-11 16:32 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +  # This is a disk image: If somebody knows how to extract it please do so.
The disk image is easy to mount, however the actual installer asks for admin privileges. I didn't find much hints.
Is it an option to take the files from `pip install` instead? It provides includes, libs, pc files, cmake files. But it bypasses the regular caching.
~~~
  x_vcpkg_get_python_packages(PYTHON_VERSION "3" PACKAGES mkl==2023.0.0 mkl-devel==2023.0.0 mkl-include==2023.0.0 mkl-static==2023.0.0 OUT_PYTHON_VAR "PYTHON3")
~~~

2023-03-12 22:45 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +  # This is a disk image: If somebody knows how to extract it please do so.
It seems that 7zip is able to extract the image but unless vcpkg solves it tool issue that is not going to happen.

2023-03-12 22:48 UTC, talregev commented on ports/intel-mkl/portfile.cmake
> +  # This is a disk image: If somebody knows how to extract it please do so.
@Neumann-A 
What is the tool issue?

2023-03-13 11:34 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +  # This is a disk image: If somebody knows how to extract it please do so.
My comment was entirely unrelated to 7z. On macOS, you can mount the DMG using `hdiutil`. But you don't get much more than a Qt based (offline) installer.

2023-03-13 20:38 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +  # This is a disk image: If somebody knows how to extract it please do so.
All of the downloaded files are installers. Even the "shell script" on linux. The point is to manually extract these installers and move the necessary stuff to the correct location.

2023-03-20 08:27 UTC, merged

2023-03-23 07:30 UTC, FrankXie05 commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
It seems that `intel-mkl` is not properly installed on Linux, at least `${MKL_ROOT}` does not appear on my virtual machine. And not found under `/opt/`
```
ninja: error: 'MKL_RT_LINK_LIBRARY-NOTFOUND',needed by 'src/exe/colmap', missing and no known rule to make it
```
@Neumann-A

2023-03-23 07:34 UTC, talregev commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
It install intel-mkl under installed.
I install intel-mkl on my linux vm: 
![image](https://user-images.githubusercontent.com/7043539/227134356-bbbd4323-6db2-4c45-a7e2-1223ad583293.png)

2023-03-23 07:55 UTC, talregev commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
Maybe we can patch all the ports that use mkl that will fit both linux and windows?

2023-03-23 08:49 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
Tracing cmake config for dbow2 in #30363 now.

2023-03-24 06:51 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
For dbow2, the intel-mkl dependency is coming from suitesparse:
`/mnt/vcpkg-ci/installed/x64-linux/share/suitesparse/suitesparse-targets-debug.cmake(75):  set_target_properties(SuiteSparse::cholmod PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG C IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG metis;SuiteSparse::amd;SuiteSparse::camd;SuiteSparse::colamd;SuiteSparse::ccolamd;SuiteSparse::suitesparseconfig;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/liblapack.a;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libgfortran.so.5;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_thread.a;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_core.a;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_thread.a;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_core.a;/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl IMPORTED_LOCATION_DEBUG /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libcholmodd.a )
`

2023-03-24 07:24 UTC, Neumann-A commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
Hmm does suitesparse even depend on intel-mkl ? Probably not. It probably depends on blas/lapack and just finds intel-mkl first since it is not forced. (#24327 would have made sure this doesn't happen)

2023-03-24 07:31 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
Yes, I came to the same conclusion.
suitesparse usesthe LAPACK_LIBRARIES and BLAS_LIBRARIES variables, so I assume the bad dependency is in one of those ports.

2023-03-24 08:41 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
... actually suitesparse doesn't directly depend on blas.

2023-03-24 11:57 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
Another data point: The following the error for test port cmake-user only happens for one out of four configurations: debug with CMake 3.25:
~~~
-- Running tests with CMake 3.25.1 for 'debug'
...
--   find_package(LAPACK)
CMake Error at scripts/test_ports/cmake-user/portfile.cmake:191 (message):
##[error]CMake 3.25.1: configuration with
  `find_package(LAPACK)` failed.

    See logs for more information:
      /mnt/vcpkg-ci/buildtrees/cmake-user/x64-linux-3.25.1-find-package-LAPACK-debug-out.log
      /mnt/vcpkg-ci/buildtrees/cmake-user/x64-linux-3.25.1-find-package-LAPACK-debug-err.log

Call Stack (most recent call first):
  scripts/test_ports/cmake-user/portfile.cmake:218 (test_cmake_project)
  scripts/ports.cmake:147 (include)
~~~
This test runs with `CMAKE_FIND_DEBUG_MODE` enabled.
stdout:
~~~
...
-- Using VCPKG FindLAPACK from package 'lapack-reference'
-- Found BLAS: /mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_intel_lp64.a;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_intel_thread.a;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_core.a;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl  
-- A library with LAPACK API found.
-- find_package(LAPACK) check: success
-- LAPACK_LIBRARIES: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/liblapack.a;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libgfortran.so.5;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_intel_lp64.a;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_intel_thread.a;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_core.a;/mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libiomp5.so;-lpthread;-lm;-ldl
-- Configuring incomplete, errors occurred!
~~~
stderr:
~~~
...
CMake Error at CMakeLists.txt:81 (message):
  Release lib for 'Debug' build:
  /mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_intel_lp64.a


CMake Error at CMakeLists.txt:81 (message):
  Release lib for 'Debug' build:
  /mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_intel_thread.a


CMake Error at CMakeLists.txt:81 (message):
  Release lib for 'Debug' build:
  /mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libmkl_core.a


CMake Error at CMakeLists.txt:81 (message):
  Release lib for 'Debug' build:
  /mnt/vcpkg-ci/installed/x64-linux/lib/intel64/libiomp5.so
~~~
It is probably okay for port intel-mkl to not have debug libaries, but obiously intel-mkl is used by lapack.

2023-03-25 09:05 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
While building lapack-reference:
~~~
-- Found BLAS: /home/kpa/Projekte/vcpkg/vcpkg/installed/x64-linux/lib/intel64/libmkl_gf_lp64.a;/home/kpa/Projekte/vcpkg/vcpkg/installed/x64-linux/lib/intel64/libmkl_gnu_thread.a;/home/kpa/Projekte/vcpkg/vcpkg/installed/x64-linux/lib/intel64/libmkl_core.a;/usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so;-lpthread;-lm;-ldl  
~~~

2023-03-25 09:12 UTC, dg0yt commented on ports/intel-mkl/portfile.cmake
> +elseif(VCPKG_TARGET_IS_LINUX)
... and same message while configuring blas which declares to pull in openblas.
IIUC selecting mkl's BLAS is to be made by an overlay port for blas, so we need to make port blas prevent finding mkl.

2023-04-09 16:46 UTC, hmenke commented
Great work, thanks! Would it be possible to expose other MKL configurations? Currently the only configurations available are`mkl-dynamic-ilp64-iomp` and `mkl-static-ilp64-seq` but the latter requires `VCPKG_CRT_LINKAGE="static"`, i.e. absolutely *everything has to be linked statically.

There is a bunch of other configurations for MKL, all listed on the pkg-config page: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-math-kernel-library-intel-mkl-and-pkg-config-tool.html

It would be particularly useful to also have access to the lp64 configurations, because a lot of linear algebra libraries that support offloading to MKL require it.

2023-04-09 20:43 UTC, Neumann-A commented
> Would it be possible to expose other MKL configurations? 

No not without alternatives being implemented into vcpkg. For vcpkg it makes only sense to have a single configuration since you cannot link multiple into one target. You can use an overlay and change the corresponding setup (e.g. https://github.com/microsoft/vcpkg/blob/217194cea7e3491c14779c763beec50b6a4575d6/ports/intel-mkl/portfile.cmake#L66) to get a different configuration however. 

> It would be particularly useful to also have access to the lp64 configurations, because a lot of linear algebra libraries that support offloading to MKL require it.

Normally those libraries provide a switch for ilp or lp interfaces.

2023-04-13 07:33 UTC, mgexo commented
Please see this issue https://github.com/oneapi-src/oneMKL/issues/302 

CMake MKLConfig.cmake file used by vcpkg has a missing slash in GLOB MKL_DLL_FILE that lets dll finding fail 

MKLConfig.cmake has an issue here: that lets the globbing for the dlls fail

file(GLOB MKL_DLL_FILE "${MKL_ROOT}/bin${MKL_DLL_GLOB}" "${MKL_ROOT}/../bin${MKL_DLL_GLOB}" "${MKL_ROOT}/../binmkl/${MKL_DLL_GLOB}") if(NOT ${lib} STREQUAL ${MKL_IFACE_LIB} AND NOT ${lib} STREQUAL ${MKL_BLAS95} AND NOT ${lib} STREQUAL ${MKL_LAPACK95})  # Windows IFACE libs are static only list(LENGTH MKL_DLL_FILE MKL_DLL_FILE_LEN)

You can already see that behind /binmkl/ is a slash but the first to lines do NOT have a slash i.e. if the .dlls are in the bin folder they are not found.

The fix is to add slashes after the bin

file(GLOB MKL_DLL_FILE "${MKL_ROOT}/bin/${MKL_DLL_GLOB}" "${MKL_ROOT}/../bin/${MKL_DLL_GLOB}" "${MKL_ROOT}/../binmkl/${MKL_DLL_GLOB}") if(NOT ${lib} STREQUAL ${MKL_IFACE_LIB} AND NOT ${lib} STREQUAL ${MKL_BLAS95} AND NOT ${lib} STREQUAL ${MKL_LAPACK95})  # Windows IFACE libs are static only list(LENGTH MKL_DLL_FILE MKL_DLL_FILE_LEN)

I suppose that all GLOBs should be checked and fixed like that and then pushe to vcpkg.

2023-04-13 10:51 UTC, dg0yt commented
This spot looses a `/`:
https://github.com/microsoft/vcpkg/blob/4f9d25a7f299db656c376af402637819ee2caba0/ports/intel-mkl/portfile.cmake#L259