[nanobench] Bump to 4.3.10
microsoft/vcpkg pull request #29468
Opened 2023-02-06 12:36 UTC by xiaozhuai

1. Bump to 4.3.10
2. Remove dependencies `fmt`, not needed at all.
3. Modernization

2023-02-07 09:25 UTC, LilyWangLL requested changes

2023-02-07 09:29 UTC, xiaozhuai commented on ports/nanobench/portfile.cmake
Done

2023-02-07 09:36 UTC, LilyWangLL approved these changes

2023-02-07 23:24 UTC, merged

2023-02-09 14:51 UTC, RT222 commented
I had undefined symbols error after I upgraded to this PR. For people having the same issue, in order to fix it you need to define the ANKERL_NANOBENCH_IMPLEMENT macro before including nanobench.h.

Also, I disagree with the changes made in this PR. The nanobench header is split in two parts : the declaration and the implementation. The later is disabled by default, and must be enabled with the ANKERL_NANOBENCH_IMPLEMENT macro if one want to use the library as single header.

I can also be built as a library (with the ANKERL_NANOBENCH_IMPLEMENT enabled), and the nanobench header can then be included without the macro to bring only the declaration part. This is the default behavior, and this is better in my opinion, because you don't need to define the macro every time you want to include the header, and more importantly because it improves the compilation speed.

2023-02-09 14:54 UTC, xiaozhuai commented
> I had undefined symbols error after I upgraded to this PR. For people having the same issue, in order to fix it you need to define the ANKERL_NANOBENCH_IMPLEMENT macro before including nanobench.h.
> 
> Also, I disagree with the changes made in this PR. The nanobench header is split in two parts : the declaration and the implementation. The later is disabled by default, and must be enabled with the ANKERL_NANOBENCH_IMPLEMENT macro if one want to use the library as single header.
> 
> I can also be built as a library (with the ANKERL_NANOBENCH_IMPLEMENT enabled), and the nanobench header can then be included without the macro to bring only the declaration part. This is the default behavior, and this is better in my opinion, because you don't need to define the macro every time you want to include the header, and more importantly because it improves the compilation speed.

Hi, @RT222 , thanks for you feedback, I'll submit a PR to revert to the default behavior.

2023-02-09 15:00 UTC, RT222 commented
Thanks for this and for the update to the latest version. :)

2023-02-09 15:18 UTC, xiaozhuai commented
> Thanks for this and for the update to the latest version. :)

How about this?
```cmake
find_package(nanobench CONFIG REQUIRED)

# will link to nanobench library
target_link_libraries(main PRIVATE nanobench::nanobench)

# this require "#define ANKERL_NANOBENCH_IMPLEMENT" before #include <nanobench.h>
target_link_libraries(main PRIVATE unofficial::nanobench::nanobench_headeronly)
```

2023-02-09 15:55 UTC, RT222 commented
If I got it right, you would still have to build and provide the library file to allow the user to choose? If this is the case, I fail to see the benefit of using the header only version. Why do you need to build this library as header only? Are you only trying to simplify the port?

2023-02-09 17:50 UTC, xiaozhuai commented
> If I got it right, you would still have to build and provide the library file to allow the user to choose? If this is the case, I fail to see the benefit of using the header only version. Why do you need to build this library as header only? Are you only trying to simplify the port?

No, I will update this port, it will provide two verison. If you link to `nanobench::nanobench` (the default), it do not need `#define ANKERL_NANOBENCH_IMPLEMENT`
Otherwise if you link to `unofficial::nanobench::nanobench_headeronly`, it need to `#define ANKERL_NANOBENCH_IMPLEMENT` before including.

Two choice.