Libmupdf cmake upgrade
microsoft/vcpkg pull request #29533
Opened 2023-02-08 15:56 UTC by as-shura

Tested and working on Windows 11

2023-02-08 20:54 UTC, dg0yt reviewed
CMake config which is not provided by upstream should be in the `unofficial` namespace. 
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#add-cmake-exports-in-an-unofficial--namespace

2023-02-08 20:54 UTC, dg0yt commented on ports/libmupdf/libmupdfConfig.cmake.in
> +find_library(JBIG2DEC_LIB NAMES jbig2decd jbig2dec)
You probably want to use `find_dependency` instead of `find_package`.
And don't think you need any `find_library` or `find_path`.

2023-02-08 22:35 UTC, as-shura commented
> CMake config which is not provided by upstream should be in the `unofficial` namespace. https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#add-cmake-exports-in-an-unofficial--namespace

I changed the namespace

2023-02-09 06:35 UTC, JonLiu1993 requested changes

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/CMakeLists.txt
> +set(TARGETS_EXPORT_NAME "${PROJECT_NAME}Targets")
```suggestion
set(TARGETS_EXPORT_NAME "unofficial-${PROJECT_NAME}Targets")
```

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/CMakeLists.txt
> +set(TARGETS_EXPORT_NAME "${PROJECT_NAME}Targets")
@as-shura, Thanks for your PR, If there is no export in the cmake provided by the upstream, then if we add export, we must add unofficial

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/libmupdfConfig.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/@TARGETS_EXPORT_NAME@.cmake")
Please add an extra blank line at the end of the file.

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/CMakeLists.txt
> +
Please add an extra blank line at the end of the file.

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/portfile.cmake
> +    #    use-if-instead-of-ifdef-in-writer.patch
If these patches are no longer used, please delete these lines instead of blocking them, and please delete the patch file.

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/portfile.cmake
> +
Just leave a blank line here.

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/vcpkg.json
>    "port-version": 1,
```suggestion
```

2023-02-09 06:35 UTC, JonLiu1993 commented on ports/libmupdf/vcpkg.json
>    "port-version": 1,
When we update port version, we should remove the "port-version".

2023-02-09 06:37 UTC, JonLiu1993 requested changes

2023-02-09 06:37 UTC, JonLiu1993 commented on ports/libmupdf/vcpkg.json
>    "homepage": "https://github.com/ArtifexSoftware/mupdf",
```suggestion
  "homepage": "https://github.com/ArtifexSoftware/mupdf",
  "license": "AGPL-3.0",
```

2023-02-09 08:53 UTC, as-shura commented on ports/libmupdf/portfile.cmake
> +    #    use-if-instead-of-ifdef-in-writer.patch
I really don't know if the patch are not used.

2023-02-10 02:00 UTC, JonLiu1993 requested changes

2023-02-10 02:00 UTC, JonLiu1993 commented on ports/libmupdf/portfile.cmake
> -        dont-generate-extract-3rd-party-things.patch
I investigated that patch `dont-generate-extract-3rd-party-things.patch` is still needed and should be kept, `use-if-instead-of-ifdef-in-writer.patch` has been applied to the latest version so it can be removed.

2023-02-10 11:33 UTC, as-shura commented
I don't understand what is the problem and how to fix it,

2023-02-10 20:34 UTC, as-shura commented on ports/libmupdf/portfile.cmake
> -        dont-generate-extract-3rd-party-things.patch
I put it back together.

2023-02-11 17:30 UTC, as-shura commented
This error doesn't make sense it says https://dev.azure.com/vcpkg/public/_build/results?buildId=85145&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005&t=3980505e-92f5-53ef-75a8-4f2e70b97516&l=2158

But the file is there : https://github.com/as-shura/vcpkg/commit/829187d52889252219b702f41fb8fbcaa49936b1

2023-02-11 20:49 UTC, dg0yt commented on versions/l-/libmupdf.json
> +
Don't edit this by hand. You are breaking the formatting, and here you picked the wrong port version.

Start using `vcpkg x-add-version <Port>` to register a new version, and `vcpkg x-add-version --overwrite-version <Port>` when you update a PR after the initial registration of the new version.

2023-02-12 13:21 UTC, as-shura commented on versions/l-/libmupdf.json
> +
Ok I hope this works at the end. Did what you asked me to do. And sorry for the manual edit.

2023-02-12 16:02 UTC, as-shura commented
Please accept and close :D

2023-02-12 16:29 UTC, dg0yt reviewed
IMO it is not yet ready for merge.  Some comments are with regard to your modifications. But the port hasn't been updated in a while, so I made a few additional remarks.

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +  #  include
What is the point of this change?

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +
We don't want this empty line.

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +project(libmupdf VERSION 1.21.1 LANGUAGES C) #1.21.1
I would not encode the version into CMakeLists.txt. We can avoid updating this script for new versions.

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +    VERSION ${PACKAGE_VERSION}
This is where we actually need the version - and don't have it yet. No problem:
`PACKAGE_VERSION` can be set from the portfile by passing `-DPACKAGE_VERSION=${VERSION}`.

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/libmupdfConfig.cmake.in
> +find_dependency(freetype)
Please add `NO_MODULE` (as in CMakeLists.txt).

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
>  find_library(JBIG2DEC_LIB NAMES jbig2decd jbig2dec)
This is already broken: It needs a `NAMES_PER_DIR` option.

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/libmupdfConfig.cmake.in
> +find_dependency(harfbuzz)
This is not what is used during the build. But actually it would be a real improvement to start using the harfbuzz cmake config. It would mean adding `CONFIG` here, and updating CMakelists.txt to use `find_package(harfbuzz CONFIG REQUIRED)` and to link to `harfbuzz::harfbuzz`.

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/libmupdfConfig.cmake.in
> +find_dependency(jbig2decd jbig2dec)
This isn't needed. (There is no such package. The build operates with library filepaths.)

2023-02-12 16:29 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +set(PROJECT_CONFIG "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake")
This will create `libmupdfConfig.cmake`, for `find_package(libmupdf)`.
But what is needed is `unofficial-libmupdfConfig.cmake`, for `find_package(unofficial-libmupdf)`.
This has impact on other spots dealing with the cmake config.

2023-02-12 16:29 UTC, dg0yt commented on versions/l-/libmupdf.json
> +    },
This version doesn't exist yet, but are left from work in progress. This is a situation to be cleaned up by direct manual editing ;-)

2023-02-12 17:55 UTC, as-shura commented on versions/l-/libmupdf.json
> +    },
Are you joking man?

2023-02-12 17:56 UTC, as-shura commented on ports/libmupdf/CMakeLists.txt
> +  #  include
It was giving an error saying that it was already included so I had to use the old way.

2023-02-12 17:59 UTC, as-shura commented on ports/libmupdf/CMakeLists.txt
> +project(libmupdf VERSION 1.21.1 LANGUAGES C) #1.21.1
Well the config needs it and it is CMake best practice the version file generated requires this. Telling the version explicitly is a good thing. You can learn about it here https://cliutils.gitlab.io/modern-cmake/chapters/install/installing.html

2023-02-12 17:59 UTC, as-shura commented on ports/libmupdf/CMakeLists.txt
> +
Are you being religious?

2023-02-12 18:03 UTC, as-shura commented on ports/libmupdf/CMakeLists.txt
> +project(libmupdf VERSION 1.21.1 LANGUAGES C) #1.21.1
Keep in mind that this CMake files is independent from vcpkg that's why it should work with and without vcpkg.

2023-02-12 18:07 UTC, dg0yt commented on versions/l-/libmupdf.json
> +    },
I'm trying to help you with your PR.
Using `vcpkg x-add-version` added the correct version port-version 0 and rectified the formatting. It doesn't remove the port-version 1 record which was already part of this PR but shouldn't be here.

2023-02-12 18:15 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +project(libmupdf VERSION 1.21.1 LANGUAGES C) #1.21.1
> Keep in mind that this CMake files is independent from vcpkg that's why it should work with and without vcpkg.

This file is part of the vcpkg repo and so it is not independent. AFAICT it is an exception to have it in the vcpkg repo, and it shouldn't require more maintenance then necessary. Not every general recommendation applies to this repo's specific needs. (Another example: Generally it is not recommended to glob for sources, but for vcpkg it is okay.)

The suggestion to not hardcode the version number was connected to the propsal to use the information from the portfile. The config export can make good use of the version, but it doesn't need to come from `project` command.

2023-02-12 18:19 UTC, dg0yt commented on ports/libmupdf/CMakeLists.txt
> +  #  include
Still unclear.

2023-02-12 18:58 UTC, as-shura commented on ports/libmupdf/CMakeLists.txt
> +  #  include
Target "libmupdf" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "C:/vcpkg/buildtrees/libmupdf/src/1cce2ec1bd-5fb725a33d.clean/include"

  which is prefixed in the source directory.

2023-02-12 19:09 UTC, as-shura commented on ports/libmupdf/CMakeLists.txt
> +  #  include
Ok I got it I fixed this.

2023-02-12 20:37 UTC, as-shura commented on versions/l-/libmupdf.json
> +    },
I reset the version to 0 with **vcpkg x-add-version libmupdf --overwrite-version**

2023-02-12 22:18 UTC, as-shura commented on versions/l-/libmupdf.json
> +    },
I did it.

2023-02-13 08:59 UTC, JonLiu1993 commented on versions/l-/libmupdf.json
> +    },
@as-shura, please remove this code and run command `./vcpkg x-add-version libmupdf` and commit again.

2023-02-13 09:08 UTC, JonLiu1993 commented on ports/libmupdf/portfile.cmake
> +set(PACKAGE_VERSION "1.21.1")
```suggestion
```

2023-02-13 09:08 UTC, JonLiu1993 commented on ports/libmupdf/portfile.cmake
> +    REF f39eee48564274635e231e2ab652221cce2ec1bd # 1.21.1
```suggestion
    REF "${VERSION}"
```

2023-02-13 09:09 UTC, JonLiu1993 commented on ports/libmupdf/portfile.cmake
> +        -DPACKAGE_VERSION=${PACKAGE_VERSION}
```suggestion
        -DPACKAGE_VERSION=${VERSION}
```

2023-02-13 11:48 UTC, as-shura commented
All done please merge!

2023-02-13 21:55 UTC, closed without merging

2023-02-14 02:03 UTC, JonLiu1993 commented
@as-shura, Why close this PR?