Litehtml 0.6
microsoft/vcpkg pull request #29673
Opened 2023-02-15 13:32 UTC by rioki

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See docs/examples/adding-an-explicit-usage.md for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2023-02-16 00:05 UTC, Neumann-A commented
Note: litehtml is vendored by qttools currently. I don't know if it is visible from the outside or just a part of qtassistent.

2023-02-16 07:07 UTC, rioki commented
> Note: litehtml is vendored by qttools currently. I don't know if it is visible from the outside or just a part of qtassistent.

As far as I can see the QT version runs as qlitehtml and has some changes to the code. It's API and ABI incompatible as it uses QT specific types and should be considered a sperate fork.

If I see it correctly qtassistent consumes qlitehtml as a [static library and never installs anything](https://github.com/qt/qttools/blob/dev/src/assistant/CMakeLists.txt#L25).

2023-02-16 08:20 UTC, dg0yt commented
qlitehtml is a wrapper and needs litehtml. It will use an installed version if it is found:
https://code.qt.io/cgit/playground/qlitehtml.git/tree/src/CMakeLists.txt#n18

So AFAICT qttools must use the vcpkg version of litehtml if we don't want to have two providers of the same symbols.
Another questions is if we also want/need a qlitehtml port...

2023-02-16 08:25 UTC, Neumann-A commented
> Another questions is if we also want/need a qlitehtml port...

I don't think that is currently needed.

2023-02-17 01:54 UTC, jimwang118 commented
All test passed with following triplets:
x86-windows
x64-windows
x64-windows-static

2023-02-17 02:42 UTC, JonLiu1993 requested changes

2023-02-17 02:42 UTC, JonLiu1993 commented on ports/litehtml/portfile.cmake
> +    REF v0.6
```suggestion
    REF "v${VERSION}"
```

2023-02-17 02:42 UTC, JonLiu1993 commented on ports/litehtml/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2023-02-17 02:45 UTC, JonLiu1993 submitted a review, later dismissed

2023-02-17 04:59 UTC, dg0yt commented
IIUC litehtml still needs to be devendored from qttools.

2023-02-18 17:14 UTC, rioki commented
I will see if I can devendor litehtml this weekend.

2023-02-19 11:14 UTC, rioki commented
I fixed the CMakeLists.txt in qlitehtml/src so that is used the vcpkg litehtml. git still pulls the submodule, but I have no idea how to fix that, since I can patch the .gitmodules but that happens only after the submodule was pulled.

2023-02-19 14:39 UTC, rioki commented
Not sure why this fails on the CI but not on my machine. Will make gumbo static liked and patch the CMake config, as gumbo-parser is vendored into litehtml and the official repo is marked as defunct.

2023-02-19 14:59 UTC, rioki commented
Looking into why it fails on the CI (works on my machine™)

2023-02-19 18:46 UTC, rioki commented
I fixed litehtml exposing the vendored [gumbo](https://github.com/google/gumbo-parser) for CMake to handle it's dependencies cleanly. The project is defunct, thus I don't think making a unique port is needed.

2023-02-20 02:28 UTC, jimwang118 approved these changes

2023-02-21 01:47 UTC, jimwang118 approved these changes

2023-02-21 15:58 UTC, merged

2023-02-23 06:41 UTC, dg0yt commented
> I fixed litehtml exposing the vendored [gumbo](https://github.com/google/gumbo-parser) for CMake to handle it's dependencies cleanly. The project is defunct, thus I don't think making a unique port is needed.

There is a gumbo port, and we have a file conflict in CI now.
https://dev.azure.com/vcpkg/public/_build/results?buildId=85761&view=logs&j=84da4f4a-968a-5b5c-16e9-f444c845396d&t=8cdf6620-a129-5b70-3f3e-822630a64446

2023-02-23 07:07 UTC, rioki commented
Sorry for missing that. I will look into fixing this.