[lastools] Update to 2.0.2, fix include directories
microsoft/vcpkg pull request #29770
Opened 2023-02-21 12:56 UTC by Obbart

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2023-02-21 12:58 UTC, Obbart commented
@microsoft-github-policy-service agree

2023-02-21 15:40 UTC, Obbart commented
> @Obbart please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2023-02-21 18:11 UTC, instafirm2023 approved these changes, later dismissed

2023-02-22 05:34 UTC, Cheney-W commented
x64-osx failure:
```
/Users/vagrant/Data/buildtrees/lastools/src/v2.0.2-cfbfed1eda.clean/src/lasindex.cpp:146:25: error: character too large for enclosing character literal type
      if (argv[i][0] == '�') argv[i][0] = '-';
```
log: https://dev.azure.com/vcpkg/public/_build/results?buildId=85696&view=artifacts&pathAsName=false&type=publishedArtifacts

2023-02-22 05:38 UTC, Cheney-W commented on ports/lastools/portfile.cmake
> +    REF v2.0.2
```suggestion
    REF "v${VERSION}"
```

2023-02-22 05:42 UTC, Cheney-W commented
Please remove the records of the lastools from https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt because `"supports": "!uwp"` has been added into the vcpkg.json file. 
```
lastools:arm-uwp=fail
lastools:x64-uwp=fail
```

2023-02-22 08:31 UTC, Obbart commented on ports/lastools/portfile.cmake
> +    REF v2.0.2
To solve this: https://github.com/microsoft/vcpkg/pull/29770#issuecomment-1439465504 I had to update the REF to latest master commit

2023-02-22 08:33 UTC, Obbart commented
> Please remove the records of the lastools from https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt because `"supports": "!uwp"` has been added into the vcpkg.json file.
> 
> ```
> lastools:arm-uwp=fail
> lastools:x64-uwp=fail
> ```

References removed

2023-02-22 10:02 UTC, Cheney-W requested changes

2023-02-22 10:02 UTC, Cheney-W commented on ports/lastools/vcpkg.json
>    "port-version": 1,
```suggestion
```

2023-02-23 01:55 UTC, Cheney-W requested changes

2023-02-23 01:55 UTC, Cheney-W commented on versions/l-/lastools.json
> +    },
```suggestion
```

2023-02-23 05:13 UTC, dg0yt requested changes

2023-02-23 05:13 UTC, dg0yt commented on ports/lastools/vcpkg.json
> +  "version": "2.0.2",
This claims a wrong version for the commit you are using.
I think you should use `2.0.2+20230206`.
https://github.com/LAStools/LAStools/compare/v2.0.2...2bbbfa9

2023-02-23 07:39 UTC, dg0yt approved these changes

2023-02-23 09:48 UTC, Cheney-W approved these changes

2023-02-23 19:19 UTC, merged