miniply - add new port
microsoft/vcpkg pull request #29802
Opened 2023-02-23 07:54 UTC by fran6co

2023-02-23 08:57 UTC, Adela0814 requested changes

2023-02-23 08:57 UTC, Adela0814 commented on ports/miniply/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2023-02-23 11:33 UTC, fran6co commented on ports/miniply/CMakeLists.txt
> +install(TARGETS miniply EXPORT miniply-config
Done

2023-02-23 11:33 UTC, fran6co commented on ports/miniply/vcpkg.json
> +  "homepage": "https://github.com/vilya/miniply",
Done

2023-02-24 02:36 UTC, Adela0814 submitted a review, later dismissed

2023-02-24 04:10 UTC, dg0yt commented on ports/miniply/fix-cmake.patch
> ++set_target_properties(miniply PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
Is this okay to merge?
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-add-cmake_windows_export_all_symbols

2023-02-24 20:37 UTC, JavierMatosD submitted a review, later dismissed

2023-02-24 20:37 UTC, JavierMatosD commented on ports/miniply/fix-cmake.patch
> ++set_target_properties(miniply PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
@fran6co Please follow the instructions provided in the link :)

2023-03-08 02:55 UTC, Adela0814 requested changes

2023-03-08 02:55 UTC, Adela0814 commented on ports/miniply/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH share/unofficial-miniply TARGET_PATH share/unofficial-miniply)
Please use `'vcpkg_cmake_config_fixup'`.

2023-03-09 10:14 UTC, Adela0814 approved these changes

2023-03-09 23:37 UTC, fran6co commented
I have removed it and it's static linking only now

2023-04-03 09:38 UTC, fran6co commented
ping @dan-shaw

2023-04-14 02:22 UTC, Adela0814 requested changes

2023-04-14 02:22 UTC, Adela0814 commented on ports/miniply/fix-cmake.patch
> ++set_target_properties(miniply PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
Please remove `WINDOWS_EXPORT_ALL_SYMBOLS`.

2023-04-21 02:24 UTC, Adela0814 approved these changes

2023-04-21 21:52 UTC, merged

2023-04-21 21:52 UTC, BillyONeal commented
Thanks for the new port!

2023-04-22 08:01 UTC, dg0yt commented on ports/miniply/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH share/unofficial-miniply)
Another broken CMake config!