[scope-guard] Add new port
microsoft/vcpkg pull request #29821
Opened 2023-02-24 00:06 UTC by oold

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-02-24 02:51 UTC, FrankXie05 requested changes

2023-02-24 02:51 UTC, FrankXie05 commented on ports/scope-guard/portfile.cmake
> +vcpkg_from_github(
```suggestion
# Header-only library
vcpkg_from_github(

```
We can note this. :)

2023-02-24 02:51 UTC, FrankXie05 commented on ports/scope-guard/portfile.cmake
> +    REF v1.0.0
```suggestion
    REF "v${VERSION}"

```

2023-02-24 02:51 UTC, FrankXie05 commented on ports/scope-guard/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

```
We can use the new function.

2023-02-24 02:51 UTC, FrankXie05 commented on ports/scope-guard/vcpkg.json
> +  "version-semver": "1.0.0",
Is semer the semantic rules required upstream? If not, we should change to the `"version": "1.0.0",`

2023-02-24 21:33 UTC, oold commented on ports/scope-guard/vcpkg.json
> +  "version-semver": "1.0.0",
Upstream uses semver.

2023-02-28 02:00 UTC, FrankXie05 approved these changes

2023-02-28 02:01 UTC, FrankXie05 commented
/azp run

2023-02-28 18:16 UTC, merged