[luminoengine] Fix cann't find luminoengine.lib
microsoft/vcpkg pull request #29879
Opened 2023-02-27 06:57 UTC by jimwang118

Add a judgment on whether `luminoengine.lib `is linked in `luminoConfig.cmake.`
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-02-27 07:24 UTC, jimwang118 commented
/azp run

2023-02-27 09:45 UTC, LilyWangLL requested changes

2023-02-27 09:45 UTC, LilyWangLL commented on ports/luminoengine/portfile.cmake
> +	PATCHES
```suggestion
    PATCHES
```

2023-02-27 09:45 UTC, LilyWangLL commented on ports/luminoengine/fix-pkgconfig.patch
> ++add_library(lumino::Lumino INTERFACE IMPORTED)
```suggestion
```

2023-02-27 09:46 UTC, LilyWangLL requested changes, later dismissed

2023-02-27 09:46 UTC, LilyWangLL commented on ports/luminoengine/portfile.cmake
>      REF v0.10.1
```suggestion
    REF "v${VERSION}"
```

2023-02-27 10:02 UTC, Neumann-A commented on ports/luminoengine/portfile.cmake
> +        fix-pkgconfig.patch
that should probably be renamed to `fix-cmake-config.patch` ?

2023-02-27 10:03 UTC, Neumann-A commented on ports/luminoengine/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT")
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT}")
```

2023-02-27 10:03 UTC, Neumann-A commented on ports/luminoengine/portfile.cmake
> +    SOURCE_PATH "${SOURCE_PATH}"
why was this touched ?

2023-02-27 10:04 UTC, Neumann-A commented on ports/luminoengine/fix-pkgconfig.patch
> ++if(LUMINO_BUILD_ENGINE)
Maybe it should be `@LUMINO_BUILD_ENGINE@` ?

2023-02-27 10:09 UTC, jimwang118 commented on ports/luminoengine/fix-pkgconfig.patch
> ++if(LUMINO_BUILD_ENGINE)
Yes, here it is mainly judged whether the feature is installed or not.

2023-02-27 18:03 UTC, BillyONeal approved these changes

2023-02-28 01:58 UTC, JonLiu1993 approved these changes

2023-02-28 02:15 UTC, merged