Libopnmidi
microsoft/vcpkg pull request #30015
Opened 2023-03-04 09:39 UTC by dbarkar

All provided patches are in upstream:
cmake-build-shared-libs-support.patch - https://github.com/Wohlstand/libOPNMIDI/commit/76e461033e83f9b2a77285146d249bd682bf5bb4
cmake-package-export.patch -https://github.com/Wohlstand/libOPNMIDI/commit/a48f3f7d702faab815d43a29959ecd1f959a6e07
disable-wopn2hpp.patch - https://github.com/Wohlstand/libOPNMIDI/commit/0a91e141218dd5c330bd6ccb1910bad25dba56f9
fix-build-without-sequencer.patch -https://github.com/Wohlstand/libOPNMIDI/commit/2c348b348fadce0a84d743c1c09b2f1e16eb0436
fix-pmdwin-emulator-include.patch - https://github.com/Wohlstand/libOPNMIDI/commit/81178c3ff0f7f1073f0758e074ea4ab992ab510d

All features are additive.
**There are two experimental emulators (pmdwin-emulator and gx-emulator), should they be included in default features? What's the best practice here?**

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2023-03-06 02:34 UTC, jimwang118 commented
> All provided patches are in upstream: cmake-build-shared-libs-support.patch - [Wohlstand/libOPNMIDI@76e4610](https://github.com/Wohlstand/libOPNMIDI/commit/76e461033e83f9b2a77285146d249bd682bf5bb4) cmake-package-export.patch -[Wohlstand/libOPNMIDI@a48f3f7](https://github.com/Wohlstand/libOPNMIDI/commit/a48f3f7d702faab815d43a29959ecd1f959a6e07) disable-wopn2hpp.patch - [Wohlstand/libOPNMIDI@0a91e14](https://github.com/Wohlstand/libOPNMIDI/commit/0a91e141218dd5c330bd6ccb1910bad25dba56f9) fix-build-without-sequencer.patch -[Wohlstand/libOPNMIDI@2c348b3](https://github.com/Wohlstand/libOPNMIDI/commit/2c348b348fadce0a84d743c1c09b2f1e16eb0436) fix-pmdwin-emulator-include.patch - [Wohlstand/libOPNMIDI@81178c3](https://github.com/Wohlstand/libOPNMIDI/commit/81178c3ff0f7f1073f0758e074ea4ab992ab510d)
> 
> All features are additive. **There are two experimental emulators (pmdwin-emulator and gx-emulator), should they be included in default features? What's the best practice here?**
> 
> * [x]  Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
> * [x]  The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
> * [x]  Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
> * [x]  The versioning scheme in `vcpkg.json` matches what upstream says.
> * [x]  The license declaration in `vcpkg.json` matches what upstream says.
> * [x]  The installed as the "copyright" file matches what upstream says.
> * [x]  The source code of the component installed comes from an authoritative source.
> * [x]  The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
> * [x]  The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
> * [x]  Only one version is in the new port's versions file.
> * [x]  Only one version is added to each modified port's versions file.

2023-03-06 02:45 UTC, jimwang118 requested changes

2023-03-06 02:45 UTC, jimwang118 commented on ports/libopnmidi/portfile.cmake
> +    REF v${VERSION}
```suggestion
    REF "v${VERSION}"

```

2023-03-06 02:45 UTC, jimwang118 commented on ports/libopnmidi/vcpkg.json
> +  "homepage": "https://github.com/Wohlstand/libOPNMIDI",
```suggestion
  "homepage": "https://github.com/Wohlstand/libOPNMIDI",
  "license": "LGPL-3.0",
```

2023-03-06 06:44 UTC, jimwang118 approved these changes

2023-03-06 06:55 UTC, jimwang118 commented
All feature passed with following triplets:
x86-windows
x64-windows
x64-windows-static

The usage has been tested successfully locally. 
```
find_package()
target_link_library()
```

2023-03-07 02:30 UTC, JonLiu1993 approved these changes

2023-03-08 22:16 UTC, merged