Bump yomm2 to 1.3.1
microsoft/vcpkg pull request #30028
Opened 2023-03-05 18:23 UTC by stellarpower

Existing version 1.1.2 [had compile error](https://github.com/jll63/yomm2/issues/26) so I have nbumped to the latest upstream tag (1.3.1)

I don't have the availability to maintain this ATM, it's not properly tested, not been built cross platforms, etc. etc. I have just changed the patches from the previous version that wouldn't apply and pushed my work up so that someone else can benefit.

Cheers

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
  * I think so.
- [x] SHA512s are updated for each updated download
- [?] The "supports" clause reflects platforms that may be fixed by this new version
- [?] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
  * This removed my "port-version" from the manifest.
- [x] Only one version is added to each modified port's versions file.

2023-03-05 18:28 UTC, stellarpower commented
@microsoft-github-policy-service agree


On Sun, 5 Mar 2023 at 18:24, microsoft-github-policy-service[bot] <
***@***.***> wrote:

> @stellarpower <https://github.com/stellarpower> please read the following
> Contributor License Agreement(CLA). If you agree with the CLA, please reply
> with the following information.
>
> @microsoft-github-policy-service agree [company="{your company}"]
>
>
> Options:
>
>    - (default - no company specified) I have sole ownership of
>    intellectual property rights to my Submissions and I am not making
>    Submissions in the course of work for my employer.
>
> @microsoft-github-policy-service agree
>
>
>
>    - (when company given) I am making Submissions in the course of work
>    for my employer (or my employer has intellectual property rights in my
>    Submissions by contract or applicable law). I have permission from my
>    employer to make Submissions and enter into this Agreement on behalf of my
>    employer. By signing below, the defined term “You” includes me and my
>    employer.
>
> @microsoft-github-policy-service agree company="Microsoft"
>
>
> Contributor License Agreement Contribution License Agreement
>
> This Contribution License Agreement (*“Agreement”*) is agreed to by the
> party signing below (*“You”*),
> and conveys certain license rights to Microsoft Corporation and its
> affiliates (“Microsoft”) for Your
> contributions to Microsoft open source projects. This Agreement is
> effective as of the latest signature
> date below.
>
>    1. *Definitions*.
>    *“Code”* means the computer software code, whether in human-readable
>    or machine-executable form,
>    that is delivered by You to Microsoft under this Agreement.
>    *“Project”* means any of the projects owned or managed by Microsoft
>    and offered under a license
>    approved by the Open Source Initiative (www.opensource.org).
>    *“Submit”* is the act of uploading, submitting, transmitting, or
>    distributing code or other content to any
>    Project, including but not limited to communication on electronic
>    mailing lists, source code control
>    systems, and issue tracking systems that are managed by, or on behalf
>    of, the Project for the purpose of
>    discussing and improving that Project, but excluding communication
>    that is conspicuously marked or
>    otherwise designated in writing by You as “Not a Submission.”
>    *“Submission”* means the Code and any other copyrightable material
>    Submitted by You, including any
>    associated comments and documentation.
>    2. *Your Submission*. You must agree to the terms of this Agreement
>    before making a Submission to any
>    Project. This Agreement covers any and all Submissions that You, now
>    or in the future (except as
>    described in Section 4 below), Submit to any Project.
>    3. *Originality of Work*. You represent that each of Your Submissions
>    is entirely Your original work.
>    Should You wish to Submit materials that are not Your original work,
>    You may Submit them separately
>    to the Project if You (a) retain all copyright and license information
>    that was in the materials as You
>    received them, (b) in the description accompanying Your Submission,
>    include the phrase “Submission
>    containing materials of a third party:” followed by the names of the
>    third party and any licenses or other
>    restrictions of which You are aware, and (c) follow any other
>    instructions in the Project’s written
>    guidelines concerning Submissions.
>    4. *Your Employer*. References to “employer” in this Agreement include
>    Your employer or anyone else
>    for whom You are acting in making Your Submission, e.g. as a
>    contractor, vendor, or agent. If Your
>    Submission is made in the course of Your work for an employer or Your
>    employer has intellectual
>    property rights in Your Submission by contract or applicable law, You
>    must secure permission from Your
>    employer to make the Submission before signing this Agreement. In that
>    case, the term “You” in this
>    Agreement will refer to You and the employer collectively. If You
>    change employers in the future and
>    desire to Submit additional Submissions for the new employer, then You
>    agree to sign a new Agreement
>    and secure permission from the new employer before Submitting those
>    Submissions.
>    5. *Licenses*.
>
>
>    - *Copyright License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license in the
>    Submission to reproduce, prepare derivative works of, publicly
>    display, publicly perform, and distribute
>    the Submission and such derivative works, and to sublicense any or all
>    of the foregoing rights to third
>    parties.
>    - *Patent License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license under
>    Your patent claims that are necessarily infringed by the Submission or
>    the combination of the
>    Submission with the Project to which it was Submitted to make, have
>    made, use, offer to sell, sell and
>    import or otherwise dispose of the Submission alone or with the
>    Project.
>    - *Other Rights Reserved*. Each party reserves all rights not
>    expressly granted in this Agreement.
>    No additional licenses or rights whatsoever (including, without
>    limitation, any implied licenses) are
>    granted by implication, exhaustion, estoppel or otherwise.
>
>
>    1. *Representations and Warranties*. You represent that You are
>    legally entitled to grant the above
>    licenses. You represent that each of Your Submissions is entirely Your
>    original work (except as You may
>    have disclosed under Section 3). You represent that You have secured
>    permission from Your employer to
>    make the Submission in cases where Your Submission is made in the
>    course of Your work for Your
>    employer or Your employer has intellectual property rights in Your
>    Submission by contract or applicable
>    law. If You are signing this Agreement on behalf of Your employer, You
>    represent and warrant that You
>    have the necessary authority to bind the listed employer to the
>    obligations contained in this Agreement.
>    You are not expected to provide support for Your Submission, unless
>    You choose to do so. UNLESS
>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE
>    WARRANTIES
>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED
>    UNDER THIS AGREEMENT IS
>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO,
>    ANY WARRANTY OF
>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
>    2. *Notice to Microsoft*. You agree to notify Microsoft in writing of
>    any facts or circumstances of which
>    You later become aware that would make Your representations in this
>    Agreement inaccurate in any
>    respect.
>    3. *Information about Submissions*. You agree that contributions to
>    Projects and information about
>    contributions may be maintained indefinitely and disclosed publicly,
>    including Your name and other
>    information that You submit with Your Submission.
>    4. *Governing Law/Jurisdiction*. This Agreement is governed by the
>    laws of the State of Washington, and
>    the parties consent to exclusive jurisdiction and venue in the federal
>    courts sitting in King County,
>    Washington, unless no federal subject matter jurisdiction exists, in
>    which case the parties consent to
>    exclusive jurisdiction and venue in the Superior Court of King County,
>    Washington. The parties waive all
>    defenses of lack of personal jurisdiction and forum non-conveniens.
>    5. *Entire Agr [...]

2023-03-06 03:00 UTC, JonLiu1993 requested changes

2023-03-06 04:03 UTC, stellarpower commented
Thanks for the changes!

2023-03-28 02:18 UTC, JonLiu1993 commented
@stellarpower, please run command `./vcpkg x-add-version yomm2 --overwrite-version` and commit again.

2023-04-13 07:56 UTC, JonLiu1993 commented
Ping @stellarpower for response, could you consider the review suggestion above?

2023-04-13 22:18 UTC, stellarpower commented
Sorry, really just not having the time for development right now.

That is pushed to the branch so hopefully should be visible.

Think I should have resolved the conflicts, but IDK why it's then committed this back to my branch. The conflicts should be with the base I presume.

2023-04-14 04:55 UTC, BillyONeal submitted a review, later dismissed
This looks good to me.

@stellarpower can you un-draft it if you think it's OK to go, or are you waiting to do something?

@JonLiu1993 It looks like your comments have been fixed, does it look good to you now?

2023-04-14 05:54 UTC, JonLiu1993 requested changes

2023-04-14 05:54 UTC, JonLiu1993 commented on versions/y-/yomm2.json
> -      "port-version": 2
@stellarpower, Please restore the records here and add new records, so that we can go back to the historical version.

2023-04-14 05:56 UTC, JonLiu1993 commented on versions/y-/yomm2.json
> -      "port-version": 2
@BillyONeal, Yes the others seem to have been fixed but there is one place that needs to be modified.

2023-04-14 05:58 UTC, JonLiu1993 commented
@stellarpower, After completing the above modification, please click `ready for review` so that we can review megre as soon as possible, Thanks.

2023-04-15 02:00 UTC, BillyONeal commented on versions/y-/yomm2.json
> -      "port-version": 2
Ah, yes, old versions should never be removed from the version database. I'll push a fix.

2023-04-15 02:02 UTC, BillyONeal approved these changes

2023-04-15 02:02 UTC, BillyONeal commented
@stellarpower Since it sounds like you are OK with this outcome can you undraft the PR?

2023-04-17 01:42 UTC, JonLiu1993 approved these changes

2023-04-17 01:43 UTC, JonLiu1993 commented
@stellarpower, please click `ready for review` so that we can review megre as soon as possible, Thanks.

2023-04-19 19:09 UTC, merged

2023-04-19 19:09 UTC, BillyONeal commented
Thanks for the update!

2023-04-19 19:41 UTC, stellarpower commented
Thanks a lot for your help!!