[rocksdb] update to 7.10.2
microsoft/vcpkg pull request #30074
Opened 2023-03-07 14:46 UTC by kobykahane

Update the rocksdb port to the new upstream release, 7.10.2.

2023-03-09 08:04 UTC, JonLiu1993 requested changes

2023-03-10 12:59 UTC, kobykahane commented on ports/rocksdb/portfile.cmake
> +  REF 3258b5c3e2488464de0827343c8c27bc6499765e # v7.10.2
Fixed.

2023-03-13 02:36 UTC, JonLiu1993 approved these changes

2023-03-13 03:00 UTC, JonLiu1993 requested changes

2023-03-13 03:00 UTC, JonLiu1993 commented on ports/rocksdb/portfile.cmake
> +  SHA512 527f5f69305dc5bc766fa1f492ae4b4a7e487b5edee9249dc1b99ec738f955a25eccaeaaf21d86bd10a6d79cfdf6ef026add6d45b1d4647e0c31a18f189aa1e6
@kobykahane, Thanks for your PR, when I tested the feature locally, I found that the hash value was incorrect.

2023-03-20 06:34 UTC, JonLiu1993 approved these changes

2023-03-20 06:36 UTC, JonLiu1993 commented
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

2023-03-20 06:40 UTC, merged