[catch2] Update to 3.3.2
microsoft/vcpkg pull request #30073
Opened 2023-03-07 14:19 UTC by RT222

Update catch2 from 3.3.1 to 3.3.2 : https://github.com/catchorg/Catch2/releases/tag/v3.3.2

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-03-10 01:59 UTC, jimwang118 requested changes

2023-03-10 01:59 UTC, jimwang118 commented on ports/catch2/vcpkg.json
> +  "version-semver": "3.3.2",
```suggestion
  "version": "3.3.2",
```

2023-03-10 02:00 UTC, jimwang118 commented
The usage has been tested successfully locally. 
```
find_package()
target_link_library()
```

2023-03-13 02:47 UTC, jimwang118 approved these changes

2023-03-13 18:59 UTC, dan-shaw commented
@jimwang118 Why are we changing the versioning scheme?

2023-03-14 01:59 UTC, jimwang118 requested changes

2023-03-14 01:59 UTC, jimwang118 commented on ports/catch2/vcpkg.json
> +  "version": "3.3.2",
```suggestion
  "version-semver": "3.3.2",
```
I'm very sorry, I re-checked that the version control provided by the upstream code is version-semver, please restore the version control to version-semver, thank you.

2023-03-15 11:16 UTC, RT222 commented on ports/catch2/vcpkg.json
> +  "version": "3.3.2",
No worries. :wink:

2023-03-16 06:28 UTC, jimwang118 approved these changes

2023-03-17 00:57 UTC, merged