[Spout2] New Port
microsoft/vcpkg pull request #30119
Opened 2023-03-10 14:17 UTC by cnSchwarzer

Fixes #30117

2023-03-11 09:00 UTC, dg0yt commented on ports/spout2/usage
>      target_link_libraries(main PRIVATE Spout2::Spout_static Spout2::SpoutLibrary)
Vcpkg doesn't want to build both `Spout2::Spout` and `Spout2::Spout_static` in the same triplet. Only one will match the triplet's `VCPKG_LIBRARY_LINKAGE`.
And IIUC `Spout2::SpoutLibrary` isn't much more than another DLL interface to `Spout2::Spout_static`? Correct me if I'm wrong. In that case user probably wouldn't explicitly link another Spout2 lib at the same time.

2023-03-11 09:07 UTC, cnSchwarzer commented on ports/spout2/usage
>      target_link_libraries(main PRIVATE Spout2::Spout_static Spout2::SpoutLibrary)
> Vcpkg doesn't want to build both Spout2::Spout and Spout2::Spout_static in the same triplet. Only one will match the triplet's VCPKG_LIBRARY_LINKAGE.
The library's cmake file was designed in such way, and I'm not going to do massive change to it, so let's just keep it like this.

> And IIUC Spout2::SpoutLibrary isn't much more than another DLL interface to Spout2::Spout_static? Correct me if I'm wrong. In that case user probably wouldn't explicitly link another Spout2 lib at the same time.
Yes, a feature should do.

2023-03-12 05:39 UTC, dg0yt commented on ports/spout2/portfile.cmake
> +    list(APPEND OPTIONS -DSPOUT_BUILD_LIBRARY=OFF)
Can't this be done with` vcpkg_check_features()`?

2023-03-12 07:38 UTC, cnSchwarzer commented on ports/spout2/portfile.cmake
> +    list(APPEND OPTIONS -DSPOUT_BUILD_LIBRARY=OFF)
Sorry... Never heard about this function. I'll replace it.

2023-03-12 15:26 UTC, dg0yt commented on ports/spout2/portfile.cmake
> +        -DSPOUT_BUILD_LIBRARY=${SPOUT_BUILD_LIBRARY}
Instead of these two lines, you only need `${FEATURE_OPTIONS}`.

2023-03-12 16:56 UTC, cnSchwarzer commented on ports/spout2/portfile.cmake
> +        -DSPOUT_BUILD_LIBRARY=${SPOUT_BUILD_LIBRARY}
Splendid

2023-03-13 07:06 UTC, jimwang118 commented
All feature passed with following triplets:

x64-windows
x64-windows-static

2023-03-13 07:12 UTC, dg0yt commented
This comment was marked as resolved, but isn't IMO:
> Vcpkg doesn't want to build both Spout2::Spout and Spout2::Spout_static in the same triplet. Only one will match the triplet's VCPKG_LIBRARY_LINKAGE.

2023-03-13 09:39 UTC, cnSchwarzer commented
I can change the cmake file to prevent building static target, but I don't agree to do massive change and rename Spout_static to Spout and make the port respect the compiler setting.

2023-03-13 10:10 UTC, LilyWangLL requested changes

2023-03-13 10:10 UTC, LilyWangLL commented on ports/spout2/portfile.cmake
> +    ${CURRENT_PACKAGES_DIR}/debug/share)
```suggestion
    "${CURRENT_PACKAGES_DIR}/debug/include")
```

2023-03-13 10:10 UTC, LilyWangLL commented on ports/spout2/portfile.cmake
> +vcpkg_cmake_config_fixup()
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/${PORT})
```
This can fix the config path instead of patch `fixup_for_vcpkg.patch`.

2023-03-13 10:10 UTC, LilyWangLL commented on ports/spout2/portfile.cmake
> +        fixup_for_vcpkg.patch
```suggestion
```

2023-03-13 10:10 UTC, LilyWangLL commented on ports/spout2/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2023-03-13 10:28 UTC, LilyWangLL approved these changes, later dismissed

2023-03-15 02:38 UTC, cnSchwarzer commented
Why this still not merged?👀

2023-03-15 05:26 UTC, dg0yt reviewed
Does this port need OpenGL-related dependencies?
It has 
~~~
#include <gl/gl.h> // For OpenGL definitions
~~~

2023-03-15 05:26 UTC, dg0yt commented on ports/spout2/vcpkg.json
> +    },
TBH I wonder if this makes sense to be a separate feature.

2023-03-15 05:44 UTC, cnSchwarzer commented on ports/spout2/vcpkg.json
> +    },
I don't care about this because I use this library in my C++ project, and this C-compatible library can also be switched on/off by `SPOUT_BUILD_LIBRARY`. It really doesn't make any significant difference about whether separating this option as a feature or not. So I'll just leave it there.

2023-03-15 05:48 UTC, cnSchwarzer commented
> Does this port need OpenGL-related dependencies?

Yes, but it seems included in Windows SDK and doesn't makes a dependency error on both my computer and CI.

2023-03-15 06:16 UTC, dg0yt commented on ports/spout2/vcpkg.json
> +    },
We can add features at any time, but it is disruptive to remove them. 

AFAICS this library has C++ API, so `c` is a disnomer. 
https://github.com/leadedge/Spout2/blob/master/SPOUTSDK/SpoutLibrary/SpoutLibrary.h

AFAIU it is just a tiny alternative DLL surface on top of `Spout_static`.
https://github.com/leadedge/Spout2/blob/master/SPOUTSDK/SpoutLibrary/CMakeLists.txt

That's why I'm reluctant to accept a feature `c` here.

2023-03-15 06:55 UTC, cnSchwarzer commented
Thank for telling that, I'll add it.

2023-03-15 06:57 UTC, cnSchwarzer commented on ports/spout2/vcpkg.json
> +    },
Sound reasonable, I'll remove that.

2023-03-15 17:48 UTC, merged