[libxml2] add more features
microsoft/vcpkg pull request #30154
Opened 2023-03-13 12:40 UTC by yurybura

Move hardcoded external dependencies (libiconv, liblzma, zlib) to features, disable legacy flag by default.

2023-03-13 20:23 UTC, dg0yt requested changes
Please don't change the formatting.

The network features are controversial.
FTP is off by default upstream, so it should be off by default in vcpkg.
HTTP is on by default upstream, but this breaks uwp.
IMO both could be off by default because they are don't offer secure communication.

2023-03-13 21:16 UTC, yurybura commented
> Please don't change the formatting.

Ok.

> The network features are controversial. FTP is off by default upstream, so it should be off by default in vcpkg. 

FTP is off by default in the library, but it was enabled by default in VCPKG. Ok, I will follow library defaults.

> HTTP is on by default upstream, but this breaks uwp.

HTTP and FTP are off on UWP in port's JSON: https://github.com/microsoft/vcpkg/pull/30154/files#diff-642422f43590726b42670763cb558af55056b3c1b9e8218f00a01bf1d753c102R32

2023-03-14 04:23 UTC, dg0yt commented
> HTTP and FTP are off on UWP in port's JSON:

They are not supported on UWP but still default features on all platforms. That's why the default installation is now broken for UWP.

2023-03-14 08:37 UTC, yurybura commented
> > HTTP and FTP are off on UWP in port's JSON:
> 
> They are not supported on UWP but still default features on all platforms. That's why the default installation is now broken for UWP.

@dg0yt Thank you for the help. Can you explain how to find this error in CI log? I see only failing ffmpeg, but not libxml2.
I thought that not supported features shouldn't be enabled by default.

2023-03-14 12:39 UTC, dg0yt commented
> Can you explain how to find this error in CI log? I see only failing ffmpeg, but not libxml2.
> I thought that not supported features shouldn't be enabled by default.

The last assumption is wrong, unfortunately.

In CI, you can find this:
~~~
2023-03-13T21:24:25.0719853Z Determining parent hashes using HEAD~1
...
2023-03-13T21:24:37.7602418Z                          libxml2:x64-uwp:        *: fc1251a26227be5ea7e8d85511264909ea6130594175934b5e57573f149dd7c7
...
2023-03-13T21:24:38.2563362Z The following packages will be built and installed:
...
2023-03-13T21:24:38.5708655Z     libxml2[core]:x64-uwp -> 2.10.3
~~~
i.e. it tinyxml2 would build for master, but now for your PR merged into master:
~~~
2023-03-13T21:24:38.8263790Z Running CI using parent hashes
2023-03-13T21:24:38.9107487Z HEAD is now at 406598af0 Merge 8b1c3a90708f580b7c849e60c3f03a5119114251 into f09a2226865dd00a54b983933dd29ab29bca8bf6
...
2023-03-13T21:24:50.6519768Z                          libxml2:x64-uwp:  cascade
~~~
i.e. libxml2 is already known to be unsupported and is not even considered for build, which in turn causes
~~~
2023-03-13T21:24:51.4587144Z ##[error]REGRESSIONS:
REGRESSION: vcpkg-ci-ffmpeg:x64-uwp cascaded, but it is required to pass. (C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt).
~~~
because is vcpkg-ci-ffmpeg is required to pass, but has unsatisfied requirements.

2023-03-14 12:43 UTC, dg0yt commented
You can probably also check locally with  `vcpkg install --dry-run libxml2:x64-uwp`.

2023-03-17 02:18 UTC, jimwang118 commented
@yurybura There is a conflict in the code you submitted, and the conflict needs to be resolved before CI can run.

2023-03-17 06:30 UTC, dg0yt requested changes

2023-03-19 16:33 UTC, yurybura commented on ports/libxml2/vcpkg.json
> +    },
Reverted.

2023-03-19 21:22 UTC, yurybura commented
@jimwang118 All checks has been done.

2023-03-20 02:35 UTC, jimwang118 commented
All feature passed with following triplets:

x86-windows
x64-windows
x64-windows-static

2023-03-22 01:59 UTC, LilyWangLL approved these changes

2023-03-22 23:20 UTC, merged