Bump foonathan-memory version.
microsoft/vcpkg pull request #30212
Opened 2023-03-15 19:21 UTC by marcovc

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-03-16 06:47 UTC, Cheney-W commented on ports/foonathan-memory/portfile.cmake
> +    REF 0f0775770fd1c506fa9c5ad566bd6ba59659db66
```suggestion
    REF "v${VERSION}"
```

2023-03-16 06:49 UTC, Cheney-W requested changes
Please do not modify the contents of the entire portfile.cmake file.

2023-03-16 06:49 UTC, Cheney-W commented on ports/foonathan-memory/vcpkg.json
>    "port-version": 2,
```suggestion
```
If you update the `version-string`, then the `port-version` should be removed.

2023-03-16 16:35 UTC, autoantwort commented
> Could you be more specific? I only modified the REF and SHA512 and commented some lines that were preventing compilation.

The git diff shows that you changed the whole file content, probably by changing the line endings in the file

2023-03-17 09:15 UTC, Cheney-W commented on ports/foonathan-memory/portfile.cmake
> +#)
Please remove the useless codes directly instead of commenting them.

2023-03-17 09:16 UTC, Cheney-W commented on ports/foonathan-memory/portfile.cmake
> +#)
ditto

2023-03-17 09:16 UTC, Cheney-W commented on ports/foonathan-memory/vcpkg.json
>    "homepage": "https://foonathan.net/doc/memory/",
```suggestion
  "homepage": "https://foonathan.net/doc/memory/",
  "license": "Zlib",
```

2023-03-20 02:24 UTC, Cheney-W commented
```
CMake Error in src/cpp/CMakeLists.txt:
  Imported target "foonathan_memory" includes non-existent path

    "D:/installed/x86-windows/include/foonathan_memory"

  in its INTERFACE_INCLUDE_DIRECTORIES.
```
Error logs: https://dev.azure.com/vcpkg/public/_build/results?buildId=86808&view=artifacts&pathAsName=false&type=publishedArtifacts

2023-03-23 10:21 UTC, marcovc commented
> ```
> CMake Error in src/cpp/CMakeLists.txt:
>   Imported target "foonathan_memory" includes non-existent path
> 
>     "D:/installed/x86-windows/include/foonathan_memory"
> 
>   in its INTERFACE_INCLUDE_DIRECTORIES.
> ```
> 
> Error logs: https://dev.azure.com/vcpkg/public/_build/results?buildId=86808&view=artifacts&pathAsName=false&type=publishedArtifacts

Unfortunately I don't know enough about this library to be able to fix this.

2023-06-12 02:10 UTC, Cheney-W commented
Duplicate of https://github.com/microsoft/vcpkg/pull/31905

2023-06-12 02:10 UTC, closed without merging