[apr] Update to 1.7.2
microsoft/vcpkg pull request #30217
Opened 2023-03-15 20:19 UTC by klalumiere

Fixes #30216 (hence, fixes [CVE-2021-35940](https://www.cve.org/CVERecord?id=CVE-2021-35940))

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-03-15 20:32 UTC, klalumiere commented
I'll debug `apr-util` failure.

2023-03-15 22:58 UTC, klalumiere commented
It's green! :heavy_check_mark: :tada:

2023-03-16 03:08 UTC, FrankXie05 requested changes

2023-03-16 03:08 UTC, FrankXie05 commented on ports/apr/portfile.cmake
>  vcpkg_extract_source_archive_ex(
Could you please use the new function? `vcpkg_extract_source_archive` :)
https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_extract_source_archive

2023-03-16 05:48 UTC, FrankXie05 approved these changes, later dismissed

2023-03-16 05:48 UTC, FrankXie05 commented on ports/apr/portfile.cmake
>  vcpkg_extract_source_archive_ex(
Not necessary, just suggestions.

2023-03-16 20:24 UTC, klalumiere commented
It's done! :smile:

2023-03-17 02:13 UTC, FrankXie05 approved these changes

2023-03-20 06:36 UTC, merged