[Jsonifier] New Port
microsoft/vcpkg pull request #30276
Opened 2023-03-19 01:56 UTC by RealTimeChris

- [Yes] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [Nope] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [Yes] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [Yes] The versioning scheme in `vcpkg.json` matches what upstream says.
- [Yes] The license declaration in `vcpkg.json` matches what upstream says.
- [Yes] The installed as the "copyright" file matches what upstream says.
- [Yes] The source code of the component installed comes from an authoritative source.
- [Yes] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [Yes] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [Yes] Only one version is in the new port's versions file.
- [Yes] Only one version is added to each modified port's versions file.

2023-03-19 07:35 UTC, dg0yt commented on ports/jsonifier/vcpkg.json
> +  "supports": "(windows & x64 & !static) | (linux & x64)",
Oh, this is tight. Why should handling JSON exclude arm or os or dynamic linkage?
Will have a look at upstream.

2023-03-19 07:39 UTC, RealTimeChris commented on ports/jsonifier/vcpkg.json
> +  "supports": "(windows & x64 & !static) | (linux & x64)",
I haven't written the fallback for arm - and don't you mean that I'm excluding static linkage? Tbh I forgot to check that individual part before pushing the repo I believe it does support static linkage.

2023-03-20 04:40 UTC, RealTimeChris commented
Hey so it seems to be throwing a "read violation" in uwp upon attempting to run a necessary test to detect CPU architecture.
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/86911/artifacts?artifactName=failure%20logs%20for%20x64-uwp&api-version=7.0&%24format=zip

2023-03-20 05:08 UTC, dg0yt commented
uwp is a cross build. Simply do not run anything for the target, it is always a barrier for cross-builds.

2023-03-20 06:22 UTC, RealTimeChris commented
> uwp is a cross build. Simply do not run anything for the target, it is always a barrier for cross-builds.

How do I not run anything for the target?

2023-03-20 06:33 UTC, dg0yt commented
> > uwp is a cross build. Simply do not run anything for the target, it is always a barrier for cross-builds.
> 
> How do I not run anything for the target?

Do not use any `*_SOURCE_RUNS` or similar (here: `FindAVX.cmake`).
Or make the port directly set the expected results for each target CPU, so that the actual test is skipped.

2023-03-20 10:00 UTC, jimwang118 requested changes

2023-03-20 10:00 UTC, jimwang118 commented on ports/jsonifier/vcpkg.json
> +  "supports": "(windows & x64 & !uwp) | (linux & x64) | (osx & x64)",
Doesn't this library upstream support x86 builds?

2023-03-20 10:03 UTC, RealTimeChris commented on ports/jsonifier/vcpkg.json
> +  "supports": "(windows & x64 & !uwp) | (linux & x64) | (osx & x64)",
No I don't believe it does as it utilizes AVX/AVX2/AVX512 instruction sets.

2023-03-21 01:31 UTC, jimwang118 requested changes

2023-03-21 01:31 UTC, jimwang118 commented on ports/jsonifier/portfile.cmake
> +)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/License.md")
```

2023-03-21 01:31 UTC, jimwang118 commented on ports/jsonifier/vcpkg.json
> +  "homepage": "https://https://github.com/RealTimeChris/Jsonifier",
```suggestion
  "homepage": "https://github.com/RealTimeChris/Jsonifier",
```

2023-03-21 04:50 UTC, dg0yt commented
I still wonder whether this lib requires C++20 or C++23.

Being header-only, it really shouldn't deal with AVX detection at port build time IMO. Artifact caching will easily give the wrong package. If not autodetected at runtime, a possible solution is to create independet targets (as in ports fbgemm, libsodium).

2023-03-21 05:03 UTC, RealTimeChris commented
> I still wonder whether this lib requires C++20 or C++23.
> 
> Being header-only, it really shouldn't deal with AVX detection at port build time IMO. Artifact caching will easily give the wrong package. If not autodetected at runtime, a possible solution is to create independet targets (as in ports fbgemm, libsodium).

It uses std::expected, so it requires C++23. Also that's an interesting idea RE: Independent Targets.

2023-03-22 01:45 UTC, jimwang118 requested changes

2023-03-22 01:45 UTC, jimwang118 commented on ports/jsonifier/portfile.cmake
> +vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/License.md")
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/License.md")

```

2023-03-22 02:04 UTC, jimwang118 commented
Tested usage successfully by the x64-windows triplet.
```
find_package(Jsonifier CONFIG REQUIRED)
target_link_libraries(main PRIVATE Jsonifier::Jsonifier)
```

2023-03-23 01:42 UTC, jimwang118 approved these changes

2023-03-23 16:44 UTC, merged