[cppslippi] Add new port
microsoft/vcpkg pull request #30315
Opened 2023-03-20 18:16 UTC by Kered13

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [X] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says.
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [X] Only one version is added to each modified port's versions file.

2023-03-20 21:08 UTC, dg0yt reviewed
Given upstream's repo name and in particular the cmake config name, it might make sense to choose `cppslippi` for the port name.

2023-03-20 21:08 UTC, dg0yt commented on ports/cpp-slippi/portfile.cmake
> +set(VERSION 1.0.3.14)
This isn't needed. `VERSION` is already set to the value from `vcpkg.json`.

2023-03-20 21:08 UTC, dg0yt commented on versions/c-/cpp-slippi.json
> +    }
Oops, too much.

2023-03-20 21:30 UTC, Kered13 commented on versions/c-/cpp-slippi.json
> +    }
All comments have been addressed. Port renamed from cpp-slippi to cppslippi (I wasn't sure what the right convention here was).

2023-03-20 21:33 UTC, Kered13 commented
Port renamed from cpp-slippi to cppslippi.

I wasn't sure what the convention here was.

2023-03-20 21:58 UTC, Kered13 commented
Ran `vcpkg x-add-version cppslippi --overwrite-version` again to fix the version file and pushed.

2023-03-20 22:28 UTC, Kered13 commented
Removed one more leftover reference to `cpp-slippi`.

2023-03-21 02:37 UTC, LilyWangLL requested changes

2023-03-21 02:37 UTC, LilyWangLL commented on ports/cppslippi/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH lib/share/CppSlippi)
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
```
Since `CppSlippi-config.cmake` was installed in _lib/share_ folder, so need to handle it too.

2023-03-21 02:37 UTC, LilyWangLL commented on ports/cppslippi/portfile.cmake
> +file(COPY "${SOURCE_PATH}/README.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion
file(COPY "${SOURCE_PATH}/README.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/share" "${CURRENT_PACKAGES_DIR}/lib/share")
```

2023-03-21 03:33 UTC, Kered13 commented
Suggested changes applied.

2023-03-21 03:36 UTC, Kered13 commented
Actually, would it be better to apply changes to the upstream repo? I was still figuring out how to use CMake, so I don't know if I installed all the files in the right place.

2023-03-21 05:10 UTC, dg0yt commented on scripts/ci.baseline.txt
> +cppslippi:x64-osx=fail
Are you sure this is missing, or does the project need help with configuration?

2023-03-21 05:10 UTC, dg0yt commented on ports/cppslippi/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
Why does it need two lines here?
The config only needs to exist in one location. This should be fixed upstream.
(`lib/share/..` looks unusual. If it wouldn't exist, it wouldn't need to be removed later.)

2023-03-21 05:37 UTC, Kered13 commented on scripts/ci.baseline.txt
> +cppslippi:x64-osx=fail
You are welcome to take a look, I would prefer to not need these exclusions. But I think it is correct. C++20 is configured as a requirement for the library here: https://sourceforge.net/p/cppslippi/code/ci/default/tree/CMakeLists.txt#l32

The error logs from when the CI ran without these exclusions can still be seen [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=86954&view=artifacts&pathAsName=false&type=publishedArtifacts).

I asked on the C++ Discord (vcpkg channel) about this and was told that the CI is running GCC 9.3:

> CI has the compiler that comes with Ubuntu 20.04 which is GCC 9.3.0. (We are still blocked from deploying Ubuntu 22.04 by https://github.com/microsoft/azure-pipelines-agent/issues/3834)

And if you check on Godbolt you will indeed get the same error if you try to `#include <concepts>` on GCC 9.3. GCC 10.0 is required, at least for Linux, in order to build. My library depends on other C++20 features as well, `<concepts>` is just the one that shows up in the error logs.

2023-03-21 05:41 UTC, Kered13 commented on ports/cppslippi/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
This was suggested by @LilyWangLL, above. I'm still new to CMake so I'm not exactly sure what is right here or in my upstream. My upstream configuration is [here](https://sourceforge.net/p/cppslippi/code/ci/default/tree/CMakeLists.txt#l70). Are you saying that lines 70-73 should be deleted?

2023-03-21 05:49 UTC, LilyWangLL commented on ports/cppslippi/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
```
-- Installing: E:/Lily/vcpkg/packages/cppslippi_x64-windows/debug/lib/cmake/CppSlippi/CppSlippiTargets.cmake
-- Installing: E:/Lily/vcpkg/packages/cppslippi_x64-windows/debug/lib/cmake/CppSlippi/CppSlippiTargets-debug.cmake
-- Installing: E:/Lily/vcpkg/packages/cppslippi_x64-windows/debug/lib/share/CppSlippi/CppSlippi-config.cmake
-- Installing: E:/Lily/vcpkg/packages/cppslippi_x64-windows/debug/lib/share/CppSlippi/CppSlippi-config-version.cmake
```
Its config and targets files in different folder.

2023-03-21 05:53 UTC, dg0yt commented on ports/cppslippi/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
You need to fix it upstream. `CppSlippi-config.cmake` is probably installed twice, once via `INSTALL_DESTINATION` and once via `install(FILES ...)`. But there should be only one installation, in one directory with config, config-version, and targets.

2023-03-21 05:58 UTC, LilyWangLL commented
> Actually, would it be better to apply changes to the upstream repo? I was still figuring out how to use CMake, so I don't know if I installed all the files in the right place.

Most ports install their config and targets files to _lib/cmake_ folder, I think you could change the following codes in upstream, just change config file's install path, then still use `vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)` to fix them on vcpkg.

https://sourceforge.net/p/cppslippi/code/ci/default/tree/CMakeLists.txt#:~:text=install(FILES,share/CppSlippi)
```
install(FILES
		"${CMAKE_CURRENT_BINARY_DIR}/CppSlippi-config.cmake"
		"${CMAKE_CURRENT_BINARY_DIR}/CppSlippi-config-version.cmake"
	DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/CppSlippi)
```

2023-03-21 06:16 UTC, Kered13 commented
Thank you both for your help, I believe I have the installation fixed upstream now.

2023-03-21 06:16 UTC, Kered13 commented on ports/cppslippi/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/CppSlippi)
Fixed upstream.

2023-03-21 06:17 UTC, Kered13 commented on scripts/ci.baseline.txt
> +cppslippi:x64-osx=fail
I am marking this as resolved for now, if you think there is something that can be done to make the CI pass on Linux and OS X, feel free to reopen.

2023-03-21 06:21 UTC, dg0yt commented on scripts/ci.baseline.txt
> +cppslippi:x64-osx=fail
If you don't mark this discussion as resolved, your explanation will remain visible for others who aren't following discord.
And I don't see osx being mentioned in the answer.

2023-03-21 07:44 UTC, LilyWangLL commented
/azp run

2023-03-21 08:25 UTC, LilyWangLL commented
I use your latest commit to install `cppslippi:x64-windows` failed with the following error:
```
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/Lily/vcpkg/buildtrees/cppslippi/x64-windows-dbg
    See logs for more information:
      E:\Lily\vcpkg\buildtrees\cppslippi\install-x64-windows-dbg-out.log
      E:\Lily\vcpkg\buildtrees\cppslippi\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/cppslippi/portfile.cmake:15 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```
**install-x64-windows-dbg-err.log**
```
ninja: error: manifest 'build.ninja' still dirty after 100 tries, perhaps system time is not set
```

2023-03-21 13:14 UTC, Kered13 commented on scripts/ci.baseline.txt
> +cppslippi:x64-osx=fail
On OS X the error is slightly different, but I believe the underlying cause is basically same. From the logs above, you can see that the error message is:

```FAILED: CMakeFiles/CppSlippi.dir/CppSlippi/Model/Enums/Costume.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++  -I/Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean -isystem /Users/vagrant/Data/installed/x64-osx/include -fPIC -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -std=c++20 -MD -MT CMakeFiles/CppSlippi.dir/CppSlippi/Model/Enums/Costume.cpp.o -MF CMakeFiles/CppSlippi.dir/CppSlippi/Model/Enums/Costume.cpp.o.d -o CMakeFiles/CppSlippi.dir/CppSlippi/Model/Enums/Costume.cpp.o -c /Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean/CppSlippi/Model/Enums/Costume.cpp
In file included from /Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean/CppSlippi/Model/Enums/Costume.cpp:1:
In file included from /Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean/CppSlippi/Model/Enums/Costume.h:8:
/Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean/CppSlippi/Model/Enums/Character.h:13:2: error: no type named 'integral' in namespace 'std'
        DEFINE_ENUM(CssCharacter, uint8_t,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean/CppSlippi/Utils/Enums.h:38:5: note: expanded from macro 'DEFINE_ENUM'
    ENUM_COMMON(Name, Type, __VA_ARGS__)                    \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vagrant/Data/buildtrees/cpp-slippi/src/77f14b0cea-b5f578d32f.clean/CppSlippi/Utils/Enums.h:13:23: note: expanded from macro 'ENUM_COMMON'
        template<std::integral T>                                     \
                 ~~~~~^
```

So the compiler does not recognize [std::integral](https://en.cppreference.com/w/cpp/concepts/integral). The is [here](https://sourceforge.net/p/cppslippi/code/ci/default/tree/CppSlippi/Utils/Enums.h) and you can see that it correctly includes `<concepts>`. I don't have a Mac and Godbolt doesn't have an OS X mode, so I cannot investigate this any further, but it appears to be a problem again of the compiler being out of date.

2023-03-21 13:18 UTC, Kered13 commented
> I use your latest commit to install `cppslippi:x64-windows` failed with the following error:
> 
> ```
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
>     Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
>     Working Directory: E:/Lily/vcpkg/buildtrees/cppslippi/x64-windows-dbg
>     See logs for more information:
>       E:\Lily\vcpkg\buildtrees\cppslippi\install-x64-windows-dbg-out.log
>       E:\Lily\vcpkg\buildtrees\cppslippi\install-x64-windows-dbg-err.log
> 
> Call Stack (most recent call first):
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
>   ports/cppslippi/portfile.cmake:15 (vcpkg_cmake_install)
>   scripts/ports.cmake:147 (include)
> ```
> 
> **install-x64-windows-dbg-err.log**
> 
> ```
> ninja: error: manifest 'build.ninja' still dirty after 100 tries, perhaps system time is not set
> ```

I cannot tell from this error message what the issue is. Are there any more helpful logs?

This works on my machine:

```C:\Users\Derek\Projects\vcpkg>vcpkg install cppslippi:x64-windows
Computing installation plan...
The following packages will be built and installed:
    cppslippi[core]:x64-windows -> 1.0.3.14
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Derek\AppData\Local\vcpkg\archives in 184.6 us. Use --debug to see more details.
Installing 1/1 cppslippi:x64-windows...
Building cppslippi[core]:x64-windows...
-- Using cached CppSlippi-1.0.3.14.zip.
-- Cleaning sources at C:/Users/Derek/Projects/vcpkg/buildtrees/cppslippi/src/f7ad602032-5f0c04ad7a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Derek/Projects/vcpkg/downloads/CppSlippi-1.0.3.14.zip
-- Using source at C:/Users/Derek/Projects/vcpkg/buildtrees/cppslippi/src/f7ad602032-5f0c04ad7a.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/Users/Derek/Projects/vcpkg/packages/cppslippi_x64-windows/share/cppslippi/copyright
-- Performing post-build validation
Stored binary cache: "C:\Users\Derek\AppData\Local\vcpkg\archives\ae\ae3abd5ec6fe7526b2b939cb2b42656de1d2af2f6bb1c93677b72bf491de9c9d.zip"
Elapsed time to handle cppslippi:x64-windows: 48.887354 s
Total install time: 55.8035165 s
The package cppslippi provides CMake targets:

    find_package(CppSlippi CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CppSlippi::CppSlippi)```

2023-03-23 08:14 UTC, LilyWangLL commented
@Kered13 Please add the following codes in **CMakeLists.txt**, this will install config files, if not the usage can't use because CMake can't find config files.

https://sourceforge.net/p/cppslippi/code/ci/default/tree/CMakeLists.txt#l75:~:text=COMPATIBILITY%20AnyNewerVersion)-,%23%20Release,-if(CMAKE_PROJECT_NAME

```
install(FILES
	"${CMAKE_CURRENT_BINARY_DIR}/CppSlippi-config.cmake"
	"${CMAKE_CURRENT_BINARY_DIR}/CppSlippi-config-version.cmake"
	DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/CppSlippi)

# Release
```

2023-03-24 16:40 UTC, Kered13 commented
Requested changes applied upstream.

2023-03-27 10:10 UTC, LilyWangLL approved these changes

2023-03-27 10:11 UTC, LilyWangLL commented
Usage test pass on `x64-windows`.

2023-03-28 20:25 UTC, merged