[vcpkg] Bump to 4.5.3.
microsoft/vcpkg pull request #30366
Opened 2023-03-22 14:31 UTC by SvenPStarFinanz

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-03-23 06:58 UTC, SvenPStarFinanz commented
The commit message was wrong, meant [sqlcipher].

2023-03-23 08:09 UTC, FrankXie05 requested changes

2023-03-23 08:09 UTC, FrankXie05 commented on ports/sqlcipher/portfile.cmake
> +    REF v4.5.3
```suggestion
    REF "v${VERSION}"

```
We can use the new method. :)

2023-03-23 08:10 UTC, FrankXie05 commented on ports/sqlcipher/portfile.cmake
> +    REF v4.5.3
It's not necessary, but I'll wait a day for the user to respond.

2023-03-23 08:41 UTC, FrankXie05 requested changes

2023-03-23 08:41 UTC, FrankXie05 commented on ports/sqlcipher/portfile.cmake
> +    SHA512 27dcc83c8088ea32a2bbc3d5493d070e29976dc54ccf91d849df67be19cb553761a32b3613e293a07f50128aeb808d54f363ad12a58a47f06a61a1cc4e1eb0cd
```suggestion
    REF "v${VERSION}"
    SHA512 27dcc83c8088ea32a2bbc3d5493d070e29976dc54ccf91d849df67be19cb553761a32b3613e293a07f50128aeb808d54f363ad12a58a47f06a61a1cc4e1eb0cd

```
No blank lines required.

2023-03-23 08:46 UTC, FrankXie05 submitted a review, later dismissed

2023-03-24 07:02 UTC, FrankXie05 approved these changes

2023-03-25 06:02 UTC, merged