[kd-soap] update to 2.1.1 and build against Qt6
microsoft/vcpkg pull request #30371
Opened 2023-03-22 16:23 UTC by MehdiChinoune

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2023-03-24 08:59 UTC, LilyWangLL requested changes

2023-03-24 09:00 UTC, MehdiChinoune commented on ports/kd-soap/portfile.cmake
>  )
Doesn't contain git submodules.

2023-03-24 10:00 UTC, LilyWangLL requested changes

2023-03-24 10:06 UTC, LilyWangLL requested changes

2023-03-24 10:09 UTC, LilyWangLL commented
Are the following files useful? If not, please move them to share folder or remove them.
![image](https://user-images.githubusercontent.com/94091114/227491583-d8c8a492-b0fc-4c51-83fb-61aa916e1597.png)

2023-03-24 13:28 UTC, MehdiChinoune commented
> Are the following files useful? If not, please move them to share folder or remove them. ![image](https://user-images.githubusercontent.com/94091114/227491583-d8c8a492-b0fc-4c51-83fb-61aa916e1597.png)

I think They could used by qmake projects, but I am sure about that. Leaving them there won't hurt I guess.

2023-03-24 13:30 UTC, MehdiChinoune commented
> Usage test failed with the following error, this should be fixed by add `find_dependency` into *config.cmake.
> 
> ```
> 1> [CMake] CMake Error at E:/Lily/test/installed/x64-windows/share/KDSoap-qt6/KDSoapTargets.cmake:60 (set_target_properties):
> 1> [CMake]   The link interface of target "KDSoap::kdsoap" contains:
> 1> [CMake] 
> 1> [CMake]     Qt6::Core
> 1> [CMake] 
> 1> [CMake]   but the target was not found.  Possible reasons include:
> 1> [CMake] 
> 1> [CMake]     * There is a typo in the target name.
> 1> [CMake]     * A find_package call is missing for an IMPORTED target.
> 1> [CMake]     * An ALIAS target is missing.
> ```

I don't think I could do something about this, This is an upstream issue.

2023-03-24 21:06 UTC, MehdiChinoune commented
https://github.com/KDAB/KDSoap/issues/258

2023-03-25 21:29 UTC, Neumann-A commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
What is the defaul installed name before `vcpkg_cmake_config_fixup`. if it doesn't include qt6 this is a hard no!

2023-03-25 21:31 UTC, MehdiChinoune commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
It's the default name.

2023-03-25 22:12 UTC, Neumann-A commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
I feel like upstream is in the wrong here since that forces all downstream users to add this suffix. But ok.

2023-03-25 22:12 UTC, Neumann-A commented
> I don't think I could do something about this, This is an upstream issue.

It is but it is easily fixiable by patching the call into the config.cmake template upstream provides.

2023-03-25 22:20 UTC, MehdiChinoune commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
I could patch it!

2023-03-26 06:18 UTC, dg0yt commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
Don't patch. It is upstream's explicit choice.
https://github.com/KDAB/KDSoap/blob/731a1202423a6e659b903110df6a3d5865d75343/CMakeLists.txt#L220-L232

2023-03-26 06:21 UTC, MehdiChinoune commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
I know It's not a bug, They did that to allow parallel installation with qt5 version.
I could patch it to set ${PROJECT_NAME}_LIBRARY_QTID="" the same as Qt5 https://github.com/KDAB/KDSoap/blob/731a1202423a6e659b903110df6a3d5865d75343/CMakeLists.txt#L117

2023-03-26 06:56 UTC, dg0yt commented on ports/kd-soap/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME KDSoap-qt6 CONFIG_PATH lib/cmake/KDSoap-qt6)
And that patch would create a bug because it would remove the `KDSoap-qt6` package name.

2023-03-26 16:07 UTC, MehdiChinoune commented
I have backported the fix from upstream

2023-03-27 06:50 UTC, LilyWangLL requested changes

2023-03-27 06:50 UTC, LilyWangLL commented on ports/kd-soap/portfile.cmake
> +        Ensure-KDSoapConfig-finds-Qt-first.patch
```suggestion
```

2023-03-27 06:50 UTC, LilyWangLL commented on ports/kd-soap/portfile.cmake
> +    ARCHIVE "${ARCHIVE}"
```suggestion
    ARCHIVE "${ARCHIVE}"
    PATCHES
        Ensure-KDSoapConfig-finds-Qt-first.patch
```

2023-03-27 06:51 UTC, LilyWangLL commented
Usage test passed on `x64-windows`.

2023-03-27 06:52 UTC, LilyWangLL commented on ports/kd-soap/portfile.cmake
> +    ARCHIVE "${ARCHIVE}"
Patch should be added by function `vcpkg_extract_source_archive`.

2023-03-27 07:11 UTC, MehdiChinoune commented on ports/kd-soap/portfile.cmake
> +    ARCHIVE "${ARCHIVE}"
Sorry!

2023-03-27 07:20 UTC, LilyWangLL approved these changes

2023-03-27 18:57 UTC, merged