[theia] use support expression
microsoft/vcpkg pull request #30465
Opened 2023-03-27 15:03 UTC by autoantwort

2023-03-27 17:40 UTC, autoantwort commented
`openimageio` seems to be a baseline regression

2023-03-28 02:47 UTC, FrankXie05 requested changes

2023-03-28 02:47 UTC, FrankXie05 commented on ports/theia/vcpkg.json
> +  "supports": "!uwp & !arm & !(windows & x86)",
What about `x64-windows`?

2023-03-28 02:49 UTC, autoantwort commented on ports/theia/vcpkg.json
> +  "supports": "!uwp & !arm & !(windows & x86)",
The ci is green, so it builds successful

2023-03-28 09:56 UTC, FrankXie05 approved these changes

2023-03-28 20:39 UTC, merged