Fixes #13331
microsoft/vcpkg pull request #30783
Opened 2023-04-11 22:05 UTC by juan-lunarg

Fixes #13331

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-04-11 22:17 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
> -  "version": "1.1.82.1",
I'm not very clear what the intent was with 1.1.82.1 specifically. Better to just make it `1` to avoid confusion.

2023-04-11 22:17 UTC, juan-lunarg commented on ports/vulkan/portfile.cmake
> -endif()
This check is overly aggressive and doesn't work in many instances. It really only works well for pure WIN32 users.

The main thing is this will NOT work with linux package managers. Which is not ideal. And while I could wrangle up something to work with the official LunarG Ubuntu packages, I know plenty of users prefer to use their own distros particular flavor (arch, fedora, debian, etc).

2023-04-11 22:17 UTC, juan-lunarg commented on ports/vulkan/portfile.cmake
> +if (WIN32 AND NOT MINGW)
I have worked with the MINGW folks to get the vulkan validation layer working with their package manager. So I know MINGW is a platform some users care about.

2023-04-11 23:02 UTC, Osyotr commented
You've just completely disabled the check on non-windows. Maybe add a dummy `CMakeLists.txt` which does a `find_package(Vulkan REQUIRED)` call?

2023-04-12 00:12 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan)
Using `find_package(Vulkan REQUIRED)` doesn't work. I had to use the `Vulkan_FOUND` variable. Not 100% sure why.

2023-04-12 00:12 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
Note this is the error message the user will receive if find_package fails currently:

```
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/juan/projects/dk/ninja/1.11.1/ninja -v
    Working Directory: /home/juan/projects/vcpkg/buildtrees/vulkan/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/juan/projects/vcpkg/buildtrees/vulkan/config-x64-linux-dbg-CMakeCache.txt.log
      /home/juan/projects/vcpkg/buildtrees/vulkan/config-x64-linux-rel-CMakeCache.txt.log
      /home/juan/projects/vcpkg/buildtrees/vulkan/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/vulkan/portfile.cmake:5 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)
```

2023-04-12 00:13 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
I'm mainly pointing this out since unless the user decides to look in `config-x64-linux-out.log` they will likely be confused.

2023-04-12 06:07 UTC, BillyONeal commented on ports/vulkan/vcpkg.json
> -  "version": "1.1.82.1",
Unfortunately you can't do that, since that makes the version go backwards. The version is set to that value because that's what the previous `portfile.cmake` looks for.

2023-04-12 06:14 UTC, JonLiu1993 commented on ports/vulkan/vcpkg.json
> +  "version": "1",
We should restore the previous version and should not add new ones.

2023-04-12 06:18 UTC, JonLiu1993 commented on ports/vulkan/portfile.cmake
> -endif()
@juan-lunarg, I have a question. After these codes are deleted, `vulkan` version seems to be unable to be upgraded, because I can’t see what this portfile.cmake has to do with the version.

2023-04-12 14:58 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
> +  "version": "1",
I can revert that. Just seems strange to have the version be 1.1.82.1 when that is not at all representative of this port.

2023-04-12 16:05 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
> -  "version": "1.1.82.1",
Reverted.

2023-04-12 16:05 UTC, juan-lunarg commented on ports/vulkan/portfile.cmake
> -endif()
I added version checking support

2023-04-12 16:56 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
> +  "version": "1",
I updated the logic to account for the version.

2023-04-12 17:23 UTC, dg0yt requested changes

2023-04-12 17:23 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +endif()
I think the ultimate trick is *to not fail* in any case, but to produce an indication which can be used by the portfile.
It may be as simple as installing `usage` on success, or writing another file on failure.

2023-04-12 17:23 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan)
With this before that line:
~~~cmake
set(CMAKE_FIND_DEBUG_MODE 1)
~~~
the log will have a detailed trace of what CMake tried.

2023-04-12 17:23 UTC, dg0yt commented on ports/vulkan/portfile.cmake
> +)
I think we should add this before these lines:
~~~cmake
set(VCPKG_BUILD_TYPE release)
~~~

2023-04-12 17:23 UTC, dg0yt commented on ports/vulkan/vcpkg.json
>    "version": "1.1.82.1",
Perhaps we should move to somethin like
~~~json
"version": "1.1.82.1+check-only"
~~~

2023-04-12 17:23 UTC, dg0yt commented on ports/vulkan/vcpkg.json
>    "description": "A graphics and compute API that provides high-efficiency, cross-platform access to modern GPUs on a wide variety of devices.",
This description should be edited to reflect that this is just an empty port checking for dependencies.
E.g. similar to port `atlmfc`:
"A stub package that ensures that the Vulkan SDK is installed."

2023-04-12 17:29 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +endif()
Is there an existing precedent I can use? If not I can wrangle something.

2023-04-12 17:36 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
>    "version": "1.1.82.1",
Does +stub do something in particular?

2023-04-12 18:35 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan)
It doesn't matter. vcpkg uses a newer version, and the older version simply log less.

2023-04-12 18:37 UTC, dg0yt commented on ports/vulkan/vcpkg.json
>    "version": "1.1.82.1",
It should be information and have an effect.  But to be honest, it probably would need a number to be actually a "never" version. I can't say exactly now, so just no need ot change this.

2023-04-12 18:39 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +endif()
I wish I knew...

2023-04-13 00:22 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
>    "version": "1.1.82.1",
Apologies I'm a little confused. Should I add the `+stub`?

2023-04-13 00:23 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
>    "description": "A graphics and compute API that provides high-efficiency, cross-platform access to modern GPUs on a wide variety of devices.",
Agree that's much less misleading. Sadly the version number is still confusing.

2023-04-13 00:27 UTC, juan-lunarg commented on ports/vulkan/vcpkg.json
>    "version": "1.1.82.1",
I mean the main problem is this version is confusing. Ideally IMO it would just be version 1. To indicate you are using Vulkan SDK major version 1.

2023-04-13 01:59 UTC, JonLiu1993 commented on ports/vulkan/vcpkg.json
>    "version": "1.1.82.1",
I personally think that we should keep the version consistent with the previous version and should not modify it.

2023-04-13 02:07 UTC, JonLiu1993 requested changes

2023-04-13 02:07 UTC, JonLiu1993 commented on ports/vulkan/CMakeLists.txt
> +endif()
I think it would be better if these can be detected and implemented in portfile.cmake.

2023-04-13 04:04 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +endif()
Portfiles are run in script mode, not project mode. There are some hacks to make `find_...` stuff work to some extent, but I would discourage this practice. We want to see the result for project mode, not debug the script mode hacks, and project mode is easily available.

2023-04-13 06:54 UTC, JonLiu1993 commented
@juan-lunarg, I installed `VulkanSDK` version `1.3.243` locally, and then cloned your library to install `Vulkan` locally, and it appeared the log you set:
````
Could NOT find Vulkan (missing: Vulkan_LIBRARY) (found version "1.3.243")
````
At present, only the version `1.1.82` of `Vulkan` will be installed successfully. Install` Vulkan` successfully, right?

2023-04-13 17:36 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +endif()
I added explicit error checking for the `VULKAN_SDK` environment variable. After reading the `FindVulkan.cmake` code.

https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindVulkan.cmake#L244

Could you try again @JonLiu1993 ?

2023-04-13 23:15 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +endif()
Note it may be better to move this check to the `portfile` instead

2023-04-14 07:44 UTC, JonLiu1993 commented on ports/vulkan/CMakeLists.txt
> +endif()
@juan-lunarg, I tried it again locally, but it seems that the last error was reported, and I checked that my machine also set the `VULKAN_SDK` environment variable, and it did not trigger your newly added environment variable detection error message.

````


  The item was not found.

Call Stack (most recent call first):
  F:/Feature-test/vulkan/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  CMakeLists.txt:14 (find_package)


-- Could NOT find Vulkan (missing: Vulkan_LIBRARY) (found version "1.3.243")
CMake Debug Log at F:/Feature-test/vulkan/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  find_package considered the following paths for FindVulkan.cmake:

  The file was found at

    F:/Feature-test/vulkan/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindVulkan.cmake

  The module is considered not found due to Vulkan_FOUND being FALSE.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


CMake Error at CMakeLists.txt:20 (message):
  Unable to find Vulkan!


-- Configuring incomplete, errors occurred!
See also "F:/Feature-test/vulkan/vcpkg/buildtrees/vulkan/x86-windows-rel/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.
````

![image](https://user-images.githubusercontent.com/63675417/231978085-b40170a9-5638-4f6e-b8ba-94fe56a43b3c.png)

2023-04-14 20:40 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +endif()
@JonLiu1993 could you try the following:

```
cd /home/.../vcpkg/ports/vulkan
cmake -S . -B build
```

I want to isolate if the CMakeLists.txt is wrong, or there is some interaction with the portfile.cmake that is causing the issue.

2023-04-14 21:01 UTC, juan-lunarg commented on ports/vulkan/portfile.cmake
> +set(VCPKG_BUILD_TYPE release) # Stub only port
@dg0yt is this needed if `VCPKG_POLICY_EMPTY_PACKAGE` is enabled?

2023-04-17 15:15 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +endif()
Looks like it works fine. Does the portfile still not work for you?

2023-04-18 06:35 UTC, JonLiu1993 commented on ports/vulkan/CMakeLists.txt
> +endif()
@juan-lunarg, I tried again:

````
 CMake Error at F:/Feature-test/vulkan/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY) (found suitable version
  "1.3.243", minimum required is "1.1.82")
Call Stack (most recent call first):
  F:/Feature-test/vulkan/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  F:/Feature-test/vulkan/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindVulkan.cmake:597 (find_package_handle_standard_args)
  F:/Feature-test/vulkan/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  CMakeLists.txt:6 (find_package)
````

2023-04-18 17:13 UTC, juan-lunarg commented
Okay I believe the logic is sound now @JonLiu1993

2023-04-19 02:39 UTC, JonLiu1993 approved these changes, later dismissed

2023-04-19 02:46 UTC, JonLiu1993 commented
@juan-lunarg, Thanks for your contribution.
````
PS E:\vulkan> ./vcpkg install vulkan:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-windows-i386.zip->E:\vulkan\downloads\cmake-3.25.1-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
  * vcpkg-cmake[core]:x64-windows -> 2022-12-22
    vulkan[core]:x64-windows -> 1.1.82.1#6
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.8) Downloading portable powershell-core 7.2.8...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.8/PowerShell-7.2.8-win-x86.zip->E:\vulkan\downloads\PowerShell-7.2.8-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.8/PowerShell-7.2.8-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v21.7.0) Downloading portable 7zip 21.7.0...
Downloading 7zip...
https://www.7-zip.org/a/7z2107-extra.7z->E:\vulkan\downloads\7z2107-extra.7z
Downloading https://www.7-zip.org/a/7z2107-extra.7z
Extracting 7zip...
Restored 1 package(s) from C:\Users\test\AppData\Local\vcpkg\archives in 2.2 s. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 11.6 ms
Installing 2/2 vulkan:x64-windows...
Building vulkan[core]:x64-windows...
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Installing: E:/vulkan/packages/vulkan_x64-windows/share/vulkan/usage
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle vulkan:x64-windows: 2 s
Total install time: 22 s
Visual Studio users can reference the VULKAN_SDK environment variable

 

    Ex: Add $(VULKAN_SDK)/include to your include directories.

 

CMake provides built in support to find Vulkan:

 

    # https://cmake.org/cmake/help/latest/module/FindVulkan.html
    find_package(Vulkan REQUIRED)
    target_link_libraries(main PRIVATE Vulkan::Vulkan)
````

2023-04-19 03:35 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan REQUIRED) # https://cmake.org/cmake/help/latest/module/FindVulkan.html
REQUIRED still implies that error details are hidden in the logs, not printed to the console.
This is a step back. In particular, there will be no reminder to set  the VULKAN_SDK environment variable.

2023-04-19 03:35 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +endif()
vcpkg use at least CMake 3.25. Is there a reason to not delegate this to `find_package`?
Is there a reason to chose 1.1.82?

2023-04-19 03:39 UTC, BillyONeal commented on ports/vulkan/usage
> +    Ex: Add $(VULKAN_SDK)/include to your include directories.
I think the previous wording was much clearer than this rewrite. In particular you replaced concrete what to do instructions with an "example", and didn't even spell out the word example.

The CMake changes below are good though.

2023-04-19 18:27 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan REQUIRED) # https://cmake.org/cmake/help/latest/module/FindVulkan.html
No, it is a simple as writing/installing a file from the cmake project, and read/include that file from the portfile.

2023-04-19 18:36 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan REQUIRED) # https://cmake.org/cmake/help/latest/module/FindVulkan.html
Hmm. Gotcha, I guess I was overthinking it. If you send your PR I'll incorporate it into this PR then.

2023-04-19 18:37 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan REQUIRED) # https://cmake.org/cmake/help/latest/module/FindVulkan.html
Or feel free to edit this branch/PR with the idea.

2023-04-20 05:44 UTC, dg0yt commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan REQUIRED) # https://cmake.org/cmake/help/latest/module/FindVulkan.html
https://github.com/juan-lunarg/vcpkg/pull/1

2023-04-20 15:21 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +find_package(Vulkan REQUIRED) # https://cmake.org/cmake/help/latest/module/FindVulkan.html
I've merged in your changes @dg0yt 

Clean approach to the problem :+1:

2023-04-20 15:22 UTC, juan-lunarg commented on ports/vulkan/CMakeLists.txt
> +configure_file("vulkan-result.cmake.in" "${OUTFILE}" @ONLY ESCAPE_QUOTES)
Gotta say @dg0yt this is pretty clean/good use of configure_file :+1:

2023-04-20 15:49 UTC, juan-lunarg commented on ports/vulkan/usage
> +    Ex: Add $(VULKAN_SDK)/include to your include directories.
Updated again based on @dg0yt's PR. Please double check.

2023-04-21 02:44 UTC, JonLiu1993 approved these changes

2023-04-21 22:01 UTC, merged

2023-04-21 22:01 UTC, BillyONeal commented
Thanks for the fix!