add new port libre
microsoft/vcpkg pull request #30859
Opened 2023-04-14 12:40 UTC by alfredh

2023-04-14 12:43 UTC, alfredh commented
@microsoft-github-policy-service agree

2023-04-15 16:56 UTC, Thomas1664 commented
> [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)

This is not true: https://github.com/baresip/re/blob/0d6edc84d73b7e9f730854d630b47d7b194afbca/cmake/re-config.cmake

2023-04-16 09:41 UTC, alfredh commented
hi Thomas,

many thanks for your comment.

libre depends on OpenSSL and Libz. In practice we want to enable both for most builds.

Do you know how to add support for optional deps to e.g. libz ?

2023-04-16 13:32 UTC, Thomas1664 commented
The following links might be helpful:
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#when-defining-features-explicitly-control-dependencies
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/maintainers/functions/vcpkg_check_features.md
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/manifests.md#features

2023-04-19 10:19 UTC, alfredh commented
The page says "1 workflow awaiting approval" ...

Is there someone who can approve it ?

2023-04-19 12:21 UTC, Thomas1664 reviewed
You did not address my previous review comments. I'm not sure weither you understood/ read the links I posted in my previous comment. Therefore, I decided to give concrete suggestions.

2023-04-20 10:43 UTC, alfredh commented
thanks for the explanation Thomas

I updated the code as you suggested, so that it always builds with OpenSSL and zlib enabled.

Does it look better now ?

2023-04-20 17:45 UTC, alfredh commented
Thanks,

I added a change so that only static lib is built.


Do you mean this file for usage:

```
 /usr/local/lib/cmake/re/re-config.cmake
```


is there a convenience function that can be used instead of line 28 ?

2023-04-20 21:46 UTC, Thomas1664 commented
> Thanks,
> 
> I added a change so that only static lib is built.
> 
> Do you mean this file for usage:
> 
> ```
>  /usr/local/lib/cmake/re/re-config.cmake
> ```
> 
> is there a convenience function that can be used instead of line 28 ?

https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/maintainers/functions/vcpkg_cmake_config_fixup.md

Additionally, use if(BUILD_SHARED_LIBS) instead of disabling shared libraries entirely.

2023-04-21 09:35 UTC, alfredh commented
thanks again, I updated the code as suggested.

2023-04-21 10:03 UTC, LilyWangLL requested changes

2023-04-21 10:03 UTC, LilyWangLL commented on ports/libre/cmake.diff
> ++endif()
`static` and `shared` can't be installed at the same.
```
if(BUILD_SHARED_LIBS)
add_library(re-shared SHARED $<TARGET_OBJECTS:re-objs>)
target_link_libraries(re-shared PRIVATE ${LINKLIBS})
set_target_properties(re-shared PROPERTIES VERSION
  ${PROJECT_SOVERSION}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
set_target_properties(re-shared PROPERTIES SOVERSION ${PROJECT_SOVERSION})
set_target_properties(re-shared PROPERTIES OUTPUT_NAME "re")

else()
##############################################################################
#
# Static target libre.a
#

add_library(re STATIC $<TARGET_OBJECTS:re-objs>)
target_link_libraries(re PUBLIC ${LINKLIBS})
target_include_directories(re PUBLIC include)
set_target_properties(re PROPERTIES PUBLIC_HEADER "${HEADERS}")
endif()
```

2023-04-21 10:03 UTC, LilyWangLL commented on ports/libre/cmake.diff
> + install(TARGETS re-shared re
```suggestion
 install(TARGETS re-shared
```

2023-04-21 11:38 UTC, alfredh commented
many thanks for your review. I updated the code as suggested.

Both static and dynamic libs should be working now.

2023-04-23 10:03 UTC, LilyWangLL commented
@alfredh Thanks for your fast respond. I installed this port locally, I found it didn't install re.lib, just have re.dll, is this behavior is expected?

And the usage of libre test failed, could you please check it and fix again?
```
The package libre is compatible with built-in CMake targets:

    find_package(libre REQUIRED)
    target_link_libraries(main PRIVATE libre::libre)
```

2023-04-23 16:47 UTC, alfredh commented
for Windows, the static library re.lib should be used.

I updated the usage, could you please try again ?

2023-04-24 06:33 UTC, LilyWangLL commented
> for Windows, the static library re.lib should be used.

I noticed that this library also exports `re.dll,` but it was not installed in the `installed` directory of vcpkg. Is this the expected result? Just have `re-static.lib`.

> I updated the usage, could you please try again ?

I tested usage again on VS2022 CMakeProject, the configure succeed, but the header files cannot be found in the CMakeProject.

2023-04-24 06:33 UTC, LilyWangLL requested changes

2023-04-24 06:33 UTC, LilyWangLL commented on ports/libre/portfile.cmake
> +
```suggestion
```

2023-04-24 06:33 UTC, LilyWangLL commented on ports/libre/portfile.cmake
> +    REF v3.0.0
```suggestion
    REF "v${VERSION}"
```

2023-04-24 07:11 UTC, alfredh commented
the name of the library is changed in the re cmake file:

https://github.com/baresip/re/blob/main/CMakeLists.txt#L687


I tested again and the header files are installed here:

`packages/libre_arm64-osx/include/re`

2023-04-24 08:25 UTC, LilyWangLL commented
> the name of the library is changed in the re cmake file:
> 
> https://github.com/baresip/re/blob/main/CMakeLists.txt#L687

My meaning is that this port generates a dynamic `re.dll` and a static `re-static.lib` at the same, but 're.dll' was not installed in the `packages` directory, like below:
![image](https://user-images.githubusercontent.com/94091114/233940535-e69fdc49-cfc8-4577-bcb9-3522e78a142f.png)


Because of the following codes just install `LIBRARY:`
```
install(TARGETS re-shared re
  LIBRARY
    DESTINATION ${CMAKE_INSTALL_LIBDIR}
    COMPONENT Libraries
    NAMELINK_SKIP
  ARCHIVE
    DESTINATION ${CMAKE_INSTALL_LIBDIR}
    COMPONENT Development
  PUBLIC_HEADER
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/re
    COMPONENT Development
)

install(TARGETS re-shared
  LIBRARY
    DESTINATION ${CMAKE_INSTALL_LIBDIR}
    NAMELINK_ONLY
    COMPONENT Development
)
```

> for Windows, the static library re.lib should be used.

Since this port should use a static library on Windows, then on Windows, it should be `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`. 

And when to use a dynamic `re.dll`?

2023-04-24 08:31 UTC, LilyWangLL commented
> I tested again and the header files are installed here:
> 
> packages/libre_arm64-osx/include/re

The header files of `libre` installed correct, but this port missed property [target_include_directories(PORT_NAME PUBLIC "$<INSTALL_INTERFACE:include>")](https://cmake.org/cmake/help/latest/command/target_include_directories.html), it use its own `re-config.cmake`.
```
install(FILES cmake/re-config.cmake
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/re
  COMPONENT Development
)
```

2023-04-24 12:32 UTC, alfredh commented
hi, many thanks for your comments

I have added the ONLY_STATIC_LIBRARY flag.

For windows it only makes sense to install the static library (re.lib).
It does not make sense to install the DLL library.

regarding missing include files, I will have a look and see if I can figure out what is wrong.

2023-04-28 10:59 UTC, alfredh commented
Given that this port will only build a static library, should we remove the dynamic part of the cmake patch?

Regarding the missing include files, I think I need some help to figure out why it is not working.

2023-04-28 11:10 UTC, dg0yt commented
Why is it only static? Is it just about Windows DLL exports?

2023-04-29 11:42 UTC, alfredh commented
> Why is it only static? Is it just about Windows DLL exports?

The library can be compiled static or shared.

For practical reasons shared is only useful on certain platforms:

* Windows: Static
* Android: Static
* iOS: Static
* macOS: Static or dynamic
* Linux: Static or dynamic

do you prefer that both static and shared options are available ?

2023-04-29 13:58 UTC, dg0yt commented
> practical reasons

This doesn't really answer *why*.

> do you prefer that both static and shared options are available ?

Vcpkg wants the packages to follow the triplet setting. (And once the user has made his triplet choice, it is convenient if package and target names are uniform regardless of linkage.)

Typical problems for not being able to offer a choice (at least for some platforms):
- Lack the dllexport information, so only static linkage on windows.
- Dynamic plugin architecture, so only dynamic linkage.
- Lack of sufficient transitive linking information, so only dynamic linkage (in particular for non-MSVC where static link libs have to be in the right order).

2023-04-30 07:59 UTC, alfredh commented
hi, many thanks for your comment.

Could you please have a look again ?

We have updated the CMake files with `BUILD_SHARED_LIBS`
so that it either builds Static or Shared library.

2023-05-01 13:42 UTC, dg0yt commented on ports/libre/usage
> +    target_link_libraries(main PRIVATE re)
This message is copying existing patterns in vcpkg, but the package isn't using any working pattern. 
This seems to be a more general problem with the package, not specific to vcpkg. It might help to have a minimal standalone example, for manual tests and for (libre) CI.

- There is no such CMake package. There is neiter a Find module, nor would `find_package(re)` consider `share/libre/re-config.cmake`).
- There are no "built-in" CMake targets. (This would refer to a Find module coming with CMake.)
- Actually there are no CMake targets at all. `re-config.cmake` doesn't create any.
- The only line which make some sense to me is:
  ~~~cmake
      target_link_libraries(main PRIVATE re)
  ~~~
  This transform into a linker namespec, i.e. something which is passed literally to the linker as `-lre`, and resolution is left to the linker.
- Without `re` being a target, there is no information about the required include directories.
- FTR imported CMake targets should use a namespace. (So CMake can recognize that it is a target, and report at configuration time if it doesn't have information for the linker.)

Actually `re-config.cmake`  seems to be more related to build time dependencies of libre than to to downstream build time dependencies for using libre.

How to proceed?
- For single-config dynamic linkage, we would get away with this usage.
  ~~~cmake
  find_path(RE_INCLUDE_DIR NAMES ...)
  find_libary(RE_LIBRARY NAMES ...)
  target_include_directores(main PRIVATE "${RE_INCLUDE_DIR}")
  target_include_directores(main PRIVATE "${RE_LIBRARY}")
  ~~~
- For multiconfig-generators, this would need to be extended to select the right libary.
- For static linkage, this would need to be extended to pass the right link libraries for OpenSSL and ZLIB.
- The ultimate solution is properly exporting CMake config from the build.
- libre also install pkg-config which might be used in CMake. Unfortunately it is also based on assumptions about static link library names which don't always work (eg. libre.pc: `-lz`, vcpkg windows: `zlib.lib` or `libzlib.dll.a`).

Please correct me if I missed some pieces in what the package installs.

2023-05-02 07:27 UTC, alfredh commented
many thanks for your comments,

I will follow up with a proper CMake config and namespace.

2023-05-04 11:13 UTC, alfredh commented on ports/libre/usage
> +    target_link_libraries(main PRIVATE re)
hi @dg0yt 

We are trying to fix the problems as you mentioned, here is a PR for the work:

https://github.com/baresip/re/pull/786


Can you please check if the namespace part is what we want ?

The include files are not listed in the `owns` command, not sure why that is...

2023-05-13 12:10 UTC, closed without merging