[MakeID] Add new port
microsoft/vcpkg pull request #30902
Opened 2023-04-16 09:37 UTC by Pospelove

2023-04-17 06:18 UTC, Adela0814 requested changes

2023-04-17 06:18 UTC, Adela0814 commented on ports/makeid/portfile.cmake
> +file(COPY ${ARCHIVE} DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```suggestion
file(COPY ${ARCHIVE} DESTINATION "${CURRENT_PACKAGES_DIR}/include")
```

2023-04-17 06:18 UTC, Adela0814 commented on ports/makeid/portfile.cmake
> +file(WRITE ${CURRENT_PACKAGES_DIR}/share/makeid/copyright "${license_text}")
```suggestion
file(WRITE "${CURRENT_PACKAGES_DIR}/share/makeid/copyright" "${license_text}")
```

2023-04-17 06:29 UTC, Adela0814 approved these changes, later dismissed

2023-04-17 06:32 UTC, dg0yt commented on ports/makeid/portfile.cmake
> +    FILENAME "MakeID.h"
There can't be different versions (and SHA512) with the same name.
Can we use `FILENNAME "MakeID.h-${VERSION}"` here (and in the copy command below)?

2023-04-17 23:51 UTC, BillyONeal commented
I'm a bit concerned over 'makeid' since that seems likely to be a conflicting name but I can't find any actual conflicts so I guess this works.

If you know how to contract upstream it would be good to ask them to make versioned download locations.

2023-04-17 23:51 UTC, merged

2023-04-18 04:16 UTC, dg0yt commented
> I'm a bit concerned over 'makeid' since that seems likely to be a conflicting name.

In that case we should quickly move it to a subdir...

2023-04-18 04:42 UTC, BillyONeal commented
> > I'm a bit concerned over 'makeid' since that seems likely to be a conflicting name.
> 
> In that case we should quickly move it to a subdir...

I didn't find any actual conflicts so I don't think it needs a subdir. Unless we see actual conflicts.