[many ports] Include functional to fix error C2039 and C2504
microsoft/vcpkg pull request #30946
Opened 2023-04-18 08:10 UTC by LilyWangLL

In an internal version of Visual Studio, many ports install failed with following error:
```
error C2039: 'binary_function': is not a member of 'std'
error C2504: 'binary_function': base class undefined
error C2143: syntax error: missing ',' before '<'
```
Or
```
error C2039: 'unary_function': is not a member of 'std'
error C2504: 'unary_function': base class undefined
error C2143: syntax error: missing ',' before '<'
```
The reason is new STL change, need include `<functional>` to fix them.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-04-18 08:13 UTC, Neumann-A commented on ports/kenlm/portfile.cmake
> +        Include_functional.patch
hmm vcpkg should have a rule to consistently name patches all lowercase.

2023-04-18 08:13 UTC, Neumann-A commented on ports/kenlm/vcpkg.json
> +      "supports": "!windows",
Why is that ?

2023-04-18 08:15 UTC, Neumann-A commented on ports/moos-core/vcpkg.json
>    "license": null,
GPL-2-or-later ?

2023-04-18 08:17 UTC, Neumann-A commented
```
error C2039: 'binary_function': is not a member of 'std'
error C2039: 'unary_function': is not a member of 'std'
```

maybe patch the use of these functions out since they have been deprecated since c++11 and are removed in 17 (Maybe there is an update upstream which already does this?)

2023-04-18 08:23 UTC, LilyWangLL commented on ports/kenlm/vcpkg.json
> +      "supports": "!windows",
Instead of the following codes in `portfile.cmake`.
```
if ("interpolate" IN_LIST FEATURES AND VCPKG_TARGET_IS_WINDOWS)
    message(FATAL_ERROR "The interpolate feature does not support Windows.")
endif()
```

2023-04-19 12:28 UTC, Thomas1664 commented on ports/libsbml/portfile.cmake
> +endif()
Do we need a usage file for this?

2023-04-20 03:11 UTC, LilyWangLL commented on ports/libsbml/portfile.cmake
> +endif()
I am fixing its usage.

2023-04-20 10:20 UTC, Thomas1664 commented on ports/libsbml/fix-cmake.patch
> ++  ${CMAKE_CURRENT_BINARY_DIR}/${LIBSBML_LIBRARY}-config-version.cmake
@Neumann-A are we allowed to rename upstream targets?

2023-04-21 21:56 UTC, BillyONeal commented
>maybe patch the use of these functions out since they have been deprecated since c++11 and are removed in 17 (Maybe there is an update upstream which already does this?)

I think that crosses into 'upstream needs to be in the loop' territory where just add standard library header can be considered 'fairly mindless'.

2023-04-21 21:59 UTC, BillyONeal requested changes

2023-04-21 21:59 UTC, BillyONeal commented on ports/libsbml/fix-cmake.patch
> +diff --git a/CMakeModules/FindLIBXML.cmake b/CMakeModules/FindLIBXML.cmake
This change does not appear to be adding `<functional>`; did you intend this to be in a different PR instead? If you did intend it here, can you describe the problem you are trying to fix?

2023-04-23 01:56 UTC, LilyWangLL commented on ports/libsbml/fix-cmake.patch
> +diff --git a/CMakeModules/FindLIBXML.cmake b/CMakeModules/FindLIBXML.cmake
The latest version of  `libsbml` has removed `unary_function`, so I don't need add `<functional>`, just update it.

2023-04-23 01:56 UTC, LilyWangLL commented on ports/libsbml/fix-cmake.patch
> +diff --git a/CMakeModules/FindLIBXML.cmake b/CMakeModules/FindLIBXML.cmake
This patch is fixing some build errors.

2023-04-26 07:08 UTC, BillyONeal commented on ports/libsbml/fix-cmake.patch
> +diff --git a/CMakeModules/FindLIBXML.cmake b/CMakeModules/FindLIBXML.cmake
I see, OK, let me double check with folks that Thomas1664's comment below about renaming targets is OK, and if it is, this looks good to me.

2023-04-26 07:08 UTC, BillyONeal commented
Tagging vcpkg-team-review for the 'rename upstream targets' question.

2023-04-27 00:34 UTC, BillyONeal requested changes
I think @dg0yt has pointed out a legitimate problem with the edits to libsbml. It might be a good idea to separate that into its own PR since it is very much not "include functional" like the other changes here.

Thanks!

2023-04-27 02:30 UTC, LilyWangLL commented
> I think @dg0yt has pointed out a legitimate problem with the edits to libsbml. It might be a good idea to separate that into its own PR since it is very much not "include functional" like the other changes here.
> 
> Thanks!

Done. I reverted the changes of `libsbml`, I will submit a new PR to update `libsbml`.

2023-04-27 04:05 UTC, BillyONeal approved these changes
Thanks for the fixes!

2023-04-27 04:05 UTC, merged