[glaze] new port
microsoft/vcpkg pull request #30966
Opened 2023-04-19 10:56 UTC by omarhogni

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-04-19 11:01 UTC, omarhogni commented
@microsoft-github-policy-service agree company="Skaginn 3X ehf."

2023-04-20 02:43 UTC, FrankXie05 requested changes

2023-04-20 02:43 UTC, FrankXie05 commented on ports/glaze/portfile.cmake
> +    REF v1.2.0
```suggestion
    REF "v{VERSION}"
```

2023-04-20 02:43 UTC, FrankXie05 commented on ports/glaze/vcpkg.json
> +  "version": "1.2.0",
```suggestion
  "version": "1.2.1",
```
https://github.com/stephenberry/glaze/releases/tag/v1.2.1

2023-04-20 10:10 UTC, FrankXie05 requested changes

2023-04-20 10:10 UTC, FrankXie05 commented on ports/glaze/disable-dev-mode.patch
> ++	#include(cmake/dev-mode.cmake)
Is there any official reason to disable it `dev-mode.cmake`? 
Otherwise just disable the `BUILD_TESTING`. 
https://github.com/stephenberry/glaze/blob/d16808a6f97af78a4ceaaa2edd8e8f126982e689/cmake/dev-mode.cmake#L6

2023-04-24 11:41 UTC, omarhogni commented
Upstream project requires at least gcc 10 the azure pipelines are built using gcc 9.

```
/mnt/vcpkg-ci/buildtrees/glaze/src/v1.2.1-af0f635c8a.clean/include/glaze/binary/header.hpp:7:10: fatal error: concepts: No such file or directory
    7 | #include <concepts>
      |          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

What is usually done in this situation?

2023-04-25 02:19 UTC, FrankXie05 commented
We can wait to merge until a VM update allows us to test this.

Otherwise, we can only temporarily disable the relevant functions as we cannot test it. Sorry for that. 😔

Track: https://github.com/microsoft/azure-pipelines-agent/issues/3834

2023-04-25 03:05 UTC, dg0yt commented
No need to wait.

> What is usually done in this situation?

- Tell port users:
  Add a message to the portfile that gcc must be at least \<version>.
- Tell vcpkg CI:
  Insert `glaze:x64-linux=fail` to `scripts/ci.baseline.txt`

Example: port coroutine.

2023-04-27 09:03 UTC, FrankXie05 approved these changes

2023-04-27 22:25 UTC, merged

2023-04-27 22:25 UTC, BillyONeal commented
Thanks for the new port!