[boringssl] Update to 2023-04-20
microsoft/vcpkg pull request #30986
Opened 2023-04-20 10:30 UTC by BurningEnlightenment

Update BoringSSL to the current master commit.

BoringSSL gained a proper install target with an exported config last year. The exported config is highly compatible with the CMake built-in `FindOpenSSL.cmake` module which is why I added usage information without specifying `MODULE/CONFIG`.

The `go` runtime update is required by the BoringSSL buildsystem.

Lastly I removed the `tools` feature due to the fact that the BoringSSL buildsystem doesn't offer a corresponding configuration option and always installs `bssl` (which by the way is not referenced by the CMake configs).

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-04-21 00:20 UTC, BillyONeal commented
Note that ci does not test boringssl.

`vcpkg install boringssl:x64-windows` fails with:

```
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=crypto\CMakeFiles\crypto_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe  CMakeFiles\crypto_test_data.dir\crypto_test_data.cc.obj crypto\CMakeFiles\crypto_test.dir\abi_self_test.cc.obj crypto\CMakeFiles\crypto_test.dir\asn1\asn1_test.cc.obj crypto\CMakeFiles\crypto_test.dir\base64\base64_test.cc.obj crypto\CMakeFiles\crypto_test.dir\bio\bio_test.cc.obj crypto\CMakeFiles\crypto_test.dir\blake2\blake2_test.cc.obj crypto\CMakeFiles\crypto_test.dir\buf\buf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\bytestring\bytestring_test.cc.obj crypto\CMakeFiles\crypto_test.dir\chacha\chacha_test.cc.obj crypto\CMakeFiles\crypto_test.dir\cipher_extra\aead_test.cc.obj crypto\CMakeFiles\crypto_test.dir\cipher_extra\cipher_test.cc.obj crypto\CMakeFiles\crypto_test.dir\compiler_test.cc.obj crypto\CMakeFiles\crypto_test.dir\conf\conf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\constant_time_test.cc.obj crypto\CMakeFiles\crypto_test.dir\cpu_arm_linux_test.cc.obj crypto\CMakeFiles\crypto_test.dir\crypto_test.cc.obj crypto\CMakeFiles\crypto_test.dir\curve25519\ed25519_test.cc.obj crypto\CMakeFiles\crypto_test.dir\curve25519\spake25519_test.cc.obj crypto\CMakeFiles\crypto_test.dir\curve25519\x25519_test.cc.obj crypto\CMakeFiles\crypto_test.dir\ecdh_extra\ecdh_test.cc.obj crypto\CMakeFiles\crypto_test.dir\dh_extra\dh_test.cc.obj crypto\CMakeFiles\crypto_test.dir\digest_extra\digest_test.cc.obj crypto\CMakeFiles\crypto_test.dir\dsa\dsa_test.cc.obj crypto\CMakeFiles\crypto_test.dir\err\err_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\evp_extra_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\evp_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\pbkdf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\scrypt_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\aes\aes_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\bn\bn_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\cmac\cmac_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\ec\ec_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\ec\p256-nistz_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\ecdsa\ecdsa_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\hkdf\hkdf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\md5\md5_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\modes\gcm_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\rand\ctrdrbg_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\rand\fork_detect_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\service_indicator\service_indicator_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\sha\sha_test.cc.obj crypto\CMakeFiles\crypto_test.dir\hpke\hpke_test.cc.obj crypto\CMakeFiles\crypto_test.dir\hmac_extra\hmac_test.cc.obj crypto\CMakeFiles\crypto_test.dir\hrss\hrss_test.cc.obj crypto\CMakeFiles\crypto_test.dir\impl_dispatch_test.cc.obj crypto\CMakeFiles\crypto_test.dir\kyber\kyber_test.cc.obj crypto\CMakeFiles\crypto_test.dir\lhash\lhash_test.cc.obj crypto\CMakeFiles\crypto_test.dir\obj\obj_test.cc.obj crypto\CMakeFiles\crypto_test.dir\pem\pem_test.cc.obj crypto\CMakeFiles\crypto_test.dir\pkcs7\pkcs7_test.cc.obj crypto\CMakeFiles\crypto_test.dir\pkcs8\pkcs8_test.cc.obj crypto\CMakeFiles\crypto_test.dir\pkcs8\pkcs12_test.cc.obj crypto\CMakeFiles\crypto_test.dir\poly1305\poly1305_test.cc.obj crypto\CMakeFiles\crypto_test.dir\pool\pool_test.cc.obj crypto\CMakeFiles\crypto_test.dir\rand_extra\rand_test.cc.obj crypto\CMakeFiles\crypto_test.dir\refcount_test.cc.obj crypto\CMakeFiles\crypto_test.dir\rsa_extra\rsa_test.cc.obj crypto\CMakeFiles\crypto_test.dir\self_test.cc.obj crypto\CMakeFiles\crypto_test.dir\stack\stack_test.cc.obj crypto\CMakeFiles\crypto_test.dir\siphash\siphash_test.cc.obj crypto\CMakeFiles\crypto_test.dir\test\file_test_gtest.cc.obj crypto\CMakeFiles\crypto_test.dir\thread_test.cc.obj crypto\CMakeFiles\crypto_test.dir\trust_token\trust_token_test.cc.obj crypto\CMakeFiles\crypto_test.dir\x509\x509_test.cc.obj crypto\CMakeFiles\crypto_test.dir\x509\x509_time_test.cc.obj crypto\CMakeFiles\crypto_test.dir\x509v3\tab_test.cc.obj  /out:crypto\crypto_test.exe /implib:crypto\crypto_test.lib /pdb:crypto\crypto_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  crypto\test\test_support_libd.lib  crypto\test\boringssl_gtest_maind.lib  crypto\test\test_support_libd.lib  dbghelp.lib  crypto\cryptod.lib  ws2_32.lib  boringssl_gtestd.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe CMakeFiles\crypto_test_data.dir\crypto_test_data.cc.obj crypto\CMakeFiles\crypto_test.dir\abi_self_test.cc.obj crypto\CMakeFiles\crypto_test.dir\asn1\asn1_test.cc.obj crypto\CMakeFiles\crypto_test.dir\base64\base64_test.cc.obj crypto\CMakeFiles\crypto_test.dir\bio\bio_test.cc.obj crypto\CMakeFiles\crypto_test.dir\blake2\blake2_test.cc.obj crypto\CMakeFiles\crypto_test.dir\buf\buf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\bytestring\bytestring_test.cc.obj crypto\CMakeFiles\crypto_test.dir\chacha\chacha_test.cc.obj crypto\CMakeFiles\crypto_test.dir\cipher_extra\aead_test.cc.obj crypto\CMakeFiles\crypto_test.dir\cipher_extra\cipher_test.cc.obj crypto\CMakeFiles\crypto_test.dir\compiler_test.cc.obj crypto\CMakeFiles\crypto_test.dir\conf\conf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\constant_time_test.cc.obj crypto\CMakeFiles\crypto_test.dir\cpu_arm_linux_test.cc.obj crypto\CMakeFiles\crypto_test.dir\crypto_test.cc.obj crypto\CMakeFiles\crypto_test.dir\curve25519\ed25519_test.cc.obj crypto\CMakeFiles\crypto_test.dir\curve25519\spake25519_test.cc.obj crypto\CMakeFiles\crypto_test.dir\curve25519\x25519_test.cc.obj crypto\CMakeFiles\crypto_test.dir\ecdh_extra\ecdh_test.cc.obj crypto\CMakeFiles\crypto_test.dir\dh_extra\dh_test.cc.obj crypto\CMakeFiles\crypto_test.dir\digest_extra\digest_test.cc.obj crypto\CMakeFiles\crypto_test.dir\dsa\dsa_test.cc.obj crypto\CMakeFiles\crypto_test.dir\err\err_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\evp_extra_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\evp_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\pbkdf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\evp\scrypt_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\aes\aes_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\bn\bn_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\cmac\cmac_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\ec\ec_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\ec\p256-nistz_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\ecdsa\ecdsa_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\hkdf\hkdf_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\md5\md5_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\modes\gcm_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\rand\ctrdrbg_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\rand\fork_detect_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\service_indicator\service_indicator_test.cc.obj crypto\CMakeFiles\crypto_test.dir\fipsmodule\sha\sha_test.cc.obj crypto\CMakeFiles\crypto_test.dir\hpke\hpke_test.cc.obj crypto\CMakeFiles\crypto_test.dir\hmac_extra\hmac_test.cc.obj crypto\CMakeFiles\crypto_test.dir\hrss\hrss_test.cc.obj crypto\CMakeFiles\crypto_test.dir\impl_dispatch_test.cc.obj crypto\CMakeFiles\crypto_test.dir\kyber\kyber_test.cc.obj crypto\CMakeFiles\crypto_test.dir\lhash\lhash_test.cc.obj crypto\CMakeFiles\crypto_test.dir\obj\obj_test.cc.obj crypto\CMakeFiles\crypto_test.d [...]

2023-04-21 07:45 UTC, BurningEnlightenment commented
The test target thinks that it exports this variable due to `BORINGSSL_IMPLEMENTATION` being defined. Ugh, that's what you get for using `add_definitions()` in the project directory instead of `target_compile_definitions`. This buildsystem is such a goddamn mess (I know, I know, OpenSSL has it much worse).

2023-04-21 09:11 UTC, BurningEnlightenment commented
I've successfully installed the `grpc` port with `boringssl` on:
- [x] `x64-windows`
- [x] `x64-windows-static`
- [x] `x64-linux` (`Ubuntu-22.04`)

2023-04-21 09:14 UTC, FrankXie05 requested changes

2023-04-21 09:18 UTC, BurningEnlightenment commented on ports/boringssl/usage
> +    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
> it may be better to use message if possible.

What do you mean?

> I am worried that it will mislead users about `openssl`

Well, it is a drop-in replacement. There is no way to make something like `find_package(BoringSSL ...` work.

2023-04-21 09:23 UTC, FrankXie05 commented on ports/boringssl/usage
> +    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
I mean:
If you install `BoringSSL` without knowing it, but the usage of `openssl` is given.

2023-04-21 22:38 UTC, BillyONeal requested changes

2023-04-21 22:38 UTC, BillyONeal commented on scripts/cmake/vcpkg_find_acquire_program(GO).cmake
> +set(tool_subdirectory 1.20.3.windows-386)
We should add `vcpkg-tool-go` instead so that it can participate in versioning rather than being updated underneath people.

2023-04-21 22:38 UTC, BillyONeal commented on ports/boringssl/usage
> +    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
@FrankXie05 , boringssl is a fork of openssl and is intended to be a drop in replacement. Therefore folks who are looking for openssl should get boringssl when that is used. When used with vcpkg it does mean that folks need an overlay port that makes openssl empty and simply depends on boringssl.

Note that we would not add a library like boringssl today now that we have registries.

2023-04-22 09:27 UTC, BurningEnlightenment commented
I added the `vcpkg-tool-go` port (inspired by `vcpkg-tool-nodejs`). Should I revert the `vcpkg_find_acquire_program(GO).cmake` changes? Currently there is no other official portfile containing `vcpkg_find_acquire_program(GO`. Does that function need a deprecation marker? If that is the case I'd need some guidance on how to deprecate it.

Btw. IMO it doesn't make much sense that binary caching is enabled for `vcpkg-tool-go` as recompressing the ~100MiB archive takes a considerable amount of time and disk space.

2023-04-24 12:16 UTC, BurningEnlightenment commented on ports/boringssl/usage
> +    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
Is there anything actionable left or can this be marked as resolved?

2023-04-25 02:31 UTC, FrankXie05 submitted a review, later dismissed

2023-04-25 02:31 UTC, FrankXie05 commented on ports/boringssl/usage
> +    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
> Is there anything actionable left or can this be marked as resolved?

Done.

2023-04-27 05:52 UTC, BurningEnlightenment commented
@BillyONeal I need some feedback on how to proceed.

2023-05-01 19:10 UTC, BillyONeal commented
> @BillyONeal I need some feedback on how to proceed.

I'm working on a spec for how we want this going forward, should have something for you in a few days.

2023-05-09 03:05 UTC, FrankXie05 commented
Until we get a better workaround, I'm turning this PR into draft status for now. :)

2023-05-09 10:06 UTC, BurningEnlightenment commented
@BillyONeal would it be acceptable if I split the find module compatibility changes (13cd1dcfc186d61a8c070e335e6fdfc5406e7035) into a seperate PR which can be merged independently of the boringssl/go version update?

2023-05-19 05:52 UTC, BurningEnlightenment commented
@BillyONeal any news on the spec?

@FrankXie05 I rebased onto master including #31387 => this no longer depends on a different PR

2023-05-22 01:49 UTC, FrankXie05 requested changes

2023-05-22 01:49 UTC, FrankXie05 commented on ports/vcpkg-tool-go/portfile.cmake
> +set(PROGRAM_NAME "go")
We have `go`, why do we need to add new ports manually? 
https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program(GO).cmake

2023-05-22 01:51 UTC, FrankXie05 commented on ports/vcpkg-tool-go/portfile.cmake
> +set(PROGRAM_NAME "go")
>The go runtime update is required by the BoringSSL buildsystem.

we can update the script.

2023-05-22 01:54 UTC, FrankXie05 commented
> I added the `vcpkg-tool-go` port (inspired by `vcpkg-tool-nodejs`). Should I revert the `vcpkg_find_acquire_program(GO).cmake` changes? Currently there is no other official portfile containing `vcpkg_find_acquire_program(GO`. Does that function need a deprecation marker? If that is the case I'd need some guidance on how to deprecate it.
> 
> Btw. IMO it doesn't make much sense that binary caching is enabled for `vcpkg-tool-go` as recompressing the ~100MiB archive takes a considerable amount of time and disk space.

We just separated it out, in order to reduce the pressure of maintaining `vcpkg_find_acquire_program`. We need to use it.

2023-05-22 03:06 UTC, dg0yt commented
> > Btw. IMO it doesn't make much sense that binary caching is enabled for `vcpkg-tool-go` as recompressing the ~100MiB archive takes a considerable amount of time and disk space.
> 
> We just separated it out, in order to reduce the pressure of maintaining `vcpkg_find_acquire_program`. We need to use it.

This is only loosely related. Instead of installing and creating a real binary artifact, it is possible to provide an individual script function to acquire the tool when needed. The download would still go through asset caching.
It is now possible to add or change tools in `vcpkg_find_acquire_program` without rebuilding the world. The problem of `vcpkg_find_acquire_program` is the lack of versioning.

2023-05-22 07:37 UTC, FrankXie05 approved these changes

2023-07-10 22:19 UTC, BillyONeal commented
Dropping info:reviewed as this is still pending the tools PR.

2023-09-26 08:41 UTC, BurningEnlightenment commented
I factored the port update into a separate PR and will leave this untouched as it can serve as an implementation reference for a future `vcpkg-tool-go` port.

2023-09-26 08:41 UTC, closed without merging