[libsystemd] add new port
microsoft/vcpkg pull request #31150
Opened 2023-04-27 12:10 UTC by jbbjarnason

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-04-27 17:43 UTC, dg0yt requested changes
I think it wasn't easy to get so far. Please bear with me if my comments ask for more work. It is opinon, not an official request.

2023-04-27 17:43 UTC, dg0yt commented on ports/libcap/cross-compile.patch
> ++#OBJCOPY := $(CROSS_COMPILE)objcopy
You could pass these variables as `OPTIONS` to `vcpkg_build_make`. This should override the local definitions.

(You already do this for `CC`...)

2023-04-27 17:43 UTC, dg0yt commented on ports/libsystemd/Config.cmake.in
> +    message(WARNING "DID not FiND SYSTEMD")
This warning should be removed. In Config mode, CMake will continue searching config in other locations.

2023-04-27 17:43 UTC, dg0yt commented on ports/libsystemd/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/Config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/unofficial-systemd/unofficial-systemd-config.cmake" @ONLY)
IMO this CMake config should be removed. There is an official pc file, and the CMake config would need to rely on pkg-config for some dependencies.

2023-04-27 18:23 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +    configure.patch
This would require some work, I can maybe try to add it later

2023-04-27 18:23 UTC, jbbjarnason commented on ports/libsystemd/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/Config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/unofficial-systemd/unofficial-systemd-config.cmake" @ONLY)
In my experience, the systemd pkgconfig file is not enough they do not declare requirements since they manually make the pkgconfig file instead of utilizing the meson generator.
https://github.com/systemd/systemd/blob/main/src/libsystemd/libsystemd.pc.in

2023-04-29 20:22 UTC, jbbjarnason commented on ports/libcap/cross-compile.patch
> ++#OBJCOPY := $(CROSS_COMPILE)objcopy
I would vote against it, I don't want to be forced to use gcc in any case and this strictly uses gcc as the compiler. When vcpkg dependencies are built with clang, I don't want one dependency building with gcc & libstdc++ because libc++ and libstdc++ are not 100% ABI compatible.
Please let me know if I am wrong in any case.

2023-05-04 10:02 UTC, Adela0814 requested changes

2023-05-04 10:02 UTC, Adela0814 commented on ports/libcap/portfile.cmake
> +  file(INSTALL ${BUILD_DIR_RELEASE}/libcap/libcap.a DESTINATION ${CURRENT_PACKAGES_DIR}/lib )
Please remove extra spaces.

2023-05-04 10:04 UTC, jbbjarnason commented on ports/libcap/configure.patch
> +--
this patch has a new file because of this issue https://github.com/microsoft/vcpkg/issues/14389

2023-05-04 10:06 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +)
I am not sure I fully understand, could you elaborate further?

2023-05-05 08:03 UTC, Adela0814 requested changes

2023-05-05 08:03 UTC, Adela0814 commented on ports/libcap/configure.patch
> +--
Can this be removed?

2023-05-05 08:08 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-05-05 10:22 UTC, jbbjarnason commented on ports/libcap/configure.patch
> +--
No but this can be done differently, https://github.com/microsoft/vcpkg/pull/31150#discussion_r1179492380

2023-05-12 09:33 UTC, jbbjarnason reviewed
Address review comments

2023-05-12 09:33 UTC, jbbjarnason commented on ports/libsystemd/Config.cmake.in
> +
removed

2023-05-12 09:33 UTC, jbbjarnason commented on ports/libcap/cross-compile.patch
> ++#OBJCOPY := $(CROSS_COMPILE)objcopy
nvm this can be set as option, done

2023-05-12 09:33 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +    configure.patch
I have changed it from being a patch to an empty configure script. However I have not made it as a general configure script since it is empty and therefore would instead like to do the required things in CMake.

2023-05-12 09:33 UTC, jbbjarnason commented on ports/libcap/configure.patch
> +--
removed patch and now as empty configure script file

2023-05-15 03:14 UTC, Adela0814 approved these changes, later dismissed

2023-05-15 03:27 UTC, dg0yt requested changes
The host stuff must be done in the host triplet.
(Example: infoware pci_data.hpp in https://github.com/microsoft/vcpkg/pull/31388)

Multiple calls to vcpkg_*_make overwrite logfiles.

Are the pc files valid now?

2023-05-15 03:27 UTC, dg0yt commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
No, this cannot be approved!

2023-05-15 08:10 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
Can you elaborate further on this topic please?

2023-05-15 08:27 UTC, jbbjarnason commented
@dg0yt Thank you for the review!

> The host stuff must be done in the host triplet.
(Example: infoware pci_data.hpp in https://github.com/microsoft/vcpkg/pull/31388)

I am guessing you are referring to `libcap` to generate cap_names.h, right? And if so the reason for overriding the compiler is because the `libcap` Makefiles are not made for cross compiling and utilize the host to run generated artifact to make the `cap_names.h`. The generated artifact is not used to build the libcap library only the header, in my understanding. This is one way to bypass this problem, I am not sure, is it possible to declare host triplet in ports directory?

> Multiple calls to vcpkg_*_make overwrite logfiles.

Should I specify `LOGFILE_ROOT` to each call?

> Are the pc files valid now?

If you are referring to the systemd pkgconfig files, than no. The pkgconfig files are straight from systemd as I don't wan't to change the implementation of systemd without going to upstream with it. As a result I made the cmake configuration file which is an addon, therefore, not changing the behavior in any way.

2023-05-18 02:40 UTC, Adela0814 commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
@dg0yt Could you please explain?

2023-05-23 10:01 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
@Adela0814 or @dg0yt is there any progress with this?

2023-05-23 21:01 UTC, dg0yt commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
I don't know where to start with explanation again, and why the reviewers can't do it.

Host stuff must be done in the host triplet. The artifact become readily available for the cross build context by using host dependencies. This done in infoware, gmp, nettle, luajit, ..., What shouldn't be assumed to be readily available, even for a linux-only port, is `gcc`.

The problem with libcap is that it needs a number of makefile variables properly passed in. It is not an easy port to start with.

2023-05-24 07:21 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
@dg0yt Okay, I am still unsure what a host triplet is!. Reason for hard coding `gcc` as compiler is because it is the default compiler for Linux, as you are already aware of I reckon.

As I would like this to finish, I see 3 options for next steps:

1. Iterative development, this currently works, let's fix it when it becomes a problem.
2. @Adela0814 helps with the review and me to make host triplet changes.
3. @dg0yt would you be willing to help by contributing directly to this pull request? I can give you access privileges to my fork. 

Which option do you guys prefer?

2023-05-24 07:52 UTC, Adela0814 commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
I have tested the usage of `libcap` on my Linux machine and it works well. I think this PR can be approved.
![image](https://github.com/microsoft/vcpkg/assets/95600143/d0e99bca-d725-4f03-ac75-7ea89bcff3c7)

2023-05-25 18:28 UTC, dg0yt commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
> 1\. Iterative development, this currently works, let's fix it when it becomes a problem.

Not acceptable IMO. It is known to not be implemented correctly. It may become a problem for another contributor who wants to update lzma, lz4, meson...

> 2\. @Adela0814 helps with the review and me to make host triplet changes.

This is how I understand the roles.

> 3\. @dg0yt would you be willing to help by contributing directly to this pull request? I can give you access privileges to my fork.

I already considered that option. I would be willing but I don't think I can spend time on it soon.

2023-05-30 03:08 UTC, Adela0814 commented on ports/libcap/portfile.cmake
> +    CC=gcc # use host architecture to generate cap_names.h
I will be converting your PR to draft status. When this PR is ready for review, please reactivate it.

2023-06-16 09:25 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +  message(FATAL_ERROR "Unable to find gcc or clang host compiler")
Thank you @dan-shaw for the example, and suggestion. I was now able to understand what needed to be changed. I have applied your suggestion.

2023-06-19 16:22 UTC, dg0yt commented
This PR should immediately have the  https://github.com/microsoft/vcpkg/labels/info%3Areviewed removed until it is reviewed again. Basically we don't know if it is ready to review because it wasn't reset to draft state after @dan-shaw's comment.
 AFAIU the host triplet part is still incomplete, and my comment about installing the official exported config is still valid. (There would be more comments with regard to the code, but it is more stylistic, not fundamental.)

2023-06-30 09:25 UTC, jbbjarnason commented
> This PR should immediately have the [ info:reviewed](https://github.com/microsoft/vcpkg/labels/info%3Areviewed) Pull Request changes follow basic guidelines removed until it is reviewed again. Basically we don't know if it is ready to review because it wasn't reset to draft state after @dan-shaw's comment. AFAIU the host triplet part is still incomplete, and my comment about installing the official exported config is still valid. (There would be more comments with regard to the code, but it is more stylistic, not fundamental.)

@dg0yt you are right In terms of the host triplet being incomplete I have tried now fixing it but it would require patching the Makefile, would that be sufficient?
My unsuccessful try so far: 
```cmake
string(COMPARE EQUAL "${TARGET_TRIPLET}" "${HOST_TRIPLET}" BUILDING_WITH_HOST_TRIPLET)

list(APPEND libcap_OPTIONS "prefix=${CURRENT_INSTALLED_DIR}" "CC=$ENV{CC}" "AR=$ENV{AR}" "RANLIB=$ENV{RANLIB}")

if(BUILDING_WITH_HOST_TRIPLET)
  message(WARNING "CROSS COMPILING ${BUILDING_WITH_HOST_TRIPLET}")
  vcpkg_build_make(SUBPATH libcap
    BUILD_TARGET cap_names.h
    LOGFILE_ROOT "configure"
    OPTIONS
      ${libcap_OPTIONS}
  )
endif()
if(VCPKG_CROSSCOMPILING)
  file(COPY "${CURRENT_BUILDTREES_DIR}/${HOST_TRIPLET}-rel/libcap/_makenames" DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/libcap/")
  file(COPY "${CURRENT_BUILDTREES_DIR}/${HOST_TRIPLET}-dbg/libcap/_makenames" DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/libcap/")
  file(COPY "${CURRENT_BUILDTREES_DIR}/${HOST_TRIPLET}-rel/libcap/cap_names.h" DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/libcap/")
  file(COPY "${CURRENT_BUILDTREES_DIR}/${HOST_TRIPLET}-dbg/libcap/cap_names.h" DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/libcap/")
# everything works if the below code is enabled, as it implicitly uses the host compiler to generate this one header
#  vcpkg_build_make(SUBPATH libcap
#    BUILD_TARGET cap_names.h
#    LOGFILE_ROOT "configure"
#  )
endif ()
```

In terms of the >installing the official exported config< how would you propose discussing that topic ?

2023-07-10 23:13 UTC, dan-shaw reviewed
Based on your comment, I think we can keep the unofficial CMake config. Can you explain your cross-compilation scenario? What is your host/target platform?

2023-07-10 23:13 UTC, dan-shaw commented on ports/libcap/portfile.cmake
> +list(APPEND libcap_OPTIONS "prefix=${CURRENT_INSTALLED_DIR}" "CC=$ENV{CC}" "AR=$ENV{AR}" "RANLIB=$ENV{RANLIB}")
```suggestion
```
What does this do?

2023-07-11 10:50 UTC, jbbjarnason commented
> Based on your comment, I think we can keep the unofficial CMake config. Can you explain your cross-compilation scenario? What is your host/target platform?

I am using different host OS but all based of x86_64 architecture. The OSs are Ubuntu 23.04 and Arch Linux.
My target platform is arm64/aarch64 f.e. Raspberry pi. Everything is Linux based, and I think systemd is actually GNU libc dependent but that's a different subject.

2023-07-11 11:07 UTC, jbbjarnason commented on ports/libsystemd/Config.cmake.in
> +    find_package(PkgConfig REQUIRED)
done

2023-07-11 11:10 UTC, jbbjarnason commented on ports/libcap/portfile.cmake
> +list(APPEND libcap_OPTIONS "prefix=${CURRENT_INSTALLED_DIR}" "CC=$ENV{CC}" "AR=$ENV{AR}" "RANLIB=$ENV{RANLIB}")
overwriting the compiler, see here: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/tree/Make.Rules?h=cap/v1.2.68#n69

2023-07-11 17:39 UTC, dg0yt commented
> Based on your comment, I think we can keep the unofficial CMake config.

I don't get why. Without the pc file, the port fails to satisfy reasonable user expectations IMO. So the official pc files should be installed and fixed. It shouldn't be too hard, given that similar dependency knowledge is the base of the CMake config. And the proposed cmake config relies on pkg-config anyways. It has some issues, but I even didn't want to start making review comments. 

(Coincidentally I'm currently working on port freerdp which would use `libsystemd.pc` if available...)

2023-07-13 03:09 UTC, dan-shaw commented
Some thoughts:

1. Ok @dg0yt I agree with you. In general, the `pkgconfig` file should be correct, or we should remove it. As you pointed out, this is probably a simple change (probably 1 or 2 lines), so I think we should try to figure out what that is. I can help as well.
2. We need the path to the compiler/tools so we can override the hard coded values in the `Makefile`. The proper way is to use `vcpkg-cmake-get-vars` (this is a port), and get the tool info from CMake.
3. So it seems that `cap_names.h` is generated from the target system linux capabilities, so I don't think it is correct to have the host system generate this file, so actually this means this is broken for cross compiling. I think the best effort thing we can do is 1) add `cap_names.h` as a file in the port. This file would be copied to the build tree when cross compiling. 2) for host builds, we generate `cap_names.h` as before.

Once these are addressed, I think we can merge.

2023-08-08 16:07 UTC, jbbjarnason commented
@dan-shaw 
1. CMake config is now removed and pkgconfig file has been patched, https://github.com/microsoft/vcpkg/pull/31150/commits/4fad2c2f318c86c8a0150ba770118ee1ba58790a
2. Pending
3. The cap_names.h generated from kernel version 6.2 (Ubuntu) on arm64 target is the same as x64 kernel version 6.4.8 (Arch), so the benefit of copying the file is not much. 
4. Copying the cap_names.h while cross compiling will require some patches to the makefile, is this something I should do?

2023-08-11 08:21 UTC, dan-shaw commented
Thanks! For 3, I was thinking of:
```cmake
if(VCPKG_CROSSCOMPILING)
 file(COPY "${CMAKE_CURRENT_LIST_DIR}/cap_names.h" DESTINATION "${SOURCE_PATH}")
endif()
```
and we would check in `cap_names.h`.

2023-08-11 08:31 UTC, dg0yt commented
@dan-shaw Why not take it from the host triplet?

2023-08-14 07:22 UTC, dg0yt commented
I still don't fully understand how close the coupling is between libsystemd (here proposed as a vcpkg port) and the systemd host processes (system packages which cannot be replaced), i.e. how the vcpkg port improves or limits or compatibility of the resulting binaries.

But I'm quite sure that we will see a number of installation order problems. There is at least port `dbus` interacting with libsystemd. 
(Context: While looking at #29660, I found that I can't cross build at-spi-core:arm64-linux because it doesn't link the right libdbus, and I can't cross build the dbus:arm64-linux because I don't have libsystemd for this target (and no system package for this). Port `libsystemd` might resolve a problem here. But we would have to patch two more ports for dependencies.)

A similar problem may exists with `libxcrypt`: Until now, ports would pick `libcrypt.[a|so]` from the system. On Ubuntu 20.04, the runtime is a dependency of `base-files`, and the development package is a dependency of the libc development packages. 
In absence of libxcrypt, glibc might have its own libcrypt implementation, as far as I understand from https://github.com/besser82/libxcrypt#compatibility-notes. But libxcrypt seems to be an ABI compatible replacement.

2023-09-11 19:22 UTC, dan-shaw commented
@dg0yt That is also possible. @jbbjarnason still working on this?

2023-09-11 19:27 UTC, jbbjarnason commented
@dan-shaw this was on hold while I waited for an answer to @dg0yt  question. The 3. Point is a bit complicated and will require patching the makefile. I will look into it tomorrow.

2023-09-12 11:18 UTC, jbbjarnason commented
> @dg0yt That is also possible. @jbbjarnason still working on this?

@dan-shaw I have finished point 2 and 3 of your request for changes comment, https://github.com/microsoft/vcpkg/pull/31150/commits/cd334f8e3b991e7f0b5721ab7cf13bc24abef1e3

2023-09-13 22:45 UTC, dan-shaw approved these changes

2023-09-13 22:48 UTC, dan-shaw commented
@dg0yt I think all the outstanding changes have been addressed unless there was something I missed. We may need changes to other ports, but I think it is outside the scope of this PR.

2023-09-14 02:27 UTC, Adela0814 approved these changes

2023-09-20 16:56 UTC, merged