[netgen] add new port
microsoft/vcpkg pull request #31288
Opened 2023-05-06 12:19 UTC by Neumann-A

- [ ] depends on opencascade being fixed. 

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-10-25 12:59 UTC, Neumann-A commented
@BillyONeal Suddenly ICE:
```
D:\buildtrees\netgen\src\140c4f4da5-6d91c2da69.clean\libsrc\meshing\meshclass.cpp(4513): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1639)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
D:\buildtrees\netgen\src\140c4f4da5-6d91c2da69.clean\libsrc\core\taskmanager.hpp(242): note: see reference to function template instantiation 'auto netgen::Mesh::CalcTotalBad::<lambda_36f3864a128a202fc3c8c4f2f8a44e7a>::operator ()<ngcore::T_Range<size_t>>(ngcore::T_Range<size_t>) const' being compiled
D:\buildtrees\netgen\src\140c4f4da5-6d91c2da69.clean\libsrc\meshing\meshclass.cpp(4491): note: see reference to function template instantiation 'void ngcore::ParallelForRange<size_t,netgen::Mesh::CalcTotalBad::<lambda_36f3864a128a202fc3c8c4f2f8a44e7a>>(ngcore::T_Range<size_t>,TFUNC,int,ngcore::TotalCosts)' being compiled
        with
        [
            TFUNC=netgen::Mesh::CalcTotalBad::<lambda_36f3864a128a202fc3c8c4f2f8a44e7a>
        ]
INTERNAL COMPILER ERROR in 'C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```
Bit strange since https://github.com/microsoft/vcpkg/runs/18040094681 was fine.

2023-12-27 08:02 UTC, JonLiu1993 commented
````
CMake Error at windows/CMakeLists.txt:1 (configure_file):
  Permission denied
````

2024-01-01 21:59 UTC, Neumann-A commented
> I originally wanted to test usage locally after merging.

```
configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/netgen.rc.template"
    "${CMAKE_CURRENT_SOURCE_DIR}/netgen.rc"
    IMMEDIATE @ONLY)
```
mutating the source tree so disable parallel configure should solve it.

2024-01-02 05:02 UTC, dg0yt commented on versions/n-/netgen.json
> +    }
```suggestion
```

2024-01-02 08:23 UTC, Neumann-A commented on versions/n-/netgen.json
> +    }
i would have committed this but the correction was one line of. It needed to start at the `},` line otherwise there would have been a trailing `,`

2024-01-08 02:54 UTC, JonLiu1993 commented
Tested usage successfully by netgen:x64-windows:
````
netgen provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(Netgen CONFIG REQUIRED)
  # note: 1 additional targets are not displayed.
  target_link_libraries(main PRIVATE nglib ngcore netgen_mpi netgen_cgns)
````

2024-01-08 02:59 UTC, JonLiu1993 commented
@Neumann-A, This PR looks very good, but there are many upstream patches. I think we should submit a PR upstream to let upstream know about it.

2024-01-08 06:17 UTC, Neumann-A commented
There is https://github.com/NGSolve/netgen/issues/150
and
https://github.com/NGSolve/netgen/pull/38

only ports/netgen/static-exports.patch seems to be intereseting for upstream then.

2024-01-11 23:32 UTC, JavierMatosD requested changes

2024-01-11 23:32 UTC, JavierMatosD commented on ports/netgen/cgns-scoped-enum.patch
> + {
I think these replacements can be done through macros to reduce the size of the patch. I.e., `#define ElementType_t CGNS_ENUMT(ElementType_t)`. Please include a comment saying these macros are here for compatibility with `CGNS_ENABLE_SCOPING`.

2024-01-11 23:48 UTC, Neumann-A commented on ports/netgen/cgns-scoped-enum.patch
> + {
Wouldn't that lead to a patch which upstream would disagree with since that seems like a nasty hack then a proper fix for the issue? 
Since upstream approval is mentioned before minimizing patches in the maintainers guide I would  say "possible approval" > "small patch"

2024-01-12 18:08 UTC, JavierMatosD commented on ports/netgen/cgns-scoped-enum.patch
> + {
> Wouldn't that lead to a patch which upstream would disagree with since that seems like a nasty hack then a proper fix for the issue?

I disagree that this is a "nasty hack" since it essentially does the same thing your patch is doing but results in a much smaller patch. 

> Since upstream approval is mentioned before minimizing patches in the maintainers guide I would say "possible approval" > "small patch"

I've already discussed this with @BillyONeal, @ras0219-msft, and @data-queue and we all agree with this proposed solution.

2024-01-12 21:03 UTC, Neumann-A commented on ports/netgen/cgns-scoped-enum.patch
> + {
Done

2024-01-16 23:04 UTC, JavierMatosD approved these changes

2024-01-16 23:04 UTC, merged