[qt5-declarative] Add d3d12 feature
microsoft/vcpkg pull request #31291
Opened 2023-05-06 15:58 UTC by Osyotr

Towards https://github.com/microsoft/vcpkg/issues/8213 (https://github.com/microsoft/vcpkg/issues/8213#issuecomment-1536983382)

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-05-08 06:49 UTC, Adela0814 requested changes, later dismissed

2023-05-08 06:49 UTC, Adela0814 commented on ports/qt5-declarative/vcpkg.json
> +    "platform-default-features"
You can add `d3d12` directly as a default feature.
```suggestion
    "d3d12"
```

2023-05-08 06:53 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-05-08 07:17 UTC, dg0yt commented on ports/qt5-declarative/vcpkg.json
> +    "platform-default-features"
No, you cannot.

2023-05-08 07:37 UTC, Adela0814 commented on ports/qt5-declarative/vcpkg.json
> +    "platform-default-features"
Ok, I noticed the explanation in this comment:https://github.com/microsoft/vcpkg/pull/31294#issuecomment-1537223587.

2023-05-09 02:22 UTC, Adela0814 commented
Tested features in the following triplets:

- x64-windows
- x64-windows-static
- x86-windows

2023-05-09 23:34 UTC, merged