[pcre2] fix jit off for osx arm64
microsoft/vcpkg pull request #31294
Opened 2023-05-06 18:32 UTC by talregev

fix jit off for osx arm64

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2023-05-06 19:30 UTC, autoantwort commented
It is currently not failing?

2023-05-06 19:46 UTC, talregev commented
> It is currently not failing?

vcpkg ci doesn't check `arm64-osx` triplet.

2023-05-06 19:46 UTC, autoantwort commented
I have tested it locally

2023-05-06 19:47 UTC, talregev commented
> I have tested it locally

I tested it on osx on the gitgub action ci. and it fail without this fix.

2023-05-06 19:50 UTC, autoantwort commented
Can you provide the error logs?

2023-05-06 19:51 UTC, talregev commented
> Can you provide the error logs?

I will.

2023-05-06 19:52 UTC, autoantwort commented
Ah I found it:
```
/Users/leanderSchulten/git_projekte/vcpkg2/buildtrees/pcre2/src/cre2-10.40-42fc341438.clean/src/sljit/sljitExecAllocator.c:156:2: error: "Must target Big Sur or newer"
#error "Must target Big Sur or newer"
 ^
1 error generated.
```

2023-05-06 19:52 UTC, autoantwort commented
But then I suggest to make it a feature instead of turning it off completely because it only works on current macs.

2023-05-06 19:53 UTC, talregev commented
> But then I suggest to make it a feature instead of turning it off completely because it only works on current macs.

I will try to convert it to a feature.

2023-05-06 20:17 UTC, autoantwort commented on ports/pcre2/vcpkg.json
> +      "supports": "!ios & !emscripten"
The `!ios` is actually wrong. I tested it locally.

2023-05-06 20:18 UTC, talregev commented on ports/pcre2/vcpkg.json
> +      "supports": "!ios & !emscripten"
Did you see that in the original they turn it off for ios?

2023-05-06 20:19 UTC, autoantwort commented on ports/pcre2/vcpkg.json
> +      "supports": "!ios & !emscripten"
Yes, but it seems that this is wrong (maybe it was right in the past)

2023-05-06 20:22 UTC, talregev commented on ports/pcre2/vcpkg.json
> +      "supports": "!ios & !emscripten"
I remove it. But I have a feeling that other people will fix it to add not support ios.

2023-05-06 20:24 UTC, talregev commented
@autoantwort Can you test my port and check I didn't make errors?

2023-05-06 20:24 UTC, autoantwort commented on ports/pcre2/vcpkg.json
> +      "supports": "!ios & !emscripten"
We'll see in the future.

2023-05-06 20:25 UTC, autoantwort approved these changes, later dismissed

2023-05-06 20:52 UTC, talregev commented
@autoantwort What about android failing?

2023-05-06 20:56 UTC, autoantwort commented
I think it is a baseline regression not caused by this PR.

2023-05-06 21:07 UTC, Osyotr commented
It think that until https://github.com/microsoft/vcpkg-tool/pull/813 is merged, `default-features` should not contain features that have `supports` expression.
Workaround is to create `platform-default-features` feature that has `platform` expression (https://github.com/microsoft/vcpkg/pull/31291/files#diff-fa5764c3245e6fdc2a5bd9ad48405b4e6f2555a4bff9079d365bb4990e3b002a)

2023-05-08 09:04 UTC, Cheney-W commented
/azp run

2023-05-08 09:05 UTC, Cheney-W approved these changes, later dismissed

2023-05-08 12:01 UTC, talregev commented
@Cheney-W 
There already fix that approved
https://github.com/microsoft/vcpkg/pull/29767

I will merge the master after you will merge it.

2023-05-09 03:56 UTC, dg0yt commented
> It think that until [microsoft/vcpkg-tool#813](https://github.com/microsoft/vcpkg-tool/pull/813) is merged, `default-features` should not contain features that have `supports` expression. Workaround is to create `platform-default-features` feature that has `platform` expression (https://github.com/microsoft/vcpkg/pull/31291/files#diff-fa5764c3245e6fdc2a5bd9ad48405b4e6f2555a4bff9079d365bb4990e3b002a)

This still must be done.

2023-05-09 23:29 UTC, vicroms requested changes, later dismissed

2023-05-09 23:29 UTC, vicroms commented on ports/pcre2/vcpkg.json
> +  }
```suggestion
  "default-features": [
    "default-features"
  ],
  "features": {
    "default-features": {
      "description": "Enable default features",
      "dependencies": [
        {
          "name": "pcre2",
          "platform": "!emscripten",
          "features": [
            "jit"
          ]
        }
      ]
    },
    "jit": {
      "description": "Build JIT support",
      "supports": "!emscripten"
    }
  }
```

2023-05-09 23:29 UTC, vicroms commented on ports/pcre2/vcpkg.json
> +  }
As suggested by @Osyotr make a `default-features` a feature itself

2023-05-10 01:36 UTC, Cheney-W commented
I have converted your PR to draft status. When you respond to Victor's suggestion, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-05-10 10:43 UTC, talregev commented on ports/pcre2/vcpkg.json
> +  }
done.

2023-05-10 10:43 UTC, talregev commented
@Cheney-W @vicroms 
Ready for review.

2023-05-11 02:04 UTC, Cheney-W approved these changes

2023-05-11 18:37 UTC, merged