Add wcslib port
microsoft/vcpkg pull request #31320
Opened 2023-05-08 13:34 UTC by sjperkins

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2023-05-08 16:48 UTC, dg0yt commented
Did you try to use the official build system? CMake may be faster to build, but the vendored build system needs to be reviewed and maintained. And long-term experience from other ports is .... mixed.

2023-05-08 17:26 UTC, dg0yt requested changes
Please let CI fi

2023-05-08 17:26 UTC, dg0yt commented on ports/wcslib/vcpkg.json
> +      "features": ["curl", "pthreads"]
Hm, the cfitsio pthreads feature seems to be broken on windows.
Can you remove `pthreads` in this line?

2023-05-08 17:26 UTC, dg0yt commented on ports/wcslib/vcpkg.json
> +      "default-features": true,
These two lines are redundant. The current values are the defaults.

2023-05-08 17:38 UTC, sjperkins commented
> Did you try to use the official build system? CMake may be faster to build, but the vendored build system needs to be reviewed and maintained. And long-term experience from other ports is .... mixed.

Yes, I think this is as far as I've managed to get with it https://github.com/microsoft/vcpkg/pull/31320/commits/5eaa02b9a9fe0ea29e5b5ca431a2a6c7d3613298.

There are two issues I've run into:

1. Quoting from the [docs](https://www.gnu.org/software/gnuastro/manual/html_node/WCSLIB.html), `configure` need `-lcurl` to succeed:
    ```
    ## If `./configure' fails, remove `-lcurl' and run again.
    $ ./configure LIBS="-pthread -lcurl -lm" --without-pgplot     \
            --disable-fortran CFLAGS="$CFLAGS -g0 -O3"
   ```
   I don't think the above is correct (LIBS should be set before ./configure). So I'm not entirely sure how cleanly pass LIBS into the configure call. Do you have any ideas here?

   ```
   vcpkg_configure_make(
     SOURCE_PATH ${src}
     COPY_SOURCE
     OPTIONS
        --disable-flex
        --disable-fortran
        --without-pgplot
        --with-libcfitsio-include=${CURRENT_INSTALLED_DIR}/include/cfitsio
        --with-libcfitsio-lib=${CURRENT_INSTALLED_DIR}/lib)
   ```

2. Also `wcslib.pc.in` ends up with an absolute path in the prefix. Perhaps this can be fixed with a patch.

2023-05-08 17:42 UTC, sjperkins commented on ports/wcslib/vcpkg.json
> +      "features": ["curl", "pthreads"]
I strongly suspect this package has never compiled on windows. Is there rather some way to disable the port for windows?

2023-05-08 17:44 UTC, sjperkins commented on ports/wcslib/vcpkg.json
> +      "default-features": true,
Have removed the locally, but will refrain from pushing until CI is done.

2023-05-08 17:49 UTC, dg0yt commented on ports/wcslib/vcpkg.json
> +      "features": ["curl", "pthreads"]
Does wcslib strictly depend on these cfitsio features? Or will it use cfitsio as is?

2023-05-08 18:22 UTC, sjperkins commented
> `-lcurl` won't be enough - at least for static builds, it takes a long list of link libraries. The solution is to use `pkgconfig`, both during configuration and as Requires.private in the pc file. Maybe the same needs to be done with cfitsio, for the same reasons. Last not least you have to deal with the fact that vcpkg builds both release and debug. These variants install libs to different directories and sometimes with different names. pkgconfig will resolve this for curl and cfitsio.
> 
> Do you feel comfortable with creating patches as needed?

I think I'll be fine creating patches. Would it be possible for you to provide a snippet showing how to call `pkg-config` in relation to the above `vcpkg_configure_make` call, also showing show to point it at the relevant `.pc` files in the `installation` dirs?

2023-05-08 18:27 UTC, sjperkins commented on ports/wcslib/vcpkg.json
> +      "features": ["curl", "pthreads"]
I guess not, but it does allow for remote access of FITS files: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node85.html

2023-05-08 20:10 UTC, dg0yt commented
All examples seem to be quite specific...
I currently work on libpq, which has this patch to configure.ac :
https://github.com/microsoft/vcpkg/blob/3a409cdf210466d3d86bbb8aeb0fa20a5bbf95e0/ports/libpq/patches/fix-configure.patch#L66-L70

The pattern is
- remove or disable the original test
- Use PKG_CHECK_MODULES
- Put `<PREFIX>_CFLAGS` and `<PREFIX>_LIBS` into `CFLAGS` and `LIBS`

And in the pc file template, remove all `-l` references for the dependency and add the "module" name to `Requires.private:`. (It is more difficult with optional deps.)

2023-05-09 06:36 UTC, JonLiu1993 commented on ports/wcslib/portfile.cmake
> +vcpkg_configure_make(
I see the CMakeLists file you provided yourself above, why not make cmake compile?

2023-05-09 07:53 UTC, sjperkins commented on ports/wcslib/portfile.cmake
> +vcpkg_configure_make(
See previous discussion here https://github.com/microsoft/vcpkg/pull/31320#issuecomment-1538714414 which suggests using wcslib's inbuilt configure/make system.

I actually prefer the parallel cmake system but as @dg0yt points out, it may drift from the configure/make system.

On the other hand, wcslib is quite mature so drift may be minimal going forward. Difficult to quantify this though.

2023-05-09 08:09 UTC, sjperkins commented on ports/wcslib/CMakeLists.txt
> +    # utils/wcsgrid.c
There are 4 commented out sections:

1. pgplot related utilities, but these could be removed. Supporting evidence from the [docs](https://www.gnu.org/software/gnuastro/manual/html_node/WCSLIB.html):
 
  > WCSLIB also has plotting capabilities which use PGPLOT (a plotting library for C). If you wan to use those capabilities in WCSLIB, [PGPLOT](https://www.gnu.org/software/gnuastro/manual/html_node/PGPLOT.html) provides the PGPLOT installation instructions. However PGPLOT is old[75](https://www.gnu.org/software/gnuastro/manual/html_node/WCSLIB.html#FOOT75), so its installation is not easy, there are also many great modern WCS plotting tools (mostly in written in Python). Hence, if you will not be using those plotting functions in WCSLIB, you can configure it with the --without-pgplot option as shown below.

2. [FORTRAN wrappers](https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/fortran.html) of the c code. These can also be removed.

3. test cases. Might be worth compiling and running them on install? I'm not sure if vcpkg supports this?

4. utilities. Also unlikely to be used, so could be removed.

2023-05-09 09:03 UTC, JonLiu1993 commented on ports/wcslib/portfile.cmake
> +vcpkg_configure_make(
@sjperkins @dg0yt , In this case, I don't think it is necessary to add the CMakeLists file, just use the official make build directly, what do you think?

2023-05-10 12:38 UTC, sjperkins commented
I had an email discussion with the author of wcslib, Mark Callabreta
yesterday, email [here](https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/index.html).

> Also, re pgplot, it's not required for the library itself, only the test
suite - of interest only to myself and package maintainers; it doesn't
belong in the library package, nor do the utility programs. The same
applies to cfitsio, though there is a slight wrinkle with one function,
getwcstab(), but it is only provided as a programming template - it
doesn't go into the wcslib object library. The Fortran wrappers were
really only intended for heritage packages such as AIPS and Miriad. As
maintainer of the latter at ATNF I retrofitted it to use WCSLIB some
years ago.

This means that the dependencies (especially cfitsio) are only necessary for
running the test suite and wcslib can be compiled without dependencies
(as @dg0yt noted), rendering the `vcpkg_configure_make` route much easier.

> People have asked previously about supporting Windows but I have zero
familiarity with it (don't even know how to edit a source file) and it's
not something I can contemplate at this stage.

I think this means that it will probably be necessary to set `{"supports": "!windows"}`
in `vcpkg.json` but perhaps lets see what happens when the CI runs?

2023-05-10 12:39 UTC, sjperkins commented on ports/wcslib/portfile.cmake
> +vcpkg_configure_make(
Removed `CMakeLists.txt`

2023-05-10 12:41 UTC, sjperkins commented on ports/wcslib/vcpkg.json
> +      "features": ["curl", "pthreads"]
> Does wcslib strictly depend on these cfitsio features? Or will it use cfitsio as is?

This was a good question! As discussed here https://github.com/microsoft/vcpkg/pull/31320#issuecomment-1542138468 cfitsio is only necessary for running the wcslib test suite, so we can remove this dependency

2023-05-11 07:49 UTC, JonLiu1993 commented
@sjperkins, Could you please help test the usage locally? I cannot successfully install wcslib locally, and the error shows that the link timed out when downloading `ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2`:
````
test@test001:~/vcpkg$ ./vcpkg install wcslib
Computing installation plan...
The following packages will be built and installed:
    wcslib[core]:x64-linux -> 7.12
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/test/.cache/vcpkg/archives in 9.9 us. Use --debug to see more details.
Installing 1/1 wcslib:x64-linux...
Building wcslib[core]:x64-linux...
-- Downloading ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2 -> wcslib-7.12.tar.bz2...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/test/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/test/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 1000: popen( curl --fail -L ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2 --create-dirs --output /home/test/vcpkg/downloads/wcslib-7.12.tar.bz2.327728.part 2>&1)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 28 after 131752902 us
error: Failed to download from mirror set
error: ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2: curl failed to download with exit code 28
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (28) Failed to connect to ftp.atnf.csiro.au port 21 after 131744 ms: Connection timed out


````

2023-05-11 07:53 UTC, sjperkins commented
> @sjperkins, Could you please help test the usage locally? I cannot successfully install wcslib locally, and the error shows that the link timed out when downloading `ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2`:

Thanks for trying. I get the following:

```
simon@LAPTOP-6HDASBBS:~/code/vcpkg$ ./vcpkg install wcslib
Computing installation plan...
The following packages will be built and installed:
    wcslib[core]:x64-linux -> 7.12
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/simon/.cache/vcpkg/archives in 644 us. Use --debug to see more details.
Installing 1/1 wcslib:x64-linux...
Building wcslib[core]:x64-linux...
-- Downloading ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2 -> wcslib-7.12.tar.bz2...
-- Extracting source /home/simon/code/vcpkg/downloads/wcslib-7.12.tar.bz2
-- Using source at /home/simon/code/vcpkg/buildtrees/wcslib/src/wcslib-7-d81e56e144.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Installing x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-rel
-- Fixing pkgconfig file: /home/simon/code/vcpkg/packages/wcslib_x64-linux/lib/pkgconfig/wcslib.pc
-- Fixing pkgconfig file: /home/simon/code/vcpkg/packages/wcslib_x64-linux/debug/lib/pkgconfig/wcslib.pc
-- Installing: /home/simon/code/vcpkg/packages/wcslib_x64-linux/share/wcslib/copyright
-- Installing: /home/simon/code/vcpkg/packages/wcslib_x64-linux/share/wcslib/usage
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle wcslib:x64-linux: 27 s
Total install time: 30 s
The package wcslib provides CMake targets:

    find_package(wcslib REQUIRED)
    target_link_libraries(main PRIVATE wcslib)
    target_include_directories(main PRIVATE wcslib)
```

Maybe your network blocks outgoing FTP requests?

2023-05-11 07:59 UTC, JonLiu1993 commented
@sjperkins, I asked my colleagues to help me to try to install but failed to install, could you test the usage of this port locally? If successful, we can wait to merge this PR.

2023-05-11 09:55 UTC, sjperkins commented
> @sjperkins, I asked my colleagues to help me to try to install but failed to install, could you test the usage of this port locally? If successful, we can wait to merge this PR.

Sure! 

From my perspective, I'm adding wcslib in order to make a port of a larger Radio Astronomy package called [casacore](https://casacore.github.io/). I've already started on this port locally, and it's now able to depend on the wcslib port, but I haven't managed to get `casacore` to fully compile yet (there's an issue with the `fftw3` dependency that I'll need to address separately).

That's a fairly large change. From your perspective, what would be useful for me to demonstrate success with wcslib locally?

2023-05-11 09:58 UTC, JonLiu1993 commented
Use a simple cmake project to test the usage provided by this port:

````
    find_package(wcslib REQUIRED)
    target_link_libraries(main PRIVATE wcslib)
    target_include_directories(main PRIVATE wcslib)
````

2023-05-11 16:17 UTC, dg0yt commented on ports/wcslib/vcpkg.json
> +  "homepage": "https://www.gnu.org/software/gnuastro/manual/html_node/WCSLIB.html",
What I take from that page is that the actual homepage is:
https://www.atnf.csiro.au/people/mcalabre/WCS/

2023-05-11 16:17 UTC, dg0yt commented on ports/wcslib/portfile.cmake
> +    URLS "ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2"
Can the FTP link replaced or complemented with a secure transport? The official website has an http link, but it can be used with HTTPS:
https://www.atnf.csiro.au/people/mcalabre/WCS/wcslib-7.12.tar.bz2

2023-05-11 20:09 UTC, sjperkins commented on ports/wcslib/vcpkg.json
> +  "homepage": "https://www.gnu.org/software/gnuastro/manual/html_node/WCSLIB.html",
Changed to https://www.atnf.csiro.au/people/mcalabre/WCS/

2023-05-11 20:09 UTC, sjperkins commented on ports/wcslib/portfile.cmake
> +    URLS "ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib-7.12.tar.bz2"
Changed to to use the https url

2023-05-11 20:11 UTC, sjperkins commented
> Use a simple cmake project to test the usage provided by this port:
> 
> ```
>     find_package(wcslib REQUIRED)
>     target_link_libraries(main PRIVATE wcslib)
>     target_include_directories(main PRIVATE wcslib)
> ```

I've tried this, but I think I'm making a conceptual mistake here. As this is a `make/configure` project, it doesn't produce any cmake file and so `find_package(wcslib REQUIRED)` will always fail. If this is the correct behaviour on vcpkg's part, should I jsut remove the `usage` file?

2023-05-11 20:33 UTC, sjperkins commented
> As this is a `make/configure` project, it doesn't produce any cmake file

For e.g. the acl port has no usage file

2023-05-12 03:53 UTC, dg0yt commented
The usage file is just documentation, and it is desired. This project installs pkgconfig files, and it can be used from cmake in this way. Cf. `ports/mujs/usage`.

2023-05-12 08:11 UTC, sjperkins commented
> The usage file is just documentation, and it is desired. This project installs pkgconfig files, and it can be used from cmake in this way. Cf. `ports/mujs/usage`.

Thanks, I've updated the usage.

The following archive [test.zip](https://github.com/microsoft/vcpkg/files/11460890/test.zip) contains a cmake example using code from wcslib utils to compile a utility called `fitshdr`:

```cmake
cmake_minimum_required(VERSION 3.19.1)

project(fitshdr)
add_executable(fitshdr fitshdr.c)

find_package(PkgConfig)
pkg_check_modules(wcslib REQUIRED IMPORTED_TARGET wcslib)
target_include_directories(fitshdr PRIVATE PkgConfig::wcslib)
target_link_libraries(fitshdr PRIVATE PkgConfig::wcslib)
```

The following compiles `fitshdr` with the vcpkg cmake toolchain

```bash
$ cmake -DCMAKE_TOOLCHAIN_FILE=$HOME/code/vcpkg/scripts/buildsystems/vcpkg.cmake ..
```
and if one downloads an example FITS file from https://fits.gsfc.nasa.gov/fits_samples.html:

```bash
$ ./fitshdr ../WFPC2u5780205r_c0fx.fits 
================================================================================
FITS header number 1 at block number 1.
--------------------------------------------------------------------------------
SIMPLE  =                    T / file does conform to FITS standard
BITPIX  =                  -32 / number of bits per data pixel
NAXIS   =                    3 / number of data axes
NAXIS1  =                  200 / length of data axis 1
NAXIS2  =                  200 / length of data axis 2
NAXIS3  =                    4 / length of data axis 3
EXTEND  =                    T / FITS dataset may contain extensions
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H
BSCALE  =                1.0E0 / REAL = TAPE*BSCALE + BZERO
BZERO   =                0.0E0 /
OPSIZE  =                 2112 / PSIZE of original image
ORIGIN  = 'STScI-STSDAS'       / Fitsio version 21-Feb-1996
FITSDATE= '2004-01-09'         / Date FITS file was created
FILENAME= 'u5780205r_cvt.c0h'  / Original filename
ALLG-MAX=           3.777701E3 / Data max in all groups
ALLG-MIN=          -7.319537E1 / Data min in all groups
ODATTYPE= 'FLOATING'           / Original datatype: Single precision real
SDASMGNU=                    4 / Number of groups in original image
CRVAL1  =       182.6311886308
CRVAL2  =       39.39633673411
CRPIX1  =                 420.
CRPIX2  =                424.5
CD1_1   =         -1.067040E-6
CD1_2   =         -1.259580E-5
CD2_1   =         -1.260160E-5
CD2_2   =          1.066550E-6
DATAMIN =          -7.319537E1 / DATA MIN
DATAMAX =           3.777701E3 / DATA MAX
MIR_REVR=                    T
ORIENTAT=               -85.16
FILLCNT =                    0
ERRCNT  =                    0
FPKTTIME=         51229.798574
LPKTTIME=         51229.798742
CTYPE1  = 'RA---TAN'
CTYPE2  = 'DEC--TAN'
DETECTOR=                    1
DEZERO  =             316.6452
BIASEVEN=             316.6715
BIASODD =             316.6189
GOODMIN =            -5.064006
GOODMAX =              2552.17
DATAMEAN=            0.4182382
GPIXELS =               632387
SOFTERRS=                    0
CALIBDEF=                 1466
STATICD =                    0
ATODSAT =                   16
DATALOST=                    0
BADPIXEL=                    0
OVERLAP =                    0
PHOTMODE= 'WFPC2,1,A2D7,LRF#4877.0,,CAL'
PHOTFLAM=         3.447460E-16
PHOTZPT =                -21.1
PHOTPLAM=             4884.258
PHOTBW  =             20.20996
MEDIAN  =            -0.175651
MEDSHADO=            -0.121681
HISTWIDE=             1.033711
SKEWNESS=            -1.983727
MEANC10 =              0.12958
MEANC25 =            0.3129676
MEANC50 =            0.4577668
MEANC100=            0.3916293
MEANC200=            0.3115222
MEANC300=            0.3295493
BACKGRND=           -0.3676353
ORIGIN  = 'NOAO-IRAF FITS Image Kernel December 2001' / FITS file originator
DATE    = '2004-01-09T03:26:36'
IRAF-TLM= '03:26:36 (09/01/2004)'
FILETYPE= 'SCI      '          / type of data found in data file

TELESCOP= 'HST'                / telescope used to acquire data
INSTRUME= 'WFPC2 '             / identifier for instrument used to acquire data
EQUINOX =               2000.0 / equinox of celestial coord. system

              / WFPC-II DATA DESCRIPTOR KEYWORDS

ROOTNAME= 'u5780205r'             / rootname of the observation set
PROCTIME=   5.301314019676E+04 / Pipeline processing time (MJD)
OPUS_VER= 'OPUS 14.5a        ' / OPUS software system version number
CAL_VER = '                        ' / CALWP2 code version

              / SCIENCE INSTRUMENT CONFIGURATION

MODE    = 'FULL'               / instr. mode: FULL (full res.), AREA (area int.)
SERIALS = 'OFF'                / serial clocks: ON, OFF

              / IMAGE TYPE CHARACTERISTICS

IMAGETYP= 'EXT               ' / DARK/BIAS/IFLAT/UFLAT/VFLAT/KSPOT/EXT/ECAL
CDBSFILE= 'NO                ' / GENERIC/BIAS/DARK/PREF/FLAT/MASK/ATOD/NO
PKTFMT  =                   96 / packet format code

              / FILTER CONFIGURATION

FILTNAM1= 'FR533P15'           / first filter name
FILTNAM2= '        '           / second filter name
FILTER1 =                   69 / first filter number (0-48)
FILTER2 =                    0 / second filter number (0-48)
FILTROT =                 15.0 / partial filter rotation angle (degrees)
LRFWAVE =          4877.000000 / linear ramp filter wavelength

              / INSTRUMENT STATUS USED IN DATA PROCESSING

UCH1CJTM=             -88.2569 / TEC cold junction #1 temperature (Celsius)
UCH2CJTM=             -88.6697 / TEC cold junction #2 temperature (Celsius)
UCH3CJTM=             -88.3028 / TEC cold junction #3 temperature (Celsius)
UCH4CJTM=             -88.7671 / TEC cold junction #4 temperature (Celsius)
UBAY3TMP=              13.2302 / bay 3 A1 temperature (deg C)
KSPOTS  = 'OFF'                / Status of Kelsall spot lamps: ON, OFF
SHUTTER = 'A'                  / Shutter in place at beginning of the exposure
ATODGAIN=                  7.0 / Analog to Digital Gain (Electrons/DN)

              / RSDP CONTROL KEYWORDS

MASKCORR= 'COMPLETE'           / Do mask correction: PERFORM, OMIT, COMPLETE
ATODCORR= 'COMPLETE'           / Do A-to-D correction: PERFORM, OMIT, COMPLETE
BLEVCORR= 'COMPLETE'           / Do bias level correction
BIASCORR= 'COMPLETE'           / Do bias correction: PERFORM, OMIT, COMPLETE
DARKCORR= 'COMPLETE'           / Do dark correction: PERFORM, OMIT, COMPLETE
FLATCORR= 'SKIPPED '           / Do flat field correction
SHADCORR= 'OMIT    '           / Do shaded shutter correction
DOSATMAP= 'OMIT    '           / Output saturated pixel map
DOPHOTOM= 'COMPLETE'           / Fill photometry keywords
DOHISTOS= 'OMIT    '           / Make histograms: PERFORM, OMIT, COMPLETE
OUTDTYPE= 'REAL  '             / Output image datatype: REAL, LONG, SHORT

              / CALIBRATION REFERENCE FILES

MASKFILE= 'uref$f8213081u.r0h     ' / name of the input DQF of known bad pixels
ATODFILE= 'uref$dbu1405iu.r1h'      / name of the A-to-D conversion file
BLEVFILE= 'ucal$u5780205r.x0h     ' / Engineering file with extended register da
BLEVDFIL= 'ucal$u5780205r.q1h     ' / Engineering file DQF
BIASFILE= 'uref$j9a1612mu.r2h'      / name of the bias frame reference file
BIASDFIL= 'uref$j9a1612mu.b2h'      / name of the bias frame reference DQF
DARKFILE= 'uref$j2g1549cu.r3h'      / name of the dark reference file
DARKDFIL= 'uref$j2g1549cu.b3h'      / name of the dark reference DQF
FLATFILE= 'uref$f4i1559cu.r4h'      / name of the flat field reference file
FLATDFIL= 'uref$f4i1559cu.b4h'      / name of the flat field reference DQF
SHADFILE= 'uref$e371355eu.r5h'      / name of the reference file for shutter sha
PHOTTAB = 'u5780205r_c3t.fits'      / name of the photometry calibration table
GRAPHTAB= 'mtab$n9i1408hm_tmg.fits' / the HST graph table
COMPTAB = 'mtab$nc809508m_tmc.fits' / the HST components table

              / DEFAULT KEYWORDS SET BY STSCI

 [...]

2023-05-15 18:47 UTC, sjperkins commented
Is anything else required from my side?

2023-05-16 02:55 UTC, JonLiu1993 approved these changes

2023-05-16 02:56 UTC, JonLiu1993 commented
Tested usage successfully by `wcslib:x64-linux`:
````
test@test001:~/build$ /home/test/vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake .. -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/buildsystems/vcpkg.cmake
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for module 'wcslib'
--   Found wcslib, version 7.12
-- Configuring done
-- Generating done
-- Build files have been written to: /home/test/build

````

2023-05-16 17:45 UTC, merged