[libmad] Add dynamic support
microsoft/vcpkg pull request #31350
Opened 2023-05-09 15:30 UTC by d10sfan

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

This adds support for building in dynamic mode for libmad.

2023-05-09 18:51 UTC, dg0yt requested changes

2023-05-09 19:11 UTC, d10sfan commented on ports/libmad/portfile.cmake
> +        -DBUILD_DYNAMIC=${BUILD_DYNAMIC}
Ah thanks, I didn't realize the check_linkage forced to static initially, I've removed these changes and it seems to work just fine now.

2023-05-09 19:12 UTC, d10sfan commented on ports/libmad/portfile.cmake
> +endif()
I've changed it so that it'll do the pkgconfig all the time, let me know if there's any changes there.

2023-05-09 19:12 UTC, d10sfan commented on ports/libmad/portfile.cmake
> -
I've made a change so that this will only run if the target is not linux. Let me know if there's anything else I should plan on doing here.

2023-05-09 20:37 UTC, Osyotr commented on ports/libmad/libmad.pc.in
> +Name: libmad
Both Debian and RHEL install `mad.pc`, I think we should also do that.
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: mad
Description: MPEG Audio Decoder
Requires:
Version: 0.15.0b
Libs: -L${libdir} -lmad
Cflags: -I${includedir}
```
https://packages.debian.org/sid/libmad0
https://rhel.pkgs.org/7/epel-x86_64/libmad-devel-0.15.1b-26.el7.x86_64.rpm.html

2023-05-10 01:27 UTC, d10sfan commented on ports/libmad/libmad.pc.in
> +Name: libmad
Let me know what you think of this, thanks

2023-05-10 03:27 UTC, dg0yt commented on ports/libmad/portfile.cmake
> +if(NOT VCPKG_TARGET_IS_LINUX)
Use `if(VCPKG_TARGET_IS_WINDOWS)` here.

2023-05-10 03:27 UTC, dg0yt commented on ports/libmad/portfile.cmake
> +# Adds pkgconfig template
Remove the comment.

2023-05-10 09:36 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2023-05-10 13:51 UTC, d10sfan commented on ports/libmad/portfile.cmake
> +if(NOT VCPKG_TARGET_IS_LINUX)
Done

2023-05-10 13:51 UTC, d10sfan commented on ports/libmad/portfile.cmake
> +# Adds pkgconfig template
Done

2023-05-11 07:01 UTC, FrankXie05 approved these changes, later dismissed

2023-05-11 15:27 UTC, dg0yt requested changes

2023-05-11 15:27 UTC, dg0yt commented on ports/libmad/mad.pc.in
> +Version: @VERSION@
This variable name has a value during portfile execution (script mode), but not (yet) during CMakeLists.txt execution (project mode).

2023-05-11 15:27 UTC, dg0yt commented on ports/libmad/portfile.cmake
>  )
In `vcpkg_cmake_configure`, you can pass the version from script to project:
~~~cmake
    OPTIONS
        "-DVERSION=${VERSION}"
~~~

2023-05-11 18:16 UTC, merged