[lexbor] Add new port
microsoft/vcpkg pull request #31415
Opened 2023-05-12 10:14 UTC by Pospelove

2023-05-15 07:19 UTC, JonLiu1993 requested changes

2023-05-15 07:19 UTC, JonLiu1993 commented on ports/lexbor/portfile.cmake
> +endif()
```suggestion
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" BUILD_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" BUILD_SHARED)
```

2023-05-15 07:19 UTC, JonLiu1993 commented on ports/lexbor/portfile.cmake
> +    -DLEXBOR_BUILD_STATIC=${LEXBOR_BUILD_STATIC}
```suggestion
    -DLEXBOR_BUILD_SHARED=${BUILD_SHARED}
    -DLEXBOR_BUILD_STATIC=${BUILD_STATIC}
```

2023-05-15 10:05 UTC, Pospelove commented
@JonLiu1993 ready

2023-05-16 06:56 UTC, JonLiu1993 approved these changes

2023-05-16 17:47 UTC, merged