[bshoshany-thread-pool] Updated to v3.4.0
microsoft/vcpkg pull request #31418
Opened 2023-05-12 19:22 UTC by bshoshany

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Thanks!

2023-05-15 02:52 UTC, Adela0814 approved these changes, later dismissed

2023-05-15 02:54 UTC, Adela0814 commented on ports/bshoshany-thread-pool/portfile.cmake
> +    REF v3.4.0
```suggestion
    REF "v${VERSION}"

```

2023-05-15 02:56 UTC, Adela0814 commented
@bshoshany Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-05-15 03:03 UTC, bshoshany commented
Thanks! I accepted your changes, but now it's failing a check :(

2023-05-15 03:46 UTC, Adela0814 requested changes

2023-05-15 03:46 UTC, Adela0814 commented on ports/bshoshany-thread-pool/portfile.cmake
> +
Please remove this line.

2023-05-15 14:56 UTC, bshoshany commented
I removed the line you indicated, but it's still failing a check - although maybe I didn't understand what you wanted me to change. Perhaps we should just revert to the original version? Thanks.

2023-05-16 01:53 UTC, Adela0814 commented
@bshoshany  The CI error was reported because the SHA value is incorrect. After making the changes, you should run the command again: `\vcpkg.exe x-add-version bshoshany-thread-pool --overwrite-version`.

2023-05-16 02:24 UTC, bshoshany commented
In the end I decided to just revert to my original version, since unfortunately I don't have more time to devote to this PR. I will incorporate the `REF "v${VERSION}"` trick next time I update the package. Thanks again :)

2023-05-16 02:31 UTC, Adela0814 approved these changes

2023-05-16 17:00 UTC, merged