[vcpkg baseline][vcpkg-ci-arrow | arrow]  Fix ci error
microsoft/vcpkg pull request #31439
Opened 2023-05-15 09:00 UTC by JonLiu1993

Fixes vcpkg pipeline issue: https://dev.azure.com/vcpkg/public/_build/results?buildId=89455&view=results
````
/mnt/vcpkg-ci/installed/x64-android/debug/lib/libbrotlidec-static.a  /mnt/vcpkg-ci/installed/x64-android/debug/lib/libbrotlicommon-static.a  /mnt/vcpkg-ci/installed/x64-android/debug/lib/libbz2d.a  /mnt/vcpkg-ci/installed/x64-android/debug/lib/liblz4d.a  /mnt/vcpkg-ci/installed/x64-android/debug/lib/libsnappy.a  /mnt/vcpkg-ci/installed/x64-android/debug/lib/libz.a  /mnt/vcpkg-ci/installed/x64-android/debug/lib/libzstd.a  -pthread  -lrt  -latomic -lm && :
ld: error: unable to find library -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

````
````
PASSING, REMOVE FROM FAIL LIST: arrow:x64-android
PASSING, REMOVE FROM FAIL LIST: arrow:arm64-android
````
Remove `-lrt` for Android:
````
-if(NOT WIN32 AND NOT APPLE)
+if(NOT WIN32 AND NOT APPLE AND NOT ANDROID)
   # Pass -lrt on Linux only
   list(APPEND ARROW_SYSTEM_LINK_LIBS rt)
 endif()
````

Remove this code from ci.baseline.txt:
````
arrow:arm64-android=fail
arrow:x64-android=fail
````

2023-05-15 10:23 UTC, dg0yt commented
So arrow builds now for android, but vcpkg-ci-arrow fails? 
Then please fix arrow so that vcpkg-ci-arrow succeeds, too. Because this verifies that arrow is actually usable.

2023-05-15 10:34 UTC, FrankXie05 requested changes, later dismissed

2023-05-15 10:34 UTC, FrankXie05 commented on scripts/ci.baseline.txt
> +vcpkg-ci-arrow:arm64-android=fail
```suggestion
vcpkg-ci-arrow:x64-android=fail
vcpkg-ci-arrow:arm64-android=fail
```
We need to fix it instead of skipping.

2023-05-15 10:39 UTC, JonLiu1993 commented on scripts/ci.baseline.txt
> +vcpkg-ci-arrow:arm64-android=fail
We currently do not have a repro environment to reproduce the error.

2023-05-15 10:51 UTC, dg0yt commented on scripts/ci.baseline.txt
> +vcpkg-ci-arrow:arm64-android=fail
Of couse you have the repro:
~~~
vcpkg install --overlay-ports=scripts/test-ports vcpkg-ci-arrow
 ~~~

2023-05-15 10:54 UTC, FrankXie05 commented
"librt" refers to a library in the `Linux` system that provides functions related to real-time operation. If `vcpkg` does not provide it, it cannot be linked to on `android`.

2023-05-16 04:14 UTC, dg0yt commented
`glibc` isn't used on Android, but of course it does have it is `libc`.
`librt` can be  a system library on POSIX systems. But on Android it is integrated into `libc`. 
https://developer.android.com/ndk/guides/stable_apis#c_library 
Thus `-lrt` must be removed for Android.

2023-05-16 10:51 UTC, dg0yt commented
I don't know why you patch their CI scripts.
My attention would be here:
https://github.com/apache/arrow/blob/f6e447944f2a2ab108d5971daf351b7443bc96fb/cpp/CMakeLists.txt#L933-L936

2023-05-16 10:53 UTC, dg0yt commented on ports/arrow/vcpkg.json
> +  "supports": "android",
If you want to scope CI, you don't neet to touch the ABI-hashed manifest: You can change the "default" pattern here instead:
https://github.com/microsoft/vcpkg/blob/d4d39d71b3e6dd7536592c36ab2f7e84a8a64942/scripts/azure-pipelines/azure-pipelines.yml#L16-L19

Just remember to restore the original value before ready-for-review.

2023-05-19 05:43 UTC, LilyWangLL approved these changes

2023-05-22 00:52 UTC, merged