[alembic] update to 1.8.5
microsoft/vcpkg pull request #31456
Opened 2023-05-16 07:04 UTC by jimwang118

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-05-17 03:07 UTC, dg0yt commented on ports/alembic/disable-warnings-as-error.patch
> +-if (ALEMBIC_DEBUG_WARNINGS_AS_ERRORS AND "${CMAKE_BUILD_TYPE}" MATCHES "Debug" AND NOT MSVC)
Given th new `ALEMBIC_DEBUG_WARNINGS_AS_ERRORS` variable, is a patch still needed?

2023-05-17 06:34 UTC, jimwang118 commented on ports/alembic/disable-warnings-as-error.patch
> +-if (ALEMBIC_DEBUG_WARNINGS_AS_ERRORS AND "${CMAKE_BUILD_TYPE}" MATCHES "Debug" AND NOT MSVC)
This patch is really not needed, I will change it in the options.

2023-05-18 01:24 UTC, Adela0814 requested changes

2023-05-18 01:24 UTC, Adela0814 commented on ports/alembic/fix-runtime-destination.patch
> +
Please restore the ending character.

2023-05-18 02:10 UTC, Adela0814 approved these changes

2023-05-18 18:23 UTC, merged