port/cbc
microsoft/vcpkg pull request #31607
Opened 2023-05-24 11:34 UTC by jpfeuffer

2023-05-24 13:58 UTC, jpfeuffer commented
@Neumann-A Would you mind having a look here? You recently updated all coin recipes. I was trying to use the Buildtools autoconf files, like you did for all other recipes but it fails.

2023-05-24 15:57 UTC, Neumann-A commented
You need to figure out where the missing macros should come from and set ac_local accordingly.

2023-05-24 17:38 UTC, jpfeuffer commented
Hmm.. sorry but I don't know what you mean.
Honestly, I don't see a reason why this should fail while the other ports run through. It is essentially the same setup. Now even with the same configure options.

2023-05-24 18:39 UTC, jpfeuffer commented
Any idea how to get additional debug information from this incredibly obscure build system? Otherwise I think this out-of-scope for me. I unfortunately cannot invest the time to learn autoconf just for this.

2023-05-24 18:42 UTC, dg0yt commented
I started an attempt on building coinutils with the official buildsystem last year: #26524
This is from my notes.
~~~
# We cannot run autoreconf without providing extra coin-or build tools
# and the specific compatible version of autotools, cg.
# https://coin-or-tools.github.io/BuildTools/autotools#using-the-correct-version-of-the-autotools
# But we need to update key scripts for arm64-windows and uwp support.
~~~~

2023-05-25 02:18 UTC, jimwang118 requested changes

2023-05-25 02:18 UTC, jimwang118 commented on ports/coin-or-cbc/portfile.cmake
> +    ## PATCHES fix-c1083-error.patch
If the fix-c1083-error.patch is not applied to this port, please delete the patch file. Please remove extra blank lines in the file.

2023-05-25 02:18 UTC, jimwang118 commented on ports/coin-or-cbc/portfile.cmake
> +    ## PATCHES fix-c1083-error.patch
```suggestion
```

2023-05-25 02:18 UTC, jimwang118 commented on ports/coin-or-cbc/portfile.cmake
> +if(1)
The judgment condition here is always true, then the following branch will not enter. Whether content in the branch below should be deleted.

2023-05-25 02:18 UTC, jimwang118 commented on ports/coin-or-cbc/vcpkg.json
> +  "homepage": "https://github.com/coin-or/Cgl",
```suggestion
  "homepage": "https://github.com/coin-or/Cbc",
```

2023-05-25 02:18 UTC, jimwang118 commented on versions/c-/coin-or-cbc.json
> +  "versions": [
You should use the command: `./vcpkg x-add-version coin-or-cbc` to automatically generate this file instead of writing it manually.

2023-05-25 02:22 UTC, jimwang118 requested changes

2023-05-25 02:22 UTC, jimwang118 commented on ports/coin-or-cbc/portfile.cmake
> +    REF 133f1171f1667c930e46efd350f4be8ad995b231
```suggestion
    REF "releases/${VERSION}"
```

2023-05-25 02:23 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-05-25 07:58 UTC, jpfeuffer commented
Yes will do. waiting for some replies to see what the best way forward is and will remove things once decided.

2023-05-26 22:08 UTC, ilya-lavrenov commented on ports/coin-or-cbc/Config.cmake.in
> +find_dependency(CoinUtils REQUIRED)
it should not mention `REQUIRED`

2023-05-27 10:42 UTC, jpfeuffer commented on ports/coin-or-cbc/portfile.cmake
> +    REF 133f1171f1667c930e46efd350f4be8ad995b231
not possible. see other coin ports. on the release branch, autoconf is not compatible with vcpkg.

2023-05-27 10:48 UTC, jpfeuffer commented
I have NO IDEA at all why Windows fails. It's exactly the same setup as in the ports from @Neumann-A now.

2023-05-27 10:54 UTC, jpfeuffer commented on versions/c-/coin-or-cbc.json
> +  "versions": [
It *was* generated with that command but it still complains..

2023-05-27 11:10 UTC, jpfeuffer commented
Can someone try this on Windows and maybe help me finish this PR? I would very very much appreciate it.

2023-05-27 12:06 UTC, dg0yt commented
CI logs for x64-windows:
~~~
configure:17898: checking D:/downloads/tools/msys2/9a1ec3f33446b195/mingw32/bin/pkg-config.exe is at least version 0.16.0
configure:17902: result: yes: 0.29.2
configure:17938: D:/downloads/tools/msys2/9a1ec3f33446b195/mingw32/bin/pkg-config.exe path is "/D/installed/x64-windows/debug/lib/pkgconfig:D:/installed/x64-windows/debug/lib/pkgconfig/;D:/installed/x64-windows/debug/share/pkgconfig/"
configure:17949: checking for package CoinUtils
configure:18152: result: no
configure:18191: error: Required package CoinUtils is not available.
~~~
The file list says there is a `coinutils.pc`. I know windows file systems aren't case-sensitive, but maybe pkg-config looks at the directory entries. 
(But I see that [coin documentation](https://coin-or-tools.github.io/BuildTools/configure#check-for-packages) uses CamelCase.)

2023-05-28 08:20 UTC, jpfeuffer commented
Thanks a lot! Does anyone know why the pkconfig path is a weird mix of Unix and Windows paths? Especially with respect to the path separators ":" and ";"

2023-05-28 08:46 UTC, dg0yt commented
Does the port or package add a component to this path itself?
On windows there is context switching between msys and windows envirinments, including implicit conversion of parameters and environment variables which are assumed to be paths. msys is the unix environment in this game.

2023-06-03 13:13 UTC, dg0yt commented
> Does the port or package add a component to this path itself?

Yes, https://github.com/coin-or/Cbc/blob/600f7d1095fde2e1c6fc93ed54372880d420ff7b/configure#L17936:
~~~sh
  COIN_PKG_CONFIG_PATH="${expanded_libdir}/pkgconfig:${COIN_PKG_CONFIG_PATH}"
~~~
This doesn't consider pkg-config on windows which uses `;` to separate dirs.

2023-06-04 09:28 UTC, jpfeuffer commented
Good find! I guess a patch with an ifelse could work around this?

2023-06-04 10:28 UTC, dg0yt commented
I wouldn't mind to see it removed entirely. Don't pick anything from other coin-or locations before proper vcpkg packages.

2023-06-07 17:22 UTC, jpfeuffer commented
k, now it is looking for glpk since coinutils is always built with glpk and therefore COINUTILS_HAS_GLPK is active.

@dg0yt Is it possible to configure this package based on the enabled features in the dependency coinutils, after https://github.com/microsoft/vcpkg/pull/31739 was merged?

2023-06-07 18:14 UTC, dg0yt commented
.. which triplet?

2023-06-14 09:04 UTC, jpfeuffer commented
Ok, Windows x64 builds when deactivating glpk, which I do not plan to support as a feature for now.
Sorry, but I did not completely understand your suggestion @dg0yt and I think it would be a bigger change in this very complex build system. I linked an issue that I raised on the source repo, above.

Lastly I have for the Windows static builds:
`ar-lib: unknown action specified`

2023-06-14 18:17 UTC, dg0yt commented
> Ok, Windows x64 builds when deactivating glpk, which I do not plan to support as a feature for now. Sorry, but I did not completely understand your suggestion @dg0yt and I think it would be a bigger change in this very complex build system. I linked an issue that I raised on the source repo, above.

I don't mind if glpk is missing when the port is added.

> Lastly I have for the Windows static builds: `ar-lib: unknown action specified`

Can you try to add `USE_WRAPPERS` to `vcpkg_configure_make`? ATM it is not using the ar-lib  wrapper during configuration tests.

2023-06-14 22:24 UTC, jpfeuffer commented on ports/coin-or-cbc/portfile.cmake
> +#AUTOCONFIG
```suggestion
USE_WRAPPERS
```

2023-06-16 02:11 UTC, jimwang118 approved these changes, later dismissed

2023-06-16 02:38 UTC, LilyWangLL requested changes

2023-06-16 02:38 UTC, LilyWangLL commented on ports/coin-or-cbc/portfile.cmake
> +    --disable-readline
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
    USE_WRAPPERS
    OPTIONS
        --with-coinutils
        --with-clp
        --with-cgl
        --with-osi
        --without-ositests
        --without-sample
        --without-netlib
        --without-miplib3
        --enable-relocatable
        --disable-readline
```

2023-06-16 02:38 UTC, LilyWangLL commented on ports/coin-or-cbc/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2023-06-16 02:38 UTC, LilyWangLL commented on ports/coin-or-cbc/portfile.cmake
> +    PATCHES "dep.patch" "pkgconf_win.patch" "disable_glpk.patch"
```suggestion
    PATCHES
        dep.patch
        pkgconf_win.patch
        disable_glpk.patch
```

2023-06-16 02:38 UTC, LilyWangLL commented on ports/coin-or-cbc/vcpkg.json
> +  "version-date": "2023-02-01",
I saw the upstream has release version [releases/2.10.10](https://github.com/coin-or/Cbc/releases/tag/releases%2F2.10.10), why not use release version?

2023-06-16 02:39 UTC, LilyWangLL commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-06-16 06:16 UTC, jpfeuffer commented on ports/coin-or-cbc/vcpkg.json
> +  "version-date": "2023-02-01",
As far as I understood, it's too old to work with newer autoconf versions. I used the commit with the autoconf changes to the whole coinor ecosystem. They seem to have been applied on the same day for all coin packages, so it seemed fitting to use that commit here as well.

I think in the original PR for the revamping of the coinor packages this is explained better.

I also raised an issue at their repo and they said there is no release in sight, that we could wait for.

2023-06-16 07:37 UTC, dg0yt commented on ports/coin-or-cbc/vcpkg.json
> +  "version-date": "2023-02-01",
Hm, I'm lost in the the chickens and eggs...

The PR no longer uses the `AUTOCONFIG` parameter, so it is *not* meant to use `autoreconf` (autoconf).
There is a patch to `configure.ac` which doesn't have an effect without `autoreconf`. But it might trigger `autoreconf` from `make` if the patched `configure.ac` is newer than `configure`. I guess this only prevented by the patch to `configure`....

Long story short, isn't it possible to drop the patch to `configure.ac` and build the latest release?

BTW I think there should be `DETERMINE_BUILD_TRIPLET` if `AUTOCONFIG` isn't used. It is needed for cross-builds.

2023-06-16 09:49 UTC, jpfeuffer commented on ports/coin-or-cbc/vcpkg.json
> +  "version-date": "2023-02-01",
Hmm ok makes sense. I did not know how these files and tools work together. I mostly tried to replicate what was done for the other coinor ports.

I can certainly try this. Just a question, since this confused me as well:
Did you consider that these coinor ports including mine, checkout the coinor Buildtools port to get some additional scripts or something? It felt like this is another reason why not the latest release was chosen but I am not sure.
https://github.com/coin-or-tools/BuildTools

2023-06-28 11:45 UTC, jpfeuffer commented on ports/coin-or-cbc/vcpkg.json
> +  "version-date": "2023-02-01",
Ok I added back AUTOCONFIG but I think all the patches are needed. One fixes paths on windows, another allows inclusion of additional macros from the buildtools package and the last one disables glpk.
I don't think that can be solved by going back to an even older codebase. Keep in mind that this package heavily depends on other coin-or packages and all of them are built from this specific point in time when the coin-or team updated their configure scripts.
Maybe @Neumann-A can comment a bit more on the reasons.

2023-06-28 12:28 UTC, jpfeuffer commented
Keeping logs:
With AUTOCONFIG + dep.patch for configure.ac:

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I "/mnt/vcpkg-ci/buildtrees/coin-or-cbc/src/970c621a3b-821838d561.clean/BuildTools" --force 
aclocal: error: couldn't open directory 'm4': No such file or directory
autoreconf: error: aclocal failed with exit status: 1
```

2023-06-28 13:32 UTC, dg0yt commented
To make it clear, I suggest the combination of:  
not AUTOCONFIG
DETERMINE_BUILD_TRIPLET
not patching configure.ac

2023-06-28 14:58 UTC, jpfeuffer commented
Can someone retrigger stalled CI?

2023-06-30 09:18 UTC, LilyWangLL approved these changes

2023-07-05 11:01 UTC, jpfeuffer commented
Hi! I was wondering if there is something missing. In any case, just bumping so this won't be forgotten.

2023-07-05 19:10 UTC, merged

2023-07-05 22:21 UTC, jpfeuffer commented
Great! I want to thank everyone here for their help and that project in general!