[cppzmq] draft dependency update
microsoft/vcpkg pull request #31624
Opened 2023-05-25 08:36 UTC by recsater

cppzmq[draft] must need zeromq[draft] but it was not included.

2023-05-25 08:37 UTC, recsater commented
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

2023-05-25 09:55 UTC, FrankXie05 requested changes

2023-05-25 09:55 UTC, FrankXie05 commented on ports/cppzmq/vcpkg.json
> +      ]
```suggestion
      "description": "Build and install draft",
      "dependencies": [
        {
          "name": "zeromq",
          "default-features": false,
          "features": [
              "draft"
          ]
        }
      ]
```
If only depend on feature `zeromq[draft]` then other features should be disabled to reduce build time.

2023-05-25 09:56 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2023-05-26 02:35 UTC, FrankXie05 approved these changes

2023-05-26 20:43 UTC, merged