[crossguid] Fix compilation on gcc v13
microsoft/vcpkg pull request #31835
Opened 2023-06-05 16:48 UTC by alexdewar

Crossguid no longer compiles with gcc v13 (tested on Linux), due to a missing include (cstdint). There is an upstream pull request to fix the issue which has been open for some time but not yet merged.

Let's patch the sources in vcpkg until upstream fixes it.

Fixes #31834.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-06-05 17:18 UTC, alexdewar commented
@microsoft-github-policy-service agree company="Imperial College London"

2023-06-06 06:40 UTC, Adela0814 requested changes

2023-06-06 06:40 UTC, Adela0814 commented on ports/crossguid/missing-include-cstdint.patch
> +
Please remove these useless codes, thanks.

2023-06-06 06:47 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-06-06 09:14 UTC, alexdewar commented on ports/crossguid/missing-include-cstdint.patch
> +
Done

2023-06-07 02:49 UTC, Adela0814 approved these changes

2023-06-07 16:45 UTC, merged