[flashlight-text] New port
microsoft/vcpkg pull request #31859
Opened 2023-06-06 16:28 UTC by jacobkahn

2023-06-07 02:22 UTC, jimwang118 requested changes

2023-06-07 02:22 UTC, jimwang118 commented on ports/flashlight-text/vcpkg.json
> +    }
```suggestion
    }
```

2023-06-07 02:22 UTC, jimwang118 commented on ports/flashlight-text/portfile.cmake
> +    REF v0.0.3
```suggestion
    REF "v${VERSION}"
```

2023-06-07 02:22 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-06-07 07:10 UTC, dg0yt commented on ports/flashlight-text/portfile.cmake
> +  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON # flashlight-text doesn't explicitly export symbols
[Do not add CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.](https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-add-cmake_windows_export_all_symbols)

2023-06-07 07:11 UTC, jimwang118 submitted a review, later dismissed

2023-06-07 19:19 UTC, jacobkahn commented on ports/flashlight-text/portfile.cmake
> +  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON # flashlight-text doesn't explicitly export symbols
Removing upstream -- will update PR.

2023-06-07 20:46 UTC, jacobkahn commented on ports/flashlight-text/portfile.cmake
> +  -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON # flashlight-text doesn't explicitly export symbols
https://github.com/flashlight/text/pull/70

2023-06-08 02:31 UTC, jimwang118 commented on ports/flashlight-text/portfile.cmake
> +
`vcpkg_cmake_config_fixup(CONFIG_PATH share/${PORT}/cmake)`
Add the above statement and modify the path of the `${PORT}-config` file.
When I use the following `cmake` statement to call this port, the following error occurs during compilation.
```
find_package(flashlight-text CONFIG REQUIRED)
target_link_libraries(testflashlight-text PRIVATE flashlight::flashlight-text flashlight::flashlight-text-kenlm)
```
```
Error		CMake Error at testflashlight-text/CMakeLists.txt:9 (target_link_libraries):
  Target "testflashlight-text" links to:

    flashlight::flashlight-text

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		F:\testwork\testflashlight-text\testflashlight-text/CMakeLists.txt	9
```

2023-06-08 03:25 UTC, dg0yt commented on ports/flashlight-text/portfile.cmake
> +)
Move these flags directly to `vcpkg_cmake_configure`.

2023-06-08 03:25 UTC, dg0yt commented on ports/flashlight-text/portfile.cmake
> +    kenlm FL_TEXT_USE_KENLM
Indent after keywords:
~~~cmake
vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        kenlm FL_TEXT_USE_KENLM
)

2023-06-08 03:25 UTC, dg0yt commented on ports/flashlight-text/portfile.cmake
> +)
Indent after keywords:
~~~cmake:
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FL_TEXT_DEFAULT_VCPKG_CMAKE_FLAGS}
        ${FEATURE_OPTIONS}
)

2023-06-08 04:12 UTC, jacobkahn commented on ports/flashlight-text/portfile.cmake
> +
The config was being installed to the incorrect location. Fix is ready for review.

2023-06-08 04:23 UTC, dg0yt commented on ports/flashlight-text/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME ${PORT})
`${PORT}` is the default `PACKAGE_NAME`. Omit it.

2023-06-08 08:21 UTC, jimwang118 commented
All features passed with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```
Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

2023-06-08 17:00 UTC, merged