Soem version date
microsoft/vcpkg pull request #31889
Opened 2023-06-08 10:52 UTC by omarhogni

Fixes https://github.com/OpenEtherCATsociety/SOEM/issues/707

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-06-09 02:55 UTC, FrankXie05 requested changes

2023-06-09 02:55 UTC, FrankXie05 commented on ports/soem/vcpkg.json
> +  "version-date": "2022-12-02",
```suggestion
  "version-date": "2023-06-09",
```
The data here refers to the date when vcpkg updated this port to ensure when we have modified it.

2023-06-09 02:55 UTC, FrankXie05 commented on ports/soem/portfile.cmake
>  vcpkg_cmake_configure(
We don't build `TEST`. Please add option `BUILD_TESTS=OFF`.

2023-06-09 02:56 UTC, FrankXie05 commented on ports/soem/portfile.cmake
> -        disable-werror.patch
Upstream has been fixed the patches.

2023-06-09 02:56 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2023-06-09 10:37 UTC, omarhogni commented on ports/soem/portfile.cmake
> -        disable-werror.patch
I misunderstood the winpcap patch and have added it again.

Regarding the werror patch it looks like it was added when CI pipelines for vcpkg were updated to ubuntu 20.04 and look to no longer be required.

2023-06-09 11:49 UTC, dg0yt commented
> Regarding the werror patch it looks like it was added when CI pipelines for vcpkg were updated to ubuntu 20.04 and look to no longer be required.

Please restore the patch. werror is a tool for a particular build environment of upstream developers, but not for general build recipes which may face different (incl. future) environments, facing unexpected warnings incl. false positives.

2023-06-12 09:28 UTC, omarhogni commented
> > Regarding the werror patch it looks like it was added when CI pipelines for vcpkg were updated to ubuntu 20.04 and look to no longer be required.
> 
> Please restore the patch. werror is a tool for a particular build environment of upstream developers, but not for general build recipes which may face different (incl. future) environments, facing unexpected warnings incl. false positives.

Added back werror patch.

2023-06-13 02:39 UTC, FrankXie05 approved these changes

2023-06-14 03:51 UTC, merged