[openscap] update to 1.3.6
microsoft/vcpkg pull request #31917
Opened 2023-06-10 04:48 UTC by jiayuehua

…Jon/openscap

2023-06-12 06:07 UTC, Adela0814 requested changes

2023-06-12 06:07 UTC, Adela0814 commented on ports/openscap/vcpkg.json
> +  "version": "1.3.6",
The latest version is 1.3.7, please update to [1.3.7](https://github.com/OpenSCAP/openscap/releases/tag/1.3.7). Thanks.

2023-06-12 06:07 UTC, Adela0814 commented on ports/openscap/portfile.cmake
> +    REF 3eccd5c064b9b152fe14a95b3534c60e003be17f #1.3.6
```suggestion
    REF $VERSION
```

2023-06-12 06:07 UTC, Adela0814 commented on ports/openscap/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING")
```

2023-06-12 06:08 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-06-13 06:17 UTC, jiayuehua commented
@Adela0814 I have summit my change.

2023-06-13 09:37 UTC, Adela0814 commented
@jiayuehua  I encountered an error while testing the feature.
Repro step:` .\vcpkg.exe install openscap[*]:x64-windows`

Error message:
```
E:\4\vcpkg\buildtrees\openscap\src\1.3.7-278c0d1b45.clean\src\OVAL\probes\crapi\digest.c(30): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
E:\4\vcpkg\buildtrees\openscap\src\1.3.7-278c0d1b45.clean\src\OVAL\probes\crapi\md5.c(30): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11733262/install-x64-windows-dbg-out.log)

2023-06-14 02:06 UTC, Adela0814 approved these changes

2023-06-14 02:07 UTC, Adela0814 commented
Tested all feature on the following triplets:

- x64-windows
- x64-windows-static
- x86-windows

2023-06-14 02:10 UTC, merged

2023-06-14 05:47 UTC, dg0yt commented on ports/openscap/vcpkg.json
> -        }
Why did the PR remove the `util` feature? It may break users of the port.

2023-06-14 05:47 UTC, dg0yt commented on ports/openscap/vcpkg.json
>    "description": "The oscap program is a command line tool that allows users to load, scan, validate, edit, and export SCAP documents.",
And the port is even described as "command line tool".

2023-06-14 09:12 UTC, jiayuehua commented on ports/openscap/vcpkg.json
> -        }
#31982