[pcre2] Update to version 10.42 and fix CMake integration.
microsoft/vcpkg pull request #31928
Opened 2023-06-10 14:37 UTC by teo-tsirpanis

This PR updates the version of the `pcre2` port to the latest released, and applies the patch in PCRE2Project/pcre2#260, to fix the previously broken CMake integration.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-06-10 14:53 UTC, dg0yt commented
Please mark this as draft.

2023-06-10 15:04 UTC, dg0yt commented
I opened #31929 now to ensure that the pristine update doesn't cause any regressions.

I realize now that the CMake config may be underused (or even unused) in vcpkg (or in general) because we didn't install it due to its poor state. So this PR will probably not give the insight I was hoping for.

2023-06-11 12:39 UTC, teo-tsirpanis commented
Some ports break because they were searching for the PCRE2 library in `lib`. 😭 https://github.com/pocoproject/poco/blob/a00bfbe89fccabbe3606b31c0a1c7edd3da14e2e/cmake/FindPCRE2.cmake#L69-L77

2023-06-11 13:37 UTC, dg0yt commented
> Some ports break because they were searching for the PCRE2 library in `lib`. sob https://github.com/pocoproject/poco/blob/a00bfbe89fccabbe3606b31c0a1c7edd3da14e2e/cmake/FindPCRE2.cmake#L69-L77

`find_library` breaking in *vendored* Find modules is unrelated to adding *official* exported CMake config to pcre2.
Port poco doesn't even use this Find module, see patch `ports/poco/0007-find-pcre2.patch`.

2023-06-11 13:38 UTC, dg0yt commented on ports/pcre2/portfile.cmake
> -
Don't remove this. It causes the build errors. Nobody is using the new CMake config, and some will never do.

2023-06-12 23:27 UTC, teo-tsirpanis commented on ports/pcre2/portfile.cmake
> -
Fixed. `qt5-websockets` fails, will investigate tomorrow. And I will also rebase the PR.

2023-06-13 02:01 UTC, LilyWangLL requested changes

2023-06-13 02:03 UTC, LilyWangLL commented
Thanks for your PR. PR https://github.com/microsoft/vcpkg/pull/31929 did update `pcre2` to 10.42, it has been merged, please resolve the conflicts.

2023-06-30 17:41 UTC, SamuelMarks commented
Any progress here? - Really need PCRE2 for my project (porting libbsd to Windows)

2023-06-30 18:21 UTC, teo-tsirpanis commented
I am waiting for it to get merged upstream in  PCREProject/pcre2#260.

2023-08-30 07:15 UTC, BurningEnlightenment commented on ports/pcre2/portfile.cmake
> -
You can refactor this to use [`vcpkg_replace_string`](https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_replace_string)

2023-09-08 04:15 UTC, BillyONeal reviewed
I fixed the problem that caused every line to be edited; there was an accidental LF -> CRLF in there.

2023-09-08 04:15 UTC, BillyONeal commented on ports/pcre2/portfile.cmake
> +        -DCMAKE_DISABLE_FIND_PACKAGE_BZip2=ON
Can you explain what this part of the change is doing?

2023-09-08 06:21 UTC, LilyWangLL requested changes

2023-09-08 06:21 UTC, LilyWangLL commented on ports/pcre2/usage
> +    target_link_libraries(main PRIVATE pcre2::8BIT pcre2::POSIX)
Usage test failed with the following error:
```
1> [CMake] CMake Error at PRreview/CMakeLists.txt:14 (target_link_libraries):
1> [CMake]   Target "PRreview" links to:
1> [CMake]     pcre2::8BIT
1> [CMake]     pcre2::POSIX
1> [CMake] 
1> [CMake]   but the target was not found.
```

2023-09-08 11:29 UTC, teo-tsirpanis commented on ports/pcre2/portfile.cmake
> +        -DCMAKE_DISABLE_FIND_PACKAGE_BZip2=ON
BZip2 and Zlib are used by the `pcre2grep` program which was disabled by the line just above.

2023-09-08 17:10 UTC, teo-tsirpanis commented on ports/pcre2/usage
> +    target_link_libraries(main PRIVATE pcre2::8BIT pcre2::POSIX)
`pcre2` was in all caps, fixed, let's see…

2023-09-11 10:14 UTC, LilyWangLL approved these changes

2023-09-20 12:27 UTC, teo-tsirpanis commented
Can we merge it?

2023-09-22 18:35 UTC, merged