Updating alpaca to latest release in github
microsoft/vcpkg pull request #31949
Opened 2023-06-12 15:03 UTC by sdavtaker

If this PR updates an existing port, please uncomment and fill out this checklist:

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-06-12 15:05 UTC, sdavtaker commented
@microsoft-github-policy-service agree

2023-06-13 02:32 UTC, jimwang118 requested changes

2023-06-13 02:32 UTC, jimwang118 commented on ports/alpaca/portfile.cmake
> +    REF v0.2.1
```suggestion
    REF "v${VERSION}"
```

2023-06-13 02:33 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-06-14 02:04 UTC, jimwang118 commented
You need to re-run this command: `./vcpkg x-add-version {portname} --overwirte-version` and then submit the result.

2023-06-14 04:01 UTC, sdavtaker commented
Rerun the version with overwrite this time.

2023-06-14 05:49 UTC, jimwang118 approved these changes

2023-06-14 06:32 UTC, jimwang118 commented
Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

2023-06-14 19:13 UTC, merged