[flycv] new port flycv 1.2
microsoft/vcpkg pull request #31986
Opened 2023-06-14 10:02 UTC by sdcb

fix https://github.com/PaddlePaddle/FlyCV/issues/137

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

**This is a new port:**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-06-14 17:22 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++    "${CMAKE_INSTALL_PREFIX}/include/version.h")
Hm, I don't think we want a global `version.h`. Should the includes go to `${CMAKE_INSTALL_PREFIX}/include/flycv` instead?

2023-06-14 17:22 UTC, dg0yt commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
These libs are available as vcpkg ports.

2023-06-15 00:10 UTC, sdcb commented on ports/flycv/int64_and_install.patch
> ++    "${CMAKE_INSTALL_PREFIX}/include/version.h")
You're right, I renamed into flycv_version.h

2023-06-15 00:12 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
I understand, however official flycv using static link to these 3 packages even in dynamic link compilation, so I feel like it's a good idea to keep these 3 self-contained packages.

2023-06-15 05:40 UTC, dg0yt commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
AFAICT this is not acceptable in the vcpkg registry. It limits what can be used together, and it ignores patches and security updates. Basically, getting rid of unmaintained vendored copies is one of the key benefits of package managers.

2023-06-15 06:48 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
I see, is it possible to link to static library even it's building dynamic lib?
@TomasRan can you help me migrate to external maintained in this vcpkg flycv port?

2023-06-15 07:11 UTC, dg0yt commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
> I see, is it possible to link to static library even it's building dynamic lib?

Why do you want to do that, i.e. which problem do you want to solve?

2023-06-15 07:25 UTC, dg0yt commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
So IIUC you need help with a patch (or better: upstream support for external dependencies).

2023-06-15 07:28 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
Yes, remove all external dependencies would need a patch, I tried but somehow not working, @TomasRan is the upstream maintainer.

2023-06-15 07:31 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
Here is the updated patch that I tried:

```int64_and_install.patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 097f8e3..86eec04 100755
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -79,18 +79,18 @@ endif(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
 
 configure_file(
     "${PROJECT_SOURCE_DIR}/include/flycv_namespace.h.in"
-    "${CMAKE_INSTALL_PREFIX}/flycv/include/flycv_namespace.h")
+    "${CMAKE_INSTALL_PREFIX}/include/flycv_namespace.h")
 
 configure_file(
     "${PROJECT_SOURCE_DIR}/include/version.h.in"
-    "${CMAKE_INSTALL_PREFIX}/flycv/include/version.h")
+    "${CMAKE_INSTALL_PREFIX}/include/flycv_version.h")
 
 # add modules
 add_subdirectory(modules)
 
 configure_file(
     "${PROJECT_SOURCE_DIR}/include/flycv.h.in"
-    "${CMAKE_INSTALL_PREFIX}/flycv/include/flycv.h")
+    "${CMAKE_INSTALL_PREFIX}/include/flycv.h")
 
 # ============================ Unit Test ==================================
 # Add gtest
diff --git a/cmake/FCVFindDependencies.cmake b/cmake/FCVFindDependencies.cmake
index ca85c85..3c76abf 100755
--- a/cmake/FCVFindDependencies.cmake
+++ b/cmake/FCVFindDependencies.cmake
@@ -5,15 +5,19 @@ if(BUILD_FCV_MEDIA_IO)
     if(WITH_FCV_IMGCODECS)
         # Build with jpeg
         if(WITH_LIB_JPEG_TURBO)
-            include(external/libjpeg-turbo)
+            find_package(libjpeg-turbo CONFIG REQUIRED)
+            target_link_libraries(${FCV_TARGET_NAME} libjpeg-turbo::turbojpeg)
+            include_directories(${})
             add_definitions(-DWITH_LIB_JPEG_TURBO)
         endif(WITH_LIB_JPEG_TURBO)
 
         # Build with libpng.
         if(WITH_LIB_PNG)
-            include(external/libpng)
-            include(external/zlib)
-            add_dependencies(libpng zlib)
+            find_package(ZLIB REQUIRED)
+            target_link_libraries(${FCV_TARGET_NAME} ZLIB::ZLIB)
+            find_package(PNG REQUIRED)
+            target_link_libraries(${FCV_TARGET_NAME} PNG::PNG)
+            include_directories(${ZLIB_INCLUDE_DIR})
             add_definitions(-DWITH_LIB_PNG)
         endif(WITH_LIB_PNG)
     endif(WITH_FCV_IMGCODECS)
diff --git a/cmake/platform/windows/windows.cmake b/cmake/platform/windows/windows.cmake
index 04d487a..2bcd83c 100755
--- a/cmake/platform/windows/windows.cmake
+++ b/cmake/platform/windows/windows.cmake
@@ -1,6 +1,4 @@
 add_compile_options(/W4)
-set(CMAKE_CXX_FLAGS_RELEASE /MD)
-set(CMAKE_CXX_FLAGS_DEBUG /MDd)
 set(CMAKE_CXX_STANDARD 11)
 
 if(CMAKE_BUILD_TYPE STREQUAL Release)
diff --git a/modules/CMakeLists.txt b/modules/CMakeLists.txt
index ee9b14f..75333ea 100755
--- a/modules/CMakeLists.txt
+++ b/modules/CMakeLists.txt
@@ -4,7 +4,7 @@ endif()
 
 include_directories(
     ${PROJECT_SOURCE_DIR}
-    ${CMAKE_INSTALL_PREFIX}/flycv/include
+    ${CMAKE_INSTALL_PREFIX}/include
 )
 
 get_subdir_list(FCV_ALL_MODULE_LIST ${CMAKE_CURRENT_SOURCE_DIR})
@@ -110,24 +110,13 @@ foreach(each_interface ${FCV_UNIVERSE_INTERFACES})
     install(FILES
         ${CMAKE_SOURCE_DIR}/${each_interface}
         DESTINATION
-        ${CMAKE_INSTALL_PREFIX}/flycv/include/${OUTPUT_INTERFACE_PATH}
+        ${CMAKE_INSTALL_PREFIX}/include/${OUTPUT_INTERFACE_PATH}
     )
 endforeach()
 
-install(TARGETS ${FCV_TARGET_NAME}
-    DESTINATION ${CMAKE_INSTALL_PREFIX}/flycv/${FCV_INSTALL_LIB_NAME})
+install(TARGETS ${FCV_TARGET_NAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
+install(TARGETS ${FCV_TARGET_NAME} LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
 
 if(BUILD_SHARED_LIBS AND (BUILD_TEST OR BUILD_BENCHMARK))
     install(TARGETS ${FCV_TARGET_NAME} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
 endif()
-
-foreach(item ${FCV_EXPORT_LIBS})
-    string(REGEX MATCH "\/" BLACKSLASH ${item})
-    if ("${BLACKSLASH}" STREQUAL "")
-        install(TARGETS ${item}
-            DESTINATION ${CMAKE_INSTALL_PREFIX}/flycv/${FCV_INSTALL_LIB_NAME})
-    else()
-        install(FILES ${item}
-            DESTINATION ${CMAKE_INSTALL_PREFIX}/flycv/${FCV_INSTALL_LIB_NAME})
-    endif()
-endforeach()
diff --git a/modules/img_transform/resize/src/resize_avx.cpp b/modules/img_transform/resize/src/resize_avx.cpp
index c9c8260..f167dde 100755
--- a/modules/img_transform/resize/src/resize_avx.cpp
+++ b/modules/img_transform/resize/src/resize_avx.cpp
@@ -13,6 +13,7 @@
 // limitations under the License.
 
 #include "modules/img_transform/resize/include/resize_avx.h"
+typedef int64_t __int64_t;
 
 #include <cmath>
 #include <immintrin.h>
diff --git a/modules/media_io/imgcodecs/src/imgcodecs_png.cpp b/modules/media_io/imgcodecs/src/imgcodecs_png.cpp
index 7214b49..458107c 100755
--- a/modules/media_io/imgcodecs/src/imgcodecs_png.cpp
+++ b/modules/media_io/imgcodecs/src/imgcodecs_png.cpp
@@ -15,7 +15,7 @@
 #include "modules/media_io/imgcodecs/include/imgcodecs_png.h"
 
 #ifdef WITH_LIB_PNG
-#include "third_party/libpng/png.h"
+#include "png.h"
 #endif
 
 G_FCV_NAMESPACE1_BEGIN(g_fcv_ns)
```

Here is the updated portfile.cmake I tried:
```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO PaddlePaddle/FlyCV
    REF "release/v1.2.0"
    SHA512 6f40f00f54a3d10da3f49a3c070e6cc8319c3d429d3fe4651e3ca1c55973d9610b64e05a5dec5a33dd8e6c7c293117a1d1b85e2833e07faebfd591f8fed3da14
    HEAD_REF develop
    PATCHES
        int64_and_install.patch
)

# vcpkg_from_github(
#     OUT_SOURCE_PATH JPEG_SOURCE_PATH
#     REPO libjpeg-turbo/libjpeg-turbo
#     REF 2.1.4
#     SHA512 d3e92d614168355827e0ed884ff847cc7df8f6f1fb7b673c6c99afdf61fdfc0372afe5d30fdbf5e743335e2a7a27ca9f510c67d213e5cb2315a8d946e9414575
#     HEAD_REF main
# )
# file(COPY ${JPEG_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/libjpeg-turbo)

# vcpkg_from_github(
#     OUT_SOURCE_PATH PNG_SOURCE_PATH
#     REPO glennrp/libpng
#     REF v1.6.39
#     SHA512 d61408cee5850582baa57166547ccab6cc171bc809076e53494ace26157fd7787c3209e3b757fd68c541bfb95afe309745d887fb5cd2005b2024af7355c809a0
#     HEAD_REF main
# )
# file(COPY ${PNG_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/libpng)

# vcpkg_from_github(
#     OUT_SOURCE_PATH ZLIB_SOURCE_PATH
#     REPO madler/zlib
#     REF v1.2.9
#     SHA512 c38fee5a729cf57801b04d64d10c3727a4732dd47c69d9d107bc862a2e66012afdff07c2e2829d3b7b4337a31e65cc8f921a5a8a23a7e12c6730b2cbb0b9a7c7
#     HEAD_REF main
# )
# file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)

.... else is same 
```

2023-06-15 07:42 UTC, dg0yt commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
It is going into the right direction.

> ```diff
>          if(WITH_LIB_JPEG_TURBO)
> -            include(external/libjpeg-turbo)
> +            find_package(libjpeg-turbo CONFIG REQUIRED)
> +            target_link_libraries(${FCV_TARGET_NAME} libjpeg-turbo::turbojpeg)
> +            include_directories(${})
> ```

You need to follow how the external stuff is fed into the other parts.
https://github.com/PaddlePaddle/FlyCV/blob/426e7a8eb5640f51cc277f2ed0fa3b23821b8f64/cmake/external/libjpeg-turbo.cmake#L80-L87
So probably (untested):
~~~diff
         if(WITH_LIB_JPEG_TURBO)
-            include(external/libjpeg-turbo)
+            find_package(libjpeg-turbo CONFIG REQUIRED)
+            list(APPEND FCV_LINK_DEPS libjpeg-turbo::turbojpeg)
~~~
... and the include directories should already come with the target when it is used.

Similar for libpng. You don't need to deal with zlib if it is only a transitive dependency of libpng.
(And it goes without saying that you have to add the dependencies to vcpkg.json.)

2023-06-15 08:08 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
Good spot, it make sense to me, I'll make a try, thanks!

2023-06-15 08:15 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-06-15 15:02 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
Thanks, I can confirm `target_link_libraries(${FCV_TARGET_NAME} libjpeg-turbo::turbojpeg)` this is working, but I don't know how to write libpng, it seems this is not correct: `list(APPEND FCV_LINK_DEPS libpng16::libpng)`, but I don't know the rule.

2023-06-16 01:10 UTC, sdcb commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
If I write:
```cmake
if(WITH_LIB_PNG)
    find_package(PNG REQUIRED)
    list(APPEND FCV_LINK_DEPS libpng)
    target_link_libraries(${FCV_TARGET_NAME} PNG::PNG)
    include_directories(${PNG_PNG_INCLUDE_DIR})
    add_definitions(-DWITH_LIB_PNG)
endif(WITH_LIB_PNG)
```

Output is:
```
[1/2] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=modules\CMakeFiles\flycv_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x86\link.exe  @CMakeFiles\flycv_shared.rsp  /out:modules\flycv_shared.dll /implib:modules\flycv_shared.lib /pdb:modules\flycv_shared.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  && cd ."
FAILED: modules/flycv_shared.dll modules/flycv_shared.lib 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=modules\CMakeFiles\flycv_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x86\link.exe  @CMakeFiles\flycv_shared.rsp  /out:modules\flycv_shared.dll /implib:modules\flycv_shared.lib /pdb:modules\flycv_shared.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x86\link.exe @CMakeFiles\flycv_shared.rsp /out:modules\flycv_shared.dll /implib:modules\flycv_shared.lib /pdb:modules\flycv_shared.pdb /dll /version:0.0 /machine:X86 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:modules\CMakeFiles\flycv_shared.dir/intermediate.manifest modules\CMakeFiles\flycv_shared.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'libpng.lib'

ninja: build stopped: subcommand failed.
```

If I write:
```cmake
if(WITH_LIB_PNG)
    find_package(PNG REQUIRED)
    # list(APPEND FCV_LINK_DEPS libpng)
    target_link_libraries(${FCV_TARGET_NAME} PNG::PNG)
    include_directories(${PNG_PNG_INCLUDE_DIR})
    add_definitions(-DWITH_LIB_PNG)
endif(WITH_LIB_PNG)
```

Then output is:
```
[113/114] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=modules\CMakeFiles\flycv_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x86\link.exe  @CMakeFiles\flycv_shared.rsp  /out:modules\flycv_shared.dll /implib:modules\flycv_shared.lib /pdb:modules\flycv_shared.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  && cd ."
FAILED: modules/flycv_shared.dll modules/flycv_shared.lib 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=modules\CMakeFiles\flycv_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x86\link.exe  @CMakeFiles\flycv_shared.rsp  /out:modules\flycv_shared.dll /implib:modules\flycv_shared.lib /pdb:modules\flycv_shared.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x86\link.exe @CMakeFiles\flycv_shared.rsp /out:modules\flycv_shared.dll /implib:modules\flycv_shared.lib /pdb:modules\flycv_shared.pdb /dll /version:0.0 /machine:X86 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:modules\CMakeFiles\flycv_shared.dir/intermediate.manifest modules\CMakeFiles\flycv_shared.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library modules\flycv_shared.lib and object modules\flycv_shared.exp
imgcodecs_png.cpp.obj : error LNK2019: unresolved external symbol _png_image_begin_read_from_memory referenced in function "class fcv::Mat __cdecl fcv::imdecode_png(unsigned char const *,unsigned int)" (?imdecode_png@fcv@@YA?AVMat@1@PBEI@Z)
imgcodecs_png.cpp.obj : error LNK2019: unresolved external symbol _png_image_finish_read referenced in function "class fcv::Mat __cdecl fcv::imdecode_png(unsigned char const *,unsigned int)" (?imdecode_png@fcv@@YA?AVMat@1@PBEI@Z)
imgcodecs_png.cpp.obj : error LNK2019: unresolved external symbol _png_image_free referenced in function "class fcv::Mat __cdecl fcv::imdecode_png(unsigned char const *,unsigned int)" (?imdecode_png@fcv@@YA?AVMat@1@PBEI@Z)
imgcodecs_png.cpp.obj : error LNK2019: unresolved external symbol _png_image_write_to_memory referenced in function "bool __cdecl fcv::imencode_png(class fcv::Mat const &,class std::vector<unsigned char,class std::allocator<unsigned char> > &)" (?imencode_png@fcv@@YA_NABVMat@1@AAV?$vector@EV?$allocator@E@std@@@std@@@Z)

modules\flycv_shared.dll : fatal error LNK1120: 4 unresolved externals

ninja: build stopped: subcommand failed.
```

I don't know how to troubleshoot.

2023-06-16 05:25 UTC, dg0yt commented on ports/flycv/portfile.cmake
> +file(COPY ${ZLIB_SOURCE_PATH}/ DESTINATION ${SOURCE_PATH}/third_party/zlib)
Hm, AFAICS you didn't follow the pattern...
1. find_package(<package_name> REQUIRED)
2. list(APPEND FCV_LINK_DEPS <target>)
3. add_definitions(-D\<flycv_macro>)

i.e.
~~~cmake
if(WITH_LIB_PNG)
    find_package(PNG REQUIRED)
    list(APPEND FCV_LINK_DEPS PNG::PNG)
    add_definitions(-DWITH_LIB_PNG)
endif(WITH_LIB_PNG)

2023-06-16 05:33 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++            target_link_libraries(${FCV_TARGET_NAME} libjpeg-turbo::turbojpeg)
I don't think this `target_link_libraries` is needed. The project uses the link libraries from `FCV_LINK_DEPS`.

2023-06-16 05:33 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++install(TARGETS ${FCV_TARGET_NAME} LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
Please use a single command with three destinations:
~~~cmake
install(TARGETS ${FCV_TARGET_NAME}
    RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
    LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
    ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
)

2023-06-16 05:35 UTC, sdcb commented on ports/flycv/int64_and_install.patch
> ++            target_link_libraries(${FCV_TARGET_NAME} libjpeg-turbo::turbojpeg)
let me try

2023-06-16 05:46 UTC, sdcb commented
@dg0yt @jimwang118 Thank you all, vcpkg managed 3rd-party dependencies have already working, but still one question to ask, how to write usage? I'm not familiar with cmake before, should I write: 
```
The package flycv is compatible with built-in CMake targets:

    find_package(FLYCV REQUIRED)
    target_link_libraries(main PRIVATE FLYCV::FLYCV)
```

Or
```
flycv provides CMake targets for the flycv C/C++ API:

    find_package(flycv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE FLYCV::FLYCV)
```

How can I tell the different? Which one are correct in this case?

2023-06-16 05:50 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++            include_directories(${PNG_PNG_INCLUDE_DIR})
This line is pointless. The variable doesn't exist, and the include dir is already carried as a property of `PNG::PNG`.
That's the special power of CMake targets ;-)

2023-06-16 05:58 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++            list(APPEND FCV_LINK_DEPS libjpeg-turbo::turbojpeg)
Oops, found a problem in port libjpeg-turbo's usage. We need to use:
~~~cmake
list(APPEND FCV_LINK_DEPS $<IF:$<TARGET_EXISTS:libjpeg-turbo::turbojpeg>,libjpeg-turbo::turbojpeg,libjpeg-turbo::turbojpeg-static>
~~~

2023-06-16 06:11 UTC, sdcb commented on ports/flycv/int64_and_install.patch
> ++            include_directories(${PNG_PNG_INCLUDE_DIR})
Yes I also confirmed it's pointless, I removed and updated code, thanks.

2023-06-16 06:11 UTC, sdcb commented on ports/flycv/int64_and_install.patch
> ++            list(APPEND FCV_LINK_DEPS libjpeg-turbo::turbojpeg)
Not make any sense to me, but stuff still works LOL, thanks.

2023-06-16 06:23 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++            list(APPEND FCV_LINK_DEPS libjpeg-turbo::turbojpeg)
There is a different target name when libjpeg-turbo was installed with static linkage.
That's why we use this "generator expression" (`$<...>`): It chooses (`IF:..,...,...`) the actual target checks based on whether one particular target exists (`TARGET_EXISTS:...`).

2023-06-16 06:26 UTC, dg0yt commented on ports/flycv/int64_and_install.patch
> ++            list(APPEND FCV_LINK_DEPS libjpeg-turbo::turbojpeg)
Note: this was meant to be used instead of `list(APPEND FCV_LINK_DEPS libjpeg-turbo::turbojpeg)`.

2023-06-16 06:31 UTC, jimwang118 requested changes

2023-06-16 06:31 UTC, jimwang118 commented on ports/flycv/portfile.cmake
> +    REF "release/v1.2.0"
```suggestion
    REF "release/v${VERSION}"
```

2023-06-19 02:59 UTC, jimwang118 submitted a review, later dismissed

2023-06-19 03:49 UTC, sdcb commented
@jimwang118 @dg0yt Hi all, when can we merge this PR?

2023-06-19 05:43 UTC, jimwang118 commented
> @jimwang118 @dg0yt Hi all, when can we merge this PR?

There is no problem with compiling now. How can I use this library after compiling?

2023-06-19 05:59 UTC, sdcb commented
> There is no problem with compiling now. How can I use this library after compiling?

This part actually I don't know for `cmake`, but it works in `Visual Studio`, I also wants to check with you how to write usage file? I'm not familiar with cmake before, should I write(like libpng):
```
The package flycv is compatible with built-in CMake targets:

    find_package(FLYCV REQUIRED)
    target_link_libraries(main PRIVATE FLYCV::FLYCV)
```
Or (like libjpeg-turbo)

```
flycv provides CMake targets for the flycv C/C++ API:

    find_package(flycv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE FLYCV::FLYCV)
```
How can I tell the different? Which one are correct in this case?

2023-06-19 06:25 UTC, jimwang118 commented
> > There is no problem with compiling now. How can I use this library after compiling?
> 
> This part actually I don't know for `cmake`, but it works in `Visual Studio`, I also wants to check with you how to write usage file? I'm not familiar with cmake before, should I write(like libpng):
> 
> ```
> The package flycv is compatible with built-in CMake targets:
> 
>     find_package(FLYCV REQUIRED)
>     target_link_libraries(main PRIVATE FLYCV::FLYCV)
> ```
> 
> Or (like libjpeg-turbo)
> 
> ```
> flycv provides CMake targets for the flycv C/C++ API:
> 
>     find_package(flycv CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE FLYCV::FLYCV)
> ```
> 
> How can I tell the different? Which one are correct in this case?

This represents two usage modes of `find_package()`, one is the default module mode and the other is the config mode. You can check the `cmake` official website to understand this. For generating usage, you can check cmake's `install` syntax to complete the export usage.

2023-06-19 06:57 UTC, sdcb commented
After checked these details, but still no, I can't write a cmake usage file because still not make sense to me, upstream document also seems lack of these details: https://github.com/PaddlePaddle/FlyCV/wiki/Quick-Start

Can we merge without a usage since .lib/.dll already compiled and Visual Studio is working fine?

2023-06-21 06:50 UTC, sdcb commented
@jimwang118 @dg0yt I already added usage, please check and review.

2023-06-21 07:01 UTC, jimwang118 commented
> @jimwang118 @dg0yt I already added usage, please check and review.

The following error occurs when using the added usage.
```
Error		CMake Error at F:/flycv/scripts/buildsystems/vcpkg.cmake:853 (_find_package):
  By not providing "FindFLYCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FLYCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "FLYCV" with any of
  the following names:

    FLYCVConfig.cmake
    flycv-config.cmake

  Add the installation prefix of "FLYCV" to CMAKE_PREFIX_PATH or set
  "FLYCV_DIR" to a directory containing one of the above files.  If "FLYCV"
  provides a separate development package or SDK, be sure it has been
  installed.		F:/flycv/scripts/buildsystems/vcpkg.cmake	853	
```

2023-07-27 03:04 UTC, jimwang118 commented
@sdcb Thanks for your PR, Is work still being done for this PR?

2023-07-31 00:51 UTC, sdcb commented
> @sdcb Thanks for your PR, Is work still being done for this PR?

Actually no, I don't know how to write usage, I will delete the wrong usage file, request merge without usage.

2023-07-31 01:55 UTC, jimwang118 commented
The following error occurs when testing locally.
![image](https://github.com/microsoft/vcpkg/assets/122244446/f823e004-bd7c-4820-9f53-e5f9026d9449)

2023-07-31 03:40 UTC, sdcb commented
Hey @jimwang118 It seems I don't have such a line in your screenshot: `file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")`

it's test good in my side:
```powershell
PS C:\_\3rd\vcpkg> vcpkg install flycv:x64-windows --editable --binarysource=clear
Computing installation plan...
The following packages will be built and installed:
    flycv:x64-windows -> 1.2.0
Installing 1/1 flycv:x64-windows...
Building flycv:x64-windows...
-- Using cached PaddlePaddle-FlyCV-release_-v1.2.0.tar.gz.
-- Extracting source C:/_/3rd/vcpkg/downloads/PaddlePaddle-FlyCV-release_-v1.2.0.tar.gz
-- Applying patch int64_and_install.patch
-- Using source at C:/_/3rd/vcpkg/buildtrees/flycv/src/se_-v1.2.0-b36dbca405
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/_/3rd/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:44 (message):
  Could not find a matching pdb file for:

      C:/_/3rd/vcpkg/packages/flycv_x64-windows/bin/flycv_shared.dll
      C:/_/3rd/vcpkg/packages/flycv_x64-windows/debug/bin/flycv_shared.dll

Call Stack (most recent call first):
  ports/flycv/portfile.cmake:22 (vcpkg_copy_pdbs)
  scripts/ports.cmake:147 (include)

-- Installing: C:/_/3rd/vcpkg/packages/flycv_x64-windows/share/flycv/copyright
-- Performing post-build validation
Elapsed time to handle flycv:x64-windows: 1.3 min
Total install time: 1.3 min
```

2023-07-31 06:45 UTC, jimwang118 commented
`file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")` 
This line is not in your latest submitted `portfile.cmake`, you are checking the following.

2023-07-31 07:18 UTC, sdcb commented
> `file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")` This line is not in your latest submitted `portfile.cmake`, you are checking the following.

Sorry I don't get it, are you talking about an issue in an old version, but current version is good? 

I think my best concern is will you merge without the usage file? (Because I tested in Visual Studio it's works perfectly)

2023-08-24 05:11 UTC, dan-shaw commented
I think we need a working usage file for CMake users. @jimwang118 can you help?

2023-08-25 02:10 UTC, jimwang118 commented
> I think we need a working usage file for CMake users. @jimwang118 can you help?

The local compilation test has the following problems. I can help write cmake usage.
```
warning: /debug/share should not exist. Please reorganize any important files, then use
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
warning: There should be no absolute paths, such as the following, in an installed package:
    F:\flycv\packages\flycv_x64-windows
    F:\flycv\installed
    F:\flycv\buildtrees\flycv
    F:\flycv\downloads
Absolute paths were found in the following files:
    F:\flycv\packages\flycv_x64-windows\debug\share\flycv\flycv_sharedConfig-debug.cmake
    F:\flycv\packages\flycv_x64-windows\share\flycv\flycv_sharedConfig-release.cmake
error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: F:\flycv\ports\flycv\portfile.cmake
```

2023-11-17 02:18 UTC, jimwang118 commented
Thanks for your PR, Is work still being done for this PR?

2023-11-17 02:19 UTC, sdcb commented
@jimwang118 sadly nop, hmm maybe you should close this PR😂?

2023-11-17 08:10 UTC, jimwang118 commented
> @jimwang118 sadly nop, hmm maybe you should close this PR😂?

Then you can just close the PR.

2023-11-18 15:25 UTC, closed without merging