[opentelemetry-fluentd] Add new port
microsoft/vcpkg pull request #32063
Opened 2023-06-16 19:15 UTC by niande-xbox

Add opentelemetry-cpp-contrib's fluentd exporter.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [X] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says. (_I'm using vcpkg_install_copyright_)
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [X] Only one version is added to each modified port's versions file.

2023-07-03 10:41 UTC, LilyWangLL commented
There are the following warnings after building `opentelemetry-fluentd:x64-windows`, it is a `ONLY_STATIC_LIBRARY` port on windows, but it uses dynamic CRT.
```
-- Installing: E:/PRreview/opentele/packages/opentelemetry-fluentd_x64-windows/share/opentelemetry-fluentd/copyright
-- Performing post-build validation
warning: The following binaries should use the Dynamic Debug (/MDd) CRT.
    E:\PRreview\opentele\packages\opentelemetry-fluentd_x64-windows\debug\lib\opentelemetry_exporter_fluentd_logs.lib links with: Dynamic Release (/MD)
    E:\PRreview\opentele\packages\opentelemetry-fluentd_x64-windows\debug\lib\opentelemetry_exporter_fluentd_trace.lib links with: Dynamic Release (/MD)
To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
error: Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: E:\PRreview\opentele\ports\opentelemetry-fluentd\portfile.cmake
Stored binaries in 1 destinations in 1.3 s.
```

2023-07-03 11:13 UTC, Neumann-A commented on ports/opentelemetry-fluentd/portfile.cmake
> +        -DCMAKE_BUILD_TYPE=Release
This is wrong.

2023-07-03 11:14 UTC, Neumann-A commented on ports/opentelemetry-fluentd/portfile.cmake
> +        -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE
```suggestion
```

2023-07-04 02:56 UTC, LilyWangLL commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-07-06 03:01 UTC, LilyWangLL approved these changes

2023-07-06 03:06 UTC, LilyWangLL requested changes

2023-07-06 03:06 UTC, LilyWangLL commented on ports/opentelemetry-fluentd/portfile.cmake
> +
```suggestion
```
Since this port doesn't support windows, so here's codes could be removed.

2023-07-06 03:14 UTC, LilyWangLL commented on ports/opentelemetry-fluentd/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/${PORT})
I saw this port exports target file, but it doesn't install it. Could you please also fix it?
https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/20721e51235565020fc7fef2ba1aee92fc5744e8/exporters/fluentd/CMakeLists.txt#L192-L196C4

2023-07-06 04:19 UTC, dg0yt commented
> Added !windows in the supports - which should address this!

I can't see that  Windows is unsupported. AFAIU the problem was the portfile's overriding of the build type.

2023-07-07 03:03 UTC, LilyWangLL requested changes

2023-07-07 03:03 UTC, LilyWangLL commented on ports/opentelemetry-fluentd/portfile.cmake
> +        -DBUILD_EXAMPLE=OFF
The `CMakeLists.txt` in `fluentd` subdirectory doesn't use option `BUILD_EXAMPLE`, it has code [`add_subdirectory(example)`](https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/49a42a3bd950d3359f0b3921c13f6adc7cfc793a/exporters/fluentd/CMakeLists.txt#L91), so this option is useless.
```
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      BUILD_EXAMPLE

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.
```
If you want disable build example, you need add a patch as below:
```
if(0)
add_subdirectory(example)
endif()
```
Or add option `BUILD_EXAMPLE`:
```
if(BUILD_EXAMPLE)
add_subdirectory(example)
endif()
```

2023-07-07 04:24 UTC, LilyWangLL commented on ports/opentelemetry-fluentd/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/${PORT})
I saw your PR https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/297 has been merged, however, this change has not been synchronized with this PR. 

I tested the usage locally, and it still has some other issues like below error. It need add `include(CMakeFindDependencyMacro)` and `find_dependency` in `opentelemetry-fluentd-config.cmake`.
```
1> [CMake] CMake Error at E:/PRreview/vcpkg/installed/x64-windows/share/opentelemetry-fluentd/opentelemetry-fluentd-target.cmake:60 (set_target_properties):
1> [CMake]   The link interface of target "opentelemetry-fluentd::trace" contains:
1> [CMake] 
1> [CMake]     opentelemetry-cpp::api
1> [CMake] 
1> [CMake]   but the target was not found.  Possible reasons include:
```

2023-07-11 08:32 UTC, LilyWangLL commented
Please apply the following patch to `opentelemetry-fluentd`, which is a fix for the usage.
[fix-usage.patch](https://github.com/microsoft/vcpkg/files/12012470/fix-usage.patch)

2023-07-13 04:10 UTC, dg0yt commented
Well, co

> > Please apply the following patch to `opentelemetry-fluentd`, which is a fix for the usage. [fix-usage.patch](https://github.com/microsoft/vcpkg/files/12012470/fix-usage.patch)
> 
> Looking into whether this breaks anything because I don't see any explicit setting of opentelemetry-fluentd_FOUND like they had before.

It is probably still better than before:
In config mode, `<Pkg>_FOUND` is initialized to TRUE by CMake. `find_dependency` will add a relevant interaction with it.
The variable checks it did before the path aren't really useful, at least in the vcpkg port.

2023-07-14 02:46 UTC, LilyWangLL approved these changes

2023-07-14 02:47 UTC, LilyWangLL commented
Usage passed on x64-windows.

2023-07-14 05:59 UTC, LilyWangLL commented
> @LilyWangLL - are you able to merge on my behalf?

Pinging @vicroms @BillyONeal for response, this PR is ready to merge now.

2023-07-14 18:06 UTC, vicroms approved these changes

2023-07-14 23:19 UTC, BillyONeal commented
> [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.

I can't substantiate this. `opentelemetry-fluentd` doesn't appear on repology and I didn't get search hits either. Should this be a feature of `opentelemetry-cpp`, or of a new port `opentelemetry-contrib` instead?

2023-07-14 23:31 UTC, BillyONeal commented
Upon further reflection I realize now that the name starts with opentelemetry which matches close enough the org name `open-telemetry` so I think this is fine.

Thanks for the new port!

2023-07-14 23:31 UTC, merged