[concurrentqueue] Update to 1.0.4
microsoft/vcpkg pull request #32183
Opened 2023-06-23 12:04 UTC by RT2Code

Update concurrentqueue port from 1.0.3 to 1.0.4 : https://github.com/cameron314/concurrentqueue/releases/tag/v1.0.4

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-06-23 20:20 UTC, vicroms requested changes

2023-06-23 20:20 UTC, vicroms commented on ports/concurrentqueue/portfile.cmake
> +
```suggestion

```

This is no longer needed, the minimum version has been bumped in `vcpkg.cmake`.

2023-06-25 01:48 UTC, Adela0814 requested changes

2023-06-25 01:48 UTC, Adela0814 commented on ports/concurrentqueue/portfile.cmake
> +
Please remove the extra blank line.

2023-06-25 01:48 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-06-25 09:29 UTC, Adela0814 approved these changes

2023-06-27 05:11 UTC, vicroms approved these changes

2023-06-27 05:11 UTC, merged