Add new port nyan
microsoft/vcpkg pull request #32250
Opened 2023-06-27 01:22 UTC by duanqn

Fixes 32249

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-06-27 02:17 UTC, duanqn commented
Name should be nyan-lang

2023-06-30 08:09 UTC, duanqn commented
Let me figure out what this means

```
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    D:\packages\nyan-lang_x86-windows\bin\nyancat.exe

warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    D:\packages\nyan-lang_x86-windows\debug\bin\nyancat.exe
```

2023-06-30 08:27 UTC, duanqn commented
Hi @Adela0814 , how should I handle these exe files? Should I put them under tools\ instead of bin\ ?

2023-06-30 08:40 UTC, Adela0814 commented
> Hi @Adela0814 , how should I handle these exe files? Should I put them under tools\ instead of bin\ ?

Yes, please move the executable file to the `tools\`.

2023-07-04 06:14 UTC, duanqn commented
Will contact upstream for build failures

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +        -DFLEX_ROOT=${FLEX_PATH}
```suggestion
        "-DFLEX_ROOT=${FLEX_PATH}"
```

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +vcpkg_install_copyright(FILE_LIST ${SOURCE_PATH}/legal/GPLv3 ${SOURCE_PATH}/legal/LGPLv3 ${SOURCE_PATH}/copying.md)
```suggestion
vcpkg_install_copyright(
    FILE_LIST
        "${SOURCE_PATH}/copying.md"
        "${SOURCE_PATH}/legal/LGPLv3"
        "${SOURCE_PATH}/legal/GPLv3"
)

```

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +set(VERSION 0.1)
```suggestion
```

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +    REF v0.3
```suggestion
    REF "v${VERSION}"
```

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +get_filename_component(FLEX_PATH ${FLEX} DIRECTORY CACHE)
```suggestion
cmake_path(GET FLEX PARENT_PATH FLEX_PATH)
```

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +        -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
```suggestion
```
(I don't see that this is used.)

2023-07-04 06:26 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +
```suggestion
```

2023-07-06 14:50 UTC, duanqn commented on ports/nyan-lang/portfile.cmake
> +        -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
Removing this causes failures as FLEX_ROOT is not used by CMake.

2023-07-06 19:15 UTC, dg0yt commented on ports/nyan-lang/portfile.cmake
> +        -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
Is this for `find_package(FLEX)`? Shouldn't it be happy with `"-DFLEX_EXECUTABLE=${FLEX}"`, removing the need for `FLEX_PATH`? But I don't want to request another change now.

2023-07-07 03:19 UTC, duanqn commented
UWP builds are failing because SymInitialize is not available.

2023-07-11 05:02 UTC, duanqn commented
Hi @Adela0814 , is there a way to detect UWP builds? I contacted upstream and the maintainers want to remove the usage of SymInitialize in UWP builds.

2023-07-14 04:59 UTC, dg0yt reviewed
I would still recommend switching to setting `FLEX_EXECUTABLE`.

2023-07-14 04:59 UTC, dg0yt commented on ports/nyan-lang/0001-buildsys-Detect-WindowsStore-build-environment.patch
> + 	set_target_properties(nyan PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
If upstream really needs to export all symbols on Windows, can it really work without that on UWP?

2023-07-17 03:45 UTC, duanqn commented
> I would still recommend switching to setting `FLEX_EXECUTABLE`.

nyan/CMakeLists.txt has `find_package(FLEX 2.6 REQUIRED)`. Does setting `FLEX_EXECUTABLE` work for `find_package`?

2023-07-17 03:50 UTC, duanqn commented on ports/nyan-lang/0001-buildsys-Detect-WindowsStore-build-environment.patch
> + 	set_target_properties(nyan PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
I'm not entirely sure about the purpose of setting up symbols. It could be a "because we can" scenario here...

2023-07-25 10:12 UTC, Adela0814 requested changes

2023-07-25 10:12 UTC, Adela0814 commented on ports/nyan-lang/vcpkg.json
> +  "supports": "!osx & !static & !uwp",
Does this port not support UWP? I couldn't find any relevant instructions upstream.

2023-07-25 10:29 UTC, Adela0814 requested changes

2023-07-25 10:29 UTC, Adela0814 commented on ports/nyan-lang/portfile.cmake
> +        -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
```suggestion

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        "-DFLEX_EXECUTABLE=${FLEX}"
```

2023-07-25 10:31 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-07-25 17:51 UTC, dg0yt commented
> > I would still recommend switching to setting `FLEX_EXECUTABLE`.
> 
> @dg0yt nyan/CMakeLists.txt has `find_package(FLEX 2.6 REQUIRED)`. Does setting `FLEX_EXECUTABLE` work for `find_package`?

Yes. The package does a `find_program(FLEX_EXECUTABLE ...)`, and setting this cache variable (aka input variable) in advance is a public interface. In vcpkg, it is used in five other ports.

2023-08-30 06:56 UTC, duanqn commented on ports/nyan-lang/vcpkg.json
> +  "supports": "!osx & !static & !uwp",
UWP build cannot pass. See https://github.com/microsoft/vcpkg/pull/32250#issuecomment-1624593331

2023-08-30 07:01 UTC, duanqn commented
Applied suggested changes and rebased to latest master branch.

2023-09-01 02:59 UTC, Adela0814 approved these changes

2023-09-01 18:31 UTC, merged