[croncpp] Update to v2023.03.30
microsoft/vcpkg pull request #32368
Opened 2023-07-03 09:40 UTC by MonicaLiu0311

Fixes #32343, Update `croncpp` to `v2023.03.30`.

No feature needs to be tested, the usage test passed (header files found):
```
croncpp provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(croncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE croncpp::croncpp)
```

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-07-03 14:49 UTC, dg0yt commented on ports/croncpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug" "${CURRENT_PACKAGES_DIR}/lib")
~~~cmake
set(VCPKG_BUILD_TYPE release) # header-only-port
~~~

2023-07-03 14:52 UTC, dg0yt requested changes

2023-07-03 14:52 UTC, dg0yt commented on ports/croncpp/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug" "${CURRENT_PACKAGES_DIR}/lib")
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
```

2023-07-03 14:52 UTC, dg0yt commented on ports/croncpp/portfile.cmake
>  vcpkg_from_github(
```suggestion
set(VCPKG_BUILD_TYPE release) # header-only port
vcpkg_from_github(
```

2023-07-05 07:26 UTC, JonLiu1993 submitted a review, later dismissed

2023-07-05 18:29 UTC, vicroms submitted a review, later dismissed

2023-07-05 18:29 UTC, vicroms commented on ports/croncpp/vcpkg.json
> +  "version-string": "v2023.03.30",
In my opinion, this should stay as `version-date`. Changing the version scheme will cause problems because `v2023.03.30` is incomparable with all the previous versions that use `version-date`. This change of scheme has a minimal benefit but a large impact.

2023-07-05 19:10 UTC, dg0yt commented on ports/croncpp/vcpkg.json
> +  "version-string": "v2023.03.30",
> In my opinion, this should stay as `version-date`.

Indeed.
In other ports, we already transform `VERSION` into what is actually needed for download. Examples: sqlite3, poppler. So `version-string` is not justified at all.

2023-07-06 09:21 UTC, JonLiu1993 approved these changes

2023-07-06 17:43 UTC, merged