[imgui] Update to 1.89.7
microsoft/vcpkg pull request #32393
Opened 2023-07-04 18:02 UTC by RT2Code

Update imgui port from 1.89.6 to 1.89.7 : https://github.com/ocornut/imgui/releases/tag/v1.89.7

I tested the following features and platforms with success : 

```
imgui[docking-experimental,dx9-binding,dx10-binding,dx11-binding,freetype,glfw-binding,glut-binding,libigl-imgui,opengl2-binding,opengl3-binding,sdl2-binding,vulkan-binding,wchar32,win32-binding]:x86-windows
imgui[docking-experimental,dx9-binding,dx10-binding,dx11-binding,dx12-binding,freetype,glfw-binding,glut-binding,libigl-imgui,opengl2-binding,opengl3-binding,sdl2-binding,vulkan-binding,wchar32,win32-binding]:x64-windows
imgui[docking-experimental,dx9-binding,dx10-binding,dx11-binding,dx12-binding,freetype,glfw-binding,libigl-imgui,opengl2-binding,opengl3-binding,sdl2-binding,vulkan-binding,wchar32,win32-binding]:x64-windows-static
imgui[docking-experimental,freetype,libigl-imgui,vulkan-binding,wchar32]:x64-uwp
```

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-07-05 06:35 UTC, Adela0814 commented
Please fix the CI error, you can find all failure logs from https://dev.azure.com/vcpkg/public/_build/results?buildId=91490&view=artifacts&pathAsName=false&type=publishedArtifacts.
```
FAILED: CMakeFiles/implot.dir/implot.cpp.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\cl.exe   /TP  -ID:\buildtrees\implot\src\v0.14-fd7f3e910d.clean -ID:\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\implot.dir\implot.cpp.obj /FdCMakeFiles\implot.dir\implot.pdb /FS -c D:\buildtrees\implot\src\v0.14-fd7f3e910d.clean\implot.cpp
D:\buildtrees\implot\src\v0.14-fd7f3e910d.clean\implot.cpp(1805): error C2065: 'ImGuiButtonFlags_AllowItemOverlap': undeclared identifier
D:\buildtrees\implot\src\v0.14-fd7f3e910d.clean\implot.cpp(1805): error C2737: 'plot_button_flags': const object must be initialized
D:\buildtrees\implot\src\v0.14-fd7f3e910d.clean\implot.cpp(3381): error C2065: 'ImGuiButtonFlags_AllowItemOverlap': undeclared identifier
D:\buildtrees\implot\src\v0.14-fd7f3e910d.clean\implot.cpp(3411): error C2065: 'ImGuiButtonFlags_AllowItemOverlap': undeclared identifier
```

2023-07-07 03:05 UTC, Adela0814 requested changes

2023-07-07 03:05 UTC, Adela0814 commented on ports/implot/fix-build.patch
> ++++ b/implot.cpp
The content of this patch should be submitted to the upstream, and we need to wait for upstream approval or release.

2023-07-07 05:34 UTC, RT2Code commented on ports/implot/fix-build.patch
> ++++ b/implot.cpp
These changes are already merged upstream, I didn't improvise it. The patch is an aggregate of these two commits :
https://github.com/epezent/implot/commit/6dd8007e8e12f3bb8e2a4541175b384946f5c396
https://github.com/epezent/implot/commit/cc5e1daa5c7f2335a9460ae79c829011dc5cef2d

2023-07-07 05:50 UTC, Adela0814 approved these changes

2023-07-07 16:13 UTC, merged