[libunifex] Update to 2023-06-07 (v0.3.0)
microsoft/vcpkg pull request #32481
Opened 2023-07-10 20:56 UTC by bobbymcr

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-07-10 20:59 UTC, dacabdi commented
This is great, hopefully we can get it in soon :).

2023-07-11 06:04 UTC, MonicaLiu0311 requested changes

2023-07-11 06:04 UTC, MonicaLiu0311 commented on ports/libunifex/vcpkg.json
> +  "port-version": 1,
```suggestion
```

Each time the major version `version-date` is updated, the `port-version` counts from `0` (`"port-version": 0,` will generally be removed).

1. remove `"port-version": 0,`
2. commit `vcpkg.json`
3. Run `./vcpkg x-add-version libunifex --overwrite-version` to update `git-tree`
4. commit `libunifex.json`
5. Push together


`--overwrite-version`
After the first modification, please run `./vcpkg x-add-version portName` to generate the corresponding json; for subsequent modifications of the same version, please use `./vcpkg x-add-version portName --overwrite-version` to update git-tree.

2023-07-11 06:58 UTC, bobbymcr commented on ports/libunifex/vcpkg.json
> +  "port-version": 1,
Oh, sorry, I misunderstood that. Fixed now!

2023-07-11 07:54 UTC, MonicaLiu0311 commented
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

2023-07-11 08:27 UTC, MonicaLiu0311 submitted a review, later dismissed

2023-07-11 17:24 UTC, dg0yt commented on ports/libunifex/vcpkg.json
> +  "version-date": "2023-06-07",
```suggestion
  "version": "0.3.0",
```
... would enable ...

2023-07-11 17:24 UTC, dg0yt commented on ports/libunifex/portfile.cmake
> +    REF v0.3.0
```suggestion
    REF "v${VERSION}"
```

2023-07-11 18:19 UTC, bobbymcr commented on ports/libunifex/portfile.cmake
> +    REF v0.3.0
Thanks for the suggestion. I'm fine to move to semver-like versioning now that libunifex has adopted it. Are there any concerns about shifting away from the version date scheme that was used so far?

2023-07-11 18:53 UTC, merged

2023-07-11 18:53 UTC, BillyONeal commented
Thanks for the update!