[lunasvg] Update 2.3.8
microsoft/vcpkg pull request #32510
Opened 2023-07-11 15:02 UTC by sakiodre

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version *(not sure what this means)*
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-07-11 15:04 UTC, sakiodre commented
@microsoft-github-policy-service agree

2023-07-11 17:21 UTC, dg0yt commented on ports/lunasvg/fix-install.patch
> +@@ -23,16 +23,5 @@ if(LUNASVG_BUILD_EXAMPLES)
If there is no other change, maybe leave the patch unchanged?

2023-07-11 17:21 UTC, dg0yt commented on ports/lunasvg/portfile.cmake
> +  REF 87137e791c912432b93982722a8e965628950ca7 #2.3.8
```suggestion
  REF "v${VERSION}
```
... which will have a different SHA512.

2023-07-11 17:34 UTC, sakiodre commented on ports/lunasvg/fix-install.patch
> +@@ -23,16 +23,5 @@ if(LUNASVG_BUILD_EXAMPLES)
My mistake, I thought since the CMakelist.txt has changed, the patch also needed to be updated

2023-07-11 20:00 UTC, BillyONeal submitted a review, later dismissed

2023-07-12 02:16 UTC, FrankXie05 submitted a review, later dismissed

2023-07-12 02:18 UTC, FrankXie05 commented on ports/lunasvg/portfile.cmake
> +  REF v${VERSION}
```suggestion
  REF "v${VERSION}"

```
Not necessary, but more secure.

2023-07-12 02:24 UTC, FrankXie05 requested changes

2023-07-12 02:24 UTC, FrankXie05 commented on ports/lunasvg/portfile.cmake
> +  SHA512 368f76ae3c04fbcb08406d9e7793af37b5e28ab90ffe0978fae8783620a45af3270fcd4e895c553e3e651f0ba07e37355acffd9f0aab1bf9ef822f465de21073
```suggestion
  REF "v${VERSION}"
  SHA512 368f76ae3c04fbcb08406d9e7793af37b5e28ab90ffe0978fae8783620a45af3270fcd4e895c553e3e651f0ba07e37355acffd9f0aab1bf9ef822f465de21073

```

2023-07-12 02:25 UTC, FrankXie05 commented
Every change requires running the command `./vcpkg x-add-version lunasvg --overwrite-version`. :)

2023-07-12 02:26 UTC, FrankXie05 commented on ports/lunasvg/portfile.cmake
> +  SHA512 368f76ae3c04fbcb08406d9e7793af37b5e28ab90ffe0978fae8783620a45af3270fcd4e895c553e3e651f0ba07e37355acffd9f0aab1bf9ef822f465de21073
Remove the space.

2023-07-12 02:44 UTC, FrankXie05 approved these changes

2023-07-12 06:53 UTC, merged

2023-07-12 06:53 UTC, BillyONeal commented
Thanks!