Async mqtt tls
microsoft/vcpkg pull request #32551
Opened 2023-07-13 09:55 UTC by omarhogni

Fixes https://github.com/redboltz/async_mqtt/issues/49

2023-07-14 06:02 UTC, LilyWangLL commented
All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```

2023-07-14 06:02 UTC, LilyWangLL approved these changes, later dismissed

2023-07-14 23:55 UTC, BillyONeal requested changes

2023-07-14 23:55 UTC, BillyONeal commented on ports/async-mqtt/portfile.cmake
> +
This doesn't look like a feature, it looks like an alternative. For example, as a feature, there's no way for someone to write a constraint that it must *not* be static OpenSSL.

Moreover, why doesn't this just listen to what `find_package(OpenSSL` says?

2023-07-14 23:55 UTC, BillyONeal commented on ports/async-mqtt/portfile.cmake
> +set(ASYNC_MQTT_USE_TLS OFF)
This feature looks OK as it's just shadowing an optional dependency. (It doesn't seem like one would ever need to require this to be off)

2023-07-21 12:01 UTC, omarhogni commented on ports/async-mqtt/portfile.cmake
> +
So after looking into this I don't think zlib is a dependency even when statically linking openssl. The other effect this flag has is set ```OPENSSL_USE_STATIC_LIBS```.  I believe that is just a hint and should not matter for vcpkg builds. So I just removed the option.

2023-07-21 20:53 UTC, BillyONeal approved these changes, later dismissed

2023-07-24 01:59 UTC, LilyWangLL approved these changes, later dismissed

2023-07-24 06:11 UTC, dg0yt commented on ports/async-mqtt/vcpkg.json
> +    "use-tls": {
I would prefer the feature to be named `tls`.

2023-07-24 18:32 UTC, BillyONeal approved these changes

2023-07-24 18:33 UTC, BillyONeal commented
Thanks for the fix! I fixed @dg0yt's nitpick and clarified by using `vcpkg_check_features`. I'll merge as soon as build comes back.

2023-07-24 18:44 UTC, merged