[cxxgraph] Add new port CXXGraph
microsoft/vcpkg pull request #32696
Opened 2023-07-21 21:16 UTC by QuantumFelidae

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-07-21 21:18 UTC, QuantumFelidae commented
@microsoft-github-policy-service agree

2023-07-24 06:26 UTC, FrankXie05 requested changes

2023-07-24 06:26 UTC, FrankXie05 commented on ports/cxxgraph/portfile.cmake
> +    REF v2.0.0
```suggestion
    REF "v{VERSION}"
```
Please use the new function.

2023-07-24 06:26 UTC, FrankXie05 commented on ports/cxxgraph/portfile.cmake
> +file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")

```
We need the end line.

2023-07-24 06:26 UTC, FrankXie05 commented on ports/cxxgraph/vcpkg.json
> +  "description": "CXXGraph is a header only comprehensive C++ graph library.",
```suggestion
  "description": "CXXGraph is a header only comprehensive C++ graph library.",
  "homepage": "https://github.com/ZigRazor/CXXGraph"
```

2023-07-24 06:26 UTC, FrankXie05 commented on ports/cxxgraph/portfile.cmake
> +vcpkg_from_github(
```suggestion
# Header-only library

vcpkg_from_github(
```

2023-07-24 06:26 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2023-07-25 03:10 UTC, FrankXie05 commented
The usage tested successfully on `x64-windows`.

2023-07-25 03:11 UTC, FrankXie05 approved these changes, later dismissed

2023-07-25 05:12 UTC, dg0yt commented on ports/cxxgraph/portfile.cmake
> +# Header-only library
AFAIU there is no point in `vcpkg_cmake_configure` setting up the debug build type.
```suggestion
set(VCPKG_BUILD_TYPE release) # Header-only library
```

2023-07-25 15:56 UTC, QuantumFelidae commented
The PR was not marked as draft, so consider this comment to be marking as ready for review :)

2023-07-25 19:15 UTC, merged

2023-07-25 19:15 UTC, BillyONeal commented
Looks great, thanks for the new port!