[vcpkg baseline] Fix protoc.exe use the new headers with old DLLs
microsoft/vcpkg pull request #32800
Opened 2023-07-28 08:20 UTC by FrankXie05

Fix [CI_baseline](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8132201&view=results) issues.
```
cmd.exe /C "cd /D D:\buildtrees\gamenetworkingsockets\x64-windows-dbg\src && D:\installed\x64-windows\tools\protobuf\protoc.exe 
--cpp_out D:/buildtrees/gamenetworkingsockets/x64-windows-dbg/src 
-I D:/buildtrees/gamenetworkingsockets/src/687597c3e9-05f1ecc051.clean/src/common D:/buildtrees/gamenetworkingsockets/src/687597c3e9-05f1ecc051.clean/src/common/steamnetworkingsockets_messages_certs.proto"
ninja: build stopped: subcommand failed.
```
Currently we cannot synchronize the latest `STL` headers(specifically `<mutex>`) with the `IDE`, resulting in errors in the generation of `libprotobuf.dll` that `protoc.exe` depends on. 

error:
`0x00007FF9B37A28E0 (msvcp140d.dll) in protoc.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`

The result is that all ports that depend on `protoc.exe` fail to build.
So add compile option `/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` to temporarily disable method usage for new headers as a workaround.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-07-28 09:07 UTC, Neumann-A commented
I don't think this is the right solution. Please explain the problem further.

2023-07-28 09:16 UTC, FrankXie05 commented
@BillyONeal Should we show information about our internal testing to users?

2023-07-28 09:26 UTC, Osyotr commented
What new headers? What old DLLs? What does adding this definition fix?

2023-07-28 09:40 UTC, Neumann-A commented on ports/protobuf/portfile.cmake
> +    if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.38.32920.95")
this is not available in portfile.cmake since script mode does not run compiler detection

2023-07-28 09:43 UTC, FrankXie05 commented on ports/protobuf/portfile.cmake
> +    if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.38.32920.95")
Shuold be added `CMakeLists.txt`.

2023-07-28 15:38 UTC, BillyONeal requested changes
I don't think we should be working around an MSVC++ compiler team infrastructure issue by changing downstream consumers.

2023-07-31 10:29 UTC, Cheney-W commented
Does this mean we need to keep these failures in the result of `VCPKG Testing MSVC run` until the `MSVC++ compiler team infrastructure issue` is fixed?

2023-09-08 04:02 UTC, BillyONeal commented
> Does this mean we need to keep these failures in the result of `VCPKG Testing MSVC run` until the `MSVC++ compiler team infrastructure issue` is fixed?

Yes. Compiler team needs to fix the infrastructure for their tests.

2023-09-08 08:57 UTC, closed without merging

2023-09-08 08:57 UTC, FrankXie05 commented
Close this PR due to https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/494762.

At present, this problem is avoided by modifying the code logic and macro `_ENABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`.  
Unless we actively pass the macro.

And, this behavior will be the default in 17.9 and this issue will be completely resolved.