[vulkan-hpp] deprecate vulkan-hpp
microsoft/vcpkg pull request #32975
Opened 2023-08-04 23:06 UTC by qbojj

fix #32970

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-08-04 23:07 UTC, qbojj commented
@microsoft-github-policy-service agree

2023-08-05 11:03 UTC, qbojj commented
This fix is backwards compatibile as the old automatic usage (`find_path(VULKAN_HPP_INCLUDE_DIRS "vulkan/vulkan.hpp")`) will find the vulkan.hpp from [vulkan-headers], but this time you are guaranteed to actually have all the headers of Vulkan-Hpp and its dependencies (such as `<vulkan/vulkan.h>`) in the VULKAN_HPP_INCLUDE_DIRS.

2023-08-05 12:42 UTC, dg0yt requested changes

2023-08-05 12:42 UTC, dg0yt commented on ports/vulkan-hpp/usage
> +!!! [vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead !!!
As long as `vulkan.hpp` isn't installed by `vulkan-headers`, that port cannot replace port `vulkan.hpp`.

2023-08-05 12:42 UTC, dg0yt commented on ports/vulkan-hpp/usage
> +    target_link_libraries(main PRIVATE Vulkan::Headers)
These lines belong to port `vulkan-headers`. The wording is somewhat outdated and shouldn't be blindly duplicated. 
In addition, I don't think this is enough to ensure the availability of `vulkan.hpp`. A more complete version probably looks like: 
~~~cmake
vulkan-hpp can be used with CMake:

    find_path(VULKAN_HPP_DIR vulkan.hpp REQUIRED)
    find_package(VulkanHeaders CONFIG REQUIRED)
    target_include_directores(main PRIVATE "${VULKAN_HPP_DIR}")
    target_link_libraries(main PRIVATE Vulkan::Headers)
~~~

2023-08-05 12:42 UTC, dg0yt commented on ports/vulkan-hpp/portfile.cmake
> +message(WARNING "[vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead")
Again, this is cannot be right (or this port must not install `vulkan.hpp`).

2023-08-05 14:05 UTC, qbojj commented on ports/vulkan-hpp/usage
> +!!! [vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead !!!
But `vulkan-headers` as well as `vulkan` ports supply the `vulkan.hpp` and all other components of `KhronosGroup/Vulkan-Hpp`

2023-08-05 14:08 UTC, qbojj commented on ports/vulkan-hpp/usage
> +    target_link_libraries(main PRIVATE Vulkan::Headers)
The `vulkan.hpp` was only included to silence "warning: The folder /include is empty or not present. This indicates the library was not correctly installed.". I do not know how to silence this warning otherwise.

2023-08-05 14:08 UTC, qbojj commented on ports/vulkan-hpp/portfile.cmake
> +message(WARNING "[vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead")
This port should not install `vulkan.hpp` (only was to silence warning)

2023-08-05 14:18 UTC, qbojj commented on ports/vulkan-hpp/usage
> +    target_link_libraries(main PRIVATE Vulkan::Headers)
Found a way to silence the warning by enabling `VCPKG_POLICY_EMPTY_PACKAGE`, so vulkan.hpp is no longer installed.

2023-08-05 14:19 UTC, qbojj commented on ports/vulkan-hpp/portfile.cmake
> +message(WARNING "[vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead")
removed installation of `vulkan.hpp`

2023-08-05 14:31 UTC, dg0yt reviewed
That's the right policy now.

2023-08-05 14:31 UTC, dg0yt commented on ports/vulkan-hpp/portfile.cmake
> +set(VCPKG_BUILD_TYPE release) # header-only port
This is now obsolete.

2023-08-05 14:31 UTC, dg0yt commented on ports/vulkan-hpp/portfile.cmake
> +message(WARNING "[vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead")
The message from the portfile is now obsolete. It is issued only during an actual build. The usage has the same message, and it is also printed when installing from cache (if the port is explicitly requested).

2023-08-05 14:31 UTC, dg0yt commented on ports/vulkan-hpp/usage
> +!!! [vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead !!!
Fine. 
I'm still not happy with the specific style. Proposal (based on common patterns):
~~~
vulkan-hpp is deprecated. Please use port vulkan-headers instead.
~~~

2023-08-05 18:24 UTC, qbojj commented on ports/vulkan-hpp/usage
> +!!! [vulkan-hpp] is deprecated: use [vulkan-headers] or [vulkan] instead !!!
done

2023-08-05 18:53 UTC, qbojj commented on ports/vulkan-hpp/vcpkg.json
> +    "vulkan-headers"
`vulkan-hpp` should pull the same version of library as itself. Should this be expressed?

2023-08-05 19:01 UTC, dg0yt commented on ports/vulkan-hpp/vcpkg.json
> +    "vulkan-headers"
This can't be expressed in port manifests.
But given that you are deprecating the port, you could change the `version` field to `"version-string": "deprecated"`.

2023-08-06 00:00 UTC, qbojj commented on ports/vulkan-hpp/vcpkg.json
> +    "vulkan-headers"
done

2023-08-07 08:10 UTC, FrankXie05 approved these changes

2023-08-07 08:13 UTC, FrankXie05 commented
The usage has been tested successfully.

2023-08-07 16:19 UTC, merged