[azure-iot-sdk-c] LTS_08_2023
microsoft/vcpkg pull request #33016
Opened 2023-08-07 20:40 UTC by RLeclair

[azure-iot-sdk-c] LTS_08_2023

2023-08-07 20:47 UTC, dg0yt commented on ports/azure-iot-sdk-c/vcpkg.json
> +  "version-date": "2023-08-03",
Now we are moving backwards.

2023-08-07 21:44 UTC, RLeclair commented on ports/azure-iot-sdk-c/vcpkg.json
> +  "version-date": "2023-08-03",
Pushed control date forward to `2023-08-06`

2023-08-07 21:51 UTC, RLeclair commented on ports/azure-iot-sdk-c/vcpkg.json
> +  "version-date": "2023-08-03",
Pushed to `2023-08-07`

2023-08-07 22:53 UTC, vaavva approved these changes

2023-08-07 23:47 UTC, RLeclair commented
Hi @dg0yt, anything else needed to merge this PR?

2023-08-08 06:33 UTC, FrankXie05 requested changes

2023-08-08 06:33 UTC, FrankXie05 commented on ports/azure-macro-utils-c/vcpkg.json
> +  "version-date": "2023-08-07",
Please modify the corresponding `portfile.cmake` file.

2023-08-08 06:33 UTC, FrankXie05 commented on ports/umock-c/vcpkg.json
> +  "version-date": "2023-08-07",
https://github.com/microsoft/vcpkg/blob/ad46340bfce415333d6a2139592c22a499fb0df0/ports/umock-c/portfile.cmake#L6

2023-08-08 06:33 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2023-08-08 06:38 UTC, dg0yt requested changes

2023-08-08 06:38 UTC, dg0yt commented on ports/umock-c/vcpkg.json
> +  "version-date": "2023-08-07",
Can we be explicit?
Either don't update the `version-date`, or actually update the port.

2023-08-08 06:38 UTC, dg0yt commented on ports/azure-macro-utils-c/vcpkg.json
> +  "version-date": "2023-08-07",
i.e. either don't update the version-date, or actually update the port.

2023-08-08 15:04 UTC, RLeclair commented on ports/azure-macro-utils-c/vcpkg.json
> +  "version-date": "2023-08-07",
Removed update to `version-date`

2023-08-09 09:42 UTC, FrankXie05 commented on versions/a-/azure-c-shared-utility.json
> +      "port-version": 1
```suggestion
      "port-version": 0
```
Need to delete the `port-version` field in the `vcpkg.json`, and use the command `./vcpkg x-add-version`

2023-08-10 02:22 UTC, FrankXie05 approved these changes

2023-08-10 17:21 UTC, merged