Larryo/fixedcurldependency2
microsoft/vcpkg pull request #33207
Opened 2023-08-15 20:16 UTC by LarryOsterman

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2023-08-15 21:01 UTC, LarryOsterman commented
Tagging @BillyONeal

2023-08-16 09:39 UTC, FrankXie05 commented
@LarryOsterman Is there any official statement about the minimum version support for `curl`?

2023-08-16 17:39 UTC, LarryOsterman commented
> @LarryOsterman Is there any official statement about the minimum version support for `curl`?

Yes. The minimum version for the Azure SDK for C++ is 7.44.

However vcpkg will not let us express that, so I've been iterating trying to find ANY version of curl that we can mark as our minimum supported version. And thus this series of pull requests.

2023-08-16 19:30 UTC, dg0yt commented on ports/azure-core-cpp/vcpkg.json
> +          "version>=": "7.74.0"
Is `7.74.0` good enough, or does it have to be `7.74.0#5`?  (I don't know.)

2023-08-16 21:10 UTC, LarryOsterman commented on ports/azure-core-cpp/vcpkg.json
> +          "version>=": "7.74.0"
I honestly don't know either. 

I'm just trying to find any version that works, to be honest.

2023-08-16 22:06 UTC, BillyONeal commented
Given that any version of curl vcpkg is ever going to give complies with what Azure SDKs wants, should we just remove the version constraint entirely?

2023-08-18 02:00 UTC, FrankXie05 requested changes

2023-08-18 18:58 UTC, LarryOsterman commented on versions/a-/azure-core-cpp.json
> +    },
This suggested change confuses me. If I remove the `},` won't that render the JSON invalid?

2023-08-21 06:41 UTC, FrankXie05 commented on versions/a-/azure-core-cpp.json
> +    },
For the modification of a port, we require `port-version` +1.

2023-08-21 18:08 UTC, LarryOsterman commented on versions/a-/azure-core-cpp.json
> +    },
As best as I can figure, the suggested change removes line 7 from the file. Won't that break things?

2023-08-21 18:29 UTC, dg0yt commented on versions/a-/azure-core-cpp.json
> +    },
The suggestion is to remove the whole `port-version` 4 entry: A single PR can only a singe entry for each port.

2023-08-22 21:22 UTC, dan-shaw commented
/azp run

2023-08-23 01:54 UTC, FrankXie05 approved these changes

2023-08-23 18:45 UTC, merged