[colmap] Update to latest version from 2023-08-13
microsoft/vcpkg pull request #33251
Opened 2023-08-18 08:07 UTC by ahojnnes

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-08-18 08:37 UTC, Cheney-W commented
Could you please solve the CI test failures?
Failures logs: https://dev.azure.com/vcpkg/public/_build/results?buildId=93075&view=artifacts&pathAsName=false&type=publishedArtifacts

2023-08-21 09:45 UTC, Cheney-W commented on scripts/ci.baseline.txt
> +colmap:x64-windows-static-md=fail
Does this mean that this port no longer supports static? If so, please add the support field in vcpkg.json file.

2023-08-21 10:03 UTC, Cheney-W commented
I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-10-08 12:38 UTC, ahojnnes commented on scripts/ci.baseline.txt
> +colmap:x64-windows-static-md=fail
I hope this is correct?

2023-10-08 12:39 UTC, ahojnnes commented
@Cheney-W PTAL, thank you.

2023-10-09 03:05 UTC, Cheney-W commented on scripts/ci.baseline.txt
> +colmap:x64-windows-static-md=fail
I saw you have added `windows & !static` into the support, please remove above records from ci.baseline.txt.

2023-10-09 10:48 UTC, ahojnnes commented on scripts/ci.baseline.txt
> +colmap:x64-windows-static-md=fail
OK, thanks, wasn't sure. Done.

2023-10-10 02:12 UTC, Cheney-W requested changes

2023-10-10 02:12 UTC, Cheney-W commented on 9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
What's this? I think this should be removed.

2023-10-10 06:55 UTC, ahojnnes commented on 9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
Accidentally committed. Apologies.

2023-10-10 08:47 UTC, Cheney-W approved these changes

2023-10-10 09:04 UTC, Cheney-W approved these changes

2023-10-10 21:59 UTC, BillyONeal commented on ports/colmap/fix-dependencies.patch
> --find_package(FreeImage REQUIRED)
I confirmed that these changes are obsoleted by https://github.com/colmap/colmap/pull/2116/

2023-10-10 21:59 UTC, BillyONeal approved these changes

2023-10-10 21:59 UTC, merged

2023-10-10 21:59 UTC, BillyONeal commented
Thanks for the update!