[ffmpeg] Add support for disable-everything, file, h264 options
microsoft/vcpkg pull request #33343
Opened 2023-08-23 21:42 UTC by qmfrederik

This PR adds support for three new FFmpeg configuration options: disable-everything, file and h264.

2023-08-23 22:43 UTC, Osyotr commented
Vcpkg features should be additive. Is `ffmpeg[core]` not slim enough for you?

2023-08-24 05:35 UTC, dg0yt reviewed
Declare new features in the manifest usually doesn't have any effect on the build, without changing `portfile.cmake`.

2023-08-24 05:35 UTC, dg0yt commented on ports/ffmpeg/vcpkg.json
> +    },
AFAIU this feature isn't additive. "Features must be treated as additive functionality."
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives
And there is `vcpkg install ffmpeg[core]`.

2023-08-24 13:29 UTC, qmfrederik commented
Thanks @Osyotr and @dg0yt. Looks like ffmpeg[core] ships with a copy of avutil which is about 200KB larger than what you get with --disable-everything, which is fine.

I've updated the PR to drop the disable-everything option and keep file and h264 only.  Let me know what you think. Thanks!

2023-08-24 15:25 UTC, Osyotr commented on ports/ffmpeg/vcpkg.json
> +    "h264": {
No dependencies?

2023-08-24 15:25 UTC, Osyotr commented on ports/ffmpeg/vcpkg.json
> +    "file": {
This is very generic.
Also should be in `default-features`.

2023-08-24 15:25 UTC, Osyotr commented on ports/ffmpeg/portfile.cmake
> +    set(OPTIONS "${OPTIONS} --enable-protocol=file")
No `--disable...`?

2023-08-24 15:25 UTC, Osyotr commented on ports/ffmpeg/portfile.cmake
> +    set(OPTIONS "${OPTIONS} --enable-decoder=h264 --enable-parser=h264 --enable-demuxer=h264")
No `--disable...`?

2023-08-24 20:10 UTC, qmfrederik commented
So, I compared `ffmpeg[core,h264]` with `--disable-everything --enable-decoder=h264`

| library | core | disable-everything |
|-|-|
| avcodec-58 | 11,9 MB | 1,68 MB
| avfilter-8 | 3,38 MB | -
| avformat-59 | 2,10 MB | 180 KB 
| avutil-57 | 705 KB | 518 KB
| swscale-5 | 602 KB | 494 KB

So that's almost 15 MB extra.

2023-08-24 21:19 UTC, qmfrederik commented
So, in the end, what worked for me was to add options to enable/disable the default components which make up the various FFmpeg libraries for at least the core build.  I've amended the PR, let me know what you think.

2023-09-08 09:13 UTC, qmfrederik commented
@Osyotr @dg0yt I've reworked the PR based on your feedback, thoughts?

2023-09-16 04:02 UTC, Sibras commented
This PR doesnt do anything as file and h264 are already enabled in default ffmpeg configuration. So ffmpeg[core] already has all of these features enabled so adding extra command line parameters to enable them individually doesnt do anything.

I can see your original intention was to disable everything then only enable the small file and h264 components. But using specific options for fine-grained enablement of configs is massive as ffmpeg has 1000s of similar small pieces that can be enabled or disabled using its own configuration system. Vcpkg has deliberetly avoided that as its huge and ever changing (so keeping it in sync with source is difficult). So even if these components werent enabled as default im not sure we want to support adding just 2 specific options for one particular use case given we cant support all of them and then others may want similar options added for their own specific use cases.

2023-10-03 05:06 UTC, BillyONeal requested changes
I agree with @Osyotr

2024-02-08 18:29 UTC, qmfrederik commented
Closing for now, will revisit later if time allows.

2024-02-08 18:29 UTC, closed without merging