[libdecor] new port
microsoft/vcpkg pull request #33386
Opened 2023-08-25 23:51 UTC by quyykk

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-08-28 02:32 UTC, JonLiu1993 commented
@quyykk, Thanks for your PR, this is ci test error.
Please take a look:
````
Run-time dependency wayland-protocols found: NO (tried pkgconfig and cmake)

../src/0.1.1-abfd227373.clean/meson.build:46:0: ERROR: Dependency "wayland-protocols" not found, tried pkgconfig and cmake
````

2023-08-28 09:40 UTC, quyykk commented
@JonLiu1993 This needs an update to the Linux VM image with the new apt package that I added in this PR.

2023-08-29 19:51 UTC, quyykk commented
@JonLiu1993 can you add the "depends: vm update" label? thanks

2023-09-14 02:14 UTC, BillyONeal commented
> @JonLiu1993 This needs an update to the Linux VM image with the new apt package that I added in this PR.

It seems like `wayland-protocols` should be added to vcpkg rather than getting it through apt?

2023-09-14 09:26 UTC, quyykk commented
It's already in vcpkg but as a system port https://github.com/microsoft/vcpkg/blob/master/ports/wayland-protocols/portfile.cmake#L10

2023-10-09 04:30 UTC, dg0yt commented
> Since `wayland-protocols` is a virtual port, do you think it's fine in that case to add it through apt?

This PR needs to add the dependency on `wayland-protocols` because it needs it, and users are expected to install the system package because the virtual port needs it.

2023-11-14 21:00 UTC, BillyONeal commented
Dropping requires:vm-update because https://github.com/microsoft/vcpkg/pull/34431 made the change

2023-11-14 21:54 UTC, BillyONeal commented
/azp run

2023-11-14 21:54 UTC, BillyONeal commented
Restarting run because SAS tokens got reset

2023-11-14 23:05 UTC, quyykk commented
@JonLiu1993 this PR is now ready for review :smile:

2023-11-15 07:27 UTC, JonLiu1993 approved these changes

2023-11-16 01:33 UTC, data-queue commented on ports/libdecor/fix-plugin-loading.patch
> ++		plugin_dir_env = buffer;
Is this an upstream patch?

2023-11-16 01:54 UTC, quyykk commented on ports/gtk3/portfile.cmake
> +        -Dwayland_backend=true
Linux has two windowing systems, X11 and Wayland. This change enabled Wayland support.

2023-11-16 01:54 UTC, quyykk commented on ports/libdecor/fix-plugin-loading.patch
> ++		plugin_dir_env = buffer;
No

2023-11-17 22:32 UTC, data-queue commented on ports/libdecor/fix-plugin-loading.patch
> ++		plugin_dir_env = buffer;
Can you submit it upstream?

2023-11-17 22:41 UTC, quyykk commented on ports/gtk3/portfile.cmake
> +        -Dwayland_backend=true
I realized I didn't answer your question. Libdecor needs GTK with Wayland support enabled to work. GTK should be built with Wayland support anyways because Linux distros are all switching to Wayland.

2023-11-17 22:42 UTC, quyykk commented on ports/libdecor/fix-plugin-loading.patch
> ++		plugin_dir_env = buffer;
Sure

2024-01-04 00:43 UTC, BillyONeal requested changes
Please link to where upstream has had an opportunity to consider this patch.

2024-01-04 00:43 UTC, BillyONeal commented on ports/libdecor/fix-plugin-loading.patch
> ++		dladdr(&libdecor_new, &info);
This almost certainly needs to handle errors

2024-01-04 00:43 UTC, BillyONeal commented on ports/libdecor/fix-plugin-loading.patch
> ++		size_t index = last_slash - info.dli_fname;
This is doomed if there is no slash. Consider initializing last_slash with info.dli_fname rather than NULL?

2024-01-04 00:43 UTC, BillyONeal commented on ports/libdecor/fix-plugin-loading.patch
> ++		char *buffer = malloc(sizeof(char) * (index + strlen(PLUGIN_DIR) + 1));
Who frees this?

2024-02-01 21:38 UTC, data-queue commented
@quyykk Still working on this?

2024-05-14 06:45 UTC, JonLiu1993 commented
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

2024-05-14 06:45 UTC, closed without merging