[libxml2] Update to 2.11.5
microsoft/vcpkg pull request #33461
Opened 2023-08-30 11:39 UTC by SvenPStarFinanz

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-08-31 05:54 UTC, Adela0814 requested changes

2023-08-31 05:54 UTC, Adela0814 commented on ports/libxml2/disable-docs.patch
> +-install(FILES doc/xmlcatalog.1 DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 COMPONENT documentation)
Please restore the EOL.

2023-08-31 05:54 UTC, Adela0814 commented on ports/libxml2/portfile.cmake
> +    REF v2.11.5
```suggestion
    REF "v${VERSION}"
```

2023-08-31 05:59 UTC, Adela0814 commented
Please fix the CI error:
error message(`D:\buildtrees\ffmpeg\build-x64-windows-static-rel-out.log`):
```
=== CONFIGURING ===
ERROR: libxml-2.0 not found using pkg-config
```
Please find details from https://dev.azure.com/vcpkg/public/_build/results?buildId=93532&view=artifacts&pathAsName=false&type=publishedArtifacts.

2023-08-31 05:59 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-09-03 09:29 UTC, dg0yt reviewed
AFAICS `fix_cmakelist.patch` doesn't need to be modified at all.

2023-09-04 12:05 UTC, SvenPStarFinanz commented on ports/libxml2/disable-docs.patch
> +-install(FILES doc/xmlcatalog.1 DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 COMPONENT documentation)
Did so.

2023-09-05 07:53 UTC, Adela0814 commented
All feature tested pass in the following triplets:

- x64-windows
- x86-windows
- x64-windows-static

Usage tested pass on `x64-windows`.

2023-09-05 07:53 UTC, Adela0814 approved these changes

2023-09-06 05:32 UTC, merged

2023-09-06 05:35 UTC, BillyONeal commented
Thanks for the update!