[rlottie] New port
microsoft/vcpkg pull request #33476
Opened 2023-08-30 17:06 UTC by frabert

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-08-31 02:43 UTC, JonLiu1993 commented on ports/rlottie/portfile.cmake
> +    "patches/01_fix_install.patch"
```suggestion
    PATCHES
        "patches/01_fix_install.patch"
```

2023-08-31 02:43 UTC, JonLiu1993 commented on ports/rlottie/portfile.cmake
> +    -DLOTTIE_MODULE=${LOTTIE_MODULE}
```suggestion
    OPTIONS
        -DLOTTIE_MODULE=${LOTTIE_MODULE}
```

2023-08-31 02:48 UTC, JonLiu1993 commented on ports/rlottie/portfile.cmake
> +configure_file("${SOURCE_PATH}/COPYING" "${CURRENT_PACKAGES_DIR}/share/rlottie/copyright" COPYONLY)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING")
```

2023-08-31 02:56 UTC, JonLiu1993 commented
@frabert, Thanks for your PR, this is ci test error, please take a look:
````
FAILED: CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o 
/usr/bin/c++  -I/mnt/vcpkg-ci/buildtrees/rlottie/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/inc -I/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector/freetype -I/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector/pixman -I/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector -I/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/lottie -I/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/binding/c -fPIC -g -std=c++14 -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -Wall -fvisibility=hidden -Wnon-virtual-dtor -Woverloaded-virtual -Wno-unused-parameter -MD -MT CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o -MF CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o.d -o CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o -c /mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector/vrle.cpp
/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector/vrle.cpp: In member function ‘void VRle::Data::updateBbox() const’:
/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector/vrle.cpp:127:32: error: ‘numeric_limits’ is not a member of ‘std’
  127 |     int               l = std::numeric_limits<int>::max();
      |                                ^~~~~~~~~~~~~~
/mnt/vcpkg-ci/buildtrees/rlottie/src/v0.2-548eae308b.clean/src/vector/vrle.cpp:127:47: error: expected primary-expression before ‘int’
  127 |     int               l = std::numeric_limits<int>::max();
      |                                               ^~~
````

2023-08-31 02:56 UTC, JonLiu1993 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-08-31 11:52 UTC, frabert commented
@JonLiu1993 would it be possible to have access to the rest of the compilation log? I am not able to reproduce the issue on a local Ubuntu 20.04 machine

2023-09-01 02:02 UTC, JonLiu1993 commented
Please click this URL for the full build log:
https://dev.azure.com/vcpkg/public/_build/results?buildId=93556&view=artifacts&pathAsName=false&type=publishedArtifacts
![image](https://github.com/microsoft/vcpkg/assets/63675417/b13fe7d5-8c28-408f-9f7c-63603cba7132)

2023-09-04 06:59 UTC, JonLiu1993 commented on ports/rlottie/portfile.cmake
> +vcpkg_cmake_install()
```suggestion
vcpkg_cmake_install()

vcpkg_fixup_pkgconfig()
```

2023-09-04 07:12 UTC, JonLiu1993 commented
Tested usage successfully by `rlottie:x64-windows`:
````
rlottie provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(rlottie CONFIG REQUIRED)
    target_link_libraries(main PRIVATE rlottie::rlottie)

````

2023-09-04 07:13 UTC, JonLiu1993 commented on ports/rlottie/portfile.cmake
> +vcpkg_cmake_install()
We need add vcpkg_fixup_pkgconfig() function to fix common paths in *.pc files and make everything relative to $(prefix).

2023-09-04 10:11 UTC, JonLiu1993 approved these changes

2023-09-07 07:11 UTC, BillyONeal requested changes
I think upstream needs a look at the patches before we merge this. Other than that the port looks great to me!

2023-09-07 07:11 UTC, BillyONeal commented on ports/rlottie/patches/03_fix_arm_neon.patch
> ++    memset(dest, value, length);
I don't believe this is correct, as it repeats `value` in each `char` rather than each `uint32_t`?

Perhaps `std::fill_n(dest, length, value)`?

This suggests that these changes need to be submitted upstream first.

2023-09-08 17:58 UTC, frabert commented on ports/rlottie/patches/03_fix_arm_neon.patch
> ++    memset(dest, value, length);
Upstream already has a PR open for a similar fix but it doesn't look much activity is going on there. I would be ok with either saying this port won't work on ARM for now, or rejecting this port altogether for lack of maintenance. What do you think?

2024-11-15 07:14 UTC, JonLiu1993 commented
@frabert, Since there has been no progress on this PR for a year and a half, I will temporarily close this PR. If you have any updates, please feel free to let me know and open it again.

2024-11-15 07:14 UTC, closed without merging