[bde-tools] Add script port bde-tools
microsoft/vcpkg pull request #33569
Opened 2023-09-05 20:19 UTC by hallfox

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

Adding this to help support ports like bde and future ports like bloomberg/blazingmq. I think I did this correctly, but given that this is a port with just CMake modules and scripts I might have missed something. Thanks!

2023-09-06 06:53 UTC, Adela0814 requested changes

2023-09-06 06:53 UTC, Adela0814 commented on versions/b-/bde-tools.json
> +
```suggestion
{
  "versions": [
    {
      "git-tree": "cf37f7a2074d6d7814850d9832660f2f93639edf",
      "version": "3.123.0.0",
      "port-version": 0
    }
  ]
}
```

2023-09-06 06:57 UTC, Adela0814 requested changes

2023-09-06 06:57 UTC, Adela0814 commented on ports/bde-tools/portfile.cmake
> +    REPO bloomberg/bde-tools
Please note that we have an existing port `bde` that is the same source as yours.
https://github.com/microsoft/vcpkg/blob/1384becefca5c1511f0e070c43f66ad6a3783c8e/ports/bde/portfile.cmake#L12

2023-09-06 06:57 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-09-08 07:21 UTC, Adela0814 commented
Close this PR because it is an existing port.

2023-09-08 07:21 UTC, closed without merging

2023-09-08 16:52 UTC, hallfox commented on ports/bde-tools/portfile.cmake
> +    REPO bloomberg/bde-tools
`bde-tools` is different from `bde`. `bde` downloads it as part of its portfile build, I plan on altering future port versions of `bde` so that it would depend on this port instead. This is also because I plan to add a new port which will also use `bde-tools` for its CMake modules.

2023-09-08 16:56 UTC, hallfox commented
Hey sorry for the lag time between responses. This is a different port than [bde](https://github.com/microsoft/vcpkg/blob/db95d1c098a728ce39ef232bee95391cbd350561/ports/bde/portfile.cmake#L25), although the current port version uses bde-tools' source as you pointed out. This PR intends to create a port to separate the two.