[symengine] Fix find TCMALLOC
microsoft/vcpkg pull request #33582
Opened 2023-09-06 07:45 UTC by FrankXie05

Fix https://github.com/microsoft/vcpkg/issues/33576

All features has been tested successfully locally.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-09-07 00:47 UTC, BillyONeal commented
Is the tcmalloc port not publishing something it should be publishing?

2023-09-07 02:21 UTC, FrankXie05 commented
@BillyONeal The best way is probably to add port `tcmalloc`. I will try this。

2023-09-07 06:51 UTC, BillyONeal commented
> @BillyONeal The best way is probably to add port `tcmalloc`. I will try this。

I think there at least needs to be an investigation; this change might still be the correct one but we should ensure tcmalloc can't publish bits that work first.

2023-09-07 07:26 UTC, FrankXie05 commented
@BillyONeal The cmake integration for `tcmalloc `has been in progress, but since `bazel` and `cmake`, the syntax and ideas of the two build systems are very different. This progress should not be fast. And it seems they haven't updated or maintained it for a long time. 
https://github.com/google/tcmalloc/pull/104

2023-09-19 02:56 UTC, MonicaLiu0311 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review".

2023-11-13 09:55 UTC, MonicaLiu0311 commented
Flag `info:reviewed` for further review.

2023-11-13 09:55 UTC, MonicaLiu0311 approved these changes, later dismissed

2023-11-15 01:06 UTC, data-queue commented
I agree, I think the best way is to add the port `tcmalloc`.

2023-11-15 07:04 UTC, FrankXie05 commented
> @BillyONeal The best way is probably to add port `tcmalloc`. I will try this。

Convert to draft.

2023-11-22 05:02 UTC, BillyONeal commented
> I agree, I think the best way is to add the port `tcmalloc`.

The port exists, it just isn't publishing a cmake config this downstream port expects.

2023-11-22 06:40 UTC, FrankXie05 commented
Should we export it?

https://github.com/microsoft/vcpkg/blob/11cbb6b57b502d4864fa3c51b36b1ec88527a036/ports/gperftools/CMakeLists.txt#L194

2024-02-01 21:57 UTC, data-queue commented
I think the correct solution is to export `libtcmalloc_minimal` so `find_package` will find it.

2024-02-02 03:10 UTC, FrankXie05 commented
> I think the correct solution is to export `libtcmalloc_minimal` so `find_package` will find it.

Ok, I will do it.

2024-03-07 09:26 UTC, FrankXie05 commented
> > I think the correct solution is to export `libtcmalloc_minimal` so `find_package` will find it.
> 
> Ok, I will do it.

Done.

2024-03-08 05:51 UTC, FrankXie05 commented
The usage has been tested successfully.
```
gperftools provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(unofficial-libtcmalloc_minimal CONFIG REQUIRED)
  target_link_libraries(main PRIVATE unofficial::libtcmalloc_minimal)
```

2024-03-08 05:53 UTC, MonicaLiu0311 submitted a review, later dismissed

2024-03-08 06:08 UTC, dg0yt requested changes

2024-03-08 06:08 UTC, dg0yt commented on ports/gperftools/CMakeLists.txt
> +    )
IIUC the guidelines say that port `bar` may install `unofficial-bar-config.cmake` with `unofficial::bar::foo`,
and so port `gperftools` may install `unofficial-gperftools-config.cmake` with `unofficial::gperftools::libtcmalloc_minimal`.

If gerftools is the right port to install and own this lib.

2024-03-08 07:48 UTC, vicroms requested changes
Please apply @dg0yt's suggestion

2024-03-08 08:47 UTC, FrankXie05 commented
New usage has been verified：
```
gperftools provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(unofficial-gperftools CONFIG REQUIRED)
  target_link_libraries(main PRIVATE unofficial::gperftools::libtcmalloc_minimal)
```

2024-03-11 19:10 UTC, vicroms commented
marking `requires:vcpkg-team-review` to confirm that we're OK with `gperftools` vendoring `tmalloc`

2024-05-05 09:32 UTC, kotori2 commented
Any update on this PR?

2024-06-13 21:42 UTC, BillyONeal commented
@JavierMatosD
@vicroms
@ras0219-msft
and I discussed today.

The totally unrelated gperftools should not be vendoring TCMALLOC. And we should not be making symengine consume that vendored copy. Sorry for any confusion.

https://github.com/google/tcmalloc/pull/104 <-- Google has had more than enough time given our usual cooldown periods.

I think the path forward is this:

* Add unofficial configs to the port `tcmalloc` so that CMake customers can use it. This does not necessarily imply building tcmalloc itself with CMake; we can just write configs that do the right thing.
* Fix `gperftools` to stop vendoring `tcmalloc` and use the port
* Fix `symengine` to also use the port `tcmalloc`

I'm sorry that our 'rotation' process has led to some confusion as we didn't always understand everything when this was handed off between maintainers. I'll look to get this one to some resolution regardless of the 'rotation' mechanism.

2024-10-08 21:44 UTC, JavierMatosD commented
I'm marking this PR draft until review comments have been addressed.

2024-12-05 06:22 UTC, MonicaLiu0311 commented
Is there any new progress?

2024-12-05 09:51 UTC, FrankXie05 commented
Turn it off temporarily.

2024-12-05 09:51 UTC, closed without merging