[sparsehash-c11] New port
microsoft/vcpkg pull request #33639
Opened 2023-09-07 15:21 UTC by uchenily

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-09-07 15:41 UTC, uchenily commented
@microsoft-github-policy-service agree

2023-09-08 06:34 UTC, JonLiu1993 approved these changes, later dismissed

2023-09-08 06:35 UTC, JonLiu1993 commented
Tetsed usage successfully by `sparsehash-c11:x64-windows`:
````
sparsehash-c11 is header-only and can be used from CMake via:

    find_path(SPARSEHASH_C11_INCLUDE_DIRS "sparsehash/dense_hash_map")
    target_include_directories(main PRIVATE ${SPARSEHASH_C11_INCLUDE_DIRS})
````

2023-09-08 18:23 UTC, BillyONeal requested changes
Unfortunately this conflicts with the existing sparsehash port:

```console
Building sparsehash-c11:x64-windows...
-- Downloading https://github.com/sparsehash/sparsehash-c11/archive/v2.11.1.tar.gz -> sparsehash-sparsehash-c11-v2.11.1.tar.gz...
-- Extracting source C:/Dev/vcpkg/downloads/sparsehash-sparsehash-c11-v2.11.1.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/sparsehash-c11/src/v2.11.1-0d07fbd96c.clean
-- Installing: C:/Dev/vcpkg/packages/sparsehash-c11_x64-windows/share/sparsehash-c11/copyright
-- Performing post-build validation
error: The following files are already installed in C:/Dev/vcpkg/installed/x64-windows and are in conflict with sparsehash-c11:x64-windows
Installed by sparsehash:x64-windows
include/sparsehash/dense_hash_map
    include/sparsehash/dense_hash_set
    include/sparsehash/internal/densehashtable.h
    include/sparsehash/internal/hashtable-common.h
    include/sparsehash/internal/libc_allocator_with_realloc.h
    include/sparsehash/internal/sparsehashtable.h
    include/sparsehash/sparse_hash_map
    include/sparsehash/sparse_hash_set
    include/sparsehash/sparsetable

Stored binaries in 1 destinations in 45.7 ms.
Elapsed time to handle sparsehash-c11:x64-windows: 1.4 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sparsehash-c11
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sparsehash-c11]+Build+error
Include '[sparsehash-c11] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.     
    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 77f8eb7d7 2023-09-08 (19 hours ago)
```

As a result I don't believe we can take this as currently proposed. Changes would be needed to allow them not to conflict, such as being installed to different header directories and containing different namespaces. But that seems to conflict with what the thing is trying to be by implementing the same API.

Perhaps the sparsehash port should just get instructions to replace with this one should one want to?

2023-09-09 01:51 UTC, uchenily commented
Maybe we can display conflicting information when installing sparsehash or sparsehash-c11?

2023-09-11 06:50 UTC, JonLiu1993 commented on ports/sparsehash/portfile.cmake
> +if(EXISTS ${CURRENT_INSTALLED_DIR}/share/sparsehash-c11/copyright)
@uchenily, we should also change sparsehash/vcpkg.json file, change `port-version: 2` to  `port-version: 3`

2023-09-11 06:51 UTC, JonLiu1993 commented on versions/s-/sparsehash.json
> -      "git-tree": "c835b4a393784616327a8e5532769096fc443375",
We can‘ t change the historical "git-tree", which is our main basis for backtracking historical versions.

2023-09-11 12:15 UTC, uchenily commented on versions/s-/sparsehash.json
> -      "git-tree": "c835b4a393784616327a8e5532769096fc443375",
Thanks! I'll try it later.

2023-09-11 22:46 UTC, BillyONeal commented
> Maybe we can display conflicting information when installing sparsehash or sparsehash-c11?

We used to accept conflicting ports like this but have not since registries were added as a feature. Going forward we want to be able to say that we've tested things added to the registry together, and we can't do that if we allow conflicting universes.

2023-09-12 02:24 UTC, uchenily commented
Got it, since I don't know how to fix it right now, I will close this PR

2023-09-12 02:24 UTC, closed without merging