[flecs] update to 3.2.7
microsoft/vcpkg pull request #33823
Opened 2023-09-17 18:21 UTC by MUN1Z

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] <strike>The "supports" clause reflects platforms that may be fixed by this new version</strike>
- [ ] <strike>Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.</strike>
- [ ] <strike>Any patches that are no longer applied are deleted from the port's directory.</strike>
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-09-18 07:21 UTC, Adela0814 requested changes

2023-09-18 07:21 UTC, Adela0814 commented on versions/f-/flecs.json
> +    },
Please make sure only one version is added to modified port's versions file.

2023-09-18 07:21 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-09-18 22:21 UTC, dg0yt commented on versions/f-/flecs.json
> +    },
```suggestion
```

2024-01-08 09:16 UTC, Adela0814 commented
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

2024-01-08 09:16 UTC, closed without merging