[libremidi] Add new port
microsoft/vcpkg pull request #33848
Opened 2023-09-19 00:07 UTC by marinedalek

Fixes #20623

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says.
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [X] Only one version is added to each modified port's versions file.

Opened as draft for testing/comment

2023-09-19 05:48 UTC, jimwang118 requested changes

2023-09-19 05:48 UTC, jimwang118 commented on ports/libremidi/portfile.cmake
> +    REF "v4.0"
```suggestion
    REF "v${VERSION}"

```

2023-09-19 05:48 UTC, jimwang118 commented on ports/libremidi/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")
```

2023-09-25 02:04 UTC, jimwang118 approved these changes

2023-09-25 02:14 UTC, jimwang118 commented
Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

2023-09-26 07:33 UTC, merged

2023-09-26 18:31 UTC, jcelerier commented
yay ^-^

2023-10-03 05:40 UTC, BillyONeal commented
We accidentally merged this without verifying:

> Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all find_package calls are REQUIRED, are satisfied by vcpkg.json's declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)

and the port breaks that rule:

```
## JACK support ##
if(NOT LIBREMIDI_NO_JACK)
  find_path(WEAKJACK_PATH weakjack/weak_libjack.h HINTS ${WEAKJACK_FOLDER})
  find_path(JACK_PATH jack/jack.h)
  if(WEAKJACK_PATH AND JACK_PATH)
    message(STATUS "libremidi: using WeakJACK")
    set(LIBREMIDI_HAS_JACK 1)

    target_include_directories(libremidi ${_public} $<BUILD_INTERFACE:${WEAKJACK_PATH}> $<BUILD_INTERFACE:${JACK_PATH}>)
  elseif(JACK_PATH)
    find_library(JACK_LIBRARIES jack)
    if(JACK_LIBRARIES)
      message(STATUS "libremidi: using linked JACK")
      set(LIBREMIDI_HAS_JACK 1)
      
      target_link_libraries(libremidi ${_public} ${JACK_LIBRARIES})
      target_include_directories(libremidi ${_public} $<BUILD_INTERFACE:${JACK_PATH}>)
    endif()
  endif()

  if(LIBREMIDI_HAS_JACK)
    target_compile_definitions(libremidi ${_public} LIBREMIDI_JACK)
  endif()
endif()
```

and as a result this port fails in CI because jack2 happened to be installed first.

I submitted https://github.com/microsoft/vcpkg/pull/34223 which should fix this.

2023-10-22 19:05 UTC, splisp commented
I have commented on another issue but maybe this one is more relevant. The link to my comment is:

https://github.com/microsoft/vcpkg/issues/20623#issuecomment-1774173080