[sdbus-cpp] New port
microsoft/vcpkg pull request #33879
Opened 2023-09-19 20:17 UTC by russelltg

- [sdbus-cpp] new port
- ./vcpkg x-add-version --all

Fixes #19025

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-09-19 22:12 UTC, russelltg commented
This depends on libsystemd, which is why the CI is failing. Two options here:

* Remove from CI
* Add a libsystemd port

Let me know if there's a preference

2023-09-20 04:57 UTC, dg0yt commented
CI is mandatory.
libsystemd is proposed in https://github.com/microsoft/vcpkg/pull/31150.

2023-09-20 14:41 UTC, russelltg commented
Ok. Converting to draft status for now then

2023-09-21 10:34 UTC, jbbjarnason commented
@russelltg the systemd port has been merged, so you could probably continue. 

Side note, if you are not committed to this library I recommend having a look at https://github.com/openbmc/sdbusplus.

2023-09-28 02:55 UTC, Adela0814 requested changes

2023-09-28 02:55 UTC, Adela0814 commented on ports/sdbus-cpp/portfile.cmake
> +
Please remove this line.

2023-09-28 02:55 UTC, Adela0814 commented on ports/sdbus-cpp/usage
> +    target_link_libraries(main PRIVATE SDBusCpp::sdbus-c++)
Please add a new line at the end of the file.

2023-09-28 02:56 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-10-07 09:47 UTC, Adela0814 approved these changes

2023-10-09 22:29 UTC, merged

2023-10-09 22:29 UTC, BillyONeal commented
Thanks for the new port!