[libvmdk] Updated to version 20221124
microsoft/vcpkg pull request #33968
Opened 2023-09-24 15:48 UTC by lazyhamster

Updates libvmdk to latest available version.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-09-25 02:58 UTC, Adela0814 requested changes

2023-09-25 02:58 UTC, Adela0814 commented on ports/libvmdk/portfile.cmake
> +set(LIB_VERSION 20221124)
Unnecessary, please remove it and use the variable `VERSION` directly.

2023-09-25 03:00 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-09-25 09:26 UTC, lazyhamster commented
Done

2023-09-26 02:19 UTC, Adela0814 approved these changes

2023-09-26 06:42 UTC, merged