[sdl2] add missing 'dbus' dependency
microsoft/vcpkg pull request #34013
Opened 2023-09-25 20:52 UTC by quyykk

On Linux add the [dbus] dependency, which is needed for certain APIs. The patch is necessary to fix the dependency resolution so that it can find dbus.

2023-09-26 09:57 UTC, LilyWangLL submitted a review, later dismissed

2023-09-27 06:37 UTC, dg0yt requested changes

2023-09-27 06:37 UTC, dg0yt commented on ports/sdl2/fix-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
I don't understand why this patch is needed.
The original line should have the same effect as the new line.

2023-09-27 07:27 UTC, quyykk commented on ports/sdl2/fix-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
According to [the docs](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html):

> This command will set the value of the [CMAKE_MINIMUM_REQUIRED_VERSION](https://cmake.org/cmake/help/latest/variable/CMAKE_MINIMUM_REQUIRED_VERSION.html#variable:CMAKE_MINIMUM_REQUIRED_VERSION) variable to \<min\>.

And then it goes into this `if` right here: https://github.com/Kitware/CMake/blob/master/Modules/FindPkgConfig.cmake#L184, which makes it not apply the vcpkg paths to the search paths.

2023-09-27 10:11 UTC, dg0yt commented on ports/sdl2/fix-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
So if this is the purpose, then the actual solution is passing 
~~~
-DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=ON
~~~
with the CMake options so that it can enter
https://github.com/Kitware/CMake/blob/a314fbe4b26714962ce87330cc27c1ee830bbd61/Modules/FindPkgConfig.cmake#L179
This already used by other ports.

2023-09-27 10:40 UTC, quyykk commented on ports/sdl2/fix-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
Makes sense, but it doesn't work for some reason. Maybe because https://github.com/Kitware/CMake/blob/a314fbe4b26714962ce87330cc27c1ee830bbd61/Modules/FindPkgConfig.cmake#L711?

2023-09-27 10:56 UTC, dg0yt commented on ports/sdl2/fix-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
But we are years after 3.3, and L184 isn't reached when `PKG_CONFIG_USE_CMAKE_PREFIX_PATH` is defined.

2023-09-27 11:06 UTC, quyykk commented on ports/sdl2/fix-cmake-min.patch
> ++cmake_minimum_required(VERSION 3.5)
I have no idea what I did, but now it works lmao. Thanks! :smile:

2023-09-28 06:11 UTC, LilyWangLL approved these changes

2023-09-29 06:22 UTC, merged