[ecm] update to 5.110.0
microsoft/vcpkg pull request #34139
Opened 2023-09-29 10:47 UTC by jiayuehua

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-10-03 03:21 UTC, BillyONeal requested changes

2023-10-03 03:21 UTC, BillyONeal commented on ports/ecm/portfile.cmake
>          fix_canberra.patch         # https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/187
Are these patches still necessary?

2023-10-03 09:19 UTC, jiayuehua commented on ports/ecm/portfile.cmake
>          fix_canberra.patch         # https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/187
not neccessary any more, should delete them.

2023-10-07 09:57 UTC, Cheney-W commented
/azp run

2023-10-08 06:08 UTC, Cheney-W commented
/mnt/vcpkg-ci/buildtrees/kf5solid/install-x64-linux-dbg-out.log
https://dev.azure.com/vcpkg/_apis/resources/Containers/24564343/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fkf5solid&%24format=zip&saveAbsolutePath=false

2023-10-09 02:02 UTC, Cheney-W commented
Moving the PR to draft. Please set it to "ready for review" once failures have been fixed.

2023-10-10 14:05 UTC, jiayuehua commented
I don't know why k5solid fail.

2023-10-28 06:08 UTC, closed without merging