[Thorvg] Update Thorvg port to v0.11.0
microsoft/vcpkg pull request #34202
Opened 2023-10-02 06:22 UTC by rinechran

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-10-03 00:30 UTC, BillyONeal requested changes

2023-10-03 00:30 UTC, BillyONeal commented on ports/thorvg/portfile.cmake
> +    if(VCPKG_TARGET_IS_WINDOWS)
Why did you change this from the `supports` expression? Telling people up front something doesn't work (as supports does) is a better experience than building dependencies and stuff only for it to explode later..

2023-10-03 02:10 UTC, rinechran commented on ports/thorvg/portfile.cmake
> +    if(VCPKG_TARGET_IS_WINDOWS)
That's a good sound

2023-10-03 02:47 UTC, BillyONeal commented on ports/thorvg/portfile.cmake
> +    if(VCPKG_TARGET_IS_WINDOWS)
This doesn't look changed

2023-10-03 03:08 UTC, rinechran commented on ports/thorvg/portfile.cmake
> +    if(VCPKG_TARGET_IS_WINDOWS)
I'm sorry. I think I made a mistake I'll put up the PR again

2023-10-04 00:51 UTC, BillyONeal requested changes
The supports expression removal is still here :(

2023-10-04 01:04 UTC, rinechran commented
> The supports expression removal is still here :(

Is the talking support by any chance vcpkg.json's support?

2023-10-04 03:16 UTC, BillyONeal commented
> > The supports expression removal is still here :(
> 
> Is the talking support by any chance vcpkg.json's support?

There are still changes here which remove a `"supports"` from `vcpkg.json` and add an equivalent block in `portfile.cmake`. Above it looks like you said you would revert that change but it's still here.

2023-10-04 04:26 UTC, eunsikNota commented
> > > The supports expression removal is still here :(
> > 
> > 
> > Is the talking support by any chance vcpkg.json's support?
> 
> There are still changes here which remove a `"supports"` from `vcpkg.json` and add an equivalent block in `portfile.cmake`. Above it looks like you said you would revert that change but it's still here.

Thank you for understanding me

2023-10-04 04:27 UTC, rinechran commented
> > > The supports expression removal is still here :(
> > 
> > 
> > Is the talking support by any chance vcpkg.json's support?
> 
> There are still changes here which remove a `"supports"` from `vcpkg.json` and add an equivalent block in `portfile.cmake`. Above it looks like you said you would revert that change but it's still here.

Thank you for understanding me

2023-10-04 20:48 UTC, BillyONeal approved these changes
Thanks for the update!

2023-10-04 20:48 UTC, merged

2023-10-05 02:36 UTC, rinechran commented
I didn't know it changed a lot because I contributed after a long time.  Thank you so much for letting me know. @BillyONeal