[libremidi] update to 4.2.1
microsoft/vcpkg pull request #34269
Opened 2023-10-04 22:42 UTC by jcelerier

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [?] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

END OF PORT UPDATE CHECKLIST (delete this line) -->

2023-10-04 22:43 UTC, jcelerier commented
@microsoft-github-policy-service agree

2023-10-04 22:44 UTC, jcelerier commented
@marinedalek @BillyONeal hopefully this fixes the issue with ALSA that was mentioned before

2023-10-04 23:18 UTC, BillyONeal requested changes

2023-10-04 23:18 UTC, BillyONeal commented on ports/libremidi/vcpkg.json
>    "homepage": "https://github.com/jcelerier/libremidi",
You need to add `{"name": "alsa", "platform": "linux"},` to dependencies.

2023-10-04 23:18 UTC, BillyONeal commented on ports/libremidi/portfile.cmake
>      OPTIONS
```suggestion
    OPTIONS
        ${options}
```

2023-10-04 23:18 UTC, BillyONeal commented on ports/libremidi/portfile.cmake
```suggestion
vcpkg_list(SET options)
if(VCPKG_TARGET_IS_LINUX)
    vcpkg_list(APPEND options -DLIBREMIDI_NO_ALSA=OFF)
else()
    vcpkg_list(APPEND options -DLIBREMIDI_NO_ALSA=ON)
endif()
```

2023-10-06 03:20 UTC, BillyONeal commented
```
/usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/midi_in.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/midi_in.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/midi_in.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/midi_in.cpp
In file included from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/backends/alsa_raw/helpers.hpp:2,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/backends/alsa_raw/midi_in.hpp:3,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/backends/alsa_raw.hpp:2,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/backends.hpp:15,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/midi_in.cpp:5:
/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.1-604e663e2a.clean/include/libremidi/backends/linux/alsa.hpp:5:10: fatal error: alsa/asoundlib.h: No such file or directory
    5 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

hmmmm this is strange, since alsa indeed is supposed to install that stuff:

```
alsa:x64-linux:/debug/lib/libasound.a
alsa:x64-linux:/debug/lib/libatopology.a
alsa:x64-linux:/debug/lib/pkgconfig/alsa-topology.pc
alsa:x64-linux:/debug/lib/pkgconfig/alsa.pc
alsa:x64-linux:/include/alsa/asoundef.h
alsa:x64-linux:/include/alsa/asoundlib.h               <-- !!!
alsa:x64-linux:/include/alsa/conf.h
alsa:x64-linux:/include/alsa/control.h
alsa:x64-linux:/include/alsa/control_external.h
alsa:x64-linux:/include/alsa/control_plugin.h
alsa:x64-linux:/include/alsa/error.h
alsa:x64-linux:/include/alsa/global.h
alsa:x64-linux:/include/alsa/hwdep.h
alsa:x64-linux:/include/alsa/input.h
alsa:x64-linux:/include/alsa/mixer.h
alsa:x64-linux:/include/alsa/mixer_abst.h
alsa:x64-linux:/include/alsa/output.h
alsa:x64-linux:/include/alsa/pcm.h
alsa:x64-linux:/include/alsa/pcm_external.h
alsa:x64-linux:/include/alsa/pcm_extplug.h
alsa:x64-linux:/include/alsa/pcm_ioplug.h
alsa:x64-linux:/include/alsa/pcm_old.h
alsa:x64-linux:/include/alsa/pcm_plugin.h
alsa:x64-linux:/include/alsa/pcm_rate.h
alsa:x64-linux:/include/alsa/rawmidi.h
alsa:x64-linux:/include/alsa/seq.h
alsa:x64-linux:/include/alsa/seq_event.h
alsa:x64-linux:/include/alsa/seq_midi_event.h
alsa:x64-linux:/include/alsa/seqmid.h
alsa:x64-linux:/include/alsa/sound/asoc.h
alsa:x64-linux:/include/alsa/sound/asound_fm.h
alsa:x64-linux:/include/alsa/sound/emu10k1.h
alsa:x64-linux:/include/alsa/sound/hdsp.h
alsa:x64-linux:/include/alsa/sound/hdspm.h
alsa:x64-linux:/include/alsa/sound/sb16_csp.h
alsa:x64-linux:/include/alsa/sound/sscape_ioctl.h
alsa:x64-linux:/include/alsa/sound/tlv.h
alsa:x64-linux:/include/alsa/sound/type_compat.h
alsa:x64-linux:/include/alsa/sound/uapi/asoc.h
alsa:x64-linux:/include/alsa/sound/uapi/asound_fm.h
alsa:x64-linux:/include/alsa/sound/uapi/emu10k1.h
alsa:x64-linux:/include/alsa/sound/uapi/hdsp.h
alsa:x64-linux:/include/alsa/sound/uapi/hdspm.h
alsa:x64-linux:/include/alsa/sound/uapi/sb16_csp.h
alsa:x64-linux:/include/alsa/sound/uapi/sscape_ioctl.h
alsa:x64-linux:/include/alsa/sound/uapi/tlv.h
alsa:x64-linux:/include/alsa/timer.h
alsa:x64-linux:/include/alsa/topology.h
alsa:x64-linux:/include/alsa/ump.h
alsa:x64-linux:/include/alsa/ump_msg.h
alsa:x64-linux:/include/alsa/use-case.h
alsa:x64-linux:/include/alsa/version.h
alsa:x64-linux:/include/asoundlib.h
alsa:x64-linux:/include/sys/asoundlib.h
alsa:x64-linux:/lib/libasound.a
alsa:x64-linux:/lib/libatopology.a
alsa:x64-linux:/lib/pkgconfig/alsa-topology.pc
alsa:x64-linux:/lib/pkgconfig/alsa.pc
alsa:x64-linux:/share/alsa/aclocal/alsa.m4
alsa:x64-linux:/share/alsa/copyright
alsa:x64-linux:/share/alsa/usage
alsa:x64-linux:/share/alsa/vcpkg-cmake-wrapper.cmake
alsa:x64-linux:/share/alsa/vcpkg.spdx.json
alsa:x64-linux:/share/alsa/vcpkg_abi_info.txt
alsa:x64-linux:/tools/alsa/bin/aserver
alsa:x64-linux:/tools/alsa/debug/bin/aserver
```

Is our alsa `.pc` messed up or something, or is libremidi missing a `target_link_libraries` meant to add the include path?

2023-10-06 03:27 UTC, dg0yt commented
> Is our alsa `.pc` messed up or something, or is libremidi missing a `target_link_libraries` meant to add the include path?

AFAICS it does `find_package(ALSA)`, but it doesn't use the result except for `ALSA_FOUND`.
FTR it does look for udev when it finds alsa, and would use that include dir.
Really more work to get it right...
https://github.com/jcelerier/libremidi/blob/857b16ae550afc140adf761d1487cde302645ffe/CMakeLists.txt#L289-L306

2023-10-06 13:16 UTC, jcelerier commented
My bad, I didn't expect to not have libasound not in the default compiler include path. Adding it

2023-10-06 13:37 UTC, jcelerier commented on versions/l-/libremidi.json
>    "versions": [
I don't understand, why is this failing?

2023-10-06 16:40 UTC, BillyONeal commented on versions/l-/libremidi.json
>    "versions": [
Sorry, I have outstanding changes to make this clearer: https://github.com/microsoft/vcpkg-tool/pull/1210

Pretend this says:

```console
C:\Dev\vcpkg\versions\l-\libremidi.json: error: libremidi@4.2.2#1 is declared to have git tree e3d526d3695fc3183036d1a37883eb5e97017e9d, but the local port C:\Dev\vcpkg\ports\libremidi has git tree d21cee0e369a1a5998a226fce0168954621840dc
note: If libremidi@4.2.2#1 is already published, update the libremidi manifest with a new version or port-version, then add the new version by running:
  vcpkg x-add-version libremidi
  git add versions
  git commit -m "Update version database"
note: if libremidi@4.2.2#1 is not yet published, overwrite the previous git tree by running:
  vcpkg x-add-version libremidi --overwrite-version
  git add versions
  git commit -m "Update version database"
```

2023-10-06 18:35 UTC, jcelerier commented
It's still failing, but I can't see the log, I just see this in azure:

```
Installing 4/4 libremidi:x64-linux...
Building libremidi:x64-linux...
-- Downloading https://github.com/jcelerier/libremidi/archive/v4.2.2.tar.gz -> jcelerier-libremidi-v4.2.2.tar.gz...
-- Extracting source /mnt/vcpkg-ci/downloads/jcelerier-libremidi-v4.2.2.tar.gz
-- Using source at /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /mnt/vcpkg-ci/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j33
    Working Directory: /mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg
    See logs for more information:
      /mnt/vcpkg-ci/buildtrees/libremidi/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  /mnt/vcpkg-ci/installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /mnt/vcpkg-ci/installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libremidi/portfile.cmake:24 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)


error: building libremidi:x64-linux failed with: BUILD_FAILED
```

is this log available somewhere?     /mnt/vcpkg-ci/buildtrees/libremidi/install-x64-linux-dbg-out.log

2023-10-06 19:35 UTC, dg0yt commented
https://github.com/microsoft/vcpkg/discussions/31357

2023-10-06 23:41 UTC, BillyONeal commented
> is this log available somewhere? /mnt/vcpkg-ci/buildtrees/libremidi/install-x64-linux-dbg-out.lo

In addition to @dg0yt's link:

```
Change Dir: '/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg'

Run Build Command(s): /mnt/vcpkg-ci/downloads/tools/ninja-1.10.2-linux/ninja -v -v -j33 install
[1/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_in.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_in.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_in.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/emscripten/midi_in.cpp
[2/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_out.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_out.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_out.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/emscripten/midi_out.cpp
[3/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/observer.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/observer.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/observer.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/emscripten/observer.cpp
[4/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_access.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_access.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/backends/emscripten/midi_access.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/emscripten/midi_access.cpp
[5/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/writer.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/writer.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/writer.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/writer.cpp
[6/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/reader.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/reader.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/reader.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/reader.cpp
[7/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/client.cpp
FAILED: CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o 
/usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g -std=gnu++20 -fPIC -MD -MT CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o -MF CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o.d -o CMakeFiles/libremidi.dir/include/libremidi/client.cpp.o -c /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/client.cpp
In file included from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/alsa_seq.hpp:15,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends.hpp:16,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/client.cpp:4:
/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/alsa_seq/midi_in.hpp: In member function ‘int libremidi::alsa_seq::midi_in_impl<ConfigurationBase, ConfigurationImpl>::process_ump_event(const snd_seq_ump_event_t&)’:
/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/alsa_seq/midi_in.hpp:348:10: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
  348 |     std::memcpy(ump.bytes, ev.ump, sizeof(ev.ump));
      |          ^~~~~~
      |          wmemcpy
In file included from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/alsa_seq_ump.hpp:6,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends.hpp:19,
                 from /mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/client.cpp:4:
/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/alsa_seq_ump/midi_out.hpp: In member function ‘virtual void libremidi::alsa_seq_ump::midi_out_impl::send_ump(const unsigned int*, std::size_t)’:
/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include/libremidi/backends/alsa_seq_ump/midi_out.hpp:132:10: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
  132 |     std::memcpy(ev.ump, message, size * sizeof(uint32_t));
      |          ^~~~~~
      |          wmemcpy
[8/13] /usr/bin/c++ -DLIBREMIDI_ALSA -DLIBREMIDI_EXPORTS -DLIBREMIDI_HAS_UDEV -DLIBREMIDI_NO_BOOST -I/mnt/vcpkg-ci/buildtrees/libremidi/x64-linux-dbg -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean -I/mnt/vcpkg-ci/buildtrees/libremidi/src/v4.2.2-bc2528a3a3.clean/include -I/mnt/vcpkg-ci/installed/x64-linux/include -fPIC -g [...]

2023-10-08 14:43 UTC, jcelerier commented
indeed.. I wonder why this wasn't caught in my already extensive CI.
Is there a way that I could use to replicate the vcpkg CI configuration easily in mine so that I'm sure new releases will work?

2023-10-08 14:48 UTC, jcelerier commented
> How can I inspect the failed PR CI build log?: #31357

just fyi : 
![image](https://github.com/microsoft/vcpkg/assets/2772730/14b31483-d2e4-4305-a857-06c439ee0027)

2023-10-08 15:31 UTC, dg0yt commented
> Is there a way that I could use to replicate the vcpkg CI configuration easily in mine so that I'm sure new releases will work?

The most relevant component for this error is the compiler. The x64-linux CI is based on Ubuntu 22.04.
https://github.com/microsoft/vcpkg/tree/master/scripts/azure-pipelines/linux

> missing a string.h?

Or `<cstring>`, for C++ headers.

2023-10-08 19:00 UTC, jcelerier commented
yep, my CI is testing ubuntu too, with both gcc / libstdc++, clang / libstdc++ and clang / libc++.. https://github.com/jcelerier/libremidi/actions/runs/6448142359/job/17505112858 so most likely there is something else going on

2023-10-09 04:26 UTC, dg0yt commented
Well, any other external header may have that include line. And then you can track is origin. But I don't think it is worth spending that time. Include what you use. (There is even a tool for it.)

2023-10-09 22:59 UTC, jcelerier commented
okay, looks green :)

2023-10-10 00:19 UTC, BillyONeal commented
> Is there a way that I could use to replicate the vcpkg CI configuration easily in mine so that I'm sure new releases will work?

It's likely that this problem is hidden on your own test system because alsa is almost always going to be present on a traditional desktop OS; we start with the ubuntu 'minimal' install then add these packages:

https://github.com/microsoft/vcpkg/blob/848006ded39bc0b77dcc8614de60990dc1c0bec1/scripts/azure-pipelines/linux/managed-image.json#L6

You should be able to produce more or less the same environment by making a blank Ubuntu Server 22.04 Minimal installation, then running this script: https://github.com/microsoft/vcpkg/blob/848006ded39bc0b77dcc8614de60990dc1c0bec1/scripts/azure-pipelines/linux/provision-image.sh

2023-10-10 01:03 UTC, BillyONeal approved these changes
Thanks for the update!

2023-10-10 01:03 UTC, merged