[sdl2] Add feature alsa
microsoft/vcpkg pull request #34311
Opened 2023-10-06 14:25 UTC by Thomas1664

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Fix use of alsa. This regression was introduced by #33283.

cc @Honeybunch

2023-10-06 14:41 UTC, Honeybunch commented
Oof thanks my bad

2023-10-08 08:22 UTC, MonicaLiu0311 commented
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
x64-linux
```

2023-10-09 02:40 UTC, MonicaLiu0311 commented
Feature `alsa` is tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
x64-linux
```

2023-10-09 02:46 UTC, MonicaLiu0311 submitted a review, later dismissed

2023-10-09 23:09 UTC, BillyONeal commented on ports/sdl2/alsa-dep-fix.patch
> ++if(@HAVE_ALSA@)
Can you explain what this patch is doing? Has it been submitted upstream? Given that `SDL_ALSA` was set above on line 7 and should match `HAVE_ALSA` exactly something seems broken here...

2023-10-09 23:09 UTC, BillyONeal requested changes
(see comment)

2023-10-10 07:09 UTC, Thomas1664 commented on ports/sdl2/alsa-dep-fix.patch
> ++if(@HAVE_ALSA@)
It doesn't because of [this line](https://github.com/libsdl-org/SDL/blob/8a5ba43d00252c6c8b33c9aa4f1048222955ab4d/cmake/sdlchecks.cmake#L92). `SDL_ALSA` only expresses that the user wants alsa but if alsa can't be found, this is still set to `ON`. Because we're now controlling the alsa feature directly, the patch might not be needed anymore. I'll check that today.

2023-10-12 02:32 UTC, MonicaLiu0311 commented
Please resolve the conflict.

2023-10-16 02:35 UTC, MonicaLiu0311 approved these changes

2023-10-16 17:47 UTC, BillyONeal approved these changes

2023-10-16 17:48 UTC, merged