[zoe] Add new port
microsoft/vcpkg pull request #34369
Opened 2023-10-09 07:51 UTC by winsoft666

If this PR adds a new port, please uncomment and fill out this checklist:

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-10-09 08:57 UTC, FrankXie05 commented
```
/mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp: In member function ‘zoe::Result zoe::EntryHandler::_asyncTaskProcess()’:
/mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp:363:25: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  363 |       std::this_thread::sleep_for(std::chrono::milliseconds(100));
      |                         ^~~~~~~~~
/mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp:373:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  373 |         std::this_thread::sleep_for(std::chrono::milliseconds(50));
      |                           ^~~~~~~~~
```
Maybe need include `<thread.h>`  or wrong namespace.
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/12844111/install-x64-linux-dbg-out.2.log)

2023-10-10 06:59 UTC, winsoft666 commented
> ```
> /mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp: In member function ‘zoe::Result zoe::EntryHandler::_asyncTaskProcess()’:
> /mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp:363:25: error: ‘sleep_for’ is not a member of ‘std::this_thread’
>   363 |       std::this_thread::sleep_for(std::chrono::milliseconds(100));
>       |                         ^~~~~~~~~
> /mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp:373:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
>   373 |         std::this_thread::sleep_for(std::chrono::milliseconds(50));
>       |                           ^~~~~~~~~
> ```
> 
> Maybe need include `<thread.h>` or wrong namespace. [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/12844111/install-x64-linux-dbg-out.2.log)

I have fixed this issue, could you try again?

2023-10-10 07:01 UTC, FrankXie05 commented
> > ```
> > /mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp: In member function ‘zoe::Result zoe::EntryHandler::_asyncTaskProcess()’:
> > /mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp:363:25: error: ‘sleep_for’ is not a member of ‘std::this_thread’
> >   363 |       std::this_thread::sleep_for(std::chrono::milliseconds(100));
> >       |                         ^~~~~~~~~
> > /mnt/vcpkg-ci/buildtrees/zoe/src/41c3c2d161-9b4d7598fd.clean/src/entry_handler.cpp:373:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
> >   373 |         std::this_thread::sleep_for(std::chrono::milliseconds(50));
> >       |                           ^~~~~~~~~
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe need include `<thread.h>` or wrong namespace. [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/12844111/install-x64-linux-dbg-out.2.log)
> 
> I have fixed this issue, could you try again?

This is error from CI check.

2023-10-10 07:16 UTC, FrankXie05 requested changes

2023-10-10 07:16 UTC, FrankXie05 commented on ports/zoe/vcpkg.json
> +  "port-version": 1,
```suggestion
```
The `+1` operation of `port-verison` will only be performed when the port is modified.
Simply, one PR gets `+1` at a time.

2023-10-10 07:16 UTC, FrankXie05 commented on versions/z-/zoe.json
> +    },
```suggestion
  "versions": [
    {
      "git-tree": "24d50f143b93df2ab26fc6420ef6648cac18005a",
      "version": "3.0",
      "port-version": 1
    },
    {
      "git-tree": "b1c5c5bb8d55ed4a3b7a763dc19c69666694e6c4",
      "version": "3.2",
      "port-version": 0
    },
    {
      "git-tree": "bbac35ef9a8843e0f75c2c8823c386909686fa50",
      "version": "3.1",
      "port-version": 0
    },
```
Just run command `./vcpkg x-add-version zoe --overwrite-version`

2023-10-11 07:06 UTC, FrankXie05 commented
CI error: https://dev.azure.com/vcpkg/public/_build/results?buildId=95324&view=artifacts&pathAsName=false&type=publishedArtifacts

```
FAILED: src/CMakeFiles/zoe-static.dir/file_util.cpp.o 
/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android21 --sysroot=/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DNOMINMAX -DUNICODE -DWITH_OPENSSL -DZOE_STATIC -D_UNICODE -I/mnt/vcpkg-ci/buildtrees/zoe/src/b4e3a319e2-1e96496453.clean/./include -isystem /mnt/vcpkg-ci/installed/x64-android/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions  -fPIC   -fno-limit-debug-info    -std=gnu++11 -fPIC -pthread -MD -MT src/CMakeFiles/zoe-static.dir/file_util.cpp.o -MF src/CMakeFiles/zoe-static.dir/file_util.cpp.o.d -o src/CMakeFiles/zoe-static.dir/file_util.cpp.o -c /mnt/vcpkg-ci/buildtrees/zoe/src/b4e3a319e2-1e96496453.clean/src/file_util.cpp
/mnt/vcpkg-ci/buildtrees/zoe/src/b4e3a319e2-1e96496453.clean/src/file_util.cpp:50:3: error: use of undeclared identifier 'fseeko64'
  fseeko64(f, 0L, SEEK_END);
  ^
/mnt/vcpkg-ci/buildtrees/zoe/src/b4e3a319e2-1e96496453.clean/src/file_util.cpp:51:19: error: use of undeclared identifier 'ftello64'; did you mean 'ftello'?
  int64_t fsize = ftello64(f);
                  ^~~~~~~~
                  ftello
/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdio.h:251:7: note: 'ftello' declared here
off_t ftello(FILE* __fp);
      ^
/mnt/vcpkg-ci/buildtrees/zoe/src/b4e3a319e2-1e96496453.clean/src/file_util.cpp:185:12: error: use of undeclared identifier 'fseeko64'
    return fseeko64(f, offset, origin);
           ^
3 errors generated.
```
[install-x64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/12865993/install-x64-android-dbg-out.log)

2023-10-12 04:03 UTC, dg0yt commented on ports/zoe/portfile.cmake
> +endif()
```suggestion
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" ZOE_BUILD_SHARED_LIBS)
string(COMPARE EQUAL "${VCPKG_CRT_LINKAGE}" "static" ZOE_USE_STATIC_CRT)
```

BTW vcpkg already set `BUILD_SHARED_LIBS`, the standard variable.

2023-10-12 04:03 UTC, dg0yt commented on ports/zoe/portfile.cmake
> +    vcpkg_cmake_config_fixup(CONFIG_PATH share/zoe)
This will detect but not touch files in `/share/libGet`.

2023-10-20 07:33 UTC, winsoft666 commented
I successfully tested the following command on Windows 11, but automatic checks were not successful.
```
vcpkg install crashrpt-lite:x64-windows
```

2023-10-20 08:20 UTC, winsoft666 commented
> @FrankXie05 I add a new port that named crashrpt-lite on this pr. I don't know if this operation is compliant.

I have removed crashrpt-lite port.

2023-10-20 08:28 UTC, winsoft666 commented
@FrankXie05 @FrankXie05 Could you help me merge this pr?

2023-10-24 02:24 UTC, FrankXie05 approved these changes, later dismissed

2023-10-27 01:34 UTC, winsoft666 commented
> @winsoft666 Only one question: Is the port `Header-only`? :)

No

2023-10-27 02:36 UTC, FrankXie05 commented
> > @winsoft666 Only one question: Is the port `Header-only`? :)
> 
> No

Then we should provide usage for this port to use lib. :)

2023-10-27 02:43 UTC, winsoft666 commented
> > > @winsoft666 Only one question: Is the port `Header-only`? :)
> > 
> > 
> > No
> 
> Then we should provide usage for this port to use lib. :)

Do you need me to do anything?

2023-10-27 02:45 UTC, FrankXie05 commented
@winsoft666 Yes, we need export cmake config files.

2023-10-27 08:10 UTC, winsoft666 commented
> @winsoft666 Yes, we need export cmake config files.

Just add usage file into port, like these?
```txt usage
The package zoe is compatible with built-in CMake targets:

    find_package(zoe REQUIRED)
    target_link_libraries(main PRIVATE zoe)
```

2023-10-31 02:15 UTC, winsoft666 commented
@FrankXie05 Thanks for your PR, I have merged.

2023-10-31 02:34 UTC, FrankXie05 commented
The usage has been tested successfully locally.
```
zoe provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(zoe CONFIG REQUIRED)
  target_link_libraries(main PRIVATE zoe::zoe)
```

2023-10-31 04:03 UTC, dg0yt commented on ports/zoe/portfile.cmake
> +endif()
Why doesn't upstream always install to the same location... Both paths are good for all platforms.
And this code supports the no-config case (due to lack of unconditional  `else`). Do we want this?

2023-10-31 06:23 UTC, FrankXie05 requested changes

2023-10-31 06:23 UTC, FrankXie05 commented on ports/zoe/portfile.cmake
> +endif()
Just add this.
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH share/zoe)
```

2023-10-31 07:37 UTC, winsoft666 commented on ports/zoe/portfile.cmake
> +endif()
Thanks, I have update cmake.

2023-10-31 07:38 UTC, FrankXie05 requested changes

2023-10-31 07:38 UTC, FrankXie05 commented on ports/zoe/portfile.cmake
> +file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion
```
No need to add the `usage`, cmake will automatically export the correct usage.

2023-10-31 14:27 UTC, winsoft666 commented on ports/zoe/portfile.cmake
> +file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
> No need to add the `usage`, cmake will automatically export the correct usage.

Updated

2023-11-01 01:55 UTC, FrankXie05 approved these changes

2023-11-01 20:14 UTC, merged