[matio] Add usage
microsoft/vcpkg pull request #34505
Opened 2023-10-16 07:59 UTC by jimwang118

Fixes https://github.com/microsoft/vcpkg/issues/34488

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

2023-10-17 06:43 UTC, dg0yt commented on ports/matio/usage
> +matio provides usage:
Don't invent new text.
```suggestion
matio can be imported via CMake FindPkgConfig module:
```

2023-10-17 06:47 UTC, dg0yt requested changes
Maybe you need to test the usage?

2023-10-17 06:47 UTC, dg0yt commented on ports/matio/portfile.cmake
> +set(exec_prefix \$\{prefix\})
Such patterns are simpler with 
```suggestion
set(exec_prefix [[${prefix}]])
```

2023-10-17 06:47 UTC, dg0yt commented on ports/matio/portfile.cmake
> +endif()
```suggestion
file(INSTALL "${SOURCE_PATH}/matio.pc" DESTINATION "${CURRENT_PACKAGES_DIR}/lib/pkgconfig")
if(NOT VCPKG_BUILD_TYPE)
    set(includedir [[${prefix}/../include]])
    file(INSTALL "${SOURCE_PATH}/matio.pc" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig")
endif()
```
At least the include dir change.

2023-10-18 07:30 UTC, dg0yt commented on ports/matio/portfile.cmake
>  set(includedir \$\{prefix\}/include)
... I didn't want to flag every line because I assumed the pattern can be recognized.

2023-10-18 08:33 UTC, jimwang118 commented on ports/matio/portfile.cmake
>  set(includedir \$\{prefix\}/include)
> ... I didn't want to flag every line because I assumed the pattern can be recognized.

Okay, I'll fix the rest too.

2023-10-23 10:48 UTC, MonicaLiu0311 approved these changes

2023-10-23 18:35 UTC, merged