[pravila00-enum-string] New port
microsoft/vcpkg pull request #34518
Opened 2023-10-16 17:35 UTC by Pravila00

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] <del> The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines. </del> 
- [ ] <del> Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html) </del> 
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] <del> The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context. </del>
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2023-10-17 06:55 UTC, FrankXie05 requested changes

2023-10-17 06:55 UTC, FrankXie05 commented on ports/pravila00-enum-string/vcpkg.json
> +  "version-date": "2023-16-10",
```suggestion
  "version-date": "2023-10-16",
```
Note the format：
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/versioning.md#version-date

2023-10-17 06:55 UTC, FrankXie05 commented on ports/pravila00-enum-string/portfile.cmake
> +vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

```
Empty line in the end.

2023-10-17 06:55 UTC, FrankXie05 commented on ports/pravila00-enum-string/portfile.cmake
> +vcpkg_from_github(
```suggestion
# Header-only library

vcpkg_from_github(
```

2023-10-17 06:55 UTC, FrankXie05 commented on ports/pravila00-enum-string/portfile.cmake
> +file(COPY "${SOURCE_PATH}/EnumString.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include/enum-string")
```suggestion
file(COPY "${SOURCE_PATH}/EnumString.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
```
I don't think it's necessary to have a port that starts with the author's name.

2023-10-17 06:55 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2023-10-17 14:46 UTC, Pravila00 commented on ports/pravila00-enum-string/portfile.cmake
> +file(COPY "${SOURCE_PATH}/EnumString.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include/enum-string")
Sure, it is fine with me. I've just removed the author's name from the beginning :)

2023-10-17 14:54 UTC, Pravila00 commented
This should be for review again @FrankXie05, thanks a lot!

2023-10-18 02:32 UTC, FrankXie05 approved these changes, later dismissed

2023-10-18 17:48 UTC, JavierMatosD commented
The port LGTM, but since this is a new library and it doesn't show up on repology, could you change the port's name? We typically request that newer libraries add a prefix to the name.

2023-10-19 10:50 UTC, Pravila00 commented
@JavierMatosD I have added again the prefix for the port, let me know if it looks good to you. Thanks!

2023-10-19 17:51 UTC, merged