Add JavaScriptCore port
microsoft/vcpkg pull request #34604
Opened 2023-10-19 13:49 UTC by bavulapati

Refs: #32555

2023-10-19 14:04 UTC, bavulapati commented
Another noob question:
Every time I try to test my changes, I'm using `vcpkg install` and this results in cleaning and extracting the source. In this case, it is taking 12 minutes for me. Is there any way to avoid this to speed my development process?
Thanks!

2023-10-19 16:05 UTC, Osyotr commented
> Another noob question: Every time I try to test my changes, I'm using `vcpkg install` and this results in cleaning and extracting the source. In this case, it is taking 12 minutes for me. Is there any way to avoid this to speed my development process? Thanks!

`vcpkg install javascriptcore --editable`

2023-10-20 05:59 UTC, bavulapati commented
@microsoft-github-policy-service agree company="Postman"

2023-11-21 07:51 UTC, ylluminate commented
Where does this port currently stand in your efforts @bavulapati? Your effort looks to be quite promising for a solid native Windows release.

2023-11-28 12:22 UTC, bavulapati commented
@ylluminate We are actively working on porting the javascriptcore to vcpkg.
We were encountering an issue with webkit finding the dependencies like cairo, icu, etc.,
Webkit was monkey patching the find_package. We are patching it to unblock us.
We will share more when we make progress.

2023-12-19 13:03 UTC, bavulapati commented
@Osyotr @jviotti @raisinten 
The javascriptcore port is building and 
The PR is ready for review.
Please take a look.

2023-12-19 13:17 UTC, bavulapati commented
This port currently supports only windows x64 with dynamic linking or DLLs

2023-12-19 13:53 UTC, Osyotr requested changes

2023-12-19 13:53 UTC, Osyotr commented on ports/javascriptcore/portfile.cmake
> +
```suggestion
```
This is a part of a toolchain, not a port.

2024-01-02 11:20 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
> +
@Osyotr The PR now uses ICU dependency from vcpkg. This is removed.

2024-01-02 11:21 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
> +
@Osyotr The PR now uses ICU dependency from vcpkg.

2024-01-02 11:21 UTC, bavulapati commented on ports/javascriptcore/usage
> +set(JavaScriptCore_FOUND TRUE)
Removed.

2024-01-02 11:21 UTC, bavulapati commented on ports/javascriptcore/usage
> +set(JavaScriptCore_FOUND TRUE)
Removed.

2024-01-02 11:29 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
> +
removed.

2024-01-02 11:30 UTC, bavulapati commented
@Osyotr Addressed your review comments.
Please take another look.
Thanks!

2024-01-02 12:28 UTC, Osyotr reviewed
I think this port can be greatly simplified by switching to `-DPORT=JSCOnly`, though you would probably need to fix this https://github.com/WebKit/WebKit/blob/5ddbccf5974982d2fc1902c78dadffb0c98b4afd/Source/cmake/OptionsJSCOnly.cmake#L56-L62

2024-01-02 12:28 UTC, Osyotr commented on ports/javascriptcore/portfile.cmake
> +message(STATUS "RUBY_PATH: ${RUBY_PATH}")
```suggestion
```
This is redundant (ditto below)

2024-01-02 12:28 UTC, Osyotr commented on ports/javascriptcore/portfile.cmake
> +      -DPORT=WinCairo
```suggestion
      -DPORT=JSCOnly
```

2024-01-02 12:28 UTC, Osyotr commented on ports/javascriptcore/tune_jsconly_options.patch
> ++find_package(JPEG 1.5.2)
If you remove REQUIRED, you should add `CMAKE_DISABLE_FIND_PACKAGE_<pkg>` to the portfile.

2024-01-02 15:24 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
> +message(STATUS "RUBY_PATH: ${RUBY_PATH}")
removed.

2024-01-02 15:39 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
> +      -DPORT=WinCairo
Changed the PORT.

2024-01-02 15:40 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_options.patch
> ++find_package(JPEG 1.5.2)
With JSCOnly port, we are not removing REQUIRED.

2024-01-02 15:41 UTC, bavulapati commented
@Osyotr Updated the PR with JSCOnly port.
Please take another look.
Thanks.

2024-01-02 15:51 UTC, Osyotr commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
```suggestion
```
`find_package(ICU ...)` does not require any additional setup. Is there a particular error that you encountered?

2024-01-02 15:51 UTC, Osyotr commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++    set(PORT Win)
Does it have any impact at this point?

2024-01-02 15:51 UTC, Osyotr commented on ports/javascriptcore/portfile.cmake
>  vcpkg_cmake_build(
Now that you use `JSCOnly` port, you can call `vcpkg_cmake_install` directly and get rid of `file(INSTALL ...)` calls below.

2024-01-02 17:02 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
The components aren't found. Here's the error log:
```
CMake Error at D:/repos/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find all ICU components (missing: ICU_INCLUDE_DIR
  _ICU_REQUIRED_LIBS_FOUND) (Required is at least version "61.2")
Call Stack (most recent call first):
  D:/repos/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  D:/repos/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/FindICU.cmake:333 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  D:/repos/vcpkg/installed/x64-windows/share/icu/vcpkg-cmake-wrapper.cmake:6 (_find_package)
  D:/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:813 (include)
  Source/cmake/OptionsJSCOnly.cmake:111 (find_package)
  Source/cmake/WebKitCommon.cmake:228 (include)
  CMakeLists.txt:21 (include)
```

2024-01-02 17:03 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
The output log:
```
-- Found the following ICU libraries:
--   i18n (required): C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64/icuin.Lib
--   uc (required): C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64/icuuc.lib
-- The following ICU libraries were not found:
--   data (required)
-- Configuring incomplete, errors occurred!
```

2024-01-02 18:32 UTC, dg0yt commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
This is not icu from vcpkg.

2024-01-03 12:50 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++    set(PORT Win)
The JSCOnly port needed to use the hack from win port. Added the lowlevelinterpreter asm.

2024-01-03 12:52 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
Yes, that's the problem if we do not provide the ICU_ROOT, ICU_INCLUDE_DIR variables.
@dg0yt @Osyotr Any thoughts?

2024-01-03 13:03 UTC, Osyotr commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
Add `--trace-expand` to the `OPTIONS` parameter in the `vcpkg_cmake_configure` call and collect the log.

2024-01-03 20:19 UTC, dg0yt commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
You probably stumble over `Source/cmake/WebKitFindPackage.cmake` doing the same as vcpkg: Overriding `find_package`. And so breaking the loading of wrappers from vcpkg.

We can probably get rid of that WebKit's override, given that vcpkg has recent versions of CMake and the packages.
A patch may simply rename that macro, e.g. to `find_package_unused`.

[Source/cmake/WebKitFindPackage.cmake](https://github.com/WebKit/WebKit/blob/ac784c090ce396d3b17092ca7ad4ac8968c48f8f/Source/cmake/WebKitFindPackage.cmake)

2024-01-03 20:21 UTC, dg0yt commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
OTOH my explanation doesn't match the CMake call stack...

2024-01-05 06:41 UTC, Adela0814 requested changes

2024-01-05 06:41 UTC, Adela0814 commented on ports/javascriptcore/vcpkg.json
> +  "dependencies": [
Please add license and homepage.

2024-01-05 06:41 UTC, Adela0814 commented on ports/javascriptcore/vcpkg.json
> +  "port-version": 10,
Please remove the `port-version`.

2024-01-05 06:41 UTC, Adela0814 commented on ports/javascriptcore/vcpkg.json
> +  "version": "6.0",
Where did you get this 0.6 from? I couldn't find it upstream.

2024-01-17 06:38 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/13959533/config-x64-windows-out.log)
@Osyotr Attached the logs with trace options specified. Let me know if you have any comments

2024-01-17 06:38 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
>  vcpkg_cmake_build(
@Osyotr Made the change.

2024-01-17 07:26 UTC, dg0yt commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
Hm, I can't see from the log why `find_library` doesn't find/use the icu libs from vcpkg. And `find_path` doesn't find the include dir.  
vcpkg does find the wrapper, and `FindICU.cmake` does find the icu tools from vcpkg.

The next step would be to insert `set(CMAKE_FIND_DEBUG_MODE 1)` before `find_package(ICU ...)`.

2024-01-17 08:03 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
@dg0yt Thanks for taking a glance. Attaching the logs with `set(CMAKE_FIND_DEBUG_MODE 1)`
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/13960226/config-x64-windows-out.log)

2024-01-17 08:28 UTC, Osyotr commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
Probably this (should be `list(APPEND)` instead of `set()`):
https://github.com/WebKit/WebKit/blob/b65f4ed6d7773e43c59f050351d01b7396f8e0d8/Source/cmake/OptionsJSCOnly.cmake#L77
https://github.com/WebKit/WebKit/blob/b65f4ed6d7773e43c59f050351d01b7396f8e0d8/CMakeLists.txt#L20

2024-01-17 09:00 UTC, dg0yt commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
> https://github.com/WebKit/WebKit/blob/b65f4ed6d7773e43c59f050351d01b7396f8e0d8/Source/cmake/OptionsJSCOnly.cmake#L77

This one. (I looked for CMAKE_PREFIX_PATH, but I missed it.)

2024-01-17 10:00 UTC, bavulapati commented on ports/javascriptcore/tune_jsconly_port_for_windows.patch
> ++set(ICU_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
Yes. Appending to `CMAKE_PREFIX_PATH` made it right. 👍🏾
Thanks!

2024-01-17 10:31 UTC, bavulapati commented on ports/javascriptcore/vcpkg.json
> +  "dependencies": [
@Adela0814 Adding homepage but according to https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#license, will have to leave license as empty.
As the license is a combination of LICENSE-APPLE and LICENSE-LGPL-2.1 
And that combination is provided as `copyright` file.

2024-01-17 10:32 UTC, bavulapati commented on ports/javascriptcore/vcpkg.json
> +  "port-version": 10,
A noob question!
Is it not required?

2024-01-18 06:19 UTC, bavulapati commented on ports/javascriptcore/vcpkg.json
> +  "version": "6.0",
I got it from https://webkitgtk.org/reference/jsc-glib/unstable/index.html

2024-01-18 07:30 UTC, Osyotr commented on ports/javascriptcore/vcpkg.json
> +  "version": "6.0",
> API Version: 6.0
Library Version: 2.43.3

2024-01-18 09:42 UTC, bavulapati commented on ports/javascriptcore/vcpkg.json
> +  "version": "6.0",
but the webkt versioning strategy seems to be different from webkitgtk versioning.
And the webkit community is [suggesting](https://webkit.slack.com/archives/CTV4FGWF4/p1705560897343739?thread_ts=1705486610.114179&cid=CTV4FGWF4) to use dates.

2024-01-18 14:31 UTC, bavulapati commented
Checking the builds on osx and linux. Will post the findings.

2024-01-18 19:51 UTC, dg0yt commented on ports/javascriptcore/vcpkg.json
> +  "dependencies": [
This is not resolved. The proper change is:
```suggestion
  "license": null,
  "dependencies": [
```
where `null` means: Too complex, please read the copyright file.

2024-01-19 06:14 UTC, bavulapati commented
> Checking the builds on osx and linux. Will post the findings.

ICU on osx and linux is creating issues. There's an existing issue https://github.com/microsoft/vcpkg/issues/36171

We can go ahead with windows only for this PR.

2024-01-19 06:16 UTC, dg0yt commented
> > Checking the builds on osx and linux. Will post the findings.
> 
> ICU on osx and linux is creating issues. There's an existing issue #36171
> 
> We can go ahead with windows only for this PR.

#36171 is not a blocker. Many packages need `autoconf-archive`.

2024-01-19 06:22 UTC, dg0yt commented
~~~
FAILED: bin/TestWebKitAPI/TestWTF 
...
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libicuuc.a(udata.ao): in function `openCommonData(char const*, int, UErrorCode*)':
/mnt/vcpkg-ci/b/icu/x64-linux-dbg/common/.././../src/c-74_1-src-8ca76704fa.clean/source/common/udata.cpp:699: undefined reference to `icudt74_dat'
/usr/bin/ld: /mnt/vcpkg-ci/b/icu/x64-linux-dbg/common/.././../src/c-74_1-src-8ca76704fa.clean/source/common/udata.cpp:722: undefined reference to `icudt74_dat'
~~~
So the question is why it doesn't in link the ICU data lib.
(Another question is whether vcpkg has to build the `Test` stuff.)

2024-01-19 06:28 UTC, bavulapati commented
> > > Checking the builds on osx and linux. Will post the findings.
> > 
> > 
> > ICU on osx and linux is creating issues. There's an existing issue #36171
> > We can go ahead with windows only for this PR.
> 
> #36171 is not a blocker. Many packages need `autoconf-archive`.

But that makes the PR checks fail. And I noticed further linking issues after installing `autoconf-archive`.

2024-01-19 06:29 UTC, bavulapati commented
> ```
> FAILED: bin/TestWebKitAPI/TestWTF 
> ...
> /usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libicuuc.a(udata.ao): in function `openCommonData(char const*, int, UErrorCode*)':
> /mnt/vcpkg-ci/b/icu/x64-linux-dbg/common/.././../src/c-74_1-src-8ca76704fa.clean/source/common/udata.cpp:699: undefined reference to `icudt74_dat'
> /usr/bin/ld: /mnt/vcpkg-ci/b/icu/x64-linux-dbg/common/.././../src/c-74_1-src-8ca76704fa.clean/source/common/udata.cpp:722: undefined reference to `icudt74_dat'
> ```
> 
> So the question is why it doesn't in link the ICU data lib. (Another question is whether vcpkg has to build the `Test` stuff.)

vcpkg doesn't need to build the Test stuff.
I can try to disable and run the vcpkg pipeline again.

2024-01-19 06:47 UTC, dg0yt commented
> But that makes the PR checks fail.

No.

2024-01-19 07:04 UTC, bavulapati commented
@dg0yt How do we access the log files created by pipelines. for example https://dev.azure.com/vcpkg/public/_build/results?buildId=98677&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=a23dba4e-3a62-59dc-a73c-a7222676d7a4&l=6980 
`/Users/vagrant/Data/b/javascriptcore/config-x64-osx-out.log`

2024-01-19 07:06 UTC, bavulapati commented
I am able to configure `javascriptcore` locally after installing `autoconf-archive` but the pipeline is failing.
https://dev.azure.com/vcpkg/public/_build/results?buildId=98677&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=a23dba4e-3a62-59dc-a73c-a7222676d7a4&l=6980

2024-01-19 07:34 UTC, bavulapati commented
Locally, `vcpkg install javascriptcore` succeeds. But on pipeline, the configure fails for `x64-osx-rel` but succeeds for `x64-osx-dbg`.

Log from `config-x64-osx-out.log`
```
-- Performing Test CXX_COMPILER_SUPPORTS_-Wno-cast-align - Success
-- Using platform-specific CMakeLists: /Users/vagrant/Data/b/javascriptcore/src/1.27.211.1-64117d7fa2.clean/Source/WTF/wtf/PlatformJSCOnly.cmake
-- Copying generate-unified-source-bundles.rb to: /Users/vagrant/Data/b/javascriptcore/x64-osx-rel/WTF/Scripts
CMake Error at Source/WTF/CMakeLists.txt:8 (file):
  file COPY cannot set modification time on
  "/Users/vagrant/Data/installed/x64-osx/include/unicode/stringpiece.h": No
  such file or directory.
```
I checked for the file `installed/x64-osx/include/unicode/stringpiece.h`, it is available locally.

2024-01-19 07:56 UTC, Osyotr commented
https://github.com/WebKit/WebKit/blob/741a55f3d6f1dda9857b4d20d45a9f9125af9426/Source/WTF/CMakeLists.txt#L8

It shouldn't do that...

2024-01-19 08:12 UTC, bavulapati commented
> https://github.com/WebKit/WebKit/blob/741a55f3d6f1dda9857b4d20d45a9f9125af9426/Source/WTF/CMakeLists.txt#L8
> 
> It shouldn't do that...

Yes. We are not using the webkit's find_package.
Will diable that.

2024-01-19 08:14 UTC, bavulapati commented
> The logs are available as downloadable "artefacts" for that CI run.
> 
> * on the summary page via "<n> published", https://dev.azure.com/vcpkg/public/_build/results?buildId=98677&view=results
> * on the job page via "<n> artifacts produced", https://dev.azure.com/vcpkg/public/_build/results?buildId=98677&view=logs&j=84da4f4a-968a-5b5c-16e9-f444c845396d
> 
> On the artifacts page, hover the line of interest, and then click the three-dots icon on the right side, https://dev.azure.com/vcpkg/public/_build/results?buildId=98677&view=artifacts&pathAsName=false&type=publishedArtifacts.

Thanks!

2024-01-23 11:46 UTC, bavulapati commented
> > ```
> > FAILED: bin/TestWebKitAPI/TestWTF 
> > ...
> > /usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libicuuc.a(udata.ao): in function `openCommonData(char const*, int, UErrorCode*)':
> > /mnt/vcpkg-ci/b/icu/x64-linux-dbg/common/.././../src/c-74_1-src-8ca76704fa.clean/source/common/udata.cpp:699: undefined reference to `icudt74_dat'
> > /usr/bin/ld: /mnt/vcpkg-ci/b/icu/x64-linux-dbg/common/.././../src/c-74_1-src-8ca76704fa.clean/source/common/udata.cpp:722: undefined reference to `icudt74_dat'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So the question is why it doesn't in link the ICU data lib. (Another question is whether vcpkg has to build the `Test` stuff.)
> 
> vcpkg doesn't need to build the Test stuff. I can try to disable and run the vcpkg pipeline again.

The Linux build breaks while linking with ICU. It doesn't without vcpkg.
Can we merge the JavaScriptCore port for windows and later someone with the expertise and testing infrastructure can pick up the Linux stuff?
We don't intend to use JavaScriptCore on platforms other than windows.

2024-01-25 11:42 UTC, bavulapati commented
@Osyotr @dg0yt @Adela0814 Please take another look. Thanks!

2024-01-25 14:11 UTC, Osyotr reviewed
My personal opinion is that new ports in this repo should not exclude platforms that can be tested in CI.

2024-01-25 14:11 UTC, Osyotr commented on ports/javascriptcore/portfile.cmake
> +  set(ENABLE_STATIC_JSC ON)
Why is this ON?
According to CI file lists there is no `JavaScriptCore.dll` among produced artifacts and no `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` either.

2024-01-31 11:33 UTC, bavulapati commented on ports/javascriptcore/portfile.cmake
> +  set(ENABLE_STATIC_JSC ON)
Good Catch. Thanks. It shouldn't be ON for both the cases.

2024-02-22 06:32 UTC, JonLiu1993 commented on versions/j-/javascriptcore.json
> +      "port-version": 0
```suggestion
```

2024-03-05 06:39 UTC, JonLiu1993 commented
@bavulapati, When I tested the usage by `javascriptcore:x64-windows` I get this error, please take a look:
````
1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\test\source\repos\CMakeProject1\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=F:/Feature-test/javascri/scripts/buildsystems/vcpkg.cmake "C:\Users\test\source\repos\CMakeProject1" 2>&1"
1> Working directory: C:\Users\test\source\repos\CMakeProject1\out\build\x64-Debug
1> [CMake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
1> [CMake] -- The C compiler identification is MSVC 19.39.33519.0
1> [CMake] -- The CXX compiler identification is MSVC 19.39.33519.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] CMake Deprecation Warning at CMakeProject1/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 3.5 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] CMake Error at F:/Feature-test/javascri/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
1> [CMake]   By not providing "FindJavaScriptCore.cmake" in CMAKE_MODULE_PATH this
1> [CMake]   project has asked CMake to find a package configuration file provided by
1> [CMake]   "JavaScriptCore", but CMake did not find one.
1> [CMake] 
1> [CMake]   Could not find a package configuration file provided by "JavaScriptCore"
1> [CMake]   with any of the following names:
1> [CMake] 
1> [CMake]     JavaScriptCoreConfig.cmake
1> [CMake]     javascriptcore-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "JavaScriptCore" to CMAKE_PREFIX_PATH or set
1> [CMake]   "JavaScriptCore_DIR" to a directory containing one of the above files.  If
1> [CMake]   "JavaScriptCore" provides a separate development package or SDK, be sure it
1> [CMake]   has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeProject1/CMakeLists.txt:5 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> 'C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\test\source\repos\CMakeProject1\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=F:/Feature-test/javascri/scripts/buildsystems/vcpkg.cmake "C:\Users\test\source\repos\CMakeProject1" 2>&1"' execution failed with error: ''C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\test\source\repos\CMakeProject1\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=F:/Feature-test/javascri/scripts/buildsystems/vcpkg.cmake "C:\Users\test\source\repos\CMakeProject1" 2>&1"' returned with exit code: 1'.

````
I noticed that the share\javascriptcore directory does not have *.cmake file.

2024-06-27 20:55 UTC, BillyONeal commented
I converted this to draft because the usage problem reported by @JonLiu1993 above appears unaddressed?

2024-11-15 07:16 UTC, JonLiu1993 commented
Ping @bavulapati for response.

2025-01-16 07:52 UTC, JonLiu1993 commented
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

2025-01-16 07:52 UTC, closed without merging