[mpark-patterns] add new port
microsoft/vcpkg pull request #34679
Opened 2023-10-23 15:00 UTC by jiayuehua

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [X] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says.
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [X] Only one version is added to each modified port's versions file.

2023-10-25 03:17 UTC, MonicaLiu0311 commented on ports/mpark-patterns/vcpkg.json
> +  "homepage": "https://github.com/mpack/patterns/",
```suggestion
  "homepage": "https://github.com/mpark/patterns",
```

2023-10-25 03:24 UTC, MonicaLiu0311 commented on ports/mpark-patterns/usage
> +
When testing usage, the following error occurs:
```
1> [CMake] CMake Error at G:/mpark-patterns/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "mpark_patterns"
1> [CMake]   with any of the following names:
1> [CMake] 
1> [CMake]     mpark_patternsConfig.cmake
1> [CMake]     mpark_patterns-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "mpark_patterns" to CMAKE_PREFIX_PATH or set
1> [CMake]   "mpark_patterns_DIR" to a directory containing one of the above files.  If
1> [CMake]   "mpark_patterns" provides a separate development package or SDK, be sure it
1> [CMake]   has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
```

<details>
<summary><b>test.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "mpark/patterns.hpp"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "G:/mpark-patterns/scripts/buildsystems/vcpkg.cmake")

project ("test")

add_library (main "test.cpp")

find_package(mpark_patterns CONFIG REQUIRED)
target_link_libraries(main PRIVATE mpark_patterns)
</pre></details>

2023-10-25 05:51 UTC, jiayuehua commented on ports/mpark-patterns/usage
> +
shoule be ok now.

2023-10-25 05:51 UTC, jiayuehua commented on ports/mpark-patterns/vcpkg.json
> +  "homepage": "https://github.com/mpack/patterns/",
has fixed.

2023-10-26 01:36 UTC, FrankXie05 requested changes

2023-10-26 01:36 UTC, FrankXie05 commented on ports/mpark-patterns/vcpkg.json
> +  "homepage": "https://github.com/mpack/patterns",
```suggestion
  "homepage": "https://github.com/mpark/patterns",
```
It has not been fixed.

2023-10-26 01:54 UTC, FrankXie05 requested changes

2023-10-26 01:54 UTC, FrankXie05 commented on ports/mpark-patterns/vcpkg.json
> +  "version-date": "2019-10-03",
```suggestion
  "version-date": "2019-10-03",
```
Why update to master instead of `v0.3.0` https://github.com/mpark/patterns/releases/tag/v0.3.0 ?
It seems it has been a few years since the last maintenance.

2023-10-26 02:42 UTC, jiayuehua commented on ports/mpark-patterns/vcpkg.json
> +  "version-date": "2019-10-03",
I think [Workaround for GCC 8.1.](https://github.com/mpark/patterns/commit/23fbb3b64188e69137ef1ecff64da2dfdef9e340) [Fixed](https://github.com/mpark/patterns/commit/23fbb3b64188e69137ef1ecff64da2dfdef9e340) https://github.com/mpark/patterns/issues/9[.](https://github.com/mpark/patterns/commit/23fbb3b64188e69137ef1ecff64da2dfdef9e340)  and [Fixed linker error by defining a function.](https://github.com/mpark/patterns/commit/bd4b9b82d1e45358eaf27015cd314c574f32a6d4) those two commits that on master has fix serious bug which after v0.3.0

2023-10-26 02:43 UTC, jiayuehua commented on ports/mpark-patterns/vcpkg.json
> +  "homepage": "https://github.com/mpack/patterns",
this time has fixed. I only have notice the '/'

2023-10-26 05:50 UTC, FrankXie05 approved these changes

2023-10-26 05:50 UTC, FrankXie05 commented
The usage has been tested successfully locally.

2023-10-26 08:06 UTC, MonicaLiu0311 approved these changes

2023-10-27 03:58 UTC, data-queue approved these changes

2023-10-27 03:58 UTC, merged