[quantum] add new port
microsoft/vcpkg pull request #34682
Opened 2023-10-23 16:43 UTC by jiayuehua

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [X] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says.
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [X] Only one version is added to each modified port's versions file.

2023-10-24 08:34 UTC, Adela0814 requested changes

2023-10-24 08:34 UTC, Adela0814 commented on ports/quantum/vcpkg.json
> +  "name": "quantum",
Suggest you change the port name (with a prefix or suffix). What I found through this name is https://github.com/microsoft/Quantum.

2023-10-24 08:34 UTC, Adela0814 commented on ports/quantum/usage
> +
Please remove excess blank lines at the end of the file.

2023-10-24 09:02 UTC, jiayuehua commented on ports/quantum/vcpkg.json
> +  "name": "quantum",
change to bloomberg-quantum?

2023-10-24 09:23 UTC, jiayuehua commented on ports/quantum/vcpkg.json
> +  "name": "quantum",
But microsoft/quantum is a Q# project, Is it still need to change change name?

2023-10-25 10:24 UTC, Adela0814 approved these changes, later dismissed

2023-10-25 10:25 UTC, Adela0814 commented
Usage tested pass on `x64-windows`.

2023-10-27 03:53 UTC, data-queue commented on ports/bloomberg-quantum/change-project-name.patch
> ++project(unofficial-bloomberg-quantum LANGUAGES CXX)
What is the intent of this patch? If it is to add the unofficial namespace to the exported target, I think it will be clearer if we patch the `install(EXPORT ...)` command directly.

2023-10-28 02:57 UTC, data-queue approved these changes

2023-10-28 02:57 UTC, merged