Fixes #34796
microsoft/vcpkg pull request #34800
Opened 2023-10-30 14:04 UTC by olejniczak

Fixes #34796

2023-10-31 07:01 UTC, jimwang118 commented
You need to run the command:`./vcpkg x-add-version {portname}` and submit the generated file.

2023-10-31 07:47 UTC, olejniczak commented
I wanted to fix #34537 pull request. In my pr there is no version change.

2023-10-31 08:38 UTC, jimwang118 commented
> I wanted to fix #34537 pull request. In my pr there is no version change.



> I wanted to fix #34537 pull request. In my pr there is no version change.

The above command is to update the version number and commit record defined in `vcpkg`. You can refer to our [maintainer-guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#versioning) on how to modify the version.

2023-11-17 02:39 UTC, jimwang118 requested changes

2023-11-17 02:39 UTC, jimwang118 commented on ports/protobuf/vcpkg.json
>    "homepage": "https://github.com/protocolbuffers/protobuf",
You need to add the keyword "port-version": 1.

2023-11-17 02:39 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-11-21 12:40 UTC, olejniczak commented
Thank you for your help. Yes, indeed, it was some recommendations, hopefully there are reasonable.

2023-11-21 14:41 UTC, dg0yt commented
Please use a more telling PR title. It will become part of the git history.

2023-11-29 10:38 UTC, closed without merging