[libtheora] install pkg-config files
microsoft/vcpkg pull request #34904
Opened 2023-11-04 16:49 UTC by luncliff

### Changes

Generate/Install `.pc` files for pkg-config users.

### References

* https://github.com/microsoft/vcpkg/pull/28204 (previous update)

### Checklist

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-11-14 07:24 UTC, dg0yt commented on ports/libtheora/CMakeLists.txt
> +set(VERSION "1.2.0-alpha1")
Maintenance trap. Can this follow some variable? If nothing is available in the project, derive from `VERSION` in portfile.

2023-11-14 08:33 UTC, luncliff commented on ports/libtheora/CMakeLists.txt
> +set(VERSION "1.2.0-alpha1")
I will check if other ports have similar patterns or solutions.

2023-11-16 06:30 UTC, dg0yt requested changes

2023-11-16 06:30 UTC, dg0yt commented on ports/libtheora/CMakeLists.txt
> +  FILES ${PROJECT_BINARY_DIR}/theora.pc ${PROJECT_BINARY_DIR}/theoradec.pc ${PROJECT_BINARY_DIR}/theoraenc.pc
```suggestion
  FILES "${PROJECT_BINARY_DIR}/theora.pc" "${PROJECT_BINARY_DIR}/theoradec.pc" "${PROJECT_BINARY_DIR}/theoraenc.pc"
```

2023-11-16 06:30 UTC, dg0yt commented on ports/libtheora/portfile.cmake
> +        -DVERSION:STRING="${VERSION}"
```suggestion
        "-DVERSION:STRING=${VERSION}"
```
Quoting for CMake, not for the shell.

2023-11-16 06:31 UTC, dg0yt commented on ports/libtheora/CMakeLists.txt
> +include(GNUInstallDirs)
```suggestion
```
Probably unused.

2023-11-20 09:07 UTC, FrankXie05 approved these changes

2023-11-21 03:31 UTC, data-queue approved these changes

2023-11-21 03:31 UTC, merged