[luajit] add usage
microsoft/vcpkg pull request #34991
Opened 2023-11-09 06:29 UTC by Adela0814

Fixes https://github.com/microsoft/vcpkg/issues/34954

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-11-09 06:40 UTC, dg0yt commented
Or just wait for https://github.com/microsoft/vcpkg-tool/pull/1268.

2023-11-11 08:32 UTC, Pospelove requested changes
quick moment: should be `usage`, not `Usage`

2023-11-13 06:58 UTC, dg0yt commented
This PR becomes obsolete when https://github.com/microsoft/vcpkg-tool/pull/1268 is accepted/merged/released.

2024-01-05 06:44 UTC, Adela0814 commented
Fixed by https://github.com/microsoft/vcpkg-tool/pull/1268.

2024-01-05 06:44 UTC, closed without merging