[fontconfig] fix pkgconfig data file installation
microsoft/vcpkg pull request #35003
Opened 2023-11-09 15:09 UTC by SchaichAlonso

Fixes #35002 .

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~SHA512s are updated for each updated download~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-11-09 15:22 UTC, SchaichAlonso commented
Seems the trivial attempt to fix it breaks more then it fixes...

2023-11-09 15:50 UTC, dg0yt commented
... there is nothing to fix on the supported platforms. The problem might be freebsd-only.

2023-11-09 20:19 UTC, SchaichAlonso commented
> ... there is nothing to fix on the supported platforms. The problem might be freebsd-only.

Indeed. It turns out meson has hardcoded the pkgconfig installation paths the different platforms, with [FreeBSD installing to libdata](https://github.com/mesonbuild/meson/blob/bb91cea0d66d8d036063dedec1f194d663399cdf/mesonbuild/modules/pkgconfig.py#L587) unless `install_dir` is specified [...]

2023-11-10 15:02 UTC, SchaichAlonso commented
This issue also seems to affect all meson ports, rather then only fontconfig -> cairo.

Rather then patching 20-ish ports to set `install_dir` explicitly, patching `vcpkg-tool-meson` to not provide different pc-file paths for different platforms might be more appropriate.

2023-11-10 15:08 UTC, Neumann-A commented
>  patching vcpkg-tool-meson

You mean directly patching meson. Im fine with patching meson. It is a hard coding mess any way. Installation directories/layout should be user specifiable but that is something meson will never understand

2023-11-13 02:02 UTC, jimwang118 commented
The function vcpkg_apply_patches is deprecated. Please use the PATCHES arguments to the "extract" helpers (for example, vcpkg_from_github() (https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_from_github))

2023-11-17 02:40 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-11-21 06:02 UTC, SchaichAlonso commented
Rewrote the download code of the portfile and regenerated the patches.

Sorry it took me so long, I had connectivity issues last week.

2023-12-05 02:45 UTC, jimwang118 commented on ports/vcpkg-tool-meson/vcpkg.json
>    "version": "0.63",
Check that the latest meson version upstream is 1.3.0. Can't this version be updated to the latest one?

2023-12-05 02:46 UTC, jimwang118 requested changes

2023-12-05 02:46 UTC, jimwang118 commented on ports/vcpkg-tool-meson/portfile.cmake
> +    REF bb91cea0d66d8d036063dedec1f194d663399cdf
```suggestion
    REF "${VERSION}"
```

2023-12-05 02:46 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-12-05 04:26 UTC, dg0yt commented on ports/vcpkg-tool-meson/vcpkg.json
>    "version": "0.63",
The update to meson 1.3.0 is out of scope for this PR. This PR should be kept minimal to minimize merge avoid conflicts.
Cf. https://github.com/microsoft/vcpkg/pull/28084, https://github.com/microsoft/vcpkg/pull/35348.

2023-12-07 07:46 UTC, SchaichAlonso commented on ports/vcpkg-tool-meson/portfile.cmake
> +    REF bb91cea0d66d8d036063dedec1f194d663399cdf
I can bump the version to ${VERSION}, which is `0.63`, however that will represent a major change, since despite being registered to vcpkg as `vcpkg-tool-meson-0.63#1`, bb91cea0d66d8d036063dedec1f194d663399cdf@mesonbuild/meson is actually meson `0.62.1` as the ref bit was forgotten to be updated in ce9f50f7aca5efa734b73f89434cbc1b44d8759e .

2023-12-07 07:55 UTC, SchaichAlonso commented on ports/vcpkg-tool-meson/portfile.cmake
> +    REF bb91cea0d66d8d036063dedec1f194d663399cdf
updated it. pango and its' dependencies seem to build with 0.63 over here, didn't check the others

2023-12-08 22:34 UTC, SchaichAlonso commented
Seems `gobject-instrospection` fails to build on x64-windows with meson-0.63, so i'll revert the meson version update part, as fixing meson version update regressions should be handled by their own tickets / PRs.

2023-12-08 22:41 UTC, SchaichAlonso commented on ports/vcpkg-tool-meson/portfile.cmake
> +    REF bb91cea0d66d8d036063dedec1f194d663399cdf
The CI failed to build gobject-introspection with meson 0.63 so I'm reverting the meson version upgrade commit.

2023-12-11 02:19 UTC, jimwang118 approved these changes

2023-12-13 11:02 UTC, merged

2023-12-13 20:39 UTC, BillyONeal commented
LGTM