[opencascade] fix build using mingw
microsoft/vcpkg pull request #35063
Opened 2023-11-12 22:16 UTC by paulbuechner

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

This PR fixes an issue when building using msys mingw setup on windows using the `x64-mingw` community triplet, where the generated `/bin` and `/lib` layout is not suffixed with `d` and therefore files dont need to be moved. 

Currently, cmake will end up throwing an error stating that `${CURRENT_PACKAGES_DIR}/debug/libd` does not exist... this PR fixes this issue(s).

2023-11-12 22:17 UTC, paulbuechner commented
@microsoft-github-policy-service agree

2023-11-13 07:07 UTC, MonicaLiu0311 submitted a review, later dismissed

2023-11-13 07:18 UTC, dg0yt requested changes
Idiomatic in vcpkg portfiles:
~~~cmake
if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)

2023-11-13 07:18 UTC, dg0yt commented on ports/opencascade/portfile.cmake
> +if(WIN32 AND NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "MinGW")
```suggestion
if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
```

2023-11-13 07:18 UTC, dg0yt commented on ports/opencascade/portfile.cmake
> +    if (NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "MinGW")
Integrate into the outer `if` instead:
~~~
if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW AND VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")

2023-11-15 02:54 UTC, MonicaLiu0311 approved these changes

2023-11-15 03:50 UTC, dg0yt requested changes
Let me try to create an alternative PR which generally gets rid of the trailing `d`.

2023-11-15 05:50 UTC, paulbuechner commented
This would result in a patch then, right? I appreciate that, let's see if it works.

2023-11-15 06:27 UTC, MonicaLiu0311 commented
Temporarily remove the `info:reviewed` flag.

We don't have a mingW machine to test on, so thanks for discussing and fixing it.

2023-11-15 07:17 UTC, paulbuechner commented
For reference #35119

2023-11-22 02:31 UTC, MonicaLiu0311 commented
If this PR is replaced by https://github.com/microsoft/vcpkg/pull/35119, then please close this.

2023-11-22 08:08 UTC, closed without merging