[aws-c-http] update to 0.7.14
microsoft/vcpkg pull request #35070
Opened 2023-11-13 06:09 UTC by jiayuehua

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2023-11-14 02:42 UTC, jimwang118 requested changes

2023-11-14 02:42 UTC, jimwang118 commented on ports/aws-c-common/vcpkg.json
> +  "version": "0.9.8",
The latest upstream version is 0.9.9.

2023-11-14 02:42 UTC, jimwang118 commented on ports/aws-c-s3/vcpkg.json
> +  "version": "0.3.23",
The latest upstream version is 0.3.24.

2023-11-14 02:42 UTC, jimwang118 commented on ports/aws-crt-cpp/vcpkg.json
> +  "version": "0.24.5",
The latest upstream version is 0.24.7.

2023-11-14 02:42 UTC, jimwang118 commented on ports/aws-sdk-cpp/vcpkg.json
> +  "version": "1.11.200",
The latest upstream version is 1.11.201.

2023-11-14 02:42 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2023-11-15 01:40 UTC, jimwang118 approved these changes

2023-11-16 00:02 UTC, merged

2023-11-18 02:38 UTC, autoantwort commented
This resulted in https://github.com/microsoft/vcpkg/issues/35182