[dartsim] Fix correct usage
microsoft/vcpkg pull request #35121
Opened 2023-11-15 08:40 UTC by FrankXie05

Fix https://github.com/microsoft/vcpkg/issues/34985
```
# Targets - {dependency targets}, source directories, [external dependency libs]
#===============================================================================
# dart - common, math, integration, lcpsolver, optimizer, dynamics, collision,
#        collision/dart, collision/fcl, constraint, simulation, [eigen3, libccd,
#        fcl, assimp, boost]
```
https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/CMakeLists.txt#L42C12-L42C12

Add the usage to fix the correct dependency libs.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2023-11-15 08:45 UTC, FrankXie05 commented
The usage has been tested successfully locally on `x64-windows`.

2023-11-16 07:26 UTC, Adela0814 requested changes

2023-11-16 07:26 UTC, Adela0814 commented on ports/dartsim/usage
> +    target_link_libraries(main PRIVATE Eigen3::Eigen Boost::system ccd fcl assimp::assimp)
Please add a new line at the end of the file.

2023-11-16 08:04 UTC, dg0yt commented on ports/dartsim/usage
> +    target_link_libraries(main PRIVATE Eigen3::Eigen Boost::system ccd fcl assimp::assimp)
WHY?
The real problem is that the list of link libs makes no sense. These are dependencies, but not the usage for dartsim.

2023-11-16 08:12 UTC, dg0yt commented
You already visited https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/CMakeLists.txt#L38-L51: From this table, the targets are
~~~
dart
dart-optimizer-ipopt
...
~~~
so usage should have something like
~~~
    target_link_libraries(main PRIVATE <maybe-namespace::>dart)
    # Other targets: dart-optimizer-ipopt, ...
~~~

But I have no idea if they export everything and correctly. They also link dependencies with `PUBLIC`. Not an indicator for good practice.

2023-11-22 07:11 UTC, talregev commented
Any news on this fix?

2023-11-22 07:14 UTC, FrankXie05 commented
Exporting or disabling these targets for usage.
```
# dart-optimizer-ipopt - {dart}, optimizer/ipopt, [ipopt]
# dart-optimizer-nlopt - {dart}, optimizer/nlopt, [nlopt]
# dart-collision-bullet - {dart}, collision/bullet, [bullet]
# dart-utils - {dart}, utils, utils/sdf, [tinyxml2]
# dart-utils-urdf - {dart-utils}, utils/urdf, [urdfdom]
# dart-gui - {dart}, gui, [opengl, glut]
# dart-gui-osg - {dart-gui}, gui/osg, gui/osg/render, [openscenegraph]
# dart-planning - {dart}, planning, [flann]
```

2024-01-08 09:24 UTC, Adela0814 commented
Pinging @FrankXie05  for response. Is work still being done for this PR?

2024-01-08 09:41 UTC, FrankXie05 commented
https://github.com/dartsim/dart/issues/1770#issuecomment-1854792766

2025-06-27 07:16 UTC, closed without merging