[nethost] Bump to 8.0.0
microsoft/vcpkg pull request #35158
Opened 2023-11-16 20:47 UTC by julianxhokaxhiu

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

---

Bump the following ports:
- nethost: 7.0.0 -> 8.0.0

See also: https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/

2023-11-17 03:39 UTC, MonicaLiu0311 commented on ports/nethost/portfile.cmake
> +set(COMMIT_HASH "v${PRODUCT_VERSION}")
```suggestion
```

2023-11-17 03:40 UTC, MonicaLiu0311 commented on ports/nethost/portfile.cmake
>      REF ${COMMIT_HASH}
```suggestion
    REF "v${VERSION}"
```
${VERSION} is obtained from vcpkg.json.

2023-11-17 03:44 UTC, MonicaLiu0311 commented
-`file(INSTALL "${SOURCE_PATH}/LICENSE.TXT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)`
+`vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.TXT")`

2023-11-17 08:51 UTC, julianxhokaxhiu commented
Thanks @MonicaLiu0311 I applied all the suggestions. Feel free to review :)

2023-11-17 09:49 UTC, MonicaLiu0311 submitted a review, later dismissed

2023-11-18 17:55 UTC, dg0yt requested changes

2023-11-18 17:55 UTC, dg0yt commented on ports/nethost/portfile.cmake
>  endif()
~~~suggestion
file(MAKE_DIRECTORY "${SOURCE_PATH}/artifacts/obj")
set(copy_version_files  sh -c "${SOURCE_PATH}/eng/native/version/copy_version_files.sh")
if(VCPKG_HOST_IS_WINDOWS)
  set(copy_version_files  cmd /C "eng\\native\\version\\copy_version_files.cmd")
endif()
vcpkg_execute_required_process(
  COMMAND ${copy_version_files}
  WORKING_DIRECTORY "${SOURCE_PATH}"
  LOGNAME "copy_version_files-${TARGET_TRIPLET}"
)
~~~
Key change is `VCPKG_HOST_IS_WINDOWS`.
But everything else is nice to have, too.

2023-11-18 18:34 UTC, julianxhokaxhiu commented
Thanks @dg0yt applied your suggestions as well. Feel free to review :)

2023-11-20 06:44 UTC, MonicaLiu0311 commented
The usage test passed on `x64-windows` (header files found):
```
The package nethost can be used via CMake:

    find_package(unofficial-nethost CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::nethost::nethost)
```

2023-11-20 06:44 UTC, MonicaLiu0311 approved these changes

2023-11-22 02:59 UTC, data-queue approved these changes

2023-11-22 02:59 UTC, merged