[thomasmonkman-filewatch] Add patch for fixing Unix version
microsoft/vcpkg pull request #35236
Opened 2023-11-21 14:47 UTC by Pravila00

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2023-11-21 14:49 UTC, Pravila00 commented
This patch comes from https://github.com/ThomasMonkman/filewatch/pull/29, which trigger events on Unix as it does on Windows for having the same behaviour in both platforms.

2023-11-22 07:05 UTC, Adela0814 requested changes

2023-11-22 07:05 UTC, Adela0814 commented on versions/t-/thomasmonkman-filewatch.json
> +    },
Please restore the original git tree back.

2023-11-22 07:06 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-11-22 10:13 UTC, Pravila00 commented on versions/t-/thomasmonkman-filewatch.json
> +    },
Thanks! I've just restored the original git tree back, let me know if you need anything else from my side.

2023-11-22 10:25 UTC, Adela0814 approved these changes

2023-11-22 10:27 UTC, Adela0814 commented
This patch has been submitted to the upstream and has not responded for more than 2 years.

2023-11-29 09:11 UTC, merged