[veigar] Add new port.
microsoft/vcpkg pull request #35327
Opened 2023-11-26 09:27 UTC by winsoft666

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2023-11-28 07:03 UTC, Adela0814 requested changes

2023-11-28 07:03 UTC, Adela0814 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2023-11-28 10:29 UTC, Adela0814 requested changes

2023-11-28 10:29 UTC, Adela0814 commented on ports/veigar/portfile.cmake
> +    REF 9451b69dd9eb8956f25a1f63f550d80053741bbe
```suggestion
    REF ${VERSION}
```

2023-11-30 06:02 UTC, Adela0814 commented
@winsoft666  Usage test failed, unable to find header file in the test project.
Repro steps:

1. Install veigar: `./vcpkg install veigar`
2. Create a test cmake project and use the usage provided by vcpkg:
```
     find_package(veigar CONFIG REQUIRED)
     target_link_libraries(mainPRIVATE veigar::veigar)
```
3. Add `#include <veigar/veigar.h>` to cpp file.

2023-12-09 10:01 UTC, winsoft666 commented
@Adela0814 I think I have fixed this problem, could you take a look?

2023-12-09 12:03 UTC, dg0yt commented on ports/veigar/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH share/veigar)
```suggestion
vcpkg_cmake_config_fixup()
```
Default is `share/${PORT}`, so we don't need to be explicit.

2023-12-09 12:03 UTC, dg0yt commented on versions/v-/veigar.json
> +      "port-version": 0
```suggestion
```
Only one record can be added in a single PR.

2023-12-09 12:03 UTC, dg0yt commented on ports/veigar/vcpkg.json
> +  "supports": "(windows | linux) & !uwp",
```suggestion
  "supports": "linux | (windows & !uwp & !xbox)",
```
if it really doesn't support osx or android.

2023-12-11 08:02 UTC, Adela0814 commented
Usage test pass on `x64-windows`.

2023-12-11 08:07 UTC, Adela0814 approved these changes

2023-12-12 12:17 UTC, merged