[icu] Fix x64-windows-static building icu will generate complete icudt.lib
microsoft/vcpkg pull request #35416
Opened 2023-11-30 08:57 UTC by jimwang118

Fixes https://github.com/microsoft/vcpkg/issues/33358
Make tools only generated under ios.
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Compile test pass with following triplets:
```
x64-windows-static
```

2023-12-04 05:44 UTC, Adela0814 approved these changes

2023-12-04 07:28 UTC, dg0yt requested changes
With all respect: 
I don't get how this can get `info:reviewed` approval.

Does it even have the effect desired by #33358, on x64 windows icudt.lib?

2023-12-04 07:28 UTC, dg0yt commented on ports/icu/portfile.cmake
>  endif()
This change doesn't make sense. It limits controlling the `--...-tools` option - and thus the effect of the `tools` feature - to ios.

- The right way to modify the availability of features is the `supports` field in the manifest.
- But here, it doesn't even seem logical that "tools" (which normally means certain executables) are supported on ios and nowhere else.

2023-12-05 01:28 UTC, BillyONeal requested changes
I agree with @dg0yt

2023-12-07 07:38 UTC, dg0yt commented
Proper fix is in #35529.

2023-12-07 08:12 UTC, closed without merging