[qtbase] enable egl for android
microsoft/vcpkg pull request #35845
Opened 2023-12-23 16:44 UTC by m-kuhn

Enable support for feature `egl` for `android` for `qtbase`.
Specifying it as default-feature for android but at the same time specifying the feature as not supported is inconsistent.

2023-12-23 20:17 UTC, m-kuhn commented
`ANDROID_SDK_ROOT` needs to be available to build qt for android in CI (which was NOT done so far).

https://github.com/microsoft/vcpkg/blob/7b3ea912e979594eef9cff9e37606d0d15e9c8fc/ports/qtbase/cmake/qt_install_submodule.cmake#L11-L13

The SDK is not installed from what I can see (only the NDK).

https://github.com/microsoft/vcpkg/blob/7b3ea912e979594eef9cff9e37606d0d15e9c8fc/scripts/azure-pipelines/android/Dockerfile#L10-L16

We could:

 - Disable these tests
 - Install the SDK
   - and detect the location from env vars directly in the qt ports (I am starting to wonder if this would be the correct approach. The NDK is also detected from `ANDROID_NDK_HOME` if I'm not wrong)
   - stick to the current approach and require the user to provide `ANDROID_SDK_ROOT` via triplet, but then we need an overlay triplet for the tests

2023-12-26 11:15 UTC, m-kuhn commented
I added the android sdk. It probably needs more to install specific packages with the sdkmanager (tests will tell).

2023-12-26 16:39 UTC, m-kuhn commented on scripts/azure-pipelines/android/Dockerfile
> +RUN ls -a
note to self: remove debug stuff

2023-12-27 16:07 UTC, m-kuhn commented
Either I am missing something here (I just look at how `ANDROID_NDK_HOME` is and tried to apply the same to `ANDROID_SDK_ROOT`) or the changes in the Dockerfile are not automatically taken into account.
Does someone see why the ENV var from the Dockerfile doesn't make it into the port?

2023-12-27 16:26 UTC, dg0yt commented
I guess the docker file is only regenerated once a month.
This is how I currently experiment with NDK r26: 
https://github.com/microsoft/vcpkg/pull/35851/files#diff-b810c6816d42fd5c52f27e1ca0da28fd595a2bd00cbb448b443eff8e1739fe57

2023-12-27 17:39 UTC, m-kuhn commented
Thanks for the hint.
Still seems not sufficient. I was thinking about `VCPKG_ENV_PASSTHROUGH` but that's windows specific.

2023-12-30 02:20 UTC, m-kuhn commented
Looks like the toolchain file is not loaded at the point where the check happens.

2023-12-30 07:15 UTC, dg0yt commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    message(FATAL_ERROR "${PORT} requires ANDROID_SDK_ROOT to be set. Set ANDROID_SDK_ROOT as environment variable or in the triplet." )
qt_install_submodule operates in script mode. It doesn't see results from the toolchain, and AFAICS it uses a cmake variable `ANDROID_SDK_ROOT` at the moment, not an environment variable. So it would need to be set e.g. in the triplet file. 
You may change this file to use the environment variable to initialize the cmake variable iff unset. It is the only use of `ANDROID_SDK_ROOT`.

2023-12-30 08:42 UTC, m-kuhn commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    message(FATAL_ERROR "${PORT} requires ANDROID_SDK_ROOT to be set. Set ANDROID_SDK_ROOT as environment variable or in the triplet." )
Triplets is what I do in my own repo, but I was wondering if we could do this transparently (after all, the ndk path is also picked up from the environment without triplet involved).
But it would certainly be easier to do with the triplet.

2023-12-30 08:54 UTC, dg0yt commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    message(FATAL_ERROR "${PORT} requires ANDROID_SDK_ROOT to be set. Set ANDROID_SDK_ROOT as environment variable or in the triplet." )
That's why I suggested that the portfile could pick the environement variable. (Fully switching to the environment variable might break users.)

2023-12-30 08:58 UTC, dg0yt commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    message(FATAL_ERROR "${PORT} requires ANDROID_SDK_ROOT to be set. Set ANDROID_SDK_ROOT as environment variable or in the triplet." )
Setting it in the triplet ensures the desired (?!) effect on ABI hashes, but is more intrusive on the user side.
The NDK environment variable already affects ABI hashing via the compiler binaries hashes.

2023-12-30 09:00 UTC, dg0yt commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    message(FATAL_ERROR "${PORT} requires ANDROID_SDK_ROOT to be set. Set ANDROID_SDK_ROOT as environment variable or in the triplet." )
Mabye useful in the future: https://github.com/microsoft/vcpkg-tool/pull/1315. This would hash the extra script, and the triplet could remain unchanged.

2023-12-30 09:27 UTC, m-kuhn commented on ports/qtbase/cmake/qt_install_submodule.cmake
> +    message(FATAL_ERROR "${PORT} requires ANDROID_SDK_ROOT to be set. Set ANDROID_SDK_ROOT as environment variable or in the triplet." )
> That's why I suggested that the portfile could pick the environement variable. (Fully switching to the environment variable might break users.)

If it's set to an absolute path, yes. But that would mean every user has to provide a local triplet. And if it's set via env var (as done with the latest iteration of this PR) it means that the ABI hash of the triplet is not really reliable.

2023-12-30 09:31 UTC, dg0yt commented on triplets/arm-neon-android.cmake
> +set(ANDROID_SDK_ROOT $ENV{ANDROID_SDK_ROOT})
This doesn't help with ABI hashes: The content of the triplet files remains independent of the content of `ENV{ANDROID_SDK_ROOT}`.

2023-12-30 09:34 UTC, dg0yt commented on triplets/arm-neon-android.cmake
> +set(ANDROID_SDK_ROOT $ENV{ANDROID_SDK_ROOT})
There is https://learn.microsoft.com/en-us/vcpkg/users/triplets#vcpkg_env_passthrough, but it is documented "for Windows"...

2023-12-30 13:06 UTC, m-kuhn commented on triplets/arm-neon-android.cmake
> +set(ANDROID_SDK_ROOT $ENV{ANDROID_SDK_ROOT})
The only way I know to bring this into ABI hashes is by (a) writing it into an overlay triplet, but as you mentioned, this is intrusive on user side.
Or we respect environment variables, either by inspecting them (b) in the triplet (done currently) or (c) in the android toolchain (done before) or (d) in the port and forward it to cmake configure from there.

And if I understand correctly, your preference is (d)?

2023-12-30 14:47 UTC, m-kuhn commented
I'm afraid I am hitting a wall with installing the SDK through `test-modified-ports.ps1`, it seems that it runs with limited permissions and I cannot install java.

2024-01-05 00:28 UTC, m-kuhn commented
@dan-shaw @BillyONeal what is the best way to get an update into the android ci docker image? I assume the current changes should be sufficient.

NB: happy to update the version as soon as the path forward is clear, there are currently other PRs waiting for qtbase which are probably merged earlier.

2024-03-11 17:32 UTC, m-kuhn commented
gentle ping, how can we get the java dependencies into the ci docker image?

2024-05-09 05:22 UTC, m-kuhn commented
gentle ping, how can we get the jdk/android sdk dependencies into the ci docker image?

2024-06-12 23:46 UTC, BillyONeal commented
R26c was just landed by @dg0yt in https://github.com/microsoft/vcpkg/pull/35851

2024-06-13 03:14 UTC, m-kuhn commented
This is about the android sdk which requires java https://github.com/microsoft/vcpkg/pull/35845/files#diff-783e7bf9703fa77a2652b514ee607d8e40aafdd4f25f7e4e663de8b224f43e62R43

2024-06-13 05:22 UTC, dg0yt commented
@BillyONeal This might be waiting for feedback from your team.

**Motivation**

qtbase needs to build some Java code for Android. So it needs the SDK.

**Approach**

What can be applied from https://github.com/microsoft/vcpkg/pull/35851 is the approach:
1. Have a fully working proof-of-concept build by downloads with modifications in `test-modified-ports.ps1`. (Invasive, draft.)
2. Port the necessary changes to the docker script in another PR. (No side effects.)
3. Once the other PR is merged and the image is updated, switch the first PR to activate the new tools. (Invasive, but ready for review.)

**Passing the location of the SDK**

Here, there is the additional issue of passing the environment variable (which is today called) [`ANDROID_HOME`](https://developer.android.com/tools/variables?hl=de#android_home) through vcpkg tool. It must not be removed from the environment on windows. This could be achieved by adding it to `VCPKG_ENV_PASSTHROUGH` or `VCPKG_ENV_PASSTHROUGH_UNTRACKED` in the android triplet files.

And of course the SDK needs a JDK. This PR installs the system packages so it is in the non-windows `PATH`.

However, there are open review comments on the triplet file changes proposed by this PR.

**ABI hashing**

One open question is how the SDK should affect ABI hashing. `VCPKG_ENV_PASSTHROUGH` would use the installation path of the SDK. But this might be a poor choice:
- Different locations can very well produce the same results.
- The actual "compiler" is `javac`, but there are other tools affecting the structure of the artifact.
- The most interesting factor for ABI concerns is the pair of API levels (minimum, target). This is somewhat covered by `[VCPKG_]CMAKE_SYSTEM_VERSION`.

2024-06-13 05:29 UTC, m-kuhn commented
> 1. Have a fully working proof-of-concept build by downloads with modifications in test-modified-ports.ps1. (Invasive, draft.)

I have tried to do so, but failed because this script doesn't run with the necessary permissions to install additional system packages (jdk). I think we will need to have the jdk already pre-installed in the CI image to work on a proof-of-concept that runs on azure.

2024-06-13 05:38 UTC, dg0yt commented
> I have tried to do so, but failed because this script doesn't run with the necessary permissions to install additional system packages (jdk). I think we will need to have the jdk already pre-installed in the CI image to work on a proof-of-concept that runs on azure.

Hm, I think I have done so successfully already, at least with `sudo`.

And there is still the option to fetch and unpack a plain tarball. https://openjdk.org/install/

2024-06-13 06:12 UTC, Neumann-A commented
> VCPKG_ENV_PASSTHROUGH would use the installation path of the SDK

Use `VCPKG_ENV_PASSTHROUGH_UNTRACKED` as you already mentioned

> The actual "compiler" is javac, but there are other tools affecting the structure of the artifact.

`VCPKG_HASH_ADDITIONAL_FILES` is intended to be used in this case. You have a ENV variable with a root path so you can just point it to the files of the JDK which should affect the ABI hash

2024-07-08 06:29 UTC, dg0yt commented
qtbase still doesn't build because of baseline cascades. It would help if the tool would print the deps which participate in the cascade.

2024-07-08 07:35 UTC, m-kuhn commented
I don't see any debug output in the logs https://github.com/microsoft/vcpkg/pull/35845/files#diff-b810c6816d42fd5c52f27e1ca0da28fd595a2bd00cbb448b443eff8e1739fe57R125

is `$IsLinuxHost` correct, not sure where that should come from, I copied it from somewhere?

2024-07-08 07:46 UTC, dg0yt commented
The problem is not in changes from this PR. It is some dependency which is `skip` or `fail` in `scripts/ci.baseline.txt`.

2024-07-08 07:56 UTC, m-kuhn commented
But the `Write-Host` output from `test-modified-ports.ps1` should be visible anyway?

2024-07-08 09:55 UTC, dg0yt commented on scripts/azure-pipelines/test-modified-ports.ps1
> +if ($IsLinuxHost)
Did you mean to write
```suggestion
if ($IsLinux)
```
or maybe
```suggestion
if ($Triplet -match 'android')
```

2024-07-13 08:53 UTC, m-kuhn commented on scripts/azure-pipelines/test-modified-ports.ps1
> +    & "./vcpkg" x-download android-sdk.zip "--sha512=d143221d0957256c5b172a5be70e5f098a08b2b3097a20c576c8febf444a00a64f626a7f651a7d5123b9ba32418dc0ae7053d0b4b52c40f772a6a1fb19a95417" "--url=https://d
```suggestion
    & "./vcpkg" x-download android-sdk.zip "--sha512=d143221d0957256c5b172a5be70e5f098a08b2b3097a20c576c8febf444a00a64f626a7f651a7d5123b9ba32418dc0ae7053d0b4b52c40f772a6a1fb19a95417" "--url=https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip"

```

2024-07-22 18:30 UTC, m-kuhn commented
Cannot download sdk :

> ```
> Asset cache miss for android-sdk.zip and downloads are blocked by x-block-origin.
> ```

Why is it working for the jdk, but not for the sdk?

2024-07-22 18:44 UTC, m-kuhn commented
> Cannot download sdk :
> 
> > ```
> > Asset cache miss for android-sdk.zip and downloads are blocked by x-block-origin.
> > ```
> 
> Why is it working for the jdk, but not for the sdk?

That seems to be caused by disabling the cache.
Which was disabled because

```
Downloading Android SDK
error: Failed to download from mirror set
error: https://vcpkgassetcachewus3.blob.core.windows.net/cache/d143221d0957256c5b172a5be70e5f098a08b2b3097a20c576c8febf444a00a64f626a7f651a7d5123b9ba32418dc0ae7053d0b4b52c40f772a6a1fb19a95417?*** SECRET ***: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 404 The specified blob does not exist.

error: File does not have the expected hash:
url: https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
```

404 but the link works here

2024-07-25 19:42 UTC, dg0yt requested changes

2024-07-25 19:42 UTC, dg0yt commented on scripts/azure-pipelines/test-modified-ports.ps1
> +    & "./vcpkg" x-download android-sdk.zip "--sha512=d143221d0957256c5b172a5be70e5f098a08b2b3097a20c576c8febf444a00a64f626a7f651a7d5123b9ba32418dc0ae7053d0b4b52c40f772a6a1fb19a95417" "--url=https://d
```suggestion
    & "./vcpkg" x-download android-sdk.zip "--sha512=64b7d18ee7adeb1204eaa2978091e874dc9af9604796b64e1a185a11c15325657383fc9900e55e4590c8b8a2784b3881745d2f32daef1207e746c0ee41c2b72b" "--url=https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip"

```

2024-07-26 11:35 UTC, dg0yt commented on scripts/azure-pipelines/test-modified-ports.ps1
> +    & bash -c 'yes | /android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses'
```suggestion
    & bash -c 'yes | ./android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses'

```

2024-07-28 09:17 UTC, dg0yt commented
Please try https://github.com/m-kuhn/vcpkg/pull/1

2024-08-03 08:55 UTC, dg0yt commented
Hm, still not successful in CI.
~~~
Setting up the Android SDK in /vcpkg/android-sdk
Loading package information...                                                  
Loading local repository...                                                     
[                                       ] 3% Loading local repository...        
[                                       ] 3% Fetch remote repository...         
[=                                      ] 3% Fetch remote repository...         
                                                                                
[=                                      ] 3% Fetch remote repository...         
Warning: Failed to download any source lists!
                                                                                
Warning: IO exception while downloading manifest
[=                                      ] 3% Fetch remote repository...         
                                                                                
Warning: IO exception while downloading manifest
[=                                      ] 3% Fetch remote repository...         
Warning: Still waiting for package manifests to be fetched remotely.
                                                                                
[=                                      ] 3% Fetch remote repository...         
[=                                      ] 3% Computing updates...               
[===                                    ] 8% Computing updates...               
[===                                    ] 10% Computing updates...              
                                                                                
[===                                    ] 10% Computing updates...              
Warning: Failed to find package 'platform-tools'
yes: standard output: Broken pipe
Loading package information...                                                  
Loading local repository...                                                     
[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=======================================] 100% Fetch remote repository...       
~~~

2024-08-03 10:09 UTC, m-kuhn commented
Is network connectivity blocked except through vcpkg tool?

2024-08-03 13:42 UTC, dg0yt commented
> Is network connectivity blocked except through vcpkg tool?

IDK. Let's try https://github.com/m-kuhn/vcpkg/pull/2.

2024-08-03 15:45 UTC, dg0yt commented
~~~
Installed packages:
  Path                 | Version | Description                       | Location            
  -------              | ------- | -------                           | -------             
  build-tools;34.0.0   | 34.0.0  | Android SDK Build-Tools 34        | build-tools/34.0.0  
  platform-tools       | 35.0.1  | Android SDK Platform-Tools 35.0.1 | platform-tools      
  platforms;android-34 | 3       | Android SDK Platform 34, rev 3    | platforms/android-34
~~~
Good.

~~~
CMake Error at ports/qtbase/cmake/qt_install_submodule.cmake:13 (message):
  qtbase requires ANDROID_SDK_ROOT to be set.  Set ANDROID_SDK_ROOT as
  environment variable or in the triplet.
~~~
Okay, the CI script sets  `ANDROID_HOME` because this what is given in https://developer.android.com/tools/variables#envar, but the Qt still wants `ANDROID_SDK_ROOT`. This should be bridged in the port.

2024-08-04 15:36 UTC, m-kuhn commented
> Okay, the CI script sets `ANDROID_HOME` because this is what is given in https://developer.android.com/tools/variables#envar, but the Qt still wants `ANDROID_SDK_ROOT`. This should be bridged in the port.

I tried to implement this in the port, but it seems `ENV{ANDROID_HOME}` is not visible there.

2024-11-10 08:57 UTC, closed without merging

2024-11-10 08:57 UTC, m-kuhn commented
Closing in favor of https://github.com/microsoft/vcpkg/pull/42080