[embree3] Add macOS and ARM support, plus various options
microsoft/vcpkg pull request #35929
Opened 2023-12-30 00:13 UTC by theblackunknown

Improve incompatible MSVC configuration setup

Add neon features

Add support for max ISA

Add feature for choice of tasking system

Add additional Embree configurable options as features

Change `file(INSTALL ...)` to `vcpkg_install_copyright`

Format

2023-12-30 08:53 UTC, dg0yt commented on ports/embree3/vcpkg.json
> +    },
I think the existing ISA features might have been a mistake, and no extra ISA features should be added. Features shall not model alternatives. The package already chooses neon2x for `APPLE` arm and neon for other arm targets, as alternatives.

(One ISA must be used, and `embree[core]` is broken at the moment for x64. But it is not a regression, and it is not necessary to fix the problem in this PR.)

2023-12-30 16:58 UTC, theblackunknown reviewed
Thanks for the early review @dg0yt , I'll finish reviewing it on my mac machine, address your comments and then I'll remove thz draft status

2023-12-30 16:58 UTC, theblackunknown commented on ports/embree3/vcpkg.json
> +  "supports": "!(arm & (windows | android))",
Good catch ! Let me adjust for another round before removing the draft status

2023-12-30 16:58 UTC, theblackunknown commented on ports/embree3/vcpkg.json
> +  "supports": "!(arm & (windows | android))",
Note that `arm` was previously not marked as supported in the previous port version. 
If this is trivial to enable I'll do it otherwise I propose that we defer this to another port version as I do not have a fully android setup at the moment.

2023-12-30 16:58 UTC, theblackunknown commented on ports/embree3/vcpkg.json
> +    },
I tend to agree with you, in Embree terms I ideally we should directly target the only ISA we are interested in at build time and live with it, and thus is particularly useful for the binary size when you can afford to do so ! (note that this is almost what setting `EMBREE_MAX_ISA` to `NONE` or `DEFAULT` is doing.)

On the other hand, things in practice are different: you do not necessarily know which ISA will be supported at _runtime_ on a user machine, and thus you want to pack a set of possibly supported ISA at _buildtime_ and let Embree runtime cpu feature detection select which ISA among thebones selected at build time to use.
For example, you may want to build a Embree library which SSE2, SSE42, AVX and AVX2 but then at runtime Embree will select AVX2, AVX or lower depending on what is possible. 

For this flexibility/complexity, I do not feel comfortable yet to revise the way the set of features but happy to do so in a following port version !

Do you want us to start a discussion about it to prepare a following port version?

2023-12-30 17:04 UTC, theblackunknown commented
Looking at existing PR/issue there may be some redundancy with #30548 
Something to double check before removing the draft status

2024-01-03 09:45 UTC, theblackunknown commented on ports/embree3/vcpkg.json
> +  "supports": "!(arm & (windows | android))",
I have now reverted this one.

2024-01-03 09:49 UTC, theblackunknown commented on ports/embree3/vcpkg.json
> +    },
Bump on this one as I am marking this PR ready for review: I think this is best to follow the current logic for now, and revise this in a following port-version.

What are your thoughts on this ?

2024-01-04 08:40 UTC, Adela0814 submitted a review, later dismissed

2024-01-04 08:41 UTC, Adela0814 commented
All feature tested on the following triplets:

- x64-windows
- x64-windows-static
- x86-windows

2024-01-04 19:53 UTC, BillyONeal commented
Tagged vcpkg-team-review to answer this question:

Today, we would refuse to merge features that try to change ISA like this, under the 'do not implement alternatives as features' rule. However, embree3 already has other ISA features, should we make an exception in that this adds one like the others? See also, last time the maintainers weighed in on this topic: https://github.com/microsoft/vcpkg/pull/29093#issuecomment-1465969155

Alternatively, should we remove all ISA features entirely, because they are broken?

2024-01-04 20:00 UTC, Neumann-A commented
I'll vote for removal. Stuff like this can be set via `VCPKG_CMAKE_COINFIGURE_OPTIONS` or the port needs to inspect compiler flags to enable those.

2024-01-05 15:26 UTC, theblackunknown commented
@BillyONeal @Neumann-A great discussion !
I took the liberty to implement an embree3 port where we get rid of ISA features and handle it as best we can in the portfile.

I gave it a quick test on an internal project which target both native and emscripten platforms.
For Emscripten, I had to hijack the ISA selection because it was incorrect otherwise letting Embree select the default one by itself seems to work fine.

Let me know what you think of 9d47b0a

2024-01-13 20:39 UTC, theblackunknown commented
Hey @BillyONeal @Neumann-A, did you have the time to look at my latest revision which should take into account to your feedbacks ?

2024-02-09 21:01 UTC, theblackunknown commented
Gentle reminder, @BillyONeal @Neumann-A, did you have the time to look at my latest revision which should take into account to your feedbacks ?

2024-02-29 21:28 UTC, BillyONeal approved these changes, later dismissed

2024-02-29 22:29 UTC, vicroms requested changes

2024-02-29 22:29 UTC, vicroms commented on ports/embree3/001-downgrade-find-package-tbb-2020.patch
> ++    find_package(TBB 2020 COMPONENTS ${EMBREE_TBB_COMPONENT} CONFIG ${TBB_FIND_PACKAGE_OPTION})
```suggestion
+    find_package(TBB COMPONENTS ${EMBREE_TBB_COMPONENT} CONFIG ${TBB_FIND_PACKAGE_OPTION})
```

2024-03-02 21:33 UTC, theblackunknown commented on ports/embree3/001-downgrade-find-package-tbb-2020.patch
> ++    find_package(TBB 2020 COMPONENTS ${EMBREE_TBB_COMPONENT} CONFIG ${TBB_FIND_PACKAGE_OPTION})
Thanks ! I have added your suggestion in the latest amended commit.

2024-03-05 09:04 UTC, vicroms commented on ports/embree3/vcpkg.json
> +    "tasking-tbb"
are all of these features actually required to be default-features?

2024-03-05 09:04 UTC, vicroms reviewed
The title of the PR should be changed to reflect the new changes.

2024-03-06 07:43 UTC, vicroms approved these changes

2024-03-06 22:43 UTC, theblackunknown commented on ports/embree3/vcpkg.json
> +    "tasking-tbb"
I believe those are true Embree features (toggling them does not change Embree API), and I have marked them as default features because it reflects the default cmake specified in the CMake project.

https://github.com/embree/embree/blob/698442324ccddd11725fb8875275dc1384f7fb40/CMakeLists.txt#L139-L153

2024-03-06 22:44 UTC, theblackunknown commented
> The title of the PR should be changed to reflect the new changes.

Indeed, I'll find something more appropriate before the end of the week.

2024-03-07 18:02 UTC, merged