[libid3tag] Add version 0.16.3
microsoft/vcpkg pull request #35954
Opened 2023-12-31 23:41 UTC by generic-pers0n

Add's Tenacity's libid3tag port with some modifications, including a hashable source, correct usage text, and using `vcpkg_install_copyright()`.

This is similar #15991, but this port is smaller, does not feature any patches, and uses 0.16.3.

Note: the usage text may be wrong, which is why this is a draft PR at the moment. Once I can confirm the usage text is correct, I'll mark this as ready.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-02-11 16:14 UTC, generic-pers0n commented
Note that the source tarball used is Codeberg's auto-generated source tarball. I've updated the hash after it changed, presumably from the DDoS attack.

I also have reason to believe that these source tarballs are stable and that the hash change, like with what happened in #36362, was an unusual event. However, if it's preferred, we can provide our own source tarballs instead like with libmad.

2024-02-26 10:21 UTC, Cheney-W requested changes

2024-02-26 10:21 UTC, Cheney-W commented on ports/libid3tag/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/id3tag)
```suggestion
vcpkg_cmake_config_fixup(PACKAGE_NAME id3tag CONFIG_PATH lib/cmake/id3tag)
```

After completing this modification, the usage information for this port will be automatically generated upon successful installation, eliminating the need for a usage file or its installation.

2024-02-26 23:27 UTC, JoergAtGithub commented
@generic-pers0n You should change the state of this PR from Draft to ReadyForReview. Otherwise it does not appear on the teams review list.

2024-02-27 02:23 UTC, generic-pers0n commented
> @generic-pers0n You should change the state of this PR from Draft to ReadyForReview. Otherwise it does not appear on the teams review list.

I have marked this PR ready for review as I feel that it is ready to be reviewed again.

2024-02-27 02:25 UTC, Cheney-W approved these changes

2024-02-27 02:28 UTC, Cheney-W commented
Usage test passed with `x64-windows`  triplet.

2024-02-27 09:04 UTC, merged