mtl new port
microsoft/vcpkg pull request #36105
Opened 2024-01-10 10:15 UTC by tonitaga

2024-01-10 19:21 UTC, dg0yt reviewed
Based on [repology.org](https://repology.org/project/mtl/information), there are two other mtl packages, although their orginal websites are no longer online. From https://web.archive.org/web/20171128164030/http://www.osl.iu.edu/research/mtl/, I get to:

The Matrix Template Library 2 (MTL2), July 5, 2005: Distribution 2.1.2-22  
https://web.archive.org/web/20151117184500/http://www.crest.iu.edu/research  /mtl/mtl2.php3

The Matrix Template Library 4,  
https://web.archive.org/web/20171216224505/http://www.simunova.com/en/node/24  
Copyright (c) 2007-2008 The Trustees of Indiana University. All rights reserved.  
Authors: Peter Gottschling and Andrew Lumsdaine
Seems to be the same as https://github.com/simunova/mtl4

Is the new package related to that old packages?

2024-01-10 19:21 UTC, dg0yt commented on versions/m-/mtl.json
> +}
Please update run `vcpkg x-add-version --overwrite-version mtl` to ensure standard formatting.

2024-01-10 19:21 UTC, dg0yt commented on ports/mtl/vcpkg.json
> +  "version-string": "1.0.0",
```suggestion
  "version": "1.0.0",
```
if it is 1.0.0 at all - I don't spot it on https://github.com/tonitaga/Matrix-Template-Library-CPP/tags.

2024-01-10 20:42 UTC, tonitaga commented on ports/mtl/vcpkg.json
> +  "version-string": "1.0.0",
From now on the version numbering will start again, I didn't have time to change it in my repository

2024-01-10 20:44 UTC, tonitaga commented on versions/m-/mtl.json
> +}
OK

2024-01-10 20:45 UTC, tonitaga commented on ports/mtl/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/cmake/Findmtl.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
Sorry, that was my first try to do that, i will change that

2024-01-10 20:46 UTC, tonitaga commented
> Based on [repology.org](https://repology.org/project/mtl/information), there are two other mtl packages, although their orginal websites are no longer online. From https://web.archive.org/web/20171128164030/http://www.osl.iu.edu/research/mtl/, I get to:
> 
> The Matrix Template Library 2 (MTL2), July 5, 2005: Distribution 2.1.2-22 https://web.archive.org/web/20151117184500/http://www.crest.iu.edu/research /mtl/mtl2.php3
> 
> The Matrix Template Library 4, https://web.archive.org/web/20171216224505/http://www.simunova.com/en/node/24 Copyright (c) 2007-2008 The Trustees of Indiana University. All rights reserved. Authors: Peter Gottschling and Andrew Lumsdaine Seems to be the same as https://github.com/simunova/mtl4
> 
> Is the new package related to that old packages?

No, the new package is not linked to the old ones.

2024-01-11 09:58 UTC, FrankXie05 requested changes

2024-01-11 09:58 UTC, FrankXie05 commented on ports/mtl/usage
> +    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
```suggestion
    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
    
```

2024-01-11 09:58 UTC, FrankXie05 commented on ports/mtl/portfile.cmake
> +
```suggestion

```

2024-01-11 10:02 UTC, FrankXie05 requested changes

2024-01-11 10:02 UTC, FrankXie05 commented on ports/mtl/portfile.cmake
> +        -DMTL_CMAKE_DIR=share/mtl
```suggestion
        -DMTL_CMAKE_DIR=share/mtl
```
is this macro necessary? I didn't see it in `CMakeLists.txt`. :)

2024-01-11 10:03 UTC, FrankXie05 requested changes

2024-01-11 10:03 UTC, FrankXie05 commented on ports/mtl/portfile.cmake
> +vcpkg_from_github(
```suggestion
# Header-only library

vcpkg_from_github(
```

2024-01-11 10:50 UTC, tonitaga commented on ports/mtl/portfile.cmake
> +vcpkg_from_github(
OK, I commited it

2024-01-11 11:00 UTC, tonitaga reviewed
All changes are addressed

2024-01-12 02:05 UTC, FrankXie05 approved these changes, later dismissed

2024-01-12 05:40 UTC, dg0yt commented on ports/mtl/portfile.cmake
> +# Header-only library
```suggestion
set(VCPKG_BUILD_TYPE release) # Header-only library
```

2024-01-12 05:40 UTC, dg0yt commented on ports/mtl/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib" "${CURRENT_PACKAGES_DIR}/debug")
```suggestion
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib")
```
`debug` won't exist after setting `VCPKG_BUILD_TYPE`.

2024-01-12 05:40 UTC, dg0yt commented on ports/mtl/usage
> +
```suggestion

```
(Remove the four space, not the line break.)

2024-01-12 05:51 UTC, tonitaga commented on ports/mtl/usage
> +
OK

2024-01-12 05:51 UTC, tonitaga commented on ports/mtl/portfile.cmake
> +# Header-only library
OK

2024-01-12 05:52 UTC, tonitaga commented on ports/mtl/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib" "${CURRENT_PACKAGES_DIR}/debug")
OK

2024-01-12 06:17 UTC, dg0yt commented on ports/mtl/usage
> +    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
You failed to leave the final line break in place. (In VS code, it appears as an empty line.)

2024-01-12 06:22 UTC, tonitaga commented on ports/mtl/usage
> +    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
Sorry, didn't read the previous comment carefully

2024-01-12 06:23 UTC, tonitaga commented on ports/mtl/usage
> +    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
What bad things will happen if we leave it as it is?

2024-01-12 06:37 UTC, dg0yt commented on ports/mtl/usage
> +    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
It causes non-conforming output. Most systems in the world rely on text files ending with a line break. For example a plain `cat ports/mtl/usage` in a bash shell. It will put the prompt right behind `...mtl::mtl)`. And that's why it is flagged with a red `(-)` here on GH.

2024-01-12 06:39 UTC, tonitaga commented on ports/mtl/usage
> +    target_link_libraries(${PROJECT_NAME} PRIVATE mtl::mtl)
OK, i will add the line break

2024-01-15 02:39 UTC, FrankXie05 submitted a review, later dismissed

2024-01-18 00:06 UTC, JavierMatosD requested changes
The only issue I see here is that "mtl" is taken on repology and it doesn't refer to upstream. I suggest renaming the port to "tonitaga-mtl". I will set the PR to draft. Toggle ready for review when you've made the changes. Thanks!

2024-01-18 10:35 UTC, tonitaga commented
> The only issue I see here is that "mtl" is taken on repology and it doesn't refer to upstream. I suggest renaming the port to "tonitaga-mtl". I will set the PR to draft. Toggle ready for review when you've made the changes. Thanks!

I decided to add a "t" at the end of the port name, which just about epitomizes my nickname. The current port name is "mtlt". Is this ok? Or should it be tonitaga-mtl, just in this case I would have to change namespaces from mtl to tonitaga_mtl, and base include folder from mtl to tonitaga_mtl in my repository to avoid other conflicts. I find "mtlt" to be a more convenient and understandable notation.

2024-01-18 10:45 UTC, tonitaga commented
> The only issue I see here is that "mtl" is taken on repology and it doesn't refer to upstream. I suggest renaming the port to "tonitaga-mtl". I will set the PR to draft. Toggle ready for review when you've made the changes. Thanks!

2024-01-19 06:22 UTC, FrankXie05 approved these changes

2024-01-19 06:24 UTC, dg0yt commented
Please update the PR title, for the git merge commit message.

2024-01-19 11:52 UTC, tonitaga commented
> Please update the PR title, for the git merge commit message.

Ready

2024-01-19 19:59 UTC, JavierMatosD approved these changes

2024-01-19 20:00 UTC, merged