[dcmtk] Update to 3.6.8
microsoft/vcpkg pull request #36124
Opened 2024-01-11 10:50 UTC by kevle

Fixes #36121

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-01-11 13:40 UTC, kevle commented on ports/dcmtk/osconfig_absolute_paths.patch
The paths, after configuration, have changed to "${CURRENT_PACKAGES_DIR}/share/dcmtk-3.6.8/dicom.dic" from "${CURRENT_PACKAGES_DIR}/share/dcmtk/dicom.dic", therefore I have removed the substitution here to simplify string replacement in the port file.
The macros can not be removed directly in the patch, since some static functions reference them during configuration phase from what I could gather.

2024-01-12 02:15 UTC, jimwang118 requested changes

2024-01-12 02:15 UTC, jimwang118 commented on ports/dcmtk/portfile.cmake
> +    REF 59f75a8b50e50ae1bb1ff12098040c6327500740 # DCMTK-3.6.8
```suggestion
    REF "DCMTK-${VERSION}"
```

2024-01-12 02:34 UTC, jimwang118 requested changes

2024-01-12 02:34 UTC, jimwang118 commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"\"" "")
```suggestion
vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DCMTK_PREFIX \"\"" "")
vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DCM_DICT_DEFAULT_PATH \"\"" "")
vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_CONFIGURATION_DIR \"\"" "")
vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"\"" "")
```
The function implemented by this code is the same as that of osconfig_absolute_paths.patch. Can be deleted directly.

2024-01-12 02:35 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2024-01-12 08:25 UTC, kevle commented on ports/dcmtk/portfile.cmake
> +vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/dcmtk/config/osconfig.h" "#define DEFAULT_SUPPORT_DATA_DIR \"\"" "")
Good idea, thanks.
Upon trying to outright delete the constants in the patch, this turned up: https://github.com/DCMTK/dcmtk/blob/59f75a8b50e50ae1bb1ff12098040c6327500740/ofstd/libsrc/ofstd.cc#L3292C27-L3292C27
The constants "DEFAULT_SUPPORT_DATA_DIR" and "DEFAULT_CONFIGURATION_DIR" defined in the configured `osconfig.h` are apparently used during compilation to hard-code some default paths.

Further inspection revealed that `OFStandard::getDefaultSupportDataDir()`, and `OFStandard::getDefaultConfigurationDir()` are only used in [dcm2xml.cc](https://github.com/DCMTK/dcmtk/blob/DCMTK-3.6.8/dcmdata/apps/dcm2xml.cc) and [dcmqrti.cc](https://github.com/DCMTK/dcmtk/blob/DCMTK-3.6.8/dcmqrdb/apps/dcmqrti.cc) which are both utility programs.

I will delete the patch and try to adapt the paths in the port file, similar to how it has been done before.

2024-01-16 01:51 UTC, jimwang118 approved these changes, later dismissed

2024-01-16 06:01 UTC, jimwang118 commented
When I test all feature installations, the following error message appears.
```
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

  F:\dcmtk\packages\dcmtk_x64-windows\bin\mkcsmapper.exe
  F:\dcmtk\packages\dcmtk_x64-windows\bin\mkesdb.exe
  F:\dcmtk\packages\dcmtk_x64-windows\bin\oficonv_tests.exe

error: Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: F:\dcmtk\ports\dcmtk\portfile.cmake
```

2024-01-16 09:20 UTC, kevle commented
Thanks for testing! I have resolved the problem for x64-windows, but on x64-linux there still is a problem with libtiff since it is missing a link dependency to liblzma for the DCMTK tools because DCMTK_LINK_STATIC ( introduced in DCMTK 3.6.7 ) is not defined, even though VCPKG_LIBRARY_LINKAGE is static.
I am working to resolve this problem and will reopen for review once it works.

2024-01-17 20:02 UTC, merged

2024-03-08 11:31 UTC, MarkVabulas commented
While this is still open, the DCMTK_WITH_OPENJPEG advanced option is missing as a configurable library, which gives Jpeg2000 support to the DCMTK library.

2024-04-05 08:59 UTC, kevle commented
> While this is still open, the DCMTK_WITH_OPENJPEG advanced option is missing as a configurable library, which gives Jpeg2000 support to the DCMTK library.

From what I can gather, full JPEG 2000 support is not part of the open source package yet.

See:
https://forum.dcmtk.org/viewtopic.php?t=4920
https://dicom.offis.de/dcmjp2k.php.en

In any case, I think adding DCMTK_WITH_OPENJPEG warrants its own issue and PR if there is any benefit from it.

2024-04-16 20:19 UTC, dg0yt commented on ports/dcmtk/portfile.cmake
> +        -DDCMTK_USE_FIND_PACKAGE_WIN_DEFAULT=ON
Hey reviewers, this is wrong!

2024-04-17 03:09 UTC, jimwang118 commented on ports/dcmtk/portfile.cmake
> +        -DDCMTK_USE_FIND_PACKAGE_WIN_DEFAULT=ON
I'm very sorry, this was my mistake and I will correct it.

2024-04-17 07:14 UTC, kevle commented on ports/dcmtk/portfile.cmake
> +        -DDCMTK_USE_FIND_PACKAGE_WIN_DEFAULT=ON
Sorry, I might have force pushed this after getting a warning on Linux builds.

If anyone stumbles on this, here is how it is done right:
https://github.com/microsoft/vcpkg/pull/38223#discussion_r1568281315

Documentation:
https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_cmake_configure#maybe_unused_variables