[libsrtp] Added openssl feature flag for enabling OpenSSL support
microsoft/vcpkg pull request #36135
Opened 2024-01-11 18:39 UTC by asantoni

This pull request adds a feature flag for the existing libsrtp port, to allow it to be built with OpenSSL support. OpenSSL support is necessary in order for libsrtp to support the AES GCM modes, which you won't find realize until you've debugged it. 🙃 

The changes are minimal and hopefully correct, but please let me know if any modifications are needed!

To use the feature flag, you can add "openssl" to the list of features on the dependency (as per the vcpkg docs, same way as any other feature):

```
Your vcpkg.json:
....
  "dependencies": [
    ...
    {"name": "libsrtp", "features": ["openssl"]},
    "openssl",
...
```

2024-01-11 18:41 UTC, asantoni commented
@microsoft-github-policy-service agree company="Radio Mast, Inc."

2024-01-12 02:15 UTC, Cheney-W commented on ports/libsrtp/portfile.cmake
>  )
```suggestion
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        openssl ENABLE_OPENSSL
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        "-DCMAKE_PROJECT_INCLUDE=${CMAKE_CURRENT_LIST_DIR}/cmake-project-include.cmake"
        -DTEST_APPS=OFF
        ${FEATURE_OPTIONS}
)

```

2024-01-12 02:17 UTC, Cheney-W commented on ports/libsrtp/portfile.cmake
>  )
https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_check_features

2024-01-12 02:19 UTC, Cheney-W commented on ports/libsrtp/portfile.cmake
>  )
Moving the PR to draft. Please set it to "ready for review" once changes have been applied. Thank you!

2024-01-15 17:03 UTC, asantoni commented
@Cheney-W Thanks for the review and suggestions. I have implemented and tested your changes, and so I think this PR is ready for another review.

2024-01-16 02:52 UTC, Cheney-W commented
Please modify the vcpkg.json as below:
```
{
  "name": "libsrtp",
  "version": "2.5.0",
  "port-version": 1,
  "description": "This package provides an implementation of the Secure Real-time Transport Protocol (SRTP), the Universal Security Transform (UST), and a supporting cryptographic kernel.",
...
```

2024-01-16 03:05 UTC, Cheney-W commented on ports/libsrtp/portfile.cmake
> +
```suggestion
```
Please delete extra blank lines.

2024-01-27 13:17 UTC, kevle commented on ports/libsrtp/vcpkg.json
Port version should probably be bumped
`"port-version": 1`

2024-01-29 10:42 UTC, Cheney-W commented on ports/libsrtp/vcpkg.json
Yes, I have mentioned it in this [comment](https://github.com/microsoft/vcpkg/pull/36135#issuecomment-1892994714).

2024-01-29 16:27 UTC, asantoni commented
Thanks for the continued reviews @Cheney-W @kevle. I have made those two tweaks and updated the version database. This should be ready for review again.

2024-01-30 02:51 UTC, Cheney-W requested changes

2024-01-30 02:51 UTC, Cheney-W commented on versions/l-/libsrtp.json
> +      "git-tree": "0f0b21bc9987edfc4a76c49ecdcaa04d67c7d34c",
```suggestion
      "git-tree": "27c325c9851b5c07e172e74e312e8070af7b9d0b",
```

2024-01-31 08:37 UTC, Cheney-W commented
If you first modify the port file and commit them, you should run `vcpkg x-add-version libsrtp`;
if you modify the port file and commit them again, you should run vcpkg `x-add-version libsrtp --overwrite-version`

2024-01-31 08:39 UTC, Cheney-W commented
Please click the `Ready for review` button when you think this PR is done.

2024-02-01 00:05 UTC, data-queue approved these changes

2024-02-01 17:29 UTC, asantoni commented
Aha, thanks @Cheney-W. I forgot to add `--overwrite-version` last time. Should be ready for review now.

2024-02-02 02:40 UTC, Cheney-W approved these changes

2024-02-02 19:45 UTC, data-queue approved these changes

2024-02-02 19:45 UTC, merged