[datraw] new port
microsoft/vcpkg pull request #36183
Opened 2024-01-15 16:44 UTC by moritz-h

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

About choosing the port name:
Repology has no entry for `datraw`. First search result on Google and Bing for `datraw` is the GitHub repo of this library (at least when searching from my location). There is an official NuGet Package of this library also using the name `datraw` (https://nuget.info/packages/datraw).
The name "dat/raw", ".dat .raw file pairs", or similar is sometimes used in scientific literature to refer to a volume data file format. This library is a reader of that format.

2024-01-16 07:58 UTC, FrankXie05 requested changes

2024-01-16 07:58 UTC, FrankXie05 commented on ports/datraw/portfile.cmake
> +# header-only library
```suggestion
set(VCPKG_BUILD_TYPE release) # Header-only library
```

2024-01-16 13:11 UTC, moritz-h commented on ports/datraw/portfile.cmake
> +# header-only library
For future reference and that I understand this better: So far I thought setting the `VCPKG_BUILD_TYPE` to release is only required for header-only libraries i.e. when vcpkg_cmake_configure or other build systems are involved to avoid building an unnecessary extra debug copy. But as here only files are copied in the port, there is no debug/release duplication anyway. So technically it is probably not needed, but do you want that generally added to all header-only ports for style and future proof reasons or is there something I'm missing?

2024-01-17 02:14 UTC, FrankXie05 commented on ports/datraw/portfile.cmake
> +# header-only library
Of course it can be unnecessary if there is no build involved. :)

2024-01-18 02:02 UTC, FrankXie05 approved these changes

2024-01-19 20:41 UTC, merged