[fakeit] Fix fakeit build
microsoft/vcpkg pull request #36195
Opened 2024-01-16 09:42 UTC by MonicaLiu0311

Fixes #36180, use `vcpkg_cmake_configure()` to build `fakeit` and install the `config*.cmake` files.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~SHA512s are updated for each updated download~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-01-17 09:16 UTC, FrankXie05 commented on ports/fakeit/usage
> +  target_link_libraries(main PRIVATE FakeIt::FakeIt-boost FakeIt::FakeIt-catch FakeIt::FakeIt-cute FakeIt::FakeIt-doctest FakeIt::FakeIt-gtest FakeIt::FakeIt-mettle FakeIt::FakeIt-mstest FakeIt::Fake
We need to export all link targets to avoid confusion, and this approach is consistent with the upstream cmake configuration.

2024-01-17 09:16 UTC, FrankXie05 submitted a review, later dismissed

2024-01-17 16:21 UTC, dg0yt requested changes

2024-01-17 16:21 UTC, dg0yt commented on ports/fakeit/usage
> +  target_link_libraries(main PRIVATE FakeIt::FakeIt-boost FakeIt::FakeIt-catch FakeIt::FakeIt-cute FakeIt::FakeIt-doctest FakeIt::FakeIt-gtest FakeIt::FakeIt-mettle FakeIt::FakeIt-mstest FakeIt::Fake
> We need to export all link targets to avoid confusion, and this approach is consistent with the upstream cmake configuration.

No, it is not consistent with upstream.
No, we don't need to print it like this. 
Actual we must not print it like this to avoid confusion.

The vcpkg tool has a heuristical usage generator which can't do better to list a short list of target. Whether it makes sense or not. (And that's why there is an extra comment!)
But there is no need to put the same type of uninformed guess into `usage` files. Either print a key example and link to docs, or provide useful hints.
Example: `ports/geos/usage`.

2024-01-17 19:43 UTC, JavierMatosD requested changes

2024-01-17 19:43 UTC, JavierMatosD commented on ports/fakeit/usage
> +  target_link_libraries(main PRIVATE FakeIt::FakeIt-boost FakeIt::FakeIt-catch FakeIt::FakeIt-cute FakeIt::FakeIt-doctest FakeIt::FakeIt-gtest FakeIt::FakeIt-mettle FakeIt::FakeIt-mstest FakeIt::Fake
The point of a usage file is to provide the [minimal steps necessary to integrate with a build system](https://learn.microsoft.com/en-us/vcpkg/maintainers/handling-usage-files) NOT to provide an exhaustive list of everything the port offers. Providing a usage example that includes multiple framework targets could lead users to mistakenly link against all of them, which is typically not the intended use case (I'm assuming). The usage file should reflect how the library is typically used in its upstream source. If the upstream source recommends or documents specific common usage patterns, the vcpkg usage file should ideally align with that.  Overloading it with all possible options can lead to confusion, especially for new users. I agree with @dg0yt on using `ports/geos/usage` as an example. 

I don't know much about the port, but after a brief glance I'd suggest something like:

```
The package FakeIt provides CMake targets:

# Main usage
find_package(FakeIt CONFIG REQUIRED)
target_link_libraries(main PRIVATE FakeIt::FakeIt_dev)

# For specific test framework configurations (e.g., boost, catch, gtest, etc.),
# additional targets are available in the format FakeIt::FakeIt-<framework>.
# Refer to the upstream documentation for detailed usage of these targets.
```

You don't have to take my example wholesale, since I'm assuming you know more about the port than I do, but something like that.

2024-01-19 03:14 UTC, MonicaLiu0311 commented on ports/fakeit/usage
> +  target_link_libraries(main PRIVATE FakeIt::FakeIt-boost FakeIt::FakeIt-catch FakeIt::FakeIt-cute FakeIt::FakeIt-doctest FakeIt::FakeIt-gtest FakeIt::FakeIt-mettle FakeIt::FakeIt-mstest FakeIt::Fake
Since upstream doesn't provide its own source files: 
[2.4.0/include/CMakeLists.txt](https://github.com/eranpeer/FakeIt/blob/2.4.0/include/CMakeLists.txt), 
[2.4.0#using-the-source-header-files](https://github.com/eranpeer/FakeIt/tree/2.4.0?tab=readme-ov-file#using-the-source-header-files). 
I didn't change it, so I'm just going to provide a usage for testing a specific framework: 
[2.4.0/single_header/CMakeLists.txt](https://github.com/eranpeer/FakeIt/blob/2.4.0/single_header/CMakeLists.txt), 
[2.4.0#using-a-pre-packaged-single-header-file](https://github.com/eranpeer/FakeIt/tree/2.4.0?tab=readme-ov-file#using-a-pre-packaged-single-header-file).
```
The package FakeIt provides CMake targets:

    # Usage for specific framework tests (e.g. boost, catch, gtest, etc.)
    find_package(FakeIt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE FakeIt::FakeIt-<framework>)

    # Only specific test framework configuration files are provided upstream.
    # It does not install its own source header files.
    # So only the usage of the test framework is provided here.
```

2024-01-24 23:28 UTC, JavierMatosD approved these changes

2024-01-24 23:28 UTC, merged

2024-03-11 21:28 UTC, cardinotGV commented
This seems to be broken for Linux now. Tested from 2024.02.14