[apriltag] New port added
microsoft/vcpkg pull request #36336
Opened 2024-01-24 02:10 UTC by AenBleidd

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-01-24 05:05 UTC, dg0yt requested changes
The patch can be much smaller...
If they don't define DLL exports in a proper way, the portfile must  do 
~~~cmake
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()

2024-01-24 05:05 UTC, dg0yt commented on ports/apriltag/fix-config.patch
> ++# endif()
Vcpkg does set `CMAKE_BUILD_TYPE`.
And the only block defines an option.
```suggestion
 if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    message(STATUS "Setting build type to '${default_build_type}' as none was specified.")
    set(CMAKE_BUILD_TYPE "${default_build_type}" CACHE  STRING "Choose the type of build." FORCE)
    # Set the possible values of build type for cmake-gui
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS  "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
 endif()
```

2024-01-24 05:05 UTC, dg0yt commented on ports/apriltag/fix-config.patch
> ++set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
Forbidden by vcpkg policies.
```suggestion
```

2024-01-24 05:05 UTC, dg0yt commented on ports/apriltag/fix-config.patch
> ++    find_dependency(PThreads4W)
```suggestion
+    find_package(PThreads4W)
```

2024-01-24 05:05 UTC, dg0yt commented on ports/apriltag/fix-config.patch
> ++    find_dependency(Threads)
```suggestion
     find_package(Threads REQUIRED)
```

2024-01-24 05:05 UTC, dg0yt commented on ports/apriltag/fix-config.patch
> ++#set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX "d")
Not allowed to be changed, vcpkg policy.

2024-01-24 08:14 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2024-01-24 08:49 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++include(CMakeFindDependencyMacro)
Fixed

2024-01-24 08:49 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++# set(default_build_type "Release")
Fixed

2024-01-24 08:49 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++# endif()
Fixed

2024-01-24 08:50 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
Fixed

2024-01-24 08:50 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++    find_dependency(PThreads4W)
Fixed

2024-01-24 08:50 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++#set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX "d")
Fixed

2024-01-24 09:08 UTC, AenBleidd commented
@jimwang118, ready for review.
@dg0yt, thank you for your suggestions. I'm not really happy to have static library only for Windows, but I may assume this is much better since the library itself doesn't provide a good exports for Windows.

2024-01-24 11:50 UTC, AenBleidd commented
Looks like the OSX machine failed the build due to some unrelated to this PR issue.

2024-01-24 15:49 UTC, AenBleidd commented on ports/apriltag/fix-config.patch
> ++#option(BUILD_SHARED_LIBS "Build shared libraries" ON)
Fixed as well

2024-01-25 08:45 UTC, jimwang118 commented
I get the following error when testing usage.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at F:/apriltag/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  By not providing "Findapriltag.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "apriltag",
  but CMake did not find one.

  Could not find a package configuration file provided by "apriltag" with any
  of the following names:

    apriltagConfig.cmake
    apriltag-config.cmake

  Add the installation prefix of "apriltag" to CMAKE_PREFIX_PATH or set
  "apriltag_DIR" to a directory containing one of the above files.  If
  "apriltag" provides a separate development package or SDK, be sure it has
  been installed.		F:/apriltag/scripts/buildsystems/vcpkg.cmake	859	

```

2024-01-25 09:28 UTC, jimwang118 commented
I get the following error when testing usage.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at F:/apriltag/installed/x64-windows/share/apriltag/apriltagTargets.cmake:60 (set_target_properties):
  The link interface of target "apriltag::apriltag" contains:

    PThreads4W::PThreads4W

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		F:/apriltag/installed/x64-windows/share/apriltag/apriltagTargets.cmake	60	

```

2024-01-25 10:33 UTC, AenBleidd commented
@jimwang118, fixed

2024-01-25 23:53 UTC, JavierMatosD commented
I've verified the usage :)

Thanks for the port!

@jimwang118, @dg0yt thanks for helping review this!

2024-01-25 23:53 UTC, merged