[dcmtk] Fix dependencies
microsoft/vcpkg pull request #36607
Opened 2024-02-06 07:00 UTC by jimwang118

Fixes https://github.com/microsoft/vcpkg/issues/36509

Fix the method of finding `lzma` in `tiff`.
```
ld: Undefined symbols:
  _lzma_code, referenced from:
      _ in libtiff.a[24](tif_lzma.c.o)
      _LZMAPostEncode in libtiff.a[24](tif_lzma.c.o)
      _LZMAEncode in libtiff.a[24](tif_lzma.c.o)
```
Fix the duplicate names of functions in `jpeg` and `dcmtk`.
```
duplicate symbol '_jpeg12_read_scanlines' in:
    /Users/vcpkg/jim/vcpkg/installed/arm64-osx/lib/libjpeg.a[24](jdapistd.c.o)
    lib/libijg12.a[29](jdapistd.c.o)
duplicate symbol '_jpeg16_read_scanlines' in:
    /Users/vcpkg/jim/vcpkg/installed/arm64-osx/lib/libjpeg.a[52](jdapistd.c.o)
    lib/libijg16.a[29](jdapistd.c.o)
duplicate symbol '_jpeg12_read_raw_data' in:
    /Users/vcpkg/jim/vcpkg/installed/arm64-osx/lib/libjpeg.a[24](jdapistd.c.o)
    lib/libijg12.a[29](jdapistd.c.o)
ld: 3 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x64-windows
arm64-osx
```

2024-02-06 07:49 UTC, dg0yt requested changes

2024-02-06 07:49 UTC, dg0yt commented on ports/tiff/Findlzma.patch
> ++find_package(liblzma CONFIG REQUIRED)
IMO this change to tiff is not necessary at all.

2024-02-06 07:51 UTC, dg0yt commented
> ~~~
> ld: Undefined symbols:
>   _lzma_code, referenced from:
>       _ in libtiff.a[24](tif_lzma.c.o)
>       _LZMAPostEncode in libtiff.a[24](tif_lzma.c.o)
>       _LZMAEncode in libtiff.a[24](tif_lzma.c.o)

dcmtk isn't linking tiff correctly. dcmtk bug, not tiff bug.

2024-02-06 07:53 UTC, dg0yt commented
Mixing two similar implementations of jpeg (port libjpeg-turbo via port tiff, and a vendored copy in dcmtk) is asking for all kind of trouble.

2024-02-06 07:55 UTC, dg0yt commented
And port dcmtk even doesn't allow users to opt out from the dependencies' default features.

2024-02-06 15:50 UTC, dg0yt commented on ports/dcmtk/fix_link_tiff.patch
> ++      set(LIBTIFF_LIBS TIFF::TIFF ${TIFF_EXTRA_LIBS_STATIC})
Does it export cmake config with `find_dependency(TIFF)`?
Otherwise 
```suggestion
-      set(LIBTIFF_LIBS ${TIFF_LIBRARY} ${TIFF_EXTRA_LIBS_STATIC} ${JPEG_LIBRARY})
+      set(LIBTIFF_LIBS ${TIFF_LIBRARIES})
```

2024-02-08 02:33 UTC, MonicaLiu0311 approved these changes

2024-02-08 06:27 UTC, merged