[taglib] Update to 2.0
microsoft/vcpkg pull request #36623
Opened 2024-02-07 03:20 UTC by nlogozzo

Fixes #36594 

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Tested on `x64-windows`

2024-02-08 06:50 UTC, LilyWangLL commented
Usage test passed on `x64-windows`.

2024-02-08 06:52 UTC, LilyWangLL commented
Please remove the usage file and code `file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")` in portfile.cmake, vcpkg will output the following usage:
```
taglib provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(taglib CONFIG REQUIRED)
  target_link_libraries(main PRIVATE TagLib::tag TagLib::tag_c TagLib::TagLib)

taglib provides pkg-config modules:

    # Audio meta-data library
    taglib

    # Audio meta-data library (C bindings)
    taglib_c
```

2024-02-08 06:53 UTC, LilyWangLL requested changes, later dismissed

2024-02-08 06:53 UTC, LilyWangLL commented on ports/taglib/vcpkg.json
> +  "version-semver": "2.0.0",
```suggestion
  "version": "2.0.0",
```

2024-02-08 06:53 UTC, LilyWangLL commented on ports/taglib/vcpkg.json
> +  "version-semver": "2.0.0",
Is this port a semver library? If it is not, here should use `"version"`?

2024-02-08 06:53 UTC, LilyWangLL commented on ports/taglib/portfile.cmake
> +    REF v2.0
```suggestion
    REF "v${VERSION}"
```

2024-02-10 04:32 UTC, nlogozzo commented
fixed all mentioned issues

2024-02-14 06:25 UTC, data-queue approved these changes

2024-02-14 06:25 UTC, merged