[sdl2-mixer] Make wavpack a feature
microsoft/vcpkg pull request #36982
Opened 2024-02-27 06:47 UTC by JonLiu1993

Fixes #36787

`Make the new wavpack dependency a togglable feature, enabled by default.`

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-02-29 00:58 UTC, vicroms commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
Does `wavpack` really need to be a default feature? Default features are complicated to disable, so if `sdl2-mixer` can be successfully used in most cases without this feature we shouldn't make it a default.

2024-02-29 08:16 UTC, dg0yt commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@vicroms If IIUC it is upstream's decision that wavpack is on by default, and vcpkg wants to follow upstream when it comes to default features.

https://github.com/libsdl-org/SDL_mixer/blob/8a0af850229ab464d10a3e964282386fb6341628/CMakeLists.txt#L183  
https://github.com/libsdl-org/SDL_mixer/blob/8a0af850229ab464d10a3e964282386fb6341628/CMakeLists.txt#L861-L862

2024-03-10 09:13 UTC, matthiakl commented
Any chance that this gets merged soon?

2024-03-11 02:55 UTC, JonLiu1993 commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@vicroms, sdl2-mixer couldn't install successfully without wavpack, so I added it as a feature and made it default.

2024-03-11 18:21 UTC, vicroms approved these changes, later dismissed

2024-03-12 03:57 UTC, BillyONeal commented
I want to talk with the other maintainers about the default features thing before merging but other than that this LGTM

2024-03-12 07:08 UTC, vicroms commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@JonLiu1993 can you elaborate more? How is the installation unsuccessful currently?

2024-03-12 09:01 UTC, JonLiu1993 commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
Yes, when I add wavpack as default feature, I run the command `./vcpkg install sdl2-mixer[core]:x64-windows` and it will get the same error
When I add WavPack as a normal feature, I get the same error when I run the command `./vcpkg install sinstal sdl2-mixer:x64-windows`.

2024-03-12 09:09 UTC, vicroms commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
Then for this to be a valid feature we need to patch the library to build even with `wavpack` off.

2024-03-12 09:09 UTC, vicroms requested changes
Make the library able to build with `wavpack` off or remove the feature toggle.

2024-03-12 21:21 UTC, matthiakl commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
Building x64-windows-static with this patch works perfectly fine:
https://github.com/matthiakl/widelands/actions/runs/8252974280/job/22573754137#step:5:94
No traces of wavpack during installation and building and linking against sdl2-mixer succeeds.
With x64-linux it does also work. Is this only related to x64-windows or is there an issue with your test setup?

2024-03-13 21:31 UTC, vicroms commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@JonLiu1993 

I tested `sdl2-mixer[core]` locally and it seems to be working fine as reported by @matthiakl 
Can you try again with `wavpack` removed from the default features?

2024-03-15 01:56 UTC, JonLiu1993 commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@vicroms @matthiakl , Sorry for causing any disturbance to you, maybe because my local branch was contaminated, I re-pulled a new branch and tested it successfully using the commands.
`./vcpkg install sdl2-mixer[core]:x64-windows`
`./vcpkg install sdl2-mixer[core]:x64-windows-static`

2024-03-15 02:11 UTC, JonLiu1993 commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@vicroms @matthiakl Sorry for any disruption, probably because my local branch was tainted, I re-pulled a new branch with my PR and removed 
````
"default-features": [
     "wavpack"
   ]
````
Then successfully tested it using command.
`./vcpkg install sdl2-mixer[core]:x64-windows`
`./vcpkg install sdl2-mixer[core]:x64-windows-static`

2024-03-17 20:45 UTC, matthiakl commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
If it is working, can you mark the PR ready to get it reviewed and merged?

2024-03-18 07:16 UTC, JonLiu1993 commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
@vicroms, Based on the success of the test we discussed earlier, can we allow this PR to be merged?

2024-03-18 20:37 UTC, vicroms commented on ports/sdl2-mixer/vcpkg.json
> +  "default-features": [
I still want `wavpack` to be removed from the default features. I could bring this PR for discussion on the next meeting if you feel that `wavpack` needs to be a default feature.

2024-03-18 21:22 UTC, BillyONeal approved these changes
```console
PS D:\vcpkg> .\vcpkg.exe install sdl2-mixer[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * libogg:x64-windows@1.3.5#1
  * libvorbis:x64-windows@1.3.7#2
  * sdl2:x64-windows@2.30.0
    sdl2-mixer:x64-windows@2.8.0#3
  * vcpkg-cmake:x64-windows@2023-05-04
  * vcpkg-cmake-config:x64-windows@2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\bion\AppData\Local\vcpkg\archives in 1.65 ms. Use --debug to see more details.
Installing 1/6 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
-- Installing: D:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: D:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: D:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: D:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: D:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 59.7 ms.
Elapsed time to handle vcpkg-cmake:x64-windows: 116 ms
vcpkg-cmake:x64-windows package ABI: 0a65aa467d00c643bd528a44d90bcd763188b085907ac0a3f1894adc09d67e08
Installing 2/6 vcpkg-cmake-config:x64-windows@2022-02-06#1...
Building vcpkg-cmake-config:x64-windows@2022-02-06#1...
-- Installing: D:/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: D:/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: D:/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 23.4 ms.
Elapsed time to handle vcpkg-cmake-config:x64-windows: 60.1 ms
vcpkg-cmake-config:x64-windows package ABI: 6e43d0df2ba4328b9218863ae0c24aeb8d4f89227303b0659c76cb879dfe0a71
Installing 3/6 libogg:x64-windows@1.3.5#1...
Building libogg:x64-windows@1.3.5#1...
-- Using cached xiph-ogg-v1.3.5.tar.gz.
-- Extracting source D:/vcpkg-downloads/xiph-ogg-v1.3.5.tar.gz
-- Using source at D:/vcpkg/buildtrees/libogg/src/v1.3.5-1a4243fef9.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/vcpkg/packages/libogg_x64-windows/lib/pkgconfig/ogg.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg-downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: D:/vcpkg/packages/libogg_x64-windows/debug/lib/pkgconfig/ogg.pc
-- Installing: D:/vcpkg/packages/libogg_x64-windows/share/libogg/copyright      
-- Performing post-build validation
Stored binaries in 1 destinations in 89.9 ms.
Elapsed time to handle libogg:x64-windows: 7.7 s
libogg:x64-windows package ABI: dff2ed36b527703748f1ba35b0c2fa427dd756aefc3f8cc92b129701bae6c21d
Installing 4/6 libvorbis:x64-windows@1.3.7#2...
Building libvorbis:x64-windows@1.3.7#2...
-- Using cached xiph-vorbis-v1.3.7.tar.gz.
-- Extracting source D:/vcpkg-downloads/xiph-vorbis-v1.3.7.tar.gz
-- Applying patch 0001-Dont-export-vorbisenc-functions.patch
-- Applying patch 0002-Fixup-pkgconfig-libs.patch
-- Applying patch 0003-def-mingw-compat.patch
-- Using source at D:/vcpkg/buildtrees/libvorbis/src/v1.3.7-1480004d18.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/vcpkg/packages/libvorbis_x64-windows/lib/pkgconfig/vorbis.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/libvorbis_x64-windows/lib/pkgconfig/vorbisenc.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/libvorbis_x64-windows/lib/pkgconfig/vorbisfile.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.       
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg-downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: D:/vcpkg/packages/libvorbis_x64-windows/debug/lib/pkgconfig/vorbis.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/libvorbis_x64-windows/debug/lib/pkgconfig/vorbisenc.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/libvorbis_x64-windows/debug/lib/pkgconfig/vorbisfile.pc
-- Installing: D:/vcpkg/packages/libvorbis_x64-windows/share/libvorbis/usage
-- Installing: D:/vcpkg/packages/libvorbis_x64-windows/share/libvorbis/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 138 ms.
Elapsed time to handle libvorbis:x64-windows: 3.7 s
libvorbis:x64-windows package ABI: 2f922f0fa40f2b1b271635d32cc6894ad26288177315379c0a5f296015cdc823
Installing 5/6 sdl2:x64-windows@2.30.0...
Building sdl2:x64-windows@2.30.0...
-- Downloading https://github.com/libsdl-org/SDL/archive/release-2.30.0.tar.gz -> libsdl-org-SDL-release-2.30.0.tar.gz...
-- Extracting source D:/vcpkg-downloads/libsdl-org-SDL-release-2.30.0.tar.gz
-- Applying patch deps.patch
-- Applying patch alsa-dep-fix.patch
-- Using source at D:/vcpkg/buildtrees/sdl2/src/ase-2.30.0-3ceee4a14f.clean
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      CMAKE_DISABLE_FIND_PACKAGE_ALSA
      CMAKE_REQUIRE_FIND_PACKAGE_ALSA

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the   
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/sdl2/portfile.cmake:43 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/vcpkg/packages/sdl2_x64-windows/lib/pkgconfig/sdl2.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.       
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg-downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: D:/vcpkg/packages/sdl2_x64-windows/debug/lib/pkgconfig/sdl2.pc
-- Installing: D:/vcpkg/packages/sdl2_x64-windows/share/sdl2/usage
-- Installing: D:/vcpkg/packages/sdl2_x64-windows/share/sdl2/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 663 ms.
Elapsed time to handle sdl2:x64-windows: 22 s
sdl2:x64-windows package ABI: 4c86e55e130676fe897bd5bd57a2127ec8e2a233190073ff2336b479f33795a9
Installing 6/6 sdl2-mixer:x64-windows@2.8.0#3...
Building sdl2-mixer:x64-windows@2.8.0#3...
-- Downloading https://github.com/libsdl-org/SDL_mixer/archive/release-2.8.0.tar.gz -> libsdl-org-SDL_mixer-release-2.8.0.tar.gz...
-- Extracting source D:/vcpkg-downloads/libsdl-org-SDL_mixer-release-2.8.0.tar.gz
-- Applying patch fix-pkg-prefix.patch
-- Using source at D:/vcpkg/buildtrees/sdl2-mixer/src/ease-2.8.0-5d1a2b7a04.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/vcpkg/packages/sdl2-mixer_x64-windows/lib/pkgconfig/SDL2_mixer.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.       
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg-downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: D:/vcpkg/packages/sdl2-mixer_x64-windows/debug/lib/pkgconfig/SDL2_mixer.pc
-- Installing: D:/vcpkg/packages/sdl2-mixer_x64-windows/share/sdl2-mixer/usage
-- Installing: D:/vcpkg/packages/sdl2-mixer_x64-windows/share/sdl2-mixer/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 105 ms.
Elapsed time  [...]

2024-03-19 22:03 UTC, vicroms approved these changes

2024-03-19 22:07 UTC, merged

2024-03-19 22:07 UTC, BillyONeal commented
Thanks for the feature!