[liblzf] New port
microsoft/vcpkg pull request #37006
Opened 2024-02-27 22:31 UTC by valgur

Adds liblzf: http://software.schmorp.de/pkg/liblzf.html

[![Packaging status](https://repology.org/badge/tiny-repos/liblzf.svg)](https://repology.org/project/liblzf/versions)

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-02-28 06:38 UTC, dg0yt reviewed
Another new port for unmaintained software?

2024-02-28 06:38 UTC, dg0yt commented on ports/liblzf/CMakeLists.txt
> +endif()
Not for vcpkg. Done by the toolchain.

2024-02-28 06:38 UTC, dg0yt commented on ports/liblzf/CMakeLists.txt
> +set_target_properties(liblzf PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
Discouraged in vcpkg.

2024-02-28 06:38 UTC, dg0yt commented on ports/liblzf/CMakeLists.txt
> +    "${CMAKE_CURRENT_BINARY_DIR}/unofficial-liblzf-config-version.cmake"
```suggestion
    "${CMAKE_CURRENT_BINARY_DIR}/unofficial-liblzf-config-version.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/unofficial-liblzf-targets.cmake"
```
from above `install(... EXPORT ...)`.

2024-02-28 06:38 UTC, dg0yt commented on ports/liblzf/CMakeLists.txt
> +)
```suggestion
```
`export(EXPORT ...)` is not for installation.

2024-02-28 06:38 UTC, dg0yt commented on ports/liblzf/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

2024-02-28 06:38 UTC, dg0yt commented on ports/liblzf/usage
> +The magic.mgc file can be accessed from the unofficial-libmagic_DICTIONARY variable.
Really?

2024-02-28 07:20 UTC, valgur commented
Thanks, @dg0yt! Was not really expecting a review for this draft PR yet.

> Another new port for unmaintained software?

Yes. It's unfortunately the standard compression format for .pcd point cloud files frequently used in robotics.

2024-03-01 11:09 UTC, WangWeiLin-MV requested changes

2024-03-01 11:09 UTC, WangWeiLin-MV commented on ports/liblzf/CMakeLists.txt
> +    DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
```suggestion
set(LIBLZF_SHARE_DIR share/unofficial-liblzf)
install(EXPORT unofficial-liblzf-targets
    FILE unofficial-liblzf-config.cmake
    NAMESPACE unofficial::liblzf::
    DESTINATION ${LIBLZF_SHARE_DIR}
)
```

2024-03-01 11:09 UTC, WangWeiLin-MV commented on ports/liblzf/CMakeLists.txt
> +    "${CMAKE_CURRENT_BINARY_DIR}/unofficial-liblzf-targets.cmake"
```suggestion
```

2024-03-01 11:09 UTC, WangWeiLin-MV commented on ports/liblzf/portfile.cmake
> +vcpkg_cmake_config_fixup()
```suggestion
vcpkg_cmake_config_fixup(PACKAGE_NAME "unofficial-liblzf")
```

2024-03-01 11:09 UTC, WangWeiLin-MV commented on ports/liblzf/portfile.cmake
> +file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```suggestion

```
There is heuristically generated usage for CMake ports.

2024-03-01 11:09 UTC, WangWeiLin-MV commented on ports/liblzf/usage
Remove this usage file. There is heuristically generated usage for CMake ports.

2024-03-04 02:44 UTC, WangWeiLin-MV approved these changes
Port usage test pass with following triplets:
* x64-linux
* x64-windows
* x64-windows-static
* x86-windows

2024-03-04 07:19 UTC, JonLiu1993 approved these changes

2024-03-05 09:52 UTC, merged