Libfork
microsoft/vcpkg pull request #37048
Opened 2024-02-29 13:48 UTC by ConorWilliams

This PR adds [libfork](https://github.com/ConorWilliams/libfork), a [portable continuation stealing framework](https://arxiv.org/abs/2402.18480). I am the author of the package.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-03-01 02:36 UTC, jimwang118 requested changes

2024-03-01 02:36 UTC, jimwang118 commented on ports/libfork/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")
```

2024-03-01 02:36 UTC, jimwang118 commented on ports/libfork/usage
> +    target_link_libraries(main PRIVATE libfork::libfork)
Add a blank line to the end of the file.

2024-03-01 02:36 UTC, jimwang118 commented on ports/libfork/vcpkg.json
> +  "version": "3.7.1",
```suggestion
  "version": "${VERSION}",
```

2024-03-01 02:39 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2024-03-01 03:11 UTC, jimwang118 commented
May I ask where the compiled lib file is installed?

2024-03-01 14:43 UTC, ConorWilliams commented
> May I ask where the compiled lib file is installed?

It is a header-only lib

2024-03-04 02:26 UTC, jimwang118 submitted a review, later dismissed

2024-03-04 02:39 UTC, jimwang118 commented
Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

2024-03-04 12:04 UTC, ConorWilliams commented
> Usage test pass with following triplets:
> 
> ```
> x86-windows
> x64-windows
> x64-windows-static
> ```

Fantastic, are we good to merge?

2024-03-05 10:00 UTC, merged