[libmodplug] Fix WASM build by pinning C++ standard to 11
microsoft/vcpkg pull request #37090
Opened 2024-03-02 04:12 UTC by fwcd

Fixes #37089 

The port uses the register storage class specifier which was removed in C++17, pinning the standard to C++11 solves this.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-03-04 06:33 UTC, FrankXie05 requested changes

2024-03-04 06:33 UTC, FrankXie05 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2024-03-04 06:41 UTC, fwcd commented on ports/libmodplug/portfile.cmake
> +)
If we do this, I would probably go with `VCPKG_TARGET_IS_EMSCRIPTEN`, since this is specific to the compiler. Off top of my head, we'd probably also have to move it above the configure.

I'm actually a bit surprised that it builds on all other major platforms as-is though, especially given that Emscripten just runs Clang under the hood. Maybe the major compilers are more lenient when it comes to accepting older C++ standards by default?

2024-03-04 07:21 UTC, FrankXie05 commented on ports/libmodplug/portfile.cmake
> +)
Upstream has no special instructions for the C++ standard, so a lower standard may be accepted. ：）

2024-03-04 07:22 UTC, FrankXie05 commented on ports/libmodplug/portfile.cmake
> +)
It's better to use `VCPKG_TARGET_IS_EMSCRIPTEN`.

2024-03-05 08:51 UTC, FrankXie05 approved these changes

2024-03-05 09:46 UTC, merged