[directxmath] port update to fix include path in pkgconfig
microsoft/vcpkg pull request #37151
Opened 2024-03-05 21:10 UTC by walbourn

The include path in the generated pkgconfig was incorrect. This updates the port to use the version upstream with this fix.

2024-03-05 21:11 UTC, walbourn commented
Upstream fix can be seen here: https://github.com/microsoft/DirectXMath/pull/188

2024-03-06 02:58 UTC, WangWeiLin-MV requested changes
Since the port `REF` is updated, the `version-date` needs to be updated instead of the `port-version`.

2024-03-06 19:03 UTC, walbourn commented
The version date matches the NuGet package and GitHub releases that have the idential header files. The only differenence between feb2024 and feb2024b is the one CMakeLists.txt fix to pkgconfig. There is no functional difference at all, which is why I went with a port-version update instead.

2024-03-07 03:03 UTC, WangWeiLin-MV approved these changes

2024-03-08 06:53 UTC, merged