[directxtex] Update for March 2024 release
microsoft/vcpkg pull request #37233
Opened 2024-03-07 20:22 UTC by walbourn

In addition to updating for the latest release on GitHub, this adds support for four new *features*:

* **jpeg** this adds JPEG support for Linux (Windows already had it via WIC)
* **png** this adds PNG support for Linux (Windows already had it via WIC)
* **xboxone** this builds the library for PC but with Xbox One extensions for development. Requires the Microsoft GDKX.
* **xboxseriesx** this builds the library for PC but with Xbox Series X|S extensions for development. Requires the Microsoft GDKX.

> The **xboxone** and **xboxseriesx** features are mutually exlusive.

2024-03-07 20:50 UTC, walbourn commented
Verified all supported triplets and features:

```
.\vcpkg install directxtex[core]:x86-windows
.\vcpkg install directxtex:x86-windows --recurse
.\vcpkg install directxtex[tools]:x86-windows --recurse
.\vcpkg install directxtex[dx12]:x86-windows --recurse
.\vcpkg install directxtex[openexr,tools]:x86-windows --recurse
.\vcpkg install directxtex[spectre]:x86-windows --recurse
.\vcpkg install directxtex:x86-windows-static
.\vcpkg install directxtex:x86-windows-static-md

.\vcpkg install directxtex[core]:x64-windows
.\vcpkg install directxtex:x64-windows --recurse
.\vcpkg install directxtex[tools]:x64-windows --recurse
.\vcpkg install directxtex[dx12]:x64-windows --recurse
.\vcpkg install directxtex[openexr,tools]:x64-windows --recurse
.\vcpkg install directxtex[spectre]:x64-windows --recurse
.\vcpkg install directxtex:x64-windows-static
.\vcpkg install directxtex:x64-windows-static-md

.\vcpkg install directxtex:arm64-windows
.\vcpkg install directxtex[tools]:arm64-windows --recurse 
.\vcpkg install directxtex[spectre]:arm64-windows --recurse
.\vcpkg install directxtex:arm64-windows-static
.\vcpkg install directxtex:arm64-windows-static-md

.\vcpkg install directxtex:x86-uwp 
.\vcpkg install directxtex:x64-uwp 
.\vcpkg install directxtex:arm64-uwp 

.\vcpkg install directxtex:x64-mingw-static
.\vcpkg install directxtex[dx12]:x64-mingw-static --recurse
.\vcpkg install directxtex[tools]:x64-mingw-static --recurse

.\vcpkg install directxtex:x86-mingw-static
.\vcpkg install directxtex[dx12]:x86-mingw-static --recurse
.\vcpkg install directxtex[tools]:x86-mingw-static --recurse

./vcpkg install directxtex:x64-linux
./vcpkg install directxtex[dx12]:x64-linux --recurse
./vcpkg install directxtex[openexr]:x64-linux --recurse
./vcpkg install directxtex[jpeg]:x64-linux --recurse
./vcpkg install directxtex[png]:x64-linux --recurse

./vcpkg install directxtex:arm64-linux
./vcpkg install directxtex[dx12]:arm64-linux --recurse
./vcpkg install directxtex[openexr]:arm64-linux --recurse
./vcpkg install directxtex[jpeg]:arm64-linux --recurse
./vcpkg install directxtex[png]:arm64-linux --recurse
```

Windows on ARM (32-bit) triplets build, although this platform has been deprecated:

```
.\vcpkg install directxtex:arm-windows
.\vcpkg install directxtex[tools]:arm-windows --recurse
.\vcpkg install directxtex[spectre]:arm-windows --recurse

.\vcpkg install directxtex:arm-uwp 
```

The following are supported on systems with the *Microsoft GDK with Xbox Extensions* installed:

```
.\vcpkg install directxtex:x64-xbox-scarlett
.\vcpkg install directxtex:x64-xbox-scarlett-static

.\vcpkg install directxtex:x64-xbox-xboxone
.\vcpkg install directxtex:x64-xbox-xboxone-static

.\vcpkg install directxtex[xboxone,tools]:x64-windows --recurse
.\vcpkg remove directxtex:x64-windows
.\vcpkg install directxtex[xboxseriesx,tools]:x64-windows
```

Also verified with proposed Clang/CL community triplets (#31028):

```
.\vcpkg install directxtex[core]:x64-clangcl-dynamic
.\vcpkg install directxtex:x64-clangcl-dynamic --recurse
.\vcpkg install directxtex[tools]:x64-clangcl-dynamic --recurse
.\vcpkg install directxtex[dx12]:x64-clangcl-dynamic --recurse
.\vcpkg install directxtex:x64-clangcl-static
.\vcpkg install directxtex:arm64-clangcl-dynamic
.\vcpkg install directxtex[tools]:arm64-clangcl-dynamic --recurse 
.\vcpkg install directxtex:arm64-clangcl-static
.\vcpkg install directxtex:x64-clangcl-uwp 
.\vcpkg install directxtex:arm64-clangcl-uwp 

.\vcpkg install directxtex:x64-clangcl-scarlett
.\vcpkg install directxtex:x64-clangcl-scarlett-static
.\vcpkg install directxtex:x64-clangcl-xboxone
.\vcpkg install directxtex:x64-clangcl-xboxone-static

.\vcpkg install directxtex:x64-clangcl-dynamic[xboxone,tools] --recursive
.\vcpkg remove directxtex:x64-clangcl-dynamic
.\vcpkg install directxtex:x64-clangcl-dynamic[xboxseriesx,tools]
```

2024-03-08 02:38 UTC, JonLiu1993 submitted a review, later dismissed

2024-03-08 06:31 UTC, vicroms requested changes

2024-03-08 06:31 UTC, vicroms commented on ports/directxtex/portfile.cmake
> +endif()
[Features must not model alternatives](https://learn.microsoft.com/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives).

A workaround would be to have a triplet setting that can be used in conjunction with the feature.

```cmake
if("xbox" IN_LIST FEATURES)
  if(DIRECTXTEX_XBOX_CONSOLE_TARGET  STREQUAL "scarlett")
    list(APPEND FEATURE_OPTIONS "-DBUILD_XBOX_EXTS_SCARLETT")
  elseif(DIRECTXTEX_XBOX_CONSOLE_TARGET  STREQUAL "xboxone")
    list(APPEND FEATURE_OPTIONS "-DBUILD_XBOX_EXTS_XBOXONE")
  else()
    message(FATAL_ERROR "The triplet variable DIRECTXTEX_XBOX_CONSOLE_TARGET must be").
  endif()
endif()
```

 Or use `VCPKG_CMAKE_CONFIGURE_OPTIONS` in the triplet file:
 
 ```cmake
if (PORT STREQUAL "directxtex")
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DBUILD_XBOX_EXTS_XBOXONE") #or scarlett
endif()
```

and adding the instructions to enable these features in the `usage` file

2024-03-08 18:24 UTC, walbourn commented on ports/directxtex/portfile.cmake
> +endif()
OK, so the issue here is that the **xboxone** and **xboxseriesx** features I'm proposing here are NOT for the 'xbox' triplets. It is adding additional functionality to the x64-windows (PC) build of the library which supports off-line texture processing to TARGET the console. The issue I'm having to express here is that you can't build these extensions with the ms-gdkx installed.

In other words, these new features have NOTHING AT ALL to do with the xbox community triplets.

The challenge I'm having is that there are two possible build-modes: one for Xbox Series X|S and one for Xbox One. If mutually exclusive features are not a thing, then how else could I express this?

* I had considered that if you had both `xboxone,xboxseriesx` then I would just force the result to only work for `xboxseriesx`. This seems confusing, but technically meets the requirements.

* Another option is to just not have the `xboxone` feature and only support Xbox Series X|S. This would work, but is not really practical since developers don't generally have the option of ignoring Xbox One scenarios.

2024-03-09 00:16 UTC, vicroms commented on ports/directxtex/portfile.cmake
> +endif()
Hi @walbourn

Thanks for taking the time to explain the scenario.

The problem of alternatives is that two ports on the tree could depend on different exclusive features and that becomes a dependency conflict.

* package `A` - depends on `directxtex[xboxone]`
* package `B` - depends on `directxtex[xboxseriesx]`
* CI must build both `A` and `B` (or a project could depend on both and be unaware of the conflict).

The lack of alternatives is a known limitation, and the team is aware of it. Unfortunately, we don't have a timeline for when we'll be able to design/implement such a feature. 

For the time being, we have accepted the following methods as workaround solutions:

* Let the port hardcode a selection and use an [overlay port](https://learn.microsoft.com/vcpkg/concepts/overlay-ports) to override it
* Let the port read a triplet setting and use an [overlay triplet](https://learn.microsoft.com/vcpkg/concepts/triplets#add-or-replace-triplets) to change the value of the setting (which is the recommendation I gave you above).

In both cases, there is a single feature name that enables the behavior but vcpkg picks a "favorite" as the default. This allows other packages to depend on the feature and lets users override with their desired option.

You can document how to select the alternative through the `usage` file.

2024-03-09 11:46 UTC, dg0yt commented on ports/directxtex/portfile.cmake
> +endif()
> In other words, these new features have NOTHING AT ALL to do with the xbox community triplets.

> Introduce two MORE community triplets: x64-windows-xboxone-static and x64-windows-xboxseriesx-static as variants of x64-windows, 

The feedback was neither suggesting a relation to the xbox community triplets nor suggesting a need for new community triplets. 

The suggestion is that users must customize their triplet files when they needs something else than the default. Triplet files are a customization point for defaults with effect on ABI - and even for exceptions per port.
They are not the optimal point for exeptions and for choosing alternatives, because it is (perceived as) inconvenient, and because these changes impact all cached artifacts. Unfortunately, there is no better point for choosing alternatives at the moment.

2024-03-09 19:51 UTC, walbourn commented on ports/directxtex/portfile.cmake
> +endif()
Thanks. I've taken this feedback.

2024-03-11 09:19 UTC, JonLiu1993 approved these changes

2024-03-11 18:19 UTC, vicroms approved these changes

2024-03-12 03:16 UTC, merged

2024-03-12 03:16 UTC, BillyONeal commented
Thanks for the update!