[libmediainfo] update to 24.01
microsoft/vcpkg pull request #37264
Opened 2024-03-08 10:40 UTC by jiayuehua

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2024-03-11 07:15 UTC, JonLiu1993 commented on ports/libmediainfo/vcpkg.json
> +  "version-string": "24.01",
```suggestion
  "version": "24.01",
```

2024-03-11 07:16 UTC, JonLiu1993 commented on ports/libmediainfo/vcpkg.json
> +  "version-string": "24.01",
@jiayuehua, thanks for the PR, we don't recommend using "version string", especially when "version" is available

2024-03-11 07:17 UTC, JonLiu1993 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2024-03-11 07:34 UTC, dg0yt commented on ports/libmediainfo/vcpkg.json
> +  "version-string": "24.01",
Unfortunately, we cannot use leading zeros with scheme `version`.
What can be done: Use `"version": "24.1"`, and use a REGEX REPLACE to generate other formats in the portfile.

2024-03-11 10:18 UTC, JonLiu1993 approved these changes, later dismissed

2024-03-11 12:13 UTC, dg0yt requested changes
Simplify.

2024-03-11 12:13 UTC, dg0yt commented on ports/libmediainfo/portfile.cmake
> +endif()
```suggestion
string(REGEX REPLACE "[.]([0-9])\$" ".0\\1" VERSION_STR "${VERSION}")
```

2024-03-11 12:13 UTC, dg0yt commented on ports/libmediainfo/portfile.cmake
> +    REF "v${MAJOR}.${padding}${MINOR}"
```suggestion
    REF "v${VERSION_STR}"
```

2024-03-12 03:11 UTC, JonLiu1993 approved these changes

2024-03-12 03:31 UTC, merged

2024-03-12 03:31 UTC, BillyONeal commented
Thanks for the update!