[cs-libguarded] Add new port
microsoft/vcpkg pull request #37551
Opened 2024-03-19 13:28 UTC by BA7LYA

Fixes #37511.

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-03-19 13:41 UTC, Neumann-A commented on ports/cs-libguarded/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
Header only ? Consider using `set(VCPKG_BUILD_TYPE release)`

2024-03-19 13:44 UTC, BA7LYA commented on ports/cs-libguarded/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
thx for the tip :)

2024-03-20 02:40 UTC, Cheney-W commented on ports/cs-libguarded/portfile.cmake
> +    REF libguarded-${VERSION}
```suggestion
    REF "libguarded-${VERSION}"
```

2024-03-20 03:12 UTC, Cheney-W requested changes

2024-03-20 03:12 UTC, Cheney-W commented on ports/cs-libguarded/portfile.cmake
> +vcpkg_cmake_config_fixup(CONFIG_PATH cmake/CsLibGuarded)
```suggestion
vcpkg_cmake_config_fixup(PACKAGE_NAME CsLibGuarded CONFIG_PATH cmake/CsLibGuarded)
```

2024-03-20 03:12 UTC, Cheney-W commented on ports/cs-libguarded/portfile.cmake
> +)
```suggestion
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")

```

2024-03-20 03:12 UTC, Cheney-W commented on ports/cs-libguarded/usage
> +    target_link_libraries(main PRIVATE CopperSpice::CsLibGuarded)
```suggestion
    target_link_libraries(main PRIVATE CsLibGuarded::CsLibGuarded)
```
According to the `CsLibGuardedLibraryTargets.cmake` file, the expected target is `CsLibGuarded::CsLibGuarded`.

2024-03-20 03:12 UTC, Cheney-W commented on ports/cs-libguarded/vcpkg.json
> +      "name": "catch2"
```suggestion
```
`catch2` will only be used when `BUILD_TESTS` is on, so there is no need to add it as a dependency here.

2024-03-20 03:12 UTC, Cheney-W commented on ports/cs-libguarded/vcpkg.json
> +}
```suggestion
}

```

2024-03-20 03:12 UTC, Cheney-W commented on versions/baseline.json
> +}
Please restore the line break here and do not manually modify this file.

2024-03-20 03:42 UTC, BA7LYA commented on ports/cs-libguarded/vcpkg.json
> +      "name": "catch2"
What about mark it as `“host”=true` ?

2024-03-20 04:41 UTC, dg0yt commented on ports/cs-libguarded/vcpkg.json
> +      "name": "catch2"
If it isn't used, it must not appear as a dependency.
Users and CI must rebuild depending packages when a dependency changes.

2024-03-20 04:42 UTC, dg0yt commented on ports/cs-libguarded/vcpkg.json
> +      "name": "catch2"
And it is not a "host" dependency.

2024-03-20 04:51 UTC, dg0yt reviewed
When checking repology, I noticed that there is already a port for this package: 
`libguarded`.
I think that the `cs` prefix is needed, but then the other port must be turned into an empty proxy for this port.

2024-03-20 04:51 UTC, dg0yt commented on ports/cs-libguarded/portfile.cmake
> +    PACKAGE_NAME CsLibGuarded
There are discussions to enforce lower-case package names in `share`, and this option is used only for the directory name. Consider
```suggestion
    PACKAGE_NAME cslibguarded
```
And if the port would be named   `cslibguarded`, mathching the "CsLibGuarded" in the documentation, the option wouldn't be needed.
(I know repology/AUR/Conan have cs-libguarded. But packaging is still rare.)

2024-03-21 14:05 UTC, BA7LYA commented
> When checking repology, I noticed that there is already a port for this package: `libguarded`. I think that the `cs` prefix is needed, but then the other port must be turned into an empty proxy for this port.

Once this PR is accepted, i will submit another PR to fix this.

2024-03-21 19:57 UTC, dg0yt commented
> Once this PR is accepted, i will submit another PR to fix this.

No, you must do it in this PR. Vcpkg nightly CI will install both ports, and then they will probably clash. This cannot be accepted.

And I think we should seriously consider the `cslibguarded` name pattern proposal. It would align docs, cmake package and port. But somebody else will have to decide. (Disclaimer: I'm a community member.)

2025-07-23 18:12 UTC, closed without merging