update osgEath port to osgEarth 3.5
microsoft/vcpkg pull request #37613
Opened 2024-03-21 22:32 UTC by plevy

If this PR updates an existing port, please uncomment and fill out this checklist:

- [x ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ x] SHA512s are updated for each updated download.
- [ x] The "supports" clause reflects platforms that may be fixed by this new version.
- [ x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ x] Any patches that are no longer applied are deleted from the port's directory.
- [ x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ x] Only one version is added to each modified port's versions file.

2024-03-22 07:24 UTC, FrankXie05 requested changes

2024-03-22 07:24 UTC, FrankXie05 commented on ports/osgearth/find-package.patch
> + endif()
These now need to be added as features to support. Otherwise they cannot be used :)

2024-03-22 07:49 UTC, dg0yt commented on ports/osgearth/find-package.patch
> + endif()
~~~diff
-These now need to be added as features to support. 
+These now need to be added as dependencies. 
~~~

2024-03-22 08:20 UTC, FrankXie05 commented
I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

2024-03-22 16:45 UTC, plevy commented on ports/osgearth/find-package.patch
> + endif()
All 3 are similar in that they are not available in vcpkg and turned off by default.  If someone tries to enable them, they should error out.

Silverlining and Triton have been handled this way in previous ports, Cesium Native is new but same in that there is no vcpkg port.

2024-03-25 02:11 UTC, FrankXie05 commented on ports/osgearth/find-package.patch
> + endif()
>Since Silverlining, Triton, and Cesium Native do not have vcpkg ports,

**Silverlining** :
If the feature is not implemented, don't modify it

https://github.com/microsoft/vcpkg/blob/a34c873a9717a888f58dc05268dea15592c2f0ff/ports/osgearth/portfile.cmake#L64

**Triton**:

If you want to modify `find_package(Triton REQUIRED)`, please improve it to a feature (if the port is correct https://github.com/microsoft/vcpkg/blob/master/ports/triton/portfile.cmake)

**Cesium Native**:
If it's not supported, don't modify it. :)

2024-03-25 05:14 UTC, dg0yt commented on ports/osgearth/find-package.patch
> + endif()
FTR the lines are only moved, not added,

2024-03-26 00:14 UTC, plevy commented
I removed the modifications to Triton and Silverlining.  The Triton that we use is this one:
https://sundog-soft.com/portfolio-items/the-triton-ocean-sdk/

Different than the other Triton with a port.

2024-03-26 01:44 UTC, FrankXie05 requested changes

2024-03-26 01:44 UTC, FrankXie05 commented on versions/o-/osgearth.json
> +    },
```suggestion
```

2024-04-30 14:22 UTC, plevy commented
@FrankXie05 @dg0yt I'd still like to complete this port. Any suggestions on how to move it forward?

2024-04-30 17:16 UTC, dg0yt requested changes
After *committing* the changes, run `vcpkg x-add-version --overwrite-version osgearth`, and commit that, too.

And please fix an "osgEath" typo in the PR title.

2024-05-03 00:38 UTC, dg0yt commented
It cannot be merged in this state. Please respond to the review comments.

2024-05-03 21:23 UTC, plevy commented
> It cannot be merged in this state. Please respond to the review comments.

Fixed the patch but the build fails now.  My cmake skills aren't strong, can you take a quick look at the failure.  I think you wrote the original patch.

2024-05-04 05:16 UTC, dg0yt reviewed
Please apply the suggestions in the source and recreate the patch.

2024-05-04 05:16 UTC, dg0yt commented on ports/osgearth/link-libraries.patch
>  +            TARGET_LINK_LIBRARIES(${TRGTNAME} ${${lwv_libraries}})
```suggestion
+-           TARGET_LINK_LIBRARIES(${TRGTNAME} ${${lwv_libraries}})
++           TARGET_LINK_LIBRARIES(${TRGTNAME} PRIVATE ${${lwv_libraries}})
```
Upstream uses a keyword, so our addition must use it, too.

2024-05-04 05:16 UTC, dg0yt commented on ports/osgearth/link-libraries.patch
> ++        endif()
```suggestion
+        endif()
```

2024-05-07 02:51 UTC, dg0yt commented on ports/osgearth/link-libraries.patch
>  +        endif()
I think this will add some libraries twice now. LIBRARIES are included in LINK_LIBRARIES if the latter is defined. This should be avoided.

2024-06-12 23:41 UTC, BillyONeal reviewed
Can you respond to dg0yt's feedback?

2024-06-12 23:41 UTC, BillyONeal commented on ports/osgearth/exampleresources.patch
> +-            bool eat = true;
Is this patch submitted upstream?

2024-07-30 19:38 UTC, closed without merging

2024-08-01 05:01 UTC, dg0yt commented
@plevy Do you want this to be completed by somebody else?