[polyhook2] Update to 2024-03-30
microsoft/vcpkg pull request #37866
Opened 2024-03-30 11:53 UTC by Summpot

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-03-30 12:30 UTC, dg0yt commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
Do we really need to remove that platform?

The x64-android error in CI was a failing patch step, i.e. *unrelated* to android. (Which is concerning.)

2024-03-30 12:43 UTC, Summpot commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
Really? But it doesn't even support linux.

2024-03-30 12:46 UTC, Summpot commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
You're right, the library author changed the name of the config file, I'm sorry I didn't notice this before.

2024-03-30 13:13 UTC, dg0yt commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
Now I see the  `!linux`. But the port builds find on linux with  `--unsupported`... The statement is more or less literal from 2020. Maybe the other toolchains lacked C++17  at that time?
I would be glad if you could remove the whole line, and let vcpkg CI finish one run, so that we can inspect the build logs.

2024-03-30 13:28 UTC, Summpot commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
I removed supports, but it seems that this library only supports x86 and x64, maybe we should use "x86 & x64"? Maybe we should use "x86 & x64"? I can't quite tell if I should use "&" or "|".

2024-04-01 23:14 UTC, BillyONeal commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
`x86 | x64` should work.

Platform expressions are an expression that must be true in order for the thing to work. `x86 & x64` is never true, since if x86, x64 must not be and vice versa.

2024-04-01 23:15 UTC, BillyONeal commented
Do we still intend to block osx?

(It's OK if the answer is yes, I just want that to be explicitly understood given the questions above)

2024-04-02 03:09 UTC, Summpot commented
It seems that the library author used to support osx, but currently it doesn't compile in osx, and there should be a lack of maintenance at the moment (maybe due to the massive drop in users of x64 osx).

2024-04-03 06:36 UTC, WangWeiLin-MV requested changes

2024-04-07 06:16 UTC, WangWeiLin-MV commented on ports/polyhook2/vcpkg.json
> +  "supports": "!(arm | uwp | linux | osx | android)",
```diff
-"supports": "!(arm | uwp | osx)",
+"supports": "(x86 | x64) & !(uwp | osx)",
```

2024-04-07 08:09 UTC, WangWeiLin-MV approved these changes
Port usage and features test pass with following triplets:
* x64-linux
* x64-windows

2024-04-09 15:26 UTC, merged