[perfetto] initial port of 43.1
microsoft/vcpkg pull request #37959
Opened 2024-04-03 20:58 UTC by rtzoeller

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2024-04-03 21:02 UTC, rtzoeller commented
@microsoft-github-policy-service agree company="ALIARO"

2024-04-04 04:48 UTC, rtzoeller commented
I've only directly tested the output on Linux x64, but I have no reason to believe it will not work in other environments.

2024-04-05 07:10 UTC, dg0yt commented
How much overlap has this port with an official (`gn`) build? 
Isn't it possible to use a shared lib on non-windows?

2024-04-05 13:42 UTC, rtzoeller commented
> How much overlap has this port with an official (gn) build?

@dg0yt one of the outputs of the official build is the pair of amalgamated source files we're consuming, which are attached to each tagged release (e.g. [for 43.0](https://github.com/google/perfetto/commit/355f5d8074c86b037bca5d0b4588e8e3e2a93cdd)).

This greatly simplifies the build process, and matches the [example built with CMake](https://github.com/google/perfetto/blob/main/examples/sdk/CMakeLists.txt).

>  Isn't it possible to use a shared lib on non-windows?

Maybe, but I've not tested it here and presumed we could enable it later if needed without breaking compatibility.

If this is a blocker for the initial port let me know and I'll happily investigate.

2024-04-05 14:58 UTC, rtzoeller commented
> Isn't it possible to use a shared lib on non-windows?

Looks like it is. I'll get a fix pushed shortly.

2024-04-05 18:51 UTC, dg0yt commented on ports/perfetto/CMakeLists.txt
> +add_library(perfetto sdk/perfetto.cc)
I think we still need
```suggestion
add_library(perfetto sdk/perfetto.cc)
target_include_directories(perfetto PUBLIC $<LINK_INTERFACE:include>)
```
~~~

2024-04-05 18:52 UTC, dg0yt commented on ports/perfetto/CMakeLists.txt
> +    NAMESPACE unofficial::
The suggested pattern is:
```suggestion
    NAMESPACE unofficial::perfetto::
```

2024-04-05 18:52 UTC, dg0yt commented on ports/perfetto/usage
> +    target_link_libraries(main PRIVATE unofficial::perfetto)
I wouldn't install a file if the heuristics output is good enough.
And for consistency, it uses a slightly different wording and formatting:
~~~
perfetto provides CMake targets:

  find_package(unofficial-perfetto CONFIG REQUIRED)
  target_link_libraries(main PRIVATE unofficial::perfetto::perfetto)
~~~

2024-04-05 19:06 UTC, rtzoeller commented on ports/perfetto/usage
> +    target_link_libraries(main PRIVATE unofficial::perfetto)
Ah, at one point it wasn't generating any output automatically for me and so I added the file manually. Looks like that was probably due to some other issue in my configuration at the time.

Thanks!

2024-04-05 19:44 UTC, rtzoeller commented on ports/perfetto/CMakeLists.txt
> +add_library(perfetto sdk/perfetto.cc)
Feedback should all be addressed.

2024-04-07 09:51 UTC, WangWeiLin-MV requested changes

2024-04-07 09:51 UTC, WangWeiLin-MV commented on ports/perfetto/CMakeLists.txt
> +)
```suggestion
# Unofficial perfetto CMakeLists.txt from https://github.com/google/perfetto/blob/v43.1/meson.build
cmake_minimum_required(VERSION 3.23)
project(perfetto LANGUAGES CXX)

add_library(perfetto)
target_compile_features(perfetto PRIVATE cxx_std_17)
target_sources(perfetto
    PRIVATE "sdk/perfetto.cc"
    PUBLIC FILE_SET HEADERS BASE_DIRS "sdk" FILES "sdk/perfetto.h"
)

set(THREADS_PREFER_PTHREAD_FLAG TRUE)
find_package(Threads REQUIRED)
target_link_libraries(perfetto PRIVATE Threads::Threads)

if(ANDROID)
    target_link_libraries(perfetto PRIVATE log)
endif(ANDROID)

if(WIN32)
    target_compile_options(perfetto PRIVATE "/bigobj")
    target_compile_definitions(perfetto PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
    target_link_libraries(perfetto PRIVATE ws2_32)
endif(WIN32)

if(MSVC)
    target_compile_options(perfetto PRIVATE "/permissive-")
endif(MSVC)

install(TARGETS perfetto
    EXPORT unofficial-perfetto-config
    FILE_SET HEADERS DESTINATION "include"
)

install(EXPORT unofficial-perfetto-config
    NAMESPACE unofficial::perfetto::
    DESTINATION "share/unofficial-perfetto"
)

install(FILES "protos/perfetto/trace/perfetto_trace.proto" DESTINATION "share/unofficial-perfetto")
```

2024-04-07 09:51 UTC, WangWeiLin-MV commented on ports/perfetto/portfile.cmake
> +    REF v43.1
```suggestion
    REF "v${VERSION}"
```

2024-04-07 09:51 UTC, WangWeiLin-MV commented on ports/perfetto/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME unofficial-${PORT})
```suggestion
vcpkg_cmake_config_fixup(PACKAGE_NAME unofficial-${PORT})

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/share"
)
```

2024-04-08 15:37 UTC, rtzoeller commented
@WangWeiLin-MV I've squashed the proposed changes into the original commit and added you as a co-author for it. This should be ready for another review.

2024-04-09 02:34 UTC, WangWeiLin-MV approved these changes, later dismissed
Port usage tests pass with following triplets:
* x64-linux
* x64-windows
* x64-windows-static
* x64-windows-static-md
* x86-windows

2024-04-09 02:34 UTC, WangWeiLin-MV commented on ports/perfetto/vcpkg.json
> +  "supports": "!uwp & !x86",
Should `x86` be excluded? The local test passed for triplet `x86-windows`.

2024-04-09 02:56 UTC, rtzoeller commented on ports/perfetto/vcpkg.json
> +  "supports": "!uwp & !x86",
> Should `x86` be excluded? The local test passed for triplet `x86-windows`.

Hmm, it had failed on an earlier version of this PR, which is why I disabled it. That may have been an unrelated failure (I don't recall the message).

I'll be available in a few hours to try re-enabling it to see if the automated PR checks pass.

UWP definitely doesn't work.

2024-04-09 04:08 UTC, rtzoeller commented on ports/perfetto/vcpkg.json
> +  "supports": "!uwp & !x86",
Seems to be passing now, so I'll leave it enabled!

2024-04-09 04:33 UTC, WangWeiLin-MV approved these changes, later dismissed

2024-04-09 18:34 UTC, JavierMatosD commented
Hi @rtzoeller,

We generally aim to use upstream's build configurations directly and only resort to providing unofficial exports when integrating with upstream would involve extensive patching or customization that doesn't seem justifiable. Could you share your rationale for opting for an unofficial CMake export instead of adapting Perfetto's existing Meson build for vcpkg? I'm not deeply familiar with Meson and its intricacies, so your insights would be very valuable to me and perhaps highlight aspects I might not be aware of.

Thanks for your contribution and looking forward to your thoughts!

2024-04-09 19:36 UTC, rtzoeller commented
Thanks for the insight @JavierMatosD.

> Could you share your rationale for opting for an unofficial CMake export instead of adapting Perfetto's existing Meson build for vcpkg?

I wasn't previously aware of any existing Meson support in Perfetto; the primary [build instructions](https://perfetto.dev/docs/contributing/build-instructions) only mention GN as a build system, although the repo also provides [an example](https://github.com/google/perfetto/tree/main/examples/sdk) of using CMake to consume the amalgamated source files.  In my usage of Perfetto I've always consumed the amalgamated SDK source files (e.g. [for v43.0](https://github.com/google/perfetto/commit/355f5d8074c86b037bca5d0b4588e8e3e2a93cdd)), and given the example CMake build this was the most approachable option.

I now see that there is a [`meson.build`](https://github.com/google/perfetto/blob/master/meson.build) file, and can take a look at consuming it.

> I'm not deeply familiar with Meson and its intricacies, so your insights would be very valuable to me and perhaps highlight aspects I might not be aware of.

I have zero familiarity with Meson, so please bear with me as I attempt to rework this PR. :smile:

2024-04-09 20:03 UTC, rtzoeller commented
At first glance the [existing Meson support](https://github.com/google/perfetto/blob/master/meson.build) appears to be rather incomplete.

AFAICT, it only supports building a static library and does not install any headers (but does include the `.proto` file). It's likely possible for us to patch `meson.build` as part of the port, but I'm unsure that's any better than the current CMake situation -- the minimal [commit history for `meson.build`](https://github.com/google/perfetto/commits/master/meson.build) and lack of documentation/examples using Meson admittedly don't inspire a ton of confidence in me.

---

@JavierMatosD can you please advise on which direction is acceptable for moving forward? Thanks!

- Continue maintaining an unofficial CMake build (i.e. merge the existing PR).
- Patch the existing Meson build system to also install `perfetto.h` to the `include` directory.
  - Optionally patch the Meson build system to support building as a dynamic library.
  - Full disclosure: I have effectively no experience with Meson other than reviewing the existing build just now.
- Move away from the amalgamated SDK builds provided by the official Perfetto releases and build the source directly with GN instead.
  - Full disclosure: I have no experience with GN.

2024-04-10 17:00 UTC, JavierMatosD commented
Big thanks for diving into the integration options! I'm initially leaning towards the unofficial CMake route because it seems super practical for now. But, I want to run it by our team to double-check we’re all on the same page for the long haul.

I’ll circle back with you as soon as we've made a decision. Really appreciate your patience and all the effort you're putting into this!

2024-04-10 18:26 UTC, dg0yt commented
This port has no dependencies. So providing an unofficial CMake config written by hand shouldn't be more difficult write by hand than a whole vendored CMake build system. If meson doesn't already provided official pkg-config files.

2024-04-12 14:32 UTC, JavierMatosD commented on ports/perfetto/CMakeLists.txt
> +set(THREADS_PREFER_PTHREAD_FLAG TRUE)
Should `PThreads` be a dependency (or feature) in the `vcpkg.json`?

2024-04-12 14:32 UTC, JavierMatosD commented on ports/perfetto/CMakeLists.txt
> +    target_compile_definitions(perfetto PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
Why are these preprocessor definitions needed? (`WIN32_LEAN_AND_MEAN`, `NOMINMAX`)

2024-04-12 14:32 UTC, JavierMatosD commented on ports/perfetto/CMakeLists.txt
> +    target_compile_options(perfetto PRIVATE "/permissive-")
Why is this needed?

2024-04-12 14:34 UTC, JavierMatosD commented
Setting the PR to draft. Please mark ready for review when you've responded. That way I will know you've responded

2024-04-12 15:29 UTC, rtzoeller commented on ports/perfetto/CMakeLists.txt
> +target_compile_features(perfetto PRIVATE cxx_std_17)
Yes, see the [v33.1 release notes](https://github.com/google/perfetto/releases/tag/v33.1).

> Switched to a C++17-only project by removing C++11 opt-out. This completes the migration started in v31.0.

2024-04-12 15:53 UTC, rtzoeller commented on ports/perfetto/CMakeLists.txt
> +    target_compile_definitions(perfetto PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX)
`NOMINMAX` is needed to prevent the definition of macros which conflict with perfetto's use of `std::min` and `std::max`.

`WIN32_LEAN_AND_MEAN` is needed to compile both `winsock.h` and `ws2def.h` successfully.

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(103): warning C4005: 'AF_IPX': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winsock.h(457): note: see previous definition of 'AF_IPX'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(147): warning C4005: 'AF_MAX': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winsock.h(476): note: see previous definition of 'AF_MAX'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(187): warning C4005: 'SO_DONTLINGER': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winsock.h(399): note: see previous definition of 'SO_DONTLINGER'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(240): error C2011: 'sockaddr': 'struct' type redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winsock.h(482): note: see declaration of 'sockaddr'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(442): error C2143: syntax error: missing '}' before 'constant'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(442): error C2059: syntax error: 'constant'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(496): error C2143: syntax error: missing ';' before '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(496): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(496): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(577): warning C4005: 'IN_CLASSA': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winsock.h(284): note: see previous definition of 'IN_CLASSA'

```

2024-04-12 16:04 UTC, rtzoeller commented on ports/perfetto/CMakeLists.txt
> +    target_compile_options(perfetto PRIVATE "/permissive-")
To be clear that turns _off_ permissive mode (note the minus), and puts MSVC into standards-compliant mode.

I wasn't able to get it to fail without this flag as part of the automated build, but my recollection from previous usage is that it's needed for older MSVC versions  (2017?). 

It's in the [recommended set of flags](https://perfetto.dev/docs/instrumentation/tracing-sdk) for using the tracing compiler:

```cmake
# Enable standards-compliant mode when using the Visual Studio compiler.
if (MSVC)
  target_compile_options(example PRIVATE "/permissive-")
endif (MSVC)
```

2024-04-12 16:14 UTC, rtzoeller commented on ports/perfetto/CMakeLists.txt
> +find_package(Threads REQUIRED)
I'm unsure what you mean here aside from what's asked in the other comment.

> Should PThreads be a dependency (or feature) in the vcpkg.json?

2024-04-12 16:14 UTC, rtzoeller commented on ports/perfetto/CMakeLists.txt
> +set(THREADS_PREFER_PTHREAD_FLAG TRUE)
Seems like it, yes. I'll add it.

2024-04-15 02:43 UTC, WangWeiLin-MV commented on ports/perfetto/CMakeLists.txt
> +find_package(Threads REQUIRED)
The lib `pthread` is a system library, it just requires the `find_package`, and it will only be used on NON-WINDOWS. The checks in upstream https://github.com/google/perfetto/blob/v43.1/include/perfetto/ext/base/thread_checker.h#L22-L24.

2024-04-15 17:19 UTC, JavierMatosD commented on ports/perfetto/CMakeLists.txt
> +    target_compile_options(perfetto PRIVATE "/permissive-")
If it's not strictly required we should remove this. Thanks for the explanation!

2024-04-15 17:19 UTC, JavierMatosD commented on ports/perfetto/vcpkg.json
> +    "pthreads",
```suggestion
    {
         "name"" "pthreads",
         "platform": "!windows"
    },
```

2024-04-15 18:01 UTC, dg0yt commented on ports/perfetto/vcpkg.json
> +    "pthreads",
@JavierMatosD Are you serious about this? Almost no port does this, but almost every non-trivial port uses pthreads.

2024-04-15 18:30 UTC, JavierMatosD commented on ports/perfetto/vcpkg.json
> +    "pthreads",
Serious about what exactly? Adding the platform expression or adding it as a dependency?

2024-04-15 19:29 UTC, dg0yt commented on ports/perfetto/vcpkg.json
> +    "pthreads",
Do we really request a `pthreads` dependency on platforms where the port is empty and where most ports don't use the dependency and where depending ports don't need to be rebuilt when the windows-only implementation is updated?

2024-04-15 19:35 UTC, merged