[google-cloud-cpp] update to the latest release (v2.23)
microsoft/vcpkg pull request #38204
Opened 2024-04-15 23:14 UTC by alevenberg

Updates google-cloud-cpp to the latest release (v2.23.0)

Removed `DGOOGLE_CLOUD_CPP_ENABLE_CTYPE_CORD_WORKAROUND` since it is no longer used because it is automatically set now (https://github.com/googleapis/google-cloud-cpp/pull/13877).

Tested locally (on x64-linux) with:

```
 for feature in "cloudcontrolspartner" "storagecontrol" "apphub" "backupdr"; do ./vcpkg remove google-cloud-cpp; ./vcpkg install "google-cloud-cpp[core,${feature}]" || break; done
```

and

```
./vcpkg remove google-cloud-cpp && ./vcpkg install 'google-cloud-cpp[*]'
```

-  [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-04-15 23:22 UTC, dbolduc commented on ports/google-cloud-cpp/vcpkg.json
> +        "crc32c",
idts

2024-04-15 23:36 UTC, alevenberg commented on ports/google-cloud-cpp/vcpkg.json
> +        "crc32c",
Fixed

2024-04-15 23:44 UTC, dbolduc commented
I am not sure what the build failure is. Does running the following make any changes? If so, try committing them.

```
./vcpkg x-add-version google-cloud-cpp --overwrite-version
```

2024-04-16 13:50 UTC, alevenberg commented
> I am not sure what the build failure is. Does running the following make any changes? If so, try committing them.
> 
> ```
> ./vcpkg x-add-version google-cloud-cpp --overwrite-version
> ```

Fixed it thanks.

2024-04-16 14:09 UTC, dbolduc approved these changes

2024-04-22 16:25 UTC, teo-tsirpanis requested changes

2024-04-22 16:25 UTC, teo-tsirpanis commented on ports/google-cloud-cpp/vcpkg.json
OpenSSL is no longer a dependency on Windows (googleapis/google-cloud-cpp#13785).

2024-04-24 00:22 UTC, alevenberg commented
> @alevenberg you need to run `./vcpkg x-add-version google-cloud-cpp --overwrite-version` again and push a commit.

Thanks. Done.

2024-04-24 08:38 UTC, teo-tsirpanis approved these changes

2024-04-24 10:00 UTC, WangWeiLin-MV approved these changes
Port usage tests pass with following triplets:
* x64-windows

2024-04-24 12:52 UTC, merged