[folly] update to 2024.04.15
microsoft/vcpkg pull request #38279
Opened 2024-04-20 07:52 UTC by c8ef

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-04-23 02:48 UTC, c8ef commented
Hello reviewers, does the PR look good to you? If it does, could you please approve it? Thank you! @WangWeiLin-MV

2024-04-23 04:06 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++  endif()
I see this pattern exists everywhere here already. But I notice it now, and IMO it is not good.
`CMAKE_DISABLE_FIND_PACKAGE_unofficial-sodium` already has an effect on `find_package`. It doesn't need to be in in `if` guard. Even worse, it has an effect on transitive dependencies.
And `find_package` doesn't have `REQUIRED`, so the requested feature might be missing in the end.
And the success of `find_package` should be checked with `<Pkg>_FOUND` (if not `REQUIRED`).

The pattern I would suggest is
```diff
+if(WITH_sodium)
+  find_package(unofficial-sodium CONFIG REQUIRED)
+  list(APPEND FOLLY_LINK_LIBRARIES unofficial-sodium::sodium)
+endif()
```
and addding the variable `WITH_sodium` to `vcpkg_check_feature(... OPTIONS ...)` in the portfile, instead of `CMAKE_DISABLE_FIND_PACKAGE_unofficial-sodium`.

Similar for the other occurences of the pattern. And a review of the exported CMake config for the variables which control `find_dependency`.

2024-04-23 04:22 UTC, c8ef commented on ports/folly/fix-deps.patch
> ++  endif()
I agree with you, but implementing this change will further increase the size of the already large pull request. Perhaps we could maintain the old approach for historical features and address this through a separate refactoring pull request.

2024-04-23 04:28 UTC, c8ef commented on ports/folly/fix-deps.patch
> ++  endif()
```
    FEATURES
        "zlib"       CMAKE_REQUIRE_FIND_PACKAGE_ZLIB
        "liburing"   WITH_liburing
        "libaio"     WITH_libaio
```

The feature flag naming is also inconsistent; we can address this in another pull request with the above concern.

2024-04-23 04:29 UTC, dg0yt commented on ports/folly/fix-deps.patch
> ++  endif()
Okay.

2024-04-24 05:21 UTC, c8ef commented
Ping. @WangWeiLin-MV

2024-04-24 09:00 UTC, WangWeiLin-MV requested changes

2024-04-24 09:18 UTC, c8ef commented on ports/mvfst/vcpkg.json
Done.

2024-04-24 10:02 UTC, WangWeiLin-MV reviewed
Ports `folly`,`fizz`,`wangle`,`proxygen`,`mvfst`,`fbthrift` install pass with following triplets:
* x64-linux

2024-04-24 10:11 UTC, WangWeiLin-MV approved these changes

2024-04-24 10:12 UTC, WangWeiLin-MV commented
The `cachelib` installs failed with last link command, I will try again.

2024-04-24 10:14 UTC, c8ef commented
Thank you for your prompt response! The cachelib link error may be related to missing system packages. You may need to install the `libaio1` and `libaio-dev` packages.

2024-04-24 10:25 UTC, WangWeiLin-MV commented
> Thank you for your prompt response! The cachelib link error may be related to missing system packages. You may need to install the `libaio1` and `libaio-dev` packages on debian based distros.

My previous test environment was Debian `libaio-dev/stable,now 0.3.113-4 amd64`, which may be affected by differences with Ubuntu `libaio-dev/mantic,now 0.3.113-5 amd64`.

2024-04-24 10:32 UTC, c8ef commented
This is actually strange because libaio has not been updated for 2 years: https://pagure.io/libaio/commits/master

The current hot spot seems to be liburing. Therefore, there should not be any breaking changes between these two package versions.

2024-04-25 10:21 UTC, WangWeiLin-MV approved these changes
Ports `folly`,`fizz`,`wangle`,`proxygen`,`mvfst`,`fbthrift`,`cachelib` installation test pass under `ubuntu:mantic-20240405` with following triplets:
* x64-linux

2024-04-25 13:17 UTC, merged