[onnxruntim-cuda12] new port
microsoft/vcpkg pull request #38275
Opened 2024-04-19 19:10 UTC by vipcxj

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

There is already a port named onnxruntime-gpu. But it use cuda 11. And cuda 11 is still the default cuda version of onnxruntime-gpu. This port introduce the onnxruntime-gpu with cuda 12.

2024-04-20 11:14 UTC, vipcxj commented
I'd like to upgrade onnxruntime-gpu if needed, but the cuda I'm currently using is all 12, and having multiple versions of cuda on one machine could cause quite a few problems!

2024-04-28 01:51 UTC, vipcxj commented
@FrankXie05 Any news?

2024-04-28 09:21 UTC, FrankXie05 approved these changes

2024-04-29 01:58 UTC, FrankXie05 commented
All features and usage have been tested successfully on `x64-windows`.

2024-04-30 00:08 UTC, data-queue commented
I understand why you are trying to make this change, but this should be an overlay port or in a custom registry for now. I think the port should use the default version of CUDA recommended by upstream. There is cost for maintaining multiple versions of a port (`opencv2`, `opencv3`, `opencv4`), and we shouldn't really be doing that in general.

2024-05-02 04:44 UTC, JoergAtGithub commented
There is also #36850 which uses port features for the different execution providers.

2024-05-02 10:47 UTC, vipcxj commented
> There is also #36850 which uses port features for the different execution providers.

There's no telling when this pr will be merged at all I guess, this pr is compiled with the source code to replace the current direct download version, it looks like it's going to be a long work in progress.

2024-05-02 10:49 UTC, vipcxj commented
> I understand why you are trying to make this change, but this should be an overlay port or in a custom registry for now. I think the port should use the default version of CUDA recommended by upstream. There is cost for maintaining multiple versions of a port (`opencv2`, `opencv3`, `opencv4`), and we shouldn't really be doing that in general.

Like @JoergAtGithub mentioned, if that pr is finished, I won't need further maintenance on this port, but isn't he currently not finished? I don't know when it will be finished either.

2024-05-02 19:55 UTC, BillyONeal requested changes
This port conflicts with an existing port:

```
error: The following files are already installed in D:/vcpkg/installed/x64-windows and are in conflict with onnxruntime-gpu:x64-windows
Installed by onnxruntime-cuda12:x64-windows
bin/onnxruntime.dll
    bin/onnxruntime.pdb
    bin/onnxruntime_providers_cuda.dll
    bin/onnxruntime_providers_cuda.pdb
    bin/onnxruntime_providers_shared.dll
    bin/onnxruntime_providers_shared.pdb
    bin/onnxruntime_providers_tensorrt.dll
    bin/onnxruntime_providers_tensorrt.pdb
    debug/bin/onnxruntime.dll
    debug/bin/onnxruntime.pdb
    debug/bin/onnxruntime_providers_cuda.dll
    debug/bin/onnxruntime_providers_cuda.pdb
    debug/bin/onnxruntime_providers_shared.dll
    debug/bin/onnxruntime_providers_shared.pdb
    debug/bin/onnxruntime_providers_tensorrt.dll
    debug/bin/onnxruntime_providers_tensorrt.pdb
    debug/lib/onnxruntime.lib
    debug/lib/onnxruntime_providers_cuda.lib
    debug/lib/onnxruntime_providers_shared.lib
    debug/lib/onnxruntime_providers_tensorrt.lib
    lib/onnxruntime.lib
    lib/onnxruntime_providers_cuda.lib
    lib/onnxruntime_providers_shared.lib
    lib/onnxruntime_providers_tensorrt.lib
```

2024-05-03 09:37 UTC, vipcxj commented
@BillyONeal It will definitely conflict with onnxruntime-gpu because this port is the onnxruntime which using the cuda12, using the same dll or so with onnxruntime-gpu, do you have any suggestions for modifications? In fact if a future compiled version of onnxruntime is merged, it's bound to conflict with onnxruntime-gpu as well. Normally you wouldn't install more than one version of onnxruntime at the same time, because even if you avoid the conflict by modifying the name of the dll or so, all the functions are still the same and still in conflict, you can't link different versions of onnxruntime at the same time!

2024-05-06 22:16 UTC, data-queue commented
There's an open question on how to represent `onnxruntime` and its providers in a vcpkg port:
1. Creating a port for each `onnxruntime` provider and version would be too expensive to maintain long term for vcpkg.
2. Having features to represent each provider (features as alternatives) would go against our model of how features work.

Some potential options to improve the situation:
1. Add documentation in the port to recommend users to create an overlay port or maintain this in a custom registry.
2. Change the default installation for each platform.
3. Maybe there are other ideas?

Longer term, we may revisit our features as alternatives policy to account for scenarios like this.

2024-05-07 03:44 UTC, vipcxj commented
> There's an open question on how to represent `onnxruntime` and its providers in a vcpkg port:
> 
> 1. Creating a port for each `onnxruntime` provider and version would be too expensive to maintain long term for vcpkg.
> 2. Having features to represent each provider (features as alternatives) would go against our model of how features work.
> 
> Some potential options to improve the situation:
> 
> 1. Add documentation in the port to recommend users to create an overlay port or maintain this in a custom registry.
> 2. Change the default installation for each platform.
> 3. Maybe there are other ideas?
> 
> Longer term, we may revisit our features as alternatives policy to account for scenarios like this.

Creating an overlay port is not a option. You can't expect everyone to know how to write portfile, even if it's just downloading a precompiled link library that doesn't involve compilation. And in order for cmake to find it, users need to have a deep understanding of the mechanics of cmake as well. Isn't open source about not building the wheel over and over again?

2024-05-08 20:59 UTC, data-queue commented
Hi @vipcxj unfortunately, we can't accept this port into the main catalog until we figure out a better solution for our features as alternatives policy. There are changes in this PR, such as the CMake config changes, that we can accept into the `onnxruntime-gpu` port if you are interested in making that PR.

2024-06-10 22:13 UTC, BillyONeal commented
> Creating an overlay port is not a option. You can't expect everyone to know how to write portfile, even if it's just downloading a precompiled link library that doesn't involve compilation. And in order for cmake to find it, users need to have a deep understanding of the mechanics of cmake as well. Isn't open source about not building the wheel over and over again?

I'm sorry that there was some confusion over this. You can write instructions in the 'onnxruntime' port that says 'to get the CUDA12 one, copy this as an overlay port and make these changes'. We are not going to be able to accept ports like this that conflict with each other for the foreseeable future. Before registries were a feature, we accepted some alternatives, such as `boringssl`, into the registry. However, now that registries are a feature, we have refrained from accepting anything else like this as being in the curated registry is a statement that we have tested the component together with other parts of the curated registry, which we are unable to do in these alternatives cases.

See also https://learn.microsoft.com/vcpkg/contributing/maintainer-guide#unique-port-attribution-rule

2025-10-14 16:59 UTC, YuHuanTin commented
I have to spit out that I'm really kind of sad that vcpkg is so poorly configured for package optionality that the same package has gone through a lot of effort just to change from cuda11 to cuda12 :(

2025-10-20 17:34 UTC, BillyONeal commented
> I have to spit out that I'm really kind of sad that vcpkg is so poorly configured for package optionality that the same package has gone through a lot of effort just to change from cuda11 to cuda12 :(

This isn't trying to *change* the CUDA version, it's trying to add a new / completely different port that takes all of the same binary, header, and symbol names. One thing we're "selling" is that you can use what is in our curated registry together, and we can't do that if we ingest mutually incompatible ports. Testing the `2^N` potential combinations would not be practical.

Replacing the existing `onnxruntime` ports with ones that use cuda12 instead would be entirely fine.

2025-10-21 01:45 UTC, YuHuanTin commented
> > I have to spit out that I'm really kind of sad that vcpkg is so poorly configured for package optionality that the same package has gone through a lot of effort just to change from cuda11 to cuda12 :(
> 
> This isn't trying to _change_ the CUDA version, it's trying to add a new / completely different port that takes all of the same binary, header, and symbol names. One thing we're "selling" is that you can use what is in our curated registry together, and we can't do that if we ingest mutually incompatible ports. Testing the `2^N` potential combinations would not be practical.
> 
> Replacing the existing `onnxruntime` ports with ones that use cuda12 instead would be entirely fine.

Thank you for your patience!But I am worried that people who need to use cuda11 will not be able to use the latest version of onnxrunime. Although they can use the version of git control port...it is very troublesome. 🤣

2025-10-24 19:31 UTC, BillyONeal commented
> Thank you for your patience!But I am worried that people who need to use cuda11 will not be able to use the latest version of onnxrunime. Although they can use the version of git control port...it is very troublesome. 🤣

That is why we have overlay ports and similar mechanisms for users to control things. What we are selling with the curated registry is that we promise everything supported on one of the non-community triplets are mutually compatible by actually testing that they work together. If they aren't mutually compatible, we have to choose one, lest we effectively break the registry into `2^number_of_mutations` possible registries that we could not practically test.

2026-05-13 21:04 UTC, vicroms commented
We have [closed this PR due to inactivity](https://learn.microsoft.com/vcpkg/contributing/maintainer-guide#close-inactive-prs). Please create a new PR if you're still interested in getting these changes merged.

2026-05-13 21:04 UTC, closed without merging