[vcpkg-cmake] get more logs
microsoft/vcpkg pull request #38409
Opened 2024-04-25 05:28 UTC by Neumann-A

2024-04-25 05:41 UTC, dg0yt requested changes
`CMakeConfigureLog.yaml` is great.

Note that another change to this port is pending in #38249.

2024-04-25 05:41 UTC, dg0yt commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +            "../../${TARGET_TRIPLET}-dbg/build.ninja" ALIAS "dbg-ninaja.log"
```suggestion
            "../build.ninja" ALIAS "rel-ninja.log"
            "../../${TARGET_TRIPLET}-dbg/build.ninja" ALIAS "dbg-ninja.log"
```
but I'm not sure if they are so useful.

2024-04-25 05:42 UTC, dg0yt commented
And IIUC all these logs become part of the GH issues.

2024-04-25 06:06 UTC, Neumann-A commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +            "../../${TARGET_TRIPLET}-dbg/build.ninja" ALIAS "dbg-ninaja.log"
Useful for e.g. debugging link issues where the install logs just shows the response file being used.

2024-04-25 07:35 UTC, dg0yt commented on ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
> +            "../../${TARGET_TRIPLET}-dbg/build.ninja" ALIAS "dbg-ninaja.log"
I understand the problem with the response files, but does the ninja file at more information? (Dependencies, of course, but content?)

2024-04-25 07:36 UTC, dg0yt commented
meson and gn use ninja, too. At which point will "build with ninja" be generalized?

2024-04-26 16:17 UTC, Neumann-A commented
```
REGRESSION: openmvs:x64-windows-static failed with BUILD_FAILED. If expected, add openmvs:x64-windows-static=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: rtabmap:x64-windows-static failed with BUILD_FAILED. If expected, add rtabmap:x64-windows-static=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
```

are baseline due to the removal of CBLAS_LIBRARIES from the lapack-wrapper is fixed in the VTK PR

2024-04-30 07:51 UTC, Neumann-A commented
I wouldn't mind `SAVE_LOG_FILES` to be exposed to the caller somehow. Maybe some `Z_VCPKG_` variable would make sense here? The main use is debugging especially for the `build.ninja` file.

2024-05-28 06:20 UTC, FrankXie05 approved these changes

2024-06-14 18:34 UTC, merged

2024-06-14 18:34 UTC, BillyONeal commented
Thanks for the logs!