[libharu] Fix x64-linux-dynamic
microsoft/vcpkg pull request #38551
Opened 2024-05-03 14:59 UTC by bansan85

Fixes #32493

Without this fix, vtk doesn't compile.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2024-05-03 15:13 UTC, dg0yt requested changes

2024-05-03 15:13 UTC, dg0yt commented on ports/libharu/portfile.cmake
> +if(WIN32)
```suggestion
if(VCPKG_TARGET_IS_WINDOWS)
```

2024-05-07 06:16 UTC, MonicaLiu0311 approved these changes

2024-05-08 03:40 UTC, data-queue approved these changes

2024-05-08 03:41 UTC, merged