[Breakpad] Add windows tools
microsoft/vcpkg pull request #38671
Opened 2024-05-10 11:14 UTC by RealChuan

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-05-11 06:09 UTC, jimwang118 commented
Testing under local Windows did not generate dump_syms, sym_upload, google_converter.

2024-05-11 06:48 UTC, RealChuan commented
> Testing under local Windows did not generate dump_syms, sym_upload, google_converter.

Use vcpkg install breakpad[tools] - triplet x64-windows?

2024-05-11 06:56 UTC, jimwang118 commented
> > Testing under local Windows did not generate dump_syms, sym_upload, google_converter.
> 
> Use vcpkg install breakpad[tools] - triplet x64-windows?

I'm very sorry, it's my fault that I didn't add the feature during the test. Retested and passed.

2024-05-11 06:57 UTC, jimwang118 commented
Compile test pass with following triplets:
```
x64-windows
```

2024-05-14 05:57 UTC, dg0yt commented on ports/breakpad/CMakeLists.txt
> +        set(CMAKE_GENERATOR_PLATFORM ${VCPKG_TARGET_ARCHITECTURE})
Isn't it initialized correctly?  
"The value of this variable should never be modified by project code."  
https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_PLATFORM.html

2024-05-14 11:14 UTC, RealChuan commented
Test https://github.com/RealChuan/vcpkg/actions/runs/9078244060

2024-05-16 20:01 UTC, data-queue requested changes

2024-05-16 20:01 UTC, data-queue commented on ports/breakpad/FindDiaSDK.cmake
> +  COMMAND "$ENV{${PROGRAMFILES_X86}}/Microsoft Visual Studio/Installer/vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
@BillyONeal pointed out that this command may choose a DIA SDK instance not related to the compiler used

2024-05-17 01:24 UTC, closed without merging