[cinatra, cmdline] Add new ports
microsoft/vcpkg pull request #38712
Opened 2024-05-13 13:06 UTC by EmployeeNo427

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-05-15 10:49 UTC, Cheney-W commented
This port has the following issues:
1. Its dependencies are not being used at all, as there is no related code in the source's CMakeLists.txt.
2. The headers provided by the source contain many calls to headers in the same or lower-level directories. If these calls are to use files from those dependencies, the current file structure does not match.
3. You have used some deprecated functions, and vcpkg's policy is not to build examples.

2024-05-16 06:02 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +vcpkg_install_cmake()
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_UNIT_TESTS=OFF
        -DBUILD_EXAMPLES=OFF
        -DBUILD_PRESS_TOOL=ON
)

vcpkg_cmake_install()

```

2024-05-16 06:03 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +
```suggestion

set(VCPKG_BUILD_TYPE "release") # header-only port

```

2024-05-16 06:04 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +
```suggestion
```

2024-05-16 06:06 UTC, Cheney-W commented on ports/cinatra/vcpkg.json
> +  "license": "MIT"
```suggestion
  "license": "MIT",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    }
  ]
```

2024-05-16 06:08 UTC, Cheney-W commented on ports/cinatra/vcpkg.json
> +  "version-date": "2024-05-15",
```suggestion
  "version": "0.9.1",
```

2024-05-16 06:11 UTC, Cheney-W commented on scripts/ci.baseline.txt
> +
```suggestion
```
If this port does not support Android and UWP, you can add `"supports": "!uwp & !android"` on the line following the `license` statement in `vcpkg.json`.

2024-05-16 06:25 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +file(REMOVE_RECURSE "${SOURCE_PATH}/.git")
```suggestion
```

2024-05-16 06:26 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +endif()
Only the copy of `cinatra_press_tool.exe` needs to be retained here.

2024-05-16 08:29 UTC, EmployeeNo427 commented
@Cheney-W Thank you very much for the detailed feedback! I have applied all the suggestions.

2024-05-17 08:36 UTC, Cheney-W commented
0.9.1 is declared with ce7e7fba41dc0718831bc3ce20644051f46a6878, but the local port has a different SHA 91af211a6a62396620de86d320f075490e0ea302.
Please update the port's version fields and then run:
vcpkg x-add-version cinatra
git add versions
git commit -m "Update version database"
to add the new version.
To attempt to resolve all errors at once, run:
vcpkg x-add-version --all

2024-05-17 09:49 UTC, EmployeeNo427 commented
> 0.9.1 is declared with ce7e7fba41dc0718831bc3ce20644051f46a6878, but the local port has a different SHA 91af211a6a62396620de86d320f075490e0ea302. Please update the port's version fields and then run: vcpkg x-add-version cinatra git add versions git commit -m "Update version database" to add the new version. To attempt to resolve all errors at once, run: vcpkg x-add-version --all

Thank you for the feedback. I tried to do something like that, but I encountered an error:
```
PS D:\opensourcework\vcpkgstuff\vcpkg> git add ports/cinatra
PS D:\opensourcework\vcpkgstuff\vcpkg> git commit -m "Update cinatra/portfile.cmake and cinatra/vcpkg.json to include dependencies as part of the cinatra installation"
[add-cinatra-port fca3554da] Update cinatra/portfile.cmake and cinatra/vcpkg.json to include dependencies as part of the cinatra installation
 2 files changed, 5 insertions(+), 25 deletions(-)
PS D:\opensourcework\vcpkgstuff\vcpkg> git push -u origin add-cinatra-port
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 618 bytes | 618.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/EmployeeNo427/vcpkg.git
   2fdf2e5ed..fca3554da  add-cinatra-port -> add-cinatra-port
branch 'add-cinatra-port' set up to track 'origin/add-cinatra-port'.
PS D:\opensourcework\vcpkgstuff\vcpkg> vcpkg x-add-version cinatra
error: cinatra is not properly formatted
Run `vcpkg format-manifest "D:\opensourcework\vcpkgstuff\vcpkg\ports\cinatra\vcpkg.json"` to format the file
Don't forget to commit the result!

PS D:\opensourcework\vcpkgstuff\vcpkg> vcpkg format-manifest "D:\opensourcework\vcpkgstuff\vcpkg\ports\cinatra\vcpkg.json
>> ^C
PS D:\opensourcework\vcpkgstuff\vcpkg> vcpkg format-manifest "D:\opensourcework\vcpkgstuff\vcpkg\ports\cinatra\vcpkg.json"
Succeeded in formatting the manifest files.
PS D:\opensourcework\vcpkgstuff\vcpkg> vcpkg x-add-version cinatra
warning: there are uncommitted changes for cinatra
error: checked-in files for cinatra have changed but the version was not updated
version: 0.9.1
old SHA: ce7e7fba41dc0718831bc3ce20644051f46a6878
new SHA: b6989160d51c1b9ce67e472c1b2de2ae15d5f9c9
Did you remember to update the version or port version?
Use --overwrite-version to bypass this check
***No files were updated***
PS D:\opensourcework\vcpkgstuff\vcpkg> vcpkg format-manifest "D:\opensourcework\vcpkgstuff\vcpkg\ports\cinatra\vcpkg.json"
Succeeded in formatting the manifest files.
PS D:\opensourcework\vcpkgstuff\vcpkg> vcpkg x-add-version cinatra
warning: there are uncommitted changes for cinatra
error: checked-in files for cinatra have changed but the version was not updated
version: 0.9.1
old SHA: ce7e7fba41dc0718831bc3ce20644051f46a6878
new SHA: b6989160d51c1b9ce67e472c1b2de2ae15d5f9c9
Did you remember to update the version or port version?
Use --overwrite-version to bypass this check
***No files were updated***
PS D:\opensourcework\vcpkgstuff\vcpkg>
```

2024-05-17 10:02 UTC, EmployeeNo427 commented
> 0.9.1 is declared with ce7e7fba41dc0718831bc3ce20644051f46a6878, but the local port has a different SHA 91af211a6a62396620de86d320f075490e0ea302. Please update the port's version fields and then run: vcpkg x-add-version cinatra git add versions git commit -m "Update version database" to add the new version. To attempt to resolve all errors at once, run: vcpkg x-add-version --all

@Cheney-W Thanks! For clarification, I need to **manually** change "\vcpkg\versions\c-\cinatra.json" from:
```
{
  "versions": [
    {
      "git-tree": "f14ed90b0ac73f6a970d7688329dfbabe7b08a58",
      "version-date": "2024-05-15",
      "port-version": 0
    },
    {
      "git-tree": "ce7e7fba41dc0718831bc3ce20644051f46a6878",
      "version": "0.9.1",
      "port-version": 0
    }
  ]
}
```
to:
```
{
  "versions": [
    {
      "git-tree": "f14ed90b0ac73f6a970d7688329dfbabe7b08a58",
      "version-date": "2024-05-15",
      "port-version": 0
    },
    {
      "git-tree": "91af211a6a62396620de86d320f075490e0ea302",
      "version": "0.9.1",
      "port-version": 0
    }
  ]
}
```
And then run the commands?

2024-05-17 10:19 UTC, Cheney-W commented
There should be only one record in the `\vcpkg\versions\c-\cinatra.json` file.
When you do any change in the cinatra port and submit a commit, you should run below commands:
```
.\vcpkg x-add-version cinatra --overwrite-version
git add .
git commit --amend --no-edit
git push
```
Also, I noticed that `cinatra_press_tool.exe` is stored in `${CURRENT_PACKAGES_DIR}/include`, so you won't find it under `${CURRENT_PACKAGES_DIR}/bin`.

2024-05-20 09:26 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +         DESTINATION "${CURRENT_PACKAGES_DIR}/tools/cinatra")
Please remove the `include/cinatra_press_tool.exe` when it is copied to `tools/cinatra`.

2024-05-20 10:09 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +file(COPY ${SOURCE_PATH}/include DESTINATION ${CURRENT_PACKAGES_DIR})
The current header file storage structure may cause conflicts with header files from other ports. Therefore, I suggest moving all the contents under the include directory to `${CURRENT_PACKAGES_DIR}/include/cinatra` instead of `${CURRENT_PACKAGES_DIR}/include/`.

2024-05-20 10:27 UTC, EmployeeNo427 commented on ports/cinatra/portfile.cmake
> +file(COPY ${SOURCE_PATH}/include DESTINATION ${CURRENT_PACKAGES_DIR})
Thank you very much!

2024-05-20 15:55 UTC, dg0yt reviewed
vcpkg has asio, boost-asio, and async-simple. Shouldn't this port use the corresponding vcpkg ports instead of vendored copies?

2024-05-21 05:48 UTC, EmployeeNo427 commented on ports/cinatra/portfile.cmake
> +         DESTINATION "${CURRENT_PACKAGES_DIR}/tools/cinatra")
Thanks!

2024-05-21 06:03 UTC, EmployeeNo427 commented
> vcpkg has asio, boost-asio, and async-simple. Shouldn't this port use the corresponding vcpkg ports instead of vendored copies?

Thank you for the suggestion! I initially tried to incorporate the vcpkg ports for dependencies, but it seems to require reconfiguring the library.

https://github.com/microsoft/vcpkg/pull/38712#issuecomment-2112180645

2024-05-21 06:46 UTC, dg0yt commented
> I initially tried to incorporate the vcpkg ports for dependencies, but it seems to require reconfiguring the library.

This might be a necessary task for integrating it into vcpkg, so that downstream apps don't end up with different definitions of the same functions.

2024-05-21 06:49 UTC, dg0yt commented on ports/cinatra/portfile.cmake
> +    DESTINATION "${CURRENT_PACKAGES_DIR}/tools/cinatra"
```suggestion
```
This is the default.

2024-05-21 06:49 UTC, dg0yt commented on ports/cinatra/portfile.cmake
> +# Copy executables to the tools directory using vcpkg_copy_tools
```suggestion
```
`vcpkg_copy_tools` is expressive enough.

2024-05-21 06:51 UTC, dg0yt commented
What does  `cinatra_press_tool` do? 
It is unexpected for a "header-only" port to install tools, and it is unexpected that it installs to `include`.

2024-05-21 06:55 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +    DESTINATION "${CURRENT_PACKAGES_DIR}/tools/cinatra"
The `AUTO_CLEAN` of `vcpkg_copy_tools` can only delete the tool under `${CURRENT_PACKAGES_DIR}/bin`, so `${CURRENT_PACKAGES_DIR}/include/cinatra_press_tool.exe` still needs to be deleted manually here.

2024-05-21 07:38 UTC, EmployeeNo427 commented
There are some build errors I encountered with vcpkg_copy_tools; it is referring to the bin folder.

2024-05-21 08:53 UTC, EmployeeNo427 commented
@Cheney-W and @dg0yt

Thank you for your feedback and suggestions! I have reverted to using a combination of `vcpkg_copy_tools` and manually removing `cinatra_press_tool.exe` from the `include` directory to handle the tool. However, from looking at the GitHub checks, it is still referring to the `bin` folder for some reason and encountering build errors.

Additionally, I noticed there are ongoing discussions about the proper handling and integration of dependencies. Could you please provide guidance on the following points?

1. Is the current approach of using `vcpkg_copy_tools` combined with the manual removal of `cinatra_press_tool.exe` acceptable, or is there a better method you would recommend?
2. What is the best way to handle the integration of dependencies to ensure compatibility and avoid issues with downstream applications? Previously, I updated `cinatra/portfile.cmake` and `cinatra/vcpkg.json` to include dependencies as part of the cinatra installation instead of through vcpkg, due to how cinatra itself is structured, as @Cheney-W mentioned:
    ```
    Its dependencies are not being used at all, as there is no related code in the source's CMakeLists.txt.
    The headers provided by the source contain many calls to headers in the same or lower-level directories. If these calls are to use files from those dependencies, the current file structure does not match.
    ```

Again, thank you very much for your assistance on these matters!

2025-01-13 08:37 UTC, Cheney-W requested changes

2025-01-13 08:37 UTC, Cheney-W commented on ports/cinatra/vcpkg.json
> +  ]
```suggestion
  "supports": "!uwp & !android"
```

2025-01-13 08:37 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +
```suggestion
```

2025-01-13 08:37 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +file(COPY ${SOURCE_PATH}/include DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```suggestion
file(COPY "${SOURCE_PATH}/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(RENAME "${CURRENT_PACKAGES_DIR}/include/include" "${CURRENT_PACKAGES_DIR}/include/cinatra")
```

2025-01-13 08:37 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +
```suggestion
```

2025-01-13 08:37 UTC, Cheney-W commented on ports/tanakh-cmdline/portfile.cmake
> +     DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```suggestion
file(INSTALL "${SOURCE_PATH}/cmdline.h"
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/tanakh-cmdline"
```

2025-01-16 18:27 UTC, EmployeeNo427 commented on ports/tanakh-cmdline/portfile.cmake
> +     DESTINATION ${CURRENT_PACKAGES_DIR}/include)
Thank you for taking the time to review! Some of these changes may have caused the CI build to fail, but I am not sure why. Could you help me pinpoint the issues and advise me on how to proceed?

2025-05-15 08:07 UTC, EmployeeNo427 commented
Hi @Cheney-W, thank you for your previous review!
Are there any remaining changes needed? I noticed there's one requested change, but I couldn't find any specific details about it.

2025-05-15 09:17 UTC, Cheney-W approved these changes

2025-05-16 15:13 UTC, JavierMatosD submitted a review, later dismissed

2025-05-16 15:13 UTC, JavierMatosD commented on ports/cinatra/portfile.cmake
> +vcpkg_from_github(
```suggestion
set(VCPKG_BUILD_TYPE "release") # header-only port
vcpkg_from_github(
```

2025-05-16 15:13 UTC, JavierMatosD commented on ports/tanakh-cmdline/portfile.cmake
> +vcpkg_from_github(
```suggestion
set(VCPKG_BUILD_TYPE "release") # header-only port
vcpkg_from_github(
```

2025-05-19 06:00 UTC, Cheney-W approved these changes

2025-05-19 07:33 UTC, dg0yt reviewed
The include dir still needs devendoring:
IIUC there are copies of tanakh-cmdline and of boost-asio.

2025-05-19 07:33 UTC, dg0yt commented on ports/cinatra/portfile.cmake
> +file(RENAME "${CURRENT_PACKAGES_DIR}/include/include" "${CURRENT_PACKAGES_DIR}/include/cinatra")
```suggestion
file(COPY "${SOURCE_PATH}/include/" DESTINATION "${CURRENT_PACKAGES_DIR}/include/cinatra")
```

2025-05-19 07:33 UTC, dg0yt commented on ports/cinatra/portfile.cmake
> +)
```suggestion
# Install the license file(s)
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2025-05-21 07:35 UTC, Cheney-W commented on ports/cinatra/portfile.cmake
> +)
```suggestion
file(INSTALL
    "${SOURCE_PATH}/include/cinatra"
    "${SOURCE_PATH}/include/cinatra.hpp"
    DESTINATION "${CURRENT_PACKAGES_DIR}/include"
)
```
The original command generates the following structure:
```
include/cinatra.hpp
include/cinatra/cinatra/xxx
```
This causes an error in `cinatra.hpp` for the line `#include "cinatra/coro_http_client.hpp"`.

2025-05-26 01:55 UTC, Cheney-W approved these changes

2025-05-27 05:34 UTC, vicroms approved these changes

2025-05-27 05:35 UTC, merged