[imgui] Add test-engine feature
microsoft/vcpkg pull request #38758
Opened 2024-05-16 09:49 UTC by RT2Code

Add test-engine feature to the imgui port: https://github.com/ocornut/imgui_test_engine

I made it a feature because they both depend on each other to build, so a separate port was not possible.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-05-16 21:15 UTC, dg0yt commented on ports/imgui/portfile.cmake
> +    file(COPY "${TEST_ENGINE_SOURCE_PATH}/imgui_test_engine/" DESTINATION "${SOURCE_PATH}/test-engine")
```suggestion
    file(REMOVE_RECURSE "${SOURCE_PATH}/test-engine")
    file(COPY "${TEST_ENGINE_SOURCE_PATH}/imgui_test_engine/" DESTINATION "${SOURCE_PATH}/test-engine")
```
"Editable" build do not remove the sources.

2024-05-16 21:15 UTC, dg0yt commented on ports/imgui/portfile.cmake
> +    vcpkg_replace_string("${SOURCE_PATH}/imconfig.h" "#pragma once" "#pragma once\n\n#include \"imgui_te_imconfig.h\"")
```suggestion
    vcpkg_replace_string("${SOURCE_PATH}/imconfig.h" "#pragma once" "#pragma  once\n\n#include \"imgui_te_imconfig.h\"")
```
Again, handle editable builds.

2024-05-16 21:15 UTC, dg0yt commented on ports/imgui/portfile.cmake
> +endif()
This is surprising.  
If the licenses are the same, if/else is not needed.
If they are different, the FILE_LIST should perhaps be extended for test-engine.

2024-05-16 21:15 UTC, dg0yt commented on ports/imgui/portfile.cmake
> +        REF "v${VERSION}"
Do we need a test port to activate this feature?
It is easy to forget the test, or just to forget to update the SHA512 for a optional download.

2024-05-17 10:09 UTC, RT2Code commented on ports/imgui/portfile.cmake
> +endif()
The licenses are different: imgui uses MIT, but the test engine has its own license. This is an oversight on my part, both licenses should indeed be installed with the test-engine feature, I fixed it.

2024-05-17 10:21 UTC, RT2Code commented on ports/imgui/portfile.cmake
> +        REF "v${VERSION}"
I didn't know that test ports existed, but I suppose it would be better to have one here. I added it.

2024-05-17 19:34 UTC, dg0yt commented
Now we see how useful test ports and executables are...
With test-engine in imgui, there are two problems downstream:
- stb definitions in test engine duplicate the definitions in downstream apps.
- stb definitions in test engine are not relocatable.

Excerpt from milerius-sfml-imgui:
~~~
/mnt/vcpkg-ci/installed/x64-linux/include/stb_image_write.h:1617: multiple definition of `stbi_write_jpg'; /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libimguid.a(imgui_capture_tool.cpp.o):/mnt/vcpkg-ci/b/imgui/src/.6-docking-82d03bc653.clean/test-engine/thirdparty/stb/imstb_image_write.h:1519: first defined here
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libsfml-graphics-s-d.a(ImageLoader.cpp.o): warning: relocation against `stbi_write_force_png_filter' in read-only section `.text'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libsfml-graphics-s-d.a(ImageLoader.cpp.o): relocation R_X86_64_PC32 against symbol `stbi_write_tga_with_rle' can not be used when making a shared object; recompile with -fPIC
~~~

IMO there should be no stb definition in any lib (unless there would be a *single* stb lib) - that's how stb is designed.

2024-05-21 21:25 UTC, RT2Code commented
I managed to make it build on all platforms. I disabled uwp support because the test-engine library uses some CRT functions which aren't supported on this platform like _wpopen. I also replaced the embedded stb lib with the one from vcpkg to better conform to the vcpkg maintainer guidelines.

One thing that I'm really unhappy with is the way that the std implementation is managed. The only way I found to make it build everywhere was to disable it for static builds, but keep it enabled for dynamic builds, which is unconsistent.

Wouldn't it be better if the stb port compiled it to a static library instead of only providing the headers and leaving the responsability of handling the implementation to the user? The macro would need to be defined only once, in the port build, and then it would act like any other static library. No multiple definitions, no need to define any macro to get the implementation.

2024-05-22 02:02 UTC, WangWeiLin-MV approved these changes, later dismissed
The port usage and features test pass with the following triplets:
* x64-linux
* x64-windows

2024-05-22 03:54 UTC, dg0yt commented
> Wouldn't it be better if the stb port compiled it to a static library instead of only providing the headers and leaving the responsability of handling the implementation to the user? The macro would need to be defined only once, in the port build, and then it would act like any other static library. No multiple definitions, no need to define any macro to get the implementation.

That is also what I think. There are several such claim to be header only, but actually only avoid building a proper static lib. 
However I don't want to open this can of worms for packages which document another form of use.

2024-05-22 18:47 UTC, RT2Code commented
I spent more time studying the stb libs and reconsidered what I said. Those libs have many important compile time options, and some are designed to build with static symbols to allow for multiple configurations in the same project. If we build them into a static library, we remove those options for the user, so I now think the current way vcpkg handle stb is the best.

That being said, I have found a better way to fix the multiple definition issue. As I said, some stb libs provide the option to make the symbols static instead of public in the compilation unit, and it's perfect to prevent any clash with other libraries using the same stb headers. I just added the STB_IMAGE_WRITE_STATIC macro before std_image_write.h inclusion, and now everything builds fine on every platform with no ugly hacks.

2024-05-24 06:45 UTC, WangWeiLin-MV approved these changes, later dismissed
The port usage tests pass with the following triplets:
* x64-linux
* x64-windows

2024-05-24 23:06 UTC, RT2Code commented
Sorry, I changed it to draft because I want to try a different approach to add this feature which could be better. I'll make a second PR and I'll explain the difference between the two versions, so you can choose the one you think is the most pertinent.

2024-05-25 02:38 UTC, BillyONeal commented
In general, ports are not expected to build tests. Can you explain what a vcpkg customer does with this option? (This might be entirely fine, I just want to understand that it is :) )

2024-05-25 16:02 UTC, RT2Code commented
The test-engine library is an official component of imgui composed of two parts :
- The test-engine itself, a test/automation system for imgui.
- The test-suite, a collection of tests for imgui written with the test-engine.

The latter is not relevant for vcpkg, because as you said, ports are not supposed to build tests, that's why I ignore it in this port. But the test-engine can be very useful for a variety of applications. It's akin to libraries like google-test or catch2, it can be used to write your own tests for imgui, or for automation purposes. As it can simulate user inputs, it can also be used to write some kind of live tutorials, and it is also able to export the result to videos/gifs to showcase it. There's also a performance tool, and that's the feature that is lacking in the current PR that I want to try to add, but it's not easy because of a circular dependency with implot. 

In a nutshell, the test-engine is a very powerful set of features for imgui, and it really should be available in vcpkg.

2024-05-27 15:44 UTC, RT2Code commented
Ultimately, I was unable to make the new PR work [for reasons explained here](https://github.com/microsoft/vcpkg/pull/38961#issuecomment-2133714138), so, except if someone knows a way to fix it, I guess this one will have to do.

2024-05-27 22:53 UTC, vicroms requested changes

2024-05-27 22:53 UTC, vicroms commented on versions/i-/imgui.json
> +      "git-tree": "64d9267db2a90b61bc06b597c63a06611d610caa",
only the new version should be added please revert the change to `1.90.6`

2024-05-29 08:40 UTC, vicroms approved these changes

2024-05-29 08:40 UTC, merged