[wolfmqtt] update to 1.19.0
microsoft/vcpkg pull request #38849
Opened 2024-05-21 22:29 UTC by lealem47

2024-05-21 22:55 UTC, lealem47 commented
@microsoft-github-policy-service agree company="wolfSSL"

2024-05-22 01:59 UTC, WangWeiLin-MV requested changes

2024-05-22 01:59 UTC, WangWeiLin-MV commented on ports/wolfmqtt/portfile.cmake
> +    REF v1.19.0
```suggestion
    REF "v${VERSION}"
```

2024-05-24 02:12 UTC, WangWeiLin-MV approved these changes
The port usage tests pass with the following triplets:
* x64-windows

2024-05-25 02:20 UTC, BillyONeal commented
Can you explain why the CMake patch is no longer necessary (in order to force REQUIRED)? Thanks!

2024-05-29 15:36 UTC, lealem47 commented
> Can you explain why the CMake patch is no longer necessary (in order to force REQUIRED)? Thanks!
> 
> (I'm not saying that there's anything wrong with the change, I just want to make sure I understand why there is no problem should there be none :) )

Hi @BillyONeal, The patch is no longer necessary because it is already included in latest versions of wolfMQTT

2024-05-31 04:02 UTC, WangWeiLin-MV approved these changes

2024-05-31 04:02 UTC, WangWeiLin-MV commented on ports/wolfmqtt/cmake-patch.diff
Merged in https://github.com/wolfSSL/wolfMQTT/blob/v1.19.0/CMakeLists.txt#L66-L69

2024-05-31 19:44 UTC, merged