[phnt]Update phnt to 1.1.0
microsoft/vcpkg pull request #38863
Opened 2024-05-22 07:40 UTC by frendguo

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-05-22 07:41 UTC, frendguo commented
@microsoft-github-policy-service agree

2024-05-23 02:37 UTC, MonicaLiu0311 requested changes

2024-05-23 02:37 UTC, MonicaLiu0311 commented on ports/phnt/vcpkg.json
> +  "version-date": "2024-05-22",
```suggestion
  "version": "1.1.0",
  "version-date": "2024-05-22",
```

Either `version` or `version-date` , not both at the same time.
Also: I didn't find the `1.0.0` version upstream.

2024-05-23 02:37 UTC, MonicaLiu0311 commented on versions/baseline.json
> +      "port-version": 1
```suggestion
      "baseline": "2024-05-22",
      "port-version": 0
```

After modifying `portfile.cmake` and `vcpkg.json`, please commit, then use the `./vcpkg x-add-version phnt --overwrite-version` command to generate version information and then commit. rather than modifying it manually.

2024-05-23 02:37 UTC, MonicaLiu0311 commented on versions/baseline.json
> +      "port-version": 1
Please run `./vcpkg x-add-version testPort [--overwrite-version]` before each push:
1. For any file modification under the `ports/testPort/` folder, please commit after modification
2. Run `./vcpkg x-add-version portName` to generate a series of version according to your commit info (Add `--overwrite-version` when generating other than the first time)
     ```
     vcpkg/versions/
         t-/
             testport.josn (automatically generated)
         baseline.json (automatically add records)
     ```
3. Commit verison information again
4. Push together

`--overwrite-version`
After the first modification, please run `./vcpkg x-add-version testPort` to generate the corresponding json; for subsequent modifications of the same version, please use `./vcpkg x-add-version portName --overwrite-version` to update git-tree.

[maintainer guide#versioning](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#versioning).

2024-05-23 02:38 UTC, MonicaLiu0311 commented
Note: I will be converting your PR to draft status. When you're ready, please revert to "ready for review".

2024-05-24 06:04 UTC, MonicaLiu0311 commented
Please get [failure logs here](https://dev.azure.com/vcpkg/public/_build/results?buildId=103274&view=results). 
```
Installing 1/1 phnt:x64-windows@2024-05-22...
Building phnt:x64-windows@2024-05-22...
-- Downloading https://github.com/winsiderss/phnt/archive/4889215a26ece2105548103adba45238fc213fa4.tar.gz -> winsiderss-phnt-4889215a26ece2105548103adba45238fc213fa4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\a\_work\1\s\vcpkg-bundle.json
[DEBUG] Failed to open: D:\a\_work\1\s\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://vcpkgassetcachewus3.blob.core.windows.net/cache/34e2113daf28be85f7053f48881d6b7dc9fc54a5edf10995f1ae9d74c57b5c521ca90d0cfbd498e09182f1a069ef9a8b27c62bb3bf116d2b0fbc13ed2e337a38?*** SECRET ***
Downloading https://github.com/winsiderss/phnt/archive/4889215a26ece2105548103adba45238fc213fa4.tar.gz
[DEBUG] Trying to hash D:\downloads\winsiderss-phnt-4889215a26ece2105548103adba45238fc213fa4.tar.gz.8604.part
[DEBUG] D:\downloads\winsiderss-phnt-4889215a26ece2105548103adba45238fc213fa4.tar.gz.8604.part has hash 6f6a8d85f321da636a6849e270dc8f23a5706154fa8c63b351ece2198cce55e5ce79d5b05289ede61ee772205f523520c7090961dbba161addd9e78578cb7816
error: Failed to download from mirror set
error: https://vcpkgassetcachewus3.blob.core.windows.net/cache/34e2113daf28be85f7053f48881d6b7dc9fc54a5edf10995f1ae9d74c57b5c521ca90d0cfbd498e09182f1a069ef9a8b27c62bb3bf116d2b0fbc13ed2e337a38?*** SECRET ***: failed: status code 404
error: File does not have the expected hash:
url: https://github.com/winsiderss/phnt/archive/4889215a26ece2105548103adba45238fc213fa4.tar.gz
File: D:\downloads\winsiderss-phnt-4889215a26ece2105548103adba45238fc213fa4.tar.gz.8604.part
Expected hash: 34e2113daf28be85f7053f48881d6b7dc9fc54a5edf10995f1ae9d74c57b5c521ca90d0cfbd498e09182f1a069ef9a8b27c62bb3bf116d2b0fbc13ed2e337a38
Actual hash: 6f6a8d85f321da636a6849e270dc8f23a5706154fa8c63b351ece2198cce55e5ce79d5b05289ede61ee772205f523520c7090961dbba161addd9e78578cb7816
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 15us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 750us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 768 ms (758580us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`./ This is not correct, because `https://`/ prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port`/ to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://`/ prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/phnt/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)


error: building phnt:x64-windows failed with: BUILD_FAILED
Elapsed time to handle phnt:x64-windows: 821 ms
Total install time: 821 ms
```

2024-05-27 06:43 UTC, MonicaLiu0311 approved these changes

2024-05-27 22:37 UTC, merged