[sentry-native] Fix linux build error
microsoft/vcpkg pull request #39122
Opened 2024-06-04 10:16 UTC by JonLiu1993

Fixes #39114

Apply upstream change fix sentry-native linux build error. related issue: https://github.com/getsentry/sentry-native/issues/596#issuecomment-944118365

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-06-04 16:22 UTC, dg0yt requested changes
> [sentry-native] Fix linux build error

AFAICT there is no build error. There is a *runtime* error.
And that's why CI won't sufficiently indicate that the change is okay.

2024-06-04 16:22 UTC, dg0yt commented on ports/sentry-native/fix-crashpad-pthread.patch
> +-
IMO this change is incorrect. Cf. second part of https://github.com/microsoft/vcpkg/issues/39114#issuecomment-2146636567

2024-06-05 08:36 UTC, JonLiu1993 commented
Tested usage successfully by `sentry-native:x64-windows-static`

2024-06-06 09:23 UTC, WangWeiLin-MV approved these changes
The port usage tests pass with the following triplets:
* x64-linux
* x64-windows-static

2024-06-07 04:20 UTC, dg0yt commented
The changes should also be upstreamed, to have them included in future releases.

2024-06-07 07:35 UTC, JonLiu1993 commented
I have commit PR for upstream : 
https://github.com/getsentry/sentry-native/pull/1005 
https://github.com/getsentry/crashpad/pull/103

2024-06-07 09:55 UTC, merged