sophus 1.24.06
microsoft/vcpkg pull request #39225
Opened 2024-06-11 16:58 UTC by strasdat

<!-- If this PR updates an existing port, please uncomment and fill out this checklist:

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2024-06-12 02:27 UTC, jimwang118 requested changes

2024-06-12 02:27 UTC, jimwang118 commented on ports/sophus/vcpkg.json
> +  "version": "1.24.6",
Check the latest upstream release version is 1.22.10. Where did you get the updated 1.24.6 from?
In addition, if you update this port, you need to execute the ./vcpkg x-add-version {portname} command after updating the version, and then submit the generated version file.

2024-06-12 02:55 UTC, strasdat commented on ports/sophus/vcpkg.json
> +  "version": "1.24.6",
Oh, I did not create a release tag yet in the original repo. Thanks for the pointer.

2024-06-12 06:06 UTC, jimwang118 requested changes

2024-06-12 06:19 UTC, strasdat commented
@microsoft-github-policy-service agree

2024-06-12 06:28 UTC, jimwang118 commented
You need to execute the `./vcpkg x-add-version {portname}` command after updating the version, and then submit the generated version file.

2024-06-12 06:36 UTC, dg0yt commented on ports/sophus/vcpkg.json
> +  "version": "1.24.6",
STOP SUGGESTING USING LEADING ZEROS WITH SCHEME `version`.
IT DOESN'T WORK.

2024-06-12 06:43 UTC, strasdat commented on ports/sophus/vcpkg.json
> +  "version": "1.24.6",
fixed the tag in the origin repository instead

2024-06-12 07:12 UTC, dg0yt commented on ports/sophus/vcpkg.json
> +  "version": "1.24.6",
Okay.
In some other ports, we transform VERSION in the portfile instead.

2024-06-12 07:37 UTC, strasdat commented
@FrankXie05 I did create a new version for Sophus and it seems to work. Also. out of curiosity, I enabled to build tests to see whether it actual compiles for the target platform.

It looks like all windows builds are failing - I'm not too surprised since I have no windows CI in the base repository yet. The error seems to be:

```
 fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

What is the recommended course of action?

2024-06-12 09:11 UTC, jimwang118 approved these changes, later dismissed

2024-06-12 15:45 UTC, strasdat commented
@jimwang118 I think I might need another approval...

2024-06-12 18:45 UTC, dg0yt requested changes

2024-06-12 18:45 UTC, dg0yt commented on ports/sophus/portfile.cmake
> +        -DBUILD_SOPHUS_TESTS=ON
```suggestion
        -DBUILD_SOPHUS_TESTS=OFF
```
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-build-testsdocsexamples-by-default

2024-06-12 18:49 UTC, strasdat commented on ports/sophus/portfile.cmake
> +        -DBUILD_SOPHUS_TESTS=ON
@dg0yt sophus is a header only library and if we do not build the tests we actually do not know whether Sophus works in the target OS.

2024-06-12 18:57 UTC, dg0yt commented on ports/sophus/portfile.cmake
> +        -DBUILD_SOPHUS_TESTS=ON
It is not the first header-only lib in vcpkg... Which properties do really need to be tested *in every build* and isn't sufficiently controlled by upstream tests before a release?

Note that vcpkg provides build recipes and binary caching, but it doesn't distribute binary artifacts. Ports are built more often then one would expect.

2024-06-12 19:01 UTC, strasdat commented on ports/sophus/portfile.cmake
> +        -DBUILD_SOPHUS_TESTS=ON
Hm, yeah, that is an option. All windows builds were failing and I could only detect that with in vcpkg CI, since there are currently no windows builds upstream. But yeah we do not need to have that verified in every build.

2024-06-12 19:06 UTC, dg0yt commented on ports/sophus/portfile.cmake
> +        -DBUILD_SOPHUS_TESTS=ON
What may help until there is another downstream port is to add tiny test port in `scripts/test-ports`.
There is already a small collection. Some do only pull in non-default feautures, but other really build test projects (e.g. vcpkg-ci-soci).
This gives an end-to-end test experience in vcpkg CI (or for manual tests) without affecting every build.

2024-06-12 23:26 UTC, merged

2024-06-12 23:26 UTC, BillyONeal commented
Thanks for the update!

2024-06-13 01:26 UTC, FrankXie05 commented
> **edit: figured it out**
> 
> @FrankXie05 I did create a new version for Sophus and it seems to work. Also. out of curiosity, I enabled to build tests to see whether it actual compiles for the target platform.
> 
> It looks like all windows builds are failing - I'm not too surprised since I have no windows CI in the base repository yet. The error seems to be:
> 
> ```
>  fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
> ```
> 
> What is the recommended course of action?

It indicates that the number of sections in the object file has exceeded the limit imposed by the default object file format. 

This usually happens in large projects, or when using templates and complex code that generates a large number of sections in the object file.

You can instruct the compiler to use a larger object file format by adding the `/bigobj` option. :)
eg:
CMake:
```
if(MSVC)
add_compile_options(/bigobj)
endif()
```
makefile:
```
CXXFLAGS += /bigobj
```