[gsal] Add new port
microsoft/vcpkg pull request #39247
Opened 2024-06-12 10:18 UTC by talregev

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2024-06-12 17:09 UTC, AenBleidd commented on ports/gsasl/portfile.cmake
> +    URLS "https://ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
Maybe it would be better to use tagged archives from https://gitlab.com/gsasl/gsasl instead?

2024-06-12 23:13 UTC, talregev commented on ports/gsasl/portfile.cmake
> +    URLS "https://ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
You can change it in another PR.

2024-06-12 23:25 UTC, BillyONeal commented on ports/gsasl/portfile.cmake
> +    URLS "https://ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
I think an HTTPS download is fine. It's `vcpkg_from_git` that creates pain for caching systems.

2024-06-12 23:25 UTC, BillyONeal commented on ports/gsasl/portfile.cmake
> +        remove-testes-examples-docs.patch
```suggestion
        remove-tests-examples-docs.patch
```

2024-06-13 06:44 UTC, dg0yt commented on ports/gsasl/portfile.cmake
> +    URLS "https://ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
But I would strongly suggest to add a mirror. I did this for similar ports.

```suggestion
    URLS "https://ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
         "https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
```

2024-06-13 06:54 UTC, dg0yt requested changes
If you need an idea how to correctly deal with gettext and autopoint, `git grep AUTOPOINT` might be a starting point. For many ports, NLS is now controlled by a feature `nls`.

For now, I suggest to disable it. Untested.

2024-06-13 06:54 UTC, dg0yt commented on ports/gsasl/portfile.cmake
> +
```suggestion
```
(Wrong condition, wrong action.)

2024-06-13 06:54 UTC, dg0yt commented on ports/gsasl/portfile.cmake
> +    OPTIONS
```suggestion
    OPTIONS
        --disable-nls
```

2024-06-13 06:54 UTC, dg0yt commented on ports/gsasl/vcpkg.json
> +  ]
```suggestion
  "supports": "!uwp"
```
(Would need elaboration for target and host dependencies.)

2024-06-13 06:55 UTC, dg0yt commented on ports/gsasl/portfile.cmake
> +
Breaks `--editable` builds.
This should be done after install only, in `CURRENT_PACKAGES_DIR`.

2024-06-13 06:56 UTC, dg0yt commented on ports/gsasl/remove-testes-examples-docs.patch
> ++AM_CONDITIONAL([HAVE_GTK_DOC], false)
Other ports (e.g. libgutls) use `set(ENV{GTKDOCIZE} true)` in the portfile to get rid of the doc dependency. Maybe this could work here, too.

2024-06-13 06:57 UTC, dg0yt commented on ports/gsasl/remove-testes-examples-docs.patch
> +
I don't think these changes are necessary. And they don't save much time.

2024-06-13 13:03 UTC, AenBleidd commented on ports/gsasl/portfile.cmake
> +    URLS "https://ftp.gnu.org/gnu/gsasl/gsasl-${VERSION}.tar.gz"
This is exactly the reason I suggested to use GitLab: I strongly believe its uptime and response time are better than the ftp.
@talregev, I just want to help. No need to be aggressive again.

2024-06-13 19:49 UTC, talregev commented on ports/gsasl/remove-testes-examples-docs.patch
> +
I remove them because it not compile on windows. They have __attribute__

2024-06-13 19:58 UTC, talregev commented on ports/gsasl/portfile.cmake
> +
I cannot remove it, it fail on build on static. Maybe after this PR, you will find another creative solution for this problem.

2024-06-13 19:59 UTC, talregev commented on ports/gsasl/portfile.cmake
> +    OPTIONS
Even if I disable nls, it still looking for autopoint.

2024-06-13 20:19 UTC, dg0yt commented on ports/gsasl/remove-testes-examples-docs.patch
> +
You already remove the SUBDIRS. That's why the Makefiles should already have no effect.

2024-06-13 20:20 UTC, dg0yt commented on ports/gsasl/portfile.cmake
> +
See port libidn2 for how to do it.

2024-06-13 20:26 UTC, talregev commented on ports/gsasl/portfile.cmake
> +
I change it.

2024-06-13 20:26 UTC, talregev commented on ports/gsasl/remove-testes-examples-docs.patch
> +
ok.

2024-06-17 17:21 UTC, talregev commented
@MonicaLiu0311 Can you take a look. Thank you for your help!

2024-06-18 09:10 UTC, MonicaLiu0311 commented
When testing usage, the following error occurs:
```
>------ Build All started: Project: CMakeUsage, Configuration: x64-Debug ------
  MSBuild version 17.10.4+10fbfbf2e for .NET Framework
  
    CMakeUsage.cpp
G:\gsasl\installed\x64-windows\include\gsasl.h(36,11): error C1083: Cannot open include file: 'unistd.h': No such file or directory 

Build All failed.
```
<details>
<summary><b>test.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "gsasl.h"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "G:/gsasl/scripts/buildsystems/vcpkg.cmake")

project ("test")

add_library (main "test.cpp")

find_package(PkgConfig REQUIRED) 
pkg_check_modules(TEST REQUIRED IMPORTED_TARGET libgsasl) 
target_include_directories(main PRIVATE ${TEST_INCLUDE_DIRS}) 
target_link_libraries(main ${TEST_LIBRARIES})
</pre></details>

2024-06-18 22:45 UTC, talregev commented
@MonicaLiu0311 When I am using gsasl on curl port, I am using it like that:

```cmake
if(USE_GSASL)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(GSASL REQUIRED libgsasl)
  list(APPEND CURL_LIBS ${GSASL_LINK_LIBRARIES})
endif()
```

2024-06-18 22:47 UTC, talregev commented
https://cmake.org/cmake/help/latest/module/FindPkgConfig.html

From hehe you should:
<XXX>_INCLUDE_DIRS
the '-I' preprocessor flags (without the '-I')

<XXX>_LINK_LIBRARIES
the libraries and their absolute paths

2024-06-18 23:17 UTC, talregev commented
G:\gsasl\installed\x64-windows\include\gsasl.h(36,11):
```
# include <unistd.h>		/* ssize_t */
```
from stackoverflow: 
https://stackoverflow.com/questions/22705751/cannot-open-include-file-unistd-h-no-such-file-or-directory
The "uni" in unistd stands for "UNIX" - you won't find it on a Windows system.

I will test if this working on curl on windows.

2024-06-18 23:57 UTC, talregev commented
@MonicaLiu0311 I fix the issue.
Also create PR in upstream:
https://gitlab.com/gsasl/gsasl/-/merge_requests/10

2024-06-19 02:14 UTC, MonicaLiu0311 commented
> @MonicaLiu0311 I fix the issue. Also create PR in upstream: https://gitlab.com/gsasl/gsasl/-/merge_requests/10

Thanks you, let's wait a moment for the upstream response.

2024-06-19 03:58 UTC, dg0yt commented
Don't forget to test mingw.

2024-06-23 15:16 UTC, talregev commented
@MonicaLiu0311 upstream is not responsive. I also give them a link to here if they want to talk with us.
Please review my PR.

2024-06-24 06:22 UTC, MonicaLiu0311 commented
```
>------ Build All started: Project: CMakeUsage, Configuration: x64-Debug ------
  MSBuild version 17.10.4+10fbfbf2e for .NET Framework
  
    1>Checking Build System
    Building Custom Rule C:/Users/v-liumonica/source/repos/CMakeUsage/CMakeUsage/CMakeLists.txt
    CMakeUsage.cpp
C:\Users\monica\source\repos\CMakeUsage\out\build\x64-Debug\CMakeUsage\LINK : fatal error LNK1104: cannot open file 'gsasl.lib' 

Build All failed.
```

<details>
<summary><b>test.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "gsasl.h"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "G:/gsasl/scripts/buildsystems/vcpkg.cmake")

project ("test")

add_library (main "test.cpp")

find_package(PkgConfig REQUIRED) 
pkg_check_modules(TEST REQUIRED IMPORTED_TARGET libgsasl) 
target_include_directories(main PRIVATE ${TEST_INCLUDE_DIRS}) 
target_link_libraries(main ${TEST_LIBRARIES})
</pre></details>

2024-06-24 06:25 UTC, talregev commented
@MonicaLiu0311 `${TEST_LINK_LIBRARIES}`

2024-06-24 08:11 UTC, MonicaLiu0311 commented
When I use the command line to build, both `${TEST_LINK_LIBRARIES}` and `${TEST_LIBRARIES}` succeed.

![image](https://github.com/microsoft/vcpkg/assets/110024546/de3657a2-c753-44a7-824b-70da4790dc1d)

2024-06-24 08:11 UTC, MonicaLiu0311 approved these changes

2024-06-25 00:58 UTC, BillyONeal commented
I would like @JavierMatosD to review since this touches vcpkg_Xxx_make

2024-06-25 18:16 UTC, talregev commented
@BillyONeal You can also check how I use gsasl in curl port: #39497

2024-06-26 20:06 UTC, BillyONeal commented
> Why is a risk to use `vcpkg_configure_make` and `vcpkg_install_make`?

It's more like "I don't know how these work and would like someone who does to confirm that this is OK" than "I see a problem"

2024-06-26 20:24 UTC, BillyONeal commented on ports/gsasl/remove-testes-examples-docs.patch
> ++AM_CONDITIONAL([HAVE_GTK_DOC], false)
@dg0yt how does set(ENV{GTKDOCIZE} true) *remove* doc dependencies?

2024-06-26 21:49 UTC, BillyONeal commented on ports/gsasl/remove-testes-examples-docs.patch
> ++AM_CONDITIONAL([HAVE_GTK_DOC], false)
oh wow @Neumann-A just explained it. This isn't 'turn on the feature', this is 'set the path to the thing to the program named true which is an empty program that does nothing'. So `set(ENV{GTKDOCIZE} true)` *looks* like 'please turn on GTKDOCIZE' but actually means 'please remove GTKDOCIZE'

2024-06-26 21:49 UTC, merged

2024-06-26 21:49 UTC, BillyONeal commented
Thanks for the new port! (I talked with @JavierMatosD about it out of band)

2024-06-26 21:52 UTC, dg0yt commented on ports/gsasl/remove-testes-examples-docs.patch
> ++AM_CONDITIONAL([HAVE_GTK_DOC], false)
yeah. There is a reason why usually add a comment `# true, the program`.

2024-06-26 22:08 UTC, Neumann-A commented on ports/gsasl/remove-testes-examples-docs.patch
> ++AM_CONDITIONAL([HAVE_GTK_DOC], false)
And to add to the confusion

```
neumann@Iluinrandir:~$ true
neumann@Iluinrandir:~$ echo $?
0
neumann@Iluinrandir:~$ false
neumann@Iluinrandir:~$ echo $?
1
```

so its not even a Boolean true/false.

2024-12-13 20:17 UTC, talregev commented
@Neustradamus 
https://gitlab.com/gsasl/gsasl/-/merge_requests/10

2024-12-13 20:37 UTC, Neustradamus commented
@talregev: New comment done!