Add opendis6 library
microsoft/vcpkg pull request #39349
Opened 2024-06-18 04:58 UTC by crhowell3

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

This PR introduces the opendis6 package, a C++ implementation of the IEEE 1278.1a-1998 Distributed Interactive Simulation standard.

2024-06-18 05:02 UTC, crhowell3 commented
@microsoft-github-policy-service agree

2024-06-18 07:34 UTC, LilyWangLL commented on ports/opendis6/usage
> +target_link_libraries(main PRIVATE opendis6::opendis6)
The link target should be `target_link_libraries(main PRIVATE OpenDIS::OpenDIS6)`, and missing the include property.

2024-06-18 07:35 UTC, LilyWangLL commented
The CI pipeline error could be fixed by run command `.\vcpkg x-add-version opendis6 --overwrite-version`.

2024-06-18 14:57 UTC, crhowell3 commented
> The CI pipeline error could be fixed by run command `.\vcpkg x-add-version opendis6 --overwrite-version`.

I ran this command and updated the version database in my latest commit, but the `microsoft.vcpkg.pr (x86_windows)` CI job is still failing. Is there something else I need to do?

2024-06-19 03:07 UTC, LilyWangLL requested changes

2024-06-19 03:07 UTC, LilyWangLL commented on ports/opendis6/portfile.cmake
> +  SOURCE_PATH "${SOURCE_PATH}"
```suggestion
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DINSTALL_INCLUDE_DIR=include
```

2024-06-19 03:07 UTC, LilyWangLL commented on ports/opendis6/usage
> +	target_include_directories(main PRIVATE ${OpenDIS_INCLUDE_DIR})
```suggestion
```

2024-06-19 03:07 UTC, LilyWangLL commented on ports/opendis6/portfile.cmake
> +  SOURCE_PATH "${SOURCE_PATH}"
Due to the value [INSTALL_INCLUDE_DIR](https://github.com/crhowell3/opendis6/blob/dc1cd3bffdffcabf13b237f270d92cfebf45717c/CMakeLists.txt#L29C27-L29C46) is empty, so the target missed the include property.
You could fix this by this way or change this in source.

2024-06-19 03:44 UTC, dg0yt commented on ports/opendis6/portfile.cmake
> +  SOURCE_PATH "${SOURCE_PATH}"
@crhowell3 You are "upstream". Did you intent to use GNUInstallDirs's `CMAKE_INSTALL_INCLUDEDIR` instead of `INSTALL_INCLUDE_DIR`?

2024-06-19 03:49 UTC, dg0yt commented on ports/opendis6/portfile.cmake
> +  vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Upstream has `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`. That is not perfect, but is it so bad that dynamic linkage doesn't work?

2024-06-19 03:49 UTC, dg0yt commented on ports/opendis6/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2024-06-19 03:49 UTC, dg0yt commented on ports/opendis6/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)
```suggestion
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
```

2024-06-19 03:49 UTC, dg0yt commented on ports/opendis6/usage
> +	target_link_libraries(main PRIVATE OpenDIS::OpenDIS6)
General pattern:
```suggestion
opendis6 provides CMake targets:

  find_package(OpenDIS CONFIG REQUIRED)
  target_link_libraries(main PRIVATE OpenDIS::OpenDIS6)
```

2024-06-19 19:39 UTC, dg0yt commented on ports/opendis6/usage
> +	target_link_libraries(main PRIVATE OpenDIS::OpenDIS6)
```suggestion
opendis6 provides CMake targets:

  find_package(OpenDIS CONFIG REQUIRED)
  target_link_libraries(main PRIVATE OpenDIS::OpenDIS6)
```
vcpkg tool uses 2 spaces now in heuristics, so all new/updated `usage` files should follow.

2024-06-20 08:39 UTC, LilyWangLL commented
Usage test passed on `x64-windows`.

2024-06-20 08:39 UTC, LilyWangLL approved these changes, later dismissed

2024-06-21 03:41 UTC, BillyONeal reviewed
I'm a bit nervous about the name, as searching for `opendis` points to https://github.com/open-dis/open-dis-cpp rather than this library. The name 'opendis6' points to this repo on repology, but only from Conan and the author of the Conan recipe is also @crhowell3 . I'm torn between saying 'it's in repology, it's already out there' and asking for `crhowell3-opendis6` instead.

Tagging vcpkg-team-review for a 2nd opinion

2024-06-21 15:23 UTC, crhowell3 commented
@BillyONeal Maybe this is too drastic of a suggestion, but what if I were to just change the name of my package to avoid confusion with the other `opendis` library? I could name it something like `dis-cpp` or `disprotocol`, maybe even just `dis6`. Thoughts? Alternative name suggestions?

2024-06-21 20:53 UTC, BillyONeal commented
> @BillyONeal Maybe this is too drastic of a suggestion, but what if I were to just change the name of my package to avoid confusion with the other `opendis` library? I could name it something like `dis-cpp` or `disprotocol`, maybe even just `dis6`. Thoughts? Alternative name suggestions?

The problem is that there's nonzero potential confusion with https://github.com/open-dis . (That is, we want someone who does `vcpkg install opendis6` to not be surprised when they get something not owned by that org)

I think odds are pretty high we take the name as written here, we just want more than one maintainer to OK any time anything is worth questioning because once we 'give away' a name like that, we can't take it back. Whereas we can always rename `crhowell3-opendis6` to `opendis6` should the library in question become the unambiguous defacto meaning of that name in the future.

2024-06-21 20:55 UTC, BillyONeal approved these changes, later dismissed
This LGTM if the name is OK. Thanks for the new port!

2024-06-27 22:21 UTC, BillyONeal commented
@AugP
@ras0219-msft
@data-queue
@JavierMatosD
and I discussed this today.

@ras0219-msft I agree the repology reference to only conan is problematic. The names like disprotocol would be fine though.

@BillyONeal But someone who wants opendis6 would never type `vcpkg install disprotocol`

@ras0219-msft That's fair.

@BillyONeal The other problem is searching for 'disprotocol' also points to github.com/open-dis

In order to accept this we want the name to be crhowell3-opendis6, given the potential confusion with the github organization github.com/open-dis.

Since you are upstream, if you're willing to rename the repo and rename the project to something with no chance of confusion we would be happy to do that too.

Thanks for your contribution to vcpkg!

2024-06-28 15:45 UTC, crhowell3 commented
I'm certainly open to changing the name of the package! Would a name like `libdis6` work? It looks clean on https://repology.org, and searching for it does not bring up the other open-dis package.

2024-06-30 05:19 UTC, crhowell3 commented
Looks like the pipeline is getting an error stating that the package directory is nonexistent. I pushed a fix to my upstream main branch, but I was only able to confirm it was resolved locally using `vcpkg install libdis6 --head`. Just using `vcpkg install libdis6` does not work. Is there something I need to do to correct that?

2024-07-08 01:31 UTC, LilyWangLL approved these changes, later dismissed

2024-07-11 22:38 UTC, JavierMatosD commented
@data-queue, @vicroms, @AugP, and below discussed this today.

We don't count trailing numbers as a distinguisher between ports. For example, we expect `libfoo6` to be related to `libfoo5` and `libfoo`. Additionally, a `lib` prefix isn't considered a distinguisher between ports. For example, we don't want `libpng` to be different that `png`. Therefore, this name is taking the stem `dis`. 

@BillyONeal - Still concerned about the name being confused with the `open-dis` project. A user cannot type the name you picked and think they got `open-dis` and `dis` or even `libdis6` isn't sufficiently different enough to disambiguate between projects. I'm weakly against this. I still propose `<org>-name`

@ras0219-msft - For example, we wouldn't accept the name `libecmascript6`. `dis` is less known than `ecmascript` but using the name of the standard as the name of the library is problematic unless blessed by owners of the standard. 

Given the discussion above, we would still like a more unique name.

2024-07-12 04:11 UTC, crhowell3 commented
I understand. I'll try to think of a package name that does not incorporate the `dis` stem so as to avoid confusion with the `open-dis` library. If I can't think of anything, then I'll just go with `<org>-name` as you all have proposed. Thank you for taking the time to review and comment.

2024-07-12 05:01 UTC, crhowell3 commented
@JavierMatosD, @data-queue, @vicroms,  @AugP and whomever else may be involved:

Here is my final name proposition: `libsersi` (from *ser*ialize and *si*mulation). If this is sufficient, I'll change it upstream. If not, then I am fine moving forward with the `<org>-name`  suggestion. In either case, thank you for being patient with me and for being as helpful as you have been.

2024-07-15 18:41 UTC, JavierMatosD commented
> @JavierMatosD, @data-queue, @vicroms, @AugP and whomever else may be involved:
> 
> Here is my final name proposition: `libsersi` (from _ser_ialize and _si_mulation). If this is sufficient, I'll change it upstream. If not, then I am fine moving forward with the `<org>-name` suggestion. In either case, thank you for being patient with me and for being as helpful as you have been.

@crhowell3, I think `libsersi` is good. Thank you for your patience and understanding.

2024-07-17 01:42 UTC, LilyWangLL approved these changes

2024-07-18 16:40 UTC, merged