[opencc] allow to build on arm
microsoft/vcpkg pull request #39366
Opened 2024-06-18 19:10 UTC by shenlebantongying

This package can be built on arm (I tested on macOS) today.

Homebrew has been providing Arm build of this package for a very long time https://formulae.brew.sh/formula/opencc

2024-06-19 02:16 UTC, jimwang118 requested changes

2024-06-19 02:16 UTC, jimwang118 commented on ports/opencc/vcpkg.json
>    "description": "A project for conversions between Traditional Chinese, Simplified Chinese and Japanese Kanji (Shinjitai)",
"port-version": 2,

2024-06-19 02:16 UTC, jimwang118 commented on ports/opencc/vcpkg.json
>    "description": "A project for conversions between Traditional Chinese, Simplified Chinese and Japanese Kanji (Shinjitai)",
Run the command: ./vcpkg x-add-version {portname}, and then submit the generated result.

2024-06-19 03:56 UTC, dg0yt reviewed
The real problem was never arm, but insufficient cross-build support in the vcpkg port. That's why arm android fails now: It tries to run  `opencc_dict` on the host. But in vcpkg, ports may build only for one triplet, and everything else must be modeled via host dependencies.

2024-06-19 03:56 UTC, dg0yt commented on ports/opencc/vcpkg.json
> +  "supports": "!(uwp)",
```suggestion
  "supports": "!uwp",
```

2024-06-19 04:35 UTC, shenlebantongying commented on ports/opencc/vcpkg.json
> +  "supports": "!(uwp)",
So, should I also add `!android` and `!x86` to pass CI?

I don't think upstream is going to fix them :sweat_smile:

2024-06-19 05:07 UTC, dg0yt commented on ports/opencc/vcpkg.json
> +  "supports": "!(uwp)",
No, it is not an upstream issue. It is how to adapt the build to vcpkg's concept of separating host triplet and target triplet.

2024-06-19 13:51 UTC, shenlebantongying commented
@microsoft-github-policy-service agree

2024-06-24 06:24 UTC, jimwang118 approved these changes, later dismissed

2024-06-25 01:57 UTC, BillyONeal commented
@shenlebantongying please fix the build failures and then mark ready for review. I'm guessing you just need a "!android" in supports?

2024-06-30 00:30 UTC, closed without merging