[folly, cachelib] support libdwarf related functionality
microsoft/vcpkg pull request #39547
Opened 2024-06-27 03:51 UTC by c8ef

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-06-27 09:02 UTC, MonicaLiu0311 approved these changes

2024-06-27 09:05 UTC, MonicaLiu0311 commented
folly
-
Feature `libdwarf` is tested successfully in the following triplet:
```
x64-windows
x64-windows-static
```

2024-06-27 20:11 UTC, BillyONeal commented on ports/folly/vcpkg.json
> +    },
What hooks up this feature? There should be corresponding changes in portfile.cmake to hook it up but I don't see them...

2024-06-28 03:37 UTC, dg0yt commented on ports/folly/vcpkg.json
> +    },
"Header-based" means auto-detection means installation order problems with binary caching.  
Folly may pick dependencies (libdwarf) which are installed for other reasons then the feature being activated.
Then the cached artifact will not record not that it needs to have the dependency installed first.
The the user will see errors when he tries to use folly.

2024-06-29 05:51 UTC, BillyONeal requested changes
Locking whether the feature is enabled to the feature setting needs to be implemented.

Implementing this with a REQUIRE_FIND_PACKAGE/DISABLE_FIND_PACKAGE pair in `vcpkg_check_features` is acceptable.

2024-06-29 06:11 UTC, closed without merging