[cpprealm] new port
microsoft/vcpkg pull request #39561
Opened 2024-06-27 14:29 UTC by leemaguire

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-06-28 02:32 UTC, jimwang118 requested changes

2024-06-28 02:32 UTC, jimwang118 commented on ports/cpprealm/portfile.cmake
> +        REF "ae469c149503570c4dd74b1b0e7be488b6996284"
```suggestion
        REF "v${VERSION}"

```

2024-06-28 02:32 UTC, jimwang118 commented on ports/cpprealm/portfile.cmake
> +file(WRITE ${CURRENT_PACKAGES_DIR}/include/cpprealm/internal/bridge/bridge_types.hpp "${MODIFIED_HEADER}")
Can't the modification of file bridge_types.hpp be done through a patch or upstream?

2024-06-28 02:52 UTC, jimwang118 requested changes

2024-06-28 02:52 UTC, jimwang118 commented on ports/cpprealm/portfile.cmake
> +vcpkg_cmake_config_fixup(PACKAGE_NAME "cpprealm" CONFIG_PATH "cmake")
```suggestion
vcpkg_cmake_config_fixup(CONFIG_PATH "cmake")

```

2024-06-28 02:53 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2024-06-28 09:36 UTC, leemaguire commented on ports/cpprealm/portfile.cmake
> +file(WRITE ${CURRENT_PACKAGES_DIR}/include/cpprealm/internal/bridge/bridge_types.hpp "${MODIFIED_HEADER}")
This needs to be done after the compiler invocation, as we rely on a generated binary to give us the size and memory alignment of our bridged realm-core types. So this will need to happen after `vcpkg_cmake_install()`.

2024-07-01 01:45 UTC, jimwang118 submitted a review, later dismissed

2024-07-01 06:50 UTC, dg0yt requested changes
Community feedback. Untested.

2024-07-01 06:50 UTC, dg0yt commented on ports/cpprealm/portfile.cmake
> +)
Keep it simple. Quote for CMake, not for the command line interpreter.
```suggestion
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
        -DREALM_CPP_NO_TESTS=ON
        -DREALM_ENABLE_EXPERIMENTAL=ON
        -DREALMCXX_VERSION=${VERSION}
)
```

2024-07-01 06:50 UTC, dg0yt commented on ports/cpprealm/portfile.cmake
> +file(WRITE ${CURRENT_PACKAGES_DIR}/include/cpprealm/internal/bridge/bridge_types.hpp "${MODIFIED_HEADER}")
ATM it breaks release-only configs, and I don't like the whole trick. 
I would simplify this to:
```suggestion
if(NOT VCPKG_BUILD_TYPE)
    file(READ "${CURRENT_PACKAGES_DIR}/debug/include/cpprealm/internal/bridge/bridge_types.hpp" DEBUG_TYPE_HEADER_CONTENTS)
    file(READ "${CURRENT_PACKAGES_DIR}/include/cpprealm/internal/bridge/bridge_types.hpp" RELEASE_TYPE_HEADER_CONTENTS)
    file(WRITE "${CURRENT_PACKAGES_DIR}/include/cpprealm/internal/bridge/bridge_types.hpp" "
#ifdef REALM_DEBUG
${DEBUG_TYPE_HEADER_CONTENTS}
#else
${RELEASE_TYPE_HEADER_CONTENTS}
#endif
")
endif()
```

2024-07-03 01:51 UTC, jimwang118 approved these changes, later dismissed

2024-07-03 07:20 UTC, dg0yt reviewed
(Community feedback.)

2024-07-03 07:20 UTC, dg0yt commented on ports/cpprealm/portfile.cmake
> +#if defined(_DEBUG) || !defined(NDEBUG)
IMO using `NDEBUG` is asking for trouble. The user project might set it independent of build type, anytime, to control `assert`, not ABI.

2024-07-03 07:20 UTC, dg0yt commented on ports/cpprealm/vcpkg.json
> +    },
In other cases, version constraints were rejected for the main registry.

2024-07-03 07:20 UTC, dg0yt commented on ports/cpprealm/portfile.cmake
> +        HEAD_REF "main")
Nitpick:
```suggestion
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO realm/realm-cpp
    REF "v${VERSION}"
    SHA512 "d880daea7bceb3143052cae9d8883b448162484adacc566cca5315ac096964d0c79c421b25a76d5c2efbd8c3294dfb5acd3dd7314a6c154163e7d141b9eb2e51"
    HEAD_REF "main"
)

```

2024-07-03 12:03 UTC, leemaguire commented on ports/cpprealm/portfile.cmake
> +#if defined(_DEBUG) || !defined(NDEBUG)
I've removed this completely in favour of using the `REALM_DISABLE_ALIGNED_STORAGE` cmake flag we expose.

2024-07-03 12:04 UTC, leemaguire commented on ports/cpprealm/vcpkg.json
> +    },
Could you expand more on what you mean by this, and what action we should take?

2024-07-03 16:51 UTC, JavierMatosD commented on ports/cpprealm/vcpkg.json
> +    },
@leemaguire can you explain why this version constraint is required?

2024-07-03 16:51 UTC, JavierMatosD commented on ports/cpprealm/vcpkg.json
> +  "name": "cpprealm",
Should this be renamed to `realm-cpp` to match `realm-core` and the upstream repo?

2024-07-03 16:51 UTC, JavierMatosD commented
Converting the PR to draft. Please mark ready for review once you've replied.

2024-07-03 20:53 UTC, BillyONeal commented on ports/cpprealm/vcpkg.json
> +    },
>In other cases, version constraints were rejected for the main registry.

It looks like we have plenty of those to me:

![image](https://github.com/microsoft/vcpkg/assets/1544943/d90eb62a-dbf1-4597-bad2-6f40fe4fb1e9)

The situation I know we had a problem with was that we opposed trying to keep 'metapackages' consistent because it made every change invalidate the universe. (as in, changing one thing about boost-build shouldn't force a package-version update on every other boost thing)

2024-07-03 22:42 UTC, BillyONeal commented on ports/cpprealm/vcpkg.json
> +    },
(That said, "just fill in the version that is current that a baseline would do anyway" should not happen)

2024-07-04 08:35 UTC, leemaguire commented on ports/cpprealm/vcpkg.json
> +  "name": "cpprealm",
The target name is `cpprealm` for historical reasons, and our docs & folder structure already reflect that target name.

I have no issue changing the port folder and name to be `realm-cpp` as long as the `cpprealm` target name can be kept. What are you thoughts @JavierMatosD?

2024-07-04 08:37 UTC, leemaguire commented
@JavierMatosD I have placed the version constraints as these are the minimum versions of the dependancies we test on for this version of `cpprealm`.

2024-07-04 08:39 UTC, leemaguire commented on ports/cpprealm/vcpkg.json
> +    },
@JavierMatosD I have placed the version constraints as these are the minimum versions of the dependancies we test on for this version of cpprealm.

2024-07-04 08:43 UTC, leemaguire commented on ports/cpprealm/vcpkg.json
> +    },
@BillyONeal if there is a more correct way to reference the dependancies in this case please let me know.

2024-07-05 17:15 UTC, JavierMatosD commented on ports/cpprealm/vcpkg.json
> +  "name": "cpprealm",
I don't think changing the name is necessary if that's the target name.

2024-07-05 17:18 UTC, JavierMatosD commented on ports/cpprealm/vcpkg.json
> +    },
> I have placed the version constraints as these are the minimum versions of the dependancies we test on for this version of cpprealm.

In that case, I think we should drop the version constraints.

2024-07-08 08:47 UTC, leemaguire commented on ports/cpprealm/vcpkg.json
> +    },
@JavierMatosD I've updated the PR with version constraints removed.

2024-07-08 14:07 UTC, merged