[eCAL] Update to 5.13.2
microsoft/vcpkg pull request #39595
Opened 2024-06-29 14:22 UTC by DownerCase

Fixes #39316 

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [X] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2024-07-01 06:54 UTC, LilyWangLL commented
Usage test passed on `x64-windows`.

2024-07-01 06:54 UTC, LilyWangLL approved these changes

2024-07-01 22:18 UTC, JavierMatosD requested changes

2024-07-10 08:45 UTC, LilyWangLL commented
Pinging @DownerCase for response. Can you address the review suggestions? Thanks!

2024-07-10 17:48 UTC, DownerCase commented on ports/ecal/portfile.cmake
> -        -DDISABLE_FIND_PACKAGE_OVERLOAD=ON # From patch, disable find_package macro
Because it was added in [0002-fix-build.patch](https://github.com/microsoft/vcpkg/pull/39595/files#diff-d4ace9d8d38050f9fc57e179878ba6b53b96db862d99399571adb3a1e2bf9f27) to disable eCAL's overriding of `find_package()` which has since been removed by upstream refactoring (https://github.com/eclipse-ecal/ecal/commit/263c7c084d9029c432476765d026f07ed6f60c0e) so no longer needed.

2024-07-10 17:51 UTC, DownerCase commented on ports/ecal/portfile.cmake
> -        -DECAL_JOIN_MULTICAST_TWICE=OFF
The option was removed upstream [CMakeLists.txt](https://github.com/eclipse-ecal/ecal/commit/28ef1a150bf7e27d0748c124d42a7381f72c4862#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a)

2024-07-10 17:52 UTC, DownerCase commented
> Pinging @DownerCase for response. Can you address the review suggestions? Thanks!

Done. The removals in question were due to fixes upstream.

2024-07-13 14:28 UTC, JavierMatosD approved these changes

2024-07-13 14:28 UTC, merged