Asmjit update - Following pull request #39090
microsoft/vcpkg pull request #39630
Opened 2024-07-01 13:33 UTC by JakubMelka

If this PR updates an existing port, please uncomment and fill out this checklist:

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2024-07-01 13:35 UTC, JakubMelka commented
@microsoft-github-policy-service agree

2024-07-01 13:41 UTC, JakubMelka commented
This request is following pull request #39090.

2024-07-01 13:54 UTC, kobalicek commented on ports/asmjit/vcpkg.json
> +  "version-date": "2024-06-05",
Here must be a correct version: 2024-06-28

2024-07-01 13:54 UTC, kobalicek commented on versions/a-/asmjit.json
> +      "version-date": "2024-06-05",
Here must be a correct version: 2024-06-28

2024-07-01 13:55 UTC, kobalicek commented on versions/baseline.json
> +      "baseline": "2024-06-05",
Here must be a correct version: 2024-06-28

2024-07-01 14:03 UTC, JakubMelka commented on ports/asmjit/vcpkg.json
> +  "version-date": "2024-06-05",
Fixed.

2024-07-01 14:03 UTC, JakubMelka commented on versions/a-/asmjit.json
> +      "version-date": "2024-06-05",
Fixed date, but @kobalicek, I think "git-tree" should also be updated? How this hash is constructed?

2024-07-01 14:27 UTC, JakubMelka commented on versions/a-/asmjit.json
> +      "version-date": "2024-06-05",
Figured it out. ./vcpkg x-add-version --all --overwrite-version solved it.

2024-07-02 02:30 UTC, JonLiu1993 commented on ports/asmjit/vcpkg.json
> +  "documentation": "https://asmjit.com/doc/index.html",
@JakubMelka, Thanks for your PR, there are two points to note here. First, we prefer the homepage URL of github `https://github.com/asmjit/asmjit`
Second, can you explain why the new version does not support arm?

2024-07-02 03:49 UTC, JonLiu1993 commented on ports/polyhook2/portfile.cmake
> -    PATCHES fix-dep.patch
The patch has been applied to the latest version.

2024-07-02 03:50 UTC, JonLiu1993 commented on versions/f-/fbgemm.json
> -      "git-tree": "e19b797fb42fad6dae0f9aca0890ddc62535800f",
Restore it,  please do not modify the history `git-tree`.

2024-07-02 03:52 UTC, JonLiu1993 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2024-07-02 03:58 UTC, dg0yt requested changes
Just one change needed. Thanks from the community.

2024-07-02 03:58 UTC, dg0yt commented on ports/asmjit/vcpkg.json
> +  "documentation": "https://asmjit.com/doc/index.html",
@JonLiu1993 You read it wrong, twice.
The homepage URL is *unchanged*.
Arm support is *added*, not removed.

2024-07-02 03:58 UTC, dg0yt commented on ports/fbgemm/vcpkg.json
> +  "supports": "!arm & !x86 & !uwp",
*This* exclusion of arm might have been hitten behind a `asmjit` failure cascade. So it is not worse than before.

2024-07-02 03:58 UTC, dg0yt commented on versions/f-/fbgemm.json
> -      "git-tree": "e19b797fb42fad6dae0f9aca0890ddc62535800f",
This is badly displayed on Github. Let me add a suggestion a feew lines later...

2024-07-02 03:58 UTC, dg0yt commented on versions/f-/fbgemm.json
> +      "git-tree": "2aa09f4d6344a0c379f6b65fae72dc8117759805",
Here:
```suggestion
      "git-tree": "e19b797fb42fad6dae0f9aca0890ddc62535800f",
```
i.e. the original value for `0.4.1#0`.

2024-07-02 04:01 UTC, dg0yt commented on ports/asmjit/vcpkg.json
> +  "documentation": "https://asmjit.com/doc/index.html",
To be honest, my preference is  
homepage: https://asmjit.com/
documentation: https://asmjit.com/doc/

https://github.com/asmjit/asmjit *is not* the homepage.

2024-07-02 07:28 UTC, JakubMelka commented on ports/polyhook2/portfile.cmake
> -    PATCHES fix-dep.patch
Is some action from me needed?

2024-07-02 07:30 UTC, JakubMelka commented on versions/f-/fbgemm.json
> -      "git-tree": "e19b797fb42fad6dae0f9aca0890ddc62535800f",
This is very strange. This is commit from other author. In diff, it is displayed as this: 
![image](https://github.com/microsoft/vcpkg/assets/11367048/c99065f8-4e8f-45bb-a0b6-121f629c8ae9)

You mean that I should restore hash for port-version 0?

2024-07-02 07:31 UTC, JakubMelka commented on ports/fbgemm/vcpkg.json
> +  "supports": "!arm & !x86 & !uwp",
Yes, ARM support for ASMJIT has been added, but FBGEMM does not support it.

2024-07-02 07:35 UTC, JakubMelka commented on versions/f-/fbgemm.json
> +      "git-tree": "2aa09f4d6344a0c379f6b65fae72dc8117759805",
OK, I have reverted it.

2024-07-02 07:37 UTC, JakubMelka commented on versions/f-/fbgemm.json
> -      "git-tree": "e19b797fb42fad6dae0f9aca0890ddc62535800f",
port-version 0 has been restored.

2024-07-02 08:03 UTC, JakubMelka commented
@JonLiu1993, I hope I have fixed all your issues.

2024-07-03 08:19 UTC, dg0yt approved these changes
LGTM, but someone else must approve.

2024-07-03 16:27 UTC, kobalicek commented
I approve, although my approval is worthless here :)

And I don't approve the patching of course, but that we know from the previous PR.

2024-07-05 17:57 UTC, merged