[fmt] update to 11.0.1
microsoft/vcpkg pull request #39738
Opened 2024-07-07 06:03 UTC by miyanyan

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-07-07 14:33 UTC, miyanyan commented
got some error with folly, this's my first time to see such error, will see it tomorrow evening
>CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/github/miyanyan/vcpkg/buildtrees/folly/x64-windows-rel/libfolly.pc

libfolly.pc:
```prefix=D:/github/miyanyan/vcpkg/packages/folly_x64-windows
  exec_prefix=D:/github/miyanyan/vcpkg/packages/folly_x64-windows
  libdir=${exec_prefix}/lib
  includedir=${prefix}/include
  
  Name: libfolly
  Description: Facebook (Folly) C++ library
  Version: 0.58.0-dev
  Cflags: -I${includedir}  /Zc:__cplusplus  -DFMT_SHARED -DBOOST_CONTEXT_NO_LIB= -DBOOST_CONTEXT_DYN_LINK= -DBOOST_CONTEXT_EXPORT=EXPORT -DBOOST_FILESYSTEM_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK=1 -D -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_USE_DLL -DGLOG_USE_GLOG_EXPORT -DGLOG_USE_GFLAGS -DGLOG_NO_ABBREVIATED_SEVERITIES -DGFLAGS_IS_A_DLL=1 -ID:/github/miyanyan/vcpkg/installed/x64-windows/include
  Libs: -L${libdir} -lfolly
  Libs.private: -lIphlpapi.lib -lWs2_32.lib -lD:/github/miyanyan/vcpkg/installed/x64-windows/lib/zlib.lib -l -lD:/github/miyanyan/vcpkg/installed/x64-windows/lib/libssl.lib -l -lD:/github/miyanyan/vcpkg/installed/x64-windows/lib/libcrypto.lib -l
```

2024-07-08 02:22 UTC, jimwang118 commented
> got some error with folly, this's my first time to see such error, will see it tomorrow evening
> 
> > CMake Error in CMakeLists.txt:
> > Evaluation file to be written multiple times with different content.  This
> > is generally caused by the content evaluating the configuration type,
> > language, or location of object files:
> > D:/github/miyanyan/vcpkg/buildtrees/folly/x64-windows-rel/libfolly.pc
> 
> libfolly.pc:
> 
> ```
>   exec_prefix=D:/github/miyanyan/vcpkg/packages/folly_x64-windows
>   libdir=${exec_prefix}/lib
>   includedir=${prefix}/include
>   
>   Name: libfolly
>   Description: Facebook (Folly) C++ library
>   Version: 0.58.0-dev
>   Cflags: -I${includedir}  /Zc:__cplusplus  -DFMT_SHARED -DBOOST_CONTEXT_NO_LIB= -DBOOST_CONTEXT_DYN_LINK= -DBOOST_CONTEXT_EXPORT=EXPORT -DBOOST_FILESYSTEM_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK=1 -D -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_USE_DLL -DGLOG_USE_GLOG_EXPORT -DGLOG_USE_GFLAGS -DGLOG_NO_ABBREVIATED_SEVERITIES -DGFLAGS_IS_A_DLL=1 -ID:/github/miyanyan/vcpkg/installed/x64-windows/include
>   Libs: -L${libdir} -lfolly
>   Libs.private: -lIphlpapi.lib -lWs2_32.lib -lD:/github/miyanyan/vcpkg/installed/x64-windows/lib/zlib.lib -l -lD:/github/miyanyan/vcpkg/installed/x64-windows/lib/libssl.lib -l -lD:/github/miyanyan/vcpkg/installed/x64-windows/lib/libcrypto.lib -l
> ```

This may be caused by multi-threaded compilation. You can add the DISABLE_PARALLEL_CONFIGURE compilation option and then try compiling.

2024-07-08 04:27 UTC, dg0yt commented
> This may be caused by multi-threaded compilation. ... `DISABLE_PARALLEL_CONFIGURE`.

This option is for not disabling parallel *configuration* (i.e. CMake). This helps with parallel writes to the source directory (`D:/github/miyanyan/vcpkg/buildtrees/folly/src/...`). 
However, the error points at the build dir (`D:/github/miyanyan/vcpkg/buildtrees/folly/x64-windows-rel/libfolly.pc`).

2024-07-08 14:40 UTC, miyanyan commented
> > This may be caused by multi-threaded compilation. ... `DISABLE_PARALLEL_CONFIGURE`.
> 
> This option is for not disabling parallel _configuration_ (i.e. CMake). This helps with parallel writes to the source directory (`D:/github/miyanyan/vcpkg/buildtrees/folly/src/...`). However, the error points at the build dir (`D:/github/miyanyan/vcpkg/buildtrees/folly/x64-windows-rel/libfolly.pc`).

find an issue https://github.com/facebook/folly/issues/2250

2024-07-15 01:13 UTC, miyanyan commented
another folly build error is https://github.com/facebook/folly/pull/2255

2024-07-18 01:53 UTC, jimwang118 requested changes

2024-07-18 01:53 UTC, jimwang118 commented on ports/folly/vcpkg.json
>    "port-version": 1,
```suggestion
```

2024-07-22 01:09 UTC, miyanyan commented
> another folly build error is [facebook/folly#2255](https://github.com/facebook/folly/pull/2255)

[https://github.com/fmtlib/fmt/pull/4055](https://github.com/fmtlib/fmt/issues/4036) maybe this will fix

2024-07-23 01:05 UTC, miyanyan commented
the arm64_osx check seems failed to start

2024-07-25 01:43 UTC, miyanyan commented
https://github.com/facebook/folly/pull/2265

2024-07-25 02:43 UTC, jimwang118 commented
All features passed with following triplets:

```
x64-windows
x64-windows-static
```
Usage test pass with following triplets:

```
x64-windows
x64-windows-static
```

2024-07-25 02:51 UTC, miyanyan commented
> [facebook/folly#2265](https://github.com/facebook/folly/pull/2265)

@jimwang118 my folly patch is based on https://github.com/facebook/folly/pull/2255, but seems https://github.com/facebook/folly/pull/2265 is the chosen one, maybe this pr should not merged now?

2024-07-25 02:55 UTC, jimwang118 commented
> @jimwang118 my folly patch is based on [facebook/folly#2255](https://github.com/facebook/folly/pull/2255), but seems [facebook/folly#2265](https://github.com/facebook/folly/pull/2265) is the chosen one, maybe this pr should not merged now?

Okay, I have removed the reviewed tag. Maybe you can use vcpkg_download_distfile to directly download this PR as a patch.

2024-07-26 02:17 UTC, jimwang118 commented
I will change the PR status to Draft. If you have finished editing, please click 'ready for review'.

2024-08-02 18:17 UTC, BillyONeal approved these changes

2024-08-02 18:17 UTC, BillyONeal commented
> Fixes #40000 

Ooooo nice number.

2024-08-03 04:36 UTC, miyanyan commented
hi, if [vcpkg_cmake_configure](https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_cmake_configure) set ```BUILD_SHARED_LIBS``` according to the value of ```VCPKG_LIBRARY_LINKAGE```,  is it still needed to replace ```FMT_SHARED```? I found fmt will set it:
https://github.com/fmtlib/fmt/blob/master/CMakeLists.txt#L349

2024-08-03 06:47 UTC, dg0yt commented
If you refer to the `vcpkg_replace_string`: This is needed for projects which don't use CMake.  Mostly msbuild.

2024-08-03 07:41 UTC, BillyONeal commented
What dg0yt said. In general we prefer to rely on build system bindings for as little as possible as not every downstream build system listens to such bindings. That's why this replacement was in place before.

2024-08-03 07:41 UTC, merged