Add port str-view
microsoft/vcpkg pull request #39872
Opened 2024-07-11 23:01 UTC by agl-alexglopez

If this PR adds a new port, please uncomment and fill out this checklist:

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-07-11 23:02 UTC, agl-alexglopez commented
@microsoft-github-policy-service agree

2024-07-12 01:40 UTC, LilyWangLL commented
Please update the version files as the maintainer-guide: https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#update-the-version-files-in-versions-of-any-modified-ports.

2024-07-12 02:04 UTC, LilyWangLL requested changes

2024-07-12 04:19 UTC, agl-alexglopez commented
Thank you!

2024-07-12 07:37 UTC, LilyWangLL commented
Please fix the build error, you could check the error log from CI pipeline: https://dev.azure.com/vcpkg/public/_build/results?buildId=104940&view=artifacts&pathAsName=false&type=publishedArtifacts.

2024-07-12 16:58 UTC, agl-alexglopez commented
The errors are from the msvc compiler.

I have set up a GitHub action on my repository for this library. It runs a windows machine and uses cmake to build a release, similar to how the failing tests build the project. Here are the commands I use.

```zsh
cmake -S . -B build -G "Visual Studio 17 2022" -A x64
cmake --build build --config Debug
```

After addressing the needed changes for msvc, my action built the project no problem. What else could I try to get my action to more closely resemble these failing test runners? That way I can troubleshoot faster.

2024-07-15 02:58 UTC, LilyWangLL commented
> Alternatively, if I specify I do not support windows with the `"supports"` option in my `vcpkg.json` file will these tests pass? Or is supporting windows required for all new ports?

If the upstream of this port explicitly states that the port does not support Windows builds, the `supports` field should be added to `vcpkg.json`. If there are currently unresolved compilation errors, you can temporarily add `str-view:x64-windows=fail` to `[VCPKG_ROOT]/scripts/ci.baseline.txt`. Once the errors are resolved, you can remove the corresponding fail.

2024-07-15 03:01 UTC, LilyWangLL requested changes

2024-07-15 03:01 UTC, LilyWangLL commented on ports/str-view/portfile.cmake
> +)
```suggestion
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO agl-alexglopez/str_view
    REF "v${VERSION}"
    SHA512 63d8821d62409c7b6bda838ca4a687b183345be83bcf1a5a302a3e2115a290467fac292d1d7809de195589890f3c5982e9c3089c02b2c51c84498efd9a9adb94
    HEAD_REF main
)
```

2024-07-15 08:10 UTC, agl-alexglopez commented on ports/str-view/portfile.cmake
> +)
Ok I agree. But I will use the 'release' branch as the HEAD_REF so users can get only the necessary library through vcpkg and don't need to download tests, resources, images, etc. that are in the main branch.

2024-07-15 09:18 UTC, LilyWangLL requested changes

2024-07-15 09:18 UTC, LilyWangLL commented on ports/str-view/vcpkg.json
> +  "supports": "!windows",
```suggestion
```
Since this port will support windows build in the future, and you have added it fail in `ci.baseline.txt`, so this supports should be removed.

2024-07-16 09:42 UTC, LilyWangLL submitted a review, later dismissed

2024-07-17 03:57 UTC, dg0yt commented on ports/str-view/usage
> +target_link_libraries(main PRIVATE str_view::str_view)
Nitpick
```suggestion
str_view provides CMake targets:

  find_package(str_view CONFIG REQUIRED)
  target_link_libraries(main PRIVATE str_view::str_view)
```

2024-07-23 01:46 UTC, LilyWangLL commented
/azp run

2024-07-24 17:32 UTC, data-queue approved these changes

2024-07-24 17:33 UTC, merged