[lib3mf] New port. Introduces version 2.3.2
microsoft/vcpkg pull request #39886
Opened 2024-07-12 14:59 UTC by vijaiaeroastro

This PR introduces a new port for lib3mf. The version is 2.3.2

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-07-15 04:14 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +)
All dependencies should be split out and packaged separately, see [Do not use vendored dependencies](https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-vendored-dependencies).

2024-07-25 02:54 UTC, WangWeiLin-MV reviewed
Note: I will be converting your PR to draft status. Please click "Ready for review" after making the fix and modifications.


Please feel free to mark 'Ready for review' when you're happy with it.

2024-07-25 02:54 UTC, WangWeiLin-MV commented on ports/lib3mf/vcpkg.json
> +      "version>=": "V2.rc.08"
The port `cpp-base64` using `version-string`, which vcpkg does not compare.

2024-07-25 02:54 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Just suggestion:

```suggestion
vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO 3MFConsortium/lib3mf
    REF "v${VERSION}"
    SHA512 875529759aff6128b32291d0719b95a75a72a3b19f98711b12c9b1076727b231668b3b14604e69bb1fec79b4725fd098f030b7e965072e566bfb061f3086279c
    HEAD_REF master
)

vcpkg_apply_patches(
    SOURCE_PATH ${SOURCE_PATH}
    PATCHES "0001-lib3mf-fix-deps.patch"
)
```

2024-07-25 02:54 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++option(USE_INCLUDED_FAST_FLOAT "Use included fast float library" ON)
As new options, these require upstream approval. We would be very grateful if you could submit it upstream.

2024-07-25 02:54 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    endif()
It seems that it only needs `target_link_libraries(${PROJECT_NAME} PRIVATE ZLIB::ZLIB)`
```suggestion
```

2024-07-25 02:54 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++endif ()
`fast-float` provides usage:
```
find_package(FastFloat CONFIG REQUIRED)
target_link_libraries(main PRIVATE FastFloat::fast_float)
```

2024-07-25 02:54 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    if(CMAKE_TOOLCHAIN_FILE MATCHES "vcpkg")
The port internal patches do not need check it.

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/portfile.cmake
> +vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
More like:

```suggestion
vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO 3MFConsortium/lib3mf
    REF "v${VERSION}"
    SHA512 875529759aff6128b32291d0719b95a75a72a3b19f98711b12c9b1076727b231668b3b14604e69bb1fec79b4725fd098f030b7e965072e566bfb061f3086279c
    HEAD_REF master
    PATCHES
        0001-lib3mf-fix-deps.patch
)
```
(Don't call `vcpkg_apply_patches` separately.)

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++option(USE_INCLUDED_FAST_FLOAT "Use included fast float library" ON)
NB: There don't need to be new option unless you want to suggest this upstream.
vcpkg will probably never use `ON`.

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++#target_include_directories(${PROJECT_NAME} PRIVATE ${LIBS_INCLUDE})
Reduce to
```suggestion
-target_include_directories(${PROJECT_NAME} PRIVATE ${LIBS_INCLUDE})
```

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    find_package(LIBZIP REQUIRED)
Just
```suggestion
-    find_package(PkgConfig REQUIRED)
-    pkg_check_modules(LIBZIP REQUIRED libzip)
-    target_link_libraries(${PROJECT_NAME} ${LIBZIP_LIBRARIES})
+    find_package(LIBZIP REQUIRED)
+    target_link_libraries(${PROJECT_NAME} PRIVATE libzip::zip)
```
Attention, using imported targets means the exported cmake config needs `find_dependency`.

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    target_link_libraries(${PROJECT_NAME} PRIVATE ZLIB::ZLIB)
Just
```suggestion
-    find_package(PkgConfig REQUIRED)
-    pkg_check_modules(ZLIB REQUIRED zlib)
-    target_link_libraries(${PROJECT_NAME} ${ZLIB_LIBRARIES})
+    find_package(ZLIB REQUIRED)
+    target_link_libraries(${PROJECT_NAME} PRIVATE ZLIB::ZLIB)
```
Attention, using imported targets means the exported cmake config needs `find_dependency`.

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/portfile.cmake
> +    -DLIB3MF_TESTS=OFF
Nitpick:
```suggestion
    OPTIONS 
       -DUSE_INCLUDED_ZLIB=OFF
       -DUSE_INCLUDED_LIBZIP=OFF
       -DUSE_INCLUDED_BASE_64=OFF
       -DUSE_INCLUDED_FAST_FLOAT=OFF
       -DUSE_INCLUDED_SSL=OFF
       -DBUILD_FOR_CODECOVERAGE=OFF
       -DLIB3MF_TESTS=OFF
```

2024-07-25 03:20 UTC, dg0yt commented on ports/lib3mf/portfile.cmake
> +file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
Don't repeat yourself.
```suggestion
vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/lib3mf)
vcpkg_fixup_pkgconfig()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2024-07-25 03:58 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
Sorry I was negligent, please follow @dg0yt 's suggestion.

2024-07-25 18:38 UTC, dg0yt reviewed
The `usage` file should be a short synopsis. If the basic usage pattern doesn't fit in a few lines, it is alerting.

`lib3mf::lib3mf` changing personality subject to `find_package` components seems to be asking for trouble in a world where different libs might ask for different configurations and forward that configuration to downstream to an executable. Ideally `find_package` is used only once per project, but there are good reasons for multiple instances of `target_link_libraries`.

Letting the vcpkg triplet correctly control the library linkage, and letting the user choose the API/language per use, seems much cleaner:
~~~
lib3mf provide CMake targets:

  find_package(lib3mf CONFIG REQUIRED)

  # C API
  target_link_libraries(main PRIVATE lib3mf::C)

  # C++ API
  target_link_libraries(main PRIVATE lib3mf::Cpp)
~~~

2024-07-25 18:38 UTC, dg0yt commented on ports/lib3mf/usage
> +Choose the component type based on your usage needs.
This is too much choice for vcpkg. The type of linkage is determined by the triplet, either static or shared. Packages are patched if necessary (and feasible).

2024-07-25 18:38 UTC, dg0yt commented on ports/lib3mf/usage
> +    * target_link_libraries is just an interface and it introduces a definition called LIB3MF_LIBRARY_LOCATION which points to the location of the library
Too much detail, and not really right.

2024-07-26 04:41 UTC, dg0yt commented on ports/lib3mf/usage
> +Choose the component type based on your usage needs.
>  When they use CppDynamic or CDynamic, no actual linkage happens, and the DLL path is simply passed to the code. 

What does this mean: Is it used as a module/plugin loaded at runtime?

2024-07-28 06:38 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++endif ()
~~~
fast-float provides CMake targets:

    find_package(FastFloat CONFIG REQUIRED)
    target_link_libraries(main PRIVATE FastFloat::fast_float)
~~~

The config package is named FastFloat. It is located in `share/FastFloat`.

~~~cmake
set_target_properties(FastFloat::fast_float PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
~~~

The desired file is in `include/fast_float`, so the proper statement is
~~~cxx
#include <fast_float/fast_float.h>
~~~

2024-07-28 09:21 UTC, dg0yt commented
> Since the port is officially prepared by the 3MFConsortium developers, all these changes will be merged upstream and made available in the next release. Hopefully, no patch will be required in future releases.

That's nice. But IMO it should be achieve without any `USE_VCPKG` and `CMAKE_TOOLCHAIN_FILE MATCHES "vcpkg"`.

2024-07-28 09:46 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++endif()
This should be avoided. De-vendoring deps is a general topic for packaging, not a vcpkg topic.

2024-07-28 09:46 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++#endif
Labeling it `USE_VCPKG` is misleading (but might be acceptable as a temorary solution).
The upstream task is to move the vendored fast_float to a subdir so that it could uniformly use the official `#include <fast_float/fast_float.h>`.

2024-07-28 09:46 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    find_dependency(ZLIB 1.3.1)
`VCPKG_TOOLCHAIN` again...
I see why you do it for `LIB3MF_ROOT_DIR`. But
- The dependencies actually depend on (NOT) `USE_INCLUDED_LIBZIP` and (NOT) `USE_INCLUDED_ZLIB`.
- The dependencies actually depend on (NOT) `BUILD_SHARED_LIBS` when used with `PRIVATE`.
- The dependencies actually only make sense if they appear in `INTERFACE_LINK_LIBRARIES`. But does the package actually use `install(EXPORT ...)`? I don't see exported targets being included in https://github.com/3MFConsortium/lib3mf/blob/v2.3.2/cmake/lib3mfConfig.cmake, so all the benefits of Modern CMake including transitive usage requirements and multi-config support are lost. 

But this port is `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` ATM, so the result of `find_dependency` is unused anyways. Maybe it *could* be a static lib if it would only use good Modern CMake practice. A small test project could easily ensure proper cmake config for static linkage.

2024-07-28 09:46 UTC, dg0yt commented on ports/lib3mf/usage
> +
Really, stick to the common pattern:
```suggestion
lib3mf provides CMake targets:

  find_package(lib3mf CONFIG REQUIRED)
  target_link_libraries(target_name PRIVATE lib3mf::lib3mf) 

For examples and use cases, kindly check
https://github.com/3MFConsortium/lib3mf/tree/develop/SDK/CPackExamples
```

2024-07-28 09:46 UTC, dg0yt commented on ports/lib3mf/vcpkg.json
> +    }
Port manifest normally don't use version constraints. `vcpkg-cmake-config` is a host port.
```suggestion
    "fast-float",
    "libzip",
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    },
    "name": "zlib"
```

2024-07-28 11:23 UTC, dg0yt commented on ports/lib3mf/vcpkg.json
> +    }
This defines minimum versions, not pinned versions, for users of manifest mode.
And it constrains how informed users mix ports. They might (and should) do their own testing. It is valuable information which version you tested/recommend, but it doesn't imply earlier (patch) versions wouldn't work.

vcpkg CI will only test the combination of latest versions.

2024-07-28 11:24 UTC, dg0yt commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    find_dependency(ZLIB 1.3.1)
BTW hardcoding versions here might be another maintenance debt.

2024-07-30 07:51 UTC, WangWeiLin-MV requested changes

2024-07-30 07:51 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +    SHA512 df05d86f872a97fc129a4c316bffa5ba69cf8a266440ca31b32dd461c929d4d9111a54875f919d39dcd5dc69dba54255406f1164a062e33bce04d79c5a4533aa
```suggestion
    REF "v${VERSION}"
    SHA512 875529759aff6128b32291d0719b95a75a72a3b19f98711b12c9b1076727b231668b3b14604e69bb1fec79b4725fd098f030b7e965072e566bfb061f3086279c
```

2024-07-30 07:51 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> +@@ -170,20 +172,35 @@ if (USE_INCLUDED_LIBZIP)
```suggestion
@@ -170,20 +172,36 @@ if (USE_INCLUDED_LIBZIP)
```

2024-07-30 07:51 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++            ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/cpp-base64/base64.cpp)
```suggestion
+    find_path(CPP_BASE64_INCLUDE_DIRS "cpp-base64/base64.cpp")
+    include_directories("${CPP_BASE64_INCLUDE_DIRS}/cpp-base64")
+    set(BASE64_SRC
+            ${CPP_BASE64_INCLUDE_DIRS}/cpp-base64/base64.h
+            ${CPP_BASE64_INCLUDE_DIRS}/cpp-base64/base64.cpp)
```

2024-07-30 08:00 UTC, WangWeiLin-MV commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++            ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/cpp-base64/base64.cpp)
Project should not use the variables in portfiles, since "Portfiles and Project builds invoked by portfiles are run in different processes", see https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#portfiles-are-run-in-script-mode.

For the above case, one way is to pass parameters, and a better way is searching for libs by the well-known usage, i.e. find from search path.

2024-07-30 09:05 UTC, WangWeiLin-MV reviewed
~The port usage tests pass with the following triplets:~

* ~x64-linux~
* ~x64-windows~

Invalid check after update.

2024-07-30 09:05 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +# Only dynamic libraries (Based on Jan's Port)
```suggestion
```

2024-07-30 09:05 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +# Pull from github directly
```suggestion
```

2024-07-30 09:05 UTC, WangWeiLin-MV commented on ports/lib3mf/portfile.cmake
> +# Proceed with the usual build process
```suggestion
```

2024-07-31 01:30 UTC, WangWeiLin-MV submitted a review, later dismissed
The port usage tests pass with the following triplets:

* x64-linux
* x64-windows

2024-08-01 00:17 UTC, BillyONeal commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++option(USE_INCLUDED_FAST_FLOAT "Use included fast float library" ON)
There's stuff like commented out code here which clearly won't be shipped that way in a release as-is, so I'm inclined to reduce the patch size by removing the options.

2024-08-01 00:18 UTC, BillyONeal commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++    find_dependency(ZLIB)
Here these are controlled by `VCPKG_TOOLCHAIN` but elsewhere they're controlled by separate options. What controls `find_dependency` should always match what controls it in the CMakeLists.txt

2024-08-01 00:25 UTC, BillyONeal commented on ports/lib3mf/lib3mf_vcpkg.patch
> ++option(USE_INCLUDED_FAST_FLOAT "Use included fast float library" ON)
Oh wait, I see now that this PR is coming from upstream's GitHub org, so I think we can assume that means upstream is OK with it.

2024-08-01 00:44 UTC, BillyONeal requested changes
As written the patch seems inapplicable for either the goal of minimizing the size of the patch in vcpkg, as well as the goal of matching exactly what upstream should do. To that end, I would like to see something like one of the following.

Option A: Minimize the size of the patch to only what vcpkg needs to touch, I've submitted as https://github.com/3MFConsortium/vcpkg/pull/2

Option B: Actually wire up the new options correctly with respect to what upstream needs to do to be correct in their CMake configs; I've submitted that as https://github.com/3MFConsortium/vcpkg/pull/3

2024-08-01 04:27 UTC, WangWeiLin-MV approved these changes
The port usage tests pass with the following triplets:

* x64-linux
* x64-windows

2024-08-01 15:54 UTC, BillyONeal approved these changes

2024-08-01 15:54 UTC, merged

2024-08-01 15:54 UTC, BillyONeal commented
Thanks for the new port!