[lua] Update 5.3.5. Modern CMake practices and MinGW Linux support.
microsoft/vcpkg pull request #39953
Opened 2024-07-16 23:13 UTC by XJ-0461

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Updates:

- Added `INSTALL_TOOLS` CMake option via `tools` vcpkg feature
- Better support cross-compiling builds
  - Cross-compiling previous port (5.3.5#6) to Windows target without PowerShell available on the system (likely on Linux) causes error `CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message): Could not find PowerShell Core; please open an issue to report this.`
- Modern CMake config-file usage style find_package() with targets in the unofficial::lua:: namespace.
  - FindLua.cmake no longer required
- Feature 'cpp' adds C++ library to the install, as opposed to changing behavior of core lua port.
  - Current behavior (in my opinion) goes against the spirit of 'Do not use features to implement alternatives' recommendation from the Maintaner guide.
  - Exports
    - C library target - unofficial::lua::lua
    - C++ library target - unofficial::lua::lua-cpp

2024-07-17 15:44 UTC, XJ-0461 commented
@JonLiu1993 @ruitard @dg0yt. I see yall have been involved with this port in the past. Any comments on this?

Can we abandon the FindLua module completely?
  - Move toward `unofficial::lua::` targets with find_package() in the way I've done here.
  - Find modules are for packages that dont supply config-file packages, which we obviously can and do.
  
Should tools be a default feature?

2024-07-17 22:48 UTC, dg0yt commented
(Disclaimer: Community feedback)
- The powershell dependency of mingw triplets is known to work on Linux. It is used for app-local deployment of DLLs. (AFAIU vcpkg is expected to do this deployment directly in the future.)
- Abandoning the existing `FindLua` might break existing users.
- Tools should not be a default feature in vcpkg AFAICT.

2024-07-17 23:03 UTC, dg0yt reviewed
Some early comments.

2024-07-17 23:03 UTC, dg0yt commented on ports/lua/portfile.cmake
> +    FILENAME "lua-5.3.5.tar.gz"
Removing `${VERSION}` is not desired.

2024-07-17 23:03 UTC, dg0yt commented on ports/lua/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/cpp/CMakeLists.txt DESTINATION ${SOURCE_PATH}/cpp)
Removing double quotes is not desired for non-trivial expressions.

2024-07-17 23:03 UTC, dg0yt commented on ports/lua/portfile.cmake
> +    if (VCPKG_TARGET_IS_WINDOWS)
Actually we usually remove such spaces.
I see that this file wasn't consistent before.

2024-07-19 00:45 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +        target_link_libraries(lua ${LIB_MATH})
Updated to link `m` instead.

2024-07-19 00:47 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    endif()
Using solely `CMAKE_DL_LIBS`. `if (LIB_DLOPEN)` changed to `if (NOT CMAKE_DL_LIBS STREQUAL "")` to determine if the system has `dl`

2024-07-19 00:48 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    endif()
Yes, some refactoring holdover. Removed.

2024-07-19 00:50 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +    FILENAME "lua-5.3.5.tar.gz"
Added `${VERSION}` here

2024-07-19 00:51 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +file(COPY ${CMAKE_CURRENT_LIST_DIR}/cpp/CMakeLists.txt DESTINATION ${SOURCE_PATH}/cpp)
Added double-quotes around select expressions.

2024-07-19 02:23 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +    if (VCPKG_TARGET_IS_WINDOWS)
yes, this is my style preference. If there is an official vcpkg style guide somewhere I will be happy to conform with it.

2024-07-19 02:45 UTC, XJ-0461 commented
@dg0yt Thanks for your quick feedback, I appreciate the help on this.

I will say, though when I take inspiration from some of the newer lua ports I do not understand the rationale behind the choices in the `vcpkg-cmake-wrapper` files.

For example in the [latest 5.4.6 vcpkg-cmake-wrapper](https://github.com/microsoft/vcpkg/blob/master/ports/lua/vcpkg-cmake-wrapper.cmake.in) file we see:

```cmake
_find_package(unofficial-lua CONFIG ${REQUIRES})

get_filename_component(LUA_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}" PATH)
get_filename_component(LUA_INCLUDE_DIR "${LUA_INCLUDE_DIR}" PATH)
set(LUA_INCLUDE_DIR ${LUA_INCLUDE_DIR}/include)

list(APPEND LUA_LIBRARIES lua)
if (TARGET lua-cpp)
    list(APPEND LUA_LIBRARIES lua-cpp)
endif()
```

It silently redirects users to `unofficial-lua`. Perhaps there should be a warning to the user? Because the user will be expected to use the `unofficial::` targets anyways.

If the user uses the `cpp` feature, then `find_package(lua)` will set LUA_LIBRARIES to both the C and C++ version of the library? Users will not want to link to both at the same time. This also diverges from the expected behavior of `FindLua.cmake` which sets `LUA_LIBRARIES` to "both lua and lualib".

2024-07-19 05:16 UTC, dg0yt commented
It is hard to understand the rationale behind historical choices...

 > Perhaps there should be a warning to the user? 

That's what I do in such migration polyfill, e.g. in `port/skia/skiaConfig.cmake`:
~~~
file(READ "${CMAKE_CURRENT_LIST_DIR}/usage" usage)
message(AUTHOR_WARNING "find_package(skia) is deprecated.\n${usage}")
~~~

 > Because the user will be expected to use the `unofficial::` targets anyways.

Well, I guess the legacy interface is the *variables*, not the targets. 
(However, imported targets within variables are bad. That's why I want users to fully migrate to targets.)

> If the user uses the `cpp` feature, then `find_package(lua)` will set LUA_LIBRARIES to both the C and C++ version of the library? Users will not want to link to both at the same time. This also diverges from the expected behavior of `FindLua.cmake` which sets `LUA_LIBRARIES` to "both lua and lualib".

Maybe it has always been this way in this vcpkg port... Somebody introduced it, and nobody else want to touch it without understanding why it was done in the first place.

2024-07-19 15:36 UTC, XJ-0461 commented
Investigating regression in `rbdl` port.

2024-07-22 09:44 UTC, Cheney-W commented
@XJ-0461 Could you please update this port to 5.4.7 for fixing https://github.com/microsoft/vcpkg/issues/40014? Thank you!

2024-07-22 17:47 UTC, XJ-0461 commented
> @XJ-0461 Could you please update this port to 5.4.7 for fixing #40014? Thank you!

@Cheney-W this PR is for 5.3.5, there will have to be a separate PR for 5.4.7.

2024-07-22 23:03 UTC, XJ-0461 commented
I think this port is ready to merge. It improves the ergonomics of using this package from within CMake, providing features that should be normalized across all of the vcpkg lua ports.
- Exports CMake targets in the unofficial:: namespace
  - unofficial::lua::lua (C library)
  - unofficial::lua::lua-cpp (C++ library)
  - unofficial::lua::lua-compiler (compiler executable)
  - unofficial::lua::lua-interpreter (interpreter executable)
- Supports legacy flow explicitly
  - vcpkg-cmake-wrapper exports variables expected from [FindLua](https://cmake.org/cmake/help/latest/module/FindLua.html) CMake module
- `cpp` vcpkg feature adds functionality instead of replacing functionality
  - Better follows the maintainer guide

2024-07-24 02:10 UTC, data-queue commented
/azp run

2024-07-24 03:50 UTC, dg0yt reviewed
I'm sure I missed some issues.

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +)
Originally the file used GLOB. AFAICT this is prefered for port-local CMake build systems, in contrast to official CMake build system.
Can't this pattern be kept? Only the public headers need to be handled explicitly.

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +
Redundant.
```suggestion
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +)
Nitpick: Keep short statements short.
```suggestion
add_library(lua ${SRC_LIBLUA})
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +
Probably redundant.
```suggestion
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +        target_link_libraries(lua m)
To be really "modern", all link statement should use INTERFACE/PUBLIC/PRIVATE.
```suggestion
        target_link_libraries(lua PRIVATE m)
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +)
```suggestion
target_link_libraries(lua PRIVATE ${CMAKE_DL_LIBS})
```
Maybe this should be moved to where `LUA_USE_DLOPEN` is handled?

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    endif()
Nitpick:
```suggestion
    if (APPLE OR NOT CMAKE_DL_LIBS STREQUAL "")
        target_compile_definitions(lua PUBLIC LUA_USE_DLOPEN)
    endif()
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +if (INSTALL_TOOLS AND NOT SKIP_INSTALL_TOOLS)
Either A or NOT B.
```suggestion
if (INSTALL_TOOLS)
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    add_executable(unofficial::lua::lua-compiler ALIAS lua-compiler)
The build-time alias is not used in vcpkg.
```suggestion
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    endif()
I start to wonder why lua-compiler uses `SRC_LIBLUA` instead of simply linking `lua`.

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +            set(_LIB_READLINE_NAME readline)
Hm, readline has a vcpkg port, so lua needs a dependency on this port.
(And maybe it should be used for FreeBSD, too? This would simplify the port.)

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +        if (CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
```suggestion
        if (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +            if (_LIB_READLINE_NAME STREQUAL edit)
```suggestion
            if (_LIB_READLINE_NAME STREQUAL "edit")
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +        RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/tools/lua
Generally, do not use absolute destination paths with `install`:
```suggestion
        RUNTIME DESTINATION tools/lua
```
(It breaks `CMAKE_STAGING_PREFIX`. Not used in vcpkg.)

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    PUBLIC_HEADER   DESTINATION "${CMAKE_INSTALL_PREFIX}/include"
```suggestion
    RUNTIME         DESTINATION "bin"
    LIBRARY         DESTINATION "lib"
    ARCHIVE         DESTINATION "lib"
    INCLUDES        DESTINATION "include"
    PUBLIC_HEADER   DESTINATION "include"
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    DESTINATION "${CMAKE_INSTALL_PREFIX}/share/unofficial-lua"
```suggestion
    DESTINATION "share/unofficial-lua"
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    include(CMakeFindDependencyMacro)\n \
Unused.
```suggestion
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    INSTALL_DESTINATION "${CMAKE_INSTALL_PREFIX}/share/unofficial-lua"
```suggestion
    INSTALL_DESTINATION "share/unofficial-lua"
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/CMakeLists.txt
> +    DESTINATION "${CMAKE_INSTALL_PREFIX}/share/unofficial-lua"
```suggestion
    DESTINATION "share/unofficial-lua"
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/cpp/CMakeLists.txt
> +)
Depends on top-level `CMakeLists.txt`.
```suggestion
```

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/cpp/CMakeLists.txt
> +set(HDR_LIBLUA_CPP ${HDR_LIBLUA})
This might be the reason why the port doesn't allow to build the C lib and the C++ lib at the same time: There will be two libs exporting the same symbols.

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/cpp/CMakeLists.txt
> +set_source_files_properties(${SRC_LIBLUA_CPP} PROPERTIES LANGUAGE CXX)
So this makes the `.c` files being compiled with C++ :thinking:

2024-07-24 03:50 UTC, dg0yt commented on ports/lua/cpp/CMakeLists.txt
> +    endif()
```suggestion
    if (APPLE OR NOT CMAKE_DL_LIBS STREQUAL "")
        target_compile_definitions(lua-cpp PUBLIC LUA_USE_DLOPEN)
    endif()
```
And maybe the `if(UNIX)` is redundant.

2024-07-24 16:31 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    endif()
This comment is from before I started working on this port
`# compiler uses non-exported APIs, so must include sources directly.`

Trying to link with lua instead yields - 
```/usr/bin/ld: /.../buildtrees/lua/src/lua-5-292bcd51ee.clean/src/luac.c:306:(.text+0xe1e): undefined reference to `luaP_opmodes'```

2024-07-24 17:46 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +            set(_LIB_READLINE_NAME readline)
This is a good idea. I looked into this.

I modified the manifest to include the dependency and CMakeLists to bring it in:

```json
    "tools": {
      "description": "Builds Lua compiler and interpreter",
      "dependencies": [
        {
          "name": "readline",
          "platform": "!uwp"
        }
      ],
      "supports": "!ios"
    }
```
```cmake
    if (UNIX)
        find_package(PkgConfig REQUIRED)
        pkg_check_modules(readline REQUIRED IMPORTED_TARGET readline)
        target_link_libraries(lua-interpreter PRIVATE PkgConfig::readline)
    endif()

```

This works fine when building static libraries, but fails when building shared.

```
/usr/bin/ld: /.../vcpkg_installed/cool-vcpkg-custom-triplet/debug/lib/libreadline.so: undefined reference to `tputs'
```
The undefined references are from `libtinfo` which should come with the `ncurses` port pulled in by `readline-unix`. But it is only distributed when `ncurses` is built with `--with-termlib` [ref](https://github.com/void-linux/void-packages/issues/11718#issuecomment-492762471).

The vcpkg ncurses port does not enable --with-termlib:
```cmake
if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    list(APPEND OPTIONS
        --with-cxx-shared
        --with-shared    # "lib model"
        --without-normal # "lib model"
    )
endif()
```

2024-07-24 18:18 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +if (INSTALL_TOOLS AND NOT SKIP_INSTALL_TOOLS)
The logic was right, but I agree in spirit. It needs to be simplified. The SKIP_INSTALL_TOOLS option was used in the OPTIONS_DEBUG to skip the work if we are building DEBUG versions but honestly it builds so fast it doesn't really matter. I'll just remove it afterwards.

```cmake
...
    OPTIONS_DEBUG
       # -DSKIP_INSTALL_HEADERS=ON -- REMOVE THIS
       # -DSKIP_INSTALL_TOOLS=ON -- REMOVE THIS
)
vcpkg_cmake_install()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include") # INTRODUCE THIS
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/tools") # INTRODUCE THIS
```

2024-07-24 18:42 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +
Taking care of with portfile statement -> `file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")`

2024-07-24 18:56 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +)
Sure, moved.

2024-07-24 18:58 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +)
I suppose, but I've already went through the pain. I don't see the benefit in changing it back to GLOB now.

2024-07-24 18:59 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +        target_link_libraries(lua m)
Yeah fair enough.

2024-07-24 19:01 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    endif()
Previously, I kept it the original way because I thought it flowed better when reading the code. But I changed it to this now that I moved the `target_link_libraries(CMAKE_DL_LIBS)` down there.

2024-07-24 19:02 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    add_executable(unofficial::lua::lua-compiler ALIAS lua-compiler)
Removed aliases.

2024-07-24 19:03 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +        if (CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
Corrected the STREQUAL comparisons

2024-07-24 19:03 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +            if (_LIB_READLINE_NAME STREQUAL edit)
Corrected.

2024-07-24 19:03 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +        RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/tools/lua
Okay, good to know.

2024-07-24 19:04 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    PUBLIC_HEADER   DESTINATION "${CMAKE_INSTALL_PREFIX}/include"
Corrected.

2024-07-24 19:04 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    include(CMakeFindDependencyMacro)\n \
Very true.

2024-07-24 19:04 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    INSTALL_DESTINATION "${CMAKE_INSTALL_PREFIX}/share/unofficial-lua"
Corrected.

2024-07-24 19:04 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +    DESTINATION "${CMAKE_INSTALL_PREFIX}/share/unofficial-lua"
Changed.

2024-07-24 19:08 UTC, XJ-0461 commented on ports/lua/cpp/CMakeLists.txt
> +set(HDR_LIBLUA_CPP ${HDR_LIBLUA})
Idk, this is the way it was authored before so I didn't change it too much.

2024-07-24 19:12 UTC, XJ-0461 commented on ports/lua/cpp/CMakeLists.txt
> +    endif()
Yeah if (UNIX) is probably not necessary but hes just hanging out not hurting nothing so I kept him plus I think it reads a bit easier. Did change to `if (APPLE OR NOT CMAKE_DL_LIBS STREQUAL "")` though.

2024-07-24 19:50 UTC, XJ-0461 commented on ports/lua/cpp/CMakeLists.txt
> +)
Fair enough, changed.

2024-07-24 19:50 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +)
Made short statements shorter.

2024-07-24 19:51 UTC, XJ-0461 commented on ports/lua/CMakeLists.txt
> +
Changed.

2024-07-26 10:05 UTC, LilyWangLL requested changes

2024-07-26 16:05 UTC, XJ-0461 commented on ports/lua/vcpkg.json
> +  "port-version": 7,
Yes these changes are only for 5.3.5. I plan on updating 5.4.6, 5.4.7, and introducing 5.1.5 (its still popular because AFAIK it is compatible with LuaJit.

2024-07-26 16:26 UTC, XJ-0461 commented on ports/lua/portfile.cmake
>  file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/COPYRIGHT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
The COPYRIGHT file is provided with the port and not with the source distribution. Will update to `vcpkg_install_copyright(FILE_LIST "${CMAKE_CURRENT_LIST_DIR}/COPYRIGHT")`

2024-07-26 16:30 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +        -DLUA_RELEASE_VERSION="${VERSION}"
Done.

2024-07-26 16:31 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +    PATCHES vs2015-impl-c99.patch
Changed.

2024-07-26 16:33 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +if (INSTALL_TOOLS)
We provide the CMakeLists file and associated options with this port. But I understand. I will change it as a best practice.

2024-07-26 16:33 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +if (COMPILE_AS_CPP)
Changed.

2024-07-26 16:33 UTC, XJ-0461 commented on ports/lua/portfile.cmake
> +    SOURCE_PATH ${SOURCE_PATH}
Added.

2024-08-01 17:02 UTC, XJ-0461 commented
@LilyWangLL Can we follow up on this? I responded to the feedback from yall

2024-08-02 17:33 UTC, BillyONeal commented on ports/lua/vcpkg.json
> +  "port-version": 7,
At the moment we don't have infrastructure in place to effectively insert new versions 'in the middle' like this; I think it would be strange to users if they update their baseline and the version they get goes backwards. Internally we have discussed doing something like having a separate directory so that versions can be effectively inserted 'in the middle' of the registry even though we can't effectively test that, but thus far it's only discussion/theory.

2024-08-29 06:06 UTC, LilyWangLL commented
Close this PR because these fixes cannot be applied at the moment.

2024-08-29 06:06 UTC, closed without merging