[sdl2] Update to 2.30.6
microsoft/vcpkg pull request #40259
Opened 2024-08-03 21:33 UTC by AregevDev

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-08-04 00:39 UTC, bwrsandman commented
You might want to include this patch https://github.com/libsdl-org/SDL/commit/558630d59c2db73ac7c0c0cae000e4bee6ef42cf.patch in order to avoid #40268

2024-08-04 07:38 UTC, AregevDev commented
Is this fix still on master? Can't it wait for SDL's next release?

2024-08-04 12:02 UTC, bwrsandman commented
It's merged into master of sdl2 but it's a compilation error for that release so in any case it will need a patch.

2024-08-04 14:47 UTC, AregevDev commented
I see

2024-08-04 19:39 UTC, AregevDev commented
I applied the patch and SDL2 builds properly on arm64... I don't have a way to test it in an application though. I'll need to remove this patch in the next SDL2 release, right?

2024-08-04 20:01 UTC, bwrsandman commented
> I'll need to remove this patch in the next SDL2 release, right?
Yes most likely

I tested that it builds with nkd r27 and it does with the patch.

2024-08-05 03:10 UTC, jimwang118 requested changes

2024-08-05 03:10 UTC, jimwang118 commented on versions/s-/sdl2.json
> +    },
```suggestion
```

2024-08-05 06:05 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2024-08-05 06:29 UTC, jimwang118 submitted a review, later dismissed

2024-08-05 06:32 UTC, jimwang118 commented
All features passed with following triplets:

```
x64-windows
x64-windows-static
```

2024-08-06 21:48 UTC, data-queue commented
I'm not sure about the patch: the upstream patch doesn't apply cleanly since it seems the code around it has refactored significantly. I think it's better to either wait for a new `sdl2` release or just not fix the android NDK issue in this PR.

2024-08-06 23:50 UTC, bwrsandman commented
I can make a separate PR for the patch

2024-08-07 11:27 UTC, AregevDev commented
Yeah, sounds good. I'll revert the changes when I can.

2024-08-10 14:00 UTC, AregevDev commented
Do I need to add a `port-version`?

2024-08-10 21:06 UTC, erikyuzwa commented
@AregevDev - here's the PR for `2.30.5` - https://github.com/microsoft/vcpkg/pull/39710 - maybe that helps?

2024-08-11 11:39 UTC, dg0yt commented
> Do I need to add a `port-version`?

No (for `ports/sdl2/vcpkg.json`). Revision Zero of a new version doesn't need it.

2024-08-11 19:14 UTC, AregevDev commented
Seems ok now...

2024-08-16 02:01 UTC, data-queue approved these changes

2024-08-16 02:05 UTC, data-queue approved these changes

2024-08-16 02:05 UTC, merged