Hlslpp port (hlsl++ from https://github.com/redorav/hlslpp)
microsoft/vcpkg pull request #40400
Opened 2024-08-11 18:14 UTC by plekakis

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-08-11 18:28 UTC, plekakis commented
@microsoft-github-policy-service agree [company="default"]


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: microsoft-github-policy-service[bot] ***@***.***>
Sent: Sunday, August 11, 2024 7:14:36 PM
To: microsoft/vcpkg ***@***.***>
Cc: Pantelis Lekakis ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoft/vcpkg] Hlslpp port (hlsl++ from https://github.com/redorav/hlslpp) (PR #40400)


@plekakis<https://github.com/plekakis> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]


Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree


  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"


Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement (“Agreement”) is agreed to by the party signing below (“You”),
and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
“Project” means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org>).
“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”
“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase “Submission
containing materials of a third party:” followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
guidelines concerning Submissions.
  4.  Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
defenses of lack of personal jurisdiction and forum non-conveniens.
  5.  Entire Agreement/Assignment. This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or oral, between
the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

—
Reply to this email directly, view it on GitHub<https://github.com/microsoft/vcpkg/ [...]

2024-08-11 18:30 UTC, plekakis commented
@microsoft-github-policy-service agree

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: microsoft-github-policy-service[bot] ***@***.***>
Sent: Sunday, August 11, 2024 7:29:20 PM
To: microsoft/vcpkg ***@***.***>
Cc: Pantelis Lekakis ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoft/vcpkg] Hlslpp port (hlsl++ from https://github.com/redorav/hlslpp) (PR #40400)


@plekakis<https://github.com/plekakis> the command you issued was incorrect. Please try again.

Examples are:

@microsoft-github-policy-service agree


and

@microsoft-github-policy-service agree company="your company"


—
Reply to this email directly, view it on GitHub<https://github.com/microsoft/vcpkg/pull/40400#issuecomment-2282847899>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABL7J5PJ2ZPSJF3IAAZZT6TZQ6UQBAVCNFSM6AAAAABMK6L4VWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBSHA2DOOBZHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-08-13 01:56 UTC, jimwang118 requested changes

2024-08-13 01:56 UTC, jimwang118 commented on ports/hlslpp/hlslpp-config.cmake
> +set(hlslpp_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../include/hlslpp/include")
```suggestion
set(hlslpp_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../include/hlslpp/include")

```

2024-08-13 01:56 UTC, jimwang118 commented on ports/hlslpp/portfile.cmake
> +configure_file("${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)
```suggestion
configure_file("${CMAKE_CURRENT_LIST_DIR}/usage" "${CURRENT_PACKAGES_DIR}/share/${PORT}/usage" COPYONLY)

```

2024-08-13 01:56 UTC, jimwang118 commented on ports/hlslpp/usage
> +target_include_directories(main PUBLIC ${hlslpp_INCLUDE_DIRS})
```suggestion
target_include_directories(main PUBLIC ${hlslpp_INCLUDE_DIRS})

```

2024-08-14 01:51 UTC, jimwang118 approved these changes

2024-08-14 01:54 UTC, jimwang118 requested changes

2024-08-14 01:54 UTC, jimwang118 commented on ports/hlslpp/vcpkg.json
> +  "port-version": 2,
```suggestion
```
The newly added port does not require this keyword.

2024-08-14 01:54 UTC, jimwang118 commented on versions/h-/hlslpp.json
> +    },
```suggestion
```

2024-08-14 01:54 UTC, jimwang118 commented on ports/hlslpp/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```suggestion
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
```

2024-08-14 01:54 UTC, jimwang118 commented
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

2024-08-14 06:47 UTC, dg0yt requested changes
Most comments don't add value to the command that follow. Just remove them.

The CMake config package is not provided by upstream. The package-name should be prefixed with `unofficial-`.  
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#add-cmake-exports-in-an-unofficial--namespace  
And even for a header-only package, it might make sense to provide an imported target instead of variables.

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/usage
> +hlslpp provides header-only CMake targets:
It doesn't provide targets.
```suggestion
hlslpp provides a CMake package:
```

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/usage
> +target_include_directories(main PUBLIC ${hlslpp_INCLUDE_DIRS})
```suggestion
  find_package(hlslpp CONFIG REQUIRED)
  target_include_directories(main PUBLIC ${hlslpp_INCLUDE_DIRS})
```
As applied by vpckg tool heuristics.

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/hlslpp-config.cmake
> +set(hlslpp_VERSION 3.5)
```suggestion
set(hlslpp_VERSION "@VERSION@")
```
and install with `configure_file ... @ONLY`. So it doesn't need updating again.

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/hlslpp-config.cmake
> +# Specify include directories
```suggestion
```

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/hlslpp-config.cmake
> +set(hlslpp_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../include/hlslpp/include")
Wouldn't it be nice to place includes in `${CMAKE_CURRENT_LIST_DIR}/../../include/hlslpp`?

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/portfile.cmake
> +
```suggestion
# vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

```

2024-08-14 06:47 UTC, dg0yt commented on ports/hlslpp/portfile.cmake
> +file(INSTALL "${SOURCE_PATH}/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include/hlslpp/")
Maybe
```suggestion
file(INSTALL "${SOURCE_PATH}/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include/")
file(RENAME "${CURRENT_PACKAGES_DIR}/include/include" "${CURRENT_PACKAGES_DIR}/include/hlslpp")
```

2024-08-15 08:42 UTC, plekakis commented
Apologies for all the above, this is my first vcpkg contribution and I am learning still.
I'm talking to the author of hlslpp and doing this in his place instead, so I would still like this to be an official port - bear with me and will sort it all out properly.

2024-08-19 02:10 UTC, jimwang118 approved these changes, later dismissed

2024-08-19 02:37 UTC, jimwang118 commented
Usage test pass with following triplet:

```
x64-windows
```

2024-08-19 03:50 UTC, dg0yt commented on ports/hlslpp/hlslpp-config.cmake
> +target_include_directories(hlslpp INTERFACE "${CMAKE_CURRENT_LIST_DIR}/../../include/hlslpp")
The missing piece was the `IMPORTED` keyword.
And as long as it isn't provided by upstream, it package name and target name shall be prefixed as `unofficial`.
```suggestion
add_library(unofficial::hlslpp::hlslpp INTERACE IMPORTED)
target_include_directories(unofficial::hlslpp::hlslpp INTERFACE "${CMAKE_CURRENT_LIST_DIR}/../../include/hlslpp")
```
installed as `share/unofficial-hlslpp/unofficial-hlslpp-config.cmake`.

2024-08-19 03:51 UTC, dg0yt commented on ports/hlslpp/usage
> +  target_link_libraries(main PUBLIC hlslpp::hlslpp)
```suggestion
  find_package(unofficial-hlslpp CONFIG REQUIRED)
  target_link_libraries(main PUBLIC unofficial::hlslpp::hlslpp)
```

2024-08-23 10:26 UTC, merged