[exiv2] Update to 0.28.3, fixes, cleanup
microsoft/vcpkg pull request #40476
Opened 2024-08-15 16:54 UTC by dg0yt

2024-08-20 07:15 UTC, FrankXie05 requested changes

2024-08-20 07:15 UTC, FrankXie05 commented on ports/exiv2/portfile.cmake
> +        #fix-brotli.patch
```suggestion
```

2024-08-20 17:19 UTC, dg0yt commented on ports/exiv2/portfile.cmake
> +        #fix-brotli.patch
Done.

2024-08-21 06:02 UTC, FrankXie05 approved these changes

2024-08-21 06:30 UTC, merged

2024-10-09 11:58 UTC, m-kuhn commented on ports/exiv2/dependencies.diff
> ++  find_dependency(expat)
@dg0yt this seems to be causing issues for me

> The package name passed to find_package_handle_standard_args (EXPAT) does
  not match the name of the calling package (expat).  This can lead to
  problems in calling code that expects find_package result variables
  (e.g., _FOUND) to follow a certain pattern.

did you have a specific reason to change capitalization here?

2024-10-09 12:32 UTC, dg0yt commented on ports/exiv2/dependencies.diff
> ++  find_dependency(expat)
@m-kuhn 
- The change in capitalization is intentational and necessary, because that's how the config packages is named.
- The call stack will tell you more: I guess you run into a Find module on a case insensitive filesystem.
- So the fix is to add  `CONFIG`.