Update gtsam port version 4.2a9#3
microsoft/vcpkg pull request #40655
Opened 2024-08-26 16:34 UTC by andre-nguyen

Add a vcpkg feature which provides access to the cmake option `GTSAM_BUILD_WITH_MARCH_NATIVE` which in turn controls building with `-march=native`. This is important when the consuming application has native instructions enabled. 

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-08-26 16:51 UTC, talregev commented
you can try to update the port to 4.2

2024-08-26 17:00 UTC, valgur commented
I would recommend adding
```cmake
set(VCPKG_C_FLAGS -march=native) 
set(VCPKG_CXX_FLAGS -march=native) 
```
to your triplet file to enable the flag globally instead of exposing this as a recipe feature.

2024-08-27 15:02 UTC, talregev commented on versions/g-/gtsam.json
> +    },
You should remove 
```
    {
      "git-tree": "c04737be9e5ba4b2f85a80709cd1a146b086dc49",
      "version-string": "4.2a9",
      "port-version": 3
    },
```

2024-08-27 15:03 UTC, talregev commented
> I would recommend adding
> 
> ```cmake
> set(VCPKG_C_FLAGS -march=native) 
> set(VCPKG_CXX_FLAGS -march=native) 
> ```
> 
> to your triplet file to enable the flag globally instead of exposing this as a recipe feature.

In my opinion it should stay as a feature like he already dose.

2024-08-27 15:28 UTC, andre-nguyen commented on versions/g-/gtsam.json
> +    },
Thank you!!

Hopefully this is now correct

2024-08-27 15:30 UTC, andre-nguyen commented
@valgur I will leave the option there since it is an available option on the gtsam side.
I will also use your suggestion of editing my triplet file.

2024-08-28 03:09 UTC, Cheney-W commented on ports/gtsam/portfile.cmake
>      HEAD_REF master
```suggestion
    HEAD_REF develop
```
The default branch of gtsam is `develop` instead of `master`.

2024-08-28 14:19 UTC, andre-nguyen commented on ports/gtsam/portfile.cmake
>      HEAD_REF master
yes, thank you for pointing that out

2024-08-28 14:36 UTC, talregev commented
@andre-nguyen Change to not draft to notify you are ready for review.

2024-08-29 02:09 UTC, Cheney-W approved these changes, later dismissed

2024-08-29 06:45 UTC, vicroms requested changes

2024-08-29 14:05 UTC, talregev commented on ports/gtsam/portfile.cmake
> +
@andre-nguyen Thank you for your work!
Please change the title that fit the PR, that it only update.

2024-08-30 06:51 UTC, Cheney-W approved these changes

2024-09-03 20:34 UTC, vicroms approved these changes

2024-09-03 20:34 UTC, merged