[ls-qpack] Detect xxhash with pkgconf as upstream
microsoft/vcpkg pull request #40751
Opened 2024-09-02 01:27 UTC by talregev

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2024-09-02 01:28 UTC, talregev commented
upstream detect xxHash with pkgconf:
https://github.com/litespeedtech/ls-qpack/blob/95c7b9cc05787357335b93ad6f001cd6d1eddf22/CMakeLists.txt#L36-L39

2024-09-02 01:29 UTC, talregev commented
Please check usage both windows and linux. Thank you in advance 🙏🏻🙏🏻🙏🏻

2024-09-02 07:06 UTC, FrankXie05 commented
> Please check usage both windows and linux. Thank you in advance 🙏🏻🙏🏻🙏🏻

The usage has been tested successfully locally.

2024-09-03 18:27 UTC, vicroms requested changes

2024-09-03 18:27 UTC, vicroms commented on ports/ls-qpack/portfile.cmake
> +"find_package(PkgConfig REQUIRED)
```suggestion
"include(CMakeFindDependencyMacro)
find_dependency(PkgConfig)
```

2024-09-03 18:38 UTC, talregev commented on ports/ls-qpack/portfile.cmake
> +"find_package(PkgConfig REQUIRED)
Done.

2024-09-03 20:41 UTC, vicroms approved these changes

2024-09-03 20:41 UTC, merged

2024-09-04 08:00 UTC, dg0yt commented
This change isn't beneficial: It creates a dependency on the presence of a `pkg-config` tool for consuming ls-qpack despite the fact that official cmake config is available also for xxhash.

2024-09-04 08:13 UTC, talregev commented
@dg0yt What are you suggesting to do?

2024-09-04 08:31 UTC, dg0yt commented
cmake in, cmake out.
Use cmake for xxhash import and export in ls-qpack.

2024-09-04 09:26 UTC, talregev commented
Do you want to do it?
If you want to do it, also create a PR that export cmake export.
So we can use official cmake export.

2024-09-04 11:00 UTC, dg0yt commented
My backlog doesn't need extra stuff. (And official CMake is extra stuff.)