[bit7z] new port
microsoft/vcpkg pull request #40889
Opened 2024-09-10 02:20 UTC by msclock

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

2024-09-10 10:58 UTC, Cheney-W commented on ports/bit7z/portfile.cmake
> +        ${FEATURE_OPTIONS}
```suggestion
        -DBIT7Z_BUILD_TESTS=OFF
        -DBIT7Z_BUILD_DOCS=OFF
        ${FEATURE_OPTIONS}
```

2024-09-10 10:59 UTC, Cheney-W commented
Can these features of this port be enabled simultaneously?

2024-09-11 01:12 UTC, msclock commented
> Can these features of this port be enabled simultaneously?

Of course, all features in the vcpkg.json are from the bit7z build [options](https://github.com/rikyoz/bit7z/wiki/Building-the-library#%EF%B8%8F-build-options)

2024-09-11 04:21 UTC, dg0yt commented
> > Can these features of this port be enabled simultaneously?
> 
> all features in the vcpkg.json are from the bit7z build [options](https://github.com/rikyoz/bit7z/wiki/Building-the-library#%EF%B8%8F-build-options)

The origin is obvious, but this doesn't answer the question.

Some "features" belong to the toolchain: `link-libcpp`, `static-runtime`.

2024-09-11 05:58 UTC, msclock commented
> Some "features" belong to the triplet and toolchain: `link-libcpp`, `static-runtime`.

@dg0yt Yep, it can customize ports in triplets or set flags in toolchains to do the same things. And it needs more comprehensive understand on the build options of bit7z.

2024-09-11 07:00 UTC, dg0yt requested changes

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/fix_install.patch
> + target_compile_definitions( ${LIB_TARGET} PRIVATE UNICODE _UNICODE )
```suggestion
```

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/fix_install.patch
> ++        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
Isn't this covered by `PUBLIC_HEADER` installation?

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Usually wrong for non-windows.

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
Looks like a negative feature. Should this be a positive default-feature?

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
Do these feature change the API?

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    }
What is used when it is off?

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
Not sure if this a reasonable feature.

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/fix_dependency.patch
> ++target_link_libraries( ${LIB_TARGET} PRIVATE 7zip::7zip )
Personal preference: locality of changes
```suggestion
 # dependencies
-include( cmake/Dependencies.cmake )
+find_package(7zip CONFIG REQUIRED)
+add_library(7zip ALIAS 7zip::7zip)
 
 # 7-zip source code
 target_link_libraries( ${LIB_TARGET} PRIVATE 7-zip )
```
Note that using an imported target here will need `find_dependency(7zip CONFIG)` in exported cmake config.

2024-09-11 07:00 UTC, dg0yt commented on ports/bit7z/fix_dependency.patch
> ++endif()
Is `USE_STANDARD_FILESYSTEM` introduced by this patch?
(Why would we add this in the port instead of upstream?)

2024-09-11 07:13 UTC, msclock commented on ports/bit7z/fix_dependency.patch
> ++endif()
> Is USE_STANDARD_FILESYSTEM introduced by this patch?

2024-09-11 07:19 UTC, msclock commented on ports/bit7z/fix_dependency.patch
> ++target_link_libraries( ${LIB_TARGET} PRIVATE 7zip::7zip )
```
 # dependencies
-include( cmake/Dependencies.cmake )
+find_package(7zip CONFIG REQUIRED)
+add_library(7-zip ALIAS 7zip::7zip) <--- alias to 7-zip
 
 # 7-zip source code
 target_link_libraries( ${LIB_TARGET} PRIVATE 7-zip )
```
Is that right?

2024-09-11 07:28 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
bit7z localized std::filesystem/ghc::filesystem itself to be compatibility for pre-cxx17 standards. But it provides the option to use thirdparth ghc always.

2024-09-11 07:37 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    }
```
#ifdef BIT7Z_USE_SYSTEM_CODEPAGE
#define CODEPAGE CP_ACP <-- prefer to local charsets
#define CODEPAGE_WC_FLAGS WC_NO_BEST_FIT_CHARS
#else
#define CODEPAGE CP_UTF8
#define CODEPAGE_WC_FLAGS 0
#endif
```
Default to utf-8. But upstream recommend to close it(Off), otherwise, program is limited to in the set of characters it can pass to and read from bit7z.

2024-09-11 07:41 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
Yep, bit7z provides a api string type tstring(from string/wstring) based on the option.

2024-09-11 07:45 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
It will check passwords by default when the feature is OFF. And I consider it express its meanings literally. 🫤

2024-09-11 07:50 UTC, msclock commented on ports/bit7z/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Dose it not work for non-windows?😓I thoght it work for all platforms.

2024-09-11 07:54 UTC, msclock commented on ports/bit7z/fix_install.patch
> ++        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
I have commented the PUBLIC_HEADRE for install instrutions simplicity and add explicit public header installation instructions.

2024-09-11 08:01 UTC, msclock commented on ports/bit7z/fix_install.patch
> + target_compile_definitions( ${LIB_TARGET} PRIVATE UNICODE _UNICODE )
WIP for practice...

2024-09-11 18:18 UTC, dg0yt commented on ports/bit7z/fix_install.patch
> + target_compile_definitions( ${LIB_TARGET} PRIVATE UNICODE _UNICODE )
If the PR is WIP, mark it as draft.

2024-09-11 18:21 UTC, dg0yt commented on ports/bit7z/fix_install.patch
> ++        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
I want to know it it is *really* necessary. Upstream seems to have an idea which headers are public. Installing all headers overrides upstream's choice.

2024-09-11 18:22 UTC, dg0yt commented on ports/bit7z/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
It works by limiting user's choice. It is usually wrong to limit user's choice. If I install bit7z:x64-linux-dynamic, I expect a shared object, but this line makes the port build a static archive.

2024-09-11 18:28 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
> It will check passwords by default when the feature is OFF.

That is why a suggest "default-feature".

> I consider it express its meanings literally.

"Literally" is inappropriate when it conflicts with vcpkg guidelines. Guidelines say that features should be additive. IMO this port needs 
- a feature "zip-ascii-pwd-check"
- that feature being listed in `default-features` (if the check should really be default-enabled)
- that feature being hooked up in `vcpkg_check_features` via the `INVERTED_FEATURES` list.

2024-09-11 18:30 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
If ports can strongly depend on the default interface, and activating the feature will break the build of these ports, then it is not an acceptable feature.

2024-09-11 18:31 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    }
Uh.

2024-09-11 19:20 UTC, rikyoz commented on ports/bit7z/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
Hi, bit7z's author here. The library only supports static linking, there's no dynamic flavor.
I'm not familiar with vcpkg, so I'm not sure thi is the best way to handle such cases, but reading the documentation [here](https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_check_linkage#only_static_library) and [here](https://learn.microsoft.com/en-gb/vcpkg/users/triplets#vcpkg_library_linkage) it seems to make sense to use `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`.

2024-09-11 19:36 UTC, rikyoz commented on ports/bit7z/vcpkg.json
> +    }
Just to clarify a bit the encoding options available in bit7z:
- Default (`BIT7Z_USE_NATIVE_STRING=OFF` and `BIT7Z_USE_SYSTEM_CODEPAGE=OFF`): bit7z uses `std::string` in its API and treats it as UTF-8 encoded.
- `BIT7Z_USE_NATIVE_STRING=ON`: bit7z uses `std::wstring` (UTF-16) in its API.
- `BIT7Z_USE_SYSTEM_CODEPAGE=ON`: bit7z uses `std::string` in its API and treats it as encoded using the system codepage encoding.

When bit7z uses `std::string` (default setting, or when `BIT7Z_USE_SYSTEM_CODEPAGE=ON`), it must internally perform string conversions from/to UTF-16 wide strings, as 7-Zip only uses this string type in its interfaces.
Such conversions are of course not needed if `BIT7Z_USE_NATIVE_STRING=ON`.

I usually advise against using the `BIT7Z_USE_SYSTEM_CODEPAGE` option, as system codepage encodings are usually limited in the characters they can represent (unlike UTF-8 or UTF-16).

2024-09-11 19:58 UTC, rikyoz commented on ports/bit7z/vcpkg.json
> +    },
To clarify this as well.
Bit7z uses `std::filesystem` if the compiler supports it, otherwise it reverts to using the `ghc-filesystem` library.
This usage is internal to the library in any case.
Bit7z only uses strings in its API to handle paths, at least for now.
For some reasons, there are actually some semi-public API functions that take filesystem's paths, but they can only be used if the program using bit7z is compiled using the C++17 standard. And the user is not expected to use them.

> ghc-fileystem also seems to active make additional choices about encoding (prefering utf-8)

Since v1.5.0, `ghc::filesystem` by default follows the C++17 standard and uses `wchar_t` and `std::wstring` on Windows, so it uses UTF-16.

2024-09-12 01:14 UTC, msclock commented on ports/bit7z/fix_install.patch
> ++        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
I see, and follow upstream selection whenever possible.

2024-09-12 01:25 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
But the advise does against bit7z default behaviors on the decision whether it checks passwords.

🤔 I'm not sure it is a good idea.

2024-09-12 01:39 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
> activating the feature will break the build of these port

It does happens on this changes. So for stability, I will remove features which impact api string type.

2024-09-12 01:43 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    }
Account for stability, I would like to remove featurs use_native_string/use_system_codepage and treat it as UTF-8 encoded always.

2024-09-12 01:49 UTC, msclock commented on ports/bit7z/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
So the instruction is correct?

2024-09-12 01:58 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
Got it, before cxx17, use strings in APIs, and after cxx17, filesystem's api can be used. 

Then this feature is not necessary.

2024-09-12 04:05 UTC, dg0yt commented on ports/bit7z/portfile.cmake
> +vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
This is correct when the "library only supports static linking". I wanted this to be confirmed for non-Windows.

2024-09-12 04:07 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
No, there is no contradiction. The positive default-on feature is equivalent to the negative default-off feature.

2024-09-12 04:14 UTC, dg0yt commented on ports/bit7z/fix_dependency.patch
> ++target_link_libraries( ${LIB_TARGET} PRIVATE 7zip::7zip )
Yeah. This is more a nit-pick here. It becomes more useful in larger packages when you have many instances of target_link_libraries. And in particular when updating such patches.

(Actually the ALIAS command is for cases like the internal build of 7zip, so that consumers could use the namespaced form regardless of how 7zip is provided. This is not relevant for the port ATM, but it could be considered upstream.)

2024-09-13 06:07 UTC, Cheney-W approved these changes

2024-09-13 09:26 UTC, Cheney-W requested changes

2024-09-13 09:26 UTC, Cheney-W commented on ports/bit7z/unofficial-bit7z-config.cmake.in
> +
```suggestion

include(CMakeFindDependencyMacro)

```

2024-09-13 09:55 UTC, dg0yt commented on ports/bit7z/unofficial-bit7z-config.cmake.in
> +find_dependency(ghc_filesystem CONFIG)
For proper CMake config search mode:
```suggestion
find_dependency(7zip CONFIG)
find_dependency(ghc_filesystem CONFIG)

include("${CMAKE_CURRENT_LIST_DIR}/unofficial-bit7z-targets.cmake")
```
(Don't create targets before finding the dependencies.)

2024-09-14 07:52 UTC, Cheney-W approved these changes, later dismissed

2024-09-18 01:08 UTC, msclock commented
@dg0yt @rikyoz Awaiting requested reviews

2024-09-18 20:31 UTC, BillyONeal commented on ports/bit7z/fix_dependency.patch
> ++    if(NOT USE_STANDARD_FILESYSTEM OR NOT STANDARD_FILESYSTEM_COMPILES)
Since it seems like we are forcing `ghc_filesystem` on, can the patch be made more minimal by not including this if?

2024-09-19 03:06 UTC, msclock commented on ports/bit7z/fix_dependency.patch
> ++    if(NOT USE_STANDARD_FILESYSTEM OR NOT STANDARD_FILESYSTEM_COMPILES)
I consider it is enough simple, and upstream uses those conditions in another cmake module to add `ghc_filesystem` as its dependency.🫤

2024-09-19 03:25 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
Still a little confused. Dose it mean it is suitable to use overlay ports instead of features if an option affects the same api.🤔

2024-09-19 18:45 UTC, BillyONeal commented on ports/bit7z/vcpkg.json
> +    },
It's always acceptable for someone to use an overlay port if they disagree with configuration choices made in the curated registry. That's less a statement of the system we'd like to have a more a statement of the system we have.

The features system is designed strongly around "turning a feature on is always safe". For instance, port A that depends on C[featurea] and port B that depends on C[featureb], we assume there is no problem in giving the user A B C[featurea,featureb], and in this condition it is not possible to say "no, I don't want featurea". This is why we have the 'do not use features to implement alternatives' rule: if used as a general configuration bit where a user might need to require that it is off, the features feature is not designed for that and leaves that user unhappy. We prefer to not advertise a configuration like that that we can't really represent well and point such users at making their own overlays instead.

2024-09-19 19:19 UTC, rikyoz commented on ports/bit7z/vcpkg.json
> +    },
I'm confused too :sweat_smile:. The vcpkg documentation says that `features must be treated as additive functionality`, and [more specifically](https://learn.microsoft.com/en-us/vcpkg/concepts/features):

> Features represent sets of functionality, behavior, and dependencies that can be selectively added to a package or project upon installation.
>
> By design, features should follow these principles:
>
> - Additive: enabling a feature should provide new functionality otherwise missing from the package without disabling any other functionality.
> - Non-exclusive: enabling a feature should not prevent other features from being installed.

Both `auto-prefix-long-paths` and `path-sanitization` are additive options in bit7z: by default, the library does not automatically prefix long paths, and it does not perform path sanitization.
Even when these options are enabled, the API of the library doesn't change at all: these options only change the internal behavior of the library, _adding_ support for long paths or sanitization of extracted paths. 
Finally, both these options are non-exclusive: any combination of them can be used.

So according to this part of the documentation, it seems reasonable to me to treat them as features.

But I guess the problem is semantic, and as a non-native English speaker I may be missing some details. 🤔

2024-09-19 20:36 UTC, BillyONeal commented on ports/bit7z/vcpkg.json
> +    },
>Even when these options are enabled, the API of the library doesn't change at all: these options only change the internal behavior of the library, adding support for long paths or sanitization of extracted paths.

What do you do as a user if you don't want this sanitization to happen?

2024-09-20 02:45 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
@BillyONeal @rikyoz  If I understand correctly, features passed as options in vcpkg could bring more additive public api or more additive public structures that means it is not safe to act as a feature in vcpkg port dependencies chain when an option changes a api internally.

@rikyoz It seems only `auto-format` and `regex-matching` are acceptable features. Other options could be passed by default in vcpkg portfile. And becasuse these options all are OFF by default and which options do you think are recommended to set ON in the porfile of vcpkg. I personally condsier the below is suitable:
```
-DBIT7Z_AUTO_PREFIX_LONG_PATHS=ON
-DBIT7Z_DISABLE_ZIP_ASCII_PWD_CHECK=OFF
-DBIT7Z_PATH_SANITIZATION=ON
-DBIT7Z_DISABLE_USE_STD_FILESYSTEM=OFF
-DBIT7Z_USE_STD_BYTE=OFF
-DBIT7Z_USE_NATIVE_STRING=OFF
-DBIT7Z_USE_SYSTEM_CODEPAGE=OFF
-DBIT7Z_BUILD_TESTS=OFF
-DBIT7Z_BUILD_DOCS=OFF
```

2024-09-20 07:01 UTC, rikyoz commented on ports/bit7z/vcpkg.json
> +    },
> What do you do as a user if you don't want this sanitization to happen?

As a user, I would not enable the feature, as I don't need it.

By the way, I think that the "enables or disables" in the feature description might be a bit misleading in this context. The description is taken from the original CMake option, which can be set `OFF` or `ON`. In the context of vcpkg, it would probably be better to use only "enables", if enabling the feature is equivalent to setting the corresponding CMake option to `ON`.

> @BillyONeal @rikyoz If I understand correctly, features passed as options in vcpkg could bring more additive public api or more additive public structures that means it is not safe to act as a feature in vcpkg port dependencies chain when an option changes its behaviors of a api internally.
> 
> @rikyoz It seems only `auto-format` and `regex-matching` are acceptable features. Other options could be passed by default in vcpkg portfile. And becasuse these options all are OFF by default and which options do you think are recommended to set ON in the porfile of vcpkg. I personally condsier the below is suitable:

If this is correct, then I am afraid that even `auto-format` cannot be accepted a feature, as it is not additive at the public API level: this option changes the signature of some constructors so that the archive format parameter has `BitFormat::Auto` as default value; when this option is turned off, the same parameter doesn't have a default value.
`regex-matching` seems an acceptable feature though, as it simply adds more methods to classes.

2024-09-23 00:49 UTC, msclock commented on ports/bit7z/vcpkg.json
> +    },
> even auto-format cannot be accepted a feature

@rikyoz  I see.🫤 I would readjust options:
```
-DBIT7Z_AUTO_FORMAT=ON
-DBIT7Z_AUTO_PREFIX_LONG_PATHS=ON
-DBIT7Z_DISABLE_ZIP_ASCII_PWD_CHECK=OFF
-DBIT7Z_PATH_SANITIZATION=ON
-DBIT7Z_DISABLE_USE_STD_FILESYSTEM=OFF
-DBIT7Z_USE_STD_BYTE=OFF
-DBIT7Z_USE_NATIVE_STRING=OFF
-DBIT7Z_USE_SYSTEM_CODEPAGE=OFF
-DBIT7Z_BUILD_TESTS=OFF
-DBIT7Z_BUILD_DOCS=OFF
```

2024-09-23 05:42 UTC, dg0yt commented on ports/bit7z/vcpkg.json
> +    },
> If this is correct, then I am afraid that even `auto-format` cannot be accepted a feature, as it is not additive at the public API level: this option changes the signature of some constructors so that the archive format parameter has `BitFormat::Auto` as default value; when this option is turned off, the same parameter doesn't have a default value.

IIUC this would not have been a problem:  
Code which doesn't depend on the feature would always supply the parameter.
Enabling the feature doesn't remove this interface, so that source keeps building.

But I'm happy with having one feature less. Users might still opt out via triplet customization.

2024-09-23 09:50 UTC, Cheney-W approved these changes, later dismissed

2024-09-23 11:18 UTC, rikyoz approved these changes

2024-09-23 21:10 UTC, JavierMatosD requested changes
LGTM with those nitpicks :)

Thank you for the contribution! Feel free to mark the PR "Ready for Review" once you have responded to my comments and/or made any relevant changes.

2024-09-24 02:05 UTC, msclock commented
> Can you explain why commenting our PUBLIC_HEADERS was needed?

@JavierMatosD I just make easiest changes I think, and are there better ways to handle it🤔

2024-09-24 03:05 UTC, msclock commented
I have switched to set_target_properties with PUBLIC_HEADER to conform to upstream public headers. And it is more accurate in some way.

2024-09-24 06:36 UTC, msclock commented on ports/bit7z/fix_install.patch
> ++        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
Upstream dose have headers explicitly and I have siwtched to PUBLIC_HEADERS installation now.

2024-09-24 13:08 UTC, msclock commented on ports/bit7z/fix_dependency.patch
> ++    if(NOT USE_STANDARD_FILESYSTEM OR NOT STANDARD_FILESYSTEM_COMPILES)
Yep, it is redundant.

2024-09-24 14:51 UTC, JavierMatosD requested changes

2024-09-24 14:51 UTC, JavierMatosD commented on ports/bit7z/fix_install.patch
> ++set_target_properties( ${LIB_TARGET} PROPERTIES PUBLIC_HEADER "${_includes}")
I think this can be reduced to simply
```suggestion
+set_target_properties(${LIB_TARGET} PROPERTIES PUBLIC_HEADER "${PUBLIC_HEADERS}")
```

2024-09-24 16:41 UTC, msclock commented on ports/bit7z/fix_install.patch
> ++set_target_properties( ${LIB_TARGET} PROPERTIES PUBLIC_HEADER "${_includes}")
I tried this change before And it failed to install headers locally. But now this way works🤔

2024-09-24 17:02 UTC, JavierMatosD approved these changes

2024-09-24 17:02 UTC, merged