[irrlicht] Fix build error under linux
microsoft/vcpkg pull request #41073
Opened 2024-09-19 09:08 UTC by jimwang118

One of the fixes for the https://github.com/microsoft/vcpkg/issues/32398 issue.
The following error occurs when installing irrlicht[core,tools]:x64-linux.
```
/usr/bin/ld: /lib/x86_64-linux-gnu/libfontconfig.so.1: error adding symbols: DSO missing from command line
/mnt/vcpkg/buildtrees/irrlicht/src/irrlicht-1-633b25421b.clean/tools/IrrFontTool/newFontTool/CFontTool.cpp:407:(.text+0x102): undefined reference to `XftInitFtLibrary' 
/usr/include/X11/Xft/Xft.h:40:10: fatal error: ft2build.h: No such file or directory
   40 | #include <ft2build.h>
      |          ^~~~~~~~~~~~

```
Add tools feature to compile missing dependencies.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [ ] ~~When updating the upstream version, the `"port-version"` is reset (removed from `vcpkg.json`).~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

The features passed with following triplets:

```
x64-windows
x64-linux
```
Usage test passed with following triplet:
`x64-windows`

2024-09-20 02:47 UTC, MonicaLiu0311 submitted a review, later dismissed

2024-09-20 05:21 UTC, dg0yt commented
Where is the actual change? I only see whitespace changes.

2024-09-20 05:25 UTC, dg0yt commented
Note that the original problem might be hard to solve in vcpkg at the moment:

Xft is a system lib, built with system freetype (shared objects). Mixing vcpkg freetype and system freetype is ... fragile at least.

2024-09-24 02:23 UTC, jimwang118 commented
> Note that the original problem might be hard to solve in vcpkg at the moment:
> 
> Xft is a system lib, built with system freetype (shared objects). Mixing vcpkg freetype and system freetype is ... fragile at least.

Use `freetype` and `Fontconfig` in vcpkg under Linux. However, `libxft` only uses system packages under Linux, so users need to be prompted to install it.

2024-09-24 06:58 UTC, dg0yt requested changes

2024-09-24 06:58 UTC, dg0yt commented on ports/irrlicht/CMakeLists.txt
> +    if(UNIX)
`UNIX` includes Android and macOS. I don't think that's right.

2024-09-24 06:58 UTC, dg0yt commented on ports/irrlicht/vcpkg.json
> +    "pkgconf",
This is not the right way to provide `pkg-config`.
I give the instructions 6 times a year, and I start to get tired.

2024-09-24 06:58 UTC, dg0yt commented on ports/irrlicht/vcpkg.json
> +        "libxft"
IIUC these dependencies should be subject to a `platform` expression.

2024-10-28 07:25 UTC, dg0yt requested changes

2024-10-28 07:25 UTC, dg0yt commented on ports/irrlicht/CMakeLists.txt
> +        target_link_libraries(FontTool      Irrlicht ${XFT_LIBRARIES}  Freetype::Freetype Fontconfig::Fontconfig)
Say "Hello!" to ABI mismatch at runtime!

2024-10-28 07:25 UTC, dg0yt commented on ports/irrlicht/vcpkg.json
> +    },
Do not use `pkgconf` at all.
There is `vcpkg_find_acquire_program(PKGCONFIG)`.

2024-10-28 07:27 UTC, jimwang118 commented on ports/irrlicht/vcpkg.json
> +    },
Ok, thanks for your suggestion.

2024-11-28 01:01 UTC, BillyONeal reviewed
I believe @dg0yt is correct and this is incorrectly trying to mix and match system libs with vcpkg libs.

2024-12-05 02:56 UTC, MonicaLiu0311 commented
Is there any new progress?

2024-12-05 08:19 UTC, jimwang118 commented
I will continue to follow up.

2024-12-05 08:29 UTC, MonicaLiu0311 commented
/azp run

2025-02-20 02:45 UTC, MonicaLiu0311 commented
/azp run

2025-04-09 19:53 UTC, closed without merging

2025-04-09 19:54 UTC, BillyONeal commented
Closed this due to no changes in 6 months. Would be happy to take similar changes in the future should someone be able to do so without trying to mix system and vcpkg provided libraries.