[parallel-hashmap] Bump version to 1.4.0
microsoft/vcpkg pull request #41100
Opened 2024-09-20 22:26 UTC by greg7mdp

2024-09-23 02:50 UTC, WangWeiLin-MV requested changes

2024-09-23 02:50 UTC, WangWeiLin-MV commented on versions/p-/parallel-hashmap.json
> +      "git-tree": "aea42146de0d8a439e04c1cca716a456f8395d05",
Please do not modify exist version data.

2024-09-23 13:21 UTC, greg7mdp commented on versions/p-/parallel-hashmap.json
> +      "git-tree": "aea42146de0d8a439e04c1cca716a456f8395d05",
I restored the existing data, but I don't understand your second comment?

2024-09-24 02:19 UTC, WangWeiLin-MV commented on versions/p-/parallel-hashmap.json
> +      "git-tree": "aea42146de0d8a439e04c1cca716a456f8395d05",
The description of this PR is commened with `<!--`. I will clear it.

2024-09-24 02:20 UTC, WangWeiLin-MV approved these changes

2024-09-24 14:05 UTC, merged