[aom] Update to 3.10.0
microsoft/vcpkg pull request #41125
Opened 2024-09-23 02:29 UTC by jimwang118

Fixes https://github.com/microsoft/vcpkg/issues/41123

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] When updating the upstream version, the `"port-version"` is reset (removed from `vcpkg.json`).
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplet:

```
x64-windows
```

2024-09-24 02:44 UTC, JonLiu1993 approved these changes

2024-09-24 15:02 UTC, JavierMatosD commented on ports/aom/fix_uwp.patch
> ++                         (LPTHREAD_START_ROUTINE)start, arg, 0, /* dwStackSize */
How are we sure this patch fixes the bug and doesn't just bypass the compilation error? 

The linked issue just includes a link to the change log. Can you provide more context?

2024-09-25 02:11 UTC, jimwang118 commented on ports/aom/fix_uwp.patch
> ++                         (LPTHREAD_START_ROUTINE)start, arg, 0, /* dwStackSize */
> How are we sure this patch fixes the bug and doesn't just bypass the compilation error?
> 
> The linked issue just includes a link to the change log. Can you provide more context?

```
E:\vcpkg\buildtrees\aom\src\a3cfd7c5fc-83bc6a3bee.clean\aom_util/aom_pthread.h(95): error C2664: 'HANDLE CreateThread(LPSECURITY_ATTRIBUTES,SIZE_T,LPTHREAD_START_ROUTINE,LPVOID,DWORD,LPDWORD)': cannot convert argument 3 from 'unsigned int (__cdecl *)(void *)' to 'LPTHREAD_START_ROUTINE'
E:\vcpkg\buildtrees\aom\src\a3cfd7c5fc-83bc6a3bee.clean\aom_util/aom_pthread.h(97): note: This conversion requires a reinterpret_cast, a C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\processthreadsapi.h(194): note: see declaration of 'CreateThread'
E:\vcpkg\buildtrees\aom\src\a3cfd7c5fc-83bc6a3bee.clean\aom_util/aom_pthread.h(95): note: while trying to match the argument list '(int, int, unsigned int (__cdecl *)(void *), void *, int, int)'
```
The specific error message is as above. This is a C project code, so C-style forced type conversion is performed.

2024-09-25 18:47 UTC, BillyONeal requested changes, later dismissed

2024-09-25 18:47 UTC, BillyONeal commented on ports/aom/fix_uwp.patch
> ++                         (LPTHREAD_START_ROUTINE)start, arg, 0, /* dwStackSize */
This cast is not safe. `LPTHREADSTARTROUTINE` is:

```c++
typedef DWORD (__stdcall *LPTHREAD_START_ROUTINE) (  
    [in] LPVOID lpThreadParameter  
); 
```

Note: `__stdcall`. If this were converting from `unsigned int (__stdcall *)(void *)` to `unsigned long (__stdcall *)(void *)` (changing int to long in an environment where int and long are the same size) it *might* be OK, but changing the calling convention with a cast like this is never OK.

2024-12-16 08:01 UTC, dg0yt commented on ports/aom/portfile.cmake
> -        -DTHREADS_PREFER_PTHREAD_FLAGS=ON
There was a typo. THe proper name is singular `THREADS_PREFER_PTHREAD_FLAG`.

2024-12-16 08:13 UTC, jimwang118 commented on ports/aom/portfile.cmake
> -        -DTHREADS_PREFER_PTHREAD_FLAGS=ON
Thanks, it has been modified.

2024-12-19 08:45 UTC, JonLiu1993 approved these changes

2024-12-19 21:26 UTC, BillyONeal commented on ports/aom/fix-uwp.patch
> ++  *thread = (pthread_t)work;
This is missing `CloseThreadpoolWork`. I think we should just be marking `"supports":"!uwp"`.

2024-12-20 02:21 UTC, jimwang118 commented on ports/aom/fix-uwp.patch
> ++  *thread = (pthread_t)work;
Editing completed.

2024-12-20 02:46 UTC, jdpurcell commented
And the PR title should be updated to reflect the new version `3.11.0` otherwise the squash merge's commit message will be wrong, no?

@jimwang118 Thank you, by the way!

2024-12-20 02:50 UTC, jimwang118 commented
> And the PR title should be updated to reflect the new version `3.11.0` otherwise the squash merge's commit message will be wrong, no?
> 
> @jimwang118 Thank you, by the way!

Thanks for your suggestion, I have changed the title.

2024-12-20 08:51 UTC, JonLiu1993 approved these changes

2024-12-20 20:35 UTC, merged