add poselib port
microsoft/vcpkg pull request #41468
Opened 2024-10-10 08:46 UTC by fran6co

2024-10-10 09:49 UTC, LilyWangLL commented
Please fix the following warning after installation: 
```
-- Performing post-build validation
F:\PRreview\vcpkg\ports\poselib\portfile.cmake: warning: Import libraries for installed DLLs appear to be missing. If this is intended, add set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
F:\PRreview\vcpkg\ports\poselib\portfile.cmake: warning: the following DLLs were built without any exports. DLLs without exports are likely bugs in the build script. If this is intended, add set(VCPKG_POLICY_DLLS_WITHOUT_EXPORTS enabled)
F:\PRreview\vcpkg\packages\poselib_x64-windows: note: the DLLs are relative to ${CURRENT_PACKAGES_DIR} here
note: debug/bin/PoseLibd.dll
note: bin/PoseLib.dll
F:\PRreview\vcpkg\ports\poselib\portfile.cmake: warning: There should be no installed empty directories. Empty directories are not representable to several binary cache providers, git repositories, and are not considered semantic build outputs. You should either create a regular file inside each empty directory, or delete them with the following CMake. To suppress this message, add set(VCPKG_POLICY_ALLOW_EMPTY_FOLDERS enabled)
F:\PRreview\vcpkg\packages\poselib_x64-windows: note: the directories are relative to ${CURRENT_PACKAGES_DIR} here
note: file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib" "${CURRENT_PACKAGES_DIR}/lib")
F:\PRreview\vcpkg\ports\poselib\portfile.cmake: warning: Found 3 post-build check problem(s). These are usually caused by bugs in portfile.cmake or the upstream build system. Please correct these before submitting this port to the curated registry.
Stored binaries in 1 destinations in 41 s.
Elapsed time to handle poselib:x64-windows: 6.3 min
```
Does this port only generate `*.dll` files? No `*.lib` files after installation.

2024-10-10 09:52 UTC, LilyWangLL commented
And please confirm the check list about add new port in description of this PR.

2024-10-10 10:26 UTC, fran6co commented
I don't have a windows box to test this, I will disable windows from the port for now

2024-10-10 20:29 UTC, dg0yt commented
> I will disable windows from the port for now

Wrong fix.

When the package lacks DLL export definitions, we can still build static libs for Windows. Start the portfile with:
~~~cmake
if(VCPKG_TARGET_IS_WINDOWS)
    check_library_linkage(ONLY_STATIC_LIBRARY)
endif()
~~~

2024-10-11 07:01 UTC, fran6co commented
Done

2024-10-11 08:43 UTC, LilyWangLL requested changes

2024-10-11 08:43 UTC, LilyWangLL commented on ports/poselib/portfile.cmake
> +    check_library_linkage(ONLY_STATIC_LIBRARY)
```suggestion
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```

2024-10-11 08:44 UTC, fran6co commented on ports/poselib/portfile.cmake
> +    check_library_linkage(ONLY_STATIC_LIBRARY)
Done

2024-10-11 10:35 UTC, LilyWangLL approved these changes

2024-10-16 03:57 UTC, data-queue approved these changes

2024-10-16 03:58 UTC, merged