When cross-compiling pcl for Android pre-set some cache variables. Fixes #41505
microsoft/vcpkg pull request #41506
Opened 2024-10-11 21:39 UTC by jackjansen

Fixes #41505.

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2024-10-11 21:41 UTC, jackjansen commented
> @jackjansen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

2024-10-12 05:22 UTC, dg0yt commented on ports/pcl/portfile.cmake
> +
```suggestion
```

2024-10-18 22:37 UTC, BillyONeal requested changes
Can you explain what the effect of setting these is, and why it is correct to do so for Android?

2024-10-30 20:44 UTC, jackjansen commented
Sorry for the delay in answering this.

The problem this fix solves is that these build-time tests depend on running a program to test the existence of some aligned-allocation functions. This cannot work when cross-compiling.

When building for Android you're always cross-compiling. Moreover, these macros aren't actually needed because they're used in one place in the pcl sources, and in that place there's a separate `#if` for Android.

I've reported the same issue in the pcl repo, but past experience suggests that the pcl developers move at glacial speed.

2025-01-15 21:32 UTC, jackjansen commented
Superseded by #43295

2025-01-15 21:32 UTC, closed without merging