[shitmedia-libgnutls, nettle] update shiftmedia-libgnutls to 3.8.7, add symbols in nettle for shiftmedia-libgnutls
microsoft/vcpkg pull request #41704
Opened 2024-10-21 17:07 UTC by talregev

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-10-22 08:00 UTC, Mengna-Li requested changes

2024-10-22 08:00 UTC, Mengna-Li commented on ports/shiftmedia-libgnutls/external-libtasn1.patch
>       <ClCompile Include="..\lib\nettle\sysrng-bcrypt.c">
@talregev Can you submit this patch upstream?

2024-10-22 08:02 UTC, talregev commented on ports/shiftmedia-libgnutls/external-libtasn1.patch
>       <ClCompile Include="..\lib\nettle\sysrng-bcrypt.c">
I cannot, because they using internal libtasn1. 
This is how when it create this port:
https://github.com/microsoft/vcpkg/pull/18029

2024-10-22 08:05 UTC, talregev commented on ports/shiftmedia-libgnutls/external-libtasn1.patch
>       <ClCompile Include="..\lib\nettle\sysrng-bcrypt.c">
https://github.com/microsoft/vcpkg/pull/18029/files#r947705859

2024-10-22 08:06 UTC, Mengna-Li approved these changes

2024-10-23 06:00 UTC, data-queue approved these changes

2024-10-23 06:00 UTC, merged