[libmodplug] Fix build failure with clang-19
microsoft/vcpkg pull request #41959
Opened 2024-11-05 02:52 UTC by ankurvdev

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

2024-11-05 03:59 UTC, LilyWangLL requested changes

2024-11-05 03:59 UTC, LilyWangLL commented on ports/libmodplug/portfile.cmake
> +set(EXTRA_OPTIONS "-DCMAKE_CXX_STANDARD=11")
Is it necessary to set C++11 on all platforms?

2024-11-05 05:09 UTC, ankurvdev commented on ports/libmodplug/portfile.cmake
> +set(EXTRA_OPTIONS "-DCMAKE_CXX_STANDARD=11")
The failure happens because if we dont set it explicitly then with newer compiler it is set to a higher standard which doesnt work because of deprecated features being removed.

So setting the necessary standard on all platforms seems to be a good thing to do

2024-11-05 09:25 UTC, LilyWangLL approved these changes, later dismissed

2024-11-05 19:28 UTC, vicroms requested changes

2024-11-05 19:28 UTC, vicroms commented on versions/l-/libmodplug.json
> +      "git-tree": "c8e3d0af1af8bb778f772c0a8d59a3c99ec663c1",
The `git-tree` for version `0.8.9.0` should not be modified. Please restore the old `git-tree` and just add the new port version's entry.

2024-11-07 04:47 UTC, vicroms approved these changes

2024-11-07 04:47 UTC, merged