[daw-header-libraries] update to v2.114.1
microsoft/vcpkg pull request #41957
Opened 2024-11-05 02:25 UTC by jimwang118

Fixes https://github.com/microsoft/vcpkg/issues/41925

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test passed with x64-windows triplet.

2024-11-06 01:48 UTC, Mengna-Li submitted a review, later dismissed

2024-11-07 04:53 UTC, vicroms requested changes

2024-11-07 04:53 UTC, vicroms commented on ports/daw-json-link/portfile.cmake
> +#endif()
```suggestion
```

Remove these lines since the conflict no longer exists.

2024-11-07 06:16 UTC, jimwang118 commented on ports/daw-json-link/portfile.cmake
> +#endif()
Done

2024-11-11 08:21 UTC, vicroms approved these changes

2024-11-11 08:21 UTC, merged