[cpp-pinyin] Add new port
microsoft/vcpkg pull request #42063
Opened 2024-11-09 01:45 UTC by wolfgitpr

<!-- If this PR adds a new port, please uncomment and fill out this checklist:

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [ ] The versioning scheme in `vcpkg.json` matches what upstream says.
- [ ] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [ ] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is in the new port's versions file.
- [ ] Only one version is added to each modified port's versions file.

2024-11-09 01:48 UTC, wolfgitpr commented
@microsoft-github-policy-service agree

2024-11-11 07:55 UTC, Mengna-Li requested changes

2024-11-11 07:55 UTC, Mengna-Li commented on ports/cpp-pinyin/portfile.cmake
> +            -DVCPKG_DICT_DIR=${CURRENT_PACKAGES_DIR}/share/${PORT}
I think it's best to just include build-static as a variable in the IF condition.

2024-11-11 08:14 UTC, dg0yt commented on ports/cpp-pinyin/portfile.cmake
> +endif()
```suggestion
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" CPP_PINYIN_BUILD_STATIC)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DCPP_PINYIN_BUILD_STATIC=${CPP_PINYIN_BUILD_STATIC}
        -DCPP_PINYIN_BUILD_TESTS=FALSE
        "-DVCPKG_DICT_DIR=${CURRENT_PACKAGES_DIR}/share/${PORT}"
)
```

2024-11-11 08:19 UTC, dg0yt commented on ports/cpp-pinyin/usage
> +    https://github.com/wolfgitpr/pinyin-makedict
Synopsis. Consistent use of target name `main`. No vcpkg variables.
```suggestion
cpp-pinyin provides CMake targets:

  find_package(cpp-pinyin CONFIG REQUIRED)
  target_link_libraries(main PRIVATE cpp-pinyin::cpp-pinyin)

To use the library, you need to copy the dictionary files to the binary directory.

  add_custom_command(TARGET main POST_BUILD
      COMMAND "${CMAKE_COMMAND}" -E copy_directory
        "${cpp-pinyin_DIR}/dict"
        "$<TARGET_FILE_DIR:main>/dict"
  )
```

2024-11-12 02:15 UTC, Mengna-Li approved these changes

2024-11-12 07:26 UTC, merged