[gsl-lite] Update to v0.42.0
microsoft/vcpkg pull request #42140
Opened 2024-11-13 14:35 UTC by mbeutel

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [X] The "supports" clause reflects platforms that may be fixed by this new version.
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2024-11-14 02:58 UTC, Mengna-Li requested changes

2024-11-14 02:58 UTC, Mengna-Li commented on ports/gsl-lite/portfile.cmake
> +    REF 004a3e61f30e5c94b5964a0b4a2728847579a304
```suggestion
    REF “v${VERSION}”
```

2024-11-14 09:12 UTC, mbeutel commented on ports/gsl-lite/portfile.cmake
> +    REF 004a3e61f30e5c94b5964a0b4a2728847579a304
Without typographic quotation marks, I presume? Just made the change in a new commit.

(I'll note that the version tags references a slightly earlier commit, which is why the SHA has changed; the commits that came after were of peripheral nature and had no impact on the source code.)

2024-11-15 01:44 UTC, Mengna-Li approved these changes

2024-11-16 00:05 UTC, merged