[kerbal] update to v2024.11.1
microsoft/vcpkg pull request #42307
Opened 2024-11-22 06:56 UTC by WentsingNee

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

2024-11-22 08:12 UTC, jimwang118 requested changes

2024-11-22 08:12 UTC, jimwang118 commented on ports/kerbal/vcpkg.json
>    "license": "LGPL-3.0",
```suggestion
  "license": "LGPL-3.0-or-later",
```

2024-11-22 08:30 UTC, jimwang118 approved these changes, later dismissed

2024-11-22 08:35 UTC, jimwang118 commented
> @jimwang118 should I squash the second commit into the first one?

You need to run the command: `./vcpkg x-add-version {portname} --overwrite-version`, and then submit the regenerated kerbal.json file.

2024-11-22 08:37 UTC, WentsingNee commented
> > @jimwang118 should I squash the second commit into the first one?
> 
> You need to run the command: `./vcpkg x-add-version {portname} --overwrite-version`, and then submit the regenerated kerbal.json file.

done

2024-11-22 23:23 UTC, BillyONeal commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
Can you explain where the `-or-later` is documented? The LICENSE does not say that.

2024-11-23 03:54 UTC, WentsingNee commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
Well, this change is suggested by @jimwang118  during his review. Actually, I didn't change my project's LICENSE these days.

2024-11-23 03:54 UTC, WentsingNee commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
https://github.com/microsoft/vcpkg/pull/42307#discussion_r1853448738

2024-11-23 04:02 UTC, WentsingNee commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
I didn't focus and track the policy published by the vcpkg official so I also don't understand. Whether you have updated the policy related to the LICENSE in pursuit of the compatibility?

2024-11-25 06:28 UTC, jimwang118 commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
There is no separate LGPL-3.0 license in the website [SPDX-license-list](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-list/) where we are verifying the license, so it is changed to [LGPL-3.0-or-later](https://spdx.org/licenses/LGPL-3.0-or-later.html).

2024-11-25 08:42 UTC, dg0yt commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
Either it is `LGPL-3.0-or-later` or it is `LGPL-3.0-only`. If we do not know exactly, the deprecated fuzzy `LGPL-3.0` might be the best fit!

2024-11-25 21:26 UTC, BillyONeal commented on ports/kerbal/vcpkg.json
> +  "license": "LGPL-3.0-or-later",
@WentsingNee Ah, I'm sorry, I didn't notice that you are upstream! In that case, I agree with @dg0yt that the deprecated fuzzy one should remain. I would suggest that, as the upstream maintainer, you clarify in your own project's documentation which you mean, and we'll update the license expression when we ingest that update. However, we don't need that to happen to take this update. Thanks!

2024-11-25 21:31 UTC, BillyONeal approved these changes
I reverted the license field edit and set auto merge, I assumed @WentsingNee is happy with that given that their initial PR did not contain that change.

2024-11-26 06:19 UTC, jimwang118 approved these changes

2024-11-26 06:27 UTC, merged