Add license information for a set of ports
microsoft/vcpkg pull request #42312
Opened 2024-11-22 13:10 UTC by aristotelos

See:

- https://github.com/google/double-conversion/blob/master/LICENSE
- http://glew.sourceforge.net/mesa.txt
- https://github.com/jasper-software/jasper/blob/master/LICENSE.txt
- https://github.com/BLAKE2/libb2/blob/master/COPYING
- https://github.com/microsoft/vcpkg/blob/master/ports/libiconv/portfile.cmake#L56
- https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/libmount/COPYING
- https://gitlab.freedesktop.org/xorg/lib/libxext/-/blob/master/COPYING
- https://gitlab.freedesktop.org/xorg/lib/libxfixes/-/blob/master/COPYING
- https://gitlab.freedesktop.org/xorg/lib/libxi/-/blob/master/COPYING
- https://gitlab.freedesktop.org/xorg/lib/libxtst/-/blob/master/COPYING
- https://gitlab.freedesktop.org/xorg/lib/libxv/-/blob/master/COPYING
- https://github.com/pkgconf/pkgconf/blob/master/COPYING
- https://github.com/google/snappy/blob/main/COPYING
- https://gitlab.freedesktop.org/xorg/util/macros/-/blob/master/COPYING
- https://gitlab.freedesktop.org/xorg/lib/libxtrans/-/blob/master/COPYING

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download. - NOT APPLICABLE
- [x] The "supports" clause reflects platforms that may be fixed by this new version. - NOT APPLICABLE
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file. - NOT APPLICABLE
- [x] Any patches that are no longer applied are deleted from the port's directory. - NOT APPLICABLE
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result. - NOT APPLICABLE
- [x] Only one version is added to each modified port's versions file. - NOT APPLICABLE

2024-11-25 22:00 UTC, BillyONeal requested changes
The ones that are explicitly `null` need justification as to why null is incorrect beyond a link to a COPYING file, particularly to COPYING files that are not the license you indicated.

Please:

* Fix the licenses to match what they actually say, and/or
* Supply more concrete justification that refutes what was said in the PRs that added `"license": null`, and/or
* Remove the edits to ports where you can't do that

and un-draft this PR to request a re-review.

Thanks for your contribution to vcpkg!

2024-11-25 22:00 UTC, BillyONeal commented on ports/glew/vcpkg.json
> +  "license": "MIT AND BSD-3-Clause",
This is not supported by the http://glew.sourceforge.net/mesa.txt in the description of the PR, but is supported by https://github.com/nigels-com/glew#copyright-and-licensing , so no change requested.

2024-11-25 22:00 UTC, BillyONeal commented on ports/libiconv/vcpkg.json
> +  "license": "LGPL-2.1-only"
This change is wrong, as `portfile.cmake` explains. (I'm not sure why you linked to this in the PR description despite it contradicting this) `null` is correct as some parts of the installed port content are not `LGPL-2.1-only`, and an explanation is necessary to determine which parts are.

2024-11-25 22:00 UTC, BillyONeal commented on ports/libxext/vcpkg.json
> +  "license": "MIT",
Your own reference link contradicts this; it does not point at the MIT license. I believe `MIT-open-group` *might* be correct.

2024-11-25 22:00 UTC, BillyONeal commented on ports/libxi/vcpkg.json
> +  "license": "MIT",
As per your own link, I believe 'MIT' is wrong. I know at the top it says 'is licensed under the MIT license', but the actual license text is not the MIT license. In particular this part is closer to the BSD licenses that forbid use of names: https://gitlab.freedesktop.org/xorg/lib/libxi/-/blob/master/COPYING#L23-L41

I think this should remain `null`.

2024-11-25 22:00 UTC, BillyONeal commented on ports/libxtst/vcpkg.json
> +  "license": "X11",
The https://gitlab.freedesktop.org/xorg/lib/libxtst/-/blob/master/COPYING#L101-L104 part is not the `X11` license. I believe `null` is correct.

2024-11-25 22:00 UTC, BillyONeal commented on ports/libxv/vcpkg.json
> +  "license": "MIT",
https://gitlab.freedesktop.org/xorg/lib/libxv/-/blob/master/COPYING is not the MIT license. I believe null is correct.

2024-11-25 22:00 UTC, BillyONeal commented on ports/snappy/vcpkg.json
> +  "license": "BSD-3-Clause",
I think this one is OK. https://github.com/google/snappy/blob/32ded457c0b1fe78ceb8397632c416568d6714a0/COPYING#L32C1-L32C65 is here and says testdata is licensed differently, but the port does not install the testdata.

2024-11-25 22:00 UTC, BillyONeal commented on ports/xtrans/vcpkg.json
> +  "license": "MIT-open-group",
This is not MIT-open-group: https://gitlab.freedesktop.org/xorg/lib/libxtrans/-/blob/master/COPYING#L103-L121

I believe `null` is correct.

2024-11-25 22:00 UTC, BillyONeal commented on ports/libmount/vcpkg.json
> +  "license": "LGPL-2.1-or-later",
I don't think https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/libmount/COPYING is sufficient to prove this, https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/README.licensing as the port references explicitly says that the COPYING part only applies to files without their own license inside. https://github.com/microsoft/vcpkg/pull/35738/ was justified in setting this to null. Or did you actually check every source file?

2024-11-26 15:06 UTC, aristotelos commented on ports/libiconv/vcpkg.json
> +  "license": "LGPL-2.1-only"
I thought the `libiconv` port would not distribute `iconv` itself, I thought it would only distribute the library. But apparently I am mistaken...

2024-11-26 15:11 UTC, aristotelos commented on ports/libxext/vcpkg.json
> +  "license": "MIT",
Oops, I think indeed this is a complex list of licenses starting wth MIT-open-group but followed by many others...

2024-11-26 15:23 UTC, aristotelos commented on ports/libxi/vcpkg.json
> +  "license": "MIT",
Hmm, it should indeed be more specific. When I paste the various licenses in https://tools.spdx.org/app/check_license/, I get:
- MIT-open-group
- SMLNJ
- MIT-open-group
- MIT
So it should probably be `MIT-open-group AND SMLNJ AND MIT`

2024-11-26 15:28 UTC, closed without merging

2024-11-27 03:36 UTC, BillyONeal commented
> @BillyONeal Thanks for the thorough review, and sorry for my lack of confidence to continue.

S'ok, that's the whole point of review, we still appreciate it! Thanks for your contribution!