Libxml2 extra options
microsoft/vcpkg pull request #42674
Opened 2024-12-12 21:29 UTC by donny-dont

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [X] The "supports" clause reflects platforms that may be fixed by this new version.
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

2024-12-13 18:58 UTC, donny-dont commented
Alrighty this is ready for review. Spoke with the maintainer over at https://gitlab.gnome.org/GNOME/libxml2/-/issues/826#note_2297229 about the option sets and updated based on their feedback.

2024-12-13 19:58 UTC, dg0yt reviewed
(Community feedback.)

2024-12-13 19:58 UTC, dg0yt commented on ports/libxslt/vcpkg.json
>      },
This feature is marked as deprecated, and AFAICS it doesn't to anything useful: It builds a test plugin and a test executable. Would it make sense to remove it instead?

2024-12-13 19:58 UTC, dg0yt commented on ports/libxml2/vcpkg.json
> +    },
If this isn't wired to a *specific* capability, it should be unrolled in port libxslt instead. (libxslt must know what it needs.)

2024-12-13 19:58 UTC, dg0yt commented on ports/libxml2/vcpkg.json
> +    },
What does this feature when iconv is enabled at the same time?

2024-12-13 21:04 UTC, donny-dont commented on ports/libxml2/vcpkg.json
> +    },
Looks like https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/encoding.c points to it only being relevant if neither ICU or iconv is present.

How would you suggest that be expressed?

2024-12-13 21:09 UTC, donny-dont commented on ports/libxslt/vcpkg.json
>      },
I just saw that this feature will not build without the `plugins` feature in `libxml2`. I don't have a strong preference here. Module support is still present so maybe someone wants to build with it? 🤷

2024-12-13 21:10 UTC, donny-dont commented on ports/libxml2/vcpkg.json
> +    },
Will fix

2024-12-13 21:11 UTC, donny-dont commented
> (Community feedback.)

Thanks @dg0yt ! Will adjust after we align on the changes requested.

2024-12-13 21:18 UTC, dg0yt commented on ports/libxslt/vcpkg.json
>      },
But does this feature change any bits in libxslt?
For plugins in libxml2, there is a feature in libxml2...

2024-12-13 21:25 UTC, donny-dont commented on ports/libxslt/vcpkg.json
>      },
At some point this will be removed https://gitlab.gnome.org/GNOME/libxslt/-/commit/ff7cf97d808f37837bfd055e715e5474c7f338d9 but at this point in time it is required to be present  https://gitlab.gnome.org/GNOME/libxslt/-/blob/v1.1.42/libxslt/extensions.c?ref_type=tags#L25-27

2024-12-13 21:28 UTC, dg0yt commented on ports/libxml2/vcpkg.json
> +    },
Hm.
"ICU" is not modeled AFAICS. (And I don't ask for it. This would add another alternative.)
icon comes with a dependency, but this feature is without. I would probably enable iso8859x by default, without and explicit feature.

(This PR adds many features. I don't expect many users to be willing to go into that level of details.)

2024-12-13 21:29 UTC, dg0yt commented
BTW I expect the maintainers to ask for reducing the number of default-features. It is easy to ask  for optional features, but many users find it inconvenient to disable default-features.

2024-12-13 21:35 UTC, donny-dont commented
> BTW I expect the maintainers to ask for reducing the number of default-features. It is easy to ask for optional features, but many users find it inconvenient to disable default-features.

I modeled it after what defaults to `ON` in https://gitlab.gnome.org/GNOME/libxml2/-/blob/2.13/CMakeLists.txt?ref_type=heads#L26-64 .

For WebKit we're able to turn off a number of features, see https://github.com/WebKitForWindows/WebKitRequirements/blob/730b4ba17b3b2d4485d126add5355d76535e7f47/ports/libxml2/portfile.cmake#L29-L81 , and I'd like to continue to have a minimal `libxml2` going forward here.

2024-12-16 08:01 UTC, JonLiu1993 approved these changes

2024-12-16 08:05 UTC, JonLiu1993 commented
Features `c14n,catalog,html,iso8859x,output,pattern,plugins,push,reader,regex,sax1,schemas,schematron,thread,thread-alloc,thread-local-storage,validation,writer,xinclude,xpath,xptr,xptr-locs` tested successfully in the following triplet:
- x86-windows
- x64-windows

Features `c14n,catalog,html,iso8859x,output,pattern,push,reader,regex,sax1,schemas,schematron,thread,thread-alloc,thread-local-storage,validation,writer,xinclude,xpath,xptr,xptr-locs` tested successfully in the follwoing triplet:
- x64-windows-static

2024-12-16 08:17 UTC, JonLiu1993 approved these changes

2024-12-16 16:42 UTC, JavierMatosD requested changes

2024-12-18 19:47 UTC, donny-dont commented on ports/libxml2/vcpkg.json
> +    "xptr"
I'm just going by what is `ON` by default in the CMakeLists.txt file of the library.

@nwellnhof is the maintainer of the library. Maybe he has thoughts on this?

2024-12-18 20:37 UTC, dg0yt commented on ports/libxml2/vcpkg.json
> +    "xptr"
OTOH it might not be necessary add a feature when 99.99% of the users won't turn it off.

2025-02-08 07:02 UTC, JonLiu1993 commented
Ping @donny-dont for response.

2025-04-09 18:36 UTC, closed without merging

2025-04-09 18:36 UTC, BillyONeal commented
I'm closing this due to lack of response. We're more than happy to add non-default features if there's a use case for turning them off. Please feel free to open a new PR consistent with the discussion above should you wish to do so.