Miniz dep was removed in latest version and replaced by libdeflate
microsoft/vcpkg pull request #42694
Opened 2024-12-14 10:36 UTC by flarive

Miniz dep was removed in latest version and replaced by libdeflate

2024-12-14 14:07 UTC, Osyotr commented
The library has a proper cmake support. The port should use it instead of the vendored one.

2024-12-14 21:16 UTC, flarive commented
> The library has a proper cmake support. The port should use it instead of the vendored one.

Ah ok, so what should i do ?
I'm not familiar with updating vcpkg ports :(

2024-12-16 03:02 UTC, JonLiu1993 requested changes

2024-12-16 03:02 UTC, JonLiu1993 commented on ports/openfbx/vcpkg.json
> +  "port-version": "2",
```suggestion
  "port-version": "1",
```

2024-12-16 03:04 UTC, JonLiu1993 commented
Please run command `./vcpkg x-add-version openfbx` after finish your changes, and command agagin.

2024-12-16 03:08 UTC, JonLiu1993 commented
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

2024-12-16 19:14 UTC, flarive commented
> Please run command `./vcpkg x-add-version openfbx` after finish your changes, and commit agagin.

Ok, just did it...
Now i have this error :
Error: PRs must add only one version, and must not modify any published versions.
When making any changes to a library, the version or port-version in vcpkg.json must be modified, and the version database updated.
Making the following changes will fix this problem:```diff
error: checked-in files for openfbx have changed but the version was not updated
version: 2024-05-08#1
old SHA: 0044aa1e6ff32e6287babe258cab76c7f7bf8bf7
new SHA: 92185e9f54b9847f4c4b87cf7ffbe4f9522f4dda
Did you remember to update the version or port version?
Use --overwrite-version to bypass this check
See https://learn.microsoft.com/vcpkg/commands/add-version?WT.mc_id=vcpkg_inproduct_cli#--overwrite-version for more information.
***No files were updated***

2024-12-17 02:52 UTC, JonLiu1993 commented
This is ci error log, please take a look:
````
CMake Error at CMakeLists.txt:12 (target_link_libraries):
  Target "openfbx" links to:

    libdeflate::libdeflate

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
````

2024-12-17 04:52 UTC, dg0yt commented on ports/openfbx/CMakeLists.txt
> +target_link_libraries(openfbx PRIVATE libdeflate::libdeflate)
```suggestion
target_link_libraries(openfbx PRIVATE $<IF:$<TARGET_EXISTS:libdeflate::libdeflate_shared>,libdeflate::libdeflate_shared,libdeflate::libdeflate_static>)
```

2024-12-18 02:23 UTC, JonLiu1993 commented
Please run command `./vcpkg x-add-version openfbx --overwrite-version` and commit again.

2024-12-19 08:21 UTC, JonLiu1993 approved these changes

2024-12-19 08:41 UTC, JonLiu1993 commented
Tested usage successfully by `openfbx:x64-windows`

2024-12-19 21:14 UTC, merged