Compiler detection: Cache compiler hash
microsoft/vcpkg pull request #42994
Opened 2024-12-30 02:57 UTC by autoantwort

Implements https://github.com/microsoft/vcpkg-tool/pull/362#issuecomment-2375518454

2024-12-30 07:59 UTC, Mengna-Li requested changes

2024-12-30 07:59 UTC, Mengna-Li commented on scripts/detect_compiler/portfile.cmake
>  vcpkg_configure_cmake(
The function vcpkg_configure_cmake is deprecated. Please use vcpkg_cmake_configure.

2024-12-31 06:03 UTC, dg0yt commented on scripts/detect_compiler/portfile.cmake
>  vcpkg_configure_cmake(
@Mengna-Li This script is not part of a port and thus cannot depend on other ports. It must use `vcpkg_configure_make`.

2025-01-02 01:17 UTC, Mengna-Li approved these changes

2025-01-03 20:18 UTC, autoantwort commented on scripts/detect_compiler/CMakeLists.txt
> +if(VCPKG_COMPILER_CACHE_FILE)
No. The variable is passed to this port by `-DVCPKG_COMPILER_CACHE_FILE=${VCPKG_COMPILER_CACHE_FILE}`, but if an "old" `vcpkg-tool` is used the variable is not defined in the portfile and an empty variable gets defined.

2025-01-04 09:35 UTC, dg0yt commented on scripts/detect_compiler/portfile.cmake
> +        -DVCPKG_COMPILER_CACHE_FILE=${VCPKG_COMPILER_CACHE_FILE}
```suggestion
        "-DVCPKG_COMPILER_CACHE_FILE=${VCPKG_COMPILER_CACHE_FILE}"

```

2025-01-13 20:30 UTC, BillyONeal commented on scripts/detect_compiler/CMakeLists.txt
> +if(VCPKG_COMPILER_CACHE_FILE)
What defines the empty value?

2025-01-14 14:17 UTC, autoantwort commented on scripts/detect_compiler/CMakeLists.txt
> +if(VCPKG_COMPILER_CACHE_FILE)
This line: https://github.com/microsoft/vcpkg/pull/42994/files#diff-ab4c1b03d38817e599af1bda49e53b433097815b43514492c0896f89519405f5R22

2025-01-16 08:26 UTC, merged

2025-01-16 08:26 UTC, BillyONeal commented
Thanks!