[exprtk] Add versions 0.0.2 and 0.0.3
microsoft/vcpkg pull request #42996
Opened 2024-12-30 03:28 UTC by ArashPartow

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.

Closes: https://github.com/microsoft/vcpkg/pull/42173, https://github.com/microsoft/vcpkg/pull/40270, https://github.com/microsoft/vcpkg/pull/33571, https://github.com/microsoft/vcpkg/pull/30058, https://github.com/microsoft/vcpkg/pull/29955, https://github.com/microsoft/vcpkg/pull/29801, https://github.com/microsoft/vcpkg/pull/29775, https://github.com/microsoft/vcpkg/pull/29665

2024-12-30 07:19 UTC, LilyWangLL commented
The pipeline errors will be fixed by PR https://github.com/microsoft/vcpkg/pull/42912.

2024-12-30 07:28 UTC, ArashPartow commented
@LilyWangLL  thanks for the update on the pipeline issue. 

Please feel free to merge this PR, once https://github.com/microsoft/vcpkg/pull/42912 and the current PR's pipeline goes all green 🟢

2024-12-30 08:08 UTC, LilyWangLL approved these changes

2024-12-30 08:10 UTC, ArashPartow commented
@LilyWangLL  can you please revert the change you made specifically: [8770ed9](https://github.com/microsoft/vcpkg/pull/42996/commits/8770ed9ee0467cebf0294146bf083b10fa200b68)

That version is intentionally there it is tag 0.0.2.

2024-12-30 08:13 UTC, ArashPartow reviewed
@LilyWangLL can you please **revert** the change you made specifically: [8770ed9](https://github.com/microsoft/vcpkg/pull/42996/commits/8770ed9ee0467cebf0294146bf083b10fa200b68)

That version is intentionally there it is tag 0.0.2.

--------------

On a side note: Not sure why Github will not allowed me to request a change on my own PR .

2024-12-30 08:25 UTC, LilyWangLL commented
> @LilyWangLL can you please **revert** the change you made specifically: [8770ed9](https://github.com/microsoft/vcpkg/pull/42996/commits/8770ed9ee0467cebf0294146bf083b10fa200b68)
> 
> That version is intentionally there it is tag 0.0.2.
> 
> On a side note: Not sure why Github will not allowed me to request a change on my own PR .

In fact, version 2023-01-01 does not exist in vcpkg. This PR directly upgraded from version 2022-01-01 to version 2024-01-01.

2024-12-30 08:30 UTC, ArashPartow commented
@LilyWangLL  please read the title:  "Add versions 0.0.2 and 0.0.3"   there was no going directly from 0.0.1 to 0.0.3 

Also:

![image](https://github.com/user-attachments/assets/fd38a0c7-059c-4c99-8e94-263e8122babd)

2024-12-30 08:47 UTC, LilyWangLL commented
The commit for version 2023-01-01 is just a historical submission in this PR. The final data merged in the PR reflects the final changes, just from version 2022-01-01 to version 2024-01-01. 

After this PR is merged, users will only be able to install versions 2022-01-01 and 2024-01-01 in vcpkg, and not version 2023-01-01. The data in this JSON file needs to correspond to the changes shown in the image below and should not include any additional modifications.

![image](https://github.com/user-attachments/assets/cf2f9222-dd69-47e4-af43-d6d13a80f91c)

2024-12-30 08:50 UTC, ArashPartow commented
@LilyWangLL  I tried it locally before pushing the PR and was able to install both 2023-01-01  and 2024-01-01  - by default it will install 2024-01-01  however as you know the version can be specified as well.

Are you really suggesting I create two PRs , one for 2023-01-01 and one for 2024-01-01?

2024-12-30 08:56 UTC, LilyWangLL commented
If you want both versions 2023-01-01 and 2024-01-01 to be installable, you need to submit separate PRs for each version. After version 2023-01-01 is merged, then merge version 2024-01-01.

2024-12-30 09:06 UTC, LilyWangLL commented
> @LilyWangLL ok, I'll convert this PR to 2023 and then create another one once this has been merged for 2024, are you ok with me proceeding?

That's great!

2024-12-30 09:57 UTC, ArashPartow commented
@LilyWangLL  updated the PR to only include 0.0.2

Please merge the PR once the pipeline issues have been resolved.

-----------------------------

2024-12-30 10:17 UTC, LilyWangLL approved these changes

2024-12-30 12:21 UTC, dg0yt commented on ports/exprtk/vcpkg.json
> +  "version-date": "2023-01-01",
This port should finally decide which version scheme to use. The subject says `0.0.2`, and there is also a tag for it.

2024-12-30 12:21 UTC, dg0yt commented on ports/exprtk/copyright
> +SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Is it necessary to modify the file?
With 0.0.3, I expected it to be removed in favor of the file in upstream's repo.

2024-12-30 12:21 UTC, dg0yt commented on ports/exprtk/portfile.cmake
> +    SHA512 5D4F1CC49E035860D9B2410A9B48E1ADF8784C6301A31B2C7462C2DBFA64CA6763A832354E57414919DF7B7D23975F5F7759D0984BECAF25B39FB0AEDE6B716F
Nitpick: In vcpkg ports, we usually see lower case for these values.

2024-12-30 15:22 UTC, ArashPartow commented on ports/exprtk/copyright
> +SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
This is a copy of the license.txt in the repo. however it's not there in 0.0.2. Which is not in the repo. I'll make the change in the next PR as per: https://github.com/microsoft/vcpkg/pull/42996#issuecomment-2565198038

2024-12-30 15:24 UTC, ArashPartow commented on ports/exprtk/portfile.cmake
> +    SHA512 5D4F1CC49E035860D9B2410A9B48E1ADF8784C6301A31B2C7462C2DBFA64CA6763A832354E57414919DF7B7D23975F5F7759D0984BECAF25B39FB0AEDE6B716F
Is there a formal definition anywhere regarding this? I checked other ports and it seems to be a mixed bag.  It will be uppercase for this port.

2024-12-30 18:34 UTC, dg0yt commented on ports/exprtk/portfile.cmake
> +    SHA512 5D4F1CC49E035860D9B2410A9B48E1ADF8784C6301A31B2C7462C2DBFA64CA6763A832354E57414919DF7B7D23975F5F7759D0984BECAF25B39FB0AEDE6B716F
There is more like a dominant inflow than a mixed bag.
`git` uses lower case.
`sha512sum` produces lower case (on linux).
`cmake -E sha512sum` produces lower case.
`vcpkg hash` produces lower case. (IIRC it was deliberately change to do that. Does this count as a formal definition?)

2024-12-31 06:57 UTC, ArashPartow commented
@LilyWangLL would you happen to know how to resolve the unfound refs issue?

2024-12-31 16:51 UTC, ArashPartow commented
@LilyWangLL  can you please merge this PR, as I need to do the next one.

2025-01-01 11:16 UTC, dg0yt commented
Not resolved: Use lower-case SHA512 and git ref SHA, https://github.com/microsoft/vcpkg/pull/42996#discussion_r1899507748.

Still confusing: Versioning.

2025-01-01 17:34 UTC, ArashPartow commented
> Not resolved: Use lower-case SHA512 and git ref SHA, https://github.com/microsoft/vcpkg/pull/42996#discussion_r1899507748. 

@dg0yt  I requested you provide a guideline that requires this. Please also note you have since the start of 2023 getting in the way of ExprTk being update, with nitpicks that none of the other mods seems to raise.  Can you please refrain from interfering with this PR unless you have serious and legitimate concerns. 


> Still confusing: Versioning. 

I did not create the original vcpkg for this library which used dates for some reason for versions, but have been continuing it as-is.  If you feel like changing it, please do so via a PR once this and the next PR are merged.

2025-01-01 17:53 UTC, ArashPartow commented
> Not resolved: Use lower-case SHA512 and git ref SHA, https://github.com/microsoft/vcpkg/pull/42996#discussion_r1899507748. 

@dg0yt  I requested you provide a guideline that requires this. Please also note you have since the start of 2023 getting in the way of ExprTk being updated, with nitpicks etc.  Can you please refrain from this PR unless you have serious and legitimate concerns. 

```
ports/edlib/portfile.cmake:    SHA512 720C732C76D0D9ABE28ADCE9972B355864571A2E6CBD2C72C3B4A92E045A99E3A688153865586F7E8B6C90433E2EB1BB024AD0A6E9D4EB4B4D401A160D3F13CE
ports/srell/portfile.cmake:     SHA512 5F2762A98E1B68C3A4FA79051AE2CBEFD23CEDF1CE833FA1EB812D3F1112734018AF36AA9D9A50E2DC40C87A7FAAF46AF0B8F4161481994DC5E19F44301E867D
ports/sparsehash/portfile.cmake:    SHA512 40C007BC5814DD5F2BDACD5EC884BC5424F7126F182D4C7B34371F88B674456FC193B947FDD283DBD0C7EB044D8F06BAF8CAEC6C93E73B1B587282B9026EA877
ports/indicators/portfile.cmake:    SHA512 59FB17E93C886CEC2418E93E221FEBD2BF3160691B3473363417F8F8FA3D50D42D1DE0E55D62598EBA800B13C1D5AB1422D0A2C867246006B61340BA32D99232
ports/fakeit/portfile.cmake:    SHA512 CA9932DF909D6C7F75AB775B6AC9695C80F1DC4A58599C789EEA279A05183E9568BB80B63EBDA5EF77EDD54D766977AB7C5BCD565FB45A61B56CB8D43E49007B
ports/qcoro/portfile.cmake:    SHA512 BDE5C5CD9F3C038E6B5EC5A6ADAE5AE2218EDD9DF350E75FC5D8DB31D9339484E92CC88FDC37FA0539E0CDF1F53731418EBFA73B94564E993D7B02168988771B
ports/nmslib/portfile.cmake:    SHA512 62BBB965EA4BF1D416ED78231B1BA4B41C0F46327D7BE16D1F98095DB63EF0E0D893B70040009711BC9C68555B1B8C4038F5032ABD66B759E955E2CBB0553EC3
ports/greatest/portfile.cmake:    SHA512 836392A7C9C56C6A5658FD18B4BBB146304B1997DFD9CB59F2A83C18A5EC140C8DDE64A2C0CF9A169C426B9E586D37E2ED7D7FB792402DBB4149CC424EC2DB2E
ports/zeroc-ice/prepare_for_build.cmake:            SHA512 E65620F3B667A48B28EC770443296BB0B8058168197DB3AE877A36531FFC6CE7E9289C7FE37DFAD751877FBDBA03C55E37122931BBF001EA6F1906DFEEBACFCB
ports/snap7/portfile.cmake:    SHA512 84F4E1AD15BFEC201F9EB1EC90A28F37DFC848E370DB5CEA22EF4946F41FF6CC514581D29D592B57EE6D4C77F4AABB4B2BBA1E3637043161821BA2FFAE7F2DD6
ports/clue/portfile.cmake:    SHA512 A142EDD57753DA36687803332E81BD9D4413203F69F0055466219437C3385C593384DA2A3C6BC67B39EC7ED0C36854354F34C2AA2D4CE4F1D2B912546F4F46B2
ports/distorm/portfile.cmake:    SHA512 8AAD0C51E8D9DFAEAA069A3D4FADE4BDF87CCE464C85898B6B4888FA51A9BB6EC1221FAF32ACF59EBD047CCEB9A535B2FF93D196FD14FA834D8ECE5685417A55
ports/rpclib/portfile.cmake:    SHA512 9C65AE5D000CD66E39498667DC826A4E8A2C28EB4138CFFE3AA09D5DDC22575551B9FA6CE9D951343213B9583F947899CB18B58130AEAEE36DAB5881EA496272
ports/tl-optional/portfile.cmake:    SHA512 3911F397440D4383721B92DE614DE1BEF5DB5C88371FA35F008B92F673F1E1EBF46E98FCFF4CD2D71E558C89537B9128AD549777197FD0390ED18A5BDFC5D6E0
ports/yas/portfile.cmake:       SHA512 1101BBE0B11FF8FA3B40B1E3030E5E93125FEDC85A90532466C9E6E0708B1C4C38821C86FCAFE153717B66B7107FCB29D0E13E87E68BF2217948A7014FC3BAC0
ports/minisat-master-keying/portfile.cmake:    SHA512 48E7AC1C97EA58070EAB9310F977404295E881B1403D527A33E059A0BB5A16CAA9AF2FA9E5230AD7E53E008B83077E300B3BAEEB0C220BE4E52B6B85887A05E1
ports/strong-type/portfile.cmake:    SHA512 "67F6F0AC34703206A5F45B492CB52ACAF87189D137B3CA5F9A0BB3708FE91FF4FBA61B6BFD9CDC8D2494D112F7964C8BE366F2ECECEF3B8B5B7CC1F318EFAFDD"
ports/quill/portfile.cmake:    SHA512 75FF87FD0A51F9A35C748421589411B21449CEAFF930843A8A1142B0BA6B3C20821E29FA2CE7F746C4304F652D576DFB306CCA1627849911CA4B1D7ADD05332A
ports/bond/portfile.cmake:        SHA512 4CD92F0665E36CB718311A237DF80B8CD93BFE33971F6460B88A1B74E9E2237D6AEA146766D6AE92674E2DDBBB3245CEBB199FF5BA82163FE69781340E0479AE
ports/easyhook/portfile.cmake:    SHA512 D0CA5B64E77F6281B2DD7EE0DC492A9B07DDB60A9F514037938CC3E3FFA5DD57C95CB630E18C02C984A89070839E4188044896D4EE57A21E43E6EA3A4918255A
ports/libassert/portfile.cmake:    SHA512 848D961CA884734FDB9C9440098E40EC9A4A7586C7A3D223D94A57513D904FB582B032A9F179A0D7C7D8AF76CF178CA215233642F651CF51A27200200DD7052A
```
Just a short sampling, but have you been involved in any of these?

--------------------------------------------

> Still confusing: Versioning. 

when I originally  created the port vcpkg for this library, I followed another port's scheme, because the library doesn't use semver. I've added semver recently to the GH repo to make it easier for people that use package managers.  This was accepted at the time. So I'm not sure what is the best path going forward that wont break backwards compatibility. In short if you have a complete and viable solution please let me know. Otherwise you are always free to make your own PR once these have been merged and take over this port.

2025-01-01 17:55 UTC, ArashPartow commented
@Cheney-W / @Mengna-Li / @PhoebeHui / @jimwang118 / @JonLiu1993 / @LilyWangLL  Can any of you please merge this PR. Been trying to get it merged since early **2023**

2025-01-02 02:54 UTC, LilyWangLL approved these changes

2025-01-03 17:10 UTC, JavierMatosD requested changes
See comments

2025-01-03 17:10 UTC, JavierMatosD commented on ports/exprtk/copyright
> -Copyright 1999-2022 Arash Partow
I see that upstream has a license file. Please just install that copyright file rather than checking it in here.

2025-01-03 17:10 UTC, JavierMatosD commented on ports/exprtk/vcpkg.json
> +  "version-date": "2023-01-01",
@ArashPartow we should be using the version scheme that upstream uses. In this case, it appears there's a tag for `0.0.3`

2025-02-07 03:30 UTC, vicroms commented
Version 0.0.3 has been merged in the registry. Our policy is to take the latest versions of each package.

2025-02-07 03:30 UTC, closed without merging