Add xlnt port
microsoft/vcpkg pull request #482
Opened 2017-01-03 01:28 UTC by tfussell

xlnt is a C++ library I wrote for reading and writing XLSX files. I would like to add support for installing xlnt using vcpkg with this pull request. Please let me know if there's anything I need to do to improve this port. (Closes tfussell/xlnt#85).

2017-01-03 01:28 UTC, msftclas commented
Hi __@tfussell__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2017-01-03 11:48 UTC, codicodi commented
I think it would be best if dependencies of your library would be provided by vcpkg. Unfortunately we don't have ports of libstudxml and botan, so IMHO they should be added first.
It would be also nice if your port automatically inserted `XLNT_STATIC `macro to your headers after build.

As a sidenote not related to port: I noticed that constructor for ` document_security` class isn't defined anywhere - shouldn't it be defaulted?

2017-01-04 02:47 UTC, tfussell commented
Thanks for the feedback @codicodi. It would be nice to use vcpkg for all of the dependencies, but I'm targeting Windows, OSX, and Linux so I think I'll have to stick with Git submodules for the time being. I'm not sure how other vcpkg ports have dealt with this.

You're right about the XLNT_STATIC definition. I'll see if I can get that working.

As for document_security, defaulting the constructor is a good idea. Xlnt does have some unused methods missing definitions since my goal was to implement the core functionality and then let the community provide any advanced fucntionality they might need. The spec is just too big for me to get everything done on version 1.0.

2017-01-13 00:40 UTC, ras0219-msft commented
We do need to use system dependencies when they are available, to enable

- Upgrading/security patching
- Static linking (to avoid symbol conflicts with the system copies)
- Sane debugging (`#include <expat>` does the same thing everywhere)

For now, this means cryptopp, expat, zlib, and utfcpp.

Looking at [1], I think the least intrusive way to do this would be to add a non-default cmake macro that would disable the `xlnt.third-party` target and instead run a series of `find_library` calls that grab the appropriate prebuilt versions and assemble them into a cmake pseudo-target.

[1] https://github.com/tfussell/xlnt/blob/master/third-party/CMakeLists.txt

2017-01-27 02:25 UTC, tfussell commented
Thanks for taking a look at my port @ras0219-msft. It does make sense to use system libraries when possible. I was simply trying to reduce friction when using my library by building all of the third-party libraries directly. I've nearly sorted out how to use find_package to locate vcpkg libraries. I'll get the port modified and update the pull request accordingly soon.

2017-02-22 00:46 UTC, ras0219-msft commented
@tfussell Any progress here?

2017-02-22 13:32 UTC, tfussell commented
I'm working hard to get this working. This cross-platform support is turning out to be complicated. I hope to have an update for you by the weekend. Sorry it's taking so long. @ras0219-msft

2017-02-23 04:02 UTC, ras0219-msft commented
No problem at all, I just wanted to check in.

Please take your time to make sure it's in a state you can maintain going forward. I'd be happy to help on any decisions you're unsure about.

2017-03-13 00:56 UTC, Mixaill requested changes

2017-03-13 00:56 UTC, Mixaill commented on ports/xlnt/portfile.cmake
> +set(GIT_URL "https://github.com/tfussell/xlnt.git")
Maybe we should switch to download revision by URL?

`https://github.com/<user>/<project>/archive/<hash>.zip`

`https://github.com/tfussell/xlnt/archive/f908dca6fe342f44b814073947aaccc69df7c9b6.zip`

2017-03-18 15:30 UTC, tfussell commented
@Mixaill Thanks for the suggestion. I've reconfigured the xlnt portfile based on your recommendation and some other example ports I found. @ras0219-msft It took more work than I anticipated, but I believe my library and associated port now meet all of your requirements. static/dynamic and x86/x64 builds are all working on my end. Let me know if you need me to do anything else for this to be merged.

2017-03-22 00:31 UTC, ras0219-msft commented
Looks great, thanks for the hard work!

2017-03-22 00:31 UTC, merged