Check scripts/cmake/* and buildsystems/vcpkg.cmake for changes when hashing
microsoft/vcpkg pull request #6036
Opened 2019-04-10 17:16 UTC by cbezault

2019-04-20 00:12 UTC, ras0219-msft requested changes

2019-04-20 00:12 UTC, ras0219-msft commented on toolsrc/src/vcpkg/build.cpp
> +            for (auto &script_file : fs::stdfs::recursive_directory_iterator(paths.scripts))
This appears to hash everything inside `scripts/` -- is that correct?

There are a lot of files in there that shouldn't be hashed (vcpkgTools.xml, bootstrap.sh, etc).

We should only hash `scripts/cmake/*`.

2019-04-20 05:47 UTC, cbezault commented on toolsrc/src/vcpkg/build.cpp
> +            for (auto &script_file : fs::stdfs::recursive_directory_iterator(paths.scripts))
It appears you're right, I'll fix that.

2019-05-10 21:34 UTC, vicroms commented
/AzurePipelines run

2019-05-13 17:59 UTC, vicroms commented
Hadn't seen this in a while:

```
vcpkg.exe has crashed.
Please send an email to:
    vcpkg@microsoft.com
containing a brief summary of what you were trying to do and the following data blob:

Version=2018.11.23-nohash
EXCEPTION='invalid string position'
```

2019-05-13 18:07 UTC, cbezault commented
I'll take a look this evening, was it static?

2019-05-13 18:10 UTC, vicroms commented
Yes, `x64-windows-static` while installing port `gdcm2`.

2019-05-20 17:35 UTC, ras0219-msft commented on toolsrc/src/vcpkg/build.cpp
> +            "vcpkg",
This should have a longer name to avoid being confused with the vcpkg tool itself. Maybe just `vcpkg.cmake` would be fine.

2019-05-20 17:47 UTC, cbezault commented on toolsrc/src/vcpkg/build.cpp
> +            "vcpkg",
done

2019-05-24 02:22 UTC, cbezault commented
/azp run

2019-05-26 04:45 UTC, cbezault commented
/azp run

2019-05-27 17:53 UTC, cbezault commented
/azp run

2019-05-28 18:35 UTC, cbezault commented
/azp run

2019-06-06 23:08 UTC, cbezault commented
/azp run

2019-07-01 22:12 UTC, ras0219-msft commented
/azp run

2020-05-07 17:43 UTC, closed without merging