[libgd] Fix static build
microsoft/vcpkg pull request #6307
Opened 2019-05-04 12:57 UTC by jumpinjackie

Fixes #6306 by reverting portfile changes made by  050e71d

2019-05-05 06:28 UTC, cenit requested changes

2019-05-05 06:28 UTC, cenit commented on ports/libgd/portfile.cmake
> +            -DBUILD_SHARED_LIBS=${LIBGD_SHARED_LIBS}
This variable is not necessary. We cleaned up not correctly this port, but i’d not fully revert to the previous situation. 
`BUILD_SHARED_LIBS` is an official cmake variable and is already properly initialized by the vcpkg toolchain. On the other hand, `BUILD_STATIC_LIBS` is not and must be manually initialized, and that’s the only variable we need to re-instate here

2019-05-05 13:14 UTC, jumpinjackie commented on ports/libgd/portfile.cmake
> +            -DBUILD_SHARED_LIBS=${LIBGD_SHARED_LIBS}
Yes, I've confirmed restoring this flag is indeed redundant.

2019-05-06 17:48 UTC, merged

2019-05-06 17:48 UTC, vicroms commented
Thanks for the PR!