[liblas] Add new port
microsoft/vcpkg pull request #6746
Opened 2019-06-04 06:35 UTC by wangli28

Related issue: #6634

2019-06-04 17:57 UTC, mloskot commented on ports/liblas/fix-BuildError.patch
> +-if (NOT CMAKE_BUILD_TYPE )
Removal of default `CMAKE_BUILD_TYPE` could be submitted to the upstream. I'd accept it.

2019-06-04 18:01 UTC, mloskot commented
Thanks for the update.

BTW, what does the `internal` label mean for Vcpkg?

2019-06-11 02:19 UTC, wangli28 commented
The build of this port on Windows has been passed, and the support for Linux will be added later.

2019-06-20 22:50 UTC, ras0219-msft requested changes

2019-06-20 22:50 UTC, ras0219-msft commented on ports/liblas/fix-BuildError.patch
> +-if (NOT CMAKE_BUILD_TYPE )
This should not be needed -- we always set CMAKE_BUILD_TYPE

2019-06-20 22:50 UTC, ras0219-msft commented on ports/liblas/portfile.cmake
> +set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/libLAS-${VERSION})
This is not needed because it will be set by `OUT_SOURCE_PATH` on line 15.

2019-06-20 22:50 UTC, ras0219-msft commented on ports/liblas/portfile.cmake
> +  OPTIONS -DBUILD_OSGEO4W=OFF # Disable osgeo4w
We need to pass `-DCMAKE_DISABLE_FIND_PACKAGE_xyz` based on the optional features enabled (zlib, jpeg); otherwise, these features will be accidentally enabled by someone running:
```
>vcpkg install zlib
>vcpkg install liblas
```

As an example, see https://github.com/microsoft/vcpkg/blob/e16efa4d6aa6f36247eb6dfd646fdf81af0c36e0/ports/xerces-c/portfile.cmake#L29

2019-07-06 00:29 UTC, ras0219-msft commented
/azp run

2019-07-19 00:37 UTC, dan-shaw requested changes

2019-07-19 00:37 UTC, dan-shaw commented on ports/liblas/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
Use `vcpkg_fixup_cmake_targets(CONFIG_PATH share/cmake/libLAS)` instead, it will move the debug config files to the right locations. We will also need to move `vcpkg_fixup_cmake_targets` to the end, since `debug/share` is only removed when the folder is empty. We might need to remove `liblas-depends.cmake` from `debug/share`.

2019-07-19 06:02 UTC, wangli28 commented on ports/liblas/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
Add `vcpkg_fixup_cmake_targets(CONFIG_PATH share/cmake/libLAS)` to fix config_path. But it cannot remove `debug/include` and `debug/share`. We need use `file(REMOVE_RECURSE)` to remove them.

2019-07-23 00:43 UTC, merged

2019-07-23 00:43 UTC, dan-shaw commented
Thanks for the PR!