Windows Port of libu2f-server
microsoft/vcpkg pull request #6781
Opened 2019-06-05 13:10 UTC by xgcssch

Documentation can be found here at [Yubico](https://developers.yubico.com/libu2f-server/)

2019-06-05 17:05 UTC, xgcssch commented
In the CI pipeline, the platforms x64-windows-static, x64-uwp and arm-uwp fail, despite building fine on a local machine.
It seems, that the includefiles for the dependencies jason-c and openssl are not installed.
I have no clue, why this happens.

2019-06-15 03:23 UTC, JackBoosY commented
/azp run

2019-06-20 22:45 UTC, dan-shaw commented
I've changed it so we don't use msbuild, and it appears that it passes on Linux.

2019-06-24 22:48 UTC, ras0219-msft requested changes

2019-06-24 22:48 UTC, ras0219-msft commented on ports/libu2f-server/windows.patch
> ++  u2fs_rc u2fs_get_challenge( u2fs_ctx_t * ctx, const char **challenge );
This looks like a "feature" -- why do we need these new functions patched in?

If these are feature changes, they should be pushed upstream and go through the normal OSS review process (see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-implement-features-in-patches)

2019-06-27 23:41 UTC, merged

2019-06-27 23:41 UTC, dan-shaw commented
Thanks for the PR!