[etcdcpp] Add new port
microsoft/vcpkg pull request #6999
Opened 2019-06-23 07:19 UTC by SamuelMarks

A C++ client library for [etcd](https://etcd.io). etcd is a distributed, reliable key-value store.

2019-07-03 18:07 UTC, dan-shaw commented
/azp run

2019-07-08 22:24 UTC, ras0219-msft requested changes

2019-07-08 22:24 UTC, ras0219-msft commented on ports/etcdcpp/CONTROL
> +Source: etcdcpp
Should probably be renamed to `offscale-libetcd-cpp` to avoid conflicting with the many different `etcdcpp`s.

From the etcd documentation[1]:

#### C++ libraries

- edwardcapriolo/etcdcpp - Supports v2
- suryanathan/etcdcpp - Supports v2 (with waits)
- nokia/etcd-cpp-api - Supports v2
- nokia/etcd-cpp-apiv3 - Supports v3

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/integrations.md

2019-07-11 18:09 UTC, merged

2019-07-11 18:09 UTC, dan-shaw commented
Thanks for the PR!