[zookeeper-mt] Add new port
microsoft/vcpkg pull request #7000
Opened 2019-06-23 07:21 UTC by SamuelMarks

> [Apache ZooKeeper](https://zookeeper.apache.org) is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.

2019-07-05 22:33 UTC, dan-shaw commented
@SamuelMarks Thanks for the PR! I've made some changes:

1) Added support for zookeeper_st shared library (it's the zookeeper[async] feature). However, by default zookeeper_mt is installed. I've also changed the name from zookeeper-mt to zookeeper since we now support both libraries.
2) I've made it into a static library since zookeeper doesn't support BUILD_SHARED_LIBS yet
3) I've also refactored some of the cmake

Let me know if I missed anything.

2019-07-06 01:43 UTC, ras0219-msft requested changes

2019-07-06 01:43 UTC, ras0219-msft commented on ports/zookeeper/CONTROL
> +Description: ZooKeeper with only the async API
Features should always model adding additional functionality -- in this case, this sounds like we should have a `sync` feature that is part of `Default-Features:` and removing it will cause only the async api to be built.

2019-07-06 01:43 UTC, ras0219-msft commented on ports/zookeeper/portfile.cmake
> +    PREFER_NINJA
May need `DISABLE_PARALLEL_CONFIGURE` if zookeeper's configuration step writes to the source directory.

2019-07-06 21:52 UTC, merged

2019-07-06 21:53 UTC, dan-shaw commented
Thanks for the PR!