[wintoast] Add new port.
microsoft/vcpkg pull request #7006
Opened 2019-06-24 02:31 UTC by NancyLi1013

WinToast is a lightly library written in C++ which brings a complete integration of the modern toast notifications of Windows 8 & Windows 10.
Related issue #6706.

2019-06-24 20:39 UTC, ras0219-msft requested changes

2019-06-24 20:39 UTC, ras0219-msft commented on ports/wintoast/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/src/wintoastlib.cpp
We should generally build cpp source files into a library instead of installing them.

In this case, we should write a CMakeLists.txt that builds a static library and add `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` to the top of this portfile.

2019-06-25 06:14 UTC, NancyLi1013 commented on ports/wintoast/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/src/wintoastlib.cpp
I just added CMakeLists.txt file and updated this portfile. Please help check it again. Thanks.

2019-06-27 02:13 UTC, NancyLi1013 commented
WinToast only supports on Windows platform. So the current results are expected. And it doesn't currently support UWP. I have added the message in portfile.cmake.

2019-07-01 20:55 UTC, vicroms commented
Thanks for the PR!

2019-07-01 21:03 UTC, vicroms requested changes

2019-07-01 21:03 UTC, vicroms commented on ports/wintoast/CMakeLists.txt
> +add_library(wintoast ${SRC_FILES} ${HEADER_FILES})
Header files should be added using `target_include_directories`

```
target_include_directories(wintoast PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>
  $<INSTALL_INTERFACE:include/wintoast>
)
```

And installed using

```
# Install headers
if (INSTALL_HEADERS)
  install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/src/wintoatstlib.h DESTINATION include/wintoast)
endif()
```

The `INSTALL_HEADERS` option allows us to skip installing headers during the debug build by setting the option to `OFF` during `vcpkg_configure_cmake()`

2019-07-03 08:09 UTC, NancyLi1013 commented on ports/wintoast/CMakeLists.txt
> +add_library(wintoast ${SRC_FILES} ${HEADER_FILES})
Thanks for your review and advice.

2019-07-07 08:45 UTC, MikeGitb commented on ports/wintoast/CMakeLists.txt
> +add_library(wintoast ${SRC_FILES} ${HEADER_FILES})
May I say that I find the practice of including the header of a single header library via `#include <HeaderName.h>` instead of `#include Libname/HeaderName.h` really annoying?

2019-07-15 21:58 UTC, vicroms commented
/azp run

2019-07-15 23:32 UTC, vicroms commented
@NancyLi1013 

Thanks for the PR!

2019-07-15 23:33 UTC, merged