[Newport] Paho MQTT C++ library: pahomqttpp3
microsoft/vcpkg pull request #7033
Opened 2019-06-25 18:50 UTC by thedevilfish

This is a pull request to support Eclipse's Paho MQTT C++ library. More more information about the library please see: [Eclipse Paho](https://github.com/eclipse/paho.mqtt.cpp)

2019-06-26 05:08 UTC, ras0219-msft requested changes

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/CONTROL
> +Build-Depends: openssl, paho-mqtt
Should openssl be removed from here, since it is a feature?

Also, ssl sounds like a good candidate for a `Default-Features:`.

Finally, note that `paho-mqtt` _only_ builds with ssl right now, so disabling openssl here won't actually remove the openssl dependency.

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +if (openssl IN_LIST FEATURES)
`openssl` should be quoted here.

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +      -DCMAKE_PREFIX_PATH=${PAHO_C_LIBRARY_PATH}    #  -DCMAKE_PREFIX_PATH=path to Paho MQTT C library
Setting CMAKE_PREFIX_PATH should not be needed -- our toolchain file will add the appropriate directories to CMAKE_PREFIX_PATH.

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +  # Paho-Mqtt CPP doesn't work well with Ninja. Best is to generate 'NMake Makefiles'
If the problem is parallelism, we can pass `DISABLE_PARALLEL` on windows systems to `vcpkg_install_cmake()`.

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +set(PAHO_C_LIBRARY_PATH "${CURRENT_INSTALLED_DIR}/lib")
This doesn't account for debug vs release; perhaps there is a better way to handle this problem?

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH "lib/cmake/PahoMqttCpp")
This will (by default) put the config files into `share/paho-mqttpp3/`, which will only work if they are named something like `Paho-Mqttpp3-config.cmake`.

I suspect these files are named something like `PahoMqttCppConfig.cmake`, so this call should have an extra argument: `TARGET_PATH share/pahomqttcpp`.

We'd hope for this to be caught by the `vcpkg_test_cmake()` line, however it is currently under construction unfortunately 🚧 .

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +  set(PAHO_C_LIB "${PAHO_C_LIBRARY_PATH}/${PAHO_C_LIBNAME}")
This will need to be set differently for release vs debug

2019-06-26 05:08 UTC, ras0219-msft commented on ports/paho-mqttpp3/portfile.cmake
> +  set(PAHO_C_LIB "${PAHO_C_LIBRARY_PATH}/${PAHO_C_LIBNAME}")
Also, how does this work without the library's extension (`.a`, `.lib`)?

2019-06-26 13:48 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +  # Paho-Mqtt CPP doesn't work well with Ninja. Best is to generate 'NMake Makefiles'
I'm not sure if the problem is parallelism here. Is there any way to verify if the problem here is parallelism?

2019-06-26 13:55 UTC, thedevilfish commented on ports/paho-mqttpp3/CONTROL
> +Build-Depends: openssl, paho-mqtt
Since `paho-mqtt` is currently built with openssl, I will remove this dependency as per your suggestion. But, then we have to explicitly set `PAHO_WITH_SSL` to `ON` in `portfile.cmake`. So, should I do add this to our `portfile.cmake` then? (See below):

```cmake
# Add explicit dependency on SSL
set (PAHO_WITH_SSL ON)

# If SSL is defined as part of the feature list, we set that feature ON
if (openssl IN_LIST FEATURES)
  # Use OpenSSL support
  set(PAHO_WITH_SSL ON)
  # Link with 'paho-mqtt3as.lib'
  set(PAHO_C_LIBNAME paho-mqtt3as)
else()
  # Do not use OpenSSL support
  set(PAHO_WITH_SSL OFF)
  # Link with 'paho-mqtt3a.lib'
  set(PAHO_C_LIBNAME paho-mqtt3a)
endif()
```

2019-06-26 13:56 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +if (openssl IN_LIST FEATURES)
Done, will update the PR!

2019-06-26 14:17 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +  set(PAHO_C_LIB "${PAHO_C_LIBRARY_PATH}/${PAHO_C_LIBNAME}")
- I will check to see if the library names need to be set separately for debug and release.
- As far as I can tell, library extensions are actually specified inside the `paho.mqtt.cpp` cmake files. Hence I don't have to specify a `.a`, or a `.lib` extension.

2019-06-26 14:21 UTC, thedevilfish commented on ports/paho-mqttpp3/CONTROL
> +Build-Depends: openssl, paho-mqtt
Also, regarding your other note on `Default-Features:`, should I then remove the `openssl` feature since `paho-mqtt` builds with SSL only?

2019-06-26 14:40 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +  set(PAHO_C_LIB "${PAHO_C_LIBRARY_PATH}/${PAHO_C_LIBNAME}")
Actually, regarding the last point about library extensions (`.a`, `.lib`), 

When I see the install logs of vcpkg, I see the following on linux:
```
--- Installing: /home/dev/Projects/github/vcpkg/packages/paho-mqttpp3_x64-linux/lib/libpaho-mqttpp3.a
```
When I see the install logs on windows, I see the following on windows:
```Creating library src\paho-mqttpp3.lib and object src\paho-mqttpp3.exp
Microsoft (R) Incremental Linker Version 14.21.27702.2
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library src\paho-mqttpp3.lib and object src\paho-mqttpp3.exp
```

2019-06-26 14:55 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH "lib/cmake/PahoMqttCpp")
Will add.

2019-06-26 15:50 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +set(PAHO_C_LIBRARY_PATH "${CURRENT_INSTALLED_DIR}/lib")
Do you mean add a check such as this:
```cmake
if (NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
  set(PAHO_C_LIBRARY_PATH "${CURRENT_INSTALLED_DIR}/debug/lib")
else()
  set(PAHO_C_LIBRARY_PATH "${CURRENT_INSTALLED_DIR}/lib")
endif()
```
Frankly, I don't believe this makes a difference.

2019-06-26 16:02 UTC, thedevilfish commented on ports/paho-mqttpp3/portfile.cmake
> +  # Paho-Mqtt CPP doesn't work well with Ninja. Best is to generate 'NMake Makefiles'
I've tested this with Ninja again. Seems to be working with parallelism.

2019-06-27 13:13 UTC, thedevilfish reviewed
Addressed all code review comments.

2019-06-28 13:27 UTC, thedevilfish commented
@ras0219 I've updated the pull request with your comments. Please can you review my changes? Thanks in advance!

2019-07-02 14:36 UTC, thedevilfish reviewed
Addressed code review comments.

2019-07-15 21:17 UTC, vicroms commented
@thedevilfish 
Thanks for the PR !

2019-07-15 21:17 UTC, merged