[vcpkg] Portfile Settings
microsoft/vcpkg pull request #7292
Opened 2019-07-16 23:05 UTC by cbezault

This PR allows you to add a `port_settings.cmake` file to a port to override settings defined in the triplet globally or to define settings which govern the behavior of the vpckg binary on a per port basis.

Written on top of #7290

2019-07-18 21:17 UTC, vicroms requested changes

2019-07-18 21:17 UTC, vicroms commented on toolsrc/src/vcpkg/build.cpp
> +                    paths.ports / port.value_or_exit(VCPKG_LINE_INFO) / "port-settings.cmake");
This won't work with overlay ports, it will always resolve to `<vcpkg_root>/ports/<port>/port-settings.cmake`. 

You can get the correct port directory from `BuildPackageConfig.config.ports_dir` which seems to be available from all calling sites.

2019-07-18 21:29 UTC, grdowns commented on toolsrc/src/vcpkg/build.cpp
> +                    paths.ports / port.value_or_exit(VCPKG_LINE_INFO) / "port-settings.cmake");
Yikes. This seems like a trap people can fall into easily

2019-07-18 21:35 UTC, vicroms commented on toolsrc/src/vcpkg/build.cpp
> +                    paths.ports / port.value_or_exit(VCPKG_LINE_INFO) / "port-settings.cmake");
Yes, probably should rename the variables in `VcpkgPaths`

- `ports` -> `default_ports`
- `triplets` -> `default_triplets`

or something similar.

2019-07-18 22:54 UTC, cbezault commented on toolsrc/src/vcpkg/build.cpp
> +                    paths.ports / port.value_or_exit(VCPKG_LINE_INFO) / "port-settings.cmake");
Woops, yeah that's a big mistake and should probably be changed :/

2019-07-18 22:59 UTC, cbezault commented on toolsrc/src/vcpkg/build.cpp
> +                    paths.ports / port.value_or_exit(VCPKG_LINE_INFO) / "port-settings.cmake");
I think I'm just going to change the build config to contain a `SourceControlFileLocation`.

2019-07-18 23:54 UTC, vicroms commented on toolsrc/include/vcpkg/build.h
> +            , port_dir(scfl.source_location)
Shouldn't this member be removed now that this can be obtained from `scfl`.

2019-07-19 00:30 UTC, cbezault commented on toolsrc/include/vcpkg/build.h
> +            , port_dir(scfl.source_location)
Sure, but why not just keep the reference for convenience?
Fewer changes that way.

2019-07-19 05:03 UTC, vicroms approved these changes

2019-07-19 07:36 UTC, Rastaban approved these changes

2019-07-19 15:01 UTC, merged