fix error message for debug/share
microsoft/vcpkg pull request #7406
Opened 2019-07-24 19:44 UTC by dan-shaw

2019-08-08 20:50 UTC, ras0219-msft requested changes

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
> +            if (std::regex_search(path.generic_u8string(), std::regex(R"(share/[^/]*)")))
Pull out `path.generic_u8string()` and reuse it

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
> +            if (std::regex_search(path.generic_u8string(), std::regex(R"(share/[^/]*)")))
How does this handle `C:\share\vcpkg\packages\zlib_x64-windows\...`?

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
> +            if (std::regex_search(path.generic_u8string(), std::regex(R"(share/[^/]*)")))
Generally, regex is probably not a good fit for this problem. Instead, we should use the `fs::path` APIs to iterate through and check for relevant path elements.

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
> +                std::regex_search(path.generic_u8string(), std::regex(R"([^/]*Config.cmake)")))
`Strings::ends_with(path.filename().generic_u8string(), "-config.cmake")` et al.

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
> +            for (auto&& file : files_found)
Instead of first gathering the files matching the conditions, then looping again through those files and checking the conditions again, it would be simpler to just build the config message as you go along in a single loop.

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
> +            Checks::check_exit(VCPKG_LINE_INFO, false, "");
We should use another mechanism to suppress other messages instead of exiting here.

2019-08-08 20:50 UTC, ras0219-msft commented on toolsrc/src/vcpkg/postbuildlint.cpp
>          error_count += check_for_files_in_debug_share_directory(fs, package_dir);
Consider fusing these checks together to print the clearest messages possible for the user. (check_config_paths, check_for_files_in_debug_share_directory, check_folder_lib_cmake, check_folder_debug_lib_cmake)

2020-01-22 03:20 UTC, PhoebeHui commented
@dan-shaw, could you please resolve the conflicts?

2020-01-31 00:46 UTC, closed without merging