[imgui-sfml] Add new package ImGui-SFML
microsoft/vcpkg pull request #7429
Opened 2019-07-25 21:20 UTC by tntxtnt

* Static build only to match with `imgui`.

2019-07-25 22:51 UTC, eliasdaler requested changes
Thanks for submitting the PR. I feel like having ImGui-SFML on vcpkg would be helpful.
However, I feel like some things can be improved and maybe there'll be less patches required if ImGui-SFML fixes some of the problems you've had to work around.

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/require-c++11.patch
> ++set(CMAKE_CXX_STANDARD_REQUIRED ON)
Why is C++11 required? ImGui-SFML, ImGui and SFML can build with C++03 just fine.

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
Not sure if this is necessary.

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# if(NOT IMGUI_DIR)
Does vcpkg set `imgui_DIR`? Maybe I can just allow users to specify how ImGui should be searched for (e.g. "ImGui" or "imgui"), so we'll have something like this:

```cmake
if(NOT ${IMGUI_NAME}_DIR)
   ...
endif()
```

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++find_package(imgui REQUIRED)
This looks like `${IMGUI_NAME}` variable would be useful again. Not sure what to do about the version, maybe vcpkg script for ImGui should set `imgui_VERSION` and I'll be able to compare it afterwards, not during `find_package`?

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# set(IMGUI_PUBLIC_HEADERS
Not sure if this is needed for patch - yes, it won't be used, but patch should be as minimal as possible, in my opinion.

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> +-            #define IMGUI_API __declspec(dllexport)
Does this really affect anything? If ImGui-SFML is compiled statically, then IMGUI_SFML_EXPORTS should not be defined?

2019-07-25 22:51 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> +-        #define IMGUI_API __attribute__ ((visibility("default")))
Okay, maybe I'll need to add `#ifndef IMGUI_API` before this, but again, I wonder if it really affects anything.

2019-07-25 23:18 UTC, tntxtnt commented on ports/imgui-sfml/require-c++11.patch
> ++set(CMAKE_CXX_STANDARD_REQUIRED ON)
Somehow in the x64-osx build I got this error:
```
In file included from /Users/vagrant/azure_agent/_work/3/s/buildtrees/imgui-sfml/src/v2.0.2-d5398dcc0e/imgui-SFML.cpp:2:
/Users/vagrant/azure_agent/_work/3/s/installed/x64-osx/include/imgui.h:192:5: error: delegating constructors are permitted only in C++11
    IM_VEC4_CLASS_EXTRA     // Define additional constructors and implicit cast operators in imconfig.h to convert back and forth between your math types and ImVec4.
    ^~~~~~~~~~~~~~~~~~~
```
error: delegating constructors are permitted only in C++11 

So I add C++11 to your CMakeLists. It's from `imgui.h` though, I don't know why only x64-osx build failed with this.

2019-07-25 23:21 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# if(NOT IMGUI_DIR)
vcpkg `imgui` doesn't provide version. Someone provided [`CMakeLists.txt`](https://github.com/microsoft/vcpkg/blob/master/ports/imgui/CMakeLists.txt) without version: `project(imgui CXX)`

2019-07-25 23:25 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
I just want to use vcpkg's `find_package(imgui REQUIRED)` so I disable all of your FindImgui cmake as they are not needed (I guess)

2019-07-25 23:38 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
Maybe I should put a check for osx triplet and enable C++11 for osx build only.

2019-07-26 00:20 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> +-        #define IMGUI_API __attribute__ ((visibility("default")))
You can include it but I think it's kinda weird to define another library's defines when you don't build that library (use vcpkg's imgui) so I removed them.

2019-07-26 00:23 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> +-        #define IMGUI_API __attribute__ ((visibility("default")))
On second thought I should include them since imgui-sfml is imgui's replacement.

2019-07-26 02:39 UTC, tntxtnt commented on ports/imgui-sfml/require-c++11.patch
> ++set(CMAKE_CXX_STANDARD_REQUIRED ON)
Ah, so in `imconfig-SFML.h` you use delegating constructors, which is a C++11 feature:
```cpp
#define IM_VEC4_CLASS_EXTRA                                             \
    ImVec4(const sf::Color & c)                                         \
        : ImVec4(c.r / 255.f, c.g / 255.f, c.b / 255.f, c.a / 255.f) {  \
    }                                                                   \
```
Could be (badly 😄) rewritten to:
```cpp
#define IM_VEC4_CLASS_EXTRA                                             \
    ImVec4(const sf::Color & c)                                         \
        : x(c.r / 255.f), y(c.g / 255.f), z(c.b / 255.f), w(c.a / 255.f) {  \
    }                                                                   \
```

2019-07-26 10:36 UTC, eliasdaler commented on ports/imgui-sfml/require-c++11.patch
> ++set(CMAKE_CXX_STANDARD_REQUIRED ON)
Yes, this should be fixed in ImGui-SFML - will do!

2019-07-26 10:37 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# if(NOT IMGUI_DIR)
I guess checking for version could be disabled in some cases... I'll thunk about it.

2019-07-26 10:39 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
Yes, FindImGui.cmake is not needed, if you use vcpkg's find module, but it won't really change anything, so I think to make patch smaller, this line should not be changed with it.

Also I might put some other useful CMake things in imgui-sfml's "cmake" directory, so this might break some other things.

2019-07-26 10:40 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
>  -#define ImTextureID unsigned int
Why is this line needed? ImTextureID should really be "unsigned int" for ImGui-SFML, not "void*"

2019-07-26 13:44 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
imgui-sfml needs these sources
```cmake
set(IMGUI_SOURCES
  ${IMGUI_INCLUDE_DIR}/imgui.cpp
  ${IMGUI_INCLUDE_DIR}/imgui_draw.cpp
  ${IMGUI_INCLUDE_DIR}/imgui_widgets.cpp
  ${IMGUI_INCLUDE_DIR}/misc/cpp/imgui_stdlib.cpp
)

set(IMGUI_DEMO_SOURCES
  ${IMGUI_INCLUDE_DIR}/imgui_demo.cpp
)
```
while vcpkg's imgui CMakeLists.txt has these compiled
```cmake
set(IMGUI_SOURCES
    imgui.cpp
    imgui_demo.cpp
    imgui_draw.cpp
    imgui_widgets.cpp
)
```
The only file that is missing is `misc/cpp/imgui_stdlib.cpp`, which it states that it needs C++11: https://github.com/ocornut/imgui/blob/d057550209d794461744a91c812bf8e9e264f32f/misc/cpp/imgui_stdlib.h#L5

2019-07-26 13:46 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
And since vcpkg has those sources already compile so you won't find these .cpp files, which create a cmake config error so I don't use it.

2019-07-26 14:00 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# if(NOT IMGUI_DIR)
I could make vcpkg's imgui to export `imguiConfigVersion.cmake` with [`write_basic_package_version_file`](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file) but CMake requires `COMPATIBILITY mode` which if you choose `SameMinorVersion|ExactVersion` 1.68 will not be compatible with 1.70, if you choose `AnyNewerVersion|SameMajorVersion` then 1.00 may be compat with 1.70 which is wrong, as new imgui doesn't guarantee backward compat between minor versions, so `SameMinorVersion|ExactVersion` should be compat mode here. However that will require `imgui-sfml` port to change `imgui` version everytime `imgui` updates new version, and it doesn't guarantee compatibility with newer verions...

Maybe you should include an exact verison of `imgui`, i.e. 1.68, in `imgui-sfml`, and don't depend on system's `imgui` anymore. Not sure if it's the right thing to do.

2019-07-26 14:14 UTC, tntxtnt commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
>  -#define ImTextureID unsigned int
It creates a linkage error with static build of vcpkg's imgui. C++ name mangling magic treats imgui static compiled `Imgui::Image(...` and imgui-sfml `Imgui::Image(unsigned int, ...` differently so you either have to compile `imgui` with `imgui-sfml` (which you can't in this case, vcpkg's static compiled imgui), or don't define it and use imgui's `typedef void* ImTextureID;`

2019-07-26 15:27 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
imgui_stdlib functions don't need C++11 to compile, but they're not guaranteed to work. That's an imporant difference.

As for the sources vs linking to target - yeah. Again, ImGui-SFML needs to add some flags which will allow you to either build ImGui along with ImGui-SFML or link to it in some other way.

2019-07-26 15:29 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
> ++# if(NOT IMGUI_DIR)
ImGui is mostly stable in the part that ImGui-SFML uses. ImGui's widgets functions/interfaces can change, but that will break client's ImGui code, not ImGui-SFML's code.
So in my opinion requiring specific version of ImGui doesn't feel right.

2019-07-26 15:33 UTC, eliasdaler commented on ports/imgui-sfml/static-build-with-vcpkg-imgui.patch
>  -#define ImTextureID unsigned int
I see. Well, I hope that doesn't break something.

Also yeah, it looks like using external 'imgui' package with imgui-sfml is kinda painful... I've thought about adding ImGui as git submodule for ImGui-SFML here: https://github.com/eliasdaler/imgui-sfml/issues/81 ... and maybe it'll make the whole process easier if you don't depend on ImGui's vckpg package.

2019-08-08 13:04 UTC, dan-shaw commented
@tntxtnt @eliasdaler Is this ready to be merged?

2019-08-08 13:50 UTC, tntxtnt commented
It's still missing `misc/cpp/imgui_stdlib.cpp` from `imgui` port but I think it's ok.

2019-09-03 21:45 UTC, merged

2019-09-03 21:46 UTC, dan-shaw commented
Thanks for the PR! I've merged this, but it may be updated in #8004.