Hermes
microsoft/vcpkg pull request #7463
Opened 2019-07-29 22:40 UTC by mganandraj

Creating VcPkg port for the new JavaScript engine by Facebook, tailored for react-native applications. More details can be found at https://github.com/facebook/hermes. Also, I hope the inline comments in the portfile clarifies the steps.

2019-08-06 22:07 UTC, vicroms requested changes

2019-08-06 22:07 UTC, vicroms commented on ports/hermes/portfile.cmake
> +set(LLVM_BUILD_RELATIVE_PATH llvm_build_${VCPKG_TARGET_ARCHITECTURE})
This should use our `llvm` package instead of trying to build it's own copy.
You will need to add the extra configuration steps as a feature in the existing `llvm` package.

2020-01-19 07:12 UTC, JackBoosY commented
Pinging @mganandraj for response. Is work still being done for this PR?

2020-01-31 01:20 UTC, dan-shaw commented
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

2020-01-31 01:20 UTC, closed without merging