[status-value-lite, type-lite, value-ptr-lite] Add new ports
microsoft/vcpkg pull request #7563
Opened 2019-08-06 08:58 UTC by NancyLi1013

Related issue #1489.

2019-08-08 23:51 UTC, cbezault requested changes

2019-08-08 23:51 UTC, cbezault commented on ports/status-value-lite/portfile.cmake
> +       -DNSSV_OPT_BUILD_TESTS=OFF
Make tests and examples two features.

2019-08-08 23:51 UTC, cbezault commented on ports/type-lite/portfile.cmake
> +        -DTYPE_LITE_OPT_BUILD_TESTS=OFF
Make tests and examples two features.

2019-08-08 23:51 UTC, cbezault commented on ports/value-ptr-lite/portfile.cmake
> +        -DVALUE_PTR_LITE_OPT_BUILD_TESTS=OFF
Make tests and examples two features.

2019-08-09 06:17 UTC, PhoebeHui commented on ports/status-value-lite/portfile.cmake
> +       -DNSSV_OPT_BUILD_TESTS=OFF
@cbezault, from [doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-build-testsdocsexamples-by-default), it seems the test and examples to be disabled to minimizes build time, and optionally to add a test feature, I just think to disable them simply, and add them as feature when user need. what do you think?

2019-08-12 16:42 UTC, cbezault commented on ports/status-value-lite/portfile.cmake
> +       -DNSSV_OPT_BUILD_TESTS=OFF
I agree that by default tests should be disabled. I also think that there should be a way for the user to run the tests. Since right now the only mechanism we have that can allow that is features we should provide a test feature.

2019-08-26 07:57 UTC, NancyLi1013 commented on ports/status-value-lite/portfile.cmake
> +       -DNSSV_OPT_BUILD_TESTS=OFF
@cbezault, thanks for your review, As you and Phoebe talked above, we should make test as a feature. As for examples, we keep the same as before that by default examples should be disabled. So I just add test feature.

2019-08-29 21:12 UTC, merged