[vcpkg] QoL: add host specific path separator to common definitions
microsoft/vcpkg pull request #7598
Opened 2019-08-08 12:41 UTC by Neumann-A

2019-08-12 06:35 UTC, vicroms commented
I'm not sure about this one.

- Most ports that would require `VCPKG_HOST_PATH_SEPARATOR` should be using `vcpkg_add_to_path()` instead.
- This could work better as a standalone function `vcpkg_replace_path_separators()` or as an option in `vcpkg_execute_required_process(... USE_HOST_PATH_SEPARATORS)`.
- Nitpick: I feel that the word separator is a bit ambiguous between file-path separators ('/', '\') and path separators (':', ':').

In my limited search I couldn't find any port that would benefit from this aside from `ffmpeg`.

Do you have any more examples where this could be taken advantage of?

2019-08-12 08:29 UTC, Neumann-A commented
> Nitpick: I feel that the word separator is a bit ambiguous between file-path separators ('/', '') and path separators (':', ':').

If you google it the name "path separator" seems to always relate to  (';', ':').
See:
https://stackoverflow.com/questions/5971964/file-separator-or-file-pathseparator
https://docs.microsoft.com/de-de/dotnet/api/system.io.path.pathseparator?view=netframework-4.8
so the ship naming this thing has already shipped. 

The ('/', '\') would probably be called directory separators? (Yeah wikipedia says the same: https://en.wikipedia.org/wiki/Path_(computing))

> In my limited search I couldn't find any port that would benefit from this aside from ffmpeg

hmm there is also `vcpkg_build_qmake` and `vcpkg_build_cmake` which should use `vcpkg_add_to_path`. 
I also couldn't find any other port aside from ffmpeg which would currently benefit from it. On the other hand if it is used and something other like vcpkg_add_path should be used searching for it becomes trivial. So even if it is not used it has its benefits. 

> This could work better as a standalone function vcpkg_replace_path_separators() 

That is not needed if the variables are declared 
`list(JOIN ${LIST_OF_PATHS} ${VCPKG_HOST_PATH_SEPARATOR_ESCAPED} output_with_correct_separators)`

2019-08-21 10:00 UTC, Neumann-A commented
nmap might benefit:
```
set(ENV{INCLUDE} "${CURRENT_INSTALLED_DIR}/include;$ENV{INCLUDE}")
set(ENV{LIB} "${CURRENT_INSTALLED_DIR}/lib;$ENV{LIB}")
```

2019-09-07 01:47 UTC, ras0219-msft requested changes
Fundamental design LGTM other than the above comments.

2019-09-07 01:47 UTC, ras0219-msft commented on scripts/cmake/vcpkg_build_qmake.cmake
> +        vcpkg_add_to_path(PREPEND "${CURRENT_INSTALLED_DIR}${_BUILD_PREFIX}/bin")
This can end up using `_BUILD_PREFIX` from above.

Unless these can be combined usefully into a loop somehow, I think we should not use this variable indirection (and same argument for `_int_build_type`).

2019-09-07 01:47 UTC, ras0219-msft commented on scripts/cmake/vcpkg_common_definitions.cmake
> +    set(VCPKG_HOST_PATH_SEPARATOR_ESCAPED "\\;") #sometimes needed to differentiate between the cmake list separator
This seems inappropriate to provide unless we have a use case proving that it works.

2019-09-20 10:54 UTC, Neumann-A commented on scripts/cmake/vcpkg_common_definitions.cmake
> +    set(VCPKG_HOST_PATH_SEPARATOR_ESCAPED "\\;") #sometimes needed to differentiate between the cmake list separator
i removed `VCPKG_HOST_PATH_SEPARATOR_ESCAPED` and added a usage requirement for VCPKG_HOST_PATH_SEPARATOR. VCPKG_HOST_PATH_SEPARATOR  should only be used within "" and variables using VCPKG_HOST_PATH_SEPARATOR  can only be passed around in "" (which is probably the only correct way in cmake to handle paths anyway due to the possibility of spaces in paths)

2019-09-20 10:57 UTC, Neumann-A commented on scripts/cmake/vcpkg_build_qmake.cmake
> +        vcpkg_add_to_path(PREPEND "${CURRENT_INSTALLED_DIR}${_BUILD_PREFIX}/bin")
fixed

2019-09-23 22:19 UTC, vicroms approved these changes

2019-09-23 22:20 UTC, vicroms commented
LGTM

2019-11-22 17:45 UTC, merged

2019-11-22 17:45 UTC, ras0219-msft commented
Thanks for the PR!