[libsbml]Add new port
microsoft/vcpkg pull request #7673
Opened 2019-08-14 04:48 UTC by JackBoosY

Related: #7612.

2019-08-15 17:03 UTC, cbezault requested changes

2019-08-15 21:36 UTC, cbezault commented
For now just depend on libxml2.

2019-08-16 17:10 UTC, cbezault commented
Hey @JackBoosY it looks like this PR took some changes directly from https://github.com/fbergmann/vcpkg/tree/master/ports/libsbml without any attribution.

I recognize that you made significant changes to the port to get it to work but we can't accept this PR as is. Could you please rebase this work on top of @fbergmann 's fork? @fbergmann if you'd like to see your changes mainlined could you please sign the CLA?

2019-08-16 17:10 UTC, closed without merging

2019-08-16 17:14 UTC, cbezault commented on ports/libsbml/CONTROL
> -Build-Depends: libsbml[expat] or libsbml[libxml2]
We can't rely on Default-Features because some could just say `vcpkg install libsbml[core]` and it has to be able to build. libsbml requires either `expat` or `libxml2` but we need to just choose one, in this case we should choose `libxml2` since pretty much every sbml library with prebuilt binaries uses it.

2019-08-16 21:42 UTC, fbergmann commented on ports/libsbml/CONTROL
> -Build-Depends: libsbml[expat] or libsbml[libxml2]
I actually would prefer the default to be expat, as it has much lower requirements, and provides all the options that libSBML would need. libxml2 already needs 2 other libraries.

2019-08-19 04:06 UTC, JackBoosY commented
@fbergmann Please merge this PR modification into your branch.

Thanks.