QoL: Buildtype variables for looping over buildtypes
microsoft/vcpkg pull request #7733
Opened 2019-08-16 23:39 UTC by Neumann-A

While working on the qt scripts I often defined those variables below to avoid unnecessary code duplication to loop over the different buildtypes

2019-09-07 01:59 UTC, ras0219-msft commented
Thanks for the PR!

This _in principle_ seems like it could be a useful abstraction, but I'd like to see it demonstrated in multiple contexts before merging.

Specifically, if it turns out to only be useful in Qt5, then it should be private to Qt5. However, if it can be used to make code significantly cleaner and clearer in more contexts, I'd like to see this PR introduce at least two of those refactorings.

2019-09-07 18:57 UTC, Neumann-A commented
TODO (only 2 of N):
- [ ] Refactor vcpkg_build_cmake
- [ ] Refactor vcpkg_build_msbuild
- [ ] Refactor vcpkg_build_qmake
- [ ] Refactor vcpkg_configure_cmake
- [ ] Refactor vcpkg_configure_meson
- [ ] Refactor vcpkg_configure_qmake
- [ ] Refactor vcpkg_fixup_cmake_targets
- [ ] Refactor vcpkg_install_meson (a bit short for a refactor, but consistency is important)
- [ ] Refactor vcpkg_install_msbuild
- [ ] Refactor an unknown number of ports which might benift from the PR (purely optional; but at least qt if the update to 5.12.4 PR is merged.)

2020-01-14 04:33 UTC, JackBoosY commented
Please resolve these conflicts.

Thanks.

2020-05-14 02:29 UTC, JackBoosY commented
Pinging @Neumann-A  for response. Is work still being done for this PR?

2020-05-14 06:41 UTC, Neumann-A commented
@JackBoosY: You put the PR back into Draft?!?! I consider it finished for the time unless there is something which needs to ne fixed which I don't know of or you want some changes to it. Maybe run a full rebuild of everything to check if everything is working as intended.

2020-05-14 09:00 UTC, JackBoosY commented
@Neumann-A Sorry, my fault.

2020-05-14 09:02 UTC, JackBoosY commented
/azp run

2020-05-15 02:17 UTC, JackBoosY commented
Could you select some ports to test these functions?

2020-05-18 11:40 UTC, Neumann-A commented
hmm most regressions are failed due to download failures. The rest seems to be port build issues and not related to these changes.

2020-05-19 07:46 UTC, JackBoosY commented
Test result:
- sdl2:x64-uwp: failed on master branch.

Waiting for other pipeline results...

2020-05-19 12:49 UTC, Neumann-A commented
Hmm from the whole list only two ports seem to be relevant which are:
```
seal:x64-linux : needs further investigate
libfabric:x64-windows-static : needs further investigate
```
I was able to build both successfully using this branch.

2020-05-20 03:11 UTC, JackBoosY commented
@Neumann-A Yep, I also can't repro that in my machine.

2020-05-21 09:22 UTC, JackBoosY commented
OMG...more and more different regressions...

2020-05-21 09:26 UTC, JackBoosY commented
- [ ] osg:x64-linux
- [ ] signalrclient:x64-linux
- [ ] opencc:x64-linux
- [ ] seal:x64-linux
- [ ] xmsh:x64-osx
- [ ] rply:x64-osx
- [ ] seal:x64-osx
- [ ] signalrclient:x64-osx
- [ ] gmp:x64-osx
- [ ] rply:x64-uwp
- [ ] solid3:x64-uwp
- [ ] protobuf:x64-uwp
- [ ] signalrclient:x64-windows
- [ ] seal:x64-windows
- [ ] libaiff:x64-windows
- [ ] monkeys-audio:x64-windows
- [ ] rply:x64-windows
- [ ] pdal:x64-windows
- [ ] gmp:x64-windows
- [ ] dmlc:x64-windows
- [ ] icu:x64-windows
- [ ] signalrclient:x64-windows-static
- [ ] seal:x64-windows-static
- [ ] dcmtk:x64-windows-static
- [ ] icu:x64-windows-static
- [ ] rply:x64-windows-static
- [ ] pdal:x64-windows-static
- [ ] gmp:x64-windows-static
- [ ] zxing-cpp:x64-windows-static
- [ ] libfabric:x64-windows-static
- [ ] signalrclient:x86-windows
- [ ] seal:x86-windows
- [ ] monkeys-audio:x86-windows
- [ ] gsoap:x86-windows
- [ ] rply:x86-windows
- [ ] pdal:x86-windows
- [ ] gmp:x86-windows
- [ ] icu:x86-windows

2020-05-21 10:10 UTC, JackBoosY commented
/azp run

2020-05-22 04:00 UTC, BillyONeal commented
This PR always seems to be the first one that triggers msys losing it ¯\\\_(ツ)\_/¯

2020-05-22 04:01 UTC, BillyONeal commented
/azp run

2020-05-22 04:31 UTC, BillyONeal commented
Either the msys servers relied upon by some ports are broken causing CI failure, or something in this change causes CI to hang consistently.

2020-05-22 04:59 UTC, BillyONeal commented
This change depends on msys being fixed as in https://github.com/microsoft/vcpkg/pull/11443 or https://github.com/microsoft/vcpkg/pull/11471

2020-05-22 08:14 UTC, Neumann-A commented
@JackBoosY: None of those regressions look like they are caused by this PR. I assume some hidden unresolved dependencies in the ports which generate the errors in a full rebuild. (also see #11502 for comparison)

pdal: -> find_package issue. PostgreSQL::PostgreSQL in wrapper used without check if it actually exists.

2020-05-22 08:22 UTC, JackBoosY commented
@Neumann-A That's correct, I only want to know which port failed on the baseline.

2020-05-22 08:27 UTC, Neumann-A commented
@JackBoosY: Ah okay was just wondering due to the `requires:author-response` tag

2020-06-02 03:06 UTC, JackBoosY commented
/azp run

2020-06-09 06:07 UTC, JackBoosY commented
@Neumann-A pipelines are fixed, could you resolve the file conflict?

Thanks.

2020-06-09 08:23 UTC, Neumann-A commented
@JackBoosY: done

2020-06-12 05:39 UTC, JackBoosY commented
Can you merge the latest changes into this branch?

2020-06-15 08:53 UTC, PhoebeHui commented
/azp run

2020-06-18 06:56 UTC, PhoebeHui commented
/azp run

2020-06-18 07:51 UTC, PhoebeHui commented
@Neumann-A, ocilib:x86-windows and ocilib:x64-windows failed with debug mode, I noticed it only build release mode before, the solution doesn't configure debug mode, could you help have a look?

       "D:\buildtrees\ocilib\x86-windows-dbg\v4.6.4-271d6c24cf\proj\dll\ocilib_dll_vs2019.sln" (Rebuild target) (1) ->
       (ValidateSolutionConfiguration target) -> 
         D:\buildtrees\ocilib\x86-windows-dbg\v4.6.4-271d6c24cf\proj\dll\ocilib_dll_vs2019.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [D:\buildtrees\ocilib\x86-windows-dbg\v4.6.4-271d6c24cf\proj\dll\ocilib_dll_vs2019.sln]

2020-09-05 01:21 UTC, BillyONeal approved these changes

2020-11-16 06:01 UTC, JackBoosY commented
`monkeys-audio` regression will be fixed in another PR.

2020-11-19 22:28 UTC, ras0219 commented on scripts/cmake/vcpkg_common_definitions.cmake
> +    set(VCPKG_COPY_EXE_${_buildname} 1)
This should be set to `0` in the other branch.

2020-11-19 22:28 UTC, strega-nil requested changes
Thanks @Neumann-A, just some minor last changes and a few removals/deletions.

2020-11-19 22:28 UTC, strega-nil commented on scripts/cmake/vcpkg_common_definitions.cmake
> +## VCPKG_BUILDTREE_TRIPLET_DIR_<BUILDTYPE>  Path to current buildtype buildtree (e.g. CURRENT_BUILDTREES_DIR/TRIPLET-rel )
In discussion, we have agreed on the following things:

1. We probably shouldn't define `VCPKG_BUILD_CMAKE_TYPE_*` and `VCPKG_BUILD_QMAKE_CONFIG_*`, since they're build-system specific.
2. We should remove `VCPKG_BUILDTREE_TRIPLET_DIR_*`, since that's not a concept we want to codify.
3. We need to rename these:
  * `VCPKG_BUILD_LIST` -> `VCPKG_BUILD_TYPES`
  * `VCPKG_BUILD_SHORT_NAME_*` -> `VCPKG_BUILD_TYPE_SHORT_NAME_*`
  * `VCPKG_BUILD_TRIPLET_*` -> `VCPKG_LOGNAME_STEM_*` or something similar

`VCPKG_PATH_SUFFIX_*` is good as it is.

Additionally, we want to lowercase the build types in these, so that `VCPKG_BUILD_TYPES` becomes `release;debug`,
and the different variables are `VCPKG_PATH_SUFFIX_release`, `VCPKG_PATH_SUFFIX_debug`, etc.

2020-11-19 22:28 UTC, strega-nil commented on ports/3fd/portfile.cmake
> +vcpkg_copy_pdbs()
Should be removed from the diff.

2020-11-19 22:28 UTC, strega-nil commented on ports/libqglviewer/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENCE DESTINATION ${CURRENT_PACKAGES_DIR}/share/libqglviewer RENAME copyright)
Should be removed from the diff.

2020-11-19 22:28 UTC, strega-nil commented on ports/ocilib/portfile.cmake
> +    set(VCPKG_BUILD_LIST RELEASE)
Doesn't need to be done anymore.

2020-11-19 22:28 UTC, strega-nil commented on ports/ocilib/CONTROL
> +Port-Version: 1
Thus, this stays the same as well

2020-11-19 22:28 UTC, strega-nil commented on ports/qcustomplot/portfile.cmake
> +configure_file(${SOURCE_PATH}/GPL.txt ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)
Remove from the diff.

2020-11-20 10:35 UTC, Neumann-A commented on scripts/cmake/vcpkg_common_definitions.cmake
> +## VCPKG_BUILDTREE_TRIPLET_DIR_<BUILDTYPE>  Path to current buildtype buildtree (e.g. CURRENT_BUILDTREES_DIR/TRIPLET-rel )
Please re-discuss the following or give arguments:
> Additionally, we want to lowercase the build types in these

uppercase is the way to go since cmake variables itself are uppercase. If I don't use uppercase build types I always have to use a `string(UPPER)` for `VCPKG_DETECTED_<SOMELANGUAGE>_FLAGS_<SOMEBUILDTYPE_UPPER> `. I don't see any good reason to stick to lowercase build types here. (I mean I can also introduce `VCPKG_BUILD_TYPE_UPPER_<config>` if you plan to stick to lowercase configs but it will get complicated to access flags: `MY_C_FLAGS_${VCPKG_BUILD_TYPE_UPPER_${config}}` instead of `MY_C_FLAGS_${config}`)

>We should remove VCPKG_BUILDTREE_TRIPLET_DIR_*, since that's not a concept we want to codify.

The path is used so often and even inside portfiles. I can rename it to `_VCPKG_INTERNAL_BUILDTREE_TRIPLET_DIR_`

> VCPKG_BUILD_TRIPLET_* -> VCPKG_LOGNAME_STEM_* or something similar

although often used for the logname it is not only used there. It is also used in messages and paths/folders. 

>We probably shouldn't define VCPKG_BUILD_CMAKE_TYPE_* and VCPKG_BUILD_QMAKE_CONFIG_*, since they're build-system specific.

TODO: I'll move them to the configure scripts.

2020-11-20 18:21 UTC, strega-nil commented on scripts/cmake/vcpkg_common_definitions.cmake
> +## VCPKG_BUILDTREE_TRIPLET_DIR_<BUILDTYPE>  Path to current buildtype buildtree (e.g. CURRENT_BUILDTREES_DIR/TRIPLET-rel )
The thing is, `release` and `debug` aren't necessarily related to the CMake stuff, they're related to the vcpkg BUILD_TYPE stuff; even though the words are the same between VCPKG_BUILD_TYPE = release and CMAKE_BUILD_TYPE = Release, they're not necessarily the same thing, and we shouldn't use RELEASE just because CMake does for a related but different concept.

The big reason we want to do this is we wish to tie this to VCPKG_BUILD_TYPE. I think this would be a really unfortunate and weird feature if it weren't tied to VCPKG_BUILD_TYPE.

2020-11-25 20:30 UTC, Neumann-A commented on scripts/cmake/vcpkg_common_definitions.cmake
> +## VCPKG_BUILD_QMAKE_CONFIG_<BUILDTYPE>     Required QMAKE CONFIG flags for buildtype
```suggestion
```

2021-02-07 06:21 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2021-02-07 06:21 UTC, closed without merging