[wampcc] Add new port
microsoft/vcpkg pull request #7929
Opened 2019-08-27 18:54 UTC by SergeyLukashevich

Related to #7928

2019-08-27 21:02 UTC, cbezault requested changes

2019-08-28 11:37 UTC, cenit commented on ports/wampcc/portfile.cmake
> +        -DBUILD_SHARED_LIBS:BOOL=${USE_SHARED_RUNTIME}
Why this mixture between libs and runtime? Is it ok? 

BUILD_SHARED_LIBS is a standard CMake symbol and properly defined already by the vcpkg toolchain. If the "mixture" of libs on the left and crt on the right of the = symbol is by design, which means for example that the library when built as static works only with static CRT, that's a different problem and requires a different approach, similar to the vcpkg_check_linkage(ONLY_STATIC_LIBRARY) at the beginning

2019-08-29 06:06 UTC, SergeyLukashevich commented on ports/wampcc/portfile.cmake
> +        -DBUILD_SHARED_LIBS:BOOL=${USE_SHARED_RUNTIME}
Extra symbols are removed

2019-08-29 06:09 UTC, SergeyLukashevich commented on ports/wampcc/portfile.cmake
> +        -DBUILD_UTILS:BOOL=OFF
Utils and examples feature has been added. Tests build is broken in a recent version.

2019-09-03 17:48 UTC, dan-shaw commented on ports/wampcc/CONTROL
> +Version: 1.6
This appears to be a rolling-release port, so we want the version formatted as `YYYY-MM-DD` (the date that the commit was accessed by you).

2019-09-09 22:43 UTC, cbezault approved these changes

2019-09-09 22:43 UTC, merged