Port for libsrtp
microsoft/vcpkg pull request #8046
Opened 2019-09-04 18:37 UTC by sipsorcery

2019-09-09 23:38 UTC, vicroms commented
Build fails for UWP, are these failures expected?

2019-09-11 21:26 UTC, vicroms requested changes

2019-09-11 21:26 UTC, vicroms commented on ports/libsrtp/portfile.cmake
> +set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -D_CRT_SECURE_NO_WARNINGS /wd4703")
These lines should be inside an `if` block:

```
if (VCPKG_TARGET_IS_WINDOWS)
endif()
```

2019-09-12 04:37 UTC, sipsorcery commented on ports/libsrtp/portfile.cmake
> +set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -D_CRT_SECURE_NO_WARNINGS /wd4703")
Done.

2019-09-12 05:34 UTC, merged

2019-09-12 05:34 UTC, vicroms commented
Thanks for the PR!