[sdl1]Support linux build.
microsoft/vcpkg pull request #8070
Opened 2019-09-06 03:05 UTC by JackBoosY

Related: #8060.

2019-09-06 17:46 UTC, cbezault requested changes

2019-09-06 17:46 UTC, cbezault commented on ports/sdl1/portfile.cmake
> +    vcpkg_execute_required_process(
You should `vcpkg_execute_build_process` here.

2019-09-09 03:11 UTC, JackBoosY commented on ports/sdl1/portfile.cmake
> +    vcpkg_execute_required_process(
@cbezault After reading #6695, I still don't know the difference between `vcpkg_execute_required_process` and `vcpkg_execute_build_process`. May use `vcpkg_execute_build_process` to build with multiple cores? Or does it have special handling for build logs?

2019-09-09 20:33 UTC, cbezault commented on ports/sdl1/portfile.cmake
> +    vcpkg_execute_required_process(
`vcpkg_execute_build_process` takes both a parallel and non-parallel build mode because in parallel mode users sometimes run out of memory when linking. If a non-parallel mode is provided we retry with the non-parallel mode.

2019-09-09 20:35 UTC, cbezault requested changes

2019-09-09 20:35 UTC, cbezault commented on ports/sdl1/portfile.cmake
> +    vcpkg_execute_build_process(
don't think you need `vcpkg_execute_build_process` here.

2019-09-09 20:35 UTC, cbezault commented on ports/sdl1/portfile.cmake
> +        COMMAND "make"
You should try running `make -j ${VCPKG_CONCURRENCY}` and then just `make` as the non-parallel option.

2019-09-11 00:00 UTC, cbezault requested changes

2019-09-11 00:00 UTC, cbezault commented on ports/sdl1/portfile.cmake
> +        COMMAND "make -j ${VCPKG_CONCURRENCY}"
If you provide a parallel command you need to supply a non-parallel command

2019-09-11 17:42 UTC, merged

2019-09-11 17:42 UTC, cbezault reviewed
LGTM, thanks!

2019-12-03 08:33 UTC, CJCombrink commented on ports/sdl1/portfile.cmake
> +        message(FATAL_ERROR "autoreconf and libgles2-mesa-dev must be installed before libepoxy can build. Install them with \"apt-get dh-autoreconf libgles2-mesa-dev\".")
I don't normally comment on a merged PR but: 
1. Shouldn't this be `libsdl1` instead of `libepoxy` (suspecting copy paste issue)
1. Command should be `apt-get install ...`