[gtsam] Add new port
microsoft/vcpkg pull request #8127
Opened 2019-09-11 07:51 UTC by NancyLi1013

Related issue #5728.

2019-09-12 06:10 UTC, NancyLi1013 commented
It failed on static now. It needs more time to fix this issue. Besides this, this port doesn't currently support ARM and UWP due to it needs to depend on boost.

2019-10-21 03:08 UTC, JackBoosY requested changes

2019-10-21 03:08 UTC, JackBoosY commented on ports/gtsam/portfile.cmake
> +    REF 3.2.3
Use commit ID instead of tag name.

2019-10-21 03:08 UTC, JackBoosY commented on ports/gtsam/portfile.cmake
> +include(vcpkg_common_functions)
Remove this line.

2019-10-25 07:33 UTC, NancyLi1013 commented
The failure on `static `is due to this:
```
boost_serialization-vc140-mt-gd.lib(utf8_codecvt_facet.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_iarchive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(extended_type_info.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(archive_exception.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_oarchive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(extended_type_info_typeid.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_oserializer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_text_oprimitive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(text_oarchive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_iserializer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_text_iprimitive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(text_iarchive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_archive.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_serialization-vc140-mt-gd.lib(basic_serializer_map.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_filesystem-vc140-mt-gd.lib(path_traits.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_filesystem-vc140-mt-gd.lib(path.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_filesystem-vc140-mt-gd.lib(operations.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_filesystem-vc140-mt-gd.lib(codecvt_error_category.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_filesystem-vc140-mt-gd.lib(windows_file_codecvt.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_timer-vc140-mt-gd.lib(cpu_timer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
boost_chrono-vc140-mt-gd.lib(chrono.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DSFVector.cpp.obj
```

2020-01-06 03:16 UTC, NancyLi1013 commented
/azp run

2020-01-14 01:57 UTC, NancyLi1013 commented
/azp run

2020-01-14 04:28 UTC, JackBoosY commented
/azp run

2020-03-20 04:40 UTC, NancyLi1013 commented
Please feel free to ask us to reopen this PR if you need it.

2020-03-20 04:40 UTC, closed without merging