[WIP] [gazebo10] Add new port
microsoft/vcpkg pull request #8178
Opened 2019-09-15 10:55 UTC by traversaro

Add new port for the Gazebo simulator and its libraries. 

Currently a WIP, as it is needs https://github.com/microsoft/vcpkg/pull/8177 and https://github.com/microsoft/vcpkg/pull/8136 to be merged before. 

Furthermore, at the moment the part of handling executables is a draft, as I am  not sure how about the following points: 
* The `gazebo` and related executables is a tool for C++ projects in the sense that is a launcher for simulations that contain C++ plugins  developed against the Gazebo C++ API . For this reason, on Windows to launch Gazebo plugins compiled in Debug, you need to have the Gazebo executables  compiled in Debug, and for plugins compiled in Release, you need the Release executables. As far as I saw, all the ports that install tools only install the release version, as they are typically tools only used for code generation or similar build duties. 
What is the correct strategy to adopt in this case? Install the tools under `tools/gazebo10/debug` ? 
Note that there is an ongoing discussion on this in https://github.com/microsoft/vcpkg/issues/7826, if the tools could be installed in `bin` and in `debug/bin` there would be no problem at all. 
* How is `tools`/`executables` installation meant to be handled on `x64-osx` and `x64-linux` triplets? Some ports I saw identify executables by grepping all the files that end in `.exe` in the `bin` directory (see for example https://github.com/microsoft/vcpkg/blob/ecfc714b9adbdf8bf6b394dd6b46d9c56ca993ea/ports/pcl/portfile.cmake#L62) but this is not going to work on *nix triplets.

2019-09-16 20:03 UTC, Rastaban commented
I recommend using draft PRs for WIP https://github.blog/2019-02-14-introducing-draft-pull-requests/

2019-09-19 21:42 UTC, traversaro commented
> I recommend using draft PRs for WIP https://github.blog/2019-02-14-introducing-draft-pull-requests/. It helps up know when you feel it is ready for checkin.

Thanks, I actually wanted to run some CI on some early version of the port to collect preliminary info. However, now the port kind of stalled as a non-trivial patch is necessary to compile Gazebo against Ogre 1.12, so I think we can put the PR in draft mode indeed.

2019-10-08 17:48 UTC, vicroms commented
>   What is the correct strategy to adopt in this case? Install the tools under `tools/gazebo10/debug` ?

Yes, that would be the correct strategy. We're not in the business of shipping applications with vcpkg so while we allow ports to build executable files, we also require those executables to be moved to a `tools/<port>/` directory. You're free to structure things inside `tools/<port>` however you want, so for this case I would suggest to have a folder for each configuration: `tools/gazebo/debug/` and `tools/gazebo/release/`.

> * How is `tools`/`executables` installation meant to be handled on `x64-osx` and `x64-linux` triplets? Some ports I saw identify executables by grepping all the files that end in `.exe` in the `bin` directory (see for example https://github.com/microsoft/vcpkg/blob/ecfc714b9adbdf8bf6b394dd6b46d9c56ca993ea/ports/pcl/portfile.cmake#L62
>   ) but this is not going to work on *nix triplets.

You're correct, that doesn't work on non-Windows triplets. The correct way to handle is to move the binaries by name, for example: 

```cmake
set(EXECUTABLE_SUFFIX)
if (VCPKG_TARGET_IS_WINDOWS)
  set(EXECUTABLE_SUFFIX ".exe")
endif()

if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
  file(COPY "program1${EXECUTABLE_SUFFIX}" DESTINATION "tools/gazebo/debug")
  # other output files to be moved
...
```

2019-10-08 17:48 UTC, vicroms commented
/azp run

2019-10-30 15:15 UTC, traversaro commented
As of https://github.com/microsoft/vcpkg/pull/8178/commits/b132feed133ff4efde3d698247702bfc4c46480d, the port is ready and compiles successfully (at least on my machine). Proper generation of Release and Debug `setup.bat` is still missing, however during the testing even with properly modified `setup.bat`, the `gzserver.exe` tool does not start correctly but just hangs with the `[Msg] Waiting for master` message:
~~~
$ ./gzserver.exe  --verbose
[Msg] Waiting for master.
Gazebo multi-robot simulator, version 10.1.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org
~~~

I am not sure when I will be able to debug this. I remember experiencing this problem also in the past, @seanyen perhaps do you have some hint on what could be the problem given your experience working with Gazebo on Windows?

2019-11-12 06:20 UTC, stephenjust commented
@traversaro Thank you for putting this together, I've had such a headache trying to build Gazebo for Windows on my own.

I've managed to get both gzclient and gzserver running on my machine with the following "setup.bat" script run beforehand:
```bat
@REM Add paths to Windows. Run this script prior to running gzserver.exe
@REM and gzclient.ext on a Windows machine.
@REM Meant to be run from inside build/
@set build_type=Release
@if not "%1"=="" set build_type=%1
@echo Configuring for build type %build_type%

@REM Need absolute paths in order to run anything inside install dir
@set gz_root_path=%~dp0
@set gz_build_path=%gz_root_path%tools\gazebo10\%build_type%
@set gz_resource_path=%gz_root_path%share\gazebo-10
@pushd %~dp0
@set deps_path=%CD%\bin
@popd
@echo - script path is %gz_root_path%
@echo - build path is %gz_build_path%
@echo - resource path is %gz_resource_path%
@echo - dependencies path is %deps_path%

@set HOME=%HOMEDRIVE%%HOMEPATH%

@set GAZEBO_MODEL_PATH=%gz_resource_path%models
@set GAZEBO_PLUGINS_PATH=%gz_root_path%bin\gazebo-10\plugins
@set GAZEBO_RESOURCE_PATH=%gz_resource_path%;%gz_root_path%Media
@set OGRE_RESOURCE_PATH=%gz_root_path%bin

@set PATH=%gz_build_path%;%PATH%
```

There appears to still be some problems with certain resources - particularly shaders with `/` in the path, and most image files.

Thank you for the work so far though!

2019-11-12 07:56 UTC, traversaro commented
> @traversaro Thank you for putting this together, I've had such a headache trying to build Gazebo for Windows on my own.
> 
> I've managed to get both gzclient and gzserver running on my machine with the following "setup.bat" script run beforehand:
>

That is great, thanks a lot for working on this.  Eventually, can I take some parts of your `setup.bat` script to include it in the port? 

> 
> There appears to still be some problems with certain resources - particularly shaders with `/` in the path, and most image files (image codecs are now a plugin you need to include in latest Ogre).
> 

Have you tried to add `%gz_root_path%/share/gazebo-10` to `GAZEBO_RESOURCE_PATH`? At a first glance, it seems that is missing w.r.t. to the official `setup.bat` (see https://bitbucket.org/osrf/gazebo/src/a9352854ba1da2d2ddbad60e43f5bcbc7484e23e/CMakeLists.txt#lines-161 and https://bitbucket.org/osrf/gazebo/src/a9352854ba1da2d2ddbad60e43f5bcbc7484e23e/cmake)./setup.bat.in

2019-11-12 08:00 UTC, traversaro commented
Have you tried to run your script for launching Gazebo in Debug mode? I think that in that case, also `OGRE_RESOURCE_PATH` and `GAZEBO_PLUGINS_PATH` need to be modified to use the Debug version of the plugins.

2019-11-18 20:34 UTC, traversaro commented
@stephenjust I saw a few related  PR in Gazebo (https://bitbucket.org/osrf/gazebo/pull-requests/3150/fix-texture-loading-on-ogre-111-112/diff and  https://bitbucket.org/osrf/gazebo/pull-requests/3151),  do you think it make sense to add them as patches to the port? 
Btw, if you are able to reliable get to work the port by installing a suitable `setup.bat` or `win_addpath.bat`, feel free to open a new improved PR to add Gazebo in vcpkg. I do not have a lot of time to work on it, so if you are able to get it merged in the main vcpkg repo, it would be great!

2020-01-14 04:28 UTC, JackBoosY commented
/azp run

2020-01-16 07:26 UTC, JackBoosY requested changes

2020-01-16 07:26 UTC, JackBoosY commented on ports/gazebo10/gazebo-3131.patch
> +-#if OGRE_DEBUG_MODE
Why not force `OGRE_DEBUG_MODE` to `0` in `CMakeLists.txt`?

2020-01-16 07:26 UTC, JackBoosY commented on ports/gazebo10/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME gazebo)
`vcpkg_test_cmake` is deprecated, please remove this line.

2020-01-16 07:26 UTC, JackBoosY commented on ports/gazebo10/portfile.cmake
> +                    ${CURRENT_PACKAGES_DIR}/debug/lib/cmake
_${CURRENT_PACKAGES_DIR}/debug/lib/cmake_ should be deleted by `vcpkg_fixup_cmake_targets` automatically.

2020-01-16 07:26 UTC, JackBoosY commented on ports/gazebo10/portfile.cmake
> +if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
I prefer to use patch to fix the installation path with tools.

2020-01-16 07:27 UTC, JackBoosY commented
This PR contains too many patches, maybe we can wait for upstream to accept them and use the new version?

2020-01-16 08:10 UTC, traversaro commented on ports/gazebo10/gazebo-3131.patch
> +-#if OGRE_DEBUG_MODE
Because `OGRE_DEBUG_MODE` is already defned to `1` in OGRE headers if OGRE is compiled in Debug, so forcing it to `0` could create problems in the compilation of OGRE headers. See the related upstream PR : https://bitbucket.org/osrf/gazebo/pull-requests/3131,

2020-01-16 08:10 UTC, traversaro commented on ports/gazebo10/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME gazebo)
Ack.

2020-01-16 08:11 UTC, traversaro commented on ports/gazebo10/portfile.cmake
> +                    ${CURRENT_PACKAGES_DIR}/debug/lib/cmake
Good catch, thanks!

2020-01-16 08:17 UTC, traversaro commented on ports/gazebo10/portfile.cmake
> +if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
Just to understand, what is the rational to prefer a patch for this change that will never be upstreamed, as the installation of executables in `tools/<port>` is a vcpkg peculiarity?  
Do you have a good example port that can be used as an example for a patch that fixes tool installation? 
The current strategy was proposed by @vicroms in https://github.com/microsoft/vcpkg/pull/8178#issuecomment-539626680 .

2020-01-16 08:18 UTC, traversaro reviewed
Some replies.

2020-01-16 08:23 UTC, traversaro commented
> 
> 
> This PR contains too many patches, maybe we can wait for upstream to accept them and use the new version?

I think this is indeed a good idea, as Gazebo 11 that should contain all the proposed patch should be released at the end of January, and then we can add a gazebo11 port. Furthermore, as mentioned in https://github.com/microsoft/vcpkg/pull/8178#issuecomment-547957556 I am not able to use the existing port, so we would need at least someone that is able to correctly use the port to actually merge it.

2020-01-16 08:23 UTC, closed without merging

2020-03-16 21:30 UTC, traversaro commented
> 
> 
> As of [b132fee](https://github.com/microsoft/vcpkg/commit/b132feed133ff4efde3d698247702bfc4c46480d), the port is ready and compiles successfully (at least on my machine). Proper generation of Release and Debug `setup.bat` is still missing, however during the testing even with properly modified `setup.bat`, the `gzserver.exe` tool does not start correctly but just hangs with the `[Msg] Waiting for master` message:
> 
> ```
> $ ./gzserver.exe  --verbose
> [Msg] Waiting for master.
> Gazebo multi-robot simulator, version 10.1.0
> Copyright (C) 2012 Open Source Robotics Foundation.
> Released under the Apache 2 License.
> http://gazebosim.org
> ```
> 
> I am not sure when I will be able to debug this. I remember experiencing this problem also in the past, @seanyen perhaps do you have some hint on what could be the problem given your experience working with Gazebo on Windows?

For future reference, I had this problem also with Gazebo compiled outside of vcpkg because I had a rather old Windows 10 version (1709). By updating to Windows 10 1903, the problem was fixed.