Revert "[glib]Fix missing dependency selinux."
microsoft/vcpkg pull request #8201
Opened 2019-09-16 22:47 UTC by grdowns

Reverts microsoft/vcpkg#7988

2019-09-16 23:43 UTC, cbezault requested changes

2019-09-16 23:43 UTC, cbezault commented on ports/glib/CONTROL
>  Build-Depends: zlib, pcre, libffi, gettext, libiconv
Make selinux a default feature.

2019-09-17 11:32 UTC, JackBoosY commented on ports/glib/CONTROL
>  Build-Depends: zlib, pcre, libffi, gettext, libiconv
@cbezault Selinux may not be installed by default in linux, do you insist on this?

2019-09-17 16:29 UTC, cbezault commented on ports/glib/CONTROL
>  Build-Depends: zlib, pcre, libffi, gettext, libiconv
Yes, it should be default, selinux is pretty important, it's just that glib should be buildable without it.

2019-09-25 21:34 UTC, grdowns commented on ports/glib/CONTROL
>  Build-Depends: zlib, pcre, libffi, gettext, libiconv
I dug into this a bit more. Selinux is not required for all builds of glib (we know this), caused my machine to be unbootable, and was uninstallable through a Docker image. We should leave this as a non-default feature. Thanks @JackBoosY!

2019-09-25 21:34 UTC, closed without merging