Add mirror support
microsoft/vcpkg pull request #83
Opened 2016-09-24 13:28 UTC by Ninetainedo

Fixes #58 
Updated `vcpkg_download_distfile.cmake` to handle MIRRORS url.

2016-09-24 13:28 UTC, msftclas commented
Hi __@Ninetainedo__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, MSBOT;

2016-09-24 19:19 UTC, ras0219-msft commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                "        File path: [${downloaded_file_path}]\n"
Could you leave spaces between the '[' and the hash? This enables double clicking to select in the default windows terminal.

2016-09-24 19:21 UTC, ras0219-msft commented on scripts/cmake/vcpkg_download_distfile.cmake
> +# Usage: vcpkg_download_distfile(<VAR> URL <http://...> FILENAME <output.zip> SHA512 <5981de...> MIRRORS <http://mirror1> <http://mirror2>)
I think there's no benefit to separating the `URL` argument from the `MIRRORS` argument -- if we rename `MIRRORS` to `URLS`, in the future we could completely eliminate the `URL` argument (just need to move all the portfiles and the template over to using `URLS`).

2016-09-24 19:22 UTC, ras0219-msft commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                message(STATUS "Downloading ${url}... Failed")
On failure, we should display the status code to the user for debugging.

2016-09-24 19:23 UTC, ras0219-msft commented on scripts/cmake/vcpkg_download_distfile.cmake
> +            "    Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues/new\n")
Link to issues directly; it's possible there will be an existing issue.

2016-09-24 19:23 UTC, ras0219-msft commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                    "\nFile does not have expected hash:\n"
I'd really prefer to avoid duplicating the bulk of this user output code. Perhaps an inner function that could be called in both places would be appropriate here?

2016-09-24 19:26 UTC, ras0219-msft requested changes

2016-09-24 19:27 UTC, ras0219-msft commented
Overall this looks great. I think performing the hash check and throwing a hard failure on mismatch is the right way to go (as you've done).

The one important comment I have is the `MIRRORS` argument; I think it would be great in the future to not distinguish between the "URL" and the "MIRRORS", since the logic is basically the same (download each in the list until success).

2016-09-24 22:10 UTC, Ninetainedo commented on scripts/cmake/vcpkg_download_distfile.cmake
> +# Usage: vcpkg_download_distfile(<VAR> URL <http://...> FILENAME <output.zip> SHA512 <5981de...> MIRRORS <http://mirror1> <http://mirror2>)
You are entirely right, I'll change it and update all portfiles accordingly.

2016-09-24 22:10 UTC, Ninetainedo commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                "        File path: [${downloaded_file_path}]\n"
Yes, no problem for that. I didn't put it because I tried to stick to the exact syntax of CMake but I have to admit that it's easier with those spaces.

2016-09-24 22:25 UTC, Ninetainedo commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                message(STATUS "Downloading ${url}... Failed")
It's done as well.

2016-09-24 22:26 UTC, Ninetainedo commented on scripts/cmake/vcpkg_download_distfile.cmake
> +            "    Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues/new\n")
Done

2016-09-24 22:38 UTC, Ninetainedo commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                    "\nFile does not have expected hash:\n"
Done as well. I used a parameter named `FILE_KIND` which is `"cached file"` or `"downloaded file"` to have more precise logs. (I couldn't find a better name for the variable)

2016-09-24 22:40 UTC, Ninetainedo commented on scripts/cmake/vcpkg_download_distfile.cmake
> +                message(STATUS "Downloading ${url}... Failed. Status: ${download_status}")
I print the whole `download_status` variable because it contains both the error code and a human-friendly message

2016-09-26 20:56 UTC, merged

2016-09-26 20:57 UTC, alexkaratarakis commented
Solid work, thank you!