[librdkafka] Add vcpkg-cmake-wrapper.cmake
microsoft/vcpkg pull request #8355
Opened 2019-09-26 11:22 UTC by PhoebeHui

Related to https://github.com/microsoft/vcpkg/pull/8073

2019-09-26 17:02 UTC, cbezault requested changes
See #7331, it's very similar.

2019-09-26 17:02 UTC, cbezault commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +        unset(_RdKafka_LINK_INTERFACE)
You should clean up all variables that downstream consumers of the standard module wouldn't need. `TARGET_NAME` for example.

2019-09-26 17:02 UTC, cbezault commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +            set(RdKafka_SHARED_LIBRARIES ${RdKafka_LIBRARIES})
Are these two variables needed by consumers? They're not listed as outputs of the standard module.

2019-09-27 08:36 UTC, PhoebeHui commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +        if("${_RdKafka_DEFS}" MATCHES "RdKafka_STATIC")
Updated, thanks for pointing out this!

2019-09-27 08:36 UTC, PhoebeHui commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +        list(APPEND RdKafka_LIBRARY ${_RdKafka_LINK_INTERFACE})
Updated, thanks!

2019-09-27 08:37 UTC, PhoebeHui commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +_find_package(RdKafka CONFIG)
Added, thanks!

2019-09-27 08:37 UTC, PhoebeHui commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +        unset(_RdKafka_LINK_INTERFACE)
Updated, thanks for pointing out this!

2019-09-27 08:37 UTC, PhoebeHui commented on ports/librdkafka/vcpkg-cmake-wrapper.cmake
> +            set(RdKafka_SHARED_LIBRARIES ${RdKafka_LIBRARIES})
I removed them, thanks!

2019-09-27 16:46 UTC, merged