[rxcpp] Change to new repository
microsoft/vcpkg pull request #8361
Opened 2019-09-26 15:58 UTC by geiseri

This changes the source repository but not the version.  I also added an upstream patch that allows for `find_package(rxcpp CONFIG)` to work properly.  This will be in their next release and can be dropped at that point, but for any prior releases it will need to be applied.  I can remove that part of the PR if this is not acceptable.

2019-09-26 15:58 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8361) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8361) before we can accept your contribution.<br/><br/>:x: geiseri [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8361)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=8361) it.</sub>

2019-09-26 16:42 UTC, cbezault requested changes

2019-09-26 16:42 UTC, cbezault commented on ports/rxcpp/portfile.cmake
> +vcpkg_apply_patches(
Patches should be applied as the `PATCH` parameter to `vcpkg_from_github`.

2019-09-26 16:42 UTC, cbezault commented on ports/rxcpp/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug)
Why are you removing all of debug? You should only remove files that are identical between debug and release.

2019-09-27 00:39 UTC, geiseri commented on ports/rxcpp/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug)
This is header-only the only files in `debug` were inside of the `include` directory.  Those were duplicates of release so I just removed the entire directory tree.

2019-09-27 00:49 UTC, geiseri commented on ports/rxcpp/portfile.cmake
> +vcpkg_apply_patches(
okay, fixed

2019-09-27 18:18 UTC, cbezault approved these changes

2019-09-29 17:51 UTC, merged