[cppgraphqlgen & PEGTL] Update to latest version/commit
microsoft/vcpkg pull request #8397
Opened 2019-09-30 02:20 UTC by wravery

2019-09-30 06:58 UTC, Neumann-A commented on ports/pegtl/CONTROL
> +Version: 3.0.0-pre-cfd5e55
there is the `--head` option for things like this....

2019-09-30 23:28 UTC, wravery commented on ports/pegtl/CONTROL
> +Version: 3.0.0-pre-cfd5e55
If I understand the suggestion, I could use `--head` to install the dependency from HEAD instead of upping the commit routinely. However, there's been at least one breaking change from PEGTL leading up to the 3.0.0 release in cppgraphqlgen. I'm trying to keep the PEGTL commit in vcpkg in synch with a known compatible version of cppgraphqlgen until it releases.

2019-10-04 22:59 UTC, vicroms requested changes

2019-10-04 22:59 UTC, vicroms commented on ports/pegtl/CONTROL
> +Version: 3.0.0-pre-cfd5e55
I would actually change this to `2019-10-04` to follow our [CONTROL file versioning guidelines](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#version).

2019-10-04 23:06 UTC, vicroms commented
I see regressions on UWP that could be related to 
https://developercommunity.visualstudio.com/content/problem/369081/use-of-stdfilesystempath-causes-link-error-on-uwp.html

2019-10-07 15:41 UTC, wravery commented on ports/pegtl/CONTROL
> +Version: 3.0.0-pre-cfd5e55
Sounds good, I hadn't noticed that bit in the docs.

2019-10-07 15:49 UTC, wravery commented
> I see regressions on UWP for `cppgraphqlgen` that could be related to:
> 
> https://developercommunity.visualstudio.com/content/problem/369081/use-of-stdfilesystempath-causes-link-error-on-uwp.html

Yup, that checks out, thanks for the reference. I'll look into adding the CMake option to fallback to Boost.filesystem on UWP specifically.

> On the other hand `pegtl` doesn't seem to have any regressions at all, if you put the update to PEGTL in a separate PR then I can merge it ASAP.

Will do, just need to make sure it works with the previous version of `cppgraphqlgen`.

2019-10-07 15:49 UTC, closed without merging

2019-10-07 15:50 UTC, wravery commented
Will re-open once I've taken care of the requested changes.