[glslang,shaderc,spirv-tools]Various fixes
microsoft/vcpkg pull request #8436
Opened 2019-10-03 07:37 UTC by ChaoJia

glslang: added include dir to target config file;
shaderc: export target config file, make shaderc::combined optional as a feature;
spirv-tools: vcpkg_fixup_cmake_targets, added INTERFACE_INCLUDE_DIRECTORIES for target spirv-tools::SPIRV-Tools

(split from pull request #8425)

2019-10-08 13:01 UTC, jweg commented
This is very welcome. I ran into problems with shaderc before and made a local package config file for it as well (haven't had time to make a PR). 
That said, I've tried this PR and it doesn't work for me in this state. The way the shaderc::shaderc_combined target is defined (in the portfile) seems to be Windows-only, linking fails on Linux. Also, why has this been moved to a feature?

2019-10-08 15:14 UTC, ChaoJia commented
@jweg yeah, I realized it right after I made this PR. Thought no one would ever really want to use that nearly _1 GB_ combined version, and I've never used vcpkg on Linux. 
could you please replace lines `55` - `84` in file `shaderc/portfile.cmake` with the following code, give it a try and let me know if it works? All suggestions are welcome! Thanks!

```
if("combine" IN_LIST FEATURES)
    string(REPLACE 
        [[
# Cleanup temporary variables.
set(_IMPORT_PREFIX)]]
        [[
set(_STATIC_SUFFIX ".lib")
if (UNIX)
  set(_STATIC_SUFFIX ".a")
endif()
# add target shaderc::shaderc_combined
add_library(shaderc::shaderc_combined STATIC IMPORTED)
set_target_properties(shaderc::shaderc_combined PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

set_property(TARGET shaderc::shaderc_combined APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(shaderc::shaderc_combined PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/shaderc_combined${_STATIC_SUFFIX}"
)

set_property(TARGET shaderc::shaderc_combined APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(shaderc::shaderc_combined PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/shaderc_combined${_STATIC_SUFFIX}"
)

# Cleanup temporary variables.
set(_STATIC_SUFFIX)
set(_IMPORT_PREFIX)]] 
    shaderc_config_file "${shaderc_config_file}")

endif("combine" IN_LIST FEATURES)
```

2019-10-08 22:13 UTC, jweg commented
That almost works, but it also need the prefix "lib". Rather than configuring prefix and suffix I just put the whole name into a variable. 
[Here's the resulting portfile](https://gist.github.com/jweg/4aa988b25e8c36c319fbddc57c31a660) which works in my project.

2019-10-08 23:26 UTC, ChaoJia commented
@jweg Cool, thanks!

2019-11-19 19:29 UTC, ras0219-msft commented
/azp run

2019-11-19 19:35 UTC, ras0219-msft requested changes

2019-11-19 19:35 UTC, ras0219-msft commented on ports/glslang/portfile.cmake
> +file(WRITE ${SOURCE_PATH}/glslang/CMakeLists.txt "${glsl_cmake_lists}")
Every time this portfile runs, it will inject one additional line into the CMakeLists.txt.

This should be easily fixed by modifying the substitution to _not quite_ match (such as adding additional spaces inside `target_link_libraries(glslang OGLCompiler OSDependent)`.

2019-11-19 19:35 UTC, ras0219-msft commented on ports/shaderc/CONTROL
> +Feature: combine
"Feature"s aren't good at expressing XOR choices (such as "build as a single combined lib" versus "build as many separate libs") -- they are designed to express additive choices (such as "build with this additional API surface" or not).

Is anyone especially interested in using the all-in-one gigantic lib? If not, let's not add this for now.

2019-11-25 22:23 UTC, ChaoJia commented on ports/glslang/portfile.cmake
> +file(WRITE ${SOURCE_PATH}/glslang/CMakeLists.txt "${glsl_cmake_lists}")
Done. Thanks.

2019-11-25 22:23 UTC, ChaoJia commented on ports/shaderc/CONTROL
> +Feature: combine
removed feature `combine`.

2020-01-15 09:59 UTC, PhoebeHui requested changes

2020-01-15 09:59 UTC, PhoebeHui commented on ports/shaderc/portfile.cmake
> +
Looks you remove 'combine' feature, could you also remove this?

2020-03-20 07:30 UTC, PhoebeHui commented
@ChaoJia, is this PR still being worked on? do you have a chance to address the review suggestions?

2020-03-24 06:18 UTC, PhoebeHui commented
We have new PR https://github.com/microsoft/vcpkg/pull/10457 to update glslang and https://github.com/microsoft/vcpkg/pull/10441 to update spirv-tools currently. it seems not actively work on, I will close this PR.

2020-03-24 06:18 UTC, closed without merging