Added TAO as feature
microsoft/vcpkg pull request #8468
Opened 2019-10-06 14:09 UTC by ordisbold

Added CMake files to find ACE and TAO

2019-10-06 14:10 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8468) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8468) before we can accept your contribution.<br/><br/>:x: ordisbold [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8468)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=8468) it.</sub>

2019-10-07 16:18 UTC, ordisbold commented
I won't make any further changes. All builds succeed.

2019-10-07 22:43 UTC, cbezault commented
Why are you providing find modules? You should be providing config files if anything.

2019-10-07 22:46 UTC, ordisbold commented
I wasn't aware of that. I'll have a look at the documentation. I'd
appreciate if you gave me a hint though.

Curtis J Bezault <notifications@github.com> schrieb am Di., 8. Okt. 2019,
05:44:

> Why are you providing find modules? You should be providing config files
> if anything.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/vcpkg/pull/8468?email_source=notifications&email_token=AFBD2MO6N3KKBUFYTJDD7J3QNO3TPA5CNFSM4I54EBP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEASBJNY#issuecomment-539235511>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFBD2MNISUYIGKWNNP56ZW3QNO3TPANCNFSM4I54EBPQ>
> .
>

2019-10-07 23:19 UTC, Voskrese commented
hmm... error

```
\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" завершилась с кодом -1073741515. [E:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\tao\tao\TransportCurrent\TC_IIOP_Idl.vcxproj]
  Invoking "E:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\bin\tao_idl on ZIOP.pidl"
```


```
      <Command Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">setlocal&#x0D;&#x0A;PATH=%PATH%;E:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\lib&#x0D;&#x0A;cmd /c &quot;E:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\bin\tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -IE:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\tao -Wb,versioning_begin=TAO_BEGIN_VERSIONED_NAMESPACE_DECL -Wb,versioning_end=TAO_END_VERSIONED_NAMESPACE_DECL -Wb,export_include=tao/TransportCurrent/Transport_Current_Export.h -Wb,export_macro=TAO_Transport_Current_Export -iC tao/TransportCurrent -I./TransportCurrent -SS -Sci &quot;TC_IIOP.idl&quot;&quot;&#x0D;&#x0A;endlocal</Command>
      <Message Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">Invoking "E:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\bin\tao_idl on TC_IIOP.idl"</Message>
```

tag `&quot;` causes an error or does not find the file `TC_IIOP.idl or ace/pre.h or ace/post.h`

and such everywhere, where present `<CustomBuild`

2019-10-08 00:25 UTC, ordisbold commented
> hmm... error
> 
I originally started this port with another name a few weeks ago. While merging it to this ACE port, I forgot to change the target directory for the executables (i.e. tao_idl) from ace-tao to ace. That's fixed now.

2019-10-08 02:29 UTC, Voskrese commented on ports/ace/portfile.cmake
> +set(ACE_ROOT ${CURRENT_BUILDTREES_DIR}/src/ACE_wrappers)
```suggestion
set(ACE_ROOT ${CURRENT_BUILDTREES_DIR}/src/ACE_wrappers)
```

https://github.com/DOCGroup/ACE_TAO/blob/57c52c1183d8d5e11e725fc9886263dfca11f22c/azure-pipelines.yml#L2

? MPC_ROOT
https://github.com/DOCGroup/ACE_TAO/blob/57c52c1183d8d5e11e725fc9886263dfca11f22c/azure-pipelines.yml#L4

2019-10-08 02:39 UTC, Voskrese commented
can immediately add?
`CIAO_ROOT, DANCE_ROOT, DDS_ROOT, XSC_ROOT`

2019-10-08 03:52 UTC, cbezault commented
In general find modules are written by the consumers of cmake libraries. Config files are created by the consumed library for the benefit of the consumers. Both define targets and all other variables necessary to consume a library.

2019-10-08 04:42 UTC, Voskrese commented
`vcpkg install ace[*]:x64-windows`

`    ace[core,qt5,ssl,tao,tao-bzip2,tao-zlib,wchar,xml]:x64-windows`

error
`?strdup@ACE_OS@@YAPEADPEBD@Z`
`Точка входа в процедуру ?strdup@ACE_OS@@YAPEADPEBD@Z не найдена в библиотеке DLL E:\tools\vcpkg\buildtrees\ace\src\ACE_wrappers\lib\TAO_IDL_BE.dll.`
`
E:/tools/vcpkg/downloads/tools/perl/perl/bin/perl.exe E:/tools/vcpkg/buildtrees/ace/src/ACE_wrappers/bin/mwc.pl -type vs2017 TAO_ACE.mwc -features stl=1,ace_for_tao=0,ace_inline=0,uses_wchar=1,xml=1,ssl=1,qt5=1,bzip2=1,zlib=0 -workers 5 -use_env -expand_vars`

`ace[core,qt5,ssl,tao,tao-bzip2,tao-zlib,wchar,xml]`

?
**,zlib=0,ace_for_tao=0,ace_inline=0**
`-features stl=1,ace_for_tao=0,ace_inline=0,uses_wchar=1,xml=1,ssl=1,qt5=1,bzip2=1,zlib=0`

2019-10-08 07:48 UTC, ordisbold commented
> **other error**
> 

@Voskrese 
PS C:\vcpkg> .\vcpkg.exe install ace[*]
The following packages will be built and installed:
    ace[core,qt5,ssl,tao,tao-bzip2,tao-zlib,wchar,xml]:x64-windows
Starting package 1/1: ace:x64-windows
Building package ace[core,qt5,ssl,tao,tao-bzip2,tao-zlib,wchar,xml]:x64-windows...
Warning: abi keys are missing values:
    bzip2
    openssl
    qt5-base
    zlib

-- Using cached C:/vcpkg/downloads/ACE+TAO-src-6.5.6.tar.gz
-- Extracting source C:/vcpkg/downloads/ACE+TAO-src-6.5.6.tar.gz
-- Applying patch C:/vcpkg/ports/ace/qtcoreapplication.patch
-- Applying patch C:/vcpkg/ports/ace/bzip2.patch
-- Applying patch C:/vcpkg/ports/ace/mpc-arm.patch
-- Applying patch C:/vcpkg/ports/ace/stacktrace-arm.patch
-- Applying patch C:/vcpkg/ports/ace/arm_prevent_amd64_definition.patch
,uses_wchar=1,xml=1,ssl=1,qt5=1,bzip2=1,zlib=1
-- Building C:/vcpkg/buildtrees/ace/src/ACE_wrappers/tao/TAO_ACE.sln for Release

2019-10-08 07:59 UTC, ordisbold commented on ports/ace/portfile.cmake
> +set(ACE_ROOT ${CURRENT_BUILDTREES_DIR}/src/ACE_wrappers)
@Voskrese 

**ACE_ROOT & MPC_ROOT**
The folder structure of the ACE_TAO git repository is different from the one in the archive. 

**default.features**
Yes. I will change that. :-)

2019-10-08 08:00 UTC, Voskrese commented
is guilty, means at me remained everything in a cache, files were not reconfigured
will look further

2019-10-11 07:56 UTC, jwillemsen commented on ports/ace/CONTROL
> +Maintainer: Benjamin Oldenburg <benjamin.oldenburg@ordis.co.th>
Maintainer is not a field they support as far as I can find, see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md

2019-10-11 07:58 UTC, jwillemsen commented on ports/ace/bzip2.patch
> +@@ -5,8 +5,6 @@
Could you create a PR for MPC https://github.com/DOCGroup/MPC

2019-10-11 09:20 UTC, ordisbold commented on ports/ace/bzip2.patch
> +@@ -5,8 +5,6 @@
Yes... I've moved our office. I expect to be done tonight and can take care about this and the other PRs on the weekend.

2019-10-19 11:50 UTC, jwillemsen commented on ports/ace/CONTROL
> +Homepage: http://www.dre.vanderbilt.edu/~schmidt/TAO.html
Please use https link

2019-11-19 04:14 UTC, JackBoosY commented
/azp run

2019-11-20 16:01 UTC, jwillemsen commented
We also have https://github.com/microsoft/vcpkg/pull/9016 as another PR in ace

2019-11-22 09:17 UTC, jwillemsen commented
See https://github.com/microsoft/vcpkg/pull/9074 for the new ACE release which has some of the patches integrated

2019-11-28 12:09 UTC, jwillemsen commented
@ordisbold Any plans to finish the TAO feature soon?

2019-11-29 05:04 UTC, JackBoosY commented
@ordisbold Ace in vcpkg has been updated to 6.5.7, does your change still work?

2019-11-29 07:59 UTC, ordisbold commented
> @ordisbold Any plans to finish the TAO feature soon?

Not at the moment. I got too many other things on my plate and it has proven to be time intensive to get it right for all CI targets.

2020-01-15 08:55 UTC, PhoebeHui requested changes

2020-01-15 08:55 UTC, PhoebeHui commented on ports/ace/CONTROL
>  Version: 6.5.6
Could you please update Version to ' 6.5.6-1'?

2020-01-15 08:55 UTC, PhoebeHui commented on ports/ace/CONTROL
> +Description: Enable bzip2 support for TAO
Have you test these features locally?

2020-01-15 08:55 UTC, PhoebeHui commented on ports/ace/portfile.cmake
>  include(vcpkg_common_functions)
Could you please remove 'include(vcpkg_common_functions)', this is deprecated.

2020-01-15 09:32 UTC, JackBoosY commented
Please resolve these conflicts.

Thanks.

2020-01-15 09:33 UTC, jwillemsen commented
I think we first should get https://github.com/microsoft/vcpkg/pull/9016 and after that resolve the conflicts with this one, seems there is some overlap

2020-01-21 20:23 UTC, jwillemsen commented
#9016 got merged

2020-02-10 09:38 UTC, jwillemsen commented
new ACE/TAO release, see https://github.com/microsoft/vcpkg/pull/10003

2020-04-01 23:46 UTC, ordisbold commented on ports/ace/CONTROL
> +Homepage: http://www.dre.vanderbilt.edu/~schmidt/TAO.html
Done

2020-04-02 02:38 UTC, JackBoosY commented
Please remove the following content in _VCPKG_PATH/scripts/ci.baseline.txt_:
```
ace:x64-uwp=fail
ace:arm64-windows=fail
ace:arm-uwp=fail
```

2020-04-02 08:06 UTC, jwillemsen commented
Are all patches still required with TAO 2.5.8? Some got integrated already as far as I remember.

2020-04-02 11:29 UTC, ordisbold commented
> Are all patches still required with TAO 2.5.8? Some got integrated already as far as I remember.

I did remove them, just two were still necessary. I will look into it again

2020-04-02 14:55 UTC, ordisbold commented
Have a look at 

** Test Modified Ports **

for OSX. 

The build fails, but the status of the job is "succeeded". Something wrong there!?

2020-04-02 14:57 UTC, jwillemsen commented
Looks macosX is allowed to fail because it didn't work before, from the log I can find the following, no idea why make fails, I can't find the detailed log they refer to

```
2020-04-01T23:57:41.0768120Z Could not locate cached archive: /Volumes/data/work/1/s/archives/1d/1d6d510a49f5d1baaf7084deeeffb6f7b1ea6287.zip
2020-04-02T00:00:23.6257350Z -- Downloading https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-6_5_8/ACE+TAO-src-6.5.8.tar.gz...
2020-04-02T00:00:23.6259490Z -- Extracting source /Volumes/data/work/1/s/downloads/ACE+TAO-src-6.5.8.tar.gz
2020-04-02T00:00:23.6260260Z -- Applying patch /Volumes/data/work/1/s/ports/ace/arm_prevent_amd64_definition.patch
2020-04-02T00:00:23.6260870Z -- Applying patch /Volumes/data/work/1/s/ports/ace/bzip2.patch
2020-04-02T00:00:23.6261070Z CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
2020-04-02T00:00:23.6261220Z     Command failed: make
2020-04-02T00:00:23.6261380Z     Working Directory: /Volumes/data/work/1/s/buildtrees/ace/src/ACE_wrappers
2020-04-02T00:00:23.6273580Z     Error code: 2
2020-04-02T00:00:23.6274010Z     See logs for more information:
2020-04-02T00:00:23.6275600Z       /Volumes/data/work/1/s/buildtrees/ace/make-x64-osx-out.log
2020-04-02T00:00:23.6276180Z       /Volumes/data/work/1/s/buildtrees/ace/make-x64-osx-err.log
2020-04-02T00:00:23.6276710Z 
2020-04-02T00:00:23.6277000Z Call Stack (most recent call first):
2020-04-02T00:00:23.6278280Z   ports/ace/portfile.cmake:183 (vcpkg_execute_required_process)
2020-04-02T00:00:23.6278450Z   scripts/ports.cmake:90 (include)
2020-04-02T00:00:23.6278700Z 
2020-04-02T00:00:23.6278860Z 
2020-04-02T00:00:24.8916680Z Error: Building package ace:x64-osx failed with: BUILD_FAILED
2020-04-02T00:00:24.8917820Z Elapsed time for package ace:x64-osx: 2.73 min
2020-04-02T00:00:24.8918000Z 
2020-04-02T00:00:24.8918410Z Triplet: x64-osx
2020-04-02T00:00:24.8918590Z Total elapsed time: 2.73 min
2020-04-02T00:00:24.8918890Z RESULTS
2020-04-02T00:00:24.8919320Z     ace:x64-osx: BUILD_FAILED: 2.73 min
```

2020-04-02 15:28 UTC, jwillemsen commented
> > Are all patches still required with TAO 2.5.8? Some got integrated already as far as I remember.
> 
> I did remove them, just two were still necessary. I will look into it again

The patches are not applied but still list of the changes, just remove them again from git I would like to suggest

2020-04-02 15:29 UTC, jwillemsen approved these changes

2020-04-02 19:01 UTC, jwillemsen commented on ports/ace/portfile.cmake
> +    list(APPEND ACE_FEATURE_LIST "xml=1")
There is no xml feature, should be xerces3

2020-04-02 19:03 UTC, ordisbold commented
@jwillemsen 
I have another port file for axcioma... but it builds ACE and TAO as well.
I didn't yet figure out how to use ACE/TAO from a separate build and I don't know if that would be a good idea either.

Any ideas on how we can make both coexist or how to combine them?

In my opinion it would be better to have an axcioma port with features "ace, tao, taox11, ..., ..." and make brix11 able to only build these targets if desired.

2020-04-02 19:06 UTC, ordisbold commented on ports/ace/portfile.cmake
> +    list(APPEND ACE_FEATURE_LIST "xml=1")
Done

2020-04-02 19:08 UTC, ordisbold commented
And maybe it's possible to introduce some alias package sort of thing... so, if someone wants to install ace, it would actually install axcioma[ace].

2020-04-02 19:11 UTC, ordisbold commented
And another issue... is there something like feature dependencies?

xerces-c has an xmlch_wchar option.
If ace is built with wchar support and xerces-c support, shouldn't then be built with implicitly xmlch_wchar enabled?

2020-04-02 19:17 UTC, jwillemsen commented
Yes, I thought that worked, for xerces you need to pass xerces3=1 to mpc, not xml=1

2020-04-03 02:53 UTC, JackBoosY requested changes

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +set(ACE_ROOT ${CURRENT_BUILDTREES_DIR}/src/ACE_wrappers)
Has this requirement been resolved?

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +if(NOT VCPKG_CMAKE_SYSTEM_NAME)
Please replace it with
```
if (VCPKG_TARGET_IS_WINDOWS)
...
elseif (VCPKG_TARGET_IS_LINUX)
...
elseif(VCPKG_TARGET_IS_OSX)
...
elseif (VCPKG_TARGET_IS_UWP)
```

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +if((NOT VCPKG_CMAKE_SYSTEM_NAME) OR ("WindowsStore" STREQUAL VCPKG_CMAKE_SYSTEM_NAME))
Please replace it with `if (VCPKG_TARGET_IS_WINDOWS)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +elseif((VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux") OR (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin"))
Please replaice it with `if (VCPKG_TARGET_IS_LINUX OR VCPKG_TARGET_IS_OSX)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +if((NOT VCPKG_CMAKE_SYSTEM_NAME) OR ("WindowsStore" STREQUAL VCPKG_CMAKE_SYSTEM_NAME))
Please replace it with `if (VCPKG_TARGET_IS_WINDOWS)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
Please replaice it with `if (VCPKG_TARGET_IS_LINUX OR VCPKG_TARGET_IS_OSX)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +  FIND_PROGRAM(MAKE make)
I think we should use `vcpkg_*_make`, see documentation:
[vcpkg_configure_make](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_make.md) / [vcpkg_build_make](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_build_make.md) / [vcpkg_install_make](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_make.md)

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +if(NOT VCPKG_CMAKE_SYSTEM_NAME)
Please replace it with `if (VCPKG_TARGET_IS_WINDOWS)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
Please replace it with `if (VCPKG_TARGET_IS_LINUX)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
Please replace it with `if (VCPKG_TARGET_IS_OSX)`

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
>    set(LIB_RELEASE_SUFFIX .lib)
These vars are already defined in [vcpkg_common_definitions](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_common_definitions.cmake).
Eg: `VCPKG_TARGET_STATIC_LIBRARY_SUFFIX` / `VCPKG_TARGET_SHARED_LIBRARY_SUFFIX`.

2020-04-03 02:53 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +    if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
Please replace it with `if (VCPKG_TARGET_IS_LINUX)`

2020-04-03 08:01 UTC, ordisbold commented on ports/ace/portfile.cmake
> +if(NOT VCPKG_CMAKE_SYSTEM_NAME)
It's using vcpkg_download_distfile now...

2020-04-06 07:31 UTC, jwillemsen commented
> @jwillemsen
> I have another port file for axcioma... but it builds ACE and TAO as well.
> I didn't yet figure out how to use ACE/TAO from a separate build and I don't know if that would be a good idea either.
> 
> Any ideas on how we can make both coexist or how to combine them?
> 
> In my opinion it would be better to have an axcioma port with features "ace, tao, taox11, ..., ..." and make brix11 able to only build these targets if desired.

To start with I think you should let axcioma also generate the configuration files and build ACE/TAO. brix11 sets various flags which knowledge we don't want to duplicate again

2020-04-06 07:44 UTC, ordisbold commented
> > @jwillemsen
> > I have another port file for axcioma... but it builds ACE and TAO as well.
> > I didn't yet figure out how to use ACE/TAO from a separate build and I don't know if that would be a good idea either.
> > Any ideas on how we can make both coexist or how to combine them?
> > In my opinion it would be better to have an axcioma port with features "ace, tao, taox11, ..., ..." and make brix11 able to only build these targets if desired.
> 
> To start with I think you should let axcioma also generate the configuration files and build ACE/TAO. brix11 sets various flags which knowledge we don't want to duplicate again

Alright... I will create another PR after this one has been merged.

2020-04-06 14:12 UTC, jwillemsen commented
Looks linux/windows CI builds failed after the most recent changes

2020-04-06 14:12 UTC, jwillemsen commented
> Alright... I will create another PR after this one has been merged.

Just tag me when you have made that PR @ordisbold

2020-04-08 16:14 UTC, ordisbold commented on ports/ace/portfile.cmake
>    set(LIB_RELEASE_SUFFIX .lib)
Yep, but they don't handle static and debug suffixes on Windows, so I don't see any benefit of changing what already works and is very likely to work for the next decade.

2020-04-08 16:28 UTC, ordisbold commented
I don't understand why it's trying to build qt5-tools on Linux.

.\vcpkg.exe depend-info ace[*]
openssl-windows:
bzip2:
openssl: openssl-windows
xerces-c:
zlib:
ace[wchar, bzip2, xerces-c, ssl, tao, zlib]: bzip2, openssl, xerces-c, zlib

2020-04-08 16:33 UTC, ordisbold commented on ports/ace/CONTROL
> +Description: Enable bzip2 support for TAO
As in building a tao based application that uses compression with these libraries? No, of course I have not.

2020-04-08 16:39 UTC, ordisbold commented
I will focus on the axcioma based build... And I will not try to support all platforms and features immediately. :-D

2020-04-09 02:31 UTC, JackBoosY commented
@ordisbold Well, `qt5-tools` issue has been resolved. Could you reopen this PR again?

2020-04-09 03:15 UTC, ordisbold commented
> @ordisbold Well, `qt5-tools` issue has been resolved. Could you reopen this PR again?

I don't understand why it even required qt5-tools. I removed everything qt5 and it still failed due to an issue in the qt5 package. 🤔

I reopened it. 

But there's a problem regarding this port. 

TAO is based on ACE and it is not advisable to separate the build process of these libraries and make TAO a separate port. TAO only supports the decades old IDL-to-C++ mapping, which doesn't support the STL, because the STL wasn't part of the C++ standard when the IDL-to-C++ mapping was defined. The "old" IDL-to-C++ mapping is hard to use and developing with it is error-prone, especially for beginners. 

Renedy IT has crated a new IDL-to-C++11 mapping. It is now part of the official IDL to language specifications by the OMG. 

Remedy IT has also implemened the aforementioned IDL-to-C++11 mapping based on TAO and recently released it with other relevant components (i.e. LwCCM) as open source software. The suite is called AXCIOMA and  just the implementation of the new IDL-to-C++11 mapping is called TAOX11. 

Separating so if this is a can of worms I don't want to open. 

The question is: how to represent this in vcpkg? The AXCIOMA build process appears to be complex but stable. It implicitly downloads ACE and TAO and builds these libraries with specific settings that the library depends on.

2020-04-09 03:22 UTC, JackBoosY commented
/azp run

2020-04-09 04:30 UTC, ordisbold commented
_VCPKG_MAKE_GENERATOR in vcpkg_build_make.cmake seems to be undefined. That's why the Linux build now fails :-D

Where is _VCPKG_MAKE_GENERATOR  set?

2020-04-09 04:57 UTC, JackBoosY commented
@ordisbold `_VCPKG_MAKE_GENERATOR` is automatically set in `vcpkg_configure_make`.

2020-04-09 04:59 UTC, JackBoosY requested changes

2020-04-09 04:59 UTC, JackBoosY commented on ports/ace/portfile.cmake
> +  vcpkg_build_make(SOURCE_PATH ${SOURCE_PATH})
You need to call `vcpkg_configure_make` first. See [example](https://github.com/microsoft/vcpkg/blob/19baa0d9b3be740fc107131759f89ce12b0038ac/ports/libmesh/portfile.cmake), [documentation](https://github.com/microsoft/vcpkg/blob/c0d22c88ea7638d1b74339f9e9adfd37b0f525ed/docs/maintainers/vcpkg_configure_make.md).

2020-04-09 13:17 UTC, jwillemsen requested changes
Before this PR linux worked as far as I know, now it is disabled, personally I don't like to remove a platform again

2020-04-10 02:56 UTC, JackBoosY requested changes
```
-- Applying patch /home/vcpkg/ports/ace/arm_prevent_amd64_definition.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:51 (message):
  Applying patch failed.  Checking patch ace/config-win32-common.h...

  error: while searching for:

  #if defined (_WIN64) || defined (WIN64)

  # define ACE_WIN64



  // MPC template adds _AMD64_ but user projects not generated using MPC

  // may want to use _AMD64_ as well.  Ensure it's there in all cases.

  # ifndef _AMD64_

  # define _AMD64_

  # endif



  // Use 64-bit file offsets by default in the WIN64 case, similar to

  // what 64-bit UNIX systems do.

  //



  error: patch failed: ace/config-win32-common.h:39

  error: ace/config-win32-common.h: patch does not apply

Call Stack (most recent call first):
  ports/ace/portfile.cmake:42 (vcpkg_apply_patches)
  scripts/ports.cmake:90 (include)
```

2020-04-10 03:39 UTC, ordisbold commented
> Before this PR linux worked as far as I know, now it is disabled, personally I don't like to remove a platform again

Okay, but this PR took much longer than I anticipated. This was certainly due to my lack of knowledge of vcpkg and it's rules for ports but also because I intented to support all platforms right away. 

So, at the moment I want to only support Windows (I never thought I would ever write this :-P) and add other platforms in separate PRs. Otherwise I fear there will always be new issues, like the qt5-tools issue yesterday, which came and went away, even though I have removed all dependencies on qt5. 

I have already setup a CentOS VM yesterday to test Linux builds with it.

2020-04-10 04:12 UTC, ordisbold commented
I won't invest more time in this PR. 

I wanted to share the addition of TAO which I have been using here for a while and I didn't expect that the PR consumes more time than the addition of TAO to the port.

So, I don't require it to be merged.

2020-04-10 04:12 UTC, closed without merging

2020-04-10 08:00 UTC, jwillemsen commented
Regret to see this closed, would be nice to have tao on vcpkg