[expat] Update library to 2.2.9
microsoft/vcpkg pull request #8726
Opened 2019-10-24 12:41 UTC by ehsan-mohammadi

Update `expat` library to 2.2.9 version.

2019-10-25 08:09 UTC, ehsan-mohammadi commented
It gives error on some windows triplets:

- ### `x86-windows`:
> REGRESSION: io2d:x86-windows
 REGRESSION: apr-util:x86-windows
 REGRESSION: gdal:x86-windows
 REGRESSION: readosm:x86-windows

- ### `x64-windows`:
> REGRESSION: io2d:x64-windows
 REGRESSION: apr-util:x64-windows
 REGRESSION: gdal:x64-windows
 REGRESSION: readosm:x64-windows
 REGRESSION: gtk:x64-windows

- ### `x64-windows-static`:
> REGRESSION: readosm:x64-windows-static
 REGRESSION: apr-util:x64-windows-static
 REGRESSION: gdal:x64-windows-static

- ### `arm64-windows`:
> REGRESSION: readosm:arm64-windows

2019-11-19 03:01 UTC, JackBoosY commented
/azp run

2019-11-19 03:02 UTC, JackBoosY commented
/azp run

2020-01-19 07:42 UTC, LilyWangL commented
/azp run

2020-01-21 09:37 UTC, LilyWangL commented
Pinging @ehsan-mohammadi for response. Is work still being done for this PR?

2020-01-21 09:40 UTC, LilyWangL requested changes

2020-01-21 09:40 UTC, LilyWangL commented on ports/expat/portfile.cmake
>  include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-01-21 09:40 UTC, LilyWangL commented on ports/expat/portfile.cmake
> +    message(FATAL_ERROR "${PORT} does not currently support UWP")
Please use `vcpkg_fail_port_install(ON_TARGET "UWP")` to description this port doesn't support UWP. And please modify _VCPKG_PATH/scripts/ci.baseline.txt_ to account for the UWP failures.

2020-01-21 10:14 UTC, ehsan-mohammadi commented on ports/expat/portfile.cmake
> +    message(FATAL_ERROR "${PORT} does not currently support UWP")
@LilyWangL Thanks for helping me! I resolved these conversations.

2020-01-22 02:25 UTC, LilyWangL commented
@ehsan-mohammadi  Currently, this PR fails on Windows due to:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EXPAT_LIB
    linked by target "io2d_cairo_win32" in directory C:/vsts/_work/4/s/buildtrees/io2d/src/3b5b5fc338-1775a03870/P0267_RefImpl/P0267_RefImpl/cairo/win32
```
Ports such as io2d and gdal are dependent on expat. Due to this update, these build failed. Could you continue to resolve this PR?

2020-03-27 03:02 UTC, LilyWangL commented
Pinging @ehsan-mohammadi for response. Is work still being done for this PR?

2020-04-09 09:52 UTC, LilyWangL commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2020-04-09 09:52 UTC, closed without merging