Add libical port
microsoft/vcpkg pull request #8754
Opened 2019-10-26 12:37 UTC by winterz

This is a new port for the libical project and also my first ever attempt to create a vcpkg port.

2019-10-26 12:38 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8754) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8754) before we can accept your contribution.<br/><br/>:x: winterz [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8754)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=8754) it.</sub>

2019-11-01 08:14 UTC, NancyLi1013 requested changes

2019-11-01 08:14 UTC, NancyLi1013 commented on ports/libical/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib/cmake)
Please remove these lines
```
file(COPY ${CURRENT_PACKAGES_DIR}/lib/cmake/LibICal
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/libical/cmake
    FILES_MATCHING PATTERN "*.cmake" )
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/lib/cmake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib/cmake)
```
and use this `vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/LibIcal TARGET_PATH share/LibIcal)`.

2019-11-01 08:14 UTC, NancyLi1013 commented on ports/libical/portfile.cmake
> +file(RENAME ${CURRENT_PACKAGES_DIR}/share/libical/COPYING ${CURRENT_PACKAGES_DIR}/share/libical/copyright)
Please keep one of licenses and remove others. 
f`ile(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT }RENAME copyright)`

2019-11-01 08:24 UTC, NancyLi1013 commented
Hi @winterz  thanks for this pull request. Please try to sign CLA first.  You can click the following link to complete it.
https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8754

2019-11-01 13:58 UTC, winterz commented on ports/libical/portfile.cmake
> +    REF v3.0.6
ok, but tags are convenient and easy to read and understand.
Can I put in a comment saying "this is tag v3.0.6" ?

2019-11-01 13:59 UTC, winterz commented on ports/libical/portfile.cmake
> +include(vcpkg_common_functions)
ok, but the examples need to be modified as well.

2019-11-01 13:59 UTC, winterz commented on ports/libical/portfile.cmake
> +
will do.

2019-11-01 13:59 UTC, winterz commented on ports/libical/portfile.cmake
> +file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib/cmake)
nice!

2019-11-01 14:01 UTC, winterz commented
I will update the pull request as indicated.

as for signing the CLA: my employer is ok with my signing it, but they are deciding on a company-wide policy.  might take some time.

2019-11-19 02:59 UTC, JackBoosY commented
/azp run

2019-11-19 15:26 UTC, winterz commented
same to you bub :)
I'm not sure what you're referring to @JackBoosY

2019-11-19 16:36 UTC, JackBoosY commented
@winterz I just restart the CI test.

2019-12-13 02:36 UTC, NancyLi1013 commented
@winterz 
I also noticed that you have added these two ports `qt5-kdreports` and `qt5-kdsoap` in this PR.
Could you add them in a separate PR? Please refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

As `qt5-kdreports` and `qt5-kdsoap` belong to qt5. You can refer to other qt5 components to add them.
So please remove these two ports from this PR.

2019-12-13 05:43 UTC, JackBoosY commented
/azp run

2019-12-18 13:36 UTC, winterz commented
I'm going to abandon this for now.

2019-12-18 13:36 UTC, closed without merging