[wxwidgets] Upgrade to 3.1.3
microsoft/vcpkg pull request #8808
Opened 2019-10-30 08:50 UTC by cnbatch

2019-10-30 18:58 UTC, ras0219-msft requested changes
Thanks for the PR!

Could you also change the `Version:` field in the CONTROL file?

2019-10-31 04:40 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8808) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8808) before we can accept your contribution.<br/><br/>:x: cnbatch [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=8808)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=8808) it.</sub>

2019-10-31 04:44 UTC, cnbatch commented
> Thanks for the PR!
> 
> Could you also change the `Version:` field in the CONTROL file?

Sure

2019-10-31 21:19 UTC, merged

2019-10-31 21:19 UTC, ras0219-msft commented
Thanks!