[cpd] Add new port
microsoft/vcpkg pull request #8827
Opened 2019-10-31 06:32 UTC by LilyWangL

Due to there are no `dllexport` in source code, port cpd only support static library linkage.

2019-10-31 09:41 UTC, NancyLi1013 approved these changes

2019-10-31 20:07 UTC, ras0219-msft requested changes

2019-10-31 20:07 UTC, ras0219-msft commented on ports/cpd/portfile.cmake
> +vcpkg_fail_port_install(ON_LIBRARY_LINKAGE "dynamic")
Generally, `vcpkg_check_linkage()`[1] should be used instead of `vcpkg_fail_port_install()` for linkage cases.

[1] https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_check_linkage.cmake

2019-11-19 02:54 UTC, JackBoosY commented
/azp run

2019-11-22 23:18 UTC, vicroms requested changes

2019-11-22 23:18 UTC, vicroms commented on ports/cpd/Fix-FindJsoncpp.patch
> + find_package(jsoncpp QUIET)
We need to remove lines similar to the ones below from the CMakeLists.txt

```
find_package(Fgt QUIET)
option(WITH_FGT "Build with fgt" ${Fgt_FOUND})
```

These type of automatically enabled features introduce flakiness to our CI.

We want to either make all `find_package(<pkg> QUIET)` calls into `REQUIRED` ones, or better yet, convert them into features.

2020-01-03 03:12 UTC, NancyLi1013 commented
/azp run

2020-01-22 08:56 UTC, NancyLi1013 commented
/azp run

2020-03-20 09:03 UTC, LilyWangL commented
Please feel free to ask us to reopen this PR if you need it.

2020-03-20 09:03 UTC, closed without merging