[yas] Initial port
microsoft/vcpkg pull request #8891
Opened 2019-11-04 20:58 UTC by RT222

2019-11-19 02:43 UTC, NancyLi1013 commented
/azp run

2019-11-20 03:22 UTC, NancyLi1013 commented on ports/yas/CONTROL
> +Description: Yet Another Serialization is a header only serialization library
Please add this line here:
Homepage:   https://github.com/niXman/yas
Why does the version add `-1` ? You don't need to change the version if you add a new port.

2019-11-20 03:22 UTC, NancyLi1013 commented on ports/yas/portfile.cmake
> +include(vcpkg_common_functions)
This line is no longer needed, please remove it.

2019-11-20 03:22 UTC, NancyLi1013 commented on ports/yas/portfile.cmake
> +	REF 7.0.4
Please use commit id `572d6b4c405ce2c808c06a5bb88a66b0b98b85a5 `here instead of tag name.

2019-11-20 03:22 UTC, NancyLi1013 commented on ports/yas/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/README.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
README.md is not license. Please update it as [MIT LICENSE](https://github.com/microsoft/vcpkg/blob/master/LICENSE.txt).

2019-11-21 16:02 UTC, RT222 commented on ports/yas/portfile.cmake
> +	REF 7.0.4
Done, but are you sure about this change? The documentation seems to recommended to use the official releases tag first if available :
> For repositories without official releases, this can be set to the full commit id of the current latest master.

2019-11-22 08:31 UTC, NancyLi1013 approved these changes

2019-11-22 17:13 UTC, ras0219-msft requested changes

2019-11-22 17:13 UTC, ras0219-msft commented on ports/yas/LICENSE.txt
> +Copyright (c) Microsoft Corporation
This library (as far as I can tell) is not "Copyright (c) Microsoft Corporation".

It looks like the license is embedded at the top of the source files[1]. Therefore, we can use a source file as the copyright file.

[1] https://github.com/niXman/yas/blob/master/include/yas/binary_iarchive.hpp#L2

2020-01-06 22:53 UTC, merged