[hiredis] Support static build on Windows
microsoft/vcpkg pull request #8902
Opened 2019-11-05 07:14 UTC by NancyLi1013

Add windows support. 
It currently only supports static on Windows.

Related issue #8840 
Related PR #8843, #8846.

2019-11-19 02:04 UTC, NancyLi1013 commented
/azp run

2019-11-19 02:48 UTC, JackBoosY commented
/azp run

2019-11-25 07:55 UTC, JackBoosY requested changes

2019-11-25 07:55 UTC, JackBoosY commented on ports/hiredis/portfile.cmake
> +if (VCPKG_TARGET_IS_WINDOWS AND VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
We can use:
```
if (VCPKG_TARGET_IS_WINDOWS)
    vcpkg_fail_port_install(ON_LIBRARY_LINKAGE  "dynamic")
endif()
```

2019-11-25 08:40 UTC, JackBoosY approved these changes

2019-11-25 09:55 UTC, NancyLi1013 commented on ports/hiredis/portfile.cmake
> +if (VCPKG_TARGET_IS_WINDOWS AND VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
I updated as the following code:

```
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
```

2019-12-24 03:15 UTC, NancyLi1013 commented
The Related PR #9388 has been merged.
So I close this PR now.

2019-12-24 03:15 UTC, closed without merging