use latest librtmp
microsoft/vcpkg pull request #8958
Opened 2019-11-10 17:26 UTC by jeremad

as stated there: http://rtmpdump.mplayerhq.hu/ we should use the git repository, as the sources tar ball are very outdated

2019-11-10 22:34 UTC, cenit commented
Bump also the control file :)

2019-11-12 13:54 UTC, jeremad commented
fixed, thanks

2019-11-18 22:03 UTC, jeremad commented
Hello, any news on this?

2019-11-19 02:13 UTC, NancyLi1013 commented
/azp run

2019-11-20 06:09 UTC, NancyLi1013 requested changes

2019-11-20 06:09 UTC, NancyLi1013 commented on ports/librtmp/CONTROL
> +Version: 2.4-3
I noticed that you have updated the source. So the version here shouldn't be 2.4. You can change it as a date ( 2019-11-11) that  you updated the port if there is no specific version number.

2019-11-20 06:09 UTC, NancyLi1013 commented on ports/librtmp/portfile.cmake
>  include(vcpkg_common_functions)
This line is no longer needed. Please remove it.

2019-11-20 10:14 UTC, jeremad commented on ports/librtmp/portfile.cmake
>  include(vcpkg_common_functions)
Fixed. Thanks for the review!

2019-11-21 03:16 UTC, NancyLi1013 commented
/azp run

2019-11-22 01:14 UTC, merged

2019-11-22 01:14 UTC, ras0219-msft commented
LGTM, thanks for the PR!