[pdcurses] Add usage
microsoft/vcpkg pull request #9042
Opened 2019-11-19 07:22 UTC by NancyLi1013

When building it as a DLL, need to define PDC_DLL_BUILD to import external variables.
So I add the usage to this port.

Related issue #4848 

No features need to test.

2019-11-21 03:15 UTC, NancyLi1013 commented
./azp run

2019-11-22 00:45 UTC, ras0219-msft requested changes

2019-11-22 00:45 UTC, ras0219-msft commented on ports/pdcurses/portfile.cmake
>  endif()
This should use `vcpkg_check_linkage(ONLY_DYNAMIC_CRT)`

2019-11-22 00:45 UTC, ras0219-msft commented on ports/pdcurses/portfile.cmake
> +configure_file(${CMAKE_CURRENT_LIST_DIR}/usage ${CURRENT_PACKAGES_DIR}/share/${PORT}/usage @ONLY)
Instead of installing a usage file, which requires changes to every downstream project, we should patch the installed headers to always do the right thing.

Specifically, we can replace
```
#ifdef PDC_DLL_BUILD
```
with
```
#if 1
```
when `VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic"`.

Example: https://github.com/microsoft/vcpkg/blob/a306312f4bc8d2c1f36656ad6d13f744e2ff833c/ports/docopt/portfile.cmake#L30-L34

2019-11-22 05:53 UTC, NancyLi1013 commented on ports/pdcurses/portfile.cmake
> +configure_file(${CMAKE_CURRENT_LIST_DIR}/usage ${CURRENT_PACKAGES_DIR}/share/${PORT}/usage @ONLY)
Thanks for your review.

2019-11-22 06:58 UTC, JackBoosY approved these changes

2019-11-22 22:56 UTC, ras0219-msft approved these changes

2019-11-22 22:56 UTC, merged