[rply]new port
microsoft/vcpkg pull request #9045
Opened 2019-11-19 11:05 UTC by ChaoJia

http://w3.impa.br/~diego/software/rply/
rply: ANSI C Library for PLY file format input and output

2019-11-21 08:15 UTC, PhoebeHui commented
/azp run

2019-11-22 18:17 UTC, ras0219-msft requested changes

2019-11-22 18:17 UTC, ras0219-msft commented on ports/rply/export_functions.patch
> ++RPLY_DLL_DEF
Instead of attempting to maintain a large patchfile, we should either mark this library as static only or use a `.def` file.

2019-11-22 18:17 UTC, ras0219-msft commented on ports/rply/export_functions.patch
> ++RPLY_DLL_DEF
See `libtheora`, `libexif`, or `libmsgpack` for examples of how to use `.def` files.

2019-11-25 22:12 UTC, ChaoJia commented on ports/rply/export_functions.patch
> ++RPLY_DLL_DEF
switched to `.def` file. Thanks.

2019-11-29 02:53 UTC, NancyLi1013 requested changes

2019-11-29 02:53 UTC, NancyLi1013 commented on ports/rply/CONTROL
> +Description: ANSI C Library for PLY file format input and output
Could you please add homepage here?
Homepage: http://w3.impa.br/~diego/software/rply

2019-11-29 02:53 UTC, NancyLi1013 commented on ports/rply/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is deprected. Could you please remove this line here?

2019-11-29 09:57 UTC, ChaoJia commented on ports/rply/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` appears in 1147 `portfile.cmake`s, and `vcpkg_common_functions` was updated on Oct 5. It is still in the [example](https://vcpkg.readthedocs.io/en/latest/examples/packaging-github-repos/#create-the-portfile) provided by vcpkg documentation. Is there some better source indicating `include(vcpkg_common_functions)` is deprecated?

2019-12-03 02:57 UTC, NancyLi1013 commented on ports/rply/portfile.cmake
> +include(vcpkg_common_functions)
Since adding` include(vcpkg_common_functions)` will cause `vcpkg create` again. So we suggest remove this line.

2019-12-13 06:16 UTC, NancyLi1013 approved these changes

2019-12-13 06:19 UTC, NancyLi1013 commented
Hi @ChaoJia thanks for this PR. 
LGTM now.
What issue does this PR fix? Please open an issue so others may replicate this problem.

2020-01-09 00:37 UTC, dan-shaw commented
/azp run

2020-01-14 02:15 UTC, NancyLi1013 commented
/azp run

2020-02-04 23:38 UTC, ras0219-msft commented
/azp run

2020-02-06 02:12 UTC, ras0219-msft commented
/azp run

2020-02-06 23:17 UTC, ras0219-msft commented
Thanks for the PR!

2020-02-06 23:17 UTC, merged