[libpqxx]Fix lib name on Linux.
microsoft/vcpkg pull request #9051
Opened 2019-11-20 05:45 UTC by AlvinZhangH

When build and generate lib on Linux, there is prefix 'lib', do not need to add 'lib' to lib name.
Related issue #9040.
No features need to test.

2019-11-20 12:17 UTC, heydojo commented
This patch fixes the prefix being **liblib**? When it should be **lib**?
Consider this pretty standard snippet of CMakeLists.txt if you will:
```
if (MACOSX)
  set (CMAKE_FIND_LIBRARY_PREFIXES "lib")
  set (CMAKE_FIND_LIBRARY_SUFFIXES ".dylib;.so;.a")
elseif (LINUX OR UNIX AND NOT APPLE)
  set (CMAKE_FIND_LIBRARY_PREFIXES "lib")
  set (CMAKE_FIND_LIBRARY_SUFFIXES ".so;.a")
elseif (MSVC OR WIN32)
  set (CMAKE_FIND_LIBRARY_PREFIXES "")
  set (CMAKE_FIND_LIBRARY_SUFFIXES ".lib")
endif ()
```

2019-11-21 05:57 UTC, AlvinZhangH commented
Hi! @heydojo Thank you for the review and provide code! 
The original target name was set as libpqxx_static in CMakeLists.txt, it is right in WIN32, but the lib name add prefixes 'lib' to be liblibpqxx_static on Linux, so need set original target name to be pqxx_static on Linux, UNIX OR APPLE.

2019-11-22 08:44 UTC, AlvinZhangH commented
/azp run

2019-11-25 05:44 UTC, JackBoosY requested changes

2019-11-25 05:44 UTC, JackBoosY commented on ports/libpqxx/CMakeLists.txt
> +IF(UNIX OR APPLE)
`UNIX` includes `APPLE`, so we should just use macro `UNIX` here.

2019-11-25 06:53 UTC, JackBoosY approved these changes

2020-01-14 07:31 UTC, JackBoosY commented
/azp run

2020-01-16 00:38 UTC, merged