[azure-iot-sdk-c] Update macro-utils and umock-c to differentiate master and public-preview installations
microsoft/vcpkg pull request #9117
Opened 2019-11-27 20:00 UTC by ewertons

This change is necessary to keep the chain of submodule dependencies versions correct on the azure-iot-sdk-c vcpkg ports when installing using different flavors (from master or public-preview).

2019-11-27 20:06 UTC, danewalton commented on ports/azure-macro-utils-c/portfile.cmake
> +        HEAD_REF master
Should this be public preview

2019-11-27 20:06 UTC, danewalton commented on ports/umock-c/portfile.cmake
> +        HEAD_REF master
Same question here: public preview?

2019-11-27 20:09 UTC, danewalton-msft approved these changes

2019-11-27 20:59 UTC, ewertons commented on ports/azure-macro-utils-c/portfile.cmake
> +        HEAD_REF master
No, there is no public-preview branch for macro-utils.
Indeed only azure-iot-SDK-c has public-preview branch. All others are referenced through commits in their masters. The difference is that the azure-iot-SDK-c port will point to different commit trees throughout its submodules depending if regular or public-preview is being installed.

2019-11-27 20:59 UTC, ewertons commented on ports/umock-c/portfile.cmake
> +        HEAD_REF master
Same as above.

2019-11-27 21:01 UTC, jspaith approved these changes

2019-11-29 03:01 UTC, JackBoosY requested changes

2019-11-29 03:01 UTC, JackBoosY commented on ports/azure-c-shared-utility/CONTROL
> +Version: 2019-11-27.1
Can you please correct the Version field in the CONTROL file to `2019-10-07.2-1` [1]?

[1]. https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#version

2019-12-02 16:49 UTC, ewertons commented on ports/azure-macro-utils-c/CONTROL
> +Build-Depends:
Sure.

2019-12-02 16:50 UTC, ewertons commented on ports/umock-c/portfile.cmake
> +    vcpkg_from_github(
It is the same for now, but the commit ids and shas will start diverging after our next releases.

2019-12-02 16:52 UTC, ewertons commented on ports/azure-c-shared-utility/CONTROL
> +Version: 2019-11-27.1
Makes sense. Done.

2019-12-02 16:53 UTC, ewertons commented on ports/azure-macro-utils-c/portfile.cmake
> +    vcpkg_from_github(
Same comment as for the other one. This is in preparation of next releases, where the commits will diverge. This is for our automation to work well with the vcpkg ports.

2019-12-02 19:44 UTC, ewertons commented
Comments addressed, could you please let us know if there are any other blockers to merge? Thanks.

2019-12-03 02:39 UTC, JackBoosY commented
@ewertons The CI system does not test all features, so we need to test them in all triplets before merging this PR.

2019-12-03 04:09 UTC, JackBoosY commented
It looks like `azure-c-shared-utility [public-preview]` does not support uwp, if this is correct, please add `vcpkg_fail_port_install (ON_TARGET "UWP") ` on top of _PORTS/azure-c-shared-utility/portfile.cmake_ .

Thanks.

2019-12-03 05:12 UTC, JackBoosY approved these changes

2019-12-03 18:41 UTC, ewertons commented
@JackBoosY , would it be possible to check why the vcpkg-osx-PR pipeline run hasn't started yet? It's been queued since yesterday.

2019-12-04 03:16 UTC, JackBoosY commented
@ewertons Our OSX CI system is now being updated, so we need to wait a few days.

2019-12-06 17:35 UTC, ewertons commented
Folks, we have our release automation solution waiting for this to get in.
Could you please let us know when this will be merged?

2019-12-09 02:35 UTC, JackBoosY commented
@ewertons After repairing the CI system and re-running this PR test, we will merge this PR.

2019-12-10 19:11 UTC, merged