[ICU] Upgrade ICU to 65.1
microsoft/vcpkg pull request #9122
Opened 2019-11-28 05:06 UTC by xuhongxu96

Upgrade `ICU` to 65.1.

2019-12-02 06:43 UTC, xuhongxu96 commented
There are some compile issues. Pending.

2019-12-02 08:38 UTC, maksqwe commented
@grdowns please take a look. The current ICU version 61 cannot be downloaded.

2020-01-14 03:20 UTC, LilyWangL commented
/azp run

2020-01-15 08:09 UTC, LilyWangL requested changes

2020-01-15 08:09 UTC, LilyWangL commented on ports/icu/portfile.cmake
>  include(vcpkg_common_functions)
include(vcpkg_common_functions) is deprecated. Please remove it. 

Thanks.

2020-01-16 02:39 UTC, xuhongxu96 commented on ports/icu/portfile.cmake
>  include(vcpkg_common_functions)
Done.

2020-01-17 05:49 UTC, PhoebeHui approved these changes
LGTM, thanks for the PR!

2020-01-19 01:44 UTC, LilyWangL approved these changes

2020-01-19 03:20 UTC, JackBoosY approved these changes

2020-02-04 22:14 UTC, ras0219-msft commented
Thanks for the update!

2020-02-04 22:14 UTC, merged