[rapidstring] Update the repo to cenit/rapidstring
microsoft/vcpkg pull request #9143
Opened 2019-11-29 02:51 UTC by PhoebeHui

Related issue https://github.com/microsoft/vcpkg/issues/9115 and PR https://github.com/microsoft/vcpkg/pull/8912

The author of rapidstring delete their Github repro, update the repo to cenit/rapidstring.

Background:
https://github.com/microsoft/vcpkg/pull/8912#issuecomment-551969108
https://github.com/microsoft/vcpkg/pull/8912#issuecomment-558246277

rapidstring has no features need test locally.

2019-11-29 05:37 UTC, NancyLi1013 requested changes

2019-11-29 05:37 UTC, NancyLi1013 commented on ports/rapidstring/CONTROL
> +Version: 2019-11-29
Please also add homepage
Homepage: https://github.com/cenit/rapidstring

2019-11-29 05:54 UTC, NancyLi1013 approved these changes

2019-11-29 06:31 UTC, PhoebeHui commented on ports/rapidstring/CONTROL
> +Version: 2019-11-29
Thanks!

2019-12-02 21:20 UTC, grdowns commented
Thanks for doing this @PhoebeHui!

@cenit just a heads up, I've placed a message in the portfile letting the user know that you own the fork in question. If you'd prefer us to not do this, just tell us and we can revert it for you. Thanks!

2019-12-03 06:00 UTC, cenit commented
@grdowns ok sure, just to be clear that this is not from @boyerjohn. I just hope that people are not expecting me to do the development he just stopped, apart from that this repo will not disappear :)
I might also accept interesting PR in future if they will happen

2019-12-06 03:46 UTC, grdowns commented
After some thought, we should remove rapidstring unless we have someone willing to keep it maintained. To anyone reading, if this sounds like you then feel free to create a PR. We would be more than happy to have rapidstring again if there is interest :slightly_smiling_face:

2019-12-06 03:46 UTC, merged

2019-12-06 17:03 UTC, timautry commented
:( disappointing :( I guess that's life though :) Maybe someone else whose is willing and able may pick it up in the future :)