[expat] Update the version to 2.2.9 (add support for uwp)
microsoft/vcpkg pull request #9146
Opened 2019-11-29 09:36 UTC by NancyLi1013

Update to 2.2.9
- Add support for uwp
- Support` find_package() `by `expat-config.cmake` instead of `Findexpat.cmake`(Remove usage in _ports/expat/usage_)

Related issue #3174.

2020-01-06 02:50 UTC, NancyLi1013 commented
/azp run

2020-01-07 10:01 UTC, NancyLi1013 commented
/azp run

2020-01-09 02:16 UTC, NancyLi1013 commented
/azp run

2020-01-14 02:05 UTC, NancyLi1013 commented
/azp run

2020-02-20 02:17 UTC, NancyLi1013 commented
/azp run

2020-03-20 06:23 UTC, NancyLi1013 commented
/azp run

2020-04-16 09:14 UTC, NancyLi1013 commented
/azp run

2020-05-27 15:58 UTC, ray42 commented
@NancyLi1013 @JackBoosY what needs to be done to get this merged? Anything I could help with? I would love to get expat v2.2.9, thanks.

2020-05-27 16:20 UTC, JackBoosY commented
/azp run

2020-05-28 02:14 UTC, JackBoosY commented
@ray42 we are trying to solve the baseline error, then we will handle this PR.

2020-05-28 06:08 UTC, ray42 commented
@JackBoosY Thank you.

@NancyLi1013 - let me know if there is anything I can help out with, thank you.

2020-06-01 07:43 UTC, NancyLi1013 commented
/azp run

2020-06-09 06:48 UTC, NancyLi1013 commented
/azp run

2020-06-24 19:44 UTC, ray42 commented
The same tests have been failing for quite a while. Are they expected to fail? If so, should we add them to ci.baseline.txt ?
If not, is there anything I can do to help push this along? Thank you for everything you're doing, I appreciate it a lot.

2020-06-28 06:34 UTC, NancyLi1013 commented
@ray42 
Thanks for paying attention to this PR.
I will continue solving the regressions on this PR.
I will ask for your help if there is something need to be done from you.

2020-06-29 03:19 UTC, NancyLi1013 commented
/azp run

2020-06-30 06:59 UTC, oswjk commented
I also just want to thank anyone working on this. Keep up the good work 👍

2020-07-02 11:15 UTC, NancyLi1013 commented
It should work now.
@ray42 
Could you please help review this PR?
Any suggestions are welcomed.

2020-07-03 03:05 UTC, JackBoosY requested changes

2020-07-03 03:05 UTC, JackBoosY commented on ports/expat/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/${PORT})
```suggestion
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/expat)
```

2020-07-03 03:05 UTC, JackBoosY commented on ports/gdal/portfile.cmake
> +      file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/lib/libexpatMD.lib" EXPAT_LIBRARY_REL)
We should consider the non-Windows situations.

2020-07-03 03:05 UTC, JackBoosY commented on ports/readosm/portfile.cmake
> +    set(LIBS_ALL_DBG "\"${CURRENT_INSTALLED_DIR}/debug/lib/libexpatd.lib\" \"${CURRENT_INSTALLED_DIR}/debug/lib/zlibd.lib\"")
Same as above.

2020-07-03 03:05 UTC, JackBoosY commented on ports/spatialite-tools/portfile.cmake
> +    set(EXPAT_LIBS_REL "${LDIR}/lib/libexpat.lib")
Same as above.

2020-07-09 23:40 UTC, strega-nil commented
This seems like it should be merged; should we resolve conflicts and do so @NancyLi1013 ?

2020-07-10 05:55 UTC, NancyLi1013 commented
/azp run

2020-07-22 09:02 UTC, ray42 commented
Thank you @NancyLi1013 for all your hard work. Does it look like this can be merged now?

2020-07-22 10:20 UTC, NancyLi1013 commented
@ray42 
Thanks for your kindly reminder.
It should be fine on my sides. But since these features are blocked by other ports. 
 I'm not sure if all features can work well now.

2020-07-24 07:53 UTC, JackBoosY approved these changes

2020-07-24 10:01 UTC, NancyLi1013 commented
All features have finished testing.

- `skia[metal] `failed on x64-windows and x64-windows-static. (Also failed on master branch)

- `poco[mariadb,postgresql,pdf] `have passed on x64-windows.
- `poco[mysql] ` failed on x64-windows. (Also failed on master branch)
- `poco[mariadb,postgresql]` failed on x64-windows-static. (Also failed on master branch)
- `poco[pdf]` has passed on x64-windows-static
- `exiv2[unicode,xmp]` have passed on x86-windows and x64-windows-static.
- `gdal[mysql-libmariadb,libspatialite]` have passed on x64-windows.
- `gdal[mysql-libmariadb,libspatialite]` failed on x64-windows-static. (Also failed on master branch)

2020-07-27 07:31 UTC, NancyLi1013 commented
/azp run

2020-07-27 18:28 UTC, strega-nil commented
/azp run

2020-07-28 20:40 UTC, strega-nil commented
/azp run

2020-07-30 08:12 UTC, NancyLi1013 commented
The regression on x64-osx for `itk `is due to the following cause, which will be fixed in PR #11208.
```
Undefined symbols for architecture x86_64:
  "gdcm::Rescaler::SetMinMaxForPixelType(double, double)", referenced from:
      itk::GDCMImageIO::Write(void const*) in libITKIOGDCM-5.0.a(itkGDCMImageIO.cxx.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

2020-07-30 16:19 UTC, strega-nil commented
@NancyLi1013 is this `itk` failure going to happen regardless, or should we wait for #11208 to be merged?

2020-07-31 01:55 UTC, NancyLi1013 commented
The `itk `failure will happen regardless, which has existed for long time . It seems that this issue appeared in this PR https://github.com/microsoft/vcpkg/pull/10767#issuecomment-629959205 for the first time and the failure code was removed from ci.baseline.txt in #11513. It appeared again in #https://github.com/microsoft/vcpkg/pull/12067#issuecomment-649738044 and https://github.com/microsoft/vcpkg/pull/12133.

It should not block this PR. But we can also wait for #11208 merged and then try to rerun this PR. There are also many changes in this PR. We may wait for all CI checks have passed.

2020-08-05 17:37 UTC, strega-nil commented
/azp run

2020-08-05 19:47 UTC, strega-nil commented
@NancyLi1013 what's going on with `itk` and `cmake` on windows, do you know?

2020-08-06 07:44 UTC, NancyLi1013 commented
@strega-nil 

For the regressions caused by itk, I'm in investigation now.
For cmake, I don't know why it will fail.

I resolved the conflicts for `wxwidgets` just now. Let's wait for the new results.

2020-08-07 00:10 UTC, strega-nil commented
/azp run

2020-08-07 09:55 UTC, NancyLi1013 commented
The regressions for `itk `have been fixed now. 
But for `cmake`, I have no idea.

```
[503/504] cmd.exe /C "cd /D D:\buildtrees\cmake\x64-windows-dbg && D:\buildtrees\cmake\x64-windows-dbg\bin\cmake.exe -P cmake_install.cmake"
FAILED: CMakeFiles/install.util 
cmd.exe /C "cd /D D:\buildtrees\cmake\x64-windows-dbg && D:\buildtrees\cmake\x64-windows-dbg\bin\cmake.exe -P cmake_install.cmake"
ninja: build stopped: subcommand failed.
```

2020-08-14 02:06 UTC, NancyLi1013 commented
@strega-nil 
Thanks for your help to fix cmake issue.

I noticed that you updated cmake to 3.18.1 and also disable `-DCMAKE_USE_SYSTEM_EXPAT=OFF`.

I tried to install cmake 3.17.2 via  `.\vcpkg.exe install cmake --overlay-ports=scripts/test_ports `on my local on both master branch and expat branch, it failed with the same error, which is different from CI results.

The results from expat branch:
```
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(39): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(39): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(55): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(55): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(57): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(57): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(217): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(217): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\expet\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
```
The results from master branch:
```
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(39): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(39): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(55): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(55): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(57): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(57): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(217): error C2672: 'cm::static_reference_cast': no matching overloaded function found
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Source\cmGeneratorExpressionParser.cxx(217): error C2783: 'T &cm::static_reference_cast(O &)': could not deduce template argument for '__formal'
F:\new\vcpkg\buildtrees\cmake\src\7fc4616c28-392dff6306.clean\Utilities\std\cmext/memory(19): note: see declaration of 'cm::static_reference_cast'
```
So I'm not sure if the regressions on CI are related with the changes in this PR. I also have a doubt that why you update cmake to 3.18.1?

2020-08-14 16:29 UTC, strega-nil commented
@NancyLi1013 yeah, that was a thing that was broken in that version of CMake with the latest version of VC++.

2020-08-17 15:33 UTC, merged

2020-08-18 01:08 UTC, NancyLi1013 commented
@strega-nil thanks for your help.

2020-08-18 04:29 UTC, ray42 commented
Thanks to everyone, especially @NancyLi1013 , for the awesome work :)