[bento4] Fix install to add cmake config file
microsoft/vcpkg pull request #9161
Opened 2019-11-30 12:16 UTC by RamadanAhmed

2019-12-17 06:56 UTC, PhoebeHui commented on ports/bento4/fix-install-and-c4996-error.patch
> ++++ b/Bento4Config.cmake
Could you add Bento4Config.cmake to port/bento4, instead of patching it?

2019-12-17 06:57 UTC, PhoebeHui commented
@RamadanAhmed , thanks for the PR!

Could you open an issue for fixing the uwp failures? so others may replicate this problem.

2019-12-17 08:24 UTC, RamadanAhmed commented
> Could you open an issue for fixing the uwp failures? so others may replicate this problem.
add_definitions(-D_CRT_SECURE_NO_WARNINGS) already exists in the old patch(thanks to NancyLi1013) but I forget to add it.

2019-12-20 06:34 UTC, PhoebeHui approved these changes

2020-01-09 00:36 UTC, dan-shaw commented
/azp run

2020-01-09 22:50 UTC, dan-shaw commented
Can you bump the control file?

2020-01-09 22:53 UTC, dan-shaw commented on ports/bento4/fix-install-and-c4996-error.patch
> +
Can we remove the above lines so that the patch file is minimized?

2020-01-27 23:28 UTC, vicroms commented
/azp run

2020-02-03 06:58 UTC, PhoebeHui commented
@RamadanAhmed, can you please address the review suggestions? Thanks!

2020-02-06 08:26 UTC, PhoebeHui approved these changes

2020-02-06 23:01 UTC, ras0219-msft requested changes

2020-02-06 23:01 UTC, ras0219-msft commented on ports/bento4/fix-install-and-c4996-error.patch
> ++add_library(Bento4 STATIC ${AP4_SOURCES})
Why is it required to rename the binary away from upstream?

2020-02-09 10:53 UTC, RamadanAhmed commented on ports/bento4/fix-install-and-c4996-error.patch
> ++add_library(Bento4 STATIC ${AP4_SOURCES})
To be able to use like 
`target_link_libraries(main PRIVATE Bento4::Bento4)`
not 
`target_link_libraries(main PRIVATE Bento4::ap4)`

2020-02-14 06:58 UTC, ras0219-msft commented on ports/bento4/fix-install-and-c4996-error.patch
> ++add_library(Bento4 STATIC ${AP4_SOURCES})
Vcpkg will correctly detect the `Bento4::ap4` name and display help for the user, so I don't see that as a problem. Additionally, renaming the binaries causes incompatibilities with existing buildsystems which might use functions like
```
find_library(BENTO4 NAMES ap4)
```

We prefer to use upstream names whenever possible.

2020-05-12 06:59 UTC, PhoebeHui commented
Pinging @RamadanAhmed for response.

2020-05-22 10:30 UTC, RamadanAhmed commented
@PhoebeHui Sorry for being late, I think now its ready to be merged

2020-05-29 05:36 UTC, PhoebeHui requested changes
@RamadanAhmed thanks for your updates!

Could you also update the version from  1.5.1-628 to 1.5.1-628-1 in CONTROL file?

2020-05-29 05:36 UTC, PhoebeHui commented on ports/bento4/Bento4Config.cmake
> +include("${CMAKE_CURRENT_LIST_DIR}/Bento4Targets.cmake")
Could you update ' Bento4Targets.cmake' to 'bento4Targets.cmake'?

2020-05-31 06:40 UTC, RamadanAhmed commented
> @RamadanAhmed thanks for your updates!
> 
> Could you also update the version from 1.5.1-628 to 1.5.1-628-1 in CONTROL file?

it should be 1.6.0-634

2020-06-12 08:50 UTC, PhoebeHui commented
@RamadanAhmed, thanks for the updates!

Could you update 'Bento4Targets.cmake' to 'bento4Targets.cmake'? since it's case sensitive on Linux?

2020-07-01 02:01 UTC, PhoebeHui commented
@RamadanAhmed, could you adress the review suggestions? Thanks!
1. Bump the version in CONTROL file.
2.  Update 'Bento4Targets.cmake' to 'bento4Targets.cmake' in Bento4Config.cmake file.

2020-08-31 02:57 UTC, PhoebeHui commented
Closing this PR since it seems that no progress is being made, since the repository has been removed, however the changes is useful for us, I will summit a seprate PR for this.

2020-08-31 02:57 UTC, closed without merging