[bgfx] New ports: bgfx, bx, bimg
microsoft/vcpkg pull request #9163
Opened 2019-11-30 21:32 UTC by Outurnate

This is a resubmit of #7763 with some changes

- GENiE common logic has been moved to a common file
- tinystl includes the BSD license it's under with its include directory.  This is a separate project, but it has the same license as bx

2019-12-02 08:41 UTC, JackBoosY requested changes

2019-12-02 08:41 UTC, JackBoosY commented on ports/bgfx/portfile.cmake
> +# Common Ambient Variables:
Can you please remove the comments from line 1 to line 11 in `portfile.cmake`?

2019-12-02 08:41 UTC, JackBoosY commented on ports/bgfx/portfile.cmake
> +include(vcpkg_common_functions)
We don't need to include it in `portfile.cmake` anymore, please remove this line.

2019-12-02 08:41 UTC, JackBoosY commented on ports/bimg/portfile.cmake
> +# Common Ambient Variables:
Can you please remove the comments from line 1 to line 11 in `portfile.cmake`?

2019-12-02 08:41 UTC, JackBoosY commented on ports/bimg/portfile.cmake
> +include(vcpkg_common_functions)
We don't need to include it in `portfile.cmake` anymore, please remove this line.

2019-12-02 08:41 UTC, JackBoosY commented on ports/bx/portfile.cmake
> +# Common Ambient Variables:
Can you please remove the comments from line 1 to line 11 in `portfile.cmake`?

2019-12-02 08:41 UTC, JackBoosY commented on ports/bx/portfile.cmake
> +include(vcpkg_common_functions)
We don't need to include it in `portfile.cmake` anymore, please remove this line.

2019-12-02 08:41 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_genie.cmake
> +    vcpkg_execute_required_process(
`vcpkg_execute_required_process` is deprecated in build process. Please use `vcpkg_execute_build_process` instead.

2019-12-03 02:21 UTC, Outurnate commented
All the necessary changes were made.  I took the time to update the commit refs from the upstream.  I've also added a step to include the shader compiler tool which is necessary for projects using bgfx

There is a patch file included - I've submitted bkaradzic/bgfx#1958 to upstream this

2019-12-03 02:24 UTC, Outurnate commented
Can anyone provide some guidance on retrieving logs from Azure DevOps?  One of the steps seems to reference storing the results in a container, but I can't figure out where that is

2019-12-03 02:57 UTC, JackBoosY requested changes

2019-12-03 02:57 UTC, JackBoosY commented on ports/bimg/portfile.cmake
> +    file(INSTALL "${SOURCE_DIR}/include/bimg" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
We prefer to add a patch to fix these installation issues instead of adding the installation code directly in `portfile.cmake`.

2019-12-03 02:57 UTC, JackBoosY commented on ports/bx/portfile.cmake
> +    file(INSTALL
We prefer to add a patch to fix these installation issues instead of adding the installation code directly in `portfile.cmake`.

2019-12-03 03:00 UTC, JackBoosY commented
@Outurnate You can click the `Details` link and view the log in `Test Modified Port`.

2019-12-17 23:46 UTC, Outurnate commented
@JackBoosY upstream has declined to apply the patch.  The CMake files generated by GENie don't link shaderc & friends to libdl.  According to the maintainer of bgfx and vcpkg, CMake generation isn't supported (ref bgfx#1958)

Appreciate the pointer to the detailed logs.  Since this change represents a total rewrite, I'll be closing this PR and resubmitting

2019-12-17 23:46 UTC, closed without merging