[CGNS] add new port and improve hdf5 with features
microsoft/vcpkg pull request #9183
Opened 2019-12-02 23:40 UTC by Neumann-A

#9181

2019-12-03 00:20 UTC, vicroms commented
/azp run

2019-12-10 03:21 UTC, JackBoosY commented
We should test all features in all triplets first.

2019-12-16 06:21 UTC, JackBoosY requested changes

2019-12-16 06:21 UTC, JackBoosY commented on ports/hdf5/CONTROL
> +Build-Depends:
Could you remove this line?

Thanks.

2019-12-16 08:04 UTC, Neumann-A commented on ports/hdf5/CONTROL
> +Build-Depends:
Done.

2019-12-16 08:09 UTC, JackBoosY commented
We need to test it in all triplets before merge.

2019-12-16 08:52 UTC, JackBoosY requested changes
```
-- Performing post-build validation
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:/9183/vcpkg/packages/hdf5_x86-windows/bin/ph5diff.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:/9183/vcpkg/packages/hdf5_x86-windows/debug/bin/ph5diff.exe

Found 2 error(s). Please correct the portfile:
    F:\9183\vcpkg\ports\hdf5\portfile.cmake
-- Performing post-build validation done
Error: Building package hdf5:x86-windows failed with: POST_BUILD_CHECKS_FAILED
```
Please fix this issue.

2019-12-16 08:52 UTC, JackBoosY commented on ports/cgns/CONTROL
> +Build-Depends: hdf5[mpi]
This feature depends on `hdf5[mpi]`, but `hdf5[mpi]` does not exist. Should it be `hdf5[parallel]`?

2019-12-16 08:58 UTC, Neumann-A commented on ports/cgns/CONTROL
> +Build-Depends: hdf5[mpi]
good catch. I have corrected it.

2019-12-16 09:13 UTC, JackBoosY commented
Build cgns using command `./vcpkg install cgns[fortran]` cause error in configuration steps:
```
CMake Error at CMakeLists.txt:117 (enable_language):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Kitware has implemented the required
  features but as of this version of CMake they have not been integrated to
  upstream ninja.  Pending integration, Kitware maintains a branch at:

    https://github.com/Kitware/ninja/tree/features-for-fortran#readme

  with the required features.  One may build ninja from that branch to get
  support for Fortran.


-- Configuring incomplete, errors occurred!
```

2019-12-16 09:16 UTC, JackBoosY requested changes

2019-12-16 09:16 UTC, JackBoosY commented on ports/cgns/portfile.cmake
> +IF(EXISTS ${CURRENT_PACKAGES_DIR}/debug)
Can we use macros to handle this part of the code? I want to reduce this part of the code.

2019-12-16 09:16 UTC, JackBoosY commented on ports/hdf5/portfile.cmake
> +        file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/bin/gif2h5${VCPKG_TARGET_EXECUTABLE_SUFFIX}
Can we use macros to handle this part of the code? I want to reduce this part of the code.

2019-12-16 09:17 UTC, Neumann-A commented
>Please fix this issue.

will do so if your single build PR for HDF5 is merged into master. (#9043) 
This PR is basically waiting for it to so that i can rewrite the tool installation/movement. 

> Build cgns using command ./vcpkg install cgns[fortran] cause error in configuration steps:

Please read the feature description.
```
Feature: fortran
Description: Enable fortran support (not yet implemented) 
```
Fortran is not yet merged into VCPKG. Needs #6939.

2019-12-16 09:19 UTC, Neumann-A commented on ports/cgns/portfile.cmake
> +IF(EXISTS ${CURRENT_PACKAGES_DIR}/debug)
that is the plan after PR 9043 is merged. I'll use the same approach as in e.g. VTK

2020-01-22 08:33 UTC, Neumann-A commented
@JackBoosY: Do you mind if I close this PR and let it be superseded by #9202? (because I would need to backport some changes from #9202 to this PR)

2020-01-22 08:47 UTC, JackBoosY commented
@Neumann-A Okay.

2020-01-22 08:50 UTC, closed without merging

2020-01-22 08:51 UTC, Neumann-A commented on ports/cgns/portfile.cmake
> +IF(EXISTS ${CURRENT_PACKAGES_DIR}/debug)
done in https://github.com/microsoft/vcpkg/pull/9202/commits/3595c5aeb9cd8a67a930cb0614a8fe2fd2181e2d

2020-01-22 08:52 UTC, Neumann-A commented on ports/hdf5/portfile.cmake
> +        file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/bin/gif2h5${VCPKG_TARGET_EXECUTABLE_SUFFIX}
done in https://github.com/microsoft/vcpkg/pull/9202/commits/3595c5aeb9cd8a67a930cb0614a8fe2fd2181e2d