Added port for AA+ library (astronomical algorithms)
microsoft/vcpkg pull request #9194
Opened 2019-12-03 11:10 UTC by Matioupi

This is a PR proposal for a new port of AA+ library by naughter software :
http://www.naughter.com/aa.html

I checked with the lib author that he is OK with having it integrated into vcpkg.

2019-12-03 11:10 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=9194) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=9194) before we can accept your contribution.<br/><br/>:x: Matioupi [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=9194)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=9194) it.</sub>

2019-12-04 05:49 UTC, JackBoosY requested changes

2019-12-04 05:49 UTC, JackBoosY commented on ports/libaaplus/CMakeLists.txt
> +set(LIBS_SRC
If all source files need to be added, we prefer to use:
`file(GLOB LIBS_SRC ${CMAKE_CURRENT_LIST_DIR}/*.cpp)`

2019-12-04 05:49 UTC, JackBoosY commented on ports/libaaplus/CMakeLists.txt
> +set(PUBLIC_HEADERS
If all source files need to be added, we prefer to use:
`file(GLOB PUBLIC_HEADERS ${CMAKE_CURRENT_LIST_DIR}/*.h)`

2019-12-04 05:49 UTC, JackBoosY commented on ports/libaaplus/CONTROL
> +Description: libaaplus is an astronomical computations library by naughter software : http://www.naughter.com/aa.html
Can you add homepage here?

2019-12-04 05:49 UTC, JackBoosY commented on ports/libaaplus/portfile.cmake
> +include(vcpkg_common_functions)
We no longer need to include this, please remove this line.

2019-12-04 05:49 UTC, JackBoosY commented on ports/libaaplus/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME LIBAAPLUS MODULE)
vcpkg_test_cmake is deprecated, please remove this line.

2019-12-04 06:58 UTC, Matioupi commented on ports/libaaplus/CMakeLists.txt
> +set(LIBS_SRC
done. I add all and substracted the one AATest.cpp file which is used to build the test executable, I hope this fit the rules.

2019-12-04 06:58 UTC, Matioupi commented on ports/libaaplus/CMakeLists.txt
> +set(PUBLIC_HEADERS
done

2019-12-04 06:58 UTC, Matioupi commented on ports/libaaplus/CONTROL
> +Description: libaaplus is an astronomical computations library by naughter software : http://www.naughter.com/aa.html
done

2019-12-04 06:58 UTC, Matioupi commented on ports/libaaplus/portfile.cmake
> +include(vcpkg_common_functions)
done

2019-12-04 06:58 UTC, Matioupi commented on ports/libaaplus/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME LIBAAPLUS MODULE)
done

2019-12-04 07:48 UTC, JackBoosY approved these changes

2019-12-04 18:19 UTC, Matioupi commented
I don't understand why the vcpkg-Linux-PR #20687 failed... will need a learning curve here and help from gurus !

2019-12-05 02:37 UTC, JackBoosY commented
@Matioupi It's a fake error, ignore it.

2019-12-09 04:23 UTC, ras0219-msft commented
/azp run

2019-12-10 23:48 UTC, dan-shaw commented
@Matioupi LGTM, the MacOS CI pipeline is down now, so we'll have to wait a bit before we can merge this.

2019-12-10 23:48 UTC, dan-shaw approved these changes

2019-12-11 02:56 UTC, JackBoosY commented
/azp run

2019-12-11 08:04 UTC, Matioupi commented
> 
> 
> @Matioupi LGTM, the MacOS CI pipeline is down now, so we'll have to wait a bit before we can merge this.

Seems like all the pipelines have issue this times ! One day the windows test pass, and next day it fails without obvious reasons.

2019-12-11 10:05 UTC, JackBoosY commented
@Matioupi Yes, we should update baseline in master branch.

2019-12-12 02:18 UTC, JackBoosY commented
/azp run

2019-12-18 07:01 UTC, Matioupi commented
is this long CI test queue time normal ? I see that the pipelines have restarted for some other PR tests.

2019-12-18 10:06 UTC, JackBoosY commented
After the CI system is fixed, we will merge it.

2020-01-06 12:37 UTC, Matioupi commented
Hello, is the CI system still down ?

2020-01-06 23:04 UTC, merged