[jsoncons] Update to v0.141.0
microsoft/vcpkg pull request #9230
Opened 2019-12-06 04:18 UTC by danielaparker

Update to v0.141.0

2019-12-11 04:02 UTC, dan-shaw approved these changes

2019-12-11 05:53 UTC, LilyWangL approved these changes

2019-12-11 05:55 UTC, LilyWangL requested changes
`include(vcpkg_common_functions)` is deprecated. Please remove it. Can you please use command `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright?

Thanks.

2020-01-01 19:04 UTC, danielaparker commented
Just noticed the comment. I'm closing this pull request and will follow up with another with the issue addressed.

2020-01-01 19:04 UTC, closed without merging

2020-01-02 01:28 UTC, danielaparker commented
Just FYI, I cancelled the old pull request and made a new one with an updated version. I incorporated the changes requested to portfile.cmake. I observe that the pull request is failing, but it looks like all recent pull requests from everyone are failing, so perhaps a common issue?
Best regards,Daniel

[jsoncons] Update to v0.143.0 by danielaparker · Pull Request #9522 · microsoft/vcpkg

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
[jsoncons] Update to v0.143.0 by danielaparker · Pull Request #9522 · mi...

Describe the pull request What does your PR fix? Fixes issue # Update to v0.143.0. Fixes issue in portfile.cmak...
 |

 |

 |





     On Wednesday, December 11, 2019, 12:55:44 a.m. EST, Lily <notifications@github.com> wrote:  
 
 
@LilyWangL requested changes on this pull request.

include(vcpkg_common_functions) is deprecated. Please remove it. Can you please use command file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright) to handle copyright?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.