[freeglut] Update to 3.2.1 and fix not found macro NDEBUG
microsoft/vcpkg pull request #9233
Opened 2019-12-06 08:42 UTC by JackBoosY

Related: #8315.

Note: this port does not contain any feature.

2019-12-06 09:17 UTC, JackBoosY commented
After this PR merges, I will open a new PR to delete `vcpkg-cmake-wrapper.cmake` to use `FreeGLUTConfig.cmake`.

2019-12-06 20:51 UTC, cenit commented on ports/freeglut/fix-debug-macro.patch
> + #              pragma comment (lib, "freeglut_static.lib")
These macro are wrong since we are renaming libs in the portfile....

2019-12-09 02:38 UTC, JackBoosY commented on ports/freeglut/fix-debug-macro.patch
> + #              pragma comment (lib, "freeglut_static.lib")
@cenit It's right because we apply this patch first and THEN rename the library name.

2019-12-09 05:28 UTC, cenit commented on ports/freeglut/fix-debug-macro.patch
> + #              pragma comment (lib, "freeglut_static.lib")
@jackboosy Maybe I was not clear enough. Just read what you are encapsulating with your patched macro: a pragma comment, which means a linker hint.
These macro are wrong because we are hinting the linker to use libraries which are not going to exist at all since we are renaming libraries in the portfile (and so those names will not exist anymore)

2019-12-09 06:56 UTC, JackBoosY commented on ports/freeglut/fix-debug-macro.patch
> + #              pragma comment (lib, "freeglut_static.lib")
@cenit Do you mean we need to create a patch to modify the freeglut library name instead of changing the library name in portfile.cmake?

2019-12-09 13:02 UTC, cenit commented on ports/freeglut/fix-debug-macro.patch
> + #              pragma comment (lib, "freeglut_static.lib")
exactly :)

2019-12-10 06:08 UTC, JackBoosY commented on ports/freeglut/fix-debug-macro.patch
> + #              pragma comment (lib, "freeglut_static.lib")
@cenit Fixed.

2019-12-13 03:19 UTC, PhoebeHui approved these changes

2020-01-07 02:06 UTC, JackBoosY commented
/azp run

2020-01-14 02:03 UTC, JackBoosY commented
/azp run

2020-01-19 07:46 UTC, JackBoosY commented
There are 2 PRs conflicts with this: #9081 #8385.

2020-02-12 01:20 UTC, ras0219-msft requested changes
We may also want to consider installing a wrapper file that intercepts `find_package(GLUT)` and redirects it to `find_package(FreeGLUT)`.

2020-02-12 01:20 UTC, ras0219-msft commented on ports/glui/fix-dependency-freeglut.patch
> ++set(GLUT_FOUND FreeGLUT_FOUND)
This should be `${FreeGLUT_FOUND}`, or just `1` since we passed `REQUIRED` above.

2020-02-12 01:20 UTC, ras0219-msft commented on ports/jasper/fix-find-freeglut.patch
> ++    set(GLUT_FOUND FreeGLUT_FOUND)
Same as above.

2020-02-26 08:34 UTC, JackBoosY commented on ports/freeglut/fix-static-lib-name.patch
> +-    ADD_LIBRARY(freeglut_static STATIC ${FREEGLUT_SRCS})
@ras0219-msft 
I hope that during dynamic and static build, the name of the generated library or the name of the library in `-config.cmake` will be the same to make it easier to use.

2020-02-26 09:29 UTC, JackBoosY commented on ports/freeglut/fix-debug-macro.patch
> ++#           if defined(NDEBUG) || !defined(_DEBUG)
@ras0219-msft 
After re-reading the related issues, I found that the problem was caused by the compiler not adding `NDEBUG` to the predefined definition when using the cmake project in Visual Studio to build the release.
That's weird, can you confirm it?

My solution has two:
1. Add the public macro `NDEBUG` when building release in `CMakeLists.txt` in freeglut so that the exported `config.cmake` contains the macro.
However, user may use `FindGLUT.cmake` provided by cmake to invalidate this solution.
2. Add the following code to freeglut.h:
```
#ifndef _DEBUG
#define NDEBUG
#endif
```

2020-05-08 04:52 UTC, JackBoosY commented
/azp run

2020-07-06 06:38 UTC, JackBoosY commented
Since #11527 fixed this issue, close this PR now.

2020-07-06 06:38 UTC, closed without merging