[qt5-base] Fix Qt5 linux build and be a bit less flaky in CI
microsoft/vcpkg pull request #9260
Opened 2019-12-09 18:39 UTC by Neumann-A

2019-12-11 18:19 UTC, Neumann-A commented
There was also an issue with linkage of expat. Have to find the port linking to it

2019-12-11 18:23 UTC, Neumann-A commented
will add the following fixes described here as soon as i have time: 
https://github.com/microsoft/vcpkg/pull/8912#issuecomment-552799724
https://github.com/microsoft/vcpkg/pull/8912#issuecomment-554796750

2019-12-12 02:48 UTC, JackBoosY commented
/azp run

2019-12-12 16:10 UTC, Neumann-A commented
So I included every fix I know of in this PR.

2019-12-12 18:29 UTC, janholt commented
Seems there are two problems with Qt that worth to note.


On `x64-linux` `Debug` and `Release` installations are not merged.
`Qt5CoreConfig.cmake` on `x64-linux` only has
```
    _populate_Core_target_properties(RELEASE "libQt5Core.a" "" )
```
while on `x64-windows` there is
```
    _populate_Core_target_properties(RELEASE "Qt5Core.dll" "Qt5Core.lib" )

    if (EXISTS
        "${_qt5Core_install_prefix}/debug/bin/Qt5Cored.dll"
      AND EXISTS
        "${_qt5Core_install_prefix}/debug/lib/Qt5Cored.lib" )
        _populate_Core_target_properties(DEBUG "Qt5Cored.dll" "Qt5Cored.lib" )
    endif()
```

And the major one: there is no "direct" way to link static Qt from cmake (no targets for plugins and additional libraries(Qt5ThemeSupport), dependencies(external, internal) not declared). So `x64-linux` does not work out-of-the-box.
Here is the work on this topic: https://bugreports.qt.io/browse/QTBUG-38913

2019-12-12 19:37 UTC, Neumann-A commented
I'll adress #9296 and #9299 next

2019-12-12 19:51 UTC, Neumann-A commented
next issue: _populate_Core_plugin_properties only populates release properties

2019-12-12 20:20 UTC, Neumann-A commented
hmm seems like fixcmake.py is not 100% doing what it should be
```
    dllpattern = re.compile("_install_prefix}/bin/Qt5.*d+(.dll|.so)")
    libpattern = re.compile("_install_prefix}/lib/Qt5.*d+(.lib|.a)")
    exepattern = re.compile("_install_prefix}/bin/[a-z]+(.exe|)")
    toolexepattern = re.compile("_install_prefix}/tools/qt5/bin/[a-z]+(.exe|)")
    tooldllpattern = re.compile("_install_prefix}/tools/qt5/bin/Qt5.*d+(.dll|.so)")
```

2019-12-12 22:51 UTC, Neumann-A commented
@janholt: Your issue should be solved now

2019-12-13 03:10 UTC, JackBoosY commented
If you have completed this fix, please let me know.

Thanks.

2019-12-13 13:17 UTC, Neumann-A commented
@JackBoosY: Should be finished if CI finishes successfully. I'll not spent time to fix single configuration builds though. They worked by circumstance before because debug/release were not merged correctly.

2019-12-13 13:23 UTC, Neumann-A commented on scripts/ci.baseline.txt
>  qt5-tools:x64-windows-static=ignore
Should this still be on the CI ignore list? 
Will ignore get build by CI? 
It should be successful and only fail if libwebp is build with all features.

2019-12-15 21:02 UTC, Neumann-A commented
@JackBoosY CI for Linux and Windows are green. So I am finished with it

2019-12-15 22:41 UTC, Neumann-A commented
Also VTK should build on linux. The error is:
```
CMake Error at Rendering/OpenGL2/CMakeLists.txt:154 (message):
  X11_Xt_LIB could not be found.  Required for VTK X lib.
```
so the CI machine is missing some required system library

2019-12-16 04:57 UTC, JackBoosY commented
> Also VTK should build on linux. The error is:
> 
> ```
> CMake Error at Rendering/OpenGL2/CMakeLists.txt:154 (message):
>   X11_Xt_LIB could not be found.  Required for VTK X lib.
> ```
> 
> so the CI machine is missing some required system library

Confirmed.

2019-12-16 05:00 UTC, JackBoosY requested changes

2019-12-16 05:00 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +qt5-tools:x64-linux=pass
You can just remove them.

2019-12-16 08:22 UTC, Neumann-A commented on scripts/ci.baseline.txt
> +qt5-tools:x64-linux=pass
done. I didn't know of serious the issue was with qt5-tools so I expected to change it back but after seeing that it were just linking errors I moved forward to resolve those.

2019-12-16 08:29 UTC, JackBoosY approved these changes

2019-12-16 09:29 UTC, zweistein-frm2 commented
Hello,
I lost track on wether the qt5 linux (or WSL) build is working now?  Which branch should I use? Please could you give a simple link as I am not so literate in advanced git. Thank you

2019-12-16 09:58 UTC, Neumann-A commented
@zweistein-frm2: If you cannot wait until this is merged into master:
```
git clone https://github.com/microsoft/vcpkg.git
git remote add Neumann-A https://github.com/Neumann-A/vcpkg.git
git fetch Neumann-A
git merge Neumann-A/fix_qt_linux
```

2019-12-17 06:36 UTC, zweistein-frm2 commented
OK, almost there, takes 6-12 h to compile on linux and goes through
But when I want to install something else (vcpkg install boost for example)  then I get
Error: database corrupted. Package qt5:x64-linux is installed but dependency qt5-purchasing:x64-linux is not. Seems that vcpkg installation is busted!

2019-12-17 06:42 UTC, zweistein-frm2 commented
Seems that the database corruptions occurred only on a Windows and WSL install. On a real Ubuntu 18.04 there are no problems

2019-12-17 06:46 UTC, zweistein-frm2 commented
Maybe related:  The windows vcpkg and the WSL vcpkg directories point to the same folder. Should be fine? as the triplets are in seperate folders

2019-12-17 07:37 UTC, Neumann-A commented
>Error: database corrupted. Package qt5:x64-linux is installed but dependency qt5-purchasing:x64-linux is not. Seems that vcpkg installation is busted!

Yep the reason is:
>Maybe related: The windows vcpkg and the WSL vcpkg directories point to the same folder. Should be fine?

No its not fine. vcpkg is not designed to be run in parallel into the same installed folder. This typically corrupts the database located in the folder `installed/vcpkg`

2019-12-21 01:17 UTC, ras0219-msft commented on ports/qt5-base/vcpkg-cmake-wrapper.cmake
> +        #The fact that we are within this file means we are using the VCPKG toolchain. Has such we only need to search in VCPKG paths!
👍

2019-12-21 01:22 UTC, ras0219-msft commented
>No its not fine. vcpkg is not designed to be run in parallel into the same installed folder.

You're 100% correct, but just to be very verbose about it:

1) Running multiple vcpkg processes operating on the same instance at the same time is not allowed.
2) Sharing one instance between Windows and WSL _is_ allowed (as long as you don't modify it from both at the same time).

So it's ok to open a windows prompt, run `vcpkg install xyz`, wait for it to finish, then open wsl and run the same command. It's not ok to launch CMD and WSL prompts and run `vcpkg install xyz` in both to see which finishes first.

2019-12-21 01:24 UTC, ras0219-msft commented
/azp run

2020-01-03 02:51 UTC, JackBoosY commented
/azp run

2020-01-06 20:36 UTC, merged