[fmt] Update to 6.1.2
microsoft/vcpkg pull request #9289
Opened 2019-12-11 21:16 UTC by kevinlul

2019-12-12 05:46 UTC, NancyLi1013 requested changes

2019-12-12 05:46 UTC, NancyLi1013 commented on ports/fmt/portfile.cmake
>  vcpkg_from_github(
`include(vcpkg_common_functions)` is no longer needed. Could you please remove this line?

2019-12-12 05:46 UTC, NancyLi1013 commented on ports/fmt/portfile.cmake
> +    REF 6.1.2
We prefer to use commit id `f94b7364b9409f05207c3af3fa4666730e11a854` instead of tag name here.
Could you please update it?

2019-12-12 06:13 UTC, NancyLi1013 commented
@kevinlul thanks for the PR.

Failing on the Windows CI:
```
CMake Error at ports/fmt/portfile.cmake:24 (file):
  file RENAME failed to rename

    C:/vsts/_work/3/s/packages/fmt_x86-windows/debug/lib/fmtd.dll

  to

    C:/vsts/_work/3/s/packages/fmt_x86-windows/debug/bin/fmtd.dll

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
```
As  _bin/fmtd.dll_ has existed, it cannot be renamed again.

Failing on the Linux CI:
```
l-inl.h: In member function ‘bool spdlog::details::thread_pool::process_next_msg_()’:
/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/thread_pool-inl.h:119:9: error: ‘assert’ was not declared in this scope
         assert(false && "Unexpected async_msg_type");
         ^~~~~~
compilation terminated due to -Wfatal-errors.
```
spdlog failed on the `Linux `due to above reason.

Please take a look and try to fix them.

2019-12-12 06:17 UTC, NancyLi1013 commented
What does this PR fix? Please open an issue so others may replicate this problem.

2019-12-12 21:28 UTC, rleigh-codelibre commented on ports/fmt/portfile.cmake
> +    REF 6.1.2
@NancyLi1013 What is the reason for this change?  The integrity of the commit is ensured by the file hash:

`8770bf4bd2bb6d938e75e0cf1e665c41930dbd9d2a6825274a5a43cd1d85b9c9ca621bb040ed099429f0e16bddbc3399361c453eb1bf3fc01376e6ad9dd875b7 fmt-6.1.2.tar.gz`

and GitHub's release process should guarantee that the tag remains stable: https://github.com/fmtlib/fmt/releases/tag/6.1.2

What are the scenarios which this policy change is attempting to mitigate?  I understand the commit hash is guaranteed stable, however I've yet to see a problem in practice with any packaging system using git tags as references.

2019-12-13 19:18 UTC, kevinlul commented
This is a simple package update to the latest version of **{fmt}**

2019-12-13 20:45 UTC, dan-shaw commented
@kevinlul LGTM, still waiting for the MacOS pipeline

2019-12-13 22:00 UTC, kevinlul commented
I don't know about the spdlog regression on all platforms or the arm failures

2019-12-16 07:54 UTC, NancyLi1013 commented
@kevinlul  The failures on Windows platform from CI system:
`C:\vsts\_work\3\s\buildtrees\spdlog\src\34724392a0-c671dd4aa9\include\spdlog/details/thread_pool-inl.h(119): error C3861: 'assert': identifier not found`

`C:\vsts\_work\3\s\buildtrees\spdlog\src\34724392a0-c671dd4aa9\include\spdlog/details/pattern_formatter-inl.h(76): error C3861: 'assert': identifier not found`

The failures on Linux are the same as those on Windows.

2020-01-03 02:51 UTC, JackBoosY commented
/azp run

2020-01-06 22:48 UTC, dan-shaw commented
@kevinlul I've just merged #9121, which may fix the regressions in the CI. Can you check?

2020-01-09 16:43 UTC, kevinlul commented
Doesn't look like it.

2020-01-10 01:45 UTC, NancyLi1013 commented
/azp run

2020-01-14 02:38 UTC, JackBoosY commented
/azp run

2020-01-19 08:39 UTC, NancyLi1013 commented
It seems that there is something wrong with patch.
I got the error info from CI system:
```
Checking patch include/fmt/format.h...
error: while searching for:
#ifndef FMT_FORMAT_H_
#define FMT_FORMAT_H_

#include <algorithm>
#include <cassert>
#include <cmath>

error: patch failed: include/fmt/format.h:33
error: include/fmt/format.h: patch does not apply
```
Could you please help check?

2020-01-20 02:55 UTC, NancyLi1013 commented
/azp run

2020-01-20 05:52 UTC, NancyLi1013 commented
The regressions on Linux and Windows caused by `spdlog` still exist.

Could you take a look?

2020-02-19 17:55 UTC, kevinlul commented
Closing due to redundancy with two other PRs.

2020-02-19 17:55 UTC, closed without merging