[libevent] Fix include headers fails on x64-windows, using CMAKE
microsoft/vcpkg pull request #9292
Opened 2019-12-12 06:24 UTC by AlvinZhangH

Related issue #9275.

1. fix LibeventConfig.cmake.in path
2. Delete deprecated functions
3. Update deprecated functions

All Features of this port install ok on triplet x86-windows, x64-windows, x64-linux.

2020-01-03 08:20 UTC, AlvinZhangH commented
/azp run

2020-01-06 05:43 UTC, JackBoosY requested changes
Could you update version in _CONTROL_?

2020-01-06 08:27 UTC, AlvinZhangH commented
@JackBoosY  Already updated the version.

2020-01-06 08:52 UTC, JackBoosY approved these changes

2020-01-06 20:38 UTC, merged