[opendnp3] Add new port
microsoft/vcpkg pull request #9313
Opened 2019-12-13 15:00 UTC by OOPMan

Fixes issue #9312

2019-12-13 15:00 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=9313) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=9313) before we can accept your contribution.<br/><br/>:x: OOPMan [sign now](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=9313)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/vcpkg?pullRequest=9313) it.</sub>

2019-12-16 03:08 UTC, PhoebeHui commented
@OOPMan , thanks for the PR!

The CI test failed with following triplet, is it expected? if not, could you help take a look?
opendnp3:x64-uwp
opendnp3:arm-uwp

If so, could you add 'vcpkg_fail_port_install(ON_TARGET "uwp")'  at the top of portfile.cmake. And
could you also update https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt?

opendnp3:x64-uwp=fail
opendnp3:arm-uwp=fail

2019-12-16 03:08 UTC, PhoebeHui requested changes

2019-12-16 14:02 UTC, OOPMan commented on ports/opendnp3/portfile.cmake
> +include(vcpkg_common_functions)
Will do

2019-12-16 14:05 UTC, OOPMan reviewed
> @OOPMan , thanks for the PR!
> 
> The CI test failed with following triplet, is it expected? if not, could you help take a look?
> opendnp3:x64-uwp
> opendnp3:arm-uwp
> 
> If so, could you add 'vcpkg_fail_port_install(ON_TARGET "uwp")' at the top of portfile.cmake. And
> could you also update https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt?
> 
> opendnp3:x64-uwp=fail
> opendnp3:arm-uwp=fail

@PhoebeHui I think this failure can be expected as I don't think the library actually supports UWP at all. I'll add the makefile and update the baseline as requested.

2019-12-17 01:55 UTC, PhoebeHui approved these changes

2019-12-18 02:24 UTC, PhoebeHui approved these changes

2019-12-18 06:13 UTC, JackBoosY approved these changes

2019-12-19 20:13 UTC, dan-shaw approved these changes

2019-12-20 20:00 UTC, merged