[boost] Update to 1.72.0
microsoft/vcpkg pull request #9317
Opened 2019-12-14 13:15 UTC by yurybura

Update Boost libarary to 1.72.0:
*  `generate-ports.ps1` script was modified to support new version and was run to re-generate related ports;
* custom build settings for `boost-iostreams` port were removed;
* `boost-python` was fixed to find Python3 even Python2 port is installed.
 
Fixes issues #9298

2019-12-15 08:19 UTC, cenit reviewed
Please also edit the generate-ports.ps1 to remove `include(vcpkg_common_functions)`

2019-12-15 08:19 UTC, cenit commented on ports/boost-python/portfile.cmake
> +set(PYTHON_DIR_NAME "python3\.*")
This dir_name won't work on *nix. Please change the backslash to a forward slash

2019-12-15 08:19 UTC, cenit commented on scripts/boost/post-source-stubs/python.cmake
> +set(PYTHON_DIR_NAME "python3\.*")
Same here

2019-12-15 10:39 UTC, yurybura commented on ports/boost-python/portfile.cmake
> +set(PYTHON_DIR_NAME "python3\.*")
`\.` matches the character `.` literally. Include path must be [...]/python3.6 or [...]/python3.7, etc.

2019-12-15 20:01 UTC, yurybura commented on scripts/boost/post-source-stubs/python.cmake
> +set(PYTHON_DIR_NAME "python3\.*")
Fixed.

2019-12-15 20:01 UTC, yurybura commented on ports/boost-python/portfile.cmake
> +set(PYTHON_DIR_NAME "python3\.*")
Fixed.

2019-12-15 20:04 UTC, yurybura commented
> This means that libgo is not buildable anymore in any os nor any config?

Temporary yes, this library is not compatible with Boost.Context 1.72.0.

2019-12-16 02:37 UTC, PhoebeHui approved these changes
Thanks for the PR!

2019-12-19 22:34 UTC, ras0219-msft requested changes

2019-12-19 22:34 UTC, ras0219-msft commented on scripts/boost/generate-ports.ps1
> -        elseif ($Name -eq "iostreams")
Please revert the changes to how `boost-iostreams` is handled and submit it as a separate PR

2019-12-20 02:36 UTC, PhoebeHui commented
Related to https://github.com/microsoft/vcpkg/pull/8372

2019-12-20 22:08 UTC, yurybura commented on ports/boost-system/portfile.cmake
> -vcpkg_buildpath_length_warning(37)
I've added it for boost-system only (like it was before).

2019-12-20 22:09 UTC, yurybura commented on scripts/boost/generate-ports.ps1
> -        elseif ($Name -eq "iostreams")
Reverted.

2019-12-24 05:53 UTC, JackBoosY commented
/azp run

2020-01-03 02:50 UTC, JackBoosY commented
/azp run

2020-01-06 20:30 UTC, dan-shaw commented
/azp run

2020-01-06 20:41 UTC, yurybura commented
Dear @dan-shaw, CI was failed with empty log,.. could you help to investigate the reason?

2020-01-07 02:20 UTC, JackBoosY commented
/azp run

2020-01-09 01:23 UTC, dan-shaw commented
/azp run

2020-01-09 01:23 UTC, dan-shaw commented
Should work now

2020-01-13 19:49 UTC, ras0219-msft commented
/azp run

2020-01-13 22:35 UTC, ras0219-msft commented
/azp run

2020-01-14 02:54 UTC, JackBoosY commented
/azp run

2020-01-16 11:42 UTC, yurybura commented
Finally all checks have done. Please merge or request changes. Thanks a lot.

2020-01-16 23:10 UTC, vicroms commented
Thanks for the PR!

2020-01-16 23:10 UTC, merged