[liblas] link with laszip to support .laz (compressed .las) files.
microsoft/vcpkg pull request #9351
Opened 2019-12-17 11:56 UTC by LaurensVoerman

By linking liblas with laszip, it gains support for compressed .laz files.
I have only just read that liblas is being replaced by pdal, but we are still using liblas to get read ability for las and laz in osg.
Regards, Laurens.

2019-12-18 05:50 UTC, NancyLi1013 commented
/azp run

2019-12-19 01:51 UTC, NancyLi1013 commented on ports/liblas/portfile.cmake
> +file(REMOVE ${SOURCE_PATH}/cmake/modules/FindLASzip.cmake)
include(vcpkg_common_functions) is no longer needed. Could you please remove it?

2019-12-19 02:12 UTC, NancyLi1013 requested changes

2019-12-20 10:28 UTC, LaurensVoerman commented
I found out that this change is not working at all (laszip is still not found) and after attempting to fix that I found that the version of laszip (3.4.1) in vcpkg is not compatible with liblas (needs laszip 2.1.0 or 2.2.0).
Sorry for wasting your time.
Regards, Laurens.

2019-12-20 10:28 UTC, closed without merging