[bgfx] Add new port
microsoft/vcpkg pull request #9369
Opened 2019-12-19 16:27 UTC by Outurnate

Rewrite of #9163

I've only written a port for bgfx.  There's no way to get GENie to use the artifacts from another port (i.e. bx or bimg), so I saw little point in exposing them

There was a bug in vcpkg_build_make as well - the docs specified that there was a `TARGET` parameter where no such parameter existed.  I added this parameter, as well as two others to override the target for debug/release builds

2019-12-20 06:34 UTC, JackBoosY commented
Seems have problem:
```
make: *** No rule to make target 'vs2017-debug32'.  Stop.
```

2019-12-21 18:59 UTC, Outurnate commented
A couple more changes in `vcpkg_build_make`.  I added a new `WORKING_DIRECTORY` option.  I removed the section that closes `gpg-agent.exe` on Windows since it doesn't work (the code was copy/pasted from the icu port - it still had a ref to a variable that was only in the original port).  It seemed unnecessary since the process is a part of Msys2 and in no way prevents the build from completing

As it turns out, the windows make target for the project is sort of broken.  The makefile just calls `devenv PATH_TO_SLN /Build` which ends up just launching Visual Studio.  I used the makefile to generate the SLN file, then ran msbuild over that

2020-01-03 02:49 UTC, JackBoosY commented
/azp run

2020-01-07 09:27 UTC, JackBoosY commented
/azp run

2020-01-09 09:08 UTC, JackBoosY commented
/azp run

2020-01-14 02:53 UTC, JackBoosY commented
/azp run

2020-01-16 06:24 UTC, JackBoosY commented
Only have windows build failure, please download failure log [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=25475&view=artifacts&type=publishedArtifacts) and resolve them.

Thanks.

2020-01-16 08:28 UTC, Outurnate commented
There's nothing in any of those log bundles.  I tested this port on the Windows 10 dev VM provided by Microsoft

2020-01-16 10:16 UTC, JackBoosY commented
@Outurnate I will provide your failure logs tomorrow.

2020-01-17 08:10 UTC, JackBoosY commented
@Outurnate I think you catch a vcpkg bug.

2020-01-17 08:26 UTC, JackBoosY requested changes

2020-01-17 08:26 UTC, JackBoosY commented on ports/bgfx/portfile.cmake
> +  set(EXECUTABLE_SUFFIX ".exe")
Could you remove it and replace it to `VCPKG_TARGET_EXECUTABLE_SUFFIX`?

2020-04-14 08:45 UTC, LilyWangL commented
@Outurnate Can you address the review suggestions? Thanks!

2020-04-20 17:39 UTC, StuartDAdams commented
Would be really eager to see this library added to vcpkg.

2020-05-14 02:39 UTC, JackBoosY commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2020-05-14 02:39 UTC, closed without merging