[nano-signal-slot] Update to latest version
microsoft/vcpkg pull request #9376
Opened 2019-12-20 01:17 UTC by RT222

I know that official releases should be preferred, but I used the latest commit instead because it fix an issue which was causing compilations error on the latest MSVC version (https://github.com/NoAvailableAlias/nano-signal-slot/issues/26).

2019-12-20 01:38 UTC, NancyLi1013 requested changes

2019-12-20 01:38 UTC, NancyLi1013 commented on ports/nano-signal-slot/CONTROL
> +Version: 20-12-2019
The Version field seems some problem. 
Could you update it as 2019-12-20?

2019-12-20 02:43 UTC, RT222 commented on ports/nano-signal-slot/CONTROL
> +Version: 20-12-2019
My bad, that's the French date format, I changed it.

2019-12-20 09:57 UTC, NancyLi1013 approved these changes

2019-12-21 01:12 UTC, merged

2019-12-21 01:12 UTC, ras0219-msft commented
Thanks for the PR!