[uvatlas] Upgrade to dec2019
microsoft/vcpkg pull request #9379
Opened 2019-12-20 05:47 UTC by AlvinZhangH

Related issue #9370.

This port install ok on triplet x86-windows, x64-windows, UVAtlas only supports Windows Desktop
No features need to test.

2019-12-20 10:07 UTC, JackBoosY requested changes

2019-12-20 10:07 UTC, JackBoosY commented on scripts/ci.baseline.txt
> +uvatlas:x86-windows-static=fail
We don't test `x86-windows-static` by default, please remove it.

2019-12-22 20:43 UTC, ZeeZeeMorin approved these changes

2019-12-26 02:13 UTC, JackBoosY approved these changes

2019-12-27 06:31 UTC, AlvinZhangH commented
@ZeeZeeMorin  Help what？

2019-12-27 08:19 UTC, ZeeZeeMorin approved these changes

2020-01-02 20:51 UTC, dan-shaw commented
/azp run

2020-01-02 21:56 UTC, merged