oatpp 0.19.11 port
microsoft/vcpkg pull request #9402
Opened 2019-12-21 13:47 UTC by mheyman

Oat++ is a "Modern Web Framework for C++. High performance, simple API, cross-platform, zero-dependency."

I managed to get the core Oat++ and most of the submodules to compile on Windows and Linux - untested on Mac. Oat++ windows support is recent and not available on the libressl submodule (requires libressl3.0 and vcpkg has 2.9.1-2) - the mbedtls submodule covers what I need so it isn't a show-stopper.

Some submodules require pkg-config to be available for building. Vcpkg doesn't seem to have support for pkg-config. Because of this, I had to go through semi-extraordinary measures to detect and use pkg-config and feel lucky that pkg-config to have found a way without resorting to patching Oat++'s CMakeLists.txt files. I did include a message about how to get pkg-config when you don't have it.

(Also, I think PR should have been a continuation of [#9244](https://github.com/microsoft/vcpkg/pull/9244) which I accidentally closed).

2019-12-23 20:09 UTC, ras0219-msft commented
/azp run

2019-12-24 07:05 UTC, JackBoosY requested changes

2019-12-24 07:05 UTC, JackBoosY commented on ports/oatpp/portfile.cmake
> +function(verify_pkg_config SUBMODULE_NAME)
vcpkg does not depend on using pkgconfig, please implement this code in other ways (e.g. find_program / find_package / find_library).

2019-12-24 07:05 UTC, JackBoosY commented on ports/oatpp/portfile.cmake
> +    message(STATUS "Warning: Building dynamic libraries not supported. Building static libraries linking to a ${_crt_linkage_text} CRT.")
Could you use `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` instead of these 2 lines?

2019-12-24 12:34 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +function(verify_pkg_config SUBMODULE_NAME)
Unfortunately, I'm not an Oat++ developer (just a user) - it may take me a while to figure out how to make patches for the cmake files to get rid of the pkgconfig dependency. If I get a version that works for both vcpkg and the other Oat++ targets, I'll certainly do a pull request for Oat++ to hopefully get rid of Oat++'s dependency on pkgconfig. In the mean time, I've been building Oat++ vcpkg with pkgconfig on Windows and Linux with enough success to be useful - that is, I haven't run into any debug vs release ABI issues (because I defaulted to pkgconfig using release builds).

2019-12-24 12:37 UTC, mheyman commented on ports/oatpp/CONTROL
> +Build-Depends:
Done - didn't know that was a think :-)

2019-12-24 12:37 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +function(dump_variables)
But that is my favorite function :-) - all gone now

2019-12-24 12:37 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +# if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
Done

2019-12-24 12:38 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +    message(STATUS "Warning: Building dynamic libraries not supported. Building static libraries linking to a ${_crt_linkage_text} CRT.")
Didn't know that existed, I had just copied some other port that I got to by googling - it was probably old code...

2019-12-26 14:30 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +function(verify_pkg_config SUBMODULE_NAME)
Added a patch that detects if compiling in vcpkg and sets the PKG_CURL... variables appropriately for the rest of the build.

2019-12-27 02:32 UTC, JackBoosY requested changes

2019-12-27 02:32 UTC, JackBoosY commented on ports/oatpp/curl-submodule-no-pkg-config-in-vcpkg.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
Can you change the document format of this patch to LF?

2019-12-27 17:49 UTC, mheyman commented on ports/oatpp/curl-submodule-no-pkg-config-in-vcpkg.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
Done - didn't seem them...

2019-12-30 02:21 UTC, JackBoosY requested changes

2019-12-30 02:21 UTC, JackBoosY commented on ports/oatpp/portfile.cmake
> +# For when OATPP dynamic linkage builds:
If we don't need this code, please delete these commented codes.

2019-12-30 13:51 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +# For when OATPP dynamic linkage builds:
The OATPP_VERSION variable is required.

Oat++ doesn't build with dynamic linkage - I've started looking into the changes necessary and, while I'm no expert on C++ classes in DLLs and shared libraries, I think the changes would be pretty extensive.

2020-01-03 02:49 UTC, JackBoosY commented
/azp run

2020-01-07 09:27 UTC, JackBoosY commented
/azp run

2020-01-09 09:07 UTC, JackBoosY commented
/azp run

2020-01-14 02:52 UTC, JackBoosY commented
/azp run

2020-01-16 06:22 UTC, JackBoosY commented
Any progress?

2020-01-17 04:28 UTC, PhoebeHui requested changes
@mheyman, thanks for your PR!

@vicroms, what do you think?

2020-01-17 04:28 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +    vcpkg_copy_pdbs()
I think it's better to add a separate port to vcpkg and add the dependency to the feature.

2020-01-17 04:28 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +    vcpkg_copy_pdbs()
Same as above.

2020-01-17 04:28 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +endif()
Same as above.

2020-01-17 04:28 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +        HEAD_REF master
Same as above.

2020-01-17 04:28 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +    vcpkg_copy_pdbs()
Same as above.

2020-01-17 04:28 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +    vcpkg_copy_pdbs()
Same as above.

2020-01-17 14:05 UTC, mheyman commented on ports/oatpp/portfile.cmake
> +    vcpkg_copy_pdbs()
Not quite sure what you are saying so I'll restate it: 
    
    you think it would be better to have an oatpp vcpkg port 
    and a separate oatpp-consul vcpkg port with a dependency 
    on the oatpp port.

If this is the case, it may be possible but I believe the oatpp-consul port will need to be able to find the oatpp build directory (on line 46 above) and I'm not sure how to do that in vcpkg land. The Oat++ developers may be able to make it so Oat++ modules can build without this intimate connection to the base Oat++ code but that isn't there yet. One possible solution would be to copy the required files from the base Oat++ code into the installed/../share directory and point module builds at that location - is that an okay solution for vcpkg builds like this?

2020-01-20 02:34 UTC, PhoebeHui commented on ports/oatpp/portfile.cmake
> +    vcpkg_copy_pdbs()
@mheyman, sorry for the confusing!

Yes, here is steps you can reference:
1. Create 6 separate ports for REPO oatpp/oatpp, oatpp/oatpp-curl, oatpp/oatpp-libressl, oatpp/oatpp-mbedtls, oatpp/oatpp-swagger, oatpp/oatpp-websocket
2.  Install oatpp, it already generated cmake config and targets file, keep them installed to ' installed/../share' directory, you can use vcpkg_fixup_cmake_targets function.
3. Add 'oatpp' to Build-Depends for others 5 ports(the others 5 libraries seems depend on oatpp)

2020-01-31 09:17 UTC, JackBoosY requested changes

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp-consul/portfile.cmake
> +message(STATUS "Building oatpp-consul")
Can you remove this debug info?

Thanks.

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp-curl/portfile.cmake
> +message(STATUS "Building oatpp-curl")
Can you remove this debug info?

Thanks.

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp-libressl/portfile.cmake
> +message(STATUS "Building oatpp-libressl")
Can you remove this debug info?

Thanks.

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp-mbedtls/portfile.cmake
> +message(STATUS "Building oatpp-mbedtls")
Can you remove this debug info?

Thanks.

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp-swagger/portfile.cmake
> +message(STATUS "Building oatpp-swagger")
Can you remove this debug info?

Thanks.

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp/portfile.cmake
> +message(STATUS "Building oatpp[core]")
Can you remove this debug info?

Thanks.

2020-01-31 09:17 UTC, JackBoosY commented on ports/oatpp-websocket/portfile.cmake
> +message(STATUS "Building oatpp-websocket")
Can you remove this debug info?

Thanks.

2020-02-08 13:48 UTC, mheyman commented on ports/oatpp-websocket/portfile.cmake
> +message(STATUS "Building oatpp-websocket")
Done - I originally thought the ports were supposed to have that because of a port I used as an example...

2020-02-10 11:16 UTC, JackBoosY approved these changes

2020-02-10 11:17 UTC, JackBoosY commented
LGTM, thanks for this PR!

2020-05-14 02:39 UTC, JackBoosY commented
/azp run

2020-05-15 20:34 UTC, strega-nil commented
Alright, this looks good to me. thanks @mheyman! :D

2020-05-15 20:34 UTC, merged