[libxlsxwriter] upgrade to 0.8.9
microsoft/vcpkg pull request #9410
Opened 2019-12-21 18:34 UTC by jmcnamara

Upgrade to the latest version of libxlsxwriter.

Closes #9408

2019-12-23 08:46 UTC, NancyLi1013 requested changes

2019-12-23 08:46 UTC, NancyLi1013 commented on ports/libxlsxwriter/portfile.cmake
>  if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
Could you also update copyright as the following content?
`file(INSTALL ${SOURCE_PATH}/License.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
`

2019-12-23 08:46 UTC, NancyLi1013 commented on ports/libxlsxwriter/0001-fix-cmake-file.patch
> +     DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
It seems that these changes are all from 001-fix-build-error.patch and 002-fix-uwp-build.patch. Why do you put them together and rename patch?

2019-12-23 14:10 UTC, ras0219-msft commented
/azp run

2019-12-23 14:40 UTC, jmcnamara commented on ports/libxlsxwriter/portfile.cmake
>  vcpkg_from_github(
Yes. Will do.

2019-12-23 14:40 UTC, jmcnamara commented on ports/libxlsxwriter/portfile.cmake
>  vcpkg_from_github(
Yes. Will do.

2019-12-23 14:40 UTC, jmcnamara commented on ports/libxlsxwriter/portfile.cmake
>  if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
Yes to both of these.

2019-12-23 14:42 UTC, jmcnamara commented on ports/libxlsxwriter/0001-fix-cmake-file.patch
> +     DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
I put them together since there are targeting the same file, for the same reason, for vcpkg compatibility.

Note, I'm working to remove these patches completely and merge the changes upstream.

2019-12-23 14:43 UTC, jmcnamara commented
@ras0219-msft 

> /azp run

What does this mean.

2019-12-23 14:45 UTC, jmcnamara commented on ports/libxlsxwriter/portfile.cmake
>  if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
> Could you update this as if (VCPKG_TARGET_IS_UWP) ?

Is this why the CI checks are failing?

2019-12-23 16:01 UTC, jmcnamara commented
> What does this mean.

I guess you were using it to re-trigger the CI.

2019-12-23 16:21 UTC, jmcnamara commented
I've made the required changes and force pushed to master to redo the PR.

Thanks for your help.

2019-12-24 06:05 UTC, NancyLi1013 approved these changes

2020-01-02 21:55 UTC, merged

2020-01-02 21:55 UTC, dan-shaw commented
Thanks for the PR!