[argumentum] Add argumentum
microsoft/vcpkg pull request #9478
Opened 2019-12-27 18:21 UTC by mmahnic

Argumentum is a library for parsing command line arguments. It can be used as a static library and as a header-only library. A dynamic version is planned for a future release.

    What does your PR fix? It adds a new port.

    Which triplets are supported/not supported? Have you updated the CI baseline?
    Tested only on x64-linux.

    Does your PR follow the maintainer guide?
    I believe so.

2019-12-30 05:57 UTC, NancyLi1013 requested changes

2019-12-30 05:57 UTC, NancyLi1013 commented on ports/argumentum/portfile.cmake
> +include( GNUInstallDirs )
`include( GNUInstallDirs )` should be not needed.
Could you please remove this?

2019-12-30 05:57 UTC, NancyLi1013 commented on ports/argumentum/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH ${CMAKE_INSTALL_LIBDIR}/cmake/Argumentum)
This line may be updated as
`vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/Argumentum)`.

2019-12-30 06:15 UTC, NancyLi1013 commented
Hi @mmahnic thanks for this PR.
I noticed that this port failed on `arm-uwp, x64-uwp, arm64-windows`.
Are those expected? If this port currently doesn't support `arm, arm64, uwp`, please add this to portfile.cmake.

`vcpkg_fail_port_install(ON_ARCH "arm" "arm64" ON_TARGET "uwp")
`
Besides this, please also update [ci.baseline.txt](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) with the following content:
```
argumentum:arm4-windows=fail
argumentum:x64-uwp=fail
argumentum:arm-uwp=fail
```
If not, please try to fix the failures.

2019-12-30 15:25 UTC, mmahnic commented on ports/argumentum/portfile.cmake
> +    REPO mmahnic/argumentum
This is the original repository.

2019-12-31 18:34 UTC, mmahnic commented on ports/argumentum/portfile.cmake
> +vcpkg_fixup_cmake_targets(CONFIG_PATH ${CMAKE_INSTALL_LIBDIR}/cmake/Argumentum)
I have applied all the suggested changes.

2020-01-02 01:38 UTC, NancyLi1013 approved these changes

2020-01-02 20:46 UTC, dan-shaw commented
/azp run

2020-01-02 21:40 UTC, merged

2020-01-02 21:41 UTC, dan-shaw commented
Thanks for the PR!