[vcpkg-msbuild-integration] Extending logic that decides between 'Release' and 'Debug' libraries by referring to $(UseDebugLibraries)
microsoft/vcpkg pull request #9496
Opened 2019-12-29 20:53 UTC by trueqbit

- Fixes issue #9495

_scripts/buildsystems/msbuild/vcpkg.targets_ should be extended to determine the build configuration in the following way:

```xml
<VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'true'">Debug</VcpkgNormalizedConfiguration>
<VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
<VcpkgNormalizedConfiguration Condition="'$(VcpkgNormalizedConfiguration)' == '' and $(VcpkgConfiguration.StartsWith('Debug'))">Debug</VcpkgNormalizedConfiguration>
<VcpkgNormalizedConfiguration Condition="'$(VcpkgNormalizedConfiguration)' == '' and ($(VcpkgConfiguration.StartsWith('Release')) or '$(VcpkgConfiguration)' == 'RelWithDebInfo' or '$(VcpkgConfiguration)' == 'MinSizeRel')">Release</VcpkgNormalizedConfiguration>
```

2020-01-03 02:44 UTC, JackBoosY commented
/azp run

2020-01-07 09:18 UTC, JackBoosY commented
/azp run

2020-01-09 09:00 UTC, JackBoosY commented
/azp run

2020-01-14 01:02 UTC, ras0219-msft requested changes

2020-01-14 01:02 UTC, ras0219-msft commented on scripts/buildsystems/msbuild/vcpkg.targets
> +    <VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
This should be chained onto the end of our current logic, instead of overriding it (i.e. only check UseDebugLibraries if our other checks fail).

2020-01-23 16:41 UTC, trueqbit commented on scripts/buildsystems/msbuild/vcpkg.targets
> +    <VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
Why would you do that?
Note that I don't override it - it's ordered first, then the string-based logic follows. The goal of this PR is to be independent of the actual configuration name, unless UseDebugLibraries would be undefined.

2020-01-23 19:09 UTC, ras0219-msft commented on scripts/buildsystems/msbuild/vcpkg.targets
> +    <VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
The problem with this is that it potentially results in different behavior for existing users.

I assume your use case is having a configuration that isn't named "Debug" nor "Release", and so you want the setting to be inherited from `UseDebugLibraries`. In this case, chaining the new logic _after_ the existing settings (such that it only activates if the configuration isn't named Debug or Release) will preserve our existing semantics as much as reasonable while also enabling your scenario.

2020-01-24 10:01 UTC, trueqbit commented on scripts/buildsystems/msbuild/vcpkg.targets
> +    <VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
I understand your concern. Though, how exactly would it affect existing users (see 2.)?

I have three strong motivators for my change:
  1. It's about correctness: the presumption is that `UseDebugLibraries` is set correctly - after all MSBuild's default build mechanism has switches on it. It follows that it's the most accurate and correct way to determine whether the debug or release runtime should be used.
    Ordering the `UseDebugLibraries` condition after the string-based ones doesn't offer any benefits.
  2. I do presume that the way the current string comparisons are performed, align with how `UseDebugLibraries` is already set in the first place [i.e. `"Debug" == UseDebugLibraries`, `"Release" or "RelWithDebInfo" or "MinSizeRel" == not UseDebugLibraries`]. I don't see how it changes semantics and how it would negatively affect existing users.
  3. A 'personal' must-have: Historically, I have a configuration named "DebugRelease", which turns off all optimizations but links to the release runtime. There's no way to override vcpkg's existing logic.

Now, if we can't agree on this I don't see any reason to integrate the PR. It wouldn't solve any user's problem and certainly not mine, as I am left stuck with my own fork (of course I can rename my configuration, but I stand to my viewpoint that `UseDebugLibraries` remains the most accurate way).

If still unsure about `UseDebugLibraries` itself, how about contacting the MSBuild team?

2020-05-14 02:42 UTC, JackBoosY commented on scripts/buildsystems/msbuild/vcpkg.targets
> +    <VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
@trueqbit Sorry, you can go to slack to contact us. #9184.

2020-07-09 22:05 UTC, BillyONeal commented
I think the recent steps to ensure the use can set VcpkgTargetTriplet themselves obsoletes this change.

2020-07-09 22:08 UTC, ras0219-msft commented
This is manipulating the Configuration, not the Triplet. We should investigate improving exposure of the Configuration to users.

2020-10-27 09:02 UTC, closed without merging

2021-12-18 17:06 UTC, trueqbit commented
Please see continuation #22086