reproc: Update to v10.0.0.
microsoft/vcpkg pull request #9544
Opened 2020-01-03 17:56 UTC by DaanDeMeyer

2020-01-06 06:06 UTC, PhoebeHui requested changes

2020-01-06 17:31 UTC, DaanDeMeyer commented on ports/reproc/CONTROL
> +Version: 10.0.0
My bad, fixed.

2020-01-07 01:25 UTC, PhoebeHui approved these changes

2020-01-08 21:44 UTC, vicroms commented
/azp run

2020-01-09 00:35 UTC, dan-shaw commented
/azp run

2020-01-09 22:34 UTC, merged