[soem] add v1.4.0 port
microsoft/vcpkg pull request #9572
Opened 2020-01-07 08:33 UTC by seanyen

Add a new port `SOEM` - https://github.com/OpenEtherCATsociety/SOEM.

2020-01-07 09:53 UTC, NancyLi1013 requested changes

2020-01-07 09:53 UTC, NancyLi1013 commented on ports/soem/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

2020-01-07 09:53 UTC, NancyLi1013 commented on ports/soem/portfile.cmake
> +file(RENAME ${CURRENT_PACKAGES_DIR}/share/soem/LICENSE ${CURRENT_PACKAGES_DIR}/share/soem/copyright)
Could you update this
```
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/soem)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/soem/LICENSE ${CURRENT_PACKAGES_DIR}/share/soem/copyright)
```
as `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright) `?

2020-01-07 18:56 UTC, seanyen commented
@NancyLi1013 Thanks for the feedback. I have made the respective changes.

2020-01-09 01:22 UTC, NancyLi1013 commented
/azp run

2020-01-10 02:14 UTC, NancyLi1013 commented
Hi @seanyen thanks for this PR.
I noticed that this port failed on` x64-uwp` and `arm-uwp` triplets from CI system.
Are these expected? If not, please try to fix them.

If this port doesn't support arm, please add `vcpkg_fail_port_install(ON_TARGET "UWP")` to the top of `portfile.cmake`.
Also update [baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) with the following content:
```
soem:x64-uwp=fail
soem:arm-uwp=fail
```

2020-01-10 08:57 UTC, PhoebeHui requested changes

2020-01-10 08:57 UTC, PhoebeHui commented on ports/soem/CONTROL
> +Version: 1.4.0-1
The revision should be 1.4.0

2020-01-10 08:57 UTC, PhoebeHui commented on ports/soem/portfile.cmake
> +)
You can use follow code instead.
```
  vcpkg_from_github(
        OUT_SOURCE_PATH SOURCE_PATH
        REPO OpenEtherCATsociety/SOEM
        REF abbf0d42e38d6cfbaa4c1e9e8e07ace651c386fd #v1.4.0
        SHA512 2967775c6746bb63becea5eb12f136c184bbf874e1e5e8753374bfc212ec9cefbf1159350e79627b978af3562d261b61c50f38936a425c4d9c70598a1d136817
        HEAD_REF master
        PATCHES 
             winpcap.patch
    )
```

2020-01-13 23:33 UTC, seanyen commented
@NancyLi1013 @PhoebeHui Thanks for the feedback. I have revised this PR respectively.

2020-01-14 07:46 UTC, PhoebeHui approved these changes

2020-01-14 20:28 UTC, vicroms commented
Thanks for the PR!

2020-01-14 20:28 UTC, merged