[moltenvk] add new port
microsoft/vcpkg pull request #9575
Opened 2020-01-07 19:46 UTC by magicfoo

Add new port for moltenVK library.
This port only supports macOS platform to provide a compliant API to Vulkan based on native Metal.

2020-01-08 06:12 UTC, NancyLi1013 requested changes

2020-01-08 06:12 UTC, NancyLi1013 commented on ports/moltenvk/portfile.cmake
> +include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

2020-01-08 06:12 UTC, NancyLi1013 commented on ports/moltenvk/portfile.cmake
> +vcpkg_fail_port_install(ON_TARGET "WINDOWS" "LINUX" "UWP" "ANDROID" "FREEBSD")
Since both `ANDROID` and `FREEBSD` belong to `LINUX`.
We can remove these two items from `ON_TARGET`.

2020-01-08 06:12 UTC, NancyLi1013 commented on ports/moltenvk/portfile.cmake
> +    REF bf3ffff4bb2496e2dfa300bf5d869de95e5bc372
Is the commit id from v1.0.38? I noticed that v1.0.39 has been released. Why do you not use the latest version?

2020-01-08 06:17 UTC, NancyLi1013 commented
Hi @magicfoo thanks for this PR.
Since this port only supports macOS platform. Please update [baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) with the following content:
```
moltenvk:x86-windows=fail
moltenvk:x64-windows=fail
moltenvk:x64-windows-static=fail
moltenvk:x64-uwp=fail
moltenvk:arm-uwp=fail
moltenvk:arm64-windows=fail
moltenvk:x64-linux=fail
```

2020-01-09 00:00 UTC, magicfoo commented on ports/moltenvk/portfile.cmake
> +    REF bf3ffff4bb2496e2dfa300bf5d869de95e5bc372
IMHO it is more risky to automatically use the latest version as the port file could be obsolete quickly due. Better, IMHO again, to be in favor of more stability in vcpkg with manual update of packages and related port files ... As a user, I don't like things that break frequently for no good reason. Most of the time, users don't need latest version/ features, except for bug fixes requiring a manual update. TBD

2020-01-09 00:02 UTC, magicfoo commented on ports/moltenvk/portfile.cmake
> +# after running some local build tests with more recent updates.
this port is intentionally locked to a stable version known to build properly.

2020-01-09 01:26 UTC, NancyLi1013 commented
/azp run

2020-01-10 02:25 UTC, NancyLi1013 commented
I noticed that this port failed on OSX pipeline.
I get this info from CI system in `fetch-dependencies-x64-osx-rel-err.log`
```
HEAD is now at 204cd13 Merge pull request #134 from Tobski/patch-1
fetchDependencies: line 109: cmake: command not found
```
Could you please check this?

2020-01-10 15:47 UTC, magicfoo commented
> I noticed that this port failed on OSX pipeline.
> I get this info from CI system in `fetch-dependencies-x64-osx-rel-err.log`
> 
> ```
> HEAD is now at 204cd13 Merge pull request #134 from Tobski/patch-1
> fetchDependencies: line 109: cmake: command not found
> ```
> 
> Could you please check this?

Do you have more details please? It doesn't fail on my laptop. MoltenVK needs xcode 11.3 (catalina). Note that from my tests, few ports including glib will start failing with the new xcode 11.3. My other PR fixes by the way.

2020-01-14 09:24 UTC, NancyLi1013 commented
Thanks for your feedback.
I will rerun and let's wait for the new test result from CI system.

2020-01-14 09:24 UTC, NancyLi1013 commented
/azp run

2020-01-21 10:13 UTC, NancyLi1013 commented
/azp run

2020-02-03 13:43 UTC, NancyLi1013 commented
It seems that it still failed on osx pipeline.

2020-02-20 02:10 UTC, NancyLi1013 commented
Hi @magicfoo 
Could you please resolve the conflicts?

2020-03-05 05:25 UTC, NancyLi1013 commented
Pinging @magicfoo 
 Is work still being done for this PR?

2020-04-16 05:49 UTC, NancyLi1013 commented
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

2020-04-16 05:49 UTC, closed without merging