Upgrade to v1.4.0
microsoft/vcpkg pull request #9609
Opened 2020-01-09 18:31 UTC by cnbatch

**Describe the pull request**

- What does your PR fix? Fixes issue #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

2020-01-10 07:54 UTC, PhoebeHui requested changes

2020-01-10 07:54 UTC, PhoebeHui commented on ports/xlnt/portfile.cmake
> +endif()
This is deprecated, could you please update it? 
 
```
if(VCPKG_TARGET_IS_WINDOWS)
     set(win_patch "static-linking-for-windows.patch")
endif()

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO tfussell/xlnt
    REF v1.4.0
    SHA512 74abbee97994098fb7d8fd0839929db74fe01b8428f8bdb8edd28340d3b3ed04d4c7d6dd5d886ae766054ff1b0fe9a8275098a1462e7a5146ff09f1cdb063360
    HEAD_REF master
    PATCHES
        ${win_patch}
)
```

2020-01-10 07:54 UTC, PhoebeHui commented on ports/xlnt/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/xlnt RENAME copyright)
We usually use 'file(INSTALL ${SOURCE_PATH}/LICENSE.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)' instead.

2020-01-10 08:38 UTC, cnbatch commented on ports/xlnt/portfile.cmake
> +file(INSTALL ${SOURCE_PATH}/LICENSE.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/xlnt RENAME copyright)
Thanks for reviewing. New changes are made to portfile.cmake file.

2020-01-13 02:27 UTC, PhoebeHui approved these changes

2020-01-13 03:08 UTC, JackBoosY approved these changes

2020-01-14 02:40 UTC, JackBoosY commented
/azp run

2020-01-15 20:16 UTC, merged