[glad] Update to 0.1.33
microsoft/vcpkg pull request #9627
Opened 2020-01-11 06:24 UTC by crackedmind

2020-01-13 02:24 UTC, NancyLi1013 requested changes

2020-01-13 02:24 UTC, NancyLi1013 commented on ports/glad/CONTROL
> +Version: 0.1.33
Could you please add homepage here?
`Homepage: https://github.com/Dav1dde/glad`

2020-01-13 02:24 UTC, NancyLi1013 commented on ports/glad/portfile.cmake
>  vcpkg_from_github(
`include(vcpkg_common_functions)` is no longer needed. 
Could you please remove this line?

2020-01-13 02:24 UTC, NancyLi1013 commented on ports/glad/portfile.cmake
Could you update `configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/glad/copyright COPYONLY)` as
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)?`

2020-01-13 02:24 UTC, NancyLi1013 commented
/azp run

2020-01-13 07:11 UTC, NancyLi1013 approved these changes

2020-01-13 19:56 UTC, ras0219-msft commented
/azp run

2020-01-15 00:28 UTC, vicroms approved these changes

2020-01-15 18:32 UTC, merged