[freeglut] check whether debug/release is enabled before moving files
microsoft/vcpkg pull request #9745
Opened 2020-01-18 09:36 UTC by theblackunknown

When using custom triplet which request to only build debug or release flavor this ports fails

- What does your PR fix?
It fixes the issue by checking what VCPKG has been asked to build

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

2020-01-19 06:08 UTC, JackBoosY requested changes
Can you update version in file _CONTROL_?
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

2020-01-19 08:04 UTC, theblackunknown commented
Hi @JackBoos, just to be sure I should update the control file to indicate that I have patched the port right ? (i.e. -1)

2020-01-19 08:07 UTC, JackBoosY commented
@theblackunknown You should change it to `3.0.0-9`.

2020-01-19 12:08 UTC, theblackunknown commented
@JackBoosY PR updated

2020-01-20 02:37 UTC, JackBoosY approved these changes

2020-01-20 02:37 UTC, JackBoosY commented
LGTM, thanks!
I will rerun windows pipeline test after #9725 merged.

2020-01-30 22:40 UTC, merged

2020-01-30 22:40 UTC, vicroms commented
Thanks for the PR!