[open62541] Update to v1.0
microsoft/vcpkg pull request #9767
Opened 2020-01-20 12:56 UTC by yurybura

[open62541] Update to v1.0

Fixes #9766

2020-01-20 13:01 UTC, traversaro commented
Thanks @yurybura for working on this. 

As the dependency on python six was dropped in https://github.com/iit-danieli-joint-lab/idjl-software/pull/725 , I guess we can now also remove all the code necessary to install `six`, see https://github.com/microsoft/vcpkg/pull/9767/files#diff-d7c83a3acc5f48906322217e14675fe7L36 .

2020-01-20 13:26 UTC, yurybura commented
Hi @traversaro
Thanks for comment. Unfortunately your link is unavailable. I'll try to remove python-six after my investigations.

2020-01-20 14:59 UTC, traversaro commented
> 
> 
> Hi @traversaro
> Thanks for comment. Unfortunately your link is unavailable. I'll try to remove python-six after my investigations.

Sorry, I had copy pasted the wrong comment. The correct one is https://github.com/open62541/open62541/pull/2493 .

2020-01-20 16:43 UTC, yurybura commented
Requires #9752 merge to fix Windows CI...

2020-01-20 19:48 UTC, cenit commented on ports/open62541/portfile.cmake
>  vcpkg_find_acquire_program(PYTHON3)
Also this part should not be required anymore, right?

2020-01-20 20:46 UTC, yurybura commented on ports/open62541/portfile.cmake
>  vcpkg_find_acquire_program(PYTHON3)
No, Python is still required to build.
CMakeLists.txt contains:
`find_package(PythonInterp REQUIRED)`

2020-01-21 03:18 UTC, NancyLi1013 requested changes

2020-01-21 03:18 UTC, NancyLi1013 commented on ports/open62541/CONTROL
>  Description: open62541 is an open source C (C99) implementation of OPC UA licensed under the Mozilla Public License v2.0.
Could you please add homepage here?

2020-01-21 03:18 UTC, NancyLi1013 commented on ports/open62541/portfile.cmake
>  include(vcpkg_common_functions)
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

2020-01-21 03:18 UTC, NancyLi1013 commented on ports/open62541/portfile.cmake
>  endif()
This can be updated as` vcpkg_fail_port_install(ON_TARGET "UWP")`.

2020-01-21 03:18 UTC, NancyLi1013 commented on ports/open62541/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME ${PORT})
`vcpkg_test_cmake()` is deprecated.
Could you remove it?

2020-01-21 04:36 UTC, yurybura commented on ports/open62541/CONTROL
>  Description: open62541 is an open source C (C99) implementation of OPC UA licensed under the Mozilla Public License v2.0.
Added.

2020-01-21 04:37 UTC, yurybura commented on ports/open62541/portfile.cmake
>  include(vcpkg_common_functions)
Fixed.

2020-01-21 04:37 UTC, yurybura commented on ports/open62541/portfile.cmake
>  endif()
Fixed.

2020-01-21 04:37 UTC, yurybura commented on ports/open62541/portfile.cmake
> +vcpkg_test_cmake(PACKAGE_NAME ${PORT})
Removed.

2020-01-21 04:39 UTC, yurybura commented
@NancyLi1013 thank you for review! I've fixed issues.

2020-01-21 05:40 UTC, NancyLi1013 approved these changes

2020-01-21 06:16 UTC, JackBoosY requested changes

2020-01-21 06:16 UTC, JackBoosY commented on ports/open62541/portfile.cmake
> -    message("${PORT} currently requires the following tools from the system package manager:\n    python-six\n\nThis can be installed on Ubuntu systems via apt-get install python-six python3-six (dep
Can you be sure again that the port does not depend on `python-six` and `python3-six` now?

2020-01-21 07:25 UTC, yurybura commented on ports/open62541/portfile.cmake
> -    message("${PORT} currently requires the following tools from the system package manager:\n    python-six\n\nThis can be installed on Ubuntu systems via apt-get install python-six python3-six (dep
According to open62541/open62541#2493 dependency to python-six was removed 6 months ago. Anyway I'll check in the sources.

2020-01-21 08:39 UTC, yurybura commented on ports/open62541/portfile.cmake
> -    message("${PORT} currently requires the following tools from the system package manager:\n    python-six\n\nThis can be installed on Ubuntu systems via apt-get install python-six python3-six (dep
I can confirm that python-six dependency was removed in v1.0.

2020-01-21 08:54 UTC, JackBoosY approved these changes

2020-01-21 20:25 UTC, vicroms commented
Thanks @yurybura for the PR and everyone that helped review it!

2020-01-21 20:25 UTC, merged