[boost-python] Try to fix build issue on Linux
microsoft/vcpkg pull request #9780
Opened 2020-01-21 09:09 UTC by yurybura

This PR allows install and use Python3 dependency on Linux and OSX.

Fixes #9764

2020-01-22 01:41 UTC, PhoebeHui commented
@yurybura, the CI on linux passed due to 'boost-python:x64-linux=ignore' added to https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt#L164, could you please remove it from ci baseline?

2020-01-22 08:35 UTC, yurybura commented
@PhoebeHui `boost_modular_build()` doesn't configure Python on Linux. Let me try to fix it first. Please add WIP label for this PR. Thanks.

2020-01-23 04:56 UTC, yurybura commented
Dear @PhoebeHui, could you start reviewing of this PR? I have just finished fixing this issue.

I think  Boost's CMake scripts should be reworked to merge in one for all platforms in separate PR...

2020-01-23 07:35 UTC, yurybura commented
Build bot has failed but this fail isn't related to my changes... CI quite unstable again.

2020-02-02 13:39 UTC, adamvm commented
@yurybura ready :)

2020-02-02 13:52 UTC, yurybura commented
@adamvm Thank you.
@PhoebeHui Please start review of this PR.

2020-02-03 04:09 UTC, PhoebeHui requested changes
@yurybura, thanks for the updates!

2020-02-03 04:09 UTC, PhoebeHui commented on ports/boost-modular-build-helper/boost-modular-build.cmake
> +                "-DCURRENT_INSTALLED_DIR=${CURRENT_INSTALLED_DIR}"
@yurybura, Is this needed?  where does them use? it looks they are environment variables, it should recognize them.

2020-02-03 05:57 UTC, yurybura commented on ports/boost-modular-build-helper/boost-modular-build.cmake
> +                "-DCURRENT_INSTALLED_DIR=${CURRENT_INSTALLED_DIR}"
File user-config.jam file requires these variables. CMake configures this file on Linux too:
https://github.com/microsoft/vcpkg/blob/070f37693c2d8044c363be03ddbb84dba8367c51/ports/boost-modular-build-helper/CMakeLists.txt#L115

vcpkg_configure_cmake() runs second instance of CMake where these variables aren't defined and configuration of user-config.jam doesn't work correctly. I pass these variables to this second CMake instance.

2020-02-04 06:49 UTC, PhoebeHui commented
@ras0219-msft, could you help review?

2020-02-04 06:51 UTC, PhoebeHui approved these changes
LGTM

2020-02-10 06:52 UTC, zlojvavan commented
how to apply the fix?

2020-02-18 12:29 UTC, PhoebeHui commented
@ras0219-msft, could you priority to review this PR?

2020-02-26 01:21 UTC, strega-nil commented on ports/boost-modular-build-helper/user-config.jam
> +    lib icudt : : <file>"@CURRENT_INSTALLED_DIR@/debug/lib/icudtd.lib" <variant>debug : : ;
What do these changes mean?

2020-02-26 12:02 UTC, yurybura commented on ports/boost-modular-build-helper/boost-modular-build.cmake
> +            list(APPEND configure_option "-DVCPKG_PYTHON_VERSION=${VCPKG_PYTHON_VERSION}")
All variables have different names. This isn't code duplicate.

2020-02-26 12:05 UTC, yurybura commented on ports/boost-modular-build-helper/user-config.jam
> +        ;
@strega-nil, I want to have the same formatting like for lines 13-21.

2020-02-26 12:07 UTC, yurybura commented on ports/boost-modular-build-helper/user-config.jam
> +    lib icudt : : <file>"@CURRENT_INSTALLED_DIR@/debug/lib/icudtd.lib" <variant>debug : : ;
@strega-nil, This changes fixes build boost-regex[icu] on Linux.

2020-03-01 09:46 UTC, yurybura commented
@PhoebeHui, @strega-nil, @ras0219-msft
Ping. Please have a look this PR.

2020-03-02 06:59 UTC, PhoebeHui approved these changes

2020-03-02 18:41 UTC, strega-nil commented
I'm happy with this! Thanks @yurybura, this is really awesome :)

2020-03-02 18:41 UTC, merged

2020-03-04 20:32 UTC, cenit commented
Hi! Thanks for the PR, but... boost-python was broken on Linux but still is... at least for me. 
Installing the python3 dependency fails with an error message telling the dev that to build out of tree the source must be clean (at install phase). Of course, buildtrees folder was removed before installing.

2020-03-04 20:50 UTC, yurybura commented
@cenit, looks like it is a python3 port issue. Could you report a separate bug report for this?