[luajit] Copy tool dependencies
microsoft/vcpkg pull request #9782
Opened 2020-01-21 15:53 UTC by SeekingMeaning

**Describe the pull request**

- What does your PR fix? Fixes issue #N/A

Fixes luajit tool error on run

- Which triplets are supported/not supported? Have you updated the CI baseline?

Same as before; no update necessary

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-01-22 05:22 UTC, JackBoosY requested changes

2020-01-22 05:22 UTC, JackBoosY commented on ports/luajit/portfile.cmake
> +        file(COPY ${CURRENT_PACKAGES_DIR}/debug/bin/lua51.dll DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
Why not use vcpkg_copy_tool_dependencies here?

2020-01-22 14:54 UTC, SeekingMeaning commented on ports/luajit/portfile.cmake
> +        file(COPY ${CURRENT_PACKAGES_DIR}/debug/bin/lua51.dll DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
It copies dependencies for release, but not debug.

2020-01-23 03:54 UTC, JackBoosY approved these changes

2020-01-23 21:28 UTC, cenit commented on ports/luajit/portfile.cmake
> +        file(COPY ${CURRENT_PACKAGES_DIR}/debug/bin/lua51.dll DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
Installing debug tools would be something unusual (read: new) on vcpkg. Is it necessary?

2020-01-27 22:59 UTC, merged