[cairo] fix export symbols on dynamic libraries for macOS
microsoft/vcpkg pull request #9800
Opened 2020-01-23 12:17 UTC by angelmixu

Fixed exporting symbols by changing the definition for macOS dynamic libraries (and probably Linux too).

2020-01-26 23:36 UTC, angelmixu commented
The error is:

> qwinjumplist.cpp
C:\vsts\_work\1\s\buildtrees\qt5-winextras\src\5.12.5-99fbd09e12\src\winextras\qwinfunctions.cpp(2045): fatal error C1051: program database file, 'C:\vsts\_work\1\s\buildtrees\qt5-winextras\x64-windows-dbg\src\winextras\.obj\debug\Qt5WinExtrasd.vc.pdb', has an obsolete format, delete it and recompile

As far as I can see, the error is not retaled to this change, isn't, it? :/

2020-02-04 08:39 UTC, LilyWangL approved these changes

2020-02-04 23:22 UTC, ras0219-msft requested changes
Thanks for the PR! LGTM after we resolve my one comment.

2020-02-04 23:22 UTC, ras0219-msft commented on ports/cairo/CMakeLists.txt
> +	    PROPERTIES COMPILE_DEFINITIONS "cairo_public=__declspec(dllexport)")
This difference is actually MSVC vs GCC/Clang; it would probably be better to use `if(MSVC)` instead of `if(WINDOWS)`

2020-02-06 09:38 UTC, angelmixu commented on ports/cairo/CMakeLists.txt
> +	    PROPERTIES COMPILE_DEFINITIONS "cairo_public=__declspec(dllexport)")
changed, thanks for the suggestion! :)

2020-02-06 23:06 UTC, ras0219-msft commented
Thanks for the fix!

2020-02-06 23:06 UTC, merged