[scripts] add PKG_CONFIG_PATHS to vcpkg_configure_make
microsoft/vcpkg pull request #9863
Opened 2020-01-31 14:12 UTC by Neumann-A

required for autoconf with pkgconfig calls to find dependent libraries correctly.

I am wondering if `<CURRENT_INSTALLED_DIR>(/debug)/lib/pkgconfig` should be added by default.

2020-02-01 01:44 UTC, JackBoosY commented
Maybe we need to modify a port to test?

2020-02-01 01:56 UTC, JackBoosY requested changes

2020-02-01 01:56 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_make.cmake
> +##     [OPTIONS_DEBUG <-DDEBUGGABLE=1>...]+
This `+` seems like text?

2020-02-01 01:56 UTC, JackBoosY commented on scripts/cmake/vcpkg_configure_make.cmake
> +                    LOGNAME prerun-2-${TARGET_TRIPLET}-dbg
Why change log name here?

2020-02-01 13:08 UTC, Neumann-A commented on scripts/cmake/vcpkg_configure_make.cmake
> +                    LOGNAME prerun-2-${TARGET_TRIPLET}-dbg
- first of `${TAR_TRIPLET_DIR}` was not defined here. (but is later in the release case)
- second it was overwriting the PRERUN shell log with the same name. 

The whole file could use some refactoring but this was not my aim here

2020-02-03 06:09 UTC, JackBoosY approved these changes

2020-02-10 13:20 UTC, Neumann-A commented
After thinking about it.
`<CURRENT_INSTALLED_DIR>(/debug)/lib/pkgconfig`
should be included by default to the pkgconfig search path in the corresponding configure scripts as such this PR seems unnecessary.

2020-02-10 13:20 UTC, closed without merging