[protobuf]: upgrade to v3.11.3
microsoft/vcpkg pull request #9889
Opened 2020-02-03 13:38 UTC by coryan

Upgrade protobuf to v3.11.3, this release includes important fixes for protobuf generated code on Windows.

- Which triplets are supported/not supported? Have you updated the CI baseline?

Same triplets as before, no need to update the ci baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I believe so.

2020-02-03 16:16 UTC, coryan commented
The Windows x86 failure (`azure-kinect-sensor-sdk`) seems unrelated, it is not even an indirect dependency of protobuf.

Likewise, the macOS (osx) failures seem unrelated.

2020-02-04 02:30 UTC, LilyWangL requested changes

2020-02-04 02:30 UTC, LilyWangL commented on ports/protobuf/portfile.cmake
>  vcpkg_from_github(
`include(vcpkg_common_functions)` is deprecated. Please remove it.

2020-02-04 02:32 UTC, LilyWangL commented
/azp run

2020-02-04 15:15 UTC, coryan commented on ports/protobuf/portfile.cmake
>  vcpkg_from_github(
Done.

2020-02-05 13:39 UTC, coryan commented
Rebased to pick up fixes from `master`.

2020-02-06 09:39 UTC, LilyWangL approved these changes

2020-02-06 22:59 UTC, ras0219-msft commented
Thanks as always, @coryan!

2020-02-06 22:59 UTC, merged