[avro-c] Fix build error on Linux
microsoft/vcpkg pull request #9898
Opened 2020-02-04 04:20 UTC by LilyWangL

Fix function find_package in CMakeLists.txt and incorrect function in source file.
There are no features need to test.
Related issue: #9841

2020-02-04 05:00 UTC, JackBoosY approved these changes

2020-02-04 06:57 UTC, PhoebeHui commented
@LilyWangL, Could you update CI baseline file?

2020-02-08 01:40 UTC, ras0219-msft requested changes

2020-02-08 01:40 UTC, ras0219-msft commented on ports/avro-c/fix-dependency.patch
> +-    add_definitions(-DDEFLATE_CODEC)
Without these defines (`-DDEFLATE_CODEC`) and includes (`${ZLIB_INCLUDE_DIR}`), the package is is not being used.

Instead, the original `find_package()` commands should be modified to be `REQUIRED` and potentially have their include/link commands adjusted. For example, the zlib section should probably be modified to use `link_libraries(ZLIB::ZLIB)` instead of `include_directories(${ZLIB_INCLUDE_DIR})`.

2020-02-20 06:12 UTC, LilyWangL commented
/azp run

2020-03-19 10:19 UTC, LilyWangL commented
The port avro-c has been updated to version 1.9.2 in PR #10380, and it doesn't support triplet `uwp` `Linux` `OSX`. So closed this PR.

2020-03-19 10:19 UTC, closed without merging