[farmhash] Add new port
microsoft/vcpkg pull request #9929
Opened 2020-02-05 16:42 UTC by kreuzerkrieg

Google FarmHash

- Which triplets are supported/not supported? 
uwp and arm on windows are not supported
Have you updated the CI baseline?
yes

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

2020-02-06 02:37 UTC, NancyLi1013 requested changes

2020-02-06 02:37 UTC, NancyLi1013 commented on ports/farmhash/CONTROL
> +Version: 1.1
Where do you get the version 1.1? I noticed that there is no released version now.
In this case, we should use a date(such as 2020-02-06) as the version here.

2020-02-06 02:37 UTC, NancyLi1013 commented on ports/farmhash/portfile.cmake
> +        REF master
We should use commit id(such as the latest commit `0d859a811870d10f53a594927d0d0b97573ad06d`) in `REF`.
Could you please update it?

2020-02-06 05:34 UTC, kreuzerkrieg commented on ports/farmhash/CONTROL
> +Version: 1.1
README
> FarmHash, a family of hash functions.
> Version 1.1
> 
> Introduction
> ============

2020-02-06 07:40 UTC, NancyLi1013 commented
Hi @kreuzerkrieg thanks for this PR.
The regressions on x86-windows, x64-windows, x64-windows triplets:
```
Can't load '/usr/lib/perl5/core_perl/auto/POSIX/POSIX.dll' for module POSIX: No such process at /usr/share/perl5/core_perl/XSLoader.pm line 93.
  at /usr/lib/perl5/core_perl/POSIX.pm line 24.
Compilation failed in require at /usr/share/autoconf/Autom4te/FileUtils.pm line 266.
BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 266.
Compilation failed in require at /usr/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /usr/bin/autoreconf line 42.
```
Could you please take a look and try to fix them?

2020-02-06 08:36 UTC, kreuzerkrieg commented
> Hi @kreuzerkrieg thanks for this PR.
> The regressions on x86-windows, x64-windows, x64-windows triplets:
> 
> ```
> Can't load '/usr/lib/perl5/core_perl/auto/POSIX/POSIX.dll' for module POSIX: No such process at /usr/share/perl5/core_perl/XSLoader.pm line 93.
>   at /usr/lib/perl5/core_perl/POSIX.pm line 24.
> Compilation failed in require at /usr/share/autoconf/Autom4te/FileUtils.pm line 266.
> BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 266.
> Compilation failed in require at /usr/bin/autoreconf line 42.
> BEGIN failed--compilation aborted at /usr/bin/autoreconf line 42.
> ```
> 
> Could you please take a look and try to fix them?

Dont have a win machine at hand right now, will check it later

2020-02-07 16:14 UTC, kreuzerkrieg commented
> Hi @kreuzerkrieg thanks for this PR.
> The regressions on x86-windows, x64-windows, x64-windows triplets:
> Can't load '/usr/lib/perl5/core_perl/auto/POSIX/POSIX.dll' for module POSIX: No such process at /usr/share/perl5/core_perl/XSLoader.pm line 93.
>   at /usr/lib/perl5/core_perl/POSIX.pm line 24.
> Compilation failed in require at /usr/share/autoconf/Autom4te/FileUtils.pm line 266.
> BEGIN failed--compilation aborted at /usr/share/autoconf/Autom4te/FileUtils.pm line 266.
> Compilation failed in require at /usr/bin/autoreconf line 42.
> BEGIN failed--compilation aborted at /usr/bin/autoreconf line 42.
> 
> Could you please take a look and try to fix them?

Ok, checked it. Well, I didnt get same messages but it clearly cant be compiled on Windows, at least I dont see it happening without intervention in the original autotools script
Meanwhile I've disabled builds for win/uwp for all architectures and all builds for arm

2020-02-12 22:44 UTC, merged

2020-02-12 22:45 UTC, ras0219-msft commented
Thanks for the PR!

This is fine for now, however looking at the upstream sources it seems that the build process is actually very simple for the library -- just `src/farmhash.cc` and `src/farmhash.h`. A very nice improvement would be to add a CMake replacement buildsystem, which would enable compiling for more targets and easier tweaking of flags for users (such as passing `-march`).